DayZ: PPEManagerStatic Class Reference
PPEManagerStatic Class Reference
Static component of PPE manager, used to hold the instance.
Static Private Member Functions
static void CreateManagerStatic ()
static void DestroyManagerStatic ()
static PPEManager GetPPEManager ()
Returns the manager instance singleton.
Static Private Attributes
static ref PPEManager m_Manager
Detailed Description
Static component of PPE manager, used to hold the instance.
Definition at line 2 of file PPEManager.c.
Member Function Documentation
CreateManagerStatic()
static void PPEManagerStatic::CreateManagerStatic () inline static private
Definition at line 6 of file PPEManager.c.
  {
    if (m_Manager)
    {
      Debug.Log("PPEManagerStatic | CreateManagerStatic - PPEManager already exists");
      return;
    }
    m_Manager = new PPEManager;
  }
References Debug::Log(), m_Manager, and PPEManager().
Referenced by CGame::DayZGame().
DestroyManagerStatic()
static void PPEManagerStatic::DestroyManagerStatic () inline static private
Definition at line 17 of file PPEManager.c.
  {
    if (m_Manager)
    {
      m_Manager.Cleanup();
      delete m_Manager;
    }
  }
References m_Manager.
Referenced by CGame::~DayZGame().
GetPPEManager()
static PPEManager PPEManagerStatic::GetPPEManager () inline static private
Returns the manager instance singleton.
Definition at line 27 of file PPEManager.c.
  {
    return m_Manager;
  }
References m_Manager.
Referenced by BleedingIndicatorDropData::AdjustColorSaturation(), CGame::DeferredInit(), PPEClassBase::Init(), CGame::LoadingHide(), PPEMatClassParameterColor::ModifyResultValues(), MissionBase::OnMissionFinish(), ManBase::OnSelectPlayer(), PPERequesterBase::RelativizeValue(), PPERequesterBase::SendCurrentValueData(), PPERequesterBase::SetRequesterUpdating(), ActionTargetsCursor::Update(), PPEMatClassParameterCommandData::Update(), DayZIntroScene::~DayZIntroScene(), and DayZIntroSceneXbox::~DayZIntroSceneXbox().
Member Data Documentation
m_Manager
ref PPEManager PPEManagerStatic::m_Manager static private
Definition at line 4 of file PPEManager.c.
Referenced by CreateManagerStatic(), DestroyManagerStatic(), and GetPPEManager().
The documentation for this class was generated from the following file:
scripts/3_Game/PPEManager/PPEManager.c