DayZ: CAContinuousCraft Class Reference
CAContinuousCraft Class Reference
Private Member Functions
override void Setup (ActionData action_data)
override int Execute (ActionData action_data)
override float GetProgress ()
Private Member Functions inherited from CAContinuousTime
void CAContinuousTime (float time_to_complete_action)
override void Setup (ActionData action_data)
override int Execute (ActionData action_data)
override int Cancel (ActionData action_data)
override float GetProgress ()
Additional Inherited Members
Private Attributes inherited from CAContinuousTime
float m_LocalTimeElpased
float m_TimeElpased
float m_AdjustedTimeToComplete
float m_DefaultTimeToComplete
ref Param1< float > m_SpentUnits
Detailed Description
Definition at line 1 of file CAContinuousCraft.c.
Member Function Documentation
Execute()
override int CAContinuousCraft::Execute (ActionData action_data) inline private
Definition at line 28 of file CAContinuousCraft.c.
  {
    if (!action_data.m_Player)
      return UA_ERROR;
    if (m_TimeElpased < m_AdjustedTimeToComplete)
      m_TimeElpased += action_data.m_Player.GetDeltaT();
    else
    {
      if (m_SpentUnits)
      {
        m_SpentUnits.param1 = m_TimeElpased;
        SetACData(m_SpentUnits);
      }
      OnCompletePogress(action_data);
      return UA_FINISHED;
    }
    return UA_PROCESSING;
  }
References CAContinuousTime::m_AdjustedTimeToComplete, CAContinuousTime::m_SpentUnits, CAContinuousTime::m_TimeElpased, CAContinuousBase::OnCompletePogress(), CABase::SetACData(), UA_ERROR, UA_FINISHED, and UA_PROCESSING.
GetProgress()
override float CAContinuousCraft::GetProgress () inline private
Definition at line 48 of file CAContinuousCraft.c.
  {
    if (m_AdjustedTimeToComplete > 0)
    {
      //float progress = m_TimeElpased/m_AdjustedTimeToComplete;
      return m_TimeElpased / m_AdjustedTimeToComplete;
    }
    return 1;
  }
References CAContinuousTime::m_AdjustedTimeToComplete, and CAContinuousTime::m_TimeElpased.
Setup()
override void CAContinuousCraft::Setup (ActionData action_data) inline private
Definition at line 3 of file CAContinuousCraft.c.
  {
    m_TimeElpased = 0;
    m_AdjustedTimeToComplete = 1000; //indication of arror if somting will be craft 1000 sec
    if (!m_SpentUnits)
      m_SpentUnits = new Param1<float>(0);
    else
      m_SpentUnits.param1 = 0;
    WorldCraftActionData action_data_wc = WorldCraftActionData.Cast(action_data);
    PluginRecipesManager module_recipes_manager;
    Class.CastTo(module_recipes_manager, GetPlugin(PluginRecipesManager));
    if (module_recipes_manager)
    {
      m_AdjustedTimeToComplete = module_recipes_manager.GetRecipeLengthInSecs(action_data_wc.m_RecipeID);
      if (module_recipes_manager.GetIsInstaRecipe(action_data_wc.m_RecipeID) || module_recipes_manager.IsEnableDebugCrafting())
        m_AdjustedTimeToComplete = 0;
      float specialty_weight = module_recipes_manager.GetRecipeSpecialty(action_data_wc.m_RecipeID);
      m_AdjustedTimeToComplete = action_data.m_Player.GetSoftSkillsManager().AdjustCraftingTime(m_AdjustedTimeToComplete, specialty_weight);
      //PrintString("ttc:" + m_AdjustedTimeToComplete.ToString());
    }
  }
References Class::CastTo(), GetPlugin(), CAContinuousTime::m_AdjustedTimeToComplete, CAContinuousTime::m_SpentUnits, and CAContinuousTime::m_TimeElpased.
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousCraft.c