DayZ: scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionRepairCarPart.c File Reference
ActionRepairCarPart.c File Reference
Classes
class RepairCarPartActionReciveData
class ActionRepairCarPartCB
Functions
void ActionRepairCarPart ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override ActionData CreateActionData ()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
Variables
RepairCarPartActionReciveData m_DamageZone
ActionRepairCarPartCB m_LastValidType
string m_CurrentDamageZone = ""
int m_LastValidComponentIndex = -1
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 43 of file ActionRepairCarPart.c.
  {
    if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
      return false;
    Object targetObject = target.GetObject();
    Object targetParent = target.GetParent();
    CarDoor carDoor = CarDoor.Cast(targetObject);
    if (!carDoor || !player)
      return false;
    if (GetGame().IsMultiplayer() && GetGame().IsServer())
      return true;
    if (carDoor)
    {
      //Check if item is attached to car -> If so, block repair if door is closed
      if (targetParent != null)
      {
        InventoryLocation loc = new InventoryLocation();
        bool isPresent = carDoor.GetInventory().GetCurrentInventoryLocation(loc);
        if (!isPresent || loc.GetSlot() == -1)
          return false;
        string slotName = InventorySlots.GetSlotName(loc.GetSlot());
        if (slotName && CarScript.Cast(targetParent).GetCarDoorsState(slotName) != CarDoorState.DOORS_OPEN)
          return false;
      }
      //Check health level of door
      int zoneHP = carDoor.GetHealthLevel("");
      return zoneHP > GameConstants.STATE_WORN && zoneHP < GameConstants.STATE_RUINED);
    }
    return false;
  }
References CarScript::GetCarDoorsState(), GetGame(), InventorySlots::GetSlotName(), slotName, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
ActionRepairCarPart()
void ActionRepairCarPart ()
Definition at line 25 of file ActionRepairCarPart.c.
  {
    m_CallbackClass = ActionRepairCarPartCB;
    m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
    m_FullBody = true;
    m_LockTargetOnUse = false;
    m_Text = "#repair";
  }
References m_FullBody, m_LockTargetOnUse, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Referenced by ActionConstructor::RegisterActions(), and EpoxyPutty::SetActions().
CreateActionData()
override ActionData CreateActionData ()
Definition at line 132 of file ActionRepairCarPart.c.
  {
    RepairCarPartActionData actionData = new RepairCarPartActionData();
    return actionData;
  }
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 37 of file ActionRepairCarPart.c.
  {
    m_ConditionItem = new CCINonRuined();
    m_ConditionTarget = new CCTCursor(UAMaxDistances.REPAIR);
  }
References m_ConditionItem, m_ConditionTarget, and UAMaxDistances::REPAIR.
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
Definition at line 170 of file ActionRepairCarPart.c.
  {
    super.HandleReciveData(action_recive_data, action_data);
    RepairCarPartActionReciveData reciveDataRepair = RepairCarPartActionReciveData.Cast(action_recive_data);
    RepairCarPartActionData.Cast(action_data).m_DamageZone = reciveDataRepair.m_DamageZoneRecived;
  }
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 82 of file ActionRepairCarPart.c.
  {
    Object tgObject = action_data.m_Target.GetObject();
    string damageZone = RepairCarPartActionData.Cast(action_data).m_DamageZone;
    if (!GetGame().IsMultiplayer())
      damageZone = m_CurrentDamageZone;
    if (tgObject)
    {
      CarDoor carDoor = CarDoor.Cast(tgObject);
      if (carDoor)
      {
        int newDmgLevel = Math.Clamp(carDoor.GetHealthLevel(damageZone) - 1, GameConstants.STATE_WORN, GameConstants.STATE_RUINED);
        float zoneMax = carDoor.GetMaxHealth("", "");
        float randomValue = Math.RandomFloatInclusive(zoneMax * 0.05, zoneMax * 0.15);
        switch (newDmgLevel)
        {
        case GameConstants.STATE_BADLY_DAMAGED:
          carDoor.SetHealth("", "", (zoneMax * GameConstants.DAMAGE_RUINED_VALUE) + randomValue);
          break;
        case GameConstants.STATE_DAMAGED:
          carDoor.SetHealth("", "", (zoneMax * GameConstants.DAMAGE_BADLY_DAMAGED_VALUE) + randomValue);
          break;
        case GameConstants.STATE_WORN:
          carDoor.SetHealth("", "", (zoneMax * GameConstants.DAMAGE_DAMAGED_VALUE) + randomValue);
          break;
        default:
          break;
        }
        if (action_data.m_MainItem.HasQuantity())
        {
          if (action_data.m_MainItem.GetQuantity() > 1)
          {
            int qnt = action_data.m_MainItem.GetQuantity();
            qnt -= action_data.m_MainItem.GetQuantityMax() * 0.25;
            action_data.m_MainItem.SetQuantity(qnt);
          }
          else
            action_data.m_MainItem.Delete();
        }
      }
    }
  }
References Math::Clamp(), GameConstants::DAMAGE_BADLY_DAMAGED_VALUE, GameConstants::DAMAGE_DAMAGED_VALUE, GameConstants::DAMAGE_RUINED_VALUE, GetGame(), m_CurrentDamageZone, Math::RandomFloatInclusive(), GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
Definition at line 150 of file ActionRepairCarPart.c.
  {
    if (!action_recive_data)
      action_recive_data = new RepairCarPartActionReciveData();
    super.ReadFromContext(ctx, action_recive_data);
    RepairCarPartActionReciveData reciveDataRepair = RepairCarPartActionReciveData.Cast(action_recive_data);
    if (HasTarget())
    {
      string zone;
      if (!ctx.Read(zone))
        return false;
      reciveDataRepair.m_DamageZoneRecived = zone;
    }
    return true;
  }
References HasTarget().
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Definition at line 138 of file ActionRepairCarPart.c.
  {
    super.WriteToContext(ctx, action_data);
    RepairCarPartActionData repairActionData;
    if (HasTarget() && Class.CastTo(repairActionData, action_data))
    {
      repairActionData.m_DamageZone = m_CurrentDamageZone;
      ctx.Write(repairActionData.m_DamageZone);
    }
  }
References Class::CastTo(), HasTarget(), and m_CurrentDamageZone.
Variable Documentation
m_CurrentDamageZone
string m_CurrentDamageZone = ""
Definition at line 22 of file ActionRepairCarPart.c.
m_DamageZone
RepairCarPartActionReciveData m_DamageZone
m_LastValidComponentIndex
int m_LastValidComponentIndex = -1
Definition at line 23 of file ActionRepairCarPart.c.
m_LastValidType
ActionRepairCarPartCB m_LastValidType