DayZ: scripts/4_World/Entities/Creatures/Animals/AnimalBase.c File Reference
AnimalBase.c File Reference
Classes
class DayZAnimal
class Animal_BosTaurus
class AnimalBase
class Animal_CervusElaphus
class Animal_GallusGallusDomesticus
class Animal_GallusGallusDomesticusF
Functions
class AnimalBase extends DayZAnimal RegisterHitComponentsForAI ()
void AnimalBase ()
override ArrowManagerBase GetArrowManager ()
override bool IsRefresherSignalingViable ()
override string CaptureSound ()
override string ReleaseSound ()
override bool IsDanger ()
class Animal_CapraHircus extends AnimalBase GetDestructionBehaviour ()
override bool IsDestructionBehaviour ()
override void EEInit ()
void ~Animal_CapraHircus_Spooky ()
override void OnDamageDestroyed (int oldLevel)
override bool ResistContaminatedEffect ()
override bool ReplaceOnDeath ()
override bool CanBeSkinned ()
override string GetDeadItemName ()
override bool KeepHealthOnReplace ()
Variables
ref ArrowManagerBase m_ArrowManager
GoatLight m_EyeLight
Function Documentation
AnimalBase()
void RegisterHitComponentsForAI::AnimalBase () protected
Definition at line 26 of file AnimalBase.c.
  {
    return "CattleBellow_SoundSet";
  }
  override string ReleaseSound()
  {
    return "CattleMooA_SoundSet";
  }
}
class Animal_BosTaurusF extends Animal_BosTaurus {}
class Animal_CanisLupus extends AnimalBase
{
  override void RegisterHitComponentsForAI()
  {
    m_DefaultHitComponent = "Zone_Chest";
    m_DefaultHitPositionComponent = "Pelvis";
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Head", 2);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Neck", 65);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Chest", 50);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Legs_Back", 75);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Legs_Front", 70);
  }
  override bool IsDanger()
  {
    return true;
  }
  override string CaptureSound()
  {
    return "WolfWhimper_SoundSet";
  }
  override string ReleaseSound()
  {
    return "WolfBark_SoundSet";
  }
}
class Animal_CapraHircus extends AnimalBase
{
  override void RegisterHitComponentsForAI()
  {
    m_DefaultHitComponent = "Zone_Chest";
    m_DefaultHitPositionComponent = "Pelvis";
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Head", 4);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Neck", 65);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Chest", 50);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Legs", 70);
  }
  override string CaptureSound()
  {
    return "GoatBleat_B_SoundSet";
  }
  override string ReleaseSound()
  {
    return "GoatBleat_A_SoundSet";
  }
}
class Animal_CapraHircusF extends Animal_CapraHircus {}
class Animal_CapraHircus_Spooky extends Animal_CapraHircus
{
  override string GetDestructionBehaviour()
  {
    return "DestructionEffectSpookyGoat";
  }
  override bool IsDestructionBehaviour()
  {
    return true;
  }
#ifndef SERVER
  protected GoatLight m_EyeLight;
  override void EEInit()
  {
    if (!IsDamageDestroyed())//walking up to or connecting to already dead zombies check
      m_EyeLight = GoatLight.Cast(ScriptedLightBase.CreateLightAtObjMemoryPoint(GoatLight, this, "GoatLight"));
  }
  void ~Animal_CapraHircus_Spooky()
  {
    if (m_EyeLight)
      m_EyeLight.Destroy();
  }
  override void OnDamageDestroyed(int oldLevel)
  {
    if (m_EyeLight)
      m_EyeLight.FadeOut(15);
  }
#endif
  override bool ResistContaminatedEffect()
  {
    return true;
  }
}
class Animal_CapreolusCapreolus extends AnimalBase
{
  override void RegisterHitComponentsForAI()
  {
    m_DefaultHitComponent = "Zone_Chest";
    m_DefaultHitPositionComponent = "Pelvis";
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Head", 4);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Neck", 65);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Chest", 50);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Legs", 70);
  }
  override string CaptureSound()
  {
    return "HareSquawk_SoundSet";
  }
  override string ReleaseSound()
  {
    return "HareChirp_SoundSet";
  }
}
class Animal_CapreolusCapreolusF extends Animal_CapreolusCapreolus {}
class Animal_CervusElaphus extends AnimalBase
{
  override void RegisterHitComponentsForAI()
  {
    m_DefaultHitComponent = "Zone_Chest";
    m_DefaultHitPositionComponent = "Pelvis";
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Head", 2);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Neck", 65);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Chest", 50);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Legs", 70);
  }
  override string CaptureSound()
  {
    return "DeerBleat_SoundSet";
  }
  override string ReleaseSound()
  {
    return "DeerRoar_SoundSet";
  }
}
class Animal_CervusElaphusF extends Animal_CervusElaphus {}
class Animal_GallusGallusDomesticus extends AnimalBase
{
  override void RegisterHitComponentsForAI()
  {
    m_DefaultHitComponent = "Spine";
    m_DefaultHitPositionComponent = "Spine";
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Head", 1);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Head", 5);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Head", 20);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "LArm1", 33);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "RArm1", 33);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Spine", 70);
  }
  override string CaptureSound()
  {
    return "HenScream_SoundSet";
  }
  override string ReleaseSound()
  {
    return "HenCluck_X_SoundSet";
  }
  override bool ReplaceOnDeath()
  {
    return true;
  }
  override bool CanBeSkinned()
  {
    return false;
  }
  override string GetDeadItemName()
  {
    return "DeadRooster";
  }
  override bool KeepHealthOnReplace()
  {
    return false;
  }
}
class Animal_GallusGallusDomesticusF extends Animal_GallusGallusDomesticus
{
  override string GetDeadItemName()
  {
    return "DeadChicken_Brown";
  }
}
class Animal_GallusGallusDomesticusF_Brown extends Animal_GallusGallusDomesticusF
{
  override string GetDeadItemName()
  {
    return "DeadChicken_Brown";
  }
}
class Animal_GallusGallusDomesticusF_Spotted extends Animal_GallusGallusDomesticusF
{
  override string GetDeadItemName()
  {
    return "DeadChicken_Spotted";
  }
}
class Animal_GallusGallusDomesticusF_White extends Animal_GallusGallusDomesticusF
{
  override string GetDeadItemName()
  {
    return "DeadChicken_White";
  }
}
class Animal_OvisAries extends AnimalBase
{
  override void RegisterHitComponentsForAI()
  {
    m_DefaultHitComponent = "Zone_Chest";
    m_DefaultHitPositionComponent = "Pelvis";
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Head", 4);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Chest", 15);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Neck", 55);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Chest", 50);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Legs", 70);
  }
  override string CaptureSound()
  {
    return "SheepBleat_E_SoundSet";
  }
  override string ReleaseSound()
  {
    return "SheepBleat_G_SoundSet";
  }
}
class Animal_OvisAriesF extends Animal_OvisAries {}
class Animal_SusDomesticus extends AnimalBase
{
  override void RegisterHitComponentsForAI()
  {
    m_DefaultHitComponent = "Zone_Spine";
    m_DefaultHitPositionComponent = "Spine1";
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Head", 5);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Belly", 25);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Neck", 65);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Chest", 50);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Legs", 70);
  }
  override string CaptureSound()
  {
    return "HogSqueal_SoundSet";
  }
  override string ReleaseSound()
  {
    return "HogGrunt_G_SoundSet";
  }
}
class Animal_SusScrofa extends AnimalBase
{
  override void RegisterHitComponentsForAI()
  {
    m_DefaultHitComponent = "Zone_Spine";
    m_DefaultHitPositionComponent = "Pelvis";
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Head", 3);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Neck", 55);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Belly", 15);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Legs", 70);
  }
  override string CaptureSound()
  {
    return "HogSqueal_SoundSet";
  }
  override string ReleaseSound()
  {
    return "HogGrunt_G_SoundSet";
  }
}
class Animal_UrsusArctos extends AnimalBase
{
  override void RegisterHitComponentsForAI()
  {
    m_DefaultHitComponent = "Zone_Head";
    m_DefaultHitPositionComponent = "Pelvis";
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Head", 25);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Belly", 50);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Neck", 65);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Legs", 70);
  }
  override bool IsDanger()
  {
    return true;
  }
  override string CaptureSound()
  {
    return "BearSnarl_SoundSet";
  }
  override string ReleaseSound()
  {
    return "BearRoarShort_SoundSet";
  }
}
CanBeSkinned()
override bool CanBeSkinned () protected
Definition at line 222 of file AnimalBase.c.
  {
    return false;
  }
CaptureSound()
override string CaptureSound ()
Definition at line 35 of file AnimalBase.c.
  {
    return "CattleBellow_SoundSet";
  }
EEInit()
override void EEInit () protected
Definition at line 117 of file AnimalBase.c.
  {
    if (!IsDamageDestroyed())//walking up to or connecting to already dead zombies check
      m_EyeLight = GoatLight.Cast(ScriptedLightBase.CreateLightAtObjMemoryPoint(GoatLight, this, "GoatLight"));
  }
References IsDamageDestroyed(), and m_EyeLight.
GetArrowManager()
override ArrowManagerBase RegisterHitComponentsForAI::GetArrowManager () protected
Definition at line 31 of file AnimalBase.c.
Referenced by ManBase::EEDelete(), ManBase::OnBleedingSourceRemoved(), ManBase::OnStoreLoad(), ManBase::OnStoreSave(), and ManBase::ResetPlayer().
GetDeadItemName()
override string GetDeadItemName () protected
Definition at line 227 of file AnimalBase.c.
  {
    return "DeadRooster";
  }
Referenced by Entity::DeathUpdate().
GetDestructionBehaviour()
class Animal_CapraHircus extends AnimalBase GetDestructionBehaviour ()
Definition at line 77 of file AnimalBase.c.
  {
    return "DestructionEffectSpookyGoat";
  }
Referenced by Entity::AttemptDestructionBehaviour().
IsDanger()
override bool IsDanger ()
Definition at line 61 of file AnimalBase.c.
  {
    return true;
  }
IsDestructionBehaviour()
override bool IsDestructionBehaviour ()
Definition at line 109 of file AnimalBase.c.
  {
    return true;
  }
Referenced by Entity::AttemptDestructionBehaviour().
IsRefresherSignalingViable()
override bool RegisterHitComponentsForAI::IsRefresherSignalingViable () protected
Definition at line 36 of file AnimalBase.c.
  {
    return "CattleBellow_SoundSet";
  }
KeepHealthOnReplace()
override bool KeepHealthOnReplace () protected
Definition at line 232 of file AnimalBase.c.
  {
    return false;
  }
Referenced by Entity::DeathUpdate().
OnDamageDestroyed()
override void OnDamageDestroyed (int oldLevel) protected
Definition at line 128 of file AnimalBase.c.
  {
    if (m_EyeLight)
      m_EyeLight.FadeOut(15);
  }
References m_EyeLight.
Referenced by Entity::EEHealthLevelChanged().
RegisterHitComponentsForAI()
class AnimalBase extends DayZAnimal RegisterHitComponentsForAI ()
Definition at line 1 of file AnimalBase.c.
  {
    m_DefaultHitComponent = "Zone_Chest";
    m_DefaultHitPositionComponent = "Pelvis";
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Head", 5);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Belly", 25);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Neck", 65);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Chest", 50);
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Legs", 70);
  }
Referenced by DayZCreatureAI::DayZAnimal().
ReleaseSound()
override string ReleaseSound ()
Definition at line 40 of file AnimalBase.c.
  {
    return "CattleMooA_SoundSet";
  }
ReplaceOnDeath()
override bool ReplaceOnDeath () protected
Definition at line 217 of file AnimalBase.c.
  {
    return true;
  }
Referenced by Entity::EEKilled().
ResistContaminatedEffect()
override bool ResistContaminatedEffect () protected
Definition at line 136 of file AnimalBase.c.
  {
    return true;
  }
~Animal_CapraHircus_Spooky()
void ~Animal_CapraHircus_Spooky () protected
Definition at line 123 of file AnimalBase.c.
  {
    if (m_EyeLight)
      m_EyeLight.Destroy();
  }
References m_EyeLight.
Variable Documentation
m_ArrowManager
ref ArrowManagerBase m_ArrowManager protected
Definition at line 24 of file AnimalBase.c.
Referenced by DayZAnimal::AnimalBase(), DayZAnimal::GetArrowManager(), DayZInfected::GetArrowManager(), ManBase::GetArrowManager(), DayZInfected::Init(), and ManBase::Init().
m_EyeLight
GoatLight m_EyeLight protected
Definition at line 115 of file AnimalBase.c.
Referenced by EEInit(), ZombieMaleBase::EEInit(), OnDamageDestroyed(), ZombieMaleBase::OnDamageDestroyed(), ~Animal_CapraHircus_Spooky(), and ZombieMaleBase::~ZmbM_Mummy().