DayZ: scripts/5_Mission/GUI/ScriptedWindows/MissionLoader.c File Reference
MissionLoader.c File Reference
Classes
class JsonMissionLoaderData
Functions
override Widget Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnDoubleClick (Widget w, int x, int y, int button)
override bool OnKeyDown (Widget w, int x, int y, int key)
Variables
class JsonMissionLoaderData m_WgtLstMsnList
ButtonWidget m_WgtBtnMsnPlay
ButtonWidget m_WgtBtnMsnClose
ref TStringArray m_ListMissionsNames
ref JsonMissionLoaderData m_MissionData
Function Documentation
Init()
override Widget Init () protected
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
pre-init arrays
Definition at line 43 of file MissionLoader.c.
  {
    m_MissionData = JsonMissionLoaderData.GetData();
    layoutRoot = GetGame().GetWorkspace().CreateWidgets("gui/layouts/day_z_mission_loader.layout");
    m_WgtLstMsnList = TextListboxWidget.Cast(layoutRoot.FindAnyWidget("wgt_lst_missions"));
    m_WgtBtnMsnPlay = ButtonWidget.Cast(layoutRoot.FindAnyWidget("wgt_btn_mission_play"));
    m_WgtBtnMsnClose = ButtonWidget.Cast(layoutRoot.FindAnyWidget("wgt_btn_mission_close"));
    foreach (string path: m_MissionData.MissionPaths)
      m_WgtLstMsnList.AddItem(path, NULL, 0);
    return layoutRoot;
  }
References JsonMissionLoaderData::GetData(), GetGame(), m_MissionData, m_WgtBtnMsnClose, m_WgtBtnMsnPlay, m_WgtLstMsnList, and path.
OnClick()
override bool OnClick (Widget w, int x, int y, int button) protected
Definition at line 59 of file MissionLoader.c.
  {
    super.OnClick(w, x, y, button);
    if (w == m_WgtBtnMsnClose)
    {
      Close();
      return true;
    }
    else if (w == m_WgtBtnMsnPlay)
    {
      int rowIndex = m_WgtLstMsnList.GetSelectedRow();
      string missionPath = m_MissionData.MissionPaths.Get(rowIndex);
      GetGame().PlayMission(missionPath);
      return true;
    }
    return false;
  }
References Close(), GetGame(), m_MissionData, m_WgtBtnMsnClose, m_WgtBtnMsnPlay, m_WgtLstMsnList, x, and y.
OnDoubleClick()
override bool OnDoubleClick (Widget w, int x, int y, int button) protected
Definition at line 80 of file MissionLoader.c.
  {
    super.OnClick(w, x, y, button);
    if (w == m_WgtLstMsnList)
    {
      int rowIndex = m_WgtLstMsnList.GetSelectedRow();
      string missionPath = m_MissionData.MissionPaths.Get(rowIndex);
      GetGame().PlayMission(missionPath);
    }
    return false;
  }
References GetGame(), m_MissionData, m_WgtLstMsnList, x, and y.
OnKeyDown()
override bool OnKeyDown (Widget w, int x, int y, int key) protected
Definition at line 93 of file MissionLoader.c.
  {
    super.OnKeyDown(w, x, y, key);
    switch (key)
    {
    case KeyCode.KC_ESCAPE:
    {
      Close();
      return true;
    }
    }
    return false;
  }
References Close(), x, and y.
Variable Documentation
m_ListMissionsNames
ref TStringArray m_ListMissionsNames protected
Definition at line 40 of file MissionLoader.c.
m_MissionData
ref JsonMissionLoaderData m_MissionData protected
Definition at line 41 of file MissionLoader.c.
Referenced by Init(), OnClick(), and OnDoubleClick().
m_WgtBtnMsnClose
ButtonWidget m_WgtBtnMsnClose protected
Definition at line 39 of file MissionLoader.c.
Referenced by Init(), and OnClick().
m_WgtBtnMsnPlay
ButtonWidget m_WgtBtnMsnPlay protected
Definition at line 38 of file MissionLoader.c.
Referenced by Init(), and OnClick().
m_WgtLstMsnList
class JsonMissionLoaderData m_WgtLstMsnList
Referenced by Init(), OnClick(), and OnDoubleClick().