DayZ: Trigger Class Reference
Trigger Class Reference
Scripted Trigger.
Protected Member Functions
override void OnEnter (Object obj)
override void OnLeave (Object obj)
void UpdateInsiders (int timeout)
void SetParentObject (Hologram projection)
void SetParentOwner (PlayerBase player)
TriggerEvents, backwards compatibility calling
Implementation for backwards compatibility with old Trigger system
void OnEnterBeginEvent (TriggerInsider insider)
void OnLeaveBeginEvent (TriggerInsider insider)
DEPRECATED Events
left for backwards compatibility
void OnEnter (Object obj)
void OnLeave (Object obj)
TriggerInsider conditions
Conditions applied to TriggerInsider for if it can be added or should be removed
bool CanAddObjectAsInsider (Object object)
Condition whether an Object can be added as TriggerInsider (checked before calling AddInsider)
bool ShouldRemoveInsider (TriggerInsider insider)
Condition whether a TriggerInsider should still be updated or not (checked in update loop and before adding)
bool ShouldRemoveInsiderNoLeave (TriggerInsider insider)
Condition whether a TriggerInsider should still be updated or not, skips OnLeaveEvent (checked in update loop and before adding)
TriggerInsider processing
Logic and processing of adding, removing and updating a TriggerInsider
TriggerInsider CreateInsider (Object obj)
Used for easily overriding TriggerInsider creation without rewriting AddInsider.
void AddInsider (Object obj)
Adding of new TriggerInsider.
void RemoveInsider (TriggerInsider insider, int index=-1)
Removing of TriggerInsider.
void RemoveInsiderByObject (Object object)
Removing of TriggerInsider through Object.
void UpdateInsiders (int timeout)
Update the current TriggerInsider inside the Trigger, timeout paramter is deprecated.
DEBUGGING
General internal debugging functionality
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Protected Attributes
int m_TriggerUpdateMs
Hologram m_ParentObj
PlayerBase m_Player
Private Member Functions
void Trigger ()
ctor
void ~Trigger ()
dtor
IEntity events
Usage of IEntity events
override void EOnInit (IEntity other, int extra)
Set the default extents of the Trigger only once it is properly initialized.
override void EOnFrame (IEntity other, float timeSlice)
When an Object touches the Trigger, we want to register it being inside the Trigger -> Replaced by EOnEnter.
override void EOnEnter (IEntity other, int extra)
When an Object enters the trigger add it to Insiders.
override void EOnLeave (IEntity other, int extra)
When an Object exits the trigger remove it from Insiders.
Trigger configuration
Basic configuration and data API
void SetExtents (vector mins, vector maxs)
Set the size of the Trigger, avoid using SetCollisionBox directly.
float GetRadius (vector min, vector max)
Get the radius of the CollisionBox, simply left for backwards compatibility.
array< ref TriggerInsider > GetInsiders ()
Get the current TriggerInsider array, left for backwards compatibility, moved down from ManTrigger.
TriggerInsider GetInsiderForObject (Object object)
Gets the TriggerInsider for the Object if it exists.
int GetInsiderIndexForObject (Object object)
Gets the index in m_insiders for the Object.
Private Member Functions inherited from TriggerEvents
ScriptInvoker GetOnEnterInvoker ()
ScriptInvoker GetOnLeaveInvoker ()
void Enter (TriggerInsider insider)
void OnEnterBeginEvent (TriggerInsider insider)
void OnEnterServerEvent (TriggerInsider insider)
void OnEnterClientEvent (TriggerInsider insider)
void OnEnterEndEvent (TriggerInsider insider)
void StayStart (int nrOfInsiders)
void OnStayStartBeginEvent (int nrOfInsiders)
void OnStayStartServerEvent (int nrOfInsiders)
void OnStayStartClientEvent (int nrOfInsiders)
void OnStayStartEndEvent (int nrOfInsiders)
void Stay (TriggerInsider insider, float deltaTime)
void OnStayBeginEvent (TriggerInsider insider, float deltaTime)
void OnStayServerEvent (TriggerInsider insider, float deltaTime)
void OnStayClientEvent (TriggerInsider insider, float deltaTime)
void OnStayEndEvent (TriggerInsider insider, float deltaTime)
void StayFinish ()
void OnStayFinishBeginEvent ()
void OnStayFinishServerEvent ()
void OnStayFinishClientEvent ()
void OnStayFinishEndEvent ()
void Leave (TriggerInsider insider)
void OnLeaveBeginEvent (TriggerInsider insider)
void OnLeaveServerEvent (TriggerInsider insider)
void OnLeaveClientEvent (TriggerInsider insider)
void OnLeaveEndEvent (TriggerInsider insider)
Private Attributes
const int TIMEOUT = 1000
DEPRECATED.
ref array< ref TriggerInsider > m_insiders
The objects and their metadata which are currently inside the Trigger.
Private Attributes inherited from TriggerEvents
ref ScriptInvoker m_OnEnterInvoker
ref ScriptInvoker m_OnLeaveInvoker
Detailed Description
Scripted Trigger.
Definition at line 1517 of file Hologram.c.
Constructor & Destructor Documentation
Trigger()
void Trigger::Trigger () inline private
ctor
Definition at line 53 of file Trigger.c.
  {
    SetEventMask(EntityEvent.INIT /*| EntityEvent.TOUCH*/ | EntityEvent.FRAME | EntityEvent.ENTER | EntityEvent.LEAVE);
    SetFlags(EntityFlags.TRIGGER, false);
    m_insiders = new array<ref TriggerInsider>;
  }
References m_insiders, and SetFlags().
~Trigger()
void Trigger::~Trigger () inline private
dtor
Definition at line 62 of file Trigger.c.
  {
#ifdef DIAG_DEVELOPER
    CleanupDebugShapes(dbgTargets);
#endif
  }
Member Function Documentation
AddInsider()
void Trigger::AddInsider (Object obj) inline protected
Adding of new TriggerInsider.
Definition at line 228 of file Trigger.c.
  {
    if (!obj)
      return;
    // Already in?
    if (GetInsiderForObject(obj))
    {
      Error(string.Format("[WARNING] :: [Trigger] :: [%1] :: Insider (%2) is already inside.", GetDebugName(this), GetDebugName(obj)));
      return;
    }
    // New Object entered! Fill the data.
    TriggerInsider insider = CreateInsider(obj);
    insider.timeStamp = g_Game.GetTime();
    insider.timeEntered = g_Game.GetTickTime();
    insider.lastUpdated = insider.timeEntered;
    // Don't add if it is going to be removed anyways..
    if (ShouldRemoveInsider(insider) || ShouldRemoveInsiderNoLeave(insider))
      return;
    // Keep track of the Object as long as it is inside the Trigger
    int index = m_insiders.Insert(insider);
    // Call the enter event to signal this Object entered
    Enter(insider);
    obj.OnEnterTrigger(this);
#ifdef TRIGGER_DEBUG_NORMAL
    Debug.TriggerLog(string.Format("%1: inserted at index %2", GetDebugName(obj), index), "Trigger", "", "AddInsider", GetDebugName(this));
#endif
  }
References CreateInsider(), TriggerEvents::Enter(), Error(), g_Game, GetDebugName(), GetInsiderForObject(), TriggerInsider::lastUpdated, m_insiders, ShouldRemoveInsider(), ShouldRemoveInsiderNoLeave(), TriggerInsider::timeEntered, TriggerInsider::timeStamp, and Debug::TriggerLog().
Referenced by EOnEnter().
CanAddObjectAsInsider()
bool Trigger::CanAddObjectAsInsider (Object object) inline protected
Condition whether an Object can be added as TriggerInsider (checked before calling AddInsider)
Definition at line 198 of file Trigger.c.
  {
    return true;
  }
Referenced by EOnEnter().
CreateInsider()
TriggerInsider Trigger::CreateInsider (Object obj) inline protected
Used for easily overriding TriggerInsider creation without rewriting AddInsider.
Definition at line 222 of file Trigger.c.
  {
    return new TriggerInsider(obj);
  }
Referenced by AddInsider().
EOnEnter()
override void Trigger::EOnEnter (IEntity other, int extra) inline private
When an Object enters the trigger add it to Insiders.
Definition at line 94 of file Trigger.c.
  {
    Object obj;
    if (Class.CastTo(obj, other) && CanAddObjectAsInsider(obj))
      AddInsider(obj);
  }
References AddInsider(), CanAddObjectAsInsider(), and Class::CastTo().
EOnFrame()
override void Trigger::EOnFrame (IEntity other, float timeSlice) inline private
When an Object touches the Trigger, we want to register it being inside the Trigger -> Replaced by EOnEnter.
We want to update the insiders every frame (or do we?)
Definition at line 88 of file Trigger.c.
  {
    UpdateInsiders(TIMEOUT);
  }
References TIMEOUT, and UpdateInsiders().
EOnInit()
override void Trigger::EOnInit (IEntity other, int extra) inline private
Set the default extents of the Trigger only once it is properly initialized.
Definition at line 74 of file Trigger.c.
  {
    SetExtents("-2 -4 -2", "2 4 2");
  }
References SetExtents().
EOnLeave()
override void Trigger::EOnLeave (IEntity other, int extra) inline private
When an Object exits the trigger remove it from Insiders.
Definition at line 102 of file Trigger.c.
  {
    Object obj;
    if (Class.CastTo(obj, other))
      RemoveInsiderByObject(obj);
  }
References Class::CastTo(), and RemoveInsiderByObject().
GetInsiderForObject()
TriggerInsider Trigger::GetInsiderForObject (Object object) inline private
Gets the TriggerInsider for the Object if it exists.
Definition at line 134 of file Trigger.c.
  {
    TriggerInsider ins;
    for (int n = 0; n < m_insiders.Count(); ++n)
    {
      ins = m_insiders[n];
      if (ins.GetObject() == object)
        return ins;
    }
    return null;
  }
References m_insiders.
Referenced by AddInsider().
GetInsiderIndexForObject()
int Trigger::GetInsiderIndexForObject (Object object) inline private
Gets the index in m_insiders for the Object.
Definition at line 149 of file Trigger.c.
  {
    TriggerInsider ins;
    for (int n = 0; n < m_insiders.Count(); ++n)
    {
      ins = m_insiders[n];
      if (ins.GetObject() == object)
        return n;
    }
    return -1;
  }
References m_insiders.
GetInsiders()
array< ref TriggerInsider > Trigger::GetInsiders () inline private
Get the current TriggerInsider array, left for backwards compatibility, moved down from ManTrigger.
Definition at line 128 of file Trigger.c.
  {
    return m_insiders;
  }
References m_insiders.
Referenced by ConstructionBoxTrigger::IsColliding().
GetRadius()
float Trigger::GetRadius (vector min, vector max) inline private
Get the radius of the CollisionBox, simply left for backwards compatibility.
Definition at line 122 of file Trigger.c.
  {
    return GetCollisionRadius();
  }
OnEnter() [1/2]
override void Trigger::OnEnter (Object obj) inline protected
Definition at line 1523 of file Hologram.c.
  {
    //Print("OnEnter");
    if (m_ParentObj)
    {
      m_ParentObj.SetIsCollidingPlayer(true);
      m_TriggerUpdateMs = 50;
    }
  }
References m_ParentObj.
Referenced by OnEnterBeginEvent().
OnEnter() [2/2]
void Trigger::OnEnter (Object obj) inline protected
Definition at line 187 of file Trigger.c.
{}
OnEnterBeginEvent()
void Trigger::OnEnterBeginEvent (TriggerInsider insider) inline protected
Definition at line 169 of file Trigger.c.
  {
    // Call the old event for backwards compatibility
    OnEnter(insider.GetObject());
  }
References TriggerInsider::GetObject(), and OnEnter().
OnLeave() [1/2]
override void Trigger::OnLeave (Object obj) inline protected
Definition at line 1533 of file Hologram.c.
  {
    //Print("OnLeave");
    if (m_ParentObj)
      m_ParentObj.SetIsCollidingPlayer(false);
  }
References m_ParentObj.
Referenced by OnLeaveBeginEvent().
OnLeave() [2/2]
void Trigger::OnLeave (Object obj) inline protected
Definition at line 189 of file Trigger.c.
{}
OnLeaveBeginEvent()
void Trigger::OnLeaveBeginEvent (TriggerInsider insider) inline protected
Definition at line 175 of file Trigger.c.
  {
    // Call the old event for backwards compatibility
    OnLeave(insider.GetObject());
  }
References TriggerInsider::GetObject(), and OnLeave().
OnRPC()
override void Trigger::OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) inline protected
Definition at line 350 of file Trigger.c.
  {
    super.OnRPC(sender, rpc_type, ctx);
#ifdef DIAG_DEVELOPER
    switch (rpc_type)
    {
    case ERPCs.DIAG_TRIGGER_DEBUG:
      DebugTriggerInfo data = new DebugTriggerInfo(vector.Zero, vector.Zero, vector.Zero, vector.Zero, 0, "", null);
      if (ctx.Read(data))
        DebugDmgTrigger(data.param1, data.param2, data.param3, data.param4, data.param5, data.param6, data.param7);
      break;
    }
#endif
  }
References vector::Zero.
RemoveInsider()
void Trigger::RemoveInsider (TriggerInsider insider, int index = -1) inline protected
Removing of TriggerInsider.
Definition at line 263 of file Trigger.c.
  {
    Leave(insider);
    insider.GetObject().OnLeaveTrigger(this);
#ifdef TRIGGER_DEBUG_NORMAL
    Debug.TriggerLog(string.Format("%1: removing at index %2", GetDebugName(insider.GetObject()), index), "Trigger", "", "RemoveInsider", GetDebugName(this));
#endif
    if (index >= 0)
      m_insiders.Remove(index);
    else
      m_insiders.RemoveItemUnOrdered(insider);
  }
References GetDebugName(), TriggerInsider::GetObject(), TriggerEvents::Leave(), m_insiders, and Debug::TriggerLog().
Referenced by RemoveInsiderByObject(), and UpdateInsiders().
RemoveInsiderByObject()
void Trigger::RemoveInsiderByObject (Object object) inline protected
Removing of TriggerInsider through Object.
Definition at line 279 of file Trigger.c.
  {
    TriggerInsider ins;
    for (int n = 0; n < m_insiders.Count(); ++n)
    {
      ins = m_insiders[n];
      if (ins.GetObject() == object)
      {
        RemoveInsider(ins, n);
        return;
      }
    }
    // As EOnLeave can call this, it is perfectly valid that this Object is not found on Script side
    // because of "ShouldRemoveInsider" and "ShouldRemoveInsiderNoLeave"
  }
References m_insiders, and RemoveInsider().
Referenced by EOnLeave().
SetExtents()
void Trigger::SetExtents (vector mins, vector maxs) inline private
Set the size of the Trigger, avoid using SetCollisionBox directly.
Definition at line 116 of file Trigger.c.
  {
    SetCollisionBox(mins, maxs);
  }
References SetCollisionBox().
Referenced by CreateCollisionTrigger(), CreateTrigger(), TrapBase::CreateTrigger(), ManTrigger::EOnInit(), and EOnInit().
SetParentObject()
void Trigger::SetParentObject (Hologram projection) inline protected
Definition at line 1545 of file Hologram.c.
  {
    m_ParentObj = projection;
  }
References m_ParentObj.
SetParentOwner()
void Trigger::SetParentOwner (PlayerBase player) inline protected
Definition at line 1550 of file Hologram.c.
  {
    m_Player = player;
  }
References m_Player.
ShouldRemoveInsider()
bool Trigger::ShouldRemoveInsider (TriggerInsider insider) inline protected
Condition whether a TriggerInsider should still be updated or not (checked in update loop and before adding)
Definition at line 204 of file Trigger.c.
  {
    return false;
  }
Referenced by AddInsider(), and UpdateInsiders().
ShouldRemoveInsiderNoLeave()
bool Trigger::ShouldRemoveInsiderNoLeave (TriggerInsider insider) inline protected
Condition whether a TriggerInsider should still be updated or not, skips OnLeaveEvent (checked in update loop and before adding)
Definition at line 210 of file Trigger.c.
  {
    return false;
  }
Referenced by AddInsider(), and UpdateInsiders().
UpdateInsiders() [1/2]
void Trigger::UpdateInsiders (int timeout) inline protected
Definition at line 1540 of file Hologram.c.
  {
    super.UpdateInsiders(m_TriggerUpdateMs);
  }
Referenced by EOnFrame().
UpdateInsiders() [2/2]
void Trigger::UpdateInsiders (int timeout) inline protected
Update the current TriggerInsider inside the Trigger, timeout paramter is deprecated.
Definition at line 297 of file Trigger.c.
  {
#ifdef DIAG_DEVELOPER
    DebugSendDmgTrigger();
#endif
    // Don't do anything if there aren't any insiders
    if (m_insiders.Count() == 0)
      return;
    // Mark the beginning of the update loop
    StayStart(m_insiders.Count());
    // Iterate over the current insiders, backwards because we are deleting
    for (int n = m_insiders.Count() - 1; n >= 0 ; --n)
    {
      TriggerInsider insider = m_insiders.Get(n);
      Object obj = insider.GetObject();
      // Check if the Object still exists or should be removed without calling OnLeaveEvent
      if (!obj || ShouldRemoveInsiderNoLeave(insider))
      {
#ifdef TRIGGER_DEBUG_BASIC
        Debug.TriggerLog(string.Format("%1: removed with no Leave.", GetDebugName(obj)), "Trigger", "", "UpdateInsiders", GetDebugName(this));
#endif
        m_insiders.Remove(n);
        continue;
      }
      // Check if Object left the Trigger or should be removed regardless
      if (ShouldRemoveInsider(insider))
      {
        RemoveInsider(insider, n);
        continue;
      }
      // Call the OnStayEvent, Object is still inside the Trigger and can be updated
      // Pass in the time since the Object was last updated (or entered)
      float currentTime = g_Game.GetTickTime();
      Stay(insider, currentTime - insider.lastUpdated);
      insider.lastUpdated = currentTime;
    }
    // Mark the end of the update loop
    StayFinish();
  }
References g_Game, GetDebugName(), TriggerInsider::GetObject(), TriggerInsider::lastUpdated, m_insiders, RemoveInsider(), ShouldRemoveInsider(), ShouldRemoveInsiderNoLeave(), TriggerEvents::Stay(), TriggerEvents::StayFinish(), TriggerEvents::StayStart(), and Debug::TriggerLog().
Member Data Documentation
m_insiders
ref array<ref TriggerInsider> Trigger::m_insiders private
The objects and their metadata which are currently inside the Trigger.
Definition at line 44 of file Trigger.c.
Referenced by AddInsider(), GetInsiderForObject(), GetInsiderIndexForObject(), GetInsiders(), RemoveInsider(), RemoveInsiderByObject(), Trigger(), and UpdateInsiders().
m_ParentObj
Hologram Trigger::m_ParentObj protected
Definition at line 1520 of file Hologram.c.
m_Player
PlayerBase Trigger::m_Player protected
Definition at line 1521 of file Hologram.c.
m_TriggerUpdateMs
int Trigger::m_TriggerUpdateMs protected
Definition at line 1519 of file Hologram.c.
TIMEOUT
const int Trigger::TIMEOUT = 1000 private
DEPRECATED.
Definition at line 42 of file Trigger.c.
Referenced by EOnFrame().
The documentation for this class was generated from the following files:
scripts/4_World/Classes/Hologram.c
scripts/4_World/Entities/ScriptedEntities/Triggers/Trigger.c