DayZ: ComponentEnergyManager Class Reference
ComponentEnergyManager Class Reference
Protected Member Functions
void ComponentEnergyManager ()
void ~ComponentEnergyManager ()
override void Event_OnInit ()
void DebugUpdate ()
Shape DrawArrow (vector from, vector to, float size=0.5, int color=0xFFFFFFFF, float flags=0)
EntityAI GetThisEntityAI ()
override void Event_OnAwake ()
override int GetCompType ()
void OnDeviceDestroyed ()
void RefreshDebug ()
bool GetDebugPlugs ()
void SetDebugPlugs (bool newVal)
void SwitchOn ()
Energy manager: Switches ON the device so it starts doing its work if it has enough energy.
void SwitchOff ()
Energy manager: Switches OFF the device.
void SetPassiveState (bool state=true)
Energy manager: Changes the status of this device. When it's passive (true), the main timer and OnWork events are not used.
void UnplugDevice (EntityAI device_to_unplug)
Energy manager: Unplugs the given device from this one.
void UnplugThis ()
Energy manager: Unplugs this device from its power source.
void UnplugAllDevices ()
Energy manager: Unplugs everything directly connected to this device.
void RestorePlugState (bool state)
void SetEnergy (float new_energy)
Energy manager: Sets stored energy for this device. It ignores the min/max limit!
void SetEnergy0To1 (float energy01)
Energy manager: Sets stored energy for this device between 0 and MAX based on relative input value between 0 and 1.
void UpdateSelections ()
Energy manager: Shows/Hides all selections this system works with. Call this if something is wrong with selections (like during Init and Restore event in config)
void UpdatePlugState ()
Energy manager: Unplugs this device when it's necesarry.
void GetCompatiblePlugTypes (out TIntArray IDs)
void StoreEnergySourceIDs (int b1, int b2, int b3, int b4)
void SetEnergyMaxPristine (float new_limit)
Energy manager: Changes the maximum amount of energy this device can store (when pristine).
void SetCordLength (float new_length)
Energy manager: Changes the length of the virtual power cord.
void SetPlugType (int new_type)
void SetAttachmentAction (int new_action_type)
void SetEnergyUsage (float new_usage)
Energy manager: Changes the energy usage per second.
void ResetEnergyUsage ()
Energy manager: Resets energy usage to default (config) value.
void SetCordTextureFile (string new_path)
void SetEnergySourceClient (EntityAI source)
void SetDeviceBySocketID (int id, EntityAI plugged_device)
Energy manager: Stores the device which is plugged into the given socket ID.
void SetElectricityIconVisibility (bool make_visible)
Energy manager: Sets visibility of the electricity icon (bolt).
void UpdateCanWork ()
void HandleMoveInsideCargo (EntityAI container)
void SetUpdateInterval (float value)
Energy manager: Sets the interval of the OnWork(...) calls. Changing this value does not change the rate of energy consumption.
bool GetRestorePlugState ()
bool PlugThisInto (EntityAI energy_source, int socket_id=-1)
Energy manager: Attempts to plug this device into the energy_source. Returns true if the action was successfull, or false if not (due to plug incompatibility or no free socket on the receiver). The ID of the power socket is chosen automatically unless optional parameter socket_id is used (starting from 0). If the given ID is not free then a free socket is found.
bool CanSwitchOn ()
Energy manager: Checks if the device can be switched ON.
bool CanWork (float test_energy=-1)
Energy manager: Checks whenever this device can do work or not.
bool CheckWetness ()
Energy manager: Checks if this device is being stopped from working by its wetness level. Returns true when its wetness is not blocking it, false when its to owet to work.
bool CanSwitchOff ()
Energy manager: Checks if the device can be switched OFF.
bool GetPreviousSwitchState ()
bool IsSwitchedOn ()
Energy manager: Returns state of the switch. Whenever the device is working or not does not matter. Use IsWorking() to account for that as well.
bool IsCordFolded ()
Energy manager: Returns true if the cord of this device is folded. Returns false if it's plugged.
bool IsPassive ()
Energy manager: Returns true if this device is set to be passive. False if otherwise.
bool IsPlugged ()
Energy manager: Returns true if this device is plugged into some other device (even if they are OFF or ruined). Otherwise it returns false.
bool ConsumeEnergy (float amount)
Energy manager: Consumes the given amount of energy. If there is not enough of stored energy in this device, then it tries to take it from its power source, if any exists. Returns true if the requested amount of energy was consumed. Otherwise it returns false.
bool IsWorking ()
Energy manager: Returns true if this device is working right now.
bool HasEnoughStoredEnergy ()
Energy manager: Returns true if this device has enough of stored energy for its own use.
bool HasFreeSocket (int socket_id=-1)
Energy manager: Returns true if this device has any free socket to receive a plug. If optional parameter socket_id is provided then only that socket ID is checked.
bool IsPlugCompatible (int plug_ID)
Energy manager: Checks if the given plug is compatible with this device's socket. Used by CanReceivePlugFrom() method.
bool CanReceivePlugFrom (EntityAI device_to_plug)
Energy manager: Returns true if this device can receive power plug of the other device.
bool CanBePluggedInto (EntityAI potential_energy_provider)
Energy manager: Returns true if this device can be plugged into the given energy source. Otherwise returns false.
bool HasElectricityIcon ()
Energy manager: Returns true if the electricity icon (bolt) is supposed to be visible for this device. False if not.
bool HasConversionOfEnergyToQuantity ()
Energy manager: Returns true if this item automatically converts its energy to quantity.
bool IsEnergySourceAtReach (vector from_position, float add_tolerance=0, vector override_source_position="-1 -1 -1")
Energy manager: Returns true if this device's virtual power cord can reach its energy source at the given position, depending on its cordLength config parameter. Otherwise returns false.
bool HasVisibleSocketsInInventory ()
bool IsSelectionAPlug (string selection_to_test)
Energy manager: Returns true if this selection is a plug that's plugged into this device. Otherwise returns false.
int GetSocketsCount ()
Energy manager: Returns the count of power sockets (whenever used or not)
int GetPlugType ()
Energy manager: Returns plug type. Check \DZ\data\basicDefines.hpp OR \Scripts\Classes\Component_constants.h files for types of plugs.
int GetAttachmentAction ()
int GetEnergySourceStorageIDb1 ()
int GetEnergySourceStorageIDb2 ()
int GetEnergySourceStorageIDb3 ()
int GetEnergySourceStorageIDb4 ()
int GetEnergySourceNetworkIDLow ()
int GetEnergySourceNetworkIDHigh ()
int GetPluggedDevicesCount ()
Energy manager: Returns the number of devices plugged into this one.
int GetEnergy0To100 ()
Energy manager: Returns % of stored energy this device has as integer (from 0 to 100)
float GetEnergy0To1 ()
Energy manager: Returns % of stored energy this device has as float (from 0.0 to 1.0)
float GetUpdateInterval ()
Energy manager: Returns the update interval of this device.
float GetWetnessExposure ()
Returns wetness exposure value defined in config.
float GetEnergyUsage ()
Energy manager: Returns the number of energy this device needs to run itself (See its config >> energyUsagePerSecond)
float GetEnergy ()
Energy manager: Returns the amount of stored energy this device has.
float AddEnergy (float added_energy)
Energy manager: Adds energy to this device and clamps it within its min/max storage limits. Returns the amount of energy that was clamped. Negative value is supported, but you should still use ConsumeEnergy(...) for propper substraction of energy.
float GetEnergyMax ()
Energy manager: Returns the maximum amount of energy this device can curently store. If parameter 'reduceMaxEnergyByDamageCoef' is used in the config of this device then the returned value will be reduced by damage.
float GetEnergyMaxPristine ()
Energy manager: Returns the maximum amount of energy this device can store. It's damage is NOT taken into account.
float GetEnergyAtSpawn ()
float GetCordLength ()
Energy manager: Returns the length of the virtual power cord.
EntityAI GetEnergySource ()
Energy manager: Returns the energy source this device is plugged into.
EntityAI GetDeviceBySocketID (int id)
Energy manager: Returns the device which is plugged into the given socket ID.
EntityAI GetPlugOwner (string plug_selection_name)
Energy manager: Returns the device to which the given plug selection belongs to.
EntityAI GetPluggedDevice ()
Energy manager: Returns a device which is plugged into this one. If there are more devices to choose from then it returns the first one that is found.
string GetCordTextureFile ()
Energy manager: Returns path to the cord texture file.
array< EntityAI > GetPluggedDevices ()
Energy manager: Returns an array of devices which are plugged into this one.
array< EntityAI > GetPoweredDevices ()
Energy manager: Returns an array of devices which are plugged into this one and are turned on.
void OnWork (float consumed_energy)
void OnIsPlugged (EntityAI source_device)
void OnIsUnplugged (EntityAI last_energy_source)
void OnOwnSocketTaken (EntityAI device)
void OnOwnSocketReleased (EntityAI device)
void OnAttachmentAdded (EntityAI elec_device)
void OnAttachmentRemoved (EntityAI elec_device)
void StartUpdates ()
void OnEnergyConsumed ()
Energy manager: Called when energy was consumed on this device.
void OnEnergyAdded ()
Energy manager: Called when energy was added on this device.
void StopUpdates ()
void InteractBranch (EntityAI originalCaller, Man player=null, int system=0)
void OnInteractBranch (EntityAI originalCaller, Man player, int system)
Called when the player is interacting with an item containing this energy component, or when interacting with an item this device is connected to.
void WakeUpWholeBranch (EntityAI original_caller)
void PlugCordIntoSocket (EntityAI device_to_plug, int socket_id=-1)
void UpdateSocketSelections (int socket_id, EntityAI device_to_plug)
void SetEnergySource (EntityAI source)
bool PlugInDevice (EntityAI device_to_plug, int socket_id=-1)
void SetPlugOwner (string selection_name, EntityAI device)
void UnplugCordFromSocket (int socket_to_unplug_ID)
void SetPowered (bool state)
bool FindAndConsumeEnergy (EntityAI original_caller, float amount, bool ignore_switch_state=false)
int GetMySocketID ()
void SetMySocketID (int slot_ID)
void Synch ()
void ClearLastUpdateTime ()
void RememberLastUpdateTime ()
float GetCurrentUpdateTime ()
void DeviceUpdate ()
Protected Attributes
const float DEFAULT_UPDATE_INTERVAL = 15
Shape m_DebugPlugArrow
bool m_IsSwichedOn
bool m_IsSwichedOnPreviousState
bool m_IsPassiveDevice
bool m_IsWorking
bool m_CanWork
bool m_CanStopWork
bool m_RestorePlugState
bool m_AutoSwitchOff
bool m_ShowSocketsInInventory
bool m_HasElectricityIcon
bool m_AutoSwitchOffWhenInCargo
bool m_IsPlugged
bool m_ConvertEnergyToQuantity
int m_MySocketID = -1
int m_PlugType
int m_EnergySourceStorageIDb1
int m_EnergySourceStorageIDb2
int m_EnergySourceStorageIDb3
int m_EnergySourceStorageIDb4
int m_AttachmentActionType
int m_EnergySourceNetworkIDLow = -1
int m_EnergySourceNetworkIDHigh = -1
float m_EnergyUsage
float m_Energy
float m_EnergyAtSpawn
float m_EnergyStorageMax
float m_ReduceMaxEnergyByDamageCoef
float m_SocketsCount
float m_CordLength
float m_LastUpdateTime
float m_WetnessExposure
float m_UpdateInterval
string m_CordTextureFile
ref TIntArray m_CompatiblePlugTypes
EntityAI m_EnergySource
ref array< EntityAI > m_PluggedDevices
ref map< string, EntityAI > m_DeviceByPlugSelection
ref Timer m_UpdateTimer
ref Timer m_UpdateQuantityTimer
ref Timer m_DebugUpdate
const int MAX_SOCKETS_COUNT = 4
EntityAI m_Sockets [MAX_SOCKETS_COUNT]
Static Protected Attributes
static bool m_DebugPlugs = false
static const string SOCKET_ = "socket_"
static const string _PLUGGED = "_plugged"
static const string _AVAILABLE = "_available"
static const string SEL_CORD_PLUGGED = "cord_plugged"
static const string SEL_CORD_FOLDED = "cord_folded"
Additional Inherited Members
Private Member Functions inherited from Component
void Event_OnFrame (IEntity other, float timeSlice)
Shape DebugBBoxDraw ()
void DebugBBoxSetColor (int color)
void DebugBBoxDelete ()
Shape DebugDirectionDraw (float distance=1)
void DebugDirectionSetColor (int color)
void DebugDirectionDelete ()
void SetParentEntityAI (EntityAI e)
void Event_OnAwake ()
void Event_OnInit ()
void LogThis (string msg, string fnc_name="n/a")
void LogThisWarning (string msg, string fnc_name="n/a")
void LogThisError (string msg, string fnc_name="n/a")
string GetCompName ()
int GetCompType ()
void Event_OnItemAttached (EntityAI item, string slot_name)
void Event_OnItemDetached (EntityAI item, string slot_name)
override Shape DebugBBoxDraw ()
override void DebugBBoxSetColor (int color)
override void DebugBBoxDelete ()
override Shape DebugDirectionDraw (float distance=1)
override void DebugDirectionDelete ()
void OnDrawing ()
Static Private Member Functions inherited from Component
static void Init ()
static string GetNameByType (int comp_type)
static bool IsTypeExist (int comp_type)
static void LogErrorBadCompType (int comp_type, string fnc_name)
static void LogWarningAlredyExist (int comp_type, string fnc_name)
Private Attributes inherited from Component
EntityAI m_ThisEntityAI
Shape m_DebugShapeBBox
Shape m_DebugShapeDirection
float m_DebugShapeDirectionDist
Detailed Description
Definition at line 18 of file ComponentEnergyManager.c.
Constructor & Destructor Documentation
ComponentEnergyManager()
void ComponentEnergyManager::ComponentEnergyManager () inline protected
Definition at line 82 of file ComponentEnergyManager.c.
  {
    // Disable debug arrows on public release, so that they don't use their timers.
#ifndef DEVELOPER
    m_DebugPlugs = false;
#endif
  }
References m_DebugPlugs.
~ComponentEnergyManager()
void ComponentEnergyManager::~ComponentEnergyManager () inline protected
Definition at line 90 of file ComponentEnergyManager.c.
  {
    if (m_DebugPlugArrow)
    {
      m_DebugPlugArrow.Destroy();
      m_DebugPlugArrow = NULL;
    }
  }
References m_DebugPlugArrow.
Member Function Documentation
AddEnergy()
float ComponentEnergyManager::AddEnergy (float added_energy) inline protected
Energy manager: Adds energy to this device and clamps it within its min/max storage limits. Returns the amount of energy that was clamped. Negative value is supported, but you should still use ConsumeEnergy(...) for propper substraction of energy.
Definition at line 1150 of file ComponentEnergyManager.c.
  {
    if (added_energy != 0)
    {
      //Print("AddEnergy ---------> " + added_energy + " " + this + " " +m_ThisEntityAI.ClassName());
#ifdef DIAG_DEVELOPER
      if (FeatureTimeAccel.GetFeatureTimeAccelEnabled(ETimeAccelCategories.ENERGY_CONSUMPTION) && added_energy < 0)
      {
        float timeAccel = FeatureTimeAccel.GetFeatureTimeAccelValue();
        added_energy *= timeAccel;
      }
#endif
      bool energy_was_added = (added_energy > 0);
      float energy_to_clamp = GetEnergy() + added_energy;
      float clamped_energy = Math.Clamp(energy_to_clamp, 0, GetEnergyMax());
      SetEnergy(clamped_energy);
      StartUpdates();
      if (energy_was_added)
        OnEnergyAdded();
      else
        OnEnergyConsumed();
      return energy_to_clamp - clamped_energy;
    }
    return 0;
  }
References Math::Clamp(), GetEnergy(), GetEnergyMax(), OnEnergyAdded(), OnEnergyConsumed(), SetEnergy(), and StartUpdates().
Referenced by FindAndConsumeEnergy().
CanBePluggedInto()
bool ComponentEnergyManager::CanBePluggedInto (EntityAI potential_energy_provider) inline protected
Energy manager: Returns true if this device can be plugged into the given energy source. Otherwise returns false.
Definition at line 944 of file ComponentEnergyManager.c.
  {
    return potential_energy_provider.GetCompEM().CanReceivePlugFrom(m_ThisEntityAI);
  }
References Component::m_ThisEntityAI.
CanReceivePlugFrom()
bool ComponentEnergyManager::CanReceivePlugFrom (EntityAI device_to_plug) inline protected
Energy manager: Returns true if this device can receive power plug of the other device.
Definition at line 924 of file ComponentEnergyManager.c.
  {
    // The following conditions are broken down for the sake of easier reading/debugging.
    if (HasFreeSocket() && device_to_plug != m_ThisEntityAI)
    {
      if (device_to_plug.GetCompEM().GetEnergySource() != m_ThisEntityAI)
      {
        if (IsPlugCompatible(device_to_plug.GetCompEM().GetPlugType()))
        {
          if (device_to_plug.GetCompEM().IsEnergySourceAtReach(device_to_plug.GetPosition(), 0, m_ThisEntityAI.GetPosition()))
            return true;
        }
      }
    }
    return false;
  }
References HasFreeSocket(), IsPlugCompatible(), and Component::m_ThisEntityAI.
Referenced by PlugInDevice().
CanSwitchOff()
bool ComponentEnergyManager::CanSwitchOff () inline protected
Energy manager: Checks if the device can be switched OFF.
Definition at line 809 of file ComponentEnergyManager.c.
  {
    if (IsPassive())
      return false;
    return IsSwitchedOn();
  }
References IsPassive(), and IsSwitchedOn().
Referenced by SwitchOff().
CanSwitchOn()
bool ComponentEnergyManager::CanSwitchOn () inline protected
Energy manager: Checks if the device can be switched ON.
Definition at line 715 of file ComponentEnergyManager.c.
  {
    if (!IsSwitchedOn())
      return true;
    return false;
  }
References IsSwitchedOn().
Referenced by SwitchOn().
CanWork()
bool ComponentEnergyManager::CanWork (float test_energy = -1) inline protected
Energy manager: Checks whenever this device can do work or not.
Parameters
test_energy float optional parameter will overwite the default energy consumption value of this device.
Returns
bool Returns true if this device will work when it's switched on. Otherwise it returns false.
Definition at line 729 of file ComponentEnergyManager.c.
  {
    if (GetGame().IsMultiplayer() && GetGame().IsClient())
      return m_CanWork;
    if (m_ThisEntityAI && m_ThisEntityAI.IsRuined())
      return false;
    // Check if the power source(s) (which can be serially connected) can provide needed energy.
    float energy_usage = test_energy;
    float gathered_energy = GetEnergy();
    EntityAI energy_source = GetEnergySource();
    if (energy_usage == -1)
      energy_usage = GetEnergyUsage();
    if (!CheckWetness())
      return false;
    if (gathered_energy <= 0 && energy_usage <= 0) //empty power source
      return false;
    int cycle_limit = 500; // Sanity check to definitely avoid infinite cycles
    while (gathered_energy < energy_usage) // Look for energy source if we don't have enough stored energy
    {
      // Safetycheck!
      if (cycle_limit > 0)
        cycle_limit--;
      else
      {
        DPrint("Energy Manager ERROR: The 'cycle_limit' safety break had to be activated to prevent possible game freeze. Dumping debug information...");
        //Print(m_ThisEntityAI);
        //Print(this);
        //Print(energy_source);
        if (energy_source.GetCompEM())
        {
          //Print(energy_source.GetCompEM());
        }
        //Print(gathered_energy);
        //Print(energy_usage);
        //Print(m_ThisEntityAI.GetPosition());
        if (energy_source)
        {
          //Print(energy_source.GetPosition());
        }
        //Print("End of the 'cycle_limit' safety break ^ ");
        return false;
      }
      // ^ Safetycheck!
      if (energy_source && energy_source != m_ThisEntityAI && !energy_source.IsRuined() && energy_source.GetCompEM() && energy_source.GetCompEM().IsSwitchedOn() && energy_source.GetCompEM().CheckWetness())
      {
        gathered_energy = gathered_energy + energy_source.GetCompEM().GetEnergy();
        energy_source = energy_source.GetCompEM().GetEnergySource();
      }
      else
      {
        // No power source, no energy.
        return false;
      }
    }
    // Enough energy was found
    return true;
  }
References CheckWetness(), DPrint(), GetEnergy(), GetEnergySource(), GetEnergyUsage(), GetGame(), m_CanWork, and Component::m_ThisEntityAI.
Referenced by UpdateCanWork().
CheckWetness()
bool ComponentEnergyManager::CheckWetness () inline protected
Energy manager: Checks if this device is being stopped from working by its wetness level. Returns true when its wetness is not blocking it, false when its to owet to work.
Definition at line 803 of file ComponentEnergyManager.c.
  {
    return (m_ThisEntityAI.GetWet() <= 1 - m_WetnessExposure);
  }
References Component::m_ThisEntityAI, and m_WetnessExposure.
Referenced by CanWork(), and DeviceUpdate().
ClearLastUpdateTime()
void ComponentEnergyManager::ClearLastUpdateTime () inline protected
Definition at line 1635 of file ComponentEnergyManager.c.
  {
    m_LastUpdateTime = 0;
  }
References m_LastUpdateTime.
Referenced by DeviceUpdate().
ConsumeEnergy()
bool ComponentEnergyManager::ConsumeEnergy (float amount) inline protected
Energy manager: Consumes the given amount of energy. If there is not enough of stored energy in this device, then it tries to take it from its power source, if any exists. Returns true if the requested amount of energy was consumed. Otherwise it returns false.
Definition at line 852 of file ComponentEnergyManager.c.
  {
    return FindAndConsumeEnergy(m_ThisEntityAI, amount, true);
  }
References FindAndConsumeEnergy(), and Component::m_ThisEntityAI.
Referenced by DeviceUpdate().
DebugUpdate()
void ComponentEnergyManager::DebugUpdate () inline protected
Definition at line 107 of file ComponentEnergyManager.c.
  {
    if (GetDebugPlugs())
    {
      if (GetGame().IsMultiplayer() && GetGame().IsServer())
      {
        if (m_DebugUpdate)
          m_DebugUpdate.Stop();
        return;
      }
      if (m_DebugPlugArrow)
      {
        m_DebugPlugArrow.Destroy();
        m_DebugPlugArrow = NULL;
      }
      if (GetEnergySource())
      {
        vector from = GetEnergySource().GetPosition() + "0 0.1 0";
        vector to = m_ThisEntityAI.GetPosition() + "0 0.1 0";
        //No need to draw an arrow in this situation as it would not be visible
        if (vector.DistanceSq(from, to) == 0)
          return;
        if (m_ThisEntityAI.GetType() == "BarbedWire") // Special case for debugging of electric fences. Temporal code until offsets in fences are fixed.
        {
          EntityAI BBB = m_ThisEntityAI.GetHierarchyParent();
          if (BBB && BBB.GetType() == "Fence")
            to = to + "0 -1.3 0";
        }
        m_DebugPlugArrow = DrawArrow(from, to);
      }
    }
  }
References vector::DistanceSq(), DrawArrow(), GetDebugPlugs(), GetEnergySource(), GetGame(), m_DebugPlugArrow, m_DebugUpdate, and Component::m_ThisEntityAI.
DeviceUpdate()
void ComponentEnergyManager::DeviceUpdate () inline protected
Definition at line 1651 of file ComponentEnergyManager.c.
  {
    /*
      vector pos = m_ThisEntityAI.GetPosition();
      string debug_message = "Object " + m_ThisEntityAI.GetType() + "  |  Energy: " + GetEnergy() + "  |  IsAtReach: " + (IsEnergySourceAtReach(pos)).ToString();
      Print(debug_message);
    */
    if (!m_IsPassiveDevice)
    {
      // 'm_ThisEntityAI' and 'this' must be checked because this method is caled from a timer
      if (m_ThisEntityAI && this && IsSwitchedOn() && !m_ThisEntityAI.IsRuined() && CheckWetness() && m_CanWork && !GetGame().IsMissionMainMenu())
      {
        bool was_powered = IsWorking();
        float consumed_energy_coef;
        // Make sure to use only as much % of energy as needed since this function can be called at random.
        if (m_LastUpdateTime == 0)
        {
          RememberLastUpdateTime();
          consumed_energy_coef = 1.0;
        }
        else
        {
          float updatetime = GetCurrentUpdateTime();
          float time = updatetime - m_LastUpdateTime;
          consumed_energy_coef = time / 1000;
        }
        if (consumed_energy_coef > 0) // Prevents calling of OnWork events when no energy is consumed
        {
          m_LastUpdateTime = GetCurrentUpdateTime();
          float consume_energy = GetEnergyUsage() * consumed_energy_coef;
          bool has_consumed_enough = true;
          if (GetGame().IsServer() || !GetGame().IsMultiplayer()) // single player or server side multiplayer
            has_consumed_enough = ConsumeEnergy(consume_energy);
          SetPowered(has_consumed_enough);
          if (has_consumed_enough)
          {
            if (!was_powered)
            {
              m_CanStopWork = true;
              WakeUpWholeBranch(m_ThisEntityAI);
              GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnWorkStart", NULL, 0);
              UpdateCanWork();
            }
            OnWork(consume_energy);
          }
          else
          {
            if (was_powered)
            {
              if (m_CanStopWork)
              {
                m_CanStopWork = false;
                ClearLastUpdateTime();
                GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnWorkStop", NULL, 0); // This event is called only once when the device STOPS being powered
                UpdateCanWork();
                if (m_AutoSwitchOff)
                  SwitchOff();
              }
            }
            StopUpdates();
          }
        }
        else
          ClearLastUpdateTime();
      }
      else if (this && m_ThisEntityAI)
      {
        SetPowered(false);
        StopUpdates();
        if (m_CanStopWork)
        {
          m_CanStopWork = false;
          ClearLastUpdateTime();
          GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnWorkStop", NULL, 0); // This event is called only once when the device STOPS being powered
          UpdateCanWork();
          if (m_AutoSwitchOff)
            SwitchOff();
        }
      }
    }
  }
References CheckWetness(), ClearLastUpdateTime(), ConsumeEnergy(), GetCurrentUpdateTime(), GetEnergyUsage(), GetGame(), IsSwitchedOn(), IsWorking(), m_AutoSwitchOff, m_CanStopWork, m_CanWork, m_IsPassiveDevice, m_LastUpdateTime, Component::m_ThisEntityAI, OnWork(), RememberLastUpdateTime(), SetPowered(), StopUpdates(), SwitchOff(), UpdateCanWork(), and WakeUpWholeBranch().
Referenced by Entity::OnVariablesSynchronized(), SetPassiveState(), SwitchOff(), and SwitchOn().
DrawArrow()
Shape ComponentEnergyManager::DrawArrow (vector from, vector to, float size = 0.5, int color = 0xFFFFFFFF, float flags = 0) inline protected
Definition at line 147 of file ComponentEnergyManager.c.
  {
    vector dir = to - from;
    dir.Normalize();
    vector dir1 = dir * size;
    size = size * 0.5;
    vector dir2 = dir.Perpend() * size;
    vector pts[5];
    pts[0] = from;
    pts[1] = to;
    pts[2] = to - dir1 - dir2;
    pts[3] = to - dir1 + dir2;
    pts[4] = to;
    return Shape.CreateLines(color, flags, pts, 5);
  }
References vector::Normalize(), vector::Perpend(), and Shape.
Referenced by DebugUpdate().
Event_OnAwake()
override void ComponentEnergyManager::Event_OnAwake () inline protected
Definition at line 172 of file ComponentEnergyManager.c.
  {
    string cfg_item = "CfgVehicles " + m_ThisEntityAI.GetType();
    string cfg_energy_manager = cfg_item + " EnergyManager ";
    // Read all config parameters
    m_EnergyUsage = GetGame().ConfigGetFloat(cfg_energy_manager + "energyUsagePerSecond");
    bool switch_on = GetGame().ConfigGetFloat(cfg_energy_manager + "switchOnAtSpawn");
    m_AutoSwitchOff = GetGame().ConfigGetFloat(cfg_energy_manager + "autoSwitchOff");
    m_HasElectricityIcon = GetGame().ConfigGetFloat(cfg_energy_manager + "hasIcon");
    m_AutoSwitchOffWhenInCargo = GetGame().ConfigGetFloat(cfg_energy_manager + "autoSwitchOffWhenInCargo");
    m_EnergyAtSpawn = GetGame().ConfigGetFloat(cfg_energy_manager + "energyAtSpawn");
    m_Energy = m_EnergyAtSpawn;
    m_EnergyStorageMax = GetGame().ConfigGetFloat(cfg_energy_manager + "energyStorageMax");
    m_ReduceMaxEnergyByDamageCoef = GetGame().ConfigGetFloat(cfg_energy_manager + "reduceMaxEnergyByDamageCoef");
    m_SocketsCount = GetGame().ConfigGetFloat(cfg_energy_manager + "powerSocketsCount");
    m_IsPassiveDevice = GetGame().ConfigGetFloat(cfg_energy_manager + "isPassiveDevice");
    m_CordLength = GetGame().ConfigGetFloat(cfg_energy_manager + "cordLength");
    m_PlugType = GetGame().ConfigGetFloat(cfg_energy_manager + "plugType");
    m_AttachmentActionType = GetGame().ConfigGetFloat(cfg_energy_manager + "attachmentAction");
    m_WetnessExposure = GetGame().ConfigGetFloat(cfg_energy_manager + "wetnessExposure");
    float update_interval = GetGame().ConfigGetFloat(cfg_energy_manager + "updateInterval");
    m_ConvertEnergyToQuantity = GetGame().ConfigGetFloat(cfg_energy_manager + "convertEnergyToQuantity");
    // Check if energy->quantity converion is configured properly
    float cfg_max_quantity = GetGame().ConfigGetFloat(cfg_item + " varQuantityMax");
    if (m_ConvertEnergyToQuantity && cfg_max_quantity <= 0)
    {
      string error = "Error! Item " + m_ThisEntityAI.GetType() + " has invalid configuration of the energy->quantity conversion feature. To fix this, add 'varQuantityMax' parameter with value higher than 0 to the item's config. Then make sure to re-build the PBO containing this item!";
      Error(error);
      m_ConvertEnergyToQuantity = false;
    }
    else
    {
      if (m_ConvertEnergyToQuantity)
      {
        if (!m_UpdateQuantityTimer)
          m_UpdateQuantityTimer = new Timer(CALL_CATEGORY_SYSTEM);
        m_UpdateQuantityTimer.Run(0.3, this, "OnEnergyAdded", NULL, false);
      }
    }
    // Set update interval
    if (update_interval <= 0)
      update_interval = DEFAULT_UPDATE_INTERVAL;
    SetUpdateInterval(update_interval);
    // If energyAtSpawn is present, then use its value for energyStorageMax if that cfg param is not present (for convenience's sake)
    string cfg_check_energy_limit = cfg_energy_manager + "energyStorageMax";
    if (!GetGame().ConfigIsExisting(cfg_check_energy_limit) && m_Energy > 0)
      m_EnergyStorageMax = m_Energy;
    // Fill m_CompatiblePlugTypes
    string cfg_check_plug_types = cfg_energy_manager + "compatiblePlugTypes";
    if (GetGame().ConfigIsExisting(cfg_check_plug_types))
    {
      m_CompatiblePlugTypes = new TIntArray;
      GetGame().ConfigGetIntArray(cfg_check_plug_types, m_CompatiblePlugTypes);
    }
    if (GetSocketsCount() > 0)
      m_PluggedDevices = new array<EntityAI>;
    if (m_CordLength < 0)
    {
      m_CordLength = 0;
      string error_message_cord = "Warning! " + m_ThisEntityAI.GetType() + ": config parameter 'cordLength' is less than 0! Cord length should not be negative!";
      DPrint(error_message_cord);
    }
    if (GetSocketsCount() > 0)
    {
      m_DeviceByPlugSelection = new map<string, EntityAI>;
      // Prepare the m_DeviceByPlugSelection
      string cfg_animation_sources = "cfgVehicles " + m_ThisEntityAI.GetType() + " " + "AnimationSources ";
      int animation_sources_count = GetGame().ConfigGetChildrenCount(cfg_animation_sources);
      for (int i_selection = 0; i_selection < animation_sources_count; i_selection++)
      {
        // TO DO: This could be optimized so not all selections on item are considered as plug/socket selections.
        string selection;
        GetGame().ConfigGetChildName(cfg_animation_sources, i_selection, selection);
        m_DeviceByPlugSelection.Set(selection, NULL);
      }
    }
    // Prepare sockets
    if (m_SocketsCount > MAX_SOCKETS_COUNT)
    {
      m_SocketsCount = MAX_SOCKETS_COUNT;
      string error_message_sockets = "Error! " + m_ThisEntityAI.GetType() + ": config parameter 'powerSocketsCount' is higher than the current limit (" + MAX_SOCKETS_COUNT.ToString() + ")! Raise the limit (constant MAX_SOCKETS_COUNT) or decrease the powerSocketsCount parameter for this device!";
      DPrint(error_message_sockets);
    }
    m_Sockets[MAX_SOCKETS_COUNT]; // Handles selections for plugs in the sockets. Feel free to change the limit if needed.
    GetGame().ConfigGetText(cfg_energy_manager + "cordTextureFile", m_CordTextureFile);
    if (switch_on)
      SwitchOn();
    for (int i = 0; i <= GetSocketsCount(); ++i)
      m_ThisEntityAI.HideSelection(SOCKET_ + i.ToString() + _PLUGGED);
    // Show/hide inventory sockets
    m_ShowSocketsInInventory = false;
    if (GetSocketsCount() > 0 && IsPlugCompatible(PLUG_COMMON_APPLIANCE) && m_ThisEntityAI.GetType() != "MetalWire") // metal wire filter is hopefully temporal.
      m_ShowSocketsInInventory = true;
    m_CanWork = HasEnoughStoredEnergy();
    m_ThisEntityAI.HideSelection(SEL_CORD_PLUGGED);
#ifdef DIAG_DEVELOPER
    GetGame().m_EnergyManagerArray.Insert(this);
#endif
  }
References _PLUGGED, CALL_CATEGORY_SYSTEM, DEFAULT_UPDATE_INTERVAL, DPrint(), Error(), GetGame(), GetSocketsCount(), HasEnoughStoredEnergy(), IsPlugCompatible(), m_AttachmentActionType, m_AutoSwitchOff, m_AutoSwitchOffWhenInCargo, m_CanWork, m_CompatiblePlugTypes, m_ConvertEnergyToQuantity, m_CordLength, m_CordTextureFile, m_DeviceByPlugSelection, m_Energy, m_EnergyAtSpawn, m_EnergyStorageMax, m_EnergyUsage, m_HasElectricityIcon, m_IsPassiveDevice, m_PluggedDevices, m_PlugType, m_ReduceMaxEnergyByDamageCoef, m_ShowSocketsInInventory, m_Sockets, m_SocketsCount, Component::m_ThisEntityAI, m_UpdateQuantityTimer, m_WetnessExposure, MAX_SOCKETS_COUNT, PLUG_COMMON_APPLIANCE, SEL_CORD_PLUGGED, SetUpdateInterval(), SOCKET_, and SwitchOn().
Event_OnInit()
override void ComponentEnergyManager::Event_OnInit () inline protected
Definition at line 100 of file ComponentEnergyManager.c.
  {
    m_ThisEntityAI.m_EM = this;
    GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnInitEnergy", NULL, 0);
  }
References GetGame(), and Component::m_ThisEntityAI.
FindAndConsumeEnergy()
bool ComponentEnergyManager::FindAndConsumeEnergy (EntityAI original_caller, float amount, bool ignore_switch_state = false) inline protected
Definition at line 1594 of file ComponentEnergyManager.c.
  {
    if ((ignore_switch_state || IsSwitchedOn()) && !m_ThisEntityAI.IsRuined())
    {
      float available_energy = AddEnergy(-amount);
      if (available_energy < 0 && IsPlugged())
      {
        // This devices does not has enough of stored energy, therefore it will take it from its power source (which can be a chain of cable reels)
        EntityAI next_power_source = GetEnergySource();
        if (next_power_source && next_power_source != original_caller) // Prevents infinite loop if the power source is the original caller itself
          return next_power_source.GetCompEM().FindAndConsumeEnergy(original_caller, -available_energy);
      }
      if (available_energy >= 0)
        return true;
      return false;
    }
    else
      return false;
  }
References AddEnergy(), GetEnergySource(), IsPlugged(), IsSwitchedOn(), and Component::m_ThisEntityAI.
Referenced by ConsumeEnergy().
GetAttachmentAction()
int ComponentEnergyManager::GetAttachmentAction () inline protected
Definition at line 1048 of file ComponentEnergyManager.c.
  {
    return m_AttachmentActionType;
  }
References m_AttachmentActionType.
Referenced by OnAttachmentAdded(), and OnAttachmentRemoved().
GetCompatiblePlugTypes()
void ComponentEnergyManager::GetCompatiblePlugTypes (out TIntArray IDs) inline protected
Definition at line 593 of file ComponentEnergyManager.c.
  {
    IDs = m_CompatiblePlugTypes;
  }
References m_CompatiblePlugTypes.
GetCompType()
override int ComponentEnergyManager::GetCompType () inline protected
Definition at line 304 of file ComponentEnergyManager.c.
  {
    return COMP_TYPE_ENERGY_MANAGER;
  }
References COMP_TYPE_ENERGY_MANAGER.
GetCordLength()
float ComponentEnergyManager::GetCordLength () inline protected
Energy manager: Returns the length of the virtual power cord.
Definition at line 1216 of file ComponentEnergyManager.c.
  {
    return m_CordLength;
  }
References m_CordLength.
Referenced by IsEnergySourceAtReach().
GetCordTextureFile()
string ComponentEnergyManager::GetCordTextureFile () inline protected
Energy manager: Returns path to the cord texture file.
Definition at line 1252 of file ComponentEnergyManager.c.
  {
    return m_CordTextureFile;
  }
References m_CordTextureFile.
GetCurrentUpdateTime()
float ComponentEnergyManager::GetCurrentUpdateTime () inline protected
Definition at line 1645 of file ComponentEnergyManager.c.
  {
    return GetGame().GetTime();
  }
References GetGame().
Referenced by DeviceUpdate(), and RememberLastUpdateTime().
GetDebugPlugs()
bool ComponentEnergyManager::GetDebugPlugs () inline protected
Definition at line 345 of file ComponentEnergyManager.c.
  {
    return m_DebugPlugs;
  }
References m_DebugPlugs.
Referenced by DebugUpdate().
GetDeviceBySocketID()
EntityAI ComponentEnergyManager::GetDeviceBySocketID (int id) inline protected
Energy manager: Returns the device which is plugged into the given socket ID.
Definition at line 1228 of file ComponentEnergyManager.c.
  {
    return m_Sockets[id];
  }
References m_Sockets.
Referenced by HasFreeSocket(), PlugCordIntoSocket(), UnplugCordFromSocket(), and UpdateSelections().
GetEnergy()
float ComponentEnergyManager::GetEnergy () inline protected
Energy manager: Returns the amount of stored energy this device has.
Definition at line 1144 of file ComponentEnergyManager.c.
  {
    return m_Energy;
  }
References m_Energy.
Referenced by AddEnergy(), CanWork(), HasEnoughStoredEnergy(), and Entity::OnStoreSave().
GetEnergy0To1()
float ComponentEnergyManager::GetEnergy0To1 () inline protected
Energy manager: Returns % of stored energy this device has as float (from 0.0 to 1.0)
Definition at line 1111 of file ComponentEnergyManager.c.
  {
    if (m_EnergyStorageMax > 0)
      return m_Energy / m_EnergyStorageMax;
    return 0;
  }
References m_Energy, and m_EnergyStorageMax.
GetEnergy0To100()
int ComponentEnergyManager::GetEnergy0To100 () inline protected
Energy manager: Returns % of stored energy this device has as integer (from 0 to 100)
Definition at line 1099 of file ComponentEnergyManager.c.
  {
    if (m_EnergyStorageMax > 0)
    {
      int coef = Math.Round(m_Energy / m_EnergyStorageMax * 100);
      return coef;
    }
    return 0;
  }
References m_Energy, m_EnergyStorageMax, and Math::Round().
GetEnergyAtSpawn()
float ComponentEnergyManager::GetEnergyAtSpawn () inline protected
Definition at line 1210 of file ComponentEnergyManager.c.
  {
    return m_EnergyAtSpawn;
  }
References m_EnergyAtSpawn.
GetEnergyMax()
float ComponentEnergyManager::GetEnergyMax () inline protected
Energy manager: Returns the maximum amount of energy this device can curently store. If parameter 'reduceMaxEnergyByDamageCoef' is used in the config of this device then the returned value will be reduced by damage.
Definition at line 1182 of file ComponentEnergyManager.c.
  {
    float max_health = 0;
    if (m_ThisEntityAI.HasDamageSystem())
      max_health = m_ThisEntityAI.GetMaxHealth("", "");
    //else if ( m_ReduceMaxEnergyByDamageCoef != 0 )
    // Error("[ERROR] ReduceMaxEnergyByDamageCoef is setup but " + m_ThisEntityAI.GetType() + " does not have a Damage System");
    if (max_health == 0 || m_ReduceMaxEnergyByDamageCoef == 0)
      return GetEnergyMaxPristine();
    float health = 100;
    if (GetGame().IsServer() || !GetGame().IsMultiplayer()) // TO DO: Remove this IF when method GetHealth can be called on client!
      health = m_ThisEntityAI.GetHealth("", "");
    float damage_coef = 1 - (health / max_health);
    return GetEnergyMaxPristine() * (1 - (damage_coef * m_ReduceMaxEnergyByDamageCoef));
  }
References GetEnergyMaxPristine(), GetGame(), m_ReduceMaxEnergyByDamageCoef, and Component::m_ThisEntityAI.
Referenced by AddEnergy(), and SetEnergy0To1().
GetEnergyMaxPristine()
float ComponentEnergyManager::GetEnergyMaxPristine () inline protected
Energy manager: Returns the maximum amount of energy this device can store. It's damage is NOT taken into account.
Definition at line 1205 of file ComponentEnergyManager.c.
  {
    return m_EnergyStorageMax;
  }
References m_EnergyStorageMax.
Referenced by GetEnergyMax().
GetEnergySource()
EntityAI ComponentEnergyManager::GetEnergySource () inline protected
Energy manager: Returns the energy source this device is plugged into.
Definition at line 1222 of file ComponentEnergyManager.c.
  {
    return m_EnergySource;
  }
References m_EnergySource.
Referenced by CanWork(), DebugUpdate(), FindAndConsumeEnergy(), IsEnergySourceAtReach(), OnAttachmentRemoved(), Entity::OnStoreSave(), UnplugThis(), and UpdateSelections().
GetEnergySourceNetworkIDHigh()
int ComponentEnergyManager::GetEnergySourceNetworkIDHigh () inline protected
Definition at line 1084 of file ComponentEnergyManager.c.
  {
    return m_EnergySourceNetworkIDHigh;
  }
References m_EnergySourceNetworkIDHigh.
Referenced by Entity::OnVariablesSynchronized().
GetEnergySourceNetworkIDLow()
int ComponentEnergyManager::GetEnergySourceNetworkIDLow () inline protected
Definition at line 1078 of file ComponentEnergyManager.c.
  {
    return m_EnergySourceNetworkIDLow;
  }
References m_EnergySourceNetworkIDLow.
Referenced by Entity::OnVariablesSynchronized().
GetEnergySourceStorageIDb1()
int ComponentEnergyManager::GetEnergySourceStorageIDb1 () inline protected
Definition at line 1054 of file ComponentEnergyManager.c.
  {
    return m_EnergySourceStorageIDb1;
  }
References m_EnergySourceStorageIDb1.
Referenced by Entity::EEOnAfterLoad().
GetEnergySourceStorageIDb2()
int ComponentEnergyManager::GetEnergySourceStorageIDb2 () inline protected
Definition at line 1060 of file ComponentEnergyManager.c.
  {
    return m_EnergySourceStorageIDb2;
  }
References m_EnergySourceStorageIDb2.
Referenced by Entity::EEOnAfterLoad().
GetEnergySourceStorageIDb3()
int ComponentEnergyManager::GetEnergySourceStorageIDb3 () inline protected
Definition at line 1066 of file ComponentEnergyManager.c.
  {
    return m_EnergySourceStorageIDb3;
  }
References m_EnergySourceStorageIDb3.
Referenced by Entity::EEOnAfterLoad().
GetEnergySourceStorageIDb4()
int ComponentEnergyManager::GetEnergySourceStorageIDb4 () inline protected
Definition at line 1072 of file ComponentEnergyManager.c.
  {
    return m_EnergySourceStorageIDb4;
  }
References m_EnergySourceStorageIDb4.
Referenced by Entity::EEOnAfterLoad().
GetEnergyUsage()
float ComponentEnergyManager::GetEnergyUsage () inline protected
Energy manager: Returns the number of energy this device needs to run itself (See its config >> energyUsagePerSecond)
Definition at line 1138 of file ComponentEnergyManager.c.
  {
    return m_EnergyUsage;
  }
References m_EnergyUsage.
Referenced by CanWork(), DeviceUpdate(), HasEnoughStoredEnergy(), and SetEnergy().
GetMySocketID()
int ComponentEnergyManager::GetMySocketID () inline protected
Definition at line 1619 of file ComponentEnergyManager.c.
  {
    return m_MySocketID;
  }
References m_MySocketID.
GetPluggedDevice()
EntityAI ComponentEnergyManager::GetPluggedDevice () inline protected
Energy manager: Returns a device which is plugged into this one. If there are more devices to choose from then it returns the first one that is found.
Definition at line 1243 of file ComponentEnergyManager.c.
  {
    if (GetPluggedDevicesCount() > 0)
      return GetPluggedDevices().Get(0);
    return NULL;
  }
References GetPluggedDevices(), and GetPluggedDevicesCount().
GetPluggedDevices()
array< EntityAI > ComponentEnergyManager::GetPluggedDevices () inline protected
Energy manager: Returns an array of devices which are plugged into this one.
Definition at line 1258 of file ComponentEnergyManager.c.
  {
    return m_PluggedDevices;
  }
References m_PluggedDevices.
Referenced by GetPluggedDevice(), GetPluggedDevicesCount(), GetPoweredDevices(), InteractBranch(), IsSelectionAPlug(), PlugInDevice(), UnplugAllDevices(), UnplugDevice(), and WakeUpWholeBranch().
GetPluggedDevicesCount()
int ComponentEnergyManager::GetPluggedDevicesCount () inline protected
Energy manager: Returns the number of devices plugged into this one.
Definition at line 1090 of file ComponentEnergyManager.c.
  {
    if (GetPluggedDevices())
      return GetPluggedDevices().Count();
    return 0;
  }
References GetPluggedDevices().
Referenced by GetPluggedDevice(), GetPoweredDevices(), HasFreeSocket(), UnplugAllDevices(), and UnplugDevice().
GetPlugOwner()
EntityAI ComponentEnergyManager::GetPlugOwner (string plug_selection_name) inline protected
Energy manager: Returns the device to which the given plug selection belongs to.
Definition at line 1234 of file ComponentEnergyManager.c.
  {
    if (m_DeviceByPlugSelection.Contains(plug_selection_name))
      return m_DeviceByPlugSelection.Get(plug_selection_name);
    return NULL;
  }
References m_DeviceByPlugSelection.
GetPlugType()
int ComponentEnergyManager::GetPlugType () inline protected
Energy manager: Returns plug type. Check \DZ\data\basicDefines.hpp OR \Scripts\Classes\Component_constants.h files for types of plugs.
Definition at line 1042 of file ComponentEnergyManager.c.
  {
    return m_PlugType;
  }
References m_PlugType.
GetPoweredDevices()
array< EntityAI > ComponentEnergyManager::GetPoweredDevices () inline protected
Energy manager: Returns an array of devices which are plugged into this one and are turned on.
Definition at line 1264 of file ComponentEnergyManager.c.
  {
    array<EntityAI> return_array = new array<EntityAI>;
    int plugged_devices_c = GetPluggedDevicesCount();
    for (int i = 0; i < plugged_devices_c; ++i)
    {
      EntityAI device = GetPluggedDevices().Get(i);
      if (IsSwitchedOn())
        return_array.Insert(device);
    }
    return return_array;
  }
References GetPluggedDevices(), GetPluggedDevicesCount(), and IsSwitchedOn().
GetPreviousSwitchState()
bool ComponentEnergyManager::GetPreviousSwitchState () inline protected
Definition at line 818 of file ComponentEnergyManager.c.
  {
    return m_IsSwichedOnPreviousState;
  }
References m_IsSwichedOnPreviousState.
Referenced by Entity::OnVariablesSynchronized().
GetRestorePlugState()
bool ComponentEnergyManager::GetRestorePlugState () inline protected
Definition at line 703 of file ComponentEnergyManager.c.
  {
    return m_RestorePlugState;
  }
References m_RestorePlugState.
Referenced by Entity::EEOnAfterLoad().
GetSocketsCount()
int ComponentEnergyManager::GetSocketsCount () inline protected
Energy manager: Returns the count of power sockets (whenever used or not)
Definition at line 1036 of file ComponentEnergyManager.c.
  {
    return m_SocketsCount;
  }
References m_SocketsCount.
Referenced by Event_OnAwake(), HasFreeSocket(), InteractBranch(), IsSelectionAPlug(), PlugCordIntoSocket(), UpdateSelections(), and WakeUpWholeBranch().
GetThisEntityAI()
EntityAI ComponentEnergyManager::GetThisEntityAI () inline protected
Definition at line 166 of file ComponentEnergyManager.c.
  {
    return m_ThisEntityAI;
  }
References Component::m_ThisEntityAI.
GetUpdateInterval()
float ComponentEnergyManager::GetUpdateInterval () inline protected
Energy manager: Returns the update interval of this device.
Definition at line 1120 of file ComponentEnergyManager.c.
  {
#ifdef DIAG_DEVELOPER
    if (FeatureTimeAccel.GetFeatureTimeAccelEnabled(ETimeAccelCategories.ENERGY_CONSUMPTION) || (FeatureTimeAccel.GetFeatureTimeAccelEnabled(ETimeAccelCategories.ENERGY_RECHARGE)))
    {
      return 1;//when modifying time accel, we might want to see things happen when they should, instead of waiting for the next tick
    }
#endif
    return m_UpdateInterval;
  }
References m_UpdateInterval.
Referenced by StartUpdates().
GetWetnessExposure()
float ComponentEnergyManager::GetWetnessExposure () inline protected
Returns wetness exposure value defined in config.
Definition at line 1132 of file ComponentEnergyManager.c.
  {
    return m_WetnessExposure;
  }
References m_WetnessExposure.
HandleMoveInsideCargo()
void ComponentEnergyManager::HandleMoveInsideCargo (EntityAI container) inline protected
Definition at line 687 of file ComponentEnergyManager.c.
  {
    if (m_AutoSwitchOffWhenInCargo)
    {
      if (IsSwitchedOn())
        SwitchOff();
    }
  }
References IsSwitchedOn(), m_AutoSwitchOffWhenInCargo, and SwitchOff().
Referenced by Entity::OnMovedInsideCargo().
HasConversionOfEnergyToQuantity()
bool ComponentEnergyManager::HasConversionOfEnergyToQuantity () inline protected
Energy manager: Returns true if this item automatically converts its energy to quantity.
Definition at line 956 of file ComponentEnergyManager.c.
  {
    return m_ConvertEnergyToQuantity;
  }
References m_ConvertEnergyToQuantity.
HasElectricityIcon()
bool ComponentEnergyManager::HasElectricityIcon () inline protected
Energy manager: Returns true if the electricity icon (bolt) is supposed to be visible for this device. False if not.
Definition at line 950 of file ComponentEnergyManager.c.
  {
    return m_HasElectricityIcon;
  }
References m_HasElectricityIcon.
HasEnoughStoredEnergy()
bool ComponentEnergyManager::HasEnoughStoredEnergy () inline protected
Energy manager: Returns true if this device has enough of stored energy for its own use.
Definition at line 864 of file ComponentEnergyManager.c.
  {
    if (GetEnergy() > GetEnergyUsage())
      return true;
    return false;
  }
References GetEnergy(), and GetEnergyUsage().
Referenced by Event_OnAwake().
HasFreeSocket()
bool ComponentEnergyManager::HasFreeSocket (int socket_id = -1) inline protected
Energy manager: Returns true if this device has any free socket to receive a plug. If optional parameter socket_id is provided then only that socket ID is checked.
Definition at line 873 of file ComponentEnergyManager.c.
  {
    if (socket_id == -1)
    {
      int plugged_devices = GetPluggedDevicesCount();
      int plugged_devices_limit = GetSocketsCount();
      if (plugged_devices < plugged_devices_limit)
        return true;
      return false;
    }
    else
    {
      EntityAI device = GetDeviceBySocketID(socket_id);
      if (device)
        return false;
      else
        return true;
    }
  }
References GetDeviceBySocketID(), GetPluggedDevicesCount(), and GetSocketsCount().
Referenced by CanReceivePlugFrom().
HasVisibleSocketsInInventory()
bool ComponentEnergyManager::HasVisibleSocketsInInventory () inline protected
Definition at line 1010 of file ComponentEnergyManager.c.
  {
    return m_ShowSocketsInInventory;
  }
References m_ShowSocketsInInventory.
InteractBranch()
void ComponentEnergyManager::InteractBranch (EntityAI originalCaller, Man player = null, int system = 0) inline protected
Gets called originally when the player is interacting with an item containing this energy component, then recursively following the branches of connection from the original item to the peripheries External calling of this function is not automatic for all item interactions and may need to be implemented on case by case bases Avoid using for gameplay logic, use 'OnInteractBranch' instead
Definition at line 1416 of file ComponentEnergyManager.c.
  {
    OnInteractBranch(originalCaller, player, system);
    if (GetSocketsCount() > 0)
    {
      array<EntityAI> devices = GetPluggedDevices();
      foreach (EntityAI device : devices)
      {
        if (device != originalCaller) // originalCaller check here prevents infinite loops
          device.GetCompEM().InteractBranch(originalCaller, player, system);
      }
    }
  }
References GetPluggedDevices(), GetSocketsCount(), and OnInteractBranch().
Referenced by PlugInDevice().
IsCordFolded()
bool ComponentEnergyManager::IsCordFolded () inline protected
Energy manager: Returns true if the cord of this device is folded. Returns false if it's plugged.
Definition at line 830 of file ComponentEnergyManager.c.
  {
    if (IsPlugged())
      return false;
    return true;
  }
References IsPlugged().
IsEnergySourceAtReach()
bool ComponentEnergyManager::IsEnergySourceAtReach (vector from_position, float add_tolerance = 0, vector override_source_position = "-1 -1 -1") inline protected
Energy manager: Returns true if this device's virtual power cord can reach its energy source at the given position, depending on its cordLength config parameter. Otherwise returns false.
Parameters
from_position vector position from where the measurement will be taken
add_tolerance float parameter will add to the cord's length in meters (optional)
Returns
bool True if the power source will be at reach for the plug, or if config param cordLength is absent or 0. False if not, or is not plugged, or this device lacks Energy Manager component.
vector position_player = GetGame().GetPlayer().GetPosition();
if (my_device.GetCompEM().IsEnergySourceAtReach(position_player))
{
  Print("Power source is at reach!");
}else{
  Print("Power source is NOT at reach!");
}
Definition at line 977 of file ComponentEnergyManager.c.
  {
    if (!IsPlugged() && override_source_position == "-1 -1 -1")
      return false;
    if (GetCordLength() == 0) // 0 is an exception, which means infinitely long cable.
      return true;
    vector source_pos;
    float distance;
    if (override_source_position == "-1 -1 -1")
    {
      EntityAI energy_source = GetEnergySource();
      if (!energy_source)
        return false;
      source_pos = energy_source.GetPosition();
      distance = vector.Distance(from_position, source_pos);
    }
    else
    {
      source_pos = override_source_position;
      distance = vector.Distance(from_position, source_pos);
    }
    if (distance > GetCordLength() + add_tolerance)
      return false;
    else
      return true;
  }
References vector::Distance(), GetCordLength(), GetEnergySource(), and IsPlugged().
Referenced by UpdatePlugState().
IsPassive()
bool ComponentEnergyManager::IsPassive () inline protected
Energy manager: Returns true if this device is set to be passive. False if otherwise.
Definition at line 839 of file ComponentEnergyManager.c.
  {
    return m_IsPassiveDevice;
  }
References m_IsPassiveDevice.
Referenced by CanSwitchOff(), and Entity::OnStoreSave().
IsPlugCompatible()
bool ComponentEnergyManager::IsPlugCompatible (int plug_ID) inline protected
Energy manager: Checks if the given plug is compatible with this device's socket. Used by CanReceivePlugFrom() method.
Definition at line 897 of file ComponentEnergyManager.c.
  {
    if (plug_ID == PLUG_UNDEFINED)
    {
      return true; // When plugType is undefined in config then make it compatible.
    }
    if (m_CompatiblePlugTypes)
    {
      for (int i = 0; i < m_CompatiblePlugTypes.Count(); i++)
      {
        int plug_ID_to_Check = m_CompatiblePlugTypes.Get(i);
        if (plug_ID_to_Check == plug_ID)
          return true;
      }
    }
    else
    {
      // Since the config parameter compatiblePlugTypes is not present, then accept all plugs for simplicity's sake
      return true;
    }
    return false;
  }
References m_CompatiblePlugTypes, and PLUG_UNDEFINED.
Referenced by CanReceivePlugFrom(), and Event_OnAwake().
IsPlugged()
bool ComponentEnergyManager::IsPlugged () inline protected
Energy manager: Returns true if this device is plugged into some other device (even if they are OFF or ruined). Otherwise it returns false.
Definition at line 845 of file ComponentEnergyManager.c.
  {
    return m_IsPlugged;
  }
References m_IsPlugged.
Referenced by FindAndConsumeEnergy(), IsCordFolded(), IsEnergySourceAtReach(), and Entity::OnStoreSave().
IsSelectionAPlug()
bool ComponentEnergyManager::IsSelectionAPlug (string selection_to_test) inline protected
Energy manager: Returns true if this selection is a plug that's plugged into this device. Otherwise returns false.
Definition at line 1016 of file ComponentEnergyManager.c.
  {
    if (GetPluggedDevices())
    {
      int socket_count = GetSocketsCount();
      for (int i = socket_count; i >= 0; --i)
      {
        string real_selection = SOCKET_ + i.ToString() + _PLUGGED;
        if (selection_to_test == real_selection)
          return true;
      }
    }
    return false;
  }
References _PLUGGED, GetPluggedDevices(), GetSocketsCount(), and SOCKET_.
IsSwitchedOn()
bool ComponentEnergyManager::IsSwitchedOn () inline protected
Energy manager: Returns state of the switch. Whenever the device is working or not does not matter. Use IsWorking() to account for that as well.
Definition at line 824 of file ComponentEnergyManager.c.
  {
    return m_IsSwichedOn;
  }
References m_IsSwichedOn.
Referenced by CanSwitchOff(), CanSwitchOn(), DeviceUpdate(), FindAndConsumeEnergy(), GetPoweredDevices(), HandleMoveInsideCargo(), Entity::OnStoreSave(), and Entity::OnVariablesSynchronized().
IsWorking()
bool ComponentEnergyManager::IsWorking () inline protected
Energy manager: Returns true if this device is working right now.
Definition at line 858 of file ComponentEnergyManager.c.
  {
    return m_IsWorking;
  }
References m_IsWorking.
Referenced by DeviceUpdate(), Entity::IsIgnited(), and SwitchOff().
OnAttachmentAdded()
void ComponentEnergyManager::OnAttachmentAdded (EntityAI elec_device) inline protected
Definition at line 1340 of file ComponentEnergyManager.c.
  {
    int attachment_action_type = GetAttachmentAction();
    if (attachment_action_type == PLUG_THIS_INTO_ATTACHMENT)
    {
      if (elec_device.GetCompEM().CanReceivePlugFrom(m_ThisEntityAI))
        PlugThisInto(elec_device);
    }
    else if (attachment_action_type == PLUG_ATTACHMENTS_INTO_THIS)
      elec_device.GetCompEM().PlugThisInto(m_ThisEntityAI);
  }
References GetAttachmentAction(), Component::m_ThisEntityAI, PLUG_ATTACHMENTS_INTO_THIS, PLUG_THIS_INTO_ATTACHMENT, and PlugThisInto().
Referenced by Entity::EEItemAttached().
OnAttachmentRemoved()
void ComponentEnergyManager::OnAttachmentRemoved (EntityAI elec_device) inline protected
Definition at line 1354 of file ComponentEnergyManager.c.
  {
    int attachment_action_type = GetAttachmentAction();
    if (attachment_action_type == PLUG_THIS_INTO_ATTACHMENT)
    {
      if (elec_device == GetEnergySource())
        UnplugThis();
    }
    else if (attachment_action_type == PLUG_ATTACHMENTS_INTO_THIS)
      elec_device.GetCompEM().UnplugThis();
  }
References GetAttachmentAction(), GetEnergySource(), PLUG_ATTACHMENTS_INTO_THIS, PLUG_THIS_INTO_ATTACHMENT, and UnplugThis().
Referenced by Entity::EEItemDetached().
OnDeviceDestroyed()
void ComponentEnergyManager::OnDeviceDestroyed () inline protected
Definition at line 310 of file ComponentEnergyManager.c.
  {
    bool was_working = m_ThisEntityAI.GetCompEM().IsWorking();
    SwitchOff();
    UnplugAllDevices();
    UnplugThis();
    SetPowered(false);
    if (was_working)
      m_ThisEntityAI.OnWorkStop();
    ;
  }
References Component::m_ThisEntityAI, SetPowered(), SwitchOff(), UnplugAllDevices(), and UnplugThis().
Referenced by Entity::EEDelete().
OnEnergyAdded()
void ComponentEnergyManager::OnEnergyAdded () inline protected
Energy manager: Called when energy was added on this device.
Definition at line 1387 of file ComponentEnergyManager.c.
  {
    if (m_UpdateQuantityTimer)
    {
      m_UpdateQuantityTimer.Stop();
      m_UpdateQuantityTimer = NULL;
    }
    m_ThisEntityAI.OnEnergyAdded();
  }
References Component::m_ThisEntityAI, and m_UpdateQuantityTimer.
Referenced by AddEnergy().
OnEnergyConsumed()
void ComponentEnergyManager::OnEnergyConsumed () inline protected
Energy manager: Called when energy was consumed on this device.
Definition at line 1381 of file ComponentEnergyManager.c.
  {
    m_ThisEntityAI.OnEnergyConsumed();
  }
References Component::m_ThisEntityAI.
Referenced by AddEnergy().
OnInteractBranch()
void ComponentEnergyManager::OnInteractBranch (EntityAI originalCaller, Man player, int system) inline protected
Called when the player is interacting with an item containing this energy component, or when interacting with an item this device is connected to.
Definition at line 1432 of file ComponentEnergyManager.c.
  {
    m_ThisEntityAI.IncreaseLifetime();
  }
References Component::m_ThisEntityAI.
Referenced by InteractBranch().
OnIsPlugged()
void ComponentEnergyManager::OnIsPlugged (EntityAI source_device) inline protected
Definition at line 1290 of file ComponentEnergyManager.c.
  {
    if (m_DebugPlugs)
    {
      if (!m_DebugUpdate)
        m_DebugUpdate = new Timer(CALL_CATEGORY_SYSTEM);
      if (!m_DebugUpdate.IsRunning())
        m_DebugUpdate.Run(0.01, this, "DebugUpdate", NULL, true);
    }
    UpdateCanWork();
    m_ThisEntityAI.OnIsPlugged(source_device);
  }
References CALL_CATEGORY_SYSTEM, m_DebugPlugs, m_DebugUpdate, Component::m_ThisEntityAI, and UpdateCanWork().
OnIsUnplugged()
void ComponentEnergyManager::OnIsUnplugged (EntityAI last_energy_source) inline protected
Definition at line 1306 of file ComponentEnergyManager.c.
  {
    UpdateCanWork();
    m_ThisEntityAI.OnIsUnplugged(last_energy_source);
  }
References Component::m_ThisEntityAI, and UpdateCanWork().
OnOwnSocketReleased()
void ComponentEnergyManager::OnOwnSocketReleased (EntityAI device) inline protected
Definition at line 1326 of file ComponentEnergyManager.c.
  {
    //play sound
    if (device.GetCompEM().GetPlugType() == PLUG_COMMON_APPLIANCE && m_ThisEntityAI.IsInitialized())
    {
      EffectSound sound_unplug;
      m_ThisEntityAI.PlaySoundSet(sound_unplug, "cablereel_unplug_SoundSet", 0, 0);
    }
    m_ThisEntityAI.OnOwnSocketReleased(device);
  }
References Component::m_ThisEntityAI, and PLUG_COMMON_APPLIANCE.
Referenced by UnplugDevice().
OnOwnSocketTaken()
void ComponentEnergyManager::OnOwnSocketTaken (EntityAI device) inline protected
Definition at line 1313 of file ComponentEnergyManager.c.
  {
    //play sound
    if (device.GetCompEM().GetPlugType() == PLUG_COMMON_APPLIANCE && m_ThisEntityAI.IsInitialized())
    {
      EffectSound sound_plug;
      m_ThisEntityAI.PlaySoundSet(sound_plug, "cablereel_plugin_SoundSet", 0, 0);
    }
    m_ThisEntityAI.OnOwnSocketTaken(device);
  }
References Component::m_ThisEntityAI, and PLUG_COMMON_APPLIANCE.
Referenced by PlugInDevice().
OnWork()
void ComponentEnergyManager::OnWork (float consumed_energy) inline protected
Definition at line 1284 of file ComponentEnergyManager.c.
  {
    m_ThisEntityAI.OnWork(consumed_energy);
  }
References Component::m_ThisEntityAI.
Referenced by DeviceUpdate().
PlugCordIntoSocket()
void ComponentEnergyManager::PlugCordIntoSocket (EntityAI device_to_plug, int socket_id = -1) inline protected
Definition at line 1462 of file ComponentEnergyManager.c.
  {
    if (socket_id >= 0)
    {
      EntityAI plug_owner_by_socket = GetDeviceBySocketID(socket_id);
      if (!plug_owner_by_socket)
      {
        UpdateSocketSelections(socket_id, device_to_plug);
        return;
      }
    }
    int slots_c = GetSocketsCount();
    for (int i = 0; i < slots_c; ++i)
    {
      EntityAI plug_owner = GetDeviceBySocketID(i);
      if (!plug_owner) // Check if this socket is available
      {
        UpdateSocketSelections(i, device_to_plug);
        break;
      }
    }
  }
References GetDeviceBySocketID(), GetSocketsCount(), and UpdateSocketSelections().
Referenced by PlugInDevice().
PlugInDevice()
bool ComponentEnergyManager::PlugInDevice (EntityAI device_to_plug, int socket_id = -1) inline protected
Definition at line 1531 of file ComponentEnergyManager.c.
  {
    if (CanReceivePlugFrom(device_to_plug))
    {
      device_to_plug.IncreaseLifetime();
      InteractBranch(m_ThisEntityAI);
      if (device_to_plug.GetCompEM().IsPlugged())
        device_to_plug.GetCompEM().UnplugThis();
      GetPluggedDevices().Insert(device_to_plug);
      device_to_plug.GetCompEM().SetEnergySource(m_ThisEntityAI);
      PlugCordIntoSocket(device_to_plug, socket_id); // Visualisation
      OnOwnSocketTaken(device_to_plug);
      device_to_plug.GetCompEM().OnIsPlugged(m_ThisEntityAI);
      WakeUpWholeBranch(m_ThisEntityAI);
      if (GetGame().IsServer() || !GetGame().IsMultiplayer())
      {
        device_to_plug.HideSelection(SEL_CORD_FOLDED);
        device_to_plug.ShowSelection(SEL_CORD_PLUGGED);
      }
      return true;
    }
    return false;
  }
References CanReceivePlugFrom(), GetGame(), GetPluggedDevices(), InteractBranch(), Component::m_ThisEntityAI, OnOwnSocketTaken(), PlugCordIntoSocket(), SEL_CORD_FOLDED, SEL_CORD_PLUGGED, and WakeUpWholeBranch().
PlugThisInto()
bool ComponentEnergyManager::PlugThisInto (EntityAI energy_source, int socket_id = -1) inline protected
Energy manager: Attempts to plug this device into the energy_source. Returns true if the action was successfull, or false if not (due to plug incompatibility or no free socket on the receiver). The ID of the power socket is chosen automatically unless optional parameter socket_id is used (starting from 0). If the given ID is not free then a free socket is found.
Definition at line 709 of file ComponentEnergyManager.c.
  {
    return energy_source.GetCompEM().PlugInDevice(m_ThisEntityAI, socket_id);
  }
References Component::m_ThisEntityAI.
Referenced by Entity::EEOnAfterLoad(), OnAttachmentAdded(), and Entity::OnVariablesSynchronized().
RefreshDebug()
void ComponentEnergyManager::RefreshDebug () inline protected
Definition at line 325 of file ComponentEnergyManager.c.
  {
    if (m_DebugPlugs)
    {
      if (!m_DebugUpdate)
        m_DebugUpdate = new Timer(CALL_CATEGORY_SYSTEM);
      if (!m_DebugUpdate.IsRunning())
        m_DebugUpdate.Run(0.01, this, "DebugUpdate", NULL, true);
    }
    else
    {
      if (m_DebugPlugArrow)
      {
        m_DebugPlugArrow.Destroy();
        m_DebugPlugArrow = NULL;
      }
    }
  }
References CALL_CATEGORY_SYSTEM, m_DebugPlugArrow, m_DebugPlugs, and m_DebugUpdate.
Referenced by SetDebugPlugs().
RememberLastUpdateTime()
void ComponentEnergyManager::RememberLastUpdateTime () inline protected
Definition at line 1640 of file ComponentEnergyManager.c.
  {
    m_LastUpdateTime = GetCurrentUpdateTime();
  }
References GetCurrentUpdateTime(), and m_LastUpdateTime.
Referenced by DeviceUpdate().
ResetEnergyUsage()
void ComponentEnergyManager::ResetEnergyUsage () inline protected
Energy manager: Resets energy usage to default (config) value.
Definition at line 638 of file ComponentEnergyManager.c.
  {
    string cfg_energy_usage = "CfgVehicles " + m_ThisEntityAI.GetType() + " EnergyManager ";
    m_EnergyUsage = GetGame().ConfigGetFloat(cfg_energy_usage + "energyUsagePerSecond");
  }
References GetGame(), m_EnergyUsage, and Component::m_ThisEntityAI.
RestorePlugState()
void ComponentEnergyManager::RestorePlugState (bool state) inline protected
Definition at line 499 of file ComponentEnergyManager.c.
  {
    m_RestorePlugState = state;
  }
References m_RestorePlugState.
Referenced by Entity::OnStoreLoad().
SetAttachmentAction()
void ComponentEnergyManager::SetAttachmentAction (int new_action_type) inline protected
Definition at line 626 of file ComponentEnergyManager.c.
  {
    m_AttachmentActionType = new_action_type;
  }
References m_AttachmentActionType.
SetCordLength()
void ComponentEnergyManager::SetCordLength (float new_length) inline protected
Energy manager: Changes the length of the virtual power cord.
Definition at line 614 of file ComponentEnergyManager.c.
  {
    m_CordLength = new_length;
  }
References m_CordLength.
SetCordTextureFile()
void ComponentEnergyManager::SetCordTextureFile (string new_path) inline protected
Definition at line 645 of file ComponentEnergyManager.c.
  {
    m_CordTextureFile = new_path;
  }
References m_CordTextureFile.
SetDebugPlugs()
void ComponentEnergyManager::SetDebugPlugs (bool newVal) inline protected
Definition at line 350 of file ComponentEnergyManager.c.
  {
    m_DebugPlugs = newVal;
    RefreshDebug();
  }
References m_DebugPlugs, and RefreshDebug().
SetDeviceBySocketID()
void ComponentEnergyManager::SetDeviceBySocketID (int id, EntityAI plugged_device) inline protected
Energy manager: Stores the device which is plugged into the given socket ID.
Definition at line 657 of file ComponentEnergyManager.c.
  {
    m_Sockets[id] = plugged_device;
  }
References m_Sockets.
Referenced by UnplugCordFromSocket(), and UpdateSocketSelections().
SetElectricityIconVisibility()
void ComponentEnergyManager::SetElectricityIconVisibility (bool make_visible) inline protected
Energy manager: Sets visibility of the electricity icon (bolt).
Definition at line 664 of file ComponentEnergyManager.c.
  {
    m_HasElectricityIcon = make_visible;
  }
References m_HasElectricityIcon.
SetEnergy()
void ComponentEnergyManager::SetEnergy (float new_energy) inline protected
Energy manager: Sets stored energy for this device. It ignores the min/max limit!
Definition at line 505 of file ComponentEnergyManager.c.
  {
    if (GetGame().IsServer() || !GetGame().IsMultiplayer()) // Client can't change energy value.
    {
      m_ThisEntityAI.SetWeightDirty();
      float old_energy = m_Energy;
      m_Energy = new_energy;
      if (old_energy - GetEnergyUsage() <= 0 || (old_energy != new_energy && Math.Min(old_energy, new_energy) <= 0))
        UpdateCanWork();
    }
  }
References GetEnergyUsage(), GetGame(), m_Energy, Component::m_ThisEntityAI, Math::Min(), and UpdateCanWork().
Referenced by AddEnergy(), Entity::OnStoreLoad(), and SetEnergy0To1().
SetEnergy0To1()
void ComponentEnergyManager::SetEnergy0To1 (float energy01) inline protected
Energy manager: Sets stored energy for this device between 0 and MAX based on relative input value between 0 and 1.
Definition at line 519 of file ComponentEnergyManager.c.
  {
    SetEnergy(Math.Lerp(0, GetEnergyMax(), energy01));
  }
References GetEnergyMax(), Math::Lerp(), and SetEnergy().
SetEnergyMaxPristine()
void ComponentEnergyManager::SetEnergyMaxPristine (float new_limit) inline protected
Energy manager: Changes the maximum amount of energy this device can store (when pristine).
Definition at line 608 of file ComponentEnergyManager.c.
  {
    m_EnergyStorageMax = new_limit;
  }
References m_EnergyStorageMax.
SetEnergySource()
void ComponentEnergyManager::SetEnergySource (EntityAI source) inline protected
Definition at line 1508 of file ComponentEnergyManager.c.
  {
    m_EnergySource = source;
    if (source)
    {
      m_IsPlugged = true;
      StartUpdates();
    }
    else
    {
      m_IsPlugged = false;
      m_EnergySourceNetworkIDLow = -1;
      m_EnergySourceNetworkIDHigh = -1;
    }
    if (m_EnergySource)
      m_EnergySource.GetNetworkID(m_EnergySourceNetworkIDLow, m_EnergySourceNetworkIDHigh);
    Synch();
  }
References m_EnergySource, m_EnergySourceNetworkIDHigh, m_EnergySourceNetworkIDLow, m_IsPlugged, StartUpdates(), and Synch().
Referenced by SetEnergySourceClient().
SetEnergySourceClient()
void ComponentEnergyManager::SetEnergySourceClient (EntityAI source) inline protected
Definition at line 651 of file ComponentEnergyManager.c.
  {
    SetEnergySource(source);
  }
References SetEnergySource().
SetEnergyUsage()
void ComponentEnergyManager::SetEnergyUsage (float new_usage) inline protected
Energy manager: Changes the energy usage per second.
Definition at line 632 of file ComponentEnergyManager.c.
  {
    m_EnergyUsage = new_usage;
  }
References m_EnergyUsage.
SetMySocketID()
void ComponentEnergyManager::SetMySocketID (int slot_ID) inline protected
Definition at line 1625 of file ComponentEnergyManager.c.
  {
    m_MySocketID = slot_ID;
  }
References m_MySocketID.
SetPassiveState()
void ComponentEnergyManager::SetPassiveState (bool state = true) inline protected
Energy manager: Changes the status of this device. When it's passive (true), the main timer and OnWork events are not used.
Definition at line 427 of file ComponentEnergyManager.c.
  {
    m_IsPassiveDevice = state;
    if (!m_IsPassiveDevice)
      DeviceUpdate();
  }
References DeviceUpdate(), and m_IsPassiveDevice.
Referenced by Entity::OnStoreLoad().
SetPlugOwner()
void ComponentEnergyManager::SetPlugOwner (string selection_name, EntityAI device) inline protected
Definition at line 1562 of file ComponentEnergyManager.c.
  {
    if (m_DeviceByPlugSelection.Contains(selection_name))
      m_DeviceByPlugSelection.Set(selection_name, device);
  }
References m_DeviceByPlugSelection.
Referenced by UnplugCordFromSocket(), and UpdateSocketSelections().
SetPlugType()
void ComponentEnergyManager::SetPlugType (int new_type) inline protected
Definition at line 620 of file ComponentEnergyManager.c.
  {
    m_PlugType = new_type;
  }
References m_PlugType.
SetPowered()
void ComponentEnergyManager::SetPowered (bool state) inline protected
Definition at line 1588 of file ComponentEnergyManager.c.
  {
    m_IsWorking = state;
  }
References m_IsWorking.
Referenced by DeviceUpdate(), and OnDeviceDestroyed().
SetUpdateInterval()
void ComponentEnergyManager::SetUpdateInterval (float value) inline protected
Energy manager: Sets the interval of the OnWork(...) calls. Changing this value does not change the rate of energy consumption.
Definition at line 697 of file ComponentEnergyManager.c.
  {
    m_UpdateInterval = value;
  }
References m_UpdateInterval.
Referenced by Event_OnAwake().
StartUpdates()
void ComponentEnergyManager::StartUpdates () inline protected
Definition at line 1368 of file ComponentEnergyManager.c.
  {
    if (!m_IsPassiveDevice)
    {
      if (!m_UpdateTimer)
        m_UpdateTimer = new Timer(CALL_CATEGORY_SYSTEM);
      if (!m_UpdateTimer.IsRunning()) // Makes sure the timer is NOT running already
        m_UpdateTimer.Run(GetUpdateInterval(), this, "DeviceUpdate", null, true);
    }
  }
References CALL_CATEGORY_SYSTEM, GetUpdateInterval(), m_IsPassiveDevice, and m_UpdateTimer.
Referenced by AddEnergy(), Entity::OnVariablesSynchronized(), SetEnergySource(), and SwitchOn().
StopUpdates()
void ComponentEnergyManager::StopUpdates () inline protected
Definition at line 1404 of file ComponentEnergyManager.c.
  {
    if (m_UpdateTimer)
    {
      m_UpdateTimer.Stop();
      m_UpdateTimer = NULL; // Delete timer from memory
    }
  }
References m_UpdateTimer.
Referenced by DeviceUpdate(), and SwitchOff().
StoreEnergySourceIDs()
void ComponentEnergyManager::StoreEnergySourceIDs (int b1, int b2, int b3, int b4) inline protected
Definition at line 599 of file ComponentEnergyManager.c.
  {
    m_EnergySourceStorageIDb1 = b1;
    m_EnergySourceStorageIDb2 = b2;
    m_EnergySourceStorageIDb3 = b3;
    m_EnergySourceStorageIDb4 = b4;
  }
References m_EnergySourceStorageIDb1, m_EnergySourceStorageIDb2, m_EnergySourceStorageIDb3, and m_EnergySourceStorageIDb4.
Referenced by Entity::OnStoreLoad().
SwitchOff()
void ComponentEnergyManager::SwitchOff () inline protected
Energy manager: Switches OFF the device.
Definition at line 392 of file ComponentEnergyManager.c.
  {
    m_IsSwichedOnPreviousState = m_IsSwichedOn;
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      if (CanSwitchOff())
      {
        m_IsSwichedOn = false;
        Synch();
        if (IsWorking())
        {
          StopUpdates();
          DeviceUpdate();
        }
        // 'Wakes up' all connected devices
        WakeUpWholeBranch(m_ThisEntityAI);
        UpdateCanWork();
        // Call event
        GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnSwitchOff", NULL, 0);
      }
    }
    if (!GetGame().IsServer() && GetGame().IsMultiplayer())
    {
      m_IsSwichedOn = false;
      GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnSwitchOff", NULL, 0);
    }
  }
References CanSwitchOff(), DeviceUpdate(), GetGame(), IsWorking(), m_IsSwichedOn, m_IsSwichedOnPreviousState, Component::m_ThisEntityAI, StopUpdates(), Synch(), UpdateCanWork(), and WakeUpWholeBranch().
Referenced by DeviceUpdate(), HandleMoveInsideCargo(), OnDeviceDestroyed(), and Entity::OnVariablesSynchronized().
SwitchOn()
void ComponentEnergyManager::SwitchOn () inline protected
Energy manager: Switches ON the device so it starts doing its work if it has enough energy.
Definition at line 363 of file ComponentEnergyManager.c.
  {
    m_IsSwichedOnPreviousState = m_IsSwichedOn;
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      if (CanSwitchOn())
      {
        m_IsSwichedOn = true;
        Synch();
        DeviceUpdate(); // 'Wake up' this device now
        StartUpdates();
        // 'Wakes up' all connected devices
        WakeUpWholeBranch(m_ThisEntityAI);
        UpdateCanWork();
        // Call event
        GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnSwitchOn", NULL, 0);
      }
    }
    if (!GetGame().IsServer() && GetGame().IsMultiplayer()/*  &&  CanSwitchOn() */) // I want the CanSwitchOn() check, but when it's here, the OnSwitchOn() event is never called on client-side due to engine's synchronization system changing the m_IsSwichedOn to true without any specific event beign called. (Yes there is OnVariablesSynchronized() but that is called also when m_CanWork is synchronized, so I need to write a method of knowing when was this specific value changed.)
      GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnSwitchOn", NULL, 0);
  }
References CanSwitchOn(), DeviceUpdate(), GetGame(), m_IsSwichedOn, m_IsSwichedOnPreviousState, Component::m_ThisEntityAI, StartUpdates(), Synch(), UpdateCanWork(), and WakeUpWholeBranch().
Referenced by Event_OnAwake(), Entity::OnStoreLoad(), and Entity::OnVariablesSynchronized().
Synch()
void ComponentEnergyManager::Synch () inline protected
Definition at line 1630 of file ComponentEnergyManager.c.
  {
    m_ThisEntityAI.SetSynchDirty();
  }
References Component::m_ThisEntityAI.
Referenced by SetEnergySource(), SwitchOff(), SwitchOn(), and UpdateCanWork().
UnplugAllDevices()
void ComponentEnergyManager::UnplugAllDevices () inline protected
Energy manager: Unplugs everything directly connected to this device.
Definition at line 488 of file ComponentEnergyManager.c.
  {
    if (GetPluggedDevices()) // This check is necesarry in case this function is called before initialization
    {
      int indexStart = GetPluggedDevicesCount() - 1;
      for (int i = indexStart; i >= 0; --i)
        UnplugDevice(GetPluggedDevices().Get(i));
    }
  }
References Get(), GetPluggedDevices(), GetPluggedDevicesCount(), and UnplugDevice().
Referenced by OnDeviceDestroyed().
UnplugCordFromSocket()
void ComponentEnergyManager::UnplugCordFromSocket (int socket_to_unplug_ID) inline protected
Definition at line 1570 of file ComponentEnergyManager.c.
  {
    EntityAI plug_owner = GetDeviceBySocketID(socket_to_unplug_ID);
    if (plug_owner)
    {
      SetDeviceBySocketID(socket_to_unplug_ID, NULL);
      string unplugged_selection = SOCKET_ + (socket_to_unplug_ID + 1).ToString() + _AVAILABLE;
      m_ThisEntityAI.ShowSelection(unplugged_selection);
      string plugged_selection = SOCKET_ + (socket_to_unplug_ID + 1).ToString() + _PLUGGED;
      m_ThisEntityAI.HideSelection(plugged_selection);
      SetPlugOwner(plugged_selection, NULL);
      plug_owner.GetCompEM().SetMySocketID(-1);
    }
  }
References _AVAILABLE, _PLUGGED, GetDeviceBySocketID(), Component::m_ThisEntityAI, SetDeviceBySocketID(), SetPlugOwner(), SOCKET_, and ToString().
Referenced by UnplugDevice().
UnplugDevice()
void ComponentEnergyManager::UnplugDevice (EntityAI device_to_unplug) inline protected
Energy manager: Unplugs the given device from this one.
Definition at line 435 of file ComponentEnergyManager.c.
  {
    if (GetGame())
    {
      int indexStart = GetPluggedDevicesCount() - 1;
      bool deviceFound = false;
      for (int i = indexStart; i >= 0; --i)
      {
        EntityAI plugged_device = GetPluggedDevices().Get(i);
        if (plugged_device == device_to_unplug)
        {
          GetPluggedDevices().Remove(i);
          deviceFound = true;
          break;
        }
      }
      if (deviceFound)
      {
        int socket_ID = device_to_unplug.GetCompEM().GetMySocketID();
        UnplugCordFromSocket(socket_ID);
        device_to_unplug.GetCompEM().SetEnergySource(null);
        device_to_unplug.GetCompEM().DeviceUpdate();
        device_to_unplug.GetCompEM().StartUpdates();
        device_to_unplug.GetCompEM().WakeUpWholeBranch(m_ThisEntityAI);
        if (m_DebugPlugs && m_DebugPlugArrow)
        {
          m_DebugPlugArrow.Destroy();
          m_DebugPlugArrow = null;
        }
        OnOwnSocketReleased(device_to_unplug);
        device_to_unplug.GetCompEM().OnIsUnplugged(m_ThisEntityAI);
        device_to_unplug.ShowSelection(SEL_CORD_FOLDED);
        device_to_unplug.HideSelection(SEL_CORD_PLUGGED);
      }
    }
  }
References GetGame(), GetPluggedDevices(), GetPluggedDevicesCount(), m_DebugPlugArrow, m_DebugPlugs, Component::m_ThisEntityAI, OnOwnSocketReleased(), SEL_CORD_FOLDED, SEL_CORD_PLUGGED, and UnplugCordFromSocket().
Referenced by UnplugAllDevices().
UnplugThis()
void ComponentEnergyManager::UnplugThis () inline protected
Energy manager: Unplugs this device from its power source.
Definition at line 478 of file ComponentEnergyManager.c.
  {
    if (GetGame())
    {
      if (GetEnergySource())
        GetEnergySource().GetCompEM().UnplugDevice(m_ThisEntityAI);
    }
  }
References GetEnergySource(), GetGame(), and Component::m_ThisEntityAI.
Referenced by OnAttachmentRemoved(), OnDeviceDestroyed(), Entity::OnVariablesSynchronized(), and UpdatePlugState().
UpdateCanWork()
void ComponentEnergyManager::UpdateCanWork () inline protected
Definition at line 670 of file ComponentEnergyManager.c.
  {
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      bool current_state = CanWork();
      if (current_state != m_CanWork)
      {
        m_CanWork = current_state;
        Synch();
        if (m_ThisEntityAI && m_ThisEntityAI.GetHierarchyParent() && m_ThisEntityAI.GetHierarchyParent().GetCompEM())
          m_ThisEntityAI.GetHierarchyParent().GetCompEM().UpdateCanWork();
      }
    }
  }
References CanWork(), GetGame(), m_CanWork, Component::m_ThisEntityAI, and Synch().
Referenced by DeviceUpdate(), OnIsPlugged(), OnIsUnplugged(), SetEnergy(), SwitchOff(), and SwitchOn().
UpdatePlugState()
void ComponentEnergyManager::UpdatePlugState () inline protected
Energy manager: Unplugs this device when it's necesarry.
Definition at line 565 of file ComponentEnergyManager.c.
  {
    if (m_ThisEntityAI.GetCompEM().GetEnergySource())
    {
      EntityAI player = m_ThisEntityAI.GetHierarchyRootPlayer();
      // Check if the item is held in hands during advanced placement
      if (player)
      {
        // Measure distance from the player
        vector playerPosition = player.GetPosition();
        if (!IsEnergySourceAtReach(playerPosition, 5))
          UnplugThis();
      }
      else
      {
        // Measure distance from the device
        vector itemPosition = m_ThisEntityAI.GetPosition();
        if (m_ThisEntityAI.GetHierarchyParent())
          itemPosition = m_ThisEntityAI.GetHierarchyParent().GetPosition();
        if (!IsEnergySourceAtReach(itemPosition))
          UnplugThis();
      }
    }
  }
References IsEnergySourceAtReach(), Component::m_ThisEntityAI, and UnplugThis().
UpdateSelections()
void ComponentEnergyManager::UpdateSelections () inline protected
Energy manager: Shows/Hides all selections this system works with. Call this if something is wrong with selections (like during Init and Restore event in config)
Definition at line 525 of file ComponentEnergyManager.c.
  {
    // Lets update sockets, if there are any
    int slots_c = GetSocketsCount();
    for (int i = 0; i < slots_c; ++i)
    {
      EntityAI plug_owner = GetDeviceBySocketID(i);
      if (plug_owner)
      {
        string plugged_selection = SOCKET_ + (i + 1).ToString() + _PLUGGED;
        string available_selection = SOCKET_ + (i + 1).ToString() + _AVAILABLE;
        m_ThisEntityAI.ShowSelection(plugged_selection);
        m_ThisEntityAI.HideSelection(available_selection);
        string texture_path = plug_owner.GetCompEM().GetCordTextureFile();
        int selection_index = m_ThisEntityAI.GetHiddenSelectionIndex(plugged_selection);
        m_ThisEntityAI.SetObjectTexture(selection_index, texture_path);
      }
      else
      {
        m_ThisEntityAI.ShowSelection(SOCKET_ + (i + 1).ToString() + _AVAILABLE);
        m_ThisEntityAI.HideSelection(SOCKET_ + (i + 1).ToString() + _PLUGGED);
      }
    }
    // Now lets update the cord/plug state
    if (GetEnergySource())
    {
      m_ThisEntityAI.ShowSelection(SEL_CORD_PLUGGED);
      m_ThisEntityAI.HideSelection(SEL_CORD_FOLDED);
    }
    else
    {
      m_ThisEntityAI.ShowSelection(SEL_CORD_FOLDED);
      m_ThisEntityAI.HideSelection(SEL_CORD_PLUGGED);
    }
  }
References _AVAILABLE, _PLUGGED, GetDeviceBySocketID(), GetEnergySource(), GetSocketsCount(), Component::m_ThisEntityAI, SEL_CORD_FOLDED, SEL_CORD_PLUGGED, SOCKET_, and ToString().
UpdateSocketSelections()
void ComponentEnergyManager::UpdateSocketSelections (int socket_id, EntityAI device_to_plug) inline protected
Definition at line 1490 of file ComponentEnergyManager.c.
  {
    SetDeviceBySocketID(socket_id, device_to_plug);
    string plugged_selection = SOCKET_ + (socket_id + 1).ToString() + _PLUGGED;
    SetPlugOwner(plugged_selection, device_to_plug);
    m_ThisEntityAI.ShowSelection(plugged_selection);
    string unplugged_selection = SOCKET_ + (socket_id + 1).ToString() + _AVAILABLE;
    m_ThisEntityAI.HideSelection(unplugged_selection);
    string texture_path = device_to_plug.GetCompEM().GetCordTextureFile();
    int selection_index = m_ThisEntityAI.GetHiddenSelectionIndex(plugged_selection);
    m_ThisEntityAI.SetObjectTexture(selection_index, texture_path);
    device_to_plug.GetCompEM().SetMySocketID(socket_id);
  }
References _AVAILABLE, _PLUGGED, Component::m_ThisEntityAI, SetDeviceBySocketID(), SetPlugOwner(), SOCKET_, and ToString().
Referenced by PlugCordIntoSocket().
WakeUpWholeBranch()
void ComponentEnergyManager::WakeUpWholeBranch (EntityAI original_caller) inline protected
Definition at line 1439 of file ComponentEnergyManager.c.
  {
    if (GetSocketsCount() > 0)
    {
      array<EntityAI> plugged_devices = GetPluggedDevices();
      int plugged_devices_c = plugged_devices.Count();
      for (int i = 0; i < plugged_devices_c; ++i)
      {
        EntityAI device = plugged_devices.Get(i);
        if (device != original_caller) // original_caller check here prevents infinite loops
        {
          device.GetCompEM().UpdateCanWork();
          device.GetCompEM().DeviceUpdate();
          device.GetCompEM().StartUpdates();
          device.GetCompEM().WakeUpWholeBranch(original_caller);
        }
      }
    }
  }
References GetPluggedDevices(), and GetSocketsCount().
Referenced by DeviceUpdate(), PlugInDevice(), SwitchOff(), and SwitchOn().
Member Data Documentation
_AVAILABLE
const string ComponentEnergyManager::_AVAILABLE = "_available" static protected
Definition at line 64 of file ComponentEnergyManager.c.
Referenced by UnplugCordFromSocket(), UpdateSelections(), and UpdateSocketSelections().
_PLUGGED
const string ComponentEnergyManager::_PLUGGED = "_plugged" static protected
Definition at line 63 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), IsSelectionAPlug(), UnplugCordFromSocket(), UpdateSelections(), and UpdateSocketSelections().
DEFAULT_UPDATE_INTERVAL
const float ComponentEnergyManager::DEFAULT_UPDATE_INTERVAL = 15 protected
Definition at line 20 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake().
m_AttachmentActionType
int ComponentEnergyManager::m_AttachmentActionType protected
Definition at line 44 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), GetAttachmentAction(), and SetAttachmentAction().
m_AutoSwitchOff
bool ComponentEnergyManager::m_AutoSwitchOff protected
Definition at line 31 of file ComponentEnergyManager.c.
Referenced by DeviceUpdate(), and Event_OnAwake().
m_AutoSwitchOffWhenInCargo
bool ComponentEnergyManager::m_AutoSwitchOffWhenInCargo protected
Definition at line 34 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), and HandleMoveInsideCargo().
m_CanStopWork
bool ComponentEnergyManager::m_CanStopWork protected
Definition at line 29 of file ComponentEnergyManager.c.
Referenced by DeviceUpdate().
m_CanWork
bool ComponentEnergyManager::m_CanWork protected
Definition at line 28 of file ComponentEnergyManager.c.
Referenced by CanWork(), DeviceUpdate(), Event_OnAwake(), and UpdateCanWork().
m_CompatiblePlugTypes
ref TIntArray ComponentEnergyManager::m_CompatiblePlugTypes protected
Definition at line 68 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), GetCompatiblePlugTypes(), and IsPlugCompatible().
m_ConvertEnergyToQuantity
bool ComponentEnergyManager::m_ConvertEnergyToQuantity protected
Definition at line 36 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), and HasConversionOfEnergyToQuantity().
m_CordLength
float ComponentEnergyManager::m_CordLength protected
Definition at line 54 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), GetCordLength(), and SetCordLength().
m_CordTextureFile
string ComponentEnergyManager::m_CordTextureFile protected
Definition at line 59 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), GetCordTextureFile(), and SetCordTextureFile().
m_DebugPlugArrow
Shape ComponentEnergyManager::m_DebugPlugArrow protected
Definition at line 22 of file ComponentEnergyManager.c.
Referenced by DebugUpdate(), RefreshDebug(), UnplugDevice(), and ~ComponentEnergyManager().
m_DebugPlugs
bool ComponentEnergyManager::m_DebugPlugs = false static protected
Definition at line 21 of file ComponentEnergyManager.c.
Referenced by ComponentEnergyManager(), GetDebugPlugs(), OnIsPlugged(), RefreshDebug(), SetDebugPlugs(), and UnplugDevice().
m_DebugUpdate
ref Timer ComponentEnergyManager::m_DebugUpdate protected
Definition at line 75 of file ComponentEnergyManager.c.
Referenced by DebugUpdate(), OnIsPlugged(), and RefreshDebug().
m_DeviceByPlugSelection
ref map<string, EntityAI> ComponentEnergyManager::m_DeviceByPlugSelection protected
Definition at line 71 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), GetPlugOwner(), and SetPlugOwner().
m_Energy
float ComponentEnergyManager::m_Energy protected
Definition at line 49 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), GetEnergy(), GetEnergy0To1(), GetEnergy0To100(), and SetEnergy().
m_EnergyAtSpawn
float ComponentEnergyManager::m_EnergyAtSpawn protected
Definition at line 50 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), and GetEnergyAtSpawn().
m_EnergySource
EntityAI ComponentEnergyManager::m_EnergySource protected
Definition at line 69 of file ComponentEnergyManager.c.
Referenced by GetEnergySource(), and SetEnergySource().
m_EnergySourceNetworkIDHigh
int ComponentEnergyManager::m_EnergySourceNetworkIDHigh = -1 protected
Definition at line 46 of file ComponentEnergyManager.c.
Referenced by GetEnergySourceNetworkIDHigh(), and SetEnergySource().
m_EnergySourceNetworkIDLow
int ComponentEnergyManager::m_EnergySourceNetworkIDLow = -1 protected
Definition at line 45 of file ComponentEnergyManager.c.
Referenced by GetEnergySourceNetworkIDLow(), and SetEnergySource().
m_EnergySourceStorageIDb1
int ComponentEnergyManager::m_EnergySourceStorageIDb1 protected
Definition at line 40 of file ComponentEnergyManager.c.
Referenced by GetEnergySourceStorageIDb1(), and StoreEnergySourceIDs().
m_EnergySourceStorageIDb2
int ComponentEnergyManager::m_EnergySourceStorageIDb2 protected
Definition at line 41 of file ComponentEnergyManager.c.
Referenced by GetEnergySourceStorageIDb2(), and StoreEnergySourceIDs().
m_EnergySourceStorageIDb3
int ComponentEnergyManager::m_EnergySourceStorageIDb3 protected
Definition at line 42 of file ComponentEnergyManager.c.
Referenced by GetEnergySourceStorageIDb3(), and StoreEnergySourceIDs().
m_EnergySourceStorageIDb4
int ComponentEnergyManager::m_EnergySourceStorageIDb4 protected
Definition at line 43 of file ComponentEnergyManager.c.
Referenced by GetEnergySourceStorageIDb4(), and StoreEnergySourceIDs().
m_EnergyStorageMax
float ComponentEnergyManager::m_EnergyStorageMax protected
Definition at line 51 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), GetEnergy0To1(), GetEnergy0To100(), GetEnergyMaxPristine(), and SetEnergyMaxPristine().
m_EnergyUsage
float ComponentEnergyManager::m_EnergyUsage protected
Definition at line 48 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), GetEnergyUsage(), ResetEnergyUsage(), and SetEnergyUsage().
m_HasElectricityIcon
bool ComponentEnergyManager::m_HasElectricityIcon protected
Definition at line 33 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), HasElectricityIcon(), and SetElectricityIconVisibility().
m_IsPassiveDevice
bool ComponentEnergyManager::m_IsPassiveDevice protected
Definition at line 26 of file ComponentEnergyManager.c.
Referenced by DeviceUpdate(), Event_OnAwake(), IsPassive(), SetPassiveState(), and StartUpdates().
m_IsPlugged
bool ComponentEnergyManager::m_IsPlugged protected
Definition at line 35 of file ComponentEnergyManager.c.
Referenced by IsPlugged(), and SetEnergySource().
m_IsSwichedOn
bool ComponentEnergyManager::m_IsSwichedOn protected
Definition at line 24 of file ComponentEnergyManager.c.
Referenced by IsSwitchedOn(), SwitchOff(), and SwitchOn().
m_IsSwichedOnPreviousState
bool ComponentEnergyManager::m_IsSwichedOnPreviousState protected
Definition at line 25 of file ComponentEnergyManager.c.
Referenced by GetPreviousSwitchState(), SwitchOff(), and SwitchOn().
m_IsWorking
bool ComponentEnergyManager::m_IsWorking protected
Definition at line 27 of file ComponentEnergyManager.c.
Referenced by IsWorking(), and SetPowered().
m_LastUpdateTime
float ComponentEnergyManager::m_LastUpdateTime protected
Definition at line 55 of file ComponentEnergyManager.c.
Referenced by ClearLastUpdateTime(), DeviceUpdate(), and RememberLastUpdateTime().
m_MySocketID
int ComponentEnergyManager::m_MySocketID = -1 protected
Definition at line 38 of file ComponentEnergyManager.c.
Referenced by GetMySocketID(), and SetMySocketID().
m_PluggedDevices
ref array<EntityAI> ComponentEnergyManager::m_PluggedDevices protected
Definition at line 70 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), and GetPluggedDevices().
m_PlugType
int ComponentEnergyManager::m_PlugType protected
Definition at line 39 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), GetPlugType(), and SetPlugType().
m_ReduceMaxEnergyByDamageCoef
float ComponentEnergyManager::m_ReduceMaxEnergyByDamageCoef protected
Definition at line 52 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), and GetEnergyMax().
m_RestorePlugState
bool ComponentEnergyManager::m_RestorePlugState protected
Definition at line 30 of file ComponentEnergyManager.c.
Referenced by GetRestorePlugState(), and RestorePlugState().
m_ShowSocketsInInventory
bool ComponentEnergyManager::m_ShowSocketsInInventory protected
Definition at line 32 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), and HasVisibleSocketsInInventory().
m_Sockets
EntityAI ComponentEnergyManager::m_Sockets[MAX_SOCKETS_COUNT] protected
Definition at line 78 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), GetDeviceBySocketID(), and SetDeviceBySocketID().
m_SocketsCount
float ComponentEnergyManager::m_SocketsCount protected
Definition at line 53 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), and GetSocketsCount().
m_UpdateInterval
float ComponentEnergyManager::m_UpdateInterval protected
Definition at line 57 of file ComponentEnergyManager.c.
Referenced by GetUpdateInterval(), and SetUpdateInterval().
m_UpdateQuantityTimer
ref Timer ComponentEnergyManager::m_UpdateQuantityTimer protected
Definition at line 74 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), and OnEnergyAdded().
m_UpdateTimer
ref Timer ComponentEnergyManager::m_UpdateTimer protected
Definition at line 73 of file ComponentEnergyManager.c.
Referenced by StartUpdates(), and StopUpdates().
m_WetnessExposure
float ComponentEnergyManager::m_WetnessExposure protected
Definition at line 56 of file ComponentEnergyManager.c.
Referenced by CheckWetness(), Event_OnAwake(), and GetWetnessExposure().
MAX_SOCKETS_COUNT
const int ComponentEnergyManager::MAX_SOCKETS_COUNT = 4 protected
Definition at line 77 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake().
SEL_CORD_FOLDED
const string ComponentEnergyManager::SEL_CORD_FOLDED = "cord_folded" static protected
Definition at line 66 of file ComponentEnergyManager.c.
Referenced by PlugInDevice(), UnplugDevice(), and UpdateSelections().
SEL_CORD_PLUGGED
const string ComponentEnergyManager::SEL_CORD_PLUGGED = "cord_plugged" static protected
Definition at line 65 of file ComponentEnergyManager.c.
Referenced by ActionUnplugThisByCord::ActionCondition(), Event_OnAwake(), PlugInDevice(), UnplugDevice(), and UpdateSelections().
SOCKET_
const string ComponentEnergyManager::SOCKET_ = "socket_" static protected
Definition at line 62 of file ComponentEnergyManager.c.
Referenced by Event_OnAwake(), IsSelectionAPlug(), UnplugCordFromSocket(), UpdateSelections(), and UpdateSocketSelections().
The documentation for this class was generated from the following file:
scripts/3_Game/tools/Component/ComponentEnergyManager.c