DayZ: scripts/4_World/Systems/Inventory/DayZPlayerInventory.c File Reference
DayZPlayerInventory.c File Reference
Classes
class DeferredEvent
class DeferredSwapEntities
class DeferredHandEvent
Functions
void DeferredTakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
override bool ReserveInventory (HumanInventory inventory)
override void ClearInventoryReservation (HumanInventory inventory)
void DeferredForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation dst1, notnull InventoryLocation dst2)
void DeferredHandEvent (InventoryMode mode, HandEventBase e)
void DayZPlayerInventory ()
DayZPlayer GetDayZPlayerOwner ()
bool IsAuthoritative ()
bool IsOwner ()
bool IsProxy ()
override void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
void CancelHandEvent ()
cancels any handevents that will be executed this frame @NOTE: this is used in situations where the player performs an action that renders the event invalid exactly on the frame it will be executed
void CancelWeaponEvent ()
void AbortWeaponEvent ()
void PostWeaponEvent (WeaponEventBase e)
void DeferredWeaponFailed ()
void HandleWeaponEvents (float dt, out bool exitIronSights)
void HandleInventory (float dt)
void OnInputUserDataForRemote (ParamsReadContext ctx)
override void OnServerInventoryCommand (ParamsReadContext ctx)
bool ValidateSyncMove (inout Serializer ctx, InventoryValidation validation)
bool ValidateHandEvent (inout Serializer ctx, InventoryValidation validation)
bool ValidateSwap (inout Serializer ctx, InventoryValidation validation)
bool ValidateDestroy (inout Serializer ctx, InventoryValidation validation)
bool ProcessInputData (ParamsReadContext ctx, bool isJuncture, bool isRemote)
void RemoveMovableOverride (EntityAI item)
void EnableMovableOverride (EntityAI item)
void CheckForRope (InventoryLocation src, InventoryLocation dst)
bool IsServerOrLocalPlayer ()
bool StoreInputForRemotes (bool handling_juncture, bool remote, ParamsReadContext ctx)
override bool TakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
void HandleTakeToDst (DeferredEvent deferred_event)
override bool SwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2)
void HandleSwapEntities (DeferredEvent deferred_event)
override bool ForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
void HandleForceSwapEntities (DeferredEvent deferred_event)
static void SendServerHandEventViaJuncture (notnull DayZPlayer player, HandEventBase e)
override void NetSyncCurrentStateID (int id)
override void OnAfterStoreLoad ()
engine reaction to load from database originates in: engine - Person::BinLoad script - PlayerBase.OnAfterStoreLoad
bool OnEventForRemoteWeapon (ParamsReadContext ctx)
bool OnHandEventForRemote (ParamsReadContext ctx)
void SyncHandEventToRemote (HandEventBase e)
override void OnHandsExitedStableState (HandStateBase src, HandStateBase dst)
override void OnHandsEnteredStableState (HandStateBase src, HandStateBase dst)
override void OnHandsStateChanged (HandStateBase src, HandStateBase dst)
override bool HandEvent (InventoryMode mode, HandEventBase e)
void HandleHandEvent (DeferredEvent deferred_event)
override void HandleInventoryManipulation ()
bool IsProcessing ()
bool PlayerCheckRequestSrc (notnull InventoryLocation src, float radius)
bool PlayerCheckRequestDst (notnull InventoryLocation src, notnull InventoryLocation dst, float radius)
bool PlayerCheckSwapItemsRequest (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, float radius)
bool PlayerCheckDropRequest (notnull InventoryLocation src, float radius)
override bool OnInventoryJunctureFromServer (ParamsReadContext ctx)
override bool OnInventoryJunctureRepairFromServer (ParamsReadContext ctx)
override void OnInventoryJunctureFailureFromServer (ParamsReadContext ctx)
override void OnInventoryFailure (InventoryCommandType type, InventoryValidationReason reason, InventoryLocation src, InventoryLocation dst)
void OnHandleStoredJunctureData (ParamsReadContext ctx)
proto native void StoreJunctureData (ParamsReadContext ctx)
override bool OnInputUserDataProcess (ParamsReadContext ctx)
void OnHandleStoredInputUserData (ParamsReadContext ctx)
proto native void StoreInputUserData (ParamsReadContext ctx)
Variables
class DeferredEvent m_src
ref InventoryLocation m_dst
DeferredSwapEntities m_item1
EntityAI m_item2
ref InventoryLocation m_dst1
ref InventoryLocation m_dst2
ref HandEventBase m_event
m_DeferredEvent = NULL
ref Timer m_DeferredWeaponTimer = new Timer
ref HandEventBase m_DeferredPostedHandEvent = NULL
ref WeaponEventBase m_DeferredWeaponEvent = NULL
deferred hand event
ref HandAnimatedTakingFromAtt m_Taking
deferred weapon event
ref HandAnimatedMovingToAtt m_MovingTo
ref HandAnimatedSwapping m_Swapping
ref HandAnimatedForceSwapping m_FSwapping
ref HandAnimatedForceSwapping_Inst m_FSwappingInst
Function Documentation
AbortWeaponEvent()
void AbortWeaponEvent () protected
Definition at line 255 of file DayZPlayerInventory.c.
  {
    HumanCommandWeapons hcw = GetDayZPlayerOwner().GetCommandModifier_Weapons();
    Weapon_Base weapon;
    Class.CastTo(weapon, GetEntityInHands());
    if (hcw && weapon && weapon.CanProcessWeaponEvents() && !weapon.IsIdle())
    {
      if (LogManager.IsWeaponLogEnable())
        wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(weapon) + " Weapon event: ABORT! notifying running state=" + weapon.GetCurrentState());
      weapon.ProcessWeaponAbortEvent(new WeaponEventHumanCommandActionAborted(GetDayZPlayerOwner()));
    }
  }
References Class::CastTo(), GetDayZPlayerOwner(), LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
Referenced by ManBase::OnCommandClimbStart(), ManBase::OnCommandDeathStart(), ManBase::OnCommandFallStart(), ManBase::OnCommandMelee2Start(), ManBase::OnCommandSwimStart(), ManBase::OnJumpStart(), and ManBase::OnStanceChange().
CancelHandEvent()
CancelHandEvent () protected
cancels any handevents that will be executed this frame @NOTE: this is used in situations where the player performs an action that renders the event invalid exactly on the frame it will be executed
Definition at line 243 of file DayZPlayerInventory.c.
  {
    m_DeferredPostedHandEvent = null;
    //m_postedHandEvent = null;
  }
References m_DeferredPostedHandEvent.
CancelWeaponEvent()
void CancelWeaponEvent () protected
Definition at line 249 of file DayZPlayerInventory.c.
  {
    m_DeferredWeaponEvent = null;
    m_DeferredWeaponTimer.Stop();
  }
References m_DeferredWeaponEvent, and m_DeferredWeaponTimer.
Referenced by DeferredWeaponFailed().
CheckForRope()
void CheckForRope (InventoryLocation src, InventoryLocation dst) protected
Definition at line 1392 of file DayZPlayerInventory.c.
  {
    Rope rope = Rope.Cast(src.GetItem());
    if (rope)
      rope.SetTargetLocation(dst);
  }
Referenced by ValidateHandEvent(), and ValidateSyncMove().
ClearInventoryReservation()
override void ClearInventoryReservation (HumanInventory inventory)
Definition at line 29 of file DayZPlayerInventory.c.
  {
    inventory.ClearInventoryReservationEx(m_dst.GetItem(), m_dst);
  }
References m_dst.
DayZPlayerInventory()
void DayZPlayerInventory () protected
Definition at line 145 of file DayZPlayerInventory.c.
  {
  }
DeferredForceSwapEntities()
void DeferredForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation dst1, notnull InventoryLocation dst2)
Definition at line 77 of file DayZPlayerInventory.c.
  {
    m_mode = mode;
    m_item1 = item1;
    m_item2 = item2;
    m_dst1 = dst1;
    m_dst2 = dst2;
  }
References m_dst1, m_dst2, m_item1, and m_item2.
Referenced by ForceSwapEntities(), and HandleForceSwapEntities().
DeferredHandEvent()
void DayZPlayerInventory::DeferredHandEvent (InventoryMode mode, HandEventBase e)
Definition at line 108 of file DayZPlayerInventory.c.
  {
    m_mode = mode;
    m_event = e;
  }
Referenced by HandEvent().
DeferredTakeToDst()
void DeferredTakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
Definition at line 15 of file DayZPlayerInventory.c.
  {
    m_mode = mode;
    m_src = src;
    m_dst = dst;
  }
References m_dst, and m_src.
Referenced by HandleTakeToDst(), and TakeToDst().
DeferredWeaponFailed()
void DeferredWeaponFailed () protected
Definition at line 288 of file DayZPlayerInventory.c.
  {
    Weapon_Base weapon;
    Class.CastTo(weapon, GetEntityInHands());
    string secondPart = " - ENTITY IN HANDS IS NOT A WEAPON: " + Object.GetDebugName(GetEntityInHands());
    string firstPart = "[wpnfsm] " + Object.GetDebugName(GetInventoryOwner()) + " failed to perform weaponevent " + m_DeferredWeaponEvent.DumpToString();
    if (weapon)
    {
      secondPart = " on " + Object.GetDebugName(GetEntityInHands()) + " which is in state " + weapon.GetCurrentState();
      secondPart += " with physical state: J: " + weapon.IsJammed() + " | ";
      for (int i = 0; i < weapon.GetMuzzleCount(); ++i)
      {
        secondPart += "Chamber_" + i + ": B(" + weapon.IsChamberFull(i) + ") F(" + weapon.IsChamberFiredOut(i) + ") E(" + weapon.IsChamberEmpty(i) + ") | ";
        secondPart += "Magazine_" + i + ": " + weapon.GetMagazine(i);
        if (i < weapon.GetMuzzleCount() - 1)
          secondPart += " | ";
      }
    }
    Error(firstPart + secondPart);
    CancelWeaponEvent();
  }
References CancelWeaponEvent(), Class::CastTo(), Error(), and m_DeferredWeaponEvent.
EnableMovableOverride()
void EnableMovableOverride (EntityAI item) protected
Definition at line 1384 of file DayZPlayerInventory.c.
  {
    ItemBase itemIB = ItemBase.Cast(item);
    if (itemIB)
      itemIB.SetCanBeMovedOverride(true);
  }
Referenced by HandleHandEvent(), HandleSwapEntities(), HandleTakeToDst(), ValidateHandEvent(), ValidateSwap(), and ValidateSyncMove().
ForceSwapEntities()
override bool ForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) protected
Definition at line 1671 of file DayZPlayerInventory.c.
  {
#ifdef DEVELOPER
    if (LogManager.IsInventoryMoveLogEnable())
      Debug.InventoryMoveLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item1 = " + item1 + " item2 = " + item2 + " dst=" + InventoryLocation.DumpToStringNullSafe(item2_dst), "n/a", "n/a", "ForceSwapEntities", GetDayZPlayerOwner().ToString());
#endif
    if (mode == InventoryMode.LOCAL)
    {
      InventoryLocation src1, src2, dst1;
      if (GameInventory.MakeSrcAndDstForForceSwap(item1, item2, src1, src2, dst1, item2_dst))
      {
        LocationSwap(src1, src2, dst1, item2_dst);
        return true;
      }
    }
    if (!super.ForceSwapEntities(mode, item1, item2, item2_dst))
    {
      if (!m_DeferredEvent)
      {
        if (GameInventory.MakeSrcAndDstForForceSwap(item1, item2, src1, src2, dst1, item2_dst))
        {
          m_DeferredEvent = new DeferredForceSwapEntities(mode, item1, item2, dst1, item2_dst);
          if (m_DeferredEvent.ReserveInventory(this))
            return true;
        }
      }
      m_DeferredEvent = null;
      return false;
    }
    return true;
  }
References DeferredForceSwapEntities(), InventoryLocation::DumpToStringNullSafe(), GetDayZPlayerOwner(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), m_DeferredEvent, GameInventory::MakeSrcAndDstForForceSwap(), and ToString().
GetDayZPlayerOwner()
DayZPlayer GetDayZPlayerOwner () protected
Definition at line 149 of file DayZPlayerInventory.c.
{ return DayZPlayer.Cast(GetInventoryOwner()); }
Referenced by AbortWeaponEvent(), ForceSwapEntities(), HandEvent(), HandleForceSwapEntities(), HandleHandEvent(), HandleInventory(), HandleSwapEntities(), HandleTakeToDst(), HandleWeaponEvents(), IsServerOrLocalPlayer(), NetSyncCurrentStateID(), OnAfterStoreLoad(), OnEventForRemoteWeapon(), OnHandleStoredInputUserData(), OnHandleStoredJunctureData(), OnHandsStateChanged(), OnInputUserDataForRemote(), OnInputUserDataProcess(), OnInventoryJunctureFromServer(), OnServerInventoryCommand(), PlayerCheckDropRequest(), PlayerCheckRequestDst(), PlayerCheckRequestSrc(), PlayerCheckSwapItemsRequest(), ProcessInputData(), StoreInputForRemotes(), SwapEntities(), SyncHandEventToRemote(), TakeToDst(), ValidateDestroy(), ValidateHandEvent(), ValidateSwap(), and ValidateSyncMove().
HandEvent()
override bool HandEvent (InventoryMode mode, HandEventBase e) protected
Let the client know a failure happened
If singleplayer or the client is executing this
Definition at line 1952 of file DayZPlayerInventory.c.
  {
    if (!IsProcessing())
    {
      EntityAI itemInHands = GetEntityInHands();
      InventoryLocation handInventoryLocation();
      handInventoryLocation.SetHands(GetInventoryOwner(), itemInHands);
      InventoryValidation validation();
      if (e.CanPerformEventEx(validation))
      {
        m_DeferredEvent = new DeferredHandEvent(mode, e);
        if (m_DeferredEvent.ReserveInventory(this))
          return true;
      }
      m_DeferredEvent = null;
      if (!GetGame().IsMultiplayer() || GetGame().IsClient())
      {
        OnInventoryFailure(InventoryCommandType.HAND_EVENT, validation.m_Reason, e.GetSrc(), e.GetDst());
      }
      else
      {
        ScriptInputUserData serializer();
        InventoryInputUserData.SerializeHandEvent(serializer, e);
        serializer.Write(validation.m_Reason);
        GetDayZPlayerOwner().SendSyncJuncture(DayZPlayerSyncJunctures.SJ_INVENTORY_FAILURE, serializer);
      }
    }
    return false;
  }
References DeferredHandEvent(), GetDayZPlayerOwner(), GetGame(), IsProcessing(), m_DeferredEvent, OnInventoryFailure(), InventoryInputUserData::SerializeHandEvent(), and DayZPlayerSyncJunctures::SJ_INVENTORY_FAILURE.
HandleForceSwapEntities()
void HandleForceSwapEntities (DeferredEvent deferred_event) protected
Definition at line 1708 of file DayZPlayerInventory.c.
  {
    DeferredForceSwapEntities deferred_force_swap_entities = DeferredForceSwapEntities.Cast(deferred_event);
    if (deferred_force_swap_entities)
    {
      deferred_force_swap_entities.ClearInventoryReservation(this);
      InventoryLocation src1 = new InventoryLocation;
      InventoryLocation src2 = new InventoryLocation;
      deferred_force_swap_entities.m_item1.GetInventory().GetCurrentInventoryLocation(src1);
      deferred_force_swap_entities.m_item2.GetInventory().GetCurrentInventoryLocation(src2);
      DayZPlayer player = GetGame().GetPlayer();
      if (LogManager.IsInventoryMoveLogEnable())
        inventoryDebugPrint("[inv] I::FSwap(" + typename.EnumToString(InventoryMode, deferred_force_swap_entities.m_mode) + ") src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) + " dst1=" + InventoryLocation.DumpToStringNullSafe(deferred_force_swap_entities.m_dst1) + " dst2=" + InventoryLocation.DumpToStringNullSafe(deferred_force_swap_entities.m_dst2));
      switch (deferred_force_swap_entities.m_mode)
      {
      case InventoryMode.PREDICTIVE:
        if (CanForceSwapEntitiesEx(deferred_force_swap_entities.m_dst1.GetItem(), deferred_force_swap_entities.m_dst1, deferred_force_swap_entities.m_dst2.GetItem(), deferred_force_swap_entities.m_dst2))
        {
          InventoryInputUserData.SendInputUserDataSwap(src1, src2, deferred_force_swap_entities.m_dst1, deferred_force_swap_entities.m_dst2);
          LocationSwap(src1, src2, deferred_force_swap_entities.m_dst1, deferred_force_swap_entities.m_dst2);
        }
        else
        {
#ifdef DEVELOPER
          if (LogManager.IsInventoryMoveLogEnable())
            Debug.InventoryMoveLog("Can not force swap (PREDICTIVE) STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item1 = " + deferred_force_swap_entities.m_dst1.GetItem() + " item2 = " + deferred_force_swap_entities.m_dst2.GetItem() + " dst=" + InventoryLocation.DumpToStringNullSafe(deferred_force_swap_entities.m_dst2), "n/a", "n/a", "ForceSwapEntities", GetDayZPlayerOwner().ToString());
#endif
        }
        break;
      case InventoryMode.JUNCTURE:
        if (CanForceSwapEntitiesEx(deferred_force_swap_entities.m_dst1.GetItem(), deferred_force_swap_entities.m_dst1, deferred_force_swap_entities.m_dst2.GetItem(), deferred_force_swap_entities.m_dst2))
        {
          player.GetHumanInventory().AddInventoryReservationEx(deferred_force_swap_entities.m_item1, deferred_force_swap_entities.m_dst1, GameInventory.c_InventoryReservationTimeoutShortMS);
          player.GetHumanInventory().AddInventoryReservationEx(deferred_force_swap_entities.m_item2, deferred_force_swap_entities.m_dst2, GameInventory.c_InventoryReservationTimeoutShortMS);
          InventoryInputUserData.SendInputUserDataSwap(src1, src2, deferred_force_swap_entities.m_dst1, deferred_force_swap_entities.m_dst2);
        }
        else
        {
#ifdef DEVELOPER
          if (LogManager.IsInventoryMoveLogEnable())
            Debug.InventoryMoveLog("Can not force swap (JUNCTURE) STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item1 = " + deferred_force_swap_entities.m_dst1.GetItem() + " item2 = " + deferred_force_swap_entities.m_dst2.GetItem() + " dst=" + InventoryLocation.DumpToStringNullSafe(deferred_force_swap_entities.m_dst2), "n/a", "n/a", "ForceSwapEntities", GetDayZPlayerOwner().ToString());
#endif
        }
        break;
      case InventoryMode.LOCAL:
        break;
      default:
        Error("ForceSwapEntities - HandEvent - Invalid mode");
      }
    }
  }
References GameInventory::c_InventoryReservationTimeoutShortMS, DeferredForceSwapEntities(), InventoryLocation::DumpToStringNullSafe(), Error(), GetDayZPlayerOwner(), GetGame(), inventoryDebugPrint(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), InventoryInputUserData::SendInputUserDataSwap(), and ToString().
Referenced by HandleInventoryManipulation().
HandleHandEvent()
void HandleHandEvent (DeferredEvent deferred_event) protected
Default structure suffices
Definition at line 1992 of file DayZPlayerInventory.c.
  {
    InventoryValidation validation();
    DeferredHandEvent deferred_hand_event = DeferredHandEvent.Cast(deferred_event);
    if (deferred_hand_event)
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryHFSMLogEnable())
        Debug.InventoryHFSMLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp(), "n/a", "n/a", "HandleHandEvent", GetDayZPlayerOwner().ToString());
#endif
      if (LogManager.IsInventoryHFSMLogEnable())
        hndDebugPrint("[inv] HumanInventory::HandEvent(" + typename.EnumToString(InventoryMode, deferred_hand_event.m_mode) + ") ev=" + deferred_hand_event.m_event.DumpToString());
      switch (deferred_hand_event.m_mode)
      {
      case InventoryMode.PREDICTIVE:
#ifdef DEVELOPER
        if (LogManager.IsInventoryHFSMLogEnable())
          Debug.InventoryHFSMLog("PREDICTIVE", "n/a", "n/a", "HandleHandEvent", GetDayZPlayerOwner().ToString());
#endif
        deferred_hand_event.ClearInventoryReservation(this);
        if (deferred_hand_event.m_event.CanPerformEventEx(validation))
        {
          InventoryInputUserData.SendInputUserDataHandEvent(deferred_hand_event.m_event);
          ProcessHandEvent(deferred_hand_event.m_event);
        }
        break;
      case InventoryMode.JUNCTURE:
#ifdef DEVELOPER
        if (LogManager.IsInventoryHFSMLogEnable())
          Debug.InventoryHFSMLog("JUNCTURE", "n/a", "n/a", "HandleHandEvent", GetDayZPlayerOwner().ToString());
#endif
        deferred_hand_event.ClearInventoryReservation(this);
        if (deferred_hand_event.m_event.CanPerformEventEx(validation))
        {
          deferred_hand_event.ReserveInventory(this);
          InventoryInputUserData.SendInputUserDataHandEvent(deferred_hand_event.m_event);
          //Functionality to prevent desync when two players perform interfering action at the same time
          EntityAI itemSrc = deferred_hand_event.m_event.GetSrcEntity();
          EntityAI itemDst = null;
          if (deferred_hand_event.m_event.GetDst())
            itemDst = deferred_hand_event.m_event.GetDst().GetItem();
          if (itemSrc)
            EnableMovableOverride(itemSrc);
          if (itemDst)
            EnableMovableOverride(itemDst);
        }
        break;
      case InventoryMode.LOCAL:
#ifdef DEVELOPER
        if (LogManager.IsInventoryHFSMLogEnable())
          Debug.InventoryHFSMLog("LOCAL", "n/a", "n/a", "HandleHandEvent", GetDayZPlayerOwner().ToString());
#endif
        deferred_hand_event.ClearInventoryReservation(this);
        ProcessHandEvent(deferred_hand_event.m_event);
        //PostHandEvent(deferred_hand_event.m_event);
        break;
      case InventoryMode.SERVER:
#ifdef DEVELOPER
        if (LogManager.IsInventoryHFSMLogEnable())
          Debug.InventoryHFSMLog("SERVER", "n/a", "n/a", "HandleHandEvent", GetDayZPlayerOwner().ToString());
#endif
        if (LogManager.IsInventoryHFSMLogEnable())
          hndDebugPrint("[inv] DZPI::HandEvent(" + typename.EnumToString(InventoryMode, deferred_hand_event.m_mode) + ")");
        if (!deferred_hand_event.m_event.IsServerSideOnly())
        {
          if (GetDayZPlayerOwner().IsAlive())
            SendServerHandEventViaJuncture(GetDayZPlayerOwner(), deferred_hand_event.m_event);
          else
            InventoryInputUserData.SendServerHandEventViaInventoryCommand(GetDayZPlayerOwner(), deferred_hand_event.m_event);
        }
        else
          ProcessHandEvent(deferred_hand_event.m_event);
        break;
      default:
        Error("HumanInventory::HandEvent - Invalid mode");
      }
    }
  }
References EnableMovableOverride(), Error(), GetDayZPlayerOwner(), hndDebugPrint(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), InventoryInputUserData::SendInputUserDataHandEvent(), InventoryInputUserData::SendServerHandEventViaInventoryCommand(), SendServerHandEventViaJuncture(), and ToString().
Referenced by HandleInventoryManipulation().
HandleInventory()
void HandleInventory (float dt) protected
Definition at line 387 of file DayZPlayerInventory.c.
  {
    HumanCommandWeapons hcw = GetDayZPlayerOwner().GetCommandModifier_Weapons();
    EntityAI ih = GetEntityInHands();
    Weapon_Base weapon;
    Class.CastTo(weapon, ih);
    if (hcw)
    {
      m_FSM.GetCurrentState().OnUpdate(dt);
#ifdef DEVELOPER
      if (LogManager.IsInventoryHFSMLogEnable())
        hndDebugSpamALot("[hndfsm] HCW: playing A=" + typename.EnumToString(WeaponActions, hcw.GetRunningAction()) + " AT=" + WeaponActionTypeToString(hcw.GetRunningAction(), hcw.GetRunningActionType()) + " fini=" + hcw.IsActionFinished());
#endif
      if (!m_FSM.GetCurrentState().IsIdle() || !m_FSM.IsRunning())
      {
        while (true)
        {
          int weaponEventId = hcw.IsEvent();
          if (weaponEventId == -1)
            break;
          HandEventBase anim_event = HandAnimEventFactory(weaponEventId, GetManOwner(), NULL);
#ifdef DEVELOPER
          if (LogManager.IsInventoryHFSMLogEnable())
            hndDebugPrint("[hndfsm] HandleInventory: event arrived " + typename.EnumToString(WeaponEvents, weaponEventId) + "(" + weaponEventId + ")  fsm_ev=" + anim_event.ToString());
#endif
          if (anim_event != NULL)
          {
            SyncHandEventToRemote(anim_event);
            ProcessHandEvent(anim_event);
          }
        }
        if (hcw.IsActionFinished())
        {
          if (m_FSM.GetCurrentState().IsWaitingForActionFinish())
          {
#ifdef DEVELOPER
            if (LogManager.IsInventoryHFSMLogEnable())
              hndDebugPrint("[hndfsm] Hand-Weapon event: finished! notifying waiting state=" + m_FSM.GetCurrentState());
#endif
            HandEventBase fin_event = new HandEventHumanCommandActionFinished(GetManOwner());
            SyncHandEventToRemote(fin_event);
            ProcessHandEvent(fin_event);
          }
          else
          {
#ifdef DEVELOPER
            if (LogManager.IsInventoryHFSMLogEnable())
              hndDebugPrint("[hndfsm] Hand-Weapon event: ABORT! notifying running state=" + m_FSM.GetCurrentState());
#endif
            HandEventBase abt_event = new HandEventHumanCommandActionAborted(GetManOwner());
            SyncHandEventToRemote(abt_event);
            ProcessHandAbortEvent(abt_event);
            //m_FSM.ProcessHandAbortEvent(new WeaponEventHumanCommandActionAborted(GetManOwner()));
          }
        }
      }
    }
  }
References Class::CastTo(), GetDayZPlayerOwner(), HandAnimEventFactory(), hndDebugPrint(), hndDebugSpamALot(), LogManager::IsInventoryHFSMLogEnable(), SyncHandEventToRemote(), and WeaponActionTypeToString().
HandleInventoryManipulation()
override void HandleInventoryManipulation () protected
Definition at line 2085 of file DayZPlayerInventory.c.
  {
    super.HandleInventoryManipulation();
    if (m_DeferredEvent && ScriptInputUserData.CanStoreInputUserData())
    {
      HandleHandEvent(m_DeferredEvent);
      HandleTakeToDst(m_DeferredEvent);
      HandleSwapEntities(m_DeferredEvent);
      HandleForceSwapEntities(m_DeferredEvent);
      m_DeferredEvent = null;
    }
  }
References ScriptInputUserData::CanStoreInputUserData(), HandleForceSwapEntities(), HandleHandEvent(), HandleSwapEntities(), HandleTakeToDst(), and m_DeferredEvent.
HandleSwapEntities()
void HandleSwapEntities (DeferredEvent deferred_event) protected
Definition at line 1611 of file DayZPlayerInventory.c.
  {
    DeferredSwapEntities deferred_swap_entities = DeferredSwapEntities.Cast(deferred_event);
    if (deferred_swap_entities)
    {
      deferred_swap_entities.ClearInventoryReservation(this);
      InventoryLocation src1, src2, dst1, dst2;
      if (GameInventory.MakeSrcAndDstForSwap(deferred_swap_entities.m_item1, deferred_swap_entities.m_item2, src1, src2, dst1, dst2))
      {
        if (LogManager.IsInventoryMoveLogEnable())
          inventoryDebugPrint("[inv] I::Swap(" + typename.EnumToString(InventoryMode, deferred_swap_entities.m_mode) + ") src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) + " dst1=" + InventoryLocation.DumpToStringNullSafe(deferred_swap_entities.m_dst1) + " dst2=" + InventoryLocation.DumpToStringNullSafe(deferred_swap_entities.m_dst2));
        switch (deferred_swap_entities.m_mode)
        {
        case InventoryMode.PREDICTIVE:
          if (CanSwapEntitiesEx(deferred_swap_entities.m_dst1.GetItem(), deferred_swap_entities.m_dst2.GetItem()))
          {
            InventoryInputUserData.SendInputUserDataSwap(src1, src2, deferred_swap_entities.m_dst1, deferred_swap_entities.m_dst2);
            LocationSwap(src1, src2, deferred_swap_entities.m_dst1, deferred_swap_entities.m_dst2);
          }
          else
          {
#ifdef DEVELOPER
            if (LogManager.IsInventoryMoveLogEnable())
              Debug.InventoryMoveLog("Can not swap (PREDICTIVE) STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item1 = " + deferred_swap_entities.m_dst1.GetItem() + " item2 = " + deferred_swap_entities.m_dst2.GetItem() + " dst=" + InventoryLocation.DumpToStringNullSafe(deferred_swap_entities.m_dst2), "n/a", "n/a", "ForceSwapEntities", GetDayZPlayerOwner().ToString());
#endif
          }
          break;
        case InventoryMode.JUNCTURE:
          if (CanSwapEntitiesEx(deferred_swap_entities.m_dst1.GetItem(), deferred_swap_entities.m_dst2.GetItem()))
          {
            DayZPlayer player = GetGame().GetPlayer();
            player.GetHumanInventory().AddInventoryReservationEx(deferred_swap_entities.m_dst1.GetItem(), deferred_swap_entities.m_dst1, GameInventory.c_InventoryReservationTimeoutShortMS);
            player.GetHumanInventory().AddInventoryReservationEx(deferred_swap_entities.m_dst2.GetItem(), deferred_swap_entities.m_dst2, GameInventory.c_InventoryReservationTimeoutShortMS);
            EnableMovableOverride(deferred_swap_entities.m_dst1.GetItem());
            EnableMovableOverride(deferred_swap_entities.m_dst2.GetItem());
            InventoryInputUserData.SendInputUserDataSwap(src1, src2, deferred_swap_entities.m_dst1, deferred_swap_entities.m_dst2);
          }
          else
          {
#ifdef DEVELOPER
            if (LogManager.IsInventoryMoveLogEnable())
              Debug.InventoryMoveLog("Can not swap (JUNCTURE) STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item1 = " + deferred_swap_entities.m_dst1.GetItem() + " item2 = " + deferred_swap_entities.m_dst2.GetItem() + " dst=" + InventoryLocation.DumpToStringNullSafe(deferred_swap_entities.m_dst2), "n/a", "n/a", "ForceSwapEntities", GetDayZPlayerOwner().ToString());
#endif
          }
          break;
        case InventoryMode.LOCAL:
          break;
        default:
          Error("SwapEntities - HandEvent - Invalid mode");
        }
      }
      else
        Error("SwapEntities - MakeSrcAndDstForSwap - no inv loc");
    }
  }
References GameInventory::c_InventoryReservationTimeoutShortMS, InventoryLocation::DumpToStringNullSafe(), EnableMovableOverride(), Error(), GetDayZPlayerOwner(), GetGame(), inventoryDebugPrint(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), GameInventory::MakeSrcAndDstForSwap(), InventoryInputUserData::SendInputUserDataSwap(), and ToString().
Referenced by HandleInventoryManipulation().
HandleTakeToDst()
void HandleTakeToDst (DeferredEvent deferred_event) protected
Definition at line 1501 of file DayZPlayerInventory.c.
  {
    DeferredTakeToDst deferred_take_to_dst = DeferredTakeToDst.Cast(deferred_event);
    if (deferred_take_to_dst)
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryHFSMLogEnable())
        Debug.InventoryHFSMLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp(), "n/a", "n/a", "HandleTakeToDst", GetDayZPlayerOwner().ToString());
#endif
      deferred_take_to_dst.ClearInventoryReservation(this);
      if (LogManager.IsInventoryMoveLogEnable())
        inventoryDebugPrint("[inv] I::Take2Dst(" + typename.EnumToString(InventoryMode, deferred_take_to_dst.m_mode) + ") src=" + InventoryLocation.DumpToStringNullSafe(deferred_take_to_dst.m_src) + " dst=" + InventoryLocation.DumpToStringNullSafe(deferred_take_to_dst.m_dst));
      switch (deferred_take_to_dst.m_mode)
      {
      case InventoryMode.PREDICTIVE:
#ifdef DEVELOPER
        if (LogManager.IsInventoryHFSMLogEnable())
          Debug.InventoryHFSMLog("PREDICTIVE ", "n/a", "n/a", "HandleTakeToDst", GetDayZPlayerOwner().ToString());
#endif
        if (LocationCanMoveEntity(deferred_take_to_dst.m_src, deferred_take_to_dst.m_dst))
        {
          InventoryInputUserData.SendInputUserDataMove(InventoryCommandType.SYNC_MOVE, deferred_take_to_dst.m_src, deferred_take_to_dst.m_dst);
          LocationSyncMoveEntity(deferred_take_to_dst.m_src, deferred_take_to_dst.m_dst);
        }
        else
        {
#ifdef DEVELOPER
          if (LogManager.IsInventoryMoveLogEnable())
            Debug.InventoryMoveLog("Can not move entity (PREDICTIVE) STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item = " + deferred_take_to_dst.m_dst.GetItem() + " dst=" + InventoryLocation.DumpToStringNullSafe(deferred_take_to_dst.m_dst), "n/a", "n/a", "HandleTakeToDst", GetDayZPlayerOwner().ToString());
#endif
        }
        break;
      case InventoryMode.JUNCTURE:
#ifdef DEVELOPER
        if (LogManager.IsInventoryHFSMLogEnable())
          Debug.InventoryHFSMLog("JUNCTURE ", "n/a", "n/a", "HandleTakeToDst", GetDayZPlayerOwner().ToString());
#endif
        if (LocationCanMoveEntity(deferred_take_to_dst.m_src, deferred_take_to_dst.m_dst))
        {
          DayZPlayer player = GetGame().GetPlayer();
          player.GetHumanInventory().AddInventoryReservationEx(deferred_take_to_dst.m_dst.GetItem(), deferred_take_to_dst.m_dst, GameInventory.c_InventoryReservationTimeoutShortMS);
          EnableMovableOverride(deferred_take_to_dst.m_dst.GetItem());
          InventoryInputUserData.SendInputUserDataMove(InventoryCommandType.SYNC_MOVE, deferred_take_to_dst.m_src, deferred_take_to_dst.m_dst);
        }
        else
        {
#ifdef DEVELOPER
          if (LogManager.IsInventoryMoveLogEnable())
            Debug.InventoryMoveLog("Can not move entity (JUNCTURE) STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item = " + deferred_take_to_dst.m_dst.GetItem() + " dst=" + InventoryLocation.DumpToStringNullSafe(deferred_take_to_dst.m_dst), "n/a", "n/a", "HandleTakeToDst", GetDayZPlayerOwner().ToString());
#endif
        }
        break;
      case InventoryMode.LOCAL:
#ifdef DEVELOPER
        if (LogManager.IsInventoryHFSMLogEnable())
          Debug.InventoryHFSMLog("LOCAL ", "n/a", "n/a", "HandleTakeToDst", GetDayZPlayerOwner().ToString());
#endif
        break;
      case InventoryMode.SERVER:
#ifdef DEVELOPER
        if (LogManager.IsInventoryHFSMLogEnable())
          Debug.InventoryHFSMLog("SERVER ", "n/a", "n/a", "HandleTakeToDst", GetDayZPlayerOwner().ToString());
#endif
        break;
      default:
        Error("HandEvent - Invalid mode");
        break;
      }
    }
  }
References GameInventory::c_InventoryReservationTimeoutShortMS, DeferredTakeToDst(), InventoryLocation::DumpToStringNullSafe(), EnableMovableOverride(), Error(), GetDayZPlayerOwner(), GetGame(), inventoryDebugPrint(), Debug::InventoryHFSMLog(), Debug::InventoryMoveLog(), LogManager::IsInventoryHFSMLogEnable(), LogManager::IsInventoryMoveLogEnable(), InventoryInputUserData::SendInputUserDataMove(), and ToString().
Referenced by HandleInventoryManipulation().
HandleWeaponEvents()
void HandleWeaponEvents (float dt, out bool exitIronSights) protected
Definition at line 313 of file DayZPlayerInventory.c.
  {
    HumanCommandWeapons hcw = GetDayZPlayerOwner().GetCommandModifier_Weapons();
    Weapon_Base weapon;
    Class.CastTo(weapon, GetEntityInHands());
    if (hcw && weapon && weapon.CanProcessWeaponEvents())
    {
      weapon.GetCurrentState().OnUpdate(dt);
      if (LogManager.IsWeaponLogEnable())
        wpnDebugSpamALot("[wpnfsm] " + Object.GetDebugName(weapon) + " HCW: playing A=" + typename.EnumToString(WeaponActions, hcw.GetRunningAction()) + " AT=" + WeaponActionTypeToString(hcw.GetRunningAction(), hcw.GetRunningActionType()) + " fini=" + hcw.IsActionFinished());
      if (!weapon.IsIdle())
      {
        while (true)
        {
          int weaponEventId = hcw.IsEvent();
          if (weaponEventId == -1)
            break;
          if (weaponEventId == WeaponEvents.CHANGE_HIDE)
            break;
          WeaponEventBase anim_event = WeaponAnimEventFactory(weaponEventId, GetDayZPlayerOwner(), NULL);
          if (LogManager.IsWeaponLogEnable())
            wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(weapon) + " HandleWeapons: event arrived " + typename.EnumToString(WeaponEvents, weaponEventId) + "(" + weaponEventId + ")  fsm_ev=" + anim_event.ToString());
          if (anim_event != NULL)
            weapon.ProcessWeaponEvent(anim_event);
        }
        if (hcw.IsActionFinished())
        {
          if (weapon.IsWaitingForActionFinish())
          {
            if (LogManager.IsWeaponLogEnable())
              wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(weapon) + " Weapon event: finished! notifying waiting state=" + weapon.GetCurrentState());
            weapon.ProcessWeaponEvent(new WeaponEventHumanCommandActionFinished(GetDayZPlayerOwner()));
          }
          else
          {
            if (LogManager.IsWeaponLogEnable())
              wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(weapon) + " Weapon event: ABORT! notifying running state=" + weapon.GetCurrentState());
            weapon.ProcessWeaponAbortEvent(new WeaponEventHumanCommandActionAborted(GetDayZPlayerOwner()));
          }
        }
      }
      if (m_DeferredWeaponEvent)
      {
        if (LogManager.IsWeaponLogEnable())
          wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(weapon) + " Weapon event: deferred " + m_DeferredWeaponEvent.DumpToString());
        if (weapon.ProcessWeaponEvent(m_DeferredWeaponEvent))
        {
          exitIronSights = true;
          if (LogManager.IsWeaponLogEnable())
            fsmDebugSpam("[wpnfsm] " + Object.GetDebugName(weapon) + " Weapon event: resetting deferred event" + m_DeferredWeaponEvent.DumpToString());
          m_DeferredWeaponEvent = NULL;
          m_DeferredWeaponTimer.Stop();
        }
        else if (!m_DeferredWeaponTimer.IsRunning())
          m_DeferredWeaponTimer.Run(3, this, "DeferredWeaponFailed");
      }
    }
  }
References Class::CastTo(), fsmDebugSpam(), GetDayZPlayerOwner(), LogManager::IsWeaponLogEnable(), m_DeferredWeaponEvent, m_DeferredWeaponTimer, WeaponActionTypeToString(), WeaponAnimEventFactory(), wpnDebugPrint(), and wpnDebugSpamALot().
Init()
override void Init () protected
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
pre-init arrays
Definition at line 178 of file DayZPlayerInventory.c.
  {
    if (LogManager.IsInventoryHFSMLogEnable())
      hndDebugPrint("[hndfsm] Creating DayZPlayer Inventory FSM");
    CreateStableStates(); // stable states needs to be created first
    m_Taking = new HandAnimatedTakingFromAtt(GetManOwner(), null);
    m_MovingTo = new HandAnimatedMovingToAtt(GetManOwner(), null);
    m_Swapping = new HandAnimatedSwapping(GetManOwner(), null);
    m_FSwapping = new HandAnimatedForceSwapping(GetManOwner(), null);
    m_FSwappingInst = new HandAnimatedForceSwapping_Inst(GetManOwner(), null);
    // events
    HandEventBase _fin_ = new HandEventHumanCommandActionFinished;
    HandEventBase _abt_ = new HandEventHumanCommandActionAborted;
    HandEventBase __T__ = new HandEventTake;
    HandEventBase __M__ = new HandEventMoveTo;
    HandEventBase __W__ = new HandEventSwap;
    //HandEventBase __D__ = new HandEventDropping;
    HandEventBase __Xd_ = new HandEventDestroyed;
    HandEventBase __F__ = new HandEventForceSwap;
    // setup transitions
    m_FSM.AddTransition(new HandTransition(m_Empty, __T__, m_Taking, NULL, new HandSelectAnimationOfTakeToHandsEvent(GetManOwner())));
    m_FSM.AddTransition(new HandTransition(m_Taking, _fin_, m_Empty, null, new HandGuardNot(new HandGuardHasItemInHands(GetManOwner()))));
    m_FSM.AddTransition(new HandTransition(m_Taking, _fin_, m_Equipped, null, null));
    m_FSM.AddTransition(new HandTransition(m_Taking, __Xd_, m_Empty, new HandActionDestroyed, new HandGuardHasDestroyedItemInHands(GetManOwner())));
    m_Taking.AddTransition(new HandTransition(m_Taking.m_Hide, _abt_, m_Empty));
    m_Taking.AddTransition(new HandTransition(m_Taking.m_Show, _abt_, m_Equipped));
    m_FSM.AddTransition(new HandTransition(m_Equipped, __M__, m_MovingTo, NULL, new HandSelectAnimationOfMoveFromHandsEvent(GetManOwner())));
    m_FSM.AddTransition(new HandTransition(m_MovingTo, __Xd_, m_Empty, new HandActionDestroyed, new HandGuardHasDestroyedItemInHands(GetManOwner())));
    m_FSM.AddTransition(new HandTransition(m_MovingTo, _fin_, m_Equipped, null, new HandGuardHasItemInHands(GetManOwner())));
    m_FSM.AddTransition(new HandTransition(m_MovingTo, _fin_, m_Empty, null, null));
    m_MovingTo.AddTransition(new HandTransition(m_MovingTo.m_Hide, _abt_, m_Equipped));
    m_MovingTo.AddTransition(new HandTransition(m_MovingTo.m_Show, _abt_, m_Empty));
    m_FSM.AddTransition(new HandTransition(m_Equipped, __W__, m_Swapping, NULL, new HandSelectAnimationOfSwapInHandsEvent(GetManOwner())));
    m_FSM.AddTransition(new HandTransition(m_Swapping, __Xd_, m_Empty, new HandActionDestroyed, new HandGuardHasDestroyedItemInHands(GetManOwner())));
    m_FSM.AddTransition(new HandTransition(m_Swapping, _fin_, m_Empty, null, new HandGuardNot(new HandGuardHasItemInHands(GetManOwner()))));
    m_FSM.AddTransition(new HandTransition(m_Swapping, _fin_, m_Equipped, null, null));
    m_FSM.AddTransition(new HandTransition(m_Swapping, _abt_, m_Equipped, null, null));
    m_FSM.AddTransition(new HandTransition(m_Equipped, __F__, m_FSwappingInst, NULL, new HandGuardAnd(new HandSelectAnimationOfForceSwapInHandsEvent(GetManOwner()), new HandGuardInstantForceSwap(GetManOwner()))));
    m_FSM.AddTransition(new HandTransition(m_FSwappingInst, _fin_, m_Equipped, null, new HandGuardHasItemInHands(GetManOwner())));
    m_FSM.AddTransition(new HandTransition(m_FSwappingInst, _fin_, m_Empty, null, null));
    m_FSM.AddTransition(new HandTransition(m_FSwappingInst, __Xd_, m_Empty, new HandActionDestroyed, new HandGuardHasDestroyedItemInHands(GetManOwner())));
    m_FSM.AddTransition(new HandTransition(m_FSwappingInst, _abt_, m_Equipped, null, null));
    m_FSM.AddTransition(new HandTransition(m_Equipped, __F__, m_FSwapping, NULL, new HandSelectAnimationOfForceSwapInHandsEvent(GetManOwner())));
    m_FSM.AddTransition(new HandTransition(m_FSwapping, _fin_, m_Equipped, null, new HandGuardHasItemInHands(GetManOwner())));
    m_FSM.AddTransition(new HandTransition(m_FSwapping, _fin_, m_Empty, null, null));
    m_FSM.AddTransition(new HandTransition(m_FSwapping, __Xd_, m_Empty, new HandActionDestroyed, new HandGuardHasDestroyedItemInHands(GetManOwner())));
    m_FSwapping.AddTransition(new HandTransition(m_FSwapping.m_Start, _abt_, m_Equipped));
    m_FSwapping.AddTransition(new HandTransition(m_FSwapping.m_Hide, _abt_, m_Empty));
    m_FSwapping.AddTransition(new HandTransition(m_FSwapping.m_Show, _abt_, m_Equipped));
    super.Init(); // initialize ordinary human fsm (no anims)
  }
References hndDebugPrint(), LogManager::IsInventoryHFSMLogEnable(), m_FSwapping, m_FSwappingInst, m_MovingTo, m_Swapping, and m_Taking.
IsAuthoritative()
bool IsAuthoritative () protected
Definition at line 151 of file DayZPlayerInventory.c.
  {
    DayZPlayer player;
    if (!Class.CastTo(player, GetInventoryOwner()))
      return false;
    return (player.GetInstanceType() != DayZPlayerInstanceType.INSTANCETYPE_CLIENT && player.GetInstanceType() != DayZPlayerInstanceType.INSTANCETYPE_REMOTE);
  }
References Class::CastTo().
IsOwner()
bool IsOwner () protected
Definition at line 160 of file DayZPlayerInventory.c.
  {
    DayZPlayer player;
    if (!Class.CastTo(player, GetInventoryOwner()))
      return false;
    return (player.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT || player.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_AI_SERVER || player.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_AI_SINGLEPLAYER);
  }
References Class::CastTo().
IsProcessing()
bool IsProcessing () protected
Definition at line 2100 of file DayZPlayerInventory.c.
  {
    return !m_FSM.GetCurrentState().IsIdle() || m_DeferredEvent || m_DeferredPostedHandEvent;
  }
References m_DeferredEvent, and m_DeferredPostedHandEvent.
Referenced by HandEvent(), DayZPlayer::HandleADS(), and ManBase::OnQuickBarSingleUse().
IsProxy()
bool IsProxy () protected
Definition at line 169 of file DayZPlayerInventory.c.
  {
    DayZPlayer player;
    if (!Class.CastTo(player, GetInventoryOwner()))
      return false;
    return (player.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_REMOTE || player.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_AI_REMOTE);
  }
References Class::CastTo().
IsServerOrLocalPlayer()
bool IsServerOrLocalPlayer () protected
Definition at line 1399 of file DayZPlayerInventory.c.
  {
    return GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER || GetDayZPlayerOwner() == GetGame().GetPlayer());
  }
References GetDayZPlayerOwner(), and GetGame().
NetSyncCurrentStateID()
override void NetSyncCurrentStateID (int id) protected
Definition at line 1819 of file DayZPlayerInventory.c.
  {
    super.NetSyncCurrentStateID(id);
    GetDayZPlayerOwner().GetItemAccessor().OnItemInHandsChanged();
  }
References GetDayZPlayerOwner(), and DayZPlayer::OnItemInHandsChanged().
OnAfterStoreLoad()
OnAfterStoreLoad () protected
engine reaction to load from database originates in: engine - Person::BinLoad script - PlayerBase.OnAfterStoreLoad
Definition at line 1832 of file DayZPlayerInventory.c.
  {
    GetDayZPlayerOwner().GetItemAccessor().OnItemInHandsChanged(true);
  }
References GetDayZPlayerOwner(), and DayZPlayer::OnItemInHandsChanged().
OnEventForRemoteWeapon()
bool OnEventForRemoteWeapon (ParamsReadContext ctx) protected
Definition at line 1840 of file DayZPlayerInventory.c.
  {
    if (GetEntityInHands())
    {
      Weapon_Base wpn = Weapon_Base.Cast(GetEntityInHands());
      if (wpn)
      {
        PlayerBase pb = PlayerBase.Cast(GetDayZPlayerOwner());
        WeaponEventBase e = CreateWeaponEventFromContext(ctx);
        if (pb && e)
        {
          pb.GetWeaponManager().SetRunning(true);
          if (LogManager.IsWeaponLogEnable())
            fsmDebugSpam("[wpnfsm] " + Object.GetDebugName(wpn) + " recv event from remote: created event=" + e);
          if (e.GetEventID() == WeaponEventID.HUMANCOMMAND_ACTION_ABORTED)
            wpn.ProcessWeaponAbortEvent(e);
          else
            wpn.ProcessWeaponEvent(e);
          pb.GetWeaponManager().SetRunning(false);
        }
      }
      else
        Error("OnEventForRemoteWeapon - entity in hands, but not weapon. item=" + GetEntityInHands());
    }
    else
      Error("OnEventForRemoteWeapon - no entity in hands");
    return true;
  }
References CreateWeaponEventFromContext(), Error(), fsmDebugSpam(), GetDayZPlayerOwner(), and LogManager::IsWeaponLogEnable().
OnHandEventForRemote()
bool OnHandEventForRemote (ParamsReadContext ctx) protected
Definition at line 1876 of file DayZPlayerInventory.c.
  {
    HandEventBase e = HandEventBase.CreateHandEventFromContext(ctx);
    if (e)
    {
      if (LogManager.IsInventoryHFSMLogEnable())
        hndDebugSpam("[hndfsm] recv event from remote: created event=" + e);
      //m_FSM.ProcessEvent(e);
      if (e.GetEventID() == HandEventID.HUMANCOMMAND_ACTION_ABORTED)
      {
        ProcessEventResult aa;
        m_FSM.ProcessAbortEvent(e, aa);
      }
      else
        m_FSM.ProcessEvent(e);
      return true;
    }
    return false;
  }
References hndDebugSpam(), and LogManager::IsInventoryHFSMLogEnable().
OnHandleStoredInputUserData()
void OnHandleStoredInputUserData (ParamsReadContext ctx) protected
Definition at line 634 of file DayZPlayerInventory.c.
  {
    int tmp = -1;
    ctx.Read(tmp);
    if (LogManager.IsSyncLogEnable())
      syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " handle InputUserData packet STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp());
    ProcessInputData(ctx, false, false);
  }
References GetDayZPlayerOwner(), LogManager::IsSyncLogEnable(), ProcessInputData(), and syncDebugPrint().
OnHandleStoredJunctureData()
void OnHandleStoredJunctureData (ParamsReadContext ctx) protected
Juncture is only ever Server Req->Client Ack and Perform->Server Perform, never remote
Definition at line 594 of file DayZPlayerInventory.c.
  {
    int tmp = -1;
    ctx.Read(tmp);
    if (LogManager.IsSyncLogEnable())
      syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " handle JunctureData packet STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp());
    ProcessInputData(ctx, true, false);
  }
References GetDayZPlayerOwner(), LogManager::IsSyncLogEnable(), ProcessInputData(), and syncDebugPrint().
OnHandsEnteredStableState()
override void OnHandsEnteredStableState (HandStateBase src, HandStateBase dst) protected
Definition at line 1924 of file DayZPlayerInventory.c.
  {
    super.OnHandsEnteredStableState(src, dst);
    if (LogManager.IsInventoryHFSMLogEnable())
      hndDebugPrint("[hndfsm] hand fsm entered stable dst=" + dst.Type().ToString());
  }
References hndDebugPrint(), and LogManager::IsInventoryHFSMLogEnable().
Referenced by OnHandsStateChanged().
OnHandsExitedStableState()
override void OnHandsExitedStableState (HandStateBase src, HandStateBase dst) protected
Definition at line 1916 of file DayZPlayerInventory.c.
  {
    super.OnHandsExitedStableState(src, dst);
    if (LogManager.IsInventoryHFSMLogEnable())
      hndDebugPrint("[hndfsm] hand fsm exit stable src=" + src.Type().ToString());
  }
References hndDebugPrint(), and LogManager::IsInventoryHFSMLogEnable().
Referenced by OnHandsStateChanged().
OnHandsStateChanged()
override void OnHandsStateChanged (HandStateBase src, HandStateBase dst) protected
Definition at line 1932 of file DayZPlayerInventory.c.
  {
    super.OnHandsStateChanged(src, dst);
    if (LogManager.IsInventoryHFSMLogEnable())
      hndDebugPrint("[hndfsm] hand fsm changed state src=" + src.Type().ToString() + " ---> dst=" + dst.Type().ToString());
    if (src.IsIdle())
      OnHandsExitedStableState(src, dst);
    if (dst.IsIdle())
      OnHandsEnteredStableState(src, dst);
#ifdef BOT
    PlayerBase p = PlayerBase.Cast(GetDayZPlayerOwner());
    if (p && p.m_Bot)
      p.m_Bot.ProcessEvent(new BotEventOnItemInHandsChanged(p));
#endif
  }
References GetDayZPlayerOwner(), hndDebugPrint(), LogManager::IsInventoryHFSMLogEnable(), OnHandsEnteredStableState(), and OnHandsExitedStableState().
OnInputUserDataForRemote()
void OnInputUserDataForRemote (ParamsReadContext ctx) protected
Definition at line 651 of file DayZPlayerInventory.c.
  {
    if (LogManager.IsSyncLogEnable())
      syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " remote handling InputUserData packet from server");
    ProcessInputData(ctx, false, true);
  }
References GetDayZPlayerOwner(), LogManager::IsSyncLogEnable(), ProcessInputData(), and syncDebugPrint().
OnInputUserDataProcess()
override bool OnInputUserDataProcess (ParamsReadContext ctx) protected
Definition at line 621 of file DayZPlayerInventory.c.
  {
    if (LogManager.IsSyncLogEnable())
      syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " store InputUserData packet STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp());
    StoreInputUserData(ctx);
    return true;
  }
References GetDayZPlayerOwner(), LogManager::IsSyncLogEnable(), StoreInputUserData(), and syncDebugPrint().
OnInventoryFailure()
override void OnInventoryFailure (InventoryCommandType type, InventoryValidationReason reason, InventoryLocation src, InventoryLocation dst) protected
TODO(kumarjac): Notify player here
Definition at line 580 of file DayZPlayerInventory.c.
  {
    if (reason == InventoryValidationReason.DROP_PREVENTED)
    {
      return;
    }
  }
Referenced by HandEvent(), and OnInventoryJunctureFailureFromServer().
OnInventoryJunctureFailureFromServer()
override void OnInventoryJunctureFailureFromServer (ParamsReadContext ctx) protected
Function and setup is still messy due to the switch statement and relation with reading.
It could be cleaner if we used classes to handle each inventory command type, but that comes at a performance cost and will also probably require making a fair amount of changes elsewhere.
The downsides with this system right now:
It makes it hard to track what is written/read from the serializer
It makes this file very very large
The new changes at least remove the massive switch block and allow for all inventory commands to respond back to the client if something goes wrong
Definition at line 509 of file DayZPlayerInventory.c.
  {
    if (GetGame().IsDedicatedServer())
      return;
    int udtIdentifier = -1;
    if (!ctx.Read(udtIdentifier) || udtIdentifier != INPUT_UDT_INVENTORY)
      return;
    InventoryLocation src = new InventoryLocation;
    InventoryLocation dst = new InventoryLocation;
    InventoryLocation temp = new InventoryLocation;
    InventoryCommandType type = -1;
    if (!ctx.Read(type))
      return;
    switch (type)
    {
    case InventoryCommandType.SYNC_MOVE:
    {
      src.ReadFromContext(ctx);
      dst.ReadFromContext(ctx);
      break;
    }
    case InventoryCommandType.HAND_EVENT:
    {
      HandEventBase e = HandEventBase.CreateHandEventFromContext(ctx);
      src = e.GetSrc();
      dst = e.GetDst();
      break;
    }
    case InventoryCommandType.SWAP:
    {
      src.ReadFromContext(ctx);
      temp.ReadFromContext(ctx);
      dst.ReadFromContext(ctx);
      temp.ReadFromContext(ctx);
      break;
    }
    case InventoryCommandType.FORCESWAP:
    {
      break;
    }
    case InventoryCommandType.DESTROY:
    {
      src.ReadFromContext(ctx);
      break;
    }
    }
    InventoryValidationReason reason;
    if (!ctx.Read(reason))
      reason = InventoryValidationReason.UNKNOWN;
    OnInventoryFailure(type, reason, src, dst);
  }
References GetGame(), INPUT_UDT_INVENTORY, and OnInventoryFailure().
OnInventoryJunctureFromServer()
override bool OnInventoryJunctureFromServer (ParamsReadContext ctx) protected
Definition at line 464 of file DayZPlayerInventory.c.
  {
    int tmp = -1;
    ctx.Read(tmp);
    if (LogManager.IsSyncLogEnable())
      syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " store Juncture packet STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp());
    StoreJunctureData(ctx);
    return true;
  }
References GetDayZPlayerOwner(), LogManager::IsSyncLogEnable(), StoreJunctureData(), and syncDebugPrint().
OnInventoryJunctureRepairFromServer()
override bool OnInventoryJunctureRepairFromServer (ParamsReadContext ctx) protected
Definition at line 484 of file DayZPlayerInventory.c.
  {
    /*    InventoryLocation il = new InventoryLocation;
        if (!il.ReadFromContext(ctx) )
          return false;
        InventoryLocation il_current = new InventoryLocation;
        EntityAI item = il.GetItem();
        item.GetInventory().GetCurrentInventoryLocation(il_current);
        if( !il_current.CompareLocationOnly(il))
        {
          LocationMoveEntity(il_current,il);
        }*/
    return true;
  }
OnServerInventoryCommand()
override void OnServerInventoryCommand (ParamsReadContext ctx) protected
Definition at line 659 of file DayZPlayerInventory.c.
  {
    if (LogManager.IsSyncLogEnable())
      syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " DZPInventory command from server");
    ProcessInputData(ctx, true, true);
  }
References GetDayZPlayerOwner(), LogManager::IsSyncLogEnable(), ProcessInputData(), and syncDebugPrint().
PlayerCheckDropRequest()
bool PlayerCheckDropRequest (notnull InventoryLocation src, float radius) protected
Definition at line 2206 of file DayZPlayerInventory.c.
  {
    bool result = true;
    EntityAI ent = src.GetParent();
    if (ent)
    {
      PlayerBase player = PlayerBase.Cast(ent.GetHierarchyRootPlayer());
      if (player)
      {
        if (GetDayZPlayerOwner() != player)
        {
          if (player.IsAlive())
          {
            if (!player.IsRestrained() && !player.IsUnconscious())
              return false;
          }
        }
      }
    }
    if (result)
      result = CheckDropRequest(GetManOwner(), src, radius);
    return result;
  }
References GetDayZPlayerOwner().
Referenced by ValidateDestroy().
PlayerCheckRequestDst()
bool PlayerCheckRequestDst (notnull InventoryLocation src, notnull InventoryLocation dst, float radius) protected
Definition at line 2132 of file DayZPlayerInventory.c.
  {
    bool result = true;
    EntityAI ent = dst.GetParent();
    if (ent)
    {
      PlayerBase player = PlayerBase.Cast(ent.GetHierarchyRootPlayer());
      if (player)
      {
        if (GetDayZPlayerOwner() != player)
        {
          if (player.IsAlive())
          {
            if (!player.IsRestrained() && !player.IsUnconscious())
              return false;
          }
        }
      }
    }
    if (result)
      result = CheckMoveToDstRequest(GetManOwner(), src, dst, radius);
    return result;
  }
References GetDayZPlayerOwner().
Referenced by ValidateSyncMove().
PlayerCheckRequestSrc()
bool PlayerCheckRequestSrc (notnull InventoryLocation src, float radius) protected
Definition at line 2105 of file DayZPlayerInventory.c.
  {
    bool result = true;
    EntityAI ent = src.GetParent();
    if (ent)
    {
      PlayerBase player = PlayerBase.Cast(ent.GetHierarchyRootPlayer());
      if (player)
      {
        if (GetDayZPlayerOwner() != player)
        {
          if (player.IsAlive())
          {
            if (!player.IsRestrained() && !player.IsUnconscious())
              return false;
          }
        }
      }
    }
    if (result)
      result = CheckRequestSrc(GetManOwner(), src, radius);
    return result;
  }
References CheckRequestSrc(), and GetDayZPlayerOwner().
Referenced by ValidateDestroy(), ValidateSwap(), and ValidateSyncMove().
PlayerCheckSwapItemsRequest()
bool PlayerCheckSwapItemsRequest (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, float radius) protected
Definition at line 2159 of file DayZPlayerInventory.c.
  {
    bool result = true;
    EntityAI ent = dst1.GetParent();
    PlayerBase player;
    if (ent)
    {
      player = PlayerBase.Cast(ent.GetHierarchyRootPlayer());
      if (player)
      {
        if (GetDayZPlayerOwner() != player)
        {
          if (player.IsAlive())
          {
            if (!player.IsRestrained() && !player.IsUnconscious())
              return false;
          }
        }
      }
    }
    ent = dst2.GetParent();
    if (ent)
    {
      player = PlayerBase.Cast(ent.GetHierarchyRootPlayer());
      if (player)
      {
        if (GetDayZPlayerOwner() != player)
        {
          if (player.IsAlive())
          {
            if (!player.IsRestrained() && !player.IsUnconscious())
              return false;
          }
        }
      }
    }
    if (result)
      result = CheckSwapItemsRequest(GetManOwner(), src1, src2, dst1, dst2, GameInventory.c_MaxItemDistanceRadius);
    return result;
  }
References GameInventory::c_MaxItemDistanceRadius, and GetDayZPlayerOwner().
Referenced by ValidateSwap().
PostWeaponEvent()
void PostWeaponEvent (WeaponEventBase e) protected
Definition at line 275 of file DayZPlayerInventory.c.
  {
    if (m_DeferredWeaponEvent == NULL)
    {
      m_DeferredWeaponEvent = e;
      if (LogManager.IsWeaponLogEnable())
        wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(GetInventoryOwner()) + " Posted event m_DeferredWeaponEvent=" + m_DeferredWeaponEvent.DumpToString());
    }
    else
      Error("[wpnfsm] " + Object.GetDebugName(GetInventoryOwner()) + " warning - pending event already posted, curr_event=" + m_DeferredWeaponEvent.DumpToString() + " new_event=" + e.DumpToString());
  }
References Error(), LogManager::IsWeaponLogEnable(), m_DeferredWeaponEvent, and wpnDebugPrint().
ProcessInputData()
bool ProcessInputData (ParamsReadContext ctx, bool isJuncture, bool isRemote) protected
Returns
false on malformed data, true on anything else, including cheats
It should be impossible for juncture to be ran on remote
Serializer can be updated and re-written to when we may want to only correct the client instead of denying the inventory command
Only inform client about failure
General purpose serializer change from read to write here if the validation doesn't update it
Only send juncture back to client
Definition at line 1295 of file DayZPlayerInventory.c.
  {
    if (isJuncture && isRemote)
    {
      return false;
    }
    int type = -1;
    if (!ctx.Read(type))
      return false;
    InventoryValidation validation();
    validation.m_IsJuncture = isJuncture;
    validation.m_IsRemote = isRemote;
    Serializer serializer = ctx;
    switch (type)
    {
    case InventoryCommandType.USER_RESERVATION_CANCEL:
      if (!ValidateUserReservationCancel(serializer, validation))
        return false;
      break;
    case InventoryCommandType.SYNC_MOVE:
      if (!ValidateSyncMove(serializer, validation))
        return false;
      break;
    case InventoryCommandType.HAND_EVENT:
      if (!ValidateHandEvent(serializer, validation))
        return false;
      break;
    case InventoryCommandType.SWAP:
      if (!ValidateSwap(serializer, validation))
        return false;
      break;
    case InventoryCommandType.DESTROY:
      if (!ValidateDestroy(serializer, validation))
        return false;
      break;
    default:
      break;
    }
    bool canSendJuncture = !isJuncture && GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER;
    switch (validation.m_Result)
    {
    case InventoryValidationResult.FAILED:
      if (canSendJuncture)
      {
        if (!serializer.CanWrite())
        {
          ScriptInputUserData writeableSerializer();
          writeableSerializer.CopyFrom(serializer);
          serializer = writeableSerializer;
        }
        serializer.Write(validation.m_Reason);
        GetDayZPlayerOwner().SendSyncJuncture(DayZPlayerSyncJunctures.SJ_INVENTORY_FAILURE, serializer);
      }
      break;
    case InventoryValidationResult.JUNCTURE:
      if (canSendJuncture)
      {
        GetDayZPlayerOwner().SendSyncJuncture(DayZPlayerSyncJunctures.SJ_INVENTORY, serializer);
        //StoreInputForRemotes(isJuncture, isRemote, serializer);
      }
      else
        Error("InventoryValidationResult.JUNCTURE returned when not possible to send!");
      break;
    case InventoryValidationResult.SUCCESS:
      StoreInputForRemotes(isJuncture, isRemote, serializer);
      break;
    }
    return true;
  }
References Error(), GetDayZPlayerOwner(), DayZPlayerSyncJunctures::SJ_INVENTORY, DayZPlayerSyncJunctures::SJ_INVENTORY_FAILURE, StoreInputForRemotes(), ValidateDestroy(), ValidateHandEvent(), ValidateSwap(), and ValidateSyncMove().
Referenced by OnHandleStoredInputUserData(), OnHandleStoredJunctureData(), OnInputUserDataForRemote(), and OnServerInventoryCommand().
RemoveMovableOverride()
void RemoveMovableOverride (EntityAI item) protected
Definition at line 1377 of file DayZPlayerInventory.c.
  {
    ItemBase itemIB = ItemBase.Cast(item);
    if (itemIB)
      itemIB.SetCanBeMovedOverride(false);
  }
Referenced by ValidateHandEvent(), ValidateSwap(), and ValidateSyncMove().
ReserveInventory()
override bool ReserveInventory (HumanInventory inventory)
Definition at line 22 of file DayZPlayerInventory.c.
  {
    if (!inventory.AddInventoryReservationEx(m_dst.GetItem(), m_dst, GameInventory.c_InventoryReservationTimeoutShortMS))
      return false;
    return true;
  }
References GameInventory::c_InventoryReservationTimeoutShortMS, and m_dst.
SendServerHandEventViaJuncture()
static void SendServerHandEventViaJuncture (notnull DayZPlayer player, HandEventBase e) static protected
Remote inputs are processed in sync juncture once performed on the server - this code below was executing the inventory command before the player simulation timeestamp for remotes which is illegal
Definition at line 1767 of file DayZPlayerInventory.c.
  {
    if (GetGame().IsServer())
    {
      if (e.IsServerSideOnly())
        Error("[syncinv] " + Object.GetDebugName(player) + " SendServerHandEventViaJuncture - called on server side event only, e=" + e.DumpToString());
      if (player.IsAlive())
      {
        InventoryLocation dst = e.GetDst();
        InventoryLocation src = e.GetSrc();
        if (src.IsValid() && dst.IsValid())
        {
          if (player.NeedInventoryJunctureFromServer(src.GetItem(), src.GetParent(), dst.GetParent()))
          {
            if (LogManager.IsSyncLogEnable())
              syncDebugPrint("[syncinv] " + Object.GetDebugName(player) + " STS = " + player.GetSimulationTimeStamp() + " SendServerHandEventViaJuncture(" + typename.EnumToString(InventoryMode, InventoryMode.SERVER) + ") need juncture src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
            if (GetGame().AddInventoryJunctureEx(player, src.GetItem(), dst, true, GameInventory.c_InventoryReservationTimeoutMS))
            {
              if (LogManager.IsSyncLogEnable())
                syncDebugPrint("[syncinv] " + Object.GetDebugName(player) + " STS = " + player.GetSimulationTimeStamp() + " SendServerHandEventViaJuncture(" + typename.EnumToString(InventoryMode, InventoryMode.SERVER) + ") got juncture");
            }
            else
            {
              if (LogManager.IsSyncLogEnable())
                syncDebugPrint("[syncinv] " + Object.GetDebugName(player) + " STS = " + player.GetSimulationTimeStamp() + " SendServerHandEventViaJuncture(" + typename.EnumToString(InventoryMode, InventoryMode.SERVER) + ") !got juncture");
            }
          }
          if (LogManager.IsSyncLogEnable())
            syncDebugPrint("[syncinv] " + Object.GetDebugName(player) + " STS = " + player.GetSimulationTimeStamp() + " SendServerHandEventViaJuncture(" + typename.EnumToString(InventoryMode, InventoryMode.SERVER) + " server hand event src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
          ScriptInputUserData ctx = new ScriptInputUserData;
          InventoryInputUserData.SerializeHandEvent(ctx, e);
          player.SendSyncJuncture(DayZPlayerSyncJunctures.SJ_INVENTORY, ctx);
          if (LogManager.IsSyncLogEnable())
            syncDebugPrint("[syncinv] " + Object.GetDebugName(player) + " STS = " + player.GetSimulationTimeStamp() + " store input for remote - SendServerHandEventViaJuncture(" + typename.EnumToString(InventoryMode, InventoryMode.SERVER) + " server hand event src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
          //player.StoreInputForRemotes(ctx); // @TODO: is this right place? maybe in HandleInputData(server=true, ...)
        }
      }
      else
        Error("[syncinv] SendServerHandEventViaJuncture - called on dead player, juncture is for living only");
    }
  }
References GameInventory::c_InventoryReservationTimeoutMS, InventoryLocation::DumpToStringNullSafe(), Error(), GetGame(), LogManager::IsSyncLogEnable(), InventoryInputUserData::SerializeHandEvent(), DayZPlayerSyncJunctures::SJ_INVENTORY, and syncDebugPrint().
Referenced by HandleHandEvent().
StoreInputForRemotes()
bool StoreInputForRemotes (bool handling_juncture, bool remote, ParamsReadContext ctx) protected
Definition at line 1404 of file DayZPlayerInventory.c.
  {
    if (!remote && GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp(), "n/a", "n/a", "StoreInputForRemotes", GetDayZPlayerOwner().ToString());
#endif
      GetDayZPlayerOwner().StoreInputForRemotes(ctx); // @NOTE: needs to be called _after_ the operation
      return true;
    }
    return false;
  }
References GetDayZPlayerOwner(), GetInstanceType(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), and ToString().
StoreInputUserData()
proto native void StoreInputUserData (ParamsReadContext ctx) protected
Referenced by OnInputUserDataProcess().
StoreJunctureData()
proto native void StoreJunctureData (ParamsReadContext ctx) protected
Referenced by OnInventoryJunctureFromServer().
SwapEntities()
override bool SwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2) protected
Definition at line 1577 of file DayZPlayerInventory.c.
  {
#ifdef DEVELOPER
    if (LogManager.IsInventoryMoveLogEnable())
      Debug.InventoryMoveLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item1 = " + item1 + " item2 = " + item2, "n/a", "n/a", "SwapEntities", GetDayZPlayerOwner().ToString());
#endif
    InventoryLocation src1, src2, dst1, dst2;
    if (mode == InventoryMode.LOCAL)
    {
      if (GameInventory.MakeSrcAndDstForSwap(item1, item2, src1, src2, dst1, dst2))
      {
        LocationSwap(src1, src2, dst1, dst2);
        return true;
      }
    }
    if (!super.SwapEntities(mode, item1, item2))
    {
      if (!m_DeferredEvent)
      {
        if (GameInventory.MakeSrcAndDstForSwap(item1, item2, src1, src2, dst1, dst2));
        {
          m_DeferredEvent = new DeferredSwapEntities(mode, item1, item2, dst1, dst2);
          if (m_DeferredEvent.ReserveInventory(this))
            return true;
        }
      }
      m_DeferredEvent = null;
      return false;
    }
    return true;
  }
References GetDayZPlayerOwner(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), m_DeferredEvent, GameInventory::MakeSrcAndDstForSwap(), and ToString().
SyncHandEventToRemote()
void SyncHandEventToRemote (HandEventBase e) protected
Definition at line 1899 of file DayZPlayerInventory.c.
  {
    DayZPlayer p = GetDayZPlayerOwner();
    if (p && p.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
    {
      ScriptRemoteInputUserData ctx = new ScriptRemoteInputUserData;
      ctx.Write(INPUT_UDT_HAND_REMOTE_EVENT);
      e.WriteToContext(ctx);
      if (LogManager.IsInventoryHFSMLogEnable())
        hndDebugPrint("[hndfsm] send 2 remote: sending e=" + e + " id=" + e.GetEventID() + " p=" + p + "  e=" + e.DumpToString());
      p.StoreInputForRemotes(ctx);
    }
  }
References GetDayZPlayerOwner(), hndDebugPrint(), INPUT_UDT_HAND_REMOTE_EVENT, and LogManager::IsInventoryHFSMLogEnable().
Referenced by HandleInventory().
TakeToDst()
override bool TakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst) protected
Remote inputs are processed in sync juncture once performed on the server - this code below was executing the inventory command before the player simulation timeestamp for remotes which is illegal
Definition at line 1420 of file DayZPlayerInventory.c.
  {
    if (GetManOwner().IsAlive() == false)
      return super.TakeToDst(mode, src, dst);
#ifdef DEVELOPER
    if (LogManager.IsInventoryMoveLogEnable())
      Debug.InventoryMoveLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst), "n/a", "n/a", "TakeToDst", GetDayZPlayerOwner().ToString());
#endif
    switch (mode)
    {
    case InventoryMode.SERVER:
      if (RedirectToHandEvent(mode, src, dst))
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryMoveLogEnable())
          Debug.InventoryMoveLog("RedirectToHandEvent", "n/a", "n/a", "TakeToDst", GetDayZPlayerOwner().ToString());
#endif
        return true;
      }
      if (GetDayZPlayerOwner().NeedInventoryJunctureFromServer(src.GetItem(), src.GetParent(), dst.GetParent()))
      {
        if (GetGame().AddInventoryJunctureEx(GetDayZPlayerOwner(), src.GetItem(), dst, true, GameInventory.c_InventoryReservationTimeoutMS))
        {
          if (LogManager.IsSyncLogEnable())
            syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " DZPI::Take2Dst(" + typename.EnumToString(InventoryMode, mode) + ") got juncture");
        }
        else
        {
#ifdef DEVELOPER
          if (LogManager.IsInventoryMoveLogEnable())
            Debug.InventoryMoveLog("Juncture failed", "n/a", "n/a", "TakeToDst", GetDayZPlayerOwner().ToString());
#endif
          if (LogManager.IsSyncLogEnable())
            syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " DZPI::Take2Dst(" + typename.EnumToString(InventoryMode, mode) + ") got juncture");
          return false;
        }
      }
      ScriptInputUserData ctx = new ScriptInputUserData;
      InventoryInputUserData.SerializeMove(ctx, InventoryCommandType.SYNC_MOVE, src, dst);
      GetDayZPlayerOwner().SendSyncJuncture(DayZPlayerSyncJunctures.SJ_INVENTORY, ctx);
      if (LogManager.IsSyncLogEnable())
        syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " store input for remote - DZPI::Take2Dst(" + typename.EnumToString(InventoryMode, mode) + " server sync move src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
      //GetDayZPlayerOwner().StoreInputForRemotes(ctx); // @TODO: is this right place? maybe in HandleInputData(server=true, ...)
#ifdef DEVELOPER
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Success - store input for remote mode - " + typename.EnumToString(InventoryMode, mode) + " src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst), "n/a", "n/a", "TakeToDst", GetDayZPlayerOwner().ToString());
#endif
      return true;
    case InventoryMode.LOCAL:
      LocationSyncMoveEntity(src, dst);
      return true;
    }
    if (!super.TakeToDst(mode, src, dst))
    {
      if (!m_DeferredEvent)
      {
        m_DeferredEvent = new DeferredTakeToDst(mode, src, dst);
        if (m_DeferredEvent.ReserveInventory(this))
          return true;
      }
      m_DeferredEvent = null;
      return false;
    }
    return true;
  }
References GameInventory::c_InventoryReservationTimeoutMS, DeferredTakeToDst(), InventoryLocation::DumpToStringNullSafe(), GetDayZPlayerOwner(), GetGame(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), LogManager::IsSyncLogEnable(), m_DeferredEvent, InventoryInputUserData::SerializeMove(), DayZPlayerSyncJunctures::SJ_INVENTORY, syncDebugPrint(), and ToString().
Referenced by EntityAI::PredictiveMoveItemFromHandsToInventory().
ValidateDestroy()
bool ValidateDestroy (inout Serializer ctx, InventoryValidation validation) protected
TODO(kumarjac): Probably should be called through inventory juncture, we shouldn't allow the client to delete until the server says it is okay as there can be more reasons than "cheater" for it to be rejected such as desync
Do not check for action validity on remotes or when performing through juncture. Juncture locks guarentee the item is safe to interact with and the server has validated the command at this point. Checking at this point is both wasteful and can result in a failure which leads to desync
Do not check for action validity on remotes or when performing through juncture. Juncture locks guarentee the item is safe to interact with and the server has validated the command at this point. Checking at this point is both wasteful and can result in a failure which leads to desync
Definition at line 1219 of file DayZPlayerInventory.c.
  {
    InventoryCommandType type = InventoryCommandType.DESTROY;
    if (validation.m_IsJuncture)
    {
      return true;
    }
    InventoryLocation src = new InventoryLocation;
    src.ReadFromContext(ctx);
#ifdef DEVELOPER
    if (LogManager.IsInventoryMoveLogEnable())
      Debug.InventoryMoveLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " src=" + InventoryLocation.DumpToStringNullSafe(src), "DESTROY", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
    if (validation.m_IsRemote && !src.GetItem())
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Failed item not exist", "DESTROY", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
      Error("[syncinv] HandleInputData remote input (cmd=DESTROY) dropped, item not in bubble");
      return true;
    }
    if (!validation.m_IsRemote && !validation.m_IsJuncture && !PlayerCheckRequestSrc(src, GameInventory.c_MaxItemDistanceRadius))
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Failed CheckRequestSrc", "DESTROY", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
      return true;
    }
    if (!validation.m_IsRemote && !validation.m_IsJuncture && !PlayerCheckDropRequest(src, GameInventory.c_MaxItemDistanceRadius))
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Failed CheckDropRequest", "DESTROY", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
      return true;
    }
#ifdef DEVELOPER
    if (LogManager.IsInventoryMoveLogEnable())
      Debug.InventoryMoveLog("Success ObjectDelete", "DESTROY", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
    GetGame().ObjectDelete(src.GetItem());
    validation.m_Result = InventoryValidationResult.SUCCESS;
    return true;
  }
References GameInventory::c_MaxItemDistanceRadius, InventoryLocation::DumpToStringNullSafe(), Error(), GetDayZPlayerOwner(), GetGame(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), PlayerCheckDropRequest(), PlayerCheckRequestSrc(), and ToString().
Referenced by ProcessInputData().
ValidateHandEvent()
bool ValidateHandEvent (inout Serializer ctx, InventoryValidation validation) protected
Pass partial information to guards so guards can do minimal checks if needed The guards can't prevent event so it would be incorrect to pass full InventoryValidation struct. We have to make sure guards don't inadvertantly produce different results in the FSM as that will create desync (two players attempting to put a rag into the same fireplace slot at the same time)
kumarjac: This indicates a failure in replication relationships as player full inventory should be synchronized always if player exists on the remote
TODO(kumarjac): Is this one correct to be 'RemoveMovableOverride' or are the other Validate methdos wrong with 'EnableMovableOverride'?
Do not check for action validity on remotes or when performing through juncture. Juncture locks guarentee the item is safe to interact with and the server has validated the command at this point. Checking at this point is both wasteful and can result in a failure which leads to desync
'HandEventBase.CheckRequestEx' updates failure reason
if it already happened on server, remote just needs to comply TODO(kumarjac): Move m_IsRemote check to inside of HandEventBase.CanPerformEventEx
'HandEventBase.CanPerformEventEx' updates failure reason
Check if this this is being executed on the server and not by a juncture or AI
Continuing on with execution of rest of the function
Is called twice unfortunately... but it works so won't change
TODO(kumarjac): We should probably set the result to failure like so
Definition at line 833 of file DayZPlayerInventory.c.
  {
    InventoryCommandType type = InventoryCommandType.HAND_EVENT;
    HandEventBase e = HandEventBase.CreateHandEventFromContext(ctx);
    e.ClearInventoryReservation();
    e.m_IsRemote = validation.m_IsRemote;
    e.m_IsJuncture = validation.m_IsJuncture;
    EntityAI itemSrc = e.GetSrcEntity();
    EntityAI itemDst = e.GetSecondSrcEntity();
#ifdef DEVELOPER
    if (LogManager.IsInventoryMoveLogEnable())
      Debug.InventoryMoveLog("STS = " + e.m_Player.GetSimulationTimeStamp() + " event= " + e.DumpToString(), "HAND_EVENT", "n/a", "ProcessInputData", e.m_Player.ToString());
#endif
    if (validation.m_IsRemote && !e.GetSrcEntity())
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Failed - CheckRequestSrc", "HAND_EVENT", "n/a", "ProcessInputData", e.m_Player.ToString());
#endif
      Error("[syncinv] HandleInputData remote input (cmd=HAND_EVENT, event=" + e.DumpToString() + ") dropped, item not in bubble");
      return true;
    }
    if (itemSrc)
      RemoveMovableOverride(itemSrc);
    if (itemDst)
      RemoveMovableOverride(itemDst);
    if (!validation.m_IsRemote && !validation.m_IsJuncture && !e.CheckRequestSrc())
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Failed - CheckRequestSrc", "HAND_EVENT", "n/a", "ProcessInputData", e.m_Player.ToString());
#endif
      if (!validation.m_IsRemote)
      {
        ctx = new ScriptInputUserData;
        InventoryInputUserData.SerializeHandEvent(ctx, e);
      }
      RemoveMovableOverride(itemSrc);
      RemoveMovableOverride(itemDst);
      return true;
    }
    if (!e.CheckRequestEx(validation))
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Failed - CheckRequest", "HAND_EVENT", "n/a", "ProcessInputData", e.m_Player.ToString());
#endif
      ctx = new ScriptInputUserData;
      InventoryInputUserData.SerializeHandEvent(ctx, e);
      if (LogManager.IsSyncLogEnable())
        syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " is cheating with cmd=" + typename.EnumToString(InventoryCommandType, type) + " event=" + e.DumpToString());
      RemoveMovableOverride(itemSrc);
      RemoveMovableOverride(itemDst);
      return true;
    }
    if (!validation.m_IsRemote && !e.CanPerformEventEx(validation))
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Failed - CanPerformEvent", "HAND_EVENT", "n/a", "ProcessInputData", e.m_Player.ToString());
#endif
      ctx = new ScriptInputUserData;
      InventoryInputUserData.SerializeHandEvent(ctx, e);
      if (LogManager.IsSyncLogEnable())
        syncDebugPrint("[desync] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " CANNOT do cmd=HAND_EVENT e=" + e.DumpToString());
      RemoveMovableOverride(itemSrc);
      RemoveMovableOverride(itemDst);
      return true;
    }
    RemoveMovableOverride(itemSrc);
    RemoveMovableOverride(itemDst);
    if (!validation.m_IsJuncture && GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
    {
      JunctureRequestResult result_ev = e.AcquireInventoryJunctureFromServer(GetDayZPlayerOwner());
      if (result_ev == JunctureRequestResult.JUNCTURE_NOT_REQUIRED)
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryMoveLogEnable())
          Debug.InventoryMoveLog("Juncture not required", "HAND_EVENT", "n/a", "ProcessInputData", e.m_Player.ToString());
#endif
      }
      else if (result_ev == JunctureRequestResult.JUNCTURE_ACQUIRED)
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryMoveLogEnable())
          Debug.InventoryMoveLog("Juncture sended", "HAND_EVENT", "n/a", "ProcessInputData", e.m_Player.ToString());
#endif
        ctx = new ScriptInputUserData;
        InventoryInputUserData.SerializeHandEvent(ctx, e);
        validation.m_Result = InventoryValidationResult.JUNCTURE;
        if (itemSrc)
          EnableMovableOverride(itemSrc);
        if (itemDst)
          EnableMovableOverride(itemDst);
        return true;
      }
      else if (result_ev == JunctureRequestResult.JUNCTURE_DENIED)
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryMoveLogEnable())
          Debug.InventoryMoveLog("Juncture denied", "HAND_EVENT", "n/a", "ProcessInputData", e.m_Player.ToString());
#endif
        validation.m_Reason = InventoryValidationReason.JUNCTURE_DENIED;
        return true;
      }
      else
      {
        Error("[syncinv] HandleInputData: unexpected return code from AcquireInventoryJunctureFromServer");
        return true;
      }
    }
    if (GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
      CheckForRope(e.GetSrc(), e.GetDst());
#ifdef DEVELOPER
    if (LogManager.IsInventoryMoveLogEnable())
      Debug.InventoryMoveLog("Success - ProcessHandEvent", "HAND_EVENT", "n/a", "ProcessInputData", e.m_Player.ToString());
#endif
    validation.m_Result = InventoryValidationResult.SUCCESS;
    if (!e.m_Player.GetHumanInventory().ProcessHandEvent(e))
    {
      //result = InventoryValidationResult.FAILURE;
    }
    return true;
  }
References CheckForRope(), EnableMovableOverride(), Error(), GetDayZPlayerOwner(), GetInstanceType(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), LogManager::IsSyncLogEnable(), RemoveMovableOverride(), InventoryInputUserData::SerializeHandEvent(), and syncDebugPrint().
Referenced by ProcessInputData().
ValidateSwap()
bool ValidateSwap (inout Serializer ctx, InventoryValidation validation) protected
kumarjac: This indicates a failure in replication relationships as player full inventory should be synchronized always if player exists on the remote
Do not check for action validity on remotes or when performing through juncture. Juncture locks guarentee the item is safe to interact with and the server has validated the command at this point. Checking at this point is both wasteful and can result in a failure which leads to desync
Do not check for action validity on remotes or when performing through juncture. Juncture locks guarentee the item is safe to interact with and the server has validated the command at this point. Checking at this point is both wasteful and can result in a failure which leads to desync
Do not check for action validity on remotes or when performing through juncture. Juncture locks guarentee the item is safe to interact with and the server has validated the command at this point. Checking at this point is both wasteful and can result in a failure which leads to desync
Do not check for action validity on remotes or when performing through juncture. Juncture locks guarentee the item is safe to interact with and the server has validated the command at this point. Checking at this point is both wasteful and can result in a failure which leads to desync
Check if this this is being executed on the server and not by a juncture or AI
Continuing on with execution of rest of the function
Definition at line 1009 of file DayZPlayerInventory.c.
  {
    InventoryCommandType type = InventoryCommandType.SWAP;
    InventoryLocation src1 = new InventoryLocation;
    InventoryLocation src2 = new InventoryLocation;
    InventoryLocation dst1 = new InventoryLocation;
    InventoryLocation dst2 = new InventoryLocation;
    bool skippedSwap = false;
    src1.ReadFromContext(ctx);
    src2.ReadFromContext(ctx);
    dst1.ReadFromContext(ctx);
    dst2.ReadFromContext(ctx);
    ctx.Read(skippedSwap);
#ifdef DEVELOPER
    if (LogManager.IsInventoryMoveLogEnable())
      Debug.InventoryMoveLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) + " dst2=" + InventoryLocation.DumpToStringNullSafe(dst2), "SWAP", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
    if (validation.m_IsRemote && (!src1.GetItem() || !src2.GetItem()))
    {
      if (skippedSwap)
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryMoveLogEnable())
          Debug.InventoryMoveLog("Remote - skipped", "SWAP", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
        /*
                if (LogManager.IsSyncLogEnable())
                {
                  syncDebugPrint("[syncinv] HandleInputData remote input (cmd=SWAP) dropped, swap is skipped");
                }
        */
      }
      else
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryMoveLogEnable())
          Debug.InventoryMoveLog("Failed - item1 or item2 not exist", "SWAP", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
        Error("[syncinv] HandleInputData remote input (cmd=SWAP) dropped, item not in bubble");
      }
      return true;
    }
    EnableMovableOverride(src1.GetItem());
    EnableMovableOverride(src2.GetItem());
    if (!validation.m_IsRemote && !validation.m_IsJuncture && !PlayerCheckRequestSrc(src1, GameInventory.c_MaxItemDistanceRadius))
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Failed - CheckRequestSrc1", "SWAP", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
      if (LogManager.IsSyncLogEnable())
        syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " failed src1 check with cmd=" + typename.EnumToString(InventoryCommandType, type) + " src1=" + InventoryLocation.DumpToStringNullSafe(src1));
      RemoveMovableOverride(src1.GetItem());
      RemoveMovableOverride(src2.GetItem());
      return true;
    }
    if (!validation.m_IsRemote && !validation.m_IsJuncture && !PlayerCheckRequestSrc(src2, GameInventory.c_MaxItemDistanceRadius))
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Failed - CheckRequestSrc2", "SWAP", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
      if (LogManager.IsSyncLogEnable())
        syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " failed src2 check with cmd=" + typename.EnumToString(InventoryCommandType, type) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2));
      RemoveMovableOverride(src1.GetItem());
      RemoveMovableOverride(src2.GetItem());
      return true;
    }
    if (!validation.m_IsRemote && !validation.m_IsJuncture && !PlayerCheckSwapItemsRequest(src1, src2, dst1, dst2, GameInventory.c_MaxItemDistanceRadius))
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Failed - CheckSwapItemsRequest", "SWAP", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
      if (LogManager.IsSyncLogEnable())
        syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " is cheating with cmd=" + typename.EnumToString(InventoryCommandType, type) + " src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) + " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " dst2=" + InventoryLocation.DumpToStringNullSafe(dst2));
      RemoveMovableOverride(src1.GetItem());
      RemoveMovableOverride(src2.GetItem());
      return true;
    }
    RemoveMovableOverride(src1.GetItem());
    RemoveMovableOverride(src2.GetItem());
    if (GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
    {
      ClearInventoryReservationEx(dst1.GetItem(), dst1);
      ClearInventoryReservationEx(dst2.GetItem(), dst2);
    }
    if (!validation.m_IsRemote && !validation.m_IsJuncture && !GameInventory.CanForceSwapEntitiesEx(src1.GetItem(), dst1, src2.GetItem(), dst2))
    {
#ifdef DEVELOPER
      DumpInventoryDebug();
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Failed - CanForceSwapEntitiesEx", "SWAP", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
      Error("[desync] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " CANNOT swap cmd=" + typename.EnumToString(InventoryCommandType, type) + " src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " | src2=" + InventoryLocation.DumpToStringNullSafe(src2) + " dst2=" + InventoryLocation.DumpToStringNullSafe(dst2));
      return true;
    }
    if (GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
    {
      AddInventoryReservationEx(dst1.GetItem(), dst1, GameInventory.c_InventoryReservationTimeoutShortMS);
      AddInventoryReservationEx(dst2.GetItem(), dst2, GameInventory.c_InventoryReservationTimeoutShortMS);
    }
    if (!(src1.IsValid() && src2.IsValid() && dst1.IsValid() && dst2.IsValid()))
    {
      Error("HandleInputData: cmd=" + typename.EnumToString(InventoryCommandType, type) + " invalid input(s): src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) + " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " dst2=" + InventoryLocation.DumpToStringNullSafe(dst2));
      return true;
    }
    if (!validation.m_IsJuncture && GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
    {
      JunctureRequestResult result_sw = TryAcquireTwoInventoryJuncturesFromServer(GetDayZPlayerOwner(), src1, src2, dst1, dst2);
      if (result_sw == JunctureRequestResult.JUNCTURE_NOT_REQUIRED)
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryMoveLogEnable())
          Debug.InventoryMoveLog("Juncture not required", "SWAP", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
      }
      else if (result_sw == JunctureRequestResult.JUNCTURE_ACQUIRED)
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryMoveLogEnable())
          Debug.InventoryMoveLog("Juncture sended", "SWAP", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
        validation.m_Result = InventoryValidationResult.JUNCTURE;
        EnableMovableOverride(src1.GetItem());
        EnableMovableOverride(src2.GetItem());
        return true;
      }
      else if (result_sw == JunctureRequestResult.JUNCTURE_DENIED)
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryMoveLogEnable())
          Debug.InventoryMoveLog("Juncture denied", "SWAP", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
        validation.m_Reason = InventoryValidationReason.JUNCTURE_DENIED;
        return true;
      }
      else
      {
        Error("[syncinv] HandleInputData: unexpected return code from TryAcquireTwoInventoryJuncturesFromServer"); return true;
        return true;
      }
    }
    if (GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
    {
      ClearInventoryReservationEx(dst1.GetItem(), dst1);
      ClearInventoryReservationEx(dst2.GetItem(), dst2);
    }
#ifdef DEVELOPER
    if (LogManager.IsInventoryMoveLogEnable())
      Debug.InventoryMoveLog("Success - item swap", "SWAP", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
    bool isNotSkipped = LocationSwap(src1, src2, dst1, dst2);
    ctx = new ScriptInputUserData();
    InventoryInputUserData.SerializeSwap(ctx, src1, src2, dst1, dst2, !isNotSkipped);
    validation.m_Result = InventoryValidationResult.SUCCESS;
    return true;
  }
References GameInventory::c_InventoryReservationTimeoutShortMS, GameInventory::c_MaxItemDistanceRadius, GameInventory::CanForceSwapEntitiesEx(), ClearInventoryReservationEx(), InventoryLocation::DumpToStringNullSafe(), EnableMovableOverride(), Error(), GetDayZPlayerOwner(), GetInstanceType(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), LogManager::IsSyncLogEnable(), PlayerCheckRequestSrc(), PlayerCheckSwapItemsRequest(), RemoveMovableOverride(), InventoryInputUserData::SerializeSwap(), syncDebugPrint(), ToString(), and TryAcquireTwoInventoryJuncturesFromServer().
Referenced by ProcessInputData().
ValidateSyncMove()
bool ValidateSyncMove (inout Serializer ctx, InventoryValidation validation) protected
kumarjac: This indicates a failure in replication relationships as player full inventory should be synchronized always if player exists on the remote
Do not check for action validity on remotes or when performing through juncture. Juncture locks guarentee the item is safe to interact with and the server has validated the command at this point. Checking at this point is both wasteful and can result in a failure which leads to desync
kumarjac: This indicates a failure in replication relationships as player full inventory should be synchronized always if player exists on the remote
Do not check for action validity on remotes or when performing through juncture. Juncture locks guarentee the item is safe to interact with and the server has validated the command at this point. Checking at this point is both wasteful and can result in a failure which leads to desync
Check if this this is being executed on the server and not by a juncture or AI so we can lock the item and ensure replication relationships are setup
TODO(kumarjac): We should continue with the execution and not have this special block but making a change here now will require testing
Is called twice unfortunately...
Do not check for action validity on remotes or when performing through juncture. Juncture locks guarentee the item is safe to interact with and the server has validated the command at this point. Checking at this point is both wasteful and can result in a failure which leads to desync
Definition at line 667 of file DayZPlayerInventory.c.
  {
    InventoryCommandType type = InventoryCommandType.SYNC_MOVE;
    InventoryLocation src = new InventoryLocation;
    InventoryLocation dst = new InventoryLocation;
    src.ReadFromContext(ctx);
    dst.ReadFromContext(ctx);
#ifdef DEVELOPER
    if (LogManager.IsInventoryMoveLogEnable())
      Debug.InventoryMoveLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + "src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst), "SYNC_MOVE", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
    if (validation.m_IsRemote && (!src.GetItem() || !dst.GetItem()))
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Failed - item not in bubble", "SYNC_MOVE", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
      if (LogManager.IsSyncLogEnable())
        syncDebugPrint("[syncinv] HandleInputData remote input (cmd=SYNC_MOVE) dropped, item not in bubble! src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
      return true;
    }
    EnableMovableOverride(src.GetItem());
    if (!validation.m_IsRemote && !validation.m_IsJuncture && !PlayerCheckRequestSrc(src, GameInventory.c_MaxItemDistanceRadius))
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Failed - CheckRequestSrc", "SYNC_MOVE", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
      if (LogManager.IsSyncLogEnable())
        syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " failed src check with cmd=" + typename.EnumToString(InventoryCommandType, type) + " src=" + InventoryLocation.DumpToStringNullSafe(src));
      RemoveMovableOverride(src.GetItem());
      return true;
    }
    if (!validation.m_IsRemote && !validation.m_IsJuncture && !PlayerCheckRequestDst(src, dst, GameInventory.c_MaxItemDistanceRadius))
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Failed - CheckMoveToDstRequest", "SYNC_MOVE", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
      if (LogManager.IsSyncLogEnable())
        syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " is cheating with cmd=" + typename.EnumToString(InventoryCommandType, type) + " src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
      RemoveMovableOverride(src.GetItem());
      return true;
    }
    RemoveMovableOverride(src.GetItem());
    if (LogManager.IsSyncLogEnable())
      syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " HandleInputData t=" + GetGame().GetTime() + "ms received cmd=" + typename.EnumToString(InventoryCommandType, type) + " src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
    if (!validation.m_IsJuncture && GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
    {
      JunctureRequestResult result_mv = TryAcquireInventoryJunctureFromServer(GetDayZPlayerOwner(), src, dst);
      if (result_mv == JunctureRequestResult.JUNCTURE_NOT_REQUIRED)
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryMoveLogEnable())
          Debug.InventoryMoveLog("Juncture not required", "SYNC_MOVE", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
        LocationSyncMoveEntity(src, dst);
        validation.m_Result = InventoryValidationResult.SUCCESS;
        return true;
      }
      else if (result_mv == JunctureRequestResult.JUNCTURE_ACQUIRED)
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryMoveLogEnable())
          Debug.InventoryMoveLog("Juncture sended", "SYNC_MOVE", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
        if (!GameInventory.LocationCanMoveEntity(src, dst))
        {
#ifdef DEVELOPER
          DumpInventoryDebug();
          if (LogManager.IsInventoryMoveLogEnable())
            Debug.InventoryMoveLog("Failed - LocationCanMoveEntity - Juncture denied", "SYNC_MOVE", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
          return true;
        }
        validation.m_Result = InventoryValidationResult.JUNCTURE;
        EnableMovableOverride(src.GetItem());
        return true;
      }
      else if (result_mv == JunctureRequestResult.JUNCTURE_DENIED)
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryMoveLogEnable())
          Debug.InventoryMoveLog("Juncture denied", "SYNC_MOVE", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
        validation.m_Reason = InventoryValidationReason.JUNCTURE_DENIED;
        return true;
      }
      else
      {
        Error("[syncinv] HandleInputData: unexpected return code from AcquireInventoryJunctureFromServer");
        return true;
      }
    }
    if (GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
      ClearInventoryReservationEx(dst.GetItem(), dst);
    if (GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
      CheckForRope(src, dst);
    if (!validation.m_IsRemote && !validation.m_IsJuncture && !GameInventory.LocationCanMoveEntitySyncCheck(src, dst))
    {
#ifdef DEVELOPER
      DumpInventoryDebug();
      if (LogManager.IsInventoryMoveLogEnable())
        Debug.InventoryMoveLog("Failed - LocationCanMoveEntity", "SYNC_MOVE", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
      Error("[desync] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " CANNOT move cmd=" + typename.EnumToString(InventoryCommandType, type) + " src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
      return true;
    }
#ifdef DEVELOPER
    if (LogManager.IsInventoryMoveLogEnable())
      Debug.InventoryMoveLog("Success - LocationSyncMoveEntity", "SYNC_MOVE", "n/a", "ProcessInputData", GetDayZPlayerOwner().ToString());
#endif
    LocationSyncMoveEntity(src, dst);
    validation.m_Result = InventoryValidationResult.SUCCESS;
    return true;
  }
References GameInventory::c_MaxItemDistanceRadius, CheckForRope(), ClearInventoryReservationEx(), InventoryLocation::DumpToStringNullSafe(), EnableMovableOverride(), Error(), GetDayZPlayerOwner(), GetGame(), GetInstanceType(), GetTime(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), LogManager::IsSyncLogEnable(), GameInventory::LocationCanMoveEntity(), GameInventory::LocationCanMoveEntitySyncCheck(), PlayerCheckRequestDst(), PlayerCheckRequestSrc(), RemoveMovableOverride(), syncDebugPrint(), ToString(), and TryAcquireInventoryJunctureFromServer().
Referenced by ProcessInputData().
Variable Documentation
m_DeferredEvent
m_DeferredEvent = NULL
Referenced by ForceSwapEntities(), HandEvent(), HandleInventoryManipulation(), IsProcessing(), SwapEntities(), and TakeToDst().
m_DeferredPostedHandEvent
ref HandEventBase m_DeferredPostedHandEvent = NULL protected
Definition at line 136 of file DayZPlayerInventory.c.
Referenced by CancelHandEvent(), and IsProcessing().
m_DeferredWeaponEvent
ref WeaponEventBase m_DeferredWeaponEvent = NULL protected
deferred hand event
Definition at line 137 of file DayZPlayerInventory.c.
Referenced by CancelWeaponEvent(), DeferredWeaponFailed(), HandleWeaponEvents(), and PostWeaponEvent().
m_DeferredWeaponTimer
ref Timer m_DeferredWeaponTimer = new Timer
Definition at line 132 of file DayZPlayerInventory.c.
Referenced by CancelWeaponEvent(), and HandleWeaponEvents().
m_dst
ref InventoryLocation m_dst
Definition at line 13 of file DayZPlayerInventory.c.
Referenced by ClearInventoryReservation(), DeferredTakeToDst(), WeaponStateBase::LoadCurrentFSMState(), WeaponStateBase::OnAbort(), WeaponStateBase::OnEntry(), WeaponStateBase::OnExit(), WeaponEventBase::ReadFromContext(), ReserveInventory(), WeaponStateBase::SaveCurrentFSMState(), WeaponEventBase::WeaponEventDetachMagazine(), WeaponEventBase::WeaponEventSwapMagazine(), and WeaponEventBase::WriteToContext().
m_dst1
ref InventoryLocation m_dst1
Definition at line 74 of file DayZPlayerInventory.c.
Referenced by DeferredForceSwapEntities().
m_dst2
ref InventoryLocation m_dst2
Definition at line 75 of file DayZPlayerInventory.c.
Referenced by DeferredForceSwapEntities().
m_event
ref HandEventBase m_event
Definition at line 107 of file DayZPlayerInventory.c.
Referenced by FSMTransition< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FSMTransition().
m_FSwapping
ref HandAnimatedForceSwapping m_FSwapping protected
Definition at line 142 of file DayZPlayerInventory.c.
Referenced by Init().
m_FSwappingInst
ref HandAnimatedForceSwapping_Inst m_FSwappingInst protected
Definition at line 143 of file DayZPlayerInventory.c.
Referenced by Init().
m_item1
DeferredSwapEntities m_item1
Referenced by DeferredForceSwapEntities().
m_item2
EntityAI m_item2
Definition at line 73 of file DayZPlayerInventory.c.
Referenced by DeferredForceSwapEntities().
m_MovingTo
ref HandAnimatedMovingToAtt m_MovingTo protected
Definition at line 140 of file DayZPlayerInventory.c.
Referenced by Init().
m_src
class DeferredEvent m_src
Referenced by DeferredTakeToDst().
m_Swapping
ref HandAnimatedSwapping m_Swapping protected
Definition at line 141 of file DayZPlayerInventory.c.
Referenced by Init().
m_Taking
ref HandAnimatedTakingFromAtt m_Taking protected
deferred weapon event
Definition at line 139 of file DayZPlayerInventory.c.
Referenced by Init().