DayZ: JsonMissionLoaderData Class Reference
JsonMissionLoaderData Class Reference
Static Private Member Functions
static JsonMissionLoaderData GetData ()
Private Attributes
ref TStringArray MissionPaths
Detailed Description
Definition at line 1 of file MissionLoader.c.
Member Function Documentation
GetData()
static JsonMissionLoaderData JsonMissionLoaderData::GetData () inline static private
Definition at line 5 of file MissionLoader.c.
  {
    JsonMissionLoaderData data;
    string path;
    string errorMessage;
    if (GetCLIParam("missionLoaderPath", path) == false)
      path = CFG_FILE_MISSION_LIST;
    if (!FileExist(path))
    {
      DayZGame dzg = GetDayZGame();
      data = new JsonMissionLoaderData();
      data.MissionPaths = {dzg.GetMissionFolderPath()};
      if (!JsonFileLoader<JsonMissionLoaderData>.SaveFile(path, data, errorMessage))
        ErrorEx(errorMessage);
    }
    else
    {
      if (!JsonFileLoader<JsonMissionLoaderData>.LoadFile(path, data, errorMessage))
        ErrorEx(errorMessage);
    }
    return data;
  }
References CFG_FILE_MISSION_LIST, ErrorEx, FileExist(), GetCLIParam(), GetDayZGame(), and path.
Referenced by Init().
Member Data Documentation
MissionPaths
ref TStringArray JsonMissionLoaderData::MissionPaths private
Definition at line 3 of file MissionLoader.c.
The documentation for this class was generated from the following file:
scripts/5_Mission/GUI/ScriptedWindows/MissionLoader.c