DayZ: scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionRepairCarEngine.c File Reference
ActionRepairCarEngine.c File Reference
Classes
class RepairCarEngineActionReciveData
class ActionRepairCarEngineCB
Functions
void ActionRepairCarEngine ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override ActionData CreateActionData ()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
Variables
RepairCarEngineActionReciveData m_DamageZone
ActionRepairCarEngineCB m_LastValidType
string m_CurrentDamageZone = ""
int m_LastValidComponentIndex = -1
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 42 of file ActionRepairCarEngine.c.
  {
    if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
      return false;
    Object targetObject = target.GetObject();
    Object targetParent = target.GetParent();
    CarScript car = CarScript.Cast(targetObject);
    EntityAI carEntity = EntityAI.Cast(targetObject);
    if (!car || !player)
      return false;
    if (car.EngineIsOn())
      return false;
    if (GetGame().IsMultiplayer() && GetGame().IsServer())
      return true;
    if (m_LastValidType != target.Type() || m_LastValidComponentIndex != target.GetComponentIndex() || m_CurrentDamageZone == "")
    {
      string damageZone = "";
      array<string> selections = new array<string>();
      targetObject.GetActionComponentNameList(target.GetComponentIndex(), selections, LOD.NAME_VIEW);
      foreach (string selection : selections)
      {
        //NOTE: relevant fire geometry and view geometry selection names MUST match in order to get a valid damage zone
        if (carEntity && DamageSystem.GetDamageZoneFromComponentName(carEntity, selection, damageZone))
        {
          if (damageZone == "Engine")
          {
            int zoneHP = car.GetHealthLevel(damageZone);
            if (zoneHP > GameConstants.STATE_WORN && zoneHP < GameConstants.STATE_RUINED)
            {
              m_CurrentDamageZone = damageZone;
              m_LastValidComponentIndex = target.GetComponentIndex();
              return true;
            }
          }
        }
      }
    }
    return false;
  }
References GetGame(), m_CurrentDamageZone, m_LastValidComponentIndex, m_LastValidType, LOD::NAME_VIEW, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
ActionRepairCarEngine()
void ActionRepairCarEngine ()
Definition at line 25 of file ActionRepairCarEngine.c.
  {
    m_CallbackClass = ActionRepairTentPartCB;
    m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
    m_FullBody = true;
    m_LockTargetOnUse = false;
    m_Text = "#repair";
  }
References m_FullBody, m_LockTargetOnUse, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Referenced by ActionConstructor::RegisterActions().
CreateActionData()
override ActionData CreateActionData ()
Definition at line 130 of file ActionRepairCarEngine.c.
  {
    RepairCarPartActionData actionData = new RepairCarPartActionData();
    return actionData;
  }
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 36 of file ActionRepairCarEngine.c.
  {
    m_ConditionItem = new CCINonRuined();
    m_ConditionTarget = new CCTCursor(UAMaxDistances.REPAIR);
  }
References m_ConditionItem, m_ConditionTarget, and UAMaxDistances::REPAIR.
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
Definition at line 168 of file ActionRepairCarEngine.c.
  {
    super.HandleReciveData(action_recive_data, action_data);
    RepairCarPartActionReciveData reciveDataRepair = RepairCarPartActionReciveData.Cast(action_recive_data);
    RepairCarPartActionData.Cast(action_data).m_DamageZone = reciveDataRepair.m_DamageZoneRecived;
  }
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 90 of file ActionRepairCarEngine.c.
  {
    Object tgObject = action_data.m_Target.GetObject();
    string damageZone = RepairCarPartActionData.Cast(action_data).m_DamageZone;
    if (!GetGame().IsMultiplayer())
      damageZone = m_CurrentDamageZone;
    if (tgObject && damageZone != "")
    {
      CarScript car = CarScript.Cast(tgObject);
      if (car)
      {
        int newDmgLevel = Math.Clamp(car.GetHealthLevel(damageZone) - 1, GameConstants.STATE_WORN, GameConstants.STATE_RUINED);
        float zoneMax = car.GetMaxHealth(damageZone, "");
        float randomValue = Math.RandomFloatInclusive(zoneMax * 0.05, zoneMax * 0.15);
        switch (newDmgLevel)
        {
        case GameConstants.STATE_BADLY_DAMAGED:
          car.SetHealth(damageZone, "", (zoneMax * GameConstants.DAMAGE_RUINED_VALUE) + randomValue);
          break;
        case GameConstants.STATE_DAMAGED:
          car.SetHealth(damageZone, "", (zoneMax * GameConstants.DAMAGE_BADLY_DAMAGED_VALUE) + randomValue);
          break;
        case GameConstants.STATE_WORN:
          car.SetHealth(damageZone, "", (zoneMax * GameConstants.DAMAGE_DAMAGED_VALUE) + randomValue);
          break;
        default:
          break;
        }
        MiscGameplayFunctions.DealAbsoluteDmg(action_data.m_MainItem, UADamageApplied.BUILD);
      }
    }
  }
References UADamageApplied::BUILD, Math::Clamp(), GameConstants::DAMAGE_BADLY_DAMAGED_VALUE, GameConstants::DAMAGE_DAMAGED_VALUE, GameConstants::DAMAGE_RUINED_VALUE, GetGame(), m_CurrentDamageZone, Math::RandomFloatInclusive(), GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
Definition at line 148 of file ActionRepairCarEngine.c.
  {
    if (!action_recive_data)
      action_recive_data = new RepairCarPartActionReciveData();
    super.ReadFromContext(ctx, action_recive_data);
    RepairCarPartActionReciveData reciveDataRepair = RepairCarPartActionReciveData.Cast(action_recive_data);
    if (HasTarget())
    {
      string zone;
      if (!ctx.Read(zone))
        return false;
      reciveDataRepair.m_DamageZoneRecived = zone;
    }
    return true;
  }
References HasTarget().
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Definition at line 136 of file ActionRepairCarEngine.c.
  {
    super.WriteToContext(ctx, action_data);
    RepairCarPartActionData repairActionData;
    if (HasTarget() && Class.CastTo(repairActionData, action_data))
    {
      repairActionData.m_DamageZone = m_CurrentDamageZone;
      ctx.Write(repairActionData.m_DamageZone);
    }
  }
References Class::CastTo(), HasTarget(), and m_CurrentDamageZone.
Variable Documentation
m_CurrentDamageZone
string m_CurrentDamageZone = ""
Definition at line 22 of file ActionRepairCarEngine.c.
Referenced by ActionCondition(), OnFinishProgressServer(), and WriteToContext().
m_DamageZone
RepairCarEngineActionReciveData m_DamageZone
m_LastValidComponentIndex
int m_LastValidComponentIndex = -1
Definition at line 23 of file ActionRepairCarEngine.c.
Referenced by ActionCondition().
m_LastValidType
ActionRepairCarEngineCB m_LastValidType
Referenced by ActionCondition().