DayZ: ScriptConsoleOutputTab Class Reference
ScriptConsoleOutputTab Class Reference
Protected Member Functions
void ScriptConsoleOutputTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void ~ScriptConsoleOutputTab ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnChange (Widget w, int x, int y, bool finished)
void Clear (bool clearFile=false)
void Add (string message, bool isReload=false)
void ReloadOutput ()
Protected Attributes
TextListboxWidget m_ClientLogListbox
ButtonWidget m_ClientLogClearButton
CheckBoxWidget m_ClientLogScrollCheckbox
Additional Inherited Members
Private Member Functions inherited from ScriptConsoleTabBase
void ScriptConsoleTabBase (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void Init (int id)
int GetID ()
Widget GetRoot ()
bool IsSelected ()
void Select (bool select, ScriptConsoleTabBase selectedHandler)
void OnSelected ()
void Show (bool show, ScriptConsoleTabBase selectedHandler)
Widget GetButton ()
void Update (float timeslice)
bool OnChange (Widget w, int x, int y, bool finished)
bool OnClick (Widget w, int x, int y, int button)
bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
bool OnKeyDown (Widget w, int x, int y, int key)
bool OnDoubleClick (Widget w, int x, int y, int button)
void OnRPCEx (int rpc_type, ParamsReadContext ctx)
bool OnMouseButtonDown (Widget w, int x, int y, int button)
bool OnKeyPress (Widget w, int x, int y, int key)
void AddItemToClipboard (TextListboxWidget text_listbox_widget)
Private Attributes inherited from ScriptConsoleTabBase
int m_Id
bool m_IsSelected
Widget m_ParentRoot
Widget m_Root
Widget m_Button
ScriptConsole m_ScriptConsole
ScriptConsoleTabBase m_Parent
PluginConfigDebugProfile m_ConfigDebugProfile
PluginConfigDebugProfileFixed m_ConfigDebugProfileFixed
Detailed Description
Definition at line 1 of file ScriptConsoleOutputTab.c.
Constructor & Destructor Documentation
ScriptConsoleOutputTab()
void ScriptConsoleOutputTab::ScriptConsoleOutputTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent = null) inline protected
Definition at line 7 of file ScriptConsoleOutputTab.c.
  {
    m_ClientLogListbox = TextListboxWidget.Cast(root.FindAnyWidget("TextListbox"));
    m_ClientLogClearButton = ButtonWidget.Cast(root.FindAnyWidget("ButtonClear"));
    m_ClientLogScrollCheckbox = CheckBoxWidget.Cast(root.FindAnyWidget("CheckBoxAutoScroll"));
    ReloadOutput();
  }
References m_ClientLogClearButton, m_ClientLogListbox, m_ClientLogScrollCheckbox, and ReloadOutput().
~ScriptConsoleOutputTab()
void ScriptConsoleOutputTab::~ScriptConsoleOutputTab () inline protected
Definition at line 15 of file ScriptConsoleOutputTab.c.
  {
  }
Member Function Documentation
Add()
void ScriptConsoleOutputTab::Add (string message, bool isReload = false) inline protected
Definition at line 45 of file ScriptConsoleOutputTab.c.
  {
    if (m_ClientLogListbox)
    {
      m_ClientLogListbox.AddItem(String(message), NULL, 0);
      if (m_ClientLogScrollCheckbox.IsChecked())
        m_ClientLogListbox.EnsureVisible(m_ClientLogListbox.GetNumItems());
    }
  }
References m_ClientLogListbox, m_ClientLogScrollCheckbox, and String().
Referenced by ReloadOutput().
Clear()
void ScriptConsoleOutputTab::Clear (bool clearFile = false) inline protected
Definition at line 38 of file ScriptConsoleOutputTab.c.
  {
    if (clearFile)
      Debug.ClearLogs();
    m_ClientLogListbox.ClearItems();
  }
References Debug::ClearLogs(), and m_ClientLogListbox.
Referenced by OnClick(), and ReloadOutput().
OnChange()
override bool ScriptConsoleOutputTab::OnChange (Widget w, int x, int y, bool finished) inline protected
Definition at line 31 of file ScriptConsoleOutputTab.c.
  {
    super.OnChange(w, x, y, finished);
    return false;
  }
References x, and y.
OnClick()
override bool ScriptConsoleOutputTab::OnClick (Widget w, int x, int y, int button) inline protected
Definition at line 19 of file ScriptConsoleOutputTab.c.
  {
    super.OnClick(w, x, y, button);
    if (w == m_ClientLogClearButton)
    {
      Clear(true);
      return true;
    }
    return false;
  }
References Clear(), m_ClientLogClearButton, x, and y.
ReloadOutput()
void ScriptConsoleOutputTab::ReloadOutput () inline protected
Definition at line 56 of file ScriptConsoleOutputTab.c.
  {
    Clear();
    FileHandle file_index = OpenFile(Debug.GetFileName(), FileMode.READ);
    if (file_index)
    {
      string line_content;
      while (FGets(file_index, line_content) != -1)
        Add(line_content, true);
      CloseFile(file_index);
    }
  }
References Add(), Clear(), CloseFile(), FGets(), Debug::GetFileName(), and OpenFile().
Referenced by ScriptConsoleOutputTab().
Member Data Documentation
m_ClientLogClearButton
ButtonWidget ScriptConsoleOutputTab::m_ClientLogClearButton protected
Definition at line 4 of file ScriptConsoleOutputTab.c.
Referenced by OnClick(), and ScriptConsoleOutputTab().
m_ClientLogListbox
TextListboxWidget ScriptConsoleOutputTab::m_ClientLogListbox protected
Definition at line 3 of file ScriptConsoleOutputTab.c.
Referenced by Add(), Clear(), and ScriptConsoleOutputTab().
m_ClientLogScrollCheckbox
CheckBoxWidget ScriptConsoleOutputTab::m_ClientLogScrollCheckbox protected
Definition at line 5 of file ScriptConsoleOutputTab.c.
Referenced by Add(), and ScriptConsoleOutputTab().
The documentation for this class was generated from the following file:
scripts/5_Mission/GUI/ScriptConsoleOutputTab.c