DayZ: Rifle_Base Class Reference
Rifle_Base Class Reference
base for rifles @NOTE name copies config base class
Private Member Functions
override RecoilBase SpawnRecoilObject ()
override void InitStateMachine ()
override bool CanEnterIronsights ()
override void SetActions ()
override void OnDebugSpawn ()
override void InitStateMachine ()
override bool CanChamberBullet (int muzzleIndex, Magazine mag)
override void SetActions ()
void RifleBoltFree_Base ()
override void InitStateMachine ()
override float GetChanceToJam ()
override void SetActions ()
void RifleBoltLock_Base ()
override void InitStateMachine ()
override float GetChanceToJam ()
override void SetActions ()
void RifleSingleShot_Base ()
override void InitStateMachine ()
override float GetChanceToJam ()
Private Attributes
ref WeaponStableState C0
ref WeaponStableState C1
ref WeaponStableState L0
ref WeaponStableState JF
ref WeaponStableState D0
ref WeaponStableState DF
ref WeaponStableState C00
ref WeaponStableState C10
ref WeaponStableState C11
ref WeaponStableState C01
ref WeaponStableState JF0
ref WeaponStableState JF1
ref WeaponStableState O00
ref WeaponStableState O01
Detailed Description
base for rifles @NOTE name copies config base class
Definition at line 69 of file SKS.c.
Member Function Documentation
CanChamberBullet()
override bool Rifle_Base::CanChamberBullet (int muzzleIndex, Magazine mag) inline private
Definition at line 219 of file Repeater.c.
  {
    return CanChamberFromMag(muzzleIndex, mag) && !IsInternalMagazineFull(muzzleIndex);
  }
CanEnterIronsights()
override bool Rifle_Base::CanEnterIronsights () inline private
Definition at line 248 of file SKS.c.
  {
    ItemOptics optic = GetAttachedOptics();
    if (optic && PUScopeOptic.Cast(optic))
      return true;
    return super.CanEnterIronsights();
  }
GetChanceToJam() [1/3]
override float Rifle_Base::GetChanceToJam () inline private
Definition at line 364 of file RifleBoltFree_Base.c.
  {
    float chanceToJam = super.GetChanceToJam();
    Magazine mag = GetMagazine(GetCurrentMuzzle());
    if (mag)
      chanceToJam = chanceToJam + ((1.0 - chanceToJam) * mag.GetChanceToJam());
    else
      chanceToJam = chanceToJam + ((1.0 - chanceToJam) * 0.06);
    return chanceToJam;
  }
GetChanceToJam() [2/3]
override float Rifle_Base::GetChanceToJam () inline private
Definition at line 481 of file RifleBoltLock_Base.c.
  {
    float chanceToJam = super.GetChanceToJam();
    Magazine mag = GetMagazine(GetCurrentMuzzle());
    if (mag)
      chanceToJam = chanceToJam + ((1.0 - chanceToJam) * mag.GetChanceToJam());
    else
      chanceToJam = chanceToJam + ((1.0 - chanceToJam) * 0.06);
    return chanceToJam;
  }
GetChanceToJam() [3/3]
override float Rifle_Base::GetChanceToJam () inline private
Definition at line 190 of file RifleSingleShot_Base.c.
  {
    return 0.0;
  }
InitStateMachine() [1/5]
override void Rifle_Base::InitStateMachine () inline private
Definition at line 81 of file SKS.c.
  {
    m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_CLOSED_KEEP));
    m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_CLOSED));
    m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_OPENED));
    m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ENDLOOPABLE));
    m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD_CLIP, 0));
    m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_OPENED)));//????
    m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, GetWeaponSpecificCommand(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, GetWeaponSpecificCommand(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_END)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_LAST)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_JAM)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY)));
    //m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_UNCOCKED));
    // setup state machine
    // basic weapon states
    // close-locked-jammed | nobullet-bullet | nomag-mag
    // regexp: [CLJ][01][01]
    C0 = new SKS_CLO_BU0(this, NULL, SKSAnimState.DEFAULT);
    C1 = new SKS_CLO_BU1(this, NULL, SKSAnimState.DEFAULT);
    L0 = new SKS_OPN_BU0(this, NULL, SKSAnimState.OPENED);
    JF = new SKS_JAM_BU1(this, NULL, SKSAnimState.JAMMED);
    // unstable (intermediate) states
    WeaponChargingInnerMag Mech_C0 = new WeaponChargingInnerMag(this, NULL, WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
    WeaponChargingInnerMag Mech_L0 = new WeaponChargingInnerMag(this, NULL, WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_OPENED));
    WeaponChargingInnerMag Mech_C1 = new WeaponChargingInnerMag(this, NULL, WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
    //Fire
    WeaponStateBase Trigger_C0 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY)); // cock without clip
    WeaponFireAndChamberFromInnerMagazine Trigger_C1 = new WeaponFireAndChamberFromInnerMagazine(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL));
    WeaponStateBase Trigger_C1L = new WeaponFireLast(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_LAST));
    WeaponStateBase Trigger_L0 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY));
    WeaponStateBase Trigger_JF = new WeaponDryFire(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY));
    WeaponStateBase Trigger_C1J = new WeaponFireToJam(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_JAM);
    //Unjam
    WeaponStateBase Unjam_JF = new WeaponUnjamming(this, NULL, WeaponActions.UNJAMMING, GetWeaponSpecificCommand(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START));
    //Chambering
    LoopedChambering Chamber_C0 = new LoopedChambering(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_CLOSED, WeaponActionChamberingTypes.CHAMBERING_ENDLOOPABLE);
    LoopedChambering Chamber_C1 = new LoopedChambering(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_CLOSED_KEEP, WeaponActionChamberingTypes.CHAMBERING_ENDLOOPABLE);
    LoopedChambering Chamber_L0 = new LoopedChambering(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_OPENED, WeaponActionChamberingTypes.CHAMBERING_ENDLOOPABLE);
    //WeaponStateBase chmMag = new WeaponChamberFromAttMag(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED);
    // events
    WeaponEventBase __M__ = new WeaponEventMechanism;
    WeaponEventBase __T__ = new WeaponEventTrigger;
    WeaponEventBase __TJ_ = new WeaponEventTriggerToJam;
    WeaponEventBase __U__ = new WeaponEventUnjam;
    WeaponEventBase __L__ = new WeaponEventLoad1Bullet;
    WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
    WeaponEventBase _abt_ = new WeaponEventHumanCommandActionAborted;
    WeaponEventBase _rto_ = new WeaponEventReloadTimeout;
    WeaponEventBase _dto_ = new WeaponEventDryFireTimeout;
    m_fsm = new WeaponFSM();
    // order: Discharged-Charged | nobullet-bullet | nomag-mag
    // charging
    m_fsm.AddTransition(new WeaponTransition(C0, __M__, Mech_C1)); // charge from dischg nobullet nomag
    m_fsm.AddTransition(new WeaponTransition(C1, __M__, Mech_C1)); // charge from bullet nomag
    m_fsm.AddTransition(new WeaponTransition(Mech_C1, _fin_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C1, _fin_, C1));
    m_fsm.AddTransition(new WeaponTransition(Mech_C1, _abt_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C1, _abt_, C1));
    m_fsm.AddTransition(new WeaponTransition(L0, __M__, Mech_L0)); // charge from dischg nobullet nomag
    m_fsm.AddTransition(new WeaponTransition(Mech_L0, _fin_, L0, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_L0, _fin_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_L0, _fin_, C1));
    m_fsm.AddTransition(new WeaponTransition(Mech_L0, _abt_, L0, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_L0, _abt_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_L0, _abt_, C1));
    /*m_start = new WeaponCharging_Start(m_weapon, this, m_action, m_actionType);
      m_onBE = new WeaponEjectBullet_Cartridge_W4T(m_weapon, this);
      m_onBEFireOut = new WeaponEjectCasing_W4T(m_weapon, this);
      m_hideB = new BulletHide_W4T(m_weapon, this);
      m_onCK = new WeaponCharging_CK(m_weapon, this);
      m_chamber = new WeaponChamberFromInnerMag_W4T(m_weapon, this);*/
    // fire
    m_fsm.AddTransition(new WeaponTransition(C0, __T__, Trigger_C0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C0, _fin_, C0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C0, _dto_, C0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C0, _abt_, C0));
    m_fsm.AddTransition(new WeaponTransition(C1, __T__, Trigger_C1, NULL, new WeaponGuardHasAmmoInnerMagazine(this)));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C1, _fin_, C1));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C1, _rto_, C1));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C1, _abt_, C1));
    m_fsm.AddTransition(new WeaponTransition(C1, __T__, Trigger_C1L));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C1L, _fin_, L0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C1L, _rto_, L0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C1L, _abt_, L0));
    m_fsm.AddTransition(new WeaponTransition(C1, __TJ_, Trigger_C1J));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C1J, _fin_, JF));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C1J, _rto_, JF));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C1J, _abt_, JF));
    m_fsm.AddTransition(new WeaponTransition(L0, __T__, Trigger_L0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_L0, _fin_, L0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_L0, _dto_, L0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_L0, _abt_, L0));
    m_fsm.AddTransition(new WeaponTransition(JF, __T__, Trigger_JF)); // opened fire.uncocked w mag
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF, _fin_, JF));
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF, _dto_, JF));
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF, _abt_, JF));
    // load cartridge
    m_fsm.AddTransition(new WeaponTransition(C0, __L__, Chamber_C0));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C0, _fin_, L0, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C0, _fin_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C0, _fin_, C1));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C0, _abt_, L0, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C0, _abt_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C0, _abt_, C1));
    m_fsm.AddTransition(new WeaponTransition(C1, __L__, Chamber_C1, NULL, new GuardNot(new WeaponGuardInnerMagazineFullShareChamber(this))));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C1, _fin_, C1));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C1, _abt_, C1));
    m_fsm.AddTransition(new WeaponTransition(L0, __L__, Chamber_L0, NULL, new GuardNot(new WeaponGuardInnerMagazineFullShareChamber(this))));
    m_fsm.AddTransition(new WeaponTransition(Chamber_L0, _fin_, L0, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_L0, _fin_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_L0, _fin_, C1));
    m_fsm.AddTransition(new WeaponTransition(Chamber_L0, _abt_, L0, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_L0, _abt_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_L0, _abt_, C1));
    // unjam
    m_fsm.AddTransition(new WeaponTransition(JF, __U__, Unjam_JF)); // unjam nomag
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF, _fin_, JF, NULL, new WeaponGuardJammed(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF, _fin_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF, _fin_, C1));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF, _abt_, JF, NULL, new WeaponGuardJammed(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF, _abt_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF, _abt_, C1));
    SetInitialState(C0);
    SelectionBulletHide();
    HideMagazine();
    m_fsm.Start();
  }
References SKS_CLO_BU0, SKS_CLO_BU1, SKS_JAM_BU1, SKS_OPN_BU0, and WeaponGuardWeaponOpen().
InitStateMachine() [2/5]
override void Rifle_Base::InitStateMachine () inline private
Definition at line 75 of file Repeater.c.
  {
    m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
    m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_OPENED));
    m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_SHOTGUN_COCKED));
    m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_SHOTGUN_UNCOCKED));
    m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ENDLOOPABLE));
    m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START));
    m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_END));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_COCKED));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_UNCOCKED));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY));
    D0 = new RPTEmptyDischarged(this, NULL, RPTAnimState.DEFAULT);
    C0 = new RPTEmptyDischarged(this, NULL, RPTAnimState.CHARGED);
    DF = new RPTLoadedDischarged(this, NULL, RPTAnimState.DEFAULT);
    C1 = new RPTLoadedCharged(this, NULL, RPTAnimState.CHARGED);
    JF = new RPTLoadedJammed(this, NULL, RPTAnimState.JAMMED);
    //WeaponStateBase Mech_D0 = new WeaponChargingInnerMag(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED);
    WeaponStateBase Mech_C1 = new WeaponChargingInnerMag(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_OPENED);
    WeaponStateBase Mech_DF = new WeaponChargingInnerMag(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED);
    LoopedChamberingEjectLast Chamber_D0 = new LoopedChamberingEjectLast(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_SHOTGUN_UNCOCKED, WeaponActionChamberingTypes.CHAMBERING_ENDLOOPABLE);
    LoopedChamberingEjectLast Chamber_C0 = new LoopedChamberingEjectLast(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_SHOTGUN_UNCOCKED, WeaponActionChamberingTypes.CHAMBERING_ENDLOOPABLE);
    LoopedChamberingEjectLast Chamber_C1 = new LoopedChamberingEjectLast(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_SHOTGUN_COCKED, WeaponActionChamberingTypes.CHAMBERING_ENDLOOPABLE);
    LoopedChamberingEjectLast Chamber_DF = new LoopedChamberingEjectLast(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_SHOTGUN_UNCOCKED, WeaponActionChamberingTypes.CHAMBERING_ENDLOOPABLE);
    WeaponStateBase Unjam_JF = new WeaponUnjamming(this, NULL, WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START);
    WeaponStateBase Trigger_D0 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY);
    WeaponStateBase Trigger_C0 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL);
    WeaponStateBase Trigger_C1 = new WeaponFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL);
    WeaponStateBase Trigger_DF = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY);
    WeaponStateBase Trigger_JF = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY);
    WeaponStateBase Trigger_C1J = new WeaponFireToJam(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_JAM);
    WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
    WeaponEventBase __L__ = new WeaponEventLoad1Bullet;
    WeaponEventBase __T__ = new WeaponEventTrigger;
    WeaponEventBase __TJ_ = new WeaponEventTriggerToJam;
    WeaponEventBase __U__ = new WeaponEventUnjam;
    WeaponEventBase __M__ = new WeaponEventMechanism;
    WeaponEventBase _abt_ = new WeaponEventHumanCommandActionAborted;
    WeaponEventBase _rto_ = new WeaponEventReloadTimeout;
    WeaponEventBase _dto_ = new WeaponEventDryFireTimeout;
    m_fsm = new WeaponFSM();
    // Mechanism
    //----------------------------------------
    m_fsm.AddTransition(new WeaponTransition(D0, __M__, Mech_DF));
    m_fsm.AddTransition(new WeaponTransition(C0, __M__, Mech_C1));
    m_fsm.AddTransition(new WeaponTransition(C1, __M__, Mech_C1));
    m_fsm.AddTransition(new WeaponTransition(Mech_C1, _fin_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C1, _fin_, C1));
    m_fsm.AddTransition(new WeaponTransition(Mech_C1, _abt_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C1, _abt_, C1));
    m_fsm.AddTransition(new WeaponTransition(DF, __M__, Mech_DF));
    m_fsm.AddTransition(new WeaponTransition(Mech_DF, _fin_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_DF, _fin_, DF, NULL, new WeaponGuardCurrentChamberFiredOut(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_DF, _fin_, C1));
    m_fsm.AddTransition(new WeaponTransition(Mech_DF, _abt_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_DF, _abt_, DF, NULL, new WeaponGuardCurrentChamberFiredOut(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_DF, _abt_, C1));
    //----------------------------------------
    m_fsm.AddTransition(new WeaponTransition(C0, __L__, Chamber_D0));
    m_fsm.AddTransition(new WeaponTransition(D0, __L__, Chamber_D0));
    m_fsm.AddTransition(new WeaponTransition(Chamber_D0, _fin_, C1));
    m_fsm.AddTransition(new WeaponTransition(Chamber_D0, _abt_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_D0, _abt_, C1));
    m_fsm.AddTransition(new WeaponTransition(C1, __L__, Chamber_C1, NULL, new GuardNot(new WeaponGuardInnerMagazineFull(this))));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C1, _fin_, C1));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C1, _abt_, C1));
    m_fsm.AddTransition(new WeaponTransition(DF, __L__, Chamber_DF, NULL, new GuardNot(new WeaponGuardInnerMagazineFull(this))));
    m_fsm.AddTransition(new WeaponTransition(Chamber_DF, _fin_, C1));
    m_fsm.AddTransition(new WeaponTransition(Chamber_DF, _abt_, DF, NULL, new WeaponGuardCurrentChamberFiredOut(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_DF, _abt_, C1));
    //------------------------------------------
    m_fsm.AddTransition(new WeaponTransition(JF, __U__, Unjam_JF));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF, _fin_, JF, NULL, new WeaponGuardJammed(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF, _fin_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF, _fin_, C1));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF, _abt_, JF, NULL, new WeaponGuardJammed(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF, _abt_, C0, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF, _abt_, C1));
    //-----------------------------------------
    // fire
    m_fsm.AddTransition(new WeaponTransition(D0, __T__, Trigger_D0)); // fire.cocked
    m_fsm.AddTransition(new WeaponTransition(Trigger_D0, _fin_, D0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_D0, _dto_, D0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_D0, _abt_, D0));
    m_fsm.AddTransition(new WeaponTransition(C0, __T__, Trigger_C0)); // fire.cocked
    m_fsm.AddTransition(new WeaponTransition(Trigger_C0, _fin_, D0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C0, _dto_, D0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C0, _abt_, D0));
    m_fsm.AddTransition(new WeaponTransition(C1, __T__, Trigger_C1)); // fire.cocked
    m_fsm.AddTransition(new WeaponTransition(Trigger_C1, _fin_, DF));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C1, _rto_, DF));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C1, _abt_, DF));
    m_fsm.AddTransition(new WeaponTransition(DF, __T__, Trigger_DF)); // fire.cocked
    m_fsm.AddTransition(new WeaponTransition(Trigger_DF, _fin_, DF));
    m_fsm.AddTransition(new WeaponTransition(Trigger_DF, _dto_, DF));
    m_fsm.AddTransition(new WeaponTransition(Trigger_DF, _abt_, DF));
    m_fsm.AddTransition(new WeaponTransition(JF, __T__, Trigger_JF)); // fire.cocked
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF, _fin_, JF));
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF, _dto_, JF));
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF, _abt_, JF));
    m_fsm.AddTransition(new WeaponTransition(JF, __TJ_, Trigger_C1J)); // fire.cocked
    m_fsm.AddTransition(new WeaponTransition(Trigger_C1J, _fin_, JF));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C1J, _rto_, JF));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C1J, _abt_, JF));
    //---------------------------------------------
    SetInitialState(D0);
    SelectionBulletHide();
    HideMagazine();
    m_fsm.Start();
  }
InitStateMachine() [3/5]
override void Rifle_Base::InitStateMachine () inline private
Definition at line 106 of file RifleBoltFree_Base.c.
  {
    m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_BULLET)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_NOMAGAZINE_BULLET)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_NOBULLET)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_NOMAGAZINE_NOBULLET)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_DETACH)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, GetWeaponSpecificCommand(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_CLOSED)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, GetWeaponSpecificCommand(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, GetWeaponSpecificCommand(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_END)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_JAM)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY)));
    // setup state machine
    // basic weapon states
    // close-locked-jammed | nobullet-bullet | nomag-mag
    // regexp: [CLJ][01][01]
    C00 = new RBF_CLO_BU0_MA0(this, NULL, RBLAnimState.DEFAULT);
    C10 = new RBF_CLO_BU1_MA0(this, NULL, RBLAnimState.DEFAULT);
    C11 = new RBF_CLO_BU1_MA1(this, NULL, RBLAnimState.DEFAULT);
    C01 = new RBF_CLO_BU0_MA1(this, NULL, RBLAnimState.DEFAULT);
    JF0 = new RBF_JAM_BU1_MA0(this, NULL, RBLAnimState.JAMMED);
    JF1 = new RBF_JAM_BU1_MA1(this, NULL, RBLAnimState.JAMMED);
    // unstable (intermediate) states
    WeaponCharging Mech_C00 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
    WeaponCharging Mech_C01 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
    WeaponCharging Mech_C10 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
    WeaponCharging Mech_C11 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
    WeaponStateBase Trigger_C00 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY)); // cock without clip
    WeaponStateBase Trigger_C10 = new WeaponFireLast(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL)); // cock with clip
    WeaponFireAndChamberNext Trigger_C11 = new WeaponFireAndChamberNext(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL));
    WeaponStateBase Trigger_C11L = new WeaponFireLast(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL));
    WeaponStateBase Trigger_C01 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY));
    WeaponStateBase Trigger_JF0 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY));
    WeaponStateBase Trigger_JF1 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY));
    //Fire and jammed
    WeaponStateBase Trigger_C10J = new WeaponFireToJam(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_JAM)); // cock with clip
    WeaponStateBase Trigger_C11J = new WeaponFireToJam(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_JAM));
    // Unjam
    WeaponStateBase Unjam_JF0 = new WeaponUnjamming(this, NULL, WeaponActions.UNJAMMING, GetWeaponSpecificCommand(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START));
    WeaponStateBase Unjam_JF1 = new WeaponUnjamming(this, NULL, WeaponActions.UNJAMMING, GetWeaponSpecificCommand(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START));
    WeaponChambering Chamber_C00 = new WeaponChambering(this, NULL, WeaponActions.CHAMBERING, GetWeaponSpecificCommand(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_CLOSED));
    WeaponChambering Chamber_C01 = new WeaponChambering(this, NULL, WeaponActions.CHAMBERING, GetWeaponSpecificCommand(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_CLOSED));
    WeaponAttachMagazine Attach_C00 = new WeaponAttachMagazine(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_NOMAGAZINE_NOBULLET));
    WeaponAttachMagazine Attach_C10 = new WeaponAttachMagazine(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_NOMAGAZINE_BULLET));
    WeaponAttachMagazine Attach_JF0 = new WeaponAttachMagazine(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_NOMAGAZINE_BULLET));
    WeaponReplacingMagAndChamberNext Reload_C11 = new WeaponReplacingMagAndChamberNext(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_BULLET));
    WeaponReplacingMagAndChamberNext Reload_C01 = new WeaponReplacingMagAndChamberNext(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_NOBULLET));
    WeaponReplacingMagAndChamberNext Reload_JF1 = new WeaponReplacingMagAndChamberNext(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_BULLET));
    WeaponDetachingMag Detach_C11 = new WeaponDetachingMag(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_DETACH));
    WeaponDetachingMag Detach_C01 = new WeaponDetachingMag(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_DETACH));
    WeaponDetachingMag Detach_JF1 = new WeaponDetachingMag(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_DETACH));
    // events
    WeaponEventBase __M__ = new WeaponEventMechanism;
    WeaponEventBase __T__ = new WeaponEventTrigger;
    WeaponEventBase __TJ_ = new WeaponEventTriggerToJam;
    WeaponEventBase __U__ = new WeaponEventUnjam;
    WeaponEventBase __L__ = new WeaponEventLoad1Bullet;
    WeaponEventBase __A__ = new WeaponEventAttachMagazine;
    WeaponEventBase __D__ = new WeaponEventDetachMagazine;
    WeaponEventBase __S__ = new WeaponEventSwapMagazine;
    WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
    WeaponEventBase _abt_ = new WeaponEventHumanCommandActionAborted;
    WeaponEventBase _rto_ = new WeaponEventReloadTimeout;
    WeaponEventBase _dto_ = new WeaponEventDryFireTimeout;
    m_fsm = new WeaponFSM();
    // order: Discharged-Charged | nobullet-bullet | nomag-mag
    // charging
    m_fsm.AddTransition(new WeaponTransition(C00, __M__, Mech_C00)); // charge from dischg nobullet nomag
    m_fsm.AddTransition(new WeaponTransition(Mech_C00, _fin_, C00));
    m_fsm.AddTransition(new WeaponTransition(Mech_C00, _abt_, C00));
    m_fsm.AddTransition(new WeaponTransition(C10, __M__, Mech_C10)); // charge from bullet nomag
    m_fsm.AddTransition(new WeaponTransition(Mech_C10, _fin_, C00, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C10, _fin_, C10));
    m_fsm.AddTransition(new WeaponTransition(Mech_C10, _abt_, C00, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C10, _abt_, C10));
    m_fsm.AddTransition(new WeaponTransition(C11, __M__, Mech_C11)); // charge from dischg nobullet nomag
    m_fsm.AddTransition(new WeaponTransition(Mech_C11, _fin_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C11, _fin_, C11));
    m_fsm.AddTransition(new WeaponTransition(Mech_C11, _abt_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C11, _abt_, C11));
    m_fsm.AddTransition(new WeaponTransition(C01, __M__, Mech_C01)); // charge from dischg nobullet nomag
    m_fsm.AddTransition(new WeaponTransition(Mech_C01, _fin_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C01, _fin_, C11));
    m_fsm.AddTransition(new WeaponTransition(Mech_C01, _abt_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C01, _abt_, C11));
    // fire
    m_fsm.AddTransition(new WeaponTransition(C00, __T__, Trigger_C00));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C00, _fin_, C00));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C00, _dto_, C00));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C00, _abt_, C00));
    m_fsm.AddTransition(new WeaponTransition(C01, __T__, Trigger_C01));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C01, _fin_, C01));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C01, _dto_, C01));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C01, _abt_, C01));
    m_fsm.AddTransition(new WeaponTransition(C10, __T__, Trigger_C10));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C10, _fin_, C00));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C10, _rto_, C00));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C10, _abt_, C00));
    m_fsm.AddTransition(new WeaponTransition(JF1, __T__, Trigger_JF1));
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF1, _fin_, JF1));
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF1, _rto_, JF1));
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF1, _abt_, JF1));
    m_fsm.AddTransition(new WeaponTransition(JF0, __T__, Trigger_JF0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF0, _fin_, JF0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF0, _rto_, JF0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF0, _abt_, JF0));
    m_fsm.AddTransition(new WeaponTransition(C11, __T__, Trigger_C11, NULL, new WeaponGuardHasAmmo(this)));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11, _fin_, C11));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11, _rto_, C11));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11, _abt_, C11));
    m_fsm.AddTransition(new WeaponTransition(C11, __T__, Trigger_C11L));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11L, _fin_, C01));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11L, _rto_, C01));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11L, _abt_, C01));
    m_fsm.AddTransition(new WeaponTransition(C11, __TJ_, Trigger_C11J));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11J, _fin_, JF1));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11J, _rto_, JF1));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11J, _abt_, JF1));
    m_fsm.AddTransition(new WeaponTransition(C10, __TJ_, Trigger_C10J));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C10J, _fin_, JF0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C10J, _rto_, JF0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C10J, _abt_, JF0));
    // load cartridge
    m_fsm.AddTransition(new WeaponTransition(C00, __L__, Chamber_C00)); // chamber from closed=1
    m_fsm.AddTransition(new WeaponTransition(Chamber_C00, _fin_, C00, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C00, _fin_, C10));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C00, _abt_, C00, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C00, _abt_, C10));
    m_fsm.AddTransition(new WeaponTransition(C01, __L__, Chamber_C01)); // chamber from closed charged
    m_fsm.AddTransition(new WeaponTransition(Chamber_C01, _fin_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C01, _fin_, C11));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C01, _abt_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C01, _abt_, C11));
    // attach magazine (no mag in weapon)
    m_fsm.AddTransition(new WeaponTransition(C00, __A__, Attach_C00, NULL, new WeaponGuardCanAttachMag(this))); // attach from CLO/b0/m0
    m_fsm.AddTransition(new WeaponTransition(Attach_C00, _fin_, C11, NULL, new WeaponGuardCurrentChamberFull(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_C00, _fin_, C01, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_C00, _fin_, C00));
    m_fsm.AddTransition(new WeaponTransition(Attach_C00, _abt_, C11, NULL, new WeaponGuardCurrentChamberFull(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_C00, _abt_, C01, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_C00, _abt_, C00));
    m_fsm.AddTransition(new WeaponTransition(C10, __A__, Attach_C10, NULL, new WeaponGuardCanAttachMag(this))); // attach from CLO/b1/m0
    m_fsm.AddTransition(new WeaponTransition(Attach_C10, _fin_, C11, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_C10, _fin_, C10));
    m_fsm.AddTransition(new WeaponTransition(Attach_C10, _abt_, C11, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_C10, _abt_, C10));
    m_fsm.AddTransition(new WeaponTransition(JF0, __A__, Attach_JF0, NULL, new WeaponGuardCanAttachMag(this))); // attach from JAM/b1/m0
    m_fsm.AddTransition(new WeaponTransition(Attach_JF0, _fin_, JF1, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_JF0, _fin_, JF0));
    m_fsm.AddTransition(new WeaponTransition(Attach_JF0, _abt_, JF1, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_JF0, _abt_, JF0));
    // replace magazine
    m_fsm.AddTransition(new WeaponTransition(C11, __S__, Reload_C11, NULL, new WeaponGuardCanSwapMag(this))); // swap in Chg/b1/m1
    m_fsm.AddTransition(new WeaponTransition(Reload_C11, _fin_, C11, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_C11, _fin_, C10));
    m_fsm.AddTransition(new WeaponTransition(Reload_C11, _abt_, C11, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_C11, _abt_, C10));
    m_fsm.AddTransition(new WeaponTransition(C01, __S__, Reload_C01, NULL, new WeaponGuardCanSwapMag(this))); // swap in CLO/b0/m1
    m_fsm.AddTransition(new WeaponTransition(Reload_C01, _fin_, C11, NULL, new WeaponGuardCurrentChamberFull(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_C01, _fin_, C01, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_C01, _fin_, C00));
    m_fsm.AddTransition(new WeaponTransition(Reload_C01, _abt_, C11, NULL, new WeaponGuardCurrentChamberFull(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_C01, _abt_, C01, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_C01, _abt_, C00));
    m_fsm.AddTransition(new WeaponTransition(JF1, __S__, Reload_JF1, NULL, new WeaponGuardCanSwapMag(this))); // swap in Chg/b1/m1
    m_fsm.AddTransition(new WeaponTransition(Reload_JF1, _fin_, JF1, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_JF1, _fin_, JF0));
    m_fsm.AddTransition(new WeaponTransition(Reload_JF1, _abt_, JF1, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_JF1, _abt_, JF0));
    // detach magazine
    m_fsm.AddTransition(new WeaponTransition(C11, __D__, Detach_C11, NULL, new WeaponGuardCanDetachMag(this))); // detach from Chg/b1/m1
    m_fsm.AddTransition(new WeaponTransition(Detach_C11, _fin_, C11, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Detach_C11, _fin_, C10));
    m_fsm.AddTransition(new WeaponTransition(Detach_C11, _abt_, C11, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Detach_C11, _abt_, C10));
    m_fsm.AddTransition(new WeaponTransition(C01, __D__, Detach_C01, NULL, new WeaponGuardCanDetachMag(this))); // detach from Chg/b0/m1
    m_fsm.AddTransition(new WeaponTransition(Detach_C01, _fin_, C01, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Detach_C01, _fin_, C00));
    m_fsm.AddTransition(new WeaponTransition(Detach_C01, _abt_, C01, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Detach_C01, _abt_, C00));
    m_fsm.AddTransition(new WeaponTransition(JF1, __D__, Detach_JF1, NULL, new WeaponGuardCanDetachMag(this))); // detach from CLO/b1/m1 jammed
    m_fsm.AddTransition(new WeaponTransition(Detach_JF1, _fin_, JF1, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Detach_JF1, _fin_, JF0));
    m_fsm.AddTransition(new WeaponTransition(Detach_JF1, _abt_, JF1, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Detach_JF1, _abt_, JF0));
    // unjam
    m_fsm.AddTransition(new WeaponTransition(JF0, __U__, Unjam_JF0)); // unjam nomag
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF0, _fin_, JF0, NULL, new WeaponGuardJammed(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF0, _fin_, C00));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF0, _abt_, JF0, NULL, new WeaponGuardJammed(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF0, _abt_, C00));
    m_fsm.AddTransition(new WeaponTransition(JF1, __U__, Unjam_JF1)); // unjam with mag with ammo
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF1, _fin_, JF1, NULL, new WeaponGuardJammed(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF1, _fin_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF1, _fin_, C11));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF1, _abt_, JF1, NULL, new WeaponGuardJammed(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF1, _abt_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF1, _abt_, C11));
    SetInitialState(C00);
    SelectionBulletHide();
    HideMagazine();
    m_fsm.Start();
  }
References RBF_CLO_BU0_MA0, RBF_CLO_BU0_MA1, RBF_CLO_BU1_MA0, RBF_CLO_BU1_MA1, RBF_JAM_BU1_MA0, RBF_JAM_BU1_MA1, and WeaponGuardHasAmmo().
InitStateMachine() [4/5]
override void Rifle_Base::InitStateMachine () inline private
Definition at line 134 of file RifleBoltLock_Base.c.
  {
    m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_BULLET)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_NOMAGAZINE_BULLET)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_NOBULLET)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_NOMAGAZINE_NOBULLET)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_NOMAGAZINE_NOBULLET_OPEN)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_NOBULLET_OPEN)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_DETACH)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, GetWeaponSpecificCommand(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_CLOSED)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, GetWeaponSpecificCommand(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_UNIQUE_CLOSED)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_OPENED)));//????
    m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, GetWeaponSpecificCommand(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, GetWeaponSpecificCommand(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_END)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_LAST)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_JAM)));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY)));
    //m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_UNCOCKED));
    // setup state machine
    // basic weapon states
    // close-locked-jammed | nobullet-bullet | nomag-mag
    // regexp: [CLJ][01][01]
    C00 = new RBL_CLO_BU0_MA0(this, NULL, RBLAnimState.DEFAULT);
    C10 = new RBL_CLO_BU1_MA0(this, NULL, RBLAnimState.DEFAULT);
    C11 = new RBL_CLO_BU1_MA1(this, NULL, RBLAnimState.DEFAULT);
    C01 = new RBL_CLO_BU0_MA1(this, NULL, RBLAnimState.DEFAULT);
    O00 = new RBL_OPN_BU0_MA0(this, NULL, RBLAnimState.OPENED);
    O01 = new RBL_OPN_BU0_MA1(this, NULL, RBLAnimState.OPENED);
    JF0 = new RBL_JAM_BU1_MA0(this, NULL, RBLAnimState.JAMMED);
    JF1 = new RBL_JAM_BU1_MA1(this, NULL, RBLAnimState.JAMMED);
    // unstable (intermediate) states
    WeaponCharging Mech_C00 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
    WeaponCharging Mech_C01 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
    WeaponCharging Mech_O00 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_OPENED));
    WeaponCharging Mech_O01 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_OPENED));
    WeaponCharging Mech_C10 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
    WeaponCharging Mech_C11 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, GetWeaponSpecificCommand(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
    WeaponStateBase Trigger_C00 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY)); // cock without clip
    WeaponStateBase Trigger_C10 = new WeaponFireLast(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL)); // cock with clip
    WeaponFireAndChamberNext Trigger_C11 = new WeaponFireAndChamberNext(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL));
    WeaponStateBase Trigger_C11L = new WeaponFireLast(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_LAST));
    WeaponStateBase Trigger_C01 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY));
    WeaponStateBase Trigger_O00 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY));
    WeaponStateBase Trigger_O01 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY));
    WeaponStateBase Trigger_JF0 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY));
    WeaponStateBase Trigger_JF1 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY));
    //Fire and jam
    WeaponStateBase Trigger_C10J = new WeaponFireToJam(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_JAM)); // cock with clip
    WeaponStateBase Trigger_C11J = new WeaponFireToJam(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_JAM));
    // WeaponStateBase Trigger_C11J = new WeaponFire(this, NULL, WeaponActions.FIRE, GetWeaponSpecificCommand(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_JAM));
    WeaponStateBase Unjam_JF0 = new WeaponUnjamming(this, NULL, WeaponActions.UNJAMMING, GetWeaponSpecificCommand(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START));
    WeaponStateBase Unjam_JF1 = new WeaponUnjamming(this, NULL, WeaponActions.UNJAMMING, GetWeaponSpecificCommand(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START));
    WeaponChambering Chamber_C00 = new WeaponChambering(this, NULL, WeaponActions.CHAMBERING, GetWeaponSpecificCommand(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_CLOSED));
    WeaponChambering Chamber_C01 = new WeaponChambering(this, NULL, WeaponActions.CHAMBERING, GetWeaponSpecificCommand(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_CLOSED));
    WeaponChambering Chamber_O00 = new WeaponChambering(this, NULL, WeaponActions.CHAMBERING, GetWeaponSpecificCommand(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_UNIQUE_CLOSED));
    WeaponChambering Chamber_O01 = new WeaponChambering(this, NULL, WeaponActions.CHAMBERING, GetWeaponSpecificCommand(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_UNIQUE_CLOSED));
    WeaponAttachMagazine Attach_C00 = new WeaponAttachMagazine(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_NOMAGAZINE_NOBULLET));
    WeaponAttachMagazine Attach_C10 = new WeaponAttachMagazine(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_NOMAGAZINE_BULLET));
    WeaponAttachMagazine Attach_O00 = new WeaponAttachMagazine(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_NOMAGAZINE_NOBULLET_OPEN));//TODO Need add open animation
    WeaponAttachMagazine Attach_JF0 = new WeaponAttachMagazine(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_NOMAGAZINE_BULLET));
    WeaponReplacingMagAndChamberNext Reload_C11 = new WeaponReplacingMagAndChamberNext(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_BULLET));
    WeaponReplacingMagAndChamberNext Reload_C01 = new WeaponReplacingMagAndChamberNext(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_NOBULLET));
    WeaponReplacingMagAndChamberNext Reload_O01 = new WeaponReplacingMagAndChamberNext(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_NOBULLET_OPEN));//TODO Need add open animation
    WeaponReplacingMagAndChamberNext Reload_JF1 = new WeaponReplacingMagAndChamberNext(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_BULLET));
    WeaponDetachingMag Detach_C11 = new WeaponDetachingMag(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_DETACH));
    WeaponDetachingMag Detach_C01 = new WeaponDetachingMag(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_DETACH));
    WeaponDetachingMag Detach_O01 = new WeaponDetachingMag(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_DETACH));
    WeaponDetachingMag Detach_JF1 = new WeaponDetachingMag(this, NULL, WeaponActions.RELOAD, GetWeaponSpecificCommand(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADRIFLE_MAGAZINE_DETACH));
    //WeaponStateBase chmMag = new WeaponChamberFromAttMag(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED);
    // events
    WeaponEventBase __M__ = new WeaponEventMechanism;
    WeaponEventBase __T__ = new WeaponEventTrigger;
    WeaponEventBase __TJ_ = new WeaponEventTriggerToJam;
    WeaponEventBase __U__ = new WeaponEventUnjam;
    WeaponEventBase __L__ = new WeaponEventLoad1Bullet;
    WeaponEventBase __A__ = new WeaponEventAttachMagazine;
    WeaponEventBase __D__ = new WeaponEventDetachMagazine;
    WeaponEventBase __S__ = new WeaponEventSwapMagazine;
    WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
    WeaponEventBase _abt_ = new WeaponEventHumanCommandActionAborted;
    WeaponEventBase _rto_ = new WeaponEventReloadTimeout;
    WeaponEventBase _dto_ = new WeaponEventDryFireTimeout;
    m_fsm = new WeaponFSM();
    // order: Discharged-Charged | nobullet-bullet | nomag-mag
    // charging
    m_fsm.AddTransition(new WeaponTransition(C00, __M__, Mech_C00)); // charge from dischg nobullet nomag
    m_fsm.AddTransition(new WeaponTransition(Mech_C00, _fin_, C00));
    m_fsm.AddTransition(new WeaponTransition(Mech_C00, _abt_, C00));
    m_fsm.AddTransition(new WeaponTransition(C10, __M__, Mech_C10)); // charge from bullet nomag
    m_fsm.AddTransition(new WeaponTransition(Mech_C10, _fin_, C00, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C10, _fin_, C10));
    m_fsm.AddTransition(new WeaponTransition(Mech_C10, _abt_, C00, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C10, _abt_, C10));
    m_fsm.AddTransition(new WeaponTransition(C11, __M__, Mech_C11)); // charge from dischg nobullet nomag
    m_fsm.AddTransition(new WeaponTransition(Mech_C11, _fin_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C11, _fin_, C11));
    m_fsm.AddTransition(new WeaponTransition(Mech_C11, _abt_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C11, _abt_, C11));
    m_fsm.AddTransition(new WeaponTransition(C01, __M__, Mech_C01)); // charge from dischg nobullet nomag
    m_fsm.AddTransition(new WeaponTransition(Mech_C01, _fin_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C01, _fin_, C11));
    m_fsm.AddTransition(new WeaponTransition(Mech_C01, _abt_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_C01, _abt_, C11));
    m_fsm.AddTransition(new WeaponTransition(O00, __M__, Mech_O00)); // charge from dischg nobullet nomag
    m_fsm.AddTransition(new WeaponTransition(Mech_O00, _fin_, O00, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_O00, _fin_, C00));
    m_fsm.AddTransition(new WeaponTransition(Mech_O00, _abt_, O00, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_O00, _abt_, C00));
    m_fsm.AddTransition(new WeaponTransition(O01, __M__, Mech_O01)); // charge from dischg nobullet nomag
    m_fsm.AddTransition(new WeaponTransition(Mech_O01, _fin_, O01, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_O01, _fin_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_O01, _fin_, C11));
    m_fsm.AddTransition(new WeaponTransition(Mech_O01, _abt_, O01, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_O01, _abt_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_O01, _abt_, C11));
    // fire
    m_fsm.AddTransition(new WeaponTransition(C00, __T__, Trigger_C00));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C00, _fin_, C00));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C00, _dto_, C00));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C00, _abt_, C00));
    m_fsm.AddTransition(new WeaponTransition(C01, __T__, Trigger_C01));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C01, _fin_, C01));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C01, _dto_, C01));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C01, _abt_, C01));
    m_fsm.AddTransition(new WeaponTransition(C10, __T__, Trigger_C10));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C10, _fin_, C00));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C10, _rto_, C00));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C10, _abt_, C00));
    m_fsm.AddTransition(new WeaponTransition(C11, __T__, Trigger_C11, NULL, new WeaponGuardHasAmmo(this)));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11, _fin_, C11));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11, _rto_, C11));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11, _abt_, C11));
    m_fsm.AddTransition(new WeaponTransition(C11, __T__, Trigger_C11L));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11L, _fin_, O01));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11L, _rto_, O01));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11L, _abt_, O01));
    m_fsm.AddTransition(new WeaponTransition(O00, __T__, Trigger_O00));
    m_fsm.AddTransition(new WeaponTransition(Trigger_O00, _fin_, O00));
    m_fsm.AddTransition(new WeaponTransition(Trigger_O00, _dto_, O00));
    m_fsm.AddTransition(new WeaponTransition(Trigger_O00, _abt_, O00));
    m_fsm.AddTransition(new WeaponTransition(O01, __T__, Trigger_O01));
    m_fsm.AddTransition(new WeaponTransition(Trigger_O01, _fin_, O01));
    m_fsm.AddTransition(new WeaponTransition(Trigger_O01, _dto_, O01));
    m_fsm.AddTransition(new WeaponTransition(Trigger_O01, _abt_, O01));
    m_fsm.AddTransition(new WeaponTransition(JF0, __T__, Trigger_JF0)); // opened fire.uncocked w mag
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF0, _fin_, JF0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF0, _dto_, JF0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF0, _abt_, JF0));
    m_fsm.AddTransition(new WeaponTransition(JF1, __T__, Trigger_JF1)); // opened fire.uncocked w mag
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF1, _fin_, JF1));
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF1, _dto_, JF1));
    m_fsm.AddTransition(new WeaponTransition(Trigger_JF1, _abt_, JF1));
    m_fsm.AddTransition(new WeaponTransition(C10, __TJ_, Trigger_C10J));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C10J, _fin_, JF0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C10J, _rto_, JF0));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C10J, _abt_, JF0));
    m_fsm.AddTransition(new WeaponTransition(C11, __TJ_, Trigger_C11J));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11J, _fin_, JF1));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11J, _rto_, JF1));
    m_fsm.AddTransition(new WeaponTransition(Trigger_C11J, _abt_, JF1));
    // load cartridge
    m_fsm.AddTransition(new WeaponTransition(C00, __L__, Chamber_C00)); // chamber from closed=1
    m_fsm.AddTransition(new WeaponTransition(Chamber_C00, _fin_, O00, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C00, _fin_, C00, NULL, new WeaponGuardChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C00, _fin_, C10));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C00, _abt_, O00, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C00, _abt_, C00, NULL, new WeaponGuardChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C00, _abt_, C10));
    m_fsm.AddTransition(new WeaponTransition(C01, __L__, Chamber_C01)); // chamber from closed charged
    m_fsm.AddTransition(new WeaponTransition(Chamber_C01, _fin_, O01, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C01, _fin_, C01, NULL, new WeaponGuardChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C01, _fin_, C11));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C01, _abt_, O01, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C01, _abt_, C01, NULL, new WeaponGuardChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_C01, _abt_, C11));
    m_fsm.AddTransition(new WeaponTransition(O00, __L__, Chamber_O00)); // chamber from closed charged
    m_fsm.AddTransition(new WeaponTransition(Chamber_O00, _fin_, O00, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_O00, _fin_, C10));
    m_fsm.AddTransition(new WeaponTransition(Chamber_O00, _abt_, O00, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_O00, _abt_, C10));
    m_fsm.AddTransition(new WeaponTransition(O01, __L__, Chamber_O01)); // chamber from closed charged
    m_fsm.AddTransition(new WeaponTransition(Chamber_O01, _fin_, O01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_O01, _fin_, C11));
    m_fsm.AddTransition(new WeaponTransition(Chamber_O01, _abt_, O01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_O01, _abt_, C11));
    // attach magazine (no mag in weapon)
    m_fsm.AddTransition(new WeaponTransition(C00, __A__, Attach_C00, NULL, new WeaponGuardCanAttachMag(this))); // attach from CLO/b0/m0
    m_fsm.AddTransition(new WeaponTransition(Attach_C00, _fin_, C00, NULL, new GuardNot(new WeaponGuardHasMag(this))));
    m_fsm.AddTransition(new WeaponTransition(Attach_C00, _fin_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_C00, _fin_, C11));
    m_fsm.AddTransition(new WeaponTransition(Attach_C00, _abt_, C00, NULL, new GuardNot(new WeaponGuardHasMag(this))));
    m_fsm.AddTransition(new WeaponTransition(Attach_C00, _abt_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_C00, _abt_, C11));
    m_fsm.AddTransition(new WeaponTransition(C10, __A__, Attach_C10, NULL, new WeaponGuardCanAttachMag(this))); // attach from CLO/b1/m0
    m_fsm.AddTransition(new WeaponTransition(Attach_C10, _fin_, C11, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_C10, _fin_, C10));
    m_fsm.AddTransition(new WeaponTransition(Attach_C10, _abt_, C11, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_C10, _abt_, C10));
    m_fsm.AddTransition(new WeaponTransition(O00, __A__, Attach_O00, NULL, new WeaponGuardCanAttachMag(this))); // attach from CLO/b0/m0
    m_fsm.AddTransition(new WeaponTransition(Attach_O00, _fin_, O00, NULL, new GuardNot(new WeaponGuardHasMag(this))));
    m_fsm.AddTransition(new WeaponTransition(Attach_O00, _fin_, O01, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_O00, _fin_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_O00, _fin_, C11));
    m_fsm.AddTransition(new WeaponTransition(Attach_O00, _abt_, O00, NULL, new GuardNot(new WeaponGuardHasMag(this))));
    m_fsm.AddTransition(new WeaponTransition(Attach_O00, _abt_, O01, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_O00, _abt_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_O00, _abt_, C11));
    m_fsm.AddTransition(new WeaponTransition(JF0, __A__, Attach_JF0, NULL, new WeaponGuardCanAttachMag(this))); // attach from JAM/b1/m0
    m_fsm.AddTransition(new WeaponTransition(Attach_JF0, _fin_, JF1, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_JF0, _fin_, JF0));
    m_fsm.AddTransition(new WeaponTransition(Attach_JF0, _abt_, JF1, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Attach_JF0, _abt_, JF0));
    // replace magazine
    m_fsm.AddTransition(new WeaponTransition(C11, __S__, Reload_C11, NULL, new WeaponGuardCanSwapMag(this))); // swap in Chg/b1/m1
    m_fsm.AddTransition(new WeaponTransition(Reload_C11, _fin_, C11, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_C11, _fin_, C10));
    m_fsm.AddTransition(new WeaponTransition(Reload_C11, _abt_, C11, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_C11, _abt_, C10));
    m_fsm.AddTransition(new WeaponTransition(C01, __S__, Reload_C01, NULL, new WeaponGuardCanSwapMag(this))); // swap in CLO/b0/m1
    m_fsm.AddTransition(new WeaponTransition(Reload_C01, _fin_, C11, NULL, new WeaponGuardCurrentChamberFull(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_C01, _fin_, C01, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_C01, _fin_, C00));
    m_fsm.AddTransition(new WeaponTransition(Reload_C01, _abt_, C11, NULL, new WeaponGuardCurrentChamberFull(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_C01, _abt_, C01, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_C01, _abt_, C00));
    m_fsm.AddTransition(new WeaponTransition(O01, __S__, Reload_O01, NULL, new WeaponGuardCanSwapMag(this))); // swap in CLO/b0/m1
    m_fsm.AddTransition(new WeaponTransition(Reload_O01, _fin_, O00, NULL, new GuardNot(new WeaponGuardHasMag(this))));
    m_fsm.AddTransition(new WeaponTransition(Reload_O01, _fin_, O01, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_O01, _fin_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_O01, _fin_, C11));
    m_fsm.AddTransition(new WeaponTransition(Reload_O01, _abt_, O00, NULL, new GuardNot(new WeaponGuardHasMag(this))));
    m_fsm.AddTransition(new WeaponTransition(Reload_O01, _abt_, O01, NULL, new WeaponGuardWeaponOpen(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_O01, _abt_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_O01, _abt_, C11));
    m_fsm.AddTransition(new WeaponTransition(JF1, __S__, Reload_JF1, NULL, new WeaponGuardCanSwapMag(this))); // swap in JAM/b1/m1
    m_fsm.AddTransition(new WeaponTransition(Reload_JF1, _fin_, JF1, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_JF1, _fin_, JF0));
    m_fsm.AddTransition(new WeaponTransition(Reload_JF1, _abt_, JF1, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Reload_JF1, _abt_, JF0));
    // @TODO: abort in jam
    // detach magazine
    m_fsm.AddTransition(new WeaponTransition(C11, __D__, Detach_C11, NULL, new WeaponGuardCanDetachMag(this))); // detach from Chg/b1/m1
    m_fsm.AddTransition(new WeaponTransition(Detach_C11, _fin_, C11, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Detach_C11, _fin_, C10));
    m_fsm.AddTransition(new WeaponTransition(Detach_C11, _abt_, C11, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Detach_C11, _abt_, C10));
    m_fsm.AddTransition(new WeaponTransition(C01, __D__, Detach_C01, NULL, new WeaponGuardCanDetachMag(this))); // detach from Chg/b0/m1
    m_fsm.AddTransition(new WeaponTransition(Detach_C01, _fin_, C01, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Detach_C01, _fin_, C00));
    m_fsm.AddTransition(new WeaponTransition(Detach_C01, _abt_, C01, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Detach_C01, _abt_, C00));
    m_fsm.AddTransition(new WeaponTransition(O01, __D__, Detach_O01, NULL, new WeaponGuardCanDetachMag(this))); // detach from Dic/b0/m1
    m_fsm.AddTransition(new WeaponTransition(Detach_O01, _fin_, O01, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Detach_O01, _fin_, O00));
    m_fsm.AddTransition(new WeaponTransition(Detach_O01, _abt_, O01, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Detach_O01, _abt_, O00));
    m_fsm.AddTransition(new WeaponTransition(JF1, __D__, Detach_JF1, NULL, new WeaponGuardCanDetachMag(this))); // detach from CLO/b1/m1 jammed
    m_fsm.AddTransition(new WeaponTransition(Detach_JF1, _fin_, JF1, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Detach_JF1, _fin_, JF0));
    m_fsm.AddTransition(new WeaponTransition(Detach_JF1, _abt_, JF1, NULL, new WeaponGuardHasMag(this)));
    m_fsm.AddTransition(new WeaponTransition(Detach_JF1, _abt_, JF0));
    // unjam
    m_fsm.AddTransition(new WeaponTransition(JF0, __U__, Unjam_JF0)); // unjam nomag
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF0, _fin_, JF0, NULL, new WeaponGuardJammed(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF0, _fin_, C00));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF0, _abt_, JF0, NULL, new WeaponGuardJammed(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF0, _abt_, C00));
    m_fsm.AddTransition(new WeaponTransition(JF1, __U__, Unjam_JF1)); // unjam with mag with ammo
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF1, _fin_, JF1, NULL, new WeaponGuardJammed(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF1, _fin_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF1, _fin_, C11));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF1, _abt_, JF1, NULL, new WeaponGuardJammed(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF1, _abt_, C01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_JF1, _abt_, C11));
    SetInitialState(C00);
    SelectionBulletHide();
    HideMagazine();
    m_fsm.Start();
  }
References RBL_CLO_BU0_MA0, RBL_CLO_BU0_MA1, RBL_CLO_BU1_MA0, RBL_CLO_BU1_MA1, RBL_JAM_BU1_MA0, RBL_JAM_BU1_MA1, RBL_OPN_BU0_MA0, RBL_OPN_BU0_MA1, WeaponGuardHasAmmo(), and WeaponGuardWeaponOpen().
InitStateMachine() [5/5]
override void Rifle_Base::InitStateMachine () inline private
Definition at line 71 of file RifleSingleShot_Base.c.
  {
    // setup abilities
    m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
    m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_CLOSED));
    m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START));
    m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_END));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL));
    m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_COCKED));
    // setup state machine
    // basic weapon states
    WeaponStableState E = new RSSEmpty(this, NULL, RSSAnimState.DEFAULT);
    WeaponStableState F = new RSSFireout(this, NULL, RSSAnimState.DEFAULT);
    WeaponStableState J = new RSSJammed(this, NULL, RSSAnimState.DEFAULT);
    WeaponStableState L = new RSSLoaded(this, NULL, RSSAnimState.DEFAULT);
    // unstable (intermediate) states
    WeaponStateBase Mech_F = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED);
    WeaponStateBase Mech_L = new WeaponEjectBullet(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED);
    WeaponChambering Chamber_E = new WeaponChambering(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_CLOSED);
    WeaponChambering Chamber_F = new WeaponChambering(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_CLOSED);
    //WeaponStateBase Chamber_L = new RifleReChambering(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_CLOSED);
    WeaponStateBase Trigger_E = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_COCKED);
    WeaponStateBase Trigger_L = new WeaponFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL);
    WeaponStateBase Trigger_F = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_COCKED);
    WeaponStateBase Trigger_LJ = new WeaponFireToJam(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_JAM);
    WeaponStateBase Unjam_J = new WeaponUnjamming(this, NULL, WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START);
    // events
    WeaponEventBase __M__ = new WeaponEventMechanism;
    WeaponEventBase __T__ = new WeaponEventTrigger;
    WeaponEventBase __TJ_ = new WeaponEventTriggerToJam;
    WeaponEventBase __L__ = new WeaponEventLoad1Bullet;
    WeaponEventBase __U__ = new WeaponEventUnjam;
    WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
    WeaponEventBase _abt_ = new WeaponEventHumanCommandActionAborted;
    WeaponEventBase _dto_ = new WeaponEventDryFireTimeout;
    m_fsm = new WeaponFSM();
    // charging
    m_fsm.AddTransition(new WeaponTransition(E, __M__, Mech_F));
    m_fsm.AddTransition(new WeaponTransition(F, __M__, Mech_F));
    m_fsm.AddTransition(new WeaponTransition(Mech_F, _fin_, F, NULL, new WeaponGuardCurrentChamberFiredOut(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_F, _fin_, E));
    m_fsm.AddTransition(new WeaponTransition(Mech_F, _abt_, F, NULL, new WeaponGuardCurrentChamberFiredOut(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_F, _abt_, E));
    // eject good cartridge
    m_fsm.AddTransition(new WeaponTransition(L, __M__, Mech_L));
    m_fsm.AddTransition(new WeaponTransition(Mech_L, _fin_, E, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_L, _fin_, L));
    m_fsm.AddTransition(new WeaponTransition(Mech_L, _abt_, E, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Mech_L, _abt_, L));
    // load bullet
    m_fsm.AddTransition(new WeaponTransition(E, __L__, Chamber_E));
    m_fsm.AddTransition(new WeaponTransition(Chamber_E, _fin_, E, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_E, _fin_, L));
    m_fsm.AddTransition(new WeaponTransition(Chamber_E, _abt_, E, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_E, _abt_, L));
    m_fsm.AddTransition(new WeaponTransition(F, __L__, Chamber_F));
    m_fsm.AddTransition(new WeaponTransition(Chamber_F, _fin_, F, NULL, new WeaponGuardCurrentChamberFiredOut(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_F, _fin_, E, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_F, _fin_, L));
    m_fsm.AddTransition(new WeaponTransition(Chamber_F, _abt_, F, NULL, new WeaponGuardCurrentChamberFiredOut(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_F, _abt_, E, NULL, new WeaponGuardCurrentChamberEmpty(this)));
    m_fsm.AddTransition(new WeaponTransition(Chamber_F, _abt_, L));
    // fire
    m_fsm.AddTransition(new WeaponTransition(E, __T__, Trigger_E)); // fire cocked
    m_fsm.AddTransition(new WeaponTransition(Trigger_E, _fin_, E));
    m_fsm.AddTransition(new WeaponTransition(Trigger_E, _dto_, E));
    m_fsm.AddTransition(new WeaponTransition(Trigger_E, _abt_, E));
    m_fsm.AddTransition(new WeaponTransition(F, __T__, Trigger_F)); // fire uncocked
    m_fsm.AddTransition(new WeaponTransition(Trigger_F, _fin_, F));
    m_fsm.AddTransition(new WeaponTransition(Trigger_F, _dto_, F));
    m_fsm.AddTransition(new WeaponTransition(Trigger_F, _abt_, F));
    m_fsm.AddTransition(new WeaponTransition(L, __T__, Trigger_L)); // a) fire if not jammed
    m_fsm.AddTransition(new WeaponTransition(Trigger_L, _fin_, F));
    m_fsm.AddTransition(new WeaponTransition(Trigger_L, _abt_, F));
    m_fsm.AddTransition(new WeaponTransition(L, __TJ_, Trigger_LJ)); // a) fire if not jammed
    m_fsm.AddTransition(new WeaponTransition(Trigger_LJ, _fin_, J));
    m_fsm.AddTransition(new WeaponTransition(Trigger_LJ, _abt_, J));
    // unjam
    m_fsm.AddTransition(new WeaponTransition(J, __U__, Unjam_J));
    m_fsm.AddTransition(new WeaponTransition(Unjam_J, _fin_, J, NULL, new WeaponGuardJammed(this)));
    m_fsm.AddTransition(new WeaponTransition(Unjam_J, _fin_, E));
    // initial state setup
    bool empty = true;
    bool discharged = false; // @TODO:
    WeaponStableState init_state = E;
    if (empty)
    {
      if (!discharged)
        init_state = E;
    }
    else
    {
      init_state = L; // can init state == load/jammed?
    }
    SetInitialState(init_state);
    SelectionBulletHide();
    m_fsm.Start();
  }
References E, F, and L.
OnDebugSpawn()
override void Rifle_Base::OnDebugSpawn () inline private
Definition at line 266 of file SKS.c.
  {
    super.OnDebugSpawn();
    GameInventory inventory = GetInventory();
    inventory.CreateInInventory("PUScopeOptic");
    inventory.CreateInInventory("SKS_Bayonet");
  }
RifleBoltFree_Base()
void Rifle_Base::RifleBoltFree_Base () inline private
Definition at line 101 of file RifleBoltFree_Base.c.
  {
  }
RifleBoltLock_Base()
void Rifle_Base::RifleBoltLock_Base () inline private
Definition at line 130 of file RifleBoltLock_Base.c.
  {
  }
RifleSingleShot_Base()
void Rifle_Base::RifleSingleShot_Base () inline private
Definition at line 67 of file RifleSingleShot_Base.c.
  {
  }
SetActions() [1/4]
override void Rifle_Base::SetActions () inline private
Definition at line 256 of file SKS.c.
  {
    super.SetActions();
    AddAction(FirearmActionLoadMultiBullet);
    RemoveAction(FirearmActionLoadBulletQuick); // Easy reload
    AddAction(FirearmActionLoadMultiBulletQuick); // Easy reload
  }
References AddAction(), FirearmActionLoadBulletQuick(), and RemoveAction().
SetActions() [2/4]
override void Rifle_Base::SetActions () inline private
Definition at line 224 of file Repeater.c.
  {
    super.SetActions();
    AddAction(FirearmActionLoadMultiBullet);
    RemoveAction(FirearmActionLoadBulletQuick); // Easy reload
    AddAction(FirearmActionLoadMultiBulletQuick); // Easy reload
  }
References AddAction(), FirearmActionLoadBulletQuick(), and RemoveAction().
SetActions() [3/4]
override void Rifle_Base::SetActions () inline private
Definition at line 377 of file RifleBoltFree_Base.c.
  {
    super.SetActions();
    AddAction(FirearmActionDetachMagazine);
    //AddAction(ActionAdvancedDetachMagazine);
  }
References AddAction().
SetActions() [4/4]
override void Rifle_Base::SetActions () inline private
Definition at line 494 of file RifleBoltLock_Base.c.
  {
    super.SetActions();
    AddAction(FirearmActionDetachMagazine);
    //AddAction(ActionAdvancedDetachMagazine);
  }
References AddAction().
SpawnRecoilObject()
override RecoilBase Rifle_Base::SpawnRecoilObject () inline private
Definition at line 76 of file SKS.c.
  {
    return new SKSRecoil(this);
  }
Member Data Documentation
C0
ref WeaponStableState Rifle_Base::C0 private
Definition at line 71 of file SKS.c.
C00
ref WeaponStableState Rifle_Base::C00 private
Definition at line 94 of file RifleBoltFree_Base.c.
C01
ref WeaponStableState Rifle_Base::C01 private
Definition at line 97 of file RifleBoltFree_Base.c.
C1
ref WeaponStableState Rifle_Base::C1 private
Definition at line 72 of file SKS.c.
C10
ref WeaponStableState Rifle_Base::C10 private
Definition at line 95 of file RifleBoltFree_Base.c.
C11
ref WeaponStableState Rifle_Base::C11 private
Definition at line 96 of file RifleBoltFree_Base.c.
D0
ref WeaponStableState Rifle_Base::D0 private
Definition at line 68 of file Repeater.c.
DF
ref WeaponStableState Rifle_Base::DF private
Definition at line 71 of file Repeater.c.
JF
ref WeaponStableState Rifle_Base::JF private
Definition at line 74 of file SKS.c.
JF0
ref WeaponStableState Rifle_Base::JF0 private
Definition at line 98 of file RifleBoltFree_Base.c.
JF1
ref WeaponStableState Rifle_Base::JF1 private
Definition at line 99 of file RifleBoltFree_Base.c.
L0
ref WeaponStableState Rifle_Base::L0 private
Definition at line 73 of file SKS.c.
O00
ref WeaponStableState Rifle_Base::O00 private
Definition at line 125 of file RifleBoltLock_Base.c.
O01
ref WeaponStableState Rifle_Base::O01 private
Definition at line 126 of file RifleBoltLock_Base.c.
The documentation for this class was generated from the following files:
scripts/4_World/Entities/Firearms/AutomaticRifle/SKS.c
scripts/4_World/Entities/Firearms/Rifle/Repeater.c
scripts/4_World/Entities/Firearms/RifleBoltFree_Base.c
scripts/4_World/Entities/Firearms/RifleBoltLock_Base.c
scripts/4_World/Entities/Firearms/RifleSingleShot_Base.c