DayZ: ErrorHandlerModule Class Reference
ErrorHandlerModule Class Reference
Definition and API of an ErrorHandlerModule - Do not insert any logic here! (as this class is not moddable)
Protected Member Functions
void OnErrorThrown (int errorCode, owned string additionalInfo="")
Event that gets triggered when an error of the owned category is thrown.
string GetClientMessage (int errorCode, string additionalInfo="")
Retrieve the message shown on Client.
string GetLastClientMessage (int errorCode)
Retrieve the message shown on Client.
string GetServerMessage (int errorCode, string additionalInfo="")
Retrieve the message shown on Server.
string GetLastServerMessage (int errorCode)
Retrieve the message shown on Server.
string GetSimpleMessage (int errorCode, string additionalInfo="")
Simple message of just code and info.
void OnEvent (EventType eventTypeId, Param params)
Event called by ErrorModuleHandler.
Private Member Functions
proto native ErrorCategory GetCategory ()
Returns the category the module handles.
proto native void SetCategory (ErrorCategory category)
Set the category the module handles.
Detailed Description
Definition and API of an ErrorHandlerModule - Do not insert any logic here! (as this class is not moddable)
Definition at line 5 of file ErrorHandlerModule.c.
Member Function Documentation
GetCategory()
proto native ErrorCategory ErrorHandlerModule::GetCategory () private
Returns the category the module handles.
GetClientMessage()
string ErrorHandlerModule::GetClientMessage (int errorCode, string additionalInfo = "") inline protected
Retrieve the message shown on Client.
Definition at line 22 of file ErrorHandlerModule.c.
  {
    return GetSimpleMessage(errorCode, additionalInfo);
  }
References GetSimpleMessage().
GetLastClientMessage()
string ErrorHandlerModule::GetLastClientMessage (int errorCode) inline protected
Retrieve the message shown on Client.
Definition at line 28 of file ErrorHandlerModule.c.
  {
    return GetSimpleMessage(errorCode);
  }
References GetSimpleMessage().
GetLastServerMessage()
string ErrorHandlerModule::GetLastServerMessage (int errorCode) inline protected
Retrieve the message shown on Server.
Definition at line 40 of file ErrorHandlerModule.c.
  {
    return GetSimpleMessage(errorCode);
  }
References GetSimpleMessage().
GetServerMessage()
string ErrorHandlerModule::GetServerMessage (int errorCode, string additionalInfo = "") inline protected
Retrieve the message shown on Server.
Definition at line 34 of file ErrorHandlerModule.c.
  {
    return GetSimpleMessage(errorCode, additionalInfo);
  }
References GetSimpleMessage().
GetSimpleMessage()
string ErrorHandlerModule::GetSimpleMessage (int errorCode, string additionalInfo = "") inline protected
Simple message of just code and info.
Definition at line 46 of file ErrorHandlerModule.c.
  {
    return string.Format("[%1]: %2", ErrorModuleHandler.GetErrorHex(errorCode), additionalInfo);
  }
References string::Format(), and ErrorModuleHandler::GetErrorHex().
Referenced by GetClientMessage(), GetLastClientMessage(), GetLastServerMessage(), and GetServerMessage().
OnErrorThrown()
void ErrorHandlerModule::OnErrorThrown (int errorCode, owned string additionalInfo = "") inline protected
Event that gets triggered when an error of the owned category is thrown.
Definition at line 14 of file ErrorHandlerModule.c.
  {
#ifdef DEVELOPER
    Print(ErrorModuleHandler.GetErrorHex(errorCode));
#endif
  }
References ErrorModuleHandler::GetErrorHex(), and Print().
OnEvent()
void ErrorHandlerModule::OnEvent (EventType eventTypeId, Param params) inline protected
Event called by ErrorModuleHandler.
Definition at line 52 of file ErrorHandlerModule.c.
  {
  }
SetCategory()
proto native void ErrorHandlerModule::SetCategory (ErrorCategory category) private
Set the category the module handles.
The documentation for this class was generated from the following file:
scripts/3_Game/Global/ErrorModuleHandler/ErrorHandlerModule.c