DayZ: DayZIntroScene Class Reference
DayZIntroScene Class Reference
Protected Member Functions
void DayZIntroScene ()
void ~DayZIntroScene ()
IntroSceneCharacter GetIntroCharacter ()
Camera GetIntroCamera ()
void ResetIntroCamera ()
void SetInitPostprocesses ()
Since this can get created at the same time as DayZGame, non-static postprocesses need to be deffered.
void GetSelectedUserName ()
vector SwapYZ (vector vec)
vector SnapToGround (vector pos)
Protected Attributes
ref IntroSceneCharacter m_Character
Camera m_Camera
vector m_CameraTrans [4]
vector m_CharacterPos
vector m_CharacterRot
Weather m_Weather
vector m_Target
ref OptionsMenu m_OptionsMenu
Additional Inherited Members
Private Member Functions inherited from Managed
void IntroSceneCharacter ()
void ~IntroSceneCharacter ()
bool IsDefaultCharacter ()
void SetToDefaultCharacter ()
void SetCharacterID (int char_id)
int GetCharacterID ()
PlayerBase GetCharacterObj ()
TStringArray GetCharGenderList ()
TStringArray GetCharList (ECharGender gender)
TStringArray GetCharShirtsList ()
TStringArray GetCharPantsList ()
TStringArray GetCharShoesList ()
void SetCharacterGender (ECharGender gender)
bool IsCharacterFemale ()
ECharGender GetCharacterGender ()
vector GetPosition ()
int GetNextCharacterID ()
int GetPrevCharacterID ()
void CreateNewCharacterRandom ()
void CreateNewCharacterById (int character_id)
void CreateNewCharacterByName (string character_name, bool randomize_equip=true)
void CreateDefaultCharacter ()
void GetLastPlayedServer (int characterID, out string address, out string name, out int port)
void CreateNewCharacter ()
void LoadCharacterData (vector char_pos, vector char_rot, bool default_char=false)
Generates random equip for the new IntroSceneCharacter, whatever is defined in 'cfgCharacterCreation'.
void CharacterUnload ()
void CharacterLoad (int character_id, vector char_pos, vector char_rot)
void SetupPlayerName (bool new_name)
void SetAttachment (string type, int slot)
string GetCharacterNameById (int char_id)
string GetCharacterName ()
void SaveCharName (string name)
void SaveDefaultCharacter ()
void TransferValues (PlayerBase player)
void Init ()
void OnScheduledTick (float deltatime)
void CheckValues ()
float GetBlood ()
float GetHealth ()
void CheckHealth ()
void CheckBlood ()
void SendInitValues ()
Sends values on object creation.
void SendValue (int value_type, float value)
void ReceiveValue (int value_type, float value)
void OnRPC (ParamsReadContext ctx)
void ShowDebugValues (bool show)
void BleedingIndicator (int source_ID, int severity, GameplayEffectsDataBleeding parent)
void InitIndicator (vector position)
void StopIndicator (bool instant=false)
void StartRunningDrops ()
bool IsRunningDrops ()
Are any drops currently being animated?
void TrySpawnNextDrop ()
void ResetSequence ()
void ResetIndicator ()
void Update (float timeSlice)
bool GetEndNow ()
int GetSeverity ()
void GameplayEffectsData (array< ref Widget > input, int type, int user_override=-1)
void Init (array< ref Widget > input, int type, Widget layout_root, int user_override=-1)
array< ref Widget > GetWidgetSet ()
int GetWidgetSetType ()
int GetWidgetSetID ()
bool HasDefinedHandle ()
Returns 'true' if this class contains update info.
bool DataInitialized ()
void UpdateVisibility (bool state)
void RegisterData (Param p)
void Update (float timeSlice=0, Param p=null, int handle=-1)
void ForceStop ()
Private Attributes inherited from Managed
int m_CharacterId
string m_CharacterType
MenuData m_CharacterDta
PlayerBase m_CharacterObj
vector m_CharacterPos
vector m_CharacterRot
ref TStringArray m_CharGenderList = new TStringArray
ref TStringArray m_CharShirtList = new TStringArray
ref TStringArray m_CharPantsList = new TStringArray
ref TStringArray m_CharShoesList = new TStringArray
ref map< ECharGender, ref array< string > > m_Characters = new map<ECharGender, ref array<string>>
ECharGender m_CharGender
bool m_InitialSyncSent
bool m_Initialized
bool m_Terminating = false
bool m_EndNow = false
bool m_IsRunning = false
int m_DropSpawnsQueued
int m_ActiveDropsCount
int m_Severity
int m_SourceID
GameplayEffectsDataBleeding m_ParentMetaData
array< float > m_DropProbabilityArray
float m_AverageFrequency
float m_SequenceTick
float m_SequenceDuration
float m_TimeElapsedTotal
float m_TimeElapsedSequence
float m_LastDropSpawnTime
float m_DropSpawnMinDelay
float m_DropSpawnMaxDelay
int m_CurrentDropProbabilityStep
int m_DropProbabilityRollsCount
vector m_BasePosition
ref set< ref BleedingIndicatorDropData > m_ActiveDrops
ref set< int > m_CleanupQueue
ref array< ref Widget > m_WidgetArray
int m_Type
int m_WidgetSetIdentifier
Widget m_LayoutRoot
Detailed Description
Definition at line 1 of file DayZIntroScene.c.
Constructor & Destructor Documentation
DayZIntroScene()
void DayZIntroScene::DayZIntroScene () inline protected
Definition at line 13 of file DayZIntroScene.c.
  {
    string root_path = "cfgCharacterScenes " + g_Game.GetWorldName();
    int count = g_Game.ConfigGetChildrenCount(root_path);
    int index = Math.RandomInt(0, count - 1);
    string childName;
    g_Game.ConfigGetChildName(root_path, index, childName);
    string scene_path = root_path + " " + childName;
    m_Target = SwapYZ(g_Game.ConfigGetVector(scene_path + " target"));
    vector position = SwapYZ(g_Game.ConfigGetVector(scene_path + " position"));
    TIntArray date = new TIntArray;
    TFloatArray storm = new TFloatArray;
    g_Game.ConfigGetIntArray(scene_path + " date", date);
    float fov = g_Game.ConfigGetFloat(scene_path + " fov");
    float overcast = g_Game.ConfigGetFloat(scene_path + " overcast");
    float rain = g_Game.ConfigGetFloat(scene_path + " rain");
    float fog = g_Game.ConfigGetFloat(scene_path + " fog");
    float windspeed = -1;
    if (g_Game.ConfigIsExisting(scene_path + " windspeed")) windspeed = g_Game.ConfigGetFloat(scene_path + " windspeed");
    g_Game.ConfigGetFloatArray(scene_path + " storm", storm);
    World world = g_Game.GetWorld();
    if (world && date.Count() >= 5)
      world.SetDate(date.Get(0), date.Get(1), date.Get(2), date.Get(3), date.Get(4));
    GetGame().ObjectDelete(m_Camera);
    Class.CastTo(m_Camera, g_Game.CreateObject("staticcamera", SnapToGround(position), true)); //Vector(position[0] , position[1] + 1, position[2])
    Math3D.MatrixIdentity4(m_CameraTrans);
    if (m_Camera)
    {
      //m_Camera.SetPosition(Vector(m_Camera.GetPosition()[0],m_Camera.GetPosition()[1]+0,m_Camera.GetPosition()[2]));
      m_Camera.LookAt(m_Target);
      m_Camera.SetFOV(fov);
      m_Camera.SetFocus(5.0, 0.0); //5.0, 1.0
      m_Camera.SetActive(true);
      Math3D.DirectionAndUpMatrix(m_Target - SnapToGround(position), "0 1 0", m_CameraTrans);
      m_CameraTrans[3] = m_Camera.GetPosition();
      m_CharacterPos = Vector(0.685547, -0.988281, 3.68823).Multiply4(m_CameraTrans);
      float pos_x = m_CharacterPos[0];
      float pos_z = m_CharacterPos[2];
      float pos_y = GetGame().SurfaceY(pos_x, pos_z);
      vector ground_demo_pos = Vector(pos_x, pos_y, pos_z);
      m_CharacterPos = ground_demo_pos;
      vector to_cam_dir = m_Camera.GetPosition() - m_CharacterPos;
      m_CharacterRot[0] = Math.Atan2(to_cam_dir[0], to_cam_dir[2]) * Math.RAD2DEG;
    }
    m_Weather = g_Game.GetWeather();
    m_Weather.GetOvercast().SetLimits(overcast, overcast);
    m_Weather.GetRain().SetLimits(rain, rain);
    m_Weather.GetFog().SetLimits(fog, fog);
    m_Weather.GetOvercast().Set(overcast, 0, 0);
    m_Weather.GetRain().Set(rain, 0, 0);
    m_Weather.GetFog().Set(fog, 0, 0);
    if (storm.Count() == 3)
      m_Weather.SetStorm(storm.Get(0), storm.Get(1), storm.Get(2));
    if (windspeed != -1)
    {
      m_Weather.SetWindSpeed(windspeed);
      m_Weather.SetWindMaximumSpeed(windspeed);
      m_Weather.SetWindFunctionParams(1, 1, 1);
    }
    m_Character = new IntroSceneCharacter();
    m_Character.LoadCharacterData(m_CharacterPos, m_CharacterRot);
    PPEffects.Init(); //Deprecated, left in for legacy purposes only
    GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(SetInitPostprocesses);
  }
References Math::Atan2(), CALL_CATEGORY_GUI, Class::CastTo(), Math3D::DirectionAndUpMatrix(), g_Game, Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), PPEffects::Init(), Managed::IntroSceneCharacter(), m_Camera, m_CameraTrans, m_Character, m_CharacterPos, m_CharacterRot, m_Target, m_Weather, Math3D::MatrixIdentity4(), Math::RAD2DEG, Math::RandomInt(), SetInitPostprocesses(), Weather::SetStorm(), Weather::SetWindFunctionParams(), Weather::SetWindMaximumSpeed(), Weather::SetWindSpeed(), SnapToGround(), SwapYZ(), and Vector().
~DayZIntroScene()
void DayZIntroScene::~DayZIntroScene () inline protected
Definition at line 96 of file DayZIntroScene.c.
  {
    if (PPEManagerStatic.GetPPEManager())
      PPEManagerStatic.GetPPEManager().StopAllEffects(PPERequesterCategory.ALL);
  }
References PPEManagerStatic::GetPPEManager().
Member Function Documentation
GetIntroCamera()
Camera DayZIntroScene::GetIntroCamera () inline protected
Definition at line 113 of file DayZIntroScene.c.
  {
    return m_Camera;
  }
References m_Camera.
Referenced by UIScriptedMenu::OnShow(), and ResetIntroCamera().
GetIntroCharacter()
IntroSceneCharacter DayZIntroScene::GetIntroCharacter () inline protected
Definition at line 105 of file DayZIntroScene.c.
  {
    return m_Character;
  }
References m_Character.
Referenced by UIScriptedMenu::CanSaveDefaultCharacter(), UIScriptedMenu::ConnectLastSession(), UIScriptedMenu::NextCharacter(), UIScriptedMenu::OnChangeCharacter(), UIScriptedMenu::OnMouseEnter(), UIScriptedMenu::OnShow(), UIScriptedMenu::PreviousCharacter(), and ResetIntroCamera().
GetSelectedUserName()
void DayZIntroScene::GetSelectedUserName () inline protected
Definition at line 136 of file DayZIntroScene.c.
  {
    string name;
    BiosUserManager user_manager = GetGame().GetUserManager();
    if (user_manager)
    {
      BiosUser user = user_manager.GetSelectedUser();
      if (user)
      {
        g_Game.SetPlayerGameName(user.GetName());
        return;
      }
    }
    g_Game.SetPlayerGameName(GameConstants.DEFAULT_CHARACTER_NAME);
  }
References GameConstants::DEFAULT_CHARACTER_NAME, g_Game, GetGame(), and name.
ResetIntroCamera()
void DayZIntroScene::ResetIntroCamera () inline protected
Definition at line 121 of file DayZIntroScene.c.
  {
    if (GetIntroCharacter().GetCharacterObj())
    {
      GetIntroCamera().LookAt(GetIntroCharacter().GetPosition() + Vector(0, 1, 0));
      //GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLater( SceneCharacterSetPos, 250 );
    }
  }
References Managed::GetCharacterObj(), GetIntroCamera(), GetIntroCharacter(), Managed::GetPosition(), and Vector().
Referenced by UIScriptedMenu::Init().
SetInitPostprocesses()
void DayZIntroScene::SetInitPostprocesses () inline protected
Since this can get created at the same time as DayZGame, non-static postprocesses need to be deffered.
Definition at line 131 of file DayZIntroScene.c.
  {
    PPERequesterBank.GetRequester(PPERequester_BurlapSackEffects).Stop();
  }
Referenced by DayZIntroScene().
SnapToGround()
vector DayZIntroScene::SnapToGround (vector pos) inline protected
Definition at line 164 of file DayZIntroScene.c.
  {
    float pos_x = pos[0];
    float pos_z = pos[2];
    float pos_y = GetGame().SurfaceY(pos_x, pos_z);
    vector tmp_pos = Vector(pos_x, pos_y, pos_z);
    tmp_pos[1] = tmp_pos[1] + pos[1];
    return tmp_pos;
  }
References GetGame(), and Vector().
Referenced by DayZIntroScene().
SwapYZ()
vector DayZIntroScene::SwapYZ (vector vec) inline protected
Definition at line 153 of file DayZIntroScene.c.
  {
    vector tmp;
    tmp[0] = vec[0];
    tmp[1] = vec[2];
    tmp[2] = vec[1];
    return tmp;
  }
Referenced by DayZIntroScene().
Member Data Documentation
m_Camera
Camera DayZIntroScene::m_Camera protected
Definition at line 4 of file DayZIntroScene.c.
Referenced by DayZIntroScene(), DayZIntroScenePC::DayZIntroScenePC(), and GetIntroCamera().
m_CameraTrans
vector DayZIntroScene::m_CameraTrans[4] protected
Definition at line 5 of file DayZIntroScene.c.
Referenced by DayZIntroScene().
m_Character
ref IntroSceneCharacter DayZIntroScene::m_Character protected
Definition at line 3 of file DayZIntroScene.c.
Referenced by DayZIntroScenePC::CharacterRotate(), DayZIntroScenePC::CharacterRotationStart(), DayZIntroScene(), GetIntroCharacter(), and DayZIntroScenePC::Update().
m_CharacterPos
vector DayZIntroScene::m_CharacterPos protected
Definition at line 6 of file DayZIntroScene.c.
Referenced by DayZIntroScene(), and DayZIntroScenePC::DayZIntroScenePC().
m_CharacterRot
vector DayZIntroScene::m_CharacterRot protected
Definition at line 7 of file DayZIntroScene.c.
Referenced by DayZIntroScenePC::CharacterRotate(), DayZIntroScenePC::CharacterRotationStart(), and DayZIntroScene().
m_OptionsMenu
ref OptionsMenu DayZIntroScene::m_OptionsMenu protected
Definition at line 11 of file DayZIntroScene.c.
m_Target
vector DayZIntroScene::m_Target protected
Definition at line 9 of file DayZIntroScene.c.
Referenced by DayZIntroScene().
m_Weather
Weather DayZIntroScene::m_Weather protected
Definition at line 8 of file DayZIntroScene.c.
Referenced by DayZIntroScene().
The documentation for this class was generated from the following file:
scripts/5_Mission/DayZIntroScene.c