DayZ: bool Class Reference
bool Class Reference
Private Member Functions
string ToString ()
Detailed Description
Definition at line 1 of file EnConvert.c.
Member Function Documentation
ToString()
string bool::ToString () inline private
Definition at line 3 of file EnConvert.c.
  {
    if (value) return "true";
    else return "false";
  }
Referenced by HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindAbortDestinationState(), Environment::GetDebugMessage(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortEvent(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessAbortEvent(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent(), and HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessEvent().
The documentation for this class was generated from the following file:
scripts/1_Core/proto/EnConvert.c