DayZ: Compass Class Reference
Compass Class Reference
Protected Member Functions
void Compass ()
override void Open ()
override void Close ()
override bool IsOpen ()
void UpdateVisualState ()
override void OnVariablesSynchronized ()
override void SetActions ()
Protected Attributes
ref OpenableBehaviour m_Openable
Detailed Description
Definition at line 1 of file Compass.c.
Constructor & Destructor Documentation
Compass()
void Compass::Compass () inline protected
Definition at line 5 of file Compass.c.
  {
    m_Openable = new OpenableBehaviour(false);
    RegisterNetSyncVariableBool("m_Openable.m_IsOpened");
    UpdateVisualState();
  }
References m_Openable, and UpdateVisualState().
Member Function Documentation
Close()
override void Compass::Close () inline protected
Definition at line 22 of file Compass.c.
  {
    m_Openable.Close();
    SetSynchDirty();
    UpdateVisualState();
  }
References m_Openable, and UpdateVisualState().
IsOpen()
override bool Compass::IsOpen () inline protected
Definition at line 30 of file Compass.c.
  {
    return m_Openable.IsOpened();
  }
References m_Openable.
Referenced by UpdateVisualState().
OnVariablesSynchronized()
override void Compass::OnVariablesSynchronized () inline protected
Definition at line 43 of file Compass.c.
  {
    super.OnVariablesSynchronized();
    UpdateVisualState();
  }
References UpdateVisualState().
Open()
override void Compass::Open () inline protected
Definition at line 14 of file Compass.c.
  {
    m_Openable.Open();
    SetSynchDirty();
    UpdateVisualState();
  }
References m_Openable, and UpdateVisualState().
SetActions()
override void Compass::SetActions () inline protected
Definition at line 50 of file Compass.c.
  {
    super.SetActions();
    AddAction(ActionOpen);
    AddAction(ActionClose);
    AddAction(ActionViewCompass);
  }
References AddAction().
UpdateVisualState()
void Compass::UpdateVisualState () inline protected
Definition at line 35 of file Compass.c.
  {
    if (IsOpen())
      SetAnimationPhase("cover", 1.0);
    else
      SetAnimationPhase("cover", 0.0);
  }
References IsOpen().
Referenced by Close(), Compass(), OnVariablesSynchronized(), and Open().
Member Data Documentation
m_Openable
ref OpenableBehaviour Compass::m_Openable protected
Definition at line 3 of file Compass.c.
Referenced by Close(), Compass(), IsOpen(), and Open().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Compass.c