DayZ: ActionCarDoors Class Reference
ActionCarDoors Class Reference
Protected Member Functions
void ActionCarDoors ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStartServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnEnd (ActionData action_data)
override bool CanBeUsedInVehicle ()
void FillCommandUIDPerCrewIdx (int crewIdx0, int crewIdx1, int crewIdx2, int crewIdx3)
void FillCommandUIDPerCrewIdx (int evenCrewIdx0, int unevenCrewIdx1)
Protected Attributes
int m_CommandUIDPerCrewIdx [4]
bool m_IsOpening = true
CarScript m_Car = null
string m_AnimSource = ""
Detailed Description
Definition at line 1 of file ActionCarDoors.c.
Constructor & Destructor Documentation
ActionCarDoors()
void ActionCarDoors::ActionCarDoors () inline protected
Definition at line 10 of file ActionCarDoors.c.
  {
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_OPENDOORFW;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ALL;
    m_LockTargetOnUse = false;
  }
References AnimatedActionBase::m_CommandUID, m_LockTargetOnUse, and m_StanceMask.
Member Function Documentation
ActionCondition()
override bool ActionCarDoors::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline protected
player inside vehicle
crewIdx sanity checks and see if there is a door
see if door is in reach
Definition at line 23 of file ActionCarDoors.c.
  {
    CarScript car = null;
    string animSource = "";
    if (player && player.GetCommand_Vehicle())
    {
      if (Class.CastTo(car, player.GetCommand_Vehicle().GetTransport()))
      {
        int crewIdx = car.CrewMemberIndex(player);
        if (crewIdx < 0 || crewIdx > 3 || car.GetCarDoorsState(car.GetDoorInvSlotNameFromSeatPos(crewIdx)) == CarDoorState.DOORS_MISSING)
          return false;
        animSource = car.GetAnimSourceFromSelection(car.GetDoorSelectionNameFromSeatPos(crewIdx));
        if (!car.CanReachDoorsFromSeat(animSource, crewIdx) || !car.IsAreaAtDoorFree(crewIdx))
          return false;
        m_CommandUID = m_CommandUIDPerCrewIdx[crewIdx];
        float animationPhaseInside = car.GetAnimationPhase(animSource);
        return (m_IsOpening && animationPhaseInside <= 0.5) || (!m_IsOpening && animationPhaseInside > 0.5);
      }
    }
    return false;
  }
References Class::CastTo(), AnimatedActionBase::m_CommandUID, m_CommandUIDPerCrewIdx, and m_IsOpening.
CanBeUsedInVehicle()
override bool ActionCarDoors::CanBeUsedInVehicle () inline protected
Definition at line 102 of file ActionCarDoors.c.
  {
    return true;
  }
CreateConditionComponents()
override void ActionCarDoors::CreateConditionComponents () inline protected
Definition at line 17 of file ActionCarDoors.c.
  {
    m_ConditionItem = new CCINone;
    m_ConditionTarget = new CCTNone;
  }
References m_ConditionItem, and m_ConditionTarget.
FillCommandUIDPerCrewIdx() [1/2]
void ActionCarDoors::FillCommandUIDPerCrewIdx (int crewIdx0, int crewIdx1, int crewIdx2, int crewIdx3) inline protected
Definition at line 107 of file ActionCarDoors.c.
  {
    m_CommandUIDPerCrewIdx[0] = crewIdx0;
    m_CommandUIDPerCrewIdx[1] = crewIdx1;
    m_CommandUIDPerCrewIdx[2] = crewIdx2;
    m_CommandUIDPerCrewIdx[3] = crewIdx3;
  }
References m_CommandUIDPerCrewIdx.
Referenced by ActionCloseCarDoors::ActionCloseCarDoors(), ActionOpenCarDoors::ActionOpenCarDoors(), and FillCommandUIDPerCrewIdx().
FillCommandUIDPerCrewIdx() [2/2]
void ActionCarDoors::FillCommandUIDPerCrewIdx (int evenCrewIdx0, int unevenCrewIdx1) inline protected
Definition at line 115 of file ActionCarDoors.c.
  {
    FillCommandUIDPerCrewIdx(evenCrewIdx0, unevenCrewIdx1, evenCrewIdx0, unevenCrewIdx1);
  }
References FillCommandUIDPerCrewIdx().
OnEnd()
override void ActionCarDoors::OnEnd (ActionData action_data) inline protected
Definition at line 96 of file ActionCarDoors.c.
  {
    if (m_Car || m_AnimSource.Length() > 0)
      Error("[WARNING] m_Car and m_AnimSource are left for backwards compatibility to not crash mods that are using it, but should no longer be used.");
  }
References Error(), string::Length(), m_AnimSource, and m_Car.
OnEndServer()
override void ActionCarDoors::OnEndServer (ActionData action_data) inline protected
Definition at line 85 of file ActionCarDoors.c.
  {
    CarScript car;
    PlayerBase player = action_data.m_Player;
    if (player && player.GetCommand_Vehicle())
      car = CarScript.Cast(player.GetCommand_Vehicle().GetTransport());
    if (car)
      car.ForceUpdateLightsEnd();
  }
OnStartServer()
override void ActionCarDoors::OnStartServer (ActionData action_data) inline protected
Definition at line 55 of file ActionCarDoors.c.
  {
    PlayerBase player = action_data.m_Player;
    float phase;
    if (m_IsOpening)
      phase = 1.0;
    else
      phase = 0.0;
    string animSource = "";
    CarScript car;
    if (player && player.GetCommand_Vehicle())
    {
      car = CarScript.Cast(player.GetCommand_Vehicle().GetTransport());
      if (car)
      {
        int crewIdx = car.CrewMemberIndex(player);
        animSource = car.GetAnimSourceFromSelection(car.GetDoorSelectionNameFromSeatPos(crewIdx));
      }
    }
    if (car)
    {
      car.ForceUpdateLightsStart();
      car.SetAnimationPhase(animSource, phase);
    }
  }
References m_IsOpening.
Member Data Documentation
m_AnimSource
string ActionCarDoors::m_AnimSource = "" protected
Definition at line 7 of file ActionCarDoors.c.
Referenced by OnEnd().
m_Car
CarScript ActionCarDoors::m_Car = null protected
Definition at line 6 of file ActionCarDoors.c.
Referenced by OnEnd().
m_CommandUIDPerCrewIdx
int ActionCarDoors::m_CommandUIDPerCrewIdx[4] protected
Definition at line 3 of file ActionCarDoors.c.
Referenced by ActionCondition(), and FillCommandUIDPerCrewIdx().
m_IsOpening
bool ActionCarDoors::m_IsOpening = true protected
Definition at line 4 of file ActionCarDoors.c.
Referenced by ActionCloseCarDoors::ActionCloseCarDoors(), ActionCondition(), ActionOpenCarDoors::ActionOpenCarDoors(), and OnStartServer().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Interact/Vehicles/ActionCarDoors.c