DayZ: Bottle_Base Class Reference
Bottle_Base Class Reference
Private Member Functions
void CanisterGasoline ()
void ~CanisterGasoline ()
override bool IsContainer ()
override string GetPouringSoundset ()
override string GetEmptyingLoopSoundsetHard ()
override string GetEmptyingLoopSoundsetSoft ()
override string GetEmptyingLoopSoundsetWater ()
override string GetEmptyingEndSoundsetHard ()
override string GetEmptyingEndSoundsetSoft ()
override string GetEmptyingEndSoundsetWater ()
override float GetLiquidThroughputCoef ()
override bool CanPutInCargo (EntityAI parent)
override bool IsOpen ()
void Canteen ()
void ~Canteen ()
override bool IsContainer ()
override string GetPouringSoundset ()
override string GetEmptyingLoopSoundsetHard ()
override string GetEmptyingLoopSoundsetSoft ()
override string GetEmptyingLoopSoundsetWater ()
override string GetEmptyingEndSoundsetHard ()
override string GetEmptyingEndSoundsetSoft ()
override string GetEmptyingEndSoundsetWater ()
override bool CanPutInCargo (EntityAI parent)
override bool IsOpen ()
override void EEOnCECreate ()
void Cauldron ()
void ~Cauldron ()
override bool IsContainer ()
override string GetPouringSoundset ()
override string GetEmptyingLoopSoundsetHard ()
override string GetEmptyingLoopSoundsetSoft ()
override string GetEmptyingLoopSoundsetWater ()
override string GetEmptyingEndSoundsetHard ()
override string GetEmptyingEndSoundsetSoft ()
override string GetEmptyingEndSoundsetWater ()
override bool CanPutInCargo (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanLoadItemIntoCargo (EntityAI item)
override bool IsOpen ()
override bool CanHaveWetness ()
override void SetActions ()
void Pot ()
void ~Pot ()
override bool IsContainer ()
override string GetPouringSoundset ()
override string GetEmptyingLoopSoundsetHard ()
override string GetEmptyingLoopSoundsetSoft ()
override string GetEmptyingLoopSoundsetWater ()
override string GetEmptyingEndSoundsetHard ()
override string GetEmptyingEndSoundsetSoft ()
override string GetEmptyingEndSoundsetWater ()
override bool CanPutInCargo (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanLoadItemIntoCargo (EntityAI item)
override bool IsOpen ()
override bool CanHaveWetness ()
override void SetActions ()
void WaterBottle ()
void ~WaterBottle ()
override bool IsContainer ()
override string GetPouringSoundset ()
override string GetEmptyingLoopSoundsetHard ()
override string GetEmptyingLoopSoundsetSoft ()
override string GetEmptyingLoopSoundsetWater ()
override string GetEmptyingEndSoundsetHard ()
override string GetEmptyingEndSoundsetSoft ()
override string GetEmptyingEndSoundsetWater ()
override bool CanPutInCargo (EntityAI parent)
override bool IsOpen ()
override void EEOnCECreate ()
Detailed Description
Definition at line 1 of file CanisterGasoline.c.
Constructor & Destructor Documentation
~CanisterGasoline()
void Bottle_Base::~CanisterGasoline () inline private
Definition at line 7 of file CanisterGasoline.c.
  {
  }
~Canteen()
void Bottle_Base::~Canteen () inline private
Definition at line 8 of file Canteen.c.
  {
  }
~Cauldron()
void Bottle_Base::~Cauldron () inline private
Definition at line 8 of file Cauldron.c.
  {
  }
~Pot()
void Bottle_Base::~Pot () private
~WaterBottle()
void Bottle_Base::~WaterBottle () inline private
Definition at line 8 of file WaterBottle.c.
  {
  }
Member Function Documentation
CanHaveWetness() [1/2]
override bool Bottle_Base::CanHaveWetness () inline private
Definition at line 99 of file Cauldron.c.
  {
    return true;
  }
CanHaveWetness() [2/2]
override bool Bottle_Base::CanHaveWetness () inline private
Definition at line 116 of file Pot.c.
  {
    return true;
  }
CanisterGasoline()
void Bottle_Base::CanisterGasoline () inline private
Definition at line 3 of file CanisterGasoline.c.
  {
  }
CanLoadItemIntoCargo() [1/2]
override bool Bottle_Base::CanLoadItemIntoCargo (EntityAI item) inline private
Definition at line 83 of file Cauldron.c.
  {
    if (!super.CanLoadItemIntoCargo(item))
      return false;
    if (IsCargoException4x3(item))
      return false;
    return true;
  }
References IsCargoException4x3().
CanLoadItemIntoCargo() [2/2]
override bool Bottle_Base::CanLoadItemIntoCargo (EntityAI item) inline private
Definition at line 88 of file Pot.c.
  {
    if (!super.CanLoadItemIntoCargo(item))
      return false;
    if (IsCargoException4x3(item))
      return false;
    //can 'this' be attached to the item (->assumed smaller size than item)?
    int slotId;
    for (int i = 0; i < GetInventory().GetSlotIdCount(); i++)
    {
      slotId = GetInventory().GetSlotId(i);
      if (item.GetInventory().HasAttachmentSlot(slotId))
      {
        //Print("CanLoadItemIntoCargo | item " + item + " matches in slot name: " + InventorySlots.GetSlotName(slotId) + " of " + this);
        return false;
      }
    }
    return true;
  }
References IsCargoException4x3().
CanPutInCargo() [1/5]
override bool Bottle_Base::CanPutInCargo (EntityAI parent) inline private
Definition at line 56 of file CanisterGasoline.c.
  {
    if (!super.CanPutInCargo(parent)) return false;
    if (parent && (parent.IsKindOf("CanisterGasoline"))/* && !(parent.IsKindOf("Container_Base"))*/)
      return false;
    return true;
  }
CanPutInCargo() [2/5]
override bool Bottle_Base::CanPutInCargo (EntityAI parent) inline private
Definition at line 53 of file Canteen.c.
  {
    if (!super.CanPutInCargo(parent)) return false;
    if (parent && (parent.IsKindOf("Canteen"))/* && !(parent.IsKindOf("Container_Base"))*/)
      return false;
    return true;
  }
CanPutInCargo() [3/5]
override bool Bottle_Base::CanPutInCargo (EntityAI parent) inline private
Definition at line 53 of file Cauldron.c.
  {
    if (!super.CanPutInCargo(parent))
      return false;
    if (parent && IsCargoException4x3(parent))
      return false;
    //is 'parent' somewhere in cargo?
    if (parent && parent.GetInventory().IsCargoInHiearchy())
      return false;
    return true;
  }
References IsCargoException4x3().
CanPutInCargo() [4/5]
override bool Bottle_Base::CanPutInCargo (EntityAI parent) inline private
Definition at line 46 of file Pot.c.
  {
    if (!super.CanPutInCargo(parent))
      return false;
    if (parent && IsCargoException4x3(parent))
      return false;
    //is 'parent' somewhere in cargo?
    if (parent && parent.GetInventory().IsCargoInHiearchy())
      return false;
    return true;
  }
References IsCargoException4x3().
CanPutInCargo() [5/5]
override bool Bottle_Base::CanPutInCargo (EntityAI parent) inline private
Definition at line 53 of file WaterBottle.c.
  {
    if (!super.CanPutInCargo(parent)) return false;
    if (parent && (parent.IsKindOf("WatterBottle"))/* && !(parent.IsKindOf("Container_Base"))*/)
      return false;
    return true;
  }
CanReceiveItemIntoCargo() [1/2]
override bool Bottle_Base::CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 68 of file Cauldron.c.
  {
    if (!super.CanReceiveItemIntoCargo(item))
      return false;
    if (IsCargoException4x3(item))
      return false;
    //is 'this' somewhere in cargo?
    if (GetInventory().IsCargoInHiearchy())
      return false;
    return true;
  }
References IsCargoException4x3().
CanReceiveItemIntoCargo() [2/2]
override bool Bottle_Base::CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 61 of file Pot.c.
  {
    if (!super.CanReceiveItemIntoCargo(item))
      return false;
    if (IsCargoException4x3(item))
      return false;
    //is 'this' somewhere in cargo?
    if (GetInventory().IsCargoInHiearchy())
      return false;
    //can 'this' be attached to the item (->assumed smaller size than item)?
    int slotId;
    for (int i = 0; i < GetInventory().GetSlotIdCount(); i++)
    {
      slotId = GetInventory().GetSlotId(i);
      if (item.GetInventory().HasAttachmentSlot(slotId))
      {
        //Print("CanReceiveItemIntoCargo | item " + item + " matches in slot name: " + InventorySlots.GetSlotName(slotId) + " of " + this);
        return false;
      }
    }
    return true;
  }
References IsCargoException4x3().
Canteen()
void Bottle_Base::Canteen () inline private
Definition at line 3 of file Canteen.c.
  {
  }
Cauldron()
void Bottle_Base::Cauldron () inline private
Definition at line 3 of file Cauldron.c.
  {
  }
EEOnCECreate() [1/2]
override void Bottle_Base::EEOnCECreate () inline private
Definition at line 67 of file Canteen.c.
  {
    super.EEOnCECreate();
    int rand = Math.RandomInt(0, 10);
    if (rand > 5)
      InsertAgent(eAgents.CHOLERA, 1);
  }
References InsertAgent(), and Math::RandomInt().
EEOnCECreate() [2/2]
override void Bottle_Base::EEOnCECreate () inline private
Definition at line 67 of file WaterBottle.c.
  {
    super.EEOnCECreate();
    int rand = Math.RandomInt(0, 10);
    if (rand > 5)
      InsertAgent(eAgents.CHOLERA, 1);
  }
References InsertAgent(), and Math::RandomInt().
GetEmptyingEndSoundsetHard() [1/5]
override string Bottle_Base::GetEmptyingEndSoundsetHard () inline private
Definition at line 36 of file CanisterGasoline.c.
  {
    return "pour_End_HardGround_GasolineCanister_SoundSet";
  }
Referenced by GetEmptyingEndSoundset().
GetEmptyingEndSoundsetHard() [2/5]
override string Bottle_Base::GetEmptyingEndSoundsetHard () inline private
Definition at line 38 of file Canteen.c.
  {
    return "pour_End_HardGround_Canteen_SoundSet";
  }
GetEmptyingEndSoundsetHard() [3/5]
override string Bottle_Base::GetEmptyingEndSoundsetHard () inline private
Definition at line 38 of file Cauldron.c.
  {
    return "pour_End_HardGround_Pot_SoundSet";
  }
GetEmptyingEndSoundsetHard() [4/5]
override string Bottle_Base::GetEmptyingEndSoundsetHard () inline private
Definition at line 31 of file Pot.c.
  {
    return "pour_End_HardGround_Pot_SoundSet";
  }
GetEmptyingEndSoundsetHard() [5/5]
override string Bottle_Base::GetEmptyingEndSoundsetHard () inline private
Definition at line 38 of file WaterBottle.c.
  {
    return "pour_End_HardGround_WatterBottle_SoundSet";
  }
GetEmptyingEndSoundsetSoft() [1/5]
override string Bottle_Base::GetEmptyingEndSoundsetSoft () inline private
Definition at line 41 of file CanisterGasoline.c.
  {
    return "pour_End_SoftGround_GasolineCanister_SoundSet";
  }
Referenced by GetEmptyingEndSoundset().
GetEmptyingEndSoundsetSoft() [2/5]
override string Bottle_Base::GetEmptyingEndSoundsetSoft () inline private
Definition at line 43 of file Canteen.c.
  {
    return "pour_End_SoftGround_Canteen_SoundSet";
  }
GetEmptyingEndSoundsetSoft() [3/5]
override string Bottle_Base::GetEmptyingEndSoundsetSoft () inline private
Definition at line 43 of file Cauldron.c.
  {
    return "pour_End_SoftGround_Pot_SoundSet";
  }
GetEmptyingEndSoundsetSoft() [4/5]
override string Bottle_Base::GetEmptyingEndSoundsetSoft () inline private
Definition at line 36 of file Pot.c.
  {
    return "pour_End_SoftGround_Pot_SoundSet";
  }
GetEmptyingEndSoundsetSoft() [5/5]
override string Bottle_Base::GetEmptyingEndSoundsetSoft () inline private
Definition at line 43 of file WaterBottle.c.
  {
    return "pour_End_SoftGround_WatterBottle_SoundSet";
  }
GetEmptyingEndSoundsetWater() [1/5]
override string Bottle_Base::GetEmptyingEndSoundsetWater () inline private
Definition at line 46 of file CanisterGasoline.c.
  {
    return "pour_End_Water_GasolineCanister_SoundSet";
  }
Referenced by GetEmptyingEndSoundset().
GetEmptyingEndSoundsetWater() [2/5]
override string Bottle_Base::GetEmptyingEndSoundsetWater () inline private
Definition at line 48 of file Canteen.c.
  {
    return "pour_End_Water_Canteen_SoundSet";
  }
GetEmptyingEndSoundsetWater() [3/5]
override string Bottle_Base::GetEmptyingEndSoundsetWater () inline private
Definition at line 48 of file Cauldron.c.
  {
    return "pour_End_Water_Pot_SoundSet";
  }
GetEmptyingEndSoundsetWater() [4/5]
override string Bottle_Base::GetEmptyingEndSoundsetWater () inline private
Definition at line 41 of file Pot.c.
  {
    return "pour_End_Water_Pot_SoundSet";
  }
GetEmptyingEndSoundsetWater() [5/5]
override string Bottle_Base::GetEmptyingEndSoundsetWater () inline private
Definition at line 48 of file WaterBottle.c.
  {
    return "pour_End_Water_WatterBottle_SoundSet";
  }
GetEmptyingLoopSoundsetHard() [1/5]
override string Bottle_Base::GetEmptyingLoopSoundsetHard () inline private
Definition at line 21 of file CanisterGasoline.c.
  {
    return "pour_HardGround_GasolineCanister_SoundSet";
  }
Referenced by GetEmptyingLoopSoundset().
GetEmptyingLoopSoundsetHard() [2/5]
override string Bottle_Base::GetEmptyingLoopSoundsetHard () inline private
Definition at line 23 of file Canteen.c.
  {
    return "pour_HardGround_Canteen_SoundSet";
  }
GetEmptyingLoopSoundsetHard() [3/5]
override string Bottle_Base::GetEmptyingLoopSoundsetHard () inline private
Definition at line 23 of file Cauldron.c.
  {
    return "pour_HardGround_Pot_SoundSet";
  }
GetEmptyingLoopSoundsetHard() [4/5]
override string Bottle_Base::GetEmptyingLoopSoundsetHard () inline private
Definition at line 16 of file Pot.c.
  {
    return "pour_HardGround_Pot_SoundSet";
  }
GetEmptyingLoopSoundsetHard() [5/5]
override string Bottle_Base::GetEmptyingLoopSoundsetHard () inline private
Definition at line 23 of file WaterBottle.c.
  {
    return "pour_HardGround_WatterBottle_SoundSet";
  }
GetEmptyingLoopSoundsetSoft() [1/5]
override string Bottle_Base::GetEmptyingLoopSoundsetSoft () inline private
Definition at line 26 of file CanisterGasoline.c.
  {
    return "pour_SoftGround_GasolineCanister_SoundSet";
  }
Referenced by GetEmptyingLoopSoundset().
GetEmptyingLoopSoundsetSoft() [2/5]
override string Bottle_Base::GetEmptyingLoopSoundsetSoft () inline private
Definition at line 28 of file Canteen.c.
  {
    return "pour_SoftGround_Canteen_SoundSet";
  }
GetEmptyingLoopSoundsetSoft() [3/5]
override string Bottle_Base::GetEmptyingLoopSoundsetSoft () inline private
Definition at line 28 of file Cauldron.c.
  {
    return "pour_SoftGround_Pot_SoundSet";
  }
GetEmptyingLoopSoundsetSoft() [4/5]
override string Bottle_Base::GetEmptyingLoopSoundsetSoft () inline private
Definition at line 21 of file Pot.c.
  {
    return "pour_SoftGround_Pot_SoundSet";
  }
GetEmptyingLoopSoundsetSoft() [5/5]
override string Bottle_Base::GetEmptyingLoopSoundsetSoft () inline private
Definition at line 28 of file WaterBottle.c.
  {
    return "pour_SoftGround_WatterBottle_SoundSet";
  }
GetEmptyingLoopSoundsetWater() [1/5]
override string Bottle_Base::GetEmptyingLoopSoundsetWater () inline private
Definition at line 31 of file CanisterGasoline.c.
  {
    return "pour_Water_GasolineCanister_SoundSet";
  }
Referenced by GetEmptyingLoopSoundset().
GetEmptyingLoopSoundsetWater() [2/5]
override string Bottle_Base::GetEmptyingLoopSoundsetWater () inline private
Definition at line 33 of file Canteen.c.
  {
    return "pour_Water_Canteen_SoundSet";
  }
GetEmptyingLoopSoundsetWater() [3/5]
override string Bottle_Base::GetEmptyingLoopSoundsetWater () inline private
Definition at line 33 of file Cauldron.c.
  {
    return "pour_Water_Pot_SoundSet";
  }
GetEmptyingLoopSoundsetWater() [4/5]
override string Bottle_Base::GetEmptyingLoopSoundsetWater () inline private
Definition at line 26 of file Pot.c.
  {
    return "pour_Water_Pot_SoundSet";
  }
GetEmptyingLoopSoundsetWater() [5/5]
override string Bottle_Base::GetEmptyingLoopSoundsetWater () inline private
Definition at line 33 of file WaterBottle.c.
  {
    return "pour_Water_WatterBottle_SoundSet";
  }
GetLiquidThroughputCoef()
override float Bottle_Base::GetLiquidThroughputCoef () inline private
Definition at line 51 of file CanisterGasoline.c.
  {
    return LIQUID_THROUGHPUT_GASOLINECANISTER;
  }
References LIQUID_THROUGHPUT_GASOLINECANISTER.
GetPouringSoundset() [1/5]
override string Bottle_Base::GetPouringSoundset () inline private
Definition at line 16 of file CanisterGasoline.c.
  {
    return "emptyVessle_CanisterGasoline_SoundSet";
  }
Referenced by PlayPouringLoopSound().
GetPouringSoundset() [2/5]
override string Bottle_Base::GetPouringSoundset () inline private
Definition at line 18 of file Canteen.c.
  {
    return "emptyVessle_Canteen_SoundSet";
  }
GetPouringSoundset() [3/5]
override string Bottle_Base::GetPouringSoundset () inline private
Definition at line 18 of file Cauldron.c.
  {
    return "emptyVessle_Pot_SoundSet";
  }
GetPouringSoundset() [4/5]
override string Bottle_Base::GetPouringSoundset () inline private
Definition at line 11 of file Pot.c.
  {
    return "emptyVessle_Pot_SoundSet";
  }
GetPouringSoundset() [5/5]
override string Bottle_Base::GetPouringSoundset () inline private
Definition at line 18 of file WaterBottle.c.
  {
    return "emptyVessle_WaterBottle_SoundSet";
  }
IsContainer() [1/5]
override bool Bottle_Base::IsContainer () inline private
Definition at line 11 of file CanisterGasoline.c.
  {
    return true;
  }
IsContainer() [2/5]
override bool Bottle_Base::IsContainer () inline private
Definition at line 13 of file Canteen.c.
  {
    return true;
  }
IsContainer() [3/5]
override bool Bottle_Base::IsContainer () inline private
Definition at line 13 of file Cauldron.c.
  {
    return true;
  }
IsContainer() [4/5]
override bool Bottle_Base::IsContainer () inline private
Definition at line 6 of file Pot.c.
  {
    return true;
  }
IsContainer() [5/5]
override bool Bottle_Base::IsContainer () inline private
Definition at line 13 of file WaterBottle.c.
  {
    return true;
  }
IsOpen() [1/5]
override bool Bottle_Base::IsOpen () inline private
Definition at line 65 of file CanisterGasoline.c.
  {
    return true;
  }
IsOpen() [2/5]
override bool Bottle_Base::IsOpen () inline private
Definition at line 62 of file Canteen.c.
  {
    return true;
  }
IsOpen() [3/5]
override bool Bottle_Base::IsOpen () inline private
Definition at line 94 of file Cauldron.c.
  {
    return true;
  }
IsOpen() [4/5]
override bool Bottle_Base::IsOpen () inline private
Definition at line 111 of file Pot.c.
  {
    return true;
  }
IsOpen() [5/5]
override bool Bottle_Base::IsOpen () inline private
Definition at line 62 of file WaterBottle.c.
  {
    return true;
  }
Pot()
void Bottle_Base::Pot () private
SetActions() [1/2]
override void Bottle_Base::SetActions () inline private
Definition at line 104 of file Cauldron.c.
  {
    super.SetActions();
    RemoveAction(ActionDrink);
    RemoveAction(ActionEmptyBottleBase);
    AddAction(ActionDrinkCookingPot);
    AddAction(ActionEmptyCookingPot);
  }
References AddAction(), and RemoveAction().
SetActions() [2/2]
override void Bottle_Base::SetActions () inline private
Definition at line 121 of file Pot.c.
  {
    super.SetActions();
    RemoveAction(ActionDrink);
    RemoveAction(ActionEmptyBottleBase);
    AddAction(ActionDrinkCookingPot);
    AddAction(ActionEmptyCookingPot);
  }
References AddAction(), and RemoveAction().
WaterBottle()
void Bottle_Base::WaterBottle () inline private
Definition at line 3 of file WaterBottle.c.
  {
  }
The documentation for this class was generated from the following files:
scripts/4_World/Entities/ItemBase/Edible_Base/Bottle_Base/CanisterGasoline.c
scripts/4_World/Entities/ItemBase/Edible_Base/Bottle_Base/Canteen.c
scripts/4_World/Entities/ItemBase/Edible_Base/Bottle_Base/Cauldron.c
scripts/4_World/Entities/ItemBase/Edible_Base/Bottle_Base/Pot.c
scripts/4_World/Entities/ItemBase/Edible_Base/Bottle_Base/WaterBottle.c