DayZ: ComponentBodyStaging Class Reference
ComponentBodyStaging Class Reference
Protected Member Functions
void SynchSkinnedState ()
Private Member Functions
void ComponentBodyStaging ()
void ~ComponentBodyStaging ()
void SetAsSkinned ()
bool IsSkinned ()
void SetAsSkinnedClient ()
Private Member Functions inherited from Component
void Event_OnFrame (IEntity other, float timeSlice)
Shape DebugBBoxDraw ()
void DebugBBoxSetColor (int color)
void DebugBBoxDelete ()
Shape DebugDirectionDraw (float distance=1)
void DebugDirectionSetColor (int color)
void DebugDirectionDelete ()
void SetParentEntityAI (EntityAI e)
void Event_OnAwake ()
void Event_OnInit ()
void LogThis (string msg, string fnc_name="n/a")
void LogThisWarning (string msg, string fnc_name="n/a")
void LogThisError (string msg, string fnc_name="n/a")
string GetCompName ()
int GetCompType ()
void Event_OnItemAttached (EntityAI item, string slot_name)
void Event_OnItemDetached (EntityAI item, string slot_name)
override Shape DebugBBoxDraw ()
override void DebugBBoxSetColor (int color)
override void DebugBBoxDelete ()
override Shape DebugDirectionDraw (float distance=1)
override void DebugDirectionDelete ()
void OnDrawing ()
Private Attributes
bool m_IsSkinned
Private Attributes inherited from Component
EntityAI m_ThisEntityAI
Shape m_DebugShapeBBox
Shape m_DebugShapeDirection
float m_DebugShapeDirectionDist
Additional Inherited Members
Static Private Member Functions inherited from Component
static void Init ()
static string GetNameByType (int comp_type)
static bool IsTypeExist (int comp_type)
static void LogErrorBadCompType (int comp_type, string fnc_name)
static void LogWarningAlredyExist (int comp_type, string fnc_name)
Detailed Description
Definition at line 9 of file BodyStaging.c.
Constructor & Destructor Documentation
ComponentBodyStaging()
void ComponentBodyStaging::ComponentBodyStaging () inline private
Definition at line 13 of file BodyStaging.c.
  {
    m_IsSkinned = false;
  }
References m_IsSkinned.
~ComponentBodyStaging()
void ComponentBodyStaging::~ComponentBodyStaging () inline private
Definition at line 18 of file BodyStaging.c.
  {
  }
Member Function Documentation
IsSkinned()
bool ComponentBodyStaging::IsSkinned () inline private
Definition at line 44 of file BodyStaging.c.
  {
    return m_IsSkinned;
  }
References m_IsSkinned.
Referenced by SynchSkinnedState().
SetAsSkinned()
void ComponentBodyStaging::SetAsSkinned () inline private
Definition at line 23 of file BodyStaging.c.
  {
    m_IsSkinned = true;
    // Temporal! Body is moved into ground so we can see if it was already skinned or not until necesarry assets are developed.
    /*
      if ( !m_ThisEntityAI.IsKindOf("Animal_GallusGallusDomesticus")  &&  !m_ThisEntityAI.IsKindOf("Animal_GallusGallusDomesticusF") )
      {
      vector body_new_pos = m_ThisEntityAI.GetPosition() - "0 0.2 0";
      m_ThisEntityAI.SetPosition(body_new_pos);
      }
      else
      {
      vector body_new_pos2 = m_ThisEntityAI.GetPosition() - "0 0.08 0";
      m_ThisEntityAI.SetPosition(body_new_pos2);
      }
    */
    SynchSkinnedState();
  }
References m_IsSkinned, and SynchSkinnedState().
SetAsSkinnedClient()
void ComponentBodyStaging::SetAsSkinnedClient () inline private
Definition at line 49 of file BodyStaging.c.
  {
    m_IsSkinned = true;
  }
References m_IsSkinned.
SynchSkinnedState()
void ComponentBodyStaging::SynchSkinnedState () inline protected
Definition at line 59 of file BodyStaging.c.
  {
    if (GetGame().IsServer())
    {
      Param1<bool> p = new Param1<bool>(IsSkinned());
      GetGame().RPCSingleParam(m_ThisEntityAI, ERPCs.RPC_BS_SKINNED_STATE, p, true);
    }
  }
References GetGame(), IsSkinned(), and Component::m_ThisEntityAI.
Referenced by SetAsSkinned().
Member Data Documentation
m_IsSkinned
bool ComponentBodyStaging::m_IsSkinned private
Definition at line 11 of file BodyStaging.c.
Referenced by ComponentBodyStaging(), IsSkinned(), SetAsSkinned(), and SetAsSkinnedClient().
The documentation for this class was generated from the following file:
scripts/3_Game/tools/Component/BodyStaging.c