DayZ: scripts/4_World/Entities/ItemBase/FireworksBase.c File Reference
FireworksBase.c File Reference
Enumerations
enum EFireworksState {
DEFAULT , PLACED , IGNITED , FIRING ,
FINISHED
}
Functions
void FireworksBase ()
override void EEOnCECreate ()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
void SetActions ()
override bool HasFlammableMaterial ()
float GetMaxAllowedWetness ()
EFireworksState GetState ()
returns one of STATE_...
void SetState (EFireworksState state)
void OnStateChangedServer (EFireworksState currentState)
void OnStateChangedClient (EFireworksState currentState)
void OnInventoryEnter (Man player)
void OnInventoryExit (Man player)
void StandUp ()
override void OnIgnitedThis (EntityAI fire_source)
Executed on Server when some item ignited this one.
bool CanBeIgnitedBy (EntityAI igniter=NULL)
void OnEventServer (int type)
Called periodically after the entity gets ignited.
float GetEventDelay ()
void OnVariablesSynchronized ()
Variables
enum EFireworksState m_State
EFireworksState m_StatePrev
ref Timer m_TimerEvent
int m_RandomSeed
Enumeration Type Documentation
EFireworksState
enum EFireworksState
Enumerator
DEFAULT
PLACED
IGNITED
FIRING
FINISHED
Definition at line 2 of file FireworksBase.c.
{
  DEFAULT,
  PLACED,
  IGNITED,
  FIRING,
  FINISHED
}
Function Documentation
CanBeIgnitedBy()
bool CanBeIgnitedBy (EntityAI igniter = NULL) protected
Definition at line 97 of file FireworksBase.c.
  {
    if (GetWet() >= GetMaxAllowedWetness())
      return false;
    if (MiscGameplayFunctions.IsUnderRoofEx(this, 60))
      return false;
    if ((GetState() <= EFireworksState.PLACED) && vector.Dot(vector.Up, GetDirectionUp()) > 0.95)
      return true;
    return false;
  }
References vector::Dot(), GetMaxAllowedWetness(), GetState(), GetWet(), and vector::Up.
EEOnCECreate()
override void EEOnCECreate () protected
Definition at line 23 of file FireworksBase.c.
  {
    StandUp();
  }
References StandUp().
FireworksBase()
void FireworksBase () protected
Definition at line 18 of file FireworksBase.c.
  {
    Init();
  }
References Init().
GetEventDelay()
float GetEventDelay () protected
Definition at line 113 of file FireworksBase.c.
  {
    return 0;
  }
GetMaxAllowedWetness()
float GetMaxAllowedWetness () protected
Definition at line 45 of file FireworksBase.c.
  {
    return 0.1;
  }
Referenced by CanBeIgnitedBy().
GetState()
EFireworksState GetState () protected
returns one of STATE_...
returns the state of climb (enum value of ClimbStates);
Definition at line 50 of file FireworksBase.c.
  {
    return m_State;
  }
References m_State.
HasFlammableMaterial()
override bool HasFlammableMaterial () protected
Definition at line 40 of file FireworksBase.c.
  {
    return true;
  }
Init()
void Init () protected
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
Definition at line 120 of file DayZGame.c.
  {
    layoutRoot = GetGame().GetWorkspace().CreateWidgets("gui/layouts/dialog_queue_position.layout");
    m_HintPanel = new UiHintPanelLoading(layoutRoot.FindAnyWidget("hint_frame0"));
    m_txtPosition = TextWidget.Cast(layoutRoot.FindAnyWidget("txtPosition"));
    m_txtNote = TextWidget.Cast(layoutRoot.FindAnyWidget("txtNote"));
    m_btnLeave = ButtonWidget.Cast(layoutRoot.FindAnyWidget("btnLeave"));
    m_txtNote.Show(true);
    layoutRoot.FindAnyWidget("notification_root").Show(false);
#ifdef PLATFORM_CONSOLE
    layoutRoot.FindAnyWidget("toolbar_bg").Show(true);
    RichTextWidget toolbar_b = RichTextWidget.Cast(layoutRoot.FindAnyWidget("BackIcon"));
    toolbar_b.SetText(InputUtils.GetRichtextButtonIconFromInputAction("UAUIBack", "", EUAINPUT_DEVICE_CONTROLLER, InputUtils.ICON_SCALE_TOOLBAR));
#ifdef PLATFORM_XBOX
#ifdef BUILD_EXPERIMENTAL
    layoutRoot.FindAnyWidget("notification_root").Show(true);
#endif
#endif
#endif
    return layoutRoot;
  }
References AddModifier(), CALL_CATEGORY_GUI, CALL_CATEGORY_SYSTEM, Class::CastTo(), DrawConnectingLines(), UIScriptedMenu::DrawConnectingLines(), FISH_AGILITY, JsonMissionLoaderData::GetData(), GetGame(), CfgGameplayHandler::GetHoldBreathStaminaModifier(), GetPlayer(), InputUtils::GetRichtextButtonIconFromInputAction(), hndDebugPrint(), InputUtils::ICON_SCALE_TOOLBAR, INDEX_NOT_FOUND, INIT_LINE_STRETCH, InitPPEManagerClassMap(), InjectDamageSystemValues(), IsCameraNV(), LogManager::IsInventoryHFSMLogEnable(), ItemOptics::IsNVOptic(), ItemOptics::IsWorking(), LateInit(), m_Back, m_BaseValue, m_btnLeave, m_BurnTimePerFullFuelDose, m_BurnTimePerFullLard, m_BurnTimePerRag, m_ChanceRange, m_context_menu, m_Cooldown, m_CrossHairs, m_Cycler, m_CyclerCatching, m_DrainValvePressureDeanimationSettings, m_DrainValvePressureStageSettings, m_DrainValveWaterStageSettings, m_Duration, m_ExistingPostprocessRequests, m_Exponent, m_FillValvePressureDeanimationSettings, m_FillValvePressureStageSettings, m_FillValveWaterStageSettings, m_FishingTime, m_FishProximity, m_FSwapping, m_FSwappingInst, m_HintPanel, m_Inventory, m_IsFishPulling, m_LastActiveValve, m_ManagerInitialized, m_MaxConsumableFuelQuantity, m_MaxConsumableLardQuantity, m_MissionData, m_MovingTo, m_Multiplier, m_Name, m_Notifiers, m_opticsUsed, m_PipeBrokenParticles, m_PipeSounds, m_Player, m_Pos, m_PPEMaterialUpdateQueueMap, m_pPlayer, m_PressureAnimationRequests, m_PressureDeanimationRequests, m_PressureTimesAccumulated, m_Pull, m_Root, m_StartTimeAdjustment, m_Swapping, m_tab_images, m_TabScript, m_Taking, m_txtNote, m_txtPosition, m_UpdatedMaterials, m_UpdatingRequests, m_ValveManipulatedIndex, m_ValveManipulatedIndexPrev, m_ValveNames, m_ValveParticles, m_ValveStates, m_WaterLevelActual, m_WaterLevelPrev, m_WaterLevelsAvailable, m_WaterLevelSnapshot, m_WaterLevelTimesAccumulated, m_WgtBtnMsnClose, m_WgtBtnMsnPlay, m_WgtLstMsnList, MAX_FISHING_TIME, MIN_FISHING_TIME, path, PIPES_BROKEN_COUNT, Math::RandomInt(), SetCameraNV(), SetCameraNVType(), GameConstants::STAMINA_DRAIN_HOLD_BREATH_DURATION, GameConstants::STAMINA_DRAIN_HOLD_BREATH_EXPONENT, GameConstants::STAMINA_DRAIN_HOLD_BREATH_START, GameConstants::STAMINA_REGEN_COOLDOWN_DEPLETION, Update(), UpdateConstructionParts(), UpdatePlayerStatsValues(), VALVES_COUNT, WL_AVERAGE, WL_MAX, and WL_MIN.
Referenced by ScriptedWidgetEventHandler::Attach(), PluginBase::CheckInit(), ClockBase(), DayZPlayerCameraBase(), DayZPlayerCameraBase::DayZPlayerCameraIronsights(), DayZPlayerImplementMeleeCombat(), DayZPlayerMeleeFightLogic_LightHeavy(), Environment::Environment(), FireworksBase(), Land_Underground_WaterReservoir(), Link< Class T >::Link(), LoginQueueBase::LoginQueueStatic(), LoginTimeBase::LoginTimeStatic(), ModifiersManager(), NotifiersManager(), ScriptedWidgetEventHandler::OnWidgetScriptInit(), ManBase::PlayerBase(), PlayerStats::PlayerStats(), PPEClassBase::PPEClassBase(), BleedingSourcesManagerBase::Reload(), RemotePlayerStatDebug(), UniversalTemperatureSourceDebug::UniversalTemperatureSource(), and DayZInfected::ZombieBase().
OnEventServer()
void OnEventServer (int type) protected
Called periodically after the entity gets ignited.
OnIgnitedThis()
override void OnIgnitedThis (EntityAI fire_source) protected
Executed on Server when some item ignited this one.
Definition at line 91 of file FireworksBase.c.
  {
    SetState(EFireworksState.IGNITED);
  }
References SetState().
OnInventoryEnter()
void OnInventoryEnter (Man player) protected
Definition at line 70 of file FireworksBase.c.
  {
    if (GetState() == EFireworksState.PLACED)
      SetState(EFireworksState.DEFAULT);
  }
References GetState(), and SetState().
OnInventoryExit()
void OnInventoryExit (Man player) protected
Definition at line 76 of file FireworksBase.c.
  {
    super.OnInventoryExit(player);
    if (!IsBeingPlaced())
      StandUp();
  }
References IsBeingPlaced(), and StandUp().
OnStateChangedClient()
void OnStateChangedClient (EFireworksState currentState) protected
Referenced by OnVariablesSynchronized().
OnStateChangedServer()
void OnStateChangedServer (EFireworksState currentState) protected
Referenced by SetState().
OnVariablesSynchronized()
void OnVariablesSynchronized () protected
Definition at line 118 of file FireworksBase.c.
  {
    //Print("new state client: " + m_State);
    super.OnVariablesSynchronized();
    if (m_State != m_StatePrev)
    {
      OnStateChangedClient(m_State);
      m_StatePrev = m_State;
    }
  }
References m_State, m_StatePrev, and OnStateChangedClient().
SetActions()
void SetActions () protected
Definition at line 31 of file FireworksBase.c.
  {
    super.SetActions();
    AddAction(ActionTogglePlaceObject);
    AddAction(ActionDeployObject);
    AddAction(ActionLightItemOnFire);
  }
References ActionLightItemOnFire(), and AddAction().
SetState()
void SetState (EFireworksState state) protected
Definition at line 55 of file FireworksBase.c.
  {
    if (state != m_StatePrev && GetGame().IsServer())
    {
      m_State = state;
      SetSynchDirty();
      OnStateChangedServer(state);
      m_StatePrev = state;
    }
  }
References GetGame(), m_State, m_StatePrev, and OnStateChangedServer().
StandUp()
void StandUp () protected
Definition at line 84 of file FireworksBase.c.
  {
    if (!IsRuined())
      SetOrientation(vector.Zero);
  }
References vector::Zero.
Referenced by EEOnCECreate(), and OnInventoryExit().
Variable Documentation
m_RandomSeed
int m_RandomSeed protected
Definition at line 16 of file FireworksBase.c.
Referenced by FireworksLauncher::FireworksLauncher(), and FireworksLauncher::OnVariablesSynchronized().
m_State
enum EFireworksState m_State
m_StatePrev
EFireworksState m_StatePrev protected
Definition at line 14 of file FireworksBase.c.
m_TimerEvent
ref Timer m_TimerEvent protected
Definition at line 15 of file FireworksBase.c.
Referenced by FireworksLauncher::OnEventServer(), Anniversary_FireworksLauncher::OnEventServer(), FireworksLauncher::OnIgnitedThis(), and FireworksLauncher::RestartEventTimer().