DayZ: ActionSortAmmoPile Class Reference
ActionSortAmmoPile Class Reference
Private Member Functions
void ActionSortAmmoPile ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnEndAnimationLoopServer (ActionData action_data)
void SortAmmo (ItemBase item)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 9 of file ActionSortAmmoPile.c.
Constructor & Destructor Documentation
ActionSortAmmoPile()
void ActionSortAmmoPile::ActionSortAmmoPile () inline private
Definition at line 11 of file ActionSortAmmoPile.c.
  {
    m_CallbackClass = ActionSortAmmoPileCB;
    m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
    m_Text = "#sort_ammunition";
  }
References AnimatedActionBase::m_CallbackClass, m_SpecialtyWeight, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionSortAmmoPile::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 24 of file ActionSortAmmoPile.c.
  {
    return false;
  }
CreateConditionComponents()
override void ActionSortAmmoPile::CreateConditionComponents () inline private
Definition at line 18 of file ActionSortAmmoPile.c.
  {
    m_ConditionItem = new CCINonRuined;
    m_ConditionTarget = new CCTSelf;
  }
References m_ConditionItem, and m_ConditionTarget.
OnEndAnimationLoopServer()
override void ActionSortAmmoPile::OnEndAnimationLoopServer (ActionData action_data) inline private
Definition at line 29 of file ActionSortAmmoPile.c.
  {
    SortAmmo(action_data.m_MainItem);
  }
References SortAmmo().
SortAmmo()
void ActionSortAmmoPile::SortAmmo (ItemBase item) inline private
Definition at line 34 of file ActionSortAmmoPile.c.
  {
    Magazine magazine;
    Magazine piles[5];
    //string pile_classname = magazine.ConfigGetString("spawnPileType");
    if (Class.CastTo(magazine, item))
    {
      float health;
      string ammo_type;
      while (magazine.GetAmmoCount() > 0)
      {
        int count = magazine.GetAmmoCount();
        if (magazine.ServerAcquireCartridge(health, ammo_type))
        {
          int health_label = MiscGameplayFunctions.GetHealthLevelForAmmo(ammo_type, health);
          if (piles[health_label] == null)
            piles[health_label] = Magazine.Cast(GetGame().CreateObjectEx(item.ClassName(), item.GetPosition(), ECE_PLACE_ON_SURFACE));
          piles[health_label].ServerStoreCartridge(health, ammo_type);
        }
      }
    }
  }
References Class::CastTo(), ECE_PLACE_ON_SURFACE, and GetGame().
Referenced by OnEndAnimationLoopServer().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionSortAmmoPile.c