DayZ: PluginBase Class Reference
PluginBase Class Reference
Protected Member Functions
void PluginAdminLog ()
void ~PluginAdminLog ()
void LogPrint (string message)
string GetPlayerPrefix (PlayerBase player, PlayerIdentity identity)
string GetHitMessage (TotalDamageResult damageResult, int component, string zone, string ammo)
void PlayerKilled (PlayerBase player, Object source)
void PlayerHitBy (TotalDamageResult damageResult, int damageType, PlayerBase player, EntityAI source, int component, string dmgZone, string ammo)
void UnconStart (PlayerBase player)
void UnconStop (PlayerBase player)
void OnPlacementComplete (Man player, ItemBase item)
void OnContinouousAction (ActionData action_data)
void Suicide (PlayerBase player)
void BleedingOut (PlayerBase player)
void TotemFlagChange (bool top, notnull PlayerBase player, notnull EntityAI totem)
void PlayerList ()
void DirectAdminLogPrint (string str)
override void OnInit ()
void ToggleCameraTools ()
void CursorHide ()
void CursorShow ()
void Save ()
void PlayPause ()
void AddKeyframe ()
void DeleteKeyframe ()
void PossesInfected ()
void CommandHandler (DayZInfected infected)
void Tick ()
void InitAttacks ()
void TeleportAtCursor ()
Set Player position at his cursor position in the world.
void Teleport (PlayerBase player, vector position)
Teleport player at position.
void ToggleFreeCameraBackPos ()
Enable / Disable Free camera (Fly mod)
void ToggleFreeCamera ()
Enable / Disable Free camera (Fly mod) - disable of camera will teleport player at current free camera position.
bool IsEnabledFreeCamera ()
void PluginDeveloper ()
override void OnInit ()
void OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx)
void PrintLogClient (string msg_log)
void SendServerLogToClient (string msg)
void OnRPCSyncSceneObject (ParamsReadContext ctx)
void OnRPCPluginDayzCreatureDebug (PlayerBase player, int rpc_type, ParamsReadContext ctx)
void HandleSetTime (PlayerBase player, ParamsReadContext ctx)
void HandlePresetSpawn (PlayerBase player, string presetName, EntityAI target)
void OnRPCServerLogRecieved (ParamsReadContext ctx)
void OnRPCClearInventory (PlayerBase player)
void OnRPCSpawnEntityOnCursorDir (PlayerBase player, ParamsReadContext ctx)
void OnRPCSpawnEntityOnGround (PlayerBase player, ParamsReadContext ctx)
void OnRPCSpawnEntityOnGroundPatternGrid (PlayerBase player, ParamsReadContext ctx)
void OnRPCSpawnEntity (PlayerBase player, ParamsReadContext ctx)
void OnSetFreeCameraEvent (PlayerBase player, FreeDebugCamera camera)
void OnSpawnErrorReport (string name)
void SetupSpawnedEntity (PlayerBase player, EntityAI entity, float health, float quantity=-1, bool special=false, string presetName="")
void SpawnEntityOnGroundPatternGrid (PlayerBase player, string item_name, int count, float health, float quantity, int rows, int columns, float gapRow=1, float gapColumn=1, bool special=false, bool withPhysics=false)
void SpawnItemOnCrosshair (notnull PlayerBase player, string itemName, float health, float quantity, float maxDist=100, bool allowFreeflight=false, bool special=false, bool withPhysics=false)
EntityAI SpawnEntityOnGroundPos (PlayerBase player, string item_name, float health, float quantity, vector pos, bool special=false, bool withPhysics=false)
spawns entity on exact position
EntityAI SpawnEntityOnCursorDir (PlayerBase player, string item_name, float quantity, float distance, float health=-1, bool special=false, string presetName="", bool withPhysics=false)
spawns entity in direction of cursor at specified distance
EntityAI SpawnEntityInInventory (notnull EntityAI target, string className, float health, float quantity, bool special=false, string presetName="", FindInventoryLocationType locationType=FindInventoryLocationType.ANY)
tries to spawn item somewhere in inventory
EntityAI SpawnEntityInPlayerInventory (PlayerBase player, string item_name, float health, float quantity, bool special=false, string presetName="", FindInventoryLocationType locationType=FindInventoryLocationType.ANY)
EntityAI SpawnEntityAsAttachment (PlayerBase player, EntityAI parent, string att_name, float health, float quantity)
tries to spawn item as attachment
EntityAI SpawnFromClipboard ()
void ClearInventory (EntityAI entity)
void ToggleHelpScreen ()
void ToggleScriptConsole ()
void ToggleMissionLoader ()
void PluginUniversalTemperatureSourceClient ()
override void OnInit ()
override void OnUpdate (float delta_time)
void InitWidgets ()
void DrawDebugs ()
void ProcessUniversalTemperatureSources ()
float CalcTemperatureFromTemperatureSource (notnull UTemperatureSourceDebug utsd)
void EnableWidgets (bool enable)
void UpdateStatWidgets ()
void UpdateStatWidget (int rowIndex, UTemperatureSourceDebug utsd)
void RequestUniversalTemperatureSources (PlayerBase player, int enable)
void PrintedDebug ()
void OnRPC (ParamsReadContext ctx)
void PluginUniversalTemperatureSourceServer ()
override void OnUpdate (float delta_time)
void GatherTemperatureSources (PlayerBase player)
void SendDebug ()
void OnRequestReceived (PlayerBase player, bool enable)
void OnRPC (ParamsReadContext ctx, PlayerBase player)
void RegisterKeyBind (int ui_id, int key_code1, int key_code2, string plugin_name, string fnc_name, string info_shortcut, string info_description)
void RegisterMouseBind (int ui_id, int mouse_button, int mouse_event, string plugin_name, string fnc_name, string info_shortcut, string info_description)
bool IsCurrentUIPageValid (int ui_page_request)
bool CheckMask (int source_mask, int target_mask)
void OnMouse (int event_id, int button)
MouseButtonInfo GetMouseButtonInfo (int button)
bool IsKeyPressed (int key)
void EditorUpdate ()
float GetAgentTransferabilityIn (int agent_id)
bool GrowDuringAntibioticsAttack (int agent_id, PlayerBase player)
float GetAgentDieOffSpeedEx (int agent_id, PlayerBase player)
EStatLevels GetAgentPotencyEx (int agent_id, PlayerBase player)
float GetAgentInvasibilityEx (int agent_id, PlayerBase player)
float GetAgentAntiboticsResistance (int agent_id)
float GetAgentAntiboticsResistanceEx (int agent_id, PlayerBase player)
float GetAgentTransferabilityOut (int agent_id)
float GetAgentTransferabilityAirOut (int agent_id)
float GetAgentInvasibility (int agent_id)
float GetAgentDigestibility (int agent_id)
float GetDieOffSpeed (int agent_id)
EStatLevels GetPotency (int agent_id)
float TransmitAgentsEx (EntityAI source, EntityAI target, int pathway, int dose_size=1000, int agents=0)
void TransmitAgents (EntityAI source, EntityAI target, int pathway, int dose_size=1000)
void InjectAgentsWithoutPlayer (EntityAI target, int agents)
void InjectAgentsWithPlayer (EntityAI target, int agents, float protection, int dose_size, int inject_type)
will add agents to a given target, using chance of transmission and full dose size if chance succeeds
void InjectAgentsWithPlayerCount (EntityAI target, int agents, float protection, int dose_size, int inject_type)
will add agents to a given target, with no probability, but the dose size is modified by m_TransferabilityOut of the agent
float InjectAgentWithPlayerDose (EntityAI target, int agent, float protection, float dose_size, int inject_type)
will add agent to a given target
float GetProtectionLevel (int type, int slot, Man player)
float CalculateAgentsToTransmit (int agent_id, float protection, int dose_size, int inject_type)
bool DetermineChanceToTransmit (int agent_id, float protection, int inject_type)
Static Protected Member Functions
static int GetPlayerListTimer ()
static PluginCameraTools GetInstance ()
static PluginDeveloper GetInstance ()
static int GetAgentMaxCount (int agent_id)
static void BuildAgentArray (int agents, array< int > agents_out)
static float GetProtectionLevelEx (int type, int slot, Man player, bool consider_filter=true, int system=0)
Protected Attributes
int m_HitFilter
int m_PlacementFilter
int m_ActionsFilter
int m_PlayerListFilter
ref Timer m_Timer
autoptr array< Man > m_PlayerArray
const int TIMER_PLAYERLIST = GetPlayerListTimer()
bool m_IsWinHolding
int m_FeaturesMask
UIScriptedMenu m_ScriptConsole
float m_UTSAverageTemperature
ref array< ref UTemperatureSourceDebug > m_UTemperatureSourceDebugs
ref Widget m_RootWidget [MAX_SIMULTANEOUS_UTS]
TextListboxWidget m_StatListWidgets [MAX_SIMULTANEOUS_UTS]
TextWidget m_HeaderWidget [MAX_SIMULTANEOUS_UTS]
const int CLICK_TIME = 200
const int DOUBLE_CLICK_TIME = 300
const int HOLD_CLICK_TIME_MIN = 300
ref array< ref KeyBinding > m_KeyBindings
ref array< ref MouseButtonInfo > m_MouseButtons
ref array< ref MouseBinding > m_MouseBindings
PluginConfigScene m_ModuleConfigScene
PluginConfigDebugProfile m_ModuleConfigDebugProfile
float m_TimeLastClickRelease
float m_TimeLastClickPress
int m_PressedMouseID
bool m_IsDragging
ref array< Shape > m_ShapesSceneObjects
ref map< int, KeyBinding > m_KeyBindings
ref SceneData m_SceneData
SceneObject m_SelectedObject
string m_ClassBrowserSelected
bool m_IsOpen
Static Protected Attributes
static PluginCameraTools m_Instance
static bool m_IsOpen
Private Member Functions
void PluginBase ()
void ~PluginBase ()
void OnInit ()
void OnUpdate (float delta_time)
void OnDestroy ()
void Log (string msg, string label)
string GetModuleName ()
GetModuleType ()
void PluginConfigViewer ()
string MakeTabs (int count, bool inheritance=false)
string GetOnlyChildPath (string config_class_path, string class_path)
string GetBaseClassPath (string config_class_path, string class_path, string config_class)
string GetBaseClassPathCombined (string child_path, string base_class)
string GetBaseClassPathRecursive (string config_class_path, string class_path, string config_class)
bool ContainsFirstClass (string config_class_path, string class_path)
TStringArray GetConfigRecursive (string path, string name, string config_class_path, string config_class, local array< string > overridden, int depth=0, local bool check_base_class_of_class=false)
TStringArray GetConfig (string class_path, string filter_char)
TStringArray GetConfigVariables (string class_path)
TStringArray GetConfigHierarchy (string class_path)
string GetBaseClasses (string path, string item)
void PluginDayZInfectedDebug ()
void ~PluginDayZInfectedDebug ()
void ToggleDebugWindowEvent ()
void ToggleDebugWindowSetMode (int pMode)
void CaptureFocus ()
void ReleaseFocus ()
void Show ()
void Hide ()
void ShowWidgets (bool show)
override void OnUpdate (float delta_time)
void CreateModuleWidgets ()
void DestroyModuleWidgets ()
void ShowCard (int pCard)
bool OnClick (Widget w, int x, int y, int button)
buttons clicks
bool OnChange (Widget w, int x, int y, bool finished)
void ResetValues ()
void SpawnNewInfectedEntity ()
void CleanupDebugShapes (array< Shape > shapesArr)
void ScriptHistoryNext ()
void ScriptHistoryBack ()
bool IsIngame ()
bool IsInConsole ()
int QuickSortPartition (TStringArray arr, int left, int right)
void QuickSort (TStringArray arr, int left, int right)
void SortStringArray (TStringArray arr)
void ResetGUI ()
void SetDeveloperItemClient ()
void CheckInit ()
void Init ()
override void OnUpdate (float delta_time)
override void OnDestroy ()
vector CalculatePos ()
void CheckInit ()
void Init ()
override void OnUpdate (float delta_time)
void PluginDrawCheckerboard ()
void ~PluginDrawCheckerboard ()
void CreateWidgetOverlay ()
bool IsActive ()
bool IsEven (int num)
even or odd
void ShowWidgets (bool show)
void Show ()
void Hide ()
override void OnUpdate (float delta_time)
void SetWatching (bool enable)
bool GetWatching ()
void GatherPlayerInfo ()
void SendDebug ()
void OnDamageEvent (PlayerBase player, TotalDamageResult damageResult)
void OnRequestReceived (PlayerBase player, bool enable)
void OnRPC (ParamsReadContext ctx, PlayerBase player)
void PluginDeveloperSync ()
override void OnInit ()
void EnableUpdate (bool enable, int type, PlayerBase player)
void Update ()
void SetSystemInBitmask (PlayerBase player, int system_bit, bool state)
bool IsSetSystemInBitmask (PlayerBase player, int system_bit)
void RegisterPlayer (PlayerBase player)
bool IsPlayerRegistered (PlayerBase player)
void OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx)
bool GetRPCUpdateState (ParamsReadContext ctx)
int GetRPCModifierID (ParamsReadContext ctx)
void GetRPCModifierLock (ParamsReadContext ctx, out int id, out bool lock)
void SendRPCStats (PlayerBase player)
void OnRPCStats (ParamsReadContext ctx)
void UpdateStatsLocal ()
void OnRPCStatSet (ParamsReadContext ctx, PlayerBase player)
void SendRPCLevels (PlayerBase player)
void OnRPCLevels (ParamsReadContext ctx)
void SendRPCMods (PlayerBase player)
void SendRPCModsDetail (PlayerBase player)
void OnRPCMods (ParamsReadContext ctx)
void OnRPCModsDetailed (ParamsReadContext ctx)
void RequestDetailedInfo (int id, notnull PlayerBase player)
void ActivateModifier (int id, PlayerBase player=NULL)
void DeactivateModifier (int id, PlayerBase player=NULL)
void LockModifier (int id, bool lock, PlayerBase player=NULL)
bool IsModifierLocked (int id, PlayerBase player=NULL)
void SendRPCTemp (PlayerBase player)
void OnRPCTemp (ParamsReadContext ctx, PlayerBase player)
void SendRPCAgents (PlayerBase player)
void OnRPCAgents (ParamsReadContext ctx)
void SendRPCStomach (PlayerBase player)
void OnRPCStomach (ParamsReadContext ctx)
void CaptureFocus ()
void ReleaseFocus ()
void ToggleFocus ()
void PluginFileHandler ()
void ~PluginFileHandler ()
override void OnInit ()
string GetFileName ()
string GetSubFolderName ()
void ClearFileNoSave ()
bool LoadFile ()
bool SaveFile ()
bool IsReadOnly ()
void AddText (string text)
void AddNewLineNoSave (string text)
TStringArray GetFileContent ()
void PluginHorticulture ()
void LoadFromCfg ()
string GetPlantType (Object obj)
float GetSurfaceFertility (string surface_type)
bool GiveWormsToPlayer (PlayerBase player, float chance)
PlantMaterialHealth GetPlantMaterial (string plant_type)
void PluginKeyBinding ()
override void OnInit ()
override void OnDestroy ()
void OnKeyPress (int key)
void OnKeyRelease (int key)
void OnMouseButtonPress (int button)
void OnMouseButtonRelease (int button)
void OnFrame ()
array< ref KeyBinding > GetKeyBindings ()
array< ref MouseBinding > GetMouseBindings ()
void PluginMessageManager ()
void Broadcast (int index)
Broadcasts an empty message on a channel provided in the 'index' parameter.
void BroadcastInt (int index, int value)
Broadcasts a message on a channel provided in the 'index' parameter, passes the Int variable.
void BroadcastFloat (int index, float value)
void BroadcastString (int index, string value)
void BroadcastParam (int index, Param params)
Broadcasts a message on a channel provided in the 'index' parameter, passes the Param type object to the reciever.
void Subscribe (MessageReceiverBase receiver, int index)
Subscribes an object to listen to messages on a channel provided in the 'index' parameter.
void Unsubscribe (MessageReceiverBase receiver, int index)
void UnsubscribeAll (MessageReceiverBase receiver)
void PluginObjectsInteractionManager ()
bool IsFree (Object target)
void Lock (Object target)
void Release (Object target)
void Decay ()
void SwitchPermanentCrossHair (bool state)
void PluginPlayerStatus ()
void SetNotifier (int key, int index=9, string label="", int color=0xFFFFFFFF)
void DisplayTendency (int key, int tendency, int status=1)
void SetBadge (int key, int value)
void SetStamina (int value, int range)
void SetStance (int value)
bool Repair (PlayerBase player, ItemBase repair_kit, Object item, float specialty_weight, string damage_zone="", bool use_kit_qty=true)
void CalculateHealth (PlayerBase player, ItemBase kit, Object item, float specialty_weight, string damage_zone="", bool use_kit_qty=true)
bool CanRepair (ItemBase repair_kit, Object item, string damage_zone="")
bool IsRepairValid (int repair_kit_type, int repairable_with_type)
bool CanRepairToPristine (PlayerBase player)
Player can repair items to 100%; currently unused.
bool CanBeRepairedToPristine (Object item)
Item can be repaired to 100%.
float GetKitRepairCost (ItemBase repair_kit, Object item)
void PluginSceneManager ()
void ~PluginSceneManager ()
override void OnInit ()
override void OnDestroy ()
void OnMouseWheel (int wheel)
void OnUIEditorOpened ()
void OnUIEditorClosed ()
void Event_OnClick ()
void Event_OnClickMiddle ()
void Event_OnDrag ()
SceneObject Event_OnDoubleClick ()
void InitLoad ()
void RestoreSceneObjectsLinks ()
void ExecuteInitScripts ()
void EditorToggle ()
bool IsOpened ()
void SelectClassName (string class_name)
void FreeCameraControlEnable ()
void FreeCameraControlDisable ()
void DeleteSelectedObject ()
void SelectObject (SceneObject obj)
SceneObject GetSelectedSceneObject ()
void SelectedObjectDuplicate ()
void SelectedObjectSetRot (float dir)
void SelectedObjectSetPosX (float value)
void SelectedObjectSetPosY (float value)
void SelectedObjectSetPosZ (float value)
void SelectedObjectSetDamage (float value)
void SelectedObjectFocus ()
void SelectedObjectAddAttachment (string att_name)
void SelectedObjectRemoveAttachment (EntityAI e)
void LinkSceneObjects (SceneObject scene_object1, SceneObject scene_object2)
void UnlinkSceneObjects (SceneObject scene_object1, SceneObject scene_object2)
bool AreSceneObjectsLinked (SceneObject scene_object1, SceneObject scene_object2)
void SetDrawSelection (bool draw)
bool GetDrawSelection ()
void SetLoadPlayerPos (bool save)
bool GetLoadPlayerPos ()
void SetRotationAngle (int angle)
int GetRotationAngle ()
void SceneLoad (string scene_name)
void SceneUnload ()
void SceneSave ()
bool SceneCanDelete (string scene_name)
bool SceneDelete (string scene_name)
void SceneDuplicate (string scene_name)
void SceneRename (string scene_name, string new_name)
string SceneGetName ()
void SetWeather (float overcast, float rain, float fog, float wind_force)
void SetDate (int year, int month, int day, int hour, int minute)
void SelectAndFocusPlayerObject ()
void ExecuteEnforceScript (int index, SceneObject scene_object, string script)
void RulerToggle ()
bool IsRulerActivated ()
void RulerAddPoint ()
void RulerClearVisuals ()
void RulerDelete ()
SceneData GetLoadedScene ()
int GetSelectedSceneObjectIndex ()
array< ref SceneObject > GetSceneObjects ()
array< ref ScenePlayer > GetScenePlayers ()
array< ref SceneObject > GetSceneObjectsAll ()
SceneObject GetSceneObjectByIndex (int index)
SceneObject GetSceneObjectByEntity (EntityAI entity)
TStringArray GetSceneList ()
void DeleteSceneObject (SceneObject obj)
void DeselectObject ()
void SceneEditorMenuCmdRefresh ()
void SceneEditorMenuCmdPopup (string message)
void SceneEditorMenuCmdSave ()
bool IsMouseInScene ()
void EditorUpdateRuler ()
vector GetMousePositionInScene ()
override void OnInit ()
override void OnUpdate (float delta_time)
override void OnDestroy ()
void Show ()
void Hide ()
void OnGUITimer ()
void PluginTransmissionAgents ()
void RegisterAgent (AgentBase agent)
void ConstructSimpleAgentList ()
map< int, ref AgentBase > GetAgentList ()
map< int, string > GetSimpleAgentList ()
void RemoveAllAgents (EntityAI target)
void PluginVariables ()
void ~PluginVariables ()
void RegisterVariable (string name)
string GetName (int id)
int GetID (string name)
Static Private Member Functions
static void SetDeveloperItemClientEx (notnull Object entity, bool getFocus=false)
static bool FileDuplicate (string source_name, string dest_name)
static bool FileDelete (string file)
static void FileRename (string source_name, string dest_name)
static PluginSceneManager GetInstance ()
static string GetNameByID (int agent_id)
static void RemoveAgent (EntityAI target, int agent_id)
Private Attributes
string m_PlayerName
string m_Pid
vector m_Position
string m_PlayerPrefix
string m_PlayerPrefix2
string m_Message
string m_DisplayName
string m_HitMessage
float m_Distance
PlayerBase m_Player
PlayerBase m_Source
string m_ItemInHands
string m_PosArray [3]
int m_DotIndex
PlayerStat< float > m_StatWater
PlayerStat< float > m_StatEnergy
BleedingSourcesManagerServer m_BleedMgr
int m_CurrentMode = 0
bool m_HasFocus = false
bool m_IsActive = false
Widget m_MainWnd
main controls
ButtonWidget m_SpawnEntityButton
ButtonWidget m_CardMovementButton
ButtonWidget m_CardFightButton
Widget m_CardMovementFrame
Widget m_CardFightFrame
TextWidget m_StatusText
XComboBoxWidget m_StanceCB
movement card
XComboBoxWidget m_MindStateCB
EditBoxWidget m_MovementSpeedEB
ButtonWidget m_StartTurnButton
XComboBoxWidget m_TurnTypeCB
EditBoxWidget m_TurnDirectionEB
XComboBoxWidget m_VaultingCB
ButtonWidget m_StartVaultButton
ButtonWidget m_KnucleOutButton
XComboBoxWidget m_CrawlingTypeCB
ButtonWidget m_StartCrawlingButton
EditBoxWidget m_HitDirEB
fight card
XComboBoxWidget m_HitTypeCB
XComboBoxWidget m_HitBodyPartCB
ButtonWidget m_StartHitButton
XComboBoxWidget m_DeathTypeCB
ButtonWidget m_StartDeathButton
XComboBoxWidget m_AttackTypeCB
XComboBoxWidget m_AttackDirCB
ButtonWidget m_StartAttackButton
DayZInfected m_ControlledInfected
controlled instance
bool m_CH_DoTurn = false
command handler values
bool m_CH_DoVault = false
bool m_CH_DoKnucleOut = false
bool m_CH_GoToCrawl = false
bool m_CH_DoHit = false
bool m_CH_StartDeath = false
bool m_CH_DoAttack = false
ref PluginDayZInfectedDebugUIHandler m_pUIHandler
ref array< ref PluginDayZInfectedDebugAttackDesc > m_AttackDescriptors = new array<ref PluginDayZInfectedDebugAttackDesc>
ref array< Shape > m_DebugShapes = new array<Shape>()
ref Timer m_TickTimer
status refresh timer
PluginDeveloper m_ModuleDeveloper
PlayerBase m_Character
bool m_Initialized
vector m_cam_pos
vector m_character_pos
vector m_camera_dir
vector m_cameraTrans [4]
vector m_demoPos
vector m_demoRot
vector m_camera_orientation
const float FOV = 0.5236
ItemBase m_Ruler
ref Widget m_MainWindow
ref set< PlayerBase > m_ClientList = new set<PlayerBase>
ref array< ref RemotePlayerStatDebug > m_PlayerDebugStats = new array<ref RemotePlayerStatDebug>
ref map< PlayerBase, ref RemotePlayerDamageDebug > m_PlayerDebugDamage = new map<PlayerBase, ref RemotePlayerDamageDebug>
float m_AccuTime
[m]
const int INTERVAL = 1
eRemoteDebugType m_DebugType
bool m_Watching
const int MAX_SIMULTANEOUS_UTS = 10
const float LOOKUP_RADIUS = 20
[s]
int m_DetailedInfoRequested = 0
ref Timer m_UpdateTimer
ref map< PlayerBase, ref RegisterPlayerData > m_RegisteredPlayers
ref array< ref SyncedValue > m_PlayerStatsSynced
ref array< ref Param > m_PlayerStomachSynced
ref array< ref SyncedValueLevel > m_PlayerLevelsSynced
ref array< ref SyncedValueModifier > m_PlayerModsSynced
string m_PlayerModsDetailedSynced
string m_EnvironmentDebugMessage
ref array< ref SyncedValueAgent > m_PlayerAgentsSynced
bool m_StatsUpdateStatus
bool m_LevelsUpdateStatus
bool m_ModsUpdateStatus
bool m_AgentsUpdateStatus
bool m_StomachUpdateStatus
bool m_ReadOnly
int m_LineLimit
ref TStringArray m_FileContent
ref map< string, ref PlantMaterialHealth > m_PlantMaterials
int channelsUsed = 0
ref array< ref MessageReceiverBase > channelList [NUM_OF_CHANNELS]
ref array< Object > m_LockedObjects
ref array< float > m_LockedObjectsDecay
const float TIME_TO_FORCED_UNLOCK = 60
const float TICK_RATE = 10
ref Timer m_DecayTimer
Hud m_Hud
ref multiMap< int, string > m_NotifiersLabel
ref multiMap< int, int > m_NotifiersIndexColor
ref multiMap< int, string > m_NotifiersIcons
bool m_RulerActivated
ref array< vector > m_RulerPoints
ref array< Shape > m_RulerLines
ref array< Shape > m_RulerSpheres
ref SoundParams m_soundParams
ref SoundObjectBuilder m_soundBuilder
ref SoundObject m_soundObject
float fadeInVolume = 1.1
float fadeOutVolume = 0.9
AbstractWave m_wave
ref map< int, string > m_SimpleAgentList = new map<int, string>
bool m_IsConstructed = false
int m_Id
ref map< int, string > m_Variables
Static Private Attributes
static PluginKeyBinding instance
static string SCENE_DEFAULT_NAME = "default"
static string SCENE_SUFIX = "scene"
static PlayerBase PLAYER
static PluginSceneManager instance
static const int SCENE_EDITOR_CMD_REFRESH = 0
static const int SCENE_EDITOR_CMD_POPUP = 1
static const int SCENE_EDITOR_CMD_SAVE = 2
static ref map< int, ref AgentBase > m_AgentList = new map<int, ref AgentBase>
Detailed Description
Class PluginMessageManager provides some basic Message Distribution mechanics, if you get instance of this plugin class on your object, you can use its methods to broadcast messages.
Definition at line 1 of file PluginBase.c.
Constructor & Destructor Documentation
PluginBase()
void PluginBase::PluginBase () private
~PluginBase()
void PluginBase::~PluginBase () private
~PluginAdminLog()
void PluginBase::~PluginAdminLog () inline protected
Definition at line 58 of file PluginAdminLog.c.
  {
  }
~PluginDayZInfectedDebug()
void PluginBase::~PluginDayZInfectedDebug () inline private
Definition at line 110 of file PluginDayZInfectedDebug.c.
  {
#ifndef NO_GUI
    DestroyModuleWidgets();
#endif
  }
References DestroyModuleWidgets().
~PluginDrawCheckerboard()
void PluginBase::~PluginDrawCheckerboard () inline private
Definition at line 14 of file PluginDrawCheckerboard.c.
{}
~PluginFileHandler()
void PluginBase::~PluginFileHandler () inline private
Definition at line 32 of file PluginFileHandler.c.
  {
    ClearFileNoSave();
  }
~PluginSceneManager()
void PluginBase::~PluginSceneManager () inline private
Definition at line 28 of file PluginSceneManager.c.
  {
    if (instance == NULL)
      instance = this;
  }
~PluginVariables()
void PluginBase::~PluginVariables () inline private
Definition at line 13 of file PluginVariables.c.
  {
  }
Member Function Documentation
ActivateModifier()
void PluginBase::ActivateModifier (int id, PlayerBase player = NULL) inline private
Definition at line 617 of file PluginDeveloperSync.c.
  {
    if (!player)
      player = PlayerBase.Cast(GetDayZGame().GetPlayer());
    ModifiersManager mods_manager = player.GetModifiersManager();
    mods_manager.ActivateModifier(Math.AbsInt(id));
  }
References Math::AbsInt(), GetDayZGame(), GetPlayer(), and ModifiersManager().
Referenced by OnRPC().
AddKeyframe()
void PluginBase::AddKeyframe () inline protected
Definition at line 58 of file PluginCameraTools.c.
  {
    if (GetGame().GetUIManager().GetMenu())
      GetGame().GetUIManager().GetMenu().OnKeyPress(null, 0, 0, KeyCode.KC_Q);
  }
References GetGame().
AddNewLineNoSave()
void PluginBase::AddNewLineNoSave (string text) inline private
Definition at line 117 of file PluginFileHandler.c.
  {
    if (m_LineLimit > -1)
    {
      if (m_LineLimit == 0)
        return;
      int lines_count = m_FileContent.Count();
      if (lines_count > 0 && lines_count >= m_LineLimit)
      {
        int remove_indexes = lines_count - m_LineLimit;
        for (int i = 0; i <= remove_indexes; ++i)
          m_FileContent.RemoveOrdered(0);
      }
    }
    m_FileContent.Insert(text);
  }
AddText()
void PluginBase::AddText (string text) inline private
Definition at line 111 of file PluginFileHandler.c.
  {
    AddNewLineNoSave(text);
    SaveFile();
  }
AreSceneObjectsLinked()
bool PluginBase::AreSceneObjectsLinked (SceneObject scene_object1, SceneObject scene_object2) inline private
Definition at line 647 of file PluginSceneManager.c.
  {
    if (scene_object1.IsLinkedWithSceneObject(scene_object2) && scene_object2.IsLinkedWithSceneObject(scene_object1))
      return true;
    else
      return false;
  }
BleedingOut()
void PluginBase::BleedingOut (PlayerBase player) inline protected
Definition at line 323 of file PluginAdminLog.c.
  {
    m_PlayerPrefix = GetPlayerPrefix(player, player.GetIdentity());
    LogPrint(m_PlayerPrefix + " bled out");
  }
References GetPlayerPrefix(), and LogPrint().
Broadcast()
void PluginBase::Broadcast (int index) inline private
Broadcasts an empty message on a channel provided in the 'index' parameter.
Definition at line 16 of file PluginMessageManager.c.
  {
    //Debug.Log("Broadcasting message on a channel: "+ ToString(index), "Messaging System");
    array<ref MessageReceiverBase> x = channelList[index];
    //int test = channelList[index].Count();
    for (int i = 0; i < x.Count(); i++)
    {
      MessageReceiverBase mrb = x.Get(i);
      if (mrb != NULL)
      {
        //string s = "Broadcasting message to: "+ToString(mrb);
        //Log(s, LogTemplates.TEMPLATE_BROADCAST);
        mrb.OnReceive(index);
      }
    }
  }
References LayoutHolder::Count(), LayoutHolder::Get(), and x.
BroadcastFloat()
void PluginBase::BroadcastFloat (int index, float value) inline private
Definition at line 54 of file PluginMessageManager.c.
  {
    //Debug.Log("Broadcasting message on a channel: "+ ToString(index), "Messaging System");
    array<ref MessageReceiverBase> x = channelList[index];
    //int test = channelList[index].Count();
    for (int i = 0; i < x.Count(); i++)
    {
      MessageReceiverBase mrb = x.Get(i);
      if (mrb)
      {
        //string s = "Broadcasting message to: "+ToString(mrb);
        //Log(s, LogTemplates.TEMPLATE_BROADCAST);
        mrb.OnReceiveFloat(index, value);
      }
    }
  }
References LayoutHolder::Count(), LayoutHolder::Get(), and x.
BroadcastInt()
void PluginBase::BroadcastInt (int index, int value) inline private
Broadcasts a message on a channel provided in the 'index' parameter, passes the Int variable.
Definition at line 35 of file PluginMessageManager.c.
  {
    //Debug.Log("Broadcasting message on a channel: "+ ToString(index), "Messaging System");
    array<ref MessageReceiverBase> x = channelList[index];
    //int test = channelList[index].Count();
    for (int i = 0; i < x.Count(); i++)
    {
      MessageReceiverBase mrb = x.Get(i);
      if (mrb)
      {
        //string s = "Broadcasting message to: "+ToString(mrb);
        //Log(s, LogTemplates.TEMPLATE_BROADCAST);
        mrb.OnReceiveInt(index, value);
      }
    }
  }
References LayoutHolder::Count(), LayoutHolder::Get(), and x.
BroadcastParam()
void PluginBase::BroadcastParam (int index, Param params) inline private
Broadcasts a message on a channel provided in the 'index' parameter, passes the Param type object to the reciever.
Definition at line 90 of file PluginMessageManager.c.
  {
    //Debug.Log("Broadcasting message on a channel: "+ ToString(index), "Messaging System");
    array<ref MessageReceiverBase> x = channelList[index];
    //int test = channelList[index].Count();
    for (int i = 0; i < x.Count(); i++)
    {
      if (x.Get(i))
        x.Get(i).OnReceiveParam(index, params);
    }
  }
References LayoutHolder::Count(), LayoutHolder::Get(), and x.
BroadcastString()
void PluginBase::BroadcastString (int index, string value) inline private
Definition at line 73 of file PluginMessageManager.c.
  {
    //Debug.Log("Broadcasting message on a channel: "+ ToString(index), "Messaging System");
    array<ref MessageReceiverBase> x = channelList[index];
    //int test = channelList[index].Count();
    for (int i = 0; i < x.Count(); i++)
    {
      if (x.Get(i))
      {
        Print("broadcasting message to: ");
        Print(x.Get(i));
        x.Get(i).OnReceiveString(index, value);
      }
    }
  }
References LayoutHolder::Count(), LayoutHolder::Get(), Print(), and x.
BuildAgentArray()
static void PluginBase::BuildAgentArray (int agents, array< int > agents_out) inline static protected
Definition at line 317 of file PluginTransmissionAgents.c.
  {
    int mask = 1;
    for (int i = 0; i < BIT_INT_SIZE; i++)
    {
      if (mask & agents)
        agents_out.Insert(mask);
      mask = mask * 2;
    }
  }
References BIT_INT_SIZE.
CalcTemperatureFromTemperatureSource()
float PluginBase::CalcTemperatureFromTemperatureSource (notnull UTemperatureSourceDebug utsd) inline protected
heat transfer through air to player (env temperature)
dist factor minimum should be at 0
Definition at line 113 of file PluginUniversalTemperatureSourceClient.c.
  {
    float distance = vector.Distance(m_Player.GetPosition(), utsd.GetValue(0).ToVector());
    distance = Math.Max(distance, 0.1); //min distance cannot be 0 (division by zero)
    float temperature = 0;
    if (distance > utsd.GetValue(1).ToFloat())
    {
      float distFactor = 1 - (distance / utsd.GetValue(2).ToFloat());
      distFactor = Math.Max(distFactor, 0.0);
      temperature = utsd.GetValue(3).ToFloat() * distFactor;
    }
    else
      temperature = utsd.GetValue(3).ToFloat();
    //Print(temperature);
    return temperature;
  }
References vector::Distance(), m_Player, and Math::Max().
Referenced by ProcessUniversalTemperatureSources().
CalculateAgentsToTransmit()
float PluginBase::CalculateAgentsToTransmit (int agent_id, float protection, int dose_size, int inject_type) inline protected
Definition at line 347 of file PluginTransmissionAgents.c.
  {
    //Debug.Log("protection: "+protection.ToString());
    float prot = 1 - protection; //reverse the value (in config, the higher the value, the higher the protection: 0 - 1) so that we can easily interpolate between 0 and 1 by multiplication
    //Debug.Log("prot: "+prot.ToString(), "Agents");
    float transf;
    if (inject_type == InjectTypes.PLAYER_TO_ITEM)
      transf = GetAgentTransferabilityOut(agent_id);
    else if (inject_type == InjectTypes.ITEM_TO_PLAYER)
      transf = GetAgentTransferabilityIn(agent_id);
    else if (inject_type == InjectTypes.PLAYER_AIR_PLAYER)
      transf = GetAgentTransferabilityAirOut(agent_id);
    //Debug.Log("transf: "+transf.ToString(), "Agents");
    //float result =  GetAgentInitialCount(agent_id) * prot * transf * dose_size;//final formula
    float result = 1 * prot * transf * dose_size;//final formula
    //result = Math.Ceil(result);
    //Debug.Log("result: "+result.ToString(), "Agents");
    return result;
  }
References GetAgentTransferabilityAirOut(), GetAgentTransferabilityIn(), and GetAgentTransferabilityOut().
Referenced by InjectAgentsWithPlayerCount(), and InjectAgentWithPlayerDose().
CalculateHealth()
void PluginBase::CalculateHealth (PlayerBase player, ItemBase kit, Object item, float specialty_weight, string damage_zone = "", bool use_kit_qty = true) inline private
Definition at line 27 of file PluginRepairing.c.
  {
    EntityAI entity;
    Class.CastTo(entity, item);
    if (entity != null)
      entity.SetAllowDamage(true);
    bool kit_has_quantity = kit.HasQuantity();
    int health_levels_count = item.GetNumberOfHealthLevels(damage_zone);
    float cur_kit_quantity = kit.GetQuantity();
    float kit_repair_cost_per_level = GetKitRepairCost(kit, item);
    float kit_repair_cost_adjusted; //used with specialty_weight, disconnected
    float new_quantity;
    int target_level = Math.Clamp(item.GetHealthLevel(damage_zone) - 1, 0, health_levels_count - 1);
    float health_coef;
    if (!CanRepairToPristine(player) && !CanBeRepairedToPristine(item))
      target_level = Math.Clamp(target_level, GameConstants.STATE_WORN, health_levels_count - 1);
    health_coef = item.GetHealthLevelValue(target_level, damage_zone);
    //handles kit depletion; TODO: move to separate method.
    if (cur_kit_quantity > kit_repair_cost_per_level)
    {
      kit_repair_cost_adjusted = kit_repair_cost_per_level; //TODO: removed speciality weight for now, it should affect speed only (?).
      //kit_repair_cost_adjusted = player.GetSoftSkillsManager().SubtractSpecialtyBonus( kit_repair_cost_per_level, specialty_weight );
      kit_repair_cost_adjusted = Math.Clamp(kit_repair_cost_adjusted, 0, 100);
      if (use_kit_qty)
      {
        new_quantity = kit.GetQuantity() - kit_repair_cost_adjusted;
        kit.SetQuantity(new_quantity);
      }
    }
    else if (!kit_has_quantity) //"kit" without quantity (hammers and such) for your every day repairing needs
    {
    }
    else
    {
      if (use_kit_qty)
        kit.SetQuantity(0);
    }
    if (item.GetHealth01(damage_zone, "Health") < health_coef)
      item.SetHealth01(damage_zone, "Health", health_coef);
    if (entity != null)
      entity.ProcessInvulnerabilityCheck(entity.GetInvulnerabilityTypeString());
  }
References Class::CastTo(), Math::Clamp(), and GameConstants::STATE_WORN.
CalculatePos()
vector PluginBase::CalculatePos () inline private
Definition at line 69 of file PluginCharPlacement.c.
  {
    vector cam_pos = FreeDebugCamera.GetInstance().GetPosition();
    Math3D.MatrixIdentity4(m_cameraTrans);
    Math3D.DirectionAndUpMatrix(m_camera_dir/* - SnapToGround(cam_pos)*/, "0 1 0", m_cameraTrans);
    m_cameraTrans[3] = cam_pos;
    m_demoPos = Vector(/*0.685547, -0.988281,*/0, 0, 3.68823).Multiply4(m_cameraTrans);
    m_demoPos[1] = GetGame().SurfaceY(m_demoPos[0], m_demoPos[2]);
    return m_demoPos;
  }
References Math3D::DirectionAndUpMatrix(), GetGame(), Math3D::MatrixIdentity4(), and Vector().
CanBeRepairedToPristine()
bool PluginBase::CanBeRepairedToPristine (Object item) inline private
Item can be repaired to 100%.
Definition at line 114 of file PluginRepairing.c.
  {
    return item.CanBeRepairedToPristine();
  }
CanRepair()
bool PluginBase::CanRepair (ItemBase repair_kit, Object item, string damage_zone = "") inline private
Definition at line 76 of file PluginRepairing.c.
  {
    int state = item.GetHealthLevel(damage_zone);
    if (state != GameConstants.STATE_RUINED && (item.CanBeRepairedToPristine() && state >= GameConstants.STATE_WORN) || (!item.CanBeRepairedToPristine() && state >= GameConstants.STATE_DAMAGED))
    {
      int repair_kit_type = repair_kit.ConfigGetInt("repairKitType");
      array<int> repairable_with_types = new array<int>;
      item.ConfigGetIntArray("repairableWithKits", repairable_with_types);
      for (int i = 0; i < repairable_with_types.Count(); i++)
      {
        int repairable_with_type = repairable_with_types.Get(i);
        if (IsRepairValid(repair_kit_type, repairable_with_type))
          return true;
      }
    }
    return false;
  }
References GameConstants::STATE_DAMAGED, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
CanRepairToPristine()
bool PluginBase::CanRepairToPristine (PlayerBase player) inline private
Player can repair items to 100%; currently unused.
Definition at line 108 of file PluginRepairing.c.
  {
    return false;
  }
CaptureFocus() [1/2]
void PluginBase::CaptureFocus () inline private
Definition at line 139 of file PluginDayZInfectedDebug.c.
  {
    if (!m_HasFocus)
    {
      GetGame().GetInput().ChangeGameFocus(1);
      GetGame().GetUIManager().ShowUICursor(true);
      m_HasFocus = true;
    }
  }
References GetGame(), and m_HasFocus.
Referenced by ToggleDebugWindowEventP(), ToggleDebugWindowSetMode(), and ToggleDebugWindowSetMode().
CaptureFocus() [2/2]
void PluginBase::CaptureFocus () inline private
Definition at line 793 of file PluginDeveloperSync.c.
  {
    GetGame().GetInput().ChangeGameFocus(1);
    GetGame().GetUIManager().ShowUICursor(true);
  }
References GetGame().
CheckInit() [1/2]
void PluginBase::CheckInit () inline private
Definition at line 17 of file PluginCharPlacement.c.
  {
    if (m_Initialized)
    {
      Print("logging...");
      Log(FOV.ToString(), "FOV");
      Log(m_camera_dir.ToString(), "camera dir");
      Log(m_cam_pos.ToString(), "camera pos");
      Log(m_demoPos.ToString(), "character pos");
      return;
    }
    if (FreeDebugCamera.GetInstance().IsActive())
      Init();
  }
References Init(), Log(), m_Initialized, Print(), float::ToString(), and vector::ToString().
CheckInit() [2/2]
void PluginBase::CheckInit () inline private
Definition at line 8 of file PluginDoorRuler.c.
  {
    if (FreeDebugCamera.GetInstance().IsActive())
      Init();
  }
References Init().
CheckMask()
bool PluginBase::CheckMask (int source_mask, int target_mask) inline protected
Definition at line 316 of file PluginKeyBinding.c.
  {
    if ((source_mask & target_mask) == target_mask)
      return true;
    return false;
  }
CleanupDebugShapes()
void PluginBase::CleanupDebugShapes (array< Shape > shapesArr) inline private
Definition at line 471 of file PluginDayZInfectedDebug.c.
  {
    for (int it = 0; it < shapesArr.Count(); ++it)
      Debug.RemoveShape(shapesArr[it]);
    shapesArr.Clear();
  }
References Debug::RemoveShape().
Referenced by OnUpdate(), and ToggleDebugWindowSetMode().
ClearFileNoSave()
void PluginBase::ClearFileNoSave () inline private
Definition at line 52 of file PluginFileHandler.c.
  {
    m_FileContent.Clear();
  }
ClearInventory()
void PluginBase::ClearInventory (EntityAI entity) inline protected
Definition at line 697 of file PluginDeveloper.c.
  {
    if (GetGame().IsServer())
      entity.ClearInventory();
    else
    {
      Param1<int> params = new Param1<int>(0);
      entity.RPCSingleParam(ERPCs.DEV_RPC_CLEAR_INV, params, true);
    }
  }
References GetGame().
CommandHandler()
void PluginBase::CommandHandler (DayZInfected infected) inline protected
Definition at line 376 of file PluginDayZInfectedDebug.c.
  {
    if (infected != m_ControlledInfected)
      return;
    infected.GetInputController().OverrideMovementSpeed(true, m_MovementSpeedEB.GetText().ToFloat());
    DayZInfectedCommandMove moveCommand = infected.GetCommand_Move();
    if (moveCommand)
    {
      moveCommand.SetStanceVariation(m_StanceCB.GetCurrentItem());
      moveCommand.SetIdleState(m_MindStateCB.GetCurrentItem());
    }
    if (m_CH_DoTurn)
    {
      moveCommand.StartTurn(m_TurnDirectionEB.GetText().ToFloat(), m_TurnTypeCB.GetCurrentItem());
      m_CH_DoTurn = false;
    }
    if (m_CH_DoVault)
    {
      infected.StartCommand_Vault(m_VaultingCB.GetCurrentItem());
      m_CH_DoVault = false;
    }
    if (m_CH_DoKnucleOut)
    {
      infected.StartCommand_Vault(-1);
      m_CH_DoKnucleOut = false;
    }
    if (m_CH_GoToCrawl)
    {
      infected.StartCommand_Crawl(m_CrawlingTypeCB.GetCurrentItem());
      m_CH_GoToCrawl = false;
    }
    if (m_CH_DoHit)
    {
      float hitDir = m_HitDirEB.GetText().ToFloat();
      int bodyPart = m_HitBodyPartCB.GetCurrentItem();
      bool heavyHit = m_HitTypeCB.GetCurrentItem() == 1;
      infected.StartCommand_Hit(heavyHit, bodyPart, hitDir);
      m_CH_DoHit = false;
    }
    if (m_CH_StartDeath)
    {
      int deathType = m_DeathTypeCB.GetCurrentItem();
      float deathDir = m_HitDirEB.GetText().ToFloat();
      infected.StartCommand_Death(deathType, deathDir);
      m_CH_StartDeath = false;
    }
    if (m_CH_DoAttack)
    {
      float attackDir = m_AttackDirCB.GetCurrentItem();
      int attackType = m_AttackDescriptors.Get(m_AttackTypeCB.GetCurrentItem()).animValue;
      infected.StartCommand_Attack(null, attackType, attackDir);
      m_CH_DoAttack = false;
    }
  }
ConstructSimpleAgentList()
void PluginBase::ConstructSimpleAgentList () inline private
Definition at line 32 of file PluginTransmissionAgents.c.
  {
    string agent_name;
    int agent_type;
    for (int i = 0; i < m_AgentList.Count(); i++)
    {
      AgentBase agent = m_AgentList.GetElement(i);
      agent_name = agent.GetName();
      agent_type = agent.GetAgentType();
      m_SimpleAgentList.Insert(agent_type, agent_name);
    }
  }
Referenced by GetSimpleAgentList().
ContainsFirstClass()
bool PluginBase::ContainsFirstClass (string config_class_path, string class_path) inline private
Definition at line 90 of file PluginConfigViewer.c.
  {
    int start = class_path.IndexOf(" ");
    string name = class_path;
    if (start > -1)
      name = class_path.Substring(0, start);
    int cfg_class_count = GetGame().ConfigGetChildrenCount(config_class_path);
    for (int i = 0; i < cfg_class_count; i++)
    {
      string cfg_class_name = "";
      GetGame().ConfigGetChildName(config_class_path, i, cfg_class_name);
      if (cfg_class_name == name)
      {
        string full_name = config_class_path + " " + name;
        int type = GetGame().ConfigGetType(full_name);
        if (type == CT_CLASS)
          return true;
      }
    }
    if (start == -1)
      return false;
    else
    {
      string new_name = class_path.Substring(start + 1, class_path.Length() - (start + 1));
      return ContainsFirstClass(config_class_path + " " + name, new_name);
    }
  }
References ContainsFirstClass(), GetGame(), and name.
Referenced by ContainsFirstClass(), and GetBaseClassPathRecursive().
CreateModuleWidgets()
void PluginBase::CreateModuleWidgets () inline private
main controls
movement card
fight card
fill some controls
Definition at line 210 of file PluginDayZInfectedDebug.c.
  {
    if (!m_pUIHandler)
    {
      m_pUIHandler = new PluginDayZInfectedDebugUIHandler();
      m_pUIHandler.m_pPluginInfectedDebug = this;
    }
    if (!m_MainWnd)
    {
      m_MainWnd = GetGame().GetWorkspace().CreateWidgets("gui/layouts/debug/day_z_infecteddebug.layout");
      m_MainWnd.SetHandler(m_pUIHandler);
      m_MainWnd.Show(false);
    }
    m_SpawnEntityButton = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("SpawnEntityButton"));
    m_CardMovementButton = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("CardMovementButton"));
    m_CardFightButton = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("CardFightButton"));
    m_CardMovementFrame = m_MainWnd.FindAnyWidget("CardMovementFrame");
    m_CardFightFrame = m_MainWnd.FindAnyWidget("CardFightFrame");
    m_StatusText = TextWidget.Cast(m_MainWnd.FindAnyWidget("StatusText"));
    m_StanceCB = XComboBoxWidget.Cast(m_MainWnd.FindAnyWidget("StanceCB"));
    m_MindStateCB = XComboBoxWidget.Cast(m_MainWnd.FindAnyWidget("MindStateCB"));
    m_MovementSpeedEB = EditBoxWidget.Cast(m_MainWnd.FindAnyWidget("MovementSpeedEB"));
    m_StartTurnButton = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("StartTurnButton"));
    m_TurnTypeCB = XComboBoxWidget.Cast(m_MainWnd.FindAnyWidget("TurnTypeCB"));
    m_TurnDirectionEB = EditBoxWidget.Cast(m_MainWnd.FindAnyWidget("TurnDirectionEB"));
    m_VaultingCB = XComboBoxWidget.Cast(m_MainWnd.FindAnyWidget("TurnTypeCB"));
    m_StartVaultButton = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("StartVaultButton"));
    m_KnucleOutButton = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("KnucleOutButton"));
    m_CrawlingTypeCB = XComboBoxWidget.Cast(m_MainWnd.FindAnyWidget("TurnTypeCB"));
    m_StartCrawlingButton = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("StartCrawlingButton"));
    m_HitDirEB = EditBoxWidget.Cast(m_MainWnd.FindAnyWidget("HitDirEB"));
    m_HitTypeCB = XComboBoxWidget.Cast(m_MainWnd.FindAnyWidget("HitTypeCB"));
    m_HitBodyPartCB = XComboBoxWidget.Cast(m_MainWnd.FindAnyWidget("HitBodyPartCB"));
    m_StartHitButton = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("StartHitButton"));
    m_DeathTypeCB = XComboBoxWidget.Cast(m_MainWnd.FindAnyWidget("DeathTypeCB"));
    m_StartDeathButton = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("StartDeathButton"));
    m_AttackTypeCB = XComboBoxWidget.Cast(m_MainWnd.FindAnyWidget("AttackTypeCB"));
    m_AttackDirCB = XComboBoxWidget.Cast(m_MainWnd.FindAnyWidget("AttackDirCB"));
    m_StartAttackButton = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("StartAttackButton"));
    InitAttacks();
    ShowCard(0);
  }
References GetGame(), InitAttacks(), m_MainWnd, m_pUIHandler, and ShowCard().
Referenced by PluginDayZInfectedDebug(), and PluginDayzPlayerDebug().
CreateWidgetOverlay()
void PluginBase::CreateWidgetOverlay () inline private
row counter
sets alpha level for even/odd child
Definition at line 16 of file PluginDrawCheckerboard.c.
  {
#ifndef NO_GUI
    if (!m_MainWindow)
    {
      m_MainWindow = GetGame().GetWorkspace().CreateWidgets("gui/layouts/camera_checkerboard.layout");
      m_MainWindow.Show(false);
      int childId = 0;
      int row = 0;
      bool evenOrOdd;
      int tilesPerLine = 8;
      Widget child = m_MainWindow.GetChildren();
      while (child)
      {
        evenOrOdd = IsEven(childId);
        if (childId > (tilesPerLine * row) - 1)
          row++;
        if (IsEven(row))
          evenOrOdd = !evenOrOdd;
        if (evenOrOdd)
          child.SetAlpha(0.15);
        else
          child.SetAlpha(0.05);
        child = child.GetSibling();
        childId++;
      }
    }
#endif
  }
References GetGame(), and IsEven().
Referenced by PluginDrawCheckerboard().
CursorHide()
void PluginBase::CursorHide () inline protected
Definition at line 31 of file PluginCameraTools.c.
  {
    if (GetGame().GetUIManager().GetMenu())
      GetGame().GetUIManager().GetMenu().OnHide();
  }
References GetGame().
CursorShow()
void PluginBase::CursorShow () inline protected
Definition at line 40 of file PluginCameraTools.c.
  {
    if (GetGame().GetUIManager().GetMenu())
      GetGame().GetUIManager().GetMenu().OnShow();
  }
References GetGame().
DeactivateModifier()
void PluginBase::DeactivateModifier (int id, PlayerBase player = NULL) inline private
Definition at line 626 of file PluginDeveloperSync.c.
  {
    if (!player)
      player = PlayerBase.Cast(GetDayZGame().GetPlayer());
    ModifiersManager mods_manager = player.GetModifiersManager();
    mods_manager.DeactivateModifier(Math.AbsInt(id));
  }
References Math::AbsInt(), GetDayZGame(), GetPlayer(), and ModifiersManager().
Referenced by OnRPC().
Decay()
void PluginBase::Decay () inline private
Definition at line 57 of file PluginObjectsInteractionManager.c.
  {
    if (m_LockedObjectsDecay.Count() > 0)
    {
      for (int i = 0; i < m_LockedObjectsDecay.Count(); i++)
      {
        if (m_LockedObjectsDecay.Get(i) >= TIME_TO_FORCED_UNLOCK)
        {
          m_LockedObjects.Remove(i);
          m_LockedObjectsDecay.Remove(i);
        }
        else
          m_LockedObjectsDecay.Get(i) += TICK_RATE;
      }
    }
  }
References TICK_RATE.
DeleteKeyframe()
void PluginBase::DeleteKeyframe () inline protected
Definition at line 64 of file PluginCameraTools.c.
  {
    if (GetGame().GetUIManager().GetMenu())
      GetGame().GetUIManager().GetMenu().OnKeyPress(null, 0, 0, KeyCode.KC_E);
  }
References GetGame().
DeleteSceneObject()
void PluginBase::DeleteSceneObject (SceneObject obj) inline private
Definition at line 1015 of file PluginSceneManager.c.
  {
    if (obj != NULL)
    {
      if (obj.GetObject() != GetGame().GetPlayer())
      {
        obj.UnlinkAll();
        if (GetSelectedSceneObject() != NULL && GetSelectedSceneObject() == obj)
          DeselectObject();
        m_SceneData.DeleteSceneObject(obj);
      }
      else
        SceneEditorMenuCmdPopup("You cant delete player!");
    }
    EditorUpdate();
  }
References GetGame(), SceneObject::GetObject(), GetPlayer(), and SceneObject::UnlinkAll().
DeleteSelectedObject()
void PluginBase::DeleteSelectedObject () inline private
Definition at line 411 of file PluginSceneManager.c.
  {
    SceneObject selected_obj = GetSelectedSceneObject();
    if (selected_obj != NULL)
    {
      if (!selected_obj.IsPlayer())
      {
        array<ref SceneObject> scene_objects = GetSceneObjects();
        for (int i = 0; i < scene_objects.Count(); i++)
        {
          if (AreSceneObjectsLinked(scene_objects.Get(i), selected_obj))
            UnlinkSceneObjects(scene_objects.Get(i), selected_obj);
        }
        m_SceneData.DeleteSceneObject(selected_obj);
        scene_objects.RemoveItem(selected_obj);
        DeselectObject();
      }
      else
        SceneEditorMenuCmdPopup("You cant delete player!");
    }
    EditorUpdate();
  }
DeselectObject()
void PluginBase::DeselectObject () inline private
Definition at line 1057 of file PluginSceneManager.c.
  {
    m_SelectedObject = NULL;
  }
References m_SelectedObject.
DestroyModuleWidgets()
void PluginBase::DestroyModuleWidgets () inline private
Definition at line 269 of file PluginDayZInfectedDebug.c.
  {
    delete m_MainWnd;
  }
References m_MainWnd.
Referenced by ~PluginDayZInfectedDebug(), and ~PluginDayzPlayerDebug().
DetermineChanceToTransmit()
bool PluginBase::DetermineChanceToTransmit (int agent_id, float protection, int inject_type) inline protected
Definition at line 371 of file PluginTransmissionAgents.c.
  {
    //Debug.Log("protection: "+protection.ToString());
    float prot = 1 - protection; //reverse the value (in config, the higher the value, the higher the protection: 0 - 1) so that we can easily interpolate between 0 and 1 by multiplication
    //Debug.Log("prot: "+prot.ToString(), "Agents");
    float transf;
    if (inject_type == InjectTypes.PLAYER_TO_ITEM)
      transf = GetAgentTransferabilityOut(agent_id);
    else if (inject_type == InjectTypes.ITEM_TO_PLAYER)
      transf = GetAgentTransferabilityIn(agent_id);
    else if (inject_type == InjectTypes.PLAYER_AIR_PLAYER)
      transf = GetAgentTransferabilityAirOut(agent_id);
#ifdef DEVELOPER
    //Debug.Log("transf: "+transf.ToString(), "Agents");
#endif
    //float result =  GetAgentInitialCount(agent_id) * prot * transf * dose_size;//final formula
    bool dice = Math.RandomFloat01() < (prot * transf);
    //result = Math.Ceil(result);
    return dice;
  }
References GetAgentTransferabilityAirOut(), GetAgentTransferabilityIn(), GetAgentTransferabilityOut(), and Math::RandomFloat01().
Referenced by InjectAgentsWithPlayer().
DirectAdminLogPrint()
void PluginBase::DirectAdminLogPrint (string str) inline protected
Definition at line 368 of file PluginAdminLog.c.
  {
    LogPrint(str);
  }
References LogPrint().
DisplayTendency()
void PluginBase::DisplayTendency (int key, int tendency, int status = 1) inline private
Definition at line 42 of file PluginPlayerStatus.c.
  {
    if (key)
    {
      // display icon
      int icon_index = 0; // maybe we'll have several icons for different tendencies
      if (m_NotifiersIcons.HasKey(key))
      {
        string icon_name = m_NotifiersIcons.Get(key).Get(icon_index);
        Mission mission = GetGame().GetMission();
        if (mission)
        {
          Hud hud = mission.GetHud();
          if (hud)
            hud.DisplayNotifier(key, tendency, status);
        }
      }
    }
  }
References GetGame(), Mission::GetHud(), and mission.
DrawDebugs()
void PluginBase::DrawDebugs () inline protected
Definition at line 48 of file PluginUniversalTemperatureSourceClient.c.
  {
    foreach (UTemperatureSourceDebug utsd : m_UTemperatureSourceDebugs)
    {
      float fullRange = utsd.GetValue(1).ToFloat();
      float maxRange = utsd.GetValue(2).ToFloat();
      float temp = utsd.GetValue(3).ToFloat();
      vector sphPos = utsd.GetValue(0).ToVector();
      int fullRangeColor = COLOR_RED_A;
      int maxRangeColor = COLOR_YELLOW_A;
      if (temp < 0)
      {
        fullRangeColor = COLOR_GREEN_A;
        maxRangeColor = COLOR_BLUE_A;
      }
      Debug.DrawCylinder(sphPos, fullRange, fullRange, fullRangeColor, ShapeFlags.ONCE | ShapeFlags.TRANSP);
      Debug.DrawCylinder(sphPos, maxRange, maxRange, maxRangeColor, ShapeFlags.ONCE | ShapeFlags.TRANSP);
      Debug.DrawArrow(m_Player.GetPosition(), sphPos, 1.0, 0xffffffff, ShapeFlags.ONCE | ShapeFlags.TRANSP);
    }
    ProcessUniversalTemperatureSources();
    if (m_UTemperatureSourceDebugs.Count() > 0)
    {
      DbgUI.Begin("Universal Temp Sources", 10, 300);
      DbgUI.Text(string.Format("Lookup radius: %1m (server-side)", PluginUniversalTemperatureSourceServer.LOOKUP_RADIUS));
      DbgUI.Text(string.Format("Count: %1", m_UTemperatureSourceDebugs.Count()));
      DbgUI.Text(string.Format("Avg. temp: %1 C", m_UTSAverageTemperature));
      DbgUI.End();
    }
  }
References DbgUI::Begin(), COLOR_BLUE_A, COLOR_GREEN_A, COLOR_RED_A, COLOR_YELLOW_A, Debug::DrawArrow(), Debug::DrawCylinder(), DbgUI::End(), m_Player, m_UTemperatureSourceDebugs, ProcessUniversalTemperatureSources(), and DbgUI::Text().
Referenced by OnUpdate().
EditorToggle()
void PluginBase::EditorToggle () inline private
Definition at line 342 of file PluginSceneManager.c.
  {
    //Log("EditorToggle");
    if (GetGame().IsMultiplayer())
      return;
    if (IsOpened())
    {
      // Close UI Scene Editor Menu
      GetGame().GetUIManager().Back();
    }
    else
    {
      // Open UI Scene Editor Menu
      GetGame().GetUIManager().EnterScriptedMenu(MENU_SCENE_EDITOR, NULL);
      EditorUpdate();
    }
  }
References GetGame(), IsOpened(), and MENU_SCENE_EDITOR.
EditorUpdate()
void PluginBase::EditorUpdate () inline protected
Definition at line 1065 of file PluginSceneManager.c.
  {
    if (GetGame().IsMultiplayer())
      return;
    array<ref SceneObject> objects = GetSceneObjects();
    if (!objects)
      return;
    for (int i = 0; i < objects.Count(); ++i)
    {
      SceneObject obj = objects.Get(i);
      array<SceneObject> linked_scene_objects = obj.GetLinkedSceneObjects();
      int j;
      if (IsOpened())
      {
        obj.EditorShapeAdd();
        if (GetSelectedSceneObject() && GetSelectedSceneObject() == obj)
        {
          if (GetDrawSelection())
            obj.EditorShapeSelect();
        }
        else
          obj.EditorShapeDeselect();
        for (j = 0; j < linked_scene_objects.Count(); j++)
          obj.EditorLineAdd(linked_scene_objects.Get(j));
      }
      else
      {
        obj.EditorShapeRemove();
        if (linked_scene_objects)
        {
          for (j = 0; j < linked_scene_objects.Count(); j++)
            obj.EditorLineRemove(linked_scene_objects.Get(j));
        }
      }
    }
    SceneEditorMenuCmdRefresh();
  }
References SceneObject::EditorLineAdd(), SceneObject::EditorLineRemove(), SceneObject::EditorShapeAdd(), SceneObject::EditorShapeDeselect(), SceneObject::EditorShapeRemove(), SceneObject::EditorShapeSelect(), GetGame(), SceneObject::GetLinkedSceneObjects(), and IsOpened().
EditorUpdateRuler()
void PluginBase::EditorUpdateRuler () inline private
Definition at line 1150 of file PluginSceneManager.c.
  {
    RulerClearVisuals();
    for (int i = 0; i < m_RulerPoints.Count(); ++i)
    {
      vector pos1 = m_RulerPoints.Get(i);
      m_RulerSpheres.Insert(Debug.DrawSphere(pos1, 0.1));
      if (i < m_RulerPoints.Count() - 1)
      {
        vector pos2 = m_RulerPoints.Get(i + 1);
        m_RulerLines.Insert(Debug.DrawLine(pos1, pos2));
      }
    }
  }
References Debug::DrawLine(), and Debug::DrawSphere().
EnableUpdate()
void PluginBase::EnableUpdate (bool enable, int type, PlayerBase player) inline private
Definition at line 76 of file PluginDeveloperSync.c.
  {
    //set update by type
    if (!IsPlayerRegistered(player))
      RegisterPlayer(player);
    switch (type)
    {
    case ERPCs.DEV_STATS_UPDATE:
    {
      SetSystemInBitmask(player, PDS_SYSTEMS.STATS, enable);
      break;
    }
    case ERPCs.DEV_LEVELS_UPDATE:
    {
      SetSystemInBitmask(player, PDS_SYSTEMS.LEVELS, enable);
      break;
    }
    case ERPCs.DEV_MODS_UPDATE:
    {
      SetSystemInBitmask(player, PDS_SYSTEMS.MODS, enable);
      break;
    }
    case ERPCs.DEV_AGENTS_UPDATE:
    {
      SetSystemInBitmask(player, PDS_SYSTEMS.AGENTS, enable);
      break;
    }
    case ERPCs.DEV_STOMACH_UPDATE:
    {
      SetSystemInBitmask(player, PDS_SYSTEMS.STOMACH, enable);
      break;
    }
    case ERPCs.DEV_TEMP_UPDATE:
    {
      SetSystemInBitmask(player, PDS_SYSTEMS.TEMPERATURE, enable);
      break;
    }
    }
    //remove players with empty mask
    for (int i = 0; i < m_RegisteredPlayers.Count(); i++)
    {
      if (m_RegisteredPlayers.GetElement(i).m_Bitmask == 0)
      {
        m_RegisteredPlayers.RemoveElement(i);
        i = 0;
      }
    }
    //start/stop the tick based on existence/absence of players registered
    if (m_UpdateTimer)
    {
      if (m_RegisteredPlayers.Count() == 0)
        m_UpdateTimer.Stop();
      else if (!m_UpdateTimer.IsRunning())
        m_UpdateTimer.Run(1, this, "Update", NULL, true);
    }
  }
References IsPlayerRegistered(), m_UpdateTimer, RegisterPlayer(), and SetSystemInBitmask().
Referenced by OnRPC(), and OnRPCTemp().
EnableWidgets()
void PluginBase::EnableWidgets (bool enable) inline protected
Definition at line 134 of file PluginUniversalTemperatureSourceClient.c.
  {
    for (int i = 0; i < MAX_SIMULTANEOUS_UTS; i++)
      m_RootWidget[i].Show(enable);
  }
References m_RootWidget, MAX_SIMULTANEOUS_UTS, and Show().
Referenced by RequestUniversalTemperatureSources().
Event_OnClick()
void PluginBase::Event_OnClick () inline private
Definition at line 108 of file PluginSceneManager.c.
  {
    if (!IsMouseInScene() || !m_IsOpen)
      return;
    // Direction Vector from current active Camera
    vector dir = GetGame().GetPointerDirection();
    // Raycast from
    vector from = FreeDebugCamera.GetInstance().GetPosition();
    // Raycast to
    vector to = from + (dir * 10000);
    // Raycast out parameter
    vector contact_pos;
    vector contact_dir;
    int contact_component;
    set<Object> objects = new set<Object>;
    bool selected = false;
    if (DayZPhysics.RaycastRV(from, to, contact_pos, contact_dir, contact_component, objects))
    {
      for (int i = 0; i < objects.Count(); ++i)
      {
        Object obj = objects.Get(i);
        if (obj.IsInherited(EntityAI))
        {
          SceneObject sc_object = SceneObject.Cast(m_SceneData.GetSceneObjectByEntityAI(EntityAI.Cast(obj)));
          if (sc_object == NULL)
          {
            //sc_object = m_SceneData.AddObject(obj);
            return;
          }
          SelectObject(sc_object);
          selected = true;
          break;
        }
      }
    }
    if (!selected)
    {
      DeselectObject();
      // Ruler
      if (IsRulerActivated() && GetSelectedSceneObject() == NULL)
        RulerAddPoint();
    }
    EditorUpdate();
  }
References GetGame(), and DayZPhysics::RaycastRV().
Event_OnClickMiddle()
void PluginBase::Event_OnClickMiddle () inline private
Definition at line 166 of file PluginSceneManager.c.
  {
    if (!IsMouseInScene() || !m_IsOpen)
      return;
    if (GetSelectedSceneObject() != NULL)
    {
      // Direction Vector from current active Camera
      vector dir = GetGame().GetPointerDirection();
      // Raycast from
      vector from = FreeDebugCamera.GetInstance().GetPosition();
      // Raycast to
      vector to = from + (dir * 10000);
      // Raycast out parameter
      vector contact_pos;
      vector contact_dir;
      int contact_component;
      set<Object> objects = new set<Object>;
      bool selected = false;
      if (DayZPhysics.RaycastRV(from, to, contact_pos, contact_dir, contact_component, objects))
      {
        for (int i = 0; i < objects.Count(); ++i)
        {
          Object obj = objects.Get(i);
          if (obj.IsInherited(EntityAI))
          {
            EntityAI eai = EntityAI.Cast(obj);
            SceneObject scene_object = m_SceneData.GetSceneObjectByEntityAI(eai);
            if (!scene_object.IsPlayer())
            {
              if (scene_object != NULL && scene_object != GetSelectedSceneObject())
              {
                if (!AreSceneObjectsLinked(GetSelectedSceneObject(), scene_object))
                  LinkSceneObjects(GetSelectedSceneObject(), scene_object);
                else
                  UnlinkSceneObjects(GetSelectedSceneObject(), scene_object);
              }
            }
            else
              SceneEditorMenuCmdPopup("I am sorry. You cant create link on player!");
          }
        }
      }
    }
    EditorUpdate();
  }
References GetGame(), and DayZPhysics::RaycastRV().
Event_OnDoubleClick()
SceneObject PluginBase::Event_OnDoubleClick () inline private
Definition at line 252 of file PluginSceneManager.c.
  {
    if (!IsMouseInScene() || !m_IsOpen || m_ClassBrowserSelected == "")
      return null;
    // Direction Vector from current active Camera
    vector dir = GetGame().GetPointerDirection();
    // Raycast from
    vector from = FreeDebugCamera.GetInstance().GetPosition();
    // Raycast to
    vector to = from + (dir * 10000);
    // Raycast out parameter
    vector contact_pos;
    vector contact_dir;
    int contact_component;
    if (DayZPhysics.RaycastRV(from, to, contact_pos, contact_dir, contact_component))
    {
      SceneObject obj = m_SceneData.CreateSceneObject(m_ClassBrowserSelected, contact_pos);
      if (obj != NULL)
      {
        SelectObject(obj);
        return obj;
      }
    }
    return NULL;
  }
References GetGame(), and DayZPhysics::RaycastRV().
Event_OnDrag()
void PluginBase::Event_OnDrag () inline private
Definition at line 221 of file PluginSceneManager.c.
  {
    if (!IsMouseInScene() || !m_IsOpen)
      return;
    if (GetSelectedSceneObject() != NULL)
    {
      // Direction Vector from current active Camera
      vector dir = GetGame().GetPointerDirection();
      // Raycast from
      vector from = FreeDebugCamera.GetInstance().GetPosition();
      // Raycast to
      vector to = from + (dir * 10000);
      // Raycast out parameter
      vector contact_pos;
      vector contact_dir;
      int contact_component;
      //Raycast(vector begPos, vector endPos, out vector contactPos, out vector contactDir, out int contactComponent, out set<Object> results = NULL, Object with = NULL, Object ignore = NULL,  bool sorted = false,  bool ground_only = false,  int iType = ObjIntersectView, float radius = 0.0);
      if (DayZPhysics.RaycastRV(from, to, contact_pos, contact_dir, contact_component, NULL, NULL, NULL, false, true))
        GetSelectedSceneObject().SetPosition(contact_pos);
      EditorUpdate();
    }
  }
References GetGame(), and DayZPhysics::RaycastRV().
ExecuteEnforceScript()
void PluginBase::ExecuteEnforceScript (int index, SceneObject scene_object, string script) inline private
Definition at line 842 of file PluginSceneManager.c.
  {
    if (script != "")
    {
      string cls = scene_object.GetObject().ClassName();
      string wrapped_script = "void scMngMain() \n{\n PluginSceneManager se = GetPlugin(Type(\"PluginSceneManager\")); \n SceneObject this_obj = se.GetSceneObjectByIndex(" + index.ToString() + "); \n " + cls + " this_eai = this_obj.GetObject(); \n " + script + "\n}\n";
      GetGame().ExecuteEnforceScript(wrapped_script, "scMngMain");
    }
  }
References GetGame().
ExecuteInitScripts()
void PluginBase::ExecuteInitScripts () inline private
Definition at line 329 of file PluginSceneManager.c.
  {
    array<ref SceneObject> scene_objects = GetSceneObjects();
    for (int i = 0; i < scene_objects.Count(); i++)
    {
      SceneObject scene_object = scene_objects.Get(i);
      ExecuteEnforceScript(i, scene_object, scene_object.GetInitScript());
    }
  }
FileDelete()
static bool PluginBase::FileDelete (string file) inline static private
Definition at line 8 of file PluginFileHandler.c.
  {
    return DeleteFile(file);
  }
References DeleteFile().
FileDuplicate()
static bool PluginBase::FileDuplicate (string source_name, string dest_name) inline static private
Definition at line 3 of file PluginFileHandler.c.
  {
    return CopyFile(source_name, dest_name);
  }
References CopyFile().
FileRename()
static void PluginBase::FileRename (string source_name, string dest_name) inline static private
Definition at line 13 of file PluginFileHandler.c.
  {
    FileDuplicate(source_name, dest_name);
    FileDelete(source_name);
  }
FreeCameraControlDisable()
void PluginBase::FreeCameraControlDisable () inline private
Definition at line 396 of file PluginSceneManager.c.
  {
    // Disable Camera control
    GetGame().GetInput().ChangeGameFocus(1);
    // Enable Cursor
    GetGame().GetUIManager().ShowUICursor(true);
    if (GetGame().GetUIManager().GetMenu())
      GetGame().GetUIManager().GetMenu().OnShow();
  }
References GetGame().
FreeCameraControlEnable()
void PluginBase::FreeCameraControlEnable () inline private
Definition at line 381 of file PluginSceneManager.c.
  {
    // Enable Camera control
    GetGame().GetInput().ChangeGameFocus(-1);
    // Disable Cursor
    GetGame().GetUIManager().ShowUICursor(false);
    if (GetGame().GetUIManager().GetMenu())
      GetGame().GetUIManager().GetMenu().OnHide();
  }
References GetGame().
GatherPlayerInfo()
void PluginBase::GatherPlayerInfo () inline private
Definition at line 39 of file PluginRemotePlayerDebugServer.c.
  {
    array<Man> players = new array<Man>;
    GetGame().GetPlayers(players);
    m_PlayerDebugStats.Clear();
    foreach (Man playerMan : players)
    {
      PlayerBase player = PlayerBase.Cast(playerMan);
      RemotePlayerStatDebug rpd = new RemotePlayerStatDebug(player);
      m_PlayerDebugStats.Insert(rpd);
    }
  }
References GetGame(), m_PlayerDebugStats, and RemotePlayerStatDebug().
GatherTemperatureSources()
void PluginBase::GatherTemperatureSources (PlayerBase player) inline protected
Definition at line 31 of file PluginUniversalTemperatureSourceServer.c.
  {
    m_UTemperatureSourceDebugs.Clear();
    if (!player)
      return;
    vector playerPos = player.GetPosition();
    array<Object> nearestObjects = new array<Object>();
    GetGame().GetObjectsAtPosition(playerPos, LOOKUP_RADIUS, nearestObjects, null);
    UTemperatureSource uts;
    UTemperatureSourceDebug utsd;
    foreach (Object nearestObject : nearestObjects)
    {
      EntityAI ent = EntityAI.Cast(nearestObject);
      if (ent && ent.IsUniversalTemperatureSource() && ent != player)
      {
        uts = ent.GetUniversalTemperatureSource();
        utsd = new UTemperatureSourceDebug();
        utsd.AddHeader(ent.GetType());
        utsd.Add("position", uts.GetPosition().ToString(false));
        utsd.Add("fullrange", uts.GetFullRange().ToString());
        utsd.Add("maxrange", uts.GetMaxRange().ToString());
        utsd.Add("temperature", uts.GetTemperature().ToString());
        utsd.Add("temperatureraw", uts.GetTemperatureRaw().ToString());
        utsd.Commit();
        m_UTemperatureSourceDebugs.Insert(utsd);
      }
    }
    if (player.GetItemInHands() && player.GetItemInHands().IsUniversalTemperatureSource())
    {
      uts = player.GetItemInHands().GetUniversalTemperatureSource();
      utsd = new UTemperatureSourceDebug();
      utsd.AddHeader(player.GetItemInHands().GetType());
      utsd.Add("position", uts.GetPosition().ToString(false));
      utsd.Add("fullrange", uts.GetFullRange().ToString());
      utsd.Add("maxrange", uts.GetMaxRange().ToString());
      utsd.Add("temperature", uts.GetTemperature().ToString());
      utsd.Add("temperatureraw", uts.GetTemperatureRaw().ToString());
      utsd.Commit();
      m_UTemperatureSourceDebugs.Insert(utsd);
    }
  }
References GetGame().
Referenced by SendDebug().
GetAgentAntiboticsResistance()
float PluginBase::GetAgentAntiboticsResistance (int agent_id) inline protected
Definition at line 110 of file PluginTransmissionAgents.c.
  {
    if (!m_AgentList.Get(agent_id)) return 0;
    return m_AgentList.Get(agent_id).GetAntiboticsResistance();
  }
GetAgentAntiboticsResistanceEx()
float PluginBase::GetAgentAntiboticsResistanceEx (int agent_id, PlayerBase player) inline protected
Definition at line 117 of file PluginTransmissionAgents.c.
  {
    if (!m_AgentList.Get(agent_id)) return 0;
    return m_AgentList.Get(agent_id).GetAntibioticsResistanceEx(player);
  }
GetAgentDieOffSpeedEx()
float PluginBase::GetAgentDieOffSpeedEx (int agent_id, PlayerBase player) inline protected
Definition at line 91 of file PluginTransmissionAgents.c.
  {
    if (!m_AgentList.Get(agent_id)) return true;
    return m_AgentList.Get(agent_id).GetDieOffSpeedEx(player);
  }
GetAgentDigestibility()
float PluginBase::GetAgentDigestibility (int agent_id) inline protected
Definition at line 148 of file PluginTransmissionAgents.c.
  {
    if (!m_AgentList.Get(agent_id))
      return 0;
    return m_AgentList.Get(agent_id).GetDigestibility();
  }
GetAgentInvasibility()
float PluginBase::GetAgentInvasibility (int agent_id) inline protected
Definition at line 140 of file PluginTransmissionAgents.c.
  {
    if (!m_AgentList.Get(agent_id))
      return 0;
    return m_AgentList.Get(agent_id).GetInvasibility();
  }
GetAgentInvasibilityEx()
float PluginBase::GetAgentInvasibilityEx (int agent_id, PlayerBase player) inline protected
Definition at line 103 of file PluginTransmissionAgents.c.
  {
    if (!m_AgentList.Get(agent_id)) return true;
    return m_AgentList.Get(agent_id).GetInvasibilityEx(player);
  }
GetAgentList()
map< int, ref AgentBase > PluginBase::GetAgentList () inline private
Definition at line 46 of file PluginTransmissionAgents.c.
  {
    return m_AgentList;
  }
References m_AgentList.
GetAgentMaxCount()
static int PluginBase::GetAgentMaxCount (int agent_id) inline static protected
Definition at line 169 of file PluginTransmissionAgents.c.
  {
    if (!m_AgentList.Get(agent_id)) return 0;
    return m_AgentList.Get(agent_id).GetMaxCount();
  }
GetAgentPotencyEx()
EStatLevels PluginBase::GetAgentPotencyEx (int agent_id, PlayerBase player) inline protected
Definition at line 97 of file PluginTransmissionAgents.c.
  {
    if (!m_AgentList.Get(agent_id)) return true;
    return m_AgentList.Get(agent_id).GetPotencyEx(player);
  }
GetAgentTransferabilityAirOut()
float PluginBase::GetAgentTransferabilityAirOut (int agent_id) inline protected
Definition at line 129 of file PluginTransmissionAgents.c.
  {
    if (!m_AgentList.Get(agent_id)) return 0;
    return m_AgentList.Get(agent_id).GetTransferabilityAirOut();
  }
Referenced by CalculateAgentsToTransmit(), and DetermineChanceToTransmit().
GetAgentTransferabilityIn()
float PluginBase::GetAgentTransferabilityIn (int agent_id) inline protected
Definition at line 77 of file PluginTransmissionAgents.c.
  {
    if (!m_AgentList.Get(agent_id)) return 0;
    return m_AgentList.Get(agent_id).GetTransferabilityIn();
  }
Referenced by CalculateAgentsToTransmit(), and DetermineChanceToTransmit().
GetAgentTransferabilityOut()
float PluginBase::GetAgentTransferabilityOut (int agent_id) inline protected
Definition at line 123 of file PluginTransmissionAgents.c.
  {
    if (!m_AgentList.Get(agent_id)) return 0;
    return m_AgentList.Get(agent_id).GetTransferabilityOut();
  }
Referenced by CalculateAgentsToTransmit(), and DetermineChanceToTransmit().
GetBaseClasses()
string PluginBase::GetBaseClasses (string path, string item) inline private
Definition at line 478 of file PluginConfigViewer.c.
  {
    string adjustedPath = path;
    bool run = true;
    TStringArray resultArr = new TStringArray();
    resultArr.Insert(item);
    while (run)
    {
      //Print("checking for path:'" + adjustedPath +"'");
      string baseClass = "";
      run = GetGame().ConfigGetBaseName(adjustedPath, baseClass);
      if (baseClass)
      {
        TStringArray strs = new TStringArray;
        adjustedPath.Split(" ", strs);
        strs.Remove(strs.Count() - 1);
        strs.Insert(baseClass);
        adjustedPath = string.Join(" ", strs);
        resultArr.Insert(baseClass);
        if (adjustedPath == path)
          break;
      }
    }
    string result;
    resultArr.Invert();
    foreach (int i, string str: resultArr)
    {
      if (i != 0)
        result += " >> " + str;
      else
        result += str;
    }
    return result;
  }
References GetGame(), and path.
GetBaseClassPath()
string PluginBase::GetBaseClassPath (string config_class_path, string class_path, string config_class) inline private
Definition at line 38 of file PluginConfigViewer.c.
  {
    if (class_path == "")
      return "";
    int start = config_class_path.Length();
    int count = class_path.Length() - start;
    string class_path_without_config_class = GetOnlyChildPath(config_class_path, class_path);
    ref TStringArray full_path = new TStringArray;
    GetGame().ConfigGetFullPath(config_class_path, full_path);
    if (full_path.Count() > 1 && class_path_without_config_class != "")
      return GetBaseClassPathRecursive(config_class + " " + full_path.Get(1), class_path_without_config_class, config_class);
    else
      return "";
  }
References GetBaseClassPathRecursive(), GetGame(), and GetOnlyChildPath().
Referenced by GetConfigRecursive().
GetBaseClassPathCombined()
string PluginBase::GetBaseClassPathCombined (string child_path, string base_class) inline private
Definition at line 56 of file PluginConfigViewer.c.
  {
    int current = -1;
    int last = 0;
    while (true)
    {
      current = child_path.IndexOfFrom(last, " ");
      if (current > -1)
        last = current + 1;
      else
        break;
    }
    string result = child_path.Substring(0, last) + base_class;
    return result;
  }
Referenced by GetConfigRecursive().
GetBaseClassPathRecursive()
string PluginBase::GetBaseClassPathRecursive (string config_class_path, string class_path, string config_class) inline private
Definition at line 74 of file PluginConfigViewer.c.
  {
    if (ContainsFirstClass(config_class_path, class_path))
      return config_class_path + " " + class_path;
    else
    {
      ref TStringArray full_path = new TStringArray;
      GetGame().ConfigGetFullPath(config_class_path, full_path);
      if (full_path.Count() > 1)
        return GetBaseClassPathRecursive(config_class + " " + full_path.Get(1), class_path, config_class);
      else
        return "";
    }
  }
References ContainsFirstClass(), GetBaseClassPathRecursive(), and GetGame().
Referenced by GetBaseClassPath(), and GetBaseClassPathRecursive().
GetConfig()
TStringArray PluginBase::GetConfig (string class_path, string filter_char) inline private
Definition at line 276 of file PluginConfigViewer.c.
  {
    int i;
    TStringArray filtered = new TStringArray;
    if (class_path != "")
    {
      PluginDeveloper module_dev = PluginDeveloper.Cast(GetPlugin(PluginDeveloper));
      TStringArray path_nodes = new TStringArray;
      class_path.Split(" ", path_nodes);
      if (path_nodes.Count() >= 3)
      {
        string c_class_path = path_nodes.Get(0) + " " + path_nodes.Get(1) + " " + path_nodes.Get(2);
        array<string> overridden = new array<string>;
        string config_class = path_nodes.Get(1);
        string class_name = path_nodes.Get(2);
        TStringArray result = GetConfigRecursive(c_class_path, class_name, c_class_path, config_class, overridden);
        TStringArray nested_start = new TStringArray;
        TStringArray nested_end = new TStringArray;
        TStringArray nested_inherited_start = new TStringArray;
        TStringArray nested_inherited_end = new TStringArray;
        string tabs = MakeTabs(1);
        string tabs_inherited = MakeTabs(1, true);
        string check_tabs = MakeTabs(path_nodes.Count() - 1, true);
        nested_start.Insert(":!");
        nested_end.Insert(":#");
        nested_inherited_start.Insert(":!");
        nested_inherited_end.Insert(":#");
        string last_node = filter_char + MakeTabs(nested_start.Count()) + "!";
        if (path_nodes.Count() == 3)
          last_node = filter_char + MakeTabs(1) + "!";
        else
        {
          for (i = 1; i < path_nodes.Count() - 2; i++)
          {
            tabs = MakeTabs(i);
            tabs_inherited = MakeTabs(i, true);
            string path_node = path_nodes.Get(i + 2);
            path_node.ToLower();
            nested_start.Insert(":" + tabs + "!" + path_node);
            nested_end.Insert(":" + tabs + "#" + path_node);
            nested_inherited_start.Insert(":" + tabs_inherited + "!" + path_node);
            nested_inherited_end.Insert(":" + tabs_inherited + "#" + path_node);
          }
          last_node = filter_char + MakeTabs(i) + "!";
        }
        int current_nest = 0;
        for (i = 0; i < result.Count(); i++)
        {
          string current = result.Get(i);
          string current_lower = current;
          current_lower.ToLower();
          int len_current = current.Length();
          if (current_nest < nested_start.Count())
          {
            int len_start = nested_start.Get(current_nest).Length();
            if (len_current >= len_start)
            {
              string prefix_start = current_lower;
              if (current_nest == 0)
                prefix_start = current_lower.Substring(0, len_start);
              if (prefix_start == nested_start.Get(current_nest) || prefix_start == nested_inherited_start.Get(current_nest))
              {
                current_nest++;
                continue;
              }
            }
          }
          if (current_nest >= 1)
          {
            int len_end = nested_end.Get(current_nest - 1).Length();
            if (len_current >= len_end)
            {
              string prefix_end = current_lower;
              if (current_nest == 0)
                prefix_start = current_lower.Substring(0, len_start);
              if (prefix_end == nested_end.Get(current_nest - 1) || prefix_end == nested_inherited_end.Get(current_nest - 1))
                current_nest--;
            }
          }
          if (current_nest == nested_start.Count())
          {
            string first_char = current.Substring(0, 1);
            if (first_char == filter_char)
            {
              int bang_pos = current.IndexOf("!");
              if (bang_pos > -1)
              {
                int len_last_node = last_node.Length();
                if (len_current >= len_last_node)
                {
                  string prefix_current = current_lower.Substring(0, len_last_node);
                  if (last_node == prefix_current)
                    filtered.Insert(current.Substring(bang_pos + 1, current.Length() - (bang_pos + 1)));
                }
              }
            }
          }
        }
        TStringArray without_duplications = new TStringArray;
        map<string, string> lowered = new map<string, string>;
        for (i = 0; i < filtered.Count(); i++)
        {
          string c = filtered.Get(i);
          string lower_c = c;
          lower_c.ToLower();
          if (without_duplications.Find(lower_c) < 0)
          {
            without_duplications.Insert(lower_c);
            if (lower_c != c)
              lowered.Set(lower_c, c);
          }
        }
        module_dev.SortStringArray(without_duplications);
        for (i = 0; i < without_duplications.Count(); i++)
        {
          string cc = without_duplications.Get(i);
          if (lowered.Contains(cc))
            cc = lowered.Get(cc);
          int tilda_index = cc.IndexOf("~");
          if (tilda_index > -1)
          {
            string spaces = "    ";
            if (cc.IndexOf("~}") > -1)
              spaces = "";
            cc = spaces + cc.Substring(tilda_index + 1, cc.Length() - (tilda_index + 1));
          }
          without_duplications.Set(i, cc);
        }
        return without_duplications;
      }
      else if (filter_char == ":")
      {
        int cnt_config = GetGame().ConfigGetChildrenCount(class_path);
        for (i = 0; i < cnt_config; i++)
        {
          string config_name = "";
          GetGame().ConfigGetChildName(class_path, i, config_name);
          filtered.Insert(config_name);
        }
        module_dev.SortStringArray(filtered);
      }
    }
    else if (filter_char == ":")
    {
      filtered.Insert("configfile");
      filtered.Insert("missionconfigfile");
    }
    return filtered;
  }
References class_name, GetConfigRecursive(), GetGame(), GetPlugin(), and MakeTabs().
Referenced by GetConfigHierarchy(), and GetConfigVariables().
GetConfigHierarchy()
TStringArray PluginBase::GetConfigHierarchy (string class_path) inline private
Definition at line 473 of file PluginConfigViewer.c.
  {
    return GetConfig(class_path, ":");
  }
References GetConfig().
GetConfigRecursive()
TStringArray PluginBase::GetConfigRecursive (string path, string name, string config_class_path, string config_class, local array< string > overridden, int depth = 0, local bool check_base_class_of_class = false) inline private
Definition at line 123 of file PluginConfigViewer.c.
  {
    string tabs = MakeTabs(depth + 1);
    string child_path = path;
    int count = GetGame().ConfigGetChildrenCount(child_path);
    int i = 0;
    bool name_printed = false;
    TStringArray result = new TStringArray;
    for (i = 0; i < count; i++)
    {
      string child_name = "";
      GetGame().ConfigGetChildName(child_path, i, child_name);
      string c_child_path = child_path + " " + child_name;
      string child_name_lower = child_name;
      child_name_lower.ToLower();
      if (overridden.Find(child_name_lower) == -1)
      {
        if (!name_printed)
        {
          result.Insert(":" + MakeTabs(depth, check_base_class_of_class) + "!" + name);
          name_printed = true;
        }
        overridden.Insert(child_name_lower);
        int type = GetGame().ConfigGetType(c_child_path);
        if (type != CT_CLASS)
        {
          if (type != CT_ARRAY)
            result.Insert("-" + tabs + "!" + child_name + " = " + GetGame().ConfigGetTextOut(c_child_path));
          else
          {
            result.Insert("-" + tabs + "!" + child_name + "[] = {");
            TStringArray strs = new TStringArray;
            GetGame().ConfigGetTextArray(c_child_path, strs);
            string tabs_array = MakeTabs(depth + 2);
            int j;
            for (j = 0; j < strs.Count(); j++)
              result.Insert("-" + tabs + "!" + child_name + "[]" + j.ToStringLen(6) + "~" + strs.Get(j) + ",");
            result.Insert("-" + tabs + "!" + child_name + "[]" + j.ToStringLen(6) + "~}");
          }
        }
        else
        {
          array<string> overridden_sub = new array<string>;
          if (GetGame().ConfigGetChildrenCount(c_child_path) > 0)
          {
            TStringArray config1 = GetConfigRecursive(c_child_path, child_name, config_class_path, config_class, overridden_sub, depth + 1);
            result.InsertAll(config1);
          }
          else
            result.Insert(":" + tabs + "!" + child_name);
          string cc_child_path = c_child_path;
          string c_config_class_path = config_class_path;
          string c_child_name = child_name;
          int cc = 0;
          while (true)
          {
            string base_class = "";
            GetGame().ConfigGetBaseName(cc_child_path, base_class);
            int start = c_config_class_path.Length() + 1;
            int len = cc_child_path.Length();
            len -= c_config_class_path.Length() + c_child_name.Length();
            len -= 2;
            if (base_class != "")
            {
              string only_child_path = "";
              if (len < 0)
                only_child_path = base_class;
              else
                only_child_path = cc_child_path.Substring(start, len) + " " + base_class;
              string c_base_child_path = GetBaseClassPathCombined(cc_child_path, base_class);
              string base_class_path = GetBaseClassPath(c_config_class_path, c_base_child_path, config_class);
              if (base_class_path != "")
              {
                TStringArray config2 = GetConfigRecursive(base_class_path, base_class, base_class_path, config_class, overridden_sub, depth + 1, true);
                result.InsertAll(config2);
              }
              else
              {
                TStringArray config3 = GetConfigRecursive(base_class, base_class, base_class, config_class, overridden_sub, depth + 1, true);
                result.InsertAll(config3);
                break;
              }
              cc_child_path = base_class_path;
              c_child_name = base_class;
              c_config_class_path = cc_child_path.Substring(0, cc_child_path.Length() - only_child_path.Length() - 1);
            }
            else
              break;
          }
        }
      }
    }
    if (name_printed)
      result.Insert(":" + MakeTabs(depth, check_base_class_of_class) + "#" + name);
    if (!check_base_class_of_class)
    {
      TStringArray full_path = new TStringArray;
      GetGame().ConfigGetFullPath(child_path, full_path);
      if (full_path.Count() > 1)
      {
        TStringArray config4 = GetConfigRecursive(config_class + " " + full_path.Get(1), full_path.Get(1), config_class + " " + full_path.Get(1), config_class, overridden, depth);
        result.InsertAll(config4);
      }
    }
    else
    {
      string class_base_class = "";
      GetGame().ConfigGetBaseName(child_path, class_base_class);
      if (class_base_class != "")
      {
        string base_child_path = GetBaseClassPathCombined(child_path, class_base_class);
        string cc_base_child_path = GetBaseClassPath(config_class_path, base_child_path, config_class);
        if (cc_base_child_path != "")
        {
          TStringArray config5 = GetConfigRecursive(cc_base_child_path, class_base_class, cc_base_child_path, config_class, overridden, depth, true);
          result.InsertAll(config5);
        }
        else
        {
          TStringArray config6 = GetConfigRecursive(class_base_class, class_base_class, class_base_class, config_class, overridden, depth, true);
          result.InsertAll(config6);
        }
      }
    }
    return result;
  }
References GetBaseClassPath(), GetBaseClassPathCombined(), GetConfigRecursive(), GetGame(), MakeTabs(), name, and path.
Referenced by GetConfig(), and GetConfigRecursive().
GetConfigVariables()
TStringArray PluginBase::GetConfigVariables (string class_path) inline private
Definition at line 468 of file PluginConfigViewer.c.
  {
    return GetConfig(class_path, "-");
  }
References GetConfig().
GetDieOffSpeed()
float PluginBase::GetDieOffSpeed (int agent_id) inline protected
Definition at line 155 of file PluginTransmissionAgents.c.
  {
    if (!m_AgentList.Get(agent_id))
      return 0;
    return m_AgentList.Get(agent_id).GetDieOffSpeed();
  }
GetDrawSelection()
bool PluginBase::GetDrawSelection () inline private
Definition at line 668 of file PluginSceneManager.c.
  {
    return m_ModuleConfigDebugProfile.GetSceneEditorDrawSelection();
  }
GetFileContent()
TStringArray PluginBase::GetFileContent () inline private
Definition at line 138 of file PluginFileHandler.c.
  {
    return m_FileContent;
  }
GetFileName()
string PluginBase::GetFileName () inline private
Definition at line 42 of file PluginFileHandler.c.
  {
    return string.Empty;
  }
References string::Empty.
GetHitMessage()
string PluginBase::GetHitMessage (TotalDamageResult damageResult, int component, string zone, string ammo) inline protected
Definition at line 99 of file PluginAdminLog.c.
  {
    if (damageResult)
    {
      float dmg = damageResult.GetHighestDamage("Health");
      return " into " + zone + "(" + component.ToString() + ") for " + dmg.ToString() + " damage (" + ammo + ")";
    }
    else // block
      return " into Block" + "(" + component.ToString() + ") for 0 damage ";
  }
References component.
Referenced by PlayerHitBy().
GetID()
int PluginBase::GetID (string name) inline private
Definition at line 32 of file PluginVariables.c.
  {
    return m_Variables.GetKeyByValue(name);
  }
References name.
GetInstance() [1/3]
static PluginCameraTools PluginBase::GetInstance () inline static protected
Definition at line 11 of file PluginCameraTools.c.
  {
    return m_Instance;
  }
References m_Instance.
GetInstance() [2/3]
static PluginDeveloper PluginBase::GetInstance () inline static protected
Definition at line 8 of file PluginDeveloper.c.
  {
    return PluginDeveloper.Cast(GetPlugin(PluginDeveloper));
  }
References GetPlugin().
GetInstance() [3/3]
static PluginSceneManager PluginBase::GetInstance () inline static private
Definition at line 34 of file PluginSceneManager.c.
  {
    return PluginSceneManager.Cast(GetPlugin(PluginSceneManager));
  }
References GetPlugin().
GetKeyBindings()
array< ref KeyBinding > PluginBase::GetKeyBindings () inline private
Definition at line 260 of file PluginKeyBinding.c.
  {
    return m_KeyBindings;
  }
GetKitRepairCost()
float PluginBase::GetKitRepairCost (ItemBase repair_kit, Object item) inline private
Definition at line 119 of file PluginRepairing.c.
  {
    array<int> allowedRepairKitTypes = new array<int>();
    array<float> repairKitCosts = new array<float>();
    item.ConfigGetIntArray("repairableWithKits", allowedRepairKitTypes);
    item.ConfigGetFloatArray("repairCosts", repairKitCosts);
    int repairKitType = repair_kit.ConfigGetInt("repairKitType");
    foreach (int i, int allowedKitType : allowedRepairKitTypes)
    {
      if (allowedKitType == repairKitType)
        return repairKitCosts.Get(i);
    }
    return 0;
  }
GetLoadedScene()
SceneData PluginBase::GetLoadedScene () inline private
Definition at line 913 of file PluginSceneManager.c.
  {
    return m_SceneData;
  }
GetLoadPlayerPos()
bool PluginBase::GetLoadPlayerPos () inline private
Definition at line 684 of file PluginSceneManager.c.
  {
    return m_ModuleConfigDebugProfile.GetSceneEditorLoadPlayerPos();
  }
GetModuleName()
string PluginBase::GetModuleName () inline private
Definition at line 15 of file PluginBase.c.
  {
    return ClassName();
  }
Referenced by GetModuleType(), and Log().
GetModuleType()
PluginBase::GetModuleType () inline private
Definition at line 20 of file PluginBase.c.
  {
    return GetModuleName().ToType();
  }
References GetModuleName(), and string::ToType().
GetMouseBindings()
array< ref MouseBinding > PluginBase::GetMouseBindings () inline private
Definition at line 268 of file PluginKeyBinding.c.
  {
    return m_MouseBindings;
  }
GetMouseButtonInfo()
MouseButtonInfo PluginBase::GetMouseButtonInfo (int button) inline protected
Definition at line 347 of file PluginKeyBinding.c.
  {
    for (int i = 0; i < m_MouseButtons.Count(); ++i)
    {
      MouseButtonInfo info = m_MouseButtons.Get(i);
      if (info.GetButtonID() == button)
        return info;
    }
    return NULL;
  }
GetMousePositionInScene()
vector PluginBase::GetMousePositionInScene () inline private
Definition at line 1171 of file PluginSceneManager.c.
  {
    vector dir = GetGame().GetPointerDirection();
    vector from = FreeDebugCamera.GetInstance().GetPosition();
    vector to = from + (dir * 10000);
    vector contact_pos;
    vector contact_dir;
    int contact_component;
    if (DayZPhysics.RaycastRV(from, to, contact_pos, contact_dir, contact_component))
      return contact_pos;
    return "0 0 0";
  }
References GetGame(), and DayZPhysics::RaycastRV().
GetName()
string PluginBase::GetName (int id) inline private
Definition at line 27 of file PluginVariables.c.
  {
    return m_Variables.Get(id);
  }
GetNameByID()
static string PluginBase::GetNameByID (int agent_id) inline static private
Definition at line 61 of file PluginTransmissionAgents.c.
  {
    return m_AgentList.Get(agent_id).GetName();
  }
GetOnlyChildPath()
string PluginBase::GetOnlyChildPath (string config_class_path, string class_path) inline private
Definition at line 22 of file PluginConfigViewer.c.
  {
    int config_class_path_len = config_class_path.Length();
    int class_path_len = class_path.Length();
    if (class_path_len > config_class_path_len)
    {
      int start = config_class_path_len;
      int count = class_path_len - start;
      return class_path.Substring(start, count).Trim();
    }
    else
      return "";
  }
Referenced by GetBaseClassPath().
GetPlantMaterial()
PlantMaterialHealth PluginBase::GetPlantMaterial (string plant_type) inline private
Definition at line 97 of file PluginHorticulture.c.
  {
    if (m_PlantMaterials.Contains(plant_type))
      return m_PlantMaterials.Get(plant_type);
    return NULL;
  }
GetPlantType()
string PluginBase::GetPlantType (Object obj) inline private
Definition at line 66 of file PluginHorticulture.c.
  {
    string seed_type = obj.GetType();
    string plant_type = "";
    GetGame().ConfigGetText("cfgVehicles " + seed_type + " Horticulture PlantType", plant_type);
    return plant_type;
  }
References GetGame().
GetPlayerListTimer()
static int PluginBase::GetPlayerListTimer () inline static protected
Definition at line 30 of file PluginAdminLog.c.
  {
    return 300; // seconds
  }
GetPlayerPrefix()
string PluginBase::GetPlayerPrefix (PlayerBase player, PlayerIdentity identity) inline protected
Definition at line 67 of file PluginAdminLog.c.
  {
    m_Position = player.GetPosition();
    m_PosArray[3] = { m_Position[0].ToString(), m_Position[2].ToString(), m_Position[1].ToString() };
    for (int i = 0; i < 3; i++) // trim position precision
    {
      m_DotIndex = m_PosArray[i].IndexOf(".");
      if (m_DotIndex != -1)
        m_PosArray[i] = m_PosArray[i].Substring(0, m_DotIndex + 2);
    }
    if (identity) // return partial message even if it fails to fetch identity
    {
      //return "Player \"" + "Unknown/Dead Entity" + "\" (id=" + "Unknown" + " pos=<" +  m_PosArray[0] + ", " + m_PosArray[1] + ", " + m_PosArray[2] + ">)";
      m_PlayerName = "\"" + identity.GetName() + "\"";
      m_Pid = identity.GetId();
    }
    else
    {
      m_PlayerName = player.GetCachedName();
      m_Pid = player.GetCachedID();
    }
    if (!player.IsAlive())
      m_PlayerName = m_PlayerName + " (DEAD)";
    return "Player " + m_PlayerName + " (id=" + m_Pid + " pos=<" + m_PosArray[0] + ", " + m_PosArray[1] + ", " + m_PosArray[2] + ">)";
  }
References string::IndexOf(), m_Position, string::Substring(), and vector::ToString().
Referenced by BleedingOut(), OnContinouousAction(), OnPlacementComplete(), PlayerHitBy(), PlayerKilled(), PlayerList(), Suicide(), TotemFlagChange(), UnconStart(), and UnconStop().
GetPotency()
EStatLevels PluginBase::GetPotency (int agent_id) inline protected
Definition at line 162 of file PluginTransmissionAgents.c.
  {
    if (!m_AgentList.Get(agent_id))
      return 0;
    return m_AgentList.Get(agent_id).GetPotency();
  }
GetProtectionLevel()
float PluginBase::GetProtectionLevel (int type, int slot, Man player) inline protected
Definition at line 340 of file PluginTransmissionAgents.c.
  {
    return GetProtectionLevelEx(type, slot, player);
  }
References GetProtectionLevelEx().
Referenced by TransmitAgentsEx().
GetProtectionLevelEx()
static float PluginBase::GetProtectionLevelEx (int type, int slot, Man player, bool consider_filter = true, int system = 0) inline static protected
Definition at line 329 of file PluginTransmissionAgents.c.
  {
    ItemBase attachment = ItemBase.Cast(player.GetInventory().FindAttachment(slot));
    if (!attachment)
      return 0;
    return attachment.GetProtectionLevel(type, consider_filter, system);
  }
Referenced by GetProtectionLevel().
GetRotationAngle()
int PluginBase::GetRotationAngle () inline private
Definition at line 700 of file PluginSceneManager.c.
  {
    return m_ModuleConfigDebugProfile.GetSceneEditorRotationAngle();
  }
GetRPCModifierID()
int PluginBase::GetRPCModifierID (ParamsReadContext ctx) inline private
Definition at line 349 of file PluginDeveloperSync.c.
  {
    Param1<int> p = new Param1<int>(0);
    if (ctx.Read(p))
      return p.param1;
    return 0;
  }
Referenced by OnRPC().
GetRPCModifierLock()
void PluginBase::GetRPCModifierLock (ParamsReadContext ctx, out int id, out bool lock) inline private
Definition at line 359 of file PluginDeveloperSync.c.
  {
    Param2<int, bool> p = new Param2<int, bool>(0, false);
    if (ctx.Read(p))
    {
      id = p.param1;
      lock = p.param2;
    }
  }
Referenced by OnRPC().
GetRPCUpdateState()
bool PluginBase::GetRPCUpdateState (ParamsReadContext ctx) inline private
Definition at line 339 of file PluginDeveloperSync.c.
  {
    Param1<bool> p = new Param1<bool>(0);
    if (ctx.Read(p))
      return p.param1;
    return false;
  }
Referenced by OnRPC(), and OnRPCTemp().
GetSceneList()
TStringArray PluginBase::GetSceneList () inline private
Definition at line 1007 of file PluginSceneManager.c.
  {
    return m_ModuleConfigScene.GetSceneList();
  }
GetSceneObjectByEntity()
SceneObject PluginBase::GetSceneObjectByEntity (EntityAI entity) inline private
Definition at line 985 of file PluginSceneManager.c.
  {
    array<ref SceneObject> scene_objects = GetSceneObjects();
    if (scene_objects != NULL)
    {
      for (int i = 0; i <= scene_objects.Count(); ++i)
      {
        SceneObject obj = scene_objects.Get(i);
        EntityAI e = obj.GetObject();
        if (e == entity)
          return obj;
      }
    }
    return NULL;
  }
References SceneObject::GetObject().
GetSceneObjectByIndex()
SceneObject PluginBase::GetSceneObjectByIndex (int index) inline private
Definition at line 969 of file PluginSceneManager.c.
  {
    array<ref SceneObject> scene_objects = GetSceneObjects();
    if (scene_objects != NULL)
    {
      if (index > -1 && index < scene_objects.Count())
        return scene_objects.Get(index);
    }
    return NULL;
  }
GetSceneObjects()
array< ref SceneObject > PluginBase::GetSceneObjects () inline private
Definition at line 936 of file PluginSceneManager.c.
  {
    if (m_SceneData)
      return m_SceneData.GetSceneObjects();
    return NULL;
  }
GetSceneObjectsAll()
array< ref SceneObject > PluginBase::GetSceneObjectsAll () inline private
Definition at line 958 of file PluginSceneManager.c.
  {
    if (m_SceneData)
      return m_SceneData.GetSceneObjectsAll();
    return NULL;
  }
GetScenePlayers()
array< ref ScenePlayer > PluginBase::GetScenePlayers () inline private
Definition at line 947 of file PluginSceneManager.c.
  {
    if (m_SceneData)
      return m_SceneData.GetScenePlayers();
    return NULL;
  }
GetSelectedSceneObject()
SceneObject PluginBase::GetSelectedSceneObject () inline private
Definition at line 457 of file PluginSceneManager.c.
  {
    return m_SelectedObject;
  }
References m_SelectedObject.
GetSelectedSceneObjectIndex()
int PluginBase::GetSelectedSceneObjectIndex () inline private
Definition at line 921 of file PluginSceneManager.c.
  {
    array<ref SceneObject> scene_objects = GetSceneObjects();
    for (int i = 0; i < scene_objects.Count(); i++)
    {
      if (GetSelectedSceneObject() == scene_objects.Get(i))
        return i;
    }
    return -1;
  }
GetSimpleAgentList()
map< int, string > PluginBase::GetSimpleAgentList () inline private
Definition at line 51 of file PluginTransmissionAgents.c.
  {
    if (!m_IsConstructed)
    {
      ConstructSimpleAgentList();
      m_IsConstructed = true;
    }
    return m_SimpleAgentList;
  }
References ConstructSimpleAgentList(), and m_SimpleAgentList.
GetSubFolderName()
string PluginBase::GetSubFolderName () inline private
Definition at line 47 of file PluginFileHandler.c.
  {
    return string.Empty;
  }
References string::Empty.
GetSurfaceFertility()
float PluginBase::GetSurfaceFertility (string surface_type) inline private
Definition at line 76 of file PluginHorticulture.c.
  {
    float fertility = 0.8;
    if (surface_type == "hlina" || surface_type == "CRGrass1" || surface_type == "CRGrass2" || surface_type == "CRForest1" || surface_type == "CRForest2" || surface_type == "CRGrit1")
      fertility = 0.8;
    return fertility;
  }
GetWatching()
bool PluginBase::GetWatching () inline private
Definition at line 34 of file PluginRemotePlayerDebugServer.c.
  {
    return m_Watching;
  }
GiveWormsToPlayer()
bool PluginBase::GiveWormsToPlayer (PlayerBase player, float chance) inline private
Definition at line 85 of file PluginHorticulture.c.
  {
    if (Math.RandomFloat01() <= chance)
    {
      ItemBase item = ItemBase.Cast(player.GetHumanInventory().CreateInInventory("Food_Worm"));
      item.SetQuantity(1);
      return true;
    }
    return false;
  }
References Math::RandomFloat01().
GrowDuringAntibioticsAttack()
bool PluginBase::GrowDuringAntibioticsAttack (int agent_id, PlayerBase player) inline protected
Definition at line 84 of file PluginTransmissionAgents.c.
  {
    if (!m_AgentList.Get(agent_id)) return true;
    return m_AgentList.Get(agent_id).GrowDuringAntibioticsAttack(player);
  }
HandlePresetSpawn()
void PluginBase::HandlePresetSpawn (PlayerBase player, string presetName, EntityAI target) inline protected
Definition at line 194 of file PluginDeveloper.c.
  {
#ifdef DEVELOPER
    PlayerBase targetPlayer = player;
    if (target)
      targetPlayer = PlayerBase.Cast(target);
    if (!targetPlayer)
      return;
    targetPlayer.m_PresetSpawned = true;
    string class_name = presetName + "_Preset";
    typename type = class_name.ToType();
    if (type)
    {
      PresetSpawnBase presetObj = PresetSpawnBase.Cast(type.Spawn());
      if (presetObj)
        presetObj.Init(targetPlayer);
    }
#endif
  }
References class_name.
Referenced by OnRPC().
HandleSetTime()
void PluginBase::HandleSetTime (PlayerBase player, ParamsReadContext ctx) inline protected
Definition at line 163 of file PluginDeveloper.c.
  {
#ifdef DEVELOPER
    Param5<int, int, int, int, int> p5 = new Param5<int, int, int, int, int>(0, 0, 0, 0, 0);
    if (ctx.Read(p5))
    {
      //float time01 = p5.param4 / 100;
      //int time_minutes = Math.Lerp(0, 24*60, time01 );
      int year = p5.param1;
      int month = p5.param2;
      int day = p5.param3;
      int hour = p5.param4;
      int minute = p5.param5;
      GetGame().GetWorld().SetDate(year, month, day, hour, minute);
      /*
        Debug.Log("year:" + year);
        Debug.Log("month:" + month);
        Debug.Log("day:" + day);
        Debug.Log("hour:" + hour);
        Debug.Log("minute:" + minute);
      */
    }
#endif
  }
References GetGame().
Referenced by OnRPC().
Hide() [1/3]
void PluginBase::Hide () inline private
Definition at line 177 of file PluginDayZInfectedDebug.c.
  {
    ShowWidgets(false);
    m_IsActive = false;
    GetUApi().UpdateControls();
    m_TickTimer = NULL;
  }
References GetUApi(), m_IsActive, m_TickTimer, and ShowWidgets().
Referenced by SetDebugShowMode(), ToggleDebugWindowEventOld(), ToggleDebugWindowEventP(), ToggleDebugWindowSetMode(), and ToggleDebugWindowSetMode().
Hide() [2/3]
void PluginBase::Hide () inline private
Definition at line 81 of file PluginDrawCheckerboard.c.
  {
    ShowWidgets(false);
    m_IsActive = false;
  }
References m_IsActive, and ShowWidgets().
Hide() [3/3]
void PluginBase::Hide () inline private
Definition at line 25 of file PluginSoundDebug.c.
  {
    m_TickTimer = NULL;
  }
References m_TickTimer.
Init() [1/2]
void PluginBase::Init () inline private
Definition at line 34 of file PluginCharPlacement.c.
  {
    if (m_Character)
      m_Character.Delete();
    m_Initialized = true;
    m_Character = PlayerBase.Cast(GetGame().CreateObject("SurvivorF_Judy", FreeDebugCamera.GetInstance().GetPosition(), false, false/*ai*/));
    FreeDebugCamera.GetInstance().SetFOV(FOV); //default scene FOV
    m_demoRot = "0 0 0";
  }
References GetGame(), and m_Initialized.
Init() [2/2]
void PluginBase::Init () inline private
Definition at line 14 of file PluginDoorRuler.c.
  {
    if (m_Ruler)
      m_Ruler.Delete();
    m_Initialized = true;
    m_Ruler = ItemBase.Cast(GetGame().CreateObject("DoorTestCamera", FreeDebugCamera.GetInstance().GetPosition(), false, false/*ai*/));
  }
References GetGame(), and m_Initialized.
InitAttacks()
void PluginBase::InitAttacks () inline protected
Definition at line 449 of file PluginDayZInfectedDebug.c.
  {
    m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Attack Left Light", 0));
    m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Attack Right Light", 1));
    m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Attack Left Heavy", 2));
    m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Attack Right Heavy", 3));
    m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Crawl Attack", 7));
    //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Crawl Attack Combo", 8));
    //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Door Push Attack", 9));
    //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Door Head Attack", 10));
    //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Door Shoulder Attack", 11));
    //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Door LR Attack", 12));
    //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Door Kick Attack", 13));
    //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Door Charge R", 14));
    //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Door Charge L", 15));
    for (int i = 0; i < m_AttackDescriptors.Count(); ++i)
      m_AttackTypeCB.AddItem(m_AttackDescriptors.Get(i).name);
  }
References PluginDayZInfectedDebugAttackDesc().
Referenced by CreateModuleWidgets().
InitLoad()
void PluginBase::InitLoad () inline private
Definition at line 286 of file PluginSceneManager.c.
  {
    PLAYER = PlayerBase.Cast(GetGame().GetPlayer());
    SceneLoad(PluginMissionConfig.GetInstance().GetSceneEditorName());
    RestoreSceneObjectsLinks();
    ExecuteInitScripts();
  }
References GetGame(), GetPlayer(), and PLAYER.
InitWidgets()
void PluginBase::InitWidgets () inline protected
Definition at line 38 of file PluginUniversalTemperatureSourceClient.c.
  {
    for (int i = 0; i < MAX_SIMULTANEOUS_UTS; i++)
    {
      m_RootWidget[i] = GetGame().GetWorkspace().CreateWidgets("gui/layouts/debug/day_z_debug_remoteinfo.layout");
      m_StatListWidgets[i] = TextListboxWidget.Cast(m_RootWidget[i].FindAnyWidget("TextListboxWidget0"));
      m_HeaderWidget[i] = TextWidget.Cast(m_RootWidget[i].FindAnyWidget("TextWidget0"));
    }
  }
References FindAnyWidget(), GetGame(), m_RootWidget, m_StatListWidgets, and MAX_SIMULTANEOUS_UTS.
Referenced by OnInit().
InjectAgentsWithoutPlayer()
void PluginBase::InjectAgentsWithoutPlayer (EntityAI target, int agents) inline protected
Definition at line 261 of file PluginTransmissionAgents.c.
  {
    if (target.IsItemBase())
    {
      ItemBase ib_target = ItemBase.Cast(target);
      ib_target.TransferAgents(agents);
    }
  }
Referenced by TransmitAgentsEx().
InjectAgentsWithPlayer()
void PluginBase::InjectAgentsWithPlayer (EntityAI target, int agents, float protection, int dose_size, int inject_type) inline protected
will add agents to a given target, using chance of transmission and full dose size if chance succeeds
Definition at line 271 of file PluginTransmissionAgents.c.
  {
    if (target && (agents != 0) && target.IsEntityAI())
    {
      int bit_count = Math.GetNumberOfSetBits(agents);
      for (int i = 0; i < bit_count; i++)
      {
        int agent_bit = Math.Pow(2, Math.GetNthBitSet(agents, i));
        if (DetermineChanceToTransmit(agent_bit, protection, inject_type))
          target.InsertAgent(agent_bit, dose_size);
      }
    }
  }
References DetermineChanceToTransmit(), Math::GetNthBitSet(), Math::GetNumberOfSetBits(), and Math::Pow().
Referenced by TransmitAgentsEx().
InjectAgentsWithPlayerCount()
void PluginBase::InjectAgentsWithPlayerCount (EntityAI target, int agents, float protection, int dose_size, int inject_type) inline protected
will add agents to a given target, with no probability, but the dose size is modified by m_TransferabilityOut of the agent
Definition at line 287 of file PluginTransmissionAgents.c.
  {
    if (target && (agents != 0) && target.IsEntityAI())
    {
      int bit_count = Math.GetNumberOfSetBits(agents);
      for (int i = 0; i < bit_count; i++)
      {
        int agent_bit = Math.Pow(2, Math.GetNthBitSet(agents, i));
        float count = CalculateAgentsToTransmit(agent_bit, protection, dose_size, inject_type);
        target.InsertAgent(agent_bit, count);
      }
    }
  }
References CalculateAgentsToTransmit(), Math::GetNthBitSet(), Math::GetNumberOfSetBits(), and Math::Pow().
Referenced by TransmitAgentsEx().
InjectAgentWithPlayerDose()
float PluginBase::InjectAgentWithPlayerDose (EntityAI target, int agent, float protection, float dose_size, int inject_type) inline protected
will add agent to a given target
Definition at line 303 of file PluginTransmissionAgents.c.
  {
    float count = CalculateAgentsToTransmit(agent, protection, dose_size, inject_type);
    {
      if (count > 0)
      {
        target.InsertAgent(agent, count);
        return count;
      }
    }
    return 0;
  }
References CalculateAgentsToTransmit().
Referenced by TransmitAgentsEx().
IsActive()
bool PluginBase::IsActive () inline private
Definition at line 53 of file PluginDrawCheckerboard.c.
  {
    return m_IsActive;
  }
References m_IsActive.
IsCurrentUIPageValid()
bool PluginBase::IsCurrentUIPageValid (int ui_page_request) inline protected
Definition at line 300 of file PluginKeyBinding.c.
  {
    int ui_page_current = MENU_NONE;
    if (GetGame().GetUIManager().GetMenu())
      ui_page_current = GetGame().GetUIManager().GetMenu().GetID();
    if (ui_page_current < MENU_ANY || !CheckMask(ui_page_request, ui_page_current))
    {
      if (CheckMask(ui_page_request, MENU_NONE) || !CheckMask(ui_page_request, MENU_ANY))
        return false;
    }
    return true;
  }
References GetGame(), MENU_ANY, and MENU_NONE.
IsEnabledFreeCamera()
bool PluginBase::IsEnabledFreeCamera () inline protected
Definition at line 37 of file PluginDeveloper.c.
  {
    return DeveloperFreeCamera.IsFreeCameraEnabled();
  }
References DeveloperFreeCamera::IsFreeCameraEnabled().
IsEven()
bool PluginBase::IsEven (int num) inline private
even or odd
Definition at line 59 of file PluginDrawCheckerboard.c.
  {
    if ((num % 2) == 0)
      return true;
    else
      return false;
  }
Referenced by CreateWidgetOverlay().
IsFree()
bool PluginBase::IsFree (Object target) inline private
Definition at line 18 of file PluginObjectsInteractionManager.c.
  {
    if (target && m_LockedObjects.Count() > 0)
    {
      for (int i = 0; i < m_LockedObjects.Count(); i++)
      {
        if (m_LockedObjects.Get(i) == target)
          return false;
      }
    }
    return true;
  }
Referenced by Lock().
IsInConsole()
bool PluginBase::IsInConsole () inline private
Definition at line 778 of file PluginDeveloper.c.
  {
    UIScriptedMenu menu_curr = GetGame().GetUIManager().GetMenu();
    if (menu_curr != NULL && menu_curr.GetID() == MENU_SCRIPTCONSOLE)
      return true;
    return false;
  }
References GetGame(), and MENU_SCRIPTCONSOLE.
IsIngame()
bool PluginBase::IsIngame () inline private
Definition at line 768 of file PluginDeveloper.c.
  {
    UIScriptedMenu menu_curr = GetGame().GetUIManager().GetMenu();
    if (menu_curr == NULL)
      return true;
    return false;
  }
References GetGame().
IsKeyPressed()
bool PluginBase::IsKeyPressed (int key) inline protected
Definition at line 362 of file PluginKeyBinding.c.
  {
    return (KeyState(key) == 1);
  }
References KeyState().
IsModifierLocked()
bool PluginBase::IsModifierLocked (int id, PlayerBase player = NULL) inline private
Definition at line 643 of file PluginDeveloperSync.c.
  {
    if (!player)
      player = PlayerBase.Cast(GetDayZGame().GetPlayer());
    ModifiersManager mods_manager = player.GetModifiersManager();
    return mods_manager.GetModifierLock(Math.AbsInt(id));
  }
References Math::AbsInt(), GetDayZGame(), GetPlayer(), and ModifiersManager().
IsMouseInScene()
bool PluginBase::IsMouseInScene () inline private
Definition at line 1137 of file PluginSceneManager.c.
  {
    Widget widget_under_mouse = GetWidgetUnderCursor();
    if (widget_under_mouse != NULL && widget_under_mouse.GetName() == "pnl_SceneControl")
      return true;
    return false;
  }
References GetWidgetUnderCursor().
IsOpened()
bool PluginBase::IsOpened () inline private
Definition at line 365 of file PluginSceneManager.c.
  {
    return m_IsOpen;
  }
IsPlayerRegistered()
bool PluginBase::IsPlayerRegistered (PlayerBase player) inline private
Definition at line 219 of file PluginDeveloperSync.c.
  {
    if (m_RegisteredPlayers.Contains(player))
      return true;
    return false;
  }
Referenced by EnableUpdate(), IsSetSystemInBitmask(), RegisterPlayer(), and SetSystemInBitmask().
IsReadOnly()
bool PluginBase::IsReadOnly () inline private
Definition at line 106 of file PluginFileHandler.c.
  {
    return m_ReadOnly;
  }
IsRepairValid()
bool PluginBase::IsRepairValid (int repair_kit_type, int repairable_with_type) inline private
Definition at line 99 of file PluginRepairing.c.
  {
    if (repair_kit_type > 0 && repairable_with_type > 0)
      return repair_kit_type == repairable_with_type;
    return false;
  }
IsRulerActivated()
bool PluginBase::IsRulerActivated () inline private
Definition at line 869 of file PluginSceneManager.c.
  {
    return m_RulerActivated;
  }
IsSetSystemInBitmask()
bool PluginBase::IsSetSystemInBitmask (PlayerBase player, int system_bit) inline private
Definition at line 195 of file PluginDeveloperSync.c.
  {
    if (IsPlayerRegistered(player))
      return (m_RegisteredPlayers.Get(player).m_Bitmask & system_bit);
    return false;
  }
References IsPlayerRegistered().
Referenced by RequestDetailedInfo().
LinkSceneObjects()
void PluginBase::LinkSceneObjects (SceneObject scene_object1, SceneObject scene_object2) inline private
Definition at line 629 of file PluginSceneManager.c.
  {
    scene_object1.LinkSceneObject(scene_object2);
    scene_object2.LinkSceneObject(scene_object1);
  }
LoadFile()
bool PluginBase::LoadFile () inline private
Definition at line 57 of file PluginFileHandler.c.
  {
    ClearFileNoSave();
    FileHandle file_index = OpenFile(GetFileName(), FileMode.READ);
    if (file_index == 0)
      return false;
    string line_content = "";
    int char_count = FGets(file_index, line_content);
    while (char_count != -1)
    {
      m_FileContent.Insert(line_content);
      char_count = FGets(file_index, line_content);
    }
    CloseFile(file_index);
    return true;
  }
References CloseFile(), FGets(), PluginFileHandler::GetFileName(), and OpenFile().
LoadFromCfg()
void PluginBase::LoadFromCfg () inline private
Definition at line 12 of file PluginHorticulture.c.
  {
    string cfg_access = "CfgHorticulture"; // it is stored in dz\gear\cultivation\cfgHorticulture.hpp
    int cfg_horticulture_count = GetGame().ConfigGetChildrenCount(cfg_access);
    for (int i = 0; i < cfg_horticulture_count; i++)
    {
      string cfg_class_name = "";
      GetGame().ConfigGetChildName(cfg_access, i, cfg_class_name);
      string cfg_class_access = cfg_access + " " + cfg_class_name;
      int cfg_class_count = GetGame().ConfigGetChildrenCount(cfg_class_access);
      for (int j = 0; j < cfg_class_count; j++)
      {
        string cfg_subclass_name = "";
        GetGame().ConfigGetChildName(cfg_class_access, j, cfg_subclass_name);
        string cfg_subclass_access = cfg_class_access + " " + cfg_subclass_name;
        int cfg_subclass_count = GetGame().ConfigGetChildrenCount(cfg_subclass_access);
        PlantMaterialHealth plantMaterialHealth = NULL;
        if (cfg_class_name == "Plants")
        {
          plantMaterialHealth = new PlantMaterialHealth;
          m_PlantMaterials.Set(cfg_subclass_name, plantMaterialHealth);
        }
        for (int k = 0; k < cfg_subclass_count; k++)
        {
          string cfg_variable_name = "";
          GetGame().ConfigGetChildName(cfg_subclass_access, k, cfg_variable_name);
          string cfg_variable_access = cfg_subclass_access + " " + cfg_variable_name;
          if (cfg_class_name == "Plants")
          {
            string string_param = "";
            GetGame().ConfigGetText(cfg_variable_access, string_param);
            if (cfg_variable_name == "infestedTex")
              plantMaterialHealth.m_InfestedTex = string_param;
            else if (cfg_variable_name == "infestedMat")
              plantMaterialHealth.m_InfestedMat = string_param;
            else if (cfg_variable_name == "healthyTex")
              plantMaterialHealth.m_HealthyTex = string_param;
            else if (cfg_variable_name == "healthyMat")
              plantMaterialHealth.m_HealthyMat = string_param;
          }
        }
      }
    }
  }
References GetGame().
Referenced by PluginHorticulture(), and PluginLifespan().
Lock()
void PluginBase::Lock (Object target) inline private
Definition at line 31 of file PluginObjectsInteractionManager.c.
  {
    if (target && !IsFree(target))
    {
      m_LockedObjects.Insert(target);
      m_LockedObjectsDecay.Insert(0);
    }
  }
References IsFree().
LockModifier()
void PluginBase::LockModifier (int id, bool lock, PlayerBase player = NULL) inline private
Definition at line 635 of file PluginDeveloperSync.c.
  {
    if (!player)
      player = PlayerBase.Cast(GetDayZGame().GetPlayer());
    ModifiersManager mods_manager = player.GetModifiersManager();
    mods_manager.SetModifierLock(Math.AbsInt(id), lock);
  }
References Math::AbsInt(), GetDayZGame(), GetPlayer(), and ModifiersManager().
Referenced by OnRPC().
Log()
void PluginBase::Log (string msg, string label) inline private
Definition at line 10 of file PluginBase.c.
  {
    Debug.Log(msg, GetModuleName(), "n/a", label, "n/a");
  }
References GetModuleName(), and Debug::Log().
LogPrint()
void PluginBase::LogPrint (string message) inline protected
Definition at line 62 of file PluginAdminLog.c.
  {
    GetGame().AdminLog(message);
  }
References GetGame().
Referenced by BleedingOut(), DirectAdminLogPrint(), OnContinouousAction(), OnPlacementComplete(), PlayerHitBy(), PlayerKilled(), PlayerList(), Suicide(), TotemFlagChange(), UnconStart(), and UnconStop().
MakeTabs()
string PluginBase::MakeTabs (int count, bool inheritance = false) inline private
Definition at line 7 of file PluginConfigViewer.c.
  {
    if (count == 0)
      return "";
    string tabs = "|--";
    if (inheritance)
      tabs = "|<<";
    for (int i = 0; i < count - 1; i++)
      tabs = "|  " + tabs;
    return tabs;
  }
Referenced by GetConfig(), and GetConfigRecursive().
OnChange()
bool PluginBase::OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 341 of file PluginDayZInfectedDebug.c.
  {
    return false;
  }
OnClick()
bool PluginBase::OnClick (Widget w, int x, int y, int button) inline private
buttons clicks
Definition at line 282 of file PluginDayZInfectedDebug.c.
  {
    if (w == m_SpawnEntityButton)
    {
      ResetValues();
      SpawnNewInfectedEntity();
      return true;
    }
    if (w == m_CardMovementButton)
    {
      ShowCard(0);
      return true;
    }
    else if (w == m_CardFightButton)
    {
      ShowCard(1);
      return true;
    }
    else if (w == m_StartTurnButton)
    {
      m_CH_DoTurn = true;
      return true;
    }
    else if (w == m_StartVaultButton)
    {
      m_CH_DoVault = true;
      return true;
    }
    else if (w == m_KnucleOutButton)
    {
      m_CH_DoKnucleOut = true;
      return true;
    }
    else if (w == m_StartCrawlingButton)
    {
      m_CH_GoToCrawl = true;
      return true;
    }
    else if (w == m_StartHitButton)
    {
      m_CH_DoHit = true;
      return true;
    }
    else if (w == m_StartDeathButton)
    {
      m_CH_StartDeath = true;
      return true;
    }
    else if (w == m_StartAttackButton)
    {
      m_CH_DoAttack = true;
      return true;
    }
    return false;
  }
References ResetValues(), ShowCard(), and SpawnNewInfectedEntity().
OnContinouousAction()
void PluginBase::OnContinouousAction (ActionData action_data) inline protected
Definition at line 301 of file PluginAdminLog.c.
  {
    if (m_ActionsFilter == 1)
    {
      m_Message = action_data.m_Action.GetAdminLogMessage(action_data);
      if (m_Message == "")
        return;
      m_PlayerPrefix = GetPlayerPrefix(action_data.m_Player, action_data.m_Player.GetIdentity());
      LogPrint(m_PlayerPrefix + m_Message);
    }
  }
References GetPlayerPrefix(), LogPrint(), and m_ActionsFilter.
OnDamageEvent()
void PluginBase::OnDamageEvent (PlayerBase player, TotalDamageResult damageResult) inline private
Definition at line 90 of file PluginRemotePlayerDebugServer.c.
  {
    if (!GetWatching() || !damageResult)
      return;
    float damage_global = damageResult.GetDamage("", "");
    float damage_blood = damageResult.GetDamage("", "Blood");
    float damage_shock = damageResult.GetDamage("", "Shock");
    if (m_PlayerDebugDamage.Contains(player))
      m_PlayerDebugDamage.Get(player).AddDamage(damage_global, damage_blood, damage_shock);
    else
    {
      RemotePlayerDamageDebug rpdd = new RemotePlayerDamageDebug(player);
      rpdd.AddDamage(damage_global, damage_blood, damage_shock);
      m_PlayerDebugDamage.Insert(player, rpdd);
    }
  }
References m_PlayerDebugDamage.
OnDestroy() [1/5]
void PluginBase::OnDestroy () private
OnDestroy() [2/5]
override void PluginBase::OnDestroy () inline private
Definition at line 64 of file PluginCharPlacement.c.
  {
    FreeDebugCamera.GetInstance().SetFOV(g_Game.GetUserFOV());
  }
References g_Game.
OnDestroy() [3/5]
override void PluginBase::OnDestroy () inline private
Definition at line 116 of file PluginKeyBinding.c.
  {
    GetGame().GetUpdateQueue(CALL_CATEGORY_SYSTEM).Remove(this.OnFrame);
  }
References CALL_CATEGORY_SYSTEM, and GetGame().
OnDestroy() [4/5]
override void PluginBase::OnDestroy () inline private
Definition at line 58 of file PluginSceneManager.c.
  {
    SceneUnload();
  }
OnDestroy() [5/5]
override void PluginBase::OnDestroy () inline private
Definition at line 14 of file PluginSoundDebug.c.
  {
    m_TickTimer = NULL;
  }
References m_TickTimer.
OnFrame()
void PluginBase::OnFrame () inline private
Definition at line 236 of file PluginKeyBinding.c.
  {
    for (int i = 0; i < m_MouseButtons.Count(); ++i)
    {
      MouseButtonInfo info = m_MouseButtons.Get(i);
      if (info.IsButtonDown())
      {
        int time_curr = GetGame().GetTime();
        int time_hold = info.GetTimeLastPress() + HOLD_CLICK_TIME_MIN;
        if (time_hold < time_curr)
        {
          //Log("MB_EVENT_DRAG");
          OnMouse(MB_EVENT_DRAG, info.GetButtonID());
        }
      }
    }
  }
References GetGame(), and MB_EVENT_DRAG.
OnGUITimer()
void PluginBase::OnGUITimer () inline private
Definition at line 30 of file PluginSoundDebug.c.
  {
    DbgUI.BeginCleanupScope();
    DbgUI.Begin("Sound debug", 10, 10);
    DbgUI.PushID_Str("SoundParams");
    DbgUI.Text("SoundParams: ");
    DbgUI.SameLine();
    string soundsetName = "BearGrowl_SoundSet";
    DbgUI.InputText("", soundsetName, 200);
    DbgUI.PopID();
    DbgUI.PushID_Str("Offset");
    DbgUI.Text("Offset pos: ");
    vector posOffset = "0 0 0";
    float posVal;
    DbgUI.SameLine();
    DbgUI.PushID_Int(1);
    DbgUI.InputFloat("", posVal, 80);
    DbgUI.PopID();
    posOffset[0] = posVal;
    DbgUI.SameLine();
    DbgUI.PushID_Int(2);
    DbgUI.InputFloat("", posVal, 80);
    DbgUI.PopID();
    posOffset[1] = posVal;
    DbgUI.SameLine();
    DbgUI.PushID_Int(3);
    DbgUI.InputFloat("", posVal, 80);
    DbgUI.PopID();
    posOffset[2] = posVal;
    DbgUI.PopID();
    if (DbgUI.Button("Create"))
    {
      m_soundParams = new SoundParams(soundsetName);
      m_soundBuilder = new SoundObjectBuilder(m_soundParams);
      m_soundObject = m_soundBuilder.BuildSoundObject();
      m_soundObject.SetPosition(GetGame().GetPlayer().GetPosition() + posOffset);
    }
    DbgUI.Text("SoundObjectBuilder: ");
    DbgUI.Text("SoundObject: ");
    DbgUI.Text("AbstractWave: ");
    vector posOffset2 = "0 10 0";
    if (m_soundParams != NULL)
    {
      DbgUI.Text("FadeInFactor: ");
      DbgUI.SameLine();
      DbgUI.PushID_Str("fadeIn");
      DbgUI.InputFloat("", fadeInVolume, 80);
      DbgUI.PopID();
      DbgUI.Text("FadeOutFactor: ");
      DbgUI.SameLine();
      DbgUI.PushID_Str("fadeOut");
      DbgUI.InputFloat("", fadeOutVolume, 80);
      DbgUI.PopID();
      DbgUI.PushID_Str("Offset2");
      DbgUI.Text("Offset2 pos: ");
      float posVal2;
      DbgUI.SameLine();
      DbgUI.PushID_Int(100);
      posVal2 = posOffset2[0];
      DbgUI.InputFloat("", posVal2, 80);
      DbgUI.PopID();
      posOffset2[0] = posVal2;
      DbgUI.SameLine();
      DbgUI.PushID_Int(101);
      posVal2 = posOffset2[1];
      DbgUI.InputFloat("", posVal2, 80);
      DbgUI.PopID();
      posOffset2[1] = posVal2;
      DbgUI.SameLine();
      DbgUI.PushID_Int(102);
      posVal2 = posOffset2[2];
      DbgUI.InputFloat("", posVal2, 80);
      DbgUI.PopID();
      posOffset2[2] = posVal2;
      DbgUI.PopID();
      DbgUI.Text("skip: ");
      DbgUI.SameLine();
      float skip = 0.0;
      DbgUI.PushID_Int(200);
      DbgUI.InputFloat("", skip, 80);
      DbgUI.PopID();
      if (DbgUI.Button("Create and play"))
      {
        m_wave = GetGame().GetSoundScene().Play3D(m_soundObject, m_soundBuilder);
        m_wave.SetFadeInFactor(fadeInVolume);
        m_wave.Skip(skip);
        m_wave.SetPosition(GetGame().GetPlayer().GetPosition() + posOffset2);
      }
    }
    if (m_wave != NULL)
    {
      DbgUI.Text("Wave length: " + m_wave.GetLength() + "s");
      //DbgUI.Text("Wave position: " + Math.Round(m_wave.GetCurrPosition() * 100) + "%");
      DbgUI.Text("Volume: ");
      DbgUI.SameLine();
      float volume = 1.0;
      DbgUI.InputFloat(" ", volume, 80);
      DbgUI.SameLine();
      if (DbgUI.Button("SetVolume"))
        m_wave.SetVolume(volume);
      DbgUI.SameLine();
      if (DbgUI.Button("SetVolumeRelative"))
        m_wave.SetVolumeRelative(volume);
      if (DbgUI.Button("Play"))
        m_wave.Play();
      if (DbgUI.Button("Stop"))
        m_wave.Stop();
      if (DbgUI.Button("Restart"))
        m_wave.Restart();
      if (DbgUI.Button("Repeat"))
        m_wave.Loop(true);
      if (DbgUI.Button("StopRepeat"))
        m_wave.Loop(false);
      if (DbgUI.Button("Set position"))
        m_wave.SetPosition(GetGame().GetPlayer().GetPosition() + posOffset2);
    }
    DbgUI.End();
    DbgUI.EndCleanupScope();
  }
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::Button(), DbgUI::End(), DbgUI::EndCleanupScope(), GetGame(), GetPlayer(), GetPosition, DbgUI::InputFloat(), DbgUI::InputText(), DbgUI::PopID(), DbgUI::PushID_Int(), DbgUI::PushID_Str(), DbgUI::SameLine(), SoundObjectBuilder(), and DbgUI::Text().
OnInit() [1/9]
void PluginBase::OnInit () private
OnInit() [2/9]
override void PluginBase::OnInit () inline protected
Definition at line 6 of file PluginCameraTools.c.
  {
    m_Instance = this;
  }
References m_Instance.
OnInit() [3/9]
override void PluginBase::OnInit () inline protected
Definition at line 48 of file PluginDeveloper.c.
  {
    super.OnInit();
    DeveloperFreeCamera.OnInit();
  }
References DeveloperFreeCamera::OnInit().
OnInit() [4/9]
override void PluginBase::OnInit () inline protected
Definition at line 20 of file PluginUniversalTemperatureSourceClient.c.
  {
#ifndef NO_GUI
    InitWidgets();
#endif
  }
References InitWidgets().
OnInit() [5/9]
override void PluginBase::OnInit () inline private
Definition at line 64 of file PluginDeveloperSync.c.
  {
    super.OnInit();
    if (GetGame().IsServer())
    {
      //create timer
      m_UpdateTimer = new Timer(CALL_CATEGORY_GAMEPLAY);
    }
  }
References CALL_CATEGORY_GAMEPLAY, GetGame(), and m_UpdateTimer.
OnInit() [6/9]
override void PluginBase::OnInit () inline private
Definition at line 37 of file PluginFileHandler.c.
  {
    super.OnInit();
  }
OnInit() [7/9]
override void PluginBase::OnInit () inline private
Definition at line 28 of file PluginKeyBinding.c.
  {
    super.OnInit();
    m_KeyBindings = new array<ref KeyBinding>;
    m_MouseBindings = new array<ref MouseBinding>;
    m_MouseButtons = new array<ref MouseButtonInfo>;
    m_MouseButtons.Insert(new MouseButtonInfo(MouseState.LEFT));
    m_MouseButtons.Insert(new MouseButtonInfo(MouseState.RIGHT));
    m_MouseButtons.Insert(new MouseButtonInfo(MouseState.MIDDLE));
    GetGame().GetUpdateQueue(CALL_CATEGORY_SYSTEM).Insert(this.OnFrame);
    //Keyboard Binds  |UI_ID              |Key1         |Key2       |Callback Plugin    |Callback Function        |Info Shrtcut         |Info Description
    //------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    // |constants.h          |constants.h      |constants.h    |only plugin name   |only function          |               |
    // |MENU_***           |KeyCode.KC_***     |KeyCode.KC_***   |           |in plugin            |               |
    //------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#ifdef DEVELOPER
    RegisterKeyBind(MENU_ANY, KeyCode.KC_LCONTROL, KeyCode.KC_F1, "PluginDeveloper", "ToggleHelpScreen", "[LCTRL]+[F1]", "Show/Hide help screen");
    RegisterKeyBind(MENU_ANY, KeyCode.KC_LCONTROL, KeyCode.KC_F2, "PluginDeveloper", "ResetGUI", "[LCTRL]+[F2]", "Resets shown UI for testing purposes");
    RegisterKeyBind(MENU_NONE | MENU_SCRIPTCONSOLE, KeyCode.KC_LCONTROL, KeyCode.KC_GRAVE, "PluginDeveloper", "ToggleScriptConsole", "[LCTRL]+[~]", "Show/Hide this script console");
    RegisterKeyBind(MENU_NONE | MENU_SCRIPTCONSOLE, KeyCode.KC_RCONTROL, KeyCode.KC_GRAVE, "PluginDeveloper", "ToggleScriptConsole", "[RCTRL]+[~]", "Show/Hide this script console");
    RegisterKeyBind(MENU_NONE | MENU_SCENE_EDITOR, KeyCode.KC_LCONTROL, KeyCode.KC_TAB, "PluginSceneManager", "EditorToggle", "[LCTRL]+[TAB]", "Show/Hide Scripted Scene Editor");
    RegisterKeyBind(MENU_NONE | MENU_SCENE_EDITOR, KeyCode.KC_RCONTROL, KeyCode.KC_TAB, "PluginSceneManager", "EditorToggle", "[RCTRL]+[TAB]", "Show/Hide Scripted Scene Editor");
    RegisterKeyBind(MENU_NONE, KeyCode.KC_LCONTROL, KeyCode.KC_V, "PluginDeveloper", "SpawnFromClipboard", "[Right Shift]", "Spawn item from clipboard");
#endif
#ifdef DIAG_DEVELOPER
    RegisterKeyBind(MENU_NONE, KeyCode.KC_INSERT, -1, "PluginDeveloper", "TeleportAtCursor", "[Insert]", "Teleport player to cursor position");
    RegisterKeyBind(MENU_NONE, KeyCode.KC_HOME, -1, "PluginDeveloper", "ToggleFreeCamera", "[Home]", "Toggle free camera and teleport player to its position");
    RegisterKeyBind(MENU_NONE, KeyCode.KC_DIVIDE, -1, "PluginDeveloper", "ToggleFreeCameraBackPos", "[Divide numeric]", "Toggle free camera, no player teleport");
    RegisterKeyBind(MENU_NONE, KeyCode.KC_LCONTROL, KeyCode.KC_NUMPAD9, "PluginDeveloperSync", "ToggleFocus", "[LCtrl]+[NUMPAD9]", "Toggle game focus");
#endif
#ifdef DEVELOPER
    RegisterKeyBind(MENU_NONE, KeyCode.KC_LCONTROL, KeyCode.KC_Z, "PluginDeveloper", "SetDeveloperItemClient", "Starts watching the item", "Sets the target as Watched item for debug purposes");
    RegisterKeyBind(MENU_SCRIPTCONSOLE, KeyCode.KC_PRIOR, -1, "PluginDeveloper", "ScriptHistoryBack", "[Page Up]", "Debug Console => Script history back");
    RegisterKeyBind(MENU_SCRIPTCONSOLE, KeyCode.KC_NEXT, -1, "PluginDeveloper", "ScriptHistoryNext", "[Page Down]", "Debug Console => Script history next");
    RegisterKeyBind(MENU_SCENE_EDITOR, KeyCode.KC_DELETE, -1, "PluginSceneManager", "DeleteSelectedObject", "[Delete]", "Scene Editor => Delete current selected object");
    RegisterKeyBind(MENU_SCENE_EDITOR, KeyCode.KC_LCONTROL, KeyCode.KC_S, "PluginSceneManager", "SceneSave", "[LCtrl]+[S]", "Scene Editor => Save Current Scene");
    RegisterKeyBind(MENU_SCENE_EDITOR, KeyCode.KC_LCONTROL, KeyCode.KC_D, "PluginSceneManager", "SelectedObjectDuplicate", "[LCtrl]+[D]", "Scene Editor => Duplicate current selected object");
    RegisterKeyBind(MENU_SCENE_EDITOR, KeyCode.KC_LCONTROL, KeyCode.KC_F, "PluginSceneManager", "SelectedObjectFocus", "[LCtrl]+[F]", "Scene Editor => Focus camera on selected object");
    RegisterKeyBind(MENU_SCENE_EDITOR, KeyCode.KC_LCONTROL, KeyCode.KC_E, "PluginSceneManager", "RulerToggle", "[LCtrl]+[E]", "Scene Editor => Enable/Disable addition of ruler points");
    RegisterKeyBind(MENU_NONE, KeyCode.KC_LCONTROL, KeyCode.KC_PRIOR, "PluginRecipesManager", "CallbackGenerateCache", "[LCtrl]+[BACKSPACE]", "PluginRecipesManager => Generate recipe cache and save it to file");
    RegisterKeyBind(MENU_ANY, KeyCode.KC_LCONTROL, KeyCode.KC_DECIMAL, "PluginItemDiagnostic", "ToggleDebugWindowEvent", "[LCtrl]+[DECIMAL]", "Close the Item Debug window");
    RegisterKeyBind(MENU_ANY, KeyCode.KC_LCONTROL, KeyCode.KC_NUMPAD0, "PluginDayzPlayerDebug", "ToggleDebugWindowEvent", "[LCtrl]+[NUMPAD0]", "Open/Close Player debug window");
    RegisterKeyBind(MENU_ANY, KeyCode.KC_LCONTROL, KeyCode.KC_DECIMAL, "PluginDayzPlayerDebug", "ToggleDebugWindowEventP", "[LCtrl]+[DECIMAL]", "Open/Close Player debug window");
    RegisterKeyBind(MENU_ANY, KeyCode.KC_LCONTROL, KeyCode.KC_I, "PluginDayZInfectedDebug", "ToggleDebugWindowEvent", "[LCtrl]+[NUMPAD1]", "Open/Close Infected debug window");
    RegisterKeyBind(MENU_ANY, KeyCode.KC_LCONTROL, KeyCode.KC_O, "PluginDayZInfectedDebug", "PossesInfected", "[LCtrl]+[NUMPAD1]", "Open/Close Infected debug window");
    RegisterKeyBind(MENU_NONE, KeyCode.KC_LCONTROL, KeyCode.KC_SCROLL, "PluginNutritionDumper", "CheckInit", "[LCtrl]+[SCROLL LOCK]", "Enable Door Ruler");
    RegisterKeyBind(MENU_NONE, KeyCode.KC_LCONTROL, KeyCode.KC_RBRACKET, "PluginCharPlacement", "CheckInit", "[LCtrl]+[)]", "Enable CharPlacer");
    RegisterKeyBind(MENU_NONE | MENU_CAMERA_TOOLS, KeyCode.KC_LCONTROL, KeyCode.KC_K, "PluginCameraTools", "ToggleCameraTools", "[LCtrl]+[K]", "Toggle Camera Recording Tools");
    RegisterKeyBind(MENU_CAMERA_TOOLS, KeyCode.KC_LCONTROL, KeyCode.KC_S, "PluginCameraTools", "Save", "[X]", "Recording Tools => Start Recording Camera Path");
    RegisterKeyBind(MENU_CAMERA_TOOLS, KeyCode.KC_P, -1, "PluginCameraTools", "PlayPause", "[C]", "Recording Tools => Stop Recording Camera Path");
    RegisterKeyBind(MENU_CAMERA_TOOLS, KeyCode.KC_LCONTROL, KeyCode.KC_Q, "PluginCameraTools", "AddKeyframe", "[C]", "Recording Tools => Add Camera Point");
    RegisterKeyBind(MENU_CAMERA_TOOLS, KeyCode.KC_LCONTROL, KeyCode.KC_E, "PluginCameraTools", "DeleteKeyframe", "[V]", "Recording Tools => Play Camera Line");
    //--------------------------------------------------------------------------------------------------------------------------------------------------------------
    // Mouses Binds   |UI_ID        |Mouse Button |Mouse Event      |Callback Plugin    |Callback Function      |Info Shrtcut     |Info Description
    //----------------------------------------------------------------------------------------------------------------------------------------------------------------
    // |constants.h    |MouseState.LEFT    |MB_EVENT_CLICK     |only plugin name   |only function        |           |
    // |MENU_***     |MouseState.RIGHT   |MB_EVENT_DOUBLECLICK   |           |in plugin          |           |
    // |MouseState.MIDDLE    |MB_EVENT_DRAG      |           |             |           |
    // |           |MB_EVENT_RELEASE   |           |             |           |
    //--------------------------------------------------------------------------------------------------------------------------------------------------------------
    RegisterMouseBind(MENU_SCENE_EDITOR, MouseState.LEFT, MB_EVENT_CLICK, "PluginSceneManager", "Event_OnClick", "[LMB] Click", "Mission Editor => Select object in scene");
    RegisterMouseBind(MENU_SCENE_EDITOR, MouseState.LEFT, MB_EVENT_DOUBLECLICK, "PluginSceneManager", "Event_OnDoubleClick", "[LMB] Double Click", "Mission Editor => Craete new object in scene");
    RegisterMouseBind(MENU_SCENE_EDITOR, MouseState.LEFT, MB_EVENT_DRAG, "PluginSceneManager", "Event_OnDrag", "[LMB] Hold", "Mission Editor => Moving with selected object");
    RegisterMouseBind(MENU_SCENE_EDITOR, MouseState.MIDDLE, MB_EVENT_CLICK, "PluginSceneManager", "Event_OnClickMiddle", "[MMB] Click", "Mission Editor => Link clicked object with selected object");
    RegisterMouseBind(MENU_SCENE_EDITOR, MouseState.RIGHT, MB_EVENT_PRESS, "PluginSceneManager", "FreeCameraControlEnable", "[RMB] Hold", "Mission Editor => Enable camera movement");
    RegisterMouseBind(MENU_SCENE_EDITOR, MouseState.RIGHT, MB_EVENT_RELEASE, "PluginSceneManager", "FreeCameraControlDisable", "[RMB] Release", "Mission Editor => Disable camera movement");
    RegisterMouseBind(MENU_NONE, MouseState.LEFT, MB_EVENT_CLICK, "PluginDayZCreatureAIDebug", "Event_OnClick", "[LMB] Click", "DayZCreature graph debug => Capture entity during capture mode");
    RegisterMouseBind(MENU_CAMERA_TOOLS, MouseState.RIGHT, MB_EVENT_RELEASE, "PluginCameraTools", "CursorShow", "[LMB] Click", "DayZCreature graph debug => Capture entity during capture mode");
    // TO DO: (Boris V.) Remove the following commented-out mouse binds when weapon particles can be implemented properly. Also remove the events they call.
    //RegisterMouseBind(  MENU_NONE     ,MouseState.LEFT    ,MB_EVENT_PRESS     ,"PluginDeveloper"    ,"MuzzleParticleTestStart"  ,"[LMB] Hold"     ,"Debug particle");
    //RegisterMouseBind(  MENU_NONE     ,MouseState.LEFT    ,MB_EVENT_RELEASE   ,"PluginDeveloper"    ,"MuzzleParticleTestEnd"  ,"[LMB] Release"    ,"Debug particle2");
#endif
    //--------------------------------------------------------------------------------------------------------------------------------------------------------------
  }
References CALL_CATEGORY_SYSTEM, GetGame(), MB_EVENT_CLICK, MB_EVENT_DOUBLECLICK, MB_EVENT_DRAG, MB_EVENT_PRESS, MB_EVENT_RELEASE, MENU_ANY, MENU_CAMERA_TOOLS, MENU_NONE, MENU_SCENE_EDITOR, and MENU_SCRIPTCONSOLE.
OnInit() [8/9]
override void PluginBase::OnInit () inline private
Definition at line 42 of file PluginSceneManager.c.
  {
    m_ModuleDeveloper = PluginDeveloper.Cast(GetPlugin(PluginDeveloper));
    m_ModuleConfigScene = PluginConfigScene.Cast(GetPlugin(PluginConfigScene));
    m_ModuleConfigDebugProfile = PluginConfigDebugProfile.Cast(GetPlugin(PluginConfigDebugProfile));
    //Ruler
    m_RulerActivated = false;
    m_RulerPoints = new array<vector>;
    m_RulerLines = new array<Shape>;
    m_RulerSpheres = new array<Shape>;
  }
References GetPlugin().
OnInit() [9/9]
override void PluginBase::OnInit () inline private
Definition at line 3 of file PluginSoundDebug.c.
  {
    m_TickTimer = new Timer();
    m_TickTimer.Run(0.1, this, "OnGUITimer", NULL, true);
  }
References m_TickTimer.
OnKeyPress()
void PluginBase::OnKeyPress (int key) inline private
Definition at line 124 of file PluginKeyBinding.c.
  {
    //Print("OnKeyPress "+ key );
    for (int i = 0; i < m_KeyBindings.Count(); ++i)
    {
      KeyBinding key_binding = m_KeyBindings.Get(i);
      if (!IsCurrentUIPageValid(key_binding.GetUIMenuID()))
        continue;
      bool key1_match = false;
      bool key2_match = false;
      if (key_binding.GetKey1() > -1)
      {
        if (IsKeyPressed(key_binding.GetKey1()))
        {
          // Key1 is down
          key1_match = true;
        }
      }
      else
      {
        // Key1 is not set
        key1_match = true;
      }
      if (key_binding.GetKey2() > -1)
      {
        if (IsKeyPressed(key_binding.GetKey2()))
        {
          // Key2 is down
          key2_match = true;
        }
      }
      else
      {
        // Key2 is not set
        key2_match = true;
      }
      if (key1_match && key2_match)
      {
        //Log( "Call Method -> key press: " + itoa(key) + " " + key_binding.GetInfoDescription() );
        PluginBase m = GetPlugin(key_binding.GetCallbackTarget().ToType());
        GetGame().GameScript.CallFunction(m, key_binding.GetCallbackFunction(), NULL, 0);
        break;
      }
    }
  }
References GetGame(), and GetPlugin().
OnKeyRelease()
void PluginBase::OnKeyRelease (int key) inline private
Definition at line 181 of file PluginKeyBinding.c.
  {
  }
OnMouse()
void PluginBase::OnMouse (int event_id, int button) inline protected
Definition at line 327 of file PluginKeyBinding.c.
  {
    for (int i = 0; i < m_MouseBindings.Count(); ++i)
    {
      MouseBinding mouse_binding = m_MouseBindings.Get(i);
      if (mouse_binding.GetButtonID() == button && mouse_binding.GetMouseEvent() == event_id)
      {
        if (IsCurrentUIPageValid(mouse_binding.GetUIMenuID()))
        {
          PluginBase m = GetPlugin(mouse_binding.GetCallbackTarget().ToType());
          GetGame().GameScript.CallFunction(m, mouse_binding.GetCallbackFunction(), NULL, 0);
        }
      }
    }
  }
References GetGame(), and GetPlugin().
OnMouseButtonPress()
void PluginBase::OnMouseButtonPress (int button) inline private
Definition at line 188 of file PluginKeyBinding.c.
  {
    MouseButtonInfo button_info = GetMouseButtonInfo(button);
    if (button_info == NULL) return;
    button_info.Press();
    //Log("****************************");
    //Log(" MB_EVENT_PRESS");
    OnMouse(MB_EVENT_PRESS, button);
  }
References MB_EVENT_PRESS.
OnMouseButtonRelease()
void PluginBase::OnMouseButtonRelease (int button) inline private
Definition at line 203 of file PluginKeyBinding.c.
  {
    MouseButtonInfo button_info = GetMouseButtonInfo(button);
    if (button_info == NULL) return;
    int time_curr = GetGame().GetTime();
    int time_last_press = button_info.GetTimeLastPress();
    int time_last_release = button_info.GetTimeLastRelease();
    int time_delta_press = time_curr - time_last_press;
    int time_delta_relase = time_curr - time_last_release;
    if (time_delta_relase < DOUBLE_CLICK_TIME)
    {
      //Log(" DOUBLE_CLICK_TIME ");
      OnMouse(MB_EVENT_DOUBLECLICK, button);
    }
    else if (time_delta_press < CLICK_TIME)
    {
      //Log(" MB_EVENT_CLICK ");
      OnMouse(MB_EVENT_CLICK, button);
    }
    //Log(" MB_EVENT_RELEASE");
    OnMouse(MB_EVENT_RELEASE, button);
    button_info.Release();
  }
References GetGame(), MB_EVENT_CLICK, MB_EVENT_DOUBLECLICK, and MB_EVENT_RELEASE.
OnMouseWheel()
void PluginBase::OnMouseWheel (int wheel) inline private
Definition at line 66 of file PluginSceneManager.c.
  {
    if (!IsMouseInScene())
      return;
    if (GetSelectedSceneObject())
      GetSelectedSceneObject().AddRotation(GetRotationAngle() * wheel);
    EditorUpdate();
  }
OnPlacementComplete()
void PluginBase::OnPlacementComplete (Man player, ItemBase item) inline protected
Definition at line 286 of file PluginAdminLog.c.
  {
    if (m_PlacementFilter == 1)
    {
      m_Source = PlayerBase.Cast(player);
      m_PlayerPrefix = GetPlayerPrefix(m_Source, m_Source.GetIdentity());
      m_DisplayName = item.GetDisplayName();
      if (m_DisplayName == "")
        LogPrint(m_PlayerPrefix + " placed unknown object");
      else
        LogPrint(m_PlayerPrefix + " placed " + m_DisplayName);
    }
  }
References GetPlayerPrefix(), and LogPrint().
OnRequestReceived() [1/2]
void PluginBase::OnRequestReceived (PlayerBase player, bool enable) inline private
Definition at line 110 of file PluginRemotePlayerDebugServer.c.
  {
    int index = m_ClientList.Find(player);
    if (enable)
    {
      m_ClientList.Insert(player);
      SetWatching(true);
    }
    else if (index != -1 && m_ClientList.Count() != 0)
      m_ClientList.Remove(index);
    if (m_ClientList.Count() == 0)
      SetWatching(false);
  }
Referenced by OnRPC().
OnRequestReceived() [2/2]
void PluginBase::OnRequestReceived (PlayerBase player, bool enable) inline protected
Definition at line 98 of file PluginUniversalTemperatureSourceServer.c.
  {
    int index = m_ClientList.Find(player);
    if (enable)
      m_ClientList.Insert(player);
    else if (index != -1 && m_ClientList.Count() > 0)
      m_ClientList.Remove(index);
  }
OnRPC() [1/5]
void PluginBase::OnRPC (ParamsReadContext ctx) inline protected
Definition at line 215 of file PluginUniversalTemperatureSourceClient.c.
  {
    //Debug.Log("OnRPC called", "PluginUniversalTemperatureSourceClient");
    //PrintedDebug();
    ctx.Read(m_UTemperatureSourceDebugs);
  }
OnRPC() [2/5]
void PluginBase::OnRPC (ParamsReadContext ctx, PlayerBase player) inline private
Definition at line 126 of file PluginRemotePlayerDebugServer.c.
  {
    bool enable;
    ctx.Read(enable);
    OnRequestReceived(player, enable);
  }
OnRPC() [3/5]
void PluginBase::OnRPC (ParamsReadContext ctx, PlayerBase player) inline protected
Definition at line 108 of file PluginUniversalTemperatureSourceServer.c.
  {
    bool enable;
    ctx.Read(enable);
    OnRequestReceived(player, enable);
  }
References OnRequestReceived().
OnRPC() [4/5]
void PluginBase::OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx) inline protected
Definition at line 55 of file PluginDeveloper.c.
  {
#ifdef DIAG_DEVELOPER
    switch (rpc_type)
    {
    case ERPCs.DEV_RPC_SPAWN_ITEM_ON_GROUND:
    {
      OnRPCSpawnEntityOnGround(player, ctx); break;
    }
    case ERPCs.DEV_RPC_SPAWN_ITEM_ON_GROUND_PATTERN_GRID:
    {
      OnRPCSpawnEntityOnGroundPatternGrid(player, ctx); break;
    }
    case ERPCs.DEV_RPC_SPAWN_ITEM_ON_CURSOR:
    {
      OnRPCSpawnEntityOnCursorDir(player, ctx); break;
    }
    case ERPCs.DEV_RPC_SPAWN_ITEM_IN_INVENTORY:
    {
      OnRPCSpawnEntity(player, ctx); break;
    }
    case ERPCs.DEV_RPC_CLEAR_INV:
    {
      OnRPCClearInventory(player); break;
    }
    case ERPCs.DEV_RPC_SEND_SERVER_LOG:
    {
      OnRPCServerLogRecieved(ctx); break;
    }
    case ERPCs.RPC_SYNC_SCENE_OBJECT:
    {
      OnRPCSyncSceneObject(ctx); break;
    }
    case ERPCs.DEV_RPC_PLUGIN_DZCREATURE_DEBUG:
    {
      OnRPCPluginDayzCreatureDebug(player, rpc_type, ctx); break;
    }
    case ERPCs.DEV_RPC_SPAWN_PRESET:
    {
      string presetName;
      EntityAI target;
      ctx.Read(presetName);
      ctx.Read(target);
      HandlePresetSpawn(player, presetName, target); break;
    }
    case ERPCs.DEV_RPC_SET_TIME:
    {
      HandleSetTime(player, ctx); break;
    }
    }
    DeveloperTeleport.OnRPC(player, rpc_type, ctx);
#endif
  }
References HandlePresetSpawn(), HandleSetTime(), DeveloperTeleport::OnRPC(), OnRPCClearInventory(), OnRPCPluginDayzCreatureDebug(), OnRPCServerLogRecieved(), OnRPCSpawnEntity(), OnRPCSpawnEntityOnCursorDir(), OnRPCSpawnEntityOnGround(), OnRPCSpawnEntityOnGroundPatternGrid(), and OnRPCSyncSceneObject().
OnRPC() [5/5]
void PluginBase::OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx) inline private
Definition at line 230 of file PluginDeveloperSync.c.
  {
    if (!GetGame().IsDebug())
      return;
    switch (rpc_type)
    {
    case ERPCs.DEV_STATS_UPDATE:
    {
      EnableUpdate(GetRPCUpdateState(ctx), ERPCs.DEV_STATS_UPDATE, player); break;
    }
    case ERPCs.DEV_LEVELS_UPDATE:
    {
      EnableUpdate(GetRPCUpdateState(ctx), ERPCs.DEV_LEVELS_UPDATE, player); break;
    }
    case ERPCs.DEV_MODS_UPDATE:
    {
      EnableUpdate(GetRPCUpdateState(ctx), ERPCs.DEV_MODS_UPDATE, player); break;
    }
    case ERPCs.DEV_AGENTS_UPDATE:
    {
      EnableUpdate(GetRPCUpdateState(ctx), ERPCs.DEV_AGENTS_UPDATE, player); break;
    }
    case ERPCs.DEV_STOMACH_UPDATE:
    {
      EnableUpdate(GetRPCUpdateState(ctx), ERPCs.DEV_STOMACH_UPDATE, player); break;
    }
    case ERPCs.DEV_RPC_STATS_DATA:
    {
      OnRPCStats(ctx); break;
    }
    case ERPCs.DEV_RPC_LEVELS_DATA:
    {
      OnRPCLevels(ctx); break;
    }
    case ERPCs.DEV_RPC_MODS_DATA:
    {
      OnRPCMods(ctx); break;
    }
    case ERPCs.DEV_RPC_MODS_DATA_DETAILED:
    {
      OnRPCModsDetailed(ctx); break;
    }
    case ERPCs.DEV_RPC_AGENTS_DATA:
    {
      OnRPCAgents(ctx); break;
    }
    case ERPCs.DEV_RPC_STOMACH_DATA:
    {
      OnRPCStomach(ctx); break;
    }
    case ERPCs.DEV_RPC_MODS_ACTIVATE:
    {
      ActivateModifier(GetRPCModifierID(ctx), player); break;
    }
    case ERPCs.DEV_RPC_MODS_DETAILED:
    {
      RequestDetailedInfo(GetRPCModifierID(ctx), player); break;
    }
    case ERPCs.DEV_RPC_MODS_DEACTIVATE:
    {
      DeactivateModifier(GetRPCModifierID(ctx), player); break;
    }
    case ERPCs.DEV_RPC_MODS_LOCK:
    {
      int id;
      bool lock;
      GetRPCModifierLock(ctx, id, lock);
      LockModifier(id, lock, player); break;
    }
    case ERPCs.DEV_RPC_MODS_RESET:
    {
      player.GetModifiersManager().DeactivateAllModifiers();
      break;
    }
    case ERPCs.DEV_RPC_STATS_RESET:
    {
      player.GetPlayerStats().ResetAllStats();
      break;
    }
    case ERPCs.DEV_RPC_STAT_SET:
    {
      OnRPCStatSet(ctx, player);
      break;
    }
    case ERPCs.DEV_TEMP_UPDATE:
    {
      OnRPCTemp(ctx, player);
      break;
    }
    }
  }
References ActivateModifier(), DeactivateModifier(), EnableUpdate(), GetGame(), GetRPCModifierID(), GetRPCModifierLock(), GetRPCUpdateState(), LockModifier(), OnRPCAgents(), OnRPCLevels(), OnRPCMods(), OnRPCModsDetailed(), OnRPCStats(), OnRPCStatSet(), OnRPCStomach(), OnRPCTemp(), and RequestDetailedInfo().
OnRPCAgents()
void PluginBase::OnRPCAgents (ParamsReadContext ctx) inline private
Definition at line 696 of file PluginDeveloperSync.c.
  {
    //clear values
    m_PlayerAgentsSynced.Clear();
    Param3<string, string, int> p3 = new Param3<string, string, int>("", "", 0);
    Param1<int> p1 = new Param1<int>(0);
    //get param count
    int param_count = 0;
    if (ctx.Read(p1))
      param_count = p1.param1;
    //read values and set
    for (int i = 0; i < param_count; i++)
    {
      ctx.Read(p3);
      m_PlayerAgentsSynced.Insert(new SyncedValueAgent(p3.param1, p3.param2, p3.param3));
    }
  }
References SyncedValueAgent().
Referenced by OnRPC().
OnRPCClearInventory()
void PluginBase::OnRPCClearInventory (PlayerBase player) inline protected
Definition at line 230 of file PluginDeveloper.c.
  {
    ClearInventory(player);
  }
References ClearInventory().
Referenced by OnRPC().
OnRPCLevels()
void PluginBase::OnRPCLevels (ParamsReadContext ctx) inline private
Definition at line 483 of file PluginDeveloperSync.c.
  {
    //clear values
    m_PlayerLevelsSynced.Clear();
    Param3<string, float, float> p3 = new Param3<string, float, float>("", 0, 0);
    //get param count
    int param_count = 0;
    if (ctx.Read(p3))
      param_count = p3.param2;
    //read values and set
    for (int i = 0; i < param_count; i++)
    {
      if (ctx.Read(p3))
        m_PlayerLevelsSynced.Insert(new SyncedValueLevel(p3.param1, p3.param2, p3.param3));
    }
  }
References SyncedValueLevel().
Referenced by OnRPC().
OnRPCMods()
void PluginBase::OnRPCMods (ParamsReadContext ctx) inline private
Definition at line 557 of file PluginDeveloperSync.c.
  {
    //clear values
    m_PlayerModsSynced.Clear();
    //ref Param3<string, float, bool> p = new Param3<string, float, bool>( "", 0, false );
    Param1<int> p1 = new Param1<int>(0);
    Param4<int, string, bool, bool> p4 = new Param4<int, string, bool, bool>(0, "", false, false);
    //get param count
    int param_count = 0;
    if (ctx.Read(p1))
      param_count = (int) p1.param1;
    //read values and set
    for (int i = 0; i < param_count; i++)
    {
      if (ctx.Read(p4))
        m_PlayerModsSynced.Insert(new SyncedValueModifier(p4.param1, p4.param2, p4.param3, p4.param4));
    }
  }
Referenced by OnRPC().
OnRPCModsDetailed()
void PluginBase::OnRPCModsDetailed (ParamsReadContext ctx) inline private
Definition at line 578 of file PluginDeveloperSync.c.
  {
    Param1<string> p1 = new Param1<string>("");
    //get param count
    if (ctx.Read(p1))
      m_PlayerModsDetailedSynced = p1.param1;
  }
Referenced by OnRPC().
OnRPCPluginDayzCreatureDebug()
void PluginBase::OnRPCPluginDayzCreatureDebug (PlayerBase player, int rpc_type, ParamsReadContext ctx) inline protected
Definition at line 156 of file PluginDeveloper.c.
  {
    PluginDayZCreatureAIDebug pluginDZCreatureDebug = PluginDayZCreatureAIDebug.Cast(GetPlugin(PluginDayZCreatureAIDebug));
    if (pluginDZCreatureDebug)
      pluginDZCreatureDebug.OnRpc(player, rpc_type, ctx);
  }
References GetPlugin(), and PluginDayZCreatureAIDebug().
Referenced by OnRPC().
OnRPCServerLogRecieved()
void PluginBase::OnRPCServerLogRecieved (ParamsReadContext ctx) inline protected
Definition at line 222 of file PluginDeveloper.c.
  {
    Param1<string> param = new Param1<string>("");
    if (ctx.Read(param) && param.param1 != "")
      Debug.ReceivedLogMessageFromServer(param.param1);
  }
References Debug::ReceivedLogMessageFromServer().
Referenced by OnRPC().
OnRPCSpawnEntity()
void PluginBase::OnRPCSpawnEntity (PlayerBase player, ParamsReadContext ctx) inline protected
Definition at line 256 of file PluginDeveloper.c.
  {
#ifdef DEVELOPER
    DevSpawnItemParams p = new DevSpawnItemParams(null, "", 0, 0, false, "", FindInventoryLocationType.ANY);
    if (ctx.Read(p))
    {
      EntityAI target = EntityAI.Cast(p.param1);
      PlayerBase playerTarget = PlayerBase.Cast(target);
      EntityAI ent = SpawnEntityInInventory(target, p.param2, p.param3, p.param4, p.param5, "", p.param7);
      if (playerTarget && p.param5)
      {
        if (playerTarget.m_PresetSpawned)
        {
          playerTarget.m_PresetSpawned = false;
          playerTarget.m_PresetItems.Clear();
        }
        if (ent)
          playerTarget.m_PresetItems.Insert(ent);
      }
    }
#endif
  }
References SpawnEntityInInventory().
Referenced by OnRPC().
OnRPCSpawnEntityOnCursorDir()
void PluginBase::OnRPCSpawnEntityOnCursorDir (PlayerBase player, ParamsReadContext ctx) inline protected
Definition at line 236 of file PluginDeveloper.c.
  {
    Param7<string, float, float, float, bool, string, bool> p = new Param7<string, float, float, float, bool, string, bool>("", 0, 0, 0, false, "", false);
    if (ctx.Read(p))
      SpawnEntityOnCursorDir(player, p.param1, p.param2, p.param3, p.param4, p.param5, p.param6, p.param7);
  }
References SpawnEntityOnCursorDir().
Referenced by OnRPC().
OnRPCSpawnEntityOnGround()
void PluginBase::OnRPCSpawnEntityOnGround (PlayerBase player, ParamsReadContext ctx) inline protected
Definition at line 243 of file PluginDeveloper.c.
  {
    Param6<string, float, float, vector, bool, bool> p = new Param6<string, float, float, vector, bool, bool>("", 0, 0, "0 0 0", false, false);
    if (ctx.Read(p))
      SpawnEntityOnGroundPos(player, p.param1, p.param2, p.param3, p.param4, p.param5, p.param6);
  }
References SpawnEntityOnGroundPos().
Referenced by OnRPC().
OnRPCSpawnEntityOnGroundPatternGrid()
void PluginBase::OnRPCSpawnEntityOnGroundPatternGrid (PlayerBase player, ParamsReadContext ctx) inline protected
Definition at line 250 of file PluginDeveloper.c.
  {
    auto p = new Param10<string, int, float, float, int, int, float, float, bool, bool>("", 0, 0, 0, 0, 0, 0, 0, false, false);
    if (ctx.Read(p))
      SpawnEntityOnGroundPatternGrid(player, p.param1, p.param2, p.param3, p.param4, p.param5, p.param6, p.param7, p.param8, p.param9, p.param10);
  }
References SpawnEntityOnGroundPatternGrid().
Referenced by OnRPC().
OnRPCStats()
void PluginBase::OnRPCStats (ParamsReadContext ctx) inline private
Definition at line 398 of file PluginDeveloperSync.c.
  {
    //clear values
    m_PlayerStatsSynced.Clear();
    Param1<int> p_count = new Param1<int>(0);
    Param3<string, float, float> p = new Param3<string, float, float>("", 0, 0);
    //get param count
    int param_count = 0;
    if (ctx.Read(p_count))
      param_count = p_count.param1;
    //read values and set
    for (int i = 0; i < param_count; i++)
    {
      ctx.Read(p);
      m_PlayerStatsSynced.Insert(new SyncedValue(p.param1, p.param2, false, p.param3));
    }
  }
Referenced by OnRPC().
OnRPCStatSet()
void PluginBase::OnRPCStatSet (ParamsReadContext ctx, PlayerBase player) inline private
Definition at line 442 of file PluginDeveloperSync.c.
  {
    Param2<string, float> p = new Param2<string, float>("", 0);
    if (ctx.Read(p))
    {
      for (int i = 0; i < player.m_PlayerStats.GetPCO().Get().Count(); i++)
      {
        string label = player.m_PlayerStats.GetPCO().Get().Get(i).GetLabel();
        if (label == p.param1)
          player.m_PlayerStats.GetPCO().Get().Get(i).SetByFloatEx(p.param2);
      }
    }
  }
References Count, and Get().
Referenced by OnRPC().
OnRPCStomach()
void PluginBase::OnRPCStomach (ParamsReadContext ctx) inline private
Definition at line 735 of file PluginDeveloperSync.c.
  {
    //clear values
    m_PlayerStomachSynced.Clear();
    Param1<int> p1 = new Param1<int>(0);
    int param_count = 0;
    if (ctx.Read(p1))
      param_count = p1.param1;
    if (param_count)
    {
      //invidividual stomach items
      for (int i = 0; i < param_count; i++)
      {
        Param4<int, int, int, float> p4 = new Param4<int, int, int, float>(0, 0, 0, 0);
        ctx.Read(p4);
        m_PlayerStomachSynced.Insert(p4);
      }
      //volume
      Param1<float> p1b = new Param1<float>(0);
      ctx.Read(p1b);
      m_PlayerStomachSynced.Insert(p1b);
    }
  }
Referenced by OnRPC().
OnRPCSyncSceneObject()
void PluginBase::OnRPCSyncSceneObject (ParamsReadContext ctx) inline protected
Definition at line 142 of file PluginDeveloper.c.
  {
    Param3<string, EntityAI, Param> par = new Param3<string, EntityAI, Param>("", NULL, new Param);
    if (ctx.Read(par))
    {
      PluginSceneManager module_scene_editor = PluginSceneManager.Cast(GetPlugin(PluginSceneManager));
      SceneData scene_data = module_scene_editor.GetLoadedScene();
      SceneObject scene_object = scene_data.GetSceneObjectByEntityAI(par.param2);
      GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallByName(scene_object, par.param1, par.param3);
    }
  }
References CALL_CATEGORY_SYSTEM, GetGame(), and GetPlugin().
Referenced by OnRPC().
OnRPCTemp()
void PluginBase::OnRPCTemp (ParamsReadContext ctx, PlayerBase player) inline private
Definition at line 665 of file PluginDeveloperSync.c.
  {
    if (GetGame().IsServer() && GetGame().IsMultiplayer())
      EnableUpdate(GetRPCUpdateState(ctx), ERPCs.DEV_TEMP_UPDATE, player);
    else if (!GetGame().IsMultiplayer() || GetGame().IsClient())
    {
      if (ctx.Read(CachedObjectsParams.PARAM1_STRING))
        m_EnvironmentDebugMessage = CachedObjectsParams.PARAM1_STRING.param1;
    }
  }
References EnableUpdate(), GetGame(), GetRPCUpdateState(), and CachedObjectsParams::PARAM1_STRING.
Referenced by OnRPC().
OnSetFreeCameraEvent()
void PluginBase::OnSetFreeCameraEvent (PlayerBase player, FreeDebugCamera camera) inline protected
Definition at line 280 of file PluginDeveloper.c.
  {
    DeveloperFreeCamera.OnSetFreeCameraEvent(player, camera);
  }
References DeveloperFreeCamera::OnSetFreeCameraEvent().
OnSpawnErrorReport()
void PluginBase::OnSpawnErrorReport (string name) inline protected
Definition at line 285 of file PluginDeveloper.c.
  {
    PrintString("PluginDeveloper.SpawnEntity() Warning- Cant spawn object: " + name);
    //DumpStack();
    PrintString("PluginDeveloper.SpawnEntity() Warning END");
  }
References name, and PrintString().
Referenced by SpawnEntityAsAttachment(), SpawnEntityInPlayerInventory(), SpawnEntityOnCursorDir(), and SpawnEntityOnGroundPos().
OnUIEditorClosed()
void PluginBase::OnUIEditorClosed () inline private
Definition at line 94 of file PluginSceneManager.c.
  {
    m_IsOpen = false;
    FreeCameraControlEnable();
    m_ModuleDeveloper.ToggleFreeCameraBackPos();
    EditorUpdate();
  }
OnUIEditorOpened()
void PluginBase::OnUIEditorOpened () inline private
Definition at line 80 of file PluginSceneManager.c.
  {
    m_IsOpen = true;
    DeveloperFreeCamera.EnableFreeCameraSceneEditor(PlayerBase.Cast(GetGame().GetPlayer()));
    GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(this.FreeCameraControlDisable);
    EditorUpdate();
  }
References CALL_CATEGORY_SYSTEM, DeveloperFreeCamera::EnableFreeCameraSceneEditor(), GetGame(), and GetPlayer().
OnUpdate() [1/8]
void PluginBase::OnUpdate (float delta_time) private
OnUpdate() [2/8]
override void PluginBase::OnUpdate (float delta_time) inline private
Definition at line 194 of file PluginDayZInfectedDebug.c.
  {
    super.OnUpdate(delta_time);
    CleanupDebugShapes(m_DebugShapes);
    if (m_IsActive)
    {
      if (!m_ControlledInfected)
        return;
      m_DebugShapes.Insert(Debug.DrawSphere(m_ControlledInfected.GetPosition() + "0 2 0", 0.25, FadeColors.RED));
    }
  }
References CleanupDebugShapes(), Debug::DrawSphere(), and m_IsActive.
OnUpdate() [3/8]
override void PluginBase::OnUpdate (float delta_time) inline private
Definition at line 46 of file PluginCharPlacement.c.
  {
    if (!m_Initialized) return;
    if (!FreeDebugCamera.GetInstance().IsActive()) return;
    if (!m_Character) return;
    m_camera_orientation = FreeDebugCamera.GetInstance().GetOrientation();
    m_camera_orientation[1] = 1;
    FreeDebugCamera.GetInstance().SetOrientation(m_camera_orientation); //remove to unlock vertical axis
    m_cam_pos = FreeDebugCamera.GetInstance().GetPosition();
    m_character_pos = m_Character.GetPosition();
    m_camera_dir = FreeDebugCamera.GetInstance().GetDirection();
    m_camera_dir.Normalize();
    m_Character.SetPosition(CalculatePos());//(FreeDebugCamera.GetInstance().GetPosition() + ( m_camera_dir * 2) );
    m_demoRot[0] = Math.Atan2(-m_camera_dir[0], -m_camera_dir[2]) * Math.RAD2DEG;
    m_Character.SetOrientation(m_demoRot);//(FreeDebugCamera.GetInstance().GetPosition() - m_demoPos);
  }
References Math::Atan2(), m_Initialized, vector::Normalize(), and Math::RAD2DEG.
OnUpdate() [4/8]
override void PluginBase::OnUpdate (float delta_time) inline private
Definition at line 23 of file PluginDoorRuler.c.
  {
    if (!m_Initialized) return;
    if (!FreeDebugCamera.GetInstance().IsActive()) return;
    if (!m_Ruler) return;
    vector cam_pos = FreeDebugCamera.GetInstance().GetPosition();
    vector ruler_pos = m_Ruler.GetPosition();
    vector camera_dir = FreeDebugCamera.GetInstance().GetDirection();
    camera_dir.Normalize();
    m_Ruler.SetPosition(FreeDebugCamera.GetInstance().GetPosition() + (camera_dir * 2));
    m_Ruler.SetAngles(FreeDebugCamera.GetInstance().GetAngles());
  }
References m_Initialized.
OnUpdate() [5/8]
override void PluginBase::OnUpdate (float delta_time) inline private
Definition at line 13 of file PluginRemotePlayerDebugServer.c.
  {
#ifdef SERVER
    if (m_ClientList.Count() != 0)
    {
      m_AccuTime += delta_time;
      if (m_AccuTime > INTERVAL)
      {
        m_AccuTime = 0;
        SendDebug();
      }
    }
#endif
  }
OnUpdate() [6/8]
override void PluginBase::OnUpdate (float delta_time) inline protected
Definition at line 27 of file PluginUniversalTemperatureSourceClient.c.
  {
#ifndef NO_GUI
    if (!m_Player)
      return;
    UpdateStatWidgets();
    DrawDebugs();
#endif
  }
References DrawDebugs(), m_Player, and UpdateStatWidgets().
OnUpdate() [7/8]
override void PluginBase::OnUpdate (float delta_time) inline protected
Definition at line 17 of file PluginUniversalTemperatureSourceServer.c.
  {
    if (m_ClientList.Count() > 0)
    {
      m_AccuTime += delta_time;
      if (m_AccuTime > INTERVAL)
      {
        m_AccuTime = 0;
        SendDebug();
      }
    }
  }
References SendDebug().
OnUpdate() [8/8]
override void PluginBase::OnUpdate (float delta_time) inline private
Definition at line 9 of file PluginSoundDebug.c.
  {
    ;
  }
PlayerHitBy()
void PluginBase::PlayerHitBy (TotalDamageResult damageResult, int damageType, PlayerBase player, EntityAI source, int component, string dmgZone, string ammo) inline protected
Definition at line 168 of file PluginAdminLog.c.
  {
    if (player && source)
    {
      string playerPrefix = GetPlayerPrefix(player, player.GetIdentity()) + "[HP: " + player.GetHealth().ToString() + "]";
      string playerPrefix2;
      m_HitMessage = GetHitMessage(damageResult, component, dmgZone, ammo);
      PlayerBase playerSource;
      if (source.IsPlayer()) // Fists
        playerSource = PlayerBase.Cast(source);
      else
        playerSource = PlayerBase.Cast(source.GetHierarchyParent());
      if (playerSource)
        playerPrefix2 = GetPlayerPrefix(playerSource, playerSource.GetIdentity());
      switch (damageType)
      {
      case DamageType.CLOSE_COMBAT: // Player melee, animals, infected
        if (m_HitFilter != 1 && (source.IsZombie() || source.IsAnimal())) // Infected & Animals
        {
          m_DisplayName = source.GetDisplayName();
          LogPrint(playerPrefix + " hit by " + m_DisplayName + m_HitMessage);
        }
        else if (source.IsPlayer())// Fists
          LogPrint(playerPrefix + " hit by " + playerPrefix2 + m_HitMessage);
        else if (playerSource && (source.IsMeleeWeapon() || source.IsWeapon())) // Melee weapons
        {
          m_ItemInHands = source.GetDisplayName();
          LogPrint(playerPrefix + " hit by " + playerPrefix2 + m_HitMessage + " with " + m_ItemInHands);
        }
        else
        {
          m_DisplayName = source.GetType();
          LogPrint(playerPrefix + " hit by " + m_DisplayName + m_HitMessage);
        }
        break;
      case DamageType.FIRE_ARM: // Player ranged
        if (source.IsWeapon() && playerSource)
        {
          m_ItemInHands = source.GetDisplayName();
          m_Distance = vector.Distance(player.GetPosition(), playerSource.GetPosition());
          LogPrint(playerPrefix + " hit by " + playerPrefix2 + m_HitMessage + " with " + m_ItemInHands + " from " + m_Distance + " meters ");
        }
        else
        {
          m_DisplayName = source.GetType();
          LogPrint(playerPrefix + " hit by " + m_DisplayName + m_HitMessage);
        }
        break;
      case DamageType.EXPLOSION: // Explosion
        LogPrint(playerPrefix + " hit by explosion (" + ammo + ")");
        break;
      case DamageType.STUN: // unused atm
        LogPrint(playerPrefix + " stunned by " + ammo);
        break;
      case DamageType.CUSTOM: // Others (Vehicle hit, fall, fireplace, barbed wire ...)
        float globalHealthDamage = damageResult.GetDamage("", "Health");
        if (ammo == DayZPlayerImplementFallDamage.FALL_DAMAGE_AMMO_HEALTH || ammo == DayZPlayerImplementFallDamage.FALL_DAMAGE_AMMO_SHOCK || ammo == DayZPlayerImplementFallDamage.FALL_DAMAGE_AMMO_HEALTH_OTHER_ATTACHMENTS)
        {
          if (globalHealthDamage > 0.0)
            LogPrint(playerPrefix + " hit by " + ammo);
        }
        else if (source.GetType() == "AreaDamageManager")
        {
          EntityAI parent = EntityAI.Cast(source);
          if (parent)
            LogPrint(playerPrefix + " hit by " + parent.GetType() + " with " + ammo);
        }
        else
        {
          m_DisplayName = source.GetType();
          LogPrint(playerPrefix + " hit by " + m_DisplayName + " with " + ammo);
        }
        break;
      default:
        LogPrint("DEBUG: PlayerHitBy() unknown damageType: " + ammo);
        break;
      }
    }
    else
      LogPrint("DEBUG: player/source does not exist");
  }
References component, DayZPlayerImplementFallDamage(), vector::Distance(), GetHitMessage(), GetPlayerPrefix(), and LogPrint().
PlayerKilled()
void PluginBase::PlayerKilled (PlayerBase player, Object source) inline protected
Definition at line 110 of file PluginAdminLog.c.
  {
    if (!player || !source)
    {
      LogPrint("DEBUG: PlayerKilled() player/source does not exist");
      return;
    }
    PlayerBase playerSource = PlayerBase.Cast(EntityAI.Cast(source).GetHierarchyParent());
    if (!playerSource)
      playerSource = PlayerBase.Cast(source);
    string playerPrefix, playerPrefix2;
    if (playerSource)
      playerPrefix2 = GetPlayerPrefix(playerSource, playerSource.GetIdentity());
    playerPrefix = GetPlayerPrefix(player, player.GetIdentity());
    if (player == source) // deaths not caused by another object (starvation, dehydration)
    {
      m_StatWater = player.GetStatWater();
      m_StatEnergy = player.GetStatEnergy();
      m_BleedMgr = player.GetBleedingManagerServer();
      if (m_StatWater && m_StatEnergy && m_BleedMgr)
        LogPrint(playerPrefix + " died. Stats> Water: " + m_StatWater.Get().ToString() + " Energy: " + m_StatEnergy.Get().ToString() + " Bleed sources: " + m_BleedMgr.GetBleedingSourcesCount().ToString());
      else if (m_StatWater && m_StatEnergy && !m_BleedMgr)
        LogPrint(playerPrefix + " died. Stats> Water: " + m_StatWater.Get().ToString() + " Energy: " + m_StatEnergy.Get().ToString());
      else
        LogPrint(playerPrefix + " died. Stats> could not fetch");
    }
    else if (source.IsWeapon() || source.IsMeleeWeapon()) // player
    {
      if (source.IsMeleeWeapon())
        LogPrint(playerPrefix + " killed by " + playerPrefix2 + " with " + source.GetDisplayName());
      else
      {
        m_Distance = vector.Distance(player.GetPosition(), playerSource.GetPosition());
        LogPrint(playerPrefix + " killed by " + playerPrefix2 + " with " + source.GetDisplayName() + " from " + m_Distance + " meters ");
      }
    }
    else
    {
      if (playerSource)
      {
        //fists
        LogPrint(playerPrefix + " killed by " + playerPrefix2 + " with (MeleeFist)");
      }
      else
      {
        //rest, Animals, Zombies
        LogPrint(playerPrefix + " killed by " + source.GetType());
      }
    }
  }
References vector::Distance(), GetPlayerPrefix(), and LogPrint().
PlayerList()
void PluginBase::PlayerList () inline protected
Definition at line 348 of file PluginAdminLog.c.
  {
    GetGame().GetPlayers(m_PlayerArray);
    if (m_PlayerArray.Count() != 0)
    {
      LogPrint("##### PlayerList log: " + m_PlayerArray.Count().ToString() + " players");
      foreach (Man player: m_PlayerArray)
      {
        m_Player = PlayerBase.Cast(player);
        m_PlayerPrefix = GetPlayerPrefix(m_Player, m_Player.GetIdentity());
        LogPrint(m_PlayerPrefix);
      }
      LogPrint("#####");
    }
  }
References GetGame(), GetPlayerPrefix(), LogPrint(), m_Player, and m_PlayerArray.
PlayPause()
void PluginBase::PlayPause () inline protected
Definition at line 52 of file PluginCameraTools.c.
  {
    if (GetGame().GetUIManager().GetMenu())
      GetGame().GetUIManager().GetMenu().OnKeyPress(null, 0, 0, KeyCode.KC_P);
  }
References GetGame().
PluginAdminLog()
void PluginBase::PluginAdminLog () inline protected
Definition at line 42 of file PluginAdminLog.c.
  {
    m_HitFilter = GetGame().ServerConfigGetInt("adminLogPlayerHitsOnly"); // 1 - log player hits only / 0 - log all hits ( animals/infected )
    m_PlacementFilter = GetGame().ServerConfigGetInt("adminLogPlacement"); // 1 - log placement ( traps, tents )
    m_ActionsFilter = GetGame().ServerConfigGetInt("adminLogBuildActions"); // 1 - log basebuilding actions ( build, dismantle, destroy )
    m_PlayerListFilter = GetGame().ServerConfigGetInt("adminLogPlayerList"); // 1 - log periodic player list with position every 5 minutes
    m_PlayerArray = new array<Man>;
    if (m_PlayerListFilter == 1)
    {
      m_Timer = new Timer();
      m_Timer.Run(TIMER_PLAYERLIST, this, "PlayerList", NULL, true);
    }
  }
References GetGame(), m_ActionsFilter, and m_Timer.
PluginConfigViewer()
void PluginBase::PluginConfigViewer () inline private
Definition at line 3 of file PluginConfigViewer.c.
  {
  }
PluginDayZInfectedDebug()
void PluginBase::PluginDayZInfectedDebug () inline private
Definition at line 103 of file PluginDayZInfectedDebug.c.
  {
#ifndef NO_GUI
    CreateModuleWidgets();
#endif
  }
References CreateModuleWidgets().
PluginDeveloper()
void PluginBase::PluginDeveloper () inline protected
Definition at line 43 of file PluginDeveloper.c.
  {
  }
PluginDeveloperSync()
void PluginBase::PluginDeveloperSync () inline private
Definition at line 45 of file PluginDeveloperSync.c.
  {
    m_RegisteredPlayers = new map<PlayerBase, ref RegisterPlayerData>;
    m_PlayerStatsSynced = new array<ref SyncedValue>;
    m_PlayerLevelsSynced = new array<ref SyncedValueLevel>;
    m_PlayerModsSynced = new array<ref SyncedValueModifier>;
    m_PlayerAgentsSynced = new array<ref SyncedValueAgent>;
    m_PlayerStomachSynced = new array<ref Param>;
    m_StatsUpdateStatus = false;
    m_LevelsUpdateStatus = false;
    m_ModsUpdateStatus = false;
    m_AgentsUpdateStatus = false;
    m_StomachUpdateStatus = false;
  }
PluginDrawCheckerboard()
void PluginBase::PluginDrawCheckerboard () inline private
Definition at line 9 of file PluginDrawCheckerboard.c.
  {
    CreateWidgetOverlay();
  }
References CreateWidgetOverlay().
PluginFileHandler()
void PluginBase::PluginFileHandler () inline private
Definition at line 24 of file PluginFileHandler.c.
  {
    m_FileContent = new TStringArray;
    m_LineLimit = -1;
    LoadFile();
  }
PluginHorticulture()
void PluginBase::PluginHorticulture () inline private
Definition at line 5 of file PluginHorticulture.c.
  {
    m_PlantMaterials = new map<string, ref PlantMaterialHealth>;
    LoadFromCfg();
  }
References LoadFromCfg().
PluginKeyBinding()
void PluginBase::PluginKeyBinding () inline private
Definition at line 19 of file PluginKeyBinding.c.
  {
    if (instance == null)
      instance = this;
  }
PluginMessageManager()
void PluginBase::PluginMessageManager () inline private
Definition at line 9 of file PluginMessageManager.c.
  {
    for (int i = 0; i < NUM_OF_CHANNELS; i++)
      channelList[i] = new array<ref MessageReceiverBase>;
  }
References NUM_OF_CHANNELS.
PluginObjectsInteractionManager()
void PluginBase::PluginObjectsInteractionManager () inline private
Definition at line 9 of file PluginObjectsInteractionManager.c.
  {
    m_LockedObjects = new array<Object>;
    m_LockedObjectsDecay = new array<float>;
    //TIMERDEPRECATED - timer for decaying objects
    m_DecayTimer = new Timer();
    m_DecayTimer.Run(TICK_RATE, this, "Decay", NULL, true);
  }
References m_DecayTimer.
PluginPlayerStatus()
void PluginBase::PluginPlayerStatus () inline private
Definition at line 8 of file PluginPlayerStatus.c.
  {
    m_NotifiersLabel = new multiMap<int, string>; // [key] label
    m_NotifiersIndexColor = new multiMap<int, int>; // [key] index, color
    m_NotifiersIcons = new multiMap<int, string>; // [key] iconName
    m_NotifiersIcons.Insert(NTFKEY_HUNGRY, "iconHunger");
    m_NotifiersIcons.Insert(NTFKEY_THIRSTY, "iconThirsty");
    m_NotifiersIcons.Insert(NTFKEY_SICK, "iconHealth");
    m_NotifiersIcons.Insert(NTFKEY_BACTERIA, "iconBacteria");
    m_NotifiersIcons.Insert(NTFKEY_BLEEDISH, "iconBlood");
    m_NotifiersIcons.Insert(NTFKEY_FEVERISH, "iconTemperature");
    m_NotifiersIcons.Insert(NTFKEY_FRACTURE, "iconFracture");
  }
References NTFKEY_BACTERIA, NTFKEY_BLEEDISH, NTFKEY_FEVERISH, NTFKEY_FRACTURE, NTFKEY_HUNGRY, NTFKEY_SICK, and NTFKEY_THIRSTY.
PluginSceneManager()
void PluginBase::PluginSceneManager () inline private
Definition at line 21 of file PluginSceneManager.c.
  {
    if (instance == NULL)
      instance = this;
  }
PluginTransmissionAgents()
void PluginBase::PluginTransmissionAgents () inline private
Definition at line 14 of file PluginTransmissionAgents.c.
  {
    //add new agents here
    RegisterAgent(new InfluenzaAgent);
    RegisterAgent(new CholeraAgent);
    RegisterAgent(new SalmonellaAgent);
    RegisterAgent(new BrainAgent);
    RegisterAgent(new FoodPoisonAgent);
    RegisterAgent(new ChemicalAgent);
    RegisterAgent(new WoundAgent);
    RegisterAgent(new NerveAgent);
  }
References RegisterAgent().
PluginUniversalTemperatureSourceClient()
void PluginBase::PluginUniversalTemperatureSourceClient () inline protected
Definition at line 15 of file PluginUniversalTemperatureSourceClient.c.
  {
    m_UTemperatureSourceDebugs = new array<ref UTemperatureSourceDebug>();
  }
PluginUniversalTemperatureSourceServer()
void PluginBase::PluginUniversalTemperatureSourceServer () inline protected
Definition at line 11 of file PluginUniversalTemperatureSourceServer.c.
  {
    m_ClientList = new set<PlayerBase>();
    m_UTemperatureSourceDebugs = new array<ref UTemperatureSourceDebug>();
  }
PluginVariables()
void PluginBase::PluginVariables () inline private
Definition at line 3 of file PluginVariables.c.
  {
    m_Id = 0;
    m_Variables = new map<int, string>;
    // ("variable name")
    RegisterVariable("varNote");
    RegisterVariable("varColor");
  }
References m_Id, and RegisterVariable().
PossesInfected()
void PluginBase::PossesInfected () inline protected
Definition at line 367 of file PluginDayZInfectedDebug.c.
  {
    ResetValues();
    FreeDebugCamera.GetInstance().SetActive(true);
    m_ControlledInfected = DayZInfected.Cast(FreeDebugCamera.GetInstance().GetCrosshairObject());
    FreeDebugCamera.GetInstance().SetActive(false);
  }
References ResetValues().
PrintedDebug()
void PluginBase::PrintedDebug () inline protected
Definition at line 205 of file PluginUniversalTemperatureSourceClient.c.
  {
    foreach (UTemperatureSourceDebug utsd : m_UTemperatureSourceDebugs)
    {
      PrintString("-------------------------------------");
      utsd.Debug();
      PrintString("-------------------------------------");
    }
  }
References m_UTemperatureSourceDebugs, and PrintString().
PrintLogClient()
void PluginBase::PrintLogClient (string msg_log) inline protected
Definition at line 114 of file PluginDeveloper.c.
  {
    if (g_Game.GetUIManager().IsMenuOpen(MENU_SCRIPTCONSOLE))
    {
      Param1<string> msg_p = new Param1<string>(msg_log);
      CallMethod(CALL_ID_SCR_CNSL_ADD_PRINT, msg_p);
    }
  }
References CALL_ID_SCR_CNSL_ADD_PRINT, CallMethod(), g_Game, and MENU_SCRIPTCONSOLE.
ProcessUniversalTemperatureSources()
void PluginBase::ProcessUniversalTemperatureSources () inline protected
next temp source is too far (not cleaned on server, like in Environment, client need to know about all sources in MAXRANGE)
Definition at line 82 of file PluginUniversalTemperatureSourceClient.c.
  {
    if (m_UTemperatureSourceDebugs.Count() == 0)
    {
      m_UTSAverageTemperature = 0;
      return;
    }
    array<float> utsTemperatures = new array<float>();
    // get temperature from the source (based on distance), save it for min/max filtering
    foreach (UniversalTemperatureSourceDebug utsd : m_UTemperatureSourceDebugs)
    {
      if (vector.DistanceSq(m_Player.GetPosition(), utsd.GetValue(0).ToVector()) > Math.SqrFloat(utsd.GetValue(2).ToFloat()))
        continue;
      utsTemperatures.Insert(CalcTemperatureFromTemperatureSource(utsd));
    }
    float min = MiscGameplayFunctions.GetMinValue(utsTemperatures);
    float max = MiscGameplayFunctions.GetMaxValue(utsTemperatures);
    if (max > 0 && min < 0)
      m_UTSAverageTemperature = (max + min) * 0.5;
    else
      m_UTSAverageTemperature = max;
  }
References CalcTemperatureFromTemperatureSource(), vector::DistanceSq(), m_Player, m_UTemperatureSourceDebugs, and Math::SqrFloat().
Referenced by DrawDebugs().
QuickSort()
void PluginBase::QuickSort (TStringArray arr, int left, int right) inline private
Definition at line 827 of file PluginDeveloper.c.
  {
    int j;
    if (left < right)
    {
      j = QuickSortPartition(arr, left, right);
      QuickSort(arr, left, j - 1);
      QuickSort(arr, j + 1, right);
    }
  }
References QuickSort(), and QuickSortPartition().
Referenced by QuickSort(), and SortStringArray().
QuickSortPartition()
int PluginBase::QuickSortPartition (TStringArray arr, int left, int right) inline private
Definition at line 789 of file PluginDeveloper.c.
  {
    string pivot = arr.Get(left);
    int i = left;
    int j = right + 1;
    string temp;
    while (true)
    {
      while (true)
      {
        i++;
        if (i > right || arr.Get(i) > pivot)
          break;
      }
      while (true)
      {
        j--;
        if (arr.Get(j) <= pivot)
          break;
      }
      if (i >= j)
        break;
      temp = arr.Get(i);
      arr.Set(i, arr.Get(j));
      arr.Set(j, temp);
    }
    temp = arr.Get(left);
    arr.Set(left, arr.Get(j));
    arr.Set(j, temp);
    return j;
  }
Referenced by QuickSort().
RegisterAgent()
void PluginBase::RegisterAgent (AgentBase agent) inline private
Definition at line 27 of file PluginTransmissionAgents.c.
  {
    m_AgentList.Insert(agent.GetAgentType(), agent);
  }
Referenced by PluginTransmissionAgents().
RegisterKeyBind()
void PluginBase::RegisterKeyBind (int ui_id, int key_code1, int key_code2, string plugin_name, string fnc_name, string info_shortcut, string info_description) inline protected
Definition at line 284 of file PluginKeyBinding.c.
  {
    m_KeyBindings.Insert(new KeyBinding(ui_id, key_code1, key_code2, plugin_name, fnc_name, info_shortcut, info_description));
  }
RegisterMouseBind()
void PluginBase::RegisterMouseBind (int ui_id, int mouse_button, int mouse_event, string plugin_name, string fnc_name, string info_shortcut, string info_description) inline protected
Definition at line 292 of file PluginKeyBinding.c.
  {
    m_MouseBindings.Insert(new MouseBinding(ui_id, mouse_button, mouse_event, plugin_name, fnc_name, info_shortcut, info_description));
  }
RegisterPlayer()
void PluginBase::RegisterPlayer (PlayerBase player) inline private
Definition at line 204 of file PluginDeveloperSync.c.
  {
    if (!IsPlayerRegistered(player))
      m_RegisteredPlayers.Insert(player, new RegisterPlayerData);
  }
References IsPlayerRegistered(), and RegisterPlayerData().
Referenced by EnableUpdate().
RegisterVariable()
void PluginBase::RegisterVariable (string name) inline private
Definition at line 17 of file PluginVariables.c.
  {
    m_Id++;
    m_Variables.Set(m_Id, name); //REWORK.V maybe have 2 maps, one with key
  }
References m_Id, and name.
Referenced by PluginVariables().
Release()
void PluginBase::Release (Object target) inline private
Definition at line 40 of file PluginObjectsInteractionManager.c.
  {
    if (target && m_LockedObjects.Count() > 0)
    {
      for (int i = 0; i < m_LockedObjects.Count(); i++)
      {
        if (m_LockedObjects.Get(i) == target)
        {
          m_LockedObjects.Remove(i);
          m_LockedObjectsDecay.Remove(i);
          break;
        }
      }
    }
  }
ReleaseFocus() [1/2]
void PluginBase::ReleaseFocus () inline private
Definition at line 150 of file PluginDayZInfectedDebug.c.
  {
    if (m_HasFocus)
    {
      GetGame().GetInput().ChangeGameFocus(-1);
      GetGame().GetUIManager().ShowUICursor(false);
      m_HasFocus = false;
    }
  }
References GetGame(), and m_HasFocus.
Referenced by ToggleDebugWindowEventOld(), ToggleDebugWindowEventP(), ToggleDebugWindowSetMode(), ToggleDebugWindowSetMode(), and ~PluginDayzPlayerDebug().
ReleaseFocus() [2/2]
void PluginBase::ReleaseFocus () inline private
Definition at line 799 of file PluginDeveloperSync.c.
  {
    GetGame().GetInput().ChangeGameFocus(-1);
    GetGame().GetUIManager().ShowUICursor(false);
  }
References GetGame().
RemoveAgent()
static void PluginBase::RemoveAgent (EntityAI target, int agent_id) inline static private
Definition at line 71 of file PluginTransmissionAgents.c.
  {
    target.RemoveAgent(agent_id);
  }
RemoveAllAgents()
void PluginBase::RemoveAllAgents (EntityAI target) inline private
Definition at line 66 of file PluginTransmissionAgents.c.
  {
    target.RemoveAllAgents();
  }
Repair()
bool PluginBase::Repair (PlayerBase player, ItemBase repair_kit, Object item, float specialty_weight, string damage_zone = "", bool use_kit_qty = true) inline private
Definition at line 3 of file PluginRepairing.c.
  {
    switch (item.GetHealthLevel(damage_zone))
    {
    case GameConstants.STATE_PRISTINE:
      break;
    case GameConstants.STATE_RUINED:
#ifdef DEVELOPER
      Debug.Log("repairing from GameConstants.STATE_RUINED");
#endif
      CalculateHealth(player, repair_kit, item, specialty_weight, damage_zone, use_kit_qty);
      break;
    case GameConstants.STATE_WORN:
      if (CanRepairToPristine(player) || CanBeRepairedToPristine(item))
        CalculateHealth(player, repair_kit, item, specialty_weight,/* GameConstants.DAMAGE_PRISTINE_VALUE,*/ damage_zone, use_kit_qty);
      break;
    default:
      CalculateHealth(player, repair_kit, item, specialty_weight, damage_zone, use_kit_qty);
      break;
    }
    return true;
  }
References Debug::Log(), GameConstants::STATE_PRISTINE, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
RequestDetailedInfo()
void PluginBase::RequestDetailedInfo (int id, notnull PlayerBase player) inline private
Definition at line 604 of file PluginDeveloperSync.c.
  {
    int modifier_id = Math.AbsInt(id);
    m_RegisteredPlayers.Get(player).m_DetailedModifierIndex = modifier_id;
    if (IsSetSystemInBitmask(player, PDS_SYSTEMS.MODS_DETAILED))
      SetSystemInBitmask(player, PDS_SYSTEMS.MODS_DETAILED, false);
    else
      SetSystemInBitmask(player, PDS_SYSTEMS.MODS_DETAILED, true);
  }
References Math::AbsInt(), IsSetSystemInBitmask(), and SetSystemInBitmask().
Referenced by OnRPC().
RequestUniversalTemperatureSources()
void PluginBase::RequestUniversalTemperatureSources (PlayerBase player, int enable) inline protected
Definition at line 186 of file PluginUniversalTemperatureSourceClient.c.
  {
    //Debug.Log("RequestUniversalTemperatureSources called", "PluginUniversalTemperatureSourceClient");
    if (!enable)
    {
      m_UTemperatureSourceDebugs.Clear();
      m_Player = null;
      EnableWidgets(false);
      return;
    }
    ScriptRPC rpc = new ScriptRPC();
    rpc.Write(enable);
    rpc.Send(player, ERPCs.DEV_REQUEST_UTS_DEBUG, true, player.GetIdentity());
    m_Player = player;
  }
References EnableWidgets(), and m_Player.
ResetGUI()
void PluginBase::ResetGUI () inline private
Definition at line 844 of file PluginDeveloper.c.
  {
    if (GetGame() && GetGame().GetMission())
      GetGame().GetMission().ResetGUI();
  }
References GetGame().
ResetValues()
void PluginBase::ResetValues () inline private
Definition at line 347 of file PluginDayZInfectedDebug.c.
  {
    m_CH_DoTurn = false;
    m_CH_DoVault = false;
    m_CH_DoKnucleOut = false;
    m_CH_GoToCrawl = false;
    m_CH_DoHit = false;
    m_CH_StartDeath = false;
    m_CH_DoAttack = false;
    m_MovementSpeedEB.SetText("0");
    m_MainWnd.Update();
  }
References m_MainWnd.
Referenced by OnClick(), and PossesInfected().
RestoreSceneObjectsLinks()
void PluginBase::RestoreSceneObjectsLinks () inline private
Definition at line 300 of file PluginSceneManager.c.
  {
    array<ref SceneObject> scene_objects = GetSceneObjects();
    for (int i = 0; i < scene_objects.Count(); i++)
    {
      SceneObject scene_object = scene_objects.Get(i);
      array<int> linked_scene_objects_indices = scene_object.m_LinkedSceneObjectsIndices;
      if (linked_scene_objects_indices)
      {
        for (int j = 0; j < linked_scene_objects_indices.Count(); j++)
        {
          int index = linked_scene_objects_indices.Get(j);
          if (index >= 0 && index < scene_objects.Count())
          {
            scene_object.LinkSceneObject(scene_objects.Get(index), false);
            //PrintString("Load link: "+ ToString(scene_object.GetObject()) +" <-> "+ ToString(scene_objects.Get(index).GetObject()) );
          }
        }
      }
      scene_object.m_LinkedSceneObjectsIndices = NULL;
    }
  }
RulerAddPoint()
void PluginBase::RulerAddPoint () inline private
Definition at line 877 of file PluginSceneManager.c.
  {
    vector point_pos = GetMousePositionInScene();
    m_RulerPoints.Insert(point_pos);
    EditorUpdateRuler();
  }
RulerClearVisuals()
void PluginBase::RulerClearVisuals () inline private
Definition at line 889 of file PluginSceneManager.c.
  {
    for (int i = 0; i < m_RulerLines.Count(); ++i)
      m_RulerLines.Get(i).Destroy();
    m_RulerLines.Clear();
    for (int j = 0; j < m_RulerSpheres.Count(); ++j)
      m_RulerSpheres.Get(j).Destroy();
    m_RulerSpheres.Clear();
  }
RulerDelete()
void PluginBase::RulerDelete () inline private
Definition at line 903 of file PluginSceneManager.c.
  {
    m_RulerPoints.Clear();
    EditorUpdateRuler();
  }
RulerToggle()
void PluginBase::RulerToggle () inline private
Definition at line 856 of file PluginSceneManager.c.
  {
    if (IsRulerActivated())
      m_RulerActivated = false;
    else
      m_RulerActivated = true;
    SceneEditorMenuCmdRefresh();
  }
Save()
void PluginBase::Save () inline protected
Definition at line 46 of file PluginCameraTools.c.
  {
    if (GetGame().GetUIManager().GetMenu())
      GetGame().GetUIManager().GetMenu().OnKeyPress(null, 0, 0, KeyCode.KC_S);
  }
References GetGame().
SaveFile()
bool PluginBase::SaveFile () inline private
Definition at line 80 of file PluginFileHandler.c.
  {
    if (m_ReadOnly)
      return false;
    if (GetSubFolderName() && !FileExist(GetSubFolderName()))
      MakeDirectory(GetSubFolderName());
    //Log("SaveFile -> Opening File: "+GetFileName());
    FileHandle file_index = OpenFile(GetFileName(), FileMode.WRITE);
    if (file_index == 0)
      return false;
    for (int i = 0; i < m_FileContent.Count(); ++i)
    {
      //Log("SaveFile -> Writing: "+m_FileContent.Get(i));
      FPrintln(file_index, m_FileContent.Get(i));
    }
    CloseFile(file_index);
    return true;
  }
References CloseFile(), FileExist(), FPrintln(), PluginFileHandler::GetFileName(), GetSubFolderName(), MakeDirectory(), and OpenFile().
SceneCanDelete()
bool PluginBase::SceneCanDelete (string scene_name) inline private
Definition at line 742 of file PluginSceneManager.c.
  {
    if (scene_name == m_SceneData.GetNameScene())
      return false;
    return true;
  }
SceneDelete()
bool PluginBase::SceneDelete (string scene_name) inline private
Definition at line 753 of file PluginSceneManager.c.
  {
    if (scene_name == m_SceneData.GetNameScene())
      return false;
    m_ModuleConfigScene.SceneDelete(scene_name);
    EditorUpdate();
    return true;
  }
SceneDuplicate()
void PluginBase::SceneDuplicate (string scene_name) inline private
Definition at line 768 of file PluginSceneManager.c.
  {
    m_ModuleConfigScene.SceneDuplicate(scene_name);
    EditorUpdate();
  }
SceneEditorMenuCmdPopup()
void PluginBase::SceneEditorMenuCmdPopup (string message) inline private
Definition at line 1121 of file PluginSceneManager.c.
  {
    CallMethod(CALL_ID_SCENE_EDITOR_COMMAND, new Param2<int, Param1<string>>(SCENE_EDITOR_CMD_POPUP, new Param1<string>(message)));
  }
References CALL_ID_SCENE_EDITOR_COMMAND, and CallMethod().
SceneEditorMenuCmdRefresh()
void PluginBase::SceneEditorMenuCmdRefresh () inline private
Definition at line 1113 of file PluginSceneManager.c.
  {
    CallMethod(CALL_ID_SCENE_EDITOR_COMMAND, new Param2<int, Param>(SCENE_EDITOR_CMD_REFRESH, NULL));
  }
References CALL_ID_SCENE_EDITOR_COMMAND, and CallMethod().
SceneEditorMenuCmdSave()
void PluginBase::SceneEditorMenuCmdSave () inline private
Definition at line 1129 of file PluginSceneManager.c.
  {
    CallMethod(CALL_ID_SCENE_EDITOR_COMMAND, new Param2<int, Param>(SCENE_EDITOR_CMD_SAVE, NULL));
  }
References CALL_ID_SCENE_EDITOR_COMMAND, and CallMethod().
SceneGetName()
string PluginBase::SceneGetName () inline private
Definition at line 791 of file PluginSceneManager.c.
  {
    if (m_SceneData)
      return m_SceneData.GetNameScene();
    return STRING_EMPTY;
  }
References STRING_EMPTY.
SceneLoad()
void PluginBase::SceneLoad (string scene_name) inline private
Definition at line 708 of file PluginSceneManager.c.
  {
    SceneUnload();
    PluginMissionConfig.GetInstance().SetSceneEditorName(scene_name);
    m_SceneData = m_ModuleConfigScene.SceneDataLoad(scene_name);
    if (!(GetGame().IsMultiplayer() && GetGame().IsServer()))
      EditorUpdate();
  }
References GetGame().
SceneRename()
void PluginBase::SceneRename (string scene_name, string new_name) inline private
Definition at line 778 of file PluginSceneManager.c.
  {
    m_ModuleConfigScene.SceneRename(scene_name, new_name);
    if (scene_name == m_SceneData.GetNameScene())
      m_SceneData.SetNameScene(new_name);
    EditorUpdate();
  }
SceneSave()
void PluginBase::SceneSave () inline private
Definition at line 731 of file PluginSceneManager.c.
  {
    m_ModuleConfigScene.ClearParams();
    m_ModuleConfigScene.SceneDataSave(m_SceneData);
    SceneEditorMenuCmdSave();
    EditorUpdate();
  }
SceneUnload()
void PluginBase::SceneUnload () inline private
Definition at line 722 of file PluginSceneManager.c.
  {
    m_SceneData = NULL;
    DeselectObject();
  }
ScriptHistoryBack()
void PluginBase::ScriptHistoryBack () inline private
Definition at line 761 of file PluginDeveloper.c.
  {
    // Console key press
    if (g_Game.GetUIManager().IsMenuOpen(MENU_SCRIPTCONSOLE))
      CallMethod(CALL_ID_SCR_CNSL_HISTORY_BACK, NULL);
  }
References CALL_ID_SCR_CNSL_HISTORY_BACK, CallMethod(), g_Game, and MENU_SCRIPTCONSOLE.
ScriptHistoryNext()
void PluginBase::ScriptHistoryNext () inline private
Definition at line 754 of file PluginDeveloper.c.
  {
    // Console key press
    if (g_Game.GetUIManager().IsMenuOpen(MENU_SCRIPTCONSOLE))
      CallMethod(CALL_ID_SCR_CNSL_HISTORY_NEXT, NULL);
  }
References CALL_ID_SCR_CNSL_HISTORY_NEXT, CallMethod(), g_Game, and MENU_SCRIPTCONSOLE.
SelectAndFocusPlayerObject()
void PluginBase::SelectAndFocusPlayerObject () inline private
Definition at line 825 of file PluginSceneManager.c.
  {
    array<ref SceneObject> scene_objects = GetSceneObjects();
    for (int i = 0; i < scene_objects.Count(); i++)
    {
      if (scene_objects.Get(i).GetObject() == GetGame().GetPlayer())
      {
        SelectObject(scene_objects.Get(i));
        SelectedObjectFocus();
        break;
      }
    }
  }
References GetGame(), and GetPlayer().
SelectClassName()
void PluginBase::SelectClassName (string class_name) inline private
Definition at line 373 of file PluginSceneManager.c.
  {
    m_ClassBrowserSelected = class_name;
  }
References class_name.
SelectedObjectAddAttachment()
void PluginBase::SelectedObjectAddAttachment (string att_name) inline private
Definition at line 607 of file PluginSceneManager.c.
  {
    if (GetSelectedSceneObject())
      GetSelectedSceneObject().AddAttachment(att_name);
    EditorUpdate();
  }
SelectedObjectDuplicate()
void PluginBase::SelectedObjectDuplicate () inline private
Definition at line 465 of file PluginSceneManager.c.
  {
    SceneObject selected_obj = GetSelectedSceneObject();
    if (selected_obj)
    {
      if (selected_obj.GetObject() == PLAYER)
        return;
      vector size = GetSelectedSceneObject().GetSize();
      vector new_pos = selected_obj.GetPosition() + Vector(1, 0, 1) + size;
      SceneObject obj = m_SceneData.CreateSceneObject(selected_obj.GetTypeName(), new_pos);
      obj.SetRotation(selected_obj.GetRotation());
      array<EntityAI> attachments = selected_obj.GetAttachments();
      for (int i = 0; i < attachments.Count(); i++)
        obj.AddAttachment(attachments.Get(i).GetType());
      SelectObject(obj);
    }
  }
References SceneObject::AddAttachment(), PLAYER, SceneObject::SetRotation(), and Vector().
SelectedObjectFocus()
void PluginBase::SelectedObjectFocus () inline private
Definition at line 572 of file PluginSceneManager.c.
  {
    SceneObject selected_obj = GetSelectedSceneObject();
    if (selected_obj)
    {
      vector cam_pos = FreeDebugCamera.GetInstance().GetPosition();
      vector obj_pos = selected_obj.GetPosition();
      vector view_target = obj_pos;
      vector obj_size = selected_obj.GetSize();
      cam_pos = obj_pos;
      cam_pos[0] = cam_pos[0] + (obj_size[0] * 2);
      cam_pos[1] = cam_pos[1] + obj_size[1] + 0.5;
      cam_pos[2] = cam_pos[2] + (obj_size[2] * 2);
      view_target[1] = view_target[1] + (obj_size[1] * 0.5);
      vector cam_dir = view_target - cam_pos;
      cam_dir.Normalize();
      FreeDebugCamera.GetInstance().SetPosition(cam_pos);
      FreeDebugCamera.GetInstance().SetDirection(cam_dir);
      //vector debug_pos = cam_pos + (cam_dir * 50);
      //Debug.DrawLine(cam_pos, debug_pos);
      //Debug.DrawSphere(cam_pos);
    }
  }
SelectedObjectRemoveAttachment()
void PluginBase::SelectedObjectRemoveAttachment (EntityAI e) inline private
Definition at line 618 of file PluginSceneManager.c.
  {
    if (GetSelectedSceneObject())
      GetSelectedSceneObject().RemoveAttachment(e);
    EditorUpdate();
  }
SelectedObjectSetDamage()
void PluginBase::SelectedObjectSetDamage (float value) inline private
Definition at line 556 of file PluginSceneManager.c.
  {
    SceneObject selected_obj = GetSelectedSceneObject();
    EntityAI selected_obj_EAI = selected_obj.GetObject();
    if (selected_obj)
    {
      selected_obj.SetHealth(Math.Clamp(value, 0, selected_obj_EAI.GetMaxHealth("", "")));
      EditorUpdate();
    }
  }
References Math::Clamp().
SelectedObjectSetPosX()
void PluginBase::SelectedObjectSetPosX (float value) inline private
Definition at line 505 of file PluginSceneManager.c.
  {
    SceneObject selected_obj = GetSelectedSceneObject();
    if (selected_obj)
    {
      vector v = selected_obj.GetPosition();
      v[0] = value;
      selected_obj.SetPosition(v);
      EditorUpdate();
    }
  }
SelectedObjectSetPosY()
void PluginBase::SelectedObjectSetPosY (float value) inline private
Definition at line 522 of file PluginSceneManager.c.
  {
    SceneObject selected_obj = GetSelectedSceneObject();
    if (selected_obj)
    {
      vector v = selected_obj.GetPosition();
      v[1] = value;
      selected_obj.SetPosition(v);
      EditorUpdate();
    }
  }
SelectedObjectSetPosZ()
void PluginBase::SelectedObjectSetPosZ (float value) inline private
Definition at line 539 of file PluginSceneManager.c.
  {
    SceneObject selected_obj = GetSelectedSceneObject();
    if (GetSelectedSceneObject())
    {
      vector v = selected_obj.GetPosition();
      v[2] = value;
      selected_obj.SetPosition(v);
      EditorUpdate();
    }
  }
SelectedObjectSetRot()
void PluginBase::SelectedObjectSetRot (float dir) inline private
Definition at line 492 of file PluginSceneManager.c.
  {
    if (GetSelectedSceneObject())
    {
      GetSelectedSceneObject().SetRotation(dir);
      EditorUpdate();
    }
  }
SelectObject()
void PluginBase::SelectObject (SceneObject obj) inline private
Definition at line 442 of file PluginSceneManager.c.
  {
    if (GetSelectedSceneObject() != NULL && GetSelectedSceneObject() == obj)
      return;
    DeselectObject();
    m_SelectedObject = obj;
    EditorUpdate();
  }
References m_SelectedObject.
SendDebug() [1/2]
void PluginBase::SendDebug () inline private
Definition at line 53 of file PluginRemotePlayerDebugServer.c.
  {
#ifdef DIAG_DEVELOPER
    GatherPlayerInfo();
    array<ref RemotePlayerDamageDebug> player_damage = new array<ref RemotePlayerDamageDebug>;
    for (int i = 0; i < m_ClientList.Count(); ++i)
    {
      PlayerBase player = m_ClientList[i];
      if (player)
      {
        ScriptRPC rpc = new ScriptRPC();
        rpc.Write(m_PlayerDebugStats);
        foreach (PlayerBase player2, RemotePlayerDamageDebug value : m_PlayerDebugDamage)
        {
          if (player2)
            player_damage.Insert(value);
          //int xs = 1 + 1;
        }
        rpc.Write(player_damage);
        rpc.Send(player, ERPCs.DEV_PLAYER_DEBUG_DATA, true, player.GetIdentity());
        m_PlayerDebugDamage.Clear();
      }
      else
      {
        m_ClientList.Remove(i);
        --i;
      }
    }
#endif
  }
References m_PlayerDebugDamage, and m_PlayerDebugStats.
Referenced by OnUpdate().
SendDebug() [2/2]
void PluginBase::SendDebug () inline protected
Definition at line 81 of file PluginUniversalTemperatureSourceServer.c.
  {
    int clientCount = m_ClientList.Count();
    foreach (PlayerBase player : m_ClientList)
    {
      if (player)
      {
        GatherTemperatureSources(player);
        ScriptRPC rpc = new ScriptRPC();
        rpc.Write(m_UTemperatureSourceDebugs);
        rpc.Send(player, ERPCs.DEV_UTS_DEBUG_DATA, true, player.GetIdentity());
      }
      else
        m_ClientList.RemoveItem(player);
    }
  }
References GatherTemperatureSources(), and m_ClientList.
SendRPCAgents()
void PluginBase::SendRPCAgents (PlayerBase player) inline private
Definition at line 681 of file PluginDeveloperSync.c.
  {
    //write and send values
    if ((player && player.GetIdentity() && player.m_AgentPool != null) || (player && !GetGame().IsMultiplayer() && player.m_AgentPool != null))
    {
      //get agent pool data
      array<ref Param> agent_pool = new array<ref Param>;
      player.m_AgentPool.GetDebugObject(agent_pool);
      GetDayZGame().RPC(player, ERPCs.DEV_RPC_AGENTS_DATA, agent_pool, true, player.GetIdentity());
    }
  }
References GetDayZGame(), and GetGame().
Referenced by Update().
SendRPCLevels()
void PluginBase::SendRPCLevels (PlayerBase player) inline private
Definition at line 462 of file PluginDeveloperSync.c.
  {
    //write and send values
    if (player)
    {
      array<ref Param> rpc_params = new array<ref Param>;
      rpc_params.Insert(new Param3<string, float, float>("Immunity: " + typename.EnumToString(EStatLevels, player.GetImmunityLevel()), player.GetImmunityLevel(), player.GetBordersImmunity()));
      rpc_params.Insert(new Param3<string, float, float>("Blood: " + typename.EnumToString(EStatLevels, player.GetStatLevelBlood()), player.GetStatLevelBlood(), player.GetStatBordersBlood()));
      rpc_params.Insert(new Param3<string, float, float>("Health: " + typename.EnumToString(EStatLevels, player.GetStatLevelHealth()), player.GetStatLevelHealth(), player.GetStatBordersHealth()));
      rpc_params.Insert(new Param3<string, float, float>("Energy: " + typename.EnumToString(EStatLevels, player.GetStatLevelEnergy()), player.GetStatLevelEnergy(), player.GetStatBordersEnergy()));
      rpc_params.Insert(new Param3<string, float, float>("Water: " + typename.EnumToString(EStatLevels, player.GetStatLevelWater()), player.GetStatLevelWater(), player.GetStatBordersWater()));
      int param_count = rpc_params.Count();
      rpc_params.InsertAt(new Param3<string, float, float>("PARAM_COUNT", param_count, 0), 0);
      //send params
      GetDayZGame().RPC(player, ERPCs.DEV_RPC_LEVELS_DATA, rpc_params, true, player.GetIdentity());
    }
  }
References GetDayZGame().
Referenced by Update().
SendRPCMods()
void PluginBase::SendRPCMods (PlayerBase player) inline private
Definition at line 504 of file PluginDeveloperSync.c.
  {
    //write and send values
    if (player)
    {
      array<ref Param> rpc_params = new array<ref Param>;
      //get modifiers
      ModifiersManager mods_manager = player.GetModifiersManager();
      //param count
      array<ref ModifierDebugObj> modifiers = new array<ref ModifierDebugObj>;
      mods_manager.DbgGetModifiers(modifiers);
      float param_count = (float) modifiers.Count();
      rpc_params.Insert(new Param1<int>(param_count));
      //set modifiers
      for (int i = 0; i < modifiers.Count(); ++i)
      {
        int id = modifiers.Get(i).GetID();
        string name = modifiers.Get(i).GetName();
        bool active = modifiers.Get(i).IsActive();
        bool locked = modifiers.Get(i).IsLocked();
        rpc_params.Insert(new Param4<int, string, bool, bool>(id, name, active, locked));
      }
      //send params
      GetDayZGame().RPC(player, ERPCs.DEV_RPC_MODS_DATA, rpc_params, true, player.GetIdentity());
    }
  }
References GetDayZGame(), ModifiersManager(), and name.
Referenced by Update().
SendRPCModsDetail()
void PluginBase::SendRPCModsDetail (PlayerBase player) inline private
Definition at line 541 of file PluginDeveloperSync.c.
  {
    //write and send values
    if (player)
    {
      Param1<string> p1 = new Param1<string>("");
      ModifiersManager mods_manager = player.GetModifiersManager();
      int mod_id = m_RegisteredPlayers.Get(player).m_DetailedModifierIndex;
      p1.param1 = mods_manager.GetModifier(mod_id).GetDebugText();
      //send params
      if (p1.param1 != "")
        GetDayZGame().RPCSingleParam(player, ERPCs.DEV_RPC_MODS_DATA_DETAILED, p1, true, player.GetIdentity());
    }
  }
References GetDayZGame(), and ModifiersManager().
Referenced by Update().
SendRPCStats()
void PluginBase::SendRPCStats (PlayerBase player) inline private
Definition at line 373 of file PluginDeveloperSync.c.
  {
    //write and send values
    if (player)
    {
      array<ref Param> rpc_params = new array<ref Param>;
      //param count
      for (int i = 0; i < player.m_PlayerStats.GetPCO().Get().Count(); i++)
      {
        string label = player.m_PlayerStats.GetPCO().Get().Get(i).GetLabel();
        float value = (float) player.m_PlayerStats.GetPCO().Get().Get(i).Get();
        float value_norm = (float) player.m_PlayerStats.GetPCO().Get().Get(i).GetNormalized();
        rpc_params.Insert(new Param3<string, float, float>(label, value, value_norm));
      }
      rpc_params.Insert(new Param3<string, float, float>("(NaS)Immunity", player.GetImmunity(), 0));
      rpc_params.Insert(new Param3<string, float, float>("(NaS)BrokenLegs", player.m_BrokenLegState, 0));
      rpc_params.InsertAt(new Param1<int>(rpc_params.Count()), 0); // param count
      //send params
      GetDayZGame().RPC(player, ERPCs.DEV_RPC_STATS_DATA, rpc_params, true, player.GetIdentity());
    }
  }
References Count, Get(), and GetDayZGame().
Referenced by Update().
SendRPCStomach()
void PluginBase::SendRPCStomach (PlayerBase player) inline private
Definition at line 721 of file PluginDeveloperSync.c.
  {
    //write and send values
    if (player)
    {
      array<ref Param> stomach = new array<ref Param>;
      int count = player.m_PlayerStomach.GetDebugObject(stomach);
      stomach.InsertAt(new Param1<int>(count), 0);
      GetDayZGame().RPC(player, ERPCs.DEV_RPC_STOMACH_DATA, stomach, true, player.GetIdentity());
    }
  }
References GetDayZGame().
Referenced by Update().
SendRPCTemp()
void PluginBase::SendRPCTemp (PlayerBase player) inline private
Definition at line 656 of file PluginDeveloperSync.c.
  {
    if (player)
    {
      CachedObjectsParams.PARAM1_STRING.param1 = player.m_Environment.GetDebugMessage();
      GetDayZGame().RPCSingleParam(player, ERPCs.DEV_TEMP_UPDATE, CachedObjectsParams.PARAM1_STRING, true, player.GetIdentity());
    }
  }
References GetDayZGame(), and CachedObjectsParams::PARAM1_STRING.
Referenced by Update().
SendServerLogToClient()
void PluginBase::SendServerLogToClient (string msg) inline protected
Definition at line 124 of file PluginDeveloper.c.
  {
    if (GetGame())
    {
      array<Man> players = new array<Man>;
      GetGame().GetPlayers(players);
      for (int i = 0; i < players.Count(); ++i)
      {
        Param1<string> param = new Param1<string>(msg);
        Man player = players.Get(i);
        if (player && player.HasNetworkID())
          player.RPCSingleParam(ERPCs.DEV_RPC_SEND_SERVER_LOG, param, true, player.GetIdentity());
      }
    }
  }
References GetGame().
SetBadge()
void PluginBase::SetBadge (int key, int value) inline private
Definition at line 62 of file PluginPlayerStatus.c.
  {
    if (key)
    {
      Mission mission = GetGame().GetMission();
      if (mission)
      {
        Hud hud = mission.GetHud();
        if (hud)
          hud.DisplayBadge(key, value);
      }
    }
  }
References GetGame(), Mission::GetHud(), and mission.
SetDate()
void PluginBase::SetDate (int year, int month, int day, int hour, int minute) inline private
Definition at line 813 of file PluginSceneManager.c.
  {
    m_SceneData.SetInitYear(year);
    m_SceneData.SetInitMonth(month);
    m_SceneData.SetInitDay(day);
    m_SceneData.SetInitHour(hour);
    m_SceneData.SetInitMinute(minute);
  }
SetDeveloperItemClient()
void PluginBase::SetDeveloperItemClient () inline private
Definition at line 872 of file PluginDeveloper.c.
  {
#ifdef DEVELOPER
    Object entity;
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    FreeDebugCamera debugCam = FreeDebugCamera.GetInstance();
    if (debugCam && debugCam.GetCurrentCamera())
      entity = debugCam.GetCrosshairObject();
    else
    {
      if (player && player.GetActionManager())
      {
        ActionTarget at = player.GetActionManager().FindActionTarget();
        entity = at.GetObject();
      }
    }
    if (entity)
      SetDeveloperItemClientEx(entity, true);
#endif
  }
References GetGame(), GetPlayer(), and SetDeveloperItemClientEx().
SetDeveloperItemClientEx()
static void PluginBase::SetDeveloperItemClientEx (notnull Object entity, bool getFocus = false) inline static private
Definition at line 850 of file PluginDeveloper.c.
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (getFocus)
    {
      GetGame().GetInput().ChangeGameFocus(1);
      GetGame().GetUIManager().ShowUICursor(true);
    }
    if (GetGame().IsMultiplayer())
      GetGame().RPCSingleParam(GetGame().GetPlayer(), ERPCs.DEV_SET_DEV_ITEM, new Param1<Object>(entity), true, GetGame().GetPlayer().GetIdentity());
    else
    {
      PluginItemDiagnostic mid2 = PluginItemDiagnostic.Cast(GetPlugin(PluginItemDiagnostic));
      mid2.RegisterDebugItem(entity, player);
    }
#ifdef DEVELOPER
    SetDebugDeveloper_item(entity);
#endif
  }
References GetGame(), GetPlayer(), GetPlugin(), and PluginItemDiagnostic().
Referenced by SetDeveloperItemClient().
SetDrawSelection()
void PluginBase::SetDrawSelection (bool draw) inline private
Definition at line 658 of file PluginSceneManager.c.
  {
    m_ModuleConfigDebugProfile.SetSceneEditorDrawSelection(draw);
    EditorUpdate();
  }
SetLoadPlayerPos()
void PluginBase::SetLoadPlayerPos (bool save) inline private
Definition at line 676 of file PluginSceneManager.c.
  {
    m_ModuleConfigDebugProfile.SetSceneEditorLoadPlayerPos(save);
  }
SetNotifier()
void PluginBase::SetNotifier (int key, int index = 9, string label = "", int color = 0xFFFFFFFF) inline private
Definition at line 23 of file PluginPlayerStatus.c.
  {
    if (key)
    {
      if (m_NotifiersLabel.HasKey(key))
      {
        m_NotifiersLabel.Remove(key);
        m_NotifiersIndexColor.Remove(key);
      }
      if (label != "")
      {
        m_NotifiersLabel.Insert(key, label);
        m_NotifiersIndexColor.Insert(key, index);
        m_NotifiersIndexColor.Insert(key, color);
      }
    }
  }
SetRotationAngle()
void PluginBase::SetRotationAngle (int angle) inline private
Definition at line 692 of file PluginSceneManager.c.
  {
    m_ModuleConfigDebugProfile.SetSceneEditorRotationAngle(angle);
  }
SetStamina()
void PluginBase::SetStamina (int value, int range) inline private
Definition at line 76 of file PluginPlayerStatus.c.
  {
    // Log( String( "SetStamina" + itoa( value) ), LogTemplates.TEMPLATE_JANOSIK );
    Mission mission = GetGame().GetMission();
    if (mission)
    {
      Hud hud = mission.GetHud();
      if (hud)
        hud.SetStamina(Math.Clamp(value, 0, range), range);
    }
  }
References Math::Clamp(), GetGame(), Mission::GetHud(), and mission.
SetStance()
void PluginBase::SetStance (int value) inline private
Definition at line 88 of file PluginPlayerStatus.c.
  {
    Mission mission = GetGame().GetMission();
    if (mission)
    {
      Hud hud = mission.GetHud();
      if (hud)
        hud.DisplayStance(value);
    }
  }
References GetGame(), Mission::GetHud(), and mission.
SetSystemInBitmask()
void PluginBase::SetSystemInBitmask (PlayerBase player, int system_bit, bool state) inline private
Definition at line 181 of file PluginDeveloperSync.c.
  {
    if (IsPlayerRegistered(player))
    {
      int current_mask = m_RegisteredPlayers.Get(player).m_Bitmask;
      if (state)
        m_RegisteredPlayers.Get(player).m_Bitmask = current_mask | system_bit;
      else
        m_RegisteredPlayers.Get(player).m_Bitmask = current_mask & ~system_bit;
    }
  }
References IsPlayerRegistered().
Referenced by EnableUpdate(), and RequestDetailedInfo().
SetupSpawnedEntity()
void PluginBase::SetupSpawnedEntity (PlayerBase player, EntityAI entity, float health, float quantity = -1, bool special = false, string presetName = "") inline protected
Definition at line 292 of file PluginDeveloper.c.
  {
#ifdef DEVELOPER
    if (presetName && player.m_PresetSpawned)//this is how we ascertain this is the first item being spawned from a new preset after a previous preset was already spawned in
    {
      player.m_PresetItems.Clear();
      player.m_PresetSpawned = false;//is set to 'true' elsewhere after all the items have been spawned in
    }
    if (entity.IsInherited(PlayerBase))
    {
      PlayerBase plr = PlayerBase.Cast(entity);
      plr.OnSpawnedFromConsole();
    }
    else if (entity.IsInherited(ItemBase))
    {
      ItemBase item = ItemBase.Cast(entity);
      SetupSpawnedItem(item, health, quantity);
    }
    else if (entity.IsInherited(House))
    {
      entity.PlaceOnSurface();
      vector pos = entity.GetPosition();
      vector ori = GetGame().GetSurfaceOrientation(pos[0], pos[2]);
      entity.SetOrientation(ori);
    }
    if (presetName)
      player.m_PresetItems.Insert(entity);
    if (special)
    {
      auto debugParams = DebugSpawnParams.WithPlayer(player);
      entity.OnDebugSpawnEx(debugParams);
    }
#endif
  }
References GetGame(), and SetupSpawnedItem().
Referenced by SpawnEntityOnCursorDir(), and SpawnEntityOnGroundPos().
SetWatching()
void PluginBase::SetWatching (bool enable) inline private
Definition at line 29 of file PluginRemotePlayerDebugServer.c.
  {
    m_Watching = enable;
  }
SetWeather()
void PluginBase::SetWeather (float overcast, float rain, float fog, float wind_force) inline private
Definition at line 802 of file PluginSceneManager.c.
  {
    m_SceneData.SetInitOvercast(overcast);
    m_SceneData.SetInitRain(rain);
    m_SceneData.SetInitFog(fog);
    m_SceneData.SetInitWindForce(wind_force);
  }
Show() [1/3]
void PluginBase::Show () inline private
Definition at line 161 of file PluginDayZInfectedDebug.c.
  {
    ShowWidgets(true);
    m_IsActive = true;
    GetUApi().ActivateExclude("menu");
    GetUApi().UpdateControls();
    if (!m_TickTimer)
    {
      m_TickTimer = new Timer();
      m_TickTimer.Run(0.1, this, "Tick", NULL, true);
    }
  }
References GetUApi(), m_IsActive, m_TickTimer, and ShowWidgets().
Referenced by EnableWidgets(), SetDebugShowMode(), ToggleDebugWindowEventOld(), ToggleDebugWindowEventP(), ToggleDebugWindowSetMode(), and ToggleDebugWindowSetMode().
Show() [2/3]
void PluginBase::Show () inline private
Definition at line 74 of file PluginDrawCheckerboard.c.
  {
    ShowWidgets(true);
    m_IsActive = true;
  }
References m_IsActive, and ShowWidgets().
Show() [3/3]
void PluginBase::Show () inline private
Definition at line 19 of file PluginSoundDebug.c.
  {
    m_TickTimer = new Timer();
    m_TickTimer.Run(0.1, this, "OnGUITimer", NULL, true);
  }
References m_TickTimer.
ShowCard()
void PluginBase::ShowCard (int pCard) inline private
Definition at line 275 of file PluginDayZInfectedDebug.c.
  {
    m_CardMovementFrame.Show(pCard == 0);
    m_CardFightFrame.Show(pCard == 1);
  }
Referenced by CreateModuleWidgets(), CreateModuleWidgets(), and OnClick().
ShowWidgets() [1/2]
void PluginBase::ShowWidgets (bool show) inline private
Definition at line 188 of file PluginDayZInfectedDebug.c.
  {
    if (m_MainWnd)
      m_MainWnd.Show(show);
  }
References m_MainWnd.
Referenced by Hide(), Hide(), Show(), and Show().
ShowWidgets() [2/2]
void PluginBase::ShowWidgets (bool show) inline private
Definition at line 67 of file PluginDrawCheckerboard.c.
  {
    if (m_MainWindow)
      m_MainWindow.Show(show);
  }
SortStringArray()
void PluginBase::SortStringArray (TStringArray arr) inline private
Definition at line 839 of file PluginDeveloper.c.
  {
    QuickSort(arr, 0, arr.Count() - 1);
  }
References QuickSort().
SpawnEntityAsAttachment()
PluginBase::SpawnEntityAsAttachment (PlayerBase player, EntityAI parent, string att_name, float health, float quantity) inline protected
tries to spawn item as attachment
Parameters
[in] health health of the item
[in] quantity quantity to set if item.HasQuantity() (-1 == set to max)
Returns
entity if ok, null otherwise
Definition at line 602 of file PluginDeveloper.c.
  {
    if (GetGame().IsServer())
    {
      Weapon_Base wpn = Weapon_Base.Cast(parent);
      if (wpn)
      {
        GameInventory inventory = parent.GetInventory();
        return inventory.CreateInInventory(att_name);
        /*
          vector pos = player.GetPosition();
          EntityAI eai_gnd = SpawnEntityOnGroundPos(player, att_name, health, quantity, pos);
          Magazine mag_gnd = Magazine.Cast(eai_gnd);
          if (mag_gnd && player.GetWeaponManager().CanAttachMagazine(wpn, mag_gnd))
          {
          player.GetWeaponManager().AttachMagazine(mag_gnd);
          }
          return eai_gnd;
        */
      }
      else
      {
        EntityAI eai = parent.GetInventory().CreateAttachment(att_name);
        if (eai)
        {
          if (eai.IsInherited(ItemBase))
          {
            ItemBase i = ItemBase.Cast(eai);
            SetupSpawnedItem(ItemBase.Cast(eai), health, quantity);
          }
          return eai;
        }
        else
          OnSpawnErrorReport(att_name);
      }
      return NULL;
    }
    else
    {
      // Client -> Server Spawning: Client Side
      Param3<string, float, float> params = new Param3<string, float, float>(att_name, health, quantity);
      player.RPCSingleParam(ERPCs.DEV_RPC_SPAWN_ITEM_AS_ATTACHMENT, params, true);
    }
    return NULL;
  }
References GetGame(), OnSpawnErrorReport(), and SetupSpawnedItem().
SpawnEntityInInventory()
PluginBase::SpawnEntityInInventory (notnull EntityAI target, string className, float health, float quantity, bool special = false, string presetName = "", FindInventoryLocationType locationType = FindInventoryLocationType.ANY) inline protected
tries to spawn item somewhere in inventory
SpawnEntityInInventory queries future parent about free inventory location of the future item
Parameters
[in] health health of the item
[in] quantity quantity to set if item.HasQuantity() (-1 == set to max)
Returns
entity if ok, null otherwise
Definition at line 483 of file PluginDeveloper.c.
  {
    if (target.IsPlayer())
      return SpawnEntityInPlayerInventory(PlayerBase.Cast(target), className, health, quantity, special, presetName, locationType);
    if (GetGame().IsServer())
    {
      InventoryLocation il = new InventoryLocation;
      if (target.GetInventory() && target.GetInventory().FindFirstFreeLocationForNewEntity(className, FindInventoryLocationType.ANY, il))
      {
        EntityAI eai = SpawnEntity(className, il, ECE_IN_INVENTORY, RF_DEFAULT);
        if (eai && eai.IsInherited(ItemBase))
        {
          if (health < 0) //check for default (-1)
            health = eai.GetMaxHealth();
          ItemBase i = ItemBase.Cast(eai);
          SetupSpawnedItem(i, health, quantity);
          if (special)
          {
            auto debugParams = DebugSpawnParams.WithPlayer(null);
            eai.OnDebugSpawnEx(debugParams);
          }
        }
        return eai;
      }
    }
    else
    {
      DevSpawnItemParams params = new DevSpawnItemParams(target, className, health, quantity, special, presetName, 0);
      GetGame().GetPlayer().RPCSingleParam(ERPCs.DEV_RPC_SPAWN_ITEM_IN_INVENTORY, params, true, GetGame().GetPlayer().GetIdentity());
    }
    return null;
  }
References ECE_IN_INVENTORY, GetGame(), GetPlayer(), RF_DEFAULT, SetupSpawnedItem(), SpawnEntity(), and SpawnEntityInPlayerInventory().
Referenced by OnRPCSpawnEntity().
SpawnEntityInPlayerInventory()
EntityAI PluginBase::SpawnEntityInPlayerInventory (PlayerBase player, string item_name, float health, float quantity, bool special = false, string presetName = "", FindInventoryLocationType locationType = FindInventoryLocationType.ANY) inline protected
Definition at line 516 of file PluginDeveloper.c.
  {
    if (player)
    {
      if (GetGame().IsServer())
      {
        if (locationType == FindInventoryLocationType.HANDS && player.GetItemInHands())
        {
          if (!GetGame().IsMultiplayer())
            player.DropItem(player.GetItemInHands());
          else
            player.ServerDropEntity(player.GetItemInHands());
          GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(SpawnEntityInPlayerInventory, 100, false, player, item_name, health, quantity, special, presetName, locationType);
          return null;
        }
#ifdef DEVELOPER
        if (GetGame().IsKindOf(item_name, "Transport"))
        {
          EntityAI car = SpawnEntityOnGroundPos(player, item_name, 1, quantity, player.GetPosition());
          auto debugParams = DebugSpawnParams.WithPlayer(player);
          car.OnDebugSpawnEx(debugParams);
          if (GetGame().IsMultiplayer())
            DayZPlayerSyncJunctures.SendGetInCar(player, car);
          else
            player.SetGetInVehicleDebug(car);
          return car;
        }
#endif
        InventoryLocation il = new InventoryLocation;
        if (player.GetInventory() && player.GetInventory().FindFirstFreeLocationForNewEntity(item_name, locationType, il))
        {
          Weapon_Base wpn = Weapon_Base.Cast(il.GetParent());
          bool is_mag = il.GetSlot() == InventorySlots.MAGAZINE || il.GetSlot() == InventorySlots.MAGAZINE2 || il.GetSlot() == InventorySlots.MAGAZINE3;
          if (wpn && is_mag)
          {
            vector pos = player.GetPosition();
            EntityAI eai_gnd = SpawnEntityOnGroundPos(player, item_name, health, quantity, pos);
            Magazine mag_gnd = Magazine.Cast(eai_gnd);
            if (mag_gnd && player.GetWeaponManager().CanAttachMagazine(wpn, mag_gnd))
              player.GetWeaponManager().AttachMagazine(mag_gnd);
            return eai_gnd;
          }
          else
          {
            EntityAI eai = SpawnEntity(item_name, il, ECE_IN_INVENTORY, RF_DEFAULT);
            if (eai && eai.IsInherited(ItemBase))
            {
              if (health < 0) //check for default (-1)
                health = eai.GetMaxHealth();
              ItemBase i = ItemBase.Cast(eai);
              SetupSpawnedItem(i, health, quantity);
              if (special)
              {
                auto debugParams2 = DebugSpawnParams.WithPlayer(player);
                eai.OnDebugSpawnEx(debugParams2);
              }
            }
            return eai;
          }
        }
        else
          OnSpawnErrorReport(item_name);
        return NULL;
      }
      else
      {
        // Client -> Server Spawning: Client Side
        DevSpawnItemParams params = new DevSpawnItemParams(player, item_name, health, quantity, special, presetName, locationType);
        player.RPCSingleParam(ERPCs.DEV_RPC_SPAWN_ITEM_IN_INVENTORY, params, true);
      }
    }
    return NULL;
  }
References CALL_CATEGORY_SYSTEM, ECE_IN_INVENTORY, GetGame(), OnSpawnErrorReport(), RF_DEFAULT, SetupSpawnedItem(), SpawnEntity(), and SpawnEntityOnGroundPos().
Referenced by SpawnEntityInInventory().
SpawnEntityOnCursorDir()
PluginBase::SpawnEntityOnCursorDir (PlayerBase player, string item_name, float quantity, float distance, float health = -1, bool special = false, string presetName = "", bool withPhysics = false) inline protected
spawns entity in direction of cursor at specified distance
Parameters
[in] health health of the item
[in] quantity quantity to set if item.HasQuantity() (-1 == set to max)
[in] distance distance of the item from player
Returns
entity if ok, null otherwise
Definition at line 442 of file PluginDeveloper.c.
  {
    if (GetGame().IsServer())
    {
      // Client -> Server Spawning: Server Side
      EntityAI entity = player.SpawnEntityOnGroundOnCursorDir(item_name, distance);
      if (entity)
      {
        if (!entity.IsBuilding() && health < 0 && entity.GetMaxHealth() > 0) //check for default (-1)
          health = entity.GetMaxHealth();
        SetupSpawnedEntity(player, entity, health, quantity, special, presetName);
      }
      else
        OnSpawnErrorReport(item_name);
      InventoryItem item;
      if (Class.CastTo(item, entity) && withPhysics)
        item.ThrowPhysically(null, "0 0 0");
      return entity;
    }
    else
    {
      // Client -> Server Spawning: Client Side
      Param7<string, float, float, float, bool, string, bool> params = new Param7<string, float, float, float, bool, string, bool>(item_name, quantity, distance, health, special, presetName, withPhysics);
      player.RPCSingleParam(ERPCs.DEV_RPC_SPAWN_ITEM_ON_CURSOR, params, true);
    }
    return NULL;
  }
References Class::CastTo(), GetGame(), OnSpawnErrorReport(), and SetupSpawnedEntity().
Referenced by OnRPCSpawnEntityOnCursorDir(), and SpawnFromClipboard().
SpawnEntityOnGroundPatternGrid()
void PluginBase::SpawnEntityOnGroundPatternGrid (PlayerBase player, string item_name, int count, float health, float quantity, int rows, int columns, float gapRow = 1, float gapColumn = 1, bool special = false, bool withPhysics = false) inline protected
Definition at line 329 of file PluginDeveloper.c.
  {
    if (!item_name)
      return;
    if (GetGame().IsServer())
    {
      float rowDist = 0;
      float columnDist = 0;
      vector playerPos = player.GetPosition();
      vector camDirForward = player.GetDirection();
      vector camDirRight = camDirForward.Perpend() * -1;
      int countLoop = 0;
      for (int i = 0; i < rows; i++)
      {
        vector posRow = playerPos + camDirForward * rowDist;
        vector offsetSide;
        columnDist = 0;
        for (int j = 0; j < columns; j++)
        {
          offsetSide = camDirRight * columnDist;
          vector placement = posRow + offsetSide;
          float hlth = health * MiscGameplayFunctions.GetTypeMaxGlobalHealth(item_name);
          EntityAI ent = SpawnEntityOnGroundPos(player, item_name, hlth, quantity, placement, special);
          ent.PlaceOnSurface();
          InventoryItem item;
          if (Class.CastTo(item, ent) && withPhysics)
            item.ThrowPhysically(null, "0 0 0");
          countLoop++;
          if (countLoop == count)
            return;
          columnDist += gapColumn;
        }
        rowDist += gapRow;
      }
    }
    else
    {
      auto params = new Param10<string, int, float, float, int, int, float, float, bool, bool>(item_name, count, health, quantity, rows, columns, gapRow, gapColumn, special, withPhysics);
      player.RPCSingleParam(ERPCs.DEV_RPC_SPAWN_ITEM_ON_GROUND_PATTERN_GRID, params, true);
    }
  }
References Class::CastTo(), GetGame(), and SpawnEntityOnGroundPos().
Referenced by OnRPCSpawnEntityOnGroundPatternGrid().
SpawnEntityOnGroundPos()
PluginBase::SpawnEntityOnGroundPos (PlayerBase player, string item_name, float health, float quantity, vector pos, bool special = false, bool withPhysics = false) inline protected
spawns entity on exact position
Parameters
[in] health health of the item
[in] quantity quantity to set if item.HasQuantity() (-1 == set to max)
[in] pos position where to spawn
Returns
entity if ok, null otherwise
Definition at line 411 of file PluginDeveloper.c.
  {
    if (GetGame().IsServer())
    {
      EntityAI entity = player.SpawnEntityOnGroundPos(item_name, pos);
      if (entity)
        SetupSpawnedEntity(player, entity, health, quantity, special);
      else
        OnSpawnErrorReport(item_name);
      InventoryItem item;
      if (Class.CastTo(item, entity) && withPhysics)
        item.ThrowPhysically(null, "0 0 0");
      return entity;
    }
    else
    {
      Param6<string, float, float, vector, bool, bool> params = new Param6<string, float, float, vector, bool, bool>(item_name, health, quantity, pos, special, withPhysics);
      player.RPCSingleParam(ERPCs.DEV_RPC_SPAWN_ITEM_ON_GROUND, params, true);
    }
    return NULL;
  }
References Class::CastTo(), GetGame(), OnSpawnErrorReport(), and SetupSpawnedEntity().
Referenced by OnRPCSpawnEntityOnGround(), SpawnEntityInPlayerInventory(), SpawnEntityOnGroundPatternGrid(), and SpawnItemOnCrosshair().
SpawnFromClipboard()
EntityAI PluginBase::SpawnFromClipboard () inline protected
Definition at line 648 of file PluginDeveloper.c.
  {
    UIScriptedMenu menu_curr = GetGame().GetUIManager().GetMenu();
    if (menu_curr == NULL)
    {
      PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
      if (player)
      {
        if (!GetGame().GetWorld().Is3rdPersonDisabled())
        {
          player.SetIsInThirdPerson(!player.IsInThirdPerson());//this counters the effect of switching camera through pressing the 'V' key
        }
        vector pos_player = player.GetPosition();
        // Get item from clipboard
        string clipboard;
        GetGame().CopyFromClipboard(clipboard);
        if (!clipboard.Contains(","))
        {
          //single item
          if (DeveloperFreeCamera.IsFreeCameraEnabled())
            SpawnItemOnCrosshair(player, clipboard.Trim(), -1, 1, 40, true);
          else
            SpawnEntityOnCursorDir(player, clipboard.Trim(), 1, 1);
        }
        else
        {
          TStringArray items = new TStringArray;
          clipboard.Split(",", items);
          foreach (string item: items)
          {
            if (DeveloperFreeCamera.IsFreeCameraEnabled())
              SpawnItemOnCrosshair(player, item.Trim(), -1, 1, 40, true);
            else
              SpawnEntityOnCursorDir(player, item.Trim(), 1, 1);
          }
        }
      }
    }
    return NULL;
  }
References GetGame(), GetPlayer(), DeveloperFreeCamera::IsFreeCameraEnabled(), SpawnEntityOnCursorDir(), and SpawnItemOnCrosshair().
SpawnItemOnCrosshair()
void PluginBase::SpawnItemOnCrosshair (notnull PlayerBase player, string itemName, float health, float quantity, float maxDist = 100, bool allowFreeflight = false, bool special = false, bool withPhysics = false) inline protected
Definition at line 374 of file PluginDeveloper.c.
  {
    vector from, to;
    if (allowFreeflight && FreeDebugCamera.GetInstance().IsActive())
    {
      from = FreeDebugCamera.GetInstance().GetPosition();
      to = from + FreeDebugCamera.GetInstance().GetDirection() * maxDist;
    }
    else
    {
      from = GetGame().GetCurrentCameraPosition();
      to = from + GetGame().GetCurrentCameraDirection() * maxDist;
    }
    float hitFraction;
    vector start, end;
    vector direction;
    vector hitPos, hitNormal;
    Object obj;
    PhxInteractionLayers hitMask = PhxInteractionLayers.BUILDING | PhxInteractionLayers.DOOR | PhxInteractionLayers.VEHICLE | PhxInteractionLayers.ROADWAY | PhxInteractionLayers.TERRAIN | PhxInteractionLayers.CHARACTER | PhxInteractionLayers.AI | PhxInteractionLayers.RAGDOLL | PhxInteractionLayers.RAGDOLL_NO_CHARACTER;
    DayZPhysics.RayCastBullet(from, to, hitMask, player, obj, hitPos, hitNormal, hitFraction);
    // something is hit
    if (hitPos != vector.Zero)
      SpawnEntityOnGroundPos(player, itemName, health, quantity, hitPos, special, withPhysics);
  }
References GetGame(), DayZPhysics::RayCastBullet(), SpawnEntityOnGroundPos(), and vector::Zero.
Referenced by SpawnFromClipboard().
SpawnNewInfectedEntity()
void PluginBase::SpawnNewInfectedEntity () inline private
Definition at line 361 of file PluginDayZInfectedDebug.c.
  {
    m_ControlledInfected = DayZInfected.Cast(GetGame().CreateObjectEx("ZmbF_JournalistNormal_Blue", GetGame().GetPlayer().GetPosition(), ECE_PLACE_ON_SURFACE | ECE_INITAI | ECE_EQUIP_ATTACHMENTS));
    m_ControlledInfected.GetAIAgent().SetKeepInIdle(true);
  }
References ECE_EQUIP_ATTACHMENTS, ECE_INITAI, ECE_PLACE_ON_SURFACE, GetGame(), GetPlayer(), and GetPosition.
Referenced by OnClick().
Subscribe()
void PluginBase::Subscribe (MessageReceiverBase receiver, int index) inline private
Subscribes an object to listen to messages on a channel provided in the 'index' parameter.
Definition at line 105 of file PluginMessageManager.c.
  {
    if (index > channelsUsed) //this is used to speed up the unsubscribeAll method, instead of all channels, we sweep just those in usage
      channelsUsed = index;
    array<ref MessageReceiverBase> chan = channelList[index];
    if (chan.Find(receiver) >= 0) return;
    chan.Insert(receiver);
  }
Suicide()
void PluginBase::Suicide (PlayerBase player) inline protected
Definition at line 316 of file PluginAdminLog.c.
  {
    m_PlayerPrefix = GetPlayerPrefix(player, player.GetIdentity());
    LogPrint(m_PlayerPrefix + " committed suicide");
  }
References GetPlayerPrefix(), and LogPrint().
SwitchPermanentCrossHair()
void PluginBase::SwitchPermanentCrossHair (bool state) inline private
Definition at line 5 of file PluginPermanentCrossHair.c.
  {
    if (!m_Hud)
      m_Hud = GetGame().GetMission().GetHud();
    m_Hud.SetPermanentCrossHair(state);
  }
References GetGame(), m_Hud, and Hud::SetPermanentCrossHair().
Teleport()
void PluginBase::Teleport (PlayerBase player, vector position) inline protected
Teleport player at position.
Definition at line 20 of file PluginDeveloper.c.
  {
    DeveloperTeleport.SetPlayerPosition(player, position);
  }
References DeveloperTeleport::SetPlayerPosition().
TeleportAtCursor()
void PluginBase::TeleportAtCursor () inline protected
Set Player position at his cursor position in the world.
Definition at line 14 of file PluginDeveloper.c.
  {
    DeveloperTeleport.TeleportAtCursorEx();
  }
References DeveloperTeleport::TeleportAtCursorEx().
Tick()
void PluginBase::Tick () inline protected
Definition at line 441 of file PluginDayZInfectedDebug.c.
  {
    if (!m_ControlledInfected)
      return;
  }
ToggleCameraTools()
void PluginBase::ToggleCameraTools () inline protected
Definition at line 19 of file PluginCameraTools.c.
  {
    if (!m_IsOpen)
      GetGame().GetUIManager().EnterScriptedMenu(MENU_CAMERA_TOOLS, null);
    else
      GetGame().GetUIManager().Back();
    m_IsOpen = !m_IsOpen;
  }
References GetGame(), and MENU_CAMERA_TOOLS.
ToggleDebugWindowEvent()
void PluginBase::ToggleDebugWindowEvent () inline private
Definition at line 118 of file PluginDayZInfectedDebug.c.
  {
    m_CurrentMode++;
    if (m_CurrentMode > 2)
      m_CurrentMode = 0;
    ToggleDebugWindowSetMode(m_CurrentMode);
  }
References m_CurrentMode, and ToggleDebugWindowSetMode().
ToggleDebugWindowSetMode()
void PluginBase::ToggleDebugWindowSetMode (int pMode) inline private
Definition at line 128 of file PluginDayZInfectedDebug.c.
  {
    switch (pMode)
    {
    case 0: Hide(); ReleaseFocus(); CleanupDebugShapes(m_DebugShapes); break;
    case 1: Show(); ReleaseFocus(); break;
    case 2: Show(); CaptureFocus(); break;
    }
  }
References CaptureFocus(), CleanupDebugShapes(), Hide(), ReleaseFocus(), and Show().
Referenced by ToggleDebugWindowEvent(), and ToggleDebugWindowEvent().
ToggleFocus()
void PluginBase::ToggleFocus () inline private
Definition at line 805 of file PluginDeveloperSync.c.
  {
    if (GetGame().GetInput().HasGameFocus())
    {
      GetGame().GetInput().ChangeGameFocus(1);
      GetGame().GetUIManager().ShowUICursor(true);
    }
    else
    {
      GetGame().GetInput().ResetGameFocus();
      GetGame().GetUIManager().ShowUICursor(false);
    }
  }
References GetGame(), and GetInput().
ToggleFreeCamera()
void PluginBase::ToggleFreeCamera () inline protected
Enable / Disable Free camera (Fly mod) - disable of camera will teleport player at current free camera position.
Definition at line 32 of file PluginDeveloper.c.
  {
    DeveloperFreeCamera.FreeCameraToggle(PlayerBase.Cast(GetGame().GetPlayer()), true);
  }
References DeveloperFreeCamera::FreeCameraToggle(), GetGame(), and GetPlayer().
ToggleFreeCameraBackPos()
void PluginBase::ToggleFreeCameraBackPos () inline protected
Enable / Disable Free camera (Fly mod)
Definition at line 26 of file PluginDeveloper.c.
  {
    DeveloperFreeCamera.FreeCameraToggle(PlayerBase.Cast(GetGame().GetPlayer()), false);
  }
References DeveloperFreeCamera::FreeCameraToggle(), GetGame(), and GetPlayer().
ToggleHelpScreen()
void PluginBase::ToggleHelpScreen () inline protected
Definition at line 708 of file PluginDeveloper.c.
  {
    if (g_Game.GetUIManager().GetMenu() == NULL)
      g_Game.GetUIManager().EnterScriptedMenu(MENU_HELP_SCREEN, NULL);
    else if (g_Game.GetUIManager().IsMenuOpen(MENU_HELP_SCREEN))
      g_Game.GetUIManager().Back();
  }
References g_Game, and MENU_HELP_SCREEN.
ToggleMissionLoader()
void PluginBase::ToggleMissionLoader () inline protected
Definition at line 735 of file PluginDeveloper.c.
  {
    if (g_Game.GetUIManager().IsMenuOpen(MENU_MISSION_LOADER))
    {
      g_Game.GetUIManager().Back();
      GetGame().GetMission().RemoveActiveInputExcludes({"menu"}, true);
      return;
    }
    if (g_Game.GetUIManager().GetMenu())
      g_Game.GetUIManager().GetMenu().Close();
    g_Game.GetUIManager().EnterScriptedMenu(MENU_MISSION_LOADER, NULL);
    GetGame().GetMission().AddActiveInputExcludes({"menu"});
  }
References g_Game, GetGame(), and MENU_MISSION_LOADER.
ToggleScriptConsole()
void PluginBase::ToggleScriptConsole () inline protected
Definition at line 716 of file PluginDeveloper.c.
  {
    if (GetGame() != null && !g_Game.IsLoading() && GetGame().GetMission())
    {
      if (g_Game.GetUIManager().GetMenu() == NULL)
      {
        m_ScriptConsole = g_Game.GetUIManager().EnterScriptedMenu(MENU_SCRIPTCONSOLE, NULL);
        GetGame().GetMission().AddActiveInputExcludes({"menu"});
      }
      else if (g_Game.GetUIManager().IsMenuOpen(MENU_SCRIPTCONSOLE))
      {
        g_Game.GetUIManager().Back();
        GetGame().GetMission().RemoveActiveInputExcludes({"menu"}, true);
      }
    }
  }
References g_Game, GetGame(), and MENU_SCRIPTCONSOLE.
TotemFlagChange()
void PluginBase::TotemFlagChange (bool top, notnull PlayerBase player, notnull EntityAI totem) inline protected
Definition at line 331 of file PluginAdminLog.c.
  {
    if (m_ActionsFilter != 1)
      return;
    string prefix = GetPlayerPrefix(player, player.GetIdentity());
    string flagType = totem.FindAttachmentBySlotName("Material_FPole_Flag").ClassName();
    string action;
    if (top)
      action = "raised ";
    else
      action = "lowered ";
    LogPrint(prefix + " has " + action + flagType + " on " + totem.ClassName() + " at " + totem.GetPosition());
  }
References GetPlayerPrefix(), LogPrint(), and m_ActionsFilter.
TransmitAgents()
void PluginBase::TransmitAgents (EntityAI source, EntityAI target, int pathway, int dose_size = 1000) inline protected
Definition at line 256 of file PluginTransmissionAgents.c.
  {
    TransmitAgentsEx(source, target, pathway, dose_size);
  }
References TransmitAgentsEx().
TransmitAgentsEx()
float PluginBase::TransmitAgentsEx (EntityAI source, EntityAI target, int pathway, int dose_size = 1000, int agents = 0) inline protected
Definition at line 189 of file PluginTransmissionAgents.c.
  {
    //Debug.Log("Transmitting agents for source: " +source.ToString()+", target: " +target.ToString(),"Agents");
    int sourceAgents = agents;
    int targetAgents;
    if (!sourceAgents && source) sourceAgents = source.GetAgents(); //do not set sourceAgents again if already set
    if (target) targetAgents = target.GetAgents();
    float count = 0;
    switch (pathway)
    {
    case AGT_INV_OUT: //item leaving inventory
      break;
    case AGT_INV_IN: //item entering inventory
      break;
    case AGT_UACTION_TOUCH: //player touched the item
      //InjectAgents( source, targetAgents ,GetProtectionLevel(DEF_BIOLOGICAL,InventorySlots.GLOVES, player) );
      break;
    case AGT_WATER_POND:
      //target.InsertAgent(eAgents.CHOLERA, dose_size);
      InjectAgentsWithPlayer(target, eAgents.CHOLERA, 0, 1, InjectTypes.ITEM_TO_PLAYER);
      break;
    case AGT_UACTION_CONSUME:
      //InjectAgentsWithPlayer( target, sourceAgents , 0, dose_size, InjectTypes.ITEM_TO_PLAYER );
      InjectAgentsWithPlayer(source, targetAgents, 0, 1, InjectTypes.PLAYER_TO_ITEM);
      break;
    case AGT_UACTION_TO_PLAYER: //user action of a consumption, only from item to player
      InjectAgentsWithPlayerCount(target, sourceAgents, 0, dose_size, InjectTypes.ITEM_TO_PLAYER);
      break;
    case AGT_UACTION_TO_ITEM: //to transfer from the player to the consumed item
      InjectAgentsWithPlayer(target, sourceAgents, 0, 1, InjectTypes.PLAYER_TO_ITEM);
      break;
    case AGT_TRANSFER_COPY: //transferring liquid
      InjectAgentsWithoutPlayer(target, sourceAgents);
      break;
    case AGT_ITEM_TO_FLESH: //transferring liquid
      InjectAgentsWithPlayer(target, sourceAgents, 0, 1, InjectTypes.ITEM_TO_PLAYER);
      break;
    case AGT_AIRBOURNE_BIOLOGICAL:
      float prot_level_mask_target = GetProtectionLevel(DEF_BIOLOGICAL, InventorySlots.MASK, Man.Cast(target));
      float prot_level_mask_source = GetProtectionLevel(DEF_BIOLOGICAL, InventorySlots.MASK, Man.Cast(source));
      float prot_level_headgear_target = GetProtectionLevel(DEF_BIOLOGICAL, InventorySlots.HEADGEAR, Man.Cast(target));
      float prot_level_headgear_source = GetProtectionLevel(DEF_BIOLOGICAL, InventorySlots.HEADGEAR, Man.Cast(source));
      float prot_level_target = Math.Max(prot_level_mask_target, prot_level_headgear_target);//find the bigger of the 2, TODO: should be improved
      float prot_level_source = Math.Max(prot_level_mask_source, prot_level_headgear_source);//find the bigger of the 2, TODO: should be improved
      float prot_level_combined = 1 - (1 - prot_level_target) * (1 - prot_level_source);
      InjectAgentsWithPlayer(target, sourceAgents, prot_level_combined, 1, InjectTypes.PLAYER_AIR_PLAYER);
      break;
    case AGT_AIRBOURNE_CHEMICAL:
      float prot_level_mask_target2 = GetProtectionLevel(DEF_CHEMICAL, InventorySlots.MASK, Man.Cast(target));
      count = InjectAgentWithPlayerDose(target, agents, prot_level_mask_target2, dose_size, InjectTypes.PLAYER_AIR_PLAYER);
      break;
    }
    return count;
  }
References AGT_AIRBOURNE_BIOLOGICAL, AGT_AIRBOURNE_CHEMICAL, AGT_INV_IN, AGT_INV_OUT, AGT_ITEM_TO_FLESH, AGT_TRANSFER_COPY, AGT_UACTION_CONSUME, AGT_UACTION_TO_ITEM, AGT_UACTION_TO_PLAYER, AGT_UACTION_TOUCH, AGT_WATER_POND, DEF_BIOLOGICAL, DEF_CHEMICAL, GetProtectionLevel(), InjectAgentsWithoutPlayer(), InjectAgentsWithPlayer(), InjectAgentsWithPlayerCount(), InjectAgentWithPlayerDose(), and Math::Max().
Referenced by TransmitAgents().
UnconStart()
void PluginBase::UnconStart (PlayerBase player) inline protected
Definition at line 269 of file PluginAdminLog.c.
  {
    m_PlayerPrefix = GetPlayerPrefix(player, player.GetIdentity());
    LogPrint(m_PlayerPrefix + " is unconscious");
  }
References GetPlayerPrefix(), and LogPrint().
UnconStop()
void PluginBase::UnconStop (PlayerBase player) inline protected
Definition at line 276 of file PluginAdminLog.c.
  {
    if (player.IsAlive()) // Do not log uncon stop for dead players
    {
      m_PlayerPrefix = GetPlayerPrefix(player, player.GetIdentity());
      LogPrint(m_PlayerPrefix + " regained consciousness");
    }
  }
References GetPlayerPrefix(), and LogPrint().
UnlinkSceneObjects()
void PluginBase::UnlinkSceneObjects (SceneObject scene_object1, SceneObject scene_object2) inline private
Definition at line 638 of file PluginSceneManager.c.
  {
    scene_object1.UnlinkSceneObject(scene_object2);
    scene_object2.UnlinkSceneObject(scene_object1);
  }
Unsubscribe()
void PluginBase::Unsubscribe (MessageReceiverBase receiver, int index) inline private
Definition at line 114 of file PluginMessageManager.c.
  {
    array<ref MessageReceiverBase> chan = channelList[index];
    int i = chan.Find(receiver);
    if (i >= 0)
      chan.Remove(i);
  }
UnsubscribeAll()
void PluginBase::UnsubscribeAll (MessageReceiverBase receiver) inline private
Definition at line 122 of file PluginMessageManager.c.
  {
    //GetGame().ProfilerStart("UnsubscribeAll");
    for (int i = 0; i <= channelsUsed; i++)
    {
      array<ref MessageReceiverBase> chan = channelList[i];
      int c = chan.Find(receiver);
      if (c >= 0)
        chan.Remove(c);
    }
    //GetGame().ProfilerStop("UnsubscribeAll");
  }
References channelsUsed.
Update()
void PluginBase::Update () inline private
!!!! Highly suspect
Definition at line 142 of file PluginDeveloperSync.c.
  {
    if (!GetDayZGame().IsMultiplayer() || GetDayZGame().IsServer())
    {
      for (int i = 0; i < m_RegisteredPlayers.Count(); i++)
      {
        PlayerBase player = m_RegisteredPlayers.GetKey(i);
        if (!player || !player.IsAlive())
        {
          m_RegisteredPlayers.RemoveElement(i);
          i--;
        }
        else
        {
          int bit_mask = m_RegisteredPlayers.Get(player).m_Bitmask;
          if ((PDS_SYSTEMS.MODS & bit_mask) != 0)
          {
            SendRPCMods(player);
            if (PDS_SYSTEMS.MODS_DETAILED & bit_mask)
              SendRPCModsDetail(player);
          }
          if ((PDS_SYSTEMS.LEVELS & bit_mask) != 0)
            SendRPCLevels(player);
          if ((PDS_SYSTEMS.STATS & bit_mask) != 0)
            SendRPCStats(player);
          if ((PDS_SYSTEMS.STOMACH & bit_mask) != 0)
            SendRPCStomach(player);
          if ((PDS_SYSTEMS.AGENTS & bit_mask) != 0)
            SendRPCAgents(player);
          if ((PDS_SYSTEMS.TEMPERATURE & bit_mask))
            SendRPCTemp(player);
        }
      }
    }
  }
References GetDayZGame(), SendRPCAgents(), SendRPCLevels(), SendRPCMods(), SendRPCModsDetail(), SendRPCStats(), SendRPCStomach(), and SendRPCTemp().
UpdateStatsLocal()
void PluginBase::UpdateStatsLocal () inline private
Definition at line 422 of file PluginDeveloperSync.c.
  {
    PlayerBase player = PlayerBase.Cast(GetDayZGame().GetPlayer());
    //clear values
    m_PlayerStatsSynced.Clear();
    //set values
    for (int i = 0; i < player.m_PlayerStats.GetPCO().Get().Count(); i++)
    {
      string label = player.m_PlayerStats.GetPCO().Get().Get(i).GetLabel();
      float value = player.m_PlayerStats.GetPCO().Get().Get(i).Get();
      float value_norm = player.m_PlayerStats.GetPCO().Get().Get(i).GetNormalized();
      m_PlayerStatsSynced.Insert(new SyncedValue(label, value, false, value_norm));
    }
    m_PlayerStatsSynced.Insert(new SyncedValue("(NaS)Immunity", player.GetImmunity(), false, 0));
    m_PlayerStatsSynced.Insert(new SyncedValue("(NaS) BrokenLegs", player.m_BrokenLegState, false, 0));
  }
References Count, Get(), GetDayZGame(), and GetPlayer().
UpdateStatWidget()
void PluginBase::UpdateStatWidget (int rowIndex, UTemperatureSourceDebug utsd) inline protected
Definition at line 168 of file PluginUniversalTemperatureSourceClient.c.
  {
    m_StatListWidgets[rowIndex].ClearItems();
    m_HeaderWidget[rowIndex].SetText(utsd.GetHeader());
    int numPairs = utsd.PairsCount();
    for (int i = 0; i < numPairs; ++i)
    {
      m_StatListWidgets[rowIndex].AddItem(utsd.GetName(i), null, 0, i);
      m_StatListWidgets[rowIndex].SetItem(i, utsd.GetValue(i), null, 1);
    }
    // manually add value for distance (client only)
    m_StatListWidgets[rowIndex].AddItem("distance", null, 0, numPairs);
    m_StatListWidgets[rowIndex].SetItem(numPairs, vector.Distance(m_Player.GetPosition(), utsd.GetValue(0).ToVector()).ToString(), null, 1);
  }
References vector::Distance(), m_Player, and m_StatListWidgets.
Referenced by UpdateStatWidgets().
UpdateStatWidgets()
void PluginBase::UpdateStatWidgets () inline protected
Definition at line 140 of file PluginUniversalTemperatureSourceClient.c.
  {
    int i = 0;
    int utsDebugCount = m_UTemperatureSourceDebugs.Count();
    for (; i < utsDebugCount && i < MAX_SIMULTANEOUS_UTS; ++i)
    {
      UTemperatureSourceDebug utsd = m_UTemperatureSourceDebugs[i];
      vector pos = utsd.GetValue(0).ToVector();
      vector screen_pos_stats = GetGame().GetScreenPos(pos + "0 0 0");
      vector screen_pos_damage = GetGame().GetScreenPos(pos + "0 2 0");
      m_RootWidget[i].SetPos(screen_pos_stats[0], screen_pos_stats[1]);
      if (screen_pos_stats[2] > 0 && screen_pos_stats[0] > 0 && screen_pos_stats[1] > 0)
      {
        m_RootWidget[i].Show(true);
        UpdateStatWidget(i, utsd);
      }
      else
        m_RootWidget[i].Show(false);
    }
    for (; i < MAX_SIMULTANEOUS_UTS; ++i)
    {
      if (m_RootWidget[i])
        m_RootWidget[i].Show(false);
    }
  }
References GetGame(), m_RootWidget, MAX_SIMULTANEOUS_UTS, and UpdateStatWidget().
Referenced by OnUpdate().
Member Data Documentation
channelList
ref array<ref MessageReceiverBase> PluginBase::channelList[NUM_OF_CHANNELS] private
Definition at line 7 of file PluginMessageManager.c.
channelsUsed
int PluginBase::channelsUsed = 0 private
Definition at line 6 of file PluginMessageManager.c.
Referenced by UnsubscribeAll().
CLICK_TIME
const int PluginBase::CLICK_TIME = 200 protected
Definition at line 273 of file PluginKeyBinding.c.
DOUBLE_CLICK_TIME
const int PluginBase::DOUBLE_CLICK_TIME = 300 protected
Definition at line 274 of file PluginKeyBinding.c.
fadeInVolume
float PluginBase::fadeInVolume = 1.1 private
Definition at line 178 of file PluginSoundDebug.c.
fadeOutVolume
float PluginBase::fadeOutVolume = 0.9 private
Definition at line 179 of file PluginSoundDebug.c.
FOV
const float PluginBase::FOV = 0.5236 private
Definition at line 15 of file PluginCharPlacement.c.
HOLD_CLICK_TIME_MIN
const int PluginBase::HOLD_CLICK_TIME_MIN = 300 protected
Definition at line 275 of file PluginKeyBinding.c.
instance [1/2]
PluginKeyBinding PluginBase::instance static private
Definition at line 16 of file PluginKeyBinding.c.
instance [2/2]
PluginSceneManager PluginBase::instance static private
Definition at line 6 of file PluginSceneManager.c.
INTERVAL
const int PluginBase::INTERVAL = 1 private
Definition at line 8 of file PluginRemotePlayerDebugServer.c.
LOOKUP_RADIUS
const float PluginBase::LOOKUP_RADIUS = 20 private
[s]
Definition at line 4 of file PluginUniversalTemperatureSourceServer.c.
m_AccuTime
float PluginBase::m_AccuTime private
[m]
Definition at line 7 of file PluginRemotePlayerDebugServer.c.
m_ActionsFilter
int PluginBase::m_ActionsFilter protected
Definition at line 23 of file PluginAdminLog.c.
m_AgentList
ref map<int, ref AgentBase> PluginBase::m_AgentList = new map<int, ref AgentBase> static private
Definition at line 10 of file PluginTransmissionAgents.c.
Referenced by GetAgentList().
m_AgentsUpdateStatus
bool PluginBase::m_AgentsUpdateStatus private
Definition at line 42 of file PluginDeveloperSync.c.
m_AttackDescriptors
ref array<ref PluginDayZInfectedDebugAttackDesc> PluginBase::m_AttackDescriptors = new array<ref PluginDayZInfectedDebugAttackDesc> private
Definition at line 96 of file PluginDayZInfectedDebug.c.
m_AttackDirCB
XComboBoxWidget PluginBase::m_AttackDirCB private
Definition at line 80 of file PluginDayZInfectedDebug.c.
m_AttackTypeCB
XComboBoxWidget PluginBase::m_AttackTypeCB private
Definition at line 79 of file PluginDayZInfectedDebug.c.
m_BleedMgr
BleedingSourcesManagerServer PluginBase::m_BleedMgr private
Definition at line 19 of file PluginAdminLog.c.
m_cam_pos
vector PluginBase::m_cam_pos private
Definition at line 7 of file PluginCharPlacement.c.
m_camera_dir
vector PluginBase::m_camera_dir private
Definition at line 9 of file PluginCharPlacement.c.
m_camera_orientation
vector PluginBase::m_camera_orientation private
Definition at line 13 of file PluginCharPlacement.c.
m_cameraTrans
vector PluginBase::m_cameraTrans[4] private
Definition at line 10 of file PluginCharPlacement.c.
m_CardFightButton
ButtonWidget PluginBase::m_CardFightButton private
Definition at line 49 of file PluginDayZInfectedDebug.c.
m_CardFightFrame
Widget PluginBase::m_CardFightFrame private
Definition at line 51 of file PluginDayZInfectedDebug.c.
m_CardMovementButton
ButtonWidget PluginBase::m_CardMovementButton private
Definition at line 48 of file PluginDayZInfectedDebug.c.
m_CardMovementFrame
Widget PluginBase::m_CardMovementFrame private
Definition at line 50 of file PluginDayZInfectedDebug.c.
m_CH_DoAttack
bool PluginBase::m_CH_DoAttack = false private
Definition at line 93 of file PluginDayZInfectedDebug.c.
m_CH_DoHit
bool PluginBase::m_CH_DoHit = false private
Definition at line 91 of file PluginDayZInfectedDebug.c.
m_CH_DoKnucleOut
bool PluginBase::m_CH_DoKnucleOut = false private
Definition at line 89 of file PluginDayZInfectedDebug.c.
m_CH_DoTurn
bool PluginBase::m_CH_DoTurn = false private
command handler values
Definition at line 87 of file PluginDayZInfectedDebug.c.
m_CH_DoVault
bool PluginBase::m_CH_DoVault = false private
Definition at line 88 of file PluginDayZInfectedDebug.c.
m_CH_GoToCrawl
bool PluginBase::m_CH_GoToCrawl = false private
Definition at line 90 of file PluginDayZInfectedDebug.c.
m_CH_StartDeath
bool PluginBase::m_CH_StartDeath = false private
Definition at line 92 of file PluginDayZInfectedDebug.c.
m_Character
PlayerBase PluginBase::m_Character private
Definition at line 4 of file PluginCharPlacement.c.
m_character_pos
vector PluginBase::m_character_pos private
Definition at line 8 of file PluginCharPlacement.c.
m_ClassBrowserSelected
string PluginBase::m_ClassBrowserSelected protected
Definition at line 1051 of file PluginSceneManager.c.
m_ClientList
ref set< PlayerBase > PluginBase::m_ClientList = new set<PlayerBase> private
Definition at line 3 of file PluginRemotePlayerDebugServer.c.
Referenced by SendDebug().
m_ControlledInfected
DayZInfected PluginBase::m_ControlledInfected private
controlled instance
Definition at line 84 of file PluginDayZInfectedDebug.c.
m_CrawlingTypeCB
XComboBoxWidget PluginBase::m_CrawlingTypeCB private
Definition at line 67 of file PluginDayZInfectedDebug.c.
m_CurrentMode
int PluginBase::m_CurrentMode = 0 private
Definition at line 41 of file PluginDayZInfectedDebug.c.
m_DeathTypeCB
XComboBoxWidget PluginBase::m_DeathTypeCB private
Definition at line 76 of file PluginDayZInfectedDebug.c.
m_DebugShapes
ref array<Shape> PluginBase::m_DebugShapes = new array<Shape>() private
Definition at line 98 of file PluginDayZInfectedDebug.c.
m_DebugType
eRemoteDebugType PluginBase::m_DebugType private
Definition at line 10 of file PluginRemotePlayerDebugServer.c.
m_DecayTimer
ref Timer PluginBase::m_DecayTimer private
Definition at line 7 of file PluginObjectsInteractionManager.c.
m_demoPos
vector PluginBase::m_demoPos private
Definition at line 11 of file PluginCharPlacement.c.
m_demoRot
vector PluginBase::m_demoRot private
Definition at line 12 of file PluginCharPlacement.c.
m_DetailedInfoRequested
int PluginBase::m_DetailedInfoRequested = 0 private
Definition at line 27 of file PluginDeveloperSync.c.
m_DisplayName
string PluginBase::m_DisplayName private
Definition at line 9 of file PluginAdminLog.c.
m_Distance
float PluginBase::m_Distance private
Definition at line 11 of file PluginAdminLog.c.
m_DotIndex
int PluginBase::m_DotIndex private
Definition at line 16 of file PluginAdminLog.c.
m_EnvironmentDebugMessage
string PluginBase::m_EnvironmentDebugMessage private
Definition at line 36 of file PluginDeveloperSync.c.
m_FeaturesMask
int PluginBase::m_FeaturesMask protected
Definition at line 5 of file PluginDeveloper.c.
m_FileContent
ref TStringArray PluginBase::m_FileContent private
Definition at line 22 of file PluginFileHandler.c.
m_HasFocus
bool PluginBase::m_HasFocus = false private
Definition at line 42 of file PluginDayZInfectedDebug.c.
m_HeaderWidget
TextWidget PluginBase::m_HeaderWidget[MAX_SIMULTANEOUS_UTS] protected
Definition at line 11 of file PluginUniversalTemperatureSourceClient.c.
m_HitBodyPartCB
XComboBoxWidget PluginBase::m_HitBodyPartCB private
Definition at line 73 of file PluginDayZInfectedDebug.c.
m_HitDirEB
EditBoxWidget PluginBase::m_HitDirEB private
fight card
Definition at line 71 of file PluginDayZInfectedDebug.c.
m_HitFilter
int PluginBase::m_HitFilter protected
Definition at line 21 of file PluginAdminLog.c.
m_HitMessage
string PluginBase::m_HitMessage private
Definition at line 10 of file PluginAdminLog.c.
m_HitTypeCB
XComboBoxWidget PluginBase::m_HitTypeCB private
Definition at line 72 of file PluginDayZInfectedDebug.c.
m_Hud
Hud PluginBase::m_Hud private
Definition at line 3 of file PluginPermanentCrossHair.c.
m_Id
int PluginBase::m_Id private
Definition at line 24 of file PluginVariables.c.
m_Initialized
bool PluginBase::m_Initialized private
Definition at line 6 of file PluginCharPlacement.c.
m_Instance
PluginCameraTools PluginBase::m_Instance static protected
Definition at line 3 of file PluginCameraTools.c.
m_IsActive
bool PluginBase::m_IsActive = false private
Definition at line 43 of file PluginDayZInfectedDebug.c.
Referenced by IsActive(), and IsActive().
m_IsConstructed
bool PluginBase::m_IsConstructed = false private
Definition at line 12 of file PluginTransmissionAgents.c.
m_IsDragging
bool PluginBase::m_IsDragging protected
Definition at line 1046 of file PluginSceneManager.c.
m_IsOpen [1/2]
bool PluginBase::m_IsOpen static protected
Definition at line 4 of file PluginCameraTools.c.
m_IsOpen [2/2]
bool PluginBase::m_IsOpen protected
Definition at line 1052 of file PluginSceneManager.c.
m_IsWinHolding
bool PluginBase::m_IsWinHolding protected
Definition at line 4 of file PluginDeveloper.c.
m_ItemInHands
string PluginBase::m_ItemInHands private
Definition at line 14 of file PluginAdminLog.c.
m_KeyBindings [1/2]
ref array<ref KeyBinding> PluginBase::m_KeyBindings protected
Definition at line 277 of file PluginKeyBinding.c.
m_KeyBindings [2/2]
ref map<int, KeyBinding> PluginBase::m_KeyBindings protected
Definition at line 1048 of file PluginSceneManager.c.
m_KnucleOutButton
ButtonWidget PluginBase::m_KnucleOutButton private
Definition at line 65 of file PluginDayZInfectedDebug.c.
m_LevelsUpdateStatus
bool PluginBase::m_LevelsUpdateStatus private
Definition at line 40 of file PluginDeveloperSync.c.
m_LineLimit
int PluginBase::m_LineLimit private
Definition at line 20 of file PluginFileHandler.c.
m_LockedObjects
ref array<Object> PluginBase::m_LockedObjects private
Definition at line 3 of file PluginObjectsInteractionManager.c.
m_LockedObjectsDecay
ref array<float> PluginBase::m_LockedObjectsDecay private
Definition at line 4 of file PluginObjectsInteractionManager.c.
m_MainWindow
ref Widget PluginBase::m_MainWindow private
Definition at line 5 of file PluginDrawCheckerboard.c.
m_MainWnd
Widget PluginBase::m_MainWnd private
main controls
Definition at line 46 of file PluginDayZInfectedDebug.c.
Referenced by DestroyModuleWidgets(), and DestroyModuleWidgets().
m_Message
string PluginBase::m_Message private
Definition at line 8 of file PluginAdminLog.c.
m_MindStateCB
XComboBoxWidget PluginBase::m_MindStateCB private
Definition at line 56 of file PluginDayZInfectedDebug.c.
m_ModsUpdateStatus
bool PluginBase::m_ModsUpdateStatus private
Definition at line 41 of file PluginDeveloperSync.c.
m_ModuleConfigDebugProfile
PluginConfigDebugProfile PluginBase::m_ModuleConfigDebugProfile protected
Definition at line 1039 of file PluginSceneManager.c.
m_ModuleConfigScene
PluginConfigScene PluginBase::m_ModuleConfigScene protected
Definition at line 1038 of file PluginSceneManager.c.
m_ModuleDeveloper
PluginDeveloper PluginBase::m_ModuleDeveloper private
Definition at line 3 of file PluginCharPlacement.c.
m_MouseBindings
ref array<ref MouseBinding> PluginBase::m_MouseBindings protected
Definition at line 279 of file PluginKeyBinding.c.
m_MouseButtons
ref array<ref MouseButtonInfo> PluginBase::m_MouseButtons protected
Definition at line 278 of file PluginKeyBinding.c.
m_MovementSpeedEB
EditBoxWidget PluginBase::m_MovementSpeedEB private
Definition at line 57 of file PluginDayZInfectedDebug.c.
m_NotifiersIcons
ref multiMap<int, string> PluginBase::m_NotifiersIcons private
Definition at line 6 of file PluginPlayerStatus.c.
m_NotifiersIndexColor
ref multiMap<int, int> PluginBase::m_NotifiersIndexColor private
Definition at line 4 of file PluginPlayerStatus.c.
m_NotifiersLabel
ref multiMap<int, string> PluginBase::m_NotifiersLabel private
Definition at line 3 of file PluginPlayerStatus.c.
m_Pid
string PluginBase::m_Pid private
Definition at line 4 of file PluginAdminLog.c.
m_PlacementFilter
int PluginBase::m_PlacementFilter protected
Definition at line 22 of file PluginAdminLog.c.
m_PlantMaterials
ref map<string, ref PlantMaterialHealth> PluginBase::m_PlantMaterials private
Definition at line 3 of file PluginHorticulture.c.
m_Player
PlayerBase PluginBase::m_Player private
Definition at line 12 of file PluginAdminLog.c.
m_PlayerAgentsSynced
ref array<ref SyncedValueAgent> PluginBase::m_PlayerAgentsSynced private
Definition at line 37 of file PluginDeveloperSync.c.
m_PlayerArray
autoptr array<Man> PluginBase::m_PlayerArray protected
Definition at line 27 of file PluginAdminLog.c.
Referenced by PlayerList().
m_PlayerDebugDamage
ref map<PlayerBase, ref RemotePlayerDamageDebug> PluginBase::m_PlayerDebugDamage = new map<PlayerBase, ref RemotePlayerDamageDebug> private
Definition at line 6 of file PluginRemotePlayerDebugServer.c.
m_PlayerDebugStats
ref array<ref RemotePlayerStatDebug> PluginBase::m_PlayerDebugStats = new array<ref RemotePlayerStatDebug> private
Definition at line 5 of file PluginRemotePlayerDebugServer.c.
m_PlayerLevelsSynced
ref array<ref SyncedValueLevel> PluginBase::m_PlayerLevelsSynced private
Definition at line 33 of file PluginDeveloperSync.c.
m_PlayerListFilter
int PluginBase::m_PlayerListFilter protected
Definition at line 24 of file PluginAdminLog.c.
m_PlayerModsDetailedSynced
string PluginBase::m_PlayerModsDetailedSynced private
Definition at line 35 of file PluginDeveloperSync.c.
m_PlayerModsSynced
ref array<ref SyncedValueModifier> PluginBase::m_PlayerModsSynced private
Definition at line 34 of file PluginDeveloperSync.c.
m_PlayerName
string PluginBase::m_PlayerName private
Definition at line 3 of file PluginAdminLog.c.
m_PlayerPrefix
string PluginBase::m_PlayerPrefix private
Definition at line 6 of file PluginAdminLog.c.
m_PlayerPrefix2
string PluginBase::m_PlayerPrefix2 private
Definition at line 7 of file PluginAdminLog.c.
m_PlayerStatsSynced
ref array<ref SyncedValue> PluginBase::m_PlayerStatsSynced private
Definition at line 31 of file PluginDeveloperSync.c.
m_PlayerStomachSynced
ref array<ref Param> PluginBase::m_PlayerStomachSynced private
Definition at line 32 of file PluginDeveloperSync.c.
m_PosArray
string PluginBase::m_PosArray[3] private
Definition at line 15 of file PluginAdminLog.c.
m_Position
vector PluginBase::m_Position private
Definition at line 5 of file PluginAdminLog.c.
m_PressedMouseID
int PluginBase::m_PressedMouseID protected
Definition at line 1045 of file PluginSceneManager.c.
m_pUIHandler
ref PluginDayZInfectedDebugUIHandler PluginBase::m_pUIHandler private
Definition at line 95 of file PluginDayZInfectedDebug.c.
m_ReadOnly
bool PluginBase::m_ReadOnly private
Definition at line 19 of file PluginFileHandler.c.
m_RegisteredPlayers
ref map<PlayerBase, ref RegisterPlayerData> PluginBase::m_RegisteredPlayers private
Definition at line 29 of file PluginDeveloperSync.c.
m_RootWidget
ref Widget PluginBase::m_RootWidget[MAX_SIMULTANEOUS_UTS] protected
Definition at line 9 of file PluginUniversalTemperatureSourceClient.c.
m_Ruler
ItemBase PluginBase::m_Ruler private
Definition at line 4 of file PluginDoorRuler.c.
m_RulerActivated
bool PluginBase::m_RulerActivated private
Definition at line 8 of file PluginSceneManager.c.
m_RulerLines
ref array<Shape> PluginBase::m_RulerLines private
Definition at line 10 of file PluginSceneManager.c.
m_RulerPoints
ref array<vector> PluginBase::m_RulerPoints private
Definition at line 9 of file PluginSceneManager.c.
m_RulerSpheres
ref array<Shape> PluginBase::m_RulerSpheres private
Definition at line 11 of file PluginSceneManager.c.
m_SceneData
ref SceneData PluginBase::m_SceneData protected
Definition at line 1049 of file PluginSceneManager.c.
m_ScriptConsole
UIScriptedMenu PluginBase::m_ScriptConsole protected
Definition at line 6 of file PluginDeveloper.c.
m_SelectedObject
SceneObject PluginBase::m_SelectedObject protected
Definition at line 1050 of file PluginSceneManager.c.
m_ShapesSceneObjects
ref array<Shape> PluginBase::m_ShapesSceneObjects protected
Definition at line 1047 of file PluginSceneManager.c.
m_SimpleAgentList
ref map<int, string> PluginBase::m_SimpleAgentList = new map<int, string> private
Definition at line 11 of file PluginTransmissionAgents.c.
Referenced by GetSimpleAgentList().
m_soundBuilder
ref SoundObjectBuilder PluginBase::m_soundBuilder private
Definition at line 176 of file PluginSoundDebug.c.
m_soundObject
ref SoundObject PluginBase::m_soundObject private
Definition at line 177 of file PluginSoundDebug.c.
m_soundParams
ref SoundParams PluginBase::m_soundParams private
Definition at line 175 of file PluginSoundDebug.c.
m_Source
PlayerBase PluginBase::m_Source private
Definition at line 13 of file PluginAdminLog.c.
m_SpawnEntityButton
ButtonWidget PluginBase::m_SpawnEntityButton private
Definition at line 47 of file PluginDayZInfectedDebug.c.
m_StanceCB
XComboBoxWidget PluginBase::m_StanceCB private
movement card
Definition at line 55 of file PluginDayZInfectedDebug.c.
m_StartAttackButton
ButtonWidget PluginBase::m_StartAttackButton private
Definition at line 81 of file PluginDayZInfectedDebug.c.
m_StartCrawlingButton
ButtonWidget PluginBase::m_StartCrawlingButton private
Definition at line 68 of file PluginDayZInfectedDebug.c.
m_StartDeathButton
ButtonWidget PluginBase::m_StartDeathButton private
Definition at line 77 of file PluginDayZInfectedDebug.c.
m_StartHitButton
ButtonWidget PluginBase::m_StartHitButton private
Definition at line 74 of file PluginDayZInfectedDebug.c.
m_StartTurnButton
ButtonWidget PluginBase::m_StartTurnButton private
Definition at line 59 of file PluginDayZInfectedDebug.c.
m_StartVaultButton
ButtonWidget PluginBase::m_StartVaultButton private
Definition at line 64 of file PluginDayZInfectedDebug.c.
m_StatEnergy
PlayerStat<float> PluginBase::m_StatEnergy private
Definition at line 18 of file PluginAdminLog.c.
m_StatListWidgets
TextListboxWidget PluginBase::m_StatListWidgets[MAX_SIMULTANEOUS_UTS] protected
Definition at line 10 of file PluginUniversalTemperatureSourceClient.c.
m_StatsUpdateStatus
bool PluginBase::m_StatsUpdateStatus private
Definition at line 39 of file PluginDeveloperSync.c.
m_StatusText
TextWidget PluginBase::m_StatusText private
Definition at line 52 of file PluginDayZInfectedDebug.c.
m_StatWater
PlayerStat<float> PluginBase::m_StatWater private
Definition at line 17 of file PluginAdminLog.c.
m_StomachUpdateStatus
bool PluginBase::m_StomachUpdateStatus private
Definition at line 43 of file PluginDeveloperSync.c.
m_TickTimer
ref Timer PluginBase::m_TickTimer private
status refresh timer
Definition at line 101 of file PluginDayZInfectedDebug.c.
m_TimeLastClickPress
float PluginBase::m_TimeLastClickPress protected
Definition at line 1044 of file PluginSceneManager.c.
m_TimeLastClickRelease
float PluginBase::m_TimeLastClickRelease protected
Definition at line 1043 of file PluginSceneManager.c.
m_Timer
ref Timer PluginBase::m_Timer protected
Definition at line 26 of file PluginAdminLog.c.
m_TurnDirectionEB
EditBoxWidget PluginBase::m_TurnDirectionEB private
Definition at line 61 of file PluginDayZInfectedDebug.c.
m_TurnTypeCB
XComboBoxWidget PluginBase::m_TurnTypeCB private
Definition at line 60 of file PluginDayZInfectedDebug.c.
m_UpdateTimer
ref Timer PluginBase::m_UpdateTimer private
Definition at line 28 of file PluginDeveloperSync.c.
m_UTemperatureSourceDebugs
ref array< ref UTemperatureSourceDebug > PluginBase::m_UTemperatureSourceDebugs protected
Definition at line 7 of file PluginUniversalTemperatureSourceClient.c.
Referenced by DrawDebugs(), PrintedDebug(), and ProcessUniversalTemperatureSources().
m_UTSAverageTemperature
float PluginBase::m_UTSAverageTemperature protected
Definition at line 5 of file PluginUniversalTemperatureSourceClient.c.
m_Variables
ref map<int, string> PluginBase::m_Variables private
Definition at line 25 of file PluginVariables.c.
m_VaultingCB
XComboBoxWidget PluginBase::m_VaultingCB private
Definition at line 63 of file PluginDayZInfectedDebug.c.
m_Watching
bool PluginBase::m_Watching private
Definition at line 11 of file PluginRemotePlayerDebugServer.c.
m_wave
AbstractWave PluginBase::m_wave private
Definition at line 180 of file PluginSoundDebug.c.
MAX_SIMULTANEOUS_UTS
const int PluginBase::MAX_SIMULTANEOUS_UTS = 10 private
Definition at line 3 of file PluginUniversalTemperatureSourceClient.c.
Referenced by EnableWidgets(), InitWidgets(), and UpdateStatWidgets().
PLAYER
PlayerBase PluginBase::PLAYER static private
Definition at line 5 of file PluginSceneManager.c.
SCENE_DEFAULT_NAME
string PluginBase::SCENE_DEFAULT_NAME = "default" static private
Definition at line 3 of file PluginSceneManager.c.
SCENE_EDITOR_CMD_POPUP
const int PluginBase::SCENE_EDITOR_CMD_POPUP = 1 static private
Definition at line 14 of file PluginSceneManager.c.
SCENE_EDITOR_CMD_REFRESH
const int PluginBase::SCENE_EDITOR_CMD_REFRESH = 0 static private
Definition at line 13 of file PluginSceneManager.c.
SCENE_EDITOR_CMD_SAVE
const int PluginBase::SCENE_EDITOR_CMD_SAVE = 2 static private
Definition at line 15 of file PluginSceneManager.c.
SCENE_SUFIX
string PluginBase::SCENE_SUFIX = "scene" static private
Definition at line 4 of file PluginSceneManager.c.
TICK_RATE
const float PluginBase::TICK_RATE = 10 private
Definition at line 6 of file PluginObjectsInteractionManager.c.
Referenced by Decay().
TIME_TO_FORCED_UNLOCK
const float PluginBase::TIME_TO_FORCED_UNLOCK = 60 private
Definition at line 5 of file PluginObjectsInteractionManager.c.
TIMER_PLAYERLIST
const int PluginBase::TIMER_PLAYERLIST = GetPlayerListTimer() protected
Definition at line 28 of file PluginAdminLog.c.
The documentation for this class was generated from the following files:
scripts/4_World/Plugins/PluginBase.c
scripts/4_World/Plugins/PluginBase/PluginAdminLog.c
scripts/4_World/Plugins/PluginBase/PluginCameraTools.c
scripts/4_World/Plugins/PluginBase/PluginDayZInfectedDebug.c
scripts/4_World/Plugins/PluginBase/PluginDeveloper.c
scripts/4_World/Plugins/PluginBase/PluginDeveloper/PluginCharPlacement.c
scripts/4_World/Plugins/PluginBase/PluginDeveloper/PluginDoorRuler.c
scripts/4_World/Plugins/PluginBase/PluginDeveloper/PluginDrawCheckerboard.c
scripts/4_World/Plugins/PluginBase/PluginDeveloper/PluginRemotePlayerDebugServer.c
scripts/4_World/Plugins/PluginBase/PluginDeveloper/PluginUniversalTemperatureSourceClient.c
scripts/4_World/Plugins/PluginBase/PluginDeveloper/PluginUniversalTemperatureSourceServer.c
scripts/4_World/Plugins/PluginBase/PluginDeveloperSync.c
scripts/4_World/Plugins/PluginBase/PluginFileHandler.c
scripts/4_World/Plugins/PluginBase/PluginHorticulture.c
scripts/4_World/Plugins/PluginBase/PluginKeyBinding.c
scripts/4_World/Plugins/PluginBase/PluginMessageManager.c
scripts/4_World/Plugins/PluginBase/PluginObjectsInteractionManager.c
scripts/4_World/Plugins/PluginBase/PluginPermanentCrossHair.c
scripts/4_World/Plugins/PluginBase/PluginPlayerStatus.c
scripts/4_World/Plugins/PluginBase/PluginSceneManager.c
scripts/4_World/Plugins/PluginBase/PluginSoundDebug.c
scripts/4_World/Plugins/PluginBase/PluginTransmissionAgents.c
scripts/4_World/Plugins/PluginBase/PluginVariables.c
scripts/4_World/Plugins/PluginBase/PluginConfigViewer.c
scripts/4_World/Plugins/PluginBase/PluginRepairing.c