DayZ: HandStartAction Class Reference
HandStartAction Class Reference
simple class starting animation action specified by m_action and m_actionType
Private Member Functions
void HandForceSwapingAnimated_Show (Man player=null, HandStateBase parent=null, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
override bool IsWaitingForActionFinish ()
void HandStartHidingAnimated (Man player=null, HandStateBase parent=null, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
override bool IsWaitingForActionFinish ()
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
override bool IsWaitingForActionFinish ()
void HandTakingAnimated_Show (Man player=null, HandStateBase parent=null, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
override bool IsWaitingForActionFinish ()
Private Attributes
ref InventoryLocation m_Src1 = null
ref InventoryLocation m_Src2 = null
ref InventoryLocation m_Dst1 = null
ref InventoryLocation m_Dst2 = null
ref InventoryLocation m_Dst
ref InventoryLocation m_Src
Detailed Description
simple class starting animation action specified by m_action and m_actionType
Definition at line 53 of file HandAnimatedForceSwapping.c.
Member Function Documentation
HandForceSwapingAnimated_Show()
void HandStartAction::HandForceSwapingAnimated_Show (Man player = null, HandStateBase parent = null, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 60 of file HandAnimatedForceSwapping.c.
{ }
HandStartHidingAnimated()
void HandStartAction::HandStartHidingAnimated (Man player = null, HandStateBase parent = null, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 3 of file HandAnimatedMovingToAtt.c.
  { }
HandTakingAnimated_Show()
void HandStartAction::HandTakingAnimated_Show (Man player = null, HandStateBase parent = null, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 9 of file HandAnimatedTakingFromAtt.c.
  {
    m_Src = null;
    m_Dst = null;
  }
References m_Src.
IsWaitingForActionFinish() [1/4]
override bool HandStartAction::IsWaitingForActionFinish () inline private
Definition at line 105 of file HandAnimatedForceSwapping.c.
{ return true; }
IsWaitingForActionFinish() [2/4]
override bool HandStartAction::IsWaitingForActionFinish () inline private
Definition at line 21 of file HandAnimatedMovingToAtt.c.
{ return m_ActionType == -1; }
IsWaitingForActionFinish() [3/4]
override bool HandStartAction::IsWaitingForActionFinish () inline private
Definition at line 73 of file HandAnimatedMovingToAtt.c.
{ return true; }
IsWaitingForActionFinish() [4/4]
override bool HandStartAction::IsWaitingForActionFinish () inline private
Definition at line 59 of file HandAnimatedTakingFromAtt.c.
{ return true; }
OnAbort() [1/4]
override void HandStartAction::OnAbort (HandEventBase e) inline private
Definition at line 87 of file HandAnimatedForceSwapping.c.
  {
    m_Src1 = null;
    m_Src2 = null;
    m_Dst1 = null;
    m_Dst2 = null;
    super.OnAbort(e);
  }
OnAbort() [2/4]
override void HandStartAction::OnAbort (HandEventBase e) inline private
Definition at line 11 of file HandAnimatedMovingToAtt.c.
  {
    super.OnAbort(e);
  }
OnAbort() [3/4]
override void HandStartAction::OnAbort (HandEventBase e) inline private
Definition at line 61 of file HandAnimatedMovingToAtt.c.
  {
    m_Dst = null;
    super.OnAbort(e);
  }
OnAbort() [4/4]
override void HandStartAction::OnAbort (HandEventBase e) inline private
Definition at line 45 of file HandAnimatedTakingFromAtt.c.
  {
    m_Src = null;
    m_Dst = null;
    super.OnAbort(e);
  }
References m_Src.
OnEntry() [1/4]
override void HandStartAction::OnEntry (HandEventBase e) inline private
TODO(kumarjac): THIS IS WHAT IS BEING CALLED FOR SOME REASON!!!!!
Definition at line 62 of file HandAnimatedForceSwapping.c.
  {
    if (m_Src1 && m_Src2 && m_Dst1 && m_Dst2)
    {
      //InventoryLocation dummy;
      //dummy.Copy(m_Dst2);
      //if (GameInventory.CanForceSwapEntitiesEx(m_Src1.GetItem(), m_Dst1, m_Src2.GetItem(), dummy) && dummy == m_Dst2)
      //{
      GameInventory.LocationSwap(m_Src1, m_Src2, m_Dst1, m_Dst2);
      e.m_Player.OnItemInHandsChanged();
      //}
      //else
      //{
      // if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[hndfsm] HandForceSwapingAnimated_Show - not allowed");
      //}
    }
    else
      Error("[hndfsm] HandForceSwappingAnimated_Show is not properly configured!");
    super.OnEntry(e);
  }
References Error(), and GameInventory::LocationSwap().
OnEntry() [2/4]
override void HandStartAction::OnEntry (HandEventBase e) inline private
Definition at line 6 of file HandAnimatedMovingToAtt.c.
  {
    super.OnEntry(e);
  }
OnEntry() [3/4]
override void HandStartAction::OnEntry (HandEventBase e) inline private
Definition at line 30 of file HandAnimatedMovingToAtt.c.
  {
    Man player = e.m_Player;
    if (m_Dst && m_Dst.IsValid())
    {
      EntityAI item = m_Dst.GetItem();
      InventoryLocation src = new InventoryLocation;
      if (item.GetInventory().GetCurrentInventoryLocation(src))
      {
        if (GameInventory.LocationCanMoveEntity(src, m_Dst))
        {
          GameInventory.LocationSyncMoveEntity(src, m_Dst);
          player.OnItemInHandsChanged();
        }
        else
        {
#ifdef DEVELOPER
          if (LogManager.IsInventoryHFSMLogEnable())
            Debug.InventoryHFSMLog("[hndfsm] HandAnimatedMoveToDst_W4T - not allowed");
#endif
        }
      }
      else
        Error("[hndfsm] " + Object.GetDebugName(e.m_Player) + " STS = " + e.m_Player.GetSimulationTimeStamp() + " HandAnimatedMoveToDst_W4T - item " + item + " has no Inventory or Location, inv=" + item.GetInventory());
    }
    else
      Error("[hndfsm] HandAnimatedMoveToDst_W4T - event has no valid m_Dst");
    super.OnEntry(e);
  }
References Error(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), GameInventory::LocationCanMoveEntity(), and GameInventory::LocationSyncMoveEntity().
OnEntry() [4/4]
override void HandStartAction::OnEntry (HandEventBase e) inline private
Definition at line 15 of file HandAnimatedTakingFromAtt.c.
  {
    super.OnEntry(e);
    if (m_Src)
    {
      if (m_Src.IsValid())
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryHFSMLogEnable())
          Debug.InventoryHFSMLog("Action - STS = " + e.m_Player.GetSimulationTimeStamp(), e.ToString(), "n/a", "OnEntry", e.m_Player.ToString());
#endif
        //if (GameInventory.LocationCanMoveEntity(m_Src, m_Dst))
        //{
        GameInventory.LocationSyncMoveEntity(m_Src, m_Dst);
        e.m_Player.OnItemInHandsChanged();
        //}
        //else
        //{
        // if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[hndfsm] HandTakingAnimated_Show - not allowed");
        //}
      }
      else
        Error("[hndfsm] " + Object.GetDebugName(e.m_Player) + " STS = " + e.m_Player.GetSimulationTimeStamp() + " HandTakingAnimated_Show m_Src=invalid, item not in bubble?");
    }
    else
      Error("[hndfsm] HandTakingAnimated_Show, error - m_Src not configured");
  }
References Error(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), GameInventory::LocationSyncMoveEntity(), and m_Src.
OnExit() [1/4]
override void HandStartAction::OnExit (HandEventBase e) inline private
Definition at line 96 of file HandAnimatedForceSwapping.c.
  {
    m_Src1 = null;
    m_Src2 = null;
    m_Dst1 = null;
    m_Dst2 = null;
    super.OnExit(e);
  }
OnExit() [2/4]
override void HandStartAction::OnExit (HandEventBase e) inline private
Definition at line 16 of file HandAnimatedMovingToAtt.c.
  {
    super.OnExit(e);
  }
OnExit() [3/4]
override void HandStartAction::OnExit (HandEventBase e) inline private
Definition at line 67 of file HandAnimatedMovingToAtt.c.
  {
    m_Dst = null;
    super.OnExit(e);
  }
OnExit() [4/4]
override void HandStartAction::OnExit (HandEventBase e) inline private
Definition at line 52 of file HandAnimatedTakingFromAtt.c.
  {
    m_Src = null;
    m_Dst = null;
    super.OnExit(e);
  }
References m_Src.
Member Data Documentation
m_Dst
ref InventoryLocation HandStartAction::m_Dst private
Definition at line 28 of file HandAnimatedMovingToAtt.c.
m_Dst1
ref InventoryLocation HandStartAction::m_Dst1 = null private
Definition at line 57 of file HandAnimatedForceSwapping.c.
m_Dst2
ref InventoryLocation HandStartAction::m_Dst2 = null private
Definition at line 58 of file HandAnimatedForceSwapping.c.
m_Src
ref InventoryLocation HandStartAction::m_Src private
Definition at line 6 of file HandAnimatedTakingFromAtt.c.
m_Src1
ref InventoryLocation HandStartAction::m_Src1 = null private
Definition at line 55 of file HandAnimatedForceSwapping.c.
m_Src2
ref InventoryLocation HandStartAction::m_Src2 = null private
Definition at line 56 of file HandAnimatedForceSwapping.c.
The documentation for this class was generated from the following files:
scripts/3_Game/Systems/Inventory/HandAnimatedForceSwapping.c
scripts/3_Game/Systems/Inventory/HandAnimatedMovingToAtt.c
scripts/3_Game/Systems/Inventory/HandAnimatedTakingFromAtt.c