DayZ: Ammo_40mm_Smoke_ColorBase Class Reference
Ammo_40mm_Smoke_ColorBase Class Reference
Protected Member Functions
void Ammo_40mm_Smoke_ColorBase ()
override void OnVariablesSynchronized ()
void Activate ()
override void EEKilled (Object killer)
special behaviour - do not call super
override void EEDelete (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
override void OnActivatedByItem (notnull ItemBase item)
Protected Attributes
Particle m_ParticleSmoke
float m_ParticleLifetime
int m_ParticleId
bool m_Activated
Detailed Description
Definition at line 239 of file AmmunitionPiles.c.
Constructor & Destructor Documentation
Ammo_40mm_Smoke_ColorBase()
void Ammo_40mm_Smoke_ColorBase::Ammo_40mm_Smoke_ColorBase () inline protected
Definition at line 246 of file AmmunitionPiles.c.
  {
    RegisterNetSyncVariableBool("m_Activated");
  }
Member Function Documentation
Activate()
void Ammo_40mm_Smoke_ColorBase::Activate () inline protected
Definition at line 269 of file AmmunitionPiles.c.
  {
    m_ParticleLifetime = GetGame().ConfigGetFloat(string.Format("CfgMagazines %1 particleLifeTime", GetType()));
    m_Activated = true;
    SetSynchDirty();
    GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(DeleteSafe, m_ParticleLifetime * 1000);
  }
References CALL_CATEGORY_SYSTEM, GetGame(), GetType(), m_Activated, and m_ParticleLifetime.
Referenced by OnActivatedByItem().
CanPutInCargo()
override bool Ammo_40mm_Smoke_ColorBase::CanPutInCargo (EntityAI parent) inline protected
Definition at line 295 of file AmmunitionPiles.c.
  {
    return !m_Activated;
  }
References m_Activated.
EEDelete()
override void Ammo_40mm_Smoke_ColorBase::EEDelete (EntityAI parent) inline protected
Definition at line 285 of file AmmunitionPiles.c.
  {
#ifndef SERVER
    if (m_ParticleSmoke)
      m_ParticleSmoke.Stop();
#endif
    super.EEDelete(parent);
  }
References m_ParticleSmoke, and Particle::Stop().
EEKilled()
override void Ammo_40mm_Smoke_ColorBase::EEKilled (Object killer) inline protected
special behaviour - do not call super
Definition at line 279 of file AmmunitionPiles.c.
  {
    //analytics (behaviour from EntityAI)
    GetGame().GetAnalyticsServer().OnEntityKilled(killer, this);
  }
References GetGame().
OnActivatedByItem()
override void Ammo_40mm_Smoke_ColorBase::OnActivatedByItem (notnull ItemBase item) inline protected
Definition at line 300 of file AmmunitionPiles.c.
  {
    SetHealth("", "", 0.0);
    Activate();
  }
References Activate().
OnVariablesSynchronized()
override void Ammo_40mm_Smoke_ColorBase::OnVariablesSynchronized () inline protected
Definition at line 251 of file AmmunitionPiles.c.
  {
    super.OnVariablesSynchronized();
    if (m_Activated)
    {
#ifndef SERVER
      string particleStrIdentifier = GetGame().ConfigGetTextOut(string.Format("CfgMagazines %1 particleStrIdentifier", GetType()));
      m_ParticleId = ParticleList.GetParticleIDByName(particleStrIdentifier);
      if (m_ParticleId > 0)
      {
        m_ParticleSmoke = ParticleManager.GetInstance().PlayOnObject(m_ParticleId, this);
        m_ParticleSmoke.SetWiggle(7, 0.3);
      }
#endif
    }
  }
References GetGame(), ParticleList::GetParticleIDByName(), GetType(), m_Activated, m_ParticleId, m_ParticleSmoke, ParticleManager(), and Particle::SetWiggle().
Member Data Documentation
m_Activated
bool Ammo_40mm_Smoke_ColorBase::m_Activated protected
Definition at line 244 of file AmmunitionPiles.c.
Referenced by Activate(), CanPutInCargo(), and OnVariablesSynchronized().
m_ParticleId
int Ammo_40mm_Smoke_ColorBase::m_ParticleId protected
Definition at line 243 of file AmmunitionPiles.c.
Referenced by OnVariablesSynchronized().
m_ParticleLifetime
float Ammo_40mm_Smoke_ColorBase::m_ParticleLifetime protected
Definition at line 242 of file AmmunitionPiles.c.
Referenced by Activate().
m_ParticleSmoke
Particle Ammo_40mm_Smoke_ColorBase::m_ParticleSmoke protected
Definition at line 241 of file AmmunitionPiles.c.
Referenced by EEDelete(), and OnVariablesSynchronized().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Magazine/AmmunitionPiles.c