DayZ: DayZProfilesOptions Class Reference
DayZProfilesOptions Class Reference
Private Member Functions
DayZGame m_Game void DayZProfilesOptions ()
void RegisterProfileOption (EDayZProfilesOptions option, string profileOptionName, bool def=true)
void RegisterProfileOptionBool (EDayZProfilesOptions option, string profileOptionName, bool defaultValue=true)
void RegisterProfileOptionInt (EDayZProfilesOptions option, string profileOptionName, int defaultValue=0)
void RegisterProfileOptionFloat (EDayZProfilesOptions option, string profileOptionName, float defaultValue=0.0)
void ResetOptionsBool ()
void ResetOptions ()
void ResetOptionsInt ()
void ResetOptionsFloat ()
void SetProfileOption (EDayZProfilesOptions option, bool value)
void SetProfileOptionBool (EDayZProfilesOptions option, bool value)
void SetProfileOptionInt (EDayZProfilesOptions option, int value)
void SetProfileOptionFloat (EDayZProfilesOptions option, float value)
bool GetProfileOption (EDayZProfilesOptions option)
bool GetProfileOptionBool (EDayZProfilesOptions option)
int GetProfileOptionInt (EDayZProfilesOptions option)
float GetProfileOptionFloat (EDayZProfilesOptions option)
bool GetProfileOptionDefault (EDayZProfilesOptions option)
bool GetProfileOptionDefaultBool (EDayZProfilesOptions option)
int GetProfileOptionDefaultInt (EDayZProfilesOptions option)
float GetProfileOptionDefaultFloat (EDayZProfilesOptions option)
map< EDayZProfilesOptions, ref DayZProfilesOptionBool > GetProfileOptionMap ()
Private Attributes
ref map< EDayZProfilesOptions, ref DayZProfilesOptionBool > m_DayZProfilesOptionsBool
ref map< EDayZProfilesOptions, ref DayZProfilesOptionInt > m_DayZProfilesOptionsInt
ref map< EDayZProfilesOptions, ref DayZProfilesOptionFloat > m_DayZProfilesOptionsFloat
ref map< EDayZProfilesOptions, ref DayZProfilesOption > m_DayZProfilesOptions
Detailed Description
Definition at line 388 of file DayZGame.c.
Constructor & Destructor Documentation
DayZProfilesOptions()
DayZGame m_Game void DayZProfilesOptions::DayZProfilesOptions () inline private
Definition at line 395 of file DayZGame.c.
  {
    m_DayZProfilesOptionsBool = new map<EDayZProfilesOptions, ref DayZProfilesOptionBool>();
    m_DayZProfilesOptionsInt = new map<EDayZProfilesOptions, ref DayZProfilesOptionInt>();
    m_DayZProfilesOptionsFloat = new map<EDayZProfilesOptions, ref DayZProfilesOptionFloat>();
  }
References m_DayZProfilesOptionsBool, m_DayZProfilesOptionsFloat, and m_DayZProfilesOptionsInt.
Member Function Documentation
GetProfileOption()
bool DayZProfilesOptions::GetProfileOption (EDayZProfilesOptions option) inline private
Definition at line 533 of file DayZGame.c.
  {
    if (m_DayZProfilesOptionsBool && m_DayZProfilesOptionsBool.Contains(option))
    {
      DayZProfilesOptionBool po = m_DayZProfilesOptionsBool.Get(option);
      return po.param2;
    }
    return true;
  }
References m_DayZProfilesOptionsBool.
Referenced by GetProfileOptionBool().
GetProfileOptionBool()
bool DayZProfilesOptions::GetProfileOptionBool (EDayZProfilesOptions option) inline private
Definition at line 544 of file DayZGame.c.
  {
    return GetProfileOption(option);
  }
References GetProfileOption().
GetProfileOptionDefault()
bool DayZProfilesOptions::GetProfileOptionDefault (EDayZProfilesOptions option) inline private
Definition at line 571 of file DayZGame.c.
  {
    return GetProfileOptionDefaultBool(option);
  }
References GetProfileOptionDefaultBool().
GetProfileOptionDefaultBool()
bool DayZProfilesOptions::GetProfileOptionDefaultBool (EDayZProfilesOptions option) inline private
Definition at line 576 of file DayZGame.c.
  {
    if (m_DayZProfilesOptionsBool && m_DayZProfilesOptionsBool.Contains(option))
    {
      DayZProfilesOptionBool po = m_DayZProfilesOptionsBool.Get(option);
      return po.param3;
    }
    ErrorEx("Invalid profile option id! Returning 'true'.", ErrorExSeverity.WARNING);
    return true;
  }
References ErrorEx, and m_DayZProfilesOptionsBool.
Referenced by GetProfileOptionDefault().
GetProfileOptionDefaultFloat()
float DayZProfilesOptions::GetProfileOptionDefaultFloat (EDayZProfilesOptions option) inline private
Definition at line 600 of file DayZGame.c.
  {
    if (m_DayZProfilesOptionsFloat && m_DayZProfilesOptionsFloat.Contains(option))
    {
      DayZProfilesOptionFloat po = m_DayZProfilesOptionsFloat.Get(option);
      return po.param3;
    }
    ErrorEx("Invalid profile option id! Returning '0.0'.", ErrorExSeverity.WARNING);
    return 0.0;
  }
References ErrorEx, and m_DayZProfilesOptionsFloat.
GetProfileOptionDefaultInt()
int DayZProfilesOptions::GetProfileOptionDefaultInt (EDayZProfilesOptions option) inline private
Definition at line 588 of file DayZGame.c.
  {
    if (m_DayZProfilesOptionsInt && m_DayZProfilesOptionsInt.Contains(option))
    {
      DayZProfilesOptionInt po = m_DayZProfilesOptionsInt.Get(option);
      return po.param3;
    }
    ErrorEx("Invalid profile option id! Returning '0'.", ErrorExSeverity.WARNING);
    return 0;
  }
References ErrorEx, and m_DayZProfilesOptionsInt.
GetProfileOptionFloat()
float DayZProfilesOptions::GetProfileOptionFloat (EDayZProfilesOptions option) inline private
Definition at line 560 of file DayZGame.c.
  {
    if (m_DayZProfilesOptionsFloat && m_DayZProfilesOptionsFloat.Contains(option))
    {
      DayZProfilesOptionFloat po = m_DayZProfilesOptionsFloat.Get(option);
      return po.param2;
    }
    return 0.0;
  }
References m_DayZProfilesOptionsFloat.
GetProfileOptionInt()
int DayZProfilesOptions::GetProfileOptionInt (EDayZProfilesOptions option) inline private
Definition at line 549 of file DayZGame.c.
  {
    if (m_DayZProfilesOptionsInt && m_DayZProfilesOptionsInt.Contains(option))
    {
      DayZProfilesOptionInt po = m_DayZProfilesOptionsInt.Get(option);
      return po.param2;
    }
    return 0;
  }
References m_DayZProfilesOptionsInt.
GetProfileOptionMap()
map< EDayZProfilesOptions, ref DayZProfilesOptionBool > DayZProfilesOptions::GetProfileOptionMap () inline private
Definition at line 612 of file DayZGame.c.
  {
    if (m_DayZProfilesOptions)
      return m_DayZProfilesOptions;
    return null;
  }
References m_DayZProfilesOptions.
RegisterProfileOption()
void DayZProfilesOptions::RegisterProfileOption (EDayZProfilesOptions option, string profileOptionName, bool def = true) inline private
init of DayZProfilesOption - profileOptionName, value from Profiles files, or use default value
Definition at line 402 of file DayZGame.c.
  {
    if (!m_DayZProfilesOptionsBool.Contains(option))
    {
      bool profileVal = GetProfileValueBool(profileOptionName, def);
      m_DayZProfilesOptionsBool.Set(option, new DayZProfilesOptionBool(profileOptionName, profileVal, def));
      SetProfileOptionBool(option, profileVal);
    }
  }
References GetProfileValueBool(), m_DayZProfilesOptionsBool, and SetProfileOptionBool().
Referenced by RegisterProfileOptionBool().
RegisterProfileOptionBool()
void DayZProfilesOptions::RegisterProfileOptionBool (EDayZProfilesOptions option, string profileOptionName, bool defaultValue = true) inline private
Definition at line 414 of file DayZGame.c.
  {
    RegisterProfileOption(option, profileOptionName, defaultValue);
  }
References RegisterProfileOption().
RegisterProfileOptionFloat()
void DayZProfilesOptions::RegisterProfileOptionFloat (EDayZProfilesOptions option, string profileOptionName, float defaultValue = 0.0) inline private
init of DayZProfilesOption - profileOptionName, value from Profiles files, or use default value
Definition at line 433 of file DayZGame.c.
  {
    if (!m_DayZProfilesOptionsFloat.Contains(option))
    {
      string outValue;
      GetGame().GetProfileString(profileOptionName, outValue);
      float value = outValue.ToFloat();
      m_DayZProfilesOptionsFloat.Set(option, new DayZProfilesOptionFloat(profileOptionName, value, defaultValue));
      SetProfileOptionFloat(option, value);
    }
  }
References GetGame(), m_DayZProfilesOptionsFloat, and SetProfileOptionFloat().
RegisterProfileOptionInt()
void DayZProfilesOptions::RegisterProfileOptionInt (EDayZProfilesOptions option, string profileOptionName, int defaultValue = 0) inline private
init of DayZProfilesOption - profileOptionName, value from Profiles files, or use default value
Definition at line 419 of file DayZGame.c.
  {
    if (!m_DayZProfilesOptionsInt.Contains(option))
    {
      string outValue;
      GetGame().GetProfileString(profileOptionName, outValue);
      int value = outValue.ToInt();
      m_DayZProfilesOptionsInt.Set(option, new DayZProfilesOptionInt(profileOptionName, value, defaultValue));
      SetProfileOptionInt(option, value);
    }
  }
References GetGame(), m_DayZProfilesOptionsInt, and SetProfileOptionInt().
ResetOptions()
void DayZProfilesOptions::ResetOptions () inline private
Definition at line 459 of file DayZGame.c.
  {
    ResetOptionsBool();
  }
References ResetOptionsBool().
ResetOptionsBool()
void DayZProfilesOptions::ResetOptionsBool () inline private
Definition at line 447 of file DayZGame.c.
  {
    if (!m_DayZProfilesOptionsBool)
      m_DayZProfilesOptionsBool = new map<EDayZProfilesOptions, ref DayZProfilesOptionBool>();
    foreach (EDayZProfilesOptions e_opt, DayZProfilesOptionBool r_opt : m_DayZProfilesOptionsBool)
    {
      bool profileVal = GetProfileValueBool(r_opt.param1, r_opt.param3);
      SetProfileOptionBool(e_opt, profileVal);
    }
  }
References GetProfileValueBool(), m_DayZProfilesOptionsBool, and SetProfileOptionBool().
Referenced by ResetOptions().
ResetOptionsFloat()
void DayZProfilesOptions::ResetOptionsFloat () inline private
Definition at line 478 of file DayZGame.c.
  {
    if (!m_DayZProfilesOptionsFloat)
      m_DayZProfilesOptionsFloat = new map<EDayZProfilesOptions, ref DayZProfilesOptionFloat>();
    foreach (EDayZProfilesOptions e_opt, DayZProfilesOptionFloat r_opt : m_DayZProfilesOptionsFloat)
    {
      string outValue;
      GetGame().GetProfileString(r_opt.param1, outValue);
      float value = outValue.ToFloat();
      SetProfileOptionFloat(e_opt, value);
    }
  }
References GetGame(), m_DayZProfilesOptionsFloat, and SetProfileOptionFloat().
ResetOptionsInt()
void DayZProfilesOptions::ResetOptionsInt () inline private
Definition at line 464 of file DayZGame.c.
  {
    if (!m_DayZProfilesOptionsInt)
      m_DayZProfilesOptionsInt = new map<EDayZProfilesOptions, ref DayZProfilesOptionInt>();
    foreach (EDayZProfilesOptions e_opt, DayZProfilesOptionInt r_opt : m_DayZProfilesOptionsInt)
    {
      string outValue;
      GetGame().GetProfileString(r_opt.param1, outValue);
      int value = outValue.ToInt();
      SetProfileOptionInt(e_opt, value);
    }
  }
References GetGame(), m_DayZProfilesOptionsInt, and SetProfileOptionInt().
SetProfileOption()
void DayZProfilesOptions::SetProfileOption (EDayZProfilesOptions option, bool value) inline private
Definition at line 492 of file DayZGame.c.
  {
    if (m_DayZProfilesOptionsBool && m_DayZProfilesOptionsBool.Contains(option))
    {
      DayZProfilesOptionBool po = m_DayZProfilesOptionsBool.Get(option);
      po.param2 = value;
      GetGame().SetProfileString(po.param1, value.ToString());
      GetGame().SaveProfile();
    }
  }
References GetGame(), and m_DayZProfilesOptionsBool.
Referenced by SetProfileOptionBool().
SetProfileOptionBool()
void DayZProfilesOptions::SetProfileOptionBool (EDayZProfilesOptions option, bool value) inline private
Definition at line 504 of file DayZGame.c.
  {
    SetProfileOption(option, value);
  }
References SetProfileOption().
Referenced by RegisterProfileOption(), and ResetOptionsBool().
SetProfileOptionFloat()
void DayZProfilesOptions::SetProfileOptionFloat (EDayZProfilesOptions option, float value) inline private
Definition at line 521 of file DayZGame.c.
  {
    if (m_DayZProfilesOptionsFloat && m_DayZProfilesOptionsFloat.Contains(option))
    {
      DayZProfilesOptionFloat po = m_DayZProfilesOptionsFloat.Get(option);
      po.param2 = value;
      GetGame().SetProfileString(po.param1, value.ToString());
      GetGame().SaveProfile();
    }
  }
References GetGame(), and m_DayZProfilesOptionsFloat.
Referenced by RegisterProfileOptionFloat(), and ResetOptionsFloat().
SetProfileOptionInt()
void DayZProfilesOptions::SetProfileOptionInt (EDayZProfilesOptions option, int value) inline private
Definition at line 509 of file DayZGame.c.
  {
    if (m_DayZProfilesOptionsInt && m_DayZProfilesOptionsInt.Contains(option))
    {
      DayZProfilesOptionInt po = m_DayZProfilesOptionsInt.Get(option);
      po.param2 = value;
      GetGame().SetProfileString(po.param1, value.ToString());
      GetGame().SaveProfile();
    }
  }
References GetGame(), and m_DayZProfilesOptionsInt.
Referenced by RegisterProfileOptionInt(), and ResetOptionsInt().
Member Data Documentation
m_DayZProfilesOptions
ref map<EDayZProfilesOptions, ref DayZProfilesOption> DayZProfilesOptions::m_DayZProfilesOptions private
DEPRECATED
Definition at line 622 of file DayZGame.c.
Referenced by GetProfileOptionMap().
m_DayZProfilesOptionsBool
ref map<EDayZProfilesOptions, ref DayZProfilesOptionBool> DayZProfilesOptions::m_DayZProfilesOptionsBool private
Definition at line 390 of file DayZGame.c.
Referenced by DayZProfilesOptions(), GetProfileOption(), GetProfileOptionDefaultBool(), RegisterProfileOption(), ResetOptionsBool(), and SetProfileOption().
m_DayZProfilesOptionsFloat
ref map<EDayZProfilesOptions, ref DayZProfilesOptionFloat> DayZProfilesOptions::m_DayZProfilesOptionsFloat private
Definition at line 392 of file DayZGame.c.
Referenced by DayZProfilesOptions(), GetProfileOptionDefaultFloat(), GetProfileOptionFloat(), RegisterProfileOptionFloat(), ResetOptionsFloat(), and SetProfileOptionFloat().
m_DayZProfilesOptionsInt
ref map<EDayZProfilesOptions, ref DayZProfilesOptionInt> DayZProfilesOptions::m_DayZProfilesOptionsInt private
Definition at line 391 of file DayZGame.c.
Referenced by DayZProfilesOptions(), GetProfileOptionDefaultInt(), GetProfileOptionInt(), RegisterProfileOptionInt(), ResetOptionsInt(), and SetProfileOptionInt().
The documentation for this class was generated from the following file:
scripts/3_Game/DayZGame.c