DayZ: AttachmentCategoriesSlotsContainer Class Reference
AttachmentCategoriesSlotsContainer Class Reference
Private Member Functions
void AttachmentCategoriesSlotsContainer (LayoutHolder parent, int index)
override bool IsDisplayable ()
override void SetLayoutName ()
SlotsContainer GetSlotsContainer ()
override EntityAI GetFocusedItem ()
int GetParentID ()
int GetFocusedID ()
void ExpandCollapseContainer (bool expand)
override bool SelectItem ()
override bool Select ()
override bool Combine ()
override bool TransferItemToVicinity ()
override bool TransferItem ()
override bool SplitItem ()
override bool EquipItem ()
override bool CanCombine ()
override bool CanCombineAmmo ()
override bool IsEmpty ()
override bool IsItemActive ()
override bool IsItemWithQuantityActive ()
string GetAttachmentCategory (string config_path_attachment_categories, int i)
string GetIconName (string config_path_attachment_categories, string attachment_category)
Private Member Functions inherited from Container
void CargoContainer (LayoutHolder parent, bool is_attachment=false)
void ~CargoContainer ()
int GetCargoIndex ()
void AddedToCargoEx (EntityAI item, bool refresh=true)
void AddedToCargo (EntityAI item)
void RemovedFromCargo (EntityAI item)
void MovedInCargo (EntityAI item)
void SetLock (EntityAI item)
void ReleaseLock (EntityAI item)
override void SetLayoutName ()
void SetEntity (EntityAI item, int cargo_index=0, bool immedUpdate=true)
EntityAI GetEntity ()
void UpdateHeaderText ()
void InitGridHeight ()
void UpdateSize ()
float GetIconSize ()
float GetSpaceSize ()
int GetCargoCapacity ()
int GetMaxCargoCapacity ()
Icon GetIcon (EntityAI item)
Icon GetIcon (int index)
Icon GetFocusedIcon ()
override float GetFocusedContainerHeight (bool contents=false)
override float GetFocusedContainerYPos (bool contents=false)
override float GetFocusedContainerYScreenPos (bool contents=false)
void UpdateSelection ()
void UpdateRowVisibility (int count)
override void Refresh ()
void RefreshImpl ()
override void UpdateInterval ()
Icon InitIconEx (Icon icon, EntityAI item, int pos_x, int pos_y, bool refresh=true)
Icon InitIcon (Icon icon, EntityAI item, int pos_x, int pos_y)
bool HasItem (EntityAI item)
override bool TransferItemToVicinity ()
override void SetDefaultFocus (bool while_micromanagment_mode=false)
override void SetLastFocus ()
override void Unfocus ()
override void UnfocusAll ()
override void SetNextActive ()
override void SetPreviousActive (bool force=false)
override void SetNextRightActive ()
override void SetNextLeftActive ()
override EntityAI GetFocusedItem ()
override void SetLastActive ()
override void SetActive (bool active)
override bool IsItemActive ()
override bool IsItemWithQuantityActive ()
override bool IsEmpty ()
int GetRecipeCount (bool recipe_anywhere, ItemBase entity1, ItemBase entity2, PlayerBase player)
override bool CanCombineAmmo ()
override bool TransferItem ()
override bool SplitItem ()
override bool EquipItem ()
override bool SelectItem ()
override bool Select ()
override bool Combine ()
void ShowFalseCargoHeader (bool show)
void SetAlternateFalseTextHeaderWidget (TextWidget w)
void ClosableContainer (LayoutHolder parent, int sort=-1)
override bool IsDisplayable ()
override void UpdateRadialIcon ()
void SetOpenState (bool state)
override Header GetHeader ()
override void Open ()
override void Close ()
override void SetLayoutName ()
override void OnShow ()
override LayoutHolder Get (int x)
override void Refresh ()
void CloseButtonOnMouseButtonDown ()
override float GetFocusedContainerHeight (bool contents=false)
override float GetFocusedContainerYPos (bool contents=false)
override float GetFocusedContainerYScreenPos (bool contents=false)
void MoveContainerUp (Widget cont)
void MoveContainerDown (Widget cont)
override void CheckHeaderDragability ()
Private Attributes
ref SlotsContainer m_ItemsCont
Private Attributes inherited from Container
const int ROWS_NUMBER_XBOX = 5
CargoBase m_Cargo
int m_CargoIndex = -1
int m_FocusedItemPosition = -1
ref array< ref CargoContainerRow > m_Rows
ref array< ref Icon > m_Icons
ref map< EntityAI, ref Param3< ref Icon, int, int > > m_ShowedItemPositions
ref map< EntityAI, ref Param3< ref Icon, int, int > > m_ShowedLockPositions
float m_IconSize
float m_SpaceSize
bool m_IsAttachment
TextWidget m_FalseHeaderTextWidget
TextWidget m_AlternateFalseHeaderTextWidget
Widget m_CargoHeader
Widget m_CargoContainer
Widget m_ItemsContainer
ref SizeToChild m_Resizer1
ref SizeToChild m_Resizer2
ref Timer m_ResizeTimer
ref ClosableHeader m_ClosableHeader
bool m_LockCargo
Detailed Description
Definition at line 1 of file AttachmentCategoriesSlotsContainer.c.
Constructor & Destructor Documentation
AttachmentCategoriesSlotsContainer()
void AttachmentCategoriesSlotsContainer::AttachmentCategoriesSlotsContainer (LayoutHolder parent, int index) inline private
Definition at line 5 of file AttachmentCategoriesSlotsContainer.c.
  {
    m_ItemsCont = new SlotsContainer(this, null);
    m_Body.Insert(m_ItemsCont);
    m_ItemsCont.GetMainWidget().SetUserID(index);
    for (int k = 0; k < ITEMS_IN_ROW; k++)
    {
      //WidgetEventHandler.GetInstance().RegisterOnDropReceived( m_ItemsCont.GetSlotIcon( k ).GetMainWidget(),  m_Parent, "OnDropReceivedFromHeader" );
      //WidgetEventHandler.GetInstance().RegisterOnDropReceived(  m_ItemsCont.GetSlotIcon( k ).GetPanelWidget(),  m_Parent, "OnDropReceivedFromHeader" );
      WidgetEventHandler.GetInstance().RegisterOnDraggingOver(m_ItemsCont.GetSlotIcon(k).GetMainWidget(), m_Parent, "DraggingOverHeader");
      WidgetEventHandler.GetInstance().RegisterOnDraggingOver(m_ItemsCont.GetSlotIcon(k).GetPanelWidget(), m_Parent, "DraggingOverHeader");
      WidgetEventHandler.GetInstance().RegisterOnMouseButtonDown(m_ItemsCont.GetSlotIcon(k).GetMainWidget(), m_Parent, "MouseClick");
      WidgetEventHandler.GetInstance().RegisterOnMouseButtonDown(m_ItemsCont.GetSlotIcon(k).GetPanelWidget(), m_Parent, "MouseClick");
      WidgetEventHandler.GetInstance().RegisterOnMouseEnter(m_ItemsCont.GetSlotIcon(k).GetMainWidget(), m_ItemsCont.GetSlotIcon(k), "MouseEnterGhostSlot");
      WidgetEventHandler.GetInstance().RegisterOnMouseLeave(m_ItemsCont.GetSlotIcon(k).GetMainWidget(), m_ItemsCont.GetSlotIcon(k), "MouseLeaveGhostSlot");
      m_ItemsCont.GetSlotIcon(k).GetMainWidget().SetUserID(k);
      m_ItemsCont.GetSlotIcon(k).GetPanelWidget().SetUserID(k);
    }
  }
References WidgetEventHandler::GetInstance(), ITEMS_IN_ROW, m_ItemsCont, and m_Parent.
Member Function Documentation
CanCombine()
override bool AttachmentCategoriesSlotsContainer::CanCombine () inline private
Definition at line 107 of file AttachmentCategoriesSlotsContainer.c.
  {
    return false;
  }
CanCombineAmmo()
override bool AttachmentCategoriesSlotsContainer::CanCombineAmmo () inline private
Definition at line 112 of file AttachmentCategoriesSlotsContainer.c.
  {
    return false;
  }
Combine()
override bool AttachmentCategoriesSlotsContainer::Combine () inline private
Definition at line 82 of file AttachmentCategoriesSlotsContainer.c.
  {
    return false;
  }
EquipItem()
override bool AttachmentCategoriesSlotsContainer::EquipItem () inline private
Definition at line 102 of file AttachmentCategoriesSlotsContainer.c.
  {
    return false;
  }
ExpandCollapseContainer()
void AttachmentCategoriesSlotsContainer::ExpandCollapseContainer (bool expand) inline private
Definition at line 66 of file AttachmentCategoriesSlotsContainer.c.
  {
    m_ItemsCont.GetFocusedSlotsIcon().GetRadialIcon().Show(expand);
    m_ItemsCont.GetFocusedSlotsIcon().GetRadialIconClosed().Show(!expand);
  }
References m_ItemsCont.
GetAttachmentCategory()
string AttachmentCategoriesSlotsContainer::GetAttachmentCategory (string config_path_attachment_categories, int i) inline private
Definition at line 132 of file AttachmentCategoriesSlotsContainer.c.
  {
    string attachment_category;
    GetGame().ConfigGetChildName(config_path_attachment_categories, i, attachment_category);
    return attachment_category;
  }
References GetGame().
GetFocusedID()
int AttachmentCategoriesSlotsContainer::GetFocusedID () inline private
Definition at line 61 of file AttachmentCategoriesSlotsContainer.c.
  {
    return m_ItemsCont.GetFocusedSlotsIcon().GetMainWidget().GetUserID();
  }
References m_ItemsCont.
GetFocusedItem()
override EntityAI AttachmentCategoriesSlotsContainer::GetFocusedItem () inline private
Definition at line 51 of file AttachmentCategoriesSlotsContainer.c.
  {
    return m_ItemsCont.GetFocusedSlotsIcon().GetRender().GetItem();
  }
References m_ItemsCont.
GetIconName()
string AttachmentCategoriesSlotsContainer::GetIconName (string config_path_attachment_categories, string attachment_category) inline private
Definition at line 139 of file AttachmentCategoriesSlotsContainer.c.
  {
    string icon_path = config_path_attachment_categories + " " + attachment_category + " icon";
    string icon_name;
    GetGame().ConfigGetText(icon_path, icon_name);
    return icon_name;
  }
References GetGame().
GetParentID()
int AttachmentCategoriesSlotsContainer::GetParentID () inline private
Definition at line 56 of file AttachmentCategoriesSlotsContainer.c.
  {
    return m_ItemsCont.GetMainWidget().GetUserID();
  }
References m_ItemsCont.
GetSlotsContainer()
SlotsContainer AttachmentCategoriesSlotsContainer::GetSlotsContainer () inline private
Definition at line 46 of file AttachmentCategoriesSlotsContainer.c.
  {
    return m_ItemsCont;
  }
References m_ItemsCont.
IsDisplayable()
override bool AttachmentCategoriesSlotsContainer::IsDisplayable () inline private
Definition at line 30 of file AttachmentCategoriesSlotsContainer.c.
  {
    for (int i = 0; i < m_Body.Count(); i++)
    {
      LayoutHolder c = m_Body[i];
      if (c && c.IsDisplayable())
        return true;
    }
    return false;
  }
IsEmpty()
override bool AttachmentCategoriesSlotsContainer::IsEmpty () inline private
Definition at line 117 of file AttachmentCategoriesSlotsContainer.c.
  {
    return false;
  }
IsItemActive()
override bool AttachmentCategoriesSlotsContainer::IsItemActive () inline private
Definition at line 122 of file AttachmentCategoriesSlotsContainer.c.
  {
    return false;
  }
IsItemWithQuantityActive()
override bool AttachmentCategoriesSlotsContainer::IsItemWithQuantityActive () inline private
Definition at line 127 of file AttachmentCategoriesSlotsContainer.c.
  {
    return false;
  }
Select()
override bool AttachmentCategoriesSlotsContainer::Select () inline private
Definition at line 77 of file AttachmentCategoriesSlotsContainer.c.
  {
    return false;
  }
SelectItem()
override bool AttachmentCategoriesSlotsContainer::SelectItem () inline private
Definition at line 72 of file AttachmentCategoriesSlotsContainer.c.
  {
    return false;
  }
SetLayoutName()
override void AttachmentCategoriesSlotsContainer::SetLayoutName () inline private
Definition at line 41 of file AttachmentCategoriesSlotsContainer.c.
  {
    m_LayoutName = WidgetLayoutName.Container;
  }
References WidgetLayoutName::Container.
SplitItem()
override bool AttachmentCategoriesSlotsContainer::SplitItem () inline private
Definition at line 97 of file AttachmentCategoriesSlotsContainer.c.
  {
    return false;
  }
TransferItem()
override bool AttachmentCategoriesSlotsContainer::TransferItem () inline private
Definition at line 92 of file AttachmentCategoriesSlotsContainer.c.
  {
    return false;
  }
TransferItemToVicinity()
override bool AttachmentCategoriesSlotsContainer::TransferItemToVicinity () inline private
Definition at line 87 of file AttachmentCategoriesSlotsContainer.c.
  {
    return false;
  }
Member Data Documentation
m_ItemsCont
ref SlotsContainer AttachmentCategoriesSlotsContainer::m_ItemsCont private
Definition at line 3 of file AttachmentCategoriesSlotsContainer.c.
Referenced by AttachmentCategoriesSlotsContainer(), ExpandCollapseContainer(), GetFocusedID(), GetFocusedItem(), GetParentID(), and GetSlotsContainer().
The documentation for this class was generated from the following file:
scripts/5_Mission/GUI/InventoryNew/Inherited/AttachmentCategoriesSlotsContainer.c