DayZ: ActionSingleUseBaseCB Class Reference
ActionSingleUseBaseCB Class Reference
Private Member Functions
override void CreateActionComponent ()
override void OnAnimationEvent (int pEventID)
override void InitActionComponent ()
override void EndActionComponent ()
Private Member Functions inherited from ActionBaseCB
void ActionBaseCB ()
int GetPossileStanceMask ()
override void OnFinish (bool pCanceled)
void SetCommand (int command_uid)
void CreateActionComponent ()
void InitActionComponent ()
void ProgressActionComponent ()
void EndActionComponent ()
void Interrupt ()
void SetActionData (ActionData action_data)
override bool IsUserActionCallback ()
float GetActionComponentProgress ()
int GetActionState ()
ActionTarget GetTarget ()
Additional Inherited Members
Private Attributes inherited from ActionBaseCB
ActionData m_ActionData
SoundOnVehicle m_SoundObject
bool m_Canceled
bool m_Interrupted
Detailed Description
Definition at line 1 of file ActionSingleUseBase.c.
Member Function Documentation
CreateActionComponent()
override void ActionSingleUseBaseCB::CreateActionComponent () inline private
Definition at line 3 of file ActionSingleUseBase.c.
  {
    m_ActionData.m_ActionComponent = new CASingleUse;
  }
References ActionData::m_ActionComponent, and ActionBaseCB::m_ActionData.
Referenced by InitActionComponent().
EndActionComponent()
override void ActionSingleUseBaseCB::EndActionComponent () inline private
Definition at line 33 of file ActionSingleUseBase.c.
  {
    m_ActionData.m_State = UA_FINISHED;
  }
References ActionBaseCB::m_ActionData, ActionData::m_State, and UA_FINISHED.
InitActionComponent()
override void ActionSingleUseBaseCB::InitActionComponent () inline private
Definition at line 20 of file ActionSingleUseBase.c.
  {
    m_Interrupted = false;
    m_Canceled = false;
    CreateActionComponent();
    if (m_ActionData.m_ActionComponent)
      m_ActionData.m_ActionComponent.Init(m_ActionData);
    m_ActionData.m_State = UA_PROCESSING;
    RegisterAnimationEvent("ActionExec", UA_ANIM_EVENT);
    m_SoundObject = m_ActionData.m_Action.PlayActionSound(m_ActionData.m_Player);
  }
References CreateActionComponent(), ActionData::m_Action, ActionData::m_ActionComponent, ActionBaseCB::m_ActionData, ActionBaseCB::m_Canceled, ActionBaseCB::m_Interrupted, ActionData::m_Player, ActionBaseCB::m_SoundObject, ActionData::m_State, RegisterAnimationEvent(), UA_ANIM_EVENT, and UA_PROCESSING.
OnAnimationEvent()
override void ActionSingleUseBaseCB::OnAnimationEvent (int pEventID) inline private
Definition at line 8 of file ActionSingleUseBase.c.
  {
    if (m_ActionData)
    {
      if (!m_Interrupted && pEventID == UA_ANIM_EVENT && m_ActionData.m_Action)
      {
        AnimatedActionBase action = AnimatedActionBase.Cast(m_ActionData.m_Action);
        action.OnAnimationEvent(m_ActionData);
      }
    }
  }
References ActionData::m_Action, ActionBaseCB::m_ActionData, ActionBaseCB::m_Interrupted, and UA_ANIM_EVENT.
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/ActionSingleUseBase.c