DayZ: Anniversary_FireworksLauncher Class Reference
Anniversary_FireworksLauncher Class Reference
Protected Member Functions
void SetupColorSequences ()
FireworksLauncherClientEventBase SpawnEvent ()
override bool IsTakeable ()
override bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination)
override bool DisableVicinityIcon ()
int GetMaxShots ()
float GetFuseDelay ()
void OnEventServer (int type)
Called periodically but only after the entity gets ignited.
Private Attributes
int sequence = 0
Additional Inherited Members
Private Member Functions inherited from FireworksLauncher
bool UsesGlobalDeploy ()
override bool IsDeployable ()
override float GetDeployTime ()
how long it takes to deploy this item in seconds
void SetupColorSequences ()
string GetColorSequence ()
void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
float GetMaxAllowedWetness ()
float GetEventDelay ()
string GetFuseSoundSet ()
int GetMaxShots ()
float GetFuseDelay ()
string GetAmmoType ()
int GetDamageType ()
void OnStateChangedServer (EFireworksState currentState)
void OnStateChangedClient (EFireworksState currentState)
override void OnIgnitedThis (EntityAI fire_source)
Executed on Server when some item ignited this one.
bool CanPutInCargo (EntityAI parent)
bool CanPutIntoHands (EntityAI parent)
void OnFuseIgnitedServer ()
void OnFuseIgnitedClient ()
void OnFiringStartServer ()
void OnFiringStartClient ()
void OnFiringStop ()
void RestartEventTimer ()
Starts event timer.
bool IsIgnited ()
bool CanIgniteItem (EntityAI ignite_target=NULL)
void OnEventServer (int type)
Called periodically but only after the entity gets ignited.
void OnIndexChangedClient ()
FireworksLauncherClientEventBase SpawnEvent ()
void OnVariablesSynchronized ()
void OnStoreSave (ParamsWriteContext ctx)
bool OnStoreLoad (ParamsReadContext ctx, int version)
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
Detailed Description
Definition at line 98 of file FireworksLauncherAnniversary.c.
Member Function Documentation
CanSwapEntities()
override bool Anniversary_FireworksLauncher::CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination) inline protected
Definition at line 119 of file FireworksLauncherAnniversary.c.
  {
    return false;
  }
DisableVicinityIcon()
override bool Anniversary_FireworksLauncher::DisableVicinityIcon () inline protected
Definition at line 124 of file FireworksLauncherAnniversary.c.
  {
    return true;
  }
GetFuseDelay()
float Anniversary_FireworksLauncher::GetFuseDelay () inline protected
Definition at line 134 of file FireworksLauncherAnniversary.c.
  {
    return 1;
  }
GetMaxShots()
int Anniversary_FireworksLauncher::GetMaxShots () inline protected
Definition at line 129 of file FireworksLauncherAnniversary.c.
  {
    return 25;
  }
Referenced by OnEventServer().
IsTakeable()
override bool Anniversary_FireworksLauncher::IsTakeable () inline protected
Definition at line 114 of file FireworksLauncherAnniversary.c.
  {
    return false;
  }
OnEventServer()
void Anniversary_FireworksLauncher::OnEventServer (int type) inline protected
Called periodically but only after the entity gets ignited.
Definition at line 140 of file FireworksLauncherAnniversary.c.
  {
    m_Index++;
    DamageSystem.ExplosionDamage(this, NULL, GetAmmoType(), GetPosition(), GetDamageType());
    if (m_Index > 16)
    {
      sequence++;
      m_Index = 1;
    }
    SetSynchDirty();
    if (m_Index + (sequence * 16) > GetMaxShots())
    {
      m_Index = GetMaxShots();
      m_TimerEvent = null;
      SetState(EFireworksState.FINISHED);
    }
    else
      RestartEventTimer();
  }
References FireworksLauncher::GetAmmoType(), FireworksLauncher::GetDamageType(), GetMaxShots(), GetPosition, FireworksLauncher::m_Index, m_TimerEvent, FireworksLauncher::RestartEventTimer(), sequence, and SetState().
SetupColorSequences()
void Anniversary_FireworksLauncher::SetupColorSequences () inline protected
Definition at line 102 of file FireworksLauncherAnniversary.c.
  {
    m_ColorSequence.Insert("1234512345123451234512345");
  }
References FireworksLauncher::m_ColorSequence.
SpawnEvent()
FireworksLauncherClientEventBase Anniversary_FireworksLauncher::SpawnEvent () inline protected
Definition at line 107 of file FireworksLauncherAnniversary.c.
  {
    FireworksLauncherClientEventBase evnt = new AnniversaryFireworksLauncherClientEvent(this, m_Index);
    evnt.OnFired();
    return evnt;
  }
References FireworksLauncher::m_Index.
Member Data Documentation
sequence
int Anniversary_FireworksLauncher::sequence = 0 private
Definition at line 100 of file FireworksLauncherAnniversary.c.
Referenced by OnEventServer().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Gear/Tools/FireworksLauncherAnniversary.c