DayZ: ActionShaveTarget Class Reference
ActionShaveTarget Class Reference
Private Member Functions
void ActionShaveTarget ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 9 of file ActionShaveTarget.c.
Constructor & Destructor Documentation
ActionShaveTarget()
void ActionShaveTarget::ActionShaveTarget () inline private
Definition at line 11 of file ActionShaveTarget.c.
  {
    m_CallbackClass = ActionShaveTargetCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
    m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
    m_Text = "#shave_target";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionShaveTarget::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 27 of file ActionShaveTarget.c.
  {
    PlayerBase man;
    Class.CastTo(man, target.GetObject());
    if (man.CanShave())
      return true;
    return false;
  }
References Class::CastTo().
CreateConditionComponents()
override void ActionShaveTarget::CreateConditionComponents () inline private
Definition at line 21 of file ActionShaveTarget.c.
  {
    m_ConditionItem = new CCINonRuined;
    m_ConditionTarget = new CCTMan(UAMaxDistances.DEFAULT);
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnFinishProgressServer()
override void ActionShaveTarget::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 38 of file ActionShaveTarget.c.
  {
    PlayerBase man;
    if (action_data.m_Target && Class.CastTo(man, action_data.m_Target.GetObject()))
    {
      if (CanReceiveAction(action_data.m_Target))
      {
        man.ShavePlayer();
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty(m_SpecialtyWeight);
      }
    }
  }
References CanReceiveAction(), Class::CastTo(), and m_SpecialtyWeight.
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionShaveTarget.c