DayZ: ActionAttachOnSelection Class Reference
ActionAttachOnSelection Class Reference
Private Member Functions
void ActionAttachOnSelection ()
override void CreateConditionComponents ()
override ActionData CreateActionData ()
int FindSlotIdToAttachOrCombine (PlayerBase player, ActionTarget target, ItemBase item)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=null)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteServer (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
Detailed Description
Definition at line 1 of file ActionAttachOnSelection.c.
Constructor & Destructor Documentation
ActionAttachOnSelection()
void ActionAttachOnSelection::ActionAttachOnSelection () inline private
Definition at line 3 of file ActionAttachOnSelection.c.
  {
    m_Text = "#attach";
  }
References m_Text.
Member Function Documentation
ActionCondition()
override bool ActionAttachOnSelection::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 93 of file ActionAttachOnSelection.c.
  {
    if (GetGame().IsMultiplayer() && GetGame().IsServer())
      return true;
    if (target.GetObject() && target.GetObject().CanUseConstruction())
      return false;
    return FindSlotIdToAttachOrCombine(player, target, item) != InventorySlots.INVALID;
  }
References FindSlotIdToAttachOrCombine(), GetGame(), and InventorySlots::INVALID.
CreateActionData()
override ActionData ActionAttachOnSelection::CreateActionData () inline private
Definition at line 14 of file ActionAttachOnSelection.c.
  {
    AttachActionData action_data = new AttachActionData();
    return action_data;
  }
CreateConditionComponents()
override void ActionAttachOnSelection::CreateConditionComponents () inline private
Definition at line 8 of file ActionAttachOnSelection.c.
  {
    m_ConditionItem = new CCINonRuined();
    m_ConditionTarget = new CCTCursor();
  }
References m_ConditionItem, and m_ConditionTarget.
FindSlotIdToAttachOrCombine()
int ActionAttachOnSelection::FindSlotIdToAttachOrCombine (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 20 of file ActionAttachOnSelection.c.
  {
    EntityAI targetEntity = EntityAI.Cast(target.GetObject());
    if (targetEntity && item)
    {
      if (!targetEntity.GetInventory())
        return InventorySlots.INVALID;
      int slotsCount = item.GetInventory().GetSlotIdCount();
      array<string> selections = new array<string>();
      targetEntity.GetActionComponentNameList(target.GetComponentIndex(), selections);
      foreach (string selection : selections)
      {
        int slotId = -1;
        if (!targetEntity.TranslateSlotFromSelection(selection, slotId))
          slotId = InventorySlots.GetSlotIdFromString(selection);
        if (slotId == -1)
          continue;
        for (int i = 0; i < slotsCount; ++i)
        {
          int itemSlotId = item.GetInventory().GetSlotId(i);
          if (slotId == itemSlotId)
          {
            ItemBase currentAttachment = ItemBase.Cast(targetEntity.GetInventory().FindAttachment(slotId));
            if (currentAttachment)
            {
              if (currentAttachment.CanBeCombined(item))
                return itemSlotId;
            }
            else
            {
              if (targetEntity.GetInventory() && targetEntity.GetInventory().CanAddAttachment(item))
                return itemSlotId;
            }
          }
        }
      }
    }
    return InventorySlots.INVALID;
  }
References InventorySlots::GetSlotIdFromString(), and InventorySlots::INVALID.
Referenced by ActionCondition(), and SetupAction().
OnExecuteClient()
override void ActionAttachOnSelection::OnExecuteClient (ActionData action_data) inline private
Definition at line 123 of file ActionAttachOnSelection.c.
  {
    ClearInventoryReservationEx(action_data);
    EntityAI targetEntity = EntityAI.Cast(action_data.m_Target.GetObject());
    EntityAI itemEntity = action_data.m_MainItem;
    AttachActionData action_data_a = AttachActionData.Cast(action_data);
    ItemBase attachment = ItemBase.Cast(targetEntity.GetInventory().FindAttachment(action_data_a.m_AttSlot));
    if (attachment)
      attachment.CombineItemsClient(itemEntity);
    else
    {
      ItemBase item_base = ItemBase.Cast(itemEntity);
      float stackable = item_base.GetTargetQuantityMax(action_data_a.m_AttSlot);
      if (stackable == 0 || stackable >= item_base.GetQuantity())
        action_data.m_Player.PredictiveTakeEntityToTargetAttachmentEx(targetEntity, itemEntity, action_data_a.m_AttSlot);
      else if (stackable != 0 && stackable < item_base.GetQuantity())
        item_base.SplitIntoStackMaxClient(targetEntity, action_data_a.m_AttSlot);
    }
  }
References ClearInventoryReservationEx().
OnExecuteServer()
override void ActionAttachOnSelection::OnExecuteServer (ActionData action_data) inline private
Definition at line 104 of file ActionAttachOnSelection.c.
  {
    if (GetGame().IsMultiplayer())
      return;
    ClearInventoryReservationEx(action_data);
    AttachActionData action_data_a = AttachActionData.Cast(action_data);
    EntityAI entity;
    if (action_data.m_Target.IsProxy())
      entity = EntityAI.Cast(action_data.m_Target.GetParent());
    else
      entity = EntityAI.Cast(action_data.m_Target.GetObject());
    if (entity && action_data.m_MainItem)
      action_data.m_Player.PredictiveTakeEntityToTargetAttachmentEx(entity, action_data_a.m_MainItem, action_data_a.m_AttSlot);
  }
References ClearInventoryReservationEx(), and GetGame().
SetupAction()
override bool ActionAttachOnSelection::SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = null) inline private
Definition at line 66 of file ActionAttachOnSelection.c.
  {
    int attSlotId = InventorySlots.INVALID;
    if (!GetGame().IsDedicatedServer())
      attSlotId = FindSlotIdToAttachOrCombine(player, target, item);
    if (super.SetupAction(player, target, item, action_data, extra_data))
    {
      if (!GetGame().IsDedicatedServer())
      {
        if (attSlotId != InventorySlots.INVALID)
        {
          AttachActionData action_data_a = AttachActionData.Cast(action_data);
          action_data_a.m_AttSlot = attSlotId;
          return true;
        }
        return false;
      }
      return true;
    }
    return false;
  }
References FindSlotIdToAttachOrCombine(), GetGame(), and InventorySlots::INVALID.
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionAttachOnSelection.c