DayZ: FlammableBase Class Reference
FlammableBase Class Reference
Protected Member Functions
override void DeferredInit ()
void Init ()
override void EEInit ()
override vector GetUniversalTemperatureSourcePosition ()
override void EEDelete (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanPutInCargo (EntityAI parent)
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
bool CanBeTakenAsCargo ()
override bool IsIgnited ()
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
bool IsRagDryEnough (ItemBase rag)
void UpdateCheckForReceivingUpgrade ()
override void OnIgnitedThis (EntityAI fire_source)
override void OnSwitchOn ()
override void OnSwitchOff ()
void SetTorchDecraftResult (string type)
bool ConsumeRag ()
void ConsumeLard (Lard lard)
void Upgrade (ItemBase source)
void ConsumeFuelFromBottle (ItemBase vessel)
void ConsumeFuelFromGasStation ()
void RuinRags ()
override void OnInventoryExit (Man player)
bool StandUp ()
void CalculateQuantity ()
bool CanReceiveUpgrade ()
void CraftingInit (float quantity)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
bool CanTransformIntoStick ()
void TryTransformIntoStick ()
override void OnWorkStart ()
void StopAllParticles ()
Rag GetRag ()
void LockRags (bool do_lock)
void UpdateLight ()
override void OnItemInHandsPlayerSwimStart (PlayerBase player)
override void OnWork (float consumed_energy)
string GetSoundName ()
void UpdateParticle ()
override void OnWorkStop ()
override int GetMeleeMode ()
override int GetMeleeHeavyMode ()
override int GetMeleeSprintMode ()
override void SetActions ()
override void OnAttachmentQuantityChangedEx (ItemBase item, float delta)
override bool DisassembleOnLastDetach ()
override void OnDebugSpawn ()
int GetRagQuantity ()
string GetBurningMaterial ()
string GetBurntMaterial ()
void UpdateMaterial ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
void ApplyResultModifications (ItemBase result)
Protected Attributes
ref UniversalTemperatureSource m_UTSource
ref UniversalTemperatureSourceSettings m_UTSSettings
ref UniversalTemperatureSourceLambdaConstant m_UTSLConstant
Private Member Functions
void FlammableBase ()
Private Member Functions inherited from ItemBase
void BarbedWire ()
void ~BarbedWire ()
override void EEInit ()
bool IsMounted ()
bool GetSlotLockedState ()
void SetMountedState (bool is_mounted)
void UpdateAttachmentSlot ()
void LockAttachmentSlot (bool lock_state)
void Synchronize ()
override void OnVariablesSynchronized ()
void PlayDeployLoopSound ()
void StopDeployLoopSound ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnWork (float consumed_energy)
override void OnIsPlugged (EntityAI source_device)
override void OnIsUnplugged (EntityAI last_energy_source)
override void OnInventoryEnter (Man player)
void CreateElectrifiedDamageTrigger ()
void CreateDamageTrigger ()
void DestroyDamageTrigger ()
void Spark ()
void SoundCut ()
void SoundSpark ()
void SoundBuzzLoopStart ()
void SoundBuzzLoopStop ()
void SoundElectricShock ()
void SoundCollision ()
override void PreAreaDamageActions ()
override void PostAreaDamageActions ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override void SetActions ()
void BaseBuildingBase ()
override void EEDelete (EntityAI parent)
override string GetInvulnerabilityTypeString ()
override bool CanObstruct ()
override int GetHideIconMask ()
void SynchronizeBaseState ()
override void OnVariablesSynchronized ()
void OnSynchronizedClient ()
void RegisterPartForSync (int part_id)
void UnregisterPartForSync (int part_id)
bool IsPartBuildInSyncData (int part_id)
void RegisterActionForSync (int part_id, int action_id)
void ResetActionSyncData ()
void SetActionFromSyncData ()
void SetPartFromSyncData (ConstructionPart part)
void SetPartsFromSyncData ()
ConstructionPart GetConstructionPartById (int id)
bool HasBase ()
void SetBaseState (bool has_base)
override bool IsDeployable ()
bool IsOpened ()
ItemBase CreateConstructionKit ()
void CreateConstructionKitInHands (notnull PlayerBase player)
vector GetKitSpawnPosition ()
string GetConstructionKitType ()
void DestroyConstructionKit (ItemBase construction_kit)
void DestroyConstruction ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
void SetPartsAfterStoreLoad ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void EEOnAfterLoad ()
override void EEInit ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
void OnSetSlotLock (int slotId, bool locked, bool was_locked)
override bool IgnoreOutOfReachCondition ()
void OnPartBuiltServer (notnull Man player, string part_name, int action_id)
void OnPartBuiltClient (string part_name, int action_id)
void OnPartDismantledServer (notnull Man player, string part_name, int action_id)
void OnPartDismantledClient (string part_name, int action_id)
void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part=false)
void OnPartDestroyedClient (string part_name, int action_id)
void InitBaseState ()
void InitVisuals ()
void UpdateVisuals ()
void UpdateAttachmentVisuals (string slot_name, bool is_locked)
void UpdatePhysics ()
void UpdateAttachmentPhysics (string slot_name, bool is_locked)
void UpdateNavmesh ()
override bool CanUseConstruction ()
override bool CanUseConstructionBuild ()
bool IsAttachmentSlotLocked (EntityAI attachment)
bool IsAttachmentSlotLocked (string slot_name)
void GetAttachmentSlots (EntityAI entity, out array< string > attachment_slots)
bool CheckSlotVerticalDistance (int slot_id, PlayerBase player)
bool CheckMemoryPointVerticalDistance (float max_dist, string selection, PlayerBase player)
bool CheckLevelVerticalDistance (float max_dist, string selection, PlayerBase player)
void ConstructionInit ()
Construction GetConstruction ()
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
bool HasAttachmentsBesidesBase ()
override bool ShowZonesHealth ()
override bool CanPutInCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool IsFacingPlayer (PlayerBase player, string selection)
override bool IsPlayerInside (PlayerBase player, string selection)
bool MustBeBuiltFromOutside ()
Some buildings can only be built from outside.
bool IsFacingCamera (string selection)
bool PerformRoofCheckForBase (string partName, PlayerBase player, out bool result)
bool HasProperDistance (string selection, PlayerBase player)
bool CanFoldBaseBuildingObject ()
ItemBase FoldBaseBuildingObject ()
void CreateAreaDamage (string slot_name, float rotation_angle=0)
void CalcDamageAreaRotation (float angle_deg, out vector center, out vector orientation)
void DestroyAreaDamage (string slot_name)
override bool IsIgnoredByConstruction ()
void SoundBuildStart (string part_name)
void SoundDismantleStart (string part_name)
void SoundDestroyStart (string part_name)
string GetBuildSoundByMaterial (string part_name)
string GetDismantleSoundByMaterial (string part_name)
void CheckForHybridAttachments (EntityAI item, string slot_name)
override int GetDamageSystemVersionChange ()
override void SetActions ()
void DebugCustomState ()
array< string > OnDebugSpawnBuildExcludes ()
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
override void OnDebugSpawn ()
void FullyBuild ()
void BatteryCharger ()
override bool IsElectricAppliance ()
override void OnWork (float consumed_energy)
override void OnWorkStart ()
override void OnWorkStop ()
void UpdateStatusLights ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI player)
override void OnOwnSocketTaken (EntityAI device)
override void OnOwnSocketReleased (EntityAI device)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanLoadAttachment (EntityAI attachment)
void HideAttachedClipsStates ()
void RedLightOn ()
void GreenLightOn ()
void YellowLightOn ()
void SwitchLightOn ()
void RedLightOff ()
void GreenLightOff ()
void YellowLightOff ()
void SwitchLightOff ()
override void OnSwitchOn ()
override void OnSwitchOff ()
override void OnInventoryExit (Man player)
override void OnInventoryEnter (Man player)
override void OnVariablesSynchronized ()
override void RefreshPhysics ()
override void OnPlacementStarted (Man player)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override bool IsDeployable ()
override string GetPlaceSoundset ()
override void SetActions ()
override void OnWorkStart ()
override void OnWorkStop ()
void RefreshFlameVisual (bool working=false)
void SoundBurningStart ()
void SoundBurningStop ()
override bool CanPutInCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool IsIgnited ()
override void OnIgnitedTarget (EntityAI ignited_item)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override void SetActions ()
EntityAI GetGasCanister ()
bool HasEnoughEnergyForRepair (float pTime)
override void OnDebugSpawn ()
void KitBase ()
void ~KitBase ()
override bool IsBasebuildingKit ()
override bool HasProxyParts ()
override bool CanProxyObstruct ()
override void OnVariablesSynchronized ()
override void EEInit ()
override bool DisassembleOnLastDetach ()
override void EEItemDetached (EntityAI item, string slot_name)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnEndPlacement ()
override void OnPlacementCancelled (Man player)
override bool IsDeployable ()
override bool CanAssignAttachmentsToQuickbar ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override string GetDeployFinishSoundset ()
override void RefreshPhysics ()
void UpdateVisuals ()
void UpdatePhysics ()
void PlayDeployLoopSound ()
void StopDeployLoopSound ()
void AssembleKit ()
void DisassembleKit (ItemBase item)
void CreateRope (Rope rope)
override void SetActions ()
void Paper ()
void ~Paper ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override WrittenNoteData GetWrittenNoteData ()
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=null)
override bool CanIgniteItem (EntityAI ignite_target=null)
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedThis (EntityAI fire_source)
override bool IsThisIgnitionSuccessful (EntityAI item_source=null)
override void SetActions ()
void ParticleTest ()
override void EEDelete (EntityAI parent)
override void OnSwitchOn ()
override void OnSwitchOff ()
override void OnWorkStart ()
override void OnWorkStop ()
void SoundBurningStart ()
void SoundBurningStop ()
void SoundTurnOn ()
void SoundTurnOff ()
override void SetActions ()
ItemBase GetCookingEquipment ()
void SetCookingEquipment (ItemBase equipment)
void ClearCookingEquipment (ItemBase pItem)
void DestroyFireplace ()
override void EEInit ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void OnSwitchOn ()
override void OnSwitchOff ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnWork (float consumed_energy)
void CookWithEquipment ()
void RefreshFlameVisual (bool working=false, bool hasAttachment=false)
void RemoveCookingAudioVisuals ()
void SoundBurningStart ()
void SoundBurningStop ()
void SoundTurnOn ()
void SoundTurnOff ()
override bool CanPutInCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanLoadAttachment (EntityAI attachment)
override bool CanPutIntoHands (EntityAI parent)
override bool IsIgnited ()
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override void SetActions ()
override void OnDebugSpawn ()
void PowerGeneratorBase ()
void ~PowerGeneratorBase ()
override void EEInit ()
override void EOnInit (IEntity other, int extra)
override float GetLiquidThroughputCoef ()
void StartLoopSound ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI player)
bool CanManipulate ()
override void OnInitEnergy ()
override void OnWorkStart ()
override void OnWork (float consumed_energy)
override void OnWorkStop ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
void UpdateFuelMeter ()
void SetFuel (float fuel_amount)
float AddFuel (float available_fuel)
bool CanAddFuel (ItemBase container)
float GetFuel ()
float GetMaxFuel ()
bool HasSparkplug ()
override void OnVariablesSynchronized ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override string GetPlaceSoundset ()
override void SetActions ()
override void OnDebugSpawn ()
override void OnWorkStart ()
void StartPeriodicMeasurement ()
void PrepareMeasurement ()
void DoMeasurement ()
void StopPeriodicMeasurement ()
override void OnWorkStop ()
override void SetActions ()
void Spotlight ()
void ~Spotlight ()
override bool IsElectricAppliance ()
override void OnInitEnergy ()
override void EOnInit (IEntity other, int extra)
override void OnSwitchOn ()
override void OnSwitchOff ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnIsPlugged (EntityAI source_device)
void UpdateAllSelections ()
override void OnIsUnplugged (EntityAI last_energy_source)
override void OnVariablesSynchronized ()
void Fold (bool keep_connected=false)
void Unfold ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI player)
bool IsFolded ()
void SoundTurnOn ()
void SoundTurnOff ()
override void OnPlacementStarted (Man player)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnPlacementCancelled (Man player)
override bool IsDeployable ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
void PlayDeployLoopSound ()
void StopDeployLoopSound ()
override int GetViewIndex ()
override void SetActions ()
void TentBase ()
void ~TentBase ()
override string GetInvulnerabilityTypeString ()
override bool HasProxyParts ()
override bool CanProxyObstructSelf ()
prevents showing cargo when outside the tent geometry
override bool IsItemTent ()
override bool CanBeRepairedByCrafting ()
override int GetMeleeTargetType ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void RefreshPhysics ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnVariablesSynchronized ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
void HideAllAnimationsAndProxyPhysics (bool hide_animations=true, bool hide_physics=true)
bool ConditionIntoInventory (EntityAI player)
override bool CanPutIntoHands (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
bool ConditionOutOfHands (EntityAI player)
override bool CanBeRepairedToPristine ()
void RefreshAttachements ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override int GetViewIndex ()
int GetState ()
int GetStateLocal ()
bool CanBePacked ()
bool CanBeManipulated ()
bool CanAttach (ItemBase item)
override bool IsIgnoredByConstruction ()
void Pack (bool update_navmesh, bool init=false)
void Pitch (bool update_navmesh, bool init=false)
void TryPitch (bool update_navmesh, bool init=false)
void UpdateVisuals ()
void UpdatePhysics ()
void Refresh ()
bool CanToggleAnimations (string selection)
void ResetToggle ()
void ManipulateEntrance ()
void ManipulateWindow ()
bool IsManipulatedEntrance ()
bool IsManipulatedWindow ()
void ToggleAnimation (string selection)
void HandleCamoNetAttachment (bool hide)
void AnimateCamonetToggle (ToggleAnimations toggle)
void AnimateCamonetByOpeningSelection (string opening_selection)
string GetSoundOpen ()
string GetSoundClose ()
string GetSoundOpenWindow ()
string GetSoundCloseWindow ()
void SoundTentOpenPlay ()
void SoundTentClosePlay ()
void SoundTentOpenWindowPlay ()
void SoundTentCloseWindowPlay ()
void RegenerateNavmesh ()
bool HasClutterCutter ()
string GetClutterCutter ()
void DestroyClutterCutter ()
override bool IsDeployable ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
void PlayDeployLoopSound ()
void StopDeployLoopSound ()
override void SetActions ()
void HandleOpeningsVisuals ()
void HandleOpeningsPhysics ()
override int GetDamageSystemVersionChange ()
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanLoadItemIntoCargo (EntityAI item)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanLoadAttachment (EntityAI attachment)
override bool CanBePlaced (Man player, vector position)
void SetIsBeingPacked (bool isBeingPacked)
void ToolBase ()
int GetDisarmRate ()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Private Attributes
SoundOnVehicle m_LoopSoundEntity
Particle m_FireParticle
bool m_CanReceiveUpgrade
bool m_IsBeingDestructed = false
float m_BurnTimePerRagEx
float m_BurnTimePerFullLardEx
float m_BurnTimePerFullFuelDoseEx
float m_MaxConsumableLardQuantityEx
float m_MaxConsumableFuelQuantityEx
float m_WaterEvaporationByFireIntensityEx = 0.001
int m_StartFadeOutOfLightAtQuantityEx = 3
int m_RagsUpgradedCount
bool m_ConsumeRagFlipFlop
vector m_ParticleLocalPos = Vector(0, 0.50, 0)
string m_DecraftResult = "WoodenStick"
TorchLight m_Light
bool m_WasLit
Private Attributes inherited from ItemBase
ref array< ref Slot > m_Slots
int m_SlotFertilityState = 0
int m_SlotWateredState = 0
int m_MaxWateredStateVal = 0
float m_DefaultFertility = 1
ref Timer m_CheckRainTimer
EffectSound m_DeployLoopSound
SoundOnVehicle m_BuzzSoundLoop
ref Timer m_SparkEvent
ref AreaDamageManager m_AreaDamage
bool m_TriggerActive
bool m_IsPlaced
bool m_IsMounted
bool m_LastMountedState
const string SOUND_MOUNT = "putDown_BarbedWire_SoundSet"
EffectSound m_MountSound
EffectSound m_Sound
ref map< string, ref AreaDamageManager > m_DamageTriggers
ref array< string > m_HybridAttachments
ref array< string > m_Mountables
const string ATTACHED_CLIPS_STATES [] = {SEL_CLIPS_CAR, SEL_CLIPS_TRUCK}
const int ATTACHED_CLIPS_STATES_COUNT = 2
int m_BatteryEnergy0To100
float m_ChargeEnergyPerSecond
ref Timer m_UpdateStatusLightsTimer
bool m_BlinkingStatusLightIsOn = false
BlowtorchLight m_Light
EffectSound m_SoundBurningLoop
bool m_DeployedRegularly
ref WrittenNoteData m_NoteContents
int PARTICLE_PATH
Particle m_Particle
EffectSound m_SoundTurnOn
EffectSound m_SoundTurnOff
const string FLAME_BUTANE_ON = "dz\\gear\\cooking\\data\\flame_butane_ca.paa"
const string FLAME_BUTANE_OFF = ""
ATTACHMENT_COOKING_POT = Pot
ATTACHMENT_FRYING_PAN = FryingPan
ATTACHMENT_CAULDRON = Cauldron
const float PARAM_COOKING_TEMP_THRESHOLD = 100
const float PARAM_COOKING_EQUIP_TEMP_INCREASE = 10
const float PARAM_COOKING_EQUIP_MAX_TEMP = 250
const float PARAM_COOKING_TIME_INC_COEF = 0.5
ref UniversalTemperatureSource m_UTSource
DEPRECATED Attached spark plug item.
ref UniversalTemperatureSourceSettings m_UTSSettings
ref UniversalTemperatureSourceLambdaConstant m_UTSLConst
EffectSound m_EngineLoop
EffectSound m_EngineStart
EffectSound m_EngineStop
ref Timer m_SoundLoopStartTimer
Effect m_Smoke
ItemBase m_SparkPlug
ref UniversalTemperatureSourceLambdaEngine m_UTSLEngine
ref Timer m_Timer
int m_State
int m_StateLocal = -1
bool m_IsEntrance
bool m_IsWindow
bool m_IsToggle
bool m_IsBeingPacked = false
int m_OpeningMask = 0
int m_OpeningMaskLocal = -1
ref map< ref ToggleAnimations, bool > m_ToggleAnimations
ref array< string > m_ShowAnimationsWhenPitched
ref array< string > m_ShowAnimationsWhenPacked
Object m_ClutterCutter
CamoNet m_CamoNet
vector m_HalfExtents
int m_MineDisarmRate = 60
EntityAI m_Bait
bool m_IsActive
bool m_IsDeployed
bool m_IsInProgress
string m_AnimationPhaseSet
string m_AnimationPhaseTriggered
string m_AnimationPhaseUsed
ref array< string > m_PlaceableWaterSurfaceList
DEPRECATED.
bool m_WaterSurfaceForSetup
ref multiMap< string, float > m_CatchesPond
ref multiMap< string, float > m_CatchesSea
ref multiMap< string, float > m_CatchesGroundAnimal
ref EffectSound m_DeployLoopSound
ref Timer m_PrevTimer
bool m_NeedInstalation
bool m_BaitNeeded
bool m_IsUsable
Additional Inherited Members
Static Private Attributes inherited from ItemBase
const string SEL_CLIPS_CAR = "clips_car_battery"
const string SEL_CLIPS_TRUCK = "clips_truck_battery"
const string SEL_CLIPS_DETACHED = "clips_detached"
const string SEL_CLIPS_FOLDED = "clips_folded"
const string SEL_SWITCH_ON = "switch_on"
const string SEL_SWITCH_OFF = "switch_off"
const string SEL_CORD_PLUGGED = "cord_plugged"
const string SEL_CORD_FOLDED = "cord_folded"
const string SEL_LIGHT_STATE_1 = "light_stand_by"
const string SEL_LIGHT_STATE_2 = "light_charging"
const string SEL_LIGHT_STATE_3 = "light_charged"
const string RED_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_r.rvmat"
const string GREEN_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_g.rvmat"
const string YELLOW_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_y.rvmat"
const string SWITCH_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_switch_on.rvmat"
const string DEFAULT_MATERIAL = "dz\\gear\\camping\\data\\battery_charger.rvmat"
float m_BlinkingStatusLightInterval = 0.4
Detailed Description
Definition at line 1 of file Torch.c.
Constructor & Destructor Documentation
FlammableBase()
void FlammableBase::FlammableBase () inline private
Definition at line 3 of file Torch.c.
  {
    Init();
  }
References Init().
Member Function Documentation
ApplyResultModifications()
void FlammableBase::ApplyResultModifications (ItemBase result) inline protected
Definition at line 798 of file Torch.c.
  {
    result.SetQuantity(1);
  }
Referenced by TryTransformIntoStick().
CalculateQuantity()
void FlammableBase::CalculateQuantity () inline protected
Definition at line 393 of file Torch.c.
  {
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
      SetQuantityNormalized(GetCompEM().GetEnergy0To1());
  }
References GetGame(), and SetQuantityNormalized().
Referenced by ConsumeFuelFromBottle(), ConsumeFuelFromGasStation(), ConsumeLard(), EEItemAttached(), EEItemDetached(), OnAttachmentQuantityChangedEx(), OnDebugSpawn(), OnWork(), OnWorkStop(), and Upgrade().
CanBeIgnitedBy()
override bool FlammableBase::CanBeIgnitedBy (EntityAI igniter = NULL) inline protected
Definition at line 145 of file Torch.c.
  {
    if (!GetCompEM().CheckWetness())
      return false;
    ItemBase rag = GetRag();
    if (rag && GetCompEM().GetEnergy() < GetCompEM().GetEnergyUsage() * GetCompEM().GetUpdateInterval())
    {
      if (IsRagDryEnough(rag))
        return false;
    }
    if (!GetCompEM().CanWork())
      return false;
    if (GetCompEM().GetEnergy() < 3)
      return false;
    PlayerBase player = PlayerBase.Cast(GetHierarchyRootPlayer());
    if (player)
    {
      if (this != player.GetItemInHands())//we are in player's inventory, but not in his hands
        return false;
    }
    return true;
  }
References GetEnergy(), GetRag(), and IsRagDryEnough().
CanBeTakenAsCargo()
bool FlammableBase::CanBeTakenAsCargo () inline protected
Definition at line 123 of file Torch.c.
  {
    // Don't let players burn their pockets!
    return !GetCompEM().IsWorking();
  }
Referenced by CanPutInCargo(), and CanRemoveFromCargo().
CanIgniteItem()
override bool FlammableBase::CanIgniteItem (EntityAI ignite_target = NULL) inline protected
Definition at line 134 of file Torch.c.
  {
    return GetCompEM().IsWorking();
  }
CanPutAsAttachment()
override bool FlammableBase::CanPutAsAttachment (EntityAI parent) inline protected
Definition at line 118 of file Torch.c.
  {
    return !GetCompEM().IsWorking();
  }
CanPutInCargo()
override bool FlammableBase::CanPutInCargo (EntityAI parent) inline protected
Definition at line 100 of file Torch.c.
  {
    if (!super.CanPutInCargo(parent)) return false;
    return CanBeTakenAsCargo();
  }
References CanBeTakenAsCargo().
CanReceiveAttachment()
override bool FlammableBase::CanReceiveAttachment (EntityAI attachment, int slotId) inline protected
Definition at line 91 of file Torch.c.
  {
    ItemBase att = ItemBase.Cast(GetInventory().FindAttachment(slotId));
    if (att && att.IsFullQuantity())
      return false;
    return super.CanReceiveAttachment(attachment, slotId);
  }
CanReceiveUpgrade()
bool FlammableBase::CanReceiveUpgrade () inline protected
Definition at line 399 of file Torch.c.
  {
    return m_CanReceiveUpgrade;
  }
References m_CanReceiveUpgrade.
CanReleaseAttachment()
override bool FlammableBase::CanReleaseAttachment (EntityAI attachment) inline protected
Definition at line 106 of file Torch.c.
  {
    if (!super.CanReleaseAttachment(attachment))
      return false;
    return !GetCompEM().IsWorking();
  }
CanRemoveFromCargo()
override bool FlammableBase::CanRemoveFromCargo (EntityAI parent) inline protected
Definition at line 113 of file Torch.c.
  {
    return CanBeTakenAsCargo();
  }
References CanBeTakenAsCargo().
CanTransformIntoStick()
bool FlammableBase::CanTransformIntoStick () inline protected
Definition at line 440 of file Torch.c.
  {
    if ((GetGame().IsServer() || !GetGame().IsMultiplayer()) && !IsIgnited() && !GetRag() && !IsSetForDeletion())
      return true;
    else
      return false;
  }
References GetGame(), GetRag(), and IsIgnited().
Referenced by TryTransformIntoStick().
ConsumeFuelFromBottle()
void FlammableBase::ConsumeFuelFromBottle (ItemBase vessel) inline protected
Definition at line 302 of file Torch.c.
  {
    if (vessel)
    {
      float vessel_quant = vessel.GetQuantity();
      float available_vessel_quant = vessel_quant;
      if (available_vessel_quant > m_MaxConsumableFuelQuantityEx)
        available_vessel_quant = m_MaxConsumableFuelQuantityEx;
      float available_vessel_coef = available_vessel_quant / m_MaxConsumableFuelQuantityEx;
      float add_energy = m_BurnTimePerFullFuelDoseEx * available_vessel_coef;
      float add_energy_coef = 1;
      float energy_limit = GetCompEM().GetEnergyMax() - GetCompEM().GetEnergy();
      if (add_energy > energy_limit)
      {
        add_energy_coef = energy_limit / add_energy;
        add_energy = energy_limit;
        available_vessel_quant = available_vessel_quant * add_energy_coef;
      }
      GetCompEM().AddEnergy(add_energy);
      vessel.AddQuantity(-available_vessel_quant);
      CalculateQuantity();
      UpdateCheckForReceivingUpgrade();
    }
  }
References CalculateQuantity(), m_BurnTimePerFullFuelDoseEx, m_MaxConsumableFuelQuantityEx, and UpdateCheckForReceivingUpgrade().
ConsumeFuelFromGasStation()
void FlammableBase::ConsumeFuelFromGasStation () inline protected
Definition at line 336 of file Torch.c.
  {
    float add_energy = m_BurnTimePerFullFuelDoseEx;
    float add_energy_coef = 1;
    float energy_limit = GetCompEM().GetEnergyMax() - GetCompEM().GetEnergy();
    if (add_energy > energy_limit)
    {
      add_energy_coef = energy_limit / add_energy;
      add_energy = energy_limit;
    }
    GetCompEM().AddEnergy(add_energy);
    CalculateQuantity();
    UpdateCheckForReceivingUpgrade();
  }
References CalculateQuantity(), m_BurnTimePerFullFuelDoseEx, and UpdateCheckForReceivingUpgrade().
ConsumeLard()
void FlammableBase::ConsumeLard (Lard lard) inline protected
Definition at line 238 of file Torch.c.
  {
    if (lard)
    {
      float lard_quant = lard.GetQuantity();
      float available_lard_quant = lard_quant;
      if (available_lard_quant > m_MaxConsumableLardQuantityEx)
        available_lard_quant = m_MaxConsumableLardQuantityEx;
      float available_lard_coef = available_lard_quant / m_MaxConsumableLardQuantityEx;
      float add_energy = m_BurnTimePerFullLardEx * available_lard_coef;
      float add_energy_coef = 1;
      float energy_limit = GetCompEM().GetEnergyMax() - GetCompEM().GetEnergy();
      if (add_energy > energy_limit)
      {
        add_energy_coef = energy_limit / add_energy;
        add_energy = energy_limit;
        available_lard_quant = available_lard_quant * add_energy_coef;
      }
      GetCompEM().AddEnergy(add_energy);
      lard.AddQuantity(-available_lard_quant);
      CalculateQuantity();
      UpdateCheckForReceivingUpgrade();
    }
  }
References CalculateQuantity(), m_BurnTimePerFullLardEx, m_MaxConsumableLardQuantityEx, and UpdateCheckForReceivingUpgrade().
ConsumeRag()
bool FlammableBase::ConsumeRag () inline protected
Definition at line 218 of file Torch.c.
  {
    ItemBase rag = GetRag();
    if (rag)
    {
      if (rag.GetQuantity() <= 1)
      {
        LockRags(false); // Unlock attachment slot before deletion. Otherwise it will get stuck locked and unusable.
      }
      rag.AddQuantity(-1);
      rag.SetHealth(0);
      //GetCompEM().AddEnergy( m_BurnTimePerRagEx );
      return true;
    }
    return false;
  }
References GetRag(), and LockRags().
Referenced by OnIgnitedThis(), and OnWork().
CraftingInit()
void FlammableBase::CraftingInit (float quantity) inline protected
Definition at line 404 of file Torch.c.
  {
    GetCompEM().SetEnergy(m_BurnTimePerRagEx * quantity);
    m_CanReceiveUpgrade = true;
    SetSynchDirty();
  }
References m_BurnTimePerRagEx, and m_CanReceiveUpgrade.
Referenced by OnDebugSpawn().
DeferredInit()
override void FlammableBase::DeferredInit () inline protected
Definition at line 33 of file Torch.c.
  {
    if (m_RagsUpgradedCount)
      LockRags(true);
  }
References LockRags(), and m_RagsUpgradedCount.
DisassembleOnLastDetach()
override bool FlammableBase::DisassembleOnLastDetach () inline protected
Definition at line 731 of file Torch.c.
  {
    return true;
  }
EEDelete()
override void FlammableBase::EEDelete (EntityAI parent) inline protected
Definition at line 82 of file Torch.c.
  {
    super.EEDelete(parent);
    if (m_LoopSoundEntity != NULL && GetGame() != NULL)
      GetGame().ObjectDelete(m_LoopSoundEntity);
    StopAllParticles();
  }
References GetGame(), m_LoopSoundEntity, and StopAllParticles().
EEInit()
override void FlammableBase::EEInit () inline protected
Definition at line 53 of file Torch.c.
  {
    super.EEInit();
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      m_UTSSettings = new UniversalTemperatureSourceSettings();
      m_UTSSettings.m_Updateable = true;
      m_UTSSettings.m_UpdateInterval = 1;
      m_UTSSettings.m_TemperatureMin = 0;
      m_UTSSettings.m_TemperatureMax = 300;
      m_UTSSettings.m_RangeFull = 0.5;
      m_UTSSettings.m_RangeMax = 1;
      m_UTSSettings.m_TemperatureCap = 5;
      m_UTSLConstant = new UniversalTemperatureSourceLambdaConstant();
      m_UTSource = new UniversalTemperatureSource(this, m_UTSSettings, m_UTSLConstant);
    }
  }
References GetGame(), m_UTSLConstant, m_UTSource, and m_UTSSettings.
EEItemAttached()
override void FlammableBase::EEItemAttached (EntityAI item, string slot_name) inline protected
Definition at line 412 of file Torch.c.
  {
    super.EEItemAttached(item, slot_name);
    CalculateQuantity();
    UpdateCheckForReceivingUpgrade();
  }
References CalculateQuantity(), and UpdateCheckForReceivingUpgrade().
EEItemDetached()
override void FlammableBase::EEItemDetached (EntityAI item, string slot_name) inline protected
Definition at line 420 of file Torch.c.
  {
    super.EEItemDetached(item, slot_name);
    if (m_IsBeingDestructed)
    {
      if (GetGame().IsServer() || !GetGame().IsMultiplayer())
      {
        EntityAI rags = EntityAI.Cast(GetGame().CreateObjectEx(item.GetType(), GetPosition(), ECE_PLACE_ON_SURFACE));
        if (rags)
          MiscGameplayFunctions.TransferItemProperties(item, rags);
      }
      return;
    }
    CalculateQuantity();
    UpdateCheckForReceivingUpgrade();
    GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(TryTransformIntoStick, 100);
  }
References CalculateQuantity(), CALL_CATEGORY_SYSTEM, ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, m_IsBeingDestructed, TryTransformIntoStick(), and UpdateCheckForReceivingUpgrade().
GetBurningMaterial()
string FlammableBase::GetBurningMaterial () inline protected
Definition at line 750 of file Torch.c.
  {
    return "";
  }
Referenced by UpdateMaterial().
GetBurntMaterial()
string FlammableBase::GetBurntMaterial () inline protected
Definition at line 755 of file Torch.c.
  {
    return "";
  }
Referenced by UpdateMaterial().
GetMeleeHeavyMode()
override int FlammableBase::GetMeleeHeavyMode () inline protected
Definition at line 696 of file Torch.c.
  {
    if (GetCompEM().IsWorking())
      return 4; // ???
    else
      return 1; // ???
  }
GetMeleeMode()
override int FlammableBase::GetMeleeMode () inline protected
Definition at line 688 of file Torch.c.
  {
    if (GetCompEM().IsWorking())
      return 3; // ???
    else
      return 0; // ???
  }
GetMeleeSprintMode()
override int FlammableBase::GetMeleeSprintMode () inline protected
Definition at line 704 of file Torch.c.
  {
    if (GetCompEM().IsWorking())
      return 5; // ???
    else
      return 2; // ???
  }
GetRag()
Rag FlammableBase::GetRag () inline protected
Definition at line 505 of file Torch.c.
  {
    return Rag.Cast(GetAttachmentByType(Rag));
  }
Referenced by CanBeIgnitedBy(), CanTransformIntoStick(), ConsumeRag(), GetRagQuantity(), LockRags(), OnWork(), OnWorkStop(), RuinRags(), and Upgrade().
GetRagQuantity()
int FlammableBase::GetRagQuantity () inline protected
Definition at line 743 of file Torch.c.
  {
    if (GetRag())
      return Math.Round(GetRag().GetQuantity());
    return 0;
  }
References GetQuantity(), GetRag(), and Math::Round().
Referenced by OnDebugSpawn(), OnWork(), OnWorkStop(), UpdateCheckForReceivingUpgrade(), and Upgrade().
GetSoundName()
string FlammableBase::GetSoundName () inline protected
Definition at line 615 of file Torch.c.
  {
    return "torchLoop";
  }
Referenced by OnWork().
GetUniversalTemperatureSourcePosition()
override vector FlammableBase::GetUniversalTemperatureSourcePosition () inline protected
Definition at line 74 of file Torch.c.
  {
    if (GetHierarchyRoot())
      return GetHierarchyRoot().GetPosition();
    return super.GetPosition();
  }
HasFlammableMaterial()
override bool FlammableBase::HasFlammableMaterial () inline protected
Definition at line 139 of file Torch.c.
  {
    return true;
  }
Init()
void FlammableBase::Init () inline protected
Definition at line 39 of file Torch.c.
  {
    if (m_BurnTimePerRagEx == 0 || m_BurnTimePerFullLardEx == 0 || m_MaxConsumableLardQuantityEx == 0 || m_MaxConsumableFuelQuantityEx == 0)
    {
      string cfg_path = "CfgVehicles " + GetType();
      m_BurnTimePerRagEx = GetGame().ConfigGetFloat(cfg_path + " burnTimePerRag");
      m_BurnTimePerFullLardEx = GetGame().ConfigGetFloat(cfg_path + " burnTimePerFullLardDose");
      m_BurnTimePerFullFuelDoseEx = GetGame().ConfigGetFloat(cfg_path + " burnTimePerFullFuelDose");
      m_MaxConsumableLardQuantityEx = GetGame().ConfigGetFloat(cfg_path + " maxConsumableLardDose");
      m_MaxConsumableFuelQuantityEx = GetGame().ConfigGetFloat(cfg_path + " maxConsumableFuelDose");
    }
    RegisterNetSyncVariableBool("m_CanReceiveUpgrade");
  }
References GetGame(), GetType(), m_BurnTimePerFullFuelDoseEx, m_BurnTimePerFullLardEx, m_BurnTimePerRagEx, m_MaxConsumableFuelQuantityEx, and m_MaxConsumableLardQuantityEx.
Referenced by FlammableBase().
IsIgnited()
override bool FlammableBase::IsIgnited () inline protected
Definition at line 129 of file Torch.c.
  {
    return GetCompEM().IsWorking();
  }
Referenced by BroomBase::CanTransformIntoStick(), and CanTransformIntoStick().
IsRagDryEnough()
bool FlammableBase::IsRagDryEnough (ItemBase rag) inline protected
Definition at line 174 of file Torch.c.
  {
    float wetness = rag.GetWet();
    bool is_dry_enough = wetness <= 1 - GetCompEM().GetWetnessExposure();
    return is_dry_enough;
  }
Referenced by CanBeIgnitedBy().
LockRags()
void FlammableBase::LockRags (bool do_lock) inline protected
Definition at line 510 of file Torch.c.
  {
    ItemBase rag = GetRag();
    if (rag)
    {
      if (do_lock)
        rag.LockToParent();
      else if (!m_RagsUpgradedCount)
        rag.UnlockFromParent();
    }
  }
References GetRag(), and m_RagsUpgradedCount.
Referenced by ConsumeRag(), DeferredInit(), OnWorkStart(), OnWorkStop(), and Upgrade().
OnAttachmentQuantityChangedEx()
override void FlammableBase::OnAttachmentQuantityChangedEx (ItemBase item, float delta) inline protected
Definition at line 719 of file Torch.c.
  {
    super.OnAttachmentQuantityChangedEx(item, delta);
    if (delta > 0)
    {
      GetCompEM().AddEnergy(m_BurnTimePerRagEx * delta);
      CalculateQuantity();
      UpdateCheckForReceivingUpgrade();
    }
  }
References CalculateQuantity(), m_BurnTimePerRagEx, and UpdateCheckForReceivingUpgrade().
OnDebugSpawn()
override void FlammableBase::OnDebugSpawn () inline protected
Definition at line 736 of file Torch.c.
  {
    GetInventory().CreateAttachment("Rag");
    CraftingInit(GetRagQuantity());
    CalculateQuantity();
  }
References CalculateQuantity(), CraftingInit(), and GetRagQuantity().
OnIgnitedThis()
override void FlammableBase::OnIgnitedThis (EntityAI fire_source) inline protected
Definition at line 190 of file Torch.c.
  {
    if (!GetCompEM().HasEnoughStoredEnergy())
      ConsumeRag();
    GetCompEM().SwitchOn();
  }
References ConsumeRag().
Referenced by BroomBase::OnAction().
OnInventoryExit()
override void FlammableBase::OnInventoryExit (Man player) inline protected
Definition at line 365 of file Torch.c.
  {
    super.OnInventoryExit(player);
    StandUp();
  }
References StandUp().
OnItemInHandsPlayerSwimStart()
override void FlammableBase::OnItemInHandsPlayerSwimStart (PlayerBase player) inline protected
Definition at line 561 of file Torch.c.
  {
    GetCompEM().SwitchOff();
  }
OnStoreLoad()
override bool FlammableBase::OnStoreLoad (ParamsReadContext ctx, int version) inline protected
Definition at line 785 of file Torch.c.
  {
    if (!super.OnStoreLoad(ctx, version))
      return false;
    if (version >= 130)
    {
      if (!ctx.Read(m_WasLit))
        return false;
    }
    UpdateMaterial();
    return true;
  }
References m_WasLit, and UpdateMaterial().
OnStoreSave()
override void FlammableBase::OnStoreSave (ParamsWriteContext ctx) inline protected
Definition at line 778 of file Torch.c.
  {
    super.OnStoreSave(ctx);
    ctx.Write(m_WasLit);
  }
References m_WasLit.
OnSwitchOff()
override void FlammableBase::OnSwitchOff () inline protected
Definition at line 207 of file Torch.c.
  {
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
      m_UTSource.SetActive(false);
  }
References GetGame(), and m_UTSource.
OnSwitchOn()
override void FlammableBase::OnSwitchOn () inline protected
Definition at line 198 of file Torch.c.
  {
    if (!GetCompEM().HasEnoughStoredEnergy())
      GetCompEM().SwitchOff();
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
      m_UTSource.SetActive(true);
  }
References GetGame(), and m_UTSource.
OnWork()
override void FlammableBase::OnWork (float consumed_energy) inline protected
Definition at line 567 of file Torch.c.
  {
    UpdateMaterial();
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      if (GetCompEM().GetEnergy() < ((GetRagQuantity() + m_RagsUpgradedCount) - 1) * m_BurnTimePerRagEx)
      {
        if (m_RagsUpgradedCount == 0) //always burn rag
          ConsumeRag();
        else if (m_ConsumeRagFlipFlop)//burn rag
        {
          ConsumeRag();
          m_ConsumeRagFlipFlop = !m_ConsumeRagFlipFlop;
        }
        else//burn lard/fuel
        {
          m_RagsUpgradedCount--;
          m_ConsumeRagFlipFlop = !m_ConsumeRagFlipFlop;
        }
      }
      if (GetRag() && GetCompEM().GetEnergy() == 0 && GetRagQuantity() > 0)
        GetRag().SetQuantity(0);
      RuinRags();
      CalculateQuantity();
      UpdateCheckForReceivingUpgrade();
      AddWet(-m_WaterEvaporationByFireIntensityEx * GetCompEM().GetUpdateInterval());
      Rag rag = GetRag();
      if (rag)
        rag.AddWet(-m_WaterEvaporationByFireIntensityEx * GetCompEM().GetUpdateInterval());
    }
    if (!m_LoopSoundEntity && GetGame() && (!GetGame().IsDedicatedServer()))
      m_LoopSoundEntity = PlaySoundLoop(GetSoundName(), 50);
    // Effect scaling by fuel
    if (!GetGame().IsDedicatedServer())
    {
      UpdateLight();
      UpdateParticle();
    }
  }
References AddWet(), CalculateQuantity(), ConsumeRag(), GetEnergy(), GetGame(), GetRag(), GetRagQuantity(), GetSoundName(), m_BurnTimePerRagEx, m_ConsumeRagFlipFlop, m_LoopSoundEntity, m_RagsUpgradedCount, m_WaterEvaporationByFireIntensityEx, RuinRags(), UpdateCheckForReceivingUpgrade(), UpdateLight(), UpdateMaterial(), and UpdateParticle().
OnWorkStart()
override void FlammableBase::OnWorkStart () inline protected
Definition at line 492 of file Torch.c.
  {
    m_WasLit = true;
    LockRags(true);
    UpdateMaterial();
  }
References LockRags(), m_WasLit, and UpdateMaterial().
OnWorkStop()
override void FlammableBase::OnWorkStop () inline protected
Definition at line 654 of file Torch.c.
  {
    UpdateMaterial();
    if (m_Light)
      m_Light.FadeOut();
    if (m_LoopSoundEntity && GetGame() && (!GetGame().IsDedicatedServer()))
    {
      GetGame().ObjectDelete(m_LoopSoundEntity);
      m_LoopSoundEntity = NULL;
    }
    if (m_FireParticle)
    {
      m_FireParticle.Stop();
      m_FireParticle = NULL;
    }
    CalculateQuantity();
    UpdateCheckForReceivingUpgrade();
    LockRags(false);
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      if (GetRag() && GetCompEM().GetEnergy() == 0 && GetRagQuantity() > 0)
        GetRag().SetQuantity(0);
    }
    TryTransformIntoStick();
  }
References CalculateQuantity(), GetEnergy(), GetGame(), GetRag(), GetRagQuantity(), LockRags(), m_FireParticle, m_Light, m_LoopSoundEntity, Particle::Stop(), TryTransformIntoStick(), UpdateCheckForReceivingUpgrade(), and UpdateMaterial().
RuinRags()
void FlammableBase::RuinRags () inline protected
Definition at line 354 of file Torch.c.
  {
    ItemBase rag = GetRag();
    if (rag)
    {
      rag.SetHealth(1); //does not actually ruin rags, combining would be impossible
    }
  }
References GetRag().
Referenced by OnWork(), and Upgrade().
SetActions()
override void FlammableBase::SetActions () inline protected
Definition at line 712 of file Torch.c.
  {
    super.SetActions();
    AddAction(ActionLightItemOnFire);
  }
References ActionLightItemOnFire(), and AddAction().
SetTorchDecraftResult()
void FlammableBase::SetTorchDecraftResult (string type) inline protected
Definition at line 213 of file Torch.c.
  {
    m_DecraftResult = type; //not persistent for the moment
  }
References m_DecraftResult.
StandUp()
bool FlammableBase::StandUp () inline protected
Definition at line 373 of file Torch.c.
  {
    string surface_type;
    vector position = GetPosition();
    GetGame().SurfaceGetType(position[0], position[2], surface_type);
    bool is_surface_soft = GetGame().IsSurfaceDigable(surface_type);
    if (is_surface_soft && !IsRuined())
    {
      vector ori_rotate = "0 0 0";
      ori_rotate[0] = Math.RandomFloat(0, 360);
      ori_rotate[1] = Math.RandomFloat(0, 10);
      SetOrientation(ori_rotate);
      return true; // I am standing up
    }
    return false; // I am NOT standing up
  }
References GetGame(), GetPosition, and Math::RandomFloat().
Referenced by OnInventoryExit().
StopAllParticles()
void FlammableBase::StopAllParticles () inline protected
Definition at line 499 of file Torch.c.
  {
    if (m_FireParticle)
      m_FireParticle.Stop();
  }
References m_FireParticle, and Particle::Stop().
Referenced by EEDelete(), and TryTransformIntoStick().
TryTransformIntoStick()
void FlammableBase::TryTransformIntoStick () inline protected
Definition at line 448 of file Torch.c.
  {
    PlayerBase player = PlayerBase.Cast(GetHierarchyRootPlayer());
    if (m_IsBeingDestructed || (player && player.IsPlayerDisconnected()))
      return;
    if (CanTransformIntoStick())
    {
      m_IsBeingDestructed = true;
      if (player)
      {
        // Transform object into wooden stick
        StopAllParticles();
        TorchLambda lambda = new TorchLambda(this, m_DecraftResult);
        player.ServerReplaceItemInHandsWithNew(lambda);
      }
      else
      {
        // Create wooden stick and delete Torch
        vector pos = GetPosition();
        vector ori = GetOrientation();
        if (GetType() == "WoodenStick")
          ori = ori + Vector(0, 90, 0);
        ItemBase stick = ItemBase.Cast(GetGame().CreateObjectEx(m_DecraftResult, pos, ECE_PLACE_ON_SURFACE));
        ApplyResultModifications(stick);
        stick.SetPosition(pos);
        stick.PlaceOnSurface();
        if (stick.GetType() == "LongWoodenStick")
        {
          pos = stick.GetPosition() + Vector(0, -0.3, 0);
          stick.SetPosition(pos);
        }
        stick.SetOrientation(ori);
        GetGame().ObjectDelete(this);
      }
    }
  }
References ApplyResultModifications(), CanTransformIntoStick(), ECE_PLACE_ON_SURFACE, GetGame(), GetOrientation(), GetPosition, GetType(), m_DecraftResult, m_IsBeingDestructed, StopAllParticles(), and Vector().
Referenced by EEItemDetached(), and OnWorkStop().
UpdateCheckForReceivingUpgrade()
void FlammableBase::UpdateCheckForReceivingUpgrade () inline protected
Definition at line 181 of file Torch.c.
  {
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      m_CanReceiveUpgrade = GetRagQuantity() > 0 && m_RagsUpgradedCount < GetRagQuantity() || (m_BurnTimePerRagEx * (m_RagsUpgradedCount + GetRagQuantity()) - GetCompEM().GetEnergy()) > 1;
      SetSynchDirty();
    }
  }
References GetGame(), GetRagQuantity(), m_BurnTimePerRagEx, m_CanReceiveUpgrade, and m_RagsUpgradedCount.
Referenced by ConsumeFuelFromBottle(), ConsumeFuelFromGasStation(), ConsumeLard(), EEItemAttached(), EEItemDetached(), OnAttachmentQuantityChangedEx(), OnWork(), OnWorkStop(), and Upgrade().
UpdateLight()
void FlammableBase::UpdateLight () inline protected
Definition at line 522 of file Torch.c.
  {
    if (!m_Light)
    {
      m_Light = TorchLight.Cast(ScriptedLightBase.CreateLight(TorchLight, Vector(0, 0, 0), 1));
      m_Light.AttachOnObject(this, m_ParticleLocalPos + Vector(0, 0.2, 0));
    }
    if (m_FireParticle)
    {
      Object direct_particle = m_FireParticle.GetDirectParticleEffect();
      if (direct_particle && direct_particle != m_Light.GetAttachmentParent())
        m_Light.AttachOnObject(direct_particle, Vector(0, 0.2, 0));
    }
    float update_interval = GetCompEM().GetUpdateInterval();
    if (GetQuantity() <= m_StartFadeOutOfLightAtQuantityEx)
    {
      float brightness_coef = GetQuantity() / m_StartFadeOutOfLightAtQuantityEx;
      float radius_coef = GetQuantity() / m_StartFadeOutOfLightAtQuantityEx;
      if (radius_coef < m_StartFadeOutOfLightAtQuantityEx / 10)
        radius_coef = m_StartFadeOutOfLightAtQuantityEx / 10;
      if (brightness_coef < m_StartFadeOutOfLightAtQuantityEx / 10)
        brightness_coef = m_StartFadeOutOfLightAtQuantityEx / 10;
      m_Light.FadeBrightnessTo(m_Light.m_TorchBrightness * brightness_coef, update_interval);
      m_Light.FadeRadiusTo(m_Light.m_TorchRadius * radius_coef, update_interval);
    }
    else
    {
      m_Light.FadeBrightnessTo(m_Light.m_TorchBrightness, update_interval);
      m_Light.FadeRadiusTo(m_Light.m_TorchRadius, update_interval);
    }
  }
References Particle::GetDirectParticleEffect(), GetQuantity(), m_FireParticle, m_Light, m_ParticleLocalPos, m_StartFadeOutOfLightAtQuantityEx, and Vector().
Referenced by OnWork().
UpdateMaterial()
void FlammableBase::UpdateMaterial () inline protected
Definition at line 760 of file Torch.c.
  {
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      if (GetCompEM().IsWorking())
      {
        if (GetBurningMaterial())
          SetObjectMaterial(0, GetBurningMaterial());
      }
      else if (m_WasLit)
      {
        if (GetBurntMaterial())
          SetObjectMaterial(0, GetBurntMaterial());
      }
    }
  }
References GetBurningMaterial(), GetBurntMaterial(), GetGame(), and m_WasLit.
Referenced by OnStoreLoad(), OnWork(), OnWorkStart(), and OnWorkStop().
UpdateParticle()
void FlammableBase::UpdateParticle () inline protected
Definition at line 620 of file Torch.c.
  {
    if (GetQuantity() < 40)
    {
      if (!m_FireParticle)
        m_FireParticle = ParticleManager.GetInstance().PlayOnObject(ParticleList.TORCH_T1, this, m_ParticleLocalPos);
      float scale = GetQuantity() / 40;
      if (scale > 1)
        scale = 1;
      if (scale < 0.25)
        scale = 0.25;
      m_FireParticle.ScaleParticleParamFromOriginal(EmitorParam.SIZE, scale);
      m_FireParticle.ScaleParticleParamFromOriginal(EmitorParam.VELOCITY, scale);
      m_FireParticle.ScaleParticleParamFromOriginal(EmitorParam.VELOCITY_RND, scale);
    }
    else
    {
      if (!m_FireParticle || m_FireParticle.GetParticleID() != ParticleList.TORCH_T2)
      {
        // Executes once when fire particle starts or changes
        if (m_FireParticle)
          m_FireParticle.Stop();
        m_FireParticle = ParticleManager.GetInstance().PlayOnObject(ParticleList.TORCH_T2, this, m_ParticleLocalPos);
      }
    }
  }
References Particle::GetParticleID(), GetQuantity(), m_FireParticle, m_ParticleLocalPos, ParticleManager(), Particle::ScaleParticleParamFromOriginal(), Particle::Stop(), ParticleList::TORCH_T1, and ParticleList::TORCH_T2.
Referenced by OnWork().
Upgrade()
void FlammableBase::Upgrade (ItemBase source) inline protected
Definition at line 272 of file Torch.c.
  {
    if (!GetRag())
      return;
    RuinRags();
    LockRags(true);
    float torchCurrentEnergy = GetCompEM().GetEnergy();
    float sourceQuantity = 100000;//for upgrade from environment(gas pump)
    if (source)
      sourceQuantity = source.GetQuantity();
    float maxOverallCapacity = GetRagQuantity() * 2 * m_BurnTimePerRagEx;
    //float maxUpgradeCapacity = GetRagQuantity() * m_BurnTimePerRagEx;
    float currentlyUpgraded = Math.Max(0, torchCurrentEnergy - (GetRagQuantity() * m_BurnTimePerRagEx));
    //float freeUpgradeCapacity = maxUpgradeCapacity - currentlyUpgraded;
    float freeUpgradeCapacity = maxOverallCapacity - torchCurrentEnergy;
    float upgradeQuantity = Math.Min(freeUpgradeCapacity, sourceQuantity);
    int upgradedRags = Math.Ceil((upgradeQuantity + currentlyUpgraded) / m_BurnTimePerRagEx);
    upgradedRags = Math.Min(GetRagQuantity(), upgradedRags);
    m_RagsUpgradedCount = upgradedRags;
    GetCompEM().AddEnergy(upgradeQuantity);
    m_ConsumeRagFlipFlop = 0;//consume fuel first
    if (source)
      source.AddQuantity(-upgradeQuantity);
    CalculateQuantity();
    UpdateCheckForReceivingUpgrade();
  }
References CalculateQuantity(), Math::Ceil(), GetRag(), GetRagQuantity(), LockRags(), m_BurnTimePerRagEx, m_ConsumeRagFlipFlop, m_RagsUpgradedCount, Math::Max(), Math::Min(), RuinRags(), and UpdateCheckForReceivingUpgrade().
Member Data Documentation
m_BurnTimePerFullFuelDoseEx
float FlammableBase::m_BurnTimePerFullFuelDoseEx private
Definition at line 15 of file Torch.c.
Referenced by ConsumeFuelFromBottle(), ConsumeFuelFromGasStation(), and Init().
m_BurnTimePerFullLardEx
float FlammableBase::m_BurnTimePerFullLardEx private
Definition at line 14 of file Torch.c.
Referenced by ConsumeLard(), and Init().
m_BurnTimePerRagEx
float FlammableBase::m_BurnTimePerRagEx private
Definition at line 13 of file Torch.c.
Referenced by CraftingInit(), Init(), OnAttachmentQuantityChangedEx(), OnWork(), UpdateCheckForReceivingUpgrade(), and Upgrade().
m_CanReceiveUpgrade
bool FlammableBase::m_CanReceiveUpgrade private
Definition at line 10 of file Torch.c.
Referenced by CanReceiveUpgrade(), CraftingInit(), and UpdateCheckForReceivingUpgrade().
m_ConsumeRagFlipFlop
bool FlammableBase::m_ConsumeRagFlipFlop private
Definition at line 22 of file Torch.c.
Referenced by OnWork(), and Upgrade().
m_DecraftResult
string FlammableBase::m_DecraftResult = "WoodenStick" private
Definition at line 25 of file Torch.c.
Referenced by BroomBase::Init(), SetTorchDecraftResult(), and TryTransformIntoStick().
m_FireParticle
Particle FlammableBase::m_FireParticle private
Definition at line 9 of file Torch.c.
Referenced by OnWorkStop(), StopAllParticles(), UpdateLight(), BroomBase::UpdateParticle(), and UpdateParticle().
m_IsBeingDestructed
bool FlammableBase::m_IsBeingDestructed = false private
Definition at line 11 of file Torch.c.
Referenced by EEItemDetached(), and TryTransformIntoStick().
m_Light
TorchLight FlammableBase::m_Light private
Definition at line 26 of file Torch.c.
Referenced by OnWorkStop(), and UpdateLight().
m_LoopSoundEntity
SoundOnVehicle FlammableBase::m_LoopSoundEntity private
Definition at line 8 of file Torch.c.
Referenced by EEDelete(), OnWork(), and OnWorkStop().
m_MaxConsumableFuelQuantityEx
float FlammableBase::m_MaxConsumableFuelQuantityEx private
Definition at line 17 of file Torch.c.
Referenced by ConsumeFuelFromBottle(), and Init().
m_MaxConsumableLardQuantityEx
float FlammableBase::m_MaxConsumableLardQuantityEx private
Definition at line 16 of file Torch.c.
Referenced by ConsumeLard(), and Init().
m_ParticleLocalPos
vector FlammableBase::m_ParticleLocalPos = Vector(0, 0.50, 0) private
Definition at line 23 of file Torch.c.
Referenced by BroomBase::Init(), UpdateLight(), BroomBase::UpdateParticle(), and UpdateParticle().
m_RagsUpgradedCount
int FlammableBase::m_RagsUpgradedCount private
Definition at line 21 of file Torch.c.
Referenced by DeferredInit(), LockRags(), OnWork(), UpdateCheckForReceivingUpgrade(), and Upgrade().
m_StartFadeOutOfLightAtQuantityEx
int FlammableBase::m_StartFadeOutOfLightAtQuantityEx = 3 private
Definition at line 19 of file Torch.c.
Referenced by UpdateLight().
m_UTSLConstant
ref UniversalTemperatureSourceLambdaConstant FlammableBase::m_UTSLConstant protected
Definition at line 31 of file Torch.c.
Referenced by EEInit().
m_UTSource
ref UniversalTemperatureSource FlammableBase::m_UTSource protected
Definition at line 29 of file Torch.c.
Referenced by EEInit(), OnSwitchOff(), and OnSwitchOn().
m_UTSSettings
ref UniversalTemperatureSourceSettings FlammableBase::m_UTSSettings protected
Definition at line 30 of file Torch.c.
Referenced by EEInit().
m_WasLit
bool FlammableBase::m_WasLit private
Definition at line 27 of file Torch.c.
Referenced by OnStoreLoad(), OnStoreSave(), OnWorkStart(), and UpdateMaterial().
m_WaterEvaporationByFireIntensityEx
float FlammableBase::m_WaterEvaporationByFireIntensityEx = 0.001 private
Definition at line 18 of file Torch.c.
Referenced by OnWork().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Torch.c