DayZ: LoginScreenBase Class Reference
LoginScreenBase Class Reference
Protected Member Functions
bool CanChangeHintPage (float timeAccu)
Protected Attributes
TextWidget m_txtDescription
TextWidget m_txtLabel
ButtonWidget m_btnLeave
bool m_IsRespawn
Private Member Functions
void LoginTimeBase ()
void ~LoginTimeBase ()
override Widget Init ()
override bool OnClick (Widget w, int x, int y, int button)
void Show ()
void Hide ()
void SetTime (int time)
void SetStatus (string status)
void SetRespawn (bool value)
bool IsRespawn ()
Private Attributes
ref FullTimeData m_FullTime
Detailed Description
Definition at line 195 of file DayZGame.c.
Constructor & Destructor Documentation
~LoginTimeBase()
void LoginScreenBase::~LoginTimeBase () inline private
Definition at line 213 of file DayZGame.c.
  {
    if (g_Game)
      g_Game.SetKeyboardHandle(null);
    m_FullTime = null;
  }
References g_Game.
Member Function Documentation
CanChangeHintPage()
bool LoginScreenBase::CanChangeHintPage (float timeAccu) inline protected
Definition at line 312 of file DayZGame.c.
  {
    return timeAccu >= GameConstants.LOADING_SCREEN_HINT_INTERVAL && m_FullTime.m_Seconds >= GameConstants.LOADING_SCREEN_HINT_INTERVAL_MIN;
  }
References GameConstants::LOADING_SCREEN_HINT_INTERVAL, and GameConstants::LOADING_SCREEN_HINT_INTERVAL_MIN.
Referenced by UIScriptedMenu::Update().
Hide()
void LoginScreenBase::Hide () inline private
Definition at line 264 of file DayZGame.c.
  {
    if (layoutRoot)
      layoutRoot.Show(false);
    m_HintPanel = null;
  }
References m_HintPanel.
Init()
override Widget LoginScreenBase::Init () inline private
Definition at line 220 of file DayZGame.c.
  {
    layoutRoot = GetGame().GetWorkspace().CreateWidgets("gui/layouts/dialog_login_time.layout");
    m_txtDescription = TextWidget.Cast(layoutRoot.FindAnyWidget("txtDescription"));
    m_txtLabel = TextWidget.Cast(layoutRoot.FindAnyWidget("txtLabel"));
    m_btnLeave = ButtonWidget.Cast(layoutRoot.FindAnyWidget("btnLeave"));
    m_txtDescription.Show(true);
    layoutRoot.FindAnyWidget("notification_root").Show(false);
#ifdef PLATFORM_CONSOLE
    layoutRoot.FindAnyWidget("toolbar_bg").Show(true);
    RichTextWidget toolbar_b = RichTextWidget.Cast(layoutRoot.FindAnyWidget("BackIcon"));
    toolbar_b.SetText(InputUtils.GetRichtextButtonIconFromInputAction("UAUIBack", "", EUAINPUT_DEVICE_CONTROLLER, InputUtils.ICON_SCALE_TOOLBAR));
#ifdef PLATFORM_XBOX
#ifdef BUILD_EXPERIMENTAL
    layoutRoot.FindAnyWidget("notification_root").Show(true);
#endif
#endif
#endif
    return layoutRoot;
  }
References GetGame(), InputUtils::GetRichtextButtonIconFromInputAction(), InputUtils::ICON_SCALE_TOOLBAR, and m_btnLeave.
IsRespawn()
bool LoginScreenBase::IsRespawn () inline private
Definition at line 307 of file DayZGame.c.
  {
    return m_IsRespawn;
  }
LoginTimeBase()
void LoginScreenBase::LoginTimeBase () inline private
Definition at line 205 of file DayZGame.c.
  {
    g_Game.SetKeyboardHandle(this);
    m_IsRespawn = false;
    m_FullTime = new FullTimeData();
  }
References g_Game.
OnClick()
override bool LoginScreenBase::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 244 of file DayZGame.c.
  {
    super.OnClick(w, x, y, button);
    if (w == m_btnLeave)
    {
      Leave();
      return true;
    }
    return false;
  }
References m_btnLeave, x, and y.
SetRespawn()
void LoginScreenBase::SetRespawn (bool value) inline private
Definition at line 302 of file DayZGame.c.
  {
    m_IsRespawn = value;
  }
SetStatus()
void LoginScreenBase::SetStatus (string status) inline private
Definition at line 297 of file DayZGame.c.
  {
    m_txtDescription.SetText(status);
  }
SetTime()
void LoginScreenBase::SetTime (int time) inline private
Definition at line 271 of file DayZGame.c.
  {
    string text = "";
    TimeConversions.ConvertSecondsToFullTime(time, m_FullTime);
    if (!m_IsRespawn)
      text = "#menu_loading_in_";
    else
      text = "#dayz_game_spawning_in_";
    if (m_FullTime.m_Days > 0)
      text += "dhms";
    else if (m_FullTime.m_Hours > 0)
      text += "hms";
    else if (m_FullTime.m_Minutes > 0)
      text += "ms";
    else
      text += "s";
    text = Widget.TranslateString(text);
    text = string.Format(text, m_FullTime.m_Seconds, m_FullTime.m_Minutes, m_FullTime.m_Hours, m_FullTime.m_Days);
    m_txtLabel.SetText(text);
    if (m_IsRespawn && time <= 1)
      GetGame().SetLoginTimerFinished();
  }
References GetGame().
Show()
void LoginScreenBase::Show () inline private
Definition at line 255 of file DayZGame.c.
  {
    if (layoutRoot)
    {
      layoutRoot.Show(true);
      m_HintPanel = new UiHintPanelLoading(layoutRoot.FindAnyWidget("hint_frame0"));
    }
  }
References m_HintPanel.
Member Data Documentation
m_btnLeave
ButtonWidget LoginScreenBase::m_btnLeave protected
Definition at line 199 of file DayZGame.c.
m_FullTime
ref FullTimeData LoginScreenBase::m_FullTime private
Definition at line 203 of file DayZGame.c.
m_IsRespawn
bool LoginScreenBase::m_IsRespawn protected
Definition at line 201 of file DayZGame.c.
m_txtDescription
TextWidget LoginScreenBase::m_txtDescription protected
Definition at line 197 of file DayZGame.c.
m_txtLabel
TextWidget LoginScreenBase::m_txtLabel protected
Definition at line 198 of file DayZGame.c.
The documentation for this class was generated from the following file:
scripts/3_Game/DayZGame.c