DayZ: ActionAttachPowerSourceToPanel Class Reference
ActionAttachPowerSourceToPanel Class Reference
DEPRECATED.
Protected Member Functions
void OnExecuteImpl (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
override void OnEndClient (ActionData action_data)
Private Member Functions
void ActionAttachPowerSourceToPanel ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Detailed Description
DEPRECATED.
Definition at line 2 of file ActionAttachPowerSourceToPanel.c.
Constructor & Destructor Documentation
ActionAttachPowerSourceToPanel()
void ActionAttachPowerSourceToPanel::ActionAttachPowerSourceToPanel () inline private
Definition at line 4 of file ActionAttachPowerSourceToPanel.c.
  {
    m_Text = "#attach";
  }
References m_Text.
Member Function Documentation
ActionCondition()
override bool ActionAttachPowerSourceToPanel::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 15 of file ActionAttachPowerSourceToPanel.c.
  {
    EntityAI target_entity = EntityAI.Cast(target.GetObject());
    if (player && target_entity && item)
    {
      if (target_entity.IsStaticTransmitter() && target_entity.GetInventory().AttachmentCount() == 0) //has any power source attachment attached
        return true;
    }
    return false;
  }
CreateConditionComponents()
override void ActionAttachPowerSourceToPanel::CreateConditionComponents () inline private
Definition at line 9 of file ActionAttachPowerSourceToPanel.c.
  {
    m_ConditionItem = new CCINonRuined;
    m_ConditionTarget = new CCTNonRuined(UAMaxDistances.DEFAULT);
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnEndClient()
override void ActionAttachPowerSourceToPanel::OnEndClient (ActionData action_data) inline protected
Definition at line 52 of file ActionAttachPowerSourceToPanel.c.
  {
    // Probably not needed since attaching is done server side.
    /*
      EntityAI target_entity = EntityAI.Cast( action_data.m_Target.GetObject() );
      EntityAI item_entity = EntityAI.Cast( action_data.m_MainItem );
      //find inventory location for attachment
      InventoryLocation target_location = new InventoryLocation;
      if( target_entity.GetInventory().FindFirstFreeLocationForNewEntity( item_entity.GetType(), FindInventoryLocationType.ATTACHMENT, target_location ) )
      {
      //target_entity.PredictiveTakeEntityToTargetAttachmentEx( target_entity, item_entity, target_location.GetSlot() );
      target_entity.LocalTakeEntityAsAttachmentEx( item_entity, target_location.GetSlot() );
      }
    */
  }
OnExecuteClient()
override void ActionAttachPowerSourceToPanel::OnExecuteClient (ActionData action_data) inline protected
Definition at line 38 of file ActionAttachPowerSourceToPanel.c.
  {
    ClearInventoryReservationEx(action_data);
    OnExecuteImpl(action_data);
  }
References ClearInventoryReservationEx(), and OnExecuteImpl().
OnExecuteImpl()
void ActionAttachPowerSourceToPanel::OnExecuteImpl (ActionData action_data) inline protected
Definition at line 27 of file ActionAttachPowerSourceToPanel.c.
  {
    EntityAI target_entity = EntityAI.Cast(action_data.m_Target.GetObject());
    EntityAI item_entity = action_data.m_MainItem;
    //find inventory location for attachment
    InventoryLocation target_location = new InventoryLocation;
    if (target_entity.GetInventory().FindFirstFreeLocationForNewEntity(item_entity.GetType(), FindInventoryLocationType.ATTACHMENT, target_location))
      action_data.m_Player.PredictiveTakeEntityToTargetAttachmentEx(target_entity, item_entity, target_location.GetSlot());
  }
Referenced by OnExecuteClient(), and OnExecuteServer().
OnExecuteServer()
override void ActionAttachPowerSourceToPanel::OnExecuteServer (ActionData action_data) inline protected
Definition at line 44 of file ActionAttachPowerSourceToPanel.c.
  {
    if (GetGame().IsMultiplayer())
      return; // multiplayer handled on client side via OnExecuteClient
    else
      OnExecuteImpl(action_data); // single player
  }
References GetGame(), and OnExecuteImpl().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionAttachPowerSourceToPanel.c