DayZ: Land_Underground_Panel_Lever Class Reference
Land_Underground_Panel_Lever Class Reference
Private Member Functions
override void SetActions ()
void ResetPhase (EntityAI target)
override void OnPanelUsedSynchronized ()
override void Interact ()
Detailed Description
Definition at line 1 of file Land_Underground_Panel_Lever.c.
Member Function Documentation
Interact()
override void Land_Underground_Panel_Lever::Interact () inline private
Definition at line 23 of file Land_Underground_Panel_Lever.c.
  {
    super.Interact();
    GetGame().RegisterNetworkStaticObject(this);
    GetGame().RegisterNetworkStaticObject(GetLinkedDoor());
  }
References GetGame(), and GetLinkedDoor().
OnPanelUsedSynchronized()
override void Land_Underground_Panel_Lever::OnPanelUsedSynchronized () inline private
Definition at line 15 of file Land_Underground_Panel_Lever.c.
  {
    super.OnPanelUsedSynchronized();
    SetAnimationPhase("PanelLever", 1);
    GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(ResetPhase, 3000, false, this);
    OnLEDStateChanged();
  }
References CALL_CATEGORY_SYSTEM, GetGame(), OnLEDStateChanged(), and ResetPhase().
ResetPhase()
void Land_Underground_Panel_Lever::ResetPhase (EntityAI target) inline private
Definition at line 10 of file Land_Underground_Panel_Lever.c.
  {
    target.SetAnimationPhaseNow("PanelLever", 0);
  }
Referenced by OnPanelUsedSynchronized().
SetActions()
override void Land_Underground_Panel_Lever::SetActions () inline private
Definition at line 3 of file Land_Underground_Panel_Lever.c.
  {
    super.SetActions();
    AddAction(ActionUseUndergroundLever);
  }
References AddAction().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/Building/Underground/Entrance/Land_Underground_Panel_Lever.c