DayZ: ActionDrainLiquid Class Reference
ActionDrainLiquid Class Reference
Private Member Functions
void ActionDrainLiquid ()
override void CreateConditionComponents ()
override bool HasProneException ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override void OnStartAnimationLoop (ActionData action_data)
override void OnEndAnimationLoop (ActionData action_data)
override void OnEnd (ActionData action_data)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 11 of file ActionDrainLiquid.c.
Constructor & Destructor Documentation
ActionDrainLiquid()
void ActionDrainLiquid::ActionDrainLiquid () inline private
Definition at line 13 of file ActionDrainLiquid.c.
  {
    m_CallbackClass = ActionDrainLiquidCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_EMPTY_VESSEL;
    m_CommandUIDProne = DayZPlayerConstants.CMD_ACTIONFB_EMPTY_VESSEL;
    m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
    m_Text = "#drain_liquid";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, m_SpecialtyWeight, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionDrainLiquid::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 33 of file ActionDrainLiquid.c.
  {
    ItemBase target_item = ItemBase.Cast(target.GetObject());
    if (target_item && item)
      return Liquid.CanTransfer(target_item, item);
    return false;
  }
References Liquid::CanTransfer().
CreateConditionComponents()
override void ActionDrainLiquid::CreateConditionComponents () inline private
Definition at line 22 of file ActionDrainLiquid.c.
  {
    m_ConditionItem = new CCINonRuined;
    m_ConditionTarget = new CCTNonRuined(UAMaxDistances.DEFAULT);
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
HasProneException()
override bool ActionDrainLiquid::HasProneException () inline private
Definition at line 28 of file ActionDrainLiquid.c.
  {
    return true;
  }
OnEnd()
override void ActionDrainLiquid::OnEnd (ActionData action_data) inline private
Definition at line 69 of file ActionDrainLiquid.c.
  {
    if (!GetGame().IsMultiplayer() || GetGame().IsServer())
    {
      Bottle_Base target_vessel = Bottle_Base.Cast(action_data.m_Target.GetObject());
      Param1<bool> play = new Param1<bool>(false);
      GetGame().RPCSingleParam(target_vessel, SoundTypeBottle.EMPTYING, play, true);
    }
  }
References GetGame().
OnEndAnimationLoop()
override void ActionDrainLiquid::OnEndAnimationLoop (ActionData action_data) inline private
Definition at line 59 of file ActionDrainLiquid.c.
  {
    if (!GetGame().IsMultiplayer() || GetGame().IsServer())
    {
      Bottle_Base target_vessel = Bottle_Base.Cast(action_data.m_Target.GetObject());
      Param1<bool> play = new Param1<bool>(false);
      GetGame().RPCSingleParam(target_vessel, SoundTypeBottle.EMPTYING, play, true);
    }
  }
References GetGame().
OnFinishProgressServer()
override void ActionDrainLiquid::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 42 of file ActionDrainLiquid.c.
  {
    action_data.m_Player.GetSoftSkillsManager().AddSpecialty(m_SpecialtyWeight);
  }
References m_SpecialtyWeight.
OnStartAnimationLoop()
override void ActionDrainLiquid::OnStartAnimationLoop (ActionData action_data) inline private
Definition at line 48 of file ActionDrainLiquid.c.
  {
    if (!GetGame().IsMultiplayer() || GetGame().IsServer())
    {
      Bottle_Base vessel_in_hands = Bottle_Base.Cast(action_data.m_Target.GetObject());
      Param1<bool> play = new Param1<bool>(true);
      GetGame().RPCSingleParam(vessel_in_hands, SoundTypeBottle.EMPTYING, play, true);
    }
  }
References GetGame().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionDrainLiquid.c