DayZ: EmoteBase Class Reference
EmoteBase Class Reference
Protected Member Functions
bool EmoteCondition (int stancemask)
bool CanBeCanceledNormally (notnull EmoteCB callback)
bool EmoteFBStanceCheck (int stancemask)
Checks for valid stance mask.
bool DetermineOverride (out int callback_ID, out int stancemask, out bool is_fullbody)
void OnBeforeStandardCallbackCreated (int callback_ID, int stancemask, bool is_fullbody)
void OnCallbackEnd ()
bool EmoteStartOverride (typename callbacktype, int id, int mask, bool fullbody)
void SetOwnerPlayer (PlayerBase player)
PlayerBase GetOwnerPlayer ()
int GetID ()
string GetInputActionName ()
int GetStanceMaskAdditive ()
int GetStanceMaskFullbody ()
int GetAdditiveCallbackUID ()
int GetFullbodyCallbackUID ()
bool GetHideItemInHands ()
void EmoteLyingDown ()
override bool EmoteCondition (int stancemask)
Protected Attributes
PlayerBase m_Player
int m_ID = -1
string m_InputActionName = ""
int m_StanceMaskAdditive = 0
int m_StanceMaskFullbody = 0
int m_AdditiveCallbackUID = 0
int m_FullbodyCallbackUID = 0
bool m_HideItemInHands = false
const float WATER_DEPTH = 0.15
Private Member Functions
void EmoteGreeting ()
void EmoteHeart ()
void EmotePoint ()
void EmoteThumb ()
void EmoteThroat ()
void EmoteSalute ()
void EmoteDabbing ()
void EmoteClap ()
void EmoteWatching ()
void EmoteListening ()
void EmoteLookAtMe ()
void EmoteMove ()
void EmoteCome ()
void EmoteCampfireSit ()
void EmoteSitB ()
void EmoteRPSRock ()
void EmoteRPSScisors ()
void EmoteShake ()
void EmoteSuicide ()
override bool DetermineOverride (out int callback_ID, out int stancemask, out bool is_fullbody)
override bool EmoteCondition (int stancemask)
override bool CanBeCanceledNormally (notnull EmoteCB callback)
override void OnBeforeStandardCallbackCreated (int callback_ID, int stancemask, bool is_fullbody)
override void OnCallbackEnd ()
Detailed Description
Definition at line 1 of file EmoteBase.c.
Member Function Documentation
CanBeCanceledNormally() [1/2]
bool EmoteBase::CanBeCanceledNormally (notnull EmoteCB callback) inline protected
Definition at line 17 of file EmoteBase.c.
  {
    return true;
  }
CanBeCanceledNormally() [2/2]
override bool EmoteBase::CanBeCanceledNormally (notnull EmoteCB callback) inline private
Definition at line 667 of file EmoteClasses.c.
  {
    int state = callback.GetState();
    if (state > HumanCommandActionCallback.STATE_LOOP_LOOP) //Cannot be canceled once started
      return false;
    return super.CanBeCanceledNormally(callback);;
  }
DetermineOverride() [1/2]
bool EmoteBase::DetermineOverride (out int callback_ID, out int stancemask, out bool is_fullbody) inline protected
Definition at line 39 of file EmoteBase.c.
  {
    return false;
  }
DetermineOverride() [2/2]
override bool EmoteBase::DetermineOverride (out int callback_ID, out int stancemask, out bool is_fullbody) inline private
Definition at line 581 of file EmoteClasses.c.
  {
    is_fullbody = true;
    callback_ID = -1;
    stancemask = 0;
    string suicideStr;
    ItemBase weapon;
    weapon = m_Player.GetItemInHands();
    if (weapon)
    {
      if (weapon.ConfigIsExisting("suicideAnim"))
        suicideStr = weapon.ConfigGetString("suicideAnim");
      if (weapon.IsKindOf("Pistol_Base"))
      {
        callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_PISTOL;
        stancemask = DayZPlayerConstants.STANCEMASK_CROUCH;
        //m_Player.OverrideShootFromCamera(false);
      }
      else if (Weapon_Base.Cast(weapon)) //long firearms
      {
        callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_RIFLE;
        stancemask = DayZPlayerConstants.STANCEMASK_CROUCH;
        //m_Player.OverrideShootFromCamera(false);
      }
      else
      {
        switch (suicideStr)
        {
        case "onehanded":
          callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_1HD;
          stancemask = DayZPlayerConstants.STANCEMASK_CROUCH;
          break;
        case "fireaxe":
          callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_FIREAXE;
          stancemask = DayZPlayerConstants.STANCEMASK_ERECT;
          break;
        case "pitchfork":
          callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_PITCHFORK;
          stancemask = DayZPlayerConstants.STANCEMASK_ERECT;
          break;
        case "sword":
          callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_SWORD;
          stancemask = DayZPlayerConstants.STANCEMASK_ERECT;
          break;
        case "spear":
          callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_SPEAR;
          stancemask = DayZPlayerConstants.STANCEMASK_ERECT;
          break;
        case "woodaxe":
          callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_WOODAXE;
          stancemask = DayZPlayerConstants.STANCEMASK_ERECT;
          break;
        case "sickle":
          callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_SICKLE;
          stancemask = DayZPlayerConstants.STANCEMASK_ERECT;
          break;
        case "hoe":
          callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_HOE;
          stancemask = DayZPlayerConstants.STANCEMASK_ERECT;
          break;
        }
      }
    }
    if (callback_ID > -1)
      return true;
    return false;
  }
References m_Player.
EmoteCampfireSit()
void EmoteBase::EmoteCampfireSit () inline private
Definition at line 430 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_CAMPFIRE;
    m_InputActionName = "EmoteCampfireSit";
    m_StanceMaskAdditive = 0;
    m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_CROUCH;
    m_AdditiveCallbackUID = 0;
    m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_CAMPFIRE;
    m_HideItemInHands = true;
  }
References EmoteConstants::ID_EMOTE_CAMPFIRE, and m_ID.
EmoteClap()
void EmoteBase::EmoteClap () inline private
Definition at line 245 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_CLAP;
    m_InputActionName = "EmoteClap";
    m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    m_StanceMaskFullbody = 0;
    m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_CLAP;
    m_FullbodyCallbackUID = 0;
    m_HideItemInHands = true;
  }
References EmoteConstants::ID_EMOTE_CLAP, and m_ID.
EmoteCome()
void EmoteBase::EmoteCome () inline private
Definition at line 385 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_COME;
    m_InputActionName = "EmoteCome";
    m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
    m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_COME;
    m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_COME;
    m_HideItemInHands = false;
  }
References EmoteConstants::ID_EMOTE_COME, and m_ID.
EmoteCondition() [1/3]
bool EmoteBase::EmoteCondition (int stancemask) inline protected
Definition at line 12 of file EmoteBase.c.
  {
    return true;
  }
EmoteCondition() [2/3]
override bool EmoteBase::EmoteCondition (int stancemask) inline protected
Definition at line 72 of file EmoteClasses.c.
  {
    vector water_info = HumanCommandSwim.WaterLevelCheck(m_Player, m_Player.GetPosition() - (m_Player.GetDirection() * 0.9));
    if (water_info[0] < WATER_DEPTH) //is player able to lay down without "drowning"?
      return true;
    return false;
  }
References HumanCommandSwim(), m_Player, and WATER_DEPTH.
EmoteCondition() [3/3]
override bool EmoteBase::EmoteCondition (int stancemask) inline private
Definition at line 657 of file EmoteClasses.c.
  {
    ItemBase itemInHands = m_Player.GetItemInHands();
    if (!itemInHands.CanBeUsedForSuicide())
      return false;
    return super.EmoteCondition(stancemask);
  }
References m_Player.
EmoteDabbing()
void EmoteBase::EmoteDabbing () inline private
Definition at line 217 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_DABBING;
    //m_InputActionName = "EmoteDabbing";
    m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    m_StanceMaskFullbody = 0;
    m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_DABBING;
    m_FullbodyCallbackUID = 0;
    m_HideItemInHands = true;
  }
References EmoteConstants::ID_EMOTE_DABBING, and m_ID.
EmoteFBStanceCheck()
bool EmoteBase::EmoteFBStanceCheck (int stancemask) inline protected
Checks for valid stance mask.
Definition at line 23 of file EmoteBase.c.
  {
    int stanceIdx = DayZPlayerUtils.ConvertStanceMaskToStanceIdx(stancemask);
    if (!m_Player)
    {
      ErrorEx("No player for 'PlayerCanChangeStance'");
      return false;
    }
    if (stanceIdx != -1 && !DayZPlayerUtils.PlayerCanChangeStance(m_Player, stanceIdx))
      return false;
    return true;
  }
References DayZPlayerUtils(), ErrorEx, and m_Player.
EmoteGreeting()
void EmoteBase::EmoteGreeting () inline private
Definition at line 4 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_GREETING;
    m_InputActionName = "EmoteGreeting";
    m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
    m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_GREETING;
    m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_GREETING;
    m_HideItemInHands = false;
  }
References EmoteConstants::ID_EMOTE_GREETING, and m_ID.
EmoteHeart()
void EmoteBase::EmoteHeart () inline private
Definition at line 32 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_HEART;
    m_InputActionName = "EmoteHeart";
    m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
    m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_HEART;
    m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_HEART;
    m_HideItemInHands = true;
  }
References EmoteConstants::ID_EMOTE_HEART, and m_ID.
EmoteListening()
void EmoteBase::EmoteListening () inline private
Definition at line 301 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_LISTENING;
    m_InputActionName = "EmoteListening";
    m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
    m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_LISTENING;
    m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_LISTENING;
    m_HideItemInHands = false;
  }
References EmoteConstants::ID_EMOTE_LISTENING, and m_ID.
EmoteLookAtMe()
void EmoteBase::EmoteLookAtMe () inline private
Definition at line 329 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_LOOKATME;
    m_InputActionName = "EmoteLookAtMe";
    m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
    m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_LOOKATME;
    m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_LOOKATME;
    m_HideItemInHands = false;
  }
References EmoteConstants::ID_EMOTE_LOOKATME, and m_ID.
EmoteLyingDown()
void EmoteBase::EmoteLyingDown () inline protected
Definition at line 61 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_LYINGDOWN;
    m_InputActionName = "EmoteLyingDown";
    m_StanceMaskAdditive = 0;
    m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_CROUCH;
    m_AdditiveCallbackUID = 0;
    m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_LYINGDOWN;
    m_HideItemInHands = true;
  }
References EmoteConstants::ID_EMOTE_LYINGDOWN, and m_ID.
EmoteMove()
void EmoteBase::EmoteMove () inline private
Definition at line 357 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_MOVE;
    m_InputActionName = "EmoteMove";
    m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
    m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_MOVE;
    m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_MOVE;
    m_HideItemInHands = false;
  }
References EmoteConstants::ID_EMOTE_MOVE, and m_ID.
EmotePoint()
void EmoteBase::EmotePoint () inline private
Definition at line 97 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_POINT;
    m_InputActionName = "EmotePoint";
    m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
    m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_POINT;
    m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_POINT;
    m_HideItemInHands = false;
  }
References EmoteConstants::ID_EMOTE_POINT, and m_ID.
EmoteRPSRock()
void EmoteBase::EmoteRPSRock () inline private
Definition at line 486 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_RPS_R;
    m_InputActionName = "EmoteRPSRock";
    m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_ERECT;
    m_StanceMaskFullbody = 0;
    m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_RPS;
    m_FullbodyCallbackUID = 0;
    m_HideItemInHands = false;
  }
References EmoteConstants::ID_EMOTE_RPS_R, and m_ID.
EmoteRPSScisors()
void EmoteBase::EmoteRPSScisors () inline private
Definition at line 514 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_RPS_S;
    m_InputActionName = "EmoteRPSScisors";
    m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_ERECT;
    m_StanceMaskFullbody = 0;
    m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_RPS;
    m_FullbodyCallbackUID = 0;
    m_HideItemInHands = false;
  }
References EmoteConstants::ID_EMOTE_RPS_S, and m_ID.
EmoteSalute()
void EmoteBase::EmoteSalute () inline private
Definition at line 189 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_SALUTE;
    m_InputActionName = "EmoteSalute";
    m_StanceMaskAdditive = 0;
    m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_ERECT;
    m_AdditiveCallbackUID = 0;
    m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_SALUTE;
    m_HideItemInHands = true;
  }
References EmoteConstants::ID_EMOTE_SALUTE, and m_ID.
EmoteShake()
void EmoteBase::EmoteShake () inline private
Definition at line 542 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_SHAKE;
    m_InputActionName = "EmoteShake";
    m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
    m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_SHAKEHEAD;
    m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_SHAKEHEAD;
    m_HideItemInHands = false;
  }
References EmoteConstants::ID_EMOTE_SHAKE, and m_ID.
EmoteSitB()
void EmoteBase::EmoteSitB () inline private
Definition at line 458 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_SITB;
    m_InputActionName = "EmoteSitB";
    m_StanceMaskAdditive = 0;
    m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_CROUCH;
    m_AdditiveCallbackUID = 0;
    m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_SITB;
    m_HideItemInHands = false;
  }
References EmoteConstants::ID_EMOTE_SITB, and m_ID.
EmoteStartOverride()
bool EmoteBase::EmoteStartOverride (typename callbacktype , int id, int mask, bool fullbody) inline protected
Definition at line 47 of file EmoteBase.c.
  {
    return false;
  }
EmoteSuicide()
void EmoteBase::EmoteSuicide () inline private
Definition at line 570 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_SUICIDE;
    m_InputActionName = "EmoteSuicide";
    m_StanceMaskAdditive = 0;
    m_StanceMaskFullbody = 0;
    m_AdditiveCallbackUID = 0;
    m_FullbodyCallbackUID = 0;
    m_HideItemInHands = false;
  }
References EmoteConstants::ID_EMOTE_SUICIDE, and m_ID.
EmoteThroat()
void EmoteBase::EmoteThroat () inline private
Definition at line 153 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_THROAT;
    m_InputActionName = "EmoteThroat";
    m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
    m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_THROAT;
    m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_THROAT;
    m_HideItemInHands = false;
  }
References EmoteConstants::ID_EMOTE_THROAT, and m_ID.
EmoteThumb()
void EmoteBase::EmoteThumb () inline private
Definition at line 125 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_THUMB;
    m_InputActionName = "EmoteThumb";
    m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
    m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_THUMB;
    m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_THUMB;
    m_HideItemInHands = false;
  }
References EmoteConstants::ID_EMOTE_THUMB, and m_ID.
EmoteWatching()
void EmoteBase::EmoteWatching () inline private
Definition at line 273 of file EmoteClasses.c.
  {
    m_ID = EmoteConstants.ID_EMOTE_WATCHING;
    m_InputActionName = "EmoteWatching";
    m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
    m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_WATCHING;
    m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_WATCHING;
    m_HideItemInHands = false;
  }
References EmoteConstants::ID_EMOTE_WATCHING, and m_ID.
GetAdditiveCallbackUID()
int EmoteBase::GetAdditiveCallbackUID () inline protected
Definition at line 85 of file EmoteBase.c.
  {
    return m_AdditiveCallbackUID;
  }
References m_AdditiveCallbackUID.
GetFullbodyCallbackUID()
int EmoteBase::GetFullbodyCallbackUID () inline protected
Definition at line 90 of file EmoteBase.c.
  {
    return m_FullbodyCallbackUID;
  }
References m_FullbodyCallbackUID.
GetHideItemInHands()
bool EmoteBase::GetHideItemInHands () inline protected
Definition at line 95 of file EmoteBase.c.
  {
    return m_HideItemInHands;
  }
References m_HideItemInHands.
GetID()
int EmoteBase::GetID () inline protected
Definition at line 65 of file EmoteBase.c.
  {
    return m_ID;
  }
References m_ID.
GetInputActionName()
string EmoteBase::GetInputActionName () inline protected
Definition at line 70 of file EmoteBase.c.
  {
    return m_InputActionName;
  }
References m_InputActionName.
Referenced by GetBoundButtonText().
GetOwnerPlayer()
PlayerBase EmoteBase::GetOwnerPlayer () inline protected
Definition at line 60 of file EmoteBase.c.
  {
    return m_Player;
  }
References m_Player.
GetStanceMaskAdditive()
int EmoteBase::GetStanceMaskAdditive () inline protected
Definition at line 75 of file EmoteBase.c.
  {
    return m_StanceMaskAdditive;
  }
References m_StanceMaskAdditive.
GetStanceMaskFullbody()
int EmoteBase::GetStanceMaskFullbody () inline protected
Definition at line 80 of file EmoteBase.c.
  {
    return m_StanceMaskFullbody;
  }
References m_StanceMaskFullbody.
OnBeforeStandardCallbackCreated() [1/2]
void EmoteBase::OnBeforeStandardCallbackCreated (int callback_ID, int stancemask, bool is_fullbody) protected
OnBeforeStandardCallbackCreated() [2/2]
override void EmoteBase::OnBeforeStandardCallbackCreated (int callback_ID, int stancemask, bool is_fullbody) inline private
Definition at line 676 of file EmoteClasses.c.
  {
    if (callback_ID > -1)
    {
      if (callback_ID == DayZPlayerConstants.CMD_SUICIDEFB_PISTOL || callback_ID == DayZPlayerConstants.CMD_SUICIDEFB_RIFLE)
        m_Player.OverrideShootFromCamera(false);
    }
  }
References m_Player, and DayZPlayer::OverrideShootFromCamera().
OnCallbackEnd() [1/2]
void EmoteBase::OnCallbackEnd () protected
OnCallbackEnd() [2/2]
override void EmoteBase::OnCallbackEnd () inline private
Definition at line 685 of file EmoteClasses.c.
  {
    m_Player.SetSuicide(false);
  }
References m_Player, and DayZPlayer::SetSuicide().
SetOwnerPlayer()
void EmoteBase::SetOwnerPlayer (PlayerBase player) inline protected
Definition at line 52 of file EmoteBase.c.
  {
    m_Player = player;
  }
References m_Player.
Member Data Documentation
m_AdditiveCallbackUID
int EmoteBase::m_AdditiveCallbackUID = 0 protected
Definition at line 8 of file EmoteBase.c.
Referenced by GetAdditiveCallbackUID().
m_FullbodyCallbackUID
int EmoteBase::m_FullbodyCallbackUID = 0 protected
Definition at line 9 of file EmoteBase.c.
Referenced by GetFullbodyCallbackUID().
m_HideItemInHands
bool EmoteBase::m_HideItemInHands = false protected
Definition at line 10 of file EmoteBase.c.
Referenced by GetHideItemInHands().
m_ID
int EmoteBase::m_ID = -1 protected
Definition at line 4 of file EmoteBase.c.
Referenced by GetID().
m_InputActionName
string EmoteBase::m_InputActionName = "" protected
Definition at line 5 of file EmoteBase.c.
Referenced by GetInputActionName().
m_Player
PlayerBase EmoteBase::m_Player protected
Definition at line 3 of file EmoteBase.c.
Referenced by EmoteFBStanceCheck(), GetOwnerPlayer(), and SetOwnerPlayer().
m_StanceMaskAdditive
int EmoteBase::m_StanceMaskAdditive = 0 protected
Definition at line 6 of file EmoteBase.c.
Referenced by GetStanceMaskAdditive().
m_StanceMaskFullbody
int EmoteBase::m_StanceMaskFullbody = 0 protected
Definition at line 7 of file EmoteBase.c.
Referenced by GetStanceMaskFullbody().
WATER_DEPTH
const float EmoteBase::WATER_DEPTH = 0.15 protected
Definition at line 60 of file EmoteClasses.c.
The documentation for this class was generated from the following files:
scripts/4_World/Classes/EmoteClasses/EmoteBase.c
scripts/4_World/Classes/EmoteClasses/EmoteClasses.c