DayZ: ConnectErrorScriptModuleUI Class Reference
ConnectErrorScriptModuleUI Class Reference
Protected Member Functions
override bool OnModalResult (Widget w, int x, int y, int code, int result)
Static Protected Member Functions
static void DisconnectSession (bool loadMpPrivilege)
Additional Inherited Members
Private Member Functions inherited from UIScriptedMenu
override void Update (float timeslice)
void Leave ()
bool CanChangeHintPage (float timeAccu)
bool IsStatic ()
override Widget Init ()
void ReadBook (InventoryItem book)
override bool OnClick (Widget w, int x, int y, int button)
void NextPrevPage (bool next)
void CameraToolsMenu ()
void ~CameraToolsMenu ()
override void OnShow ()
override void OnHide ()
void SelectKeyframe (CTKeyframe kf)
void SelectEvent (CTEvent ev)
void SelectActor (CTActor ac)
override Widget Init ()
PlayerBase GetActor (int index)
void LoadData ()
void SaveData ()
float GetTotalTime (int index)
void AddKeyframe ()
void SaveKeyframe ()
void DeleteKeyframe ()
void ViewKeyframe ()
void AddActor (string actor_type)
void AddEvent (int actor_index)
void AddItem (string id, string type)
void AddHandsItem (string id, string type)
void SaveEvent ()
void DeleteEvent ()
void ViewEvent ()
Param6< vector, vector, float, float, float, int > GetCameraLine (int index)
void Play ()
void Stop ()
vector GetCameraLookDir ()
vector GetMouseLookDir ()
override void Update (float timeslice)
float SetCameraData (Param6< vector, vector, float, float, float, int > transform1, Param6< vector, vector, float, float, float, int > transform2)
void SetBlurValue (float blur)
float GetBlurValue ()
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
override bool OnKeyPress (Widget w, int x, int y, int key)
void ColorRed (Widget w)
void ColorWhite (Widget w, Widget enterW)
void ~ControlsXboxNew ()
void OnInputPresetChanged ()
void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
void Back ()
void UpdateTabContent (int tab_index)
void DrawConnectingLines (int index)
override Widget Init ()
override void OnShow ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
override void Update (float timeslice)
void ComposeData ()
Inits data structure.
void PerformSwitchPreset ()
void UpdateToolbarText ()
Widget FindChildByID (Widget wid, int user_id)
Finds immediate child widget with a corresponding userID.
bool FindAllChildrenByID (Widget wid, int user_id, out array< Widget > results)
Finds all immediate children widgets with corresponding userIDs.
int FilterByVisible (array< Widget > input, array< Widget > filtered)
returns count
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ButtonSetText (Widget w, string text)
void ButtonSetColor (Widget w, int color)
void ButtonSetTextColor (Widget w, int color)
void UpdateControlsElements ()
void UpdateControlsElementVisibility ()
void GesturesMenu ()
void ~GesturesMenu ()
void OnInputPresetChanged ()
override Widget Init ()
override void OnShow ()
override void OnHide ()
override bool OnController (Widget w, int control, int value)
override bool OnMouseEnter (Widget w, int x, int y)
override bool UseMouse ()
override bool UseGamepad ()
override void Update (float timeslice)
void ProcessEmoteConditionRequest (GestureMenuItem gesture_item)
void RefreshGestures (GestureCategories category_id=-1)
void GetGestureItems (out ref array< ref GestureMenuItem > gesture_items, GestureCategories category)
void CreateGestureContent ()
void UpdateQuickbarItemCard (GestureMenuItem gesture_item)
void DeleteGestureItems ()
void UpdateToolbar ()
DEPRECATED.
void UpdateCategoryName (string name)
void OnControlsChanged (RadialMenuControlType type)
void OnMouseSelect (Widget w)
void OnMouseDeselect (Widget w)
void OnMouseExecute (Widget w)
void OnMousePressLeft (Widget w)
LMB.
void OnMousePressRight (Widget w)
RMB.
void OnControllerSelect (Widget w)
void OnControllerDeselect (Widget w)
void OnControllerExecute (Widget w)
void OnControllerPressSelect (Widget w)
void OnControllerPressBack (Widget w)
void MarkSelected (Widget w)
void UnmarkSelected (Widget w)
void ExecuteSelectedCategory (Widget w)
void ExecuteSelectedItem ()
void BackOneLevel ()
bool IsMenuClosing ()
void SetMenuClosing (bool state)
void UpdateControlsElements ()
void OnMenuRelease ()
DEPRECATED.
void ~InGameMenu ()
override Widget Init ()
void SetGameVersion ()
bool SetServerInfo ()
void HudShow (bool show)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnClick (Widget w, int x, int y, int button)
void OnClick_Continue ()
void OnClick_Restart ()
void OnClick_Respawn ()
void OnClick_Options ()
void OnClick_Exit ()
override bool OnModalResult (Widget w, int x, int y, int code, int result)
override void Update (float timeslice)
void UpdateGUI ()
void MenuRequestRespawn (UIScriptedMenu menu, bool random)
void GameRespawn (bool random)
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ColorDisable (Widget w)
void ButtonSetText (Widget w, string text)
void ButtonSetColor (Widget w, int color)
void ButtonSetTextColor (Widget w, int color)
void SetServerInfoVisibility (bool show)
void ToggleFavoriteServer ()
DEPRECATED.
void InGameMenuXbox ()
void ~InGameMenuXbox ()
void OnInputPresetChanged ()
void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
override Widget Init ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnModalResult (Widget w, int x, int y, int code, int result)
void GameRetry (bool random)
void MenuRequestRespawn (UIScriptedMenu menu, bool random)
bool IsLocalPlayer (string uid)
SyncPlayerList CreateFakePlayerList (int player_count)
override void Update (float timeslice)
bool ShouldRestartBeVisible (Man player)
void UpdateGUI ()
bool IsOnlineOpen ()
void CloseOnline ()
void SelectServer ()
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
void SyncEvent_OnRecievedPlayerList (SyncPlayerList player_list)
void OnPermissionsUpdate (BiosPrivacyUidResultArray result_list)
override void OnShow ()
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
override void Refresh ()
void ColorDisable (Widget w)
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ButtonSetText (Widget w, string text)
void ButtonSetColor (Widget w, int color)
void ButtonSetTextColor (Widget w, int color)
void SetMuteButtonText (bool isMuted)
Set mute text button text (mute / unmute)
void LoadTextStrings ()
Set correct bottom button texts based on platform (ps4 vs xbox texts)
void LoadFooterButtonTexts ()
Initial texts load for the footer buttons.
void UpdateMenuFocus ()
void UpdateControlsElements ()
void OnInputPresetChanged ()
void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
void UpdateControlsElements ()
void UpdateControlsElementVisibility ()
void ~MapMenu ()
override Widget Init ()
override void InitMapItem (EntityAI item)
override void OnShow ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnKeyPress (Widget w, int x, int y, int key)
void OnInputPresetChanged ()
void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
override void Update (float timeslice)
void AddMarker (vector pos, int color, int icon=0)
void RemoveMarker ()
override void LoadMapMarkers ()
void CloseMapMenu ()
void SetCompassUIVisibility (bool pState)
void SetGPSMarkerVisibility (bool pState)
void SetGPSDirectionVisibility (bool pState)
void SetUpperLegendVisibility (bool pState)
void RenderScaleRuler ()
void ProcessDistanceAndUnits (float num, out float dist, out string units)
void UpdateControlsElements ()
void UpdateControlsElementVisibility ()
void ShiftMapToolsContainer ()
void CharacterCreationMenu ()
PlayerBase GetPlayerObj ()
void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
override Widget Init ()
void ~CharacterCreationMenu ()
void Apply ()
renames character
void Save ()
saves default character
void Back ()
void SetCharacter ()
void RandomizeCharacter ()
void GenderChanged ()
void SkinChanged ()
void TopChanged ()
void BottomChanged ()
void ShoesChanged ()
override bool OnKeyPress (Widget w, int x, int y, int key)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
void SetTooltipTexts (Widget w, string header="", string desc="")
void CheckNewOptions ()
override void OnShow ()
override void Refresh ()
override void Update (float timeslice)
override void OnHide ()
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ColorDisable (Widget w)
void SetCharacterSaved (bool state)
void UpdateControlsElements ()
void UpdateControlsElementVisibility ()
override Widget Init ()
void LoadDataAsync ()
override void Update (float timeslice)
void UpdateInfoPanelText (int input_device_type)
override Widget Init ()
void CreateTabs ()
void CreateGroupContainer ()
void UpdateTabContent (int tab_index)
void ClearKeybind (int key_index)
void ClearAlternativeKeybind (int key_index)
void StartEnteringKeybind (int key_index)
void CancelEnteringKeybind ()
void StartEnteringAlternateKeybind (int key_index)
void CancelEnteringAlternateKeybind ()
void ConfirmKeybindEntry (TIntArray new_keys)
void ConfirmAlternateKeybindEntry (TIntArray new_keys)
override void Update (float timeslice)
override bool OnClick (Widget w, int x, int y, int button)
void Apply ()
void Back ()
void Reset ()
Undoes the unsaved changes and reverts to previous state. Does not reset to defaults!
void SetToDefaults ()
void HardReset ()
void PerformSetToDefaultsExt (int mode)
override bool OnModalResult (Widget w, int x, int y, int code, int result)
override void Refresh ()
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnMouseWheel (Widget w, int x, int y, int wheel)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
void ColorRed (Widget w)
void ColorWhite (Widget w, Widget enterW)
void ColorDisabled (Widget w)
void InitInputSortingMap ()
void InitPresets (int index, Widget parent, Input input)
void OnAttemptSelectPreset (int index)
void OnSelectKBPreset (int index)
KeybindingsContainer GetCurrentTab ()
void AddGroup (int index, Input input)
void PerformSetToDefaults ()
deprecated, resets all (as before ~1.20)
void DeferredDefaultsInit ()
deprecated
override Widget Init ()
void ~MainMenu ()
void LoadMods ()
void FilterDlcs (inout array< ref ModInfo > modArray)
void ShowDlcFrame (bool show)
void PopulateDlcFrame ()
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
override void Refresh ()
override void OnShow ()
override void OnHide ()
override void Update (float timeslice)
void Play ()
bool CanSaveDefaultCharacter ()
void OpenMenuServerBrowser ()
void OpenMenuCustomizeCharacter ()
void NextCharacter ()
void PreviousCharacter ()
void OnChangeCharacter (bool create_character=true)
void OpenStats ()
void OpenMessages ()
void OpenSettings ()
void PlayVideo ()
void OpenTutorials ()
void OpenCredits ()
void Exit ()
bool TryConnectLastSession (out string ip, out int port)
void AutoConnect ()
void ConnectLastSession ()
void ConnectBestServer ()
override bool OnModalResult (Widget w, int x, int y, int code, int result)
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ButtonSetText (Widget w, string text)
void ButtonSetColor (Widget w, int color)
void ImagenSetColor (Widget w, int color)
void ButtonSetTextColor (Widget w, int color)
override Widget Init ()
void ~MainMenuConsole ()
void OnDLCChange (EDLCId dlcId)
void LoadMods ()
void FilterDLCs (inout array< ref ModInfo > modArray)
leaves ONLY DLCs
void PopulateDlcFrame ()
void OnInputPresetChanged ()
void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
override void Refresh ()
override void OnShow ()
override void OnHide ()
override void Update (float timeslice)
bool CanStoreBeOpened ()
void OpenMenuServerBrowser ()
void OpenMenuControls ()
void OpenMenuOptions ()
void OpenMenuPlayVideo ()
void OpenMenuTutorials ()
void OpenMenuCustomizeCharacter ()
void OpenCredits ()
void ChangeAccount ()
void Exit ()
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
override bool OnModalResult (Widget w, int x, int y, int code, int result)
void ButtonSetText (Widget w, string text)
void ButtonSetColor (Widget w, int color)
void ButtonSetAlphaAnim (Widget w)
void ButtonSetTextColor (Widget w, int color)
void UpdateControlsElements ()
void UpdateControlsElementVisibility ()
override Widget Init ()
void ~MainMenuVideo ()
override void OnShow ()
override void OnHide ()
void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
void StopVideo ()
void PlayPauseVideo ()
override void Update (float timeslice)
override void OnVisibilityChanged (bool isVisible)
void LoadFooterButtonTexts ()
void LoadTextStrings ()
void UpdateControlsElements ()
override Widget Init ()
void ~TutorialsMenu ()
void OnInputPresetChanged ()
void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
override void OnShow ()
void Back ()
void DrawConnectingLines (int index)
array< ref JsonControlMappingInfo > GetControlMappingInfo ()
override void Update (float timeslice)
void LoadFooterButtonTexts ()
Initial texts load for the footer buttons.
void LoadTextStrings ()
Set correct bottom button texts based on platform (ps4 vs xbox texts)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ButtonSetText (Widget w, string text)
void ButtonSetColor (Widget w, int color)
void ImagenSetColor (Widget w, int color)
void ButtonSetTextColor (Widget w, int color)
void UpdateControlsElements ()
void UpdateControlsElementVisibility ()
void OptionsMenu ()
override Widget Init ()
void ~OptionsMenu ()
void OnInputPresetChanged ()
void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
override bool OnClick (Widget w, int x, int y, int button)
void OnTabSwitch (int tab)
void Apply ()
void Back ()
void OnAttemptTabSwitch (int source, int target)
bool IsAnyTabChanged ()
void OnChanged ()
void Reset ()
void ResetCurrentTab ()
void SetToDefaults ()
void PerformSetToDefaults ()
void SliderFocus ()
void ToggleFocus ()
void ToggleDependentOptions (int mode, bool state)
Controls visibility and sometimes even state of specific, dependent options across sub-menus.
void ReloadOptions ()
void ReloadVideoOptions ()
override bool OnModalResult (Widget w, int x, int y, int code, int result)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
override void Refresh ()
override void OnShow ()
override void Update (float timeslice)
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ColorDisable (Widget w)
void UpdateControlsElements ()
void UpdateControlsElementVisibility ()
override Widget Init ()
void ~ServerBrowserMenuNew ()
TStringArray GetFavoritedServerIds ()
void OnInputPresetChanged ()
void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
void SetServersLoadingTab (TabType refreshing)
TabType GetServersLoadingTab ()
void AddFavoritesToFilter (GetServersInput input)
bool IsFavorited (string server_id)
bool SetFavoriteConsoles (string ipAddress, int port, bool favorite)
void AddFavorite (string ipAddress, int port, bool favorite)
void Back ()
void ShowYButton (bool show)
void ShowAButton (bool show)
void FilterFocus (bool focus)
void BackButtonFocus ()
void ServerListFocus (bool focus, bool favorite)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
override void Refresh ()
override void Update (float timeslice)
bool IsFocusable (Widget w)
void LoadFavoriteServers ()
void SaveFavoriteServersConsoles ()
void SelectServer (ServerBrowserEntry server)
void Connect (ServerBrowserEntry server)
void Play ()
void CustomizeCharacter ()
void NextCharacter ()
void PreviousCharacter ()
ServerBrowserTab GetSelectedTab ()
void OnTabSwitch ()
void OnLoadServerModsAsync (GetServerModListResult result_list)
void OnLoadServersAsync (GetServersResult result_list, EBiosError error, string response)
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ButtonSetText (Widget w, string text)
void ButtonSetColor (Widget w, int color)
void ButtonSetTextColor (Widget w, int color)
void UpdateControlsElements ()
void NoteMenu ()
void ~NoteMenu ()
override void InitNoteRead (string text="")
override void InitNoteWrite (EntityAI paper, EntityAI pen, string text="")
override Widget Init ()
override bool OnClick (Widget w, int x, int y, int button)
override void Update (float timeslice)
void RadialQuickbarMenu ()
void ~RadialQuickbarMenu ()
void OnInputPresetChanged ()
override Widget Init ()
override void OnShow ()
override void OnHide ()
override bool OnController (Widget w, int control, int value)
override bool OnMouseEnter (Widget w, int x, int y)
override bool UseMouse ()
override bool UseGamepad ()
void RefreshQuickbar (bool reset_selection=true)
void GetItems (out ref array< ref RadialQuickbarItem > items)
void CheckForLightsAndNVG (out ref array< ref RadialQuickbarItem > items, int last_idx)
void CreateContent (int selected_item_id=-1)
void UpdateQuickbarItemCard (RadialQuickbarItem quickbar_item)
void DeleteItems ()
void ChangeCurrentCategory (int category)
void OnControlsChanged (RadialMenuControlType type)
void OnMouseSelect (Widget w)
void OnMouseDeselect (Widget w)
void OnMouseExecute (Widget w)
void OnMousePressLeft (Widget w)
LMB.
void OnMousePressRight (Widget w)
RMB.
void OnControllerSelect (Widget w)
void OnControllerDeselect (Widget w)
void OnControllerPressSelect (Widget w)
void OnControllerPressBack (Widget w)
void MarkSelected (Widget w)
void UnmarkSelected (Widget w)
void PrimaryAction (Widget w)
void SecondaryAction (Widget w)
void BackOneLevel ()
void HandleLights (RadialQuickbarItem quickbar_item)
void HandleNVG (RadialQuickbarItem quickbar_item)
bool IsMenuClosing ()
void SetMenuClosing (bool state)
void UpdateControlsElements ()
void RespawnDialogue ()
void ~RespawnDialogue ()
override Widget Init ()
override void Update (float timeslice)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override void OnShow ()
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ButtonSetColor (Widget w, int color)
void ButtonSetTextColor (Widget w, int color)
void SetTooltipTexts (Widget w, string header="", string desc="")
bool RequestRespawn (bool random)
void RefreshByLocalProfile ()
void UpdateListClasses ()
map< int, SceneObject > GetFiltredSceneObjects (string search_string, map< int, SceneObject > array_ret)
TStringArray GetFiltredConfigClasses (string search_string, TStringArray array_ret)
void ScriptConsole ()
void ~ScriptConsole ()
ScriptConsoleTabBase GetSelectedHandler ()
void SetHintText (string text, Widget w)
void RegisterTab (ScriptConsoleTabBase handler)
override Widget Init ()
void HideHint ()
int GetWidgetCombinedHash (Widget w)
string GetMessage ()
void HoverSuccess ()
void HoverInterrupt ()
override bool OnKeyPress (Widget w, int x, int y, int key)
override bool OnKeyDown (Widget w, int x, int y, int key)
override void Update (float timeslice)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnDoubleClick (Widget w, int x, int y, int button)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
ScriptConsoleTabBase GetTabHandler (typename tabType)
void SelectTabByID (int id)
void SelectTabByButton (Widget button)
void SelectTab (ScriptConsoleTabBase selectedHandler)
void DisplayHint (string message)
override void OnRPCEx (int rpc_type, ParamsReadContext ctx)
Static Private Member Functions inherited from UIScriptedMenu
static void PlayAnimOnActor (int actor, int anim)
static void OpenMenu ()
static void CloseMenu ()
static void SetItemToAssign (EntityAI item)
static EntityAI GetItemToAssign ()
static RadialQuickbarMenu GetMenuInstance ()
static void OpenMenu (UIScriptedMenu parent=NULL)
static void CloseMenu ()
static void SaveData ()
static JsonHintsData GetData ()
Private Attributes inherited from UIScriptedMenu
ref UiHintPanelLoading m_HintPanel
bool m_IsStatic
float m_HintTimeAccu
TextWidget m_author
TextWidget m_title
TextWidget m_page
HtmlWidget m_content
float m_page_height
float m_content_total_height
float m_content_pos
vector m_FreeflightCamTransform [4]
vector m_NextCamPosition
float m_Time
Camera m_Camera1
Camera m_Camera2
ref array< ref Param6< vector, vector, float, float, float, int > > m_CameraLines
bool m_IsPlaying
int m_NextCameraIndex = 1
float m_FollowingTimeFinished
ref Param2< int, int > m_FollowingBone
CTKeyframe m_SelectedKeyframe
CTEvent m_SelectedEvent
CTActor m_SelectedActor
ref array< ref CTActor > m_Actors
ref array< ref CTKeyframe > m_Cameras
ref array< ref CTEvent > m_Events
Widget m_KeyframeContent
Widget m_EventContent
XComboBoxWidget m_InterpTypeSpeedCombo
XComboBoxWidget m_InterpTypeCombo
EditBoxWidget m_BlurEditWidget
EditBoxWidget m_ActorTypeWidget
EditBoxWidget m_ActorIdWidget
EditBoxWidget m_ActorItemTypeWidget
ButtonWidget m_AddItem
ButtonWidget m_AddHandsItem
ButtonWidget m_AddActor
ButtonWidget m_Play
ButtonWidget m_Stop
ButtonWidget m_Save
ButtonWidget m_Load
ButtonWidget m_AddKeyframe
ButtonWidget m_SaveKeyframe
ButtonWidget m_DeleteKeyframe
ButtonWidget m_ViewKeyframe
ButtonWidget m_AddEvent
ButtonWidget m_SaveEvent
ButtonWidget m_DeleteEvent
ButtonWidget m_ViewEvent
ButtonWidget m_CopyButton
ButtonWidget m_ApplyButton
EditBoxWidget m_CameraEditbox
TextWidget m_CameraValues
string m_BackButtonTextID
string m_NextPresetText
int m_CurrentTabIdx = -1
int m_CurrentPresetVariant = -1
ButtonWidget m_Back
ImageWidget m_ControlsLayoutImage
CanvasWidget m_CanvasWidget
TabberUI m_TabScript
Widget m_TabberWidget
Widget m_ControlsImage
Widget m_PlatformHolder
Widget m_VariantWidget
ref map< int, Widget > m_ImageMarkerStructure
ref map< int, Widget > m_CategoryStructure
ref map< int, ref TButtonPairingInfo > m_AreasLR
const int AREA_LEFT = 1
const int AREA_RIGHT = 2
const int PLATFORM_ADJUST_X1 = 1000
const int PLATFORM_ADJUST_PS = 2000
Widget m_GestureItemCardPanel
ref array< ref GestureMenuItem > m_GestureItems
Widget m_ToolbarPanel
TextWidget m_CategoryNameText
const string RADIAL_TEXT = "RadialText"
const string GESTURE_TEXT = "GestureNameText"
const string INPUT_TEXT = "InputActionText"
const string CATEGORY_NAME = "CategoryName"
Widget m_SelectedItem
bool m_IsCategorySelected
bool m_IsMenuClosing
int m_CurrentCategory
Widget m_ContinueButton
Widget m_SeparatorPanel
Widget m_ExitButton
Widget m_RestartButton
Widget m_RespawnButton
Widget m_RestartDeadRandomButton
Widget m_RestartDeadCustomButton
Widget m_OptionsButton
Widget m_ServerInfoPanel
Widget m_FavoriteButton
Widget m_FavoriteImage
Widget m_UnfavoriteImage
Widget m_CopyInfoButton
ref TextWidget m_ModdedWarning
ref TextWidget m_ServerIP
ref TextWidget m_ServerPort
ref TextWidget m_ServerName
ref UiHintPanel m_HintPanel
string m_MuteButtonTextID
string m_UnmuteButtonTextID
string m_SelectButtonTextID
string m_OpenGameCardButtonTextID
string m_CurrentMuteButtonText
bool m_SelectAvailable
bool m_MuteAvailable
bool m_BackAvailable
bool m_GamercardAvailable
bool m_PlayerAlive
ref PlayerListScriptedWidget m_ServerInfoPanel
Widget m_OnlineMenu
ButtonWidget m_ContinueButton
ButtonWidget m_ExitButton
ButtonWidget m_RestartDeadButton
ButtonWidget m_RestartButton
ButtonWidget m_OptionsButton
ButtonWidget m_ControlsButton
ButtonWidget m_OnlineButton
ButtonWidget m_TutorialsButton
TextWidget m_Version
const int BUTTON_XBOX_CONTROLS = 201
const string COORD_FORMAT = "%1.%2%3"
const int SCALE_RULER_LINE_WIDTH = 8
const int SCALE_RULER_NUM_SEGMENTS = 10
bool m_WasChanged
bool m_IsOpenning
float m_ToolScaleCellSizeCanvasWidth
float m_ToolsContainerPos0 [2]
ref IngameHud m_Hud
ref MapHandler m_MapMenuHandler
ref MapWidget m_MapWidgetInstance
ref SizeToChild m_LegendResizer
Widget m_MapToolsContainer
ImageWidget m_Images
Widget m_GPSMarker
ImageWidget m_GPSMarkerArrow
Widget m_UpperLegendContainer
Widget m_ToolsCompassBase
ImageWidget m_ToolsCompassArrow
TextWidget m_ToolsCompassAzimuth
TextWidget m_ToolsScaleContourText
TextWidget m_ToolsGPSElevationText
TextWidget m_ToolsGPSXText
TextWidget m_ToolsGPSYText
TextWidget m_ToolsScaleCellSizeText
CanvasWidget m_ToolsScaleCellSizeCanvas
ItemMap m_Map
ref MapNavigationBehaviour m_MapNavigationBehaviour
Widget m_CharacterRotationFrame
Widget m_Apply
Widget m_Save
Widget m_RandomizeCharacter
Widget m_BackButton
Widget m_PlayedCharacterInfo
Widget m_DetailsRoot
TextWidget m_DetailsLabel
RichTextWidget m_DetailsText
TextWidget m_CharacterHeaderText
ref OptionSelectorEditbox m_NameSelector
ref OptionSelectorMultistateCharacterMenu m_GenderSelector
ref OptionSelectorMultistateCharacterMenu m_SkinSelector
ref OptionSelectorMultistateCharacterMenu m_TopSelector
ref OptionSelectorMultistateCharacterMenu m_BottomSelector
ref OptionSelectorMultistateCharacterMenu m_ShoesSelector
int m_OriginalCharacterID
float m_MenuFadeInIncrement
float m_MenuFadeInLevel
float m_MenuFadeInLevel2 = 1
float m_LogoFadeInIncrement
float m_LogoFadeInLevel
float m_ScrollIncrement
float m_ScrollLevel
float m_ScrollMax
float m_ScrollSize
ref JsonDataCredits m_CreditsData
float m_CurrentTime = 0.0
ref array< ref CreditsElement > m_CreditsEntries = new array<ref CreditsElement>
ImageWidget m_Logo
ScrollWidget m_Scroller
WrapSpacerWidget m_Content
RichTextWidget m_InfoPanelText
Widget m_InfoPanel
TabberUI m_Tabber
ref DropdownPrefab m_KBDropdown
ref OptionSelectorMultistate m_PresetSelector
ref KeybindingsContainer m_GroupsContainer
ref array< ref KeybindingsGroup > m_Tabs
ButtonWidget m_Apply
ButtonWidget m_Undo
ButtonWidget m_Defaults
ButtonWidget m_HardReset
int m_CurrentSettingKeyIndex = -1
int m_CurrentSettingAlternateKeyIndex = -1
int m_OriginalPresetIndex
int m_TargetPresetIndex
ref array< int > m_SetKeybinds
const int MODAL_ID_BACK = 1337
const int MODAL_ID_DEFAULT = 100
const int MODAL_ID_DEFAULT_ALL = 101
const int MODAL_ID_PRESET_CHANGE = 200
const int MODAL_RESULT_DEFAULT_CURRENT = 0
const int MODAL_RESULT_DEFAULT_ALL = 1
ref MainMenuStats m_Stats
ref MainMenuVideo m_Video
MissionMainMenu m_Mission
DayZIntroScenePC m_ScenePC
TextWidget m_PlayerName
Widget m_Play
Widget m_ChooseServer
Widget m_CustomizeCharacter
Widget m_PlayVideo
Widget m_Tutorials
Widget m_TutorialButton
Widget m_MessageButton
Widget m_SettingsButton
Widget m_Exit
Widget m_NewsMain
Widget m_NewsSec1
Widget m_NewsSec2
Widget m_PrevCharacter
Widget m_NextCharacter
Widget m_LastPlayedTooltip
Widget m_LastPlayedTooltipLabel
TextWidget m_LastPlayedTooltipName
TextWidget m_LastPlayedTooltipIP
TextWidget m_LastPlayedTooltipPort
ref WidgetFadeTimer m_LastPlayedTooltipTimer
ref Widget m_LastFocusedButton
ref ModsMenuSimple m_ModsSimple
ref ModsMenuDetailed m_ModsDetailed
ref ModsMenuTooltip m_ModsTooltip
Widget m_DlcFrame
ref map< string, ref ModInfo > m_AllDlcsMap
ref JsonDataDLCList m_DlcData
ref array< ref MainMenuDlcHandlerBase > m_DlcHandlers
ref MainMenuDlcHandlerBase m_DisplayedDlcHandler
Widget m_ChangeAccount
Widget m_Options
Widget m_Controls
ref array< ref ModInfo > m_AllDLCs
VideoWidget m_Video
const string PATH_MOUSEKEY = "scripts/data/pagedatatutorials.json"
const string PATH_X1_OLD = "xbox/pagedatatutorials.json"
const string PATH_X1_NEW = "xbox/pagedatatutorialsalternate.json"
const string PATH_PS_OLD = "ps4/pagedatatutorials.json"
const string PATH_PS_NEW = "ps4/pagedatatutorialsalternate.json"
Widget m_InfoTextLeft
Widget m_InfoTextRight
const int TABS_COUNT = 4
ImageWidget m_tab_images [TABS_COUNT]
ref TutorialKeybinds m_KeybindsTab
ref OptionsMenuGame m_GameTab
ref OptionsMenuSounds m_SoundsTab
ref OptionsMenuVideo m_VideoTab
ref OptionsMenuControls m_ControlsTab
ref GameOptions m_Options
ButtonWidget m_Reset
Widget m_Details
int m_ActiveTabIdx = 0
bool m_ModalLock
bool m_CanApplyOrReset
bool m_CanToggle
Widget m_Back
ref ServerBrowserTab m_OfficialTab
ref ServerBrowserTab m_CommunityTab
ref ServerBrowserTab m_FavoritesTab
ref ServerBrowserTab m_LANTab
TabType m_IsRefreshing = TabType.NONE
ref TStringArray m_Favorites
ServerBrowserEntry m_SelectedServer
MultilineEditBoxWidget m_edit
HtmlWidget m_html
ButtonWidget m_confirm_button
ItemBase m_Paper
EntityAI m_Pen
bool m_IsWriting
int m_SymbolCount
string m_PenColor
Widget m_ItemCardPanel
ref array< ref RadialQuickbarItem > m_Items
const string TEXT_ITEM_NAME = "ItemName"
const string TEXT_ITEM_TITLE = "ItemTitle"
Widget m_CustomRespawn
Widget m_CurrentlyHighlighted
Widget m_WgtRoot
PluginSceneManager m_ModuleSceneManager
ButtonWidget m_WgtBtnSceneManager
ButtonWidget m_WgtBtnSceneSettings
ButtonWidget m_WgtBtnSceneSave
ButtonWidget m_WgtBtnEditorSettings
ButtonWidget m_WgtBtnDeleteRuler
Widget m_WgtPopupsMain
Widget m_WgtPopupsBg
ref TIntArray m_OpenedPopups
ref map< int, ref UIPopupScript > m_Popups
TextWidget m_SlWgtLoadedScene
string m_SlSelectedClass
ref map< int, SceneObject > m_SlObjectsList
TextListboxWidget m_SlWgtLbxObjectsList
EditBoxWidget m_SlWgtEbxFilter
ButtonWidget m_SlWgtSelect
ButtonWidget m_SlWgtFocus
string m_ClSelectedClass
ref TStringArray m_ClClassesList
EditBoxWidget m_ClWgtEbxFilter
TextListboxWidget m_ClWgtLbxClassesList
ButtonWidget m_ClWgtButtonAddAtt
TextWidget m_PrWgtClassName
EditBoxWidget m_PrWgtPoxX
EditBoxWidget m_PrWgtPoxY
EditBoxWidget m_PrWgtPoxZ
EditBoxWidget m_PrWgtDir
EditBoxWidget m_PrWgtDmg
ButtonWidget m_WgtBtnEditInitScript
Widget m_PrWgtAttRoot
Widget m_PrWgtAttTitle
ref array< ref UIPropertyAttachment > m_PrWidgetsAttachments
ref WidgetFadeTimer m_NotifyFadeTimer
Widget m_NotifyWgtPanel
TextListboxWidget m_PresetsTextListbox
TextListboxWidget m_PresetItemsTextListbox
ButtonWidget m_PresetAddItemtButton
ButtonWidget m_PresetRemoveItemButton
ButtonWidget m_SpawnOnGroundButton
ButtonWidget m_SpawnInInventoryButton
ButtonWidget m_SpawnAsAttachmentButton
ButtonWidget m_UpButton
ButtonWidget m_DownButton
ButtonWidget m_PresetNewButton
ButtonWidget m_PresetDeleteButton
ButtonWidget m_PresetRenameButton
ButtonWidget m_PresetSetDefaultButton
ButtonWidget m_CopyToClipboardButton
EditBoxWidget m_DamageEditBox
EditBoxWidget m_QuantityEditBox
EditBoxWidget m_SpawnDistanceEditBox
EditBoxWidget m_ConfigsButton
Widget m_WgtPnlWrapper
ButtonWidget m_WgtBtnLeftPresets
ButtonWidget m_WgtBtnPositionManager
string m_SelectedObject
bool m_SelectedObjectIsPreset
PluginDeveloper m_Developer
UIPopupScriptPositionManager m_PopupScriptPositionManager
PluginConfigDebugProfileFixed m_ConfigDebugProfileFixed
PluginConfigDebugProfile m_ConfigDebugProfile
bool m_HintEditMode
float m_HoverTime
bool m_HoverSuccessTriggered
Widget m_CurrentHoverWidget
Widget m_HintWidgetRoot
ImageWidget m_HintWidgetBackground
Widget m_EditTooltipRoot
RichTextWidget m_HintWidget
ButtonWidget m_HintOkButton
ButtonWidget m_HintCancelButton
ButtonWidget m_HintClearButton
EditBoxWidget m_HintInputText
float m_PrevMouseX
float m_PrevMouseY
Widget m_ButtonsWindowWidget
ScriptConsoleTabBase m_SelectedHandler
int m_Id
int m_SelectedTab
ref map< Widget, ref ScriptConsoleTabBase > m_TabHandlers = new map<Widget, ref ScriptConsoleTabBase>
ref map< int, ref ScriptConsoleTabBase > m_TabHandlersByID = new map<int, ref ScriptConsoleTabBase>
const string NO_HINT_TEXT = "No hint"
Static Private Attributes inherited from UIScriptedMenu
static CameraToolsMenu m_Instance
static GesturesMenu instance
static float MENU_FADEIN_TIME = 2.0
static float LOGO_FADEIN_TIME = 1.0
static float CREDIT_SCROLL_SPEED = 200.0
static EntityAI m_ItemToAssign
static RadialQuickbarMenu instance
static ref array< ref MapMarker > m_MarkedEntities = new array<ref MapMarker>()
static const string HINTS_PATH_DEFAULT = "scripts/data/internal/script_console_hints.json"
static const string HINTS_PATH_OPTIONAL = "$mission:script_console_hints.json"
static ref JsonHintsData m_JsonData
Detailed Description
Definition at line 51 of file ConnectErrorScriptModule.c.
Member Function Documentation
DisconnectSession()
static void ConnectErrorScriptModuleUI::DisconnectSession (bool loadMpPrivilege) inline static protected
Definition at line 53 of file ConnectErrorScriptModule.c.
  {
    g_Game.DisconnectSessionForce();
    g_Game.DisconnectSessionScript();
    if (loadMpPrivilege)
      OnlineServices.LoadMPPrivilege();
  }
References g_Game, and OnlineServices::LoadMPPrivilege().
Referenced by OnModalResult().
OnModalResult()
override bool ConnectErrorScriptModuleUI::OnModalResult (Widget w, int x, int y, int code, int result) inline protected
Definition at line 62 of file ConnectErrorScriptModule.c.
  {
    super.OnModalResult(w, x, y, code, result);
    int error = ErrorModuleHandler.GetCodeFromError(code);
    switch (error)
    {
    case EConnectErrorScript.ALREADY_CONNECTING:
    {
      switch (result)
      {
      case DBB_YES:
        g_Game.GetCallQueue(CALL_CATEGORY_SYSTEM).Call(DisconnectSession, true);
        break;
      case DBB_CANCEL:
        g_Game.GetCallQueue(CALL_CATEGORY_SYSTEM).Call(DisconnectSession, false);
        break;
      default:
        break;
      }
      break;
    }
    default:
      break;
    }
    return true;
  }
References CALL_CATEGORY_SYSTEM, DisconnectSession(), g_Game, ErrorModuleHandler::GetCodeFromError(), x, and y.
The documentation for this class was generated from the following file:
scripts/3_Game/Global/ErrorModuleHandler/ConnectErrorScriptModule.c