DayZ: ScriptConsoleEnfScriptTab Class Reference
ScriptConsoleEnfScriptTab Class Reference
Protected Member Functions
void ScriptConsoleEnfScriptTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void ~ScriptConsoleEnfScriptTab ()
override void OnSelected ()
void Add (string message, bool isReload=false)
void Clear (bool clearFile=false)
void ReloadScriptOutput ()
void HistoryBack ()
void HistoryForward ()
void RunEnscript ()
void ColorRunButton (bool success)
void ResetRunButtonColor ()
void RunEnscriptServer ()
void EnscriptHistoryBack ()
void EnscriptHistoryForward ()
override void OnRPCEx (int rpc_type, ParamsReadContext ctx)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnChange (Widget w, int x, int y, bool finished)
override void Show (bool show, ScriptConsoleTabBase selectedHandler)
Static Protected Member Functions
static void PrintS (string message)
static void PrintS (bool message)
static void PrintS (int message)
static void PrintS (float message)
static void PrintS (vector message)
static void PrintS (Object message)
Protected Attributes
int m_EnscriptHistoryRow
int m_EnscriptHistoryRowServer
ref TStringArray m_EnscriptConsoleHistory
ref TStringArray m_EnscriptConsoleHistoryServer
PluginLocalEnscriptHistory m_ModuleLocalEnscriptHistory
PluginLocalEnscriptHistoryServer m_ModuleLocalEnscriptHistoryServer
MultilineEditBoxWidget m_EnfScriptEdit
ButtonWidget m_EnfScriptRun
ButtonWidget m_EnfScriptClear
TextListboxWidget m_ScriptOutputListbox
bool m_AllowScriptOutput
int m_RunColor
Static Protected Attributes
static ScriptConsoleEnfScriptTab m_Instance
static ref TStringArray m_ScriptOutputHistory = new TStringArray()
Additional Inherited Members
Private Member Functions inherited from ScriptConsoleTabBase
void ScriptConsoleTabBase (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void Init (int id)
int GetID ()
Widget GetRoot ()
bool IsSelected ()
void Select (bool select, ScriptConsoleTabBase selectedHandler)
void OnSelected ()
void Show (bool show, ScriptConsoleTabBase selectedHandler)
Widget GetButton ()
void Update (float timeslice)
bool OnChange (Widget w, int x, int y, bool finished)
bool OnClick (Widget w, int x, int y, int button)
bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
bool OnKeyDown (Widget w, int x, int y, int key)
bool OnDoubleClick (Widget w, int x, int y, int button)
void OnRPCEx (int rpc_type, ParamsReadContext ctx)
bool OnMouseButtonDown (Widget w, int x, int y, int button)
bool OnKeyPress (Widget w, int x, int y, int key)
void AddItemToClipboard (TextListboxWidget text_listbox_widget)
Private Attributes inherited from ScriptConsoleTabBase
int m_Id
bool m_IsSelected
Widget m_ParentRoot
Widget m_Root
Widget m_Button
ScriptConsole m_ScriptConsole
ScriptConsoleTabBase m_Parent
PluginConfigDebugProfile m_ConfigDebugProfile
PluginConfigDebugProfileFixed m_ConfigDebugProfileFixed
Detailed Description
Definition at line 1 of file ScriptConsoleEnfScriptTab.c.
Constructor & Destructor Documentation
ScriptConsoleEnfScriptTab()
void ScriptConsoleEnfScriptTab::ScriptConsoleEnfScriptTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent = null) inline protected
Definition at line 19 of file ScriptConsoleEnfScriptTab.c.
  {
    m_Instance = this;
    m_ModuleLocalEnscriptHistory = PluginLocalEnscriptHistory.Cast(GetPlugin(PluginLocalEnscriptHistory));
    m_ModuleLocalEnscriptHistoryServer = PluginLocalEnscriptHistoryServer.Cast(GetPlugin(PluginLocalEnscriptHistoryServer));
    m_EnscriptConsoleHistory = m_ModuleLocalEnscriptHistory.GetAllLines();
    m_EnscriptConsoleHistoryServer = m_ModuleLocalEnscriptHistoryServer.GetAllLines();
    m_EnfScriptEdit = MultilineEditBoxWidget.Cast(root.FindAnyWidget("MultilineEditBoxWidget0"));
    m_EnfScriptRun = ButtonWidget.Cast(root.FindAnyWidget("RunButton"));
    m_EnfScriptClear = ButtonWidget.Cast(root.FindAnyWidget("ClearButton"));
    m_ScriptOutputListbox = TextListboxWidget.Cast(root.FindAnyWidget("ScriptOutputListbox"));
    m_RunColor = m_EnfScriptRun.GetColor();
  }
References GetPlugin(), m_EnfScriptClear, m_EnfScriptEdit, m_EnfScriptRun, m_EnscriptConsoleHistory, m_EnscriptConsoleHistoryServer, m_Instance, m_ModuleLocalEnscriptHistory, m_ModuleLocalEnscriptHistoryServer, m_RunColor, and m_ScriptOutputListbox.
~ScriptConsoleEnfScriptTab()
void ScriptConsoleEnfScriptTab::~ScriptConsoleEnfScriptTab () inline protected
Definition at line 33 of file ScriptConsoleEnfScriptTab.c.
  {
    m_Instance = null;
  }
References m_Instance.
Member Function Documentation
Add()
void ScriptConsoleEnfScriptTab::Add (string message, bool isReload = false) inline protected
Definition at line 82 of file ScriptConsoleEnfScriptTab.c.
  {
    if (message != string.Empty)
    {
      if (m_AllowScriptOutput && m_ScriptOutputListbox)
      {
        if (!isReload)
          m_ScriptOutputHistory.Insert(message);
        m_ScriptOutputListbox.AddItem(String(message), NULL, 0);
        m_ScriptOutputListbox.EnsureVisible(m_ScriptOutputListbox.GetNumItems());
      }
    }
  }
References Empty, m_AllowScriptOutput, m_ScriptOutputHistory, m_ScriptOutputListbox, and String().
Referenced by ReloadScriptOutput().
Clear()
void ScriptConsoleEnfScriptTab::Clear (bool clearFile = false) inline protected
Definition at line 96 of file ScriptConsoleEnfScriptTab.c.
  {
    if (clearFile)
      Debug.ClearLogs();
    m_ScriptOutputListbox.ClearItems();
  }
References Debug::ClearLogs(), and m_ScriptOutputListbox.
ColorRunButton()
void ScriptConsoleEnfScriptTab::ColorRunButton (bool success) inline protected
Definition at line 143 of file ScriptConsoleEnfScriptTab.c.
  {
    if (success)
      m_EnfScriptRun.SetColor(ARGB(255, 0, 255, 0));
    else
      m_EnfScriptRun.SetColor(ARGB(255, 255, 0, 0));
    GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(ResetRunButtonColor, 600);
  }
References ARGB(), CALL_CATEGORY_SYSTEM, GetGame(), m_EnfScriptRun, and ResetRunButtonColor().
Referenced by OnRPCEx(), and RunEnscript().
EnscriptHistoryBack()
void ScriptConsoleEnfScriptTab::EnscriptHistoryBack () inline protected
Definition at line 167 of file ScriptConsoleEnfScriptTab.c.
  {
    int history_index;
    if (m_EnfScriptEdit)
    {
      m_EnscriptHistoryRow++;
      history_index = m_EnscriptConsoleHistory.Count() - m_EnscriptHistoryRow - 1;
      if (history_index > -1)
        m_EnfScriptEdit.SetText(m_EnscriptConsoleHistory.Get(history_index));
      else m_EnscriptHistoryRow--;
    }
  }
References m_EnfScriptEdit, m_EnscriptConsoleHistory, and m_EnscriptHistoryRow.
Referenced by HistoryBack().
EnscriptHistoryForward()
void ScriptConsoleEnfScriptTab::EnscriptHistoryForward () inline protected
Definition at line 181 of file ScriptConsoleEnfScriptTab.c.
  {
    if (m_EnfScriptEdit)
    {
      int history_index;
      m_EnscriptHistoryRow--;
      history_index = m_EnscriptConsoleHistory.Count() - m_EnscriptHistoryRow - 1;
      if (history_index < m_EnscriptConsoleHistory.Count())
        m_EnfScriptEdit.SetText(m_EnscriptConsoleHistory.Get(history_index));
      else m_EnscriptHistoryRow++;
    }
  }
References m_EnfScriptEdit, m_EnscriptConsoleHistory, and m_EnscriptHistoryRow.
Referenced by HistoryForward().
HistoryBack()
void ScriptConsoleEnfScriptTab::HistoryBack () inline protected
Definition at line 113 of file ScriptConsoleEnfScriptTab.c.
  {
    EnscriptHistoryBack();
  }
References EnscriptHistoryBack().
HistoryForward()
void ScriptConsoleEnfScriptTab::HistoryForward () inline protected
Definition at line 119 of file ScriptConsoleEnfScriptTab.c.
  {
    EnscriptHistoryForward();
  }
References EnscriptHistoryForward().
OnChange()
override bool ScriptConsoleEnfScriptTab::OnChange (Widget w, int x, int y, bool finished) inline protected
Definition at line 228 of file ScriptConsoleEnfScriptTab.c.
  {
    super.OnChange(w, x, y, finished);
    return false;
  }
References x, and y.
OnClick()
override bool ScriptConsoleEnfScriptTab::OnClick (Widget w, int x, int y, int button) inline protected
Definition at line 210 of file ScriptConsoleEnfScriptTab.c.
  {
    super.OnClick(w, x, y, button);
    if (w == m_EnfScriptRun)
    {
      RunEnscript();
      return true;
    }
    else if (w == m_EnfScriptClear)
    {
      m_ScriptOutputListbox.ClearItems();
      m_ScriptOutputHistory.Clear();
      return true;
    }
    return false;
  }
References m_EnfScriptClear, m_EnfScriptRun, m_ScriptOutputHistory, m_ScriptOutputListbox, RunEnscript(), x, and y.
OnRPCEx()
override void ScriptConsoleEnfScriptTab::OnRPCEx (int rpc_type, ParamsReadContext ctx) inline protected
Definition at line 194 of file ScriptConsoleEnfScriptTab.c.
  {
    super.OnRPCEx(rpc_type, ctx);
#ifdef DIAG_DEVELOPER
    switch (rpc_type)
    {
    case ERPCs.DEV_RPC_SERVER_SCRIPT_RESULT:
    {
      if (ctx.Read(CachedObjectsParams.PARAM1_BOOL))
        ColorRunButton(CachedObjectsParams.PARAM1_BOOL.param1);
      break;
    }
    }
#endif
  }
References ColorRunButton(), and CachedObjectsParams::PARAM1_BOOL.
OnSelected()
override void ScriptConsoleEnfScriptTab::OnSelected () inline protected
Definition at line 38 of file ScriptConsoleEnfScriptTab.c.
  {
    int index = m_EnscriptConsoleHistory.Count() - m_EnscriptHistoryRow - 1;
    if (m_EnscriptConsoleHistory.IsValidIndex(index))
    {
      string text = m_EnscriptConsoleHistory.Get(index);
      m_EnfScriptEdit.SetText(text);
    }
    ReloadScriptOutput();
  }
References m_EnfScriptEdit, m_EnscriptConsoleHistory, m_EnscriptHistoryRow, and ReloadScriptOutput().
PrintS() [1/6]
static void ScriptConsoleEnfScriptTab::PrintS (bool message) inline static protected
Definition at line 56 of file ScriptConsoleEnfScriptTab.c.
  {
    PrintS(message.ToString());
  }
References PrintS().
PrintS() [2/6]
static void ScriptConsoleEnfScriptTab::PrintS (float message) inline static protected
Definition at line 66 of file ScriptConsoleEnfScriptTab.c.
  {
    PrintS(message.ToString());
  }
References PrintS().
PrintS() [3/6]
static void ScriptConsoleEnfScriptTab::PrintS (int message) inline static protected
Definition at line 61 of file ScriptConsoleEnfScriptTab.c.
  {
    PrintS(message.ToString());
  }
References PrintS().
PrintS() [4/6]
static void ScriptConsoleEnfScriptTab::PrintS (Object message) inline static protected
Definition at line 76 of file ScriptConsoleEnfScriptTab.c.
  {
    PrintS(message.ToString());
  }
References PrintS().
PrintS() [5/6]
static void ScriptConsoleEnfScriptTab::PrintS (string message) inline static protected
Definition at line 49 of file ScriptConsoleEnfScriptTab.c.
  {
    Print(message);
    if (m_Instance)
      m_Instance.Add(message);
  }
References m_Instance, and Print().
Referenced by PrintS(), PrintS(), PrintS(), PrintS(), and PrintS().
PrintS() [6/6]
static void ScriptConsoleEnfScriptTab::PrintS (vector message) inline static protected
Definition at line 71 of file ScriptConsoleEnfScriptTab.c.
  {
    PrintS(message.ToString());
  }
References PrintS().
ReloadScriptOutput()
void ScriptConsoleEnfScriptTab::ReloadScriptOutput () inline protected
Definition at line 104 of file ScriptConsoleEnfScriptTab.c.
  {
    m_ScriptOutputListbox.ClearItems();
    m_AllowScriptOutput = true;
    foreach (string s: m_ScriptOutputHistory)
      Add(s, true);
    m_AllowScriptOutput = false;
  }
References Add(), m_AllowScriptOutput, m_ScriptOutputHistory, and m_ScriptOutputListbox.
Referenced by OnSelected().
ResetRunButtonColor()
void ScriptConsoleEnfScriptTab::ResetRunButtonColor () inline protected
Definition at line 152 of file ScriptConsoleEnfScriptTab.c.
  {
    m_EnfScriptRun.SetColor(m_RunColor);
  }
References m_EnfScriptRun, and m_RunColor.
Referenced by ColorRunButton().
RunEnscript()
void ScriptConsoleEnfScriptTab::RunEnscript () inline protected
Definition at line 124 of file ScriptConsoleEnfScriptTab.c.
  {
#ifdef DEVELOPER
    string code;
    m_EnfScriptEdit.GetText(code);
    string codeNoReplace = code;
    _player = PlayerBase.Cast(GetGame().GetPlayer());
    m_AllowScriptOutput = true;
    code.Replace("Print(", "ScriptConsoleEnfScriptTab.PrintS(");
    code.Replace("Print (", "ScriptConsoleEnfScriptTab.PrintS(");
    bool success = GetGame().ExecuteEnforceScript("void scConsMain() \n{\n" + code + "\n}\n", "scConsMain");
    m_AllowScriptOutput = false;
    ColorRunButton(success);
    m_EnscriptConsoleHistory.Insert(codeNoReplace);
    m_ModuleLocalEnscriptHistory.AddNewLine(codeNoReplace);
#endif
  }
References _player, ColorRunButton(), GetGame(), GetPlayer(), m_AllowScriptOutput, m_EnfScriptEdit, m_EnscriptConsoleHistory, and m_ModuleLocalEnscriptHistory.
Referenced by OnClick().
RunEnscriptServer()
void ScriptConsoleEnfScriptTab::RunEnscriptServer () inline protected
Definition at line 157 of file ScriptConsoleEnfScriptTab.c.
  {
    string code;
    m_EnfScriptEdit.GetText(code);
    m_EnscriptConsoleHistoryServer.Insert(code);
    m_ModuleLocalEnscriptHistoryServer.AddNewLine(code);
    CachedObjectsParams.PARAM1_STRING.param1 = code;
    GetGame().RPCSingleParam(GetGame().GetPlayer(), ERPCs.DEV_RPC_SERVER_SCRIPT, CachedObjectsParams.PARAM1_STRING, true, GetGame().GetPlayer().GetIdentity());
  }
References GetGame(), GetPlayer(), m_EnfScriptEdit, m_EnscriptConsoleHistoryServer, m_ModuleLocalEnscriptHistoryServer, and CachedObjectsParams::PARAM1_STRING.
Show()
override void ScriptConsoleEnfScriptTab::Show (bool show, ScriptConsoleTabBase selectedHandler) inline protected
Definition at line 235 of file ScriptConsoleEnfScriptTab.c.
  {
    if (!show && (selectedHandler.Type() == ScriptConsoleEnfScriptTab || selectedHandler.Type() == ScriptConsoleEnfScriptServerTab))
    {
      //do nothing
    }
    else
    {
      m_Root.Show(show);
      m_Root.Enable(show);
    }
  }
References ScriptConsoleTabBase::m_Root.
Member Data Documentation
m_AllowScriptOutput
bool ScriptConsoleEnfScriptTab::m_AllowScriptOutput protected
Definition at line 14 of file ScriptConsoleEnfScriptTab.c.
Referenced by Add(), ReloadScriptOutput(), and RunEnscript().
m_EnfScriptClear
ButtonWidget ScriptConsoleEnfScriptTab::m_EnfScriptClear protected
Definition at line 12 of file ScriptConsoleEnfScriptTab.c.
Referenced by OnClick(), and ScriptConsoleEnfScriptTab().
m_EnfScriptEdit
MultilineEditBoxWidget ScriptConsoleEnfScriptTab::m_EnfScriptEdit protected
Definition at line 10 of file ScriptConsoleEnfScriptTab.c.
Referenced by EnscriptHistoryBack(), EnscriptHistoryForward(), OnSelected(), RunEnscript(), RunEnscriptServer(), and ScriptConsoleEnfScriptTab().
m_EnfScriptRun
ButtonWidget ScriptConsoleEnfScriptTab::m_EnfScriptRun protected
Definition at line 11 of file ScriptConsoleEnfScriptTab.c.
Referenced by ColorRunButton(), OnClick(), ResetRunButtonColor(), and ScriptConsoleEnfScriptTab().
m_EnscriptConsoleHistory
ref TStringArray ScriptConsoleEnfScriptTab::m_EnscriptConsoleHistory protected
Definition at line 6 of file ScriptConsoleEnfScriptTab.c.
Referenced by EnscriptHistoryBack(), EnscriptHistoryForward(), OnSelected(), RunEnscript(), and ScriptConsoleEnfScriptTab().
m_EnscriptConsoleHistoryServer
ref TStringArray ScriptConsoleEnfScriptTab::m_EnscriptConsoleHistoryServer protected
Definition at line 7 of file ScriptConsoleEnfScriptTab.c.
Referenced by RunEnscriptServer(), and ScriptConsoleEnfScriptTab().
m_EnscriptHistoryRow
int ScriptConsoleEnfScriptTab::m_EnscriptHistoryRow protected
Definition at line 4 of file ScriptConsoleEnfScriptTab.c.
Referenced by EnscriptHistoryBack(), EnscriptHistoryForward(), and OnSelected().
m_EnscriptHistoryRowServer
int ScriptConsoleEnfScriptTab::m_EnscriptHistoryRowServer protected
Definition at line 5 of file ScriptConsoleEnfScriptTab.c.
m_Instance
ScriptConsoleEnfScriptTab ScriptConsoleEnfScriptTab::m_Instance static protected
Definition at line 3 of file ScriptConsoleEnfScriptTab.c.
Referenced by PrintS(), ScriptConsoleEnfScriptTab(), and ~ScriptConsoleEnfScriptTab().
m_ModuleLocalEnscriptHistory
PluginLocalEnscriptHistory ScriptConsoleEnfScriptTab::m_ModuleLocalEnscriptHistory protected
Definition at line 8 of file ScriptConsoleEnfScriptTab.c.
Referenced by RunEnscript(), and ScriptConsoleEnfScriptTab().
m_ModuleLocalEnscriptHistoryServer
PluginLocalEnscriptHistoryServer ScriptConsoleEnfScriptTab::m_ModuleLocalEnscriptHistoryServer protected
Definition at line 9 of file ScriptConsoleEnfScriptTab.c.
Referenced by RunEnscriptServer(), and ScriptConsoleEnfScriptTab().
m_RunColor
int ScriptConsoleEnfScriptTab::m_RunColor protected
Definition at line 15 of file ScriptConsoleEnfScriptTab.c.
Referenced by ResetRunButtonColor(), and ScriptConsoleEnfScriptTab().
m_ScriptOutputHistory
ref TStringArray ScriptConsoleEnfScriptTab::m_ScriptOutputHistory = new TStringArray() static protected
Definition at line 17 of file ScriptConsoleEnfScriptTab.c.
Referenced by Add(), OnClick(), and ReloadScriptOutput().
m_ScriptOutputListbox
TextListboxWidget ScriptConsoleEnfScriptTab::m_ScriptOutputListbox protected
Definition at line 13 of file ScriptConsoleEnfScriptTab.c.
Referenced by Add(), Clear(), OnClick(), ReloadScriptOutput(), and ScriptConsoleEnfScriptTab().
The documentation for this class was generated from the following file:
scripts/5_Mission/GUI/ScriptConsoleEnfScriptTab.c