DayZ: scripts/3_Game/Systems/HFSMBase.c File Reference
HFSMBase.c File Reference
Classes
class HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >
Functions
void fsmDebugPrint (string s)
void fsmDebugSpam (string s)
Function Documentation
fsmDebugPrint()
void fsmDebugPrint (string s)
Definition at line 1 of file HFSMBase.c.
{
#ifdef FSM_DEBUG
  PrintToRPT("" + s); // comment/uncomment to hide/see debug logs
#else
  //Print("" + s); // comment/uncomment to hide/see debug logs
#endif
}
References PrintToRPT().
Referenced by HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Abort(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindAbortDestinationState(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortEvent(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessAbortEvent(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortTransition(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessAbortTransition(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessEvent(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessLocalTransition(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessLocalTransition(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), and HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Terminate().
fsmDebugSpam()
void fsmDebugSpam (string s)
Definition at line 9 of file HFSMBase.c.
{
#ifdef FSM_DEBUG_SPAM
  PrintToRPT("" + s); // comment/uncomment to hide/see debug logs
#else
  //Print("" + s); // comment/uncomment to hide/see debug logs
#endif
}
References PrintToRPT().
Referenced by HandleWeaponEvents(), OnEventForRemoteWeapon(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessEvent(), Weapon::ResetWeaponAnimState(), and SyncAnimState().