DayZ: HumanInventoryWithFSM Class Reference
HumanInventoryWithFSM Class Reference
HumanInventory... with FSM (synchronous, no anims)
Protected Member Functions
void HumanInventoryWithFSM ()
void CreateStableStates ()
override void Init ()
bool CanProcessHandEvents ()
override bool ProcessHandEvent (HandEventBase e)
hand's fsm handling of events @NOTE: warning: ProcessHandEvent can be called only within DayZPlayer::HandleInventory (or CommandHandler)
bool ProcessHandAbortEvent (HandEventBase e)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
int GetCurrentStateID ()
bool IsIdle ()
void NetSyncCurrentStateID (int id)
Engine callback - network synchronization of FSM's state. not intended to direct use.
Protected Attributes
ref HandFSM m_FSM
ref HandStateBase m_Empty
hand slot state machine
ref HandStateBase m_Equipped
Additional Inherited Members
Private Member Functions inherited from HumanInventory
bool ReplaceItemInElsewhereWithNewinHandsImpl (InventoryMode mode, HandEventBase e)
bool ReplaceItemInHandsWithNewImpl (InventoryMode mode, HandEventBase e)
bool ReplaceItemInHandsWithNew (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
bool ReplaceItemInHandsWithNewElsewhere (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
bool SwappingToPreviousLocation (EntityAI item1, EntityAI item2, out InventoryLocation dst)
void HandleInventoryManipulation ()
void Update (float delta_time)
bool ValidateUserReservationCancel (inout Serializer ctx, InventoryValidation validation)
Detailed Description
HumanInventory... with FSM (synchronous, no anims)
Definition at line 5 of file HumanInventoryWithFSM.c.
Constructor & Destructor Documentation
HumanInventoryWithFSM()
void HumanInventoryWithFSM::HumanInventoryWithFSM () inline protected
Definition at line 11 of file HumanInventoryWithFSM.c.
  {
    m_FSM = new HandFSM();
  }
References m_FSM.
Member Function Documentation
CanProcessHandEvents()
bool HumanInventoryWithFSM::CanProcessHandEvents () inline protected
Definition at line 90 of file HumanInventoryWithFSM.c.
{ return m_FSM && m_FSM.IsRunning(); }
References m_FSM.
CreateStableStates()
void HumanInventoryWithFSM::CreateStableStates () inline protected
Definition at line 16 of file HumanInventoryWithFSM.c.
  {
    // stable states are created only if they do not exist already (for example created by derived class like DayZPlayerInventory)
    // @NOTE: this cannot be done in constructor, as there is NO owner set yet. GetManOwner() will therefore return NULL.
    if (!m_Empty)
      m_Empty = new HandStateEmpty(GetManOwner());
    if (!m_Equipped)
      m_Equipped = new HandStateEquipped(GetManOwner());
  }
References HumanInventory::GetManOwner(), m_Empty, and m_Equipped.
Referenced by Init().
GetCurrentStateID()
HumanInventoryWithFSM::GetCurrentStateID () inline protected
Returns
identifier of current stable state
Definition at line 152 of file HumanInventoryWithFSM.c.
{ return m_FSM.GetCurrentStateID(); }
References m_FSM.
Init()
override void HumanInventoryWithFSM::Init () inline protected
Definition at line 26 of file HumanInventoryWithFSM.c.
  {
    // setup state machine
    if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[hndfsm] Initializing Human Inventory FSM");
    // basic states
    CreateStableStates();
    // events
    HandEventBase __T__ = new HandEventTake;
    HandEventBase __D__ = new HandEventDrop;
    HandEventBase __Tw_ = new HandEventThrow;
    HandEventBase __M__ = new HandEventMoveTo;
    HandEventBase __W__ = new HandEventSwap;
    HandEventBase __F__ = new HandEventForceSwap;
    HandEventBase __X__ = new HandEventDestroy;
    HandEventBase __Xd_ = new HandEventDestroyed;
    HandEventBase __R__ = new HandEventDestroyAndReplaceWithNew;
    HandEventBase __Re_ = new HandEventDestroyAndReplaceWithNewElsewhere;
    HandEventBase __Rh_ = new HandEventDestroyElsewhereAndReplaceWithNewInHands;
    HandEventBase __Rd_ = new HandEventReplaced;
    HandEventBase __Cd_ = new HandEventCreated;
    HandEventBase _fin_ = new HandEventHumanCommandActionFinished;
    HandEventBase _abt_ = new HandEventHumanCommandActionAborted;
    HandReplacingItemInHands replacing = new HandReplacingItemInHands(GetManOwner());
    HandReplacingItemInHands replacingElsewhere = new HandReplacingItemInHands(GetManOwner());
    HandReplacingItemElsewhereWithNewInHands replacingElsewhere3 = new HandReplacingItemElsewhereWithNewInHands(GetManOwner());
    // setup transitions
    m_FSM.AddTransition(new HandTransition(m_Empty, __T__, m_Equipped, new HandActionTake, new HandGuardHasItemInEvent(GetManOwner())));
    m_FSM.AddTransition(new HandTransition(m_Empty, __Cd_, m_Equipped, new HandActionCreated, new HandGuardHasItemInEvent(GetManOwner())));
    m_FSM.AddTransition(new HandTransition(m_Equipped, __D__, m_Empty, new HandActionDrop, null));
    m_FSM.AddTransition(new HandTransition(m_Equipped, __Tw_, m_Empty, new HandActionThrow, null));
    m_FSM.AddTransition(new HandTransition(m_Equipped, __M__, m_Empty, new HandActionMoveTo, new HandGuardAnd(new HandGuardHasItemInHands(GetManOwner()), new HandGuardCanMove(GetManOwner()))));
    m_FSM.AddTransition(new HandTransition(m_Equipped, __X__, m_Empty, new HandActionDestroy, new HandGuardHasItemInHands(GetManOwner())));
    m_FSM.AddTransition(new HandTransition(m_Equipped, __Xd_, m_Empty, new HandActionDestroyed, new HandGuardHasDestroyedItemInHands(GetManOwner())));
    m_FSM.AddTransition(new HandTransition(m_Equipped, __Xd_, m_Equipped, new HandActionDestroyed, new HandGuardNot(new HandGuardHasDestroyedItemInHands(GetManOwner()))));
    m_FSM.AddTransition(new HandTransition(m_Equipped, __R__, replacing));
    m_FSM.AddTransition(new HandTransition(replacing, _fin_, m_Equipped));
    replacing.AddTransition(new HandTransition(replacing.m_Replacing, _abt_, m_Equipped));
    m_FSM.AddTransition(new HandTransition(m_Equipped, __Re_, replacingElsewhere));
    m_FSM.AddTransition(new HandTransition(replacingElsewhere, _fin_, m_Empty));
    replacingElsewhere.AddTransition(new HandTransition(replacingElsewhere.m_Replacing, _abt_, m_Equipped));
    m_FSM.AddTransition(new HandTransition(m_Empty, __Rh_, replacingElsewhere3));
    m_FSM.AddTransition(new HandTransition(replacingElsewhere3, _fin_, m_Equipped));
    replacingElsewhere3.AddTransition(new HandTransition(replacingElsewhere3.m_Replacing, _abt_, m_Empty));
    m_FSM.AddTransition(new HandTransition(m_Equipped, __Rd_, m_Equipped, new HandActionReplaced, null));
    m_FSM.AddTransition(new HandTransition(m_Equipped, __W__, m_Equipped, new HandActionSwap, new HandGuardAnd(new HandGuardHasItemInHands(GetManOwner()), new HandGuardCanSwap(GetManOwner()))));
    m_FSM.AddTransition(new HandTransition(m_Equipped, __F__, m_Equipped, new HandActionForceSwap, new HandGuardAnd(new HandGuardHasItemInHands(GetManOwner()), new HandGuardCanForceSwap(GetManOwner()))));
    // start FSM
    m_FSM.SetInitialState(m_Empty);
    m_FSM.Start();
    super.Init();
  }
References CreateStableStates(), HumanInventory::GetManOwner(), hndDebugPrint(), LogManager::IsInventoryHFSMLogEnable(), m_Empty, m_Equipped, and m_FSM.
IsIdle()
bool HumanInventoryWithFSM::IsIdle () inline protected
Definition at line 154 of file HumanInventoryWithFSM.c.
{ return m_FSM.GetCurrentState().IsIdle(); }
References m_FSM.
NetSyncCurrentStateID()
HumanInventoryWithFSM::NetSyncCurrentStateID (int id) inline protected
Engine callback - network synchronization of FSM's state. not intended to direct use.
Definition at line 159 of file HumanInventoryWithFSM.c.
  {
    m_FSM.NetSyncCurrentStateID(id);
  }
References m_FSM.
OnStoreLoad()
override bool HumanInventoryWithFSM::OnStoreLoad (ParamsReadContext ctx, int version) inline protected
Definition at line 131 of file HumanInventoryWithFSM.c.
  {
    if (!super.OnStoreLoad(ctx, version))
      return false;
    //@TODO
    //m_FSM.OnStoreLoad(ctx, version);
    return true;
  }
OnStoreSave()
override void HumanInventoryWithFSM::OnStoreSave (ParamsWriteContext ctx) inline protected
Definition at line 142 of file HumanInventoryWithFSM.c.
  {
    super.OnStoreSave(ctx);
    //@TODO
    //m_FSM.OnStoreSave(ctx, version);
  }
ProcessHandAbortEvent()
bool HumanInventoryWithFSM::ProcessHandAbortEvent (HandEventBase e) inline protected
Definition at line 114 of file HumanInventoryWithFSM.c.
  {
    //SyncRemote(e);
    ProcessEventResult aa;
    m_FSM.ProcessAbortEvent(e, aa);
    if (aa == ProcessEventResult.FSM_OK)
    {
      if (LogManager.IsInventoryHFSMLogEnable()) hndDebugSpam("[hndfsm]  STS = " + GetManOwner().GetSimulationTimeStamp() + " Processed event e=" + e.ToString());
      return true;
    }
    else
    {
      //if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("FSM refused to process event (no transition): src=" + GetCurrentState().ToString() + " event=" + e.ToString());
      return false;
    }
  }
References HumanInventory::GetManOwner(), hndDebugSpam(), LogManager::IsInventoryHFSMLogEnable(), and m_FSM.
ProcessHandEvent()
HumanInventoryWithFSM::ProcessHandEvent (HandEventBase e) inline protected
hand's fsm handling of events @NOTE: warning: ProcessHandEvent can be called only within DayZPlayer::HandleInventory (or CommandHandler)
Definition at line 96 of file HumanInventoryWithFSM.c.
  {
    //SyncRemote(e);
    if (m_FSM.ProcessEvent(e) == ProcessEventResult.FSM_OK)
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryHFSMLogEnable())
        Debug.InventoryHFSMLog("STS = " + GetManOwner().GetSimulationTimeStamp(), e.ToString(), "ProcessHandEvent", e.m_Player.ToString());
#endif
      return true;
    }
    else
    {
      //if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("FSM refused to process event (no transition): src=" + GetCurrentState().ToString() + " event=" + e.ToString());
      return false;
    }
  }
References HumanInventory::GetManOwner(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_FSM.
Member Data Documentation
m_Empty
ref HandStateBase HumanInventoryWithFSM::m_Empty protected
hand slot state machine
Definition at line 8 of file HumanInventoryWithFSM.c.
Referenced by CreateStableStates(), and Init().
m_Equipped
ref HandStateBase HumanInventoryWithFSM::m_Equipped protected
Definition at line 9 of file HumanInventoryWithFSM.c.
Referenced by CreateStableStates(), and Init().
m_FSM
ref HandFSM HumanInventoryWithFSM::m_FSM protected
Definition at line 7 of file HumanInventoryWithFSM.c.
Referenced by CanProcessHandEvents(), GetCurrentStateID(), HumanInventoryWithFSM(), Init(), IsIdle(), NetSyncCurrentStateID(), ProcessHandAbortEvent(), and ProcessHandEvent().
The documentation for this class was generated from the following file:
scripts/3_Game/Systems/Inventory/HumanInventoryWithFSM.c