DayZ: FeverMdfr Class Reference
FeverMdfr Class Reference
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override void OnActivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
float m_Time
float m_NextEvent
Static Private Attributes
static const float EVENT_INTERVAL_MIN = 12
static const float EVENT_INTERVAL_MAX = 18
Detailed Description
Definition at line 1 of file Fever.c.
Member Function Documentation
ActivateCondition()
override bool FeverMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 18 of file Fever.c.
  {
    return (player.GetModifiersManager().IsModifierActive(eModifiers.MDF_CHOLERA) || player.GetModifiersManager().IsModifierActive(eModifiers.MDF_INFLUENZA) || player.GetModifiersManager().IsModifierActive(eModifiers.MDF_WOUND_INFECTION2));
  }
Referenced by DeactivateCondition().
DeactivateCondition()
override bool FeverMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 45 of file Fever.c.
  {
    return !ActivateCondition(player);
  }
References ActivateCondition().
Init()
override void FeverMdfr::Init () inline private
Definition at line 10 of file Fever.c.
  {
    m_TrackActivatedTime = false;
    m_ID = eModifiers.MDF_FEVER;
    m_TickIntervalInactive = DEFAULT_TICK_TIME_INACTIVE;
    m_TickIntervalActive = DEFAULT_TICK_TIME_ACTIVE_SHORT;
    m_SyncID = eModifierSyncIDs.MODIFIER_SYNC_FEVER;
  }
References DEFAULT_TICK_TIME_ACTIVE_SHORT, DEFAULT_TICK_TIME_INACTIVE, m_ID, m_SyncID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void FeverMdfr::OnActivate (PlayerBase player) inline private
Definition at line 23 of file Fever.c.
  {
    if (player.m_NotifiersManager)
      player.m_NotifiersManager.ActivateByType(eNotifiers.NTF_FEVERISH);
    player.GetSymptomManager().QueueUpSecondarySymptom(SymptomIDs.SYMPTOM_FEVERBLUR);
  }
OnDeactivate()
override void FeverMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 37 of file Fever.c.
  {
    if (player.m_NotifiersManager)
      player.m_NotifiersManager.DeactivateByType(eNotifiers.NTF_FEVERISH);
    player.GetSymptomManager().RemoveSecondarySymptom(SymptomIDs.SYMPTOM_FEVERBLUR);
  }
OnReconnect()
override void FeverMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 31 of file Fever.c.
  {
    this.OnActivate(player);
  }
References OnActivate().
OnTick()
override void FeverMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 50 of file Fever.c.
  {
    float water_loss = deltaT * PlayerConstants.WATER_LOSS_FEVER;
    player.GetStatWater().Add(-water_loss);
    m_Time += deltaT;
    if (m_Time >= m_NextEvent)
    {
      m_Time = 0;
      m_NextEvent = Math.RandomFloatInclusive(EVENT_INTERVAL_MIN, EVENT_INTERVAL_MAX);
      player.GetSymptomManager().QueueUpPrimarySymptom(SymptomIDs.SYMPTOM_HOT);
    }
  }
References EVENT_INTERVAL_MAX, EVENT_INTERVAL_MIN, m_NextEvent, m_Time, Math::RandomFloatInclusive(), and PlayerConstants::WATER_LOSS_FEVER.
Member Data Documentation
EVENT_INTERVAL_MAX
const float FeverMdfr::EVENT_INTERVAL_MAX = 18 static private
Definition at line 7 of file Fever.c.
Referenced by OnTick().
EVENT_INTERVAL_MIN
const float FeverMdfr::EVENT_INTERVAL_MIN = 12 static private
Definition at line 6 of file Fever.c.
Referenced by OnTick().
m_NextEvent
float FeverMdfr::m_NextEvent private
Definition at line 4 of file Fever.c.
Referenced by OnTick().
m_Time
float FeverMdfr::m_Time private
Definition at line 3 of file Fever.c.
Referenced by OnTick().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/PlayerModifiers/Modifiers/conditions/Fever.c