DayZ: ActionUnrestrainTarget Class Reference
ActionUnrestrainTarget Class Reference
Private Member Functions
void ActionUnrestrainTarget ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 51 of file ActionUnrestrainTarget.c.
Constructor & Destructor Documentation
ActionUnrestrainTarget()
void ActionUnrestrainTarget::ActionUnrestrainTarget () inline private
Definition at line 53 of file ActionUnrestrainTarget.c.
  {
    m_CallbackClass = ActionUnrestrainTargetCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_UNRESTRAINTARGET;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
    m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
    m_Text = "#unrestrain";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionUnrestrainTarget::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 69 of file ActionUnrestrainTarget.c.
  {
    PlayerBase other_player = PlayerBase.Cast(target.GetObject());
    EntityAI item_in_hands_source = player.GetItemInHands();
    if (other_player.IsRestrained())
    {
      //Print("is restrained");
      EntityAI item_in_hands_target = other_player.GetItemInHands();
      CachedObjectsArrays.ARRAY_STRING.Clear();
      if (item_in_hands_target)
      {
        item_in_hands_target.ConfigGetTextArray("CanBeUnrestrainedBy", CachedObjectsArrays.ARRAY_STRING);
        string item_in_hands_name = item_in_hands_source.GetType();
        for (int i = 0; i < CachedObjectsArrays.ARRAY_STRING.Count(); i++)
        {
          if ((i % 2) == 0)
          {
            string class_name = CachedObjectsArrays.ARRAY_STRING.Get(i);
            if (GetGame().IsKindOf(item_in_hands_name, class_name))
              return true;
          }
        }
      }
    }
    return false;
  }
References CachedObjectsArrays::ARRAY_STRING, class_name, and GetGame().
CreateConditionComponents()
override void ActionUnrestrainTarget::CreateConditionComponents () inline private
Definition at line 63 of file ActionUnrestrainTarget.c.
  {
    m_ConditionTarget = new CCTMan(UAMaxDistances.DEFAULT, false);
    m_ConditionItem = new CCINonRuined;
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnFinishProgressServer()
override void ActionUnrestrainTarget::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 101 of file ActionUnrestrainTarget.c.
  {
    PlayerBase player_target = PlayerBase.Cast(action_data.m_Target.GetObject());
    PlayerBase player_source = PlayerBase.Cast(action_data.m_Player);
    if (CanReceiveAction(action_data.m_Target) && player_target.IsRestrained())
    {
      EntityAI unrestraining_tool = action_data.m_MainItem;
      EntityAI restraining_item = player_target.GetItemInHands();
      player_target.SetRestrained(false);
      //Damage applied to tool
      CachedObjectsArrays.ARRAY_STRING.Clear();
      restraining_item.ConfigGetTextArray("CanBeUnrestrainedBy", CachedObjectsArrays.ARRAY_STRING);
      restraining_item.ConfigGetFloatArray("CanBeUnrestrainedByDMG", CachedObjectsArrays.ARRAY_FLOAT);
      string item_in_hands_name = unrestraining_tool.GetType();
      float damageToTool = 0;
      for (int i = 0; i < CachedObjectsArrays.ARRAY_STRING.Count(); i++)
      {
        string class_name = CachedObjectsArrays.ARRAY_STRING.Get(i);
        if (GetGame().IsKindOf(item_in_hands_name, class_name))
        {
          damageToTool = CachedObjectsArrays.ARRAY_FLOAT.Get(i / 2);
          break;
        }
      }
      MiscGameplayFunctions.DealAbsoluteDmg(action_data.m_MainItem, damageToTool);
      //---------------------------
      MiscGameplayFunctions.TransformRestrainItem(restraining_item, unrestraining_tool, player_source, player_target);
      action_data.m_Player.GetSoftSkillsManager().AddSpecialty(m_SpecialtyWeight);
    }
  }
References CachedObjectsArrays::ARRAY_FLOAT, CachedObjectsArrays::ARRAY_STRING, CanReceiveAction(), class_name, GetGame(), and m_SpecialtyWeight.
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionUnrestrainTarget.c