DayZ: FireworksLauncherClientEvent Class Reference
FireworksLauncherClientEvent Class Reference
Protected Member Functions
int GetSoundDelay ()
int GetLightDelay ()
float GetExplosionDistance ()
float GetShotDispersionAngle ()
string GetExplosionSoundSet ()
float GetExplosionDelay ()
void FireworksLauncherClientEvent (FireworksLauncher item, int index)
void ~FireworksLauncherClientEvent ()
void OnFired ()
vector GetShotPos ()
void CalculateExplosionPosition ()
vector GetExplosionPosition ()
int GetSecondaryExplosionCount ()
void OnExplode ()
void RequestSecondaryExplosion ()
void SpawnSecondaryExplosion ()
int GetSecondaryExplosionDelay ()
int GetExplParticleFromSequence ()
void SetupLight (PointLightBase light)
void SpawnLight ()
void PlayExplosionSound ()
Protected Attributes
ref Timer m_Timer = new Timer()
FireworksLauncher m_Item
int m_Index
vector m_ExplosionPos
EffectSound m_FireSound
EffectSound m_ExplosionSound
ParticleSource m_ParticleShot
ParticleSource m_ParticleExplosion
vector m_ShotDir
ExplosionLight m_ExplosionLight
ParticleSource m_ParticleAfterBurnEnd
string m_Color
int m_RemainingExplosions = GetSecondaryExplosionCount()
ref array< ref FireworksLauncherClientEventBase > m_Events = new ref array<ref FireworksLauncherClientEventBase>
Detailed Description
Definition at line 28 of file FireworksLauncher.c.
Constructor & Destructor Documentation
FireworksLauncherClientEvent()
void FireworksLauncherClientEvent::FireworksLauncherClientEvent (FireworksLauncher item, int index) inline protected
Definition at line 88 of file FireworksLauncher.c.
  {
    m_Item = item;
    m_Index = index;
    int colorSequenceLastIndex = m_Item.GetColorSequence().Length() - 1;
    int coloreSequenceIndex = m_Index - 1;//shot index(m_Index) starts at 1
    if (colorSequenceLastIndex >= coloreSequenceIndex)
      m_Color = m_Item.GetColorSequence().Get(coloreSequenceIndex);
    else
    {
      Debug.LogError("Failed to obtain color from color sequence");
      m_Color = "B";
    }
  }
References string::Get(), FireworksLauncher::GetColorSequence(), string::Length(), Debug::LogError(), m_Color, m_Index, and m_Item.
~FireworksLauncherClientEvent()
void FireworksLauncherClientEvent::~FireworksLauncherClientEvent () inline protected
Definition at line 105 of file FireworksLauncher.c.
  {
    SEffectManager.DestroyEffect(m_FireSound);
    SEffectManager.DestroyEffect(m_ExplosionSound);
    if (m_ParticleAfterBurnEnd)
      m_ParticleAfterBurnEnd.StopParticle();
  }
References SEffectManager::DestroyEffect(), m_ExplosionSound, m_FireSound, m_ParticleAfterBurnEnd, and ParticleSource::StopParticle().
Member Function Documentation
CalculateExplosionPosition()
void FireworksLauncherClientEvent::CalculateExplosionPosition () inline protected
Definition at line 151 of file FireworksLauncher.c.
  {
    m_ExplosionPos = GetShotPos() + m_ShotDir * GetExplosionDistance();
  }
References GetExplosionDistance(), GetShotPos(), m_ExplosionPos, and m_ShotDir.
Referenced by GetExplosionPosition().
GetExplosionDelay()
float FireworksLauncherClientEvent::GetExplosionDelay () inline protected
Definition at line 78 of file FireworksLauncher.c.
  {
    return Math.RandomFloatInclusive(1.5, 1.75);
  }
References Math::RandomFloatInclusive().
Referenced by OnFired().
GetExplosionDistance()
float FireworksLauncherClientEvent::GetExplosionDistance () inline protected
Definition at line 63 of file FireworksLauncher.c.
  {
    return Math.RandomFloatInclusive(35, 40);
  }
References Math::RandomFloatInclusive().
Referenced by CalculateExplosionPosition(), and OnFired().
GetExplosionPosition()
vector FireworksLauncherClientEvent::GetExplosionPosition () inline protected
Definition at line 156 of file FireworksLauncher.c.
  {
    if (!m_ExplosionPos)
      CalculateExplosionPosition();
    return m_ExplosionPos;
  }
References CalculateExplosionPosition(), and m_ExplosionPos.
Referenced by OnExplode(), SpawnLight(), SpawnSecondaryExplosion(), and AnniversaryFireworksLauncherClientEvent::SpawnSecondaryExplosion().
GetExplosionSoundSet()
string FireworksLauncherClientEvent::GetExplosionSoundSet () inline protected
Definition at line 73 of file FireworksLauncher.c.
  {
    return "FireworksLauncher_Explosion_SoundSet";
  }
Referenced by PlayExplosionSound().
GetExplParticleFromSequence()
int FireworksLauncherClientEvent::GetExplParticleFromSequence () inline protected
Definition at line 211 of file FireworksLauncher.c.
  {
    switch (m_Color)
    {
    case "R":
      return ParticleList.FIREWORKS_EXPLOSION_RED;
    case "G":
      return ParticleList.FIREWORKS_EXPLOSION_GREEN;
    case "B":
      return ParticleList.FIREWORKS_EXPLOSION_BLUE;
    case "Y":
      return ParticleList.FIREWORKS_EXPLOSION_YELLOW;
    case "P":
      return ParticleList.FIREWORKS_EXPLOSION_PINK;
    default:
      ErrorEx("Incorrect explosion particle color in the sequence");
    }
    return ParticleList.FIREWORKS_EXPLOSION_RED;
  }
References ErrorEx, ParticleList::FIREWORKS_EXPLOSION_BLUE, ParticleList::FIREWORKS_EXPLOSION_GREEN, ParticleList::FIREWORKS_EXPLOSION_PINK, ParticleList::FIREWORKS_EXPLOSION_RED, ParticleList::FIREWORKS_EXPLOSION_YELLOW, and m_Color.
Referenced by OnExplode().
GetLightDelay()
int FireworksLauncherClientEvent::GetLightDelay () inline protected
Definition at line 58 of file FireworksLauncher.c.
  {
    return 0;
  }
Referenced by OnExplode().
GetSecondaryExplosionCount()
int FireworksLauncherClientEvent::GetSecondaryExplosionCount () inline protected
Definition at line 163 of file FireworksLauncher.c.
  {
    return 4;
  }
GetSecondaryExplosionDelay()
int FireworksLauncherClientEvent::GetSecondaryExplosionDelay () inline protected
Definition at line 206 of file FireworksLauncher.c.
  {
    return Math.RandomIntInclusive(100, 250);
  }
References Math::RandomIntInclusive().
Referenced by RequestSecondaryExplosion().
GetShotDispersionAngle()
float FireworksLauncherClientEvent::GetShotDispersionAngle () inline protected
Definition at line 68 of file FireworksLauncher.c.
  {
    return Math.RandomFloatInclusive(-25, 25); //this is rotated 360 degrees around the UP vector too
  }
References Math::RandomFloatInclusive().
Referenced by OnFired().
GetShotPos()
vector FireworksLauncherClientEvent::GetShotPos () inline protected
Definition at line 133 of file FireworksLauncher.c.
  {
    vector memPos;
    string memName = "Shot_" + m_Index;
    if (m_Item.MemoryPointExists(memName))
    {
      memPos = m_Item.GetMemoryPointPos(memName);
      memPos = m_Item.ModelToWorld(memPos);
    }
    else
    {
      memPos = m_Item.GetPosition();//fallback to item's location
      Debug.LogError("Missing shot memory point on Fireworks");
    }
    return memPos;
  }
References Debug::LogError(), m_Index, and m_Item.
Referenced by CalculateExplosionPosition(), and OnFired().
GetSoundDelay()
int FireworksLauncherClientEvent::GetSoundDelay () inline protected
Definition at line 53 of file FireworksLauncher.c.
  {
    return 0;
  }
Referenced by OnExplode().
OnExplode()
void FireworksLauncherClientEvent::OnExplode () inline protected
Definition at line 169 of file FireworksLauncher.c.
  {
#ifdef DEVELOPER
    if (m_ShotTrajectory)
    {
      m_ShotTrajectory.Destroy();
      m_ShotTrajectory = null;
    }
#endif
    m_ParticleAfterBurnEnd.Stop();
    GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(PlayExplosionSound, GetSoundDelay(), false);
    GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(SpawnLight, GetLightDelay(), false);
    m_ParticleExplosion = ParticleManager.GetInstance().PlayInWorld(GetExplParticleFromSequence(), GetExplosionPosition());
    RequestSecondaryExplosion();
  }
References CALL_CATEGORY_SYSTEM, GetExplosionPosition(), GetExplParticleFromSequence(), GetGame(), GetLightDelay(), GetSoundDelay(), m_ParticleAfterBurnEnd, m_ParticleExplosion, ParticleManager(), PlayExplosionSound(), RequestSecondaryExplosion(), SpawnLight(), and Particle::Stop().
OnFired()
void FireworksLauncherClientEvent::OnFired () inline protected
Definition at line 113 of file FireworksLauncher.c.
  {
    m_Timer.Run(GetExplosionDelay(), this, "OnExplode", null);
    m_Item.PlaySoundSet(m_FireSound, "FireworksLauncher_Shot_SoundSet", 0, 0);
    m_ParticleShot = ParticleManager.GetInstance().PlayInWorld(ParticleList.FIREWORKS_SHOT, GetShotPos());
    m_ParticleShot.SetYawPitchRoll(Vector(Math.RandomFloatInclusive(0, 360), GetShotDispersionAngle(), 0));
    m_ParticleAfterBurnEnd = ParticleManager.GetInstance().PlayInWorld(ParticleList.FIREWORKS_AFTERBURN_END, GetShotPos());
    if (m_ParticleAfterBurnEnd)
      m_ParticleAfterBurnEnd.SetOwner(this);
    m_ShotDir = m_ParticleShot.GetDirectionUp();
#ifdef DEVELOPER
    vector pts[2];
    pts[0] = GetShotPos();
    pts[1] = GetShotPos() + m_ShotDir * GetExplosionDistance();
    //m_ShotTrajectory = Shape.CreateLines(COLOR_RED, ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE|ShapeFlags.NOZBUFFER, pts, 2);
#endif
  }
References ParticleList::FIREWORKS_AFTERBURN_END, ParticleList::FIREWORKS_SHOT, GetExplosionDelay(), GetExplosionDistance(), GetShotDispersionAngle(), GetShotPos(), m_FireSound, m_Item, m_ParticleAfterBurnEnd, m_ParticleShot, m_ShotDir, m_Timer, ParticleManager(), Math::RandomFloatInclusive(), ParticleSource::SetOwner(), and Vector().
PlayExplosionSound()
void FireworksLauncherClientEvent::PlayExplosionSound () inline protected
Definition at line 267 of file FireworksLauncher.c.
  {
    if (m_FireSound)
      m_FireSound.Stop();
    m_Item.PlaySoundSet(m_ExplosionSound, GetExplosionSoundSet(), 0, 0);
  }
References GetExplosionSoundSet(), m_ExplosionSound, m_FireSound, m_Item, and EffectSound::Stop().
Referenced by OnExplode().
RequestSecondaryExplosion()
void FireworksLauncherClientEvent::RequestSecondaryExplosion () inline protected
Definition at line 188 of file FireworksLauncher.c.
  {
    if (m_RemainingExplosions > 0)
    {
      m_RemainingExplosions--;
      GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(SpawnSecondaryExplosion, GetSecondaryExplosionDelay(), false);
    }
  }
References CALL_CATEGORY_SYSTEM, GetGame(), GetSecondaryExplosionDelay(), m_RemainingExplosions, and SpawnSecondaryExplosion().
Referenced by OnExplode(), SpawnSecondaryExplosion(), and AnniversaryFireworksLauncherClientEvent::SpawnSecondaryExplosion().
SetupLight()
void FireworksLauncherClientEvent::SetupLight (PointLightBase light) inline protected
Definition at line 231 of file FireworksLauncher.c.
  {
    switch (m_Color)
    {
    case "R":
      light.SetDiffuseColor(255, 51, 51);
      light.SetAmbientColor(255, 51, 51);
      break;
    case "G":
      light.SetDiffuseColor(0, 255, 128);
      light.SetAmbientColor(0, 255, 128);
      break;
    case "B":
      light.SetDiffuseColor(51, 153, 255);
      light.SetAmbientColor(51, 153, 255);
      break;
    case "Y":
      light.SetDiffuseColor(255, 255, 51);
      light.SetAmbientColor(255, 255, 51);
      break;
    case "P":
      light.SetDiffuseColor(255, 102, 255);
      light.SetAmbientColor(255, 102, 255);
      break;
    default:
      ErrorEx("Incorrect explosion particle color in the sequence");
    }
  }
References ErrorEx, and m_Color.
Referenced by SpawnLight().
SpawnLight()
void FireworksLauncherClientEvent::SpawnLight () inline protected
Definition at line 261 of file FireworksLauncher.c.
  {
    m_ExplosionLight = ExplosionLight.Cast(ScriptedLightBase.CreateLight(ExplosionLight, GetExplosionPosition()));
    SetupLight(m_ExplosionLight);
  }
References GetExplosionPosition(), m_ExplosionLight, and SetupLight().
Referenced by OnExplode().
SpawnSecondaryExplosion()
void FireworksLauncherClientEvent::SpawnSecondaryExplosion () inline protected
Definition at line 197 of file FireworksLauncher.c.
  {
    FireworksLauncherClientEventSecondary evnt = new FireworksLauncherClientEventSecondary(m_Item, m_Index);
    evnt.Init(GetExplosionPosition());
    evnt.OnExplode();
    m_Events.Insert(evnt);
    RequestSecondaryExplosion();
  }
References GetExplosionPosition(), m_Events, m_Index, m_Item, and RequestSecondaryExplosion().
Referenced by RequestSecondaryExplosion().
Member Data Documentation
m_Color
string FireworksLauncherClientEvent::m_Color protected
Definition at line 41 of file FireworksLauncher.c.
Referenced by FireworksLauncherClientEvent(), GetExplParticleFromSequence(), AnniversaryFireworksLauncherClientEvent::GetExplParticleFromSequence(), SetupLight(), and AnniversaryFireworksLauncherClientEvent::SetupLight().
m_Events
ref array<ref FireworksLauncherClientEventBase> FireworksLauncherClientEvent::m_Events = new ref array<ref FireworksLauncherClientEventBase> protected
Definition at line 43 of file FireworksLauncher.c.
Referenced by SpawnSecondaryExplosion(), and AnniversaryFireworksLauncherClientEvent::SpawnSecondaryExplosion().
m_ExplosionLight
ExplosionLight FireworksLauncherClientEvent::m_ExplosionLight protected
Definition at line 39 of file FireworksLauncher.c.
Referenced by SpawnLight().
m_ExplosionPos
vector FireworksLauncherClientEvent::m_ExplosionPos protected
Definition at line 33 of file FireworksLauncher.c.
Referenced by CalculateExplosionPosition(), and GetExplosionPosition().
m_ExplosionSound
EffectSound FireworksLauncherClientEvent::m_ExplosionSound protected
Definition at line 35 of file FireworksLauncher.c.
Referenced by PlayExplosionSound(), and ~FireworksLauncherClientEvent().
m_FireSound
EffectSound FireworksLauncherClientEvent::m_FireSound protected
Definition at line 34 of file FireworksLauncher.c.
Referenced by OnFired(), PlayExplosionSound(), and ~FireworksLauncherClientEvent().
m_Index
int FireworksLauncherClientEvent::m_Index protected
Definition at line 32 of file FireworksLauncher.c.
Referenced by FireworksLauncherClientEvent(), GetShotPos(), SpawnSecondaryExplosion(), and AnniversaryFireworksLauncherClientEvent::SpawnSecondaryExplosion().
m_Item
FireworksLauncher FireworksLauncherClientEvent::m_Item protected
Definition at line 31 of file FireworksLauncher.c.
Referenced by FireworksLauncherClientEvent(), GetShotPos(), OnFired(), PlayExplosionSound(), SpawnSecondaryExplosion(), and AnniversaryFireworksLauncherClientEvent::SpawnSecondaryExplosion().
m_ParticleAfterBurnEnd
ParticleSource FireworksLauncherClientEvent::m_ParticleAfterBurnEnd protected
Definition at line 40 of file FireworksLauncher.c.
Referenced by OnExplode(), OnFired(), and ~FireworksLauncherClientEvent().
m_ParticleExplosion
ParticleSource FireworksLauncherClientEvent::m_ParticleExplosion protected
Definition at line 37 of file FireworksLauncher.c.
Referenced by OnExplode().
m_ParticleShot
ParticleSource FireworksLauncherClientEvent::m_ParticleShot protected
Definition at line 36 of file FireworksLauncher.c.
Referenced by OnFired().
m_RemainingExplosions
int FireworksLauncherClientEvent::m_RemainingExplosions = GetSecondaryExplosionCount() protected
Definition at line 42 of file FireworksLauncher.c.
Referenced by RequestSecondaryExplosion().
m_ShotDir
vector FireworksLauncherClientEvent::m_ShotDir protected
Definition at line 38 of file FireworksLauncher.c.
Referenced by CalculateExplosionPosition(), and OnFired().
m_Timer
ref Timer FireworksLauncherClientEvent::m_Timer = new Timer() protected
Definition at line 30 of file FireworksLauncher.c.
Referenced by OnFired().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Gear/Tools/FireworksLauncher.c