DayZ: InventoryGridController Class Reference
InventoryGridController Class Reference
Protected Member Functions
void InventoryQuickbar (Widget quickbarGridWidget)
void ~InventoryQuickbar ()
void UpdateItems (Widget quickbarGridWidget)
void Remove (InventoryItem itemToRemove)
override void OnItemEnter (InventoryGrid grid, Widget w, int row, int col)
override void OnItemLeave (InventoryGrid grid, Widget w)
override void OnItemDraggingOver (InventoryGrid grid, Widget w, int row, int col)
override void OnItemDropReceived (InventoryGrid grid, Widget w, int row, int col)
override void OnItemDrop (InventoryGrid grid, Widget w, int row, int col)
override void OnItemDrag (InventoryGrid grid, Widget w, int row, int col)
override int GetQuickbarItemColor (InventoryGrid grid, InventoryItem item)
override int HasItemQuantity (InventoryItem item)
override string GetItemQuantityText (InventoryItem item)
override float GetItemQuantity (InventoryItem item)
override int GetItemQuantityMax (InventoryItem item)
override int GetItemCount (InventoryItem item)
override bool CanAddItemInHandToInventory ()
Protected Attributes
ref TItemsMap m_Items
InventoryGrid m_Grid
int m_DraggingIndex
Detailed Description
Definition at line 1 of file InventoryQuickbar.c.
Constructor & Destructor Documentation
~InventoryQuickbar()
void InventoryGridController::~InventoryQuickbar () inline protected
Definition at line 15 of file InventoryQuickbar.c.
  {
  }
Member Function Documentation
CanAddItemInHandToInventory()
override bool InventoryGridController::CanAddItemInHandToInventory () inline protected
Definition at line 255 of file InventoryQuickbar.c.
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    EntityAI itemInHand = player.GetHumanInventory().GetEntityInHands();
    return itemInHand && player.GetInventory().CanAddEntityToInventory(itemInHand);
  }
References GetGame(), and GetPlayer().
Referenced by ScriptedWidgetEventHandler::UpdateQuickbarItems().
GetItemCount()
override int InventoryGridController::GetItemCount (InventoryItem item) inline protected
Definition at line 249 of file InventoryQuickbar.c.
  {
    ItemBase ib = ItemBase.Cast(item);
    return ib.m_Count;
  }
Referenced by ScriptedWidgetEventHandler::RefreshItemVariables().
GetItemQuantity()
override float InventoryGridController::GetItemQuantity (InventoryItem item) inline protected
Definition at line 238 of file InventoryQuickbar.c.
  {
    return QuantityConversions.GetItemQuantity(item);
  }
References QuantityConversions::GetItemQuantity().
Referenced by ScriptedWidgetEventHandler::RefreshItemVariables().
GetItemQuantityMax()
override int InventoryGridController::GetItemQuantityMax (InventoryItem item) inline protected
Definition at line 243 of file InventoryQuickbar.c.
  {
    ItemBase ib = ItemBase.Cast(item);
    return ib.m_VarQuantityMax;
  }
Referenced by ScriptedWidgetEventHandler::RefreshItemVariables().
GetItemQuantityText()
override string InventoryGridController::GetItemQuantityText (InventoryItem item) inline protected
Definition at line 233 of file InventoryQuickbar.c.
  {
    return QuantityConversions.GetItemQuantityText(item);
  }
References QuantityConversions::GetItemQuantityText().
Referenced by ScriptedWidgetEventHandler::RefreshItemVariables().
GetQuickbarItemColor()
override int InventoryGridController::GetQuickbarItemColor (InventoryGrid grid, InventoryItem item) inline protected
Definition at line 207 of file InventoryQuickbar.c.
  {
    int color = 0x0AFFFFFF;
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    EntityAI itemInHand = player.GetHumanInventory().GetEntityInHands();
    if (player && itemInHand == item)
    {
      if (player.GetHumanInventory().FindUserReservedLocationIndex(item) != -1 || grid.CanAddItemInHandToInventory())
        color = InventoryGrid.ITEM_COLOR_QUICKBAR_H_GOOD;
      else
        color = InventoryGrid.ITEM_COLOR_QUICKBAR_H_BAD;
    }
    else if (itemInHand)
    {
      if (!grid.CanAddItemInHandToInventory() && !GameInventory.CanSwapEntitiesEx(item, itemInHand))
        color = InventoryGrid.ITEM_COLOR_QUICKBAR_I_BAD;
    }
    return color;
  }
References GameInventory::CanSwapEntitiesEx(), GetGame(), and GetPlayer().
Referenced by ScriptedWidgetEventHandler::RefreshQuickbarItemVariables().
HasItemQuantity()
override int InventoryGridController::HasItemQuantity (InventoryItem item) inline protected
Definition at line 228 of file InventoryQuickbar.c.
  {
    return QuantityConversions.HasItemQuantity(item);
  }
References QuantityConversions::HasItemQuantity().
Referenced by ScriptedWidgetEventHandler::RefreshItemVariables().
InventoryQuickbar()
void InventoryGridController::InventoryQuickbar (Widget quickbarGridWidget) inline protected
Definition at line 8 of file InventoryQuickbar.c.
  {
    m_DraggingIndex = INDEX_NOT_FOUND;
    m_Items = new TItemsMap;
    UpdateItems(quickbarGridWidget);
  }
References INDEX_NOT_FOUND, and UpdateItems().
OnItemDrag()
override void InventoryGridController::OnItemDrag (InventoryGrid grid, Widget w, int row, int col) inline protected
Definition at line 196 of file InventoryQuickbar.c.
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    InventoryItem item = InventoryItem.Cast(player.GetQuickBarEntity(col));
    if (item)
    {
      m_DraggingIndex = col;
      m_Grid.SetItemColor(item, InventoryGrid.ITEM_COLOR_DRAG);
    }
  }
References GetGame(), and GetPlayer().
Referenced by ScriptedWidgetEventHandler::OnDrag().
OnItemDraggingOver()
override void InventoryGridController::OnItemDraggingOver (InventoryGrid grid, Widget w, int row, int col) inline protected
Definition at line 89 of file InventoryQuickbar.c.
  {
    ItemPreviewWidget iw;
    InventoryItem dragged_item;
    iw = ItemPreviewWidget.Cast(w.FindAnyWidget("Render"));
    if (!iw)
    {
      string name = w.GetName();
      name.Replace("PanelWidget", "Render");
      iw = ItemPreviewWidget.Cast(w.FindAnyWidget(name));
    }
    if (!iw || !iw.GetItem())
      return;
    if (!dragged_item && iw)
      dragged_item = InventoryItem.Cast(iw.GetItem());
    if (dragged_item == NULL)
      return;
    if (dragged_item && dragged_item.GetInventory().CanRemoveEntity() == false)
    {
      int color;
      color = ARGB(150, 255, 1, 1);
      if (w.FindAnyWidget("Cursor"))
        w.FindAnyWidget("Cursor").SetColor(color);
      else
      {
        name = w.GetName();
        name.Replace("PanelWidget", "Cursor");
        if (w.FindAnyWidget(name))
          w.FindAnyWidget(name).SetColor(color);
      }
    }
    else
    {
      color = ARGB(150, 1, 255, 1);
      if (w.FindAnyWidget("Cursor"))
        w.FindAnyWidget("Cursor").SetColor(color);
      else
      {
        name = w.GetName();
        name.Replace("PanelWidget", "Cursor");
        if (w.FindAnyWidget(name))
          w.FindAnyWidget(name).SetColor(color);
      }
    }
  }
References ARGB(), and name.
Referenced by ScriptedWidgetEventHandler::OnDraggingOver().
OnItemDrop()
override void InventoryGridController::OnItemDrop (InventoryGrid grid, Widget w, int row, int col) inline protected
Definition at line 180 of file InventoryQuickbar.c.
  {
    if (m_DraggingIndex != INDEX_NOT_FOUND)
    {
      PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
      InventoryItem dragged_item = InventoryItem.Cast(player.GetQuickBarEntity(m_DraggingIndex));
      Remove(dragged_item);
      m_DraggingIndex = INDEX_NOT_FOUND;
    }
    InventoryMenu menu = InventoryMenu.Cast(GetGame().GetUIManager().FindMenu(MENU_INVENTORY));
    if (menu)
      menu.RefreshQuickbar();
    ItemManager.GetInstance().HideDropzones();
  }
References GetGame(), ItemManager::GetInstance(), GetPlayer(), INDEX_NOT_FOUND, InventoryMenu(), MENU_INVENTORY, and Remove().
Referenced by ScriptedWidgetEventHandler::OnDrop().
OnItemDropReceived()
override void InventoryGridController::OnItemDropReceived (InventoryGrid grid, Widget w, int row, int col) inline protected
Definition at line 142 of file InventoryQuickbar.c.
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    ItemBase dragged_item = ItemBase.Cast(ItemManager.GetInstance().GetDraggedItem());
    ItemPreviewWidget iw = ItemPreviewWidget.Cast(w.FindAnyWidget("Render"));
    if (!iw)
    {
      string name = w.GetName();
      name.Replace("PanelWidget", "Render");
      iw = ItemPreviewWidget.Cast(w.FindAnyWidget(name));
    }
    if (!dragged_item && iw)
      dragged_item = ItemBase.Cast(iw.GetItem());
    if (dragged_item && dragged_item.GetHierarchyRootPlayer() != GetGame().GetPlayer())
      return;
    ItemBase quickbar_item = ItemBase.Cast(player.GetQuickBarEntity(col));
    if (m_DraggingIndex != INDEX_NOT_FOUND)
      dragged_item = ItemBase.Cast(player.GetQuickBarEntity(m_DraggingIndex));
    if (dragged_item && dragged_item.GetInventory().CanRemoveEntity())
    {
      player.SetQuickBarEntityShortcut(dragged_item, col);
      if (quickbar_item && quickbar_item != dragged_item && m_DraggingIndex != INDEX_NOT_FOUND)
        player.SetQuickBarEntityShortcut(quickbar_item, m_DraggingIndex);
    }
    m_DraggingIndex = INDEX_NOT_FOUND;
    InventoryMenu menu = InventoryMenu.Cast(GetGame().GetUIManager().FindMenu(MENU_INVENTORY));
    if (menu)
      menu.RefreshQuickbar();
  }
References GetGame(), ItemManager::GetInstance(), GetPlayer(), INDEX_NOT_FOUND, InventoryMenu(), MENU_INVENTORY, and name.
Referenced by ScriptedWidgetEventHandler::OnDropReceived().
OnItemEnter()
override void InventoryGridController::OnItemEnter (InventoryGrid grid, Widget w, int row, int col) inline protected
Definition at line 71 of file InventoryQuickbar.c.
  {
    Widget quickbar = grid.GetRoot();
    if (quickbar)
    {
      // quickbar.SetColor( 0xFFFFFFFF );
    }
  }
Referenced by ScriptedWidgetEventHandler::OnMouseEnter().
OnItemLeave()
override void InventoryGridController::OnItemLeave (InventoryGrid grid, Widget w) inline protected
Definition at line 80 of file InventoryQuickbar.c.
  {
    Widget quickbar = grid.GetRoot();
    if (quickbar)
    {
      // quickbar.SetColor( 0x7FFFFFFF );
    }
  }
Referenced by ScriptedWidgetEventHandler::OnMouseLeave().
Remove()
void InventoryGridController::Remove (InventoryItem itemToRemove) inline protected
Definition at line 58 of file InventoryQuickbar.c.
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    for (int i = 0; i < m_Grid.GetGridSize(); i++)
    {
      InventoryItem item = InventoryItem.Cast(player.GetQuickBarEntity(i));
      if (item == itemToRemove)
        player.RemoveQuickBarEntityShortcut(item);
    }
  }
References GetGame(), and GetPlayer().
Referenced by OnItemDrop().
UpdateItems()
void InventoryGridController::UpdateItems (Widget quickbarGridWidget) inline protected
Definition at line 19 of file InventoryQuickbar.c.
  {
    if (!quickbarGridWidget)
      return;
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (!player)
      return;
    int i;
    // create grid and align it to center
    if (!m_Grid)
    {
      quickbarGridWidget.GetScript(m_Grid);
      m_Grid.SetController(this);
      m_Grid.GenerateQuickBarBackgroundTiles(10);
    }
    m_Items.Clear();
    InventoryItem item;
    if (m_Grid)
    {
      if (m_Grid.GetGridSize() != player.GetQuickBarSize())
        m_Grid.SetGridSize(player.GetQuickBarSize());
    }
    for (i = 0; i < m_Grid.GetGridSize(); i++)
    {
      item = InventoryItem.Cast(player.GetQuickBarEntity(i));
      if (item)
        m_Items.Set(item, Vector(i, 1, 1));
    }
    if (m_Grid)
      m_Grid.UpdateQuickbarItems(m_Items);
  }
References GetGame(), GetPlayer(), and Vector().
Referenced by InventoryQuickbar().
Member Data Documentation
m_DraggingIndex
int InventoryGridController::m_DraggingIndex protected
Definition at line 6 of file InventoryQuickbar.c.
m_Grid
InventoryGrid InventoryGridController::m_Grid protected
Definition at line 5 of file InventoryQuickbar.c.
m_Items
ref TItemsMap InventoryGridController::m_Items protected
Definition at line 4 of file InventoryQuickbar.c.
The documentation for this class was generated from the following file:
scripts/5_Mission/GUI/Inventory/InventoryQuickbar.c