DayZ: HelmetBase Class Reference
HelmetBase Class Reference
Protected Member Functions
set< int > GetAttachmentExclusionInitSlotValue (int slotId)
set< int > GetAttachmentExclusionInitSlotValue (int slotId)
void InitGlobalExclusionValues ()
set< int > GetAttachmentExclusionInitSlotValue (int slotId)
set< int > GetAttachmentExclusionInitSlotValue (int slotId)
set< int > GetAttachmentExclusionInitSlotValue (int slotId)
Private Member Functions
override array< int > GetEffectWidgetTypes ()
override bool IsObstructingVoice ()
override int GetVoiceEffect ()
override array< int > GetEffectWidgetTypes ()
override bool IsObstructingVoice ()
override int GetVoiceEffect ()
override int GetGlassesEffectID ()
override void OnDebugSpawn ()
override void OnDebugSpawn ()
override void SetActions ()
override void OnDebugSpawn ()
override array< int > GetEffectWidgetTypes ()
override bool IsObstructingVoice ()
override int GetVoiceEffect ()
override array< int > GetEffectWidgetTypes ()
override array< int > GetEffectWidgetTypes ()
override int GetGlassesEffectID ()
Detailed Description
Definition at line 1 of file GreatHelm.c.
Member Function Documentation
GetAttachmentExclusionInitSlotValue() [1/5]
set< int > HelmetBase::GetAttachmentExclusionInitSlotValue (int slotId) inline protected
Definition at line 18 of file GreatHelm.c.
  {
    set<int> ret = super.GetAttachmentExclusionInitSlotValue(slotId);
    if (slotId == InventorySlots.HEADGEAR)
    {
      ret.Insert(EAttExclusions.EXCLUSION_HEADGEAR_HELMET_0);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_0);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_1);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_2);
      ret.Insert(EAttExclusions.EXCLUSION_HEADSTRAP_0);
      ret.Insert(EAttExclusions.SHAVING_HEADGEAR_ATT_0);
    }
    return ret;
  }
GetAttachmentExclusionInitSlotValue() [2/5]
set< int > HelmetBase::GetAttachmentExclusionInitSlotValue (int slotId) inline protected
Definition at line 23 of file DarkMotoHelmet_ColorBase.c.
  {
    set<int> ret = super.GetAttachmentExclusionInitSlotValue(slotId);
    if (slotId == InventorySlots.HEADGEAR)
    {
      ret.Insert(EAttExclusions.EXCLUSION_HEADGEAR_HELMET_0);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_0);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_1);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_2);
      ret.Insert(EAttExclusions.EXCLUSION_HEADSTRAP_0);
      ret.Insert(EAttExclusions.SHAVING_HEADGEAR_ATT_0);
    }
    return ret;
  }
GetAttachmentExclusionInitSlotValue() [3/5]
set< int > HelmetBase::GetAttachmentExclusionInitSlotValue (int slotId) inline protected
Definition at line 18 of file MotoHelmet_ColorBase.c.
  {
    set<int> ret = super.GetAttachmentExclusionInitSlotValue(slotId);
    if (slotId == InventorySlots.HEADGEAR)
    {
      ret.Insert(EAttExclusions.EXCLUSION_HEADGEAR_HELMET_0);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_0);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_1);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_2);
      ret.Insert(EAttExclusions.EXCLUSION_HEADSTRAP_0);
      ret.Insert(EAttExclusions.SHAVING_HEADGEAR_ATT_0);
    }
    return ret;
  }
GetAttachmentExclusionInitSlotValue() [4/5]
set< int > HelmetBase::GetAttachmentExclusionInitSlotValue (int slotId) inline protected
Definition at line 8 of file NorseHelm.c.
  {
    set<int> ret = super.GetAttachmentExclusionInitSlotValue(slotId);
    if (slotId == InventorySlots.HEADGEAR)
    {
      ret.Insert(EAttExclusions.EXCLUSION_HEADGEAR_HELMET_0);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_0);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_1);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_2);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_3);
      ret.Insert(EAttExclusions.EXCLUSION_HEADSTRAP_0);
      ret.Insert(EAttExclusions.SHAVING_HEADGEAR_ATT_0);
    }
    return ret;
  }
GetAttachmentExclusionInitSlotValue() [5/5]
set< int > HelmetBase::GetAttachmentExclusionInitSlotValue (int slotId) inline protected
Definition at line 13 of file WeldingMask.c.
  {
    set<int> ret = super.GetAttachmentExclusionInitSlotValue(slotId);
    if (slotId == InventorySlots.HEADGEAR)
    {
      ret.Insert(EAttExclusions.EXCLUSION_HEADGEAR_HELMET_0);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_0);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_1);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_2);
      ret.Insert(EAttExclusions.EXCLUSION_HEADSTRAP_0);
      ret.Insert(EAttExclusions.SHAVING_HEADGEAR_ATT_0);
    }
    return ret;
  }
GetEffectWidgetTypes() [1/5]
override array< int > HelmetBase::GetEffectWidgetTypes () inline private
Definition at line 3 of file GreatHelm.c.
  {
    return {EffectWidgetsTypes.HELMET_OCCLUDER/*,EffectWidgetsTypes.HELMET_BREATH*/};
  }
GetEffectWidgetTypes() [2/5]
override array< int > HelmetBase::GetEffectWidgetTypes () inline private
Definition at line 3 of file DarkMotoHelmet_ColorBase.c.
  {
    return {EffectWidgetsTypes.MOTO_OCCLUDER/*,EffectWidgetsTypes.MOTO_BREATH*/};
  }
GetEffectWidgetTypes() [3/5]
override array< int > HelmetBase::GetEffectWidgetTypes () inline private
Definition at line 3 of file MotoHelmet_ColorBase.c.
  {
    return {EffectWidgetsTypes.MOTO_OCCLUDER/*,EffectWidgetsTypes.MOTO_BREATH*/};
  }
GetEffectWidgetTypes() [4/5]
override array< int > HelmetBase::GetEffectWidgetTypes () inline private
Definition at line 3 of file NorseHelm.c.
  {
    return { EffectWidgetsTypes.HELMET2_OCCLUDER };
  }
GetEffectWidgetTypes() [5/5]
override array< int > HelmetBase::GetEffectWidgetTypes () inline private
Definition at line 3 of file WeldingMask.c.
  {
    return {EffectWidgetsTypes.HELMET_OCCLUDER/*,EffectWidgetsTypes.HELMET_BREATH*/};
  }
GetGlassesEffectID() [1/2]
override int HelmetBase::GetGlassesEffectID () inline private
Definition at line 18 of file DarkMotoHelmet_ColorBase.c.
  {
    return PPERequesterBank.REQ_MOTOHELMETBLACK;
  }
GetGlassesEffectID() [2/2]
override int HelmetBase::GetGlassesEffectID () inline private
Definition at line 8 of file WeldingMask.c.
  {
    return PPERequesterBank.REQ_GLASSESWELDING;
  }
GetVoiceEffect() [1/3]
override int HelmetBase::GetVoiceEffect () inline private
Definition at line 13 of file GreatHelm.c.
  {
    return VoiceEffectObstruction;
  }
GetVoiceEffect() [2/3]
override int HelmetBase::GetVoiceEffect () inline private
Definition at line 13 of file DarkMotoHelmet_ColorBase.c.
  {
    return VoiceEffectObstruction;
  }
GetVoiceEffect() [3/3]
override int HelmetBase::GetVoiceEffect () inline private
Definition at line 13 of file MotoHelmet_ColorBase.c.
  {
    return VoiceEffectObstruction;
  }
InitGlobalExclusionValues()
void HelmetBase::InitGlobalExclusionValues () inline protected
Definition at line 25 of file Mich2001Helmet.c.
  {
    super.InitGlobalExclusionValues();
    AddSingleExclusionValueGlobal(EAttExclusions.EXCLUSION_HEADSTRAP_0);
  }
IsObstructingVoice() [1/3]
override bool HelmetBase::IsObstructingVoice () inline private
Definition at line 8 of file GreatHelm.c.
  {
    return true;
  }
IsObstructingVoice() [2/3]
override bool HelmetBase::IsObstructingVoice () inline private
Definition at line 8 of file DarkMotoHelmet_ColorBase.c.
  {
    return true;
  }
IsObstructingVoice() [3/3]
override bool HelmetBase::IsObstructingVoice () inline private
Definition at line 8 of file MotoHelmet_ColorBase.c.
  {
    return true;
  }
OnDebugSpawn() [1/3]
override void HelmetBase::OnDebugSpawn () inline private
Definition at line 4 of file DirtBikeHelmet_ColorBase.c.
  {
    EntityAI entity;
    if (Class.CastTo(entity, this))
    {
      entity.GetInventory().CreateInInventory("DirtBikeHelmet_Visor");
      entity.GetInventory().CreateInInventory("DirtBikeHelmet_Mouthguard");
    }
  }
References Class::CastTo().
OnDebugSpawn() [2/3]
override void HelmetBase::OnDebugSpawn () inline private
Definition at line 4 of file GorkaHelmetComplete.c.
  {
    EntityAI entity;
    if (Class.CastTo(entity, this))
      entity.GetInventory().CreateInInventory("GorkaHelmetVisor");
  }
References Class::CastTo().
OnDebugSpawn() [3/3]
override void HelmetBase::OnDebugSpawn () inline private
Definition at line 13 of file Mich2001Helmet.c.
  {
    EntityAI entity;
    if (Class.CastTo(entity, this))
    {
      entity.GetInventory().CreateInInventory("NVGoggles");
      entity.GetInventory().CreateInInventory("UniversalLight");
      entity.GetInventory().CreateInInventory("Battery9V");
      entity.GetInventory().CreateInInventory("Battery9V");
    }
  }
References Class::CastTo().
SetActions()
override void HelmetBase::SetActions () inline private
Definition at line 3 of file Mich2001Helmet.c.
  {
    super.SetActions();
    AddAction(ActionTurnOnHelmetFlashlight); //use default light actions instead?
    AddAction(ActionTurnOffHelmetFlashlight);
    AddAction(ActionToggleNVG);
  }
References AddAction().
The documentation for this class was generated from the following files:
scripts/4_World/Entities/ItemBase/Clothing/GreatHelm.c
scripts/4_World/Entities/ItemBase/Clothing/HelmetBase/DarkMotoHelmet_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/HelmetBase/DirtBikeHelmet_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/HelmetBase/GorkaHelmetComplete.c
scripts/4_World/Entities/ItemBase/Clothing/HelmetBase/Mich2001Helmet.c
scripts/4_World/Entities/ItemBase/Clothing/HelmetBase/MotoHelmet_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/NorseHelm.c
scripts/4_World/Entities/ItemBase/Clothing/WeldingMask.c