DayZ: scripts/4_World/Classes/UndergroundHandlerClient.c File Reference
UndergroundHandlerClient.c File Reference
Enumerations
enum EUndergroundPresence { NONE , OUTER , TRANSITIONING , FULL }
Functions
void UndergroundHandlerClient (PlayerBase player)
void ~UndergroundHandlerClient ()
PPERUndergroundAcco GetRequester ()
void OnTriggerEnter (UndergroundTrigger trigger)
void OnTriggerLeave (UndergroundTrigger trigger)
void CalculateEyeAccoTarget ()
void ProcessEyeAcco (float timeSlice)
void ProcessLighting (float timeSlice)
void ProcessSound (float timeSlice)
void Tick (float timeSlice)
void ApplyEyeAcco ()
void UpdateNVGRequester (float value)
bool CalculateEyeAcco (float timeSlice)
void OnTriggerInsiderUpdate ()
void SetUndergroundPresence (UndergroundTrigger trigger)
void EnableLights (bool enable)
void OnUpdateTimerEnd ()
void OnUpdateTimerIn ()
void OnUpdateTimerOut ()
void OnUndergroundPresenceUpdate (EUndergroundPresence newPresence, EUndergroundPresence oldPresence)
Variables
enum EUndergroundPresence LIGHT_BLEND_SPEED_IN = 5
const float LIGHT_BLEND_SPEED_OUT = 1.75
const float MAX_RATIO = 0.9
const float RATIO_CUTOFF = 0
const float DISTANCE_CUTOFF = 5
const float ACCO_MODIFIER = 1
const float DEFAULT_INTERPOLATION_SPEED = 7
const string UNDERGROUND_LIGHTING = "dz\\data\\lighting\\lighting_underground.txt"
ref AnimationTimer m_AnimTimerLightBlend
PlayerBase m_Player
PPERUndergroundAcco m_Requester
PPERequester_CameraNV m_NVRequester
ref set< UndergroundTrigger > m_InsideTriggers = new set<UndergroundTrigger>()
float m_EyeAccoTarget = 1
float m_AccoInterpolationSpeed
float m_EyeAcco = 1
float m_LightingLerpTarget
float m_LightingLerp
EffectSound m_AmbientSound
UndergroundTrigger m_TransitionalTrigger
Enumeration Type Documentation
EUndergroundPresence
enum EUndergroundPresence
Enumerator
NONE
OUTER
TRANSITIONING
FULL
Definition at line 1 of file UndergroundHandlerClient.c.
{
  NONE,//player is not interacting with underground at any level
  OUTER,//player is on the outskirts of the underdound, some effects are already in effect, while others might not be
  TRANSITIONING,//player has entered underground and is in the process of screen darkening transition
  FULL//the player is now fully entered underground
}
Function Documentation
ApplyEyeAcco()
void ApplyEyeAcco () protected
Definition at line 220 of file UndergroundHandlerClient.c.
  {
#ifdef DIAG_DEVELOPER
    if (!DiagMenu.GetBool(DiagMenuIDs.UNDERGROUND_DISABLE_DARKENING))
      GetRequester().SetEyeAccommodation(m_EyeAcco);
    else
      GetRequester().SetEyeAccommodation(1);
#else
    GetRequester().SetEyeAccommodation(m_EyeAcco);
#endif
    float undergrounNVExposureCoef = m_EyeAcco;
    if (m_LightingLerp >= 1.0 || GetDayZGame().GetWorld().IsNight())
      undergrounNVExposureCoef = 1.0;
    //m_NVRequester.SetUndergroundExposureCoef(undergrounNVExposureCoef);
    UpdateNVGRequester(undergrounNVExposureCoef);
  }
References DiagMenu::GetBool(), GetDayZGame(), GetRequester(), m_EyeAcco, m_LightingLerp, and UpdateNVGRequester().
Referenced by ProcessEyeAcco().
CalculateEyeAcco()
bool CalculateEyeAcco (float timeSlice) protected
Definition at line 243 of file UndergroundHandlerClient.c.
  {
    if (m_TransitionalTrigger || !m_Player.m_UndergroundPresence || (m_EyeAccoTarget == 1))
    {
      float accoDiff = m_EyeAccoTarget - m_EyeAcco;
      float increase = accoDiff * m_AccoInterpolationSpeed * timeSlice;
      m_EyeAcco += increase;
      if (Math.AbsFloat(accoDiff) < 0.01)
      {
        m_EyeAcco = m_EyeAccoTarget;
        return true;
      }
    }
    else
      m_EyeAcco = m_EyeAccoTarget;
    return false;
  }
References Math::AbsFloat(), m_AccoInterpolationSpeed, m_EyeAcco, m_EyeAccoTarget, m_Player, and m_TransitionalTrigger.
Referenced by ProcessEyeAcco().
CalculateEyeAccoTarget()
void CalculateEyeAccoTarget () protected
Definition at line 79 of file UndergroundHandlerClient.c.
  {
    if (m_TransitionalTrigger && m_TransitionalTrigger.m_Data.Breadcrumbs.Count() >= 2)
    {
      float closestDist = float.MAX;
      float acco;
      array<float> distances = new array<float>();
      array<float> distancesInverted = new array<float>();
      int excludeMask = 0;
      foreach (int indx, auto crumb: m_TransitionalTrigger.m_Data.Breadcrumbs)
      {
        if (indx > 32)//error handling for exceeding this limit is handled elsewhere
          break;
        float dist = vector.Distance(m_Player.GetPosition(), crumb.GetPosition());
        float crumbRadius = m_TransitionalTrigger.m_Data.Breadcrumbs[indx].Radius;
        float maxRadiusAllowed = DISTANCE_CUTOFF;
        if (crumbRadius != -1)
          maxRadiusAllowed = crumbRadius;
        if (dist > maxRadiusAllowed)
          excludeMask = (excludeMask | (1 << indx));
        else if (m_TransitionalTrigger.m_Data.Breadcrumbs[indx].UseRaycast)
        {
          int idx = m_Player.GetBoneIndexByName("Head");
          vector rayStart = m_Player.GetBonePositionWS(idx);
          vector rayEnd = crumb.GetPosition();
          vector hitPos, hitNormal;
          float hitFraction;
          Object hitObj;
          if (DayZPhysics.RayCastBullet(rayStart, rayEnd, PhxInteractionLayers.TERRAIN | PhxInteractionLayers.ROADWAY | PhxInteractionLayers.BUILDING, null, hitObj, hitPos, hitNormal, hitFraction))
            excludeMask = (excludeMask | (1 << indx));
        }
        distances.Insert(dist);
#ifdef DIAG_DEVELOPER
        if (DiagMenu.GetBool(DiagMenuIDs.UNDERGROUND_SHOW_BREADCRUMB))
          Debug.DrawSphere(crumb.GetPosition(), 0.1, COLOR_RED, ShapeFlags.ONCE);
#endif
      }
      float baseDst = distances[0];
      float sum = 0;
      //Print(excludeMask);
      foreach (float dst: distances)
      {
        if (dst == 0)
          dst = 0.1;
        float dstInv = (baseDst / dst) * baseDst;
        sum += dstInv;
        distancesInverted.Insert(dstInv);
      }
      float sumCheck = 0;
      float eyeAcco = 0;
      foreach (int i, float dstInvert: distancesInverted)
      {
        /*
          //Print(m_TransitionalTrigger.m_Data.Breadcrumbs[i].EyeAccommodation);
          //Print(m_TransitionalTrigger.m_Data.Breadcrumbs.Count());
        */
        if ((1 << i) & excludeMask)
          continue;
        float ratio = dstInvert / sum;
        if (ratio > MAX_RATIO)
          ratio = MAX_RATIO;
        if (ratio > RATIO_CUTOFF)
        {
#ifdef DIAG_DEVELOPER
          if (DiagMenu.GetBool(DiagMenuIDs.UNDERGROUND_SHOW_BREADCRUMB))
          {
            float intensity = (1 - ratio) * 255;
            Debug.DrawLine(GetGame().GetPlayer().GetPosition() + "0 1 0", m_TransitionalTrigger.m_Data.Breadcrumbs[i].GetPosition(), ARGB(0, 255, intensity, intensity), ShapeFlags.ONCE);
          }
#endif
          eyeAcco += ratio * m_TransitionalTrigger.m_Data.Breadcrumbs[i].EyeAccommodation;
        }
      }
      m_EyeAccoTarget = eyeAcco * ACCO_MODIFIER;
    }
  }
References ACCO_MODIFIER, ARGB(), COLOR_RED, vector::Distance(), DISTANCE_CUTOFF, Debug::DrawLine(), Debug::DrawSphere(), DiagMenu::GetBool(), GetGame(), m_EyeAccoTarget, m_Player, m_TransitionalTrigger, MAX_RATIO, RATIO_CUTOFF, and DayZPhysics::RayCastBullet().
Referenced by ProcessEyeAcco().
EnableLights()
void EnableLights (bool enable) protected
Definition at line 317 of file UndergroundHandlerClient.c.
  {
    foreach (ScriptedLightBase light: ScriptedLightBase.m_NightTimeOnlyLights)
      light.SetVisibleDuringDaylight(enable);
  }
Referenced by OnUndergroundPresenceUpdate().
GetRequester()
PPERUndergroundAcco GetRequester () protected
Definition at line 54 of file UndergroundHandlerClient.c.
  {
    if (!m_Requester)
    {
      m_Requester = PPERUndergroundAcco.Cast(PPERequesterBank.GetRequester(PPERequesterBank.REQ_UNDERGROUND));
      m_Requester.Start();
    }
    return m_Requester;
  }
References m_Requester.
Referenced by ApplyEyeAcco(), ProcessEyeAcco(), and Managed::RegisterRequester().
OnTriggerEnter()
void OnTriggerEnter (UndergroundTrigger trigger) protected
Definition at line 64 of file UndergroundHandlerClient.c.
  {
    m_InsideTriggers.Insert(trigger);
    OnTriggerInsiderUpdate();
  }
References m_InsideTriggers, and OnTriggerInsiderUpdate().
OnTriggerInsiderUpdate()
void OnTriggerInsiderUpdate () protected
Definition at line 262 of file UndergroundHandlerClient.c.
  {
    EUndergroundTriggerType bestType = EUndergroundTriggerType.UNDEFINED;
    m_TransitionalTrigger = null;
    UndergroundTrigger bestTrigger;
    m_EyeAccoTarget = 1;
    m_AccoInterpolationSpeed = DEFAULT_INTERPOLATION_SPEED;
    foreach (auto t: m_InsideTriggers)
    {
      if (t.m_Type > bestType)
      {
        bestTrigger = t;
        bestType = t.m_Type;
      }
    }
    //Print(m_InsideTriggers.Count());
    //Print(bestType);
    if (bestTrigger)
    {
      if (bestTrigger.m_Type == EUndergroundTriggerType.TRANSITIONING)
        m_TransitionalTrigger = bestTrigger;
      m_EyeAccoTarget = bestTrigger.m_Accommodation;
      if (bestTrigger.m_InterpolationSpeed != -1 && bestTrigger.m_InterpolationSpeed != 0)
        m_AccoInterpolationSpeed = bestTrigger.m_InterpolationSpeed;
    }
    SetUndergroundPresence(bestTrigger);
  }
References DEFAULT_INTERPOLATION_SPEED, m_AccoInterpolationSpeed, m_EyeAccoTarget, m_InsideTriggers, m_TransitionalTrigger, and SetUndergroundPresence().
Referenced by OnTriggerEnter(), and OnTriggerLeave().
OnTriggerLeave()
void OnTriggerLeave (UndergroundTrigger trigger) protected
Definition at line 71 of file UndergroundHandlerClient.c.
  {
    int index = m_InsideTriggers.Find(trigger);
    if (index != -1)
      m_InsideTriggers.Remove(index);
    OnTriggerInsiderUpdate();
  }
References m_InsideTriggers, and OnTriggerInsiderUpdate().
OnUndergroundPresenceUpdate()
void OnUndergroundPresenceUpdate (EUndergroundPresence newPresence, EUndergroundPresence oldPresence) protected
Definition at line 345 of file UndergroundHandlerClient.c.
  {
    //Print("-----> On Undeground Presence update " + EnumTools.EnumToString(EUndergroundPresence, newPresence) + " " + EnumTools.EnumToString(EUndergroundPresence, oldPresence));
    if (newPresence > EUndergroundPresence.NONE)
    {
      if (oldPresence == EUndergroundPresence.NONE)
        EnableLights(true);
      if (newPresence > EUndergroundPresence.OUTER && oldPresence <= EUndergroundPresence.OUTER)
      {
        GetGame().GetWeather().SuppressLightningSimulation(true);
        m_Player.PlaySoundSetLoop(m_AmbientSound, "Underground_SoundSet", 3, 3);
      }
      if (newPresence == EUndergroundPresence.FULL)
      {
        m_AnimTimerLightBlend = new AnimationTimer();
        m_AnimTimerLightBlend.Run(1, this, "OnUpdateTimerIn", "OnUpdateTimerEnd", 0, false, LIGHT_BLEND_SPEED_IN);
      }
    }
    if (newPresence < EUndergroundPresence.FULL && oldPresence == EUndergroundPresence.FULL)
    {
      m_AnimTimerLightBlend = new AnimationTimer();
      m_AnimTimerLightBlend.Run(0, this, "OnUpdateTimerOut", "OnUpdateTimerEnd", m_LightingLerp, false, LIGHT_BLEND_SPEED_OUT);
    }
    if (newPresence <= EUndergroundPresence.OUTER && oldPresence > EUndergroundPresence.OUTER)
    {
      GetGame().GetWeather().SuppressLightningSimulation(false);
      if (m_AmbientSound)
        m_Player.StopSoundSet(m_AmbientSound);
    }
    if (newPresence == EUndergroundPresence.NONE && oldPresence >= EUndergroundPresence.OUTER)
    {
      GetGame().GetWorld().SetUserLightingLerp(0);
      EnableLights(false);
    }
  }
References EnableLights(), GetGame(), LIGHT_BLEND_SPEED_IN, LIGHT_BLEND_SPEED_OUT, m_AmbientSound, m_AnimTimerLightBlend, m_LightingLerp, and m_Player.
Referenced by SetUndergroundPresence().
OnUpdateTimerEnd()
void OnUpdateTimerEnd () protected
OnUpdateTimerIn()
void OnUpdateTimerIn () protected
Definition at line 325 of file UndergroundHandlerClient.c.
  {
    if (!m_AnimTimerLightBlend)
      return;
    float value01 = m_AnimTimerLightBlend.GetValue();
    float result = Easing.EaseInQuint(value01);
    m_LightingLerp = result;
  }
References Easing::EaseInQuint(), m_AnimTimerLightBlend, and m_LightingLerp.
OnUpdateTimerOut()
void OnUpdateTimerOut () protected
Definition at line 335 of file UndergroundHandlerClient.c.
  {
    if (!m_AnimTimerLightBlend)
      return;
    float value01 = m_AnimTimerLightBlend.GetValue();
    float result = Easing.EaseOutCubic(value01);
    m_LightingLerp = result;
  }
References Easing::EaseOutCubic(), m_AnimTimerLightBlend, and m_LightingLerp.
ProcessEyeAcco()
void ProcessEyeAcco (float timeSlice) protected
Definition at line 165 of file UndergroundHandlerClient.c.
  {
    CalculateEyeAccoTarget();
    bool reachedTarget = CalculateEyeAcco(timeSlice);
    ApplyEyeAcco();
    if (reachedTarget && !m_Player.m_UndergroundPresence)
    {
      GetRequester().Stop();
      UpdateNVGRequester(1);
      //m_NVRequester.SetUndergroundExposureCoef(1.0);
      m_Player.KillUndergroundHandler();
    }
  }
References ApplyEyeAcco(), CalculateEyeAcco(), CalculateEyeAccoTarget(), GetRequester(), m_Player, and UpdateNVGRequester().
Referenced by Tick().
ProcessLighting()
void ProcessLighting (float timeSlice) protected
Definition at line 180 of file UndergroundHandlerClient.c.
  {
#ifdef DEVELOPER
    if (!DiagMenu.GetBool(DiagMenuIDs.UNDERGROUND_DISABLE_DARKENING))
      GetGame().GetWorld().SetUserLightingLerp(m_LightingLerp);
    else
      GetGame().GetWorld().SetUserLightingLerp(0);
#else
    GetGame().GetWorld().SetUserLightingLerp(m_LightingLerp);
#endif
  }
References DiagMenu::GetBool(), GetGame(), and m_LightingLerp.
Referenced by Tick().
ProcessSound()
void ProcessSound (float timeSlice) protected
Definition at line 192 of file UndergroundHandlerClient.c.
  {
    GetGame().GetWorld().SetExplicitVolumeFactor_EnvSounds2D(m_EyeAcco, 0);
    if (m_AmbientSound)
    {
      m_AmbientSound.SetSoundVolume(1 - m_EyeAcco);
      //Print(m_AmbientSound.GetSoundVolume());
    }
    else
      m_Player.PlaySoundSetLoop(m_AmbientSound, "Underground_SoundSet", 3, 3);
  }
References GetGame(), m_AmbientSound, m_EyeAcco, m_Player, and EffectSound::SetSoundVolume().
SetUndergroundPresence()
void SetUndergroundPresence (UndergroundTrigger trigger) protected
Definition at line 293 of file UndergroundHandlerClient.c.
  {
    EUndergroundPresence newPresence = EUndergroundPresence.NONE;
    EUndergroundPresence oldPresence = m_Player.m_UndergroundPresence;
    if (trigger)
    {
      if (trigger.m_Type == EUndergroundTriggerType.OUTER)
        newPresence = EUndergroundPresence.OUTER;
      else if (trigger.m_Type == EUndergroundTriggerType.TRANSITIONING)
        newPresence = EUndergroundPresence.TRANSITIONING;
      else if (trigger.m_Type == EUndergroundTriggerType.INNER)
        newPresence = EUndergroundPresence.FULL;
    }
    if (newPresence != oldPresence)//was there a change ?
    {
      OnUndergroundPresenceUpdate(newPresence, oldPresence);
      m_Player.SetUnderground(newPresence);
    }
  }
References m_Player, and OnUndergroundPresenceUpdate().
Referenced by OnTriggerInsiderUpdate().
Tick()
void Tick (float timeSlice) protected
Definition at line 204 of file UndergroundHandlerClient.c.
  {
    if (!m_Player.IsAlive())
      return;
    ProcessEyeAcco(timeSlice);
    ProcessLighting(timeSlice);
    ProcessSound(timeSlice);
#ifdef DIAG_DEVELOPER
    if (DiagMenu.GetBool(DiagMenuIDs.UNDERGROUND_SHOW_BREADCRUMB))
      DisplayDebugInfo(GetGame().GetWorld().GetEyeAccom(), m_LightingLerp);
#endif
  }
References DiagMenu::GetBool(), GetGame(), m_LightingLerp, m_Player, ProcessEyeAcco(), ProcessLighting(), and ProcessSound().
UndergroundHandlerClient()
void UndergroundHandlerClient (PlayerBase player) protected
Definition at line 35 of file UndergroundHandlerClient.c.
  {
    GetGame().GetWorld().LoadUserLightingCfg(UNDERGROUND_LIGHTING, "Underground");
    m_Player = player;
    m_NVRequester = PPERequester_CameraNV.Cast(PPERequesterBank.GetRequester(PPERequesterBank.REQ_CAMERANV));
  }
References GetGame(), m_NVRequester, m_Player, and UNDERGROUND_LIGHTING.
Referenced by ManBase::GetUndergroundHandler(), OnEnterClientEvent(), and OnLeaveClientEvent().
UpdateNVGRequester()
void UpdateNVGRequester (float value) protected
Definition at line 238 of file UndergroundHandlerClient.c.
  {
    m_NVRequester.SetUndergroundExposureCoef(value);
  }
References m_NVRequester.
Referenced by ApplyEyeAcco(), and ProcessEyeAcco().
~UndergroundHandlerClient()
void ~UndergroundHandlerClient () protected
Definition at line 42 of file UndergroundHandlerClient.c.
  {
    if (GetGame())
    {
      GetGame().GetWorld().SetExplicitVolumeFactor_EnvSounds2D(1, 0.5);
      GetGame().GetWeather().SuppressLightningSimulation(false);
      GetGame().GetWorld().SetUserLightingLerp(0);
      if (m_AmbientSound)
        m_AmbientSound.Stop();
    }
  }
References GetGame(), m_AmbientSound, and EffectSound::Stop().
Variable Documentation
ACCO_MODIFIER
const float ACCO_MODIFIER = 1
Definition at line 16 of file UndergroundHandlerClient.c.
Referenced by CalculateEyeAccoTarget().
DEFAULT_INTERPOLATION_SPEED
const float DEFAULT_INTERPOLATION_SPEED = 7
Definition at line 17 of file UndergroundHandlerClient.c.
Referenced by OnTriggerInsiderUpdate().
DISTANCE_CUTOFF
const float DISTANCE_CUTOFF = 5
Definition at line 15 of file UndergroundHandlerClient.c.
Referenced by CalculateEyeAccoTarget().
LIGHT_BLEND_SPEED_IN
enum EUndergroundPresence LIGHT_BLEND_SPEED_IN = 5
Referenced by OnUndergroundPresenceUpdate().
LIGHT_BLEND_SPEED_OUT
const float LIGHT_BLEND_SPEED_OUT = 1.75
Definition at line 12 of file UndergroundHandlerClient.c.
Referenced by OnUndergroundPresenceUpdate().
m_AccoInterpolationSpeed
float m_AccoInterpolationSpeed protected
Definition at line 27 of file UndergroundHandlerClient.c.
Referenced by CalculateEyeAcco(), and OnTriggerInsiderUpdate().
m_AmbientSound
EffectSound m_AmbientSound protected
Definition at line 31 of file UndergroundHandlerClient.c.
Referenced by OnUndergroundPresenceUpdate(), ProcessSound(), and ~UndergroundHandlerClient().
m_AnimTimerLightBlend
ref AnimationTimer m_AnimTimerLightBlend protected
Definition at line 19 of file UndergroundHandlerClient.c.
Referenced by OnUndergroundPresenceUpdate(), OnUpdateTimerIn(), and OnUpdateTimerOut().
m_EyeAcco
float m_EyeAcco = 1 protected
Definition at line 28 of file UndergroundHandlerClient.c.
Referenced by ApplyEyeAcco(), CalculateEyeAcco(), and ProcessSound().
m_EyeAccoTarget
float m_EyeAccoTarget = 1 protected
Definition at line 26 of file UndergroundHandlerClient.c.
Referenced by CalculateEyeAcco(), CalculateEyeAccoTarget(), and OnTriggerInsiderUpdate().
m_InsideTriggers
ref set<UndergroundTrigger> m_InsideTriggers = new set<UndergroundTrigger>() protected
Definition at line 24 of file UndergroundHandlerClient.c.
Referenced by OnTriggerEnter(), OnTriggerInsiderUpdate(), and OnTriggerLeave().
m_LightingLerp
float m_LightingLerp protected
Definition at line 30 of file UndergroundHandlerClient.c.
Referenced by ApplyEyeAcco(), OnUndergroundPresenceUpdate(), OnUpdateTimerIn(), OnUpdateTimerOut(), ProcessLighting(), and Tick().
m_LightingLerpTarget
float m_LightingLerpTarget protected
Definition at line 29 of file UndergroundHandlerClient.c.
m_NVRequester
PPERequester_CameraNV m_NVRequester protected
Definition at line 23 of file UndergroundHandlerClient.c.
Referenced by UndergroundHandlerClient(), and UpdateNVGRequester().
m_Player
PlayerBase m_Player protected
Definition at line 21 of file UndergroundHandlerClient.c.
m_Requester
PPERUndergroundAcco m_Requester protected
Definition at line 22 of file UndergroundHandlerClient.c.
Referenced by GetRequester(), SymptomBase::OnGetDeactivatedClient(), SymptomBase::OnInit(), and SymptomBase::OnUpdateClient().
m_TransitionalTrigger
UndergroundTrigger m_TransitionalTrigger protected
Definition at line 33 of file UndergroundHandlerClient.c.
Referenced by CalculateEyeAcco(), CalculateEyeAccoTarget(), and OnTriggerInsiderUpdate().
MAX_RATIO
const float MAX_RATIO = 0.9
Definition at line 13 of file UndergroundHandlerClient.c.
Referenced by CalculateEyeAccoTarget().
RATIO_CUTOFF
const float RATIO_CUTOFF = 0
Definition at line 14 of file UndergroundHandlerClient.c.
Referenced by CalculateEyeAccoTarget().
UNDERGROUND_LIGHTING
const string UNDERGROUND_LIGHTING = "dz\\data\\lighting\\lighting_underground.txt"
Definition at line 18 of file UndergroundHandlerClient.c.
Referenced by UndergroundHandlerClient().