DayZ: SpookyEventBase Class Reference
SpookyEventBase Class Reference
Protected Member Functions
void SpookyEventBase ()
void Init ()
vector GetMatchingSurfacePos (TStringArray surfaces, TStringVectorMap gatheredSurfaces)
void SetCoolDown (float secs)
bool HasSurfaces ()
bool CanDo (PlayerBase player, TStringVectorMap surfaceTypes)
void Do (PlayerBase player)
bool CanPerform (PlayerBase player, float currentTime, TStringVectorMap surfaceTypes)
void Perform (PlayerBase player, float currentTime, TStringVectorMap gatheredSurfaces)
vector GetSoundPos (PlayerBase player)
Protected Attributes
float m_PerformedTimestamp
int m_Cooldown
string m_SoundSet
ref TStringArray m_Surfaces
vector m_MatchingSurfacePos
Detailed Description
Definition at line 84 of file SpookyAreaMisc.c.
Constructor & Destructor Documentation
SpookyEventBase()
void SpookyEventBase::SpookyEventBase () inline protected
Definition at line 94 of file SpookyAreaMisc.c.
  {
    Init();
  }
References Init().
Member Function Documentation
CanDo()
bool SpookyEventBase::CanDo (PlayerBase player, TStringVectorMap surfaceTypes) inline protected
Definition at line 127 of file SpookyAreaMisc.c.
  {
    return true;
  }
Referenced by CanPerform().
CanPerform()
bool SpookyEventBase::CanPerform (PlayerBase player, float currentTime, TStringVectorMap surfaceTypes) inline protected
Definition at line 135 of file SpookyAreaMisc.c.
  {
    bool surfaceCheckResult = 1;
    if (HasSurfaces())
    {
      m_MatchingSurfacePos = GetMatchingSurfacePos(m_Surfaces, surfaceTypes);
      surfaceCheckResult = m_MatchingSurfacePos != vector.Zero;
    }
    return (currentTime > (m_PerformedTimestamp + m_Cooldown) && surfaceCheckResult && CanDo(player, surfaceTypes));
  }
References CanDo(), GetMatchingSurfacePos(), HasSurfaces(), m_Cooldown, m_MatchingSurfacePos, m_PerformedTimestamp, m_Surfaces, and vector::Zero.
Do()
void SpookyEventBase::Do (PlayerBase player) protected
Referenced by Perform().
GetMatchingSurfacePos()
vector SpookyEventBase::GetMatchingSurfacePos (TStringArray surfaces, TStringVectorMap gatheredSurfaces) inline protected
Definition at line 102 of file SpookyAreaMisc.c.
  {
    for (int i = 0; i < gatheredSurfaces.Count(); i++)
    {
      string currSurface = gatheredSurfaces.GetKey(i);
      foreach (string s: surfaces)
      {
        if (currSurface.Contains(s))
          return gatheredSurfaces.Get(currSurface);
      }
    }
    return vector.Zero;
  }
References vector::Zero.
Referenced by CanPerform().
GetSoundPos()
vector SpookyEventBase::GetSoundPos (PlayerBase player) inline protected
Definition at line 173 of file SpookyAreaMisc.c.
  {
    vector soundPos;
    if (HasSurfaces())
      soundPos = m_MatchingSurfacePos;
    else
    {
      float distance = Math.RandomFloatInclusive(5, 15);
      vector randomDir = vector.RandomDir2D() * distance;
      vector playerPos = player.GetPosition();
      soundPos = playerPos + randomDir;
    }
    return soundPos;
  }
References HasSurfaces(), m_MatchingSurfacePos, vector::RandomDir2D(), and Math::RandomFloatInclusive().
Referenced by Perform().
HasSurfaces()
bool SpookyEventBase::HasSurfaces () inline protected
Definition at line 122 of file SpookyAreaMisc.c.
  {
    return (m_Surfaces && m_Surfaces.Count() > 0);
  }
References m_Surfaces.
Referenced by CanPerform(), and GetSoundPos().
Init()
void SpookyEventBase::Init () protected
Referenced by SpookyEventBase().
Perform()
void SpookyEventBase::Perform (PlayerBase player, float currentTime, TStringVectorMap gatheredSurfaces) inline protected
Definition at line 150 of file SpookyAreaMisc.c.
  {
#ifdef DIAG_DEVELOPER
    if (DiagMenu.GetBool(DiagMenuIDs.TRIGGER_DEBUG))
      Print("Performing " + this);
#endif
    m_PerformedTimestamp = currentTime;
    if (m_SoundSet)
    {
      vector soundPos = GetSoundPos(player);
      EffectSound sound = SEffectManager.PlaySound(m_SoundSet, soundPos);
      sound.SetAutodestroy(true);
#ifdef DIAG_DEVELOPER
      if (DiagMenu.GetBool(DiagMenuIDs.TRIGGER_DEBUG))
        Debug.DrawSphere(soundPos, 0.15, Colors.YELLOW, ShapeFlags.NOZBUFFER);
#endif
    }
    Do(player);
  }
References Do(), Debug::DrawSphere(), DiagMenu::GetBool(), GetSoundPos(), m_PerformedTimestamp, m_SoundSet, SEffectManager::PlaySound(), Print(), and Colors::YELLOW.
SetCoolDown()
void SpookyEventBase::SetCoolDown (float secs) inline protected
Definition at line 117 of file SpookyAreaMisc.c.
  {
    m_Cooldown = secs * 1000;
  }
References m_Cooldown.
Referenced by SpookyEventWind::Init(), and SpookyEventSteps::Init().
Member Data Documentation
m_Cooldown
int SpookyEventBase::m_Cooldown protected
Definition at line 88 of file SpookyAreaMisc.c.
Referenced by CanPerform(), and SetCoolDown().
m_MatchingSurfacePos
vector SpookyEventBase::m_MatchingSurfacePos protected
Definition at line 92 of file SpookyAreaMisc.c.
Referenced by CanPerform(), and GetSoundPos().
m_PerformedTimestamp
float SpookyEventBase::m_PerformedTimestamp protected
Definition at line 87 of file SpookyAreaMisc.c.
Referenced by CanPerform(), and Perform().
m_SoundSet
string SpookyEventBase::m_SoundSet protected
Definition at line 90 of file SpookyAreaMisc.c.
Referenced by SpookyEventWind::Init(), SpookyEventSteps::Init(), and Perform().
m_Surfaces
ref TStringArray SpookyEventBase::m_Surfaces protected
Definition at line 91 of file SpookyAreaMisc.c.
Referenced by CanPerform(), HasSurfaces(), and SpookyEventSteps::Init().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/ContaminatedArea/SpookyAreaMisc.c