DayZ: StarlightOptic Class Reference
StarlightOptic Class Reference
Private Member Functions
override void InitOpticMode ()
override int GetCurrentNVType ()
override void OnOpticModeChange ()
override void OnOpticEnter ()
override void UpdateSelectionVisibility ()
override void SetActions ()
Private Member Functions inherited from ItemOptics
void SetPlayer (PlayerBase player)
PlayerBase GetPlayer ()
Additional Inherited Members
Private Attributes inherited from ItemOptics
PlayerBase m_Player
Detailed Description
Definition at line 83 of file Optics.c.
Member Function Documentation
GetCurrentNVType()
override int StarlightOptic::GetCurrentNVType () inline private
Definition at line 92 of file Optics.c.
  {
    if (IsWorking())
    {
      switch (m_CurrentOpticMode)
      {
      case GameConstants.OPTICS_STATE_DAY:
        return NVTypes.NV_OPTICS_STARLIGHT_DAY;
      case GameConstants.OPTICS_STATE_NIGHTVISION:
        return NVTypes.NV_OPTICS_STARLIGHT_NIGHT;
      }
      Error("Undefined optic mode of " + this);
      return NVTypes.NONE;
    }
    else
      return NVTypes.NV_OPTICS_OFF;
  }
References Error(), ItemOptics::IsWorking(), ItemOptics::m_CurrentOpticMode, GameConstants::OPTICS_STATE_DAY, and GameConstants::OPTICS_STATE_NIGHTVISION.
InitOpticMode()
override void StarlightOptic::InitOpticMode () inline private
Definition at line 85 of file Optics.c.
  {
    super.InitOpticMode();
    SetCurrentOpticMode(GameConstants.OPTICS_STATE_NIGHTVISION);
  }
References GameConstants::OPTICS_STATE_NIGHTVISION, and ItemOptics::SetCurrentOpticMode().
OnOpticEnter()
override void StarlightOptic::OnOpticEnter () inline private
Definition at line 118 of file Optics.c.
  {
    super.OnOpticEnter();
    HideSelection("hide_cover_pilot");
  }
References ItemOptics::HideSelection().
OnOpticModeChange()
override void StarlightOptic::OnOpticModeChange () inline private
Definition at line 111 of file Optics.c.
  {
    super.OnOpticModeChange();
    UpdateSelectionVisibility();
  }
References UpdateSelectionVisibility().
SetActions()
override void StarlightOptic::SetActions () inline private
Definition at line 144 of file Optics.c.
  {
    super.SetActions();
    AddAction(ActionToggleNVMode);
  }
References AddAction().
UpdateSelectionVisibility()
override void StarlightOptic::UpdateSelectionVisibility () inline private
Definition at line 125 of file Optics.c.
  {
    super.UpdateSelectionVisibility();
    switch (GetCurrentOpticMode())
    {
    case GameConstants.OPTICS_STATE_NIGHTVISION:
      HideSelection("hide_cover");
      HideSelection("hide_cover_pilot");
      break;
    case GameConstants.OPTICS_STATE_DAY:
      ShowSelection("hide_cover");
      if (!GetGame().IsDedicatedServer() && !IsInOptics()) //quick sanity check, just in case
        ShowSelection("hide_cover_pilot");
      break;
    }
  }
References ItemOptics::GetCurrentOpticMode(), GetGame(), ItemOptics::HideSelection(), ItemOptics::IsInOptics(), GameConstants::OPTICS_STATE_DAY, GameConstants::OPTICS_STATE_NIGHTVISION, and ItemOptics::ShowSelection().
Referenced by OnOpticModeChange().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Inventory_Base/Optics.c