DayZ: ActionTestBloodTarget Class Reference
ActionTestBloodTarget Class Reference
Private Member Functions
void ActionTestBloodTarget ()
override void CreateConditionComponents ()
override void OnFinishProgressClient (ActionData action_data)
override void OnStartServer (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 9 of file ActionTestBloodTarget.c.
Constructor & Destructor Documentation
ActionTestBloodTarget()
void ActionTestBloodTarget::ActionTestBloodTarget () inline private
Definition at line 11 of file ActionTestBloodTarget.c.
  {
    m_CallbackClass = ActionTestBloodTargetCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_BANDAGETARGET;
    m_FullBody = true;
    m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
    m_Text = "#test_targets_blood";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
CreateConditionComponents()
override void ActionTestBloodTarget::CreateConditionComponents () inline private
Definition at line 20 of file ActionTestBloodTarget.c.
  {
    m_ConditionItem = new CCINonRuined;
    m_ConditionTarget = new CCTMan(UAMaxDistances.DEFAULT);
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnFinishProgressClient()
override void ActionTestBloodTarget::OnFinishProgressClient (ActionData action_data) inline private
Definition at line 26 of file ActionTestBloodTarget.c.
  {
    PlayerBase ntarget = PlayerBase.Cast(action_data.m_Target.GetObject());
    if (ntarget)
    {
      string blood_type_name, blood_name;
      bool positive;
      blood_type_name = BloodTypes.GetBloodTypeName(ntarget.GetBloodType(), blood_name, positive);
      ntarget.SetLastUAMessage(blood_type_name);
    }
  }
References BloodTypes::GetBloodTypeName().
OnFinishProgressServer()
override void ActionTestBloodTarget::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 49 of file ActionTestBloodTarget.c.
  {
    PlayerBase ntarget = PlayerBase.Cast(action_data.m_Target.GetObject());
    PluginLifespan module_lifespan = PluginLifespan.Cast(GetPlugin(PluginLifespan));
    module_lifespan.UpdateBloodTypeVisibility(ntarget, true);
    action_data.m_MainItem.Delete();
    action_data.m_Player.GetSoftSkillsManager().AddSpecialty(m_SpecialtyWeight);
  }
References GetPlugin(), m_SpecialtyWeight, and PluginLifespan().
OnStartServer()
override void ActionTestBloodTarget::OnStartServer (ActionData action_data) inline private
Definition at line 40 of file ActionTestBloodTarget.c.
  {
    PlayerBase ntarget = PlayerBase.Cast(action_data.m_Target.GetObject());
    PluginLifespan module_lifespan = PluginLifespan.Cast(GetPlugin(PluginLifespan));
    int blood_type = ntarget.GetStatBloodType().Get();
    module_lifespan.UpdateBloodType(ntarget, blood_type);
  }
References GetPlugin(), and PluginLifespan().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/Medical/ActionTestBloodTarget.c