DayZ: DeveloperTeleport Class Reference
DeveloperTeleport Class Reference
Static Protected Member Functions
static void TeleportAtCursor ()
static void TeleportAtCursorEx ()
static void SetPlayerPosition (PlayerBase player, vector position, bool breakSync=false)
static void SetPlayerDirection (PlayerBase player, vector direction)
static void OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx)
void OnRPCSetPlayerPosition (PlayerBase player, ParamsReadContext ctx)
void OnRPCSetPlayerDirection (PlayerBase player, ParamsReadContext ctx)
Static Protected Attributes
static const float TELEPORT_DISTANCE_MAX = 1000
static const float TELEPORT_DISTANCE_MAX_EX = 500
Detailed Description
Definition at line 1 of file DeveloperTeleport.c.
Member Function Documentation
OnRPC()
static void DeveloperTeleport::OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx) inline static protected
Definition at line 134 of file DeveloperTeleport.c.
  {
#ifdef DIAG_DEVELOPER
    if (rpc_type == ERPCs.DEV_RPC_TELEPORT)
      OnRPCSetPlayerPosition(player, ctx);
    else if (rpc_type == ERPCs.DEV_RPC_SET_PLAYER_DIRECTION)
      OnRPCSetPlayerDirection(player, ctx);
#endif
  }
References OnRPCSetPlayerDirection(), and OnRPCSetPlayerPosition().
Referenced by PluginBase::OnRPC().
OnRPCSetPlayerDirection()
void DeveloperTeleport::OnRPCSetPlayerDirection (PlayerBase player, ParamsReadContext ctx) inline static protected
Definition at line 157 of file DeveloperTeleport.c.
  {
    Param3<float, float, float> p = new Param3<float, float, float>(0, 0, 0);
    if (ctx.Read(p))
    {
      vector v = "0 0 0";
      v[0] = p.param1;
      v[1] = p.param2;
      v[2] = p.param3;
      SetPlayerDirection(player, v);
    }
  }
References SetPlayerDirection().
Referenced by OnRPC().
OnRPCSetPlayerPosition()
void DeveloperTeleport::OnRPCSetPlayerPosition (PlayerBase player, ParamsReadContext ctx) inline static protected
Definition at line 144 of file DeveloperTeleport.c.
  {
    Param4<float, float, float, bool> p = new Param4<float, float, float, bool>(0, 0, 0, false);
    if (ctx.Read(p))
    {
      vector v = "0 0 0";
      v[0] = p.param1;
      v[1] = p.param2;
      v[2] = p.param3;
      SetPlayerPosition(player, v, p.param4);
    }
  }
References SetPlayerPosition().
Referenced by OnRPC().
SetPlayerDirection()
static void DeveloperTeleport::SetPlayerDirection (PlayerBase player, vector direction) inline static protected
Definition at line 113 of file DeveloperTeleport.c.
  {
    if (GetGame().IsServer())
    {
      HumanCommandVehicle vehCmd = player.GetCommand_Vehicle();
      if (vehCmd)
      {
        Transport transport = vehCmd.GetTransport();
        if (transport)
          transport.SetDirection(direction);
      }
      else
        player.SetDirection(direction);
    }
    else
    {
      Param3<float, float, float> params = new Param3<float, float, float>(direction[0], direction[1], direction[2]);
      player.RPCSingleParam(ERPCs.DEV_RPC_SET_PLAYER_DIRECTION, params, true);
    }
  }
References GetGame().
Referenced by OnRPCSetPlayerDirection(), and TeleportAtCursorEx().
SetPlayerPosition()
static void DeveloperTeleport::SetPlayerPosition (PlayerBase player, vector position, bool breakSync = false) inline static protected
Definition at line 78 of file DeveloperTeleport.c.
  {
    Object object = player;
    HumanCommandVehicle vehCmd = player.GetCommand_Vehicle();
    if (vehCmd)
      object = vehCmd.GetTransport();
#ifdef DIAG_DEVELOPER
    if (GetGame().IsMultiplayer() && breakSync)
    {
      vector v;
      v[0] = Math.RandomFloat(-Math.PI, Math.PI);
      v[1] = Math.RandomFloat(-Math.PI, Math.PI);
      v[2] = Math.RandomFloat(-Math.PI, Math.PI);
      dBodySetAngularVelocity(object, v);
      SetVelocity(object, vector.Zero);
      v[0] = Math.RandomFloat(-Math.PI, Math.PI);
      v[1] = Math.RandomFloat(-Math.PI, Math.PI);
      v[2] = Math.RandomFloat(-Math.PI, Math.PI);
      object.SetOrientation(v * Math.RAD2DEG);
    }
#endif
    if (GetGame().IsServer())
      object.SetPosition(position);
    else
    {
      Param4<float, float, float, bool> params = new Param4<float, float, float, bool>(position[0], position[1], position[2], breakSync);
      player.RPCSingleParam(ERPCs.DEV_RPC_TELEPORT, params, true);
    }
  }
References dBodySetAngularVelocity(), GetGame(), Math::PI, Math::RAD2DEG, Math::RandomFloat(), SetVelocity(), and vector::Zero.
Referenced by OnRPCSetPlayerPosition(), PluginBase::Teleport(), TeleportAtCursor(), and TeleportAtCursorEx().
TeleportAtCursor()
static void DeveloperTeleport::TeleportAtCursor () inline static protected
Definition at line 5 of file DeveloperTeleport.c.
  {
    if (!DeveloperFreeCamera.IsFreeCameraEnabled())
    {
      PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
      vector pos_player = player.GetPosition();
      Object ignore;
      if (!Class.CastTo(ignore, player.GetParent()))
        ignore = player;
      vector rayStart = GetGame().GetCurrentCameraPosition();
      vector rayEnd = rayStart + GetGame().GetCurrentCameraDirection() * 1000;
      vector hitPos;
      vector hitNormal;
      int hitComponentIndex;
      DayZPhysics.RaycastRV(rayStart, rayEnd, hitPos, hitNormal, hitComponentIndex, NULL, NULL, ignore);
      float distance = vector.Distance(pos_player, hitPos);
      if (distance < TELEPORT_DISTANCE_MAX)
      {
        bool breakSync = false;
#ifdef DIAG_DEVELOPER
        breakSync = DiagMenu.GetBool(DiagMenuIDs.MISC_TELEPORT_BREAKS_SYNC);
#endif
        SetPlayerPosition(player, hitPos, breakSync);
      }
      else
        Debug.LogWarning("Distance for teleportation is too far!");
    }
  }
References Class::CastTo(), vector::Distance(), DiagMenu::GetBool(), GetGame(), GetPlayer(), DeveloperFreeCamera::IsFreeCameraEnabled(), Debug::LogWarning(), DayZPhysics::RaycastRV(), SetPlayerPosition(), and TELEPORT_DISTANCE_MAX.
TeleportAtCursorEx()
static void DeveloperTeleport::TeleportAtCursorEx () inline static protected
Definition at line 41 of file DeveloperTeleport.c.
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    vector rayStart = GetGame().GetCurrentCameraPosition();
    vector rayEnd = rayStart + GetGame().GetCurrentCameraDirection() * TELEPORT_DISTANCE_MAX_EX;
    vector hitPos;
    vector hitNormal;
    float hitFraction;
    Object hitObj;
    Object ignore;
    if (!Class.CastTo(ignore, player.GetParent()))
      ignore = player;
    int layers = 0;
    layers |= PhxInteractionLayers.TERRAIN;
    layers |= PhxInteractionLayers.ROADWAY;
    layers |= PhxInteractionLayers.ITEM_LARGE;
    layers |= PhxInteractionLayers.BUILDING;
    layers |= PhxInteractionLayers.VEHICLE;
    layers |= PhxInteractionLayers.RAGDOLL;
    if (DayZPhysics.SphereCastBullet(rayStart, rayEnd, 0.01, layers, ignore, hitObj, hitPos, hitNormal, hitFraction))
    {
      bool breakSync = false;
#ifdef DIAG_DEVELOPER
      breakSync = DiagMenu.GetBool(DiagMenuIDs.MISC_TELEPORT_BREAKS_SYNC);
#endif
      SetPlayerPosition(player, hitPos, breakSync);
      if (DeveloperFreeCamera.IsFreeCameraEnabled())
        DeveloperTeleport.SetPlayerDirection(player, FreeDebugCamera.GetInstance().GetDirection());
    }
  }
References Class::CastTo(), DiagMenu::GetBool(), GetGame(), GetPlayer(), DeveloperFreeCamera::IsFreeCameraEnabled(), SetPlayerDirection(), SetPlayerPosition(), DayZPhysics::SphereCastBullet(), and TELEPORT_DISTANCE_MAX_EX.
Referenced by DeveloperFreeCamera::DisableFreeCamera(), and PluginBase::TeleportAtCursor().
Member Data Documentation
TELEPORT_DISTANCE_MAX
const float DeveloperTeleport::TELEPORT_DISTANCE_MAX = 1000 static protected
Definition at line 3 of file DeveloperTeleport.c.
Referenced by TeleportAtCursor().
TELEPORT_DISTANCE_MAX_EX
const float DeveloperTeleport::TELEPORT_DISTANCE_MAX_EX = 500 static protected
Definition at line 40 of file DeveloperTeleport.c.
Referenced by TeleportAtCursorEx().
The documentation for this class was generated from the following file:
scripts/4_World/Plugins/PluginBase/PluginDeveloper/DeveloperTeleport.c