DayZ: SoftSkillsManager Class Reference
SoftSkillsManager Class Reference
Protected Member Functions
void SoftSkillsManager (PlayerBase player)
void InitSpecialty (float specialty_level)
void ~SoftSkillsManager ()
float AddLinearPrecise (float specialty_weight)
float AddLinearRough (float specialty_weight)
float AddExponentialPrecise (float specialty_weight)
float AddExponentialRough (float specialty_weight)
void AddSpecialty (float specialty_weight)
float AddSpecialtyBonus (float base_value, float specialty_weight, bool is_cacomponent=false, float limit_efficiency=2)
float SubtractSpecialtyBonus (float base_value, float specialty_weight, bool is_cacomponent=false, float limit_efficiency=2)
float AdjustCraftingTime (float base_time, float specialty_weight, float limit_efficiency=2)
PlayerBase GetSoftSkillsPlayer ()
void SetSpecialtyLevel (float specialty_level)
float GetSpecialtyLevel ()
void SynchSpecialtyLevel ()
void SetSoftSkillsState (bool state)
bool GetSoftSkillsState ()
void SetLinearState (bool model)
bool IsLinear ()
void GetPreciseRoughLevels ()
void StartCoolDownTimer (float cooldown_value)
bool IsCoolDown ()
void SetCoolDown (bool cool_down)
void CreateDebugWindow (bool create)
void SynchDebugStats ()
void SetIsDebug (bool is_debug)
bool IsDebug ()
void SetCoolDownValue (float cooldown_value)
float GetCoolDownValue ()
float GetLastUAValue ()
void SetLastUAValue (float last_ua_value)
void SetBonusBefore (bool is_cacomponent, float base_value)
void SetBonusAfter (bool is_cacomponent, float adjusted_value)
float GetComponentBonusBefore ()
void SetComponentBonusBefore (float component_bonus_before)
float GetComponentBonusAfter ()
void SetComponentBonusAfter (float component_bonus_after)
float GetGeneralBonusBefore ()
void SetGeneralBonusBefore (float general_bonus_before)
float GetGeneralBonusAfter ()
void SetGeneralBonusAfter (float general_bonus_after)
void StartSynchTimer ()
void StopSynchTimer ()
void ResetDebugWindow ()
Protected Attributes
PlayerBase m_Player
float m_SpecialtyLevel
float m_RoughLevel
float m_PreciseLevel
bool m_IsLinear
bool m_IsActive
bool m_IsCoolDown
int m_UserActionsCounter
ref Timer m_CoolDownTimer = new Timer()
bool m_IsDebugMode
float m_CoolDownValue
float m_LastUAValue
float m_ComponentBonusBefore
float m_ComponentBonusAfter
float m_GeneralBonusBefore
float m_GeneralBonusAfter
ref SoftSkillManagerDebug m_DebugWindow
ref Timer m_SynchTimer
Static Protected Attributes
const int DEFAULT_EFFICIENCY = 0
const float PRECISE_WEIGHT_LIMIT = -1
const float ROUGH_WEIGHT_LIMIT = 1
const float COOLDOWN_TIMER = 5
Detailed Description
Definition at line 1 of file SoftSkillsManager.c.
Constructor & Destructor Documentation
SoftSkillsManager()
void SoftSkillsManager::SoftSkillsManager (PlayerBase player) inline protected
Definition at line 33 of file SoftSkillsManager.c.
  {
    m_Player = player;
    m_IsCoolDown = false;
    m_IsLinear = false;
    m_IsActive = true;
    m_IsDebugMode = false;
  }
References m_IsActive, m_IsCoolDown, m_IsDebugMode, m_IsLinear, and m_Player.
~SoftSkillsManager()
void SoftSkillsManager::~SoftSkillsManager () inline protected
Definition at line 48 of file SoftSkillsManager.c.
  {
    delete m_CoolDownTimer;
  }
References m_CoolDownTimer.
Member Function Documentation
AddExponentialPrecise()
float SoftSkillsManager::AddExponentialPrecise (float specialty_weight) inline protected
Definition at line 74 of file SoftSkillsManager.c.
  {
    m_UserActionsCounter -= 1;
    if (m_UserActionsCounter == 0)
    {
      m_UserActionsCounter = -1;
      m_SpecialtyLevel = 0;
    }
    float adjusted_weight = specialty_weight / Math.Sqrt(Math.AbsInt(m_UserActionsCounter));
    SetLastUAValue(adjusted_weight);
    m_SpecialtyLevel += adjusted_weight;
    m_SpecialtyLevel = Math.Clamp(m_SpecialtyLevel, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT);
    return m_SpecialtyLevel;
  }
References Math::AbsInt(), Math::Clamp(), m_SpecialtyLevel, m_UserActionsCounter, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT, SetLastUAValue(), and Math::Sqrt().
Referenced by AddSpecialty().
AddExponentialRough()
float SoftSkillsManager::AddExponentialRough (float specialty_weight) inline protected
Definition at line 95 of file SoftSkillsManager.c.
  {
    m_UserActionsCounter += 1;
    if (m_UserActionsCounter == 0)
    {
      m_UserActionsCounter = 1;
      m_SpecialtyLevel = 0;
    }
    float adjusted_weight = specialty_weight / Math.Sqrt(Math.AbsInt(m_UserActionsCounter));
    SetLastUAValue(adjusted_weight);
    m_SpecialtyLevel += adjusted_weight;
    m_SpecialtyLevel = Math.Clamp(m_SpecialtyLevel, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT);
    return m_SpecialtyLevel;
  }
References Math::AbsInt(), Math::Clamp(), m_SpecialtyLevel, m_UserActionsCounter, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT, SetLastUAValue(), and Math::Sqrt().
Referenced by AddSpecialty().
AddLinearPrecise()
float SoftSkillsManager::AddLinearPrecise (float specialty_weight) inline protected
Definition at line 54 of file SoftSkillsManager.c.
  {
    m_SpecialtyLevel += specialty_weight;
    SetLastUAValue(specialty_weight);
    m_SpecialtyLevel = Math.Clamp(m_SpecialtyLevel, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT);
    return m_SpecialtyLevel;
  }
References Math::Clamp(), m_SpecialtyLevel, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT, and SetLastUAValue().
Referenced by AddSpecialty().
AddLinearRough()
float SoftSkillsManager::AddLinearRough (float specialty_weight) inline protected
Definition at line 64 of file SoftSkillsManager.c.
  {
    m_SpecialtyLevel += specialty_weight;
    SetLastUAValue(specialty_weight);
    m_SpecialtyLevel = Math.Clamp(m_SpecialtyLevel, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT);
    return m_SpecialtyLevel;
  }
References Math::Clamp(), m_SpecialtyLevel, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT, and SetLastUAValue().
Referenced by AddSpecialty().
AddSpecialty()
void SoftSkillsManager::AddSpecialty (float specialty_weight) inline protected
Definition at line 116 of file SoftSkillsManager.c.
  {
    if (GetSoftSkillsState())
    {
      if (!IsCoolDown())
      {
        if (specialty_weight < 0)
        {
          if (IsLinear())
            SetSpecialtyLevel(AddLinearPrecise(specialty_weight));
          else
            SetSpecialtyLevel(AddExponentialPrecise(specialty_weight));
          m_Player.GetStatSpecialty().Set(m_SpecialtyLevel);
          StartCoolDownTimer(Math.AbsFloat((specialty_weight * 100)) * COOLDOWN_TIMER);
          SynchSpecialtyLevel();
        }
        else if (specialty_weight > 0)
        {
          if (IsLinear())
            SetSpecialtyLevel(AddLinearRough(specialty_weight));
          else
            SetSpecialtyLevel(AddExponentialRough(specialty_weight));
          m_Player.GetStatSpecialty().Set(m_SpecialtyLevel);
          StartCoolDownTimer(Math.AbsFloat((specialty_weight * 100)) * COOLDOWN_TIMER);
          SynchSpecialtyLevel();
        }
        else
        {
          //if the specialty weight for a recipe or UA is set to 0, it will increase neither specialty, nor UA counter
          return;
        }
      }
      else
        StartCoolDownTimer(Math.AbsFloat((specialty_weight * 100)) * COOLDOWN_TIMER);
    }
  }
References Math::AbsFloat(), AddExponentialPrecise(), AddExponentialRough(), AddLinearPrecise(), AddLinearRough(), COOLDOWN_TIMER, GetSoftSkillsState(), IsCoolDown(), IsLinear(), m_Player, m_SpecialtyLevel, SetSpecialtyLevel(), StartCoolDownTimer(), and SynchSpecialtyLevel().
AddSpecialtyBonus()
float SoftSkillsManager::AddSpecialtyBonus (float base_value, float specialty_weight, bool is_cacomponent = false, float limit_efficiency = 2) inline protected
Definition at line 158 of file SoftSkillsManager.c.
  {
    if (specialty_weight == 0)
      return base_value;
    SetBonusBefore(is_cacomponent, base_value);
    float adjusted_value;
    GetPreciseRoughLevels();
    if (limit_efficiency != 0)
    {
      if (specialty_weight < 0)
        adjusted_value = base_value + ((base_value * m_PreciseLevel) / limit_efficiency);
      else
        adjusted_value = base_value + ((base_value * m_RoughLevel) / limit_efficiency);
    }
    else
    {
      if (specialty_weight < 0)
        adjusted_value = base_value + ((base_value * m_PreciseLevel));
      else
        adjusted_value = base_value + ((base_value * m_RoughLevel));
    }
    SetBonusAfter(is_cacomponent, adjusted_value);
    return adjusted_value;
  }
References GetPreciseRoughLevels(), m_PreciseLevel, m_RoughLevel, SetBonusAfter(), and SetBonusBefore().
AdjustCraftingTime()
float SoftSkillsManager::AdjustCraftingTime (float base_time, float specialty_weight, float limit_efficiency = 2) inline protected
Definition at line 226 of file SoftSkillsManager.c.
  {
    if (specialty_weight == 0)
      return base_time;
    SetBonusBefore(false, base_time);
    float adjusted_time;
    GetPreciseRoughLevels();
    if (specialty_weight < 0)
      adjusted_time = base_time - ((base_time * m_PreciseLevel) / limit_efficiency);
    else
      adjusted_time = base_time - ((base_time * m_RoughLevel) / limit_efficiency);
    SetBonusAfter(false, adjusted_time);
    return adjusted_time;
  }
References GetPreciseRoughLevels(), m_PreciseLevel, m_RoughLevel, SetBonusAfter(), and SetBonusBefore().
CreateDebugWindow()
void SoftSkillsManager::CreateDebugWindow (bool create) inline protected
Definition at line 341 of file SoftSkillsManager.c.
  {
    if (create)
    {
      m_DebugWindow = new SoftSkillManagerDebug(this);
      SetIsDebug(create);
    }
    else
    {
      ResetDebugWindow();
      SetIsDebug(create);
      delete m_DebugWindow;
    }
  }
References m_DebugWindow, ResetDebugWindow(), SetIsDebug(), and SoftSkillManagerDebug().
GetComponentBonusAfter()
float SoftSkillsManager::GetComponentBonusAfter () inline protected
Definition at line 439 of file SoftSkillsManager.c.
  {
    return m_ComponentBonusAfter;
  }
References m_ComponentBonusAfter.
GetComponentBonusBefore()
float SoftSkillsManager::GetComponentBonusBefore () inline protected
Definition at line 427 of file SoftSkillsManager.c.
  {
    return m_ComponentBonusBefore;
  }
References m_ComponentBonusBefore.
GetCoolDownValue()
float SoftSkillsManager::GetCoolDownValue () inline protected
Definition at line 385 of file SoftSkillsManager.c.
  {
    return m_CoolDownValue;
  }
References m_CoolDownValue.
GetGeneralBonusAfter()
float SoftSkillsManager::GetGeneralBonusAfter () inline protected
Definition at line 463 of file SoftSkillsManager.c.
  {
    return m_GeneralBonusAfter;
  }
References m_GeneralBonusAfter.
GetGeneralBonusBefore()
float SoftSkillsManager::GetGeneralBonusBefore () inline protected
Definition at line 451 of file SoftSkillsManager.c.
  {
    return m_GeneralBonusBefore;
  }
References m_GeneralBonusBefore.
GetLastUAValue()
float SoftSkillsManager::GetLastUAValue () inline protected
Definition at line 391 of file SoftSkillsManager.c.
  {
    return m_LastUAValue;
  }
References m_LastUAValue.
GetPreciseRoughLevels()
void SoftSkillsManager::GetPreciseRoughLevels () inline protected
Definition at line 299 of file SoftSkillsManager.c.
  {
    if (m_SpecialtyLevel > 0)
    {
      m_RoughLevel = m_SpecialtyLevel;
      m_PreciseLevel = DEFAULT_EFFICIENCY;
    }
    else if (m_SpecialtyLevel < 0)
    {
      m_RoughLevel = DEFAULT_EFFICIENCY;
      m_PreciseLevel = Math.AbsFloat(m_SpecialtyLevel);
    }
    else
    {
      m_RoughLevel = DEFAULT_EFFICIENCY;
      m_PreciseLevel = DEFAULT_EFFICIENCY;
    }
  }
References Math::AbsFloat(), DEFAULT_EFFICIENCY, m_PreciseLevel, m_RoughLevel, and m_SpecialtyLevel.
Referenced by AddSpecialtyBonus(), AdjustCraftingTime(), and SubtractSpecialtyBonus().
GetSoftSkillsPlayer()
PlayerBase SoftSkillsManager::GetSoftSkillsPlayer () inline protected
Definition at line 248 of file SoftSkillsManager.c.
  {
    return m_Player;
  }
References m_Player.
GetSoftSkillsState()
bool SoftSkillsManager::GetSoftSkillsState () inline protected
Definition at line 281 of file SoftSkillsManager.c.
  {
    return m_IsActive;
  }
References m_IsActive.
Referenced by AddSpecialty().
GetSpecialtyLevel()
float SoftSkillsManager::GetSpecialtyLevel () inline protected
Definition at line 260 of file SoftSkillsManager.c.
  {
    return m_SpecialtyLevel;
  }
References m_SpecialtyLevel.
Referenced by OnUpdate().
InitSpecialty()
void SoftSkillsManager::InitSpecialty (float specialty_level) inline protected
Definition at line 42 of file SoftSkillsManager.c.
  {
    SetSpecialtyLevel(specialty_level);
    SynchSpecialtyLevel();
  }
References SetSpecialtyLevel(), and SynchSpecialtyLevel().
IsCoolDown()
bool SoftSkillsManager::IsCoolDown () inline protected
Definition at line 327 of file SoftSkillsManager.c.
  {
    return m_IsCoolDown;
  }
References m_IsCoolDown.
Referenced by AddSpecialty().
IsDebug()
bool SoftSkillsManager::IsDebug () inline protected
Definition at line 373 of file SoftSkillsManager.c.
  {
    return m_IsDebugMode;
  }
References m_IsDebugMode.
Referenced by SetBonusAfter(), and SetBonusBefore().
IsLinear()
bool SoftSkillsManager::IsLinear () inline protected
Definition at line 293 of file SoftSkillsManager.c.
  {
    return m_IsLinear;
  }
References m_IsLinear.
Referenced by AddSpecialty().
ResetDebugWindow()
void SoftSkillsManager::ResetDebugWindow () inline protected
Definition at line 495 of file SoftSkillsManager.c.
  {
    SetSpecialtyLevel(0);
    SetLastUAValue(0);
    SetComponentBonusBefore(0);
    SetComponentBonusAfter(0);
    SetGeneralBonusBefore(0);
    SetGeneralBonusAfter(0);
    SetCoolDownValue(0);
    SynchSpecialtyLevel();
  }
References SetComponentBonusAfter(), SetComponentBonusBefore(), SetCoolDownValue(), SetGeneralBonusAfter(), SetGeneralBonusBefore(), SetLastUAValue(), SetSpecialtyLevel(), and SynchSpecialtyLevel().
Referenced by CreateDebugWindow().
SetBonusAfter()
void SoftSkillsManager::SetBonusAfter (bool is_cacomponent, float adjusted_value) inline protected
Definition at line 415 of file SoftSkillsManager.c.
  {
    if (IsDebug())
    {
      if (is_cacomponent)
        SetComponentBonusAfter(adjusted_value);
      else
        SetGeneralBonusAfter(adjusted_value);
    }
  }
References IsDebug(), SetComponentBonusAfter(), and SetGeneralBonusAfter().
Referenced by AddSpecialtyBonus(), AdjustCraftingTime(), and SubtractSpecialtyBonus().
SetBonusBefore()
void SoftSkillsManager::SetBonusBefore (bool is_cacomponent, float base_value) inline protected
Definition at line 403 of file SoftSkillsManager.c.
  {
    if (IsDebug())
    {
      if (is_cacomponent)
        SetComponentBonusBefore(base_value);
      else
        SetGeneralBonusBefore(base_value);
    }
  }
References IsDebug(), SetComponentBonusBefore(), and SetGeneralBonusBefore().
Referenced by AddSpecialtyBonus(), AdjustCraftingTime(), and SubtractSpecialtyBonus().
SetComponentBonusAfter()
void SoftSkillsManager::SetComponentBonusAfter (float component_bonus_after) inline protected
Definition at line 445 of file SoftSkillsManager.c.
  {
    m_ComponentBonusAfter = component_bonus_after;
  }
References m_ComponentBonusAfter.
Referenced by ResetDebugWindow(), and SetBonusAfter().
SetComponentBonusBefore()
void SoftSkillsManager::SetComponentBonusBefore (float component_bonus_before) inline protected
Definition at line 433 of file SoftSkillsManager.c.
  {
    m_ComponentBonusBefore = component_bonus_before;
  }
References m_ComponentBonusBefore.
Referenced by ResetDebugWindow(), and SetBonusBefore().
SetCoolDown()
void SoftSkillsManager::SetCoolDown (bool cool_down) inline protected
Definition at line 333 of file SoftSkillsManager.c.
  {
    m_IsCoolDown = cool_down;
  }
References m_IsCoolDown.
Referenced by StartCoolDownTimer().
SetCoolDownValue()
void SoftSkillsManager::SetCoolDownValue (float cooldown_value) inline protected
Definition at line 379 of file SoftSkillsManager.c.
  {
    m_CoolDownValue = cooldown_value;
  }
References m_CoolDownValue.
Referenced by ResetDebugWindow(), and StartCoolDownTimer().
SetGeneralBonusAfter()
void SoftSkillsManager::SetGeneralBonusAfter (float general_bonus_after) inline protected
Definition at line 469 of file SoftSkillsManager.c.
  {
    m_GeneralBonusAfter = general_bonus_after;
  }
References m_GeneralBonusAfter.
Referenced by ResetDebugWindow(), and SetBonusAfter().
SetGeneralBonusBefore()
void SoftSkillsManager::SetGeneralBonusBefore (float general_bonus_before) inline protected
Definition at line 457 of file SoftSkillsManager.c.
  {
    m_GeneralBonusBefore = general_bonus_before;
  }
References m_GeneralBonusBefore.
Referenced by ResetDebugWindow(), and SetBonusBefore().
SetIsDebug()
void SoftSkillsManager::SetIsDebug (bool is_debug) inline protected
Definition at line 367 of file SoftSkillsManager.c.
  {
    m_IsDebugMode = is_debug;
  }
References m_IsDebugMode.
Referenced by CreateDebugWindow(), StartSynchTimer(), and StopSynchTimer().
SetLastUAValue()
void SoftSkillsManager::SetLastUAValue (float last_ua_value) inline protected
Definition at line 397 of file SoftSkillsManager.c.
  {
    m_LastUAValue = last_ua_value;
  }
References m_LastUAValue.
Referenced by AddExponentialPrecise(), AddExponentialRough(), AddLinearPrecise(), AddLinearRough(), and ResetDebugWindow().
SetLinearState()
void SoftSkillsManager::SetLinearState (bool model) inline protected
Definition at line 287 of file SoftSkillsManager.c.
  {
    m_IsLinear = model;
  }
References m_IsLinear.
SetSoftSkillsState()
void SoftSkillsManager::SetSoftSkillsState (bool state) inline protected
Definition at line 275 of file SoftSkillsManager.c.
  {
    m_IsActive = state;
  }
References m_IsActive.
SetSpecialtyLevel()
void SoftSkillsManager::SetSpecialtyLevel (float specialty_level) inline protected
Definition at line 254 of file SoftSkillsManager.c.
  {
    m_SpecialtyLevel = specialty_level;
  }
References m_SpecialtyLevel.
Referenced by AddSpecialty(), InitSpecialty(), and ResetDebugWindow().
StartCoolDownTimer()
void SoftSkillsManager::StartCoolDownTimer (float cooldown_value) inline protected
Definition at line 319 of file SoftSkillsManager.c.
  {
    SetCoolDown(true);
    SetCoolDownValue(cooldown_value);
    m_CoolDownTimer.Run(cooldown_value, this, "SetCoolDown", new Param1<bool>(false));
  }
References m_CoolDownTimer, SetCoolDown(), and SetCoolDownValue().
Referenced by AddSpecialty().
StartSynchTimer()
void SoftSkillsManager::StartSynchTimer () inline protected
Definition at line 475 of file SoftSkillsManager.c.
  {
    SetIsDebug(true);
    m_SynchTimer = new Timer;
    m_SynchTimer.Run(2, this, "SynchDebugStats", NULL, true);
  }
References m_SynchTimer, and SetIsDebug().
StopSynchTimer()
void SoftSkillsManager::StopSynchTimer () inline protected
Definition at line 483 of file SoftSkillsManager.c.
  {
    SetIsDebug(false);
    if (m_SynchTimer)
    {
      m_SynchTimer.Stop();
      delete m_SynchTimer;
    }
  }
References m_SynchTimer, and SetIsDebug().
SubtractSpecialtyBonus()
float SoftSkillsManager::SubtractSpecialtyBonus (float base_value, float specialty_weight, bool is_cacomponent = false, float limit_efficiency = 2) inline protected
Definition at line 192 of file SoftSkillsManager.c.
  {
    if (specialty_weight == 0)
      return base_value;
    SetBonusBefore(is_cacomponent, base_value);
    float adjusted_value;
    GetPreciseRoughLevels();
    if (limit_efficiency != 0)
    {
      if (specialty_weight < 0)
        adjusted_value = base_value - ((base_value * m_PreciseLevel) / limit_efficiency);
      else
        adjusted_value = base_value - ((base_value * m_RoughLevel) / limit_efficiency);
    }
    else
    {
      if (specialty_weight < 0)
        adjusted_value = base_value - ((base_value * m_PreciseLevel));
      else
        adjusted_value = base_value - ((base_value * m_RoughLevel));
    }
    SetBonusAfter(is_cacomponent, adjusted_value);
    return adjusted_value;
  }
References GetPreciseRoughLevels(), m_PreciseLevel, m_RoughLevel, SetBonusAfter(), and SetBonusBefore().
SynchDebugStats()
void SoftSkillsManager::SynchDebugStats () inline protected
Definition at line 357 of file SoftSkillsManager.c.
  {
    if (GetGame().IsServer() && GetGame().IsMultiplayer())
    {
      Param5<float, float, float, float, bool> debug_stats = new Param5<float, float, float, float, bool>(m_GeneralBonusBefore, m_GeneralBonusAfter, m_LastUAValue, m_CoolDownValue, m_IsCoolDown);
      GetGame().RPCSingleParam(m_Player, ERPCs.RPC_SOFT_SKILLS_STATS_SYNC, debug_stats, true, m_Player.GetIdentity());
    }
  }
References GetGame(), m_CoolDownValue, m_GeneralBonusAfter, m_GeneralBonusBefore, m_IsCoolDown, m_LastUAValue, and m_Player.
SynchSpecialtyLevel()
void SoftSkillsManager::SynchSpecialtyLevel () inline protected
Definition at line 266 of file SoftSkillsManager.c.
  {
#ifdef SERVER
    Param1<float> specialty_level = new Param1<float>(m_SpecialtyLevel);
    GetGame().RPCSingleParam(m_Player, ERPCs.RPC_SOFT_SKILLS_SPECIALTY_SYNC, specialty_level, true, m_Player.GetIdentity());
#endif
  }
References GetGame(), m_Player, and m_SpecialtyLevel.
Referenced by AddSpecialty(), InitSpecialty(), and ResetDebugWindow().
Member Data Documentation
COOLDOWN_TIMER
const float SoftSkillsManager::COOLDOWN_TIMER = 5 static protected
Definition at line 17 of file SoftSkillsManager.c.
Referenced by AddSpecialty().
DEFAULT_EFFICIENCY
const int SoftSkillsManager::DEFAULT_EFFICIENCY = 0 static protected
Definition at line 14 of file SoftSkillsManager.c.
Referenced by GetPreciseRoughLevels().
m_ComponentBonusAfter
float SoftSkillsManager::m_ComponentBonusAfter protected
Definition at line 25 of file SoftSkillsManager.c.
Referenced by GetComponentBonusAfter(), and SetComponentBonusAfter().
m_ComponentBonusBefore
float SoftSkillsManager::m_ComponentBonusBefore protected
Definition at line 24 of file SoftSkillsManager.c.
Referenced by GetComponentBonusBefore(), and SetComponentBonusBefore().
m_CoolDownTimer
ref Timer SoftSkillsManager::m_CoolDownTimer = new Timer() protected
Definition at line 19 of file SoftSkillsManager.c.
Referenced by StartCoolDownTimer(), and ~SoftSkillsManager().
m_CoolDownValue
float SoftSkillsManager::m_CoolDownValue protected
Definition at line 22 of file SoftSkillsManager.c.
Referenced by GetCoolDownValue(), SetCoolDownValue(), and SynchDebugStats().
m_DebugWindow
ref SoftSkillManagerDebug SoftSkillsManager::m_DebugWindow protected
Definition at line 29 of file SoftSkillsManager.c.
Referenced by CreateDebugWindow().
m_GeneralBonusAfter
float SoftSkillsManager::m_GeneralBonusAfter protected
Definition at line 27 of file SoftSkillsManager.c.
Referenced by GetGeneralBonusAfter(), SetGeneralBonusAfter(), and SynchDebugStats().
m_GeneralBonusBefore
float SoftSkillsManager::m_GeneralBonusBefore protected
Definition at line 26 of file SoftSkillsManager.c.
Referenced by GetGeneralBonusBefore(), SetGeneralBonusBefore(), and SynchDebugStats().
m_IsActive
bool SoftSkillsManager::m_IsActive protected
Definition at line 9 of file SoftSkillsManager.c.
Referenced by GetSoftSkillsState(), SetSoftSkillsState(), and SoftSkillsManager().
m_IsCoolDown
bool SoftSkillsManager::m_IsCoolDown protected
Definition at line 10 of file SoftSkillsManager.c.
Referenced by IsCoolDown(), SetCoolDown(), SoftSkillsManager(), and SynchDebugStats().
m_IsDebugMode
bool SoftSkillsManager::m_IsDebugMode protected
Definition at line 21 of file SoftSkillsManager.c.
Referenced by IsDebug(), SetIsDebug(), and SoftSkillsManager().
m_IsLinear
bool SoftSkillsManager::m_IsLinear protected
Definition at line 8 of file SoftSkillsManager.c.
Referenced by IsLinear(), SetLinearState(), and SoftSkillsManager().
m_LastUAValue
float SoftSkillsManager::m_LastUAValue protected
Definition at line 23 of file SoftSkillsManager.c.
Referenced by GetLastUAValue(), SetLastUAValue(), and SynchDebugStats().
m_Player
PlayerBase SoftSkillsManager::m_Player protected
Definition at line 3 of file SoftSkillsManager.c.
Referenced by AddSpecialty(), GetSoftSkillsPlayer(), SoftSkillsManager(), SynchDebugStats(), and SynchSpecialtyLevel().
m_PreciseLevel
float SoftSkillsManager::m_PreciseLevel protected
Definition at line 6 of file SoftSkillsManager.c.
Referenced by AddSpecialtyBonus(), AdjustCraftingTime(), GetPreciseRoughLevels(), and SubtractSpecialtyBonus().
m_RoughLevel
float SoftSkillsManager::m_RoughLevel protected
Definition at line 5 of file SoftSkillsManager.c.
Referenced by AddSpecialtyBonus(), AdjustCraftingTime(), GetPreciseRoughLevels(), and SubtractSpecialtyBonus().
m_SpecialtyLevel
float SoftSkillsManager::m_SpecialtyLevel protected
Definition at line 4 of file SoftSkillsManager.c.
Referenced by AddExponentialPrecise(), AddExponentialRough(), AddLinearPrecise(), AddLinearRough(), AddSpecialty(), GetPreciseRoughLevels(), GetSpecialtyLevel(), SetSpecialtyLevel(), and SynchSpecialtyLevel().
m_SynchTimer
ref Timer SoftSkillsManager::m_SynchTimer protected
Definition at line 31 of file SoftSkillsManager.c.
Referenced by StartSynchTimer(), and StopSynchTimer().
m_UserActionsCounter
int SoftSkillsManager::m_UserActionsCounter protected
Definition at line 12 of file SoftSkillsManager.c.
Referenced by AddExponentialPrecise(), and AddExponentialRough().
PRECISE_WEIGHT_LIMIT
const float SoftSkillsManager::PRECISE_WEIGHT_LIMIT = -1 static protected
Definition at line 15 of file SoftSkillsManager.c.
Referenced by AddExponentialPrecise(), AddExponentialRough(), AddLinearPrecise(), and AddLinearRough().
ROUGH_WEIGHT_LIMIT
const float SoftSkillsManager::ROUGH_WEIGHT_LIMIT = 1 static protected
Definition at line 16 of file SoftSkillsManager.c.
Referenced by AddExponentialPrecise(), AddExponentialRough(), AddLinearPrecise(), and AddLinearRough().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/SoftSkillsManager.c