DayZ: SpookyArea Class Reference
SpookyArea Class Reference
Private Member Functions
override void EEInit ()
override void InitZoneServer ()
override void InitZoneClient ()
Detailed Description
Definition at line 2 of file SpookyArea.c.
Member Function Documentation
EEInit()
override void SpookyArea::EEInit () inline private
Definition at line 7 of file SpookyArea.c.
  {
    // We make sure we have the particle array
    if (!m_ToxicClouds)
      m_ToxicClouds = new array<Particle>;
    SetSynchDirty();
#ifdef DEVELOPER
    // Debugs when placing entity by hand using internal tools
    if (GetGame().IsServer() && !GetGame().IsMultiplayer())
    {
      Debug.Log("YOU CAN IGNORE THE FOLLOWING DUMP");
      InitZone();
      Debug.Log("YOU CAN USE FOLLOWING DATA PROPERLY");
    }
#endif
    if (GetGame().IsClient() && GetGame().IsMultiplayer())
      InitZone();
    super.EEInit();
  }
References GetGame(), EffectArea::InitZone(), Debug::Log(), and EffectArea::m_ToxicClouds.
InitZoneClient()
override void SpookyArea::InitZoneClient () inline private
Definition at line 40 of file SpookyArea.c.
  {
    super.InitZoneClient();
    // We spawn VFX on client
    PlaceParticles(GetWorldPosition(), m_Radius, m_InnerRings, m_InnerSpacing, m_OuterRingToggle, m_OuterSpacing, m_OuterRingOffset, m_ParticleID);
  }
References EffectArea::m_InnerRings, EffectArea::m_InnerSpacing, EffectArea::m_OuterRingOffset, EffectArea::m_OuterRingToggle, EffectArea::m_OuterSpacing, EffectArea::m_ParticleID, EffectArea::m_Radius, and EffectArea::PlaceParticles().
InitZoneServer()
override void SpookyArea::InitZoneServer () inline private
Definition at line 31 of file SpookyArea.c.
  {
    super.InitZoneServer();
    // We create the trigger on server
    if (m_TriggerType != "")
      CreateTrigger(m_Position, m_Radius);
  }
References CreateTrigger(), EffectArea::m_Position, EffectArea::m_Radius, and EffectArea::m_TriggerType.
The documentation for this class was generated from the following file:
scripts/4_World/Classes/ContaminatedArea/SpookyArea.c