DayZ: scripts/3_Game/Systems/Inventory/Debug.c File Reference
Debug.c File Reference
Functions
void syncDebugPrint (string s)
void actionDebugPrint (string s)
void inventoryDebugPrint (string s)
Function Documentation
actionDebugPrint()
void actionDebugPrint (string s)
Definition at line 10 of file Debug.c.
{
#ifdef INV_DEBUG
  PrintToRPT("" + s); // comment/uncomment to hide/see debug logs
#else
  Print("" + s); // comment/uncomment to hide/see debug logs
#endif
}
References Print(), and PrintToRPT().
inventoryDebugPrint()
void inventoryDebugPrint (string s)
Definition at line 19 of file Debug.c.
{
#ifdef INV_DEBUG
  PrintToRPT("" + s); // comment/uncomment to hide/see debug logs
#else
  //Print("" + s); // comment/uncomment to hide/see debug logs
#endif
}
References PrintToRPT().
Referenced by GameInventory::DropEntity(), GameInventory::DropEntityInBounds(), GameInventory::DropEntityWithTransform(), GameInventory::EEInit(), HandleForceSwapEntities(), HandleSwapEntities(), HandleTakeToDst(), GameInventory::LocalDestroyEntity(), GameInventory::ReplaceItemWithNew(), GameInventory::TakeEntityAsAttachment(), GameInventory::TakeEntityAsAttachmentEx(), GameInventory::TakeEntityAsTargetAttachment(), GameInventory::TakeEntityAsTargetAttachmentEx(), GameInventory::TakeEntityToCargo(), GameInventory::TakeEntityToCargoEx(), GameInventory::TakeEntityToInventory(), GameInventory::TakeEntityToTargetCargo(), GameInventory::TakeEntityToTargetCargoEx(), and GameInventory::TakeEntityToTargetInventory().
syncDebugPrint()
void syncDebugPrint (string s)
Definition at line 1 of file Debug.c.
{
#ifdef INV_DEBUG
  PrintToRPT("" + s); // comment/uncomment to hide/see debug logs
#else
  //Print("" + s); // comment/uncomment to hide/see debug logs
#endif
}
References PrintToRPT().
Referenced by HandEventBase::CheckRequestSrc(), EntityAI::DropEntityImpl(), EntityAI::ForceSwapEntitiesImpl(), EntityAI::LocalDestroyEntityInHands(), ManBase::NeedInventoryJunctureFromServer(), OnHandleStoredInputUserData(), OnHandleStoredJunctureData(), OnInputUserDataForRemote(), OnInputUserDataProcess(), OnInventoryJunctureFromServer(), ManBase::OnQuickBarSingleUse(), OnServerInventoryCommand(), GameInventory::OnServerInventoryCommandStatic(), DayZPlayerCommandDeathCallback::OnSimulationEnd(), EntityAI::PredictiveMoveItemFromHandsToInventory(), EntityAI::ReplaceItemElsewhereWithNewInHandsImpl(), EntityAI::ReplaceItemInHandsWithNewElsewhereImpl(), EntityAI::ReplaceItemInHandsWithNewImpl(), EntityAI::ReplaceItemWithNewImpl(), InventoryInputUserData::SendInputUserDataDestroy(), InventoryInputUserData::SendInputUserDataHandEvent(), InventoryInputUserData::SendInputUserDataMove(), InventoryInputUserData::SendInputUserDataSwap(), InventoryInputUserData::SendServerHandEventViaInventoryCommand(), SendServerHandEventViaJuncture(), InventoryInputUserData::SendServerMove(), InventoryInputUserData::SendServerSwap(), EntityAI::SwapEntitiesImpl(), EntityAI::TakeEntityAsAttachmentExImpl(), EntityAI::TakeEntityAsAttachmentImpl(), ManBase::TakeEntityAsAttachmentImpl(), EntityAI::TakeEntityToCargoImpl(), ManBase::TakeEntityToCargoImpl(), EntityAI::TakeEntityToHandsImpl(), ManBase::TakeEntityToHandsImpl(), EntityAI::TakeEntityToInventoryImpl(), ManBase::TakeEntityToInventoryImpl(), EntityAI::TakeEntityToTargetAttachmentExImpl(), ManBase::TakeEntityToTargetAttachmentImpl(), EntityAI::TakeEntityToTargetCargoExImpl(), EntityAI::TakeEntityToTargetCargoImpl(), ManBase::TakeEntityToTargetCargoImpl(), EntityAI::TakeEntityToTargetInventoryImpl(), ManBase::TakeEntityToTargetInventoryImpl(), TakeToDst(), EntityAI::TakeToDstImpl(), ManBase::TakeToDstImpl(), TryAcquireInventoryJunctureFromServer(), TryAcquireTwoInventoryJuncturesFromServer(), ValidateHandEvent(), ValidateSwap(), and ValidateSyncMove().