DayZ: GPSReceiver Class Reference
GPSReceiver Class Reference
Protected Member Functions
void GPSReceiver ()
void PositionalUpdate ()
override void OnMovedInsideCargo (EntityAI container)
need to be overriden, otherwise the item will be turned off when moved to cargo
override void SetActions ()
override bool IsTurnedOn ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnWork (float consumed_energy)
void UpdateDisplayState (bool pIsTurnedOn)
void UpdateDisplayPosition ()
void UpdateDisplayElevation ()
int GetHiddenSelection (string selection)
override void OnDebugSpawn ()
Protected Attributes
ref set< string > m_DisplayGridSelections
ref set< string > m_DisplayAltSelections
ref map< int, string > m_DisplayNumericSignTextureMap
ref array< int > m_OrderedPositionNumbersLast
cache
ref array< int > m_AltitudeNumbersLast
Private Attributes
const string DISPLAY_TEXTURE_PATH_FORMAT = "dz\\gear\\navigation\\data\\GPS_%1_ca.paa"
const string ANIM_PHASE_DISPLAY_HIDE = "DisplayState"
Detailed Description
Definition at line 1 of file GPSReceiver.c.
Constructor & Destructor Documentation
GPSReceiver()
void GPSReceiver::GPSReceiver () inline protected
translate numerical -1 to - texture
Definition at line 15 of file GPSReceiver.c.
  {
    m_OrderedPositionNumbersLast = new array<int>;
    m_AltitudeNumbersLast = new array<int>;
    int i;
    for (i = 0; i < MapNavigationBehaviour.DISPLAY_GRID_POS_MAX_CHARS_COUNT * 2; ++i)
      m_OrderedPositionNumbersLast.Insert(0);
    for (i = 0; i < MapNavigationBehaviour.DISPLAY_ALT_MAX_CHARS_COUNT; ++i)
      m_AltitudeNumbersLast.Insert(0);
    m_DisplayGridSelections = new set<string>();
    m_DisplayGridSelections.Insert("grid_1_0");
    m_DisplayGridSelections.Insert("grid_1_1");
    m_DisplayGridSelections.Insert("grid_1_2");
    m_DisplayGridSelections.Insert("grid_2_0");
    m_DisplayGridSelections.Insert("grid_2_1");
    m_DisplayGridSelections.Insert("grid_2_2");
    m_DisplayAltSelections = new set<string>();
    m_DisplayAltSelections.Insert("alt_0");
    m_DisplayAltSelections.Insert("alt_1");
    m_DisplayAltSelections.Insert("alt_2");
    m_DisplayAltSelections.Insert("alt_3");
    m_DisplayNumericSignTextureMap = new map<int, string>();
    for (i = -1; i < 11; i++)
    {
      string texturePath = string.Format(DISPLAY_TEXTURE_PATH_FORMAT, i);
      if (i == -1)
        texturePath = string.Format(DISPLAY_TEXTURE_PATH_FORMAT, "dash");
      m_DisplayNumericSignTextureMap.Insert(i, texturePath);
    }
  }
References DISPLAY_TEXTURE_PATH_FORMAT, m_AltitudeNumbersLast, m_DisplayAltSelections, m_DisplayGridSelections, m_DisplayNumericSignTextureMap, m_OrderedPositionNumbersLast, and MapNavigationBehaviour().
Member Function Documentation
GetHiddenSelection()
int GPSReceiver::GetHiddenSelection (string selection) inline protected
Definition at line 151 of file GPSReceiver.c.
  {
    int idx = GetHiddenSelectionIndex(selection);
    if (idx != INDEX_NOT_FOUND)
      return idx;
    else
      return 0;
  }
References INDEX_NOT_FOUND.
Referenced by UpdateDisplayElevation(), and UpdateDisplayPosition().
IsTurnedOn()
override bool GPSReceiver::IsTurnedOn () inline protected
Definition at line 72 of file GPSReceiver.c.
  {
    return GetCompEM() && GetCompEM().IsWorking();
  }
OnDebugSpawn()
override void GPSReceiver::OnDebugSpawn () inline protected
Definition at line 165 of file GPSReceiver.c.
  {
    Battery9V.Cast(GetInventory().CreateInInventory("Battery9V"));
  }
OnMovedInsideCargo()
override void GPSReceiver::OnMovedInsideCargo (EntityAI container) protected
need to be overriden, otherwise the item will be turned off when moved to cargo
OnWork()
override void GPSReceiver::OnWork (float consumed_energy) inline protected
Definition at line 102 of file GPSReceiver.c.
  {
    PositionalUpdate();
  }
References PositionalUpdate().
OnWorkStart()
override void GPSReceiver::OnWorkStart () inline protected
Definition at line 78 of file GPSReceiver.c.
  {
    UpdateDisplayState(true);
    if (GetHierarchyRoot())
    {
      PlayerBase pb = PlayerBase.Cast(GetHierarchyRoot());
      if (pb)
        pb.MapNavigationItemInPossession(this);
    }
  }
References UpdateDisplayState().
OnWorkStop()
override void GPSReceiver::OnWorkStop () inline protected
Definition at line 90 of file GPSReceiver.c.
  {
    UpdateDisplayState(false);
    if (GetHierarchyRoot())
    {
      PlayerBase pb = PlayerBase.Cast(GetHierarchyRoot());
      if (pb)
        pb.MapNavigationItemNotInPossession(this);
    }
  }
References UpdateDisplayState().
PositionalUpdate()
void GPSReceiver::PositionalUpdate () inline protected
Definition at line 55 of file GPSReceiver.c.
  {
    UpdateDisplayPosition();
    UpdateDisplayElevation();
  }
References UpdateDisplayElevation(), and UpdateDisplayPosition().
Referenced by OnWork().
SetActions()
override void GPSReceiver::SetActions () inline protected
Definition at line 64 of file GPSReceiver.c.
  {
    super.SetActions();
    AddAction(ActionTurnOnWhileInHands);
    AddAction(ActionTurnOffWhileInHands);
  }
References AddAction().
UpdateDisplayElevation()
void GPSReceiver::UpdateDisplayElevation () inline protected
Definition at line 132 of file GPSReceiver.c.
  {
    int selectionIndex;
    string selectionName;
    array<int> altitudeNumbers = MapNavigationBehaviour.OrderedAltitudeNumbersPosition(this);
    if (altitudeNumbers.DifferentAtPosition(m_AltitudeNumbersLast) != INDEX_NOT_FOUND)
    {
      for (int i = 0; i < m_DisplayAltSelections.Count(); ++i)
      {
        selectionName = m_DisplayAltSelections.Get(i);
        selectionIndex = GetHiddenSelection(selectionName);
        SetObjectTexture(selectionIndex, m_DisplayNumericSignTextureMap.Get(altitudeNumbers.Get(i)));
      }
      m_AltitudeNumbersLast = altitudeNumbers;
    }
  }
References GetHiddenSelection(), INDEX_NOT_FOUND, m_AltitudeNumbersLast, m_DisplayAltSelections, m_DisplayNumericSignTextureMap, and MapNavigationBehaviour().
Referenced by PositionalUpdate().
UpdateDisplayPosition()
void GPSReceiver::UpdateDisplayPosition () inline protected
Definition at line 113 of file GPSReceiver.c.
  {
    int selectionIndex;
    string selectionName;
    array<int> orderedPositionNumbers = MapNavigationBehaviour.OrderedPositionNumbersFromGridCoords(this);
    if (orderedPositionNumbers.DifferentAtPosition(m_OrderedPositionNumbersLast) != INDEX_NOT_FOUND)
    {
      for (int i = 0; i < m_DisplayGridSelections.Count(); ++i)
      {
        selectionName = m_DisplayGridSelections.Get(i);
        selectionIndex = GetHiddenSelection(selectionName);
        SetObjectTexture(selectionIndex, m_DisplayNumericSignTextureMap.Get(orderedPositionNumbers.Get(i)));
      }
      m_OrderedPositionNumbersLast = orderedPositionNumbers;
    }
  }
References GetHiddenSelection(), INDEX_NOT_FOUND, m_DisplayGridSelections, m_DisplayNumericSignTextureMap, m_OrderedPositionNumbersLast, and MapNavigationBehaviour().
Referenced by PositionalUpdate().
UpdateDisplayState()
void GPSReceiver::UpdateDisplayState (bool pIsTurnedOn) inline protected
Definition at line 108 of file GPSReceiver.c.
  {
    SetAnimationPhaseNow(ANIM_PHASE_DISPLAY_HIDE, !pIsTurnedOn);
  }
References ANIM_PHASE_DISPLAY_HIDE.
Referenced by OnWorkStart(), and OnWorkStop().
Member Data Documentation
ANIM_PHASE_DISPLAY_HIDE
const string GPSReceiver::ANIM_PHASE_DISPLAY_HIDE = "DisplayState" private
Definition at line 5 of file GPSReceiver.c.
Referenced by UpdateDisplayState().
DISPLAY_TEXTURE_PATH_FORMAT
const string GPSReceiver::DISPLAY_TEXTURE_PATH_FORMAT = "dz\\gear\\navigation\\data\\GPS_%1_ca.paa" private
Definition at line 4 of file GPSReceiver.c.
Referenced by GPSReceiver().
m_AltitudeNumbersLast
ref array<int> GPSReceiver::m_AltitudeNumbersLast protected
Definition at line 13 of file GPSReceiver.c.
Referenced by GPSReceiver(), and UpdateDisplayElevation().
m_DisplayAltSelections
ref set<string> GPSReceiver::m_DisplayAltSelections protected
Definition at line 8 of file GPSReceiver.c.
Referenced by GPSReceiver(), and UpdateDisplayElevation().
m_DisplayGridSelections
ref set<string> GPSReceiver::m_DisplayGridSelections protected
Definition at line 7 of file GPSReceiver.c.
Referenced by GPSReceiver(), and UpdateDisplayPosition().
m_DisplayNumericSignTextureMap
ref map<int, string> GPSReceiver::m_DisplayNumericSignTextureMap protected
Definition at line 9 of file GPSReceiver.c.
Referenced by GPSReceiver(), UpdateDisplayElevation(), and UpdateDisplayPosition().
m_OrderedPositionNumbersLast
ref array<int> GPSReceiver::m_OrderedPositionNumbersLast protected
cache
Definition at line 12 of file GPSReceiver.c.
Referenced by GPSReceiver(), and UpdateDisplayPosition().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Gear/Navigation/GPSReceiver.c