DayZ: AnimSoundObjectBuilderBank Class Reference
AnimSoundObjectBuilderBank Class Reference
Private Member Functions
void AnimSoundObjectBuilderBank ()
SoundObjectBuilder GetBuilder (string soundSetName)
Static Private Member Functions
static AnimSoundObjectBuilderBank GetInstance ()
Private Attributes
autoptr map< int, ref SoundObjectBuilder > m_pBuilders
Static Private Attributes
static ref AnimSoundObjectBuilderBank m_instance
Detailed Description
Definition at line 129 of file DayZAnimEventMaps.c.
Constructor & Destructor Documentation
AnimSoundObjectBuilderBank()
void AnimSoundObjectBuilderBank::AnimSoundObjectBuilderBank () inline private
Definition at line 131 of file DayZAnimEventMaps.c.
  {
    m_pBuilders = new map<int, ref SoundObjectBuilder>();
  }
References m_pBuilders.
Referenced by GetInstance().
Member Function Documentation
GetBuilder()
SoundObjectBuilder AnimSoundObjectBuilderBank::GetBuilder (string soundSetName) inline private
Definition at line 146 of file DayZAnimEventMaps.c.
  {
    int soundSetNameHash = soundSetName.Hash();
    SoundObjectBuilder builder = m_pBuilders.Get(soundSetNameHash);
    if (builder == NULL)
    {
      SoundParams params = new SoundParams(soundSetName);
      if (params.IsValid())
      {
        builder = new SoundObjectBuilder(params);
        m_pBuilders.Insert(soundSetNameHash, builder);
      }
      else
      {
        Print("AnimSoundObjectBuilderBank: Invalid sound set \"" + soundSetName + "\".");
        return NULL;
      }
    }
    return builder;
  }
References m_pBuilders, Print(), and SoundObjectBuilder().
GetInstance()
static AnimSoundObjectBuilderBank AnimSoundObjectBuilderBank::GetInstance () inline static private
Definition at line 137 of file DayZAnimEventMaps.c.
  {
    if (m_instance == NULL)
      m_instance = new AnimSoundObjectBuilderBank();
    return m_instance;
  }
References AnimSoundObjectBuilderBank(), and m_instance.
Referenced by SoundLookupTable::LoadTable().
Member Data Documentation
m_instance
ref AnimSoundObjectBuilderBank AnimSoundObjectBuilderBank::m_instance static private
Definition at line 168 of file DayZAnimEventMaps.c.
Referenced by GetInstance().
m_pBuilders
autoptr map<int, ref SoundObjectBuilder> AnimSoundObjectBuilderBank::m_pBuilders private
Definition at line 169 of file DayZAnimEventMaps.c.
Referenced by AnimSoundObjectBuilderBank(), and GetBuilder().
The documentation for this class was generated from the following file:
scripts/3_Game/DayZAnimEventMaps.c