DayZ: scripts/4_World/Entities/ItemBase/Gear/Consumables/EasterEgg.c File Reference
EasterEgg.c File Reference
Enumerations
enum eCaptureState {
CAPTURE = 0 , RELEASE = 1 , STASIS = 2 , CAPTUREFX = 3 ,
RELEASEFX = 4 , END
}
Functions
void EasterEgg ()
void ~EasterEgg ()
void ContactEvent (IEntity other, vector pos)
override void EOnTouch (IEntity other, int extra)
override void EOnContact (IEntity other, Contact extra)
override void OnInventoryExit (Man player)
override void OnInventoryEnter (Man player)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
void Capture (DayZCreatureAI capAnimal)
void Release (vector pos)
void PlayVFX ()
void ResizeParticle (DayZCreatureAI capAnimal)
void PlaySFX (int releaseCase=eCaptureState.CAPTURE)
override void OnVariablesSynchronized ()
void RegisterSoundSetMap ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
void DestroyEg ()
Variables
enum eCaptureState m_StoredCreature = null
string m_CreatureType
int m_CreatureHash = 0
int m_CaptureState = eCaptureState.STASIS
const vector CAPTURE_VELOCITY = { 0, 0, 0 }
Particle m_ParCapture
float m_ParScale = 1
const float PARTICLE_SCALE_MULT = 0.1
EffectSound m_CaptureSound
EffectSound m_CreatureSound
bool m_DangerSound = false
ref map< int, string > m_CreatureSoundMap
int m_CaptureSoundHash
int m_ReleaseSoundHash
Enumeration Type Documentation
eCaptureState
enum eCaptureState
Enumerator
CAPTURE
RELEASE
STASIS
CAPTUREFX
RELEASEFX
END
Definition at line 1 of file EasterEgg.c.
{
  CAPTURE = 0,
  RELEASE = 1,
  STASIS = 2,
  CAPTUREFX = 3,
  RELEASEFX = 4,
  //Keep this last value at the end, add any new states before
  END
}
Function Documentation
Capture()
void Capture (DayZCreatureAI capAnimal) private
Definition at line 155 of file EasterEgg.c.
  {
    if (!IsAlive())
    {
      if (m_ParCapture)
        m_ParCapture.Delete();
      Delete();
      return;
    }
    m_StoredCreature = capAnimal;
    m_CreatureType = m_StoredCreature.GetType();
    m_CreatureHash = m_CreatureType.Hash();
    m_CaptureState = eCaptureState.CAPTUREFX;
    m_DangerSound = m_StoredCreature.IsDanger();
    m_CaptureSoundHash = m_StoredCreature.CaptureSound().Hash();
    m_ReleaseSoundHash = m_StoredCreature.ReleaseSound().Hash();
    //Resize particle upon capture as there is enough delay to be sure value is synced
    ResizeParticle(capAnimal);
    SetSynchDirty();
    capAnimal.Delete();
    SetQuantity(GetQuantityMax());
    SetVelocity(this, CAPTURE_VELOCITY);
  }
References CAPTURE_VELOCITY, GetQuantityMax(), string::Hash(), m_CaptureSoundHash, m_CaptureState, m_CreatureHash, m_CreatureType, m_DangerSound, m_ParCapture, m_ReleaseSoundHash, m_StoredCreature, ResizeParticle(), SetQuantity(), and SetVelocity().
Referenced by ContactEvent().
ContactEvent()
void ContactEvent (IEntity other, vector pos) protected
Definition at line 61 of file EasterEgg.c.
  {
    switch (m_CaptureState)
    {
    case eCaptureState.CAPTURE:
      DayZCreatureAI capAnimal = DayZCreatureAI.Cast(other);
      if (capAnimal && capAnimal.IsAlive())
      {
        if (GetGame().IsServer())
          Capture(capAnimal);
      }
      else
        m_CaptureState = eCaptureState.STASIS; //We did not capture anything, go back to stasis
      break;
    case eCaptureState.RELEASE:
      Release(pos);
      PlayVFX();
      PlaySFX(eCaptureState.RELEASE);
      break;
    case eCaptureState.CAPTUREFX:
    case eCaptureState.RELEASEFX:
      //Intermediate state to play FX on next client side contact event
      //Creates slight delay but saves network traffic
      if (m_CreatureHash != 0)
      {
        //Make sure to go back in stasis
        m_CaptureState = eCaptureState.STASIS;
        SetSynchDirty();
      }
      break;
    case eCaptureState.STASIS:
      //Do nothing here, feel free to add logic for fun fumble effects when nothing happens :)
      break;
    default: //default in case state is somehow not initialized
      break;
    }
  }
References Capture(), GetGame(), m_CaptureState, m_CreatureHash, PlaySFX(), PlayVFX(), and Release().
Referenced by EOnContact(), and EOnTouch().
DestroyEg()
void DestroyEg () private
Definition at line 403 of file EasterEgg.c.
  {
    Delete();
  }
EasterEgg()
void EasterEgg () protected
Definition at line 37 of file EasterEgg.c.
  {
    m_CreatureType = "";
    SetEventMask(EntityEvent.CONTACT | EntityEvent.TOUCH);
    SetFlags(EntityFlags.TRIGGER, false);
    RegisterNetSyncVariableInt("m_CaptureState", 0, eCaptureState.END);
    RegisterNetSyncVariableInt("m_CreatureHash", 0, 0);
    RegisterNetSyncVariableFloat("m_ParScale", 0, 0, 0.1);
    RegisterNetSyncVariableBool("m_DangerSound");
    RegisterNetSyncVariableInt("m_CaptureSoundHash", 0, 0);
    RegisterNetSyncVariableInt("m_ReleaseSoundHash", 0, 0);
    RegisterSoundSetMap();
  }
References m_CreatureType, RegisterSoundSetMap(), and SetFlags().
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) protected
Definition at line 145 of file EasterEgg.c.
  {
    super.EEItemLocationChanged(oldLoc, newLoc);
    //DestroyEg();
  }
EOnContact()
override void EOnContact (IEntity other, Contact extra) protected
Definition at line 112 of file EasterEgg.c.
  {
    ContactEvent(other, extra.Position);
  }
References ContactEvent().
EOnTouch()
override void EOnTouch (IEntity other, int extra) protected
Definition at line 106 of file EasterEgg.c.
  {
    ContactEvent(other, GetPosition());
  }
References ContactEvent(), and GetPosition.
OnInventoryEnter()
override void OnInventoryEnter (Man player) protected
Definition at line 135 of file EasterEgg.c.
  {
    //Make sure to stop particles once in inventory
    if (GetGame().IsClient() && m_ParCapture)
    {
      m_ParCapture.Stop();
      m_ParCapture.Delete();
    }
  }
References GetGame(), m_ParCapture, and Particle::Stop().
OnInventoryExit()
override void OnInventoryExit (Man player) protected
Definition at line 117 of file EasterEgg.c.
  {
    //Do not execute on simple drop as it may cause issues
    PlayerBase player_PB = PlayerBase.Cast(player);
    if (player_PB && player_PB.GetThrowing().IsThrowingAnimationPlaying())
    {
      if (m_CreatureType != "")
        m_CaptureState = eCaptureState.RELEASE;
      else
        m_CaptureState = eCaptureState.CAPTURE;
    }
    else
      m_CaptureState = eCaptureState.STASIS;
    //Make sure state is properly synchronized or VFX might bug out
    SetSynchDirty();
  }
References m_CaptureState, and m_CreatureType.
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) private
Definition at line 376 of file EasterEgg.c.
  {
    if (!super.OnStoreLoad(ctx, version))
      return false;
    if (!ctx.Read(m_CaptureState))
      return false;
    if (!ctx.Read(m_CreatureType))
      return false;
    if (!ctx.Read(m_ParScale))
      return false;
    if (!ctx.Read(m_DangerSound))
      return false;
    if (!ctx.Read(m_CaptureSoundHash))
      return false;
    if (!ctx.Read(m_ReleaseSoundHash))
      return false;
    return true;
  }
References m_CaptureSoundHash, m_CaptureState, m_CreatureType, m_DangerSound, m_ParScale, and m_ReleaseSoundHash.
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) private
Definition at line 364 of file EasterEgg.c.
  {
    super.OnStoreSave(ctx);
    ctx.Write(m_CaptureState);
    ctx.Write(m_CreatureType);
    ctx.Write(m_ParScale);
    ctx.Write(m_DangerSound);
    ctx.Write(m_CaptureSoundHash);
    ctx.Write(m_ReleaseSoundHash);
  }
References m_CaptureSoundHash, m_CaptureState, m_CreatureType, m_DangerSound, m_ParScale, and m_ReleaseSoundHash.
OnVariablesSynchronized()
override void OnVariablesSynchronized () private
Definition at line 270 of file EasterEgg.c.
  {
    if (m_CaptureState == eCaptureState.CAPTUREFX)
    {
      PlayVFX();
      PlaySFX();
    }
    else if (m_CaptureState == eCaptureState.RELEASEFX)
    {
      PlayVFX();
      PlaySFX(eCaptureState.RELEASE);
    }
  }
References m_CaptureState, PlaySFX(), and PlayVFX().
PlaySFX()
void PlaySFX (int releaseCase = eCaptureState.CAPTURE) private
Definition at line 237 of file EasterEgg.c.
  {
    if (!GetGame().IsDedicatedServer())
    {
      string soundSet = "";
      if (releaseCase == eCaptureState.CAPTURE)
      {
        PlaySoundSet(m_CaptureSound, "EasterEgg_Catch_SoundSet", 0, 0);
        m_CreatureSoundMap.Find(m_CaptureSoundHash, soundSet);
        PlaySoundSet(m_CreatureSound, soundSet, 0, 0);
      }
      else
      {
        if (!m_DangerSound)
        {
          PlaySoundSet(m_CaptureSound, "EasterEgg_Spawn_SoundSet", 0, 0);
          m_CreatureSoundMap.Find(m_ReleaseSoundHash, soundSet);
          PlaySoundSet(m_CreatureSound, soundSet, 0, 0);
        }
        else
        {
          PlaySoundSet(m_CaptureSound, "EasterEgg_Spawn_Danger_SoundSet", 0, 0);
          m_CreatureSoundMap.Find(m_ReleaseSoundHash, soundSet);
          PlaySoundSet(m_CreatureSound, soundSet, 0, 0);
        }
      }
    }
  }
References GetGame(), m_CaptureSound, m_CaptureSoundHash, m_CreatureSound, m_CreatureSoundMap, m_DangerSound, and m_ReleaseSoundHash.
Referenced by ContactEvent(), and OnVariablesSynchronized().
PlayVFX()
void PlayVFX () private
Definition at line 210 of file EasterEgg.c.
  {
    if (!GetGame().IsDedicatedServer())
    {
      if (!m_ParCapture && m_CaptureState != eCaptureState.STASIS)
      {
        //Ideally play a one time effect such as an explosion
        m_ParCapture = ParticleManager.GetInstance().PlayInWorld(ParticleList.EASTER_EGG_ACTIVATE, GetPosition());
        //Resize, -1 signifies ALL emitors
        m_ParCapture.SetParameter(-1, EmitorParam.SIZE, m_ParScale);
        m_ParCapture.SetWiggle(7, 0.3);
      }
    }
  }
References ParticleList::EASTER_EGG_ACTIVATE, GetGame(), GetPosition, m_CaptureState, m_ParCapture, m_ParScale, ParticleManager(), Particle::SetParameter(), and Particle::SetWiggle().
Referenced by ContactEvent(), and OnVariablesSynchronized().
RegisterSoundSetMap()
void RegisterSoundSetMap () private
Definition at line 287 of file EasterEgg.c.
  {
    //Register all possible creature sounds in map with their respective hash
    string soundSet;
    m_CreatureSoundMap = new map<int, string>;
    //Cow sounds
    soundSet = "CattleMooA_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    soundSet = "CattleBellow_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    //Deer sounds
    soundSet = "DeerRoar_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    soundSet = "DeerBleat_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    //Goat sounds
    soundSet = "GoatBleat_A_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    soundSet = "GoatBleat_B_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    //Hare sounds
    soundSet = "HareChirp_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    soundSet = "HareSquawk_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    //Hen sounds
    soundSet = "HenCluck_X_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    soundSet = "HenScream_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    //Hog sounds
    soundSet = "HogGrunt_G_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    soundSet = "HogSqueal_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    //Sheep sounds
    soundSet = "SheepBleat_G_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    soundSet = "SheepBleat_E_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    //Wolf sounds
    soundSet = "WolfBark_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    soundSet = "WolfWhimper_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    //Zmb F sounds
    soundSet = "ZmbF_Normal_CallToArmsShort_Soundset";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    soundSet = "ZmbF_Normal_HeavyHit_Soundset";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    //Zmb M sounds
    soundSet = "ZmbM_Normal_CallToArmsShort_Soundset";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    soundSet = "ZmbM_Normal_HeavyHit_Soundset";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    //Bear sounds
    soundSet = "BearRoarShort_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
    soundSet = "BearSnarl_SoundSet";
    m_CreatureSoundMap.Insert(soundSet.Hash(), soundSet);
  }
References m_CreatureSoundMap.
Referenced by EasterEgg().
Release()
void Release (vector pos) private
Definition at line 183 of file EasterEgg.c.
  {
    if (GetGame().IsServer())
    {
      m_CaptureState = eCaptureState.RELEASEFX;
      m_CreatureHash = 0;
      SetSynchDirty();
      GetGame().CreateObject(m_CreatureType, pos, false, true);
      m_CreatureType = "";
      DecreaseHealth("", "", GetMaxHealth() * 0.4);
      SetQuantity(GetQuantityMin(), false);
      SetVelocity(this, CAPTURE_VELOCITY);
      if (!IsAlive())
      {
        if (m_ParCapture)
          m_ParCapture.Delete();
        Delete();
      }
    }
  }
References CAPTURE_VELOCITY, GetGame(), GetQuantityMin(), m_CaptureState, m_CreatureHash, m_CreatureType, m_ParCapture, SetQuantity(), and SetVelocity().
Referenced by ContactEvent().
ResizeParticle()
void ResizeParticle (DayZCreatureAI capAnimal) private
Definition at line 226 of file EasterEgg.c.
  {
    //Determine particle scale depending on captured animal scale
    vector mins, maxs;
    capAnimal.GetWorldBounds(mins, maxs);
    m_ParScale = vector.DistanceSq(mins, maxs);
    //Multiply to rescale down as fed values can be really large
    m_ParScale *= PARTICLE_SCALE_MULT;
  }
References vector::DistanceSq(), m_ParScale, and PARTICLE_SCALE_MULT.
Referenced by Capture().
~EasterEgg()
void ~EasterEgg () protected
Definition at line 52 of file EasterEgg.c.
  {
    if (m_ParCapture)
      m_ParCapture.Stop();
  }
References m_ParCapture, and Particle::Stop().
Variable Documentation
CAPTURE_VELOCITY
const vector CAPTURE_VELOCITY = { 0, 0, 0 } private
Definition at line 20 of file EasterEgg.c.
{ 0, 0, 0 };
Referenced by Capture(), and Release().
m_CaptureSound
EffectSound m_CaptureSound protected
Definition at line 28 of file EasterEgg.c.
Referenced by PlaySFX().
m_CaptureSoundHash
int m_CaptureSoundHash protected
Definition at line 33 of file EasterEgg.c.
Referenced by Capture(), OnStoreLoad(), OnStoreSave(), and PlaySFX().
m_CaptureState
int m_CaptureState = eCaptureState.STASIS private
Definition at line 19 of file EasterEgg.c.
Referenced by Capture(), ContactEvent(), OnInventoryExit(), OnStoreLoad(), OnStoreSave(), OnVariablesSynchronized(), PlayVFX(), and Release().
m_CreatureHash
int m_CreatureHash = 0 private
Definition at line 18 of file EasterEgg.c.
Referenced by Capture(), ContactEvent(), and Release().
m_CreatureSound
EffectSound m_CreatureSound protected
Definition at line 29 of file EasterEgg.c.
Referenced by PlaySFX().
m_CreatureSoundMap
ref map<int, string> m_CreatureSoundMap protected
Definition at line 32 of file EasterEgg.c.
Referenced by PlaySFX(), and RegisterSoundSetMap().
m_CreatureType
string m_CreatureType private
Definition at line 17 of file EasterEgg.c.
Referenced by Capture(), EasterEgg(), OnInventoryExit(), OnStoreLoad(), OnStoreSave(), and Release().
m_DangerSound
bool m_DangerSound = false protected
Definition at line 30 of file EasterEgg.c.
Referenced by Capture(), OnStoreLoad(), OnStoreSave(), and PlaySFX().
m_ParCapture
Particle m_ParCapture protected
Definition at line 23 of file EasterEgg.c.
Referenced by Capture(), OnInventoryEnter(), PlayVFX(), Release(), and ~EasterEgg().
m_ParScale
float m_ParScale = 1 private
Definition at line 24 of file EasterEgg.c.
Referenced by OnStoreLoad(), OnStoreSave(), PlayVFX(), and ResizeParticle().
m_ReleaseSoundHash
int m_ReleaseSoundHash protected
Definition at line 34 of file EasterEgg.c.
Referenced by Capture(), OnStoreLoad(), OnStoreSave(), and PlaySFX().
m_StoredCreature
enum eCaptureState m_StoredCreature = null
Referenced by Capture().
PARTICLE_SCALE_MULT
const float PARTICLE_SCALE_MULT = 0.1 private
Definition at line 25 of file EasterEgg.c.
Referenced by ResizeParticle().