DayZ: scripts/3_Game/GUI/Effects/RadialMenu.c File Reference
RadialMenu.c File Reference
Enumerations
enum RadialMenuControlType { MOUSE , CONTROLLER }
Functions
void RadialMenu ()
void ~RadialMenu ()
static RadialMenu GetInstance ()
void OnWidgetScriptInit (Widget w)
void SetControlType (RadialMenuControlType type)
bool IsUsingMouse ()
bool IsUsingController ()
void SetWidgetInitialized (bool state)
bool IsWidgetInitialized ()
void RegisterClass (UIScriptedMenu class_name)
void SetRadiusOffset (float radius_offset)
void SetExecuteDistOffset (float execute_dist_offset)
void SetOffsetFromTop (float offset_from_top)
void SetItemCardRadiusOffset (float item_card_radius_offset)
void ActivateControllerTimeout (bool state)
void SetWidgetProperties (string delimiter_layout)
void Refresh (bool hide_selector=true)
void ShowRadialSelector (Widget selected_item)
void HideRadialSelector ()
int GetItemCardsCount ()
float GetRadius ()
void GetParentCenter (out float center_x, out float center_y)
float GetParentMinSize ()
Widget GetObjectByDegAngle (float deg_angle)
float GetMousePointerAngle ()
float GetMouseDistance ()
float GetAngleInDegrees (float rad_angle)
void Update ()
float NormalizeInvertAngle (float angle)
void UpdataControllerInput ()
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
Variables
enum RadialMenuControlType m_Parent
Widget m_ItemCardsContainer
Widget m_RadialSelector
ImageWidget m_RadialSelectorImage
ImageWidget m_RadialSelectorPointerImage
int m_RadialSelectorOriginalColor
int m_RadialSelectorDisabledColor
Widget m_SelectedObject
ref map< Widget, float > m_RadialItemCards
float m_AngleRadOffset
ref Timer m_UpdateTimer
static const string RADIAL_SELECTOR = "RadialSelector"
static const string RADIAL_SELECTOR_IMAGE = "SelectorImage"
static const string RADIAL_SELECTOR_POINTER = "SelectorPointer"
static const string RADIAL_DELIMITER_CONTAINER = "RadialDelimiterContainer"
static const string RADIAL_ITEM_CARD_CONTAINER = "RadialItemCardContainer"
RadialMenuControlType m_ControlType
UAIDWrapper m_SelectInputWrapper
UAIDWrapper m_BackInputWrapper
float m_ControllerAngle
float m_ControllerTilt
int m_ControllerTimout
bool m_IsControllerTimoutEnabled = true
const float CONTROLLER_DESELECT_TIMEOUT = 1000
const float CONTROLLER_TILT_TRESHOLD_SELECT = 0.8
const float CONTROLLER_TILT_TRESHOLD_EXECUTE = 1.0
bool m_WidgetInitialized
const float MOUSE_SAFE_ZONE_RADIUS = 120
float m_RadiusOffset
float m_ExecuteDistanceOffset
float m_OffsetFromTop
float m_ItemCardRadiusOffset
string m_DelimiterLayout
ref UIScriptedMenu m_RegisteredClass
static ref RadialMenu m_Instance
int last_time = -1
Enumeration Type Documentation
RadialMenuControlType
enum RadialMenuControlType
Enumerator
MOUSE
CONTROLLER
Definition at line 1 of file RadialMenu.c.
{
  MOUSE,
  CONTROLLER
}
Function Documentation
ActivateControllerTimeout()
void ActivateControllerTimeout (bool state) protected
Definition at line 206 of file RadialMenu.c.
  {
    m_IsControllerTimoutEnabled = state;
  }
References m_IsControllerTimoutEnabled.
GetAngleInDegrees()
float GetAngleInDegrees (float rad_angle) protected
Definition at line 476 of file RadialMenu.c.
  {
    float rad_deg = rad_angle * Math.RAD2DEG;
    int angle_mp = rad_deg / 360;
    if (rad_deg < 0)
    {
      rad_deg = rad_deg - (360 * angle_mp);
      rad_deg += 360;
    }
    return rad_deg;
  }
References Math::RAD2DEG.
Referenced by GetObjectByDegAngle(), Refresh(), ShowRadialSelector(), and Update().
GetInstance()
static RadialMenu GetInstance () static protected
Definition at line 113 of file RadialMenu.c.
  {
    return m_Instance;
  }
References m_Instance.
GetItemCardsCount()
int GetItemCardsCount () protected
Definition at line 343 of file RadialMenu.c.
  {
    Widget child = m_ItemCardsContainer.GetChildren();
    int count = 0;
    while (child)
    {
      ++count;
      child = child.GetSibling();
    }
    return count;
  }
References m_ItemCardsContainer.
Referenced by Refresh().
GetMouseDistance()
float GetMouseDistance () protected
Definition at line 460 of file RadialMenu.c.
  {
    int mouse_x;
    int mouse_y;
    GetMousePos(mouse_x, mouse_y);
    float center_x;
    float center_y;
    GetParentCenter(center_x, center_y);
    float distance = vector.Distance(Vector(mouse_x, mouse_y, 0), Vector(center_x, center_y, 0));
    return distance;
  }
References vector::Distance(), GetMousePos(), GetParentCenter(), and Vector().
Referenced by Update().
GetMousePointerAngle()
float GetMousePointerAngle () protected
Definition at line 442 of file RadialMenu.c.
  {
    int mouse_x;
    int mouse_y;
    GetMousePos(mouse_x, mouse_y);
    float center_x;
    float center_y;
    GetParentCenter(center_x, center_y);
    float tan_x = mouse_x - center_x;
    float tan_y = mouse_y - center_y;
    float angle = Math.Atan2(tan_y, tan_x);
    return angle;
  }
References Math::Atan2(), GetMousePos(), and GetParentCenter().
Referenced by Update().
GetObjectByDegAngle()
Widget GetObjectByDegAngle (float deg_angle) protected
Definition at line 405 of file RadialMenu.c.
  {
    for (int i = 0; i < m_RadialItemCards.Count(); ++i)
    {
      Widget w = m_RadialItemCards.GetKey(i);
      float w_angle = GetAngleInDegrees(m_RadialItemCards.Get(w));
      float offset = GetAngleInDegrees(m_AngleRadOffset) / 2;
      float min_angle = w_angle - offset;
      float max_angle = w_angle + offset;
      if (min_angle < 0) min_angle += 360; //clamp 0-360
      if (max_angle > 360) max_angle -= 360;
      if (min_angle > max_angle) //angle radius is in the cycling point 360->
      {
        if (min_angle <= deg_angle) //is cursor position also before this point
        {
          if (deg_angle > max_angle)
            return w;
        }
        else //is cursor position after this point
        {
          if (deg_angle < max_angle)
            return w;
        }
      }
      else
      {
        if (deg_angle >= min_angle && deg_angle < max_angle) //min, max angles are within 0-360 radius
          return w;
      }
    }
    return NULL;
  }
References GetAngleInDegrees(), m_AngleRadOffset, and m_RadialItemCards.
Referenced by Update().
GetParentCenter()
void GetParentCenter (out float center_x, out float center_y) protected
Definition at line 370 of file RadialMenu.c.
  {
    if (m_Parent)
    {
      float wx;
      float wy;
      m_Parent.GetScreenPos(wx, wy);
      float ww;
      float wh;
      m_Parent.GetScreenSize(ww, wh);
      center_x = wx + ww / 2; //center
      center_y = wy + wh / 2;
    }
  }
References m_Parent.
Referenced by GetMouseDistance(), and GetMousePointerAngle().
GetParentMinSize()
float GetParentMinSize () protected
Definition at line 387 of file RadialMenu.c.
  {
    if (m_Parent)
    {
      float size_x;
      float size_y;
      m_Parent.GetScreenSize(size_x, size_y);
      return Math.Min(size_x, size_y);
    }
    return 0;
  }
References m_Parent, and Math::Min().
Referenced by GetRadius().
GetRadius()
float GetRadius () protected
Definition at line 358 of file RadialMenu.c.
  {
    float radius = Math.AbsFloat(GetParentMinSize() * 0.5);
    //PARAM --radius--
    if (m_RadiusOffset > 0)
      return radius * m_RadiusOffset;
    //----------------
    return radius;
  }
References Math::AbsFloat(), GetParentMinSize(), and m_RadiusOffset.
Referenced by Refresh(), and AreaDamageTriggerBase::SetExtents().
HideRadialSelector()
void HideRadialSelector () protected
Definition at line 334 of file RadialMenu.c.
  {
    if (m_RadialSelector)
      m_RadialSelector.Show(false);
  }
References m_RadialSelector.
Referenced by Refresh(), and Update().
IsUsingController()
bool IsUsingController () protected
Definition at line 152 of file RadialMenu.c.
  {
    if (m_ControlType == RadialMenuControlType.CONTROLLER)
      return true;
    return false;
  }
References m_ControlType.
Referenced by Update().
IsUsingMouse()
bool IsUsingMouse () protected
Definition at line 144 of file RadialMenu.c.
  {
    if (m_ControlType == RadialMenuControlType.MOUSE)
      return true;
    return false;
  }
References m_ControlType.
Referenced by Update().
IsWidgetInitialized()
bool IsWidgetInitialized () protected
Definition at line 165 of file RadialMenu.c.
  {
    return m_WidgetInitialized;
  }
References m_WidgetInitialized.
NormalizeInvertAngle()
float NormalizeInvertAngle (float angle) protected
Definition at line 603 of file RadialMenu.c.
  {
    float new_angle = 360 - angle;
    int angle_mp = new_angle / 360;
    new_angle = new_angle - (360 * angle_mp);
    return new_angle;
  }
Referenced by UpdataControllerInput().
OnMouseButtonUp()
override bool OnMouseButtonUp (Widget w, int x, int y, int button) protected
Definition at line 640 of file RadialMenu.c.
  {
    if (button == MouseState.LEFT && m_SelectedObject/* && w == m_SelectedObject*/)
    {
      //Execute
      GetGame().GameScript.CallFunction(m_RegisteredClass, "OnMousePressLeft", NULL, m_SelectedObject);
      return true;
    }
    if (button == MouseState.RIGHT)
    {
      //Back one level
      GetGame().GameScript.CallFunction(m_RegisteredClass, "OnMousePressRight", NULL, NULL);
      return true;
    }
    return false;
  }
References GetGame(), m_RegisteredClass, and m_SelectedObject.
OnWidgetScriptInit()
void OnWidgetScriptInit (Widget w) protected
Definition at line 119 of file RadialMenu.c.
  {
    m_ItemCardsContainer = w.FindAnyWidget(RADIAL_ITEM_CARD_CONTAINER);
    m_RadialSelector = w.FindAnyWidget(RADIAL_SELECTOR);
    m_RadialSelectorImage = ImageWidget.Cast(m_RadialSelector.FindAnyWidget(RADIAL_SELECTOR_IMAGE));
    m_RadialSelectorPointerImage = ImageWidget.Cast(m_RadialSelector.FindAnyWidget(RADIAL_SELECTOR_POINTER));
    m_RadialSelectorOriginalColor = m_RadialSelectorImage.GetColor();
    m_RadialSelectorDisabledColor = ARGB(255, 150, 150, 150);
    //parent
    m_Parent = w;
    m_Parent.SetHandler(this);
  }
References ARGB(), m_ItemCardsContainer, m_Parent, m_RadialSelector, m_RadialSelectorDisabledColor, m_RadialSelectorImage, m_RadialSelectorOriginalColor, m_RadialSelectorPointerImage, RADIAL_ITEM_CARD_CONTAINER, RADIAL_SELECTOR, RADIAL_SELECTOR_IMAGE, and RADIAL_SELECTOR_POINTER.
RadialMenu()
void RadialMenu () protected
Definition at line 84 of file RadialMenu.c.
  {
    m_Instance = this;
    //set default control type
#ifdef PLATFORM_CONSOLE
    Input inp = GetGame().GetInput();
    if (inp && inp.IsEnabledMouseAndKeyboardEvenOnServer())
      m_ControlType = RadialMenuControlType.MOUSE;
    else
      m_ControlType = RadialMenuControlType.CONTROLLER;
#endif
#ifdef PLATFORM_WINDOWS
    m_ControlType = RadialMenuControlType.MOUSE;
#endif
    m_SelectInputWrapper = GetUApi().GetInputByID(UAUISelect).GetPersistentWrapper();
    m_BackInputWrapper = GetUApi().GetInputByID(UAUIBack).GetPersistentWrapper();
    //radial cards
    m_RadialItemCards = new map<Widget, float>;
    m_UpdateTimer = new Timer();
    m_UpdateTimer.Run(0.01, this, "Update", NULL, true);
  }
References GetGame(), GetUApi(), m_BackInputWrapper, m_ControlType, m_Instance, m_RadialItemCards, m_SelectInputWrapper, and m_UpdateTimer.
Referenced by UIScriptedMenu::CreateContent(), UIScriptedMenu::CreateGestureContent(), UIScriptedMenu::Init(), UIScriptedMenu::OnController(), and UIScriptedMenu::OnMouseEnter().
Refresh()
void Refresh (bool hide_selector = true) protected
Definition at line 220 of file RadialMenu.c.
  {
    int item_cards_count = GetItemCardsCount();
    if (item_cards_count > 0)
      m_AngleRadOffset = 2 * Math.PI / item_cards_count;
    float angle_rad = -Math.PI / 2;
    //--PARAM top offset--
    if (m_OffsetFromTop != 0)
      angle_rad = angle_rad + m_OffsetFromTop;
    //--------------------
    //delete all delimiters
    Widget delimiters_panel = m_Parent.FindAnyWidget(RADIAL_DELIMITER_CONTAINER);
    if (delimiters_panel)
    {
      Widget del_child = delimiters_panel.GetChildren();
      while (del_child)
      {
        Widget child_to_destroy1 = del_child;
        del_child = del_child.GetSibling();
        delete child_to_destroy1;
      }
    }
    //Position item cards, crate radial delimiters
    Widget item_cards_panel = m_Parent.FindAnyWidget(RADIAL_ITEM_CARD_CONTAINER);
    Widget item_card = item_cards_panel.GetChildren();
    //get radius
    float original_r = GetRadius();
    float item_cards_r = original_r;
    //--PARAM top offset--....
    if (m_ItemCardRadiusOffset != 0)
    {
      item_cards_r = item_cards_r * m_ItemCardRadiusOffset;
      if (item_cards_r < 0) item_cards_r = 0; //min radius is 0
    }
    m_RadialItemCards.Clear();
    for (int i = 0; i < item_cards_count; ++i)
    {
      //position item cards
      if (item_card)
      {
        //creates circle from simple widget items
        float pos_x = item_cards_r * Math.Cos(angle_rad);
        float pos_y = item_cards_r * Math.Sin(angle_rad);
        pos_x = pos_x / original_r;
        pos_y = pos_y / original_r;
        item_card.SetPos(pos_x, pos_y);
        //store item card
        m_RadialItemCards.Insert(item_card, angle_rad);
        //get next child
        item_card = item_card.GetSibling();
      }
      //-------------------------
      //create delimiter
      if (item_cards_count > 1 && delimiters_panel && m_DelimiterLayout)
      {
        Widget delimiter_widget = GetGame().GetWorkspace().CreateWidgets(m_DelimiterLayout, delimiters_panel);
        float delim_angle_rad = angle_rad + (m_AngleRadOffset / 2);
        delimiter_widget.SetPos(0, 0);
        delimiter_widget.SetRotation(0, 0, GetAngleInDegrees(delim_angle_rad) + 90);
      }
      //calculate next angle
      angle_rad += m_AngleRadOffset;
    }
    //hide selector on refresh
    if (hide_selector)
      HideRadialSelector();
  }
References Math::Cos(), GetAngleInDegrees(), GetGame(), GetItemCardsCount(), GetRadius(), HideRadialSelector(), m_AngleRadOffset, m_DelimiterLayout, m_ItemCardRadiusOffset, m_OffsetFromTop, m_Parent, m_RadialItemCards, Math::PI, RADIAL_DELIMITER_CONTAINER, RADIAL_ITEM_CARD_CONTAINER, and Math::Sin().
RegisterClass()
void RegisterClass (UIScriptedMenu class_name) protected
Definition at line 173 of file RadialMenu.c.
  {
    m_RegisteredClass = class_name;
    if (m_UpdateTimer && !m_UpdateTimer.IsRunning())
      m_UpdateTimer.Run(0.01, this, "Update", NULL, true);
  }
References class_name, m_RegisteredClass, and m_UpdateTimer.
SetControlType()
void SetControlType (RadialMenuControlType type) protected
Definition at line 135 of file RadialMenu.c.
  {
    if (m_ControlType != type)
    {
      m_ControlType = type;
      GetGame().GameScript.CallFunction(m_RegisteredClass, "OnControlsChanged", NULL, type);
    }
  }
References GetGame(), m_ControlType, and m_RegisteredClass.
SetExecuteDistOffset()
void SetExecuteDistOffset (float execute_dist_offset) protected
Definition at line 188 of file RadialMenu.c.
  {
    m_ExecuteDistanceOffset = execute_dist_offset;
  }
References m_ExecuteDistanceOffset.
SetItemCardRadiusOffset()
void SetItemCardRadiusOffset (float item_card_radius_offset) protected
Definition at line 200 of file RadialMenu.c.
  {
    m_ItemCardRadiusOffset = item_card_radius_offset;
  }
References m_ItemCardRadiusOffset.
SetOffsetFromTop()
void SetOffsetFromTop (float offset_from_top) protected
Definition at line 194 of file RadialMenu.c.
  {
    m_OffsetFromTop = offset_from_top;
  }
References m_OffsetFromTop.
SetRadiusOffset()
void SetRadiusOffset (float radius_offset) protected
Definition at line 182 of file RadialMenu.c.
  {
    m_RadiusOffset = radius_offset;
  }
References m_RadiusOffset.
SetWidgetInitialized()
void SetWidgetInitialized (bool state) protected
Definition at line 160 of file RadialMenu.c.
  {
    m_WidgetInitialized = state;
  }
References m_WidgetInitialized.
SetWidgetProperties()
void SetWidgetProperties (string delimiter_layout) protected
Definition at line 211 of file RadialMenu.c.
  {
    m_DelimiterLayout = delimiter_layout;
  }
References m_DelimiterLayout.
ShowRadialSelector()
void ShowRadialSelector (Widget selected_item) protected
Definition at line 303 of file RadialMenu.c.
  {
    if (m_RadialSelector && selected_item)
    {
      int item_count = m_RadialItemCards.Count();
      if (item_count > 1)
      {
        int angle_deg = GetAngleInDegrees(m_RadialItemCards.Get(selected_item));
        m_RadialSelector.SetRotation(0, 0, angle_deg + 90); //rotate widget according to its desired rotation
        //set radial selector size
        float progress = (1 / item_count) * 2;
        m_RadialSelectorImage.SetMaskProgress(progress);
        m_RadialSelector.Show(true);
        bool grey_selector = selected_item.GetFlags() & WidgetFlags.DISABLED;
        if (!grey_selector)
        {
          m_RadialSelectorImage.SetColor(m_RadialSelectorDisabledColor);
          m_RadialSelectorPointerImage.SetColor(m_RadialSelectorDisabledColor);
        }
        else
        {
          m_RadialSelectorImage.SetColor(m_RadialSelectorOriginalColor);
          m_RadialSelectorPointerImage.SetColor(m_RadialSelectorOriginalColor);
        }
      }
    }
  }
References GetAngleInDegrees(), m_RadialItemCards, m_RadialSelector, m_RadialSelectorDisabledColor, m_RadialSelectorImage, m_RadialSelectorOriginalColor, and m_RadialSelectorPointerImage.
Referenced by Update().
UpdataControllerInput()
void UpdataControllerInput () protected
Definition at line 616 of file RadialMenu.c.
  {
    Input input = GetGame().GetInput();
    //Controller radial
    float angle;
    float tilt;
    input.GetGamepadThumbDirection(GamepadButton.THUMB_RIGHT, angle, tilt);
    angle = NormalizeInvertAngle(angle * Math.RAD2DEG);
    m_ControllerAngle = angle;
    m_ControllerTilt = tilt;
    m_ControllerTimout = 0; //reset controller timeout
    //Controller buttons
    //Select (A,cross)
    if (m_SelectInputWrapper.InputP().LocalPress())
      GetGame().GameScript.CallFunction(m_RegisteredClass, "OnControllerPressSelect", NULL, m_SelectedObject);
    //Back (B,circle)
    if (m_BackInputWrapper.InputP().LocalPress())
      GetGame().GameScript.CallFunction(m_RegisteredClass, "OnControllerPressBack", NULL, m_SelectedObject);
  }
References GetGame(), UAIDWrapper::InputP(), m_BackInputWrapper, m_ControllerAngle, m_ControllerTilt, m_ControllerTimout, m_RegisteredClass, m_SelectedObject, m_SelectInputWrapper, NormalizeInvertAngle(), and Math::RAD2DEG.
Referenced by Update().
~RadialMenu()
void ~RadialMenu () protected
Definition at line 109 of file RadialMenu.c.
  {
  }
Variable Documentation
CONTROLLER_DESELECT_TIMEOUT
const float CONTROLLER_DESELECT_TIMEOUT = 1000 protected
Definition at line 39 of file RadialMenu.c.
Referenced by Update().
CONTROLLER_TILT_TRESHOLD_EXECUTE
const float CONTROLLER_TILT_TRESHOLD_EXECUTE = 1.0 protected
Definition at line 41 of file RadialMenu.c.
CONTROLLER_TILT_TRESHOLD_SELECT
const float CONTROLLER_TILT_TRESHOLD_SELECT = 0.8 protected
Definition at line 40 of file RadialMenu.c.
Referenced by Update().
last_time
int last_time = -1 protected
Definition at line 495 of file RadialMenu.c.
Referenced by Update().
m_AngleRadOffset
float m_AngleRadOffset protected
Definition at line 19 of file RadialMenu.c.
Referenced by GetObjectByDegAngle(), and Refresh().
m_BackInputWrapper
UAIDWrapper m_BackInputWrapper private
Definition at line 32 of file RadialMenu.c.
Referenced by UIScriptedMenu::Init(), RadialMenu(), UpdataControllerInput(), and UIScriptedMenu::Update().
m_ControllerAngle
float m_ControllerAngle protected
Definition at line 33 of file RadialMenu.c.
Referenced by Controller(), UpdataControllerInput(), and Update().
m_ControllerTilt
float m_ControllerTilt protected
Definition at line 34 of file RadialMenu.c.
Referenced by Controller(), UpdataControllerInput(), and Update().
m_ControllerTimout
int m_ControllerTimout protected
Definition at line 37 of file RadialMenu.c.
Referenced by UpdataControllerInput(), and Update().
m_ControlType
RadialMenuControlType m_ControlType protected
Definition at line 30 of file RadialMenu.c.
Referenced by IsUsingController(), IsUsingMouse(), RadialMenu(), and SetControlType().
m_DelimiterLayout
string m_DelimiterLayout protected
Definition at line 52 of file RadialMenu.c.
Referenced by Refresh(), and SetWidgetProperties().
m_ExecuteDistanceOffset
float m_ExecuteDistanceOffset protected
Definition at line 49 of file RadialMenu.c.
Referenced by SetExecuteDistOffset().
m_Instance
ref RadialMenu m_Instance static protected
Definition at line 55 of file RadialMenu.c.
Referenced by UIScriptedMenu::CameraToolsMenu(), GetInstance(), PluginBase::GetInstance(), GetInstance(), array::GetTestEx(), Inventory(), MoveAttachmentDown(), MoveAttachmentUp(), PluginBase::OnInit(), UIScriptedMenu::PlayAnimOnActor(), RadialMenu(), array::Run(), and array::TFCaller().
m_IsControllerTimoutEnabled
bool m_IsControllerTimoutEnabled = true protected
Definition at line 38 of file RadialMenu.c.
Referenced by ActivateControllerTimeout(), and Update().
m_ItemCardRadiusOffset
float m_ItemCardRadiusOffset protected
Definition at line 51 of file RadialMenu.c.
Referenced by Refresh(), and SetItemCardRadiusOffset().
m_ItemCardsContainer
Widget m_ItemCardsContainer protected
Definition at line 10 of file RadialMenu.c.
Referenced by GetItemCardsCount(), and OnWidgetScriptInit().
m_OffsetFromTop
float m_OffsetFromTop protected
Definition at line 50 of file RadialMenu.c.
Referenced by Refresh(), and SetOffsetFromTop().
m_Parent
enum RadialMenuControlType m_Parent
m_RadialItemCards
ref map<Widget, float> m_RadialItemCards protected
Definition at line 17 of file RadialMenu.c.
Referenced by GetObjectByDegAngle(), RadialMenu(), Refresh(), and ShowRadialSelector().
m_RadialSelector
Widget m_RadialSelector protected
Definition at line 11 of file RadialMenu.c.
Referenced by HideRadialSelector(), OnWidgetScriptInit(), and ShowRadialSelector().
m_RadialSelectorDisabledColor
int m_RadialSelectorDisabledColor protected
Definition at line 15 of file RadialMenu.c.
Referenced by OnWidgetScriptInit(), and ShowRadialSelector().
m_RadialSelectorImage
ImageWidget m_RadialSelectorImage protected
Definition at line 12 of file RadialMenu.c.
Referenced by OnWidgetScriptInit(), and ShowRadialSelector().
m_RadialSelectorOriginalColor
int m_RadialSelectorOriginalColor protected
Definition at line 14 of file RadialMenu.c.
Referenced by OnWidgetScriptInit(), and ShowRadialSelector().
m_RadialSelectorPointerImage
ImageWidget m_RadialSelectorPointerImage protected
Definition at line 13 of file RadialMenu.c.
Referenced by OnWidgetScriptInit(), and ShowRadialSelector().
m_RadiusOffset
float m_RadiusOffset protected
Definition at line 48 of file RadialMenu.c.
Referenced by GetRadius(), and SetRadiusOffset().
m_RegisteredClass
ref UIScriptedMenu m_RegisteredClass protected
Definition at line 54 of file RadialMenu.c.
Referenced by OnMouseButtonUp(), RegisterClass(), SetControlType(), UpdataControllerInput(), and Update().
m_SelectedObject
Widget m_SelectedObject protected
Definition at line 16 of file RadialMenu.c.
Referenced by PluginBase::DeselectObject(), PluginBase::GetSelectedSceneObject(), UIScriptedMenu::OnClick(), UIScriptedMenu::OnDoubleClick(), UIScriptedMenu::OnItemSelected(), OnMouseButtonUp(), PluginBase::SelectObject(), UpdataControllerInput(), and Update().
m_SelectInputWrapper
UAIDWrapper m_SelectInputWrapper private
Definition at line 31 of file RadialMenu.c.
Referenced by RadialMenu(), and UpdataControllerInput().
m_UpdateTimer
ref Timer m_UpdateTimer protected
Definition at line 20 of file RadialMenu.c.
Referenced by PluginBase::EnableUpdate(), PluginBase::OnInit(), TrapBase::OnServerSteppedOn(), OnServerSteppedOn(), TrapBase::OnSteppedOn(), OnSteppedOn(), OnSteppedOut(), TrapBase::OnSteppedOut(), PlayerSoundEventHandler(), RadialMenu(), RegisterClass(), TrapBase(), and Update().
m_WidgetInitialized
bool m_WidgetInitialized protected
Definition at line 44 of file RadialMenu.c.
Referenced by IsWidgetInitialized(), SetWidgetInitialized(), and Update().
MOUSE_SAFE_ZONE_RADIUS
const float MOUSE_SAFE_ZONE_RADIUS = 120 protected
Definition at line 45 of file RadialMenu.c.
Referenced by Update().
RADIAL_DELIMITER_CONTAINER
const string RADIAL_DELIMITER_CONTAINER = "RadialDelimiterContainer" static protected
Definition at line 26 of file RadialMenu.c.
Referenced by Refresh().
RADIAL_ITEM_CARD_CONTAINER
const string RADIAL_ITEM_CARD_CONTAINER = "RadialItemCardContainer" static protected
Definition at line 27 of file RadialMenu.c.
Referenced by OnWidgetScriptInit(), and Refresh().
RADIAL_SELECTOR
const string RADIAL_SELECTOR = "RadialSelector" static protected
Definition at line 23 of file RadialMenu.c.
Referenced by OnWidgetScriptInit().
RADIAL_SELECTOR_IMAGE
const string RADIAL_SELECTOR_IMAGE = "SelectorImage" static protected
Definition at line 24 of file RadialMenu.c.
Referenced by OnWidgetScriptInit().
RADIAL_SELECTOR_POINTER
const string RADIAL_SELECTOR_POINTER = "SelectorPointer" static protected
Definition at line 25 of file RadialMenu.c.
Referenced by OnWidgetScriptInit().