DayZ: PMTF Class Reference
PMTF Class Reference
Protected Member Functions
void PrintPMStats (notnull ParticleManager pm)
void PrintActiveStats ()
ParticleManager CreatePMFixedBlocking (int size)
Private Member Functions
int InsertManager (ParticleManager pm)
bool GetManager (int id, out ParticleManager pm)
Private Attributes
ref map< int, ref ParticleManager > m_Managers = new map<int, ref ParticleManager>()
Static Private Attributes
static int PM_CREATED = 0
Detailed Description
Definition at line 1 of file PMTF.c.
Member Function Documentation
CreatePMFixedBlocking()
ParticleManager PMTF::CreatePMFixedBlocking (int size) inline protected
Definition at line 42 of file PMTF.c.
  {
    return new ParticleManager(new ParticleManagerSettings(size, ParticleManagerSettingsFlags.BLOCKING));
  }
References ParticleManager(), and ParticleManagerSettings().
Referenced by TestCreationSmallBlocking(), PMTPlayback::TestOnePlaying(), and TestOwnership().
GetManager()
bool PMTF::GetManager (int id, out ParticleManager pm) inline private
Definition at line 17 of file PMTF.c.
  {
    return m_Managers.Find(id, pm);
  }
References m_Managers.
Referenced by PMTPlayback::CheckOnePlaying(), and CheckTestEvents().
InsertManager()
int PMTF::InsertManager (ParticleManager pm) inline private
Definition at line 9 of file PMTF.c.
  {
    Assert(m_Managers.Insert(PM_CREATED, pm));
    ++PM_CREATED;
    return PM_CREATED - 1;
  }
References Assert(), m_Managers, and PM_CREATED.
Referenced by TestEvents(), PMTPlayback::TestOnePlaying(), and TestOwnership().
PrintActiveStats()
void PMTF::PrintActiveStats () inline protected
Definition at line 32 of file PMTF.c.
  {
    Debug.ParticleLog(string.Format(
                        "Active ParticleManagers: %1 | Active ParticleSources: %2", ParticleManager.GetStaticActiveCount(), ParticleSource.GetStaticActiveCount()),
                      this, "PrintActiveStats");
  }
References ParticleSource::GetStaticActiveCount(), Debug::ParticleLog(), and ParticleManager().
Referenced by TestCleanup().
PrintPMStats()
void PMTF::PrintPMStats (notnull ParticleManager pm) inline protected
Definition at line 25 of file PMTF.c.
  {
    Debug.ParticleLog(string.Format(
                        "Poolsize: %1 | Allocated: %2 | Virtual: %3 | Playing: %4", pm.GetPoolSize(), pm.GetAllocatedCount(), pm.GetVirtualCount(), pm.GetPlayingCount()),
                      this, "PrintPMStats", pm);
  }
References Debug::ParticleLog().
Referenced by TestCreationSmallBlocking().
Member Data Documentation
m_Managers
ref map<int, ref ParticleManager> PMTF::m_Managers = new map<int, ref ParticleManager>() private
Definition at line 4 of file PMTF.c.
Referenced by GetManager(), and InsertManager().
PM_CREATED
int PMTF::PM_CREATED = 0 static private
Definition at line 3 of file PMTF.c.
Referenced by InsertManager().
The documentation for this class was generated from the following file:
scripts/3_Game/Particles/Tests/PMTF.c