DayZ: LayoutHolder Class Reference
LayoutHolder Class Reference
Protected Member Functions
void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
void DraggingOver (Widget w, int x, int y, Widget receiver)
void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
void UpdateSpacer ()
Header GetHeader ()
void SetHeader (Header header)
void CheckHeaderDragability ()
void Container (LayoutHolder parent)
Container GetFocusedContainer ()
Container GetContainer (int index)
void SetFocusedContainer (Container cont)
SlotsIcon GetFocusedSlotsIcon ()
int GetActiveIndex ()
void SetActiveIndex (int index)
ScrollWidget GetScrollWidget ()
void UpdateRadialIcon ()
void SetSlotIcon (SlotsIcon icon)
void SetDefaultFocus (bool while_micromanagment_mode=false)
void SetLastFocus ()
void Unfocus ()
void MoveGridCursor (int direction)
void ScrollToActiveContainer ()
void CheckScrollbarVisibility ()
void Open ()
void Close ()
bool IsOpened ()
void SetOpenForSlotIcon (bool open, SlotsIcon icon=null)
void Toggle ()
float GetFocusedContainerHeight (bool contents=false)
float GetFocusedContainerYPos (bool contents=false)
float GetFocusedContainerYScreenPos (bool contents=false)
int Count ()
bool SelectItem ()
bool Select ()
bool OnSelectButton ()
bool Combine ()
bool TransferItemToVicinity ()
bool TransferItem ()
bool InspectItem ()
bool SplitItem ()
bool EquipItem ()
bool CanOpenCloseContainer ()
bool CanOpenCloseContainerEx (EntityAI focusedEntity)
bool CanSplit ()
bool CanSplitEx (EntityAI focusedEntity)
bool CanDrop ()
bool CanDropEx (EntityAI focusedEntity)
bool CanSwapOrTakeToHands ()
bool CanSwapOrTakeToHandsEx (EntityAI focusedEntity)
bool CanEquip ()
bool CanEquipEx (EntityAI focusedEntity)
bool CanTakeToInventory ()
bool CanTakeToInventoryEx (EntityAI focusedEntity)
bool CanCombine ()
bool CanCombineEx (EntityAI focusedEntity)
bool CanCombineAmmo ()
bool CanAddToQuickbarEx (EntityAI focusedEntity)
bool AddItemToQuickbarRadial (EntityAI itemToAssign)
bool IsEmpty ()
bool IsItemActive ()
bool IsItemWithQuantityActive ()
EntityAI GetFocusedItem ()
EntityAI GetFocusedContainerEntity ()
int GetColumnCount ()
void SetColumnCount (int count)
int GetFocusedColumn ()
void SetFocusedColumn (int column)
override void UpdateInterval ()
override void SetLastActive ()
override void SetFirstActive ()
override void SetActive (bool active)
void UnfocusAll ()
void UnfocusGrid ()
bool IsLastIndex ()
bool IsFirstIndex ()
bool IsFirstContainerFocused ()
bool IsLastContainerFocused ()
void ResetFocusedContainer ()
void SetNextActive ()
void SetPreviousActive (bool force=false)
void SetNextRightActive ()
void SetNextLeftActive ()
void SetSameLevelNextActive ()
void SetSameLevelPreviousActive ()
void RecomputeOpenedContainers ()
override void SetLayoutName ()
void Insert (LayoutHolder container, int pos=-1, bool immedUpdate=true)
void Remove (LayoutHolder container)
LayoutHolder Get (int x)
override void Refresh ()
void UpdateBodySpacers ()
void HideContent (bool force_hide=false)
void ShowContent (bool force_show=false)
void SetForceShow (bool value)
override void UpdateSelectionIcons ()
void ExpandCollapseContainer ()
Protected Attributes
ref array< ref LayoutHolder > m_Body
ref array< LayoutHolder > m_OpenedContainers
int m_ActiveIndex = 0
bool m_LastIndex
bool m_Closed
Container m_FocusedContainer
float m_PrevAlpha
const int ITEMS_IN_ROW = 8
int m_ColumnCount
int m_FocusedColumn = 0
bool m_ForcedHide
bool m_ForcedShow
SlotsIcon m_SlotIcon
EntityAI m_Entity
const int SORT_ATTACHMENTS_OWN = 1
const int SORT_CARGO_OWN = 2
const int SORT_ATTACHMENTS_NEXT_OFFSET = 2
const int SORT_CARGO_NEXT_OFFSET = 3
Detailed Description
Definition at line 1 of file Container.c.
Member Function Documentation
AddItemToQuickbarRadial()
bool LayoutHolder::AddItemToQuickbarRadial (EntityAI itemToAssign) inline protected
Definition at line 577 of file Container.c.
  {
    if (CanAddToQuickbarEx(itemToAssign))
    {
      PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
      DayZPlayerInventory dpi;
      dpi = player.GetDayZPlayerInventory();
      if (itemToAssign && dpi && !dpi.IsProcessing())
      {
        RadialQuickbarMenu.SetItemToAssign(itemToAssign);
        //open radial quickbar menu
        if (!GetGame().GetUIManager().IsMenuOpen(MENU_RADIAL_QUICKBAR))
          RadialQuickbarMenu.OpenMenu(GetGame().GetUIManager().FindMenu(MENU_INVENTORY));
      }
      return true;
    }
    return false;
  }
References GetGame(), GetPlayer(), MENU_INVENTORY, and MENU_RADIAL_QUICKBAR.
CanAddToQuickbarEx()
bool LayoutHolder::CanAddToQuickbarEx (EntityAI focusedEntity) inline protected
Definition at line 562 of file Container.c.
  {
    if (ItemManager.GetInstance().IsMicromanagmentMode())
      return false;
    if (focusedEntity)
    {
      PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
      if (focusedEntity.GetHierarchyRootPlayer() == player)
        return true;
    }
    return false;
  }
References GetGame(), ItemManager::GetInstance(), and GetPlayer().
CanCombine()
bool LayoutHolder::CanCombine () inline protected
Definition at line 527 of file Container.c.
  {
    EntityAI focusedEntity = GetFocusedItem();
    if (focusedEntity)
    {
      if (GetFocusedContainer())
        return GetFocusedContainer().CanCombineEx(focusedEntity);
      return CanCombineEx(focusedEntity);
    }
    return false;
  }
References Container::GetFocusedItem().
CanCombineAmmo()
bool LayoutHolder::CanCombineAmmo () inline protected
Definition at line 555 of file Container.c.
  {
    if (GetFocusedContainer())
      return GetFocusedContainer().CanCombineAmmo();
    return false;
  }
CanCombineEx()
bool LayoutHolder::CanCombineEx (EntityAI focusedEntity) inline protected
Definition at line 541 of file Container.c.
  {
    if (ItemManager.GetInstance().IsMicromanagmentMode())
      return false;
    if (focusedEntity)
    {
      EntityAI entityInHands = PlayerBase.Cast(GetGame().GetPlayer()).GetItemInHands();
      if (focusedEntity != entityInHands)
        return (ItemManager.GetCombinationFlags(entityInHands, focusedEntity) != 0);
    }
    return false;
  }
References ItemManager::GetCombinationFlags(), GetGame(), ItemManager::GetInstance(), and GetPlayer().
CanDrop()
bool LayoutHolder::CanDrop () inline protected
Definition at line 388 of file Container.c.
  {
    EntityAI focusedEntity = GetFocusedItem();
    if (focusedEntity)
    {
      if (GetFocusedContainer())
        return GetFocusedContainer().CanDropEx(focusedEntity);
      return CanDropEx(focusedEntity);
    }
    return false;
  }
References Container::GetFocusedItem().
CanDropEx()
bool LayoutHolder::CanDropEx (EntityAI focusedEntity) inline protected
Definition at line 403 of file Container.c.
  {
    if (ItemManager.GetInstance().IsMicromanagmentMode())
      return false;
    if (focusedEntity)
    {
      PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
      if (player)
        return player.CanDropEntity(focusedEntity);
    }
    return false;
  }
References GetGame(), ItemManager::GetInstance(), and GetPlayer().
CanEquip()
bool LayoutHolder::CanEquip () inline protected
Definition at line 456 of file Container.c.
  {
    EntityAI focusedEntity = GetFocusedItem();
    if (focusedEntity)
    {
      if (GetFocusedContainer())
        return GetFocusedContainer().CanEquipEx(focusedEntity);
      return CanEquipEx(focusedEntity);
    }
    return false;
  }
References Container::GetFocusedItem().
CanEquipEx()
bool LayoutHolder::CanEquipEx (EntityAI focusedEntity) inline protected
Definition at line 470 of file Container.c.
  {
    if (ItemManager.GetInstance().IsMicromanagmentMode())
      return false;
    bool found = false;
    if (focusedEntity)
    {
      InventoryLocation il = new InventoryLocation;
      PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
      found = player.GetInventory().FindFreeLocationFor(focusedEntity, FindInventoryLocationType.ATTACHMENT, il);
      if (!found)
      {
        for (int i = 0; i < focusedEntity.GetInventory().GetSlotIdCount(); i++)
        {
          int slot_id = focusedEntity.GetInventory().GetSlotId(i);
          EntityAI slot_item = player.GetInventory().FindAttachment(slot_id);
          if (slot_item && player.GetInventory().CanSwapEntitiesEx(focusedEntity, slot_item))
          {
            found = true;
            break;
          }
        }
      }
    }
    return found;
  }
References GetGame(), ItemManager::GetInstance(), and GetPlayer().
CanOpenCloseContainer()
bool LayoutHolder::CanOpenCloseContainer () inline protected
Definition at line 342 of file Container.c.
  {
    if (ItemManager.GetInstance().IsMicromanagmentMode())
      return false;
    EntityAI focusedEntity = GetFocusedItem();
    if (focusedEntity)
    {
      if (GetFocusedContainer())
        return GetFocusedContainer().CanOpenCloseContainerEx(focusedEntity);
      return CanOpenCloseContainerEx(focusedEntity);
    }
    return false;
  }
References Container::GetFocusedItem(), and ItemManager::GetInstance().
CanOpenCloseContainerEx()
bool LayoutHolder::CanOpenCloseContainerEx (EntityAI focusedEntity) inline protected
Definition at line 359 of file Container.c.
  {
    return false;
  }
CanSplit()
bool LayoutHolder::CanSplit () inline protected
Definition at line 364 of file Container.c.
  {
    EntityAI focusedEntity = GetFocusedItem();
    if (focusedEntity)
    {
      if (GetFocusedContainer())
        return GetFocusedContainer().CanSplitEx(focusedEntity);
      return CanSplitEx(focusedEntity);
    }
    return false;
  }
References Container::GetFocusedItem().
CanSplitEx()
bool LayoutHolder::CanSplitEx (EntityAI focusedEntity) inline protected
Definition at line 378 of file Container.c.
  {
    if (ItemManager.GetInstance().IsMicromanagmentMode())
      return false;
    if (focusedEntity)
      return focusedEntity.CanBeSplit();
    return false;
  }
References ItemManager::GetInstance().
CanSwapOrTakeToHands()
bool LayoutHolder::CanSwapOrTakeToHands () inline protected
Definition at line 418 of file Container.c.
  {
    EntityAI focusedEntity = GetFocusedItem();
    if (focusedEntity)
    {
      if (GetFocusedContainer())
        return GetFocusedContainer().CanSwapOrTakeToHandsEx(focusedEntity);
      return CanSwapOrTakeToHandsEx(focusedEntity);
    }
    return false;
  }
References Container::GetFocusedItem().
CanSwapOrTakeToHandsEx()
bool LayoutHolder::CanSwapOrTakeToHandsEx (EntityAI focusedEntity) inline protected
Definition at line 432 of file Container.c.
  {
    if (ItemManager.GetInstance().IsMicromanagmentMode())
      return false;
    if (focusedEntity)
    {
      PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
      EntityAI entityInHands = player.GetItemInHands();
      if (entityInHands)
      {
        InventoryLocation il = new InventoryLocation();
        if (!GameInventory.CanSwapEntitiesEx(focusedEntity, entityInHands))
          return GameInventory.CanForceSwapEntitiesEx(focusedEntity, null, entityInHands, il);
        else
          return true;
      }
      else
        return player.GetInventory().CanAddEntityIntoHands(focusedEntity);
    }
    return false;
  }
References GameInventory::CanForceSwapEntitiesEx(), GameInventory::CanSwapEntitiesEx(), GetGame(), ItemManager::GetInstance(), and GetPlayer().
CanTakeToInventory()
bool LayoutHolder::CanTakeToInventory () inline protected
Definition at line 500 of file Container.c.
  {
    EntityAI focusedEntity = GetFocusedItem();
    if (focusedEntity)
    {
      if (GetFocusedContainer())
        return GetFocusedContainer().CanTakeToInventoryEx(focusedEntity);
      return CanTakeToInventoryEx(focusedEntity);
    }
    return false;
  }
References Container::GetFocusedItem().
CanTakeToInventoryEx()
bool LayoutHolder::CanTakeToInventoryEx (EntityAI focusedEntity) inline protected
Definition at line 514 of file Container.c.
  {
    if (ItemManager.GetInstance().IsMicromanagmentMode())
      return false;
    if (focusedEntity)
    {
      PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
      return player.GetInventory().CanAddEntityToInventory(focusedEntity, FindInventoryLocationType.CARGO);
    }
    return false;
  }
References GetGame(), ItemManager::GetInstance(), and GetPlayer().
CheckHeaderDragability()
void LayoutHolder::CheckHeaderDragability () protected
CheckScrollbarVisibility()
void LayoutHolder::CheckScrollbarVisibility () inline protected
Definition at line 166 of file Container.c.
  {
    ScrollWidget sw = GetScrollWidget();
    if (sw)
    {
      if (!sw.IsScrollbarVisible())
        sw.VScrollToPos01(0.0);
      else if (sw.GetVScrollPos01() > 1.0)
        sw.VScrollToPos01(1.0);
    }
  }
Close()
void LayoutHolder::Close () inline protected
Definition at line 184 of file Container.c.
  {
    m_Closed = true;
    UpdateSelectionIcons();
  }
Combine()
bool LayoutHolder::Combine () inline protected
Definition at line 300 of file Container.c.
  {
    if (GetFocusedContainer())
      return GetFocusedContainer().Combine();
    return true;
  }
Container()
void LayoutHolder::Container (LayoutHolder parent) inline protected
Definition at line 35 of file Container.c.
  {
    m_Body = new array<ref LayoutHolder>;
    m_OpenedContainers = new array<LayoutHolder>;
    m_PrevAlpha = m_RootWidget.GetAlpha();
    m_SlotIcon = null;
    m_ForcedHide = false;
    m_ForcedShow = false;
    m_ActiveIndex = 0;
    m_IsActive = false;
  }
References m_IsActive, and m_RootWidget.
Count()
int LayoutHolder::Count () inline protected
Definition at line 274 of file Container.c.
  {
    return m_Body.Count();
  }
Referenced by PluginBase::Broadcast(), PluginBase::BroadcastFloat(), PluginBase::BroadcastInt(), PluginBase::BroadcastParam(), PluginBase::BroadcastString(), and Container::Get().
DraggingOver()
void LayoutHolder::DraggingOver (Widget w, int x, int y, Widget receiver) protected
DraggingOverHeader()
void LayoutHolder::DraggingOverHeader (Widget w, int x, int y, Widget receiver) protected
EquipItem()
bool LayoutHolder::EquipItem () inline protected
Definition at line 335 of file Container.c.
  {
    if (GetFocusedContainer())
      return GetFocusedContainer().EquipItem();
    return false;
  }
ExpandCollapseContainer()
void LayoutHolder::ExpandCollapseContainer () inline protected
Definition at line 1076 of file Container.c.
{}
Get()
LayoutHolder LayoutHolder::Get (int x) inline protected
Definition at line 1014 of file Container.c.
  {
    return m_Body.Get(x);
  }
References x.
Referenced by PluginBase::Broadcast(), PluginBase::BroadcastFloat(), PluginBase::BroadcastInt(), PluginBase::BroadcastParam(), and PluginBase::BroadcastString().
GetActiveIndex()
int LayoutHolder::GetActiveIndex () inline protected
Definition at line 76 of file Container.c.
  {
    return m_ActiveIndex;
  }
GetColumnCount()
int LayoutHolder::GetColumnCount () inline protected
Definition at line 634 of file Container.c.
  {
    return m_ColumnCount;
  }
GetContainer()
Container LayoutHolder::GetContainer (int index) inline protected
Definition at line 55 of file Container.c.
  {
    if (index < m_Body.Count())
      return Container.Cast(m_Body[index]);
    return null;
  }
GetFocusedColumn()
int LayoutHolder::GetFocusedColumn () inline protected
Definition at line 644 of file Container.c.
  {
    return m_FocusedColumn;
  }
GetFocusedContainer()
Container LayoutHolder::GetFocusedContainer () inline protected
Definition at line 48 of file Container.c.
  {
    if (m_ActiveIndex < m_OpenedContainers.Count())
      return Container.Cast(m_OpenedContainers[m_ActiveIndex]);
    return null;
  }
GetFocusedContainerEntity()
EntityAI LayoutHolder::GetFocusedContainerEntity () inline protected
Definition at line 626 of file Container.c.
  {
    EntityAI item;
    if (GetFocusedContainer())
      item = GetFocusedContainer().GetFocusedContainerEntity();
    return item;
  }
GetFocusedContainerHeight()
float LayoutHolder::GetFocusedContainerHeight (bool contents = false) inline protected
Definition at line 220 of file Container.c.
  {
    float x, y, result;
    if (GetFocusedContainer())
      y = GetFocusedContainer().GetFocusedContainerHeight(contents);
    else if (GetRootWidget())
      GetRootWidget().GetScreenSize(x, y);
    result = y;
    if (m_ActiveIndex == 0)
    {
      if (GetHeader())
      {
        GetHeader().GetRootWidget().GetScreenSize(x, y);
        result += y;
      }
    }
    return result;
  }
References GetFocusedContainerHeight(), Container::GetHeader(), x, and y.
Referenced by Container::GetFocusedContainerHeight(), and GetFocusedContainerHeight().
GetFocusedContainerYPos()
float LayoutHolder::GetFocusedContainerYPos (bool contents = false) inline protected
Definition at line 241 of file Container.c.
  {
    float x, y;
    if (GetFocusedContainer())
      y = GetFocusedContainer().GetFocusedContainerYPos(contents);
    else if (GetRootWidget())
      GetRootWidget().GetPos(x, y);
    return y;
  }
References GetFocusedContainerYPos(), x, and y.
Referenced by Container::GetFocusedContainerYPos(), and GetFocusedContainerYPos().
GetFocusedContainerYScreenPos()
float LayoutHolder::GetFocusedContainerYScreenPos (bool contents = false) inline protected
Definition at line 252 of file Container.c.
  {
    float x, y, result;
    if (GetFocusedContainer())
      y = GetFocusedContainer().GetFocusedContainerYScreenPos(contents);
    else if (GetRootWidget())
      GetRootWidget().GetScreenPos(x, y);
    result = y;
    if (m_ActiveIndex == 0)
    {
      if (GetHeader())
      {
        GetHeader().GetRootWidget().GetScreenPos(x, y);
        result = y;
      }
    }
    return result;
  }
References GetFocusedContainerYScreenPos(), Container::GetHeader(), x, and y.
Referenced by Container::GetFocusedContainerYScreenPos(), and GetFocusedContainerYScreenPos().
GetFocusedItem()
EntityAI LayoutHolder::GetFocusedItem () inline protected
Definition at line 617 of file Container.c.
  {
    EntityAI item;
    if (GetFocusedContainer())
      item = GetFocusedContainer().GetFocusedItem();
    return item;
  }
GetFocusedSlotsIcon()
SlotsIcon LayoutHolder::GetFocusedSlotsIcon () inline protected
Definition at line 68 of file Container.c.
  {
    Container c = GetFocusedContainer();
    if (c)
      return c.GetFocusedSlotsIcon();
    return null;
  }
GetHeader()
Header LayoutHolder::GetHeader () protected
GetScrollWidget()
ScrollWidget LayoutHolder::GetScrollWidget () inline protected
Definition at line 86 of file Container.c.
  {
    return null;
  }
HideContent()
void LayoutHolder::HideContent (bool force_hide = false) inline protected
Definition at line 1040 of file Container.c.
  {
    if (!m_ForcedHide)
      m_ForcedHide = force_hide;
    for (int i = 0; i < m_Body.Count(); i++)
    {
      if (m_Body.Get(i))
        m_Body.Get(i).OnHide();
    }
  }
Insert()
void LayoutHolder::Insert (LayoutHolder container, int pos = -1, bool immedUpdate = true) inline protected
Definition at line 973 of file Container.c.
  {
    if (pos > -1 && pos < m_Body.Count())
    {
      if (pos <= m_ActiveIndex)
        m_ActiveIndex++;
      m_Body.InsertAt(container, pos);
    }
    else
      m_Body.Insert(container);
    if (immedUpdate)
      Refresh();
  }
References Container::Refresh().
InspectItem()
bool LayoutHolder::InspectItem () inline protected
Definition at line 321 of file Container.c.
  {
    if (GetFocusedContainer())
      return GetFocusedContainer().InspectItem();
    return false;
  }
Referenced by Icon::MouseClick().
IsEmpty()
bool LayoutHolder::IsEmpty () inline protected
Definition at line 598 of file Container.c.
  {
    return m_OpenedContainers.Count() == 0;
  }
IsFirstContainerFocused()
bool LayoutHolder::IsFirstContainerFocused () inline protected
Definition at line 798 of file Container.c.
  {
    return m_ActiveIndex == 0;
  }
IsFirstIndex()
bool LayoutHolder::IsFirstIndex () inline protected
Definition at line 793 of file Container.c.
  {
    return m_ActiveIndex == 0;
  }
IsItemActive()
bool LayoutHolder::IsItemActive () inline protected
Definition at line 603 of file Container.c.
  {
    if (GetFocusedContainer())
      return GetFocusedContainer().IsItemActive();
    return false;
  }
IsItemWithQuantityActive()
bool LayoutHolder::IsItemWithQuantityActive () inline protected
Definition at line 610 of file Container.c.
  {
    if (GetFocusedContainer())
      return GetFocusedContainer().IsItemWithQuantityActive();
    return false;
  }
IsLastContainerFocused()
bool LayoutHolder::IsLastContainerFocused () inline protected
Definition at line 803 of file Container.c.
  {
    return m_ActiveIndex >= (m_OpenedContainers.Count() - 1);
  }
IsLastIndex()
bool LayoutHolder::IsLastIndex () inline protected
Definition at line 788 of file Container.c.
  {
    return m_ActiveIndex == (m_OpenedContainers.Count() - 1);
  }
IsOpened()
bool LayoutHolder::IsOpened () inline protected
Definition at line 190 of file Container.c.
  {
    return !m_Closed;
  }
MoveGridCursor()
void LayoutHolder::MoveGridCursor (int direction) inline protected
Definition at line 119 of file Container.c.
  {
    if (direction == Direction.UP)
      SetPreviousActive();
    else if (direction == Direction.DOWN)
      SetNextActive();
    else if (direction == Direction.RIGHT)
      SetNextRightActive();
    else if (direction == Direction.LEFT)
      SetNextLeftActive();
    UpdateSelectionIcons();
    Inventory.GetInstance().UpdateConsoleToolbar();
  }
References Inventory(), Container::SetNextActive(), Container::SetNextLeftActive(), Container::SetNextRightActive(), and Container::SetPreviousActive().
OnDropReceivedFromHeader()
void LayoutHolder::OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) protected
OnSelectButton()
bool LayoutHolder::OnSelectButton () inline protected
Definition at line 293 of file Container.c.
  {
    if (GetFocusedContainer())
      return GetFocusedContainer().OnSelectButton();
    return false;
  }
Open()
void LayoutHolder::Open () inline protected
Definition at line 178 of file Container.c.
  {
    m_Closed = false;
    UpdateSelectionIcons();
  }
RecomputeOpenedContainers()
void LayoutHolder::RecomputeOpenedContainers () inline protected
Definition at line 924 of file Container.c.
  {
    m_OpenedContainers.Clear();
    int i;
    bool need_reset_focus = false;
    Container c;
    for (i = 0; i < m_Body.Count(); i++)
    {
      c = Container.Cast(m_Body.Get(i));
      if (c)
      {
        c.RecomputeOpenedContainers();
        if (c.IsDisplayable() && c.IsVisible())
          m_OpenedContainers.Insert(c);
        else if (c.IsActive())
        {
          c.SetActive(false);
          need_reset_focus = true;
        }
      }
    }
    //In case of removing focused container or change order of containers
    if (IsActive())
    {
      if (!need_reset_focus && (m_ActiveIndex >= m_OpenedContainers.Count() || !m_OpenedContainers[m_ActiveIndex].IsActive()))
      {
        need_reset_focus = true;
        for (i = 0; i < m_OpenedContainers.Count(); i++)
        {
          if (m_OpenedContainers[i].IsActive())
          {
            need_reset_focus = false;
            m_ActiveIndex = i;
          }
        }
      }
      if (need_reset_focus)
        SetFirstActive();
    }
  }
References IsActive().
Refresh()
override void LayoutHolder::Refresh () inline protected
Definition at line 1019 of file Container.c.
  {
    for (int i = 0; i < m_Body.Count(); i++)
    {
      if (m_Body.Get(i))
        m_Body.Get(i).Refresh();
    }
  }
Remove()
void LayoutHolder::Remove (LayoutHolder container) inline protected
Definition at line 988 of file Container.c.
  {
    if (m_Body)
    {
      int index = m_Body.Find(container);
      if (index > -1)
      {
        index = m_OpenedContainers.Find(container);
        if (index > -1)
        {
          if (index <= m_ActiveIndex)
          {
            if (GetFocusedContainer() == container)
              SetPreviousActive(true);
            else
              m_ActiveIndex--;
          }
          m_OpenedContainers.RemoveItem(container);
        }
        m_Body.RemoveItem(container);
      }
    }
    Refresh();
  }
References Container::Refresh(), and Container::SetPreviousActive().
ResetFocusedContainer()
void LayoutHolder::ResetFocusedContainer () inline protected
Definition at line 808 of file Container.c.
  {
    if (GetFocusedContainer())
      GetFocusedContainer().ResetFocusedContainer();
    m_ActiveIndex == 0;
  }
ScrollToActiveContainer()
void LayoutHolder::ScrollToActiveContainer () inline protected
Definition at line 135 of file Container.c.
  {
    ScrollWidget sw = GetScrollWidget();
    if (sw)
    {
      float x, y, y_s;
      sw.GetScreenPos(x, y);
      sw.GetScreenSize(x, y_s);
      float f_y, f_h;
      float amount;
      f_y = GetFocusedContainerYScreenPos(true);
      f_h = GetFocusedContainerHeight(true);
      float next_pos = f_y + f_h;
      if (next_pos > (y + y_s))
      {
        amount = sw.GetVScrollPos() + next_pos - (y + y_s) + 2;
        sw.VScrollToPos(amount);
      }
      else if (f_y < y)
      {
        amount = sw.GetVScrollPos() + f_y - y - 2;
        sw.VScrollToPos(amount);
      }
      //CheckScrollbarVisibility();
    }
  }
References Container::GetFocusedContainerHeight(), Container::GetFocusedContainerYScreenPos(), x, and y.
Select()
bool LayoutHolder::Select () inline protected
Definition at line 286 of file Container.c.
  {
    if (GetFocusedContainer())
      return GetFocusedContainer().Select();
    return false;
  }
SelectItem()
bool LayoutHolder::SelectItem () inline protected
Definition at line 279 of file Container.c.
  {
    if (GetFocusedContainer())
      return GetFocusedContainer().SelectItem();
    return false;
  }
SetActive()
override void LayoutHolder::SetActive (bool active) inline protected
Definition at line 725 of file Container.c.
  {
    if (!active)
      HideOwnedTooltip();
    if (!active && !m_IsActive)
      return;
    super.SetActive(active);
    if (GetHeader())
      GetHeader().SetActive(active);
    if (m_MainWidget.FindAnyWidget("SelectedContainer"))
      m_MainWidget.FindAnyWidget("SelectedContainer").Show(active);
    Container c;
    if (active)
    {
      SetDefaultFocus();
      if (m_OpenedContainers.Count())
      {
        c = Container.Cast(m_OpenedContainers.Get(m_ActiveIndex));
        if (c)
          c.SetActive(active);
      }
    }
    else
    {
      c = GetFocusedContainer();
      if (c)
        GetFocusedContainer().SetActive(false);
      Unfocus();
      m_ActiveIndex = 0;
      m_FocusedColumn = 0;
    }
  }
References Container::GetHeader(), m_IsActive, Container::SetDefaultFocus(), and Container::Unfocus().
SetActiveIndex()
void LayoutHolder::SetActiveIndex (int index) inline protected
Definition at line 81 of file Container.c.
  {
    m_ActiveIndex = index;
  }
SetColumnCount()
void LayoutHolder::SetColumnCount (int count) inline protected
Definition at line 639 of file Container.c.
  {
    m_ColumnCount = count;
  }
SetDefaultFocus()
void LayoutHolder::SetDefaultFocus (bool while_micromanagment_mode = false) inline protected
Definition at line 102 of file Container.c.
  {
    m_ActiveIndex = 0;
  }
SetFirstActive()
override void LayoutHolder::SetFirstActive () inline protected
Definition at line 701 of file Container.c.
  {
    if (!m_IsActive)
      SetActive(true);
    else
    {
      if (m_OpenedContainers.Count())
      {
        SetDefaultFocus();
        if (!m_OpenedContainers[m_ActiveIndex].IsActive())
        {
          for (int i = 1; i < m_OpenedContainers.Count(); i++)
          {
            if (m_OpenedContainers[i].IsActive())
              m_OpenedContainers[i].SetActive(false);
          }
          m_OpenedContainers[m_ActiveIndex].SetActive(true);
        }
        else
          m_OpenedContainers[m_ActiveIndex].SetFirstActive();
      }
    }
  }
References IsActive(), m_IsActive, SetActive(), and Container::SetDefaultFocus().
SetFocusedColumn()
void LayoutHolder::SetFocusedColumn (int column) inline protected
Definition at line 649 of file Container.c.
  {
    m_FocusedColumn = column;
  }
SetFocusedContainer()
void LayoutHolder::SetFocusedContainer (Container cont) inline protected
Definition at line 63 of file Container.c.
  {
    m_FocusedContainer = cont;
  }
SetForceShow()
void LayoutHolder::SetForceShow (bool value) inline protected
Definition at line 1066 of file Container.c.
  {
    m_ForcedShow = value;
  }
SetHeader()
void LayoutHolder::SetHeader (Header header) protected
SetLastActive()
override void LayoutHolder::SetLastActive () inline protected
Definition at line 665 of file Container.c.
  {
    if (m_IsActive)
    {
      m_IsActive = true;
      if (m_OpenedContainers.Count())
      {
        SetLastFocus();
        if (!m_OpenedContainers[m_ActiveIndex].IsActive())
        {
          for (int i = 0; i < m_OpenedContainers.Count() - 1; i++)
          {
            if (m_OpenedContainers[i].IsActive())
              m_OpenedContainers[i].SetActive(false);
          }
          m_OpenedContainers[m_ActiveIndex].SetLastActive();
        }
        else
          m_OpenedContainers[m_ActiveIndex].SetLastActive();
      }
    }
    else
    {
      m_IsActive = true;
      if (GetHeader())
        GetHeader().SetActive(m_IsActive);
      SetLastFocus();
      if (m_OpenedContainers.Count())
      {
        Container c = Container.Cast(m_OpenedContainers.Get(m_ActiveIndex));
        if (c)
          c.SetLastActive();
      }
    }
  }
References Container::GetHeader(), IsActive(), m_IsActive, and Container::SetLastFocus().
SetLastFocus()
void LayoutHolder::SetLastFocus () inline protected
Definition at line 107 of file Container.c.
  {
    m_ActiveIndex = 0;
    m_FocusedColumn = 0;
    if (m_OpenedContainers.Count() > 0)
      m_ActiveIndex = m_OpenedContainers.Count() - 1;
  }
SetLayoutName()
override void LayoutHolder::SetLayoutName () inline protected
Definition at line 968 of file Container.c.
  {
    m_LayoutName = WidgetLayoutName.Container;
  }
References WidgetLayoutName::Container.
Referenced by ScriptedWidgetEventHandler::LayoutHolder().
SetNextActive()
void LayoutHolder::SetNextActive () inline protected
Definition at line 816 of file Container.c.
  {
    HideOwnedTooltip();
    Container active;
    if (m_OpenedContainers.Count())
      active = Container.Cast(m_OpenedContainers[m_ActiveIndex]);
    if (active && active.IsActive())
      active.SetNextActive();
    if (!active || !active.IsActive())
    {
      Container next;
      if (!IsLastContainerFocused())
      {
        m_ActiveIndex++;
        next = Container.Cast(m_OpenedContainers[m_ActiveIndex]);
        next.SetActive(true);
      }
      else if (Container.Cast(GetParent()))
        SetActive(false);
      else
      {
        SetActive(false);
        SetFirstActive();
      }
    }
  }
References GetParent(), and SetActive().
SetNextLeftActive()
void LayoutHolder::SetNextLeftActive () inline protected
Definition at line 886 of file Container.c.
  {
    Container active;
    if (m_OpenedContainers.Count())
      active = Container.Cast(m_OpenedContainers[m_ActiveIndex]);
    if (active)
      active.SetNextLeftActive();
  }
SetNextRightActive()
void LayoutHolder::SetNextRightActive () inline protected
Definition at line 876 of file Container.c.
  {
    Container active;
    if (m_OpenedContainers.Count())
      active = Container.Cast(m_OpenedContainers[m_ActiveIndex]);
    if (active)
      active.SetNextRightActive();
  }
SetOpenForSlotIcon()
void LayoutHolder::SetOpenForSlotIcon (bool open, SlotsIcon icon = null) inline protected
Definition at line 195 of file Container.c.
  {
    if (!icon)
      icon = m_SlotIcon;
    if (icon)
    {
      icon.GetRadialIcon().Show(open);
      icon.GetRadialIconClosed().Show(!open);
    }
    /*else
      {
      ErrorEx("Dbg No Icon");
      }*/
  }
SetPreviousActive()
void LayoutHolder::SetPreviousActive (bool force = false) inline protected
Definition at line 846 of file Container.c.
  {
    HideOwnedTooltip();
    Container active;
    if (m_OpenedContainers.Count())
      active = Container.Cast(m_OpenedContainers[m_ActiveIndex]);
    if (active && active.IsActive())
      active.SetPreviousActive();
    if (!active || !active.IsActive())
    {
      Container prev;
      if (!IsFirstContainerFocused())
      {
        m_ActiveIndex--;
        prev = Container.Cast(m_OpenedContainers[m_ActiveIndex]);
        prev.SetLastActive();
      }
      else if (Container.Cast(GetParent()))
        SetActive(false);
      else
      {
        SetActive(false);
        SetLastActive();
      }
    }
  }
References GetParent(), SetActive(), and Container::SetLastActive().
SetSameLevelNextActive()
void LayoutHolder::SetSameLevelNextActive () inline protected
Definition at line 896 of file Container.c.
  {
    Container active;
    active = Container.Cast(m_OpenedContainers[m_ActiveIndex]);
    active.SetActive(false);
    m_ActiveIndex++;
    if (m_ActiveIndex > m_OpenedContainers.Count() - 1)
      m_ActiveIndex = 0;
    active = Container.Cast(m_OpenedContainers[m_ActiveIndex]);
    active.SetActive(true);
  }
SetSameLevelPreviousActive()
void LayoutHolder::SetSameLevelPreviousActive () inline protected
Definition at line 910 of file Container.c.
  {
    Container active;
    active = Container.Cast(m_OpenedContainers[m_ActiveIndex]);
    active.SetActive(false);
    m_ActiveIndex--;
    if (m_ActiveIndex < 0)
      m_ActiveIndex = m_OpenedContainers.Count() - 1;
    active = Container.Cast(m_OpenedContainers[m_ActiveIndex]);
    active.SetActive(true);
  }
SetSlotIcon()
void LayoutHolder::SetSlotIcon (SlotsIcon icon) inline protected
Definition at line 97 of file Container.c.
  {
    m_SlotIcon = icon;
  }
ShowContent()
void LayoutHolder::ShowContent (bool force_show = false) inline protected
Definition at line 1051 of file Container.c.
  {
    if (force_show)
      m_ForcedHide = false;
    if (!m_ForcedHide)
    {
      for (int i = 0; i < m_Body.Count(); i++)
      {
        if (m_Body.Get(i))
          m_Body.Get(i).OnShow();
      }
    }
  }
SplitItem()
bool LayoutHolder::SplitItem () inline protected
Definition at line 328 of file Container.c.
  {
    if (GetFocusedContainer())
      return GetFocusedContainer().SplitItem();
    return false;
  }
Toggle()
void LayoutHolder::Toggle () inline protected
Definition at line 211 of file Container.c.
  {
    if (IsOpened())
      Close();
    else
      Open();
    SetOpenForSlotIcon(IsOpened());
  }
References Container::Close(), IsOpened(), and Container::Open().
TransferItem()
bool LayoutHolder::TransferItem () inline protected
Definition at line 314 of file Container.c.
  {
    if (GetFocusedContainer())
      return GetFocusedContainer().TransferItem();
    return false;
  }
TransferItemToVicinity()
bool LayoutHolder::TransferItemToVicinity () inline protected
Definition at line 307 of file Container.c.
  {
    if (GetFocusedContainer())
      return GetFocusedContainer().TransferItemToVicinity();
    return false;
  }
Unfocus()
void LayoutHolder::Unfocus () inline protected
Definition at line 115 of file Container.c.
  {
  }
UnfocusAll()
void LayoutHolder::UnfocusAll () inline protected
Definition at line 763 of file Container.c.
  {
    for (int i = 0; i < Count(); i++)
    {
      for (int j = 0; j < ITEMS_IN_ROW; j++)
      {
        SlotsIcon icon;
        if (Get(i) && Get(i).GetMainWidget())
          Get(i).GetMainWidget().GetUserData(icon);
        if (icon)
          icon.GetCursorWidget().Show(false);
      }
    }
  }
References Count, Get(), and ITEMS_IN_ROW.
UnfocusGrid()
void LayoutHolder::UnfocusGrid () inline protected
Definition at line 779 of file Container.c.
  {
    if (GetFocusedContainer())
    {
      m_FocusedColumn = 0;
      GetFocusedContainer().UnfocusAll();
    }
  }
UpdateBodySpacers()
void LayoutHolder::UpdateBodySpacers () inline protected
Definition at line 1028 of file Container.c.
  {
    for (int i = 0; i < m_Body.Count(); i++)
    {
      Container c = Container.Cast(m_Body.Get(i));
      if (c && c.IsInherited(Container))
        c.UpdateSpacer();
    }
    UpdateSpacer();
  }
UpdateInterval()
override void LayoutHolder::UpdateInterval () inline protected
Definition at line 654 of file Container.c.
  {
    for (int i = 0; i < m_Body.Count(); i++)
    {
      if (m_Body.Get(i))
        m_Body.Get(i).UpdateInterval();
    }
    CheckHeaderDragability();
  }
References Container::CheckHeaderDragability().
UpdateRadialIcon()
void LayoutHolder::UpdateRadialIcon () inline protected
Definition at line 91 of file Container.c.
  {
    if (m_SlotIcon)
      m_SlotIcon.GetRadialIconPanel().Show(false);
  }
References SlotsIcon::GetRadialIconPanel().
UpdateSelectionIcons()
override void LayoutHolder::UpdateSelectionIcons () inline protected
Definition at line 1071 of file Container.c.
  {
    m_Parent.UpdateSelectionIcons();
  }
References m_Parent.
UpdateSpacer()
void LayoutHolder::UpdateSpacer () protected
Member Data Documentation
ITEMS_IN_ROW
const int LayoutHolder::ITEMS_IN_ROW = 8 protected
Definition at line 10 of file Container.c.
m_ActiveIndex
int LayoutHolder::m_ActiveIndex = 0 protected
Definition at line 5 of file Container.c.
m_Body
ref array<ref LayoutHolder> LayoutHolder::m_Body protected
Definition at line 3 of file Container.c.
m_Closed
bool LayoutHolder::m_Closed protected
Definition at line 7 of file Container.c.
m_ColumnCount
int LayoutHolder::m_ColumnCount protected
Definition at line 13 of file Container.c.
m_Entity
EntityAI LayoutHolder::m_Entity protected
Definition at line 20 of file Container.c.
m_FocusedColumn
int LayoutHolder::m_FocusedColumn = 0 protected
Definition at line 15 of file Container.c.
m_FocusedContainer
Container LayoutHolder::m_FocusedContainer protected
Definition at line 8 of file Container.c.
m_ForcedHide
bool LayoutHolder::m_ForcedHide protected
Definition at line 16 of file Container.c.
m_ForcedShow
bool LayoutHolder::m_ForcedShow protected
Definition at line 17 of file Container.c.
m_LastIndex
bool LayoutHolder::m_LastIndex protected
Definition at line 6 of file Container.c.
m_OpenedContainers
ref array<LayoutHolder> LayoutHolder::m_OpenedContainers protected
Definition at line 4 of file Container.c.
m_PrevAlpha
float LayoutHolder::m_PrevAlpha protected
Definition at line 9 of file Container.c.
m_SlotIcon
SlotsIcon LayoutHolder::m_SlotIcon protected
Definition at line 19 of file Container.c.
SORT_ATTACHMENTS_NEXT_OFFSET
const int LayoutHolder::SORT_ATTACHMENTS_NEXT_OFFSET = 2 protected
Definition at line 24 of file Container.c.
SORT_ATTACHMENTS_OWN
const int LayoutHolder::SORT_ATTACHMENTS_OWN = 1 protected
Definition at line 22 of file Container.c.
SORT_CARGO_NEXT_OFFSET
const int LayoutHolder::SORT_CARGO_NEXT_OFFSET = 3 protected
Definition at line 25 of file Container.c.
SORT_CARGO_OWN
const int LayoutHolder::SORT_CARGO_OWN = 2 protected
Definition at line 23 of file Container.c.
The documentation for this class was generated from the following file:
scripts/5_Mission/GUI/InventoryNew/Containers/Container.c