DayZ: Math library
Math library
Classes
class Math
Functions
void Math::Math ()
void Math::~Math ()
static proto int Math::GetNumberOfSetBits (int i)
returns the number of bits set in a bitmask i
static proto int Math::GetNthBitSet (int value, int n)
returns the the index of n-th bit set in a bit mask counting from the right, for instance, in a mask ..0110 1000 , the 0th set bit(right-most bit set to 1) is at 3th position(starting at 0), 1st bit is at 5th position, 2nd bit is at 6th position etc..
static proto int Math::RandomInt (int min, int max)
Returns a random int number between and min [inclusive] and max [exclusive].
static int Math::RandomIntInclusive (int min, int max)
Returns a random int number between and min [inclusive] and max [inclusive].
static bool Math::RandomBool ()
Returns a random bool .
static proto float Math::RandomFloat (float min, float max)
Returns a random float number between and min[inclusive] and max[exclusive].
static float Math::RandomFloatInclusive (float min, float max)
Returns a random float number between and min [inclusive] and max [inclusive].
static float Math::RandomFloat01 ()
Returns a random float number between and min [inclusive] and max [inclusive].
static proto int Math::Randomize (int seed)
Sets the seed for the random number generator.
static proto float Math::NormalizeAngle (float ang)
Normalizes the angle (0...360)
static proto float Math::DiffAngle (float angle1, float angle2)
Return relative difference between angles.
static proto float Math::Pow (float v, float power)
Return power of v ^ power.
static proto float Math::ModFloat (float x, float y)
Returns the floating-point remainder of x/y rounded towards zero.
static proto float Math::RemainderFloat (float x, float y)
Returns the floating-point remainder of x/y rounded to nearest.
static proto float Math::AbsFloat (float f)
Returns absolute value.
static proto int Math::AbsInt (int i)
Returns absolute value.
static proto float Math::SignFloat (float f)
Returns sign of given value.
static proto int Math::SignInt (int i)
Returns sign of given value.
static proto float Math::SqrFloat (float f)
Returns squared value.
static proto int Math::SqrInt (int i)
Returns squared value.
static proto float Math::Sqrt (float val)
Returns square root.
static proto float Math::Log2 (float x)
Returns the binary (base-2) logarithm of x.
static proto float Math::Sin (float angle)
Returns sinus of angle in radians.
static proto float Math::Cos (float angle)
Returns cosinus of angle in radians.
static proto float Math::Tan (float angle)
Returns tangent of angle in radians.
static proto float Math::Asin (float s)
Returns angle in radians from sinus.
static proto float Math::Acos (float c)
Returns angle in radians from cosinus.
static proto float Math::Atan (float x)
Returns angle in radians from tangent.
static proto float Math::Atan2 (float y, float x)
Returns angle in radians from tangent.
static proto float Math::Round (float f)
Returns mathematical round of value.
static proto float Math::Floor (float f)
Returns floor of value.
static proto float Math::Ceil (float f)
Returns ceil of value.
static proto float Math::WrapFloat (float f, float min, float max)
Returns wrap number to specified interval [min, max[.
static proto float Math::WrapFloatInclusive (float f, float min, float max)
Returns wrap number to specified interval [min, max].
static proto float Math::WrapFloat0X (float f, float max)
Returns wrap number to specified interval [0, max[.
static proto float Math::WrapFloat0XInclusive (float f, float max)
Returns wrap number to specified interval [0, max].
static proto int Math::WrapInt (int i, int min, int max)
Returns wrap number to specified interval [min, max[.
static proto int Math::WrapInt0X (int i, int max)
Returns wrap number to specified interval [0, max[.
static proto float Math::Clamp (float value, float min, float max)
Clamps 'value' to 'min' if it is lower than 'min', or to 'max' if it is higher than 'max'.
static proto float Math::Min (float x, float y)
Returns smaller of two given values.
static proto float Math::Max (float x, float y)
Returns bigger of two given values.
static proto bool Math::IsInRange (float v, float min, float max)
Returns if value is between min and max (inclusive)
static proto bool Math::IsInRangeInt (int v, int min, int max)
Returns if value is between min and max (inclusive)
static proto float Math::Lerp (float a, float b, float time)
Linearly interpolates between 'a' and 'b' given 'time'.
static proto float Math::InverseLerp (float a, float b, float value)
Calculates the linear value that produces the interpolant value within the range [a, b], it's an inverse of Lerp.
static proto float Math::AreaOfRightTriangle (float s, float a)
Returns area of a right triangle.
static proto float Math::HypotenuseOfRightTriangle (float s, float a)
Returns hypotenus of a right triangle.
static proto bool Math::IsPointInCircle (vector c, float r, vector p)
Returns if point is inside circle.
static proto bool Math::IsPointInRectangle (vector mi, vector ma, vector p)
Returns if point is inside rectangle.
static proto float Math::SmoothCD (float val, float target, inout float velocity[], float smoothTime, float maxVelocity, float dt)
Does the CD smoothing function - easy in | easy out / S shaped smoothing.
static float Math::Poisson (float mean, int occurences)
occurences values above '12' will cause Factorial to overflow int.
static int Math::Factorial (int val)
values above '12' will cause int overflow
Variables
static const float Math::EULER = 2.7182818284590452353
static const float Math::PI = 3.14159265358979
static const float Math::PI2 = 6.28318530717958
static const float Math::PI_HALF = 1.570796326794
static const float Math::RAD2DEG = 57.2957795130823208768
static const float Math::DEG2RAD = 0.01745329251994329577
Detailed Description
Function Documentation
AbsFloat()
static proto float Math::AbsFloat (float f) static private
Returns absolute value.
Parameters
f float Value
Returns
float - Absolute value
Print(Math.AbsFloat(-12.5));
>> 12.5
Referenced by ActionPushCar::ActionCondition(), ActionFillBrakes::ActionCondition(), ActionEnterLadder::ActionCondition(), SoftSkillsManager::AddSpecialty(), DayZPlayerImplementAiming::ApplyHorizontalNoise(), WorldData::CalcBaseEnvironmentTemperature(), CalculateEyeAcco(), CCTWaterSurface::Can(), DebugMonitorValues::CheckBlood(), Managed::CheckBlood(), DebugMonitorValues::CheckHealth(), Managed::CheckHealth(), BaseBuildingBase::CheckMemoryPointVerticalDistance(), Cooling(), DayZIntroScenePC::DayZIntroScenePC(), StaminaHandler::DepleteStamina(), EvaluateComponentEx(), EvaluateHit_Player(), EntityLightSource::FadeBrightnessTo(), EntityLightSource::FadeRadiusTo(), DayZInfected::FightLogic(), FilterObstructedObjectsByGrouping(), DayZInfected::GetAttackPitch(), GetCollisionBoxSize(), Environment::GetEnvironmentTemperature(), GetMeleeTargetEx(), ActionTargetsCursor::GetOnScreenPosition(), SoftSkillsManager::GetPreciseRoughLevels(), GetRadius(), Transport::GetSpeedometerAbsolute(), DayZInfected::HandleMove(), DayZPlayer::HandleView(), AttachmentsOutOfReach::IsAttachmentReachable(), Hologram::IsBaseFlat(), Hologram::IsCollidingAngle(), BaseBuildingBase::IsFacingPlayer(), ManBase::IsFacingTarget(), IsPlayerOrientedTowardPos(), PointLightBase::OnFrameLightSource(), InventoryActionHandler::OnUpdate(), DayZPlayerImplementAiming::ProcessAimFilters(), Weapon_Base::SetCylinderRotationAnimationPhase(), EntityLightSource::SetDancingShadowsAmplitude(), EntityLightSource::SetDancingShadowsMovementSpeed(), EntityLightSource::SetFlickerAmplitude(), Hologram::SmoothProjectionMovement(), EnProfilerTests::TestClassTimeData(), EnProfilerTests::TestFuncTimeData(), AnimationTimer::Tick(), AnimatorTimer::Tick(), ScriptedWidgetEventHandler::Update(), WeaponManager::Update(), UIScriptedMenu::Update(), UpdateLRAngleUnlocked(), UpdateUDAngle(), and UpdateUDAngleUnlocked().
AbsInt()
static proto int Math::AbsInt (int i) static private
Returns absolute value.
Parameters
i int Value
Returns
int - Absolute value
Print(Math.AbsInt(-12));
>> 12
Referenced by PluginBase::ActivateModifier(), SoftSkillsManager::AddExponentialPrecise(), SoftSkillsManager::AddExponentialRough(), ManBase::CanChangeStance(), CheckContactCache(), PluginBase::DeactivateModifier(), Hud::DisplayNotifier(), ManBase::GetBrokenLegs(), GetTemperatureColor(), DayZInfected::HandleOrientation(), DayZPlayer::HandleView(), PluginBase::IsModifierLocked(), PluginBase::LockModifier(), HealthMdfr::OnTick(), OrderedPositionNumbersFromGridCoords(), Hud::RefreshVehicleHud(), PlayerAgentPool::RemoteGrowRequestDebug(), PluginBase::RequestDetailedInfo(), AutoHeightSpacer::Update(), ManBase::UpdateCorpseState(), and ManBase::UpdateCorpseStateVisual().
Acos()
static proto float Math::Acos (float c) static private
Returns angle in radians from cosinus.
Parameters
c float Cosinus
Returns
float - Angle in radians
Print(Math.Acos(0.707107)); // (cosinus 45)
>> 0.785398
Referenced by ActionCreateIndoorFireplace::ActionCondition(), ActionCreateIndoorOven::ActionCondition(), ActionPlaceFireplaceIndoor::ActionCondition(), ActionPlaceOvenIndoor::ActionCondition(), DayZInfected::ComputeHitDirectionAngle(), DayZCreatureAI::ComputeHitDirectionAngleDeg(), DayZInfected::ComputeHitDirectionAngleEx(), DropAllItemsInInventoryInBounds(), DayZPlayer::EvaluateDamageHitAnimation(), DayZPlayer::EvaluateDeathAnimation(), IsEntityBehindEntityInAngle(), BaseBuildingBase::IsFacingCamera(), BaseBuildingBase::IsFacingPlayer(), IsPlayerOrientedTowardPos(), Weapon::LiftWeaponCheck(), OnAttachmentRuined(), and EffectArea::PlaceParticles().
AreaOfRightTriangle()
static proto float Math::AreaOfRightTriangle (float s, float a) static private
Returns area of a right triangle.
Parameters
s float Length of adjacent leg
a float Angle of corner bordering adjacent which is not the right corner (in radians)
Returns
float - Area
Asin()
static proto float Math::Asin (float s) static private
Returns angle in radians from sinus.
Parameters
s float Sinus
Returns
float - Angle in radians
Print(Math.Asin(0.707107)); // (sinus 45)
>> 0.785398
Referenced by Easing::EaseInElastic(), Easing::EaseInOutElastic(), Easing::EaseOutElastic(), and Weapon::LiftWeaponCheck().
Atan()
static proto float Math::Atan (float x) static private
Returns angle in radians from tangent.
Parameters
x float Tangent
Returns
float - Angle in radians
Atan2()
static proto float Math::Atan2 (float y, float x) static private
Returns angle in radians from tangent.
Parameters
y float Tangent
x float Tangent
Returns
float - Angle in radians
Print (Math.Atan2(1, 1));
>> 0.785398
Referenced by DayZIntroScene::DayZIntroScene(), GetMousePointerAngle(), DayZInfected::HandleOrientation(), MeleeTargetSettings(), and PluginBase::OnUpdate().
Ceil()
static proto float Math::Ceil (float f) static private
Returns ceil of value.
Parameters
f float Value
Returns
float - Ceil of value
Print(Math.Ceil(5.3));
Print(Math.Ceil(5.8));
>> 6
>> 6
Referenced by ActionTargetsCursor::BuildFloatingCursor(), BleedChanceData::CalculateBleedChance(), CAContinuousMineWood::CreateSecondaryItems(), RecipeBase::Do(), ItemBase::Init(), Attachments::InitAttachmentGrid(), ServerBrowserTabConsolePages::LoadExtraEntries(), UIScriptedMenu::NextPrevPage(), ScriptedWidgetEventHandler::OnUpdate(), UIScriptedMenu::ProcessDistanceAndUnits(), ServerBrowserTab::UpdatePageButtons(), Container::UpdateRowVisibility(), and FlammableBase::Upgrade().
Clamp()
static proto float Math::Clamp (float value, float min, float max) static private
Clamps 'value' to 'min' if it is lower than 'min', or to 'max' if it is higher than 'max'.
Parameters
value float Value
min float Minimum value
max float Maximum value
Returns
float - Clamped value
Print(Math.Clamp(-0.1, 0, 1));
Print(Math.Clamp(2, 0, 1));
Print(Math.Clamp(0.5, 0, 1));
>> 0
>> 1
>> 0.5
Referenced by Chat::Add(), ComponentEnergyManager::AddEnergy(), SoftSkillsManager::AddExponentialPrecise(), SoftSkillsManager::AddExponentialRough(), IEntity::AddHealthLevel(), SoftSkillsManager::AddLinearPrecise(), SoftSkillsManager::AddLinearRough(), BaseBuildingBase::AddRefresherTime01(), AddTemperatureToItem(), AddTemperatureToItemByFire(), AddWetnessToFireplace(), AddWetnessToItem(), AdjustCameraParameters(), Hologram::AlignProjectionOnTerrain(), BaseBuildingBase::AnimateFlagEx(), RecoilBase::ApplyCamOffset(), RecoilBase::ApplyHandsOffset(), RecoilBase::ApplyMouseOffset(), HitDirectionEffectBase::CalculateArrowPosition(), GameplayEffectWidgets_base::CalculateBreathEffect(), PluginBase::CalculateHealth(), DayZPlayerImplementAiming::CalculateSwayMultiplier(), Managed::CheckBlood(), Barrel_ColorBase::ColourClothes(), CookOnDirectSlot(), DamageCrew(), DecreaseCookedItemQuantity(), UIScriptedMenu::DeleteKeyframe(), StaminaHandler::DepleteStamina(), WrittenNoteData::DepleteWritingImplement(), InjurySoundHandlerBase::DetermineInjuryZone(), Hud::DisplayNotifier(), Hud::DisplayTendencyNormal(), RecipeBase::Do(), WeaponDebug::DrawLineOfFireCameraHybrid(), UniversalTemperatureSourceLambdaBaseImpl::DryItemsInVicinity(), EOnPostSimulate(), ItemBase::Fertilize(), PPEffects::FlashbangEffect(), ManBase::FreezeCheck(), ConstructionActionData::GetActualAttachmentToDetach(), GetAirResistanceForSmokeParticles(), ManBase::GetHealthRegenSpeed(), ManBase::GetImmunity(), CAContinuousQuantityEdible::GetProgress(), Hologram::GetProjectionEntityPosition(), SoundHandlerBase::GetStaminaState(), GetTemperatureColor(), UIScriptedMenu::GetTotalTime(), GetZone(), PlayerAgentPool::GrowAgents(), HandleFallDamage(), GameplayEffectWidgets_base::HandleWidgetRoot(), Heating(), PPEffects::HitEffect(), HitDirectionEffectBase::Init(), Weapon::LiftWeaponCheck(), ScriptedWidgetEventHandler::LoadEntries(), DayZCreature::ModCommandHandlerBefore(), RightArea::MoveUpDownIcons(), BaseBuildingBase::OnCEUpdate(), OnEndServer(), ActionRefuelTorch::OnExecuteServer(), Grenade_Base::OnExplosionEffects(), ActionRepairCarChassis::OnFinishProgressServer(), OnFinishProgressServer(), CarScript::OnSound(), BleedingSourcesManagerBase::OnTick(), OnTick(), ModifierBase::OnTick(), HeatComfortMdfr::OnTick(), ShockDamageMdfr::OnTick(), TimerBase::OnUpdate(), DayZPlayerCamera3rdPersonErc::OnUpdate(), GameplayEffectWidgets_base::OnVoiceEvent(), ItemBase::OnWork(), FlashbangEffect::PlaySound(), DayZPlayerImplementAiming::ProcessAimFilters(), RainProcurementHandler::ProcessBatch(), BleedingSourcesManagerBase::ProcessHit(), Environment::ProcessItemsHeat(), ProcessNoiseComponents(), MissionBase::RandomArtillery(), ScriptedWidgetEventHandler::RandomizePageIndex(), PPERequesterBase::RelativizeValue(), SanitizeString(), PluginBase::SelectedObjectSetDamage(), Managed::SendInitValues(), InventoryItem::SetCleanness(), UniversalTemperatureSourceLambdaFireplace::SetCurrentTemperature(), PPEffects::SetDeathDarkening(), PPERequester_GameplayBase::SetFlashbangIntensity(), InventoryItem::SetQuantity(), InventoryItem::SetQuantityNormalized(), BaseBuildingBase::SetRefreshTimer01(), StaminaHandler::SetStamina(), PluginBase::SetStamina(), InventoryItem::SetTemperature(), InventoryItem::SetWet(), ShockDealtEffect::ShockDealtEffect(), Hud::ShowPlayerTag(), ManBase::SimplifyShock(), SnapOnObject(), Liquid::Transfer(), TruncateVec(), DamageDealtEffect::Update(), FlashbangEffect::Update(), ShockDealtEffect::Update(), NotificationUI::Update(), HitDirectionEffectBase::Update(), PPEMatClassParameterCommandData::Update(), RecoilBase::Update(), UpdateCookingState(), CorpseData::UpdateCorpseState(), LeftArea::UpdateSelectionIcons(), BleedingIndicatorDropData::UpdateTransform(), and ValueToBar().
Cos()
static proto float Math::Cos (float angle) static private
Returns cosinus of angle in radians.
Parameters
angle float Angle in radians
Returns
float - Cosinus of angle
Print(Math.Cos(0.785398)); // (45)
>> 0.707107
Referenced by ItemBase::CalcDamageAreaRotation(), HitDirectionEffectBase::CalculateArrowPosition(), Debug::DrawCone(), DropAllItemsInInventoryInBounds(), Easing::EaseInOutSine(), Easing::EaseInSine(), FilterObstructedObjectsByGrouping(), HitDirectionEffectBase::FinalizePositionCalculation(), GetHeadingVector(), DayZInfected::HandleOrientation(), OnAttachmentRuined(), PointLightBase::OnFrameLightSource(), EntityPlacementCallback::OnSetup(), EffectArea::PlaceParticles(), Refresh(), VicinityItemManager::RefreshVicinityItems(), vector::RotateAroundZeroDeg(), vector::RotateAroundZeroRad(), and BleedingIndicatorDropData::ScatterPosition().
DiffAngle()
static proto float Math::DiffAngle (float angle1, float angle2) static private
Return relative difference between angles.
Parameters
angle1 float
angle2 float
Returns
float Difference between angles (angle1 - angle2)
Print(Math.DiffAngle(-45, 45));
Print(Math.DiffAngle(90, 80));
>> -90
>> 10
Factorial()
static int Math::Factorial (int val) inline static private
values above '12' will cause int overflow
Definition at line 687 of file EnMath.c.
  {
    if (val > 12)
    {
      ErrorEx("Values above '12' cause int overflow! Returning '1'");
      return 1;
    }
    int res = 1;
    while (val > 1)
      res *= val--;
    return res;
  }
References ErrorEx.
Referenced by Poisson().
Floor()
static proto float Math::Floor (float f) static private
Returns floor of value.
Parameters
f float Value
Returns
float - Floor of value
Print(Math.Floor(5.3));
Print(Math.Floor(5.8));
>> 5
>> 5
Referenced by WorldData::CalcBaseEnvironmentTemperature(), BleedChanceData::CalculateBleedChance(), DayZIntroScenePC::CharacterRotate(), CreateItemBasePiles(), CreateMagazinePiles(), CreateMagazinePilesFromBullet(), HasMaterials(), UIScriptedMenu::ProcessDistanceAndUnits(), VicinitySlotsContainer::ShowItemsInContainers(), MissionBase::SortedInsert(), ServerBrowserTab::SortedInsertAsc(), ServerBrowserTab::SortedInsertDesc(), ServerBrowserTab::SortedInsertEx(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), SpawnItems(), InventoryItem::SplitItem(), InventoryItem::SplitItemToInventoryLocation(), TakeMaterialsServer(), Barrel_ColorBase::TanPelts(), TruncateVec(), ScriptedWidgetEventHandler::TutorialKeybinds(), and UIScriptedMenu::UpdateItemInfoTemperature().
GetNthBitSet()
static proto int Math::GetNthBitSet (int value, int n) static private
returns the the index of n-th bit set in a bit mask counting from the right, for instance, in a mask ..0110 1000 , the 0th set bit(right-most bit set to 1) is at 3th position(starting at 0), 1st bit is at 5th position, 2nd bit is at 6th position etc..
Referenced by AreaExposureMdfr::BleedingSourceCreateCheck(), PluginBase::InjectAgentsWithPlayer(), and PluginBase::InjectAgentsWithPlayerCount().
GetNumberOfSetBits()
static proto int Math::GetNumberOfSetBits (int i) static private
returns the number of bits set in a bitmask i
Referenced by AreaExposureMdfr::BleedingSourceCreateCheck(), GetNumberOfSetBits(), PluginBase::InjectAgentsWithPlayer(), PluginBase::InjectAgentsWithPlayerCount(), and RecipeCacheData::SetMask().
HypotenuseOfRightTriangle()
static proto float Math::HypotenuseOfRightTriangle (float s, float a) static private
Returns hypotenus of a right triangle.
Parameters
s float Length of adjacent leg
a float Angle of corner bordering adjacent which is not the right corner (in radians)
Returns
float - hypotenus
InverseLerp()
static proto float Math::InverseLerp (float a, float b, float value) static private
Calculates the linear value that produces the interpolant value within the range [a, b], it's an inverse of Lerp.
Parameters
a float Start
b float End
value float value
Returns
float - the time given the position between 'a' and 'b' given 'value', there is no clamp on 'value', to stay between [0..1] use 'value' between 'a' and 'b'
Print(Math.InverseLerp(3, 7, 5));
>> 0.5
Referenced by RecoilBase::ApplyCamOffset(), BleedChanceData::CalculateBleedChance(), GameplayEffectWidgets_base::CalculateBreathEffect(), Managed::CheckBlood(), ConvertMins12hToAlarmHand01(), DamageCrew(), BroomBase::DebugSetHealthAndEnergy(), WeaponDebug::DrawLineOfFireCameraHybrid(), CGame::ExplosionEffects(), ManBase::FreezeCheck(), HeatComfortAnimHandler::GetEventTime(), Mask_Base::GetFilterQuantity01(), ManBase::GetHealthRegenSpeed(), PlayerStatBase::GetNormalized(), InventoryItem::GetQuantityNormalized(), ManBase::GetStatLevelBorders(), GetZone(), HandleFallDamage(), MaskMdfr::HandleSounds(), Weapon::LiftWeaponCheck(), OnEndServer(), ManBase::OnReceivedHit(), CGame::OnRPC(), BleedingSourcesManagerBase::OnTick(), ModifierBase::OnTick(), PoisoningMdfr::OnTick(), HeatComfortMdfr::OnTick(), ShockDamageMdfr::OnTick(), ScriptConsoleGeneralTab::RefreshDateWidgets(), PPERequesterBase::RelativizeValue(), KitchenTimer::SecondsTo01(), Managed::SendInitValues(), KuruShake::Update(), DamageDealtEffect::Update(), Update(), FlashbangEffect::Update(), ShockDealtEffect::Update(), HitDirectionEffectBase::Update(), RecoilBase::Update(), ScriptConsoleWeatherTab::UpdateSliderValues(), and BleedingIndicatorDropData::UpdateTransform().
IsInRange()
static proto bool Math::IsInRange (float v, float min, float max) static private
Returns if value is between min and max (inclusive)
Parameters
v float Value
min float Minimum value
max float Maximum value
Returns
bool - if value is within range [min,max]
Print(Math.IsInRange(6.9, 3.6, 9.3));
>> true
IsInRangeInt()
static proto bool Math::IsInRangeInt (int v, int min, int max) static private
Returns if value is between min and max (inclusive)
Parameters
v int Value
min int Minimum value
max int Maximum value
Returns
bool - if value is within range [min,max]
Print(Math.IsInRangeInt(6, 3, 9));
>> true
IsPointInCircle()
static proto bool Math::IsPointInCircle (vector c, float r, vector p) static private
Returns if point is inside circle.
Parameters
c vector Center of circle ([0] and [2] will be used, as a circle is 2D)
r float Radius of circle
p vector Point ([0] and [2] will be used, as a circle is 2D)
Returns
bool - True when point is in circle
IsPointInRectangle()
static proto bool Math::IsPointInRectangle (vector mi, vector ma, vector p) static private
Returns if point is inside rectangle.
Parameters
mi vector Minimums of rectangle ([0] and [2] will be used, as a rectangle is 2D)
ma vector Maximums of rectangle ([0] and [2] will be used, as a rectangle is 2D)
p vector Point ([0] and [2] will be used, as a rectangle is 2D)
Returns
bool - True when point is in rectangle
Lerp()
static proto float Math::Lerp (float a, float b, float time) static private
Linearly interpolates between 'a' and 'b' given 'time'.
Parameters
a float Start
b float End
time float Time [value needs to be between 0..1 for correct results, no auto clamp applied]
Returns
float - The interpolated result between the two float values.
Print(Math.Lerp(3, 7, 0.5));
>> 5
Referenced by BleedingIndicatorDropData::AdjustColorSaturation(), PlayerSpawnHandler::ApplyAttributes(), DayZPlayerImplementAiming::ApplyBreathingPattern(), RecoilBase::ApplyCamOffset(), DayZPlayerImplementAiming::ApplyHorizontalNoise(), WorldData::CalcBaseEnvironmentTemperature(), BleedChanceData::CalculateBleedChance(), GameplayEffectWidgets_base::CalculateBreathEffect(), DayZPlayerImplementAiming::CalculateSwayMultiplier(), ConvertAlarmHand01ToMins(), ConvertAlarmHand01ToMins12h(), DamageCrew(), StaminaHandler::DepleteStamina(), DetermineSpecificFinisherType(), WeaponDebug::DrawLineOfFireCameraHybrid(), EOnPostSimulate(), CGame::ExplosionEffects(), PPERequester_GameplayBase::FadeColourMult(), PPEffects::FlashbangEffect(), ManBase::FreezeCheck(), HeatComfortAnimHandler::GetEventTime(), ManBase::GetHealthRegenSpeed(), GetMeleeTargetEx(), MaskMdfr::HandleSounds(), PPEffects::HitEffect(), KuruShake::KuruShake(), ShockHandler::LerpVignette(), PPEMatClassParameterColor::ModifyResultValues(), PlayerSoundEventBase::OnPlay(), PPERequester_GameplayBase::OnStart(), ModifierBase::OnTick(), PoisoningMdfr::OnTick(), HeatComfortMdfr::OnTick(), ShockDamageMdfr::OnTick(), ManBase::OnUnconsciousUpdate(), TimerBase::OnUpdate(), PPERequester_GameplayBase::OnUpdate(), GameplayEffectWidgets_base::OnVoiceEvent(), ComponentEnergyManager::SetEnergy0To1(), InventoryItem::SetQuantityNormalized(), ManBase::SimplifyShock(), Hologram::SmoothProjectionMovement(), ManBase::SpawnDrowningBubbles(), KitchenTimer::Time01ToSeconds(), DamageDealtEffect::Update(), ShockDealtEffect::Update(), HitDirectionEffectBase::Update(), PPEMatClassParameterCommandData::Update(), BleedingIndicatorDropData::UpdateAlpha(), ScriptConsoleGeneralTab::UpdateTime(), BleedingIndicatorDropData::UpdateTransform(), and ValueToBar().
Log2()
static proto float Math::Log2 (float x) static private
Returns the binary (base-2) logarithm of x.
Parameters
x float Value whose logarithm is calculated.
Returns
float The binary logarithm of x: log2x.
If x is negative, it causes a domain error:
If x is zero, it may cause a pole error (depending on the library implementation).
Print(Math.Log2(1.0));
>> 0.0
Referenced by DigestAgents(), and PluginRecipesManagerBase::SortIngredientsInRecipe().
Math()
void Math::Math () inline private
Definition at line 8 of file EnMath.c.
{}
Max()
static proto float Math::Max (float x, float y) static private
Returns bigger of two given values.
Parameters
x float Value
y float Value
Returns
float - max value
Print(Math.Max(5.3, 2.8));
>> 5.3
Referenced by BleedingIndicatorDropData::BleedingIndicatorDropData(), Environment::CalcTemperatureFromTemperatureSource(), PluginBase::CalcTemperatureFromTemperatureSource(), BleedChanceData::CalculateBleedChance(), ReplaceItemWithNewLambda::CopyOldPropertiesToNew(), StaminaHandler::DepleteStamina(), UniversalTemperatureSourceLambdaBaseImpl::DryItemsInVicinity(), Weapon::GetEffectiveAttachmentLength(), CfgGameplayHandler::GetMovementRotationSpeedJog(), CfgGameplayHandler::GetMovementRotationSpeedSprint(), CfgGameplayHandler::GetMovementTimeToSprint(), CfgGameplayHandler::GetMovementTimeToStrafeJog(), CfgGameplayHandler::GetMovementTimeToStrafeSprint(), Environment::GetPlayerHeat(), Environment::GetTemperatureHeightCorrection(), Environment::GetWetDelta(), HasMaterials(), ManBase::Init(), ItemOptics::InitCameraOverrideProperties(), InventoryItem::ItemBase(), PPEMatClassParameterColor::ModifyResultValues(), ScriptConsoleGeneralTab::OnDoubleClick(), CholeraMdfr::OnTick(), Environment::ProcessItemsDryness(), Ammunition_Base::SetFromProjectile(), Hologram::SetOnGround(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), TakeMaterialsServer(), PluginBase::TransmitAgentsEx(), StaminaHandler::Update(), PPEMatClassParameterCommandData::Update(), Update(), BroomBase::UpdateParticle(), Container::UpdateRowVisibility(), and FlammableBase::Upgrade().
Min()
static proto float Math::Min (float x, float y) static private
Returns smaller of two given values.
Parameters
x float Value
y float Value
Returns
float - min value
Print(Math.Min(5.3, 2.8));
>> 2.8
Referenced by Container::AddedToCargoEx(), BleedingIndicatorDropData::AdjustColorSaturation(), StaminaHandler::ApplyExhaustion(), StaminaHandler::CalcStaminaGainBonus(), BleedChanceData::CalculateBleedChance(), BroomBase::CalculateQuantity(), StaminaHandler::DepleteStamina(), InjuredLegNotfr::DisplayBadge(), CGame::GetFOVByZoomType(), GetParentMinSize(), UniversalTemperatureSourceDebug::GetTemperature(), OnGUI_AnimEvents(), Environment::ProcessItemsHeat(), Container::RemovedFromCargo(), ComponentEnergyManager::SetEnergy(), CAContinuousDisinfectPlant::Setup(), CAContinuousFertilizeGardenSlot::Setup(), CAContinuousFill::Setup(), CAContinuousFillCoolant::Setup(), CAContinuousFillFuel::Setup(), CAContinuousFillPowerGenerator::Setup(), CAContinuousQuantityLiquidTransfer::Setup(), CAContinuousTransferQuantity::Setup(), CAContinuousWaterPlant::Setup(), CAContinuousWaterSlot::Setup(), ServerBrowserTab::SortedInsertEx(), MissionBase::TickScheduler(), Liquid::Transfer(), HudDebugWinBase::Update(), StaminaHandler::Update(), PPEMatClassParameterCommandData::Update(), Update(), updateSlotsCount(), and FlammableBase::Upgrade().
ModFloat()
static proto float Math::ModFloat (float x, float y) static private
Returns the floating-point remainder of x/y rounded towards zero.
Parameters
x float Value of the quotient numerator
y float Value of the quotient denominator
Returns
float - The remainder of dividing the arguments
Print(Math.ModFloat(5.3, 2));
Print(Math.ModFloat(18.5, 4.2));
>> 1.3
>> 1.7
Referenced by HitDirectionEffectBase::CalculateArrowPosition(), and FModulus().
NormalizeAngle()
static proto float Math::NormalizeAngle (float ang) static private
Normalizes the angle (0...360)
Parameters
ang float Angle for normalizing
Returns
float - Normalized angle
Print(Math.NormalizeAngle(390));
Print(Math.NormalizeAngle(-90));
>> 30
>> 270
Referenced by HitDirectionEffectBase::CalculateArrowPosition(), and DayZInfected::HandleOrientation().
Poisson()
static float Math::Poisson (float mean, int occurences) inline static private
occurences values above '12' will cause Factorial to overflow int.
Definition at line 681 of file EnMath.c.
  {
    return Pow(mean, occurences) * Pow(EULER, -mean) / Factorial(occurences);
  }
References EULER, Factorial(), and Pow().
Referenced by GameplayEffectsData::BuildProbabilityData().
Pow()
static proto float Math::Pow (float v, float power) static private
Return power of v ^ power.
Parameters
v float Value
power float Power
Returns
float - The result of raising v to the given power
Print(Math.Pow(2, 4)); // (2*2*2*2)=16
>> 16
Referenced by AreaExposureMdfr::BleedingSourceCreateCheck(), MessageReceiverBase::CalculateAutoinfectProbability(), CombinationLock(), DayZIntroScenePC::DayZIntroScenePC(), StaminaHandler::DepleteStamina(), BleedingSourcesManagerBase::DisplayDebug(), Easing::EaseInElastic(), Easing::EaseInExpo(), Easing::EaseInOutElastic(), Easing::EaseInOutExpo(), Easing::EaseOutElastic(), Easing::EaseOutExpo(), BleedingSourcesManagerBase::GetBleedingSourceCountRemote(), MessageReceiverBase::GetCompareMask(), RecipeBase::GetIngredientMaskForItem(), ScriptConsoleConfigTab::Init(), HitDirectionEffectBase::Init(), PluginBase::InjectAgentsWithPlayer(), PluginBase::InjectAgentsWithPlayerCount(), ScriptConsoleItemsTab::OnChange(), ScriptConsoleConfigTab::OnClick(), OnStoreLoad(), Poisson(), RandomFloatInclusive(), PluginRecipesManagerBase::ResolveIngredients(), ItemBase::SetMaxWaterStateVal(), TruncateVec(), PluginRecipesManagerBase::WalkRecipes(), and ItemBase::WaterAllSlots().
RandomBool()
static bool Math::RandomBool () inline static private
Returns a random bool .
Returns
bool - Random bool either 0 or 1
Print(Math.RandomBool());
Print(Math.RandomBool());
Print(Math.RandomBool());
>> true
>> true
>> false
Definition at line 73 of file EnMath.c.
  {
    return RandomIntInclusive(0, 1);
  }
References RandomIntInclusive().
RandomFloat()
static proto float Math::RandomFloat (float min, float max) static private
Returns a random float number between and min[inclusive] and max[exclusive].
Parameters
min float Range starts [inclusive]
max float Range ends [exclusive]
Returns
float - Random number in range
Print(Math.RandomFloat(0,1));
Print(Math.RandomFloat(0,2));
>> 0.597561
>> 1.936456
Referenced by Grenade_Base::ActivateRandomTime(), ApplyForce(), Hit_MeatBones::BloodSplatGround(), EffBulletImpactBase::CalculateStoppingForce(), CGame::CloseCombatEffects(), CreateOrgan(), StaminaHandler::DepleteStamina(), RecipeBase::Do(), ItemBase::DoMeasurement(), ManBase::DropItem(), InventoryItemSuper::EEKilled(), EEOnCECreate(), EOnPostSimulate(), InventoryItem::ExplodeAmmo(), EntityLightSource::HandleDancingShadows(), EntityLightSource::HandleFlickering(), KuruShake::KuruShake(), LeakFluid(), ActionWringClothes::OnFinishProgressServer(), BrainDiseaseMdfr::OnTick(), SymptomBase::OnUpdateClient(), Particle::RandomizeOrientation(), ParticleSource::RandomizeOrientation(), GameInventory::SetGroundPosByOwnerBounds(), DeveloperTeleport::SetPlayerPosition(), Particle::SetWiggle(), TrapSpawnBase::SpawnCatch(), FlammableBase::StandUp(), ThrowAllItemsInInventory(), TrapSpawnBase::Trap_FishNet(), TrapSpawnBase::Trap_SmallFish(), and CameraShake::Update().
RandomFloat01()
static float Math::RandomFloat01 () inline static private
Returns a random float number between and min [inclusive] and max [inclusive].
Returns
float - Random number in range 0.0 .. 1.0
Print(Math.RandomFloat01());  // 0.0 .. 1.0
>> 0.3
>> 1.0
Definition at line 126 of file EnMath.c.
  {
    return RandomFloatInclusive(0, 1);
  }
References RandomFloatInclusive().
Referenced by MessageReceiverBase::AutoinfectCheck(), AreaExposureMdfr::BleedingSourceCreateCheck(), ItemBase::CheckRainTick(), ChooseAttack(), CreateParticle(), PluginBase::DetermineChanceToTransmit(), GetRandomPos(), PluginBase::GiveWormsToPlayer(), ItemBase::InfestationTimerTick(), AreaExposureMdfr::OnTick(), PoisoningMdfr::OnTick(), BrainDiseaseMdfr::OnTick(), CommonColdMdfr::OnTick(), InfluenzaMdfr::OnTick(), Edible_Base::ProcessDecay(), ManBase::ProcessFeetDamageServer(), ManBase::ProcessHandDamage(), BleedingSourcesManagerBase::ProcessHit(), ScriptedWidgetEventHandler::RandomizePageIndex(), BleedingSourcesManagerBase::RemoveBleedingSource(), ManBase::SpreadAgentsEx(), and Managed::Update().
RandomFloatInclusive()
static float Math::RandomFloatInclusive (float min, float max) inline static private
Returns a random float number between and min [inclusive] and max [inclusive].
Parameters
min float Range starts [inclusive]
max float Range ends [inclusive]
Returns
float - Random number in range
Print(Math.RandomFloatInclusive(0, 1)); // 0.0 .. 1.0
Print(Math.RandomFloatInclusive(1, 2)); // 1.0 .. 2.0
>> 0.3
>> 2.0
Definition at line 106 of file EnMath.c.
  {
    int max_range = Math.Pow(2, 30); //max range
    int random_int = Math.RandomInt(0, max_range);
    float rand_float = (float)random_int / (float)max_range;
    float range = max - min;
    return min + (rand_float * range); //rand float
  }
References Pow(), and RandomInt().
Referenced by PlayerSpawnHandler::ApplyAttributes(), AttachBleedingToZonesByHeight(), ItemBase::CatchSetQuant(), RecipeBase::Do(), GameplayEffectsData::GenerateSequenceRandomPosition(), FireworksLauncher::GetEventDelay(), HeatComfortAnimHandler::GetEventTime(), FireworksLauncherClientEvent::GetExplosionDelay(), FireworksLauncherClientEvent::GetExplosionDistance(), GetExplosionDistance(), Math3D::GetRandomDir(), FireworksLauncherClientEvent::GetShotDispersionAngle(), SpookyEventBase::GetSoundPos(), ItemBase::GetTemperatureValue(), HandleFishingResultFailure(), HandleFishingResultSuccess(), HitDirectionEffectBase::Init(), Init(), BleedingIndicatorDropData::InitImageScale(), AreaExposureMdfr::OnActivate(), ContaminationStage1Mdfr::OnActivate(), ContaminationStage2Mdfr::OnActivate(), WoundInfectStage1Mdfr::OnActivate(), WoundInfectStage2Mdfr::OnActivate(), ActionRepairCarChassis::OnFinishProgressServer(), OnFinishProgressServer(), FireworksLauncherClientEvent::OnFired(), AreaExposureMdfr::OnTick(), FeverMdfr::OnTick(), ContaminationStage2Mdfr::OnTick(), SalmonellaMdfr::OnTick(), WoundInfectStage1Mdfr::OnTick(), WoundInfectStage2Mdfr::OnTick(), SymptomBase::OnUpdateClient(), PlateCarrierVest::OnWasAttached(), ProcessSound(), InjurySoundHandlerBase::ProcessSound(), vector::RandomDir(), vector::RandomDir2D(), RandomFloat01(), Randomize(), Particle::RandWiggleFloat(), BleedingIndicatorDropData::ScatterPosition(), InventoryItem::SetCEBasedQuantity(), ContaminatedArea_Dynamic::SpawnItems(), BleedingIndicatorDropData::StartDrop(), and WorldData::WeatherOnBeforeChange().
RandomInt()
static proto int Math::RandomInt (int min, int max) static private
Returns a random int number between and min [inclusive] and max [exclusive].
Parameters
min int Range starts [inclusive]
max int Range ends [exclusive]
Returns
int - Random number in range
Print(Math.RandomInt(0, 1));  // only 0
Print(Math.RandomInt(0, 2));  // 0 or 1
>> 0
>> 1
Referenced by ApplyJumpOutDmg(), AttachBleedingToZonesByHeight(), Catching(), Managed::CreateNewCharacterRandom(), DayZIntroSceneXbox::CreateRandomCharacter(), CreditsLoader::CreateTestJson(), SymptomManager::CreateUniqueID(), InventoryItem::DamageItemAttachments(), InventoryItem::DamageItemInCargo(), DayZIntroScene::DayZIntroScene(), InventoryItem::DoAmmoExplosion(), InventoryItem::EEHitBy(), Apple::EEOnCECreate(), Bottle_Base::EEOnCECreate(), GreenBellPepper::EEOnCECreate(), Pear::EEOnCECreate(), Plum::EEOnCECreate(), Potato::EEOnCECreate(), Tomato::EEOnCECreate(), Zucchini::EEOnCECreate(), MushroomBase::EEOnCECreate(), DayZInfected::EOnInit(), FireworksLauncher::FireworksLauncher(), FishPull(), BloodTypes::GenerateBloodType(), RemotelyActivatedItemBehaviour::GeneratePersistentID(), GameplayEffectsData::GenerateSequenceRandomPosition(), AreaDamageBase::GetRandomHitZone(), array< Class T >::GetRandomIndex(), GetRandomLoadingBackground(), SoundLookupTable::GetSoundBuilder(), ItemBase::GrowthTimerTick(), HandleFishingResultSuccess(), HandleSoundEffectsPipeCreaking(), Init(), ItemBase::Init(), WeaponParticlesBase::OnActivate(), MapHandler::OnDoubleClick(), ActionUnrestrainSelf::OnFinishProgressServer(), OnSteppedOn(), CholeraMdfr::OnTick(), CommonColdMdfr::OnTick(), InfluenzaMdfr::OnTick(), SalmonellaMdfr::OnTick(), ItemBase::PlantBase(), PlayActionSound(), PlayPipeCreakingSoundOnLocation(), BleedingSourcesManagerBase::ProcessHit(), RandomFloatInclusive(), RandomIntInclusive(), UIScriptedMenu::RandomizeCharacter(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::RandomizeFSMStateEx(), BetaSound::SaySound(), DayZAIHitComponentHelpers::SelectMostProbableHitComponent(), SendEmoteRequestSync(), OptionSelector::SetRandomValue(), ShuffleLock(), ItemBase::SoundCollision(), BarbedWireTrigger::SoundCollision(), ItemBase::SoundCut(), ItemBase::SoundElectricShock(), BarbedWireTrigger::SoundElectricShock(), ItemBase::SoundSpark(), TrapSpawnBase::SpawnCatch(), TrapSpawnBase::Trap_RabbitSnare(), and WorldData::WeatherOnBeforeChange().
RandomIntInclusive()
static int Math::RandomIntInclusive (int min, int max) inline static private
Returns a random int number between and min [inclusive] and max [inclusive].
Parameters
min int Range starts [inclusive]
max int Range ends [inclusive]
Returns
int - Random number in range
Print(Math.RandomIntInclusive(0, 1)); // 0 or 1
Print(Math.RandomIntInclusive(0, 2)); // 0, 1, 2
>> 1
>> 2
Definition at line 54 of file EnMath.c.
  {
    return Math.RandomInt(min, max + 1);
  }
References RandomInt().
Referenced by ApplyJumpOutDmg(), AreaExposureMdfr::BleedingSourceCreateCheck(), DamageHands(), CAContinuousMineWood::DamagePlayersHands(), RecipeBase::Do(), Weapon::FillChamber(), Weapon::FillInnerMagazine(), FireworksLauncher::FireworksLauncher(), AreaDamageComponentRaycasted::GetFallbackHitZone(), AreaDamageBase::GetRaycastedHitZone(), FireworksLauncherClientEvent::GetSecondaryExplosionDelay(), DayZInfected::HandleDamageHit(), HitDirectionEffectBase::Init(), OnFinishProgressServer(), ActionPackGift::OnFinishProgressServer(), TrapBase::OnServerSteppedOn(), OnSteppedOn(), CholeraMdfr::OnTick(), ToxicityMdfr::OnTick(), OpenItem::OpenAndSwitch(), Edible_Base::ProcessDecay(), MissionBase::RandomArtillery(), RandomBool(), Randomize(), RandomizedDeviation(), HitDirectionImagesBase::RandomizeImageIdx(), ScriptedWidgetEventHandler::RandomizePageIndex(), CrashBase::RandomizePosition(), SelectEvent(), HitDirectionEffectBase::SetIndicatorRotation(), Weapon::SpawnAttachedMagazine(), TrapSpawnBase::SpawnCatch(), CrashBase::SpawnRandomDeers(), and WorldData::WeatherOnBeforeChange().
Randomize()
static proto int Math::Randomize (int seed) static private
Sets the seed for the random number generator.
Parameters
seed int New seed for the random number generator, -1 will use time
Returns
int - Returns new seed
Print(Math.Randomize(5));
>> 5
Referenced by AttachBleedingToZonesByHeight(), CGame::CGame(), ChooseAttack(), AreaDamageBase::GetRandomHitZone(), GetRandomLoadingBackground(), KuruShake::KuruShake(), CGame::OnAfterCreate(), FireworksLauncher::OnVariablesSynchronized(), Randomize(), RandomizedDeviation(), and ScriptedWidgetEventHandler::RandomizePageIndex().
RemainderFloat()
static proto float Math::RemainderFloat (float x, float y) static private
Returns the floating-point remainder of x/y rounded to nearest.
Parameters
x float Value of the quotient numerator
y float Value of the quotient denominator
Returns
float - The remainder of dividing the arguments
Print(Math.RemainderFloat(5.3, 2));
Print(Math.RemainderFloat(18.5, 4.2));
>> -0.7
>> 1.7
Round()
static proto float Math::Round (float f) static private
Returns mathematical round of value.
Parameters
f float Value
Returns
float - closest whole number to 'f'
Print(Math.Round(5.3));
Print(Math.Round(5.8));
>> 5
>> 6
Referenced by ScriptedWidgetEventHandler::AddItem(), BaseBuildingBase::AddRefresherTime01(), BaseBuildingBase::AnimateFlagEx(), PlayerSpawnHandler::ApplyAttributes(), DayZPlayerImplementAiming::ApplyShakes(), ItemBase::CatchSetQuant(), InventoryItem::CombineItems(), CreateOrgan(), InventoryItem::DeSerializeNumericalVars(), DetermineSpecificFinisherType(), RecipeBase::Do(), PoweredOptic_Base::DoMeasurement(), Inventory_Base::EmptySeedPack(), ScriptedWidgetEventHandler::GetDistanceString(), ComponentEnergyManager::GetEnergy0To100(), VicinitySlotsContainer::GetItemQuantityText(), FlammableBase::GetRagQuantity(), ItemBase::GetTemperatureValue(), EntityLightSource::HandleBlinking(), HandleFishingResultSuccess(), DayZInfected::HandleOrientation(), UIScriptedMenu::NextPrevPage(), BaseBuildingBase::OnCEUpdate(), Battery9V::OnEnergyAdded(), VehicleBattery::OnEnergyAdded(), Battery9V::OnEnergyConsumed(), Chemlight_ColorBase::OnEnergyConsumed(), VehicleBattery::OnEnergyConsumed(), ModifierBase::OnTick(), OnUpdate(), OrderedAltitudeNumbersPosition(), UIScriptedMenu::ProcessDistanceAndUnits(), ProcessNoiseComponents(), ScriptedWidgetEventHandler::RefreshItemVariables(), ScriptedWidgetEventHandler::RefreshQuickbarItemVariables(), ScriptedWidgetEventHandler::RemoveItem(), ScriptedWidgetEventHandler::ResetItem(), ScriptedWidgetEventHandler::SetItem(), ScriptedWidgetEventHandler::SetItemColor(), ActionTargetsCursor::SetItemQuantity(), ScriptedWidgetEventHandler::SetItemQuantity(), Icon::SetQuantity(), SlotsIcon::SetQuantity(), InventoryItem::SetQuantityNormalized(), BaseBuildingBase::SetRefreshTimer01(), UIScriptedMenu::Update(), UIScriptedMenu::UpdateItemInfoQuantity(), UIScriptedMenu::UpdateItemInfoWeight(), ServerBrowserTab::UpdatePageButtons(), ScriptedWidgetEventHandler::UpdateQuantityItems(), UIScriptedMenu::UpdateQuickbarItemCard(), ScriptedWidgetEventHandler::UpdateTemperatureItems(), HudDebugWinBase::UpdateValues(), and ValueToBar().
SignFloat()
static proto float Math::SignFloat (float f) static private
Returns sign of given value.
Parameters
f float Value
Returns
float - Sign of given value
Print(Math.SignFloat(-12.0));
Print(Math.SignFloat(0.0));
Print(Math.SignFloat(12.0));
>> -1.0
>> 0
>> 1.0
SignInt()
static proto int Math::SignInt (int i) static private
Returns sign of given value.
Parameters
i int Value
Returns
int - Sign of given value
Print(Math.SignFloat(-12));
Print(Math.SignFloat(0));
Print(Math.SignFloat(12));
>> -1
>> 0
>> 1
Sin()
static proto float Math::Sin (float angle) static private
Returns sinus of angle in radians.
Parameters
angle float Angle in radians
Returns
float - Sinus of angle
Print(Math.Sin(0.785398)); // (45)
>> 0.707107
Referenced by DayZPlayerImplementAiming::ApplyBreathingPattern(), Bobbing(), ItemBase::CalcDamageAreaRotation(), HitDirectionEffectBase::CalculateArrowPosition(), Debug::DrawCone(), DropAllItemsInInventoryInBounds(), Easing::EaseInElastic(), Easing::EaseInOutElastic(), Easing::EaseOutElastic(), Easing::EaseOutSine(), FilterObstructedObjectsByGrouping(), HitDirectionEffectBase::FinalizePositionCalculation(), GetHeadingVector(), EntityLightSource::HandleBlinking(), DayZInfected::HandleOrientation(), OnAttachmentRuined(), PointLightBase::OnFrameLightSource(), EntityPlacementCallback::OnSetup(), ManBase::OnUnconsciousUpdate(), PPERequester_GameplayBase::OnUpdate(), DayZPlayerCameraBase::OnUpdate(), SymptomBase::OnUpdateClient(), EffectArea::PlaceParticles(), Refresh(), VicinityItemManager::RefreshVicinityItems(), vector::RotateAroundZeroDeg(), vector::RotateAroundZeroRad(), BleedingIndicatorDropData::ScatterPosition(), and AnimatorTimer::Tick().
SmoothCD()
static proto float Math::SmoothCD (float val, float target, inout float velocity[], float smoothTime, float maxVelocity, float dt) static private
Does the CD smoothing function - easy in | easy out / S shaped smoothing.
Parameters
val actual value
target value we are reaching for -> Target
velocity float[1] - array of ONE member - some kind of memory and actual accel/decel rate, need to be zeroed when filter is about to be reset
smoothTime smoothing parameter, 0.1 .. 0.4 are resonable values, 0.1 is sharp, 0.4 is very smooth
maxVelocity maximal value change when multiplied by dt
dt delta time
Returns
float smoothed/filtered value
val = EnfMath.SmoothCD(val, varTarget, valVelocity, 0.3, 1000, dt);
Referenced by DayZPlayerImplementAiming::ApplyHorizontalNoise(), HitDirectionEffectBase::CalculateArrowPosition(), DayZPlayerCameraBase::HoldBreathFOVEffect(), HoldBreathFOVEffect(), DayZPlayerCameraBase::OnUpdate(), OnUpdate(), DayZPlayerImplementAiming::ProcessStealthFilters(), StdFovUpdate(), NotificationUI::Update(), UpdateLRAngle(), UpdateLRAngleLookAt(), UpdateLRAngleUnlocked(), UpdateUDAngle(), and UpdateUDAngleUnlocked().
SqrFloat()
static proto float Math::SqrFloat (float f) static private
Returns squared value.
Parameters
f float Value
Returns
float - Squared value
Print(Math.SqrFloat(12.5));
>> 156.25
Referenced by ActionTriggerRemotely::ActionCondition(), EvaluateComponentEx(), Environment::GatherTemperatureSources(), GetAttackTypeByDistanceToTarget(), HitZoneSelectionRaycast(), IsPlaceable(), MeleeTargetSettings(), RemoteDetonatorTrigger::OnActivatedByItem(), OnCEUpdate(), RemoteDetonatorTrigger::OnCEUpdate(), Grenade_Base::OnExplosionEffects(), PluginBase::ProcessUniversalTemperatureSources(), and TargetSelection().
SqrInt()
static proto int Math::SqrInt (int i) static private
Returns squared value.
Parameters
i int Value
Returns
int - Squared value
Print(Math.SqrInt(12));
>> 144
Referenced by EffectArea::PlaceParticles().
Sqrt()
static proto float Math::Sqrt (float val) static private
Returns square root.
Parameters
val float Value
Returns
float - Square of value
Print(Math.Sqrt(25));
>> 5
Referenced by SoftSkillsManager::AddExponentialPrecise(), SoftSkillsManager::AddExponentialRough(), DayZIntroScenePC::DayZIntroScenePC(), Easing::EaseInCirc(), Easing::EaseInOutCirc(), Easing::EaseOutCirc(), CGame::OnRPC(), and UIScriptedMenu::Update().
Tan()
static proto float Math::Tan (float angle) static private
Returns tangent of angle in radians.
Parameters
angle float Angle in radians
Returns
float - Tangens of angle
Print(Math.Tan(0.785398)); // (45)
>> 1
Referenced by GetMeleeTarget(), GetMeleeTargetEx(), and PointLightBase::OnFrameLightSource().
WrapFloat()
static proto float Math::WrapFloat (float f, float min, float max) static private
Returns wrap number to specified interval [min, max[.
Parameters
f float Value
min float Minimum
max float Maximum
Returns
float - number in specified interval [min, max[
Print(Math.WrapFloat(9.0, 1.0, 9.0));
>> 1.0
WrapFloat0X()
static proto float Math::WrapFloat0X (float f, float max) static private
Returns wrap number to specified interval [0, max[.
Parameters
f float Value
max float Maximum
Returns
float - number in specified interval [0, max[
Print(Math.WrapFloat0X(9.0, 9.0));
>> 0.0
WrapFloat0XInclusive()
static proto float Math::WrapFloat0XInclusive (float f, float max) static private
Returns wrap number to specified interval [0, max].
Parameters
f float Value
max float Maximum
Returns
float - number in specified interval [0, max]
Print(Math.WrapFloat0X(9.0, 9.0));
>> 9.0
WrapFloatInclusive()
static proto float Math::WrapFloatInclusive (float f, float min, float max) static private
Returns wrap number to specified interval [min, max].
Parameters
f float Value
min float Minimum
max float Maximum
Returns
float - number in specified interval [min, max]
Print(Math.WrapFloatInclusive(9.0, 1.0, 9.0));
>> 9.0
WrapInt()
static proto int Math::WrapInt (int i, int min, int max) static private
Returns wrap number to specified interval [min, max[.
Parameters
i int Value
min float Minimum
max int Maximum
Returns
int - number in specified interval [min, max[
Print(Math.WrapInt(9, 1, 9));
>> 1
Referenced by WeaponStateBase::FindNextFreeMuzzle().
WrapInt0X()
static proto int Math::WrapInt0X (int i, int max) static private
Returns wrap number to specified interval [0, max[.
Parameters
i int Value
max int Maximum
Returns
int - number in specified interval [0, max[
Print(Math.WrapInt0X(9, 9));
>> 0
~Math()
void Math::~Math () inline private
Definition at line 9 of file EnMath.c.
{}
Variable Documentation
DEG2RAD
const float Math::DEG2RAD = 0.01745329251994329577 static private
Definition at line 17 of file EnMath.c.
Referenced by ItemBase::CalcDamageAreaRotation(), HitDirectionEffectBase::CalculateArrowPosition(), GetMeleeTarget(), DayZInfected::HandleOrientation(), Weapon::LiftWeaponCheck(), MeleeTargetSettings(), DayZCreature::ModCommandHandlerBefore(), VicinityItemManager::RefreshVicinityItems(), vector::RotateAroundZeroDeg(), and UIScriptedMenu::SetCameraData().
EULER
const float Math::EULER = 2.7182818284590452353 static private
Definition at line 11 of file EnMath.c.
Referenced by Poisson().
PI
const float Math::PI = 3.14159265358979 static private
Definition at line 12 of file EnMath.c.
Referenced by HitDirectionEffectBase::CalculateArrowPosition(), DayZPlayerImplementHeading::ClampHeading(), Easing::EaseInElastic(), Easing::EaseInOutElastic(), Easing::EaseInOutSine(), Easing::EaseInSine(), Easing::EaseOutElastic(), Easing::EaseOutSine(), fixAngle_PI_PI(), SymptomBase::OnUpdateClient(), Refresh(), DayZPlayerImplementHeading::RotateOrient(), and DeveloperTeleport::SetPlayerPosition().
PI2
const float Math::PI2 = 6.28318530717958 static private
Definition at line 13 of file EnMath.c.
Referenced by HitDirectionEffectBase::CalculateArrowPosition(), ManBase::CheckAnimationOverrides(), DayZPlayerImplementHeading::ClampHeading(), fixAngle_PI_PI(), DayZCreature::ModCommandHandlerBefore(), PointLightBase::OnFrameLightSource(), DayZPlayerCameraBase::OnUpdate(), EffectArea::PlaceParticles(), DayZPlayerImplementHeading::RotateOrient(), BleedingIndicatorDropData::ScatterPosition(), and AnimatorTimer::Tick().
PI_HALF
const float Math::PI_HALF = 1.570796326794 static private
Definition at line 14 of file EnMath.c.
Referenced by DayZPlayerImplementHeading::ClampHeading(), GetHeadingVector(), EntityPlacementCallback::OnSetup(), and DayZPlayerImplementHeading::RotateOrient().
RAD2DEG
const float Math::RAD2DEG = 57.2957795130823208768 static private
Definition at line 16 of file EnMath.c.
Referenced by ActionCreateIndoorFireplace::ActionCondition(), ActionCreateIndoorOven::ActionCondition(), ActionPlaceFireplaceIndoor::ActionCondition(), ActionPlaceOvenIndoor::ActionCondition(), AddArrow(), DayZInfected::AddArrow(), ManBase::AddArrow(), DayZInfected::ComputeHitDirectionAngle(), DayZCreatureAI::ComputeHitDirectionAngleDeg(), DayZInfected::ComputeHitDirectionAngleEx(), DayZIntroScene::DayZIntroScene(), DayZSpectator::EOnFrame(), EvaluateComponentEx(), DayZPlayer::EvaluateDamageHitAnimation(), DayZPlayer::EvaluateDeathAnimation(), EvaluateHit_Player(), DayZInfected::FightLogic(), FloatingCrossHair(), GetAngleInDegrees(), GetMeleeTargetEx(), DayZInfected::HandleOrientation(), IsEntityBehindEntityInAngle(), IsPlayerOrientedTowardPos(), Weapon::LiftWeaponCheck(), PluginBase::OnUpdate(), DayZPlayerCameraBase::OnUpdate(), OnUpdate(), HitDirectionEffectBase::SetIndicatorRotation(), DeveloperTeleport::SetPlayerPosition(), UpdataControllerInput(), Rotator::Update(), ScriptedWidgetEventHandler::Update(), RadialProgressBar::UpdateChild(), UpdateLRAngle(), UpdateLRAngleLookAt(), UpdateLRAngleUnlocked(), ScriptConsoleSoundsTab::UpdateMousePos(), UpdateUDAngle(), and UpdateUDAngleUnlocked().