DayZ: ActionOpenDoors Class Reference
ActionOpenDoors Class Reference
Protected Member Functions
bool CheckIfDoorIsLocked ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStartServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
Private Member Functions
void ActionOpenDoors ()
override void CreateConditionComponents ()
Private Attributes
ref NoiseParams m_NoisePar
Detailed Description
Definition at line 1 of file ActionOpenDoors.c.
Constructor & Destructor Documentation
ActionOpenDoors()
void ActionOpenDoors::ActionOpenDoors () inline private
Definition at line 5 of file ActionOpenDoors.c.
  {
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_OPENDOORFW;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    m_Text = "#open";
  }
References AnimatedActionBase::m_CommandUID, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionOpenDoors::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline protected
Definition at line 23 of file ActionOpenDoors.c.
  {
    if (!target)
      return false;
    if (!IsBuilding(target))
      return false;
    Building building;
    if (Class.CastTo(building, target.GetObject()))
    {
      int doorIndex = building.GetDoorIndex(target.GetComponentIndex());
      if (doorIndex != -1)
      {
        if (!IsInReach(player, target, UAMaxDistances.DEFAULT))
          return false;
        return building.CanDoorBeOpened(doorIndex, CheckIfDoorIsLocked());
      }
    }
    return false;
  }
References Class::CastTo(), CheckIfDoorIsLocked(), UAMaxDistances::DEFAULT, IsBuilding(), and IsInReach().
CheckIfDoorIsLocked()
bool ActionOpenDoors::CheckIfDoorIsLocked () inline protected
Definition at line 18 of file ActionOpenDoors.c.
  {
    return true;
  }
Referenced by ActionCondition(), and OnStartServer().
CreateConditionComponents()
override void ActionOpenDoors::CreateConditionComponents () inline private
Definition at line 12 of file ActionOpenDoors.c.
  {
    m_ConditionItem = new CCINone();
    m_ConditionTarget = new CCTCursor();
  }
References m_ConditionItem, and m_ConditionTarget.
OnEndServer()
override void ActionOpenDoors::OnEndServer (ActionData action_data) inline protected
Definition at line 62 of file ActionOpenDoors.c.
  {
    m_NoisePar = new NoiseParams();
    m_NoisePar.LoadFromPath("CfgVehicles SurvivorBase NoiseActionDefault");
    NoiseSystem noise = GetGame().GetNoiseSystem();
    if (noise)
    {
      if (action_data.m_Player)
        noise.AddNoisePos(action_data.m_Player, action_data.m_Target.GetObject().GetPosition(), m_NoisePar);
    }
  }
References GetGame(), m_NoisePar, and NoiseParams().
OnStartServer()
override void ActionOpenDoors::OnStartServer (ActionData action_data) inline protected
Definition at line 48 of file ActionOpenDoors.c.
  {
    Building building;
    if (Class.CastTo(building, action_data.m_Target.GetObject()))
    {
      int doorIndex = building.GetDoorIndex(action_data.m_Target.GetComponentIndex());
      if (doorIndex != -1)
      {
        if (building.CanDoorBeOpened(doorIndex, CheckIfDoorIsLocked()))
          building.OpenDoor(doorIndex);
      }
    }
  }
References Class::CastTo(), and CheckIfDoorIsLocked().
Member Data Documentation
m_NoisePar
ref NoiseParams ActionOpenDoors::m_NoisePar private
Definition at line 3 of file ActionOpenDoors.c.
Referenced by OnEndServer().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Interact/ActionOpenDoors.c