DayZ: UIMenuPanel Class Reference
UIMenuPanel Class Reference
Part of main menu hierarchy to create custom menus from script.
Private Member Functions
proto native UIMenuPanel GetSubMenu ()
proto native UIMenuPanel GetParentMenu ()
proto native UIMenuPanel GetVisibleMenu ()
proto native void SetSubMenu (UIMenuPanel submenu)
proto native void SetParentMenu (UIMenuPanel parent)
proto native bool CanClose ()
proto native bool CanCloseOnEscape ()
proto native UIScriptedMenu EnterScriptedMenu (int id)
Create & open menu with specific id (see MenuID) and set this menu as its parent.
proto native void DestroySubmenu ()
proto native bool IsAnyMenuVisible ()
proto native bool IsVisible ()
void OnVisibilityChanged (bool isVisible)
proto native void Close ()
Safe way to close window, using this function can even window safely close itself.
bool UseMouse ()
bool UseKeyboard ()
bool UseGamepad ()
int GetID ()
Returns MenuID.
void Refresh ()
Refresh request, called from anywhere.
Widget GetLayoutRoot ()
void LockControls ()
void UnlockControls ()
void UIScriptedMenu ()
void ~UIScriptedMenu ()
void SetID (int id)
Sets MenuID.
override int GetID ()
Returns MenuID.
void SetWidgetAnimAlpha (Widget widget)
Widget Init ()
void Cleanup ()
void OnShow ()
void OnHide ()
void Update (float timeslice)
Per frame update, called from engine.
proto native void SetFadingPanels (Widget panel0, Widget panel1, Widget panel2, Widget panel3, Widget panel4)
Refresh request, called from anywhere.
bool OnClick (Widget w, int x, int y, int button)
bool OnModalResult (Widget w, int x, int y, int code, int result)
bool OnDoubleClick (Widget w, int x, int y, int button)
bool OnSelect (Widget w, int x, int y)
bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
bool OnFocus (Widget w, int x, int y)
bool OnFocusLost (Widget w, int x, int y)
bool OnMouseEnter (Widget w, int x, int y)
bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
bool OnMouseButtonDown (Widget w, int x, int y, int button)
bool OnMouseButtonUp (Widget w, int x, int y, int button)
bool OnMouseWheel (Widget w, int x, int y, int wheel)
bool OnController (Widget w, int control, int value)
bool OnKeyDown (Widget w, int x, int y, int key)
bool OnKeyUp (Widget w, int x, int y, int key)
bool OnKeyPress (Widget w, int x, int y, int key)
bool OnChange (Widget w, int x, int y, bool finished)
bool OnDrag (Widget w, int x, int y)
bool OnDragging (Widget w, int x, int y, Widget reciever)
bool OnDraggingOver (Widget w, int x, int y, Widget reciever)
bool OnDrop (Widget w, int x, int y, Widget reciever)
bool OnDropReceived (Widget w, int x, int y, Widget reciever)
bool OnEvent (EventType eventType, Widget target, int parameter0, int parameter1)
ScriptedWidgetEventHandler GetContextMenu ()
bool OnXboxEvent (int xboxEvent)
void OnRPC (ParamsReadContext ctx)
void OnRPCEx (int rpc_type, ParamsReadContext ctx)
void InitNoteWrite (EntityAI paper, EntityAI pen, string text="")
void InitNoteRead (string text="")
void InitMapItem (EntityAI item)
void LoadMapMarkers ()
Private Member Functions inherited from Managed
void IntroSceneCharacter ()
void ~IntroSceneCharacter ()
bool IsDefaultCharacter ()
void SetToDefaultCharacter ()
void SetCharacterID (int char_id)
int GetCharacterID ()
PlayerBase GetCharacterObj ()
TStringArray GetCharGenderList ()
TStringArray GetCharList (ECharGender gender)
TStringArray GetCharShirtsList ()
TStringArray GetCharPantsList ()
TStringArray GetCharShoesList ()
void SetCharacterGender (ECharGender gender)
bool IsCharacterFemale ()
ECharGender GetCharacterGender ()
vector GetPosition ()
int GetNextCharacterID ()
int GetPrevCharacterID ()
void CreateNewCharacterRandom ()
void CreateNewCharacterById (int character_id)
void CreateNewCharacterByName (string character_name, bool randomize_equip=true)
void CreateDefaultCharacter ()
void GetLastPlayedServer (int characterID, out string address, out string name, out int port)
void CreateNewCharacter ()
void LoadCharacterData (vector char_pos, vector char_rot, bool default_char=false)
Generates random equip for the new IntroSceneCharacter, whatever is defined in 'cfgCharacterCreation'.
void CharacterUnload ()
void CharacterLoad (int character_id, vector char_pos, vector char_rot)
void SetupPlayerName (bool new_name)
void SetAttachment (string type, int slot)
string GetCharacterNameById (int char_id)
string GetCharacterName ()
void SaveCharName (string name)
void SaveDefaultCharacter ()
void TransferValues (PlayerBase player)
void Init ()
void OnScheduledTick (float deltatime)
void CheckValues ()
float GetBlood ()
float GetHealth ()
void CheckHealth ()
void CheckBlood ()
void SendInitValues ()
Sends values on object creation.
void SendValue (int value_type, float value)
void ReceiveValue (int value_type, float value)
void OnRPC (ParamsReadContext ctx)
void ShowDebugValues (bool show)
void BleedingIndicator (int source_ID, int severity, GameplayEffectsDataBleeding parent)
void InitIndicator (vector position)
void StopIndicator (bool instant=false)
void StartRunningDrops ()
bool IsRunningDrops ()
Are any drops currently being animated?
void TrySpawnNextDrop ()
void ResetSequence ()
void ResetIndicator ()
void Update (float timeSlice)
bool GetEndNow ()
int GetSeverity ()
void GameplayEffectsData (array< ref Widget > input, int type, int user_override=-1)
void Init (array< ref Widget > input, int type, Widget layout_root, int user_override=-1)
array< ref Widget > GetWidgetSet ()
int GetWidgetSetType ()
int GetWidgetSetID ()
bool HasDefinedHandle ()
Returns 'true' if this class contains update info.
bool DataInitialized ()
void UpdateVisibility (bool state)
void RegisterData (Param p)
void Update (float timeSlice=0, Param p=null, int handle=-1)
void ForceStop ()
Private Attributes
int m_id
Widget layoutRoot
Widget m_AnimAlphaWidget
bool m_AnimAlphaIsIncreasing
float m_AnimAlphaValue
Private Attributes inherited from Managed
int m_CharacterId
string m_CharacterType
MenuData m_CharacterDta
PlayerBase m_CharacterObj
vector m_CharacterPos
vector m_CharacterRot
ref TStringArray m_CharGenderList = new TStringArray
ref TStringArray m_CharShirtList = new TStringArray
ref TStringArray m_CharPantsList = new TStringArray
ref TStringArray m_CharShoesList = new TStringArray
ref map< ECharGender, ref array< string > > m_Characters = new map<ECharGender, ref array<string>>
ECharGender m_CharGender
bool m_InitialSyncSent
bool m_Initialized
bool m_Terminating = false
bool m_EndNow = false
bool m_IsRunning = false
int m_DropSpawnsQueued
int m_ActiveDropsCount
int m_Severity
int m_SourceID
GameplayEffectsDataBleeding m_ParentMetaData
array< float > m_DropProbabilityArray
float m_AverageFrequency
float m_SequenceTick
float m_SequenceDuration
float m_TimeElapsedTotal
float m_TimeElapsedSequence
float m_LastDropSpawnTime
float m_DropSpawnMinDelay
float m_DropSpawnMaxDelay
int m_CurrentDropProbabilityStep
int m_DropProbabilityRollsCount
vector m_BasePosition
ref set< ref BleedingIndicatorDropData > m_ActiveDrops
ref set< int > m_CleanupQueue
ref array< ref Widget > m_WidgetArray
int m_Type
int m_WidgetSetIdentifier
Widget m_LayoutRoot
Detailed Description
Part of main menu hierarchy to create custom menus from script.
Definition at line 2 of file UIScriptedMenu.c.
Constructor & Destructor Documentation
~UIScriptedMenu()
void UIMenuPanel::~UIScriptedMenu () inline private
Definition at line 129 of file UIScriptedMenu.c.
  {
  }
Member Function Documentation
CanClose()
proto native bool UIMenuPanel::CanClose () private
CanCloseOnEscape()
proto native bool UIMenuPanel::CanCloseOnEscape () private
Cleanup()
void UIMenuPanel::Cleanup () inline private
Definition at line 158 of file UIScriptedMenu.c.
  {
  }
Close()
proto native void UIMenuPanel::Close () private
Safe way to close window, using this function can even window safely close itself.
DestroySubmenu()
proto native void UIMenuPanel::DestroySubmenu () private
EnterScriptedMenu()
proto native UIScriptedMenu UIMenuPanel::EnterScriptedMenu (int id) private
Create & open menu with specific id (see MenuID) and set this menu as its parent.
Referenced by MissionBase::CreateLogoutMenu().
GetContextMenu()
ScriptedWidgetEventHandler UIMenuPanel::GetContextMenu () inline private
Definition at line 519 of file UIScriptedMenu.c.
  {
    return null;
  }
GetID() [1/2]
int UIMenuPanel::GetID () inline private
Returns MenuID.
Definition at line 56 of file UIScriptedMenu.c.
  {
    return MENU_UNKNOWN;
  }
References MENU_UNKNOWN.
GetID() [2/2]
override int UIMenuPanel::GetID () inline private
Returns MenuID.
Definition at line 140 of file UIScriptedMenu.c.
  {
    return m_id;
  }
GetLayoutRoot()
Widget UIMenuPanel::GetLayoutRoot () inline private
Definition at line 77 of file UIScriptedMenu.c.
  {
    return layoutRoot;
  }
GetParentMenu()
proto native UIMenuPanel UIMenuPanel::GetParentMenu () private
GetSubMenu()
proto native UIMenuPanel UIMenuPanel::GetSubMenu () private
GetVisibleMenu()
proto native UIMenuPanel UIMenuPanel::GetVisibleMenu () private
Init()
Widget UIMenuPanel::Init () inline private
Definition at line 153 of file UIScriptedMenu.c.
  {
    return NULL;
  }
InitMapItem()
void UIMenuPanel::InitMapItem (EntityAI item) inline private
Definition at line 534 of file UIScriptedMenu.c.
{}
InitNoteRead()
void UIMenuPanel::InitNoteRead (string text = "") inline private
Definition at line 533 of file UIScriptedMenu.c.
{}
InitNoteWrite()
void UIMenuPanel::InitNoteWrite (EntityAI paper, EntityAI pen, string text = "") inline private
Definition at line 532 of file UIScriptedMenu.c.
{}
IsAnyMenuVisible()
proto native bool UIMenuPanel::IsAnyMenuVisible () private
IsVisible()
proto native bool UIMenuPanel::IsVisible () private
LoadMapMarkers()
void UIMenuPanel::LoadMapMarkers () inline private
Definition at line 535 of file UIScriptedMenu.c.
{}
LockControls()
void UIMenuPanel::LockControls () inline private
Definition at line 82 of file UIScriptedMenu.c.
  {
#ifdef FEATURE_CURSOR
    if (IsCreatedHidden())
      return;
#endif
    if (UseMouse())
    {
      GetGame().GetInput().ChangeGameFocus(1, INPUT_DEVICE_MOUSE);
      GetGame().GetUIManager().ShowUICursor(true);
    }
    if (UseKeyboard())
      GetGame().GetInput().ChangeGameFocus(1, INPUT_DEVICE_KEYBOARD);
    if (UseGamepad())
      GetGame().GetInput().ChangeGameFocus(1, INPUT_DEVICE_GAMEPAD);
  }
References GetGame(), INPUT_DEVICE_GAMEPAD, INPUT_DEVICE_KEYBOARD, INPUT_DEVICE_MOUSE, UIScriptedMenu::UseGamepad(), UIScriptedMenu::UseKeyboard(), and UIScriptedMenu::UseMouse().
OnChange()
bool UIMenuPanel::OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 426 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnChange(w, x, y, finished))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnClick()
bool UIMenuPanel::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 218 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnClick(w, x, y, button))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnController()
bool UIMenuPanel::OnController (Widget w, int control, int value) inline private
Definition at line 374 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnController(w, control, value))
          return true;
      }
    }
    return false;
  }
References Count, and UIScriptedWindow::GetActiveWindows().
OnDoubleClick()
bool UIMenuPanel::OnDoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 244 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnDoubleClick(w, x, y, button))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnDrag()
bool UIMenuPanel::OnDrag (Widget w, int x, int y) inline private
Definition at line 439 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnDrag(w, x, y))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnDragging()
bool UIMenuPanel::OnDragging (Widget w, int x, int y, Widget reciever) inline private
Definition at line 452 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnDragging(w, x, y, reciever))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnDraggingOver()
bool UIMenuPanel::OnDraggingOver (Widget w, int x, int y, Widget reciever) inline private
Definition at line 465 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnDraggingOver(w, x, y, reciever))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnDrop()
bool UIMenuPanel::OnDrop (Widget w, int x, int y, Widget reciever) inline private
Definition at line 478 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnDrop(w, x, y, reciever))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnDropReceived()
bool UIMenuPanel::OnDropReceived (Widget w, int x, int y, Widget reciever) inline private
Definition at line 491 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnDropReceived(w, x, y, reciever))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnEvent()
bool UIMenuPanel::OnEvent (EventType eventType, Widget target, int parameter0, int parameter1) inline private
Definition at line 505 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnEvent(eventType, target, parameter0, parameter1))
          return true;
      }
    }
    return false;
  }
References Count, and UIScriptedWindow::GetActiveWindows().
OnFocus()
bool UIMenuPanel::OnFocus (Widget w, int x, int y) inline private
Definition at line 283 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnFocus(w, x, y))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnFocusLost()
bool UIMenuPanel::OnFocusLost (Widget w, int x, int y) inline private
Definition at line 296 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnFocusLost(w, x, y))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnHide()
void UIMenuPanel::OnHide () inline private
Definition at line 169 of file UIScriptedMenu.c.
  {
    UnlockControls();
  }
OnItemSelected()
bool UIMenuPanel::OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline private
Definition at line 270 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnItemSelected(w, x, y, row, column, oldRow, oldColumn))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnKeyDown()
bool UIMenuPanel::OnKeyDown (Widget w, int x, int y, int key) inline private
Definition at line 387 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnKeyDown(w, x, y, key))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnKeyPress()
bool UIMenuPanel::OnKeyPress (Widget w, int x, int y, int key) inline private
Definition at line 413 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnKeyPress(w, x, y, key))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnKeyUp()
bool UIMenuPanel::OnKeyUp (Widget w, int x, int y, int key) inline private
Definition at line 400 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnKeyUp(w, x, y, key))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnModalResult()
bool UIMenuPanel::OnModalResult (Widget w, int x, int y, int code, int result) inline private
Definition at line 231 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnModalResult(w, x, y, code, result))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnMouseButtonDown()
bool UIMenuPanel::OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 335 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnMouseButtonDown(w, x, y, button))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnMouseButtonUp()
bool UIMenuPanel::OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 348 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnMouseButtonUp(w, x, y, button))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnMouseEnter()
bool UIMenuPanel::OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 309 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnMouseEnter(w, x, y))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnMouseLeave()
bool UIMenuPanel::OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 322 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnMouseLeave(w, enterW, x, y))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnMouseWheel()
bool UIMenuPanel::OnMouseWheel (Widget w, int x, int y, int wheel) inline private
Definition at line 361 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnMouseWheel(w, x, y, wheel))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnRPC()
void UIMenuPanel::OnRPC (ParamsReadContext ctx) inline private
Definition at line 529 of file UIScriptedMenu.c.
{}
OnRPCEx()
void UIMenuPanel::OnRPCEx (int rpc_type, ParamsReadContext ctx) inline private
Definition at line 530 of file UIScriptedMenu.c.
{}
OnSelect()
bool UIMenuPanel::OnSelect (Widget w, int x, int y) inline private
Definition at line 257 of file UIScriptedMenu.c.
  {
    if (UIScriptedWindow.GetActiveWindows())
    {
      for (int i = 0; i < UIScriptedWindow.GetActiveWindows().Count(); i++)
      {
        if (UIScriptedWindow.GetActiveWindows().GetElement(i).OnSelect(w, x, y))
          return true;
      }
    }
    return false;
  }
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnShow()
void UIMenuPanel::OnShow () inline private
Definition at line 163 of file UIScriptedMenu.c.
  {
    LockControls();
  }
OnVisibilityChanged()
void UIMenuPanel::OnVisibilityChanged (bool isVisible) inline private
If visibility of application is changed. On console it is called when application is suspended or constrained.
Parameters
isVisible indicate if application is visible in foreground
Definition at line 25 of file UIScriptedMenu.c.
  {
  }
OnXboxEvent()
bool UIMenuPanel::OnXboxEvent (int xboxEvent) inline private
Definition at line 524 of file UIScriptedMenu.c.
  {
    return true;
  }
Refresh()
void UIMenuPanel::Refresh () inline private
Refresh request, called from anywhere.
Definition at line 62 of file UIScriptedMenu.c.
  {
  }
SetFadingPanels()
proto native void UIMenuPanel::SetFadingPanels (Widget panel0, Widget panel1, Widget panel2, Widget panel3, Widget panel4) private
Refresh request, called from anywhere.
SetID()
void UIMenuPanel::SetID (int id) inline private
Sets MenuID.
Definition at line 134 of file UIScriptedMenu.c.
  {
    m_id = id;
  }
SetParentMenu()
proto native void UIMenuPanel::SetParentMenu (UIMenuPanel parent) private
SetSubMenu()
proto native void UIMenuPanel::SetSubMenu (UIMenuPanel submenu) private
SetWidgetAnimAlpha()
void UIMenuPanel::SetWidgetAnimAlpha (Widget widget) inline private
Definition at line 145 of file UIScriptedMenu.c.
  {
    m_AnimAlphaValue = 0.3;
    m_AnimAlphaWidget = widget;
  }
UIScriptedMenu()
void UIMenuPanel::UIScriptedMenu () inline private
Definition at line 124 of file UIScriptedMenu.c.
  {
    m_id = MENU_UNKNOWN;
  }
References MENU_UNKNOWN.
UnlockControls()
void UIMenuPanel::UnlockControls () inline private
Definition at line 102 of file UIScriptedMenu.c.
  {
#ifdef FEATURE_CURSOR
    if (IsCreatedHidden())
      return;
#endif
    if (UseMouse())
      GetGame().GetInput().ChangeGameFocus(-1, INPUT_DEVICE_MOUSE);
    if (GetParentMenu() && GetParentMenu().UseMouse())
      GetGame().GetUIManager().ShowUICursor(true);
    else
      GetGame().GetUIManager().ShowUICursor(false);
    if (UseKeyboard())
      GetGame().GetInput().ChangeGameFocus(-1, INPUT_DEVICE_KEYBOARD);
    if (UseGamepad())
      GetGame().GetInput().ChangeGameFocus(-1, INPUT_DEVICE_GAMEPAD);
  }
References GetGame(), INPUT_DEVICE_GAMEPAD, INPUT_DEVICE_KEYBOARD, INPUT_DEVICE_MOUSE, UIScriptedMenu::UseGamepad(), UIScriptedMenu::UseKeyboard(), and UIScriptedMenu::UseMouse().
Update()
void UIMenuPanel::Update (float timeslice) inline private
Per frame update, called from engine.
Definition at line 175 of file UIScriptedMenu.c.
  {
#ifdef PLATFORM_CONSOLE
    if (m_AnimAlphaWidget)
    {
      float anim_speed = 1.2;
      float anim_value_max = 1.0;
      float anim_value_min = 0.3;
      if (m_AnimAlphaIsIncreasing)
      {
        m_AnimAlphaValue += anim_speed * timeslice;
        if (m_AnimAlphaValue >= anim_value_max)
        {
          m_AnimAlphaValue = anim_value_max;
          m_AnimAlphaIsIncreasing = false;
        }
      }
      else
      {
        m_AnimAlphaValue -= anim_speed * timeslice;
        if (m_AnimAlphaValue <= anim_value_min)
        {
          m_AnimAlphaValue = anim_value_min;
          m_AnimAlphaIsIncreasing = true;
        }
      }
      m_AnimAlphaWidget.SetAlpha(m_AnimAlphaValue);
    }
#endif
  }
UseGamepad()
bool UIMenuPanel::UseGamepad () inline private
Definition at line 50 of file UIScriptedMenu.c.
  {
    return true;
  }
UseKeyboard()
bool UIMenuPanel::UseKeyboard () inline private
Definition at line 41 of file UIScriptedMenu.c.
  {
#ifdef PLATFORM_CONSOLE
    return GetGame().GetInput().IsEnabledMouseAndKeyboardEvenOnServer();
#else
    return true;
#endif
  }
References GetGame().
UseMouse()
bool UIMenuPanel::UseMouse () inline private
Definition at line 32 of file UIScriptedMenu.c.
  {
#ifdef PLATFORM_CONSOLE
    return GetGame().GetInput().IsEnabledMouseAndKeyboardEvenOnServer();
#else
    return true;
#endif
  }
References GetGame().
Member Data Documentation
layoutRoot
Widget UIMenuPanel::layoutRoot private
Definition at line 72 of file UIScriptedMenu.c.
m_AnimAlphaIsIncreasing
bool UIMenuPanel::m_AnimAlphaIsIncreasing private
Definition at line 74 of file UIScriptedMenu.c.
m_AnimAlphaValue
float UIMenuPanel::m_AnimAlphaValue private
Definition at line 75 of file UIScriptedMenu.c.
m_AnimAlphaWidget
Widget UIMenuPanel::m_AnimAlphaWidget private
Definition at line 73 of file UIScriptedMenu.c.
m_id
int UIMenuPanel::m_id private
Definition at line 71 of file UIScriptedMenu.c.
The documentation for this class was generated from the following file:
scripts/3_Game/tools/UIScriptedMenu.c