DayZ: AreaDamageBase Class Reference
AreaDamageBase Class Reference
Protected Member Functions
void AreaDamageBase (EntityAI parent)
void OnEnter (Object object)
events
void OnEnterClient (Object object)
void OnEnterServer (Object object)
void OnLeave (Object object)
void OnLeaveClient (Object object)
void OnLeaveServer (Object object)
void EvaluateDamage_Loop (Object object)
void EvaluateDamage_Defer (Object object)
void EvaluateDamage_DeferLoop (Object object)
void EvaluateDamage (Object object)
void EvaluateDamage_Common (Object object, string hitzone)
string GetRandomHitZone (array< string > hitzones)
string GetRaycastedHitZone (Object victim, array< string > raycast_sources_str)
Protected Attributes
AreaDamageBase m_AreaDamage
float m_PlayerDamage
float m_OthersDamage
string m_AmmoName
int m_DamageType
float m_LoopInterval
float m_DeferDuration
ref array< string > m_HitZones
ref array< string > m_RaycastSources
ref Timer m_LoopTimer
ref Timer m_DeferTimer
Private Member Functions
void AreaDamageOneTime (EntityAI parent)
void ~AreaDamageOneTime ()
override void SetHitZones (array< string > hitzones)
override void OnEnterServer (Object object)
void AreaDamageOneTimeDeferred (EntityAI parent)
void ~AreaDamageOneTimeDeferred ()
override void SetDeferDuration (float time)
override void SetHitZones (array< string > hitzones)
override void OnEnterServer (Object object)
void AreaDamageOneTimeRaycasted (EntityAI parent)
void ~AreaDamageOneTimeRaycasted ()
override void SetRaycastSources (array< string > raycast_sources)
override void OnEnterServer (Object object)
void AreaDamageOneTimeRaycastedDeferred (EntityAI parent)
void ~AreaDamageOneTimeRaycastedDeferred ()
override void SetDeferDuration (float time)
override void SetRaycastSources (array< string > raycast_sources)
override void OnEnterServer (Object object)
void AreaDamageRegular (EntityAI parent)
void ~AreaDamageRegular ()
override void SetLoopInterval (float time)
override void SetHitZones (array< string > hitzones)
override void OnEnterServer (Object object)
void AreaDamageRegularRaycasted (EntityAI parent)
void ~AreaDamageRegularRaycasted ()
override void SetLoopInterval (float time)
override void SetRaycastSources (array< string > raycast_sources)
override void OnEnterServer (Object object)
void AreaDamageRegularRaycastedDeferred (EntityAI parent)
void ~AreaDamageRegularRaycastedDeferred ()
override void SetLoopInterval (float time)
override void SetDeferDuration (float time)
override void SetRaycastSources (array< string > raycast_sources)
override void OnEnterServer (Object object)
Detailed Description
Definition at line 3 of file AreaDamage.c.
Constructor & Destructor Documentation
AreaDamageBase()
void AreaDamageBase::AreaDamageBase (EntityAI parent) inline protected
Definition at line 23 of file AreaDamage.c.
  {
    m_AreaDamage = this;
    m_PlayerDamage = 0.0;
    m_OthersDamage = 0.0;
    m_AmmoName = "MeleeDamage";
    m_DamageType = DT_CUSTOM;
    m_LoopInterval = 1.0;
    m_DeferDuration = 1.0;
    m_HitZones = new array<string>;
    m_RaycastSources = new array<string>;
    m_DamageableTypes = new array<typename>;
    m_DamageableTypes.Insert(DayZPlayer);
    m_LoopTimer = new Timer(CALL_CATEGORY_SYSTEM);
    m_DeferTimer = new Timer(CALL_CATEGORY_SYSTEM);
    m_TriggerBaseClass = "AreaDamageTrigger";
  }
References CALL_CATEGORY_SYSTEM, m_AmmoName, m_AreaDamage, m_DamageType, m_DeferDuration, m_DeferTimer, m_HitZones, m_LoopInterval, m_LoopTimer, m_OthersDamage, m_PlayerDamage, m_RaycastSources, and m_TriggerBaseClass.
~AreaDamageOneTime()
void AreaDamageBase::~AreaDamageOneTime () inline private
Definition at line 9 of file AreaDamageOneTime.c.
{}
~AreaDamageOneTimeDeferred()
void AreaDamageBase::~AreaDamageOneTimeDeferred () inline private
Definition at line 9 of file AreaDamageOneTimeDeferred.c.
{}
~AreaDamageOneTimeRaycasted()
void AreaDamageBase::~AreaDamageOneTimeRaycasted () inline private
Definition at line 9 of file AreaDamageOneTimeRaycasted.c.
{}
~AreaDamageOneTimeRaycastedDeferred()
void AreaDamageBase::~AreaDamageOneTimeRaycastedDeferred () inline private
Definition at line 9 of file AreaDamageOneTimeRaycastedDeferred.c.
{}
~AreaDamageRegular()
void AreaDamageBase::~AreaDamageRegular () inline private
Definition at line 9 of file AreaDamageRegular.c.
{}
~AreaDamageRegularRaycasted()
void AreaDamageBase::~AreaDamageRegularRaycasted () inline private
Definition at line 9 of file AreaDamageRegularRaycasted.c.
{}
~AreaDamageRegularRaycastedDeferred()
void AreaDamageBase::~AreaDamageRegularRaycastedDeferred () inline private
Definition at line 9 of file AreaDamageRegularRaycastedDeferred.c.
{}
Member Function Documentation
AreaDamageOneTime()
void AreaDamageBase::AreaDamageOneTime (EntityAI parent) inline private
Definition at line 4 of file AreaDamageOneTime.c.
  {
  }
AreaDamageOneTimeDeferred()
void AreaDamageBase::AreaDamageOneTimeDeferred (EntityAI parent) inline private
Definition at line 4 of file AreaDamageOneTimeDeferred.c.
  {
  }
AreaDamageOneTimeRaycasted()
void AreaDamageBase::AreaDamageOneTimeRaycasted (EntityAI parent) inline private
Definition at line 4 of file AreaDamageOneTimeRaycasted.c.
  {
  }
AreaDamageOneTimeRaycastedDeferred()
void AreaDamageBase::AreaDamageOneTimeRaycastedDeferred (EntityAI parent) inline private
Definition at line 4 of file AreaDamageOneTimeRaycastedDeferred.c.
  {
  }
AreaDamageRegular()
void AreaDamageBase::AreaDamageRegular (EntityAI parent) inline private
Definition at line 4 of file AreaDamageRegular.c.
  {
  }
AreaDamageRegularRaycasted()
void AreaDamageBase::AreaDamageRegularRaycasted (EntityAI parent) inline private
Definition at line 4 of file AreaDamageRegularRaycasted.c.
  {
  }
AreaDamageRegularRaycastedDeferred()
void AreaDamageBase::AreaDamageRegularRaycastedDeferred (EntityAI parent) inline private
Definition at line 4 of file AreaDamageRegularRaycastedDeferred.c.
  {
  }
EvaluateDamage()
void AreaDamageBase::EvaluateDamage (Object object) inline protected
Definition at line 91 of file AreaDamage.c.
  {
    string hitzone;
    if (m_RaycastSources.Count())
    {
      hitzone = GetRaycastedHitZone(object, m_RaycastSources);
      EvaluateDamage_Common(object, hitzone);
    }
    else
    {
      hitzone = GetRandomHitZone(m_HitZones);
      EvaluateDamage_Common(object, hitzone);
    }
  }
References EvaluateDamage_Common(), GetRandomHitZone(), GetRaycastedHitZone(), m_HitZones, and m_RaycastSources.
Referenced by OnEnterServer().
EvaluateDamage_Common()
void AreaDamageBase::EvaluateDamage_Common (Object object, string hitzone) inline protected
Definition at line 107 of file AreaDamage.c.
  {
    if (object && object.IsAlive())
    {
      if (object.IsAnyInherited(m_DamageableTypes))
      {
        //If we are hitting an infected or animal, we increase the damage dealt as they do not bleed
        //Change is multiplier
        /*DayZInfected dayzInfected = DayZInfected.Cast(object);
          DayZAnimal dayzAnimal = DayZAnimal.Cast(object);
          EntityAI eai = EntityAI.Cast(object);
          if ( dayzInfected || dayzAnimal )
          {
          //Agents should not take damage from fireplace, but just in case, keep multiplier relatively low
          if ( hitzone )
          {
            eai.ProcessDirectDamage(m_DamageType, EntityAI.Cast(m_ParentObject), hitzone, m_AmmoName, "0.5 0.5 0.5", 8);
          }
          else
            eai.ProcessDirectDamage(m_DamageType, EntityAI.Cast(m_ParentObject), "", m_AmmoName, "0.5 0.5 0.5", 8);
          }
          else*/
        {
          object.ProcessDirectDamage(m_DamageType, m_ParentObject, hitzone, m_AmmoName, "0.5 0.5 0.5", 1);
        }
        PostDamageActions();
      }
    }
  }
References m_AmmoName, m_DamageType, m_ParentObject, and PostDamageActions().
Referenced by EvaluateDamage().
EvaluateDamage_Defer()
void AreaDamageBase::EvaluateDamage_Defer (Object object) inline protected
Definition at line 81 of file AreaDamage.c.
  {
    m_DeferTimer.Run(m_DeferDuration, this, "EvaluateDamage", new Param1<Object>(object), false);
  }
References m_DeferDuration, and m_DeferTimer.
Referenced by OnEnterServer().
EvaluateDamage_DeferLoop()
void AreaDamageBase::EvaluateDamage_DeferLoop (Object object) inline protected
Definition at line 86 of file AreaDamage.c.
  {
    m_DeferTimer.Run(m_DeferDuration, this, "EvaluateDamage_Loop", new Param1<Object>(object), false);
  }
References m_DeferDuration, and m_DeferTimer.
Referenced by OnEnterServer().
EvaluateDamage_Loop()
void AreaDamageBase::EvaluateDamage_Loop (Object object) inline protected
Definition at line 76 of file AreaDamage.c.
  {
    m_LoopTimer.Run(m_LoopInterval, this, "EvaluateDamage", new Param1<Object>(object), true);
  }
References m_LoopInterval, and m_LoopTimer.
Referenced by OnEnterServer().
GetRandomHitZone()
string AreaDamageBase::GetRandomHitZone (array< string > hitzones) inline protected
common
Definition at line 142 of file AreaDamage.c.
  {
    Math.Randomize(-1);
    int idx = Math.RandomInt(0, 100) % hitzones.Count();
    return hitzones[idx];
  }
References Math::RandomInt(), and Math::Randomize().
Referenced by EvaluateDamage().
GetRaycastedHitZone()
string AreaDamageBase::GetRaycastedHitZone (Object victim, array< string > raycast_sources_str) inline protected
Definition at line 150 of file AreaDamage.c.
  {
    // Vertical raycast start positions:    Center,      North East,    North West,    South East,  South West
    //vector raycast_sources[5] = {"0.0 0.1 0.0", "0.2 0.1 0.2", "-.2 0.1 0.2", "0.2 0.1 -.2", "-.2 0.1 -.2"};
    string hitzone;
    vector contact_pos;
    vector contact_dir;
    int contactComponent;
    bool isSteppedOn = false;
    array<vector> raycast_sources = new array<vector>;
    ref set<Object> victims = new set<Object>;
    // convert Array of string to array of Vectors
    for (int v = 0; v < raycast_sources_str.Count(); ++v)
      raycast_sources.Insert(raycast_sources_str[v].ToVector());
    for (int i = 0; i < raycast_sources.Count(); ++i)
    {
      vector raycast_start_pos = m_AreaDamageTrigger.ModelToWorld(raycast_sources.Get(i));
      vector raycast_end_pos = "0 0.5 0" + raycast_start_pos;
      //#ifdef DEVELOPER
      //Debug.DrawArrow( raycast_start_pos, raycast_end_pos );
      //#endif
      DayZPhysics.RaycastRV(raycast_start_pos, raycast_end_pos, contact_pos, contact_dir, contactComponent, victims, null, m_AreaDamageTrigger, true, false, ObjIntersectIFire);
      for (int j = 0; j < victims.Count(); ++j)
      {
        Object contact_obj = victims.Get(j);
        if (contact_obj.IsAnyInherited(m_DamageableTypes))
        {
          isSteppedOn = true;
          break;
        }
      }
      if (isSteppedOn)
      {
        EntityAI eai = EntityAI.Cast(victim);
        if (eai)
        {
          hitzone = eai.GetDamageZoneNameByComponentIndex(contactComponent);
          break;
        }
      }
    }
    if (isSteppedOn)
      return hitzone;
    else
    {
      // Damage random leg since we don't know what part of player's body was caught in the trap.
      string dmg_zone_rnd = "LeftFoot";
      if (Math.RandomIntInclusive(0, 1) == 1)
        dmg_zone_rnd = "RightFoot";
      return dmg_zone_rnd;
    }
  }
References m_AreaDamageTrigger, Math::RandomIntInclusive(), and DayZPhysics::RaycastRV().
Referenced by EvaluateDamage().
OnEnter()
void AreaDamageBase::OnEnter (Object object) inline protected
events
Definition at line 48 of file AreaDamage.c.
  {
    if (GetGame().IsServer())
      OnEnterServer(object);
    else
      OnEnterClient(object);
  }
References GetGame(), OnEnterClient(), and OnEnterServer().
OnEnterClient()
void AreaDamageBase::OnEnterClient (Object object) inline protected
Definition at line 55 of file AreaDamage.c.
{}
Referenced by OnEnter().
OnEnterServer() [1/8]
void AreaDamageBase::OnEnterServer (Object object) inline protected
Definition at line 56 of file AreaDamage.c.
{}
Referenced by OnEnter().
OnEnterServer() [2/8]
override void AreaDamageBase::OnEnterServer (Object object) inline private
Definition at line 16 of file AreaDamageOneTime.c.
  {
    super.OnEnterServer(object);
    EvaluateDamage(object);
  }
References EvaluateDamage().
OnEnterServer() [3/8]
override void AreaDamageBase::OnEnterServer (Object object) inline private
Definition at line 21 of file AreaDamageOneTimeDeferred.c.
  {
    super.OnEnterServer(object);;
    EvaluateDamage_Defer(object);
  }
References EvaluateDamage_Defer().
OnEnterServer() [4/8]
override void AreaDamageBase::OnEnterServer (Object object) inline private
Definition at line 16 of file AreaDamageOneTimeRaycasted.c.
  {
    super.OnEnterServer(object);
    EvaluateDamage(object);
  }
References EvaluateDamage().
OnEnterServer() [5/8]
override void AreaDamageBase::OnEnterServer (Object object) inline private
Definition at line 21 of file AreaDamageOneTimeRaycastedDeferred.c.
  {
    super.OnEnterServer(object);
    EvaluateDamage_Defer(object);
  }
References EvaluateDamage_Defer().
OnEnterServer() [6/8]
override void AreaDamageBase::OnEnterServer (Object object) inline private
Definition at line 21 of file AreaDamageRegular.c.
  {
    super.OnEnterServer(object);
    EvaluateDamage_Loop(object);
  }
OnEnterServer() [7/8]
override void AreaDamageBase::OnEnterServer (Object object) inline private
Definition at line 21 of file AreaDamageRegularRaycasted.c.
  {
    super.OnEnterServer(object);
    EvaluateDamage_Loop(object);
  }
References EvaluateDamage_Loop().
OnEnterServer() [8/8]
override void AreaDamageBase::OnEnterServer (Object object) inline private
Definition at line 26 of file AreaDamageRegularRaycastedDeferred.c.
  {
    super.OnEnterServer(object);
    EvaluateDamage_DeferLoop(object);
  }
References EvaluateDamage_DeferLoop().
OnLeave()
void AreaDamageBase::OnLeave (Object object) inline protected
Definition at line 58 of file AreaDamage.c.
  {
    if (GetGame().IsServer())
      OnLeaveServer(object);
    else
      OnLeaveClient(object);
  }
References GetGame(), OnLeaveClient(), and OnLeaveServer().
OnLeaveClient()
void AreaDamageBase::OnLeaveClient (Object object) inline protected
Definition at line 66 of file AreaDamage.c.
{}
Referenced by OnLeave().
OnLeaveServer()
void AreaDamageBase::OnLeaveServer (Object object) inline protected
stop all running timers
Definition at line 67 of file AreaDamage.c.
  {
    if (m_DeferTimer && m_DeferTimer.IsRunning())
      m_DeferTimer.Stop();
    if (m_LoopTimer && m_LoopTimer.IsRunning())
      m_LoopTimer.Stop();
  }
References m_DeferTimer, and m_LoopTimer.
Referenced by OnLeave().
SetDeferDuration() [1/3]
override void AreaDamageBase::SetDeferDuration (float time) inline private
Definition at line 11 of file AreaDamageOneTimeDeferred.c.
  {
    m_DeferDuration = time;
  }
References m_DeferDuration.
SetDeferDuration() [2/3]
override void AreaDamageBase::SetDeferDuration (float time) inline private
Definition at line 11 of file AreaDamageOneTimeRaycastedDeferred.c.
  {
    m_DeferDuration = time;
  }
References m_DeferDuration.
SetDeferDuration() [3/3]
override void AreaDamageBase::SetDeferDuration (float time) inline private
Definition at line 16 of file AreaDamageRegularRaycastedDeferred.c.
  {
    m_DeferDuration = time;
  }
References m_DeferDuration.
SetHitZones() [1/3]
override void AreaDamageBase::SetHitZones (array< string > hitzones) inline private
Definition at line 11 of file AreaDamageOneTime.c.
  {
    m_HitZones = hitzones;
  }
SetHitZones() [2/3]
override void AreaDamageBase::SetHitZones (array< string > hitzones) inline private
Definition at line 16 of file AreaDamageOneTimeDeferred.c.
  {
    m_HitZones = hitzones;
  }
SetHitZones() [3/3]
override void AreaDamageBase::SetHitZones (array< string > hitzones) inline private
Definition at line 16 of file AreaDamageRegular.c.
  {
    m_HitZones = hitzones;
  }
SetLoopInterval() [1/3]
override void AreaDamageBase::SetLoopInterval (float time) inline private
Definition at line 11 of file AreaDamageRegular.c.
  {
    m_LoopInterval = time;
  }
SetLoopInterval() [2/3]
override void AreaDamageBase::SetLoopInterval (float time) inline private
Definition at line 11 of file AreaDamageRegularRaycasted.c.
  {
    m_LoopInterval = time;
  }
SetLoopInterval() [3/3]
override void AreaDamageBase::SetLoopInterval (float time) inline private
Definition at line 11 of file AreaDamageRegularRaycastedDeferred.c.
  {
    m_LoopInterval = time;
  }
SetRaycastSources() [1/4]
override void AreaDamageBase::SetRaycastSources (array< string > raycast_sources) inline private
Definition at line 11 of file AreaDamageOneTimeRaycasted.c.
  {
    m_RaycastSources = raycast_sources;
  }
SetRaycastSources() [2/4]
override void AreaDamageBase::SetRaycastSources (array< string > raycast_sources) inline private
Definition at line 16 of file AreaDamageOneTimeRaycastedDeferred.c.
  {
    m_RaycastSources = raycast_sources;
  }
SetRaycastSources() [3/4]
override void AreaDamageBase::SetRaycastSources (array< string > raycast_sources) inline private
Definition at line 16 of file AreaDamageRegularRaycasted.c.
  {
    m_RaycastSources = raycast_sources;
  }
SetRaycastSources() [4/4]
override void AreaDamageBase::SetRaycastSources (array< string > raycast_sources) inline private
Definition at line 21 of file AreaDamageRegularRaycastedDeferred.c.
  {
    m_RaycastSources = raycast_sources;
  }
Member Data Documentation
m_AmmoName
string AreaDamageBase::m_AmmoName protected
Definition at line 10 of file AreaDamage.c.
Referenced by AreaDamageBase(), and EvaluateDamage_Common().
m_AreaDamage
AreaDamageBase AreaDamageBase::m_AreaDamage protected
Definition at line 5 of file AreaDamage.c.
Referenced by AreaDamageBase().
m_DamageType
int AreaDamageBase::m_DamageType protected
Definition at line 11 of file AreaDamage.c.
Referenced by AreaDamageBase(), and EvaluateDamage_Common().
m_DeferDuration
float AreaDamageBase::m_DeferDuration protected
Definition at line 14 of file AreaDamage.c.
Referenced by AreaDamageBase(), EvaluateDamage_Defer(), and EvaluateDamage_DeferLoop().
m_DeferTimer
ref Timer AreaDamageBase::m_DeferTimer protected
Definition at line 21 of file AreaDamage.c.
Referenced by AreaDamageBase(), EvaluateDamage_Defer(), EvaluateDamage_DeferLoop(), and OnLeaveServer().
m_HitZones
ref array<string> AreaDamageBase::m_HitZones protected
Definition at line 16 of file AreaDamage.c.
Referenced by AreaDamageBase(), and EvaluateDamage().
m_LoopInterval
float AreaDamageBase::m_LoopInterval protected
Definition at line 13 of file AreaDamage.c.
Referenced by AreaDamageBase(), and EvaluateDamage_Loop().
m_LoopTimer
ref Timer AreaDamageBase::m_LoopTimer protected
Definition at line 20 of file AreaDamage.c.
Referenced by AreaDamageBase(), EvaluateDamage_Loop(), and OnLeaveServer().
m_OthersDamage
float AreaDamageBase::m_OthersDamage protected
Definition at line 8 of file AreaDamage.c.
Referenced by AreaDamageBase().
m_PlayerDamage
float AreaDamageBase::m_PlayerDamage protected
Definition at line 7 of file AreaDamage.c.
Referenced by AreaDamageBase().
m_RaycastSources
ref array<string> AreaDamageBase::m_RaycastSources protected
Definition at line 17 of file AreaDamage.c.
Referenced by AreaDamageBase(), and EvaluateDamage().
The documentation for this class was generated from the following files:
scripts/4_World/Classes/AreaDamage/AreaDamage.c
scripts/4_World/Classes/AreaDamage/AreaDamageOneTime.c
scripts/4_World/Classes/AreaDamage/AreaDamageOneTimeDeferred.c
scripts/4_World/Classes/AreaDamage/AreaDamageOneTimeRaycasted.c
scripts/4_World/Classes/AreaDamage/AreaDamageOneTimeRaycastedDeferred.c
scripts/4_World/Classes/AreaDamage/AreaDamageRegular.c
scripts/4_World/Classes/AreaDamage/AreaDamageRegularRaycasted.c
scripts/4_World/Classes/AreaDamage/AreaDamageRegularRaycastedDeferred.c