DayZ: GameplayEffectWidgets_base Class Reference
GameplayEffectWidgets_base Class Reference
grouped gameplay effect widgets and their handling
Protected Member Functions
void GameplayEffectWidgets ()
void ~GameplayEffectWidgets ()
void RegisterLayouts (string path, array< int > types)
Registers new layout and ties effect IDs to it.
void PairIDToTypes ()
TranslateIDToType (int typeID)
override void RegisterGameplayEffectData (int id, Param p)
void InitWidgetSet (int type, bool updating=false, int user_id_override=-1)
InitWidgetSet.
bool CreateHandledClass (typename handled_type, array< ref Widget > input, int type, int user_override)
array< int > CompileEffectListing ()
returns all vanilla effects, nested in a vanilla layout. If using different layouts for custom effects, please register and link separately
void UpdateVisibility ()
override void AddActiveEffects (array< int > effects)
override void RemoveActiveEffects (array< int > effects)
override void StopAllEffects ()
override bool IsAnyEffectRunning ()
override void AddSuspendRequest (int request_id)
override void RemoveSuspendRequest (int request_id)
override void ClearSuspendRequests ()
override int GetSuspendRequestCount ()
override void UpdateWidgets (int type=-1, float timeSlice=0, Param p=null, int handle=-1)
Usually called in course of an OnFrame update, can be manually called from elsewhere with parameters.
void CalculateValues (int type=-1, float timeSlice=0, Param p=null, int handle=-1)
Only one calculation per unique WidgetSet.
void ProcessWidgetUpdate (Widget w, int type, float timeSlice=0, Param p=null, int handle=-1)
void CalculateBreathEffect (float timeSlice=0, int type=-1, Param p=null)
void UpdateBreathEffect (ImageWidget w)
void CalculateOccluderEffect (int type, float timeSlice, Param p, int handle)
void UpdateOccluderEffect (ImageWidget w, int type, float timeSlice, Param p, int handle)
void CalculateFlashbangEffect (int type, float timeSlice, Param p, int handle)
void UpdateFlashbangEffect (ImageWidget w)
void HandleWidgetRoot (float timeSlice=0, Param p=null, int handle=-1)
override void Update (float timeSlice)
Generic update, called on frame from the player.
override void OnVoiceEvent (float breathing_resistance01)
Protected Attributes
ref Widget m_Root
ref map< int, ref Widget > m_Layouts
ref set< ref Widget > m_UniqueLayouts
ref GameplayEffectDataMap m_WidgetDataMap
ref set< int > m_RunningEffects
ref set< int > m_RunningEffectsPrevious
ref array< int > m_UpdatingEffects
ref array< ref Widget > m_UpdatedWidgetsCheck
ref array< int > m_UpdatedWidgetSetsCheck
ref set< int > m_SuspendRequests
ref map< int, typename > m_IDToTypeMap
float m_TimeProgBreath
float m_BreathMultStamina
float m_BreathResidue
const int WIDGETSET_BREATH = 100
int m_BreathColor
float m_BreathAlphaVal
float m_FlashbangCoverAlphaVal
const float BREATH_HDR_MIN = 0.005
const float BREATH_HDR_MAX = 1.0
const float BREATH_COLOR_MULT_MIN = 0.5
const float BREATH_COLOR_MULT_MAX = 0.8
Detailed Description
grouped gameplay effect widgets and their handling
Definition at line 6 of file GameplayEffectWidgets.c.
Constructor & Destructor Documentation
~GameplayEffectWidgets()
void GameplayEffectWidgets_base::~GameplayEffectWidgets () inline protected
Definition at line 73 of file GameplayEffectWidgets.c.
  {
    for (int i = 0; i < m_Layouts.Count(); i++)
    {
      if (m_Layouts.GetElement(i))
        m_Layouts.GetElement(i).Unlink();
    }
  }
Member Function Documentation
AddActiveEffects()
override void GameplayEffectWidgets_base::AddActiveEffects (array< int > effects) inline protected
Definition at line 263 of file GameplayEffectWidgets.c.
  {
    if (effects && effects.Count() > 0)
    {
      m_RunningEffectsPrevious.Copy(m_RunningEffects);
      int value;
      for (int i = 0; i < effects.Count(); i++)
      {
        value = effects.Get(i);
        m_RunningEffects.Insert(value);
      }
      if (m_RunningEffectsPrevious.Count() != m_RunningEffects.Count())
        UpdateVisibility();
    }
  }
References UpdateVisibility().
Referenced by ManBase::OnCommandHandlerTick().
AddSuspendRequest()
override void GameplayEffectWidgets_base::AddSuspendRequest (int request_id) inline protected
Definition at line 327 of file GameplayEffectWidgets.c.
  {
    m_SuspendRequests.Insert(request_id);
    UpdateVisibility();
  }
References UpdateVisibility().
Referenced by ManBase::OnUnconsciousStart().
CalculateBreathEffect()
void GameplayEffectWidgets_base::CalculateBreathEffect (float timeSlice = 0, int type = -1, Param p = null) inline protected
Definition at line 509 of file GameplayEffectWidgets.c.
  {
    float modifier = Math.Lerp(0.25, 0.5, m_BreathResidue);
    float speed = timeSlice * modifier;
    m_BreathResidue -= speed;
    m_BreathResidue = Math.Clamp(m_BreathResidue, 0, 1);
    float residue_final = Math.Lerp(0, 0.7, m_BreathResidue);
    float hdr_mult;
    hdr_mult = GetSceneHDRMul(0);
    hdr_mult = Math.Clamp(hdr_mult, BREATH_HDR_MIN, BREATH_HDR_MAX);
    hdr_mult = Math.InverseLerp(BREATH_HDR_MIN, BREATH_HDR_MAX, hdr_mult);
    hdr_mult = Math.Lerp(BREATH_COLOR_MULT_MAX, BREATH_COLOR_MULT_MIN, hdr_mult);
    m_BreathColor = ARGBF(0.0, 1.0 * hdr_mult, 1.0 * hdr_mult, 1.0 * hdr_mult); //grayscaling of the image
    m_BreathAlphaVal = Math.Lerp(m_BreathAlphaVal, residue_final, timeSlice);
  }
References ARGBF(), Math::Clamp(), GetSceneHDRMul(), Math::InverseLerp(), and Math::Lerp().
Referenced by CalculateValues().
CalculateFlashbangEffect()
void GameplayEffectWidgets_base::CalculateFlashbangEffect (int type, float timeSlice, Param p, int handle) inline protected
Definition at line 548 of file GameplayEffectWidgets.c.
  {
    Param1<float> par = Param1<float>.Cast(p);
    m_FlashbangCoverAlphaVal = par.param1;
    /*if (m_FlashbangCoverAlphaVal <= 0.0)
      {
      RemoveActiveEffects({EffectWidgetsTypes.COVER_FLASHBANG});
      return;
      }*/
  }
Referenced by CalculateValues().
CalculateOccluderEffect()
void GameplayEffectWidgets_base::CalculateOccluderEffect (int type, float timeSlice, Param p, int handle) inline protected
Definition at line 537 of file GameplayEffectWidgets.c.
  {
  }
Referenced by CalculateValues().
CalculateValues()
void GameplayEffectWidgets_base::CalculateValues (int type = -1, float timeSlice = 0, Param p = null, int handle = -1) inline protected
Only one calculation per unique WidgetSet.
Definition at line 422 of file GameplayEffectWidgets.c.
  {
    if (m_UpdatedWidgetSetsCheck.Find(m_WidgetDataMap.Get(type).GetWidgetSetID()) != -1)
    {
      //Print("skipped updating set ID " + m_WidgetDataMap.Get(type).GetWidgetSetID() + " | effect: " + type);
      return;
    }
    switch (type)
    {
    case EffectWidgetsTypes.MOTO_BREATH:
    case EffectWidgetsTypes.HELMET_BREATH:
    case EffectWidgetsTypes.MASK_BREATH:
    {
      CalculateBreathEffect(timeSlice);
    }
    break;
    case EffectWidgetsTypes.MOTO_OCCLUDER:
    case EffectWidgetsTypes.EYEPATCH_OCCLUDER:
    case EffectWidgetsTypes.HELMET_OCCLUDER:
    case EffectWidgetsTypes.HELMET2_OCCLUDER:
    case EffectWidgetsTypes.MASK_OCCLUDER:
    {
      CalculateOccluderEffect(type, timeSlice, p, handle);
    }
    break;
    case EffectWidgetsTypes.COVER_FLASHBANG:
    {
      CalculateFlashbangEffect(type, timeSlice, p, handle);
    }
    break;
    default:
      return; //no need to calculate anything
      break;
    }
    m_UpdatedWidgetSetsCheck.Insert(m_WidgetDataMap.Get(type).GetWidgetSetID());
  }
References CalculateBreathEffect(), CalculateFlashbangEffect(), and CalculateOccluderEffect().
Referenced by UpdateWidgets().
ClearSuspendRequests()
override void GameplayEffectWidgets_base::ClearSuspendRequests () inline protected
Definition at line 341 of file GameplayEffectWidgets.c.
  {
    m_SuspendRequests.Clear();
    UpdateVisibility();
  }
References UpdateVisibility().
Referenced by ManBase::SimulateDeath().
CompileEffectListing()
array< int > GameplayEffectWidgets_base::CompileEffectListing () inline protected
returns all vanilla effects, nested in a vanilla layout. If using different layouts for custom effects, please register and link separately
Definition at line 181 of file GameplayEffectWidgets.c.
  {
    array<int> ret = new array<int>;
    ret.Insert(EffectWidgetsTypes.MASK_OCCLUDER);
    ret.Insert(EffectWidgetsTypes.MASK_BREATH);
    ret.Insert(EffectWidgetsTypes.HELMET_OCCLUDER);
    ret.Insert(EffectWidgetsTypes.HELMET_BREATH);
    ret.Insert(EffectWidgetsTypes.MOTO_OCCLUDER);
    ret.Insert(EffectWidgetsTypes.MOTO_BREATH);
    ret.Insert(EffectWidgetsTypes.COVER_FLASHBANG);
    ret.Insert(EffectWidgetsTypes.NVG_OCCLUDER);
    ret.Insert(EffectWidgetsTypes.PUMPKIN_OCCLUDER);
    ret.Insert(EffectWidgetsTypes.EYEPATCH_OCCLUDER);
    ret.Insert(EffectWidgetsTypes.HELMET2_OCCLUDER);
    return ret;
  }
Referenced by GameplayEffectWidgets().
CreateHandledClass()
bool GameplayEffectWidgets_base::CreateHandledClass (typename handled_type , array< ref Widget > input, int type, int user_override) inline protected
Definition at line 168 of file GameplayEffectWidgets.c.
  {
    if (handled_type)
    {
      GameplayEffectsData data = GameplayEffectsData.Cast(handled_type.Spawn());
      data.Init(input, type, m_Layouts.Get(type), user_override);
      m_WidgetDataMap.Set(type, data);
      return true;
    }
    return false;
  }
Referenced by InitWidgetSet().
GameplayEffectWidgets()
void GameplayEffectWidgets_base::GameplayEffectWidgets () inline protected
Definition at line 32 of file GameplayEffectWidgets.c.
  {
    m_Root = GetGame().GetWorkspace().CreateWidget(FrameWidgetTypeID, 0, 0, 1.0, 1.0, WidgetFlags.VISIBLE | WidgetFlags.HEXACTPOS | WidgetFlags.VEXACTPOS, 0xffffffff, 0);
    m_Layouts = new map<int, ref Widget>;
    m_UniqueLayouts = new set<ref Widget>;
    m_WidgetDataMap = new GameplayEffectDataMap;
    m_RunningEffects = new set<int>;
    m_RunningEffectsPrevious = new set<int>;
    m_UpdatingEffects = new array<int>;
    m_UpdatedWidgetsCheck = new array<ref Widget>;
    m_UpdatedWidgetSetsCheck = new array<int>;
    m_SuspendRequests = new set<int>;
    m_IDToTypeMap = new map<int, typename>;
    m_TimeProgBreath = 0.0;
    m_BreathMultStamina = 1.0;
    PairIDToTypes();
    RegisterLayouts("gui/layouts/gameplay/CameraEffects.layout", CompileEffectListing());
    RegisterLayouts("gui/layouts/gameplay/BleedingEffects.layout", {EffectWidgetsTypes.BLEEDING_LAYER});
    InitWidgetSet(EffectWidgetsTypes.MASK_BREATH, true, WIDGETSET_BREATH);
    InitWidgetSet(EffectWidgetsTypes.HELMET_BREATH, true, WIDGETSET_BREATH);
    InitWidgetSet(EffectWidgetsTypes.MOTO_BREATH, true, WIDGETSET_BREATH);
    InitWidgetSet(EffectWidgetsTypes.MASK_OCCLUDER, false, EffectWidgetsTypes.MASK_OCCLUDER);
    InitWidgetSet(EffectWidgetsTypes.HELMET_OCCLUDER);
    InitWidgetSet(EffectWidgetsTypes.HELMET2_OCCLUDER);
    InitWidgetSet(EffectWidgetsTypes.MOTO_OCCLUDER);
    InitWidgetSet(EffectWidgetsTypes.NVG_OCCLUDER, false, EffectWidgetsTypes.NVG_OCCLUDER);
    InitWidgetSet(EffectWidgetsTypes.PUMPKIN_OCCLUDER, false, EffectWidgetsTypes.NVG_OCCLUDER);
    InitWidgetSet(EffectWidgetsTypes.EYEPATCH_OCCLUDER);
    InitWidgetSet(EffectWidgetsTypes.COVER_FLASHBANG);
    InitWidgetSet(EffectWidgetsTypes.BLEEDING_LAYER, true);
    UpdateVisibility();
  }
References CompileEffectListing(), GetGame(), InitWidgetSet(), m_Root, PairIDToTypes(), RegisterLayouts(), and UpdateVisibility().
GetSuspendRequestCount()
override int GameplayEffectWidgets_base::GetSuspendRequestCount () inline protected
Definition at line 347 of file GameplayEffectWidgets.c.
  {
    return m_SuspendRequests.Count();
  }
HandleWidgetRoot()
void GameplayEffectWidgets_base::HandleWidgetRoot (float timeSlice = 0, Param p = null, int handle = -1) inline protected
Definition at line 568 of file GameplayEffectWidgets.c.
  {
    switch (handle)
    {
    default:
    {
      Param1<float> par = Param1<float>.Cast(p);
      if (par)
      {
        float alpha_mod = Math.Clamp(par.param1, 0.0, 1.0);
        //Print(alpha_mod);
        m_Root.SetAlpha(alpha_mod);
      }
    }
    break;
    }
  }
References Math::Clamp(), and m_Root.
Referenced by UpdateWidgets().
InitWidgetSet()
void GameplayEffectWidgets_base::InitWidgetSet (int type, bool updating = false, int user_id_override = -1) inline protected
InitWidgetSet.
Parameters
type int ID of effect widget type
updating bool Marks widgets for 'PlayerBase.EOnFrame' updating
user_id_override int UserID of a widget to be used instead (allows multiple types to use single widget)
InitWidgetSet(EffectWidgetsTypes.MASK_BREATH,true,BREATH);
Note
All child widgets MUST be of the same type if special functionality is required (ImageWidget etc.)
Definition at line 121 of file GameplayEffectWidgets.c.
  {
    Widget parent = null;
    if (user_id_override != -1)
      parent = m_Layouts.Get(type).FindAnyWidgetById(user_id_override);
    else
      parent = m_Layouts.Get(type).FindAnyWidgetById(type);
    if (!parent)
    {
      Print("InitWidgetSet | type: " + type + " - parent not found!");
      return;
    }
    array<ref Widget> output;
    Widget w = parent.GetChildren();
    if (w)
    {
      output = new array<ref Widget>;
      while (w)
      {
        w.Update();
        w.Show(false, true);
        output.Insert(w);
        w = w.GetSibling();
      }
      if (parent.GetChildren())
      {
        typename handled_type = TranslateIDToType(type);
        if (handled_type)
          CreateHandledClass(handled_type, output, type, user_id_override);
        else
        {
          if (ImageWidget.Cast(parent.GetChildren()))
            m_WidgetDataMap.Set(type, new GameplayEffectsDataImage(output, type, user_id_override));
          else
            m_WidgetDataMap.Set(type, new GameplayEffectsData(output, type, user_id_override));
        }
      }
      if (updating)
        m_UpdatingEffects.Insert(type);
    }
  }
References CreateHandledClass(), GameplayEffectsDataImage(), Print(), and TranslateIDToType().
Referenced by GameplayEffectWidgets().
IsAnyEffectRunning()
override bool GameplayEffectWidgets_base::IsAnyEffectRunning () inline protected
Definition at line 322 of file GameplayEffectWidgets.c.
  {
    return m_RunningEffects && m_RunningEffects.Count() > 0;
  }
Referenced by ManBase::EOnFrame(), and StopAllEffects().
OnVoiceEvent()
override void GameplayEffectWidgets_base::OnVoiceEvent (float breathing_resistance01) inline protected
Definition at line 616 of file GameplayEffectWidgets.c.
  {
    m_BreathResidue += Math.Lerp(0, 0.35, breathing_resistance01);
    m_BreathResidue = Math.Clamp(m_BreathResidue, 0, 1);
  }
References Math::Clamp(), and Math::Lerp().
Referenced by ManBase::UpdateMaskBreathWidget().
PairIDToTypes()
void GameplayEffectWidgets_base::PairIDToTypes () inline protected
Definition at line 95 of file GameplayEffectWidgets.c.
  {
    m_IDToTypeMap.Insert(EffectWidgetsTypes.BLEEDING_LAYER, GameplayEffectsDataBleeding);
  }
Referenced by GameplayEffectWidgets().
ProcessWidgetUpdate()
void GameplayEffectWidgets_base::ProcessWidgetUpdate (Widget w, int type, float timeSlice = 0, Param p = null, int handle = -1) inline protected
Definition at line 464 of file GameplayEffectWidgets.c.
  {
    switch (type)
    {
    case EffectWidgetsTypes.MOTO_BREATH:
    case EffectWidgetsTypes.HELMET_BREATH:
    case EffectWidgetsTypes.MASK_BREATH:
    {
      UpdateBreathEffect(ImageWidget.Cast(w));
    }
    break;
    case EffectWidgetsTypes.MOTO_OCCLUDER:
    case EffectWidgetsTypes.EYEPATCH_OCCLUDER:
    case EffectWidgetsTypes.HELMET_OCCLUDER:
    case EffectWidgetsTypes.HELMET2_OCCLUDER:
    case EffectWidgetsTypes.MASK_OCCLUDER:
    {
      UpdateOccluderEffect(ImageWidget.Cast(w), type, timeSlice, p, handle);
    }
    break;
    case EffectWidgetsTypes.COVER_FLASHBANG:
    {
      UpdateFlashbangEffect(ImageWidget.Cast(w));
    }
    break;
    default:
      //Print("---invalid widget type to update---");
      break;
    }
  }
References UpdateBreathEffect(), UpdateFlashbangEffect(), and UpdateOccluderEffect().
Referenced by UpdateWidgets().
RegisterGameplayEffectData()
override void GameplayEffectWidgets_base::RegisterGameplayEffectData (int id, Param p) inline protected
Definition at line 105 of file GameplayEffectWidgets.c.
  {
    if (!m_WidgetDataMap.Get(id).DataInitialized())
      m_WidgetDataMap.Get(id).RegisterData(p);
  }
RegisterLayouts()
void GameplayEffectWidgets_base::RegisterLayouts (string path, array< int > types) inline protected
Registers new layout and ties effect IDs to it.
Note
Order of layout creation matters, they get layered on top of each other. Within a single layout, widget priorities govern the widget order.
Definition at line 86 of file GameplayEffectWidgets.c.
  {
    Widget w = GetGame().GetWorkspace().CreateWidgets(path, m_Root, false);
    m_UniqueLayouts.Insert(w);
    w.Show(false);
    foreach (int i : types)
      m_Layouts.Set(i, w);
  }
References GetGame(), m_Root, and path.
Referenced by GameplayEffectWidgets().
RemoveActiveEffects()
override void GameplayEffectWidgets_base::RemoveActiveEffects (array< int > effects) inline protected
Definition at line 281 of file GameplayEffectWidgets.c.
  {
    if (effects && effects.Count() > 0)
    {
      m_RunningEffectsPrevious.Copy(m_RunningEffects);
      int value;
      int idx;
      for (int i = 0; i < effects.Count(); i++)
      {
        value = effects.Get(i);
        idx = m_RunningEffects.Find(value);
        if (idx != -1)
          m_RunningEffects.Remove(idx);
      }
      if (m_RunningEffectsPrevious.Count() != m_RunningEffects.Count())
        UpdateVisibility();
    }
  }
References UpdateVisibility().
Referenced by ManBase::OnCommandHandlerTick().
RemoveSuspendRequest()
override void GameplayEffectWidgets_base::RemoveSuspendRequest (int request_id) inline protected
Definition at line 333 of file GameplayEffectWidgets.c.
  {
    int idx = m_SuspendRequests.Find(request_id);
    if (idx != -1)
      m_SuspendRequests.Remove(idx);
    UpdateVisibility();
  }
References UpdateVisibility().
Referenced by ManBase::OnUnconsciousStop().
StopAllEffects()
override void GameplayEffectWidgets_base::StopAllEffects () inline protected
Definition at line 302 of file GameplayEffectWidgets.c.
  {
    m_Root.Show(false); //to avoid visual 'peeling'
    if (IsAnyEffectRunning())
    {
      int count = m_RunningEffects.Count();
      GameplayEffectsData data;
      for (int i = 0; i < count; i++) //iterates over running metadata, in case anything requires its own stop handling
      {
        data = m_WidgetDataMap.Get(m_RunningEffects[i]);
        data.ForceStop();
      }
    }
    m_RunningEffectsPrevious.Copy(m_RunningEffects);
    m_RunningEffects.Clear();
    UpdateVisibility();
  }
References IsAnyEffectRunning(), m_Root, and UpdateVisibility().
Referenced by ManBase::SimulateDeath().
TranslateIDToType()
GameplayEffectWidgets_base::TranslateIDToType (int typeID) inline protected
Definition at line 100 of file GameplayEffectWidgets.c.
  {
    return m_IDToTypeMap.Get(typeID);
  }
Referenced by InitWidgetSet().
Update()
override void GameplayEffectWidgets_base::Update (float timeSlice) inline protected
Generic update, called on frame from the player.
Definition at line 588 of file GameplayEffectWidgets.c.
  {
    if (m_SuspendRequests.Count() > 0)
      return;
    UpdateWidgets(-1, timeSlice);
  }
References UpdateWidgets().
Referenced by ManBase::EOnFrame().
UpdateBreathEffect()
void GameplayEffectWidgets_base::UpdateBreathEffect (ImageWidget w) inline protected
Definition at line 528 of file GameplayEffectWidgets.c.
  {
    w.SetColor(m_BreathColor);
    w.SetAlpha(m_BreathAlphaVal);
  }
Referenced by ProcessWidgetUpdate().
UpdateFlashbangEffect()
void GameplayEffectWidgets_base::UpdateFlashbangEffect (ImageWidget w) inline protected
Definition at line 560 of file GameplayEffectWidgets.c.
  {
    w.SetAlpha(1 - m_FlashbangCoverAlphaVal);
  }
Referenced by ProcessWidgetUpdate().
UpdateOccluderEffect()
void GameplayEffectWidgets_base::UpdateOccluderEffect (ImageWidget w, int type, float timeSlice, Param p, int handle) inline protected
Definition at line 541 of file GameplayEffectWidgets.c.
  {
  }
Referenced by ProcessWidgetUpdate().
UpdateVisibility()
void GameplayEffectWidgets_base::UpdateVisibility () inline protected
Definition at line 199 of file GameplayEffectWidgets.c.
  {
    Widget w;
    //Hide diff
    int value;
    int runningEffectCount = m_RunningEffects.Count();
    bool runningEffectsPresent = runningEffectCount > 0;
    GameplayEffectsData dta;
    for (int i = 0; i < m_RunningEffectsPrevious.Count(); i++)
    {
      value = m_RunningEffectsPrevious.Get(i);
      dta = m_WidgetDataMap.Get(value);
      if (runningEffectCount < 1 || m_RunningEffects.Find(value) == -1)
      {
        if (dta.HasDefinedHandle())
          dta.UpdateVisibility(false);
        else
        {
          for (int j = 0; j < m_WidgetDataMap.Get(value).GetWidgetSet().Count(); j++)
          {
            w = m_WidgetDataMap.Get(value).GetWidgetSet().Get(j);
            w.Show(false);
          }
          w.GetParent().Show(false);
        }
      }
    }
    //Show running effects
    if (runningEffectsPresent)
    {
      value = 0;
      for (i = 0; i < runningEffectCount; i++)
      {
        value = m_RunningEffects.Get(i);
        dta = m_WidgetDataMap.Get(value);
        if (dta.HasDefinedHandle())
        {
          dta.m_LayoutRoot.Show(true);
          dta.UpdateVisibility(true);
        }
        else
        {
          for (j = 0; j < m_WidgetDataMap.Get(value).GetWidgetSet().Count(); j++)
          {
            w = m_WidgetDataMap.Get(value).GetWidgetSet().Get(j);
            w.Update();
            w.Show(true);
          }
          while (w) //dumb but necessary because of uncertain "visible" setting of the layout
          {
            w = w.GetParent();
            if (w)
              w.Show(true);
          }
        }
      }
    }
    m_Root.Show(runningEffectsPresent && m_SuspendRequests.Count() < 1);
    m_RunningEffectsPrevious.Clear();
  }
References Count, and m_Root.
Referenced by AddActiveEffects(), AddSuspendRequest(), ClearSuspendRequests(), GameplayEffectWidgets(), RemoveActiveEffects(), RemoveSuspendRequest(), and StopAllEffects().
UpdateWidgets()
override void GameplayEffectWidgets_base::UpdateWidgets (int type = -1, float timeSlice = 0, Param p = null, int handle = -1) inline protected
Usually called in course of an OnFrame update, can be manually called from elsewhere with parameters.
Definition at line 353 of file GameplayEffectWidgets.c.
  {
    GameplayEffectsData dta;
    array<ref Widget> widget_set;
    if (type == EffectWidgetsTypes.ROOT)
      HandleWidgetRoot(timeSlice, p, handle);
    else if (type == -1) //update stuff from the m_UpdatingEffects
    {
      int type_widgetset = 0;
      for (int i = 0; i < m_UpdatingEffects.Count(); i++)
      {
        if (m_RunningEffects.Find(m_UpdatingEffects.Get(i)) != -1)
        {
          type_widgetset = m_UpdatingEffects.Get(i);
          dta = m_WidgetDataMap.Get(type_widgetset);
          if (dta.HasDefinedHandle() && dta.DataInitialized())
          {
            dta.Update(timeSlice, p, handle); //calculate and apply
          }
          else
          {
            CalculateValues(type_widgetset, timeSlice, p, handle);
            widget_set = dta.GetWidgetSet();
            foreach (Widget w : widget_set)
            {
              if (w.IsVisibleHierarchy() && m_UpdatedWidgetsCheck.Find(w) == -1)
              {
                m_UpdatedWidgetsCheck.Insert(w);
                ProcessWidgetUpdate(w, type_widgetset, timeSlice, p, handle);
              }
            }
          }
        }
      }
    }
    else //update specific widget set
    {
      if (m_RunningEffects.Find(type) != -1) //only do if the effect is running (FPS stonks!)
      {
        dta = m_WidgetDataMap.Get(type);
        if (dta.HasDefinedHandle() && dta.DataInitialized())
        {
          dta.Update(timeSlice, p, handle); //calculate and apply
        }
        else
        {
          CalculateValues(type, timeSlice, p, handle);
          widget_set = dta.GetWidgetSet();
          foreach (Widget w2 : widget_set)
          {
            if (w2.IsVisibleHierarchy() && m_UpdatedWidgetsCheck.Find(w2) == -1)
            {
              m_UpdatedWidgetsCheck.Insert(w2);
              ProcessWidgetUpdate(w2, type, timeSlice, p, handle);
            }
          }
        }
      }
    }
    m_UpdatedWidgetsCheck.Clear();
    m_UpdatedWidgetSetsCheck.Clear();
  }
References CalculateValues(), HandleWidgetRoot(), and ProcessWidgetUpdate().
Referenced by ScriptedWidgetEventHandler::OnBleedingIndicationChanged(), and Update().
Member Data Documentation
BREATH_COLOR_MULT_MAX
const float GameplayEffectWidgets_base::BREATH_COLOR_MULT_MAX = 0.8 protected
Definition at line 504 of file GameplayEffectWidgets.c.
BREATH_COLOR_MULT_MIN
const float GameplayEffectWidgets_base::BREATH_COLOR_MULT_MIN = 0.5 protected
Definition at line 503 of file GameplayEffectWidgets.c.
BREATH_HDR_MAX
const float GameplayEffectWidgets_base::BREATH_HDR_MAX = 1.0 protected
Definition at line 502 of file GameplayEffectWidgets.c.
BREATH_HDR_MIN
const float GameplayEffectWidgets_base::BREATH_HDR_MIN = 0.005 protected
Definition at line 501 of file GameplayEffectWidgets.c.
m_BreathAlphaVal
float GameplayEffectWidgets_base::m_BreathAlphaVal protected
Definition at line 29 of file GameplayEffectWidgets.c.
m_BreathColor
int GameplayEffectWidgets_base::m_BreathColor protected
Definition at line 28 of file GameplayEffectWidgets.c.
m_BreathMultStamina
float GameplayEffectWidgets_base::m_BreathMultStamina protected
Definition at line 21 of file GameplayEffectWidgets.c.
m_BreathResidue
float GameplayEffectWidgets_base::m_BreathResidue protected
Definition at line 22 of file GameplayEffectWidgets.c.
m_FlashbangCoverAlphaVal
float GameplayEffectWidgets_base::m_FlashbangCoverAlphaVal protected
Definition at line 30 of file GameplayEffectWidgets.c.
m_IDToTypeMap
ref map<int, typename> GameplayEffectWidgets_base::m_IDToTypeMap protected
Definition at line 18 of file GameplayEffectWidgets.c.
m_Layouts
ref map<int, ref Widget> GameplayEffectWidgets_base::m_Layouts protected
Definition at line 9 of file GameplayEffectWidgets.c.
m_Root
ref Widget GameplayEffectWidgets_base::m_Root protected
Definition at line 8 of file GameplayEffectWidgets.c.
m_RunningEffects
ref set<int> GameplayEffectWidgets_base::m_RunningEffects protected
Definition at line 12 of file GameplayEffectWidgets.c.
m_RunningEffectsPrevious
ref set<int> GameplayEffectWidgets_base::m_RunningEffectsPrevious protected
Definition at line 13 of file GameplayEffectWidgets.c.
m_SuspendRequests
ref set<int> GameplayEffectWidgets_base::m_SuspendRequests protected
Definition at line 17 of file GameplayEffectWidgets.c.
m_TimeProgBreath
float GameplayEffectWidgets_base::m_TimeProgBreath protected
Definition at line 20 of file GameplayEffectWidgets.c.
m_UniqueLayouts
ref set<ref Widget> GameplayEffectWidgets_base::m_UniqueLayouts protected
Definition at line 10 of file GameplayEffectWidgets.c.
m_UpdatedWidgetsCheck
ref array<ref Widget> GameplayEffectWidgets_base::m_UpdatedWidgetsCheck protected
Definition at line 15 of file GameplayEffectWidgets.c.
m_UpdatedWidgetSetsCheck
ref array<int> GameplayEffectWidgets_base::m_UpdatedWidgetSetsCheck protected
Definition at line 16 of file GameplayEffectWidgets.c.
m_UpdatingEffects
ref array<int> GameplayEffectWidgets_base::m_UpdatingEffects protected
Definition at line 14 of file GameplayEffectWidgets.c.
m_WidgetDataMap
ref GameplayEffectDataMap GameplayEffectWidgets_base::m_WidgetDataMap protected
Definition at line 11 of file GameplayEffectWidgets.c.
WIDGETSET_BREATH
const int GameplayEffectWidgets_base::WIDGETSET_BREATH = 100 protected
Definition at line 25 of file GameplayEffectWidgets.c.
The documentation for this class was generated from the following file:
scripts/5_Mission/mission/GameplayEffectWidgets/GameplayEffectWidgets.c