DayZ: ActionDeployBase Class Reference
ActionDeployBase Class Reference
Protected Member Functions
void ActionDeployBase ()
override void CreateConditionComponents ()
override bool HasTarget ()
override bool HasProgress ()
override ActionData CreateActionData ()
override void OnFinishProgressServer (ActionData action_data)
void DropDuringPlacing (PlayerBase player)
void MoveEntityToFinalPosition (ActionData action_data, vector position, vector orientation)
void MoveEntityToFinalPositionSinglePlayer (ActionData action_data, InventoryLocation source, InventoryLocation destination)
Protected Attributes
const float POSITION_OFFSET = 0.5
Additional Inherited Members
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 19 of file ActionDeployBase.c.
Constructor & Destructor Documentation
ActionDeployBase()
void ActionDeployBase::ActionDeployBase () inline protected
Definition at line 23 of file ActionDeployBase.c.
  {
    m_CallbackClass = ActiondeployObjectCB;
    m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
    m_FullBody = true;
    m_Text = "#deploy_object";
  }
References AnimatedActionBase::m_CallbackClass, m_FullBody, m_SpecialtyWeight, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
CreateActionData()
override ActionData ActionDeployBase::CreateActionData () inline protected
Definition at line 48 of file ActionDeployBase.c.
  {
    PlaceObjectActionData action_data = new PlaceObjectActionData();
    return action_data;
  }
CreateConditionComponents()
override void ActionDeployBase::CreateConditionComponents () inline protected
Definition at line 32 of file ActionDeployBase.c.
  {
    m_ConditionItem = new CCINone();
    m_ConditionTarget = new CCTNone();
  }
References m_ConditionItem, and m_ConditionTarget.
DropDuringPlacing()
void ActionDeployBase::DropDuringPlacing (PlayerBase player) inline protected
Definition at line 102 of file ActionDeployBase.c.
  {
    ItemBase item;
    if (!Class.CastTo(item, player.GetItemInHands()))
      return;
    if (item.IsBasebuildingKit())
      return;
    player.PredictiveDropEntity(item);
  }
References Class::CastTo().
HasProgress()
override bool ActionDeployBase::HasProgress () inline protected
Definition at line 43 of file ActionDeployBase.c.
  {
    return true;
  }
HasTarget()
override bool ActionDeployBase::HasTarget () inline protected
Definition at line 38 of file ActionDeployBase.c.
  {
    return false;
  }
MoveEntityToFinalPosition()
void ActionDeployBase::MoveEntityToFinalPosition (ActionData action_data, vector position, vector orientation) inline protected
Definition at line 114 of file ActionDeployBase.c.
  {
    if (action_data.m_MainItem.IsBasebuildingKit())
      return;
    EntityAI entity_for_placing = action_data.m_MainItem;
    vector rotation_matrix[3];
    float direction[4];
    InventoryLocation source = new InventoryLocation;
    InventoryLocation destination = new InventoryLocation;
    Math3D.YawPitchRollMatrix(orientation, rotation_matrix);
    Math3D.MatrixToQuat(rotation_matrix, direction);
    if (entity_for_placing.GetInventory().GetCurrentInventoryLocation(source))
    {
      destination.SetGroundEx(entity_for_placing, position, direction);
      if (GetGame().IsMultiplayer())
        action_data.m_Player.ServerTakeToDst(source, destination);
      else // singleplayer
        MoveEntityToFinalPositionSinglePlayer(action_data, source, destination);
    }
  }
References GetGame(), Math3D::MatrixToQuat(), MoveEntityToFinalPositionSinglePlayer(), and Math3D::YawPitchRollMatrix().
Referenced by OnFinishProgressServer().
MoveEntityToFinalPositionSinglePlayer()
void ActionDeployBase::MoveEntityToFinalPositionSinglePlayer (ActionData action_data, InventoryLocation source, InventoryLocation destination) inline protected
Definition at line 140 of file ActionDeployBase.c.
  {
    action_data.m_Player.GetInventory().TakeToDst(InventoryMode.LOCAL, source, destination);
  }
Referenced by MoveEntityToFinalPosition().
OnFinishProgressServer()
override void ActionDeployBase::OnFinishProgressServer (ActionData action_data) inline protected
Definition at line 54 of file ActionDeployBase.c.
  {
    PlaceObjectActionData poActionData;
    poActionData = PlaceObjectActionData.Cast(action_data);
    if (!poActionData)
      return;
    if (!action_data.m_MainItem)
      return;
    EntityAI entity_for_placing = action_data.m_MainItem;
    vector position;
    vector orientation;
    // In case of placement with hologram
    if (action_data.m_Player.GetHologramServer())
    {
      position = action_data.m_Player.GetLocalProjectionPosition();
      orientation = action_data.m_Player.GetLocalProjectionOrientation();
      action_data.m_Player.GetHologramServer().EvaluateCollision(action_data.m_MainItem);
      if (GetGame().IsMultiplayer() && action_data.m_Player.GetHologramServer().IsColliding())
        return;
      action_data.m_Player.GetHologramServer().PlaceEntity(entity_for_placing);
      if (GetGame().IsMultiplayer())
        action_data.m_Player.GetHologramServer().CheckPowerSource();
    }
    else
    {
      position = action_data.m_Player.GetPosition();
      orientation = action_data.m_Player.GetOrientation();
      position = position + (action_data.m_Player.GetDirection() * POSITION_OFFSET);
    }
    action_data.m_Player.PlacingCompleteServer();
    entity_for_placing.OnPlacementComplete(action_data.m_Player, position, orientation);
    MoveEntityToFinalPosition(action_data, position, orientation);
    GetGame().ClearJunctureEx(action_data.m_Player, entity_for_placing);
    action_data.m_MainItem.SetIsBeingPlaced(false);
    action_data.m_Player.GetSoftSkillsManager().AddSpecialty(m_SpecialtyWeight);
    poActionData.m_AlreadyPlaced = true;
    action_data.m_MainItem.SoundSynchRemoteReset();
  }
References GetGame(), m_SpecialtyWeight, MoveEntityToFinalPosition(), and POSITION_OFFSET.
Member Data Documentation
POSITION_OFFSET
const float ActionDeployBase::POSITION_OFFSET = 0.5 protected
Definition at line 21 of file ActionDeployBase.c.
Referenced by OnFinishProgressServer().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/DeployActions/ActionDeployBase.c