DayZ: FireworksLauncher Class Reference
FireworksLauncher Class Reference
Protected Member Functions
bool UsesGlobalDeploy ()
override bool IsDeployable ()
override float GetDeployTime ()
how long it takes to deploy this item in seconds
void SetupColorSequences ()
string GetColorSequence ()
void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
float GetMaxAllowedWetness ()
float GetEventDelay ()
string GetFuseSoundSet ()
int GetMaxShots ()
float GetFuseDelay ()
string GetAmmoType ()
int GetDamageType ()
void OnStateChangedServer (EFireworksState currentState)
void OnStateChangedClient (EFireworksState currentState)
override void OnIgnitedThis (EntityAI fire_source)
Executed on Server when some item ignited this one.
bool CanPutInCargo (EntityAI parent)
bool CanPutIntoHands (EntityAI parent)
void OnFuseIgnitedServer ()
void OnFuseIgnitedClient ()
void OnFiringStartServer ()
void OnFiringStartClient ()
void OnFiringStop ()
void RestartEventTimer ()
Starts event timer.
bool IsIgnited ()
bool CanIgniteItem (EntityAI ignite_target=NULL)
void OnEventServer (int type)
Called periodically but only after the entity gets ignited.
void OnIndexChangedClient ()
FireworksLauncherClientEventBase SpawnEvent ()
void OnVariablesSynchronized ()
void OnStoreSave (ParamsWriteContext ctx)
bool OnStoreLoad (ParamsReadContext ctx, int version)
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
Private Member Functions
void FireworksLauncher ()
void ~FireworksLauncher ()
Private Attributes
int m_Index
int m_IndexPrev
int m_ColorSequenceIndex
ref Timer m_TimerFuse
ref array< ref FireworksLauncherClientEventBase > m_Events
EffectSound m_FuseSoundStart
EffectSound m_FuseSound
ParticleSource m_ParticleFuse
ParticleSource m_ParticleAfterBurnEnd
ref array< string > m_ColorSequence
Detailed Description
Definition at line 311 of file FireworksLauncher.c.
Constructor & Destructor Documentation
FireworksLauncher()
void FireworksLauncher::FireworksLauncher () inline private
Definition at line 324 of file FireworksLauncher.c.
  {
    m_ColorSequence = new array<string>();
    SetupColorSequences();
    RegisterNetSyncVariableInt("m_State", 0, EnumTools.GetLastEnumValue(EFireworksState));
    RegisterNetSyncVariableInt("m_Index", 0, GetMaxShots());
    RegisterNetSyncVariableInt("m_RandomSeed", 0, 1023);
    int lastIndex = m_ColorSequence.Count() - 1;
    RegisterNetSyncVariableInt("m_ColorSequenceIndex", 0, lastIndex);
    m_RandomSeed = Math.RandomInt(0, 1023);
    m_ColorSequenceIndex = Math.RandomIntInclusive(0, lastIndex);
  }
References EnumTools::GetLastEnumValue(), GetMaxShots(), m_ColorSequence, m_ColorSequenceIndex, m_RandomSeed, Math::RandomInt(), Math::RandomIntInclusive(), and SetupColorSequences().
~FireworksLauncher()
void FireworksLauncher::~FireworksLauncher () inline private
Definition at line 337 of file FireworksLauncher.c.
  {
    SEffectManager.DestroyEffect(m_FuseSound);
    SEffectManager.DestroyEffect(m_FuseSoundStart);
  }
References SEffectManager::DestroyEffect(), m_FuseSound, and m_FuseSoundStart.
Member Function Documentation
CanIgniteItem()
bool FireworksLauncher::CanIgniteItem (EntityAI ignite_target = NULL) inline protected
Definition at line 559 of file FireworksLauncher.c.
  {
    return false;
  }
CanPutInCargo()
bool FireworksLauncher::CanPutInCargo (EntityAI parent) inline protected
Definition at line 482 of file FireworksLauncher.c.
  {
    return (GetState() == EFireworksState.DEFAULT || (GetState() == EFireworksState.PLACED) || (GetState() == EFireworksState.FINISHED);
  }
References GetState().
CanPutIntoHands()
bool FireworksLauncher::CanPutIntoHands (EntityAI parent) inline protected
Definition at line 487 of file FireworksLauncher.c.
  {
    return (GetState() == EFireworksState.DEFAULT || (GetState() == EFireworksState.PLACED) || (GetState() == EFireworksState.FINISHED);
  }
References GetState().
GetAmmoType()
string FireworksLauncher::GetAmmoType () inline protected
Definition at line 423 of file FireworksLauncher.c.
  {
    return "Fireworks_Ammo";
  }
Referenced by OnEventServer(), and Anniversary_FireworksLauncher::OnEventServer().
GetColorSequence()
string FireworksLauncher::GetColorSequence () inline protected
Definition at line 375 of file FireworksLauncher.c.
  {
    if (m_ColorSequence.IsValidIndex(m_ColorSequenceIndex))
      return m_ColorSequence.Get(m_ColorSequenceIndex);
    else
    {
      ErrorEx("Failed to obtain color sequence");
      return "RYPBYYPBRGBYPBRGBRBGBPBRGRGBRBGRYPYR";
    }
  }
References ErrorEx, m_ColorSequence, and m_ColorSequenceIndex.
Referenced by FireworksLauncherClientEvent::FireworksLauncherClientEvent().
GetDamageType()
int FireworksLauncher::GetDamageType () inline protected
Definition at line 428 of file FireworksLauncher.c.
  {
    return DamageType.EXPLOSION;
  }
Referenced by OnEventServer(), and Anniversary_FireworksLauncher::OnEventServer().
GetDeploySoundset()
override string FireworksLauncher::GetDeploySoundset () inline protected
Definition at line 638 of file FireworksLauncher.c.
  {
    return "placeFireworks_SoundSet";
  }
GetDeployTime()
override float FireworksLauncher::GetDeployTime () inline protected
how long it takes to deploy this item in seconds
Definition at line 354 of file FireworksLauncher.c.
  {
    return 2;
  }
GetEventDelay()
float FireworksLauncher::GetEventDelay () inline protected
Definition at line 403 of file FireworksLauncher.c.
  {
    return Math.RandomFloatInclusive(3, 3.35);
  }
References Math::RandomFloatInclusive().
Referenced by RestartEventTimer().
GetFuseDelay()
float FireworksLauncher::GetFuseDelay () inline protected
Definition at line 418 of file FireworksLauncher.c.
  {
    return 3;
  }
Referenced by OnFuseIgnitedServer().
GetFuseSoundSet()
string FireworksLauncher::GetFuseSoundSet () inline protected
Definition at line 408 of file FireworksLauncher.c.
  {
    return "FireworksLauncher_Ignition_Loop_SoundSet";
  }
Referenced by OnFuseIgnitedClient().
GetLoopDeploySoundset()
override string FireworksLauncher::GetLoopDeploySoundset () inline protected
Definition at line 643 of file FireworksLauncher.c.
  {
    return "fireworks_deploy_SoundSet";
  }
GetMaxAllowedWetness()
float FireworksLauncher::GetMaxAllowedWetness () inline protected
Definition at line 397 of file FireworksLauncher.c.
  {
    return GameConstants.STATE_WET;
  }
References GameConstants::STATE_WET.
GetMaxShots()
int FireworksLauncher::GetMaxShots () inline protected
Definition at line 413 of file FireworksLauncher.c.
  {
    return 16;
  }
Referenced by FireworksLauncher(), and OnEventServer().
IsDeployable()
override bool FireworksLauncher::IsDeployable () inline protected
Definition at line 348 of file FireworksLauncher.c.
  {
    return true;
  }
IsIgnited()
bool FireworksLauncher::IsIgnited () inline protected
Definition at line 554 of file FireworksLauncher.c.
  {
    return GetState() == EFireworksState.IGNITED;
  }
References GetState().
OnEventServer()
void FireworksLauncher::OnEventServer (int type) inline protected
Called periodically but only after the entity gets ignited.
Definition at line 566 of file FireworksLauncher.c.
  {
    m_Index++;
    DamageSystem.ExplosionDamage(this, NULL, GetAmmoType(), GetPosition(), GetDamageType());
    SetSynchDirty();
    if (m_Index > GetMaxShots())
    {
      m_Index = GetMaxShots();
      m_TimerEvent = null;
      SetState(EFireworksState.FINISHED);
    }
    else
      RestartEventTimer();
  }
References GetAmmoType(), GetDamageType(), GetMaxShots(), GetPosition, m_Index, m_TimerEvent, RestartEventTimer(), and SetState().
Referenced by OnFiringStartServer().
OnFiringStartClient()
void FireworksLauncher::OnFiringStartClient () inline protected
Definition at line 532 of file FireworksLauncher.c.
  {
    if (m_ParticleFuse)
      m_ParticleFuse.StopParticle(StopParticleFlags.IMMEDIATE);
    if (m_FuseSound)
      m_FuseSound.Stop();
  }
References m_FuseSound, m_ParticleFuse, EffectSound::Stop(), and ParticleSource::StopParticle().
Referenced by OnStateChangedClient().
OnFiringStartServer()
void FireworksLauncher::OnFiringStartServer () inline protected
Definition at line 527 of file FireworksLauncher.c.
  {
    OnEventServer(0);
  }
References OnEventServer().
Referenced by OnStateChangedServer().
OnFiringStop()
void FireworksLauncher::OnFiringStop () inline protected
Definition at line 540 of file FireworksLauncher.c.
  {
    SetHealth01("", "", 0);
  }
OnFuseIgnitedClient()
void FireworksLauncher::OnFuseIgnitedClient () inline protected
Definition at line 498 of file FireworksLauncher.c.
  {
    m_ParticleFuse = ParticleManager.GetInstance().PlayInWorld(ParticleList.FIREWORKS_FUSE, GetPosition() + "0 0.15 0");
    if (m_ParticleFuse)
      m_ParticleFuse.SetOwner(this);
    PlaySoundSet(m_FuseSoundStart, "FireworksLauncher_Ignition_Start_SoundSet", 0, 0);
    vector fuseStart;
    vector fuseEnd;
    if (MemoryPointExists("Fuse_Start"))
    {
      fuseStart = GetMemoryPointPos("Fuse_Start");
      fuseStart = ModelToWorld(fuseStart);
    }
    if (MemoryPointExists("Fuse_End"))
    {
      fuseEnd = GetMemoryPointPos("Fuse_End");
      fuseEnd = ModelToWorld(fuseEnd);
    }
    vector fuseDir = fuseEnd - fuseStart;
    vector fuseOrientation[4];
    vector ori = fuseDir.VectorToAngles();
    m_ParticleFuse.SetOrientation(ori);
    m_ParticleFuse.SetPosition(fuseStart);
    PlaySoundSetLoop(m_FuseSound, GetFuseSoundSet(), 0, 0);
  }
References ParticleList::FIREWORKS_FUSE, GetFuseSoundSet(), GetPosition, m_FuseSound, m_FuseSoundStart, m_ParticleFuse, ParticleManager(), and ParticleSource::SetOwner().
Referenced by OnStateChangedClient().
OnFuseIgnitedServer()
void FireworksLauncher::OnFuseIgnitedServer () inline protected
Definition at line 492 of file FireworksLauncher.c.
  {
    int state = EFireworksState.FIRING;
    GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(SetState, GetFuseDelay() * 1000, false, state);
  }
References CALL_CATEGORY_SYSTEM, GetFuseDelay(), GetGame(), and SetState().
Referenced by OnStateChangedServer().
OnIgnitedThis()
override void FireworksLauncher::OnIgnitedThis (EntityAI fire_source) inline protected
Executed on Server when some item ignited this one.
Definition at line 471 of file FireworksLauncher.c.
  {
    super.OnIgnitedThis(fire_source);
    if (m_Events)
      m_Events.Clear();
    m_Index = 0;
    if (m_TimerEvent)
      m_TimerEvent.Stop();
  }
References m_Events, m_Index, and m_TimerEvent.
OnIndexChangedClient()
void FireworksLauncher::OnIndexChangedClient () inline protected
Definition at line 582 of file FireworksLauncher.c.
  {
    if (!m_Events)
      m_Events = new array<ref FireworksLauncherClientEventBase>;
    if (m_Index != 0 && m_State == EFireworksState.FIRING)//can only be true when restarting the device during debug calls
    {
      FireworksLauncherClientEventBase fireEvent = SpawnEvent();
      m_Events.Insert(fireEvent);
    }
  }
References m_Events, m_Index, m_State, and SpawnEvent().
Referenced by OnVariablesSynchronized().
OnPlacementComplete()
void FireworksLauncher::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline protected
Definition at line 387 of file FireworksLauncher.c.
  {
    super.OnPlacementComplete(player, position, orientation);
    if (GetGame().IsServer())
    {
      if (GetState() == EFireworksState.DEFAULT)
        SetState(EFireworksState.PLACED);
    }
  }
References GetGame(), GetState(), and SetState().
OnStateChangedClient()
void FireworksLauncher::OnStateChangedClient (EFireworksState currentState) inline protected
Definition at line 454 of file FireworksLauncher.c.
  {
    switch (currentState)
    {
    case EFireworksState.IGNITED:
      OnFuseIgnitedClient();
      break
    case EFireworksState.PLACED:
      break
    case EFireworksState.FIRING:
      OnFiringStartClient();
      break
    default: {};
    }
  }
References OnFiringStartClient(), and OnFuseIgnitedClient().
OnStateChangedServer()
void FireworksLauncher::OnStateChangedServer (EFireworksState currentState) inline protected
Definition at line 434 of file FireworksLauncher.c.
  {
    switch (currentState)
    {
    case EFireworksState.PLACED:
      break
    case EFireworksState.IGNITED:
      OnFuseIgnitedServer();
      break
    case EFireworksState.FIRING:
      HideSelection("cover");
      OnFiringStartServer();
      break
    case EFireworksState.FINISHED:
      HideSelection("cover");//when loading from storage
      break
    default: {};
    }
  }
References OnFiringStartServer(), and OnFuseIgnitedServer().
OnStoreLoad()
bool FireworksLauncher::OnStoreLoad (ParamsReadContext ctx, int version) inline protected
Definition at line 620 of file FireworksLauncher.c.
  {
    if (!super.OnStoreLoad(ctx, version))
      return false;
    if (version >= 130)
    {
      if (!ctx.Read(m_Index))
        return false;
      if (!ctx.Read(m_State))
        return false;
      SetState(m_State);
    }
    return true;
  }
References m_Index, m_State, and SetState().
OnStoreSave()
void FireworksLauncher::OnStoreSave (ParamsWriteContext ctx) inline protected
Definition at line 612 of file FireworksLauncher.c.
  {
    super.OnStoreSave(ctx);
    ctx.Write(m_Index);
    ctx.Write(m_State);
  }
References m_Index, and m_State.
OnVariablesSynchronized()
void FireworksLauncher::OnVariablesSynchronized () inline protected
Definition at line 600 of file FireworksLauncher.c.
  {
    super.OnVariablesSynchronized();
    //Print("index: " + m_Index);
    if (m_Index != m_IndexPrev)
    {
      Math.Randomize(m_RandomSeed + m_Index);
      OnIndexChangedClient();
      m_IndexPrev = m_Index;
    }
  }
References m_Index, m_IndexPrev, m_RandomSeed, OnIndexChangedClient(), and Math::Randomize().
RestartEventTimer()
void FireworksLauncher::RestartEventTimer () inline protected
Starts event timer.
Definition at line 546 of file FireworksLauncher.c.
  {
    if (!m_TimerEvent)
      m_TimerEvent = new Timer();
    m_TimerEvent.Run(GetEventDelay(), this, "OnEventServer", new Param1<int>(0));
  }
References GetEventDelay(), and m_TimerEvent.
Referenced by OnEventServer(), and Anniversary_FireworksLauncher::OnEventServer().
SetupColorSequences()
void FireworksLauncher::SetupColorSequences () inline protected
Definition at line 359 of file FireworksLauncher.c.
  {
    m_ColorSequence.Insert("RGBYPBRGBRGBYPBRGBRGBYPBRGBPBRGBRGBY");
    m_ColorSequence.Insert("PGPYPBYPYPBYYPBRPYPBYYPBRGBPBRGRGBRB");
    m_ColorSequence.Insert("YPBRPYPBYYPBRGBPBRGRGBRBGRPBRGBRYPBY");
    m_ColorSequence.Insert("YRBGPRYPGRYBGRGRGBRBBYPYPBYRYPGRYGRP");
    m_ColorSequence.Insert("BGRYPYRPBYYPYRBGPRYPGBYPBRGBPBRGBRGB");
    m_ColorSequence.Insert("RYGRPBRGBYPBRRPBRGBBRBBYPYPRGBRGBRPY");
    m_ColorSequence.Insert("GBRGBYRGBYPBRRPBRBYRYPGPYPRGBRGBRPYG");
    m_ColorSequence.Insert("RYPBYYPBRGBYPBRGBRBGBPBRGRGBRBGRYPYR");
    m_ColorSequence.Insert("PBRGBYPBRGBRBGBPBRGRGBRBGRYPYRRYPBYY");
    m_ColorSequence.Insert("RGRGBRBBYPYPBYRYPGRYGRPYRBGPRYPGRYBG");
    m_ColorSequence.Insert("RBYRYPGPYPRGBRGBRPYGGBRGBYRGBYPBRRPB");
    m_ColorSequence.Insert("PRGBRGBRPYGGBRRBYRYPGPYGBYRGBYPBRRPB");
  }
References m_ColorSequence.
Referenced by FireworksLauncher().
SpawnEvent()
FireworksLauncherClientEventBase FireworksLauncher::SpawnEvent () inline protected
Definition at line 593 of file FireworksLauncher.c.
  {
    FireworksLauncherClientEventBase evnt = new FireworksLauncherClientEvent(this, m_Index);
    evnt.OnFired();
    return evnt;
  }
References m_Index.
Referenced by OnIndexChangedClient().
UsesGlobalDeploy()
bool FireworksLauncher::UsesGlobalDeploy () inline protected
Definition at line 343 of file FireworksLauncher.c.
  {
    return true;
  }
Member Data Documentation
m_ColorSequence
ref array<string> FireworksLauncher::m_ColorSequence private
Definition at line 322 of file FireworksLauncher.c.
Referenced by FireworksLauncher(), GetColorSequence(), SetupColorSequences(), and Anniversary_FireworksLauncher::SetupColorSequences().
m_ColorSequenceIndex
int FireworksLauncher::m_ColorSequenceIndex private
Definition at line 315 of file FireworksLauncher.c.
Referenced by FireworksLauncher(), and GetColorSequence().
m_Events
ref array<ref FireworksLauncherClientEventBase> FireworksLauncher::m_Events private
Definition at line 317 of file FireworksLauncher.c.
Referenced by OnIgnitedThis(), and OnIndexChangedClient().
m_FuseSound
EffectSound FireworksLauncher::m_FuseSound private
Definition at line 319 of file FireworksLauncher.c.
Referenced by OnFiringStartClient(), OnFuseIgnitedClient(), and ~FireworksLauncher().
m_FuseSoundStart
EffectSound FireworksLauncher::m_FuseSoundStart private
Definition at line 318 of file FireworksLauncher.c.
Referenced by OnFuseIgnitedClient(), and ~FireworksLauncher().
m_Index
int FireworksLauncher::m_Index private
Definition at line 313 of file FireworksLauncher.c.
Referenced by OnEventServer(), Anniversary_FireworksLauncher::OnEventServer(), OnIgnitedThis(), OnIndexChangedClient(), OnStoreLoad(), OnStoreSave(), OnVariablesSynchronized(), SpawnEvent(), and Anniversary_FireworksLauncher::SpawnEvent().
m_IndexPrev
int FireworksLauncher::m_IndexPrev private
Definition at line 314 of file FireworksLauncher.c.
Referenced by OnVariablesSynchronized().
m_ParticleAfterBurnEnd
ParticleSource FireworksLauncher::m_ParticleAfterBurnEnd private
Definition at line 321 of file FireworksLauncher.c.
m_ParticleFuse
ParticleSource FireworksLauncher::m_ParticleFuse private
Definition at line 320 of file FireworksLauncher.c.
Referenced by OnFiringStartClient(), and OnFuseIgnitedClient().
m_TimerFuse
ref Timer FireworksLauncher::m_TimerFuse private
Definition at line 316 of file FireworksLauncher.c.
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Gear/Tools/FireworksLauncher.c