DayZ: ComponentAnimalBleeding Class Reference
ComponentAnimalBleeding Class Reference
Protected Member Functions
void ComponentAnimalBleeding ()
void InflictWoundDamage (TotalDamageResult damage_result, string zone_name, string ammo)
void CreateWound (TotalDamageResult damage_result, string zone_name, string ammo)
void Bleed (float wound_intensity)
float GetWoundIntensity (float bleed_treshold)
Protected Attributes
ref Timer m_BleedTimer
const float BASE_BLEED_RATE = 250
const float PASS_OUT_AMOUT = 500
Additional Inherited Members
Private Member Functions inherited from Component
void Event_OnFrame (IEntity other, float timeSlice)
Shape DebugBBoxDraw ()
void DebugBBoxSetColor (int color)
void DebugBBoxDelete ()
Shape DebugDirectionDraw (float distance=1)
void DebugDirectionSetColor (int color)
void DebugDirectionDelete ()
void SetParentEntityAI (EntityAI e)
void Event_OnAwake ()
void Event_OnInit ()
void LogThis (string msg, string fnc_name="n/a")
void LogThisWarning (string msg, string fnc_name="n/a")
void LogThisError (string msg, string fnc_name="n/a")
string GetCompName ()
int GetCompType ()
void Event_OnItemAttached (EntityAI item, string slot_name)
void Event_OnItemDetached (EntityAI item, string slot_name)
override Shape DebugBBoxDraw ()
override void DebugBBoxSetColor (int color)
override void DebugBBoxDelete ()
override Shape DebugDirectionDraw (float distance=1)
override void DebugDirectionDelete ()
void OnDrawing ()
Static Private Member Functions inherited from Component
static void Init ()
static string GetNameByType (int comp_type)
static bool IsTypeExist (int comp_type)
static void LogErrorBadCompType (int comp_type, string fnc_name)
static void LogWarningAlredyExist (int comp_type, string fnc_name)
Private Attributes inherited from Component
EntityAI m_ThisEntityAI
Shape m_DebugShapeBBox
Shape m_DebugShapeDirection
float m_DebugShapeDirectionDist
Detailed Description
Definition at line 8 of file ComponentAnimalBleeding.c.
Constructor & Destructor Documentation
ComponentAnimalBleeding()
void ComponentAnimalBleeding::ComponentAnimalBleeding () inline protected
Definition at line 16 of file ComponentAnimalBleeding.c.
  {
  }
Member Function Documentation
Bleed()
void ComponentAnimalBleeding::Bleed (float wound_intensity) inline protected
Definition at line 81 of file ComponentAnimalBleeding.c.
  {
    if (m_ThisEntityAI.IsAlive())
    {
      float bleeding_intensity = BASE_BLEED_RATE * wound_intensity;
      //Print("bleeding_intensity: " + bleeding_intensity);
      float global_blood_lvl = m_ThisEntityAI.GetHealth("", "Blood");
      m_ThisEntityAI.DecreaseHealth("", "Blood", bleeding_intensity);
      if (global_blood_lvl < PASS_OUT_AMOUT)
      {
        m_ThisEntityAI.SetHealth("", "", 0);
        //Print("global_blood_lvl < PASS_OUT_AMOUT => Zabijam zviera.");
      }
      //Print( "GetHealth Global Health: " + m_ThisEntityAI.GetHealth( "", "Health" ));
      //Print( "GetHealth Global Blood: " + m_ThisEntityAI.GetHealth( "", "Blood" ));
      //Print( "GetHealth Global Shock: " + m_ThisEntityAI.GetHealth( "", "Shock" ));
    }
    else
    {
      m_BleedTimer.Stop();
      //Print("Vypinam timer.");
    }
  }
References BASE_BLEED_RATE, m_BleedTimer, Component::m_ThisEntityAI, and PASS_OUT_AMOUT.
CreateWound()
void ComponentAnimalBleeding::CreateWound (TotalDamageResult damage_result, string zone_name, string ammo) inline protected
Definition at line 49 of file ComponentAnimalBleeding.c.
  {
    //Print( "GetHealth Health before creating wound@: " + zone_name + " " + m_ThisEntityAI.GetHealth( zone_name, "Health" ));
    InflictWoundDamage(damage_result, zone_name, ammo);
    //Print( "GetHealth Health after creating wood@: " + zone_name + " " + m_ThisEntityAI.GetHealth( zone_name, "Health" ));
    float can_bleed = false; //= GetGame().ConfigGetFloat( "CfgVehicles " + m_ThisEntityAI.GetType() + " DamageSystem " + "DamageZones " + zone_name + " canBleed" );
    //Print("can_bleed: " + can_bleed );
    float bleed_treshold = 0; //= GetGame().ConfigGetFloat( "CfgAmmo " + ammo + " DamageApplied " + "bleedThreshold" );
    //Print("bleed_treshold: " + bleed_treshold );
    float chance = -1; //Math.RandomFloat01();
    //Print("chance: " + chance );
    //Print( "GetHealth Health @: " + m_ThisEntityAI.GetHealth( zone_name, "Health" ));
    //Print( "GetHealth Blood @: " + m_ThisEntityAI.GetHealth( zone_name, "Blood" ));
    //Print( "GetHealth Shock @: " + m_ThisEntityAI.GetHealth( zone_name, "Shock" ));
    if (can_bleed && chance <= bleed_treshold)
    {
      m_BleedTimer = new Timer();
      float wound_intensity = GetWoundIntensity(bleed_treshold);
      //Print("wound_intensity: " + wound_intensity);
      m_BleedTimer.Run(1, this, "Bleed", new Param1<float>(wound_intensity), true);
    }
    /*
      else
      {
      Print("Not bleeding");
      }
    */
  }
References GetWoundIntensity(), InflictWoundDamage(), and m_BleedTimer.
GetWoundIntensity()
float ComponentAnimalBleeding::GetWoundIntensity (float bleed_treshold) inline protected
Definition at line 109 of file ComponentAnimalBleeding.c.
  {
    //higher the bleeding treshold => more intense bleeding
    return bleed_treshold * 2;
  }
Referenced by CreateWound().
InflictWoundDamage()
void ComponentAnimalBleeding::InflictWoundDamage (TotalDamageResult damage_result, string zone_name, string ammo) inline protected
Definition at line 21 of file ComponentAnimalBleeding.c.
  {
    if (ammo == "MeleeWolf")
      m_ThisEntityAI.SetHealth("", "", 0);
    if (!zone_name)
      return;
    float health_damage_inflicted = damage_result.GetDamage(zone_name, "Health");
    //float blood_damage_inflicted = damage_result.GetDamage( zone_name, "Blood");
    float wound_healt_damage = health_damage_inflicted;
    //float wound_blood_damage = health_damage_inflicted;
    m_ThisEntityAI.DecreaseHealth("", "Health", wound_healt_damage);
    //m_ThisEntityAI.DecreaseHealth( "", "Blood", wound_blood_damage );
    if (zone_name != "")
    {
      m_ThisEntityAI.DecreaseHealth(zone_name, "Health", wound_healt_damage);
      //m_ThisEntityAI.DecreaseHealth( zone_name, "Blood", wound_blood_damage );
    }
    //Print("Zone hit: " + zone_name );
    //Print("damage_result Health: " + damage_result.GetDamage( zone_name, "Health" ) );
    //Print("damage_result Blood: " + damage_result.GetDamage( zone_name, "Blood" ) );
  }
References Component::m_ThisEntityAI.
Referenced by CreateWound().
Member Data Documentation
BASE_BLEED_RATE
const float ComponentAnimalBleeding::BASE_BLEED_RATE = 250 protected
Definition at line 12 of file ComponentAnimalBleeding.c.
Referenced by Bleed().
m_BleedTimer
ref Timer ComponentAnimalBleeding::m_BleedTimer protected
Definition at line 11 of file ComponentAnimalBleeding.c.
Referenced by Bleed(), and CreateWound().
PASS_OUT_AMOUT
const float ComponentAnimalBleeding::PASS_OUT_AMOUT = 500 protected
Definition at line 13 of file ComponentAnimalBleeding.c.
Referenced by Bleed().
The documentation for this class was generated from the following file:
scripts/3_Game/tools/Component/ComponentAnimalBleeding.c