DayZ: scripts/4_World/Plugins/PluginBase/PluginItemDiagnostic.c File Reference
PluginItemDiagnostic.c File Reference
Classes
class ScriptedWidgetEventHandler
map: item x vector(index, width, height)
Functions
void PluginItemDiagnostic ()
void ~PluginItemDiagnostic ()
override void OnInit ()
bool OnMouseButtonDown (Widget w, int x, int y, int button)
bool OnMouseButtonUp (Widget w, int x, int y, int button)
void SetDragging (bool enable)
void OnDraggingStart ()
void OnDraggingEnd ()
bool OnClick (Widget w, int x, int y, int button)
void RegisterDebugItem (Object item, PlayerBase player)
Object GetWatchedItem (PlayerBase player)
bool IsActive ()
void OnScriptMenuOpened (bool opened)
void ShowWidgets (bool show)
void OnSelectAction (EntityAI ent, int actionId)
void ReleaseFocus ()
void ToggleDebugWindowEvent ()
void ClearWidgets ()
void Tick ()
void ClearProperties ()
void GeneratePropertiesObject (EntityAI item)
void SendRPC (Object item, PlayerBase player)
void StopWatchRequest (PlayerBase player)
void OnRPC (Object entity, ParamsReadContext ctx)
void FillServerFinalVars (int count, ParamsReadContext ctx, array< ref Param > params)
void InitializeWidgets ()
override void OnUpdate (float delta_time)
void DisplayAll (EntityAI item, array< ref Param > vars_server, array< ref Param > vars_client, string debug_text_server)
void FillAgentArray (ParamsReadContext ctx, int agents_count)
void UpdateAgentWidget ()
void UpdateNumericalVarsWidget (array< ref Param > vars_server, array< ref Param > vars_client)
void PrintOut ()
void GetLocalProperties (EntityAI entity, array< ref Param > properties, bool client=false)
int FillWithAgents (ItemBase item, array< ref Param > properties)
Variables
class PluginItemDiagnosticEventHandler extends ScriptedWidgetEventHandler m_Entity
ref Timer myTimer1
ref map< PlayerBase, Object > m_ObserversMap = new map<PlayerBase, Object>
ref array< string > m_Agents = new array<string>
ref map< string, float > m_Floats = new map<string, float>
ref map< string, float > m_VarsNumbersFinalServer = new map<string, float>
ref map< string, float > m_VarsFinalClient = new map<string, float>
ref array< ref Param > m_Properties = new array<ref Param>
bool m_IsActive = false
bool m_ScriptMenuOpened
string m_NoteClient
ref PluginItemDiagnosticEventHandler m_EventHandler
bool m_IsDragging
PluginConfigDebugProfile m_ConfigDebugProfile
Widget m_DebugRootWidget
Widget m_FrameWidget
TextListboxWidget m_DebugAgentListWidget
TextWidget m_DebugOutputServer
TextWidget m_DebugOutputClient
TextListboxWidget m_DebugFloatsProperListWidget
TextListboxWidget m_DebugClientVarsWidget
TextWidget m_ClassNameWidget
TextWidget m_DistanceWidget
ItemPreviewWidget m_ItemPreviewWidget
ButtonWidget m_DebugButtonWidget1
ButtonWidget m_DebugButtonWidget2
ButtonWidget m_DebugButtonWidget3
ButtonWidget m_DebugButtonWidget4
ButtonWidget m_CloseButton
Shape m_ItemLine
vector m_DraggingOffset
Function Documentation
ClearProperties()
void ClearProperties ()
Definition at line 296 of file PluginItemDiagnostic.c.
  {
    m_Properties.Clear();
  }
References m_Properties.
Referenced by GeneratePropertiesObject(), and ~PluginItemDiagnostic().
ClearWidgets()
void ClearWidgets ()
Definition at line 265 of file PluginItemDiagnostic.c.
  {
    m_DebugAgentListWidget.ClearItems();
    m_DebugOutputServer.SetText("");
    m_DebugOutputClient.SetText("");
    m_DebugFloatsProperListWidget.ClearItems();
    m_ItemPreviewWidget.SetItem(NULL);
    m_ClassNameWidget.SetText("");
  }
References m_ClassNameWidget, m_DebugAgentListWidget, m_DebugFloatsProperListWidget, m_DebugOutputClient, m_DebugOutputServer, m_ItemPreviewWidget, and ItemPreviewWidget::SetItem().
Referenced by ToggleDebugWindowEvent().
DisplayAll()
void DisplayAll (EntityAI item, array< ref Param > vars_server, array< ref Param > vars_client, string debug_text_server)
Definition at line 455 of file PluginItemDiagnostic.c.
  {
    m_ClassNameWidget.SetText(item.GetType());
    m_ItemPreviewWidget.SetItem(item);
    UpdateAgentWidget();
    //UpdateFloatWidget();
    if (vars_server && vars_client)
      UpdateNumericalVarsWidget(vars_server, vars_client);
    m_DebugOutputServer.SetText(debug_text_server);
    m_DebugOutputClient.SetText(item.GetDebugText());
    /*
      string button1, button2, button3, button4;
      item.GetDebugButtonNames(button1, button2, button3, button4);
      m_DebugButtonWidget1.SetText(button1);
      m_DebugButtonWidget2.SetText(button2);
      m_DebugButtonWidget3.SetText(button3);
      m_DebugButtonWidget4.SetText(button4);
    */
  }
References m_ClassNameWidget, m_DebugOutputClient, m_DebugOutputServer, m_ItemPreviewWidget, ItemPreviewWidget::SetItem(), UpdateAgentWidget(), and UpdateNumericalVarsWidget().
Referenced by OnRPC().
FillAgentArray()
void FillAgentArray (ParamsReadContext ctx, int agents_count)
Definition at line 478 of file PluginItemDiagnostic.c.
  {
    m_Agents.Clear();
    for (int i = 0; i < agents_count; i++)
    {
      if (ctx.Read(CachedObjectsParams.PARAM1_STRING))
      {
        string agent = CachedObjectsParams.PARAM1_STRING.param1;
        m_Agents.Insert(agent);
      }
    }
  }
References m_Agents, and CachedObjectsParams::PARAM1_STRING.
Referenced by OnRPC().
FillServerFinalVars()
void FillServerFinalVars (int count, ParamsReadContext ctx, array< ref Param > params)
Definition at line 374 of file PluginItemDiagnostic.c.
  {
    for (int i = 0; i < count; i++)
    {
      Param2<string, float> p2 = new Param2<string, float>("", 0);
      ctx.Read(p2);
      /*
        string name = CachedObjectsParams.PARAM2_STRING_FLOAT.param1;
        float value = CachedObjectsParams.PARAM2_STRING_FLOAT.param2;
        PrintString(name+","+value.ToString());
      */
      params.Insert(p2);
    }
    //PrintString("----------------------------------------------------");
  }
Referenced by OnRPC().
FillWithAgents()
int FillWithAgents (ItemBase item, array< ref Param > properties)
Definition at line 603 of file PluginItemDiagnostic.c.
  {
    if (!item)
      return 0;
    int agents = item.GetAgents();
    if (agents == 0) return 0;
    int num_of_agents = 0;
    ref array<int> agents_aray = new array<int>;
    PluginTransmissionAgents.BuildAgentArray(agents, agents_aray);
    int agents_count = agents_aray.Count();
    for (int i = 0; i < agents_count; i++)
    {
      //PluginTransmissionAgents mta = PluginTransmissionAgents.Cast(GetPlugin(PluginTransmissionAgents));
      string agent_name = PluginTransmissionAgents.GetNameByID(agents_aray.Get(i));
      Param1<string> param1 = new Param1<string>(agent_name);
      properties.Insert(param1);
      num_of_agents++;
    }
    return num_of_agents;
  }
Referenced by GetLocalProperties().
GeneratePropertiesObject()
void GeneratePropertiesObject (EntityAI item)
Definition at line 302 of file PluginItemDiagnostic.c.
  {
    ClearProperties();
    GetLocalProperties(item, m_Properties);
  }
References ClearProperties(), GetLocalProperties(), and m_Properties.
Referenced by Tick().
GetLocalProperties()
void GetLocalProperties (EntityAI entity, array< ref Param > properties, bool client = false)
Definition at line 531 of file PluginItemDiagnostic.c.
  {
    if (!entity)
      return;
    ItemBase item = ItemBase.Cast(entity);
    if (!client)
    {
      // -------- DEBUG OUTPUT ------
      Param1<string> debug_output = new Param1<string>(entity.GetDebugText());
      properties.Insert(debug_output);
      if (!item)
        return;
      // -------- AGENTS ------------
      int num_of_agents = FillWithAgents(item, properties);
      Param1<int> agents_count = new Param1<int>(num_of_agents);
      properties.InsertAt(agents_count, 1); // hard coded index 1 !!
    }
    if (!item)
      return;
    // ------ INDIVIDUAL VARS------
    int number_of_items = 0;
    Param2<string, float> quantity = new Param2<string, float>("quantity", item.GetQuantity());
    properties.Insert(quantity);
    number_of_items++;
    //-----------------------------
    Param2<string, float> liquid_type = new Param2<string, float>("liquid_type", item.GetLiquidType());
    properties.Insert(liquid_type);
    number_of_items++;
    //-----------------------------
    Param2<string, float> wetness = new Param2<string, float>("wetness", item.GetWet());
    properties.Insert(wetness);
    number_of_items++;
    //-----------------------------
    Param2<string, float> temperature = new Param2<string, float>("temperature", item.GetTemperature());
    properties.Insert(temperature);
    number_of_items++;
    //-----------------------------
    Param2<string, float> energy = new Param2<string, float>("energy", item.GetEnergy());
    properties.Insert(energy);
    number_of_items++;
    //-----------------------------
    Param2<string, float> health;
    if (!client)
      health = new Param2<string, float>("health", item.GetHealth("", ""));
    else
      health = new Param2<string, float>("NO SYNC", 0);
    properties.Insert(health);
    number_of_items++;
    //-----------------------------
    int r, g, b, a;
    item.GetColor(r, g, b, a);
    Param2<string, float> p2r = new Param2<string, float>("R", r);
    properties.Insert(p2r);
    number_of_items++;
    Param2<string, float> p2g = new Param2<string, float>("G", g);
    properties.Insert(p2g);
    number_of_items++;
    Param2<string, float> p2b = new Param2<string, float>("B", b);
    properties.Insert(p2b);
    number_of_items++;
    Param2<string, float> p2a = new Param2<string, float>("A", a);
    properties.Insert(p2a);
    number_of_items++;
    //-----------------------------
    if (!client)
    {
      Param1<int> item_count = new Param1<int>(number_of_items);
      properties.InsertAt(item_count, 2);
    }
  }
References FillWithAgents().
Referenced by GeneratePropertiesObject(), and OnRPC().
GetWatchedItem()
Object GetWatchedItem (PlayerBase player)
Definition at line 198 of file PluginItemDiagnostic.c.
  {
    return m_ObserversMap.Get(player);
  }
References m_ObserversMap.
InitializeWidgets()
void InitializeWidgets ()
Definition at line 391 of file PluginItemDiagnostic.c.
  {
    m_EventHandler = new PluginItemDiagnosticEventHandler;
    m_EventHandler.m_Owner = this;
    if (!m_DebugRootWidget)
      m_DebugRootWidget = GetGame().GetWorkspace().CreateWidgets("gui/layouts/debug/debug_item.layout");
    m_DebugRootWidget.SetHandler(m_EventHandler);
    m_FrameWidget = m_DebugRootWidget.FindAnyWidget("FrameWidget0");
    m_DebugAgentListWidget = TextListboxWidget.Cast(m_DebugRootWidget.FindAnyWidget("w_Agents"));
    m_DebugOutputServer = TextWidget.Cast(m_DebugRootWidget.FindAnyWidget("DebugOutputServer"));
    m_DebugOutputClient = TextWidget.Cast(m_DebugRootWidget.FindAnyWidget("DebugOutputClient"));
    m_DebugFloatsProperListWidget = TextListboxWidget.Cast(m_DebugRootWidget.FindAnyWidget("w_FloatsProper"));
    m_ItemPreviewWidget = ItemPreviewWidget.Cast(m_DebugRootWidget.FindAnyWidget("w_ItemPreview"));
    m_ClassNameWidget = TextWidget.Cast(m_DebugRootWidget.FindAnyWidget("w_ClassName"));
    m_DistanceWidget = TextWidget.Cast(m_DebugRootWidget.FindAnyWidget("w_Distance"));
    m_DebugButtonWidget1 = ButtonWidget.Cast(m_DebugRootWidget.FindAnyWidget("DebugButton1"));
    m_DebugButtonWidget2 = ButtonWidget.Cast(m_DebugRootWidget.FindAnyWidget("DebugButton2"));
    m_DebugButtonWidget3 = ButtonWidget.Cast(m_DebugRootWidget.FindAnyWidget("DebugButton3"));
    m_DebugButtonWidget4 = ButtonWidget.Cast(m_DebugRootWidget.FindAnyWidget("DebugButton4"));
    m_CloseButton = ButtonWidget.Cast(m_DebugRootWidget.FindAnyWidget("CloseButton"));
  }
References GetGame(), m_ClassNameWidget, m_CloseButton, m_DebugAgentListWidget, m_DebugButtonWidget1, m_DebugButtonWidget2, m_DebugButtonWidget3, m_DebugButtonWidget4, m_DebugFloatsProperListWidget, m_DebugOutputClient, m_DebugOutputServer, m_DebugRootWidget, m_DistanceWidget, m_EventHandler, m_FrameWidget, and m_ItemPreviewWidget.
Referenced by PluginItemDiagnostic().
IsActive()
bool IsActive ()
Definition at line 204 of file PluginItemDiagnostic.c.
  {
    return m_IsActive;
  }
References m_IsActive.
OnClick()
bool OnClick (Widget w, int x, int y, int button)
Definition at line 169 of file PluginItemDiagnostic.c.
  {
    SetDragging(false);
    if (w == m_CloseButton)
    {
      ToggleDebugWindowEvent();
      return true;
    }
    return true;
  }
References m_CloseButton, SetDragging(), and ToggleDebugWindowEvent().
OnDraggingEnd()
void OnDraggingEnd ()
Definition at line 158 of file PluginItemDiagnostic.c.
  {
    if (m_ConfigDebugProfile)
    {
      float wx, wy;
      m_DebugRootWidget.GetScreenPos(wx, wy);
      m_ConfigDebugProfile.SetItemDebugPos(Vector(wx, wy, 0));
    }
  }
References m_ConfigDebugProfile, m_DebugRootWidget, and Vector().
Referenced by SetDragging().
OnDraggingStart()
void OnDraggingStart ()
Definition at line 148 of file PluginItemDiagnostic.c.
  {
    int mx, my;
    float wx, wy;
    GetMousePos(mx, my);
    m_DebugRootWidget.GetScreenPos(wx, wy);
    m_DraggingOffset[0] = wx - mx;
    m_DraggingOffset[1] = wy - my;
  }
References GetMousePos(), m_DebugRootWidget, and m_DraggingOffset.
Referenced by SetDragging().
OnInit()
override void OnInit ()
Definition at line 101 of file PluginItemDiagnostic.c.
  {
    m_ConfigDebugProfile = PluginConfigDebugProfile.Cast(GetPlugin(PluginConfigDebugProfile));
    if (m_ConfigDebugProfile)
    {
      vector pos = m_ConfigDebugProfile.GetItemDebugPos();
      if (m_DebugRootWidget && pos != vector.Zero)
      {
        float wx = pos[0];
        float wy = pos[1];
        m_DebugRootWidget.SetPos(wx, wy);
      }
    }
  }
References GetPlugin(), m_ConfigDebugProfile, m_DebugRootWidget, and vector::Zero.
OnMouseButtonDown()
bool OnMouseButtonDown (Widget w, int x, int y, int button)
Definition at line 116 of file PluginItemDiagnostic.c.
  {
    if (button == 0)
      SetDragging(true);
    if (button == 1)
    {
      if (m_Entity)
      {
        float xx, yy;
        m_DebugRootWidget.GetPos(xx, yy);
        ContextMenu.DisplayContextMenu(x - xx, y - yy, EntityAI.Cast(m_Entity), m_DebugRootWidget, this);
      }
    }
    return true;
  }
References m_DebugRootWidget, m_Entity, SetDragging(), x, and y.
OnMouseButtonUp()
bool OnMouseButtonUp (Widget w, int x, int y, int button)
Definition at line 132 of file PluginItemDiagnostic.c.
  {
    if (button == 0)
      SetDragging(false);
    return true;
  }
References SetDragging().
OnRPC()
void OnRPC (Object entity, ParamsReadContext ctx)
Definition at line 326 of file PluginItemDiagnostic.c.
  {
    if (!GetGame().IsMultiplayer())
      entity = m_Entity;
    else
      m_Entity = entity;
    ItemBase item = ItemBase.Cast(entity);
#ifdef DEVELOPER
    SetDebugDeveloper_item(entity);
#endif
    if (!IsActive())
      ShowWidgets(true);
    ctx.Read(CachedObjectsParams.PARAM1_STRING);
    string debug_output_server = CachedObjectsParams.PARAM1_STRING.param1;
    array<ref Param> vars_client;
    array<ref Param> vars_server;
    if (item)
    {
      ctx.Read(CachedObjectsParams.PARAM1_INT);//hardcoded to index 1
      int agents_count = CachedObjectsParams.PARAM1_INT.param1;
      ctx.Read(CachedObjectsParams.PARAM1_INT);//hardcoded to index 2
      int individual_items_count = CachedObjectsParams.PARAM1_INT.param1;
      FillAgentArray(ctx, agents_count);
      vars_server = new array<ref Param>;
      FillServerFinalVars(individual_items_count, ctx, vars_server);
      vars_client = new array<ref Param>;
      GetLocalProperties(item, vars_client, true);
    }
    if (EntityAI.Cast(entity))
      DisplayAll(EntityAI.Cast(entity), vars_server, vars_client, debug_output_server);
    if (GetDayZGame().IsInventoryOpen() || GetGame().GetUIManager().FindMenu(MENU_SCRIPTCONSOLE))
      m_DebugRootWidget.SetSort(-1);
    else
      m_DebugRootWidget.SetSort(10);
    m_DebugRootWidget.Show(true);
  }
References DisplayAll(), FillAgentArray(), FillServerFinalVars(), GetDayZGame(), GetGame(), GetLocalProperties(), IsActive(), m_DebugRootWidget, m_Entity, MENU_SCRIPTCONSOLE, CachedObjectsParams::PARAM1_INT, CachedObjectsParams::PARAM1_STRING, and ShowWidgets().
OnScriptMenuOpened()
void OnScriptMenuOpened (bool opened)
Definition at line 209 of file PluginItemDiagnostic.c.
  {
    m_ScriptMenuOpened = opened;
  }
References m_ScriptMenuOpened.
OnSelectAction()
void OnSelectAction (EntityAI ent, int actionId)
Definition at line 224 of file PluginItemDiagnostic.c.
  {
#ifdef DIAG_DEVELOPER
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    player.GetActionManager().OnInstantAction(ActionDebug, new Param2<EntityAI, int>(ent, actionId));
#endif
  }
References GetGame(), and GetPlayer().
OnUpdate()
override void OnUpdate (float delta_time)
Definition at line 418 of file PluginItemDiagnostic.c.
  {
    super.OnUpdate(delta_time);
    if (!m_Entity || !m_IsActive)
    {
      if (m_ItemLine)
      {
        m_ItemLine.Destroy();
        m_ItemLine = null;
      }
      return;
    }
    m_ItemPreviewWidget.Show(!m_ScriptMenuOpened);
    if (m_IsDragging)
    {
      int x, y;
      GetMousePos(x, y);
      m_DebugRootWidget.SetPos(x + m_DraggingOffset[0], y + m_DraggingOffset[1]);
    }
    vector pts[2];
    pts[0] = GetGame().GetPlayer().GetPosition();
    pts[1] = m_Entity.GetPosition();
    if (m_ItemLine)
    {
      m_ItemLine.Destroy();
      m_ItemLine = null;
    }
    m_ItemLine = Shape.CreateLines(COLOR_BLUE, ShapeFlags.TRANSP | ShapeFlags.NOOUTLINE | ShapeFlags.NOZBUFFER, pts, 2);
    m_DistanceWidget.SetText(vector.Distance(pts[0], pts[1]).ToString() + "m.");
  }
References COLOR_BLUE, vector::Distance(), GetGame(), GetMousePos(), m_DebugRootWidget, m_DistanceWidget, m_DraggingOffset, m_Entity, m_IsActive, m_IsDragging, m_ItemLine, m_ItemPreviewWidget, m_ScriptMenuOpened, Shape, x, and y.
PluginItemDiagnostic()
void PluginItemDiagnostic ()
Definition at line 82 of file PluginItemDiagnostic.c.
  {
#ifndef NO_GUI
    InitializeWidgets();
    ShowWidgets(false);
#endif
  }
References InitializeWidgets(), and ShowWidgets().
Referenced by InventoryItem::OnAction(), ManBase::OnRPC(), UIScriptedMenu::ScriptConsole(), PluginBase::SetDeveloperItemClientEx(), and UIScriptedMenu::~ScriptConsole().
PrintOut()
void PrintOut ()
Definition at line 522 of file PluginItemDiagnostic.c.
  {
    Debug.LogArrayString(m_Agents, "ItemDebug");
    Debug.Log("----------------------", "ItemDebug");
  }
References Debug::Log(), Debug::LogArrayString(), and m_Agents.
RegisterDebugItem()
void RegisterDebugItem (Object item, PlayerBase player)
Definition at line 181 of file PluginItemDiagnostic.c.
  {
    if (!myTimer1)
    {
      myTimer1 = new Timer();
      myTimer1.Run(1, this, "Tick", NULL, true);
    }
    if (m_ObserversMap.Contains(player))
      m_ObserversMap.Set(player, item);
    else
      m_ObserversMap.Insert(player, item);
#ifdef DEVELOPER
    SetDebugDeveloper_item(item);
#endif
  }
References m_ObserversMap, and myTimer1.
ReleaseFocus()
void ReleaseFocus ()
Definition at line 232 of file PluginItemDiagnostic.c.
  {
    GetGame().GetInput().ResetGameFocus();
    GetGame().GetUIManager().ShowUICursor(false);
    if (GetGame().GetUIManager())
    {
      if (GetGame().GetUIManager().IsDialogVisible())
        GetGame().GetUIManager().CloseDialog();
    }
  }
References GetGame().
SendRPC()
void SendRPC (Object item, PlayerBase player)
Definition at line 309 of file PluginItemDiagnostic.c.
  {
    Param1<Object> p1 = new Param1<Object>(item);
    m_Properties.InsertAt(p1, 0);
    GetGame().RPC(player, ERPCs.RPC_ITEM_DIAG, m_Properties, true, player.GetIdentity());
    if (!GetGame().IsMultiplayer())
      m_Entity = item;
  }
References GetGame(), m_Entity, and m_Properties.
SetDragging()
void SetDragging (bool enable)
Definition at line 139 of file PluginItemDiagnostic.c.
  {
    if (enable && !m_IsDragging)
      OnDraggingStart();
    else if (!enable && m_IsDragging)
      OnDraggingEnd();
    m_IsDragging = enable;
  }
References m_IsDragging, OnDraggingEnd(), and OnDraggingStart().
Referenced by OnClick(), OnMouseButtonDown(), OnMouseButtonUp(), and ToggleDebugWindowEvent().
ShowWidgets()
void ShowWidgets (bool show)
Definition at line 215 of file PluginItemDiagnostic.c.
  {
    m_IsActive = show;
    if (m_DebugRootWidget)
      m_DebugRootWidget.Show(show);
  }
References m_DebugRootWidget, and m_IsActive.
StopWatchRequest()
void StopWatchRequest (PlayerBase player)
Definition at line 320 of file PluginItemDiagnostic.c.
  {
    if (m_ObserversMap.Contains(player))
      m_ObserversMap.Remove(player);
  }
References m_ObserversMap.
Tick()
void Tick ()
Definition at line 275 of file PluginItemDiagnostic.c.
  {
    for (int i = 0; i < m_ObserversMap.Count(); i++)
    {
      Object item = m_ObserversMap.GetElement(i);
      PlayerBase player = m_ObserversMap.GetKey(i);
      if (item && player)
      {
        GeneratePropertiesObject(EntityAI.Cast(item));
        SendRPC(item, player);
      }
      else
      {
        Debug.LogError("PluginItemDiagnostic: dead debug record, removing record");
        m_ObserversMap.RemoveElement(i);
      }
    }
  }
References GeneratePropertiesObject(), Debug::LogError(), m_ObserversMap, and SendRPC().
ToggleDebugWindowEvent()
void ToggleDebugWindowEvent ()
Definition at line 244 of file PluginItemDiagnostic.c.
  {
    if (m_IsActive)
    {
      PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
      GetGame().RPCSingleParam(player, ERPCs.RPC_ITEM_DIAG_CLOSE, null, true);
      ShowWidgets(false);
      ClearWidgets();
      GetGame().GetCallQueue(CALL_CATEGORY_GUI).CallLater(ReleaseFocus, 100);
      //m_IsActive = false;
      SetDragging(false);
    }
    else
    {
      ShowWidgets(true);
      //m_IsActive = true;
    }
  }
References CALL_CATEGORY_GUI, ClearWidgets(), GetGame(), GetPlayer(), m_IsActive, ReleaseFocus(), SetDragging(), and ShowWidgets().
UpdateAgentWidget()
void UpdateAgentWidget ()
Definition at line 492 of file PluginItemDiagnostic.c.
  {
    m_DebugAgentListWidget.ClearItems();
    for (int i = 0; i < m_Agents.Count(); i++)
    {
      string agent = m_Agents.Get(i);
      m_DebugAgentListWidget.AddItem(agent, NULL, 0);
    }
  }
References m_Agents, and m_DebugAgentListWidget.
Referenced by DisplayAll().
UpdateNumericalVarsWidget()
void UpdateNumericalVarsWidget (array< ref Param > vars_server, array< ref Param > vars_client)
Definition at line 503 of file PluginItemDiagnostic.c.
  {
    m_DebugFloatsProperListWidget.ClearItems();
    for (int i = 0; i < vars_server.Count(); i++)
    {
      Param param_server = vars_server.Get(i);
      Param2<string, float> p2_server = Param2<string, float>.Cast(param_server);
      Param param_client = vars_client.Get(i);
      Param2<string, float> p2_client = Param2<string, float>.Cast(param_client);
      string name = p2_server.param1;
      m_DebugFloatsProperListWidget.AddItem(name, NULL, 0);
      m_DebugFloatsProperListWidget.SetItem(i, p2_server.param2.ToString(), NULL, 1);
      m_DebugFloatsProperListWidget.SetItem(i, p2_client.param2.ToString(), NULL, 2);
    }
  }
References m_DebugFloatsProperListWidget, and name.
Referenced by DisplayAll().
~PluginItemDiagnostic()
void ~PluginItemDiagnostic ()
Definition at line 91 of file PluginItemDiagnostic.c.
  {
    ClearProperties();
    if (m_ItemLine)
    {
      m_ItemLine.Destroy();
      m_ItemLine = null;
    }
  }
References ClearProperties(), and m_ItemLine.
Variable Documentation
m_Agents
ref array<string> m_Agents = new array<string>
Definition at line 47 of file PluginItemDiagnostic.c.
m_ClassNameWidget
TextWidget m_ClassNameWidget
Definition at line 67 of file PluginItemDiagnostic.c.
Referenced by ClearWidgets(), DisplayAll(), and InitializeWidgets().
m_CloseButton
ButtonWidget m_CloseButton
Definition at line 76 of file PluginItemDiagnostic.c.
Referenced by InitializeWidgets(), ScriptedWidgetEventHandler::ModsMenuDetailed(), OnClick(), and ScriptedWidgetEventHandler::OnMouseButtonUp().
m_ConfigDebugProfile
PluginConfigDebugProfile m_ConfigDebugProfile
Definition at line 57 of file PluginItemDiagnostic.c.
Referenced by UIScriptedMenu::AddItemToPreset(), UIScriptedMenu::DeletePreset(), ManBase::Init(), UIScriptedMenu::Init(), UIScriptedMenu::ItemMoveDown(), UIScriptedMenu::ItemMoveUp(), UIScriptedMenu::NewPreset(), UIScriptedMenu::OnChange(), UIScriptedMenu::OnClick(), UIPopupScript::OnClick(), UIScriptedMenu::OnDoubleClick(), OnDraggingEnd(), OnInit(), UIScriptedMenu::RemoveItemFromPreset(), UIScriptedMenu::RenamePreset(), UIScriptedMenu::RenderPresetItems(), UIScriptedMenu::RenderPresets(), UIScriptedMenu::SaveProfileSpawnDistance(), UIScriptedMenu::SelectTab(), UIScriptedMenu::SetDefaultPreset(), and UIScriptedMenu::SetPreset().
m_DebugAgentListWidget
TextListboxWidget m_DebugAgentListWidget
Definition at line 62 of file PluginItemDiagnostic.c.
Referenced by ClearWidgets(), InitializeWidgets(), and UpdateAgentWidget().
m_DebugButtonWidget1
ButtonWidget m_DebugButtonWidget1
Definition at line 71 of file PluginItemDiagnostic.c.
Referenced by InitializeWidgets().
m_DebugButtonWidget2
ButtonWidget m_DebugButtonWidget2
Definition at line 72 of file PluginItemDiagnostic.c.
Referenced by InitializeWidgets().
m_DebugButtonWidget3
ButtonWidget m_DebugButtonWidget3
Definition at line 73 of file PluginItemDiagnostic.c.
Referenced by InitializeWidgets().
m_DebugButtonWidget4
ButtonWidget m_DebugButtonWidget4
Definition at line 74 of file PluginItemDiagnostic.c.
Referenced by InitializeWidgets().
m_DebugClientVarsWidget
TextListboxWidget m_DebugClientVarsWidget
Definition at line 66 of file PluginItemDiagnostic.c.
m_DebugFloatsProperListWidget
TextListboxWidget m_DebugFloatsProperListWidget
Definition at line 65 of file PluginItemDiagnostic.c.
Referenced by ClearWidgets(), InitializeWidgets(), and UpdateNumericalVarsWidget().
m_DebugOutputClient
TextWidget m_DebugOutputClient
Definition at line 64 of file PluginItemDiagnostic.c.
Referenced by ClearWidgets(), DisplayAll(), and InitializeWidgets().
m_DebugOutputServer
TextWidget m_DebugOutputServer
Definition at line 63 of file PluginItemDiagnostic.c.
Referenced by ClearWidgets(), DisplayAll(), and InitializeWidgets().
m_DebugRootWidget
Widget m_DebugRootWidget
Definition at line 59 of file PluginItemDiagnostic.c.
Referenced by InitializeWidgets(), OnDraggingEnd(), OnDraggingStart(), OnInit(), OnMouseButtonDown(), OnRPC(), OnUpdate(), and ShowWidgets().
m_DistanceWidget
TextWidget m_DistanceWidget
Definition at line 68 of file PluginItemDiagnostic.c.
m_DraggingOffset
vector m_DraggingOffset
Definition at line 79 of file PluginItemDiagnostic.c.
Referenced by OnDraggingStart(), and OnUpdate().
m_Entity
class PluginItemDiagnosticEventHandler extends ScriptedWidgetEventHandler m_Entity
m_EventHandler
ref PluginItemDiagnosticEventHandler m_EventHandler
Definition at line 55 of file PluginItemDiagnostic.c.
Referenced by InitializeWidgets().
m_Floats
ref map<string, float> m_Floats = new map<string, float>
Definition at line 48 of file PluginItemDiagnostic.c.
m_FrameWidget
Widget m_FrameWidget
Definition at line 60 of file PluginItemDiagnostic.c.
Referenced by InitializeWidgets().
m_IsActive
bool m_IsActive = false
Definition at line 52 of file PluginItemDiagnostic.c.
m_IsDragging
bool m_IsDragging
Definition at line 56 of file PluginItemDiagnostic.c.
Referenced by OnUpdate(), and SetDragging().
m_ItemLine
Shape m_ItemLine
Definition at line 78 of file PluginItemDiagnostic.c.
Referenced by OnUpdate(), and ~PluginItemDiagnostic().
m_ItemPreviewWidget
ItemPreviewWidget m_ItemPreviewWidget
Definition at line 69 of file PluginItemDiagnostic.c.
Referenced by ClearWidgets(), DisplayAll(), InitializeWidgets(), and OnUpdate().
m_NoteClient
string m_NoteClient
Definition at line 54 of file PluginItemDiagnostic.c.
m_ObserversMap
ref map<PlayerBase, Object> m_ObserversMap = new map<PlayerBase, Object>
Definition at line 46 of file PluginItemDiagnostic.c.
Referenced by GetWatchedItem(), RegisterDebugItem(), StopWatchRequest(), and Tick().
m_Properties
ref array<ref Param> m_Properties = new array<ref Param>
Definition at line 51 of file PluginItemDiagnostic.c.
Referenced by ClearProperties(), GeneratePropertiesObject(), and SendRPC().
m_ScriptMenuOpened
bool m_ScriptMenuOpened
Definition at line 53 of file PluginItemDiagnostic.c.
Referenced by OnScriptMenuOpened(), and OnUpdate().
m_VarsFinalClient
ref map<string, float> m_VarsFinalClient = new map<string, float>
Definition at line 50 of file PluginItemDiagnostic.c.
m_VarsNumbersFinalServer
ref map<string, float> m_VarsNumbersFinalServer = new map<string, float>
Definition at line 49 of file PluginItemDiagnostic.c.
myTimer1
ref Timer myTimer1
Definition at line 45 of file PluginItemDiagnostic.c.
Referenced by PluginRecipesManagerBase::PluginRecipesManager(), and RegisterDebugItem().