DayZ: scripts/4_World/Classes/QuickBarBase.c File Reference
QuickBarBase.c File Reference
Classes
class QuickBarItem
Functions
void QuickBarBase (PlayerBase player)
void SetSize (int newSize)
int GetNonEmptyCount ()
EntityAI GetEntity (int index)
int GetSize ()
int FindEntityIndex (EntityAI entity)
bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx)
void UpdateShotcutVisibility (int index)
void SetShotcutEnable (int index, bool value)
bool CanAddAsShortcut (EntityAI entity)
void SetEntityShortcut (EntityAI entity, int index, bool force=false)
void OnSetEntityNoSync (EntityAI entity, int index, bool force=false)
void OnSetEntityRPC (ParamsReadContext ctx)
Reaction on Rpc from server for set inicial state for quickbar.
void OnSetEntityRequest (ParamsReadContext ctx)
Reaction on SetEntityShortcut from client.
void _SetEntityShortcut (EntityAI entity, int index, bool force=false)
void updateSlotsCount ()
void _RemoveEntity (int index)
void _SetEntity (EntityAI entity, int index, bool force=false)
void ~QuickBarBase ()
void CancelContinuousUse (int index)
Variables
const int MAX_QUICKBAR_SLOTS_COUNT = 10
class QuickBarItem m_aQuickbarEnts [MAX_QUICKBAR_SLOTS_COUNT]
PlayerBase _player
int m_slotsCount
Function Documentation
_RemoveEntity()
void _RemoveEntity (int index) protected
Definition at line 236 of file QuickBarBase.c.
  {
    if (index >= 0 && index < MAX_QUICKBAR_SLOTS_COUNT)
    {
      CancelContinuousUse(index);
      m_aQuickbarEnts[index].m_entity = NULL;
      m_aQuickbarEnts[index].m_enabled = false;
      if (_player.m_Hud)
        _player.m_Hud.RefreshQuickbar(true);
    }
  }
References _player, CancelContinuousUse(), m_aQuickbarEnts, and MAX_QUICKBAR_SLOTS_COUNT.
Referenced by _SetEntityShortcut().
_SetEntity()
void _SetEntity (EntityAI entity, int index, bool force = false) protected
Definition at line 250 of file QuickBarBase.c.
  {
    if (index >= 0 && index < MAX_QUICKBAR_SLOTS_COUNT)
    {
      if (CanAddAsShortcut(entity))
      {
        m_aQuickbarEnts[index].m_entity = entity;
        m_aQuickbarEnts[index].m_enabled = true;
      }
      else
      {
        CancelContinuousUse(index);
        m_aQuickbarEnts[index].m_enabled = false;
      }
      if (_player.m_Hud)
        _player.m_Hud.RefreshQuickbar(true);
    }
  }
References _player, CanAddAsShortcut(), CancelContinuousUse(), m_aQuickbarEnts, and MAX_QUICKBAR_SLOTS_COUNT.
Referenced by _SetEntityShortcut().
_SetEntityShortcut()
void _SetEntityShortcut (EntityAI entity, int index, bool force = false) protected
Definition at line 205 of file QuickBarBase.c.
  {
    //TODO Check, if is in inventory
    //if(entity.GetLoca)
    if (entity == NULL)
    {
      _RemoveEntity(index);
      return;
    }
    int i = FindEntityIndex(entity);
    if (i != -1)
      _RemoveEntity(i);
    _RemoveEntity(index);
    _SetEntity(entity, index, force);
  }
References _RemoveEntity(), _SetEntity(), and FindEntityIndex().
Referenced by OnSetEntityNoSync(), OnSetEntityRequest(), OnSetEntityRPC(), and SetEntityShortcut().
CanAddAsShortcut()
bool CanAddAsShortcut (EntityAI entity) protected
Definition at line 135 of file QuickBarBase.c.
  {
    InventoryLocation loc = new InventoryLocation;
    entity.GetInventory().GetCurrentInventoryLocation(loc);
    EntityAI parent = loc.GetParent();
    return (entity && entity.GetHierarchyRootPlayer() == _player && parent.CanAssignAttachmentsToQuickbar() && entity.CanAssignToQuickbar());
  }
References _player.
Referenced by _SetEntity(), SetShotcutEnable(), and UpdateShotcutVisibility().
CancelContinuousUse()
void CancelContinuousUse (int index) protected
Definition at line 275 of file QuickBarBase.c.
  {
    if (_player.m_QuickBarHold)
    {
      HumanInputController hic = _player.GetInputController();
      if (hic && hic.IsQuickBarSlot() == index + 1)
        _player.OnQuickBarContinuousUseEnd(index + 1);
    }
  }
References _player.
Referenced by _RemoveEntity(), _SetEntity(), SetShotcutEnable(), and UpdateShotcutVisibility().
FindEntityIndex()
int FindEntityIndex (EntityAI entity) protected
Definition at line 93 of file QuickBarBase.c.
  {
    for (int i = 0; i < MAX_QUICKBAR_SLOTS_COUNT; i++)
    {
      if (m_aQuickbarEnts[i].m_entity == entity)
        return i;
    }
    return -1;
  }
References m_aQuickbarEnts, and MAX_QUICKBAR_SLOTS_COUNT.
Referenced by _SetEntityShortcut().
GetEntity()
EntityAI GetEntity (int index) protected
Definition at line 76 of file QuickBarBase.c.
  {
    if (index < 0 || index >= m_slotsCount)
      return NULL;
    if (m_aQuickbarEnts[index].m_enabled)
      return m_aQuickbarEnts[index].m_entity;
    return NULL;
  }
References m_aQuickbarEnts, and m_slotsCount.
GetNonEmptyCount()
int GetNonEmptyCount () protected
Definition at line 64 of file QuickBarBase.c.
  {
    int count = 0;
    for (int i = 0; i < m_slotsCount; i++)
    {
      if (m_aQuickbarEnts[i].m_enabled)
        count++;
    }
    return count;
  }
References m_aQuickbarEnts, and m_slotsCount.
GetSize()
int GetSize () protected
Definition at line 88 of file QuickBarBase.c.
  {
    return m_slotsCount;
  }
References m_slotsCount.
OnInputUserDataProcess()
bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx) protected
Definition at line 104 of file QuickBarBase.c.
  {
    if (userDataType == INPUT_UDT_QUICKABARSHORTCUT)
    {
      OnSetEntityRequest(ctx);
      return true;
    }
    return false;
  }
References INPUT_UDT_QUICKABARSHORTCUT, and OnSetEntityRequest().
OnSetEntityNoSync()
void OnSetEntityNoSync (EntityAI entity, int index, bool force = false) protected
Definition at line 171 of file QuickBarBase.c.
  {
    _SetEntityShortcut(entity, index, force);
  }
References _SetEntityShortcut().
OnSetEntityRequest()
void OnSetEntityRequest (ParamsReadContext ctx) protected
Reaction on SetEntityShortcut from client.
Definition at line 188 of file QuickBarBase.c.
  {
    EntityAI eai = null;
    if (!ctx.Read(eai))
      return;
    int index = -1;
    if (!ctx.Read(index))
      return;
    bool force = false;
    if (!ctx.Read(force))
      return
        _SetEntityShortcut(eai, index, force);
  }
References _SetEntityShortcut().
Referenced by OnInputUserDataProcess().
OnSetEntityRPC()
void OnSetEntityRPC (ParamsReadContext ctx) protected
Reaction on Rpc from server for set inicial state for quickbar.
Definition at line 177 of file QuickBarBase.c.
  {
    Param2<Entity, int> param;
    if (!ctx.Read(param))
      return;
    EntityAI entity1 = EntityAI.Cast(param.param1);
    _SetEntityShortcut(entity1, param.param2, false);
  }
References _SetEntityShortcut().
QuickBarBase()
void QuickBarBase (PlayerBase player) protected
Definition at line 21 of file QuickBarBase.c.
  {
    for (int i = 0; i < MAX_QUICKBAR_SLOTS_COUNT; i++)
    {
      m_aQuickbarEnts[i] = new QuickBarItem;
      m_aQuickbarEnts[i].m_enabled = false;
      m_aQuickbarEnts[i].m_entity = NULL;
    }
    _player = player;
    m_slotsCount = 0;
  }
References _player, m_aQuickbarEnts, m_slotsCount, and MAX_QUICKBAR_SLOTS_COUNT.
Referenced by ManBase::Init().
SetEntityShortcut()
void SetEntityShortcut (EntityAI entity, int index, bool force = false) protected
Definition at line 144 of file QuickBarBase.c.
  {
    //Client
    if (GetGame().IsClient())
    {
      if (ScriptInputUserData.CanStoreInputUserData())
      {
        ScriptInputUserData ctx = new ScriptInputUserData;
        ctx.Write(INPUT_UDT_QUICKABARSHORTCUT);
        ctx.Write(entity);
        ctx.Write(index);
        ctx.Write(force);
        ctx.Send();
        _SetEntityShortcut(entity, index, force);
      }
    }
    //Server
    else if (GetGame().IsMultiplayer() && GetGame().IsServer())
      DayZPlayerSyncJunctures.SendQuickbarSetShortcut(_player, entity, index, force);
    else
    {
      // Single player
      _SetEntityShortcut(entity, index, force);
    }
  }
References _player, _SetEntityShortcut(), ScriptInputUserData::CanStoreInputUserData(), GetGame(), INPUT_UDT_QUICKABARSHORTCUT, and DayZPlayerSyncJunctures::SendQuickbarSetShortcut().
SetShotcutEnable()
void SetShotcutEnable (int index, bool value) protected
Definition at line 125 of file QuickBarBase.c.
  {
    m_aQuickbarEnts[index].m_enabled = value && CanAddAsShortcut(m_aQuickbarEnts[index].m_entity);
    if (!m_aQuickbarEnts[index].m_enabled)
      CancelContinuousUse(index);
    if (_player.m_Hud)
      _player.m_Hud.RefreshQuickbar(true);
  }
References _player, CanAddAsShortcut(), CancelContinuousUse(), and m_aQuickbarEnts.
SetSize()
void SetSize (int newSize) protected
Definition at line 34 of file QuickBarBase.c.
  {
    int i = m_slotsCount;
    if (newSize == m_slotsCount)
      return;
    if (newSize > MAX_QUICKBAR_SLOTS_COUNT)
      newSize = MAX_QUICKBAR_SLOTS_COUNT;
    if (newSize > i)
    {
      for (; i < newSize; i++)
      {
        EntityAI entity = m_aQuickbarEnts[i].m_entity;
        if (entity != NULL && entity.GetHierarchyRootPlayer() == _player)
          m_aQuickbarEnts[i].m_enabled = true;
      }
    }
    else
    {
      for (i--; i >= newSize; i--)
        m_aQuickbarEnts[i].m_enabled = false;
    }
    m_slotsCount = newSize;
    if (_player.m_Hud)
      _player.m_Hud.RefreshQuickbar(true);
  }
References _player, m_aQuickbarEnts, m_slotsCount, and MAX_QUICKBAR_SLOTS_COUNT.
UpdateShotcutVisibility()
void UpdateShotcutVisibility (int index) protected
Definition at line 115 of file QuickBarBase.c.
  {
    m_aQuickbarEnts[index].m_enabled = CanAddAsShortcut(m_aQuickbarEnts[index].m_entity);
    if (!m_aQuickbarEnts[index].m_enabled)
      CancelContinuousUse(index);
    if (_player.m_Hud)
      _player.m_Hud.RefreshQuickbar(true);
  }
References _player, CanAddAsShortcut(), CancelContinuousUse(), and m_aQuickbarEnts.
updateSlotsCount()
void updateSlotsCount () protected
Definition at line 224 of file QuickBarBase.c.
  {
    int slotsCount = _player.GetQuickBarBonus();
    int attCount = _player.GetInventory().AttachmentCount();
    for (int i = 0; i < attCount; ++i)
      slotsCount += _player.GetInventory().GetAttachmentFromIndex(i).GetQuickBarBonus();
    //max slots is 10
    SetSize(Math.Min(slotsCount, 10));
  }
References _player, Math::Min(), and SetSize().
~QuickBarBase()
void ~QuickBarBase () protected
Definition at line 270 of file QuickBarBase.c.
  {
  }
Variable Documentation
_player
PlayerBase _player protected
Definition at line 18 of file QuickBarBase.c.
Referenced by _RemoveEntity(), _SetEntity(), CanAddAsShortcut(), CancelContinuousUse(), ManBase::OnRPC(), QuickBarBase(), ScriptConsoleEnfScriptTab::RunEnscript(), SetEntityShortcut(), SetShotcutEnable(), SetSize(), UpdateShotcutVisibility(), and updateSlotsCount().
m_aQuickbarEnts
class QuickBarItem m_aQuickbarEnts[MAX_QUICKBAR_SLOTS_COUNT]
Referenced by _RemoveEntity(), _SetEntity(), FindEntityIndex(), GetEntity(), GetNonEmptyCount(), QuickBarBase(), SetShotcutEnable(), SetSize(), and UpdateShotcutVisibility().
m_slotsCount
int m_slotsCount protected
Definition at line 19 of file QuickBarBase.c.
Referenced by GetEntity(), GetNonEmptyCount(), GetSize(), QuickBarBase(), and SetSize().
MAX_QUICKBAR_SLOTS_COUNT
const int MAX_QUICKBAR_SLOTS_COUNT = 10
Definition at line 1 of file QuickBarBase.c.
Referenced by _RemoveEntity(), _SetEntity(), FindEntityIndex(), QuickBarBase(), and SetSize().