DayZ: CAContinuousEmptyMagazine Class Reference
CAContinuousEmptyMagazine Class Reference
Protected Member Functions
void CAContinuousEmptyMagazine (float eject_time)
override void Setup (ActionData action_data)
override int Execute (ActionData action_data)
override int Cancel (ActionData action_data)
override float GetProgress ()
void CalcAndSetQuantity (ActionData action_data)
Protected Attributes
float m_TargetUnits
float m_SpentQuantity
float m_Time
float m_TimeToEjectOneBullet
ref Param1< float > m_SpentUnits
Detailed Description
Definition at line 1 of file CAContinuousEmptyMagazine.c.
Constructor & Destructor Documentation
CAContinuousEmptyMagazine()
void CAContinuousEmptyMagazine::CAContinuousEmptyMagazine (float eject_time) inline protected
Definition at line 9 of file CAContinuousEmptyMagazine.c.
  {
    m_TimeToEjectOneBullet = eject_time;
    m_Time = 0;
  }
References m_Time, and m_TimeToEjectOneBullet.
Member Function Documentation
CalcAndSetQuantity()
void CAContinuousEmptyMagazine::CalcAndSetQuantity (ActionData action_data) inline protected
Definition at line 73 of file CAContinuousEmptyMagazine.c.
  {
    if (GetGame().IsServer())
    {
      if (action_data.m_MainItem)
      {
        Magazine itm;
        Class.CastTo(itm, action_data.m_MainItem);
        if (m_SpentUnits)
        {
          m_SpentUnits.param1 = m_SpentQuantity;
          SetACData(m_SpentUnits);
        }
        itm.ServerAddAmmoCount(-m_SpentQuantity);
      }
    }
  }
References Class::CastTo(), GetGame(), m_SpentQuantity, m_SpentUnits, and CABase::SetACData().
Cancel()
override int CAContinuousEmptyMagazine::Cancel (ActionData action_data) inline protected
Definition at line 56 of file CAContinuousEmptyMagazine.c.
  {
    if (!action_data.m_Player || !action_data.m_MainItem)
      return UA_ERROR;
    CalcAndSetQuantity(action_data);
    return UA_CANCEL;
  }
References CalcAndSetQuantity(), UA_CANCEL, and UA_ERROR.
Execute()
override int CAContinuousEmptyMagazine::Execute (ActionData action_data) inline protected
Definition at line 28 of file CAContinuousEmptyMagazine.c.
  {
    if (!action_data.m_Player)
      return UA_ERROR;
    if (m_TargetUnits == 0)
      return UA_FINISHED;
    else
    {
      if (m_SpentQuantity < m_TargetUnits)
      {
        m_Time += action_data.m_Player.GetDeltaT();
        if (m_Time > m_TimeToEjectOneBullet)
        {
          m_Time = 0;
          m_SpentQuantity += 1;
        }
        return UA_PROCESSING;
      }
      else
      {
        CalcAndSetQuantity(action_data);
        OnCompletePogress(action_data);
        return UA_FINISHED;
      }
    }
  }
References CalcAndSetQuantity(), m_SpentQuantity, m_TargetUnits, m_Time, m_TimeToEjectOneBullet, CAContinuousBase::OnCompletePogress(), UA_ERROR, UA_FINISHED, and UA_PROCESSING.
GetProgress()
override float CAContinuousEmptyMagazine::GetProgress () inline protected
Definition at line 65 of file CAContinuousEmptyMagazine.c.
  {
    //float progress = m_SpentQuantity/m_TargetUnits;
    return m_SpentQuantity / m_TargetUnits;
  }
References m_SpentQuantity, and m_TargetUnits.
Setup()
override void CAContinuousEmptyMagazine::Setup (ActionData action_data) inline protected
Definition at line 15 of file CAContinuousEmptyMagazine.c.
  {
    if (!m_SpentUnits)
      m_SpentUnits = new Param1<float>(0);
    else
      m_SpentUnits.param1 = 0;
    m_SpentQuantity = 0;
    Magazine itm;
    Class.CastTo(itm, action_data.m_MainItem);
    m_TargetUnits = itm.GetAmmoCount();
  }
References Class::CastTo(), m_SpentQuantity, m_SpentUnits, and m_TargetUnits.
Member Data Documentation
m_SpentQuantity
float CAContinuousEmptyMagazine::m_SpentQuantity protected
Definition at line 4 of file CAContinuousEmptyMagazine.c.
Referenced by CalcAndSetQuantity(), Execute(), GetProgress(), and Setup().
m_SpentUnits
ref Param1<float> CAContinuousEmptyMagazine::m_SpentUnits protected
Definition at line 7 of file CAContinuousEmptyMagazine.c.
Referenced by CalcAndSetQuantity(), and Setup().
m_TargetUnits
float CAContinuousEmptyMagazine::m_TargetUnits protected
Definition at line 3 of file CAContinuousEmptyMagazine.c.
Referenced by Execute(), GetProgress(), and Setup().
m_Time
float CAContinuousEmptyMagazine::m_Time protected
Definition at line 5 of file CAContinuousEmptyMagazine.c.
Referenced by CAContinuousEmptyMagazine(), and Execute().
m_TimeToEjectOneBullet
float CAContinuousEmptyMagazine::m_TimeToEjectOneBullet protected
Definition at line 6 of file CAContinuousEmptyMagazine.c.
Referenced by CAContinuousEmptyMagazine(), and Execute().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousEmptyMagazine.c