DayZ: Debug Class Reference
Debug Class Reference
Static Private Member Functions
static string GetDebugName (Managed entity)
static void InitCanvas ()
static void ClearCanvas ()
static void CanvasDrawLine (float x1, float y1, float x2, float y2, float width, int color)
static void CanvasDrawPoint (float x1, float y1, int color)
Draws a "point" on the screen at x,y coordinates Debug.ClearCanvas(); for(int i = 0; i < 700;i++) { float val = i/700; float y = Easing.EaseInOutExpo(val); Debug.CanvasDrawPoint(i,y*700,ARGBF(0.6, 1, 1, 1)); }.
static void Init ()
static void DestroyAllShapes ()
static void RemoveShape (out Shape shape)
static void Log (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
Prints debug message with normal prio.
static void ActionLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void SymptomLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void InventoryMoveLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void InventoryReservationLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void InventoryHFSMLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void QuickbarLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void BaseBuildingLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void BleedingChancesLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void TriggerLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void ParticleLog (string message=LOG_DEFAULT, Managed caller=null, string function="", Managed entity=null)
static void TFLog (string message=LOG_DEFAULT, TestFramework caller=null, string function="")
static void WeightLog (string message=LOG_DEFAULT, Managed caller=null, string function="", Managed entity=null)
static void MeleeLog (Entity entity, string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT)
static void WeatherLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void LogInfo (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
Prints debug message with normal prio.
static void LogWarning (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
Prints debug message as warning message.
static void LogError (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
Prints debug message as error message.
static void LogArrayInt (array< int > arr=NULL, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void LogArrayString (array< string > arr=NULL, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void ReceivedLogMessageFromServer (string message)
static void ClearScriptLogs ()
static Shape DrawBox (vector pos1, vector pos2, int color=0x1fff7f7f)
static Shape DrawBoxEx (vector pos1, vector pos2, int color=0x1fff7f7f, ShapeFlags flags=ShapeFlags.TRANSP|ShapeFlags.NOZWRITE)
static Shape DrawCube (vector pos, float size=1, int color=0x1fff7f7f)
static Shape DrawSphere (vector pos, float size=1, int color=0x1fff7f7f, ShapeFlags flags=ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE)
static Shape DrawFrustum (float horizontalAngle, float verticalAngle, float length, int color=0x1fff7f7f, ShapeFlags flags=ShapeFlags.TRANSP|ShapeFlags.WIREFRAME)
static Shape DrawCylinder (vector pos, float radius, float height=1, int color=0x1fff7f7f, ShapeFlags flags=ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE)
static array< Shape > DrawCone (vector pos, float lenght, float halfAngle, float offsetAngle, int color=0xFFFFFFFF, int flags=0)
static Shape DrawLine (vector from, vector to, int color=0xFFFFFFFF, int flags=0)
static Shape DrawLines (vector[] positions, int count, int color=0xFFFFFFFF, int flags=0)
static Shape DrawArrow (vector from, vector to, float size=0.5, int color=0xFFFFFFFF, int flags=0)
static void GetBaseConfigClasses (out TStringArray base_classes)
Returns some of base config classes strings like CfgVehicles, CfgWeapons, etc. for searching purposes.
static void GetFiltredConfigClasses (string search_string, out TStringArray filtered_classes, bool only_public=true)
Returns config classes containing search_string in name.
string LogMessage (string level, string plugin, string entity, string author, string label, string message)
DEPRECATED.
void SaveLog (string log_message)
static void ClearLogs ()
static string GetFileName ()
string GetDate ()
Static Private Attributes
const string LOG_DEBUG = "Debug"
const string LOG_DEBUG_ACTION = "Action"
const string LOG_DEBUG_SYMPTOM = "Symptom"
const string LOG_DEBUG_INV_MOVE = "Inv Move"
const string LOG_DEBUG_INV_RESERVATION = "Inv Rrsv"
const string LOG_DEBUG_INV_HFSM = "HFSM"
const string LOG_DEBUG_QUICKBAR = "Quickbar"
const string LOG_DEBUG_BASEBUILDING = "Base Building"
const string LOG_DEBUG_BLEEDING_CHANCES = "Bleeding"
const string LOG_DEBUG_TRIGGER = "Trigger"
const string LOG_DEBUG_PARTICLE = "Particle"
const string LOG_DEBUG_TF = "TestFramework"
const string LOG_DEBUG_WEIGHT = "Weight"
const string LOG_DEBUG_MELEE = "Melee"
const string LOG_DEBUG_WEATHER = "Weather"
const string LOG_INFO = "Info"
const string LOG_WARNING = "Warning"
const string LOG_ERROR = "Error"
const string LOG_DEFAULT = "n/a"
ref array< Shape > m_DebugShapes
static Widget m_DebugLayoutCanvas
static CanvasWidget m_CanvasDebug
bool m_EnabledLogs
Detailed Description
Definition at line 13 of file Debug.c.
Member Function Documentation
ActionLog()
static void Debug::ActionLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 143 of file Debug.c.
  {
    string res = LogMessage(LOG_DEBUG_ACTION, plugin, entity, author, label, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LOG_DEBUG_ACTION, LogMessage(), and PrintToRPT().
Referenced by ActionManagerClient::ActionStart(), EntityAI::AddAction(), AddAction(), InventoryItem::AddAction(), AnimatedActionBase::Do(), AnimatedActionBase::End(), ActionInput::Init(), ActionInteractBaseCB::InitActionComponent(), ActionBaseCB::Interrupt(), ActionManagerClient::LockInventory(), OnActionEnd(), AnimatedActionBase::OnAnimationEvent(), ActionContinuousBaseCB::OnAnimationEvent(), ActionInteractBaseCB::OnAnimationEvent(), ActionContinuousBase::OnEndAnimationLoop(), ActionBaseCB::OnFinish(), ActionContinuousBase::OnFinishProgress(), ActionContinuousBase::OnStartAnimationLoop(), ActionManagerClient::ProcessActionInputEnd(), ActionManagerClient::ProcessActionRequestEnd(), ActionInput::SetInput(), SetupAction(), Start(), ActionManagerServer::StartDeliveredAction(), ActionManagerClient::UnlockInventory(), and ActionManagerServer::Update().
BaseBuildingLog()
static void Debug::BaseBuildingLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 203 of file Debug.c.
  {
    string res = LogMessage(LOG_DEBUG_BASEBUILDING, plugin, entity, author, label, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LOG_DEBUG_BASEBUILDING, LogMessage(), and PrintToRPT().
BleedingChancesLog()
static void Debug::BleedingChancesLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 213 of file Debug.c.
  {
    string res = LogMessage(LOG_DEBUG_BLEEDING_CHANCES, plugin, entity, author, label, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LOG_DEBUG_BLEEDING_CHANCES, LogMessage(), and PrintToRPT().
Referenced by BleedChanceData::CalculateBleedChance(), and BleedingSourcesManagerBase::ProcessHit().
CanvasDrawLine()
static void Debug::CanvasDrawLine (float x1, float y1, float x2, float y2, float width, int color) inline static private
Definition at line 69 of file Debug.c.
  {
    InitCanvas();
    m_CanvasDebug.DrawLine(x1, y1, x2, y2, width, color);
  }
References InitCanvas(), and m_CanvasDebug.
Referenced by CanvasDrawPoint().
CanvasDrawPoint()
static void Debug::CanvasDrawPoint (float x1, float y1, int color) inline static private
Draws a "point" on the screen at x,y coordinates Debug.ClearCanvas(); for(int i = 0; i < 700;i++) { float val = i/700; float y = Easing.EaseInOutExpo(val); Debug.CanvasDrawPoint(i,y*700,ARGBF(0.6, 1, 1, 1)); }.
Definition at line 86 of file Debug.c.
  {
    CanvasDrawLine(x1, y1, x1 + 1, y1, 1, color);
  }
References CanvasDrawLine().
ClearCanvas()
static void Debug::ClearCanvas () inline static private
Definition at line 63 of file Debug.c.
  {
    if (m_CanvasDebug)
      m_CanvasDebug.Clear();
  }
References m_CanvasDebug.
ClearLogs()
static void Debug::ClearLogs () inline static private
Definition at line 638 of file Debug.c.
  {
    if (FileExist(GetFileName()))
    {
      FileHandle fileHandle = OpenFile(GetFileName(), FileMode.WRITE);
      if (fileHandle == 0)
        return;
      FPrintln(fileHandle, "");
      CloseFile(fileHandle);
    }
  }
References CloseFile(), FileExist(), FPrintln(), GetFileName(), and OpenFile().
Referenced by ScriptConsoleEnfScriptTab::Clear(), ScriptConsoleOutputTab::Clear(), and ClearScriptLogs().
ClearScriptLogs()
static void Debug::ClearScriptLogs () inline static private
Definition at line 396 of file Debug.c.
  {
    ClearLogs();
  }
References ClearLogs().
DestroyAllShapes()
static void Debug::DestroyAllShapes () inline static private
Definition at line 96 of file Debug.c.
  {
    for (int i = 0; i < m_DebugShapes.Count(); ++i)
    {
      if (m_DebugShapes.Get(i))
        m_DebugShapes.Get(i).Destroy();
    }
    m_DebugShapes.Clear();
  }
References m_DebugShapes.
DrawArrow()
static Shape Debug::DrawArrow (vector from, vector to, float size = 0.5, int color = 0xFFFFFFFF, int flags = 0) inline static private
Definition at line 511 of file Debug.c.
  {
    Shape shape = Shape.CreateArrow(from, to, size, color, flags);
    m_DebugShapes.Insert(shape);
    return shape;
  }
References m_DebugShapes, and Shape.
Referenced by Component::DebugDirectionDraw(), PluginBase::DrawDebugs(), DrawDebugShape(), SceneObject::EditorLineAdd(), and UIScriptedMenu::Update().
DrawBox()
static Shape Debug::DrawBox (vector pos1, vector pos2, int color = 0x1fff7f7f) inline static private
Definition at line 401 of file Debug.c.
  {
    return DrawBoxEx(pos1, pos2, color, ShapeFlags.TRANSP | ShapeFlags.NOZWRITE);
  }
References DrawBoxEx().
Referenced by Component::DebugBBoxDraw(), Transport::DebugFreeAreaAtDoor(), EntityAI::DebugFreeAreaAtDoor(), DrawDebugCollisionBox(), and SceneObject::EditorShapeAdd().
DrawBoxEx()
static Shape Debug::DrawBoxEx (vector pos1, vector pos2, int color = 0x1fff7f7f, ShapeFlags flags = ShapeFlags.TRANSP | ShapeFlags.NOZWRITE) inline static private
Definition at line 406 of file Debug.c.
  {
    Shape shape = Shape.Create(ShapeType.BBOX, color, flags, pos1, pos2);
    if ((flags & ShapeFlags.ONCE) == 0)
      m_DebugShapes.Insert(shape);
    return shape;
  }
References m_DebugShapes, and Shape.
Referenced by DrawBox().
DrawCone()
static array< Shape > Debug::DrawCone (vector pos, float lenght, float halfAngle, float offsetAngle, int color = 0xFFFFFFFF, int flags = 0) inline static private
Definition at line 458 of file Debug.c.
  {
    array<Shape> shapes = new array<Shape>;
    vector endL, endR;
    Math3D.ConePoints(pos, lenght, halfAngle, offsetAngle, endL, endR);
    // Left side
    shapes.Insert(Debug.DrawLine(pos, endL, color, flags));
    // Rigth side
    shapes.Insert(Debug.DrawLine(pos, endR, color, flags));
    // Top side
    shapes.Insert(Debug.DrawLine(endL, endR, color, flags));
    // Middle (height) line
    shapes.Insert(Debug.DrawLine(pos, pos + Vector(Math.Cos(offsetAngle), 0, Math.Sin(offsetAngle)).Normalized() * lenght, color, flags));
    return shapes;
  }
References Math3D::ConePoints(), Math::Cos(), DrawLine(), Math::Sin(), and Vector().
DrawCube()
static Shape Debug::DrawCube (vector pos, float size = 1, int color = 0x1fff7f7f) inline static private
Definition at line 414 of file Debug.c.
  {
    vector min = pos;
    vector max = pos;
    float size_h = size * 0.5;
    min[0] = min[0] - size_h;
    min[1] = min[1] - size_h;
    min[2] = min[2] - size_h;
    max[0] = max[0] + size_h;
    max[1] = max[1] + size_h;
    max[2] = max[2] + size_h;
    Shape shape = Shape.Create(ShapeType.DIAMOND, color, ShapeFlags.TRANSP | ShapeFlags.NOZWRITE, min, max);
    m_DebugShapes.Insert(shape);
    return shape;
  }
References m_DebugShapes, and Shape.
DrawCylinder()
static Shape Debug::DrawCylinder (vector pos, float radius, float height = 1, int color = 0x1fff7f7f, ShapeFlags flags = ShapeFlags.TRANSP | ShapeFlags.NOOUTLINE) inline static private
Definition at line 450 of file Debug.c.
  {
    Shape shape = Shape.CreateCylinder(color, flags, pos, radius, height);
    if ((flags & ShapeFlags.ONCE) == 0)
      m_DebugShapes.Insert(shape);
    return shape;
  }
References m_DebugShapes, and Shape.
Referenced by PluginBase::DrawDebugs().
DrawFrustum()
static Shape Debug::DrawFrustum (float horizontalAngle, float verticalAngle, float length, int color = 0x1fff7f7f, ShapeFlags flags = ShapeFlags.TRANSP | ShapeFlags.WIREFRAME) inline static private
Definition at line 442 of file Debug.c.
  {
    Shape shape = Shape.CreateFrustum(horizontalAngle, verticalAngle, length, color, flags);
    if ((flags & ShapeFlags.ONCE) == 0)
      m_DebugShapes.Insert(shape);
    return shape;
  }
References m_DebugShapes, and Shape.
DrawLine()
static Shape Debug::DrawLine (vector from, vector to, int color = 0xFFFFFFFF, int flags = 0) inline static private
DrawLine \nFlags:
ShapeFlags.NOZBUFFER
ShapeFlags.NOZUPDATE
ShapeFlags.DOUBLESIDE
ShapeFlags.WIREFRAME
ShapeFlags.TRANSP
ShapeFlags.ONCE
ShapeFlags.NOOUTLINE
ShapeFlags.NOCULL
Definition at line 489 of file Debug.c.
  {
    vector pts[2]
    pts[0] = from;
    pts[1] = to;
    Shape shape = Shape.CreateLines(color, flags, pts, 2);
    if ((flags & ShapeFlags.ONCE) == 0)
      m_DebugShapes.Insert(shape);
    //m_DebugShapes.Debug();
    return shape;
  }
References m_DebugShapes, and Shape.
Referenced by CalculateEyeAccoTarget(), DrawCone(), WeaponDebug::DrawLineOfFire(), WeaponDebug::DrawLineOfFireCameraHybrid(), WeaponDebug::DrawLineOfFireMuzzleToHit(), PluginBase::EditorUpdateRuler(), GatherSurfaces(), and GetMeleeTargetEx().
DrawLines()
static Shape Debug::DrawLines (vector[] positions, int count, int color = 0xFFFFFFFF, int flags = 0) inline static private
Definition at line 502 of file Debug.c.
  {
    Shape shape = Shape.CreateLines(color, flags, positions, count);
    if ((flags & ShapeFlags.ONCE) == 0)
      m_DebugShapes.Insert(shape);
    return shape;
  }
References m_DebugShapes, and Shape.
Referenced by WeaponDebug::OnPostFrameUpdate().
DrawSphere()
static Shape Debug::DrawSphere (vector pos, float size = 1, int color = 0x1fff7f7f, ShapeFlags flags = ShapeFlags.TRANSP | ShapeFlags.NOOUTLINE) inline static private
Definition at line 434 of file Debug.c.
  {
    Shape shape = Shape.CreateSphere(color, flags, pos, size);
    if ((flags & ShapeFlags.ONCE) == 0)
      m_DebugShapes.Insert(shape);
    return shape;
  }
References m_DebugShapes, and Shape.
Referenced by CalculateEyeAccoTarget(), WeaponDebug::DrawBarrelMemoryPoints(), DrawDebugShape(), WeaponDebug::DrawEyePoint(), WeaponDebug::DrawLineOfFire(), WeaponDebug::DrawLineOfFireCameraHybrid(), WeaponDebug::DrawLineOfFireMuzzleToHit(), PluginBase::EditorUpdateRuler(), Hologram::GetProjectionEntityPosition(), PluginBase::OnUpdate(), and SpookyEventBase::Perform().
GetBaseConfigClasses()
static void Debug::GetBaseConfigClasses (out TStringArray base_classes) inline static private
Returns some of base config classes strings like CfgVehicles, CfgWeapons, etc. for searching purposes.
Parameters
base_classes out TStringArray Array containing some of base config classes
Definition at line 523 of file Debug.c.
  {
    base_classes.Clear();
    base_classes.Insert(CFG_VEHICLESPATH);
    base_classes.Insert(CFG_WEAPONSPATH);
    base_classes.Insert(CFG_MAGAZINESPATH);
    base_classes.Insert(CFG_AMMO);
    base_classes.Insert(CFG_WORLDS);
    base_classes.Insert(CFG_SURFACES);
    base_classes.Insert(CFG_SOUND_SETS);
    base_classes.Insert(CFG_SOUND_SHADERS);
    base_classes.Insert(CFG_NONAI_VEHICLES);
    base_classes.Insert(CFG_SOUND_TABLES);
  }
References CFG_AMMO, CFG_MAGAZINESPATH, CFG_NONAI_VEHICLES, CFG_SOUND_SETS, CFG_SOUND_SHADERS, CFG_SOUND_TABLES, CFG_SURFACES, CFG_VEHICLESPATH, CFG_WEAPONSPATH, and CFG_WORLDS.
Referenced by UIPopupScript::ClearHierarchy(), UIPopupScript::FindInHierarchy(), GetFiltredConfigClasses(), and ScriptConsoleConfigTab::Init().
GetDate()
string Debug::GetDate () inline static private
Definition at line 656 of file Debug.c.
  {
    int year;
    int month;
    int day;
    int hour;
    int minute;
    int second;
    GetYearMonthDay(year, month, day);
    GetHourMinuteSecond(hour, minute, second);
    string date = month.ToStringLen(2) + "-" + day.ToStringLen(2) + " " + hour.ToStringLen(2) + ":" + minute.ToStringLen(2) + ":" + second.ToStringLen(2);
    return date;
  }
References GetHourMinuteSecond(), and GetYearMonthDay().
Referenced by LogMessage().
GetDebugName()
static string Debug::GetDebugName (Managed entity) inline static private
Definition at line 42 of file Debug.c.
  {
    if (!entity)
      return "";
    Object obj;
    if (CastTo(obj, entity))
      return obj.GetDebugNameNative();
    return entity.GetDebugName();
  }
GetFileName()
static string Debug::GetFileName () inline static private
Definition at line 651 of file Debug.c.
  {
    return CFG_FILE_SCRIPT_LOG_EXT;
  }
References CFG_FILE_SCRIPT_LOG_EXT.
Referenced by ClearLogs(), ScriptConsoleOutputTab::ReloadOutput(), and SaveLog().
GetFiltredConfigClasses()
static void Debug::GetFiltredConfigClasses (string search_string, out TStringArray filtered_classes, bool only_public = true) inline static private
Returns config classes containing search_string in name.
Parameters
search_string string String to search in class names
filtered_classes out TStringArray Array containing filtered classes based on search_string
only_public bool Set to true to return only public classes, set to false to return all filtered classes
Definition at line 544 of file Debug.c.
  {
    TStringArray searching_in = new TStringArray;
    GetBaseConfigClasses(searching_in);
    filtered_classes.Clear();
    search_string.ToLower();
    for (int s = 0; s < searching_in.Count(); ++s)
    {
      string config_path = searching_in.Get(s);
      int objects_count = GetGame().ConfigGetChildrenCount(config_path);
      for (int i = 0; i < objects_count; i++)
      {
        string childName;
        GetGame().ConfigGetChildName(config_path, i, childName);
        if (only_public)
        {
          int scope = GetGame().ConfigGetInt(config_path + " " + childName + " scope");
          if (scope == 0)
            continue;
        }
        string nchName = childName;
        nchName.ToLower();
        if (nchName.Contains(search_string) != -1)
          filtered_classes.Insert(childName);
      }
    }
  }
References GetBaseConfigClasses(), and GetGame().
Init()
static void Debug::Init () inline static private
Definition at line 91 of file Debug.c.
  {
    m_DebugShapes = new array<Shape>;
  }
References m_DebugShapes.
Referenced by CGame::DayZGame().
InitCanvas()
static void Debug::InitCanvas () inline static private
Definition at line 54 of file Debug.c.
  {
    if (!m_DebugLayoutCanvas)
    {
      m_DebugLayoutCanvas = GetGame().GetWorkspace().CreateWidgets("gui/layouts/debug/day_z_debugcanvas.layout");
      m_CanvasDebug = CanvasWidget.Cast(m_DebugLayoutCanvas.FindAnyWidget("CanvasWidget"));
    }
  }
References GetGame(), m_CanvasDebug, and m_DebugLayoutCanvas.
Referenced by CanvasDrawLine().
InventoryHFSMLog()
static void Debug::InventoryHFSMLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 183 of file Debug.c.
  {
    string res = LogMessage(LOG_DEBUG_INV_HFSM, plugin, entity, author, label, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LOG_DEBUG_INV_HFSM, LogMessage(), and PrintToRPT().
Referenced by HandActionBase::Action(), HandEventBase::CanPerformEvent(), HandEventSwap::CanPerformEvent(), HandEventBase::CanPerformEventEx(), HandEventBase::CheckRequest(), HandEventSwap::CheckRequest(), HandEventBase::CheckRequestSrc(), HandGuardBase::GuardCondition(), HandGuardHasItemInEvent::GuardCondition(), HandleHandEvent(), HandleTakeToDst(), HandStateBase::OnAbort(), HandStateBase::OnEntry(), HandStartAction::OnEntry(), and HumanInventoryWithFSM::ProcessHandEvent().
InventoryMoveLog()
static void Debug::InventoryMoveLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 163 of file Debug.c.
  {
    string res = LogMessage(LOG_DEBUG_INV_MOVE, plugin, entity, author, label, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LOG_DEBUG_INV_MOVE, LogMessage(), and PrintToRPT().
Referenced by GameInventory::AddInventoryReservationEx(), GameInventory::ClearInventoryReservationEx(), GameInventory::ExtendInventoryReservationEx(), ForceSwapEntities(), HandleForceSwapEntities(), HandleSwapEntities(), HandleTakeToDst(), StoreInputForRemotes(), SwapEntities(), TakeToDst(), TryAcquireTwoInventoryJuncturesFromServer(), ValidateDestroy(), ValidateHandEvent(), ValidateSwap(), and ValidateSyncMove().
InventoryReservationLog()
static void Debug::InventoryReservationLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 173 of file Debug.c.
  {
    string res = LogMessage(LOG_DEBUG_INV_RESERVATION, plugin, entity, author, label, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LOG_DEBUG_INV_RESERVATION, LogMessage(), and PrintToRPT().
Referenced by CGame::AddInventoryJunctureEx(), CGame::ClearJunctureEx(), and TryAcquireTwoInventoryJuncturesFromServer().
Log()
static void Debug::Log (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Prints debug message with normal prio.
Parameters
msg string Debug message for print
Returns
void None
Debug.Log("Hello World");
>> [Log]: Hello World;
Definition at line 133 of file Debug.c.
  {
    string res = LogMessage(LOG_DEBUG, plugin, entity, author, label, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LOG_DEBUG, LogMessage(), and PrintToRPT().
Referenced by InventoryItem::AddAction(), RecipeBase::ApplyModificationsResults(), Managed::BleedingIndicator(), PluginRecipesManagerBase::CallbackGenerateCache(), ChangePPEMaterial(), CheckContactCache(), PlayerSpawnHandler::CreateChildItem(), PPEManagerStatic::CreateManagerStatic(), DamageCrew(), Debug(), RecipeBase::Do(), ScriptConsoleItemsTab::DrawItems(), SpookyArea::EEInit(), EOnPostSimulate(), KeysToUIElements::GetKeyToUIElement(), GetName(), PlayerSpawnPreset::GetRandomCharacterType(), Managed::GetRequester(), Managed::GetRequester(), Managed::GetRequesterID(), Managed::GetRequesterTypename(), LogTemplates::GetTemplate(), GetValue(), ManBase::HideHairSelections(), MissionBase::InvokeOnConnect(), MissionBase::InvokeOnDisconnect(), PlayerSpawnPreset::IsValid(), IsValid(), PlayerSpawnPresetDiscreteItemSetSlotData::IsValid(), MessageReceiverBase::Log(), Entity::Log(), PluginBase::Log(), Environment::LogDryWetProcess(), BloodTypes::MatchBloodCompatibility(), Entity::OnAction(), ManBase::OnConnect(), OnContact(), ManBase::OnDisconnect(), MissionBase::OnEvent(), ActionDigInStash::OnFinishProgressServer(), Icon::OnPerformRecipe(), ManBase::OnReconnect(), DayZPlayer::OnSoundEvent(), DayZPlayer::OnStepEvent(), OpenAndSwitchLambda::OnSuccess(), OnUpdate(), RecipeBase::PerformRecipe(), InventoryItem::PlayDeployFinishSound(), InventoryItem::PlayDeployLoopSoundEx(), InventoryItem::PlayDeploySound(), MissionBase::PlayerControlDisable(), InventoryItem::PlayPlaceSound(), PlayerAgentPool::PrintAgents(), PrintOut(), PluginRecipesManagerBase::PrintResultMasks(), ItemBase::PrintSlots(), PlayerSpawnHandler::ProcessCargoEquipment(), PlayerSpawnHandler::ProcessSlotsEquipment(), InventoryLocation::ReadFromContext(), GameplayEffectsData::RegisterData(), KeysToUIElements::RegisterKeyToUIElement(), LogTemplates::RegisterLogTamplate(), Managed::RegisterRequester(), PluginBase::Repair(), ManBase::Save(), PPERequesterBase::SetRequesterUpdating(), SetRequestUpdating(), SetupAnimation(), PlayerSpawnHandler::SpawnComplexChildrenItems(), PlayerSpawnHandler::SpawnDiscreteSlotItemSet(), RecipeBase::SpawnItems(), PlayerSpawnHandler::SpawnSimpleChildrenItems(), TranslateAndValidateSlot(), Entity::TryDelete(), and Managed::VerifyRequester().
LogArrayInt()
static void Debug::LogArrayInt (array< int > arr = NULL, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 351 of file Debug.c.
  {
    if (arr == null)
      return;
    string res;
    for (int i = 0; i < arr.Count(); i++)
      res += LogMessage(LOG_DEBUG, plugin, entity, author, label, arr.Get(i).ToString());
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LOG_DEBUG, LogMessage(), and PrintToRPT().
LogArrayString()
static void Debug::LogArrayString (array< string > arr = NULL, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 367 of file Debug.c.
  {
    if (arr == null)
      return;
    string res;
    for (int i = 0; i < arr.Count(); i++)
      res += LogMessage(LOG_DEBUG, plugin, entity, author, label, arr.Get(i));
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LOG_DEBUG, LogMessage(), and PrintToRPT().
Referenced by PrintOut().
LogError()
static void Debug::LogError (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Prints debug message as error message.
Parameters
msg string Debug message for error print
Returns
void None
Debug.LogError("Hello World, this is error log");
>> [Error]: Hello World, this is error log
Definition at line 341 of file Debug.c.
  {
    string res = LogMessage(LOG_ERROR, plugin, entity, author, label, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LOG_ERROR, LogMessage(), and PrintToRPT().
Referenced by EntityAI::AddAction(), AddAction(), InventoryItem::AddAction(), ActionCollectBloodTargetLambda::CopyOldPropertiesToNew(), TanLeatherLambda::CopyOldPropertiesToNew(), ReplaceItemWithNewLambda::CopyOldPropertiesToNew(), DeveloperFreeCamera::DisableFreeCamera(), DeveloperFreeCamera::EnableFreeCamera(), FireworksLauncherClientEvent::FireworksLauncherClientEvent(), Entity::GetDefaultHitComponent(), Entity::GetDefaultHitPosition(), Entity::GetDefaultHitPositionComponent(), Entity::GetHitComponentForAI(), FireworksLauncherClientEvent::GetShotPos(), Entity::GetSuitableFinisherHitComponents(), LogError(), Entity::LogError(), Component::LogErrorBadCompType(), Component::LogThisError(), Component::LogWarningAlredyExist(), Normalize(), OnStoreLoad(), SymptomManager::OnSymptomExit(), OpenItem::OpenAndSwitch(), PlaySound(), InventoryItem::SetQuantity(), and Tick().
LogInfo()
static void Debug::LogInfo (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Prints debug message with normal prio.
Parameters
msg string Debug message for print
Returns
void None
Debug.Log("Hello World");
>> [Log]: Hello World;
Definition at line 301 of file Debug.c.
  {
    string res = LogMessage(LOG_INFO, plugin, entity, author, label, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LOG_INFO, LogMessage(), and PrintToRPT().
Referenced by LogInfo().
LogMessage()
string Debug::LogMessage (string level, string plugin, string entity, string author, string label, string message) inline static private
DEPRECATED.
Definition at line 584 of file Debug.c.
  {
    if (GetGame() == null || !LogManager.IsLogsEnable())
      return string.Empty;
    bool is_server_log = (GetGame().IsServer() && GetGame().IsMultiplayer());
    // Formation output to external file
    // %date{MM-dd HH:mm:ss} | %Enviroment | %Level | %Module | %Entity | %Author | %Label | %Message
    string date = GetDate();
    string env = "Client";
    string msg = string.Empty;
    if (is_server_log)
      env = "Server";
    msg = string.Format("%1 | %2 | %3 | %4 | %5 | %6 | %7", date, env, level, plugin, entity, label, message);
    if (is_server_log)
    {
      SaveLog(msg);
#ifdef DEVELOPER //not sendig log to clients on stable
      Param1<string> msg_p = new Param1<string>(msg);
      CallMethod(CALL_ID_SEND_LOG, msg_p);
#endif
    }
    else
      SaveLog(msg);
    return msg;
  }
References CALL_ID_SEND_LOG, CallMethod(), string::Empty, GetDate(), GetGame(), LogManager::IsLogsEnable(), and SaveLog().
Referenced by ActionLog(), BaseBuildingLog(), BleedingChancesLog(), InventoryHFSMLog(), InventoryMoveLog(), InventoryReservationLog(), Log(), LogArrayInt(), LogArrayString(), LogError(), LogInfo(), LogWarning(), MeleeLog(), ParticleLog(), QuickbarLog(), SymptomLog(), TFLog(), TriggerLog(), and WeatherLog().
LogWarning()
static void Debug::LogWarning (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Prints debug message as warning message.
Parameters
msg string Debug message for warning print
Returns
void None
Debug.LogWarning("Hello World, this is warning log");
>> [Warning]: Hello World, this is warning log
Definition at line 321 of file Debug.c.
  {
    string res = LogMessage(LOG_WARNING, plugin, entity, author, label, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LOG_WARNING, LogMessage(), and PrintToRPT().
Referenced by Entity::CanDisplayAttachmentSlot(), Component::LogThisWarning(), Entity::LogWarning(), and DeveloperTeleport::TeleportAtCursor().
MeleeLog()
static void Debug::MeleeLog (Entity entity, string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT) inline static private
Definition at line 267 of file Debug.c.
  {
    string logMessage = string.Format("%1: %2", entity.GetSimulationTimeStamp(), message);
    string res = LogMessage(LOG_DEBUG_MELEE, plugin, GetDebugName(entity), author, label, logMessage);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References GetDebugName(), LOG_DEBUG_MELEE, LogMessage(), and PrintToRPT().
ParticleLog()
static void Debug::ParticleLog (string message = LOG_DEFAULT, Managed caller = null, string function = "", Managed entity = null) inline static private
Definition at line 233 of file Debug.c.
  {
    string res = LogMessage(LOG_DEBUG_PARTICLE, GetDebugName(caller), GetDebugName(entity), "", function, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References GetDebugName(), LOG_DEBUG_PARTICLE, LogMessage(), and PrintToRPT().
Referenced by PMTF::PrintActiveStats(), PMTF::PrintPMStats(), TestInvalidSize(), and TestOwnership().
QuickbarLog()
static void Debug::QuickbarLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 193 of file Debug.c.
  {
    string res = LogMessage(LOG_DEBUG_QUICKBAR, plugin, entity, author, label, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LOG_DEBUG_QUICKBAR, LogMessage(), and PrintToRPT().
ReceivedLogMessageFromServer()
static void Debug::ReceivedLogMessageFromServer (string message) inline static private
Definition at line 383 of file Debug.c.
  {
    if (!LogManager.IsLogsEnable())
      return;
    SaveLog(message);
#ifdef LOG_TO_RPT
    if (message.Length() > 0)
      PrintToRPT("" + message);
#endif
  }
References LogManager::IsLogsEnable(), PrintToRPT(), and SaveLog().
Referenced by PluginBase::OnRPCServerLogRecieved().
RemoveShape()
static void Debug::RemoveShape (out Shape shape) inline static private
Definition at line 107 of file Debug.c.
  {
    if (!shape) return;
    for (int i = 0; i < m_DebugShapes.Count(); i++)
    {
      Shape found_shape = m_DebugShapes.Get(i);
      if (found_shape && found_shape == shape)
      {
        found_shape.Destroy();
        m_DebugShapes.Remove(i); // Mandatory! Otherwise the Destroy() function causes crash!
        shape = null;
        return;
      }
    }
  }
References m_DebugShapes, and Shape.
Referenced by PluginBase::CleanupDebugShapes(), WeaponDebug::DrawLineOfFire(), WeaponDebug::DrawLineOfFireCameraHybrid(), WeaponDebug::DrawLineOfFireMuzzleToHit(), WeaponDebug::RemoveAllShapes(), and RemoveDebugShape().
SaveLog()
void Debug::SaveLog (string log_message) inline static private
Definition at line 617 of file Debug.c.
  {
#ifndef SERVER
    CachedObjectsParams.PARAM1_STRING.param1 = log_message;
    GetDispatcher().CallMethod(CALL_ID_SCR_CNSL_ADD_PRINT, CachedObjectsParams.PARAM1_STRING);
#endif
    FileHandle fileHandle = OpenFile(GetFileName(), FileMode.APPEND);
    if (fileHandle == 0)
      return;
    FPrintln(fileHandle, log_message);
    CloseFile(fileHandle);
#ifndef LOG_TO_RPT
#ifdef DIAG_DEVELOPER
    Print(string.Format("%1", log_message));
#endif
#endif
  }
References CALL_ID_SCR_CNSL_ADD_PRINT, Dispatcher::CallMethod(), CloseFile(), FPrintln(), GetDispatcher(), GetFileName(), OpenFile(), CachedObjectsParams::PARAM1_STRING, and Print().
Referenced by LogMessage(), and ReceivedLogMessageFromServer().
SymptomLog()
static void Debug::SymptomLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 153 of file Debug.c.
  {
    string res = LogMessage(LOG_DEBUG_SYMPTOM, plugin, entity, author, label, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LOG_DEBUG_SYMPTOM, LogMessage(), and PrintToRPT().
Referenced by SymptomBase::OnGetActivatedClient(), SymptomBase::OnGetActivatedServer(), SymptomBase::OnGetDeactivatedClient(), and SymptomBase::OnGetDeactivatedServer().
TFLog()
static void Debug::TFLog (string message = LOG_DEFAULT, TestFramework caller = null, string function = "") inline static private
Definition at line 243 of file Debug.c.
  {
    string res = LogMessage(LOG_DEBUG_TF, GetDebugName(caller), "", "", function, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References GetDebugName(), LOG_DEBUG_TF, LogMessage(), and PrintToRPT().
Referenced by TFModule::PrintResult(), EnProfilerTests::TestClassCountData(), EnProfilerTests::TestClassTimeData(), EnProfilerTests::TestFuncTimeData(), and EnProfilerTests::TestModule().
TriggerLog()
static void Debug::TriggerLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 223 of file Debug.c.
  {
    string res = LogMessage(LOG_DEBUG_TRIGGER, plugin, entity, author, label, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LOG_DEBUG_TRIGGER, LogMessage(), and PrintToRPT().
Referenced by Trigger::AddInsider(), TriggerEvents::Enter(), TriggerEvents::Leave(), Trigger::RemoveInsider(), TriggerEvents::Stay(), TriggerEvents::StayFinish(), TriggerEvents::StayStart(), and Trigger::UpdateInsiders().
WeatherLog()
static void Debug::WeatherLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 278 of file Debug.c.
  {
    if (!LogManager.IsWeatherLogEnabled())
      return;
    string res = LogMessage(LOG_DEBUG_WEATHER, plugin, entity, author, label, message);
#ifdef LOG_TO_RPT
    if (res.Length() > 0)
      PrintToRPT("" + res);
#endif
  }
References LogManager::IsWeatherLogEnabled(), LOG_DEBUG_WEATHER, LogMessage(), and PrintToRPT().
Referenced by WorldData::WeatherOnBeforeChange().
WeightLog()
static void Debug::WeightLog (string message = LOG_DEFAULT, Managed caller = null, string function = "", Managed entity = null) inline static private
Definition at line 253 of file Debug.c.
  {
    /*
      string res = LogMessage(LOG_DEBUG_WEIGHT, GetDebugName(caller), GetDebugName(entity), "", function, message);
      #ifdef LOG_TO_RPT
      if (res.Length() > 0)
      {
      PrintToRPT("" + res);
      }
      #endif
    */
  }
Member Data Documentation
LOG_DEBUG
const string Debug::LOG_DEBUG = "Debug" static private
Definition at line 15 of file Debug.c.
Referenced by Log(), LogArrayInt(), and LogArrayString().
LOG_DEBUG_ACTION
const string Debug::LOG_DEBUG_ACTION = "Action" static private
Definition at line 16 of file Debug.c.
Referenced by ActionLog().
LOG_DEBUG_BASEBUILDING
const string Debug::LOG_DEBUG_BASEBUILDING = "Base Building" static private
Definition at line 22 of file Debug.c.
Referenced by BaseBuildingLog().
LOG_DEBUG_BLEEDING_CHANCES
const string Debug::LOG_DEBUG_BLEEDING_CHANCES = "Bleeding" static private
Definition at line 23 of file Debug.c.
Referenced by BleedingChancesLog().
LOG_DEBUG_INV_HFSM
const string Debug::LOG_DEBUG_INV_HFSM = "HFSM" static private
Definition at line 20 of file Debug.c.
Referenced by InventoryHFSMLog().
LOG_DEBUG_INV_MOVE
const string Debug::LOG_DEBUG_INV_MOVE = "Inv Move" static private
Definition at line 18 of file Debug.c.
Referenced by InventoryMoveLog().
LOG_DEBUG_INV_RESERVATION
const string Debug::LOG_DEBUG_INV_RESERVATION = "Inv Rrsv" static private
Definition at line 19 of file Debug.c.
Referenced by InventoryReservationLog().
LOG_DEBUG_MELEE
const string Debug::LOG_DEBUG_MELEE = "Melee" static private
Definition at line 28 of file Debug.c.
Referenced by MeleeLog().
LOG_DEBUG_PARTICLE
const string Debug::LOG_DEBUG_PARTICLE = "Particle" static private
Definition at line 25 of file Debug.c.
Referenced by ParticleLog().
LOG_DEBUG_QUICKBAR
const string Debug::LOG_DEBUG_QUICKBAR = "Quickbar" static private
Definition at line 21 of file Debug.c.
Referenced by QuickbarLog().
LOG_DEBUG_SYMPTOM
const string Debug::LOG_DEBUG_SYMPTOM = "Symptom" static private
Definition at line 17 of file Debug.c.
Referenced by SymptomLog().
LOG_DEBUG_TF
const string Debug::LOG_DEBUG_TF = "TestFramework" static private
Definition at line 26 of file Debug.c.
Referenced by TFLog().
LOG_DEBUG_TRIGGER
const string Debug::LOG_DEBUG_TRIGGER = "Trigger" static private
Definition at line 24 of file Debug.c.
Referenced by TriggerLog().
LOG_DEBUG_WEATHER
const string Debug::LOG_DEBUG_WEATHER = "Weather" static private
Definition at line 29 of file Debug.c.
Referenced by WeatherLog().
LOG_DEBUG_WEIGHT
const string Debug::LOG_DEBUG_WEIGHT = "Weight" static private
Definition at line 27 of file Debug.c.
LOG_DEFAULT
const string Debug::LOG_DEFAULT = "n/a" static private
Definition at line 34 of file Debug.c.
LOG_ERROR
const string Debug::LOG_ERROR = "Error" static private
Definition at line 33 of file Debug.c.
Referenced by LogError().
LOG_INFO
const string Debug::LOG_INFO = "Info" static private
Definition at line 31 of file Debug.c.
Referenced by LogInfo().
LOG_WARNING
const string Debug::LOG_WARNING = "Warning" static private
Definition at line 32 of file Debug.c.
Referenced by LogWarning().
m_CanvasDebug
CanvasWidget Debug::m_CanvasDebug static private
Definition at line 39 of file Debug.c.
Referenced by CanvasDrawLine(), ClearCanvas(), and InitCanvas().
m_DebugLayoutCanvas
Widget Debug::m_DebugLayoutCanvas static private
Definition at line 38 of file Debug.c.
Referenced by InitCanvas().
m_DebugShapes
ref array<Shape> Debug::m_DebugShapes static private
Definition at line 36 of file Debug.c.
Referenced by DestroyAllShapes(), DrawArrow(), DrawBoxEx(), DrawCube(), DrawCylinder(), DrawFrustum(), DrawLine(), DrawLines(), DrawSphere(), Init(), and RemoveShape().
m_EnabledLogs
bool Debug::m_EnabledLogs static private
Definition at line 582 of file Debug.c.
The documentation for this class was generated from the following file:
scripts/3_Game/tools/Debug.c