DayZ: scripts/4_World/Entities/ExplosivesBase.c File Reference
ExplosivesBase.c File Reference
Classes
class ExplosiveLight
Functions
void ExplosivesBase ()
override bool IsExplosive ()
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
override void EEDelete (EntityAI parent)
override void EEKilled (Object killer)
override void OnCEUpdate ()
override void UnpairRemote ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
void CreateLight ()
void DestroyParticle (Particle p)
void InitiateExplosion ()
void OnExplode ()
override void SetActions ()
override bool IsInventoryVisible ()
override bool IsTakeable ()
bool IsTimerDetonable ()
void Arm ()
void OnArmed ()
bool CanBeArmed ()
void Disarm (bool pWithTool=false)
void OnBeforeDisarm ()
void OnDisarmed (bool pWithTool)
bool CanBeDisarmed ()
bool GetArmed ()
void SetArmed (bool state)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanRemoveFromHands (EntityAI parent)
bool GetDefused ()
void SetDefused (bool state)
void SetAmmoType (string pAmmoType)
void SetAmmoTypes (array< string > pAmmoTypes)
void SetParticleExplosion (int particle)
void SetParticlePosition (vector local_pos)
set position for smoke particle - needs to be in Local Space
void SetParticleOrientation (vector local_ori)
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
void UpdateLED (int pState)
HELPERS.
bool HasLockedTriggerSlots ()
void LockTriggerSlots ()
void UnlockTriggerSlots ()
void LockExplosivesSlots ()
void UnlockExplosivesSlots ()
Variables
ExplosiveLight DEFAULT_AMMO_TYPE = "Explosion_NonLethal"
const string ANIM_PHASE_VISIBILITY = "Visibility"
bool m_Armed
bool m_Defused
ref array< string > m_AmmoTypes
ref Timer m_DeleteTimer
ExplosiveLight m_Light
light
Particle m_ParticleExplosion
particle
ref array< ParticleSource > m_ParticleExplosionArr = {}
int m_ParticleExplosionId
vector m_ParticlePosition
vector m_ParticleOrientation
Function Documentation
Arm()
void Arm () protected
Definition at line 193 of file ExplosivesBase.c.
  {
    SetArmed(true);
    OnArmed();
  }
References OnArmed(), and SetArmed().
Referenced by Grenade_ChemGas::Grenade_ChemGas(), ClaymoreMine::OnDebugSpawn(), ClaymoreMine::OnPlacementComplete(), ImprovisedExplosive::OnTriggerAttached(), Plastic_Explosive::OnTriggerAttached(), SetAlarmInXMins(), and TurnOn().
CanBeArmed()
bool CanBeArmed () protected
Definition at line 202 of file ExplosivesBase.c.
  {
    return true;
  }
CanBeDisarmed()
bool CanBeDisarmed () protected
Definition at line 217 of file ExplosivesBase.c.
  {
    return false;
  }
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) protected
Definition at line 233 of file ExplosivesBase.c.
  {
    if (!super.CanPutInCargo(parent))
      return false;
    return IsTakeable();
  }
References IsTakeable().
CanPutIntoHands()
override bool CanPutIntoHands (EntityAI parent) protected
Definition at line 241 of file ExplosivesBase.c.
  {
    if (!super.CanPutIntoHands(parent))
      return false;
    return IsTakeable();
  }
References IsTakeable().
CanRemoveFromHands()
override bool CanRemoveFromHands (EntityAI parent) protected
Definition at line 249 of file ExplosivesBase.c.
  {
    return IsTakeable();
  }
References IsTakeable().
CreateLight()
void CreateLight () protected
Definition at line 139 of file ExplosivesBase.c.
  {
    m_Light = ExplosiveLight.Cast(ScriptedLightBase.CreateLight(ExplosiveLight, GetPosition()));
  }
References GetPosition, and m_Light.
Referenced by EntityLightSource::CreateLightAtObjMemoryPoint(), and OnExplosionEffects().
DestroyParticle()
void DestroyParticle (Particle p) protected
Definition at line 144 of file ExplosivesBase.c.
  {
#ifndef SERVER
    if (p != null)
      p.Stop();
#endif
  }
Referenced by EEDelete(), and RefreshParticlesAndSounds().
Disarm()
void Disarm (bool pWithTool = false) protected
Definition at line 207 of file ExplosivesBase.c.
  {
    SetArmed(false);
    OnDisarmed(pWithTool);
  }
References OnDisarmed(), and SetArmed().
EEDelete()
override void EEDelete (EntityAI parent) protected
Definition at line 78 of file ExplosivesBase.c.
  {
    super.EEDelete(parent);
    if (m_ParticleExplosion)
    {
      foreach (ParticleSource p : m_ParticleExplosionArr)
        DestroyParticle(p);
    }
  }
References DestroyParticle(), m_ParticleExplosion, and m_ParticleExplosionArr.
EEKilled()
override void EEKilled (Object killer) protected
should be called only here to avoid multiple explosion calculations, call SetHealth("","",0.0) instead
Definition at line 89 of file ExplosivesBase.c.
  {
    super.EEKilled(killer);
    InitiateExplosion();
    UnpairRemote();
  }
References InitiateExplosion(), and UnpairRemote().
ExplosivesBase()
void ExplosivesBase () protected
no effect
Definition at line 40 of file ExplosivesBase.c.
  {
    m_DeleteTimer = new Timer();
    m_AmmoTypes = new array<string>();
    SetAmmoType(DEFAULT_AMMO_TYPE);
    SetParticleExplosion(ParticleList.INVALID);
    SetParticlePosition(WorldToModel(GetPosition()));
    SetParticleOrientation(vector.Zero);
    RegisterNetSyncVariableBool("m_Armed");
    RegisterNetSyncVariableBool("m_Defused");
  }
References DEFAULT_AMMO_TYPE, GetPosition, ParticleList::INVALID, m_AmmoTypes, m_DeleteTimer, SetAmmoType(), SetParticleExplosion(), SetParticleOrientation(), SetParticlePosition(), and vector::Zero.
GetArmed()
bool GetArmed () protected
Definition at line 222 of file ExplosivesBase.c.
  {
    return m_Armed;
  }
References m_Armed.
Referenced by ClaymoreMine::AfterStoreLoad(), ImprovisedExplosive::CanBeArmed(), Plastic_Explosive::CanBeArmed(), ClaymoreMine::CanBeDisarmed(), Plastic_Explosive::CanBeDisarmed(), ImprovisedExplosive::CanReceiveAttachment(), Plastic_Explosive::CanReceiveAttachment(), ClaymoreMine::GetViewIndex(), ImprovisedExplosive::IsDeployable(), Plastic_Explosive::IsDeployable(), ClaymoreMine::IsTakeable(), ImprovisedExplosive::IsTakeable(), Plastic_Explosive::IsTakeable(), ClaymoreMine::OnActivatedByItem(), ImprovisedExplosive::OnActivatedByItem(), Plastic_Explosive::OnActivatedByItem(), OnCEUpdate(), and ClaymoreMine::UpdateVisuals().
GetDefused()
bool GetDefused () protected
Definition at line 254 of file ExplosivesBase.c.
  {
    return m_Defused;
  }
References m_Defused.
Referenced by ClaymoreMine::InitiateExplosion(), and ClaymoreMine::UpdateVisuals().
HasLockedTriggerSlots()
bool HasLockedTriggerSlots () protected
Definition at line 324 of file ExplosivesBase.c.
  {
    return false;
  }
InitiateExplosion()
void InitiateExplosion () protected
Definition at line 152 of file ExplosivesBase.c.
  {
    int count = m_AmmoTypes.Count();
    for (int i = 0; i < count; i++)
      Explode(DamageType.EXPLOSION, m_AmmoTypes[i]);
    OnExplode();
  }
References Explode(), m_AmmoTypes, and OnExplode().
Referenced by EEKilled(), and Plastic_Explosive::OnActivatedByItem().
IsExplosive()
override bool IsExplosive () protected
Definition at line 55 of file ExplosivesBase.c.
  {
    return true;
  }
IsInventoryVisible()
override bool IsInventoryVisible () protected
Definition at line 175 of file ExplosivesBase.c.
  {
    if (!super.IsInventoryVisible())
      return false;
    return GetAnimationPhase("Visibility") == 0;
  }
IsTakeable()
override bool IsTakeable () protected
Definition at line 183 of file ExplosivesBase.c.
  {
    return super.IsTakeable() && GetAnimationPhase("Visibility") == 0;
  }
Referenced by CanPutInCargo(), CanPutIntoHands(), and CanRemoveFromHands().
IsTimerDetonable()
bool IsTimerDetonable () protected
Definition at line 188 of file ExplosivesBase.c.
  {
    return false;
  }
LockExplosivesSlots()
void LockExplosivesSlots () protected
LockTriggerSlots()
void LockTriggerSlots () protected
OnArmed()
void OnArmed () protected
Referenced by Arm().
OnBeforeDisarm()
void OnBeforeDisarm () protected
OnCEUpdate()
override void OnCEUpdate () protected
Definition at line 99 of file ExplosivesBase.c.
  {
    super.OnCEUpdate();
    if (!IsRuined() && GetArmed() && GetPairDevice())
    {
      if (vector.DistanceSq(GetPosition(), GetPairDevice().GetPosition()) <= Math.SqrFloat(UAMaxDistances.EXPLOSIVE_REMOTE_ACTIVATION))
      {
        UpdateLED(ERemoteDetonatorLEDState.LIT);
        return;
      }
    }
    UpdateLED(ERemoteDetonatorLEDState.OFF);
  }
References vector::DistanceSq(), UAMaxDistances::EXPLOSIVE_REMOTE_ACTIVATION, GetArmed(), GetPosition, Math::SqrFloat(), and UpdateLED().
OnDisarmed()
void OnDisarmed (bool pWithTool) protected
Referenced by Disarm().
OnExplode()
void OnExplode () protected
Definition at line 161 of file ExplosivesBase.c.
  {
    if (GetGame().IsServer())
      m_DeleteTimer.Run(0.25, this, "DeleteSafe");
  }
References GetGame(), and m_DeleteTimer.
Referenced by InitiateExplosion(), and Grenade_Base::InitiateExplosion().
OnExplosionEffects()
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType) protected
Definition at line 60 of file ExplosivesBase.c.
  {
    super.OnExplosionEffects(source, directHit, componentIndex, surface, pos, surfNormal, energyFactor, explosionFactor, isWater, ammoType);
    if (m_ParticleExplosionId > ParticleList.INVALID)
    {
      EntityAI parent = this;
      if (GetHierarchyParent())
        parent = GetHierarchyParent();
      ParticleSource p = ParticleManager.GetInstance().PlayOnObject(m_ParticleExplosionId, parent, m_ParticlePosition, m_ParticleOrientation);
      m_ParticleExplosionArr.Insert(p);
      m_ParticleExplosion = p;
    }
    CreateLight();
  }
References CreateLight(), ParticleList::INVALID, m_ParticleExplosion, m_ParticleExplosionArr, m_ParticleExplosionId, m_ParticleOrientation, m_ParticlePosition, and ParticleManager().
OnPlacementComplete()
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") protected
Definition at line 127 of file ExplosivesBase.c.
  {
    super.OnPlacementComplete(player, position, orientation);
    if (GetGame().IsServer())
    {
      SetOrientation(orientation);
      SetPosition(position);
      PlaceOnSurface();
    }
  }
References GetGame(), and SetPosition().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) protected
Definition at line 305 of file ExplosivesBase.c.
  {
    if (!super.OnStoreLoad(ctx, version))
      return false;
    if (version > 129)
    {
      bool armed = false;
      if (!ctx.Read(armed))
        return false;
      SetArmed(armed);
    }
    return true;
  }
References SetArmed().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) protected
Definition at line 298 of file ExplosivesBase.c.
  {
    super.OnStoreSave(ctx);
    ctx.Write(m_Armed);
  }
References m_Armed.
SetActions()
override void SetActions () protected
Definition at line 167 of file ExplosivesBase.c.
  {
    super.SetActions();
    AddAction(ActionAttach);
    AddAction(ActionDetach);
  }
References ActionDetach(), and AddAction().
SetAmmoType()
void SetAmmoType (string pAmmoType) protected
Definition at line 265 of file ExplosivesBase.c.
  {
    SetAmmoTypes({pAmmoType});
  }
References SetAmmoTypes().
Referenced by ExplosivesBase(), Grenade_Base::FlashGrenade(), SmokeGrenadeBase::M18SmokeGrenade_ColorBase(), Grenade_Base::M67Grenade(), Plastic_Explosive::Plastic_Explosive(), SmokeGrenadeBase::RDG2SmokeGrenade_ColorBase(), Grenade_Base::RGD5Grenade(), and SmokeGrenadeBase().
SetAmmoTypes()
void SetAmmoTypes (array< string > pAmmoTypes) protected
Definition at line 270 of file ExplosivesBase.c.
  {
    m_AmmoTypes.Clear();
    m_AmmoTypes = pAmmoTypes;
  }
References m_AmmoTypes.
Referenced by ClaymoreMine::ClaymoreMine(), and SetAmmoType().
SetArmed()
void SetArmed (bool state) protected
Definition at line 227 of file ExplosivesBase.c.
  {
    m_Armed = state;
    SetSynchDirty();
  }
References m_Armed.
Referenced by Arm(), Disarm(), ImprovisedExplosive::EEHealthLevelChanged(), Plastic_Explosive::EEHealthLevelChanged(), and OnStoreLoad().
SetDefused()
void SetDefused (bool state) protected
Definition at line 259 of file ExplosivesBase.c.
  {
    m_Defused = state;
    SetSynchDirty();
  }
References m_Defused.
Referenced by ClaymoreMine::OnDisarmed().
SetParticleExplosion()
void SetParticleExplosion (int particle) protected
Definition at line 276 of file ExplosivesBase.c.
  {
    m_ParticleExplosionId = particle;
  }
References m_ParticleExplosionId.
Referenced by ClaymoreMine::ClaymoreMine(), ExplosivesBase(), Grenade_Base::FlashGrenade(), Grenade_ChemGas::Grenade_ChemGas(), Grenade_Base::M67Grenade(), Plastic_Explosive::Plastic_Explosive(), and Grenade_Base::RGD5Grenade().
SetParticleOrientation()
void SetParticleOrientation (vector local_ori) protected
Definition at line 290 of file ExplosivesBase.c.
  {
    m_ParticleOrientation = local_ori;
    if (GetHierarchyParent())
      m_ParticleOrientation = GetHierarchyParent().WorldToModel(GetOrientation());
  }
References GetOrientation(), and m_ParticleOrientation.
Referenced by ClaymoreMine::ClaymoreMine(), and ExplosivesBase().
SetParticlePosition()
void SetParticlePosition (vector local_pos) protected
set position for smoke particle - needs to be in Local Space
Definition at line 282 of file ExplosivesBase.c.
  {
    m_ParticlePosition = local_pos;
    if (GetHierarchyParent())
      m_ParticlePosition = GetHierarchyParent().WorldToModel(GetPosition());
  }
References GetPosition, and m_ParticlePosition.
Referenced by ExplosivesBase(), and SmokeGrenadeBase::RDG2SmokeGrenade_ColorBase().
UnlockExplosivesSlots()
void UnlockExplosivesSlots () protected
UnlockTriggerSlots()
void UnlockTriggerSlots () protected
UnpairRemote()
override void UnpairRemote () protected
Definition at line 116 of file ExplosivesBase.c.
  {
    if (GetRemotelyActivatedItemBehaviour())
    {
      if (GetPairDevice())
        GetPairDevice().UnpairRemote();
      GetRemotelyActivatedItemBehaviour().Unpair();
    }
  }
References GetRemotelyActivatedItemBehaviour().
Referenced by EEKilled(), ClaymoreMine::OnDisarmed(), ImprovisedExplosive::OnDisarmed(), and Plastic_Explosive::OnDisarmed().
UpdateLED()
void UpdateLED (int pState) protected
HELPERS.
Variable Documentation
ANIM_PHASE_VISIBILITY
const string ANIM_PHASE_VISIBILITY = "Visibility" protected
Definition at line 22 of file ExplosivesBase.c.
Referenced by ImprovisedExplosive::OnActivatedByItem().
DEFAULT_AMMO_TYPE
ExplosiveLight DEFAULT_AMMO_TYPE = "Explosion_NonLethal"
Referenced by ExplosivesBase().
m_AmmoTypes
ref array<string> m_AmmoTypes protected
Definition at line 26 of file ExplosivesBase.c.
Referenced by ExplosivesBase(), InitiateExplosion(), Grenade_Base::InitiateExplosion(), and SetAmmoTypes().
m_Armed
bool m_Armed protected
Definition at line 24 of file ExplosivesBase.c.
Referenced by GetArmed(), OnStoreSave(), and SetArmed().
m_Defused
bool m_Defused protected
Definition at line 25 of file ExplosivesBase.c.
Referenced by GetDefused(), and SetDefused().
m_DeleteTimer
ref Timer m_DeleteTimer protected
Definition at line 28 of file ExplosivesBase.c.
Referenced by EntityLightSource::DeleteLightWithDelay(), DeleteThis(), ExplosivesBase(), and OnExplode().
m_Light
ExplosiveLight m_Light protected
light
Definition at line 31 of file ExplosivesBase.c.
Referenced by Clothing::AttachLightOnHead(), Clothing::CreateHeadtorchLight(), CreateLight(), Grenade_Base::CreateLight(), Container_Base::DeferredInit(), BuildingSuper::EEDelete(), Container_Base::EEDelete(), BuildingSuper::EEInit(), Switchable_Base::GetLight(), GetLightEntity(), Clothing::OnInvisibleSet(), ItemBase::OnItemLocationChanged(), Headtorch_Black::OnLightCreated(), Clothing::OnLightCreated(), ItemBase::OnSwitchOff(), Clothing::OnWasAttached(), Clothing::OnWasDetached(), Clothing::OnWork(), ItemBase::OnWork(), Switchable_Base::OnWork(), ItemBase::OnWorkStart(), Switchable_Base::OnWorkStart(), ItemBase::OnWorkStop(), Clothing::OnWorkStop(), Switchable_Base::OnWorkStop(), and SetLightEntity().
m_ParticleExplosion
Particle m_ParticleExplosion protected
particle
Definition at line 34 of file ExplosivesBase.c.
Referenced by EEDelete(), OnExplode(), and OnExplosionEffects().
m_ParticleExplosionArr
ref array<ParticleSource> m_ParticleExplosionArr = {} protected
Definition at line 35 of file ExplosivesBase.c.
{};
Referenced by EEDelete(), and OnExplosionEffects().
m_ParticleExplosionId
int m_ParticleExplosionId protected
Definition at line 36 of file ExplosivesBase.c.
Referenced by OnExplosionEffects(), and SetParticleExplosion().
m_ParticleOrientation
vector m_ParticleOrientation protected
Definition at line 38 of file ExplosivesBase.c.
Referenced by OnExplosionEffects(), and SetParticleOrientation().
m_ParticlePosition
vector m_ParticlePosition protected
Definition at line 37 of file ExplosivesBase.c.
Referenced by OnExplosionEffects(), PlaySmokeParticle(), and SetParticlePosition().