DayZ: scripts/4_World/Entities/ItemBase/TrapBase/Trap_TripWire.c File Reference
Trap_TripWire.c File Reference
Classes
class TripwireTrapDeployed
Enumerations
enum eWireMaterial { WIRE = 0 , BARBED_WIRE = 1 , ROPE = 2 }
Functions
void TripwireTrap ()
override void OnVariablesSynchronized ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void CreateTrigger ()
override void OnSteppedOn (EntityAI victim)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void SetInactive (bool stop_timer=true)
void SetState (int state_ID)
int GetState ()
returns one of STATE_...
void SetWireType (int wireType)
int GetWireType ()
override void RefreshState ()
override void SetupTrapPlayer (PlayerBase player, bool set_position=true)
override void StartDeactivate (PlayerBase player)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanDisplayAttachmentSlot (int slot_id)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void EEKilled (Object killer)
void FoldTripWire ()
override void OnInventoryEnter (Man player)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnPlacementCancelled (Man player)
override bool IsDeployable ()
override bool IsTakeable ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override void SetActions ()
void UpdateProxySelections ()
Variables
enum eWireMaterial FOLDED = 3
static const int DEPLOYED = 2
static const int TRIGGERED = 1
int m_State = FOLDED
int m_WireMaterial
bool m_ResultOfAdvancedPlacing
vector m_TriggerPosition
vector m_TriggerOrientation
Enumeration Type Documentation
eWireMaterial
enum eWireMaterial
Enumerator
WIRE
BARBED_WIRE
ROPE
Definition at line 2 of file Trap_TripWire.c.
{
  WIRE = 0,
  BARBED_WIRE = 1,
  ROPE = 2
}
Function Documentation
CanDisplayAttachmentSlot()
override bool CanDisplayAttachmentSlot (int slot_id) protected
Definition at line 226 of file Trap_TripWire.c.
  {
    if (GetState() != DEPLOYED)
      return false;
    return super.CanDisplayAttachmentSlot(slot_id);
  }
References DEPLOYED, and GetState().
Referenced by Entity::CanDisplayAnyAttachmentSlot().
CanReceiveAttachment()
override bool CanReceiveAttachment (EntityAI attachment, int slotId) protected
Definition at line 217 of file Trap_TripWire.c.
  {
    if (GetState() != DEPLOYED)
      return false;
    return super.CanReceiveAttachment(attachment, slotId);
  }
References DEPLOYED, and GetState().
CreateTrigger()
override void CreateTrigger () protected
Definition at line 68 of file Trap_TripWire.c.
  {
    m_TrapTrigger = TripWireTrigger.Cast(GetGame().CreateObjectEx("TripWireTrigger", GetPosition(), SPAWN_FLAGS));
    vector mins = "-0.75 0.3 -0.01";
    vector maxs = "0.75 0.32 0.01";
    m_TrapTrigger.SetOrientation(GetOrientation());
    m_TrapTrigger.SetExtents(mins, maxs);
    m_TrapTrigger.SetParentObject(this);
    GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(DeferredEnableTrigger);
  }
References CALL_CATEGORY_SYSTEM, DeferredEnableTrigger(), GetGame(), GetOrientation(), GetPosition, m_TrapTrigger, Trigger::SetExtents(), TrapTrigger::SetParentObject(), and SPAWN_FLAGS.
EEHealthLevelChanged()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) protected
Definition at line 140 of file Trap_TripWire.c.
  {
    super.EEHealthLevelChanged(oldLevel, newLevel, zone);
    if (GetGame().IsServer())
    {
      if (newLevel == GameConstants.STATE_RUINED)
      {
        SetState(TRIGGERED);
        RefreshState();
      }
    }
  }
References GetGame(), RefreshState(), SetState(), GameConstants::STATE_RUINED, and TRIGGERED.
EEItemAttached()
override void EEItemAttached (EntityAI item, string slot_name) protected
Definition at line 234 of file Trap_TripWire.c.
  {
    super.EEItemAttached(item, slot_name);
    SetTakeable(false);
  }
References SetTakeable().
EEItemDetached()
override void EEItemDetached (EntityAI item, string slot_name) protected
Definition at line 241 of file Trap_TripWire.c.
  {
    super.EEItemDetached(item, slot_name);
    SetTakeable(false);
  }
References SetTakeable().
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) protected
Definition at line 115 of file Trap_TripWire.c.
  {
    super.EEItemLocationChanged(oldLoc, newLoc);
    if (m_ResultOfAdvancedPlacing)
    {
      if (oldLoc.GetType() == InventoryLocationType.GROUND && newLoc.GetType() == InventoryLocationType.GROUND)
      {
        SetActive();
        m_TrapTrigger.SetPosition(m_TriggerPosition);
        m_TrapTrigger.SetOrientation(m_TriggerOrientation);
      }
      m_ResultOfAdvancedPlacing = false;
    }
    if (oldLoc.GetType() == InventoryLocationType.GROUND && newLoc.GetType() == InventoryLocationType.CARGO)
    {
      SetInactive();
      DeleteTrigger();
      SetState(FOLDED);
      RefreshState();
    }
  }
References DeleteTrigger(), FOLDED, m_ResultOfAdvancedPlacing, m_TrapTrigger, m_TriggerOrientation, m_TriggerPosition, RefreshState(), SetActive(), SetInactive(), and SetState().
EEKilled()
override void EEKilled (Object killer) protected
Definition at line 248 of file Trap_TripWire.c.
  {
    if (m_TrapTrigger)
      StartDeactivate(null);
    super.EEKilled(killer);
  }
References m_TrapTrigger, and StartDeactivate().
FoldTripWire()
void FoldTripWire () protected
Definition at line 257 of file Trap_TripWire.c.
  {
    if (m_AnimationPhaseGrounded != "")
    {
      SetAnimationPhase(m_AnimationPhaseSet, 1);
      if (m_AnimationPhaseTriggered != m_AnimationPhaseGrounded)
        SetAnimationPhase(m_AnimationPhaseTriggered, 1);
      SetAnimationPhase(m_AnimationPhaseGrounded, 0);
    }
  }
References m_AnimationPhaseGrounded, m_AnimationPhaseSet, and m_AnimationPhaseTriggered.
Referenced by RefreshState().
GetDeploySoundset()
override string GetDeploySoundset () protected
Definition at line 367 of file Trap_TripWire.c.
  {
    return "tripwire_deploy_SoundSet";
  }
GetLoopDeploySoundset()
override string GetLoopDeploySoundset () protected
Definition at line 372 of file Trap_TripWire.c.
  {
    return "tripwiretrap_deploy_SoundSet";
  }
GetState()
int GetState () protected
returns one of STATE_...
returns the state of climb (enum value of ClimbStates);
Definition at line 178 of file Trap_TripWire.c.
  {
    return m_State;
  }
References m_State.
Referenced by ItemBase::CanAttach(), CanBeIgnitedBy(), ItemBase::CanBeManipulated(), ItemBase::CanBePacked(), ActionContinuousBaseCB::CancelCondition(), ActionInteractLoopBaseCB::CancelCondition(), CanDisplayAttachmentSlot(), FireworksLauncher::CanPutInCargo(), FireworksLauncher::CanPutIntoHands(), CanReceiveAttachment(), ItemBase::EEHealthLevelChanged(), GetStateString(), ItemBase::GetViewIndex(), ItemBase::HandleOpeningsPhysics(), FireworksLauncher::IsIgnited(), IsTakeable(), OnInventoryEnter(), FireworksLauncher::OnPlacementComplete(), RefreshState(), ItemBase::UpdatePhysics(), UpdateProxySelections(), and ItemBase::UpdateVisuals().
GetWireType()
int GetWireType () protected
Definition at line 188 of file Trap_TripWire.c.
  {
    return m_WireMaterial;
  }
References m_WireMaterial.
IsDeployable()
override bool IsDeployable () protected
Definition at line 356 of file Trap_TripWire.c.
  {
    return true;
  }
IsTakeable()
override bool IsTakeable () protected
Definition at line 362 of file Trap_TripWire.c.
  {
    return GetState() != DEPLOYED || (GetInventory().AttachmentCount() == 0 && GetState() == DEPLOYED);
  }
References DEPLOYED, and GetState().
OnInventoryEnter()
override void OnInventoryEnter (Man player) protected
Definition at line 270 of file Trap_TripWire.c.
  {
    SetState(FOLDED);
  }
References FOLDED, and SetState().
OnItemLocationChanged()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) protected
Definition at line 103 of file Trap_TripWire.c.
  {
    super.OnItemLocationChanged(old_owner, new_owner);
    PlayerBase player = PlayerBase.Cast(new_owner);
    if (player)
    {
      StartDeactivate(player);
      return;
    }
  }
References StartDeactivate().
OnPlacementCancelled()
override void OnPlacementCancelled (Man player) protected
Definition at line 347 of file Trap_TripWire.c.
  {
    super.OnPlacementCancelled(player);
    SetState(FOLDED);
    m_ResultOfAdvancedPlacing = false;
  }
References FOLDED, m_ResultOfAdvancedPlacing, and SetState().
OnPlacementComplete()
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") protected
Definition at line 334 of file Trap_TripWire.c.
  {
    SetIsPlaceSound(true);
    if (GetGame().IsServer())
    {
      SetState(DEPLOYED);
      m_TriggerPosition = position;
      m_TriggerOrientation = orientation;
      m_ResultOfAdvancedPlacing = true;
    }
  }
References DEPLOYED, GetGame(), m_ResultOfAdvancedPlacing, m_TriggerOrientation, m_TriggerPosition, SetIsPlaceSound(), and SetState().
OnSteppedOn()
override void OnSteppedOn (EntityAI victim) protected
Definition at line 80 of file Trap_TripWire.c.
  {
    if (!victim)
      return;
    if (!victim.GetAllowDamage())
      return;
    // We must deal some damage, here 5 shock as melee damage in order to trigger hit animation
    if (GetGame().IsServer())
    {
      victim.ProcessDirectDamage(DT_CLOSE_COMBAT, this, "", "TripWireHit", "0 0 0", 1);
      SetState(TRIGGERED);
      SetInactive(false);
    }
    // We play the trap trigger sound
#ifndef SERVER
    EffectSound sound = SEffectManager.PlaySound("TripwireTrap_Trigger_SoundSet", GetPosition());
    sound.SetAutodestroy(true);
#endif
  }
References GetGame(), GetPosition, SEffectManager::PlaySound(), SetInactive(), SetState(), and TRIGGERED.
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) protected
Definition at line 53 of file Trap_TripWire.c.
  {
    if (!super.OnStoreLoad(ctx, version))
      return false;
    int state = FOLDED;
    if (!ctx.Read(state))
      state = FOLDED;
    SetState(state);
    RefreshState();
    return true;
  }
References FOLDED, RefreshState(), and SetState().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) protected
Definition at line 45 of file Trap_TripWire.c.
  {
    super.OnStoreSave(ctx);
    ctx.Write(m_State);
  }
References m_State.
OnVariablesSynchronized()
override void OnVariablesSynchronized () protected
Definition at line 37 of file Trap_TripWire.c.
  {
    super.OnVariablesSynchronized();
    if (IsPlaceSound())
      PlayPlaceSound();
  }
References IsPlaceSound(), and PlayPlaceSound().
RefreshState()
override void RefreshState () protected
Definition at line 194 of file Trap_TripWire.c.
  {
    super.RefreshState();
    if (GetState() == FOLDED)
      FoldTripWire();
  }
References FOLDED, FoldTripWire(), and GetState().
SetActions()
override void SetActions () protected
Definition at line 377 of file Trap_TripWire.c.
  {
    super.SetActions();
    AddAction(ActionTogglePlaceObject);
    AddAction(ActionDeployObject);
  }
References AddAction().
SetInactive()
override void SetInactive (bool stop_timer = true) protected
Definition at line 154 of file Trap_TripWire.c.
  {
    super.SetInactive(stop_timer);
    // de-attach attachments after "activating them"
    for (int att = 0; att < GetInventory().AttachmentCount(); att++)
    {
      ItemBase attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(att));
      if (attachment)
      {
        if (attachment.IsLockedInSlot())
          attachment.UnlockFromParent();
        attachment.OnActivatedByItem(this);
        GetInventory().DropEntity(InventoryMode.SERVER, this, attachment);
      }
    }
  }
SetState()
void SetState (int state_ID) protected
Definition at line 173 of file Trap_TripWire.c.
  {
    m_State = state_ID;
  }
References m_State.
SetupTrapPlayer()
override void SetupTrapPlayer (PlayerBase player, bool set_position = true) protected
Definition at line 202 of file Trap_TripWire.c.
  {
    super.SetupTrapPlayer(player, set_position);
    SetState(DEPLOYED);
  }
References DEPLOYED, and SetState().
SetWireType()
void SetWireType (int wireType) protected
Definition at line 183 of file Trap_TripWire.c.
  {
    m_WireMaterial = wireType;
  }
References m_WireMaterial.
StartDeactivate()
override void StartDeactivate (PlayerBase player) protected
Definition at line 208 of file Trap_TripWire.c.
  {
    super.StartDeactivate(player);
    DeleteTrigger();
    SetState(FOLDED);
  }
References DeleteTrigger(), FOLDED, and SetState().
Referenced by EEKilled(), and OnItemLocationChanged().
TripwireTrap()
void TripwireTrap () protected
Definition at line 23 of file Trap_TripWire.c.
  {
    m_DamagePlayers = 0; //How much damage player gets when caught
    m_InitWaitTime = 0.0; //After this time after deployment, the trap is activated
    m_DefectRate = 15;
    m_NeedActivation = false;
    m_AnimationPhaseGrounded = "inventory";
    m_AnimationPhaseSet = "placing";
    m_AnimationPhaseTriggered = "triggered";
    m_InfoActivationTime = string.Format("#STR_TripwireTrap0%1#STR_TripwireTrap1", m_InitWaitTime.ToString()); // nefunguje dynamicke vyrazy mimo funkcii
    RegisterNetSyncVariableInt("m_State");
  }
References string::Format(), m_AnimationPhaseGrounded, m_AnimationPhaseSet, m_AnimationPhaseTriggered, m_DamagePlayers, m_DefectRate, m_InfoActivationTime, m_InitWaitTime, m_NeedActivation, and float::ToString().
UpdateProxySelections()
void UpdateProxySelections () protected
Definition at line 389 of file Trap_TripWire.c.
  {
    if (GetInventory().AttachmentCount() > 0)
    {
      ItemBase attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(0));
      if (attachment)
      {
        // Hide all proxies
        for (int i = 1; i <= 3; i++)
          HideSelection("s" + i + "_charge");
        // Now show the one we need to see
        string proxy_to_show = string.Format("s%1_charge", GetState());
        //Print(proxy_to_show);
        ShowSelection(proxy_to_show);
      }
    }
  }
References GetState().
Variable Documentation
DEPLOYED
const int DEPLOYED = 2 static
Definition at line 13 of file Trap_TripWire.c.
Referenced by CanDisplayAttachmentSlot(), CanReceiveAttachment(), IsTakeable(), OnPlacementComplete(), and SetupTrapPlayer().
FOLDED
enum eWireMaterial FOLDED = 3
Referenced by Inventory_Base::CanBeManipulated(), EEItemLocationChanged(), Inventory_Base::Fold(), Inventory_Base::HescoBox(), OnInventoryEnter(), OnPlacementCancelled(), OnStoreLoad(), RefreshState(), and StartDeactivate().
m_ResultOfAdvancedPlacing
bool m_ResultOfAdvancedPlacing protected
Definition at line 19 of file Trap_TripWire.c.
Referenced by EEItemLocationChanged(), OnPlacementCancelled(), and OnPlacementComplete().
m_State
int m_State = FOLDED
Definition at line 16 of file Trap_TripWire.c.
m_TriggerOrientation
vector m_TriggerOrientation protected
Definition at line 21 of file Trap_TripWire.c.
Referenced by EEItemLocationChanged(), and OnPlacementComplete().
m_TriggerPosition
vector m_TriggerPosition protected
Definition at line 20 of file Trap_TripWire.c.
Referenced by EEItemLocationChanged(), and OnPlacementComplete().
m_WireMaterial
int m_WireMaterial private
Definition at line 17 of file Trap_TripWire.c.
Referenced by GetWireType(), and SetWireType().
TRIGGERED
const int TRIGGERED = 1 static
Definition at line 14 of file Trap_TripWire.c.
Referenced by EEHealthLevelChanged(), and OnSteppedOn().