DayZ: ActionCarDoorsOutside Class Reference
ActionCarDoorsOutside Class Reference
Protected Member Functions
void ActionCarDoorsOutside ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStartServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
void FillCommandUIDPerCrewIdx (int crewIdx0, int crewIdx1, int crewIdx2, int crewIdx3)
void FillCommandUIDPerCrewIdx (int evenCrewIdx0, int unevenCrewIdx1)
Protected Attributes
int m_CommandUIDPerCrewIdx [4]
bool m_IsOpening = true
Detailed Description
Definition at line 1 of file ActionCarDoorsOutside.c.
Constructor & Destructor Documentation
ActionCarDoorsOutside()
void ActionCarDoorsOutside::ActionCarDoorsOutside () inline protected
Definition at line 6 of file ActionCarDoorsOutside.c.
  {
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_OPENDOORFW;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ALL;
    m_LockTargetOnUse = false;
  }
References AnimatedActionBase::m_CommandUID, m_LockTargetOnUse, and m_StanceMask.
Member Function Documentation
ActionCondition()
override bool ActionCarDoorsOutside::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline protected
reach check from outside of car
player is outside of vehicle
player is looking at one of the doors, can't open if obstructed
if player is in car and cannot reach doors
is in reach, should open the door
Definition at line 19 of file ActionCarDoorsOutside.c.
  {
    CarScript car = null;
    if (!IsInReach(player, target, UAMaxDistances.DEFAULT))
      return false;
    if (Class.CastTo(car, target.GetParent()))
    {
      array<string> selections = new array<string>();
      CarDoor carDoor = CarDoor.Cast(target.GetObject());
      if (carDoor)
      {
        carDoor.GetActionComponentNameList(target.GetComponentIndex(), selections);
        string animSource = "";
        for (int i = 0; i < selections.Count(); i++)
        {
          animSource = car.GetAnimSourceFromSelection(selections[i]);
          if (animSource != "")
          {
            int idx = car.GetSeatIndexFromDoor(animSource);
            if (idx != -1 && !car.IsAreaAtDoorFree(idx))
            {
              return false;
            }
            m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_OPENDOORFW;
            float animationPhase = car.GetAnimationPhase(animSource);
            return (m_IsOpening && animationPhase <= 0.5) || (!m_IsOpening && animationPhase > 0.5);
          }
        }
      }
    }
    return false;
  }
References Class::CastTo(), UAMaxDistances::DEFAULT, IsInReach(), AnimatedActionBase::m_CommandUID, and m_IsOpening.
CreateConditionComponents()
override void ActionCarDoorsOutside::CreateConditionComponents () inline protected
Definition at line 13 of file ActionCarDoorsOutside.c.
  {
    m_ConditionItem = new CCINone;
    m_ConditionTarget = new CCTNone;
  }
References m_ConditionItem, and m_ConditionTarget.
FillCommandUIDPerCrewIdx() [1/2]
void ActionCarDoorsOutside::FillCommandUIDPerCrewIdx (int crewIdx0, int crewIdx1, int crewIdx2, int crewIdx3) inline protected
Definition at line 107 of file ActionCarDoorsOutside.c.
  {
    m_CommandUIDPerCrewIdx[0] = crewIdx0;
    m_CommandUIDPerCrewIdx[1] = crewIdx1;
    m_CommandUIDPerCrewIdx[2] = crewIdx2;
    m_CommandUIDPerCrewIdx[3] = crewIdx3;
  }
References m_CommandUIDPerCrewIdx.
Referenced by ActionCloseCarDoorsOutside::ActionCloseCarDoorsOutside(), ActionOpenCarDoorsOutside::ActionOpenCarDoorsOutside(), and FillCommandUIDPerCrewIdx().
FillCommandUIDPerCrewIdx() [2/2]
void ActionCarDoorsOutside::FillCommandUIDPerCrewIdx (int evenCrewIdx0, int unevenCrewIdx1) inline protected
Definition at line 115 of file ActionCarDoorsOutside.c.
  {
    FillCommandUIDPerCrewIdx(evenCrewIdx0, unevenCrewIdx1, evenCrewIdx0, unevenCrewIdx1);
  }
References FillCommandUIDPerCrewIdx().
OnEndServer()
override void ActionCarDoorsOutside::OnEndServer (ActionData action_data) inline protected
Definition at line 99 of file ActionCarDoorsOutside.c.
  {
    CarScript car = CarScript.Cast(action_data.m_Target.GetParent());
    if (car)
      car.ForceUpdateLightsEnd();
  }
OnStartServer()
override void ActionCarDoorsOutside::OnStartServer (ActionData action_data) inline protected
Definition at line 64 of file ActionCarDoorsOutside.c.
  {
    float phase;
    if (m_IsOpening)
      phase = 1.0;
    else
      phase = 0.0;
    string animSource = "";
    CarScript car = CarScript.Cast(action_data.m_Target.GetParent());
    if (car)
    {
      array<string> selections = new array<string>();
      CarDoor carDoor = CarDoor.Cast(action_data.m_Target.GetObject());
      if (carDoor)
      {
        carDoor.GetActionComponentNameList(action_data.m_Target.GetComponentIndex(), selections);
        for (int i = 0; i < selections.Count(); i++)
        {
          animSource = car.GetAnimSourceFromSelection(selections[i]);
          if (animSource != "")
            break;
        }
      }
    }
    if (car)
    {
      car.ForceUpdateLightsStart();
      car.SetAnimationPhase(animSource, phase);
    }
  }
References m_IsOpening.
Member Data Documentation
m_CommandUIDPerCrewIdx
int ActionCarDoorsOutside::m_CommandUIDPerCrewIdx[4] protected
Definition at line 3 of file ActionCarDoorsOutside.c.
Referenced by FillCommandUIDPerCrewIdx().
m_IsOpening
bool ActionCarDoorsOutside::m_IsOpening = true protected
Definition at line 4 of file ActionCarDoorsOutside.c.
Referenced by ActionCloseCarDoorsOutside::ActionCloseCarDoorsOutside(), ActionCondition(), ActionOpenCarDoorsOutside::ActionOpenCarDoorsOutside(), and OnStartServer().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Interact/Vehicles/ActionCarDoorsOutside.c