DayZ: scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/Vehicles/ActionStartEngine.c File Reference
ActionStartEngine.c File Reference
Classes
class ActionStartCarCB
Functions
void ActionStartEngine ()
DEPRECATED.
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
override bool CanBeUsedInVehicle ()
Variables
ActionStartCarCB ROUGH_SPECIALTY_WEIGHT = 0.5
static const float MINIMUM_BATTERY_ENERGY = 5.0
bool m_BatteryCon = false
DEPRECATED.
bool m_SparkCon = false
DEPRECATED.
bool m_BeltCon = false
DEPRECATED.
bool m_FuelCon = false
DEPRECATED.
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 35 of file ActionStartEngine.c.
  {
    HumanCommandVehicle vehCommand = player.GetCommand_Vehicle();
    if (vehCommand)
    {
      Transport trans = vehCommand.GetTransport();
      if (trans)
      {
        Car car;
        if (Class.CastTo(car, trans) && !car.EngineIsOn())
        {
          if (car.GetHealthLevel("Engine") >= GameConstants.STATE_RUINED)
            return false;
          return car.CrewMemberIndex(player) == DayZPlayerConstants.VEHICLESEAT_DRIVER);
        }
      }
    }
    return false;
  }
References Class::CastTo(), and GameConstants::STATE_RUINED.
ActionStartEngine()
void ActionStartEngine ()
DEPRECATED.
Definition at line 19 of file ActionStartEngine.c.
  {
    m_CallbackClass = ActionStartCarCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_STARTENGINE;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ALL;
    m_SpecialtyWeight = ROUGH_SPECIALTY_WEIGHT;
    m_LockTargetOnUse = false;
    m_Text = "#start_the_car";
  }
References m_LockTargetOnUse, m_SpecialtyWeight, m_StanceMask, m_Text, and ROUGH_SPECIALTY_WEIGHT.
Referenced by ActionConstructor::RegisterActions(), and ManBase::SetActions().
CanBeUsedInVehicle()
override bool CanBeUsedInVehicle ()
Definition at line 87 of file ActionStartEngine.c.
  {
    return true;
  }
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 29 of file ActionStartEngine.c.
  {
    m_ConditionTarget = new CCTNone();
    m_ConditionItem = new CCINone();
  }
References m_ConditionItem, and m_ConditionTarget.
OnExecuteServer()
override void OnExecuteServer (ActionData action_data)
Definition at line 72 of file ActionStartEngine.c.
  {
    HumanCommandVehicle vehCommand = action_data.m_Player.GetCommand_Vehicle();
    if (vehCommand)
    {
      Transport trans = vehCommand.GetTransport();
      if (trans)
      {
        CarScript car;
        if (Class.CastTo(car, trans))
          car.OnBeforeEngineStart();
      }
    }
  }
References Class::CastTo().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 57 of file ActionStartEngine.c.
  {
    HumanCommandVehicle vehCommand = action_data.m_Player.GetCommand_Vehicle();
    if (vehCommand)
    {
      Transport trans = vehCommand.GetTransport();
      if (trans)
      {
        CarScript car;
        if (Class.CastTo(car, trans))
          car.EngineStart();
      }
    }
  }
References Class::CastTo().
Variable Documentation
m_BatteryCon
bool m_BatteryCon = false
DEPRECATED.
Definition at line 14 of file ActionStartEngine.c.
m_BeltCon
bool m_BeltCon = false
DEPRECATED.
Definition at line 16 of file ActionStartEngine.c.
m_FuelCon
bool m_FuelCon = false
DEPRECATED.
Definition at line 17 of file ActionStartEngine.c.
m_SparkCon
bool m_SparkCon = false
DEPRECATED.
Definition at line 15 of file ActionStartEngine.c.
MINIMUM_BATTERY_ENERGY
const float MINIMUM_BATTERY_ENERGY = 5.0 static
Definition at line 12 of file ActionStartEngine.c.
ROUGH_SPECIALTY_WEIGHT
ActionStartCarCB ROUGH_SPECIALTY_WEIGHT = 0.5
Referenced by ActionStartEngine().