DayZ: scripts/3_Game/DamageSystem.c File Reference
DamageSystem.c File Reference
Classes
class TotalDamageResult
Typedefs
typedef map< string, ref array< string > > DamageZoneMap
Enumerations
enum DamageType
exposed from C++ (do not change)
Functions
enum DamageType CloseCombatDamage (EntityAI source, Object targetObject, int targetComponentIndex, string ammoTypeName, vector worldPos, int directDamageFlags=ProcessDirectDamageFlags.ALL_TRANSFER)
static proto native void CloseCombatDamageName (EntityAI source, Object targetObject, string targetComponentName, string ammoTypeName, vector worldPos, int directDamageFlags=ProcessDirectDamageFlags.ALL_TRANSFER)
static proto native void ExplosionDamage (EntityAI source, Object directHitObject, string ammoTypeName, vector worldPos, int damageType)
static bool GetDamageZoneMap (EntityAI entity, out DamageZoneMap zoneMap)
static bool GetDamageZoneFromComponentName (notnull EntityAI entity, string component, out string damageZone)
Returns damage zone to which the named component belongs.
static bool GetComponentNamesFromDamageZone (notnull EntityAI entity, string damageZone, out array< string > componentNames)
static string GetDamageDisplayName (EntityAI entity, string zone)
static void ResetAllZones (EntityAI entity)
Variables
CLOSE_COMBAT
FIRE_ARM
EXPLOSION
STUN
CUSTOM
Typedef Documentation
DamageZoneMap
typedef map<string, ref array<string> > DamageZoneMap
Definition at line 141 of file DamageSystem.c.
Enumeration Type Documentation
DamageType
enum DamageType
exposed from C++ (do not change)
Definition at line 10 of file DamageSystem.c.
{
  CLOSE_COMBAT, // 0
  FIRE_ARM, // 1
  EXPLOSION,
  STUN,
  CUSTOM
}
Function Documentation
CloseCombatDamage()
enum DamageType CloseCombatDamage (EntityAI source, Object targetObject, int targetComponentIndex, string ammoTypeName, vector worldPos, int directDamageFlags = ProcessDirectDamageFlags.ALL_TRANSFER)
CloseCombatDamageName()
static proto native void CloseCombatDamageName (EntityAI source, Object targetObject, string targetComponentName, string ammoTypeName, vector worldPos, int directDamageFlags = ProcessDirectDamageFlags.ALL_TRANSFER) static
ExplosionDamage()
static proto native void ExplosionDamage (EntityAI source, Object directHitObject, string ammoTypeName, vector worldPos, int damageType) static
GetComponentNamesFromDamageZone()
static bool GetComponentNamesFromDamageZone (notnull EntityAI entity, string damageZone, out array< string > componentNames) static
Definition at line 94 of file DamageSystem.c.
  {
    string path;
    if (entity.IsWeapon())
      path = CFG_WEAPONSPATH;
    else if (entity.IsMagazine())
      path = CFG_MAGAZINESPATH;
    else
      path = CFG_VEHICLESPATH;
    path = string.Format("%1 %2 DamageSystem DamageZones %3 componentNames", path, entity.GetType(), damageZone);
    if (GetGame().ConfigIsExisting(path))
    {
      GetGame().ConfigGetTextArray(path, componentNames);
      return true;
    }
    return false;
  }
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, string::Format(), GetGame(), and path.
GetDamageDisplayName()
static string GetDamageDisplayName (EntityAI entity, string zone) static
Definition at line 115 of file DamageSystem.c.
  {
    string component_name;
    entity.GetEntityDamageDisplayNameMap().Find(zone.Hash(), component_name);
    component_name = Widget.TranslateString(component_name);
    return component_name;
  }
GetDamageZoneFromComponentName()
static bool GetDamageZoneFromComponentName (notnull EntityAI entity, string component, out string damageZone) static
Returns damage zone to which the named component belongs.
Definition at line 66 of file DamageSystem.c.
  {
    DamageZoneMap zoneMap = entity.GetEntityDamageZoneMap();
    array<array<string>> components;
    components = zoneMap.GetValueArray();
    for (int i = 0; i < components.Count(); i++)
    {
      array<string> inner = components.Get(i);
      for (int j = 0; j < inner.Count(); j++)
      {
        string innerComponentName = inner.Get(j);
        innerComponentName.ToLower();
        //We don't have a component name, no need to proceed
        if (innerComponentName == "")
          break;
        if (innerComponentName == component)
        {
          damageZone = zoneMap.GetKey(i);
          return true;
        }
      }
    }
    damageZone = "";
    return false;
  }
References component.
GetDamageZoneMap()
static bool GetDamageZoneMap (EntityAI entity, out DamageZoneMap zoneMap) static
Definition at line 27 of file DamageSystem.c.
  {
    string path_base;
    string path;
    if (entity.IsWeapon())
      path_base = CFG_WEAPONSPATH;
    else if (entity.IsMagazine())
      path_base = CFG_MAGAZINESPATH;
    else
      path_base = CFG_VEHICLESPATH;
    path_base = string.Format("%1 %2 DamageSystem DamageZones", path_base, entity.GetType());
    if (!GetGame().ConfigIsExisting(path_base))
      return false;
    else
    {
      string zone;
      array<string> zone_names = new array<string>;
      array<string> component_names;
      entity.GetDamageZones(zone_names);
      for (int i = 0; i < zone_names.Count(); i++)
      {
        component_names = new array<string>;
        zone = zone_names.Get(i);
        path = string.Format("%1 %2 componentNames ", path_base, zone);
        if (GetGame().ConfigIsExisting(path))
          GetGame().ConfigGetTextArray(path, component_names);
        zoneMap.Insert(zone, component_names);
      }
      return true;
    }
  }
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, string::Format(), GetGame(), and path.
ResetAllZones()
static void ResetAllZones (EntityAI entity) static
Definition at line 123 of file DamageSystem.c.
  {
    DamageZoneMap zonesMap = new DamageZoneMap();
    DamageSystem.GetDamageZoneMap(entity, zonesMap);
    array<string> zones = zonesMap.GetKeyArray();
    entity.SetHealth("", "Health", entity.GetMaxHealth("", "Health"));
    entity.SetHealth("", "Shock", entity.GetMaxHealth("", "Shock"));
    entity.SetHealth("", "Blood", entity.GetMaxHealth("", "Blood"));
    foreach (string zone : zones)
    {
      entity.SetHealth(zone, "Health", entity.GetMaxHealth(zone, "Health"));
      entity.SetHealth(zone, "Shock", entity.GetMaxHealth(zone, "Shock"));
      entity.SetHealth(zone, "Blood", entity.GetMaxHealth(zone, "Blood"));
    }
  }
Variable Documentation
CLOSE_COMBAT
CLOSE_COMBAT
Definition at line 0 of file DamageSystem.c.
CUSTOM
CUSTOM
Definition at line 4 of file DamageSystem.c.
EXPLOSION
EXPLOSION
Definition at line 2 of file DamageSystem.c.
FIRE_ARM
FIRE_ARM
Definition at line 1 of file DamageSystem.c.
STUN
STUN
Definition at line 3 of file DamageSystem.c.