DayZ: EffectTrigger Class Reference
EffectTrigger Class Reference
Protected Member Functions
void OnStayClientEvent (TriggerInsider insider, float deltaTime)
override void OnEnterServerEvent (TriggerInsider insider)
override void OnEnterClientEvent (TriggerInsider insider)
override void OnLeaveServerEvent (TriggerInsider insider)
override void OnLeaveClientEvent (TriggerInsider insider)
override bool ShouldRemoveInsider (TriggerInsider insider)
Static Protected Member Functions
static void TriggerEffect (EntityAI insider, typename triggerType)
Private Member Functions
override void OnEnterServerEvent (TriggerInsider insider)
override void OnLeaveServerEvent (TriggerInsider insider)
override void OnEnterClientEvent (TriggerInsider insider)
override void OnLeaveClientEvent (TriggerInsider insider)
override void OnStayStartServerEvent (int nrOfInsiders)
override void OnStayFinishServerEvent ()
override void OnStayServerEvent (TriggerInsider insider, float deltaTime)
override string GetAmbientSoundsetName ()
void EffectTrigger ()
void SetLocalEffects (int aroundPartId, int tinyPartId, int ppeRequesterIdx)
EffectArea GetEffectArea ()
void Init (EffectArea area, int priority)
int GetEffectsPriority ()
string GetAmbientSoundsetName ()
void SetupClientEffects (bool enable, notnull PlayerBase player)
override void EOnFrame (IEntity other, float timeSlice)
override bool CanAddObjectAsInsider (Object object)
Private Attributes
const float DAMAGE_TICK_RATE = 10
int m_AroundPartId
int m_TinyPartId
int m_PPERequester
float m_DeltaTime
float m_TimeAccuStay
bool m_DealDamageFlag
TriggerEffectManager m_Manager
EffectArea m_EffectArea
int m_EffectsPriority
Detailed Description
Definition at line 2 of file ContaminatedTrigger.c.
Constructor & Destructor Documentation
EffectTrigger()
void EffectTrigger::EffectTrigger () inline private
Definition at line 15 of file EffectTrigger.c.
  {
    RegisterNetSyncVariableInt("m_AroundPartId");
    RegisterNetSyncVariableInt("m_TinyPartId");
    RegisterNetSyncVariableInt("m_PPERequester");
    RegisterNetSyncVariableInt("m_EffectsPriority");
    m_Manager = TriggerEffectManager.GetInstance();
    m_Manager.RegisterTriggerType(this);
  }
References TriggerEffectManager::GetInstance(), m_Manager, and TriggerEffectManager::RegisterTriggerType().
Member Function Documentation
CanAddObjectAsInsider()
override bool EffectTrigger::CanAddObjectAsInsider (Object object) inline private
Definition at line 81 of file EffectTrigger.c.
  {
#ifdef SERVER
    DayZCreatureAI creature = DayZCreatureAI.Cast(object);
    if (creature)
      return !creature.ResistContaminatedEffect();
    else
    {
      PlayerBase player = PlayerBase.Cast(object);
      return player != null;
    }
#else
    PlayerBase player = PlayerBase.Cast(object);
    return (player && player.IsControlledPlayer());
#endif
  }
EOnFrame()
override void EffectTrigger::EOnFrame (IEntity other, float timeSlice) inline private
Definition at line 76 of file EffectTrigger.c.
  {
    m_DeltaTime = timeSlice;
  }
References m_DeltaTime.
GetAmbientSoundsetName() [1/2]
override string EffectTrigger::GetAmbientSoundsetName () inline private
Definition at line 79 of file ContaminatedTrigger.c.
  {
    return "ContaminatedArea_SoundSet";
  }
Referenced by OnStayClientEvent(), and SetupClientEffects().
GetAmbientSoundsetName() [2/2]
string EffectTrigger::GetAmbientSoundsetName () inline private
Definition at line 55 of file EffectTrigger.c.
  {
    return "";
  }
GetEffectArea()
EffectArea EffectTrigger::GetEffectArea () inline private
Definition at line 39 of file EffectTrigger.c.
  {
    return m_EffectArea;
  }
References m_EffectArea.
GetEffectsPriority()
int EffectTrigger::GetEffectsPriority () inline private
Definition at line 50 of file EffectTrigger.c.
  {
    return m_EffectsPriority;
  }
References m_EffectsPriority.
Referenced by ManBase::RequestTriggerEffect().
Init()
void EffectTrigger::Init (EffectArea area, int priority) inline private
Definition at line 44 of file EffectTrigger.c.
  {
    m_EffectArea = area;
    m_EffectsPriority = priority;
  }
References m_EffectArea, and m_EffectsPriority.
Referenced by EffectArea::CreateTrigger().
OnEnterClientEvent() [1/2]
override void EffectTrigger::OnEnterClientEvent (TriggerInsider insider) inline private
Definition at line 38 of file ContaminatedTrigger.c.
  {
    super.OnEnterClientEvent(insider);
  }
OnEnterClientEvent() [2/2]
override void EffectTrigger::OnEnterClientEvent (TriggerInsider insider) inline protected
Definition at line 123 of file EffectTrigger.c.
  {
    super.OnEnterClientEvent(insider);
    if (insider)
    {
      PlayerBase playerInsider = PlayerBase.Cast(insider.GetObject());
      // We will only handle the controlled player, as effects are only relevant to this player instance
      if (playerInsider && playerInsider.IsControlledPlayer())
      {
        //SetupClientEffects(true, playerInsider);
        // We then handle the update of player trigger state in manager
        m_Manager.OnPlayerEnter(playerInsider, this);
      }
    }
  }
References TriggerInsider::GetObject(), m_Manager, and TriggerEffectManager::OnPlayerEnter().
OnEnterServerEvent() [1/2]
override void EffectTrigger::OnEnterServerEvent (TriggerInsider insider) inline private
Definition at line 10 of file ContaminatedTrigger.c.
  {
    super.OnEnterServerEvent(insider);
    //Print("Entered A " + GetType());
    if (insider)
    {
      DayZCreatureAI creature = DayZCreatureAI.Cast(insider.GetObject());
      if (creature)
        creature.IncreaseEffectTriggerCount();
    }
  }
References TriggerInsider::GetObject().
OnEnterServerEvent() [2/2]
override void EffectTrigger::OnEnterServerEvent (TriggerInsider insider) inline protected
Definition at line 106 of file EffectTrigger.c.
  {
    super.OnEnterServerEvent(insider);
    // We don't need to test the trigger count as Modifiers handle such cases already
    if (insider)
    {
      PlayerBase playerInsider = PlayerBase.Cast(insider.GetObject());
      if (playerInsider)
        m_Manager.OnPlayerEnter(playerInsider, this);
    }
  }
References TriggerInsider::GetObject(), m_Manager, and TriggerEffectManager::OnPlayerEnter().
OnLeaveClientEvent() [1/2]
override void EffectTrigger::OnLeaveClientEvent (TriggerInsider insider) inline private
Definition at line 43 of file ContaminatedTrigger.c.
  {
    super.OnLeaveClientEvent(insider);
  }
OnLeaveClientEvent() [2/2]
override void EffectTrigger::OnLeaveClientEvent (TriggerInsider insider) inline protected
Definition at line 156 of file EffectTrigger.c.
  {
    super.OnLeaveClientEvent(insider);
    if (insider)
    {
      // Make sure you pass the set variable for PPE effect
      // It will not remove the correct one if START and STOP don't point to the same Requester
      PlayerBase playerInsider = PlayerBase.Cast(insider.GetObject());
      // We will only handle the controlled player, as effects are only relevant to this player instance
      if (playerInsider && playerInsider.IsControlledPlayer())
      {
        // We first handle the update of player trigger state in manager
        m_Manager.OnPlayerExit(playerInsider, this);
        //SetupClientEffects(false, playerInsider);
      }
    }
  }
References TriggerInsider::GetObject(), m_Manager, and TriggerEffectManager::OnPlayerExit().
OnLeaveServerEvent() [1/2]
override void EffectTrigger::OnLeaveServerEvent (TriggerInsider insider) inline private
Definition at line 24 of file ContaminatedTrigger.c.
  {
    super.OnLeaveServerEvent(insider);
    //Print("Left A " + GetType());
    if (insider)
    {
      DayZCreatureAI creature = DayZCreatureAI.Cast(insider.GetObject());
      if (creature)
        creature.DecreaseEffectTriggerCount();
    }
  }
References TriggerInsider::GetObject().
OnLeaveServerEvent() [2/2]
override void EffectTrigger::OnLeaveServerEvent (TriggerInsider insider) inline protected
Definition at line 142 of file EffectTrigger.c.
  {
    super.OnLeaveServerEvent(insider);
    if (insider)
    {
      PlayerBase playerInsider = PlayerBase.Cast(insider.GetObject());
      if (playerInsider)
        m_Manager.OnPlayerExit(playerInsider, this);
    }
  }
References TriggerInsider::GetObject(), m_Manager, and TriggerEffectManager::OnPlayerExit().
OnStayClientEvent()
void EffectTrigger::OnStayClientEvent (TriggerInsider insider, float deltaTime) inline protected
Definition at line 98 of file EffectTrigger.c.
  {
    super.OnStayClientEvent(insider, deltaTime);
    PlayerBase player = PlayerBase.Cast(insider.GetObject());
    if (player)
      player.RequestTriggerEffect(this, m_PPERequester, m_AroundPartId, m_TinyPartId, GetAmbientSoundsetName());
  }
References GetAmbientSoundsetName(), TriggerInsider::GetObject(), m_AroundPartId, m_PPERequester, and m_TinyPartId.
OnStayFinishServerEvent()
override void EffectTrigger::OnStayFinishServerEvent () inline private
Definition at line 60 of file ContaminatedTrigger.c.
  {
    if (m_DealDamageFlag) //the flag was previously set to true, the insiders have been updated at this point, reset the flag and the timer as well
    {
      m_TimeAccuStay = 0;
      m_DealDamageFlag = false;
    }
  }
OnStayServerEvent()
override void EffectTrigger::OnStayServerEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 69 of file ContaminatedTrigger.c.
  {
    if (m_DealDamageFlag)
    {
      DayZCreatureAI creature = DayZCreatureAI.Cast(insider.GetObject());
      if (creature && creature.m_EffectTriggerCount != 0)
        creature.DecreaseHealth("", "", GameConstants.AI_CONTAMINATION_DMG_PER_SEC * m_TimeAccuStay / creature.m_EffectTriggerCount);// we devide by m_EffectTriggerCount for multiple trigger presence(overlapping triggers)
    }
  }
References GameConstants::AI_CONTAMINATION_DMG_PER_SEC, and TriggerInsider::GetObject().
OnStayStartServerEvent()
override void EffectTrigger::OnStayStartServerEvent (int nrOfInsiders) inline private
Definition at line 49 of file ContaminatedTrigger.c.
  {
    m_TimeAccuStay += m_DeltaTime;
    if (m_TimeAccuStay > DAMAGE_TICK_RATE)
    {
      m_DealDamageFlag = true;
      //this is where we would normally reset the m_TimeAccuStay, but we need the value as deltaT when dealing damage to the insiders, so we reset it only after the insider update in OnStayFinishServerEvent
    }
  }
SetLocalEffects()
void EffectTrigger::SetLocalEffects (int aroundPartId, int tinyPartId, int ppeRequesterIdx) inline private
Definition at line 30 of file EffectTrigger.c.
  {
    m_AroundPartId = aroundPartId;
    m_TinyPartId = tinyPartId;
    m_PPERequester = ppeRequesterIdx;
    SetSynchDirty();
  }
References m_AroundPartId, m_PPERequester, and m_TinyPartId.
Referenced by EffectArea::CreateTrigger().
SetupClientEffects()
void EffectTrigger::SetupClientEffects (bool enable, notnull PlayerBase player) inline private
Definition at line 60 of file EffectTrigger.c.
  {
    if (!m_Manager.IsPlayerInTriggerType(player, this))
    {
      if (enable)
        player.SetContaminatedEffectEx(true, m_PPERequester, m_AroundPartId, m_TinyPartId, GetAmbientSoundsetName());
      else
        player.SetContaminatedEffectEx(false, m_PPERequester);
    }
  }
References GetAmbientSoundsetName(), TriggerEffectManager::IsPlayerInTriggerType(), m_AroundPartId, m_Manager, m_PPERequester, and m_TinyPartId.
ShouldRemoveInsider()
override bool EffectTrigger::ShouldRemoveInsider (TriggerInsider insider) inline protected
Definition at line 177 of file EffectTrigger.c.
  {
    return !insider.GetObject().IsAlive();
  }
References TriggerInsider::GetObject().
TriggerEffect()
static void EffectTrigger::TriggerEffect (EntityAI insider, typename triggerType) inline static protected
Definition at line 184 of file EffectTrigger.c.
{}
Member Data Documentation
DAMAGE_TICK_RATE
const float EffectTrigger::DAMAGE_TICK_RATE = 10 private
Definition at line 4 of file ContaminatedTrigger.c.
m_AroundPartId
int EffectTrigger::m_AroundPartId private
Definition at line 5 of file EffectTrigger.c.
Referenced by OnStayClientEvent(), SetLocalEffects(), and SetupClientEffects().
m_DealDamageFlag
bool EffectTrigger::m_DealDamageFlag private
Definition at line 10 of file EffectTrigger.c.
m_DeltaTime
float EffectTrigger::m_DeltaTime private
Definition at line 8 of file EffectTrigger.c.
Referenced by EOnFrame().
m_EffectArea
EffectArea EffectTrigger::m_EffectArea private
Definition at line 12 of file EffectTrigger.c.
Referenced by GetEffectArea(), and Init().
m_EffectsPriority
int EffectTrigger::m_EffectsPriority private
Definition at line 13 of file EffectTrigger.c.
Referenced by GetEffectsPriority(), and Init().
m_Manager
TriggerEffectManager EffectTrigger::m_Manager private
Definition at line 11 of file EffectTrigger.c.
Referenced by EffectTrigger(), OnEnterClientEvent(), OnEnterServerEvent(), OnLeaveClientEvent(), OnLeaveServerEvent(), and SetupClientEffects().
m_PPERequester
int EffectTrigger::m_PPERequester private
Definition at line 7 of file EffectTrigger.c.
Referenced by OnStayClientEvent(), ManBase::RemoveCurrentEffectTrigger(), SetLocalEffects(), and SetupClientEffects().
m_TimeAccuStay
float EffectTrigger::m_TimeAccuStay private
Definition at line 9 of file EffectTrigger.c.
m_TinyPartId
int EffectTrigger::m_TinyPartId private
Definition at line 6 of file EffectTrigger.c.
Referenced by OnStayClientEvent(), SetLocalEffects(), and SetupClientEffects().
The documentation for this class was generated from the following files:
scripts/4_World/Entities/ScriptedEntities/Triggers/ContaminatedTrigger.c
scripts/4_World/Entities/ScriptedEntities/Triggers/EffectTrigger.c