DayZ: ActionWorldCraft Class Reference
ActionWorldCraft Class Reference
Private Member Functions
void ActionWorldCraft ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override string GetText ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override string GetSoundCategory (ActionData action_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
override void Start (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnEndClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnFinishProgressClient (ActionData action_data)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Private Attributes
string m_ActionPrompt
Detailed Description
Definition at line 32 of file ActionWorldCraft.c.
Constructor & Destructor Documentation
ActionWorldCraft()
void ActionWorldCraft::ActionWorldCraft () inline private
Definition at line 36 of file ActionWorldCraft.c.
  {
    m_CallbackClass = ActionWorldCraftCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_CRAFTING;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH;
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, and m_StanceMask.
Member Function Documentation
ActionCondition()
override bool ActionWorldCraft::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 76 of file ActionWorldCraft.c.
  {
    //Client
    if (!GetGame().IsDedicatedServer())
      return true;
    else //Server
    {
      if (!target.GetObject() || !item)
        return false;
    }
    return true;
  }
References GetGame().
CreateActionData()
override ActionData ActionWorldCraft::CreateActionData () inline private
Definition at line 44 of file ActionWorldCraft.c.
  {
    ActionData action_data = new WorldCraftActionData;
    return action_data;
  }
CreateConditionComponents()
override void ActionWorldCraft::CreateConditionComponents () inline private
Definition at line 50 of file ActionWorldCraft.c.
  {
    m_ConditionItem = new CCINone;
    m_ConditionTarget = new CCTObject(UAMaxDistances.DEFAULT);
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetSoundCategory()
override string ActionWorldCraft::GetSoundCategory (ActionData action_data) inline private
Definition at line 90 of file ActionWorldCraft.c.
  {
    WorldCraftActionData actionDataWorldCraft = WorldCraftActionData.Cast(action_data);
    ItemBase target = ItemBase.Cast(actionDataWorldCraft.m_Target.GetObject());
    ItemBase item = actionDataWorldCraft.m_MainItem;
    PluginRecipesManager recipesManager = PluginRecipesManager.Cast(GetPlugin(PluginRecipesManager));
    string soundCat = recipesManager.GetSoundCategory(actionDataWorldCraft.m_RecipeID, target, item);
    return soundCat;
  }
References GetPlugin().
GetText()
override string ActionWorldCraft::GetText () inline private
Definition at line 63 of file ActionWorldCraft.c.
  {
    PlayerBase player;
    if (Class.CastTo(player, GetGame().GetPlayer()))
    {
      PluginRecipesManager module_recipes_manager;
      Class.CastTo(module_recipes_manager, GetPlugin(PluginRecipesManager));
      return module_recipes_manager.GetRecipeName(player.GetCraftingManager().GetRecipeID(m_VariantID));
    }
    return "Default worldcraft text";
  }
References Class::CastTo(), GetGame(), GetPlayer(), GetPlugin(), and m_VariantID.
HandleReciveData()
override void ActionWorldCraft::HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 187 of file ActionWorldCraft.c.
  {
    WorldCraftActionReciveData recive_data_wc = WorldCraftActionReciveData.Cast(action_recive_data);
    WorldCraftActionData action_data_wc = WorldCraftActionData.Cast(action_data);
    action_data_wc.m_MainItem = recive_data_wc.m_MainItem;
    if (!action_recive_data.m_Target)
      action_data.m_Target = new ActionTarget(NULL, NULL, -1, vector.Zero, 0);
    else
      action_data_wc.m_Target = recive_data_wc.m_Target;
    action_data_wc.m_RecipeID = recive_data_wc.m_RecipeID;
  }
References ActionTarget, and vector::Zero.
OnActionInfoUpdate()
override void ActionWorldCraft::OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 56 of file ActionWorldCraft.c.
  {
    PluginRecipesManager module_recipes_manager;
    Class.CastTo(module_recipes_manager, GetPlugin(PluginRecipesManager));
    m_Text = module_recipes_manager.GetRecipeName(player.GetCraftingManager().GetRecipeID(m_VariantID));
  }
References Class::CastTo(), GetPlugin(), m_Text, and m_VariantID.
OnEndClient()
override void ActionWorldCraft::OnEndClient (ActionData action_data) inline private
Definition at line 130 of file ActionWorldCraft.c.
  {
    if (action_data.m_Player) action_data.m_Player.TryHideItemInHands(false);
  }
OnEndServer()
override void ActionWorldCraft::OnEndServer (ActionData action_data) inline private
Definition at line 125 of file ActionWorldCraft.c.
  {
    if (action_data.m_Player) action_data.m_Player.TryHideItemInHands(false);
  }
OnFinishProgressClient()
override void ActionWorldCraft::OnFinishProgressClient (ActionData action_data) inline private
Definition at line 155 of file ActionWorldCraft.c.
  {
    /*ActionManagerClient am = ActionManagerClient.Cast(action_data.m_Player.GetActionManager());
      am.UnlockInventory(action_data);*/
  }
OnFinishProgressServer()
override void ActionWorldCraft::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 135 of file ActionWorldCraft.c.
  {
    /*if (!GetGame().IsMultiplayer())
      {
      ActionManagerClient am = ActionManagerClient.Cast(action_data.m_Player.GetActionManager());
      am.UnlockInventory(action_data);
      }*/
    WorldCraftActionData action_data_wc;
    PluginRecipesManager module_recipes_manager;
    ItemBase item2;
    Class.CastTo(action_data_wc, action_data);
    Class.CastTo(module_recipes_manager, GetPlugin(PluginRecipesManager));
    Class.CastTo(item2, action_data.m_Target.GetObject());
    if (action_data.m_MainItem && item2)
      module_recipes_manager.PerformRecipeServer(action_data_wc.m_RecipeID, action_data.m_MainItem, item2, action_data.m_Player);
  }
References Class::CastTo(), and GetPlugin().
ReadFromContext()
override bool ActionWorldCraft::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 170 of file ActionWorldCraft.c.
  {
    if (!action_recive_data)
      action_recive_data = new WorldCraftActionReciveData;
    super.ReadFromContext(ctx, action_recive_data);
    int recipeID;
    if (!ctx.Read(recipeID))
      return false;
    WorldCraftActionReciveData recive_data_wc = WorldCraftActionReciveData.Cast(action_recive_data);
    recive_data_wc.m_RecipeID = recipeID;
    return true;
  }
SetupAction()
override bool ActionWorldCraft::SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 104 of file ActionWorldCraft.c.
  {
    if (super.SetupAction(player, target, item, action_data, extra_data))
    {
      if (!GetGame().IsDedicatedServer())
      {
        WorldCraftActionData action_data_wc;
        Class.CastTo(action_data_wc, action_data);
        action_data_wc.m_RecipeID = player.GetCraftingManager().GetRecipeID(m_VariantID);
      }
      return true;
    }
    return false;
  }
References Class::CastTo(), GetGame(), and m_VariantID.
Start()
override void ActionWorldCraft::Start (ActionData action_data) inline private
Definition at line 119 of file ActionWorldCraft.c.
  {
    super.Start(action_data);
    if (action_data.m_Player) action_data.m_Player.TryHideItemInHands(true);
  }
WriteToContext()
override void ActionWorldCraft::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 161 of file ActionWorldCraft.c.
  {
    super.WriteToContext(ctx, action_data);
    WorldCraftActionData action_data_wc = WorldCraftActionData.Cast(action_data);
    ctx.Write(action_data_wc.m_RecipeID);
  }
Member Data Documentation
m_ActionPrompt
string ActionWorldCraft::m_ActionPrompt private
Definition at line 34 of file ActionWorldCraft.c.
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionWorldCraft.c