DayZ: ActionContinuousBase Class Reference
ActionContinuousBase Class Reference
Inherits AnimatedActionBase.
Inherited by ActionBandageBase [private], ActionBreakLongWoodenStick [private], ActionBuildPart [private], ActionBuildShelter [private], ActionBurnSewSelf [private], ActionBurnSewTarget [private], ActionBuryBody [private], ActionCPR [private], ActionCarHornLong [private], ActionCheckPulseTarget [private], ActionCollectBloodSelf [private], ActionCollectBloodTarget [private], ActionCollectSampleSelf [private], ActionCollectSampleTarget [private], ActionConsume [private], ActionCookOnStick [private], ActionCoverHeadSelf [private], ActionCoverHeadTarget [private], ActionCraft [private], ActionCraftBolts [private], ActionCraftBoltsFeather [private], ActionCraftBoneKnife [private], ActionCraftBoneKnifeEnv [private], ActionCraftImprovisedEyePatch [private], ActionCraftImprovisedFaceCover [private], ActionCraftImprovisedFeetCover [private], ActionCraftImprovisedHandsCover [private], ActionCraftImprovisedHeadCover [private], ActionCraftImprovisedLegsCover [private], ActionCraftImprovisedTorsoCover [private], ActionCraftRopeBelt [private], ActionCraftStoneKnifeEnv [private], ActionCreateGreenhouseGardenPlot [private], ActionDeconstructShelter [private], ActionDefibrilateBase [private], ActionDeployBase [private], ActionDestroyCombinationLock [private], ActionDestroyPart [private], ActionDigInStash [private], ActionDigWorms [private], ActionDisinfectBase [private], ActionDisinfectPlant [private], ActionDismantleGardenPlot [private], ActionDismantlePart [private], ActionDrainLiquid [private], ActionEmptyBottleBase [private], ActionEmptyMagazine [private], ActionFertilizeSlot [private], ActionFillBottleBase [private], ActionFillBrakes [private], ActionFillCoolant [private], ActionFillFuel [private], ActionFillGeneratorTank [private], ActionFillObject [private], ActionFillOil [private], ActionFishingNew [private], ActionGagSelf [private], ActionGagTarget [private], ActionGiveBloodSelf [private], ActionGiveBloodTarget [private], ActionGiveSalineSelf [private], ActionGiveSalineTarget [private], ActionIgniteFireplaceByAir [private], ActionLoadMagazine [private], ActionLoadMagazineQuick [private], ActionLockAttachment [private], ActionLockDoors [private], ActionLowerFlag [private], ActionMeasureTemperatureSelf [private], ActionMeasureTemperatureTarget [private], ActionMineBase [private], ActionMountBarbedWire [private], ActionPackGift [private], ActionPlaceOnGround [private], ActionPourLiquid [private], ActionPushCar [private], ActionRaiseFlag [private], ActionReadPaper [private], ActionRepackTent [private], ActionRepairCarChassis [private], ActionRepairTent [private], ActionRepairTentPart [private], ActionRestrainSelf [private], ActionRestrainTarget [private], ActionSawPlanks [private], ActionSetAlarmClock [private], ActionSetKitchenTimer [private], ActionShave [private], ActionShaveTarget [private], ActionSortAmmoPile [private], ActionSplintSelf [private], ActionSplintTarget [private], ActionStripCarrierVest [private], ActionTestBloodSelf [private], ActionTestBloodTarget [private], ActionTransferLiquid [private], ActionUncoverHeadBase [private], ActionUngagSelf [private], ActionUngagTarget [private], ActionUnlockDoors [private], ActionUnmountBarbedWire [private], ActionUnpackBox [private], ActionUnpackGift [private], ActionUnrestrainSelf [private], ActionUnrestrainTarget [private], ActionUnrestrainTargetHands [private], ActionUpgradeTorchFromGasPump [private], ActionUseRangefinder [private], ActionViewCompass [private], ActionViewOptics [private], ActionWashHandsItemContinuous [private], ActionWaterGardenSlot [private], ActionWaterPlant [private], ActionWorldCraft [private], ActionWringClothes [private], and ActionWritePaper [private].
Protected Member Functions
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Private Member Functions
void ActionContinuousBase ()
override void OnEndInput (ActionData action_data)
bool HasAlternativeInterrupt ()
override GetInputType ()
override int GetActionCategory ()
void OnStartAnimationLoop (ActionData action_data)
void OnEndAnimationLoop (ActionData action_data)
void OnFinishProgress (ActionData action_data)
Private Member Functions inherited from AnimatedActionBase
void AnimatedActionBase ()
void OnAlternativeEndServer (PlayerBase player)
void OnAlternativeEndClient (PlayerBase player)
void OnInterruptServer (PlayerBase player)
void OnInterruptClient (PlayerBase player)
void OnExecute (ActionData action_data)
void OnExecuteServer (ActionData action_data)
void OnExecuteClient (ActionData action_data)
void OnAnimationEvent (ActionData action_data)
override bool ActionConditionContinue (ActionData action_data)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
int GetActionCommand (PlayerBase player)
GetCallbackClassTypename ()
override bool HasProneException ()
void CreateAndSetupActionCallback (ActionData action_data)
override void Start (ActionData action_data)
override void Interrupt (ActionData action_data)
void OnJumpStart ()
void Do (ActionData action_data, int state)
override void End (ActionData action_data)
override float GetProgress (ActionData action_data)
Private Attributes
PluginAdminLog m_AdminLog
Private Attributes inherited from AnimatedActionBase
int m_CommandUID
int m_CommandUIDProne
m_CallbackClass
Detailed Description
Definition at line 118 of file ActionContinuousBase.c.
Constructor & Destructor Documentation
ActionContinuousBase()
void ActionContinuousBase::ActionContinuousBase () inline private
Definition at line 122 of file ActionContinuousBase.c.
  {
    m_CallbackClass = ActionContinuousBaseCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_EAT;
    if (GetGame() && GetGame().IsServer())
      m_AdminLog = PluginAdminLog.Cast(GetPlugin(PluginAdminLog));
  }
References GetGame(), GetPlugin(), m_AdminLog, AnimatedActionBase::m_CallbackClass, and AnimatedActionBase::m_CommandUID.
Member Function Documentation
GetActionCategory()
override int ActionContinuousBase::GetActionCategory () inline private
Definition at line 151 of file ActionContinuousBase.c.
  {
    return AC_CONTINUOUS;
  }
References AC_CONTINUOUS.
GetInputType()
override ActionContinuousBase::GetInputType () inline private
Definition at line 146 of file ActionContinuousBase.c.
  {
    return ContinuousDefaultActionInput;
  }
References ContinuousDefaultActionInput().
HasAlternativeInterrupt()
bool ActionContinuousBase::HasAlternativeInterrupt () inline private
Definition at line 141 of file ActionContinuousBase.c.
  {
    return false;
  }
OnEndAnimationLoop()
void ActionContinuousBase::OnEndAnimationLoop (ActionData action_data) inline private
Definition at line 168 of file ActionContinuousBase.c.
  {
    if (LogManager.IsActionLogEnable())
      Debug.ActionLog("Time stamp: " + action_data.m_Player.GetSimulationTimeStamp(), this.ToString(), "n/a", "OnEndAnimationLoop", action_data.m_Player.ToString());
    if (GetGame().IsServer())
      OnEndAnimationLoopServer(action_data);
    else
      OnEndAnimationLoopClient(action_data);
    action_data.m_WasExecuted = false;
  }
References Debug::ActionLog(), GetGame(), LogManager::IsActionLogEnable(), OnEndAnimationLoopClient(), and OnEndAnimationLoopServer().
OnEndAnimationLoopClient()
void ActionContinuousBase::OnEndAnimationLoopClient (ActionData action_data) inline protected
Definition at line 209 of file ActionContinuousBase.c.
  {
  }
Referenced by OnEndAnimationLoop().
OnEndAnimationLoopServer()
void ActionContinuousBase::OnEndAnimationLoopServer (ActionData action_data) inline protected
Definition at line 206 of file ActionContinuousBase.c.
  {
  }
Referenced by OnEndAnimationLoop().
OnEndInput()
override void ActionContinuousBase::OnEndInput (ActionData action_data) inline private
Definition at line 131 of file ActionContinuousBase.c.
  {
    ActionContinuousBaseCB callback;
    if (Class.CastTo(callback, action_data.m_Callback))
    {
      if (callback.GetState() != callback.STATE_LOOP_END && callback.GetState() != callback.STATE_LOOP_END2)
        callback.UserEndsAction();
    }
  }
References Class::CastTo().
OnFinishProgress()
void ActionContinuousBase::OnFinishProgress (ActionData action_data) inline private
Definition at line 179 of file ActionContinuousBase.c.
  {
    if (LogManager.IsActionLogEnable())
      Debug.ActionLog("Time stamp: " + action_data.m_Player.GetSimulationTimeStamp(), this.ToString(), "n/a", "OnFinishProgress", action_data.m_Player.ToString());
    if (GetGame().IsServer())
    {
      OnFinishProgressServer(action_data);
      if (m_AdminLog)
        m_AdminLog.OnContinouousAction(action_data);
    }
    else
      OnFinishProgressClient(action_data);
    action_data.m_WasExecuted = false;
  }
References Debug::ActionLog(), GetGame(), LogManager::IsActionLogEnable(), m_AdminLog, OnFinishProgressClient(), and OnFinishProgressServer().
OnFinishProgressClient()
void ActionContinuousBase::OnFinishProgressClient (ActionData action_data) inline protected
Definition at line 217 of file ActionContinuousBase.c.
  {
  }
Referenced by OnFinishProgress().
OnFinishProgressServer()
void ActionContinuousBase::OnFinishProgressServer (ActionData action_data) inline protected
Definition at line 213 of file ActionContinuousBase.c.
  {
  }
Referenced by OnFinishProgress().
OnStartAnimationLoop()
void ActionContinuousBase::OnStartAnimationLoop (ActionData action_data) inline private
Definition at line 156 of file ActionContinuousBase.c.
  {
    if (LogManager.IsActionLogEnable())
      Debug.ActionLog("Time stamp: " + action_data.m_Player.GetSimulationTimeStamp(), this.ToString(), "n/a", "OnStartAnimationLoop", action_data.m_Player.ToString());
    if (GetGame().IsServer())
      OnStartAnimationLoopServer(action_data);
    else
      OnStartAnimationLoopClient(action_data);
    action_data.m_WasExecuted = false;
  }
References Debug::ActionLog(), GetGame(), LogManager::IsActionLogEnable(), OnStartAnimationLoopClient(), and OnStartAnimationLoopServer().
OnStartAnimationLoopClient()
void ActionContinuousBase::OnStartAnimationLoopClient (ActionData action_data) inline protected
Definition at line 201 of file ActionContinuousBase.c.
  {
    action_data.m_WasActionStarted = true;
  }
Referenced by OnStartAnimationLoop().
OnStartAnimationLoopServer()
void ActionContinuousBase::OnStartAnimationLoopServer (ActionData action_data) inline protected
Definition at line 196 of file ActionContinuousBase.c.
  {
    action_data.m_WasActionStarted = true;
  }
Referenced by OnStartAnimationLoop().
Member Data Documentation
m_AdminLog
PluginAdminLog ActionContinuousBase::m_AdminLog private
Definition at line 120 of file ActionContinuousBase.c.
Referenced by ActionContinuousBase(), and OnFinishProgress().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/ActionContinuousBase.c