DayZ: ImprovisedExplosive Class Reference
ImprovisedExplosive Class Reference
Protected Member Functions
void ImprovisedExplosive ()
override void EOnInit (IEntity other, int extra)
override bool HasLockedTriggerSlots ()
override void LockTriggerSlots ()
override void UnlockTriggerSlots ()
override void LockExplosivesSlots ()
override void UnlockExplosivesSlots ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnVariablesSynchronized ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
override void PairRemote (notnull EntityAI trigger)
override EntityAI GetPairDevice ()
override bool CanBeArmed ()
override bool CanBeDisarmed ()
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanDisplayAttachmentSlot (int slot_id)
override bool IsTimerDetonable ()
override bool IsTakeable ()
override bool IsDeployable ()
override void SetActions ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void OnActivatedByItem (notnull ItemBase item)
void InitiateExplosion ()
not exploding itself, rely on attached explosives
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void OnBeforeDisarm ()
override void OnDisarmed (bool pWithTool)
override void UpdateLED (int pState)
void OnTriggerAttached (EntityAI entity)
void OnTriggerDetached (EntityAI entity)
void UpdateVisuals (EntityAI entity)
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
bool UsesGlobalDeploy ()
Protected Attributes
const float TIME_TRIGGER_INITIAL_DELAY_SECS = 0.1
const float TIME_TRIGGER_TIMER_BASED_DELAY_SECS = 1.0
const float TIME_TRIGGER_DELAY_SECS = 0.3
const int SLOT_EXPLOSIVE_COUNT = 2
const string SLOT_EXPLOSIVES [SLOT_EXPLOSIVE_COUNT]
const int SLOT_TRIGGERS_COUNT = 3
const string SLOT_TRIGGERS [SLOT_TRIGGERS_COUNT]
const string ANIM_PHASE_TRIGGER_EMPTY = "TriggerEmpty"
const string ANIM_PHASE_TRIGGER_TIMER = "TriggerTimer"
const string ANIM_PHASE_TRIGGER_CLOCK = "TriggerClock"
const string ANIM_PHASE_TRIGGER_REMOTE = "TriggerRemote"
ref RemotelyActivatedItemBehaviour m_RAIB
Static Protected Attributes
static const string SLOT_TRIGGER_ALARM_CLOCK = "TriggerAlarmClock"
static const string SLOT_TRIGGER_KITCHEN_TIMER = "TriggerKitchenTimer"
static const string SLOT_TRIGGER_REMOTE = "TriggerRemoteDetonator_Receiver"
static const string SLOT_EXPLOSIVE_A = "IEDExplosiveA"
static const string SLOT_EXPLOSIVE_B = "IEDExplosiveB"
Detailed Description
Definition at line 1 of file ImprovisedExplosive.c.
Constructor & Destructor Documentation
ImprovisedExplosive()
void ImprovisedExplosive::ImprovisedExplosive () inline protected
Definition at line 34 of file ImprovisedExplosive.c.
  {
    m_RAIB = new RemotelyActivatedItemBehaviour(this);
    RegisterNetSyncVariableInt("m_RAIB.m_PairDeviceNetIdLow");
    RegisterNetSyncVariableInt("m_RAIB.m_PairDeviceNetIdHigh");
  }
References m_RAIB.
Member Function Documentation
CanBeArmed()
override bool ImprovisedExplosive::CanBeArmed () inline protected
Definition at line 159 of file ImprovisedExplosive.c.
  {
    if (GetArmed())
      return false;
    if (!HasLockedTriggerSlots())
      return false;
    foreach (string slotName : SLOT_EXPLOSIVES)
    {
      EntityAI explosive = GetInventory().FindAttachmentByName(slotName);
      if (explosive)
        return true;
    }
    return false;
  }
References GetArmed(), HasLockedTriggerSlots(), SLOT_EXPLOSIVES, and slotName.
CanBeDisarmed()
override bool ImprovisedExplosive::CanBeDisarmed () inline protected
Definition at line 177 of file ImprovisedExplosive.c.
  {
    return true;
  }
CanDisplayAttachmentSlot()
override bool ImprovisedExplosive::CanDisplayAttachmentSlot (int slot_id) inline protected
Definition at line 200 of file ImprovisedExplosive.c.
  {
    string slotName = InventorySlots.GetSlotName(slot_id);
    switch (slotName)
    {
    case SLOT_TRIGGER_ALARM_CLOCK:
    case SLOT_TRIGGER_KITCHEN_TIMER:
    case SLOT_TRIGGER_REMOTE:
      return FindAttachmentBySlotName(slotName) != null;
      break;
    }
    return true;
  }
References InventorySlots::GetSlotName(), SLOT_TRIGGER_ALARM_CLOCK, SLOT_TRIGGER_KITCHEN_TIMER, SLOT_TRIGGER_REMOTE, and slotName.
CanReceiveAttachment()
override bool ImprovisedExplosive::CanReceiveAttachment (EntityAI attachment, int slotId) inline protected
Definition at line 183 of file ImprovisedExplosive.c.
  {
    InventoryLocation il = new InventoryLocation();
    GetInventory().GetCurrentInventoryLocation(il);
    foreach (string slotName : SLOT_TRIGGERS)
    {
      if (slotId == InventorySlots.GetSlotIdFromString(slotName))
      {
        if (il.GetType() == InventoryLocationType.HANDS)
          return false;
      }
    }
    return !GetArmed();
  }
References GetArmed(), InventorySlots::GetSlotIdFromString(), SLOT_TRIGGERS, and slotName.
EEHealthLevelChanged()
override void ImprovisedExplosive::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline protected
Definition at line 239 of file ImprovisedExplosive.c.
  {
    super.EEHealthLevelChanged(oldLevel, newLevel, zone);
    if (GetGame().IsServer())
    {
      if (newLevel == GameConstants.STATE_RUINED)
      {
        for (int attachmentIdx = 0; attachmentIdx < GetInventory().AttachmentCount(); attachmentIdx++)
        {
          ItemBase attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(attachmentIdx));
          if (attachment)
          {
            attachment.UnlockFromParent();
            attachment.SetHealth("", "", 0.0);
          }
        }
        SetArmed(false);
        SetTakeable(true);
      }
    }
  }
References GetGame(), SetArmed(), SetTakeable(), and GameConstants::STATE_RUINED.
EEItemAttached()
override void ImprovisedExplosive::EEItemAttached (EntityAI item, string slot_name) inline protected
Definition at line 337 of file ImprovisedExplosive.c.
  {
    super.EEItemAttached(item, slot_name);
    switch (slot_name)
    {
    case SLOT_TRIGGER_ALARM_CLOCK:
    case SLOT_TRIGGER_KITCHEN_TIMER:
    case SLOT_TRIGGER_REMOTE:
      OnTriggerAttached(FindAttachmentBySlotName(slot_name));
      break;
    }
  }
References OnTriggerAttached(), SLOT_TRIGGER_ALARM_CLOCK, SLOT_TRIGGER_KITCHEN_TIMER, and SLOT_TRIGGER_REMOTE.
EEItemDetached()
override void ImprovisedExplosive::EEItemDetached (EntityAI item, string slot_name) inline protected
Definition at line 351 of file ImprovisedExplosive.c.
  {
    super.EEItemDetached(item, slot_name);
    switch (slot_name)
    {
    case SLOT_TRIGGER_ALARM_CLOCK:
    case SLOT_TRIGGER_KITCHEN_TIMER:
    case SLOT_TRIGGER_REMOTE:
      OnTriggerDetached(FindAttachmentBySlotName(slot_name));
      break;
    }
  }
References OnTriggerDetached(), SLOT_TRIGGER_ALARM_CLOCK, SLOT_TRIGGER_KITCHEN_TIMER, and SLOT_TRIGGER_REMOTE.
EEItemLocationChanged()
override void ImprovisedExplosive::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline protected
Definition at line 136 of file ImprovisedExplosive.c.
  {
    super.EEItemLocationChanged(oldLoc, newLoc);
    if (m_RAIB)
      m_RAIB.Pair();
  }
References m_RAIB.
EOnInit()
override void ImprovisedExplosive::EOnInit (IEntity other, int extra) inline protected
Definition at line 42 of file ImprovisedExplosive.c.
  {
    if (!g_Game.IsMultiplayer())
      LockTriggerSlots();
  }
References g_Game, and LockTriggerSlots().
GetDeploySoundset()
override string ImprovisedExplosive::GetDeploySoundset () inline protected
Definition at line 472 of file ImprovisedExplosive.c.
  {
    return "placeImprovisedExplosive_SoundSet";
  }
GetLoopDeploySoundset()
override string ImprovisedExplosive::GetLoopDeploySoundset () inline protected
Definition at line 477 of file ImprovisedExplosive.c.
  {
    return "improvisedexplosive_deploy_SoundSet";
  }
GetPairDevice()
override EntityAI ImprovisedExplosive::GetPairDevice () inline protected
Definition at line 154 of file ImprovisedExplosive.c.
  {
    return m_RAIB.GetPairDevice();
  }
References m_RAIB.
GetRemotelyActivatedItemBehaviour()
override RemotelyActivatedItemBehaviour ImprovisedExplosive::GetRemotelyActivatedItemBehaviour () inline protected
Definition at line 144 of file ImprovisedExplosive.c.
  {
    return m_RAIB;
  }
References m_RAIB.
HasLockedTriggerSlots()
override bool ImprovisedExplosive::HasLockedTriggerSlots () inline protected
Definition at line 48 of file ImprovisedExplosive.c.
  {
    foreach (string triggerSlot : SLOT_TRIGGERS)
      return GetInventory().GetSlotLock(InventorySlots.GetSlotIdFromString(triggerSlot));
    return false;
  }
References InventorySlots::GetSlotIdFromString(), and SLOT_TRIGGERS.
Referenced by CanBeArmed().
InitiateExplosion()
void ImprovisedExplosive::InitiateExplosion () protected
not exploding itself, rely on attached explosives
IsDeployable()
override bool ImprovisedExplosive::IsDeployable () inline protected
Definition at line 226 of file ImprovisedExplosive.c.
  {
    return !GetArmed();
  }
References GetArmed().
IsTakeable()
override bool ImprovisedExplosive::IsTakeable () inline protected
Definition at line 221 of file ImprovisedExplosive.c.
  {
    return !GetArmed() && super.IsTakeable();
  }
References GetArmed().
IsTimerDetonable()
override bool ImprovisedExplosive::IsTimerDetonable () inline protected
Definition at line 216 of file ImprovisedExplosive.c.
  {
    return true;
  }
LockExplosivesSlots()
override void ImprovisedExplosive::LockExplosivesSlots () inline protected
Definition at line 68 of file ImprovisedExplosive.c.
  {
    foreach (string explosiveSlotName : SLOT_EXPLOSIVES)
      GetInventory().SetSlotLock(InventorySlots.GetSlotIdFromString(explosiveSlotName), true);
  }
References InventorySlots::GetSlotIdFromString(), and SLOT_EXPLOSIVES.
Referenced by OnTriggerAttached().
LockTriggerSlots()
override void ImprovisedExplosive::LockTriggerSlots () inline protected
Definition at line 56 of file ImprovisedExplosive.c.
  {
    foreach (string triggerSlotName : SLOT_TRIGGERS)
      GetInventory().SetSlotLock(InventorySlots.GetSlotIdFromString(triggerSlotName), true);
  }
References InventorySlots::GetSlotIdFromString(), and SLOT_TRIGGERS.
Referenced by EOnInit(), OnDisarmed(), OnStoreSave(), and OnTriggerAttached().
OnActivatedByItem()
override void ImprovisedExplosive::OnActivatedByItem (notnull ItemBase item) inline protected
attachment special handling on disarm
go through attached explosives
hard-case blocks shells (result of deferred delete)
defer delete to allow ringing
final traverse - attached explosives activation
defer damage to trigger attachments to allow ringing
Definition at line 263 of file ImprovisedExplosive.c.
  {
    if (GetGame().IsServer() && GetArmed())
    {
      bool isTimeTriggered = false;
      array<ItemBase> attachmentsCache = new array<ItemBase>();
      for (int attachmentIdx = 0; attachmentIdx < GetInventory().AttachmentCount(); attachmentIdx++)
      {
        ItemBase attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(attachmentIdx));
        if (attachment)
          attachmentsCache.Insert(attachment);
      }
      foreach (ItemBase attachment1 : attachmentsCache)
        attachment1.UnlockFromParent();
      foreach (ItemBase attachment2 : attachmentsCache)
      {
        if (attachment2.IsInherited(ClockBase))
        {
          isTimeTriggered = true;
          break;
        }
      }
      foreach (ItemBase attachment3 : attachmentsCache)
      {
        if (attachment3)
        {
          vector dropExtents = "0.5 0.0 0.5";
          if (isTimeTriggered)
            dropExtents[1] = 0.15;
          GetInventory().DropEntityInBounds(InventoryMode.SERVER, this, attachment3, dropExtents, 0, 0, 0);
          attachment3.SetAnimationPhase(ANIM_PHASE_VISIBILITY, 1.0);
          attachment3.SetTakeable(false);
        }
      }
      float delayFor = TIME_TRIGGER_INITIAL_DELAY_SECS;
      if (isTimeTriggered)
      {
        delayFor = TIME_TRIGGER_INITIAL_DELAY_SECS + TIME_TRIGGER_TIMER_BASED_DELAY_SECS;
        GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(DeleteSafe, delayFor * 1000, false);
      }
      else
        DeleteSafe();
      foreach (ItemBase attachment4 : attachmentsCache)
      {
        if (attachment4.IsAnyInherited({RemoteDetonator, ClockBase}))
        {
          GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(attachment4.DeleteSafe, delayFor * 1000, false);
        }
        if (attachment4 && !attachment4.IsAnyInherited({RemoteDetonator, ClockBase}))
        {
          Param1<ItemBase> params = new Param1<ItemBase>(attachment4);
          GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLaterByName(attachment4, "OnActivatedByItem", delayFor * 1000, false, params);
          delayFor += TIME_TRIGGER_DELAY_SECS;
        }
      }
    }
  }
References ANIM_PHASE_VISIBILITY, CALL_CATEGORY_SYSTEM, GetArmed(), GetGame(), TIME_TRIGGER_DELAY_SECS, TIME_TRIGGER_INITIAL_DELAY_SECS, and TIME_TRIGGER_TIMER_BASED_DELAY_SECS.
OnBeforeDisarm()
override void ImprovisedExplosive::OnBeforeDisarm () inline protected
Definition at line 365 of file ImprovisedExplosive.c.
  {
    UnlockExplosivesSlots();
  }
References UnlockExplosivesSlots().
OnDisarmed()
override void ImprovisedExplosive::OnDisarmed (bool pWithTool) inline protected
attachment special handling on disarm
Definition at line 370 of file ImprovisedExplosive.c.
  {
    super.OnDisarmed(pWithTool);
    UnpairRemote();
    array<ItemBase> attachmentsCache = new array<ItemBase>();
    for (int attachmentIdx = 0; attachmentIdx < GetInventory().AttachmentCount(); attachmentIdx++)
    {
      ItemBase attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(attachmentIdx));
      if (attachment)
        attachmentsCache.Insert(attachment);
    }
    foreach (ItemBase attachment1 : attachmentsCache)
      attachment1.UnlockFromParent();
    foreach (ItemBase attachment2 : attachmentsCache)
    {
      if (attachment2.IsInherited(ClockBase))
      {
        if (pWithTool)
          GetInventory().DropEntity(InventoryMode.SERVER, this, attachment2);
      }
      if (attachment2.IsInherited(RemoteDetonator))
      {
        if (pWithTool)
        {
          GetInventory().DropEntity(InventoryMode.SERVER, this, attachment2);
          attachment2.SetHealth("", "", 0.0);
        }
        else
          attachment2.Delete();
      }
    }
    LockTriggerSlots();
    SetTakeable(true);
  }
References LockTriggerSlots(), SetTakeable(), and UnpairRemote().
OnPlacementComplete()
override void ImprovisedExplosive::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline protected
Definition at line 128 of file ImprovisedExplosive.c.
  {
    super.OnPlacementComplete(player, position, orientation);
    if (GetGame().IsServer())
      SetOrientation(vector.Up);
  }
References GetGame(), and vector::Up.
OnStoreLoad()
override bool ImprovisedExplosive::OnStoreLoad (ParamsReadContext ctx, int version) inline protected
Definition at line 80 of file ImprovisedExplosive.c.
  {
    if (!super.OnStoreLoad(ctx, version))
      return false;
    if (version <= 134) // up to 1.21
    {
      foreach (string triggerSlotName : SLOT_TRIGGERS)
      {
        int slotId = InventorySlots.GetSlotIdFromString(triggerSlotName);
        bool locked = GetInventory().GetSlotLock(slotId);
        while (locked)
        {
          GetInventory().SetSlotLock(slotId, false);
          locked = GetInventory().GetSlotLock(slotId);
        }
      }
    }
    return true;
  }
References InventorySlots::GetSlotIdFromString(), and SLOT_TRIGGERS.
OnStoreSave()
override void ImprovisedExplosive::OnStoreSave (ParamsWriteContext ctx) inline protected
Definition at line 102 of file ImprovisedExplosive.c.
  {
    super.OnStoreSave(ctx);
    LockTriggerSlots();
  }
References LockTriggerSlots().
OnTriggerAttached()
void ImprovisedExplosive::OnTriggerAttached (EntityAI entity) inline protected
Definition at line 419 of file ImprovisedExplosive.c.
  {
    UpdateVisuals(entity);
    UpdateLED(ERemoteDetonatorLEDState.LIT);
    if (entity.IsInherited(ClockBase))
      Arm();
    LockTriggerSlots();
    LockExplosivesSlots();
  }
References Arm(), LockExplosivesSlots(), LockTriggerSlots(), UpdateLED(), and UpdateVisuals().
Referenced by EEItemAttached().
OnTriggerDetached()
void ImprovisedExplosive::OnTriggerDetached (EntityAI entity) inline protected
Definition at line 431 of file ImprovisedExplosive.c.
  {
    UpdateVisuals(null);
    UpdateLED(ERemoteDetonatorLEDState.OFF);
  }
References UpdateLED(), and UpdateVisuals().
Referenced by EEItemDetached().
OnVariablesSynchronized()
override void ImprovisedExplosive::OnVariablesSynchronized () inline protected
Definition at line 109 of file ImprovisedExplosive.c.
  {
    super.OnVariablesSynchronized();
    if (m_RAIB)
      m_RAIB.OnVariableSynchronized();
    foreach (string slotName : SLOT_TRIGGERS)
    {
      EntityAI trigger = GetInventory().FindAttachmentByName(slotName);
      if (trigger)
      {
        UpdateVisuals(trigger);
        break;
      }
    }
  }
References m_RAIB, SLOT_TRIGGERS, slotName, and UpdateVisuals().
PairRemote()
override void ImprovisedExplosive::PairRemote (notnull EntityAI trigger) inline protected
Definition at line 149 of file ImprovisedExplosive.c.
  {
    m_RAIB.Pair(trigger);
  }
References m_RAIB.
SetActions()
override void ImprovisedExplosive::SetActions () inline protected
Definition at line 231 of file ImprovisedExplosive.c.
  {
    super.SetActions();
    AddAction(ActionTogglePlaceObject);
    AddAction(ActionDeployObject);
  }
References AddAction().
UnlockExplosivesSlots()
override void ImprovisedExplosive::UnlockExplosivesSlots () inline protected
Definition at line 74 of file ImprovisedExplosive.c.
  {
    foreach (string explosiveSlotName : SLOT_EXPLOSIVES)
      GetInventory().SetSlotLock(InventorySlots.GetSlotIdFromString(explosiveSlotName), false);
  }
References InventorySlots::GetSlotIdFromString(), and SLOT_EXPLOSIVES.
Referenced by OnBeforeDisarm().
UnlockTriggerSlots()
override void ImprovisedExplosive::UnlockTriggerSlots () inline protected
Definition at line 62 of file ImprovisedExplosive.c.
  {
    foreach (string triggerSlotName : SLOT_TRIGGERS)
      GetInventory().SetSlotLock(InventorySlots.GetSlotIdFromString(triggerSlotName), false);
  }
References InventorySlots::GetSlotIdFromString(), and SLOT_TRIGGERS.
UpdateLED()
override void ImprovisedExplosive::UpdateLED (int pState) inline protected
Definition at line 412 of file ImprovisedExplosive.c.
  {
    RemoteDetonatorReceiver receiver = RemoteDetonatorReceiver.Cast(FindAttachmentBySlotName(SLOT_TRIGGER_REMOTE));
    if (receiver)
      receiver.UpdateLED(pState, true);
  }
References RemoteDetonatorReceiver(), and SLOT_TRIGGER_REMOTE.
Referenced by OnTriggerAttached(), and OnTriggerDetached().
UpdateVisuals()
void ImprovisedExplosive::UpdateVisuals (EntityAI entity) inline protected
Definition at line 437 of file ImprovisedExplosive.c.
  {
    if (entity)
    {
      if (entity.IsInherited(RemoteDetonator))
      {
        SetAnimationPhase(ANIM_PHASE_TRIGGER_EMPTY, 1.0);
        SetAnimationPhase(ANIM_PHASE_TRIGGER_TIMER, 1.0);
        SetAnimationPhase(ANIM_PHASE_TRIGGER_CLOCK, 1.0);
        SetAnimationPhase(ANIM_PHASE_TRIGGER_REMOTE, 0.0);
      }
      else if (entity.IsInherited(AlarmClock_ColorBase))
      {
        SetAnimationPhase(ANIM_PHASE_TRIGGER_EMPTY, 1.0);
        SetAnimationPhase(ANIM_PHASE_TRIGGER_TIMER, 1.0);
        SetAnimationPhase(ANIM_PHASE_TRIGGER_CLOCK, 0.0);
        SetAnimationPhase(ANIM_PHASE_TRIGGER_REMOTE, 1.0);
      }
      else if (entity.IsInherited(KitchenTimer))
      {
        SetAnimationPhase(ANIM_PHASE_TRIGGER_EMPTY, 1.0);
        SetAnimationPhase(ANIM_PHASE_TRIGGER_TIMER, 0.0);
        SetAnimationPhase(ANIM_PHASE_TRIGGER_CLOCK, 1.0);
        SetAnimationPhase(ANIM_PHASE_TRIGGER_REMOTE, 1.0);
      }
    }
    else
    {
      SetAnimationPhase(ANIM_PHASE_TRIGGER_EMPTY, 0.0);
      SetAnimationPhase(ANIM_PHASE_TRIGGER_TIMER, 1.0);
      SetAnimationPhase(ANIM_PHASE_TRIGGER_CLOCK, 1.0);
      SetAnimationPhase(ANIM_PHASE_TRIGGER_REMOTE, 1.0);
    }
  }
References ANIM_PHASE_TRIGGER_CLOCK, ANIM_PHASE_TRIGGER_EMPTY, ANIM_PHASE_TRIGGER_REMOTE, and ANIM_PHASE_TRIGGER_TIMER.
UsesGlobalDeploy()
bool ImprovisedExplosive::UsesGlobalDeploy () inline protected
Definition at line 482 of file ImprovisedExplosive.c.
  {
    return true;
  }
Member Data Documentation
ANIM_PHASE_TRIGGER_CLOCK
const string ImprovisedExplosive::ANIM_PHASE_TRIGGER_CLOCK = "TriggerClock" protected
Definition at line 29 of file ImprovisedExplosive.c.
Referenced by UpdateVisuals().
ANIM_PHASE_TRIGGER_EMPTY
const string ImprovisedExplosive::ANIM_PHASE_TRIGGER_EMPTY = "TriggerEmpty" protected
Definition at line 27 of file ImprovisedExplosive.c.
Referenced by UpdateVisuals().
ANIM_PHASE_TRIGGER_REMOTE
const string ImprovisedExplosive::ANIM_PHASE_TRIGGER_REMOTE = "TriggerRemote" protected
Definition at line 30 of file ImprovisedExplosive.c.
Referenced by UpdateVisuals().
ANIM_PHASE_TRIGGER_TIMER
const string ImprovisedExplosive::ANIM_PHASE_TRIGGER_TIMER = "TriggerTimer" protected
Definition at line 28 of file ImprovisedExplosive.c.
Referenced by UpdateVisuals().
m_RAIB
ref RemotelyActivatedItemBehaviour ImprovisedExplosive::m_RAIB protected
Definition at line 32 of file ImprovisedExplosive.c.
Referenced by EEItemLocationChanged(), GetPairDevice(), GetRemotelyActivatedItemBehaviour(), ImprovisedExplosive(), OnVariablesSynchronized(), and PairRemote().
SLOT_EXPLOSIVE_A
const string ImprovisedExplosive::SLOT_EXPLOSIVE_A = "IEDExplosiveA" static protected
Definition at line 11 of file ImprovisedExplosive.c.
SLOT_EXPLOSIVE_B
const string ImprovisedExplosive::SLOT_EXPLOSIVE_B = "IEDExplosiveB" static protected
Definition at line 12 of file ImprovisedExplosive.c.
SLOT_EXPLOSIVE_COUNT
const int ImprovisedExplosive::SLOT_EXPLOSIVE_COUNT = 2 protected
Definition at line 14 of file ImprovisedExplosive.c.
SLOT_EXPLOSIVES
const string ImprovisedExplosive::SLOT_EXPLOSIVES[SLOT_EXPLOSIVE_COUNT] protected
Initial value:
= {
    SLOT_EXPLOSIVE_A,
    SLOT_EXPLOSIVE_B
  }
Definition at line 15 of file ImprovisedExplosive.c.
{
    SLOT_EXPLOSIVE_A,
    SLOT_EXPLOSIVE_B
  };
Referenced by CanBeArmed(), LockExplosivesSlots(), and UnlockExplosivesSlots().
SLOT_TRIGGER_ALARM_CLOCK
const string ImprovisedExplosive::SLOT_TRIGGER_ALARM_CLOCK = "TriggerAlarmClock" static protected
Definition at line 7 of file ImprovisedExplosive.c.
Referenced by CanDisplayAttachmentSlot(), EEItemAttached(), and EEItemDetached().
SLOT_TRIGGER_KITCHEN_TIMER
const string ImprovisedExplosive::SLOT_TRIGGER_KITCHEN_TIMER = "TriggerKitchenTimer" static protected
Definition at line 8 of file ImprovisedExplosive.c.
Referenced by CanDisplayAttachmentSlot(), EEItemAttached(), and EEItemDetached().
SLOT_TRIGGER_REMOTE
const string ImprovisedExplosive::SLOT_TRIGGER_REMOTE = "TriggerRemoteDetonator_Receiver" static protected
Definition at line 9 of file ImprovisedExplosive.c.
Referenced by CanDisplayAttachmentSlot(), EEItemAttached(), EEItemDetached(), and UpdateLED().
SLOT_TRIGGERS
const string ImprovisedExplosive::SLOT_TRIGGERS[SLOT_TRIGGERS_COUNT] protected
Initial value:
= {
    SLOT_TRIGGER_ALARM_CLOCK,
    SLOT_TRIGGER_KITCHEN_TIMER,
    SLOT_TRIGGER_REMOTE
  }
Definition at line 21 of file ImprovisedExplosive.c.
{
    SLOT_TRIGGER_ALARM_CLOCK,
    SLOT_TRIGGER_KITCHEN_TIMER,
    SLOT_TRIGGER_REMOTE
  };
Referenced by CanReceiveAttachment(), HasLockedTriggerSlots(), LockTriggerSlots(), OnStoreLoad(), OnVariablesSynchronized(), and UnlockTriggerSlots().
SLOT_TRIGGERS_COUNT
const int ImprovisedExplosive::SLOT_TRIGGERS_COUNT = 3 protected
Definition at line 20 of file ImprovisedExplosive.c.
TIME_TRIGGER_DELAY_SECS
const float ImprovisedExplosive::TIME_TRIGGER_DELAY_SECS = 0.3 protected
Definition at line 5 of file ImprovisedExplosive.c.
Referenced by OnActivatedByItem().
TIME_TRIGGER_INITIAL_DELAY_SECS
const float ImprovisedExplosive::TIME_TRIGGER_INITIAL_DELAY_SECS = 0.1 protected
Definition at line 3 of file ImprovisedExplosive.c.
Referenced by OnActivatedByItem().
TIME_TRIGGER_TIMER_BASED_DELAY_SECS
const float ImprovisedExplosive::TIME_TRIGGER_TIMER_BASED_DELAY_SECS = 1.0 protected
Definition at line 4 of file ImprovisedExplosive.c.
Referenced by OnActivatedByItem().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ExplosivesBase/ImprovisedExplosive.c