DayZ: DayZPlayerImplementThrowing Class Reference
DayZPlayerImplementThrowing Class Reference
Private Member Functions
void DayZPlayerImplementThrowing (DayZPlayer pPlayer)
void HandleThrowing (HumanInputController pHic, HumanCommandWeapons pHcw, EntityAI pEntityInHands, float pDt)
void ResetState ()
void SetThrowingModeEnabled (bool enable)
bool IsThrowingModeEnabled ()
bool IsThrowingInProgress ()
Throwing wind-up only (button hold)
bool IsThrowingAnimationPlaying ()
Throwing animation after button release.
bool CanChangeThrowingStance (HumanInputController pHic)
bool CanContinueThrowing (HumanInputController pHic)
bool CanContinueThrowingEx (HumanInputController pHic, EntityAI pEntityInHands)
bool CheckFreeSpace ()
Private Attributes
DayZPlayer m_Player
bool m_bThrowingModeEnabled
bool m_bThrowingInProgress
bool m_bThrowingAnimationPlaying
float m_fThrowingForce01
const float c_fThrowingForceMin = 20.0
const float c_fThrowingForceMax = 90.0
const float c_fThrowingForceCoef = 1.0
Detailed Description
Definition at line 1 of file DayZPlayerImplementThrowing.c.
Constructor & Destructor Documentation
DayZPlayerImplementThrowing()
void DayZPlayerImplementThrowing::DayZPlayerImplementThrowing (DayZPlayer pPlayer) inline private
Definition at line 3 of file DayZPlayerImplementThrowing.c.
  {
    m_Player = pPlayer;
    SetThrowingModeEnabled(false);
    ResetState();
  }
References m_Player, ResetState(), and SetThrowingModeEnabled().
Member Function Documentation
CanChangeThrowingStance()
bool DayZPlayerImplementThrowing::CanChangeThrowingStance (HumanInputController pHic) inline private
Definition at line 149 of file DayZPlayerImplementThrowing.c.
  {
    // basic stance has priority
    if (pHic.IsStanceChange())
      return false;
    // don't change mode in raise
    if (pHic.IsWeaponRaised())
      return false;
    // check if it's not a heavy item
    HumanItemBehaviorCfg itemCfg = m_Player.GetItemAccessor().GetItemInHandsBehaviourCfg();
    if (itemCfg && itemCfg.m_iType == ItemBehaviorType.HEAVY)
      return false;
    /*    HumanMovementState movementState = new HumanMovementState();
        m_Player.GetMovementState(movementState);
        if( movementState.IsInProne() )
          return false;*/
    PlayerBase playerPB = PlayerBase.Cast(m_Player);
    if (playerPB)
    {
      if (playerPB.GetEmoteManager().IsEmotePlaying())
        return false;
      if (playerPB.GetActionManager().GetRunningAction() != NULL)
        return false;
      if (playerPB.IsRestrained() || playerPB.IsItemsToDelete())
        return false;
      if (playerPB.GetDayZPlayerInventory().IsProcessing())
        return false;
      if (playerPB.GetWeaponManager().IsRunning())
        return false;
    }
    if (!CheckFreeSpace())
      return false;
    return true;
  }
References CheckFreeSpace(), and m_Player.
Referenced by HandleThrowing().
CanContinueThrowing()
bool DayZPlayerImplementThrowing::CanContinueThrowing (HumanInputController pHic) inline private
Definition at line 194 of file DayZPlayerImplementThrowing.c.
  {
    HumanItemBehaviorCfg itemInHandsCfg = m_Player.GetItemAccessor().GetItemInHandsBehaviourCfg();
    bool boo = false;
    UAInterface input_interface = m_Player.GetInputInterface();
    if (input_interface && input_interface.SyncedPress("UAGear"))
      boo = true;
    if (boo || pHic.IsWeaponRaised() || (itemInHandsCfg && itemInHandsCfg.m_iType == ItemBehaviorType.HEAVY))
      return false;
    if (!CheckFreeSpace())
      return false;
    return true;
  }
References CheckFreeSpace(), and m_Player.
Referenced by CanContinueThrowingEx().
CanContinueThrowingEx()
bool DayZPlayerImplementThrowing::CanContinueThrowingEx (HumanInputController pHic, EntityAI pEntityInHands) inline private
Definition at line 210 of file DayZPlayerImplementThrowing.c.
  {
    if (pEntityInHands == null)
      return false;
    return CanContinueThrowing(pHic);
  }
References CanContinueThrowing().
Referenced by HandleThrowing().
CheckFreeSpace()
bool DayZPlayerImplementThrowing::CheckFreeSpace () inline private
Definition at line 218 of file DayZPlayerImplementThrowing.c.
  {
    return m_Player.CheckFreeSpace(vector.Forward, 0.7, false);
  }
References vector::Forward, and m_Player.
Referenced by CanChangeThrowingStance(), and CanContinueThrowing().
HandleThrowing()
void DayZPlayerImplementThrowing::HandleThrowing (HumanInputController pHic, HumanCommandWeapons pHcw, EntityAI pEntityInHands, float pDt) inline private
current state
handle mode change
handle action
cancel throwing in case of raising hands or heavy item in hands
check event for throw
handle throw force
Definition at line 11 of file DayZPlayerImplementThrowing.c.
  {
    if (!pEntityInHands && !m_bThrowingAnimationPlaying)
    {
      if (m_bThrowingModeEnabled)
      {
        SetThrowingModeEnabled(false);
        pHcw.SetThrowingMode(false);
      }
      return;
    }
    SetThrowingModeEnabled(pHcw.IsThrowingMode());
    if (pHic.IsThrowingModeChange() && CanChangeThrowingStance(pHic))
    {
      ResetState();
      pHcw.SetActionProgressParams(0, 0);
      pHcw.SetThrowingMode(!m_bThrowingModeEnabled);
    }
    if (m_bThrowingModeEnabled)
    {
      if (!CanContinueThrowingEx(pHic, pEntityInHands))
      {
        SetThrowingModeEnabled(false);
        ResetState();
        pHcw.SetActionProgressParams(0, 0);
        pHcw.SetThrowingMode(false);
        return;
      }
      if (pHcw.WasItemLeaveHandsEvent())
      {
        float lr = pHcw.GetBaseAimingAngleLR();
        float ud = pHcw.GetBaseAimingAngleUD();
        vector aimOrientation = m_Player.GetOrientation();
        aimOrientation[0] = aimOrientation[0] + lr;
        //add 5 deg
        aimOrientation[1] = aimOrientation[1] + ud + 5;
        m_Player.GetHumanInventory().ThrowEntity(pEntityInHands, aimOrientation.AnglesToVector(), c_fThrowingForceMin + m_fThrowingForce01 * (c_fThrowingForceMax - c_fThrowingForceMin));
        return;
      }
      if (!m_bThrowingAnimationPlaying)
      {
        if (pHic.IsAttackButton())
        {
          if (!m_bThrowingInProgress)
            m_bThrowingInProgress = true;
          m_fThrowingForce01 += pDt * c_fThrowingForceCoef;
          if (m_fThrowingForce01 > 1.0)
            m_fThrowingForce01 = 1.0;
          pHcw.SetActionProgressParams(m_fThrowingForce01, 0);
        }
        else
        {
          HumanCommandMove hcm = m_Player.GetCommand_Move();
          bool standingFromBack = hcm && hcm.IsStandingFromBack();
          if (m_bThrowingInProgress && !standingFromBack)
          {
            m_bThrowingInProgress = false;
            int throwType = 1;
            HumanItemBehaviorCfg itemCfg = m_Player.GetItemAccessor().GetItemInHandsBehaviourCfg();
            itemCfg = m_Player.GetItemAccessor().GetItemInHandsBehaviourCfg();
            if (itemCfg)
            {
              switch (itemCfg.m_iType)
              {
              case ItemBehaviorType.TWOHANDED:
              case ItemBehaviorType.POLEARMS:
                throwType = 2;
                break;
              case ItemBehaviorType.FIREARMS:
                throwType = 3;
              }
            }
            pHcw.ThrowItem(throwType);
            m_bThrowingAnimationPlaying = true;
          }
        }
      }
    }
    else
      ResetState();
  }
References c_fThrowingForceCoef, c_fThrowingForceMax, c_fThrowingForceMin, CanChangeThrowingStance(), CanContinueThrowingEx(), m_bThrowingAnimationPlaying, m_bThrowingInProgress, m_bThrowingModeEnabled, m_fThrowingForce01, m_Player, ResetState(), and SetThrowingModeEnabled().
IsThrowingAnimationPlaying()
bool DayZPlayerImplementThrowing::IsThrowingAnimationPlaying () inline private
Throwing animation after button release.
Definition at line 144 of file DayZPlayerImplementThrowing.c.
  {
    return m_bThrowingAnimationPlaying;
  }
References m_bThrowingAnimationPlaying.
Referenced by ActionPossibilityCheck().
IsThrowingInProgress()
bool DayZPlayerImplementThrowing::IsThrowingInProgress () inline private
Throwing wind-up only (button hold)
Definition at line 138 of file DayZPlayerImplementThrowing.c.
  {
    return m_bThrowingInProgress;
  }
References m_bThrowingInProgress.
IsThrowingModeEnabled()
bool DayZPlayerImplementThrowing::IsThrowingModeEnabled () inline private
Definition at line 132 of file DayZPlayerImplementThrowing.c.
  {
    return m_bThrowingModeEnabled;
  }
References m_bThrowingModeEnabled.
Referenced by CanPlayEmote().
ResetState()
void DayZPlayerImplementThrowing::ResetState () inline private
Definition at line 118 of file DayZPlayerImplementThrowing.c.
  {
    m_fThrowingForce01 = 0;
    m_bThrowingInProgress = false;
    m_bThrowingAnimationPlaying = false;
  }
References m_bThrowingAnimationPlaying, m_bThrowingInProgress, and m_fThrowingForce01.
Referenced by DayZPlayerImplementThrowing(), and HandleThrowing().
SetThrowingModeEnabled()
void DayZPlayerImplementThrowing::SetThrowingModeEnabled (bool enable) inline private
Definition at line 125 of file DayZPlayerImplementThrowing.c.
  {
    if (enable != m_bThrowingModeEnabled)
      m_Player.OnThrowingModeChange(enable);
    m_bThrowingModeEnabled = enable;
  }
References m_bThrowingModeEnabled, and m_Player.
Referenced by DayZPlayerImplementThrowing(), and HandleThrowing().
Member Data Documentation
c_fThrowingForceCoef
const float DayZPlayerImplementThrowing::c_fThrowingForceCoef = 1.0 private
Definition at line 231 of file DayZPlayerImplementThrowing.c.
Referenced by HandleThrowing().
c_fThrowingForceMax
const float DayZPlayerImplementThrowing::c_fThrowingForceMax = 90.0 private
Definition at line 230 of file DayZPlayerImplementThrowing.c.
Referenced by HandleThrowing().
c_fThrowingForceMin
const float DayZPlayerImplementThrowing::c_fThrowingForceMin = 20.0 private
Definition at line 229 of file DayZPlayerImplementThrowing.c.
Referenced by HandleThrowing().
m_bThrowingAnimationPlaying
bool DayZPlayerImplementThrowing::m_bThrowingAnimationPlaying private
Definition at line 226 of file DayZPlayerImplementThrowing.c.
Referenced by HandleThrowing(), IsThrowingAnimationPlaying(), and ResetState().
m_bThrowingInProgress
bool DayZPlayerImplementThrowing::m_bThrowingInProgress private
Definition at line 225 of file DayZPlayerImplementThrowing.c.
Referenced by HandleThrowing(), IsThrowingInProgress(), and ResetState().
m_bThrowingModeEnabled
bool DayZPlayerImplementThrowing::m_bThrowingModeEnabled private
Definition at line 224 of file DayZPlayerImplementThrowing.c.
Referenced by HandleThrowing(), IsThrowingModeEnabled(), and SetThrowingModeEnabled().
m_fThrowingForce01
float DayZPlayerImplementThrowing::m_fThrowingForce01 private
Definition at line 227 of file DayZPlayerImplementThrowing.c.
Referenced by HandleThrowing(), and ResetState().
m_Player
DayZPlayer DayZPlayerImplementThrowing::m_Player private
Definition at line 223 of file DayZPlayerImplementThrowing.c.
Referenced by CanChangeThrowingStance(), CanContinueThrowing(), CheckFreeSpace(), DayZPlayerImplementThrowing(), HandleThrowing(), and SetThrowingModeEnabled().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/DayZPlayerImplementThrowing.c