DayZ: InjuredLegNotfr Class Reference
InjuredLegNotfr Class Reference
Private Member Functions
void InjuredLegNotfr (NotifiersManager manager)
override int GetNotifierType ()
override void DisplayBadge ()
override void HideBadge ()
Private Member Functions inherited from NotifierBase
int CalculateTendency (float delta, float inctresholdlow, float inctresholdmed, float inctresholdhigh, float dectresholdlow, float dectresholdmed, float dectresholdhigh)
eBadgeLevel DetermineBadgeLevel (float value, float lvl_1, float lvl_2, float lvl_3)
void DisplayBadge ()
void HideBadge ()
float GetObservedValue ()
Detailed Description
Definition at line 1 of file InjuredLegNotfr.c.
Constructor & Destructor Documentation
InjuredLegNotfr()
void InjuredLegNotfr::InjuredLegNotfr (NotifiersManager manager) inline private
Definition at line 3 of file InjuredLegNotfr.c.
  {
    m_Active = true;
  }
References NotifierBase::m_Active.
Member Function Documentation
DisplayBadge()
override void InjuredLegNotfr::DisplayBadge () inline private
Definition at line 14 of file InjuredLegNotfr.c.
  {
    DisplayElementBadge dis_elm = DisplayElementBadge.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_BADGE_LEGS));
    if (dis_elm)
    {
      float legHealthInverted = 1 - Math.Min(m_Player.GetHealth01("LeftLeg", ""), m_Player.GetHealth01("RightLeg", ""));
      int level = eBadgeLevel.NONE;
      if (m_Player.GetBrokenLegs() == eBrokenLegs.NO_BROKEN_LEGS)
        level = DetermineBadgeLevel(legHealthInverted, 0.05, 0.35, 0.65);
      dis_elm.SetLevel(level);
    }
  }
References NotifierBase::DetermineBadgeLevel(), GetElement(), NotifierBase::GetVirtualHud(), NotifierBase::m_Player, and Math::Min().
GetNotifierType()
override int InjuredLegNotfr::GetNotifierType () inline private
Definition at line 8 of file InjuredLegNotfr.c.
  {
    return eNotifiers.NTF_LEGS;
  }
HideBadge()
override void InjuredLegNotfr::HideBadge () inline private
Definition at line 29 of file InjuredLegNotfr.c.
  {
    DisplayElementBadge dis_elm = DisplayElementBadge.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_BADGE_LEGS));
    if (dis_elm)
      dis_elm.SetLevel(eBadgeLevel.NONE);
  }
References GetElement(), and NotifierBase::GetVirtualHud().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/PlayerNotifiers/Notifiers/InjuredLegNotfr.c