DayZ: AttachmentsGroupContainer Class Reference
AttachmentsGroupContainer Class Reference
Private Member Functions
override void SetLayoutName ()
override void SetHeader (Header header)
override Header GetHeader ()
void AttachmentsGroupContainer (LayoutHolder parent)
override void SetActive (bool active)
override void SetDefaultFocus (bool while_micromanagment_mode=false)
SlotsIcon GetSlotsIcon (int row, int column, bool include_invisible=true)
int GetRowCount (bool include_invisible=true)
int GetColumnCountForRow (int row, bool include_invisible=true)
override void SetNextActive ()
override void SetPreviousActive (bool force=false)
Private Member Functions inherited from Container
void CargoContainer (LayoutHolder parent, bool is_attachment=false)
void ~CargoContainer ()
int GetCargoIndex ()
void AddedToCargoEx (EntityAI item, bool refresh=true)
void AddedToCargo (EntityAI item)
void RemovedFromCargo (EntityAI item)
void MovedInCargo (EntityAI item)
void SetLock (EntityAI item)
void ReleaseLock (EntityAI item)
override void SetLayoutName ()
void SetEntity (EntityAI item, int cargo_index=0, bool immedUpdate=true)
EntityAI GetEntity ()
void UpdateHeaderText ()
void InitGridHeight ()
void UpdateSize ()
float GetIconSize ()
float GetSpaceSize ()
int GetCargoCapacity ()
int GetMaxCargoCapacity ()
Icon GetIcon (EntityAI item)
Icon GetIcon (int index)
Icon GetFocusedIcon ()
override float GetFocusedContainerHeight (bool contents=false)
override float GetFocusedContainerYPos (bool contents=false)
override float GetFocusedContainerYScreenPos (bool contents=false)
void UpdateSelection ()
void UpdateRowVisibility (int count)
override void Refresh ()
void RefreshImpl ()
override void UpdateInterval ()
Icon InitIconEx (Icon icon, EntityAI item, int pos_x, int pos_y, bool refresh=true)
Icon InitIcon (Icon icon, EntityAI item, int pos_x, int pos_y)
bool HasItem (EntityAI item)
override bool TransferItemToVicinity ()
override void SetDefaultFocus (bool while_micromanagment_mode=false)
override void SetLastFocus ()
override void Unfocus ()
override void UnfocusAll ()
override void SetNextActive ()
override void SetPreviousActive (bool force=false)
override void SetNextRightActive ()
override void SetNextLeftActive ()
override EntityAI GetFocusedItem ()
override void SetLastActive ()
override void SetActive (bool active)
override bool IsItemActive ()
override bool IsItemWithQuantityActive ()
override bool IsEmpty ()
int GetRecipeCount (bool recipe_anywhere, ItemBase entity1, ItemBase entity2, PlayerBase player)
override bool CanCombineAmmo ()
override bool TransferItem ()
override bool SplitItem ()
override bool EquipItem ()
override bool SelectItem ()
override bool Select ()
override bool Combine ()
void ShowFalseCargoHeader (bool show)
void SetAlternateFalseTextHeaderWidget (TextWidget w)
void ClosableContainer (LayoutHolder parent, int sort=-1)
override bool IsDisplayable ()
override void UpdateRadialIcon ()
void SetOpenState (bool state)
override Header GetHeader ()
override void Open ()
override void Close ()
override void SetLayoutName ()
override void OnShow ()
override LayoutHolder Get (int x)
override void Refresh ()
void CloseButtonOnMouseButtonDown ()
override float GetFocusedContainerHeight (bool contents=false)
override float GetFocusedContainerYPos (bool contents=false)
override float GetFocusedContainerYScreenPos (bool contents=false)
void MoveContainerUp (Widget cont)
void MoveContainerDown (Widget cont)
override void CheckHeaderDragability ()
Private Attributes
ref Header m_Header
Private Attributes inherited from Container
const int ROWS_NUMBER_XBOX = 5
CargoBase m_Cargo
int m_CargoIndex = -1
int m_FocusedItemPosition = -1
ref array< ref CargoContainerRow > m_Rows
ref array< ref Icon > m_Icons
ref map< EntityAI, ref Param3< ref Icon, int, int > > m_ShowedItemPositions
ref map< EntityAI, ref Param3< ref Icon, int, int > > m_ShowedLockPositions
float m_IconSize
float m_SpaceSize
bool m_IsAttachment
TextWidget m_FalseHeaderTextWidget
TextWidget m_AlternateFalseHeaderTextWidget
Widget m_CargoHeader
Widget m_CargoContainer
Widget m_ItemsContainer
ref SizeToChild m_Resizer1
ref SizeToChild m_Resizer2
ref Timer m_ResizeTimer
ref ClosableHeader m_ClosableHeader
bool m_LockCargo
Detailed Description
Definition at line 1 of file AttachmentsGroupContainer.c.
Constructor & Destructor Documentation
AttachmentsGroupContainer()
void AttachmentsGroupContainer::AttachmentsGroupContainer (LayoutHolder parent) inline private
Definition at line 21 of file AttachmentsGroupContainer.c.
  {
    m_FocusedColumn = 0;
  }
Member Function Documentation
GetColumnCountForRow()
int AttachmentsGroupContainer::GetColumnCountForRow (int row, bool include_invisible = true) inline private
Definition at line 57 of file AttachmentsGroupContainer.c.
  {
    Container c;
    if (include_invisible)
      c = Container.Cast(m_Body[row]);
    else
      c = Container.Cast(m_OpenedContainers[row]);
    return c.GetColumnCount();
  }
GetHeader()
override Header AttachmentsGroupContainer::GetHeader () inline private
Definition at line 16 of file AttachmentsGroupContainer.c.
  {
    return m_Header;
  }
References m_Header.
GetRowCount()
int AttachmentsGroupContainer::GetRowCount (bool include_invisible = true) inline private
Definition at line 49 of file AttachmentsGroupContainer.c.
  {
    if (include_invisible)
      return m_Body.Count();
    else
      return m_OpenedContainers.Count();
  }
GetSlotsIcon()
SlotsIcon AttachmentsGroupContainer::GetSlotsIcon (int row, int column, bool include_invisible = true) inline private
Definition at line 39 of file AttachmentsGroupContainer.c.
  {
    SlotsContainer c;
    if (include_invisible)
      c = SlotsContainer.Cast(m_Body[row]);
    else
      c = SlotsContainer.Cast(m_OpenedContainers[row]);
    return c.GetSlotIcon(column);
  }
SetActive()
override void AttachmentsGroupContainer::SetActive (bool active) inline private
Definition at line 26 of file AttachmentsGroupContainer.c.
  {
    super.SetActive(active);
    if (!active)
      m_FocusedColumn = 0;
  }
SetDefaultFocus()
override void AttachmentsGroupContainer::SetDefaultFocus (bool while_micromanagment_mode = false) inline private
Definition at line 33 of file AttachmentsGroupContainer.c.
  {
    super.SetDefaultFocus();
    m_FocusedColumn = 0;
  }
SetHeader()
override void AttachmentsGroupContainer::SetHeader (Header header) inline private
Definition at line 10 of file AttachmentsGroupContainer.c.
  {
    m_Header = header;
    m_Header.GetMainWidget().SetFlags(WidgetFlags.IGNOREPOINTER);
  }
References m_Header.
SetLayoutName()
override void AttachmentsGroupContainer::SetLayoutName () inline private
Definition at line 5 of file AttachmentsGroupContainer.c.
  {
    m_LayoutName = WidgetLayoutName.AttachmentsGroupContainer;
  }
References WidgetLayoutName::AttachmentsGroupContainer.
SetNextActive()
override void AttachmentsGroupContainer::SetNextActive () inline private
Definition at line 67 of file AttachmentsGroupContainer.c.
  {
    HideOwnedTooltip();
    int visible_focus = 0;
    SlotsContainer active;
    if (m_OpenedContainers.Count())
      active = SlotsContainer.Cast(m_OpenedContainers[m_ActiveIndex]);
    if (active && active.IsActive())
    {
      visible_focus = active.GetVisibleFocus();
      active.SetNextActive();
    }
    if (!active || !active.IsActive())
    {
      SlotsContainer next;
      if (!IsLastContainerFocused())
      {
        m_ActiveIndex++;
        //int visible_focus = active.GetVisibleFocus();
        next = SlotsContainer.Cast(m_OpenedContainers[m_ActiveIndex]);
        next.SetActive(true);
        next.SetVisibleFocus(visible_focus);
      }
      else if (Container.Cast(GetParent()))
        SetActive(false);
      else
      {
        SetActive(false);
        SetFirstActive();
      }
    }
  }
References GetParent(), and SetActive().
SetPreviousActive()
override void AttachmentsGroupContainer::SetPreviousActive (bool force = false) inline private
Definition at line 104 of file AttachmentsGroupContainer.c.
  {
    HideOwnedTooltip();
    int visible_focus = 0;
    SlotsContainer active;
    if (m_OpenedContainers.Count())
      active = SlotsContainer.Cast(m_OpenedContainers[m_ActiveIndex]);
    if (active && active.IsActive())
    {
      visible_focus = active.GetVisibleFocus();
      active.SetPreviousActive();
    }
    if (!active || !active.IsActive())
    {
      SlotsContainer prev;
      if (!IsFirstContainerFocused())
      {
        m_ActiveIndex--;
        prev = SlotsContainer.Cast(m_OpenedContainers[m_ActiveIndex]);
        prev.SetActive(true);
        prev.SetVisibleFocus(visible_focus);
      }
      else if (Container.Cast(GetParent()))
        SetActive(false);
      else
      {
        SetActive(false);
        SetLastActive();
      }
    }
  }
References GetParent(), SetActive(), and Container::SetLastActive().
Member Data Documentation
m_Header
ref Header AttachmentsGroupContainer::m_Header private
Definition at line 3 of file AttachmentsGroupContainer.c.
Referenced by GetHeader(), and SetHeader().
The documentation for this class was generated from the following file:
scripts/5_Mission/GUI/InventoryNew/Containers/AttachmentsGroupContainer.c