DayZ: scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionActivateTrap.c File Reference
ActionActivateTrap.c File Reference
Classes
class ActionActivateTrapCB
Functions
ActionActivateTrapCB ActionContinuousBaseCB ActionActivateTrap ()
override void CreateActionComponent ()
override void InitActionComponent ()
override void CreateConditionComponents ()
override GetInputType ()
override bool HasProgress ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStartAnimationLoop (ActionData action_data)
override void OnEnd (ActionData action_data)
override void OnEndAnimationLoop (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Function Documentation
ActionActivateTrap()
ActionActivateTrapCB ActionContinuousBaseCB ActionActivateTrap ()
Definition at line 1 of file ActionActivateTrap.c.
  {
    m_CallbackClass = ActionActivateTrapCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_CRAFTING;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH;
    m_Sound = "craft_universal_0";
    m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
    m_Text = "#activate";
  }
Referenced by ActionConstructor::RegisterActions(), SetActions(), and ItemBase::SetActions().
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 46 of file ActionActivateTrap.c.
  {
    ItemBase targetItem = ItemBase.Cast(target.GetObject());
    if (targetItem && targetItem.IsBeingPlaced())
      return false;
    Object targetObject = target.GetObject();
    if (targetObject != null)
    {
      if (targetObject.IsInherited(TrapBase))
      {
        TrapBase trap = TrapBase.Cast(targetObject);
        if (trap.IsActivable())
          return true;
      }
      else if (targetObject.IsInherited(TrapSpawnBase))
      {
        TrapSpawnBase spawnTrap = TrapSpawnBase.Cast(targetObject);
        if (spawnTrap && !spawnTrap.IsActive())
          return spawnTrap.IsPlaceableAtPosition(spawnTrap.GetPosition());
      }
    }
    return false;
  }
CreateActionComponent()
override void ActionActivateTrap::CreateActionComponent ()
Definition at line 19 of file ActionActivateTrap.c.
  {
    m_CallbackClass = ActionActivateTrapCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_CRAFTING;
    m_FullBody = true;
References m_FullBody, and m_StanceMask.
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 30 of file ActionActivateTrap.c.
  {
    m_ConditionTarget = new CCTNonRuined(UAMaxDistances.DEFAULT);
    m_ConditionItem = new CCINotPresent;
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetInputType()
override GetInputType ()
Definition at line 36 of file ActionActivateTrap.c.
  {
    return ContinuousInteractActionInput;
  }
HasProgress()
override bool HasProgress ()
Definition at line 41 of file ActionActivateTrap.c.
  {
    return true;
  }
InitActionComponent()
override void ActionActivateTrap::InitActionComponent ()
Definition at line 24 of file ActionActivateTrap.c.
OnEnd()
override void OnEnd (ActionData action_data)
Definition at line 88 of file ActionActivateTrap.c.
  {
    if (!GetGame().IsMultiplayer() || GetGame().IsServer())
    {
      TrapBase trap = TrapBase.Cast(action_data.m_Target.GetObject());
      if (trap)
      {
        Param1<bool> play = new Param1<bool>(false);
        GetGame().RPCSingleParam(trap, SoundTypeTrap.ACTIVATING, play, true);
      }
    }
  }
References GetGame().
OnEndAnimationLoop()
override void OnEndAnimationLoop (ActionData action_data)
Definition at line 101 of file ActionActivateTrap.c.
  {
    super.OnEndAnimationLoop(action_data);
    if (!GetGame().IsMultiplayer() || GetGame().IsServer())
    {
      TrapBase trap = TrapBase.Cast(action_data.m_Target.GetObject());
      Param1<bool> play = new Param1<bool>(false);
      GetGame().RPCSingleParam(trap, SoundTypeTrap.ACTIVATING, play, true);
    }
  }
References GetGame().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 113 of file ActionActivateTrap.c.
  {
    Object targetObject = action_data.m_Target.GetObject();
    if (targetObject != null)
    {
      vector orientation = action_data.m_Player.GetOrientation();
      vector position = targetObject.GetPosition();
      if (targetObject.IsInherited(TrapBase))
      {
        TrapBase trap = TrapBase.Cast(targetObject);
        trap.OnPlacementComplete(action_data.m_Player, position, orientation);
        trap.StartActivate(action_data.m_Player);
      }
      else if (targetObject.IsInherited(TrapSpawnBase))
      {
        TrapSpawnBase spawnTrap = TrapSpawnBase.Cast(targetObject);
        spawnTrap.OnPlacementComplete(action_data.m_Player, position, orientation);
      }
    }
  }
OnStartAnimationLoop()
override void OnStartAnimationLoop (ActionData action_data)
Definition at line 73 of file ActionActivateTrap.c.
  {
    super.OnStartAnimationLoop(action_data);
    if (!GetGame().IsMultiplayer() || GetGame().IsServer())
    {
      TrapBase trap = TrapBase.Cast(action_data.m_Target.GetObject());
      if (trap)
      {
        Param1<bool> play = new Param1<bool>(true);
        GetGame().RPCSingleParam(trap, SoundTypeTrap.ACTIVATING, play, true);
      }
    }
  }
References GetGame().