DayZ: scripts/4_World/Plugins/PluginBase/PluginPresenceNotifier.c File Reference
PluginPresenceNotifier.c File Reference
Classes
class PresenceNotifierNoiseEvents
Enumerations
enum EPresenceNotifierNoiseEventType { LAND_LIGHT , LAND_HEAVY }
Functions
void PresenceNotifierNoiseEvent (float pValue, float pLength)
float GetTimerLength ()
int GetValue ()
void PluginPresenceNotifier ()
void ~PluginPresenceNotifier ()
void Init (PlayerBase player)
void EnableDebug (bool pEnabled)
void ShowCoefsDbg (bool pEnabled)
int GetNoisePresence ()
returns actual noise presence of player
int GetVisualPresence ()
returns actual visibility presence of player
void ProcessEvent (EPresenceNotifierNoiseEventType pEventType)
processing of external one-time events (land, fire, etc.)
int ProcessVisualComponents ()
int ProcessNoiseComponents ()
float GetMovementSpeedVisualCoef ()
Visibility.
float GetMovementStanceVisualCoef ()
int GetMovementSpeedNoiseComponent ()
int GetBootsNoiseComponent ()
int GetSurfaceNoiseComponent ()
DEPRECATED.
int GetExternalNoiseEventsComponent ()
DEPRECATED.
Variables
enum EPresenceNotifierNoiseEventType m_TimerLength
int m_Value
class PresenceNotifierNoiseEvents windowPosX = 0
dbgUI settings
const int windowPosY = 10
const int mainPanelSizeX = 200
const int mainPanelSizeY = 1
const int margin = 10
const int NOISE_LEVEL_MIN = 0
noise limits
const int NOISE_LEVEL_MAX = 5
const int SURFACE_NOISE_LVL0 = 0
noise component from surfaces
const int SURFACE_NOISE_LVL1 = 1
const int SURFACE_NOISE_LVL2 = 2
const float SURFACE_LVL2_THRESHOLD = 1.0
const float SURFACE_LVL1_THRESHOLD = 0.5
const int LAND_NOISE_LVL1 = 2
land noise
const int LAND_NOISE_LVL2 = 3
PlayerBase m_pPlayer
ref PresenceNotifierNoiseEvents m_PresenceNotifierNoiseEvents
Enumeration Type Documentation
EPresenceNotifierNoiseEventType
enum EPresenceNotifierNoiseEventType
Enumerator
LAND_LIGHT
LAND_HEAVY
Definition at line 1 of file PluginPresenceNotifier.c.
{
  LAND_LIGHT,
  LAND_HEAVY,
}
Function Documentation
EnableDebug()
void EnableDebug (bool pEnabled) protected
Definition at line 120 of file PluginPresenceNotifier.c.
  {
    ShowCoefsDbg(pEnabled);
  }
References ShowCoefsDbg().
GetBootsNoiseComponent()
int GetBootsNoiseComponent () protected
noise component of presence based on player's shoes DEPRECATED
GetExternalNoiseEventsComponent()
int GetExternalNoiseEventsComponent () protected
DEPRECATED.
GetMovementSpeedNoiseComponent()
int GetMovementSpeedNoiseComponent () protected
Noise related noise component of presence based on player's speed DEPRECATED
GetMovementSpeedVisualCoef()
float GetMovementSpeedVisualCoef () protected
Visibility.
Definition at line 222 of file PluginPresenceNotifier.c.
  {
    HumanMovementState hms = new HumanMovementState();
    float speedCoef = 1.0;
    m_pPlayer.GetMovementState(hms);
    switch (AITargetCallbacksPlayer.StanceToMovementIdxTranslation(hms))
    {
    case DayZPlayerConstants.MOVEMENTIDX_RUN:
      speedCoef = 0.66;
      break;
    case DayZPlayerConstants.MOVEMENTIDX_WALK:
      speedCoef = 0.33;
      break;
    case DayZPlayerConstants.MOVEMENTIDX_IDLE:
      speedCoef = 0;
      break;
    }
    return speedCoef;
  }
References m_pPlayer, and AITargetCallbacksPlayer::StanceToMovementIdxTranslation().
Referenced by ProcessVisualComponents(), and ShowCoefsDbg().
GetMovementStanceVisualCoef()
float GetMovementStanceVisualCoef () protected
Definition at line 244 of file PluginPresenceNotifier.c.
  {
    HumanMovementState hms = new HumanMovementState();
    float stanceCoef = 1.0;
    m_pPlayer.GetMovementState(hms);
    switch (hms.m_iStanceIdx)
    {
    case DayZPlayerConstants.STANCEIDX_CROUCH:
    case DayZPlayerConstants.STANCEIDX_RAISEDCROUCH:
      stanceCoef = 0.33;
      break;
    case DayZPlayerConstants.STANCEIDX_PRONE:
    case DayZPlayerConstants.STANCEIDX_RAISEDPRONE:
      stanceCoef = 0.11;
      break;
    }
    return stanceCoef;
  }
References m_pPlayer.
Referenced by ProcessVisualComponents(), and ShowCoefsDbg().
GetNoisePresence()
int GetNoisePresence () protected
returns actual noise presence of player
Definition at line 182 of file PluginPresenceNotifier.c.
  {
    return ProcessNoiseComponents();
  }
References ProcessNoiseComponents().
Referenced by ShowCoefsDbg().
GetSurfaceNoiseComponent()
int GetSurfaceNoiseComponent () protected
DEPRECATED.
GetTimerLength()
float GetTimerLength () protected
Definition at line 18 of file PluginPresenceNotifier.c.
  {
    return m_TimerLength;
  }
References m_TimerLength.
GetValue()
int GetValue () protected
Definition at line 23 of file PluginPresenceNotifier.c.
  {
    return m_Value;
  }
References m_Value.
GetVisualPresence()
int GetVisualPresence () protected
returns actual visibility presence of player
Definition at line 188 of file PluginPresenceNotifier.c.
  {
    return ProcessVisualComponents();
  }
References ProcessVisualComponents().
Referenced by ShowCoefsDbg().
Init()
void Init (PlayerBase player) protected
Definition at line 115 of file PluginPresenceNotifier.c.
  {
    m_pPlayer = player;
  }
References m_pPlayer.
PluginPresenceNotifier()
void PluginPresenceNotifier () protected
Definition at line 106 of file PluginPresenceNotifier.c.
  {
    m_PresenceNotifierNoiseEvents = new PresenceNotifierNoiseEvents();
    m_PresenceNotifierNoiseEvents.RegisterEvent(EPresenceNotifierNoiseEventType.LAND_LIGHT, LAND_NOISE_LVL1, 0.25);
    m_PresenceNotifierNoiseEvents.RegisterEvent(EPresenceNotifierNoiseEventType.LAND_HEAVY, LAND_NOISE_LVL2, 0.25);
  }
References LAND_NOISE_LVL1, LAND_NOISE_LVL2, and m_PresenceNotifierNoiseEvents.
Referenced by ManBase::OnSelectPlayer().
PresenceNotifierNoiseEvent()
void PresenceNotifierNoiseEvent (float pValue, float pLength) protected
Definition at line 12 of file PluginPresenceNotifier.c.
  {
    m_Value = pValue;
    m_TimerLength = pLength;
  }
References m_TimerLength, and m_Value.
Referenced by PresenceNotifierNoiseEvents::ProcessEvent(), and PresenceNotifierNoiseEvents::RegisterEvent().
ProcessEvent()
void ProcessEvent (EPresenceNotifierNoiseEventType pEventType) protected
processing of external one-time events (land, fire, etc.)
Definition at line 194 of file PluginPresenceNotifier.c.
  {
    m_PresenceNotifierNoiseEvents.ProcessEvent(pEventType);
  }
References m_PresenceNotifierNoiseEvents.
ProcessNoiseComponents()
int ProcessNoiseComponents () protected
Definition at line 208 of file PluginPresenceNotifier.c.
  {
    float noise = 0;
    if (m_pPlayer)
    {
      noise = NoiseAIEvaluate.GetNoiseMultiplier(m_pPlayer);
      noise = Math.Round(noise * NOISE_LEVEL_MAX);
    }
    return Math.Clamp(noise, NOISE_LEVEL_MIN, NOISE_LEVEL_MAX);
  }
References Math::Clamp(), NoiseAIEvaluate::GetNoiseMultiplier(), m_pPlayer, NOISE_LEVEL_MAX, NOISE_LEVEL_MIN, and Math::Round().
Referenced by GetNoisePresence().
ProcessVisualComponents()
int ProcessVisualComponents () protected
Definition at line 199 of file PluginPresenceNotifier.c.
  {
    float visualMean = 0;
    if (m_pPlayer)
      visualMean = (m_pPlayer.GetVisibilityCoef() + GetMovementSpeedVisualCoef() + GetMovementStanceVisualCoef()) / 3;
    return visualMean;
  }
References GetMovementSpeedVisualCoef(), GetMovementStanceVisualCoef(), and m_pPlayer.
Referenced by GetVisualPresence().
ShowCoefsDbg()
void ShowCoefsDbg (bool pEnabled) protected
HumanMovementState content
Definition at line 125 of file PluginPresenceNotifier.c.
  {
    DbgUI.BeginCleanupScope();
    if (pEnabled && m_pPlayer)
    {
      HumanMovementState hms = new HumanMovementState();
      m_pPlayer.GetMovementState(hms);
      string visualAlertLevel;
      string noiseAlertLevel;
      DbgUI.Begin("Presence Notifier", windowPosX + 10, windowPosY);
      DbgUI.Panel("MinimumSize", mainPanelSizeX, mainPanelSizeY);
      DbgUI.Text("Visual: ");
      DbgUI.Text("Visibility: " + m_pPlayer.GetVisibilityCoef());
      DbgUI.Text("Speed: " + GetMovementSpeedVisualCoef());
      DbgUI.Text("Stance: " + GetMovementStanceVisualCoef());
      DbgUI.Spacer(10);
      DbgUI.Panel("-- Noises", mainPanelSizeX, 2);
      DbgUI.Text("Noises: ");
      DbgUI.Text("Speed:  " + NoiseAIEvaluate.GetNoiseMultiplierByPlayerSpeed(m_pPlayer));
      DbgUI.Text("Boots: " + NoiseAIEvaluate.GetNoiseMultiplierByShoes(m_pPlayer));
      DbgUI.Text("Surface: " + NoiseAIEvaluate.GetNoiseMultiplierBySurface(m_pPlayer) + " [ cfg: " + m_pPlayer.GetSurfaceNoise() + "]");
      DbgUI.Spacer(10);
      DbgUI.Panel("-- Result", mainPanelSizeX, 2);
      DbgUI.Text("Result: ");
      visualAlertLevel = "";
      for (int iv = 0; iv < GetVisualPresence(); iv++)
        visualAlertLevel += "!";
      DbgUI.Text("Visual level: " + GetVisualPresence() + " [" + visualAlertLevel + "]");
      noiseAlertLevel = "";
      for (int ia = 0; ia < GetNoisePresence(); ia++)
        noiseAlertLevel += "!";
      DbgUI.Text("Noise level: " + GetNoisePresence() + " [" + noiseAlertLevel + "]");
      DbgUI.End();
      DbgUI.Begin("HumanMovementState", windowPosX + 250, windowPosY);
      DbgUI.Panel("MinimumSize", mainPanelSizeX, mainPanelSizeY);
      DbgUI.Text("Command ID: " + hms.m_CommandTypeId);
      DbgUI.Text("Stance: " + hms.m_iStanceIdx);
      DbgUI.Text("Movement: " + hms.m_iMovement);
      DbgUI.End();
    }
    DbgUI.EndCleanupScope();
  }
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::End(), DbgUI::EndCleanupScope(), GetMovementSpeedVisualCoef(), GetMovementStanceVisualCoef(), NoiseAIEvaluate::GetNoiseMultiplierByPlayerSpeed(), NoiseAIEvaluate::GetNoiseMultiplierByShoes(), NoiseAIEvaluate::GetNoiseMultiplierBySurface(), GetNoisePresence(), GetVisualPresence(), m_pPlayer, mainPanelSizeX, mainPanelSizeY, DbgUI::Panel(), DbgUI::Spacer(), DbgUI::Text(), windowPosX, and windowPosY.
Referenced by EnableDebug().
~PluginPresenceNotifier()
void ~PluginPresenceNotifier () protected
Definition at line 113 of file PluginPresenceNotifier.c.
{}
Variable Documentation
LAND_NOISE_LVL1
const int LAND_NOISE_LVL1 = 2 protected
land noise
Definition at line 97 of file PluginPresenceNotifier.c.
Referenced by PluginPresenceNotifier().
LAND_NOISE_LVL2
const int LAND_NOISE_LVL2 = 3 protected
Definition at line 98 of file PluginPresenceNotifier.c.
Referenced by PluginPresenceNotifier().
m_pPlayer
PlayerBase m_pPlayer protected
Definition at line 102 of file PluginPresenceNotifier.c.
m_PresenceNotifierNoiseEvents
ref PresenceNotifierNoiseEvents m_PresenceNotifierNoiseEvents protected
Definition at line 104 of file PluginPresenceNotifier.c.
Referenced by PluginPresenceNotifier(), and ProcessEvent().
m_TimerLength
enum EPresenceNotifierNoiseEventType m_TimerLength
Referenced by GetTimerLength(), and PresenceNotifierNoiseEvent().
m_Value
int m_Value protected
Definition at line 10 of file PluginPresenceNotifier.c.
mainPanelSizeX
const int mainPanelSizeX = 200 protected
Definition at line 79 of file PluginPresenceNotifier.c.
Referenced by OnGUI(), and ShowCoefsDbg().
mainPanelSizeY
const int mainPanelSizeY = 1 protected
Definition at line 80 of file PluginPresenceNotifier.c.
Referenced by OnGUI(), and ShowCoefsDbg().
margin
const int margin = 10 protected
Definition at line 81 of file PluginPresenceNotifier.c.
Referenced by OnGUI().
NOISE_LEVEL_MAX
const int NOISE_LEVEL_MAX = 5 protected
Definition at line 86 of file PluginPresenceNotifier.c.
Referenced by ProcessNoiseComponents().
NOISE_LEVEL_MIN
const int NOISE_LEVEL_MIN = 0 protected
noise limits
Definition at line 85 of file PluginPresenceNotifier.c.
Referenced by ProcessNoiseComponents().
SURFACE_LVL1_THRESHOLD
const float SURFACE_LVL1_THRESHOLD = 0.5 protected
Definition at line 94 of file PluginPresenceNotifier.c.
SURFACE_LVL2_THRESHOLD
const float SURFACE_LVL2_THRESHOLD = 1.0 protected
Definition at line 93 of file PluginPresenceNotifier.c.
SURFACE_NOISE_LVL0
const int SURFACE_NOISE_LVL0 = 0 protected
noise component from surfaces
Definition at line 89 of file PluginPresenceNotifier.c.
SURFACE_NOISE_LVL1
const int SURFACE_NOISE_LVL1 = 1 protected
Definition at line 90 of file PluginPresenceNotifier.c.
SURFACE_NOISE_LVL2
const int SURFACE_NOISE_LVL2 = 2 protected
Definition at line 91 of file PluginPresenceNotifier.c.
windowPosX
class PresenceNotifierNoiseEvents windowPosX = 0 protected
dbgUI settings
Referenced by OnGUI(), and ShowCoefsDbg().
windowPosY
const int windowPosY = 10 protected
Definition at line 78 of file PluginPresenceNotifier.c.
Referenced by OnGUI(), and ShowCoefsDbg().