DayZ: SVNDiffPlugin Class Reference
SVNDiffPlugin Class Reference
Private Member Functions
override void Run ()
override void Configure ()
void OkButton ()
Private Attributes
string CommandLine
Detailed Description
Definition at line 2 of file DiffTool.c.
Member Function Documentation
Configure()
override void SVNDiffPlugin::Configure () inline private
Definition at line 25 of file DiffTool.c.
  {
    Workbench.ScriptDialog("Configure SVN Diff", "Usage: \n$path - will be replaced with file name", this);
  }
References Workbench::ScriptDialog().
OkButton()
void SVNDiffPlugin::OkButton () inline private
Definition at line 31 of file DiffTool.c.
{}
Run()
override void SVNDiffPlugin::Run () inline private
Definition at line 7 of file DiffTool.c.
  {
    ScriptEditor mod = Workbench.GetModule("ScriptEditor");
    if (mod)
    {
      string file;
      string absPath;
      if (mod.GetCurrentFile(file) && Workbench.GetAbsolutePath(file, absPath))
      {
        string command = CommandLine;
        command.Replace("$path", absPath);
        Workbench.RunCmd(command);
        Print(command);
        Print(absPath);
      }
    }
  }
References Workbench::GetAbsolutePath(), Workbench::GetModule(), Print(), and Workbench::RunCmd().
Member Data Documentation
CommandLine
string SVNDiffPlugin::CommandLine private
Definition at line 5 of file DiffTool.c.
The documentation for this class was generated from the following file:
scripts/editor/Workbench/DiffTool.c