DayZ: DayZPlayerTypeStepSoundLookupTable Class Reference
DayZPlayerTypeStepSoundLookupTable Class Reference
Private Member Functions
SoundObjectBuilder GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots)
void DayZPlayerTypeStepSoundLookupTableImpl ()
override SoundObjectBuilder GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots)
Static Private Member Functions
static DayZPlayerTypeStepSoundLookupTableImpl GetInstance ()
Private Attributes
autoptr map< int, ref StepSoundLookupTable > m_pSoundTableInstances
autoptr map< int, StepSoundLookupTable > m_pSoundTables
Static Private Attributes
static ref DayZPlayerTypeStepSoundLookupTableImpl m_instance
Detailed Description
Definition at line 146 of file dayzplayer.c.
Member Function Documentation
DayZPlayerTypeStepSoundLookupTableImpl()
void DayZPlayerTypeStepSoundLookupTable::DayZPlayerTypeStepSoundLookupTableImpl () inline private
Definition at line 3 of file DayZPlayerCfgSounds.c.
  {
    m_pSoundTableInstances = new map<int, ref StepSoundLookupTable>;
    m_pSoundTables = new map<int, StepSoundLookupTable>;
    string stepsCfgPath = "CfgVehicles SurvivorBase AnimEvents Steps ";
    int stepsCount = GetGame().ConfigGetChildrenCount(stepsCfgPath);
    for (int i = 0; i < stepsCount; i++)
    {
      string stepName;
      GetGame().ConfigGetChildName(stepsCfgPath, i, stepName);
      string stepPath = stepsCfgPath + stepName + " ";
      int id = GetGame().ConfigGetInt(stepPath + "id");
      string tableName;
      GetGame().ConfigGetText(stepPath + "soundLookupTable", tableName);
      StepSoundLookupTable table = m_pSoundTableInstances.Get(tableName.Hash());
      if (table == NULL)
      {
        table = new StepSoundLookupTable();
        table.LoadTable(tableName);
        m_pSoundTableInstances.Insert(tableName.Hash(), table);
      }
      m_pSoundTables.Insert(id, table);
    }
  }
References GetGame(), m_pSoundTableInstances, m_pSoundTables, and StepSoundLookupTable().
Referenced by GetInstance().
GetInstance()
static DayZPlayerTypeStepSoundLookupTableImpl DayZPlayerTypeStepSoundLookupTable::GetInstance () inline static private
Definition at line 89 of file DayZPlayerCfgSounds.c.
  {
    if (m_instance == NULL)
      m_instance = new DayZPlayerTypeStepSoundLookupTableImpl();
    return m_instance;
  }
References DayZPlayerTypeStepSoundLookupTableImpl(), m_instance, and m_instance.
GetSoundBuilder() [1/2]
SoundObjectBuilder DayZPlayerTypeStepSoundLookupTable::GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots) inline private
Definition at line 148 of file dayzplayer.c.
  {
    return null;
  }
GetSoundBuilder() [2/2]
override SoundObjectBuilder DayZPlayerTypeStepSoundLookupTable::GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots) inline private
Definition at line 32 of file DayZPlayerCfgSounds.c.
  {
    SoundLookupTable table = m_pSoundTables.Get(eventId);
    if (table == NULL)
      return NULL;
    SoundObjectBuilder soundBuilder = table.GetSoundBuilder(pSurfaceHash);
    if (soundBuilder == NULL)
      return NULL;
    if (pMovement == DayZPlayerConstants.MOVEMENTIDX_WALK)
    {
      soundBuilder.AddVariable("walk", 1);
      soundBuilder.AddVariable("run", 0);
      soundBuilder.AddVariable("sprint", 0);
    }
    else if (pMovement == DayZPlayerConstants.MOVEMENTIDX_RUN)
    {
      soundBuilder.AddVariable("walk", 0);
      soundBuilder.AddVariable("run", 1);
      soundBuilder.AddVariable("sprint", 0);
    }
    else if (pMovement == DayZPlayerConstants.MOVEMENTIDX_SPRINT)
    {
      soundBuilder.AddVariable("walk", 0);
      soundBuilder.AddVariable("run", 0);
      soundBuilder.AddVariable("sprint", 1);
    }
    else
    {
      soundBuilder.AddVariable("walk", 0);
      soundBuilder.AddVariable("run", 0);
      soundBuilder.AddVariable("sprint", 0);
    }
    if (pBoots == AnimBootsType.None)
    {
      soundBuilder.AddVariable("bare", 1);
      soundBuilder.AddVariable("sneakers", 0);
      soundBuilder.AddVariable("boots", 0);
    }
    else if (pBoots == AnimBootsType.Sneakers)
    {
      soundBuilder.AddVariable("bare", 0);
      soundBuilder.AddVariable("sneakers", 1);
      soundBuilder.AddVariable("boots", 0);
    }
    else if (pBoots == AnimBootsType.Boots)
    {
      soundBuilder.AddVariable("bare", 0);
      soundBuilder.AddVariable("sneakers", 0);
      soundBuilder.AddVariable("boots", 1);
    }
    return soundBuilder;
  }
References m_pSoundTables.
Member Data Documentation
m_instance
ref DayZPlayerTypeStepSoundLookupTableImpl DayZPlayerTypeStepSoundLookupTable::m_instance static private
Definition at line 97 of file DayZPlayerCfgSounds.c.
Referenced by GetInstance().
m_pSoundTableInstances
autoptr map<int, ref StepSoundLookupTable> DayZPlayerTypeStepSoundLookupTable::m_pSoundTableInstances private
Definition at line 98 of file DayZPlayerCfgSounds.c.
m_pSoundTables
autoptr map<int, StepSoundLookupTable> DayZPlayerTypeStepSoundLookupTable::m_pSoundTables private
Definition at line 99 of file DayZPlayerCfgSounds.c.
The documentation for this class was generated from the following files:
scripts/3_Game/dayzplayer.c
scripts/4_World/Entities/ManBase/DayZPlayer/DayZPlayerCfgSounds.c