DayZ: DropEquipAndDestroyRootLambda Class Reference
DropEquipAndDestroyRootLambda Class Reference
this one is a bit special: it drops all items and destroys the ex-root of the hierarchy
Private Member Functions
void DropEquipAndDestroyRootLambda (EntityAI old_item, string new_item_type, PlayerBase player)
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
Private Member Functions inherited from ReplaceItemWithNewLambdaBase
bool WantCreateNewEntity ()
bool CanExecuteLambda ()
bool PrepareLocations ()
Step A. - prepare inventory locations.
void RemoveOldItemFromLocation ()
Step B. - free location for new item @NOTE this operation does not delete the object, only removes it from inventory location.
void UndoRemoveOldItemFromLocation ()
void RemoveNetworkObjectInfo ()
Step C. - remove network part of the object @NOTE this operation does not delete the object, only removes its network part (and deletes it on client)
void UndoRemoveNetworkObjectInfo ()
EntityAI CreateNewEntity ()
Step D. - create new entity (LOCAL) with specified type.
void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
Step E. copy properties from old object to the created one.
void DeleteOldEntity ()
Step F. - deletes physically old item.
void CreateNetworkObjectInfo (EntityAI new_item)
Step G. - create NetworkObjectInfo for new item.
void OnSuccess (EntityAI new_item)
Step H. - notification on finish.
void OnAbort ()
Step Out - notification on abort.
void Execute (HumanInventoryWithFSM fsm_to_notify=null)
string DumpToString ()
Private Attributes
PlayerBase m_Player
Private Attributes inherited from ReplaceItemWithNewLambdaBase
ref InventoryLocation m_OldLocation
ref InventoryLocation m_NewLocation
bool m_RemoveFromLocationPassed = false
Detailed Description
this one is a bit special: it drops all items and destroys the ex-root of the hierarchy
Definition at line 105 of file MiscGameplayFunctions.c.
Constructor & Destructor Documentation
DropEquipAndDestroyRootLambda()
void DropEquipAndDestroyRootLambda::DropEquipAndDestroyRootLambda (EntityAI old_item, string new_item_type, PlayerBase player) inline private
Definition at line 109 of file MiscGameplayFunctions.c.
  {
    m_Player = player;
  }
References m_Player.
Member Function Documentation
CopyOldPropertiesToNew()
override void DropEquipAndDestroyRootLambda::CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item) inline private
We don't care if a valid transform couldn't be found, we just want to preferably use it instead of placing on the old item
Definition at line 114 of file MiscGameplayFunctions.c.
  {
    super.CopyOldPropertiesToNew(old_item, new_item);
    InventoryLocation understash_src = m_NewLocation; // m_NewLocation is a backup of original old_item's src before the operation started
    array<EntityAI> children = new array<EntityAI>;
    old_item.GetInventory().EnumerateInventory(InventoryTraversalType.LEVELORDER, children);
    int count = children.Count();
    for (int i = 0; i < count; i++)
    {
      EntityAI child = children.Get(i);
      if (child)
      {
        InventoryLocation child_src = new InventoryLocation;
        child.GetInventory().GetCurrentInventoryLocation(child_src);
        InventoryLocation child_dst = new InventoryLocation;
        //@TODO: modify _dst with place on gnd?
        vector m4[4];
        Math3D.MatrixIdentity4(m4);
        GameInventory.PrepareDropEntityPos(old_item, child, m4, false, -1);
        child_dst.SetGround(child, m4);
        m_Player.LocalTakeToDst(child_src, child_dst);
        GetGame().RemoteObjectTreeCreate(child); // this forces server to send CreateVehicle Message to client. This is needed for preserving the appearance of network operations on client (so that DeleteObject(old) arrives before CreateVehicle(new)). @NOTE: this does not delete the object on server, only it's network representation.
      }
    }
  }
References GetGame(), ReplaceItemWithNewLambdaBase::m_NewLocation, m_Player, Math3D::MatrixIdentity4(), and GameInventory::PrepareDropEntityPos().
Member Data Documentation
m_Player
PlayerBase DropEquipAndDestroyRootLambda::m_Player private
Definition at line 107 of file MiscGameplayFunctions.c.
Referenced by CopyOldPropertiesToNew(), and DropEquipAndDestroyRootLambda().
The documentation for this class was generated from the following file:
scripts/4_World/Static/MiscGameplayFunctions.c