DayZ: CAContinuousQuantityBloodTransfer Class Reference
CAContinuousQuantityBloodTransfer Class Reference
Private Member Functions
override void CalcAndSetQuantity (ActionData action_data)
Private Member Functions inherited from CAContinuousQuantityRepeat
void CAContinuousQuantityRepeat (float quantity_used_per_second, float time_to_repeat)
override void Setup (ActionData action_data)
override int Execute (ActionData action_data)
override int Cancel (ActionData action_data)
override float GetProgress ()
void CalcAndSetQuantity (ActionData action_data)
Additional Inherited Members
Private Attributes inherited from CAContinuousQuantityRepeat
float m_ItemQuantity
float m_SpentQuantity
float m_ItemMaxQuantity
float m_TimeElpased
float m_QuantityUsedPerSecond
float m_AdjustedQuantityUsedPerSecond
float m_DefaultTimeToRepeat
ref Param1< float > m_SpentUnits
Detailed Description
Definition at line 1 of file CAContinuousQuantityBloodTransfer.c.
Member Function Documentation
CalcAndSetQuantity()
override void CAContinuousQuantityBloodTransfer::CalcAndSetQuantity (ActionData action_data) inline private
Definition at line 3 of file CAContinuousQuantityBloodTransfer.c.
  {
    if (GetGame().IsServer())
    {
      if (m_SpentUnits)
      {
        m_SpentUnits.param1 = m_SpentQuantity;
        SetACData(m_SpentUnits);
      }
      action_data.m_MainItem.AddQuantity(-m_SpentQuantity, false, false);
      ActionGiveBloodData action_data_b = ActionGiveBloodData.Cast(action_data);
      PlayerBase bloodtarget = PlayerBase.Cast(action_data.m_Target.GetObject());
      if (!bloodtarget)
        bloodtarget = action_data.m_Player;
      if (BloodTypes.MatchBloodCompatibility(action_data_b.m_ItemBloodType, bloodtarget.GetStatBloodType().Get()))
        bloodtarget.AddHealth("", "Blood", m_SpentQuantity);
    }
  }
References GetGame(), CAContinuousQuantityRepeat::m_SpentQuantity, CAContinuousQuantityRepeat::m_SpentUnits, BloodTypes::MatchBloodCompatibility(), and CABase::SetACData().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousQuantityBloodTransfer.c