DayZ: PPERequester_GameplayBase Class Reference
PPERequester_GameplayBase Class Reference
base, not to be used directly, would lead to layering collisions!
Protected Member Functions
void OnStart (Param par=null)
void OnStop (Param par=null)
void OnStop (Param par=null)
void SetNVMode (int mode)
void OnStart (Param par=null)
void OnStop (Param par=null)
void SetUndergroundExposureCoef (float coef)
void OnStart (Param par=null)
void OnUpdate (float delta)
override void OnStop (Param par=null)
float FadeColourMult (float x, float y, float deltaT)
void OnStart (Param par=null)
void OnStart (Param par=null)
void OnUpdate (float delta)
void SetStamina01 (float stamina01)
void OnStart (Param par=null)
void OnStop (Param par=null)
void OnUpdate (float delta)
void SetFlashbangIntensity (float intensity, float daytime_toggle)
void OnStart (Param par=null)
void OnStart (Param par=null)
void OnStart (Param par=null)
void OnStart (Param par=null)
void OnStart (Param par=null)
void OnStart (Param par=null)
void OnStart (Param par=null)
void OnUpdate (float delta)
override void OnStop (Param par=null)
float FadeColourMult (float x, float y, float deltaT)
void OnStart (Param par=null)
void OnStart (Param par=null)
Protected Attributes
int m_CurrentMode
float m_UGExposureCoef = 1.0
vector m_StartRGB = vector.Zero
float m_AccumulatedTime = 0
bool m_FadeIn = false
bool m_FadeOut = false
const float FADE_TIME = 3
const float R_TARGET = 0.142
const float G_TARGET = 0.15
const float B_TARGET = 0.44
float m_Value
float m_Exposure
float m_Intensity
float m_Gauss
float m_VignetteIntensity
float m_OverlayFactor
ref array< float > m_OverlayColor
Private Member Functions
void SetBloodLossLevel (float level)
void SetValuesOptics (out array< float > mask_array, out array< float > lens_array, float gauss=0.0)
void SetValuesIronsights (out array< float > DOF_array)
void SetFeverIntensity (float intensity)
void SetHitIntensity (float intensity)
void SetRadialBlur (float power_x, float power_y, float offset_x, float offset_y, float pixel_scale=0.5)
void SetEyeAccommodation (float value)
Private Attributes
float m_EffectPhase = 0
float m_Magnitude = 0
float m_MinMagnitude = 0.3
float m_MaxMagnitude = 0.3
float m_Frequency = 5
float m_Stamina01
const float VAL_FACTOR = 0.85
const float EXPOSURE_MAX = 50
const float INTENSITY_MULT = 6.0
Static Private Attributes
static const int NV_NO_BATTERY = 0
static const int NV_DEFAULT_OPTICS = 1
static const int NV_DEFAULT_GLASSES = 2
static const int NV_PUMPKIN = 3
static const int NV_TRANSITIVE = 4
static const int NV_DAYTIME_OPTICS = 5
Detailed Description
base, not to be used directly, would lead to layering collisions!
Definition at line 1 of file PPERBloodLoss.c.
Member Function Documentation
FadeColourMult() [1/2]
float PPERequester_GameplayBase::FadeColourMult (float x, float y, float deltaT) inline protected
Definition at line 77 of file PPERContaminated.c.
  {
    float output;
    output = Math.Lerp(x, y, deltaT);
    Easing.EaseInOutSine(output);
    return output;
  }
References Easing::EaseInOutSine(), Math::Lerp(), x, and y.
FadeColourMult() [2/2]
float PPERequester_GameplayBase::FadeColourMult (float x, float y, float deltaT) inline protected
Definition at line 77 of file PPERSpooky.c.
  {
    float output;
    output = Math.Lerp(x, y, deltaT);
    Easing.EaseInOutSine(output);
    return output;
  }
References Easing::EaseInOutSine(), Math::Lerp(), x, and y.
OnStart() [1/15]
void PPERequester_GameplayBase::OnStart (Param par = null) inline protected
Definition at line 3 of file PPERBurlapSack.c.
  {
    super.OnStart();
    SetTargetValueFloat(PPEExceptions.EXPOSURE, PPEExposureNative.PARAM_INTENSITY, false, -100.0, PPEExposureNative.L_0_BURLAP, PPOperators.SET);
    SetTargetValueFloat(PPEExceptions.EYEACCOM, PPEEyeAccomodationNative.PARAM_INTENSITY, false, 0.0, PPEEyeAccomodationNative.L_0_BURLAP, PPOperators.SET);
    SetTargetValueFloat(PostProcessEffectType.Glow, PPEGlow.PARAM_VIGNETTE, false, 2.0, PPEGlow.L_25_BURLAP, PPOperators.SET);
    SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_VIGNETTECOLOR, {0.0, 0.0, 0.0, 0.0}, PPEGlow.L_26_BURLAP, PPOperators.LOWEST);
    if (GetGame() && GetGame().GetMission() && GetGame().GetMission().GetEffectWidgets())
    {
      GetGame().GetMission().GetEffectWidgets().AddSuspendRequest(EffectWidgetSuspends.BURLAPSACK);//these should probably be elsewhere, PPEs are mission independent
    }
  }
References GetGame(), PPEExposureNative::L_0_BURLAP, PPEEyeAccomodationNative::L_0_BURLAP, PPEGlow::L_25_BURLAP, PPEGlow::L_26_BURLAP, PPEExposureNative::PARAM_INTENSITY, PPEEyeAccomodationNative::PARAM_INTENSITY, PPEGlow::PARAM_VIGNETTE, PPEGlow::PARAM_VIGNETTECOLOR, SetTargetValueColor(), and SetTargetValueFloat().
OnStart() [2/15]
void PPERequester_GameplayBase::OnStart (Param par = null) inline protected
Definition at line 73 of file PPERCameraNV.c.
  {
    super.OnStart();
    SetNVMode(Param1<int>.Cast(par).param1);
  }
OnStart() [3/15]
void PPERequester_GameplayBase::OnStart (Param par = null) inline protected
Definition at line 15 of file PPERContaminated.c.
  {
    super.OnStart(par);
    m_AccumulatedTime = 0;
    m_FadeIn = true;
    m_FadeOut = false;
    SetTargetValueFloat(PostProcessEffectType.FilmGrain, PPEFilmGrain.PARAM_SHARPNESS, false, 10.0, PPEFilmGrain.L_1_TOXIC_TINT, PPOperators.HIGHEST);
    SetTargetValueFloat(PostProcessEffectType.FilmGrain, PPEFilmGrain.PARAM_GRAINSIZE, false, 1.0, PPEFilmGrain.L_2_TOXIC_TINT, PPOperators.LOWEST);
  }
References PPEFilmGrain::L_1_TOXIC_TINT, PPEFilmGrain::L_2_TOXIC_TINT, PPEFilmGrain::PARAM_GRAINSIZE, PPEFilmGrain::PARAM_SHARPNESS, and SetTargetValueFloat().
OnStart() [4/15]
void PPERequester_GameplayBase::OnStart (Param par = null) inline protected
Definition at line 5 of file PPERDeathDarkening.c.
  {
    super.OnStart();
    m_Value = Param1<float>.Cast(par).param1;
    //Print("PPERequester_DeathDarkening | level: " + m_Value);
    m_Value = Easing.EaseInCubic(m_Value);
    m_Value = Math.Lerp(0, -10, m_Value);
    //Print("PPERequester_DeathDarkening | value: " + value);
    SetTargetValueFloat(PPEExceptions.EXPOSURE, PPEExposureNative.PARAM_INTENSITY, false, m_Value, PPEExposureNative.L_0_DEATH, PPOperators.SET);
  }
References Easing::EaseInCubic(), PPEExposureNative::L_0_DEATH, Math::Lerp(), m_Value, PPEExposureNative::PARAM_INTENSITY, and SetTargetValueFloat().
OnStart() [5/15]
void PPERequester_GameplayBase::OnStart (Param par = null) inline protected
Definition at line 10 of file PPERDrowningEffect.c.
  {
    super.OnStart(par);
    m_EffectPhase = 0;
    m_Magnitude = 0;
  }
OnStart() [6/15]
void PPERequester_GameplayBase::OnStart (Param par = null) inline protected
Definition at line 8 of file PPERFlashbangEffects.c.
  {
    if (!m_IsRunning)
    {
      if (GetGame().GetMission() && GetGame().GetMission().GetEffectWidgets())
        GetGame().GetMission().GetEffectWidgets().AddActiveEffects({EffectWidgetsTypes.COVER_FLASHBANG});
    }
    super.OnStart();
  }
References GetGame(), and m_IsRunning.
OnStart() [7/15]
void PPERequester_GameplayBase::OnStart (Param par = null) inline protected
Definition at line 5 of file PPERGlasses.c.
  {
    super.OnStart();
    SetTargetValueFloat(PostProcessEffectType.GodRays, PPEGodRays.PARAM_INTENSITY, true, 0, PPEGodRays.L_0_GLASSES, PPOperators.LOWEST);
    SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_COLORIZATIONCOLOR, {0.4, 0.4, 0.4, 0.0}, PPEGlow.L_23_GLASSES, PPOperators.SUBSTRACT);
  }
References PPEGodRays::L_0_GLASSES, PPEGlow::L_23_GLASSES, PPEGlow::PARAM_COLORIZATIONCOLOR, PPEGodRays::PARAM_INTENSITY, SetTargetValueColor(), and SetTargetValueFloat().
OnStart() [8/15]
void PPERequester_GameplayBase::OnStart (Param par = null) inline protected
Definition at line 31 of file PPERGlasses.c.
  {
    super.OnStart();
    SetTargetValueFloat(PostProcessEffectType.GodRays, PPEGodRays.PARAM_INTENSITY, true, 0, PPEGodRays.L_0_GLASSES, PPOperators.LOWEST);
    SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_COLORIZATIONCOLOR, {0.2, 0.0, 0.2, 0.0}, PPEGlow.L_23_GLASSES, PPOperators.SUBSTRACT);
  }
References PPEGodRays::L_0_GLASSES, PPEGlow::L_23_GLASSES, PPEGlow::PARAM_COLORIZATIONCOLOR, PPEGodRays::PARAM_INTENSITY, SetTargetValueColor(), and SetTargetValueFloat().
OnStart() [9/15]
void PPERequester_GameplayBase::OnStart (Param par = null) inline protected
Definition at line 53 of file PPERGlasses.c.
  {
    super.OnStart();
    SetTargetValueFloat(PostProcessEffectType.GodRays, PPEGodRays.PARAM_INTENSITY, true, 0, PPEGodRays.L_0_GLASSES, PPOperators.LOWEST);
    SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_COLORIZATIONCOLOR, {0.3, 0.3, 0.1, 0.0}, PPEGlow.L_23_GLASSES, PPOperators.SUBSTRACT);
  }
References PPEGodRays::L_0_GLASSES, PPEGlow::L_23_GLASSES, PPEGlow::PARAM_COLORIZATIONCOLOR, PPEGodRays::PARAM_INTENSITY, SetTargetValueColor(), and SetTargetValueFloat().
OnStart() [10/15]
void PPERequester_GameplayBase::OnStart (Param par = null) inline protected
Definition at line 74 of file PPERGlasses.c.
  {
    super.OnStart();
    SetTargetValueFloat(PostProcessEffectType.GodRays, PPEGodRays.PARAM_INTENSITY, true, 0, PPEGodRays.L_0_GLASSES, PPOperators.LOWEST);
    SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_COLORIZATIONCOLOR, {0.7, 0.7, 0.7, 0.0}, PPEGlow.L_23_GLASSES, PPOperators.SUBSTRACT);
  }
References PPEGodRays::L_0_GLASSES, PPEGlow::L_23_GLASSES, PPEGlow::PARAM_COLORIZATIONCOLOR, PPEGodRays::PARAM_INTENSITY, SetTargetValueColor(), and SetTargetValueFloat().
OnStart() [11/15]
void PPERequester_GameplayBase::OnStart (Param par = null) inline protected
Definition at line 3 of file PPERInventoryBlur.c.
  {
    super.OnStart();
    SetTargetValueFloat(PostProcessEffectType.GaussFilter, PPEGaussFilter.PARAM_INTENSITY, false, 0.5, PPEGaussFilter.L_0_INV, PPOperators.SET); //PPOperators.OVERRIDE?
  }
References PPEGaussFilter::L_0_INV, PPEGaussFilter::PARAM_INTENSITY, and SetTargetValueFloat().
OnStart() [12/15]
void PPERequester_GameplayBase::OnStart (Param par = null) inline protected
Definition at line 8 of file PPERShockHit.c.
  {
    super.OnStart();
    m_Gauss = Param3<float, float, float>.Cast(par).param1;
    m_VignetteIntensity = Param3<float, float, float>.Cast(par).param2;
    m_OverlayFactor = Param3<float, float, float>.Cast(par).param3;
    m_OverlayColor = {0.0, 0.0, 0.0, 1.0};
    if (m_OverlayFactor > 0.0)
      m_OverlayColor = {0.1, 0.1, 0.1, 1.0};
    //blur
    SetTargetValueFloat(PostProcessEffectType.GaussFilter, PPEGaussFilter.PARAM_INTENSITY, true, m_Gauss, PPEGaussFilter.L_0_SHOCK, PPOperators.ADD_RELATIVE);
    //vignette
    SetTargetValueFloat(PostProcessEffectType.Glow, PPEGlow.PARAM_VIGNETTE, false, m_VignetteIntensity, PPEGlow.L_25_SHOCK, PPOperators.ADD);
    //SetTargetValueColor(PostProcessEffectType.Glow,PPEGlow.PARAM_VIGNETTECOLOR,{0.25,0.25,0.25,0.0},PPEGlow.L_26_SHOCK,PPOperators.ADD_RELATIVE);
    //color overlay
    SetTargetValueFloat(PostProcessEffectType.Glow, PPEGlow.PARAM_OVERLAYFACTOR, true, m_OverlayFactor, PPEGlow.L_20_SHOCK, PPOperators.HIGHEST);
    SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_OVERLAYCOLOR, m_OverlayColor, PPEGlow.L_21_SHOCK, PPOperators.SET);
  }
References PPEGaussFilter::L_0_SHOCK, PPEGlow::L_20_SHOCK, PPEGlow::L_21_SHOCK, PPEGlow::L_25_SHOCK, PPEGaussFilter::PARAM_INTENSITY, PPEGlow::PARAM_OVERLAYCOLOR, PPEGlow::PARAM_OVERLAYFACTOR, PPEGlow::PARAM_VIGNETTE, SetTargetValueColor(), and SetTargetValueFloat().
OnStart() [13/15]
void PPERequester_GameplayBase::OnStart (Param par = null) inline protected
Definition at line 15 of file PPERSpooky.c.
  {
    super.OnStart(par);
    m_AccumulatedTime = 0;
    m_FadeIn = true;
    m_FadeOut = false;
    SetTargetValueFloat(PostProcessEffectType.FilmGrain, PPEFilmGrain.PARAM_SHARPNESS, false, 10.0, PPEFilmGrain.L_1_TOXIC_TINT, PPOperators.HIGHEST);
    SetTargetValueFloat(PostProcessEffectType.FilmGrain, PPEFilmGrain.PARAM_GRAINSIZE, false, 1.0, PPEFilmGrain.L_2_TOXIC_TINT, PPOperators.LOWEST);
  }
References PPEFilmGrain::L_1_TOXIC_TINT, PPEFilmGrain::L_2_TOXIC_TINT, PPEFilmGrain::PARAM_GRAINSIZE, PPEFilmGrain::PARAM_SHARPNESS, and SetTargetValueFloat().
OnStart() [14/15]
void PPERequester_GameplayBase::OnStart (Param par = null) inline protected
Definition at line 5 of file PPERTunnel.c.
  {
    super.OnStart();
    m_Intensity = Param1<float>.Cast(par).param1;
    SetTargetValueFloat(PostProcessEffectType.Glow, PPEGlow.PARAM_VIGNETTE, false, m_Intensity, PPEGlow.L_25_TUNNEL, PPOperators.HIGHEST);
    SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_VIGNETTECOLOR, {0.0, 0.0, 0.0, 0.0}, PPEGlow.L_26_TUNNEL, PPOperators.LOWEST);
  }
References PPEGlow::L_25_TUNNEL, PPEGlow::L_26_TUNNEL, PPEGlow::PARAM_VIGNETTE, PPEGlow::PARAM_VIGNETTECOLOR, SetTargetValueColor(), and SetTargetValueFloat().
OnStart() [15/15]
void PPERequester_GameplayBase::OnStart (Param par = null) inline protected
Definition at line 5 of file PPERUnconEffects.c.
  {
    super.OnStart();
    m_Intensity = Param1<float>.Cast(par).param1;
    SetTargetValueFloat(PostProcessEffectType.Glow, PPEGlow.PARAM_VIGNETTE, false, m_Intensity, PPEGlow.L_25_UNCON, PPOperators.ADD);
    SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_VIGNETTECOLOR, {0.0, 0.0, 0.0, 0.0}, PPEGlow.L_26_UNCON, PPOperators.LOWEST);
  }
References PPEGlow::L_25_UNCON, PPEGlow::L_26_UNCON, PPEGlow::PARAM_VIGNETTE, PPEGlow::PARAM_VIGNETTECOLOR, SetTargetValueColor(), and SetTargetValueFloat().
OnStop() [1/6]
void PPERequester_GameplayBase::OnStop (Param par = null) inline protected
Definition at line 18 of file PPERBurlapSack.c.
  {
    super.OnStop();
    if (GetGame() && GetGame().GetMission() && GetGame().GetMission().GetEffectWidgets())
    {
      GetGame().GetMission().GetEffectWidgets().RemoveSuspendRequest(EffectWidgetSuspends.BURLAPSACK);//these should probably be elsewhere, PPEs are mission independent
    }
  }
References GetGame().
OnStop() [2/6]
void PPERequester_GameplayBase::OnStop (Param par = null) inline protected
Definition at line 53 of file PPERCameraADS_Opt.c.
  {
    super.OnStop(par);
    if (!GetGame())
      return;
    GetGame().ResetPPMask();
    //material parameter values reset by default on stop
  }
References GetGame().
OnStop() [3/6]
void PPERequester_GameplayBase::OnStop (Param par = null) inline protected
Definition at line 81 of file PPERCameraNV.c.
  {
    super.OnStop(par);
  }
OnStop() [4/6]
override void PPERequester_GameplayBase::OnStop (Param par = null) inline protected
Definition at line 62 of file PPERContaminated.c.
  {
    m_FadeIn = false;
    m_FadeOut = false;
    Param1<bool> p;
    if (par && Class.CastTo(p, par))
      m_FadeOut = p.param1;
    m_AccumulatedTime = 0;
    super.OnStop(par);
  }
References Class::CastTo().
OnStop() [5/6]
void PPERequester_GameplayBase::OnStop (Param par = null) inline protected
Definition at line 19 of file PPERFlashbangEffects.c.
  {
    super.OnStop();
    m_Intensity = 0.0;
    m_Exposure = 0.0;
    if (GetGame().GetMission() && GetGame().GetMission().GetEffectWidgets())
      GetGame().GetMission().GetEffectWidgets().RemoveActiveEffects({EffectWidgetsTypes.COVER_FLASHBANG});
  }
References GetGame().
OnStop() [6/6]
override void PPERequester_GameplayBase::OnStop (Param par = null) inline protected
Definition at line 62 of file PPERSpooky.c.
  {
    m_FadeIn = false;
    m_FadeOut = false;
    Param1<bool> p;
    if (par && Class.CastTo(p, par))
      m_FadeOut = p.param1;
    m_AccumulatedTime = 0;
    super.OnStop(par);
  }
References Class::CastTo().
OnUpdate() [1/4]
void PPERequester_GameplayBase::OnUpdate (float delta) inline protected
Definition at line 28 of file PPERContaminated.c.
  {
    super.OnUpdate(delta);
    if (m_FadeIn && m_AccumulatedTime <= FADE_TIME)
    {
      m_AccumulatedTime += delta;
      m_StartRGB[0] = 1 - FadeColourMult(0, 1, m_AccumulatedTime / FADE_TIME) * R_TARGET;
      m_StartRGB[1] = 1 - FadeColourMult(0, 1, m_AccumulatedTime / FADE_TIME) * G_TARGET;
      m_StartRGB[2] = 1 - FadeColourMult(0, 1, m_AccumulatedTime / FADE_TIME) * B_TARGET;
      SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_COLORIZATIONCOLOR, {m_StartRGB[0], m_StartRGB[1], m_StartRGB[2], 0.0}, PPEGlow.L_23_TOXIC_TINT, PPOperators.MULTIPLICATIVE);
    }
    if (m_FadeOut)
    {
      if (m_AccumulatedTime <= FADE_TIME)
      {
        m_AccumulatedTime += delta;
        m_StartRGB[0] = (1 - R_TARGET) + FadeColourMult(0, R_TARGET, m_AccumulatedTime / FADE_TIME);
        m_StartRGB[1] = (1 - G_TARGET) + FadeColourMult(0, G_TARGET, m_AccumulatedTime / FADE_TIME);
        m_StartRGB[2] = (1 - B_TARGET) + FadeColourMult(0, B_TARGET, m_AccumulatedTime / FADE_TIME);
        SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_COLORIZATIONCOLOR, {m_StartRGB[0], m_StartRGB[1], m_StartRGB[2], 0.0}, PPEGlow.L_23_TOXIC_TINT, PPOperators.MULTIPLICATIVE);
      }
      else
      {
        Stop(); //proper termination after a fadeout
      }
    }
  }
References PPEGlow::L_23_TOXIC_TINT, PPEGlow::PARAM_COLORIZATIONCOLOR, SetTargetValueColor(), and Stop().
OnUpdate() [2/4]
void PPERequester_GameplayBase::OnUpdate (float delta) inline protected
Definition at line 18 of file PPERDrowningEffect.c.
  {
    super.OnUpdate(delta);
    if (!m_IsRunning)
      return;
    m_EffectPhase += delta * m_Frequency / (m_Stamina01 + 1); // Start with lower frequency and increase it as it gets closer to danger
    float currentVal = (Math.Sin(m_EffectPhase) + 1) / 2; // Makes current val oscillate between 0 and 1 (normlization)
    currentVal = Easing.EaseInExpo(currentVal); // Ease it to tweak the effect
    currentVal *= currentVal * m_MaxMagnitude; // Scale the normalized value to make it proportional to the Max Magnitude
    currentVal += m_MinMagnitude;
    m_Magnitude = Math.Lerp(m_Magnitude, currentVal, delta * m_Frequency); // Learp to smooth the changes
    SetTargetValueFloat(PostProcessEffectType.Glow, PPEGlow.PARAM_VIGNETTE, true, m_Magnitude, PPEGodRays.L_0_GLASSES, PPOperators.ADD);
    SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_VIGNETTECOLOR, {0.0, 0.025, 0.04, 0.0}, PPEGlow.L_23_GLASSES, PPOperators.ADD);
  }
References Easing::EaseInExpo(), PPEGodRays::L_0_GLASSES, PPEGlow::L_23_GLASSES, Math::Lerp(), m_IsRunning, PPEGlow::PARAM_VIGNETTE, PPEGlow::PARAM_VIGNETTECOLOR, SetTargetValueColor(), SetTargetValueFloat(), and Math::Sin().
OnUpdate() [3/4]
void PPERequester_GameplayBase::OnUpdate (float delta) inline protected
Definition at line 30 of file PPERFlashbangEffects.c.
  {
    super.OnUpdate(delta);
    if (GetGame() && GetGame().GetMission() && GetGame().GetMission().GetEffectWidgets())
    {
      Param1<float> par = new Param1<float>(1 - m_Intensity);
      GetGame().GetMission().GetEffectWidgets().UpdateWidgets(EffectWidgetsTypes.COVER_FLASHBANG, 0, par, EffectWidgetHandles.FLASHBANG);
    }
  }
References GetGame().
OnUpdate() [4/4]
void PPERequester_GameplayBase::OnUpdate (float delta) inline protected
Definition at line 28 of file PPERSpooky.c.
  {
    super.OnUpdate(delta);
    if (m_FadeIn && m_AccumulatedTime <= FADE_TIME)
    {
      m_AccumulatedTime += delta;
      m_StartRGB[0] = 1 - FadeColourMult(0, 1, m_AccumulatedTime / FADE_TIME) * R_TARGET;
      m_StartRGB[1] = 1 - FadeColourMult(0, 1, m_AccumulatedTime / FADE_TIME) * G_TARGET;
      m_StartRGB[2] = 1 - FadeColourMult(0, 1, m_AccumulatedTime / FADE_TIME) * B_TARGET;
      SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_COLORIZATIONCOLOR, {m_StartRGB[0], m_StartRGB[1], m_StartRGB[2], 0.0}, PPEGlow.L_23_TOXIC_TINT, PPOperators.MULTIPLICATIVE);
    }
    if (m_FadeOut)
    {
      if (m_AccumulatedTime <= FADE_TIME)
      {
        m_AccumulatedTime += delta;
        m_StartRGB[0] = (1 - R_TARGET) + FadeColourMult(0, R_TARGET, m_AccumulatedTime / FADE_TIME);
        m_StartRGB[1] = (1 - G_TARGET) + FadeColourMult(0, G_TARGET, m_AccumulatedTime / FADE_TIME);
        m_StartRGB[2] = (1 - B_TARGET) + FadeColourMult(0, B_TARGET, m_AccumulatedTime / FADE_TIME);
        SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_COLORIZATIONCOLOR, {m_StartRGB[0], m_StartRGB[1], m_StartRGB[2], 0.0}, PPEGlow.L_23_TOXIC_TINT, PPOperators.MULTIPLICATIVE);
      }
      else
      {
        Stop(); //proper termination after a fadeout
      }
    }
  }
References PPEGlow::L_23_TOXIC_TINT, PPEGlow::PARAM_COLORIZATIONCOLOR, SetTargetValueColor(), and Stop().
SetBloodLossLevel()
void PPERequester_GameplayBase::SetBloodLossLevel (float level) inline private
Definition at line 3 of file PPERBloodLoss.c.
  {
    SetTargetValueFloat(PostProcessEffectType.Glow, PPEGlow.PARAM_SATURATION, true, level, PPEGlow.L_22_BLOODLOSS, PPOperators.SET);
  }
References PPEGlow::L_22_BLOODLOSS, PPEGlow::PARAM_SATURATION, and SetTargetValueFloat().
SetEyeAccommodation()
void PPERequester_GameplayBase::SetEyeAccommodation (float value) inline private
Definition at line 3 of file PPERUndergroundAcco.c.
  {
    SetTargetValueFloat(PPEExceptions.EYEACCOM, PPEEyeAccomodationNative.PARAM_INTENSITY, false, value, PPEEyeAccomodationNative.L_0_UNDERGROUND, PPOperators.SET);
  }
References PPEEyeAccomodationNative::L_0_UNDERGROUND, PPEEyeAccomodationNative::PARAM_INTENSITY, and SetTargetValueFloat().
SetFeverIntensity()
void PPERequester_GameplayBase::SetFeverIntensity (float intensity) inline private
Definition at line 3 of file PPERFever.c.
  {
    SetTargetValueFloat(PostProcessEffectType.GaussFilter, PPEGaussFilter.PARAM_INTENSITY, true, intensity, PPEGaussFilter.L_0_FEVER, PPOperators.ADD_RELATIVE);
  }
References PPEGaussFilter::L_0_FEVER, PPEGaussFilter::PARAM_INTENSITY, and SetTargetValueFloat().
SetFlashbangIntensity()
void PPERequester_GameplayBase::SetFlashbangIntensity (float intensity, float daytime_toggle) inline protected
Definition at line 41 of file PPERFlashbangEffects.c.
  {
    m_Intensity = intensity;
    array<float> overlay_color = {1.0, 1.0, 1.0, intensity};
    if (daytime_toggle <= 5.0)
      m_Exposure = Math.Clamp(intensity * daytime_toggle, 0.0, EXPOSURE_MAX);
    else
    {
      m_Exposure = Easing.EaseInQuart(intensity);
      m_Exposure = Math.Clamp(EXPOSURE_MAX * m_Exposure, 0.0, EXPOSURE_MAX);
    }
    overlay_color[3] = intensity;
    //blur
    SetTargetValueFloat(PostProcessEffectType.GaussFilter, PPEGaussFilter.PARAM_INTENSITY, true, intensity, PPEGaussFilter.L_0_FLASHBANG, PPOperators.ADD_RELATIVE);
    //overlay
    SetTargetValueFloat(PostProcessEffectType.Glow, PPEGlow.PARAM_OVERLAYFACTOR, true, intensity, PPEGlow.L_20_FLASHBANG, PPOperators.HIGHEST);
    SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_OVERLAYCOLOR, overlay_color, PPEGlow.L_21_FLASHBANG, PPOperators.SET);
    //exposure
    SetTargetValueFloat(PPEExceptions.EXPOSURE, PPEExposureNative.PARAM_INTENSITY, false, m_Exposure, PPEExposureNative.L_0_FLASHBANG, PPOperators.ADD);
  }
References Math::Clamp(), Easing::EaseInQuart(), PPEExposureNative::L_0_FLASHBANG, PPEGaussFilter::L_0_FLASHBANG, PPEGlow::L_20_FLASHBANG, PPEGlow::L_21_FLASHBANG, PPEExposureNative::PARAM_INTENSITY, PPEGaussFilter::PARAM_INTENSITY, PPEGlow::PARAM_OVERLAYCOLOR, PPEGlow::PARAM_OVERLAYFACTOR, SetTargetValueColor(), and SetTargetValueFloat().
SetHitIntensity()
void PPERequester_GameplayBase::SetHitIntensity (float intensity) inline private
Definition at line 5 of file PPERHealthHit.c.
  {
    //color overlay
    SetTargetValueFloat(PostProcessEffectType.Glow, PPEGlow.PARAM_OVERLAYFACTOR, true, 0.05, PPEGlow.L_20_HIT, PPOperators.HIGHEST);
    SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_OVERLAYCOLOR, {intensity * INTENSITY_MULT, 0.0, 0.0, 1.0}, PPEGlow.L_21_HIT, PPOperators.HIGHEST);
  }
References PPEGlow::L_20_HIT, PPEGlow::L_21_HIT, PPEGlow::PARAM_OVERLAYCOLOR, PPEGlow::PARAM_OVERLAYFACTOR, SetTargetValueColor(), and SetTargetValueFloat().
SetNVMode()
void PPERequester_GameplayBase::SetNVMode (int mode) inline protected
Definition at line 13 of file PPERCameraNV.c.
  {
    SetTargetValueFloat(PPEExceptions.EYEACCOM, PPEEyeAccomodationNative.PARAM_INTENSITY, false, 1.0, PPEEyeAccomodationNative.L_0_NVG_GENERIC, PPOperators.SET);
    switch (mode)
    {
    case NV_NO_BATTERY: //battery off
      SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_COLORIZATIONCOLOR, {0.0, 0.0, 0.0, 0.0}, PPEGlow.L_23_NVG, PPOperators.MULTIPLICATIVE);
      SetTargetValueFloatDefault(PPEExceptions.EXPOSURE, PPEExposureNative.PARAM_INTENSITY);
      SetTargetValueFloatDefault(PostProcessEffectType.FilmGrain, PPEFilmGrain.PARAM_SHARPNESS);
      SetTargetValueFloatDefault(PostProcessEffectType.FilmGrain, PPEFilmGrain.PARAM_GRAINSIZE);
      SetTargetValueFloat(PPEExceptions.NVLIGHTPARAMS, PPELightIntensityParamsNative.PARAM_LIGHT_MULT, false, 1.0, PPELightIntensityParamsNative.L_0_NVG, PPOperators.HIGHEST);
      SetTargetValueFloat(PPEExceptions.NVLIGHTPARAMS, PPELightIntensityParamsNative.PARAM_NOISE_MULT, false, 0.0, PPELightIntensityParamsNative.L_1_NVG, PPOperators.HIGHEST);
      break;
    case NV_DEFAULT_OPTICS: //NV optic on
      SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_COLORIZATIONCOLOR, {0.0, 1.0, 0.0, 0.0}, PPEGlow.L_23_NVG, PPOperators.MULTIPLICATIVE);
      SetTargetValueFloat(PPEExceptions.EXPOSURE, PPEExposureNative.PARAM_INTENSITY, false, 7.0 * m_UGExposureCoef, PPEExposureNative.L_0_NVG_OPTIC, PPOperators.ADD);
      SetTargetValueFloat(PostProcessEffectType.FilmGrain, PPEFilmGrain.PARAM_SHARPNESS, false, 9.0, PPEFilmGrain.L_1_NVG, PPOperators.SET);
      SetTargetValueFloat(PostProcessEffectType.FilmGrain, PPEFilmGrain.PARAM_GRAINSIZE, false, 1.0, PPEFilmGrain.L_2_NVG, PPOperators.SET);
      SetTargetValueFloat(PPEExceptions.NVLIGHTPARAMS, PPELightIntensityParamsNative.PARAM_LIGHT_MULT, false, 3.0, PPELightIntensityParamsNative.L_0_NVG, PPOperators.HIGHEST);
      SetTargetValueFloat(PPEExceptions.NVLIGHTPARAMS, PPELightIntensityParamsNative.PARAM_NOISE_MULT, false, 2.0, PPELightIntensityParamsNative.L_1_NVG, PPOperators.HIGHEST);
      break;
    case NV_DAYTIME_OPTICS: //NV optic in daytime mode
      SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_COLORIZATIONCOLOR, {0.0, 1.0, 0.0, 0.0}, PPEGlow.L_23_NVG, PPOperators.MULTIPLICATIVE);
      SetTargetValueFloat(PPEExceptions.EXPOSURE, PPEExposureNative.PARAM_INTENSITY, false, 2.0 * m_UGExposureCoef, PPEExposureNative.L_0_NVG_OPTIC, PPOperators.ADD);
      SetTargetValueFloat(PostProcessEffectType.FilmGrain, PPEFilmGrain.PARAM_SHARPNESS, false, 9.0, PPEFilmGrain.L_1_NVG, PPOperators.SET);
      SetTargetValueFloat(PostProcessEffectType.FilmGrain, PPEFilmGrain.PARAM_GRAINSIZE, false, 1.0, PPEFilmGrain.L_2_NVG, PPOperators.SET);
      SetTargetValueFloat(PPEExceptions.NVLIGHTPARAMS, PPELightIntensityParamsNative.PARAM_LIGHT_MULT, false, 3.0, PPELightIntensityParamsNative.L_0_NVG, PPOperators.HIGHEST);
      SetTargetValueFloat(PPEExceptions.NVLIGHTPARAMS, PPELightIntensityParamsNative.PARAM_NOISE_MULT, false, 1.0, PPELightIntensityParamsNative.L_1_NVG, PPOperators.HIGHEST);
      break;
    case NV_DEFAULT_GLASSES: //goggles on
      SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_COLORIZATIONCOLOR, {0.0, 1.0, 0.0, 0.0}, PPEGlow.L_23_NVG, PPOperators.MULTIPLICATIVE);
      SetTargetValueFloat(PPEExceptions.EXPOSURE, PPEExposureNative.PARAM_INTENSITY, false, 7.0 * m_UGExposureCoef, PPEExposureNative.L_0_NVG_GOGGLES, PPOperators.ADD);
      SetTargetValueFloat(PostProcessEffectType.FilmGrain, PPEFilmGrain.PARAM_SHARPNESS, false, 10.0, PPEFilmGrain.L_1_NVG, PPOperators.SET);
      SetTargetValueFloat(PostProcessEffectType.FilmGrain, PPEFilmGrain.PARAM_GRAINSIZE, false, 1.0, PPEFilmGrain.L_2_NVG, PPOperators.SET);
      SetTargetValueFloat(PPEExceptions.NVLIGHTPARAMS, PPELightIntensityParamsNative.PARAM_LIGHT_MULT, false, 2.0, PPELightIntensityParamsNative.L_0_NVG, PPOperators.HIGHEST);
      SetTargetValueFloat(PPEExceptions.NVLIGHTPARAMS, PPELightIntensityParamsNative.PARAM_NOISE_MULT, false, 1.0, PPELightIntensityParamsNative.L_1_NVG, PPOperators.HIGHEST);
      break;
    case NV_PUMPKIN: //pumpkin-o-vision
      SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_COLORIZATIONCOLOR, {1.0, 0.2, 0.0, 0.0}, PPEGlow.L_23_NVG, PPOperators.MULTIPLICATIVE);
      SetTargetValueFloat(PPEExceptions.EXPOSURE, PPEExposureNative.PARAM_INTENSITY, false, 5.5 * m_UGExposureCoef, PPEExposureNative.L_0_NVG_GOGGLES, PPOperators.ADD);
      SetTargetValueFloatDefault(PostProcessEffectType.FilmGrain, PPEFilmGrain.PARAM_SHARPNESS);
      SetTargetValueFloatDefault(PostProcessEffectType.FilmGrain, PPEFilmGrain.PARAM_GRAINSIZE);
      SetTargetValueFloat(PPEExceptions.NVLIGHTPARAMS, PPELightIntensityParamsNative.PARAM_LIGHT_MULT, false, 1.0, PPELightIntensityParamsNative.L_0_NVG, PPOperators.HIGHEST);
      SetTargetValueFloat(PPEExceptions.NVLIGHTPARAMS, PPELightIntensityParamsNative.PARAM_NOISE_MULT, false, 0.0, PPELightIntensityParamsNative.L_1_NVG, PPOperators.HIGHEST);
      break;
    case NV_TRANSITIVE: //camera transition
      //SetTargetValueFloat(PPEExceptions.EXPOSURE,PPEExposureNative.PARAM_INTENSITY,false,0,PPEExposureNative.L_0_NVG_OFF,PPOperators.SET);
      SetTargetValueFloatDefault(PPEExceptions.EXPOSURE, PPEExposureNative.PARAM_INTENSITY);
      break;
    }
    m_CurrentMode = mode;
  }
References PPELightIntensityParamsNative::L_0_NVG, PPEEyeAccomodationNative::L_0_NVG_GENERIC, PPEExposureNative::L_0_NVG_GOGGLES, PPEExposureNative::L_0_NVG_OPTIC, PPELightIntensityParamsNative::L_1_NVG, PPEFilmGrain::L_1_NVG, PPEGlow::L_23_NVG, PPEFilmGrain::L_2_NVG, m_CurrentMode, NV_PUMPKIN, PPEGlow::PARAM_COLORIZATIONCOLOR, PPEFilmGrain::PARAM_GRAINSIZE, PPEExposureNative::PARAM_INTENSITY, PPEEyeAccomodationNative::PARAM_INTENSITY, PPELightIntensityParamsNative::PARAM_LIGHT_MULT, PPELightIntensityParamsNative::PARAM_NOISE_MULT, PPEFilmGrain::PARAM_SHARPNESS, SetTargetValueColor(), SetTargetValueFloat(), and SetTargetValueFloatDefault().
SetRadialBlur()
void PPERequester_GameplayBase::SetRadialBlur (float power_x, float power_y, float offset_x, float offset_y, float pixel_scale = 0.5) inline private
Definition at line 3 of file PPERPain.c.
  {
    SetTargetValueFloat(PostProcessEffectType.RadialBlur, PPERadialBlur.PARAM_POWERX, false, power_x, PPERadialBlur.L_0_PAIN_BLUR, PPOperators.SET);
    SetTargetValueFloat(PostProcessEffectType.RadialBlur, PPERadialBlur.PARAM_POWERY, false, power_y, PPERadialBlur.L_0_PAIN_BLUR, PPOperators.SET);
    SetTargetValueFloat(PostProcessEffectType.RadialBlur, PPERadialBlur.PARAM_OFFSETX, false, offset_x, PPERadialBlur.L_0_PAIN_BLUR, PPOperators.SET);
    SetTargetValueFloat(PostProcessEffectType.RadialBlur, PPERadialBlur.PARAM_OFFSETY, false, offset_y, PPERadialBlur.L_0_PAIN_BLUR, PPOperators.SET);
    SetTargetValueFloat(PostProcessEffectType.RadialBlur, PPERadialBlur.PARAM_PIXELSCALE, false, pixel_scale, PPERadialBlur.L_0_PAIN_BLUR, PPOperators.SET);
  }
References PPERadialBlur::L_0_PAIN_BLUR, PPERadialBlur::PARAM_OFFSETX, PPERadialBlur::PARAM_OFFSETY, PPERadialBlur::PARAM_PIXELSCALE, PPERadialBlur::PARAM_POWERX, PPERadialBlur::PARAM_POWERY, and SetTargetValueFloat().
SetStamina01()
void PPERequester_GameplayBase::SetStamina01 (float stamina01) inline protected
Definition at line 37 of file PPERDrowningEffect.c.
  {
    m_Stamina01 = stamina01;
  }
SetUndergroundExposureCoef()
void PPERequester_GameplayBase::SetUndergroundExposureCoef (float coef) inline protected
Definition at line 86 of file PPERCameraNV.c.
  {
    m_UGExposureCoef = coef;
    if (m_IsRunning)
      SetNVMode(m_CurrentMode); //TODO: improve (oof...)
  }
References m_CurrentMode, and m_IsRunning.
SetValuesIronsights()
void PPERequester_GameplayBase::SetValuesIronsights (out array< float > DOF_array) inline private
Definition at line 30 of file PPERCameraADS_Opt.c.
  {
    //mask - no mask
    GetGame().ResetPPMask();
    //lens - no lens
    SetTargetValueFloatDefault(PostProcessEffectType.Glow, PPEGlow.PARAM_LENSDISTORT);
    SetTargetValueFloatDefault(PostProcessEffectType.Glow, PPEGlow.PARAM_MAXCHROMABBERATION);
    SetTargetValueFloatDefault(PostProcessEffectType.Glow, PPEGlow.PARAM_LENSCENTERX);
    SetTargetValueFloatDefault(PostProcessEffectType.Glow, PPEGlow.PARAM_LENSCENTERY);
    //DOF
    SetTargetValueBool(PPEExceptions.DOF, PPEDOF.PARAM_ENABLE, DOF_array[0], PPEDOF.L_0_ADS, PPOperators.SET);
    SetTargetValueFloat(PPEExceptions.DOF, PPEDOF.PARAM_FOCUS_DIST, false, DOF_array[1], PPEDOF.L_1_ADS, PPOperators.SET);
    SetTargetValueFloat(PPEExceptions.DOF, PPEDOF.PARAM_FOCUS_LEN, false, DOF_array[2], PPEDOF.L_2_ADS, PPOperators.SET);
    SetTargetValueFloat(PPEExceptions.DOF, PPEDOF.PARAM_FOCUS_LEN_NEAR, false, DOF_array[3], PPEDOF.L_3_ADS, PPOperators.SET);
    SetTargetValueFloat(PPEExceptions.DOF, PPEDOF.PARAM_BLUR, false, DOF_array[4], PPEDOF.L_4_ADS, PPOperators.SET);
    SetTargetValueFloat(PPEExceptions.DOF, PPEDOF.PARAM_FOCUS_DEPTH_OFFSET, false, DOF_array[5], PPEDOF.L_5_ADS, PPOperators.SET);
    //blur - no gauss blur (DOF bokeh only)
    SetTargetValueFloatDefault(PostProcessEffectType.GaussFilter, PPEGaussFilter.PARAM_INTENSITY);
  }
References GetGame(), PPEDOF::L_0_ADS, PPEDOF::L_1_ADS, PPEDOF::L_2_ADS, PPEDOF::L_3_ADS, PPEDOF::L_4_ADS, PPEDOF::L_5_ADS, PPEDOF::PARAM_BLUR, PPEDOF::PARAM_ENABLE, PPEDOF::PARAM_FOCUS_DEPTH_OFFSET, PPEDOF::PARAM_FOCUS_DIST, PPEDOF::PARAM_FOCUS_LEN, PPEDOF::PARAM_FOCUS_LEN_NEAR, PPEGaussFilter::PARAM_INTENSITY, PPEGlow::PARAM_LENSCENTERX, PPEGlow::PARAM_LENSCENTERY, PPEGlow::PARAM_LENSDISTORT, PPEGlow::PARAM_MAXCHROMABBERATION, SetTargetValueBool(), SetTargetValueFloat(), and SetTargetValueFloatDefault().
SetValuesOptics()
void PPERequester_GameplayBase::SetValuesOptics (out array< float > mask_array, out array< float > lens_array, float gauss = 0.0) inline private
Definition at line 3 of file PPERCameraADS_Opt.c.
  {
    //mask
    GetGame().ResetPPMask();
    if (mask_array.Count() != 4)
    {
      mask_array = {0.0, 0.0, 0.0, 0.0};
    }
    GetGame().AddPPMask(mask_array[0], mask_array[1], mask_array[2], mask_array[3]);
    //lens
    if (lens_array.Count() != 4)
    {
      lens_array = {0.0, 0.0, 0.0, 0.0};
    }
    SetTargetValueFloat(PostProcessEffectType.Glow, PPEGlow.PARAM_LENSDISTORT, false, lens_array[0], PPEGlow.L_27_ADS, PPOperators.SET);
    SetTargetValueFloat(PostProcessEffectType.Glow, PPEGlow.PARAM_MAXCHROMABBERATION, false, lens_array[1], PPEGlow.L_28_ADS, PPOperators.SET);
    SetTargetValueFloat(PostProcessEffectType.Glow, PPEGlow.PARAM_LENSCENTERX, false, lens_array[2], PPEGlow.L_29_ADS, PPOperators.SET);
    SetTargetValueFloat(PostProcessEffectType.Glow, PPEGlow.PARAM_LENSCENTERY, false, lens_array[3], PPEGlow.L_30_ADS, PPOperators.SET);
    //DOF - no DOF in optics
    SetTargetValueBoolDefault(PPEExceptions.DOF, PPEDOF.PARAM_ENABLE);
    //blur
    SetTargetValueFloat(PostProcessEffectType.GaussFilter, PPEGaussFilter.PARAM_INTENSITY, false, gauss, PPEGaussFilter.L_0_ADS, PPOperators.ADD_RELATIVE);
  }
References GetGame(), PPEGaussFilter::L_0_ADS, PPEGlow::L_27_ADS, PPEGlow::L_28_ADS, PPEGlow::L_29_ADS, PPEGlow::L_30_ADS, PPEDOF::PARAM_ENABLE, PPEGaussFilter::PARAM_INTENSITY, PPEGlow::PARAM_LENSCENTERX, PPEGlow::PARAM_LENSCENTERY, PPEGlow::PARAM_LENSDISTORT, PPEGlow::PARAM_MAXCHROMABBERATION, SetTargetValueBoolDefault(), and SetTargetValueFloat().
Member Data Documentation
B_TARGET
const float PPERequester_GameplayBase::B_TARGET = 0.44 protected
Definition at line 13 of file PPERContaminated.c.
EXPOSURE_MAX
const float PPERequester_GameplayBase::EXPOSURE_MAX = 50 private
Definition at line 4 of file PPERFlashbangEffects.c.
FADE_TIME
const float PPERequester_GameplayBase::FADE_TIME = 3 protected
Definition at line 9 of file PPERContaminated.c.
G_TARGET
const float PPERequester_GameplayBase::G_TARGET = 0.15 protected
Definition at line 12 of file PPERContaminated.c.
INTENSITY_MULT
const float PPERequester_GameplayBase::INTENSITY_MULT = 6.0 private
Definition at line 3 of file PPERHealthHit.c.
m_AccumulatedTime
float PPERequester_GameplayBase::m_AccumulatedTime = 0 protected
Definition at line 5 of file PPERContaminated.c.
m_CurrentMode
int PPERequester_GameplayBase::m_CurrentMode protected
Definition at line 10 of file PPERCameraNV.c.
m_EffectPhase
float PPERequester_GameplayBase::m_EffectPhase = 0 private
Definition at line 3 of file PPERDrowningEffect.c.
m_Exposure
float PPERequester_GameplayBase::m_Exposure protected
Definition at line 5 of file PPERFlashbangEffects.c.
m_FadeIn
bool PPERequester_GameplayBase::m_FadeIn = false protected
Definition at line 6 of file PPERContaminated.c.
m_FadeOut
bool PPERequester_GameplayBase::m_FadeOut = false protected
Definition at line 7 of file PPERContaminated.c.
m_Frequency
float PPERequester_GameplayBase::m_Frequency = 5 private
Definition at line 7 of file PPERDrowningEffect.c.
m_Gauss
float PPERequester_GameplayBase::m_Gauss protected
Definition at line 3 of file PPERShockHit.c.
m_Intensity
float PPERequester_GameplayBase::m_Intensity protected
Definition at line 6 of file PPERFlashbangEffects.c.
m_Magnitude
float PPERequester_GameplayBase::m_Magnitude = 0 private
Definition at line 4 of file PPERDrowningEffect.c.
m_MaxMagnitude
float PPERequester_GameplayBase::m_MaxMagnitude = 0.3 private
Definition at line 6 of file PPERDrowningEffect.c.
m_MinMagnitude
float PPERequester_GameplayBase::m_MinMagnitude = 0.3 private
Definition at line 5 of file PPERDrowningEffect.c.
m_OverlayColor
ref array<float> PPERequester_GameplayBase::m_OverlayColor protected
Definition at line 6 of file PPERShockHit.c.
m_OverlayFactor
float PPERequester_GameplayBase::m_OverlayFactor protected
Definition at line 5 of file PPERShockHit.c.
m_Stamina01
float PPERequester_GameplayBase::m_Stamina01 private
Definition at line 8 of file PPERDrowningEffect.c.
m_StartRGB
vector PPERequester_GameplayBase::m_StartRGB = vector.Zero protected
Definition at line 4 of file PPERContaminated.c.
m_UGExposureCoef
float PPERequester_GameplayBase::m_UGExposureCoef = 1.0 protected
Definition at line 11 of file PPERCameraNV.c.
m_Value
float PPERequester_GameplayBase::m_Value protected
Definition at line 3 of file PPERDeathDarkening.c.
m_VignetteIntensity
float PPERequester_GameplayBase::m_VignetteIntensity protected
Definition at line 4 of file PPERShockHit.c.
NV_DAYTIME_OPTICS
const int PPERequester_GameplayBase::NV_DAYTIME_OPTICS = 5 static private
Definition at line 8 of file PPERCameraNV.c.
NV_DEFAULT_GLASSES
const int PPERequester_GameplayBase::NV_DEFAULT_GLASSES = 2 static private
Definition at line 5 of file PPERCameraNV.c.
NV_DEFAULT_OPTICS
const int PPERequester_GameplayBase::NV_DEFAULT_OPTICS = 1 static private
Definition at line 4 of file PPERCameraNV.c.
NV_NO_BATTERY
const int PPERequester_GameplayBase::NV_NO_BATTERY = 0 static private
Definition at line 3 of file PPERCameraNV.c.
NV_PUMPKIN
const int PPERequester_GameplayBase::NV_PUMPKIN = 3 static private
Definition at line 6 of file PPERCameraNV.c.
NV_TRANSITIVE
const int PPERequester_GameplayBase::NV_TRANSITIVE = 4 static private
Definition at line 7 of file PPERCameraNV.c.
R_TARGET
const float PPERequester_GameplayBase::R_TARGET = 0.142 protected
Definition at line 11 of file PPERContaminated.c.
VAL_FACTOR
const float PPERequester_GameplayBase::VAL_FACTOR = 0.85 private
Definition at line 3 of file PPERFlashbangEffects.c.
The documentation for this class was generated from the following files:
scripts/3_Game/PPEManager/Requesters/PPERBloodLoss.c
scripts/3_Game/PPEManager/Requesters/PPERCameraNV.c
scripts/3_Game/PPEManager/Requesters/PPERContaminated.c
scripts/3_Game/PPEManager/Requesters/PPERDeathDarkening.c
scripts/3_Game/PPEManager/Requesters/PPERDrowningEffect.c
scripts/3_Game/PPEManager/Requesters/PPERFlashbangEffects.c
scripts/3_Game/PPEManager/Requesters/PPERHealthHit.c
scripts/3_Game/PPEManager/Requesters/PPERShockHit.c
scripts/3_Game/PPEManager/Requesters/PPERSpooky.c
scripts/3_Game/PPEManager/Requesters/PPERTunnel.c
scripts/3_Game/PPEManager/Requesters/PPERUnconEffects.c
scripts/3_Game/PPEManager/Requesters/PPERBurlapSack.c
scripts/3_Game/PPEManager/Requesters/PPERCameraADS_Opt.c
scripts/3_Game/PPEManager/Requesters/PPERFever.c
scripts/3_Game/PPEManager/Requesters/PPERGlasses.c
scripts/3_Game/PPEManager/Requesters/PPERInventoryBlur.c
scripts/3_Game/PPEManager/Requesters/PPERPain.c
scripts/3_Game/PPEManager/Requesters/PPERUndergroundAcco.c