DayZ: DayZPlayerCameraBase Class Reference
DayZPlayerCameraBase Class Reference
this is main camera class
Protected Member Functions
void DayZPlayerCameraIronsights (DayZPlayer pPlayer, HumanInputController pInput)
void SetupSightEntities ()
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
EntityAI GetCurrentSightEntity ()
bool GetCurrentSightInfo (out vector camPos, out vector camDir)
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
override vector GetBaseAngles ()
override vector GetAdditiveAngles ()
void AdjustCameraParameters (float pDt, inout DayZPlayerCameraResult pOutResult)
float HoldBreathFOVEffect (float pDt)
override void SetCameraPP (bool state, DayZPlayerCamera launchedFrom)
override string GetCameraName ()
override void SetCameraPPDelay (DayZPlayerCamera pPrevCamera)
void UpdateBatteryOptics (EntityAI entity)
Protected Attributes
int m_iBoneIndex = -1
main bone
vector m_OffsetLS
position offset
float m_fUpDownAngle
up down angle in rad
float m_fUpDownAngleAdd
up down angle in rad
float m_fLeftRightAngle
left right angle in rad (in freelook only)
float m_fLeftRightAngleAdd
left right angle in rad (in freelook only)
vector m_CameraOffsetMS
model space offset
vector m_CameraOffsetLS
local space offset
float m_fDistance
distance from start
float m_fShoulderWidth
shoulder camera widths
bool m_bShoulderInLS
true - shoulder is in local space
float m_fRoll
camera roll (deprecated)
float m_fLeanDistance
shift on leaning
float m_fCameraLRShoulder
shoulder offsets
float m_fCameraLRShoulderVel [1]
float m_fPredictCollisionRadius
collision prediction
ref HumanMovementState m_MovementState = new HumanMovementState()
movement state
bool m_isEntering = false
bool m_opticsHasWeaponOverride = false
ref array< float > temp_array
PPERequester_CameraADS m_RequesterADS
float m_velocityYaw [1]
camera dynamics
float m_velocityPitch [1]
float m_dynamicsStrength
float m_dynamicsSmoothTime
vector m_SightMisalignmentModifier
float m_movementTimeAcc
float m_movementAmplitudeX
float m_movementAmplitudeY
float m_movementFrequencyX
float m_movementFrequencyY
float m_fShootFromCamera = 0.0
settings
vector m_OpticsCamPos
vector m_OpticsCamDir
Private Member Functions
void DayZPlayerCamera1stPerson (DayZPlayer pPlayer, HumanInputController pInput)
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
override vector GetBaseAngles ()
override vector GetAdditiveAngles ()
override string GetCameraName ()
void DayZPlayerCamera3rdPerson (DayZPlayer pPlayer, HumanInputController pInput)
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
override vector GetBaseAngles ()
override vector GetAdditiveAngles ()
override string GetCameraName ()
Static Private Attributes
static const float CONST_UD_MIN = -85.0
down limit
static const float CONST_UD_MAX = 85.0
up limit
static const float CONST_LR_MIN = -160.0
down limit
static const float CONST_LR_MAX = 160.0
up limit
static const float CONST_UD_MIN_BACK = -25.0
down limit on back
Detailed Description
this is main camera class
Definition at line 4 of file DayZPlayerCamera1stPerson.c.
Member Function Documentation
AdjustCameraParameters()
void DayZPlayerCameraBase::AdjustCameraParameters (float pDt, inout DayZPlayerCameraResult pOutResult) inline protected
Definition at line 212 of file DayZPlayerCameraIronsights.c.
  {
    pOutResult.m_iDirectBone = m_iBoneIndex;
    pOutResult.m_iDirectBoneMode = 4;
    pOutResult.m_fFovAbsolute = HoldBreathFOVEffect(pDt);
    pOutResult.m_bUpdateWhenBlendOut = false;
    pOutResult.m_fDistance = 0;
    pOutResult.m_fUseHeading = 0;
    pOutResult.m_fInsideCamera = 1.0;
    pOutResult.m_fShootFromCamera = m_fShootFromCamera;
    pOutResult.m_fNearPlane = 0.04; //0.07 default
  }
References HoldBreathFOVEffect(), m_fShootFromCamera, and m_iBoneIndex.
Referenced by OnUpdate().
DayZPlayerCamera1stPerson()
void DayZPlayerCameraBase::DayZPlayerCamera1stPerson (DayZPlayer pPlayer, HumanInputController pInput) inline private
Definition at line 13 of file DayZPlayerCamera1stPerson.c.
  {
    m_iBoneIndex = pPlayer.GetBoneIndexByName("Head");
    if (m_iBoneIndex == -1)
      Print("DayZPlayerCamera1stPerson: main bone not found");
    m_OffsetLS = "0.04 0.04 0"; //x - up, y - forward
  }
References m_iBoneIndex, m_OffsetLS, and Print().
DayZPlayerCamera3rdPerson()
void DayZPlayerCameraBase::DayZPlayerCamera3rdPerson (DayZPlayer pPlayer, HumanInputController pInput) inline private
Definition at line 12 of file DayZPlayerCamera3rdPerson.c.
  {
    if (pInput.Camera3rdIsRightShoulder())
      m_fCameraLRShoulder = 1.0;
    else
      m_fCameraLRShoulder = -1.0;
    m_fCameraLRShoulderVel[0] = 0.0;
    m_CurrentCameraRoll = 0.0;
    m_WeaponSwayModifier = 1;
    m_fLeanDistance = 0.3;
    m_fPredictCollisionRadius = 0.5;
  }
References m_CurrentCameraRoll, m_fCameraLRShoulder, m_fCameraLRShoulderVel, m_fLeanDistance, m_fPredictCollisionRadius, and m_WeaponSwayModifier.
DayZPlayerCameraIronsights()
void DayZPlayerCameraBase::DayZPlayerCameraIronsights (DayZPlayer pPlayer, HumanInputController pInput) inline protected
Definition at line 32 of file DayZPlayerCameraIronsights.c.
  {
    if (!temp_array)
      temp_array = new array<float>;
    m_iBoneIndex = pPlayer.GetBoneIndexByName("RightHand_Dummy");
    if (m_iBoneIndex == -1)
      Print("DayZPlayerCamera1stPerson: main bone not found");
    m_dynamicsStrength = 2;
    m_dynamicsSmoothTime = 0.3;
    SetupSightEntities();
    GetCurrentSightInfo(m_OpticsCamPos, m_OpticsCamDir);
    m_isEntering = true;
    m_WeaponSwayModifier = 0.5;
    m_movementTimeAcc = 0;
    m_movementAmplitudeX = 1;
    m_movementAmplitudeY = 1;
    m_movementFrequencyX = 1;
    m_movementFrequencyY = 2;
    Class.CastTo(m_RequesterADS, PPERequester_CameraADS.Cast(PPERequesterBank.GetRequester(PPERequester_CameraADS)));
    Init();
  }
References Class::CastTo(), GetCurrentSightInfo(), Init(), m_iBoneIndex, m_WeaponSwayModifier, Print(), and SetupSightEntities().
GetAdditiveAngles() [1/3]
override vector DayZPlayerCameraBase::GetAdditiveAngles () inline private
Definition at line 74 of file DayZPlayerCamera1stPerson.c.
  {
    vector a;
    a[0] = m_fUpDownAngleAdd;
    a[1] = m_fLeftRightAngleAdd;
    a[2] = 0;
    return a;
  }
References m_fLeftRightAngleAdd, and m_fUpDownAngleAdd.
GetAdditiveAngles() [2/3]
override vector DayZPlayerCameraBase::GetAdditiveAngles () inline private
Definition at line 104 of file DayZPlayerCamera3rdPerson.c.
  {
    vector a;
    a[0] = m_fUpDownAngleAdd;
    a[1] = m_fLeftRightAngleAdd;
    a[2] = 0;
    return a;
  }
References m_fLeftRightAngleAdd, and m_fUpDownAngleAdd.
GetAdditiveAngles() [3/3]
override vector DayZPlayerCameraBase::GetAdditiveAngles () inline protected
Definition at line 203 of file DayZPlayerCameraIronsights.c.
  {
    vector a;
    a[0] = m_fUpDownAngleAdd;
    a[1] = m_fLeftRightAngleAdd;
    a[2] = 0;
    return a;
  }
References m_fLeftRightAngleAdd, and m_fUpDownAngleAdd.
GetBaseAngles() [1/3]
override vector DayZPlayerCameraBase::GetBaseAngles () inline private
Definition at line 65 of file DayZPlayerCamera1stPerson.c.
  {
    vector a;
    a[0] = m_fUpDownAngle;
    a[1] = m_fLeftRightAngle;
    a[2] = 0;
    return a;
  }
References m_fLeftRightAngle, and m_fUpDownAngle.
GetBaseAngles() [2/3]
override vector DayZPlayerCameraBase::GetBaseAngles () inline private
Definition at line 95 of file DayZPlayerCamera3rdPerson.c.
  {
    vector a;
    a[0] = m_fUpDownAngle;
    a[1] = m_fLeftRightAngle;
    a[2] = 0;
    return a;
  }
References m_fLeftRightAngle, and m_fUpDownAngle.
GetBaseAngles() [3/3]
override vector DayZPlayerCameraBase::GetBaseAngles () inline protected
Definition at line 194 of file DayZPlayerCameraIronsights.c.
  {
    vector a;
    a[0] = m_fUpDownAngle;
    a[1] = m_fLeftRightAngle;
    a[2] = 0;
    return a;
  }
References m_fLeftRightAngle, and m_fUpDownAngle.
GetCameraName() [1/3]
override string DayZPlayerCameraBase::GetCameraName () inline private
Definition at line 83 of file DayZPlayerCamera1stPerson.c.
  {
    return "DayZPlayerCamera1stPerson";
  }
GetCameraName() [2/3]
override string DayZPlayerCameraBase::GetCameraName () inline private
Definition at line 113 of file DayZPlayerCamera3rdPerson.c.
  {
    return "DayZPlayerCamera3rdPerson";
  }
GetCameraName() [3/3]
override string DayZPlayerCameraBase::GetCameraName () inline protected
Definition at line 289 of file DayZPlayerCameraIronsights.c.
  {
    return "DayZPlayerCameraIronsights";
  }
GetCurrentSightEntity()
EntityAI DayZPlayerCameraBase::GetCurrentSightEntity () inline protected
Definition at line 97 of file DayZPlayerCameraIronsights.c.
  {
    if (m_opticsHasWeaponOverride)
      return m_opticsUsed;
    return m_weaponUsed;
  }
References m_opticsUsed, and m_weaponUsed.
Referenced by GetCurrentSightInfo(), and OnUpdate().
GetCurrentSightInfo()
bool DayZPlayerCameraBase::GetCurrentSightInfo (out vector camPos, out vector camDir) inline protected
Definition at line 105 of file DayZPlayerCameraIronsights.c.
  {
    EntityAI e = GetCurrentSightEntity();
    if (e)
    {
      if (e == m_weaponUsed)
      {
        m_weaponUsed.GetCameraPoint(m_weaponUsed.GetCurrentMuzzle(), camPos, camDir);
        return true;
      }
      else if (e == m_opticsUsed)
      {
        m_opticsUsed.UseWeaponIronsightsOverride(m_opticsHasWeaponOverride);
        m_opticsUsed.GetCameraPoint(camPos, camDir);
        return true;
      }
    }
    else
      ErrorEx("No sight entity found in " + this, ErrorExSeverity.INFO);
    return false;
  }
References ErrorEx, ItemOptics::GetCameraPoint(), GetCurrentSightEntity(), m_opticsUsed, m_weaponUsed, and ItemOptics::UseWeaponIronsightsOverride().
Referenced by DayZPlayerCameraIronsights().
HoldBreathFOVEffect()
float DayZPlayerCameraBase::HoldBreathFOVEffect (float pDt) inline protected
Definition at line 228 of file DayZPlayerCameraIronsights.c.
  {
    if (m_pPlayer.IsHoldingBreath())
      m_fFovAbsolute = Math.SmoothCD(m_fFovAbsolute, GameConstants.DZPLAYER_CAMERA_FOV_EYEZOOM, m_fFovAbsVel, 0.1, 1000, pDt);
    else if (m_isEntering) //sets FOV immediatelly to avoid "floating camera" effect
    {
      m_fFovAbsolute = GameConstants.DZPLAYER_CAMERA_FOV_IRONSIGHTS;
      m_isEntering = false;
    }
    else
      m_fFovAbsolute = Math.SmoothCD(m_fFovAbsolute, GameConstants.DZPLAYER_CAMERA_FOV_IRONSIGHTS, m_fFovAbsVel, 0.1, 1000, pDt);
    return m_fFovAbsolute;
  }
References GameConstants::DZPLAYER_CAMERA_FOV_EYEZOOM, GameConstants::DZPLAYER_CAMERA_FOV_IRONSIGHTS, m_fFovAbsolute, m_fFovAbsVel, m_pPlayer, and Math::SmoothCD().
Referenced by AdjustCameraParameters().
OnActivate() [1/3]
override void DayZPlayerCameraBase::OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult) inline private
Definition at line 24 of file DayZPlayerCamera1stPerson.c.
  {
    super.OnActivate(pPrevCamera, pPrevCameraResult);
    if (pPrevCamera)
    {
      vector baseAngles = pPrevCamera.GetBaseAngles();
      m_fUpDownAngle = baseAngles[0];
      m_fLeftRightAngle = baseAngles[1];
      vector addAngles = pPrevCamera.GetAdditiveAngles();
      m_fUpDownAngleAdd = addAngles[0];
      m_fLeftRightAngleAdd = addAngles[1];
    }
  }
References m_fLeftRightAngle, m_fLeftRightAngleAdd, m_fUpDownAngle, and m_fUpDownAngleAdd.
OnActivate() [2/3]
override void DayZPlayerCameraBase::OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult) inline private
Definition at line 28 of file DayZPlayerCamera3rdPerson.c.
  {
    super.OnActivate(pPrevCamera, pPrevCameraResult);
    if (pPrevCamera)
    {
      vector baseAngles = pPrevCamera.GetBaseAngles();
      m_fUpDownAngle = baseAngles[0];
      m_fLeftRightAngle = baseAngles[1];
      vector addAngles = pPrevCamera.GetAdditiveAngles();
      m_fUpDownAngleAdd = addAngles[0];
      m_fLeftRightAngleAdd = addAngles[1];
    }
  }
References m_fLeftRightAngle, m_fLeftRightAngleAdd, m_fUpDownAngle, and m_fUpDownAngleAdd.
OnActivate() [3/3]
override void DayZPlayerCameraBase::OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult) inline protected
Definition at line 81 of file DayZPlayerCameraIronsights.c.
  {
    super.OnActivate(pPrevCamera, pPrevCameraResult);
    if (pPrevCamera)
    {
      vector baseAngles = pPrevCamera.GetBaseAngles();
      m_fUpDownAngle = baseAngles[0];
      m_fLeftRightAngle = baseAngles[1];
      vector addAngles = pPrevCamera.GetAdditiveAngles();
      m_fUpDownAngleAdd = addAngles[0];
      m_fLeftRightAngleAdd = addAngles[1];
    }
  }
References m_fLeftRightAngle, m_fLeftRightAngleAdd, m_fUpDownAngle, and m_fUpDownAngleAdd.
OnUpdate() [1/3]
override void DayZPlayerCameraBase::OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult) inline private
update angles from input
Definition at line 41 of file DayZPlayerCamera1stPerson.c.
  {
    m_CurrentCameraYaw = UpdateLRAngleUnlocked(m_fLeftRightAngle, m_fLeftRightAngleAdd, CONST_LR_MIN, CONST_LR_MAX, pDt);
    m_CurrentCameraPitch = UpdateUDAngleUnlocked(m_fUpDownAngle, m_fUpDownAngleAdd, CONST_UD_MIN, CONST_UD_MAX, pDt);
    Math3D.YawPitchRollMatrix(GetCurrentOrientation(), pOutResult.m_CameraTM);
    pOutResult.m_CameraTM[3] = m_OffsetLS;
    pOutResult.m_iDirectBone = m_iBoneIndex;
    pOutResult.m_iDirectBoneMode = 1;
    pOutResult.m_fUseHeading = 1.0;
    pOutResult.m_fInsideCamera = 1.0;
    pOutResult.m_fNearPlane = 0.04; //0.07 default
    ProcessCameraShake(pDt, m_fLeftRightAngle, m_fUpDownAngleAdd);
    InitCameraOnPlayer();
    StdFovUpdate(pDt, pOutResult);
    UpdateCameraNV(PlayerBase.Cast(m_pPlayer));
  }
References CONST_LR_MAX, CONST_LR_MIN, CONST_UD_MAX, CONST_UD_MIN, GetCurrentOrientation(), InitCameraOnPlayer(), m_CurrentCameraPitch, m_CurrentCameraYaw, m_fLeftRightAngle, m_fLeftRightAngleAdd, m_fUpDownAngle, m_fUpDownAngleAdd, m_iBoneIndex, m_OffsetLS, m_pPlayer, ProcessCameraShake(), StdFovUpdate(), UpdateCameraNV(), UpdateLRAngleUnlocked(), UpdateUDAngleUnlocked(), and Math3D::YawPitchRollMatrix().
OnUpdate() [2/3]
override void DayZPlayerCameraBase::OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult) inline private
update angles from input
base bone pos
apply shoulder dist
store distance
Definition at line 45 of file DayZPlayerCamera3rdPerson.c.
  {
    m_pPlayer.GetMovementState(m_MovementState);
    m_CurrentCameraYaw = UpdateLRAngleUnlocked(m_fLeftRightAngle, m_fLeftRightAngleAdd, CONST_LR_MIN, CONST_LR_MAX, pDt);
    m_CurrentCameraPitch = UpdateUDAngleUnlocked(m_fUpDownAngle, m_fUpDownAngleAdd, CONST_UD_MIN, CONST_UD_MAX, pDt);
    ProcessCameraShake(pDt, m_fLeftRightAngle, m_fUpDownAngleAdd);
    // update l/r offsets and set it as
    if (m_pInput.Camera3rdIsRightShoulder())
      m_fCameraLRShoulder = Math.SmoothCD(m_fCameraLRShoulder, 1.0, m_fCameraLRShoulderVel, 0.14, 1000, pDt);
    else
      m_fCameraLRShoulder = Math.SmoothCD(m_fCameraLRShoulder, -1.0, m_fCameraLRShoulderVel, 0.14, 1000, pDt);
    float shoulderDist = m_fCameraLRShoulder * m_fShoulderWidth + m_MovementState.m_fLeaning * m_fLeanDistance;
    Math3D.YawPitchRollMatrix(GetCurrentOrientation(), pOutResult.m_CameraTM);
    if (m_iBoneIndex != -1)
      pOutResult.m_CameraTM[3] = m_pPlayer.GetBonePositionMS(m_iBoneIndex);
    else
      pOutResult.m_CameraTM[3] = "0 0 0";
    vector msOffset = m_CameraOffsetMS;
    vector lsOffset = m_CameraOffsetLS;
    if (m_bShoulderInLS)
      lsOffset[0] = lsOffset[0] + shoulderDist;
    else
      msOffset[0] = msOffset[0] + shoulderDist;
    // ls offset + ms offset + shoulder width
    pOutResult.m_CameraTM[3] = pOutResult.m_CameraTM[3] + pOutResult.m_CameraTM[0] * lsOffset[0] + pOutResult.m_CameraTM[1] * lsOffset[1] + pOutResult.m_CameraTM[2] * lsOffset[2] + msOffset;
    pOutResult.m_fDistance = m_fDistance;
    pOutResult.m_fUseHeading = 1.0;
    pOutResult.m_fInsideCamera = 0.0;
    pOutResult.m_fPredictCollisionRadius = m_fPredictCollisionRadius;
    InitCameraOnPlayer();
    StdFovUpdate(pDt, pOutResult);
    UpdateCameraNV(PlayerBase.Cast(m_pPlayer));
  }
References HumanInputController::Camera3rdIsRightShoulder(), CONST_LR_MAX, CONST_LR_MIN, CONST_UD_MAX, CONST_UD_MIN, GetCurrentOrientation(), InitCameraOnPlayer(), m_bShoulderInLS, m_CameraOffsetLS, m_CameraOffsetMS, m_CurrentCameraPitch, m_CurrentCameraYaw, m_fCameraLRShoulder, m_fCameraLRShoulderVel, m_fDistance, m_fLeanDistance, m_fLeftRightAngle, m_fLeftRightAngleAdd, m_fPredictCollisionRadius, m_fShoulderWidth, m_fUpDownAngle, m_fUpDownAngleAdd, m_iBoneIndex, m_MovementState, m_pInput, m_pPlayer, ProcessCameraShake(), Math::SmoothCD(), StdFovUpdate(), UpdateCameraNV(), UpdateLRAngleUnlocked(), UpdateUDAngleUnlocked(), and Math3D::YawPitchRollMatrix().
OnUpdate() [3/3]
override void DayZPlayerCameraBase::OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult) inline protected
update angles from input
Definition at line 128 of file DayZPlayerCameraIronsights.c.
  {
    float min;
    DayZPlayerImplement player = DayZPlayerImplement.Cast(GetGame().GetPlayer());
    if (player && player.IsPlayerInStance(DayZPlayerConstants.STANCEMASK_RAISEDPRONE))
      min = CONST_UD_MIN_BACK;
    else
      min = CONST_UD_MIN;
    m_CurrentCameraYaw = UpdateLRAngleUnlocked(m_fLeftRightAngle, m_fLeftRightAngleAdd, CONST_LR_MIN, CONST_LR_MAX, pDt);
    m_CurrentCameraPitch = UpdateUDAngleUnlocked(m_fUpDownAngle, m_fUpDownAngleAdd, min, CONST_UD_MAX, pDt);
    // get model space transform matrix of the gun's eye vector
    vector matTM[4];
    HumanItemAccessor hia = m_pPlayer.GetItemAccessor();
    if (GetCurrentSightEntity())
      hia.WeaponGetCameraPointBoneRelative(GetCurrentSightEntity(), m_OpticsCamPos, m_OpticsCamDir, m_iBoneIndex, matTM);
    // aim change based on character movement
    vector aimChangeYPR;
    float aimChangeX = m_pInput.GetAimDelta(pDt)[0] * Math.RAD2DEG;
    float aimChangeY = m_pInput.GetAimDelta(pDt)[1] * Math.RAD2DEG;
    HumanCommandMove hcm = m_pPlayer.GetCommand_Move();
    if (hcm)
    {
      float speed = hcm.GetCurrentMovementSpeed();
      if (speed > 0)
        m_movementTimeAcc += pDt;
      else
        m_movementTimeAcc = 0;
      aimChangeX += m_movementAmplitudeX * speed * Math.Sin(Math.PI2 * m_movementFrequencyX * m_movementTimeAcc);
      aimChangeY += m_movementAmplitudeY * speed * Math.Sin(Math.PI2 * m_movementFrequencyY * m_movementTimeAcc);
    }
    aimChangeYPR[0] = Math.SmoothCD(aimChangeYPR[0], -(m_dynamicsStrength * aimChangeY), m_velocityYaw, m_dynamicsSmoothTime, 1000, pDt);
    aimChangeYPR[1] = Math.SmoothCD(aimChangeYPR[1], -(m_dynamicsStrength * aimChangeX), m_velocityPitch, m_dynamicsSmoothTime, 1000, pDt);
    aimChangeYPR[2] = 0;
    vector dynamics[4];
    Math3D.YawPitchRollMatrix(aimChangeYPR, dynamics);
    dynamics[3] = vector.Zero;
    // aiming model offsets
    vector aimingMatTM[4];
    hia.WeaponGetAimingModelDirTm(aimingMatTM);
    // final offset matrix
    Math3D.MatrixMultiply4(dynamics, aimingMatTM, dynamics);
    Math3D.MatrixMultiply4(dynamics, matTM, pOutResult.m_CameraTM);
    AdjustCameraParameters(pDt, pOutResult);
    UpdateBatteryOptics(GetCurrentSightEntity());
    UpdateCameraNV(PlayerBase.Cast(m_pPlayer));
    if (m_CameraShake)
    {
      float x, y;
      m_CameraShake.Update(pDt, x, y);
      DayZPlayerImplement.Cast(m_pPlayer).GetAimingModel().SetCamShakeValues(x, y);
    }
  }
References AdjustCameraParameters(), CONST_LR_MAX, CONST_LR_MIN, CONST_UD_MAX, CONST_UD_MIN, CONST_UD_MIN_BACK, HumanInputController::GetAimDelta(), GetCurrentSightEntity(), GetGame(), GetPlayer(), HumanItemAccessor(), m_CameraShake, m_CurrentCameraPitch, m_CurrentCameraYaw, m_fLeftRightAngle, m_fLeftRightAngleAdd, m_fUpDownAngle, m_fUpDownAngleAdd, m_iBoneIndex, m_pInput, m_pPlayer, Math3D::MatrixMultiply4(), Math::PI2, Math::RAD2DEG, Math::Sin(), Math::SmoothCD(), UpdateBatteryOptics(), UpdateCameraNV(), UpdateLRAngleUnlocked(), UpdateUDAngleUnlocked(), x, y, Math3D::YawPitchRollMatrix(), and vector::Zero.
SetCameraPP()
override void DayZPlayerCameraBase::SetCameraPP (bool state, DayZPlayerCamera launchedFrom) inline protected
Definition at line 244 of file DayZPlayerCameraIronsights.c.
  {
    //Print("SetCameraPP - ADS");
    if (PlayerBase.Cast(m_pPlayer) && launchedFrom.Type() != PlayerBase.Cast(m_pPlayer).GetCurrentPlayerCamera().Type())
    {
      //Print("DayZPlayerCameraIronsights | SetCameraPP | skipping, wrong camera type active!");
      return;
    }
    //if (!state || !m_weaponUsed || (PlayerBase.Cast(m_pPlayer) && launchedFrom != PlayerBase.Cast(m_pPlayer).GetCurrentPlayerCamera()))
    if (!state || !m_weaponUsed)
    {
      m_RequesterADS.Stop();
      if (IsCameraNV())
        SetNVPostprocess(GetCameraNVType());
      else
        SetNVPostprocess(NVTypes.NONE);
    }
    else
    {
      temp_array = {false, 0.0, 0.0, 0.0, 0.0, 1.0};
      if (m_weaponUsed.GetWeaponDOF() || (m_opticsUsed && m_opticsUsed.GetOpticsDOF()))
      {
        if (m_opticsUsed && m_opticsUsed.GetOpticsDOF().Count() == 6)
          temp_array = m_opticsUsed.GetOpticsDOF();
        else
          temp_array = m_weaponUsed.GetWeaponDOF();
        if (temp_array.Count() != 6)
          temp_array = {false, 0.0, 0.0, 0.0, 0.0, 1.0};
      }
      m_RequesterADS.SetValuesIronsights(temp_array); //DOF only
      if (IsCameraNV())
        SetNVPostprocess(GetCameraNVType());
      else
        SetNVPostprocess(NVTypes.NONE);
    }
    if (m_weaponUsed)
      m_weaponUsed.HideWeaponBarrel(false);
  }
References GetCameraNVType(), ItemOptics::GetOpticsDOF(), IsCameraNV(), m_opticsUsed, m_pPlayer, m_weaponUsed, and SetNVPostprocess().
Referenced by OnActivate(), and UpdateCameraNV().
SetCameraPPDelay()
override void DayZPlayerCameraBase::SetCameraPPDelay (DayZPlayerCamera pPrevCamera) inline protected
Definition at line 294 of file DayZPlayerCameraIronsights.c.
  {
    if (pPrevCamera.GetCameraName() == "DayZPlayerCamera1stPerson")
    {
      //Print("---ironsights---DayZPlayerCamera1stPerson");
      m_CameraPPDelay = DayZPlayerCameras.TIME_CAMERACHANGE_01;
    }
    else if (pPrevCamera.GetCameraName() == "DayZPlayerCameraOptics")
      m_CameraPPDelay = 0;
    else
    {
      //Print("---ironsights---else");
      m_CameraPPDelay = DayZPlayerCameras.TIME_CAMERACHANGE_02;
    }
  }
References m_CameraPPDelay, DayZPlayerCameras::TIME_CAMERACHANGE_01, and DayZPlayerCameras::TIME_CAMERACHANGE_02.
Referenced by OnActivate().
SetupSightEntities()
void DayZPlayerCameraBase::SetupSightEntities () inline protected
Definition at line 60 of file DayZPlayerCameraIronsights.c.
  {
    EntityAI inHands = m_pPlayer.GetHumanInventory().GetEntityInHands();
    if (inHands)
    {
      m_weaponUsed = Weapon_Base.Cast(inHands);
      if (m_weaponUsed)
      {
        m_SightMisalignmentModifier = m_weaponUsed.GetPropertyModifierObject().m_SightMisalignment;
        m_dynamicsStrength = m_dynamicsStrength * m_SightMisalignmentModifier[0];
        m_dynamicsSmoothTime = m_dynamicsSmoothTime * m_SightMisalignmentModifier[1];
        m_opticsUsed = m_weaponUsed.GetAttachedOptics();
        if (m_opticsUsed)
          m_opticsHasWeaponOverride = m_opticsUsed.HasWeaponIronsightsOverride();
      }
      else
        m_opticsUsed = ItemOptics.Cast(inHands);
    }
  }
References ItemOptics::HasWeaponIronsightsOverride(), m_opticsUsed, m_pPlayer, and m_weaponUsed.
Referenced by DayZPlayerCameraIronsights().
UpdateBatteryOptics()
void DayZPlayerCameraBase::UpdateBatteryOptics (EntityAI entity) inline protected
Definition at line 310 of file DayZPlayerCameraIronsights.c.
  {
    ItemOptics optics = ItemOptics.Cast(entity);
    if (optics)
      optics.UpdateOpticsReddotVisibility();
  }
Referenced by OnUpdate().
Member Data Documentation
CONST_LR_MAX
static const float DayZPlayerCameraBase::CONST_LR_MAX = 160.0 static private
up limit
Definition at line 10 of file DayZPlayerCamera1stPerson.c.
CONST_LR_MIN
static const float DayZPlayerCameraBase::CONST_LR_MIN = -160.0 static private
down limit
Definition at line 9 of file DayZPlayerCamera1stPerson.c.
CONST_UD_MAX
static const float DayZPlayerCameraBase::CONST_UD_MAX = 85.0 static private
up limit
Definition at line 7 of file DayZPlayerCamera1stPerson.c.
CONST_UD_MIN
static const float DayZPlayerCameraBase::CONST_UD_MIN = -85.0 static private
down limit
Definition at line 6 of file DayZPlayerCamera1stPerson.c.
Referenced by OnUpdate().
CONST_UD_MIN_BACK
const float DayZPlayerCameraBase::CONST_UD_MIN_BACK = -25.0 static private
down limit on back
Definition at line 7 of file DayZPlayerCameraIronsights.c.
Referenced by OnUpdate().
m_bShoulderInLS
bool DayZPlayerCameraBase::m_bShoulderInLS protected
true - shoulder is in local space
Definition at line 124 of file DayZPlayerCamera3rdPerson.c.
m_CameraOffsetLS
vector DayZPlayerCameraBase::m_CameraOffsetLS protected
local space offset
Definition at line 121 of file DayZPlayerCamera3rdPerson.c.
Referenced by OnUpdate().
m_CameraOffsetMS
vector DayZPlayerCameraBase::m_CameraOffsetMS protected
model space offset
Definition at line 120 of file DayZPlayerCamera3rdPerson.c.
Referenced by OnUpdate(), and OnUpdate().
m_dynamicsSmoothTime
float DayZPlayerCameraBase::m_dynamicsSmoothTime protected
Definition at line 22 of file DayZPlayerCameraIronsights.c.
m_dynamicsStrength
float DayZPlayerCameraBase::m_dynamicsStrength protected
Definition at line 21 of file DayZPlayerCameraIronsights.c.
m_fCameraLRShoulder
float DayZPlayerCameraBase::m_fCameraLRShoulder protected
shoulder offsets
Definition at line 136 of file DayZPlayerCamera3rdPerson.c.
m_fCameraLRShoulderVel
float DayZPlayerCameraBase::m_fCameraLRShoulderVel[1] protected
Definition at line 137 of file DayZPlayerCamera3rdPerson.c.
m_fDistance
float DayZPlayerCameraBase::m_fDistance protected
distance from start
Definition at line 122 of file DayZPlayerCamera3rdPerson.c.
Referenced by OnUpdate(), and OnUpdate().
m_fLeanDistance
float DayZPlayerCameraBase::m_fLeanDistance protected
shift on leaning
Definition at line 126 of file DayZPlayerCamera3rdPerson.c.
Referenced by OnUpdate().
m_fLeftRightAngle
float DayZPlayerCameraBase::m_fLeftRightAngle protected
left right angle in rad (in freelook only)
Definition at line 93 of file DayZPlayerCamera1stPerson.c.
Referenced by GetBaseAngles(), and GetBaseAngles().
m_fLeftRightAngleAdd
float DayZPlayerCameraBase::m_fLeftRightAngleAdd protected
left right angle in rad (in freelook only)
Definition at line 94 of file DayZPlayerCamera1stPerson.c.
Referenced by GetAdditiveAngles(), and GetAdditiveAngles().
m_fPredictCollisionRadius
float DayZPlayerCameraBase::m_fPredictCollisionRadius protected
collision prediction
Definition at line 140 of file DayZPlayerCamera3rdPerson.c.
Referenced by OnUpdate().
m_fRoll
float DayZPlayerCameraBase::m_fRoll protected
camera roll (deprecated)
Definition at line 125 of file DayZPlayerCamera3rdPerson.c.
m_fShootFromCamera
float DayZPlayerCameraBase::m_fShootFromCamera = 0.0 protected
settings
Definition at line 318 of file DayZPlayerCameraIronsights.c.
Referenced by AdjustCameraParameters().
m_fShoulderWidth
float DayZPlayerCameraBase::m_fShoulderWidth protected
shoulder camera widths
Definition at line 123 of file DayZPlayerCamera3rdPerson.c.
m_fUpDownAngle
float DayZPlayerCameraBase::m_fUpDownAngle protected
up down angle in rad
runtime values
up down angle in rad
Definition at line 91 of file DayZPlayerCamera1stPerson.c.
Referenced by GetBaseAngles(), and GetBaseAngles().
m_fUpDownAngleAdd
float DayZPlayerCameraBase::m_fUpDownAngleAdd protected
up down angle in rad
Definition at line 92 of file DayZPlayerCamera1stPerson.c.
Referenced by GetAdditiveAngles(), and GetAdditiveAngles().
m_iBoneIndex
int DayZPlayerCameraBase::m_iBoneIndex = -1 protected
main bone
runtime values
runtime config
main bone
right hand dummy bone index
Definition at line 88 of file DayZPlayerCamera1stPerson.c.
Referenced by AdjustCameraParameters().
m_isEntering
bool DayZPlayerCameraBase::m_isEntering = false protected
Definition at line 12 of file DayZPlayerCameraIronsights.c.
m_movementAmplitudeX
float DayZPlayerCameraBase::m_movementAmplitudeX protected
Definition at line 26 of file DayZPlayerCameraIronsights.c.
m_movementAmplitudeY
float DayZPlayerCameraBase::m_movementAmplitudeY protected
Definition at line 27 of file DayZPlayerCameraIronsights.c.
m_movementFrequencyX
float DayZPlayerCameraBase::m_movementFrequencyX protected
Definition at line 28 of file DayZPlayerCameraIronsights.c.
m_movementFrequencyY
float DayZPlayerCameraBase::m_movementFrequencyY protected
Definition at line 29 of file DayZPlayerCameraIronsights.c.
m_MovementState
ref HumanMovementState DayZPlayerCameraBase::m_MovementState = new HumanMovementState() protected
movement state
Definition at line 143 of file DayZPlayerCamera3rdPerson.c.
m_movementTimeAcc
float DayZPlayerCameraBase::m_movementTimeAcc protected
Definition at line 25 of file DayZPlayerCameraIronsights.c.
m_OffsetLS
vector DayZPlayerCameraBase::m_OffsetLS protected
position offset
Definition at line 89 of file DayZPlayerCamera1stPerson.c.
m_OpticsCamDir
vector DayZPlayerCameraBase::m_OpticsCamDir protected
Definition at line 323 of file DayZPlayerCameraIronsights.c.
m_OpticsCamPos
vector DayZPlayerCameraBase::m_OpticsCamPos protected
Definition at line 322 of file DayZPlayerCameraIronsights.c.
m_opticsHasWeaponOverride
bool DayZPlayerCameraBase::m_opticsHasWeaponOverride = false protected
Definition at line 13 of file DayZPlayerCameraIronsights.c.
m_RequesterADS
PPERequester_CameraADS DayZPlayerCameraBase::m_RequesterADS protected
Definition at line 16 of file DayZPlayerCameraIronsights.c.
m_SightMisalignmentModifier
vector DayZPlayerCameraBase::m_SightMisalignmentModifier protected
Definition at line 23 of file DayZPlayerCameraIronsights.c.
m_velocityPitch
float DayZPlayerCameraBase::m_velocityPitch[1] protected
Definition at line 20 of file DayZPlayerCameraIronsights.c.
m_velocityYaw
float DayZPlayerCameraBase::m_velocityYaw[1] protected
camera dynamics
Definition at line 19 of file DayZPlayerCameraIronsights.c.
temp_array
ref array<float> DayZPlayerCameraBase::temp_array protected
Definition at line 14 of file DayZPlayerCameraIronsights.c.
The documentation for this class was generated from the following files:
scripts/4_World/Entities/ManBase/DayZPlayer/DayZPlayerCamera1stPerson.c
scripts/4_World/Entities/ManBase/DayZPlayer/DayZPlayerCamera3rdPerson.c
scripts/4_World/Entities/ManBase/DayZPlayer/DayZPlayerCameraIronsights.c