DayZ: scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionDigOutStash.c File Reference
ActionDigOutStash.c File Reference
Classes
class ActionDigOutStashCB
class DigOutStashLambda
Functions
ActionDigOutStashCB ActionContinuousBaseCB ActionDigOutStash ()
override void CreateActionComponent ()
override void CreateConditionComponents ()
override bool Can (PlayerBase player, ActionTarget target, ItemBase item, int condition_mask)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
void SpawnParticleShovelRaise (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override string GetAdminLogMessage (ActionData action_data)
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 36 of file ActionDigOutStash.c.
  {
    ItemBase target_IB;
    if (Class.CastTo(target_IB, target.GetObject()))
    {
      if (target_IB.CanBeDigged())
        return target_IB.IsInherited(UndergroundStash);
    }
    return false;
  }
References Class::CastTo().
ActionDigOutStash()
ActionDigOutStashCB ActionContinuousBaseCB ActionDigOutStash ()
Definition at line 1 of file ActionDigOutStash.c.
  {
    m_CallbackClass = ActionDigOutStashCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DIGUPCACHE;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
    m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_LOW;
    m_Text = "#dig_stash";
  }
Referenced by ActionConstructor::RegisterActions(), ItemBase::SetActions(), and FarmingHoe::SetActions().
Can()
override bool Can (PlayerBase player, ActionTarget target, ItemBase item, int condition_mask)
Definition at line 27 of file ActionDigOutStash.c.
  {
    if (!super.Can(player, target, item, condition_mask))
      return false;
    return player.CheckFreeSpace(vector.Forward, 1.0, false);
  }
References vector::Forward.
CreateActionComponent()
override void ActionDigOutStash::CreateActionComponent ()
Definition at line 12 of file ActionDigOutStash.c.
  {
    m_CallbackClass = ActionDigOutStashCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DIGUPCACHE;
    m_FullBody = true;
References m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_LOW.
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 21 of file ActionDigOutStash.c.
  {
    m_ConditionTarget = new CCTObject(UAMaxDistances.DEFAULT);
    m_ConditionItem = new CCINonRuined();
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetAdminLogMessage()
override string GetAdminLogMessage (ActionData action_data)
Definition at line 103 of file ActionDigOutStash.c.
  {
    return string.Format("Player %1 Dug out %2 at position %3", action_data.m_Player, action_data.m_Target.GetObject(), action_data.m_Target.GetObject().GetPosition());
  }
References string::Format().
OnExecuteClient()
override void OnExecuteClient (ActionData action_data)
Definition at line 48 of file ActionDigOutStash.c.
  {
    super.OnExecuteClient(action_data);
    SpawnParticleShovelRaise(action_data);
  }
References SpawnParticleShovelRaise().
OnExecuteServer()
override void OnExecuteServer (ActionData action_data)
Definition at line 55 of file ActionDigOutStash.c.
  {
    super.OnExecuteServer(action_data);
    if (!GetGame().IsMultiplayer())
      SpawnParticleShovelRaise(action_data);
  }
References GetGame(), and SpawnParticleShovelRaise().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 68 of file ActionDigOutStash.c.
  {
    EntityAI targetEntity = EntityAI.Cast(action_data.m_Target.GetObject());
    if (!targetEntity)
    {
      ErrorEx("Cannot get entity=" + targetEntity);
      return;
    }
    InventoryLocation target_IL = new InventoryLocation();
    if (!targetEntity.GetInventory().GetCurrentInventoryLocation(target_IL))
    {
      ErrorEx("Cannot get inventory location of entity=" + targetEntity);
      return;
    }
    // Dig out of stash
    UndergroundStash stash;
    if (Class.CastTo(stash, targetEntity))
    {
      ItemBase stashedItem = stash.GetStashedItem();
      if (stashedItem)
      {
        DigOutStashLambda lambda(stash, "", action_data.m_Player);
        action_data.m_Player.ServerReplaceItemWithNew(lambda);
      }
      else
        g_Game.ObjectDelete(stash);
    }
    //Apply tool damage
    MiscGameplayFunctions.DealAbsoluteDmg(action_data.m_MainItem, 10);
    action_data.m_Player.GetSoftSkillsManager().AddSpecialty(m_SpecialtyWeight);
  }
References Class::CastTo(), ErrorEx, g_Game, and m_SpecialtyWeight.
SpawnParticleShovelRaise()
void SpawnParticleShovelRaise (ActionData action_data)
Definition at line 63 of file ActionDigOutStash.c.
  {
    ParticleManager.GetInstance().PlayOnObject(ParticleList.DIGGING_STASH, action_data.m_Player);
  }
References ParticleList::DIGGING_STASH, and ParticleManager().
Referenced by OnExecuteClient(), and OnExecuteServer().