DayZ: ContentDLC Class Reference
ContentDLC Class Reference
ContentDLC is for query installed DLC (only as entitlement keys, not content)
Private Member Functions
proto native int GetEntitlements (out TIntArray dlcIdList)
proto native bool IsDLCInstalled (EDLCId dlcId)
bool OwnsAllDLC ()
void OnChange (EDLCId dlcId)
Private Attributes
ref ScriptInvoker m_OnChange = new ScriptInvoker()
void(EDLCId dlcId)
Detailed Description
ContentDLC is for query installed DLC (only as entitlement keys, not content)
Definition at line 10 of file ContentDLC.c.
Member Function Documentation
GetEntitlements()
proto native int ContentDLC::GetEntitlements (out TIntArray dlcIdList) private
For getting current entitlements on device (console). Could be called after any entitlement change or before accessing locked content.
Parameters
dlcIdList through this list is returned all installed DLC with valid license for current user
Returns
count of installed and valid DLCs.
IsDLCInstalled()
proto native bool ContentDLC::IsDLCInstalled (EDLCId dlcId) private
Parameters
dlcId ID of DLC
Returns
current state of availability of unlocking' dlc. Only DLC with valid license return true.
Referenced by OwnsAllDLC().
OnChange()
void ContentDLC::OnChange (EDLCId dlcId) inline private
Called from engine for notifing script after any change in additional content (installed, lost license). There should be check for current state of entitlements. On Xbox should be problem with event lost license! (system bug)
Parameters
dlcId ID of DLC that was changed. Could be empty string if console does not report concrete DLC ID.
Definition at line 49 of file ContentDLC.c.
  {
    m_OnChange.Invoke(dlcId);
  }
References m_OnChange.
OwnsAllDLC()
bool ContentDLC::OwnsAllDLC () inline private
Definition at line 29 of file ContentDLC.c.
  {
    const int length = EnumTools.GetEnumSize(EDLCId);
    // Start at 1, because 0 is DLC_UNKNOWN
    for (int i = 1; i < length; ++i)
    {
      if (!IsDLCInstalled(EnumTools.GetEnumValue(EDLCId, i)))
        return false;
    }
    return true;
  }
References EnumTools::GetEnumSize(), EnumTools::GetEnumValue(), and IsDLCInstalled().
Member Data Documentation
m_OnChange
ref ScriptInvoker ContentDLC::m_OnChange = new ScriptInvoker() private
void(EDLCId dlcId)
Definition at line 13 of file ContentDLC.c.
Referenced by OnChange().
The documentation for this class was generated from the following file:
scripts/3_Game/Services/ContentDLC.c