DayZ: Edible_Base Class Reference
Edible_Base Class Reference
Protected Member Functions
void RefreshAudio ()
void RemoveAudio ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
FoodStage GetFoodStage ()
override bool IsMeat ()
override bool IsCorpse ()
override bool IsFruit ()
override bool IsMushroom ()
FoodStageType GetFoodStageType ()
bool IsFoodRaw ()
bool IsFoodBaked ()
bool IsFoodBoiled ()
bool IsFoodDried ()
bool IsFoodBurned ()
bool IsFoodRotten ()
void ChangeFoodStage (FoodStageType new_food_stage_type)
FoodStageType GetNextFoodStageType (CookingMethodType cooking_method)
string GetFoodStageName (FoodStageType food_stage_type)
bool CanChangeToNewStage (CookingMethodType cooking_method)
void TransferFoodStage (notnull Edible_Base source)
float GetCookingTime ()
void SetCookingTime (float time)
void ReplaceEdibleWithNew (string typeName)
override void SetActions ()
void SoundCookingStart (string sound_name)
void SoundCookingStop ()
override bool CanHaveTemperature ()
override bool CanDecay ()
override bool CanProcessDecay ()
override void ProcessDecay (float delta, bool hasRootAsPlayer)
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
override bool OnAction (int action_id, Man player, ParamsReadContext ctx)
override string GetDebugText ()
float GetDecayTimer ()
float GetDecayDelta ()
FoodStageType GetLastDecayStage ()
Static Protected Member Functions
static float GetFoodTotalVolume (ItemBase item, string classname="", int food_stage=0)
static float GetFoodEnergy (ItemBase item, string classname="", int food_stage=0)
static float GetFoodWater (ItemBase item, string classname="", int food_stage=0)
static float GetFoodNutritionalIndex (ItemBase item, string classname="", int food_stage=0)
static float GetFoodToxicity (ItemBase item, string classname="", int food_stage=0)
static int GetFoodAgents (ItemBase item, string classname="", int food_stage=0)
static float GetFoodDigestibility (ItemBase item, string classname="", int food_stage=0)
static NutritionalProfile GetNutritionalProfile (ItemBase item, string classname="", int food_stage=0)
Protected Attributes
bool m_MakeCookingSounds
SoundOnVehicle m_SoundCooking
EffectSound m_SoundEffectCooking
DEPRECATED.
string m_SoundPlaying
ref FoodStage m_FoodStage
float m_DecayTimer
float m_DecayDelta = 0.0
FoodStageType m_LastDecayStage = FoodStageType.NONE
Private Member Functions
void Edible_Base ()
override void EEInit ()
override void EEDelete (EntityAI parent)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
void UpdateVisuals ()
bool Consume (float amount, PlayerBase consumer)
void OnConsume (float amount, PlayerBase consumer)
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
void Synchronize ()
override void OnVariablesSynchronized ()
void MakeSoundsOnClient (bool soundstate, CookingMethodType cookingMethod=CookingMethodType.NONE)
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCookedOnStick ()
override bool CanBeCooked ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
void BoxCerealCrunchin ()
override void SetActions ()
void Candycane_Colorbase ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsFruit ()
override bool CanDecay ()
bool ConditionAttach (EntityAI parent)
bool ConditionDetach (EntityAI parent)
override void SetActions ()
override bool CanBeCookedOnStick ()
override bool CanBeCooked ()
override bool IsCorpse ()
override bool CanDecay ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override void SetActions ()
override void OnConsume (float amount, PlayerBase consumer)
override bool CanBeCookedOnStick ()
override bool CanBeCooked ()
override bool IsCorpse ()
override bool CanDecay ()
override bool CanBeSkinned ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override void InitItemVariables ()
override bool CanPutAsAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override float GetDisinfectQuantity (int system=0, Param param1=null)
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanPutAsAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override void SetActions ()
void HumanSteakMeat ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCookedOnStick ()
override bool CanBeCooked ()
override bool IsCorpse ()
override bool CanDecay ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override void SetActions ()
override void OnConsume (float amount, PlayerBase consumer)
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCookedOnStick ()
override bool CanBeCooked ()
override bool IsCorpse ()
override bool CanDecay ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsFruit ()
override bool CanDecay ()
bool ConditionAttach (EntityAI parent)
bool ConditionDetach (EntityAI parent)
override void SetActions ()
override bool CanBeCookedOnStick ()
override bool CanBeCooked ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanPutAsAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCookedOnStick ()
override bool CanBeCooked ()
override bool IsMeat ()
Private Member Functions inherited from ItemBase
void BarbedWire ()
void ~BarbedWire ()
override void EEInit ()
bool IsMounted ()
bool GetSlotLockedState ()
void SetMountedState (bool is_mounted)
void UpdateAttachmentSlot ()
void LockAttachmentSlot (bool lock_state)
void Synchronize ()
override void OnVariablesSynchronized ()
void PlayDeployLoopSound ()
void StopDeployLoopSound ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnWork (float consumed_energy)
override void OnIsPlugged (EntityAI source_device)
override void OnIsUnplugged (EntityAI last_energy_source)
override void OnInventoryEnter (Man player)
void CreateElectrifiedDamageTrigger ()
void CreateDamageTrigger ()
void DestroyDamageTrigger ()
void Spark ()
void SoundCut ()
void SoundSpark ()
void SoundBuzzLoopStart ()
void SoundBuzzLoopStop ()
void SoundElectricShock ()
void SoundCollision ()
override void PreAreaDamageActions ()
override void PostAreaDamageActions ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override void SetActions ()
void BaseBuildingBase ()
override void EEDelete (EntityAI parent)
override string GetInvulnerabilityTypeString ()
override bool CanObstruct ()
override int GetHideIconMask ()
void SynchronizeBaseState ()
override void OnVariablesSynchronized ()
void OnSynchronizedClient ()
void RegisterPartForSync (int part_id)
void UnregisterPartForSync (int part_id)
bool IsPartBuildInSyncData (int part_id)
void RegisterActionForSync (int part_id, int action_id)
void ResetActionSyncData ()
void SetActionFromSyncData ()
void SetPartFromSyncData (ConstructionPart part)
void SetPartsFromSyncData ()
ConstructionPart GetConstructionPartById (int id)
bool HasBase ()
void SetBaseState (bool has_base)
override bool IsDeployable ()
bool IsOpened ()
ItemBase CreateConstructionKit ()
void CreateConstructionKitInHands (notnull PlayerBase player)
vector GetKitSpawnPosition ()
string GetConstructionKitType ()
void DestroyConstructionKit (ItemBase construction_kit)
void DestroyConstruction ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
void SetPartsAfterStoreLoad ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void EEOnAfterLoad ()
override void EEInit ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
void OnSetSlotLock (int slotId, bool locked, bool was_locked)
override bool IgnoreOutOfReachCondition ()
void OnPartBuiltServer (notnull Man player, string part_name, int action_id)
void OnPartBuiltClient (string part_name, int action_id)
void OnPartDismantledServer (notnull Man player, string part_name, int action_id)
void OnPartDismantledClient (string part_name, int action_id)
void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part=false)
void OnPartDestroyedClient (string part_name, int action_id)
void InitBaseState ()
void InitVisuals ()
void UpdateVisuals ()
void UpdateAttachmentVisuals (string slot_name, bool is_locked)
void UpdatePhysics ()
void UpdateAttachmentPhysics (string slot_name, bool is_locked)
void UpdateNavmesh ()
override bool CanUseConstruction ()
override bool CanUseConstructionBuild ()
bool IsAttachmentSlotLocked (EntityAI attachment)
bool IsAttachmentSlotLocked (string slot_name)
void GetAttachmentSlots (EntityAI entity, out array< string > attachment_slots)
bool CheckSlotVerticalDistance (int slot_id, PlayerBase player)
bool CheckMemoryPointVerticalDistance (float max_dist, string selection, PlayerBase player)
bool CheckLevelVerticalDistance (float max_dist, string selection, PlayerBase player)
void ConstructionInit ()
Construction GetConstruction ()
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
bool HasAttachmentsBesidesBase ()
override bool ShowZonesHealth ()
override bool CanPutInCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool IsFacingPlayer (PlayerBase player, string selection)
override bool IsPlayerInside (PlayerBase player, string selection)
bool MustBeBuiltFromOutside ()
Some buildings can only be built from outside.
bool IsFacingCamera (string selection)
bool PerformRoofCheckForBase (string partName, PlayerBase player, out bool result)
bool HasProperDistance (string selection, PlayerBase player)
bool CanFoldBaseBuildingObject ()
ItemBase FoldBaseBuildingObject ()
void CreateAreaDamage (string slot_name, float rotation_angle=0)
void CalcDamageAreaRotation (float angle_deg, out vector center, out vector orientation)
void DestroyAreaDamage (string slot_name)
override bool IsIgnoredByConstruction ()
void SoundBuildStart (string part_name)
void SoundDismantleStart (string part_name)
void SoundDestroyStart (string part_name)
string GetBuildSoundByMaterial (string part_name)
string GetDismantleSoundByMaterial (string part_name)
void CheckForHybridAttachments (EntityAI item, string slot_name)
override int GetDamageSystemVersionChange ()
override void SetActions ()
void DebugCustomState ()
array< string > OnDebugSpawnBuildExcludes ()
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
override void OnDebugSpawn ()
void FullyBuild ()
void BatteryCharger ()
override bool IsElectricAppliance ()
override void OnWork (float consumed_energy)
override void OnWorkStart ()
override void OnWorkStop ()
void UpdateStatusLights ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI player)
override void OnOwnSocketTaken (EntityAI device)
override void OnOwnSocketReleased (EntityAI device)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanLoadAttachment (EntityAI attachment)
void HideAttachedClipsStates ()
void RedLightOn ()
void GreenLightOn ()
void YellowLightOn ()
void SwitchLightOn ()
void RedLightOff ()
void GreenLightOff ()
void YellowLightOff ()
void SwitchLightOff ()
override void OnSwitchOn ()
override void OnSwitchOff ()
override void OnInventoryExit (Man player)
override void OnInventoryEnter (Man player)
override void OnVariablesSynchronized ()
override void RefreshPhysics ()
override void OnPlacementStarted (Man player)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override bool IsDeployable ()
override string GetPlaceSoundset ()
override void SetActions ()
override void OnWorkStart ()
override void OnWorkStop ()
void RefreshFlameVisual (bool working=false)
void SoundBurningStart ()
void SoundBurningStop ()
override bool CanPutInCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool IsIgnited ()
override void OnIgnitedTarget (EntityAI ignited_item)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override void SetActions ()
EntityAI GetGasCanister ()
bool HasEnoughEnergyForRepair (float pTime)
override void OnDebugSpawn ()
void KitBase ()
void ~KitBase ()
override bool IsBasebuildingKit ()
override bool HasProxyParts ()
override bool CanProxyObstruct ()
override void OnVariablesSynchronized ()
override void EEInit ()
override bool DisassembleOnLastDetach ()
override void EEItemDetached (EntityAI item, string slot_name)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnEndPlacement ()
override void OnPlacementCancelled (Man player)
override bool IsDeployable ()
override bool CanAssignAttachmentsToQuickbar ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override string GetDeployFinishSoundset ()
override void RefreshPhysics ()
void UpdateVisuals ()
void UpdatePhysics ()
void PlayDeployLoopSound ()
void StopDeployLoopSound ()
void AssembleKit ()
void DisassembleKit (ItemBase item)
void CreateRope (Rope rope)
override void SetActions ()
void Paper ()
void ~Paper ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override WrittenNoteData GetWrittenNoteData ()
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=null)
override bool CanIgniteItem (EntityAI ignite_target=null)
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedThis (EntityAI fire_source)
override bool IsThisIgnitionSuccessful (EntityAI item_source=null)
override void SetActions ()
void ParticleTest ()
override void EEDelete (EntityAI parent)
override void OnSwitchOn ()
override void OnSwitchOff ()
override void OnWorkStart ()
override void OnWorkStop ()
void SoundBurningStart ()
void SoundBurningStop ()
void SoundTurnOn ()
void SoundTurnOff ()
override void SetActions ()
ItemBase GetCookingEquipment ()
void SetCookingEquipment (ItemBase equipment)
void ClearCookingEquipment (ItemBase pItem)
void DestroyFireplace ()
override void EEInit ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void OnSwitchOn ()
override void OnSwitchOff ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnWork (float consumed_energy)
void CookWithEquipment ()
void RefreshFlameVisual (bool working=false, bool hasAttachment=false)
void RemoveCookingAudioVisuals ()
void SoundBurningStart ()
void SoundBurningStop ()
void SoundTurnOn ()
void SoundTurnOff ()
override bool CanPutInCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanLoadAttachment (EntityAI attachment)
override bool CanPutIntoHands (EntityAI parent)
override bool IsIgnited ()
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override void SetActions ()
override void OnDebugSpawn ()
void PowerGeneratorBase ()
void ~PowerGeneratorBase ()
override void EEInit ()
override void EOnInit (IEntity other, int extra)
override float GetLiquidThroughputCoef ()
void StartLoopSound ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI player)
bool CanManipulate ()
override void OnInitEnergy ()
override void OnWorkStart ()
override void OnWork (float consumed_energy)
override void OnWorkStop ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
void UpdateFuelMeter ()
void SetFuel (float fuel_amount)
float AddFuel (float available_fuel)
bool CanAddFuel (ItemBase container)
float GetFuel ()
float GetMaxFuel ()
bool HasSparkplug ()
override void OnVariablesSynchronized ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override string GetPlaceSoundset ()
override void SetActions ()
override void OnDebugSpawn ()
override void OnWorkStart ()
void StartPeriodicMeasurement ()
void PrepareMeasurement ()
void DoMeasurement ()
void StopPeriodicMeasurement ()
override void OnWorkStop ()
override void SetActions ()
void Spotlight ()
void ~Spotlight ()
override bool IsElectricAppliance ()
override void OnInitEnergy ()
override void EOnInit (IEntity other, int extra)
override void OnSwitchOn ()
override void OnSwitchOff ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnIsPlugged (EntityAI source_device)
void UpdateAllSelections ()
override void OnIsUnplugged (EntityAI last_energy_source)
override void OnVariablesSynchronized ()
void Fold (bool keep_connected=false)
void Unfold ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI player)
bool IsFolded ()
void SoundTurnOn ()
void SoundTurnOff ()
override void OnPlacementStarted (Man player)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnPlacementCancelled (Man player)
override bool IsDeployable ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
void PlayDeployLoopSound ()
void StopDeployLoopSound ()
override int GetViewIndex ()
override void SetActions ()
void TentBase ()
void ~TentBase ()
override string GetInvulnerabilityTypeString ()
override bool HasProxyParts ()
override bool CanProxyObstructSelf ()
prevents showing cargo when outside the tent geometry
override bool IsItemTent ()
override bool CanBeRepairedByCrafting ()
override int GetMeleeTargetType ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void RefreshPhysics ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnVariablesSynchronized ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
void HideAllAnimationsAndProxyPhysics (bool hide_animations=true, bool hide_physics=true)
bool ConditionIntoInventory (EntityAI player)
override bool CanPutIntoHands (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
bool ConditionOutOfHands (EntityAI player)
override bool CanBeRepairedToPristine ()
void RefreshAttachements ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override int GetViewIndex ()
int GetState ()
int GetStateLocal ()
bool CanBePacked ()
bool CanBeManipulated ()
bool CanAttach (ItemBase item)
override bool IsIgnoredByConstruction ()
void Pack (bool update_navmesh, bool init=false)
void Pitch (bool update_navmesh, bool init=false)
void TryPitch (bool update_navmesh, bool init=false)
void UpdateVisuals ()
void UpdatePhysics ()
void Refresh ()
bool CanToggleAnimations (string selection)
void ResetToggle ()
void ManipulateEntrance ()
void ManipulateWindow ()
bool IsManipulatedEntrance ()
bool IsManipulatedWindow ()
void ToggleAnimation (string selection)
void HandleCamoNetAttachment (bool hide)
void AnimateCamonetToggle (ToggleAnimations toggle)
void AnimateCamonetByOpeningSelection (string opening_selection)
string GetSoundOpen ()
string GetSoundClose ()
string GetSoundOpenWindow ()
string GetSoundCloseWindow ()
void SoundTentOpenPlay ()
void SoundTentClosePlay ()
void SoundTentOpenWindowPlay ()
void SoundTentCloseWindowPlay ()
void RegenerateNavmesh ()
bool HasClutterCutter ()
string GetClutterCutter ()
void DestroyClutterCutter ()
override bool IsDeployable ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
void PlayDeployLoopSound ()
void StopDeployLoopSound ()
override void SetActions ()
void HandleOpeningsVisuals ()
void HandleOpeningsPhysics ()
override int GetDamageSystemVersionChange ()
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanLoadItemIntoCargo (EntityAI item)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanLoadAttachment (EntityAI attachment)
override bool CanBePlaced (Man player, vector position)
void SetIsBeingPacked (bool isBeingPacked)
void ToolBase ()
int GetDisarmRate ()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Private Attributes
const string DIRECT_COOKING_SLOT_NAME = "DirectCooking"
const string SOUND_BAKING_START = "Baking_SoundSet"
const string SOUND_BAKING_DONE = "Baking_Done_SoundSet"
const string SOUND_BURNING_DONE = "Food_Burning_SoundSet"
CookingMethodType m_CookedByMethod
Private Attributes inherited from ItemBase
ref array< ref Slot > m_Slots
int m_SlotFertilityState = 0
int m_SlotWateredState = 0
int m_MaxWateredStateVal = 0
float m_DefaultFertility = 1
ref Timer m_CheckRainTimer
EffectSound m_DeployLoopSound
SoundOnVehicle m_BuzzSoundLoop
ref Timer m_SparkEvent
ref AreaDamageManager m_AreaDamage
bool m_TriggerActive
bool m_IsPlaced
bool m_IsMounted
bool m_LastMountedState
const string SOUND_MOUNT = "putDown_BarbedWire_SoundSet"
EffectSound m_MountSound
EffectSound m_Sound
ref map< string, ref AreaDamageManager > m_DamageTriggers
ref array< string > m_HybridAttachments
ref array< string > m_Mountables
const string ATTACHED_CLIPS_STATES [] = {SEL_CLIPS_CAR, SEL_CLIPS_TRUCK}
const int ATTACHED_CLIPS_STATES_COUNT = 2
int m_BatteryEnergy0To100
float m_ChargeEnergyPerSecond
ref Timer m_UpdateStatusLightsTimer
bool m_BlinkingStatusLightIsOn = false
BlowtorchLight m_Light
EffectSound m_SoundBurningLoop
bool m_DeployedRegularly
ref WrittenNoteData m_NoteContents
int PARTICLE_PATH
Particle m_Particle
EffectSound m_SoundTurnOn
EffectSound m_SoundTurnOff
const string FLAME_BUTANE_ON = "dz\\gear\\cooking\\data\\flame_butane_ca.paa"
const string FLAME_BUTANE_OFF = ""
ATTACHMENT_COOKING_POT = Pot
ATTACHMENT_FRYING_PAN = FryingPan
ATTACHMENT_CAULDRON = Cauldron
const float PARAM_COOKING_TEMP_THRESHOLD = 100
const float PARAM_COOKING_EQUIP_TEMP_INCREASE = 10
const float PARAM_COOKING_EQUIP_MAX_TEMP = 250
const float PARAM_COOKING_TIME_INC_COEF = 0.5
ref UniversalTemperatureSource m_UTSource
DEPRECATED Attached spark plug item.
ref UniversalTemperatureSourceSettings m_UTSSettings
ref UniversalTemperatureSourceLambdaConstant m_UTSLConst
EffectSound m_EngineLoop
EffectSound m_EngineStart
EffectSound m_EngineStop
ref Timer m_SoundLoopStartTimer
Effect m_Smoke
ItemBase m_SparkPlug
ref UniversalTemperatureSourceLambdaEngine m_UTSLEngine
ref Timer m_Timer
int m_State
int m_StateLocal = -1
bool m_IsEntrance
bool m_IsWindow
bool m_IsToggle
bool m_IsBeingPacked = false
int m_OpeningMask = 0
int m_OpeningMaskLocal = -1
ref map< ref ToggleAnimations, bool > m_ToggleAnimations
ref array< string > m_ShowAnimationsWhenPitched
ref array< string > m_ShowAnimationsWhenPacked
Object m_ClutterCutter
CamoNet m_CamoNet
vector m_HalfExtents
int m_MineDisarmRate = 60
EntityAI m_Bait
bool m_IsActive
bool m_IsDeployed
bool m_IsInProgress
string m_AnimationPhaseSet
string m_AnimationPhaseTriggered
string m_AnimationPhaseUsed
ref array< string > m_PlaceableWaterSurfaceList
DEPRECATED.
bool m_WaterSurfaceForSetup
ref multiMap< string, float > m_CatchesPond
ref multiMap< string, float > m_CatchesSea
ref multiMap< string, float > m_CatchesGroundAnimal
ref EffectSound m_DeployLoopSound
ref Timer m_PrevTimer
bool m_NeedInstalation
bool m_BaitNeeded
bool m_IsUsable
Additional Inherited Members
Static Private Attributes inherited from ItemBase
const string SEL_CLIPS_CAR = "clips_car_battery"
const string SEL_CLIPS_TRUCK = "clips_truck_battery"
const string SEL_CLIPS_DETACHED = "clips_detached"
const string SEL_CLIPS_FOLDED = "clips_folded"
const string SEL_SWITCH_ON = "switch_on"
const string SEL_SWITCH_OFF = "switch_off"
const string SEL_CORD_PLUGGED = "cord_plugged"
const string SEL_CORD_FOLDED = "cord_folded"
const string SEL_LIGHT_STATE_1 = "light_stand_by"
const string SEL_LIGHT_STATE_2 = "light_charging"
const string SEL_LIGHT_STATE_3 = "light_charged"
const string RED_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_r.rvmat"
const string GREEN_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_g.rvmat"
const string YELLOW_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_y.rvmat"
const string SWITCH_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_switch_on.rvmat"
const string DEFAULT_MATERIAL = "dz\\gear\\camping\\data\\battery_charger.rvmat"
float m_BlinkingStatusLightInterval = 0.4
Detailed Description
Definition at line 1 of file Edible_Base.c.
Constructor & Destructor Documentation
Edible_Base()
void Edible_Base::Edible_Base () inline private
Definition at line 20 of file Edible_Base.c.
  {
    if (HasFoodStage())
    {
      m_FoodStage = new FoodStage(this);
      RegisterNetSyncVariableInt("m_FoodStage.m_FoodStageType", FoodStageType.NONE, FoodStageType.COUNT);
      RegisterNetSyncVariableInt("m_FoodStage.m_SelectionIndex", 0, 6);
      RegisterNetSyncVariableInt("m_FoodStage.m_TextureIndex", 0, 6);
      RegisterNetSyncVariableInt("m_FoodStage.m_MaterialIndex", 0, 6);
      RegisterNetSyncVariableFloat("m_FoodStage.m_CookingTime", 0, 600, 0);
      m_SoundPlaying = "";
      m_CookedByMethod = CookingMethodType.NONE;
      RegisterNetSyncVariableInt("m_CookedByMethod", CookingMethodType.NONE, CookingMethodType.COUNT);
      RegisterNetSyncVariableBool("m_MakeCookingSounds");
    }
  }
References HasFoodStage(), m_CookedByMethod, m_FoodStage, and m_SoundPlaying.
Member Function Documentation
AfterStoreLoad()
override void Edible_Base::AfterStoreLoad () inline protected
Definition at line 214 of file Edible_Base.c.
  {
    super.AfterStoreLoad();
    Synchronize();
  }
References Synchronize().
BoxCerealCrunchin()
void Edible_Base::BoxCerealCrunchin () inline private
Definition at line 3 of file BoxCerealCrunchin.c.
  {
  }
CanBeCooked() [1/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 93 of file Edible_Base.c.
  {
    return false;
  }
CanBeCooked() [2/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file BearSteakMeat.c.
  {
    return true;
  }
CanBeCooked() [3/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file Bitterlings.c.
  {
    return true;
  }
CanBeCooked() [4/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file BoarSteakMeat.c.
  {
    return true;
  }
CanBeCooked() [5/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file CaninaBerry.c.
  {
    return true;
  }
CanBeCooked() [6/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file Carp.c.
  {
    return false;
  }
CanBeCooked() [7/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file CarpFilletMeat.c.
  {
    return true;
  }
CanBeCooked() [8/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file Chicken_ColorBase.c.
  {
    return false;
  }
CanBeCooked() [9/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file ChickenBreastMeat.c.
  {
    return true;
  }
CanBeCooked() [10/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file CowSteakMeat.c.
  {
    return true;
  }
CanBeCooked() [11/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file DeerSteakMeat.c.
  {
    return true;
  }
CanBeCooked() [12/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file FoxSteakMeat.c.
  {
    return true;
  }
CanBeCooked() [13/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file GoatSteakMeat.c.
  {
    return true;
  }
CanBeCooked() [14/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file HumanSteakMeat.c.
  {
    return true;
  }
CanBeCooked() [15/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file Lard.c.
  {
    return true;
  }
CanBeCooked() [16/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file Mackerel.c.
  {
    return false;
  }
CanBeCooked() [17/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file MackerelFilletMeat.c.
  {
    return true;
  }
CanBeCooked() [18/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file MouflonSteakMeat.c.
  {
    return true;
  }
CanBeCooked() [19/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file PigSteakMeat.c.
  {
    return true;
  }
CanBeCooked() [20/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file Rabbit.c.
  {
    return false;
  }
CanBeCooked() [21/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file RabbitLegMeat.c.
  {
    return true;
  }
CanBeCooked() [22/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file SambucusBerry.c.
  {
    return true;
  }
CanBeCooked() [23/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file Sardines.c.
  {
    return true;
  }
CanBeCooked() [24/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file SheepSteakMeat.c.
  {
    return true;
  }
CanBeCooked() [25/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file WolfSteakMeat.c.
  {
    return true;
  }
CanBeCooked() [26/26]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file Worm.c.
  {
    return false;
  }
CanBeCookedOnStick() [1/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 98 of file Edible_Base.c.
  {
    return false;
  }
CanBeCookedOnStick() [2/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file BearSteakMeat.c.
  {
    return true;
  }
CanBeCookedOnStick() [3/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 3 of file Bitterlings.c.
  {
    return true;
  }
CanBeCookedOnStick() [4/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file BoarSteakMeat.c.
  {
    return true;
  }
CanBeCookedOnStick() [5/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file CaninaBerry.c.
  {
    return false;
  }
CanBeCookedOnStick() [6/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 3 of file Carp.c.
  {
    return false;
  }
CanBeCookedOnStick() [7/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file CarpFilletMeat.c.
  {
    return true;
  }
CanBeCookedOnStick() [8/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 3 of file Chicken_ColorBase.c.
  {
    return false;
  }
CanBeCookedOnStick() [9/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file ChickenBreastMeat.c.
  {
    return true;
  }
CanBeCookedOnStick() [10/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file CowSteakMeat.c.
  {
    return true;
  }
CanBeCookedOnStick() [11/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file DeerSteakMeat.c.
  {
    return true;
  }
CanBeCookedOnStick() [12/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file FoxSteakMeat.c.
  {
    return true;
  }
CanBeCookedOnStick() [13/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file GoatSteakMeat.c.
  {
    return true;
  }
CanBeCookedOnStick() [14/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 13 of file HumanSteakMeat.c.
  {
    return true;
  }
CanBeCookedOnStick() [15/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file Lard.c.
  {
    return true;
  }
CanBeCookedOnStick() [16/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 3 of file Mackerel.c.
  {
    return false;
  }
CanBeCookedOnStick() [17/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file MackerelFilletMeat.c.
  {
    return true;
  }
CanBeCookedOnStick() [18/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file MouflonSteakMeat.c.
  {
    return true;
  }
CanBeCookedOnStick() [19/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file PigSteakMeat.c.
  {
    return true;
  }
CanBeCookedOnStick() [20/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 3 of file Rabbit.c.
  {
    return false;
  }
CanBeCookedOnStick() [21/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file RabbitLegMeat.c.
  {
    return true;
  }
CanBeCookedOnStick() [22/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file SambucusBerry.c.
  {
    return false;
  }
CanBeCookedOnStick() [23/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 3 of file Sardines.c.
  {
    return true;
  }
CanBeCookedOnStick() [24/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file SheepSteakMeat.c.
  {
    return true;
  }
CanBeCookedOnStick() [25/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file WolfSteakMeat.c.
  {
    return true;
  }
CanBeCookedOnStick() [26/26]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 3 of file Worm.c.
  {
    return false;
  }
CanBeSkinned()
override bool Edible_Base::CanBeSkinned () inline private
Definition at line 23 of file Chicken_ColorBase.c.
  {
    if (GetHealthLevel() == GameConstants.STATE_RUINED)
      return false;
    return true;
  }
References GameConstants::STATE_RUINED.
CanChangeToNewStage()
bool Edible_Base::CanChangeToNewStage (CookingMethodType cooking_method) inline protected
Definition at line 409 of file Edible_Base.c.
  {
    return GetFoodStage().CanChangeToNewStage(cooking_method);
  }
References GetFoodStage().
Referenced by ProcessDecay().
CanDecay() [1/25]
override bool Edible_Base::CanDecay () inline protected
Definition at line 493 of file Edible_Base.c.
  {
    return false;
  }
CanDecay() [2/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file BearSteakMeat.c.
  {
    return true;
  }
CanDecay() [3/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file Bitterlings.c.
  {
    return true;
  }
CanDecay() [4/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file BoarSteakMeat.c.
  {
    return true;
  }
CanDecay() [5/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file CaninaBerry.c.
  {
    return true;
  }
CanDecay() [6/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file Carp.c.
  {
    return true;
  }
CanDecay() [7/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file CarpFilletMeat.c.
  {
    return true;
  }
CanDecay() [8/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file Chicken_ColorBase.c.
  {
    return true;
  }
CanDecay() [9/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file ChickenBreastMeat.c.
  {
    return true;
  }
CanDecay() [10/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file CowSteakMeat.c.
  {
    return true;
  }
CanDecay() [11/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file DeerSteakMeat.c.
  {
    return true;
  }
CanDecay() [12/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file FoxSteakMeat.c.
  {
    return true;
  }
CanDecay() [13/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file GoatSteakMeat.c.
  {
    return true;
  }
CanDecay() [14/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 23 of file HumanSteakMeat.c.
  {
    return true;
  }
CanDecay() [15/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file Lard.c.
  {
    return true;
  }
CanDecay() [16/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file Mackerel.c.
  {
    return true;
  }
CanDecay() [17/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file MackerelFilletMeat.c.
  {
    return true;
  }
CanDecay() [18/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file MouflonSteakMeat.c.
  {
    return true;
  }
CanDecay() [19/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file PigSteakMeat.c.
  {
    return true;
  }
CanDecay() [20/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file Rabbit.c.
  {
    return true;
  }
CanDecay() [21/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file RabbitLegMeat.c.
  {
    return true;
  }
CanDecay() [22/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file SambucusBerry.c.
  {
    return true;
  }
CanDecay() [23/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file Sardines.c.
  {
    return true;
  }
CanDecay() [24/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file SheepSteakMeat.c.
  {
    return true;
  }
CanDecay() [25/25]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file WolfSteakMeat.c.
  {
    return true;
  }
CanDetachAttachment() [1/3]
override bool Edible_Base::CanDetachAttachment (EntityAI parent) inline private
Definition at line 43 of file DisinfectantSpray.c.
  {
    bool is_barrel = false;
    bool is_opened_barrel = false;
    // is barrel
    if (parent.IsKindOf("Barrel_ColorBase"))
      is_barrel = true;
    // is opened barrel
    if (is_barrel && parent.GetAnimationPhase("Lid") == 1)
      is_opened_barrel = true;
    if (is_opened_barrel || !is_barrel)
      return true;
    return false;
  }
CanDetachAttachment() [2/3]
override bool Edible_Base::CanDetachAttachment (EntityAI parent) inline private
Definition at line 36 of file Guts.c.
  {
    bool is_barrel = false;
    bool is_opened_barrel = false;
    // is barrel
    if (parent.IsKindOf("Barrel_ColorBase"))
      is_barrel = true;
    // is opened barrel
    if (is_barrel && parent.GetAnimationPhase("Lid") == 1)
      is_opened_barrel = true;
    if (is_opened_barrel || !is_barrel)
      return true;
    return false;
  }
CanDetachAttachment() [3/3]
override bool Edible_Base::CanDetachAttachment (EntityAI parent) inline private
Definition at line 36 of file SmallGuts.c.
  {
    bool is_barrel = false;
    bool is_opened_barrel = false;
    // is barrel
    if (parent.IsKindOf("Barrel_ColorBase"))
      is_barrel = true;
    // is opened barrel
    if (is_barrel && parent.GetAnimationPhase("Lid") == 1)
      is_opened_barrel = true;
    if (is_opened_barrel || !is_barrel)
      return true;
    return false;
  }
Candycane_Colorbase()
void Edible_Base::Candycane_Colorbase () inline private
Definition at line 3 of file Candycane_Colorbase.c.
  {
  }
CanHaveTemperature()
override bool Edible_Base::CanHaveTemperature () inline protected
Definition at line 488 of file Edible_Base.c.
  {
    return true;
  }
CanProcessDecay()
override bool Edible_Base::CanProcessDecay () inline protected
Definition at line 498 of file Edible_Base.c.
  {
    return (GetFoodStageType() != FoodStageType.ROTTEN);
  }
References GetFoodStageType().
CanPutAsAttachment() [1/3]
override bool Edible_Base::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 10 of file DisinfectantSpray.c.
  {
    if (!super.CanPutAsAttachment(parent)) return false;
    const int SLOTS_ARRAY = 8;
    bool is_barrel = false;
    bool is_opened_barrel = false;
    bool slot_test = true;
    string slot_names[SLOTS_ARRAY] = { "BerryR", "BerryB", "Plant", "Nails", "OakBark", "BirchBark", "Lime", "Guts" };
    // is barrel
    if (parent.IsKindOf("Barrel_ColorBase"))
      is_barrel = true;
    // is opened barrel
    if (is_barrel && parent.GetAnimationPhase("Lid") == 1)
      is_opened_barrel = true;
    // all of the barrel slots are empty
    for (int i = 0; i < SLOTS_ARRAY ; i++)
    {
      if (parent.FindAttachmentBySlotName(slot_names[i]) != NULL)
      {
        slot_test = false;
        break;
      }
    }
    if ((is_opened_barrel && slot_test) || !is_barrel)
      return true;
    return false;
  }
CanPutAsAttachment() [2/3]
override bool Edible_Base::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file Guts.c.
  {
    if (!super.CanPutAsAttachment(parent)) return false;
    const int SLOTS_ARRAY = 8;
    bool is_barrel = false;
    bool is_opened_barrel = false;
    bool slot_test = true;
    string slot_names[SLOTS_ARRAY] = { "BerryR", "BerryB", "Nails", "OakBark", "BirchBark", "Lime", "Disinfectant" };
    // is barrel
    if (parent.IsKindOf("Barrel_ColorBase"))
      is_barrel = true;
    // is opened barrel
    if (is_barrel && parent.GetAnimationPhase("Lid") == 1)
      is_opened_barrel = true;
    // all of the barrel slots are empty
    for (int i = 0; i < SLOTS_ARRAY ; i++)
    {
      if (parent.FindAttachmentBySlotName(slot_names[i]) != NULL)
      {
        slot_test = false;
        break;
      }
    }
    if ((is_opened_barrel && slot_test) || !is_barrel)
      return true;
    return false;
  }
CanPutAsAttachment() [3/3]
override bool Edible_Base::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file SmallGuts.c.
  {
    if (!super.CanPutAsAttachment(parent)) return false;
    const int SLOTS_ARRAY = 8;
    bool is_barrel = false;
    bool is_opened_barrel = false;
    bool slot_test = true;
    string slot_names[SLOTS_ARRAY] = { "BerryR", "BerryB", "Nails", "OakBark", "BirchBark", "Lime", "Disinfectant" };
    // is barrel
    if (parent.IsKindOf("Barrel_ColorBase"))
      is_barrel = true;
    // is opened barrel
    if (is_barrel && parent.GetAnimationPhase("Lid") == 1)
      is_opened_barrel = true;
    // all of the barrel slots are empty
    for (int i = 0; i < SLOTS_ARRAY ; i++)
    {
      if (parent.FindAttachmentBySlotName(slot_names[i]) != NULL)
      {
        slot_test = false;
        break;
      }
    }
    if ((is_opened_barrel && slot_test) || !is_barrel)
      return true;
    return false;
  }
ChangeFoodStage()
void Edible_Base::ChangeFoodStage (FoodStageType new_food_stage_type) inline protected
Definition at line 394 of file Edible_Base.c.
  {
    GetFoodStage().ChangeFoodStage(new_food_stage_type);
  }
References GetFoodStage().
Referenced by Apple::EEOnCECreate(), GreenBellPepper::EEOnCECreate(), Pear::EEOnCECreate(), Plum::EEOnCECreate(), Potato::EEOnCECreate(), Tomato::EEOnCECreate(), Zucchini::EEOnCECreate(), MushroomBase::EEOnCECreate(), OnAction(), ProcessDecay(), and TransferFoodStage().
ConditionAttach() [1/2]
bool Edible_Base::ConditionAttach (EntityAI parent) inline private
Definition at line 23 of file CaninaBerry.c.
  {
    //if Barrel_ColorBase
    if (parent.IsInherited(Barrel_ColorBase))
    {
      Barrel_ColorBase barrel = Barrel_ColorBase.Cast(parent);
      if (barrel.IsOpen() && !barrel.FindAttachmentBySlotName("Nails") && !barrel.FindAttachmentBySlotName("OakBark") && !barrel.FindAttachmentBySlotName("BirchBark") && !barrel.FindAttachmentBySlotName("Lime") && !barrel.FindAttachmentBySlotName("Disinfectant") && !barrel.FindAttachmentBySlotName("Guts"))
        return true;
    }
    return false;
  }
ConditionAttach() [2/2]
bool Edible_Base::ConditionAttach (EntityAI parent) inline private
Definition at line 23 of file SambucusBerry.c.
  {
    //if Barrel_ColorBase
    if (parent.IsInherited(Barrel_ColorBase))
    {
      Barrel_ColorBase barrel = Barrel_ColorBase.Cast(parent);
      if (barrel.IsOpen() && !barrel.FindAttachmentBySlotName("Nails") && !barrel.FindAttachmentBySlotName("OakBark") && !barrel.FindAttachmentBySlotName("BirchBark") && !barrel.FindAttachmentBySlotName("Lime") && !barrel.FindAttachmentBySlotName("Disinfectant") && !barrel.FindAttachmentBySlotName("Guts"))
        return true;
    }
    return false;
  }
ConditionDetach() [1/2]
bool Edible_Base::ConditionDetach (EntityAI parent) inline private
Definition at line 37 of file CaninaBerry.c.
  {
    //if Barrel_ColorBase
    if (parent.IsInherited(Barrel_ColorBase))
    {
      Barrel_ColorBase barrel = Barrel_ColorBase.Cast(parent);
      if (!barrel.IsOpen())
        return false;
    }
    return true;
  }
ConditionDetach() [2/2]
bool Edible_Base::ConditionDetach (EntityAI parent) inline private
Definition at line 37 of file SambucusBerry.c.
  {
    //if Barrel_ColorBase
    if (parent.IsInherited(Barrel_ColorBase))
    {
      Barrel_ColorBase barrel = Barrel_ColorBase.Cast(parent);
      if (!barrel.IsOpen())
        return false;
    }
    return true;
  }
Consume()
bool Edible_Base::Consume (float amount, PlayerBase consumer) inline private
Definition at line 82 of file Edible_Base.c.
  {
    AddQuantity(-amount, false, false);
    OnConsume(amount, consumer);
    return true;
  }
References AddQuantity(), and OnConsume().
EEDelete()
override void Edible_Base::EEDelete (EntityAI parent) inline private
Definition at line 46 of file Edible_Base.c.
  {
    super.EEDelete(parent);
    RemoveAudio();
  }
References RemoveAudio().
EEInit()
override void Edible_Base::EEInit () inline private
Definition at line 39 of file Edible_Base.c.
  {
    super.EEInit();
    UpdateVisuals();
  }
References UpdateVisuals().
EEItemLocationChanged()
override void Edible_Base::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
disable sounds (from cooking)
check for DirectCooking slot name
Definition at line 53 of file Edible_Base.c.
  {
    super.EEItemLocationChanged(oldLoc, newLoc);
    if (oldLoc.GetType() == InventoryLocationType.ATTACHMENT || oldLoc.GetType() == InventoryLocationType.CARGO)
    {
      switch (oldLoc.GetParent().GetType())
      {
      case "FryingPan":
      case "Pot":
      case "Cauldron":
      case "SharpWoodenStick":
        MakeSoundsOnClient(false);
        break;
      }
      if (oldLoc.GetSlot() > -1 && InventorySlots.GetSlotName(oldLoc.GetSlot()).Contains(DIRECT_COOKING_SLOT_NAME))
        MakeSoundsOnClient(false);
    }
  }
References DIRECT_COOKING_SLOT_NAME, InventorySlots::GetSlotName(), and MakeSoundsOnClient().
GetCookingTime()
float Edible_Base::GetCookingTime () inline protected
Definition at line 429 of file Edible_Base.c.
  {
    return GetFoodStage().GetCookingTime();
  }
References GetFoodStage().
GetDebugActions()
override void Edible_Base::GetDebugActions (out TSelectableActionInfoArrayEx outputList) inline protected
Definition at line 681 of file Edible_Base.c.
  {
    super.GetDebugActions(outputList);
    if (HasFoodStage())
    {
      outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.FOOD_STAGE_PREV, "Food Stage Prev", FadeColors.WHITE));
      outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.FOOD_STAGE_NEXT, "Food Stage Next", FadeColors.WHITE));
    }
  }
References HasFoodStage(), and SAT_DEBUG_ACTION.
GetDebugText()
override string Edible_Base::GetDebugText () inline protected
Definition at line 718 of file Edible_Base.c.
  {
    string debug_output;
    debug_output = super.GetDebugText();
    debug_output += "m_CookedByMethod:" + m_CookedByMethod + "\n";
    debug_output += "m_MakeCookingSounds:" + m_MakeCookingSounds + "\n";
    return debug_output;
  }
References m_CookedByMethod, and m_MakeCookingSounds.
GetDecayDelta()
float Edible_Base::GetDecayDelta () inline protected
Definition at line 739 of file Edible_Base.c.
  {
    return m_DecayDelta;
  }
References m_DecayDelta.
GetDecayTimer()
float Edible_Base::GetDecayTimer () inline protected
Definition at line 734 of file Edible_Base.c.
  {
    return m_DecayTimer;
  }
References m_DecayTimer.
GetDisinfectQuantity()
override float Edible_Base::GetDisinfectQuantity (int system = 0, Param param1 = null) inline private
Definition at line 62 of file DisinfectantSpray.c.
  {
    return (GetQuantityMax() * 0.15);
  }
References GetQuantityMax().
GetFoodAgents()
static int Edible_Base::GetFoodAgents (ItemBase item, string classname = "", int food_stage = 0) inline static protected
Definition at line 309 of file Edible_Base.c.
  {
    Edible_Base food_item = Edible_Base.Cast(item);
    if (food_item && food_item.GetFoodStage())
      return FoodStage.GetAgents(food_item.GetFoodStage());
    else if (classname != "" && food_stage)
      return FoodStage.GetAgents(null, food_stage, classname);
    string class_path = string.Format("cfgVehicles %1 Nutrition", classname);
    return GetGame().ConfigGetInt(class_path + " agents");
  }
References GetGame().
Referenced by GetNutritionalProfile().
GetFoodDigestibility()
static float Edible_Base::GetFoodDigestibility (ItemBase item, string classname = "", int food_stage = 0) inline static protected
Definition at line 320 of file Edible_Base.c.
  {
    Edible_Base food_item = Edible_Base.Cast(item);
    if (food_item && food_item.GetFoodStage())
      return FoodStage.GetDigestibility(food_item.GetFoodStage());
    else if (classname != "" && food_stage)
      return FoodStage.GetDigestibility(null, food_stage, classname);
    string class_path = string.Format("cfgVehicles %1 Nutrition", classname);
    return GetGame().ConfigGetInt(class_path + " digestibility");
  }
References GetGame().
Referenced by GetNutritionalProfile().
GetFoodEnergy()
static float Edible_Base::GetFoodEnergy (ItemBase item, string classname = "", int food_stage = 0) inline static protected
Definition at line 264 of file Edible_Base.c.
  {
    Edible_Base food_item = Edible_Base.Cast(item);
    if (food_item && food_item.GetFoodStage())
      return FoodStage.GetEnergy(food_item.GetFoodStage());
    else if (classname != "" && food_stage)
      return FoodStage.GetEnergy(null, food_stage, classname);
    string class_path = string.Format("cfgVehicles %1 Nutrition", classname);
    return GetGame().ConfigGetFloat(class_path + " energy");
  }
References GetGame().
Referenced by GetNutritionalProfile().
GetFoodNutritionalIndex()
static float Edible_Base::GetFoodNutritionalIndex (ItemBase item, string classname = "", int food_stage = 0) inline static protected
Definition at line 286 of file Edible_Base.c.
  {
    Edible_Base food_item = Edible_Base.Cast(item);
    if (food_item && food_item.GetFoodStage())
      return FoodStage.GetNutritionalIndex(food_item.GetFoodStage());
    else if (classname != "" && food_stage)
      return FoodStage.GetNutritionalIndex(null, food_stage, classname);
    string class_path = string.Format("cfgVehicles %1 Nutrition", classname);
    return GetGame().ConfigGetFloat(class_path + " nutritionalIndex");
  }
References GetGame().
Referenced by GetNutritionalProfile().
GetFoodStage()
FoodStage Edible_Base::GetFoodStage () inline protected
Definition at line 222 of file Edible_Base.c.
  {
    return m_FoodStage;
  }
References m_FoodStage.
Referenced by CanChangeToNewStage(), ChangeFoodStage(), CAContinuousTimeCooking::Execute(), GetCookingTime(), GetFoodStageName(), GetFoodStageType(), GetNextFoodStageType(), IsFoodBaked(), IsFoodBoiled(), IsFoodBurned(), IsFoodDried(), IsFoodRaw(), IsFoodRotten(), OnStoreLoad(), OnStoreSave(), SetCookingTime(), CAContinuousTimeCooking::Setup(), and UpdateVisuals().
GetFoodStageName()
string Edible_Base::GetFoodStageName (FoodStageType food_stage_type) inline protected
Definition at line 404 of file Edible_Base.c.
  {
    return GetFoodStage().GetFoodStageName(food_stage_type);
  }
References GetFoodStage().
GetFoodStageType()
FoodStageType Edible_Base::GetFoodStageType () inline protected
Definition at line 339 of file Edible_Base.c.
  {
    return GetFoodStage().GetFoodStageType();
  }
References GetFoodStage().
Referenced by CanProcessDecay(), OnAction(), ProcessDecay(), and RefreshAudio().
GetFoodTotalVolume()
static float Edible_Base::GetFoodTotalVolume (ItemBase item, string classname = "", int food_stage = 0) inline static protected
Definition at line 252 of file Edible_Base.c.
  {
    Edible_Base food_item = Edible_Base.Cast(item);
    if (food_item && food_item.GetFoodStage())
      return FoodStage.GetFullnessIndex(food_item.GetFoodStage());
    else if (classname != "" && food_stage)
      return FoodStage.GetFullnessIndex(null, food_stage, classname);
    string class_path = string.Format("cfgVehicles %1 Nutrition", classname);
    return GetGame().ConfigGetFloat(class_path + " fullnessIndex");
  }
References GetGame().
Referenced by GetNutritionalProfile().
GetFoodToxicity()
static float Edible_Base::GetFoodToxicity (ItemBase item, string classname = "", int food_stage = 0) inline static protected
Definition at line 298 of file Edible_Base.c.
  {
    Edible_Base food_item = Edible_Base.Cast(item);
    if (food_item && food_item.GetFoodStage())
      return FoodStage.GetToxicity(food_item.GetFoodStage());
    else if (classname != "" && food_stage)
      return FoodStage.GetToxicity(null, food_stage, classname);
    string class_path = string.Format("cfgVehicles %1 Nutrition", classname);
    return GetGame().ConfigGetFloat(class_path + " toxicity");
  }
References GetGame().
Referenced by GetNutritionalProfile().
GetFoodWater()
static float Edible_Base::GetFoodWater (ItemBase item, string classname = "", int food_stage = 0) inline static protected
Definition at line 275 of file Edible_Base.c.
  {
    Edible_Base food_item = Edible_Base.Cast(item);
    if (food_item && food_item.GetFoodStage())
      return FoodStage.GetWater(food_item.GetFoodStage());
    else if (classname != "" && food_stage)
      return FoodStage.GetWater(null, food_stage, classname);
    string class_path = string.Format("cfgVehicles %1 Nutrition", classname);
    return GetGame().ConfigGetFloat(class_path + " water");
  }
References GetGame().
Referenced by GetNutritionalProfile().
GetLastDecayStage()
FoodStageType Edible_Base::GetLastDecayStage () inline protected
Definition at line 744 of file Edible_Base.c.
  {
    return m_LastDecayStage;
  }
References m_LastDecayStage.
GetNextFoodStageType()
FoodStageType Edible_Base::GetNextFoodStageType (CookingMethodType cooking_method) inline protected
Definition at line 399 of file Edible_Base.c.
  {
    return GetFoodStage().GetNextFoodStageType(cooking_method);
  }
References GetFoodStage().
Referenced by RefreshAudio().
GetNutritionalProfile()
static NutritionalProfile Edible_Base::GetNutritionalProfile (ItemBase item, string classname = "", int food_stage = 0) inline static protected
Definition at line 331 of file Edible_Base.c.
  {
    return new NutritionalProfile(GetFoodEnergy(item, classname, food_stage), GetFoodWater(item, classname, food_stage), GetFoodNutritionalIndex(item, classname, food_stage), GetFoodTotalVolume(item, classname, food_stage), GetFoodToxicity(item, classname, food_stage), GetFoodAgents(item, classname, food_stage), GetFoodDigestibility(item, classname, food_stage));
  }
References GetFoodAgents(), GetFoodDigestibility(), GetFoodEnergy(), GetFoodNutritionalIndex(), GetFoodTotalVolume(), GetFoodToxicity(), and GetFoodWater().
Referenced by AddToStomach().
HumanSteakMeat()
void Edible_Base::HumanSteakMeat () inline private
Definition at line 3 of file HumanSteakMeat.c.
  {
    InsertAgent(eAgents.BRAIN, 1);
  }
References InsertAgent().
InitItemVariables()
override void Edible_Base::InitItemVariables () inline private
Definition at line 4 of file DisinfectantSpray.c.
  {
    super.InitItemVariables();
    can_this_be_combined = true;
  }
References can_this_be_combined.
IsCorpse() [1/5]
override bool Edible_Base::IsCorpse () inline protected
Definition at line 233 of file Edible_Base.c.
  {
    return false;
  }
Referenced by ProcessDecay().
IsCorpse() [2/5]
override bool Edible_Base::IsCorpse () inline private
Definition at line 13 of file Carp.c.
  {
    return true;
  }
IsCorpse() [3/5]
override bool Edible_Base::IsCorpse () inline private
Definition at line 13 of file Chicken_ColorBase.c.
  {
    return true;
  }
IsCorpse() [4/5]
override bool Edible_Base::IsCorpse () inline private
Definition at line 13 of file Mackerel.c.
  {
    return true;
  }
IsCorpse() [5/5]
override bool Edible_Base::IsCorpse () inline private
Definition at line 13 of file Rabbit.c.
  {
    return true;
  }
IsFoodBaked()
bool Edible_Base::IsFoodBaked () inline protected
Definition at line 353 of file Edible_Base.c.
  {
    if (GetFoodStage())
      return GetFoodStage().IsFoodBaked();
    return false;
  }
References GetFoodStage().
IsFoodBoiled()
bool Edible_Base::IsFoodBoiled () inline protected
Definition at line 361 of file Edible_Base.c.
  {
    if (GetFoodStage())
      return GetFoodStage().IsFoodBoiled();
    return false;
  }
References GetFoodStage().
IsFoodBurned()
bool Edible_Base::IsFoodBurned () inline protected
Definition at line 377 of file Edible_Base.c.
  {
    if (GetFoodStage())
      return GetFoodStage().IsFoodBurned();
    return false;
  }
References GetFoodStage().
IsFoodDried()
bool Edible_Base::IsFoodDried () inline protected
Definition at line 369 of file Edible_Base.c.
  {
    if (GetFoodStage())
      return GetFoodStage().IsFoodDried();
    return false;
  }
References GetFoodStage().
IsFoodRaw()
bool Edible_Base::IsFoodRaw () inline protected
Definition at line 345 of file Edible_Base.c.
  {
    if (GetFoodStage())
      return GetFoodStage().IsFoodRaw();
    return false;
  }
References GetFoodStage().
IsFoodRotten()
bool Edible_Base::IsFoodRotten () inline protected
Definition at line 385 of file Edible_Base.c.
  {
    if (GetFoodStage())
      return GetFoodStage().IsFoodRotten();
    return false;
  }
References GetFoodStage().
IsFruit() [1/3]
override bool Edible_Base::IsFruit () inline protected
Definition at line 238 of file Edible_Base.c.
  {
    return false;
  }
Referenced by ProcessDecay().
IsFruit() [2/3]
override bool Edible_Base::IsFruit () inline private
Definition at line 13 of file CaninaBerry.c.
  {
    return true;
  }
IsFruit() [3/3]
override bool Edible_Base::IsFruit () inline private
Definition at line 13 of file SambucusBerry.c.
  {
    return true;
  }
IsMeat() [1/20]
override bool Edible_Base::IsMeat () inline protected
Definition at line 228 of file Edible_Base.c.
  {
    return false;
  }
Referenced by CAContinuousTimeCooking::Execute(), and ProcessDecay().
IsMeat() [2/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file BearSteakMeat.c.
  {
    return true;
  }
IsMeat() [3/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file Bitterlings.c.
  {
    return true;
  }
IsMeat() [4/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file BoarSteakMeat.c.
  {
    return true;
  }
IsMeat() [5/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file CarpFilletMeat.c.
  {
    return true;
  }
IsMeat() [6/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file ChickenBreastMeat.c.
  {
    return true;
  }
IsMeat() [7/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file CowSteakMeat.c.
  {
    return true;
  }
IsMeat() [8/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file DeerSteakMeat.c.
  {
    return true;
  }
IsMeat() [9/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file FoxSteakMeat.c.
  {
    return true;
  }
IsMeat() [10/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file GoatSteakMeat.c.
  {
    return true;
  }
IsMeat() [11/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 18 of file HumanSteakMeat.c.
  {
    return true;
  }
IsMeat() [12/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file Lard.c.
  {
    return true;
  }
IsMeat() [13/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file MackerelFilletMeat.c.
  {
    return true;
  }
IsMeat() [14/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file MouflonSteakMeat.c.
  {
    return true;
  }
IsMeat() [15/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file PigSteakMeat.c.
  {
    return true;
  }
IsMeat() [16/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file RabbitLegMeat.c.
  {
    return true;
  }
IsMeat() [17/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file Sardines.c.
  {
    return true;
  }
IsMeat() [18/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file SheepSteakMeat.c.
  {
    return true;
  }
IsMeat() [19/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file WolfSteakMeat.c.
  {
    return true;
  }
IsMeat() [20/20]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file Worm.c.
  {
    return true;
  }
IsMushroom()
override bool Edible_Base::IsMushroom () inline protected
Definition at line 243 of file Edible_Base.c.
  {
    return false;
  }
Referenced by ProcessDecay().
MakeSoundsOnClient()
void Edible_Base::MakeSoundsOnClient (bool soundstate, CookingMethodType cookingMethod = CookingMethodType.NONE) inline private
Definition at line 130 of file Edible_Base.c.
  {
    m_MakeCookingSounds = soundstate;
    m_CookedByMethod = cookingMethod;
    Synchronize();
  }
References m_CookedByMethod, m_MakeCookingSounds, and Synchronize().
Referenced by EEItemLocationChanged().
OnAction()
override bool Edible_Base::OnAction (int action_id, Man player, ParamsReadContext ctx) inline protected
Definition at line 692 of file Edible_Base.c.
  {
    super.OnAction(action_id, player, ctx);
    if (GetGame().IsServer())
    {
      if (action_id == EActions.FOOD_STAGE_PREV)
      {
        int food_stage_prev = GetFoodStageType() - 1;
        if (food_stage_prev <= 0)
          food_stage_prev = FoodStageType.COUNT - 1;
        ChangeFoodStage(food_stage_prev);
        return true;
      }
      else if (action_id == EActions.FOOD_STAGE_NEXT)
      {
        int food_stage_next = GetFoodStageType() + 1;
        if (food_stage_next >= FoodStageType.COUNT)
          food_stage_next = FoodStageType.RAW;
        ChangeFoodStage(food_stage_next);
        return true;
      }
    }
    return false;
  }
References ChangeFoodStage(), GetFoodStageType(), and GetGame().
OnConsume() [1/3]
void Edible_Base::OnConsume (float amount, PlayerBase consumer) private
Referenced by Consume().
OnConsume() [2/3]
override void Edible_Base::OnConsume (float amount, PlayerBase consumer) inline private
Definition at line 11 of file CharcoalTablets.c.
  {
    if (!consumer.GetModifiersManager().IsModifierActive(eModifiers.MDF_CHARCOAL))
      consumer.GetModifiersManager().ActivateModifier(eModifiers.MDF_CHARCOAL);
  }
OnConsume() [3/3]
override void Edible_Base::OnConsume (float amount, PlayerBase consumer) inline private
Definition at line 11 of file PainkillerTablets.c.
  {
    if (consumer.GetModifiersManager().IsModifierActive(eModifiers.MDF_PAINKILLERS)) // effectively resets the timer
      consumer.GetModifiersManager().DeactivateModifier(eModifiers.MDF_PAINKILLERS, false);
    consumer.GetModifiersManager().ActivateModifier(eModifiers.MDF_PAINKILLERS);
  }
OnStoreLoad()
override bool Edible_Base::OnStoreLoad (ParamsReadContext ctx, int version) inline protected
Definition at line 186 of file Edible_Base.c.
  {
    if (!super.OnStoreLoad(ctx, version))
      return false;
    if (GetFoodStage())
    {
      if (!GetFoodStage().OnStoreLoad(ctx, version))
        return false;
    }
    if (version >= 115)
    {
      if (!ctx.Read(m_DecayTimer))
      {
        m_DecayTimer = 0.0;
        return false;
      }
      if (!ctx.Read(m_LastDecayStage))
      {
        m_LastDecayStage = FoodStageType.NONE;
        return false;
      }
    }
    return true;
  }
References GetFoodStage(), m_DecayTimer, m_LastDecayStage, and OnStoreLoad().
Referenced by OnStoreLoad().
OnStoreSave()
override void Edible_Base::OnStoreSave (ParamsWriteContext ctx) inline protected
Definition at line 174 of file Edible_Base.c.
  {
    super.OnStoreSave(ctx);
    if (GetFoodStage())
      GetFoodStage().OnStoreSave(ctx);
    // food decay
    ctx.Write(m_DecayTimer);
    ctx.Write(m_LastDecayStage);
  }
References GetFoodStage(), m_DecayTimer, and m_LastDecayStage.
OnVariablesSynchronized()
override void Edible_Base::OnVariablesSynchronized () inline private
Definition at line 114 of file Edible_Base.c.
  {
    super.OnVariablesSynchronized();
    UpdateVisuals();
    //update audio
    if (m_MakeCookingSounds)
      RefreshAudio();
    else
      RemoveAudio();
  }
References m_MakeCookingSounds, RefreshAudio(), RemoveAudio(), and UpdateVisuals().
ProcessDecay()
override void Edible_Base::ProcessDecay (float delta, bool hasRootAsPlayer) inline protected
Definition at line 503 of file Edible_Base.c.
  {
    delta *= DayZGame.Cast(GetGame()).GetFoodDecayModifier();
    m_DecayDelta += (1 + (1 - GetHealth01("", "")));
    if (hasRootAsPlayer)
      m_DecayDelta += GameConstants.DECAY_RATE_ON_PLAYER;
    /*Print( "-------------------------" );
      Print( this );
      Print( m_DecayTimer );
      Print( m_DecayDelta );
      Print( m_LastDecayStage );*/
    if (IsFruit() || IsMushroom())
    {
      // fruit, vegetables and mushrooms
      if (m_LastDecayStage != GetFoodStageType())
      {
        switch (GetFoodStageType())
        {
        case FoodStageType.RAW:
          m_DecayTimer = (GameConstants.DECAY_FOOD_RAW_FRVG + (Math.RandomFloat01() * (GameConstants.DECAY_FOOD_RAW_FRVG * (GameConstants.DECAY_TIMER_RANDOM_PERCENTAGE / 100.0))));
          m_LastDecayStage = FoodStageType.RAW;
          break;
        case FoodStageType.BOILED:
          m_DecayTimer = (GameConstants.DECAY_FOOD_BOILED_FRVG + (Math.RandomFloat01() * (GameConstants.DECAY_FOOD_BOILED_FRVG * (GameConstants.DECAY_TIMER_RANDOM_PERCENTAGE / 100.0))));
          m_LastDecayStage = FoodStageType.BOILED;
          break;
        case FoodStageType.BAKED:
          m_DecayTimer = (GameConstants.DECAY_FOOD_BAKED_FRVG + (Math.RandomFloat01() * (GameConstants.DECAY_FOOD_BAKED_FRVG * (GameConstants.DECAY_TIMER_RANDOM_PERCENTAGE / 100.0))));
          m_LastDecayStage = FoodStageType.BAKED;
          break;
        case FoodStageType.DRIED:
        case FoodStageType.BURNED:
        case FoodStageType.ROTTEN:
        default:
          m_DecayTimer = -1;
          m_LastDecayStage = FoodStageType.NONE;
          return;
        }
        //m_DecayTimer = m_DecayTimer / 1000.0;
      }
      m_DecayTimer -= (delta * m_DecayDelta);
      if (m_DecayTimer <= 0)
      {
        if (m_LastDecayStage != FoodStageType.NONE)
        {
          // switch to decayed stage
          if ((m_LastDecayStage == FoodStageType.BOILED) || (m_LastDecayStage == FoodStageType.BAKED))
            ChangeFoodStage(FoodStageType.ROTTEN);
          if (m_LastDecayStage == FoodStageType.RAW)
          {
            int rng = Math.RandomIntInclusive(0, 100);
            if (rng > GameConstants.DECAY_FOOD_FRVG_DRIED_CHANCE)
              ChangeFoodStage(FoodStageType.ROTTEN);
            else
            {
              if (CanChangeToNewStage(FoodStageType.DRIED))
                ChangeFoodStage(FoodStageType.DRIED);
              else
                ChangeFoodStage(FoodStageType.ROTTEN);
            }
          }
        }
      }
    }
    else if (IsMeat())
    {
      // meat
      if (m_LastDecayStage != GetFoodStageType())
      {
        switch (GetFoodStageType())
        {
        case FoodStageType.RAW:
          m_DecayTimer = (GameConstants.DECAY_FOOD_RAW_MEAT + (Math.RandomFloat01() * (GameConstants.DECAY_FOOD_RAW_MEAT * (GameConstants.DECAY_TIMER_RANDOM_PERCENTAGE / 100.0))));
          m_LastDecayStage = FoodStageType.RAW;
          break;
        case FoodStageType.BOILED:
          m_DecayTimer = (GameConstants.DECAY_FOOD_BOILED_MEAT + (Math.RandomFloat01() * (GameConstants.DECAY_FOOD_BOILED_MEAT * (GameConstants.DECAY_TIMER_RANDOM_PERCENTAGE / 100.0))));
          m_LastDecayStage = FoodStageType.BOILED;
          break;
        case FoodStageType.BAKED:
          m_DecayTimer = (GameConstants.DECAY_FOOD_BAKED_MEAT + (Math.RandomFloat01() * (GameConstants.DECAY_FOOD_BAKED_MEAT * (GameConstants.DECAY_TIMER_RANDOM_PERCENTAGE / 100.0))));
          m_LastDecayStage = FoodStageType.BAKED;
          break;
        case FoodStageType.DRIED:
          m_DecayTimer = (GameConstants.DECAY_FOOD_DRIED_MEAT + (Math.RandomFloat01() * (GameConstants.DECAY_FOOD_DRIED_MEAT * (GameConstants.DECAY_TIMER_RANDOM_PERCENTAGE / 100.0))));
          m_LastDecayStage = FoodStageType.DRIED;
          break;
        case FoodStageType.BURNED:
        case FoodStageType.ROTTEN:
        default:
          m_DecayTimer = -1;
          m_LastDecayStage = FoodStageType.NONE;
          return;
        }
      }
      m_DecayTimer -= (delta * m_DecayDelta);
      if (m_DecayTimer <= 0)
      {
        if (m_LastDecayStage != FoodStageType.NONE)
        {
          // switch to decayed stage
          if ((m_LastDecayStage == FoodStageType.DRIED) || (m_LastDecayStage == FoodStageType.RAW) || (m_LastDecayStage == FoodStageType.BOILED) || (m_LastDecayStage == FoodStageType.BAKED))
            ChangeFoodStage(FoodStageType.ROTTEN);
        }
      }
    }
    else if (IsCorpse())
    {
      // corpse
      if (m_LastDecayStage != GetFoodStageType())
      {
        switch (GetFoodStageType())
        {
        case FoodStageType.RAW:
          m_DecayTimer = (GameConstants.DECAY_FOOD_RAW_CORPSE + (Math.RandomFloat01() * (GameConstants.DECAY_FOOD_RAW_CORPSE * (GameConstants.DECAY_TIMER_RANDOM_PERCENTAGE / 100.0))));
          m_LastDecayStage = FoodStageType.RAW;
          break;
        case FoodStageType.BURNED:
        case FoodStageType.ROTTEN:
        default:
          m_DecayTimer = -1;
          m_LastDecayStage = FoodStageType.NONE;
          return;
        }
      }
      m_DecayTimer -= (delta * m_DecayDelta);
      if (m_DecayTimer <= 0)
      {
        if (m_LastDecayStage != FoodStageType.NONE)
        {
          // switch to decayed stage
          if ((m_LastDecayStage == FoodStageType.DRIED) || (m_LastDecayStage == FoodStageType.RAW) || (m_LastDecayStage == FoodStageType.BOILED) || (m_LastDecayStage == FoodStageType.BAKED))
            ChangeFoodStage(FoodStageType.ROTTEN);
        }
      }
    }
    else
    {
      // opened cans
      m_DecayTimer -= (delta * m_DecayDelta);
      if ((m_DecayTimer <= 0) && (m_LastDecayStage == FoodStageType.NONE))
      {
        m_DecayTimer = (GameConstants.DECAY_FOOD_CAN_OPEN + (Math.RandomFloat01() * (GameConstants.DECAY_FOOD_DRIED_MEAT * (GameConstants.DECAY_TIMER_RANDOM_PERCENTAGE / 100.0))));
        m_LastDecayStage = FoodStageType.RAW;
        //m_DecayTimer = m_DecayTimer / 1000.0;
      }
      else
      {
        if (m_DecayTimer <= 0)
        {
          InsertAgent(eAgents.FOOD_POISON, 1);
          m_DecayTimer = -1;
        }
      }
    }
    m_DecayDelta = 0.0;
  }
References CanChangeToNewStage(), ChangeFoodStage(), GameConstants::DECAY_FOOD_BAKED_FRVG, GameConstants::DECAY_FOOD_BAKED_MEAT, GameConstants::DECAY_FOOD_BOILED_FRVG, GameConstants::DECAY_FOOD_BOILED_MEAT, GameConstants::DECAY_FOOD_CAN_OPEN, GameConstants::DECAY_FOOD_DRIED_MEAT, GameConstants::DECAY_FOOD_FRVG_DRIED_CHANCE, GameConstants::DECAY_FOOD_RAW_CORPSE, GameConstants::DECAY_FOOD_RAW_FRVG, GameConstants::DECAY_FOOD_RAW_MEAT, GameConstants::DECAY_RATE_ON_PLAYER, GameConstants::DECAY_TIMER_RANDOM_PERCENTAGE, GetFoodStageType(), GetGame(), InsertAgent(), IsCorpse(), IsFruit(), IsMeat(), IsMushroom(), m_DecayDelta, m_DecayTimer, m_LastDecayStage, Math::RandomFloat01(), and Math::RandomIntInclusive().
RefreshAudio()
void Edible_Base::RefreshAudio () inline protected
Definition at line 138 of file Edible_Base.c.
  {
    string soundName = "";
    FoodStageType nextFoodState = GetNextFoodStageType(m_CookedByMethod);
    switch (GetFoodStageType())
    {
    case FoodStageType.RAW:
      soundName = SOUND_BAKING_START;
      if (nextFoodState == FoodStageType.BOILED)
        soundName = "";
      break;
    case FoodStageType.BAKED:
      soundName = SOUND_BAKING_DONE;
      break;
    case FoodStageType.BURNED:
      soundName = SOUND_BURNING_DONE;
      break;
    default:
      soundName = "";
      break;
    }
    SoundCookingStart(soundName);
  }
References GetFoodStageType(), GetNextFoodStageType(), m_CookedByMethod, SOUND_BAKING_DONE, SOUND_BAKING_START, SOUND_BURNING_DONE, and SoundCookingStart().
Referenced by OnVariablesSynchronized().
RemoveAudio()
void Edible_Base::RemoveAudio () inline protected
Definition at line 165 of file Edible_Base.c.
  {
    m_MakeCookingSounds = false;
    SoundCookingStop();
  }
References m_MakeCookingSounds, and SoundCookingStop().
Referenced by EEDelete(), and OnVariablesSynchronized().
ReplaceEdibleWithNew()
void Edible_Base::ReplaceEdibleWithNew (string typeName) inline protected
Definition at line 443 of file Edible_Base.c.
  {
    PlayerBase player = PlayerBase.Cast(GetHierarchyRootPlayer());
    if (player)
    {
      ReplaceEdibleWithNewLambda lambda = new ReplaceEdibleWithNewLambda(this, typeName, player);
      player.ServerReplaceItemInHandsWithNew(lambda);
    }
    else
      Error("ReplaceEdibleWithNew - cannot use edible without player");
  }
References Error(), and ReplaceEdibleWithNewLambda().
Referenced by BakedBeansCan::Open(), PeachesCan::Open(), SardinesCan::Open(), SpaghettiCan::Open(), TacticalBaconCan::Open(), TunaCan::Open(), DogFoodCan::Open(), CatFoodCan::Open(), PorkCan::Open(), Lunchmeat::Open(), UnknownFoodCan::Open(), Pajka::Open(), Pate::Open(), and BrisketSpread::Open().
SetActions() [1/28]
override void Edible_Base::SetActions () inline protected
Definition at line 455 of file Edible_Base.c.
  {
    super.SetActions();
    AddAction(ActionAttach);
    AddAction(ActionDetach);
  }
References ActionDetach(), and AddAction().
SetActions() [2/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file BearSteakMeat.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetActions() [3/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file Bitterlings.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
  }
References AddAction().
SetActions() [4/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file BoarSteakMeat.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetActions() [5/28]
override void Edible_Base::SetActions () inline private
Definition at line 7 of file BoxCerealCrunchin.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEat);
  }
References AddAction().
SetActions() [6/28]
override void Edible_Base::SetActions () inline private
Definition at line 7 of file Candycane_Colorbase.c.
  {
    super.SetActions();
    AddAction(ActionEat);
    AddAction(ActionForceFeed);
  }
References AddAction().
SetActions() [7/28]
override void Edible_Base::SetActions () inline private
Definition at line 51 of file CaninaBerry.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEat);
  }
References AddAction().
SetActions() [8/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file CarpFilletMeat.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetActions() [9/28]
override void Edible_Base::SetActions () inline private
Definition at line 3 of file CharcoalTablets.c.
  {
    super.SetActions();
    AddAction(ActionForceConsumeSingle);
    AddAction(ActionEatTabletFromWrapper);
  }
References AddAction().
SetActions() [10/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file ChickenBreastMeat.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetActions() [11/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file CowSteakMeat.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetActions() [12/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file DeerSteakMeat.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetActions() [13/28]
override void Edible_Base::SetActions () inline private
Definition at line 67 of file DisinfectantSpray.c.
  {
    super.SetActions();
    AddAction(ActionDisinfectTarget);
    AddAction(ActionDisinfectSelf);;
    AddAction(ActionDisinfectPlant);
    AddAction(ActionWashHandsItemContinuous);
    //AddAction(ActionForceDrinkDisinfectant);
    //AddAction(ActionDrinkDisinfectant);
  }
References ActionDisinfectSelf(), and AddAction().
SetActions() [14/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file FoxSteakMeat.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetActions() [15/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file GoatSteakMeat.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetActions() [16/28]
override void Edible_Base::SetActions () inline private
Definition at line 55 of file Guts.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatBig);
  }
References AddAction().
SetActions() [17/28]
override void Edible_Base::SetActions () inline private
Definition at line 28 of file HumanSteakMeat.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetActions() [18/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file Lard.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetActions() [19/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file MackerelFilletMeat.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetActions() [20/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file MouflonSteakMeat.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetActions() [21/28]
override void Edible_Base::SetActions () inline private
Definition at line 3 of file PainkillerTablets.c.
  {
    super.SetActions();
    AddAction(ActionForceConsumeSingle);
    AddAction(ActionEatTabletFromWrapper);
  }
References AddAction().
SetActions() [22/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file PigSteakMeat.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetActions() [23/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file RabbitLegMeat.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetActions() [24/28]
override void Edible_Base::SetActions () inline private
Definition at line 51 of file SambucusBerry.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEat);
  }
References AddAction().
SetActions() [25/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file Sardines.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
  }
References AddAction().
SetActions() [26/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file SheepSteakMeat.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetActions() [27/28]
override void Edible_Base::SetActions () inline private
Definition at line 55 of file SmallGuts.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatBig);
  }
References AddAction().
SetActions() [28/28]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file WolfSteakMeat.c.
  {
    super.SetActions();
    AddAction(ActionForceFeed);
    AddAction(ActionEatMeat);
    AddAction(ActionCreateIndoorFireplace);
    AddAction(ActionCreateIndoorOven);
  }
References AddAction().
SetCookingTime()
void Edible_Base::SetCookingTime (float time) inline protected
Definition at line 434 of file Edible_Base.c.
  {
    GetFoodStage().SetCookingTime(time);
    //synchronize when calling on server
    Synchronize();
  }
References GetFoodStage(), and Synchronize().
SoundCookingStart()
void Edible_Base::SoundCookingStart (string sound_name) inline protected
Definition at line 463 of file Edible_Base.c.
  {
#ifndef SERVER
    if (m_SoundPlaying != sound_name)
    {
      SoundCookingStop();
      m_SoundEffectCooking = SEffectManager.PlaySound(sound_name, GetPosition(), 0, 0, true);
      m_SoundPlaying = sound_name;
    }
#endif
  }
References GetPosition, m_SoundEffectCooking, m_SoundPlaying, SEffectManager::PlaySound(), and SoundCookingStop().
Referenced by RefreshAudio().
SoundCookingStop()
void Edible_Base::SoundCookingStop () inline protected
Definition at line 476 of file Edible_Base.c.
  {
#ifndef SERVER
    if (m_SoundEffectCooking)
    {
      m_SoundEffectCooking.Stop();
      m_SoundEffectCooking = null;
      m_SoundPlaying = "";
    }
#endif
  }
References m_SoundEffectCooking, m_SoundPlaying, and EffectSound::Stop().
Referenced by RemoveAudio(), and SoundCookingStart().
Synchronize()
void Edible_Base::Synchronize () inline private
Definition at line 106 of file Edible_Base.c.
  {
    SetSynchDirty();
    if (GetGame().IsMultiplayer())
      UpdateVisuals();
  }
References GetGame(), and UpdateVisuals().
Referenced by AfterStoreLoad(), MakeSoundsOnClient(), and SetCookingTime().
TransferFoodStage()
void Edible_Base::TransferFoodStage (notnull Edible_Base source) inline protected
Definition at line 415 of file Edible_Base.c.
  {
    if (!source.HasFoodStage())
      return;
    m_LastDecayStage = source.GetLastDecayStage();
    ChangeFoodStage(source.GetFoodStage().GetFoodStageType());
    m_DecayTimer = source.GetDecayTimer();
    m_DecayDelta = source.GetDecayDelta();
  }
References ChangeFoodStage(), m_DecayDelta, m_DecayTimer, and m_LastDecayStage.
UpdateVisuals()
void Edible_Base::UpdateVisuals () inline private
Definition at line 76 of file Edible_Base.c.
  {
    if (GetFoodStage())
      GetFoodStage().UpdateVisuals();
  }
References GetFoodStage().
Referenced by EEInit(), OnVariablesSynchronized(), and Synchronize().
Member Data Documentation
DIRECT_COOKING_SLOT_NAME
const string Edible_Base::DIRECT_COOKING_SLOT_NAME = "DirectCooking" private
Definition at line 3 of file Edible_Base.c.
Referenced by EEItemLocationChanged().
m_CookedByMethod
CookingMethodType Edible_Base::m_CookedByMethod private
Definition at line 18 of file Edible_Base.c.
Referenced by Edible_Base(), GetDebugText(), MakeSoundsOnClient(), and RefreshAudio().
m_DecayDelta
float Edible_Base::m_DecayDelta = 0.0 protected
Definition at line 15 of file Edible_Base.c.
Referenced by GetDecayDelta(), ProcessDecay(), and TransferFoodStage().
m_DecayTimer
float Edible_Base::m_DecayTimer protected
Definition at line 14 of file Edible_Base.c.
Referenced by GetDecayTimer(), OnStoreLoad(), OnStoreSave(), ProcessDecay(), and TransferFoodStage().
m_FoodStage
ref FoodStage Edible_Base::m_FoodStage protected
Definition at line 13 of file Edible_Base.c.
Referenced by Edible_Base(), and GetFoodStage().
m_LastDecayStage
FoodStageType Edible_Base::m_LastDecayStage = FoodStageType.NONE protected
Definition at line 16 of file Edible_Base.c.
Referenced by GetLastDecayStage(), OnStoreLoad(), OnStoreSave(), ProcessDecay(), and TransferFoodStage().
m_MakeCookingSounds
bool Edible_Base::m_MakeCookingSounds protected
Definition at line 9 of file Edible_Base.c.
Referenced by GetDebugText(), MakeSoundsOnClient(), OnVariablesSynchronized(), and RemoveAudio().
m_SoundCooking
SoundOnVehicle Edible_Base::m_SoundCooking protected
Definition at line 10 of file Edible_Base.c.
m_SoundEffectCooking
EffectSound Edible_Base::m_SoundEffectCooking protected
DEPRECATED.
Definition at line 11 of file Edible_Base.c.
Referenced by SoundCookingStart(), and SoundCookingStop().
m_SoundPlaying
string Edible_Base::m_SoundPlaying protected
Definition at line 12 of file Edible_Base.c.
Referenced by Edible_Base(), SoundCookingStart(), and SoundCookingStop().
SOUND_BAKING_DONE
const string Edible_Base::SOUND_BAKING_DONE = "Baking_Done_SoundSet" private
Definition at line 6 of file Edible_Base.c.
Referenced by RefreshAudio().
SOUND_BAKING_START
const string Edible_Base::SOUND_BAKING_START = "Baking_SoundSet" private
Definition at line 5 of file Edible_Base.c.
Referenced by RefreshAudio().
SOUND_BURNING_DONE
const string Edible_Base::SOUND_BURNING_DONE = "Food_Burning_SoundSet" private
Definition at line 7 of file Edible_Base.c.
Referenced by RefreshAudio().
The documentation for this class was generated from the following files:
scripts/4_World/Entities/ItemBase/Edible_Base.c
scripts/4_World/Entities/ItemBase/Edible_Base/BearSteakMeat.c
scripts/4_World/Entities/ItemBase/Edible_Base/Bitterlings.c
scripts/4_World/Entities/ItemBase/Edible_Base/BoarSteakMeat.c
scripts/4_World/Entities/ItemBase/Edible_Base/BoxCerealCrunchin.c
scripts/4_World/Entities/ItemBase/Edible_Base/Candycane_Colorbase.c
scripts/4_World/Entities/ItemBase/Edible_Base/CaninaBerry.c
scripts/4_World/Entities/ItemBase/Edible_Base/Carp.c
scripts/4_World/Entities/ItemBase/Edible_Base/CarpFilletMeat.c
scripts/4_World/Entities/ItemBase/Edible_Base/CharcoalTablets.c
scripts/4_World/Entities/ItemBase/Edible_Base/Chicken_ColorBase.c
scripts/4_World/Entities/ItemBase/Edible_Base/ChickenBreastMeat.c
scripts/4_World/Entities/ItemBase/Edible_Base/CowSteakMeat.c
scripts/4_World/Entities/ItemBase/Edible_Base/DeerSteakMeat.c
scripts/4_World/Entities/ItemBase/Edible_Base/DisinfectantSpray.c
scripts/4_World/Entities/ItemBase/Edible_Base/FoxSteakMeat.c
scripts/4_World/Entities/ItemBase/Edible_Base/GoatSteakMeat.c
scripts/4_World/Entities/ItemBase/Edible_Base/Guts.c
scripts/4_World/Entities/ItemBase/Edible_Base/HumanSteakMeat.c
scripts/4_World/Entities/ItemBase/Edible_Base/Lard.c
scripts/4_World/Entities/ItemBase/Edible_Base/Mackerel.c
scripts/4_World/Entities/ItemBase/Edible_Base/MackerelFilletMeat.c
scripts/4_World/Entities/ItemBase/Edible_Base/MouflonSteakMeat.c
scripts/4_World/Entities/ItemBase/Edible_Base/PainkillerTablets.c
scripts/4_World/Entities/ItemBase/Edible_Base/PigSteakMeat.c
scripts/4_World/Entities/ItemBase/Edible_Base/Rabbit.c
scripts/4_World/Entities/ItemBase/Edible_Base/RabbitLegMeat.c
scripts/4_World/Entities/ItemBase/Edible_Base/SambucusBerry.c
scripts/4_World/Entities/ItemBase/Edible_Base/Sardines.c
scripts/4_World/Entities/ItemBase/Edible_Base/SheepSteakMeat.c
scripts/4_World/Entities/ItemBase/Edible_Base/SmallGuts.c
scripts/4_World/Entities/ItemBase/Edible_Base/WolfSteakMeat.c
scripts/4_World/Entities/ItemBase/Edible_Base/Worm.c