DayZ: Bolt_Base Class Reference
Bolt_Base Class Reference
Private Member Functions
override bool IsInventoryVisible ()
override bool CanBeActionTarget ()
override void EEParentedTo (EntityAI parent)
override void EEParentedFrom (EntityAI parent)
Private Member Functions inherited from Ammunition_Base
float GetWeightSpecialized (bool forceRecalc=false)
override void SetQuantityToMinimum ()
override void SetFromProjectile (ProjectileStoppedInfo info)
Detailed Description
Definition at line 88 of file AmmunitionPiles.c.
Member Function Documentation
CanBeActionTarget()
override bool Bolt_Base::CanBeActionTarget () inline private
Definition at line 96 of file AmmunitionPiles.c.
  {
    if (super.CanBeActionTarget())
    {
      EntityAI parent = EntityAI.Cast(GetParent());
      if (parent)
        return !parent.IsManagingArrows();
    }
    return true;
  }
References GetParent().
Referenced by IsInventoryVisible().
EEParentedFrom()
override void Bolt_Base::EEParentedFrom (EntityAI parent) inline private
Definition at line 117 of file AmmunitionPiles.c.
  {
    if (!parent)
      return;
    ArrowManagerBase arrowManager = parent.GetArrowManager();
    if (arrowManager)
      arrowManager.RemoveArrow(this);
  }
EEParentedTo()
override void Bolt_Base::EEParentedTo (EntityAI parent) inline private
Definition at line 107 of file AmmunitionPiles.c.
  {
    if (!parent)
      return;
    ArrowManagerBase arrowManager = parent.GetArrowManager();
    if (arrowManager)
      arrowManager.AddArrow(this);
  }
IsInventoryVisible()
override bool Bolt_Base::IsInventoryVisible () inline private
omitted super call is intended
Definition at line 90 of file AmmunitionPiles.c.
  {
    return CanBeActionTarget();
  }
References CanBeActionTarget().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Magazine/AmmunitionPiles.c