DayZ: ScriptInvoker Class Reference
ScriptInvoker Class Reference
ScriptInvoker Class provide list of callbacks
usage:
Private Member Functions
proto void Invoke (void param1=NULL, void param2=NULL, void param3=NULL, void param4=NULL, void param5=NULL, void param6=NULL, void param7=NULL, void param8=NULL, void param9=NULL)
invoke call on all inserted methods with given arguments
proto bool Insert (func fn, int flags=EScriptInvokerInsertFlags.IMMEDIATE)
insert method to list
proto bool Remove (func fn, int flags=EScriptInvokerRemoveFlags.ALL)
remove specific call from list
proto int Count (func fn)
count how many times this fn is actively present in the Invoker
proto native void Clear ()
remove all calls from list
Detailed Description
ScriptInvoker Class provide list of callbacks
usage:
class Player
{
  ref ScriptInvoker m_DeathInvoker  = new ScriptInvoker();
  void OnKilled()
  {
    m_DeathInvoker.Invoke(this);
  }
}
void LogPlayerDeath(p)
{
  Print("RIP " + p);
}
class Game
{
  void RemovePlayer(Player p)
  {
  }
  void GameOver()
  {
  }
}
void OnPlayerSpaned(Player p)
{
  Game game = GetGame();
  p.m_DeathInvoker.Insert(LogPlayerDeath);
  p.m_DeathInvoker.Insert(game.RemovePlayer);
  p.m_DeathInvoker.Insert(game.GameOver);
}
Definition at line 115 of file tools.c.
Member Function Documentation
Clear()
proto native void ScriptInvoker::Clear () private
remove all calls from list
Referenced by ConstructionActionData::ConstructionActionData(), and CraftingManager::CraftingManager().
Count()
proto int ScriptInvoker::Count (func fn) private
count how many times this fn is actively present in the Invoker
Insert()
proto bool ScriptInvoker::Insert (func fn, int flags = EScriptInvokerInsertFlags.IMMEDIATE) private
insert method to list
Referenced by ConstructionActionData::ConstructionActionData(), and CraftingManager::CraftingManager().
Invoke()
proto void ScriptInvoker::Invoke (void param1 = NULL, void param2 = NULL, void param3 = NULL, void param4 = NULL, void param5 = NULL, void param6 = NULL, void param7 = NULL, void param8 = NULL, void param9 = NULL) private
invoke call on all inserted methods with given arguments
Remove()
proto bool ScriptInvoker::Remove (func fn, int flags = EScriptInvokerRemoveFlags.ALL) private
remove specific call from list
The documentation for this class was generated from the following file:
scripts/2_GameLib/tools.c