DayZ: ParticleEvents Class Reference
ParticleEvents Class Reference
Invokers for ParticleBase events, called from events.
Private Attributes
ref ScriptInvoker Event_OnParticleStart = new ScriptInvoker()
Called when particle starts playing.
ref ScriptInvoker Event_OnParticleStop = new ScriptInvoker()
Called when particle stops playing.
ref ScriptInvoker Event_OnParticleReset = new ScriptInvoker()
Called when particle is reset.
ref ScriptInvoker Event_OnParticleEnd = new ScriptInvoker()
Called when particle ends.
ref ScriptInvoker Event_OnParticleParented = new ScriptInvoker()
Called when particle receives a parent.
ref ScriptInvoker Event_OnParticleUnParented = new ScriptInvoker()
Called when particle is orphaned.
Detailed Description
Invokers for ParticleBase events, called from events.
void EnableOnEndPrint(ParticleBase psrc)
{
  psrc.GetEvents().Event_OnParticleEnd.Insert(PrintParticleEnded);
}
void PrintParticleEnded(ParticleBase psrc)
{
  Print(string.Format("%1 ended.", psrc.GetDebugNameNative());
}
Definition at line 15 of file ParticleBase.c.
Member Data Documentation
Event_OnParticleEnd
ref ScriptInvoker ParticleEvents::Event_OnParticleEnd = new ScriptInvoker() private
Called when particle ends.
Note
Particle: Called when lifetime is over and there are no emitors active anymore
ParticleSource: Called when particle ends naturally or after the particle is stopped and there are no emitors active anymore
Warning
Looped never ends naturally and need to be stopped
Definition at line 41 of file ParticleBase.c.
Referenced by OnParticleEnd().
Event_OnParticleParented
ref ScriptInvoker ParticleEvents::Event_OnParticleParented = new ScriptInvoker() private
Called when particle receives a parent.
Note
Particle: Not present
Definition at line 46 of file ParticleBase.c.
Referenced by OnParticleParented().
Event_OnParticleReset
ref ScriptInvoker ParticleEvents::Event_OnParticleReset = new ScriptInvoker() private
Called when particle is reset.
Note
Particle: Not present, there is no reset functionality
ParticleSource: Called when ResetParticleNative is successful
Definition at line 34 of file ParticleBase.c.
Referenced by OnParticleReset().
Event_OnParticleStart
ref ScriptInvoker ParticleEvents::Event_OnParticleStart = new ScriptInvoker() private
Called when particle starts playing.
Note
Particle: Called when any Play method has been called
ParticleSource: Called when PlayParticleNative is successful
Definition at line 22 of file ParticleBase.c.
Referenced by OnParticleStart().
Event_OnParticleStop
ref ScriptInvoker ParticleEvents::Event_OnParticleStop = new ScriptInvoker() private
Called when particle stops playing.
Note
Particle: Called when any Stop method has been called or when lifetime is over
ParticleSource: Called when StopParticleNative is successful, when the particle ends and when the particle is destroyed while it is playing
Definition at line 28 of file ParticleBase.c.
Referenced by OnParticleStop().
Event_OnParticleUnParented
ref ScriptInvoker ParticleEvents::Event_OnParticleUnParented = new ScriptInvoker() private
Called when particle is orphaned.
Note
Particle: Not present
Definition at line 51 of file ParticleBase.c.
Referenced by OnParticleUnParented().
The documentation for this class was generated from the following file:
scripts/3_Game/Particles/ParticleBase.c