DayZ: scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionPushCar.c File Reference
ActionPushCar.c File Reference
Classes
class ActionPushCarDataReceiveData
class CAContinuousRepeatPushCar
class ActionPushCar
Functions
override void CreateActionComponent ()
override void ProgressActionComponent ()
override void EndActionComponent ()
void ApplyForce (ActionPushCarData actionData)
Variables
ActionPushCarDataReceiveData m_PushDirection = -1
int m_EndType = 0
float m_HorizontalDirectionRandom = 1.0
float m_VerticalDirectionRandom = 1.0
vector m_Origin = "0 0 0"
bool m_NeedUpdate
CarScript m_Car
CAContinuousRepeatPushCar PUSH_FORCE_IMPULSE_INCREMENT = 200.0
ActionPushCarData m_ActionDataPushCar
Function Documentation
ApplyForce()
void ApplyForce (ActionPushCarData actionData) protected
Definition at line 101 of file ActionPushCar.c.
  {
    CarScript car = actionData.m_Car;
    actionData.m_HorizontalDirectionRandom = Math.RandomFloat(1.0, 3.5);
    actionData.m_VerticalDirectionRandom = Math.RandomFloat(-0.5, 0.5);
    float bodyMass = dBodyGetMass(car);
    float invBodyMass = 1.0 / bodyMass;
    float force = dBodyGetMass(car) * PUSH_FORCE_IMPULSE_INCREMENT * car.GetPushForceCoefficientMultiplier();
    float easedProgress = Easing.EaseInOutSine(actionData.m_ActionComponent.GetProgress());
    vector impulse = car.GetDirection() * force * (float)actionData.m_PushDirection;
    impulse = impulse * invBodyMass;
    impulse[0] = impulse[0] * actionData.m_HorizontalDirectionRandom;
    impulse[1] = impulse[1] * actionData.m_VerticalDirectionRandom;
    impulse = impulse * easedProgress;
    actionData.m_Player.DepleteStamina(EStaminaModifiers.PUSH_CAR);
    dBodyApplyImpulseAt(car, impulse, car.ModelToWorld(car.GetEnginePos()));
  }
References dBodyApplyImpulseAt(), dBodyGetMass(), Easing::EaseInOutSine(), PUSH_FORCE_IMPULSE_INCREMENT, and Math::RandomFloat().
Referenced by ProgressActionComponent().
CreateActionComponent()
override void CreateActionComponent () private
Definition at line 57 of file ActionPushCar.c.
  {
    m_ActionData.m_ActionComponent = new CAContinuousRepeatPushCar(10.0);
  }
EndActionComponent()
override void EndActionComponent () private
Definition at line 70 of file ActionPushCar.c.
  {
    m_ActionDataPushCar = ActionPushCarData.Cast(m_ActionData);
    if (!m_ActionDataPushCar)
    {
      super.EndActionComponent();
      return;
    }
    if (m_ActionDataPushCar.m_State == UA_FINISHED)
    {
      if (m_ActionDataPushCar.m_EndType == 1)
        SetCommand(DayZPlayerConstants.CMD_ACTIONINT_FINISH);
      else if (m_ActionDataPushCar.m_EndType == 0)
        SetCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
    }
    else if (m_ActionDataPushCar.m_State == UA_CANCEL)
    {
      ActionContinuousBase action = ActionContinuousBase.Cast(m_ActionDataPushCar.m_Action);
      if (action.HasAlternativeInterrupt())
        SetCommand(DayZPlayerConstants.CMD_ACTIONINT_FINISH);
      else
        SetCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
      return;
    }
    m_ActionDataPushCar.m_State = UA_FINISHED;
  }
References m_ActionDataPushCar, UA_CANCEL, and UA_FINISHED.
ProgressActionComponent()
override void ProgressActionComponent () private
Definition at line 62 of file ActionPushCar.c.
  {
    super.ProgressActionComponent();
    ActionPushCarData data = ActionPushCarData.Cast(m_ActionData);
    ApplyForce(data);
  }
References ApplyForce().
Variable Documentation
m_ActionDataPushCar
ActionPushCarData m_ActionDataPushCar private
Definition at line 55 of file ActionPushCar.c.
Referenced by EndActionComponent().
m_Car
CarScript m_Car
Definition at line 17 of file ActionPushCar.c.
m_EndType
int m_EndType = 0
Definition at line 9 of file ActionPushCar.c.
m_HorizontalDirectionRandom
float m_HorizontalDirectionRandom = 1.0
Definition at line 11 of file ActionPushCar.c.
m_NeedUpdate
bool m_NeedUpdate
Definition at line 16 of file ActionPushCar.c.
m_Origin
vector m_Origin = "0 0 0"
Definition at line 14 of file ActionPushCar.c.
m_PushDirection
ActionPushCarDataReceiveData m_PushDirection = -1
m_VerticalDirectionRandom
float m_VerticalDirectionRandom = 1.0
Definition at line 12 of file ActionPushCar.c.
PUSH_FORCE_IMPULSE_INCREMENT
CAContinuousRepeatPushCar PUSH_FORCE_IMPULSE_INCREMENT = 200.0
Referenced by ApplyForce().