DayZ: Ammunition_Base Class Reference
Ammunition_Base Class Reference
ammo pile base
Protected Member Functions
float GetWeightSpecialized (bool forceRecalc=false)
override void SetQuantityToMinimum ()
override void SetFromProjectile (ProjectileStoppedInfo info)
Private Member Functions
override void SetActions ()
override bool IsAmmoPile ()
Static Private Member Functions
static float GetAmmoWeightByBulletType (string bulletType)
Static Private Attributes
static ref map< string, float > m_AmmoWeightByBulletType = new map<string, float>()
Detailed Description
ammo pile base
Definition at line 2 of file AmmunitionPiles.c.
Member Function Documentation
GetAmmoWeightByBulletType()
static float Ammunition_Base::GetAmmoWeightByBulletType (string bulletType) inline static private
Definition at line 6 of file AmmunitionPiles.c.
  {
    if (m_AmmoWeightByBulletType.Contains(bulletType))
      return m_AmmoWeightByBulletType.Get(bulletType);
    else
    {
      float ammoWeight;
      string ammoTypeName;
      GetGame().ConfigGetText(string.Format("CfgAmmo %1 spawnPileType", bulletType), ammoTypeName);
      if (ammoTypeName)
        ammoWeight = GetGame().ConfigGetFloat(string.Format("CfgMagazines %1 weight", ammoTypeName));
      else
        ErrorEx("empty 'spawnPileType' for bullet type:" + bulletType);
      if (ammoWeight)
        m_AmmoWeightByBulletType.Insert(bulletType, ammoWeight);
      return ammoWeight;
    }
  }
References ErrorEx, GetGame(), and m_AmmoWeightByBulletType.
Referenced by Weapon::GetWeightSpecialized().
GetWeightSpecialized()
float Ammunition_Base::GetWeightSpecialized (bool forceRecalc = false) inline protected
Definition at line 37 of file AmmunitionPiles.c.
  {
#ifdef DEVELOPER
    if (WeightDebug.m_VerbosityFlags & WeightDebugType.RECALC_FORCED)
    {
      WeightDebugData data = WeightDebug.GetWeightDebug(this);
      data.SetCalcDetails("TAmmo: (" + GetAmmoCount() + "(Ammo count) * " + GetConfigWeightModifiedDebugText());
    }
#endif
    return GetAmmoCount() * GetConfigWeightModified();
  }
IsAmmoPile()
override bool Ammunition_Base::IsAmmoPile () inline private
Definition at line 32 of file AmmunitionPiles.c.
  {
    return true;
  }
SetActions()
override void Ammunition_Base::SetActions () inline private
Definition at line 25 of file AmmunitionPiles.c.
  {
    super.SetActions();
    AddAction(ActionSortAmmoPile);
  }
References AddAction().
SetFromProjectile()
override void Ammunition_Base::SetFromProjectile (ProjectileStoppedInfo info) inline protected
Definition at line 55 of file AmmunitionPiles.c.
  {
    float dmgPerUse = GetGame().ConfigGetFloat("cfgAmmo " + info.GetAmmoType() + " dmgPerUse");
    float totalDmg = info.GetProjectileDamage() + dmgPerUse;
    float health = Math.Max(1 - totalDmg, 0);
    SetQuantityToMinimum();
    SetHealth01("", "", health);
    // SetCartridgeDamageAtIndex() MUST be called AFTER SetHealth01()!!
    // otherwise, decreasing health by less than an entire health level get ignored
    SetCartridgeDamageAtIndex(0, totalDmg);
  }
References GetGame(), Math::Max(), and SetQuantityToMinimum().
SetQuantityToMinimum()
override void Ammunition_Base::SetQuantityToMinimum () inline protected
Definition at line 50 of file AmmunitionPiles.c.
  {
    ServerSetAmmoCount(1);
  }
Referenced by SetFromProjectile().
Member Data Documentation
m_AmmoWeightByBulletType
ref map<string, float> Ammunition_Base::m_AmmoWeightByBulletType = new map<string, float>() static private
Definition at line 4 of file AmmunitionPiles.c.
Referenced by GetAmmoWeightByBulletType().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Magazine/AmmunitionPiles.c