DayZ: HandsHeader Class Reference
HandsHeader Class Reference
Protected Member Functions
void HandsHeader (LayoutHolder parent, string function_name)
override void SetLayoutName ()
override void UpdateInterval ()
void ShowCollapseButtons (bool show, bool force=false)
Protected Attributes
bool m_ForceHideCollapseButtons
Widget m_ItemHeader
Additional Inherited Members
Private Member Functions inherited from Header
void Header (LayoutHolder parent, string function_name)
void SetName (string name)
void SetItemPreview (EntityAI entity_ai)
void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
override void SetActive (bool active)
void ShowCollapseButton (bool state)
Private Attributes inherited from Header
int m_DefaultColor
int m_DefaultFontSize
EntityAI m_Entity
Widget m_CollapseButton
Widget m_UpArrowButton
Widget m_DownArrowButton
TextWidget m_HeaderText
Detailed Description
Definition at line 1 of file HandsHeader.c.
Constructor & Destructor Documentation
HandsHeader()
void HandsHeader::HandsHeader (LayoutHolder parent, string function_name) inline protected
Definition at line 6 of file HandsHeader.c.
  {
    m_DefaultFontSize = 24;
    m_ItemHeader = m_MainWidget.FindAnyWidget("hands_item_header");
    m_MainWidget = GetMainWidget().FindAnyWidget("height_wrapper");
    m_DefaultColor = GetMainWidget().GetColor();
#ifdef PLATFORM_CONSOLE
    ShowCollapseButtons(false, true);
#endif
  }
References Header::m_DefaultColor, Header::m_DefaultFontSize, m_ItemHeader, and ShowCollapseButtons().
Member Function Documentation
SetLayoutName()
override void HandsHeader::SetLayoutName () inline protected
Definition at line 18 of file HandsHeader.c.
  {
    m_LayoutName = WidgetLayoutName.HandsHeader;
  }
References WidgetLayoutName::HandsHeader.
ShowCollapseButtons()
void HandsHeader::ShowCollapseButtons (bool show, bool force = false) inline protected
Definition at line 45 of file HandsHeader.c.
  {
    m_ForceHideCollapseButtons = force;
#ifdef PLATFORM_CONSOLE
    m_CollapseButton.Show(false);
#else
    m_CollapseButton.Show(show);
#endif
  }
References Header::m_CollapseButton, and m_ForceHideCollapseButtons.
Referenced by HandsHeader().
UpdateInterval()
override void HandsHeader::UpdateInterval () inline protected
Definition at line 23 of file HandsHeader.c.
  {
    PlayerBase p = PlayerBase.Cast(GetGame().GetPlayer());
    if (!p)
      return;
    EntityAI item = p.GetHumanInventory().GetEntityInHands();
    /*if ( !m_ForceHideCollapseButtons )
      {
      if ( item && !item.GetInventory().IsInventoryLockedForLockType( HIDE_INV_FROM_SCRIPT ) && item.HasCargo() )
      {
        ShowCollapseButtons( true );
      }
      else
      {
        ShowCollapseButtons( false );
      }
      }*/
    m_ItemHeader.Show(item != null);
  }
References GetGame(), GetPlayer(), and m_ItemHeader.
Member Data Documentation
m_ForceHideCollapseButtons
bool HandsHeader::m_ForceHideCollapseButtons protected
Definition at line 3 of file HandsHeader.c.
Referenced by ShowCollapseButtons().
m_ItemHeader
Widget HandsHeader::m_ItemHeader protected
Definition at line 4 of file HandsHeader.c.
Referenced by HandsHeader(), and UpdateInterval().
The documentation for this class was generated from the following file:
scripts/5_Mission/GUI/InventoryNew/ContainedItems/Headers/HandsHeader.c