DayZ: OpenableBehaviour Class Reference
OpenableBehaviour Class Reference
Protected Member Functions
void OpenableBehaviour (bool bState=true)
void Open ()
void Close ()
bool IsOpened ()
void SetState (bool bState)
bool GetState ()
Protected Attributes
bool m_IsOpened
Detailed Description
Definition at line 1 of file OpenableBehaviour.c.
Constructor & Destructor Documentation
OpenableBehaviour()
void OpenableBehaviour::OpenableBehaviour (bool bState = true) inline protected
initial value
Definition at line 5 of file OpenableBehaviour.c.
  {
    m_IsOpened = bState;
  }
References m_IsOpened.
Member Function Documentation
Close()
void OpenableBehaviour::Close () inline protected
Definition at line 15 of file OpenableBehaviour.c.
  {
    SetState(false);
  }
References SetState().
GetState()
bool OpenableBehaviour::GetState () inline protected
Definition at line 30 of file OpenableBehaviour.c.
  {
    return m_IsOpened;
  }
References m_IsOpened.
Referenced by IsOpened().
IsOpened()
bool OpenableBehaviour::IsOpened () inline protected
Definition at line 20 of file OpenableBehaviour.c.
  {
    return GetState();
  }
References GetState().
Open()
void OpenableBehaviour::Open () inline protected
Definition at line 10 of file OpenableBehaviour.c.
  {
    SetState(true);
  }
References SetState().
SetState()
void OpenableBehaviour::SetState (bool bState) inline protected
Definition at line 25 of file OpenableBehaviour.c.
  {
    m_IsOpened = bState;
  }
References m_IsOpened.
Referenced by Close(), and Open().
Member Data Documentation
m_IsOpened
bool OpenableBehaviour::m_IsOpened protected
Definition at line 3 of file OpenableBehaviour.c.
Referenced by GetState(), OpenableBehaviour(), and SetState().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/OpenableBehaviour.c