DayZ: scripts/4_World/Entities/ExplosivesBase/RemoteDetonator.c File Reference
RemoteDetonator.c File Reference
Classes
class RemoteDetonatorTrigger
class ReplaceDetonatorItemLambda
class ReplaceDetonatorItemOnDisarmLambda
Enumerations
enum ERemoteDetonatorLEDState { OFF = 0 , LIT }
Functions
bool IsKit ()
void UpdateLED (ERemoteDetonatorLEDState pState, bool pForced=false)
override void SetActions ()
RemoteDetonatorTrigger RemoteDetonator RemoteDetonatorReceiver ()
void RemoteDetonatorTrigger ()
override void OnVariablesSynchronized ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
override void OnCEUpdate ()
override void PairRemote (notnull EntityAI trigger)
override void UnpairRemote ()
override void OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
void SetControlledDevice (EntityAI pDevice)
bool IsConnected ()
EntityAI GetControlledDevice ()
static RemoteDetonatorTrigger SpawnInPlayerHands (notnull EntityAI pEntity, EntityAI deviceToPair=null)
override void OnAnimationPhaseStarted (string animSource, float phase)
override void OnWasDetached (EntityAI parent, int slot_id)
override void EEKilled (Object killer)
ReplaceDetonatorItemLambda ReplaceItemWithNewLambdaBase SetPairDevice (EntityAI device)
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
override void OnSuccess (EntityAI new_item)
override void OnAbort ()
Variables
enum ERemoteDetonatorLEDState COLOR_LED_OFF = "#(argb,8,8,3)color(0,0,0,1.0,co)"
const string COLOR_LED_LIT = "#(argb,8,8,3)color(1,0,0,1.0,co)"
const string SELECTION_NAME_LED = "LED"
ERemoteDetonatorLEDState m_LastLEDState
const string ANIM_PHASE_TRIGGER = "trigger"
bool m_LED
ref RemotelyActivatedItemBehaviour m_RAIB
Enumeration Type Documentation
ERemoteDetonatorLEDState
enum ERemoteDetonatorLEDState
Enumerator
OFF
LIT
Definition at line 1 of file RemoteDetonator.c.
{
  OFF = 0,
  LIT,
}
Function Documentation
CopyOldPropertiesToNew()
override void SetPairDevice::CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
Definition at line 265 of file RemoteDetonator.c.
  {
    m_PairDevice = device;
  }
  override void OnSuccess(EntityAI new_item)
  {
EEItemLocationChanged()
override void RemoteDetonatorReceiver::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) protected
Definition at line 252 of file RemoteDetonator.c.
  {
    super.CopyOldPropertiesToNew(old_item, new_item);
    MiscGameplayFunctions.TransferItemProperties(old_item, new_item);
  }
}
EEKilled()
override void EEKilled (Object killer) protected
Definition at line 234 of file RemoteDetonator.c.
  {
    super.EEKilled(killer);
    UpdateLED(ERemoteDetonatorLEDState.OFF, true);
  }
References UpdateLED().
GetControlledDevice()
EntityAI RemoteDetonatorReceiver::GetControlledDevice () protected
Definition at line 316 of file RemoteDetonator.c.
GetRemotelyActivatedItemBehaviour()
override RemotelyActivatedItemBehaviour RemoteDetonatorReceiver::GetRemotelyActivatedItemBehaviour () protected
Definition at line 260 of file RemoteDetonator.c.
                                      : ReplaceDetonatorItemLambda
{
  EntityAI m_PairDevice
References SetPairDevice().
Referenced by InventoryItem::EEOnAfterLoad(), InventoryItem::OnStoreLoad(), InventoryItem::OnStoreSave(), Entity::SetPersistentPairID(), and UnpairRemote().
IsConnected()
bool RemoteDetonatorReceiver::IsConnected () protected
Definition at line 311 of file RemoteDetonator.c.
    {
      if (detonator.GetRemotelyActivatedItemBehaviour())
      {
        ExplosivesBase explosive = ExplosivesBase.Cast(detonator.GetRemotelyActivatedItemBehaviour().GetPairDevice());
IsKit()
override bool IsKit () protected
Definition at line 15 of file RemoteDetonator.c.
  {
    return true;
  }
OnAbort()
override void OnAbort () protected
Definition at line 292 of file RemoteDetonator.c.
  {
    ExplosivesBase explosive = ExplosivesBase.Cast(m_PairDevice);
    if (explosive)
    {
      explosive.LockTriggerSlots();
      explosive.SetTakeable(true);
    }
  }
OnActivatedByItem()
override void OnActivatedByItem (notnull ItemBase item) protected
Called when this item is activated by other.
Definition at line 293 of file RemoteDetonator.c.
  {
    ExplosivesBase explosive = ExplosivesBase.Cast(m_PairDevice);
    if (explosive)
    {
      explosive.LockTriggerSlots();
      explosive.SetTakeable(true);
    }
  }
}
class ReplaceDetonatorItemOnDisarmLambda : ReplaceDetonatorItemLambda
{
OnAnimationPhaseStarted()
override void RemoteDetonatorReceiver::OnAnimationPhaseStarted (string animSource, float phase) protected
Definition at line 357 of file RemoteDetonator.c.
{
  OFF = 0,
  LIT,
}
class RemoteDetonator : Inventory_Base
{
  const string COLOR_LED_OFF = "#(argb,8,8,3)color(0,0,0,1.0,co)";
  const string COLOR_LED_LIT = "#(argb,8,8,3)color(1,0,0,1.0,co)";
  const string SELECTION_NAME_LED = "LED";
  protected ERemoteDetonatorLEDState m_LastLEDState;
  bool IsKit()
  {
    return true;
  }
  void UpdateLED(ERemoteDetonatorLEDState pState, bool pForced = false)
  {
    int selectionIdx = GetHiddenSelectionIndex(SELECTION_NAME_LED);
    switch (pState)
    {
    case ERemoteDetonatorLEDState.LIT:
      SetObjectTexture(selectionIdx, COLOR_LED_LIT);
      break;
    default:
      SetObjectTexture(selectionIdx, COLOR_LED_OFF);
    }
    m_LastLEDState = pState;
    SetSynchDirty();
  }
  override void SetActions()
  {
    super.SetActions();
    AddAction(ActionAttachExplosivesTrigger);
    AddAction(ActionDisarmExplosiveWithRemoteDetonatorUnpaired);
  }
}
class RemoteDetonatorTrigger : RemoteDetonator
{
  protected const string ANIM_PHASE_TRIGGER = "trigger";
  protected bool m_LED;
  protected ref RemotelyActivatedItemBehaviour m_RAIB;
  void RemoteDetonatorTrigger()
  {
    m_RAIB = new RemotelyActivatedItemBehaviour(this);
    m_RAIB.SetTrigger();
    RegisterNetSyncVariableInt("m_RAIB.m_PairDeviceNetIdLow");
    RegisterNetSyncVariableInt("m_RAIB.m_PairDeviceNetIdHigh");
    RegisterNetSyncVariableInt("m_LastLEDState", 0, EnumTools.GetEnumSize(ERemoteDetonatorLEDState));
    UpdateLED(m_LastLEDState);
  }
  override bool IsKit()
  {
    return false;
  }
  override void OnVariablesSynchronized()
  {
    super.OnVariablesSynchronized();
    if (m_RAIB)
      m_RAIB.OnVariableSynchronized();
    UpdateLED(m_LastLEDState);
  }
  override void EEItemLocationChanged(notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
  {
    super.EEItemLocationChanged(oldLoc, newLoc);
    if (m_RAIB)
      m_RAIB.Pair();
  }
  override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour()
  {
    return m_RAIB;
  }
  override void OnCEUpdate()
  {
    super.OnCEUpdate();
    if (!IsRuined() && IsConnected() && GetControlledDevice())
    {
      if (vector.DistanceSq(GetPosition(), GetControlledDevice().GetPosition()) <= Math.SqrFloat(UAMaxDistances.EXPLOSIVE_REMOTE_ACTIVATION))
      {
        UpdateLED(ERemoteDetonatorLEDState.LIT);
        return;
      }
    }
    UpdateLED(ERemoteDetonatorLEDState.OFF);
  }
  override void PairRemote(notnull EntityAI trigger)
  {
    m_RAIB.Pair(trigger);
  }
  override void UnpairRemote()
  {
    UpdateLED(ERemoteDetonatorLEDState.OFF);
    m_RAIB.Unpair();
  }
  override void OnActivatedByItem(notnull ItemBase item)
  {
    if (GetGame().IsServer())
    {
      if (m_RAIB.IsPaired() && !IsRuined())
      {
        ItemBase device = ItemBase.Cast(GetControlledDevice());
        if (device && vector.DistanceSq(GetPosition(), device.GetPosition()) <= Math.SqrFloat(UAMaxDistances.EXPLOSIVE_REMOTE_ACTIVATION))
          device.OnActivatedByItem(this);
      }
    }
  }
  void SetControlledDevice(EntityAI pDevice)
  {
    m_RAIB.Pair(pDevice);
  }
  bool IsConnected()
  {
    return m_RAIB.IsPaired();
  }
  EntityAI GetControlledDevice()
  {
    return m_RAIB.GetPairDevice();
  }
  static RemoteDetonatorTrigger SpawnInPlayerHands(notnull EntityAI pEntity, EntityAI deviceToPair = null)
  {
    string type = "RemoteDetonatorTrigger";
    RemoteDetonatorTrigger rdt;
    PlayerBase player = PlayerBase.Cast(pEntity);
    if (player)
    {
      ItemBase inHandsItem = player.GetItemInHands();
      if (inHandsItem)
      {
        if (deviceToPair)
        {
          ReplaceDetonatorItemOnArmLambda onArmLambda = new ReplaceDetonatorItemOnArmLambda(inHandsItem, type);
          onArmLambda.SetPairDevice(deviceToPair);
          MiscGameplayFunctions.TurnItemIntoItemEx(player, onArmLambda);
        }
        else
        {
          ReplaceDetonatorItemLambda lambda = new ReplaceDetonatorItemLambda(inHandsItem, type);
          MiscGameplayFunctions.TurnItemIntoItemEx(player, lambda);
        }
        rdt = RemoteDetonatorTrigger.Cast(player.GetItemInHands());
      }
      else
        rdt = RemoteDetonatorTrigger.Cast(player.GetHumanInventory().CreateInHands(type));
      if (player.GetItemInHands())
        player.GetItemAccessor().OnItemInHandsChanged();
    }
    return rdt;
  }
  override void OnAnimationPhaseStarted(string animSource, float phase)
  {
    if (animSource == ANIM_PHASE_TRIGGER)
    {
      if (phase > 0.01)
        UpdateLED(ERemoteDetonatorLEDState.OFF);
    }
  }
  override void SetActions()
  {
    super.SetActions();
    RemoveAction(ActionAttachExplosivesTrigger);
    AddAction(ActionAttachOnTrap);
    AddAction(ActionDisarmExplosiveWithRemoteDetonator);
    AddAction(ActionTriggerRemotely);
  }
#ifdef DIAG_DEVELOPER
  override protected string GetDebugText()
  {
    string debug_output;
    debug_output += string.Format("low net id: %1\n", m_RAIB.GetPairDeviceNetIdLow());
    debug_output += string.Format("high net id: %1\n", m_RAIB.GetPairDeviceNetIdHigh());
    debug_output += string.Format("pair device: %1\n", m_RAIB.GetPairDevice());
    return debug_output;
  }
#endif
}
class RemoteDetonatorReceiver : RemoteDetonator
{
  void RemoteDetonatorReceiver()
  {
    UpdateLED(ERemoteDetonatorLEDState.OFF, true);
  }
  override bool IsKit()
  {
    return false;
  }
  override void OnWasDetached(EntityAI parent, int slot_id)
  {
    UpdateLED(ERemoteDetonatorLEDState.OFF);
  }
  override void EEKilled(Object killer)
  {
    super.EEKilled(killer);
    UpdateLED(ERemoteDetonatorLEDState.OFF, true);
  }
  override void SetActions()
  {
    super.SetActions();
    RemoveAction(ActionAttachExplosivesTrigger);
    RemoveAction(ActionDisarmExplosiveWithRemoteDetonatorUnpaired);
  }
}
class ReplaceDetonatorItemLambda : ReplaceItemWithNewLambdaBase
{
  override void CopyOldPropertiesToNew(notnull EntityAI old_item, EntityAI new_item)
  {
    super.CopyOldPropertiesToNew(old_item, new_item);
    MiscGameplayFunctions.TransferItemProperties(old_item, new_item);
  }
}
class ReplaceDetonatorItemOnArmLambda : ReplaceDetonatorItemLambda
{
  EntityAI m_PairDevice
  void SetPairDevice(EntityAI device)
  {
    m_PairDevice = device;
  }
  override void OnSuccess(EntityAI new_item)
  {
    super.OnSuccess(new_item);
    RemoteDetonator detonator = RemoteDetonator.Cast(new_item);
    if (detonator)
    {
      ExplosivesBase explosive = ExplosivesBase.Cast(m_PairDevice);
      if (explosive)
      {
        ItemBase receiver = ItemBase.Cast(explosive.GetInventory().CreateAttachment("RemoteDetonatorReceiver"));
        if (receiver)
        {
          MiscGameplayFunctions.TransferItemProperties(detonator, receiver);
          receiver.LockToParent();
          explosive.SetTakeable(false);
          explosive.PairWithDevice(detonator);
          explosive.Arm();
        }
      }
    }
  }
  override void OnAbort()
  {
    ExplosivesBase explosive = ExplosivesBase.Cast(m_PairDevice);
    if (explosive)
    {
      explosive.LockTriggerSlots();
      explosive.SetTakeable(true);
    }
  }
}
class ReplaceDetonatorItemOnDisarmLambda : ReplaceDetonatorItemLambda
{
  override void OnSuccess(EntityAI new_item)
  {
    super.OnSuccess(new_item);
    RemoteDetonator detonator = RemoteDetonator.Cast(m_OldItem);
    if (detonator)
    {
      if (detonator.GetRemotelyActivatedItemBehaviour())
      {
        ExplosivesBase explosive = ExplosivesBase.Cast(detonator.GetRemotelyActivatedItemBehaviour().GetPairDevice());
        if (explosive)
          explosive.Disarm();
      }
    }
  }
  override void OnAbort()
  {
    super.OnAbort();
    RemoteDetonator detonator = RemoteDetonator.Cast(m_OldItem);
    if (detonator)
    {
      if (detonator.GetRemotelyActivatedItemBehaviour())
      {
        ExplosivesBase explosive = ExplosivesBase.Cast(detonator.GetRemotelyActivatedItemBehaviour().GetPairDevice());
        if (explosive)
          explosive.LockExplosivesSlots();
      }
    }
  }
}
OnCEUpdate()
override void RemoteDetonatorReceiver::OnCEUpdate () protected
Definition at line 265 of file RemoteDetonator.c.
  {
    m_PairDevice = device;
  }
  override void OnSuccess(EntityAI new_item)
  {
    super.OnSuccess(new_item);
    RemoteDetonator detonator = RemoteDetonator.Cast(new_item);
    if (detonator)
    {
      ExplosivesBase explosive = ExplosivesBase.Cast(m_PairDevice);
      if (explosive)
      {
        ItemBase receiver = ItemBase.Cast(explosive.GetInventory().CreateAttachment("RemoteDetonatorReceiver"));
        if (receiver)
OnSuccess()
override void OnSuccess (EntityAI new_item) protected
Definition at line 269 of file RemoteDetonator.c.
  {
    super.OnSuccess(new_item);
    RemoteDetonator detonator = RemoteDetonator.Cast(new_item);
    if (detonator)
    {
      ExplosivesBase explosive = ExplosivesBase.Cast(m_PairDevice);
      if (explosive)
      {
        ItemBase receiver = ItemBase.Cast(explosive.GetInventory().CreateAttachment("RemoteDetonatorReceiver"));
        if (receiver)
        {
          MiscGameplayFunctions.TransferItemProperties(detonator, receiver);
          receiver.LockToParent();
          explosive.SetTakeable(false);
          explosive.PairWithDevice(detonator);
          explosive.Arm();
        }
      }
    }
  }
OnVariablesSynchronized()
override void RemoteDetonatorReceiver::OnVariablesSynchronized () protected
Definition at line 242 of file RemoteDetonator.c.
  {
    super.SetActions();
    RemoveAction(ActionAttachExplosivesTrigger);
    RemoveAction(ActionDisarmExplosiveWithRemoteDetonatorUnpaired);
  }
}
class ReplaceDetonatorItemLambda : ReplaceItemWithNewLambdaBase
References ActionAttachExplosivesTrigger(), ActionDisarmExplosiveWithRemoteDetonatorUnpaired(), and RemoveAction().
OnWasDetached()
override void OnWasDetached (EntityAI parent, int slot_id) protected
Definition at line 229 of file RemoteDetonator.c.
  {
    UpdateLED(ERemoteDetonatorLEDState.OFF);
  }
References UpdateLED().
Referenced by Entity::EEItemLocationChanged().
PairRemote()
override void RemoteDetonatorReceiver::PairRemote (notnull EntityAI trigger) protected
Definition at line 282 of file RemoteDetonator.c.
RemoteDetonatorReceiver()
RemoteDetonatorTrigger RemoteDetonator RemoteDetonatorReceiver () protected
Definition at line 37 of file RemoteDetonator.c.
  {
    UpdateLED(ERemoteDetonatorLEDState.OFF, true);
  }
References ActionAttachExplosivesTrigger(), ActionDisarmExplosiveWithRemoteDetonatorUnpaired(), and AddAction().
Referenced by ActionCondition(), ImprovisedExplosive::UpdateLED(), and Plastic_Explosive::UpdateLED().
RemoteDetonatorTrigger()
void RemoteDetonatorReceiver::RemoteDetonatorTrigger () protected
Definition at line 225 of file RemoteDetonator.c.
  {
    return false;
  }
  override void OnWasDetached(EntityAI parent, int slot_id)
  {
    UpdateLED(ERemoteDetonatorLEDState.OFF);
  }
  override void EEKilled(Object killer)
  {
SetActions()
override void SetActions () protected
Definition at line 37 of file RemoteDetonator.c.
  {
    super.SetActions();
    AddAction(ActionAttachExplosivesTrigger);
    AddAction(ActionDisarmExplosiveWithRemoteDetonatorUnpaired);
  }
SetControlledDevice()
void RemoteDetonatorReceiver::SetControlledDevice (EntityAI pDevice) protected
Definition at line 306 of file RemoteDetonator.c.
  {
    super.OnSuccess(new_item);
    RemoteDetonator detonator = RemoteDetonator.Cast(m_OldItem);
References ReplaceItemWithNewLambdaBase::m_OldItem.
SetPairDevice()
ReplaceDetonatorItemLambda ReplaceItemWithNewLambdaBase SetPairDevice (EntityAI device) protected
Definition at line 241 of file RemoteDetonator.c.
  {
    m_PairDevice = device;
  }
Referenced by GetRemotelyActivatedItemBehaviour().
SpawnInPlayerHands()
static RemoteDetonatorTrigger RemoteDetonatorReceiver::SpawnInPlayerHands (notnull EntityAI pEntity, EntityAI deviceToPair = null) static protected
item replaced, use different IK
Definition at line 321 of file RemoteDetonator.c.
  {
    super.OnAbort();
    RemoteDetonator detonator = RemoteDetonator.Cast(m_OldItem);
    if (detonator)
    {
      if (detonator.GetRemotelyActivatedItemBehaviour())
      {
        ExplosivesBase explosive = ExplosivesBase.Cast(detonator.GetRemotelyActivatedItemBehaviour().GetPairDevice());
        if (explosive)
          explosive.LockExplosivesSlots();
      }
    }
  }
}
UnpairRemote()
override void RemoteDetonatorReceiver::UnpairRemote () protected
Definition at line 287 of file RemoteDetonator.c.
UpdateLED()
void UpdateLED (ERemoteDetonatorLEDState pState, bool pForced = false) protected
Definition at line 20 of file RemoteDetonator.c.
  {
    int selectionIdx = GetHiddenSelectionIndex(SELECTION_NAME_LED);
    switch (pState)
    {
    case ERemoteDetonatorLEDState.LIT:
      SetObjectTexture(selectionIdx, COLOR_LED_LIT);
      break;
    default:
      SetObjectTexture(selectionIdx, COLOR_LED_OFF);
    }
    m_LastLEDState = pState;
    SetSynchDirty();
  }
References COLOR_LED_LIT, COLOR_LED_OFF, m_LastLEDState, and SELECTION_NAME_LED.
Referenced by RemoteDetonatorTrigger::OnAnimationPhaseStarted(), RemoteDetonatorTrigger::OnCEUpdate(), RemoteDetonatorTrigger::OnVariablesSynchronized(), RemoteDetonatorTrigger::RemoteDetonatorTrigger(), and RemoteDetonatorTrigger::UnpairRemote().
Variable Documentation
ANIM_PHASE_TRIGGER
const string ANIM_PHASE_TRIGGER = "trigger" protected
Definition at line 220 of file RemoteDetonator.c.
COLOR_LED_LIT
const string COLOR_LED_LIT = "#(argb,8,8,3)color(1,0,0,1.0,co)"
Definition at line 10 of file RemoteDetonator.c.
Referenced by UpdateLED().
COLOR_LED_OFF
enum ERemoteDetonatorLEDState COLOR_LED_OFF = "#(argb,8,8,3)color(0,0,0,1.0,co)"
m_LastLEDState
ERemoteDetonatorLEDState m_LastLEDState protected
Definition at line 13 of file RemoteDetonator.c.
Referenced by RemoteDetonatorTrigger::OnVariablesSynchronized(), RemoteDetonatorTrigger::RemoteDetonatorTrigger(), and UpdateLED().
m_LED
bool m_LED protected
Definition at line 222 of file RemoteDetonator.c.
m_RAIB
ref RemotelyActivatedItemBehaviour m_RAIB protected
Definition at line 223 of file RemoteDetonator.c.
SELECTION_NAME_LED
const string SELECTION_NAME_LED = "LED"
Definition at line 11 of file RemoteDetonator.c.
Referenced by UpdateLED().