DayZ: ItemOptics Class Reference
ItemOptics Class Reference
Protected Member Functions
void SetPlayer (PlayerBase player)
PlayerBase GetPlayer ()
Protected Attributes
PlayerBase m_Player
Private Member Functions
void ItemOptics ()
proto native bool EnterOptics ()
switches to optics mode if possible
proto native bool IsInOptics ()
is weapon in optics mode or not
proto native bool ExitOptics ()
switches out of optics mode (if possible)
proto native bool HasWeaponIronsightsOverride ()
is weapon in optics mode or not
proto native bool UseWeaponIronsightsOverride (bool state)
switches into ironsights override settings
proto native bool IsUsingWeaponIronsightsOverride ()
is optics using ironsights override settings or not
proto native int GetStepFOVCount ()
returns number of configured steps
proto native int GetStepFOVIndex ()
returns index of currently used value in 'discretefov' config array
proto native bool SetStepFOVIndex (int step)
sets zoom to fov value defined at given in 'discretefov' config array
proto native bool StepFOVUp ()
sets zoom to next defined (respective to current) value in zoom fov config array
proto native bool StepFOVDown ()
sets zoom to previous (respective to current) defined value in zoom fov config array
proto native float GetCurrentStepFOV ()
returns fov value at current index, or 'OpticsInfo.opticsZoomInit' config value (non-zooming optics)
proto native int GetStepZeroing ()
returns position of currently used value in zeroing config array
proto native bool SetStepZeroing (int step)
proto native bool StepZeroingUp ()
sets zeroing to next defined (respective to current) value in zeroing config array
proto native bool StepZeroingDown ()
sets zeroing to previous (respective to current) defined value in zeroing config array
proto native void GetCameraPoint (out vector pos, out vector dir)
gets camera position & direction in model space of optics entity
proto native float GetZoomInit ()
gets FOV value, when entering optics
proto native float GetZoomMin ()
gets FOV minimum
proto native float GetZoomMax ()
gets FOV maximum
proto native float GetZeroingDistanceZoomMin ()
Gets Zeroing distance at opticsZoomMin.
proto native float GetZeroingDistanceZoomMax ()
Gets Zeroing distance at opticsZoomMax.
proto native void SetZeroingClampDist (float dist)
Sets zeroing clamp for the optics and updates the clamp if dist > 0. Used when attached to weapon.
override void OnWorkStart ()
override void OnWorkStop ()
bool IsWorking ()
void UpdateOpticsReddotVisibility ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void OnInventoryExit (Man player)
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnVariablesSynchronized ()
void InitReddotData ()
void ShowReddot (bool state)
void InitOpticsPPInfo ()
bool InitDOFAvailability ()
optics with more than 1x zoom do not allow DOF changes
void InitOpticsPP (out array< float > mask_array, out array< float > lens_array, out float blur_float)
initializes values for optics' post-processes
void InitCameraOverrideProperties ()
bool InitOpticsDOFProperties (out array< float > temp_array)
Initializes DOF properties for optic's alternate ironsights (ACOG etc.)
bool AllowsDOF ()
returns 'true' for non-magnifying optics
bool IsNVOptic ()
int GetCurrentNVType ()
void SetCurrentOpticMode (int mode)
int GetCurrentOpticMode ()
void OnOpticModeChange ()
optic-specific behaviour to be defined here (override)
void OnOpticEnter ()
void OnOpticExit ()
ref array< float > GetOpticsDOF ()
ref array< float > GetOpticsPPMask ()
ref array< float > GetOpticsPPLens ()
float GetOpticsPPBlur ()
float GetNearPlaneValue ()
void Init2DPreloadType ()
void InitOpticMode ()
void UpdateSelectionVisibility ()
override void SetActions ()
override void OnDebugSpawn ()
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
void HuntingOptic ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void HideSelection (string selection_name)
override void ShowSelection (string selection_name)
bool ParentUsesWinchesterTypeMount ()
override bool CanPutAsAttachment (EntityAI parent)
Private Attributes
bool m_data_set
bool m_allowsDOF
bool m_reddot_displayed bool m_isNVOptic = false
int m_CurrentOpticMode
int m_CurrentOpticModeLocal
int m_reddot_index
float m_blur_float
float m_nearplane_override
string m_optic_sight_texture
string m_optic_sight_material
string m_2D_preload_type
ref array< float > m_mask_array
ref array< float > m_lens_array
ref array< float > m_OpticsDOFProperties
EntityAI m_Parent
Detailed Description
Definition at line 1 of file ItemOptics.c.
Constructor & Destructor Documentation
ItemOptics()
void ItemOptics::ItemOptics () inline private
Definition at line 19 of file ItemOptics.c.
  {
    m_mask_array = new array<float>;
    m_lens_array = new array<float>;
    m_OpticsDOFProperties = new array<float>;
    InitReddotData();
    InitOpticsPPInfo();
    InitCameraOverrideProperties();
    InitOpticsDOFProperties(m_OpticsDOFProperties);
    Init2DPreloadType();
    InitOpticMode();
    m_CurrentOpticModeLocal = -1;
    RegisterNetSyncVariableInt("m_CurrentOpticMode", 0, 63);
  }
References Init2DPreloadType(), InitCameraOverrideProperties(), InitOpticMode(), InitOpticsDOFProperties(), InitOpticsPPInfo(), InitReddotData(), m_CurrentOpticModeLocal, m_lens_array, m_mask_array, and m_OpticsDOFProperties.
Member Function Documentation
AllowsDOF()
bool ItemOptics::AllowsDOF () inline private
returns 'true' for non-magnifying optics
Definition at line 394 of file ItemOptics.c.
  {
    return m_allowsDOF;
  }
References m_allowsDOF.
Referenced by SetCameraPP().
CanPutAsAttachment() [1/3]
override bool ItemOptics::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 31 of file M79.c.
  {
    return true;
  }
CanPutAsAttachment() [2/3]
override bool ItemOptics::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file BUISOptic.c.
  {
    if (!super.CanPutAsAttachment(parent)) return false;
    if (parent.IsKindOf("M4A1_Base"))
      return true;
    return false;
    //return true;
  }
CanPutAsAttachment() [3/3]
override bool ItemOptics::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file M4_CarryHandleOptic.c.
  {
    if (!super.CanPutAsAttachment(parent)) return false;
    if (parent.IsKindOf("M4A1_Base"))
      return true;
    return false;
  }
EnterOptics()
ItemOptics::EnterOptics () private
switches to optics mode if possible
Returns
true if success, false otherwise
ExitOptics()
ItemOptics::ExitOptics () private
switches out of optics mode (if possible)
Returns
true if success, false otherwise
GetCameraPoint()
ItemOptics::GetCameraPoint (out vector pos, out vector dir) private
gets camera position & direction in model space of optics entity
Referenced by DayZPlayerCameraBase::GetCurrentSightInfo(), and GetCurrentSightInfo().
GetCurrentNVType()
int ItemOptics::GetCurrentNVType () inline private
Definition at line 404 of file ItemOptics.c.
  {
    /*
      //TODO - implement this into NV optics and modify (KazuarOptic example below)
      if (IsWorking())
      {
      switch (m_CurrentOpticMode)
      {
        case GameConstants.OPTICS_STATE_DAY:
          return NVTypes.NV_OPTICS_KAZUAR_DAY;
        case GameConstants.OPTICS_STATE_NIGHTVISION:
          return NVTypes.NV_OPTICS_KAZUAR_NIGHT;
      }
      }
      else
      {
      return NVTypes.NV_OPTICS_OFF;
      }
    */
    return NVTypes.NONE;
  }
Referenced by SetCameraPP().
GetCurrentOpticMode()
int ItemOptics::GetCurrentOpticMode () inline private
Definition at line 433 of file ItemOptics.c.
  {
    return m_CurrentOpticMode;
  }
References m_CurrentOpticMode.
Referenced by KazuarOptic::UpdateSelectionVisibility(), and StarlightOptic::UpdateSelectionVisibility().
GetCurrentStepFOV()
ItemOptics::GetCurrentStepFOV () private
returns fov value at current index, or 'OpticsInfo.opticsZoomInit' config value (non-zooming optics)
GetNearPlaneValue()
float ItemOptics::GetNearPlaneValue () inline private
Definition at line 468 of file ItemOptics.c.
  {
    return m_nearplane_override;
  }
References m_nearplane_override.
Referenced by AdjustCameraParameters().
GetOpticsDOF()
ref array< float > ItemOptics::GetOpticsDOF () inline private
Definition at line 451 of file ItemOptics.c.
  {
    return m_OpticsDOFProperties;
  }
References m_OpticsDOFProperties.
Referenced by DayZPlayerCameraBase::SetCameraPP(), and SetCameraPP().
GetOpticsPPBlur()
float ItemOptics::GetOpticsPPBlur () inline private
Definition at line 463 of file ItemOptics.c.
  {
    return m_blur_float;
  }
References m_blur_float.
Referenced by SetCameraPP().
GetOpticsPPLens()
ref array< float > ItemOptics::GetOpticsPPLens () inline private
Definition at line 459 of file ItemOptics.c.
  {
    return m_lens_array;
  }
References m_lens_array.
Referenced by SetCameraPP().
GetOpticsPPMask()
ref array< float > ItemOptics::GetOpticsPPMask () inline private
Definition at line 455 of file ItemOptics.c.
  {
    return m_mask_array;
  }
References m_mask_array.
Referenced by SetCameraPP().
GetPlayer()
PlayerBase ItemOptics::GetPlayer () inline protected
Definition at line 10 of file PoweredOptic_Base.c.
  {
    return m_Player;
  }
References m_Player.
GetStepFOVCount()
ItemOptics::GetStepFOVCount () private
returns number of configured steps
GetStepFOVIndex()
ItemOptics::GetStepFOVIndex () private
returns index of currently used value in 'discretefov' config array
Returns
index of currently used value in 'discretefov' config array
GetStepZeroing()
ItemOptics::GetStepZeroing () private
returns position of currently used value in zeroing config array
Returns
position of currently used value in zeroing config array
GetZeroingDistanceZoomMax()
ItemOptics::GetZeroingDistanceZoomMax () private
Gets Zeroing distance at opticsZoomMax.
GetZeroingDistanceZoomMin()
ItemOptics::GetZeroingDistanceZoomMin () private
Gets Zeroing distance at opticsZoomMin.
GetZoomInit()
ItemOptics::GetZoomInit () private
gets FOV value, when entering optics
GetZoomMax()
ItemOptics::GetZoomMax () private
gets FOV maximum
GetZoomMin()
ItemOptics::GetZoomMin () private
gets FOV minimum
HasWeaponIronsightsOverride()
ItemOptics::HasWeaponIronsightsOverride () private
is weapon in optics mode or not
Returns
true if optics has defined override optics info for weapon
Referenced by DayZPlayerCameraBase::SetupSightEntities().
HideSelection()
override void ItemOptics::HideSelection (string selection_name) inline private
Definition at line 34 of file HuntingOptic.c.
  {
    super.HideSelection(selection_name);
    if (selection_name == "hide") //hides pilotview selections in order not to obstruct view
    {
      HideSelection("rings_ris_pilot");
      HideSelection("rings_winchester_pilot");
    }
  }
References HideSelection().
Referenced by HideSelection(), HuntingOptic(), OnOpticEnter(), KazuarOptic::OnOpticEnter(), StarlightOptic::OnOpticEnter(), OnWasAttached(), OnWasDetached(), ShowSelection(), KazuarOptic::UpdateSelectionVisibility(), and StarlightOptic::UpdateSelectionVisibility().
HuntingOptic()
void ItemOptics::HuntingOptic () inline private
Definition at line 5 of file HuntingOptic.c.
  {
    HideSelection("rings_ris");
    HideSelection("rings_ris_pilot");
  }
References HideSelection().
Init2DPreloadType()
void ItemOptics::Init2DPreloadType () inline private
Definition at line 473 of file ItemOptics.c.
  {
    string path = "cfgVehicles " + GetType() + " OpticsInfo preloadOpticType";
    string type_2d;
    if (GetGame().ConfigIsExisting(path))
    {
      GetGame().ConfigGetText(path, type_2d);
      m_2D_preload_type = type_2d;
    }
  }
References GetGame(), GetType(), m_2D_preload_type, and path.
Referenced by ItemOptics().
InitCameraOverrideProperties()
void ItemOptics::InitCameraOverrideProperties () inline private
Definition at line 368 of file ItemOptics.c.
  {
    string path = "cfgVehicles " + GetType() + " OpticsInfo";
    if (GetGame().ConfigIsExisting(path + " nearPlaneDistanceOverride"))
      m_nearplane_override = Math.Max(GetGame().ConfigGetFloat(path + " nearPlaneDistanceOverride"), DayZPlayerCameraBase.CONST_NEARPLANE_OPTICS_MIN);
    else
      m_nearplane_override = DayZPlayerCameraOptics.CONST_NEARPLANE_OPTICS;
  }
References DayZPlayerCameraOptics(), GetGame(), GetType(), m_nearplane_override, Math::Max(), and path.
Referenced by ItemOptics().
InitDOFAvailability()
bool ItemOptics::InitDOFAvailability () inline private
optics with more than 1x zoom do not allow DOF changes
Definition at line 343 of file ItemOptics.c.
  {
    float fov_max;
    string path = "cfgVehicles " + GetType() + " OpticsInfo";
    /*
      Weapon_Base weapon = Weapon_Base.Cast(GetHierarchyParent());
      if (!weapon)
      return false; // no DOF for handheld optics
    */
    fov_max = GetGame().ConfigGetFloat(path + " opticsZoomMax");
    if (fov_max >= GameConstants.DZPLAYER_CAMERA_FOV_IRONSIGHTS)
      return true;
    return false;
  }
References GameConstants::DZPLAYER_CAMERA_FOV_IRONSIGHTS, GetGame(), GetType(), and path.
Referenced by InitOpticsPPInfo().
InitOpticMode()
void ItemOptics::InitOpticMode () inline private
Definition at line 485 of file ItemOptics.c.
  {
    SetCurrentOpticMode(GameConstants.OPTICS_STATE_DAY);
  }
References GameConstants::OPTICS_STATE_DAY, and SetCurrentOpticMode().
Referenced by ItemOptics().
InitOpticsDOFProperties()
bool ItemOptics::InitOpticsDOFProperties (out array< float > temp_array) inline private
Initializes DOF properties for optic's alternate ironsights (ACOG etc.)
Definition at line 378 of file ItemOptics.c.
  {
    if (GetGame().ConfigIsExisting("cfgVehicles " + GetType() + " OpticsInfo PPDOFProperties"))
    {
      GetGame().ConfigGetFloatArray("cfgVehicles " + GetType() + " OpticsInfo PPDOFProperties", temp_array);
      return true;
    }
    else if (GetGame().ConfigIsExisting("cfgVehicles " + GetType() + " OpticsInfoWeaponOverride PPDOFProperties"))
    {
      GetGame().ConfigGetFloatArray("cfgVehicles " + GetType() + " OpticsInfoWeaponOverride PPDOFProperties", temp_array);
      return true;
    }
    return false;
  }
References GetGame(), and GetType().
Referenced by ItemOptics().
InitOpticsPP()
void ItemOptics::InitOpticsPP (out array< float > mask_array, out array< float > lens_array, out float blur_float) inline private
initializes values for optics' post-processes
Definition at line 360 of file ItemOptics.c.
  {
    string path = "cfgVehicles " + GetType() + " OpticsInfo";
    GetGame().ConfigGetFloatArray(path + " PPMaskProperties", mask_array);
    GetGame().ConfigGetFloatArray(path + " PPLensProperties", lens_array);
    blur_float = GetGame().ConfigGetFloat(path + " PPBlurProperties");
  }
References GetGame(), GetType(), and path.
Referenced by InitOpticsPPInfo().
InitOpticsPPInfo()
void ItemOptics::InitOpticsPPInfo () inline private
Definition at line 334 of file ItemOptics.c.
  {
    m_allowsDOF = InitDOFAvailability();
    InitOpticsPP(m_mask_array, m_lens_array, m_blur_float);
    m_isNVOptic = ConfigGetBool("NVOptic");
  }
References InitDOFAvailability(), InitOpticsPP(), m_allowsDOF, m_blur_float, m_isNVOptic, m_lens_array, and m_mask_array.
Referenced by ItemOptics().
InitReddotData()
void ItemOptics::InitReddotData () inline private
Definition at line 280 of file ItemOptics.c.
  {
    string path = "cfgVehicles " + GetType() + " OpticsInfo";
    string temp;
    if (GetGame().ConfigIsExisting(path))
    {
      m_reddot_index = GetHiddenSelectionIndex("reddot");
      if (GetGame().ConfigIsExisting(path + " opticSightTexture"))
      {
        GetGame().ConfigGetText(path + " opticSightTexture", temp);
        m_optic_sight_texture = temp;
        temp = "";
      }
      if (GetGame().ConfigIsExisting(path + " opticSightMaterial"))
      {
        GetGame().ConfigGetText(path + " opticSightMaterial", temp);
        m_optic_sight_material = temp;
        temp = "";
      }
    }
    m_data_set = true;
  }
References GetGame(), GetType(), m_data_set, m_optic_sight_material, m_optic_sight_texture, m_reddot_index, and path.
Referenced by ItemOptics(), and ShowReddot().
IsInOptics()
ItemOptics::IsInOptics () private
is weapon in optics mode or not
Returns
true if in optics mode, false otherwise
Referenced by KazuarOptic::UpdateSelectionVisibility(), and StarlightOptic::UpdateSelectionVisibility().
IsNVOptic()
bool ItemOptics::IsNVOptic () inline private
Definition at line 399 of file ItemOptics.c.
  {
    return m_isNVOptic;
  }
References m_isNVOptic.
Referenced by Init(), and SetCameraPP().
IsUsingWeaponIronsightsOverride()
ItemOptics::IsUsingWeaponIronsightsOverride () private
is optics using ironsights override settings or not
Returns
true if optics is using ironsights override settings
IsWorking()
bool ItemOptics::IsWorking () inline private
Definition at line 188 of file ItemOptics.c.
  {
    if (GetCompEM() && GetCompEM().CanWork())
      return true;
    return false;
  }
Referenced by KazuarOptic::GetCurrentNVType(), StarlightOptic::GetCurrentNVType(), Init(), and UpdateOpticsReddotVisibility().
OnDebugSpawn()
override void ItemOptics::OnDebugSpawn () inline private
Definition at line 499 of file ItemOptics.c.
  {
    GetInventory().CreateAttachment("Battery9V");
  }
OnInventoryExit()
override void ItemOptics::OnInventoryExit (Man player) inline private
Definition at line 229 of file ItemOptics.c.
  {
    super.OnInventoryExit(player);
    PlayerBase playerPB;
    if (PlayerBase.CastTo(playerPB, player))
      playerPB.SetReturnToOptics(false);
    SetTakeable(true);
  }
References SetTakeable().
OnOpticEnter()
void ItemOptics::OnOpticEnter () inline private
Definition at line 440 of file ItemOptics.c.
  {
    if (GetGame() && !GetGame().IsDedicatedServer())
      HideSelection("hide");
  }
References GetGame(), and HideSelection().
OnOpticExit()
void ItemOptics::OnOpticExit () inline private
Definition at line 445 of file ItemOptics.c.
  {
    if (GetGame() && !GetGame().IsDedicatedServer())
      ShowSelection("hide");
  }
References GetGame(), and ShowSelection().
OnOpticModeChange()
void ItemOptics::OnOpticModeChange () inline private
optic-specific behaviour to be defined here (override)
Definition at line 439 of file ItemOptics.c.
{}
Referenced by OnStoreLoad(), OnVariablesSynchronized(), and SetCurrentOpticMode().
OnStoreLoad()
override bool ItemOptics::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 247 of file ItemOptics.c.
  {
    if (!super.OnStoreLoad(ctx, version))
      return false;
    m_IsStoreLoad = true;
    if (version >= 126)
    {
      if (!ctx.Read(m_CurrentOpticMode))
      {
        m_IsStoreLoad = false;
        return false;
      }
    }
    OnOpticModeChange();
    SetSynchDirty();
    m_IsStoreLoad = false;
    return true;
  }
References m_CurrentOpticMode, m_IsStoreLoad, and OnOpticModeChange().
OnStoreSave()
override void ItemOptics::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 240 of file ItemOptics.c.
  {
    super.OnStoreSave(ctx);
    ctx.Write(m_CurrentOpticMode);
  }
References m_CurrentOpticMode.
OnVariablesSynchronized()
override void ItemOptics::OnVariablesSynchronized () inline private
Definition at line 269 of file ItemOptics.c.
  {
    super.OnVariablesSynchronized();
    if (m_CurrentOpticModeLocal != m_CurrentOpticMode)
    {
      OnOpticModeChange();
      m_CurrentOpticModeLocal = m_CurrentOpticMode;
    }
  }
References m_CurrentOpticMode, m_CurrentOpticModeLocal, and OnOpticModeChange().
OnWasAttached() [1/2]
override void ItemOptics::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 203 of file ItemOptics.c.
  {
    super.OnWasAttached(parent, slot_id);
    SetTakeable(false);
    Weapon wep;
    if (Class.CastTo(wep, parent))
      SetZeroingClampDist(wep.GetZeroingClamp(wep.GetCurrentMuzzle()));
  }
References Class::CastTo(), SetTakeable(), and SetZeroingClampDist().
OnWasAttached() [2/2]
override void ItemOptics::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 11 of file HuntingOptic.c.
  {
    super.OnWasAttached(parent, slot_id);
    m_Parent = parent;
    if (!ParentUsesWinchesterTypeMount())
    {
      HideSelection("rings_winchester");
      HideSelection("rings_winchester_pilot");
      ShowSelection("rings_ris");
      ShowSelection("rings_ris_pilot");
    }
  }
References HideSelection(), m_Parent, ParentUsesWinchesterTypeMount(), and ShowSelection().
OnWasDetached() [1/2]
override void ItemOptics::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 214 of file ItemOptics.c.
  {
    super.OnWasDetached(parent, slot_id);
    PlayerBase player;
    if (PlayerBase.CastTo(player, GetHierarchyRootPlayer()))
      player.SetReturnToOptics(false);
    SetTakeable(true);
    Weapon wep;
    if (Class.CastTo(wep, parent))
      SetZeroingClampDist(0.0);
  }
References Class::CastTo(), SetTakeable(), and SetZeroingClampDist().
OnWasDetached() [2/2]
override void ItemOptics::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 24 of file HuntingOptic.c.
  {
    super.OnWasDetached(parent, slot_id);
    m_Parent = null;
    HideSelection("rings_ris");
    HideSelection("rings_ris_pilot");
    ShowSelection("rings_winchester");
    ShowSelection("rings_winchester_pilot");
  }
References HideSelection(), m_Parent, and ShowSelection().
OnWorkStart()
override void ItemOptics::OnWorkStart () inline private
Definition at line 176 of file ItemOptics.c.
  {
    if (!GetGame().IsDedicatedServer())
      ShowReddot(true);
  }
References GetGame(), and ShowReddot().
OnWorkStop()
override void ItemOptics::OnWorkStop () inline private
Definition at line 182 of file ItemOptics.c.
  {
    if (!GetGame().IsDedicatedServer())
      ShowReddot(false);
  }
References GetGame(), and ShowReddot().
ParentUsesWinchesterTypeMount()
bool ItemOptics::ParentUsesWinchesterTypeMount () inline private
Definition at line 66 of file HuntingOptic.c.
  {
    if (m_Parent && m_Parent.ConfigIsExisting("winchesterTypeOpticsMount"))
      return m_Parent.ConfigGetBool("winchesterTypeOpticsMount");
    return false;
  }
References m_Parent.
Referenced by OnWasAttached(), and ShowSelection().
SetActions()
override void ItemOptics::SetActions () inline private
Definition at line 492 of file ItemOptics.c.
  {
    super.SetActions();
    AddAction(ActionViewOptics);
  }
References AddAction().
SetCurrentOpticMode()
void ItemOptics::SetCurrentOpticMode (int mode) inline private
Definition at line 427 of file ItemOptics.c.
  {
    m_CurrentOpticMode = mode;
    OnOpticModeChange();
  }
References m_CurrentOpticMode, and OnOpticModeChange().
Referenced by InitOpticMode(), KazuarOptic::InitOpticMode(), and StarlightOptic::InitOpticMode().
SetPlayer()
void ItemOptics::SetPlayer (PlayerBase player) inline protected
Definition at line 5 of file PoweredOptic_Base.c.
  {
    m_Player = player;
  }
References m_Player.
SetStepFOVIndex()
ItemOptics::SetStepFOVIndex (int step) private
sets zoom to fov value defined at given in 'discretefov' config array
Parameters
[in] index of configured step, range [0..cfg_max]
Returns
true if zoom set
SetStepZeroing()
proto native bool ItemOptics::SetStepZeroing (int step) private
SetZeroingClampDist()
ItemOptics::SetZeroingClampDist (float dist) private
Sets zeroing clamp for the optics and updates the clamp if dist > 0. Used when attached to weapon.
Referenced by OnWasAttached(), and OnWasDetached().
ShowReddot()
void ItemOptics::ShowReddot (bool state) inline private
Definition at line 304 of file ItemOptics.c.
  {
    if (GetGame().IsDedicatedServer())
    {
      ErrorEx("should not be called on the server!", ErrorExSeverity.INFO);
      return;
    }
    if (!m_data_set)
      InitReddotData();
    // does not have reddot
    if (m_reddot_index == -1)
      return;
    if (state)
    {
      if (m_optic_sight_texture != "")
        SetObjectTexture(m_reddot_index, m_optic_sight_texture);
      if (m_optic_sight_material != "")
        SetObjectMaterial(m_reddot_index, m_optic_sight_material);
    }
    else
    {
      SetObjectTexture(m_reddot_index, "");
      SetObjectMaterial(m_reddot_index, "");
    }
    m_reddot_displayed = state;
  }
References ErrorEx, GetGame(), InitReddotData(), m_data_set, m_optic_sight_material, m_optic_sight_texture, and m_reddot_index.
Referenced by OnWorkStart(), OnWorkStop(), and UpdateOpticsReddotVisibility().
ShowSelection()
override void ItemOptics::ShowSelection (string selection_name) inline private
Definition at line 44 of file HuntingOptic.c.
  {
    super.ShowSelection(selection_name);
    if (selection_name == "hide")
    {
      if (!ParentUsesWinchesterTypeMount())
      {
        HideSelection("rings_winchester");
        HideSelection("rings_winchester_pilot");
        ShowSelection("rings_ris");
        ShowSelection("rings_ris_pilot");
      }
      else
      {
        HideSelection("rings_ris");
        HideSelection("rings_ris_pilot");
        ShowSelection("rings_winchester");
        ShowSelection("rings_winchester_pilot");
      }
    }
  }
References HideSelection(), ParentUsesWinchesterTypeMount(), and ShowSelection().
Referenced by OnOpticExit(), OnWasAttached(), OnWasDetached(), ShowSelection(), KazuarOptic::UpdateSelectionVisibility(), and StarlightOptic::UpdateSelectionVisibility().
StepFOVDown()
ItemOptics::StepFOVDown () private
sets zoom to previous (respective to current) defined value in zoom fov config array
Returns
true if zoom set
StepFOVUp()
ItemOptics::StepFOVUp () private
sets zoom to next defined (respective to current) value in zoom fov config array
Returns
true if zoom set
StepZeroingDown()
ItemOptics::StepZeroingDown () private
sets zeroing to previous (respective to current) defined value in zeroing config array
Returns
true if zeroing set
StepZeroingUp()
ItemOptics::StepZeroingUp () private
sets zeroing to next defined (respective to current) value in zeroing config array
Returns
true if zeroing set
UpdateOpticsReddotVisibility()
void ItemOptics::UpdateOpticsReddotVisibility () inline private
Definition at line 195 of file ItemOptics.c.
  {
    if (IsWorking() && !m_reddot_displayed)
      ShowReddot(true);
    else if (!IsWorking() && m_reddot_displayed)
      ShowReddot(false);
  }
References IsWorking(), and ShowReddot().
UpdateSelectionVisibility()
void ItemOptics::UpdateSelectionVisibility () inline private
Definition at line 490 of file ItemOptics.c.
{}
UseWeaponIronsightsOverride()
ItemOptics::UseWeaponIronsightsOverride (bool state) private
switches into ironsights override settings
Returns
true if switching was successful
Referenced by DayZPlayerCameraBase::GetCurrentSightInfo(), and GetCurrentSightInfo().
Member Data Documentation
m_2D_preload_type
string ItemOptics::m_2D_preload_type private
Definition at line 14 of file ItemOptics.c.
Referenced by Init2DPreloadType().
m_allowsDOF
bool ItemOptics::m_allowsDOF private
Definition at line 4 of file ItemOptics.c.
Referenced by AllowsDOF(), and InitOpticsPPInfo().
m_blur_float
float ItemOptics::m_blur_float private
Definition at line 10 of file ItemOptics.c.
Referenced by GetOpticsPPBlur(), and InitOpticsPPInfo().
m_CurrentOpticMode
int ItemOptics::m_CurrentOpticMode private
Definition at line 7 of file ItemOptics.c.
Referenced by KazuarOptic::GetCurrentNVType(), StarlightOptic::GetCurrentNVType(), GetCurrentOpticMode(), OnStoreLoad(), OnStoreSave(), OnVariablesSynchronized(), and SetCurrentOpticMode().
m_CurrentOpticModeLocal
int ItemOptics::m_CurrentOpticModeLocal private
Definition at line 8 of file ItemOptics.c.
Referenced by ItemOptics(), and OnVariablesSynchronized().
m_data_set
bool ItemOptics::m_data_set private
Definition at line 3 of file ItemOptics.c.
Referenced by InitReddotData(), and ShowReddot().
m_isNVOptic
bool m_reddot_displayed bool ItemOptics::m_isNVOptic = false private
Definition at line 6 of file ItemOptics.c.
Referenced by InitOpticsPPInfo(), and IsNVOptic().
m_lens_array
ref array<float> ItemOptics::m_lens_array private
Definition at line 16 of file ItemOptics.c.
Referenced by GetOpticsPPLens(), InitOpticsPPInfo(), and ItemOptics().
m_mask_array
ref array<float> ItemOptics::m_mask_array private
Definition at line 15 of file ItemOptics.c.
Referenced by GetOpticsPPMask(), InitOpticsPPInfo(), and ItemOptics().
m_nearplane_override
float ItemOptics::m_nearplane_override private
Definition at line 11 of file ItemOptics.c.
Referenced by GetNearPlaneValue(), and InitCameraOverrideProperties().
m_optic_sight_material
string ItemOptics::m_optic_sight_material private
Definition at line 13 of file ItemOptics.c.
Referenced by InitReddotData(), and ShowReddot().
m_optic_sight_texture
string ItemOptics::m_optic_sight_texture private
Definition at line 12 of file ItemOptics.c.
Referenced by InitReddotData(), and ShowReddot().
m_OpticsDOFProperties
ref array<float> ItemOptics::m_OpticsDOFProperties private
Definition at line 17 of file ItemOptics.c.
Referenced by GetOpticsDOF(), and ItemOptics().
m_Parent
EntityAI ItemOptics::m_Parent private
Definition at line 3 of file HuntingOptic.c.
m_Player
PlayerBase ItemOptics::m_Player protected
Definition at line 3 of file PoweredOptic_Base.c.
m_reddot_index
int ItemOptics::m_reddot_index private
Definition at line 9 of file ItemOptics.c.
Referenced by InitReddotData(), and ShowReddot().
The documentation for this class was generated from the following files:
scripts/4_World/Entities/Core/Inherited/ItemOptics.c
scripts/4_World/Entities/ItemBase/Inventory_Base/HuntingOptic.c
scripts/4_World/Entities/ItemBase/PoweredOptic_Base.c
scripts/4_World/Entities/Firearms/Launcher/M79.c
scripts/4_World/Entities/ItemBase/Inventory_Base/BUISOptic.c
scripts/4_World/Entities/ItemBase/Inventory_Base/M4_CarryHandleOptic.c