DayZ: ContaminatedArea_Local Class Reference
ContaminatedArea_Local Class Reference
Private Member Functions
void ContaminatedArea_Local ()
override void SetupZoneData (EffectAreaParams params)
override void EEInit ()
override void SpawnItems ()
override float GetStartDecayLifetime ()
override float GetFinishDecayLifetime ()
override float GetRemainingTime ()
override void Tick ()
Private Member Functions inherited from ContaminatedArea_Dynamic
void ContaminatedArea_Dynamic ()
override void EEOnCECreate ()
float GetRemainingTime ()
float GetStartDecayLifetime ()
float GetFinishDecayLifetime ()
override void Tick ()
void SetDecayState (int newState)
override void EEInit ()
override void InitZone ()
override void InitZoneServer ()
void SpawnItems ()
override void InitZoneClient ()
override void OnParticleAllocation (ParticleManager pm, array< ParticleSource > particles)
override void CreateTrigger (vector pos, int radius)
void PlayFX ()
void PlayExplosionLight ()
void PlayFlareVFX ()
override void EEDelete (EntityAI parent)
override void OnVariablesSynchronized ()
Private Attributes
const float TICK_RATE = 1
ref Timer m_Timer1 = new Timer
float m_Lifetime = 360
Private Attributes inherited from ContaminatedArea_Dynamic
ref Timer m_StartupTimer
ref Timer m_FXTimer
FlareLight m_FlareLight
ShellLight m_ShellLight
vector m_OffsetPos
int m_DecayState = eAreaDecayStage.INIT
const int AIRBORNE_EXPLOSION_DELAY = 20
const int AREA_SETUP_DELAY = 10
const float AIRBORNE_FX_OFFSET = 50
const float ARTILLERY_SHELL_SPEED = 100
const float DECAY_START_PART_SIZE = 32
const int DECAY_START_PART_BIRTH_RATE = 1
const float DECAY_END_PART_SIZE = 17
const int DECAY_END_PART_BIRTH_RATE = 1
const float START_DECAY_LIFETIME = 900
const float FINISH_DECAY_LIFETIME = 300
const ref array< string > SPAWN_ITEM_TYPE = {"Grenade_ChemGas"}
const ref array< int > SPAWN_ITEM_COUNT = {Math.RandomIntInclusive(2, 5)}
const ref array< float > SPAWN_ITEM_RAD_MIN = {5}
const ref array< float > SPAWN_ITEM_RAD_MAX = {15}
Detailed Description
Definition at line 1 of file ContaminatedArea_Local.c.
Constructor & Destructor Documentation
ContaminatedArea_Local()
void ContaminatedArea_Local::ContaminatedArea_Local () inline private
Definition at line 10 of file ContaminatedArea_Local.c.
  {
    m_EffectsPriority = -10;
  }
References EffectArea::m_EffectsPriority.
Member Function Documentation
EEInit()
override void ContaminatedArea_Local::EEInit () inline private
Definition at line 31 of file ContaminatedArea_Local.c.
  {
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      SetupZoneData(new EffectAreaParams);
      m_Timer1.Run(TICK_RATE, this, "Tick", NULL, true);
    }
  }
References GetGame(), m_Timer1, SetupZoneData(), and TICK_RATE.
GetFinishDecayLifetime()
override float ContaminatedArea_Local::GetFinishDecayLifetime () inline private
Definition at line 50 of file ContaminatedArea_Local.c.
  {
    return 10;
  }
GetRemainingTime()
override float ContaminatedArea_Local::GetRemainingTime () inline private
Definition at line 55 of file ContaminatedArea_Local.c.
  {
    return m_Lifetime;
  }
References m_Lifetime.
GetStartDecayLifetime()
override float ContaminatedArea_Local::GetStartDecayLifetime () inline private
Definition at line 45 of file ContaminatedArea_Local.c.
  {
    return 20;
  }
SetupZoneData()
override void ContaminatedArea_Local::SetupZoneData (EffectAreaParams params) inline private
Definition at line 15 of file ContaminatedArea_Local.c.
  {
    params.m_ParamPartId = ParticleList.CONTAMINATED_AREA_GAS_AROUND;
    params.m_ParamInnerRings = 0;
    params.m_ParamPosHeight = 3;
    params.m_ParamNegHeight = 5;
    params.m_ParamRadius = 10;
    params.m_ParamOuterToggle = false;
    params.m_ParamTriggerType = "ContaminatedTrigger_Local";
    params.m_ParamAroundPartId = 0;
    params.m_ParamTinyPartId = 0;
    super.SetupZoneData(params);
  }
References ParticleList::CONTAMINATED_AREA_GAS_AROUND.
Referenced by EEInit().
SpawnItems()
override void ContaminatedArea_Local::SpawnItems () inline private
Definition at line 40 of file ContaminatedArea_Local.c.
  {
    // override base funcionality as we don't want any items spawned here
  }
Tick()
override void ContaminatedArea_Local::Tick () inline private
Definition at line 60 of file ContaminatedArea_Local.c.
  {
    m_Lifetime -= TICK_RATE;
    if (m_Lifetime <= 0)
      Delete();
  }
References m_Lifetime, and TICK_RATE.
Member Data Documentation
m_Lifetime
float ContaminatedArea_Local::m_Lifetime = 360 private
Definition at line 5 of file ContaminatedArea_Local.c.
Referenced by GetRemainingTime(), and Tick().
m_Timer1
ref Timer ContaminatedArea_Local::m_Timer1 = new Timer private
Definition at line 4 of file ContaminatedArea_Local.c.
Referenced by EEInit().
TICK_RATE
const float ContaminatedArea_Local::TICK_RATE = 1 private
Definition at line 3 of file ContaminatedArea_Local.c.
Referenced by EEInit(), and Tick().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/ContaminatedArea/ContaminatedArea_Local.c