DayZ: ShockHandler Class Reference
ShockHandler Class Reference
Protected Member Functions
void ShockHandler (PlayerBase player)
void Update (float deltaT)
float GetCurrentShock ()
float GetShock ()
void SetShock (float dealtShock)
void Synchronize ()
float SetMultiplier (float mult)
Protected Attributes
float m_Shock
float m_ShockValueMax
float m_ShockValueThreshold
PlayerBase m_Player
const float UPDATE_THRESHOLD = 3
const float VALUE_CHECK_INTERVAL = 0.95
float m_CumulatedShock
ref Param1< float > m_Param
Private Member Functions
void DealShock ()
void CheckValue (bool forceUpdate)
float NormalizeShockVal (float shock)
float LerpVignette (float x, float y, float deltaT)
void ShockHitEffect (float compareBase)
Private Attributes
float m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1
float m_ShockMultiplier = 1
float m_PrevVignette
float m_LerpRes
const int LIGHT_SHOCK_HIT = 33
const int MID_SHOCK_HIT = 67
const int HEAVY_SHOCK_HIT = 100
const int INTENSITY_FACTOR = 1
const float PULSE_PERIOD = 0.5
const float PULSE_AMPLITUDE = 0.05
float m_PulseTimer
Detailed Description
Definition at line 1 of file ShockHandler.c.
Constructor & Destructor Documentation
ShockHandler()
void ShockHandler::ShockHandler (PlayerBase player) inline protected
Definition at line 28 of file ShockHandler.c.
  {
    m_Player = player;
    m_Player.m_CurrentShock = m_Player.GetMaxHealth("", "Shock");
    m_PrevVignette = m_Player.m_CurrentShock * 0.01; //Equivalent to divided by 100
    m_ShockValueMax = m_Player.GetMaxHealth("", "Shock");
    m_ShockValueThreshold = m_ShockValueMax * 0.95;
    m_Param = new Param1<float>(0);
  }
References m_Param, m_Player, m_PrevVignette, m_ShockValueMax, and m_ShockValueThreshold.
Member Function Documentation
CheckValue()
void ShockHandler::CheckValue (bool forceUpdate) inline private
Definition at line 118 of file ShockHandler.c.
  {
    m_CumulatedShock += m_Shock; // increment on both client and server
    if (forceUpdate)
      m_PrevVignette = NormalizeShockVal(m_Player.m_CurrentShock);
    if (GetGame().IsServer())
    {
      m_Player.m_CurrentShock = m_Player.GetHealth("", "Shock");
      /*
        if (m_Player.m_CurrentShock <= 0)
        m_Player.SetHealthMax("", "Shock");
      */
      if (m_CumulatedShock >= UPDATE_THRESHOLD || forceUpdate)
      {
        m_CumulatedShock *= m_ShockMultiplier;
        DealShock();
        m_CumulatedShock = 0;
        m_Shock = 0;
        Synchronize();
      }
    }
  }
References DealShock(), GetGame(), m_CumulatedShock, m_Player, m_PrevVignette, m_Shock, m_ShockMultiplier, NormalizeShockVal(), Synchronize(), and UPDATE_THRESHOLD.
Referenced by SetShock(), and Update().
DealShock()
void ShockHandler::DealShock () inline private
Definition at line 111 of file ShockHandler.c.
  {
    if (GetGame().IsServer())
      m_Player.GiveShock(-m_CumulatedShock);
  }
References GetGame(), m_CumulatedShock, and m_Player.
Referenced by CheckValue().
GetCurrentShock()
float ShockHandler::GetCurrentShock () inline protected
Definition at line 94 of file ShockHandler.c.
  {
    return m_Player.m_CurrentShock;
  }
References m_Player.
GetShock()
float ShockHandler::GetShock () inline protected
Definition at line 99 of file ShockHandler.c.
  {
    return m_Shock;
  }
References m_Shock.
LerpVignette()
float ShockHandler::LerpVignette (float x, float y, float deltaT) inline private
Definition at line 163 of file ShockHandler.c.
  {
    float output;
    output = Math.Lerp(x, y, deltaT);
    return output;
  }
References Math::Lerp(), x, and y.
Referenced by Update().
NormalizeShockVal()
float ShockHandler::NormalizeShockVal (float shock) inline private
Definition at line 156 of file ShockHandler.c.
  {
    float base = m_Player.GetMaxHealth("", "Shock") * INTENSITY_FACTOR;
    float normShock = shock / base;
    return normShock;
  }
References INTENSITY_FACTOR, and m_Player.
Referenced by CheckValue(), and Update().
SetMultiplier()
float ShockHandler::SetMultiplier (float mult) inline protected
Definition at line 150 of file ShockHandler.c.
  {
    m_ShockMultiplier = mult;
    return m_ShockMultiplier;
  }
References m_ShockMultiplier.
SetShock()
void ShockHandler::SetShock (float dealtShock) inline protected
Definition at line 104 of file ShockHandler.c.
  {
    m_Shock += dealtShock;
    CheckValue(false);
  }
References CheckValue(), and m_Shock.
ShockHitEffect()
void ShockHandler::ShockHitEffect (float compareBase) inline private
Definition at line 171 of file ShockHandler.c.
  {
    float shockDifference = compareBase - m_Player.m_CurrentShock;
    //Print(shockDifference);
    if (shockDifference >= UPDATE_THRESHOLD)
    {
      if (m_CumulatedShock < 25)
        m_Player.SpawnShockEffect(MiscGameplayFunctions.Normalize(LIGHT_SHOCK_HIT, 100));
      else if (m_CumulatedShock < 50)
        m_Player.SpawnShockEffect(MiscGameplayFunctions.Normalize(MID_SHOCK_HIT, 100));
      else
        m_Player.SpawnShockEffect(MiscGameplayFunctions.Normalize(HEAVY_SHOCK_HIT, 100));
    }
  }
References HEAVY_SHOCK_HIT, LIGHT_SHOCK_HIT, m_CumulatedShock, m_Player, MID_SHOCK_HIT, and UPDATE_THRESHOLD.
Referenced by Update().
Synchronize()
void ShockHandler::Synchronize () inline protected
Definition at line 145 of file ShockHandler.c.
  {
    DayZPlayerSyncJunctures.SendShock(m_Player, m_Player.m_CurrentShock);
  }
References m_Player, and DayZPlayerSyncJunctures::SendShock().
Referenced by CheckValue().
Update()
void ShockHandler::Update (float deltaT) inline protected
Definition at line 38 of file ShockHandler.c.
  {
    m_TimeSinceLastTick += deltaT;
    m_PulseTimer += deltaT;
    if (GetGame().IsClient())
    {
      //Deactivate tunnel vignette when player falls unconscious
      if (m_Player.IsUnconscious())
      {
        PPERequesterBank.GetRequester(PPERequester_TunnelVisionEffects).Stop();
        return;
      }
      //Deactivate if above visible threshold (also stops "zero bobbing" being sent all the time
      if (m_Player.m_CurrentShock >= m_ShockValueThreshold)
      {
        PPERequesterBank.GetRequester(PPERequester_TunnelVisionEffects).Stop();
        return;
      }
      //Add bobbing to create pulsing effect
      float val = 0.0;
      if (m_Player.m_CurrentShock > m_ShockValueMax * 0.8)
        val = MiscGameplayFunctions.Bobbing(PULSE_PERIOD, PULSE_AMPLITUDE, m_PulseTimer);
      float val_adjusted;
      if (m_Player.m_CurrentShock != (m_PrevVignette * 100))
      {
        //Interpolate between previous level and currently synchronized shock level
        m_LerpRes = LerpVignette(m_PrevVignette, NormalizeShockVal(m_Player.m_CurrentShock), m_TimeSinceLastTick);
        val_adjusted = 1 - Easing.EaseInQuart(m_LerpRes) + val;
      }
      else
        val_adjusted = 1 - Easing.EaseInQuart(NormalizeShockVal(m_Player.m_CurrentShock)) + val;
      m_Param.param1 = val_adjusted;
      PPERequesterBank.GetRequester(PPERequester_TunnelVisionEffects).Start(m_Param);
    }
    if (m_TimeSinceLastTick > VALUE_CHECK_INTERVAL)
    {
      //Play the shock hit event (multiply prevVignette by 100 to "Un-Normalize" value)
      if (GetGame().IsClient())
      {
        ShockHitEffect(m_PrevVignette * 100);
        m_PrevVignette = m_Player.m_CurrentShock * 0.01;
      }
      CheckValue(false);
      m_TimeSinceLastTick = 0;
    }
  }
References CheckValue(), Easing::EaseInQuart(), GetGame(), LerpVignette(), m_LerpRes, m_Param, m_Player, m_PrevVignette, m_PulseTimer, m_ShockValueMax, m_ShockValueThreshold, m_TimeSinceLastTick, NormalizeShockVal(), PULSE_AMPLITUDE, PULSE_PERIOD, ShockHitEffect(), and VALUE_CHECK_INTERVAL.
Member Data Documentation
HEAVY_SHOCK_HIT
const int ShockHandler::HEAVY_SHOCK_HIT = 100 private
Definition at line 18 of file ShockHandler.c.
Referenced by ShockHitEffect().
INTENSITY_FACTOR
const int ShockHandler::INTENSITY_FACTOR = 1 private
Definition at line 19 of file ShockHandler.c.
Referenced by NormalizeShockVal().
LIGHT_SHOCK_HIT
const int ShockHandler::LIGHT_SHOCK_HIT = 33 private
Definition at line 16 of file ShockHandler.c.
Referenced by ShockHitEffect().
m_CumulatedShock
float ShockHandler::m_CumulatedShock protected
Definition at line 10 of file ShockHandler.c.
Referenced by CheckValue(), DealShock(), and ShockHitEffect().
m_LerpRes
float ShockHandler::m_LerpRes private
Definition at line 14 of file ShockHandler.c.
Referenced by Update().
m_Param
ref Param1<float> ShockHandler::m_Param protected
Definition at line 26 of file ShockHandler.c.
Referenced by ShockHandler(), and Update().
m_Player
PlayerBase ShockHandler::m_Player protected
Definition at line 6 of file ShockHandler.c.
Referenced by CheckValue(), DealShock(), GetCurrentShock(), NormalizeShockVal(), ShockHandler(), ShockHitEffect(), Synchronize(), and Update().
m_PrevVignette
float ShockHandler::m_PrevVignette private
Definition at line 13 of file ShockHandler.c.
Referenced by CheckValue(), ShockHandler(), and Update().
m_PulseTimer
float ShockHandler::m_PulseTimer private
Definition at line 24 of file ShockHandler.c.
Referenced by Update().
m_Shock
float ShockHandler::m_Shock protected
Definition at line 3 of file ShockHandler.c.
Referenced by CheckValue(), GetShock(), and SetShock().
m_ShockMultiplier
float ShockHandler::m_ShockMultiplier = 1 private
Definition at line 12 of file ShockHandler.c.
Referenced by CheckValue(), and SetMultiplier().
m_ShockValueMax
float ShockHandler::m_ShockValueMax protected
Definition at line 4 of file ShockHandler.c.
Referenced by ShockHandler(), and Update().
m_ShockValueThreshold
float ShockHandler::m_ShockValueThreshold protected
Definition at line 5 of file ShockHandler.c.
Referenced by ShockHandler(), and Update().
m_TimeSinceLastTick
float ShockHandler::m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1 private
Definition at line 11 of file ShockHandler.c.
Referenced by Update().
MID_SHOCK_HIT
const int ShockHandler::MID_SHOCK_HIT = 67 private
Definition at line 17 of file ShockHandler.c.
Referenced by ShockHitEffect().
PULSE_AMPLITUDE
const float ShockHandler::PULSE_AMPLITUDE = 0.05 private
Definition at line 23 of file ShockHandler.c.
Referenced by Update().
PULSE_PERIOD
const float ShockHandler::PULSE_PERIOD = 0.5 private
Definition at line 22 of file ShockHandler.c.
Referenced by Update().
UPDATE_THRESHOLD
const float ShockHandler::UPDATE_THRESHOLD = 3 protected
Definition at line 8 of file ShockHandler.c.
Referenced by CheckValue(), and ShockHitEffect().
VALUE_CHECK_INTERVAL
const float ShockHandler::VALUE_CHECK_INTERVAL = 0.95 protected
Definition at line 9 of file ShockHandler.c.
Referenced by Update().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/ShockHandler.c