DayZ: BiosSessionService Class Reference
BiosSessionService Class Reference
Protected Member Functions
proto native EBiosError EnterGameplaySessionAsync (string session_address, int session_port)
Enter a gameplay session.
proto native EBiosError LeaveGameplaySessionAsync (string session_address, int session_port)
Leave a gameplay session.
proto native void OnSessionPlayerListUpdate (array< string > newPlayers)
Alerts engine that players in current session have changed.
void TryGetSession (string join_handle="")
Gets a session from a join handle.
proto native EBiosError GetSessionAsync (string join_handle)
Gets a session from a join handle.
proto native EBiosError SetGameplayActivityAsync (string session_address, int session_port)
Sets the activity to a gameplay session.
proto native EBiosError ClearActivityAsync ()
not implemented
proto native EBiosError ShowInviteToGameplaySessionAsync (string session_address, int session_port)
Show system UI to invite friends to current gameplay session.
proto native EBiosError InviteToGameplaySessionAsync (string session_address, int session_port, array< string > invitee_list)
Send invite to list of users.
proto native void SetMultiplayState (bool is_active)
Notifiy about interactive multiplayer state.
void OnSetActivity (EBiosError error)
Callback function.
void OnClearActivity (EBiosError error)
Callback function.
void OnGetGameplaySession (string session_address, int session_port)
Callback function.
void OnGetSessionError (EBiosError error)
//! Callback function, not implemented
void OnEnterGameplaySession (string session_address, int session_port, EBiosError error)
Callback function.
void OnLeaveGameplaySession (EBiosError error)
Callback function.
void OnShowInviteToGameplaySession (EBiosError error)
Callback function.
void OnInviteToGameplaySession (EBiosError error)
Callback function.
array< string > GetSessionPlayerList ()
Protected Attributes
int m_GetSessionAttempts
string m_CurrentHandle
Detailed Description
Definition at line 1 of file BiosSessionService.c.
Member Function Documentation
ClearActivityAsync()
proto native EBiosError BiosSessionService::ClearActivityAsync () protected
not implemented
Clears the current activity
The async result is returned in the OnClearActivity callback. Expected errors:
Returns
EBiosError indicating if the async operation is pending.
EnterGameplaySessionAsync()
proto native EBiosError BiosSessionService::EnterGameplaySessionAsync (string session_address, int session_port) protected
Enter a gameplay session.
The async result is returned in the OnEnterGameplaySession callback. Expected errors: LOGICAL - if the user is currently in an active gameplay session.
Parameters
session_address server IP address.
session_port server port.
Returns
EBiosError indicating if the async operation is pending.
GetSessionAsync()
proto native EBiosError BiosSessionService::GetSessionAsync (string join_handle) protected
Gets a session from a join handle.
The async result is returned in the OnGetGameplaySession, OnGetLobbySession or OnGetSessionError callback, dependinng on the type of session, or error. Expected errors:
Parameters
join_handle the parsed join handle.
Returns
EBiosError indicating if the async operation is pending.
Referenced by TryGetSession().
GetSessionPlayerList()
array< string > BiosSessionService::GetSessionPlayerList () inline protected
Definition at line 252 of file BiosSessionService.c.
  {
    return ClientData.GetSimplePlayerList();
  }
References ClientData::GetSimplePlayerList().
InviteToGameplaySessionAsync()
proto native EBiosError BiosSessionService::InviteToGameplaySessionAsync (string session_address, int session_port, array< string > invitee_list) protected
Send invite to list of users.
The async result is returned in the OnInviteToGameplaySession callback. The user must be inside the session. That means, OnEnterGameplaySession must be called with no errors.
Parameters
session_address server IP address.
session_port server port.
invitee_list list of users to invite
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnEnterGameplaySession().
LeaveGameplaySessionAsync()
proto native EBiosError BiosSessionService::LeaveGameplaySessionAsync (string session_address, int session_port) protected
Leave a gameplay session.
The async result is returned in the OnLeaveGameplaySession callback. If there is an unexpected error the state is cleared. Expected errors: ERR_NOT_FOUND - when attempting to leave a gameplay session the user is not part of. ERR_LOGICAL - when the user is not in a gameplay session.
Parameters
session_address server IP address.
session_port server port.
Returns
EBiosError indicating if the async operation is pending.
OnClearActivity()
void BiosSessionService::OnClearActivity (EBiosError error) inline protected
Callback function.
Parameters
error error indicating success or fail of the async operation.
Definition at line 138 of file BiosSessionService.c.
  {
  }
OnEnterGameplaySession()
void BiosSessionService::OnEnterGameplaySession (string session_address, int session_port, EBiosError error) inline protected
Callback function.
Parameters
session_address server IP address. Empty if failed.
session_port server port. 0 if failed.
error error indicating success or fail of the async operation.
Definition at line 214 of file BiosSessionService.c.
  {
    if (!OnlineServices.ErrorCaught(error))
    {
      SetGameplayActivityAsync(session_address, session_port);
      if (OnlineServices.GetPendingInviteList())
        InviteToGameplaySessionAsync(session_address, session_port, OnlineServices.GetPendingInviteList());
      //OnlineServices.GetCurrentServerInfo(session_address, session_port);
    }
  }
References OnlineServices::ErrorCaught(), OnlineServices::GetPendingInviteList(), InviteToGameplaySessionAsync(), and SetGameplayActivityAsync().
OnGetGameplaySession()
void BiosSessionService::OnGetGameplaySession (string session_address, int session_port) inline protected
Callback function.
Parameters
session_address server IP address.
session_port server port.
Definition at line 147 of file BiosSessionService.c.
  {
    m_GetSessionAttempts = 0;
    switch (g_Game.GetGameState())
    {
    case DayZGameState.IN_GAME:
    {
      string addr;
      int port;
      bool found = GetGame().GetHostAddress(addr, port);
      if (addr != session_address || port != session_port)
      {
        if (found)
        {
          OnlineServices.SetInviteServerInfo(session_address, session_port);
          g_Game.GetUIManager().CloseAll();
          if (!g_Game.GetUIManager().EnterScriptedMenu(MENU_INVITE_TIMER, null))
            NotificationSystem.AddNotification(NotificationType.CONNECT_FAIL_GENERIC, NotificationSystem.DEFAULT_TIME_DISPLAYED);
        }
        else
          NotificationSystem.AddNotification(NotificationType.JOIN_FAIL_GET_SESSION, NotificationSystem.DEFAULT_TIME_DISPLAYED);
      }
      else
        NotificationSystem.AddNotification(NotificationType.INVITE_FAIL_SAME_SERVER, NotificationSystem.DEFAULT_TIME_DISPLAYED, "#ps4_already_in_session");
      break;
    }
    case DayZGameState.CONNECTING:
    {
      g_Game.DisconnectSessionEx(DISCONNECT_SESSION_FLAGS_FORCE);
      // Intentionally no break, fall through to connecting
    }
    default:
    {
      g_Game.ConnectFromJoin(session_address, session_port);
      break;
    }
    }
  }
References NotificationSystem::AddNotification(), NotificationSystem::DEFAULT_TIME_DISPLAYED, DISCONNECT_SESSION_FLAGS_FORCE, g_Game, GetGame(), m_GetSessionAttempts, MENU_INVITE_TIMER, and OnlineServices::SetInviteServerInfo().
OnGetSessionError()
void BiosSessionService::OnGetSessionError (EBiosError error) inline protected
//! Callback function, not implemented
Callback function
Parameters
error error indicating fail of the async operation. Cannot be OK.
Definition at line 195 of file BiosSessionService.c.
  {
    OnlineServices.ErrorCaught(error);
    m_GetSessionAttempts++;
#ifdef PLATFORM_XBOX
    GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(TryGetSession, 100, false, "");
#endif
#ifdef PLATFORM_PS4
    g_Game.DisconnectSessionEx(DISCONNECT_SESSION_FLAGS_JOIN);
#endif
  }
References CALL_CATEGORY_SYSTEM, DISCONNECT_SESSION_FLAGS_JOIN, OnlineServices::ErrorCaught(), g_Game, GetGame(), m_GetSessionAttempts, and TryGetSession().
OnInviteToGameplaySession()
void BiosSessionService::OnInviteToGameplaySession (EBiosError error) inline protected
Callback function.
Parameters
error indicating success or fail of the async operation.
Definition at line 247 of file BiosSessionService.c.
  {
  }
OnLeaveGameplaySession()
void BiosSessionService::OnLeaveGameplaySession (EBiosError error) inline protected
Callback function.
Parameters
error error indicating success or fail of the async operation.
Definition at line 230 of file BiosSessionService.c.
  {
  }
OnSessionPlayerListUpdate()
proto native void BiosSessionService::OnSessionPlayerListUpdate (array< string > newPlayers) protected
Alerts engine that players in current session have changed.
Parameters
newPlayers players that have just joined the server. When player joins a server, ALL players already on server count as new players.
OnSetActivity()
void BiosSessionService::OnSetActivity (EBiosError error) inline protected
Callback function.
Parameters
error error indicating success or fail of the async operation.
Definition at line 129 of file BiosSessionService.c.
  {
    OnlineServices.ErrorCaught(error);
  }
References OnlineServices::ErrorCaught().
OnShowInviteToGameplaySession()
void BiosSessionService::OnShowInviteToGameplaySession (EBiosError error) inline protected
Callback function.
Parameters
error indicating success or fail of the async operation.
Definition at line 238 of file BiosSessionService.c.
  {
    OnlineServices.ErrorCaught(error);
  }
References OnlineServices::ErrorCaught().
SetGameplayActivityAsync()
proto native EBiosError BiosSessionService::SetGameplayActivityAsync (string session_address, int session_port) protected
Sets the activity to a gameplay session.
The async result is returned in the OnSetActivity callback. Expected errors: ERR_NOT_FOUND - when attempting to set a gameplay session activity the user is not part of.
Parameters
session_address server IP address.
session_port server port.
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnEnterGameplaySession().
SetMultiplayState()
proto native void BiosSessionService::SetMultiplayState (bool is_active) protected
Notifiy about interactive multiplayer state.
ShowInviteToGameplaySessionAsync()
proto native EBiosError BiosSessionService::ShowInviteToGameplaySessionAsync (string session_address, int session_port) protected
Show system UI to invite friends to current gameplay session.
The async result is returned in the OnShowInviteToGameplaySession callback. On Xbox, if session with session_address and session_port does not exist, then xbox show message "We could not send the invite".
Parameters
session_address server IP address.
session_port server port.
Returns
EBiosError indicating if the async operation is pending.
TryGetSession()
void BiosSessionService::TryGetSession (string join_handle = "") inline protected
Gets a session from a join handle.
The async result is returned in the OnGetGameplaySession, OnGetLobbySession or OnGetSessionError callback, dependinng on the type of session, or error. Expected errors:
Parameters
join_handle the parsed join handle.
Returns
EBiosError indicating if the async operation is pending.
Definition at line 47 of file BiosSessionService.c.
  {
    if (join_handle != "")
    {
      m_GetSessionAttempts = 0;
      m_CurrentHandle = join_handle;
    }
    if (m_GetSessionAttempts < 10)
      GetSessionAsync(m_CurrentHandle);
    else
      g_Game.DisconnectSessionEx(DISCONNECT_SESSION_FLAGS_JOIN);
  }
References DISCONNECT_SESSION_FLAGS_JOIN, g_Game, GetSessionAsync(), m_CurrentHandle, and m_GetSessionAttempts.
Referenced by OnGetSessionError().
Member Data Documentation
m_CurrentHandle
string BiosSessionService::m_CurrentHandle protected
Definition at line 4 of file BiosSessionService.c.
Referenced by TryGetSession().
m_GetSessionAttempts
int BiosSessionService::m_GetSessionAttempts protected
Definition at line 3 of file BiosSessionService.c.
Referenced by OnGetGameplaySession(), OnGetSessionError(), and TryGetSession().
The documentation for this class was generated from the following file:
scripts/3_Game/Services/BiosSessionService.c