DayZ: scripts/4_World/Entities/Firearms/Debug.c File Reference
Debug.c File Reference
Functions
void wpnPrint (string s)
void wpnDebugPrint (string s)
void wpnDebugSpam (string s)
void wpnDebugSpamALot (string s)
Function Documentation
wpnDebugPrint()
void wpnDebugPrint (string s)
Definition at line 9 of file Debug.c.
{
#ifdef WPN_DEBUG
  PrintToRPT("" + s); // comment/uncomment to hide/see debug logs
#else
  //Print("" + s); // comment/uncomment to hide/see debug logs
#endif
}
References PrintToRPT().
Referenced by AbortWeaponEvent(), Weapon::CanRemoveFromHands(), ejectBulletAndStoreInMagazine(), WeaponGuardBase::GuardCondition(), GuardCondition(), HandleWeaponEvents(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::LoadAndSetCurrentFSMState(), Weapon::LoadCurrentFSMState(), magazinesHaveEqualSizes(), WeaponStateBase::OnAbort(), WeaponChambering_Base::OnAbort(), OnAbort(), WeaponStateBase::OnEntry(), WeaponChambering_Base::OnEntry(), WeaponFire::OnEntry(), WeaponChambering_Base::OnExit(), WeaponChambering_Cartridge::OnExit(), WeaponStateBase::OnExit(), Weapon::OnStoreLoad(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::OnStoreLoad(), WeaponStartAction::OnUpdate(), PostWeaponEvent(), pushToChamberFromAttachedMagazine(), pushToChamberFromInnerMagazine(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::RandomizeFSMStateEx(), Weapon::SaveCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentUnstableFSMState(), Weapon::SyncEventToRemote(), and HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ValidateAndRepairHelper().
wpnDebugSpam()
void wpnDebugSpam (string s)
Definition at line 17 of file Debug.c.
{
#ifdef WPN_DEBUG_SPAM
  PrintToRPT("" + s); // comment/uncomment to hide/see debug logs
#else
  //Print("" + s); // comment/uncomment to hide/see debug logs
#endif
}
References PrintToRPT().
Referenced by WeaponStateBase::LoadCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::LoadCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::LoadCurrentUnstableFSMState(), WeaponStateBase::SaveCurrentFSMState(), and HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentUnstableFSMState().
wpnDebugSpamALot()
void wpnDebugSpamALot (string s)
Definition at line 25 of file Debug.c.
{
#ifdef WPN_DEBUG_SPAM_FREQ
  PrintToRPT("" + s); // comment/uncomment to hide/see debug logs
#else
  //Print("" + s); // comment/uncomment to hide/see debug logs
#endif
}
References PrintToRPT().
Referenced by HandleWeaponEvents(), and HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::OnStoreSave().
wpnPrint()
void wpnPrint (string s)
Definition at line 1 of file Debug.c.
{
#ifdef WPN_DEBUG
  PrintToRPT("" + s); // comment/uncomment to hide/see at least important info
#else
  //Print("" + s); // comment/uncomment to hide/see at least important info
#endif
}
References PrintToRPT().
Referenced by WeaponStableState::OnEntry(), WeaponStateJammed::OnEntry(), WeaponStartAction::OnEntry(), WeaponFire::OnEntry(), OnEntry(), OnExit(), WeaponStableState::OnExit(), and WeaponStateJammed::OnExit().