DayZ: ActionPushCar Class Reference
ActionPushCar Class Reference
Private Member Functions
void ActionPushCar ()
override GetInputType ()
override void CreateConditionComponents ()
override bool HasAlternativeInterrupt ()
override ActionData CreateActionData ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnUpdate (ActionData action_data)
override void OnStart (ActionData action_data)
override void OnStartServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnEndInput (ActionData action_data)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
float GetDirectionDot (Object target, EntityAI player)
CarScript GetCar (ActionTarget target)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 126 of file ActionPushCar.c.
Constructor & Destructor Documentation
ActionPushCar()
void ActionPushCar::ActionPushCar () inline private
Definition at line 128 of file ActionPushCar.c.
  {
    m_CallbackClass = ActionPushCarCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_VEHICLE_PUSH;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
    m_Text = "#push_car";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionPushCar::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 160 of file ActionPushCar.c.
  {
    if (!player.IsPlayerInStance(DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH))
      return false;
    if (!player.GetSurfaceType())
      return false;
    if (!IsInReach(player, target, UAMaxDistances.SMALL))
      return false;
    if (!player.CanConsumeStamina(EStaminaConsumers.PUSH))
      return false;
    CarScript car = GetCar(target);
    if (car)
    {
      if (car.GetGear() != CarGear.NEUTRAL)
        return false;
      if (Math.AbsFloat(GetDirectionDot(car, player)) < 0.85)
        return false;
      return true;
    }
    return false;
  }
References Math::AbsFloat(), GetCar(), GetDirectionDot(), IsInReach(), and UAMaxDistances::SMALL.
CreateActionData()
override ActionData ActionPushCar::CreateActionData () inline private
Definition at line 154 of file ActionPushCar.c.
  {
    ActionPushCarData data = new ActionPushCarData();
    return data;
  }
CreateConditionComponents()
override void ActionPushCar::CreateConditionComponents () inline private
Definition at line 143 of file ActionPushCar.c.
  {
    m_ConditionItem = new CCINotPresent();
    m_ConditionTarget = new CCTCursorNoRuinCheck(UAMaxDistances.DEFAULT);
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetCar()
CarScript ActionPushCar::GetCar (ActionTarget target) inline private
Definition at line 300 of file ActionPushCar.c.
  {
    if (target.IsProxy())
      return CarScript.Cast(target.GetParent());
    return CarScript.Cast(target.GetObject());
  }
Referenced by ActionCondition(), and OnStart().
GetDirectionDot()
float ActionPushCar::GetDirectionDot (Object target, EntityAI player) inline private
Definition at line 295 of file ActionPushCar.c.
  {
    return vector.Dot(target.GetDirection(), player.GetDirection());
  }
References vector::Dot().
Referenced by ActionCondition(), and OnStartServer().
GetInputType()
override ActionPushCar::GetInputType () inline private
Definition at line 138 of file ActionPushCar.c.
  {
    return ContinuousInteractActionInput;
  }
HandleReciveData()
override void ActionPushCar::HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 287 of file ActionPushCar.c.
  {
    super.HandleReciveData(action_recive_data, action_data);
    ActionPushCarDataReceiveData receiveData = ActionPushCarDataReceiveData.Cast(action_recive_data);
    receiveData.m_Car = receiveData.m_Car;
  }
HasAlternativeInterrupt()
override bool ActionPushCar::HasAlternativeInterrupt () inline private
Definition at line 149 of file ActionPushCar.c.
  {
    return true;
  }
OnEndInput()
override void ActionPushCar::OnEndInput (ActionData action_data) inline private
Definition at line 251 of file ActionPushCar.c.
  {
    super.OnEndInput(action_data);
    ActionPushCarData data = ActionPushCarData.Cast(action_data);
    data.m_State = UA_CANCEL;
    data.m_EndType = 1;
    data.m_NeedUpdate = false;
  }
References UA_CANCEL.
OnEndServer()
override void ActionPushCar::OnEndServer (ActionData action_data) inline private
Definition at line 242 of file ActionPushCar.c.
  {
    super.OnEndServer(action_data);
    ActionPushCarData data = ActionPushCarData.Cast(action_data);
    if (data.m_Car)
      data.m_Car.SetBrakesActivateWithoutDriver(true);
  }
OnStart()
override void ActionPushCar::OnStart (ActionData action_data) inline private
Definition at line 213 of file ActionPushCar.c.
  {
    super.OnStart(action_data);
    ActionPushCarData data = ActionPushCarData.Cast(action_data);
    data.m_Car = GetCar(action_data.m_Target);
    data.m_Origin = data.m_Car.GetPosition();
    data.m_NeedUpdate = true;
  }
References GetCar().
OnStartServer()
override void ActionPushCar::OnStartServer (ActionData action_data) inline private
Definition at line 223 of file ActionPushCar.c.
  {
    super.OnStartServer(action_data);
    ActionPushCarData data = ActionPushCarData.Cast(action_data);
    if (data.m_Car)
    {
      data.m_Car.SetBrake(0.0);
      data.m_Car.SetHandbrake(0.0);
      data.m_Car.SetBrakesActivateWithoutDriver(false);
    }
    data.m_PushDirection = -1;
    if (GetDirectionDot(data.m_Car, data.m_Player) > 0)
      data.m_PushDirection = 1;
  }
References GetDirectionDot().
OnUpdate()
override void ActionPushCar::OnUpdate (ActionData action_data) inline private
Definition at line 189 of file ActionPushCar.c.
  {
    super.OnUpdate(action_data);
    ActionPushCarData data = ActionPushCarData.Cast(action_data);
    if (data.m_NeedUpdate)
    {
      if (!data.m_Player.CanConsumeStamina(EStaminaConsumers.PUSH))
      {
        data.m_State = UA_CANCEL;
        data.m_NeedUpdate = false;
        return;
      }
      if (vector.Distance(data.m_Car.GetPosition(), data.m_Origin) > 0.5)
      {
        data.m_State = UA_FINISHED;
        data.m_EndType = 0;
        data.m_NeedUpdate = false;
      }
    }
  }
References vector::Distance(), UA_CANCEL, and UA_FINISHED.
ReadFromContext()
override bool ActionPushCar::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 270 of file ActionPushCar.c.
  {
    if (!action_recive_data)
      action_recive_data = new ActionPushCarDataReceiveData();
    super.ReadFromContext(ctx, action_recive_data);
    CarScript car;
    if (!ctx.Read(car))
      return false;
    ActionPushCarDataReceiveData receiveData = ActionPushCarDataReceiveData.Cast(action_recive_data);
    receiveData.m_Car = car;
    return true;
  }
WriteToContext()
override void ActionPushCar::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 261 of file ActionPushCar.c.
  {
    super.WriteToContext(ctx, action_data);
    ActionPushCarData data = ActionPushCarData.Cast(action_data);
    ctx.Write(data.m_Car);
  }
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionPushCar.c