DayZ: HeadGear_Base Class Reference
HeadGear_Base Class Reference
hard helmet base
Protected Member Functions
set< int > GetAttachmentExclusionInitSlotValue (int slotId)
set< int > GetAttachmentExclusionInitSlotValue (int slotId)
set< int > GetAttachmentExclusionInitSlotValue (int slotId)
set< int > GetAttachmentExclusionInitSlotValue (int slotId)
Private Member Functions
override void SetActions ()
override void SetActions ()
override void SetActions ()
void ~BurlapSackCover ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void OnWasAttached (EntityAI parent, int slot_id)
override bool CanPutInCargo (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
void OnRemovedFromHead (PlayerBase player)
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
Private Member Functions inherited from Clothing
void InitGlobalExclusionValues ()
void CheckParent ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnWork (float consumed_energy)
void OnLightCreated ()
void CreateHeadtorchLight ()
void AttachLightOnHead (EntityAI person)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void SetActions ()
override bool IsLightSource ()
override ItemBase GetLightSourceItem ()
override void OnInvisibleSet (bool invisible)
Private Attributes
PlayerBase m_Player
Detailed Description
hard helmet base
Definition at line 1 of file BaseballCap_ColorBase.c.
Constructor & Destructor Documentation
~BurlapSackCover()
void HeadGear_Base::~BurlapSackCover () inline private
Definition at line 5 of file BurlapSackCover.c.
  {
    if (m_Player)
      OnRemovedFromHead(m_Player);
  }
References m_Player.
Member Function Documentation
CanDetachAttachment()
override bool HeadGear_Base::CanDetachAttachment (EntityAI parent) inline private
Definition at line 52 of file BurlapSackCover.c.
  {
    return false;
  }
CanPutInCargo()
override bool HeadGear_Base::CanPutInCargo (EntityAI parent) inline private
Definition at line 41 of file BurlapSackCover.c.
  {
    if (!super.CanPutInCargo(parent))
      return false;
    if (parent && parent != this)
      return true;
    return false;
  }
EEItemLocationChanged()
override void HeadGear_Base::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 11 of file BurlapSackCover.c.
  {
    super.EEItemLocationChanged(oldLoc, newLoc);
    if (GetGame().IsDedicatedServer() && newLoc.GetType() == InventoryLocationType.GROUND)
    {
      EntityAI newItem = EntityAI.Cast(GetGame().CreateObjectEx("BurlapSack", newLoc.GetPos(), ECE_PLACE_ON_SURFACE, RF_DEFAULT));
      MiscGameplayFunctions.TransferItemProperties(this, newItem);
      DeleteSafe();
    }
  }
References ECE_PLACE_ON_SURFACE, GetGame(), and RF_DEFAULT.
GetAttachmentExclusionInitSlotValue() [1/4]
set< int > HeadGear_Base::GetAttachmentExclusionInitSlotValue (int slotId) inline protected
Definition at line 68 of file BurlapSackCover.c.
  {
    set<int> ret = super.GetAttachmentExclusionInitSlotValue(slotId);
    if (slotId == InventorySlots.HEADGEAR)
      ret.Insert(EAttExclusions.SHAVING_HEADGEAR_ATT_0);
    return ret;
  }
GetAttachmentExclusionInitSlotValue() [2/4]
set< int > HeadGear_Base::GetAttachmentExclusionInitSlotValue (int slotId) inline protected
Definition at line 3 of file Chainmail_Coif.c.
  {
    set<int> ret = super.GetAttachmentExclusionInitSlotValue(slotId);
    if (slotId == InventorySlots.HEADGEAR)
    {
      ret.Insert(EAttExclusions.LEGACY_MASK_HEADGEAR); //same as 'noMask' used to be
      ret.Insert(EAttExclusions.SHAVING_HEADGEAR_ATT_0);
    }
    return ret;
  }
GetAttachmentExclusionInitSlotValue() [3/4]
set< int > HeadGear_Base::GetAttachmentExclusionInitSlotValue (int slotId) inline protected
Definition at line 9 of file OKZKCap_ColorBase.c.
  {
    set<int> ret = super.GetAttachmentExclusionInitSlotValue(slotId);
    if (slotId == InventorySlots.HEADGEAR)
    {
      ret.Insert(EAttExclusions.EXCLUSION_MASK_0);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_1);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_2);
      ret.Insert(EAttExclusions.EXCLUSION_MASK_3);
      ret.Insert(EAttExclusions.SHAVING_HEADGEAR_ATT_0);
    }
    return ret;
  }
GetAttachmentExclusionInitSlotValue() [4/4]
set< int > HeadGear_Base::GetAttachmentExclusionInitSlotValue (int slotId) inline protected
Definition at line 9 of file WinterCoif_ColorBase.c.
  {
    set<int> ret = super.GetAttachmentExclusionInitSlotValue(slotId);
    if (slotId == InventorySlots.HEADGEAR)
      ret.Insert(EAttExclusions.EXCLUSION_MASK_3);
    return ret;
  }
OnRemovedFromHead()
void HeadGear_Base::OnRemovedFromHead (PlayerBase player) inline private
Definition at line 57 of file BurlapSackCover.c.
  {
    if (player.IsControlledPlayer())
    {
      PPERequesterBank.GetRequester(PPERequester_BurlapSackEffects).Stop();
      player.SetInventorySoftLock(false);
      player.SetMasterAttenuation("");
    }
    SetInvisibleRecursive(false, player, {InventorySlots.MASK, InventorySlots.EYEWEAR});
  }
OnWasAttached()
override void HeadGear_Base::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 23 of file BurlapSackCover.c.
  {
    super.OnWasAttached(parent, slot_id);
    Class.CastTo(m_Player, parent.GetHierarchyRootPlayer());
    if ((!GetGame().IsDedicatedServer()) && m_Player && m_Player.IsControlledPlayer() && slot_id == InventorySlots.HEADGEAR)
    {
      PPERequesterBank.GetRequester(PPERequester_BurlapSackEffects).Start();
      m_Player.SetInventorySoftLock(true);
      m_Player.SetMasterAttenuation("BurlapSackAttenuation");
      if (GetGame().GetUIManager().IsMenuOpen(MENU_INVENTORY))
        GetGame().GetMission().HideInventory();
    }
    SetInvisibleRecursive(true, m_Player, {InventorySlots.MASK, InventorySlots.EYEWEAR});
  }
References Class::CastTo(), GetGame(), m_Player, and MENU_INVENTORY.
SetActions() [1/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file BaseballCap_ColorBase.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [2/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file BeanieHat_ColorBase.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [3/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file BoonieHat_ColorBase.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [4/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file FlatCap_ColorBase.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [5/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file HeadCover_improvised.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [6/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file MedicalScrubsHat_ColorBase.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [7/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file MorozkoHat.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [8/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file OKZKCap_ColorBase.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [9/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file PetushokHat_ColorBase.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [10/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file PilotkaCap.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [11/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file PrisonerCap.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [12/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file RadarCap_ColorBase.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [13/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file SantasHat.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [14/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file TankerHelmet.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [15/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file Ushanka_ColorBase.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [16/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file WinterCoif_ColorBase.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [17/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file WitchHat.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [18/18]
override void HeadGear_Base::SetActions () inline private
Definition at line 3 of file ZmijovkaCap_ColorBase.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
Member Data Documentation
m_Player
PlayerBase HeadGear_Base::m_Player private
Definition at line 3 of file BurlapSackCover.c.
The documentation for this class was generated from the following files:
scripts/4_World/Entities/ItemBase/Clothing/BaseballCap_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/BurlapSackCover.c
scripts/4_World/Entities/ItemBase/Clothing/BeanieHat_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/BoonieHat_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/Chainmail_Coif.c
scripts/4_World/Entities/ItemBase/Clothing/FlatCap_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/HeadCover_improvised.c
scripts/4_World/Entities/ItemBase/Clothing/MedicalScrubsHat_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/MorozkoHat.c
scripts/4_World/Entities/ItemBase/Clothing/OKZKCap_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/PetushokHat_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/PilotkaCap.c
scripts/4_World/Entities/ItemBase/Clothing/PrisonerCap.c
scripts/4_World/Entities/ItemBase/Clothing/RadarCap_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/SantasHat.c
scripts/4_World/Entities/ItemBase/Clothing/TankerHelmet.c
scripts/4_World/Entities/ItemBase/Clothing/Ushanka_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/WinterCoif_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/WitchHat.c
scripts/4_World/Entities/ItemBase/Clothing/ZmijovkaCap_ColorBase.c