DayZ: scripts/4_World/Plugins/PluginBase/PluginFileHandler/PluginLocalEnscriptHistory.c File Reference
PluginLocalEnscriptHistory.c File Reference
Classes
class PluginLocalHistoryBase
Functions
class PluginLocalEnscriptHistory extends PluginLocalHistoryBase GetSubFolderName ()
override string GetFileName ()
Function Documentation
GetFileName()
override string GetFileName ()
Definition at line 26 of file PluginLocalEnscriptHistory.c.
  {
    if (!FileExist(GetSubFolderName()))//---ALL LINES CONTAINING THIS COMMENT CAN BE REMOVED IN 1.23
      return "$profile:script_enscriptServer.history";//---ALL LINES CONTAINING THIS COMMENT CAN BE REMOVED IN 1.23
    return GetSubFolderName() + CFG_FILE_ENS_HISTORY_SERVER;
  }
References CFG_FILE_ENS_HISTORY_SERVER, FileExist(), and GetSubFolderName().
Referenced by PluginConfigHandler::SceneDataLoad().
GetSubFolderName()
override string GetSubFolderName ()
Definition at line 1 of file PluginLocalEnscriptHistory.c.
  {
    return CFG_FILE_DEBUG_DIR;
  }
Referenced by PluginConfigHandler::GetFileName(), PluginLocalHistoryBase::GetFileName(), GetFileName(), and PluginBase::SaveFile().