DayZ: Mask_Base Class Reference
Mask_Base Class Reference
gas mask base
Protected Member Functions
void InitGlobalExclusionValues ()
set< int > GetAttachmentExclusionInitSlotValue (int slotId)
void InitGlobalExclusionValues ()
void InitGlobalExclusionValues ()
void InitGlobalExclusionValues ()
set< int > GetAttachmentExclusionInitSlotValue (int slotId)
Private Member Functions
override void SetActions ()
override void SetActions ()
override void SetActions ()
override bool IsGasMask ()
override array< int > GetEffectWidgetTypes ()
override bool AllowFoodConsumption ()
override void OnDebugSpawn ()
EntityAI GetExternalFilter ()
bool HasValidFilter ()
has either external or integrated non-empty non-ruined filter ?
float GetFilterQuantityMax ()
float GetFilterQuantity ()
float GetFilterQuantity01 ()
bool IsExternalFilterAttached ()
bool HasIntegratedFilter ()
bool CanHaveExternalFilter ()
bool ConsumeQuantity (float quantity, PlayerBase consumer_player)
void OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player)
void OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player, float quantity)
void MouthRag ()
override bool CanDetachAttachment (EntityAI parent)
override bool IsObstructingVoice ()
override int GetVoiceEffect ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void OnWasAttached (EntityAI parent, int slot_id)
void SetIncomingLambaBool (bool state)
bool GetIncomingLambdaBool ()
override void SetActions ()
override void SetActions ()
Private Member Functions inherited from Clothing
void InitGlobalExclusionValues ()
void CheckParent ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnWork (float consumed_energy)
void OnLightCreated ()
void CreateHeadtorchLight ()
void AttachLightOnHead (EntityAI person)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void SetActions ()
override bool IsLightSource ()
override ItemBase GetLightSourceItem ()
override void OnInvisibleSet (bool invisible)
Private Attributes
float m_LowFilterEventTime
bool m_IncomingLambdaChange
Detailed Description
gas mask base
Definition at line 1 of file Balaclava3Holes_ColorBase.c.
Member Function Documentation
AllowFoodConsumption()
override bool Mask_Base::AllowFoodConsumption () inline private
Definition at line 16 of file MaskBase.c.
  {
    return false;
  }
CanDetachAttachment()
override bool Mask_Base::CanDetachAttachment (EntityAI parent) inline private
Definition at line 10 of file MouthRag.c.
  {
    return m_IncomingLambdaChange;
  }
References m_IncomingLambdaChange.
CanHaveExternalFilter()
bool Mask_Base::CanHaveExternalFilter () inline private
Definition at line 96 of file MaskBase.c.
  {
    return !HasIntegratedFilter();
  }
ConsumeQuantity()
bool Mask_Base::ConsumeQuantity (float quantity, PlayerBase consumer_player) inline private
Definition at line 101 of file MaskBase.c.
  {
    ItemBase filter = ItemBase.Cast(FindAttachmentBySlotName("GasMaskFilter"));
    ItemBase itemToConsume = null;
    if (HasQuantity() && GetQuantity() > 0)
    {
      itemToConsume = this;//this mask itself has quantity(masks with integrated, non-attached filter)
    }
    else if (HasValidFilter())
      itemToConsume = filter;
    if (itemToConsume)
    {
      itemToConsume.AddQuantity(-quantity);
      OnQuantityConsumed(itemToConsume, consumer_player, quantity);
      return true;
    }
    return false;
  }
References GetQuantity(), and HasQuantity().
EEItemLocationChanged()
override void Mask_Base::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 25 of file MouthRag.c.
  {
    super.EEItemLocationChanged(oldLoc, newLoc);
    if (GetGame().IsDedicatedServer())
    {
      PlayerBase playerOld;
      PlayerBase playerNew;
      if (oldLoc.GetParent())
        Class.CastTo(playerOld, oldLoc.GetParent().GetHierarchyRootPlayer());
      if (newLoc.GetParent())
        Class.CastTo(playerNew, newLoc.GetParent().GetHierarchyRootPlayer());
      if (newLoc.GetType() == InventoryLocationType.GROUND)
      {
        ItemBase newItem;
        if (Class.CastTo(newItem, GetGame().CreateObjectEx("Rag", newLoc.GetPos(), ECE_PLACE_ON_SURFACE, RF_DEFAULT)))
        {
          MiscGameplayFunctions.TransferItemProperties(this, newItem);
          newItem.SetQuantity(1);
          DeleteSafe();
        }
      }
    }
  }
References Class::CastTo(), ECE_PLACE_ON_SURFACE, GetGame(), and RF_DEFAULT.
GetAttachmentExclusionInitSlotValue() [1/2]
set< int > Mask_Base::GetAttachmentExclusionInitSlotValue (int slotId) inline protected
Definition at line 14 of file CrookedNose.c.
  {
    set<int> ret = super.GetAttachmentExclusionInitSlotValue(slotId);
    //allows shaving
    ret.RemoveItem(EAttExclusions.SHAVING_MASK_ATT_0);
    return ret;
  }
GetAttachmentExclusionInitSlotValue() [2/2]
set< int > Mask_Base::GetAttachmentExclusionInitSlotValue (int slotId) inline protected
Definition at line 171 of file Clothing_Base.c.
  {
    set<int> ret = super.GetAttachmentExclusionInitSlotValue(slotId);
    if (slotId == InventorySlots.MASK)
      ret.Insert(EAttExclusions.SHAVING_MASK_ATT_0);
    return ret;
  }
GetEffectWidgetTypes()
override array< int > Mask_Base::GetEffectWidgetTypes () inline private
Definition at line 11 of file MaskBase.c.
  {
    return {EffectWidgetsTypes.MASK_OCCLUDER, EffectWidgetsTypes.MASK_BREATH};
  }
GetExternalFilter()
EntityAI Mask_Base::GetExternalFilter () inline private
Definition at line 26 of file MaskBase.c.
  {
    return FindAttachmentBySlotName("GasMaskFilter");
  }
GetFilterQuantity()
float Mask_Base::GetFilterQuantity () inline private
Definition at line 55 of file MaskBase.c.
  {
    ItemBase filter = ItemBase.Cast(GetExternalFilter());
    if (filter)
      return filter.GetQuantity();
    else
      return GetQuantity();
  }
References GetQuantity().
GetFilterQuantity01()
float Mask_Base::GetFilterQuantity01 () inline private
Definition at line 64 of file MaskBase.c.
  {
    if (!HasValidFilter())
      return 0;
    ItemBase filter = ItemBase.Cast(GetExternalFilter());
    float quantity, quantityMax;
    if (filter)
    {
      quantity = filter.GetQuantity();
      quantityMax = filter.GetQuantityMax();
    }
    else
    {
      quantity = GetQuantity();
      quantityMax = GetQuantityMax();
    }
    return Math.InverseLerp(0, quantityMax, quantity);
  }
References GetQuantity(), GetQuantityMax(), Math::InverseLerp(), and quantityMax.
GetFilterQuantityMax()
float Mask_Base::GetFilterQuantityMax () inline private
Definition at line 43 of file MaskBase.c.
  {
    ItemBase filter = ItemBase.Cast(GetExternalFilter());
    if (filter) //mask can have a filter, and filter is attached
      return filter.GetQuantityMax();
    else if (HasQuantity())//filter was not attached, checking if mask has internal filter
      return GetQuantityMax();
    //mask does not have a filter attached nor does it have internal filter, max quantity can't be obtained
    return 0;
  }
References GetQuantityMax(), and HasQuantity().
GetIncomingLambdaBool()
bool Mask_Base::GetIncomingLambdaBool () inline private
Definition at line 66 of file MouthRag.c.
  {
    return m_IncomingLambdaChange;
  }
References m_IncomingLambdaChange.
GetVoiceEffect()
override int Mask_Base::GetVoiceEffect () inline private
Definition at line 20 of file MouthRag.c.
  {
    return VoiceEffectObstruction;
  }
HasIntegratedFilter()
bool Mask_Base::HasIntegratedFilter () inline private
Definition at line 91 of file MaskBase.c.
  {
    return HasQuantity();
  }
References HasQuantity().
HasValidFilter()
bool Mask_Base::HasValidFilter () inline private
has either external or integrated non-empty non-ruined filter ?
Definition at line 32 of file MaskBase.c.
  {
    ItemBase filter = ItemBase.Cast(GetExternalFilter());
    if (filter && !filter.IsRuined() && filter.GetQuantity() > 0)
      return true;
    else if (GetQuantity() > 0 && !IsRuined())
      return true;
    return false;
  }
References GetQuantity().
InitGlobalExclusionValues() [1/4]
void Mask_Base::InitGlobalExclusionValues () inline protected
Definition at line 3 of file CrookedNose.c.
  {
    super.InitGlobalExclusionValues();
    AddSingleExclusionValueGlobal(EAttExclusions.EXCLUSION_MASK_0);
    AddSingleExclusionValueGlobal(EAttExclusions.EXCLUSION_MASK_1);
    AddSingleExclusionValueGlobal(EAttExclusions.EXCLUSION_MASK_2);
    AddSingleExclusionValueGlobal(EAttExclusions.EXCLUSION_HEADGEAR_HELMET_0);
  }
InitGlobalExclusionValues() [2/4]
void Mask_Base::InitGlobalExclusionValues () inline protected
Definition at line 3 of file HockeyMask.c.
  {
    super.InitGlobalExclusionValues();
    AddSingleExclusionValueGlobal(EAttExclusions.EXCLUSION_MASK_0);
    AddSingleExclusionValueGlobal(EAttExclusions.EXCLUSION_GLASSES_TIGHT_0);
    AddSingleExclusionValueGlobal(EAttExclusions.EXCLUSION_GLASSES_REGULAR_0);
  }
InitGlobalExclusionValues() [3/4]
void Mask_Base::InitGlobalExclusionValues () inline protected
Definition at line 130 of file MaskBase.c.
  {
    super.InitGlobalExclusionValues();
    AddSingleExclusionValueGlobal(EAttExclusions.EXCLUSION_MASK_2);
    AddSingleExclusionValueGlobal(EAttExclusions.EXCLUSION_GLASSES_TIGHT_0);
    AddSingleExclusionValueGlobal(EAttExclusions.EXCLUSION_HEADGEAR_HELMET_0);
  }
InitGlobalExclusionValues() [4/4]
void Mask_Base::InitGlobalExclusionValues () inline protected
Definition at line 9 of file SantasBeard.c.
  {
    super.InitGlobalExclusionValues();
    AddSingleExclusionValueGlobal(EAttExclusions.EXCLUSION_MASK_0);
  }
IsExternalFilterAttached()
bool Mask_Base::IsExternalFilterAttached () inline private
Definition at line 86 of file MaskBase.c.
  {
    return ItemBase.Cast(FindAttachmentBySlotName("GasMaskFilter")) != null;
  }
IsGasMask()
override bool Mask_Base::IsGasMask () inline private
Definition at line 6 of file MaskBase.c.
  {
    return true;
  }
IsObstructingVoice()
override bool Mask_Base::IsObstructingVoice () inline private
Definition at line 15 of file MouthRag.c.
  {
    return true;
  }
MouthRag()
void Mask_Base::MouthRag () inline private
Definition at line 5 of file MouthRag.c.
  {
    m_IncomingLambdaChange = false;
  }
OnDebugSpawn()
override void Mask_Base::OnDebugSpawn () inline private
Definition at line 21 of file MaskBase.c.
  {
    GetInventory().CreateInInventory("GasMask_Filter");
  }
OnQuantityConsumed() [1/2]
void Mask_Base::OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player) inline private
Definition at line 122 of file MaskBase.c.
{};
OnQuantityConsumed() [2/2]
void Mask_Base::OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player, float quantity) inline private
Definition at line 124 of file MaskBase.c.
  {
    float damage = quantity * filter.GetFilterDamageRatio();
    filter.AddHealth("", "", -damage);
  }
OnWasAttached()
override void Mask_Base::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 51 of file MouthRag.c.
  {
    super.OnWasAttached(parent, slot_id);
    if (parent.IsPlayer())
    {
      PlayerBase.Cast(parent).CheckForGag(); //gag removal action does check, since 'OnWasDetached' is not called on item destruction.
    }
  }
SetActions() [1/5]
override void Mask_Base::SetActions () inline private
Definition at line 3 of file Balaclava3Holes_ColorBase.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [2/5]
override void Mask_Base::SetActions () inline private
Definition at line 3 of file BalaclavaMask_ColorBase.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [3/5]
override void Mask_Base::SetActions () inline private
Definition at line 3 of file FaceCover_improvised.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [4/5]
override void Mask_Base::SetActions () inline private
Definition at line 3 of file SantasBeard.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [5/5]
override void Mask_Base::SetActions () inline private
Definition at line 3 of file SurgicalMask.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetIncomingLambaBool()
void Mask_Base::SetIncomingLambaBool (bool state) inline private
Definition at line 61 of file MouthRag.c.
  {
    m_IncomingLambdaChange = state;
  }
Member Data Documentation
m_IncomingLambdaChange
bool Mask_Base::m_IncomingLambdaChange private
Definition at line 3 of file MouthRag.c.
Referenced by CanDetachAttachment(), and GetIncomingLambdaBool().
m_LowFilterEventTime
float Mask_Base::m_LowFilterEventTime private
Definition at line 4 of file MaskBase.c.
The documentation for this class was generated from the following files:
scripts/4_World/Entities/ItemBase/Clothing/Balaclava3Holes_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/MaskBase.c
scripts/4_World/Entities/ItemBase/Clothing/MouthRag.c
scripts/4_World/Entities/ItemBase/Clothing/BalaclavaMask_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/CrookedNose.c
scripts/4_World/Entities/ItemBase/Clothing/FaceCover_improvised.c
scripts/4_World/Entities/ItemBase/Clothing/HockeyMask.c
scripts/4_World/Entities/ItemBase/Clothing/SantasBeard.c
scripts/4_World/Entities/ItemBase/Clothing/SurgicalMask.c
scripts/4_World/Entities/ItemBase/Clothing_Base.c