DayZ: ActionUncoverHeadTarget Class Reference
ActionUncoverHeadTarget Class Reference
Private Member Functions
void ActionUncoverHeadTarget ()
override void CreateConditionComponents ()
override GetInputType ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
bool IsWearingBurlap (PlayerBase player)
Detailed Description
Definition at line 9 of file ActionUncoverHeadTarget.c.
Constructor & Destructor Documentation
ActionUncoverHeadTarget()
void ActionUncoverHeadTarget::ActionUncoverHeadTarget () inline private
Definition at line 11 of file ActionUncoverHeadTarget.c.
  {
    m_CallbackClass = ActionUncoverHeadTargetCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
    m_Text = "#uncover_players_head";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionUncoverHeadTarget::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 31 of file ActionUncoverHeadTarget.c.
  {
    PlayerBase targetPlayer;
    if (Class.CastTo(targetPlayer, target.GetObject()))
    {
      if (IsWearingBurlap(targetPlayer))
        return true;
    }
    return false;
  }
References Class::CastTo(), and IsWearingBurlap().
CreateConditionComponents()
override void ActionUncoverHeadTarget::CreateConditionComponents () inline private
Definition at line 20 of file ActionUncoverHeadTarget.c.
  {
    m_ConditionItem = new CCINone;
    m_ConditionTarget = new CCTMan(UAMaxDistances.DEFAULT, false);
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetInputType()
override ActionUncoverHeadTarget::GetInputType () inline private
Definition at line 26 of file ActionUncoverHeadTarget.c.
  {
    return ContinuousInteractActionInput;
  }
IsWearingBurlap()
bool ActionUncoverHeadTarget::IsWearingBurlap (PlayerBase player) inline private
Definition at line 49 of file ActionUncoverHeadTarget.c.
  {
    EntityAI attachment;
    Class.CastTo(attachment, player.GetInventory().FindAttachment(InventorySlots.HEADGEAR));
    if (attachment && attachment.GetType() == "BurlapSackCover")
      return true;
    return false;
  }
References Class::CastTo().
Referenced by ActionCondition().
OnFinishProgressServer()
override void ActionUncoverHeadTarget::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 42 of file ActionUncoverHeadTarget.c.
  {
    PlayerBase targetPlayer = PlayerBase.Cast(action_data.m_Target.GetObject());
    if (CanReceiveAction(action_data.m_Target))
      UncoverHead(PlayerBase.Cast(action_data.m_Target.GetObject()), action_data.m_Player);
  }
References CanReceiveAction(), and ActionUncoverHeadBase::UncoverHead().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionUncoverHeadTarget.c