DayZ: ActionContinuousBaseCB Class Reference
ActionContinuousBaseCB Class Reference
Inherits ActionBaseCB.
Inherited by ActionActivateTrapCB [private], ActionArmExplosiveCB [private], ActionAttachExplosivesTriggerCB [private], ActionBandageSelfCB [private], ActionBandageTargetCB [private], ActionBreakLongWoodenStickCB [private], ActionBuildOvenCB [private], ActionBuildPartCB [private], ActionBuildStoneCircleCB [private], ActionBurnSewSelfCB [private], ActionBurnSewTargetCB [private], ActionBuryAshesCB [private], ActionBuryBodyCB [private], ActionCPRCB [private], ActionCheckPulseTargetCB [private], ActionCollectBloodSelfCB [private], ActionCollectBloodTargetCB [private], ActionCollectSampleSelfCB [private], ActionCollectSampleTargetCB [private], ActionConsumeCB [private], ActionCookOnStickCB [private], ActionCoverHeadSelfCB [private], ActionCoverHeadTargetCB [private], ActionCraftArmbandCB [private], ActionCraftBoltsCB [private], ActionCraftBoltsFeatherCB [private], ActionCraftBoneKnifeCB [private], ActionCraftBoneKnifeEnvCB [private], ActionCraftCB [private], ActionCraftImprovisedEyePatchCB [private], ActionCraftImprovisedFaceCoverCB [private], ActionCraftImprovisedFeetCoverCB [private], ActionCraftImprovisedHandsCoverCB [private], ActionCraftImprovisedHeadCoverCB [private], ActionCraftImprovisedLegsCoverCB [private], ActionCraftImprovisedTorsoCoverCB [private], ActionCraftRopeBeltCB [private], ActionCraftStoneKnifeEnvCB [private], ActionCreateGreenhouseGardenPlotCB [private], ActionDeCraftDrysackBagCB [private], ActionDeCraftRopeBeltCB [private], ActionDeCraftWitchHoodCoifCB [private], ActionDefibrilateSelfCB [private], ActionDefibrilateTargetCB [private], ActionDestroyCombinationLockCB [private], ActionDestroyPartCB [private], ActionDialCombinationLockCB [private], ActionDialCombinationLockOnTargetCB [private], ActionDigInStashCB [private], ActionDigOutStashCB [private], ActionDigWormsCB [private], ActionDisarmExplosiveCB [private], ActionDisarmMineCB [private], ActionDisinfectPlantCB [private], ActionDisinfectSelfCB [private], ActionDisinfectTargetCB [private], ActionDismantleGardenPlotCB [private], ActionDismantleOvenCB [private], ActionDismantlePartCB [private], ActionDismantleStoneCircleCB [private], ActionDrainLiquidCB [private], ActionDrinkCB [private], ActionDrinkPondContinuousCB [private], ActionDrinkWellContinuousCB [private], ActionEatBigCB [private], ActionEatCanCB [private], ActionEatFruitCB [private], ActionEatMeatCB [private], ActionEatSmallCanCB [private], ActionEmptyBottleBaseCB [private], ActionExtinguishFireplaceByExtinguisherCB [private], ActionExtinguishFireplaceByLiquidCB [private], ActionFeedVitaminBottleCB [private], ActionFertilizeSlotCB [private], ActionFillBottleBaseCB [private], ActionFillBrakesCB [private], ActionFillCoolantCB [private], ActionFillFuelCB [private], ActionFillGeneratorTankCB [private], ActionFillObjectCB [private], ActionFillOilCB [private], ActionFoldBaseBuildingObjectCB [private], ActionForceConsumeCB [private], ActionForceDrinkCB [private], ActionForceFeedCB [private], ActionForceFeedMeatCB [private], ActionForceFeedSmallCB [private], ActionGiveBloodTargetCB [private], ActionGiveSalineSelfCB [private], ActionGiveSalineTargetCB [private], ActionIgniteFireplaceByAirCB [private], ActionLightItemOnFireCB [private], ActionLoadMagazineCB [private], ActionLoadMagazineQuickCB [private], ActionLockDoorsCB [private], ActionManipulateFlagCB [private], ActionMeasureTemperatureSelfCB [private], ActionMeasureTemperatureTargetCB [private], ActionMineBushCB [private], ActionMineRockCB [private], ActionMountBarbedWireCB [private], ActionPackGiftCB [private], ActionPackTentCB [private], ActionPlaceOnGroundCB [private], ActionPourLiquidCB [private], ActionRaiseAndViewCB [private], ActionRaiseMegaphoneCB [private], ActionReadPaperCB [private], ActionRepackTentCB [private], ActionRepairCarChassisCB [private], ActionRepairCarEngineCB [private], ActionRepairCarPartCB [private], ActionRepairItemWithBlowtorchCB [private], ActionRepairPartCB [private], ActionRepairTentCB [private], ActionRepairTentPartCB [private], ActionRestrainSelfCB [private], ActionRestrainTargetCB [private], ActionSawPlanksCB [private], ActionSetAlarmClockCB [private], ActionSetKitchenTimerCB [private], ActionSewSelfCB [private], ActionSewTargetCB [private], ActionShaveCB [private], ActionShaveTargetCB [private], ActionSkinningCB [private], ActionSortAmmoPileCB [private], ActionSplintSelfCB [private], ActionSplintTargetCB [private], ActionStartCarCB [private], ActionStripCarrierVestCB [private], ActionTestBloodSelfCB [private], ActionTestBloodTargetCB [private], ActionTransferLiquidCB [private], ActionTuneFrequencyCB [private], ActionTuneRadioStationCB [private], ActionTurnValveCB [private], ActionUncoverHeadSelfCB [private], ActionUncoverHeadTargetCB [private], ActionUnlockDoorsCB [private], ActionUnmountBarbedWireCB [private], ActionUnpackBoxCB [private], ActionUnpackGiftCB [private], ActionUnrestrainSelfCB [private], ActionUnrestrainTargetCB [private], ActionUnrestrainTargetHandsCB [private], ActionUpgradeTorchFromGasPumpCB [private], ActionUseRangefinderCB [private], ActionWashHandsItemContinuousCB [private], ActionWashHandsWaterCB [private], ActionWashHandsWellCB [private], ActionWaterGardenSlotCB [private], ActionWaterPlantCB [private], ActionWorldCraftCB [private], ActionWringClothesCB [private], and ActionWritePaperCB [private].
Private Member Functions
bool CancelCondition ()
override void OnAnimationEvent (int pEventID)
override void InitActionComponent ()
override void EndActionComponent ()
void UserEndsAction ()
Private Member Functions inherited from ActionBaseCB
void ActionBaseCB ()
int GetPossileStanceMask ()
override void OnFinish (bool pCanceled)
void SetCommand (int command_uid)
void CreateActionComponent ()
void InitActionComponent ()
void ProgressActionComponent ()
void EndActionComponent ()
void Interrupt ()
void SetActionData (ActionData action_data)
override bool IsUserActionCallback ()
float GetActionComponentProgress ()
int GetActionState ()
ActionTarget GetTarget ()
Private Attributes
bool m_inLoop = false
bool m_callLoopEnd = false
Private Attributes inherited from ActionBaseCB
ActionData m_ActionData
SoundOnVehicle m_SoundObject
bool m_Canceled
bool m_Interrupted
Detailed Description
Definition at line 1 of file ActionContinuousBase.c.
Member Function Documentation
CancelCondition()
bool ActionContinuousBaseCB::CancelCondition () inline private
Definition at line 6 of file ActionContinuousBase.c.
  {
    if (!m_ActionData)
      return DefaultCancelCondition();
    if ((GetState() == STATE_LOOP_LOOP || GetState() == STATE_LOOP_LOOP2 || m_inLoop))
    {
      ActionContinuousBase actionS = ActionContinuousBase.Cast(m_ActionData.m_Action);
      if (m_ActionData.m_State == UA_INITIALIZE)
      {
        actionS.OnStartAnimationLoop(m_ActionData);
        m_ActionData.m_State = UA_PROCESSING;
        m_callLoopEnd = true;
      }
      if (!m_Interrupted)
        actionS.Do(m_ActionData, m_ActionData.m_State);
    }
    else if (m_callLoopEnd == true)
    {
      ActionContinuousBase actionE = ActionContinuousBase.Cast(m_ActionData.m_Action);
      actionE.OnEndAnimationLoop(m_ActionData);
      m_callLoopEnd = false;
    }
    return DefaultCancelCondition();
  }
References DefaultCancelCondition(), GetState(), ActionData::m_Action, ActionBaseCB::m_ActionData, m_callLoopEnd, m_inLoop, ActionBaseCB::m_Interrupted, ActionData::m_State, STATE_LOOP_LOOP, STATE_LOOP_LOOP2, UA_INITIALIZE, and UA_PROCESSING.
EndActionComponent()
override void ActionContinuousBaseCB::EndActionComponent () inline private
Definition at line 85 of file ActionContinuousBase.c.
  {
    // TODO for second type animation SetCommand(DayZPlayerConstants.CMD_ACTIONINT_FINISH);
    if (m_ActionData.m_State == UA_FINISHED)
      SetCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
    else if (m_ActionData.m_State == UA_CANCEL)
    {
      ActionContinuousBase action = ActionContinuousBase.Cast(m_ActionData.m_Action);
      if (action.HasAlternativeInterrupt())
        SetCommand(DayZPlayerConstants.CMD_ACTIONINT_FINISH);
      else
        SetCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
      m_Canceled = true;
      return;
      //Cancel();
    }
    else
    {
      m_Canceled = true;
      SetCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
      return;
    }
    m_ActionData.m_State = UA_FINISHED;
  }
References ActionData::m_Action, ActionBaseCB::m_ActionData, ActionBaseCB::m_Canceled, ActionData::m_State, ActionBaseCB::SetCommand(), UA_CANCEL, and UA_FINISHED.
Referenced by UserEndsAction().
InitActionComponent()
override void ActionContinuousBaseCB::InitActionComponent () inline private
Definition at line 68 of file ActionContinuousBase.c.
  {
    m_Interrupted = false;
    m_Canceled = false;
    m_inLoop = false;
    CreateActionComponent();
    if (m_ActionData.m_ActionComponent)
      m_ActionData.m_ActionComponent.Init(m_ActionData);
    m_ActionData.m_State = UA_INITIALIZE;
    RegisterAnimationEvent("ActionExecStart", UA_IN_START);
    RegisterAnimationEvent("ActionExecEnd", UA_IN_END);
    RegisterAnimationEvent("ActionExec", UA_ANIM_EVENT);
    EnableCancelCondition(true);
    m_SoundObject = m_ActionData.m_Action.PlayActionSound(m_ActionData.m_Player);
  }
References ActionBaseCB::CreateActionComponent(), EnableCancelCondition(), ActionData::m_Action, ActionData::m_ActionComponent, ActionBaseCB::m_ActionData, ActionBaseCB::m_Canceled, m_inLoop, ActionBaseCB::m_Interrupted, ActionData::m_Player, ActionBaseCB::m_SoundObject, ActionData::m_State, RegisterAnimationEvent(), UA_ANIM_EVENT, UA_IN_END, UA_IN_START, and UA_INITIALIZE.
OnAnimationEvent()
override void ActionContinuousBaseCB::OnAnimationEvent (int pEventID) inline private
Definition at line 33 of file ActionContinuousBase.c.
  {
    if (m_ActionData && m_ActionData.m_Action)
    {
      AnimatedActionBase action = AnimatedActionBase.Cast(m_ActionData.m_Action);
#ifdef DEVELOPER
      //Print("ActionInteractBase.c | OnAnimationEvent | OnAnimationEvent called");
#endif
      if (LogManager.IsActionLogEnable())
        Debug.ActionLog("Time stamp: " + m_ActionData.m_Player.GetSimulationTimeStamp() + " / " + pEventID, this.ToString(), "n/a", "OnAnimationEvent", m_ActionData.m_Player.ToString());
      if (!m_Interrupted && pEventID == UA_IN_START)
      {
        m_inLoop = true;
        //ActionContinuousBase.Cast(action).OnStartLoop( m_ActionData );
      }
      else if (!m_Interrupted && pEventID == UA_IN_END)
      {
        m_inLoop = false;
        //ActionContinuousBase.Cast(action).OnCompleteLoop( m_ActionData );
      }
      else if (!m_Interrupted && pEventID == UA_ANIM_EVENT)
      {
        action.OnAnimationEvent(m_ActionData);
        //action.OnCompleteLoop( m_ActionData );
      }
    }
    else
    {
      //Debug.LogError("Call OnAnimationEvent ")
    }
  }
References Debug::ActionLog(), LogManager::IsActionLogEnable(), ActionData::m_Action, ActionBaseCB::m_ActionData, m_inLoop, ActionBaseCB::m_Interrupted, ActionData::m_Player, UA_ANIM_EVENT, UA_IN_END, and UA_IN_START.
UserEndsAction()
void ActionContinuousBaseCB::UserEndsAction () inline private
Definition at line 110 of file ActionContinuousBase.c.
  {
    if (m_ActionData.m_ActionComponent)
      m_ActionData.m_State = m_ActionData.m_ActionComponent.Cancel(m_ActionData);
    EndActionComponent();
  }
References EndActionComponent(), ActionData::m_ActionComponent, ActionBaseCB::m_ActionData, and ActionData::m_State.
Member Data Documentation
m_callLoopEnd
bool ActionContinuousBaseCB::m_callLoopEnd = false private
Definition at line 4 of file ActionContinuousBase.c.
Referenced by CancelCondition().
m_inLoop
bool ActionContinuousBaseCB::m_inLoop = false private
Definition at line 3 of file ActionContinuousBase.c.
Referenced by CancelCondition(), InitActionComponent(), and OnAnimationEvent().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/ActionContinuousBase.c