DayZ: scripts/4_World/Entities/Game/Super/Building.c File Reference
Building.c File Reference
Classes
class House
Typedefs
typedef House BuildingSuper
Functions
void BuildingBase ()
void InitializeActions ()
override void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
void SetActions ()
void AddAction (typename actionName)
void RemoveAction (typename actionName)
Variables
House typename
House m_BuildingTypeActionsMap = new map<typename, ref TInputActionMap>
TInputActionMap m_InputActionMap
bool m_ActionsInitialize
Typedef Documentation
BuildingSuper
typedef House BuildingSuper
Definition at line 88 of file Building.c.
Function Documentation
AddAction()
void AddAction (typename actionName)
Definition at line 47 of file Building.c.
  {
    ActionBase action = ActionManagerBase.GetAction(actionName);
    if (!action)
    {
      Debug.LogError("Action " + actionName + " dosn't exist!");
      return;
    }
    typename ai = action.GetInputType();
    if (!ai)
    {
      m_ActionsInitialize = false;
      return;
    }
    ref array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (!action_array)
    {
      action_array = new array<ActionBase_Basic>;
      m_InputActionMap.Insert(ai, action_array);
    }
    if (LogManager.IsActionLogEnable())
      Debug.ActionLog(action.ToString() + " -> " + ai, this.ToString(), "n/a", "Add action");
    action_array.Insert(action);
  }
References Debug::ActionLog(), LogManager::IsActionLogEnable(), Debug::LogError(), m_ActionsInitialize, and m_InputActionMap.
BuildingBase()
void BuildingBase ()
Definition at line 14 of file Building.c.
  {
    m_ActionsInitialize = false;
  }
References m_ActionsInitialize.
GetActions()
override void GetActions (typename action_input_type , out array< ActionBase_Basic > actions)
Definition at line 31 of file Building.c.
  {
    if (!m_ActionsInitialize)
    {
      m_ActionsInitialize = true;
      InitializeActions();
    }
    actions = m_InputActionMap.Get(action_input_type);
  }
References InitializeActions(), m_ActionsInitialize, and m_InputActionMap.
InitializeActions()
void InitializeActions ()
Definition at line 19 of file Building.c.
  {
    m_InputActionMap = m_BuildingTypeActionsMap.Get(this.Type());
    if (!m_InputActionMap)
    {
      TInputActionMap iam = new TInputActionMap;
      m_InputActionMap = iam;
      SetActions();
      m_BuildingTypeActionsMap.Insert(this.Type(), m_InputActionMap);
    }
  }
References m_BuildingTypeActionsMap, m_InputActionMap, SetActions(), and Type.
RemoveAction()
void RemoveAction (typename actionName)
Definition at line 76 of file Building.c.
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    ActionBase action = player.GetActionManager().GetAction(actionName);
    typename ai = action.GetInputType();
    ref array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (action_array)
      action_array.RemoveItem(action);
  }
References GetGame(), GetPlayer(), and m_InputActionMap.
SetActions()
void SetActions ()
Definition at line 42 of file Building.c.
  {
    //AddAction();
  }
Variable Documentation
m_ActionsInitialize
bool m_ActionsInitialize
Definition at line 12 of file Building.c.
m_BuildingTypeActionsMap
House m_BuildingTypeActionsMap = new map<typename, ref TInputActionMap>
Referenced by InitializeActions().
m_InputActionMap
TInputActionMap m_InputActionMap
Definition at line 11 of file Building.c.
typename
House typename