DayZ: scripts/5_Mission/GUI/ItemDropWarningMenu.c File Reference
ItemDropWarningMenu.c File Reference
Classes
class WarningMenuBase
class PlayerRepositionWarningMenu
Functions
WarningMenuBase UIScriptedMenu GetText ()
void WarningMenuBase ()
void ~WarningMenuBase ()
override Widget Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
override bool OnClick (Widget w, int x, int y, int button)
override void Update (float timeslice)
void OnInputPresetChanged ()
void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
void UpdateControlsElements ()
void UpdateControlsElementVisibility ()
Variables
ButtonWidget m_OkButton
MultilineTextWidget m_Description
Function Documentation
GetText()
WarningMenuBase UIScriptedMenu GetText ()
Definition at line 1 of file ItemDropWarningMenu.c.
  {
    return "#str_item_drop_notification";
  }
Init()
override Widget GetText::Init () protected
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
pre-init arrays
Definition at line 144 of file ItemDropWarningMenu.c.
                      : UIScriptedMenu
{
  protected ButtonWidget m_OkButton;
  protected MultilineTextWidget m_Description;
  void WarningMenuBase()
  {
    if (GetGame().GetMission())
    {
      GetGame().GetMission().AddActiveInputExcludes({"menu"});
      GetGame().GetMission().GetHud().ShowHudUI(false);
      GetGame().GetMission().GetHud().ShowQuickbarUI(false);
    }
  }
  void ~WarningMenuBase()
  {
    if (GetGame() && GetGame().GetMission())
    {
      GetGame().GetMission().RemoveActiveInputExcludes({"menu"}, true);
      GetGame().GetMission().GetHud().ShowHudUI(true);
      GetGame().GetMission().GetHud().ShowQuickbarUI(true);
      GetGame().GetMission().GetOnInputPresetChanged().Remove(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Remove(OnInputDeviceChanged);
    }
  }
  override Widget Init()
  {
    layoutRoot = GetGame().GetWorkspace().CreateWidgets("gui/layouts/day_z_dropped_items.layout");
    m_OkButton = ButtonWidget.Cast(layoutRoot.FindAnyWidget("bOK"));
    m_Description = MultilineTextWidget.Cast(layoutRoot.FindAnyWidget("txtDescription"));
    m_Description.Show(true);
    string text = Widget.TranslateString(GetText());
    m_Description.SetText(text);
    if (GetGame().GetMission())
    {
      GetGame().GetMission().GetOnInputPresetChanged().Insert(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Insert(OnInputDeviceChanged);
    }
    OnInputDeviceChanged(GetGame().GetInput().GetCurrentInputDevice());
    return layoutRoot;
  }
  string GetText()
  {
    return "";
  }
  override bool OnClick(Widget w, int x, int y, int button)
  {
    super.OnClick(w, x, y, button);
    if (w.GetUserID() == IDC_OK)
    {
      Close();
      return true;
    }
    return false;
  }
  override void Update(float timeslice)
  {
    super.Update(timeslice);
#ifdef PLATFORM_CONSOLE
    if (GetUApi().GetInputByID(UAUISelect).LocalPress())
      Close();
#endif
  }
  protected void OnInputPresetChanged()
  {
#ifdef PLATFORM_CONSOLE
    UpdateControlsElements();
#endif
  }
  protected void OnInputDeviceChanged(EInputDeviceType pInputDeviceType)
  {
    UpdateControlsElements();
    UpdateControlsElementVisibility();
  }
  protected void UpdateControlsElements()
  {
    RichTextWidget toolbarText = RichTextWidget.Cast(layoutRoot.FindAnyWidget("ContextToolbarText"));
    string context = string.Format(" %1", InputUtils.GetRichtextButtonIconFromInputAction("UAUISelect", "#early_access_alpha_understand", EUAINPUT_DEVICE_CONTROLLER, InputUtils.ICON_SCALE_TOOLBAR));
    toolbarText.SetText(context);
  }
  protected void UpdateControlsElementVisibility()
  {
    bool toolbarShow = false;
#ifdef PLATFORM_CONSOLE
    toolbarShow = !GetGame().GetInput().IsEnabledMouseAndKeyboard() || GetGame().GetInput().GetCurrentInputDevice() == EInputDeviceType.CONTROLLER;
#endif
    layoutRoot.FindAnyWidget("BottomConsoleToolbar").Show(toolbarShow);
    m_OkButton.Show(!toolbarShow);
  }
}
class ItemDropWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_item_drop_notification";
  }
}
class PlayerRepositionWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_position_change_notification";
  }
}
OnClick()
override bool GetText::OnClick (Widget w, int x, int y, int button) protected
Definition at line 170 of file ItemDropWarningMenu.c.
                      : UIScriptedMenu
{
  protected ButtonWidget m_OkButton;
  protected MultilineTextWidget m_Description;
  void WarningMenuBase()
  {
    if (GetGame().GetMission())
    {
      GetGame().GetMission().AddActiveInputExcludes({"menu"});
      GetGame().GetMission().GetHud().ShowHudUI(false);
      GetGame().GetMission().GetHud().ShowQuickbarUI(false);
    }
  }
  void ~WarningMenuBase()
  {
    if (GetGame() && GetGame().GetMission())
    {
      GetGame().GetMission().RemoveActiveInputExcludes({"menu"}, true);
      GetGame().GetMission().GetHud().ShowHudUI(true);
      GetGame().GetMission().GetHud().ShowQuickbarUI(true);
      GetGame().GetMission().GetOnInputPresetChanged().Remove(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Remove(OnInputDeviceChanged);
    }
  }
  override Widget Init()
  {
    layoutRoot = GetGame().GetWorkspace().CreateWidgets("gui/layouts/day_z_dropped_items.layout");
    m_OkButton = ButtonWidget.Cast(layoutRoot.FindAnyWidget("bOK"));
    m_Description = MultilineTextWidget.Cast(layoutRoot.FindAnyWidget("txtDescription"));
    m_Description.Show(true);
    string text = Widget.TranslateString(GetText());
    m_Description.SetText(text);
    if (GetGame().GetMission())
    {
      GetGame().GetMission().GetOnInputPresetChanged().Insert(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Insert(OnInputDeviceChanged);
    }
    OnInputDeviceChanged(GetGame().GetInput().GetCurrentInputDevice());
    return layoutRoot;
  }
  string GetText()
  {
    return "";
  }
  override bool OnClick(Widget w, int x, int y, int button)
  {
    super.OnClick(w, x, y, button);
    if (w.GetUserID() == IDC_OK)
    {
      Close();
      return true;
    }
    return false;
  }
  override void Update(float timeslice)
  {
    super.Update(timeslice);
#ifdef PLATFORM_CONSOLE
    if (GetUApi().GetInputByID(UAUISelect).LocalPress())
      Close();
#endif
  }
  protected void OnInputPresetChanged()
  {
#ifdef PLATFORM_CONSOLE
    UpdateControlsElements();
#endif
  }
  protected void OnInputDeviceChanged(EInputDeviceType pInputDeviceType)
  {
    UpdateControlsElements();
    UpdateControlsElementVisibility();
  }
  protected void UpdateControlsElements()
  {
    RichTextWidget toolbarText = RichTextWidget.Cast(layoutRoot.FindAnyWidget("ContextToolbarText"));
    string context = string.Format(" %1", InputUtils.GetRichtextButtonIconFromInputAction("UAUISelect", "#early_access_alpha_understand", EUAINPUT_DEVICE_CONTROLLER, InputUtils.ICON_SCALE_TOOLBAR));
    toolbarText.SetText(context);
  }
  protected void UpdateControlsElementVisibility()
  {
    bool toolbarShow = false;
#ifdef PLATFORM_CONSOLE
    toolbarShow = !GetGame().GetInput().IsEnabledMouseAndKeyboard() || GetGame().GetInput().GetCurrentInputDevice() == EInputDeviceType.CONTROLLER;
#endif
    layoutRoot.FindAnyWidget("BottomConsoleToolbar").Show(toolbarShow);
    m_OkButton.Show(!toolbarShow);
  }
}
class ItemDropWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_item_drop_notification";
  }
}
class PlayerRepositionWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_position_change_notification";
  }
}
OnInputDeviceChanged()
void GetText::OnInputDeviceChanged (EInputDeviceType pInputDeviceType) protected
Definition at line 200 of file ItemDropWarningMenu.c.
                      : UIScriptedMenu
{
  protected ButtonWidget m_OkButton;
  protected MultilineTextWidget m_Description;
  void WarningMenuBase()
  {
    if (GetGame().GetMission())
    {
      GetGame().GetMission().AddActiveInputExcludes({"menu"});
      GetGame().GetMission().GetHud().ShowHudUI(false);
      GetGame().GetMission().GetHud().ShowQuickbarUI(false);
    }
  }
  void ~WarningMenuBase()
  {
    if (GetGame() && GetGame().GetMission())
    {
      GetGame().GetMission().RemoveActiveInputExcludes({"menu"}, true);
      GetGame().GetMission().GetHud().ShowHudUI(true);
      GetGame().GetMission().GetHud().ShowQuickbarUI(true);
      GetGame().GetMission().GetOnInputPresetChanged().Remove(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Remove(OnInputDeviceChanged);
    }
  }
  override Widget Init()
  {
    layoutRoot = GetGame().GetWorkspace().CreateWidgets("gui/layouts/day_z_dropped_items.layout");
    m_OkButton = ButtonWidget.Cast(layoutRoot.FindAnyWidget("bOK"));
    m_Description = MultilineTextWidget.Cast(layoutRoot.FindAnyWidget("txtDescription"));
    m_Description.Show(true);
    string text = Widget.TranslateString(GetText());
    m_Description.SetText(text);
    if (GetGame().GetMission())
    {
      GetGame().GetMission().GetOnInputPresetChanged().Insert(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Insert(OnInputDeviceChanged);
    }
    OnInputDeviceChanged(GetGame().GetInput().GetCurrentInputDevice());
    return layoutRoot;
  }
  string GetText()
  {
    return "";
  }
  override bool OnClick(Widget w, int x, int y, int button)
  {
    super.OnClick(w, x, y, button);
    if (w.GetUserID() == IDC_OK)
    {
      Close();
      return true;
    }
    return false;
  }
  override void Update(float timeslice)
  {
    super.Update(timeslice);
#ifdef PLATFORM_CONSOLE
    if (GetUApi().GetInputByID(UAUISelect).LocalPress())
      Close();
#endif
  }
  protected void OnInputPresetChanged()
  {
#ifdef PLATFORM_CONSOLE
    UpdateControlsElements();
#endif
  }
  protected void OnInputDeviceChanged(EInputDeviceType pInputDeviceType)
  {
    UpdateControlsElements();
    UpdateControlsElementVisibility();
  }
  protected void UpdateControlsElements()
  {
    RichTextWidget toolbarText = RichTextWidget.Cast(layoutRoot.FindAnyWidget("ContextToolbarText"));
    string context = string.Format(" %1", InputUtils.GetRichtextButtonIconFromInputAction("UAUISelect", "#early_access_alpha_understand", EUAINPUT_DEVICE_CONTROLLER, InputUtils.ICON_SCALE_TOOLBAR));
    toolbarText.SetText(context);
  }
  protected void UpdateControlsElementVisibility()
  {
    bool toolbarShow = false;
#ifdef PLATFORM_CONSOLE
    toolbarShow = !GetGame().GetInput().IsEnabledMouseAndKeyboard() || GetGame().GetInput().GetCurrentInputDevice() == EInputDeviceType.CONTROLLER;
#endif
    layoutRoot.FindAnyWidget("BottomConsoleToolbar").Show(toolbarShow);
    m_OkButton.Show(!toolbarShow);
  }
}
class ItemDropWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_item_drop_notification";
  }
}
class PlayerRepositionWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_position_change_notification";
  }
}
OnInputPresetChanged()
void GetText::OnInputPresetChanged () protected
Definition at line 193 of file ItemDropWarningMenu.c.
                      : UIScriptedMenu
{
  protected ButtonWidget m_OkButton;
  protected MultilineTextWidget m_Description;
  void WarningMenuBase()
  {
    if (GetGame().GetMission())
    {
      GetGame().GetMission().AddActiveInputExcludes({"menu"});
      GetGame().GetMission().GetHud().ShowHudUI(false);
      GetGame().GetMission().GetHud().ShowQuickbarUI(false);
    }
  }
  void ~WarningMenuBase()
  {
    if (GetGame() && GetGame().GetMission())
    {
      GetGame().GetMission().RemoveActiveInputExcludes({"menu"}, true);
      GetGame().GetMission().GetHud().ShowHudUI(true);
      GetGame().GetMission().GetHud().ShowQuickbarUI(true);
      GetGame().GetMission().GetOnInputPresetChanged().Remove(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Remove(OnInputDeviceChanged);
    }
  }
  override Widget Init()
  {
    layoutRoot = GetGame().GetWorkspace().CreateWidgets("gui/layouts/day_z_dropped_items.layout");
    m_OkButton = ButtonWidget.Cast(layoutRoot.FindAnyWidget("bOK"));
    m_Description = MultilineTextWidget.Cast(layoutRoot.FindAnyWidget("txtDescription"));
    m_Description.Show(true);
    string text = Widget.TranslateString(GetText());
    m_Description.SetText(text);
    if (GetGame().GetMission())
    {
      GetGame().GetMission().GetOnInputPresetChanged().Insert(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Insert(OnInputDeviceChanged);
    }
    OnInputDeviceChanged(GetGame().GetInput().GetCurrentInputDevice());
    return layoutRoot;
  }
  string GetText()
  {
    return "";
  }
  override bool OnClick(Widget w, int x, int y, int button)
  {
    super.OnClick(w, x, y, button);
    if (w.GetUserID() == IDC_OK)
    {
      Close();
      return true;
    }
    return false;
  }
  override void Update(float timeslice)
  {
    super.Update(timeslice);
#ifdef PLATFORM_CONSOLE
    if (GetUApi().GetInputByID(UAUISelect).LocalPress())
      Close();
#endif
  }
  protected void OnInputPresetChanged()
  {
#ifdef PLATFORM_CONSOLE
    UpdateControlsElements();
#endif
  }
  protected void OnInputDeviceChanged(EInputDeviceType pInputDeviceType)
  {
    UpdateControlsElements();
    UpdateControlsElementVisibility();
  }
  protected void UpdateControlsElements()
  {
    RichTextWidget toolbarText = RichTextWidget.Cast(layoutRoot.FindAnyWidget("ContextToolbarText"));
    string context = string.Format(" %1", InputUtils.GetRichtextButtonIconFromInputAction("UAUISelect", "#early_access_alpha_understand", EUAINPUT_DEVICE_CONTROLLER, InputUtils.ICON_SCALE_TOOLBAR));
    toolbarText.SetText(context);
  }
  protected void UpdateControlsElementVisibility()
  {
    bool toolbarShow = false;
#ifdef PLATFORM_CONSOLE
    toolbarShow = !GetGame().GetInput().IsEnabledMouseAndKeyboard() || GetGame().GetInput().GetCurrentInputDevice() == EInputDeviceType.CONTROLLER;
#endif
    layoutRoot.FindAnyWidget("BottomConsoleToolbar").Show(toolbarShow);
    m_OkButton.Show(!toolbarShow);
  }
}
class ItemDropWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_item_drop_notification";
  }
}
class PlayerRepositionWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_position_change_notification";
  }
}
Update()
override void GetText::Update (float timeslice) protected
Definition at line 183 of file ItemDropWarningMenu.c.
                      : UIScriptedMenu
{
  protected ButtonWidget m_OkButton;
  protected MultilineTextWidget m_Description;
  void WarningMenuBase()
  {
    if (GetGame().GetMission())
    {
      GetGame().GetMission().AddActiveInputExcludes({"menu"});
      GetGame().GetMission().GetHud().ShowHudUI(false);
      GetGame().GetMission().GetHud().ShowQuickbarUI(false);
    }
  }
  void ~WarningMenuBase()
  {
    if (GetGame() && GetGame().GetMission())
    {
      GetGame().GetMission().RemoveActiveInputExcludes({"menu"}, true);
      GetGame().GetMission().GetHud().ShowHudUI(true);
      GetGame().GetMission().GetHud().ShowQuickbarUI(true);
      GetGame().GetMission().GetOnInputPresetChanged().Remove(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Remove(OnInputDeviceChanged);
    }
  }
  override Widget Init()
  {
    layoutRoot = GetGame().GetWorkspace().CreateWidgets("gui/layouts/day_z_dropped_items.layout");
    m_OkButton = ButtonWidget.Cast(layoutRoot.FindAnyWidget("bOK"));
    m_Description = MultilineTextWidget.Cast(layoutRoot.FindAnyWidget("txtDescription"));
    m_Description.Show(true);
    string text = Widget.TranslateString(GetText());
    m_Description.SetText(text);
    if (GetGame().GetMission())
    {
      GetGame().GetMission().GetOnInputPresetChanged().Insert(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Insert(OnInputDeviceChanged);
    }
    OnInputDeviceChanged(GetGame().GetInput().GetCurrentInputDevice());
    return layoutRoot;
  }
  string GetText()
  {
    return "";
  }
  override bool OnClick(Widget w, int x, int y, int button)
  {
    super.OnClick(w, x, y, button);
    if (w.GetUserID() == IDC_OK)
    {
      Close();
      return true;
    }
    return false;
  }
  override void Update(float timeslice)
  {
    super.Update(timeslice);
#ifdef PLATFORM_CONSOLE
    if (GetUApi().GetInputByID(UAUISelect).LocalPress())
      Close();
#endif
  }
  protected void OnInputPresetChanged()
  {
#ifdef PLATFORM_CONSOLE
    UpdateControlsElements();
#endif
  }
  protected void OnInputDeviceChanged(EInputDeviceType pInputDeviceType)
  {
    UpdateControlsElements();
    UpdateControlsElementVisibility();
  }
  protected void UpdateControlsElements()
  {
    RichTextWidget toolbarText = RichTextWidget.Cast(layoutRoot.FindAnyWidget("ContextToolbarText"));
    string context = string.Format(" %1", InputUtils.GetRichtextButtonIconFromInputAction("UAUISelect", "#early_access_alpha_understand", EUAINPUT_DEVICE_CONTROLLER, InputUtils.ICON_SCALE_TOOLBAR));
    toolbarText.SetText(context);
  }
  protected void UpdateControlsElementVisibility()
  {
    bool toolbarShow = false;
#ifdef PLATFORM_CONSOLE
    toolbarShow = !GetGame().GetInput().IsEnabledMouseAndKeyboard() || GetGame().GetInput().GetCurrentInputDevice() == EInputDeviceType.CONTROLLER;
#endif
    layoutRoot.FindAnyWidget("BottomConsoleToolbar").Show(toolbarShow);
    m_OkButton.Show(!toolbarShow);
  }
}
class ItemDropWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_item_drop_notification";
  }
}
class PlayerRepositionWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_position_change_notification";
  }
}
UpdateControlsElements()
void GetText::UpdateControlsElements () protected
Definition at line 206 of file ItemDropWarningMenu.c.
                      : UIScriptedMenu
{
  protected ButtonWidget m_OkButton;
  protected MultilineTextWidget m_Description;
  void WarningMenuBase()
  {
    if (GetGame().GetMission())
    {
      GetGame().GetMission().AddActiveInputExcludes({"menu"});
      GetGame().GetMission().GetHud().ShowHudUI(false);
      GetGame().GetMission().GetHud().ShowQuickbarUI(false);
    }
  }
  void ~WarningMenuBase()
  {
    if (GetGame() && GetGame().GetMission())
    {
      GetGame().GetMission().RemoveActiveInputExcludes({"menu"}, true);
      GetGame().GetMission().GetHud().ShowHudUI(true);
      GetGame().GetMission().GetHud().ShowQuickbarUI(true);
      GetGame().GetMission().GetOnInputPresetChanged().Remove(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Remove(OnInputDeviceChanged);
    }
  }
  override Widget Init()
  {
    layoutRoot = GetGame().GetWorkspace().CreateWidgets("gui/layouts/day_z_dropped_items.layout");
    m_OkButton = ButtonWidget.Cast(layoutRoot.FindAnyWidget("bOK"));
    m_Description = MultilineTextWidget.Cast(layoutRoot.FindAnyWidget("txtDescription"));
    m_Description.Show(true);
    string text = Widget.TranslateString(GetText());
    m_Description.SetText(text);
    if (GetGame().GetMission())
    {
      GetGame().GetMission().GetOnInputPresetChanged().Insert(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Insert(OnInputDeviceChanged);
    }
    OnInputDeviceChanged(GetGame().GetInput().GetCurrentInputDevice());
    return layoutRoot;
  }
  string GetText()
  {
    return "";
  }
  override bool OnClick(Widget w, int x, int y, int button)
  {
    super.OnClick(w, x, y, button);
    if (w.GetUserID() == IDC_OK)
    {
      Close();
      return true;
    }
    return false;
  }
  override void Update(float timeslice)
  {
    super.Update(timeslice);
#ifdef PLATFORM_CONSOLE
    if (GetUApi().GetInputByID(UAUISelect).LocalPress())
      Close();
#endif
  }
  protected void OnInputPresetChanged()
  {
#ifdef PLATFORM_CONSOLE
    UpdateControlsElements();
#endif
  }
  protected void OnInputDeviceChanged(EInputDeviceType pInputDeviceType)
  {
    UpdateControlsElements();
    UpdateControlsElementVisibility();
  }
  protected void UpdateControlsElements()
  {
    RichTextWidget toolbarText = RichTextWidget.Cast(layoutRoot.FindAnyWidget("ContextToolbarText"));
    string context = string.Format(" %1", InputUtils.GetRichtextButtonIconFromInputAction("UAUISelect", "#early_access_alpha_understand", EUAINPUT_DEVICE_CONTROLLER, InputUtils.ICON_SCALE_TOOLBAR));
    toolbarText.SetText(context);
  }
  protected void UpdateControlsElementVisibility()
  {
    bool toolbarShow = false;
#ifdef PLATFORM_CONSOLE
    toolbarShow = !GetGame().GetInput().IsEnabledMouseAndKeyboard() || GetGame().GetInput().GetCurrentInputDevice() == EInputDeviceType.CONTROLLER;
#endif
    layoutRoot.FindAnyWidget("BottomConsoleToolbar").Show(toolbarShow);
    m_OkButton.Show(!toolbarShow);
  }
}
class ItemDropWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_item_drop_notification";
  }
}
class PlayerRepositionWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_position_change_notification";
  }
}
Referenced by UIScriptedMenu::ChangeCurrentCategory(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::Init(), UIScriptedMenu::LoadMods(), UIScriptedMenu::OnInputDeviceChanged(), ScriptedWidgetEventHandler::OnInputDeviceChanged(), UIScriptedMenu::OnInputPresetChanged(), ScriptedWidgetEventHandler::OnInputPresetChanged(), UIScriptedMenu::OnShow(), UIScriptedMenu::PerformSwitchPreset(), and UIScriptedMenu::RefreshGestures().
UpdateControlsElementVisibility()
void GetText::UpdateControlsElementVisibility () protected
Definition at line 214 of file ItemDropWarningMenu.c.
                      : UIScriptedMenu
{
  protected ButtonWidget m_OkButton;
  protected MultilineTextWidget m_Description;
  void WarningMenuBase()
  {
    if (GetGame().GetMission())
    {
      GetGame().GetMission().AddActiveInputExcludes({"menu"});
      GetGame().GetMission().GetHud().ShowHudUI(false);
      GetGame().GetMission().GetHud().ShowQuickbarUI(false);
    }
  }
  void ~WarningMenuBase()
  {
    if (GetGame() && GetGame().GetMission())
    {
      GetGame().GetMission().RemoveActiveInputExcludes({"menu"}, true);
      GetGame().GetMission().GetHud().ShowHudUI(true);
      GetGame().GetMission().GetHud().ShowQuickbarUI(true);
      GetGame().GetMission().GetOnInputPresetChanged().Remove(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Remove(OnInputDeviceChanged);
    }
  }
  override Widget Init()
  {
    layoutRoot = GetGame().GetWorkspace().CreateWidgets("gui/layouts/day_z_dropped_items.layout");
    m_OkButton = ButtonWidget.Cast(layoutRoot.FindAnyWidget("bOK"));
    m_Description = MultilineTextWidget.Cast(layoutRoot.FindAnyWidget("txtDescription"));
    m_Description.Show(true);
    string text = Widget.TranslateString(GetText());
    m_Description.SetText(text);
    if (GetGame().GetMission())
    {
      GetGame().GetMission().GetOnInputPresetChanged().Insert(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Insert(OnInputDeviceChanged);
    }
    OnInputDeviceChanged(GetGame().GetInput().GetCurrentInputDevice());
    return layoutRoot;
  }
  string GetText()
  {
    return "";
  }
  override bool OnClick(Widget w, int x, int y, int button)
  {
    super.OnClick(w, x, y, button);
    if (w.GetUserID() == IDC_OK)
    {
      Close();
      return true;
    }
    return false;
  }
  override void Update(float timeslice)
  {
    super.Update(timeslice);
#ifdef PLATFORM_CONSOLE
    if (GetUApi().GetInputByID(UAUISelect).LocalPress())
      Close();
#endif
  }
  protected void OnInputPresetChanged()
  {
#ifdef PLATFORM_CONSOLE
    UpdateControlsElements();
#endif
  }
  protected void OnInputDeviceChanged(EInputDeviceType pInputDeviceType)
  {
    UpdateControlsElements();
    UpdateControlsElementVisibility();
  }
  protected void UpdateControlsElements()
  {
    RichTextWidget toolbarText = RichTextWidget.Cast(layoutRoot.FindAnyWidget("ContextToolbarText"));
    string context = string.Format(" %1", InputUtils.GetRichtextButtonIconFromInputAction("UAUISelect", "#early_access_alpha_understand", EUAINPUT_DEVICE_CONTROLLER, InputUtils.ICON_SCALE_TOOLBAR));
    toolbarText.SetText(context);
  }
  protected void UpdateControlsElementVisibility()
  {
    bool toolbarShow = false;
#ifdef PLATFORM_CONSOLE
    toolbarShow = !GetGame().GetInput().IsEnabledMouseAndKeyboard() || GetGame().GetInput().GetCurrentInputDevice() == EInputDeviceType.CONTROLLER;
#endif
    layoutRoot.FindAnyWidget("BottomConsoleToolbar").Show(toolbarShow);
    m_OkButton.Show(!toolbarShow);
  }
}
class ItemDropWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_item_drop_notification";
  }
}
class PlayerRepositionWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_position_change_notification";
  }
}
Referenced by UIScriptedMenu::Init(), UIScriptedMenu::OnInputDeviceChanged(), UIScriptedMenu::OnInputPresetChanged(), and UIScriptedMenu::OnShow().
WarningMenuBase()
void GetText::WarningMenuBase () protected
Definition at line 119 of file ItemDropWarningMenu.c.
                                  : WarningMenuBase
{
  override string GetText()
  {
    return "#str_position_change_notification";
  }
}
~WarningMenuBase()
void GetText::~WarningMenuBase () protected
Definition at line 130 of file ItemDropWarningMenu.c.
                      : UIScriptedMenu
{
  protected ButtonWidget m_OkButton;
  protected MultilineTextWidget m_Description;
  void WarningMenuBase()
  {
    if (GetGame().GetMission())
    {
      GetGame().GetMission().AddActiveInputExcludes({"menu"});
      GetGame().GetMission().GetHud().ShowHudUI(false);
      GetGame().GetMission().GetHud().ShowQuickbarUI(false);
    }
  }
  void ~WarningMenuBase()
  {
    if (GetGame() && GetGame().GetMission())
    {
      GetGame().GetMission().RemoveActiveInputExcludes({"menu"}, true);
      GetGame().GetMission().GetHud().ShowHudUI(true);
      GetGame().GetMission().GetHud().ShowQuickbarUI(true);
      GetGame().GetMission().GetOnInputPresetChanged().Remove(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Remove(OnInputDeviceChanged);
    }
  }
  override Widget Init()
  {
    layoutRoot = GetGame().GetWorkspace().CreateWidgets("gui/layouts/day_z_dropped_items.layout");
    m_OkButton = ButtonWidget.Cast(layoutRoot.FindAnyWidget("bOK"));
    m_Description = MultilineTextWidget.Cast(layoutRoot.FindAnyWidget("txtDescription"));
    m_Description.Show(true);
    string text = Widget.TranslateString(GetText());
    m_Description.SetText(text);
    if (GetGame().GetMission())
    {
      GetGame().GetMission().GetOnInputPresetChanged().Insert(OnInputPresetChanged);
      GetGame().GetMission().GetOnInputDeviceChanged().Insert(OnInputDeviceChanged);
    }
    OnInputDeviceChanged(GetGame().GetInput().GetCurrentInputDevice());
    return layoutRoot;
  }
  string GetText()
  {
    return "";
  }
  override bool OnClick(Widget w, int x, int y, int button)
  {
    super.OnClick(w, x, y, button);
    if (w.GetUserID() == IDC_OK)
    {
      Close();
      return true;
    }
    return false;
  }
  override void Update(float timeslice)
  {
    super.Update(timeslice);
#ifdef PLATFORM_CONSOLE
    if (GetUApi().GetInputByID(UAUISelect).LocalPress())
      Close();
#endif
  }
  protected void OnInputPresetChanged()
  {
#ifdef PLATFORM_CONSOLE
    UpdateControlsElements();
#endif
  }
  protected void OnInputDeviceChanged(EInputDeviceType pInputDeviceType)
  {
    UpdateControlsElements();
    UpdateControlsElementVisibility();
  }
  protected void UpdateControlsElements()
  {
    RichTextWidget toolbarText = RichTextWidget.Cast(layoutRoot.FindAnyWidget("ContextToolbarText"));
    string context = string.Format(" %1", InputUtils.GetRichtextButtonIconFromInputAction("UAUISelect", "#early_access_alpha_understand", EUAINPUT_DEVICE_CONTROLLER, InputUtils.ICON_SCALE_TOOLBAR));
    toolbarText.SetText(context);
  }
  protected void UpdateControlsElementVisibility()
  {
    bool toolbarShow = false;
#ifdef PLATFORM_CONSOLE
    toolbarShow = !GetGame().GetInput().IsEnabledMouseAndKeyboard() || GetGame().GetInput().GetCurrentInputDevice() == EInputDeviceType.CONTROLLER;
#endif
    layoutRoot.FindAnyWidget("BottomConsoleToolbar").Show(toolbarShow);
    m_OkButton.Show(!toolbarShow);
  }
}
class ItemDropWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_item_drop_notification";
  }
}
class PlayerRepositionWarningMenu : WarningMenuBase
{
  override string GetText()
  {
    return "#str_position_change_notification";
  }
}
Variable Documentation
m_Description
MultilineTextWidget m_Description protected
Definition at line 117 of file ItemDropWarningMenu.c.
m_OkButton
ButtonWidget m_OkButton protected
Definition at line 116 of file ItemDropWarningMenu.c.