DayZ: scripts/5_Mission/GUI/InventoryNew/Inventory.c File Reference
Inventory.c File Reference
Enumerations
enum Direction { RIGHT , LEFT , UP , DOWN }
Functions
void Inventory (LayoutHolder parent)
void InitInputWrapperData ()
void OnInputPresetChanged ()
void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
static Inventory GetInstance ()
void Serialize ()
void Deserialize ()
static int GetPlayerAttachmentIndex (string slot_name)
static int GetPlayerAttachmentIndex (int slot_id)
void LoadPlayerAttachmentIndexes ()
static void MoveAttachmentUp (int slot_id)
static void MoveAttachmentDown (int slot_id)
int GetProperControllerStickAngle (int angle)
int AngleToDirection (int angle)
void TimerEnd ()
bool Controller (Widget w, int control, int value)
void DraggingOverHandsPanel (Widget w, int x, int y, Widget receiver)
void OnHandsPanelDropReceived (Widget w, int x, int y, Widget receiver)
void OnLeftPanelDropReceived (Widget w, int x, int y, Widget receiver)
void OnRightPanelDropReceived (Widget w, int x, int y, Widget receiver)
void OnCenterPanelDropReceived (Widget w, int x, int y, Widget receiver)
void DraggingOverLeftPanel (Widget w, int x, int y, Widget receiver)
void DraggingOverRightPanel (Widget w, int x, int y, Widget receiver)
void DraggingOverCenterPanel (Widget w, int x, int y, Widget receiver)
void Update (float timeslice)
override void UpdateInterval ()
void AddQuickbarItem (InventoryItem item, int index)
void EnableMicromanagement ()
void DisableMicromanagement ()
override void SetLayoutName ()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
void Reset ()
void ResetFocusedContainers ()
override void OnShow ()
override void OnHide ()
void UpdateSpecialtyMeter ()
override void Refresh ()
void RefreshQuickbar ()
Container GetFocusedArea ()
void UpdateConsoleToolbar ()
string GetStringVariant (string pInputAction, notnull array< string > variants)
Picks from the strings by active input limiter variant in order: {click,hold,doubleclick}. Intended for inputs that check 'LocalPress' exclusively!!
void MoveFocusByContainer (int direction)
Shifts between containers vertically.
void MoveFocusByArea (int direction)
Shifts between vicinity-hands-player.
void InventoryMovementButtonTickHandler (float timeslice)
Variables
enum Direction m_LeftArea
ref RightArea m_RightArea
ref HandsArea m_HandsArea
ref PlayerPreview m_PlayerPreview
ref InventoryQuickbar m_Quickbar
Widget m_QuickbarWidget
Widget m_SpecializationPanel
Widget m_SpecializationIcon
Widget m_TopConsoleToolbarVicinity
Widget m_TopConsoleToolbarHands
Widget m_TopConsoleToolbarEquipment
Widget m_BottomConsoleToolbar
RichTextWidget m_BottomConsoleToolbarRichText
ref ContextMenu m_ContextMenu
static ref map< string, int > m_PlayerAttachmentsIndexes
bool m_HadFastTransferred
bool m_HadInspected
bool m_NeedUpdateConsoleToolbar
static Inventory m_Instance
int m_ControllerAngle
int m_ControllerTilt
bool m_ControllerRightStickTimerEnd = true
ref Timer m_ControllerRightStickTimer
bool m_HoldingQB
InventoryItem m_QBHoveredItems
const float BT_REPEAT_DELAY = 0.35
const float BT_REPEAT_TIME = 0.09
const float BT_THRESHOLD_VALUE = 0.8
const int INV_MOV_LEFT = 0
const int INV_MOV_RIGHT = 1
const int INV_MOV_UP = 2
const int INV_MOV_DOWN = 3
ref array< string > m_InvInputNames = {"UAUILeftInventory", "UAUIRightInventory", "UAUIUpInventory", "UAUIDownInventory"}
ref array< UAIDWrapper > m_InvInputWrappers
ref array< float > m_InvInputTimes
int m_InvInputWrappersCount
float m_SensitivityThreshold = 0.0
UAInput m_InvUAInput
int m_InvInputActive = 0
UAInput m_InpInp = null
Enumeration Type Documentation
Direction
enum Direction
Enumerator
RIGHT
LEFT
UP
DOWN
Definition at line 18 of file Inventory.c.
{
  RIGHT,
  LEFT,
  UP,
  DOWN
}
Function Documentation
AddQuickbarItem()
void AddQuickbarItem (InventoryItem item, int index) protected
Definition at line 950 of file Inventory.c.
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (item && item.GetInventory().CanRemoveEntity())
      player.SetQuickBarEntityShortcut(item, index) ;
    InventoryMenu menu = InventoryMenu.Cast(GetGame().GetUIManager().FindMenu(MENU_INVENTORY));
    if (menu)
      menu.RefreshQuickbar();
  }
References GetGame(), GetPlayer(), InventoryMenu(), and MENU_INVENTORY.
Referenced by UpdateInterval().
AngleToDirection()
int AngleToDirection (int angle) protected
Definition at line 307 of file Inventory.c.
  {
    if (angle < 45 || angle > 315)
      return Direction.RIGHT;
    else if (angle < 135 && angle > 45)
      return Direction.DOWN;
    else if (angle < 225 && angle > 135)
      return Direction.LEFT;
    else if (angle < 315 && angle > 225)
      return Direction.UP;
    return -1;
  }
Referenced by Controller().
Controller()
bool Controller (Widget w, int control, int value) protected
Definition at line 326 of file Inventory.c.
  {
#ifdef PLATFORM_CONSOLE
    //Right stick
    if (control == ControlID.CID_RADIALMENU)
    {
      m_ControllerAngle = value >> 4; // <0,360>
      m_ControllerTilt = value & 0xF; // <0,10>
      m_ControllerAngle = GetProperControllerStickAngle(m_ControllerAngle);
      m_ControllerAngle = AngleToDirection(m_ControllerAngle);
      if (m_ControllerTilt > 5)
      {
        if (m_ControllerRightStickTimerEnd)
        {
          m_ControllerRightStickTimerEnd = false;
          m_ControllerRightStickTimer.Run(0.1, this, "TimerEnd");
        }
      }
      return true;
    }
    UpdateConsoleToolbar();
#endif
    return false;
  }
References AngleToDirection(), GetProperControllerStickAngle(), m_ControllerAngle, m_ControllerRightStickTimer, m_ControllerRightStickTimerEnd, m_ControllerTilt, and UpdateConsoleToolbar().
Deserialize()
void Deserialize () protected
Definition at line 199 of file Inventory.c.
  {
    ItemManager.GetInstance().DeserializeDefaultOpenStates();
    ItemManager.GetInstance().DeserializeDefaultHeaderOpenStates();
  }
References ItemManager::GetInstance().
Referenced by OnShow().
DisableMicromanagement()
void DisableMicromanagement () protected
Definition at line 979 of file Inventory.c.
  {
    if (ItemManager.GetInstance().IsMicromanagmentMode())
    {
      ItemManager.GetInstance().SetItemMicromanagmentMode(false);
      ItemManager.GetInstance().SetSelectedItemEx(null, null, null);
      UpdateConsoleToolbar();
      HideOwnedTooltip();
    }
  }
References ItemManager::GetInstance(), and UpdateConsoleToolbar().
Referenced by UpdateInterval().
DraggingOverCenterPanel()
void DraggingOverCenterPanel (Widget w, int x, int y, Widget receiver) protected
Definition at line 498 of file Inventory.c.
  {
    if (w)
    {
      ItemPreviewWidget ipw = ItemPreviewWidget.Cast(w.FindAnyWidget("Render"));
      if (!ipw)
      {
        string name = w.GetName();
        name.Replace("PanelWidget", "Render");
        ipw = ItemPreviewWidget.Cast(w.FindAnyWidget(name));
        if (!ipw)
        {
          ipw = ItemPreviewWidget.Cast(w);
          if (!ipw)
            return;
        }
      }
      EntityAI item = ipw.GetItem();
      PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
      if (player && item)
      {
        int slot_id = item.GetInventory().GetSlotId(0);
        EntityAI slot_item = player.GetInventory().FindAttachment(slot_id);
        bool found = false;
        InventoryLocation inv_loc = new InventoryLocation;
        int index = player.GetHumanInventory().FindUserReservedLocationIndex(item);
        if (index >= 0)
        {
          player.GetHumanInventory().GetUserReservedLocation(index, inv_loc);
          if (player.GetInventory().LocationCanAddEntity(inv_loc))
            found = true;
        }
        if (!found)
          player.GetInventory().FindFreeLocationFor(item, FindInventoryLocationType.ANY, inv_loc);
        if (inv_loc.IsValid())
        {
          ItemManager.GetInstance().HideDropzones();
          GetMainWidget().FindAnyWidget("RightPanel").FindAnyWidget("DropzoneX").SetAlpha(1);
          if (inv_loc.GetType() == 4)
          {
            ItemManager.GetInstance().HideDropzones();
            GetMainWidget().FindAnyWidget("HandsPanel").FindAnyWidget("DropzoneX").SetAlpha(1);
          }
          ColorManager.GetInstance().SetColor(w, ColorManager.GREEN_COLOR);
        }
        else
        {
          ItemManager.GetInstance().ShowSourceDropzone(item);
          ColorManager.GetInstance().SetColor(w, ColorManager.RED_COLOR);
        }
      }
      else
        ColorManager.GetInstance().SetColor(w, ColorManager.RED_COLOR);
    }
  }
References GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), GetPlayer(), ColorManager::GREEN_COLOR, name, and ColorManager::RED_COLOR.
DraggingOverHandsPanel()
void DraggingOverHandsPanel (Widget w, int x, int y, Widget receiver) protected
Definition at line 356 of file Inventory.c.
  {
    ItemManager.GetInstance().HideDropzones();
    m_HandsArea.DraggingOverHandsPanel(w, x, y, receiver);
  }
References ItemManager::GetInstance(), m_HandsArea, x, and y.
DraggingOverLeftPanel()
void DraggingOverLeftPanel (Widget w, int x, int y, Widget receiver) protected
Definition at line 488 of file Inventory.c.
  {
    m_LeftArea.DraggingOverHeader(w, x, y, receiver);
  }
References m_LeftArea, x, and y.
DraggingOverRightPanel()
void DraggingOverRightPanel (Widget w, int x, int y, Widget receiver) protected
Definition at line 493 of file Inventory.c.
  {
    m_RightArea.DraggingOverHeader(w, x, y, receiver);
  }
References m_RightArea, x, and y.
EnableMicromanagement()
void EnableMicromanagement () protected
Definition at line 962 of file Inventory.c.
  {
    if (!ItemManager.GetInstance().IsMicromanagmentMode())
    {
      ItemManager.GetInstance().SetItemMicromanagmentMode(true);
      if (m_RightArea.IsActive())
        m_RightArea.SelectItem();
      else if (m_LeftArea.IsActive())
        m_LeftArea.SelectItem();
      else if (m_HandsArea.IsActive())
        m_HandsArea.SelectItem();
      UpdateConsoleToolbar();
      HideOwnedTooltip();
    }
  }
References ItemManager::GetInstance(), m_HandsArea, m_LeftArea, m_RightArea, and UpdateConsoleToolbar().
Referenced by Update(), and UpdateInterval().
GetFocusedArea()
Container GetFocusedArea () protected
Definition at line 1184 of file Inventory.c.
  {
    if (m_LeftArea && m_LeftArea.IsActive())
      return m_LeftArea;
    else if (m_RightArea && m_RightArea.IsActive())
      return m_RightArea;
    else if (m_HandsArea && m_HandsArea.IsActive())
      return m_HandsArea;
    return null;
  }
References m_HandsArea, m_LeftArea, and m_RightArea.
Referenced by UpdateConsoleToolbar().
GetInstance()
static Inventory GetInstance () static protected
Definition at line 188 of file Inventory.c.
  {
    return m_Instance;
  }
References m_Instance.
GetPlayerAttachmentIndex() [1/2]
static int GetPlayerAttachmentIndex (int slot_id) static protected
Definition at line 210 of file Inventory.c.
  {
    return GetPlayerAttachmentIndex(InventorySlots.GetSlotName(slot_id));
  }
References GetPlayerAttachmentIndex(), and InventorySlots::GetSlotName().
GetPlayerAttachmentIndex() [2/2]
static int GetPlayerAttachmentIndex (string slot_name) static protected
Definition at line 205 of file Inventory.c.
  {
    return m_PlayerAttachmentsIndexes[slot_name];
  }
References m_PlayerAttachmentsIndexes.
Referenced by GetPlayerAttachmentIndex(), MoveAttachmentDown(), and MoveAttachmentUp().
GetProperControllerStickAngle()
int GetProperControllerStickAngle (int angle) protected
Definition at line 301 of file Inventory.c.
  {
    int proper_angle = (360 - angle) % 360;
    return proper_angle;
  }
Referenced by Controller().
GetStringVariant()
string GetStringVariant (string pInputAction, notnull array< string > variants) protected
Picks from the strings by active input limiter variant in order: {click,hold,doubleclick}. Intended for inputs that check 'LocalPress' exclusively!!
Definition at line 1314 of file Inventory.c.
  {
    if (variants.Count() != 3)
    {
      ErrorEx("wrong array count!");
      return "";
    }
    UAInput inp = GetUApi().GetInputByName(pInputAction);
    if (!inp.IsLimited() || inp.IsClickLimit()) //returns 'click' (no extension) variant as default
      return variants[0];
    if (inp.IsHoldLimit() || inp.IsHoldBeginLimit())
      return variants[1];
    if (inp.IsDoubleClickLimit())
      return variants[2];
    ErrorEx("Unhandled limiter exception!");
    return "";
  }
References ErrorEx, and GetUApi().
Init()
void Init () protected
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
pre-init arrays
Definition at line 1016 of file Inventory.c.
{}
InitInputWrapperData()
void InitInputWrapperData () protected
Definition at line 145 of file Inventory.c.
  {
    int namesCount = m_InvInputNames.Count();
    m_InvInputWrappers = new array<UAIDWrapper>;
    m_InvInputTimes = new array<float>;
    for (int i = 0; i < namesCount; i++)
    {
      m_InvInputWrappers.Insert(GetUApi().GetInputByName(m_InvInputNames[i]).GetPersistentWrapper());
      m_InvInputTimes.Insert(0);
    }
    m_InvInputWrappersCount = m_InvInputWrappers.Count();
  }
References GetUApi(), m_InvInputNames, m_InvInputTimes, m_InvInputWrappers, and m_InvInputWrappersCount.
Referenced by Inventory().
Inventory()
void Inventory (LayoutHolder parent) protected
Definition at line 76 of file Inventory.c.
  {
    m_Instance = this;
    LoadPlayerAttachmentIndexes();
    m_ControllerRightStickTimer = new Timer();
    new ItemManager(GetMainWidget());
    new ColorManager();
    m_LeftArea = new LeftArea(this);
    m_RightArea = new RightArea(this);
    m_HandsArea = new HandsArea(this);
    m_PlayerPreview = new PlayerPreview(this);
    m_QuickbarWidget = GetMainWidget().FindAnyWidget("QuickbarGrid");
    m_Quickbar = new InventoryQuickbar(m_QuickbarWidget);
    m_Quickbar.UpdateItems(m_QuickbarWidget);
    m_SpecializationPanel = GetMainWidget().FindAnyWidget("SpecializationPanelPanel");
    m_SpecializationIcon = GetMainWidget().FindAnyWidget("SpecializationIcon");
    WidgetEventHandler.GetInstance().RegisterOnDropReceived(GetMainWidget().FindAnyWidget("LeftBackground"), this, "OnLeftPanelDropReceived");
    WidgetEventHandler.GetInstance().RegisterOnDraggingOver(GetMainWidget().FindAnyWidget("LeftBackground"), this, "DraggingOverLeftPanel");
    WidgetEventHandler.GetInstance().RegisterOnDropReceived(GetMainWidget().FindAnyWidget("LeftPanel").FindAnyWidget("Scroller"), this, "OnLeftPanelDropReceived");
    WidgetEventHandler.GetInstance().RegisterOnDraggingOver(GetMainWidget().FindAnyWidget("LeftPanel").FindAnyWidget("Scroller"), this, "DraggingOverLeftPanel");
    WidgetEventHandler.GetInstance().RegisterOnDropReceived(GetMainWidget().FindAnyWidget("RightBackground"), this, "OnRightPanelDropReceived");
    WidgetEventHandler.GetInstance().RegisterOnDraggingOver(GetMainWidget().FindAnyWidget("RightBackground"), this, "DraggingOverRightPanel");
    WidgetEventHandler.GetInstance().RegisterOnDropReceived(GetMainWidget().FindAnyWidget("RightPanel").FindAnyWidget("Scroller"), this, "OnRightPanelDropReceived");
    WidgetEventHandler.GetInstance().RegisterOnDraggingOver(GetMainWidget().FindAnyWidget("RightPanel").FindAnyWidget("Scroller"), this, "DraggingOverRightPanel");
    WidgetEventHandler.GetInstance().RegisterOnDropReceived(GetMainWidget().FindAnyWidget("CharacterPanel"), this, "OnCenterPanelDropReceived");
    WidgetEventHandler.GetInstance().RegisterOnDraggingOver(GetMainWidget().FindAnyWidget("CharacterPanel"), this, "DraggingOverCenterPanel");
    WidgetEventHandler.GetInstance().RegisterOnDropReceived(GetMainWidget().FindAnyWidget("HandsPanel"), this, "OnHandsPanelDropReceived");
    WidgetEventHandler.GetInstance().RegisterOnDraggingOver(GetMainWidget().FindAnyWidget("HandsPanel"), this, "DraggingOverHandsPanel");
#ifdef PLATFORM_CONSOLE
    PluginDiagMenu plugin_diag_menu = PluginDiagMenu.Cast(GetPlugin(PluginDiagMenu));
    GetGame().GetUIManager().ShowUICursor(false);
    ResetFocusedContainers();
    GetMainWidget().FindAnyWidget("CursorCharacter").Show(false);
    //console inventory toolbar
    m_TopConsoleToolbarVicinity = GetRootWidget().FindAnyWidget("LBRB_Vicinity");
    m_TopConsoleToolbarHands = GetRootWidget().FindAnyWidget("LBRB_Hands");
    m_TopConsoleToolbarEquipment = GetRootWidget().FindAnyWidget("LBRB_Equipment");
    RichTextWidget.Cast(m_TopConsoleToolbarVicinity.FindAnyWidget("LBRB_Vicinity_LBIcon")).SetText(InputUtils.GetRichtextButtonIconFromInputAction("UAUIInventoryTabLeft", "", EUAINPUT_DEVICE_CONTROLLER));
    RichTextWidget.Cast(m_TopConsoleToolbarVicinity.FindAnyWidget("LBRB_Vicinity_RBIcon")).SetText(InputUtils.GetRichtextButtonIconFromInputAction("UAUIInventoryTabRight", "", EUAINPUT_DEVICE_CONTROLLER));
    RichTextWidget.Cast(m_TopConsoleToolbarHands.FindAnyWidget("LBRB_Hands_LBIcon")).SetText(InputUtils.GetRichtextButtonIconFromInputAction("UAUIInventoryTabLeft", "", EUAINPUT_DEVICE_CONTROLLER));
    RichTextWidget.Cast(m_TopConsoleToolbarHands.FindAnyWidget("LBRB_Hands_RBIcon")).SetText(InputUtils.GetRichtextButtonIconFromInputAction("UAUIInventoryTabRight", "", EUAINPUT_DEVICE_CONTROLLER));
    RichTextWidget.Cast(m_TopConsoleToolbarEquipment.FindAnyWidget("LBRB_Equipment_LBIcon")).SetText(InputUtils.GetRichtextButtonIconFromInputAction("UAUIInventoryTabLeft", "", EUAINPUT_DEVICE_CONTROLLER));
    RichTextWidget.Cast(m_TopConsoleToolbarEquipment.FindAnyWidget("LBRB_Equipment_RBIcon")).SetText(InputUtils.GetRichtextButtonIconFromInputAction("UAUIInventoryTabRight", "", EUAINPUT_DEVICE_CONTROLLER));
    m_BottomConsoleToolbar = GetRootWidget().FindAnyWidget("BottomConsoleToolbar");
    m_BottomConsoleToolbarRichText = RichTextWidget.Cast(GetRootWidget().FindAnyWidget("ContextToolbarText"));
    m_NeedUpdateConsoleToolbar = false;
    GetGame().GetMission().GetOnInputPresetChanged().Insert(OnInputPresetChanged);
    GetGame().GetMission().GetOnInputDeviceChanged().Insert(OnInputDeviceChanged);
    m_SpecializationPanel.Show(false);
    UpdateConsoleToolbar();
    InitInputWrapperData();
#endif
  }
References FindAnyWidget(), GetGame(), WidgetEventHandler::GetInstance(), GetPlugin(), InputUtils::GetRichtextButtonIconFromInputAction(), InitInputWrapperData(), LoadPlayerAttachmentIndexes(), m_BottomConsoleToolbar, m_BottomConsoleToolbarRichText, m_ControllerRightStickTimer, m_HandsArea, m_Instance, m_LeftArea, m_NeedUpdateConsoleToolbar, m_PlayerPreview, m_Quickbar, m_QuickbarWidget, m_RightArea, m_SpecializationIcon, m_SpecializationPanel, m_TopConsoleToolbarEquipment, m_TopConsoleToolbarHands, m_TopConsoleToolbarVicinity, OnInputDeviceChanged(), OnInputPresetChanged(), ResetFocusedContainers(), and UpdateConsoleToolbar().
Referenced by HandsContainer::AttachmentAdded(), ClosableContainer::AttachmentAddedEx(), HandsContainer::AttachmentRemoved(), ClosableContainer::AttachmentRemoved(), HandsPreview::CreateNewIcon(), HandsPreview::DeleteIcon(), SlotsIcon::Init(), InventoryMenu(), PlayerContainer::ItemAttached(), PlayerContainer::ItemDetached(), ZombieContainer::ItemDetached(), Container::MoveContainerDown(), Container::MoveContainerUp(), LayoutHolder::MoveGridCursor(), ClosableContainer::MoveGridCursor(), HandsContainer::OnSelectButton(), ItemManager::SetItemMicromanagmentMode(), VicinityContainer::UpdateInterval(), and Container::UpdateSelection().
InventoryMovementButtonTickHandler()
void InventoryMovementButtonTickHandler (float timeslice) protected
Definition at line 1432 of file Inventory.c.
  {
    float tickvalue = 0;
    if (m_SensitivityThreshold > 0.0)
    {
      if (m_SensitivityThreshold < BT_REPEAT_TIME) //sensitivity solution...
      {
        m_SensitivityThreshold += timeslice;
        return;
      }
      else
        m_SensitivityThreshold = 0.0;
    }
    for (int i = 0; i < m_InvInputWrappersCount; i++)
    {
      m_InvUAInput = m_InvInputWrappers[i].InputP();
      if (m_InvUAInput.LocalValue() > BT_THRESHOLD_VALUE)
      {
        tickvalue = m_InvInputTimes[i];
        tickvalue += timeslice;
      }
      else
        tickvalue = 0.0;
      if (tickvalue < BT_REPEAT_DELAY && m_InvUAInput.LocalPress())
      {
        m_InvInputActive |= (1 << i);
        m_SensitivityThreshold += timeslice;
      }
      else if (tickvalue > (BT_REPEAT_DELAY + BT_REPEAT_TIME))
      {
        while (tickvalue > (BT_REPEAT_DELAY + BT_REPEAT_TIME))
          tickvalue -= BT_REPEAT_TIME;
        m_InvInputActive |= (1 << i);
        m_SensitivityThreshold += timeslice;
      }
      else
        m_InvInputActive &= ~(1 << i);
      m_InvInputTimes[i] = tickvalue;
    }
  }
References BT_REPEAT_DELAY, BT_REPEAT_TIME, BT_THRESHOLD_VALUE, UAInput::LocalPress(), UAInput::LocalValue(), m_InvInputActive, m_InvInputTimes, m_InvInputWrappers, m_InvInputWrappersCount, m_InvUAInput, and m_SensitivityThreshold.
Referenced by Update().
LoadPlayerAttachmentIndexes()
void LoadPlayerAttachmentIndexes () protected
Definition at line 215 of file Inventory.c.
  {
    int i;
    string data, errorMessage;
    m_PlayerAttachmentsIndexes = new map<string, int>();
    if (GetGame().GetProfileString("INV_AttIndexes", data))
    {
      if (!JsonFileLoader<map<string, int>>.LoadData(data, m_PlayerAttachmentsIndexes, errorMessage))
        ErrorEx(errorMessage);
    }
    string configPathGhostSlots = "CfgVehicles SurvivorBase InventoryEquipment playerSlots";
    array<string> playerGhostSlots = new array<string>();
    GetGame().ConfigGetTextArray(configPathGhostSlots, playerGhostSlots);
    foreach (string slotName : playerGhostSlots)
    {
      slotName.Replace("Slot_", "");
      if (!m_PlayerAttachmentsIndexes.Contains(slotName) && InventorySlots.GetSlotIdFromString(slotName) != -1)
        m_PlayerAttachmentsIndexes.Insert(slotName, m_PlayerAttachmentsIndexes.Count());
    }
    if (!JsonFileLoader<map<string, int>>.MakeData(m_PlayerAttachmentsIndexes, data, errorMessage))
      ErrorEx(errorMessage);
    GetGame().SetProfileString("INV_AttIndexes", data);
  }
References ErrorEx, GetGame(), InventorySlots::GetSlotIdFromString(), m_PlayerAttachmentsIndexes, and slotName.
Referenced by Inventory().
MoveAttachmentDown()
static void MoveAttachmentDown (int slot_id) static protected
Definition at line 273 of file Inventory.c.
  {
    int curr = GetPlayerAttachmentIndex(slot_id);
    int next_offset = 0;
    string next_item = "init";
    int next_id;
    EntityAI next_ent;
    while (!next_ent && next_item != "")
    {
      next_item = m_PlayerAttachmentsIndexes.GetKeyByValue(curr + ++next_offset);
      next_id = InventorySlots.GetSlotIdFromString(next_item);
      next_ent = GetGame().GetPlayer().GetInventory().FindAttachment(next_id);
      if (next_ent && !m_Instance.m_RightArea.HasEntityContainerVisible(next_ent))
        next_ent = null;
    }
    if (next_item != "" && next_ent)
    {
      int next = GetPlayerAttachmentIndex(next_item);
      m_PlayerAttachmentsIndexes.Set(InventorySlots.GetSlotName(slot_id), next);
      m_PlayerAttachmentsIndexes.Set(next_item, curr);
      if (m_Instance)
        m_Instance.m_RightArea.SwapItemsInOrder(next_id, slot_id);
    }
  }
References GetGame(), GetPlayerAttachmentIndex(), InventorySlots::GetSlotIdFromString(), InventorySlots::GetSlotName(), m_Instance, and m_PlayerAttachmentsIndexes.
MoveAttachmentUp()
static void MoveAttachmentUp (int slot_id) static protected
Definition at line 245 of file Inventory.c.
  {
    int curr = GetPlayerAttachmentIndex(slot_id);
    int next_offset = 0;
    string next_item = "init";
    int next_id;
    EntityAI next_ent;
    while (!next_ent && next_item != "")
    {
      next_item = m_PlayerAttachmentsIndexes.GetKeyByValue(curr + --next_offset);
      next_id = InventorySlots.GetSlotIdFromString(next_item);
      next_ent = GetGame().GetPlayer().GetInventory().FindAttachment(next_id);
      if (next_ent && !m_Instance.m_RightArea.HasEntityContainerVisible(next_ent))
        next_ent = null;
    }
    if (next_item != "" && next_ent)
    {
      int next = GetPlayerAttachmentIndex(next_item);
      m_PlayerAttachmentsIndexes.Set(InventorySlots.GetSlotName(slot_id), next);
      m_PlayerAttachmentsIndexes.Set(next_item, curr);
      if (m_Instance)
        m_Instance.m_RightArea.SwapItemsInOrder(next_id, slot_id);
    }
  }
References GetGame(), GetPlayerAttachmentIndex(), InventorySlots::GetSlotIdFromString(), InventorySlots::GetSlotName(), m_Instance, and m_PlayerAttachmentsIndexes.
MoveFocusByArea()
void MoveFocusByArea (int direction) protected
Shifts between vicinity-hands-player.
Definition at line 1363 of file Inventory.c.
  {
    HideOwnedTooltip();
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (direction == Direction.LEFT)
    {
      if (m_LeftArea.IsActive())
      {
        if (!ItemManager.GetInstance().IsMicromanagmentMode())
          m_LeftArea.UnfocusGrid();
        m_LeftArea.SetActive(false);
        m_RightArea.SetActive(true);
        UpdateConsoleToolbar();
      }
      else if (m_RightArea.IsActive())
      {
        if (!ItemManager.GetInstance().IsMicromanagmentMode())
          m_RightArea.UnfocusGrid();
        m_RightArea.SetActive(false);
        player = PlayerBase.Cast(GetGame().GetPlayer());
        EntityAI item_in_hands = player.GetItemInHands();
        m_HandsArea.SetActive(true);
        UpdateConsoleToolbar();
      }
      else if (m_HandsArea.IsActive())
      {
        m_HandsArea.UnfocusGrid();
        m_HandsArea.SetActive(false);
        m_LeftArea.SetActive(true);
        UpdateConsoleToolbar();
      }
    }
    else if (direction == Direction.RIGHT)
    {
      if (m_LeftArea.IsActive())
      {
        if (!ItemManager.GetInstance().IsMicromanagmentMode())
          m_LeftArea.UnfocusGrid();
        m_LeftArea.SetActive(false);
        player = PlayerBase.Cast(GetGame().GetPlayer());
        item_in_hands = player.GetItemInHands();
        m_HandsArea.SetActive(true);
        UpdateConsoleToolbar();
      }
      else if (m_RightArea.IsActive())
      {
        if (!ItemManager.GetInstance().IsMicromanagmentMode())
          m_RightArea.UnfocusGrid();
        m_RightArea.SetActive(false);
        m_LeftArea.SetActive(true);
        UpdateConsoleToolbar();
      }
      else if (m_HandsArea.IsActive())
      {
        m_HandsArea.UnfocusGrid();
        m_HandsArea.SetActive(false);
        m_RightArea.SetActive(true);
        UpdateConsoleToolbar();
      }
    }
  }
References GetGame(), ItemManager::GetInstance(), GetPlayer(), m_HandsArea, m_LeftArea, m_RightArea, and UpdateConsoleToolbar().
Referenced by UpdateInterval().
MoveFocusByContainer()
void MoveFocusByContainer (int direction) protected
Shifts between containers vertically.
Definition at line 1334 of file Inventory.c.
  {
    HideOwnedTooltip();
    if (direction == Direction.UP)
    {
      if (m_LeftArea.IsActive())
        m_LeftArea.SetSameLevelPreviousActive();
      else if (m_RightArea.IsActive())
        m_RightArea.SetSameLevelPreviousActive();
      else if (m_HandsArea.IsActive())
        m_HandsArea.SetSameLevelPreviousActive();
      UpdateConsoleToolbar();
    }
    else if (direction == Direction.DOWN)
    {
      if (m_LeftArea.IsActive())
        m_LeftArea.SetSameLevelNextActive();
      else if (m_RightArea.IsActive())
        m_RightArea.SetSameLevelNextActive();
      else if (m_HandsArea.IsActive())
        m_HandsArea.SetSameLevelNextActive();
      UpdateConsoleToolbar();
    }
  }
References m_HandsArea, m_LeftArea, m_RightArea, and UpdateConsoleToolbar().
Referenced by UpdateInterval().
OnCenterPanelDropReceived()
void OnCenterPanelDropReceived (Widget w, int x, int y, Widget receiver) protected
Definition at line 401 of file Inventory.c.
  {
    if (w)
    {
      ItemPreviewWidget ipw = ItemPreviewWidget.Cast(w.FindAnyWidget("Render"));
      if (!ipw)
      {
        string name = w.GetName();
        name.Replace("PanelWidget", "Render");
        ipw = ItemPreviewWidget.Cast(w.FindAnyWidget(name));
        if (!ipw)
        {
          ipw = ItemPreviewWidget.Cast(w);
          if (!ipw)
            return;
        }
      }
      EntityAI item = ipw.GetItem();
      if (item)
      {
        if (!item.GetInventory().CanRemoveEntity())
          return;
        PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
        bool found = false;
        InventoryLocation inv_loc = new InventoryLocation;
        if (player)
        {
          int index = player.GetHumanInventory().FindUserReservedLocationIndex(item);
          if (index >= 0)
          {
            player.GetHumanInventory().GetUserReservedLocation(index, inv_loc);
            if (player.GetInventory().LocationCanAddEntity(inv_loc))
              SplitItemUtils.TakeOrSplitToInventoryLocation(player, inv_loc);
            return;
          }
        }
        if (player && (player.GetInventory().CanAddAttachment(item)))
        {
          float stackable = item.GetTargetQuantityMax(-1);
          if (stackable == 0 || stackable >= item.GetQuantity())
            player.PredictiveTakeEntityAsAttachment(item);
          else
          {
            InventoryLocation il = new InventoryLocation;
            player.GetInventory().FindFreeLocationFor(item, FindInventoryLocationType.ATTACHMENT, il);
            ItemBase.Cast(item).SplitIntoStackMaxToInventoryLocationClient(il);
          }
        }
        else
        {
          int slot_id = item.GetInventory().GetSlotId(0);
          EntityAI slot_item = player.GetInventory().FindAttachment(slot_id);
          if (slot_item && player.GetInventory().CanSwapEntitiesEx(item, slot_item))
            player.PredictiveSwapEntities(item, slot_item);
          else if (player.CanReceiveItemIntoCargo(item))
          {
            InventoryLocation dst = new InventoryLocation;
            player.GetInventory().FindFreeLocationFor(item, FindInventoryLocationType.ANY, dst);
            if (dst.IsValid())
            {
              if (dst.GetType() == InventoryLocationType.HANDS && item.IsHeavyBehaviour())
              {
                ActionManagerClient mngr_client;
                CastTo(mngr_client, player.GetActionManager());
                ActionTarget atrg = new ActionTarget(item, null, -1, vector.Zero, -1.0);
                if (mngr_client.GetAction(ActionTakeItemToHands).Can(player, atrg, null))
                  mngr_client.PerformActionStart(mngr_client.GetAction(ActionTakeItemToHands), atrg, null);
                return;
              }
              SplitItemUtils.TakeOrSplitToInventoryLocation(player, dst);
            }
          }
        }
      }
    }
  }
References ActionTarget, GetGame(), GetPlayer(), name, SplitItemUtils::TakeOrSplitToInventoryLocation(), and vector::Zero.
OnHandsPanelDropReceived()
void OnHandsPanelDropReceived (Widget w, int x, int y, Widget receiver) protected
Definition at line 362 of file Inventory.c.
  {
    m_HandsArea.OnHandsPanelDropReceived(w, x, y, receiver);
  }
References m_HandsArea, x, and y.
OnHide()
override void OnHide () protected
Definition at line 1079 of file Inventory.c.
  {
    Serialize();
    HideOwnedTooltip();
    Mission mission = GetGame().GetMission();
    if (mission)
    {
      IngameHud hud = IngameHud.Cast(mission.GetHud());
      if (hud)
      {
        hud.ShowQuickbarUI(true);
        hud.ShowHudInventory(false);
      }
    }
    ItemManager.GetInstance().SetSelectedItemEx(null, null, null);
  }
References GetGame(), Mission::GetHud(), ItemManager::GetInstance(), mission, and Serialize().
OnInputDeviceChanged()
void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) protected
Definition at line 167 of file Inventory.c.
  {
    switch (pInputDeviceType)
    {
    case EInputDeviceType.CONTROLLER:
      m_BottomConsoleToolbar.Show(true);
      UpdateConsoleToolbar();
      break;
    default:
      if (GetGame().GetInput().IsEnabledMouseAndKeyboardEvenOnServer())
      {
        m_BottomConsoleToolbar.Show(false);
        m_TopConsoleToolbarVicinity.Show(false);
        m_TopConsoleToolbarHands.Show(false);
        m_TopConsoleToolbarEquipment.Show(false);
      }
      break;
    }
  }
References GetGame(), GetInput(), m_BottomConsoleToolbar, m_TopConsoleToolbarEquipment, m_TopConsoleToolbarHands, m_TopConsoleToolbarVicinity, and UpdateConsoleToolbar().
Referenced by ServerBrowserTab::Construct(), UIScriptedMenu::InGameMenuXbox(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::Init(), Inventory(), ScriptedWidgetEventHandler::ItemActionsWidget(), ScriptedWidgetEventHandler::MainMenuDlcHandlerBase(), MissionBase::OnInit(), UIScriptedMenu::~InviteMenu(), UIScriptedMenu::~MainMenuConsole(), and UIScriptedMenu::~MapMenu().
OnInputPresetChanged()
void OnInputPresetChanged () protected
Definition at line 160 of file Inventory.c.
  {
#ifdef PLATFORM_CONSOLE
    UpdateConsoleToolbar();
#endif
  }
References UpdateConsoleToolbar().
Referenced by UIScriptedMenu::GesturesMenu(), UIScriptedMenu::InGameMenuXbox(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::Init(), Inventory(), ScriptedWidgetEventHandler::ItemActionsWidget(), UIScriptedMenu::RadialQuickbarMenu(), UIScriptedMenu::~InviteMenu(), UIScriptedMenu::~MainMenuConsole(), and UIScriptedMenu::~MapMenu().
OnLeftPanelDropReceived()
void OnLeftPanelDropReceived (Widget w, int x, int y, Widget receiver) protected
Definition at line 367 of file Inventory.c.
  {
    m_LeftArea.OnLeftPanelDropReceived(w, x, y, receiver);
  }
References m_LeftArea, x, and y.
OnRightPanelDropReceived()
void OnRightPanelDropReceived (Widget w, int x, int y, Widget receiver) protected
Definition at line 372 of file Inventory.c.
  {
    if (w)
    {
      ItemPreviewWidget ipw = ItemPreviewWidget.Cast(w.FindAnyWidget("Render"));
      if (!ipw)
      {
        string name = w.GetName();
        name.Replace("PanelWidget", "Render");
        ipw = ItemPreviewWidget.Cast(w.FindAnyWidget(name));
        if (!ipw)
        {
          ipw = ItemPreviewWidget.Cast(w);
          if (!ipw)
            return;
        }
      }
      EntityAI item = ipw.GetItem();
      if (item)
      {
        PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
        InventoryLocation il = new InventoryLocation;
        if (player && player.GetInventory().FindFreeLocationFor(item, FindInventoryLocationType.CARGO | FindInventoryLocationType.ATTACHMENT, il))
          SplitItemUtils.TakeOrSplitToInventory(player, player, item);
      }
    }
  }
References GetGame(), GetPlayer(), name, and SplitItemUtils::TakeOrSplitToInventory().
OnShow()
override void OnShow () protected
Definition at line 1043 of file Inventory.c.
  {
    SetFocus(GetMainWidget());
    Deserialize();
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (player && player.IsPlacingLocal())
      GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(player.TogglePlacingLocal);
    Mission mission = GetGame().GetMission();
    if (mission)
    {
      IngameHud hud = IngameHud.Cast(mission.GetHud());
      if (hud)
      {
        hud.ShowQuickbarUI(false);
        hud.ShowHudInventory(true);
      }
    }
    UpdateSpecialtyMeter();
#ifdef PLATFORM_CONSOLE
    ResetFocusedContainers();
#endif
    RefreshQuickbar();
    UpdateInterval();
    UpdateConsoleToolbar();
    m_HadFastTransferred = false;
    m_HadInspected = false;
    m_PlayerPreview.RefreshPlayerPreview();
  }
References CALL_CATEGORY_SYSTEM, Deserialize(), GetGame(), Mission::GetHud(), GetPlayer(), m_HadFastTransferred, m_HadInspected, m_PlayerPreview, mission, RefreshQuickbar(), ResetFocusedContainers(), SetFocus(), UpdateConsoleToolbar(), UpdateInterval(), and UpdateSpecialtyMeter().
Refresh()
override void Refresh () protected
Definition at line 1114 of file Inventory.c.
  {
    m_LeftArea.Refresh();
    m_HandsArea.Refresh();
    m_RightArea.Refresh();
    RefreshQuickbar();
    UpdateConsoleToolbar();
  }
References m_HandsArea, m_LeftArea, m_RightArea, RefreshQuickbar(), and UpdateConsoleToolbar().
RefreshQuickbar()
void RefreshQuickbar () protected
Definition at line 1124 of file Inventory.c.
  {
#ifndef PLATFORM_CONSOLE
    m_QuickbarWidget.Show(true);
#else
    m_QuickbarWidget.Show(GetGame().GetInput().IsEnabledMouseAndKeyboardEvenOnServer());
#endif
#ifndef PLATFORM_CONSOLE
    if (m_Quickbar)
#else
    if (m_Quickbar && GetGame().GetInput().IsEnabledMouseAndKeyboardEvenOnServer())
#endif
    {
      m_Quickbar.UpdateItems(m_QuickbarWidget);
    }
  }
References GetGame(), GetInput(), m_Quickbar, and m_QuickbarWidget.
Reset()
void Reset () protected
Definition at line 1018 of file Inventory.c.
  {
    m_LeftArea.Refresh();
    m_RightArea.Refresh();
    m_HandsArea.Refresh();
  }
References m_HandsArea, m_LeftArea, and m_RightArea.
Referenced by UIScriptedMenu::OnClick(), UIScriptedMenu::OnModalResult(), and Update().
ResetFocusedContainers()
void ResetFocusedContainers () protected
Definition at line 1025 of file Inventory.c.
  {
#ifdef PLATFORM_CONSOLE
    m_RightArea.UnfocusGrid();
    m_LeftArea.UnfocusGrid();
    m_HandsArea.UnfocusGrid();
    m_LeftArea.SetActive(false);
    m_HandsArea.SetActive(false);
    m_RightArea.SetActive(false);
    m_RightArea.ResetFocusedContainer();
    m_LeftArea.ResetFocusedContainer();
    m_RightArea.SetActive(true);
#endif
  }
References m_HandsArea, m_LeftArea, and m_RightArea.
Referenced by Inventory(), and OnShow().
Serialize()
void Serialize () protected
Definition at line 193 of file Inventory.c.
  {
    ItemManager.GetInstance().SerializeDefaultOpenStates();
    ItemManager.GetInstance().SerializeDefaultHeaderOpenStates();
  }
References ItemManager::GetInstance().
Referenced by OnHide().
SetLayoutName()
override void SetLayoutName () protected
Definition at line 990 of file Inventory.c.
  {
#ifdef PLATFORM_CONSOLE
    m_LayoutName = WidgetLayoutName.InventoryXbox;
#else
    switch (InventoryMenu.GetWidthType())
    {
    case ScreenWidthType.NARROW:
    {
      m_LayoutName = WidgetLayoutName.InventoryNarrow;
      break;
    }
    case ScreenWidthType.MEDIUM:
    {
      m_LayoutName = WidgetLayoutName.InventoryMedium;
      break;
    }
    case ScreenWidthType.WIDE:
    {
      m_LayoutName = WidgetLayoutName.InventoryWide;
      break;
    }
    }
#endif
  }
References WidgetLayoutName::InventoryMedium, InventoryMenu(), WidgetLayoutName::InventoryNarrow, and WidgetLayoutName::InventoryWide.
TimerEnd()
void TimerEnd () protected
Definition at line 320 of file Inventory.c.
  {
    m_ControllerRightStickTimerEnd = true;
    m_ControllerRightStickTimer.Stop();
  }
References m_ControllerRightStickTimer, and m_ControllerRightStickTimerEnd.
Update()
void Update (float timeslice) protected
Definition at line 562 of file Inventory.c.
  {
#ifdef PLATFORM_CONSOLE
    //inventory grid movement
    InventoryMovementButtonTickHandler(timeslice);
    if (m_InvInputActive & (1 << INV_MOV_RIGHT))
    {
      if (GetUApi().GetInputByID(UAUIDragNDrop).LocalValue())
        EnableMicromanagement();
      if (!GetUApi().GetInputByID(UAUIInventoryTabRight).LocalValue())
      {
        if (m_RightArea.IsActive())
          m_RightArea.MoveGridCursor(Direction.RIGHT);
        if (m_LeftArea.IsActive())
          m_LeftArea.MoveGridCursor(Direction.RIGHT);
        if (m_HandsArea.IsActive())
          m_HandsArea.MoveGridCursor(Direction.RIGHT);
      }
    }
    else if (m_InvInputActive & (1 << INV_MOV_LEFT))
    {
      if (GetUApi().GetInputByID(UAUIDragNDrop).LocalValue())
        EnableMicromanagement();
      if (!GetUApi().GetInputByID(UAUIInventoryTabLeft).LocalValue())
      {
        if (m_RightArea.IsActive())
          m_RightArea.MoveGridCursor(Direction.LEFT);
        if (m_LeftArea.IsActive())
          m_LeftArea.MoveGridCursor(Direction.LEFT);
        if (m_HandsArea.IsActive())
          m_HandsArea.MoveGridCursor(Direction.LEFT);
      }
    }
    else if (m_InvInputActive & (1 << INV_MOV_UP))
    {
      if (GetUApi().GetInputByID(UAUIDragNDrop).LocalValue())
        EnableMicromanagement();
      if (!GetUApi().GetInputByID(UAUIInventoryContainerUp).LocalValue())
      {
        if (m_RightArea.IsActive())
          m_RightArea.MoveGridCursor(Direction.UP);
        if (m_LeftArea.IsActive())
          m_LeftArea.MoveGridCursor(Direction.UP);
        if (m_HandsArea.IsActive())
          m_HandsArea.MoveGridCursor(Direction.UP);
      }
    }
    else if (m_InvInputActive & (1 << INV_MOV_DOWN))
    {
      if (GetUApi().GetInputByID(UAUIDragNDrop).LocalValue())
        EnableMicromanagement();
      if (!GetUApi().GetInputByID(UAUIInventoryContainerDown).LocalValue())
      {
        if (m_RightArea.IsActive())
          m_RightArea.MoveGridCursor(Direction.DOWN);
        if (m_LeftArea.IsActive())
          m_LeftArea.MoveGridCursor(Direction.DOWN);
        if (m_HandsArea.IsActive())
          m_HandsArea.MoveGridCursor(Direction.DOWN);
      }
    }
    m_InvInputActive = 0;
#endif
    UpdateInterval();
  }
References EnableMicromanagement(), GetUApi(), INV_MOV_DOWN, INV_MOV_LEFT, INV_MOV_RIGHT, INV_MOV_UP, InventoryMovementButtonTickHandler(), m_HandsArea, m_InvInputActive, m_LeftArea, m_RightArea, and UpdateInterval().
UpdateConsoleToolbar()
void UpdateConsoleToolbar () protected
Definition at line 1211 of file Inventory.c.
  {
#ifdef PLATFORM_CONSOLE
    int combinationFlag = 0;
    string contextualText;
    InventoryLocation il;
    Container focusedArea = GetFocusedArea();
    if (focusedArea)
    {
      Container focusedContainer = GetFocusedArea().GetFocusedContainer();
      EntityAI focusedItem = GetFocusedArea().GetFocusedItem();
      if (!(focusedItem && focusedItem.IsSetForDeletion()))
      {
        if (focusedContainer)
        {
          if (focusedItem)
          {
            il = new InventoryLocation;
            focusedItem.GetInventory().GetCurrentInventoryLocation(il);
          }
          bool canBeManipulated = false;
          PlayerBase player;
          PlayerBase itemPlayerOwner;
          player = PlayerBase.Cast(GetGame().GetPlayer());
          m_NeedUpdateConsoleToolbar = player.GetInventory().GetAnyInventoryReservationCount() > 0;
          if (focusedItem)
          {
            itemPlayerOwner = PlayerBase.Cast(focusedItem.GetHierarchyRootPlayer());
            il = new InventoryLocation;
            focusedItem.GetInventory().GetCurrentInventoryLocation(il);
            canBeManipulated = !player.GetInventory().HasInventoryReservation(focusedItem, null) && !player.GetInventory().IsInventoryLocked() && !player.IsItemsToDelete();
            m_NeedUpdateConsoleToolbar |= !canBeManipulated;
            canBeManipulated = canBeManipulated && focusedItem.CanPutIntoHands(null);
            canBeManipulated = canBeManipulated && focusedItem.GetInventory().CanRemoveEntity();
            EntityAI parent = il.GetParent();
            if (parent && il.GetType() == InventoryLocationType.ATTACHMENT)
            {
              canBeManipulated = canBeManipulated && AttachmentsOutOfReach.IsAttachmentReachable(parent, "", il.GetSlot());
              canBeManipulated = canBeManipulated && !parent.GetInventory().GetSlotLock(il.GetSlot());
            }
            if (canBeManipulated)
            {
              if (!ItemManager.GetInstance().IsMicromanagmentMode())
                combinationFlag |= ConsoleActionToolbarMask.MICROMANAGMENT;
              if (focusedContainer.CanEquipEx(focusedItem))
                combinationFlag |= ConsoleActionToolbarMask.EQUIP;
              if (player != null && player == itemPlayerOwner)
              {
                if (focusedContainer.CanSwapOrTakeToHandsEx(focusedItem))
                  combinationFlag |= ConsoleActionToolbarMask.TO_HANDS_SWAP_INVENTORY;
                if (focusedContainer.CanDropEx(focusedItem))
                  combinationFlag |= ConsoleActionToolbarMask.DROP;
              }
              else
              {
                if (focusedContainer.CanSwapOrTakeToHandsEx(focusedItem))
                  combinationFlag |= ConsoleActionToolbarMask.TO_HANDS_SWAP_VICINITY;
              }
              if (focusedContainer.CanCombineEx(focusedItem))
                combinationFlag |= ConsoleActionToolbarMask.COMBINE;
              if (focusedContainer.CanSplitEx(focusedItem))
                combinationFlag |= ConsoleActionToolbarMask.SPLIT;
              if (focusedArea.CanTakeToInventoryEx(focusedItem))
                combinationFlag |= ConsoleActionToolbarMask.TO_INVENTORY;
            }
          }
          if (focusedContainer.CanOpenCloseContainerEx(focusedItem))
            combinationFlag |= ConsoleActionToolbarMask.OPEN_CLOSE_CONTAINER;
          if (player != null && focusedContainer.CanAddToQuickbarEx(focusedItem))
            combinationFlag |= ConsoleActionToolbarMask.QUICKSLOT;
        }
      }
      contextualText = GetConsoleToolbarText(combinationFlag);
      if (m_TopConsoleToolbarVicinity)
        m_TopConsoleToolbarVicinity.Show(m_LeftArea.IsActive());
      if (m_TopConsoleToolbarHands)
        m_TopConsoleToolbarHands.Show(m_HandsArea.IsActive());
      if (m_TopConsoleToolbarEquipment)
        m_TopConsoleToolbarEquipment.Show(m_RightArea.IsActive());
      if (m_BottomConsoleToolbarRichText)
        m_BottomConsoleToolbarRichText.SetText(contextualText + " ");
    }
#endif
  }
References GetFocusedArea(), Container::GetFocusedItem(), GetGame(), ItemManager::GetInstance(), GetPlayer(), AttachmentsOutOfReach::IsAttachmentReachable(), m_BottomConsoleToolbarRichText, m_HandsArea, m_LeftArea, m_NeedUpdateConsoleToolbar, m_RightArea, m_TopConsoleToolbarEquipment, m_TopConsoleToolbarHands, and m_TopConsoleToolbarVicinity.
Referenced by Controller(), DisableMicromanagement(), EnableMicromanagement(), Inventory(), MoveFocusByArea(), MoveFocusByContainer(), OnInputDeviceChanged(), OnInputPresetChanged(), OnShow(), Refresh(), and UpdateInterval().
UpdateInterval()
override void UpdateInterval () protected
Definition at line 636 of file Inventory.c.
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    InventoryItem item;
    if (GetUApi().GetInputByID(UAUIRotateInventory).LocalPress())
    {
      item = InventoryItem.Cast(ItemManager.GetInstance().GetDraggedItem());
      if (item)
      {
        int size_x, size_y;
        GetGame().GetInventoryItemSize(item, size_x, size_y);
        if (size_x != size_y)
        {
          item.GetInventory().FlipCargo();
          item.GetOnItemFlipped().Invoke(item.GetInventory().GetFlipCargo());
        }
      }
    }
#ifdef PLATFORM_CONSOLE
    DayZPlayerInventory dpi;
    if (player)
      dpi = player.GetDayZPlayerInventory();
    // There's a second one a bit below
    if (dpi && !dpi.IsProcessing())
    {
      if (GetUApi().GetInputByID(UAUIExpandCollapseContainer).LocalPress())
      {
        if (m_RightArea.IsActive())
          m_RightArea.ExpandCollapseContainer();
        else if (m_LeftArea.IsActive())
          m_LeftArea.ExpandCollapseContainer();
      }
      if (GetUApi().GetInputByID(UAUIDragNDrop).LocalHoldBegin())
        EnableMicromanagement();
      if (GetUApi().GetInputByID(UAUISplit).LocalPress())
      {
        if (m_HandsArea.IsActive())
        {
          if (m_HandsArea.SplitItem())
          {
            m_HandsArea.SetActive(false);
            m_HandsArea.UnfocusGrid();
            m_RightArea.SetActive(true);
          }
        }
        else if (m_RightArea.IsActive())
          m_RightArea.SplitItem();
        else if (m_LeftArea.IsActive())
          m_LeftArea.SplitItem();
        HideOwnedTooltip();
      }
      if (GetUApi().GetInputByID(UAUIFastEquip).LocalPress())
      {
        if (m_HandsArea.IsActive())
        {
          if (m_HandsArea.EquipItem())
          {
            m_HandsArea.SetActive(false);
            m_HandsArea.UnfocusGrid();
            m_RightArea.SetActive(true);
          }
        }
        else if (m_RightArea.IsActive())
          m_RightArea.EquipItem();
        else if (m_LeftArea.IsActive())
          m_LeftArea.EquipItem();
        UpdateConsoleToolbar();
        HideOwnedTooltip();
      }
      if (ItemManager.GetInstance().IsMicromanagmentMode() && GetUApi().GetInputByID(UAUIDragNDrop).LocalRelease())
      {
        if (m_RightArea.IsActive())
          m_RightArea.Select();
        else if (m_LeftArea.IsActive())
          m_LeftArea.Select();
        else if (m_HandsArea.IsActive())
          m_HandsArea.Select();
        DisableMicromanagement();
        UpdateConsoleToolbar();
      }
      if (GetUApi().GetInputByID(UAUIPutInHandsFromVicinity).LocalPress())
      {
        if (m_LeftArea.IsActive())
        {
          if (m_LeftArea.Select())
          {
            m_LeftArea.SetActive(false);
            m_LeftArea.UnfocusGrid();
            m_HandsArea.SetActive(true);
            UpdateConsoleToolbar();
          }
        }
      }
      if (GetUApi().GetInputByID(UAUIPutInHandsFromInventory).LocalPress())
      {
        if (m_RightArea.IsActive())
        {
          if (m_RightArea.Select())
          {
            m_RightArea.SetActive(false);
            m_RightArea.UnfocusGrid();
            m_HandsArea.SetActive(true);
            UpdateConsoleToolbar();
          }
        }
      }
      if (GetUApi().GetInputByID(UAUIFastTransferToVicinity).LocalPress()) //item drop
      {
        if (m_HandsArea.IsActive())
        {
          item = InventoryItem.Cast(m_HandsArea.GetFocusedItem());
          if (item && item.GetInventory().CanRemoveEntity())
          {
            if (m_HandsArea.TransferItemToVicinity())
            {
              m_HandsArea.SetActive(false);
              m_HandsArea.UnfocusGrid();
              m_LeftArea.SetActive(true);
              m_HadFastTransferred = true;
            }
          }
        }
        else if (m_RightArea.IsActive())
        {
          item = InventoryItem.Cast(m_RightArea.GetFocusedItem());
          if (item && item.GetInventory().CanRemoveEntity())
          {
            if (m_RightArea.TransferItemToVicinity())
              m_HadFastTransferred = true;
          }
        }
        UpdateConsoleToolbar();
        HideOwnedTooltip();
      }
    }
    if (GetUApi().GetInputByID(UAUIInspectItem).LocalPress())
    {
      if (m_HandsArea.IsActive())
      {
        if (m_HandsArea.InspectItem())
          m_HadInspected = true;
      }
      else if (m_RightArea.IsActive())
      {
        if (m_RightArea.InspectItem())
          m_HadInspected = true;
      }
      else if (m_LeftArea.IsActive())
      {
        if (m_LeftArea.InspectItem())
          m_HadInspected = true;
      }
      UpdateConsoleToolbar();
    }
    if (GetUApi().GetInputByID(UAUIFastTransferItem).LocalPress())
      m_HadFastTransferred = false;
    if (GetUApi().GetInputByID(UAUIInspectItem).LocalPress())
      m_HadInspected = false;
    if (dpi && !dpi.IsProcessing())
    {
      if (!m_HadFastTransferred && GetUApi().GetInputByID(UAUIFastTransferItem).LocalPress()) //transfers item to inventory (not hands, or hands last?)
      {
        if (m_LeftArea.IsActive())
        {
          item = InventoryItem.Cast(m_LeftArea.GetFocusedItem());
          if (item && item.GetInventory().CanRemoveEntity())
            m_LeftArea.TransferItem();
        }
        else if (m_HandsArea.IsActive())
        {
          item = InventoryItem.Cast(m_HandsArea.GetFocusedItem());
          if (item && item.GetInventory().CanRemoveEntity())
          {
            if (m_HandsArea.TransferItem())
            {
              m_HandsArea.SetActive(false);
              m_HandsArea.UnfocusGrid();
              m_RightArea.SetActive(true);
            }
          }
        }
        UpdateConsoleToolbar();
        HideOwnedTooltip();
      }
    }
    if (GetUApi().GetInputByID(UAUIInventoryContainerUp).LocalPress())
    {
      if (GetUApi().GetInputByID(UAUIDragNDrop).LocalValue())
        EnableMicromanagement();
      MoveFocusByContainer(Direction.UP);
    }
    if (GetUApi().GetInputByID(UAUIInventoryContainerDown).LocalPress())
    {
      if (GetUApi().GetInputByID(UAUIDragNDrop).LocalValue())
        EnableMicromanagement();
      MoveFocusByContainer(Direction.DOWN);
    }
    if (GetUApi().GetInputByID(UAUIInventoryTabLeft).LocalPress())
    {
      if (GetUApi().GetInputByID(UAUIDragNDrop).LocalValue())
        EnableMicromanagement();
      MoveFocusByArea(Direction.LEFT);
    }
    if (GetUApi().GetInputByID(UAUIInventoryTabRight).LocalPress())
    {
      if (GetUApi().GetInputByID(UAUIDragNDrop).LocalValue())
        EnableMicromanagement();
      MoveFocusByArea(Direction.RIGHT);
    }
    //Open Quickbar radial menu
    if (GetUApi().GetInputByID(UAUIQuickbarRadialInventoryOpen).LocalPress())
    {
      //assign item
      EntityAI item_to_assign;
      if (m_HandsArea.IsActive())
      {
        player = PlayerBase.Cast(GetGame().GetPlayer());
        item_to_assign = player.GetItemInHands();
        m_HandsArea.AddItemToQuickbarRadial(item_to_assign);
      }
      else if (m_RightArea.IsActive())
      {
        item_to_assign = m_RightArea.GetFocusedItem();
        m_RightArea.AddItemToQuickbarRadial(item_to_assign);
      }
    }
#endif
    MissionGameplay mission = MissionGameplay.Cast(GetGame().GetMission());
    if (!m_HadInspected && GetUApi().GetInputByID(UAUICombine).LocalPress())
    {
      if (GetMainWidget().IsVisible())
      {
#ifdef PLATFORM_CONSOLE
        //DisableMicromanagement();
        if (m_RightArea.IsActive())
        {
          if (m_RightArea.CanCombine())
          {
            if (m_RightArea.Combine())
              mission.HideInventory();
          }
        }
        else if (m_LeftArea.IsActive())
        {
          if (m_LeftArea.CanCombine())
          {
            if (m_LeftArea.Combine())
              mission.HideInventory();
          }
        }
#endif
      }
    }
    if (!m_HadInspected && GetUApi().GetInputByID(UAUIBack).LocalPress())
      mission.HideInventory();
    for (int i = 0; i < 10; i++)
    {
      if (!m_HoldingQB && GetUApi().GetInputByName("UAItem" + i).LocalPress())
      {
        m_QBHoveredItems = InventoryItem.Cast(ItemManager.GetInstance().GetHoveredItem());
        m_HoldingQB = true;
      }
      if (m_HoldingQB && GetUApi().GetInputByName("UAItem" + i).LocalHold())
      {
        AddQuickbarItem(m_QBHoveredItems, i);
        m_QBHoveredItems = null;
        m_HoldingQB = false;
      }
    }
    m_LeftArea.UpdateInterval();
    m_RightArea.UpdateInterval();
    m_HandsArea.UpdateInterval();
    m_PlayerPreview.UpdateInterval();
#ifdef PLATFORM_CONSOLE
    UpdateConsoleToolbarCheck();
#endif
  }
References AddQuickbarItem(), DisableMicromanagement(), EnableMicromanagement(), GetGame(), ItemManager::GetInstance(), GetPlayer(), GetUApi(), Mission::HideInventory(), IsVisible(), m_HadFastTransferred, m_HadInspected, m_HandsArea, m_HoldingQB, m_LeftArea, m_PlayerPreview, m_QBHoveredItems, m_RightArea, mission, MoveFocusByArea(), MoveFocusByContainer(), and UpdateConsoleToolbar().
Referenced by OnShow(), and Update().
UpdateSpecialtyMeter()
void UpdateSpecialtyMeter () protected
Definition at line 1096 of file Inventory.c.
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (player && player.GetSoftSkillsManager())
    {
      float x = player.GetSoftSkillsManager().GetSpecialtyLevel() / 2;
      float y = -0.75;
#ifndef PLATFORM_CONSOLE
      m_SpecializationIcon.SetPos(x, y, true);
#else
      Mission mission = GetGame().GetMission();
      IngameHud hud = IngameHud.Cast(mission.GetHud());
      if (hud)
        hud.UpdateSpecialtyMeter(x, y);
#endif
    }
  }
References GetGame(), Mission::GetHud(), GetPlayer(), m_SpecializationIcon, mission, x, and y.
Referenced by OnShow().
Variable Documentation
BT_REPEAT_DELAY
const float BT_REPEAT_DELAY = 0.35 protected
Definition at line 61 of file Inventory.c.
Referenced by InventoryMovementButtonTickHandler().
BT_REPEAT_TIME
const float BT_REPEAT_TIME = 0.09 protected
Definition at line 62 of file Inventory.c.
Referenced by InventoryMovementButtonTickHandler().
BT_THRESHOLD_VALUE
const float BT_THRESHOLD_VALUE = 0.8 protected
Definition at line 63 of file Inventory.c.
Referenced by InventoryMovementButtonTickHandler().
INV_MOV_DOWN
const int INV_MOV_DOWN = 3 protected
Definition at line 67 of file Inventory.c.
Referenced by Update().
INV_MOV_LEFT
const int INV_MOV_LEFT = 0 protected
Definition at line 64 of file Inventory.c.
Referenced by Update().
INV_MOV_RIGHT
const int INV_MOV_RIGHT = 1 protected
Definition at line 65 of file Inventory.c.
Referenced by Update().
INV_MOV_UP
const int INV_MOV_UP = 2 protected
Definition at line 66 of file Inventory.c.
Referenced by Update().
m_BottomConsoleToolbar
Widget m_BottomConsoleToolbar protected
Definition at line 40 of file Inventory.c.
Referenced by Inventory(), and OnInputDeviceChanged().
m_BottomConsoleToolbarRichText
RichTextWidget m_BottomConsoleToolbarRichText protected
Definition at line 41 of file Inventory.c.
Referenced by Inventory(), and UpdateConsoleToolbar().
m_ContextMenu
ref ContextMenu m_ContextMenu protected
Definition at line 43 of file Inventory.c.
m_ControllerAngle
int m_ControllerAngle protected
Definition at line 52 of file Inventory.c.
m_ControllerRightStickTimer
ref Timer m_ControllerRightStickTimer protected
Definition at line 55 of file Inventory.c.
Referenced by Controller(), Inventory(), and TimerEnd().
m_ControllerRightStickTimerEnd
bool m_ControllerRightStickTimerEnd = true protected
Definition at line 54 of file Inventory.c.
Referenced by Controller(), and TimerEnd().
m_ControllerTilt
int m_ControllerTilt protected
Definition at line 53 of file Inventory.c.
m_HadFastTransferred
bool m_HadFastTransferred protected
Definition at line 46 of file Inventory.c.
Referenced by OnShow(), and UpdateInterval().
m_HadInspected
bool m_HadInspected protected
Definition at line 47 of file Inventory.c.
Referenced by OnShow(), and UpdateInterval().
m_HandsArea
ref HandsArea m_HandsArea protected
Definition at line 30 of file Inventory.c.
Referenced by DraggingOverHandsPanel(), EnableMicromanagement(), GetFocusedArea(), Inventory(), MoveFocusByArea(), MoveFocusByContainer(), OnHandsPanelDropReceived(), Refresh(), Reset(), ResetFocusedContainers(), Update(), UpdateConsoleToolbar(), and UpdateInterval().
m_HoldingQB
bool m_HoldingQB protected
Definition at line 57 of file Inventory.c.
Referenced by UpdateInterval().
m_InpInp
UAInput m_InpInp = null protected
Definition at line 635 of file Inventory.c.
m_Instance
Inventory m_Instance static protected
Definition at line 50 of file Inventory.c.
m_InvInputActive
int m_InvInputActive = 0 protected
Definition at line 74 of file Inventory.c.
Referenced by InventoryMovementButtonTickHandler(), and Update().
m_InvInputNames
ref array<string> m_InvInputNames = {"UAUILeftInventory", "UAUIRightInventory", "UAUIUpInventory", "UAUIDownInventory"} protected
Definition at line 68 of file Inventory.c.
{"UAUILeftInventory", "UAUIRightInventory", "UAUIUpInventory", "UAUIDownInventory"};
Referenced by InitInputWrapperData().
m_InvInputTimes
ref array<float> m_InvInputTimes protected
Definition at line 70 of file Inventory.c.
Referenced by InitInputWrapperData(), and InventoryMovementButtonTickHandler().
m_InvInputWrappers
ref array<UAIDWrapper> m_InvInputWrappers protected
Definition at line 69 of file Inventory.c.
Referenced by InitInputWrapperData(), and InventoryMovementButtonTickHandler().
m_InvInputWrappersCount
int m_InvInputWrappersCount protected
Definition at line 71 of file Inventory.c.
Referenced by InitInputWrapperData(), and InventoryMovementButtonTickHandler().
m_InvUAInput
UAInput m_InvUAInput protected
Definition at line 73 of file Inventory.c.
Referenced by InventoryMovementButtonTickHandler().
m_LeftArea
enum Direction m_LeftArea
Referenced by DraggingOverLeftPanel(), EnableMicromanagement(), GetFocusedArea(), Inventory(), MoveFocusByArea(), MoveFocusByContainer(), OnLeftPanelDropReceived(), Refresh(), Reset(), ResetFocusedContainers(), Update(), UpdateConsoleToolbar(), and UpdateInterval().
m_NeedUpdateConsoleToolbar
bool m_NeedUpdateConsoleToolbar protected
Definition at line 48 of file Inventory.c.
Referenced by Inventory(), and UpdateConsoleToolbar().
m_PlayerAttachmentsIndexes
ref map<string, int> m_PlayerAttachmentsIndexes static protected
Definition at line 44 of file Inventory.c.
Referenced by GetPlayerAttachmentIndex(), LoadPlayerAttachmentIndexes(), MoveAttachmentDown(), and MoveAttachmentUp().
m_PlayerPreview
ref PlayerPreview m_PlayerPreview protected
Definition at line 31 of file Inventory.c.
Referenced by Inventory(), OnShow(), and UpdateInterval().
m_QBHoveredItems
InventoryItem m_QBHoveredItems protected
Definition at line 58 of file Inventory.c.
Referenced by UpdateInterval().
m_Quickbar
ref InventoryQuickbar m_Quickbar protected
Definition at line 32 of file Inventory.c.
Referenced by Hud::InitQuickbar(), Inventory(), RefreshQuickbar(), and Hud::RefreshQuickbar().
m_QuickbarWidget
Widget m_QuickbarWidget protected
Definition at line 34 of file Inventory.c.
Referenced by Hud::Init(), Hud::InitQuickbar(), Inventory(), RefreshQuickbar(), Hud::RefreshQuickbar(), and Hud::RefreshQuickbarVisibility().
m_RightArea
ref RightArea m_RightArea protected
Definition at line 29 of file Inventory.c.
Referenced by DraggingOverRightPanel(), EnableMicromanagement(), GetFocusedArea(), Inventory(), MoveFocusByArea(), MoveFocusByContainer(), Refresh(), Reset(), ResetFocusedContainers(), Update(), UpdateConsoleToolbar(), and UpdateInterval().
m_SensitivityThreshold
float m_SensitivityThreshold = 0.0 protected
Definition at line 72 of file Inventory.c.
Referenced by InventoryMovementButtonTickHandler().
m_SpecializationIcon
Widget m_SpecializationIcon protected
Definition at line 36 of file Inventory.c.
Referenced by Hud::Init(), Inventory(), UpdateSpecialtyMeter(), and Hud::UpdateSpecialtyMeter().
m_SpecializationPanel
Widget m_SpecializationPanel protected
Definition at line 35 of file Inventory.c.
Referenced by Inventory().
m_TopConsoleToolbarEquipment
Widget m_TopConsoleToolbarEquipment protected
Definition at line 39 of file Inventory.c.
Referenced by Inventory(), OnInputDeviceChanged(), and UpdateConsoleToolbar().
m_TopConsoleToolbarHands
Widget m_TopConsoleToolbarHands protected
Definition at line 38 of file Inventory.c.
Referenced by Inventory(), OnInputDeviceChanged(), and UpdateConsoleToolbar().
m_TopConsoleToolbarVicinity
Widget m_TopConsoleToolbarVicinity protected
Definition at line 37 of file Inventory.c.
Referenced by Inventory(), OnInputDeviceChanged(), and UpdateConsoleToolbar().