DayZ: scripts/4_World/Classes/UserActionsComponent/Actions/Interact/ActionGetOutTransport.c File Reference
ActionGetOutTransport.c File Reference
Classes
class GetOutTransportActionData
Functions
void ActionGetOutTransport ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override GetInputType ()
override bool HasProgress ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ProcessGetOutActionData (Car car, GetOutTransportActionData got_action_data)
override void OnStart (ActionData action_data)
override void OnStartServer (ActionData action_data)
void Unhide (PlayerBase player)
override void OnUpdate (ActionData action_data)
override bool CanBeUsedInRestrain ()
override bool CanBeUsedInVehicle ()
override int GetActionCategory ()
override void OnEnd (ActionData action_data)
override void OnEndServer (ActionData action_data)
void ApplyJumpOutDmg (ActionData action_data)
Variables
GetOutTransportActionData m_DmgFactor = 60
int m_ShockFactor = 15
const int LOW_SPEED_VALUE = 20
const int HIGH_SPEED_VALUE = 30
const int HEALTH_LOW_SPEED_VALUE = 30
const int HEALTH_HIGH_SPEED_VALUE = 70
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) private
Definition at line 53 of file ActionGetOutTransport.c.
  {
    HumanCommandVehicle vehCommand = player.GetCommand_Vehicle();
    if (vehCommand)
    {
      Transport trans = vehCommand.GetTransport();
      if (trans)
      {
        int crewIndex = trans.CrewMemberIndex(player);
        return crewIndex >= 0 && trans.CrewCanGetThrough(crewIndex) && trans.IsAreaAtDoorFree(crewIndex);
      }
    }
    return false;
  }
ActionGetOutTransport()
void ActionGetOutTransport () private
Definition at line 24 of file ActionGetOutTransport.c.
  {
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ALL;
    m_Text = "#leave_vehicle";
  }
References m_StanceMask, and m_Text.
Referenced by ActionConstructor::RegisterActions(), and ManBase::SetActions().
ApplyJumpOutDmg()
void ApplyJumpOutDmg (ActionData action_data) private
Definition at line 185 of file ActionGetOutTransport.c.
  {
    GetOutTransportActionData gotActionData = GetOutTransportActionData.Cast(action_data);
    PlayerBase player = gotActionData.m_Player;
    array<ClothingBase> equippedClothes = new array<ClothingBase>;
    equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("LEGS")));
    equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("BACK")));
    equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("VEST")));
    equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("HeadGear")));
    equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("Mask")));
    equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("BODY")));
    equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("FEET")));
    equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("GLOVES")));
    // -----------------------------------------------
    //Lower shock taken if player uses a helmet
    ItemBase headGear = ClothingBase.Cast(player.GetItemOnHead());
    HelmetBase helmet;
    if (Class.CastTo(helmet, headGear))
      gotActionData.m_ShockTaken *= 0.5;
    // -----------------------------------------------
    int randNum; //value used for probability evaluation
    randNum = Math.RandomInt(0, 100);
    if (gotActionData.m_CarSpeed < LOW_SPEED_VALUE)
    {
      if (randNum < 20)
        player.GiveShock(-gotActionData.m_ShockTaken); //To inflict shock, a negative value must be passed
      randNum = Math.RandomIntInclusive(0, PlayerBase.m_BleedingSourcesLow.Count() - 1);
      player.m_BleedingManagerServer.AttemptAddBleedingSourceBySelection(PlayerBase.m_BleedingSourcesLow[randNum]);
    }
    else if (gotActionData.m_CarSpeed >= LOW_SPEED_VALUE && gotActionData.m_CarSpeed < HIGH_SPEED_VALUE)
    {
      if (randNum < 50)
        player.GiveShock(-gotActionData.m_ShockTaken);
      randNum = Math.RandomInt(0, PlayerBase.m_BleedingSourcesUp.Count() - 1);
      player.m_BleedingManagerServer.AttemptAddBleedingSourceBySelection(PlayerBase.m_BleedingSourcesUp[randNum]);
    }
    else if (gotActionData.m_CarSpeed >= HIGH_SPEED_VALUE)
    {
      if (!headGear)
        player.m_BleedingManagerServer.AttemptAddBleedingSourceBySelection("Head");
      if (randNum < 75)
        player.GiveShock(-gotActionData.m_ShockTaken);
    }
    //Damage all currently equipped clothes
    foreach (ClothingBase cloth : equippedClothes)
    {
      //If no item is equipped on slot, slot is ignored
      if (cloth == null)
        continue;
      cloth.DecreaseHealth(gotActionData.m_DmgTaken, false);
    }
  }
References Class::CastTo(), HIGH_SPEED_VALUE, LOW_SPEED_VALUE, Math::RandomInt(), and Math::RandomIntInclusive().
Referenced by OnEndServer().
CanBeUsedInRestrain()
override bool CanBeUsedInRestrain () private
Definition at line 136 of file ActionGetOutTransport.c.
  {
    return true;
  }
CanBeUsedInVehicle()
override bool CanBeUsedInVehicle () private
Definition at line 141 of file ActionGetOutTransport.c.
  {
    return true;
  }
CreateActionData()
override ActionData CreateActionData () private
Definition at line 30 of file ActionGetOutTransport.c.
  {
    ActionData data = new GetOutTransportActionData();
    return data;
  }
CreateConditionComponents()
override void CreateConditionComponents () private
Definition at line 37 of file ActionGetOutTransport.c.
  {
    m_ConditionItem = new CCINone();
    m_ConditionTarget = new CCTNone();
  }
References m_ConditionItem, and m_ConditionTarget.
GetActionCategory()
override int GetActionCategory () private
Definition at line 146 of file ActionGetOutTransport.c.
  {
    return AC_INTERACT;
  }
References AC_INTERACT.
GetInputType()
override GetInputType () private
Definition at line 43 of file ActionGetOutTransport.c.
  {
    return ContinuousInteractActionInput;
  }
HasProgress()
override bool HasProgress () private
Definition at line 48 of file ActionGetOutTransport.c.
  {
    return false;
  }
OnEnd()
override void OnEnd (ActionData action_data) private
Definition at line 151 of file ActionGetOutTransport.c.
  {
    if (action_data.m_Player.GetInventory())
      action_data.m_Player.GetInventory().UnlockInventory(LOCK_FROM_SCRIPT);
  }
OnEndServer()
override void OnEndServer (ActionData action_data) private
Definition at line 157 of file ActionGetOutTransport.c.
  {
    GetOutTransportActionData gotActionData = GetOutTransportActionData.Cast(action_data);
    if (gotActionData.m_WasJumpingOut)
    {
      float carSpeed = gotActionData.m_CarSpeed;
      gotActionData.m_Player.OnJumpOutVehicleFinish(carSpeed);
      ApplyJumpOutDmg(action_data);
      vector posMS = gotActionData.m_Player.WorldToModel(gotActionData.m_Player.GetPosition());
      gotActionData.m_Player.DamageAllLegs(gotActionData.m_DmgTaken); //Additionnal leg specific damage dealing
      float healthCoef = Math.InverseLerp(HEALTH_LOW_SPEED_VALUE, HEALTH_HIGH_SPEED_VALUE, carSpeed);
      healthCoef = Math.Clamp(healthCoef, 0.0, 1.0);
      gotActionData.m_Player.ProcessDirectDamage(DamageType.CUSTOM, gotActionData.m_Player, "", "FallDamageHealth", posMS, healthCoef);
    }
    if (gotActionData.m_Car)
    {
      CarScript car;
      if (Class.CastTo(car, gotActionData.m_Car))
        car.ForceUpdateLightsEnd();
    }
  }
References ApplyJumpOutDmg(), Class::CastTo(), Math::Clamp(), HEALTH_HIGH_SPEED_VALUE, HEALTH_LOW_SPEED_VALUE, and Math::InverseLerp().
OnStart()
override void OnStart (ActionData action_data) private
Definition at line 80 of file ActionGetOutTransport.c.
  {
    super.OnStart(action_data);
    HumanCommandVehicle vehCommand = action_data.m_Player.GetCommand_Vehicle();
    if (vehCommand)
    {
      Transport trans = vehCommand.GetTransport();
      if (trans)
      {
        GetOutTransportActionData gotActionData = GetOutTransportActionData.Cast(action_data);
        Car car;
        if (Class.CastTo(car, trans))
          ProcessGetOutActionData(car, gotActionData);
        if (!gotActionData.m_WasJumpingOut)
          vehCommand.GetOutVehicle();
        else
          vehCommand.JumpOutVehicle();
        if (car)
          GetDayZGame().GetBacklit().OnLeaveCar();
        if (action_data.m_Player.GetInventory())
          action_data.m_Player.GetInventory().LockInventory(LOCK_FROM_SCRIPT);
      }
    }
  }
References Class::CastTo(), GetDayZGame(), and ProcessGetOutActionData().
OnStartServer()
override void OnStartServer (ActionData action_data) private
Definition at line 110 of file ActionGetOutTransport.c.
  {
    HumanCommandVehicle vehCommand = action_data.m_Player.GetCommand_Vehicle();
    if (vehCommand)
    {
      Transport trans = vehCommand.GetTransport();
      if (trans)
      {
        CarScript car;
        if (Class.CastTo(car, trans))
          car.ForceUpdateLightsStart();
      }
    }
  }
References Class::CastTo().
OnUpdate()
override void OnUpdate (ActionData action_data) private
Definition at line 127 of file ActionGetOutTransport.c.
  {
    if (action_data.m_State == UA_START)
    {
      if (!action_data.m_Player.GetCommand_Vehicle())
        End(action_data);
    }
  }
References End(), and UA_START.
ProcessGetOutActionData()
void ProcessGetOutActionData (Car car, GetOutTransportActionData got_action_data) private
Definition at line 69 of file ActionGetOutTransport.c.
  {
    got_action_data.m_StartLocation = got_action_data.m_Player.GetPosition();
    got_action_data.m_Car = car;
    float carSpeed = car.GetSpeedometerAbsolute();
    got_action_data.m_CarSpeed = carSpeed;
    got_action_data.m_DmgTaken = (carSpeed * carSpeed) / m_DmgFactor; //When using multiplications, wrong value is returned
    got_action_data.m_ShockTaken = (carSpeed * carSpeed) / m_ShockFactor;
    got_action_data.m_WasJumpingOut = carSpeed > 8.0;
  }
References m_DmgFactor, and m_ShockFactor.
Referenced by OnStart().
Unhide()
void Unhide (PlayerBase player) private
Variable Documentation
HEALTH_HIGH_SPEED_VALUE
const int HEALTH_HIGH_SPEED_VALUE = 70 private
Definition at line 22 of file ActionGetOutTransport.c.
Referenced by OnEndServer().
HEALTH_LOW_SPEED_VALUE
const int HEALTH_LOW_SPEED_VALUE = 30 private
Definition at line 21 of file ActionGetOutTransport.c.
Referenced by OnEndServer().
HIGH_SPEED_VALUE
const int HIGH_SPEED_VALUE = 30
Definition at line 19 of file ActionGetOutTransport.c.
Referenced by ApplyJumpOutDmg().
LOW_SPEED_VALUE
const int LOW_SPEED_VALUE = 20
Definition at line 18 of file ActionGetOutTransport.c.
Referenced by ApplyJumpOutDmg().
m_DmgFactor
GetOutTransportActionData m_DmgFactor = 60
Referenced by ProcessGetOutActionData().
m_ShockFactor
int m_ShockFactor = 15
Definition at line 15 of file ActionGetOutTransport.c.
Referenced by ProcessGetOutActionData().