DayZ: ActionRepackTent Class Reference
ActionRepackTent Class Reference
Private Member Functions
void ActionRepackTent ()
override void CreateConditionComponents ()
override bool HasTarget ()
override bool HasProgress ()
override bool ActionConditionContinue (ActionData action_data)
override bool HasAlternativeInterrupt ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
override void OnStartServer (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
void SetupAnimation (ItemBase item)
override void OnStartAnimationLoopClient (ActionData action_data)
override void OnStartAnimationLoopServer (ActionData action_data)
override void OnEndAnimationLoop (ActionData action_data)
override string GetAdminLogMessage (ActionData action_data)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Private Attributes
EntityAI m_RepackedEntity
bool m_IsFinished
Detailed Description
Definition at line 42 of file ActionRepackTent.c.
Constructor & Destructor Documentation
ActionRepackTent()
void ActionRepackTent::ActionRepackTent () inline private
Definition at line 47 of file ActionRepackTent.c.
  {
    m_CallbackClass = ActionRepackTentCB;
    m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
    m_CommandUID = 0;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    m_Text = "#repack_tent";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionRepackTent::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 83 of file ActionRepackTent.c.
  {
    if (!player.IsPlacingLocal())
      return true;
    return false;
  }
ActionConditionContinue()
override bool ActionRepackTent::ActionConditionContinue (ActionData action_data) inline private
Definition at line 73 of file ActionRepackTent.c.
  {
    return true;
  }
CreateConditionComponents()
override void ActionRepackTent::CreateConditionComponents () inline private
Definition at line 57 of file ActionRepackTent.c.
  {
    m_ConditionItem = new CCINone;
    m_ConditionTarget = new CCTNone;
  }
References m_ConditionItem, and m_ConditionTarget.
GetAdminLogMessage()
override string ActionRepackTent::GetAdminLogMessage (ActionData action_data) inline private
Definition at line 187 of file ActionRepackTent.c.
  {
    return " re-packed " + action_data.m_Target.GetObject().GetDisplayName() + " with Hands ";
  }
HasAlternativeInterrupt()
override bool ActionRepackTent::HasAlternativeInterrupt () inline private
Definition at line 78 of file ActionRepackTent.c.
  {
    return true;
  }
HasProgress()
override bool ActionRepackTent::HasProgress () inline private
Definition at line 68 of file ActionRepackTent.c.
  {
    return true;
  }
HasTarget()
override bool ActionRepackTent::HasTarget () inline private
Definition at line 63 of file ActionRepackTent.c.
  {
    return false;
  }
OnEndAnimationLoop()
override void ActionRepackTent::OnEndAnimationLoop (ActionData action_data) inline private
Definition at line 178 of file ActionRepackTent.c.
  {
    if (!GetGame().IsMultiplayer() || GetGame().IsServer())
    {
      Param1<bool> play = new Param1<bool>(false);
      GetGame().RPCSingleParam(action_data.m_MainItem, SoundTypeTent.REPACK, play, true);
    }
  }
References GetGame().
OnEndServer()
override void ActionRepackTent::OnEndServer (ActionData action_data) inline private
Definition at line 113 of file ActionRepackTent.c.
  {
    if (m_IsFinished)
    {
      if (action_data.m_MainItem.IsInherited(TentBase))
      {
        RepackLambda lambda_back_pack = new RepackLambda(action_data.m_MainItem, "LargeTentBackPack", action_data.m_Player);
        action_data.m_Player.ServerReplaceItemElsewhereWithNewInHands(lambda_back_pack);
      }
      if (action_data.m_MainItem.IsInherited(Clothing))
      {
        RepackLambda lambda_tent = new RepackLambda(action_data.m_MainItem, "LargeTent", action_data.m_Player);
        action_data.m_Player.ServerReplaceItemElsewhereWithNewInHands(lambda_tent);
      }
    }
    else
    {
      if (GetGame().IsMultiplayer())
      {
        if (action_data.m_MainItem)
          action_data.m_Player.ServerTakeEntityToHands(action_data.m_MainItem);
      }
      else
      {
        if (action_data.m_MainItem)
          action_data.m_Player.LocalTakeEntityToHands(action_data.m_MainItem);
      }
    }
  }
References GetGame(), and m_IsFinished.
OnFinishProgressServer()
override void ActionRepackTent::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 105 of file ActionRepackTent.c.
  {
    Param1<bool> play = new Param1<bool>(false);
    GetGame().RPCSingleParam(action_data.m_MainItem, SoundTypeTent.REPACK, play, true);
    m_IsFinished = true;
  }
References GetGame(), and m_IsFinished.
OnStartAnimationLoopClient()
override void ActionRepackTent::OnStartAnimationLoopClient (ActionData action_data) inline private
Definition at line 156 of file ActionRepackTent.c.
  {
    if (action_data.m_Player.GetItemInHands())
      ActionRepackTentCB.Cast(action_data.m_Callback).DropDuringRepacking();
  }
References ActionRepackTentCB::DropDuringRepacking().
OnStartAnimationLoopServer()
override void ActionRepackTent::OnStartAnimationLoopServer (ActionData action_data) inline private
Definition at line 162 of file ActionRepackTent.c.
  {
    Param1<bool> play = new Param1<bool>(false);
    if (!GetGame().IsMultiplayer())
    {
      if (action_data.m_Player.GetItemInHands())
        ActionRepackTentCB.Cast(action_data.m_Callback).DropDuringRepacking();
    }
    if (action_data.m_Player.GetItemInHands())
    {
      play = new Param1<bool>(true);
      GetGame().RPCSingleParam(action_data.m_MainItem, SoundTypeTent.REPACK, play, true);
    }
  }
References ActionRepackTentCB::DropDuringRepacking(), and GetGame().
OnStartServer()
override void ActionRepackTent::OnStartServer (ActionData action_data) inline private
Definition at line 99 of file ActionRepackTent.c.
  {
    m_RepackedEntity = null;
    m_IsFinished = false;
  }
References m_IsFinished, and m_RepackedEntity.
SetupAction()
override bool ActionRepackTent::SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 90 of file ActionRepackTent.c.
  {
    SetupAnimation(item);
    if (super.SetupAction(player, target, item, action_data, extra_data))
      return true;
    return false;
  }
References SetupAnimation().
SetupAnimation()
void ActionRepackTent::SetupAnimation (ItemBase item) inline private
Definition at line 144 of file ActionRepackTent.c.
  {
    if (item.IsHeavyBehaviour())
      m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_HEAVY;
    else if (item.IsOneHandedBehaviour())
      m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_1HD;
    else if (item.IsTwoHandedBehaviour())
      m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_2HD;
    else
      Print("Error: check " + item + " behaviour");
  }
References AnimatedActionBase::m_CommandUID, and Print().
Referenced by SetupAction().
Member Data Documentation
m_IsFinished
bool ActionRepackTent::m_IsFinished private
Definition at line 45 of file ActionRepackTent.c.
Referenced by OnEndServer(), OnFinishProgressServer(), and OnStartServer().
m_RepackedEntity
EntityAI ActionRepackTent::m_RepackedEntity private
Definition at line 44 of file ActionRepackTent.c.
Referenced by OnStartServer().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Interact/ActionRepackTent.c