DayZ: FatigueMdfr Class Reference
FatigueMdfr Class Reference
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override void OnActivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
float m_Time
float m_NextEvent
Static Private Attributes
static const float FATIGUE_EVENT_INTERVAL_MIN = 5
static const float FATIGUE_EVENT_INTERVAL_MAX = 12
static const float STAMINA_RECOVERY_MULTIPLIER = 0.33
static const float STAMINA_DEPLETION_MULTIPLIER = 1.33
Detailed Description
Definition at line 1 of file Fatigue.c.
Member Function Documentation
ActivateCondition()
override bool FatigueMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 19 of file Fatigue.c.
  {
    return (player.GetModifiersManager().IsModifierActive(eModifiers.MDF_WOUND_INFECTION1) || player.GetModifiersManager().IsModifierActive(eModifiers.MDF_POISONING) || player.GetModifiersManager().IsModifierActive(eModifiers.MDF_WOUND_INFECTION2));
  }
Referenced by DeactivateCondition().
DeactivateCondition()
override bool FatigueMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 49 of file Fatigue.c.
  {
    return !ActivateCondition(player);
  }
References ActivateCondition().
Init()
override void FatigueMdfr::Init () inline private
Definition at line 11 of file Fatigue.c.
  {
    m_TrackActivatedTime = false;
    m_ID = eModifiers.MDF_FATIGUE;
    m_TickIntervalInactive = DEFAULT_TICK_TIME_INACTIVE_LONG;
    m_TickIntervalActive = DEFAULT_TICK_TIME_ACTIVE;
  }
References DEFAULT_TICK_TIME_ACTIVE, DEFAULT_TICK_TIME_INACTIVE_LONG, m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void FatigueMdfr::OnActivate (PlayerBase player) inline private
Definition at line 24 of file Fatigue.c.
  {
    if (player.m_NotifiersManager)
      player.m_NotifiersManager.ActivateByType(eNotifiers.NTF_FEVERISH);
    player.GetStaminaHandler().ActivateRecoveryModifier(EStaminaMultiplierTypes.FATIGUE);
    player.GetStaminaHandler().ActivateDepletionModifier(EStaminaMultiplierTypes.FATIGUE);
  }
OnDeactivate()
override void FatigueMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 41 of file Fatigue.c.
  {
    //player.GetStaminaHandler().SetDepletionMultiplier(1);
    player.GetStaminaHandler().DeactivateRecoveryModifier(EStaminaMultiplierTypes.FATIGUE);
    player.GetStaminaHandler().DeactivateDepletionModifier(EStaminaMultiplierTypes.FATIGUE);
  }
OnReconnect()
override void FatigueMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 35 of file Fatigue.c.
  {
    this.OnActivate(player);
  }
References OnActivate().
OnTick()
override void FatigueMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 54 of file Fatigue.c.
  {
  }
Member Data Documentation
FATIGUE_EVENT_INTERVAL_MAX
const float FatigueMdfr::FATIGUE_EVENT_INTERVAL_MAX = 12 static private
Definition at line 7 of file Fatigue.c.
FATIGUE_EVENT_INTERVAL_MIN
const float FatigueMdfr::FATIGUE_EVENT_INTERVAL_MIN = 5 static private
Definition at line 6 of file Fatigue.c.
m_NextEvent
float FatigueMdfr::m_NextEvent private
Definition at line 4 of file Fatigue.c.
m_Time
float FatigueMdfr::m_Time private
Definition at line 3 of file Fatigue.c.
STAMINA_DEPLETION_MULTIPLIER
const float FatigueMdfr::STAMINA_DEPLETION_MULTIPLIER = 1.33 static private
Definition at line 9 of file Fatigue.c.
Referenced by StaminaHandler::Init().
STAMINA_RECOVERY_MULTIPLIER
const float FatigueMdfr::STAMINA_RECOVERY_MULTIPLIER = 0.33 static private
Definition at line 8 of file Fatigue.c.
Referenced by StaminaHandler::Init().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/PlayerModifiers/Modifiers/conditions/Fatigue.c