DayZ: CAContinuousMineWood Class Reference
CAContinuousMineWood Class Reference
Protected Member Functions
void CAContinuousMineWood (float time_between_drops)
override void Setup (ActionData action_data)
override int Execute (ActionData action_data)
override float GetProgress ()
bool GetMiningData (ActionData action_data)
void CreatePrimaryItems (ActionData action_data)
void CreateSecondaryItems (ActionData action_data, string material_secondary="", int quantity_secondary=-1)
void DamagePlayersHands (PlayerBase player)
Protected Attributes
float m_TimeElpased
float m_AdjustedTimeBetweenMaterialDrops
float m_CycleTimeOverride
float m_TimeBetweenMaterialDrops
float m_DamageToMiningItemEachDrop
float m_AdjustedDamageToMiningItemEachDrop
int m_AmountOfDrops
int m_CurrentAssumedDrops
ref map< string, int > m_MaterialAndQuantityMap
float m_TimeToComplete
ref Param1< float > m_SpentUnits
bool m_DataLoaded = false
const int MINEDITEM_MAX = 5
ItemBase m_MinedItem [MINEDITEM_MAX]
ItemBase m_SecondaryItem
Detailed Description
Definition at line 1 of file CAContinuousMineWood.c.
Constructor & Destructor Documentation
CAContinuousMineWood()
void CAContinuousMineWood::CAContinuousMineWood (float time_between_drops) inline protected
Definition at line 19 of file CAContinuousMineWood.c.
  {
    m_TimeBetweenMaterialDrops = time_between_drops;
    m_CycleTimeOverride = -1.0;
  }
References m_CycleTimeOverride, and m_TimeBetweenMaterialDrops.
Member Function Documentation
CreatePrimaryItems()
void CAContinuousMineWood::CreatePrimaryItems (ActionData action_data) inline protected
Definition at line 134 of file CAContinuousMineWood.c.
  {
    string material;
    int increment;
    for (int i = 0; i < m_MaterialAndQuantityMap.Count(); i++)
    {
      material = m_MaterialAndQuantityMap.GetKey(i);
      if (material != "")
      {
        increment = m_MaterialAndQuantityMap.GetElement(i);
        if (!m_MinedItem[i])
        {
          m_MinedItem[i] = ItemBase.Cast(GetGame().CreateObjectEx(material, action_data.m_Player.GetPosition(), ECE_PLACE_ON_SURFACE));
          m_MinedItem[i].SetQuantity(increment);
        }
        else if (m_MinedItem[i].HasQuantity())
        {
          if (m_MinedItem[i].IsFullQuantity())
          {
            int stack_max = m_MinedItem[i].GetQuantityMax();
            increment -= stack_max - m_MinedItem[i].GetQuantity();
            if (increment >= 1.0)
            {
              m_MinedItem[i] = ItemBase.Cast(GetGame().CreateObjectEx(material, action_data.m_Player.GetPosition(), ECE_PLACE_ON_SURFACE));
              m_MinedItem[i].SetQuantity(increment, false);
            }
          }
          else
            m_MinedItem[i].AddQuantity(increment, false);
        }
        else
          m_MinedItem[i] = ItemBase.Cast(GetGame().CreateObjectEx(material, action_data.m_Player.GetPosition(), ECE_PLACE_ON_SURFACE));
      }
    }
  }
References ECE_PLACE_ON_SURFACE, GetGame(), HasQuantity(), IsFullQuantity(), m_MaterialAndQuantityMap, and m_MinedItem.
Referenced by Execute().
CreateSecondaryItems()
void CAContinuousMineWood::CreateSecondaryItems (ActionData action_data, string material_secondary = "", int quantity_secondary = -1) inline protected
Definition at line 173 of file CAContinuousMineWood.c.
  {
    if (material_secondary == "" || quantity_secondary <= 0)
      return;
    m_SecondaryItem = ItemBase.Cast(GetGame().CreateObjectEx(material_secondary, action_data.m_Player.GetPosition(), ECE_PLACE_ON_SURFACE));
    if (!m_SecondaryItem.HasQuantity())
    {
      CreateSecondaryItems(action_data, material_secondary, quantity_secondary - 1);
      return;
    }
    int increment = quantity_secondary;
    int stack_max = m_SecondaryItem.GetQuantityMax();
    int stacks_amount;
    stacks_amount = Math.Ceil(increment / stack_max);
    for (int i = 0; i < stacks_amount; i++)
    {
      if (increment > stack_max)
      {
        m_SecondaryItem.SetQuantity(stack_max);
        increment -= stack_max;
        m_SecondaryItem = ItemBase.Cast(GetGame().CreateObjectEx(material_secondary, action_data.m_Player.GetPosition(), ECE_PLACE_ON_SURFACE));
      }
      else
        m_SecondaryItem.SetQuantity(increment);
    }
  }
References Math::Ceil(), CreateSecondaryItems(), ECE_PLACE_ON_SURFACE, GetGame(), and m_SecondaryItem.
Referenced by CreateSecondaryItems(), and Execute().
DamagePlayersHands()
void CAContinuousMineWood::DamagePlayersHands (PlayerBase player) inline protected
Definition at line 204 of file CAContinuousMineWood.c.
  {
    ItemBase gloves = ItemBase.Cast(player.FindAttachmentBySlotName("Gloves"));
    if (gloves && !gloves.IsDamageDestroyed())
      gloves.DecreaseHealth("", "", m_AdjustedDamageToMiningItemEachDrop);
    else
    {
      int rand = Math.RandomIntInclusive(0, 9);
      if (rand == 0)
      {
        rand = Math.RandomIntInclusive(0, 1);
        if (rand == 0 && !player.GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("LeftForeArmRoll"))
          player.GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("RightForeArmRoll");
        else if (rand == 1 && !player.GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("RightForeArmRoll"))
          player.GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("LeftForeArmRoll");
      }
    }
  }
References m_AdjustedDamageToMiningItemEachDrop, and Math::RandomIntInclusive().
Referenced by Execute().
Execute()
override int CAContinuousMineWood::Execute (ActionData action_data) inline protected
Definition at line 45 of file CAContinuousMineWood.c.
  {
    Object targetObject;
    Class.CastTo(targetObject, action_data.m_Target.GetObject());
    if (!action_data.m_Player || !m_DataLoaded)
      return UA_ERROR;
    if ((action_data.m_MainItem && action_data.m_MainItem.IsDamageDestroyed()) || targetObject.IsDamageDestroyed())
      return UA_FINISHED;
    else
    {
      if (m_TimeElpased < m_AdjustedTimeBetweenMaterialDrops)
        m_TimeElpased += action_data.m_Player.GetDeltaT();
      else
      {
        if (GetGame().IsServer())
        {
          float damage = 0;
          if (m_AmountOfDrops > 0)
            damage = (1 / m_AmountOfDrops) * 100;
          targetObject.DecreaseHealth("", "", damage, targetObject.CanBeAutoDeleted());
          CreatePrimaryItems(action_data);
          if (action_data.m_MainItem)
            action_data.m_MainItem.DecreaseHealth("", "", m_AdjustedDamageToMiningItemEachDrop);
          else
            DamagePlayersHands(action_data.m_Player);
          if (targetObject.IsDamageDestroyed()) //client does not know the target is destroyed yet, happens on the next Execute!
          {
            if (m_SpentUnits)
            {
              m_SpentUnits.param1 = m_TimeElpased;
              SetACData(m_SpentUnits);
            }
            if (WoodBase.Cast(targetObject))
            {
              WoodBase target_woodbase = WoodBase.Cast(targetObject);
              if (target_woodbase.GetSecondaryOutput() != "")
                CreateSecondaryItems(action_data, target_woodbase.GetSecondaryOutput(), target_woodbase.GetSecondaryDropsAmount());
            }
            if (action_data.m_MainItem)
              targetObject.OnTreeCutDown(action_data.m_MainItem);
            else
              targetObject.OnTreeCutDown(action_data.m_Player);
          }
        }
        m_CurrentAssumedDrops++;
        if (m_AmountOfDrops > 0 && m_CurrentAssumedDrops >= m_AmountOfDrops) //assumed end, client does not know the target is destroyed yet
        {
          OnCompletePogress(action_data);
          return UA_FINISHED;
        }
        m_TimeElpased = m_TimeElpased - m_AdjustedTimeBetweenMaterialDrops;
        OnCompletePogress(action_data);
      }
      return UA_PROCESSING;
    }
  }
References Class::CastTo(), CreatePrimaryItems(), CreateSecondaryItems(), DamagePlayersHands(), GetGame(), m_AdjustedDamageToMiningItemEachDrop, m_AdjustedTimeBetweenMaterialDrops, m_AmountOfDrops, m_CurrentAssumedDrops, m_DataLoaded, m_SpentUnits, m_TimeElpased, CAContinuousBase::OnCompletePogress(), CABase::SetACData(), UA_ERROR, UA_FINISHED, UA_PROCESSING, and WoodBase().
GetMiningData()
bool CAContinuousMineWood::GetMiningData (ActionData action_data) inline protected
Definition at line 117 of file CAContinuousMineWood.c.
  {
    MineActionData adata = MineActionData.Cast(action_data);
    WoodBase ntarget;
    if (Class.CastTo(ntarget, action_data.m_Target.GetObject()))
    {
      m_AmountOfDrops = ntarget.GetAmountOfDropsEx(action_data.m_MainItem, adata.m_HarvestType);
      m_CurrentAssumedDrops = 0;
      m_CycleTimeOverride = ntarget.GetCycleTimeOverride(); //TODO
      ntarget.GetMaterialAndQuantityMapEx(action_data.m_MainItem, m_MaterialAndQuantityMap, adata.m_HarvestType);
      m_DamageToMiningItemEachDrop = ntarget.GetDamageToMiningItemEachDropEx(action_data.m_MainItem, adata.m_HarvestType);
      m_AdjustedDamageToMiningItemEachDrop = action_data.m_Player.GetSoftSkillsManager().SubtractSpecialtyBonus(m_DamageToMiningItemEachDrop, m_Action.GetSpecialtyWeight(), true);
      return true;
    }
    return false;
  }
References Class::CastTo(), CABase::m_Action, m_AdjustedDamageToMiningItemEachDrop, m_AmountOfDrops, m_CurrentAssumedDrops, m_CycleTimeOverride, m_DamageToMiningItemEachDrop, m_MaterialAndQuantityMap, and WoodBase().
Referenced by Setup().
GetProgress()
override float CAContinuousMineWood::GetProgress () inline protected
Definition at line 110 of file CAContinuousMineWood.c.
  {
    return m_TimeElpased / m_AdjustedTimeBetweenMaterialDrops;
  }
References m_AdjustedTimeBetweenMaterialDrops, and m_TimeElpased.
Setup()
override void CAContinuousMineWood::Setup (ActionData action_data) inline protected
Definition at line 25 of file CAContinuousMineWood.c.
  {
    m_TimeElpased = 0;
    if (!m_SpentUnits)
      m_SpentUnits = new Param1<float>(0);
    else
      m_SpentUnits.param1 = 0;
    m_MaterialAndQuantityMap = new map<string, int>;
    m_DataLoaded = GetMiningData(action_data);
    if (m_CycleTimeOverride > -1.0)
    {
      m_TimeBetweenMaterialDrops = m_CycleTimeOverride;
      if (!action_data.m_MainItem) //hand action
        m_TimeBetweenMaterialDrops = m_TimeBetweenMaterialDrops * 3;
    }
    m_AdjustedTimeBetweenMaterialDrops = action_data.m_Player.GetSoftSkillsManager().SubtractSpecialtyBonus(m_TimeBetweenMaterialDrops, m_Action.GetSpecialtyWeight(), true);
    m_TimeToComplete = m_AmountOfDrops * m_AdjustedTimeBetweenMaterialDrops;
  }
References GetMiningData(), CABase::m_Action, m_AdjustedTimeBetweenMaterialDrops, m_AmountOfDrops, m_CycleTimeOverride, m_DataLoaded, m_MaterialAndQuantityMap, m_SpentUnits, m_TimeBetweenMaterialDrops, m_TimeElpased, and m_TimeToComplete.
Member Data Documentation
m_AdjustedDamageToMiningItemEachDrop
float CAContinuousMineWood::m_AdjustedDamageToMiningItemEachDrop protected
Definition at line 8 of file CAContinuousMineWood.c.
Referenced by DamagePlayersHands(), Execute(), CAContinuousMineRock::GetMiningData(), and GetMiningData().
m_AdjustedTimeBetweenMaterialDrops
float CAContinuousMineWood::m_AdjustedTimeBetweenMaterialDrops protected
Definition at line 4 of file CAContinuousMineWood.c.
Referenced by Execute(), GetProgress(), and Setup().
m_AmountOfDrops
int CAContinuousMineWood::m_AmountOfDrops protected
Definition at line 9 of file CAContinuousMineWood.c.
Referenced by Execute(), CAContinuousMineRock::GetMiningData(), GetMiningData(), and Setup().
m_CurrentAssumedDrops
int CAContinuousMineWood::m_CurrentAssumedDrops protected
Definition at line 10 of file CAContinuousMineWood.c.
Referenced by Execute(), and GetMiningData().
m_CycleTimeOverride
float CAContinuousMineWood::m_CycleTimeOverride protected
Definition at line 5 of file CAContinuousMineWood.c.
Referenced by CAContinuousMineWood(), GetMiningData(), and Setup().
m_DamageToMiningItemEachDrop
float CAContinuousMineWood::m_DamageToMiningItemEachDrop protected
Definition at line 7 of file CAContinuousMineWood.c.
Referenced by CAContinuousMineRock::GetMiningData(), and GetMiningData().
m_DataLoaded
bool CAContinuousMineWood::m_DataLoaded = false protected
Definition at line 14 of file CAContinuousMineWood.c.
Referenced by Execute(), and Setup().
m_MaterialAndQuantityMap
ref map<string, int> CAContinuousMineWood::m_MaterialAndQuantityMap protected
Definition at line 11 of file CAContinuousMineWood.c.
Referenced by CreatePrimaryItems(), CAContinuousMineRock::GetMiningData(), GetMiningData(), and Setup().
m_MinedItem
ItemBase CAContinuousMineWood::m_MinedItem[MINEDITEM_MAX] protected
Definition at line 16 of file CAContinuousMineWood.c.
Referenced by CreatePrimaryItems().
m_SecondaryItem
ItemBase CAContinuousMineWood::m_SecondaryItem protected
Definition at line 17 of file CAContinuousMineWood.c.
Referenced by CreateSecondaryItems().
m_SpentUnits
ref Param1<float> CAContinuousMineWood::m_SpentUnits protected
Definition at line 13 of file CAContinuousMineWood.c.
Referenced by Execute(), and Setup().
m_TimeBetweenMaterialDrops
float CAContinuousMineWood::m_TimeBetweenMaterialDrops protected
Definition at line 6 of file CAContinuousMineWood.c.
Referenced by CAContinuousMineRock::CAContinuousMineRock(), CAContinuousMineWood(), and Setup().
m_TimeElpased
float CAContinuousMineWood::m_TimeElpased protected
Definition at line 3 of file CAContinuousMineWood.c.
Referenced by Execute(), GetProgress(), and Setup().
m_TimeToComplete
float CAContinuousMineWood::m_TimeToComplete protected
Definition at line 12 of file CAContinuousMineWood.c.
Referenced by Setup().
MINEDITEM_MAX
const int CAContinuousMineWood::MINEDITEM_MAX = 5 protected
Definition at line 15 of file CAContinuousMineWood.c.
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousMineWood.c