DayZ: Sedan_02 Class Reference
Sedan_02 Class Reference
Private Member Functions
override void OnDebugSpawn ()
Detailed Description
Definition at line 427 of file Sedan_02.c.
Member Function Documentation
OnDebugSpawn()
override void Sedan_02::OnDebugSpawn () inline private
Definition at line 429 of file Sedan_02.c.
  {
    SpawnUniversalParts();
    SpawnAdditionalItems();
    FillUpCarFluids();
    GetInventory().CreateInInventory("Sedan_02_Wheel");
    GetInventory().CreateInInventory("Sedan_02_Wheel");
    GetInventory().CreateInInventory("Sedan_02_Wheel");
    GetInventory().CreateInInventory("Sedan_02_Wheel");
    GetInventory().CreateInInventory("Sedan_02_Door_1_1_Grey");
    GetInventory().CreateInInventory("Sedan_02_Door_1_2_Grey");
    GetInventory().CreateInInventory("Sedan_02_Door_2_1_Grey");
    GetInventory().CreateInInventory("Sedan_02_Door_2_2_Grey");
    GetInventory().CreateInInventory("Sedan_02_Hood_Grey");
    GetInventory().CreateInInventory("Sedan_02_Trunk_Grey");
    //-----IN CAR CARGO
    GetInventory().CreateInInventory("Sedan_02_Wheel");
    GetInventory().CreateInInventory("Sedan_02_Wheel");
  }
References FillUpCarFluids(), SpawnAdditionalItems(), and SpawnUniversalParts().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/Vehicles/InheritedCars/Sedan_02.c