DayZ: TriggerEffectManager Class Reference
TriggerEffectManager Class Reference
Private Member Functions
void TriggerEffectManager ()
void RegisterTriggerType (EffectTrigger effectTrigger)
void OnPlayerEnter (notnull PlayerBase player, notnull EffectTrigger trigger)
void OnPlayerInsideEffectAreaEnter (PlayerBase player)
void OnPlayerInsideEffectAreaExit (PlayerBase player)
void OnPlayerExit (notnull PlayerBase player, notnull EffectTrigger trigger)
bool IsPlayerInTriggerType (notnull PlayerBase player, notnull EffectTrigger trigger)
Static Private Member Functions
static void DestroyInstance ()
static TriggerEffectManager GetInstance ()
Private Attributes
ref map< string, ref map< PlayerBase, int > > m_PlayerInsiderMap
Static Private Attributes
static ref TriggerEffectManager m_This
Detailed Description
Definition at line 3 of file TriggerEffectManager.c.
Constructor & Destructor Documentation
TriggerEffectManager()
void TriggerEffectManager::TriggerEffectManager () inline private
Definition at line 10 of file TriggerEffectManager.c.
  {
    m_PlayerInsiderMap = new map<string, ref map<PlayerBase, int>>;
  }
References m_PlayerInsiderMap.
Referenced by GetInstance().
Member Function Documentation
DestroyInstance()
static void TriggerEffectManager::DestroyInstance () inline static private
Definition at line 15 of file TriggerEffectManager.c.
  {
    m_This = null;
  }
References m_This.
Referenced by MissionBaseWorld::~MissionBase().
GetInstance()
static TriggerEffectManager TriggerEffectManager::GetInstance () inline static private
Definition at line 21 of file TriggerEffectManager.c.
  {
    if (!m_This)
      m_This = new TriggerEffectManager();
    return m_This;
  }
References m_This, and TriggerEffectManager().
Referenced by ContaminatedTrigger_Dynamic(), and EffectTrigger::EffectTrigger().
IsPlayerInTriggerType()
bool TriggerEffectManager::IsPlayerInTriggerType (notnull PlayerBase player, notnull EffectTrigger trigger) inline private
Definition at line 112 of file TriggerEffectManager.c.
  {
    map<PlayerBase, int> playerMap;
    if (m_PlayerInsiderMap.Find(trigger.GetType(), playerMap))
      return playerMap != null && playerMap.Contains(player);
    return false;
  }
References m_PlayerInsiderMap.
Referenced by EffectTrigger::SetupClientEffects().
OnPlayerEnter()
void TriggerEffectManager::OnPlayerEnter (notnull PlayerBase player, notnull EffectTrigger trigger) inline private
Definition at line 41 of file TriggerEffectManager.c.
  {
    string trigger_type = trigger.GetType();
    map<PlayerBase, int> playerMap;
    if (m_PlayerInsiderMap.Find(trigger_type, playerMap))
    {
      if (playerMap)
      {
        if (playerMap.Contains(player))
        {
          int newTriggerCount = playerMap.Get(player) + 1;
          playerMap.Set(player, newTriggerCount);
          //Debug.Log("We increase the amount of triggers a player is in");
        }
        else
        {
          // First time this player enters this type of trigger, we set the trigger count to 1
          playerMap.Insert(player, 1);
          if (trigger.GetEffectArea())
            trigger.GetEffectArea().OnPlayerEnterServer(player, trigger);
          //Debug.Log("We insert a player");
        }
        //m_PlayerInsiderMap.Set( trigger_type, playerMap );
      }
      else
      {
        // We didn't have the map yet, we create it and register this player in it
        playerMap = new map<PlayerBase, int>;
        playerMap.Insert(player, 1);
        if (trigger.GetEffectArea())
          trigger.GetEffectArea().OnPlayerEnterServer(player, trigger);
        m_PlayerInsiderMap.Insert(trigger_type, playerMap);
      }
    }
  }
References m_PlayerInsiderMap.
Referenced by EffectTrigger::OnEnterClientEvent(), and EffectTrigger::OnEnterServerEvent().
OnPlayerExit()
void TriggerEffectManager::OnPlayerExit (notnull PlayerBase player, notnull EffectTrigger trigger) inline private
Definition at line 83 of file TriggerEffectManager.c.
  {
    string trigger_type = trigger.GetType();
    map<PlayerBase, int> playerMap;
    if (m_PlayerInsiderMap.Find(trigger_type, playerMap) && playerMap)
    {
      if (playerMap.Contains(player))
      {
        if (playerMap.Get(player) > 1)
        {
          //Debug.Log("We reduced the amount of triggers the player is in");
          playerMap.Set(player, playerMap.Get(player) - 1);
        }
        else
        {
          // The player left the last trigger of this type they were in
          playerMap.Remove(player);
          if (trigger.GetEffectArea())
            trigger.GetEffectArea().OnPlayerExitServer(player, trigger);
          player.RemoveCurrentEffectTrigger();
          //Debug.Log("We removed this player from this trigger type");
        }
      }
      //m_PlayerInsiderMap.Set( trigger_type, playerMap );
    }
  }
References m_PlayerInsiderMap.
Referenced by EffectTrigger::OnLeaveClientEvent(), and EffectTrigger::OnLeaveServerEvent().
OnPlayerInsideEffectAreaEnter()
void TriggerEffectManager::OnPlayerInsideEffectAreaEnter (PlayerBase player) private
OnPlayerInsideEffectAreaExit()
void TriggerEffectManager::OnPlayerInsideEffectAreaExit (PlayerBase player) private
RegisterTriggerType()
void TriggerEffectManager::RegisterTriggerType (EffectTrigger effectTrigger) inline private
Definition at line 29 of file TriggerEffectManager.c.
  {
    if (!m_PlayerInsiderMap.Contains(effectTrigger.GetType()))
    {
      map<PlayerBase, int> playerMap = new map<PlayerBase, int>;
      m_PlayerInsiderMap.Insert(effectTrigger.GetType(), playerMap);
      //Debug.Log( "We have : " + m_PlayerInsiderMap.Count() + " triggers");
    }
  }
References m_PlayerInsiderMap.
Referenced by EffectTrigger::EffectTrigger().
Member Data Documentation
m_PlayerInsiderMap
ref map<string, ref map<PlayerBase, int> > TriggerEffectManager::m_PlayerInsiderMap private
Definition at line 8 of file TriggerEffectManager.c.
Referenced by IsPlayerInTriggerType(), OnPlayerEnter(), OnPlayerExit(), RegisterTriggerType(), and TriggerEffectManager().
m_This
ref TriggerEffectManager TriggerEffectManager::m_This static private
Definition at line 5 of file TriggerEffectManager.c.
Referenced by DestroyInstance(), and GetInstance().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ScriptedEntities/Triggers/TriggerEffectManager.c