DayZ: BloodNotfr Class Reference
BloodNotfr Class Reference
Protected Member Functions
void BloodNotfr (NotifiersManager manager)
override int GetNotifierType ()
override void DisplayTendency (float delta)
override float GetObservedValue ()
Protected Attributes
const float DEC_TRESHOLD_LOW = 0
const float DEC_TRESHOLD_MED = -12
const float DEC_TRESHOLD_HIGH = -22
const float INC_TRESHOLD_LOW = 0
const float INC_TRESHOLD_MED = 3
const float INC_TRESHOLD_HIGH = 6
Additional Inherited Members
Private Member Functions inherited from NotifierBase
int CalculateTendency (float delta, float inctresholdlow, float inctresholdmed, float inctresholdhigh, float dectresholdlow, float dectresholdmed, float dectresholdhigh)
eBadgeLevel DetermineBadgeLevel (float value, float lvl_1, float lvl_2, float lvl_3)
void DisplayBadge ()
void HideBadge ()
float GetObservedValue ()
Detailed Description
Definition at line 1 of file BloodNotfr.c.
Constructor & Destructor Documentation
BloodNotfr()
void BloodNotfr::BloodNotfr (NotifiersManager manager) inline protected
Definition at line 10 of file BloodNotfr.c.
  {
  }
Member Function Documentation
DisplayTendency()
override void BloodNotfr::DisplayTendency (float delta) inline protected
Definition at line 19 of file BloodNotfr.c.
  {
    int tendency = CalculateTendency(delta, INC_TRESHOLD_LOW, INC_TRESHOLD_MED, INC_TRESHOLD_HIGH, DEC_TRESHOLD_LOW, DEC_TRESHOLD_MED, DEC_TRESHOLD_HIGH);
    //DSLevels level = DetermineLevel( GetObservedValue(), PlayerConstants.THRESHOLD_BLOOD_WARNING,  PlayerConstants.THRESHOLD_BLOOD_CRITICAL, PlayerConstants.THRESHOLD_BLOOD_BLINKING, PlayerConstants.THRESHOLD_BLOOD_EXTRA );
    DisplayElementTendency dis_elm = DisplayElementTendency.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_TDCY_BLOOD));
    EStatLevels blood_level = m_Player.GetStatLevelBlood();
    if (dis_elm)
    {
      dis_elm.SetTendency(tendency);
      dis_elm.SetSeriousnessLevel(blood_level);
    }
  }
References NotifierBase::CalculateTendency(), DEC_TRESHOLD_HIGH, DEC_TRESHOLD_LOW, DEC_TRESHOLD_MED, GetElement(), NotifierBase::GetVirtualHud(), INC_TRESHOLD_HIGH, INC_TRESHOLD_LOW, INC_TRESHOLD_MED, and NotifierBase::m_Player.
GetNotifierType()
override int BloodNotfr::GetNotifierType () inline protected
Definition at line 14 of file BloodNotfr.c.
  {
    return eNotifiers.NTF_BLOOD;
  }
GetObservedValue()
override float BloodNotfr::GetObservedValue () inline protected
Definition at line 37 of file BloodNotfr.c.
  {
    float blood = m_Player.GetHealth("GlobalHealth", "Blood");
    return blood;
  }
References NotifierBase::m_Player.
Member Data Documentation
DEC_TRESHOLD_HIGH
const float BloodNotfr::DEC_TRESHOLD_HIGH = -22 protected
Definition at line 5 of file BloodNotfr.c.
Referenced by DisplayTendency().
DEC_TRESHOLD_LOW
const float BloodNotfr::DEC_TRESHOLD_LOW = 0 protected
Definition at line 3 of file BloodNotfr.c.
Referenced by DisplayTendency().
DEC_TRESHOLD_MED
const float BloodNotfr::DEC_TRESHOLD_MED = -12 protected
Definition at line 4 of file BloodNotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_HIGH
const float BloodNotfr::INC_TRESHOLD_HIGH = 6 protected
Definition at line 8 of file BloodNotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_LOW
const float BloodNotfr::INC_TRESHOLD_LOW = 0 protected
Definition at line 6 of file BloodNotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_MED
const float BloodNotfr::INC_TRESHOLD_MED = 3 protected
Definition at line 7 of file BloodNotfr.c.
Referenced by DisplayTendency().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/PlayerNotifiers/Notifiers/BloodNotfr.c