DayZ: ScriptConsoleConfigTab Class Reference
ScriptConsoleConfigTab Class Reference
Protected Member Functions
void ScriptConsoleConfigTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void ~ScriptConsoleConfigTab ()
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
void RenderClassPath ()
override bool OnClick (Widget w, int x, int y, int button)
override void Update (float timeslice)
void Init ()
void DumpParam (string param, string relativePath)
void ChangeConfigFilter ()
void ClearHierarchy ()
void FindInHierarchy (string class_name)
void ExpandHierarchy (int row)
void CollapseHierarchy (int row)
void RenderVariables (int row)
Protected Attributes
ref TStringArray m_BaseConfigClasses = new TStringArray
ref TStringArray m_BaseConfigClassesToggled = new TStringArray
ref map< CheckBoxWidget, int > m_ClassCheckboxes = new map<CheckBoxWidget, int>
EditBoxWidget m_ObjectConfigFilter
EditBoxWidget m_VariableConfigFilter
TextListboxWidget m_ConfigHierarchyTextListbox
TextListboxWidget m_ConfigVariablesTextListbox
ButtonWidget m_SelectedRowCopy
ButtonWidget m_DumpParamButton
TextWidget m_ClassPath
Widget m_WgtClassesConfig
PluginConfigViewer m_ModuleConfigViewer
int m_Row
Static Protected Attributes
static string m_ConfigTextField
static string m_VariableTextField
static ref ConfigParamsEx m_ConfigData
Additional Inherited Members
Private Member Functions inherited from ScriptConsoleTabBase
void ScriptConsoleTabBase (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void Init (int id)
int GetID ()
Widget GetRoot ()
bool IsSelected ()
void Select (bool select, ScriptConsoleTabBase selectedHandler)
void OnSelected ()
void Show (bool show, ScriptConsoleTabBase selectedHandler)
Widget GetButton ()
void Update (float timeslice)
bool OnChange (Widget w, int x, int y, bool finished)
bool OnClick (Widget w, int x, int y, int button)
bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
bool OnKeyDown (Widget w, int x, int y, int key)
bool OnDoubleClick (Widget w, int x, int y, int button)
void OnRPCEx (int rpc_type, ParamsReadContext ctx)
bool OnMouseButtonDown (Widget w, int x, int y, int button)
bool OnKeyPress (Widget w, int x, int y, int key)
void AddItemToClipboard (TextListboxWidget text_listbox_widget)
Private Attributes inherited from ScriptConsoleTabBase
int m_Id
bool m_IsSelected
Widget m_ParentRoot
Widget m_Root
Widget m_Button
ScriptConsole m_ScriptConsole
ScriptConsoleTabBase m_Parent
PluginConfigDebugProfile m_ConfigDebugProfile
PluginConfigDebugProfileFixed m_ConfigDebugProfileFixed
Detailed Description
Definition at line 4 of file ScriptConsoleConfigTab.c.
Constructor & Destructor Documentation
ScriptConsoleConfigTab()
void ScriptConsoleConfigTab::ScriptConsoleConfigTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent = null) inline protected
Definition at line 27 of file ScriptConsoleConfigTab.c.
  {
    m_WgtClassesConfig = root.FindAnyWidget("ClassesPanel");
    m_DumpParamButton = ButtonWidget.Cast(root.FindAnyWidget("DumpParamButton"));
    m_ObjectConfigFilter = EditBoxWidget.Cast(root.FindAnyWidget("ObjectConfigFilter"));
    m_VariableConfigFilter = EditBoxWidget.Cast(root.FindAnyWidget("VariableConfigFilter"));
    m_ConfigHierarchyTextListbox = TextListboxWidget.Cast(root.FindAnyWidget("ConfigHierarchy"));
    m_ConfigVariablesTextListbox = TextListboxWidget.Cast(root.FindAnyWidget("ConfigVariables"));
    m_SelectedRowCopy = ButtonWidget.Cast(root.FindAnyWidget("SelectedRowCopy"));
    m_ClassPath = TextWidget.Cast(root.FindAnyWidget("ClassPath"));
    if (m_ConfigTextField)
      m_ObjectConfigFilter.SetText(m_ConfigTextField);
    if (m_VariableTextField)
      m_VariableConfigFilter.SetText(m_VariableTextField);
    Init();
  }
References Init(), m_ClassPath, m_ConfigHierarchyTextListbox, m_ConfigTextField, m_ConfigVariablesTextListbox, m_DumpParamButton, m_ObjectConfigFilter, m_SelectedRowCopy, m_VariableConfigFilter, m_VariableTextField, and m_WgtClassesConfig.
~ScriptConsoleConfigTab()
void ScriptConsoleConfigTab::~ScriptConsoleConfigTab () inline protected
Definition at line 45 of file ScriptConsoleConfigTab.c.
  {
    m_VariableTextField = m_VariableConfigFilter.GetText();
    foreach (int i: m_ClassCheckboxes)
    {
      Widget w = m_ClassCheckboxes.GetKeyByValue(i);
      w.GetParent().Unlink();
    }
  }
References m_ClassCheckboxes, m_VariableConfigFilter, and m_VariableTextField.
Member Function Documentation
ChangeConfigFilter()
void ScriptConsoleConfigTab::ChangeConfigFilter () inline protected
Definition at line 288 of file ScriptConsoleConfigTab.c.
  {
    m_ConfigTextField = m_ObjectConfigFilter.GetText();
    if (m_ConfigTextField == "")
      ClearHierarchy();
    else
      FindInHierarchy(m_ConfigTextField);
  }
References ClearHierarchy(), FindInHierarchy(), m_ConfigTextField, and m_ObjectConfigFilter.
Referenced by Init(), and OnChange().
ClearHierarchy()
void ScriptConsoleConfigTab::ClearHierarchy () inline protected
Definition at line 298 of file ScriptConsoleConfigTab.c.
  {
    m_ConfigHierarchyTextListbox.ClearItems();
    m_ConfigVariablesTextListbox.ClearItems();
    string config_path = "configfile";
    TStringArray variables = m_ModuleConfigViewer.GetConfigHierarchy(config_path);
    for (int i = 0; i < variables.Count(); i++)
    {
      string variable = variables.Get(i);
      for (int j = 0; j < m_BaseConfigClassesToggled.Count(); j++)
      {
        if (variable == m_BaseConfigClassesToggled.Get(j))
        {
          string new_config_path = (config_path + " " + variable).Trim();
          m_ConfigHierarchyTextListbox.AddItem("+ " + variable, new ConfigParamsEx(false, variable, 0, new_config_path, 0, variable), 0);
        }
      }
    }
  }
References m_BaseConfigClassesToggled, m_ConfigHierarchyTextListbox, m_ConfigVariablesTextListbox, and m_ModuleConfigViewer.
Referenced by ChangeConfigFilter(), Init(), and OnClick().
CollapseHierarchy()
void ScriptConsoleConfigTab::CollapseHierarchy (int row) inline protected
Definition at line 396 of file ScriptConsoleConfigTab.c.
  {
    if (row <= -1 && row >= m_ConfigHierarchyTextListbox.GetNumItems())
      return;
    ConfigParamsEx config_params;
    ConfigParamsEx config_params_next;
    m_ConfigHierarchyTextListbox.GetItemData(row, 0, config_params);
    m_ConfigHierarchyTextListbox.GetItemData(row + 1, 0, config_params_next);
    if (!config_params || !config_params_next)
      return;
    int deep = config_params.param5;
    int deep_next = config_params_next.param5;
    int max_count = m_ConfigHierarchyTextListbox.GetNumItems();
    int remove_lines_count = 0;
    // Print(max_count);
    for (int i = row + 1; i < max_count; i++)
    {
      if (deep < deep_next && i <= max_count)
      {
        remove_lines_count = remove_lines_count + 1;
        m_ConfigHierarchyTextListbox.GetItemData(i, 0, config_params_next);
        deep_next = config_params_next.param5;
      }
    }
    // remove remove_lines_count lines from row
    // remove_lines_count = remove_lines_count - 1;
    for (i = 1; i < remove_lines_count; i++)
    {
      int x = row + 1;
      if (x < max_count)
        m_ConfigHierarchyTextListbox.RemoveRow(x);
    }
    string offset = "";
    for (i = 0; i < deep; i++)
      offset = offset + "  ";
    m_ConfigHierarchyTextListbox.SetItem(row, offset + "+ " + config_params.param2, new ConfigParamsEx(false, config_params.param2, 0, config_params.param4, deep, ""), 0);
    /* //not sure why this is here, but it's causing issues when collapsing items in config viewer, disabling for now
      if (deep == 0)
      {
      ClearHierarchy();
      }
    */
  }
References m_ConfigHierarchyTextListbox, and x.
Referenced by OnClick().
DumpParam()
void ScriptConsoleConfigTab::DumpParam (string param, string relativePath) inline protected
Definition at line 248 of file ScriptConsoleConfigTab.c.
  {
    if (relativePath)
      relativePath = " " + relativePath;
    for (int i = 0; i < m_BaseConfigClassesToggled.Count(); i++)
    {
      string config_path = m_BaseConfigClassesToggled.Get(i);
      int objects_count = GetGame().ConfigGetChildrenCount(config_path);
      for (int j = 0; j < objects_count; j++)
      {
        string child_name;
        GetGame().ConfigGetChildName(config_path, j, child_name);
        //string dispName;
        //GetGame().ConfigGetText( config_path + " " + child_name + " displayName",dispName );
        string value;
        string path = config_path + " " + child_name + relativePath + " " + param;
        if (GetGame().ConfigIsExisting(path))
        {
          GetGame().ConfigGetText(path, value);
          if (value)
            Print(child_name + "," + param + "," + value);
        }
        /*
          int scope = GetGame().ConfigGetInt( config_path + " " + child_name + " scope" );
          {
          if ( scope == 2)
          {
          }
          }*/
      }
    }
  }
References GetGame(), m_BaseConfigClassesToggled, path, and Print().
Referenced by OnClick().
ExpandHierarchy()
void ScriptConsoleConfigTab::ExpandHierarchy (int row) inline protected
Definition at line 359 of file ScriptConsoleConfigTab.c.
  {
    if (row <= -1 && row >= m_ConfigHierarchyTextListbox.GetNumItems())
      return;
    TStringArray variables;
    // get current row data
    ConfigParamsEx config_params;
    m_ConfigHierarchyTextListbox.GetItemData(row, 0, config_params);
    string config_path = config_params.param4;
    int deep = config_params.param5;
    string offset = "";
    for (int i = 0; i < deep; i++)
      offset = offset + "  ";
    // change selected node
    variables = m_ModuleConfigViewer.GetConfigHierarchy(config_path);
    int childrens_count = variables.Count();
    m_ConfigHierarchyTextListbox.SetItem(row, offset + "- " + config_params.param2, new ConfigParamsEx(true, config_params.param2, childrens_count, config_path, deep, config_params.param6), 0);
    offset = offset + "  ";
    // render children
    deep = deep + 1;
    childrens_count = 0;
    for (i = variables.Count() - 1; i >= 0; i--)
    {
      string new_config_path = (config_path + " " + variables.Get(i)).Trim();
      m_ConfigHierarchyTextListbox.AddItem(offset + "+ " + variables.Get(i), new ConfigParamsEx(false, variables.Get(i), childrens_count, new_config_path, deep, config_params.param2), 0, (row + 1));
    }
  }
References m_ConfigHierarchyTextListbox, and m_ModuleConfigViewer.
Referenced by OnClick().
FindInHierarchy()
void ScriptConsoleConfigTab::FindInHierarchy (string class_name) inline protected
Definition at line 320 of file ScriptConsoleConfigTab.c.
  {
    m_ConfigHierarchyTextListbox.ClearItems();
    m_ConfigVariablesTextListbox.ClearItems();
    class_name.ToLower();
    string config_base_path = "configfile";
    string filter_lower = class_name;
    filter_lower.ToLower();
    TStringArray filters = new TStringArray;
    filter_lower.Split(" ", filters);
    for (int i = 0; i < m_BaseConfigClassesToggled.Count(); i++)
    {
      string config_root = m_BaseConfigClassesToggled.Get(i);
      string config_path = config_base_path + " " + config_root;
      TStringArray variables = m_ModuleConfigViewer.GetConfigHierarchy(config_path);
      for (int j = 0; j < variables.Count(); j++)
      {
        string variable = variables.Get(j);
        string variable_lower = variable;
        variable_lower.ToLower();
        for (int k = 0; k < filters.Count(); k++)
        {
          if (variable_lower.Contains(filters.Get(k)))
          {
            string new_config_path = (config_path + " " + variable).Trim();
            m_ConfigHierarchyTextListbox.AddItem("+ " + variable, new ConfigParamsEx(false, variable, 0, new_config_path, 0, config_root), 0);
            break;
          }
        }
      }
    }
  }
References class_name, m_BaseConfigClassesToggled, m_ConfigHierarchyTextListbox, m_ConfigVariablesTextListbox, and m_ModuleConfigViewer.
Referenced by ChangeConfigFilter().
Init()
void ScriptConsoleConfigTab::Init () inline protected
Definition at line 217 of file ScriptConsoleConfigTab.c.
  {
    Debug.GetBaseConfigClasses(m_BaseConfigClasses);
    m_ModuleConfigViewer = PluginConfigViewer.Cast(GetPlugin(PluginConfigViewer));
    int flag1;
    if (m_ConfigDebugProfile)
      flag1 = m_ConfigDebugProfile.GetConfigClassesFlag();
    //Print("------------------------------------------------");
    foreach (string s: m_BaseConfigClasses)
    {
      Widget w = GetGame().GetWorkspace().CreateWidgets("gui/layouts/script_console/config_class_item.layout", m_WgtClassesConfig);
      CheckBoxWidget cbw = CheckBoxWidget.Cast(w.FindAnyWidget("Item"));
      //cbw.SetColor(Colors.RED);
      cbw.SetText(s);
      int indx = m_ClassCheckboxes.Count();
      m_ClassCheckboxes.Insert(cbw, indx);
      //Print("adding "+cbw +" at index:" + indx);
      if (flag1 & (int)Math.Pow(2, indx))
      {
        string base_class_name = m_BaseConfigClasses.Get(indx);
        m_BaseConfigClassesToggled.Insert(base_class_name);
        cbw.SetChecked(true);
      }
    }
    ClearHierarchy();
    ChangeConfigFilter();
  }
References ChangeConfigFilter(), ClearHierarchy(), Debug::GetBaseConfigClasses(), GetGame(), GetPlugin(), m_BaseConfigClasses, m_BaseConfigClassesToggled, m_ClassCheckboxes, ScriptConsoleTabBase::m_ConfigDebugProfile, m_ModuleConfigViewer, m_WgtClassesConfig, and Math::Pow().
Referenced by ScriptConsoleConfigTab().
OnChange()
override bool ScriptConsoleConfigTab::OnChange (Widget w, int x, int y, bool finished) inline protected
Definition at line 56 of file ScriptConsoleConfigTab.c.
  {
    super.OnChange(w, x, y, finished);
    if (w == m_ObjectConfigFilter)
    {
      ChangeConfigFilter();
      return true;
    }
    else if (w == m_VariableConfigFilter)
    {
      RenderVariables(m_Row);
      return true;
    }
    return false;
  }
References ChangeConfigFilter(), m_ObjectConfigFilter, m_Row, m_VariableConfigFilter, RenderVariables(), x, and y.
OnClick()
override bool ScriptConsoleConfigTab::OnClick (Widget w, int x, int y, int button) inline protected
Definition at line 94 of file ScriptConsoleConfigTab.c.
  {
    super.OnClick(w, x, y, button);
    CheckBoxWidget cbw = CheckBoxWidget.Cast(w);
    if (w == m_DumpParamButton)
    {
      int selectedRowIndex = m_ConfigVariablesTextListbox.GetSelectedRow();
      string paramFinal;
      if (selectedRowIndex > -1)
      {
        string param;
        m_ConfigVariablesTextListbox.GetItemText(selectedRowIndex, 0, param);
        int index = param.IndexOf("=");
        if (index > 0)
          paramFinal = param.Substring(0, index).Trim();
      }
      int objects_row_index;
      objects_row_index = m_ConfigHierarchyTextListbox.GetSelectedRow();
      if (objects_row_index > -1 && objects_row_index < m_ConfigHierarchyTextListbox.GetNumItems())
      {
        ConfigParamsEx params;
        m_ConfigHierarchyTextListbox.GetItemData(objects_row_index, 0, params);
        string path = params.param4;
        TStringArray pathArr = new TStringArray();
        path.Split(" ", pathArr);
        string relativePath;
        foreach (int indx, string s: pathArr)
        {
          if (indx > 2)
            relativePath += s + " ";
        }
        if (relativePath)
          relativePath = relativePath.Trim();
        Print(relativePath);
        Print(path);
      }
      if (paramFinal)
        DumpParam(paramFinal, relativePath);
      return true;
    }
    else if (w == m_ConfigHierarchyTextListbox)
    {
      objects_row_index = m_ConfigHierarchyTextListbox.GetSelectedRow();
      //Print(objects_row_index);
      if (objects_row_index > -1 && objects_row_index < m_ConfigHierarchyTextListbox.GetNumItems())
      {
        ConfigParamsEx config_params;
        m_ConfigHierarchyTextListbox.GetItemData(objects_row_index, 0, config_params);
        if (config_params.param1 == false)
          ExpandHierarchy(objects_row_index);
        else
          CollapseHierarchy(objects_row_index);
        RenderVariables(objects_row_index);
        m_Row = objects_row_index;
      }
      return true;
    }
    else if (cbw && m_ClassCheckboxes.Contains(cbw))
    {
      int checkbox_index = m_ClassCheckboxes.Get(cbw);
      string base_class_name = m_BaseConfigClasses.Get(checkbox_index);
      int index_toggled = m_BaseConfigClassesToggled.Find(base_class_name);
      int flag, new_flag;
      if (m_ConfigDebugProfile)
        flag = m_ConfigDebugProfile.GetConfigClassesFlag();
      if (cbw.IsChecked())
      {
        if (index_toggled == -1)//not found
        {
          m_BaseConfigClassesToggled.Insert(base_class_name);
          if (m_ConfigDebugProfile)
            new_flag = (flag | (int)Math.Pow(2, checkbox_index));
        }
      }
      else if (index_toggled != -1)
      {
        m_BaseConfigClassesToggled.Remove(index_toggled);
        if (m_ConfigDebugProfile)
          new_flag = (flag ^ (int)Math.Pow(2, checkbox_index));
      }
      m_ConfigDebugProfile.SetConfigClassesFlag(new_flag);
      /*
        Print("-----------------------------------------");
        Print("flag = " + new_flag);
        foreach (string text:m_BaseConfigClassesToggled)
        {
        Print(text);
        }
        Print("-----------------------------------------");
      */
      ClearHierarchy();
    }
    else if (w == m_SelectedRowCopy)
    {
      AddItemToClipboard(m_ConfigVariablesTextListbox);
      return true;
    }
    return false;
  }
References ScriptConsoleTabBase::AddItemToClipboard(), ClearHierarchy(), CollapseHierarchy(), DumpParam(), ExpandHierarchy(), m_BaseConfigClasses, m_BaseConfigClassesToggled, m_ClassCheckboxes, ScriptConsoleTabBase::m_ConfigDebugProfile, m_ConfigHierarchyTextListbox, m_ConfigVariablesTextListbox, m_DumpParamButton, m_Row, m_SelectedRowCopy, path, Math::Pow(), Print(), RenderVariables(), string::Split(), x, and y.
OnItemSelected()
override bool ScriptConsoleConfigTab::OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline protected
Definition at line 73 of file ScriptConsoleConfigTab.c.
  {
    super.OnItemSelected(w, x, y, row, column, oldRow, oldColumn);
    if (w == m_ConfigHierarchyTextListbox)
    {
      TextListboxWidget wgt = TextListboxWidget.Cast(w);
      wgt.GetItemData(row, 0, m_ConfigData);
      RenderClassPath();
      return true;
    }
    return false;
  }
References m_ConfigData, m_ConfigHierarchyTextListbox, RenderClassPath(), x, and y.
RenderClassPath()
void ScriptConsoleConfigTab::RenderClassPath () inline protected
Definition at line 88 of file ScriptConsoleConfigTab.c.
  {
    m_ClassPath.SetText(m_ModuleConfigViewer.GetBaseClasses(m_ConfigData.param4, m_ConfigData.param2));
  }
References m_ClassPath, m_ConfigData, and m_ModuleConfigViewer.
Referenced by OnItemSelected().
RenderVariables()
void ScriptConsoleConfigTab::RenderVariables (int row) inline protected
Definition at line 444 of file ScriptConsoleConfigTab.c.
  {
    if (row > -1 && row < m_ConfigHierarchyTextListbox.GetNumItems())
    {
      string filter_lower = m_VariableConfigFilter.GetText();
      filter_lower.ToLower();
      TStringArray filters = new TStringArray();
      filter_lower.Split(" ", filters);
      ConfigParamsEx config_params;
      m_ConfigHierarchyTextListbox.GetItemData(row, 0, config_params);
      m_ConfigVariablesTextListbox.ClearItems();
      TStringArray variables;
      string path = config_params.param4;
      variables = m_ModuleConfigViewer.GetConfigVariables(path);
      for (int i = 0; i < variables.Count(); i++)
      {
        string var = variables.Get(i);
        if (filters.Count() == 0)
          m_ConfigVariablesTextListbox.AddItem(var, NULL, 0);
        else
        {
          foreach (string f: filters)
          {
            var.ToLower();
            if (var.Contains(f))
              m_ConfigVariablesTextListbox.AddItem(var, NULL, 0);
          }
        }
      }
    }
  }
References m_ConfigHierarchyTextListbox, m_ConfigVariablesTextListbox, m_ModuleConfigViewer, m_VariableConfigFilter, and path.
Referenced by OnChange(), and OnClick().
Update()
override void ScriptConsoleConfigTab::Update (float timeslice) inline protected
Definition at line 211 of file ScriptConsoleConfigTab.c.
  {
    super.Update(timeslice);
  }
Member Data Documentation
m_BaseConfigClasses
ref TStringArray ScriptConsoleConfigTab::m_BaseConfigClasses = new TStringArray protected
Definition at line 10 of file ScriptConsoleConfigTab.c.
Referenced by Init(), and OnClick().
m_BaseConfigClassesToggled
ref TStringArray ScriptConsoleConfigTab::m_BaseConfigClassesToggled = new TStringArray protected
Definition at line 11 of file ScriptConsoleConfigTab.c.
Referenced by ClearHierarchy(), DumpParam(), FindInHierarchy(), Init(), and OnClick().
m_ClassCheckboxes
ref map<CheckBoxWidget, int> ScriptConsoleConfigTab::m_ClassCheckboxes = new map<CheckBoxWidget, int> protected
Definition at line 12 of file ScriptConsoleConfigTab.c.
Referenced by Init(), OnClick(), and ~ScriptConsoleConfigTab().
m_ClassPath
TextWidget ScriptConsoleConfigTab::m_ClassPath protected
Definition at line 20 of file ScriptConsoleConfigTab.c.
Referenced by RenderClassPath(), and ScriptConsoleConfigTab().
m_ConfigData
ref ConfigParamsEx ScriptConsoleConfigTab::m_ConfigData static protected
Definition at line 9 of file ScriptConsoleConfigTab.c.
Referenced by OnItemSelected(), and RenderClassPath().
m_ConfigHierarchyTextListbox
TextListboxWidget ScriptConsoleConfigTab::m_ConfigHierarchyTextListbox protected
Definition at line 16 of file ScriptConsoleConfigTab.c.
Referenced by ClearHierarchy(), CollapseHierarchy(), ExpandHierarchy(), FindInHierarchy(), OnClick(), OnItemSelected(), RenderVariables(), and ScriptConsoleConfigTab().
m_ConfigTextField
string ScriptConsoleConfigTab::m_ConfigTextField static protected
Definition at line 7 of file ScriptConsoleConfigTab.c.
Referenced by ChangeConfigFilter(), and ScriptConsoleConfigTab().
m_ConfigVariablesTextListbox
TextListboxWidget ScriptConsoleConfigTab::m_ConfigVariablesTextListbox protected
Definition at line 17 of file ScriptConsoleConfigTab.c.
Referenced by ClearHierarchy(), FindInHierarchy(), OnClick(), RenderVariables(), and ScriptConsoleConfigTab().
m_DumpParamButton
ButtonWidget ScriptConsoleConfigTab::m_DumpParamButton protected
Definition at line 19 of file ScriptConsoleConfigTab.c.
Referenced by OnClick(), and ScriptConsoleConfigTab().
m_ModuleConfigViewer
PluginConfigViewer ScriptConsoleConfigTab::m_ModuleConfigViewer protected
Definition at line 24 of file ScriptConsoleConfigTab.c.
Referenced by ClearHierarchy(), ExpandHierarchy(), FindInHierarchy(), Init(), RenderClassPath(), and RenderVariables().
m_ObjectConfigFilter
EditBoxWidget ScriptConsoleConfigTab::m_ObjectConfigFilter protected
Definition at line 14 of file ScriptConsoleConfigTab.c.
Referenced by ChangeConfigFilter(), OnChange(), and ScriptConsoleConfigTab().
m_Row
int ScriptConsoleConfigTab::m_Row protected
Definition at line 25 of file ScriptConsoleConfigTab.c.
Referenced by OnChange(), and OnClick().
m_SelectedRowCopy
ButtonWidget ScriptConsoleConfigTab::m_SelectedRowCopy protected
Definition at line 18 of file ScriptConsoleConfigTab.c.
Referenced by OnClick(), and ScriptConsoleConfigTab().
m_VariableConfigFilter
EditBoxWidget ScriptConsoleConfigTab::m_VariableConfigFilter protected
Definition at line 15 of file ScriptConsoleConfigTab.c.
Referenced by OnChange(), RenderVariables(), ScriptConsoleConfigTab(), and ~ScriptConsoleConfigTab().
m_VariableTextField
string ScriptConsoleConfigTab::m_VariableTextField static protected
Definition at line 8 of file ScriptConsoleConfigTab.c.
Referenced by ScriptConsoleConfigTab(), and ~ScriptConsoleConfigTab().
m_WgtClassesConfig
Widget ScriptConsoleConfigTab::m_WgtClassesConfig protected
Definition at line 23 of file ScriptConsoleConfigTab.c.
Referenced by Init(), and ScriptConsoleConfigTab().
The documentation for this class was generated from the following file:
scripts/5_Mission/GUI/ScriptConsoleConfigTab.c