DayZ: StuffedNotfr Class Reference
StuffedNotfr Class Reference
Private Member Functions
void StuffedNotfr (NotifiersManager manager)
override int GetNotifierType ()
override void DisplayBadge ()
override void HideBadge ()
Private Member Functions inherited from NotifierBase
int CalculateTendency (float delta, float inctresholdlow, float inctresholdmed, float inctresholdhigh, float dectresholdlow, float dectresholdmed, float dectresholdhigh)
eBadgeLevel DetermineBadgeLevel (float value, float lvl_1, float lvl_2, float lvl_3)
void DisplayBadge ()
void HideBadge ()
float GetObservedValue ()
Detailed Description
Definition at line 1 of file StuffedNotfr.c.
Constructor & Destructor Documentation
StuffedNotfr()
void StuffedNotfr::StuffedNotfr (NotifiersManager manager) inline private
Definition at line 3 of file StuffedNotfr.c.
  {
    m_Active = true;
  }
References NotifierBase::m_Active.
Member Function Documentation
DisplayBadge()
override void StuffedNotfr::DisplayBadge () inline private
Definition at line 13 of file StuffedNotfr.c.
  {
    float volume = m_Player.m_PlayerStomach.GetStomachVolume();
    eBadgeLevel lvl = DetermineBadgeLevel(volume, PlayerConstants.BT_STOMACH_VOLUME_LVL3, PlayerConstants.BT_STOMACH_VOLUME_LVL3, PlayerConstants.BT_STOMACH_VOLUME_LVL3);
    DisplayElementBadge dis_elm = DisplayElementBadge.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_BADGE_STUFFED));
    if (dis_elm)
      dis_elm.SetLevel(lvl);
  }
References PlayerConstants::BT_STOMACH_VOLUME_LVL3, NotifierBase::DetermineBadgeLevel(), GetElement(), NotifierBase::GetVirtualHud(), and NotifierBase::m_Player.
GetNotifierType()
override int StuffedNotfr::GetNotifierType () inline private
Definition at line 8 of file StuffedNotfr.c.
  {
    return eNotifiers.NTF_STUFFED;
  }
HideBadge()
override void StuffedNotfr::HideBadge () inline private
Definition at line 23 of file StuffedNotfr.c.
  {
    DisplayElementBadge dis_elm = DisplayElementBadge.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_BADGE_STUFFED));
    if (dis_elm)
      dis_elm.SetLevel(eBadgeLevel.NONE);
  }
References GetElement(), and NotifierBase::GetVirtualHud().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/PlayerNotifiers/Notifiers/StuffedNotfr.c