DayZ: PlateCarrierVest Class Reference
PlateCarrierVest Class Reference
Private Member Functions
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnDebugSpawn ()
Detailed Description
Definition at line 1 of file PlateCarrierVest.c.
Member Function Documentation
OnDebugSpawn()
override void PlateCarrierVest::OnDebugSpawn () inline private
Definition at line 15 of file PlateCarrierVest.c.
  {
    EntityAI entity;
    if (Class.CastTo(entity, this))
    {
      entity.GetInventory().CreateInInventory("PlateCarrierPouches");
      entity.GetInventory().CreateInInventory("PlateCarrierHolster");
    }
  }
References Class::CastTo().
OnWasAttached()
override void PlateCarrierVest::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 3 of file PlateCarrierVest.c.
  {
    super.OnWasAttached(parent, slot_id);
    if (GetGame().IsServer() && parent.IsInherited(DayZInfected))
    {
      float coef = Math.RandomFloatInclusive(0.2, 0.4);
      SetHealth01("", "", coef);
    }
  }
References GetGame(), and Math::RandomFloatInclusive().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Clothing/PlateCarrierVest.c