DayZ: scripts/3_Game/DayZAnimEventMaps.c File Reference
DayZAnimEventMaps.c File Reference
Classes
class SoundLookupTable
class AnimSoundObjectBuilderBank
Functions
class SoundLookupTable StepSoundLookupTable ()
void SoundLookupTable ()
void InitTable (string tableCategoryName, string parameterName)
void LoadTable (string soundLookupTableName)
SoundObjectBuilder GetSoundBuilder (int parameterHash)
void PlayerVoiceLookupTable ()
void SetNoiseParam (NoiseParams param)
NoiseParams GetNoiseParam ()
class ImpactSoundLookupTable extends SoundLookupTable ActionSoundLookupTable ()
void ImpactSoundLookupTable ()
class AnimSoundObjectBuilderBank AnimSoundLookupTableBank ()
void AnimSoundObjectBuilderBank ()
static AnimSoundObjectBuilderBank GetInstance ()
SoundObjectBuilder GetBuilder (string soundSetName)
SoundLookupTable GetStepTable (string tableName)
SoundLookupTable GetImpactTable (string tableName)
SoundLookupTable GetActionTable (string tableName)
Variables
string m_tableCategoryName
string m_parameterName
ref map< int, ref array< SoundObjectBuilder > > m_soundBuilders
class AttachmentSoundLookupTable extends SoundLookupTable m_NoiseParams
static ref AnimSoundObjectBuilderBank m_instance
autoptr map< int, ref SoundObjectBuilder > m_pBuilders
autoptr map< int, ref SoundLookupTable > m_pTables
Function Documentation
ActionSoundLookupTable()
class ImpactSoundLookupTable extends SoundLookupTable ActionSoundLookupTable ()
Definition at line 112 of file DayZAnimEventMaps.c.
  {
    InitTable("CfgActionsSoundTables", "category");
  }
Referenced by GetActionTable().
AnimSoundLookupTableBank()
class AnimSoundObjectBuilderBank AnimSoundLookupTableBank ()
Definition at line 112 of file DayZAnimEventMaps.c.
  {
    m_pTables = new map<int, ref SoundLookupTable>();
  }
Referenced by GetInstance(), and EntityAI::InitImpactSoundData().
AnimSoundObjectBuilderBank()
void AnimSoundLookupTableBank::AnimSoundObjectBuilderBank ()
Definition at line 176 of file DayZAnimEventMaps.c.
  {
    m_pTables = new map<int, ref SoundLookupTable>();
  }
References m_pTables.
GetActionTable()
SoundLookupTable GetActionTable (string tableName)
Definition at line 218 of file DayZAnimEventMaps.c.
  {
    int tableNameHash = tableName.Hash();
    SoundLookupTable table = m_pTables.Get(tableNameHash);
    if (table == NULL)
    {
      table = new ActionSoundLookupTable();
      table.LoadTable(tableName);
      m_pTables.Insert(tableNameHash, table);
    }
    return table;
  }
References ActionSoundLookupTable(), and m_pTables.
GetBuilder()
SoundObjectBuilder AnimSoundLookupTableBank::GetBuilder (string soundSetName)
Definition at line 191 of file DayZAnimEventMaps.c.
  {
    int tableNameHash = tableName.Hash();
    SoundLookupTable table = m_pTables.Get(tableNameHash);
    if (table == NULL)
    {
      table = new StepSoundLookupTable();
      table.LoadTable(tableName);
      m_pTables.Insert(tableNameHash, table);
    }
    return table;
  }
  SoundLookupTable GetImpactTable(string tableName)
  {
    int tableNameHash = tableName.Hash();
    SoundLookupTable table = m_pTables.Get(tableNameHash);
    if (table == NULL)
    {
      table = new ImpactSoundLookupTable();
References m_pTables, and StepSoundLookupTable().
GetImpactTable()
SoundLookupTable GetImpactTable (string tableName)
Definition at line 204 of file DayZAnimEventMaps.c.
  {
    int tableNameHash = tableName.Hash();
    SoundLookupTable table = m_pTables.Get(tableNameHash);
    if (table == NULL)
    {
      table = new ImpactSoundLookupTable();
      table.LoadTable(tableName);
      m_pTables.Insert(tableNameHash, table);
    }
    return table;
  }
References ImpactSoundLookupTable(), and m_pTables.
GetInstance()
static AnimSoundLookupTableBank GetInstance () static
Definition at line 182 of file DayZAnimEventMaps.c.
  {
    if (m_instance == NULL)
      m_instance = new AnimSoundLookupTableBank();
    return m_instance;
  }
References AnimSoundLookupTableBank(), and m_instance.
GetNoiseParam()
NoiseParams GetNoiseParam ()
Definition at line 105 of file DayZAnimEventMaps.c.
  {
    return m_NoiseParams;
  }
References m_NoiseParams.
GetSoundBuilder()
SoundObjectBuilder StepSoundLookupTable::GetSoundBuilder (int parameterHash)
Definition at line 127 of file DayZAnimEventMaps.c.
{
  void AnimSoundObjectBuilderBank()
  {
    m_pBuilders = new map<int, ref SoundObjectBuilder>();
  }
  static AnimSoundObjectBuilderBank GetInstance()
  {
    if (m_instance == NULL)
      m_instance = new AnimSoundObjectBuilderBank();
GetStepTable()
SoundLookupTable GetStepTable (string tableName)
Definition at line 190 of file DayZAnimEventMaps.c.
  {
    int tableNameHash = tableName.Hash();
    SoundLookupTable table = m_pTables.Get(tableNameHash);
    if (table == NULL)
    {
      table = new StepSoundLookupTable();
      table.LoadTable(tableName);
      m_pTables.Insert(tableNameHash, table);
    }
    return table;
  }
ImpactSoundLookupTable()
void ActionSoundLookupTable::ImpactSoundLookupTable ()
Definition at line 123 of file DayZAnimEventMaps.c.
  {
    InitTable("CfgActionsSoundTables", "category");
  }
}
References SoundLookupTable::InitTable().
Referenced by GetImpactTable().
InitTable()
void StepSoundLookupTable::InitTable (string tableCategoryName, string parameterName)
Definition at line 83 of file DayZAnimEventMaps.c.
{
  void AttachmentSoundLookupTable()
  {
    InitTable("CfgAttachmentSoundTables", "category");
LoadTable()
void StepSoundLookupTable::LoadTable (string soundLookupTableName)
Definition at line 89 of file DayZAnimEventMaps.c.
{
  ref NoiseParams m_NoiseParams;
  void PlayerVoiceLookupTable()
  {
    InitTable("CfgVoiceSoundTables", "category");
  }
  void SetNoiseParam(NoiseParams param)
  {
    m_NoiseParams = param;
  }
  NoiseParams GetNoiseParam()
  {
    return m_NoiseParams;
  }
}
class ImpactSoundLookupTable extends SoundLookupTable
{
  void ImpactSoundLookupTable()
  {
    InitTable("CfgImpactSoundTables", "surface");
  }
}
class ActionSoundLookupTable extends SoundLookupTable
{
  void ActionSoundLookupTable()
  {
    InitTable("CfgActionsSoundTables", "category");
  }
PlayerVoiceLookupTable()
void PlayerVoiceLookupTable ()
Definition at line 95 of file DayZAnimEventMaps.c.
  {
    InitTable("CfgVoiceSoundTables", "category");
  }
References SoundLookupTable::InitTable().
Referenced by DayZPlayerTypeVoiceSoundLookupTable::DayZPlayerTypeVoiceSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTable::GetNoiseParams(), and DayZPlayerTypeVoiceSoundLookupTable::GetSoundBuilder().
SetNoiseParam()
void SetNoiseParam (NoiseParams param)
Definition at line 100 of file DayZAnimEventMaps.c.
  {
    m_NoiseParams = param;
  }
References m_NoiseParams.
SoundLookupTable()
void StepSoundLookupTable::SoundLookupTable ()
Definition at line 78 of file DayZAnimEventMaps.c.
  {
    InitTable("CfgStepSoundTables", "surface");
  }
}
References SoundLookupTable::InitTable().
StepSoundLookupTable()
class SoundLookupTable StepSoundLookupTable ()
Definition at line 1 of file DayZAnimEventMaps.c.
  {
    InitTable("CfgStepSoundTables", "surface");
  }
Referenced by DayZPlayerTypeStepSoundLookupTable::DayZPlayerTypeStepSoundLookupTableImpl(), and GetBuilder().
Variable Documentation
m_instance
static ref AnimSoundLookupTableBank m_instance static private
Definition at line 213 of file DayZAnimEventMaps.c.
Referenced by GetInstance(), DayZPlayerTypeStepSoundLookupTable::GetInstance(), and DayZPlayerTypeVoiceSoundLookupTable::GetInstance().
m_NoiseParams
class AttachmentSoundLookupTable extends SoundLookupTable m_NoiseParams
Referenced by CGame::CloseCombatEffects(), CGame::ExplosionEffectsEx(), CGame::FirearmEffects(), GetNoiseParam(), and SetNoiseParam().
m_parameterName
string m_parameterName private
Definition at line 144 of file DayZAnimEventMaps.c.
m_pBuilders
autoptr map<int, ref SoundObjectBuilder> m_pBuilders private
Definition at line 214 of file DayZAnimEventMaps.c.
m_pTables
autoptr map<int, ref SoundLookupTable> m_pTables private
Definition at line 233 of file DayZAnimEventMaps.c.
Referenced by AnimSoundObjectBuilderBank(), GetActionTable(), GetBuilder(), and GetImpactTable().
m_soundBuilders
ref map<int, ref array<SoundObjectBuilder> > m_soundBuilders private
Definition at line 145 of file DayZAnimEventMaps.c.
m_tableCategoryName
string m_tableCategoryName private
Definition at line 143 of file DayZAnimEventMaps.c.