DayZ: SpawnDataConverter Class Reference
SpawnDataConverter Class Reference
Utility class that converts init.c format type of spawn commands to a json file, fill in the SpawnInit() with your data and call SpawnDataConverter.SpawnObjects() through script editor console, result is a json file.
Static Private Member Functions
static void SpawnObjects ()
static void SpawnInit ()
static void AddSpawnData (string objectName, vector position, vector orientation)
Static Private Attributes
static ref array< ref ITEM_SpawnerObject > Objects = new array<ref ITEM_SpawnerObject>
static string m_Path = "$mission:myspawndata.json"
Detailed Description
Utility class that converts init.c format type of spawn commands to a json file, fill in the SpawnInit() with your data and call SpawnDataConverter.SpawnObjects() through script editor console, result is a json file.
Definition at line 98 of file ObjectSpawner.c.
Member Function Documentation
AddSpawnData()
static void SpawnDataConverter::AddSpawnData (string objectName, vector position, vector orientation) inline static private
Definition at line 123 of file ObjectSpawner.c.
  {
    ITEM_SpawnerObject obj = new ITEM_SpawnerObject();
    obj.name = objectName;
    obj.pos[0] = position[0];
    obj.pos[1] = position[1];
    obj.pos[2] = position[2];
    obj.ypr[0] = orientation[0];
    obj.ypr[1] = orientation[1];
    obj.ypr[2] = orientation[2];
    Objects.Insert(obj);
  }
References ITEM_SpawnerObject::name, Objects, ITEM_SpawnerObject::pos, and ITEM_SpawnerObject::ypr.
Referenced by SpawnInit().
SpawnInit()
static void SpawnDataConverter::SpawnInit () inline static private
Definition at line 115 of file ObjectSpawner.c.
  {
    AddSpawnData("Land_Wall_Gate_FenR", "8406.501953 107.736824 12782.338867", "0.000000 0.000000 0.000000");
    AddSpawnData("Land_Wall_Gate_FenR", "8410.501953 107.736824 12782.338867", "0.000000 0.000000 0.000000");
    AddSpawnData("Land_Wall_Gate_FenR", "8416.501953 107.736824 12782.338867", "0.000000 0.000000 0.000000");
    AddSpawnData("Land_Wall_Gate_FenR", "8422.501953 107.736824 12782.338867", "0.000000 0.000000 0.000000");
  }
References AddSpawnData().
Referenced by SpawnObjects().
SpawnObjects()
static void SpawnDataConverter::SpawnObjects () inline static private
Definition at line 103 of file ObjectSpawner.c.
  {
    Objects.Clear();
    SpawnInit();
    ObjectSpawnerJson j = new ObjectSpawnerJson();
    j.Objects = Objects;
    string errorMessage;
    if (!JsonFileLoader<ObjectSpawnerJson>.SaveFile(m_Path, j, errorMessage))
      ErrorEx(errorMessage);
  }
References ErrorEx, m_Path, Objects, and SpawnInit().
Member Data Documentation
m_Path
string SpawnDataConverter::m_Path = "$mission:myspawndata.json" static private
Definition at line 101 of file ObjectSpawner.c.
Referenced by SpawnObjects().
Objects
ref array<ref ITEM_SpawnerObject> SpawnDataConverter::Objects = new array<ref ITEM_SpawnerObject> static private
Definition at line 100 of file ObjectSpawner.c.
Referenced by AddSpawnData(), and SpawnObjects().
The documentation for this class was generated from the following file:
scripts/3_Game/ObjectSpawner.c