DayZ: ScriptInvokerTests Class Reference
ScriptInvokerTests Class Reference
Private Member Functions
void ScriptInvokerTests ()
void ~ScriptInvokerTests ()
TFResult TestFirstUnique ()
TFResult TestSecondUnique ()
TFResult TestInsertRemoveUnique ()
TFResult TestInsertUniqueImmediate ()
TFResult TestClearRunning ()
TFResult TestInvokeRunning ()
TFResult TestInsertRunning ()
void InvokeLog (string s)
void InvokeReset ()
void InvokeClear (string s)
void InvokeInvoke (string s)
void InvokeInsert (string s)
Private Attributes
ref ScriptInvoker m_Invoker
int m_InvokeCount
Detailed Description
Definition at line 1 of file ScriptInvokerTests.c.
Constructor & Destructor Documentation
ScriptInvokerTests()
void ScriptInvokerTests::ScriptInvokerTests () inline private
Definition at line 9 of file ScriptInvokerTests.c.
  {
    m_Invoker = new ScriptInvoker();
    //AddInitTest("TestFirstUnique");
    //AddInitTest("TestSecondUnique");
    //AddInitTest("TestInsertRemoveUnique");
    //AddInitTest("TestInsertUniqueImmediate");
    //AddInitTest("TestClearRunning");
    //AddInitTest("TestInvokeRunning");
    AddInitTest("TestInsertRunning");
  }
References AddInitTest(), and m_Invoker.
~ScriptInvokerTests()
void ScriptInvokerTests::~ScriptInvokerTests () inline private
Definition at line 25 of file ScriptInvokerTests.c.
  {
  }
Member Function Documentation
InvokeClear()
void ScriptInvokerTests::InvokeClear (string s) inline private
Definition at line 175 of file ScriptInvokerTests.c.
  {
    InvokeLog(s);
    m_Invoker.Clear();
  }
References InvokeLog(), and m_Invoker.
Referenced by TestClearRunning().
InvokeInsert()
void ScriptInvokerTests::InvokeInsert (string s) inline private
Definition at line 187 of file ScriptInvokerTests.c.
  {
    InvokeLog(s);
    m_Invoker.Insert(InvokeInsert, EScriptInvokerInsertFlags.IMMEDIATE);
  }
References InvokeInsert(), InvokeLog(), and m_Invoker.
Referenced by InvokeInsert(), and TestInsertRunning().
InvokeInvoke()
void ScriptInvokerTests::InvokeInvoke (string s) inline private
Definition at line 181 of file ScriptInvokerTests.c.
  {
    InvokeLog(s);
    m_Invoker.Invoke(s);
  }
References InvokeLog(), and m_Invoker.
Referenced by TestInvokeRunning().
InvokeLog()
void ScriptInvokerTests::InvokeLog (string s) inline private
Definition at line 163 of file ScriptInvokerTests.c.
  {
    //Debug.TFLog(s, this, "InvokeLog");
    ++m_InvokeCount;
  }
References m_InvokeCount.
Referenced by InvokeClear(), InvokeInsert(), InvokeInvoke(), TestClearRunning(), TestFirstUnique(), TestInsertRemoveUnique(), TestInsertUniqueImmediate(), and TestSecondUnique().
InvokeReset()
void ScriptInvokerTests::InvokeReset () inline private
Definition at line 169 of file ScriptInvokerTests.c.
  {
    m_Invoker.Clear();
    m_InvokeCount = 0;
  }
References m_InvokeCount, and m_Invoker.
Referenced by TestClearRunning(), TestFirstUnique(), TestInsertRemoveUnique(), TestInsertRunning(), TestInsertUniqueImmediate(), TestInvokeRunning(), and TestSecondUnique().
TestClearRunning()
TFResult ScriptInvokerTests::TestClearRunning () inline private
Definition at line 112 of file ScriptInvokerTests.c.
  {
    InvokeReset();
    m_Invoker.Insert(InvokeClear);
    m_Invoker.Insert(InvokeLog);
    m_Invoker.Invoke("TestClearRunning");
    bool count = Assert(m_InvokeCount == 1);
    InvokeReset();
    return BTFR(count);
  }
References Assert(), BTFR(), InvokeClear(), InvokeLog(), InvokeReset(), m_InvokeCount, and m_Invoker.
TestFirstUnique()
TFResult ScriptInvokerTests::TestFirstUnique () inline private
Definition at line 34 of file ScriptInvokerTests.c.
  {
    InvokeReset();
    bool insert1 = m_Invoker.Insert(InvokeLog, EScriptInvokerInsertFlags.UNIQUE);
    Assert(insert1);
    bool insert2 = m_Invoker.Insert(InvokeLog);
    Assert(!insert2);
    m_Invoker.Invoke("TestFirstUnique");
    bool count = Assert(m_InvokeCount == 1);
    InvokeReset();
    return BTFR(insert1 && !insert2 && count);
  }
References Assert(), BTFR(), InvokeLog(), InvokeReset(), m_InvokeCount, and m_Invoker.
TestInsertRemoveUnique()
TFResult ScriptInvokerTests::TestInsertRemoveUnique () inline private
Definition at line 72 of file ScriptInvokerTests.c.
  {
    InvokeReset();
    bool insert1 = m_Invoker.Insert(InvokeLog, EScriptInvokerInsertFlags.UNIQUE);
    Assert(insert1);
    bool remove1 = m_Invoker.Remove(InvokeLog);
    Assert(remove1);
    bool insert2 = m_Invoker.Insert(InvokeLog);
    Assert(insert2);
    m_Invoker.Invoke("TestInsertRemoveUnique");
    bool count = Assert(m_InvokeCount == 1);
    InvokeReset();
    return BTFR(insert1 && remove1 && insert2 && count);
  }
References Assert(), BTFR(), InvokeLog(), InvokeReset(), m_InvokeCount, and m_Invoker.
TestInsertRunning()
TFResult ScriptInvokerTests::TestInsertRunning () inline private
Definition at line 144 of file ScriptInvokerTests.c.
  {
    InvokeReset();
    m_Invoker.Insert(InvokeInsert);
    m_Invoker.Invoke("TestInvokeRunning");
    Print(m_InvokeCount);
    bool count = Assert(m_InvokeCount == 129);
    InvokeReset();
    return BTFR(count);
  }
References Assert(), BTFR(), InvokeInsert(), InvokeReset(), m_InvokeCount, m_Invoker, and Print().
TestInsertUniqueImmediate()
TFResult ScriptInvokerTests::TestInsertUniqueImmediate () inline private
Definition at line 93 of file ScriptInvokerTests.c.
  {
    InvokeReset();
    bool insert1 = m_Invoker.Insert(InvokeLog, EScriptInvokerInsertFlags.UNIQUE);
    Assert(insert1);
    bool insert2 = m_Invoker.Insert(InvokeLog, EScriptInvokerInsertFlags.IMMEDIATE);
    Assert(insert2);
    m_Invoker.Invoke("TestInsertUniqueImmediate");
    bool count = Assert(m_InvokeCount == 1);
    InvokeReset();
    return BTFR(insert1 && !insert2 && count);
  }
References Assert(), BTFR(), InvokeLog(), InvokeReset(), m_InvokeCount, and m_Invoker.
TestInvokeRunning()
TFResult ScriptInvokerTests::TestInvokeRunning () inline private
Definition at line 129 of file ScriptInvokerTests.c.
  {
    InvokeReset();
    m_Invoker.Insert(InvokeInvoke);
    m_Invoker.Invoke("TestInvokeRunning");
    InvokeReset();
    return BTFR(false); // This can never succeed, it will never even reach this point
  }
References BTFR(), InvokeInvoke(), InvokeReset(), and m_Invoker.
TestSecondUnique()
TFResult ScriptInvokerTests::TestSecondUnique () inline private
Definition at line 53 of file ScriptInvokerTests.c.
  {
    InvokeReset();
    bool insert1 = m_Invoker.Insert(InvokeLog);
    Assert(insert1);
    bool insert2 = m_Invoker.Insert(InvokeLog, EScriptInvokerInsertFlags.UNIQUE);
    Assert(!insert2);
    m_Invoker.Invoke("TestSecondUnique");
    bool count = Assert(m_InvokeCount == 1);
    InvokeReset();
    return BTFR(insert1 && !insert2 && count);
  }
References Assert(), BTFR(), InvokeLog(), InvokeReset(), m_InvokeCount, and m_Invoker.
Member Data Documentation
m_InvokeCount
int ScriptInvokerTests::m_InvokeCount private
Definition at line 4 of file ScriptInvokerTests.c.
Referenced by InvokeLog(), InvokeReset(), TestClearRunning(), TestFirstUnique(), TestInsertRemoveUnique(), TestInsertRunning(), TestInsertUniqueImmediate(), and TestSecondUnique().
m_Invoker
ref ScriptInvoker ScriptInvokerTests::m_Invoker private
Definition at line 3 of file ScriptInvokerTests.c.
Referenced by InvokeClear(), InvokeInsert(), InvokeInvoke(), InvokeReset(), ScriptInvokerTests(), TestClearRunning(), TestFirstUnique(), TestInsertRemoveUnique(), TestInsertRunning(), TestInsertUniqueImmediate(), TestInvokeRunning(), and TestSecondUnique().
The documentation for this class was generated from the following file:
scripts/3_Game/Systems/TFTests/ScriptInvokerTests.c