DayZ: SoundObjectBuilder Class Reference
SoundObjectBuilder Class Reference
Private Member Functions
void SoundObjectBuilder (SoundParams soundParams)
SoundObject BuildSoundObject ()
proto native void Initialize (SoundParams soundParams)
proto native void AddEnvSoundVariables (vector position)
proto native void AddVariable (string name, float value)
proto void AddVariables (notnull array< string > names, array< float > values=null)
void UpdateEnvSoundControllers (vector position)
Deprecated - same functionality, just poor naming.
void SetVariable (string name, float value)
Deprecated - same functionality, just poor naming.
Detailed Description
Definition at line 45 of file Sound.c.
Constructor & Destructor Documentation
SoundObjectBuilder()
void SoundObjectBuilder::SoundObjectBuilder (SoundParams soundParams) private
Member Function Documentation
AddEnvSoundVariables()
proto native void SoundObjectBuilder::AddEnvSoundVariables (vector position) private
Referenced by UpdateEnvSoundControllers().
AddVariable()
proto native void SoundObjectBuilder::AddVariable (string name, float value) private
Referenced by SetVariable().
AddVariables()
proto void SoundObjectBuilder::AddVariables (notnull array< string > names, array< float > values = null) private
BuildSoundObject()
SoundObject SoundObjectBuilder::BuildSoundObject () inline private
Definition at line 49 of file Sound.c.
  {
    return GetGame().GetSoundScene().BuildSoundObject(this);
  }
References GetGame().
Initialize()
proto native void SoundObjectBuilder::Initialize (SoundParams soundParams) private
SetVariable()
void SoundObjectBuilder::SetVariable (string name, float value) inline private
Deprecated - same functionality, just poor naming.
Definition at line 67 of file Sound.c.
  {
    AddVariable(name, value);
  }
References AddVariable(), and name.
UpdateEnvSoundControllers()
void SoundObjectBuilder::UpdateEnvSoundControllers (vector position) inline private
Deprecated - same functionality, just poor naming.
Definition at line 61 of file Sound.c.
  {
    AddEnvSoundVariables(position);
  }
References AddEnvSoundVariables().
The documentation for this class was generated from the following file:
scripts/3_Game/Sound.c