DayZ: FlareSimulation Class Reference
FlareSimulation Class Reference
Protected Member Functions
void FlareSimulation ()
void OnActivation (Entity flare)
void OnTermination (Entity flare)
void OnFire (Entity flare)
void Simulate (Entity flare)
void CastFlareAINoise (vector position)
void TurnOffDistantLight ()
void ~FlareSimulation ()
Protected Attributes
Particle m_ParMainFire
EffectSound m_BurningSound
FlareLight m_FlareLight
float m_LastNoiseTime = -1
float m_NoiseTimer = 0
const float NOISE_DELAY = 5
Static Protected Attributes
static const float MAX_FARLIGHT_DIST = 40
static const float MIN_FARLIGHT_DIST = 5
static ref NoiseParams m_NoisePar
m_ScriptedLight
int m_ParticleId
Additional Inherited Members
Private Member Functions inherited from Managed
void IntroSceneCharacter ()
void ~IntroSceneCharacter ()
bool IsDefaultCharacter ()
void SetToDefaultCharacter ()
void SetCharacterID (int char_id)
int GetCharacterID ()
PlayerBase GetCharacterObj ()
TStringArray GetCharGenderList ()
TStringArray GetCharList (ECharGender gender)
TStringArray GetCharShirtsList ()
TStringArray GetCharPantsList ()
TStringArray GetCharShoesList ()
void SetCharacterGender (ECharGender gender)
bool IsCharacterFemale ()
ECharGender GetCharacterGender ()
vector GetPosition ()
int GetNextCharacterID ()
int GetPrevCharacterID ()
void CreateNewCharacterRandom ()
void CreateNewCharacterById (int character_id)
void CreateNewCharacterByName (string character_name, bool randomize_equip=true)
void CreateDefaultCharacter ()
void GetLastPlayedServer (int characterID, out string address, out string name, out int port)
void CreateNewCharacter ()
void LoadCharacterData (vector char_pos, vector char_rot, bool default_char=false)
Generates random equip for the new IntroSceneCharacter, whatever is defined in 'cfgCharacterCreation'.
void CharacterUnload ()
void CharacterLoad (int character_id, vector char_pos, vector char_rot)
void SetupPlayerName (bool new_name)
void SetAttachment (string type, int slot)
string GetCharacterNameById (int char_id)
string GetCharacterName ()
void SaveCharName (string name)
void SaveDefaultCharacter ()
void TransferValues (PlayerBase player)
void Init ()
void OnScheduledTick (float deltatime)
void CheckValues ()
float GetBlood ()
float GetHealth ()
void CheckHealth ()
void CheckBlood ()
void SendInitValues ()
Sends values on object creation.
void SendValue (int value_type, float value)
void ReceiveValue (int value_type, float value)
void OnRPC (ParamsReadContext ctx)
void ShowDebugValues (bool show)
void BleedingIndicator (int source_ID, int severity, GameplayEffectsDataBleeding parent)
void InitIndicator (vector position)
void StopIndicator (bool instant=false)
void StartRunningDrops ()
bool IsRunningDrops ()
Are any drops currently being animated?
void TrySpawnNextDrop ()
void ResetSequence ()
void ResetIndicator ()
void Update (float timeSlice)
bool GetEndNow ()
int GetSeverity ()
void GameplayEffectsData (array< ref Widget > input, int type, int user_override=-1)
void Init (array< ref Widget > input, int type, Widget layout_root, int user_override=-1)
array< ref Widget > GetWidgetSet ()
int GetWidgetSetType ()
int GetWidgetSetID ()
bool HasDefinedHandle ()
Returns 'true' if this class contains update info.
bool DataInitialized ()
void UpdateVisibility (bool state)
void RegisterData (Param p)
void Update (float timeSlice=0, Param p=null, int handle=-1)
void ForceStop ()
Private Attributes inherited from Managed
int m_CharacterId
string m_CharacterType
MenuData m_CharacterDta
PlayerBase m_CharacterObj
vector m_CharacterPos
vector m_CharacterRot
ref TStringArray m_CharGenderList = new TStringArray
ref TStringArray m_CharShirtList = new TStringArray
ref TStringArray m_CharPantsList = new TStringArray
ref TStringArray m_CharShoesList = new TStringArray
ref map< ECharGender, ref array< string > > m_Characters = new map<ECharGender, ref array<string>>
ECharGender m_CharGender
bool m_InitialSyncSent
bool m_Initialized
bool m_Terminating = false
bool m_EndNow = false
bool m_IsRunning = false
int m_DropSpawnsQueued
int m_ActiveDropsCount
int m_Severity
int m_SourceID
GameplayEffectsDataBleeding m_ParentMetaData
array< float > m_DropProbabilityArray
float m_AverageFrequency
float m_SequenceTick
float m_SequenceDuration
float m_TimeElapsedTotal
float m_TimeElapsedSequence
float m_LastDropSpawnTime
float m_DropSpawnMinDelay
float m_DropSpawnMaxDelay
int m_CurrentDropProbabilityStep
int m_DropProbabilityRollsCount
vector m_BasePosition
ref set< ref BleedingIndicatorDropData > m_ActiveDrops
ref set< int > m_CleanupQueue
ref array< ref Widget > m_WidgetArray
int m_Type
int m_WidgetSetIdentifier
Widget m_LayoutRoot
Detailed Description
Definition at line 1 of file FlareSimulation.c.
Constructor & Destructor Documentation
FlareSimulation()
void FlareSimulation::FlareSimulation () inline protected
Definition at line 17 of file FlareSimulation.c.
  {
    m_ScriptedLight = FlareLight;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE;
  }
References FlareLight(), ParticleList::FLAREPROJ_ACTIVATE, m_ParticleId, and m_ScriptedLight.
~FlareSimulation()
void FlareSimulation::~FlareSimulation () inline protected
Definition at line 105 of file FlareSimulation.c.
  {
    if (m_ParMainFire)
      m_ParMainFire.Stop();
    if (m_BurningSound)
      m_BurningSound.SoundStop();
    if (m_FlareLight)
      m_FlareLight.FadeOut();
  }
References m_BurningSound, m_FlareLight, m_ParMainFire, EffectSound::SoundStop(), and Particle::Stop().
Member Function Documentation
CastFlareAINoise()
void FlareSimulation::CastFlareAINoise (vector position) inline protected
Definition at line 76 of file FlareSimulation.c.
  {
    if (m_LastNoiseTime < 0)
      m_LastNoiseTime = GetGame().GetTime() * 0.0033;
    float delta_time = GetGame().GetTime() * 0.0033 - m_LastNoiseTime;
    m_LastNoiseTime = GetGame().GetTime() * 0.0033;
    m_NoiseTimer += delta_time;
    if (m_NoiseTimer >= NOISE_DELAY)
    {
      MiscGameplayFunctions.GenerateAINoiseAtPosition(position, NOISE_DELAY, m_NoisePar);
      m_NoiseTimer = 0;
    }
  }
References GetGame(), m_LastNoiseTime, m_NoisePar, m_NoiseTimer, and NOISE_DELAY.
OnActivation()
void FlareSimulation::OnActivation (Entity flare) inline protected
Definition at line 23 of file FlareSimulation.c.
  {
    if (!GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      m_FlareLight = FlareLight.Cast(ScriptedLightBase.CreateLight(m_ScriptedLight, Vector(0, 0, 0)));
      if (m_FlareLight)
        m_FlareLight.AttachOnObject(flare);
      if (m_ParMainFire)
        m_ParMainFire.Stop();
      m_ParMainFire = ParticleManager.GetInstance().PlayOnObject(m_ParticleId, flare);
      m_ParMainFire.SetWiggle(7, 0.3);
      flare.PlaySoundSetLoop(m_BurningSound, "roadflareLoop_SoundSet", 0, 0);
    }
    if (GetGame().IsServer())
    {
      // Create and load noise parameters
      m_NoisePar = new NoiseParams();
      m_NoisePar.LoadFromPath("cfgWeapons Flaregun_Base NoiseFlare");
    }
  }
References GetGame(), m_BurningSound, m_FlareLight, m_NoisePar, m_ParMainFire, m_ParticleId, m_ScriptedLight, NoiseParams(), ParticleManager(), Particle::SetWiggle(), Particle::Stop(), and Vector().
OnFire()
void FlareSimulation::OnFire (Entity flare) inline protected
Definition at line 53 of file FlareSimulation.c.
  {
    //m_ParMainFire = ParticleManager.GetInstance().PlayOnObject( ParticleList.FLAREPROJ_FIRE, flare);
    //m_ParMainFire.SetWiggle( 7, 0.3);
  }
OnTermination()
void FlareSimulation::OnTermination (Entity flare) inline protected
Definition at line 48 of file FlareSimulation.c.
  {
    //MiscGameplayFunctions.GenerateAINoiseAtPosition(flare.GetPosition(), NOISE_DELAY, m_NoisePar);
  }
Simulate()
void FlareSimulation::Simulate (Entity flare) inline protected
Definition at line 59 of file FlareSimulation.c.
  {
    DayZPlayer player = GetGame().GetPlayer();
    if (player)
      vector playerPos = player.GetPosition();
    float dist = vector.DistanceSq(flare.GetPosition(), playerPos);
    if ((dist <= MAX_FARLIGHT_DIST * MAX_FARLIGHT_DIST) && (dist > MIN_FARLIGHT_DIST * MIN_FARLIGHT_DIST))
      m_ParMainFire.SetParameter(0, EmitorParam.SIZE, MiscGameplayFunctions.Normalize(dist, MAX_FARLIGHT_DIST * MAX_FARLIGHT_DIST));
    if (dist <= MIN_FARLIGHT_DIST * MIN_FARLIGHT_DIST)
      TurnOffDistantLight();
    //CastFlareAINoise( flare.GetPosition() );
  }
References vector::DistanceSq(), GetGame(), m_ParMainFire, MAX_FARLIGHT_DIST, MIN_FARLIGHT_DIST, Particle::SetParameter(), and TurnOffDistantLight().
TurnOffDistantLight()
void FlareSimulation::TurnOffDistantLight () inline protected
Definition at line 94 of file FlareSimulation.c.
  {
    if (m_ParMainFire)
    {
      m_ParMainFire.SetParameter(0, EmitorParam.LIFETIME, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.LIFETIME_RND, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.REPEAT, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.SIZE, 0);
    }
  }
References m_ParMainFire, and Particle::SetParameter().
Referenced by Simulate().
Member Data Documentation
m_BurningSound
EffectSound FlareSimulation::m_BurningSound protected
Definition at line 4 of file FlareSimulation.c.
Referenced by OnActivation(), and ~FlareSimulation().
m_FlareLight
FlareLight FlareSimulation::m_FlareLight protected
Definition at line 5 of file FlareSimulation.c.
Referenced by OnActivation(), and ~FlareSimulation().
m_LastNoiseTime
float FlareSimulation::m_LastNoiseTime = -1 protected
Definition at line 10 of file FlareSimulation.c.
Referenced by CastFlareAINoise().
m_NoisePar
ref NoiseParams FlareSimulation::m_NoisePar static protected
Definition at line 9 of file FlareSimulation.c.
Referenced by CastFlareAINoise(), and OnActivation().
m_NoiseTimer
float FlareSimulation::m_NoiseTimer = 0 protected
Definition at line 11 of file FlareSimulation.c.
Referenced by CastFlareAINoise().
m_ParMainFire
Particle FlareSimulation::m_ParMainFire protected
Definition at line 3 of file FlareSimulation.c.
Referenced by OnActivation(), Simulate(), TurnOffDistantLight(), and ~FlareSimulation().
m_ParticleId
int FlareSimulation::m_ParticleId static protected
Definition at line 15 of file FlareSimulation.c.
Referenced by FlareSimulation(), and OnActivation().
m_ScriptedLight
FlareSimulation::m_ScriptedLight static protected
Definition at line 14 of file FlareSimulation.c.
Referenced by FlareSimulation(), and OnActivation().
MAX_FARLIGHT_DIST
const float FlareSimulation::MAX_FARLIGHT_DIST = 40 static protected
Definition at line 6 of file FlareSimulation.c.
Referenced by Simulate().
MIN_FARLIGHT_DIST
const float FlareSimulation::MIN_FARLIGHT_DIST = 5 static protected
Definition at line 7 of file FlareSimulation.c.
Referenced by Simulate().
NOISE_DELAY
const float FlareSimulation::NOISE_DELAY = 5 protected
Definition at line 12 of file FlareSimulation.c.
Referenced by CastFlareAINoise().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/Firearms/FlareSimulation.c