DayZ: scripts/4_World/Entities/ManBase/DayZPlayer/DayZPlayerCamera_Base.c File Reference
DayZPlayerCamera_Base.c File Reference
Enumerations
enum NVTypes {
NONE = 0 , NV_GOGGLES , NV_GOGGLES_OFF , NV_OPTICS_ON ,
NV_OPTICS_OFF , NV_PUMPKIN , NV_OPTICS_KAZUAR_DAY , NV_OPTICS_KAZUAR_NIGHT ,
NV_OPTICS_STARLIGHT_DAY , NV_OPTICS_STARLIGHT_NIGHT , MAX
}
Functions
float Limit (float pV, float pMin, float pMax)
limit function
float fixAngle_PI_PI (float pAngle)
float fixAngle_180_180 (float pAngle)
void DayZPlayerCameraBase (DayZPlayer pPlayer, HumanInputController pInput)
constructor must be same
void HandleShoulderCameraOverride (HumanInputController pInput)
void ProcessCameraShake (float delta, out float leftRight, out float upDown)
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
float UpdateUDAngleUnlocked (out float pAngle, out float pAngleAdd, float pMin, float pMax, float pDt)
float UpdateLRAngleUnlocked (out float pAngle, out float pAngleAdd, float pMin, float pMax, float pDt)
float UpdateUDAngle (out float pAngle, out float pAngleAdd, float pMin, float pMax, float pDt)
float UpdateLRAngle (float pAngle, float pMin, float pMax, float pDt)
void StdFovUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
override void SpawnCameraShakeProper (float strength, float radius, float smoothness, float radius_decay_speed)
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
float GetWeaponSwayModifier ()
override string GetCameraName ()
void SetCameraPPDelay (DayZPlayerCamera pPrevCamera)
void SetCameraNV (bool nightvision)
bool IsCameraNV ()
void SetCameraNVType (int type)
int GetCameraNVType ()
void UpdateCameraNV (PlayerBase player)
void SetCameraPP (bool state, DayZPlayerCamera launchedFrom)
by default sets camera PP to zero, regardless of parameter. Override if needed.
override float GetCurrentYaw ()
override float GetCurrentPitch ()
override float GetCurrentRoll ()
void ForceFreelook (bool state)
void SetNVPostprocess (int NVtype)
DayZPlayerCameraOptics handles this separately, otherwise it takes active NVType from PlayerBase::GetCameraNVType.
void InitCameraOnPlayer (bool force=false)
Variables
enum NVTypes CONST_NEARPLANE_OPTICS_MIN = 0.04
Weapon_Base m_weaponUsed
ItemOptics m_opticsUsed
ref CameraShake m_CameraShake
float m_fLRAngleVel [1]
float m_fUDAngleVel [1]
float m_fFovAbsVel [1]
float m_fFovAbsolute
bool m_bForceFreeLook
float m_WeaponSwayModifier
float m_CameraPPDelay
float m_CurrentCameraYaw
float m_CurrentCameraPitch
float m_CurrentCameraRoll
HumanCommandWeapons m_CommandWeapons
bool m_IsNightvision
int m_NightvisionType
Enumeration Type Documentation
NVTypes
enum NVTypes
Enumerator
NONE
NV_GOGGLES
NV_GOGGLES_OFF
NV_OPTICS_ON
NV_OPTICS_OFF
NV_PUMPKIN
NV_OPTICS_KAZUAR_DAY
NV_OPTICS_KAZUAR_NIGHT
NV_OPTICS_STARLIGHT_DAY
NV_OPTICS_STARLIGHT_NIGHT
MAX
Definition at line 40 of file DayZPlayerCamera_Base.c.
{
  NONE = 0,
  NV_GOGGLES,
  NV_GOGGLES_OFF,
  NV_OPTICS_ON,
  NV_OPTICS_OFF,
  NV_PUMPKIN,
  NV_OPTICS_KAZUAR_DAY,
  NV_OPTICS_KAZUAR_NIGHT,
  NV_OPTICS_STARLIGHT_DAY,
  NV_OPTICS_STARLIGHT_NIGHT,
  MAX
}
Function Documentation
DayZPlayerCameraBase()
void DayZPlayerCameraBase (DayZPlayer pPlayer, HumanInputController pInput) protected
constructor must be same
Definition at line 64 of file DayZPlayerCamera_Base.c.
  {
    m_fLRAngleVel[0] = 0;
    m_fUDAngleVel[0] = 0;
    m_fFovAbsVel[0] = 0;
    m_WeaponSwayModifier = 1;
    m_fFovAbsolute = GetDayZGame().GetFOVByZoomType(m_pPlayer.GetEyeZoomLevel());
    /*
      {
      int perItemCamUD = pPlayer.GetCurrentPerItemCameraUD();
      string    a = "Per Item Camera User Data: " + perItemCamUD.ToString();
      Print(a);
      }
    */
    m_CameraPPDelay = 0;
    m_CommandWeapons = pPlayer.GetCommandModifier_Weapons();
    Init();
    HandleShoulderCameraOverride(pInput);
  };
References GetDayZGame(), DayZPlayer::GetEyeZoomLevel(), HandleShoulderCameraOverride(), Init(), m_CameraPPDelay, m_CommandWeapons, m_fFovAbsolute, m_fFovAbsVel, m_fLRAngleVel, m_fUDAngleVel, m_pPlayer, and m_WeaponSwayModifier.
fixAngle_180_180()
float fixAngle_180_180 (float pAngle)
Definition at line 26 of file DayZPlayerCamera_Base.c.
{
  while (pAngle > 180)
    pAngle -= 360;
  while (pAngle < -180)
    pAngle += 360;
  return pAngle;
}
Referenced by UIScriptedMenu::SetCameraData().
fixAngle_PI_PI()
float fixAngle_PI_PI (float pAngle)
Definition at line 13 of file DayZPlayerCamera_Base.c.
{
  while (pAngle > Math.PI)
    pAngle -= Math.PI2;
  while (pAngle < -Math.PI)
    pAngle += Math.PI2;
  return pAngle;
}
References Math::PI, and Math::PI2.
ForceFreelook()
void ForceFreelook (bool state) protected
Definition at line 417 of file DayZPlayerCamera_Base.c.
  {
    m_bForceFreeLook = state;
  }
References m_bForceFreeLook.
GetCameraName()
override string GetCameraName () protected
Definition at line 345 of file DayZPlayerCamera_Base.c.
  {
    return "DayZPlayerCameraBase";
  }
GetCameraNVType()
int GetCameraNVType () protected
Definition at line 369 of file DayZPlayerCamera_Base.c.
  {
    return m_NightvisionType;
  }
References m_NightvisionType.
Referenced by SetCameraPP(), DayZPlayerCameraBase::SetCameraPP(), and UpdateCameraNV().
GetCurrentPitch()
override float GetCurrentPitch () protected
Definition at line 407 of file DayZPlayerCamera_Base.c.
  {
    return m_CurrentCameraPitch;
  }
References m_CurrentCameraPitch.
GetCurrentRoll()
override float GetCurrentRoll () protected
Definition at line 412 of file DayZPlayerCamera_Base.c.
  {
    return m_CurrentCameraRoll;
  }
References m_CurrentCameraRoll.
GetCurrentYaw()
override float GetCurrentYaw () protected
Definition at line 402 of file DayZPlayerCamera_Base.c.
  {
    return m_CurrentCameraYaw;
  }
References m_CurrentCameraYaw.
GetWeaponSwayModifier()
float GetWeaponSwayModifier () protected
Definition at line 340 of file DayZPlayerCamera_Base.c.
  {
    return m_WeaponSwayModifier;
  }
References m_WeaponSwayModifier.
HandleShoulderCameraOverride()
void HandleShoulderCameraOverride (HumanInputController pInput) protected
disable override
Definition at line 88 of file DayZPlayerCamera_Base.c.
  {
    m_pInput.Override3rdIsRightShoulder(HumanInputControllerOverrideType.DISABLED, false);
  }
References m_pInput, and HumanInputController::Override3rdIsRightShoulder().
Referenced by DayZPlayerCameraBase().
Init()
void Init () protected
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
pre-init arrays
Definition at line 105 of file DayZPlayerCamera_Base.c.
  {
    PlayerBase player = PlayerBase.Cast(m_pPlayer);
    if (player && player.IsNVGWorking() != IsCameraNV())
    {
      SetCameraNV(player.IsNVGWorking());
      SetCameraNVType(player.GetNVType());
    }
  }
References IsCameraNV(), m_pPlayer, SetCameraNV(), and SetCameraNVType().
InitCameraOnPlayer()
void InitCameraOnPlayer (bool force = false) protected
Definition at line 506 of file DayZPlayerCamera_Base.c.
  {
    PlayerBase player = PlayerBase.Cast(m_pPlayer);
    if (!player.GetCurrentPlayerCamera() || (force && player.GetCurrentPlayerCamera() != this))
      player.OnCameraChanged(this);
  }
References m_pPlayer.
Referenced by OnActivate(), DayZPlayerCameraBase::OnUpdate(), and OnUpdate().
IsCameraNV()
bool IsCameraNV () protected
Definition at line 359 of file DayZPlayerCamera_Base.c.
  {
    return m_IsNightvision;
  }
References m_IsNightvision.
Referenced by Init(), OnActivate(), SetCameraPP(), DayZPlayerCameraBase::SetCameraPP(), and UpdateCameraNV().
Limit()
float Limit (float pV, float pMin, float pMax)
limit function
Definition at line 2 of file DayZPlayerCamera_Base.c.
{
  if (pV >= pMin && pV <= pMax)
    return pV;
  else if (pV < pMin)
    return pMin;
  else
    return pMax;
}
Referenced by UpdateLRAngle(), UpdateLRAngleLookAt(), UpdateLRAngleUnlocked(), UpdateUDAngle(), and UpdateUDAngleUnlocked().
OnActivate()
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult) protected
Definition at line 326 of file DayZPlayerCamera_Base.c.
  {
    InitCameraOnPlayer(true);
    SetCameraPPDelay(pPrevCamera);
    if (DayZPlayerCameraBase.Cast(pPrevCamera) && DayZPlayerCameraBase.Cast(pPrevCamera).IsCameraNV() && !IsCameraNV())
      PPERequesterBank.GetRequester(PPERequesterBank.REQ_CAMERANV).Start(new Param1<int>(PPERequester_CameraNV.NV_TRANSITIVE));
    GetGame().GetCallQueue(CALL_CATEGORY_GUI).CallLater(SetCameraPP, m_CameraPPDelay * 1000, false, true, this); // this takes care of weapon/optics postprocessing
    DayZPlayerCameraOptics optic_camera;
    if (DayZPlayerCamera.CastTo(optic_camera, pPrevCamera))
      GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(PlayerBase.Cast(m_pPlayer).HideClothing, null, false);
  }
References CALL_CATEGORY_GUI, DayZPlayerCamera(), DayZPlayerCameraOptics(), GetGame(), InitCameraOnPlayer(), IsCameraNV(), m_CameraPPDelay, m_pPlayer, DayZPlayerCameraBase::SetCameraPP(), and DayZPlayerCameraBase::SetCameraPPDelay().
OnUpdate()
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult) protected
Definition at line 306 of file DayZPlayerCamera_Base.c.
  {
    if (!m_pPlayer || !PlayerBase.Cast(m_pPlayer))
    {
      Debug.Log("DayZPlayerCameraBase | OnUpdate | no player!");
      return;
    }
    if (PlayerBase.Cast(m_pPlayer).GetCurrentCamera() != this)
    {
      //Print("DayZPlayerCameraBase | OnUpdate | unused camera! | " + this + "/" + PlayerBase.Cast(m_pPlayer).GetCurrentCamera());
      return;
    }
    super.OnUpdate(pDt, pOutResult);
    StdFovUpdate(pDt, pOutResult);
    UpdateCameraNV(PlayerBase.Cast(m_pPlayer));
    InitCameraOnPlayer();
  }
References InitCameraOnPlayer(), Debug::Log(), m_pPlayer, StdFovUpdate(), and UpdateCameraNV().
ProcessCameraShake()
void ProcessCameraShake (float delta, out float leftRight, out float upDown) protected
Definition at line 94 of file DayZPlayerCamera_Base.c.
  {
    if (m_CameraShake)
    {
      float x, y;
      m_CameraShake.Update(delta, x, y);
      leftRight += x;
      upDown += y;
    }
  }
References m_CameraShake, x, and y.
Referenced by DayZPlayerCameraBase::OnUpdate().
SetCameraNV()
void SetCameraNV (bool nightvision) protected
Definition at line 354 of file DayZPlayerCamera_Base.c.
  {
    m_IsNightvision = nightvision;
  }
References m_IsNightvision.
Referenced by Init(), SetCameraPP(), and UpdateCameraNV().
SetCameraNVType()
void SetCameraNVType (int type) protected
Definition at line 364 of file DayZPlayerCamera_Base.c.
  {
    m_NightvisionType = type;
  }
References m_NightvisionType.
Referenced by Init(), and UpdateCameraNV().
SetCameraPP()
void SetCameraPP (bool state, DayZPlayerCamera launchedFrom) protected
by default sets camera PP to zero, regardless of parameter. Override if needed.
Definition at line 388 of file DayZPlayerCamera_Base.c.
  {
    PPERequesterBank.GetRequester(PPERequester_CameraADS).Stop();
    if (IsCameraNV())
      SetNVPostprocess(GetCameraNVType());
    else
      SetNVPostprocess(NVTypes.NONE);
    m_weaponUsed = Weapon_Base.Cast(m_pPlayer.GetHumanInventory().GetEntityInHands());
    if (m_weaponUsed)
      m_weaponUsed.HideWeaponBarrel(false);
  }
References GetCameraNVType(), IsCameraNV(), m_pPlayer, m_weaponUsed, and SetNVPostprocess().
SetCameraPPDelay()
void SetCameraPPDelay (DayZPlayerCamera pPrevCamera) protected
Definition at line 350 of file DayZPlayerCamera_Base.c.
  {
  }
SetNVPostprocess()
void SetNVPostprocess (int NVtype) protected
DayZPlayerCameraOptics handles this separately, otherwise it takes active NVType from PlayerBase::GetCameraNVType.
Definition at line 424 of file DayZPlayerCamera_Base.c.
  {
    //Print("+++Setting NV type: " + NVtype + " +++");
    switch (NVtype)
    {
    case NVTypes.NONE:
    {
      PPERequesterBank.GetRequester(PPERequester_CameraNV).Stop();
      if (GetGame().GetMission() && GetGame().GetMission().GetEffectWidgets())
      {
        GetGame().GetMission().GetEffectWidgets().RemoveActiveEffects({EffectWidgetsTypes.NVG_OCCLUDER});
        GetGame().GetMission().GetEffectWidgets().RemoveActiveEffects({EffectWidgetsTypes.PUMPKIN_OCCLUDER});
      }
    }
    break;
    //night-vision modes
    case NVTypes.NV_OPTICS_KAZUAR_NIGHT:
    case NVTypes.NV_OPTICS_STARLIGHT_NIGHT:
    case NVTypes.NV_OPTICS_ON:
    {
      PPERequesterBank.GetRequester(PPERequesterBank.REQ_CAMERANV).Start(new Param1<int>(PPERequester_CameraNV.NV_DEFAULT_OPTICS));
      if (GetGame().GetMission() && GetGame().GetMission().GetEffectWidgets())
      {
        GetGame().GetMission().GetEffectWidgets().RemoveActiveEffects({EffectWidgetsTypes.NVG_OCCLUDER});
        GetGame().GetMission().GetEffectWidgets().RemoveActiveEffects({EffectWidgetsTypes.PUMPKIN_OCCLUDER});
      }
    }
    break;
    //daytime filter modes
    case NVTypes.NV_OPTICS_KAZUAR_DAY:
    case NVTypes.NV_OPTICS_STARLIGHT_DAY:
    {
      PPERequesterBank.GetRequester(PPERequesterBank.REQ_CAMERANV).Start(new Param1<int>(PPERequester_CameraNV.NV_DAYTIME_OPTICS));
      if (GetGame().GetMission() && GetGame().GetMission().GetEffectWidgets())
      {
        GetGame().GetMission().GetEffectWidgets().RemoveActiveEffects({EffectWidgetsTypes.NVG_OCCLUDER});
        GetGame().GetMission().GetEffectWidgets().RemoveActiveEffects({EffectWidgetsTypes.PUMPKIN_OCCLUDER});
      }
    }
    break;
    case NVTypes.NV_GOGGLES_OFF:
    case NVTypes.NV_OPTICS_OFF:
    {
      PPERequesterBank.GetRequester(PPERequesterBank.REQ_CAMERANV).Start(new Param1<int>(PPERequester_CameraNV.NV_NO_BATTERY));
      if (GetGame().GetMission() && GetGame().GetMission().GetEffectWidgets())
      {
        GetGame().GetMission().GetEffectWidgets().RemoveActiveEffects({EffectWidgetsTypes.NVG_OCCLUDER});
        GetGame().GetMission().GetEffectWidgets().RemoveActiveEffects({EffectWidgetsTypes.PUMPKIN_OCCLUDER});
      }
    }
    break;
    case NVTypes.NV_GOGGLES:
    {
      PPERequesterBank.GetRequester(PPERequesterBank.REQ_CAMERANV).Start(new Param1<int>(PPERequester_CameraNV.NV_DEFAULT_GLASSES));
      if (GetGame().GetMission() && GetGame().GetMission().GetEffectWidgets())
      {
        GetGame().GetMission().GetEffectWidgets().AddActiveEffects({EffectWidgetsTypes.NVG_OCCLUDER});
        GetGame().GetMission().GetEffectWidgets().RemoveActiveEffects({EffectWidgetsTypes.PUMPKIN_OCCLUDER});
      }
    }
    break;
    case NVTypes.NV_PUMPKIN:
    {
      PPERequesterBank.GetRequester(PPERequesterBank.REQ_CAMERANV).Start(new Param1<int>(PPERequester_CameraNV.NV_PUMPKIN));
      if (GetGame().GetMission() && GetGame().GetMission().GetEffectWidgets())
      {
        GetGame().GetMission().GetEffectWidgets().AddActiveEffects({EffectWidgetsTypes.PUMPKIN_OCCLUDER});
        GetGame().GetMission().GetEffectWidgets().RemoveActiveEffects({EffectWidgetsTypes.NVG_OCCLUDER});
      }
    }
    break;
    }
    if (PlayerBaseClient.Cast(m_pPlayer))
      PlayerBaseClient.Cast(m_pPlayer).SwitchPersonalLight(NVtype < 1);
  }
References GetGame(), and m_pPlayer.
Referenced by SetCameraPP(), and DayZPlayerCameraBase::SetCameraPP().
SpawnCameraShakeProper()
override void SpawnCameraShakeProper (float strength, float radius, float smoothness, float radius_decay_speed) protected
Definition at line 301 of file DayZPlayerCamera_Base.c.
  {
    m_CameraShake = new CameraShake(strength, radius, smoothness, radius_decay_speed);
  }
References m_CameraShake.
Referenced by SpawnCameraShake(), and SpawnDiagCameraShake().
StdFovUpdate()
void StdFovUpdate (float pDt, out DayZPlayerCameraResult pOutResult) protected
change abs FOV for naked eye zoom
switch shooting from camera to weapon (firearms)
Definition at line 274 of file DayZPlayerCamera_Base.c.
  {
    switch (m_pPlayer.GetEyeZoomLevel())
    {
    // ordered in likelihood of occurance for perf. reasons
    case ECameraZoomType.NONE:
      m_fFovAbsolute = Math.SmoothCD(m_fFovAbsolute, GetDayZGame().GetFOVByZoomType(ECameraZoomType.NONE), m_fFovAbsVel, 0.1, 1000, pDt);
      break;
    case ECameraZoomType.NORMAL:
      m_fFovAbsolute = Math.SmoothCD(m_fFovAbsolute, GetDayZGame().GetFOVByZoomType(ECameraZoomType.NORMAL), m_fFovAbsVel, 0.1, 1000, pDt);
      break;
    case ECameraZoomType.SHALLOW:
      m_fFovAbsolute = Math.SmoothCD(m_fFovAbsolute, GetDayZGame().GetFOVByZoomType(ECameraZoomType.SHALLOW), m_fFovAbsVel, 0.1, 1000, pDt);
      break;
    default:
      m_fFovAbsolute = Math.SmoothCD(m_fFovAbsolute, GetDayZGame().GetFOVByZoomType(ECameraZoomType.NONE), m_fFovAbsVel, 0.1, 1000, pDt);
      break;
    }
    pOutResult.m_fFovAbsolute = m_fFovAbsolute;
    if (!m_pPlayer.IsShootingFromCamera())
      pOutResult.m_fShootFromCamera = 0.0;
  }
References GetDayZGame(), DayZPlayer::GetEyeZoomLevel(), DayZPlayer::IsShootingFromCamera(), m_fFovAbsolute, m_fFovAbsVel, m_pPlayer, and Math::SmoothCD().
Referenced by DayZPlayerCameraBase::OnUpdate(), and OnUpdate().
UpdateCameraNV()
void UpdateCameraNV (PlayerBase player) protected
Definition at line 374 of file DayZPlayerCamera_Base.c.
  {
    if (!player)
      return;
    if (player.IsNVGWorking() != IsCameraNV() || player.GetNVType() != GetCameraNVType())
    {
      SetCameraNV(player.IsNVGWorking());
      SetCameraNVType(player.GetNVType());
      SetCameraPP(true, this);
    }
  }
References GetCameraNVType(), IsCameraNV(), SetCameraNV(), SetCameraNVType(), and DayZPlayerCameraBase::SetCameraPP().
Referenced by DayZPlayerCameraBase::OnUpdate(), and OnUpdate().
UpdateLRAngle()
float UpdateLRAngle (float pAngle, float pMin, float pMax, float pDt) protected
lr angle
Definition at line 241 of file DayZPlayerCamera_Base.c.
  {
    if (m_pInput.CameraIsFreeLook() || m_bForceFreeLook)
    {
      pAngle += m_pInput.GetAimChange()[0] * Math.RAD2DEG;
      pAngle = Limit(pAngle, pMin, pMax);
      m_fLRAngleVel[0] = 0; // reset filter
    }
    else
    {
      if (m_pInput.CameraIsTracking())
      {
        pAngle = m_pInput.GetTracking()[0] * Math.RAD2DEG;
        pAngle = Limit(-pAngle, pMin, pMax);
        m_fLRAngleVel[0] = 0; // reset filter
      }
      else
      {
        // smooth value back to 0
        pAngle = Math.SmoothCD(pAngle, 0, m_fLRAngleVel, 0.14, 1000, pDt);
        // m_fLeftRightAngle  = 0.9 * (1.0 - pDt);
      }
    }
    return pAngle;
  }
References HumanInputController::CameraIsFreeLook(), HumanInputController::CameraIsTracking(), HumanInputController::GetAimChange(), HumanInputController::GetTracking(), Limit(), m_bForceFreeLook, m_fLRAngleVel, m_pInput, Math::RAD2DEG, and Math::SmoothCD().
UpdateLRAngleUnlocked()
float UpdateLRAngleUnlocked (out float pAngle, out float pAngleAdd, float pMin, float pMax, float pDt) protected
Definition at line 152 of file DayZPlayerCamera_Base.c.
  {
    float target = 0;
    if (m_pInput.CameraIsTracking())
    {
      pAngleAdd = m_pInput.GetTracking()[0] * Math.RAD2DEG;
      pAngle = target;
      m_fUDAngleVel[0] = 0;
    }
    else
    {
      if (Math.AbsFloat(pAngleAdd) > 0.001)
      {
        pAngleAdd = pAngle + pAngleAdd - target;
        pAngle = target;
      }
      if (m_pInput.CameraIsFreeLook() || m_bForceFreeLook)
      {
        pAngleAdd += m_pInput.GetAimDelta(pDt)[0] * Math.RAD2DEG;
        m_fLRAngleVel[0] = 0;
      }
      else
        pAngleAdd = Math.SmoothCD(pAngleAdd, 0.0, m_fLRAngleVel, 0.14, 1000, pDt);
      pAngleAdd = pAngleAdd + pAngle;
    }
    pAngle = Limit(pAngle, pMin, pMax);
    pAngleAdd = Limit(pAngle + pAngleAdd, pMin, pMax) - pAngle;
    return pAngle + pAngleAdd;
  }
References Math::AbsFloat(), HumanInputController::CameraIsFreeLook(), HumanInputController::CameraIsTracking(), HumanInputController::GetAimDelta(), HumanInputController::GetTracking(), Limit(), m_bForceFreeLook, m_fLRAngleVel, m_fUDAngleVel, m_pInput, Math::RAD2DEG, and Math::SmoothCD().
Referenced by DayZPlayerCameraBase::OnUpdate(), and OnUpdate().
UpdateUDAngle()
float UpdateUDAngle (out float pAngle, out float pAngleAdd, float pMin, float pMax, float pDt) protected
pAngle + pAngleAdd == aimingUDAngle + aimingUDAdd now we set pAngleAdd to be the differenc from aimingAngle and we change camera angle to be the aiming angle
lr angle
update it in degrees
Definition at line 189 of file DayZPlayerCamera_Base.c.
  {
    if (Math.AbsFloat(pAngleAdd) > 0.001)
    {
      float aimingUDAngle = m_CommandWeapons.GetBaseAimingAngleUD();
      // override actual angle
      pAngleAdd = pAngle + pAngleAdd - aimingUDAngle;
      pAngle = aimingUDAngle;
      // Print("Angle: " + pAngle.ToString() + " Aim: " + actualUDAngle.ToString() );
    }
    if (m_pInput.CameraIsFreeLook())
    {
      pAngleAdd += m_pInput.GetAimChange()[1] * Math.RAD2DEG;
      pAngleAdd = Limit(pAngleAdd, pMin, pMax);
      m_fUDAngleVel[0] = 0;
    }
    else
    {
      if (m_pInput.CameraIsTracking())
      {
        pAngleAdd = m_pInput.GetTracking()[1] * Math.RAD2DEG;
        pAngleAdd = Limit(pAngleAdd, pMin, pMax);
        m_fUDAngleVel[0] = 0;
      }
      else
      {
        pAngle += m_pInput.GetAimChange()[1] * Math.RAD2DEG;
        pAngle = Limit(pAngle, pMin, pMax);
        pAngleAdd = Math.SmoothCD(pAngleAdd, 0, m_fUDAngleVel, 0.14, 1000, pDt);
      }
    }
    /*{
      float change = m_pInput.GetAimChange()[1] * Math.RAD2DEG;
      Print ("Script: Camera ud angle: " +  pAngle.ToString() + " change: " + change.ToString() );
      }*/
    return Limit(pAngle + pAngleAdd, pMin, pMax);
  }
References Math::AbsFloat(), HumanInputController::CameraIsFreeLook(), HumanInputController::CameraIsTracking(), HumanInputController::GetAimChange(), HumanCommandWeapons::GetBaseAimingAngleUD(), HumanInputController::GetTracking(), Limit(), m_CommandWeapons, m_fUDAngleVel, m_pInput, Math::RAD2DEG, and Math::SmoothCD().
UpdateUDAngleUnlocked()
float UpdateUDAngleUnlocked (out float pAngle, out float pAngleAdd, float pMin, float pMax, float pDt) protected
Definition at line 115 of file DayZPlayerCamera_Base.c.
  {
    float target = m_CommandWeapons.GetBaseAimingAngleUD();
    if (m_pInput.CameraIsTracking())
    {
      pAngleAdd = m_pInput.GetTracking()[1] * Math.RAD2DEG;
      pAngle = target;
      m_fUDAngleVel[0] = 0;
    }
    else
    {
      if (Math.AbsFloat(pAngleAdd) > 0.001)
      {
        pAngleAdd = pAngle + pAngleAdd - target;
        pAngle = target;
      }
      if (m_pInput.CameraIsFreeLook())
      {
        pAngleAdd += m_pInput.GetAimDelta(pDt)[1] * Math.RAD2DEG;
        m_fUDAngleVel[0] = 0;
      }
      else
        pAngleAdd = Math.SmoothCD(pAngleAdd, 0.0, m_fUDAngleVel, 0.14, 1000, pDt);
      if (!m_pInput.CameraIsFreeLook())
        pAngle += m_pInput.GetAimDelta(pDt)[1] * Math.RAD2DEG;
    }
    pAngle = Limit(pAngle, pMin, pMax);
    pAngleAdd = Limit(pAngle + pAngleAdd, pMin, pMax) - pAngle;
    return pAngle + pAngleAdd;
  }
References Math::AbsFloat(), HumanInputController::CameraIsFreeLook(), HumanInputController::CameraIsTracking(), HumanInputController::GetAimDelta(), HumanCommandWeapons::GetBaseAimingAngleUD(), HumanInputController::GetTracking(), Limit(), m_CommandWeapons, m_fUDAngleVel, m_pInput, Math::RAD2DEG, and Math::SmoothCD().
Referenced by DayZPlayerCameraBase::OnUpdate(), and OnUpdate().
Variable Documentation
CONST_NEARPLANE_OPTICS_MIN
enum NVTypes CONST_NEARPLANE_OPTICS_MIN = 0.04
m_bForceFreeLook
bool m_bForceFreeLook protected
Definition at line 517 of file DayZPlayerCamera_Base.c.
Referenced by ForceFreelook(), UpdateLRAngle(), UpdateLRAngleLookAt(), and UpdateLRAngleUnlocked().
m_CameraPPDelay
float m_CameraPPDelay protected
Definition at line 519 of file DayZPlayerCamera_Base.c.
Referenced by DayZPlayerCameraBase(), OnActivate(), DayZPlayerCameraBase::SetCameraPPDelay(), and SetCameraPPDelay().
m_CameraShake
ref CameraShake m_CameraShake protected
Definition at line 61 of file DayZPlayerCamera_Base.c.
Referenced by DayZPlayerCameraBase::OnUpdate(), ProcessCameraShake(), and SpawnCameraShakeProper().
m_CommandWeapons
HumanCommandWeapons m_CommandWeapons protected
Definition at line 525 of file DayZPlayerCamera_Base.c.
Referenced by DayZPlayerCameraBase(), UpdateUDAngle(), and UpdateUDAngleUnlocked().
m_CurrentCameraPitch
float m_CurrentCameraPitch protected
Definition at line 522 of file DayZPlayerCamera_Base.c.
Referenced by GetCurrentPitch(), DayZPlayerCameraBase::OnUpdate(), and OnUpdate().
m_CurrentCameraRoll
float m_CurrentCameraRoll protected
Definition at line 523 of file DayZPlayerCamera_Base.c.
Referenced by DayZPlayerCameraBase::DayZPlayerCamera3rdPerson(), GetCurrentRoll(), and OnUpdate().
m_CurrentCameraYaw
float m_CurrentCameraYaw protected
Definition at line 521 of file DayZPlayerCamera_Base.c.
Referenced by GetCurrentYaw(), DayZPlayerCameraBase::OnUpdate(), and OnUpdate().
m_fFovAbsolute
float m_fFovAbsolute protected
Definition at line 516 of file DayZPlayerCamera_Base.c.
m_fFovAbsVel
float m_fFovAbsVel[1] protected
Definition at line 515 of file DayZPlayerCamera_Base.c.
Referenced by DayZPlayerCameraBase(), DayZPlayerCameraBase::HoldBreathFOVEffect(), HoldBreathFOVEffect(), and StdFovUpdate().
m_fLRAngleVel
float m_fLRAngleVel[1] protected
Definition at line 513 of file DayZPlayerCamera_Base.c.
Referenced by DayZPlayerCameraBase(), UpdateLRAngle(), UpdateLRAngleLookAt(), and UpdateLRAngleUnlocked().
m_fUDAngleVel
float m_fUDAngleVel[1] protected
Definition at line 514 of file DayZPlayerCamera_Base.c.
Referenced by DayZPlayerCameraBase(), UpdateLRAngleUnlocked(), UpdateUDAngle(), and UpdateUDAngleUnlocked().
m_IsNightvision
bool m_IsNightvision protected
Definition at line 526 of file DayZPlayerCamera_Base.c.
Referenced by IsCameraNV(), and SetCameraNV().
m_NightvisionType
int m_NightvisionType protected
Definition at line 527 of file DayZPlayerCamera_Base.c.
Referenced by GetCameraNVType(), and SetCameraNVType().
m_opticsUsed
ItemOptics m_opticsUsed protected
Definition at line 60 of file DayZPlayerCamera_Base.c.
Referenced by AdjustCameraParameters(), DayZPlayerCameraBase::GetCurrentSightEntity(), GetCurrentSightEntity(), DayZPlayerCameraBase::GetCurrentSightInfo(), GetCurrentSightInfo(), Init(), OnActivate(), DayZPlayerCameraBase::SetCameraPP(), SetCameraPP(), and DayZPlayerCameraBase::SetupSightEntities().
m_WeaponSwayModifier
float m_WeaponSwayModifier protected
Definition at line 518 of file DayZPlayerCamera_Base.c.
Referenced by DayZPlayerCameraBase::DayZPlayerCamera3rdPerson(), DayZPlayerCameraBase(), DayZPlayerCameraBase::DayZPlayerCameraIronsights(), and GetWeaponSwayModifier().
m_weaponUsed
Weapon_Base m_weaponUsed protected
Definition at line 59 of file DayZPlayerCamera_Base.c.
Referenced by DayZPlayerCameraBase::GetCurrentSightEntity(), DayZPlayerCameraBase::GetCurrentSightInfo(), SetCameraPP(), DayZPlayerCameraBase::SetCameraPP(), and DayZPlayerCameraBase::SetupSightEntities().