DayZ: BroomBase Class Reference
BroomBase Class Reference
Private Member Functions
override void Init ()
override void SetActions ()
override bool CanReceiveUpgrade ()
override void OnWorkStart ()
override void ApplyResultModifications (ItemBase result)
override bool CanTransformIntoStick ()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
override void CalculateQuantity ()
override void UpdateParticle ()
void DebugSetHealthAndEnergy (float time)
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
override bool OnAction (int action_id, Man player, ParamsReadContext ctx)
Private Member Functions inherited from FlammableBase
override void DeferredInit ()
void Init ()
override void EEInit ()
override vector GetUniversalTemperatureSourcePosition ()
override void EEDelete (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanPutInCargo (EntityAI parent)
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
bool CanBeTakenAsCargo ()
override bool IsIgnited ()
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
bool IsRagDryEnough (ItemBase rag)
void UpdateCheckForReceivingUpgrade ()
override void OnIgnitedThis (EntityAI fire_source)
override void OnSwitchOn ()
override void OnSwitchOff ()
void SetTorchDecraftResult (string type)
bool ConsumeRag ()
void ConsumeLard (Lard lard)
void Upgrade (ItemBase source)
void ConsumeFuelFromBottle (ItemBase vessel)
void ConsumeFuelFromGasStation ()
void RuinRags ()
override void OnInventoryExit (Man player)
bool StandUp ()
void CalculateQuantity ()
bool CanReceiveUpgrade ()
void CraftingInit (float quantity)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
bool CanTransformIntoStick ()
void TryTransformIntoStick ()
override void OnWorkStart ()
void StopAllParticles ()
Rag GetRag ()
void LockRags (bool do_lock)
void UpdateLight ()
override void OnItemInHandsPlayerSwimStart (PlayerBase player)
override void OnWork (float consumed_energy)
string GetSoundName ()
void UpdateParticle ()
override void OnWorkStop ()
override int GetMeleeMode ()
override int GetMeleeHeavyMode ()
override int GetMeleeSprintMode ()
override void SetActions ()
override void OnAttachmentQuantityChangedEx (ItemBase item, float delta)
override bool DisassembleOnLastDetach ()
override void OnDebugSpawn ()
int GetRagQuantity ()
string GetBurningMaterial ()
string GetBurntMaterial ()
void UpdateMaterial ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
void ApplyResultModifications (ItemBase result)
Additional Inherited Members
Private Attributes inherited from FlammableBase
ref UniversalTemperatureSource m_UTSource
ref UniversalTemperatureSourceSettings m_UTSSettings
ref UniversalTemperatureSourceLambdaConstant m_UTSLConstant
Detailed Description
Definition at line 1 of file Broom.c.
Member Function Documentation
ApplyResultModifications()
override void BroomBase::ApplyResultModifications (ItemBase result) inline private
Definition at line 29 of file Broom.c.
  {
    result.SetHealth(result.GetHealthLevelValue(2, ""));
    result.SetQuantity(1);
  }
CalculateQuantity()
override void BroomBase::CalculateQuantity () inline private
Definition at line 52 of file Broom.c.
  {
    if (GetGame().IsServer())
    {
      float currentHealth01 = GetHealth01();
      float currentEnergy01 = GetCompEM().GetEnergy0To1();
      //Health needs to copy internal energy, but only if that means it will be going down from its current value(the item can't heal itself after obtaining damage just because it has full internal energy)
      SetHealth01("", "", Math.Min(currentHealth01, currentEnergy01));
      //Energy needs to copy health, but only if it is higher(in 01 terms) than health, that means if an item with full energy gets damaged and lit, the internal energy needs to be adjusted to follow the health. Situations where internal energy is lower than health are handled on the line above
      GetCompEM().SetEnergy0To1(GetHealth01());
    }
  }
References GetGame(), and Math::Min().
Referenced by OnWorkStart().
CanReceiveUpgrade()
override bool BroomBase::CanReceiveUpgrade () inline private
Definition at line 18 of file Broom.c.
  {
    return false;
  }
CanTransformIntoStick()
override bool BroomBase::CanTransformIntoStick () inline private
Definition at line 35 of file Broom.c.
  {
    if (GetGame().IsServer() && !IsIgnited() && GetEnergy() < 1 && !IsSetForDeletion())
      return true;
    else
      return false;
  }
References GetEnergy(), GetGame(), and FlammableBase::IsIgnited().
DebugSetHealthAndEnergy()
void BroomBase::DebugSetHealthAndEnergy (float time) inline private
Definition at line 83 of file Broom.c.
  {
    float max_energy = GetCompEM().GetEnergyMaxPristine();
    float health01 = Math.InverseLerp(0, max_energy, time);
    SetHealth01("", "", health01);
    GetCompEM().SetEnergy(time);
  }
References Math::InverseLerp().
Referenced by OnAction().
EEHitBy()
override void BroomBase::EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
Definition at line 44 of file Broom.c.
  {
    super.EEHitBy(damageResult, damageType, source, component, dmgZone, ammo, modelPos, speedCoef);
    GetCompEM().SetEnergy0To1(GetHealth01("", ""));
  }
References component.
GetDebugActions()
override void BroomBase::GetDebugActions (out TSelectableActionInfoArrayEx outputList) inline private
Definition at line 91 of file Broom.c.
  {
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.BROOM_BURN_VERY_SHORT, "SetBurnTimeTo15Secs", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.BROOM_BURN_SHORT, "SetBurnTimeTo1Min", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.BROOM_BURN_MEDIUM, "SetBurnTimeTo10Min", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.BROOM_BURN_LONG, "SetBurnTimeToMax", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.SEPARATOR, "___________________________", FadeColors.LIGHT_GREY));
    super.GetDebugActions(outputList);
  }
References SAT_DEBUG_ACTION.
Init()
override void BroomBase::Init () inline private
Definition at line 3 of file Broom.c.
  {
    super.Init();
    m_DecraftResult = "LongWoodenStick";
    m_ParticleLocalPos = Vector(0, 1.2, 0);
  }
References FlammableBase::m_DecraftResult, FlammableBase::m_ParticleLocalPos, and Vector().
OnAction()
override bool BroomBase::OnAction (int action_id, Man player, ParamsReadContext ctx) inline private
Definition at line 102 of file Broom.c.
  {
    if (super.OnAction(action_id, player, ctx))
      return true;
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      if (action_id == EActions.BROOM_BURN_VERY_SHORT)
      {
        DebugSetHealthAndEnergy(15);
        OnIgnitedThis(null);
      }
      else if (action_id == EActions.BROOM_BURN_SHORT)
      {
        DebugSetHealthAndEnergy(60);
        OnIgnitedThis(null);
      }
      else if (action_id == EActions.BROOM_BURN_MEDIUM)
      {
        DebugSetHealthAndEnergy(600);
        OnIgnitedThis(null);
      }
      else if (action_id == EActions.BROOM_BURN_LONG)
      {
        DebugSetHealthAndEnergy(GetCompEM().GetEnergyMaxPristine());
        OnIgnitedThis(null);
      }
    }
    return false;
  }
References DebugSetHealthAndEnergy(), GetGame(), and FlammableBase::OnIgnitedThis().
OnWorkStart()
override void BroomBase::OnWorkStart () inline private
Definition at line 23 of file Broom.c.
  {
    super.OnWorkStart();
    CalculateQuantity();
  }
References CalculateQuantity().
SetActions()
override void BroomBase::SetActions () inline private
Definition at line 10 of file Broom.c.
  {
    super.SetActions();
    AddAction(ActionClapBearTrapWithThisItem);
    AddAction(ActionBreakLongWoodenStick);
  }
References AddAction().
UpdateParticle()
override void BroomBase::UpdateParticle () inline private
Definition at line 66 of file Broom.c.
  {
    float normalizedQuant = GetQuantity() / GetQuantityMax();
    if (!m_FireParticle)
      m_FireParticle = ParticleManager.GetInstance().PlayOnObject(ParticleList.BROOM_TORCH_T1, this, m_ParticleLocalPos);
    m_FireParticle.ScaleParticleParamFromOriginal(EmitorParam.VELOCITY, 1.0);
    m_FireParticle.ScaleParticleParamFromOriginal(EmitorParam.VELOCITY_RND, 1.0);
    if (m_FireParticle)
    {
      float scale = Math.Max(normalizedQuant * 2.4, 0.4);
      m_FireParticle.ScaleParticleParamFromOriginal(EmitorParam.SIZE, scale);
    }
  }
References ParticleList::BROOM_TORCH_T1, GetQuantity(), GetQuantityMax(), FlammableBase::m_FireParticle, FlammableBase::m_ParticleLocalPos, Math::Max(), ParticleManager(), and Particle::ScaleParticleParamFromOriginal().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Gear/Tools/Broom.c