DayZ: Diag menu API definition
Diag menu API definition
Debug utilities » Debug Shape API definition
Classes
class DiagMenu
Functions
static proto bool DiagMenu::IsInitialized ()
Checks if DiagMenu is initialized.
static proto void DiagMenu::InitScriptDiags ()
To be used before registering scripted diags.
static proto void DiagMenu::ClearScriptDiags ()
To be used when scripted diags should not be present.
static proto void DiagMenu::RegisterMenu (int id, string name, int parent)
Register a new menu.
static proto void DiagMenu::RegisterItem (int id, string shortcut, string name, int parent, string values, func callback=null)
Register a new item.
static proto void DiagMenu::RegisterBool (int id, string shortcut, string name, int parent, bool reverse=false, func callback=null)
Register a new bool item.
static proto void DiagMenu::RegisterRange (int id, string shortcut, string name, int parent, string valuenames, func callback=null)
Register a new range item.
static proto void DiagMenu::Unregister (int id)
Unregister the item at given id.
static proto bool DiagMenu::IsRegistered (int id)
Check if the item at given id has been registered.
static proto bool DiagMenu::BindCallback (int id, func callback)
Bind a callback to the given id.
static proto void DiagMenu::UnbindCallback (int id)
Unbind the callback from the given id.
static proto bool DiagMenu::GetBool (int id, bool reverse=false)
Get value as bool from the given script id.
static proto int DiagMenu::GetValue (int id)
Get value as int from the given script id.
static proto void DiagMenu::SetValue (int id, int value)
Set value at the given script id.
static proto float DiagMenu::GetRangeValue (int id)
Get range value at the given script id.
static proto void DiagMenu::SetRangeValue (int id, float value)
Set range value at the given script id.
static proto int DiagMenu::GetEngineValue (int id)
Get value at the given engine id.
static proto void DiagMenu::SetEngineValue (int id, int value)
Set value at the given engine id.
static proto float DiagMenu::GetEngineRangeValue (int id)
Get range value at the given engine id.
static proto void DiagMenu::SetEngineRangeValue (int id, float value)
Set range value at the given engine id.
static proto bool DiagMenu::MenuExists (string name)
Check if a menu with supplied name already exists.
Variables
INFO
WARNING
ERROR
FIRSTCONTACT
NEARESTCONTACT ONLYSTATIC ONLYDYNAMIC ONLYWATER ALLOBJECTS
class DiagMenu Shape ()
don't call destructor directly. Use Destroy() instead
Detailed Description
Function Documentation
BindCallback()
static proto bool DiagMenu::BindCallback (int id, func callback) static private
Bind a callback to the given id.
Note
Only one callback can be registered, so when attempting to registering multiple, only the last one will be present
The callbacks are required to have one of following signatures
All Register... support: o static void Callback();
RegisterItem & RegisterBool: o static void Callback(int value); o static void Callback(int value, int id); o static void Callback(bool value); o static void Callback(bool value, int id);
RegisterRange: o static void Callback(float value); o static void Callback(float value, int id); o static void Callback(int value); o static void Callback(int value, int id);
Keep in mind that bool and int are interchangeable, so 'bool value' is possible for RegisterRange too
ClearScriptDiags()
static proto void DiagMenu::ClearScriptDiags () static private
To be used when scripted diags should not be present.
GetBool()
static proto bool DiagMenu::GetBool (int id, bool reverse = false) static private
Get value as bool from the given script id.
Referenced by ApplyEyeAcco(), CalculateEyeAccoTarget(), MissionBase::DisplayHairDebug(), ManBase::EEHitBy(), ActionTargets::FilterObstructedObjectsEx(), GatherSurfaces(), GetMeleeTargetEx(), Hologram::GetProjectionEntityPosition(), Hologram::IsCollidingBBox(), BaseBuildingBase::OnDebugSpawnBuildExcludes(), PlayerSoundEventBase::OnPlay(), Managed::OnScheduledTick(), EntityPlacementCallback::OnSetup(), SymptomManager::OnTick(), CGame::OnUpdate(), MissionBase::OnUpdate(), SpookyEventBase::Perform(), ProcessLighting(), SelectEvent(), DeveloperTeleport::TeleportAtCursor(), DeveloperTeleport::TeleportAtCursorEx(), Tick(), ScriptedWidgetEventHandler::Update(), UIScriptedMenu::Update(), and ActionMenu::UpdateWidgets().
GetEngineRangeValue()
static proto float DiagMenu::GetEngineRangeValue (int id) static private
Get range value at the given engine id.
Referenced by DayZPlayer::CommandHandlerDebug().
GetEngineValue()
static proto int DiagMenu::GetEngineValue (int id) static private
Get value at the given engine id.
Referenced by CheckShowMode(), DayZPlayer::CommandHandler(), and DayZPlayer::HeadingModel().
GetRangeValue()
static proto float DiagMenu::GetRangeValue (int id) static private
Get range value at the given script id.
GetValue()
static proto int DiagMenu::GetValue (int id) static private
Get value as int from the given script id.
Referenced by Weapon::LiftWeaponCheck(), and MissionBase::ShowHairDebugValues().
InitScriptDiags()
static proto void DiagMenu::InitScriptDiags () static private
To be used before registering scripted diags.
IsInitialized()
static proto bool DiagMenu::IsInitialized () static private
Checks if DiagMenu is initialized.
Referenced by ScriptedWidgetEventHandler::RandomizePageIndex().
IsRegistered()
static proto bool DiagMenu::IsRegistered (int id) static private
Check if the item at given id has been registered.
MenuExists()
static proto bool DiagMenu::MenuExists (string name) static private
Check if a menu with supplied name already exists.
RegisterBool()
static proto void DiagMenu::RegisterBool (int id, string shortcut, string name, int parent, bool reverse = false, func callback = null) static private
Register a new bool item.
Note
This is just a RegisterItem with value="true,false" or when reversed value="false,true"
Parameters
id int The unique ID of the item in the range [0,512]
shortcut string The keyboard shortcut of the item
name string The name of the item
parent string The index of the parent of the item
values string The values of the item, separated by commas
reverse bool Whether to reverse the bool (OPTIONAL)
callback func Callback to call when the value is changed (OPTIONAL) (Also read BindCallback)
RegisterItem()
static proto void DiagMenu::RegisterItem (int id, string shortcut, string name, int parent, string values, func callback = null) static private
Register a new item.
Parameters
id int The unique ID of the item in the range [0,512]
shortcut string The keyboard shortcut of the item
name string The name of the item
parent int The index of the parent of the item
values string The values of the item separated by commas, internally this will be an int starting at 0 for the first item
callback func Callback to call when the value is changed (OPTIONAL) (Also read BindCallback)
RegisterMenu()
static proto void DiagMenu::RegisterMenu (int id, string name, int parent) static private
Register a new menu.
Parameters
id int The unique ID of the menu in the range [0,512]
name string The name of the menu
parent int The index of the parent of the menu
RegisterRange()
static proto void DiagMenu::RegisterRange (int id, string shortcut, string name, int parent, string valuenames, func callback = null) static private
Register a new range item.
Parameters
id int The unique ID of the item in the range [0,512]
shortcut string The keyboard shortcut of the item
name string The name of the item
parent int The index of the parent of the item
values string Range specification in format "min,max,startValue,step"
callback func Callback to call when the value is changed (OPTIONAL) (Also read BindCallback)
SetEngineRangeValue()
static proto void DiagMenu::SetEngineRangeValue (int id, float value) static private
Set range value at the given engine id.
SetEngineValue()
static proto void DiagMenu::SetEngineValue (int id, int value) static private
Set value at the given engine id.
SetRangeValue()
static proto void DiagMenu::SetRangeValue (int id, float value) static private
Set range value at the given script id.
SetValue()
static proto void DiagMenu::SetValue (int id, int value) static private
Set value at the given script id.
Referenced by ManBase::SetBloodyHandsBase(), and SetModifiers().
UnbindCallback()
static proto void DiagMenu::UnbindCallback (int id) static private
Unbind the callback from the given id.
Unregister()
static proto void DiagMenu::Unregister (int id) static private
Unregister the item at given id.
Variable Documentation
ALLOBJECTS
ALLOBJECTS
Definition at line 5 of file EnDebug.c.
ERROR
ERROR
Definition at line 2 of file EnDebug.c.
FIRSTCONTACT
FIRSTCONTACT
Definition at line 0 of file EnDebug.c.
INFO
INFO
Definition at line 0 of file EnDebug.c.
Shape
class DiagMenu Shape ()
don't call destructor directly. Use Destroy() instead
Instance of created debug visualizer
Referenced by Transport::DebugFreeAreaAtDoor(), EntityAI::DebugFreeAreaAtDoor(), ComponentEnergyManager::DrawArrow(), Debug::DrawArrow(), Debug::DrawBoxEx(), Debug::DrawCube(), Debug::DrawCylinder(), Debug::DrawFrustum(), ScriptConsoleItemsTab::DrawItems(), ScriptConsoleItemsTab::DrawItemsClear(), Debug::DrawLine(), Debug::DrawLines(), Debug::DrawSphere(), Weapon::LiftWeaponCheck(), EntityPlacementCallback::OnDebug(), OnUpdate(), and Debug::RemoveShape().
WARNING
WARNING
Definition at line 1 of file EnDebug.c.