DayZ: scripts/3_Game/tools/LogTemplates.c File Reference
LogTemplates.c File Reference
Classes
class LogTemplates
Typedefs
typedef Param3< string, string, string > LogTemplate
typedef int LogTemplateID
Functions
class LogTemplates Log (string message, LogTemplateID template_id=0)
Creates debug log (optional) from LogTemplate which are registred.
void RegisterLogTamplate (LogTemplateID template_id, string author, string plugin, string label)
static void Init ()
static LogTemplate GetTemplate (LogTemplateID template_id)
void LogInfo (string message, LogTemplateID template_id=0)
Creates info log (optional) from LogTemplate which are registred.
void LogWarning (string message, LogTemplateID template_id=0)
Creates warning log (optional) from LogTemplate which are registred.
void LogError (string message, LogTemplateID template_id=0)
Creates error log (optional) from LogTemplate which are registred.
void SQFPrint (string sqf_msg)
void SQFLog (string sqf_msg)
Variables
ref map< LogTemplateID, ref LogTemplate > m_LogTemplates
static LogTemplateID TEMPLATE_UNKNOWN = 0
static LogTemplateID TEMPLATE_JANOSIK = 1
static LogTemplateID TEMPLATE_PLAYER_WEIGHT = 2
static LogTemplateID TEMPLATE_BROADCAST = 3
Typedef Documentation
LogTemplate
typedef Param3<string, string, string> LogTemplate
Definition at line 1 of file LogTemplates.c.
LogTemplateID
typedef int LogTemplateID
Definition at line 2 of file LogTemplates.c.
Function Documentation
GetTemplate()
static LogTemplate Log::GetTemplate (LogTemplateID template_id) static private
Definition at line 109 of file LogTemplates.c.
{
  LogTemplate log_template = LogTemplates.GetTemplate(template_id);
  Debug.LogError(message, log_template.param2, log_template.param1, log_template.param3);
}
void SQFPrint(string sqf_msg)
{
  Print(sqf_msg);
}
void SQFLog(string sqf_msg)
{
  Log(sqf_msg);
}
Init()
static void Log::Init () static private
Definition at line 97 of file LogTemplates.c.
{
  LogTemplate log_template = LogTemplates.GetTemplate(template_id);
Log()
class LogTemplates Log (string message, LogTemplateID template_id = 0)
Creates debug log (optional) from LogTemplate which are registred.
Parameters
template_id LogTemplateID ID of LogTemplate which was registred in proto/Logtemplate.h -> "class LogTemplates"
message string Debug message for log
Returns
void
Log("This is some debug log message", TEMPLATE_JINDRICH);
>> output to scriptExt.log (for GamutLogViewer)
Definition at line 2 of file LogTemplates.c.
{
  LogTemplate log_template = LogTemplates.GetTemplate(template_id);
  Debug.Log(message, log_template.param2, log_template.param1, log_template.param3);
}
Referenced by PluginBase::CheckInit(), Debug(), UIPopupScript::OnClick(), PluginFileHandler::SaveParameter(), and SQFLog().
LogError()
void LogError (string message, LogTemplateID template_id = 0)
Creates error log (optional) from LogTemplate which are registred.
Parameters
template_id LogTemplateID ID of LogTemplate which was registred in proto/Logtemplate.h -> "class LogTemplates"
message string Error message for log
Returns
void
LogT(TEMPLATE_JINDRICH, "This is some error log message");
>> output to scriptExt.log (for GamutLogViewer)
Definition at line 123 of file LogTemplates.c.
{
  LogTemplate log_template = LogTemplates.GetTemplate(template_id);
  Debug.LogError(message, log_template.param2, log_template.param1, log_template.param3);
}
References LogTemplates::GetTemplate(), and Debug::LogError().
Referenced by GameInventory::OnServerInventoryCommandStatic().
LogInfo()
void LogInfo (string message, LogTemplateID template_id = 0)
Creates info log (optional) from LogTemplate which are registred.
Parameters
template_id LogTemplateID ID of LogTemplate which was registred in proto/Logtemplate.h -> "class LogTemplates"
message string Info message for log
Returns
void
LogInfo("This is some info log message", TEMPLATE_JINDRICH);
>> output to scriptExt.log (for GamutLogViewer)
Definition at line 87 of file LogTemplates.c.
{
  LogTemplate log_template = LogTemplates.GetTemplate(template_id);
  Debug.LogInfo(message, log_template.param2, log_template.param1, log_template.param3);
}
References LogTemplates::GetTemplate(), and Debug::LogInfo().
LogWarning()
void LogWarning (string message, LogTemplateID template_id = 0)
Creates warning log (optional) from LogTemplate which are registred.
Parameters
template_id LogTemplateID ID of LogTemplate which was registred in proto/Logtemplate.h -> "class LogTemplates"
message string Warning message for log
Returns
void
LogT(TEMPLATE_JINDRICH, "This is some warning log message");
>> output to scriptExt.log (for GamutLogViewer)
Definition at line 105 of file LogTemplates.c.
{
  LogTemplate log_template = LogTemplates.GetTemplate(template_id);
  Debug.LogWarning(message, log_template.param2, log_template.param1, log_template.param3);
}
References LogTemplates::GetTemplate().
RegisterLogTamplate()
void Log::RegisterLogTamplate (LogTemplateID template_id, string author, string plugin, string label) static private
Definition at line 72 of file LogTemplates.c.
SQFLog()
void SQFLog (string sqf_msg)
Definition at line 135 of file LogTemplates.c.
{
  Log(sqf_msg);
}
References Log().
SQFPrint()
void SQFPrint (string sqf_msg)
Definition at line 130 of file LogTemplates.c.
{
  Print(sqf_msg);
}
References Print().
Variable Documentation
m_LogTemplates
ref map<LogTemplateID, ref LogTemplate> m_LogTemplates static private
Definition at line 70 of file LogTemplates.c.
TEMPLATE_BROADCAST
LogTemplateID TEMPLATE_BROADCAST = 3 static private
Definition at line 95 of file LogTemplates.c.
TEMPLATE_JANOSIK
LogTemplateID TEMPLATE_JANOSIK = 1 static private
Definition at line 93 of file LogTemplates.c.
TEMPLATE_PLAYER_WEIGHT
LogTemplateID TEMPLATE_PLAYER_WEIGHT = 2 static private
Definition at line 94 of file LogTemplates.c.
TEMPLATE_UNKNOWN
LogTemplateID TEMPLATE_UNKNOWN = 0 static private
Definition at line 92 of file LogTemplates.c.