DayZ: ScriptConsoleSoundsTab Class Reference
ScriptConsoleSoundsTab Class Reference
Protected Member Functions
void ScriptConsoleSoundsTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void ~ScriptConsoleSoundsTab (Widget root)
override bool OnChange (Widget w, int x, int y, bool finished)
void UpdateMousePos ()
void PrepareFilters (string filter, out TStringArray filters)
void ChangeFilter (TStringArray classes, TextListboxWidget widget, EditBoxWidget filterWidget, int categoryMask=-1, bool ignoreScope=false)
override void Update (float timeslice)
void HandleKeys ()
void SetMapPos (vector pos)
vector GetMapPos ()
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
TStringArray GetSoundClasses ()
void ChangeFilterSound ()
Protected Attributes
bool m_PlayerPosRefreshBlocked
vector m_MapPos
ButtonWidget m_CopySoundset
ButtonWidget m_PlaySoundset
ButtonWidget m_PlaySoundsetLooped
ButtonWidget m_StopSoundset
EditBoxWidget m_SoundFilter
TextListboxWidget m_SoundsTextListbox
ref Timer m_RefreshFilterTimer = new Timer()
MapWidget m_DebugMapWidget
TextWidget m_MapDistWidget
TextWidget m_MouseCurPos
TextWidget m_MapHeadingWidget
Static Protected Attributes
static float DEBUG_MAP_ZOOM = 1
static EffectSound m_SoundSet
Additional Inherited Members
Private Member Functions inherited from ScriptConsoleTabBase
void ScriptConsoleTabBase (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void Init (int id)
int GetID ()
Widget GetRoot ()
bool IsSelected ()
void Select (bool select, ScriptConsoleTabBase selectedHandler)
void OnSelected ()
void Show (bool show, ScriptConsoleTabBase selectedHandler)
Widget GetButton ()
void Update (float timeslice)
bool OnChange (Widget w, int x, int y, bool finished)
bool OnClick (Widget w, int x, int y, int button)
bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
bool OnKeyDown (Widget w, int x, int y, int key)
bool OnDoubleClick (Widget w, int x, int y, int button)
void OnRPCEx (int rpc_type, ParamsReadContext ctx)
bool OnMouseButtonDown (Widget w, int x, int y, int button)
bool OnKeyPress (Widget w, int x, int y, int key)
void AddItemToClipboard (TextListboxWidget text_listbox_widget)
Private Attributes inherited from ScriptConsoleTabBase
int m_Id
bool m_IsSelected
Widget m_ParentRoot
Widget m_Root
Widget m_Button
ScriptConsole m_ScriptConsole
ScriptConsoleTabBase m_Parent
PluginConfigDebugProfile m_ConfigDebugProfile
PluginConfigDebugProfileFixed m_ConfigDebugProfileFixed
Detailed Description
Definition at line 1 of file ScriptConsoleSoundsTab.c.
Constructor & Destructor Documentation
ScriptConsoleSoundsTab()
void ScriptConsoleSoundsTab::ScriptConsoleSoundsTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent = null) inline protected
Definition at line 22 of file ScriptConsoleSoundsTab.c.
  {
    m_MouseCurPos = TextWidget.Cast(root.FindAnyWidget("MapSoundsPos"));
    m_MapDistWidget = TextWidget.Cast(root.FindAnyWidget("MapSoundsDistance"));
    m_MapHeadingWidget = TextWidget.Cast(root.FindAnyWidget("MapHeadingSounds"));
    m_CopySoundset = ButtonWidget.Cast(root.FindAnyWidget("SoundsetCopy"));
    m_PlaySoundset = ButtonWidget.Cast(root.FindAnyWidget("PlaySoundset"));
    m_PlaySoundsetLooped = ButtonWidget.Cast(root.FindAnyWidget("PlaySoundsetLooped"));
    m_StopSoundset = ButtonWidget.Cast(root.FindAnyWidget("StopSoundset"));
    m_DebugMapWidget = MapWidget.Cast(root.FindAnyWidget("MapSounds"));
    m_SoundFilter = EditBoxWidget.Cast(root.FindAnyWidget("SoundsFilter"));
    m_SoundsTextListbox = TextListboxWidget.Cast(root.FindAnyWidget("SoundsList"));
    m_SoundFilter.SetText(m_ConfigDebugProfile.GetSoundsetFilter());
    ChangeFilterSound();
    if (GetGame().GetPlayer())
    {
      m_DebugMapWidget.SetScale(DEBUG_MAP_ZOOM);
      m_DebugMapWidget.SetMapPos(GetGame().GetPlayer().GetWorldPosition());
      SetMapPos(GetGame().GetPlayer().GetWorldPosition());
    }
  }
References ChangeFilterSound(), DEBUG_MAP_ZOOM, GetGame(), GetPlayer(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_CopySoundset, m_DebugMapWidget, m_MapDistWidget, m_MapHeadingWidget, m_MouseCurPos, m_PlaySoundset, m_PlaySoundsetLooped, m_SoundFilter, m_SoundsTextListbox, m_StopSoundset, SetMapPos(), MapWidget::SetMapPos(), and MapWidget::SetScale().
~ScriptConsoleSoundsTab()
void ScriptConsoleSoundsTab::~ScriptConsoleSoundsTab (Widget root) inline protected
Definition at line 50 of file ScriptConsoleSoundsTab.c.
  {
    DEBUG_MAP_ZOOM = m_DebugMapWidget.GetScale();
  }
References DEBUG_MAP_ZOOM, MapWidget::GetScale(), and m_DebugMapWidget.
Member Function Documentation
ChangeFilter()
void ScriptConsoleSoundsTab::ChangeFilter (TStringArray classes, TextListboxWidget widget, EditBoxWidget filterWidget, int categoryMask = -1, bool ignoreScope = false) inline protected
Definition at line 113 of file ScriptConsoleSoundsTab.c.
  {
    widget.ClearItems();
    TStringArray filters;
    PrepareFilters(filterWidget.GetText(), filters);
    map<string, ref TStringArray> itemsByFilters = new map<string, ref TStringArray>();
    TStringArray itemsArray = TStringArray();
    for (int i = 0; i < classes.Count(); i++)
    {
      string config_path = classes.Get(i);
      int objects_count = GetGame().ConfigGetChildrenCount(config_path);
      for (int j = 0; j < objects_count; j++)
      {
        string child_name;
        bool add = false;
        GetGame().ConfigGetChildName(config_path, j, child_name);
        if (!filters.Count())
          add = true;
        else
        {
          foreach (int indx, string filter: filters)
          {
            string child_name_lower = child_name;
            child_name_lower.ToLower();
            if (child_name_lower.Contains(filter))
            {
              add = true;
              break;
            }
          }
        }
        if (add)
          itemsArray.Insert(child_name);
      }
    }
    if (itemsArray)
    {
      itemsArray.Sort();
      foreach (string it: itemsArray)
        widget.AddItem(it, NULL, 0);
    }
    if (filters)
    {
      /*
        if (m_FilterOrderReversed)
        filters.Invert();
      */
      foreach (string f: filters)
      {
        TStringArray arr2 = itemsByFilters.Get(f);
        if (arr2)
        {
          arr2.Sort();
          foreach (string itm: arr2)
            int row = widget.AddItem(itm, NULL, 0);
        }
      }
    }
  }
References GetGame(), and PrepareFilters().
Referenced by ChangeFilterSound().
ChangeFilterSound()
void ScriptConsoleSoundsTab::ChangeFilterSound () inline protected
Definition at line 305 of file ScriptConsoleSoundsTab.c.
  {
    m_ConfigDebugProfile.SetSoundsetFilter(m_SoundFilter.GetText());
    ChangeFilter(GetSoundClasses(), m_SoundsTextListbox, m_SoundFilter, 0, true);
  }
References ChangeFilter(), GetSoundClasses(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_SoundFilter, and m_SoundsTextListbox.
Referenced by OnClick(), and ScriptConsoleSoundsTab().
GetMapPos()
vector ScriptConsoleSoundsTab::GetMapPos () inline protected
Definition at line 229 of file ScriptConsoleSoundsTab.c.
  {
    return m_MapPos;
  }
References m_MapPos.
Referenced by HandleKeys(), OnClick(), Update(), and UpdateMousePos().
GetSoundClasses()
TStringArray ScriptConsoleSoundsTab::GetSoundClasses () inline protected
Definition at line 300 of file ScriptConsoleSoundsTab.c.
  {
    return {CFG_SOUND_SETS};
  }
References CFG_SOUND_SETS.
Referenced by ChangeFilterSound().
HandleKeys()
void ScriptConsoleSoundsTab::HandleKeys () inline protected
Definition at line 204 of file ScriptConsoleSoundsTab.c.
  {
    bool playRequested = KeyState(KeyCode.KC_P) != 0;
    if (playRequested)
    {
      int selected_row_index = m_SoundsTextListbox.GetSelectedRow();
      if (m_SoundSet)
        m_SoundSet.Stop();
      if (selected_row_index != -1)
      {
        string soundSetName;
        m_SoundsTextListbox.GetItemText(selected_row_index, 0, soundSetName);
        m_SoundSet = SEffectManager.PlaySoundEnviroment(soundSetName, GetMapPos());
        m_SoundSet.SetAutodestroy(true);
      }
    }
  }
References GetMapPos(), KeyState(), m_SoundSet, m_SoundsTextListbox, and SEffectManager::PlaySoundEnviroment().
Referenced by Update().
OnChange()
override bool ScriptConsoleSoundsTab::OnChange (Widget w, int x, int y, bool finished) inline protected
Definition at line 55 of file ScriptConsoleSoundsTab.c.
  {
    super.OnChange(w, x, y, finished);
    if (w == m_SoundFilter)
    {
      m_RefreshFilterTimer.Run(0.85, this, "ChangeFilterSound", null, false);
      return true;
    }
    return false;
  }
References m_RefreshFilterTimer, m_SoundFilter, x, and y.
OnClick()
override bool ScriptConsoleSoundsTab::OnClick (Widget w, int x, int y, int button) inline protected
Definition at line 259 of file ScriptConsoleSoundsTab.c.
  {
    super.OnClick(w, x, y, button);
    if (w == m_CopySoundset)
    {
      AddItemToClipboard(m_SoundsTextListbox);
      return true;
    }
    else if (w == m_PlaySoundset || w == m_PlaySoundsetLooped)
    {
      int selected_row_index = m_SoundsTextListbox.GetSelectedRow();
      string soundSetName;
      if (m_SoundSet)
        m_SoundSet.Stop();
      if (selected_row_index != -1)
      {
        m_SoundsTextListbox.GetItemText(selected_row_index, 0, soundSetName);
        bool looped = (w == m_PlaySoundsetLooped);
        m_SoundSet = SEffectManager.PlaySoundEnviroment(soundSetName, GetMapPos(), 0, 0, looped);
      }
      return true;
    }
    else if (w == m_StopSoundset)
    {
      if (m_SoundSet)
        m_SoundSet.Stop();
      return true;
    }
    else if (w == m_SoundFilter)
    {
      ChangeFilterSound();
      return true;
    }
    return false;
  }
References ScriptConsoleTabBase::AddItemToClipboard(), ChangeFilterSound(), GetMapPos(), m_CopySoundset, m_PlaySoundset, m_PlaySoundsetLooped, m_SoundFilter, m_SoundSet, m_SoundsTextListbox, m_StopSoundset, SEffectManager::PlaySoundEnviroment(), x, and y.
OnMouseButtonDown()
override bool ScriptConsoleSoundsTab::OnMouseButtonDown (Widget w, int x, int y, int button) inline protected
Definition at line 234 of file ScriptConsoleSoundsTab.c.
  {
    super.OnMouseButtonDown(w, x, y, button);
    if (w == m_DebugMapWidget)
    {
      if (button == 0)
      {
        m_PlayerPosRefreshBlocked = true;
        int mouseX, mouseY;
        GetMousePos(mouseX, mouseY);
        vector mousePos, worldPos;
        mousePos[0] = mouseX;
        mousePos[1] = mouseY;
        worldPos = m_DebugMapWidget.ScreenToMap(mousePos);
        worldPos[1] = GetGame().SurfaceY(worldPos[0], worldPos[2]);
        SetMapPos(worldPos);
      }
      else if (button == 1 && GetGame().GetPlayer())
        SetMapPos(GetGame().GetPlayer().GetWorldPosition());
    }
    return true;
  }
References GetGame(), GetMousePos(), GetPlayer(), m_DebugMapWidget, m_PlayerPosRefreshBlocked, MapWidget::ScreenToMap(), SetMapPos(), x, and y.
PrepareFilters()
void ScriptConsoleSoundsTab::PrepareFilters (string filter, out TStringArray filters) inline protected
Definition at line 98 of file ScriptConsoleSoundsTab.c.
  {
    filter.Trim();
    filter.ToLower();
    filters = new TStringArray;
    TStringArray rawFilters = new TStringArray;
    filter.Split(" ", rawFilters);
    foreach (int i, string f: rawFilters)
      filters.Insert(f);
  }
Referenced by ChangeFilter().
SetMapPos()
void ScriptConsoleSoundsTab::SetMapPos (vector pos) inline protected
Definition at line 224 of file ScriptConsoleSoundsTab.c.
  {
    m_MapPos = pos;
  }
References m_MapPos.
Referenced by OnMouseButtonDown(), and ScriptConsoleSoundsTab().
Update()
override void ScriptConsoleSoundsTab::Update (float timeslice) inline protected
Definition at line 184 of file ScriptConsoleSoundsTab.c.
  {
    super.Update(timeslice);
    HandleKeys();
    m_DebugMapWidget.ClearUserMarks();
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (player)
    {
      vector playerPos = player.GetWorldPosition();
      m_DebugMapWidget.AddUserMark(playerPos, "You", COLOR_RED, "\\dz\\gear\\navigation\\data\\map_tree_ca.paa");
      if (playerPos != GetMapPos())
        m_DebugMapWidget.AddUserMark(GetMapPos(), "Source", COLOR_GREEN, "\\dz\\gear\\navigation\\data\\map_tree_ca.paa");
    }
    UpdateMousePos();
  }
References MapWidget::AddUserMark(), MapWidget::ClearUserMarks(), COLOR_GREEN, COLOR_RED, GetGame(), GetMapPos(), GetPlayer(), HandleKeys(), m_DebugMapWidget, and UpdateMousePos().
UpdateMousePos()
void ScriptConsoleSoundsTab::UpdateMousePos () inline protected
Definition at line 67 of file ScriptConsoleSoundsTab.c.
  {
    if (!GetGame().GetPlayer())
      return;
    int x, y;
    GetMousePos(x, y);
    vector mousePos, worldPos;
    mousePos[0] = x;
    mousePos[1] = y;
    worldPos = m_DebugMapWidget.ScreenToMap(mousePos);
    vector playerPos = GetGame().GetPlayer().GetWorldPosition();
    if (GetMapPos() != playerPos)
      worldPos = GetMapPos();
    worldPos[1] = GetGame().SurfaceY(worldPos[0], worldPos[2]);
    if (m_MouseCurPos)
      m_MouseCurPos.SetText("Mouse: " + MiscGameplayFunctions.TruncateToS(worldPos[0]) + ", " + MiscGameplayFunctions.TruncateToS(worldPos[1]) + ", " + MiscGameplayFunctions.TruncateToS(worldPos[2]));
    if (m_MapDistWidget && GetGame().GetPlayer())
    {
      float dst = (worldPos - playerPos).Length();
      m_MapDistWidget.SetText("Distance: " + MiscGameplayFunctions.TruncateToS(dst));
    }
    if (m_MapHeadingWidget)
    {
      vector playerCamDir = GetGame().GetCurrentCameraDirection();
      float heading = Math3D.AngleFromPosition(playerPos, playerCamDir, worldPos) * Math.RAD2DEG;
      m_MapHeadingWidget.SetText("Heading:" + heading.ToString());
    }
  }
References Math3D::AngleFromPosition(), GetGame(), GetMapPos(), GetMousePos(), GetPlayer(), m_DebugMapWidget, m_MapDistWidget, m_MapHeadingWidget, m_MouseCurPos, Math::RAD2DEG, MapWidget::ScreenToMap(), x, and y.
Referenced by Update().
Member Data Documentation
DEBUG_MAP_ZOOM
float ScriptConsoleSoundsTab::DEBUG_MAP_ZOOM = 1 static protected
Definition at line 4 of file ScriptConsoleSoundsTab.c.
Referenced by ScriptConsoleSoundsTab(), and ~ScriptConsoleSoundsTab().
m_CopySoundset
ButtonWidget ScriptConsoleSoundsTab::m_CopySoundset protected
Definition at line 6 of file ScriptConsoleSoundsTab.c.
Referenced by OnClick(), and ScriptConsoleSoundsTab().
m_DebugMapWidget
MapWidget ScriptConsoleSoundsTab::m_DebugMapWidget protected
Definition at line 17 of file ScriptConsoleSoundsTab.c.
Referenced by OnMouseButtonDown(), ScriptConsoleSoundsTab(), Update(), UpdateMousePos(), and ~ScriptConsoleSoundsTab().
m_MapDistWidget
TextWidget ScriptConsoleSoundsTab::m_MapDistWidget protected
Definition at line 18 of file ScriptConsoleSoundsTab.c.
Referenced by ScriptConsoleSoundsTab(), and UpdateMousePos().
m_MapHeadingWidget
TextWidget ScriptConsoleSoundsTab::m_MapHeadingWidget protected
Definition at line 20 of file ScriptConsoleSoundsTab.c.
Referenced by ScriptConsoleSoundsTab(), and UpdateMousePos().
m_MapPos
vector ScriptConsoleSoundsTab::m_MapPos protected
Definition at line 5 of file ScriptConsoleSoundsTab.c.
Referenced by GetMapPos(), and SetMapPos().
m_MouseCurPos
TextWidget ScriptConsoleSoundsTab::m_MouseCurPos protected
Definition at line 19 of file ScriptConsoleSoundsTab.c.
Referenced by ScriptConsoleSoundsTab(), and UpdateMousePos().
m_PlayerPosRefreshBlocked
bool ScriptConsoleSoundsTab::m_PlayerPosRefreshBlocked protected
Definition at line 3 of file ScriptConsoleSoundsTab.c.
Referenced by OnMouseButtonDown().
m_PlaySoundset
ButtonWidget ScriptConsoleSoundsTab::m_PlaySoundset protected
Definition at line 7 of file ScriptConsoleSoundsTab.c.
Referenced by OnClick(), and ScriptConsoleSoundsTab().
m_PlaySoundsetLooped
ButtonWidget ScriptConsoleSoundsTab::m_PlaySoundsetLooped protected
Definition at line 8 of file ScriptConsoleSoundsTab.c.
Referenced by OnClick(), and ScriptConsoleSoundsTab().
m_RefreshFilterTimer
ref Timer ScriptConsoleSoundsTab::m_RefreshFilterTimer = new Timer() protected
Definition at line 15 of file ScriptConsoleSoundsTab.c.
Referenced by OnChange().
m_SoundFilter
EditBoxWidget ScriptConsoleSoundsTab::m_SoundFilter protected
Definition at line 11 of file ScriptConsoleSoundsTab.c.
Referenced by ChangeFilterSound(), OnChange(), OnClick(), and ScriptConsoleSoundsTab().
m_SoundSet
EffectSound ScriptConsoleSoundsTab::m_SoundSet static protected
Definition at line 14 of file ScriptConsoleSoundsTab.c.
Referenced by HandleKeys(), and OnClick().
m_SoundsTextListbox
TextListboxWidget ScriptConsoleSoundsTab::m_SoundsTextListbox protected
Definition at line 12 of file ScriptConsoleSoundsTab.c.
Referenced by ChangeFilterSound(), HandleKeys(), OnClick(), and ScriptConsoleSoundsTab().
m_StopSoundset
ButtonWidget ScriptConsoleSoundsTab::m_StopSoundset protected
Definition at line 9 of file ScriptConsoleSoundsTab.c.
Referenced by OnClick(), and ScriptConsoleSoundsTab().
The documentation for this class was generated from the following file:
scripts/5_Mission/GUI/ScriptConsoleSoundsTab.c