DayZ: scripts/4_World/Entities/Vehicles/CarScript.c File Reference
CarScript.c File Reference
Enumerations
enum CarDoorState { DOORS_MISSING , DOORS_OPEN , DOORS_CLOSED }
Functions
void CarScript ()
override void EEInit ()
vector GetEnginePosWS ()
vector GetCoolantPtcPosWS ()
vector GetRefillPointPosWS ()
vector GetEnginePointPosWS ()
vector GetFrontPointPosWS ()
vector GetBackPointPosWS ()
vector Get_1_1PointPosWS ()
vector Get_1_2PointPosWS ()
vector Get_2_1PointPosWS ()
vector Get_2_2PointPosWS ()
override float GetLiquidThroughputCoef ()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
override void EEDelete (EntityAI parent)
void ~CarScript ()
void CleanupEffects ()
void CleanupSound (EffectSound sound)
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
override bool OnAction (int action_id, Man player, ParamsReadContext ctx)
override void OnVariablesSynchronized ()
void CreateCarDestroyedEffect ()
override void EEItemAttached (EntityAI item, string slot_name)
void UpdateHeadlightState ()
override void EEItemDetached (EntityAI item, string slot_name)
override void OnAttachmentRuined (EntityAI attachment)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanReleaseAttachment (EntityAI attachment)
bool CanManipulateSpareWheel (string slotSelectionName)
override void EOnPostSimulate (IEntity other, float timeSlice)
void OnBrakesPressed ()
void OnBrakesReleased ()
override void OnUpdate (float dt)
override void EEKilled (Object killer)
override void OnContact (string zoneName, vector localPos, IEntity other, Contact data)
WARNING: Can be called very frequently in one frame, use with caution.
void CheckContactCache ()
Responsible for damaging the car according to contact events from OnContact.
void DamageCrew (float dmg)
Responsible for damaging crew in a car crash.
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override void OnAnimationPhaseStarted (string animSource, float phase)
void HandleDoorsSound (string animSource, float phase)
void HandleSeatAdjustmentSound (string animSource, float phase)
void HandleCarHornSound (ECarHornState pState)
void HandleEngineSound (CarEngineSoundState state)
override void MarkCrewMemberUnconscious (int crewMemberIndex)
override void MarkCrewMemberDead (int crewMemberIndex)
override void HandleByCrewMemberState (ECrewMemberState state)
float GetEnviroHeatComfortOverride ()
DEPRECATED.
override void OnFluidChanged (CarFluid fluid, float newValue, float oldValue)
override bool OnBeforeEngineStart ()
override void OnGearChanged (int newGear, int oldGear)
override void OnEngineStart ()
Gets called everytime the engine starts.
override void OnEngineStop ()
Gets called everytime the engine stops.
bool OnBeforeSwitchLights (bool toOn)
bool IsScriptedLightsOn ()
Propper way to get if light is swiched on. Use instead of IsLightsOn().
void ToggleHeadlights ()
Switches headlights on/off, including the illumination of the control panel and synchronizes this change to all clients.
void UpdateLights (int new_gear=-1)
void UpdateLightsClient (int newGear=-1)
void UpdateLightsServer (int newGear=-1)
void BrakesRearLight ()
void ReverseRearLight ()
void BrakeAndReverseRearLight ()
void NoRearLight ()
void LeftFrontLightShineOn ()
void RightFrontLightShineOn ()
void LeftFrontLightShineOff ()
void RightFrontLightShineOff ()
void ReverseLightsShineOn ()
void ReverseLightsShineOff ()
void BrakeLightsShineOn ()
void BrakeLightsShineOff ()
void TailLightsShineOn ()
void TailLightsShineOff ()
void DashboardShineOn ()
void DashboardShineOff ()
CarRearLightBase CreateRearLight ()
CarLightBase CreateFrontLight ()
void CheckVitalItem (bool isVital, string itemName)
void LeakFluid (CarFluid fluid)
void CarPartsHealthCheck ()
bool GetCrashLightSound ()
void SynchCrashLightSound (bool play)
void PlayCrashLightSound ()
bool GetCrashHeavySound ()
void SynchCrashHeavySound (bool play)
void PlayCrashHeavySound ()
void PlaySoundEx (string soundset, EffectSound sound, out bool soundbool)
void PlaySound (string soundset, ref EffectSound sound, out bool soundbool)
string GetAnimSourceFromSelection (string selection)
string GetDoorConditionPointFromSelection (string selection)
string GetDoorSelectionNameFromSeatPos (int posIdx)
string GetDoorInvSlotNameFromSeatPos (int posIdx)
int GetCrewIndex (string selection)
override bool CanReachSeatFromDoors (string pSeatSelection, vector pFromPos, float pDistance=1.0)
bool IsVitalCarBattery ()
bool IsVitalTruckBattery ()
bool IsVitalSparkPlug ()
bool IsVitalGlowPlug ()
bool IsVitalEngineBelt ()
bool IsVitalRadiator ()
bool IsVitalFuelTank ()
bool HasRadiator ()
EntityAI GetRadiator ()
bool IsMoving ()
bool IsHandbrakeActive ()
override int Get3rdPersonCameraType ()
camera type
void SetEngineStarted (bool started)
int GetCarDoorsState (string slotType)
CarDoorState TranslateAnimationPhaseToCarDoorState (string animation)
string GetActionCompNameCoolant ()
float GetActionDistanceCoolant ()
string GetActionCompNameFuel ()
float GetActionDistanceFuel ()
string GetActionCompNameOil ()
float GetActionDistanceOil ()
string GetActionCompNameBrakes ()
float GetActionDistanceBrakes ()
void InitializeActions ()
override void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
void SetActions ()
void AddAction (typename actionName)
void RemoveAction (typename actionName)
override bool IsInventoryVisible ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void EEOnCECreate ()
void ForceUpdateLightsStart ()
void ForceUpdateLightsEnd ()
float GetBatteryConsumption ()
float GetBatteryRuntimeConsumption ()
float GetBatteryRechargeRate ()
ItemBase GetBattery ()
void SetCarHornState (int pState)
void GenerateCarHornAINoise (int pState)
override vector GetDefaultHitPosition ()
void SetEngineZoneReceivedHit (bool pState)
bool HasEngineZoneReceivedHit ()
float GetMomentum ()
float GetPushForceCoefficientMultiplier ()
void SpawnUniversalParts ()
void SpawnAdditionalItems ()
void FillUpCarFluids ()
Variables
enum CarDoorState NONE
enum CarDoorState LEFT
enum CarDoorState RIGHT
enum CarDoorState BRAKES_ONLY
enum CarDoorState REVERSE_ONLY
enum CarDoorState STARTING
enum CarDoorState START_OK
enum CarDoorState START_NO_FUEL
enum CarDoorState START_NO_BATTERY
enum CarDoorState START_NO_SPARKPLUG
enum CarDoorState STOP_OK
enum CarDoorState OFF = 0
enum CarDoorState SHORT = 1
enum CarDoorState LONG
enum CarDoorState typename
enum CarDoorState m_CarTypeActionsMap = new map<typename, ref TInputActionMap>
TInputActionMap m_InputActionMap
bool m_ActionsInitialize
float m_MomentumPrevTick
vector m_VelocityPrevTick
ref CarContactCache m_ContactCache
float m_Time
static float DROWN_ENGINE_THRESHOLD = 0.5
static float DROWN_ENGINE_DAMAGE = 350.0
static const string MEMORY_POINT_NAME_CAR_HORN = "pos_carHorn"
float m_FuelAmmount
keeps ammount of each fluid
float m_CoolantAmmount
float m_OilAmmount
float m_BrakeAmmount
float m_dmgContactCoef = 0.058
float m_EnviroHeatComfortOverride
float m_DrownTime
static vector m_DrownEnginePos
float m_EngineHealth
float m_RadiatorHealth
float m_FuelTankHealth
float m_BatteryHealth
float m_PlugHealth
EntityAI m_Radiator
float m_BatteryConsume = 15
float m_BatteryContinuousConsume = 0.25
float m_BatteryRecharge = 0.15
float m_BatteryTimer = 0
const float BATTERY_UPDATE_DELAY = 100
float m_BatteryEnergyStartMin = 5.0
ref EffVehicleSmoke m_coolantFx
Particles.
ref EffVehicleSmoke m_engineFx
ref EffVehicleSmoke m_exhaustFx
int m_enginePtcFx
int m_coolantPtcFx
int m_exhaustPtcFx
vector m_exhaustPtcPos
vector m_exhaustPtcDir
vector m_enginePtcPos
vector m_coolantPtcPos
vector m_fuelPos
vector m_enginePos
vector m_frontPos
vector m_backPos
vector m_side_1_1Pos
vector m_side_1_2Pos
vector m_side_2_1Pos
vector m_side_2_2Pos
string m_EngineStartOK = ""
Sounds.
string m_EngineStartBattery = ""
string m_EngineStartPlug = ""
string m_EngineStartFuel = ""
string m_EngineStopFuel = ""
string m_CarDoorOpenSound = ""
string m_CarDoorCloseSound = ""
string m_CarSeatShiftInSound = ""
string m_CarSeatShiftOutSound = ""
string m_CarHornShortSoundName = ""
string m_CarHornLongSoundName = ""
ref EffectSound m_CrashSoundLight
ref EffectSound m_CrashSoundHeavy
ref EffectSound m_WindowSmall
ref EffectSound m_WindowLarge
ref EffectSound m_PreStartSound
ref EffectSound m_CarHornSoundEffect
ref NoiseParams m_NoisePar
NoiseSystem m_NoiseSystem
bool m_PlayCrashSoundLight
bool m_PlayCrashSoundHeavy
bool m_HeadlightsOn
bool m_HeadlightsState
bool m_BrakesArePressed
bool m_RearLightType
bool m_ForceUpdateLights
bool m_EngineStarted
bool m_EngineDestroyed
int m_CarHornState
CarLightBase m_Headlight
CarRearLightBase m_RearLight
static string m_ReverseLightPoint = "light_reverse"
static string m_LeftHeadlightPoint = "light_left"
static string m_RightHeadlightPoint = "light_right"
static string m_LeftHeadlightTargetPoint = "light_left_dir"
static string m_RightHeadlightTargetPoint = "light_right_dir"
static string m_DrownEnginePoint = "drown_engine"
static const int SELECTION_ID_FRONT_LIGHT_L = 0
static const int SELECTION_ID_FRONT_LIGHT_R = 1
static const int SELECTION_ID_BRAKE_LIGHT_L = 2
static const int SELECTION_ID_BRAKE_LIGHT_R = 3
static const int SELECTION_ID_REVERSE_LIGHT_L = 4
static const int SELECTION_ID_REVERSE_LIGHT_R = 5
static const int SELECTION_ID_TAIL_LIGHT_L = 6
static const int SELECTION_ID_TAIL_LIGHT_R = 7
static const int SELECTION_ID_DASHBOARD_LIGHT = 8
bool m_EngineBeforeStart
bool m_EngineStartDoOnce
bool m_EngineZoneReceivedHit
ref set< int > m_UnconsciousCrewMemberIndices
ref set< int > m_DeadCrewMemberIndices
Enumeration Type Documentation
CarDoorState
enum CarDoorState
Enumerator
DOORS_MISSING
DOORS_OPEN
DOORS_CLOSED
Definition at line 1 of file CarScript.c.
{
  DOORS_MISSING,
  DOORS_OPEN,
  DOORS_CLOSED
}
Function Documentation
AddAction()
void AddAction (typename actionName) protected
Definition at line 2323 of file CarScript.c.
  {
    ActionBase action = ActionManagerBase.GetAction(actionName);
    if (!action)
    {
      Debug.LogError("Action " + actionName + " dosn't exist!");
      return;
    }
    typename ai = action.GetInputType();
    if (!ai)
    {
      m_ActionsInitialize = false;
      return;
    }
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (!action_array)
    {
      action_array = new array<ActionBase_Basic>;
      m_InputActionMap.Insert(ai, action_array);
    }
    if (LogManager.IsActionLogEnable())
      Debug.ActionLog(action.ToString() + " -> " + ai, this.ToString(), "n/a", "Add action");
    action_array.Insert(action);
  }
References Debug::ActionLog(), LogManager::IsActionLogEnable(), Debug::LogError(), m_ActionsInitialize, and m_InputActionMap.
BrakeAndReverseRearLight()
void BrakeAndReverseRearLight () protected
Definition at line 1839 of file CarScript.c.
  {
    m_RearLight.AggregateLight();
    m_RearLight.SetFadeOutTime(1);
  }
References m_RearLight.
Referenced by UpdateLightsClient().
BrakeLightsShineOff()
void BrakeLightsShineOff () protected
Definition at line 1916 of file CarScript.c.
  {
    string material = ConfigGetString("brakeReflectorMatOff");
    if (material)
    {
      SetObjectMaterial(SELECTION_ID_BRAKE_LIGHT_L, material);
      SetObjectMaterial(SELECTION_ID_BRAKE_LIGHT_R, material);
    }
  }
References SELECTION_ID_BRAKE_LIGHT_L, and SELECTION_ID_BRAKE_LIGHT_R.
Referenced by UpdateLightsServer().
BrakeLightsShineOn()
void BrakeLightsShineOn () protected
Definition at line 1905 of file CarScript.c.
  {
    string material = ConfigGetString("brakeReflectorMatOn");
    if (material)
    {
      SetObjectMaterial(SELECTION_ID_BRAKE_LIGHT_L, material);
      SetObjectMaterial(SELECTION_ID_BRAKE_LIGHT_R, material);
    }
  }
References SELECTION_ID_BRAKE_LIGHT_L, and SELECTION_ID_BRAKE_LIGHT_R.
Referenced by UpdateLightsServer().
BrakesRearLight()
void BrakesRearLight () protected
Definition at line 1829 of file CarScript.c.
  {
    m_RearLight.SetAsSegregatedBrakeLight();
  }
References m_RearLight.
Referenced by UpdateLightsClient().
CanManipulateSpareWheel()
bool CanManipulateSpareWheel (string slotSelectionName) protected
Definition at line 799 of file CarScript.c.
  {
    return false;
  }
CanReachSeatFromDoors()
override bool CanReachSeatFromDoors (string pSeatSelection, vector pFromPos, float pDistance = 1.0) protected
skip the height for now
Definition at line 2147 of file CarScript.c.
  {
    string conPointName = GetDoorConditionPointFromSelection(pSeatSelection);
    if (conPointName.Length() > 0)
    {
      if (MemoryPointExists(conPointName))
      {
        vector conPointMS = GetMemoryPointPos(conPointName);
        vector conPointWS = ModelToWorld(conPointMS);
        conPointWS[1] = 0;
        pFromPos[1] = 0;
        if (vector.Distance(pFromPos, conPointWS) <= pDistance)
          return true;
      }
    }
    return false;
  }
References vector::Distance(), and CarScript::GetDoorConditionPointFromSelection().
CanReceiveAttachment()
override bool CanReceiveAttachment (EntityAI attachment, int slotId) protected
Definition at line 744 of file CarScript.c.
  {
    if (!super.CanReceiveAttachment(attachment, slotId))
      return false;
    InventoryLocation attachmentInventoryLocation = new InventoryLocation();
    attachment.GetInventory().GetCurrentInventoryLocation(attachmentInventoryLocation);
    if (attachmentInventoryLocation.GetParent() == null)
      return true;
    if (attachment && attachment.Type().IsInherited(CarWheel))
    {
      string slotSelectionName;
      InventorySlots.GetSelectionForSlotId(slotId, slotSelectionName);
      switch (slotSelectionName)
      {
      case "wheel_spare_1":
      case "wheel_spare_2":
        return CanManipulateSpareWheel(slotSelectionName);
        break;
      }
    }
    return true;
  }
References CarScript::CanManipulateSpareWheel(), and InventorySlots::GetSelectionForSlotId().
CanReleaseAttachment()
override bool CanReleaseAttachment (EntityAI attachment) protected
Definition at line 771 of file CarScript.c.
  {
    if (!super.CanReleaseAttachment(attachment))
      return false;
    if (EngineIsOn() && IsMoving())
      return false;
    if (attachment && attachment.Type().IsInherited(CarWheel))
    {
      InventoryLocation attachmentInventoryLocation = new InventoryLocation();
      attachment.GetInventory().GetCurrentInventoryLocation(attachmentInventoryLocation);
      string slotSelectionName;
      InventorySlots.GetSelectionForSlotId(attachmentInventoryLocation.GetSlot(), slotSelectionName);
      switch (slotSelectionName)
      {
      case "wheel_spare_1":
      case "wheel_spare_2":
        return CanManipulateSpareWheel(slotSelectionName);
        break;
      }
    }
    return true;
  }
References CarScript::CanManipulateSpareWheel(), InventorySlots::GetSelectionForSlotId(), and IsMoving().
CarPartsHealthCheck()
void CarPartsHealthCheck () protected
Definition at line 2027 of file CarScript.c.
  {
    if (GetGame().IsServer())
    {
      if (HasRadiator())
        m_RadiatorHealth = GetRadiator().GetHealth01("", "");
      else
        m_RadiatorHealth = 0;
      m_EngineHealth = GetHealth01("Engine", "");
      m_FuelTankHealth = GetHealth01("FuelTank", "");
    }
  }
References GetGame(), GetRadiator(), HasRadiator(), m_EngineHealth, m_FuelTankHealth, and m_RadiatorHealth.
Referenced by EOnPostSimulate().
CarScript()
void CarScript () protected
Definition at line 282 of file CarScript.c.
  {
#ifdef DEVELOPER
    _car = this;
#endif
    SetEventMask(EntityEvent.POSTSIMULATE);
    m_ContactCache = new CarContactCache;
    m_Time = 0;
    // sets max health for all components at init
    m_EngineHealth = 1;
    m_FuelTankHealth = 1;
    m_RadiatorHealth = -1;
    m_BatteryHealth = -1;
    m_PlugHealth = -1;
    m_enginePtcFx = -1;
    m_coolantPtcFx = -1;
    m_exhaustPtcFx = -1;
    m_EnviroHeatComfortOverride = 0;
    m_PlayCrashSoundLight = false;
    m_PlayCrashSoundHeavy = false;
    m_CarHornState = ECarHornState.OFF;
    m_UnconsciousCrewMemberIndices = new set<int>();
    m_DeadCrewMemberIndices = new set<int>();
    RegisterNetSyncVariableBool("m_HeadlightsOn");
    RegisterNetSyncVariableBool("m_BrakesArePressed");
    RegisterNetSyncVariableBool("m_ForceUpdateLights");
    RegisterNetSyncVariableBool("m_EngineZoneReceivedHit");
    RegisterNetSyncVariableBoolSignal("m_PlayCrashSoundLight");
    RegisterNetSyncVariableBoolSignal("m_PlayCrashSoundHeavy");
    RegisterNetSyncVariableInt("m_CarHornState", ECarHornState.OFF, ECarHornState.LONG);
    if (MemoryPointExists("ptcExhaust_end"))
    {
      m_exhaustPtcPos = GetMemoryPointPos("ptcExhaust_end");
      if (MemoryPointExists("ptcExhaust_start"))
      {
        vector exhaustStart = GetMemoryPointPos("ptcExhaust_start");
        vector tempOri = vector.Direction(exhaustStart, m_exhaustPtcPos);
        m_exhaustPtcDir[0] = -tempOri[2];
        m_exhaustPtcDir[1] = tempOri[1];
        m_exhaustPtcDir[2] = tempOri[0];
        m_exhaustPtcDir = m_exhaustPtcDir.Normalized().VectorToAngles();
      }
    }
    else
    {
      m_exhaustPtcPos = "0 0 0";
      m_exhaustPtcDir = "1 1 1";
    }
    if (MemoryPointExists("ptcEnginePos"))
      m_enginePtcPos = GetMemoryPointPos("ptcEnginePos");
    else
      m_enginePtcPos = "0 0 0";
    if (MemoryPointExists("ptcCoolantPos"))
      m_coolantPtcPos = GetMemoryPointPos("ptcCoolantPos");
    else
      m_coolantPtcPos = "0 0 0";
    if (MemoryPointExists("refill"))
      m_fuelPos = GetMemoryPointPos("refill");
    else
      m_fuelPos = "0 0 0";
    if (MemoryPointExists("drown_engine"))
      m_DrownEnginePos = GetMemoryPointPos("drown_engine");
    else
      m_DrownEnginePos = "0 0 0";
    if (MemoryPointExists("dmgZone_engine"))
      m_enginePos = GetMemoryPointPos("dmgZone_engine");
    else
      m_enginePos = "0 0 0";
    if (MemoryPointExists("dmgZone_front"))
      m_frontPos = GetMemoryPointPos("dmgZone_front");
    else
      m_frontPos = "0 0 0";
    if (MemoryPointExists("dmgZone_back"))
      m_backPos = GetMemoryPointPos("dmgZone_back");
    else
      m_backPos = "0 0 0";
    if (MemoryPointExists("dmgZone_fender_1_1"))
      m_side_1_1Pos = GetMemoryPointPos("dmgZone_fender_1_1");
    else
      m_side_1_1Pos = "0 0 0";
    if (MemoryPointExists("dmgZone_fender_1_2"))
      m_side_1_2Pos = GetMemoryPointPos("dmgZone_fender_1_2");
    else
      m_side_1_2Pos = "0 0 0";
    if (MemoryPointExists("dmgZone_fender_2_1"))
      m_side_2_1Pos = GetMemoryPointPos("dmgZone_fender_2_1");
    else
      m_side_2_1Pos = "0 0 0";
    if (MemoryPointExists("dmgZone_fender_2_2"))
      m_side_2_2Pos = GetMemoryPointPos("dmgZone_fender_2_2");
    else
      m_side_2_2Pos = "0 0 0";
  }
References vector::Direction(), m_backPos, m_BatteryHealth, m_CarHornState, m_ContactCache, m_coolantPtcFx, m_coolantPtcPos, m_DeadCrewMemberIndices, m_DrownEnginePos, m_EngineHealth, m_enginePos, m_enginePtcFx, m_enginePtcPos, m_EnviroHeatComfortOverride, m_exhaustPtcDir, m_exhaustPtcFx, m_exhaustPtcPos, m_frontPos, m_fuelPos, m_FuelTankHealth, m_PlayCrashSoundHeavy, m_PlayCrashSoundLight, m_PlugHealth, m_RadiatorHealth, m_side_1_1Pos, m_side_1_2Pos, m_side_2_1Pos, m_side_2_2Pos, m_Time, m_UnconsciousCrewMemberIndices, and vector::Normalized().
CheckContactCache()
void CheckContactCache () protected
Responsible for damaging the car according to contact events from OnContact.
Definition at line 1085 of file CarScript.c.
  {
    int contactZonesCount = m_ContactCache.Count();
    if (contactZonesCount == 0)
      return;
    for (int i = 0; i < contactZonesCount; ++i)
    {
      string zoneName = m_ContactCache.GetKey(i);
      array<ref CarContactData> data = m_ContactCache[zoneName];
      float dmg = Math.AbsInt(data[0].impulse * m_dmgContactCoef);
      float crewDmgBase = Math.AbsInt((data[0].impulse / dBodyGetMass(this)) * 1000 * m_dmgContactCoef);// calculates damage as if the object's weight was 1000kg instead of its actual weight
#ifdef DIAG_DEVELOPER
      CrashDebugData.m_CrashDataPoint = new CrashDebugData();
      CrashDebugData.m_CrashDataPoint.m_VehicleType = GetDisplayName();
      CrashDebugData.m_CrashDataPoint.m_Damage = dmg;
      CrashDebugData.m_CrashDataPoint.m_Zone = zoneName;
      CrashDebugData.m_CrashDataPoint.m_MomentumCurr = GetMomentum();
      CrashDebugData.m_CrashDataPoint.m_MomentumPrev = m_MomentumPrevTick;
      CrashDebugData.m_CrashDataPoint.m_MomentumDelta = data[0].impulse;
      CrashDebugData.m_CrashDataPoint.m_SpeedWorld = GetVelocity(this).Length() * 3.6;
      CrashDebugData.m_CrashDataPoint.m_SpeedWorldPrev = m_VelocityPrevTick.Length() * 3.6;
      CrashDebugData.m_CrashDataPoint.m_SpeedWorldDelta = (m_VelocityPrevTick.Length() - GetVelocity(this).Length()) * 3.6;
      CrashDebugData.m_CrashDataPoint.m_VelocityCur = GetVelocity(this);
      CrashDebugData.m_CrashDataPoint.m_VelocityPrev = m_VelocityPrevTick;
      CrashDebugData.m_CrashDataPoint.m_VelocityDot = vector.Dot(m_VelocityPrevTick.Normalized(), GetVelocity(this).Normalized());
      CrashDebugData.m_CrashDataPoint.m_Time = GetGame().GetTime();
      if (DEBUG_OUTPUT_TYPE & EVehicleDebugOutputType.DAMAGE_CONSIDERED)
      {
        Debug.Log("--------------------------------------------------");
        Debug.Log("Vehicle:" + GetDisplayName());
        Debug.Log("DMG: " + dmg);
        Debug.Log("zoneName : " + zoneName);
        Debug.Log("momentumCurr : " + GetMomentum());
        Debug.Log("momentumPrev : " + m_MomentumPrevTick);
        Debug.Log("momentumDelta : " + data[0].impulse);
        Debug.Log("speed(km/h): " + GetVelocity(this).Length() * 3.6);
        Debug.Log("speedPrev(km/h): " + m_VelocityPrevTick.Length() * 3.6);
        Debug.Log("speedDelta(km/h) : " + (m_VelocityPrevTick.Length() - GetVelocity(this).Length()) * 3.6);
        Debug.Log("velocityCur.): " + GetVelocity(this));
        Debug.Log("velocityPrev.): " + m_VelocityPrevTick);
        Debug.Log("velocityDot): " + vector.Dot(m_VelocityPrevTick.Normalized(), GetVelocity(this).Normalized()));
        Debug.Log("GetGame().GetTime(): " + GetGame().GetTime());
        Debug.Log("--------------------------------------------------");
      }
#endif
      if (dmg < GameConstants.CARS_CONTACT_DMG_MIN)
        continue;
      int pddfFlags;
#ifdef DIAG_DEVELOPER
      CrashDebugData.m_CrashData.Insert(CrashDebugData.m_CrashDataPoint);
      CrashDebugData.m_CrashDataPoint.m_Speedometer = GetSpeedometer();
      //Print("Crash data recorded");
#endif
      if (dmg < GameConstants.CARS_CONTACT_DMG_THRESHOLD)
      {
#ifdef DIAG_DEVELOPER
        CrashDebugData.m_CrashDataPoint.m_DamageType = "Small";
        if (DEBUG_OUTPUT_TYPE & EVehicleDebugOutputType.DAMAGE_APPLIED)
          Debug.Log(string.Format("[Vehiles:Damage]:: DMG %1 to the %2 zone is SMALL (threshold: %3), SPEEDOMETER: %4, TIME: %5", dmg, zoneName, GameConstants.CARS_CONTACT_DMG_MIN, GetSpeedometer(), GetGame().GetTime()));
#endif
        SynchCrashLightSound(true);
        pddfFlags = ProcessDirectDamageFlags.NO_TRANSFER;
      }
      else
      {
#ifdef DIAG_DEVELOPER
        CrashDebugData.m_CrashDataPoint.m_DamageType = "Big";
        if (DEBUG_OUTPUT_TYPE & EVehicleDebugOutputType.DAMAGE_APPLIED)
          Debug.Log(string.Format("[Vehiles:Damage]:: DMG %1 to the %2 zone is BIG (threshold: %3), SPEED: %4, TIME: %5", dmg, zoneName, GameConstants.CARS_CONTACT_DMG_THRESHOLD, GetSpeedometer(), GetGame().GetTime()));
#endif
        DamageCrew(crewDmgBase);
        SynchCrashHeavySound(true);
        pddfFlags = 0;
      }
#ifdef DEVELOPER
      m_DebugContactDamageMessage += string.Format("%1: %2\n", zoneName, dmg);
#endif
      ProcessDirectDamage(DT_CUSTOM, null, zoneName, "EnviroDmg", "0 0 0", dmg, pddfFlags);
    }
    UpdateHeadlightState();
    UpdateLights();
    m_ContactCache.Clear();
  }
References Math::AbsInt(), GameConstants::CARS_CONTACT_DMG_MIN, GameConstants::CARS_CONTACT_DMG_THRESHOLD, DamageCrew(), dBodyGetMass(), vector::Dot(), GetGame(), GetMomentum(), GetTime(), GetVelocity(), vector::Length(), Debug::Log(), m_ContactCache, m_dmgContactCoef, m_MomentumPrevTick, m_VelocityPrevTick, vector::Normalized(), SynchCrashHeavySound(), SynchCrashLightSound(), UpdateHeadlightState(), and UpdateLights().
Referenced by EOnPostSimulate().
CheckVitalItem()
void CheckVitalItem (bool isVital, string itemName) protected
Definition at line 1991 of file CarScript.c.
  {
    if (!isVital)
      return;
    EntityAI item = FindAttachmentBySlotName(itemName);
    if (!item)
      EngineStop();
    else if (item.IsRuined())
      EngineStop();
  }
Referenced by EOnPostSimulate().
CleanupEffects()
void CleanupEffects () protected
Definition at line 514 of file CarScript.c.
  {
    SEffectManager.DestroyEffect(m_coolantFx);
    SEffectManager.DestroyEffect(m_exhaustFx);
    SEffectManager.DestroyEffect(m_engineFx);
    if (m_Headlight)
      m_Headlight.Destroy();
    if (m_RearLight)
      m_RearLight.Destroy();
    SEffectManager.DestroyEffect(m_CrashSoundLight);
    SEffectManager.DestroyEffect(m_CrashSoundHeavy);
    SEffectManager.DestroyEffect(m_WindowSmall);
    SEffectManager.DestroyEffect(m_WindowLarge);
    CleanupSound(m_CarHornSoundEffect);
  }
References CleanupSound(), SEffectManager::DestroyEffect(), m_CarHornSoundEffect, m_coolantFx, m_CrashSoundHeavy, m_CrashSoundLight, m_engineFx, m_exhaustFx, m_Headlight, m_RearLight, m_WindowLarge, and m_WindowSmall.
Referenced by EEDelete(), and ~CarScript().
CleanupSound()
void CleanupSound (EffectSound sound) protected
Definition at line 533 of file CarScript.c.
  {
    SEffectManager.DestroyEffect(sound);
  }
References SEffectManager::DestroyEffect().
Referenced by CleanupEffects(), and HandleCarHornSound().
CreateCarDestroyedEffect()
void CreateCarDestroyedEffect () protected
Definition at line 630 of file CarScript.c.
  {
    if (!SEffectManager.IsEffectExist(m_enginePtcFx) && GetGame().GetWaterDepth(GetEnginePosWS()) <= 0)
    {
      m_engineFx = new EffEngineSmoke();
      m_engineFx.SetParticleStateHeavy();
      m_enginePtcFx = SEffectManager.PlayOnObject(m_engineFx, this, m_enginePtcPos, Vector(0, 0, 0));
    }
  }
References GetEnginePosWS(), GetGame(), SEffectManager::IsEffectExist(), m_engineFx, m_enginePtcFx, m_enginePtcPos, SEffectManager::PlayOnObject(), and Vector().
Referenced by EEHealthLevelChanged().
CreateFrontLight()
CarLightBase CreateFrontLight () protected
Definition at line 1986 of file CarScript.c.
  {
    return CarLightBase.Cast(ScriptedLightBase.CreateLight(OffroadHatchbackFrontLight));
  }
CreateRearLight()
CarRearLightBase CreateRearLight () protected
Definition at line 1980 of file CarScript.c.
  {
    return CarRearLightBase.Cast(ScriptedLightBase.CreateLight(OffroadHatchbackFrontLight));
  }
DamageCrew()
void DamageCrew (float dmg) protected
Responsible for damaging crew in a car crash.
Definition at line 1184 of file CarScript.c.
  {
    for (int c = 0; c < CrewSize(); ++c)
    {
      Human crew = CrewMember(c);
      if (!crew)
        continue;
      PlayerBase player;
      if (Class.CastTo(player, crew))
      {
        if (dmg > GameConstants.CARS_CONTACT_DMG_KILLCREW)
        {
#ifdef DIAG_DEVELOPER
          CrashDebugData.m_CrashDataPoint.m_CrewDamageBase = dmg;
          CrashDebugData.m_CrashDataPoint.m_DMGHealth = -100;
          if (DEBUG_OUTPUT_TYPE & EVehicleDebugOutputType.DAMAGE_APPLIED)
          {
            Debug.Log("--------------------------------------------------");
            Debug.Log("Killing the player");
            Debug.Log("Crew DMG Base: " + dmg);
            Debug.Log("--------------------------------------------------");
          }
#endif
          player.SetHealth(0.0);
        }
        else
        {
          float shockTemp = Math.InverseLerp(GameConstants.CARS_CONTACT_DMG_THRESHOLD, GameConstants.CARS_CONTACT_DMG_KILLCREW, dmg);
          shockTemp = Math.Clamp(shockTemp, 0, 1);
          float shock = Math.Lerp(50, 150, shockTemp);
          float hp = Math.Lerp(2, 100, shockTemp);
#ifdef DIAG_DEVELOPER
          CrashDebugData.m_CrashDataPoint.m_CrewDamageBase = dmg;
          CrashDebugData.m_CrashDataPoint.m_ShockTemp = shockTemp;
          CrashDebugData.m_CrashDataPoint.m_DMGHealth = hp;
          CrashDebugData.m_CrashDataPoint.m_DMGShock = shock;
          if (DEBUG_OUTPUT_TYPE & EVehicleDebugOutputType.DAMAGE_APPLIED)
          {
            Debug.Log("--------------------------------------------------");
            Debug.Log("Crew DMG Base: " + dmg);
            Debug.Log("Crew shockTemp: " + shockTemp);
            Debug.Log("Crew DMG Health: " + hp);
            Debug.Log("Crew DMG Shock: " + shock);
            Debug.Log("--------------------------------------------------");
          }
#endif
          player.AddHealth("", "Shock", -shock);
          player.AddHealth("", "Health", -hp);
        }
      }
    }
  }
References GameConstants::CARS_CONTACT_DMG_KILLCREW, GameConstants::CARS_CONTACT_DMG_THRESHOLD, Class::CastTo(), Math::Clamp(), Math::InverseLerp(), Math::Lerp(), and Debug::Log().
Referenced by CheckContactCache().
DashboardShineOff()
void DashboardShineOff () protected
Definition at line 1971 of file CarScript.c.
  {
    string material = ConfigGetString("dashboardMatOff");
    if (material)
      SetObjectMaterial(SELECTION_ID_DASHBOARD_LIGHT, material);
  }
References SELECTION_ID_DASHBOARD_LIGHT.
Referenced by UpdateLightsServer().
DashboardShineOn()
void DashboardShineOn () protected
Definition at line 1963 of file CarScript.c.
  {
    string material = ConfigGetString("dashboardMatOn");
    if (material)
      SetObjectMaterial(SELECTION_ID_DASHBOARD_LIGHT, material);
  }
References SELECTION_ID_DASHBOARD_LIGHT.
Referenced by UpdateLightsServer().
EEDelete()
override void EEDelete (EntityAI parent) protected
Definition at line 500 of file CarScript.c.
  {
#ifndef SERVER
    CleanupEffects();
#endif
  }
References CleanupEffects().
EEHealthLevelChanged()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) protected
Definition at line 2368 of file CarScript.c.
  {
    super.EEHealthLevelChanged(oldLevel, newLevel, zone);
    if (newLevel == GameConstants.STATE_RUINED && oldLevel != newLevel)
    {
      bool dummy;
      switch (zone)
      {
      case "WindowLR":
      case "WindowRR":
        if (m_Initialized)
          PlaySoundEx("offroad_hit_window_small_SoundSet", m_WindowSmall, dummy);
        break;
      case "WindowFront":
      case "WindowBack":
      case "WindowFrontLeft":
      case "WindowFrontRight":
        if (m_Initialized)
          PlaySoundEx("offroad_hit_window_large_SoundSet", m_WindowLarge, dummy);
        break;
      case "Engine":
#ifndef SERVER
        CreateCarDestroyedEffect();
#endif
        break;
      }
    }
  }
References CreateCarDestroyedEffect(), m_Initialized, m_WindowLarge, m_WindowSmall, PlaySoundEx(), and GameConstants::STATE_RUINED.
EEHitBy()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) protected
Definition at line 490 of file CarScript.c.
  {
    super.EEHitBy(damageResult, damageType, source, component, dmgZone, ammo, modelPos, speedCoef);
    ForceUpdateLightsStart();
    GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLater(ForceUpdateLightsEnd, 100, false);
    SetEngineZoneReceivedHit(dmgZone == "Engine");
  }
References CALL_CATEGORY_GAMEPLAY, component, ForceUpdateLightsEnd(), ForceUpdateLightsStart(), GetGame(), and SetEngineZoneReceivedHit().
EEInit()
override void EEInit () protected
Definition at line 399 of file CarScript.c.
  {
    super.EEInit();
    if (GetGame().IsServer())
    {
      m_NoiseSystem = GetGame().GetNoiseSystem();
      if (m_NoiseSystem && !m_NoisePar)
      {
        m_NoisePar = new NoiseParams();
        m_NoisePar.LoadFromPath("cfgVehicles " + GetType() + " NoiseCarHorn");
      }
    }
  }
References GetGame(), GetType(), m_NoisePar, m_NoiseSystem, and NoiseParams().
EEItemAttached()
override void EEItemAttached (EntityAI item, string slot_name) protected
Definition at line 640 of file CarScript.c.
  {
    super.EEItemAttached(item, slot_name);
    switch (slot_name)
    {
    case "Reflector_1_1":
      if (GetGame().IsServer())
        SetHealth("Reflector_1_1", "Health", item.GetHealth());
      break;
    case "Reflector_2_1":
      if (GetGame().IsServer())
        SetHealth("Reflector_2_1", "Health", item.GetHealth());
      break;
    case "CarBattery":
    case "TruckBattery":
      if (GetGame().IsServer())
        m_BatteryHealth = item.GetHealth01();
      break;
    case "SparkPlug":
    case "GlowPlug":
      if (GetGame().IsServer())
        m_PlugHealth = item.GetHealth01();
      break;
    case "CarRadiator":
      if (GetGame().IsServer())
        m_RadiatorHealth = item.GetHealth01();
      m_Radiator = item;
      break;
    }
    if (GetGame().IsServer())
      Synchronize();
    UpdateHeadlightState();
    UpdateLights();
  }
References GetGame(), m_BatteryHealth, m_PlugHealth, m_Radiator, m_RadiatorHealth, Synchronize(), UpdateHeadlightState(), and UpdateLights().
EEItemDetached()
override void EEItemDetached (EntityAI item, string slot_name) protected
Definition at line 695 of file CarScript.c.
  {
    switch (slot_name)
    {
    case "CarBattery":
    case "TruckBattery":
      m_BatteryHealth = -1;
      if (GetGame().IsServer())
      {
        if (EngineIsOn())
          EngineStop();
        if (IsScriptedLightsOn())
          ToggleHeadlights();
      }
      break;
    case "SparkPlug":
    case "GlowPlug":
      m_PlugHealth = -1;
      if (GetGame().IsServer() && EngineIsOn())
        EngineStop();
      break;
    case "CarRadiator":
      m_Radiator = null;
      if (GetGame().IsServer())
      {
        LeakAll(CarFluid.COOLANT);
        if (m_DamageZoneMap.Contains("Radiator"))
          SetHealth("Radiator", "Health", 0);
      }
      break;
    }
    if (GetGame().IsServer())
      Synchronize();
    UpdateHeadlightState();
    UpdateLights();
  }
References GetGame(), IsScriptedLightsOn(), m_BatteryHealth, m_PlugHealth, m_Radiator, Synchronize(), ToggleHeadlights(), UpdateHeadlightState(), and UpdateLights().
EEKilled()
override void EEKilled (Object killer) protected
Definition at line 1051 of file CarScript.c.
  {
    super.EEKilled(killer);
    m_EngineDestroyed = true;
  }
References m_EngineDestroyed.
EEOnCECreate()
override void EEOnCECreate () protected
Definition at line 2400 of file CarScript.c.
  {
    float maxVolume = GetFluidCapacity(CarFluid.FUEL);
    float amount = Math.RandomFloat(0.0, maxVolume * 0.35);
    Fill(CarFluid.FUEL, amount);
  }
References Math::RandomFloat().
EOnPostSimulate()
override void EOnPostSimulate (IEntity other, float timeSlice) protected
actions runned when the engine on
leaking of coolant from radiator when damaged
Definition at line 804 of file CarScript.c.
  {
    m_Time += timeSlice;
    if (GetGame().IsServer())
    {
      HandleByCrewMemberState(ECrewMemberState.UNCONSCIOUS);
      HandleByCrewMemberState(ECrewMemberState.DEAD);
#ifdef DIAG_DEVELOPER
      if (DEBUG_OUTPUT_TYPE & EVehicleDebugOutputType.CONTACT)
      {
        if (m_ContactCalled)
        {
          Debug.Log("Momentum delta: " + (GetMomentum() - m_MomentumPrevTick));
          Debug.Log("--------------------------------------------------------------------");
          m_ContactCalled = false;
        }
      }
#endif
      CheckContactCache();
      m_VelocityPrevTick = GetVelocity(this);
      m_MomentumPrevTick = GetMomentum();
#ifdef DEVELOPER
      m_DebugMessageCleanTime += timeSlice;
      if (m_DebugMessageCleanTime >= DEBUG_MESSAGE_CLEAN_TIME_SECONDS)
      {
        m_DebugMessageCleanTime = 0;
        m_DebugContactDamageMessage = "";
      }
#endif
    }
    if (m_Time >= GameConstants.CARS_FLUIDS_TICK)
    {
      m_Time = 0;
      CarPartsHealthCheck();
      //First of all check if the car should stop the engine
      if (GetGame().IsServer() && EngineIsOn())
      {
        if (GetFluidFraction(CarFluid.FUEL) <= 0 || m_EngineHealth <= 0)
          EngineStop();
        CheckVitalItem(IsVitalCarBattery(), "CarBattery");
        CheckVitalItem(IsVitalTruckBattery(), "TruckBattery");
        CheckVitalItem(IsVitalSparkPlug(), "SparkPlug");
        CheckVitalItem(IsVitalGlowPlug(), "GlowPlug");
      }
      if (GetGame().IsServer())
      {
        if (IsVitalFuelTank())
        {
          if (m_FuelTankHealth == GameConstants.DAMAGE_RUINED_VALUE && m_EngineHealth > GameConstants.DAMAGE_RUINED_VALUE)
            SetHealth("Engine", "Health", GameConstants.DAMAGE_RUINED_VALUE);
        }
      }
      if (EngineIsOn())
      {
        if (GetGame().IsServer())
        {
          float dmg;
          if (EngineGetRPM() >= EngineGetRPMRedline())
          {
            if (EngineGetRPM() > EngineGetRPMMax())
              AddHealth("Engine", "Health", -GetMaxHealth("Engine", "") * 0.05); //CAR_RPM_DMG
            dmg = EngineGetRPM() * 0.001 * Math.RandomFloat(0.02, 1.0); //CARS_TICK_DMG_MIN; //CARS_TICK_DMG_MAX
            ProcessDirectDamage(DamageType.CUSTOM, null, "Engine", "EnviroDmg", vector.Zero, dmg);
            SetEngineZoneReceivedHit(true);
          }
          else
            SetEngineZoneReceivedHit(false);
          if (IsVitalRadiator())
          {
            if (GetFluidFraction(CarFluid.COOLANT) > 0 && m_RadiatorHealth < 0.5) //CARS_LEAK_THRESHOLD
              LeakFluid(CarFluid.COOLANT);
          }
          if (GetFluidFraction(CarFluid.FUEL) > 0 && m_FuelTankHealth < GameConstants.DAMAGE_DAMAGED_VALUE)
            LeakFluid(CarFluid.FUEL);
          if (GetFluidFraction(CarFluid.BRAKE) > 0 && m_EngineHealth < GameConstants.DAMAGE_DAMAGED_VALUE)
            LeakFluid(CarFluid.BRAKE);
          if (GetFluidFraction(CarFluid.OIL) > 0 && m_EngineHealth < GameConstants.DAMAGE_DAMAGED_VALUE)
            LeakFluid(CarFluid.OIL);
          if (m_EngineHealth < 0.25)
            LeakFluid(CarFluid.OIL);
          if (IsVitalRadiator())
          {
            if (GetFluidFraction(CarFluid.COOLANT) < 0.5 && GetFluidFraction(CarFluid.COOLANT) >= 0)
            {
              dmg = (1 - GetFluidFraction(CarFluid.COOLANT)) * Math.RandomFloat(0.02, 10.00); //CARS_DMG_TICK_MIN_COOLANT; //CARS_DMG_TICK_MAX_COOLANT
              AddHealth("Engine", "Health", -dmg);
              SetEngineZoneReceivedHit(true);
            }
          }
        }
        //FX only on Client and in Single
        if (!GetGame().IsDedicatedServer())
        {
          if (!SEffectManager.IsEffectExist(m_exhaustPtcFx))
          {
            m_exhaustFx = new EffExhaustSmoke();
            m_exhaustPtcFx = SEffectManager.PlayOnObject(m_exhaustFx, this, m_exhaustPtcPos, m_exhaustPtcDir);
            m_exhaustFx.SetParticleStateLight();
          }
          if (IsVitalRadiator() && GetFluidFraction(CarFluid.COOLANT) < 0.5)
          {
            if (!SEffectManager.IsEffectExist(m_coolantPtcFx))
            {
              m_coolantFx = new EffCoolantSteam();
              m_coolantPtcFx = SEffectManager.PlayOnObject(m_coolantFx, this, m_coolantPtcPos, vector.Zero);
            }
            if (m_coolantFx)
            {
              if (GetFluidFraction(CarFluid.COOLANT) > 0)
                m_coolantFx.SetParticleStateLight();
              else
                m_coolantFx.SetParticleStateHeavy();
            }
          }
          else
          {
            if (SEffectManager.IsEffectExist(m_coolantPtcFx))
              SEffectManager.Stop(m_coolantPtcFx);
          }
        }
      }
      else
      {
        //FX only on Client and in Single
        if (!GetGame().IsDedicatedServer())
        {
          if (SEffectManager.IsEffectExist(m_exhaustPtcFx))
          {
            SEffectManager.Stop(m_exhaustPtcFx);
            m_exhaustPtcFx = -1;
          }
          if (SEffectManager.IsEffectExist(m_coolantPtcFx))
          {
            SEffectManager.Stop(m_coolantPtcFx);
            m_coolantPtcFx = -1;
          }
        }
      }
    }
  }
References CarPartsHealthCheck(), GameConstants::CARS_FLUIDS_TICK, CheckContactCache(), CheckVitalItem(), GameConstants::DAMAGE_DAMAGED_VALUE, GameConstants::DAMAGE_RUINED_VALUE, GetGame(), GetMomentum(), GetVelocity(), HandleByCrewMemberState(), SEffectManager::IsEffectExist(), CarScript::IsVitalCarBattery(), IsVitalFuelTank(), CarScript::IsVitalGlowPlug(), CarScript::IsVitalRadiator(), CarScript::IsVitalSparkPlug(), CarScript::IsVitalTruckBattery(), LeakFluid(), Debug::Log(), m_coolantFx, m_coolantPtcFx, m_coolantPtcPos, m_EngineHealth, m_exhaustFx, m_exhaustPtcDir, m_exhaustPtcFx, m_exhaustPtcPos, m_FuelTankHealth, m_MomentumPrevTick, m_RadiatorHealth, m_Time, m_VelocityPrevTick, SEffectManager::PlayOnObject(), Math::RandomFloat(), SetEngineZoneReceivedHit(), SEffectManager::Stop(), and vector::Zero.
FillUpCarFluids()
void FillUpCarFluids () protected
Definition at line 2578 of file CarScript.c.
  {
    Fill(CarFluid.FUEL, 200.0);
    Fill(CarFluid.COOLANT, 200.0);
    Fill(CarFluid.OIL, 200.0);
  }
Referenced by CarScript::OnDebugSpawn(), CivilianSedan::OnDebugSpawn(), Hatchback_02::OnDebugSpawn(), Sedan_02::OnDebugSpawn(), and Truck_01_Covered::OnDebugSpawn().
ForceUpdateLightsEnd()
void ForceUpdateLightsEnd () protected
Definition at line 2418 of file CarScript.c.
  {
    if (m_ForceUpdateLights)
    {
      m_ForceUpdateLights = false;
      SetSynchDirty();
    }
  }
References m_ForceUpdateLights.
Referenced by EEHitBy().
ForceUpdateLightsStart()
void ForceUpdateLightsStart () protected
Definition at line 2409 of file CarScript.c.
  {
    if (!m_ForceUpdateLights)
    {
      m_ForceUpdateLights = true;
      SetSynchDirty();
    }
  }
References m_ForceUpdateLights.
Referenced by EEHitBy().
GenerateCarHornAINoise()
void GenerateCarHornAINoise (int pState) protected
Definition at line 2463 of file CarScript.c.
  {
    if (pState != ECarHornState.OFF)
    {
      if (m_NoiseSystem && m_NoisePar)
      {
        float noiseMultiplier = 1.0;
        if (pState == ECarHornState.LONG)
          noiseMultiplier = 2.0;
        m_NoiseSystem.AddNoiseTarget(GetPosition(), 5, m_NoisePar, noiseMultiplier);
      }
    }
  }
References NoiseSystem::AddNoiseTarget(), GetPosition, m_NoisePar, and m_NoiseSystem.
Referenced by SetCarHornState().
Get3rdPersonCameraType()
override int Get3rdPersonCameraType () protected
camera type
Definition at line 2225 of file CarScript.c.
  {
    return DayZPlayerCameras.DAYZCAMERA_3RD_VEHICLE;
  }
References DayZPlayerCameras::DAYZCAMERA_3RD_VEHICLE.
Get_1_1PointPosWS()
vector Get_1_1PointPosWS () protected
Definition at line 467 of file CarScript.c.
  {
    return ModelToWorld(m_side_1_1Pos);
  }
References m_side_1_1Pos.
Get_1_2PointPosWS()
vector Get_1_2PointPosWS () protected
Definition at line 471 of file CarScript.c.
  {
    return ModelToWorld(m_side_1_2Pos);
  }
References m_side_1_2Pos.
Get_2_1PointPosWS()
vector Get_2_1PointPosWS () protected
Definition at line 475 of file CarScript.c.
  {
    return ModelToWorld(m_side_2_1Pos);
  }
References m_side_2_1Pos.
Get_2_2PointPosWS()
vector Get_2_2PointPosWS () protected
Definition at line 479 of file CarScript.c.
  {
    return ModelToWorld(m_side_2_2Pos);
  }
References m_side_2_2Pos.
GetActionCompNameBrakes()
string GetActionCompNameBrakes () protected
Definition at line 2279 of file CarScript.c.
  {
    return "carradiator";
  }
GetActionCompNameCoolant()
string GetActionCompNameCoolant () protected
Definition at line 2249 of file CarScript.c.
  {
    return "radiator";
  }
GetActionCompNameFuel()
string GetActionCompNameFuel () protected
Definition at line 2259 of file CarScript.c.
  {
    return "refill";
  }
GetActionCompNameOil()
string GetActionCompNameOil () protected
Definition at line 2269 of file CarScript.c.
  {
    return "carradiator";
  }
GetActionDistanceBrakes()
float GetActionDistanceBrakes () protected
Definition at line 2284 of file CarScript.c.
  {
    return 2.0;
  }
GetActionDistanceCoolant()
float GetActionDistanceCoolant () protected
Definition at line 2254 of file CarScript.c.
  {
    return 2.0;
  }
GetActionDistanceFuel()
float GetActionDistanceFuel () protected
Definition at line 2264 of file CarScript.c.
  {
    return 1.5;
  }
GetActionDistanceOil()
float GetActionDistanceOil () protected
Definition at line 2274 of file CarScript.c.
  {
    return 2.0;
  }
GetActions()
override void GetActions (typename action_input_type , out array< ActionBase_Basic > actions) protected
Definition at line 2301 of file CarScript.c.
  {
    if (!m_ActionsInitialize)
    {
      m_ActionsInitialize = true;
      InitializeActions();
    }
    actions = m_InputActionMap.Get(action_input_type);
  }
References InitializeActions(), m_ActionsInitialize, and m_InputActionMap.
GetAnimSourceFromSelection()
string GetAnimSourceFromSelection (string selection) protected
Definition at line 2106 of file CarScript.c.
  {
    return "";
  }
GetBackPointPosWS()
vector GetBackPointPosWS () protected
Definition at line 463 of file CarScript.c.
  {
    return ModelToWorld(m_backPos);
  }
References m_backPos.
GetBattery()
ItemBase GetBattery () protected
Definition at line 2443 of file CarScript.c.
  {
    if (IsVitalCarBattery())
      return ItemBase.Cast(FindAttachmentBySlotName("CarBattery"));
    else if (IsVitalTruckBattery())
      return ItemBase.Cast(FindAttachmentBySlotName("TruckBattery"));
    return null;
  }
References CarScript::IsVitalCarBattery(), and CarScript::IsVitalTruckBattery().
Referenced by OnBeforeEngineStart(), OnEngineStart(), and OnUpdate().
GetBatteryConsumption()
float GetBatteryConsumption () protected
Definition at line 2428 of file CarScript.c.
  {
    return m_BatteryConsume;
  }
References m_BatteryConsume.
Referenced by OnEngineStart().
GetBatteryRechargeRate()
float GetBatteryRechargeRate () protected
Definition at line 2438 of file CarScript.c.
  {
    return -m_BatteryRecharge;
  }
References m_BatteryRecharge.
Referenced by OnUpdate().
GetBatteryRuntimeConsumption()
float GetBatteryRuntimeConsumption () protected
Definition at line 2433 of file CarScript.c.
  {
    return m_BatteryContinuousConsume;
  }
References m_BatteryContinuousConsume.
Referenced by OnUpdate().
GetCarDoorsState()
int GetCarDoorsState (string slotType) protected
Definition at line 2236 of file CarScript.c.
  {
    return -1;
  }
Referenced by CarScript::CrewCanGetThrough(), and CarScript::OnSound().
GetCoolantPtcPosWS()
vector GetCoolantPtcPosWS () protected
Definition at line 445 of file CarScript.c.
  {
    return ModelToWorld(m_coolantPtcPos);
  }
References m_coolantPtcPos.
GetCrashHeavySound()
bool GetCrashHeavySound () protected
Definition at line 2060 of file CarScript.c.
  {
    return m_PlayCrashSoundHeavy;
  }
References m_PlayCrashSoundHeavy.
Referenced by OnVariablesSynchronized().
GetCrashLightSound()
bool GetCrashLightSound () protected
Definition at line 2041 of file CarScript.c.
  {
    return m_PlayCrashSoundLight;
  }
References m_PlayCrashSoundLight.
Referenced by OnVariablesSynchronized().
GetCrewIndex()
int GetCrewIndex (string selection) protected
Definition at line 2142 of file CarScript.c.
  {
    return -1;
  }
GetDebugActions()
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList) protected
Definition at line 538 of file CarScript.c.
  {
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.CAR_HORN_START_SHORT, "Car Horn Start Short", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.CAR_HORN_START_LONG, "Car Horn Start Long", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.CAR_HORN_STOP, "Car Horn Stop", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.SEPARATOR, "Car Fuel", FadeColors.RED));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.CAR_FUEL_FULL, "Full", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.CAR_FUEL_EMPTY, "Empty", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.CAR_FUEL_INCREASE, "10% increase", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.CAR_FUEL_DECREASE, "10% decrease", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.SEPARATOR, "___________________________", FadeColors.RED));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.SEPARATOR, "Car Cooler", FadeColors.RED));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.CAR_COOLANT_FULL, "Full", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.CAR_COOLANT_EMPTY, "Empty", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.CAR_COOLANT_INCREASE, "10% increase", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.CAR_COOLANT_DECREASE, "10% decrease", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.SEPARATOR, "___________________________", FadeColors.RED));
    super.GetDebugActions(outputList);
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.SEPARATOR, "___________________________", FadeColors.RED));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.DELETE, "Delete", FadeColors.RED));
  }
References SAT_DEBUG_ACTION.
GetDefaultHitPosition()
override vector GetDefaultHitPosition () protected
Definition at line 2478 of file CarScript.c.
  {
    return vector.Zero;
  }
References vector::Zero.
GetDoorConditionPointFromSelection()
string GetDoorConditionPointFromSelection (string selection) protected
Definition at line 2111 of file CarScript.c.
  {
    switch (selection)
    {
    case "seat_driver":
      return "seat_con_1_1";
      break;
    case "seat_codriver":
      return "seat_con_2_1";
      break;
    case "seat_cargo1":
      return "seat_con_1_2";
      break;
    case "seat_cargo2":
      return "seat_con_2_2";
      break;
    }
    return "";
  }
GetDoorInvSlotNameFromSeatPos()
string GetDoorInvSlotNameFromSeatPos (int posIdx) protected
Definition at line 2137 of file CarScript.c.
  {
    return "";
  }
GetDoorSelectionNameFromSeatPos()
string GetDoorSelectionNameFromSeatPos (int posIdx) protected
Definition at line 2132 of file CarScript.c.
  {
    return "";
  }
GetEnginePointPosWS()
vector GetEnginePointPosWS () protected
Definition at line 455 of file CarScript.c.
  {
    return ModelToWorld(m_enginePos);
  }
References m_enginePos.
GetEnginePosWS()
vector GetEnginePosWS () protected
Definition at line 440 of file CarScript.c.
  {
    return ModelToWorld(m_DrownEnginePos);
  }
References m_DrownEnginePos.
Referenced by CreateCarDestroyedEffect(), and OnUpdate().
GetEnviroHeatComfortOverride()
float GetEnviroHeatComfortOverride () protected
DEPRECATED.
GetFrontPointPosWS()
vector GetFrontPointPosWS () protected
Definition at line 459 of file CarScript.c.
  {
    return ModelToWorld(m_frontPos);
  }
References m_frontPos.
GetLiquidThroughputCoef()
override float GetLiquidThroughputCoef () protected
Definition at line 484 of file CarScript.c.
  {
    return LIQUID_THROUGHPUT_CAR_DEFAULT;
  }
References LIQUID_THROUGHPUT_CAR_DEFAULT.
GetMomentum()
float GetMomentum () protected
Definition at line 2494 of file CarScript.c.
  {
    return GetVelocity(this).Length() * dBodyGetMass(this);
  }
References dBodyGetMass(), and GetVelocity().
Referenced by CheckContactCache(), EOnPostSimulate(), and OnContact().
GetPushForceCoefficientMultiplier()
float GetPushForceCoefficientMultiplier () protected
Definition at line 2499 of file CarScript.c.
  {
    return 1.0;
  }
GetRadiator()
EntityAI GetRadiator () protected
Definition at line 2209 of file CarScript.c.
  {
    return m_Radiator;
  }
References m_Radiator.
Referenced by CarPartsHealthCheck().
GetRefillPointPosWS()
vector GetRefillPointPosWS () protected
Definition at line 450 of file CarScript.c.
  {
    return ModelToWorld(m_fuelPos);
  }
References m_fuelPos.
HandleByCrewMemberState()
override void HandleByCrewMemberState (ECrewMemberState state) protected
Definition at line 1415 of file CarScript.c.
  {
    switch (state)
    {
    case ECrewMemberState.UNCONSCIOUS:
      foreach (int unconsciousCrewMemberIndex : m_UnconsciousCrewMemberIndices)
      {
        if (unconsciousCrewMemberIndex == DayZPlayerConstants.VEHICLESEAT_DRIVER)
        {
          EngineStop();
          SetBrake(0.5);
        }
        m_UnconsciousCrewMemberIndices.RemoveItem(unconsciousCrewMemberIndex);
      }
      break
    case ECrewMemberState.DEAD:
      foreach (int deadCrewMemberIndex : m_DeadCrewMemberIndices)
      {
        if (deadCrewMemberIndex == DayZPlayerConstants.VEHICLESEAT_DRIVER)
        {
          EngineStop();
          SetBrake(0.5);
        }
        m_DeadCrewMemberIndices.RemoveItem(deadCrewMemberIndex);
      }
      break
    }
  }
References m_DeadCrewMemberIndices, and m_UnconsciousCrewMemberIndices.
Referenced by EOnPostSimulate().
HandleCarHornSound()
void HandleCarHornSound (ECarHornState pState) protected
Definition at line 1310 of file CarScript.c.
  {
    switch (pState)
    {
    case ECarHornState.SHORT:
      PlaySoundSet(m_CarHornSoundEffect, m_CarHornShortSoundName, 0, 0, false);
      break;
    case ECarHornState.LONG:
      PlaySoundSet(m_CarHornSoundEffect, m_CarHornLongSoundName, 0, 0, true);
      break;
    default:
      CleanupSound(m_CarHornSoundEffect);
      break;
    }
  }
References CleanupSound(), m_CarHornLongSoundName, m_CarHornShortSoundName, and m_CarHornSoundEffect.
Referenced by OnVariablesSynchronized().
HandleDoorsSound()
void HandleDoorsSound (string animSource, float phase) protected
Definition at line 1267 of file CarScript.c.
  {
    switch (animSource)
    {
    case "doorsdriver":
    case "doorscodriver":
    case "doorscargo1":
    case "doorscargo2":
    case "doorshood":
    case "doorstrunk":
      EffectSound sound;
      if (phase == 0)
        sound = SEffectManager.PlaySound(m_CarDoorOpenSound, GetPosition());
      else
        sound = SEffectManager.PlaySound(m_CarDoorCloseSound, GetPosition());
      if (sound)
        sound.SetAutodestroy(true);
      break;
    }
  }
References GetPosition, m_CarDoorCloseSound, m_CarDoorOpenSound, and SEffectManager::PlaySound().
Referenced by OnAnimationPhaseStarted().
HandleEngineSound()
void HandleEngineSound (CarEngineSoundState state) protected
postpone the engine sound played from c++ on soundcontroller (via OnSound override)
Definition at line 1326 of file CarScript.c.
  {
#ifndef SERVER
    PlayerBase player = null;
    EffectSound sound = null;
    WaveKind waveKind = WaveKind.WAVEEFFECT;
    switch (state)
    {
    case CarEngineSoundState.STARTING:
      m_PreStartSound = SEffectManager.PlaySound("Offroad_02_Starting_SoundSet", ModelToWorld(GetEnginePos()));
      m_PreStartSound.SetSoundFadeOut(0.15);
      break;
    case CarEngineSoundState.START_OK:
      // play different sound based on selected camera
      if (Class.CastTo(player, CrewMember(0)))
      {
        if (!player.IsCameraInsideVehicle())
          waveKind = WaveKind.WAVEEFFECTEX;
        sound = SEffectManager.CreateSound(m_EngineStartOK, ModelToWorld(GetEnginePos()));
        if (sound)
        {
          sound.SetSoundWaveKind(waveKind);
          sound.SoundPlay();
          sound.SetAutodestroy(true);
        }
      }
      GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLater(SetEngineStarted, 1000, false, true);
      break;
    case CarEngineSoundState.START_NO_FUEL:
      sound = SEffectManager.PlaySound("offroad_engine_failed_start_fuel_SoundSet", ModelToWorld(GetEnginePos()));
      sound.SetAutodestroy(true);
      break;
    case CarEngineSoundState.START_NO_BATTERY:
      sound = SEffectManager.PlaySound("offroad_engine_failed_start_battery_SoundSet", ModelToWorld(GetEnginePos()));
      sound.SetAutodestroy(true);
      break;
    case CarEngineSoundState.START_NO_SPARKPLUG:
      sound = SEffectManager.PlaySound("offroad_engine_failed_start_sparkplugs_SoundSet", ModelToWorld(GetEnginePos()));
      sound.SetAutodestroy(true);
      break;
    case CarEngineSoundState.STOP_OK:
    case CarEngineSoundState.STOP_NO_FUEL:
      // play different sound based on selected camera
      if (Class.CastTo(player, CrewMember(0)))
      {
        if (!player.IsCameraInsideVehicle())
          waveKind = WaveKind.WAVEEFFECTEX;
        sound = SEffectManager.CreateSound(m_EngineStopFuel, ModelToWorld(GetEnginePos()));
        if (sound)
        {
          sound.SetSoundWaveKind(waveKind);
          sound.SoundPlay();
          sound.SetAutodestroy(true);
        }
      }
      SetEngineStarted(false);
      break;
    }
#endif
  }
References CALL_CATEGORY_GAMEPLAY, Class::CastTo(), SEffectManager::CreateSound(), GetGame(), m_EngineStartOK, m_EngineStopFuel, m_PreStartSound, SEffectManager::PlaySound(), and SetEngineStarted().
Referenced by OnBeforeEngineStart(), OnEngineStart(), and OnEngineStop().
HandleSeatAdjustmentSound()
void HandleSeatAdjustmentSound (string animSource, float phase) protected
Definition at line 1290 of file CarScript.c.
  {
    switch (animSource)
    {
    case "seatdriver":
    case "seatcodriver":
      EffectSound sound;
      if (phase == 0)
        sound = SEffectManager.PlaySound(m_CarSeatShiftInSound, GetPosition());
      else
        sound = SEffectManager.PlaySound(m_CarSeatShiftOutSound, GetPosition());
      if (sound)
        sound.SetAutodestroy(true);
      break;
    }
  }
References GetPosition, m_CarSeatShiftInSound, m_CarSeatShiftOutSound, and SEffectManager::PlaySound().
Referenced by OnAnimationPhaseStarted().
HasEngineZoneReceivedHit()
bool HasEngineZoneReceivedHit () protected
Definition at line 2489 of file CarScript.c.
  {
    return m_EngineZoneReceivedHit;
  }
References m_EngineZoneReceivedHit.
HasRadiator()
bool HasRadiator () protected
Definition at line 2204 of file CarScript.c.
  {
    return m_Radiator != null;
  }
References m_Radiator.
Referenced by CarPartsHealthCheck().
InitializeActions()
void InitializeActions () protected
Definition at line 2289 of file CarScript.c.
  {
    m_InputActionMap = m_CarTypeActionsMap.Get(this.Type());
    if (!m_InputActionMap)
    {
      TInputActionMap iam = new TInputActionMap;
      m_InputActionMap = iam;
      SetActions();
      m_CarTypeActionsMap.Insert(this.Type(), m_InputActionMap);
    }
  }
References m_CarTypeActionsMap, m_InputActionMap, CarScript::SetActions(), and Type.
IsHandbrakeActive()
bool IsHandbrakeActive () protected
Definition at line 2219 of file CarScript.c.
  {
    return GetHandbrake() > 0.0;
  }
IsInventoryVisible()
override bool IsInventoryVisible () protected
Definition at line 2363 of file CarScript.c.
  {
    return (GetGame().GetPlayer() && (!GetGame().GetPlayer().GetCommand_Vehicle() || GetGame().GetPlayer().GetCommand_Vehicle().GetTransport() == this));
  }
References GetCommand_Vehicle(), GetGame(), and GetPlayer().
IsMoving()
bool IsMoving () protected
Definition at line 2214 of file CarScript.c.
  {
    return GetSpeedometerAbsolute() > 3.5;
  }
Referenced by CanReleaseAttachment().
IsScriptedLightsOn()
bool IsScriptedLightsOn () protected
Propper way to get if light is swiched on. Use instead of IsLightsOn().
Definition at line 1585 of file CarScript.c.
  {
    return m_HeadlightsOn;
  }
References m_HeadlightsOn.
Referenced by EEItemDetached(), and OnUpdate().
IsVitalCarBattery()
bool IsVitalCarBattery () protected
Definition at line 2169 of file CarScript.c.
  {
    return true;
  }
IsVitalEngineBelt()
bool IsVitalEngineBelt () protected
Definition at line 2189 of file CarScript.c.
  {
    return true;
  }
IsVitalFuelTank()
bool IsVitalFuelTank () protected
Definition at line 2199 of file CarScript.c.
  {
    return true;
  }
Referenced by EOnPostSimulate().
IsVitalGlowPlug()
bool IsVitalGlowPlug () protected
Definition at line 2184 of file CarScript.c.
  {
    return true;
  }
IsVitalRadiator()
bool IsVitalRadiator () protected
Definition at line 2194 of file CarScript.c.
  {
    return true;
  }
IsVitalSparkPlug()
bool IsVitalSparkPlug () protected
Definition at line 2179 of file CarScript.c.
  {
    return true;
  }
IsVitalTruckBattery()
bool IsVitalTruckBattery () protected
Definition at line 2174 of file CarScript.c.
  {
    return true;
  }
LeakFluid()
void LeakFluid (CarFluid fluid) protected
Definition at line 2004 of file CarScript.c.
  {
    float ammount = 0;
    switch (fluid)
    {
    case CarFluid.COOLANT:
      ammount = (1 - m_RadiatorHealth) * Math.RandomFloat(0.02, 0.05); //CARS_LEAK_TICK_MIN; CARS_LEAK_TICK_MAX
      Leak(fluid, ammount);
      break;
    case CarFluid.OIL:
      ammount = (1 - m_EngineHealth) * Math.RandomFloat(0.02, 1.0); //CARS_LEAK_OIL_MIN; CARS_LEAK_OIL_MAX
      Leak(fluid, ammount);
      break;
    case CarFluid.FUEL:
      ammount = (1 - m_FuelTankHealth) * Math.RandomFloat(0.02, 0.05); //CARS_LEAK_TICK_MIN; CARS_LEAK_TICK_MAX
      Leak(fluid, ammount);
      break;
    }
  }
References m_EngineHealth, m_FuelTankHealth, m_RadiatorHealth, and Math::RandomFloat().
Referenced by EOnPostSimulate().
LeftFrontLightShineOff()
void LeftFrontLightShineOff () protected
Definition at line 1867 of file CarScript.c.
  {
    string material = ConfigGetString("frontReflectorMatOff");
    if (material)
      SetObjectMaterial(SELECTION_ID_FRONT_LIGHT_L, material);
  }
References SELECTION_ID_FRONT_LIGHT_L.
Referenced by UpdateLightsServer().
LeftFrontLightShineOn()
void LeftFrontLightShineOn () protected
Definition at line 1851 of file CarScript.c.
  {
    string material = ConfigGetString("frontReflectorMatOn");
    if (material)
      SetObjectMaterial(SELECTION_ID_FRONT_LIGHT_L, material);
  }
References SELECTION_ID_FRONT_LIGHT_L.
Referenced by UpdateLightsServer().
MarkCrewMemberDead()
override void MarkCrewMemberDead (int crewMemberIndex) protected
Definition at line 1406 of file CarScript.c.
  {
    set<int> crewMemberIndicesCopy = new set<int>();
    crewMemberIndicesCopy.Copy(m_DeadCrewMemberIndices);
    crewMemberIndicesCopy.Insert(crewMemberIndex);
    m_DeadCrewMemberIndices = crewMemberIndicesCopy;
  }
References m_DeadCrewMemberIndices.
MarkCrewMemberUnconscious()
override void MarkCrewMemberUnconscious (int crewMemberIndex) protected
Definition at line 1397 of file CarScript.c.
  {
    set<int> crewMemberIndicesCopy = new set<int>();
    crewMemberIndicesCopy.Copy(m_UnconsciousCrewMemberIndices);
    crewMemberIndicesCopy.Insert(crewMemberIndex);
    m_UnconsciousCrewMemberIndices = crewMemberIndicesCopy;
  }
References m_UnconsciousCrewMemberIndices.
NoRearLight()
void NoRearLight () protected
Definition at line 1845 of file CarScript.c.
  {
    m_RearLight.FadeOut();
    m_RearLight = null;
  }
References m_RearLight.
Referenced by UpdateLightsClient().
OnAction()
override bool OnAction (int action_id, Man player, ParamsReadContext ctx) protected
Definition at line 563 of file CarScript.c.
  {
    if (super.OnAction(action_id, player, ctx))
      return true;
    if (!GetGame().IsServer())
      return false;
    switch (action_id)
    {
    case EActions.CAR_HORN_START_SHORT:
      SetCarHornState(ECarHornState.SHORT);
      return true;
    case EActions.CAR_HORN_START_LONG:
      SetCarHornState(ECarHornState.LONG);
      return true;
    case EActions.CAR_HORN_STOP:
      SetCarHornState(ECarHornState.OFF);
      return true;
    case EActions.CAR_FUEL_FULL:
      Fill(CarFluid.FUEL, GetFluidCapacity(CarFluid.FUEL));
      return true;
    case EActions.CAR_FUEL_EMPTY:
      LeakAll(CarFluid.FUEL);
      return true;
    case EActions.CAR_FUEL_INCREASE:
      Fill(CarFluid.FUEL, GetFluidCapacity(CarFluid.FUEL) * 0.1);
      return true;
    case EActions.CAR_FUEL_DECREASE:
      Leak(CarFluid.FUEL, GetFluidCapacity(CarFluid.FUEL) * 0.1);
      return true;
    case EActions.CAR_COOLANT_FULL:
      Fill(CarFluid.COOLANT, GetFluidCapacity(CarFluid.COOLANT));
      return true;
    case EActions.CAR_COOLANT_EMPTY:
      LeakAll(CarFluid.COOLANT);
      return true;
    case EActions.CAR_COOLANT_INCREASE:
      Fill(CarFluid.COOLANT, GetFluidCapacity(CarFluid.COOLANT) * 0.1);
      return true;
    case EActions.CAR_COOLANT_DECREASE:
      Leak(CarFluid.COOLANT, GetFluidCapacity(CarFluid.COOLANT) * 0.1);
      return true;
    case EActions.DELETE:
      Delete();
      return true;
    }
    return false;
  }
References GetGame(), and SetCarHornState().
OnAnimationPhaseStarted()
override void OnAnimationPhaseStarted (string animSource, float phase) protected
Definition at line 1259 of file CarScript.c.
  {
#ifndef SERVER
    HandleDoorsSound(animSource, phase);
    HandleSeatAdjustmentSound(animSource, phase);
#endif
  }
References HandleDoorsSound(), and HandleSeatAdjustmentSound().
OnAttachmentRuined()
override void OnAttachmentRuined (EntityAI attachment) protected
Definition at line 736 of file CarScript.c.
  {
    super.OnAttachmentRuined(attachment);
    UpdateHeadlightState();
    UpdateLights();
  }
References UpdateHeadlightState(), and UpdateLights().
OnBeforeEngineStart()
override bool OnBeforeEngineStart () protected
Gets called everytime the game wants to start the engine. This callback is called on server only.
Returns
true if the engine can start, false otherwise.
Definition at line 1486 of file CarScript.c.
  {
    EntityAI item = null;
    if (m_EngineStartDoOnce)
    {
      m_EngineStartDoOnce = false;
      return m_EngineBeforeStart;
    }
    if (GetFluidFraction(CarFluid.FUEL) <= 0)
    {
      HandleEngineSound(CarEngineSoundState.START_NO_FUEL);
      return false;
    }
    if (IsVitalCarBattery() || IsVitalTruckBattery())
    {
      item = GetBattery();
      if (!item || (item && (item.IsRuined() || item.GetCompEM().GetEnergy() < m_BatteryEnergyStartMin)))
      {
        m_EngineStartDoOnce = true;
        HandleEngineSound(CarEngineSoundState.START_NO_BATTERY);
        return false;
      }
    }
    if (IsVitalSparkPlug())
    {
      item = FindAttachmentBySlotName("SparkPlug");
      if (!item || (item && item.IsRuined()))
      {
        m_EngineStartDoOnce = true;
        HandleEngineSound(CarEngineSoundState.START_NO_SPARKPLUG);
        return false;
      }
    }
    if (IsVitalGlowPlug())
    {
      item = FindAttachmentBySlotName("GlowPlug");
      if (!item || (item && item.IsRuined()))
      {
        m_EngineStartDoOnce = true;
        HandleEngineSound(CarEngineSoundState.START_NO_SPARKPLUG);
        return false;
      }
    }
    if (!m_EngineBeforeStart)
    {
      m_EngineBeforeStart = true;
      HandleEngineSound(CarEngineSoundState.STARTING);
    }
    return true;
  }
References GetBattery(), HandleEngineSound(), CarScript::IsVitalCarBattery(), CarScript::IsVitalGlowPlug(), CarScript::IsVitalSparkPlug(), CarScript::IsVitalTruckBattery(), m_BatteryEnergyStartMin, m_EngineBeforeStart, and m_EngineStartDoOnce.
OnBeforeSwitchLights()
bool OnBeforeSwitchLights (bool toOn) protected
DEPRECATED Gets called everytime the game wants to switch the lights.
Returns
true when lights can be switched, false otherwise.
Definition at line 1579 of file CarScript.c.
  {
    return true;
  }
OnBrakesPressed()
void OnBrakesPressed () protected
Definition at line 969 of file CarScript.c.
  {
    UpdateLights();
  }
References UpdateLights().
Referenced by OnUpdate().
OnBrakesReleased()
void OnBrakesReleased () protected
Definition at line 974 of file CarScript.c.
  {
    UpdateLights();
  }
References UpdateLights().
Referenced by OnUpdate().
OnContact()
override void OnContact (string zoneName, vector localPos, IEntity other, Contact data) protected
WARNING: Can be called very frequently in one frame, use with caution.
Definition at line 1058 of file CarScript.c.
  {
    if (GetGame().IsServer())
    {
#ifdef DIAG_DEVELOPER
      m_ContactCalled = true;
      if (DEBUG_OUTPUT_TYPE & EVehicleDebugOutputType.CONTACT)
      {
        string output = "Zone: " + zoneName + " | Impulse:" + data.Impulse;
        Debug.Log(output);
      }
#endif
      if (m_ContactCache.Count() == 0)
      {
        array<ref CarContactData> ccd = new array<ref CarContactData>;
        m_ContactCache.Insert(zoneName, ccd);
        float momentumDelta = GetMomentum() - m_MomentumPrevTick;
        float dot = vector.Dot(m_VelocityPrevTick.Normalized(), GetVelocity(this).Normalized());
        if (dot < 0)
          momentumDelta = m_MomentumPrevTick;
        ccd.Insert(new CarContactData(localPos, other, momentumDelta));
      }
    }
  }
References vector::Dot(), GetGame(), GetMomentum(), GetVelocity(), Debug::Log(), m_ContactCache, m_MomentumPrevTick, m_VelocityPrevTick, and vector::Normalized().
OnEngineStart()
override void OnEngineStart () protected
Gets called everytime the engine starts.
Definition at line 1551 of file CarScript.c.
  {
    ItemBase battery = GetBattery();
    if (GetGame().IsServer() && battery)
      battery.GetCompEM().ConsumeEnergy(GetBatteryConsumption());
    UpdateLights();
    HandleEngineSound(CarEngineSoundState.START_OK);
    m_EngineBeforeStart = false;
  }
References GetBattery(), GetBatteryConsumption(), GetGame(), HandleEngineSound(), m_EngineBeforeStart, and UpdateLights().
OnEngineStop()
override void OnEngineStop () protected
Gets called everytime the engine stops.
Definition at line 1565 of file CarScript.c.
  {
    UpdateLights();
    HandleEngineSound(CarEngineSoundState.STOP_OK);
    SetEngineZoneReceivedHit(false);
    m_EngineBeforeStart = false;
  }
References HandleEngineSound(), m_EngineBeforeStart, SetEngineZoneReceivedHit(), and UpdateLights().
OnFluidChanged()
override void OnFluidChanged (CarFluid fluid, float newValue, float oldValue) protected
Gets called everytime when the specified vehicle's fluid changes its current value eg. when car is consuming fuel.
This callback is called on both server and client.
Definition at line 1458 of file CarScript.c.
  {
    switch (fluid)
    {
    case CarFluid.FUEL:
      m_FuelAmmount = newValue;
      break;
    case CarFluid.OIL:
      m_OilAmmount = newValue;
      break;
    case CarFluid.BRAKE:
      m_BrakeAmmount = newValue;
      break;
    case CarFluid.COOLANT:
      m_CoolantAmmount = newValue;
      break;
    }
  }
References m_BrakeAmmount, m_CoolantAmmount, m_FuelAmmount, and m_OilAmmount.
OnGearChanged()
override void OnGearChanged (int newGear, int oldGear) protected
Definition at line 1544 of file CarScript.c.
  {
    //Debug.Log(string.Format("OnGearChanged newGear=%1,oldGear=%2", newGear, oldGear));
    UpdateLights(newGear);
  }
References UpdateLights().
OnSound()
override float OnSound (CarSoundCtrl ctrl, float oldValue) protected
Gets called every sound simulation step. In this callback, user can modify behaviour of sound controllers The higher the return value is the more muted sound is.
Definition at line 1246 of file CarScript.c.
  {
    switch (ctrl)
    {
    case CarSoundCtrl.ENGINE:
      if (!m_EngineStarted)
        return 0.0;
      break;
    }
    return oldValue;
  }
References m_EngineStarted.
OnUpdate()
override void OnUpdate (float dt) protected
Definition at line 979 of file CarScript.c.
  {
    if (GetGame().IsServer())
    {
      ItemBase battery = GetBattery();
      if (battery)
      {
        if (EngineIsOn())
        {
          m_BatteryTimer += dt;
          if (m_BatteryTimer >= BATTERY_UPDATE_DELAY)
          {
            battery.GetCompEM().ConsumeEnergy(GetBatteryRechargeRate() * m_BatteryTimer);
            m_BatteryTimer = 0;
          }
        }
        else if (!EngineIsOn() && IsScriptedLightsOn())
        {
          m_BatteryTimer += dt;
          if (m_BatteryTimer >= BATTERY_UPDATE_DELAY)
          {
            battery.GetCompEM().ConsumeEnergy(GetBatteryRuntimeConsumption() * m_BatteryTimer);
            m_BatteryTimer = 0;
            if (battery.GetCompEM().GetEnergy() <= 0)
              ToggleHeadlights();
          }
        }
      }
      if (GetGame().GetWaterDepth(GetEnginePosWS()) > 0)
      {
        m_DrownTime += dt;
        if (m_DrownTime > DROWN_ENGINE_THRESHOLD)
        {
          // *dt to get damage per second
          AddHealth("Engine", "Health", -DROWN_ENGINE_DAMAGE * dt);
          SetEngineZoneReceivedHit(true);
        }
      }
      else
        m_DrownTime = 0;
    }
    // For visualisation of brake lights for all players
    float brake_coef = GetBrake();
    if (brake_coef > 0)
    {
      if (!m_BrakesArePressed)
      {
        m_BrakesArePressed = true;
        SetSynchDirty();
        OnBrakesPressed();
      }
    }
    else
    {
      if (m_BrakesArePressed)
      {
        m_BrakesArePressed = false;
        SetSynchDirty();
        OnBrakesReleased();
      }
    }
    if ((!GetGame().IsDedicatedServer()) && m_ForceUpdateLights)
    {
      UpdateLights();
      m_ForceUpdateLights = false;
    }
  }
References BATTERY_UPDATE_DELAY, DROWN_ENGINE_DAMAGE, DROWN_ENGINE_THRESHOLD, GetBattery(), GetBatteryRechargeRate(), GetBatteryRuntimeConsumption(), GetEnginePosWS(), GetGame(), IsScriptedLightsOn(), m_BatteryTimer, m_BrakesArePressed, m_DrownTime, m_ForceUpdateLights, OnBrakesPressed(), OnBrakesReleased(), SetEngineZoneReceivedHit(), ToggleHeadlights(), and UpdateLights().
OnVariablesSynchronized()
override void OnVariablesSynchronized () protected
Definition at line 616 of file CarScript.c.
  {
    super.OnVariablesSynchronized();
    if (GetCrashHeavySound())
      PlayCrashHeavySound();
    else if (GetCrashLightSound())
      PlayCrashLightSound();
    HandleCarHornSound(m_CarHornState);
    UpdateLights();
  }
References GetCrashHeavySound(), GetCrashLightSound(), HandleCarHornSound(), m_CarHornState, PlayCrashHeavySound(), PlayCrashLightSound(), and UpdateLights().
PlayCrashHeavySound()
void PlayCrashHeavySound () protected
Definition at line 2074 of file CarScript.c.
  {
    PlaySoundEx("offroad_hit_heavy_SoundSet", m_CrashSoundHeavy, m_PlayCrashSoundHeavy);
  }
References m_CrashSoundHeavy, m_PlayCrashSoundHeavy, and PlaySoundEx().
Referenced by OnVariablesSynchronized().
PlayCrashLightSound()
void PlayCrashLightSound () protected
Definition at line 2055 of file CarScript.c.
  {
    PlaySoundEx("offroad_hit_light_SoundSet", m_CrashSoundLight, m_PlayCrashSoundLight);
  }
References m_CrashSoundLight, m_PlayCrashSoundLight, and PlaySoundEx().
Referenced by OnVariablesSynchronized().
PlaySound()
void PlaySound (string soundset, ref EffectSound sound, out bool soundbool) protected
Definition at line 2101 of file CarScript.c.
  {
    PlaySoundEx(soundset, sound, soundbool);
  }
References PlaySoundEx().
PlaySoundEx()
void PlaySoundEx (string soundset, EffectSound sound, out bool soundbool) protected
Definition at line 2079 of file CarScript.c.
  {
#ifndef SERVER
    if (!sound)
    {
      sound = SEffectManager.PlaySoundCachedParams(soundset, GetPosition());
      if (sound)
        sound.SetAutodestroy(true);
    }
    else
    {
      if (!sound.IsSoundPlaying())
      {
        sound.SetPosition(GetPosition());
        sound.SoundPlay();
      }
    }
    soundbool = false;
#endif
  }
References GetPosition, and SEffectManager::PlaySoundCachedParams().
Referenced by EEHealthLevelChanged(), PlayCrashHeavySound(), PlayCrashLightSound(), and PlaySound().
RemoveAction()
void RemoveAction (typename actionName) protected
Definition at line 2352 of file CarScript.c.
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    ActionBase action = player.GetActionManager().GetAction(actionName);
    typename ai = action.GetInputType();
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (action_array)
      action_array.RemoveItem(action);
  }
References GetGame(), GetPlayer(), and m_InputActionMap.
ReverseLightsShineOff()
void ReverseLightsShineOff () protected
Definition at line 1894 of file CarScript.c.
  {
    string material = ConfigGetString("ReverseReflectorMatOff");
    if (material)
    {
      SetObjectMaterial(SELECTION_ID_REVERSE_LIGHT_L, material);
      SetObjectMaterial(SELECTION_ID_REVERSE_LIGHT_R, material);
    }
  }
References SELECTION_ID_REVERSE_LIGHT_L, and SELECTION_ID_REVERSE_LIGHT_R.
Referenced by UpdateLightsServer().
ReverseLightsShineOn()
void ReverseLightsShineOn () protected
Definition at line 1883 of file CarScript.c.
  {
    string material = ConfigGetString("ReverseReflectorMatOn");
    if (material)
    {
      SetObjectMaterial(SELECTION_ID_REVERSE_LIGHT_L, material);
      SetObjectMaterial(SELECTION_ID_REVERSE_LIGHT_R, material);
    }
  }
References SELECTION_ID_REVERSE_LIGHT_L, and SELECTION_ID_REVERSE_LIGHT_R.
Referenced by UpdateLightsServer().
ReverseRearLight()
void ReverseRearLight () protected
Definition at line 1834 of file CarScript.c.
  {
    m_RearLight.SetAsSegregatedReverseLight();
  }
References m_RearLight.
Referenced by UpdateLightsClient().
RightFrontLightShineOff()
void RightFrontLightShineOff () protected
Definition at line 1875 of file CarScript.c.
  {
    string material = ConfigGetString("frontReflectorMatOff");
    if (material)
      SetObjectMaterial(SELECTION_ID_FRONT_LIGHT_R, material);
  }
References SELECTION_ID_FRONT_LIGHT_R.
Referenced by UpdateLightsServer().
RightFrontLightShineOn()
void RightFrontLightShineOn () protected
Definition at line 1859 of file CarScript.c.
  {
    string material = ConfigGetString("frontReflectorMatOn");
    if (material)
      SetObjectMaterial(SELECTION_ID_FRONT_LIGHT_R, material);
  }
References SELECTION_ID_FRONT_LIGHT_R.
Referenced by UpdateLightsServer().
SetActions()
void SetActions () protected
Definition at line 2312 of file CarScript.c.
  {
    AddAction(ActionOpenCarDoorsOutside);
    AddAction(ActionCloseCarDoorsOutside);
    AddAction(ActionGetInTransport);
    AddAction(ActionSwitchLights);
    AddAction(ActionCarHornShort);
    AddAction(ActionCarHornLong);
    AddAction(ActionPushCar);
  }
References ActionCarHornShort(), and AddAction().
SetCarHornState()
void SetCarHornState (int pState) protected
Definition at line 2453 of file CarScript.c.
  {
    m_CarHornState = pState;
    SetSynchDirty();
    if (GetGame().IsServer())
      GenerateCarHornAINoise(pState);
  }
References GenerateCarHornAINoise(), GetGame(), and m_CarHornState.
Referenced by OnAction().
SetEngineStarted()
void SetEngineStarted (bool started) protected
Definition at line 2231 of file CarScript.c.
  {
    m_EngineStarted = started;
  }
References m_EngineStarted.
Referenced by HandleEngineSound().
SetEngineZoneReceivedHit()
void SetEngineZoneReceivedHit (bool pState) protected
Definition at line 2483 of file CarScript.c.
  {
    m_EngineZoneReceivedHit = pState;
    SetSynchDirty();
  }
References m_EngineZoneReceivedHit.
Referenced by EEHitBy(), EOnPostSimulate(), OnEngineStop(), and OnUpdate().
SpawnAdditionalItems()
void SpawnAdditionalItems () protected
Definition at line 2554 of file CarScript.c.
  {
    GetInventory().CreateInInventory("Wrench");
    GetInventory().CreateInInventory("LugWrench");
    GetInventory().CreateInInventory("Screwdriver");
    GetInventory().CreateInInventory("EpoxyPutty");
    GetInventory().CreateInInventory("CanisterGasoline");
    EntityAI ent;
    ItemBase container;
    ent = GetInventory().CreateInInventory("CanisterGasoline");
    if (Class.CastTo(container, ent))
      container.SetLiquidType(LIQUID_WATER, true);
    ent = GetInventory().CreateInInventory("Blowtorch");
    if (ent)
      ent.GetInventory().CreateInInventory("LargeGasCanister");
    ent = GetInventory().CreateInInventory("Blowtorch");
    if (ent)
      ent.GetInventory().CreateInInventory("LargeGasCanister");
  }
References Class::CastTo(), and LIQUID_WATER.
Referenced by CarScript::OnDebugSpawn(), CivilianSedan::OnDebugSpawn(), Hatchback_02::OnDebugSpawn(), Sedan_02::OnDebugSpawn(), and Truck_01_Covered::OnDebugSpawn().
SpawnUniversalParts()
void SpawnUniversalParts () protected
Definition at line 2516 of file CarScript.c.
  {
    GetInventory().CreateInInventory("HeadlightH7");
    GetInventory().CreateInInventory("HeadlightH7");
    GetInventory().CreateInInventory("HeadlightH7");
    GetInventory().CreateInInventory("HeadlightH7");
    if (IsVitalCarBattery())
    {
      GetInventory().CreateInInventory("CarBattery");
      GetInventory().CreateInInventory("CarBattery");
    }
    if (IsVitalTruckBattery())
    {
      GetInventory().CreateInInventory("TruckBattery");
      GetInventory().CreateInInventory("TruckBattery");
    }
    if (IsVitalRadiator())
    {
      GetInventory().CreateInInventory("CarRadiator");
      GetInventory().CreateInInventory("CarRadiator");
    }
    if (IsVitalSparkPlug())
    {
      GetInventory().CreateInInventory("SparkPlug");
      GetInventory().CreateInInventory("SparkPlug");
    }
    if (IsVitalGlowPlug())
    {
      GetInventory().CreateInInventory("GlowPlug");
      GetInventory().CreateInInventory("GlowPlug");
    }
  }
References CarScript::IsVitalCarBattery(), CarScript::IsVitalGlowPlug(), CarScript::IsVitalRadiator(), CarScript::IsVitalSparkPlug(), and CarScript::IsVitalTruckBattery().
Referenced by CarScript::OnDebugSpawn(), CivilianSedan::OnDebugSpawn(), Hatchback_02::OnDebugSpawn(), Sedan_02::OnDebugSpawn(), and Truck_01_Covered::OnDebugSpawn().
SynchCrashHeavySound()
void SynchCrashHeavySound (bool play) protected
Definition at line 2065 of file CarScript.c.
  {
    if (m_PlayCrashSoundHeavy != play)
    {
      m_PlayCrashSoundHeavy = play;
      SetSynchDirty();
    }
  }
References m_PlayCrashSoundHeavy.
Referenced by CheckContactCache().
SynchCrashLightSound()
void SynchCrashLightSound (bool play) protected
Definition at line 2046 of file CarScript.c.
  {
    if (m_PlayCrashSoundLight != play)
    {
      m_PlayCrashSoundLight = play;
      SetSynchDirty();
    }
  }
References m_PlayCrashSoundLight.
Referenced by CheckContactCache().
TailLightsShineOff()
void TailLightsShineOff () protected
Definition at line 1952 of file CarScript.c.
  {
    string material = ConfigGetString("TailReflectorMatOff");
    if (material)
    {
      SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_L, material);
      SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_R, material);
    }
  }
References SELECTION_ID_TAIL_LIGHT_L, and SELECTION_ID_TAIL_LIGHT_R.
Referenced by UpdateLightsServer().
TailLightsShineOn()
void TailLightsShineOn () protected
Definition at line 1927 of file CarScript.c.
  {
    string material = ConfigGetString("TailReflectorMatOn");
    string materialOff = ConfigGetString("TailReflectorMatOff");
    if (material && materialOff)
    {
      if (m_HeadlightsState == CarHeadlightBulbsState.LEFT)
      {
        SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_L, material);
        SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_R, materialOff);
      }
      else if (m_HeadlightsState == CarHeadlightBulbsState.RIGHT)
      {
        SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_L, materialOff);
        SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_R, material);
      }
      else if (m_HeadlightsState == CarHeadlightBulbsState.BOTH)
      {
        SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_L, material);
        SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_R, material);
      }
    }
  }
References m_HeadlightsState, SELECTION_ID_TAIL_LIGHT_L, and SELECTION_ID_TAIL_LIGHT_R.
Referenced by UpdateLightsServer().
ToggleHeadlights()
void ToggleHeadlights () protected
Switches headlights on/off, including the illumination of the control panel and synchronizes this change to all clients.
Definition at line 1591 of file CarScript.c.
  {
    m_HeadlightsOn = !m_HeadlightsOn;
    SetSynchDirty();
  }
References m_HeadlightsOn.
Referenced by EEItemDetached(), and OnUpdate().
TranslateAnimationPhaseToCarDoorState()
CarDoorState TranslateAnimationPhaseToCarDoorState (string animation) protected
Definition at line 2241 of file CarScript.c.
  {
    if (GetAnimationPhase(animation) > 0.5)
      return CarDoorState.DOORS_OPEN;
    else
      return CarDoorState.DOORS_CLOSED;
  }
Referenced by CarScript::GetCarDoorsState().
UpdateHeadlightState()
void UpdateHeadlightState () protected
Definition at line 680 of file CarScript.c.
  {
    EntityAI bulb_L = FindAttachmentBySlotName("Reflector_1_1");
    EntityAI bulb_R = FindAttachmentBySlotName("Reflector_2_1");
    if (bulb_L && !bulb_L.IsRuined() && bulb_R && !bulb_R.IsRuined())
      m_HeadlightsState = CarHeadlightBulbsState.BOTH;
    else if (bulb_L && !bulb_L.IsRuined())
      m_HeadlightsState = CarHeadlightBulbsState.LEFT;
    else if (bulb_R && !bulb_R.IsRuined())
      m_HeadlightsState = CarHeadlightBulbsState.RIGHT;
    else if ((!bulb_L || bulb_L.IsRuined()) && (!bulb_R || bulb_R.IsRuined()))
      m_HeadlightsState = CarHeadlightBulbsState.NONE;
  }
References m_HeadlightsState.
Referenced by CheckContactCache(), EEItemAttached(), EEItemDetached(), and OnAttachmentRuined().
UpdateLights()
void UpdateLights (int new_gear = -1) protected
Definition at line 1597 of file CarScript.c.
  {
#ifndef SERVER
    UpdateLightsClient(new_gear);
#endif
    UpdateLightsServer(new_gear);
  }
References UpdateLightsClient(), and UpdateLightsServer().
Referenced by CheckContactCache(), EEItemAttached(), EEItemDetached(), OnAttachmentRuined(), OnBrakesPressed(), OnBrakesReleased(), OnEngineStart(), OnEngineStop(), OnGearChanged(), OnUpdate(), and OnVariablesSynchronized().
UpdateLightsClient()
void UpdateLightsClient (int newGear = -1) protected
Definition at line 1605 of file CarScript.c.
  {
    int gear;
    if (newGear == -1)
      gear = GetGear();
    else
      gear = newGear;
    if (m_HeadlightsOn)
    {
      if (!m_Headlight && m_HeadlightsState != CarHeadlightBulbsState.NONE)
        m_Headlight = CreateFrontLight();
      if (m_Headlight)
      {
        switch (m_HeadlightsState)
        {
        case CarHeadlightBulbsState.LEFT:
          m_Headlight.AttachOnMemoryPoint(this, m_LeftHeadlightPoint, m_LeftHeadlightTargetPoint);
          m_Headlight.SegregateLight();
          break;
        case CarHeadlightBulbsState.RIGHT:
          m_Headlight.AttachOnMemoryPoint(this, m_RightHeadlightPoint, m_RightHeadlightTargetPoint);
          m_Headlight.SegregateLight();
          break;
        case CarHeadlightBulbsState.BOTH:
          vector local_pos_left = GetMemoryPointPos(m_LeftHeadlightPoint);
          vector local_pos_right = GetMemoryPointPos(m_RightHeadlightPoint);
          vector local_pos_middle = (local_pos_left + local_pos_right) * 0.5;
          m_Headlight.AttachOnObject(this, local_pos_middle);
          m_Headlight.AggregateLight();
          break;
        default:
          m_Headlight.FadeOut();
          m_Headlight = null;
        }
      }
    }
    else
    {
      if (m_Headlight)
      {
        m_Headlight.FadeOut();
        m_Headlight = null;
      }
    }
    // brakes & reverse
    switch (gear)
    {
    case CarGear.REVERSE:
    case CarAutomaticGearboxMode.R:
      if (m_BrakesArePressed)
        m_RearLightType = CarRearLightType.BRAKES_AND_REVERSE;
      else
        m_RearLightType = CarRearLightType.REVERSE_ONLY;
      break;
    default:
      if (m_BrakesArePressed)
        m_RearLightType = CarRearLightType.BRAKES_ONLY;
      else
        m_RearLightType = CarRearLightType.NONE;
    }
    //Debug.Log(string.Format("m_BrakesArePressed=%1, m_RearLightType=%2", m_BrakesArePressed.ToString(), EnumTools.EnumToString(CarRearLightType, m_RearLightType)));
    if (!m_RearLight && m_RearLightType != CarRearLightType.NONE && m_HeadlightsState != CarHeadlightBulbsState.NONE)
    {
      if (EngineIsOn() || m_RearLightType == CarRearLightType.BRAKES_ONLY || m_RearLightType == CarRearLightType.BRAKES_AND_REVERSE)
      {
        m_RearLight = CreateRearLight();
        vector localPos = GetMemoryPointPos(m_ReverseLightPoint);
        m_RearLight.AttachOnObject(this, localPos, "180 0 0");
      }
    }
    // rear lights
    if (m_RearLight && m_RearLightType != CarRearLightType.NONE && m_HeadlightsState != CarHeadlightBulbsState.NONE)
    {
      switch (m_RearLightType)
      {
      case CarRearLightType.BRAKES_ONLY:
        BrakesRearLight();
        break;
      case CarRearLightType.REVERSE_ONLY:
        if (EngineIsOn())
          ReverseRearLight();
        else
          NoRearLight();
        break;
      case CarRearLightType.BRAKES_AND_REVERSE:
        if (EngineIsOn())
          BrakeAndReverseRearLight();
        else
          BrakesRearLight();
        break;
      default:
        NoRearLight();
      }
    }
    else
    {
      if (m_RearLight)
        NoRearLight();
    }
  }
References BrakeAndReverseRearLight(), BrakesRearLight(), CarScript::CreateFrontLight(), CarScript::CreateRearLight(), m_BrakesArePressed, m_Headlight, m_HeadlightsOn, m_HeadlightsState, m_LeftHeadlightPoint, m_LeftHeadlightTargetPoint, m_RearLight, m_RearLightType, m_ReverseLightPoint, m_RightHeadlightPoint, m_RightHeadlightTargetPoint, NoRearLight(), and ReverseRearLight().
Referenced by UpdateLights().
UpdateLightsServer()
void UpdateLightsServer (int newGear = -1) protected
Definition at line 1716 of file CarScript.c.
  {
    int gear;
    if (newGear == -1)
    {
      gear = GetGear();
      if (GearboxGetType() == CarGearboxType.AUTOMATIC)
        gear = GearboxGetMode();
    }
    else
      gear = newGear;
    if (m_HeadlightsOn)
    {
      DashboardShineOn();
      TailLightsShineOn();
      switch (m_HeadlightsState)
      {
      case CarHeadlightBulbsState.LEFT:
        LeftFrontLightShineOn();
        RightFrontLightShineOff();
        break;
      case CarHeadlightBulbsState.RIGHT:
        LeftFrontLightShineOff();
        RightFrontLightShineOn();
        break;
      case CarHeadlightBulbsState.BOTH:
        LeftFrontLightShineOn();
        RightFrontLightShineOn();
        break;
      default:
        LeftFrontLightShineOff();
        RightFrontLightShineOff();
      }
      //Debug.Log(string.Format("m_HeadlightsOn=%1, m_HeadlightsState=%2", m_HeadlightsOn.ToString(), EnumTools.EnumToString(CarHeadlightBulbsState, m_HeadlightsState)));
    }
    else
    {
      TailLightsShineOff();
      DashboardShineOff();
      LeftFrontLightShineOff();
      RightFrontLightShineOff();
    }
    // brakes & reverse
    switch (gear)
    {
    case CarGear.REVERSE:
    case CarAutomaticGearboxMode.R:
      if (m_BrakesArePressed)
        m_RearLightType = CarRearLightType.BRAKES_AND_REVERSE;
      else
        m_RearLightType = CarRearLightType.REVERSE_ONLY;
      break;
    default:
      if (m_BrakesArePressed)
        m_RearLightType = CarRearLightType.BRAKES_ONLY;
      else
        m_RearLightType = CarRearLightType.NONE;
    }
    //Debug.Log(string.Format("m_BrakesArePressed=%1, m_RearLightType=%2", m_BrakesArePressed.ToString(), EnumTools.EnumToString(CarRearLightType, m_RearLightType)));
    // rear lights
    if (m_RearLightType != CarRearLightType.NONE && m_HeadlightsState != CarHeadlightBulbsState.NONE)
    {
      switch (m_RearLightType)
      {
      case CarRearLightType.BRAKES_ONLY:
        ReverseLightsShineOff();
        BrakeLightsShineOn();
        break;
      case CarRearLightType.REVERSE_ONLY:
        if (EngineIsOn())
        {
          ReverseLightsShineOn();
          BrakeLightsShineOff();
        }
        else
        {
          ReverseLightsShineOff();
          BrakeLightsShineOff();
        }
        break;
      case CarRearLightType.BRAKES_AND_REVERSE:
        if (EngineIsOn())
        {
          BrakeLightsShineOn();
          ReverseLightsShineOn();
        }
        else
        {
          ReverseLightsShineOff();
          BrakeLightsShineOn();
        }
        break;
      default:
        ReverseLightsShineOff();
        BrakeLightsShineOff();
      }
    }
    else
    {
      ReverseLightsShineOff();
      BrakeLightsShineOff();
    }
  }
References BrakeLightsShineOff(), BrakeLightsShineOn(), DashboardShineOff(), DashboardShineOn(), LeftFrontLightShineOff(), LeftFrontLightShineOn(), m_BrakesArePressed, m_HeadlightsOn, m_HeadlightsState, m_RearLightType, ReverseLightsShineOff(), ReverseLightsShineOn(), RightFrontLightShineOff(), RightFrontLightShineOn(), TailLightsShineOff(), and TailLightsShineOn().
Referenced by UpdateLights().
~CarScript()
void ~CarScript () protected
Definition at line 507 of file CarScript.c.
  {
#ifndef SERVER
    CleanupEffects();
#endif
  }
References CleanupEffects().
Variable Documentation
BATTERY_UPDATE_DELAY
const float BATTERY_UPDATE_DELAY = 100 private
Definition at line 179 of file CarScript.c.
Referenced by OnUpdate().
BRAKES_ONLY
enum CarDoorState BRAKES_ONLY
DROWN_ENGINE_DAMAGE
float DROWN_ENGINE_DAMAGE = 350.0 static protected
Definition at line 147 of file CarScript.c.
Referenced by OnUpdate().
DROWN_ENGINE_THRESHOLD
float DROWN_ENGINE_THRESHOLD = 0.5 static protected
Definition at line 146 of file CarScript.c.
Referenced by OnUpdate().
LEFT
enum CarDoorState LEFT
LONG
enum CarDoorState LONG
m_ActionsInitialize
bool m_ActionsInitialize
Definition at line 139 of file CarScript.c.
m_backPos
vector m_backPos protected
Definition at line 200 of file CarScript.c.
Referenced by CarScript(), and GetBackPointPosWS().
m_BatteryConsume
float m_BatteryConsume = 15 protected
Definition at line 175 of file CarScript.c.
Referenced by GetBatteryConsumption().
m_BatteryContinuousConsume
float m_BatteryContinuousConsume = 0.25 protected
Definition at line 176 of file CarScript.c.
Referenced by GetBatteryRuntimeConsumption().
m_BatteryEnergyStartMin
float m_BatteryEnergyStartMin = 5.0 protected
Definition at line 180 of file CarScript.c.
Referenced by OnBeforeEngineStart().
m_BatteryHealth
float m_BatteryHealth protected
Definition at line 170 of file CarScript.c.
Referenced by CarScript(), EEItemAttached(), and EEItemDetached().
m_BatteryRecharge
float m_BatteryRecharge = 0.15 protected
Definition at line 177 of file CarScript.c.
Referenced by GetBatteryRechargeRate().
m_BatteryTimer
float m_BatteryTimer = 0 private
Definition at line 178 of file CarScript.c.
Referenced by OnUpdate().
m_BrakeAmmount
float m_BrakeAmmount protected
Definition at line 155 of file CarScript.c.
Referenced by OnFluidChanged().
m_BrakesArePressed
bool m_BrakesArePressed protected
Definition at line 236 of file CarScript.c.
Referenced by OnUpdate(), UpdateLightsClient(), and UpdateLightsServer().
m_CarDoorCloseSound
string m_CarDoorCloseSound = "" protected
Definition at line 214 of file CarScript.c.
Referenced by CarScript::CivilianSedan(), HandleDoorsSound(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_CarDoorOpenSound
string m_CarDoorOpenSound = "" protected
Definition at line 213 of file CarScript.c.
Referenced by CarScript::CivilianSedan(), HandleDoorsSound(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_CarHornLongSoundName
string m_CarHornLongSoundName = "" protected
Definition at line 219 of file CarScript.c.
Referenced by CarScript::CivilianSedan(), HandleCarHornSound(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_CarHornShortSoundName
string m_CarHornShortSoundName = "" protected
Definition at line 218 of file CarScript.c.
Referenced by CarScript::CivilianSedan(), HandleCarHornSound(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_CarHornSoundEffect
ref EffectSound m_CarHornSoundEffect protected
Definition at line 227 of file CarScript.c.
Referenced by CleanupEffects(), and HandleCarHornSound().
m_CarHornState
int m_CarHornState protected
Definition at line 243 of file CarScript.c.
Referenced by CarScript(), OnVariablesSynchronized(), and SetCarHornState().
m_CarSeatShiftInSound
string m_CarSeatShiftInSound = "" protected
Definition at line 215 of file CarScript.c.
Referenced by HandleSeatAdjustmentSound(), and CarScript::OffroadHatchback().
m_CarSeatShiftOutSound
string m_CarSeatShiftOutSound = "" protected
Definition at line 216 of file CarScript.c.
Referenced by HandleSeatAdjustmentSound(), and CarScript::OffroadHatchback().
m_CarTypeActionsMap
enum CarDoorState m_CarTypeActionsMap = new map<typename, ref TInputActionMap>
Referenced by InitializeActions().
m_ContactCache
ref CarContactCache m_ContactCache protected
Definition at line 142 of file CarScript.c.
Referenced by CarScript(), CheckContactCache(), and OnContact().
m_CoolantAmmount
float m_CoolantAmmount protected
Definition at line 153 of file CarScript.c.
Referenced by OnFluidChanged().
m_coolantFx
ref EffVehicleSmoke m_coolantFx protected
Particles.
Definition at line 183 of file CarScript.c.
Referenced by CleanupEffects(), and EOnPostSimulate().
m_coolantPtcFx
int m_coolantPtcFx protected
Definition at line 188 of file CarScript.c.
Referenced by CarScript(), and EOnPostSimulate().
m_coolantPtcPos
vector m_coolantPtcPos protected
Definition at line 194 of file CarScript.c.
Referenced by CarScript(), EOnPostSimulate(), and GetCoolantPtcPosWS().
m_CrashSoundHeavy
ref EffectSound m_CrashSoundHeavy protected
Definition at line 222 of file CarScript.c.
Referenced by CleanupEffects(), and PlayCrashHeavySound().
m_CrashSoundLight
ref EffectSound m_CrashSoundLight protected
Definition at line 221 of file CarScript.c.
Referenced by CleanupEffects(), and PlayCrashLightSound().
m_DeadCrewMemberIndices
ref set<int> m_DeadCrewMemberIndices protected
Definition at line 274 of file CarScript.c.
Referenced by CarScript(), HandleByCrewMemberState(), and MarkCrewMemberDead().
m_dmgContactCoef
float m_dmgContactCoef = 0.058 protected
Definition at line 159 of file CarScript.c.
Referenced by CheckContactCache(), and CarScript::Sedan_02().
m_DrownEnginePoint
string m_DrownEnginePoint = "drown_engine" static protected
Definition at line 254 of file CarScript.c.
m_DrownEnginePos
vector m_DrownEnginePos static protected
Definition at line 164 of file CarScript.c.
Referenced by CarScript(), and GetEnginePosWS().
m_DrownTime
float m_DrownTime protected
Definition at line 163 of file CarScript.c.
Referenced by OnUpdate().
m_EngineBeforeStart
bool m_EngineBeforeStart protected
Definition at line 268 of file CarScript.c.
Referenced by OnBeforeEngineStart(), OnEngineStart(), and OnEngineStop().
m_EngineDestroyed
bool m_EngineDestroyed protected
Definition at line 241 of file CarScript.c.
Referenced by EEKilled().
m_engineFx
ref EffVehicleSmoke m_engineFx protected
Definition at line 184 of file CarScript.c.
Referenced by CleanupEffects(), and CreateCarDestroyedEffect().
m_EngineHealth
float m_EngineHealth protected
Definition at line 167 of file CarScript.c.
Referenced by CarPartsHealthCheck(), CarScript(), EOnPostSimulate(), and LeakFluid().
m_enginePos
vector m_enginePos protected
Definition at line 198 of file CarScript.c.
Referenced by CarScript(), and GetEnginePointPosWS().
m_enginePtcFx
int m_enginePtcFx protected
Definition at line 187 of file CarScript.c.
Referenced by CarScript(), and CreateCarDestroyedEffect().
m_enginePtcPos
vector m_enginePtcPos protected
Definition at line 193 of file CarScript.c.
Referenced by CarScript(), CreateCarDestroyedEffect(), CarScript::Truck_01_Base(), and CarScript::Truck_02().
m_EngineStartBattery
string m_EngineStartBattery = "" protected
Definition at line 208 of file CarScript.c.
Referenced by CarScript::CivilianSedan(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_EngineStartDoOnce
bool m_EngineStartDoOnce protected
Definition at line 269 of file CarScript.c.
Referenced by OnBeforeEngineStart().
m_EngineStarted
bool m_EngineStarted protected
Definition at line 240 of file CarScript.c.
Referenced by OnSound(), and SetEngineStarted().
m_EngineStartFuel
string m_EngineStartFuel = "" protected
Definition at line 210 of file CarScript.c.
Referenced by CarScript::CivilianSedan(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_EngineStartOK
string m_EngineStartOK = "" protected
Sounds.
Definition at line 207 of file CarScript.c.
Referenced by CarScript::CivilianSedan(), HandleEngineSound(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_EngineStartPlug
string m_EngineStartPlug = "" protected
Definition at line 209 of file CarScript.c.
Referenced by CarScript::CivilianSedan(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_EngineStopFuel
string m_EngineStopFuel = "" protected
Definition at line 211 of file CarScript.c.
Referenced by CarScript::CivilianSedan(), HandleEngineSound(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_EngineZoneReceivedHit
bool m_EngineZoneReceivedHit protected
Definition at line 271 of file CarScript.c.
Referenced by HasEngineZoneReceivedHit(), and SetEngineZoneReceivedHit().
m_EnviroHeatComfortOverride
float m_EnviroHeatComfortOverride protected
Definition at line 160 of file CarScript.c.
Referenced by CarScript().
m_exhaustFx
ref EffVehicleSmoke m_exhaustFx protected
Definition at line 185 of file CarScript.c.
Referenced by CleanupEffects(), and EOnPostSimulate().
m_exhaustPtcDir
vector m_exhaustPtcDir protected
Definition at line 192 of file CarScript.c.
Referenced by CarScript(), and EOnPostSimulate().
m_exhaustPtcFx
int m_exhaustPtcFx protected
Definition at line 189 of file CarScript.c.
Referenced by CarScript(), and EOnPostSimulate().
m_exhaustPtcPos
vector m_exhaustPtcPos protected
Definition at line 191 of file CarScript.c.
Referenced by CarScript(), and EOnPostSimulate().
m_ForceUpdateLights
bool m_ForceUpdateLights protected
Definition at line 239 of file CarScript.c.
Referenced by ForceUpdateLightsEnd(), ForceUpdateLightsStart(), and OnUpdate().
m_frontPos
vector m_frontPos protected
Definition at line 199 of file CarScript.c.
Referenced by CarScript(), and GetFrontPointPosWS().
m_FuelAmmount
float m_FuelAmmount protected
keeps ammount of each fluid
Definition at line 152 of file CarScript.c.
Referenced by OnFluidChanged().
m_fuelPos
vector m_fuelPos protected
Definition at line 196 of file CarScript.c.
Referenced by CarScript(), and GetRefillPointPosWS().
m_FuelTankHealth
float m_FuelTankHealth protected
Definition at line 169 of file CarScript.c.
Referenced by CarPartsHealthCheck(), CarScript(), EOnPostSimulate(), and LeakFluid().
m_Headlight
CarLightBase m_Headlight protected
Definition at line 245 of file CarScript.c.
Referenced by CleanupEffects(), and UpdateLightsClient().
m_HeadlightsOn
bool m_HeadlightsOn protected
Definition at line 234 of file CarScript.c.
Referenced by IsScriptedLightsOn(), ToggleHeadlights(), UpdateLightsClient(), and UpdateLightsServer().
m_HeadlightsState
bool m_HeadlightsState protected
Definition at line 235 of file CarScript.c.
Referenced by TailLightsShineOn(), UpdateHeadlightState(), UpdateLightsClient(), and UpdateLightsServer().
m_InputActionMap
TInputActionMap m_InputActionMap
Definition at line 138 of file CarScript.c.
m_LeftHeadlightPoint
string m_LeftHeadlightPoint = "light_left" static protected
Definition at line 250 of file CarScript.c.
Referenced by UpdateLightsClient().
m_LeftHeadlightTargetPoint
string m_LeftHeadlightTargetPoint = "light_left_dir" static protected
Definition at line 252 of file CarScript.c.
Referenced by UpdateLightsClient().
m_MomentumPrevTick
float m_MomentumPrevTick protected
Definition at line 140 of file CarScript.c.
Referenced by CheckContactCache(), EOnPostSimulate(), and OnContact().
m_NoisePar
ref NoiseParams m_NoisePar protected
Definition at line 228 of file CarScript.c.
m_NoiseSystem
NoiseSystem m_NoiseSystem protected
Definition at line 229 of file CarScript.c.
Referenced by EEInit(), and GenerateCarHornAINoise().
m_OilAmmount
float m_OilAmmount protected
Definition at line 154 of file CarScript.c.
Referenced by OnFluidChanged().
m_PlayCrashSoundHeavy
bool m_PlayCrashSoundHeavy protected
Definition at line 232 of file CarScript.c.
Referenced by CarScript(), GetCrashHeavySound(), PlayCrashHeavySound(), and SynchCrashHeavySound().
m_PlayCrashSoundLight
bool m_PlayCrashSoundLight protected
Definition at line 231 of file CarScript.c.
Referenced by CarScript(), GetCrashLightSound(), PlayCrashLightSound(), and SynchCrashLightSound().
m_PlugHealth
float m_PlugHealth protected
Definition at line 171 of file CarScript.c.
Referenced by CarScript(), EEItemAttached(), and EEItemDetached().
m_PreStartSound
ref EffectSound m_PreStartSound private
Definition at line 225 of file CarScript.c.
Referenced by HandleEngineSound().
m_Radiator
EntityAI m_Radiator protected
Definition at line 173 of file CarScript.c.
Referenced by EEItemAttached(), EEItemDetached(), GetRadiator(), and HasRadiator().
m_RadiatorHealth
float m_RadiatorHealth protected
Definition at line 168 of file CarScript.c.
Referenced by CarPartsHealthCheck(), CarScript(), EEItemAttached(), EOnPostSimulate(), and LeakFluid().
m_RearLight
CarRearLightBase m_RearLight protected
Definition at line 246 of file CarScript.c.
Referenced by BrakeAndReverseRearLight(), BrakesRearLight(), CleanupEffects(), NoRearLight(), ReverseRearLight(), and UpdateLightsClient().
m_RearLightType
bool m_RearLightType protected
Definition at line 237 of file CarScript.c.
Referenced by UpdateLightsClient(), and UpdateLightsServer().
m_ReverseLightPoint
string m_ReverseLightPoint = "light_reverse" static protected
Definition at line 249 of file CarScript.c.
Referenced by UpdateLightsClient().
m_RightHeadlightPoint
string m_RightHeadlightPoint = "light_right" static protected
Definition at line 251 of file CarScript.c.
Referenced by UpdateLightsClient().
m_RightHeadlightTargetPoint
string m_RightHeadlightTargetPoint = "light_right_dir" static protected
Definition at line 253 of file CarScript.c.
Referenced by UpdateLightsClient().
m_side_1_1Pos
vector m_side_1_1Pos protected
Definition at line 201 of file CarScript.c.
Referenced by CarScript(), and Get_1_1PointPosWS().
m_side_1_2Pos
vector m_side_1_2Pos protected
Definition at line 202 of file CarScript.c.
Referenced by CarScript(), and Get_1_2PointPosWS().
m_side_2_1Pos
vector m_side_2_1Pos protected
Definition at line 203 of file CarScript.c.
Referenced by CarScript(), and Get_2_1PointPosWS().
m_side_2_2Pos
vector m_side_2_2Pos protected
Definition at line 204 of file CarScript.c.
Referenced by CarScript(), and Get_2_2PointPosWS().
m_Time
float m_Time protected
Definition at line 144 of file CarScript.c.
Referenced by CarScript(), EOnPostSimulate(), SymptomBase::OnUpdateClient(), UIScriptedMenu::Play(), and UIScriptedMenu::Update().
m_UnconsciousCrewMemberIndices
ref set<int> m_UnconsciousCrewMemberIndices protected
Definition at line 273 of file CarScript.c.
Referenced by CarScript(), HandleByCrewMemberState(), and MarkCrewMemberUnconscious().
m_VelocityPrevTick
vector m_VelocityPrevTick protected
Definition at line 141 of file CarScript.c.
Referenced by CheckContactCache(), EOnPostSimulate(), and OnContact().
m_WindowLarge
ref EffectSound m_WindowLarge protected
Definition at line 224 of file CarScript.c.
Referenced by CleanupEffects(), and EEHealthLevelChanged().
m_WindowSmall
ref EffectSound m_WindowSmall protected
Definition at line 223 of file CarScript.c.
Referenced by CleanupEffects(), and EEHealthLevelChanged().
MEMORY_POINT_NAME_CAR_HORN
const string MEMORY_POINT_NAME_CAR_HORN = "pos_carHorn" static protected
Definition at line 149 of file CarScript.c.
NONE
enum CarDoorState NONE
OFF
enum CarDoorState OFF = 0
REVERSE_ONLY
enum CarDoorState REVERSE_ONLY
RIGHT
enum CarDoorState RIGHT
SELECTION_ID_BRAKE_LIGHT_L
const int SELECTION_ID_BRAKE_LIGHT_L = 2 static protected
Definition at line 260 of file CarScript.c.
Referenced by BrakeLightsShineOff(), and BrakeLightsShineOn().
SELECTION_ID_BRAKE_LIGHT_R
const int SELECTION_ID_BRAKE_LIGHT_R = 3 static protected
Definition at line 261 of file CarScript.c.
Referenced by BrakeLightsShineOff(), and BrakeLightsShineOn().
SELECTION_ID_DASHBOARD_LIGHT
const int SELECTION_ID_DASHBOARD_LIGHT = 8 static protected
Definition at line 266 of file CarScript.c.
Referenced by DashboardShineOff(), and DashboardShineOn().
SELECTION_ID_FRONT_LIGHT_L
const int SELECTION_ID_FRONT_LIGHT_L = 0 static protected
Definition at line 258 of file CarScript.c.
Referenced by LeftFrontLightShineOff(), and LeftFrontLightShineOn().
SELECTION_ID_FRONT_LIGHT_R
const int SELECTION_ID_FRONT_LIGHT_R = 1 static protected
Definition at line 259 of file CarScript.c.
Referenced by RightFrontLightShineOff(), and RightFrontLightShineOn().
SELECTION_ID_REVERSE_LIGHT_L
const int SELECTION_ID_REVERSE_LIGHT_L = 4 static protected
Definition at line 262 of file CarScript.c.
Referenced by ReverseLightsShineOff(), and ReverseLightsShineOn().
SELECTION_ID_REVERSE_LIGHT_R
const int SELECTION_ID_REVERSE_LIGHT_R = 5 static protected
Definition at line 263 of file CarScript.c.
Referenced by ReverseLightsShineOff(), and ReverseLightsShineOn().
SELECTION_ID_TAIL_LIGHT_L
const int SELECTION_ID_TAIL_LIGHT_L = 6 static protected
Definition at line 264 of file CarScript.c.
Referenced by TailLightsShineOff(), and TailLightsShineOn().
SELECTION_ID_TAIL_LIGHT_R
const int SELECTION_ID_TAIL_LIGHT_R = 7 static protected
Definition at line 265 of file CarScript.c.
Referenced by TailLightsShineOff(), and TailLightsShineOn().
SHORT
enum CarDoorState SHORT = 1
START_NO_BATTERY
enum CarDoorState START_NO_BATTERY
START_NO_FUEL
enum CarDoorState START_NO_FUEL
START_NO_SPARKPLUG
enum CarDoorState START_NO_SPARKPLUG
START_OK
enum CarDoorState START_OK
STARTING
enum CarDoorState STARTING
STOP_OK
enum CarDoorState STOP_OK
typename
enum CarDoorState typename
Base script class for all motorized wheeled vehicles.