DayZ: ActionInteractLoopBaseCB Class Reference
ActionInteractLoopBaseCB Class Reference
Private Member Functions
bool CancelCondition ()
override void OnAnimationEvent (int pEventID)
override void CreateActionComponent ()
override void InitActionComponent ()
Detailed Description
Definition at line 1 of file ActionInteractLoopBase.c.
Member Function Documentation
CancelCondition()
bool ActionInteractLoopBaseCB::CancelCondition () inline private
Definition at line 4 of file ActionInteractLoopBase.c.
  {
    if (!m_ActionData)
      return DefaultCancelCondition();
    //SetCommand(DayZPlayerConstants.CMD_ACTIONINT_ACTIONLOOP);
    //Print("cancel condition enabled: " + GetState().ToString() );
    if (!m_Interrupted && (GetState() == STATE_LOOP_LOOP || GetState() == STATE_LOOP_LOOP2))
    {
      AnimatedActionBase action = AnimatedActionBase.Cast(m_ActionData.m_Action);
      action.Do(m_ActionData, m_ActionData.m_State);
    }
    return DefaultCancelCondition();
  }
References DefaultCancelCondition(), GetState(), ActionData::m_Action, ActionBaseCB::m_ActionData, ActionBaseCB::m_Interrupted, ActionData::m_State, STATE_LOOP_LOOP, and STATE_LOOP_LOOP2.
CreateActionComponent()
override void ActionInteractLoopBaseCB::CreateActionComponent () inline private
Definition at line 22 of file ActionInteractLoopBase.c.
  {
    m_ActionData.m_ActionComponent = new CAInteract;
  }
References ActionData::m_ActionComponent, and ActionBaseCB::m_ActionData.
InitActionComponent()
override void ActionInteractLoopBaseCB::InitActionComponent () inline private
Definition at line 27 of file ActionInteractLoopBase.c.
  {
    super.InitActionComponent();
    EnableCancelCondition(true);
  }
References EnableCancelCondition().
OnAnimationEvent()
override void ActionInteractLoopBaseCB::OnAnimationEvent (int pEventID) inline private
Definition at line 18 of file ActionInteractLoopBase.c.
  {
  }
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/ActionInteractLoopBase.c