DayZ: ActionUnmountBarbedWire Class Reference
ActionUnmountBarbedWire Class Reference
Private Member Functions
void ActionUnmountBarbedWire ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override string GetAdminLogMessage (ActionData action_data)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Private Attributes
float m_DamageAmount
string m_SlotName
Detailed Description
Definition at line 9 of file ActionUnMountBarbedWire.c.
Constructor & Destructor Documentation
ActionUnmountBarbedWire()
void ActionUnmountBarbedWire::ActionUnmountBarbedWire () inline private
Definition at line 14 of file ActionUnMountBarbedWire.c.
  {
    m_CallbackClass = ActionUnmountBarbedWireCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
    m_DamageAmount = 2;
    m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_HIGH;
    m_Text = "#unmount_barbed_wire";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_DamageAmount, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
Member Function Documentation
ActionCondition()
override bool ActionUnmountBarbedWire::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 32 of file ActionUnMountBarbedWire.c.
  {
    Object targetObject = target.GetObject();
    if (targetObject && targetObject.CanUseConstruction())
    {
      BaseBuildingBase base_building = BaseBuildingBase.Cast(targetObject);
      if (!base_building.IsPlayerInside(player, ""))
        return false;
      string selection = targetObject.GetActionComponentName(target.GetComponentIndex());
      if (selection.Length() > 0)
      {
        int delimiter_index = selection.IndexOfFrom(0, "_mounted");
        if (delimiter_index > -1)
        {
          selection = selection.Substring(0, delimiter_index);
          BarbedWire barbed_wire = BarbedWire.Cast(base_building.FindAttachmentBySlotName(selection));
          if (barbed_wire && barbed_wire.IsMounted())
          {
            m_SlotName = selection;
            return true;
          }
        }
      }
    }
    return false;
  }
References string::IndexOfFrom(), string::Length(), m_SlotName, and string::Substring().
CreateConditionComponents()
override void ActionUnmountBarbedWire::CreateConditionComponents () inline private
Definition at line 26 of file ActionUnMountBarbedWire.c.
  {
    m_ConditionItem = new CCINonRuined;
    m_ConditionTarget = new CCTNonRuined(UAMaxDistances.BASEBUILDING);
  }
References UAMaxDistances::BASEBUILDING, m_ConditionItem, and m_ConditionTarget.
GetAdminLogMessage()
override string ActionUnmountBarbedWire::GetAdminLogMessage (ActionData action_data) inline private
Definition at line 76 of file ActionUnMountBarbedWire.c.
  {
    string message = string.Format("Player %1 Unmounted BarbedWire from %2", action_data.m_Player, action_data.m_Target.GetObject().ClassName());
    return message;
  }
OnFinishProgressServer()
override void ActionUnmountBarbedWire::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 65 of file ActionUnMountBarbedWire.c.
  {
    BaseBuildingBase base_building = BaseBuildingBase.Cast(action_data.m_Target.GetObject());
    BarbedWire barbed_wire = BarbedWire.Cast(base_building.FindAttachmentBySlotName(m_SlotName));
    //unmount and refresh parent
    barbed_wire.SetMountedState(false);
    action_data.m_Player.GetSoftSkillsManager().AddSpecialty(m_SpecialtyWeight);
  }
References m_SlotName, and m_SpecialtyWeight.
Member Data Documentation
m_DamageAmount
float ActionUnmountBarbedWire::m_DamageAmount private
Definition at line 11 of file ActionUnMountBarbedWire.c.
Referenced by ActionUnmountBarbedWire().
m_SlotName
string ActionUnmountBarbedWire::m_SlotName private
Definition at line 12 of file ActionUnMountBarbedWire.c.
Referenced by ActionCondition(), and OnFinishProgressServer().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionUnMountBarbedWire.c