DayZ: ThirstMdfr Class Reference
ThirstMdfr Class Reference
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override void OnReconnect (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
float m_LastWaterLevel
ref HumanMovementState m_MovementState = new HumanMovementState()
Detailed Description
Definition at line 1 of file Thirst.c.
Member Function Documentation
ActivateCondition()
override bool ThirstMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 15 of file Thirst.c.
  {
    return true;
  }
DeactivateCondition()
override bool ThirstMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 25 of file Thirst.c.
  {
    return false;
  }
Init()
override void ThirstMdfr::Init () inline private
Definition at line 6 of file Thirst.c.
  {
    m_TrackActivatedTime = false;
    m_ID = eModifiers.MDF_THIRST;
    m_TickIntervalInactive = DEFAULT_TICK_TIME_INACTIVE;
    m_TickIntervalActive = 1;
    DisableDeactivateCheck();
  }
References DEFAULT_TICK_TIME_INACTIVE, DisableDeactivateCheck(), m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnReconnect()
override void ThirstMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 20 of file Thirst.c.
  {
  }
OnTick()
override void ThirstMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 30 of file Thirst.c.
  {
    player.GetMovementState(m_MovementState);
    float water = player.GetStatWater().Get();
    float metabolic_speed = MiscGameplayFunctions.GetWaterMetabolicSpeed(m_MovementState.m_iMovement);
    float modifier = water / PlayerConstants.SL_WATER_MAX + PlayerConstants.CONSUMPTION_MULTIPLIER_BASE;
    metabolic_speed *= modifier; //non linear shaping for consumption curve (comment out to have it linear)
    player.GetStatWater().Add((-metabolic_speed * deltaT));
    if (water <= PlayerConstants.LOW_WATER_THRESHOLD)
    {
      player.SetMixedSoundState(eMixedSoundStates.THIRSTY);
      if ((player.GetStomach().GetDigestingType() & PlayerStomach.DIGESTING_WATER) == 0)
        player.AddHealth("GlobalHealth", "Health", -PlayerConstants.LOW_WATER_DAMAGE_PER_SEC * deltaT);
    }
    else
      player.UnsetMixedSoundState(eMixedSoundStates.THIRSTY);
  }
References PlayerConstants::CONSUMPTION_MULTIPLIER_BASE, PlayerConstants::LOW_WATER_DAMAGE_PER_SEC, PlayerConstants::LOW_WATER_THRESHOLD, m_MovementState, PlayerStomach(), and PlayerConstants::SL_WATER_MAX.
Member Data Documentation
m_LastWaterLevel
float ThirstMdfr::m_LastWaterLevel private
Definition at line 3 of file Thirst.c.
m_MovementState
ref HumanMovementState ThirstMdfr::m_MovementState = new HumanMovementState() private
Definition at line 4 of file Thirst.c.
Referenced by OnTick().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/PlayerModifiers/Modifiers/Thirst.c