DayZ: scripts/4_World/Entities/Building/Specific/AnniversaryMusicSource.c File Reference
AnniversaryMusicSource.c File Reference
Enumerations
enum EAnniversaryMusicStates { INVALID , LIGHT , INTENSE }
Functions
void AnniversaryMusicSource ()
override void EEDelete (EntityAI parent)
override void OnVariablesSynchronized ()
void UpdateMusic ()
void SetIntenseServer ()
void SetLightServer ()
void SetInvalidServer ()
void PlayIntense ()
void PlayLight ()
void StopAllMusic ()
Variables
enum EAnniversaryMusicStates SOUND_INTENSE = "AnniversaryMusic_Intense_SoundSet"
const string SOUND_LIGHT = "AnniversaryMusic_Light_SoundSet"
EffectSound m_LightAmbientSound
EffectSound m_IntenseAmbientSound
int m_MusicState
int m_MusicStateLocal
Enumeration Type Documentation
EAnniversaryMusicStates
enum EAnniversaryMusicStates
Enumerator
INVALID
LIGHT
INTENSE
Definition at line 1 of file AnniversaryMusicSource.c.
{
  INVALID,
  LIGHT,
  INTENSE
}
Function Documentation
AnniversaryMusicSource()
void AnniversaryMusicSource () protected
Definition at line 21 of file AnniversaryMusicSource.c.
  {
    m_MusicState = EAnniversaryMusicStates.INVALID;
    m_MusicStateLocal = EAnniversaryMusicStates.INVALID;
    RegisterNetSyncVariableInt("m_MusicState", 0, EnumTools.GetEnumSize(EAnniversaryMusicStates));
  }
References EnumTools::GetEnumSize(), m_MusicState, and m_MusicStateLocal.
EEDelete()
override void EEDelete (EntityAI parent) protected
Definition at line 29 of file AnniversaryMusicSource.c.
  {
    super.EEDelete(parent);
#ifndef SERVER
    if (m_LightAmbientSound)
      SEffectManager.DestroyEffect(m_LightAmbientSound);
    if (m_IntenseAmbientSound)
      SEffectManager.DestroyEffect(m_IntenseAmbientSound);
#endif
  }
References SEffectManager::DestroyEffect(), m_IntenseAmbientSound, and m_LightAmbientSound.
OnVariablesSynchronized()
override void OnVariablesSynchronized () protected
Definition at line 42 of file AnniversaryMusicSource.c.
  {
    super.OnVariablesSynchronized();
    if (m_MusicState != m_MusicStateLocal)
    {
      m_MusicStateLocal = m_MusicState;
#ifndef SERVER
      UpdateMusic();
#endif
    }
  }
References m_MusicState, m_MusicStateLocal, and UpdateMusic().
PlayIntense()
void PlayIntense () protected
Definition at line 102 of file AnniversaryMusicSource.c.
  {
#ifndef SERVER
    m_LightAmbientSound.SoundStop();
    m_IntenseAmbientSound.SoundPlay();
#endif
  }
References m_IntenseAmbientSound, m_LightAmbientSound, EffectSound::SoundPlay(), and EffectSound::SoundStop().
Referenced by UpdateMusic().
PlayLight()
void PlayLight () protected
Definition at line 110 of file AnniversaryMusicSource.c.
  {
#ifndef SERVER
    m_IntenseAmbientSound.SoundStop();
    m_LightAmbientSound.SoundPlay();
#endif
  }
References m_IntenseAmbientSound, m_LightAmbientSound, EffectSound::SoundPlay(), and EffectSound::SoundStop().
Referenced by UpdateMusic().
SetIntenseServer()
void SetIntenseServer () protected
Definition at line 82 of file AnniversaryMusicSource.c.
  {
    m_MusicState = EAnniversaryMusicStates.INTENSE;
    SetSynchDirty();
  }
References m_MusicState.
SetInvalidServer()
void SetInvalidServer () protected
Definition at line 96 of file AnniversaryMusicSource.c.
  {
    m_MusicState = EAnniversaryMusicStates.INVALID;
    SetSynchDirty();
  }
References m_MusicState.
SetLightServer()
void SetLightServer () protected
Definition at line 89 of file AnniversaryMusicSource.c.
  {
    m_MusicState = EAnniversaryMusicStates.LIGHT;
    SetSynchDirty();
  }
References m_MusicState.
StopAllMusic()
void StopAllMusic () protected
Definition at line 118 of file AnniversaryMusicSource.c.
  {
#ifndef SERVER
    m_IntenseAmbientSound.SoundStop();
    m_LightAmbientSound.SoundStop();
#endif
  }
References m_IntenseAmbientSound, m_LightAmbientSound, and EffectSound::SoundStop().
Referenced by UpdateMusic().
UpdateMusic()
void UpdateMusic () protected
Definition at line 55 of file AnniversaryMusicSource.c.
  {
#ifndef SERVER
    if (!m_IntenseAmbientSound)
      m_IntenseAmbientSound = SEffectManager.CreateSound(SOUND_INTENSE, GetPosition(), 0.5, 0.5, false);
    if (!m_LightAmbientSound)
      m_LightAmbientSound = SEffectManager.CreateSound(SOUND_LIGHT, GetPosition(), 0.5, 0.5, true);
#endif
    switch (m_MusicState)
    {
    case EAnniversaryMusicStates.LIGHT:
      PlayLight();
      break;
    case EAnniversaryMusicStates.INTENSE:
      PlayIntense();
      break;
    default:
      StopAllMusic();
      break;
    }
  }
References SEffectManager::CreateSound(), GetPosition, m_IntenseAmbientSound, m_LightAmbientSound, m_MusicState, PlayIntense(), PlayLight(), SOUND_INTENSE, SOUND_LIGHT, and StopAllMusic().
Referenced by OnVariablesSynchronized(), and ScriptedWidgetEventHandler::OptionsMenuSounds().
Variable Documentation
m_IntenseAmbientSound
EffectSound m_IntenseAmbientSound protected
Definition at line 15 of file AnniversaryMusicSource.c.
Referenced by EEDelete(), PlayIntense(), PlayLight(), StopAllMusic(), and UpdateMusic().
m_LightAmbientSound
EffectSound m_LightAmbientSound protected
Definition at line 14 of file AnniversaryMusicSource.c.
Referenced by EEDelete(), PlayIntense(), PlayLight(), StopAllMusic(), and UpdateMusic().
m_MusicState
int m_MusicState protected
Definition at line 18 of file AnniversaryMusicSource.c.
Referenced by AnniversaryMusicSource(), OnVariablesSynchronized(), SetIntenseServer(), SetInvalidServer(), SetLightServer(), and UpdateMusic().
m_MusicStateLocal
int m_MusicStateLocal protected
Definition at line 19 of file AnniversaryMusicSource.c.
Referenced by AnniversaryMusicSource(), and OnVariablesSynchronized().
SOUND_INTENSE
enum EAnniversaryMusicStates SOUND_INTENSE = "AnniversaryMusic_Intense_SoundSet"
Referenced by UpdateMusic().
SOUND_LIGHT
const string SOUND_LIGHT = "AnniversaryMusic_Light_SoundSet" private
Definition at line 11 of file AnniversaryMusicSource.c.
Referenced by UpdateMusic().