DayZ: Dispatcher Class Reference
Dispatcher Class Reference
Private Member Functions
Param CallMethod (CallID call_id, Param params)
void SendLogAtClient (Param1< string > p)
void ScriptConsoleAddPrint (Param1< string > p)
void ScriptConsoleHistoryBack ()
void ScriptConsoleHistoryForward ()
void SceneEditorCommand (Param params)
void MissionGameplayHideInventory ()
override Param CallMethod (CallID call_id, Param params)
Detailed Description
Definition at line 13 of file Dispatcher.c.
Member Function Documentation
CallMethod() [1/2]
Param Dispatcher::CallMethod (CallID call_id, Param params) inline private
Definition at line 15 of file Dispatcher.c.
{}
Referenced by Debug::SaveLog().
CallMethod() [2/2]
override Param Dispatcher::CallMethod (CallID call_id, Param params) inline private
Definition at line 65 of file DispatcherCaller.c.
  {
    switch (call_id)
    {
    case CALL_ID_SEND_LOG:
      SendLogAtClient(Param1<string>.Cast(params));
      break;
    case CALL_ID_SCR_CNSL_ADD_PRINT:
      ScriptConsoleAddPrint(Param1<string>.Cast(params));
      break;
    case CALL_ID_SCENE_EDITOR_COMMAND:
      SceneEditorCommand(params);
      break;
    case CALL_ID_HIDE_INVENTORY:
      MissionGameplayHideInventory();
      break;
    case CALL_ID_SCR_CNSL_GETSELECTEDITEM:
      return new Param1<string>(ScriptConsoleItemsTab.GetLastSelectedObject());
    case CALL_ID_SCR_CNSL_HISTORY_BACK:
      ScriptConsoleHistoryBack();
      break;
    case CALL_ID_SCR_CNSL_HISTORY_NEXT:
      ScriptConsoleHistoryForward();
      break;
    }
    return null;
  }
References CALL_ID_HIDE_INVENTORY, CALL_ID_SCENE_EDITOR_COMMAND, CALL_ID_SCR_CNSL_ADD_PRINT, CALL_ID_SCR_CNSL_GETSELECTEDITEM, CALL_ID_SCR_CNSL_HISTORY_BACK, CALL_ID_SCR_CNSL_HISTORY_NEXT, CALL_ID_SEND_LOG, and ScriptConsoleItemsTab::GetLastSelectedObject().
MissionGameplayHideInventory()
void Dispatcher::MissionGameplayHideInventory () inline private
Definition at line 58 of file DispatcherCaller.c.
  {
    MissionGameplay mission = MissionGameplay.Cast(GetGame().GetMission());
    if (mission)
      mission.HideInventory();
  }
References GetGame(), Mission::HideInventory(), and mission.
SceneEditorCommand()
void Dispatcher::SceneEditorCommand (Param params) inline private
Definition at line 48 of file DispatcherCaller.c.
  {
    UIScriptedMenu ui_menu = GetGame().GetUIManager().GetMenu();
    if (ui_menu && ui_menu.GetID() == MENU_SCENE_EDITOR)
    {
      SceneEditorMenu editor_menu = SceneEditorMenu.Cast(ui_menu);
      editor_menu.SceneEditorCommand(params);
    }
  }
References GetGame(), and MENU_SCENE_EDITOR.
ScriptConsoleAddPrint()
void Dispatcher::ScriptConsoleAddPrint (Param1< string > p) inline private
Definition at line 11 of file DispatcherCaller.c.
  {
    UIScriptedMenu ui_menu = GetGame().GetUIManager().GetMenu();
    if (ui_menu && ui_menu.GetID() == MENU_SCRIPTCONSOLE)
    {
      ScriptConsole scripted_console = ScriptConsole.Cast(ui_menu);
      ScriptConsoleEnfScriptTab tab = ScriptConsoleEnfScriptTab.Cast(scripted_console.GetTabHandler(ScriptConsoleEnfScriptTab));
      if (tab)
        tab.Add(p.param1);
    }
  }
References GetGame(), and MENU_SCRIPTCONSOLE.
ScriptConsoleHistoryBack()
void Dispatcher::ScriptConsoleHistoryBack () inline private
Definition at line 23 of file DispatcherCaller.c.
  {
    UIScriptedMenu ui_menu = GetGame().GetUIManager().GetMenu();
    if (ui_menu.GetID() == MENU_SCRIPTCONSOLE)
    {
      ScriptConsole scriptConsole = ScriptConsole.Cast(ui_menu);
      ScriptConsoleEnfScriptTab handler = ScriptConsoleEnfScriptTab.Cast(scriptConsole.GetSelectedHandler());
      if (handler)
        handler.HistoryBack();
    }
  }
References GetGame(), and MENU_SCRIPTCONSOLE.
ScriptConsoleHistoryForward()
void Dispatcher::ScriptConsoleHistoryForward () inline private
Definition at line 35 of file DispatcherCaller.c.
  {
    UIScriptedMenu ui_menu = GetGame().GetUIManager().GetMenu();
    if (ui_menu.GetID() == MENU_SCRIPTCONSOLE)
    {
      ScriptConsole scriptConsole = ScriptConsole.Cast(ui_menu);
      ScriptConsoleEnfScriptTab handler = ScriptConsoleEnfScriptTab.Cast(scriptConsole.GetSelectedHandler());
      if (handler)
        handler.HistoryForward();
    }
  }
References GetGame(), and MENU_SCRIPTCONSOLE.
SendLogAtClient()
void Dispatcher::SendLogAtClient (Param1< string > p) inline private
Definition at line 3 of file DispatcherCaller.c.
  {
    PluginDeveloper m = PluginDeveloper.Cast(GetPlugin(PluginDeveloper));
    if (m != NULL)
      m.SendServerLogToClient(p.param1);
  }
References GetPlugin().
The documentation for this class was generated from the following files:
scripts/3_Game/tools/Dispatcher.c
scripts/5_Mission/mission/DispatcherCaller.c