DayZ: InventorySlots Class Reference
InventorySlots Class Reference
provides access to slot configuration
C++ constants
@NOTE: engine pre-populates this class with first 32 slots from CfgSlots (uppercased)
Constants filled in from C++
const int COUNT
Amount of pre-populated slots (32)
const int INVALID
Invalid slot (-1)
void InventorySlots ()
void ~InventorySlots ()
static proto native int GetSlotIdFromString (string slot_name)
converts string to slot_id
static proto native owned string GetSlotName (int id)
converts slot_id to string
static proto native owned string GetSlotDisplayName (int id)
converts slot_id to string
static proto native bool IsSlotIdValid (int slotId)
verifies existence of the slot id
static proto native int GetStackMaxForSlotId (int slot_Id)
static proto native bool GetShowForSlotId (int slot_Id)
static proto native bool GetAutoAttachForSlotId (int slot_Id)
static proto bool GetBoneNameForSlotId (int slot_Id, out string bone_name)
static proto bool GetSelectionForSlotId (int slot_Id, out string selection)
Detailed Description
provides access to slot configuration
Examples
P:/extracted/scripts/3_Game/Systems/Inventory/InventorySlots.c.
Definition at line 5 of file InventorySlots.c.
Constructor & Destructor Documentation
InventorySlots()
void InventorySlots::InventorySlots () inline private
Examples
P:/extracted/scripts/3_Game/Systems/Inventory/InventorySlots.c.
Definition at line 24 of file InventorySlots.c.
{}
~InventorySlots()
void InventorySlots::~InventorySlots () inline private
Examples
P:/extracted/scripts/3_Game/Systems/Inventory/InventorySlots.c.
Definition at line 25 of file InventorySlots.c.
{}
Member Function Documentation
GetAutoAttachForSlotId()
InventorySlots::GetAutoAttachForSlotId (int slot_Id) static private
Parameters
[in] slot_id queried slot
Returns
auto attach attribute from corresponding entry (or default value == 1)
Examples
P:/extracted/scripts/3_Game/Systems/Inventory/InventorySlots.c.
GetBoneNameForSlotId()
InventorySlots::GetBoneNameForSlotId (int slot_Id, out string bone_name) static private
Parameters
[in] slot_id queried slot
[out] bone_name selection filled with attribute from corresponding entry
Returns
true if slot valid
Examples
P:/extracted/scripts/3_Game/Systems/Inventory/InventorySlots.c.
GetSelectionForSlotId()
InventorySlots::GetSelectionForSlotId (int slot_Id, out string selection) static private
Parameters
[in] slot_id queried slot
[out] selection selection filled with attribute from corresponding entry
Returns
true if slot valid
Examples
P:/extracted/scripts/3_Game/Systems/Inventory/InventorySlots.c.
Referenced by CanReceiveAttachment(), CanReleaseAttachment(), and BaseBuildingBase::CheckSlotVerticalDistance().
GetShowForSlotId()
InventorySlots::GetShowForSlotId (int slot_Id) static private
Parameters
[in] slot_id queried slot
Returns
show attribute from corresponding entry (or default value == true)
Examples
P:/extracted/scripts/3_Game/Systems/Inventory/InventorySlots.c.
Referenced by Entity::CanDisplayAttachmentSlot(), and Entity::CanDisplayAttachmentSlot().
GetSlotDisplayName()
InventorySlots::GetSlotDisplayName (int id) static private
converts slot_id to string
Parameters
[in] slot_id slot id to be find.
Returns
string or null string
Examples
P:/extracted/scripts/3_Game/Systems/Inventory/InventorySlots.c.
Referenced by Attachments::AttachmentAdded(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), ZombieContainer::InitGhostSlots(), and PlayerContainer::PlayerContainer().
GetSlotIdFromString()
InventorySlots::GetSlotIdFromString (string slot_name) static private
converts string to slot_id
Parameters
[in] slot_name slot name to be find.
Returns
slot id or InventorySlots.INVALID
Examples
P:/extracted/scripts/3_Game/Systems/Inventory/InventorySlots.c.
Referenced by ActionFillCoolant::ActionCondition(), ActionDetachFromTarget_SpecificSlot_MetalSheets(), BaseBuildingBase::AnimateFlagEx(), AttachItem(), Attachments::AttachmentAdded(), HandsContainer::AttachmentAdded(), ClosableContainer::AttachmentAddedEx(), Attachments::AttachmentRemoved(), HandsContainer::AttachmentRemoved(), ClosableContainer::AttachmentRemoved(), BaseBuildingBase::CanDisplayAttachmentSlot(), Entity::CanDisplayAttachmentSlot(), ImprovisedExplosive::CanReceiveAttachment(), MyBotTrigger::CheckTrigger(), AttachmentsOutOfReach::CreateAttachmentPosition(), Clothing::CreateHeadtorchLight(), Barrel_ColorBase::DetermineAction(), RecipeBase::Do(), Entity::EEItemAttached(), ItemBase::EEItemAttached(), Entity::EEItemDetached(), Entity::FindAttachmentBySlotName(), ActionAttachOnSelection::FindSlotIdToAttachOrCombine(), ActionDetachFromTarget::FindSlotIdToDetach(), ActionDetachFromTarget_SpecificSlotsCategory::FindSlotIdToDetach(), ConstructionActionData::GetAttachmentsFromSelection(), ConstructionActionData::GetAttachmentSlotFromSelection(), ManBase::GetItemOnSlot(), HasCookingStand(), ImprovisedExplosive::HasLockedTriggerSlots(), Plastic_Explosive::HasLockedTriggerSlots(), ItemBase::HasSparkplug(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), Switchable_Base::InitAttachmentsSlotsToCheck(), ZombieContainer::InitGhostSlots(), ItemBase::InitializeSlots(), AttachmentsOutOfReach::IsAttachmentReachable(), ItemBase::IsAttachmentSlotLocked(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), PlayerContainer::ItemDetached(), ZombieContainer::ItemDetached(), LoadPlayerAttachmentIndexes(), ImprovisedExplosive::LockExplosivesSlots(), LockOvenAttachments(), ImprovisedExplosive::LockTriggerSlots(), Plastic_Explosive::LockTriggerSlots(), MoveAttachmentDown(), MoveAttachmentUp(), OnAttachmentRuined(), BotStateBase::OnEntry(), OnEntry(), AnalyticsManagerClient::OnItemAttachedAtPlayer(), PlayerSoundEventBase::OnPlay(), ManBase::OnPlayerLoaded(), ImprovisedExplosive::OnStoreLoad(), Plastic_Explosive::OnStoreLoad(), OnUpdate(), Plastic_Explosive::OnVariablesSynchronized(), PlayerContainer::PlayerContainer(), ItemBase::RefreshAttachements(), ItemBase::SetCanCatch(), SetHandsMaterial(), SetOvenState(), PlayerContainer::SetPlayer(), SetPlayerLifespanLevel(), SetStoneCircleState(), UIPropertyAttachment::Show(), TranslateAndValidateSlot(), BaseBuildingBase::TranslateSlotFromSelection(), ImprovisedExplosive::UnlockExplosivesSlots(), ImprovisedExplosive::UnlockTriggerSlots(), Plastic_Explosive::UnlockTriggerSlots(), ManBase::UpdateCorpseStateVisual(), Attachments::UpdateInterval(), ItemBase::UpdateNVGStatus(), and ReplaceItemWithNewLambda::VerifyItemTypeBySlotType().
GetSlotName()
InventorySlots::GetSlotName (int id) static private
converts slot_id to string
Parameters
[in] slot_id slot id to be find.
Returns
string or null string
Examples
P:/extracted/scripts/3_Game/Systems/Inventory/InventorySlots.c.
Referenced by ActionLockAttachment::ActionCondition(), ActionCondition(), InventoryItemSuper::CanDetachAttachment(), ImprovisedExplosive::CanDisplayAttachmentSlot(), Plastic_Explosive::CanDisplayAttachmentSlot(), BaseBuildingBase::CanDisplayAttachmentSlot(), FireplaceBase::CanDisplayAttachmentSlot(), BaseBuildingBase::CanReceiveAttachment(), BleedingSourcesManagerBase::DisplayDebug(), Edible_Base::EEItemLocationChanged(), BaseBuildingBase::GateAttachmentConditions(), GameInventory::GetCurrentAttachmentSlotInfo(), GetPlayerAttachmentIndex(), AttachmentsOutOfReach::IsAttachmentReachable(), MoveAttachmentDown(), MoveAttachmentUp(), ActionFoldEntityToSlot::OnExecuteServer(), ItemBase::OnSetSlotLock(), InventoryItem::OnWasAttached(), AttachmentCategoriesRow::RefreshSlot(), ClosableContainer::SetEntity(), HandsContainer::ShowAtt(), PlayerSpawnHandler::SpawnDiscreteSlotItemSet(), ItemBase::UpdateAttachmentSlot(), and EntityLightSource::UpdateMode().
GetStackMaxForSlotId()
InventorySlots::GetStackMaxForSlotId (int slot_Id) static private
Parameters
[in] slot_id queried slot
Returns
stackMax attribute from corresponding entry (or default value == 1)
Examples
P:/extracted/scripts/3_Game/Systems/Inventory/InventorySlots.c.
Referenced by AttachmentCategoriesRow::CanCombine(), SlotsIcon::ClearRemainSelected(), AttachmentCategoriesRow::Combine(), AttachmentCategoriesRow::DraggingOverHeader(), InventoryItem::GetQuantityMax(), InventoryItem::GetTargetQuantityMax(), and AttachmentCategoriesRow::Select().
IsSlotIdValid()
InventorySlots::IsSlotIdValid (int slotId) static private
verifies existence of the slot id
Returns
true if slot valid
Examples
P:/extracted/scripts/3_Game/Systems/Inventory/InventorySlots.c.
Referenced by InventoryItem::SplitIntoStackMax(), and TranslateAndValidateSlot().
Member Data Documentation
COUNT
const int InventorySlots::COUNT private
Amount of pre-populated slots (32)
Examples
P:/extracted/scripts/3_Game/Systems/Inventory/InventorySlots.c.
Definition at line 15 of file InventorySlots.c.
INVALID
const int InventorySlots::INVALID private
Invalid slot (-1)
Examples
P:/extracted/scripts/3_Game/Systems/Inventory/InventorySlots.c.
Definition at line 17 of file InventorySlots.c.
Referenced by ActionRefuelTorch::ActionCondition(), ActionDetachFromTarget::ActionCondition(), ActionAttachOnSelection::ActionCondition(), ActionDetachFromTarget_SpecificSlot_MetalSheets(), VehicleBattery::CanPutAsAttachment(), Entity::CheckExclusionAccessPropagation(), Entity::FindAttachmentBySlotName(), ActionAttachOnSelection::FindSlotIdToAttachOrCombine(), ActionDetachFromTarget::FindSlotIdToDetach(), ActionDetachFromTarget_SpecificSlotsCategory::FindSlotIdToDetach(), GameInventory::GetCurrentAttachmentSlotInfo(), ActionDetachFromTarget::GetDisplayInteractObject(), BotStateBase::GetNextSlot(), Entity::InitInherentSlotExclusionMap(), ActionDetachFromTarget::SetupAction(), and ActionAttachOnSelection::SetupAction().
The documentation for this class was generated from the following file:
scripts/3_Game/Systems/Inventory/InventorySlots.c