DayZ: ActionWritePaper Class Reference
ActionWritePaper Class Reference
Private Member Functions
void ActionWritePaper ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStartClient (ActionData action_data)
override void OnStartServer (ActionData action_data)
override void OnUpdate (ActionData action_data)
override void OnEndRequest (ActionData action_data)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Private Attributes
const float TARGET_DISTANCE = 2
Detailed Description
Definition at line 33 of file ActionWritePaper.c.
Constructor & Destructor Documentation
ActionWritePaper()
void ActionWritePaper::ActionWritePaper () inline private
Definition at line 37 of file ActionWritePaper.c.
  {
    m_CallbackClass = ActionWritePaperCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_VIEWNOTE;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_PRONE;
    m_Text = "#write_note";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionWritePaper::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 52 of file ActionWritePaper.c.
  {
    if ((item && item.ConfigIsExisting("writingColor") && target.GetObject() && Paper.Cast(target.GetObject())) || (target.GetObject() && target.GetObject().ConfigIsExisting("writingColor") && item && Paper.Cast(item)))
      return true;
    return false;
  }
CreateConditionComponents()
override void ActionWritePaper::CreateConditionComponents () inline private
Definition at line 46 of file ActionWritePaper.c.
  {
    m_ConditionItem = new CCINonRuined;
    m_ConditionTarget = new CCTNone;//CCTNonRuined(TARGET_DISTANCE);
  }
References m_ConditionItem, and m_ConditionTarget.
OnEndRequest()
override void ActionWritePaper::OnEndRequest (ActionData action_data) inline private
Definition at line 86 of file ActionWritePaper.c.
  {
    if (action_data.m_Callback)
      action_data.m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_INTERRUPT);
  }
OnStartClient()
override void ActionWritePaper::OnStartClient (ActionData action_data) inline private
Definition at line 59 of file ActionWritePaper.c.
  {
    if (action_data.m_Target.GetObject().ConfigIsExisting("writingColor"))
      action_data.m_MainItem.GetWrittenNoteData().InitNoteInfo(ItemBase.Cast(action_data.m_Target.GetObject()), action_data.m_MainItem);
    else
      ItemBase.Cast(action_data.m_Target.GetObject()).GetWrittenNoteData().InitNoteInfo(action_data.m_MainItem, ItemBase.Cast(action_data.m_Target.GetObject()));
  }
References ItemBase::GetWrittenNoteData().
OnStartServer()
override void ActionWritePaper::OnStartServer (ActionData action_data) inline private
Definition at line 67 of file ActionWritePaper.c.
  {
    if (action_data.m_Target.GetObject().ConfigIsExisting("writingColor"))
      action_data.m_MainItem.GetWrittenNoteData().InitNoteInfo(ItemBase.Cast(action_data.m_Target.GetObject()), action_data.m_MainItem);
    else
      ItemBase.Cast(action_data.m_Target.GetObject()).GetWrittenNoteData().InitNoteInfo(action_data.m_MainItem, ItemBase.Cast(action_data.m_Target.GetObject()));
  }
References ItemBase::GetWrittenNoteData().
OnUpdate()
override void ActionWritePaper::OnUpdate (ActionData action_data) inline private
Definition at line 75 of file ActionWritePaper.c.
  {
    super.OnUpdate(action_data);
    if (!GetGame().IsDedicatedServer())
    {
      if (action_data.m_State == UA_FINISHED && GetGame().GetUIManager() && !GetGame().GetUIManager().IsMenuOpen(MENU_NOTE))
        ActionManagerClient.Cast(action_data.m_Player.GetActionManager()).RequestEndAction();
    }
  }
References GetGame(), MENU_NOTE, ActionManagerClient::RequestEndAction(), and UA_FINISHED.
Member Data Documentation
TARGET_DISTANCE
const float ActionWritePaper::TARGET_DISTANCE = 2 private
Definition at line 35 of file ActionWritePaper.c.
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionWritePaper.c