DayZ: ActionDigWorms Class Reference
ActionDigWorms Class Reference
Private Member Functions
void ActionDigWorms ()
override void CreateConditionComponents ()
override bool Can (PlayerBase player, ActionTarget target, ItemBase item, int condition_mask)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
override bool HasTarget ()
override void OnFinishProgressServer (ActionData action_data)
void SetDiggingAnimation (ItemBase item)
bool IsTargetFertile (ActionTarget target)
bool IsPlayerOnGround (PlayerBase player)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 14 of file ActionDigWorms.c.
Constructor & Destructor Documentation
ActionDigWorms()
void ActionDigWorms::ActionDigWorms () inline private
Definition at line 16 of file ActionDigWorms.c.
  {
    m_CallbackClass = ActionDigWormsCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DIGMANIPULATE;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
    m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_MEDIUM;
    m_Text = "#dig_up_worms";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_MEDIUM.
Member Function Documentation
ActionCondition()
override bool ActionDigWorms::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 40 of file ActionDigWorms.c.
  {
    if (player.IsPlacingLocal())
      return false;
    return IsTargetFertile(target) && IsPlayerOnGround(player);
  }
References IsPlayerOnGround(), and IsTargetFertile().
ActionConditionContinue()
override bool ActionDigWorms::ActionConditionContinue (ActionData action_data) inline private
Definition at line 48 of file ActionDigWorms.c.
  {
    return IsPlayerOnGround(action_data.m_Player);
  }
References IsPlayerOnGround().
Can()
override bool ActionDigWorms::Can (PlayerBase player, ActionTarget target, ItemBase item, int condition_mask) inline private
Definition at line 32 of file ActionDigWorms.c.
  {
    if (!super.Can(player, target, item, condition_mask))
      return false;
    return player.CheckFreeSpace(vector.Forward, 0.8, false);
  }
References vector::Forward.
CreateConditionComponents()
override void ActionDigWorms::CreateConditionComponents () inline private
Definition at line 26 of file ActionDigWorms.c.
  {
    m_ConditionItem = new CCINonRuined;
    m_ConditionTarget = new CCTSurface(UAMaxDistances.DEFAULT);
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool ActionDigWorms::HasTarget () inline private
Definition at line 66 of file ActionDigWorms.c.
  {
    return true;
  }
IsPlayerOnGround()
bool ActionDigWorms::IsPlayerOnGround (PlayerBase player) inline private
Definition at line 111 of file ActionDigWorms.c.
  {
    vector position = player.GetPosition();
    float heightDiff = GetGame().SurfaceY(position[0], position[2]);
    heightDiff = position[1] - heightDiff;
    return heightDiff <= 0.4; // Player is considered on ground
  }
References GetGame().
Referenced by ActionCondition(), and ActionConditionContinue().
IsTargetFertile()
bool ActionDigWorms::IsTargetFertile (ActionTarget target) inline private
Definition at line 94 of file ActionDigWorms.c.
  {
    if (target)
    {
      string surface_type;
      vector position;
      position = target.GetCursorHitPos();
      GetGame().SurfaceGetType(position[0], position[2], surface_type);
      if (GetGame().IsSurfaceFertile(surface_type))
        return true;
    }
    return false;
  }
References GetGame().
Referenced by ActionCondition().
OnFinishProgressServer()
override void ActionDigWorms::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 71 of file ActionDigWorms.c.
  {
    ItemBase worms;
    Class.CastTo(worms, GetGame().CreateObjectEx("Worm", action_data.m_Player.GetPosition(), ECE_PLACE_ON_SURFACE));
    worms.SetQuantity(10, false);
    MiscGameplayFunctions.DealAbsoluteDmg(action_data.m_MainItem, 4);
    action_data.m_Player.GetSoftSkillsManager().AddSpecialty(m_SpecialtyWeight);
  }
References Class::CastTo(), ECE_PLACE_ON_SURFACE, GetGame(), and m_SpecialtyWeight.
SetDiggingAnimation()
void ActionDigWorms::SetDiggingAnimation (ItemBase item) inline private
Definition at line 80 of file ActionDigWorms.c.
  {
    if (item.KindOf("Knife"))
    {
      m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_1HD;
      m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
    }
    else
    {
      m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DIGMANIPULATE;
      m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
    }
  }
References AnimatedActionBase::m_CommandUID, and m_StanceMask.
Referenced by SetupAction().
SetupAction()
override bool ActionDigWorms::SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 53 of file ActionDigWorms.c.
  {
    if (super.SetupAction(player, target, item, action_data, extra_data))
    {
      if (item)
        SetDiggingAnimation(item);
      return true;
    }
    return false;
  }
References SetDiggingAnimation().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionDigWorms.c