DayZ: BotGuardBase Class Reference
BotGuardBase Class Reference
represents guard on a transition from state to state
Private Member Functions
bool GuardCondition (BotEventBase e)
void BotGuardAnd (BotGuardBase arg0=NULL, BotGuardBase arg1=NULL)
override bool GuardCondition (BotEventBase e)
void BotGuardNot (BotGuardBase arg0=NULL)
override bool GuardCondition (BotEventBase e)
void BotGuardOr (BotGuardBase arg0=NULL, BotGuardBase arg1=NULL)
override bool GuardCondition (BotEventBase e)
Private Attributes
ref BotGuardBase m_arg0
ref BotGuardBase m_arg1
Detailed Description
represents guard on a transition from state to state
Definition at line 4 of file BotGuards.c.
Member Function Documentation
BotGuardAnd()
void BotGuardBase::BotGuardAnd (BotGuardBase arg0 = NULL, BotGuardBase arg1 = NULL) inline private
Definition at line 19 of file BotGuards.c.
{ m_arg0 = arg0; m_arg1 = arg1; }
BotGuardNot()
void BotGuardBase::BotGuardNot (BotGuardBase arg0 = NULL) inline private
Definition at line 33 of file BotGuards.c.
{ m_arg0 = arg0; }
BotGuardOr()
void BotGuardBase::BotGuardOr (BotGuardBase arg0 = NULL, BotGuardBase arg1 = NULL) inline private
Definition at line 48 of file BotGuards.c.
{ m_arg0 = arg0; m_arg1 = arg1; }
GuardCondition() [1/4]
bool BotGuardBase::GuardCondition (BotEventBase e) inline private
Definition at line 11 of file BotGuards.c.
{ return true; }
GuardCondition() [2/4]
override bool BotGuardBase::GuardCondition (BotEventBase e) inline private
Definition at line 21 of file BotGuards.c.
  {
    bool result = m_arg0.GuardCondition(e) && m_arg1.GuardCondition(e);
    botDebugPrint("[botfsm] guard - " + m_arg0.Type() + " && " + m_arg1.Type() + " = " + result);
    return result;
  }
References botDebugPrint().
GuardCondition() [3/4]
override bool BotGuardBase::GuardCondition (BotEventBase e) inline private
Definition at line 35 of file BotGuards.c.
  {
    bool result = !m_arg0.GuardCondition(e);
    botDebugPrint("[botfsm] guard - ! " + m_arg0.Type() + " = " + result);
    return result;
  }
References botDebugPrint().
GuardCondition() [4/4]
override bool BotGuardBase::GuardCondition (BotEventBase e) inline private
Definition at line 50 of file BotGuards.c.
  {
    bool result = m_arg0.GuardCondition(e) || m_arg1.GuardCondition(e);
    botDebugPrint("[botfsm] guard - " + m_arg0.Type() + " || " + m_arg1.Type() + " = " + result);
    return result;
  }
References botDebugPrint().
Member Data Documentation
m_arg0
ref BotGuardBase BotGuardBase::m_arg0 private
Definition at line 16 of file BotGuards.c.
m_arg1
ref BotGuardBase BotGuardBase::m_arg1 private
Definition at line 17 of file BotGuards.c.
The documentation for this class was generated from the following file:
scripts/4_World/Systems/Bot/BotGuards.c