DayZ: NotificationUI Class Reference
NotificationUI Class Reference
Protected Member Functions
void NotificationUI ()
void ~NotificationUI ()
void AddNotification (NotificationRuntimeData data)
void RemoveNotification (NotificationRuntimeData data)
void AddVoiceNotification (string player, string name)
void RemoveVoiceNotification (string player)
void ClearVoiceNotifications ()
void UpdateTargetHeight ()
void UpdateOffset ()
void Update (float timeslice)
Protected Attributes
ref Widget m_Root
ref Widget m_Spacer
ref Widget m_VoiceContent
ref Widget m_NotificationContent
ref map< NotificationRuntimeData, Widget > m_Notifications
ref map< string, Widget > m_VoiceNotifications
float m_Width
float m_CurrentHeight
float m_TargetHeight
float m_BackupPosX
float m_BackupPosY
ref map< string, Widget > m_WidgetTimers
bool m_OffsetEnabled
Static Protected Attributes
static float m_VelArr [1]
Detailed Description
Definition at line 1 of file NotificationUI.c.
Constructor & Destructor Documentation
NotificationUI()
void NotificationUI::NotificationUI () inline protected
Definition at line 20 of file NotificationUI.c.
  {
    m_Root = GetGame().GetWorkspace().CreateWidgets("gui/layouts/new_ui/notifications/notifications.layout");
    m_Spacer = m_Root.FindAnyWidget("NotificationSpacer");
    m_VoiceContent = m_Root.FindAnyWidget("VoiceContent");
    m_NotificationContent = m_Root.FindAnyWidget("NotificationContent");
    m_Notifications = new map<NotificationRuntimeData, Widget>;
    m_VoiceNotifications = new map<string, Widget>;
    m_WidgetTimers = new map<string, Widget>;
    NotificationSystem ntfSys = NotificationSystem.GetInstance();
    if (ntfSys)
    {
      ntfSys.m_OnNotificationAdded.Insert(AddNotification);
      ntfSys.m_OnNotificationRemoved.Insert(RemoveNotification);
    }
  }
References AddNotification(), GetGame(), NotificationSystem::GetInstance(), m_NotificationContent, m_Notifications, m_Root, m_Spacer, m_VoiceContent, m_VoiceNotifications, m_WidgetTimers, and RemoveNotification().
~NotificationUI()
void NotificationUI::~NotificationUI () inline protected
Definition at line 38 of file NotificationUI.c.
  {
    NotificationSystem ntfSys = NotificationSystem.GetInstance();
    if (ntfSys)
    {
      ntfSys.m_OnNotificationAdded.Remove(AddNotification);
      ntfSys.m_OnNotificationRemoved.Remove(RemoveNotification);
    }
  }
References AddNotification(), NotificationSystem::GetInstance(), and RemoveNotification().
Member Function Documentation
AddNotification()
void NotificationUI::AddNotification (NotificationRuntimeData data) inline protected
Definition at line 48 of file NotificationUI.c.
  {
    Widget notification = GetGame().GetWorkspace().CreateWidgets("gui/layouts/new_ui/notifications/notification_element.layout", m_NotificationContent);
    ImageWidget icon = ImageWidget.Cast(notification.FindAnyWidget("Image"));
    RichTextWidget title = RichTextWidget.Cast(notification.FindAnyWidget("Title"));
    if (data.GetIcon() != "")
      icon.LoadImageFile(0, data.GetIcon());
    title.SetText(data.GetTitleText());
    if (data.GetDetailText() != "")
    {
      Widget bottom_spacer = notification.FindAnyWidget("BottomSpacer");
      RichTextWidget detail = RichTextWidget.Cast(notification.FindAnyWidget("Detail"));
      bottom_spacer.Show(true);
      detail.SetText(data.GetDetailText());
      detail.Update();
      bottom_spacer.Update();
      notification.Update();
    }
    m_Notifications.Insert(data, notification);
    UpdateTargetHeight();
  }
References GetGame(), m_NotificationContent, m_Notifications, and UpdateTargetHeight().
Referenced by NotificationUI(), and ~NotificationUI().
AddVoiceNotification()
void NotificationUI::AddVoiceNotification (string player, string name) inline protected
Definition at line 85 of file NotificationUI.c.
  {
    if (!m_VoiceNotifications.Contains(player))
    {
      Widget notification;
      if (!m_WidgetTimers.Contains(player))
        notification = GetGame().GetWorkspace().CreateWidgets("gui/layouts/new_ui/notifications/notification_voice_element.layout", m_VoiceContent);
      else
      {
        notification = m_WidgetTimers.Get(player);
        m_WidgetTimers.Remove(player);
        notification.SetAlpha(120 / 255);
        Widget w_c = notification.FindAnyWidget("Name");
        if (w_c)
          w_c.SetAlpha(1);
      }
      RichTextWidget title = RichTextWidget.Cast(notification.FindAnyWidget("Name"));
      m_VoiceNotifications.Insert(player, notification);
      title.SetText(name);
      UpdateTargetHeight();
    }
  }
References GetGame(), m_VoiceContent, m_VoiceNotifications, m_WidgetTimers, name, and UpdateTargetHeight().
ClearVoiceNotifications()
void NotificationUI::ClearVoiceNotifications () inline protected
Definition at line 120 of file NotificationUI.c.
  {
    for (int i = 0; i < m_VoiceNotifications.Count(); i++)
    {
      Widget w = m_VoiceNotifications.GetElement(i);
      delete w;
    }
    m_VoiceNotifications.Clear();
    UpdateTargetHeight();
  }
References m_VoiceNotifications, and UpdateTargetHeight().
RemoveNotification()
void NotificationUI::RemoveNotification (NotificationRuntimeData data) inline protected
Definition at line 74 of file NotificationUI.c.
  {
    if (m_Notifications.Contains(data))
    {
      Widget notification = m_Notifications.Get(data);
      m_WidgetTimers.Insert(m_WidgetTimers.Count().ToString() + data.GetTime().ToString(), notification);
      m_Notifications.Remove(data);
      UpdateTargetHeight();
    }
  }
References m_Notifications, m_WidgetTimers, and UpdateTargetHeight().
Referenced by NotificationUI(), and ~NotificationUI().
RemoveVoiceNotification()
void NotificationUI::RemoveVoiceNotification (string player) inline protected
Definition at line 109 of file NotificationUI.c.
  {
    if (m_VoiceNotifications.Contains(player))
    {
      Widget notification = m_VoiceNotifications.Get(player);
      m_WidgetTimers.Insert(player, notification);
      m_VoiceNotifications.Remove(player);
      UpdateTargetHeight();
    }
  }
References m_VoiceNotifications, m_WidgetTimers, and UpdateTargetHeight().
Update()
void NotificationUI::Update (float timeslice) inline protected
Definition at line 173 of file NotificationUI.c.
  {
    UpdateOffset();
    float x;
    m_Spacer.GetScreenSize(x, m_TargetHeight);
    bool is_near = (m_CurrentHeight + 0.01 < m_TargetHeight || m_CurrentHeight - 0.01 > m_TargetHeight);
    if (is_near)
    {
      m_CurrentHeight = Math.SmoothCD(m_CurrentHeight, m_TargetHeight, m_VelArr, 0.2, 10000, timeslice);
      m_Root.SetSize(m_Width, m_CurrentHeight);
    }
    else if (m_TargetHeight != m_CurrentHeight)
    {
      m_CurrentHeight = m_TargetHeight;
      m_Root.SetSize(m_Width, m_CurrentHeight);
      m_VelArr[0] = 0;
    }
    for (int i = 0; i < m_WidgetTimers.Count();)
    {
      Widget w = m_WidgetTimers.GetElement(i);
      float new_alpha = Math.Clamp(w.GetAlpha() - timeslice / NotificationSystem.NOTIFICATION_FADE_TIME, 0, 1);
      if (new_alpha > 0)
      {
        w.SetAlpha(new_alpha);
        Widget w_c = w.FindAnyWidget("TopSpacer");
        Widget w_c2 = w.FindAnyWidget("BottomSpacer");
        Widget w_c3 = w.FindAnyWidget("Title");
        Widget w_c4 = w.FindAnyWidget("Detail");
        Widget w_c5 = w.FindAnyWidget("Name");
        if (w_c && w_c2)
        {
          float new_alpha_cont = Math.Clamp(w_c.GetAlpha() - timeslice / NotificationSystem.NOTIFICATION_FADE_TIME, 0, 1);
          w_c.SetAlpha(new_alpha_cont);
          w_c2.SetAlpha(new_alpha_cont);
          w_c3.SetAlpha(new_alpha_cont);
          w_c4.SetAlpha(new_alpha_cont);
        }
        if (w_c5)
        {
          float new_alpha_voice = Math.Clamp(w_c5.GetAlpha() - timeslice / NotificationSystem.NOTIFICATION_FADE_TIME, 0, 1);
          w_c5.SetAlpha(new_alpha_voice);
        }
        i++;
      }
      else
      {
        delete w;
        m_WidgetTimers.RemoveElement(i);
        UpdateTargetHeight();
      }
    }
  }
References Math::Clamp(), m_CurrentHeight, m_Root, m_Spacer, m_TargetHeight, m_VelArr, m_WidgetTimers, m_Width, NotificationSystem::NOTIFICATION_FADE_TIME, Math::SmoothCD(), UpdateOffset(), UpdateTargetHeight(), and x.
UpdateOffset()
void NotificationUI::UpdateOffset () inline protected
Definition at line 144 of file NotificationUI.c.
  {
    UIScriptedMenu menu = UIScriptedMenu.Cast(GetGame().GetUIManager().GetMenu());
    if (menu)
    {
      Widget expNotification = menu.GetLayoutRoot().FindAnyWidget("notification_root");
      if (expNotification && expNotification.IsVisible())
      {
        if (!m_OffsetEnabled)
        {
          m_Root.GetPos(m_BackupPosX, m_BackupPosY);
          float x, y, w, h;
          m_Root.GetScreenPos(x, y);
          expNotification.GetScreenSize(w, h);
          m_Root.SetScreenPos(x, h);
          m_OffsetEnabled = true;
        }
      }
      else if (m_OffsetEnabled)
      {
        m_Root.SetPos(m_BackupPosX, m_BackupPosY);
        m_OffsetEnabled = false;
      }
    }
  }
References GetGame(), m_BackupPosX, m_BackupPosY, m_OffsetEnabled, m_Root, x, and y.
Referenced by Update(), and UpdateTargetHeight().
UpdateTargetHeight()
void NotificationUI::UpdateTargetHeight () inline protected
Definition at line 131 of file NotificationUI.c.
  {
    m_VoiceContent.Update();
    m_NotificationContent.Update();
    m_Spacer.Update();
    float x;
    m_Spacer.GetScreenSize(x, m_TargetHeight);
    m_Root.GetScreenSize(m_Width, m_CurrentHeight);
    UpdateOffset();
  }
References m_CurrentHeight, m_NotificationContent, m_Root, m_Spacer, m_TargetHeight, m_VoiceContent, m_Width, UpdateOffset(), and x.
Referenced by AddNotification(), AddVoiceNotification(), ClearVoiceNotifications(), RemoveNotification(), RemoveVoiceNotification(), and Update().
Member Data Documentation
m_BackupPosX
float NotificationUI::m_BackupPosX protected
Definition at line 14 of file NotificationUI.c.
Referenced by UpdateOffset().
m_BackupPosY
float NotificationUI::m_BackupPosY protected
Definition at line 15 of file NotificationUI.c.
Referenced by UpdateOffset().
m_CurrentHeight
float NotificationUI::m_CurrentHeight protected
Definition at line 12 of file NotificationUI.c.
Referenced by Update(), and UpdateTargetHeight().
m_NotificationContent
ref Widget NotificationUI::m_NotificationContent protected
Definition at line 6 of file NotificationUI.c.
Referenced by AddNotification(), NotificationUI(), and UpdateTargetHeight().
m_Notifications
ref map<NotificationRuntimeData, Widget> NotificationUI::m_Notifications protected
Definition at line 8 of file NotificationUI.c.
Referenced by AddNotification(), NotificationUI(), and RemoveNotification().
m_OffsetEnabled
bool NotificationUI::m_OffsetEnabled protected
Definition at line 18 of file NotificationUI.c.
Referenced by UpdateOffset().
m_Root
ref Widget NotificationUI::m_Root protected
Definition at line 3 of file NotificationUI.c.
Referenced by NotificationUI(), Update(), UpdateOffset(), and UpdateTargetHeight().
m_Spacer
ref Widget NotificationUI::m_Spacer protected
Definition at line 4 of file NotificationUI.c.
Referenced by NotificationUI(), Update(), and UpdateTargetHeight().
m_TargetHeight
float NotificationUI::m_TargetHeight protected
Definition at line 13 of file NotificationUI.c.
Referenced by Update(), and UpdateTargetHeight().
m_VelArr
float NotificationUI::m_VelArr[1] static protected
Definition at line 172 of file NotificationUI.c.
Referenced by Update().
m_VoiceContent
ref Widget NotificationUI::m_VoiceContent protected
Definition at line 5 of file NotificationUI.c.
Referenced by AddVoiceNotification(), NotificationUI(), and UpdateTargetHeight().
m_VoiceNotifications
ref map<string, Widget> NotificationUI::m_VoiceNotifications protected
Definition at line 9 of file NotificationUI.c.
Referenced by AddVoiceNotification(), ClearVoiceNotifications(), NotificationUI(), and RemoveVoiceNotification().
m_WidgetTimers
ref map<string, Widget> NotificationUI::m_WidgetTimers protected
Definition at line 16 of file NotificationUI.c.
Referenced by AddVoiceNotification(), NotificationUI(), RemoveNotification(), RemoveVoiceNotification(), and Update().
m_Width
float NotificationUI::m_Width protected
Definition at line 11 of file NotificationUI.c.
Referenced by Update(), and UpdateTargetHeight().
The documentation for this class was generated from the following file:
scripts/3_Game/Client/Notifications/NotificationUI.c