DayZ: scripts/4_World/Entities/AdvancedCommunication/AdvancedCommunication.c File Reference
AdvancedCommunication.c File Reference
Classes
class EntityAI
class AdvancedCommunication
Functions
void AdvancedCommunication ()
void TurnOnTransmitter ()
void TurnOffTransmitter ()
void InitializeActions ()
override void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
void SetActions ()
void AddAction (typename actionName)
void RemoveAction (typename actionName)
Variables
static ref map< typename, ref TInputActionMap > m_AdvComTypeActionsMap = new map<typename, ref TInputActionMap>
TInputActionMap m_InputActionMap
bool m_ActionsInitialize
class PASBroadcaster extends AdvancedCommunication IsInventoryVisible
Function Documentation
AddAction()
void IsInventoryVisible::AddAction (typename actionName)
Definition at line 212 of file AdvancedCommunication.c.
Referenced by ManBase::AddAction(), RemoteDetonatorReceiver(), EntityAI::SetActions(), StaticTransmitter::SetActions(), Land_Misc_Through_Static::SetActions(), Land_Underground_Panel_Lever::SetActions(), SetActions(), BuildingSuper::SetActions(), InventoryItemSuper::SetActions(), ItemBase::SetActions(), ItemOptics::SetActions(), ClaymoreMine::SetActions(), ImprovisedExplosive::SetActions(), Plastic_Explosive::SetActions(), RemoteDetonatorTrigger::SetActions(), Rifle_Base::SetActions(), BoltActionRifle_ExternalMagazine_Base::SetActions(), BoltActionRifle_Base::SetActions(), DoubleBarrel_Base::SetActions(), Weapon_Base::SetActions(), Mp133Shotgun_Base::SetActions(), Weapon::SetActions(), InventoryItem::SetActions(), Barrel_ColorBase::SetActions(), BaseBuildingBase::SetActions(), Battery9V::SetActions(), BloodContainerBase::SetActions(), ToolBase::SetActions(), CattleProd::SetActions(), Chemlight_ColorBase::SetActions(), ItemMap::SetActions(), Clothing::SetActions(), Mask_Base::SetActions(), HeadGear_Base::SetActions(), Top_Base::SetActions(), Pants_Base::SetActions(), DrysackBag_ColorBase::SetActions(), Glasses_Base::SetActions(), Shoes_Base::SetActions(), Gloves_Base::SetActions(), HelmetBase::SetActions(), RopeBelt::SetActions(), WitchHoodCoif_ColorBase::SetActions(), Compass::SetActions(), Edible_Base::SetActions(), AgaricusMushroom::SetActions(), Apple::SetActions(), AuriculariaMushroom::SetActions(), Banana::SetActions(), BoletusMushroom::SetActions(), Bottle_Base::SetActions(), Cannabis::SetActions(), GreenBellPepper::SetActions(), Kiwi::SetActions(), LactariusMushroom::SetActions(), MacrolepiotaMushroom::SetActions(), Orange::SetActions(), Pear::SetActions(), PleurotusMushroom::SetActions(), Plum::SetActions(), Potato::SetActions(), SlicedPumpkin::SetActions(), TetracyclineAntibiotics::SetActions(), Tomato::SetActions(), TunaCan::SetActions(), VitaminBottle::SetActions(), Zucchini::SetActions(), EyeMask_ColorBase::SetActions(), FireplaceBase::SetActions(), FishingRod_Base_New::SetActions(), WoodenCrate::SetActions(), Bandana_ColorBase::SetActions(), Bone::SetActions(), DuctTape::SetActions(), SmallStone::SetActions(), TannedLeather::SetActions(), BurlapSack::SetActions(), ChickenFeather::SetActions(), LongWoodenStick::SetActions(), SharpWoodenStick::SetActions(), Spear::SetActions(), Fabric::SetActions(), AntiPestsSpray::SetActions(), SeedBase::SetActions(), SodaCan_ColorBase::SetActions(), BakedBeansCan_Opened::SetActions(), DogFoodCan::SetActions(), PorkCan::SetActions(), Lunchmeat::SetActions(), Pajka::SetActions(), Pate::SetActions(), BrisketSpread::SetActions(), Marmalade::SetActions(), MushroomBase::SetActions(), Honey::SetActions(), Zagorky_ColorBase::SetActions(), Snack_ColorBase::SetActions(), PeachesCan_Opened::SetActions(), PowderedMilk::SetActions(), Rice::SetActions(), SardinesCan_Opened::SetActions(), SpaghettiCan_Opened::SetActions(), TacticalBaconCan_Opened::SetActions(), TunaCan_Opened::SetActions(), AntiChemInjector::SetActions(), BloodTestKit::SetActions(), DisinfectantAlcohol::SetActions(), Epinephrine::SetActions(), IodineTincture::SetActions(), Morphine::SetActions(), SalineBagIV::SetActions(), Splint::SetActions(), GPSReceiver::SetActions(), Binoculars::SetActions(), AlarmClock_ColorBase::SetActions(), BroomBase::SetActions(), Crowbar::SetActions(), EpoxyPutty::SetActions(), FarmingHoe::SetActions(), FireExtinguisher::SetActions(), HandcuffKeys::SetActions(), Handcuffs::SetActions(), HandSaw::SetActions(), HayHook::SetActions(), Iceaxe::SetActions(), KitchenTimer::SetActions(), LeatherSewingKit::SetActions(), Lockpick::SetActions(), LugWrench::SetActions(), MeatTenderizer::SetActions(), Paddle::SetActions(), Pen_ColorBase::SetActions(), SewingKit::SetActions(), Wrench::SetActions(), Container_Base::SetActions(), Grenade_Base::SetActions(), Heatpack::SetActions(), KazuarOptic::SetActions(), StarlightOptic::SetActions(), Inventory_Base::SetActions(), LongTorch::SetActions(), Ammunition_Base::SetActions(), ItemMegaphone::SetActions(), PoweredOptic_Base::SetActions(), PunchedCard::SetActions(), ItemRadio::SetActions(), Roadflare::SetActions(), StunBaton::SetActions(), Switchable_Base::SetActions(), TelescopicBaton::SetActions(), TentBase::SetActions(), FlammableBase::SetActions(), ItemTransmitter::SetActions(), TrapBase::SetActions(), TrapSpawnBase::SetActions(), TripodBase::SetActions(), VehicleBattery::SetActions(), WoodenStick::SetActions(), CarScript::SetActions(), ManBase::SetActions(), ManBase::SetActionsRemoteTarget(), and UnknownFoodCan_Opened().
AdvancedCommunication()
void IsInventoryVisible::AdvancedCommunication ()
Definition at line 134 of file AdvancedCommunication.c.
{
  proto native void SwitchOn(bool onOff);
  proto native bool IsOn();
};
class StaticTransmitter extends AdvancedCommunication
GetActions()
override void IsInventoryVisible::GetActions (typename action_input_type , out array< ActionBase_Basic > actions)
Definition at line 194 of file AdvancedCommunication.c.
{
  static ref map<typename, ref TInputActionMap> m_AdvComTypeActionsMap = new map<typename, ref TInputActionMap>;
  TInputActionMap m_InputActionMap;
  bool m_ActionsInitialize;
  void AdvancedCommunication()
  {
    if (!GetGame().IsDedicatedServer())
    {
      if (GetGame().GetPlayer())
        m_ActionsInitialize = false;
    }
  }
  //HUD
  /*
    protected Hud GetHud( PlayerBase player )
    {
    if ( !player )
    {
      return NULL;
    }
    return player.m_Hud;
    }
    void DisplayRadioInfo( string message, PlayerBase player )
    {
    Hud hud;
    if ( player )
    {
      hud = GetHud( player );
    }
    if ( hud )
    {
      hud.SetWalkieTalkieText( message );
      hud.ShowWalkieTalkie( 3 );
    }
    }
  */
  //control transmitter via user actions
  void TurnOnTransmitter()
  {
    GetCompEM().SwitchOn();
  }
  void TurnOffTransmitter()
  {
    GetCompEM().SwitchOff();
  }
  void InitializeActions()
  {
    m_InputActionMap = m_AdvComTypeActionsMap.Get(this.Type());
    if (!m_InputActionMap)
    {
      TInputActionMap iam = new TInputActionMap;
      m_InputActionMap = iam;
      SetActions();
      m_AdvComTypeActionsMap.Insert(this.Type(), m_InputActionMap);
    }
  }
  override void GetActions(typename action_input_type, out array<ActionBase_Basic> actions)
  {
    if (!m_ActionsInitialize)
    {
      m_ActionsInitialize = true;
      InitializeActions();
    }
    actions = m_InputActionMap.Get(action_input_type);
  }
  void SetActions()
  {
    AddAction(ActionTurnOnTransmitterOnGround);
    AddAction(ActionTurnOffTransmitterOnGround);
    AddAction(ActionDetachPowerSourceFromPanel);
  }
  void AddAction(typename actionName)
  {
    ActionBase action = ActionManagerBase.GetAction(actionName);
    if (!action)
    {
      Debug.LogError("Action " + actionName + " dosn't exist!");
      return;
    }
    typename ai = action.GetInputType();
    if (!ai)
    {
      m_ActionsInitialize = false;
      return;
    }
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (!action_array)
    {
      action_array = new array<ActionBase_Basic>;
      m_InputActionMap.Insert(ai, action_array);
    }
    if (LogManager.IsActionLogEnable())
      Debug.ActionLog(action.ToString() + " -> " + ai, this.ToString(), "n/a", "Add action");
    action_array.Insert(action);
  }
  void RemoveAction(typename actionName)
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    ActionBase action = player.GetActionManager().GetAction(actionName);
    typename ai = action.GetInputType();
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (action_array)
      action_array.RemoveItem(action);
  }
}
class PASReceiver extends AdvancedCommunication
{
  override bool IsInventoryVisible()
  {
    return false;
  }
};
class PASBroadcaster extends AdvancedCommunication
{
  proto native void SwitchOn(bool onOff);
  proto native bool IsOn();
};
class StaticTransmitter extends AdvancedCommunication
{
  proto native void SwitchOn(bool onOff);
  proto native bool IsOn();
  proto native void SetNextChannel();
  proto native void SetPrevChannel();
  proto native float GetTunedFrequency();
  proto native void EnableBroadcast(bool state);
  proto native void EnableReceive(bool state);
  proto native bool IsBroadcasting();
  proto native bool IsReceiving();
  proto native int GetTunedFrequencyIndex();
  proto native void SetFrequencyByIndex(int index);
}
InitializeActions()
void IsInventoryVisible::InitializeActions ()
Definition at line 182 of file AdvancedCommunication.c.
{
  static ref map<typename, ref TInputActionMap> m_AdvComTypeActionsMap = new map<typename, ref TInputActionMap>;
  TInputActionMap m_InputActionMap;
  bool m_ActionsInitialize;
  void AdvancedCommunication()
  {
    if (!GetGame().IsDedicatedServer())
    {
      if (GetGame().GetPlayer())
        m_ActionsInitialize = false;
    }
  }
  //HUD
  /*
    protected Hud GetHud( PlayerBase player )
    {
    if ( !player )
    {
      return NULL;
    }
    return player.m_Hud;
    }
    void DisplayRadioInfo( string message, PlayerBase player )
    {
    Hud hud;
    if ( player )
    {
      hud = GetHud( player );
    }
    if ( hud )
    {
      hud.SetWalkieTalkieText( message );
      hud.ShowWalkieTalkie( 3 );
    }
    }
  */
  //control transmitter via user actions
  void TurnOnTransmitter()
  {
    GetCompEM().SwitchOn();
  }
  void TurnOffTransmitter()
  {
    GetCompEM().SwitchOff();
  }
  void InitializeActions()
  {
    m_InputActionMap = m_AdvComTypeActionsMap.Get(this.Type());
    if (!m_InputActionMap)
    {
      TInputActionMap iam = new TInputActionMap;
      m_InputActionMap = iam;
      SetActions();
      m_AdvComTypeActionsMap.Insert(this.Type(), m_InputActionMap);
    }
  }
  override void GetActions(typename action_input_type, out array<ActionBase_Basic> actions)
  {
    if (!m_ActionsInitialize)
    {
      m_ActionsInitialize = true;
      InitializeActions();
    }
    actions = m_InputActionMap.Get(action_input_type);
  }
  void SetActions()
  {
    AddAction(ActionTurnOnTransmitterOnGround);
    AddAction(ActionTurnOffTransmitterOnGround);
    AddAction(ActionDetachPowerSourceFromPanel);
  }
  void AddAction(typename actionName)
  {
    ActionBase action = ActionManagerBase.GetAction(actionName);
    if (!action)
    {
      Debug.LogError("Action " + actionName + " dosn't exist!");
      return;
    }
    typename ai = action.GetInputType();
    if (!ai)
    {
      m_ActionsInitialize = false;
      return;
    }
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (!action_array)
    {
      action_array = new array<ActionBase_Basic>;
      m_InputActionMap.Insert(ai, action_array);
    }
    if (LogManager.IsActionLogEnable())
      Debug.ActionLog(action.ToString() + " -> " + ai, this.ToString(), "n/a", "Add action");
    action_array.Insert(action);
  }
  void RemoveAction(typename actionName)
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    ActionBase action = player.GetActionManager().GetAction(actionName);
    typename ai = action.GetInputType();
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (action_array)
      action_array.RemoveItem(action);
  }
}
class PASReceiver extends AdvancedCommunication
{
  override bool IsInventoryVisible()
  {
    return false;
  }
};
class PASBroadcaster extends AdvancedCommunication
{
  proto native void SwitchOn(bool onOff);
  proto native bool IsOn();
};
class StaticTransmitter extends AdvancedCommunication
{
  proto native void SwitchOn(bool onOff);
  proto native bool IsOn();
  proto native void SetNextChannel();
  proto native void SetPrevChannel();
  proto native float GetTunedFrequency();
  proto native void EnableBroadcast(bool state);
  proto native void EnableReceive(bool state);
  proto native bool IsBroadcasting();
  proto native bool IsReceiving();
  proto native int GetTunedFrequencyIndex();
  proto native void SetFrequencyByIndex(int index);
}
Referenced by EntityAI::GetActions(), GetActions(), InventoryItem::GetActions(), and ManBase::GetActions().
RemoveAction()
void IsInventoryVisible::RemoveAction (typename actionName)
Definition at line 242 of file AdvancedCommunication.c.
{
  static ref map<typename, ref TInputActionMap> m_AdvComTypeActionsMap = new map<typename, ref TInputActionMap>;
  TInputActionMap m_InputActionMap;
  bool m_ActionsInitialize;
  void AdvancedCommunication()
  {
    if (!GetGame().IsDedicatedServer())
    {
      if (GetGame().GetPlayer())
        m_ActionsInitialize = false;
    }
  }
  //HUD
  /*
    protected Hud GetHud( PlayerBase player )
    {
    if ( !player )
    {
      return NULL;
    }
    return player.m_Hud;
    }
    void DisplayRadioInfo( string message, PlayerBase player )
    {
    Hud hud;
    if ( player )
    {
      hud = GetHud( player );
    }
    if ( hud )
    {
      hud.SetWalkieTalkieText( message );
      hud.ShowWalkieTalkie( 3 );
    }
    }
  */
  //control transmitter via user actions
  void TurnOnTransmitter()
  {
    GetCompEM().SwitchOn();
  }
  void TurnOffTransmitter()
  {
    GetCompEM().SwitchOff();
  }
  void InitializeActions()
  {
    m_InputActionMap = m_AdvComTypeActionsMap.Get(this.Type());
    if (!m_InputActionMap)
    {
      TInputActionMap iam = new TInputActionMap;
      m_InputActionMap = iam;
      SetActions();
      m_AdvComTypeActionsMap.Insert(this.Type(), m_InputActionMap);
    }
  }
  override void GetActions(typename action_input_type, out array<ActionBase_Basic> actions)
  {
    if (!m_ActionsInitialize)
    {
      m_ActionsInitialize = true;
      InitializeActions();
    }
    actions = m_InputActionMap.Get(action_input_type);
  }
  void SetActions()
  {
    AddAction(ActionTurnOnTransmitterOnGround);
    AddAction(ActionTurnOffTransmitterOnGround);
    AddAction(ActionDetachPowerSourceFromPanel);
  }
  void AddAction(typename actionName)
  {
    ActionBase action = ActionManagerBase.GetAction(actionName);
    if (!action)
    {
      Debug.LogError("Action " + actionName + " dosn't exist!");
      return;
    }
    typename ai = action.GetInputType();
    if (!ai)
    {
      m_ActionsInitialize = false;
      return;
    }
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (!action_array)
    {
      action_array = new array<ActionBase_Basic>;
      m_InputActionMap.Insert(ai, action_array);
    }
    if (LogManager.IsActionLogEnable())
      Debug.ActionLog(action.ToString() + " -> " + ai, this.ToString(), "n/a", "Add action");
    action_array.Insert(action);
  }
  void RemoveAction(typename actionName)
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    ActionBase action = player.GetActionManager().GetAction(actionName);
    typename ai = action.GetInputType();
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (action_array)
      action_array.RemoveItem(action);
  }
}
class PASReceiver extends AdvancedCommunication
{
  override bool IsInventoryVisible()
  {
    return false;
  }
};
class PASBroadcaster extends AdvancedCommunication
{
  proto native void SwitchOn(bool onOff);
  proto native bool IsOn();
};
class StaticTransmitter extends AdvancedCommunication
{
  proto native void SwitchOn(bool onOff);
  proto native bool IsOn();
  proto native void SetNextChannel();
  proto native void SetPrevChannel();
  proto native float GetTunedFrequency();
  proto native void EnableBroadcast(bool state);
  proto native void EnableReceive(bool state);
  proto native bool IsBroadcasting();
  proto native bool IsReceiving();
  proto native int GetTunedFrequencyIndex();
  proto native void SetFrequencyByIndex(int index);
}
Referenced by OnVariablesSynchronized(), ManBase::RemoveAction(), Land_Misc_Through_Static::SetActions(), CarDoor::SetActions(), RemoteDetonatorTrigger::SetActions(), Rifle_Base::SetActions(), BoltActionRifle_Base::SetActions(), DoubleBarrel_Base::SetActions(), Weapon_Base::SetActions(), Mp133Shotgun_Base::SetActions(), SetActions(), ItemBase::SetActions(), Bottle_Base::SetActions(), Binoculars::SetActions(), PoweredOptic_Base::SetActions(), TentBase::SetActions(), and TrapSpawnBase::SetActions().
SetActions()
override void SetActions ()
Definition at line 205 of file AdvancedCommunication.c.
{
  static ref map<typename, ref TInputActionMap> m_AdvComTypeActionsMap = new map<typename, ref TInputActionMap>;
  TInputActionMap m_InputActionMap;
  bool m_ActionsInitialize;
  void AdvancedCommunication()
  {
    if (!GetGame().IsDedicatedServer())
    {
      if (GetGame().GetPlayer())
        m_ActionsInitialize = false;
    }
  }
  //HUD
  /*
    protected Hud GetHud( PlayerBase player )
    {
    if ( !player )
    {
      return NULL;
    }
    return player.m_Hud;
    }
    void DisplayRadioInfo( string message, PlayerBase player )
    {
    Hud hud;
    if ( player )
    {
      hud = GetHud( player );
    }
    if ( hud )
    {
      hud.SetWalkieTalkieText( message );
      hud.ShowWalkieTalkie( 3 );
    }
    }
  */
  //control transmitter via user actions
  void TurnOnTransmitter()
  {
    GetCompEM().SwitchOn();
  }
  void TurnOffTransmitter()
  {
    GetCompEM().SwitchOff();
  }
  void InitializeActions()
  {
    m_InputActionMap = m_AdvComTypeActionsMap.Get(this.Type());
    if (!m_InputActionMap)
    {
      TInputActionMap iam = new TInputActionMap;
      m_InputActionMap = iam;
      SetActions();
      m_AdvComTypeActionsMap.Insert(this.Type(), m_InputActionMap);
    }
  }
  override void GetActions(typename action_input_type, out array<ActionBase_Basic> actions)
  {
    if (!m_ActionsInitialize)
    {
      m_ActionsInitialize = true;
      InitializeActions();
    }
    actions = m_InputActionMap.Get(action_input_type);
  }
  void SetActions()
  {
    AddAction(ActionTurnOnTransmitterOnGround);
    AddAction(ActionTurnOffTransmitterOnGround);
    AddAction(ActionDetachPowerSourceFromPanel);
  }
  void AddAction(typename actionName)
  {
    ActionBase action = ActionManagerBase.GetAction(actionName);
    if (!action)
    {
      Debug.LogError("Action " + actionName + " dosn't exist!");
      return;
    }
    typename ai = action.GetInputType();
    if (!ai)
    {
      m_ActionsInitialize = false;
      return;
    }
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (!action_array)
    {
      action_array = new array<ActionBase_Basic>;
      m_InputActionMap.Insert(ai, action_array);
    }
    if (LogManager.IsActionLogEnable())
      Debug.ActionLog(action.ToString() + " -> " + ai, this.ToString(), "n/a", "Add action");
    action_array.Insert(action);
  }
  void RemoveAction(typename actionName)
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    ActionBase action = player.GetActionManager().GetAction(actionName);
    typename ai = action.GetInputType();
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (action_array)
      action_array.RemoveItem(action);
  }
}
class PASReceiver extends AdvancedCommunication
{
  override bool IsInventoryVisible()
  {
    return false;
  }
};
class PASBroadcaster extends AdvancedCommunication
{
  proto native void SwitchOn(bool onOff);
  proto native bool IsOn();
};
class StaticTransmitter extends AdvancedCommunication
{
  proto native void SwitchOn(bool onOff);
  proto native bool IsOn();
  proto native void SetNextChannel();
  proto native void SetPrevChannel();
  proto native float GetTunedFrequency();
  proto native void EnableBroadcast(bool state);
  proto native void EnableReceive(bool state);
  proto native bool IsBroadcasting();
  proto native bool IsReceiving();
  proto native int GetTunedFrequencyIndex();
  proto native void SetFrequencyByIndex(int index);
}
Referenced by EntityAI::InitializeActions(), InitializeActions(), and ManBase::InitializeActions().
TurnOffTransmitter()
void IsInventoryVisible::TurnOffTransmitter ()
Definition at line 177 of file AdvancedCommunication.c.
{
  static ref map<typename, ref TInputActionMap> m_AdvComTypeActionsMap = new map<typename, ref TInputActionMap>;
  TInputActionMap m_InputActionMap;
  bool m_ActionsInitialize;
  void AdvancedCommunication()
  {
    if (!GetGame().IsDedicatedServer())
    {
      if (GetGame().GetPlayer())
        m_ActionsInitialize = false;
    }
  }
  //HUD
  /*
    protected Hud GetHud( PlayerBase player )
    {
    if ( !player )
    {
      return NULL;
    }
    return player.m_Hud;
    }
    void DisplayRadioInfo( string message, PlayerBase player )
    {
    Hud hud;
    if ( player )
    {
      hud = GetHud( player );
    }
    if ( hud )
    {
      hud.SetWalkieTalkieText( message );
      hud.ShowWalkieTalkie( 3 );
    }
    }
  */
  //control transmitter via user actions
  void TurnOnTransmitter()
  {
    GetCompEM().SwitchOn();
  }
  void TurnOffTransmitter()
  {
    GetCompEM().SwitchOff();
  }
  void InitializeActions()
  {
    m_InputActionMap = m_AdvComTypeActionsMap.Get(this.Type());
    if (!m_InputActionMap)
    {
      TInputActionMap iam = new TInputActionMap;
      m_InputActionMap = iam;
      SetActions();
      m_AdvComTypeActionsMap.Insert(this.Type(), m_InputActionMap);
    }
  }
  override void GetActions(typename action_input_type, out array<ActionBase_Basic> actions)
  {
    if (!m_ActionsInitialize)
    {
      m_ActionsInitialize = true;
      InitializeActions();
    }
    actions = m_InputActionMap.Get(action_input_type);
  }
  void SetActions()
  {
    AddAction(ActionTurnOnTransmitterOnGround);
    AddAction(ActionTurnOffTransmitterOnGround);
    AddAction(ActionDetachPowerSourceFromPanel);
  }
  void AddAction(typename actionName)
  {
    ActionBase action = ActionManagerBase.GetAction(actionName);
    if (!action)
    {
      Debug.LogError("Action " + actionName + " dosn't exist!");
      return;
    }
    typename ai = action.GetInputType();
    if (!ai)
    {
      m_ActionsInitialize = false;
      return;
    }
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (!action_array)
    {
      action_array = new array<ActionBase_Basic>;
      m_InputActionMap.Insert(ai, action_array);
    }
    if (LogManager.IsActionLogEnable())
      Debug.ActionLog(action.ToString() + " -> " + ai, this.ToString(), "n/a", "Add action");
    action_array.Insert(action);
  }
  void RemoveAction(typename actionName)
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    ActionBase action = player.GetActionManager().GetAction(actionName);
    typename ai = action.GetInputType();
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (action_array)
      action_array.RemoveItem(action);
  }
}
class PASReceiver extends AdvancedCommunication
{
  override bool IsInventoryVisible()
  {
    return false;
  }
};
class PASBroadcaster extends AdvancedCommunication
{
  proto native void SwitchOn(bool onOff);
  proto native bool IsOn();
};
class StaticTransmitter extends AdvancedCommunication
{
  proto native void SwitchOn(bool onOff);
  proto native bool IsOn();
  proto native void SetNextChannel();
  proto native void SetPrevChannel();
  proto native float GetTunedFrequency();
  proto native void EnableBroadcast(bool state);
  proto native void EnableReceive(bool state);
  proto native bool IsBroadcasting();
  proto native bool IsReceiving();
  proto native int GetTunedFrequencyIndex();
  proto native void SetFrequencyByIndex(int index);
}
TurnOnTransmitter()
void IsInventoryVisible::TurnOnTransmitter ()
Definition at line 172 of file AdvancedCommunication.c.
{
  static ref map<typename, ref TInputActionMap> m_AdvComTypeActionsMap = new map<typename, ref TInputActionMap>;
  TInputActionMap m_InputActionMap;
  bool m_ActionsInitialize;
  void AdvancedCommunication()
  {
    if (!GetGame().IsDedicatedServer())
    {
      if (GetGame().GetPlayer())
        m_ActionsInitialize = false;
    }
  }
  //HUD
  /*
    protected Hud GetHud( PlayerBase player )
    {
    if ( !player )
    {
      return NULL;
    }
    return player.m_Hud;
    }
    void DisplayRadioInfo( string message, PlayerBase player )
    {
    Hud hud;
    if ( player )
    {
      hud = GetHud( player );
    }
    if ( hud )
    {
      hud.SetWalkieTalkieText( message );
      hud.ShowWalkieTalkie( 3 );
    }
    }
  */
  //control transmitter via user actions
  void TurnOnTransmitter()
  {
    GetCompEM().SwitchOn();
  }
  void TurnOffTransmitter()
  {
    GetCompEM().SwitchOff();
  }
  void InitializeActions()
  {
    m_InputActionMap = m_AdvComTypeActionsMap.Get(this.Type());
    if (!m_InputActionMap)
    {
      TInputActionMap iam = new TInputActionMap;
      m_InputActionMap = iam;
      SetActions();
      m_AdvComTypeActionsMap.Insert(this.Type(), m_InputActionMap);
    }
  }
  override void GetActions(typename action_input_type, out array<ActionBase_Basic> actions)
  {
    if (!m_ActionsInitialize)
    {
      m_ActionsInitialize = true;
      InitializeActions();
    }
    actions = m_InputActionMap.Get(action_input_type);
  }
  void SetActions()
  {
    AddAction(ActionTurnOnTransmitterOnGround);
    AddAction(ActionTurnOffTransmitterOnGround);
    AddAction(ActionDetachPowerSourceFromPanel);
  }
  void AddAction(typename actionName)
  {
    ActionBase action = ActionManagerBase.GetAction(actionName);
    if (!action)
    {
      Debug.LogError("Action " + actionName + " dosn't exist!");
      return;
    }
    typename ai = action.GetInputType();
    if (!ai)
    {
      m_ActionsInitialize = false;
      return;
    }
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (!action_array)
    {
      action_array = new array<ActionBase_Basic>;
      m_InputActionMap.Insert(ai, action_array);
    }
    if (LogManager.IsActionLogEnable())
      Debug.ActionLog(action.ToString() + " -> " + ai, this.ToString(), "n/a", "Add action");
    action_array.Insert(action);
  }
  void RemoveAction(typename actionName)
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    ActionBase action = player.GetActionManager().GetAction(actionName);
    typename ai = action.GetInputType();
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (action_array)
      action_array.RemoveItem(action);
  }
}
class PASReceiver extends AdvancedCommunication
{
  override bool IsInventoryVisible()
  {
    return false;
  }
};
class PASBroadcaster extends AdvancedCommunication
{
  proto native void SwitchOn(bool onOff);
  proto native bool IsOn();
};
class StaticTransmitter extends AdvancedCommunication
{
  proto native void SwitchOn(bool onOff);
  proto native bool IsOn();
  proto native void SetNextChannel();
  proto native void SetPrevChannel();
  proto native float GetTunedFrequency();
  proto native void EnableBroadcast(bool state);
  proto native void EnableReceive(bool state);
  proto native bool IsBroadcasting();
  proto native bool IsReceiving();
  proto native int GetTunedFrequencyIndex();
  proto native void SetFrequencyByIndex(int index);
}
Variable Documentation
IsInventoryVisible
class AdvancedCommunication extends EntityAI IsInventoryVisible
Definition at line 1 of file AdvancedCommunication.c.
  {
    return false;
  }
m_ActionsInitialize
bool m_ActionsInitialize
Definition at line 132 of file AdvancedCommunication.c.
Referenced by EntityAI::AddAction(), AddAction(), InventoryItem::AddAction(), ManBase::AddAction(), EntityAI::AdvancedCommunication(), BuildingBase(), EntityAI::GetActions(), GetActions(), InventoryItem::GetActions(), ManBase::GetActions(), ManBase::Init(), and InventoryItem::ItemBase().
m_AdvComTypeActionsMap
ref map<typename, ref TInputActionMap> m_AdvComTypeActionsMap = new map<typename, ref TInputActionMap> static
Definition at line 130 of file AdvancedCommunication.c.
Referenced by EntityAI::InitializeActions().
m_InputActionMap
TInputActionMap m_InputActionMap
Definition at line 131 of file AdvancedCommunication.c.
Referenced by EntityAI::AddAction(), AddAction(), InventoryItem::AddAction(), ManBase::AddAction(), EntityAI::GetActions(), GetActions(), InventoryItem::GetActions(), ManBase::GetActions(), EntityAI::InitializeActions(), InitializeActions(), InventoryItem::InitializeActions(), ManBase::InitializeActions(), EntityAI::RemoveAction(), RemoveAction(), InventoryItem::RemoveAction(), and ManBase::RemoveAction().