DayZ: ActionTakeArrowToHands Class Reference
ActionTakeArrowToHands Class Reference
Private Member Functions
void ActionTakeArrowToHands ()
override void CreateConditionComponents ()
override bool HasProneException ()
override GetInputType ()
override bool HasProgress ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override Object GetDisplayInteractObject (PlayerBase player, ActionTarget target)
override bool CanContinue (ActionData action_data)
override bool InventoryReservation (ActionData action_data)
override void OnExecute (ActionData action_data)
override void CreateAndSetupActionCallback (ActionData action_data)
override bool CanBeUsedOnBack ()
Detailed Description
Definition at line 1 of file ActionTakeArrowToHands.c.
Constructor & Destructor Documentation
ActionTakeArrowToHands()
void ActionTakeArrowToHands::ActionTakeArrowToHands () inline private
Definition at line 3 of file ActionTakeArrowToHands.c.
  {
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_HANDS;
    m_CommandUIDProne = DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HANDS;
    m_Text = "#take_to_hands";
  }
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionTakeArrowToHands::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 31 of file ActionTakeArrowToHands.c.
  {
    EntityAI targetEntity = EntityAI.Cast(target.GetObject());
    if (!targetEntity || (targetEntity && targetEntity.IsManagingArrows() && !targetEntity.IsDamageDestroyed()))
      return false;
    ArrowManagerBase arrowManager = targetEntity.GetArrowManager();
    if (arrowManager)
    {
      ItemBase arrow = ItemBase.Cast(arrowManager.GetFirstArrow());
      if (arrow && !arrow.IsSetForDeletion())
      {
        if (player.GetInventory().CanAddEntityIntoHands(arrow))
          return true;
      }
    }
    return false;
  }
CanBeUsedOnBack()
override bool ActionTakeArrowToHands::CanBeUsedOnBack () inline private
Definition at line 145 of file ActionTakeArrowToHands.c.
  {
    return true;
  }
CanContinue()
override bool ActionTakeArrowToHands::CanContinue (ActionData action_data) inline private
Definition at line 64 of file ActionTakeArrowToHands.c.
  {
    return true;
  }
CreateAndSetupActionCallback()
override void ActionTakeArrowToHands::CreateAndSetupActionCallback (ActionData action_data) inline private
Definition at line 121 of file ActionTakeArrowToHands.c.
  {
    EntityAI target = EntityAI.Cast(action_data.m_Target.GetObject());
    if (!target)
      return;
    ActionBaseCB callback;
    if (target.IsHeavyBehaviour())
      Class.CastTo(callback, action_data.m_Player.StartCommand_Action(DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HEAVY, GetCallbackClassTypename(), DayZPlayerConstants.STANCEMASK_ERECT));
    else
    {
      if (action_data.m_Player.IsPlayerInStance(DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT))
        Class.CastTo(callback, action_data.m_Player.AddCommandModifier_Action(m_CommandUID, GetCallbackClassTypename()));
      else
        Class.CastTo(callback, action_data.m_Player.StartCommand_Action(m_CommandUIDProne, GetCallbackClassTypename(), DayZPlayerConstants.STANCEMASK_PRONE));
    }
    callback.SetActionData(action_data);
    callback.InitActionComponent();
    action_data.m_Callback = callback;
  }
References Class::CastTo(), AnimatedActionBase::GetCallbackClassTypename(), AnimatedActionBase::m_CommandUID, and AnimatedActionBase::m_CommandUIDProne.
CreateConditionComponents()
override void ActionTakeArrowToHands::CreateConditionComponents () inline private
Definition at line 10 of file ActionTakeArrowToHands.c.
  {
    m_ConditionItem = new CCINone();
    m_ConditionTarget = new CCTObject(UAMaxDistances.DEFAULT);
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetDisplayInteractObject()
override Object ActionTakeArrowToHands::GetDisplayInteractObject (PlayerBase player, ActionTarget target) inline private
Definition at line 51 of file ActionTakeArrowToHands.c.
  {
    EntityAI targetEntity = EntityAI.Cast(target.GetObject());
    if (!targetEntity || (targetEntity && targetEntity.IsManagingArrows() && !targetEntity.IsDamageDestroyed()))
      return null;
    ArrowManagerBase arrowManager = targetEntity.GetArrowManager();
    if (arrowManager)
      return arrowManager.GetFirstArrow();
    return null;
  }
GetInputType()
override ActionTakeArrowToHands::GetInputType () inline private
Definition at line 21 of file ActionTakeArrowToHands.c.
  {
    return ContinuousInteractActionInput;
  }
HasProgress()
override bool ActionTakeArrowToHands::HasProgress () inline private
Definition at line 26 of file ActionTakeArrowToHands.c.
  {
    return false;
  }
HasProneException()
override bool ActionTakeArrowToHands::HasProneException () inline private
Definition at line 16 of file ActionTakeArrowToHands.c.
  {
    return true;
  }
InventoryReservation()
override bool ActionTakeArrowToHands::InventoryReservation (ActionData action_data) inline private
Definition at line 69 of file ActionTakeArrowToHands.c.
  {
    bool success = true;
    InventoryLocation il = new InventoryLocation();
    EntityAI targetEntity;
    if (EntityAI.CastTo(targetEntity, action_data.m_Target.GetObject()))
    {
      ArrowManagerBase arrowManager = targetEntity.GetArrowManager();
      if (arrowManager)
      {
        ItemBase targetArrow = ItemBase.Cast(arrowManager.GetFirstArrow());
        if (targetArrow)
        {
          il.SetHands(action_data.m_Player, targetArrow);
          if (action_data.m_Player.GetInventory().HasInventoryReservation(targetArrow, il))
            success = false;
          else
            action_data.m_Player.GetInventory().AddInventoryReservationEx(targetArrow, il, GameInventory.c_InventoryReservationTimeoutMS);
        }
      }
    }
    if (success)
    {
      if (il)
        action_data.m_ReservedInventoryLocations.Insert(il);
    }
    return success;
  }
References GameInventory::c_InventoryReservationTimeoutMS.
OnExecute()
override void ActionTakeArrowToHands::OnExecute (ActionData action_data) inline private
Definition at line 103 of file ActionTakeArrowToHands.c.
  {
    if (GetGame().IsMultiplayer() && GetGame().IsServer())
      return;
    InventoryLocation il = action_data.m_ReservedInventoryLocations.Get(0);
    ItemBase arrow = ItemBase.Cast(il.GetItem());
    ClearInventoryReservationEx(action_data);
    float stackable = arrow.GetTargetQuantityMax(-1);
    if (stackable == 0 || stackable >= arrow.GetQuantity())
      action_data.m_Player.PredictiveTakeEntityToHands(arrow);
    else
      arrow.SplitIntoStackMaxToInventoryLocationClient(il);
  }
References ClearInventoryReservationEx(), and GetGame().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Interact/ActionTakeArrowToHands.c