DayZ: InventoryItemType Class Reference
InventoryItemType Class Reference
Private Member Functions
void InventoryItemType ()
void ~InventoryItemType ()
void LoadSoundEvents ()
AnimSoundEvent GetSoundEvent (int event_id)
proto native owned string GetName ()
Private Attributes
ref array< ref AnimSoundEvent > m_animSoundEvents
Detailed Description
Definition at line 1 of file InventoryItemType.c.
Constructor & Destructor Documentation
InventoryItemType()
void InventoryItemType::InventoryItemType () inline private
Definition at line 5 of file InventoryItemType.c.
  {
    LoadSoundEvents();
  }
References LoadSoundEvents().
~InventoryItemType()
void InventoryItemType::~InventoryItemType () private
Member Function Documentation
GetName()
proto native owned string InventoryItemType::GetName () private
Referenced by LoadSoundEvents().
GetSoundEvent()
AnimSoundEvent InventoryItemType::GetSoundEvent (int event_id) inline private
Definition at line 50 of file InventoryItemType.c.
  {
    foreach (AnimSoundEvent soundEvent : m_animSoundEvents)
    {
      if (soundEvent.m_iID == event_id)
        return soundEvent;
    }
    return null;
  }
References m_animSoundEvents.
LoadSoundEvents()
void InventoryItemType::LoadSoundEvents () inline private
Definition at line 12 of file InventoryItemType.c.
  {
    string cfgPath = "CfgVehicles " + GetName() + " AnimEvents SoundWeapon";
    m_animSoundEvents = new array<ref AnimSoundEvent>;
    int soundCount = GetGame().ConfigGetChildrenCount(cfgPath);
    if (soundCount <= 0)//try other path
    {
      cfgPath = "CfgWeapons " + GetName() + " AnimEvents SoundWeapon";
      soundCount = GetGame().ConfigGetChildrenCount(cfgPath);
    }
    if (soundCount <= 0)//try other path
    {
      cfgPath = "CfgMagazines " + GetName() + " AnimEvents SoundWeapon";
      soundCount = GetGame().ConfigGetChildrenCount(cfgPath);
    }
    if (soundCount <= 0)//try other path
    {
      cfgPath = "CfgAmmo " + GetName() + " AnimEvents SoundWeapon";
      soundCount = GetGame().ConfigGetChildrenCount(cfgPath);
    }
    for (int i = 0; i < soundCount; i++)
    {
      string soundName;
      GetGame().ConfigGetChildName(cfgPath, i, soundName);
      string soundPath = cfgPath + " " + soundName + " ";
      AnimSoundEvent soundEvent = new AnimSoundEvent(soundPath);
      if (soundEvent.IsValid())
        m_animSoundEvents.Insert(soundEvent);
    }
  }
References GetGame(), GetName(), and m_animSoundEvents.
Referenced by InventoryItemType().
Member Data Documentation
m_animSoundEvents
ref array<ref AnimSoundEvent> InventoryItemType::m_animSoundEvents private
Definition at line 3 of file InventoryItemType.c.
Referenced by GetSoundEvent(), and LoadSoundEvents().
The documentation for this class was generated from the following file:
scripts/3_Game/InventoryItemType.c