DayZ: CAContinuousQuantityExtinguish Class Reference
CAContinuousQuantityExtinguish Class Reference
Private Member Functions
void CAContinuousQuantityExtinguish (float quantity_used_per_second, float time_to_repeat, float wetness_gain_multiplier)
override void CalcAndSetQuantity (ActionData action_data)
override int Interrupt (ActionData action_data)
void MultiplyQuantityUsed (float coef)
Private Member Functions inherited from CAContinuousQuantityRepeat
void CAContinuousQuantityRepeat (float quantity_used_per_second, float time_to_repeat)
override void Setup (ActionData action_data)
override int Execute (ActionData action_data)
override int Cancel (ActionData action_data)
override float GetProgress ()
void CalcAndSetQuantity (ActionData action_data)
Private Attributes
float m_WetnessGainMultiplier = 1.0
Private Attributes inherited from CAContinuousQuantityRepeat
float m_ItemQuantity
float m_SpentQuantity
float m_ItemMaxQuantity
float m_TimeElpased
float m_QuantityUsedPerSecond
float m_AdjustedQuantityUsedPerSecond
float m_DefaultTimeToRepeat
ref Param1< float > m_SpentUnits
Detailed Description
Definition at line 1 of file CAContinuousQuantityExtinguish.c.
Constructor & Destructor Documentation
CAContinuousQuantityExtinguish()
void CAContinuousQuantityExtinguish::CAContinuousQuantityExtinguish (float quantity_used_per_second, float time_to_repeat, float wetness_gain_multiplier) inline private
Definition at line 5 of file CAContinuousQuantityExtinguish.c.
  {
    m_QuantityUsedPerSecond = quantity_used_per_second;
    m_DefaultTimeToRepeat = time_to_repeat;
    m_WetnessGainMultiplier = wetness_gain_multiplier;
  }
References CAContinuousQuantityRepeat::m_DefaultTimeToRepeat, CAContinuousQuantityRepeat::m_QuantityUsedPerSecond, and m_WetnessGainMultiplier.
Member Function Documentation
CalcAndSetQuantity()
override void CAContinuousQuantityExtinguish::CalcAndSetQuantity (ActionData action_data) inline private
Definition at line 12 of file CAContinuousQuantityExtinguish.c.
  {
    if (GetGame().IsServer())
    {
      if (m_SpentUnits)
      {
        m_SpentUnits.param1 = m_SpentQuantity;
        SetACData(m_SpentUnits);
      }
      Object targetObject = action_data.m_Target.GetObject();
      if (targetObject)
      {
        FireplaceBase fireplace = FireplaceBase.Cast(targetObject);
        //add wetness to fireplace targets
        float wetness = (m_SpentQuantity / 1000) * m_WetnessGainMultiplier;
        fireplace.AddWetnessToFireplace(wetness);
        //subtract quantity from water source
        action_data.m_MainItem.AddQuantity(-m_SpentQuantity);
      }
    }
  }
References GetGame(), CAContinuousQuantityRepeat::m_SpentQuantity, CAContinuousQuantityRepeat::m_SpentUnits, m_WetnessGainMultiplier, and CABase::SetACData().
Interrupt()
override int CAContinuousQuantityExtinguish::Interrupt (ActionData action_data) inline private
Definition at line 37 of file CAContinuousQuantityExtinguish.c.
  {
    if (GetGame().IsServer())
      action_data.m_Player.GetSoftSkillsManager().AddSpecialty(UASoftSkillsWeight.ROUGH_MEDIUM);
    return super.Interrupt(action_data);
  }
References GetGame(), and UASoftSkillsWeight::ROUGH_MEDIUM.
MultiplyQuantityUsed()
void CAContinuousQuantityExtinguish::MultiplyQuantityUsed (float coef) inline private
Definition at line 45 of file CAContinuousQuantityExtinguish.c.
  {
    m_QuantityUsedPerSecond *= coef;
  }
References CAContinuousQuantityRepeat::m_QuantityUsedPerSecond.
Referenced by ActionExtinguishFireplaceByExtinguisherCB::CreateActionComponent(), and ActionExtinguishFireplaceByLiquidCB::CreateActionComponent().
Member Data Documentation
m_WetnessGainMultiplier
float CAContinuousQuantityExtinguish::m_WetnessGainMultiplier = 1.0 private
Definition at line 3 of file CAContinuousQuantityExtinguish.c.
Referenced by CAContinuousQuantityExtinguish(), and CalcAndSetQuantity().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousQuantityExtinguish.c