DayZ: CarWheel_Ruined Class Reference
CarWheel_Ruined Class Reference
Private Member Functions
override bool CanPutAsAttachment (EntityAI parent)
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
Detailed Description
Definition at line 277 of file InventoryItem.c.
Member Function Documentation
CanPutAsAttachment()
override bool CarWheel_Ruined::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 279 of file InventoryItem.c.
  {
    // So that the lambda can always put it to the Transport
    if (parent.IsInherited(Transport) && parent.IsRuined())
    {
      InventoryLocation loc = new InventoryLocation();
      if (GetInventory().GetCurrentInventoryLocation(loc))
        return loc.GetType() == InventoryLocationType.UNKNOWN;
      return false;
    }
    if (!super.CanPutAsAttachment(parent))
      return false;
    return true;
  }
EEHealthLevelChanged()
override void CarWheel_Ruined::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 297 of file InventoryItem.c.
  {
    super.EEHealthLevelChanged(oldLevel, newLevel, zone);
#ifdef DEVELOPER
    // used when fixing the whole car through debug
    if (newLevel == GameConstants.STATE_PRISTINE)
    {
      string newWheel = "";
      switch (GetType())
      {
      case "HatchbackWheel_Ruined":
        newWheel = "HatchbackWheel";
        break;
      case "CivSedanWheel_Ruined":
        newWheel = "CivSedanWheel";
        break;
      case "Hatchback_02_Wheel_Ruined":
        newWheel = "Hatchback_02_Wheel";
        break;
      case "Sedan_02_Wheel_Ruined":
        newWheel = "Sedan_02_Wheel";
        break;
      case "Truck_01_Wheel_Ruined":
        newWheel = "Truck_01_Wheel";
        break;
      case "Truck_01_WheelDouble_Ruined":
        newWheel = "Truck_01_WheelDouble";
        break;
      case "Offroad_02_Wheel_Ruined":
        newWheel = "Offroad_02_Wheel";
        break;
      }
      if (newWheel != "")
      {
        //Unlock to allow creating a new item
        if (IsLockedInSlot())
          UnlockFromParent();
        ReplaceWheelLambda lambda = new ReplaceWheelLambda(this, newWheel, null);
        lambda.SetTransferParams(true, true, true);
        GetInventory().ReplaceItemWithNew(InventoryMode.SERVER, lambda);
      }
    }
#endif
  }
References GetType(), ReplaceWheelLambda(), GameConstants::STATE_PRISTINE, and UnlockFromParent().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/Core/Inherited/InventoryItem.c