DayZ: GameInventory Class Reference
GameInventory Class Reference
script counterpart to engine's class Inventory
Protected Member Functions
proto native bool GetCurrentInventoryLocation (out notnull InventoryLocation loc)
returns information about current item location
proto native bool FindFreeLocationFor (notnull EntityAI item, FindInventoryLocationType flags, out notnull InventoryLocation loc)
FindFreeLocationFor.
proto native bool FindFreeLocationForEx (notnull EntityAI item, FindInventoryLocationType flags, notnull InventoryLocation exclude, out notnull InventoryLocation loc)
FindFreeLocationForEx.
proto native bool FindFirstFreeLocationForNewEntity (string item_type, FindInventoryLocationType flags, out notnull InventoryLocation loc)
FindFirstFreeLocationForNewEntity.
proto native int FindFreeLocationsFor (notnull EntityAI item, FindInventoryLocationType flags, out notnull array< ref InventoryLocation > locs)
searches inventory for suitable location for @item
bool IsInCargo ()
Returns true if this Inventory owner is in cargo of something.
bool IsAttachment ()
Returns true if this Inventory owner is an attachment of something.
bool IsCargoInHiearchy ()
Returns true if inventory owner or his hiearchy parents are in cargo.
bool GetCurrentAttachmentSlotInfo (out int slot_id, out string slot_name)
Returns true if the item is currently attached and outputs attachment slot id and name.
proto native bool CanAddSwappedEntity (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2)
void OnInventoryFailure (InventoryCommandType type, InventoryValidationReason reason, InventoryLocation src, InventoryLocation dst)
bool TakeEntityToInventory (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item)
Put item anywhere into this entity (as attachment or into cargo, recursively)
bool TakeEntityToTargetInventory (InventoryMode mode, notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
helper that finds location first, then moves the entity into it
bool TakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
move src to dst
bool TakeEntityToCargo (InventoryMode mode, notnull EntityAI item)
moves item to cargo of this intentory
bool TakeEntityToTargetCargo (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
Put item into into cargo of another entity.
bool TakeEntityToCargoEx (InventoryMode mode, notnull EntityAI item, int idx, int row, int col)
moves item on specific cargo location
bool TakeEntityToTargetCargoEx (InventoryMode mode, notnull CargoBase cargo, notnull EntityAI item, int row, int col)
Put item into into cargo on specific cargo location of another entity.
bool TakeEntityAsAttachmentEx (InventoryMode mode, notnull EntityAI item, int slot)
bool TakeEntityAsTargetAttachmentEx (InventoryMode mode, notnull EntityAI target, notnull EntityAI item, int slot)
put item as attachment of target
bool TakeEntityAsAttachment (InventoryMode mode, notnull EntityAI item)
bool TakeEntityAsTargetAttachment (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
bool SwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2)
bool ForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
bool DropEntity (InventoryMode mode, EntityAI owner, notnull EntityAI item)
bool DropEntityWithTransform (InventoryMode mode, EntityAI owner, notnull EntityAI item, vector transform[4])
bool DropEntityInBounds (InventoryMode mode, EntityAI owner, notnull EntityAI item, vector halfExtents, float angle, float cosAngle, float sinAngle)
bool LocalDestroyEntity (notnull EntityAI item)
bool ReplaceItemWithNew (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
proto native bool GetFlipCargo ()
proto native void SetFlipCargo (bool flip)
proto native void FlipCargo ()
proto native void ResetFlipCargo ()
proto native EntityAI GetInventoryOwner ()
Engine native functions.
proto native bool HasEntityInInventory (notnull EntityAI item)
query inventory if item is somewhere
proto native bool EnumerateInventory (InventoryTraversalType tt, out array< EntityAI > items)
enumerate inventory using traversal type and filling items array
proto native int CountInventory ()
almost identical to EnumerateInventory except it does not return items
proto native CargoBase GetCargo ()
cargo
proto native CargoBase GetCargoFromIndex (int index)
proto native EntityAI CreateEntityInCargo (string typeName)
Create Entity of specified type in cargo of entity.
proto native EntityAI CreateEntityInCargoEx (string typeName, int idx, int row, int col, bool flip)
Create Entity of specified type in cargo of entity at coordinates (row, col)
proto native bool HasEntityInCargo (notnull EntityAI e)
proto native bool HasEntityInCargoEx (notnull EntityAI e, int idx, int row, int col)
proto native bool CanAddEntityInCargo (notnull EntityAI e, bool flip)
proto native bool CanAddEntityInCargoEx (notnull EntityAI e, int idx, int row, int col, bool flip)
proto native bool CanAddEntityInCargoExLoc (InventoryLocation loc)
proto native bool TestAddEntityInCargoEx (notnull EntityAI e, int idx, int row, int col, bool flip, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check, bool do_script_load_check)
proto native bool TestAddEntityInCargoExLoc (notnull InventoryLocation loc, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check, bool do_script_load_check)
proto native bool CanRemoveEntityInCargo (notnull EntityAI e)
proto native bool CanRemoveEntityInCargoEx (notnull EntityAI e, int idx, int row, int col)
proto native int GetSlotId (int index)
attachments
proto native int GetSlotIdCount ()
proto native int GetAttachmentSlotId (int index)
proto native int GetAttachmentSlotsCount ()
bool HasAttachmentSlot (int slotId)
proto native bool HasInventorySlot (int slotId)
proto native int AttachmentCount ()
Returns count of attachments attached to this item.
proto native EntityAI CreateAttachment (string typeName)
Create Entity of specified type as attachment of entity.
proto native EntityAI CreateAttachmentEx (string typeName, int slotId)
Create Entity of specified type as attachment of entity.
proto native EntityAI GetAttachmentFromIndex (int index)
proto native EntityAI FindAttachment (int slot)
Returns attached entity in slot (you can use InventorySlots.GetSlotIdFromString(name) to get slot id)
proto native EntityAI FindAttachmentByName (string slotName)
Returns attached entity in slot (you can use EntityAI.GetActionComponentName to get slot id)
proto native bool HasAttachment (notnull EntityAI e)
brief Returns True if entity is attached to this
proto native bool HasAttachmentEx (notnull EntityAI e, int slot)
brief Returns True if entity is attached to this in slot
proto native bool CanAddAttachment (notnull EntityAI e)
Check if attachment can be added to any slot.
proto native bool CanAddAttachmentEx (notnull EntityAI e, int slot)
Check if attachment can be added to slot @NOTE: Note that slot index IS NOT slot ID! Slot ID is defined in DZ/data/config.cpp.
proto native bool CanRemoveAttachment (EntityAI attachment)
proto native bool CanRemoveAttachmentEx (EntityAI attachment, int slot)
proto native EntityAI FindPlaceholderForSlot (int slot)
Returns placeholder entity for slot (naked arms, legs etc)
proto native bool IsPlaceholderEntity (notnull Object e)
proto native bool CanLockInventoryWithKey (notnull EntityAI key)
locks
proto native bool CanUnlockInventoryWithKey (notnull EntityAI key)
proto native void LockInventoryWithKey (notnull EntityAI key)
proto native void UnlockInventoryWithKey (notnull EntityAI key)
proto native bool HasKeys ()
proto native void LockInventory (int lockType)
proto native void UnlockInventory (int lockType)
proto native int GetScriptLockCount ()
proto native bool IsInventoryUnlocked ()
proto native bool IsInventoryLocked ()
proto native bool IsInventoryLockedForLockType (int lockType)
proto native bool SetSlotLock (int slot, bool locked)
proto native bool GetSlotLock (int slot)
void Init ()
script functions
bool OnStoreLoad (ParamsReadContext ctx, int version)
db load hooks
void OnAfterStoreLoad ()
void OnStoreSave (ParamsWriteContext ctx)
db store hook
void EEInit ()
void EEDelete (EntityAI parent)
EntityAI CreateInInventory (string type)
creates entity somewhere in inventory
bool CanAddEntityToInventory (notnull EntityAI item, int flag=FindInventoryLocationType.ANY)
ask inventory if item could be placed somewhere in inventory
bool AddEntityToInventory (notnull EntityAI item)
add entity somewhere in inventory
bool CanRemoveEntity ()
Returns if entity can be removed from its current location.
bool CanAddEntityInto (notnull EntityAI item, FindInventoryLocationType flags=FindInventoryLocationType.ANY)
Asks inventory if item could be placed in inventory, hands, etc.
bool CanAddEntityIntoInventory (notnull EntityAI item)
Test if entity can be put to the inventory (Cargo, ProxyCargo, Attachment)
bool CanAddEntityIntoHands (notnull EntityAI item)
Test if entity can be put into hands.
bool OnInputUserDataProcess (ParamsReadContext ctx)
synchronization
bool OnInventoryJunctureFromServer (ParamsReadContext ctx)
bool OnInventoryJunctureRepairFromServer (ParamsReadContext ctx)
void OnInventoryJunctureFailureFromServer (ParamsReadContext ctx)
void OnServerInventoryCommand (ParamsReadContext ctx)
Static Protected Member Functions
static proto native EntityAI LocationCreateEntity (notnull InventoryLocation inv_loc, string type, int iSetupFlags, int iRotation)
creates new item directly at location
static proto native EntityAI LocationCreateLocalEntity (notnull InventoryLocation inv_loc, string type, int iSetupFlags, int iRotation)
creates new local item directly at location @NOTE: the item is created localy, i.e. it's not registered to network
static proto native bool LocationCanAddEntity (notnull InventoryLocation inv_loc)
queries if the entity contained in inv_loc.m_item can be added to ground/attachment/cargo/hands/...
static bool LocationCanAddEntityEx (notnull InventoryLocation inv_loc)
static proto native bool LocationTestAddEntity (notnull InventoryLocation inv_loc, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check, bool do_script_load_check)
test if the entity contained in inv_loc.m_item can be added to ground/attachment/cargo/hands/...
static proto native bool LocationCanRemoveEntity (notnull InventoryLocation inv_loc)
queries if the entity contained in inv_loc.m_item can be removed from ground/attachment/cargo/hands/...
static proto native bool LocationCanMoveEntity (notnull InventoryLocation src, notnull InventoryLocation dst)
queries if the entity contained in inv_loc.m_item can be moved to another location This is a shorthand for CanRemove + CanAdd query
static int GetInventoryCheckContext ()
static bool LocationCanMoveEntitySyncCheck (notnull InventoryLocation src, notnull InventoryLocation dst)
static proto native EntityAI LocationGetEntity (notnull InventoryLocation inv_loc)
static void OnServerInventoryCommandStatic (ParamsReadContext ctx)
static proto native bool LocationAddEntity (notnull InventoryLocation inv_loc)
adds item to inventory location
static proto native bool LocationRemoveEntity (notnull InventoryLocation inv_loc)
removes item from inventory location
static proto native bool LocationMoveEntity (notnull InventoryLocation src_loc, notnull InventoryLocation dst_loc)
removes item from current inventory location and adds it to destination
static proto native bool LocationSyncMoveEntity (notnull InventoryLocation src_loc, notnull InventoryLocation dst_loc)
synchronously removes item from current inventory location and adds it to destination no anims involved
static proto native bool LocationSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2)
swaps two entities
static proto native bool ServerLocationMoveEntity (notnull EntityAI item, ParamsWriteContext ctx)
removes item from current inventory location and adds it to destination + sync via inventory command
static proto native bool ServerLocationSyncMoveEntity (Man player, notnull EntityAI item, ParamsWriteContext ctx)
synchronously removes item from current inventory location and adds it to destination + sync via inventory command no anims involved
static proto native bool ServerLocationSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, ParamsWriteContext ctx)
swaps two entities
static proto native bool ServerHandEvent (notnull Man player, notnull EntityAI item, ParamsWriteContext ctx)
hand event to clients
static proto native bool PrepareDropEntityPos (EntityAI owner, notnull EntityAI item, out vector mat[4], bool useValuesInMatrix=false, int conflictCheckDepth=-1)
Finds a transformation for the item to be dropped to If the initial transforation overlaps with another conflicting entity (i.e. car) then the transform will be snapped to the nearest outer edge. If no valid snapping transformation could be found, then the output from 'PlaceOnSurface' is used.
static proto native bool TestDropEntityPos (EntityAI owner, notnull EntityAI item, out vector mat[4], bool useValuesInMatrix=false, int conflictCheckDepth=-1)
static proto native bool CanSwapEntities (notnull EntityAI item1, notnull EntityAI item2)
test if ordinary swap can be performed.
static bool CanSwapEntitiesEx (notnull EntityAI item1, notnull EntityAI item2)
static proto native bool CanForceSwapEntities (notnull EntityAI item1, InventoryLocation item1_dst, notnull EntityAI item2, out InventoryLocation item2_dst)
test if forced swap can be performed.
static bool CanForceSwapEntitiesEx (notnull EntityAI item1, InventoryLocation item1_dst, notnull EntityAI item2, out InventoryLocation item2_dst)
static bool MakeDstForSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, out InventoryLocation dst1, out InventoryLocation dst2)
helper function for swap
static bool MakeSrcAndDstForSwap (notnull EntityAI item1, notnull EntityAI item2, out InventoryLocation src1, out InventoryLocation src2, out InventoryLocation dst1, out InventoryLocation dst2)
helper function for swap
static bool MakeSrcAndDstForForceSwap (notnull EntityAI item1, notnull EntityAI item2, out InventoryLocation src1, out InventoryLocation src2, out InventoryLocation dst1, notnull InventoryLocation dst2)
helper function for ForceSwap
static bool SetGroundPosByOwner (EntityAI owner, notnull EntityAI item, out InventoryLocation ground)
static bool SetGroundPosByTransform (EntityAI owner, notnull EntityAI item, out InventoryLocation ground, vector transform[4])
static void SetGroundPosByOwnerBounds (EntityAI owner, notnull EntityAI item, out InventoryLocation ground, vector halfExtents, float angle, float cosAngle, float sinAngle)
Static Protected Attributes
static int m_inventory_check_context = InventoryCheckContext.DEFAULT
const int c_InventoryReservationTimeoutMS = 5000
reservations
const int c_InventoryReservationTimeoutShortMS = 3000
bool AddInventoryReservationEx (EntityAI item, InventoryLocation dst, int timeout_ms)
bool ExtendInventoryReservationEx (EntityAI item, InventoryLocation dst, int timeout_ms)
bool ClearInventoryReservationEx (EntityAI item, InventoryLocation dst)
proto native int GetAnyInventoryReservationCount ()
static proto native bool AddInventoryReservation (EntityAI item, InventoryLocation dst, int timeout_ms)
static proto native bool ExtendInventoryReservation (EntityAI item, InventoryLocation dst, int timeout_ms)
static proto native bool ClearInventoryReservation (EntityAI item, InventoryLocation dst)
static proto native bool HasInventoryReservation (EntityAI item, InventoryLocation dst)
Internally: HasInventoryReservationEx(item, dst, FindInventoryReservationMode.LEGACY, FindInventoryReservationMode.LEGACY)
static proto native bool HasInventoryReservationCanAdd (EntityAI item, InventoryLocation dst)
Internally: !HasInventoryReservationEx(item, dst, FindInventoryReservationMode.ITEM, FindInventoryReservationMode.DST)
static proto native bool HasInventoryReservationEx (EntityAI item, InventoryLocation dst, FindInventoryReservationMode itemMode, FindInventoryReservationMode parentMode)
itemMode will iterate over item reservations, parentMode will iterate over parent reservations
static proto native bool GetInventoryReservationCount (EntityAI item, InventoryLocation dst)
const float c_MaxItemDistanceRadius = 2.5
anti-cheats
static proto native bool CheckRequestSrc (notnull Man requestingPlayer, notnull InventoryLocation src, float radius)
static proto native bool CheckDropRequest (notnull Man requestingPlayer, notnull InventoryLocation src, float radius)
static proto native bool CheckTakeItemRequest (notnull Man requestingPlayer, notnull InventoryLocation src, notnull InventoryLocation dst, float radius)
static proto native bool CheckMoveToDstRequest (notnull Man requestingPlayer, notnull InventoryLocation src, notnull InventoryLocation dst, float radius)
static proto native bool CheckSwapItemsRequest (notnull Man requestingPlayer, notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, float radius)
static proto native bool CheckManipulatedObjectsDistances (notnull EntityAI e0, notnull EntityAI e1, float radius)
Detailed Description
script counterpart to engine's class Inventory
Definition at line 78 of file Inventory.c.
Member Function Documentation
AddEntityToInventory()
GameInventory::AddEntityToInventory (notnull EntityAI item) inline protected
add entity somewhere in inventory
All available inventory locations (hands, cargo, attachments, proxycargo, ...) are traversed recursively from root to leafs.
@NOTE: AddEntityToInventory does not perform the checks the CanAddEntityToInventory does (script conditions for example). if not sure, always call CanAddEntityToInventory before AddEntityToInventory.
Parameters
[in] item item to be placed in inventory
Returns
true if item can be added, false otherwise
Definition at line 899 of file Inventory.c.
  {
    InventoryLocation il = new InventoryLocation();
    bool result = FindFreeLocationFor(item, FindInventoryLocationType.ANY, il);
    if (result)
      return LocationAddEntity(il);
    return result;
  }
References FindFreeLocationFor(), and LocationAddEntity().
AddInventoryReservation()
static proto native bool GameInventory::AddInventoryReservation (EntityAI item, InventoryLocation dst, int timeout_ms) static protected
Referenced by AddInventoryReservationEx().
AddInventoryReservationEx()
bool GameInventory::AddInventoryReservationEx (EntityAI item, InventoryLocation dst, int timeout_ms) inline protected
Definition at line 691 of file Inventory.c.
  {
    if (GetGame().IsMultiplayer() && GetGame().IsServer())
      return true;
    bool ret_val = AddInventoryReservation(item, dst, timeout_ms);
#ifdef DEVELOPER
    if (LogManager.IsInventoryReservationLogEnable())
    {
      DayZPlayer player = GetGame().GetPlayer();
      if (player)
      {
        if (item)
          Debug.InventoryMoveLog("Reservation result: " + ret_val + " - STS = " + player.GetSimulationTimeStamp() + " / " + item.ToString() + " / " + InventoryLocation.DumpToStringNullSafe(dst), "n/a", "n/a", "AddInventoryReservation", player.ToString());
        else
          Debug.InventoryMoveLog("Reservation result: " + ret_val + " - STS = " + player.GetSimulationTimeStamp() + " / null / " + InventoryLocation.DumpToStringNullSafe(dst), "n/a", "n/a", "AddInventoryReservation", player.ToString());
      }
    }
#endif
    return ret_val;
  }
References AddInventoryReservation(), InventoryLocation::DumpToStringNullSafe(), GetGame(), Debug::InventoryMoveLog(), and LogManager::IsInventoryReservationLogEnable().
AttachmentCount()
GameInventory::AttachmentCount () protected
Returns count of attachments attached to this item.
CanAddAttachment()
GameInventory::CanAddAttachment (notnull EntityAI e) protected
Check if attachment can be added to any slot.
Returns
true if entity can be added as attachment
CanAddAttachmentEx()
GameInventory::CanAddAttachmentEx (notnull EntityAI e, int slot) protected
Check if attachment can be added to slot @NOTE: Note that slot index IS NOT slot ID! Slot ID is defined in DZ/data/config.cpp.
CanAddEntityInCargo()
proto native bool GameInventory::CanAddEntityInCargo (notnull EntityAI e, bool flip) protected
CanAddEntityInCargoEx()
proto native bool GameInventory::CanAddEntityInCargoEx (notnull EntityAI e, int idx, int row, int col, bool flip) protected
CanAddEntityInCargoExLoc()
proto native bool GameInventory::CanAddEntityInCargoExLoc (InventoryLocation loc) protected
CanAddEntityInto()
GameInventory::CanAddEntityInto (notnull EntityAI item, FindInventoryLocationType flags = FindInventoryLocationType.ANY) inline protected
Asks inventory if item could be placed in inventory, hands, etc.
Location is based on the flags parameter. This method is used in methods that are asking for if item can be placed in specific location, like CanAddEntityToInventory, CanAddEntityInHands, etc.
Parameters
[in] item item to be placed in inventory
[in] flags FindInventoryLocationType
Returns
true if item can be added, false otherwise
Definition at line 934 of file Inventory.c.
  {
    InventoryLocation loc = new InventoryLocation();
    return FindFreeLocationFor(item, flags, loc) && !item.IsHologram();
  }
References FindFreeLocationFor().
Referenced by CanAddEntityIntoHands(), and CanAddEntityIntoInventory().
CanAddEntityIntoHands()
bool GameInventory::CanAddEntityIntoHands (notnull EntityAI item) inline protected
Test if entity can be put into hands.
Definition at line 951 of file Inventory.c.
  {
    return CanAddEntityInto(item, FindInventoryLocationType.HANDS);
  }
References CanAddEntityInto().
CanAddEntityIntoInventory()
bool GameInventory::CanAddEntityIntoInventory (notnull EntityAI item) inline protected
Test if entity can be put to the inventory (Cargo, ProxyCargo, Attachment)
Definition at line 943 of file Inventory.c.
  {
    return CanAddEntityInto(item, FindInventoryLocationType.ANY_CARGO | FindInventoryLocationType.ATTACHMENT);
  }
References CanAddEntityInto().
CanAddEntityToInventory()
GameInventory::CanAddEntityToInventory (notnull EntityAI item, int flag = FindInventoryLocationType.ANY) inline protected
ask inventory if item could be placed somewhere in inventory
All available inventory locations (hands, cargo, attachments, proxycargo, ...) are traversed recursively from root to leafs.
Parameters
[in] item item to be placed in inventory
Returns
true if item can be added, false otherwise
Definition at line 879 of file Inventory.c.
  {
    InventoryLocation il = new InventoryLocation();
    bool result = FindFreeLocationFor(item, flag, il);
    return result;
  }
References FindFreeLocationFor().
CanAddSwappedEntity()
proto native bool GameInventory::CanAddSwappedEntity (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2) protected
CanForceSwapEntities()
GameInventory::CanForceSwapEntities (notnull EntityAI item1, InventoryLocation item1_dst, notnull EntityAI item2, out InventoryLocation item2_dst) static protected
test if forced swap can be performed.
Parameters
[in] item1 is the forced item (primary)
[in] item1_dst optional destination for item1 (null if item1 goes to place of item2)
[in] item2 second item that will be replaced by the item1. (secondary)
[out] item2_dst second item's potential destination (if null, search for item_dst2 is ommited). if (NOT null AND IsValid()), then it is tried first, without search to inventory
Returns
true if can be force swapped
Referenced by CanForceSwapEntitiesEx().
CanForceSwapEntitiesEx()
static bool GameInventory::CanForceSwapEntitiesEx (notnull EntityAI item1, InventoryLocation item1_dst, notnull EntityAI item2, out InventoryLocation item2_dst) inline static protected
Definition at line 645 of file Inventory.c.
  {
    if (!CanForceSwapEntities(item1, item1_dst, item2, item2_dst))
      return false;
    int slot;
    InventoryLocation il = new InventoryLocation;
    if (!item1.CanBeFSwaped())
      return false;
    if (item1_dst == null)
    {
      item2.GetInventory().GetCurrentInventoryLocation(il);
      slot = il.GetSlot();
    }
    else
      slot = item1_dst.GetSlot();
    if (item1.GetQuantity() > item1.GetTargetQuantityMax(slot))
      return false;
    if (item2_dst == null)
    {
      item1.GetInventory().GetCurrentInventoryLocation(il);
      slot = il.GetSlot();
    }
    else
      slot = item2_dst.GetSlot();
    if (!item1.CanSwapEntities(item2, item2_dst, item1_dst) || !item2.CanSwapEntities(item1, item1_dst, item2_dst))
      return false;
    if (item2.GetQuantity() > item2.GetTargetQuantityMax(slot))
      return false;
    return true;
  }
References CanForceSwapEntities().
Referenced by HandEventBase::CanPerformEvent(), HandEventSwap::CanPerformEvent(), WeaponManager::CanSwapMagazine(), LayoutHolder::CanSwapOrTakeToHandsEx(), Icon::DraggingOverSwap(), ItemManager::GetChosenCombinationFlag(), HandGuardBase::GuardCondition(), ManBase::OnQuickBarSingleUse(), WeaponManager::PrepareInventoryLocationForMagazineSwap(), Icon::Swap(), and ValidateSwap().
CanLockInventoryWithKey()
proto native bool GameInventory::CanLockInventoryWithKey (notnull EntityAI key) protected
locks
CanRemoveAttachment()
proto native bool GameInventory::CanRemoveAttachment (EntityAI attachment) protected
CanRemoveAttachmentEx()
proto native bool GameInventory::CanRemoveAttachmentEx (EntityAI attachment, int slot) protected
CanRemoveEntity()
bool GameInventory::CanRemoveEntity () inline protected
Returns if entity can be removed from its current location.
Definition at line 912 of file Inventory.c.
  {
    InventoryLocation il = new InventoryLocation;
    if (GetCurrentInventoryLocation(il))
      return LocationCanRemoveEntity(il);
    return false;
  }
References GetCurrentInventoryLocation(), and LocationCanRemoveEntity().
CanRemoveEntityInCargo()
proto native bool GameInventory::CanRemoveEntityInCargo (notnull EntityAI e) protected
CanRemoveEntityInCargoEx()
proto native bool GameInventory::CanRemoveEntityInCargoEx (notnull EntityAI e, int idx, int row, int col) protected
CanSwapEntities()
GameInventory::CanSwapEntities (notnull EntityAI item1, notnull EntityAI item2) static protected
test if ordinary swap can be performed.
Ordinary in the sense that the two items has equal sizes and can be swapped without additional space.
Parameters
[in] item1 first item
[in] item2 second item
Returns
true if can be swapped
Referenced by CanSwapEntitiesEx().
CanSwapEntitiesEx()
static bool GameInventory::CanSwapEntitiesEx (notnull EntityAI item1, notnull EntityAI item2) inline static protected
Definition at line 610 of file Inventory.c.
  {
    int slot;
    InventoryLocation il1 = new InventoryLocation();
    InventoryLocation il2 = new InventoryLocation();
    item2.GetInventory().GetCurrentInventoryLocation(il2);
    slot = il2.GetSlot();
    if (item1.GetQuantity() > item1.GetTargetQuantityMax(slot))
      return false;
    item1.GetInventory().GetCurrentInventoryLocation(il1);
    slot = il1.GetSlot();
    if (item2.GetQuantity() > item2.GetTargetQuantityMax(slot))
      return false;
    if (!item1.CanSwapEntities(item2, il2, il1) || !item2.CanSwapEntities(item1, il1, il2))
      return false;
    return CanSwapEntities(item1, item2);
  }
References CanSwapEntities().
Referenced by WeaponManager::CanSwapMagazine(), LayoutHolder::CanSwapOrTakeToHandsEx(), AttachmentCategoriesRow::Combine(), PlayerContainer::DraggingOver(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), ItemManager::GetChosenCombinationFlag(), HandsContainer::GetCombinationFlags(), InventoryGridController::GetQuickbarItemColor(), HandGuardBase::GuardCondition(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), ManBase::OnQuickBarSingleUse(), WeaponManager::PrepareInventoryLocationForMagazineSwap(), Attachments::Select(), Container::Select(), HandsPreview::Select(), AttachmentCategoriesRow::Select(), PlayerContainer::Select(), VicinitySlotsContainer::Select(), ZombieContainer::Select(), EntityAI::SwapEntitiesImpl(), HumanInventory::SwappingToPreviousLocation(), HandsContainer::TakeAsAttachment(), and ClosableContainer::TakeAsAttachment().
CanUnlockInventoryWithKey()
proto native bool GameInventory::CanUnlockInventoryWithKey (notnull EntityAI key) protected
CheckDropRequest()
static proto native bool GameInventory::CheckDropRequest (notnull Man requestingPlayer, notnull InventoryLocation src, float radius) static protected
CheckManipulatedObjectsDistances()
static proto native bool GameInventory::CheckManipulatedObjectsDistances (notnull EntityAI e0, notnull EntityAI e1, float radius) static protected
Referenced by VicinityItemManager::AddVicinityItems().
CheckMoveToDstRequest()
static proto native bool GameInventory::CheckMoveToDstRequest (notnull Man requestingPlayer, notnull InventoryLocation src, notnull InventoryLocation dst, float radius) static protected
Referenced by HandEventBase::CheckRequest().
CheckRequestSrc()
static proto native bool GameInventory::CheckRequestSrc (notnull Man requestingPlayer, notnull InventoryLocation src, float radius) static protected
Referenced by HandEventBase::CheckRequestSrc().
CheckSwapItemsRequest()
static proto native bool GameInventory::CheckSwapItemsRequest (notnull Man requestingPlayer, notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, float radius) static protected
Referenced by HandEventBase::CheckRequest(), and HandEventSwap::CheckRequest().
CheckTakeItemRequest()
static proto native bool GameInventory::CheckTakeItemRequest (notnull Man requestingPlayer, notnull InventoryLocation src, notnull InventoryLocation dst, float radius) static protected
ClearInventoryReservation()
static proto native bool GameInventory::ClearInventoryReservation (EntityAI item, InventoryLocation dst) static protected
Referenced by HandStateEquipped::OnEntry().
ClearInventoryReservationEx()
bool GameInventory::ClearInventoryReservationEx (EntityAI item, InventoryLocation dst) inline protected
Definition at line 737 of file Inventory.c.
  {
    if (GetGame().IsMultiplayer() && GetGame().IsServer())
      return true;
    bool ret_val = ClearInventoryReservation(item, dst);
#ifdef DEVELOPER
    if (LogManager.IsInventoryReservationLogEnable())
    {
      DayZPlayer player = GetGame().GetPlayer();
      if (player)
      {
        if (item)
          Debug.InventoryMoveLog("Reservation cleared result: " + ret_val + " - STS = " + player.GetSimulationTimeStamp() + " / " + item.ToString() + " / " + InventoryLocation.DumpToStringNullSafe(dst), "n/a", "n/a", "ClearInventoryReservation", player.ToString());
        else
          Debug.InventoryMoveLog("Reservation cleared result: " + ret_val + " - STS = " + player.GetSimulationTimeStamp() + " / null / " + InventoryLocation.DumpToStringNullSafe(dst), "n/a", "n/a", "ClearInventoryReservation", player.ToString());
      }
    }
#endif
    return ret_val;
  }
References ClearInventoryReservation(), InventoryLocation::DumpToStringNullSafe(), GetGame(), Debug::InventoryMoveLog(), and LogManager::IsInventoryReservationLogEnable().
CountInventory()
GameInventory::CountInventory () protected
almost identical to EnumerateInventory except it does not return items
Returns
number of items
CreateAttachment()
GameInventory::CreateAttachment (string typeName) protected
Create Entity of specified type as attachment of entity.
CreateAttachmentEx()
GameInventory::CreateAttachmentEx (string typeName, int slotId) protected
Create Entity of specified type as attachment of entity.
Parameters
typeName type to create
slotId the slot to be created in
CreateEntityInCargo()
proto native EntityAI GameInventory::CreateEntityInCargo (string typeName) protected
Create Entity of specified type in cargo of entity.
CreateEntityInCargoEx()
proto native EntityAI GameInventory::CreateEntityInCargoEx (string typeName, int idx, int row, int col, bool flip) protected
Create Entity of specified type in cargo of entity at coordinates (row, col)
Parameters
typeName type to create
row the row of cargo to be created at
col the column of cargo to be created at
CreateInInventory()
GameInventory::CreateInInventory (string type) inline protected
creates entity somewhere in inventory
Parameters
[in] type item type to be placed in inventory
Returns
created entity or null
Definition at line 849 of file Inventory.c.
  {
    InventoryLocation loc = new InventoryLocation();
    if (FindFirstFreeLocationForNewEntity(type, FindInventoryLocationType.CARGO | FindInventoryLocationType.ATTACHMENT, loc))
    {
      switch (loc.GetType())
      {
      case InventoryLocationType.ATTACHMENT:
        return loc.GetParent().GetInventory().CreateAttachmentEx(type, loc.GetSlot());
      case InventoryLocationType.CARGO:
        return loc.GetParent().GetInventory().CreateEntityInCargoEx(type, loc.GetIdx(), loc.GetRow(), loc.GetCol(), loc.GetFlip());
      default:
        Error("CreateInInventory: unknown location for item");
        break;
      }
    }
    return null;
  }
References Error(), and FindFirstFreeLocationForNewEntity().
DropEntity()
bool GameInventory::DropEntity (InventoryMode mode, EntityAI owner, notnull EntityAI item) inline protected
Definition at line 1221 of file Inventory.c.
  {
    if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::Drop(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
    InventoryLocation src = new InventoryLocation();
    if (item.GetInventory().GetCurrentInventoryLocation(src))
    {
      InventoryLocation dst = new InventoryLocation();
      if (!SetGroundPosByOwner(owner, item, dst))
      {
        OnInventoryFailure(InventoryCommandType.SYNC_MOVE, InventoryValidationReason.DROP_PREVENTED, src, dst);
        return false;
      }
      return TakeToDst(mode, src, dst);
    }
    Error("DropEntity - No inventory location");
    return false;
  }
References Error(), inventoryDebugPrint(), LogManager::IsInventoryMoveLogEnable(), OnInventoryFailure(), SetGroundPosByOwner(), and TakeToDst().
DropEntityInBounds()
bool GameInventory::DropEntityInBounds (InventoryMode mode, EntityAI owner, notnull EntityAI item, vector halfExtents, float angle, float cosAngle, float sinAngle) inline protected
Definition at line 1283 of file Inventory.c.
  {
    if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::Drop(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
    InventoryLocation src = new InventoryLocation();
    if (item.GetInventory().GetCurrentInventoryLocation(src))
    {
      InventoryLocation dst = new InventoryLocation();
      SetGroundPosByOwnerBounds(owner, item, dst, halfExtents, angle, cosAngle, sinAngle);
      return TakeToDst(mode, src, dst);
    }
    Error("DropEntityInBounds - No inventory location");
    return false;
  }
References Error(), inventoryDebugPrint(), LogManager::IsInventoryMoveLogEnable(), SetGroundPosByOwnerBounds(), and TakeToDst().
DropEntityWithTransform()
bool GameInventory::DropEntityWithTransform (InventoryMode mode, EntityAI owner, notnull EntityAI item, vector transform[4]) inline protected
Definition at line 1248 of file Inventory.c.
  {
    if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::Drop(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
    InventoryLocation src = new InventoryLocation();
    if (item.GetInventory().GetCurrentInventoryLocation(src))
    {
      InventoryLocation dst = new InventoryLocation();
      SetGroundPosByTransform(owner, item, dst, transform);
      return TakeToDst(mode, src, dst);
    }
    Error("DropEntityWithTransform - No inventory location");
    return false;
  }
References Error(), inventoryDebugPrint(), LogManager::IsInventoryMoveLogEnable(), SetGroundPosByTransform(), and TakeToDst().
EEDelete()
void GameInventory::EEDelete (EntityAI parent) inline protected
Definition at line 835 of file Inventory.c.
  {
    EntityAI item = GetInventoryOwner();
    Man player = item.GetHierarchyRootPlayer();
    if (player)
      player.GetInventory().ClearInventoryReservationEx(item, null);
  }
References GetInventoryOwner().
EEInit()
void GameInventory::EEInit () inline protected
Definition at line 818 of file Inventory.c.
  {
    InventoryLocation src = new InventoryLocation;
    if (GetCurrentInventoryLocation(src))
    {
      if (src.GetType() == InventoryLocationType.HANDS)
      {
        Man man = Man.Cast(src.GetParent());
        if (man)
        {
          if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("Inventory::EEInit - Man=" + man + " item=" + this);
          man.GetHumanInventory().OnEntityInHandsCreated(src);
        }
      }
    }
  }
References GetCurrentInventoryLocation(), inventoryDebugPrint(), and LogManager::IsInventoryMoveLogEnable().
EnumerateInventory()
GameInventory::EnumerateInventory (InventoryTraversalType tt, out array< EntityAI > items) protected
enumerate inventory using traversal type and filling items array
Parameters
[in] tt used traversal type
[out] items items in inventory (in order determined by traversal)
Returns
true if found any, false otherwise
ExtendInventoryReservation()
static proto native bool GameInventory::ExtendInventoryReservation (EntityAI item, InventoryLocation dst, int timeout_ms) static protected
Referenced by ExtendInventoryReservationEx().
ExtendInventoryReservationEx()
bool GameInventory::ExtendInventoryReservationEx (EntityAI item, InventoryLocation dst, int timeout_ms) inline protected
Definition at line 714 of file Inventory.c.
  {
    if (GetGame().IsMultiplayer() && GetGame().IsServer())
      return true;
    bool ret_val = ExtendInventoryReservation(item, dst, timeout_ms);
#ifdef DEVELOPER
    if (LogManager.IsInventoryReservationLogEnable())
    {
      DayZPlayer player = GetGame().GetPlayer();
      if (player)
      {
        if (item)
          Debug.InventoryMoveLog("Reservation result: " + ret_val + " - STS = " + player.GetSimulationTimeStamp() + " / " + item.ToString() + " / " + InventoryLocation.DumpToStringNullSafe(dst), "n/a", "n/a", "ExtendInventoryReservation", player.ToString());
        else
          Debug.InventoryMoveLog("Reservation result: " + ret_val + " - STS = " + player.GetSimulationTimeStamp() + " / null / " + InventoryLocation.DumpToStringNullSafe(dst), "n/a", "n/a", "ExtendInventoryReservation", player.ToString());
      }
    }
#endif
    return ret_val;
  }
References InventoryLocation::DumpToStringNullSafe(), ExtendInventoryReservation(), GetGame(), Debug::InventoryMoveLog(), and LogManager::IsInventoryReservationLogEnable().
FindAttachment()
proto native EntityAI GameInventory::FindAttachment (int slot) protected
Returns attached entity in slot (you can use InventorySlots.GetSlotIdFromString(name) to get slot id)
FindAttachmentByName()
proto native EntityAI GameInventory::FindAttachmentByName (string slotName) protected
Returns attached entity in slot (you can use EntityAI.GetActionComponentName to get slot id)
FindFirstFreeLocationForNewEntity()
proto native bool GameInventory::FindFirstFreeLocationForNewEntity (string item_type, FindInventoryLocationType flags, out notnull InventoryLocation loc) protected
FindFirstFreeLocationForNewEntity.
Parameters
[in] item_type item type that would be placed in inventory
[out] loc the InventoryLocation the item can be placed to
Returns
true if found any, false otherwise
Referenced by CreateInInventory().
FindFreeLocationFor()
proto native bool GameInventory::FindFreeLocationFor (notnull EntityAI item, FindInventoryLocationType flags, out notnull InventoryLocation loc) protected
FindFreeLocationFor.
Parameters
[in] item item that would be placed in inventory
[out] loc the InventoryLocation the item can be placed to
Returns
true if found any, false otherwise
Referenced by AddEntityToInventory(), CanAddEntityInto(), CanAddEntityToInventory(), HumanInventory::TakeEntityToInventory(), and TakeEntityToInventory().
FindFreeLocationForEx()
proto native bool GameInventory::FindFreeLocationForEx (notnull EntityAI item, FindInventoryLocationType flags, notnull InventoryLocation exclude, out notnull InventoryLocation loc) protected
FindFreeLocationForEx.
Parameters
[in] item item that would be placed in inventory
[out] loc the InventoryLocation the item can be placed to
Returns
true if found any, false otherwise
FindFreeLocationsFor()
GameInventory::FindFreeLocationsFor (notnull EntityAI item, FindInventoryLocationType flags, out notnull array< ref InventoryLocation > locs) protected
searches inventory for suitable location for @item
Parameters
[in] item item that would be placed in inventory
[in] flags flags affecting selection (
See also
FindInventoryLocation)
Parameters
[out] locs array of InventoryLocations the item can be placed to
Returns
number of suitable inventory locations
Example:
Entity bino = GetGame().CreateObject("Binoculars", "3312 0 854");
EntityAI bino2;
if (Class.CastTo(bino2, bino))
{
  array<ref InventoryLocation> a = new array<ref InventoryLocation>; // 1) allocate memory for array
  for (int i = 0; i < 10; ++i)
  {
    a.Insert(new InventoryLocation); // 2) pre-allocate inventorylocations from script. engine only fills them in, engine does not allocate memory to avoid mixing.
  }
  int sz = player.FindFreeLocationsFor(bino, FindInventoryLocationType.ANY_CARGO | FindInventoryLocationType.ATTACHMENT, a); // 3) ask engine to fill the locations
  if (sz > 0)
  {
    InventoryLocation src = new InventoryLocation;
    bino2.GetCurrentInventoryLocation(src); // 5) get current location
    InventoryLocation dst = a[0]; // 6) get first (this is only example)
    ... use src and dst
  }
}
FindPlaceholderForSlot()
proto native EntityAI GameInventory::FindPlaceholderForSlot (int slot) protected
Returns placeholder entity for slot (naked arms, legs etc)
FlipCargo()
proto native void GameInventory::FlipCargo () protected
ForceSwapEntities()
bool GameInventory::ForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) inline protected
Definition at line 1207 of file Inventory.c.
  {
    return false;
  }
GetAnyInventoryReservationCount()
proto native int GameInventory::GetAnyInventoryReservationCount () protected
GetAttachmentFromIndex()
GameInventory::GetAttachmentFromIndex (int index) protected
Returns
attached entity by attachment index @NOTE: index is not slot! for getting attachment by slot use FindAttachment
GetAttachmentSlotId()
GameInventory::GetAttachmentSlotId (int index) protected
Parameters
index index of the slot for attachment (
See also
GetAttachmentSlotsCount)
Returns
slot for attachment
Referenced by HasAttachmentSlot().
GetAttachmentSlotsCount()
GameInventory::GetAttachmentSlotsCount () protected
Returns
number of slots for attachments
Referenced by HasAttachmentSlot().
GetCargo()
proto native CargoBase GameInventory::GetCargo () protected
cargo
GetCargoFromIndex()
proto native CargoBase GameInventory::GetCargoFromIndex (int index) protected
GetCurrentAttachmentSlotInfo()
bool GameInventory::GetCurrentAttachmentSlotInfo (out int slot_id, out string slot_name) inline protected
Returns true if the item is currently attached and outputs attachment slot id and name.
Definition at line 436 of file Inventory.c.
  {
    slot_id = InventorySlots.INVALID;
    slot_name = "";
    InventoryLocation lcn = new InventoryLocation();
    GetCurrentInventoryLocation(lcn);
    if (lcn.GetType() == InventoryLocationType.ATTACHMENT)
    {
      slot_id = lcn.GetSlot();
      slot_name = InventorySlots.GetSlotName(slot_id);
      return true;
    }
    return false;
  }
References GetCurrentInventoryLocation(), InventorySlots::GetSlotName(), and InventorySlots::INVALID.
GetCurrentInventoryLocation()
GameInventory::GetCurrentInventoryLocation (out notnull InventoryLocation loc) protected
returns information about current item location
Parameters
[out] loc current InventoryLocation
Returns
true if current location retrieved (and is valid)
Referenced by CanRemoveEntity(), EEInit(), GetCurrentAttachmentSlotInfo(), IsAttachment(), and IsInCargo().
GetFlipCargo()
proto native bool GameInventory::GetFlipCargo () protected
GetInventoryCheckContext()
static int GameInventory::GetInventoryCheckContext () inline static protected
Definition at line 373 of file Inventory.c.
  {
    return m_inventory_check_context;
  }
References m_inventory_check_context.
Referenced by Container_Base::CanReceiveItemIntoCargo().
GetInventoryOwner()
GameInventory::GetInventoryOwner () protected
Engine native functions.
Returns
entity associated with this inventory
Referenced by EEDelete(), HumanInventory::GetManOwner(), Init(), IsCargoInHiearchy(), HumanInventory::LocalDestroyEntity(), HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl(), HumanInventory::ReplaceItemInHandsWithNewImpl(), HumanInventory::TakeEntityAsAttachmentEx(), TakeEntityAsAttachmentEx(), HumanInventory::TakeEntityToCargoEx(), and TakeEntityToCargoEx().
GetInventoryReservationCount()
static proto native bool GameInventory::GetInventoryReservationCount (EntityAI item, InventoryLocation dst) static protected
GetScriptLockCount()
proto native int GameInventory::GetScriptLockCount () protected
GetSlotId()
GameInventory::GetSlotId (int index) protected
attachments
Parameters
index index into array of configured slots (
See also
GetSlotIdCount)
Returns
slot where this item belongs
GetSlotIdCount()
GameInventory::GetSlotIdCount () protected
Returns
number of slots this item can belong to
GetSlotLock()
proto native bool GameInventory::GetSlotLock (int slot) protected
HasAttachment()
GameInventory::HasAttachment (notnull EntityAI e) protected
brief Returns True if entity is attached to this
HasAttachmentEx()
GameInventory::HasAttachmentEx (notnull EntityAI e, int slot) protected
brief Returns True if entity is attached to this in slot
HasAttachmentSlot()
GameInventory::HasAttachmentSlot (int slotId) inline protected
Returns
true if this entity has attachments slot with id=slotId
Definition at line 186 of file Inventory.c.
  {
    int count = GetAttachmentSlotsCount();
    for (int i = 0; i < count; i++)
    {
      if (GetAttachmentSlotId(i) == slotId)
        return true;
    }
    return false;
  }
References GetAttachmentSlotId(), and GetAttachmentSlotsCount().
HasEntityInCargo()
proto native bool GameInventory::HasEntityInCargo (notnull EntityAI e) protected
HasEntityInCargoEx()
proto native bool GameInventory::HasEntityInCargoEx (notnull EntityAI e, int idx, int row, int col) protected
HasEntityInInventory()
GameInventory::HasEntityInInventory (notnull EntityAI item) protected
query inventory if item is somewhere
All available inventory locations (hands, cargo, attachments, proxycargo, ...) are traversed recursively from root to leafs.
Parameters
[in] item item to be found in inventory
Returns
true if found, false otherwise
HasInventoryReservation()
static proto native bool GameInventory::HasInventoryReservation (EntityAI item, InventoryLocation dst) static protected
Internally: HasInventoryReservationEx(item, dst, FindInventoryReservationMode.LEGACY, FindInventoryReservationMode.LEGACY)
Referenced by HandStateEquipped::OnEntry().
HasInventoryReservationCanAdd()
static proto native bool GameInventory::HasInventoryReservationCanAdd (EntityAI item, InventoryLocation dst) static protected
Internally: !HasInventoryReservationEx(item, dst, FindInventoryReservationMode.ITEM, FindInventoryReservationMode.DST)
HasInventoryReservationEx()
static proto native bool GameInventory::HasInventoryReservationEx (EntityAI item, InventoryLocation dst, FindInventoryReservationMode itemMode, FindInventoryReservationMode parentMode) static protected
itemMode will iterate over item reservations, parentMode will iterate over parent reservations
HasInventorySlot()
GameInventory::HasInventorySlot (int slotId) protected
Returns
true if this entity has inventory slot with id=slotId
HasKeys()
proto native bool GameInventory::HasKeys () protected
Init()
GameInventory::Init () inline protected
script functions
called by engine right after creation of entity
Definition at line 804 of file Inventory.c.
  {
    GetInventoryOwner().OnInventoryInit();
  }
References GetInventoryOwner().
IsAttachment()
bool GameInventory::IsAttachment () inline protected
Returns true if this Inventory owner is an attachment of something.
Definition at line 406 of file Inventory.c.
  {
    InventoryLocation lcn = new InventoryLocation();
    GetCurrentInventoryLocation(lcn);
    if (lcn.GetType() == InventoryLocationType.ATTACHMENT)
      return true;
    return false;
  }
References GetCurrentInventoryLocation().
IsCargoInHiearchy()
bool GameInventory::IsCargoInHiearchy () inline protected
Returns true if inventory owner or his hiearchy parents are in cargo.
Definition at line 417 of file Inventory.c.
  {
    InventoryLocation lcn = new InventoryLocation();
    EntityAI ent = GetInventoryOwner();
    while (ent)
    {
      if (ent.GetInventory().GetCurrentInventoryLocation(lcn) && lcn.IsValid())
      {
        if (lcn.GetType() == InventoryLocationType.CARGO || lcn.GetType() == InventoryLocationType.PROXYCARGO)
          return true;
      }
      ent = ent.GetHierarchyParent();
    }
    return false;
  }
References GetInventoryOwner().
IsInCargo()
bool GameInventory::IsInCargo () inline protected
Returns true if this Inventory owner is in cargo of something.
Definition at line 395 of file Inventory.c.
  {
    InventoryLocation lcn = new InventoryLocation();
    GetCurrentInventoryLocation(lcn);
    if (lcn.GetType() == InventoryLocationType.CARGO)
      return true;
    return false;
  }
References GetCurrentInventoryLocation().
IsInventoryLocked()
proto native bool GameInventory::IsInventoryLocked () protected
IsInventoryLockedForLockType()
proto native bool GameInventory::IsInventoryLockedForLockType (int lockType) protected
IsInventoryUnlocked()
proto native bool GameInventory::IsInventoryUnlocked () protected
IsPlaceholderEntity()
proto native bool GameInventory::IsPlaceholderEntity (notnull Object e) protected
LocalDestroyEntity()
bool GameInventory::LocalDestroyEntity (notnull EntityAI item) inline protected
Definition at line 1301 of file Inventory.c.
  {
    if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::LocalDestroyEntity inv item=" + item);
    InventoryLocation src = new InventoryLocation();
    if (item.GetInventory().GetCurrentInventoryLocation(src))
    {
      if (src.GetType() == InventoryLocationType.HANDS)
        Error("[inv] Source location == HANDS, player has to handle this");
      GetGame().ObjectDelete(src.GetItem());
      return true;
    }
    Error("LocalDestroyEntity: No inventory location");
    return false;
  }
References Error(), GetGame(), inventoryDebugPrint(), and LogManager::IsInventoryMoveLogEnable().
LocationAddEntity()
GameInventory::LocationAddEntity (notnull InventoryLocation inv_loc) static protected
adds item to inventory location
Returns
true if success, false otherwise
Referenced by AddEntityToInventory(), and ReplaceItemWithNewLambdaBase::UndoRemoveOldItemFromLocation().
LocationCanAddEntity()
GameInventory::LocationCanAddEntity (notnull InventoryLocation inv_loc) static protected
queries if the entity contained in inv_loc.m_item can be added to ground/attachment/cargo/hands/...
query the entity at the specific inventory location
Returns
true if can be added, false otherwise
entity at the location, null otherwise
Referenced by LocationCanAddEntityEx(), and TransferInventory().
LocationCanAddEntityEx()
static bool GameInventory::LocationCanAddEntityEx (notnull InventoryLocation inv_loc) inline static protected
Definition at line 348 of file Inventory.c.
  {
    return LocationCanAddEntity(inv_loc);
  }
References LocationCanAddEntity().
LocationCanMoveEntity()
GameInventory::LocationCanMoveEntity (notnull InventoryLocation src, notnull InventoryLocation dst) static protected
queries if the entity contained in inv_loc.m_item can be moved to another location This is a shorthand for CanRemove + CanAdd query
Returns
true if can be moved, false otherwise
Referenced by HandEventBase::CanPerformEvent(), HandEventBase::CanPerformEventEx(), HandGuardBase::GuardCondition(), LocationCanMoveEntitySyncCheck(), WeaponStateBase::OnAbort(), OnAbort(), HandStateBase::OnEntry(), HandStartAction::OnEntry(), WeaponStateBase::OnExit(), and ValidateSyncMove().
LocationCanMoveEntitySyncCheck()
static bool GameInventory::LocationCanMoveEntitySyncCheck (notnull InventoryLocation src, notnull InventoryLocation dst) inline static protected
Definition at line 378 of file Inventory.c.
  {
    m_inventory_check_context = InventoryCheckContext.SYNC_CHECK;
    bool result = LocationCanMoveEntity(src, dst);
    m_inventory_check_context = InventoryCheckContext.DEFAULT;
    return result;
  }
References LocationCanMoveEntity(), and m_inventory_check_context.
Referenced by ValidateSyncMove().
LocationCanRemoveEntity()
GameInventory::LocationCanRemoveEntity (notnull InventoryLocation inv_loc) static protected
queries if the entity contained in inv_loc.m_item can be removed from ground/attachment/cargo/hands/...
Returns
true if can be added, false otherwise
Referenced by ReplaceItemWithNewLambdaBase::CanExecuteLambda(), CanRemoveEntity(), and ActionDigInStash::OnFinishProgressServer().
LocationCreateEntity()
GameInventory::LocationCreateEntity (notnull InventoryLocation inv_loc, string type, int iSetupFlags, int iRotation) static protected
creates new item directly at location
Parameters
[in] type item type to be placed in inventory
Returns
created entity, null otherwise
Referenced by ReplaceItemWithNewLambdaBase::CreateNewEntity(), SpawnEntity(), InventoryItem::SplitIntoStackMaxToInventoryLocationEx(), InventoryItem::SplitItemToInventoryLocation(), ThrowEntityFromInventory(), and ActionUncoverHeadBase::UncoverHead().
LocationCreateLocalEntity()
GameInventory::LocationCreateLocalEntity (notnull InventoryLocation inv_loc, string type, int iSetupFlags, int iRotation) static protected
creates new local item directly at location @NOTE: the item is created localy, i.e. it's not registered to network
Parameters
[in] type item type to be placed in inventory
Returns
created entity, null otherwise
Referenced by ReplaceItemWithNewLambdaBase::CreateNewEntity().
LocationGetEntity()
static proto native EntityAI GameInventory::LocationGetEntity (notnull InventoryLocation inv_loc) static protected
LocationMoveEntity()
GameInventory::LocationMoveEntity (notnull InventoryLocation src_loc, notnull InventoryLocation dst_loc) static protected
removes item from current inventory location and adds it to destination
Returns
true if success, false otherwise
LocationRemoveEntity()
GameInventory::LocationRemoveEntity (notnull InventoryLocation inv_loc) static protected
removes item from inventory location
Returns
true if success, false otherwise
Referenced by ReplaceItemWithNewLambdaBase::RemoveOldItemFromLocation().
LocationSwap()
GameInventory::LocationSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2) static protected
swaps two entities
Returns
true if success, false otherwise
Referenced by HandActionBase::Action(), HandStartAction::OnEntry(), and OnServerInventoryCommandStatic().
LocationSyncMoveEntity()
GameInventory::LocationSyncMoveEntity (notnull InventoryLocation src_loc, notnull InventoryLocation dst_loc) static protected
synchronously removes item from current inventory location and adds it to destination no anims involved
Returns
true if success, false otherwise
Referenced by HandActionBase::Action(), HandleDropMagazine(), WeaponStateBase::OnAbort(), OnAbort(), HandStateBase::OnEntry(), HandStartAction::OnEntry(), WeaponStateBase::OnEntry(), WeaponStateBase::OnExit(), OnServerInventoryCommandStatic(), and TakeToDst().
LocationTestAddEntity()
GameInventory::LocationTestAddEntity (notnull InventoryLocation inv_loc, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check, bool do_script_load_check) static protected
test if the entity contained in inv_loc.m_item can be added to ground/attachment/cargo/hands/...
Returns
true if can be added, false otherwise
Referenced by HandGuardBase::GuardCondition().
LockInventory()
proto native void GameInventory::LockInventory (int lockType) protected
LockInventoryWithKey()
proto native void GameInventory::LockInventoryWithKey (notnull EntityAI key) protected
MakeDstForSwap()
static bool GameInventory::MakeDstForSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, out InventoryLocation dst1, out InventoryLocation dst2) inline static protected
helper function for swap
Definition at line 1147 of file Inventory.c.
  {
    if (dst1 == null)
      dst1 = new InventoryLocation();
    dst1.Copy(src1);
    dst1.CopyLocationFrom(src2, false);
    dst1.SetFlip(src1.GetItem().GetInventory().GetFlipCargo()); // update flip flag from inventory item
    if (dst2 == null)
      dst2 = new InventoryLocation();
    dst2.Copy(src2);
    dst2.CopyLocationFrom(src1, false);
    dst2.SetFlip(src2.GetItem().GetInventory().GetFlipCargo()); // update flip flag from inventory item
    return true;
  }
Referenced by MakeSrcAndDstForSwap().
MakeSrcAndDstForForceSwap()
static bool GameInventory::MakeSrcAndDstForForceSwap (notnull EntityAI item1, notnull EntityAI item2, out InventoryLocation src1, out InventoryLocation src2, out InventoryLocation dst1, notnull InventoryLocation dst2) inline static protected
helper function for ForceSwap
Definition at line 1178 of file Inventory.c.
  {
    if (src1 == null)
      src1 = new InventoryLocation();
    if (src2 == null)
      src2 = new InventoryLocation();
    if (item1.GetInventory().GetCurrentInventoryLocation(src1) && item2.GetInventory().GetCurrentInventoryLocation(src2))
    {
      // src1 -> dst_of(src2)
      if (dst1 == null)
        dst1 = new InventoryLocation();
      dst1.Copy(src1);
      dst1.CopyLocationFrom(src2, false);
      dst1.SetFlip(dst1.GetItem().GetInventory().GetFlipCargo());
      // src2 -> dst2 from user
      return true;
    }
    return false;
  }
Referenced by HumanInventory::ForceSwapEntities(), and ForceSwapEntities().
MakeSrcAndDstForSwap()
static bool GameInventory::MakeSrcAndDstForSwap (notnull EntityAI item1, notnull EntityAI item2, out InventoryLocation src1, out InventoryLocation src2, out InventoryLocation dst1, out InventoryLocation dst2) inline static protected
helper function for swap
Definition at line 1166 of file Inventory.c.
  {
    if (src1 == null)
      src1 = new InventoryLocation();
    if (src2 == null)
      src2 = new InventoryLocation();
    if (item1.GetInventory().GetCurrentInventoryLocation(src1) && item2.GetInventory().GetCurrentInventoryLocation(src2))
      return MakeDstForSwap(src1, src2, dst1, dst2);
    return false;
  }
References MakeDstForSwap().
Referenced by HandleSwapEntities(), HumanInventory::SwapEntities(), and SwapEntities().
OnAfterStoreLoad()
void GameInventory::OnAfterStoreLoad () protected
OnInputUserDataProcess()
bool GameInventory::OnInputUserDataProcess (ParamsReadContext ctx) protected
synchronization
OnInventoryFailure()
void GameInventory::OnInventoryFailure (InventoryCommandType type, InventoryValidationReason reason, InventoryLocation src, InventoryLocation dst) protected
Referenced by DropEntity().
OnInventoryJunctureFailureFromServer()
void GameInventory::OnInventoryJunctureFailureFromServer (ParamsReadContext ctx) protected
OnInventoryJunctureFromServer()
bool GameInventory::OnInventoryJunctureFromServer (ParamsReadContext ctx) protected
OnInventoryJunctureRepairFromServer()
bool GameInventory::OnInventoryJunctureRepairFromServer (ParamsReadContext ctx) protected
OnServerInventoryCommand()
void GameInventory::OnServerInventoryCommand (ParamsReadContext ctx) protected
OnServerInventoryCommandStatic()
static void GameInventory::OnServerInventoryCommandStatic (ParamsReadContext ctx) inline static protected
Definition at line 451 of file Inventory.c.
  {
    int tmp = -1;
    ctx.Read(tmp);
    int type = -1;
    if (!ctx.Read(type))
      return;
    switch (type)
    {
    case InventoryCommandType.SYNC_MOVE:
    {
      InventoryLocation src = new InventoryLocation();
      InventoryLocation dst = new InventoryLocation();
      src.ReadFromContext(ctx);
      dst.ReadFromContext(ctx);
      if (LogManager.IsSyncLogEnable()) syncDebugPrint("[syncinv] t=" + GetGame().GetTime() + "ms ServerInventoryCommand cmd=" + typename.EnumToString(InventoryCommandType, type) + " src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
      if (!src.GetItem() || !dst.GetItem())
      {
        LogError("[syncinv] ServerInventoryCommand (cmd=SYNC_MOVE) dropped, item not in bubble");
        break; // not in bubble
      }
      LocationSyncMoveEntity(src, dst);
      break;
    }
    case InventoryCommandType.HAND_EVENT:
    {
      HandEventBase e = HandEventBase.CreateHandEventFromContext(ctx);
      if (LogManager.IsSyncLogEnable()) syncDebugPrint("[syncinv] t=" + GetGame().GetTime() + "ms ServerInventoryCommand cmd=" + typename.EnumToString(InventoryCommandType, type) + " event=" + e.DumpToString());
      if (!e.GetSrcEntity())
      {
        Error("[syncinv] ServerInventoryCommand (cmd=HAND_EVENT) dropped, item not in bubble");
        break; // not in bubble
      }
      e.m_Player.GetHumanInventory().ProcessHandEvent(e);
      break;
    }
    case InventoryCommandType.FORCESWAP:
    case InventoryCommandType.SWAP:
    {
      InventoryLocation src1 = new InventoryLocation();
      InventoryLocation src2 = new InventoryLocation();
      InventoryLocation dst1 = new InventoryLocation();
      InventoryLocation dst2 = new InventoryLocation();
      src1.ReadFromContext(ctx);
      src2.ReadFromContext(ctx);
      dst1.ReadFromContext(ctx);
      dst2.ReadFromContext(ctx);
      if (src1.IsValid() && src2.IsValid() && dst1.IsValid() && dst2.IsValid())
      {
        if (LogManager.IsSyncLogEnable()) syncDebugPrint("[syncinv] t=" + GetGame().GetTime() + "ms ServerInventoryCommand Swap src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) + " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " dst2=" + InventoryLocation.DumpToStringNullSafe(dst2));
        LocationSwap(src1, src2, dst1, dst2);
      }
      else
        Error("ServerInventoryCommand - cannot swap, invalid location input: src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) + " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " dst2=" + InventoryLocation.DumpToStringNullSafe(dst2));
      break;
    }
    }
  }
References InventoryLocation::DumpToStringNullSafe(), Error(), GetGame(), GetTime(), LogManager::IsSyncLogEnable(), LocationSwap(), LocationSyncMoveEntity(), LogError(), and syncDebugPrint().
OnStoreLoad()
bool GameInventory::OnStoreLoad (ParamsReadContext ctx, int version) inline protected
db load hooks
Definition at line 810 of file Inventory.c.
  {
    return true;
  }
OnStoreSave()
void GameInventory::OnStoreSave (ParamsWriteContext ctx) protected
db store hook
PrepareDropEntityPos()
GameInventory::PrepareDropEntityPos (EntityAI owner, notnull EntityAI item, out vector mat[4], bool useValuesInMatrix = false, int conflictCheckDepth = -1) static protected
Finds a transformation for the item to be dropped to If the initial transforation overlaps with another conflicting entity (i.e. car) then the transform will be snapped to the nearest outer edge. If no valid snapping transformation could be found, then the output from 'PlaceOnSurface' is used.
Parameters
useValuesInMatrix Is ignored if transformation overlaps with possible conflicting entity. If no valid transform is found and this is false then the transform at the owner is used for 'PlaceOnSurface'
conflictCheckDepth If -1 then no conflict depth check is performed, if 0 then it only checks to see if it conflicts but doesn't perform snapping
Returns
true if valid transformation found near owner
Referenced by DropEquipAndDestroyRootLambda::CopyOldPropertiesToNew(), HandleDropMagazine(), ManBase::PredictiveDropEntity(), SetGroundPosByOwner(), and SetGroundPosByTransform().
ReplaceItemWithNew()
bool GameInventory::ReplaceItemWithNew (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline protected
Definition at line 1318 of file Inventory.c.
  {
    InventoryLocation src = new InventoryLocation();
    if (lambda.m_OldItem.GetInventory().GetCurrentInventoryLocation(src))
    {
      if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::ReplaceItemWithNew executing lambda=" + lambda + "on old_item=" + lambda.m_OldItem);
      lambda.Execute();
      return true;
    }
    Error("[inv] I::ReplaceItemWithNew - no inventory location");
    return false;
  }
References Error(), inventoryDebugPrint(), and LogManager::IsInventoryMoveLogEnable().
ResetFlipCargo()
proto native void GameInventory::ResetFlipCargo () protected
ServerHandEvent()
GameInventory::ServerHandEvent (notnull Man player, notnull EntityAI item, ParamsWriteContext ctx) static protected
hand event to clients
Returns
true if success, false otherwise
Referenced by InventoryInputUserData::SendServerHandEventViaInventoryCommand().
ServerLocationMoveEntity()
GameInventory::ServerLocationMoveEntity (notnull EntityAI item, ParamsWriteContext ctx) static protected
removes item from current inventory location and adds it to destination + sync via inventory command
Returns
true if success, false otherwise
ServerLocationSwap()
GameInventory::ServerLocationSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, ParamsWriteContext ctx) static protected
swaps two entities
Returns
true if success, false otherwise
Referenced by InventoryInputUserData::SendServerSwap().
ServerLocationSyncMoveEntity()
GameInventory::ServerLocationSyncMoveEntity (Man player, notnull EntityAI item, ParamsWriteContext ctx) static protected
synchronously removes item from current inventory location and adds it to destination + sync via inventory command no anims involved
Returns
true if success, false otherwise
Referenced by InventoryInputUserData::SendServerMove().
SetFlipCargo()
proto native void GameInventory::SetFlipCargo (bool flip) protected
SetGroundPosByOwner()
static bool GameInventory::SetGroundPosByOwner (EntityAI owner, notnull EntityAI item, out InventoryLocation ground) inline static protected
Definition at line 1212 of file Inventory.c.
  {
    vector m4[4];
    Math3D.MatrixIdentity4(m4);
    bool success = GameInventory.PrepareDropEntityPos(owner, item, m4, false, GameConstants.INVENTORY_ENTITY_DROP_OVERLAP_DEPTH);
    ground.SetGround(item, m4);
    return success;
  }
References GameConstants::INVENTORY_ENTITY_DROP_OVERLAP_DEPTH, Math3D::MatrixIdentity4(), and PrepareDropEntityPos().
Referenced by HandEventRemove::CanPerformEventEx(), HandEventRemove::CheckRequestEx(), DropEntity(), OnEntry(), ActionUnpackGift::OnFinishProgressServer(), and StaticConstructionMethods::SpawnConstructionMaterialPiles().
SetGroundPosByOwnerBounds()
static void GameInventory::SetGroundPosByOwnerBounds (EntityAI owner, notnull EntityAI item, out InventoryLocation ground, vector halfExtents, float angle, float cosAngle, float sinAngle) inline static protected
Definition at line 1264 of file Inventory.c.
  {
    vector m4[4];
    owner.GetTransform(m4);
    vector randomPos = Vector(Math.RandomFloat(-halfExtents[0], halfExtents[0]), 0, Math.RandomFloat(-halfExtents[2], halfExtents[2]));
    randomPos = vector.RotateAroundZero(randomPos, vector.Up, cosAngle, sinAngle);
    float dist = randomPos[0] * m4[1][0] + randomPos[1] * m4[1][1] + randomPos[2] * m4[1][2];
    m4[3][0] = m4[3][0] + randomPos[0];
    m4[3][1] = m4[3][1] - dist + halfExtents[1];
    m4[3][2] = m4[3][2] + randomPos[2];
    item.PlaceOnSurfaceRotated(m4, Vector(m4[3][0], m4[3][1], m4[3][2]));
    ground.SetGround(item, m4);
  }
References Math::RandomFloat(), vector::RotateAroundZero(), vector::Up, and Vector().
Referenced by DropEntityInBounds().
SetGroundPosByTransform()
static bool GameInventory::SetGroundPosByTransform (EntityAI owner, notnull EntityAI item, out InventoryLocation ground, vector transform[4]) inline static protected
Definition at line 1241 of file Inventory.c.
  {
    bool success = GameInventory.PrepareDropEntityPos(owner, item, transform, true, GameConstants.INVENTORY_ENTITY_DROP_OVERLAP_DEPTH);
    ground.SetGround(item, transform);
    return success;
  }
References GameConstants::INVENTORY_ENTITY_DROP_OVERLAP_DEPTH, and PrepareDropEntityPos().
Referenced by DropEntityWithTransform().
SetSlotLock()
proto native bool GameInventory::SetSlotLock (int slot, bool locked) protected
SwapEntities()
bool GameInventory::SwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2) inline protected
Definition at line 1202 of file Inventory.c.
  {
    return false;
  }
TakeEntityAsAttachment()
bool GameInventory::TakeEntityAsAttachment (InventoryMode mode, notnull EntityAI item) inline protected
Definition at line 1134 of file Inventory.c.
  {
    if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::Take2Att(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
    return TakeEntityToInventory(mode, FindInventoryLocationType.ATTACHMENT, item);
  }
References inventoryDebugPrint(), LogManager::IsInventoryMoveLogEnable(), and TakeEntityToInventory().
Referenced by EntityAI::TakeEntityAsAttachmentImpl().
TakeEntityAsAttachmentEx()
bool GameInventory::TakeEntityAsAttachmentEx (InventoryMode mode, notnull EntityAI item, int slot) inline protected
Definition at line 1103 of file Inventory.c.
  {
    if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::Take2AttEx(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + " slot=" + slot);
    return TakeEntityAsTargetAttachmentEx(mode, GetInventoryOwner(), item, slot);
  }
References GetInventoryOwner(), inventoryDebugPrint(), LogManager::IsInventoryMoveLogEnable(), and TakeEntityAsTargetAttachmentEx().
TakeEntityAsTargetAttachment()
bool GameInventory::TakeEntityAsTargetAttachment (InventoryMode mode, notnull EntityAI target, notnull EntityAI item) inline protected
Definition at line 1140 of file Inventory.c.
  {
    if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::Take2AttEx(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
    return TakeEntityToTargetInventory(mode, target, FindInventoryLocationType.ATTACHMENT, item);
  }
References inventoryDebugPrint(), LogManager::IsInventoryMoveLogEnable(), and TakeEntityToTargetInventory().
TakeEntityAsTargetAttachmentEx()
bool GameInventory::TakeEntityAsTargetAttachmentEx (InventoryMode mode, notnull EntityAI target, notnull EntityAI item, int slot) inline protected
put item as attachment of target
Definition at line 1110 of file Inventory.c.
  {
    if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::Take2TargetAttEx(" + typename.EnumToString(InventoryMode, mode) + ") as ATT of target=" + target + " item=" + item + " slot=" + slot);
    InventoryLocation src = new InventoryLocation();
    if (item.GetInventory().GetCurrentInventoryLocation(src))
    {
      EntityAI att = target.GetInventory().FindAttachment(slot);
      if (att)
      {
        att.CombineItemsClient(item, true);
        return true;
      }
      else
      {
        InventoryLocation dst = new InventoryLocation();
        dst.SetAttachment(target, item, slot);
        return TakeToDst(mode, src, dst);
      }
    }
    Error("[inv] I::Take2AttEx(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + " Error - src has no inventory location");
    return false;
  }
References Error(), inventoryDebugPrint(), LogManager::IsInventoryMoveLogEnable(), and TakeToDst().
Referenced by TakeEntityAsAttachmentEx().
TakeEntityToCargo()
GameInventory::TakeEntityToCargo (InventoryMode mode, notnull EntityAI item) inline protected
moves item to cargo of this intentory
Parameters
[in] mode inventory mode
[in] item item to be put in this inventory as cargo
Definition at line 1054 of file Inventory.c.
  {
    if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::Take2Cgo(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
    return TakeEntityToInventory(mode, FindInventoryLocationType.CARGO, item);
  }
References inventoryDebugPrint(), LogManager::IsInventoryMoveLogEnable(), and TakeEntityToInventory().
Referenced by EntityAI::TakeEntityToCargoImpl().
TakeEntityToCargoEx()
GameInventory::TakeEntityToCargoEx (InventoryMode mode, notnull EntityAI item, int idx, int row, int col) inline protected
moves item on specific cargo location
Parameters
[in] mode inventory mode
[in] item item to be put in this inventory as cargo
Definition at line 1072 of file Inventory.c.
  {
    if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::Take2Cgo(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + " row=" + row + " col=" + col);
    InventoryLocation src = new InventoryLocation();
    if (item.GetInventory().GetCurrentInventoryLocation(src))
    {
      InventoryLocation dst = new InventoryLocation();
      dst.SetCargo(GetInventoryOwner(), item, idx, row, col, item.GetInventory().GetFlipCargo());
      return TakeToDst(mode, src, dst);
    }
    Error("[inv] I::Take2Cgo(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + " row=" + row + " col=" + col + " Error - src has no inventory location");
    return false;
  }
References Error(), GetInventoryOwner(), inventoryDebugPrint(), LogManager::IsInventoryMoveLogEnable(), and TakeToDst().
TakeEntityToInventory()
GameInventory::TakeEntityToInventory (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item) inline protected
Put item anywhere into this entity (as attachment or into cargo, recursively)
Parameters
[in] mode inventory mode
[in] flags preferred location,
See also
FindInventoryLocationType
Parameters
[in] item item to be taken in inventory
Returns
true on success
@NOTE: Predictive.* / Local.* functions: a) 'Predictive' means that the operation uses Client-Side Prediction, i.e. the action runs the same code on both, client AND server.
b) 'Local' operation executes from where it is run, i.e. the operation from client is NOT sent to server, and only client performs the inventory operation (TakeEntityTo.*) this behaviour is necessary when inventory operations are ALREADY synchronized by another means, like Actions. For example
See also
ActionTakeItemToHands that performs OnCompleteServer and OnCompleteClient with synchronization set to false in order to avoid duplicate synchronization.
Definition at line 986 of file Inventory.c.
  {
    if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::Take2Inv(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
    InventoryLocation src = new InventoryLocation();
    if (item.GetInventory().GetCurrentInventoryLocation(src))
    {
      InventoryLocation dst = new InventoryLocation();
      if (FindFreeLocationFor(item, flags, dst))
        return TakeToDst(mode, src, dst);
      if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::Take2Inv(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + " Warning - no room for item");
      return false;
    }
    Error("[inv] I::Take2Inv(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + " Error - src has no inventory location");
    return false;
  }
References Error(), FindFreeLocationFor(), inventoryDebugPrint(), LogManager::IsInventoryMoveLogEnable(), and TakeToDst().
Referenced by TakeEntityAsAttachment(), and TakeEntityToCargo().
TakeEntityToTargetCargo()
bool GameInventory::TakeEntityToTargetCargo (InventoryMode mode, notnull EntityAI target, notnull EntityAI item) inline protected
Put item into into cargo of another entity.
Definition at line 1061 of file Inventory.c.
  {
    if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::Take2TargetCgo(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + "to cargo of target=" + target);
    return TakeEntityToTargetInventory(mode, target, FindInventoryLocationType.CARGO, item);
  }
References inventoryDebugPrint(), LogManager::IsInventoryMoveLogEnable(), and TakeEntityToTargetInventory().
TakeEntityToTargetCargoEx()
bool GameInventory::TakeEntityToTargetCargoEx (InventoryMode mode, notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline protected
Put item into into cargo on specific cargo location of another entity.
Definition at line 1088 of file Inventory.c.
  {
    if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::Take2TargetCgoEx(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + "to cargo of target=" + cargo.GetCargoOwner() + " row=" + row + " col=" + col);
    InventoryLocation src = new InventoryLocation();
    if (item.GetInventory().GetCurrentInventoryLocation(src))
    {
      InventoryLocation dst = new InventoryLocation();
      dst.SetCargoAuto(cargo, item, row, col, item.GetInventory().GetFlipCargo());
      return TakeToDst(mode, src, dst);
    }
    Error("[inv] I::Take2TargetCgoEx(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + "to cargo of target=" + cargo.GetCargoOwner() + " row=" + row + " col=" + col);
    return false;
  }
References Error(), inventoryDebugPrint(), LogManager::IsInventoryMoveLogEnable(), and TakeToDst().
TakeEntityToTargetInventory()
bool GameInventory::TakeEntityToTargetInventory (InventoryMode mode, notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline protected
helper that finds location first, then moves the entity into it
Definition at line 1005 of file Inventory.c.
  {
    if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::Take2Target(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
    InventoryLocation src = new InventoryLocation();
    if (item.GetInventory().GetCurrentInventoryLocation(src))
    {
      InventoryLocation dst = new InventoryLocation();
      if (target.GetInventory().FindFreeLocationFor(item, flags, dst))
        return TakeToDst(mode, src, dst);
      if (LogManager.IsInventoryMoveLogEnable()) inventoryDebugPrint("[inv] I::Take2Target(" + typename.EnumToString(InventoryMode, mode) + ") target=" + target + " item=" + item + " Warning - no room for item in target");
      return false;
    }
    Error("[inv] I::Take2Target(" + typename.EnumToString(InventoryMode, mode) + ") target=" + target + " item=" + item + " Error - src has no inventory location");
    return false;
  }
References Error(), inventoryDebugPrint(), LogManager::IsInventoryMoveLogEnable(), and TakeToDst().
Referenced by TakeEntityAsTargetAttachment(), and TakeEntityToTargetCargo().
TakeToDst()
GameInventory::TakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst) inline protected
move src to dst
Parameters
[in] mode inventory mode
[in] src source location of the item
[in] dst destination location of the item
Definition at line 1030 of file Inventory.c.
  {
    bool ret;
    switch (mode)
    {
    case InventoryMode.SERVER:
      ret = LocationSyncMoveEntity(src, dst);
      if (ret && dst.IsValid())
        InventoryInputUserData.SendServerMove(null, InventoryCommandType.SYNC_MOVE, src, dst);
      return ret;
    case InventoryMode.LOCAL:
      ret = LocationSyncMoveEntity(src, dst);
      return ret;
    default:
      return false;
    }
    return false;
  }
References LocationSyncMoveEntity(), and InventoryInputUserData::SendServerMove().
Referenced by DropEntity(), DropEntityInBounds(), DropEntityWithTransform(), TakeEntityAsTargetAttachmentEx(), TakeEntityToCargoEx(), TakeEntityToInventory(), TakeEntityToTargetCargoEx(), and TakeEntityToTargetInventory().
TestAddEntityInCargoEx()
proto native bool GameInventory::TestAddEntityInCargoEx (notnull EntityAI e, int idx, int row, int col, bool flip, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check, bool do_script_load_check) protected
TestAddEntityInCargoExLoc()
proto native bool GameInventory::TestAddEntityInCargoExLoc (notnull InventoryLocation loc, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check, bool do_script_load_check) protected
TestDropEntityPos()
static proto native bool GameInventory::TestDropEntityPos (EntityAI owner, notnull EntityAI item, out vector mat[4], bool useValuesInMatrix = false, int conflictCheckDepth = -1) static protected
UnlockInventory()
proto native void GameInventory::UnlockInventory (int lockType) protected
UnlockInventoryWithKey()
proto native void GameInventory::UnlockInventoryWithKey (notnull EntityAI key) protected
Member Data Documentation
c_InventoryReservationTimeoutMS
const int GameInventory::c_InventoryReservationTimeoutMS = 5000 protected
reservations
Definition at line 687 of file Inventory.c.
Referenced by InventoryReservation(), ActionRemoveSeed::InventoryReservation(), ActionTakeArrow::InventoryReservation(), ActionTakeArrowToHands::InventoryReservation(), ActionTakeHybridAttachment::InventoryReservation(), ActionTakeItem::InventoryReservation(), FirearmActionAttachMagazine::InventoryReservation(), FirearmActionAttachMagazineQuick::InventoryReservation(), WeaponManager::InventoryReservation(), SendServerHandEventViaJuncture(), SetEmoteLockState(), TakeToDst(), TryAcquireInventoryJunctureFromServer(), and TryAcquireTwoInventoryJuncturesFromServer().
c_InventoryReservationTimeoutShortMS
const int GameInventory::c_InventoryReservationTimeoutShortMS = 3000 protected
Definition at line 688 of file Inventory.c.
Referenced by InventoryItem::CombineItemsClient(), HandGuardBase::GuardCondition(), HandleForceSwapEntities(), HandleSwapEntities(), HandleTakeToDst(), HandStateBase::OnEntry(), InventoryItem::OnRightClick(), ReserveInventory(), HandEventBase::ReserveInventory(), ReserveInventory(), DeferredSwapEntities::ReserveInventory(), and ValidateSwap().
c_MaxItemDistanceRadius
const float GameInventory::c_MaxItemDistanceRadius = 2.5 protected
anti-cheats
Definition at line 788 of file Inventory.c.
Referenced by HandEventBase::CheckRequest(), HandEventSwap::CheckRequest(), HandEventBase::CheckRequestSrc(), PlayerCheckSwapItemsRequest(), ValidateDestroy(), ValidateSwap(), and ValidateSyncMove().
m_inventory_check_context
int GameInventory::m_inventory_check_context = InventoryCheckContext.DEFAULT static protected
Definition at line 80 of file Inventory.c.
Referenced by GetInventoryCheckContext(), and LocationCanMoveEntitySyncCheck().
The documentation for this class was generated from the following file:
scripts/3_Game/Systems/Inventory/Inventory.c