DayZ: ItemManager Class Reference
ItemManager Class Reference
Protected Member Functions
void ItemManager (Widget root)
void SetItemMicromanagmentMode (bool item_micromanagment_mode)
bool IsMicromanagmentMode ()
HandsPreview GetHandsPreview ()
void SetHandsPreview (HandsPreview hansd_preview)
EntityAI GetSelectedItem ()
Container GetSelectedContainer ()
Widget GetSelectedWidget ()
SlotsIcon GetSelectedIcon ()
void SetSelectedItem (EntityAI selected_item, Container selected_container, Widget selected_widget, SlotsIcon selected_icon)
void SetSelectedItemEx (EntityAI selected_item, Container selected_container, LayoutHolder selected_icon)
void ClearDefaultOpenStates ()
void ClearDefaultHeaderOpenStates ()
void SetDefaultOpenState (string type, bool is_opened)
void SetDefaultHeaderOpenState (string type, bool is_opened)
void SetDefaultOpenStateHands (bool is_opened)
bool GetDefaultOpenStateHands ()
void SerializeDefaultHeaderOpenStates ()
void DeserializeDefaultHeaderOpenStates ()
void SerializeDefaultOpenStates ()
void DeserializeDefaultOpenStates ()
bool GetDefaultOpenState (string type)
bool GetDefaultHeaderOpenState (string type)
void HideDropzones ()
void ShowSourceDropzone (EntityAI item)
Widget GetLeftDropzone ()
Widget GetRightDropzone ()
Widget GetCenterDropzone ()
EntityAI GetHoveredItem ()
void SetDraggedItem (EntityAI dragged_item)
EntityAI GetDraggedItem ()
void SetDraggedIcon (Icon dragged_icon)
Icon GetDraggedIcon ()
void SetIsDragging (bool is_dragging)
bool IsDragging ()
void HideTooltip ()
void HideTooltipSlot ()
void SetTemperature (EntityAI item, Widget item_w)
void SetIconTemperature (EntityAI item, Widget item_w)
void PrepareTooltip (EntityAI item, int x=0, int y=0)
void PrepareSlotsTooltip (string name, string desc, int x=0, int y=0)
position is currentlycalculated from the owning 'm_TooltipSourceWidget' directly
void CalculateTooltipSlotPosition (int x=0, int y=0)
void UpdateTooltipSlotPosition ()
void SetTooltipWidget (Widget w)
bool EvaluateContainerDragabilityDefault (EntityAI entity)
void SetWidgetDraggable (Widget w, bool draggable)
void ShowTooltip ()
void ShowTooltipSlot ()
Static Protected Member Functions
static ItemManager GetInstance ()
static int GetItemHealthColor (int pHealthLevel)
static int GetItemHealthColor (EntityAI item, string zone="")
static int ColorFromFloat (float fraction)
static int GetChosenCombinationFlag (EntityAI selectedEntity, EntityAI targetEntity, int relevantFlags, out InventoryLocation dst=null)
static int GetCombinationFlags (EntityAI entity1, EntityAI entity2)
static int GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2)
Protected Attributes
bool m_IsDragging
EntityAI m_HoveredItem
bool m_SlotInfoShown
EntityAI m_DraggedItem
Icon m_DraggedIcon
ref Widget m_TooltipWidget
ref Widget m_TooltipSlotWidget
ref Widget m_TooltipCategoryWidget
ItemPreviewWidget m_ItemPreviewWidget
Widget m_RootWidget
ref map< string, bool > m_DefautOpenStates
ref map< string, bool > m_DefautHeaderOpenStates
int m_HandsDefaultOpenState
ref Timer m_ToolTipTimer
ref Timer m_TooltipSlotTimer
EntityAI m_SelectedItem
Container m_SelectedContainer
Widget m_SelectedWidget
SlotsIcon m_SelectedIcon
LayoutHolder m_SelectedBaseIcon
HandsPreview m_HandsPreview
bool m_ItemMicromanagmentMode
Widget m_LeftDropzone
Widget m_CenterDropzone
Widget m_RightDropzone
int m_TooltipPosX
int m_TooltipPosY
Widget m_TooltipSourceWidget
const float TOOLTIP_DELAY = 0.25
Static Private Attributes
static ref ItemManager m_Instance
Detailed Description
Definition at line 1 of file ItemManager.c.
Constructor & Destructor Documentation
ItemManager()
void ItemManager::ItemManager (Widget root) inline protected
Definition at line 44 of file ItemManager.c.
  {
    m_Instance = this;
    m_RootWidget = root;
    m_DefautOpenStates = new map<string, bool>;
    m_DefautHeaderOpenStates = new map<string, bool>;
    m_SlotInfoShown = false;
#ifdef PLATFORM_CONSOLE
    m_TooltipWidget = GetGame().GetWorkspace().CreateWidgets("gui/layouts/inventory_new/day_z_inventory_new_tooltip_xbox.layout", root);
    m_TooltipSlotWidget = GetGame().GetWorkspace().CreateWidgets("gui/layouts/inventory_new/day_z_inventory_new_tooltip_slot_xbox.layout", root);
#else
    m_TooltipWidget = GetGame().GetWorkspace().CreateWidgets("gui/layouts/inventory_new/day_z_inventory_new_tooltip.layout", root);
    m_TooltipSlotWidget = GetGame().GetWorkspace().CreateWidgets("gui/layouts/inventory_new/day_z_inventory_new_tooltip_slot.layout", root);
#endif
    m_TooltipWidget.Show(false);
    m_TooltipSlotWidget.Show(false);
  }
References GetGame(), m_DefautHeaderOpenStates, m_DefautOpenStates, m_Instance, m_RootWidget, m_SlotInfoShown, m_TooltipSlotWidget, and m_TooltipWidget.
Member Function Documentation
CalculateTooltipSlotPosition()
void ItemManager::CalculateTooltipSlotPosition (int x = 0, int y = 0) inline protected
Definition at line 562 of file ItemManager.c.
  {
    int screen_w, screen_h;
    float w, h;
    GetScreenSize(screen_w, screen_h);
    //m_TooltipSlotWidget.GetScreenSize(w,h);
    m_TooltipSlotWidget.GetSize(w, h);
    int slot_normal_w = SlotsIcon.GetNormalWidth();
    int slot_normal_h = SlotsIcon.GetNormalHeight();
    //minimal edge distance adjustments..
    screen_w -= 10;
    screen_h -= 10;
#ifndef PLATFORM_CONSOLE
    x += 5;
    y += slot_normal_h + 5;
#else
    x += 5;
    y += 15;
#endif
    Widget scrollerWidget = m_TooltipSourceWidget.GetParent();
    while (scrollerWidget)
    {
      if (ScrollWidget.Cast(scrollerWidget))
        break;
      else
        scrollerWidget = scrollerWidget.GetParent();
    }
    int rightEdge = x + w;
    if (rightEdge > screen_w)
      x = screen_w - w;
    int bottomEdge = y + h;
    if (scrollerWidget)
    {
      float scrollerX, scrollerY, scrollerSizeX, scrollerSizeY;
      scrollerWidget.GetScreenPos(scrollerX, scrollerY);
      scrollerWidget.GetScreenSize(scrollerSizeX, scrollerSizeY);
      int scroller_bottom = scrollerY + scrollerSizeY;
      if (bottomEdge > scroller_bottom)
      {
        y = scroller_bottom - slot_normal_h;
        bottomEdge = y + h;
      }
    }
    /*else
      {
      ErrorEx("No scroller widget! | m_TooltipSourceWidget: " + m_TooltipSourceWidget);
      }*/
    if (bottomEdge > screen_h) //should mostly never proc now
      y = screen_h - h;
    m_TooltipPosX = x;
    m_TooltipPosY = y;
  }
References SlotsIcon::GetNormalHeight(), SlotsIcon::GetNormalWidth(), GetScreenSize(), m_TooltipPosX, m_TooltipPosY, m_TooltipSlotWidget, m_TooltipSourceWidget, x, and y.
Referenced by UpdateTooltipSlotPosition().
ClearDefaultHeaderOpenStates()
void ItemManager::ClearDefaultHeaderOpenStates () inline protected
Definition at line 156 of file ItemManager.c.
  {
    m_DefautHeaderOpenStates.Clear();
  }
References m_DefautHeaderOpenStates.
Referenced by DeserializeDefaultHeaderOpenStates().
ClearDefaultOpenStates()
void ItemManager::ClearDefaultOpenStates () inline protected
Definition at line 151 of file ItemManager.c.
  {
    m_DefautOpenStates.Clear();
  }
References m_DefautOpenStates.
Referenced by DeserializeDefaultOpenStates().
ColorFromFloat()
static int ItemManager::ColorFromFloat (float fraction) inline static protected
Definition at line 427 of file ItemManager.c.
  {
    if (fraction > 1 || fraction < 0)
      return 0x00FFFFFF;
    else if (fraction > 0.80)
      return Colors.COLOR_PRISTINE;
    else if (fraction > 0.6)
      return Colors.COLOR_WORN;
    else if (fraction > 0.4)
      return Colors.COLOR_DAMAGED;
    else if (fraction > 0.2)
      return Colors.COLOR_BADLY_DAMAGED;
    else
      return Colors.COLOR_RUINED;
  }
References Colors::COLOR_BADLY_DAMAGED, Colors::COLOR_DAMAGED, Colors::COLOR_PRISTINE, Colors::COLOR_RUINED, and Colors::COLOR_WORN.
DeserializeDefaultHeaderOpenStates()
void ItemManager::DeserializeDefaultHeaderOpenStates () inline protected
Definition at line 202 of file ItemManager.c.
  {
    ClearDefaultHeaderOpenStates();
    TStringArray serialized_types = new TStringArray;
    GetGame().GetProfileStringList("defaultHeaderOpenStates", serialized_types);
    for (int i = 0; i < serialized_types.Count(); i++)
    {
      TStringArray strs = new TStringArray;
      serialized_types.Get(i).Split(",", strs);
      bool is_opened = strs.Get(1).ToInt();
      SetDefaultHeaderOpenState(strs.Get(0), is_opened);
    }
  }
References ClearDefaultHeaderOpenStates(), GetGame(), and SetDefaultHeaderOpenState().
DeserializeDefaultOpenStates()
void ItemManager::DeserializeDefaultOpenStates () inline protected
Definition at line 233 of file ItemManager.c.
  {
    ClearDefaultOpenStates();
    TStringArray serialized_types = new TStringArray;
    GetGame().GetProfileStringList("defaultOpenStates", serialized_types);
    for (int i = 0; i < serialized_types.Count(); i++)
    {
      TStringArray strs = new TStringArray;
      serialized_types.Get(i).Split(",", strs);
      bool is_opened = strs.Get(1).ToInt();
      SetDefaultOpenState(strs.Get(0), is_opened);
    }
  }
References ClearDefaultOpenStates(), GetGame(), and SetDefaultOpenState().
EvaluateContainerDragabilityDefault()
bool ItemManager::EvaluateContainerDragabilityDefault (EntityAI entity) inline protected
Definition at line 633 of file ItemManager.c.
  {
    if (!ItemBase.Cast(entity))
      return false;
    bool draggable;
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    draggable = !player.GetInventory().HasInventoryReservation(entity, null) && !player.IsItemsToDelete();
    draggable = draggable && entity.CanPutIntoHands(GetGame().GetPlayer());
    draggable = draggable && entity.GetInventory().CanRemoveEntity();
    return draggable;
  }
References GetGame(), and GetPlayer().
GetCenterDropzone()
Widget ItemManager::GetCenterDropzone () inline protected
Definition at line 316 of file ItemManager.c.
  {
    if (!m_CenterDropzone)
      m_CenterDropzone = m_RootWidget.FindAnyWidget("HandsPanel").FindAnyWidget("DropzoneX");
    return m_CenterDropzone;
  }
References m_CenterDropzone, and m_RootWidget.
Referenced by HideDropzones(), and ShowSourceDropzone().
GetChosenCombinationFlag()
static int ItemManager::GetChosenCombinationFlag (EntityAI selectedEntity, EntityAI targetEntity, int relevantFlags, out InventoryLocation dst = null) inline static protected
Definition at line 671 of file ItemManager.c.
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (!selectedEntity || !targetEntity)
      return InventoryCombinationFlags.NONE;
    ItemBase selectedItem = ItemBase.Cast(selectedEntity);
    ItemBase targetItem = ItemBase.Cast(targetEntity);
    //EntityAI itemInHands = m_player.GetHumanInventory().GetEntityInHands();
    ActionManagerClient amc = ActionManagerClient.Cast(player.GetActionManager());
    if (relevantFlags & InventoryCombinationFlags.PERFORM_ACTION)
    {
      if (amc.CanPerformActionFromInventory(targetItem, selectedItem))
        return InventoryCombinationFlags.PERFORM_ACTION;
    }
    if (relevantFlags & InventoryCombinationFlags.SET_ACTION)
    {
      if (amc.CanSetActionFromInventory(targetItem, selectedItem))
        return InventoryCombinationFlags.SET_ACTION;
    }
    if (relevantFlags & InventoryCombinationFlags.COMBINE_QUANTITY2)
    {
      if (targetEntity.CanBeCombined(selectedEntity))
        return InventoryCombinationFlags.COMBINE_QUANTITY2;
    }
    if (relevantFlags & InventoryCombinationFlags.ADD_AS_ATTACHMENT)
    {
      if (targetEntity.GetInventory().CanAddAttachment(selectedEntity))
        return InventoryCombinationFlags.ADD_AS_ATTACHMENT;
    }
    if (relevantFlags & InventoryCombinationFlags.ADD_AS_CARGO)
    {
      if (!targetEntity.GetInventory().HasEntityInInventory(selectedEntity) && targetEntity.GetInventory().CanAddEntityInCargo(selectedEntity, selectedEntity.GetInventory().GetFlipCargo()))
        return InventoryCombinationFlags.ADD_AS_CARGO;
    }
    if (relevantFlags & InventoryCombinationFlags.SWAP_MAGAZINE)
    {
      Magazine mag = Magazine.Cast(targetEntity);
      Weapon_Base wpn = Weapon_Base.Cast(targetEntity.GetHierarchyParent());
      if (wpn && mag)
      {
        if (player.GetWeaponManager().CanSwapMagazine(wpn, Magazine.Cast(selectedEntity)))
          return InventoryCombinationFlags.SWAP_MAGAZINE;
      }
    }
    if (relevantFlags & InventoryCombinationFlags.SWAP)
    {
      if (GameInventory.CanSwapEntitiesEx(selectedEntity, targetEntity))
        return InventoryCombinationFlags.SWAP;
    }
    if (relevantFlags & InventoryCombinationFlags.FSWAP)
    {
      if (GameInventory.CanForceSwapEntitiesEx(selectedEntity, null, targetEntity, dst))
        return InventoryCombinationFlags.FSWAP;
    }
    return InventoryCombinationFlags.NONE;
  }
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, GameInventory::CanForceSwapEntitiesEx(), GameInventory::CanSwapEntitiesEx(), InventoryCombinationFlags::COMBINE_QUANTITY2, InventoryCombinationFlags::FSWAP, GetGame(), GetPlayer(), InventoryCombinationFlags::NONE, InventoryCombinationFlags::PERFORM_ACTION, InventoryCombinationFlags::SET_ACTION, InventoryCombinationFlags::SWAP, and InventoryCombinationFlags::SWAP_MAGAZINE.
Referenced by Icon::Combine(), Icon::DraggingOver(), Icon::DraggingOverCombine(), Icon::DraggingOverSwap(), Icon::DropReceivedFromMain(), and Icon::Swap().
GetCombinationFlags()
static int ItemManager::GetCombinationFlags (EntityAI entity1, EntityAI entity2) inline static protected
Definition at line 740 of file ItemManager.c.
  {
    int flags = 0;
    PlayerBase m_player = PlayerBase.Cast(GetGame().GetPlayer());
    if (!entity1 || !entity2)
      return flags;
    if (entity1.IsInherited(ItemBase) && entity2.IsInherited(ItemBase))
    {
      ItemBase ent1 = ItemBase.Cast(entity1);
      if (ent1.CanBeCombined(ItemBase.Cast(entity2))) flags = flags | InventoryCombinationFlags.COMBINE_QUANTITY2;
    }
    if (entity1.GetInventory().CanAddAttachment(entity2))
    {
      if (!entity1.IsInherited(ZombieBase) && !entity1.IsInherited(Car) && !entity2.IsInherited(ZombieBase) && !entity2.IsInherited(Car))
        flags = flags | InventoryCombinationFlags.ADD_AS_ATTACHMENT;
    }
    if (!entity1.GetInventory().HasEntityInInventory(entity2) && entity1.GetInventory().CanAddEntityInCargo(entity2, entity2.GetInventory().GetFlipCargo())) flags = flags | InventoryCombinationFlags.ADD_AS_CARGO;
    if (entity1 == m_player.GetHumanInventory().GetEntityInHands() || entity2 == m_player.GetHumanInventory().GetEntityInHands())
    {
      ActionManagerClient amc;
      Class.CastTo(amc, m_player.GetActionManager());
      if (entity1 == m_player.GetHumanInventory().GetEntityInHands())
      {
        if (amc.CanPerformActionFromInventory(ItemBase.Cast(entity1), ItemBase.Cast(entity2)))
          flags = flags | InventoryCombinationFlags.PERFORM_ACTION;
        else if (amc.CanSetActionFromInventory(ItemBase.Cast(entity1), ItemBase.Cast(entity2)))
          flags = flags | InventoryCombinationFlags.SET_ACTION;
      }
      else
      {
        if (amc.CanPerformActionFromInventory(ItemBase.Cast(entity2), ItemBase.Cast(entity1)))
          flags = flags | InventoryCombinationFlags.PERFORM_ACTION;
        else if (amc.CanSetActionFromInventory(ItemBase.Cast(entity2), ItemBase.Cast(entity1)))
          flags = flags | InventoryCombinationFlags.SET_ACTION;
      }
    }
    return flags;
  }
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, Class::CastTo(), InventoryCombinationFlags::COMBINE_QUANTITY2, GetGame(), GetPlayer(), m_player, InventoryCombinationFlags::PERFORM_ACTION, and InventoryCombinationFlags::SET_ACTION.
Referenced by Attachments::CanCombine(), LayoutHolder::CanCombineEx(), and Icon::CombineItems().
GetDefaultHeaderOpenState()
bool ItemManager::GetDefaultHeaderOpenState (string type) inline protected
Definition at line 257 of file ItemManager.c.
  {
    if (m_DefautHeaderOpenStates.Contains(type))
      return m_DefautHeaderOpenStates.Get(type);
    else
      return true;
  }
References m_DefautHeaderOpenStates.
GetDefaultOpenState()
bool ItemManager::GetDefaultOpenState (string type) inline protected
Definition at line 249 of file ItemManager.c.
  {
    if (m_DefautOpenStates.Contains(type))
      return m_DefautOpenStates.Get(type);
    else
      return true;
  }
References m_DefautOpenStates.
GetDefaultOpenStateHands()
bool ItemManager::GetDefaultOpenStateHands () inline protected
Definition at line 179 of file ItemManager.c.
  {
    string value;
    GetGame().GetProfileString("defaultOpenStateHands", value);
    m_HandsDefaultOpenState = value.ToInt();
    return m_HandsDefaultOpenState;
  }
References GetGame(), and m_HandsDefaultOpenState.
GetDraggedIcon()
Icon ItemManager::GetDraggedIcon () inline protected
Definition at line 343 of file ItemManager.c.
  {
    return m_DraggedIcon;
  }
References m_DraggedIcon.
GetDraggedItem()
EntityAI ItemManager::GetDraggedItem () inline protected
Definition at line 333 of file ItemManager.c.
  {
    return m_DraggedItem;
  }
References m_DraggedItem.
GetHandsPreview()
HandsPreview ItemManager::GetHandsPreview () inline protected
Definition at line 74 of file ItemManager.c.
  {
    return m_HandsPreview;
  }
References m_HandsPreview.
GetHoveredItem()
EntityAI ItemManager::GetHoveredItem () inline protected
Definition at line 323 of file ItemManager.c.
  {
    return m_HoveredItem;
  }
References m_HoveredItem.
GetInstance()
static ItemManager ItemManager::GetInstance () inline static protected
Definition at line 265 of file ItemManager.c.
  {
    return m_Instance;
  }
References m_Instance.
Referenced by LayoutHolder::CanAddToQuickbarEx(), LayoutHolder::CanCombineEx(), LayoutHolder::CanDropEx(), LayoutHolder::CanEquipEx(), LayoutHolder::CanOpenCloseContainer(), LayoutHolder::CanSplitEx(), LayoutHolder::CanSwapOrTakeToHandsEx(), LayoutHolder::CanTakeToInventoryEx(), SlotsIcon::ClearRemainSelected(), Container::Close(), ClosableContainer::Close(), VicinityContainer::CollapseButtonOnMouseButtonDown(), Attachments::Combine(), PlayerContainer::Combine(), VicinitySlotsContainer::Combine(), Icon::Combine(), Icon::CreateWhiteBackground(), Deserialize(), Icon::DestroyWhiteBackground(), DisableMicromanagement(), Icon::DraggingOver(), ClosableContainer::DraggingOver(), PlayerContainer::DraggingOver(), DraggingOverCenterPanel(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverGrid(), ClosableContainer::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), ClosableContainer::DropReceived(), Icon::DropReceivedFromMain(), EnableMicromanagement(), ColorManager::GetItemColor(), HandsContainer::HandsContainer(), ScriptedWidgetEventHandler::HideOwnedSlotsTooltip(), ScriptedWidgetEventHandler::HideOwnedTooltip(), Icon::Icon(), SlotsIcon::Init(), Icon::InitLock(), CollapsibleContainer::LoadDefaultState(), VicinitySlotsContainer::MouseButtonDown(), Icon::MouseClick(), AttachmentCategoriesRow::MouseClick(), PlayerContainer::MouseClick(), ZombieContainer::MouseClick(), HandsContainer::MouseClick2(), ClosableContainer::MouseClick2(), MoveFocusByArea(), Icon::OnDraggingOverBackground(), ClosableHeader::OnDragHeader(), ClosableHeader::OnDropHeader(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), OnHide(), SlotsIcon::OnIconDrag(), SlotsIcon::OnIconDrop(), InventoryGridController::OnItemDrop(), InventoryGridController::OnItemDropReceived(), HandsContainer::OnSelectButton(), OnShow(), MissionBase::OnUpdate(), Container::Open(), ClosableContainer::Open(), ScriptedWidgetEventHandler::PrepareOwnedSlotsTooltip(), ScriptedWidgetEventHandler::PrepareOwnedTooltip(), AttachmentCategoriesRow::RefreshSlot(), Attachments::Select(), Container::Select(), HandsPreview::Select(), AttachmentCategoriesRow::Select(), PlayerContainer::Select(), VicinitySlotsContainer::Select(), ZombieContainer::Select(), Attachments::SelectItem(), Container::SelectItem(), HandsPreview::SelectItem(), SlotsContainer::SelectItem(), Serialize(), Container::SetOpenState(), Icon::SetTemperature(), SlotsIcon::SetTemperature(), Icon::ShowActionMenuCombine(), VicinitySlotsContainer::ShowItemsInContainers(), Icon::Swap(), HandsContainer::TakeAsAttachment(), ClosableContainer::TakeAsAttachment(), PlayerContainer::ToggleWidget(), UpdateConsoleToolbar(), Icon::UpdateFrameColor(), VicinityContainer::UpdateHeader(), Attachments::UpdateInterval(), HandsPreview::UpdateInterval(), ClosableContainer::UpdateInterval(), UpdateInterval(), IconsContainer::UpdateItemsTemperature(), Icon::~Icon(), and SlotsIcon::~SlotsIcon().
GetItemHealthColor() [1/2]
static int ItemManager::GetItemHealthColor (EntityAI item, string zone = "") inline static protected
Definition at line 403 of file ItemManager.c.
  {
    if (item)
    {
      switch (item.GetHealthLevel(zone))
      {
      case -1:
        break;
      case GameConstants.STATE_PRISTINE:
        return Colors.COLOR_PRISTINE;
      case GameConstants.STATE_WORN:
        return Colors.COLOR_WORN;
      case GameConstants.STATE_DAMAGED:
        return Colors.COLOR_DAMAGED;
      case GameConstants.STATE_BADLY_DAMAGED:
        return Colors.COLOR_BADLY_DAMAGED;
      case GameConstants.STATE_RUINED:
        return Colors.COLOR_RUINED;
      }
    }
    return 0x00FFFFFF;
  }
References Colors::COLOR_BADLY_DAMAGED, Colors::COLOR_DAMAGED, Colors::COLOR_PRISTINE, Colors::COLOR_RUINED, Colors::COLOR_WORN, GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_PRISTINE, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
GetItemHealthColor() [2/2]
static int ItemManager::GetItemHealthColor (int pHealthLevel) inline static protected
Definition at line 382 of file ItemManager.c.
  {
    switch (pHealthLevel)
    {
    case -1:
      break;
    case GameConstants.STATE_PRISTINE:
      return Colors.COLOR_PRISTINE;
    case GameConstants.STATE_WORN:
      return Colors.COLOR_WORN;
    case GameConstants.STATE_DAMAGED:
      return Colors.COLOR_DAMAGED;
    case GameConstants.STATE_BADLY_DAMAGED:
      return Colors.COLOR_BADLY_DAMAGED;
    case GameConstants.STATE_RUINED:
      return Colors.COLOR_RUINED;
    }
    return 0x00FFFFFF;
  }
References Colors::COLOR_BADLY_DAMAGED, Colors::COLOR_DAMAGED, Colors::COLOR_PRISTINE, Colors::COLOR_RUINED, Colors::COLOR_WORN, GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_PRISTINE, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
Referenced by Hud::RefreshVehicleHud(), and ActionTargetsCursor::SetItemHealth().
GetLeftDropzone()
Widget ItemManager::GetLeftDropzone () inline protected
Definition at line 301 of file ItemManager.c.
  {
    if (!m_LeftDropzone)
      m_LeftDropzone = m_RootWidget.FindAnyWidget("LeftPanel").FindAnyWidget("DropzoneX");
    return m_LeftDropzone;
  }
References m_LeftDropzone, and m_RootWidget.
Referenced by HideDropzones(), and ShowSourceDropzone().
GetRecipeCount()
static int ItemManager::GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2) inline static protected
Definition at line 783 of file ItemManager.c.
  {
    PluginRecipesManager plugin_recipes_manager = PluginRecipesManager.Cast(GetPlugin(PluginRecipesManager));
    return plugin_recipes_manager.GetValidRecipes(ItemBase.Cast(entity1), ItemBase.Cast(entity2), NULL, PlayerBase.Cast(GetGame().GetPlayer()));
  }
References GetGame(), GetPlayer(), and GetPlugin().
GetRightDropzone()
Widget ItemManager::GetRightDropzone () inline protected
Definition at line 309 of file ItemManager.c.
  {
    if (!m_RightDropzone)
      m_RightDropzone = m_RootWidget.FindAnyWidget("RightPanel").FindAnyWidget("DropzoneX");
    return m_RightDropzone;
  }
References m_RightDropzone, and m_RootWidget.
Referenced by HideDropzones(), and ShowSourceDropzone().
GetSelectedContainer()
Container ItemManager::GetSelectedContainer () inline protected
Definition at line 89 of file ItemManager.c.
  {
    return m_SelectedContainer;
  }
References m_SelectedContainer.
GetSelectedIcon()
SlotsIcon ItemManager::GetSelectedIcon () inline protected
Definition at line 99 of file ItemManager.c.
  {
    return m_SelectedIcon;
  }
References m_SelectedIcon.
GetSelectedItem()
EntityAI ItemManager::GetSelectedItem () inline protected
Definition at line 84 of file ItemManager.c.
  {
    return m_SelectedItem;
  }
References m_SelectedItem.
GetSelectedWidget()
Widget ItemManager::GetSelectedWidget () inline protected
Definition at line 94 of file ItemManager.c.
  {
    return m_SelectedWidget;
  }
References m_SelectedWidget.
HideDropzones()
void ItemManager::HideDropzones () inline protected
Definition at line 270 of file ItemManager.c.
  {
    GetRightDropzone().SetAlpha(0);
    GetLeftDropzone().SetAlpha(0);
    GetCenterDropzone().SetAlpha(0);
  }
References GetCenterDropzone(), GetLeftDropzone(), and GetRightDropzone().
Referenced by ShowSourceDropzone().
HideTooltip()
void ItemManager::HideTooltip () inline protected
Definition at line 363 of file ItemManager.c.
  {
    m_TooltipWidget.Show(false);
    m_HoveredItem = null;
    delete m_ToolTipTimer;
    HideTooltipSlot();
  }
References HideTooltipSlot(), m_HoveredItem, m_ToolTipTimer, and m_TooltipWidget.
Referenced by PrepareSlotsTooltip(), and PrepareTooltip().
HideTooltipSlot()
void ItemManager::HideTooltipSlot () inline protected
Definition at line 372 of file ItemManager.c.
  {
    if (m_SlotInfoShown)
    {
      m_TooltipSlotWidget.Show(false);
      m_SlotInfoShown = false;
      delete m_TooltipSlotTimer;
    }
  }
References m_SlotInfoShown, m_TooltipSlotTimer, and m_TooltipSlotWidget.
Referenced by HideTooltip().
IsDragging()
bool ItemManager::IsDragging () inline protected
Definition at line 358 of file ItemManager.c.
  {
    return m_IsDragging;
  }
References m_IsDragging.
Referenced by PrepareTooltip().
IsMicromanagmentMode()
bool ItemManager::IsMicromanagmentMode () inline protected
Definition at line 69 of file ItemManager.c.
  {
    return m_ItemMicromanagmentMode;
  }
References m_ItemMicromanagmentMode.
PrepareSlotsTooltip()
void ItemManager::PrepareSlotsTooltip (string name, string desc, int x = 0, int y = 0) inline protected
position is currentlycalculated from the owning 'm_TooltipSourceWidget' directly
Definition at line 547 of file ItemManager.c.
  {
    InspectMenuNew.UpdateSlotInfo(m_TooltipSlotWidget, name, desc);
    HideTooltip();
    if (name != "")
    {
      m_SlotInfoShown = true;
      //CalculateTooltipSlotPosition(x,y);
      m_TooltipSlotTimer = new Timer();
      m_TooltipSlotTimer.Run(TOOLTIP_DELAY, this, "ShowTooltipSlot");
    }
  }
References HideTooltip(), m_SlotInfoShown, m_TooltipSlotTimer, m_TooltipSlotWidget, name, and TOOLTIP_DELAY.
PrepareTooltip()
void ItemManager::PrepareTooltip (EntityAI item, int x = 0, int y = 0) inline protected
Definition at line 492 of file ItemManager.c.
  {
    if (IsDragging() || !item)
      return;
    if (item.IsInherited(InventoryItem))
    {
      HideTooltip();
      m_HoveredItem = item;
      InspectMenuNew.UpdateItemInfo(m_TooltipWidget, item);
      int screen_w, screen_h;
      float w, h;
      GetScreenSize(screen_w, screen_h);
      m_TooltipWidget.GetScreenSize(w, h);
      if (x == -1)//set by icon focusing
      {
        x = screen_w / 2 - w / 2;
        float x1, y1;
        m_RootWidget.FindAnyWidget("InventoryFrameWidget").GetScreenPos(x1, y1); //allign to the same height
        y = y1;
      }
      else if (x == 0 && y == 0 && GetGame().GetInput().IsEnabledMouseAndKeyboardEvenOnServer())
        GetMousePos(x, y);
      //minimal edge distance adjustments..
      screen_w -= 10;
      screen_h -= 10;
      int rightEdge = x + w;
      if (rightEdge > screen_w)
        x = screen_w - w;
      int bottomEdge = y + h;
      if (bottomEdge > screen_h)
        y = screen_h - h;
      m_TooltipWidget.SetPos(x, y);
      m_ToolTipTimer = new Timer();
      m_ToolTipTimer.Run(TOOLTIP_DELAY, this, "ShowTooltip");
      Widget preview_frame = m_TooltipWidget.FindAnyWidget("ItemFrameWidget");
      if (preview_frame)
      {
        m_ItemPreviewWidget = ItemPreviewWidget.Cast(preview_frame);
        m_ItemPreviewWidget.SetItem(item);
        m_ItemPreviewWidget.SetView(item.GetViewIndex());
      }
    }
  }
References GetGame(), GetInput(), GetMousePos(), GetScreenSize(), HideTooltip(), IsDragging(), m_HoveredItem, m_ItemPreviewWidget, m_RootWidget, m_ToolTipTimer, m_TooltipWidget, ItemPreviewWidget::SetItem(), ItemPreviewWidget::SetView(), TOOLTIP_DELAY, x, and y.
SerializeDefaultHeaderOpenStates()
void ItemManager::SerializeDefaultHeaderOpenStates () inline protected
Definition at line 187 of file ItemManager.c.
  {
    TStringArray serialized_types = new TStringArray;
    for (int i = 0; i < m_DefautHeaderOpenStates.Count(); i++)
    {
      int is_opened = m_DefautHeaderOpenStates.GetElement(i); //from bool to int for easier parsing
      serialized_types.Insert(m_DefautHeaderOpenStates.GetKey(i) + "," + is_opened);
    }
    if (serialized_types.Count() > 0)
      GetGame().SetProfileStringList("defaultHeaderOpenStates", serialized_types);
    GetGame().SaveProfile();
  }
References GetGame(), and m_DefautHeaderOpenStates.
SerializeDefaultOpenStates()
void ItemManager::SerializeDefaultOpenStates () inline protected
Definition at line 218 of file ItemManager.c.
  {
    TStringArray serialized_types = new TStringArray;
    for (int i = 0; i < m_DefautOpenStates.Count(); i++)
    {
      int is_opened = m_DefautOpenStates.GetElement(i); //from bool to int for easier parsing
      serialized_types.Insert(m_DefautOpenStates.GetKey(i) + "," + is_opened);
    }
    if (serialized_types.Count() > 0)
      GetGame().SetProfileStringList("defaultOpenStates", serialized_types);
    GetGame().SaveProfile();
  }
References GetGame(), and m_DefautOpenStates.
SetDefaultHeaderOpenState()
void ItemManager::SetDefaultHeaderOpenState (string type, bool is_opened) inline protected
Definition at line 166 of file ItemManager.c.
  {
    m_DefautHeaderOpenStates.Set(type, is_opened);
  }
References m_DefautHeaderOpenStates.
Referenced by DeserializeDefaultHeaderOpenStates().
SetDefaultOpenState()
void ItemManager::SetDefaultOpenState (string type, bool is_opened) inline protected
Definition at line 161 of file ItemManager.c.
  {
    m_DefautOpenStates.Set(type, is_opened);
  }
References m_DefautOpenStates.
Referenced by DeserializeDefaultOpenStates().
SetDefaultOpenStateHands()
void ItemManager::SetDefaultOpenStateHands (bool is_opened) inline protected
Definition at line 171 of file ItemManager.c.
  {
    m_HandsDefaultOpenState = is_opened;
    int hands_default_open_state = m_HandsDefaultOpenState; //from bool to int for easier parsing
    GetGame().SetProfileString("defaultOpenStateHands", hands_default_open_state.ToString());
    GetGame().SaveProfile();
  }
References GetGame(), and m_HandsDefaultOpenState.
SetDraggedIcon()
void ItemManager::SetDraggedIcon (Icon dragged_icon) inline protected
Definition at line 338 of file ItemManager.c.
  {
    m_DraggedIcon = dragged_icon;
  }
References m_DraggedIcon.
Referenced by SetIsDragging().
SetDraggedItem()
void ItemManager::SetDraggedItem (EntityAI dragged_item) inline protected
Definition at line 328 of file ItemManager.c.
  {
    m_DraggedItem = dragged_item;
  }
References m_DraggedItem.
Referenced by SetIsDragging().
SetHandsPreview()
void ItemManager::SetHandsPreview (HandsPreview hansd_preview) inline protected
Definition at line 79 of file ItemManager.c.
  {
    m_HandsPreview = hansd_preview;
  }
References m_HandsPreview.
SetIconTemperature()
void ItemManager::SetIconTemperature (EntityAI item, Widget item_w) inline protected
Definition at line 472 of file ItemManager.c.
  {
    if (item_w)
    {
      if (item && item.IsInherited(ItemBase))
      {
        int color = ColorManager.GetInstance().GetItemColor(ItemBase.Cast(item));
        if (color)
        {
          Widget color_widget = item_w.FindAnyWidget("Color");
          if (color != -1)
            color_widget.SetColor(color);
          else
            color_widget.SetColor(ColorManager.BASE_COLOR);
        }
      }
    }
  }
References ColorManager::BASE_COLOR, and ColorManager::GetInstance().
SetIsDragging()
void ItemManager::SetIsDragging (bool is_dragging) inline protected
Definition at line 348 of file ItemManager.c.
  {
    m_IsDragging = is_dragging;
    if (!is_dragging)
    {
      SetDraggedItem(null);
      SetDraggedIcon(null);
    }
  }
References m_IsDragging, SetDraggedIcon(), and SetDraggedItem().
SetItemMicromanagmentMode()
void ItemManager::SetItemMicromanagmentMode (bool item_micromanagment_mode) inline protected
Definition at line 63 of file ItemManager.c.
  {
    m_ItemMicromanagmentMode = item_micromanagment_mode;
    Inventory.GetInstance().UpdateConsoleToolbar();
  }
References Inventory(), and m_ItemMicromanagmentMode.
SetSelectedItem()
void ItemManager::SetSelectedItem (EntityAI selected_item, Container selected_container, Widget selected_widget, SlotsIcon selected_icon) inline protected
Definition at line 104 of file ItemManager.c.
  {
    m_SelectedItem = selected_item;
    m_SelectedContainer = selected_container;
    m_SelectedWidget = selected_widget;
    m_SelectedIcon = selected_icon;
  }
References m_SelectedContainer, m_SelectedIcon, m_SelectedItem, and m_SelectedWidget.
SetSelectedItemEx()
void ItemManager::SetSelectedItemEx (EntityAI selected_item, Container selected_container, LayoutHolder selected_icon) inline protected
Definition at line 112 of file ItemManager.c.
  {
    SlotsIcon sIcon;
    Icon icon;
    m_SelectedItem = selected_item;
    m_SelectedContainer = selected_container;
    if (m_SelectedBaseIcon)
    {
      sIcon = SlotsIcon.Cast(m_SelectedBaseIcon);
      icon = Icon.Cast(m_SelectedBaseIcon);
      if (sIcon)
        sIcon.GetMicromanagedPanel().Show(false);
      else if (icon)
        icon.GetMicromanagedPanel().Show(false);
    }
    if (selected_icon)
    {
      sIcon = SlotsIcon.Cast(selected_icon);
      icon = Icon.Cast(selected_icon);
      if (sIcon)
      {
        m_SelectedWidget = sIcon.GetCursorWidget();
        sIcon.GetMicromanagedPanel().Show(true);
      }
      else if (icon)
      {
        m_SelectedWidget = icon.GetCursorWidget();
        icon.GetMicromanagedPanel().Show(true);
      }
    }
    else
      m_SelectedWidget = null;
    m_SelectedBaseIcon = selected_icon;
  }
References m_SelectedBaseIcon, m_SelectedContainer, m_SelectedItem, and m_SelectedWidget.
SetTemperature()
void ItemManager::SetTemperature (EntityAI item, Widget item_w) inline protected
Definition at line 443 of file ItemManager.c.
  {
    if (item_w)
    {
      if (true/*show_temperature */)
      {
        if (item && item.IsInherited(ItemBase))
        {
          int color = ColorManager.GetInstance().GetItemColor(ItemBase.Cast(item)); // !!!!!
          if (color)
          {
            string name = item_w.GetName();
            name.Replace("Render", "Temperature");
            Widget temperature_widget = item_w.GetParent().FindAnyWidget(name);
            if (color != -1)
            {
              temperature_widget.Show(true);
              temperature_widget.SetColor(color);
            }
            else
              temperature_widget.Show(false);
            temperature_widget.SetAlpha(0.3);
          }
        }
      }
    }
  }
References ColorManager::GetInstance(), and name.
SetTooltipWidget()
void ItemManager::SetTooltipWidget (Widget w) inline protected
Definition at line 628 of file ItemManager.c.
  {
    m_TooltipSourceWidget = w;
  }
References m_TooltipSourceWidget.
SetWidgetDraggable()
void ItemManager::SetWidgetDraggable (Widget w, bool draggable) inline protected
Definition at line 647 of file ItemManager.c.
  {
    if (w)
    {
      if (draggable)
        w.SetFlags(WidgetFlags.DRAGGABLE);
      else
        w.ClearFlags(WidgetFlags.DRAGGABLE);
    }
  }
ShowSourceDropzone()
void ItemManager::ShowSourceDropzone (EntityAI item) inline protected
Definition at line 277 of file ItemManager.c.
  {
    EntityAI owner = item.GetHierarchyParent();
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (item == player)
      GetRightDropzone().SetAlpha(1);
    else if (owner && owner != player)
      ShowSourceDropzone(owner);
    else
    {
      InventoryLocation inv_loc_src = new InventoryLocation;
      item.GetInventory().GetCurrentInventoryLocation(inv_loc_src);
      int loc_type = inv_loc_src.GetType();
      HideDropzones();
      if (loc_type == InventoryLocationType.GROUND)
        GetLeftDropzone().SetAlpha(1);
      else if (loc_type == InventoryLocationType.HANDS)
        GetCenterDropzone().SetAlpha(1);
      else
        GetRightDropzone().SetAlpha(1);
    }
  }
References GetCenterDropzone(), GetGame(), GetLeftDropzone(), GetPlayer(), GetRightDropzone(), HideDropzones(), and ShowSourceDropzone().
Referenced by ShowSourceDropzone().
ShowTooltip()
void ItemManager::ShowTooltip () inline protected
Definition at line 658 of file ItemManager.c.
  {
    if (m_ItemPreviewWidget)
      m_TooltipWidget.Show(true);
  }
References m_ItemPreviewWidget, and m_TooltipWidget.
ShowTooltipSlot()
void ItemManager::ShowTooltipSlot () inline protected
Definition at line 664 of file ItemManager.c.
  {
    UpdateTooltipSlotPosition();
    m_TooltipSlotWidget.SetPos(m_TooltipPosX, m_TooltipPosY);
    m_TooltipSlotWidget.Show(true);
  }
References m_TooltipPosX, m_TooltipPosY, m_TooltipSlotWidget, and UpdateTooltipSlotPosition().
UpdateTooltipSlotPosition()
void ItemManager::UpdateTooltipSlotPosition () inline protected
Definition at line 621 of file ItemManager.c.
  {
    float x, y;
    m_TooltipSourceWidget.GetScreenPos(x, y);
    CalculateTooltipSlotPosition(x, y);
  }
References CalculateTooltipSlotPosition(), m_TooltipSourceWidget, x, and y.
Referenced by ShowTooltipSlot().
Member Data Documentation
m_CenterDropzone
Widget ItemManager::m_CenterDropzone protected
Definition at line 31 of file ItemManager.c.
Referenced by GetCenterDropzone().
m_DefautHeaderOpenStates
ref map<string, bool> ItemManager::m_DefautHeaderOpenStates protected
Definition at line 15 of file ItemManager.c.
Referenced by ClearDefaultHeaderOpenStates(), GetDefaultHeaderOpenState(), ItemManager(), SerializeDefaultHeaderOpenStates(), and SetDefaultHeaderOpenState().
m_DefautOpenStates
ref map<string, bool> ItemManager::m_DefautOpenStates protected
Definition at line 14 of file ItemManager.c.
Referenced by ClearDefaultOpenStates(), GetDefaultOpenState(), ItemManager(), SerializeDefaultOpenStates(), and SetDefaultOpenState().
m_DraggedIcon
Icon ItemManager::m_DraggedIcon protected
Definition at line 8 of file ItemManager.c.
Referenced by GetDraggedIcon(), and SetDraggedIcon().
m_DraggedItem
EntityAI ItemManager::m_DraggedItem protected
Definition at line 7 of file ItemManager.c.
Referenced by GetDraggedItem(), and SetDraggedItem().
m_HandsDefaultOpenState
int ItemManager::m_HandsDefaultOpenState protected
Definition at line 16 of file ItemManager.c.
Referenced by GetDefaultOpenStateHands(), and SetDefaultOpenStateHands().
m_HandsPreview
HandsPreview ItemManager::m_HandsPreview protected
Definition at line 26 of file ItemManager.c.
Referenced by GetHandsPreview(), and SetHandsPreview().
m_HoveredItem
EntityAI ItemManager::m_HoveredItem protected
Definition at line 5 of file ItemManager.c.
Referenced by GetHoveredItem(), HideTooltip(), and PrepareTooltip().
m_Instance
ref ItemManager ItemManager::m_Instance static private
Definition at line 3 of file ItemManager.c.
Referenced by GetInstance(), and ItemManager().
m_IsDragging
bool ItemManager::m_IsDragging protected
Definition at line 4 of file ItemManager.c.
Referenced by IsDragging(), and SetIsDragging().
m_ItemMicromanagmentMode
bool ItemManager::m_ItemMicromanagmentMode protected
Definition at line 28 of file ItemManager.c.
Referenced by IsMicromanagmentMode(), and SetItemMicromanagmentMode().
m_ItemPreviewWidget
ItemPreviewWidget ItemManager::m_ItemPreviewWidget protected
Definition at line 12 of file ItemManager.c.
Referenced by PrepareTooltip(), and ShowTooltip().
m_LeftDropzone
Widget ItemManager::m_LeftDropzone protected
Definition at line 30 of file ItemManager.c.
Referenced by GetLeftDropzone().
m_RightDropzone
Widget ItemManager::m_RightDropzone protected
Definition at line 32 of file ItemManager.c.
Referenced by GetRightDropzone().
m_RootWidget
Widget ItemManager::m_RootWidget protected
Definition at line 13 of file ItemManager.c.
Referenced by GetCenterDropzone(), GetLeftDropzone(), GetRightDropzone(), ItemManager(), and PrepareTooltip().
m_SelectedBaseIcon
LayoutHolder ItemManager::m_SelectedBaseIcon protected
Definition at line 24 of file ItemManager.c.
Referenced by SetSelectedItemEx().
m_SelectedContainer
Container ItemManager::m_SelectedContainer protected
Definition at line 21 of file ItemManager.c.
Referenced by GetSelectedContainer(), SetSelectedItem(), and SetSelectedItemEx().
m_SelectedIcon
SlotsIcon ItemManager::m_SelectedIcon protected
Definition at line 23 of file ItemManager.c.
Referenced by GetSelectedIcon(), and SetSelectedItem().
m_SelectedItem
EntityAI ItemManager::m_SelectedItem protected
Definition at line 20 of file ItemManager.c.
Referenced by GetSelectedItem(), SetSelectedItem(), and SetSelectedItemEx().
m_SelectedWidget
Widget ItemManager::m_SelectedWidget protected
Definition at line 22 of file ItemManager.c.
Referenced by GetSelectedWidget(), SetSelectedItem(), and SetSelectedItemEx().
m_SlotInfoShown
bool ItemManager::m_SlotInfoShown protected
Definition at line 6 of file ItemManager.c.
Referenced by HideTooltipSlot(), ItemManager(), and PrepareSlotsTooltip().
m_TooltipCategoryWidget
ref Widget ItemManager::m_TooltipCategoryWidget protected
Definition at line 11 of file ItemManager.c.
m_TooltipPosX
int ItemManager::m_TooltipPosX protected
Definition at line 34 of file ItemManager.c.
Referenced by CalculateTooltipSlotPosition(), and ShowTooltipSlot().
m_TooltipPosY
int ItemManager::m_TooltipPosY protected
Definition at line 35 of file ItemManager.c.
Referenced by CalculateTooltipSlotPosition(), and ShowTooltipSlot().
m_TooltipSlotTimer
ref Timer ItemManager::m_TooltipSlotTimer protected
Definition at line 18 of file ItemManager.c.
Referenced by HideTooltipSlot(), and PrepareSlotsTooltip().
m_TooltipSlotWidget
ref Widget ItemManager::m_TooltipSlotWidget protected
Definition at line 10 of file ItemManager.c.
Referenced by CalculateTooltipSlotPosition(), HideTooltipSlot(), ItemManager(), PrepareSlotsTooltip(), and ShowTooltipSlot().
m_TooltipSourceWidget
Widget ItemManager::m_TooltipSourceWidget protected
Definition at line 36 of file ItemManager.c.
Referenced by CalculateTooltipSlotPosition(), SetTooltipWidget(), and UpdateTooltipSlotPosition().
m_ToolTipTimer
ref Timer ItemManager::m_ToolTipTimer protected
Definition at line 17 of file ItemManager.c.
Referenced by HideTooltip(), and PrepareTooltip().
m_TooltipWidget
ref Widget ItemManager::m_TooltipWidget protected
Definition at line 9 of file ItemManager.c.
Referenced by HideTooltip(), ItemManager(), PrepareTooltip(), and ShowTooltip().
TOOLTIP_DELAY
const float ItemManager::TOOLTIP_DELAY = 0.25 protected
Definition at line 39 of file ItemManager.c.
Referenced by PrepareSlotsTooltip(), and PrepareTooltip().
The documentation for this class was generated from the following file:
scripts/5_Mission/GUI/InventoryNew/ItemManager.c