DayZ: ActionRestrainTarget Class Reference
ActionRestrainTarget Class Reference
Private Member Functions
void ActionRestrainTarget ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override int GetStanceMask (PlayerBase player)
override bool ActionConditionContinue (ActionData action_data)
override void OnStartServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnFinishProgressClient (ActionData action_data)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 19 of file ActionRestrainTarget.c.
Constructor & Destructor Documentation
ActionRestrainTarget()
void ActionRestrainTarget::ActionRestrainTarget () inline private
Definition at line 21 of file ActionRestrainTarget.c.
  {
    m_CallbackClass = ActionRestrainTargetCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_RESTRAINTARGET;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
    m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
    m_Text = "#restrain";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionRestrainTarget::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 37 of file ActionRestrainTarget.c.
  {
    PlayerBase other_player = PlayerBase.Cast(target.GetObject());
    if (!other_player)
      return false;
    if (player.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
      return other_player.CanBeRestrained();
    else
      return !other_player.IsRestrained();
  }
ActionConditionContinue()
override bool ActionRestrainTarget::ActionConditionContinue (ActionData action_data) inline private
Definition at line 57 of file ActionRestrainTarget.c.
  {
    PlayerBase target_player = PlayerBase.Cast(action_data.m_Target.GetObject());
    if (GetGame().IsServer() && GetGame().IsMultiplayer())
    {
      if (target_player.IsSurrendered() || !target_player.CanBeRestrained())
        return false;
    }
    if (GetGame().IsServer())
    {
      ActionRestrainTargetCB callback = ActionRestrainTargetCB.Cast(action_data.m_Callback);
      if (callback.GetActionComponentProgress() > 0.75 && !target_player.IsRestrainPrelocked())
        target_player.SetRestrainPrelocked(true);
      return !GetGame().GetMission().IsPlayerDisconnecting(target_player);
    }
    return true;
  }
References GetGame().
CreateConditionComponents()
override void ActionRestrainTarget::CreateConditionComponents () inline private
Definition at line 31 of file ActionRestrainTarget.c.
  {
    m_ConditionTarget = new CCTMan(UAMaxDistances.DEFAULT);
    m_ConditionItem = new CCINonRuined;
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetStanceMask()
override int ActionRestrainTarget::GetStanceMask (PlayerBase player) inline private
Definition at line 49 of file ActionRestrainTarget.c.
  {
    if (player.IsPlayerInStance(DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_PRONE))
      return DayZPlayerConstants.STANCEMASK_CROUCH;
    else
      return DayZPlayerConstants.STANCEMASK_ERECT;
  }
OnEndServer()
override void ActionRestrainTarget::OnEndServer (ActionData action_data) inline private
Definition at line 93 of file ActionRestrainTarget.c.
  {
    PlayerBase target_player = PlayerBase.Cast(action_data.m_Target.GetObject());
    if (target_player)
    {
      target_player.SetRestrainStarted(false);
      target_player.SetRestrainPrelocked(false);
    }
  }
OnFinishProgressClient()
override void ActionRestrainTarget::OnFinishProgressClient (ActionData action_data) inline private
Definition at line 138 of file ActionRestrainTarget.c.
  {
    super.OnFinishProgressClient(action_data);
    GetGame().GetAnalyticsClient().OnActionRestrain();
  }
References GetGame().
OnFinishProgressServer()
override void ActionRestrainTarget::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 103 of file ActionRestrainTarget.c.
  {
    PlayerBase target_player = PlayerBase.Cast(action_data.m_Target.GetObject());
    PlayerBase source_player = PlayerBase.Cast(action_data.m_Player);
    if (CanReceiveAction(action_data.m_Target) && !target_player.IsRestrained())
    {
      EntityAI item_in_hands_target = target_player.GetHumanInventory().GetEntityInHands();
      EntityAI item_in_hands_source = source_player.GetHumanInventory().GetEntityInHands();
      if (!item_in_hands_source)
      {
        Error("Restraining target failed, nothing in hands");
        return;
      }
      string new_item_name = MiscGameplayFunctions.ObtainRestrainItemTargetClassname(item_in_hands_source);
      if (item_in_hands_target)
      {
        Print("Restraining player with item in hands, first drop & then restrain");
        ChainedDropAndRestrainLambda lambda2 = new ChainedDropAndRestrainLambda(item_in_hands_target, item_in_hands_target.GetType(), target_player, false, source_player);
        MiscGameplayFunctions.TurnItemInHandsIntoItemEx(target_player, lambda2);
      }
      else
      {
        Print("Restraining player with empty hands");
        RestrainTargetPlayerLambda lambda = new RestrainTargetPlayerLambda(item_in_hands_source, new_item_name, target_player);
        source_player.LocalReplaceItemInHandsWithNewElsewhere(lambda);
      }
      action_data.m_Player.GetSoftSkillsManager().AddSpecialty(m_SpecialtyWeight);
    }
  }
References CanReceiveAction(), Error(), m_SpecialtyWeight, Print(), and RestrainTargetPlayerLambda().
OnStartServer()
override void ActionRestrainTarget::OnStartServer (ActionData action_data) inline private
Definition at line 79 of file ActionRestrainTarget.c.
  {
    PlayerBase target_player = PlayerBase.Cast(action_data.m_Target.GetObject());
    if (target_player.IsSurrendered())
    {
      SurrenderDataRestrain sdr = new SurrenderDataRestrain;
      target_player.EndSurrenderRequest(sdr);
    }
    else if (target_player.IsEmotePlaying())
      target_player.m_EmoteManager.ServerRequestEmoteCancel();
    target_player.SetRestrainStarted(true);
  }
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionRestrainTarget.c