DayZ: scripts/4_World/Classes/SoundEvents/PlayerSoundEvents/Events/SymptomEvents.c File Reference
SymptomEvents.c File Reference
Classes
class PlayerSoundEventBase
class SymptomSoundEventBase
Functions
class SymptomSoundEventBase extends PlayerSoundEventBase CoughSoundEvent ()
void SymptomSoundEventBase ()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
class LaugherSoundEvent extends SymptomSoundEventBase SneezeSoundEvent ()
void LaugherSoundEvent ()
Function Documentation
CoughSoundEvent()
class SymptomSoundEventBase extends PlayerSoundEventBase CoughSoundEvent ()
Definition at line 1 of file SymptomEvents.c.
  {
    m_ID = EPlayerSoundEventID.SYMPTOM_COUGH;
    m_SoundVoiceAnimEventClassID = 8;
  }
Referenced by PlayerSoundEventHandler().
HasPriorityOverCurrent()
override bool CoughSoundEvent::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
Definition at line 24 of file SymptomEvents.c.
{
  void LaugherSoundEvent()
  {
LaugherSoundEvent()
void SneezeSoundEvent::LaugherSoundEvent ()
Definition at line 36 of file SymptomEvents.c.
  {
    m_ID = EPlayerSoundEventID.SYMPTOM_SNEEZE;
    m_SoundVoiceAnimEventClassID = 9;
  }
}
References m_ID, and m_SoundVoiceAnimEventClassID.
Referenced by PlayerSoundEventHandler().
SneezeSoundEvent()
class LaugherSoundEvent extends SymptomSoundEventBase SneezeSoundEvent ()
Definition at line 24 of file SymptomEvents.c.
  {
    m_ID = EPlayerSoundEventID.SYMPTOM_SNEEZE;
    m_SoundVoiceAnimEventClassID = 9;
  }
Referenced by PlayerSoundEventHandler().
SymptomSoundEventBase()
void CoughSoundEvent::SymptomSoundEventBase ()
Definition at line 18 of file SymptomEvents.c.
  {
    m_ID = EPlayerSoundEventID.SYMPTOM_COUGH;
    m_SoundVoiceAnimEventClassID = 8;
  }
}
References m_ID, and m_SoundVoiceAnimEventClassID.