DayZ: scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionDrinkPondContinuous.c File Reference
ActionDrinkPondContinuous.c File Reference
Classes
class ActionDrinkPondContinuousCB
Functions
void ActionDrinkPondContinuous ()
override bool IsDrink ()
override GetInputType ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStart (ActionData action_data)
override void OnEnd (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnEndAnimationLoopServer (ActionData action_data)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
Variables
ActionDrinkPondContinuousCB WATER_DRANK_PER_SEC = 35
const string ALLOWED_WATER_SURFACES = string.Format("%1|%2", UAWaterType.FRESH, UAWaterType.STILL)
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) protected
Definition at line 39 of file ActionDrinkPondContinuous.c.
  {
    if (item && item.IsHeavyBehaviour())
      return false;
    return player.CanEatAndDrink();
  }
ActionDrinkPondContinuous()
void ActionDrinkPondContinuous () protected
Definition at line 14 of file ActionDrinkPondContinuous.c.
  {
    m_CallbackClass = ActionDrinkPondContinuousCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DRINKPOND;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH;
    m_Text = "#drink";
  }
References m_FullBody, m_StanceMask, and m_Text.
CreateConditionComponents()
override void CreateConditionComponents () protected
Definition at line 33 of file ActionDrinkPondContinuous.c.
  {
    m_ConditionItem = new CCINone();
    m_ConditionTarget = new CCTWaterSurface(UAMaxDistances.DEFAULT, ALLOWED_WATER_SURFACES);
  }
References ALLOWED_WATER_SURFACES, UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetInputType()
override GetInputType () protected
Definition at line 28 of file ActionDrinkPondContinuous.c.
  {
    return ContinuousInteractActionInput;
  }
IsDrink()
override bool IsDrink () protected
Definition at line 23 of file ActionDrinkPondContinuous.c.
  {
    return true;
  }
OnEnd()
override void OnEnd (ActionData action_data) protected
Definition at line 54 of file ActionDrinkPondContinuous.c.
  {
    action_data.m_Player.TryHideItemInHands(false);
  }
OnEndAnimationLoopServer()
override void OnEndAnimationLoopServer (ActionData action_data) protected
Definition at line 66 of file ActionDrinkPondContinuous.c.
  {
    if (action_data.m_Player.HasBloodyHands() && !action_data.m_Player.GetInventory().FindAttachment(InventorySlots.GLOVES))
      action_data.m_Player.SetBloodyHandsPenalty();
  }
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) protected
Definition at line 59 of file ActionDrinkPondContinuous.c.
  {
    Param1<float> nacdata = Param1<float>.Cast(action_data.m_ActionComponent.GetACData());
    float amount = UAQuantityConsumed.DRINK;
    action_data.m_Player.Consume(null, amount, EConsumeType.ENVIRO_POND);
  }
References UAQuantityConsumed::DRINK.
OnStart()
override void OnStart (ActionData action_data) protected
Definition at line 47 of file ActionDrinkPondContinuous.c.
  {
    super.OnStart(action_data);
    action_data.m_Player.TryHideItemInHands(true);
  }
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) protected
Definition at line 85 of file ActionDrinkPondContinuous.c.
  {
    super.ReadFromContext(ctx, action_recive_data);
    if (HasTarget())
    {
      vector cursorPosition;
      if (!ctx.Read(cursorPosition))
        return false;
      action_recive_data.m_Target.SetCursorHitPos(cursorPosition);
    }
    return true;
  }
References HasTarget().
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data) protected
Definition at line 72 of file ActionDrinkPondContinuous.c.
  {
    super.WriteToContext(ctx, action_data);
    if (HasTarget())
    {
      ctx.Write(action_data.m_Target.GetCursorHitPos());
      return;
    }
    ctx.Write(vector.Zero);
  }
References HasTarget(), and vector::Zero.
Variable Documentation
ALLOWED_WATER_SURFACES
const string ALLOWED_WATER_SURFACES = string.Format("%1|%2", UAWaterType.FRESH, UAWaterType.STILL) protected
Definition at line 12 of file ActionDrinkPondContinuous.c.
Referenced by CreateConditionComponents().
WATER_DRANK_PER_SEC
ActionDrinkPondContinuousCB WATER_DRANK_PER_SEC = 35