DayZ: ObjectSpawnerHandler Class Reference
ObjectSpawnerHandler Class Reference
Static Protected Member Functions
static void SpawnObjects ()
static void SpawnObject (ITEM_SpawnerObject item)
static void OnGameplayDataHandlerLoad ()
static bool ValidatePath (string path)
Static Protected Attributes
static const ref TStringArray VALID_PATHS = {"DZ\\plants", "DZ\\plants_bliss", "DZ\\rocks", "DZ\\rocks_bliss", "DZ/plants", "DZ/plants_bliss", "DZ/rocks", "DZ/rocks_bliss"}
Detailed Description
Definition at line 1 of file ObjectSpawner.c.
Member Function Documentation
OnGameplayDataHandlerLoad()
static void ObjectSpawnerHandler::OnGameplayDataHandlerLoad () inline static protected
Definition at line 63 of file ObjectSpawner.c.
  {
    SpawnObjects();
    GetGame().GetWorld().ProcessMarkedObjectsForPathgraphUpdate();
  }
References GetGame(), and SpawnObjects().
Referenced by CGame::GlobalsInit().
SpawnObject()
static void ObjectSpawnerHandler::SpawnObject (ITEM_SpawnerObject item) inline static protected
Definition at line 27 of file ObjectSpawner.c.
  {
    Object object;
    float scale = item.scale;
    if (scale == 0)
      scale = 1;
    if (item.name.Contains("\\") || item.name.Contains("/"))
    {
      if (ValidatePath(item.name))
        object = GetGame().CreateStaticObjectUsingP3D(item.name, vector.ArrayToVec(item.pos), vector.ArrayToVec(item.ypr), scale);
    }
    else
    {
      int flags = ECE_SETUP | ECE_UPDATEPATHGRAPH | ECE_CREATEPHYSICS | ECE_NOLIFETIME | ECE_DYNAMIC_PERSISTENCY;
      if (item.enableCEPersistency)
      {
        flags &= ~ECE_DYNAMIC_PERSISTENCY;
        flags &= ~ECE_NOLIFETIME;
      }
      object = GetGame().CreateObjectEx(item.name, vector.ArrayToVec(item.pos), flags, RF_IGNORE);
      if (object)
      {
        object.SetOrientation(vector.ArrayToVec(item.ypr));
        if (item.scale != 1)
          object.SetScale(scale);
      }
    }
    if (!object)
      PrintToRPT("Object spawner failed to spawn " + item.name);
  }
References vector::ArrayToVec(), ECE_CREATEPHYSICS, ECE_DYNAMIC_PERSISTENCY, ECE_NOLIFETIME, ECE_SETUP, ECE_UPDATEPATHGRAPH, GetGame(), PrintToRPT(), RF_IGNORE, and ValidatePath().
Referenced by SpawnObjects().
SpawnObjects()
static void ObjectSpawnerHandler::SpawnObjects () inline static protected
Definition at line 5 of file ObjectSpawner.c.
  {
    if (CfgGameplayHandler.GetObjectSpawnersArr() && CfgGameplayHandler.GetObjectSpawnersArr().Count() > 0)
    {
      TStringArray arr = CfgGameplayHandler.GetObjectSpawnersArr();
      foreach (string spawnerFilePath: arr)
      {
        string path = "$mission:" + spawnerFilePath;
        string errorMessage;
        ObjectSpawnerJson spawner;
        if (JsonFileLoader<ObjectSpawnerJson>.LoadFile(path, spawner, errorMessage))
        {
          foreach (ITEM_SpawnerObject o : spawner.Objects)
            SpawnObject(o);
        }
        else
          ErrorEx(errorMessage);
      }
    }
  }
References ErrorEx, CfgGameplayHandler::GetObjectSpawnersArr(), path, and SpawnObject().
Referenced by OnGameplayDataHandlerLoad().
ValidatePath()
static bool ObjectSpawnerHandler::ValidatePath (string path) inline static protected
Definition at line 70 of file ObjectSpawner.c.
  {
    foreach (string p: VALID_PATHS)
    {
      if (path.Contains(p))
        return true;
    }
    return false;
  }
References string::Contains(), path, and VALID_PATHS.
Referenced by SpawnObject().
Member Data Documentation
VALID_PATHS
const ref TStringArray ObjectSpawnerHandler::VALID_PATHS = {"DZ\\plants", "DZ\\plants_bliss", "DZ\\rocks", "DZ\\rocks_bliss", "DZ/plants", "DZ/plants_bliss", "DZ/rocks", "DZ/rocks_bliss"} static protected
Definition at line 3 of file ObjectSpawner.c.
{"DZ\\plants", "DZ\\plants_bliss", "DZ\\rocks", "DZ\\rocks_bliss", "DZ/plants", "DZ/plants_bliss", "DZ/rocks", "DZ/rocks_bliss"};
Referenced by ValidatePath().
The documentation for this class was generated from the following file:
scripts/3_Game/ObjectSpawner.c