DayZ: DayZCreatureAI Class Reference
DayZCreatureAI Class Reference
do not process rotations !
Protected Member Functions
proto native DayZAnimalInputController GetInputController ()
proto native void StartCommand_Death (int pType, int pDirection)
proto native void StartCommand_Move ()
proto native void StartCommand_Jump ()
proto native void StartCommand_Attack ()
proto native void StartCommand_Hit (int pType, int pDirection)
proto native DayZAnimalCommandScript StartCommand_Script (DayZAnimalCommandScript pInfectedCommand)
scripted commands
proto native DayZAnimalCommandScript StartCommand_ScriptInst (typename pCallbackClass)
proto native DayZAnimalCommandScript GetCommand_Script ()
proto native void SignalAIAttackStarted ()
proto native void SignalAIAttackEnded ()
void DayZAnimal ()
override bool IsHealthVisible ()
override bool IsAnimal ()
override bool IsInventoryVisible ()
override int GetHideIconMask ()
void CommandHandler (float dt, int currentCommandID, bool currentCommandFinished)
bool HandleDeath (int currentCommandID, DayZAnimalInputController inputController)
bool HandleDamageHit (int currentCommandID)
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
void QueueDamageHit (int type, int direction)
bool ComputeDamageHitParams (EntityAI source, string dmgZone, string ammo, out int type, out int direction)
float ComputeHitDirectionAngleDeg (EntityAI source)
int TranslateHitAngleDegToDirectionIndex (float angleDeg)
int FindComponentDirectionOffset (string component)
void EOnContact (IEntity other, Contact extra)
void RegisterHitComponentsForAI ()
register hit components for AI melee (used by attacking AI)
override string GetHitComponentForAI ()
override string GetDefaultHitComponent ()
override string GetDefaultHitPositionComponent ()
override vector GetDefaultHitPosition ()
vector SetDefaultHitPosition (string pSelection)
float ConvertNonlethalDamage (float damage, DamageType damageType)
Protected Attributes
ref array< ref DayZAIHitComponent > m_HitComponentsForAI
Melee hit components (AI targeting)
string m_DefaultHitComponent
string m_DefaultHitPositionComponent
vector m_DefaultHitPosition
bool m_DamageHitToProcess = false
int m_DamageHitType = 0
int m_DamageHitDirection = 0
Detailed Description
do not process rotations !
Definition at line 572 of file DayZAnimal.c.
Member Function Documentation
CommandHandler()
void DayZCreatureAI::CommandHandler (float dt, int currentCommandID, bool currentCommandFinished) inline protected
for mods
for mods
Definition at line 637 of file DayZAnimal.c.
  {
    DayZAnimalInputController inputController = GetInputController();
    if (ModCommandHandlerBefore(dt, currentCommandID, currentCommandFinished))
      return;
    if (HandleDeath(currentCommandID, inputController))
      return;
    if (currentCommandFinished)
    {
      if (currentCommandID == DayZAnimalConstants.COMMANDID_ATTACK)
        SignalAIAttackEnded();
      StartCommand_Move();
      return;
    }
    if (ModCommandHandlerInside(dt, currentCommandID, currentCommandFinished))
      return;
    if (HandleDamageHit(currentCommandID))
    {
      if (currentCommandID == DayZAnimalConstants.COMMANDID_ATTACK)
        SignalAIAttackEnded();
      return;
    }
    if (currentCommandID == DayZAnimalConstants.COMMANDID_MOVE)
    {
      if (inputController.IsJump())
      {
        StartCommand_Jump();
        return;
      }
      if (inputController.IsAttack())
      {
        StartCommand_Attack();
        SignalAIAttackStarted();
        return;
      }
    }
    if (ModCommandHandlerAfter(dt, currentCommandID, currentCommandFinished))
      return;
  }
References GetInputController(), ModCommandHandlerAfter(), ModCommandHandlerBefore(), ModCommandHandlerInside(), and StartCommand_Move().
ComputeDamageHitParams()
bool DayZCreatureAI::ComputeDamageHitParams (EntityAI source, string dmgZone, string ammo, out int type, out int direction) inline protected
Definition at line 760 of file DayZAnimal.c.
  {
    type = 0; // not used right now
    float angleDeg = ComputeHitDirectionAngleDeg(source);
    direction = TranslateHitAngleDegToDirectionIndex(angleDeg);
    direction += FindComponentDirectionOffset(dmgZone);
    return true;
  }
ComputeHitDirectionAngleDeg()
float DayZCreatureAI::ComputeHitDirectionAngleDeg (EntityAI source) inline protected
Definition at line 772 of file DayZAnimal.c.
  {
    vector targetDirection = GetDirection();
    vector toSourceDirection = (source.GetPosition() - GetPosition());
    targetDirection[1] = 0;
    toSourceDirection[1] = 0;
    targetDirection.Normalize();
    toSourceDirection.Normalize();
    float cosFi = vector.Dot(targetDirection, toSourceDirection);
    vector cross = targetDirection * toSourceDirection;
    float dirAngleDeg = Math.Acos(cosFi) * Math.RAD2DEG;
    if (cross[1] < 0)
      dirAngleDeg = -dirAngleDeg;
    return dirAngleDeg;
  }
References Math::Acos(), vector::Dot(), GetPosition, and Math::RAD2DEG.
ConvertNonlethalDamage()
float DayZCreatureAI::ConvertNonlethalDamage (float damage, DamageType damageType) inline protected
Definition at line 880 of file DayZAnimal.c.
  {
    switch (damageType)
    {
    case DamageType.CLOSE_COMBAT:
      return damage * GameConstants.NL_DAMAGE_CLOSECOMBAT_CONVERSION_ANIMALS;
    case DamageType.FIRE_ARM:
      return damage * GameConstants.NL_DAMAGE_FIREARM_CONVERSION_ANIMALS;
    }
    return super.ConvertNonlethalDamage(damage, damageType);
  }
References GameConstants::NL_DAMAGE_CLOSECOMBAT_CONVERSION_ANIMALS, and GameConstants::NL_DAMAGE_FIREARM_CONVERSION_ANIMALS.
DayZAnimal()
void DayZCreatureAI::DayZAnimal () inline protected
sets default hit position and cache it here (mainly for impact particles)
Definition at line 597 of file DayZAnimal.c.
  {
    // testing: animals have no inventory by default
    //GetInventory().LockInventory(LOCK_FROM_SCRIPT); // Hides animals from vicinity in inventory. Remove this if wanted otherwise.
    m_HitComponentsForAI = new array<ref DayZAIHitComponent>;
    RegisterHitComponentsForAI();
    m_DefaultHitPosition = SetDefaultHitPosition(GetDefaultHitPositionComponent());
  }
References GetDefaultHitPositionComponent(), m_HitComponentsForAI, and RegisterHitComponentsForAI().
EEHitBy()
override void DayZCreatureAI::EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline protected
Definition at line 729 of file DayZAnimal.c.
  {
    super.EEHitBy(damageResult, damageType, source, component, dmgZone, ammo, modelPos, speedCoef);
    m_TransportHitRegistered = false;
    int transferShockToDamageCoef = g_Game.ConfigGetInt(string.Format("%1 %2 DamageApplied transferShockToDamage", CFG_AMMO, ammo));
    if (transferShockToDamageCoef == 1)
    {
      //Print("DayZAnimal | EEHitBy | nonlethal hit");
      AddHealth("", "Health", -ConvertNonlethalDamage(damageResult.GetDamage(dmgZone, "Shock"), damageType));
    }
    else
    {
      ComponentAnimalBleeding animal_bleeding = ComponentAnimalBleeding.Cast(GetComponent(COMP_TYPE_ANIMAL_BLEEDING));
      animal_bleeding.CreateWound(damageResult, dmgZone, ammo);
    }
    int type = 0;
    int direction = 0;
    if (ComputeDamageHitParams(source, dmgZone, ammo, type, direction) == true)
      QueueDamageHit(type, direction);
  }
References CFG_AMMO, COMP_TYPE_ANIMAL_BLEEDING, component, and g_Game.
EOnContact()
void DayZCreatureAI::EOnContact (IEntity other, Contact extra) inline protected
Phx contact event
Definition at line 825 of file DayZAnimal.c.
  {
    if (!IsAlive())
      return;
    Transport transport = Transport.Cast(other);
    if (transport)
    {
      if (GetGame().IsServer())
        RegisterTransportHit(transport);
    }
  }
References GetGame().
FindComponentDirectionOffset()
int DayZCreatureAI::FindComponentDirectionOffset (string component) inline protected
Definition at line 803 of file DayZAnimal.c.
  {
    const int directionCount = 4;
    int offset = 0;
    if (component.Length() == 0)
      offset = 0;
    else if (component == "Zone_Head")
      offset = directionCount;
    else if (component == "Zone_Chest" || component == "Zone_Legs_Front" || component == "Zone_Spine_Front" || component == "Zone_Neck")
      offset = 2 * directionCount;
    else
      offset = 3 * directionCount;
    return offset;
  }
References component.
GetCommand_Script()
proto native DayZAnimalCommandScript DayZCreatureAI::GetCommand_Script () protected
GetDefaultHitComponent()
override string DayZCreatureAI::GetDefaultHitComponent () inline protected
Definition at line 860 of file DayZAnimal.c.
  {
    return m_DefaultHitComponent;
  }
References m_DefaultHitComponent.
GetDefaultHitPosition()
override vector DayZCreatureAI::GetDefaultHitPosition () inline protected
Definition at line 870 of file DayZAnimal.c.
  {
    return m_DefaultHitPosition;
  }
GetDefaultHitPositionComponent()
override string DayZCreatureAI::GetDefaultHitPositionComponent () inline protected
Definition at line 865 of file DayZAnimal.c.
  {
    return m_DefaultHitPositionComponent;
  }
References m_DefaultHitPositionComponent.
GetHideIconMask()
override int DayZCreatureAI::GetHideIconMask () inline protected
Definition at line 625 of file DayZAnimal.c.
  {
    return EInventoryIconVisibility.HIDE_VICINITY;
    /*
      if (IsAlive())
      {
      return EInventoryIconVisibility.HIDE_VICINITY;
      }
      return super.GetHideIconMask();
    */
  }
GetHitComponentForAI()
override string DayZCreatureAI::GetHitComponentForAI () inline protected
Definition at line 850 of file DayZAnimal.c.
  {
    string hitComp;
    if (DayZAIHitComponentHelpers.SelectMostProbableHitComponent(m_HitComponentsForAI, hitComp))
      return hitComp;
    return GetDefaultHitComponent();
  }
References GetDefaultHitComponent(), m_HitComponentsForAI, and DayZAIHitComponentHelpers::SelectMostProbableHitComponent().
GetInputController()
proto native DayZAnimalInputController DayZCreatureAI::GetInputController () protected
HandleDamageHit()
bool DayZCreatureAI::HandleDamageHit (int currentCommandID) inline protected
Definition at line 716 of file DayZAnimal.c.
  {
    if (m_DamageHitToProcess)
    {
      m_DamageHitToProcess = false;
      if (currentCommandID != DayZAnimalConstants.COMMANDID_HIT)
        StartCommand_Hit(m_DamageHitType, m_DamageHitDirection);
      return true;
    }
    return false;
  }
HandleDeath()
bool DayZCreatureAI::HandleDeath (int currentCommandID, DayZAnimalInputController inputController) inline protected
Definition at line 694 of file DayZAnimal.c.
  {
    if (inputController.IsDead())
    {
      if (currentCommandID == DayZAnimalConstants.COMMANDID_DEATH)
        return true;
      if (m_DamageHitToProcess)
      {
        m_DamageHitToProcess = false;
        StartCommand_Death(m_DamageHitType, m_DamageHitDirection);
      }
      else
        StartCommand_Death(0, 0);
      return true;
    }
    return false;
  }
References StartCommand_Death().
IsAnimal()
override bool DayZCreatureAI::IsAnimal () inline protected
Definition at line 615 of file DayZAnimal.c.
  {
    return true;
  }
IsHealthVisible()
override bool DayZCreatureAI::IsHealthVisible () inline protected
Definition at line 610 of file DayZAnimal.c.
  {
    return false;
  }
IsInventoryVisible()
override bool DayZCreatureAI::IsInventoryVisible () inline protected
Definition at line 620 of file DayZAnimal.c.
  {
    return false;
  }
QueueDamageHit()
void DayZCreatureAI::QueueDamageHit (int type, int direction) inline protected
Definition at line 753 of file DayZAnimal.c.
  {
    m_DamageHitToProcess = true;
    m_DamageHitType = type;
    m_DamageHitDirection = direction;
  }
RegisterHitComponentsForAI()
void DayZCreatureAI::RegisterHitComponentsForAI () inline protected
register hit components for AI melee (used by attacking AI)
registers default hit compoent for the entity
registers default hit position component for entity
register hit components that are selected by probability
Definition at line 839 of file DayZAnimal.c.
  {
    m_DefaultHitComponent = "Zone_Chest";
    m_DefaultHitPositionComponent = "Pelvis";
    DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Chest", 50);
  }
References m_DefaultHitComponent, m_DefaultHitPositionComponent, m_HitComponentsForAI, and DayZAIHitComponentHelpers::RegisterHitComponent().
SetDefaultHitPosition()
vector DayZCreatureAI::SetDefaultHitPosition (string pSelection) inline protected
Definition at line 875 of file DayZAnimal.c.
  {
    return GetSelectionPositionMS(pSelection);
  }
SignalAIAttackEnded()
proto native void DayZCreatureAI::SignalAIAttackEnded () protected
SignalAIAttackStarted()
proto native void DayZCreatureAI::SignalAIAttackStarted () protected
StartCommand_Attack()
proto native void DayZCreatureAI::StartCommand_Attack () protected
StartCommand_Death()
proto native void DayZCreatureAI::StartCommand_Death (int pType, int pDirection) protected
StartCommand_Hit()
proto native void DayZCreatureAI::StartCommand_Hit (int pType, int pDirection) protected
StartCommand_Jump()
proto native void DayZCreatureAI::StartCommand_Jump () protected
StartCommand_Move()
proto native void DayZCreatureAI::StartCommand_Move () protected
StartCommand_Script()
proto native DayZAnimalCommandScript DayZCreatureAI::StartCommand_Script (DayZAnimalCommandScript pInfectedCommand) protected
scripted commands
StartCommand_ScriptInst()
proto native DayZAnimalCommandScript DayZCreatureAI::StartCommand_ScriptInst (typename pCallbackClass) protected
TranslateHitAngleDegToDirectionIndex()
int DayZCreatureAI::TranslateHitAngleDegToDirectionIndex (float angleDeg) inline protected
Definition at line 793 of file DayZAnimal.c.
  {
    if (angleDeg >= -20 && angleDeg <= 20) // front
      return 1;
    else if (angleDeg < 0) // left
      return 2;
    return 3; // right
  }
Member Data Documentation
m_DamageHitDirection
int DayZCreatureAI::m_DamageHitDirection = 0 protected
Definition at line 692 of file DayZAnimal.c.
m_DamageHitToProcess
bool DayZCreatureAI::m_DamageHitToProcess = false protected
Definition at line 690 of file DayZAnimal.c.
m_DamageHitType
int DayZCreatureAI::m_DamageHitType = 0 protected
Definition at line 691 of file DayZAnimal.c.
m_DefaultHitComponent
string DayZCreatureAI::m_DefaultHitComponent protected
Definition at line 577 of file DayZAnimal.c.
m_DefaultHitPosition
vector DayZCreatureAI::m_DefaultHitPosition protected
Definition at line 579 of file DayZAnimal.c.
m_DefaultHitPositionComponent
string DayZCreatureAI::m_DefaultHitPositionComponent protected
Definition at line 578 of file DayZAnimal.c.
m_HitComponentsForAI
ref array<ref DayZAIHitComponent> DayZCreatureAI::m_HitComponentsForAI protected
Melee hit components (AI targeting)
Definition at line 576 of file DayZAnimal.c.
The documentation for this class was generated from the following file:
scripts/3_Game/Entities/DayZAnimal.c