DayZ: scripts/4_World/Entities/DayZPlayerImplementFallDamage.c File Reference
DayZPlayerImplementFallDamage.c File Reference
Classes
class FallDamageData
Functions
void DayZPlayerImplementFallDamage (DayZPlayer pPlayer)
float GetHeight ()
int GetLandType ()
void HandleFallDamage (FallDamageData pData)
float Randomize (int pType, float pValue)
void AttachBleedingToZonesByHeight (notnull PlayerBase pPlayer)
void DamageAttachedGear (notnull PlayerBase pPlayer)
void HandleFallDamage (float pHeight)
float DamageCoef (float pHeight)
Variables
class FallDamageData FALL_DAMAGE_AMMO_HEALTH = "FallDamageHealth"
static const string FALL_DAMAGE_AMMO_SHOCK = "FallDamageShock"
static const string FALL_DAMAGE_AMMO_HEALTH_ATTACHMENT = "FallDamageHealthAttachment"
static const string FALL_DAMAGE_AMMO_HEALTH_OTHER_ATTACHMENTS = "FallDamageHealthOtherAttachments"
const float HEALTH_HEIGHT_LOW = 5
const float HEALTH_HEIGHT_HIGH = 14
const float SHOCK_HEIGHT_LOW = 3
const float SHOCK_HEIGHT_HIGH = 12
const float BROKENLEGS_HEIGHT_LOW = 5
const float BROKENLEGS_HEIGHT_HIGH = 9
const float GLOVES_HEALTH_HEIGHT_LOW = 5
const float GLOVES_HEALTH_HEIGHT_HIGH = 15
const float SHOES_HEALTH_HEIGHT_LOW = 2
const float SHOES_HEALTH_HEIGHT_HIGH = 15
const float PANTS_HEALTH_HEIGHT_LOW = 5
const float PANTS_HEALTH_HEIGHT_HIGH = 16
const float BLEEDINGHANDS_HEIGHT_LOW = 5
const float BLEEDINGFEET_HEIGHT_LOW = 3
const float BLEEDINGLEGS_HEIGHT_LOW = 10
const float RANDOM_THRESHOLD_HEALTH_LOW = 0.05
const float RANDOM_THRESHOLD_HEALTH_HIGH = 0.1
const float RANDOM_THRESHOLD_LEGS_LOW = 0.05
const float RANDOM_THRESHOLD_LEGS_HIGH = 0.1
const float RANDOM_THRESHOLD_ATTACHMENTS_LOW = 0
const float RANDOM_THRESHOLD_ATTACHMENTS_HIGH = 0.2
const float BLEEDING_CHANCE_HEIGHT_LOW = 3
const float BLEEDING_CHANCE_HEIGHT_HIGH = 15
static const float BROKENLEGS_HEALTH_DAMAGE_MAX = 125
static const string BLEEDING_HANDS_SELECTIONS [2] = {"LeftForeArmRoll", "RightForeArmRoll"}
static const string BLEEDING_FEET_SELECTIONS [2] = {"LeftFoot", "RightFoot"}
static const string BLEEDING_LEGS_SELECTIONS [2] = {"LeftLeg", "RightLeg"}
const int DAMAGE_TYPE_GLOBAL = 0
const int DAMAGE_TYPE_LEGS = 1
const int DAMAGE_TYPE_ATTACHMENTS = 2
DayZPlayer m_Player
ref FallDamageData m_FallDamageData
const string FD_AMMO = "FallDamage"
ammo type used for damaging
const float FD_DMG_FROM_HEIGHT = 2.5
damage will not be taken into account bellow this HeightToDamage
const float FD_MAX_DMG_AT_HEIGHT = 15
height where player gets 100% damage
const float FD_MAX_HEIGHT_LEG_BREAK = 8
height where legs break most of the time
Function Documentation
AttachBleedingToZonesByHeight()
void AttachBleedingToZonesByHeight (notnull PlayerBase pPlayer) private
Definition at line 179 of file DayZPlayerImplementFallDamage.c.
  {
    Math.Randomize(GetGame().GetTime());
    int bleedingSelectionIndex;
    BleedingSourcesManagerServer bleedingManager = pPlayer.GetBleedingManagerServer();
    if (Math.RandomFloatInclusive(0.0, 1.0) <= m_FallDamageData.m_BleedingChanceCoef && m_FallDamageData.m_BleedingHandsCoef == 1.0 && pPlayer.FindAttachmentBySlotName("Gloves") == null)
    {
      bleedingSelectionIndex = Math.RandomInt(0, 2);
      bleedingManager.AttemptAddBleedingSourceBySelection(BLEEDING_HANDS_SELECTIONS[bleedingSelectionIndex]);
    }
    if (Math.RandomFloatInclusive(0.0, 1.0) <= m_FallDamageData.m_BleedingChanceCoef && m_FallDamageData.m_BleedingFeetCoef == 1.0 && pPlayer.FindAttachmentBySlotName("Feet") == null)
    {
      bleedingSelectionIndex = Math.RandomInt(0, 2);
      bleedingManager.AttemptAddBleedingSourceBySelection(BLEEDING_FEET_SELECTIONS[bleedingSelectionIndex]);
    }
    if (Math.RandomFloatInclusive(0.0, 1.0) <= m_FallDamageData.m_BleedingChanceLegsCoef && m_FallDamageData.m_BleedingLegsCoef == 1.0)
    {
      bleedingSelectionIndex = Math.RandomInt(0, 2);
      bleedingManager.AttemptAddBleedingSourceBySelection(BLEEDING_LEGS_SELECTIONS[bleedingSelectionIndex]);
    }
  }
References BLEEDING_FEET_SELECTIONS, BLEEDING_HANDS_SELECTIONS, BLEEDING_LEGS_SELECTIONS, GetGame(), GetTime(), m_FallDamageData, Math::RandomFloatInclusive(), Math::RandomInt(), and Math::Randomize().
Referenced by HandleFallDamage().
DamageAttachedGear()
void DamageAttachedGear (notnull PlayerBase pPlayer) private
Definition at line 205 of file DayZPlayerImplementFallDamage.c.
  {
    EntityAI gloves = pPlayer.FindAttachmentBySlotName("Gloves");
    if (gloves)
      gloves.ProcessDirectDamage(DT_CUSTOM, pPlayer, "", FALL_DAMAGE_AMMO_HEALTH_OTHER_ATTACHMENTS, gloves.WorldToModel(gloves.GetPosition()), m_FallDamageData.m_GlovesHealthCoef);
    EntityAI shoes = pPlayer.FindAttachmentBySlotName("Feet");
    if (shoes)
      shoes.ProcessDirectDamage(DT_CUSTOM, pPlayer, "", FALL_DAMAGE_AMMO_HEALTH_OTHER_ATTACHMENTS, shoes.WorldToModel(shoes.GetPosition()), m_FallDamageData.m_ShoesHealthCoef);
    EntityAI pants = pPlayer.FindAttachmentBySlotName("Legs");
    if (pants)
      pants.ProcessDirectDamage(DT_CUSTOM, pPlayer, "", FALL_DAMAGE_AMMO_HEALTH_ATTACHMENT, pants.WorldToModel(pants.GetPosition()), m_FallDamageData.m_PantsHealthCoef);
  }
References FALL_DAMAGE_AMMO_HEALTH_ATTACHMENT, FALL_DAMAGE_AMMO_HEALTH_OTHER_ATTACHMENTS, and m_FallDamageData.
Referenced by HandleFallDamage().
DamageCoef()
float DamageCoef (float pHeight) private
DayZPlayerImplementFallDamage()
void DayZPlayerImplementFallDamage (DayZPlayer pPlayer) private
Definition at line 73 of file DayZPlayerImplementFallDamage.c.
  {
    m_Player = pPlayer;
    m_FallDamageData = new FallDamageData();
#ifdef DIAG_DEVELOPER
    PreloadAmmoTypeData();
#endif
  }
References m_FallDamageData, and m_Player.
Referenced by DayZPlayer::CommandHandler(), DayZPlayer::DayZPlayerImplement(), and PluginBase::PlayerHitBy().
GetHeight()
float GetHeight () private
Definition at line 83 of file DayZPlayerImplementFallDamage.c.
  {
    return m_FallDamageData.m_Height;
  }
References m_FallDamageData.
GetLandType()
int GetLandType () private
Definition at line 88 of file DayZPlayerImplementFallDamage.c.
  {
    return m_FallDamageData.m_LandType;
  }
References m_FallDamageData.
HandleFallDamage() [1/2]
void HandleFallDamage (FallDamageData pData) private
Definition at line 93 of file DayZPlayerImplementFallDamage.c.
  {
    m_FallDamageData = pData;
    m_FallDamageData.m_HealthCoef = Math.InverseLerp(HEALTH_HEIGHT_LOW, HEALTH_HEIGHT_HIGH, pData.m_Height);
    m_FallDamageData.m_HealthCoef = Randomize(DAMAGE_TYPE_GLOBAL, m_FallDamageData.m_HealthCoef);
    m_FallDamageData.m_HealthCoef = Math.Clamp(m_FallDamageData.m_HealthCoef, 0, 1);
    m_FallDamageData.m_ShockCoef = Math.InverseLerp(SHOCK_HEIGHT_LOW, SHOCK_HEIGHT_HIGH, pData.m_Height);
    m_FallDamageData.m_ShockCoef = Math.Clamp(m_FallDamageData.m_ShockCoef, 0, 1);
    m_FallDamageData.m_BrokenLegsCoef = Math.InverseLerp(BROKENLEGS_HEIGHT_LOW, BROKENLEGS_HEIGHT_HIGH, pData.m_Height);
    m_FallDamageData.m_BrokenLegsCoef = Randomize(DAMAGE_TYPE_LEGS, m_FallDamageData.m_BrokenLegsCoef);
    m_FallDamageData.m_BrokenLegsCoef = Math.Clamp(m_FallDamageData.m_BrokenLegsCoef, 0, 1);
    m_FallDamageData.m_BleedingHandsCoef = Math.InverseLerp(0, BLEEDINGHANDS_HEIGHT_LOW, pData.m_Height);
    m_FallDamageData.m_BleedingHandsCoef = Math.Clamp(m_FallDamageData.m_BleedingHandsCoef, 0, 1);
    m_FallDamageData.m_BleedingFeetCoef = Math.InverseLerp(0, BLEEDINGFEET_HEIGHT_LOW, pData.m_Height);
    m_FallDamageData.m_BleedingFeetCoef = Math.Clamp(m_FallDamageData.m_BleedingFeetCoef, 0, 1);
    m_FallDamageData.m_BleedingLegsCoef = Math.InverseLerp(0, BLEEDINGLEGS_HEIGHT_LOW, pData.m_Height);
    m_FallDamageData.m_BleedingLegsCoef = Math.Clamp(m_FallDamageData.m_BleedingLegsCoef, 0, 1);
    m_FallDamageData.m_GlovesHealthCoef = Math.InverseLerp(GLOVES_HEALTH_HEIGHT_LOW, GLOVES_HEALTH_HEIGHT_HIGH, pData.m_Height);
    m_FallDamageData.m_GlovesHealthCoef = Randomize(DAMAGE_TYPE_ATTACHMENTS, m_FallDamageData.m_GlovesHealthCoef);
    m_FallDamageData.m_GlovesHealthCoef = Math.Clamp(m_FallDamageData.m_GlovesHealthCoef, 0, 1);
    m_FallDamageData.m_ShoesHealthCoef = Math.InverseLerp(SHOES_HEALTH_HEIGHT_LOW, SHOES_HEALTH_HEIGHT_HIGH, pData.m_Height);
    m_FallDamageData.m_ShoesHealthCoef = Randomize(DAMAGE_TYPE_ATTACHMENTS, m_FallDamageData.m_ShoesHealthCoef);
    m_FallDamageData.m_ShoesHealthCoef = Math.Clamp(m_FallDamageData.m_ShoesHealthCoef, 0, 1);
    m_FallDamageData.m_PantsHealthCoef = Math.InverseLerp(PANTS_HEALTH_HEIGHT_LOW, PANTS_HEALTH_HEIGHT_HIGH, pData.m_Height);
    m_FallDamageData.m_PantsHealthCoef = Randomize(DAMAGE_TYPE_ATTACHMENTS, m_FallDamageData.m_PantsHealthCoef);
    m_FallDamageData.m_PantsHealthCoef = Math.Clamp(m_FallDamageData.m_PantsHealthCoef, 0, 1);
    m_FallDamageData.m_BleedingChanceCoef = Math.InverseLerp(BLEEDING_CHANCE_HEIGHT_LOW, BLEEDING_CHANCE_HEIGHT_HIGH, pData.m_Height);
    m_FallDamageData.m_BleedingChanceCoef = Math.Clamp(m_FallDamageData.m_BleedingChanceCoef, 0, 0.7);
    m_FallDamageData.m_BleedingChanceLegsCoef = 0.15;
    if (GetGame().IsServer())
    {
      PlayerBase playerBase = PlayerBase.Cast(m_Player);
      if (playerBase)
      {
        AttachBleedingToZonesByHeight(playerBase);
        DamageAttachedGear(playerBase);
        playerBase.DamageAllLegs(BROKENLEGS_HEALTH_DAMAGE_MAX * m_FallDamageData.m_BrokenLegsCoef);
      }
      vector posMS = m_Player.WorldToModel(m_Player.GetPosition());
      m_Player.ProcessDirectDamage(DamageType.CUSTOM, m_Player, "", FALL_DAMAGE_AMMO_HEALTH, posMS, m_FallDamageData.m_HealthCoef);
      m_Player.ProcessDirectDamage(DamageType.CUSTOM, m_Player, "", FALL_DAMAGE_AMMO_SHOCK, posMS, m_FallDamageData.m_ShockCoef);
      if (playerBase)
        playerBase.ForceUpdateInjuredState();
    }
  }
References AttachBleedingToZonesByHeight(), BLEEDING_CHANCE_HEIGHT_HIGH, BLEEDING_CHANCE_HEIGHT_LOW, BLEEDINGFEET_HEIGHT_LOW, BLEEDINGHANDS_HEIGHT_LOW, BLEEDINGLEGS_HEIGHT_LOW, BROKENLEGS_HEALTH_DAMAGE_MAX, BROKENLEGS_HEIGHT_HIGH, BROKENLEGS_HEIGHT_LOW, Math::Clamp(), DAMAGE_TYPE_ATTACHMENTS, DAMAGE_TYPE_GLOBAL, DAMAGE_TYPE_LEGS, DamageAttachedGear(), FALL_DAMAGE_AMMO_HEALTH, FALL_DAMAGE_AMMO_SHOCK, GetGame(), GLOVES_HEALTH_HEIGHT_HIGH, GLOVES_HEALTH_HEIGHT_LOW, HEALTH_HEIGHT_HIGH, HEALTH_HEIGHT_LOW, Math::InverseLerp(), m_FallDamageData, m_Player, PANTS_HEALTH_HEIGHT_HIGH, PANTS_HEALTH_HEIGHT_LOW, Randomize(), SHOCK_HEIGHT_HIGH, SHOCK_HEIGHT_LOW, SHOES_HEALTH_HEIGHT_HIGH, and SHOES_HEALTH_HEIGHT_LOW.
HandleFallDamage() [2/2]
void HandleFallDamage (float pHeight) private
Randomize()
float Randomize (int pType, float pValue) private
Definition at line 154 of file DayZPlayerImplementFallDamage.c.
  {
    Math.Randomize(GetGame().GetTime());
    int randomizedSign = -1;
    if (Math.RandomIntInclusive(1, 2) % 2 == 1)
      randomizedSign = 1;
    float randomizationValue = 0;
    switch (pType)
    {
    case DAMAGE_TYPE_GLOBAL:
      randomizationValue = Math.RandomFloatInclusive(RANDOM_THRESHOLD_HEALTH_LOW, RANDOM_THRESHOLD_HEALTH_HIGH);
      break;
    case DAMAGE_TYPE_LEGS:
      randomizationValue = Math.RandomFloatInclusive(RANDOM_THRESHOLD_LEGS_LOW, RANDOM_THRESHOLD_LEGS_HIGH);
      break;
    case DAMAGE_TYPE_ATTACHMENTS:
      randomizationValue = Math.RandomFloatInclusive(RANDOM_THRESHOLD_ATTACHMENTS_LOW, RANDOM_THRESHOLD_ATTACHMENTS_HIGH);
      break;
    }
    return pValue + (randomizedSign * pValue * randomizationValue);
  }
References DAMAGE_TYPE_ATTACHMENTS, DAMAGE_TYPE_GLOBAL, DAMAGE_TYPE_LEGS, GetGame(), GetTime(), RANDOM_THRESHOLD_ATTACHMENTS_HIGH, RANDOM_THRESHOLD_ATTACHMENTS_LOW, RANDOM_THRESHOLD_HEALTH_HIGH, RANDOM_THRESHOLD_HEALTH_LOW, RANDOM_THRESHOLD_LEGS_HIGH, RANDOM_THRESHOLD_LEGS_LOW, Math::RandomFloatInclusive(), Math::RandomIntInclusive(), and Math::Randomize().
Referenced by HandleFallDamage().
Variable Documentation
BLEEDING_CHANCE_HEIGHT_HIGH
const float BLEEDING_CHANCE_HEIGHT_HIGH = 15 private
Definition at line 53 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
BLEEDING_CHANCE_HEIGHT_LOW
const float BLEEDING_CHANCE_HEIGHT_LOW = 3 private
Definition at line 52 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
BLEEDING_FEET_SELECTIONS
const string BLEEDING_FEET_SELECTIONS[2] = {"LeftFoot", "RightFoot"} static private
Definition at line 58 of file DayZPlayerImplementFallDamage.c.
{"LeftFoot", "RightFoot"};
Referenced by AttachBleedingToZonesByHeight().
BLEEDING_HANDS_SELECTIONS
const string BLEEDING_HANDS_SELECTIONS[2] = {"LeftForeArmRoll", "RightForeArmRoll"} static private
Definition at line 57 of file DayZPlayerImplementFallDamage.c.
{"LeftForeArmRoll", "RightForeArmRoll"};
Referenced by AttachBleedingToZonesByHeight().
BLEEDING_LEGS_SELECTIONS
const string BLEEDING_LEGS_SELECTIONS[2] = {"LeftLeg", "RightLeg"} static private
Definition at line 59 of file DayZPlayerImplementFallDamage.c.
{"LeftLeg", "RightLeg"};
Referenced by AttachBleedingToZonesByHeight().
BLEEDINGFEET_HEIGHT_LOW
const float BLEEDINGFEET_HEIGHT_LOW = 3 private
Definition at line 42 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
BLEEDINGHANDS_HEIGHT_LOW
const float BLEEDINGHANDS_HEIGHT_LOW = 5 private
Definition at line 41 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
BLEEDINGLEGS_HEIGHT_LOW
const float BLEEDINGLEGS_HEIGHT_LOW = 10 private
Definition at line 43 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
BROKENLEGS_HEALTH_DAMAGE_MAX
const float BROKENLEGS_HEALTH_DAMAGE_MAX = 125 static private
Definition at line 55 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
BROKENLEGS_HEIGHT_HIGH
const float BROKENLEGS_HEIGHT_HIGH = 9 private
Definition at line 32 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
BROKENLEGS_HEIGHT_LOW
const float BROKENLEGS_HEIGHT_LOW = 5 private
Definition at line 31 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
DAMAGE_TYPE_ATTACHMENTS
const int DAMAGE_TYPE_ATTACHMENTS = 2 private
Definition at line 63 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage(), and Randomize().
DAMAGE_TYPE_GLOBAL
const int DAMAGE_TYPE_GLOBAL = 0 private
Definition at line 61 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage(), and Randomize().
DAMAGE_TYPE_LEGS
const int DAMAGE_TYPE_LEGS = 1 private
Definition at line 62 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage(), and Randomize().
FALL_DAMAGE_AMMO_HEALTH
class FallDamageData FALL_DAMAGE_AMMO_HEALTH = "FallDamageHealth"
Referenced by HandleFallDamage().
FALL_DAMAGE_AMMO_HEALTH_ATTACHMENT
const string FALL_DAMAGE_AMMO_HEALTH_ATTACHMENT = "FallDamageHealthAttachment" static
Definition at line 23 of file DayZPlayerImplementFallDamage.c.
Referenced by DamageAttachedGear().
FALL_DAMAGE_AMMO_HEALTH_OTHER_ATTACHMENTS
const string FALL_DAMAGE_AMMO_HEALTH_OTHER_ATTACHMENTS = "FallDamageHealthOtherAttachments" static
Definition at line 24 of file DayZPlayerImplementFallDamage.c.
Referenced by DamageAttachedGear().
FALL_DAMAGE_AMMO_SHOCK
const string FALL_DAMAGE_AMMO_SHOCK = "FallDamageShock" static
Definition at line 21 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
FD_AMMO
const string FD_AMMO = "FallDamage" private
ammo type used for damaging
DEPRECATED
Definition at line 326 of file DayZPlayerImplementFallDamage.c.
FD_DMG_FROM_HEIGHT
const float FD_DMG_FROM_HEIGHT = 2.5 private
damage will not be taken into account bellow this HeightToDamage
Definition at line 327 of file DayZPlayerImplementFallDamage.c.
FD_MAX_DMG_AT_HEIGHT
const float FD_MAX_DMG_AT_HEIGHT = 15 private
height where player gets 100% damage
Definition at line 328 of file DayZPlayerImplementFallDamage.c.
FD_MAX_HEIGHT_LEG_BREAK
const float FD_MAX_HEIGHT_LEG_BREAK = 8 private
height where legs break most of the time
Definition at line 329 of file DayZPlayerImplementFallDamage.c.
GLOVES_HEALTH_HEIGHT_HIGH
const float GLOVES_HEALTH_HEIGHT_HIGH = 15 private
Definition at line 35 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
GLOVES_HEALTH_HEIGHT_LOW
const float GLOVES_HEALTH_HEIGHT_LOW = 5 private
Definition at line 34 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
HEALTH_HEIGHT_HIGH
const float HEALTH_HEIGHT_HIGH = 14
Definition at line 27 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
HEALTH_HEIGHT_LOW
const float HEALTH_HEIGHT_LOW = 5
Definition at line 26 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
m_FallDamageData
ref FallDamageData m_FallDamageData private
Definition at line 66 of file DayZPlayerImplementFallDamage.c.
Referenced by AttachBleedingToZonesByHeight(), DamageAttachedGear(), DayZPlayerImplementFallDamage(), GetHeight(), GetLandType(), and HandleFallDamage().
m_Player
DayZPlayer m_Player private
Definition at line 65 of file DayZPlayerImplementFallDamage.c.
PANTS_HEALTH_HEIGHT_HIGH
const float PANTS_HEALTH_HEIGHT_HIGH = 16 private
Definition at line 39 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
PANTS_HEALTH_HEIGHT_LOW
const float PANTS_HEALTH_HEIGHT_LOW = 5 private
Definition at line 38 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
RANDOM_THRESHOLD_ATTACHMENTS_HIGH
const float RANDOM_THRESHOLD_ATTACHMENTS_HIGH = 0.2 private
Definition at line 50 of file DayZPlayerImplementFallDamage.c.
Referenced by Randomize().
RANDOM_THRESHOLD_ATTACHMENTS_LOW
const float RANDOM_THRESHOLD_ATTACHMENTS_LOW = 0 private
Definition at line 49 of file DayZPlayerImplementFallDamage.c.
Referenced by Randomize().
RANDOM_THRESHOLD_HEALTH_HIGH
const float RANDOM_THRESHOLD_HEALTH_HIGH = 0.1 private
Definition at line 46 of file DayZPlayerImplementFallDamage.c.
Referenced by Randomize().
RANDOM_THRESHOLD_HEALTH_LOW
const float RANDOM_THRESHOLD_HEALTH_LOW = 0.05 private
Definition at line 45 of file DayZPlayerImplementFallDamage.c.
Referenced by Randomize().
RANDOM_THRESHOLD_LEGS_HIGH
const float RANDOM_THRESHOLD_LEGS_HIGH = 0.1 private
Definition at line 48 of file DayZPlayerImplementFallDamage.c.
Referenced by Randomize().
RANDOM_THRESHOLD_LEGS_LOW
const float RANDOM_THRESHOLD_LEGS_LOW = 0.05 private
Definition at line 47 of file DayZPlayerImplementFallDamage.c.
Referenced by Randomize().
SHOCK_HEIGHT_HIGH
const float SHOCK_HEIGHT_HIGH = 12 private
Definition at line 30 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
SHOCK_HEIGHT_LOW
const float SHOCK_HEIGHT_LOW = 3 private
Definition at line 29 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
SHOES_HEALTH_HEIGHT_HIGH
const float SHOES_HEALTH_HEIGHT_HIGH = 15 private
Definition at line 37 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
SHOES_HEALTH_HEIGHT_LOW
const float SHOES_HEALTH_HEIGHT_LOW = 2 private
Definition at line 36 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().