DayZ: ActionLoadMagazineQuick Class Reference
ActionLoadMagazineQuick Class Reference
Private Member Functions
void ActionLoadMagazineQuick ()
override bool HasProneException ()
override GetInputType ()
override void CreateConditionComponents ()
override bool HasTarget ()
bool CanLoadMagazine (PlayerBase player, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteServer (ActionData action_data)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 90 of file ActionLoadMagazine.c.
Constructor & Destructor Documentation
ActionLoadMagazineQuick()
void ActionLoadMagazineQuick::ActionLoadMagazineQuick () inline private
Definition at line 92 of file ActionLoadMagazine.c.
  {
    m_CallbackClass = ActionLoadMagazineQuickCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_FILLMAG;
    m_CommandUIDProne = DayZPlayerConstants.CMD_ACTIONFB_FILLMAG;
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, and AnimatedActionBase::m_CommandUIDProne.
Member Function Documentation
ActionCondition()
override bool ActionLoadMagazineQuick::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 132 of file ActionLoadMagazine.c.
  {
    return CanLoadMagazine(player, item);
  }
References CanLoadMagazine().
ActionConditionContinue()
override bool ActionLoadMagazineQuick::ActionConditionContinue (ActionData action_data) inline private
Definition at line 127 of file ActionLoadMagazine.c.
  {
    return CanLoadMagazine(action_data.m_Player, action_data.m_MainItem);
  }
References CanLoadMagazine().
CanLoadMagazine()
bool ActionLoadMagazineQuick::CanLoadMagazine (PlayerBase player, ItemBase item) inline private
Definition at line 120 of file ActionLoadMagazine.c.
  {
    Magazine mag = Magazine.Cast(item);
    return mag && player.GetWeaponManager().GetPreparedMagazine() != null && mag.GetAmmoCount() < mag.GetAmmoMax();
  }
Referenced by ActionCondition(), and ActionConditionContinue().
CreateConditionComponents()
override void ActionLoadMagazineQuick::CreateConditionComponents () inline private
Definition at line 109 of file ActionLoadMagazine.c.
  {
    m_ConditionItem = new CCINonRuined();
    m_ConditionTarget = new CCTSelf;
  }
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override ActionLoadMagazineQuick::GetInputType () inline private
Definition at line 104 of file ActionLoadMagazine.c.
  {
    return ContinuousWeaponManipulationActionInput;
  }
HasProneException()
override bool ActionLoadMagazineQuick::HasProneException () inline private
Definition at line 99 of file ActionLoadMagazine.c.
  {
    return true;
  }
HasTarget()
override bool ActionLoadMagazineQuick::HasTarget () inline private
Definition at line 115 of file ActionLoadMagazine.c.
  {
    return false;
  }
OnExecuteServer()
override void ActionLoadMagazineQuick::OnExecuteServer (ActionData action_data) inline private
Definition at line 137 of file ActionLoadMagazine.c.
  {
    //Param1<float> timeSpendParam;
    //if( !Class.CastTo(timeSpendParam, action_data.m_ActionComponent.GetACData()) ) return;
    Magazine itm = Magazine.Cast(action_data.m_MainItem);
    Magazine trg = action_data.m_Player.GetWeaponManager().GetPreparedMagazine();
    if (!itm || !trg)
      return;
    float dmg;
    string ammoType;
    if (trg.ServerAcquireCartridge(dmg, ammoType))
    {
      if (!itm.ServerStoreCartridge(dmg, ammoType))
        trg.ServerStoreCartridge(dmg, ammoType);
      else
        itm.ApplyManipulationDamage(); //damages magazine
    }
    trg.SetSynchDirty();
    itm.SetSynchDirty();
    //manipulationDamage
    //if(trg.GetAmmoCount() > 0 )
    //trg.SetSynchDirty();
    //itm.SetSynchDirty();
  }
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionLoadMagazine.c