DayZ: NotificationSystem Class Reference
NotificationSystem Class Reference
Protected Member Functions
void NotificationSystem ()
NotificationData GetNotificationData (NotificationType type)
Static Protected Member Functions
static void InitInstance ()
static void CleanupInstance ()
static NotificationSystem GetInstance ()
static void SendNotificationToPlayerExtended (Man player, float show_time, string title_text, string detail_text="", string icon="")
Send custom notification to player from server.
static void SendNotificationToPlayerIdentityExtended (PlayerIdentity player, float show_time, string title_text, string detail_text="", string icon="")
Send custom notification to player identity from server.
static void SendNotificationToPlayer (Man player, NotificationType type, float show_time, string detail_text="")
Send notification from default types to player from server.
static void SendNotificationToPlayerIdentity (PlayerIdentity player, NotificationType type, float show_time, string detail_text="")
Send notification from default types to player identity from server.
static void AddNotification (NotificationType type, float show_time, string detail_text="")
Send notification from default types to local player.
static void AddNotificationExtended (float show_time, string title_text, string detail_text="", string icon="")
Send custom notification from to local player.
static void Update (float timeslice)
static void LoadNotificationData ()
Protected Attributes
ref array< ref NotificationRuntimeData > m_TimeArray
ref array< ref NotificationRuntimeData > m_DeferredArray
ref map< NotificationType, ref NotificationData > m_DataArray
float m_TimeElapsed
ref ScriptInvoker m_OnNotificationAdded = new ScriptInvoker()
ref ScriptInvoker m_OnNotificationRemoved = new ScriptInvoker()
Static Protected Attributes
static const string JSON_FILE_PATH = "scripts/data/notifications.json"
static const int MAX_NOTIFICATIONS = 5
static ref NotificationSystem m_Instance
Private Attributes
const int DEFAULT_TIME_DISPLAYED = 10
const float NOTIFICATION_FADE_TIME = 3.0
Static Private Attributes
static const float UPDATE_INTERVAL_THRESHOLD = 1.0
Detailed Description
Definition at line 69 of file NotificationSystem.c.
Constructor & Destructor Documentation
NotificationSystem()
void NotificationSystem::NotificationSystem () inline protected
Definition at line 109 of file NotificationSystem.c.
  {
    m_TimeElapsed = 0.0;
    m_TimeArray = new array<ref NotificationRuntimeData>();
    m_DeferredArray = new array<ref NotificationRuntimeData>();
  }
References m_DeferredArray, m_TimeArray, and m_TimeElapsed.
Referenced by InitInstance().
Member Function Documentation
AddNotification()
static void NotificationSystem::AddNotification (NotificationType type, float show_time, string detail_text = "") inline static protected
Send notification from default types to local player.
Parameters
type the type of notification to send - these can be viewed in /Scripts/Data/Notifications.json
show_time amount of time this notification is displayed
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
Definition at line 188 of file NotificationSystem.c.
  {
    if (m_Instance.m_TimeArray.Count() < MAX_NOTIFICATIONS)
    {
      NotificationRuntimeData data = new NotificationRuntimeData(show_time, m_Instance.GetNotificationData(type), detail_text);
      m_Instance.m_TimeArray.Insert(data);
      m_Instance.m_OnNotificationAdded.Invoke(data);
    }
    else
    {
      NotificationRuntimeData dataDeferred = new NotificationRuntimeData(show_time, m_Instance.GetNotificationData(type), detail_text);
      m_Instance.m_DeferredArray.Insert(dataDeferred);
    }
  }
References m_Instance, MAX_NOTIFICATIONS, and NotificationRuntimeData().
Referenced by CGame::DisconnectSessionEx(), OnlineServices::OnFriendsAsync(), BiosSessionService::OnGetGameplaySession(), CGame::OnRPC(), and BiosUserManager::SelectUserEx().
AddNotificationExtended()
static void NotificationSystem::AddNotificationExtended (float show_time, string title_text, string detail_text = "", string icon = "") inline static protected
Send custom notification from to local player.
Parameters
show_time amount of time this notification is displayed
title_text the title text that is displayed in the notification
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
icon the icon that is displayed in the notification - will use default icon if not set
Definition at line 211 of file NotificationSystem.c.
  {
    if (m_Instance.m_TimeArray.Count() < MAX_NOTIFICATIONS)
    {
      NotificationData tempData = new NotificationData(icon, title_text);
      NotificationRuntimeData data = new NotificationRuntimeData(show_time, tempData, detail_text);
      m_Instance.m_TimeArray.Insert(data);
      m_Instance.m_OnNotificationAdded.Invoke(data);
    }
    else
    {
      NotificationData tempDataDeferred = new NotificationData(icon, title_text);
      NotificationRuntimeData dataDeferred = new NotificationRuntimeData(show_time, tempDataDeferred, detail_text);
      m_Instance.m_DeferredArray.Insert(dataDeferred);
    }
  }
References m_Instance, MAX_NOTIFICATIONS, and NotificationRuntimeData().
Referenced by CGame::OnRPC().
CleanupInstance()
static void NotificationSystem::CleanupInstance () inline static protected
Definition at line 99 of file NotificationSystem.c.
  {
    m_Instance = null;
  }
References m_Instance.
Referenced by CGame::~DayZGame().
GetInstance()
static NotificationSystem NotificationSystem::GetInstance () inline static protected
Definition at line 104 of file NotificationSystem.c.
  {
    return m_Instance;
  }
References m_Instance.
Referenced by NotificationUI::NotificationUI(), and NotificationUI::~NotificationUI().
GetNotificationData()
NotificationData NotificationSystem::GetNotificationData (NotificationType type) inline protected
Definition at line 268 of file NotificationSystem.c.
  {
    if (m_DataArray.Contains(type))
      return m_DataArray.Get(type);
    return null;
  }
References m_DataArray.
InitInstance()
static void NotificationSystem::InitInstance () inline static protected
Definition at line 90 of file NotificationSystem.c.
  {
    if (!m_Instance)
    {
      m_Instance = new NotificationSystem();
      m_Instance.LoadNotificationData();
    }
  }
References m_Instance, and NotificationSystem().
Referenced by CGame::InitNotifications().
LoadNotificationData()
static void NotificationSystem::LoadNotificationData () inline static protected
Definition at line 276 of file NotificationSystem.c.
  {
    map<NotificationType, NotificationData> dataArray;
    m_Instance.m_DataArray = new map<NotificationType, ref NotificationData>();
    string errorMessage;
    if (!JsonFileLoader<map<NotificationType, NotificationData>>.LoadFile(JSON_FILE_PATH, dataArray, errorMessage))
      ErrorEx(errorMessage);
    m_Instance.m_DataArray.Copy(dataArray);
    array<int> notificationTypes = new array<int>();
    NotificationType notificationType = 0;
    while (notificationType != NotificationType.NOTIFICATIONS_END)
    {
      notificationTypes.Insert(notificationType);
      notificationType++;
    }
    for (int i = 0; i < m_Instance.m_DataArray.Count(); ++i)
      notificationTypes.RemoveItem(m_Instance.m_DataArray.GetKey(i));
    if (notificationTypes.Count() > 0)
    {
      foreach (NotificationType notificationType2 : notificationTypes)
      {
        NotificationData notificationData = new NotificationData(
          "please_add_an_icon",
          "please_add_a_title",
          "optional_description",
        );
        m_Instance.m_DataArray.Insert(notificationType2, notificationData);
      }
      if (!JsonFileLoader<map<NotificationType, ref NotificationData>>.SaveFile(JSON_FILE_PATH, m_Instance.m_DataArray, errorMessage))
        ErrorEx(errorMessage);
    }
  }
References ErrorEx, JSON_FILE_PATH, and m_Instance.
SendNotificationToPlayer()
static void NotificationSystem::SendNotificationToPlayer (Man player, NotificationType type, float show_time, string detail_text = "") inline static protected
Send notification from default types to player from server.
Parameters
player the target player to send notification to
type the type of notification to send - these can be viewed in /Scripts/Data/Notifications.json
show_time amount of time this notification is displayed
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
Definition at line 158 of file NotificationSystem.c.
  {
    if (player)
      SendNotificationToPlayerIdentity(player.GetIdentity(), type, show_time, detail_text);
  }
References SendNotificationToPlayerIdentity().
SendNotificationToPlayerExtended()
static void NotificationSystem::SendNotificationToPlayerExtended (Man player, float show_time, string title_text, string detail_text = "", string icon = "") inline static protected
Send custom notification to player from server.
Parameters
player the target player to send notification to
show_time amount of time this notification is displayed
title_text the title text that is displayed in the notification
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
icon the icon that is displayed in the notification - will use default icon if not set
Definition at line 125 of file NotificationSystem.c.
  {
    if (player)
      SendNotificationToPlayerIdentityExtended(player.GetIdentity(), show_time, title_text, detail_text, icon);
  }
References SendNotificationToPlayerIdentityExtended().
SendNotificationToPlayerIdentity()
static void NotificationSystem::SendNotificationToPlayerIdentity (PlayerIdentity player, NotificationType type, float show_time, string detail_text = "") inline static protected
Send notification from default types to player identity from server.
Parameters
player the target player to send notification to - if null, will send to all players
type the type of notification to send - these can be viewed in /Scripts/Data/Notifications.json
show_time amount of time this notification is displayed
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
Definition at line 171 of file NotificationSystem.c.
  {
    ScriptRPC rpc = new ScriptRPC();
    rpc.Write(type);
    rpc.Write(show_time);
    rpc.Write(detail_text);
    rpc.Send(null, ERPCs.RPC_SEND_NOTIFICATION, true, player);
  }
Referenced by SendNotificationToPlayer().
SendNotificationToPlayerIdentityExtended()
static void NotificationSystem::SendNotificationToPlayerIdentityExtended (PlayerIdentity player, float show_time, string title_text, string detail_text = "", string icon = "") inline static protected
Send custom notification to player identity from server.
Parameters
player the target player to send notification to - if null, will send to all players
show_time amount of time this notification is displayed
title_text the title text that is displayed in the notification
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
icon the icon that is displayed in the notification - will use default icon if not set
Definition at line 139 of file NotificationSystem.c.
  {
    ScriptRPC rpc = new ScriptRPC();
    rpc.Write(show_time);
    rpc.Write(title_text);
    rpc.Write(detail_text);
    rpc.Write(icon);
    rpc.Send(null, ERPCs.RPC_SEND_NOTIFICATION_EXTENDED, true, player);
  }
Referenced by SendNotificationToPlayerExtended().
Update()
static void NotificationSystem::Update (float timeslice) inline static protected
Definition at line 229 of file NotificationSystem.c.
  {
    if (m_Instance)
    {
      if (g_Game.GetGameState() != DayZGameState.IN_GAME && g_Game.GetGameState() != DayZGameState.MAIN_MENU)
        return;
      m_Instance.m_TimeElapsed += timeslice;
      if (m_Instance.m_TimeElapsed >= UPDATE_INTERVAL_THRESHOLD)
      {
        array<NotificationRuntimeData> expiredNotifications = new array<NotificationRuntimeData>();
        foreach (NotificationRuntimeData visibleNotificationData : m_Instance.m_TimeArray)
        {
          if (visibleNotificationData.GetRemainingTime() <= 0.0)
            expiredNotifications.Insert(visibleNotificationData);
          else
            visibleNotificationData.UpdateRemainingTime(UPDATE_INTERVAL_THRESHOLD);
        }
        foreach (NotificationRuntimeData expiredNotificationData : expiredNotifications)
        {
          m_Instance.m_OnNotificationRemoved.Invoke(expiredNotificationData);
          m_Instance.m_TimeArray.RemoveItem(expiredNotificationData);
          if (m_Instance.m_DeferredArray.Count() > 0)
          {
            int count = m_Instance.m_DeferredArray.Count();
            NotificationRuntimeData deferredNotificationData = m_Instance.m_DeferredArray.Get(count - 1);
            m_Instance.m_TimeArray.Insert(deferredNotificationData);
            m_Instance.m_OnNotificationAdded.Invoke(deferredNotificationData);
            m_Instance.m_DeferredArray.Remove(count - 1);
          }
        }
        m_Instance.m_TimeElapsed = 0;
      }
    }
  }
References g_Game, m_Instance, NotificationRuntimeData(), and UPDATE_INTERVAL_THRESHOLD.
Referenced by CGame::OnUpdate().
Member Data Documentation
DEFAULT_TIME_DISPLAYED
const int NotificationSystem::DEFAULT_TIME_DISPLAYED = 10 private
Definition at line 71 of file NotificationSystem.c.
Referenced by CGame::DisconnectSessionEx(), OnlineServices::OnFriendsAsync(), BiosSessionService::OnGetGameplaySession(), and BiosUserManager::SelectUserEx().
JSON_FILE_PATH
const string NotificationSystem::JSON_FILE_PATH = "scripts/data/notifications.json" static protected
Definition at line 74 of file NotificationSystem.c.
Referenced by LoadNotificationData().
m_DataArray
ref map<NotificationType, ref NotificationData> NotificationSystem::m_DataArray protected
Definition at line 83 of file NotificationSystem.c.
Referenced by GetNotificationData().
m_DeferredArray
ref array<ref NotificationRuntimeData> NotificationSystem::m_DeferredArray protected
Definition at line 82 of file NotificationSystem.c.
Referenced by NotificationSystem().
m_Instance
ref NotificationSystem NotificationSystem::m_Instance static protected
Definition at line 79 of file NotificationSystem.c.
Referenced by AddNotification(), AddNotificationExtended(), CleanupInstance(), GetInstance(), InitInstance(), LoadNotificationData(), and Update().
m_OnNotificationAdded
ref ScriptInvoker NotificationSystem::m_OnNotificationAdded = new ScriptInvoker() protected
Definition at line 87 of file NotificationSystem.c.
m_OnNotificationRemoved
ref ScriptInvoker NotificationSystem::m_OnNotificationRemoved = new ScriptInvoker() protected
Definition at line 88 of file NotificationSystem.c.
m_TimeArray
ref array<ref NotificationRuntimeData> NotificationSystem::m_TimeArray protected
Definition at line 81 of file NotificationSystem.c.
Referenced by NotificationSystem().
m_TimeElapsed
float NotificationSystem::m_TimeElapsed protected
Definition at line 85 of file NotificationSystem.c.
Referenced by NotificationSystem().
MAX_NOTIFICATIONS
const int NotificationSystem::MAX_NOTIFICATIONS = 5 static protected
Definition at line 75 of file NotificationSystem.c.
Referenced by AddNotification(), and AddNotificationExtended().
NOTIFICATION_FADE_TIME
const float NotificationSystem::NOTIFICATION_FADE_TIME = 3.0 private
Definition at line 72 of file NotificationSystem.c.
Referenced by NotificationUI::Update().
UPDATE_INTERVAL_THRESHOLD
const float NotificationSystem::UPDATE_INTERVAL_THRESHOLD = 1.0 static private
Definition at line 77 of file NotificationSystem.c.
Referenced by Update().
The documentation for this class was generated from the following file:
scripts/3_Game/Client/Notifications/NotificationSystem.c