DayZ: NoIndicationActionInputBase Class Reference
NoIndicationActionInputBase Class Reference
Private Member Functions
void NoIndicationActionInputBase (PlayerBase player)
override void UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask)
override ActionBase GetAction ()
override ActionBase GetPossibleAction ()
Private Member Functions inherited from ActionInput
void SetInput (string input_name)
int GetInputType ()
UAInput GetUAInput ()
bool JustActivate ()
bool IsActive ()
bool WasEnded ()
void Update ()
void Reset ()
void UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask)
ActionBase GetAction ()
ActionTarget GetUsedActionTarget ()
ItemBase GetUsedMainItem ()
array< ActionBase > GetPossibleActions ()
ActionBase GetPossibleAction ()
int GetPossibleActionIndex ()
bool HasTarget ()
void OnActionStart ()
void OnActionEnd ()
void ActionsSelectReset ()
void ForceAction (ActionBase action, ActionTarget target, ItemBase item)
void ForceActionTarget (ActionTarget target)
void ClearForcedAction ()
void ClearForcedTarget ()
bool ForceActionCheck (PlayerBase player)
void SelectNextAction ()
void SelectPrevAction ()
int GetPossibleActionsCount ()
bool HasInput ()
int GetPriority ()
Detailed Description
Definition at line 536 of file ActionInput.c.
Constructor & Destructor Documentation
NoIndicationActionInputBase()
void NoIndicationActionInputBase::NoIndicationActionInputBase (PlayerBase player) inline private
Definition at line 538 of file ActionInput.c.
  {
    m_DetectFromTarget = false;
  }
References ActionInput::m_DetectFromTarget.
Member Function Documentation
GetAction()
override ActionBase NoIndicationActionInputBase::GetAction () inline private
Definition at line 550 of file ActionInput.c.
  {
    if (ForceActionCheck(m_Player))
      return m_ForcedActionData.m_Action;
    if (m_MainItem)
    {
      array<ActionBase_Basic> possible_actions;
      ActionBase action;
      m_MainItem.GetActions(this.Type(), possible_actions);
      if (possible_actions)
      {
        for (int i = 0; i < possible_actions.Count(); i++)
        {
          action = ActionBase.Cast(possible_actions.Get(i));
          if (action.Can(m_Player, m_Target, m_MainItem, m_ConditionMask))
            return action;
        }
      }
    }
    return NULL;
  }
References ActionInput::ForceActionCheck(), ActionInput::m_ConditionMask, ActionInput::m_ForcedActionData, ActionInput::m_MainItem, ActionInput::m_Player, ActionInput::m_Target, and Type.
Referenced by GetPossibleAction().
GetPossibleAction()
override ActionBase NoIndicationActionInputBase::GetPossibleAction () inline private
Definition at line 575 of file ActionInput.c.
  {
    return GetAction();
  }
References GetAction().
UpdatePossibleActions()
override void NoIndicationActionInputBase::UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask) inline private
Definition at line 543 of file ActionInput.c.
  {
    m_MainItem = item;
    m_Target = target;
    m_ConditionMask = action_condition_mask;
  }
References ActionInput::m_ConditionMask, ActionInput::m_MainItem, and ActionInput::m_Target.
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/ActionInput.c