DayZ: ClosableContainer Class Reference
ClosableContainer Class Reference
Protected Member Functions
void ContainerWithCargo (Container parent, int sort=-1)
override bool IsDisplayable ()
override bool IsEmpty ()
override bool IsItemActive ()
override bool CanCombine ()
override bool CanCombineAmmo ()
override bool IsItemWithQuantityActive ()
void LockCargo (bool value)
override void Open ()
override void Close ()
override bool IsOpened ()
override void UpdateInterval ()
override bool IsFirstContainerFocused ()
override bool IsLastContainerFocused ()
override void SetDefaultFocus (bool while_micromanagment_mode=false)
override void UnfocusAll ()
override bool SplitItem ()
override bool EquipItem ()
override bool TransferItem ()
override bool TransferItemToVicinity ()
override bool InspectItem ()
void SetEntity (EntityAI entity, int cargo_index=0, bool immedUpdate=true)
EntityAI GetEntity ()
override EntityAI GetFocusedContainerEntity ()
EntityAI GetItemPreviewItem (Widget w)
bool DraggingOverGrid (Widget w, int x, int y, Widget reciever)
void DropReceived (Widget w, int x, int y)
void TakeIntoHands (notnull PlayerBase player, notnull EntityAI item)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
override void DraggingOver (Widget w, int x, int y, Widget receiver)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
void ContainerWithCargoAndAttachments (LayoutHolder parent, int sort=-1)
void ~ContainerWithCargoAndAttachments ()
void RecomputeContainers ()
void AttachmentAddedEx (EntityAI item, string slot, EntityAI parent, bool immedUpdate=true)
void AttachmentAdded (EntityAI item, string slot, EntityAI parent)
void AttachmentRemoved (EntityAI item, string slot, EntityAI parent)
override void UpdateInterval ()
override EntityAI GetFocusedContainerEntity ()
override void UnfocusAll ()
override bool IsLastIndex ()
override bool IsFirstContainerFocused ()
override bool IsLastContainerFocused ()
override void MoveGridCursor (int direction)
void SetEntity (EntityAI entity, bool immedUpdate=true)
void HideCargo ()
void ShowCargo ()
EntityAI GetEntity ()
ItemPreviewWidget GetItemPreviewWidgetDragOrDrop (Widget w)
EntityAI GetItemPreviewItem (Widget w)
Widget GetItemPreviewWidget (Widget w)
void MouseClick2 (Widget w, int x, int y, int button)
void DropReceived (Widget w, int x, int y, CargoContainer cargo)
NOTE Used for mouse only.
void TakeAsAttachment (Widget w, Widget receiver)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
void OnDropReceivedFromHeader2 (Widget w, int x, int y, Widget receiver)
void DoubleClick (Widget w, int x, int y, int button)
bool DraggingOverGrid (Widget w, int x, int y, Widget reciever, CargoContainer cargo)
override void DraggingOver (Widget w, int x, int y, Widget receiver)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
Protected Attributes
ref CargoContainer m_CargoGrid
int m_CargoIndex = -1
ref Attachments m_Atts
ref map< EntityAI, ref CargoContainer > m_AttachmentCargos
ref map< EntityAI, ref AttachmentsWrapper > m_AttachmentAttachmentsContainers
ref map< EntityAI, ref Attachments > m_AttachmentAttachments
ref array< int > m_AttachmentSlotsSorted
Detailed Description
Definition at line 1 of file ContainerWithCargo.c.
Constructor & Destructor Documentation
~ContainerWithCargoAndAttachments()
void ClosableContainer::~ContainerWithCargoAndAttachments () inline protected
Definition at line 16 of file ContainerWithCargoAndAttachments.c.
  {
    if (m_Entity)
    {
      m_Entity.GetOnItemAttached().Remove(AttachmentAdded);
      m_Entity.GetOnItemDetached().Remove(AttachmentRemoved);
    }
    if (m_Atts)
      delete m_Atts;
    foreach (EntityAI e, Attachments att : m_AttachmentAttachments)
      delete att;
    if (m_AttachmentAttachments)
      m_AttachmentAttachments.Clear();
    if (m_AttachmentAttachmentsContainers)
      m_AttachmentAttachmentsContainers.Clear();
    if (m_AttachmentCargos)
      m_AttachmentCargos.Clear();
  }
References m_Entity.
Member Function Documentation
AttachmentAdded()
void ClosableContainer::AttachmentAdded (EntityAI item, string slot, EntityAI parent) inline protected
Definition at line 129 of file ContainerWithCargoAndAttachments.c.
  {
    AttachmentAddedEx(item, slot, parent);
  }
AttachmentAddedEx()
void ClosableContainer::AttachmentAddedEx (EntityAI item, string slot, EntityAI parent, bool immedUpdate = true) inline protected
Definition at line 67 of file ContainerWithCargoAndAttachments.c.
  {
    int slot_id = InventorySlots.GetSlotIdFromString(slot);
    int sort = -1;
    bool updateNeeded = false;
    ref Attachments att_cont = null;
    ref CargoContainer cont = null;
    if (item.GetInventory().GetAttachmentSlotsCount() > 0 && item.CanDisplayAnyAttachmentSlot())
    {
      updateNeeded = true;
      att_cont = new Attachments(this, item);
      sort = (m_AttachmentSlotsSorted.Find(slot_id) * 2) + SORT_ATTACHMENTS_NEXT_OFFSET;
      att_cont.InitAttachmentGrid(sort);
      m_AttachmentAttachments.Insert(item, att_cont);
      m_AttachmentAttachmentsContainers.Insert(item, att_cont.GetWrapper());
      att_cont.UpdateInterval();
    }
    if (item.GetInventory().GetCargo())
    {
      updateNeeded = true;
      cont = new CargoContainer(this, true);
      sort = (m_AttachmentSlotsSorted.Find(slot_id) * 2) + SORT_CARGO_NEXT_OFFSET;
      cont.GetRootWidget().SetSort(sort);
      cont.SetEntity(item, false);
      Insert(cont, m_Atts.GetAttachmentHeight() + m_AttachmentCargos.Count() + 1);
      m_AttachmentCargos.Insert(item, cont);
    }
    if (updateNeeded)
    {
      if (att_cont)
      {
        att_cont.ShowFalseAttachmentsHeader(true);
        if (cont)
        {
          cont.ShowFalseCargoHeader(false);
          cont.UpdateSize();
          cont.SetAlternateFalseTextHeaderWidget(att_cont.GetFalseHeaderTextWidget());
        }
      }
      else if (cont)
      {
        cont.SetAlternateFalseTextHeaderWidget(null); //just to be safe..
      }
      RecomputeContainers();
      RecomputeOpenedContainers();
      Inventory.GetInstance().UpdateConsoleToolbar();
      if (m_Parent && immedUpdate)
        m_Parent.Refresh();
    }
  }
References InventorySlots::GetSlotIdFromString(), Inventory(), and m_Parent.
AttachmentRemoved()
void ClosableContainer::AttachmentRemoved (EntityAI item, string slot, EntityAI parent) inline protected
Definition at line 134 of file ContainerWithCargoAndAttachments.c.
  {
    int slot_id = InventorySlots.GetSlotIdFromString(slot);
    CargoContainer old_cont = m_AttachmentCargos.Get(item);
    if (old_cont)
    {
      m_AttachmentCargos.Remove(item);
      delete old_cont;
      if (m_Parent)
        m_Parent.Refresh();
      Inventory.GetInstance().UpdateConsoleToolbar();
    }
    AttachmentsWrapper old_att_cont = m_AttachmentAttachmentsContainers.Get(item);
    if (old_att_cont)
    {
      m_AttachmentAttachmentsContainers.Remove(item);
      m_AttachmentAttachments.Remove(item);
      delete old_att_cont;
      if (m_Parent)
        m_Parent.Refresh();
      Inventory.GetInstance().UpdateConsoleToolbar();
    }
    RecomputeContainers();
    RecomputeOpenedContainers();
  }
References InventorySlots::GetSlotIdFromString(), Inventory(), and m_Parent.
CanCombine()
override bool ClosableContainer::CanCombine () inline protected
Definition at line 37 of file ContainerWithCargo.c.
  {
    return m_CargoGrid.CanCombine();
  }
CanCombineAmmo()
override bool ClosableContainer::CanCombineAmmo () inline protected
Definition at line 42 of file ContainerWithCargo.c.
  {
    return m_CargoGrid.CanCombineAmmo();
  }
Close()
override void ClosableContainer::Close () inline protected
Definition at line 84 of file ContainerWithCargo.c.
  {
    if (!m_LockCargo)
    {
      ItemManager.GetInstance().SetDefaultOpenState(m_Entity.GetType(), false);
      m_Closed = true;
      SetOpenForSlotIcon(false);
      OnHide();
      m_Parent.m_Parent.Refresh();
    }
    if (m_SlotIcon)
      m_SlotIcon.GetRadialIconPanel().Show(!m_LockCargo);
  }
References ItemManager::GetInstance(), m_Entity, m_Parent, and OnHide().
Referenced by Container::CloseButtonOnMouseButtonDown().
ContainerWithCargo()
void ClosableContainer::ContainerWithCargo (Container parent, int sort = -1) inline protected
Definition at line 6 of file ContainerWithCargo.c.
  {
    m_LockCargo = false;
    m_Parent = parent;
    m_CargoGrid = new CargoContainer(this);
    Insert(m_CargoGrid);
    m_CargoGrid.GetRootWidget().SetSort(1);
    WidgetEventHandler.GetInstance().RegisterOnDraggingOver(m_MainWidget, this, "DraggingOverGrid");
    RecomputeOpenedContainers();
  }
References WidgetEventHandler::GetInstance(), and m_Parent.
Referenced by AttachmentCategoriesRow::RefreshSlot().
ContainerWithCargoAndAttachments()
void ClosableContainer::ContainerWithCargoAndAttachments (LayoutHolder parent, int sort = -1) inline protected
Definition at line 11 of file ContainerWithCargoAndAttachments.c.
  {
    WidgetEventHandler.GetInstance().RegisterOnDraggingOver(m_MainWidget, this, "DraggingOverHeader2");
  }
References WidgetEventHandler::GetInstance().
DoubleClick()
void ClosableContainer::DoubleClick (Widget w, int x, int y, int button) inline protected
Definition at line 601 of file ContainerWithCargoAndAttachments.c.
  {
    if (button == MouseState.LEFT && !g_Game.IsLeftCtrlDown())
    {
      PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
      if (w == NULL || player.GetInventory().IsInventoryLocked())
        return;
      ItemPreviewWidget iw = ItemPreviewWidget.Cast(w.FindAnyWidget("Render"));
      if (!iw)
      {
        string name = w.GetName();
        name.Replace("PanelWidget", "Render");
        iw = ItemPreviewWidget.Cast(w.FindAnyWidget(name));
      }
      if (!iw)
        iw = ItemPreviewWidget.Cast(w);
      EntityAI item = iw.GetItem();
      if (!item)
        return;
      SlotsIcon icon;
      iw.GetUserData(icon);
      if (icon && icon.IsReserved())
        return;
      if (!item.GetInventory().CanRemoveEntity() || !player.CanManipulateInventory())
        return;
      if (player.GetInventory().HasEntityInInventory(item) && player.GetHumanInventory().CanAddEntityInHands(item))
        player.PredictiveTakeEntityToHands(item);
      else
      {
        if (player.GetInventory().CanAddEntityToInventory(item) && item.GetInventory().CanRemoveEntity())
          player.PredictiveTakeEntityToInventory(FindInventoryLocationType.ANY, InventoryItem.Cast(item));
        else
        {
          if (player.GetHumanInventory().CanAddEntityInHands(item))
            player.PredictiveTakeEntityToHands(item);
        }
      }
      HideOwnedTooltip();
      name = w.GetName();
      name.Replace("PanelWidget", "Temperature");
      w.FindAnyWidget(name).Show(false);
    }
  }
References g_Game, GetGame(), GetPlayer(), and name.
DraggingOver() [1/2]
override void ClosableContainer::DraggingOver (Widget w, int x, int y, Widget receiver) inline protected
Definition at line 395 of file ContainerWithCargo.c.
  {
    if (!w)
      return;
    EntityAI item = GetItemPreviewItem(w);
    if (!item)
      return;
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (item.GetInventory().CanRemoveEntity() && player.CanManipulateInventory() && m_Entity.GetInventory().CanAddEntityInCargo(item, item.GetInventory().GetFlipCargo()) && !m_Entity.GetInventory().HasEntityInCargo(item))
    {
      ColorManager.GetInstance().SetColor(w, ColorManager.GREEN_COLOR);
      ItemManager.GetInstance().HideDropzones();
      if (m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer())
        ItemManager.GetInstance().GetRightDropzone().SetAlpha(1);
      else
        ItemManager.GetInstance().GetLeftDropzone().SetAlpha(1);
    }
    else
    {
      ColorManager.GetInstance().SetColor(w, ColorManager.RED_COLOR);
      ItemManager.GetInstance().ShowSourceDropzone(item);
    }
  }
References GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), GetItemPreviewItem(), GetPlayer(), ColorManager::GREEN_COLOR, m_Entity, and ColorManager::RED_COLOR.
Referenced by DraggingOverHeader().
DraggingOver() [2/2]
override void ClosableContainer::DraggingOver (Widget w, int x, int y, Widget receiver) inline protected
Definition at line 717 of file ContainerWithCargoAndAttachments.c.
  {
    DraggingOverHeader(w, x, y, receiver);
  }
References x, and y.
DraggingOverGrid() [1/2]
bool ClosableContainer::DraggingOverGrid (Widget w, int x, int y, Widget reciever) inline protected
Definition at line 229 of file ContainerWithCargo.c.
  {
    if (w == null)
      return false;
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (!player.CanManipulateInventory())
      return false;
    EntityAI item = GetItemPreviewItem(w);
    if (!item)
      return false;
    if (!item.GetInventory().CanRemoveEntity())
      return false;
    int color, c_x, c_y;
#ifdef PLATFORM_CONSOLE
    int idx = -1;
#else
    int idx = 0;
#endif
    CargoBase cargo = m_Entity.GetInventory().GetCargoFromIndex(m_CargoIndex);
    if (cargo)
    {
      c_x = cargo.GetHeight();
      c_y = cargo.GetWidth();
    }
    InventoryLocation dst = new InventoryLocation;
#ifdef PLATFORM_CONSOLE
    x = 0;
    y = cargo.GetItemCount();
    m_Entity.GetInventory().FindFreeLocationFor(item, FindInventoryLocationType.CARGO, dst);
#else
    dst.SetCargoAuto(cargo, item, x, y, item.GetInventory().GetFlipCargo());
#endif
#ifdef PLATFORM_CONSOLE
    if (dst.IsValid() && m_Entity.GetInventory().LocationCanAddEntityEx(dst))
#else
    if (m_Entity && c_x > x && c_y > y && m_Entity.GetInventory().LocationCanAddEntityEx(dst))
#endif
    {
      ItemManager.GetInstance().HideDropzones();
      if (m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer())
        ItemManager.GetInstance().GetRightDropzone().SetAlpha(1);
      else
        ItemManager.GetInstance().GetLeftDropzone().SetAlpha(1);
      color = ColorManager.GREEN_COLOR;
    }
    else
    {
      color = ColorManager.RED_COLOR;
      ItemManager.GetInstance().ShowSourceDropzone(item);
    }
    if (w.FindAnyWidget("Cursor"))
      w.FindAnyWidget("Cursor").SetColor(color);
    else
    {
      string name = w.GetName();
      name.Replace("PanelWidget", "Cursor");
      if (w.FindAnyWidget(name))
        w.FindAnyWidget(name).SetColor(color);
    }
    return true;
  }
References GetGame(), ItemManager::GetInstance(), GetItemPreviewItem(), GetPlayer(), ColorManager::GREEN_COLOR, m_Entity, name, ColorManager::RED_COLOR, x, and y.
DraggingOverGrid() [2/2]
bool ClosableContainer::DraggingOverGrid (Widget w, int x, int y, Widget reciever, CargoContainer cargo) inline protected
Definition at line 654 of file ContainerWithCargoAndAttachments.c.
  {
    if (w == NULL)
      return false;
    EntityAI item = GetItemPreviewItem(w);
    if (!item)
      return false;
    int color;
    int idx = 0;
    int c_x, c_y;
    EntityAI target_entity;
    CargoBase target_cargo;
    if (cargo == m_CargoGrid)
    {
      target_entity = m_Entity;
      target_cargo = m_Entity.GetInventory().GetCargo();
    }
    else
    {
      target_entity = m_AttachmentCargos.GetKeyByValue(cargo);
      if (target_entity)
        target_cargo = target_entity.GetInventory().GetCargo();
      else
        return false;
    }
    if (target_cargo && target_entity)
    {
      c_x = target_cargo.GetHeight();
      c_y = target_cargo.GetWidth();
    }
    else
      return false;
    if (c_x > x && c_y > y && target_entity.GetInventory().CanAddEntityInCargoEx(item, idx, x, y, item.GetInventory().GetFlipCargo()))
    {
      color = ColorManager.GREEN_COLOR;
      if (target_entity.GetHierarchyRootPlayer() == GetGame().GetPlayer())
        ItemManager.GetInstance().GetRightDropzone().SetAlpha(1);
      else
        ItemManager.GetInstance().GetLeftDropzone().SetAlpha(1);
    }
    else
      color = ColorManager.RED_COLOR;
    if (w.FindAnyWidget("Cursor"))
      w.FindAnyWidget("Cursor").SetColor(color);
    else
    {
      string name = w.GetName();
      name.Replace("PanelWidget", "Cursor");
      if (w.FindAnyWidget(name))
        w.FindAnyWidget(name).SetColor(color);
    }
    return true;
  }
References GetGame(), ItemManager::GetInstance(), GetPlayer(), ColorManager::GREEN_COLOR, m_Entity, name, ColorManager::RED_COLOR, x, and y.
DraggingOverHeader() [1/2]
override void ClosableContainer::DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline protected
Definition at line 390 of file ContainerWithCargo.c.
  {
    DraggingOver(w, x, y, receiver);
  }
References DraggingOver(), x, and y.
DraggingOverHeader() [2/2]
override void ClosableContainer::DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline protected
Definition at line 722 of file ContainerWithCargoAndAttachments.c.
  {
    if (w == NULL)
      return;
    EntityAI item = GetItemPreviewItem(w);
    if (!item)
      return;
    SlotsIcon slots_icon;
    receiver.GetUserData(slots_icon);
    EntityAI attached_entity;
    EntityAI receiver_item;
    bool is_reserved = false;
    int slot_id = -1;
    if (slots_icon)
    {
      attached_entity = slots_icon.GetSlotParent();
      slot_id = slots_icon.GetSlotID();
      receiver_item = slots_icon.GetEntity();
      is_reserved = slots_icon.IsReserved();
    }
    Weapon_Base wpn;
    Magazine mag;
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (m_Entity)
    {
      if (Class.CastTo(wpn, m_Entity) && Class.CastTo(mag, item))
      {
        if (player.GetWeaponManager().CanAttachMagazine(wpn, mag))
        {
          ItemManager.GetInstance().HideDropzones();
          if (m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer())
            ItemManager.GetInstance().GetRightDropzone().SetAlpha(1);
          else
            ItemManager.GetInstance().GetLeftDropzone().SetAlpha(1);
          ColorManager.GetInstance().SetColor(w, ColorManager.GREEN_COLOR);
        }
      }
      else if (receiver_item && !is_reserved)
      {
        ItemBase receiver_itemIB = ItemBase.Cast(receiver_item);
        ItemBase itemIB = ItemBase.Cast(item);
        if (receiver_itemIB && itemIB && receiver_itemIB.CanBeCombined(itemIB))
        {
          ItemManager.GetInstance().HideDropzones();
          if (m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer())
            ItemManager.GetInstance().GetRightDropzone().SetAlpha(1);
          else
            ItemManager.GetInstance().GetLeftDropzone().SetAlpha(1);
          ColorManager.GetInstance().SetColor(w, ColorManager.COMBINE_COLOR);
        }
        else if (GameInventory.CanSwapEntitiesEx(receiver_item, item))
        {
          ItemManager.GetInstance().HideDropzones();
          if (m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer())
            ItemManager.GetInstance().GetRightDropzone().SetAlpha(1);
          else
            ItemManager.GetInstance().GetLeftDropzone().SetAlpha(1);
          ColorManager.GetInstance().SetColor(w, ColorManager.SWAP_COLOR);
        }
        else if (receiver_itemIB.GetInventory().CanAddAttachment(item))
        {
          ItemManager.GetInstance().HideDropzones();
          if (receiver_itemIB.GetHierarchyRootPlayer() == GetGame().GetPlayer())
            ItemManager.GetInstance().GetRightDropzone().SetAlpha(1);
          else
            ItemManager.GetInstance().GetLeftDropzone().SetAlpha(1);
          ColorManager.GetInstance().SetColor(w, ColorManager.GREEN_COLOR);
        }
      }
      else if (attached_entity && attached_entity.GetInventory().CanAddAttachmentEx(item, slot_id))
      {
        ItemManager.GetInstance().HideDropzones();
        if (attached_entity.GetHierarchyRootPlayer() == GetGame().GetPlayer())
          ItemManager.GetInstance().GetRightDropzone().SetAlpha(1);
        else
          ItemManager.GetInstance().GetLeftDropzone().SetAlpha(1);
        ColorManager.GetInstance().SetColor(w, ColorManager.GREEN_COLOR);
      }
      else if (m_Entity.GetInventory().CanAddAttachment(item))
      {
        ItemManager.GetInstance().HideDropzones();
        if (m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer())
          ItemManager.GetInstance().GetRightDropzone().SetAlpha(1);
        else
          ItemManager.GetInstance().GetLeftDropzone().SetAlpha(1);
        ColorManager.GetInstance().SetColor(w, ColorManager.GREEN_COLOR);
      }
      else if ((m_Entity.GetInventory().CanAddEntityInCargo(item, item.GetInventory().GetFlipCargo()) && !m_Entity.GetInventory().HasEntityInCargo(item)) /*|| player.GetHumanInventory().HasEntityInHands( item )*/)
      {
        ItemManager.GetInstance().HideDropzones();
        if (m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer())
          ItemManager.GetInstance().GetRightDropzone().SetAlpha(1);
        else
          ItemManager.GetInstance().GetLeftDropzone().SetAlpha(1);
        ColorManager.GetInstance().SetColor(w, ColorManager.GREEN_COLOR);
      }
      else
      {
        ItemManager.GetInstance().ShowSourceDropzone(item);
        ColorManager.GetInstance().SetColor(w, ColorManager.RED_COLOR);
      }
    }
  }
References GameInventory::CanSwapEntitiesEx(), Class::CastTo(), ColorManager::COMBINE_COLOR, GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), GetPlayer(), ColorManager::GREEN_COLOR, m_Entity, ColorManager::RED_COLOR, and ColorManager::SWAP_COLOR.
DropReceived() [1/2]
void ClosableContainer::DropReceived (Widget w, int x, int y) inline protected
Definition at line 302 of file ContainerWithCargo.c.
  {
    float xx, yy;
    GetMainWidget().Update();
    GetMainWidget().GetScreenSize(xx, yy);
    if (GetMainWidget().FindAnyWidget("Background"))
    {
      GetMainWidget().FindAnyWidget("Background").Show(true);
      GetMainWidget().FindAnyWidget("Background").SetSize(xx, yy);
    }
    EntityAI item = GetItemPreviewItem(w);
    if (!item)
      return;
#ifdef PLATFORM_CONSOLE
    if (m_CargoGrid.HasItem(item))
      return;
#endif
#ifdef PLATFORM_CONSOLE
    int idx = -1;
#else
    int idx = 0;
#endif
    int c_x, c_y;
    CargoBase cargo = m_Entity.GetInventory().GetCargoFromIndex(m_CargoIndex);
    if (cargo)
    {
      c_x = cargo.GetHeight();
      c_y = cargo.GetWidth();
    }
    InventoryLocation dst = new InventoryLocation;
#ifdef PLATFORM_CONSOLE
    x = 0;
    y = cargo.GetItemCount();
    m_Entity.GetInventory().FindFreeLocationFor(item, FindInventoryLocationType.CARGO, dst);
#else
    dst.SetCargoAuto(cargo, item, x, y, item.GetInventory().GetFlipCargo());
#endif
    InventoryLocation src = new InventoryLocation;
    item.GetInventory().GetCurrentInventoryLocation(src);
    if (src.CompareLocationOnly(dst) && src.GetFlip() == dst.GetFlip())
      return;
#ifdef PLATFORM_CONSOLE
    if (dst.IsValid() && m_Entity.GetInventory().LocationCanAddEntityEx(dst))
#else
    if (c_x > x && c_y > y && m_Entity.GetInventory().LocationCanAddEntityEx(dst))
#endif
    {
      PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
      SplitItemUtils.TakeOrSplitToInventoryLocation(player, dst);
      Icon icon = m_CargoGrid.GetIcon(item);
      if (icon && w && w.FindAnyWidget("Cursor"))
      {
        w.FindAnyWidget("Cursor").SetColor(ColorManager.BASE_COLOR);
        icon.Refresh();
        Refresh();
      }
    }
    ItemManager.GetInstance().HideDropzones();
    ItemManager.GetInstance().SetIsDragging(false);
  }
References ColorManager::BASE_COLOR, FindAnyWidget(), GetGame(), ItemManager::GetInstance(), GetItemPreviewItem(), GetPlayer(), m_Entity, Refresh(), SplitItemUtils::TakeOrSplitToInventoryLocation(), x, and y.
DropReceived() [2/2]
void ClosableContainer::DropReceived (Widget w, int x, int y, CargoContainer cargo) inline protected
NOTE Used for mouse only.
Definition at line 433 of file ContainerWithCargoAndAttachments.c.
  {
    EntityAI item = GetItemPreviewItem(w);
    if (!item)
      return;
#ifndef PLATFORM_CONSOLE
    int c_x, c_y;
#endif
    EntityAI targetEntity = m_Entity;
    CargoBase targetCargo;
    if (cargo != m_CargoGrid)
      targetEntity = m_AttachmentCargos.GetKeyByValue(cargo);
    if (targetEntity)
    {
      targetCargo = targetEntity.GetInventory().GetCargo();
#ifdef PLATFORM_CONSOLE
      if (m_CargoGrid && m_CargoGrid.HasItem(item))
        return;
#endif
    }
    if (!targetCargo || !targetEntity)
      return;
    InventoryLocation dst = new InventoryLocation();
#ifdef PLATFORM_CONSOLE
    x = 0;
    y = targetCargo.GetItemCount();
    targetEntity.GetInventory().FindFreeLocationFor(item, FindInventoryLocationType.CARGO, dst);
#else
    c_x = targetCargo.GetHeight();
    c_y = targetCargo.GetWidth();
    dst.SetCargoAuto(targetCargo, item, x, y, item.GetInventory().GetFlipCargo());
#endif
    InventoryLocation src = new InventoryLocation();
    item.GetInventory().GetCurrentInventoryLocation(src);
    if (src.CompareLocationOnly(dst) && src.GetFlip() == dst.GetFlip())
      return;
#ifdef PLATFORM_CONSOLE
    if (dst.IsValid() && targetEntity.GetInventory().LocationCanAddEntity(dst))
#else
    if (c_x > x && c_y > y && targetEntity.GetInventory().LocationCanAddEntity(dst))
#endif
    {
      PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
      SplitItemUtils.TakeOrSplitToInventoryLocation(player, dst);
      Icon icon = cargo.GetIcon(item);
      if (icon)
      {
        if (w && w.FindAnyWidget("Cursor"))
          w.FindAnyWidget("Cursor").SetColor(ColorManager.BASE_COLOR);
        icon.Refresh();
        Refresh();
      }
    }
    ItemManager.GetInstance().HideDropzones();
    ItemManager.GetInstance().SetIsDragging(false);
  }
References ColorManager::BASE_COLOR, GetGame(), ItemManager::GetInstance(), GetPlayer(), m_Entity, Refresh(), SplitItemUtils::TakeOrSplitToInventoryLocation(), x, and y.
EquipItem()
override bool ClosableContainer::EquipItem () inline protected
Definition at line 158 of file ContainerWithCargo.c.
  {
    return m_CargoGrid.EquipItem();
  }
GetEntity() [1/2]
EntityAI ClosableContainer::GetEntity () inline protected
Definition at line 203 of file ContainerWithCargo.c.
  {
    return m_Entity;
  }
References m_Entity.
Referenced by OnDropReceivedFromHeader().
GetEntity() [2/2]
EntityAI ClosableContainer::GetEntity () inline protected
Definition at line 328 of file ContainerWithCargoAndAttachments.c.
  {
    return m_Entity;
  }
References m_Entity.
GetFocusedContainerEntity() [1/2]
override EntityAI ClosableContainer::GetFocusedContainerEntity () inline protected
Definition at line 208 of file ContainerWithCargo.c.
  {
    return m_Entity;
  }
References m_Entity.
GetFocusedContainerEntity() [2/2]
override EntityAI ClosableContainer::GetFocusedContainerEntity () inline protected
Definition at line 194 of file ContainerWithCargoAndAttachments.c.
  {
    return m_Entity;
  }
References m_Entity.
GetItemPreviewItem() [1/2]
EntityAI ClosableContainer::GetItemPreviewItem (Widget w) inline protected
Definition at line 213 of file ContainerWithCargo.c.
  {
    ItemPreviewWidget ipw = ItemPreviewWidget.Cast(w.FindAnyWidget("Render"));
    if (!ipw)
    {
      string name = w.GetName();
      name.Replace("PanelWidget", "Render");
      ipw = ItemPreviewWidget.Cast(w.FindAnyWidget(name));
    }
    if (!ipw)
      ipw = ItemPreviewWidget.Cast(w);
    if (!ipw || !ipw.IsInherited(ItemPreviewWidget))
      return null;
    return ipw.GetItem();
  }
References name.
Referenced by DraggingOver(), DraggingOverGrid(), DropReceived(), and OnDropReceivedFromHeader().
GetItemPreviewItem() [2/2]
EntityAI ClosableContainer::GetItemPreviewItem (Widget w) inline protected
Definition at line 340 of file ContainerWithCargoAndAttachments.c.
  {
    ItemPreviewWidget ipw = ItemPreviewWidget.Cast(w.FindAnyWidget("Render"));
    if (!ipw)
    {
      string name = w.GetName();
      name.Replace("PanelWidget", "Render");
      ipw = ItemPreviewWidget.Cast(w.FindAnyWidget(name));
    }
    if (!ipw)
      ipw = ItemPreviewWidget.Cast(w);
    if (!ipw || !ipw.IsInherited(ItemPreviewWidget))
      return NULL;
    return ipw.GetItem();
  }
References name.
GetItemPreviewWidget()
Widget ClosableContainer::GetItemPreviewWidget (Widget w) inline protected
Definition at line 356 of file ContainerWithCargoAndAttachments.c.
  {
    ItemPreviewWidget ipw = ItemPreviewWidget.Cast(w.FindAnyWidget("Render"));
    if (!ipw)
    {
      string name = w.GetName();
      name.Replace("PanelWidget", "Render");
      ipw = ItemPreviewWidget.Cast(w.FindAnyWidget(name));
    }
    if (!ipw)
      ipw = ItemPreviewWidget.Cast(w);
    return ipw;
  }
References name.
GetItemPreviewWidgetDragOrDrop()
ItemPreviewWidget ClosableContainer::GetItemPreviewWidgetDragOrDrop (Widget w) inline protected
Definition at line 333 of file ContainerWithCargoAndAttachments.c.
  {
    string name = w.GetName();
    name.Replace("PanelWidget", "Render");
    return ItemPreviewWidget.Cast(w.FindAnyWidget(name));
  }
References name.
HideCargo()
void ClosableContainer::HideCargo () inline protected
Definition at line 304 of file ContainerWithCargoAndAttachments.c.
  {
    if (m_CargoGrid)
    {
      if (m_CargoGrid.IsVisible())
      {
        m_CargoGrid.OnHide();
        RecomputeOpenedContainers();
      }
    }
  }
InspectItem()
override bool ClosableContainer::InspectItem () inline protected
Definition at line 173 of file ContainerWithCargo.c.
  {
    return m_CargoGrid.InspectItem();
  }
Referenced by AttachmentCategoriesRow::MouseClick().
IsDisplayable()
override bool ClosableContainer::IsDisplayable () inline protected
Definition at line 20 of file ContainerWithCargo.c.
  {
    if (m_Entity)
      return m_Entity.CanDisplayCargo();
    return false;
  }
References m_Entity.
Referenced by Container::Open(), and Container::UpdateRadialIcon().
IsEmpty()
override bool ClosableContainer::IsEmpty () inline protected
Definition at line 27 of file ContainerWithCargo.c.
  {
    return m_CargoGrid.IsEmpty();
  }
IsFirstContainerFocused() [1/2]
override bool ClosableContainer::IsFirstContainerFocused () inline protected
Definition at line 133 of file ContainerWithCargo.c.
  {
    return m_CargoGrid.IsFirstContainerFocused();
  }
IsFirstContainerFocused() [2/2]
override bool ClosableContainer::IsFirstContainerFocused () inline protected
Definition at line 220 of file ContainerWithCargoAndAttachments.c.
  {
    return IsFirstIndex();
  }
IsItemActive()
override bool ClosableContainer::IsItemActive () inline protected
Definition at line 32 of file ContainerWithCargo.c.
  {
    return m_CargoGrid.IsItemActive();
  }
IsItemWithQuantityActive()
override bool ClosableContainer::IsItemWithQuantityActive () inline protected
Definition at line 47 of file ContainerWithCargo.c.
  {
    return m_CargoGrid.IsItemWithQuantityActive();
  }
IsLastContainerFocused() [1/2]
override bool ClosableContainer::IsLastContainerFocused () inline protected
Definition at line 138 of file ContainerWithCargo.c.
  {
    return m_CargoGrid.IsLastContainerFocused();
  }
IsLastContainerFocused() [2/2]
override bool ClosableContainer::IsLastContainerFocused () inline protected
Definition at line 225 of file ContainerWithCargoAndAttachments.c.
  {
    return IsLastIndex();
  }
IsLastIndex()
override bool ClosableContainer::IsLastIndex () inline protected
Definition at line 215 of file ContainerWithCargoAndAttachments.c.
  {
    return m_ActiveIndex == (m_OpenedContainers.Count() - 1);
  }
IsOpened()
override bool ClosableContainer::IsOpened () inline protected
Definition at line 99 of file ContainerWithCargo.c.
  {
    return !m_Closed && !m_LockCargo;
  }
Referenced by Container::OnShow(), UpdateInterval(), and Container::UpdateRadialIcon().
LockCargo()
void ClosableContainer::LockCargo (bool value) inline protected
Definition at line 52 of file ContainerWithCargo.c.
  {
    if (value != m_LockCargo)
    {
      if (value)
      {
        m_LockCargo = true;
        OnHide();
      }
      else
      {
        m_LockCargo = false;
        SetOpenState(!m_Closed);
      }
    }
  }
References OnHide().
Referenced by SetEntity(), and UpdateInterval().
MouseClick2()
void ClosableContainer::MouseClick2 (Widget w, int x, int y, int button) inline protected
Definition at line 370 of file ContainerWithCargoAndAttachments.c.
  {
    SlotsIcon icon;
    w.GetUserData(icon);
    ItemBase selectedItem;
    if (icon)
      selectedItem = ItemBase.Cast(icon.GetEntity());
    if (selectedItem)
    {
      bool isReserved = icon.IsReserved();
      switch (button)
      {
      case MouseState.RIGHT:
#ifdef DIAG_DEVELOPER
        if (GetDayZGame().IsLeftCtrlDown())
          ShowActionMenu(selectedItem);
#endif
        if (isReserved)
        {
          EntityAI attachmentParent = icon.GetSlotParent();
          GetGame().GetPlayer().GetHumanInventory().ClearUserReservedLocationSynced(selectedItem);
          attachmentParent.GetOnAttachmentReleaseLock().Invoke(selectedItem, icon.GetSlotID());
        }
        break;
      case MouseState.MIDDLE:
        if (!isReserved)
          InspectItem(selectedItem);
        break;
      case MouseState.LEFT:
        if (!isReserved)
        {
          PlayerBase controlledPlayer = PlayerBase.Cast(GetGame().GetPlayer());
          if (g_Game.IsLeftCtrlDown())
          {
            if (controlledPlayer.CanDropEntity(selectedItem))
            {
              if (selectedItem.GetTargetQuantityMax() < selectedItem.GetQuantity())
                selectedItem.SplitIntoStackMaxClient(null, -1);
              else
                controlledPlayer.PhysicalPredictiveDropItem(selectedItem);
            }
          }
          else
          {
            bool draggable = !controlledPlayer.GetInventory().HasInventoryReservation(selectedItem, null) && !controlledPlayer.GetInventory().IsInventoryLocked() && selectedItem.GetInventory().CanRemoveEntity() && !controlledPlayer.IsItemsToDelete();
            ItemManager.GetInstance().SetWidgetDraggable(w, draggable);
          }
        }
        break;
      }
    }
  }
References g_Game, GetDayZGame(), GetGame(), ItemManager::GetInstance(), and GetPlayer().
MoveGridCursor()
override void ClosableContainer::MoveGridCursor (int direction) inline protected
Definition at line 230 of file ContainerWithCargoAndAttachments.c.
  {
    Container c = GetFocusedContainer();
    if (c)
    {
      c.MoveGridCursor(direction);
      Inventory.GetInstance().UpdateConsoleToolbar();
    }
  }
References Inventory().
OnDropReceivedFromHeader() [1/2]
override void ClosableContainer::OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline protected
Definition at line 420 of file ContainerWithCargo.c.
  {
    EntityAI item = GetItemPreviewItem(w);
    if (!item)
      return;
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    InventoryLocation src = new InventoryLocation();
    if (GetEntity() && item.GetInventory().GetCurrentInventoryLocation(src))
    {
      InventoryLocation dst = new InventoryLocation();
      if (m_Entity.GetInventory().FindFreeLocationFor(item, FindInventoryLocationType.ATTACHMENT, dst))
        player.PredictiveTakeToDst(src, dst);
      bool can_add = m_Entity.GetInventory().CanAddEntityInCargo(item, item.GetInventory().GetFlipCargo());
      bool in_cargo = !player.GetInventory().HasEntityInInventory(item) || !m_Entity.GetInventory().HasEntityInCargo(item);
      if (can_add && in_cargo)
        SplitItemUtils.TakeOrSplitToInventory(player, m_Entity, item);
    }
  }
References GetEntity(), GetGame(), GetItemPreviewItem(), GetPlayer(), m_Entity, and SplitItemUtils::TakeOrSplitToInventory().
OnDropReceivedFromHeader() [2/2]
override void ClosableContainer::OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline protected
Definition at line 591 of file ContainerWithCargoAndAttachments.c.
  {
    TakeAsAttachment(w, receiver);
  }
OnDropReceivedFromHeader2()
void ClosableContainer::OnDropReceivedFromHeader2 (Widget w, int x, int y, Widget receiver) inline protected
Definition at line 596 of file ContainerWithCargoAndAttachments.c.
  {
    TakeAsAttachment(w, receiver);
  }
Open()
override void ClosableContainer::Open () inline protected
Definition at line 69 of file ContainerWithCargo.c.
  {
    if (!m_LockCargo)
    {
      ItemManager.GetInstance().SetDefaultOpenState(m_Entity.GetType(), true);
      m_Closed = false;
      SetOpenForSlotIcon(true);
      OnShow();
      m_Parent.m_Parent.Refresh();
    }
    if (m_SlotIcon)
      m_SlotIcon.GetRadialIconPanel().Show(!m_LockCargo);
  }
References ItemManager::GetInstance(), m_Entity, m_Parent, and OnShow().
RecomputeContainers()
void ClosableContainer::RecomputeContainers () inline protected
Definition at line 40 of file ContainerWithCargoAndAttachments.c.
  {
    m_Body.Clear();
    if (m_Atts)
      m_Body.Insert(m_Atts.GetWrapper());
    if (m_CargoGrid)
      m_Body.Insert(m_CargoGrid);
    GameInventory inv = m_Entity.GetInventory();
    for (int i = 0; i < inv.AttachmentCount(); i++)
    {
      EntityAI ent = inv.GetAttachmentFromIndex(i);
      if (ent)
      {
        AttachmentsWrapper att = m_AttachmentAttachmentsContainers.Get(ent);
        if (att)
          m_Body.Insert(att);
        CargoContainer cargo = m_AttachmentCargos.Get(ent);
        if (cargo)
          m_Body.Insert(cargo);
      }
    }
  }
References m_Entity.
SetDefaultFocus()
override void ClosableContainer::SetDefaultFocus (bool while_micromanagment_mode = false) inline protected
Definition at line 143 of file ContainerWithCargo.c.
  {
    m_CargoGrid.SetDefaultFocus(while_micromanagment_mode);
  }
SetEntity() [1/2]
void ClosableContainer::SetEntity (EntityAI entity, bool immedUpdate = true) inline protected
Definition at line 240 of file ContainerWithCargoAndAttachments.c.
  {
    m_Entity = entity;
    m_Atts = new Attachments(this, m_Entity);
    m_Atts.InitAttachmentGrid(SORT_ATTACHMENTS_OWN);
    m_AttachmentSlotsSorted = m_Atts.GetSlotsSorted();
    m_Entity.GetOnItemAttached().Insert(AttachmentAdded);
    m_Entity.GetOnItemDetached().Insert(AttachmentRemoved);
    m_ClosableHeader.SetItemPreview(m_Entity);
    CheckHeaderDragability();
    if (m_Entity.GetInventory().GetCargo())
    {
      m_CargoGrid = new CargoContainer(this, false);
      m_CargoGrid.GetRootWidget().SetSort(SORT_CARGO_OWN);
      m_CargoGrid.SetEntity(m_Entity, 0, immedUpdate);
      m_CargoGrid.UpdateHeaderText(); // TODO: refresh?
      Insert(m_CargoGrid);
    }
    else
    {
      string name = m_Entity.GetDisplayName();
      name.ToUpper();
      m_ClosableHeader.SetName(name);
    }
    m_AttachmentCargos = new map<EntityAI, ref CargoContainer>;
    m_AttachmentAttachmentsContainers = new map<EntityAI, ref AttachmentsWrapper>;
    m_AttachmentAttachments = new map<EntityAI, ref Attachments>;
    (Container.Cast(m_Parent)).Insert(this);
    foreach (int slot_id : m_AttachmentSlotsSorted)
    {
      EntityAI item = m_Entity.GetInventory().FindAttachment(slot_id);
      if (item)
        AttachmentAddedEx(item, InventorySlots.GetSlotName(slot_id), m_Entity, false);
    }
    RecomputeContainers();
    if (m_CargoGrid)
    {
      bool hideCargo = m_Entity.GetInventory().IsInventoryLockedForLockType(HIDE_INV_FROM_SCRIPT) || !m_Entity.CanDisplayCargo() || m_ForcedHide;
      if (m_CargoGrid.IsVisible() && hideCargo)
        HideCargo();
      else if (!m_CargoGrid.IsVisible() && !hideCargo)
        ShowCargo();
    }
    if (IsDisplayable())
      SetOpenState(true);
    else
      SetOpenState(false);
    if (immedUpdate)
      m_Parent.m_Parent.Refresh();
    RecomputeOpenedContainers();
  }
References InventorySlots::GetSlotName(), m_Entity, m_Parent, and name.
SetEntity() [2/2]
void ClosableContainer::SetEntity (EntityAI entity, int cargo_index = 0, bool immedUpdate = true) inline protected
Definition at line 178 of file ContainerWithCargo.c.
  {
    m_Entity = entity;
    m_CargoIndex = cargo_index;
    SetOpenState(true);
    m_CargoGrid.SetEntity(entity, immedUpdate);
    m_CargoGrid.UpdateHeaderText();
    m_ClosableHeader.SetItemPreview(entity);
    CheckHeaderDragability();
    (Container.Cast(m_Parent)).Insert(this, -1, false);
    if (m_Entity.GetInventory().IsInventoryLockedForLockType(HIDE_INV_FROM_SCRIPT) || !m_Entity.CanDisplayCargo())
      LockCargo(true);
    else
      LockCargo(false);
    if (immedUpdate)
    {
      Refresh();
      GetMainWidget().Update();
    }
  }
References LockCargo(), m_Entity, m_Parent, and Refresh().
ShowCargo()
void ClosableContainer::ShowCargo () inline protected
Definition at line 316 of file ContainerWithCargoAndAttachments.c.
  {
    if (m_CargoGrid)
    {
      if (!m_CargoGrid.IsVisible())
      {
        m_CargoGrid.OnShow();
        RecomputeOpenedContainers();
      }
    }
  }
SplitItem()
override bool ClosableContainer::SplitItem () inline protected
Definition at line 153 of file ContainerWithCargo.c.
  {
    return m_CargoGrid.SplitItem();
  }
TakeAsAttachment()
void ClosableContainer::TakeAsAttachment (Widget w, Widget receiver) inline protected
Definition at line 503 of file ContainerWithCargoAndAttachments.c.
  {
    ItemManager.GetInstance().HideDropzones();
    ItemManager.GetInstance().SetIsDragging(false);
    SlotsIcon slots_icon;
    EntityAI receiver_item;
    int slot_id = -1;
    bool is_reserved = false;
    EntityAI attached_entity;
    receiver.GetUserData(slots_icon);
    //string name = receiver.GetName();
    //name.Replace("PanelWidget", "Render");
    //ItemPreviewWidget receiver_iw = ItemPreviewWidget.Cast( receiver.FindAnyWidget(name) );
    if (slots_icon)
    {
      receiver_item = slots_icon.GetEntity();
      slot_id = slots_icon.GetSlotID();
      attached_entity = slots_icon.GetSlotParent();
      is_reserved = slots_icon.IsReserved();
    }
    EntityAI item = GetItemPreviewItem(w);
    if (!item)
      return;
    ItemBase item_base = ItemBase.Cast(item);
    InventoryLocation il = new InventoryLocation;
    float stackable;
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (!item.GetInventory().CanRemoveEntity() || !player.CanManipulateInventory())
      return;
    EntityAI target_att_entity = m_Entity;
    Weapon_Base wpn;
    Magazine mag;
    if (Class.CastTo(wpn, m_Entity) && Class.CastTo(mag, item))
    {
      if (player.GetWeaponManager().CanAttachMagazine(wpn, mag))
        player.GetWeaponManager().AttachMagazine(mag);
    }
    else if (receiver_item && !is_reserved)
    {
      if ((ItemBase.Cast(receiver_item)).CanBeCombined(ItemBase.Cast(item)))
        (ItemBase.Cast(receiver_item)).CombineItemsClient(ItemBase.Cast(item));
      else if (GameInventory.CanSwapEntitiesEx(receiver_item, item))
      {
        if (!receiver_item.GetInventory().CanRemoveEntity())
          return;
        GetGame().GetPlayer().PredictiveSwapEntities(receiver_item, item);
      }
      else if (receiver_item.GetInventory().CanAddAttachment(item))
        player.PredictiveTakeEntityToTargetAttachment(receiver_item, item);
    }
    else if (attached_entity && attached_entity.GetInventory().CanAddAttachmentEx(item, slot_id))
    {
      stackable = item_base.GetTargetQuantityMax(slot_id);
      if (stackable == 0 || stackable >= item_base.GetQuantity())
        player.PredictiveTakeEntityToTargetAttachmentEx(attached_entity, item, slot_id);
      else if (stackable != 0 && stackable < item_base.GetQuantity())
        item_base.SplitIntoStackMaxClient(attached_entity, slot_id);
    }
    else if (attached_entity && attached_entity.GetInventory().CanAddAttachment(item))
    {
      attached_entity.GetInventory().FindFreeLocationFor(item, FindInventoryLocationType.ATTACHMENT, il);
      stackable = item_base.GetTargetQuantityMax(il.GetSlot());
      if (stackable == 0 || stackable >= item_base.GetQuantity())
        player.PredictiveTakeEntityToTargetAttachmentEx(attached_entity, item, il.GetSlot());
      else if (stackable != 0 && stackable < item_base.GetQuantity())
        item_base.SplitIntoStackMaxClient(attached_entity, il.GetSlot());
    }
    else if (m_Entity.GetInventory().CanAddAttachment(item))
    {
      m_Entity.GetInventory().FindFreeLocationFor(item, FindInventoryLocationType.ATTACHMENT, il);
      stackable = item_base.GetTargetQuantityMax(il.GetSlot());
      if (stackable == 0 || stackable >= item_base.GetQuantity())
        player.PredictiveTakeEntityToTargetAttachmentEx(m_Entity, item, il.GetSlot());
      else if (stackable != 0 && stackable < item_base.GetQuantity())
        item_base.SplitIntoStackMaxClient(m_Entity, il.GetSlot());
    }
    else if (m_Entity.GetInventory().CanAddEntityInCargo(item, item.GetInventory().GetFlipCargo()) && !m_Entity.GetInventory().HasEntityInCargo(item))
      SplitItemUtils.TakeOrSplitToInventory(PlayerBase.Cast(GetGame().GetPlayer()), m_Entity, item);
    /*else if( !player.GetInventory().HasEntityInInventory( item ) || !m_Entity.GetInventory().HasEntityInCargo( item ) )
      {
      SplitItemUtils.TakeOrSplitToInventory( PlayerBase.Cast( GetGame().GetPlayer() ), m_Entity, item );
      }*/
  }
References GameInventory::CanSwapEntitiesEx(), Class::CastTo(), CombineItemsClient(), GetGame(), ItemManager::GetInstance(), GetPlayer(), m_Entity, and SplitItemUtils::TakeOrSplitToInventory().
TakeIntoHands()
void ClosableContainer::TakeIntoHands (notnull PlayerBase player, notnull EntityAI item) inline protected
Definition at line 375 of file ContainerWithCargo.c.
  {
    ItemBase item_base = ItemBase.Cast(item);
    if (!item.GetInventory().CanRemoveEntity() || !player.CanManipulateInventory())
      return;
    float stackable = item_base.GetTargetQuantityMax();
    if (stackable == 0 || stackable >= item_base.GetQuantity())
      player.PredictiveTakeEntityToHands(item);
    else if (stackable != 0 && stackable < item_base.GetQuantity())
      item_base.SplitIntoStackMaxHandsClient(player);
  }
TransferItem()
override bool ClosableContainer::TransferItem () inline protected
Definition at line 163 of file ContainerWithCargo.c.
  {
    return m_CargoGrid.TransferItem();
  }
TransferItemToVicinity()
override bool ClosableContainer::TransferItemToVicinity () inline protected
Definition at line 168 of file ContainerWithCargo.c.
  {
    return m_CargoGrid.TransferItemToVicinity();
  }
UnfocusAll() [1/2]
override void ClosableContainer::UnfocusAll () inline protected
Definition at line 148 of file ContainerWithCargo.c.
  {
    m_CargoGrid.Unfocus();
  }
UnfocusAll() [2/2]
override void ClosableContainer::UnfocusAll () inline protected
Definition at line 199 of file ContainerWithCargoAndAttachments.c.
  {
    if (m_Atts)
      m_Atts.UnfocusAll();
    if (m_CargoGrid)
      m_CargoGrid.UnfocusAll();
    foreach (EntityAI e1, CargoContainer cargo : m_AttachmentCargos)
      cargo.UnfocusAll();
    foreach (EntityAI e2, Attachments att : m_AttachmentAttachments)
      att.UnfocusAll();
  }
UpdateInterval() [1/2]
override void ClosableContainer::UpdateInterval () inline protected
Definition at line 104 of file ContainerWithCargo.c.
  {
    if (m_Entity)
    {
      if (m_Entity.GetInventory().IsInventoryLockedForLockType(HIDE_INV_FROM_SCRIPT) || !m_Entity.CanDisplayCargo())
      {
        LockCargo(true);
        if (m_CargoGrid.IsVisible())
          RecomputeOpenedContainers();
      }
      else
      {
        LockCargo(false);
        if (!m_CargoGrid.IsVisible())
          RecomputeOpenedContainers();
      }
      super.UpdateInterval();
      m_CargoGrid.UpdateInterval();
      bool hide = m_LockCargo || ItemManager.GetInstance().GetDraggedItem() == m_Entity;
      if (!hide)
        SetOpenForSlotIcon(IsOpened());
      if (m_SlotIcon)
        m_SlotIcon.GetRadialIconPanel().Show(!hide);
    }
  }
References ItemManager::GetInstance(), IsOpened(), LockCargo(), and m_Entity.
UpdateInterval() [2/2]
override void ClosableContainer::UpdateInterval () inline protected
Definition at line 166 of file ContainerWithCargoAndAttachments.c.
  {
    if (m_Entity)
    {
      if (m_CargoGrid)
      {
        bool hideCargo = m_Entity.GetInventory().IsInventoryLockedForLockType(HIDE_INV_FROM_SCRIPT) || !m_Entity.CanDisplayCargo() || m_ForcedHide;
        if (m_CargoGrid.IsVisible() && hideCargo)
          HideCargo();
        else if (!m_CargoGrid.IsVisible() && !hideCargo)
          ShowCargo();
        m_CargoGrid.UpdateInterval();
      }
      if (m_SlotIcon)
      {
        bool hide = m_LockCargo || ItemManager.GetInstance().GetDraggedItem() == m_Entity;
        if (!hide)
          SetOpenForSlotIcon(IsOpened());
        m_SlotIcon.GetRadialIconPanel().Show(!hide);
      }
      super.UpdateInterval();
    }
  }
References ItemManager::GetInstance(), IsOpened(), and m_Entity.
Member Data Documentation
m_AttachmentAttachments
ref map<EntityAI, ref Attachments> ClosableContainer::m_AttachmentAttachments protected
Definition at line 8 of file ContainerWithCargoAndAttachments.c.
m_AttachmentAttachmentsContainers
ref map<EntityAI, ref AttachmentsWrapper> ClosableContainer::m_AttachmentAttachmentsContainers protected
Definition at line 7 of file ContainerWithCargoAndAttachments.c.
m_AttachmentCargos
ref map<EntityAI, ref CargoContainer> ClosableContainer::m_AttachmentCargos protected
Definition at line 6 of file ContainerWithCargoAndAttachments.c.
m_AttachmentSlotsSorted
ref array<int> ClosableContainer::m_AttachmentSlotsSorted protected
Definition at line 9 of file ContainerWithCargoAndAttachments.c.
m_Atts
ref Attachments ClosableContainer::m_Atts protected
Definition at line 3 of file ContainerWithCargoAndAttachments.c.
m_CargoGrid
ref CargoContainer ClosableContainer::m_CargoGrid protected
Definition at line 3 of file ContainerWithCargo.c.
m_CargoIndex
int ClosableContainer::m_CargoIndex = -1 protected
Definition at line 4 of file ContainerWithCargo.c.
The documentation for this class was generated from the following files:
scripts/5_Mission/GUI/InventoryNew/Inherited/ContainerWithCargo.c
scripts/5_Mission/GUI/InventoryNew/Inherited/ContainerWithCargoAndAttachments.c