DayZ: Mouse API
Mouse API
System
returns index of defined key in InputDevice by its name
Enumerations
enum MouseState {
LEFT , RIGHT , MIDDLE , X ,
Y , WHEEL
}
Functions
proto native int GetMouseState (MouseState index)
proto void GetMousePos (out int x, out int y)
proto void GetScreenSize (out int x, out int y)
Detailed Description
returns index of defined key in InputDevice by its name
Enumeration Type Documentation
MouseState
enum MouseState
Enumerator
LEFT
RIGHT
MIDDLE
X
Y
WHEEL
Definition at line 310 of file EnSystem.c.
{
  LEFT,
  RIGHT,
  MIDDLE,
  X,
  Y,
  WHEEL
};
Function Documentation
GetMousePos()
proto void GetMousePos (out int x, out int y)
Referenced by DayZIntroScenePC::CharacterRotate(), DayZIntroScenePC::CharacterRotationStart(), UIScriptedMenu::DisplayHint(), DisplayHint(), Icon::FlagAction(), GetMouseDistance(), GetMousePointerAngle(), PlayerPreview::MouseButtonDown(), OnDraggingStart(), ScrollBarContainer::OnMouseButtonDown(), UIScriptedMenu::OnMouseButtonDown(), ScriptConsoleGeneralTab::OnMouseButtonDown(), ScriptConsoleSoundsTab::OnMouseButtonDown(), OnUpdate(), ItemManager::PrepareTooltip(), ScriptedWidgetEventHandler::ShowActionMenu(), HandsContainer::ShowActionMenuCombine(), ScriptedWidgetEventHandler::ShowTooltip(), CallQueue::Tick(), UIScriptedMenu::Update(), PlayerPreview::UpdateInterval(), ScriptConsoleGeneralTab::UpdateMousePos(), and ScriptConsoleSoundsTab::UpdateMousePos().
GetMouseState()
proto native int GetMouseState (MouseState index)
Returns state of mouse button. It's combination of number of release/pressed edges and mask MB_PRESSED_MASK that is set when button is pressed. If you want just to check if button is pressed, use this: if(GetMouseState(MouseState.LEFT) & MB_PRESSED_MASK)) Print("left button pressed");
Referenced by ScriptConsoleWeatherTab::OnChange(), WeaponDebug::OnCommandHandlerUpdate(), CallQueue::Tick(), and PlayerPreview::UpdateInterval().
GetScreenSize()
proto void GetScreenSize (out int x, out int y)
Referenced by BleedingIndicatorDropData::BleedingIndicatorDropData(), ActionTargetsCursor::BuildFixedCursor(), HitDirectionEffectBase::CalculateArrowPosition(), ItemManager::CalculateTooltipSlotPosition(), CheckWidth(), UIScriptedMenu::DisplayHint(), DisplayHint(), ScriptedWidgetEventHandler::GetOnScreenPosition(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::Init(), ItemManager::PrepareTooltip(), ScriptedWidgetEventHandler::Show(), and UIScriptedMenu::UpdateScale().