DayZ: EntityAI Class Reference
EntityAI Class Reference
Protected Member Functions
void InitImpactSoundData ()
AbstractWave PlaySound (SoundObject so, SoundObjectBuilder sob)
void PlaySoundByAnimEvent (EAnimSoundEventID id)
string GetImpactSurfaceType (IEntity other, Contact impact)
string GetImpactSurfaceTypeEx (IEntity other, Contact impact, out int liquid)
string GetRuinedMeleeAmmoType ()
returns ammo (projectile) used in melee if the item is destroyed. Override higher for specific use
float ProcessImpactSound (IEntity other, Contact extra, float weight, out int surfaceHash)
float ProcessImpactSoundEx (IEntity other, Contact extra, float weight, out int surfaceHash, out int liquidType)
override bool CanDropEntity (notnull EntityAI item)
void OnItemInHandsChanged ()
bool NeedInventoryJunctureFromServer (notnull EntityAI item, EntityAI currParent, EntityAI newParent)
void LocalDestroyEntityInHands ()
void PredictiveMoveItemFromHandsToInventory ()
void JunctureDeleteItem (EntityAI item)
override bool CanBeSkinned ()
void UpdateInventoryMenu ()
bool IsInventorySoftLocked ()
void SetInventorySoftLock (bool status)
bool IsInTransport ()
returns true if man is in transport, false otherwise
void StopDeathDarkeningEffect ()
bool PhysicalPredictiveDropItem (EntityAI entity, bool heavy_item_only=true)
void SetProcessUIWarning (bool state)
void OnGameplayDataHandlerSync ()
bool CanPlaceItem (EntityAI item)
void HandleByCrewMemberState (ECrewMemberState state)
vector GetTransportCameraOffset ()
int GetAnimInstance ()
int GetSeatAnimationType (int posIdx)
int Get3rdPersonCameraType ()
bool CrewCanGetThrough (int posIdx)
bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
bool CanReachSeatFromDoors (string pSeatSelection, vector pFromPos, float pDistance=1.0)
bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
int GetSeatIndexFromDoor (string pDoorSelection)
bool IsIgnoredObject (Object o)
bool IsAreaAtDoorFree (int currentSeat, float maxAllowedObjHeight, inout vector extents, out vector transform[4])
bool IsAreaAtDoorFree (int currentSeat, float maxAllowedObjHeight=0.5, float horizontalExtents=0.5, float playerHeight=1.7)
Shape DebugFreeAreaAtDoor (int currentSeat, float maxAllowedObjHeight=0.5, float horizontalExtents=0.5, float playerHeight=1.7)
void JunctureTakeEntityToHands (notnull EntityAI item)
hand juncture
void PredictiveTakeEntityToHands (EntityAI item)
void LocalTakeEntityToHands (EntityAI item)
void ServerTakeEntityToHands (EntityAI item)
void TakeEntityToHandsImpl (InventoryMode mode, EntityAI item)
bool ReplaceItemWithNewImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
!hand -> !hand replace
bool LocalReplaceItemWithNew (ReplaceItemWithNewLambdaBase lambda)
bool ServerReplaceItemWithNew (ReplaceItemWithNewLambdaBase lambda)
bool ReplaceItemElsewhereWithNewInHandsImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
!hand replace -> hand
bool LocalReplaceItemElsewhereWithNewInHands (ReplaceItemWithNewLambdaBase lambda)
bool ServerReplaceItemElsewhereWithNewInHands (ReplaceItemWithNewLambdaBase lambda)
bool ReplaceItemInHandsWithNewImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
hand replace
bool LocalReplaceItemInHandsWithNew (ReplaceItemWithNewLambdaBase lambda)
bool ServerReplaceItemInHandsWithNew (ReplaceItemWithNewLambdaBase lambda)
bool ReplaceItemInHandsWithNewElsewhereImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
hand replace2
bool LocalReplaceItemInHandsWithNewElsewhere (ReplaceItemWithNewLambdaBase lambda)
bool ServerReplaceItemInHandsWithNewElsewhere (ReplaceItemWithNewLambdaBase lambda)
bool JunctureTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
to inv juncture
override bool PredictiveTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
override bool LocalTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
override bool ServerTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
bool TakeEntityToInventoryImpl (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item)
bool JunctureTakeEntityToCargo (notnull EntityAI item)
to cgo juncture
override bool PredictiveTakeEntityToCargo (notnull EntityAI item)
override bool LocalTakeEntityToCargo (notnull EntityAI item)
override bool ServerTakeEntityToCargo (notnull EntityAI item)
bool TakeEntityToCargoImpl (InventoryMode mode, notnull EntityAI item)
bool JunctureTakeEntityAsAttachment (notnull EntityAI item)
as att juncture
override bool PredictiveTakeEntityAsAttachment (notnull EntityAI item)
override bool LocalTakeEntityAsAttachment (notnull EntityAI item)
override bool ServerTakeEntityAsAttachment (notnull EntityAI item)
bool TakeEntityAsAttachmentImpl (InventoryMode mode, notnull EntityAI item)
bool JunctureTakeEntityAsAttachmentEx (notnull EntityAI item, int slot)
as att ex juncture
override bool PredictiveTakeEntityAsAttachmentEx (notnull EntityAI item, int slot)
override bool LocalTakeEntityAsAttachmentEx (notnull EntityAI item, int slot)
override bool ServerTakeEntityAsAttachmentEx (notnull EntityAI item, int slot)
bool TakeEntityAsAttachmentExImpl (InventoryMode mode, notnull EntityAI item, int slot)
bool JunctureSwapEntities (notnull EntityAI item1, notnull EntityAI item2)
swap juncture
bool PredictiveSwapEntities (notnull EntityAI item1, notnull EntityAI item2)
bool LocalSwapEntities (notnull EntityAI item1, notnull EntityAI item2)
bool ServerSwapEntities (notnull EntityAI item1, notnull EntityAI item2)
bool SwapEntitiesImpl (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2)
bool JunctureForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
ForceSwap juncture.
bool PredictiveForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
bool LocalForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
bool ServerForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
bool ForceSwapEntitiesImpl (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
bool JunctureTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
to target inv juncture
override bool PredictiveTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
bool PredictiveTakeOrSwapAttachment (notnull EntityAI item)
override bool LocalTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
bool TakeEntityToTargetInventoryImpl (InventoryMode mode, notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
bool JunctureTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
to target cgo ex juncture
override bool PredictiveTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
override bool LocalTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
override bool ServerTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
bool TakeEntityToTargetCargoExImpl (InventoryMode mode, notnull CargoBase cargo, notnull EntityAI item, int row, int col)
bool JunctureTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
to target cgo juncture
override bool PredictiveTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
override bool LocalTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
override bool ServerTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
bool TakeEntityToTargetCargoImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
bool JunctureTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
to target att ex juncture
override bool PredictiveTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
override bool LocalTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
override bool ServerTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
bool TakeEntityToTargetAttachmentExImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item, int slot)
bool JunctureTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
to target att juncture
override bool PredictiveTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
override bool LocalTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
override bool ServerTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
bool TakeEntityToTargetAttachmentImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
bool JunctureTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
to dst juncture
override bool PredictiveTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
override bool LocalTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
override bool ServerTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
bool TakeToDstImpl (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
proto native bool StatRegister (string name)
proto native float StatGet (string name)
Gets counter value of the specified stat type.
proto void StatGetCounter (string name, out string value)
Gets counter value as string of the specified stat type.
proto void StatGetAsTime (string name, out string value)
Gets counter value as formatted time string of the specified stat type.
proto native void StatUpdate (string name, float value)
Updates stat counter with given value.
proto native void StatUpdateByTime (string name)
Updates stat counter by time.
proto native void StatUpdateByPosition (string name)
Updates stat counter by player's actual position.
proto native void StatUpdateByGivenPos (string name, vector pos)
Updates stat counter by given position.
proto native void StatInvokeUpdate ()
proto native void StatSyncToClient ()
Private Member Functions
proto native int GetLaddersCount ()
proto native vector GetLadderPosTop (int ladderIndex)
proto native vector GetLadderPosBottom (int ladderIndex)
proto native int GetDoorIndex (int componentIndex)
Gets the index of the door based on the view geometry component index.
proto native int GetDoorCount ()
Returns the number of the doors in the building.
proto native bool IsDoorOpen (int index)
When the door is requested to be fully open (animation wanted phase is greater than 0.5)
proto native bool IsDoorOpening (int index)
When the wanted phase is at the open phase target (1.0)
proto native bool IsDoorOpeningAjar (int index)
When the wanted phase is at the ajar phase target (0.2)
proto native bool IsDoorClosing (int index)
When the wanted phase is at the close phase target (0.0)
proto native bool IsDoorOpened (int index)
When the phase is at the open phase target (1.0)
proto native bool IsDoorOpenedAjar (int index)
When the phase is at the ajar phase target (0.2)
proto native bool IsDoorClosed (int index)
When the phase is at the close phase target (0.0)
proto native bool IsDoorLocked (int index)
When the door is locked.
proto native void PlayDoorSound (int index)
Plays the appropriate sound at the door, based on animation phase and state.
proto native void OpenDoor (int index)
Attempts to open the door.
proto native void CloseDoor (int index)
Attempts to close the door.
proto native void LockDoor (int index, bool force=false)
Locks the door if not already locked, resets the door health. 'force = true' will close the door if open.
proto native void UnlockDoor (int index)
Unlocks the door if locked.
proto native vector GetDoorSoundPos (int index)
Position in world space for where the door sounds are played from.
proto native float GetDoorSoundDistance (int index)
Audible distance for the door sound.
proto native void OutputDoorLog ()
Requires special build as logging is disabled even on internal builds due to memory usage. Used for checking of possible causes of navmesh desync.
int GetNearestDoorBySoundPos (vector position)
Gets the nearest door based on the sound position (quick and dirty function for debugging)
void OnDoorOpenStart (DoorStartParams params)
Event for when the door starts opening.
void OnDoorOpenFinish (DoorFinishParams params)
Event for when the door finishes opening.
void OnDoorOpenAjarStart (DoorStartParams params)
Event for when the door starts opening ajarred (usually after unlock)
void OnDoorOpenAjarFinish (DoorFinishParams params)
Event for when the door finishes opening ajarred (usually after unlock)
void OnDoorCloseStart (DoorStartParams params)
Event for when the door starts closing.
void OnDoorCloseFinish (DoorFinishParams params)
Event for when the door finishes closing.
void OnDoorLocked (DoorLockParams params)
Event for when the door is locked.
void OnDoorUnlocked (DoorLockParams params)
Event for when the door is unlocked.
bool CanDoorBeOpened (int doorIndex, bool checkIfLocked=false)
bool CanDoorBeClosed (int doorIndex)
bool CanDoorBeLocked (int doorIndex)
Check if the door is closed and if the door is unlocked.
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
override bool OnAction (int action_id, Man player, ParamsReadContext ctx)
override bool IsBuilding ()
override bool CanObstruct ()
override bool IsHealthVisible ()
void Building ()
override bool IsInventoryVisible ()
override int GetMeleeTargetType ()
proto native InventoryItemType GetInventoryItemType ()
proto native void SwitchOn (bool onOff)
Some inventoryItem devices can be switched on/off (radios, transmitters)
proto native bool IsOn ()
Some inventoryItem devices can be switched on/off (radios, transmitters)
proto native void EnableCollisionsWithCharacter (bool state)
collisions with character
proto native bool HasCollisionsWithCharacter ()
proto native MeleeCombatData GetMeleeCombatData ()
proto native void ThrowPhysically (DayZPlayer player, vector force, bool collideWithCharacters=true)
proto native void ForceFarBubble (bool state)
Sets the item to use the server configured 'networkRangeFar' instead of 'networkRangeNear'.
void InventoryItem ()
void OnRightClick ()
event bool OnUseFromInventory (Man owner)
string GetTooltip ()
Get tooltip text.
override bool IsInventoryItem ()
int GetMeleeMode ()
int GetMeleeHeavyMode ()
int GetMeleeSprintMode ()
override bool IsMeleeWeapon ()
bool IsMeleeFinisher ()
void PlayImpactSound (float weight, float velocity, int surfaceHash)
proto native UAInterface GetInputInterface ()
Returns player's input interface.
proto native PlayerIdentity GetIdentity ()
Returns player's identity.
proto native EntityAI GetDrivingVehicle ()
Returns vehicle which this Man object is driving. If this Man object isn't as driver of any vehicle it will return NULL.
proto native owned string GetCurrentWeaponMode ()
proto native void SetSpeechRestricted (bool state)
Set speech restriction.
proto native bool IsSpeechRestricted ()
Check if player has resctricted speech.
proto native void SetFaceTexture (string texture_name)
Texture that is used on the Man's face and hands.
proto native void SetFaceMaterial (string material_name)
Material that is used on the Man's face and hands.
proto native bool IsSoundInsideBuilding ()
proto native bool IsCameraInsideVehicle ()
proto native owned string GetMasterAttenuation ()
proto native void SetMasterAttenuation (string masterAttenuation)
void Man ()
override bool IsMan ()
override bool IsHealthVisible ()
override bool HasFixedActionTargetCursorPosition ()
bool IsUnconscious ()
int GetPlayerState ()
void AddItemToDelete (EntityAI item)
void Transport ()
override int GetMeleeTargetType ()
proto native void Synchronize ()
Synchronizes car's state in case the simulation is not running.
proto native int CrewSize ()
Returns crew capacity of this vehicle.
proto native int CrewPositionIndex (int componentIdx)
proto native int CrewMemberIndex (Human player)
proto native Human CrewMember (int posIdx)
proto void CrewEntry (int posIdx, out vector pos, out vector dir)
Reads entry point and direction into vehicle on given position in model space.
proto void CrewEntryWS (int posIdx, out vector pos, out vector dir)
Reads entry point and direction into vehicle on given position in world space.
proto void CrewTransform (int posIdx, out vector mat[4])
Returns crew transformation indside vehicle in model space.
proto void CrewTransformWS (int posIdx, out vector mat[4])
Returns crew transformation indside vehicle in world space.
proto native void CrewGetIn (Human player, int posIdx)
Performs transfer of player from world into vehicle on given position.
proto native Human CrewGetOut (int posIdx)
Performs transfer of player from vehicle into world from given position.
proto native void CrewDeath (int posIdx)
Handles death of player in vehicle and awakes its physics if needed.
override bool IsTransport ()
override bool IsIgnoredByConstruction ()
override bool IsHealthVisible ()
override bool ShowZonesHealth ()
bool IsAnyCrewPresent ()
float GetTransportCameraDistance ()
void MarkCrewMemberUnconscious (int crewMemberIndex)
void MarkCrewMemberDead (int crewMemberIndex)
void AdvancedCommunication ()
void TurnOnTransmitter ()
void TurnOffTransmitter ()
void InitializeActions ()
override void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
void SetActions ()
void AddAction (typename actionName)
void RemoveAction (typename actionName)
Private Attributes
ref TIntArray m_InteractActions
SoundLookupTable m_SoundImpactTable
float m_SoundContactTickTime
bool m_IsMeleeWeapon = false
ref TIntArray m_SingleUseActions
ref TIntArray m_ContinuousActions
TInputActionMap m_InputActionMap
bool m_ActionsInitialize
Static Private Attributes
const float SOUND_CONTACT_SKIP = 0.33
static ref map< typename, ref TInputActionMap > m_AdvComTypeActionsMap = new map<typename, ref TInputActionMap>
ref ScriptInvoker m_OnItemAddedToHands
ref ScriptInvoker m_OnItemRemovedFromHands
HumanInventory GetHumanInventory ()
inventory
ScriptInvoker GetOnItemAddedToHands ()
ScriptInvoker GetOnItemRemovedFromHands ()
void EEItemIntoHands (EntityAI item)
void EEItemOutOfHands (EntityAI item)
bool JunctureDropEntity (notnull EntityAI item)
drop juncture
override bool PredictiveDropEntity (notnull EntityAI item)
override bool LocalDropEntity (notnull EntityAI item)
override bool ServerDropEntity (notnull EntityAI item)
bool DropEntityImpl (InventoryMode mode, notnull EntityAI owner, notnull EntityAI item)
Detailed Description
Base native class of all vehicles in game.
Definition at line 5 of file Building.c.
Member Function Documentation
AddAction()
void EntityAI::AddAction (typename actionName) inline private
Definition at line 85 of file AdvancedCommunication.c.
  {
    ActionBase action = ActionManagerBase.GetAction(actionName);
    if (!action)
    {
      Debug.LogError("Action " + actionName + " dosn't exist!");
      return;
    }
    typename ai = action.GetInputType();
    if (!ai)
    {
      m_ActionsInitialize = false;
      return;
    }
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (!action_array)
    {
      action_array = new array<ActionBase_Basic>;
      m_InputActionMap.Insert(ai, action_array);
    }
    if (LogManager.IsActionLogEnable())
      Debug.ActionLog(action.ToString() + " -> " + ai, this.ToString(), "n/a", "Add action");
    action_array.Insert(action);
  }
References Debug::ActionLog(), LogManager::IsActionLogEnable(), Debug::LogError(), m_ActionsInitialize, and m_InputActionMap.
AddItemToDelete()
void EntityAI::AddItemToDelete (EntityAI item) private
AdvancedCommunication()
void EntityAI::AdvancedCommunication () inline private
Definition at line 7 of file AdvancedCommunication.c.
  {
    if (!GetGame().IsDedicatedServer())
    {
      if (GetGame().GetPlayer())
        m_ActionsInitialize = false;
    }
  }
References GetGame(), GetPlayer(), and m_ActionsInitialize.
Building()
void EntityAI::Building () inline private
Definition at line 223 of file Building.c.
  {
    m_InteractActions = new TIntArray;
    g_Game.ConfigGetIntArray("cfgVehicles " + GetType() + " InteractActions", m_InteractActions);
  }
References g_Game, GetType(), and m_InteractActions.
CanBeSkinned()
override bool EntityAI::CanBeSkinned () inline protected
Definition at line 835 of file Man.c.
  {
    return true;
  }
CanDoorBeClosed()
bool EntityAI::CanDoorBeClosed (int doorIndex) inline private
Definition at line 143 of file Building.c.
  {
    return IsDoorOpen(doorIndex);
  }
CanDoorBeLocked()
bool EntityAI::CanDoorBeLocked (int doorIndex) inline private
Check if the door is closed and if the door is unlocked.
Definition at line 149 of file Building.c.
  {
    return (!IsDoorOpen(doorIndex) && !IsDoorLocked(doorIndex));
  }
CanDoorBeOpened()
bool EntityAI::CanDoorBeOpened (int doorIndex, bool checkIfLocked = false) inline private
Definition at line 125 of file Building.c.
  {
    if (IsDoorOpen(doorIndex))
      return false;
    if (checkIfLocked)
    {
      if (IsDoorLocked(doorIndex))
        return false;
    }
    else
    {
      if (!IsDoorLocked(doorIndex))
        return false;
    }
    return true;
  }
CanDropEntity()
override bool EntityAI::CanDropEntity (notnull EntityAI item) inline protected
Definition at line 142 of file Man.c.
{ return true; }
CanObstruct()
override bool EntityAI::CanObstruct () inline private
Definition at line 211 of file Building.c.
  {
    return true;
  }
CanPlaceItem()
bool EntityAI::CanPlaceItem (EntityAI item) protected
CanReachDoorsFromSeat()
bool EntityAI::CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline protected
Definition at line 160 of file Transport.c.
  {
#ifndef CFGMODS_DEFINE_TEST
    return false;
#else
    return true;
#endif
  }
CanReachSeatFromDoors()
bool EntityAI::CanReachSeatFromDoors (string pSeatSelection, vector pFromPos, float pDistance = 1.0) inline protected
Definition at line 151 of file Transport.c.
  {
#ifndef CFGMODS_DEFINE_TEST
    return false;
#else
    return true;
#endif
  }
CanReachSeatFromSeat()
bool EntityAI::CanReachSeatFromSeat (int currentSeat, int nextSeat) inline protected
Definition at line 142 of file Transport.c.
  {
#ifndef CFGMODS_DEFINE_TEST
    return false;
#else
    return true;
#endif
  }
CloseDoor()
proto native void EntityAI::CloseDoor (int index) private
Attempts to close the door.
CrewCanGetThrough()
bool EntityAI::CrewCanGetThrough (int posIdx) inline protected
Definition at line 133 of file Transport.c.
  {
#ifndef CFGMODS_DEFINE_TEST
    return false;
#else
    return true;
#endif
  }
CrewDeath()
proto native void EntityAI::CrewDeath (int posIdx) private
Handles death of player in vehicle and awakes its physics if needed.
CrewEntry()
proto void EntityAI::CrewEntry (int posIdx, out vector pos, out vector dir) private
Reads entry point and direction into vehicle on given position in model space.
CrewEntryWS()
proto void EntityAI::CrewEntryWS (int posIdx, out vector pos, out vector dir) private
Reads entry point and direction into vehicle on given position in world space.
CrewGetIn()
proto native void EntityAI::CrewGetIn (Human player, int posIdx) private
Performs transfer of player from world into vehicle on given position.
CrewGetOut()
proto native Human EntityAI::CrewGetOut (int posIdx) private
Performs transfer of player from vehicle into world from given position.
CrewMember()
proto native Human EntityAI::CrewMember (int posIdx) private
Returns crew member based on position index. Null can be returned if no Human is present on the given position.
CrewMemberIndex()
proto native int EntityAI::CrewMemberIndex (Human player) private
Returns crew member index based on player's instance. -1 is returned when the player is not isnide.
CrewPositionIndex()
proto native int EntityAI::CrewPositionIndex (int componentIdx) private
Returns crew member index based on action component index. -1 is returned when no crew position corresponds to given component index.
CrewSize()
proto native int EntityAI::CrewSize () private
Returns crew capacity of this vehicle.
CrewTransform()
proto void EntityAI::CrewTransform (int posIdx, out vector mat[4]) private
Returns crew transformation indside vehicle in model space.
CrewTransformWS()
proto void EntityAI::CrewTransformWS (int posIdx, out vector mat[4]) private
Returns crew transformation indside vehicle in world space.
DebugFreeAreaAtDoor()
Shape EntityAI::DebugFreeAreaAtDoor (int currentSeat, float maxAllowedObjHeight = 0.5, float horizontalExtents = 0.5, float playerHeight = 1.7) inline protected
Definition at line 272 of file Transport.c.
  {
    int color = ARGB(20, 0, 255, 0);
    vector transform[4];
    vector extents;
    extents[0] = horizontalExtents;
    extents[1] = playerHeight;
    extents[2] = horizontalExtents;
    if (!IsAreaAtDoorFree(currentSeat, maxAllowedObjHeight, extents, transform))
      color = ARGB(20, 255, 0, 0);
    Shape shape = Debug.DrawBox(-extents * 0.5, extents * 0.5, color);
    shape.SetMatrix(transform);
    return shape;
  }
References ARGB(), Debug::DrawBox(), Transport::IsAreaAtDoorFree(), and Shape.
DropEntityImpl()
bool EntityAI::DropEntityImpl (InventoryMode mode, notnull EntityAI owner, notnull EntityAI item) inline protected
Definition at line 133 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " ::DropEntity(" + typename.EnumToString(InventoryMode, mode) + ") item=" + Object.GetDebugName(item));
    bool code = GetHumanInventory().DropEntity(mode, owner, item);
    UpdateInventoryMenu();
    return code;
  }
References HumanInventory::DropEntity(), GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by JunctureDropEntity(), LocalDropEntity(), PredictiveDropEntity(), and ServerDropEntity().
EEItemIntoHands()
void EntityAI::EEItemIntoHands (EntityAI item) inline protected
Definition at line 89 of file Man.c.
  {
    SetWeightDirty();
    if (m_OnItemAddedToHands)
      m_OnItemAddedToHands.Invoke(item, this);
  }
EEItemOutOfHands()
void EntityAI::EEItemOutOfHands (EntityAI item) inline protected
Definition at line 96 of file Man.c.
  {
    SetWeightDirty();
    if (m_OnItemRemovedFromHands)
      m_OnItemRemovedFromHands.Invoke(item, this);
  }
EnableCollisionsWithCharacter()
proto native void EntityAI::EnableCollisionsWithCharacter (bool state) private
collisions with character
ForceFarBubble()
proto native void EntityAI::ForceFarBubble (bool state) private
Sets the item to use the server configured 'networkRangeFar' instead of 'networkRangeNear'.
ForceSwapEntitiesImpl()
bool EntityAI::ForceSwapEntitiesImpl (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) inline protected
Definition at line 566 of file Man.c.
  {
    bool code = false;
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + "  ForceSwapImpl(" + typename.EnumToString(InventoryMode, mode) + ") item1=" + Object.GetDebugName(item1) + " item2=" + item2.GetDebugName(this));
    code = GetHumanInventory().ForceSwapEntities(mode, item1, item2, item2_dst);
    UpdateInventoryMenu();
    if (!code)
      if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + "  ForceSwapEntitiesImpl - cannot Forceswap");
    return code;
  }
References HumanInventory::ForceSwapEntities(), GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by JunctureForceSwapEntities(), LocalForceSwapEntities(), PredictiveForceSwapEntities(), and ServerForceSwapEntities().
Get3rdPersonCameraType()
int EntityAI::Get3rdPersonCameraType () inline protected
Definition at line 123 of file Transport.c.
  {
#ifndef CFGMODS_DEFINE_TEST
    Error("Get3rdPersonCameraType() not implemented");
    return 0;
#else
    return 31;
#endif
  }
References Error().
GetActions()
override void EntityAI::GetActions (typename action_input_type , out array< ActionBase_Basic > actions) inline private
Definition at line 67 of file AdvancedCommunication.c.
  {
    if (!m_ActionsInitialize)
    {
      m_ActionsInitialize = true;
      InitializeActions();
    }
    actions = m_InputActionMap.Get(action_input_type);
  }
References InitializeActions(), m_ActionsInitialize, and m_InputActionMap.
GetAnimInstance()
int EntityAI::GetAnimInstance () inline protected
Definition at line 105 of file Transport.c.
  {
#ifndef CFGMODS_DEFINE_TEST
    Error("GetAnimInstance() not implemented");
    return 0;
#else
    return 2;
#endif
  }
References Error().
GetCurrentWeaponMode()
proto native owned string EntityAI::GetCurrentWeaponMode () private
GetDebugActions()
override void EntityAI::GetDebugActions (out TSelectableActionInfoArrayEx outputList) inline private
Definition at line 154 of file Building.c.
  {
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.BUILDING_OUTPUT_LOG, "Output Door Log", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.SEPARATOR, " --- ", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.BUILDING_PLAY_DOOR_SOUND, "Play Door Sound", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.BUILDING_OPEN_DOOR, "Open Door", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.BUILDING_CLOSE_DOOR, "Close Door", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.BUILDING_LOCK_DOOR, "Lock Door", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.BUILDING_UNLOCK_DOOR, "Unlock Door", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.SEPARATOR, " --- ", FadeColors.LIGHT_GREY));
    super.GetDebugActions(outputList);
  }
References SAT_DEBUG_ACTION.
GetDoorCount()
proto native int EntityAI::GetDoorCount () private
Returns the number of the doors in the building.
GetDoorIndex()
proto native int EntityAI::GetDoorIndex (int componentIndex) private
Gets the index of the door based on the view geometry component index.
GetDoorSoundDistance()
proto native float EntityAI::GetDoorSoundDistance (int index) private
Audible distance for the door sound.
GetDoorSoundPos()
proto native vector EntityAI::GetDoorSoundPos (int index) private
Position in world space for where the door sounds are played from.
GetDrivingVehicle()
proto native EntityAI EntityAI::GetDrivingVehicle () private
Returns vehicle which this Man object is driving. If this Man object isn't as driver of any vehicle it will return NULL.
GetHumanInventory()
HumanInventory EntityAI::GetHumanInventory () inline private
inventory
Definition at line 61 of file Man.c.
  {
    HumanInventory i = HumanInventory.Cast(GetInventory());
    return i;
  }
Referenced by DropEntityImpl(), ForceSwapEntitiesImpl(), LocalDestroyEntityInHands(), PredictiveMoveItemFromHandsToInventory(), ReplaceItemElsewhereWithNewInHandsImpl(), ReplaceItemInHandsWithNewElsewhereImpl(), ReplaceItemInHandsWithNewImpl(), ReplaceItemWithNewImpl(), SwapEntitiesImpl(), TakeEntityAsAttachmentExImpl(), TakeEntityAsAttachmentImpl(), TakeEntityToCargoImpl(), TakeEntityToHandsImpl(), TakeEntityToInventoryImpl(), and TakeToDstImpl().
GetIdentity()
proto native PlayerIdentity EntityAI::GetIdentity () private
Returns player's identity.
GetImpactSurfaceType()
string EntityAI::GetImpactSurfaceType (IEntity other, Contact impact) inline protected
Definition at line 152 of file InventoryItem.c.
  {
    string surface;
    int liquid = -1;
    return GetImpactSurfaceTypeEx(other, impact, liquid);
  }
GetImpactSurfaceTypeEx()
string EntityAI::GetImpactSurfaceTypeEx (IEntity other, Contact impact, out int liquid) inline protected
Definition at line 160 of file InventoryItem.c.
  {
    vector mins, maxs;
    GetWorldBounds(mins, maxs);
    vector size = maxs - mins;
    vector add = impact.RelativeVelocityBefore.Normalized() * size.Length();
    string surfaceImpact;
    if (DayZPhysics.GetHitSurfaceAndLiquid(
          Object.Cast(other),
          impact.Position + add,
          impact.Position - add,
          surfaceImpact,
          liquid))
      return surfaceImpact;
    string surface;
    GetGame().SurfaceUnderObjectEx(this, surface, surfaceImpact, liquid);
    return surfaceImpact;
  }
References GetGame(), and DayZPhysics::GetHitSurfaceAndLiquid().
GetInputInterface()
proto native UAInterface EntityAI::GetInputInterface () private
Returns player's input interface.
GetInventoryItemType()
proto native InventoryItemType EntityAI::GetInventoryItemType () private
GetLadderPosBottom()
proto native vector EntityAI::GetLadderPosBottom (int ladderIndex) private
GetLadderPosTop()
proto native vector EntityAI::GetLadderPosTop (int ladderIndex) private
GetLaddersCount()
proto native int EntityAI::GetLaddersCount () private
GetMasterAttenuation()
proto native owned string EntityAI::GetMasterAttenuation () private
GetMeleeCombatData()
proto native MeleeCombatData EntityAI::GetMeleeCombatData () private
GetMeleeHeavyMode()
int EntityAI::GetMeleeHeavyMode () inline private
Definition at line 71 of file InventoryItem.c.
  {
    return 1;
  }
GetMeleeMode()
int EntityAI::GetMeleeMode () inline private
Definition at line 66 of file InventoryItem.c.
  {
    return 0;
  }
GetMeleeSprintMode()
int EntityAI::GetMeleeSprintMode () inline private
Definition at line 76 of file InventoryItem.c.
  {
    return 2;
  }
GetMeleeTargetType() [1/2]
override int EntityAI::GetMeleeTargetType () inline private
Definition at line 234 of file Building.c.
  {
    return EMeleeTargetType.NONALIGNABLE;
  }
Referenced by DayZInfected::FightLogic().
GetMeleeTargetType() [2/2]
override int EntityAI::GetMeleeTargetType () inline private
Definition at line 14 of file Transport.c.
  {
    return EMeleeTargetType.NONALIGNABLE;
  }
GetNearestDoorBySoundPos()
int EntityAI::GetNearestDoorBySoundPos (vector position) inline private
Gets the nearest door based on the sound position (quick and dirty function for debugging)
Definition at line 66 of file Building.c.
  {
    float smallestDist = float.MAX;
    int nearestDoor = -1;
    int count = GetDoorCount();
    for (int i = 0; i < count; i++)
    {
      float dist = vector.DistanceSq(GetDoorSoundPos(i), position);
      if (dist < smallestDist)
      {
        nearestDoor = i;
        smallestDist = dist;
      }
    }
    return nearestDoor;
  }
References vector::DistanceSq().
GetOnItemAddedToHands()
ScriptInvoker EntityAI::GetOnItemAddedToHands () inline protected
Definition at line 72 of file Man.c.
  {
    if (!m_OnItemAddedToHands)
      m_OnItemAddedToHands = new ScriptInvoker();
    return m_OnItemAddedToHands;
  }
References m_OnItemAddedToHands.
GetOnItemRemovedFromHands()
ScriptInvoker EntityAI::GetOnItemRemovedFromHands () inline protected
Definition at line 81 of file Man.c.
  {
    if (!m_OnItemRemovedFromHands)
      m_OnItemRemovedFromHands = new ScriptInvoker;
    return m_OnItemRemovedFromHands;
  }
References m_OnItemRemovedFromHands.
GetPlayerState()
int EntityAI::GetPlayerState () inline private
Definition at line 50 of file Man.c.
  {
    if (IsAlive())
      return EPlayerStates.ALIVE;
    return EPlayerStates.DEAD;
  }
GetRuinedMeleeAmmoType()
string EntityAI::GetRuinedMeleeAmmoType () inline protected
returns ammo (projectile) used in melee if the item is destroyed. Override higher for specific use
Definition at line 182 of file InventoryItem.c.
  {
    return "MeleeSoft";
  }
GetSeatAnimationType()
int EntityAI::GetSeatAnimationType (int posIdx) inline protected
Definition at line 115 of file Transport.c.
  {
#ifndef CFGMODS_DEFINE_TEST
    Error("GetSeatAnimationType() not implemented");
#endif
    return 0;
  }
References Error().
GetSeatIndexFromDoor()
int EntityAI::GetSeatIndexFromDoor (string pDoorSelection) inline protected
Definition at line 169 of file Transport.c.
  {
    //Potientially could be fixed some other way, currently follows the unfortunate pattern that CanReachDoorsFromSeat has created
    switch (pDoorSelection)
    {
    case "DoorsDriver":
      return 0;
      break;
    case "DoorsCoDriver":
      return 1;
      break;
    case "DoorsCargo1":
      return 2;
      break;
    case "DoorsCargo2":
      return 3;
      break;
    }
    return -1;
  }
GetTooltip()
string EntityAI::GetTooltip () inline private
Get tooltip text.
Definition at line 53 of file InventoryItem.c.
  {
    string temp;
    if (!DescriptionOverride(temp))
      temp = ConfigGetString("descriptionShort");
    return temp;
  }
GetTransportCameraDistance()
float EntityAI::GetTransportCameraDistance () inline private
Definition at line 91 of file Transport.c.
  {
    return 4.0;
  }
GetTransportCameraOffset()
vector EntityAI::GetTransportCameraOffset () inline protected
Definition at line 100 of file Transport.c.
  {
    return "0 1.3 0";
  }
HandleByCrewMemberState()
void EntityAI::HandleByCrewMemberState (ECrewMemberState state) protected
HasCollisionsWithCharacter()
proto native bool EntityAI::HasCollisionsWithCharacter () private
HasFixedActionTargetCursorPosition()
override bool EntityAI::HasFixedActionTargetCursorPosition () inline private
Definition at line 43 of file Man.c.
  {
    return true;
  }
InitializeActions()
void EntityAI::InitializeActions () inline private
Definition at line 55 of file AdvancedCommunication.c.
  {
    m_InputActionMap = m_AdvComTypeActionsMap.Get(this.Type());
    if (!m_InputActionMap)
    {
      TInputActionMap iam = new TInputActionMap;
      m_InputActionMap = iam;
      SetActions();
      m_AdvComTypeActionsMap.Insert(this.Type(), m_InputActionMap);
    }
  }
References m_AdvComTypeActionsMap, m_InputActionMap, SetActions(), and Type.
InitImpactSoundData()
void EntityAI::InitImpactSoundData () inline protected
Definition at line 114 of file InventoryItem.c.
  {
#ifndef SERVER
    string soundImpactType = "default";
    if (ConfigIsExisting("soundImpactType"))
      soundImpactType = ConfigGetString("soundImpactType");
    m_SoundImpactTable = AnimSoundLookupTableBank.GetInstance().GetImpactTable(soundImpactType + "_Impact_LookupTable");
#endif
  }
References AnimSoundLookupTableBank().
InventoryItem()
void EntityAI::InventoryItem () inline private
Definition at line 33 of file InventoryItem.c.
  {
    InitImpactSoundData();
    if (ConfigIsExisting("isMeleeWeapon"))
      m_IsMeleeWeapon = ConfigGetBool("isMeleeWeapon");
  }
IsAnyCrewPresent()
bool EntityAI::IsAnyCrewPresent () inline private
Definition at line 80 of file Transport.c.
  {
    for (int index = 0; index < CrewSize(); ++index)
    {
      if (CrewMember(index) != null)
        return true;
    }
    return false;
  }
IsAreaAtDoorFree() [1/2]
bool EntityAI::IsAreaAtDoorFree (int currentSeat, float maxAllowedObjHeight, inout vector extents, out vector transform[4]) inline protected
Definition at line 215 of file Transport.c.
  {
    GetTransform(transform);
    vector crewPos;
    vector crewDir;
    CrewEntry(currentSeat, crewPos, crewDir);
    vector entry[4];
    entry[2] = crewDir;
    entry[0] = vector.Up * crewDir;
    entry[1] = entry[2] * entry[0];
    entry[3] = crewPos;
    Math3D.MatrixMultiply4(transform, entry, transform);
    vector position = transform[3];
    vector orientation = Math3D.MatrixToAngles(transform);
    position[1] = position[1] + maxAllowedObjHeight + (extents[1] * 0.5);
    array<Object> excluded = new array<Object>;
    array<Object> collided = new array<Object>;
    excluded.Insert(this);
    GetGame().IsBoxColliding(position, orientation, extents, excluded, collided);
    orientation.RotationMatrixFromAngles(transform);
    transform[3] = position;
    foreach (Object o : collided)
    {
      EntityAI e = EntityAI.Cast(o);
      if (IsIgnoredObject(o))
        continue;
      vector minmax[2];
      if (o.GetCollisionBox(minmax))
        return false;
    }
    return true;
  }
References GetGame(), Math3D::MatrixMultiply4(), Math3D::MatrixToAngles(), and vector::Up.
IsAreaAtDoorFree() [2/2]
bool EntityAI::IsAreaAtDoorFree (int currentSeat, float maxAllowedObjHeight = 0.5, float horizontalExtents = 0.5, float playerHeight = 1.7) inline protected
Definition at line 260 of file Transport.c.
  {
    vector transform[4];
    vector extents;
    extents[0] = horizontalExtents;
    extents[1] = playerHeight;
    extents[2] = horizontalExtents;
    return IsAreaAtDoorFree(currentSeat, maxAllowedObjHeight, extents, transform);
  }
References Transport::IsAreaAtDoorFree().
IsBuilding()
override bool EntityAI::IsBuilding () inline private
Definition at line 206 of file Building.c.
  {
    return true;
  }
IsCameraInsideVehicle()
proto native bool EntityAI::IsCameraInsideVehicle () private
IsDoorClosed()
proto native bool EntityAI::IsDoorClosed (int index) private
When the phase is at the close phase target (0.0)
IsDoorClosing()
proto native bool EntityAI::IsDoorClosing (int index) private
When the wanted phase is at the close phase target (0.0)
IsDoorLocked()
proto native bool EntityAI::IsDoorLocked (int index) private
When the door is locked.
IsDoorOpen()
proto native bool EntityAI::IsDoorOpen (int index) private
When the door is requested to be fully open (animation wanted phase is greater than 0.5)
IsDoorOpened()
proto native bool EntityAI::IsDoorOpened (int index) private
When the phase is at the open phase target (1.0)
IsDoorOpenedAjar()
proto native bool EntityAI::IsDoorOpenedAjar (int index) private
When the phase is at the ajar phase target (0.2)
IsDoorOpening()
proto native bool EntityAI::IsDoorOpening (int index) private
When the wanted phase is at the open phase target (1.0)
IsDoorOpeningAjar()
proto native bool EntityAI::IsDoorOpeningAjar (int index) private
When the wanted phase is at the ajar phase target (0.2)
IsHealthVisible() [1/3]
override bool EntityAI::IsHealthVisible () inline private
Definition at line 216 of file Building.c.
  {
    return false;
  }
IsHealthVisible() [2/3]
override bool EntityAI::IsHealthVisible () inline private
Definition at line 38 of file Man.c.
  {
    return false;
  }
IsHealthVisible() [3/3]
override bool EntityAI::IsHealthVisible () inline private
Definition at line 70 of file Transport.c.
  {
    return true;
  }
IsIgnoredByConstruction()
override bool EntityAI::IsIgnoredByConstruction () inline private
Definition at line 65 of file Transport.c.
  {
    return false;
  }
IsIgnoredObject()
bool EntityAI::IsIgnoredObject (Object o) inline protected
If the player can't interact (hint: collide) with the object, then it is ignored
Ignore any player that is currently in this vehicle
Definition at line 190 of file Transport.c.
  {
    if (!o)
      return false;
    int layer = dBodyGetInteractionLayer(o);
    bool interacts = dGetInteractionLayer(this, PhxInteractionLayers.CHARACTER, layer);
    if (!interacts)
      return true;
    DayZPlayer player;
    if (Class.CastTo(player, o))
    {
      HumanCommandVehicle hcv = player.GetCommand_Vehicle();
      if (hcv && hcv.GetTransport() == this)
        return true;
    }
    EntityAI e = EntityAI.Cast(o);
    // CanBeSkinned means it is a dead entity which should not block the door
    return ((e && (e.IsZombie() || e.IsHologram())) || o.CanBeSkinned() || o.IsBush() || o.IsTree());
  }
References Class::CastTo(), dBodyGetInteractionLayer(), and dGetInteractionLayer().
IsInTransport()
bool EntityAI::IsInTransport () inline protected
returns true if man is in transport, false otherwise
Definition at line 907 of file Man.c.
  {
    return Transport.Cast(GetParent()) != null;
  }
References GetParent().
IsInventoryItem()
override bool EntityAI::IsInventoryItem () inline private
Definition at line 61 of file InventoryItem.c.
  {
    return true;
  }
IsInventorySoftLocked()
bool EntityAI::IsInventorySoftLocked () inline protected
Definition at line 899 of file Man.c.
  {
    return false;
  }
IsInventoryVisible()
override bool EntityAI::IsInventoryVisible () inline private
Definition at line 229 of file Building.c.
  {
    return false;
  }
IsMan()
override bool EntityAI::IsMan () inline private
Definition at line 33 of file Man.c.
  {
    return true;
  }
Referenced by Entity::CanBeTargetedByAI(), Clothing_Base::CanLoadItemIntoCargoClothingConditions(), ClothingBase::CanPutAsAttachment(), Clothing::CanPutInCargo(), and Clothing_Base::CanPutInCargoClothingConditions().
IsMeleeFinisher()
bool EntityAI::IsMeleeFinisher () inline private
Definition at line 86 of file InventoryItem.c.
  {
    return false;
  }
IsMeleeWeapon()
override bool EntityAI::IsMeleeWeapon () inline private
Definition at line 81 of file InventoryItem.c.
  {
    return m_IsMeleeWeapon;
  }
IsOn()
proto native bool EntityAI::IsOn () private
Some inventoryItem devices can be switched on/off (radios, transmitters)
IsSoundInsideBuilding()
proto native bool EntityAI::IsSoundInsideBuilding () private
IsSpeechRestricted()
proto native bool EntityAI::IsSpeechRestricted () private
Check if player has resctricted speech.
IsTransport()
override bool EntityAI::IsTransport () inline private
Definition at line 60 of file Transport.c.
  {
    return true;
  }
IsUnconscious()
bool EntityAI::IsUnconscious () private
JunctureDeleteItem()
void EntityAI::JunctureDeleteItem (EntityAI item) inline protected
Definition at line 830 of file Man.c.
  {
  }
JunctureDropEntity()
bool EntityAI::JunctureDropEntity (notnull EntityAI item) inline protected
drop juncture
Definition at line 104 of file Man.c.
  {
    return DropEntityImpl(InventoryMode.JUNCTURE, this, item);
  }
References DropEntityImpl().
Referenced by PredictiveDropEntity().
JunctureForceSwapEntities()
bool EntityAI::JunctureForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) inline protected
ForceSwap juncture.
Definition at line 535 of file Man.c.
  {
    return ForceSwapEntitiesImpl(InventoryMode.JUNCTURE, item1, item2, item2_dst);
  }
References ForceSwapEntitiesImpl().
JunctureSwapEntities()
bool EntityAI::JunctureSwapEntities (notnull EntityAI item1, notnull EntityAI item2) inline protected
swap juncture
Definition at line 487 of file Man.c.
  {
    return SwapEntitiesImpl(InventoryMode.JUNCTURE, item1, item2);
  }
References SwapEntitiesImpl().
JunctureTakeEntityAsAttachment()
bool EntityAI::JunctureTakeEntityAsAttachment (notnull EntityAI item) inline protected
as att juncture
Definition at line 409 of file Man.c.
  {
    return TakeEntityAsAttachmentImpl(InventoryMode.JUNCTURE, item);
  }
References TakeEntityAsAttachmentImpl().
Referenced by PredictiveTakeEntityAsAttachment().
JunctureTakeEntityAsAttachmentEx()
bool EntityAI::JunctureTakeEntityAsAttachmentEx (notnull EntityAI item, int slot) inline protected
as att ex juncture
Definition at line 448 of file Man.c.
  {
    return TakeEntityAsAttachmentExImpl(InventoryMode.JUNCTURE, item, slot);
  }
References TakeEntityAsAttachmentExImpl().
Referenced by PredictiveTakeEntityAsAttachmentEx().
JunctureTakeEntityToCargo()
bool EntityAI::JunctureTakeEntityToCargo (notnull EntityAI item) inline protected
to cgo juncture
Definition at line 370 of file Man.c.
  {
    return TakeEntityToCargoImpl(InventoryMode.JUNCTURE, item);
  }
References TakeEntityToCargoImpl().
Referenced by PredictiveTakeEntityToCargo().
JunctureTakeEntityToHands()
void EntityAI::JunctureTakeEntityToHands (notnull EntityAI item) inline protected
hand juncture
Definition at line 149 of file Man.c.
  {
    TakeEntityToHandsImpl(InventoryMode.JUNCTURE, item);
  }
References TakeEntityToHandsImpl().
Referenced by PredictiveTakeEntityToHands().
JunctureTakeEntityToInventory()
bool EntityAI::JunctureTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline protected
to inv juncture
Definition at line 331 of file Man.c.
  {
    return TakeEntityToInventoryImpl(InventoryMode.JUNCTURE, flags, item);
  }
References TakeEntityToInventoryImpl().
Referenced by PredictiveTakeEntityToInventory().
JunctureTakeEntityToTargetAttachment()
bool EntityAI::JunctureTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline protected
to target att juncture
Definition at line 752 of file Man.c.
  {
    return TakeEntityToTargetAttachmentImpl(InventoryMode.JUNCTURE, target, item);
  }
References TakeEntityToTargetAttachmentImpl().
Referenced by PredictiveTakeEntityToTargetAttachment().
JunctureTakeEntityToTargetAttachmentEx()
bool EntityAI::JunctureTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline protected
to target att ex juncture
Definition at line 713 of file Man.c.
  {
    return TakeEntityToTargetAttachmentExImpl(InventoryMode.JUNCTURE, target, item, slot);
  }
References TakeEntityToTargetAttachmentExImpl().
Referenced by PredictiveTakeEntityToTargetAttachmentEx().
JunctureTakeEntityToTargetCargo()
bool EntityAI::JunctureTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline protected
to target cgo juncture
Definition at line 670 of file Man.c.
  {
    return TakeEntityToTargetCargoImpl(InventoryMode.JUNCTURE, target, item);
  }
References TakeEntityToTargetCargoImpl().
Referenced by PredictiveTakeEntityToTargetCargo().
JunctureTakeEntityToTargetCargoEx()
bool EntityAI::JunctureTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline protected
to target cgo ex juncture
Definition at line 631 of file Man.c.
  {
    return TakeEntityToTargetCargoExImpl(InventoryMode.JUNCTURE, cargo, item, row, col);
  }
References TakeEntityToTargetCargoExImpl().
Referenced by PredictiveTakeEntityToTargetCargoEx().
JunctureTakeEntityToTargetInventory()
bool EntityAI::JunctureTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline protected
to target inv juncture
Definition at line 580 of file Man.c.
  {
    return TakeEntityToTargetInventoryImpl(InventoryMode.JUNCTURE, target, flags, item);
  }
References TakeEntityToTargetInventoryImpl().
Referenced by PredictiveTakeEntityToTargetInventory().
JunctureTakeToDst()
bool EntityAI::JunctureTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline protected
to dst juncture
Definition at line 791 of file Man.c.
  {
    return TakeToDstImpl(InventoryMode.JUNCTURE, src, dst);
  }
References TakeToDstImpl().
Referenced by PredictiveTakeToDst().
LocalDestroyEntityInHands()
void EntityAI::LocalDestroyEntityInHands () inline protected
Definition at line 206 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " Destroy IH=" + GetHumanInventory().GetEntityInHands());
    GetHumanInventory().LocalDestroyEntity(GetHumanInventory().GetEntityInHands());
    UpdateInventoryMenu();
  }
References GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), HumanInventory::LocalDestroyEntity(), syncDebugPrint(), and UpdateInventoryMenu().
LocalDropEntity()
override bool EntityAI::LocalDropEntity (notnull EntityAI item) inline protected
Definition at line 123 of file Man.c.
  {
    return DropEntityImpl(InventoryMode.LOCAL, this, item);
  }
References DropEntityImpl().
LocalForceSwapEntities()
bool EntityAI::LocalForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) inline protected
Definition at line 556 of file Man.c.
  {
    return ForceSwapEntitiesImpl(InventoryMode.LOCAL, item1, item2, item2_dst);
  }
References ForceSwapEntitiesImpl().
LocalReplaceItemElsewhereWithNewInHands()
bool EntityAI::LocalReplaceItemElsewhereWithNewInHands (ReplaceItemWithNewLambdaBase lambda) inline protected
Definition at line 279 of file Man.c.
  {
    return ReplaceItemElsewhereWithNewInHandsImpl(InventoryMode.LOCAL, lambda);
  }
References ReplaceItemElsewhereWithNewInHandsImpl().
LocalReplaceItemInHandsWithNew()
bool EntityAI::LocalReplaceItemInHandsWithNew (ReplaceItemWithNewLambdaBase lambda) inline protected
Definition at line 299 of file Man.c.
  {
    return ReplaceItemInHandsWithNewImpl(InventoryMode.LOCAL, lambda);
  }
References ReplaceItemInHandsWithNewImpl().
LocalReplaceItemInHandsWithNewElsewhere()
bool EntityAI::LocalReplaceItemInHandsWithNewElsewhere (ReplaceItemWithNewLambdaBase lambda) inline protected
Definition at line 319 of file Man.c.
  {
    return ReplaceItemInHandsWithNewElsewhereImpl(InventoryMode.LOCAL, lambda);
  }
References ReplaceItemInHandsWithNewElsewhereImpl().
LocalReplaceItemWithNew()
bool EntityAI::LocalReplaceItemWithNew (ReplaceItemWithNewLambdaBase lambda) inline protected
Definition at line 259 of file Man.c.
  {
    return ReplaceItemWithNewImpl(InventoryMode.LOCAL, lambda);
  }
References ReplaceItemWithNewImpl().
LocalSwapEntities()
bool EntityAI::LocalSwapEntities (notnull EntityAI item1, notnull EntityAI item2) inline protected
Definition at line 508 of file Man.c.
  {
    return SwapEntitiesImpl(InventoryMode.LOCAL, item1, item2);
  }
References SwapEntitiesImpl().
LocalTakeEntityAsAttachment()
override bool EntityAI::LocalTakeEntityAsAttachment (notnull EntityAI item) inline protected
Definition at line 428 of file Man.c.
  {
    return TakeEntityAsAttachmentImpl(InventoryMode.LOCAL, item);
  }
References TakeEntityAsAttachmentImpl().
LocalTakeEntityAsAttachmentEx()
override bool EntityAI::LocalTakeEntityAsAttachmentEx (notnull EntityAI item, int slot) inline protected
Definition at line 467 of file Man.c.
  {
    return TakeEntityAsAttachmentExImpl(InventoryMode.LOCAL, item, slot);
  }
References TakeEntityAsAttachmentExImpl().
LocalTakeEntityToCargo()
override bool EntityAI::LocalTakeEntityToCargo (notnull EntityAI item) inline protected
Definition at line 389 of file Man.c.
  {
    return TakeEntityToCargoImpl(InventoryMode.LOCAL, item);
  }
References TakeEntityToCargoImpl().
LocalTakeEntityToHands()
void EntityAI::LocalTakeEntityToHands (EntityAI item) inline protected
Definition at line 168 of file Man.c.
  {
    TakeEntityToHandsImpl(InventoryMode.LOCAL, item);
  }
References TakeEntityToHandsImpl().
LocalTakeEntityToInventory()
override bool EntityAI::LocalTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline protected
Definition at line 350 of file Man.c.
  {
    return TakeEntityToInventoryImpl(InventoryMode.LOCAL, flags, item);
  }
References TakeEntityToInventoryImpl().
LocalTakeEntityToTargetAttachment()
override bool EntityAI::LocalTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline protected
Definition at line 771 of file Man.c.
  {
    return TakeEntityToTargetAttachmentImpl(InventoryMode.LOCAL, target, item);
  }
References TakeEntityToTargetAttachmentImpl().
LocalTakeEntityToTargetAttachmentEx()
override bool EntityAI::LocalTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline protected
Definition at line 732 of file Man.c.
  {
    return TakeEntityToTargetAttachmentExImpl(InventoryMode.LOCAL, target, item, slot);
  }
References TakeEntityToTargetAttachmentExImpl().
LocalTakeEntityToTargetCargo()
override bool EntityAI::LocalTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline protected
Definition at line 689 of file Man.c.
  {
    return TakeEntityToTargetCargoImpl(InventoryMode.LOCAL, target, item);
  }
References TakeEntityToTargetCargoImpl().
LocalTakeEntityToTargetCargoEx()
override bool EntityAI::LocalTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline protected
Definition at line 650 of file Man.c.
  {
    return TakeEntityToTargetCargoExImpl(InventoryMode.LOCAL, cargo, item, row, col);
  }
References TakeEntityToTargetCargoExImpl().
LocalTakeEntityToTargetInventory()
override bool EntityAI::LocalTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline protected
Definition at line 616 of file Man.c.
  {
    return TakeEntityToTargetInventoryImpl(InventoryMode.LOCAL, target, flags, item);
  }
References TakeEntityToTargetInventoryImpl().
LocalTakeToDst()
override bool EntityAI::LocalTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline protected
Definition at line 810 of file Man.c.
  {
    return TakeToDstImpl(InventoryMode.LOCAL, src, dst);
  }
References TakeToDstImpl().
Referenced by DropNonUsableMaterialsServer().
LockDoor()
proto native void EntityAI::LockDoor (int index, bool force = false) private
Locks the door if not already locked, resets the door health. 'force = true' will close the door if open.
Man()
void EntityAI::Man () inline private
Definition at line 28 of file Man.c.
  {
    SetFlags(EntityFlags.TOUCHTRIGGERS, false);
  }
References SetFlags().
MarkCrewMemberDead()
void EntityAI::MarkCrewMemberDead (int crewMemberIndex) private
MarkCrewMemberUnconscious()
void EntityAI::MarkCrewMemberUnconscious (int crewMemberIndex) private
NeedInventoryJunctureFromServer()
bool EntityAI::NeedInventoryJunctureFromServer (notnull EntityAI item, EntityAI currParent, EntityAI newParent) inline protected
Definition at line 146 of file Man.c.
{ return false; }
Referenced by PredictiveDropEntity(), PredictiveForceSwapEntities(), PredictiveMoveItemFromHandsToInventory(), PredictiveSwapEntities(), PredictiveTakeEntityAsAttachment(), PredictiveTakeEntityAsAttachmentEx(), PredictiveTakeEntityToCargo(), PredictiveTakeEntityToHands(), PredictiveTakeEntityToInventory(), PredictiveTakeEntityToTargetAttachment(), PredictiveTakeEntityToTargetAttachmentEx(), PredictiveTakeEntityToTargetCargo(), PredictiveTakeEntityToTargetCargoEx(), PredictiveTakeEntityToTargetInventory(), and PredictiveTakeToDst().
OnAction()
override bool EntityAI::OnAction (int action_id, Man player, ParamsReadContext ctx) inline private
Definition at line 169 of file Building.c.
  {
    if (super.OnAction(action_id, player, ctx))
      return true;
    switch (action_id)
    {
    case EActions.BUILDING_PLAY_DOOR_SOUND:
      PlayDoorSound(GetNearestDoorBySoundPos(player.GetPosition()));
      return true;
    }
    if (!GetGame().IsServer())
      return false;
    switch (action_id)
    {
    case EActions.BUILDING_OUTPUT_LOG:
      OutputDoorLog();
      return true;
    case EActions.BUILDING_OPEN_DOOR:
      OpenDoor(GetNearestDoorBySoundPos(player.GetPosition()));
      return true;
    case EActions.BUILDING_CLOSE_DOOR:
      CloseDoor(GetNearestDoorBySoundPos(player.GetPosition()));
      return true;
    case EActions.BUILDING_LOCK_DOOR:
      LockDoor(GetNearestDoorBySoundPos(player.GetPosition()));
      return true;
    case EActions.BUILDING_UNLOCK_DOOR:
      UnlockDoor(GetNearestDoorBySoundPos(player.GetPosition()));
      return true;
    }
    return false;
  }
References GetGame().
OnDoorCloseFinish()
void EntityAI::OnDoorCloseFinish (DoorFinishParams params) inline private
Event for when the door finishes closing.
Definition at line 111 of file Building.c.
  {
  }
OnDoorCloseStart()
void EntityAI::OnDoorCloseStart (DoorStartParams params) inline private
Event for when the door starts closing.
Definition at line 106 of file Building.c.
  {
  }
OnDoorLocked()
void EntityAI::OnDoorLocked (DoorLockParams params) inline private
Event for when the door is locked.
Definition at line 116 of file Building.c.
  {
  }
OnDoorOpenAjarFinish()
void EntityAI::OnDoorOpenAjarFinish (DoorFinishParams params) inline private
Event for when the door finishes opening ajarred (usually after unlock)
Definition at line 101 of file Building.c.
  {
  }
OnDoorOpenAjarStart()
void EntityAI::OnDoorOpenAjarStart (DoorStartParams params) inline private
Event for when the door starts opening ajarred (usually after unlock)
Definition at line 96 of file Building.c.
  {
  }
OnDoorOpenFinish()
void EntityAI::OnDoorOpenFinish (DoorFinishParams params) inline private
Event for when the door finishes opening.
Definition at line 91 of file Building.c.
  {
  }
OnDoorOpenStart()
void EntityAI::OnDoorOpenStart (DoorStartParams params) inline private
Event for when the door starts opening.
Definition at line 86 of file Building.c.
  {
  }
OnDoorUnlocked()
void EntityAI::OnDoorUnlocked (DoorLockParams params) inline private
Event for when the door is unlocked.
Definition at line 121 of file Building.c.
  {
  }
OnGameplayDataHandlerSync()
void EntityAI::OnGameplayDataHandlerSync () protected
OnItemInHandsChanged()
void EntityAI::OnItemInHandsChanged () inline protected
Definition at line 144 of file Man.c.
{ }
OnRightClick()
void EntityAI::OnRightClick () inline private
Definition at line 42 of file InventoryItem.c.
  {
  }
OnUseFromInventory()
event bool EntityAI::OnUseFromInventory (Man owner) inline private
Definition at line 47 of file InventoryItem.c.
  {
    return false;
  }
OpenDoor()
proto native void EntityAI::OpenDoor (int index) private
Attempts to open the door.
OutputDoorLog()
proto native void EntityAI::OutputDoorLog () private
Requires special build as logging is disabled even on internal builds due to memory usage. Used for checking of possible causes of navmesh desync.
PhysicalPredictiveDropItem()
bool EntityAI::PhysicalPredictiveDropItem (EntityAI entity, bool heavy_item_only = true) protected
PlayDoorSound()
proto native void EntityAI::PlayDoorSound (int index) private
Plays the appropriate sound at the door, based on animation phase and state.
PlayImpactSound()
void EntityAI::PlayImpactSound (float weight, float velocity, int surfaceHash) inline private
Definition at line 92 of file InventoryItem.c.
  {
    if (!m_SoundImpactTable)
      return;
    SoundObjectBuilder soundBuilder = m_SoundImpactTable.GetSoundBuilder(surfaceHash);
    if (soundBuilder != null)
    {
      soundBuilder.AddVariable("weight", weight);
      soundBuilder.AddVariable("speed", velocity);
      soundBuilder.AddEnvSoundVariables(GetPosition());
      SoundObject soundObject = soundBuilder.BuildSoundObject();
      if (soundObject != null)
      {
        soundObject.SetKind(WaveKind.WAVEEFFECTEX);
        PlaySound(soundObject, soundBuilder);
      }
    }
  }
References GetPosition, SoundLookupTable::GetSoundBuilder(), PlaySound(), and SoundObject().
PlaySound()
AbstractWave EntityAI::PlaySound (SoundObject so, SoundObjectBuilder sob) inline protected
Definition at line 126 of file InventoryItem.c.
  {
    if (so == null)
      return null;
    so.SetPosition(GetPosition());
    AbstractWave wave = GetGame().GetSoundScene().Play3D(so, sob);
    return wave;
  }
References GetGame(), and GetPosition.
PlaySoundByAnimEvent()
void EntityAI::PlaySoundByAnimEvent (EAnimSoundEventID id) inline protected
Definition at line 138 of file InventoryItem.c.
  {
    AnimSoundEvent soundEvent = GetInventoryItemType().GetSoundEvent(id);
    if (soundEvent)
    {
      SoundObjectBuilder builder = soundEvent.GetSoundBuilder();
      SoundObject soundObject = builder.BuildSoundObject();
      if (soundObject)
        PlaySound(soundObject, builder);
    }
  }
References PlaySound(), and SoundObject().
PredictiveDropEntity()
override bool EntityAI::PredictiveDropEntity (notnull EntityAI item) inline protected
Definition at line 109 of file Man.c.
  {
    if (!ScriptInputUserData.CanStoreInputUserData())
    {
      Print("[inv] " + GetSimulationTimeStamp() + " Man@" + this + " ::PredictiveDropEntity input data not sent yet, cannot allow another input action");
      return false;
    }
    if (NeedInventoryJunctureFromServer(item, item.GetHierarchyParent(), this))
      return JunctureDropEntity(item);
    else
      return DropEntityImpl(InventoryMode.PREDICTIVE, this, item);
  }
References ScriptInputUserData::CanStoreInputUserData(), DropEntityImpl(), JunctureDropEntity(), NeedInventoryJunctureFromServer(), and Print().
PredictiveForceSwapEntities()
bool EntityAI::PredictiveForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) inline protected
Definition at line 540 of file Man.c.
  {
    if (!ScriptInputUserData.CanStoreInputUserData())
    {
      Print("[inv] " + GetSimulationTimeStamp() + " Man@" + this + " ::PredictiveForceSwapEntities input data not sent yet, cannot allow another input action");
      return false;
    }
    bool need_j1 = NeedInventoryJunctureFromServer(item1, item1.GetHierarchyParent(), item2.GetHierarchyParent());
    bool need_j2 = NeedInventoryJunctureFromServer(item2, item2.GetHierarchyParent(), item1.GetHierarchyParent());
    if (need_j1 || need_j2)
      return ForceSwapEntitiesImpl(InventoryMode.JUNCTURE, item1, item2, item2_dst);
    else
      return ForceSwapEntitiesImpl(InventoryMode.PREDICTIVE, item1, item2, item2_dst);
  }
References ScriptInputUserData::CanStoreInputUserData(), ForceSwapEntitiesImpl(), NeedInventoryJunctureFromServer(), and Print().
PredictiveMoveItemFromHandsToInventory()
void EntityAI::PredictiveMoveItemFromHandsToInventory () inline protected
returns item to previous location, if available
Definition at line 213 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " Stash IH=" + GetHumanInventory().GetEntityInHands());
    if (!ScriptInputUserData.CanStoreInputUserData())
    {
      Print("[inv] PredictiveMoveItemFromHandsToInventory input data not sent yet, cannot allow another input action");
      return;
    }
    InventoryMode invMode = InventoryMode.PREDICTIVE;
    if (NeedInventoryJunctureFromServer(GetHumanInventory().GetEntityInHands(), this, this))
      invMode = InventoryMode.JUNCTURE;
    if (GetHumanInventory().GetEntityInHands().m_OldLocation && GetHumanInventory().GetEntityInHands().m_OldLocation.IsValid())
    {
      InventoryLocation invLoc = new InventoryLocation;
      GetHumanInventory().GetEntityInHands().GetInventory().GetCurrentInventoryLocation(invLoc);
      //old location is somewhere on player
      if (GetHumanInventory().GetEntityInHands().m_OldLocation.GetParent() && GetHumanInventory().GetEntityInHands().m_OldLocation.GetParent().GetHierarchyRootPlayer())
      {
        if (GetHumanInventory().LocationCanMoveEntity(invLoc, GetHumanInventory().GetEntityInHands().m_OldLocation))
        {
          if (GetHumanInventory().TakeToDst(invMode, invLoc, GetHumanInventory().GetEntityInHands().m_OldLocation))
          {
            UpdateInventoryMenu();
            return;
          }
        }
      }
    }
    GetHumanInventory().TakeEntityToInventory(invMode, FindInventoryLocationType.ATTACHMENT | FindInventoryLocationType.CARGO, GetHumanInventory().GetEntityInHands());
    UpdateInventoryMenu();
  }
References ScriptInputUserData::CanStoreInputUserData(), GetDebugName(), HumanInventory::GetEntityInHands(), GetHumanInventory(), LogManager::IsSyncLogEnable(), NeedInventoryJunctureFromServer(), Print(), syncDebugPrint(), HumanInventory::TakeEntityToInventory(), TakeToDst(), and UpdateInventoryMenu().
PredictiveSwapEntities()
bool EntityAI::PredictiveSwapEntities (notnull EntityAI item1, notnull EntityAI item2) inline protected
Definition at line 492 of file Man.c.
  {
    if (!ScriptInputUserData.CanStoreInputUserData())
    {
      Print("[inv] " + GetSimulationTimeStamp() + " Man@" + this + " ::PredictiveSwapEntities input data not sent yet, cannot allow another input action");
      return false;
    }
    bool need_j1 = NeedInventoryJunctureFromServer(item1, item1.GetHierarchyParent(), item2.GetHierarchyParent());
    bool need_j2 = NeedInventoryJunctureFromServer(item2, item2.GetHierarchyParent(), item1.GetHierarchyParent());
    if (need_j1 || need_j2)
      return SwapEntitiesImpl(InventoryMode.JUNCTURE, item1, item2);
    else
      return SwapEntitiesImpl(InventoryMode.PREDICTIVE, item1, item2);
  }
References ScriptInputUserData::CanStoreInputUserData(), NeedInventoryJunctureFromServer(), Print(), and SwapEntitiesImpl().
Referenced by PredictiveTakeOrSwapAttachment().
PredictiveTakeEntityAsAttachment()
override bool EntityAI::PredictiveTakeEntityAsAttachment (notnull EntityAI item) inline protected
Definition at line 414 of file Man.c.
  {
    if (!ScriptInputUserData.CanStoreInputUserData())
    {
      Print("[inv] " + GetSimulationTimeStamp() + " Man@" + this + " ::PredictiveTakeEntityAsAttachment input data not sent yet, cannot allow another input action");
      return false;
    }
    if (NeedInventoryJunctureFromServer(item, item.GetHierarchyParent(), this))
      return JunctureTakeEntityAsAttachment(item);
    else
      return TakeEntityAsAttachmentImpl(InventoryMode.PREDICTIVE, item);
  }
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeEntityAsAttachment(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityAsAttachmentImpl().
Referenced by PredictiveTakeOrSwapAttachment().
PredictiveTakeEntityAsAttachmentEx()
override bool EntityAI::PredictiveTakeEntityAsAttachmentEx (notnull EntityAI item, int slot) inline protected
Definition at line 453 of file Man.c.
  {
    if (!ScriptInputUserData.CanStoreInputUserData())
    {
      Print("[inv] " + GetSimulationTimeStamp() + " Man@" + this + " ::PredictiveTakeEntityAsAttachmentEx input data not sent yet, cannot allow another input action");
      return false;
    }
    if (NeedInventoryJunctureFromServer(item, item.GetHierarchyParent(), this))
      return JunctureTakeEntityAsAttachmentEx(item, slot);
    else
      return TakeEntityAsAttachmentExImpl(InventoryMode.PREDICTIVE, item, slot);
  }
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeEntityAsAttachmentEx(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityAsAttachmentExImpl().
PredictiveTakeEntityToCargo()
override bool EntityAI::PredictiveTakeEntityToCargo (notnull EntityAI item) inline protected
Definition at line 375 of file Man.c.
  {
    if (!ScriptInputUserData.CanStoreInputUserData())
    {
      Print("[inv] " + GetSimulationTimeStamp() + " Man@" + this + " ::PredictiveTakeEntityToCargo input data not sent yet, cannot allow another input action");
      return false;
    }
    if (NeedInventoryJunctureFromServer(item, item.GetHierarchyParent(), this))
      return JunctureTakeEntityToCargo(item);
    else
      return TakeEntityToCargoImpl(InventoryMode.PREDICTIVE, item);
  }
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeEntityToCargo(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToCargoImpl().
PredictiveTakeEntityToHands()
void EntityAI::PredictiveTakeEntityToHands (EntityAI item) inline protected
Definition at line 154 of file Man.c.
  {
    if (!ScriptInputUserData.CanStoreInputUserData())
    {
      Print("[inv] " + GetSimulationTimeStamp() + " Man@" + this + " ::PredictiveTakeEntityToHands input data not sent yet, cannot allow another input action");
      return;
    }
    if (NeedInventoryJunctureFromServer(item, item.GetHierarchyParent(), this))
      JunctureTakeEntityToHands(item);
    else
      TakeEntityToHandsImpl(InventoryMode.PREDICTIVE, item);
  }
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeEntityToHands(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToHandsImpl().
PredictiveTakeEntityToInventory()
override bool EntityAI::PredictiveTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline protected
Definition at line 336 of file Man.c.
  {
    if (!ScriptInputUserData.CanStoreInputUserData())
    {
      Print("[inv] " + GetSimulationTimeStamp() + " Man@" + this + " ::PredictiveTakeEntityToInventory input data not sent yet, cannot allow another input action");
      return false;
    }
    if (NeedInventoryJunctureFromServer(item, item.GetHierarchyParent(), this))
      return JunctureTakeEntityToInventory(flags, item);
    else
      return TakeEntityToInventoryImpl(InventoryMode.PREDICTIVE, flags, item);
  }
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeEntityToInventory(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToInventoryImpl().
PredictiveTakeEntityToTargetAttachment()
override bool EntityAI::PredictiveTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline protected
Definition at line 757 of file Man.c.
  {
    if (!ScriptInputUserData.CanStoreInputUserData())
    {
      Print("[inv] " + GetSimulationTimeStamp() + " Man@" + this + " ::PredictiveTakeEntityToTargetAttachment input data not sent yet, cannot allow another input action");
      return false;
    }
    if (NeedInventoryJunctureFromServer(item, item.GetHierarchyParent(), target))
      return JunctureTakeEntityToTargetAttachment(target, item);
    else
      return TakeEntityToTargetAttachmentImpl(InventoryMode.PREDICTIVE, target, item);
  }
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeEntityToTargetAttachment(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToTargetAttachmentImpl().
PredictiveTakeEntityToTargetAttachmentEx()
override bool EntityAI::PredictiveTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline protected
Definition at line 718 of file Man.c.
  {
    if (!ScriptInputUserData.CanStoreInputUserData())
    {
      Print("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " ::PredictiveTakeEntityToTargetAttachmentEx input data not sent yet, cannot allow another input action");
      return false;
    }
    if (NeedInventoryJunctureFromServer(item, item.GetHierarchyParent(), target))
      return JunctureTakeEntityToTargetAttachmentEx(target, item, slot);
    else
      return TakeEntityToTargetAttachmentExImpl(InventoryMode.PREDICTIVE, target, item, slot);
  }
References ScriptInputUserData::CanStoreInputUserData(), GetDebugName(), JunctureTakeEntityToTargetAttachmentEx(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToTargetAttachmentExImpl().
PredictiveTakeEntityToTargetCargo()
override bool EntityAI::PredictiveTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline protected
Definition at line 675 of file Man.c.
  {
    if (!ScriptInputUserData.CanStoreInputUserData())
    {
      Print("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " ::PredictiveTakeEntityToTargetCargo input data not sent yet, cannot allow another input action");
      return false;
    }
    if (NeedInventoryJunctureFromServer(item, item.GetHierarchyParent(), target))
      return JunctureTakeEntityToTargetCargo(target, item);
    else
      return TakeEntityToTargetCargoImpl(InventoryMode.PREDICTIVE, target, item);
  }
References ScriptInputUserData::CanStoreInputUserData(), GetDebugName(), JunctureTakeEntityToTargetCargo(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToTargetCargoImpl().
PredictiveTakeEntityToTargetCargoEx()
override bool EntityAI::PredictiveTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline protected
Definition at line 636 of file Man.c.
  {
    if (!ScriptInputUserData.CanStoreInputUserData())
    {
      Print("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " ::PredictiveTakeEntityToTargetCargoEx input data not sent yet, cannot allow another input action");
      return false;
    }
    if (NeedInventoryJunctureFromServer(item, item.GetHierarchyParent(), cargo.GetCargoOwner()))
      return JunctureTakeEntityToTargetCargoEx(cargo, item, row, col);
    else
      return TakeEntityToTargetCargoExImpl(InventoryMode.PREDICTIVE, cargo, item, row, col);
  }
References ScriptInputUserData::CanStoreInputUserData(), GetDebugName(), JunctureTakeEntityToTargetCargoEx(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToTargetCargoExImpl().
PredictiveTakeEntityToTargetInventory()
override bool EntityAI::PredictiveTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline protected
Definition at line 585 of file Man.c.
  {
    if (!ScriptInputUserData.CanStoreInputUserData())
    {
      Print("[inv] " + GetSimulationTimeStamp() + " ::PredictiveTakeEntityToTargetInventory input data not sent yet, cannot allow another input action");
      return false;
    }
    if (NeedInventoryJunctureFromServer(item, item.GetHierarchyParent(), target))
      return JunctureTakeEntityToTargetInventory(target, flags, item);
    else
      return TakeEntityToTargetInventoryImpl(InventoryMode.PREDICTIVE, target, flags, item);
  }
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeEntityToTargetInventory(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToTargetInventoryImpl().
PredictiveTakeOrSwapAttachment()
bool EntityAI::PredictiveTakeOrSwapAttachment (notnull EntityAI item) inline protected
Definition at line 599 of file Man.c.
  {
    if (GetInventory().CanAddAttachment(item))
      return PredictiveTakeEntityAsAttachment(item);
    else
    {
      for (int i = 0; i < item.GetInventory().GetSlotIdCount(); i++)
      {
        int slot_id = item.GetInventory().GetSlotId(i);
        EntityAI slot_item = GetInventory().FindAttachment(slot_id);
        if (slot_item && GetInventory().CanSwapEntitiesEx(item, slot_item))
          return PredictiveSwapEntities(item, slot_item);
      }
    }
    return false;
  }
References PredictiveSwapEntities(), and PredictiveTakeEntityAsAttachment().
PredictiveTakeToDst()
override bool EntityAI::PredictiveTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline protected
Definition at line 796 of file Man.c.
  {
    if (!ScriptInputUserData.CanStoreInputUserData())
    {
      Print("[inv] " + GetSimulationTimeStamp() + " Man@" + this + " ::PredictiveTakeToDst input data not sent yet, cannot allow another input action");
      return false;
    }
    if (NeedInventoryJunctureFromServer(src.GetItem(), src.GetParent(), dst.GetParent()))
      return JunctureTakeToDst(src, dst);
    else
      return TakeToDstImpl(InventoryMode.PREDICTIVE, src, dst);
  }
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeToDst(), NeedInventoryJunctureFromServer(), Print(), and TakeToDstImpl().
ProcessImpactSound()
float EntityAI::ProcessImpactSound (IEntity other, Contact extra, float weight, out int surfaceHash) inline protected
Definition at line 188 of file InventoryItem.c.
  {
    int liquidType = -1;
    return ProcessImpactSoundEx(other, extra, weight, surfaceHash, liquidType);
  }
ProcessImpactSoundEx()
float EntityAI::ProcessImpactSoundEx (IEntity other, Contact extra, float weight, out int surfaceHash, out int liquidType) inline protected
Definition at line 196 of file InventoryItem.c.
  {
    float impactVelocity = extra.RelativeVelocityBefore.Length();
    if (impactVelocity < 0.3)
      return 0.0;
    float tickTime = GetGame().GetTickTime();
    if (m_SoundContactTickTime + SOUND_CONTACT_SKIP > tickTime)
      return 0.0;
    string surfaceName = GetImpactSurfaceTypeEx(other, extra, liquidType);
    if (surfaceName == "")
      return 0.0;
#ifdef DIAG_DEVELOPER
    string infoText = "Surface: " + surfaceName + ", Weight: " + weight + ", Speed: " + impactVelocity;
    if (s_ImpactSoundsInfo.Count() == 10)
      s_ImpactSoundsInfo.Remove(9);
    s_ImpactSoundsInfo.InsertAt(infoText, 0);
#endif
    m_SoundContactTickTime = tickTime;
    surfaceHash = surfaceName.Hash();
    return impactVelocity;
  }
References GetGame().
RemoveAction()
void EntityAI::RemoveAction (typename actionName) inline private
Definition at line 115 of file AdvancedCommunication.c.
  {
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    ActionBase action = player.GetActionManager().GetAction(actionName);
    typename ai = action.GetInputType();
    array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
    if (action_array)
      action_array.RemoveItem(action);
  }
References GetGame(), GetPlayer(), and m_InputActionMap.
ReplaceItemElsewhereWithNewInHandsImpl()
bool EntityAI::ReplaceItemElsewhereWithNewInHandsImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline protected
!hand replace -> hand
Definition at line 271 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " Replace !HND->HND lambda=" + lambda.DumpToString());
    bool code = GetHumanInventory().ReplaceItemElsewhereWithNewInHands(mode, lambda);
    UpdateInventoryMenu();
    return code;
  }
References GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), HumanInventory::ReplaceItemElsewhereWithNewInHands(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by LocalReplaceItemElsewhereWithNewInHands(), and ServerReplaceItemElsewhereWithNewInHands().
ReplaceItemInHandsWithNewElsewhereImpl()
bool EntityAI::ReplaceItemInHandsWithNewElsewhereImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline protected
hand replace2
Definition at line 311 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " Replace HND->elsewhere lambda=" + lambda.DumpToString());
    bool code = GetHumanInventory().ReplaceItemInHandsWithNewElsewhere(mode, lambda);
    UpdateInventoryMenu();
    return code;
  }
References GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), HumanInventory::ReplaceItemInHandsWithNewElsewhere(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by LocalReplaceItemInHandsWithNewElsewhere(), and ServerReplaceItemInHandsWithNewElsewhere().
ReplaceItemInHandsWithNewImpl()
bool EntityAI::ReplaceItemInHandsWithNewImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline protected
hand replace
Definition at line 291 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " Replace HND->HND lambda=" + lambda.DumpToString());
    bool code = GetHumanInventory().ReplaceItemInHandsWithNew(mode, lambda);
    UpdateInventoryMenu();
    return code;
  }
References GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), HumanInventory::ReplaceItemInHandsWithNew(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by LocalReplaceItemInHandsWithNew(), and ServerReplaceItemInHandsWithNew().
ReplaceItemWithNewImpl()
bool EntityAI::ReplaceItemWithNewImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline protected
!hand -> !hand replace
Definition at line 251 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " Replace !HND lambda=" + lambda.DumpToString());
    bool code = GetHumanInventory().ReplaceItemWithNew(mode, lambda);
    UpdateInventoryMenu();
    return code;
  }
References GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), HumanInventory::ReplaceItemWithNew(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by LocalReplaceItemWithNew(), and ServerReplaceItemWithNew().
ServerDropEntity()
override bool EntityAI::ServerDropEntity (notnull EntityAI item) inline protected
Definition at line 128 of file Man.c.
  {
    return DropEntityImpl(InventoryMode.SERVER, this, item);
  }
References DropEntityImpl().
ServerForceSwapEntities()
bool EntityAI::ServerForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) inline protected
Definition at line 561 of file Man.c.
  {
    return ForceSwapEntitiesImpl(InventoryMode.SERVER, item1, item2, item2_dst);
  }
References ForceSwapEntitiesImpl().
ServerReplaceItemElsewhereWithNewInHands()
bool EntityAI::ServerReplaceItemElsewhereWithNewInHands (ReplaceItemWithNewLambdaBase lambda) inline protected
Definition at line 284 of file Man.c.
  {
    return ReplaceItemElsewhereWithNewInHandsImpl(InventoryMode.SERVER, lambda);
  }
References ReplaceItemElsewhereWithNewInHandsImpl().
ServerReplaceItemInHandsWithNew()
bool EntityAI::ServerReplaceItemInHandsWithNew (ReplaceItemWithNewLambdaBase lambda) inline protected
Definition at line 304 of file Man.c.
  {
    return ReplaceItemInHandsWithNewImpl(InventoryMode.SERVER, lambda);
  }
References ReplaceItemInHandsWithNewImpl().
ServerReplaceItemInHandsWithNewElsewhere()
bool EntityAI::ServerReplaceItemInHandsWithNewElsewhere (ReplaceItemWithNewLambdaBase lambda) inline protected
Definition at line 324 of file Man.c.
  {
    return ReplaceItemInHandsWithNewElsewhereImpl(InventoryMode.SERVER, lambda);
  }
References ReplaceItemInHandsWithNewElsewhereImpl().
ServerReplaceItemWithNew()
bool EntityAI::ServerReplaceItemWithNew (ReplaceItemWithNewLambdaBase lambda) inline protected
Definition at line 264 of file Man.c.
  {
    return ReplaceItemWithNewImpl(InventoryMode.SERVER, lambda);
  }
References ReplaceItemWithNewImpl().
ServerSwapEntities()
bool EntityAI::ServerSwapEntities (notnull EntityAI item1, notnull EntityAI item2) inline protected
Definition at line 513 of file Man.c.
  {
    return SwapEntitiesImpl(InventoryMode.SERVER, item1, item2);
  }
References SwapEntitiesImpl().
ServerTakeEntityAsAttachment()
override bool EntityAI::ServerTakeEntityAsAttachment (notnull EntityAI item) inline protected
Definition at line 433 of file Man.c.
  {
    return TakeEntityAsAttachmentImpl(InventoryMode.SERVER, item);
  }
References TakeEntityAsAttachmentImpl().
ServerTakeEntityAsAttachmentEx()
override bool EntityAI::ServerTakeEntityAsAttachmentEx (notnull EntityAI item, int slot) inline protected
Definition at line 472 of file Man.c.
  {
    return TakeEntityAsAttachmentExImpl(InventoryMode.SERVER, item, slot);
  }
References TakeEntityAsAttachmentExImpl().
ServerTakeEntityToCargo()
override bool EntityAI::ServerTakeEntityToCargo (notnull EntityAI item) inline protected
Definition at line 394 of file Man.c.
  {
    return TakeEntityToCargoImpl(InventoryMode.SERVER, item);
  }
References TakeEntityToCargoImpl().
ServerTakeEntityToHands()
void EntityAI::ServerTakeEntityToHands (EntityAI item) inline protected
Definition at line 173 of file Man.c.
  {
    TakeEntityToHandsImpl(InventoryMode.SERVER, item);
  }
References TakeEntityToHandsImpl().
ServerTakeEntityToInventory()
override bool EntityAI::ServerTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline protected
Definition at line 355 of file Man.c.
  {
    return TakeEntityToInventoryImpl(InventoryMode.SERVER, flags, item);
  }
References TakeEntityToInventoryImpl().
ServerTakeEntityToTargetAttachment()
override bool EntityAI::ServerTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline protected
Definition at line 776 of file Man.c.
  {
    return TakeEntityToTargetAttachmentImpl(InventoryMode.SERVER, target, item);
  }
References TakeEntityToTargetAttachmentImpl().
ServerTakeEntityToTargetAttachmentEx()
override bool EntityAI::ServerTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline protected
Definition at line 737 of file Man.c.
  {
    return TakeEntityToTargetAttachmentExImpl(InventoryMode.SERVER, target, item, slot);
  }
References TakeEntityToTargetAttachmentExImpl().
ServerTakeEntityToTargetCargo()
override bool EntityAI::ServerTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline protected
Definition at line 694 of file Man.c.
  {
    if (IsAlive())
      return TakeEntityToTargetCargoImpl(InventoryMode.SERVER, target, item);
    else
      return TakeEntityToTargetCargoImpl(InventoryMode.SERVER, target, item);
  }
References TakeEntityToTargetCargoImpl().
ServerTakeEntityToTargetCargoEx()
override bool EntityAI::ServerTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline protected
Definition at line 655 of file Man.c.
  {
    return TakeEntityToTargetCargoExImpl(InventoryMode.SERVER, cargo, item, row, col);
  }
References TakeEntityToTargetCargoExImpl().
ServerTakeToDst()
override bool EntityAI::ServerTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline protected
Definition at line 815 of file Man.c.
  {
    return TakeToDstImpl(InventoryMode.SERVER, src, dst);
  }
References TakeToDstImpl().
Referenced by DropNonUsableMaterialsServer().
SetActions()
void EntityAI::SetActions () inline private
Definition at line 78 of file AdvancedCommunication.c.
  {
    AddAction(ActionTurnOnTransmitterOnGround);
    AddAction(ActionTurnOffTransmitterOnGround);
    AddAction(ActionDetachPowerSourceFromPanel);
  }
References AddAction().
SetFaceMaterial()
proto native void EntityAI::SetFaceMaterial (string material_name) private
Material that is used on the Man's face and hands.
SetFaceTexture()
proto native void EntityAI::SetFaceTexture (string texture_name) private
Texture that is used on the Man's face and hands.
SetInventorySoftLock()
void EntityAI::SetInventorySoftLock (bool status) protected
SetMasterAttenuation()
proto native void EntityAI::SetMasterAttenuation (string masterAttenuation) private
SetProcessUIWarning()
void EntityAI::SetProcessUIWarning (bool state) protected
SetSpeechRestricted()
proto native void EntityAI::SetSpeechRestricted (bool state) private
Set speech restriction.
ShowZonesHealth()
override bool EntityAI::ShowZonesHealth () inline private
Definition at line 75 of file Transport.c.
  {
    return true;
  }
StatGet()
proto native float EntityAI::StatGet (string name) protected
Gets counter value of the specified stat type.
Parameters
[in] name The name of the stat type.
StatGetAsTime()
proto void EntityAI::StatGetAsTime (string name, out string value) protected
Gets counter value as formatted time string of the specified stat type.
Parameters
[in] name The name of the stat type.
[out] value A formatted string containing stat value.
StatGetCounter()
proto void EntityAI::StatGetCounter (string name, out string value) protected
Gets counter value as string of the specified stat type.
Parameters
[in] name The name of the stat type.
[out] value A formatted string containing stat value.
StatInvokeUpdate()
proto native void EntityAI::StatInvokeUpdate () protected
Invokes read stats from server to client.
Note
Call this on client when you need update stats.
StatRegister()
proto native bool EntityAI::StatRegister (string name) protected
Stats Registers new stat type for this player.
Parameters
[in] name The name of the stat type.
StatSyncToClient()
proto native void EntityAI::StatSyncToClient () protected
Invokes save stats from server to client.
Note
Call this on server when you need update stats.
StatUpdate()
proto native void EntityAI::StatUpdate (string name, float value) protected
Updates stat counter with given value.
Parameters
[in] name The name of the stat type.
[in] value The specified value.
StatUpdateByGivenPos()
proto native void EntityAI::StatUpdateByGivenPos (string name, vector pos) protected
Updates stat counter by given position.
Parameters
[in] name The name of the stat type.
[in] pos The specified position.
StatUpdateByPosition()
proto native void EntityAI::StatUpdateByPosition (string name) protected
Updates stat counter by player's actual position.
Use this to measure player's travelling distance.
Parameters
[in] name The name of the stat type.
StatUpdateByTime()
proto native void EntityAI::StatUpdateByTime (string name) protected
Updates stat counter by time.
Use this to measure play time.
Parameters
[in] name The name of the stat type.
StopDeathDarkeningEffect()
void EntityAI::StopDeathDarkeningEffect () protected
SwapEntitiesImpl()
bool EntityAI::SwapEntitiesImpl (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2) inline protected
Definition at line 518 of file Man.c.
  {
    bool code;
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " ::SwapImpl(" + typename.EnumToString(InventoryMode, mode) + ") item1=" + Object.GetDebugName(item1) + " item2=" + item2.GetDebugName(this));
    if (!GameInventory.CanSwapEntitiesEx(item1, item2))
      Error("[inv] (Man@" + this + ") SwapEntitiesImpl - cannot swap items!");
    code = GetHumanInventory().SwapEntities(mode, item1, item2);
    UpdateInventoryMenu();
    if (!code)
      if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + "  SwapEntitiesImpl - cannot swap or forceswap");
    return code;
  }
References GameInventory::CanSwapEntitiesEx(), Error(), GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), HumanInventory::SwapEntities(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by JunctureSwapEntities(), LocalSwapEntities(), PredictiveSwapEntities(), and ServerSwapEntities().
SwitchOn()
proto native void EntityAI::SwitchOn (bool onOff) private
Some inventoryItem devices can be switched on/off (radios, transmitters)
Synchronize()
proto native void EntityAI::Synchronize () private
Synchronizes car's state in case the simulation is not running.
TakeEntityAsAttachmentExImpl()
bool EntityAI::TakeEntityAsAttachmentExImpl (InventoryMode mode, notnull EntityAI item, int slot) inline protected
Definition at line 477 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " ::Take2AttEx(" + typename.EnumToString(InventoryMode, mode) + ") item=" + Object.GetDebugName(item));
    bool code = GetHumanInventory().TakeEntityAsAttachmentEx(mode, item, slot);
    UpdateInventoryMenu();
    return code;
  }
References GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), syncDebugPrint(), HumanInventory::TakeEntityAsAttachmentEx(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityAsAttachmentEx(), LocalTakeEntityAsAttachmentEx(), PredictiveTakeEntityAsAttachmentEx(), and ServerTakeEntityAsAttachmentEx().
TakeEntityAsAttachmentImpl()
bool EntityAI::TakeEntityAsAttachmentImpl (InventoryMode mode, notnull EntityAI item) inline protected
Definition at line 438 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " ::Take2Att(" + typename.EnumToString(InventoryMode, mode) + ") item=" + Object.GetDebugName(item));
    bool code = GetHumanInventory().TakeEntityAsAttachment(mode, item);
    UpdateInventoryMenu();
    return code;
  }
References GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), syncDebugPrint(), GameInventory::TakeEntityAsAttachment(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityAsAttachment(), LocalTakeEntityAsAttachment(), PredictiveTakeEntityAsAttachment(), and ServerTakeEntityAsAttachment().
TakeEntityToCargoImpl()
bool EntityAI::TakeEntityToCargoImpl (InventoryMode mode, notnull EntityAI item) inline protected
Definition at line 399 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " ::Take2Cgo(" + typename.EnumToString(InventoryMode, mode) + ") item=" + Object.GetDebugName(item));
    bool code = GetHumanInventory().TakeEntityToCargo(mode, item);
    UpdateInventoryMenu();
    return code;
  }
References GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), syncDebugPrint(), GameInventory::TakeEntityToCargo(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityToCargo(), LocalTakeEntityToCargo(), PredictiveTakeEntityToCargo(), and ServerTakeEntityToCargo().
TakeEntityToHandsImpl()
void EntityAI::TakeEntityToHandsImpl (InventoryMode mode, EntityAI item) inline protected
Definition at line 178 of file Man.c.
  {
    if (!GetGame().IsDedicatedServer())
    {
      InventoryLocation il = new InventoryLocation;
      il.SetHands(this, item);
      //GetInventory().AddInventoryReservationEx(item, il ,GameInventory.c_InventoryReservationTimeoutShortMS);
    }
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " ::Take2Hands(" + typename.EnumToString(InventoryMode, mode) + ") item=" + Object.GetDebugName(item));
    EntityAI itemInHands = GetHumanInventory().GetEntityInHands();
    InventoryLocation src_item = new InventoryLocation;
    if (item.GetInventory().GetCurrentInventoryLocation(src_item))
    {
      if (itemInHands == null)
      {
        InventoryLocation hand_dst = new InventoryLocation;
        hand_dst.SetHands(this, item);
        GetHumanInventory().TakeToDst(mode, src_item, hand_dst);
      }
      else if (GetHumanInventory().CanSwapEntitiesEx(itemInHands, item))
        GetInventory().SwapEntities(mode, itemInHands, item);
      UpdateInventoryMenu();
    }
  }
References GetDebugName(), HumanInventory::GetEntityInHands(), GetGame(), GetHumanInventory(), LogManager::IsSyncLogEnable(), syncDebugPrint(), HumanInventory::TakeToDst(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityToHands(), LocalTakeEntityToHands(), PredictiveTakeEntityToHands(), and ServerTakeEntityToHands().
TakeEntityToInventoryImpl()
bool EntityAI::TakeEntityToInventoryImpl (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item) inline protected
Definition at line 360 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " ::Take2Inv(" + typename.EnumToString(InventoryMode, mode) + ") item=" + Object.GetDebugName(item));
    bool code = GetHumanInventory().TakeEntityToInventory(mode, flags, item);
    UpdateInventoryMenu();
    return code;
  }
References GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), syncDebugPrint(), HumanInventory::TakeEntityToInventory(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityToInventory(), LocalTakeEntityToInventory(), PredictiveTakeEntityToInventory(), and ServerTakeEntityToInventory().
TakeEntityToTargetAttachmentExImpl()
bool EntityAI::TakeEntityToTargetAttachmentExImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item, int slot) inline protected
Definition at line 742 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " ::Take2TargetAtt(" + typename.EnumToString(InventoryMode, mode) + ") item=" + Object.GetDebugName(item));
    bool code = GetInventory().TakeEntityAsTargetAttachmentEx(mode, target, item, slot);
    UpdateInventoryMenu();
    return code;
  }
References GetDebugName(), LogManager::IsSyncLogEnable(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityToTargetAttachmentEx(), LocalTakeEntityToTargetAttachmentEx(), PredictiveTakeEntityToTargetAttachmentEx(), ServerTakeEntityToTargetAttachmentEx(), and TakeEntityToTargetAttachmentImpl().
TakeEntityToTargetAttachmentImpl()
bool EntityAI::TakeEntityToTargetAttachmentImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item) inline protected
Definition at line 781 of file Man.c.
  {
    InventoryLocation il = new InventoryLocation;
    if (target.GetInventory().FindFreeLocationFor(item, FindInventoryLocationType.ATTACHMENT, il))
      return TakeEntityToTargetAttachmentExImpl(mode, target, item, il.GetSlot());
    return false;
  }
References TakeEntityToTargetAttachmentExImpl().
Referenced by JunctureTakeEntityToTargetAttachment(), LocalTakeEntityToTargetAttachment(), PredictiveTakeEntityToTargetAttachment(), and ServerTakeEntityToTargetAttachment().
TakeEntityToTargetCargoExImpl()
bool EntityAI::TakeEntityToTargetCargoExImpl (InventoryMode mode, notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline protected
Definition at line 660 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " ::Take2TargetCgoEx(" + typename.EnumToString(InventoryMode, mode) + ") item=" + Object.GetDebugName(item));
    bool code = GetInventory().TakeEntityToTargetCargoEx(mode, cargo, item, row, col);
    UpdateInventoryMenu();
    return code;
  }
References GetDebugName(), LogManager::IsSyncLogEnable(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityToTargetCargoEx(), LocalTakeEntityToTargetCargoEx(), PredictiveTakeEntityToTargetCargoEx(), and ServerTakeEntityToTargetCargoEx().
TakeEntityToTargetCargoImpl()
bool EntityAI::TakeEntityToTargetCargoImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item) inline protected
Definition at line 702 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " Take2TargetCgo(" + typename.EnumToString(InventoryMode, mode) + ") item=" + Object.GetDebugName(item));
    bool code = GetInventory().TakeEntityToTargetInventory(mode, target, FindInventoryLocationType.CARGO, item);
    UpdateInventoryMenu();
    return code;
  }
References GetDebugName(), LogManager::IsSyncLogEnable(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityToTargetCargo(), LocalTakeEntityToTargetCargo(), PredictiveTakeEntityToTargetCargo(), and ServerTakeEntityToTargetCargo().
TakeEntityToTargetInventoryImpl()
bool EntityAI::TakeEntityToTargetInventoryImpl (InventoryMode mode, notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline protected
Definition at line 621 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " ::Take2TargetInv(" + typename.EnumToString(InventoryMode, mode) + ") item=" + Object.GetDebugName(item));
    bool code = GetInventory().TakeEntityToTargetInventory(mode, target, flags, item);
    UpdateInventoryMenu();
    return code;
  }
References GetDebugName(), LogManager::IsSyncLogEnable(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityToTargetInventory(), LocalTakeEntityToTargetInventory(), and PredictiveTakeEntityToTargetInventory().
TakeToDstImpl()
bool EntityAI::TakeToDstImpl (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst) inline protected
Definition at line 820 of file Man.c.
  {
    if (LogManager.IsSyncLogEnable()) syncDebugPrint("[inv] " + GetDebugName(this) + " STS = " + GetSimulationTimeStamp() + " ::Take2Dst(" + typename.EnumToString(InventoryMode, mode) + ") src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
    bool code = GetHumanInventory().TakeToDst(mode, src, dst);
    UpdateInventoryMenu();
    return code;
  }
References InventoryLocation::DumpToStringNullSafe(), GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), syncDebugPrint(), HumanInventory::TakeToDst(), and UpdateInventoryMenu().
Referenced by JunctureTakeToDst(), LocalTakeToDst(), PredictiveTakeToDst(), and ServerTakeToDst().
ThrowPhysically()
proto native void EntityAI::ThrowPhysically (DayZPlayer player, vector force, bool collideWithCharacters = true) private
Transport()
void EntityAI::Transport () inline private
Definition at line 10 of file Transport.c.
  {
  }
TurnOffTransmitter()
void EntityAI::TurnOffTransmitter () inline private
Definition at line 50 of file AdvancedCommunication.c.
  {
    GetCompEM().SwitchOff();
  }
TurnOnTransmitter()
void EntityAI::TurnOnTransmitter () inline private
Definition at line 45 of file AdvancedCommunication.c.
  {
    GetCompEM().SwitchOn();
  }
UnlockDoor()
proto native void EntityAI::UnlockDoor (int index) private
Unlocks the door if locked.
UpdateInventoryMenu()
void EntityAI::UpdateInventoryMenu () protected
Referenced by DropEntityImpl(), ForceSwapEntitiesImpl(), LocalDestroyEntityInHands(), PredictiveMoveItemFromHandsToInventory(), ReplaceItemElsewhereWithNewInHandsImpl(), ReplaceItemInHandsWithNewElsewhereImpl(), ReplaceItemInHandsWithNewImpl(), ReplaceItemWithNewImpl(), SwapEntitiesImpl(), TakeEntityAsAttachmentExImpl(), TakeEntityAsAttachmentImpl(), TakeEntityToCargoImpl(), TakeEntityToHandsImpl(), TakeEntityToInventoryImpl(), TakeEntityToTargetAttachmentExImpl(), TakeEntityToTargetCargoExImpl(), TakeEntityToTargetCargoImpl(), TakeEntityToTargetInventoryImpl(), and TakeToDstImpl().
Member Data Documentation
m_ActionsInitialize
bool EntityAI::m_ActionsInitialize private
Definition at line 5 of file AdvancedCommunication.c.
m_AdvComTypeActionsMap
ref map<typename, ref TInputActionMap> EntityAI::m_AdvComTypeActionsMap = new map<typename, ref TInputActionMap> static private
Definition at line 3 of file AdvancedCommunication.c.
m_ContinuousActions
ref TIntArray EntityAI::m_ContinuousActions private
Definition at line 7 of file Transport.c.
m_InputActionMap
TInputActionMap EntityAI::m_InputActionMap private
Definition at line 4 of file AdvancedCommunication.c.
m_InteractActions
ref TIntArray EntityAI::m_InteractActions private
Definition at line 221 of file Building.c.
m_IsMeleeWeapon
bool EntityAI::m_IsMeleeWeapon = false private
Definition at line 11 of file InventoryItem.c.
m_OnItemAddedToHands
ref ScriptInvoker EntityAI::m_OnItemAddedToHands protected
Definition at line 68 of file Man.c.
Referenced by GetOnItemAddedToHands().
m_OnItemRemovedFromHands
ref ScriptInvoker EntityAI::m_OnItemRemovedFromHands protected
Definition at line 70 of file Man.c.
Referenced by GetOnItemRemovedFromHands().
m_SingleUseActions
ref TIntArray EntityAI::m_SingleUseActions private
Definition at line 6 of file Transport.c.
m_SoundContactTickTime
float EntityAI::m_SoundContactTickTime private
Definition at line 10 of file InventoryItem.c.
m_SoundImpactTable
SoundLookupTable EntityAI::m_SoundImpactTable private
Definition at line 9 of file InventoryItem.c.
SOUND_CONTACT_SKIP
const float EntityAI::SOUND_CONTACT_SKIP = 0.33 static private
Definition at line 3 of file InventoryItem.c.
The documentation for this class was generated from the following files:
scripts/3_Game/Entities/Building.c
scripts/3_Game/Entities/InventoryItem.c
scripts/3_Game/Entities/Man.c
scripts/3_Game/Vehicles/Transport.c
scripts/4_World/Entities/AdvancedCommunication/AdvancedCommunication.c