DayZ: scripts/4_World/Classes/SoundEvents/PlayerSoundEvents/Events/JumpEvents.c File Reference
JumpEvents.c File Reference
Classes
class PlayerSoundEventBase
Functions
class JumpEventsBase extends PlayerSoundEventBase JumpSoundEvent ()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override bool CanPlay (PlayerBase player)
override void OnPlay (PlayerBase player)
override void OnEnd ()
Function Documentation
CanPlay()
override bool JumpSoundEvent::CanPlay (PlayerBase player)
Definition at line 39 of file JumpEvents.c.
HasPriorityOverCurrent()
override bool JumpSoundEvent::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
Definition at line 34 of file JumpEvents.c.
  {
    m_HasPriorityOverTypes = -1;//-1 for all
    m_Type = EPlayerSoundEventType.GENERAL;
    m_ID = EPlayerSoundEventID.JUMP;
References m_HasPriorityOverTypes, m_ID, m_SoundVoiceAnimEventClassID, and m_Type.
JumpSoundEvent()
class JumpEventsBase extends PlayerSoundEventBase JumpSoundEvent ()
Definition at line 1 of file JumpEvents.c.
  {
    m_HasPriorityOverTypes = -1;//-1 for all
    m_Type = EPlayerSoundEventType.GENERAL;
    m_ID = EPlayerSoundEventID.JUMP;
    m_SoundVoiceAnimEventClassID = 18;
  }
Referenced by PlayerSoundEventHandler().
OnEnd()
override void JumpSoundEvent::OnEnd ()
Definition at line 53 of file JumpEvents.c.
{
  override bool HasPriorityOverCurrent(PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
  {
    return true;
  }
  override bool CanPlay(PlayerBase player)
  {
    if (!super.CanPlay(player))
      return false;
    return true;
  }
  override void OnPlay(PlayerBase player)
  {
    super.OnPlay(player);
    if (player.CanSpawnBreathVaporEffect())
      player.SpawnBreathVaporEffect();
  }
  override void OnEnd()
  {
    super.OnEnd();
    //m_Player.GetStaminaSoundHandlerClient().PostponeStamina(1000);
    if (m_Player)
      StaminaSoundHandlerClient.Cast(m_Player.m_PlayerSoundManagerClient.GetHandler(eSoundHandlers.STAMINA)).PostponeStamina(1300);
  }
}
class JumpSoundEvent extends JumpEventsBase
{
  void JumpSoundEvent()
  {
    m_HasPriorityOverTypes = -1;//-1 for all
    m_Type = EPlayerSoundEventType.GENERAL;
    m_ID = EPlayerSoundEventID.JUMP;
    m_SoundVoiceAnimEventClassID = 18;
  }
}
Referenced by End(), and AnimatedActionBase::End().
OnPlay()
override void JumpSoundEvent::OnPlay (PlayerBase player)
Definition at line 46 of file JumpEvents.c.
{
  override bool HasPriorityOverCurrent(PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
  {
    return true;
  }
  override bool CanPlay(PlayerBase player)
  {
    if (!super.CanPlay(player))
      return false;
    return true;
  }
  override void OnPlay(PlayerBase player)
  {
    super.OnPlay(player);
    if (player.CanSpawnBreathVaporEffect())
      player.SpawnBreathVaporEffect();
  }
  override void OnEnd()
  {
    super.OnEnd();
    //m_Player.GetStaminaSoundHandlerClient().PostponeStamina(1000);
    if (m_Player)
      StaminaSoundHandlerClient.Cast(m_Player.m_PlayerSoundManagerClient.GetHandler(eSoundHandlers.STAMINA)).PostponeStamina(1300);
  }
}
class JumpSoundEvent extends JumpEventsBase
{
  void JumpSoundEvent()
  {
    m_HasPriorityOverTypes = -1;//-1 for all
    m_Type = EPlayerSoundEventType.GENERAL;
    m_ID = EPlayerSoundEventID.JUMP;
    m_SoundVoiceAnimEventClassID = 18;
  }
}