DayZ: Weapon Class Reference
Weapon Class Reference
script counterpart to engine's class Weapon
Protected Member Functions
void Weapon_Base ()
void InitStateMachine ()
override void EEInit ()
void SetInitialState (WeaponStableState initState)
bool IsCharged ()
void SetCharged (bool value)
bool IsWeaponOpen ()
void SetWeaponOpen (bool value)
float GetWeightSpecialized (bool forceRecalc=false)
void AssembleGun ()
override on weapons with some assembly required
bool CanProcessAction (int action, int actionType)
bool HasActionAbility (int action, int actionType)
query if weapon supports action and actionType
int GetAbilityCount ()
AbilityRecord GetAbility (int index)
bool CanProcessWeaponEvents ()
WeaponStateBase GetCurrentState ()
returns currently active state
bool IsWaitingForActionFinish ()
returns true if state machine started playing action/actionType and waits for finish
bool IsIdle ()
bool ProcessWeaponEvent (WeaponEventBase e)
weapon's fsm handling of events @NOTE: warning: ProcessWeaponEvent can be called only within DayZPlayer::HandleWeapons (or CommandHandler)
bool ProcessWeaponAbortEvent (WeaponEventBase e)
bool CanChamberBullet (int muzzleIndex, Magazine mag)
void SetWeaponAnimState (int state)
void ResetWeaponAnimState ()
int GetWeaponAnimState ()
void EEFired (int muzzleType, int mode, string ammoType)
bool JamCheck (int muzzleIndex)
void ShowBullet (int muzzleIndex)
void HideBullet (int muzzleIndex)
bool IsJammed ()
bool CanEjectBullet ()
void SetJammed (bool value)
float GetSyncChanceToJam ()
float GetChanceToJam ()
void SyncSelectionState (bool has_bullet, bool has_mag)
void ForceSyncSelectionState ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
void SaveCurrentFSMState (ParamsWriteContext ctx)
bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
override void OnStoreSave (ParamsWriteContext ctx)
int GetInternalStateID ()
int GetCurrentStableStateID ()
tries to return identifier of current stable state (or nearest stable state if unstable state is currently running)
void RandomizeFSMState ()
With the parameters given, selects a random suitable state for the FSM of the weapon @WARNING: Weapon_Base.Synchronize call might be needed, if this method is called while clients are connected.
array< MuzzleState > GetMuzzleStates ()
Helper method for RandomizeFSMState.
Protected Attributes
const float DEFAULT_DAMAGE_ON_SHOT = 0.05
ref array< ref AbilityRecord > m_abilities = new array<ref AbilityRecord>
ref WeaponFSM m_fsm
weapon abilities
bool m_isJammed = false
weapon state machine
bool m_LiftWeapon = false
bool m_BayonetAttached
bool m_ButtstockAttached
bool m_Charged = false
bool m_WeaponOpen = false
int m_BurstCount
int m_BayonetAttachmentIdx
int m_ButtstockAttachmentIdx
int m_weaponAnimState = -1
int m_magazineSimpleSelectionIndex = -1
animation state the weapon is in, -1 == uninitialized
int m_weaponHideBarrelIdx = -1
float m_DmgPerShot = 0
float m_WeaponLength
float m_WeaponLiftCheckVerticalOffset
float m_ShoulderDistance
vector m_LastLiftPosition
ref array< int > m_bulletSelectionIndex = new array<int>
ref array< float > m_DOFProperties
ref array< float > m_ChanceToJam = new array<float>
float m_ChanceToJamSync = 0
ref PropertyModifiers m_PropertyModifierObject
PhxInteractionLayers hit_mask = PhxInteractionLayers.CHARACTER | PhxInteractionLayers.BUILDING | PhxInteractionLayers.DOOR | PhxInteractionLayers.VEHICLE | PhxInteractionLayers.ROADWAY | PhxInteractionLayers.TERRAIN | PhxInteractionLayers.ITEM_SMALL | PhxInteractionLayers.ITEM_LARGE | PhxInteractionLayers.FENCE | PhxInteractionLayers.AI
Private Member Functions
override int GetSlotsCountCorrect ()
Returns number of slots for attachments corrected for weapons.
Private Attributes
const int SAMF_DEFAULT = WeaponWithAmmoFlags.CHAMBER | WeaponWithAmmoFlags.MAX_CAPACITY_MAG
Full highest capacity magazine + chambered round.
const int SAMF_RNG = WeaponWithAmmoFlags.CHAMBER_RNG | WeaponWithAmmoFlags.QUANTITY_RNG
Random bullet quantity + maybe chambered round.
Weapon With Ammo
Helpers for spawning ammo/magazine in weapon For the flags, either a combination of WeaponWithAmmoFlags can be used Or one of the preset 'const int' with 'SAMF_' prefix (SAMF_DEFAULT, SAMF_RNG)
bool SpawnAmmo (string magazineType="", int flags=WeaponWithAmmoFlags.CHAMBER)
General method trying to attch magazine, fill inner magazine and fill chamber.
Magazine SpawnAttachedMagazine (string magazineType="", int flags=WeaponWithAmmoFlags.CHAMBER)
Try to spawn and attach a magazine.
bool FillInnerMagazine (string ammoType="", int flags=WeaponWithAmmoFlags.CHAMBER)
Try to fill the inner magazine.
bool FillChamber (string ammoType="", int flags=WeaponWithAmmoFlags.CHAMBER)
Try to fill the chamber.
override int GetSlotsCountCorrect ()
Returns number of slots for attachments corrected for weapons.
PropertyModifiers GetPropertyModifierObject ()
void OnFire (int muzzle_index)
void OnFireModeChange (int fireMode)
void ValidateAndRepair ()
override void OnInventoryEnter (Man player)
override void OnInventoryExit (Man player)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanRemoveFromHands (EntityAI parent)
bool IsRemoteWeapon ()
void SyncEventToRemote (WeaponEventBase e)
RecoilBase SpawnRecoilObject ()
int GetWeaponSpecificCommand (int weaponAction, int subCommand)
bool CanFire ()
bool CanEnterIronsights ()
bool InitDOFProperties (out array< float > temp_array)
Initializes DOF properties for weapon's ironsight/optics cameras.
bool InitReliability (out array< float > reliability_array)
bool InitWeaponLength ()
gets weapon length from config for weaponlift raycast
bool InitWeaponLiftCheckVerticalOffset ()
gets weapon vertical offset from config for weaponlift raycast
bool InitShoulderDistance ()
gets approximate weapon distance from shoulder from config
ref array< float > GetWeaponDOF ()
bool LiftWeaponCheck (PlayerBase player)
bool LiftWeaponRaycastResultCheck (notnull RaycastRVResult res)
Return whether provided material triggers weapon lift (true) or not (false).
float GetEffectiveAttachmentLength ()
Returns effective length of attachments that influence total weapon length.
void SetSyncJammingChance (float jamming_chance)
bool EjectCartridge (int muzzleIndex, out float ammoDamage, out string ammoTypeName)
unload bullet from chamber or internal magazine
bool CopyWeaponStateFrom (notnull Weapon_Base src)
override void SetBayonetAttached (bool pState, int slot_idx=-1)
attachment helpers (firearm melee)
override bool HasBayonetAttached ()
override int GetBayonetAttachmentIdx ()
override void SetButtstockAttached (bool pState, int slot_idx=-1)
override bool HasButtstockAttached ()
override int GetButtstockAttachmentIdx ()
void HideWeaponBarrel (bool state)
void ShowMagazine ()
void HideMagazine ()
override EntityAI ProcessMeleeItemDamage (int mode=0)
bool IsShowingChamberedBullet ()
int GetBurstCount ()
void ResetBurstCount ()
override void SetActions ()
override bool CanBeUsedForSuicide ()
override void OnDebugSpawn ()
static Weapon_Base CreateWeaponWithAmmo (string weaponType, string magazineType="", int flags=WeaponWithAmmoFlags.CHAMBER)
Create weapon with ammo.
Detailed Description
script counterpart to engine's class Weapon
Definition at line 48 of file InventoryItem.c.
Member Function Documentation
AfterStoreLoad()
override void Weapon::AfterStoreLoad () inline protected
Definition at line 583 of file Weapon_Base.c.
  {
    if (m_fsm)
    {
      int mi = GetCurrentMuzzle();
      Magazine mag = GetMagazine(mi);
      bool has_mag = mag != null;
      bool has_bullet = !IsChamberEmpty(mi);
      SyncSelectionState(has_bullet, has_mag);
    }
  }
AssembleGun()
void Weapon::AssembleGun () protected
override on weapons with some assembly required
CanBeUsedForSuicide()
override bool Weapon::CanBeUsedForSuicide () inline protected
Definition at line 1761 of file Weapon_Base.c.
  {
    if (!ConfigGetBool("isSuicideWeapon"))
      return false;
    return super.CanBeUsedForSuicide();
  }
CanChamberBullet()
bool Weapon::CanChamberBullet (int muzzleIndex, Magazine mag) inline protected
Definition at line 303 of file Weapon_Base.c.
  {
    return CanChamberFromMag(muzzleIndex, mag) && (!IsChamberFull(muzzleIndex) || IsChamberFiredOut(muzzleIndex) || !IsInternalMagazineFull(muzzleIndex));
  }
References IsChamberFiredOut(), and IsChamberFull().
CanEjectBullet()
bool Weapon::CanEjectBullet () inline protected
Definition at line 383 of file Weapon_Base.c.
{return true;}
CanEnterIronsights()
bool Weapon::CanEnterIronsights () inline protected
Definition at line 1160 of file Weapon_Base.c.
  {
    ItemOptics optic = GetAttachedOptics();
    if (!optic)
      return true;
    return optic.HasWeaponIronsightsOverride();
  }
CanFire()
bool Weapon::CanFire () inline protected
Definition at line 1153 of file Weapon_Base.c.
  {
    if (!IsChamberEmpty(GetCurrentMuzzle()) && !IsChamberFiredOut(GetCurrentMuzzle()) && !IsJammed() && !m_LiftWeapon && !IsDamageDestroyed())
      return true;
    return false;
  }
References IsChamberFiredOut(), IsDamageDestroyed(), and IsJammed().
CanProcessAction()
bool Weapon::CanProcessAction (int action, int actionType) inline protected
Definition at line 215 of file Weapon_Base.c.
  {
    return false; // @TODO
  }
CanProcessWeaponEvents()
Weapon::CanProcessWeaponEvents () inline protected
Returns
true if weapon has running fsm
Definition at line 249 of file Weapon_Base.c.
{ return m_fsm && m_fsm.IsRunning(); }
CanReleaseAttachment()
override bool Weapon::CanReleaseAttachment (EntityAI attachment) inline protected
Definition at line 1082 of file Weapon_Base.c.
  {
    if (!super.CanReleaseAttachment(attachment))
      return false;
    Magazine mag = Magazine.Cast(attachment);
    if (mag)
    {
      PlayerBase player = PlayerBase.Cast(GetHierarchyRootPlayer());
      if (player)
      {
        if (player.GetItemInHands() == this)
          return true;
      }
      return false;
    }
    return true;
  }
CanRemoveFromHands()
override bool Weapon::CanRemoveFromHands (EntityAI parent) inline protected
Definition at line 1101 of file Weapon_Base.c.
  {
    if (IsIdle())
      return true;
    if (LogManager.IsWeaponLogEnable()) wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(this) + " Weapon=" + this + " not in stable state=" + GetCurrentState().Type());
    return false; // do not allow removal of weapon while weapon is busy
  }
References IsIdle(), LogManager::IsWeaponLogEnable(), Type, and wpnDebugPrint().
CopyWeaponStateFrom()
bool Weapon::CopyWeaponStateFrom (notnull Weapon_Base src) inline protected
Definition at line 1611 of file Weapon_Base.c.
  {
    float damage = 0.0;
    string type;
    for (int mi = 0; mi < src.GetMuzzleCount(); ++mi)
    {
      if (!src.IsChamberEmpty(mi))
      {
        if (src.GetCartridgeInfo(mi, damage, type))
          PushCartridgeToChamber(mi, damage, type);
      }
      for (int ci = 0; ci < src.GetInternalMagazineCartridgeCount(mi); ++ci)
      {
        if (src.GetInternalMagazineCartridgeInfo(mi, ci, damage, type))
          PushCartridgeToInternalMagazine(mi, damage, type);
      }
    }
    int dummy_version = int.MAX;
    PlayerBase parentPlayer = PlayerBase.Cast(src.GetHierarchyRootPlayer());
    if (!parentPlayer)
      dummy_version -= 1;
    ScriptReadWriteContext ctx = new ScriptReadWriteContext;
    src.OnStoreSave(ctx.GetWriteContext());
    OnStoreLoad(ctx.GetReadContext(), dummy_version);
    return true;
  }
References OnStoreLoad().
CreateWeaponWithAmmo()
Weapon::CreateWeaponWithAmmo (string weaponType, string magazineType = "", int flags = WeaponWithAmmoFlags.CHAMBER) inline static protected
Create weapon with ammo.
Parameters
[in] weaponType string The weapon to create
[in] magazineType string The magazine to attach or ammo to load, passing in empty string will select random
[in] flags int Setup flags, please read WeaponWithAmmoFlags
Returns
The created weapon
Definition at line 697 of file Weapon_Base.c.
  {
    Weapon_Base wpn = Weapon_Base.Cast(GetGame().CreateObjectEx(weaponType, vector.Zero, ECE_PLACE_ON_SURFACE));
    if (!wpn)
    {
      ErrorEx(string.Format("%1 does not exist or is not a weapon.", weaponType));
      return null;
    }
    wpn.SpawnAmmo(magazineType, flags);
    return wpn;
  }
References ECE_PLACE_ON_SURFACE, ErrorEx, GetGame(), and vector::Zero.
EEFired()
void Weapon::EEFired (int muzzleType, int mode, string ammoType) inline protected
Definition at line 320 of file Weapon_Base.c.
  {
    if (!GetGame().IsDedicatedServer())
    {
      ItemBase suppressor = GetAttachedSuppressor();
      // Muzzle flash & overheating effects
      ItemBase.PlayFireParticles(this, muzzleType, ammoType, this, suppressor, "CfgWeapons");
      IncreaseOverheating(this, ammoType, this, suppressor, "CfgWeapons");
      if (suppressor)
      {
        ItemBase.PlayFireParticles(this, muzzleType, ammoType, suppressor, NULL, "CfgVehicles");
        suppressor.IncreaseOverheating(this, ammoType, this, suppressor, "CfgVehicles");
      }
    }
    //obsolete, replaced by C++ solution!
    /*
        if (GetGame().IsServer())
        {
          AddHealth("","Health",-m_DmgPerShot); //damages weapon
          if (suppressor)
            suppressor.AddHealth("","Health",-m_DmgPerShot); //damages suppressor; TODO add suppressor damage coeficient/parameter (?) to suppressors/weapons (?)
        }
    */
    //JamCheck(muzzleType);
#ifdef DIAG_DEVELOPER
    MiscGameplayFunctions.UnlimitedAmmoDebugCheck(this);
#endif
  }
References GetGame(), and IncreaseOverheating().
EEInit()
override void Weapon::EEInit () inline protected
Definition at line 116 of file Weapon_Base.c.
  {
    super.EEInit();
    if (GetGame().IsServer())
      GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).Call(AssembleGun);
  }
References Weapon_Base::AssembleGun(), CALL_CATEGORY_GAMEPLAY, and GetGame().
EEItemAttached()
override void Weapon::EEItemAttached (EntityAI item, string slot_name) inline protected
Definition at line 1033 of file Weapon_Base.c.
  {
    super.EEItemAttached(item, slot_name);
    GetPropertyModifierObject().UpdateModifiers();
  }
EEItemDetached()
override void Weapon::EEItemDetached (EntityAI item, string slot_name) inline protected
Definition at line 1040 of file Weapon_Base.c.
  {
    super.EEItemDetached(item, slot_name);
    GetPropertyModifierObject().UpdateModifiers();
  }
EEItemLocationChanged()
override void Weapon::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline protected
Definition at line 1047 of file Weapon_Base.c.
  {
    super.EEItemLocationChanged(oldLoc, newLoc);
    if (newLoc.GetType() == InventoryLocationType.HANDS)
    {
      PlayerBase player;
      if (newLoc.GetParent() && PlayerBase.CastTo(player, newLoc.GetParent()))
      {
        HumanCommandMove cm = player.GetCommand_Move();
        if (cm)
          cm.SetMeleeBlock(false);
      }
    }
  }
EjectCartridge()
Weapon::EjectCartridge (int muzzleIndex, out float ammoDamage, out string ammoTypeName) inline protected
unload bullet from chamber or internal magazine
@NOTE: EjectCartridge = GetCartridgeInfo + PopCartridge
Parameters
[in] muzzleIndex
[out] ammoDamage damage of the ammo
[out] ammoTypeName type name of the ejected ammo
Returns
true if bullet removed from chamber
Definition at line 1596 of file Weapon_Base.c.
  {
    if (IsChamberEjectable(muzzleIndex))
    {
      if (PopCartridgeFromChamber(muzzleIndex, ammoDamage, ammoTypeName))
        return true;
    }
    else if (GetInternalMagazineCartridgeCount(muzzleIndex) > 0)
    {
      if (PopCartridgeFromInternalMagazine(muzzleIndex, ammoDamage, ammoTypeName))
        return true;
    }
    return false;
  }
FillChamber()
Weapon::FillChamber (string ammoType = "", int flags = WeaponWithAmmoFlags.CHAMBER) inline protected
Try to fill the chamber.
Parameters
[in] ammoType string The ammo to load, passing in empty string will select random
Note
It is best to fill in the actual 'ammo', as in the ones usually prefixed by 'Bullet_', to skip searching for it
Parameters
[in] flags int Setup flags, please read WeaponWithAmmoFlags
Returns
Whether any chamber was filled
Definition at line 862 of file Weapon_Base.c.
  {
    // Quickly check if there are any chambers we can fill
    int muzzCount = GetMuzzleCount();
    bool anyEmpty = false;
    for (int m = 0; m < muzzCount; ++m)
    {
      if (IsChamberEmpty(m))
      {
        anyEmpty = true;
        break;
      }
    }
    if (!anyEmpty)
      return false;
    // Make sure the given ammoType is actually useable
    if (ammoType != "")
      if (!AmmoTypesAPI.MagazineTypeToAmmoType(ammoType, ammoType))
        return false;
    // Just so we don't '&' wastefully in a loop
    bool didSomething = false;
    bool chamberFullRng = (flags & WeaponWithAmmoFlags.CHAMBER_RNG_SPORADIC);
    bool chamberRng = (flags & WeaponWithAmmoFlags.CHAMBER_RNG);
    bool chamber = (flags & WeaponWithAmmoFlags.CHAMBER);
    if (chamber || chamberRng || chamberFullRng)
    {
      int amountToChamber = muzzCount;
      // No need to do this for full rng, as that will roll for every muzzle
      if (chamberRng)
        amountToChamber = Math.RandomIntInclusive(0, muzzCount);
      bool chamberAmmoRng = (ammoType == "");
      bool chamberAmmoFullRng = chamberAmmoRng && (flags & WeaponWithAmmoFlags.AMMO_CHAMBER_RNG);
      // No full RNG flag, so pick one random and use only this one
      if (chamberAmmoRng && !chamberAmmoFullRng)
        ammoType = GetRandomChamberableAmmoTypeName(0);
      for (int i = 0; i < muzzCount; ++i)
      {
        // Skip when there's already something in the chamber
        if (!IsChamberEmpty(i))
          continue;
        // Roll the rng when enabled
        if (chamberFullRng)
          chamber = Math.RandomIntInclusive(0, 1);
        // We chambering
        if (chamber)
        {
          // Full random, decide a new one for every muzzle
          if (chamberAmmoFullRng)
            ammoType = GetRandomChamberableAmmoTypeName(i);
          // Push it
          PushCartridgeToChamber(i, 0, ammoType);
          didSomething = true;
          // Stop chambering when we hit the desired amount
          --amountToChamber;
          if (amountToChamber <= 0)
            break;
        }
      }
    }
    // Only fix the FSM and Synchronize when absolutely needed
    if (!didSomething)
      return false;
    // FSM cares about chamber state
    RandomizeFSMState();
    Synchronize();
    return true;
  }
References AmmoTypesAPI::MagazineTypeToAmmoType(), Math::RandomIntInclusive(), and Synchronize().
FillInnerMagazine()
Weapon::FillInnerMagazine (string ammoType = "", int flags = WeaponWithAmmoFlags.CHAMBER) inline protected
Try to fill the inner magazine.
Parameters
[in] ammoType string The ammo to load, passing in empty string will select random
Note
It is best to fill in the actual 'ammo', as in the ones usually prefixed by 'Bullet_', to skip searching for it
Parameters
[in] flags int Setup flags, please read WeaponWithAmmoFlags
Returns
Whether any ammo was added to the gun or not
Definition at line 796 of file Weapon_Base.c.
  {
    // Don't try to fill it when there are none
    if (!HasInternalMagazine(-1))
      return false;
    // Make sure the given ammoType is actually useable
    if (ammoType != "")
    {
      if (!AmmoTypesAPI.MagazineTypeToAmmoType(ammoType, ammoType))
        return false;
    }
    bool didSomething = false;
    int muzzCount = GetMuzzleCount();
    bool ammoRng = ammoType == "";
    bool ammoFullRng = ammoRng && (flags & WeaponWithAmmoFlags.AMMO_MAG_RNG);
    // No full RNG flag, so pick one random and use only this one
    if (ammoRng && !ammoFullRng)
      ammoType = GetRandomChamberableAmmoTypeName(0);
    // Fill the internal magazine
    for (int i = 0; i < muzzCount; ++i)
    {
      int ammoCount = GetInternalMagazineMaxCartridgeCount(i);
      // Decide random quantity when enabled
      if (flags & WeaponWithAmmoFlags.QUANTITY_RNG)
        ammoCount = Math.RandomIntInclusive(0, ammoCount);
      // Only do the things when there is actually ammo to fill
      if (ammoCount > 0)
      {
        // Push in the cartridges
        for (int j = 0; j < ammoCount; ++j)
        {
          // Full random, decide a new one for every cartridge
          if (ammoFullRng)
            ammoType = GetRandomChamberableAmmoTypeName(i);
          PushCartridgeToInternalMagazine(i, 0, ammoType);
          didSomething = true;
        }
      }
    }
    // Call the chamber method if asked for
    bool chamber = (flags & WeaponWithAmmoFlags.CHAMBER) || (flags & WeaponWithAmmoFlags.CHAMBER_RNG);
    if (chamber && FillChamber(ammoType, flags))
      didSomething = true;
    // Does not need any FSM fixing, FSM does not care about inner magazines
    return didSomething;
  }
References AmmoTypesAPI::MagazineTypeToAmmoType(), and Math::RandomIntInclusive().
ForceSyncSelectionState()
void Weapon::ForceSyncSelectionState () inline protected
Definition at line 435 of file Weapon_Base.c.
  {
    int nMuzzles = GetMuzzleCount();
    for (int i = 0; i < nMuzzles; ++i)
    {
      if (IsChamberFull(i))
      {
        ShowBullet(i);
        float damage;
        string ammoTypeName;
        GetCartridgeInfo(i, damage, ammoTypeName);
        EffectBulletShow(i, damage, ammoTypeName);
      }
      else
      {
        HideBullet(i);
        EffectBulletHide(i);
      }
      Magazine mag = GetMagazine(i);
      if (mag)
        ShowMagazine();
      else
        HideMagazine();
    }
  }
References Weapon_Base::HideBullet(), IsChamberFull(), and Weapon_Base::ShowBullet().
GetAbility()
Weapon::GetAbility (int index) inline protected
Parameters
[in] index index into m_abilities storage
Returns
ability record
Definition at line 244 of file Weapon_Base.c.
{ return m_abilities.Get(index); }
GetAbilityCount()
Weapon::GetAbilityCount () inline protected
Returns
number of stored abilities
Definition at line 239 of file Weapon_Base.c.
{ return m_abilities.Count(); }
GetBayonetAttachmentIdx()
override int Weapon::GetBayonetAttachmentIdx () inline protected
Definition at line 1653 of file Weapon_Base.c.
  {
    return m_BayonetAttachmentIdx;
  }
GetBurstCount()
int Weapon::GetBurstCount () inline protected
Definition at line 1737 of file Weapon_Base.c.
  {
    return m_BurstCount;
  }
GetButtstockAttachmentIdx()
override int Weapon::GetButtstockAttachmentIdx () inline protected
Definition at line 1669 of file Weapon_Base.c.
  {
    return m_ButtstockAttachmentIdx;
  }
GetChanceToJam()
float Weapon::GetChanceToJam () inline protected
Definition at line 386 of file Weapon_Base.c.
  {
    int level = GetHealthLevel();
    if (level >= 0 && level < m_ChanceToJam.Count())
      return m_ChanceToJam[level];
    else
      return 0.0;
  }
GetCurrentStableStateID()
Weapon::GetCurrentStableStateID () inline protected
tries to return identifier of current stable state (or nearest stable state if unstable state is currently running)
Definition at line 633 of file Weapon_Base.c.
  {
    if (m_fsm)
      return m_fsm.GetCurrentStableStateID();
    return 0;
  }
GetCurrentState()
Weapon::GetCurrentState () inline protected
returns currently active state
Returns
current state the FSM is in (or NULL)
Definition at line 255 of file Weapon_Base.c.
{ return m_fsm.GetCurrentState(); }
GetEffectiveAttachmentLength()
float Weapon::GetEffectiveAttachmentLength () inline protected
Returns effective length of attachments that influence total weapon length.
Definition at line 1564 of file Weapon_Base.c.
  {
    ItemBase attachment;
    if (HasBayonetAttached())
    {
      int bayonetIndex = GetBayonetAttachmentIdx();
      attachment = ItemBase.Cast(GetInventory().FindAttachment(bayonetIndex));
    }
    else
      attachment = GetAttachedSuppressor();
    if (attachment)
      return Math.Max(attachment.m_ItemModelLength + attachment.m_ItemAttachOffset, 0);
    else
      return 0;
  }
References Math::Max().
GetInternalStateID()
int Weapon::GetInternalStateID () inline protected
Definition at line 623 of file Weapon_Base.c.
  {
    if (m_fsm)
      return m_fsm.GetInternalStateID();
    return 0;
  }
GetMuzzleStates()
array< MuzzleState > Weapon::GetMuzzleStates () inline protected
Helper method for RandomizeFSMState.
Definition at line 660 of file Weapon_Base.c.
  {
    array<MuzzleState> muzzleStates = new array<MuzzleState>;
    int nMuzzles = GetMuzzleCount();
    for (int i = 0; i < nMuzzles; ++i)
    {
      MuzzleState state = MuzzleState.U;
      if (IsChamberFiredOut(i))
        state = MuzzleState.F;
      else if (IsChamberFull(i))
        state = MuzzleState.L;
      else if (IsChamberEmpty(i))
        state = MuzzleState.E;
      else
        ErrorEx(string.Format("Unable to identify chamber state of muzzle %1", i));
      muzzleStates.Insert(state);
    }
    return muzzleStates;
  }
References ErrorEx, IsChamberFiredOut(), and IsChamberFull().
GetPropertyModifierObject()
PropertyModifiers Weapon::GetPropertyModifierObject () inline protected
Definition at line 960 of file Weapon_Base.c.
  {
    if (!m_PropertyModifierObject)
      m_PropertyModifierObject = new PropertyModifiers(this);
    return m_PropertyModifierObject;
  }
GetSlotsCountCorrect() [1/2]
override int Weapon::GetSlotsCountCorrect () inline protected
Returns number of slots for attachments corrected for weapons.
Definition at line 952 of file Weapon_Base.c.
  {
    int ac = GetInventory().AttachmentCount();
    int sc = GetInventory().GetAttachmentSlotsCount() + GetMuzzleCount();
    if (ac > sc) sc = ac; // fix of some weapons which has 1 attachments but 0 slots...
    return sc;
  };
GetSlotsCountCorrect() [2/2]
override int Weapon::GetSlotsCountCorrect () inline private
Returns number of slots for attachments corrected for weapons.
Definition at line 6 of file BinocularsBase.c.
  {
    return GetInventory().GetAttachmentSlotsCount();
  };
GetSyncChanceToJam()
float Weapon::GetSyncChanceToJam () inline protected
Definition at line 385 of file Weapon_Base.c.
{ return m_ChanceToJamSync; }
GetWeaponAnimState()
int Weapon::GetWeaponAnimState () inline protected
Definition at line 318 of file Weapon_Base.c.
{ return m_weaponAnimState; }
GetWeaponDOF()
ref array< float > Weapon::GetWeaponDOF () inline protected
Definition at line 1227 of file Weapon_Base.c.
  {
    return m_DOFProperties;
  }
GetWeaponSpecificCommand()
int Weapon::GetWeaponSpecificCommand (int weaponAction, int subCommand) inline protected
Definition at line 1148 of file Weapon_Base.c.
  {
    return subCommand;
  }
GetWeightSpecialized()
float Weapon::GetWeightSpecialized (bool forceRecalc = false) inline protected
Definition at line 152 of file Weapon_Base.c.
  {
    float baseWeight = GetInventoryAndCargoWeight(forceRecalc);
    float ammoWeight;
    float ammoDamage;
    string bulletTypeName, ammoTypeName;
    int muzzleCount = GetMuzzleCount();
#ifdef DEVELOPER
    if (WeightDebug.m_VerbosityFlags & WeightDebugType.RECALC_FORCED)
    {
      WeightDebugData data1 = WeightDebug.GetWeightDebug(this);
      data1.SetCalcDetails("TWPN: " + m_ConfigWeight + "(item weight) + " + baseWeight + "(contents weight)");
    }
#endif
    for (int muzzleIndex = 0; muzzleIndex < muzzleCount; muzzleIndex++)
    {
      //chamber weight
      if (!IsChamberEmpty(muzzleIndex))
      {
        ammoTypeName = GetChamberAmmoTypeName(muzzleIndex);
        ammoWeight += g_Game.ConfigGetFloat(string.Format("CfgMagazines %1 weight", ammoTypeName));
#ifdef DEVELOPER
        if (WeightDebug.m_VerbosityFlags & WeightDebugType.RECALC_FORCED)
        {
          WeightDebugData data2 = WeightDebug.GetWeightDebug(this);
          data2.AddCalcDetails(g_Game.ConfigGetFloat("CfgMagazines " + ammoTypeName + " weight").ToString() + "(chamber weight)");
        }
#endif
      }
      //correctly calculates internal magazine weight based on the ammo type of each bullet
      if (HasInternalMagazine(muzzleIndex))
      {
#ifdef DEVELOPER
        float debugInternalMagWeight;
#endif
        int cartridgeCount = GetInternalMagazineCartridgeCount(muzzleIndex);
        for (int cartridgeIndex = 0; cartridgeIndex < cartridgeCount; cartridgeIndex++)
        {
          GetInternalMagazineCartridgeInfo(muzzleIndex, cartridgeIndex, ammoDamage, bulletTypeName);
          ammoWeight += Ammunition_Base.GetAmmoWeightByBulletType(bulletTypeName);
#ifdef DEVELOPER
          debugInternalMagWeight += g_Game.ConfigGetFloat("CfgMagazines " + ammoTypeName + " weight");
#endif
        }
#ifdef DEVELOPER
        if (WeightDebug.m_VerbosityFlags & WeightDebugType.RECALC_FORCED)
        {
          WeightDebugData data3 = WeightDebug.GetWeightDebug(this);
          data3.AddCalcDetails(debugInternalMagWeight.ToString() + "(internal mag weight)");
        }
#endif
      }
    }
    return ammoWeight + baseWeight + GetConfigWeightModified();
  }
References g_Game, and Ammunition_Base::GetAmmoWeightByBulletType().
HasActionAbility()
Weapon::HasActionAbility (int action, int actionType) inline protected
query if weapon supports action and actionType
Parameters
[in] action one of Human.actions (i.e. RELOAD, MECHANISM, ...)
[in] actionType one of Human.actionTypes (i.e. CHAMBERING_ONEBULLET_CLOSED, MECHANISM_CLOSED...)
Returns
true if weapon supports operation
Definition at line 225 of file Weapon_Base.c.
  {
    int count = GetAbilityCount();
    for (int i = 0; i < count; ++i)
    {
      AbilityRecord rec = GetAbility(i);
      if (rec.m_action == action && rec.m_actionType == actionType)
        return true;
    }
    return false;
  }
HasBayonetAttached()
override bool Weapon::HasBayonetAttached () inline protected
Definition at line 1648 of file Weapon_Base.c.
  {
    return m_BayonetAttached;
  }
HasButtstockAttached()
override bool Weapon::HasButtstockAttached () inline protected
Definition at line 1664 of file Weapon_Base.c.
  {
    return m_ButtstockAttached;
  }
HideBullet()
void Weapon::HideBullet (int muzzleIndex) inline protected
Definition at line 374 of file Weapon_Base.c.
  {
    if (m_bulletSelectionIndex.Count() > muzzleIndex)
      SetSimpleHiddenSelectionState(m_bulletSelectionIndex[muzzleIndex], 0);
    else
      SelectionBulletHide();
  }
HideMagazine()
void Weapon::HideMagazine () inline protected
Definition at line 1692 of file Weapon_Base.c.
  {
    if (m_magazineSimpleSelectionIndex > -1)
      SetSimpleHiddenSelectionState(m_magazineSimpleSelectionIndex, 0);
    else
      SelectionMagazineHide();
  }
HideWeaponBarrel()
void Weapon::HideWeaponBarrel (bool state) inline protected
Definition at line 1674 of file Weapon_Base.c.
  {
    if (!GetGame().IsDedicatedServer()) //hidden for client only
    {
      ItemOptics optics = GetAttachedOptics();
      if (optics && !optics.AllowsDOF() && m_weaponHideBarrelIdx != -1)
        SetSimpleHiddenSelectionState(m_weaponHideBarrelIdx, !state);
    }
  }
References GetGame().
InitDOFProperties()
bool Weapon::InitDOFProperties (out array< float > temp_array) inline protected
Initializes DOF properties for weapon's ironsight/optics cameras.
Definition at line 1170 of file Weapon_Base.c.
  {
    if (GetGame().ConfigIsExisting("cfgWeapons " + GetType() + " PPDOFProperties"))
    {
      GetGame().ConfigGetFloatArray("cfgWeapons " + GetType() + " PPDOFProperties", temp_array);
      return true;
    }
    return false;
  }
References GetGame(), and GetType().
InitReliability()
bool Weapon::InitReliability (out array< float > reliability_array) inline protected
Definition at line 1180 of file Weapon_Base.c.
  {
    if (GetGame().ConfigIsExisting("cfgWeapons " + GetType() + " Reliability ChanceToJam"))
    {
      GetGame().ConfigGetFloatArray("cfgWeapons " + GetType() + " Reliability ChanceToJam", reliability_array);
      return true;
    }
    return false;
  }
References GetGame(), and GetType().
InitShoulderDistance()
bool Weapon::InitShoulderDistance () inline protected
gets approximate weapon distance from shoulder from config
Definition at line 1215 of file Weapon_Base.c.
  {
    if (ConfigIsExisting("ShoulderDistance"))
    {
      m_ShoulderDistance = ConfigGetFloat("ShoulderDistance");
      return true;
    }
    m_ShoulderDistance = 0;
    return false;
  }
InitStateMachine()
void Weapon::InitStateMachine () inline protected
Definition at line 114 of file Weapon_Base.c.
{ }
InitWeaponLength()
bool Weapon::InitWeaponLength () inline protected
gets weapon length from config for weaponlift raycast
Definition at line 1191 of file Weapon_Base.c.
  {
    if (ConfigIsExisting("WeaponLength"))
    {
      m_WeaponLength = ConfigGetFloat("WeaponLength");
      return true;
    }
    m_WeaponLength = 0.8; //default value if not set in config; should not be zero
    return false;
  }
InitWeaponLiftCheckVerticalOffset()
bool Weapon::InitWeaponLiftCheckVerticalOffset () inline protected
gets weapon vertical offset from config for weaponlift raycast
Definition at line 1203 of file Weapon_Base.c.
  {
    if (ConfigIsExisting("WeaponLiftCheckVerticalOffset"))
    {
      m_WeaponLiftCheckVerticalOffset = ConfigGetFloat("WeaponLiftCheckVerticalOffset");
      return true;
    }
    m_WeaponLiftCheckVerticalOffset = 0.0; //no offset by default
    return false;
  }
IsCharged()
bool Weapon::IsCharged () inline protected
Definition at line 132 of file Weapon_Base.c.
  {
    return m_Charged;
  }
IsIdle()
bool Weapon::IsIdle () inline protected
Definition at line 265 of file Weapon_Base.c.
  {
    return CanProcessWeaponEvents() && GetCurrentState().IsIdle();
  }
IsJammed()
bool Weapon::IsJammed () inline protected
Definition at line 382 of file Weapon_Base.c.
{ return m_isJammed; }
IsRemoteWeapon()
bool Weapon::IsRemoteWeapon () inline protected
Definition at line 1109 of file Weapon_Base.c.
  {
    InventoryLocation il = new InventoryLocation;
    if (GetInventory().GetCurrentInventoryLocation(il))
    {
      EntityAI parent = il.GetParent();
      DayZPlayer dayzp = DayZPlayer.Cast(parent);
      if (il.GetType() == InventoryLocationType.HANDS && dayzp)
      {
        bool remote = dayzp.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_REMOTE;
        return remote;
      }
    }
    return true;
  }
IsShowingChamberedBullet()
bool Weapon::IsShowingChamberedBullet () inline protected
Definition at line 1732 of file Weapon_Base.c.
  {
    return true;
  }
IsWaitingForActionFinish()
Weapon::IsWaitingForActionFinish () inline protected
returns true if state machine started playing action/actionType and waits for finish
Definition at line 260 of file Weapon_Base.c.
  {
    return CanProcessWeaponEvents() && GetCurrentState().IsWaitingForActionFinish();
  }
IsWeaponOpen()
bool Weapon::IsWeaponOpen () inline protected
Definition at line 142 of file Weapon_Base.c.
  {
    return m_WeaponOpen;
  }
JamCheck()
bool Weapon::JamCheck (int muzzleIndex) inline protected
Definition at line 353 of file Weapon_Base.c.
  {
    PlayerBase player = PlayerBase.Cast(GetHierarchyRootPlayer());
    if (player)
    {
      float rnd = player.GetRandomGeneratorSyncManager().GetRandom01(RandomGeneratorSyncUsage.RGSJam);
      //Print("Random Jam - " + rnd);
      if (rnd < GetSyncChanceToJam())
        return true;
    }
    return false;
  }
LiftWeaponCheck()
bool Weapon::LiftWeaponCheck (PlayerBase player) inline protected
snippet below measures distance from "RightHandIndex1" bone for lifting calibration
Definition at line 1233 of file Weapon_Base.c.
  {
    int idx;
    float distance;
    float hit_fraction; //junk
    vector start, end;
    vector direction;
    vector usti_hlavne_position;
    vector trigger_axis_position;
    vector hit_pos, hit_normal; //junk
    Object obj;
    ItemBase attachment;
    HumanMovementState movementState = new HumanMovementState();
    bool wasLift = m_LiftWeapon;
    vector lastLiftPosition = m_LastLiftPosition;
    m_LiftWeapon = false;
    // not a gun, no weap.raise for now
    if (HasSelection("Usti hlavne"))
      return false;
    if (!player)
    {
      Print("Error: No weapon owner, returning");
      return false;
    }
    // weapon not raised
    player.GetMovementState(movementState);
    if (!movementState.IsRaised())
      return false;
    // suppress raising of weapon during melee attack preventing state inconsistency
    if (movementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_MELEE || movementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_MELEE2)
      return false;
    usti_hlavne_position = GetSelectionPositionLS("Usti hlavne"); // Usti hlavne
    trigger_axis_position = GetSelectionPositionLS("trigger_axis");
    // If possible use aiming angles instead as these will work consistently
    // and independently of any cameras, etc.
    HumanCommandWeapons hcw = player.GetCommandModifier_Weapons();
    if (hcw)
    {
      vector yawPitchRoll = Vector(
                              hcw.GetBaseAimingAngleLR() + player.GetOrientation()[0],
                              hcw.GetBaseAimingAngleUD(),
                              0.0);
      direction = yawPitchRoll.AnglesToVector();
    }
    else // Fallback to previously implemented logic
    {
      // freelook raycast
      if (player.GetInputController().CameraIsFreeLook())
      {
        if (player.m_DirectionToCursor != vector.Zero)
          direction = player.m_DirectionToCursor;
        // if player raises weapon in freelook
        else
          direction = MiscGameplayFunctions.GetHeadingVector(player);
      }
      else
      {
        direction = GetGame().GetCurrentCameraDirection(); // exception for freelook. Much better this way!
      }
    }
    idx = player.GetBoneIndexByName("Neck"); //RightHandIndex1
    if (idx == -1)
      start = player.GetPosition()[1] + 1.5;
    else
      start = player.GetBonePositionWS(idx);
    // Updated weapon lift detection code prototype
    {
      // 0: construct stable trasformation matrix that
      // approximately aligns with the weapon transform
      // without actually using the weapon as reference
      // (as the weapon can be moved unpredictably by anims)
      vector resTM[4];
      resTM[0] = Vector(direction[0], 0, direction[2]).Normalized();
      resTM[0] = vector.RotateAroundZeroDeg(resTM[0], vector.Up, 90);
      resTM[2] = direction;
      resTM[1] = resTM[2] * resTM[0];
      resTM[3] = start;
      // Approximate the roll of leaning
      HumanMovementState hms = new HumanMovementState();
      player.GetMovementState(hms);
      float leanAngle = hms.m_fLeaning * 35;
      vector rotTM[3];
      Math3D.YawPitchRollMatrix(Vector(0, 0, leanAngle), rotTM);
      Math3D.MatrixMultiply3(resTM, rotTM, resTM);
      // Draw relative TM diagnostic
#ifdef DIAG_DEVELOPER
      if (DiagMenu.GetValue(DiagMenuIDs.WEAPON_LIFT_DEBUG))
      {
        Shape.CreateArrow(resTM[3], resTM[3] + resTM[0], 0.05, COLOR_RED, ShapeFlags.ONCE);
        Shape.CreateArrow(resTM[3], resTM[3] + resTM[1], 0.05, COLOR_GREEN, ShapeFlags.ONCE);
        Shape.CreateArrow(resTM[3], resTM[3] + resTM[2], 0.05, COLOR_BLUE, ShapeFlags.ONCE);
      }
#endif
      // 1: pick from predefined offset relative to
      // the previously constructed transform
      float udAngle = Math.Asin(direction[1]) * Math.RAD2DEG;
      // offsets are [right, up, forward]
      // values are based on what felt right after iterating
      vector offsets[] = {
        "0.11 0.17 0.0", // offset while aiming down
        "0.12 0.05 0.0", // offset while aiming forward
        "0.112 0.03 0.0" // offset while aiming up
      };
      const int lastIndex = 2; // length of offsets - 1
      // <0,1> range of aiming
      float a = Math.Clamp(Math.InverseLerp(DayZPlayerCamera1stPerson.CONST_UD_MIN, DayZPlayerCamera1stPerson.CONST_UD_MAX, udAngle), 0, 0.9999);
      int lo = a * lastIndex;
      int hi = Math.Clamp(lo + 1, 0, lastIndex);
      // remap to current lo-hi range
      float t = Math.Clamp(a * lastIndex - lo, 0, 1);
      vector offset = vector.Lerp(offsets[lo], offsets[hi], t);
      // offsets are [right, up forward]
      // additional offsets added to previous offsets per stance
      vector stanceOffsets[] = {
        "0 -0.015 0", // erect
        "0 0.03 0", // crouch
        "0 -0.04 0",// prone
      };
      // 2. pick from predefined offsets based on stance,
      // allows to even further approximate the alignment
      int stanceOffsetIndex = hms.m_iStanceIdx;
      if (stanceOffsetIndex >= DayZPlayerConstants.STANCEIDX_PRONE)
        stanceOffsetIndex -= DayZPlayerConstants.STANCEIDX_RAISED;
      stanceOffsetIndex -= DayZPlayerConstants.STANCEIDX_ERECT;
      offset += stanceOffsets[stanceOffsetIndex];
      // if any additional height offset is defined, apply it
      if (m_WeaponLiftCheckVerticalOffset != 0)
        offset[1] = offset[1] + m_WeaponLiftCheckVerticalOffset;
      // 3. use the offset as the start position.
      // it will not be perfect, but it should reflect
      // the actual weapon transform more accurately
      start = offset.Multiply4(resTM);
    }
    /*usti_hlavne_position = ModelToWorld(usti_hlavne_position);
      distance = vector.Distance(start,usti_hlavne_position);*/
    distance = m_WeaponLength + GetEffectiveAttachmentLength();
    vector weaponStart = start + (m_ShoulderDistance * direction);
    vector weaponEnd = weaponStart + (distance * direction);
    // Draw diagnostics: Script -> Weapon -> Weapon Lift
#ifdef DIAG_DEVELOPER
    if (DiagMenu.GetValue(DiagMenuIDs.WEAPON_LIFT_DEBUG))
    {
      vector diagNoAttachEnd = weaponStart + (m_WeaponLength * direction);
      int diagPtsShpFlgs = ShapeFlags.ONCE | ShapeFlags.NOOUTLINE;
      float diagPtsRadius = 0.025;
      Shape.CreateSphere(COLOR_GREEN, diagPtsShpFlgs, weaponStart, diagPtsRadius);
      Shape.CreateSphere(COLOR_YELLOW, diagPtsShpFlgs, diagNoAttachEnd, diagPtsRadius);
      Shape.CreateSphere(COLOR_BLUE, diagPtsShpFlgs, weaponEnd, diagPtsRadius);
    }
#endif
    // For the physical cast, extend the distance by x%
    // to allow for smoother transition handling in some cases
    end = weaponEnd + ((0.1 * distance) * direction);
    // Prepare raycast params and perform the cast in fire geo
    RaycastRVParams rayParm = new RaycastRVParams(start, end, player, 0.04);
    rayParm.flags = CollisionFlags.ALLOBJECTS;
    rayParm.type = ObjIntersect.Fire;
    DbgUI.BeginCleanupScope();
    array<ref RaycastRVResult> results = {};
    if (!DayZPhysics.RaycastRVProxy(rayParm, results) || results.Count() == 0)
    {
      hit_pos = vector.Zero;
      hit_fraction = 0;
    }
    else
    {
      RaycastRVResult res = results[0];
#ifdef DIAG_DEVELOPER // isect diag
      if (DiagMenu.GetValue(DiagMenuIDs.WEAPON_LIFT_DEBUG) == 2)
      {
        DbgUI.Begin("Weapon Lift Diag");
        {
          if (res.surface)
          {
            DbgUI.Text("Intersection data:");
            DbgUI.Text("  Name: " + res.surface.GetName());
            DbgUI.Text("  EntryName: " + res.surface.GetEntryName());
            DbgUI.Text("  SurfaceType: " + res.surface.GetSurfaceType());
            DbgUI.Text("  IsPassThrough: " + res.surface.IsPassthrough());
            DbgUI.Text("  IsSolid: " + res.surface.IsSolid());
          }
          else
            DbgUI.Text("Intersection with no surface");
        }
        DbgUI.End();
      }
#endif  // !isect diag
      if (LiftWeaponRaycastResultCheck(res))
      {
        hit_pos = res.pos;
        float len0 = (hit_pos - start).Length();
        float len1 = (end - start).Length();
        if (len0 <= 0 || len1 <= 0)
          hit_fraction = 1;
        else
          hit_fraction = len0 / len1;
      }
      else
      {
        hit_pos = vector.Zero;
        hit_fraction = 0;
      }
    }
    DbgUI.EndCleanupScope();
    // Draw diagnostics: Script -> Weapon -> Weapon Lift
#ifdef DIAG_DEVELOPER
    if (DiagMenu.GetValue(DiagMenuIDs.WEAPON_LIFT_DEBUG))
    {
      const vector epsilon = "0 0.0002 0"; // to overcome excessive z-fighting for diag
      if (lastLiftPosition != vector.Zero)
        Shape.CreateArrow(start - epsilon, lastLiftPosition - epsilon, 0.05, COLOR_YELLOW, ShapeFlags.ONCE);
      Shape.CreateArrow(start, weaponEnd, 0.05, COLOR_WHITE, ShapeFlags.ONCE | ShapeFlags.NOZBUFFER);
      if (hit_fraction != 0)
        Shape.CreateArrow(start + epsilon, hit_pos + epsilon, 0.05, COLOR_RED, ShapeFlags.ONCE);
    }
#endif
    // Start by assuming that we want to retain state
    bool wantsLift = wasLift;
    // Sq. distance of weapon movement required to trigger lift (in)
    const float inThreshold = 0.002;
    // Sq. distance of weapon movement required to trigger lift (out)
    const float outThreshold = 0.003;
    const float noIsctOutThreshold = 0.01;
    // Min angle in degrees change from last lift to stop lifting
    // Base threshold of 0.75 degrees + 0.6 degrees per meter of weapon length
    float angleThreshold = 0.75 + Math.Clamp(m_WeaponLength * 0.6, 0, 1.5);
    // Update state when a hit is registered
    if (hit_fraction != 0)
    {
      vector v1 = hit_pos - weaponEnd;
      vector v2 = hit_pos - end;
      float d = vector.Dot(v1, v2);
      // But leave some threshold where previous state is kept
      // to prevent excessive switches from occuring
      if (!wasLift && d > inThreshold)
        wantsLift = true;
      else if (wasLift && d < -outThreshold)
        wantsLift = false;
      m_LastLiftPosition = hit_pos;
    }
    else
    {
      // With no hit and no previous lift
      if (lastLiftPosition == vector.Zero)
      {
        wantsLift = false;
        m_LastLiftPosition = vector.Zero;
      }
      // See if previous hit wasn't very close to our current position,
      // in which case simply don't lift the weapon
      else
      {
        vector v3 = (lastLiftPosition - start).Normalized();
        vector v4 = (end - start).Normalized();
        float d2 = vector.Dot(v3, v4);
        // no isect, angle delta check
        if (Math.Acos(d2) > (angleThreshold * Math.DEG2RAD)) // if relative angle is > x degree, stop lifting
        {
          wantsLift = false;
          m_LastLiftPosition = vector.Zero;
        }
        // no isect, distance check
        else
        {
          float d3 = vector.Dot(lastLiftPosition - weaponEnd, (start - end).Normalized());
          if (d3 < -noIsctOutThreshold)
          {
            wantsLift = false;
            m_LastLiftPosition = vector.Zero;
          }
        }
      }
    }
    // lift is desired
    if (wantsLift)
    {
      //Print(distance);
      m_LiftWeapon = true;
      return true;
    }
    return false;
  }
References Math::Acos(), Math::Asin(), DbgUI::Begin(), DbgUI::BeginCleanupScope(), Math::Clamp(), COLOR_BLUE, COLOR_GREEN, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, Math::DEG2RAD, vector::Dot(), DbgUI::End(), DbgUI::EndCleanupScope(), GetGame(), DiagMenu::GetValue(), Math::InverseLerp(), vector::Lerp(), Math3D::MatrixMultiply3(), Print(), Math::RAD2DEG, DayZPhysics::RaycastRVProxy(), vector::RotateAroundZeroDeg(), Shape, DbgUI::Text(), vector::Up, Vector(), Math3D::YawPitchRollMatrix(), and vector::Zero.
LiftWeaponRaycastResultCheck()
bool Weapon::LiftWeaponRaycastResultCheck (notnull RaycastRVResult res) inline protected
Return whether provided material triggers weapon lift (true) or not (false).
Definition at line 1558 of file Weapon_Base.c.
  {
    return res.surface.IsSolid();
  }
LoadCurrentFSMState()
bool Weapon::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline protected
Definition at line 550 of file Weapon_Base.c.
  {
    if (m_fsm)
    {
      if (m_fsm.LoadCurrentFSMState(ctx, version))
      {
        WeaponStableState state = WeaponStableState.Cast(GetCurrentState());
        if (state)
        {
          SyncSelectionState(state.HasBullet(), state.HasMagazine());
          state.SyncAnimState();
          if (LogManager.IsWeaponLogEnable()) wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(this) + " Weapon=" + this + " stable state loaded and synced.");
          return true;
        }
        else
        {
          if (LogManager.IsWeaponLogEnable()) wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(this) + " Weapon=" + this + " unstable/error state loaded.");
          return false;
        }
      }
      else
      {
        Error("[wpnfsm] " + Object.GetDebugName(this) + " Weapon=" + this + " did not load.");
        return false;
      }
    }
    else
    {
      Error("[wpnfsm] " + Object.GetDebugName(this) + " Weapon.LoadCurrentFSMState: trying to load weapon without FSM (or uninitialized weapon) this=" + this + " type=" + GetType());
      return false;
    }
  }
References Error(), GetType(), LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
OnDebugSpawn()
override void Weapon::OnDebugSpawn () inline protected
Definition at line 1770 of file Weapon_Base.c.
  {
    SpawnAmmo("", SAMF_DEFAULT);
  }
OnFire()
void Weapon::OnFire (int muzzle_index) inline protected
Definition at line 967 of file Weapon_Base.c.
  {
    /*
        array<Man> players();
        GetGame().GetPlayers(players);
        Man root = GetHierarchyRootPlayer();
        if (!root)
        {
          return;
        }
        vector safePosition = root.GetPosition() + (root.GetDirection() * "0 1 0" * 3.0);
        Man other = null;
        foreach (auto player : players)
        {
          if (player != GetHierarchyRootPlayer())
          {
            player.SetPosition(safePosition);
          }
        }
    */
    m_BurstCount++;
  }
OnFireModeChange()
void Weapon::OnFireModeChange (int fireMode) inline protected
Definition at line 995 of file Weapon_Base.c.
  {
    if (!GetGame().IsDedicatedServer())
    {
      EffectSound eff;
      if (fireMode == 0)
        eff = SEffectManager.PlaySound("Fire_Mode_Switch_Marked_Click_SoundSet", GetPosition());
      else
        eff = SEffectManager.PlaySound("Fire_Mode_Switch_Simple_Click_SoundSet", GetPosition());
      eff.SetAutodestroy(true);
    }
    ResetBurstCount();
  }
References GetGame(), GetPosition, and SEffectManager::PlaySound().
OnInventoryEnter()
override void Weapon::OnInventoryEnter (Man player) inline protected
Definition at line 1018 of file Weapon_Base.c.
  {
    m_PropertyModifierObject = null;
    ValidateAndRepair();
    super.OnInventoryEnter(player);
  }
OnInventoryExit()
override void Weapon::OnInventoryExit (Man player) inline protected
Definition at line 1027 of file Weapon_Base.c.
  {
    m_PropertyModifierObject = null;
    super.OnInventoryExit(player);
  }
OnItemLocationChanged()
override void Weapon::OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline protected
Definition at line 1063 of file Weapon_Base.c.
  {
    super.OnItemLocationChanged(old_owner, new_owner);
    // "resets" optics memory on optics
    PlayerBase player;
    if (PlayerBase.CastTo(player, old_owner))
    {
      player.SetReturnToOptics(false);
      //optics item state reset
      ItemOptics optics;
      if (Class.CastTo(optics, GetAttachedOptics()))
        player.SwitchOptics(optics, false);
    }
    HideWeaponBarrel(false);
  }
References Class::CastTo().
OnStoreLoad()
override bool Weapon::OnStoreLoad (ParamsReadContext ctx, int version) inline protected
Definition at line 462 of file Weapon_Base.c.
  {
    if (!super.OnStoreLoad(ctx, version))
      return false;
    if (version >= 113)
    {
      int current_muzzle = 0;
      if (!ctx.Read(current_muzzle))
      {
        Error("Weapon.OnStoreLoad " + this + " cannot read current muzzle!");
        return false;
      }
      if (current_muzzle >= GetMuzzleCount() || current_muzzle < 0)
        Error("Weapon.OnStoreLoad " + this + " trying to set muzzle index " + current_muzzle + " while it only has " + GetMuzzleCount() + " muzzles!");
      else
        SetCurrentMuzzle(current_muzzle);
    }
    if (version >= 105)
    {
      int mode_count = 0;
      if (!ctx.Read(mode_count))
      {
        Error("Weapon.OnStoreLoad " + this + " cannot read mode count!");
        return false;
      }
      for (int m = 0; m < mode_count; ++m)
      {
        int mode = 0;
        if (!ctx.Read(mode))
        {
          Error("Weapon.OnStoreLoad " + this + " cannot read mode[" + m + "]");
          return false;
        }
        if (LogManager.IsWeaponLogEnable()) wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(this) + " OnStoreLoad - loaded muzzle[" + m + "].mode = " + mode);
        SetCurrentMode(m, mode);
      }
    }
    if (version >= 106)
    {
      if (!ctx.Read(m_isJammed))
      {
        Error("Weapon.OnStoreLoad cannot load jamming state");
        return false;
      }
    }
    if (m_fsm)
    {
      if (!m_fsm.OnStoreLoad(ctx, version))
        return false;
      WeaponStableState wss = WeaponStableState.Cast(m_fsm.GetCurrentState());
      if (wss)
        SetGroundAnimFrameIndex(wss.m_animState);
    }
    else
    {
      int dummy = 0;
      if (!ctx.Read(dummy))
        return false;
    }
    return true;
  }
References Error(), LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
OnStoreSave()
override void Weapon::OnStoreSave (ParamsWriteContext ctx) inline protected
Definition at line 595 of file Weapon_Base.c.
  {
    super.OnStoreSave(ctx);
    // current muzzle added in version 113
    int current_muzzle = GetCurrentMuzzle();
    ctx.Write(current_muzzle);
    // fire mode added in version 105
    int mode_count = GetMuzzleCount();
    ctx.Write(mode_count);
    for (int m = 0; m < mode_count; ++m)
      ctx.Write(GetCurrentMode(m));
    ctx.Write(m_isJammed);
    if (m_fsm)
      m_fsm.OnStoreSave(ctx);
    else
    {
      int dummy = 0;
      ctx.Write(dummy);
    }
  }
ProcessMeleeItemDamage()
override EntityAI Weapon::ProcessMeleeItemDamage (int mode = 0) inline protected
Definition at line 1700 of file Weapon_Base.c.
  {
    EntityAI attachment;
    switch (mode)
    {
    case 0:
      super.ProcessMeleeItemDamage();
      break;
    case 1:
      attachment = GetInventory().FindAttachment(m_ButtstockAttachmentIdx);
      break;
    case 2:
      attachment = GetInventory().FindAttachment(m_BayonetAttachmentIdx);
      break;
    default:
      super.ProcessMeleeItemDamage();
      break;
    }
    if (attachment)
    {
      attachment.ProcessMeleeItemDamage();
      return attachment;
    }
    return this;
  }
ProcessWeaponAbortEvent()
Weapon::ProcessWeaponAbortEvent (WeaponEventBase e) inline protected
@NOTE: warning: ProcessWeaponEvent can be called only within DayZPlayer::HandleWeapons (or CommandHandler)
Definition at line 294 of file Weapon_Base.c.
  {
    SyncEventToRemote(e);
    ProcessEventResult aa;
    m_fsm.ProcessAbortEvent(e, aa);
    return aa == ProcessEventResult.FSM_OK;
  }
ProcessWeaponEvent()
Weapon::ProcessWeaponEvent (WeaponEventBase e) inline protected
weapon's fsm handling of events @NOTE: warning: ProcessWeaponEvent can be called only within DayZPlayer::HandleWeapons (or CommandHandler)
Definition at line 274 of file Weapon_Base.c.
  {
    SyncEventToRemote(e);
    // @NOTE: synchronous events not handled by fsm
    if (e.GetEventID() == WeaponEventID.SET_NEXT_MUZZLE_MODE)
    {
      SetNextMuzzleMode(GetCurrentMuzzle());
      return true;
    }
    if (m_fsm.ProcessEvent(e) == ProcessEventResult.FSM_OK)
      return true;
    //if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("FSM refused to process event (no transition): src=" + GetCurrentState().ToString() + " event=" + e.ToString()); }
    return false;
  }
RandomizeFSMState()
Weapon::RandomizeFSMState () inline protected
With the parameters given, selects a random suitable state for the FSM of the weapon @WARNING: Weapon_Base.Synchronize call might be needed, if this method is called while clients are connected.
Definition at line 644 of file Weapon_Base.c.
  {
    if (m_fsm)
    {
      int mi = GetCurrentMuzzle();
      Magazine mag = GetMagazine(mi);
      bool has_mag = mag != null;
      bool has_bullet = !IsChamberEmpty(mi);
      bool has_jam = IsJammed();
      array<MuzzleState> muzzleStates = GetMuzzleStates();
      m_fsm.RandomizeFSMStateEx(muzzleStates, has_mag, has_jam);
      ForceSyncSelectionState();
    }
  }
References IsJammed().
ResetBurstCount()
void Weapon::ResetBurstCount () inline protected
Definition at line 1742 of file Weapon_Base.c.
  {
    m_BurstCount = 0;
  }
ResetWeaponAnimState()
void Weapon::ResetWeaponAnimState () inline protected
Definition at line 313 of file Weapon_Base.c.
  {
    if (LogManager.IsWeaponLogEnable()) fsmDebugSpam("[wpnfsm] " + Object.GetDebugName(this) + " resetting anim state: " + typename.EnumToString(PistolAnimState, m_weaponAnimState) + " --> " + typename.EnumToString(PistolAnimState, -1));
    m_weaponAnimState = -1;
  }
References fsmDebugSpam(), and LogManager::IsWeaponLogEnable().
SaveCurrentFSMState()
void Weapon::SaveCurrentFSMState (ParamsWriteContext ctx) inline protected
Definition at line 535 of file Weapon_Base.c.
  {
    if (m_fsm && m_fsm.IsRunning())
    {
      if (m_fsm.SaveCurrentFSMState(ctx))
      {
        if (LogManager.IsWeaponLogEnable()) wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(this) + " Weapon=" + this + " state saved.");
      }
      else
        Error("[wpnfsm] " + Object.GetDebugName(this) + " Weapon=" + this + " state NOT saved.");
    }
    else
      Error("[wpnfsm] " + Object.GetDebugName(this) + " Weapon.SaveCurrentFSMState: trying to save weapon without FSM (or uninitialized weapon) this=" + this + " type=" + GetType());
  }
References Error(), GetType(), LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
SetActions()
override void Weapon::SetActions () inline protected
Definition at line 1747 of file Weapon_Base.c.
  {
    super.SetActions();
    AddAction(FirearmActionUnjam);
    AddAction(FirearmActionAttachMagazine);
    AddAction(FirearmActionLoadBullet);
    AddAction(FirearmActionMechanicManipulate);
    AddAction(ActionTurnOnWeaponFlashlight);
    AddAction(ActionTurnOffWeaponFlashlight);
    AddAction(FirearmActionAttachMagazineQuick); // Easy reload
    AddAction(FirearmActionLoadBulletQuick); // Easy reload
  }
References AddAction(), and FirearmActionLoadBulletQuick().
SetBayonetAttached()
override void Weapon::SetBayonetAttached (bool pState, int slot_idx = -1) inline protected
attachment helpers (firearm melee)
Definition at line 1642 of file Weapon_Base.c.
  {
    m_BayonetAttached = pState;
    m_BayonetAttachmentIdx = slot_idx;
  }
SetButtstockAttached()
override void Weapon::SetButtstockAttached (bool pState, int slot_idx = -1) inline protected
Definition at line 1658 of file Weapon_Base.c.
  {
    m_ButtstockAttached = pState;
    m_ButtstockAttachmentIdx = slot_idx;
  }
SetCharged()
void Weapon::SetCharged (bool value) inline protected
Definition at line 137 of file Weapon_Base.c.
  {
    m_Charged = value;
  }
SetInitialState()
void Weapon::SetInitialState (WeaponStableState initState) inline protected
Definition at line 124 of file Weapon_Base.c.
  {
    m_fsm.SetInitialState(initState);
    SetCharged(!initState.IsDischarged());
    SetWeaponOpen(!initState.IsWeaponOpen());
    SetGroundAnimFrameIndex(initState.m_animState);
  }
SetJammed()
void Weapon::SetJammed (bool value) inline protected
Definition at line 384 of file Weapon_Base.c.
{ m_isJammed = value; }
SetSyncJammingChance()
void Weapon::SetSyncJammingChance (float jamming_chance) inline protected
Definition at line 1581 of file Weapon_Base.c.
  {
    m_ChanceToJamSync = jamming_chance;
  }
SetWeaponAnimState()
void Weapon::SetWeaponAnimState (int state) inline protected
Definition at line 308 of file Weapon_Base.c.
  {
    m_weaponAnimState = state;
    SetGroundAnimFrameIndex(state);
  }
SetWeaponOpen()
void Weapon::SetWeaponOpen (bool value) inline protected
Definition at line 147 of file Weapon_Base.c.
  {
    m_WeaponOpen = value;
  }
ShowBullet()
void Weapon::ShowBullet (int muzzleIndex) inline protected
Definition at line 366 of file Weapon_Base.c.
  {
    if (m_bulletSelectionIndex.Count() > muzzleIndex)
      SetSimpleHiddenSelectionState(m_bulletSelectionIndex[muzzleIndex], 1);
    else
      SelectionBulletShow();
  }
ShowMagazine()
void Weapon::ShowMagazine () inline protected
Definition at line 1684 of file Weapon_Base.c.
  {
    if (m_magazineSimpleSelectionIndex > -1)
      SetSimpleHiddenSelectionState(m_magazineSimpleSelectionIndex, 1);
    else
      SelectionMagazineShow();
  }
SpawnAmmo()
Weapon::SpawnAmmo (string magazineType = "", int flags = WeaponWithAmmoFlags.CHAMBER) inline protected
General method trying to attch magazine, fill inner magazine and fill chamber.
Parameters
[in] magazineType string The magazine to attach or ammo to load, passing in empty string will select random
[in] flags int Setup flags, please read WeaponWithAmmoFlags
Returns
whether anything was spawned or done
Definition at line 717 of file Weapon_Base.c.
  {
    // Attempt internal mag
    if (HasInternalMagazine(-1) && FillInnerMagazine(magazineType, flags))
      return true;
    // Attempt mag attachment
    if (GetMagazineTypeCount(0) > 0 && SpawnAttachedMagazine(magazineType, flags))
      return true;
    // Attempt chamber
    if (FillChamber(magazineType, flags))
      return true;
    return false;
  }
SpawnAttachedMagazine()
Weapon::SpawnAttachedMagazine (string magazineType = "", int flags = WeaponWithAmmoFlags.CHAMBER) inline protected
Try to spawn and attach a magazine.
Parameters
[in] magazineType string The magazine to attach, passing in empty string will select random
[in] flags int Setup flags, please read WeaponWithAmmoFlags
Returns
The created magazine or null
Definition at line 740 of file Weapon_Base.c.
  {
    // Check if the gun has any magazines registered in config
    if (GetMagazineTypeCount(0) == 0)
    {
      ErrorEx(string.Format("No 'magazines' config entry for %1.", this));
      return null;
    }
    // Randomize when no specific one is given
    if (magazineType == "")
    {
      if (flags & WeaponWithAmmoFlags.MAX_CAPACITY_MAG)
        magazineType = GetMaxMagazineTypeName(0);
      else
        magazineType = GetRandomMagazineTypeName(0);
    }
    EntityAI magAI = GetInventory().CreateAttachment(magazineType);
    if (!magAI)
    {
      ErrorEx(string.Format("Failed to create and attach %1 to %2", GetDebugName(magAI), this));
      return null;
    }
    Magazine mag;
    if (!CastTo(mag, magAI))
    {
      ErrorEx(string.Format("Expected magazine, created: %1", GetDebugName(magAI)));
      return null;
    }
    // Decide random quantity when enabled
    if (flags & WeaponWithAmmoFlags.QUANTITY_RNG)
      mag.ServerSetAmmoCount(Math.RandomIntInclusive(0, mag.GetAmmoMax()));
    // Fill chamber when flagged
    bool chamberRng = (flags & WeaponWithAmmoFlags.CHAMBER_RNG);
    bool chamber = (flags & WeaponWithAmmoFlags.CHAMBER) || chamberRng;
    if (chamber || chamberRng)
      FillChamber(magazineType, flags);
    // FSM cares about magazine state
    RandomizeFSMState();
    Synchronize();
    return mag;
  }
References ErrorEx, GetDebugName(), Math::RandomIntInclusive(), and Synchronize().
SpawnRecoilObject()
RecoilBase Weapon::SpawnRecoilObject () inline protected
Definition at line 1143 of file Weapon_Base.c.
  {
    return new DefaultRecoil(this);
  }
SyncEventToRemote()
void Weapon::SyncEventToRemote (WeaponEventBase e) inline protected
Definition at line 1125 of file Weapon_Base.c.
  {
    DayZPlayer p = DayZPlayer.Cast(GetHierarchyParent());
    if (p && p.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
    {
      ScriptRemoteInputUserData ctx = new ScriptRemoteInputUserData();
      ctx.Write(INPUT_UDT_WEAPON_REMOTE_EVENT);
      e.WriteToContext(ctx);
      if (LogManager.IsWeaponLogEnable())
        wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(this) + " send 2 remote: sending e=" + e + " id=" + e.GetEventID() + " p=" + e.m_player + "  m=" + e.m_magazine);
      p.StoreInputForRemotes(ctx);
    }
  }
References INPUT_UDT_WEAPON_REMOTE_EVENT, LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
SyncSelectionState()
void Weapon::SyncSelectionState (bool has_bullet, bool has_mag) inline protected
Definition at line 396 of file Weapon_Base.c.
  {
    if (has_bullet)
    {
      string chamberedAmmoTypeName;
      float chamberedAmmoDmg;
      if (GetCartridgeInfo(0, chamberedAmmoDmg, chamberedAmmoTypeName))
        EffectBulletShow(0, chamberedAmmoDmg, chamberedAmmoTypeName);
      //ShowBullet(0);
      SelectionBulletShow();
    }
    else
    {
      //HideBullet(0);
      SelectionBulletHide();
      EffectBulletHide(0);
    }
    if (has_mag)
      ShowMagazine();
    else
      HideMagazine();
  }
ValidateAndRepair()
void Weapon::ValidateAndRepair () inline protected
Definition at line 1012 of file Weapon_Base.c.
  {
    if (m_fsm)
      m_fsm.ValidateAndRepair();
  }
Weapon_Base()
void Weapon::Weapon_Base () inline protected
Definition at line 72 of file Weapon_Base.c.
  {
    //m_DmgPerShot    = ConfigGetFloat("damagePerShot");
    m_BayonetAttached = false;
    m_ButtstockAttached = false;
    m_BayonetAttachmentIdx = -1;
    m_ButtstockAttachmentIdx = -1;
    m_BurstCount = 0;
    m_DOFProperties = new array<float>;
    if (ConfigIsExisting("simpleHiddenSelections"))
    {
      TStringArray selectionNames = new TStringArray;
      ConfigGetTextArray("simpleHiddenSelections", selectionNames);
      m_weaponHideBarrelIdx = selectionNames.Find("hide_barrel");
      m_magazineSimpleSelectionIndex = selectionNames.Find("magazine");
      int bulletIndex = selectionNames.Find("bullet");
      if (bulletIndex != -1)
      {
        m_bulletSelectionIndex.Insert(bulletIndex);
        for (int i = 2; i < 100; i++)
        {
          bulletIndex = selectionNames.Find(string.Format("bullet%1", i));
          if (bulletIndex != -1)
            m_bulletSelectionIndex.Insert(bulletIndex);
          else
            break;
        }
      }
    }
    InitWeaponLength();
    InitWeaponLiftCheckVerticalOffset();
    InitShoulderDistance();
    InitDOFProperties(m_DOFProperties);
    if (GetGame().IsServer())
      InitReliability(m_ChanceToJam);
    InitStateMachine();
  }
References GetGame(), and Weapon_Base::InitStateMachine().
Member Data Documentation
DEFAULT_DAMAGE_ON_SHOT
const float Weapon::DEFAULT_DAMAGE_ON_SHOT = 0.05 protected
Definition at line 45 of file Weapon_Base.c.
hit_mask
PhxInteractionLayers Weapon::hit_mask = PhxInteractionLayers.CHARACTER | PhxInteractionLayers.BUILDING | PhxInteractionLayers.DOOR | PhxInteractionLayers.VEHICLE | PhxInteractionLayers.ROADWAY | PhxInteractionLayers.TERRAIN | PhxInteractionLayers.ITEM_SMALL | PhxInteractionLayers.ITEM_LARGE | PhxInteractionLayers.FENCE | PhxInteractionLayers.AI protected
Definition at line 70 of file Weapon_Base.c.
m_abilities
ref array<ref AbilityRecord> Weapon::m_abilities = new array<ref AbilityRecord> protected
Definition at line 46 of file Weapon_Base.c.
m_BayonetAttached
bool Weapon::m_BayonetAttached protected
Definition at line 50 of file Weapon_Base.c.
m_BayonetAttachmentIdx
int Weapon::m_BayonetAttachmentIdx protected
Definition at line 55 of file Weapon_Base.c.
m_bulletSelectionIndex
ref array<int> Weapon::m_bulletSelectionIndex = new array<int> protected
Definition at line 65 of file Weapon_Base.c.
m_BurstCount
int Weapon::m_BurstCount protected
Definition at line 54 of file Weapon_Base.c.
m_ButtstockAttached
bool Weapon::m_ButtstockAttached protected
Definition at line 51 of file Weapon_Base.c.
m_ButtstockAttachmentIdx
int Weapon::m_ButtstockAttachmentIdx protected
Definition at line 56 of file Weapon_Base.c.
m_ChanceToJam
ref array<float> Weapon::m_ChanceToJam = new array<float> protected
Definition at line 67 of file Weapon_Base.c.
m_ChanceToJamSync
float Weapon::m_ChanceToJamSync = 0 protected
Definition at line 68 of file Weapon_Base.c.
m_Charged
bool Weapon::m_Charged = false protected
Definition at line 52 of file Weapon_Base.c.
m_DmgPerShot
float Weapon::m_DmgPerShot = 0 protected
Definition at line 60 of file Weapon_Base.c.
m_DOFProperties
ref array<float> Weapon::m_DOFProperties protected
Definition at line 66 of file Weapon_Base.c.
m_fsm
ref WeaponFSM Weapon::m_fsm protected
weapon abilities
Definition at line 47 of file Weapon_Base.c.
m_isJammed
bool Weapon::m_isJammed = false protected
weapon state machine
Definition at line 48 of file Weapon_Base.c.
m_LastLiftPosition
vector Weapon::m_LastLiftPosition protected
Definition at line 64 of file Weapon_Base.c.
m_LiftWeapon
bool Weapon::m_LiftWeapon = false protected
Definition at line 49 of file Weapon_Base.c.
m_magazineSimpleSelectionIndex
int Weapon::m_magazineSimpleSelectionIndex = -1 protected
animation state the weapon is in, -1 == uninitialized
Definition at line 58 of file Weapon_Base.c.
m_PropertyModifierObject
ref PropertyModifiers Weapon::m_PropertyModifierObject protected
Definition at line 69 of file Weapon_Base.c.
m_ShoulderDistance
float Weapon::m_ShoulderDistance protected
Definition at line 63 of file Weapon_Base.c.
m_weaponAnimState
int Weapon::m_weaponAnimState = -1 protected
Definition at line 57 of file Weapon_Base.c.
m_weaponHideBarrelIdx
int Weapon::m_weaponHideBarrelIdx = -1 protected
Definition at line 59 of file Weapon_Base.c.
m_WeaponLength
float Weapon::m_WeaponLength protected
Definition at line 61 of file Weapon_Base.c.
m_WeaponLiftCheckVerticalOffset
float Weapon::m_WeaponLiftCheckVerticalOffset protected
Definition at line 62 of file Weapon_Base.c.
m_WeaponOpen
bool Weapon::m_WeaponOpen = false protected
Definition at line 53 of file Weapon_Base.c.
SAMF_DEFAULT
const int Weapon::SAMF_DEFAULT = WeaponWithAmmoFlags.CHAMBER | WeaponWithAmmoFlags.MAX_CAPACITY_MAG private
Full highest capacity magazine + chambered round.
Definition at line 41 of file Weapon_Base.c.
SAMF_RNG
const int Weapon::SAMF_RNG = WeaponWithAmmoFlags.CHAMBER_RNG | WeaponWithAmmoFlags.QUANTITY_RNG private
Random bullet quantity + maybe chambered round.
Definition at line 43 of file Weapon_Base.c.
The documentation for this class was generated from the following files:
scripts/4_World/Entities/Core/Inherited/InventoryItem.c
scripts/4_World/Entities/Firearms/Weapon_Base.c
scripts/4_World/Entities/ItemBase/BinocularsBase.c