DayZ: scripts/4_World/Classes/ContaminatedArea/SpookyAreaMisc.c File Reference
SpookyAreaMisc.c File Reference
Classes
class SpookyEventWind
class SpookyEventSteps
class SpookyEventBase
class SpookyPlayerStalker
this entity gets attached to each player while present in the spooky area
Functions
SpookyEventWind SpookyEventBase Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
bool CanDo (PlayerBase player, TStringVectorMap surfaceTypes)
void Do (PlayerBase player)
void SpookyTriggerEventsHandler (notnull PlayerBase player)
void ~SpookyTriggerEventsHandler ()
void RegisterEvents ()
void Update (float deltaTime)
void GatherSurfaces (notnull TStringVectorMap gatheredGurfaces)
bool SelectEvent ()
Variables
class SpookyEventBase m_SoundEvents
PlayerBase m_Player
float m_TimeAccu
const float CONSECUTIVE_EVENTS_COOLDOWN = 20
const float EVENT_CHECK_FREQUENCY = 2
const float FIRST_EVENT_CHECK_DELAY = 15
const float SURFACE_CHECK_POINT_DISTANCE = 2
float m_NextEventCheck = FIRST_EVENT_CHECK_DELAY
Function Documentation
CanDo()
bool CanDo (PlayerBase player, TStringVectorMap surfaceTypes) protected
Definition at line 30 of file SpookyAreaMisc.c.
  {
    //put additional code here
  }
Do()
void Do (PlayerBase player) protected
Definition at line 35 of file SpookyAreaMisc.c.
                       : SpookyEventBase
{
  override protected void Init()
GatherSurfaces()
void GatherSurfaces (notnull TStringVectorMap gatheredGurfaces) protected
Definition at line 242 of file SpookyAreaMisc.c.
  {
    gatheredGurfaces.Clear();
    vector playerPos = m_Player.GetPosition();
    TVectorArray positions = new TVectorArray();
    positions.Insert(playerPos);
    positions.Insert(playerPos + ("0 0 1" * SURFACE_CHECK_POINT_DISTANCE));
    positions.Insert(playerPos + ("0 0 -1" * SURFACE_CHECK_POINT_DISTANCE));
    positions.Insert(playerPos + ("1 0 0" * SURFACE_CHECK_POINT_DISTANCE));
    positions.Insert(playerPos + ("-1 0 0" * SURFACE_CHECK_POINT_DISTANCE));
    foreach (vector pos : positions)
    {
      string surfaceType;
      GetGame().SurfaceGetType3D(pos[0], pos[1], pos[2], surfaceType);
      if (!gatheredGurfaces.Contains(surfaceType))
        gatheredGurfaces.Insert(surfaceType, pos);
    }
#ifdef DIAG_DEVELOPER
    if (DiagMenu.GetBool(DiagMenuIDs.TRIGGER_DEBUG))
    {
      foreach (vector p: positions)
        Debug.DrawLine(p, p + "0 10 0", COLOR_BLUE, ShapeFlags.NOZBUFFER);
    }
#endif
  }
References COLOR_BLUE, Debug::DrawLine(), DiagMenu::GetBool(), GetGame(), m_Player, and SURFACE_CHECK_POINT_DISTANCE.
Referenced by SelectEvent().
Init()
SpookyEventWind SpookyEventBase Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
Definition at line 1 of file SpookyAreaMisc.c.
  {
    SetCoolDown(80);
    m_SoundSet = "SpookyArea_Whispering_SoundSet";
  }
RegisterEvents()
void RegisterEvents () protected
Definition at line 220 of file SpookyAreaMisc.c.
  {
    m_SoundEvents.Insert(new SpookyEventWind());
    m_SoundEvents.Insert(new SpookyEventWhisper());
    m_SoundEvents.Insert(new SpookyEventSteps());
    m_SoundEvents.Insert(new SpookyEventRustle());
  }
References m_SoundEvents.
Referenced by SpookyTriggerEventsHandler().
SelectEvent()
bool SelectEvent () protected
Definition at line 274 of file SpookyAreaMisc.c.
  {
    TStringVectorMap gatheredSurfaces = new TStringVectorMap();
    GatherSurfaces(gatheredSurfaces);//this can be optimized by calling this on demand from an event, as none events might be eligible at this point, so we might be doing this in vain
#ifdef DIAG_DEVELOPER
    if (DiagMenu.GetBool(DiagMenuIDs.TRIGGER_DEBUG))
    {
      for (int i = 0; i < gatheredSurfaces.Count(); i++)
      {
        Print(gatheredSurfaces.GetKey(i));
        Print(gatheredSurfaces.Get(gatheredSurfaces.GetKey(i)));
      }
      Print("--------------------------------------------------------------------");
    }
#endif
    array<ref SpookyEventBase> validEvents = new array<ref SpookyEventBase>();
    float currentTime = GetGame().GetTime();
    foreach (SpookyEventBase spookyEvent: m_SoundEvents)
    {
      if (spookyEvent.CanPerform(m_Player, currentTime, gatheredSurfaces))
        validEvents.Insert(spookyEvent);
    }
    //validEvents.Debug();
    SpookyEventBase selectedEvent;
    if (validEvents.Count() > 0)
    {
      int randIndex = Math.RandomIntInclusive(0, validEvents.Count() - 1);
      selectedEvent = validEvents[randIndex];
    }
    if (selectedEvent)
    {
      selectedEvent.Perform(m_Player, currentTime, gatheredSurfaces);
      return true;
    }
    return false;
  }
References GatherSurfaces(), DiagMenu::GetBool(), GetGame(), m_Player, m_SoundEvents, Print(), and Math::RandomIntInclusive().
Referenced by Update().
SpookyTriggerEventsHandler()
void SpookyTriggerEventsHandler (notnull PlayerBase player) protected
Definition at line 204 of file SpookyAreaMisc.c.
  {
    if (!m_SoundEvents)
    {
      m_SoundEvents = new array<ref SpookyEventBase>();
      RegisterEvents();
    }
    m_Player = player;
  }
References m_Player, m_SoundEvents, and RegisterEvents().
Referenced by OnEnterClientEvent().
Update()
void Update (float deltaTime) protected
Definition at line 229 of file SpookyAreaMisc.c.
  {
    m_TimeAccu += deltaTime;
    if (m_TimeAccu > m_NextEventCheck)
    {
      if (SelectEvent())
        m_NextEventCheck = CONSECUTIVE_EVENTS_COOLDOWN;
      else
        m_NextEventCheck = EVENT_CHECK_FREQUENCY;
      m_TimeAccu = 0;
    }
  }
References CONSECUTIVE_EVENTS_COOLDOWN, EVENT_CHECK_FREQUENCY, m_NextEventCheck, m_TimeAccu, and SelectEvent().
~SpookyTriggerEventsHandler()
void ~SpookyTriggerEventsHandler () protected
Definition at line 215 of file SpookyAreaMisc.c.
  {
    m_SoundEvents = null;
  }
References m_SoundEvents.
Variable Documentation
CONSECUTIVE_EVENTS_COOLDOWN
const float CONSECUTIVE_EVENTS_COOLDOWN = 20 protected
Definition at line 198 of file SpookyAreaMisc.c.
Referenced by Update().
EVENT_CHECK_FREQUENCY
const float EVENT_CHECK_FREQUENCY = 2 protected
Definition at line 199 of file SpookyAreaMisc.c.
Referenced by Update().
FIRST_EVENT_CHECK_DELAY
const float FIRST_EVENT_CHECK_DELAY = 15 protected
Definition at line 200 of file SpookyAreaMisc.c.
m_NextEventCheck
float m_NextEventCheck = FIRST_EVENT_CHECK_DELAY protected
Definition at line 202 of file SpookyAreaMisc.c.
Referenced by Update().
m_Player
PlayerBase m_Player protected
Definition at line 196 of file SpookyAreaMisc.c.
m_SoundEvents
class SpookyEventBase m_SoundEvents protected
Referenced by RegisterEvents(), SelectEvent(), SpookyTriggerEventsHandler(), and ~SpookyTriggerEventsHandler().
m_TimeAccu
float m_TimeAccu protected
Definition at line 197 of file SpookyAreaMisc.c.
Referenced by Update().
SURFACE_CHECK_POINT_DISTANCE
const float SURFACE_CHECK_POINT_DISTANCE = 2 protected
Definition at line 201 of file SpookyAreaMisc.c.
Referenced by GatherSurfaces().