DayZ: HumanInventory Class Reference
HumanInventory Class Reference
inventory for plain man/human
Protected Member Functions
bool ReplaceItemInElsewhereWithNewinHandsImpl (InventoryMode mode, HandEventBase e)
bool ReplaceItemInHandsWithNewImpl (InventoryMode mode, HandEventBase e)
bool ReplaceItemInHandsWithNew (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
bool ReplaceItemInHandsWithNewElsewhere (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
bool SwappingToPreviousLocation (EntityAI item1, EntityAI item2, out InventoryLocation dst)
void HandleInventoryManipulation ()
void Update (float delta_time)
bool ValidateUserReservationCancel (inout Serializer ctx, InventoryValidation validation)
Private Member Functions
proto native EntityAI GetEntityInHands ()
proto native bool CanAddEntityInHands (EntityAI e)
alternative for TestAddEntityInHands(e, true, true, true);
proto native bool TestAddEntityInHands (EntityAI e, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check)
proto native bool CanRemoveEntityInHands ()
proto native bool CanOpenInventory ()
proto native EntityAI CreateInHands (string typeName)
creates new entity in hands
proto native int GetUserReservedLocationCount ()
proto native int FindUserReservedLocationIndex (notnull EntityAI e)
proto native int FindCollidingUserReservedLocationIndex (notnull EntityAI e, notnull InventoryLocation dst)
proto native void GetUserReservedLocation (int index, out notnull InventoryLocation dst)
proto native int FindFirstUserReservedLocationIndexForContainer (notnull EntityAI e)
proto native void SetUserReservedLocation (notnull EntityAI eai, notnull InventoryLocation dst)
proto native void ClearUserReservedLocation (notnull EntityAI eai)
proto native bool ClearUserReservedLocationAtIndex (int index)
proto native void ClearUserReservedLocationForContainer (notnull EntityAI eai)
proto native bool GetDebugFlag ()
override EntityAI CreateInInventory (string type)
creates entity somewhere in inventory
void ClearUserReservedLocationSynced (notnull EntityAI eai)
void ClearUserReservedLocationAtIndexSynced (int index)
Man GetManOwner ()
bool HasEntityInHands (EntityAI e)
bool ProcessHandEvent (HandEventBase e)
void OnHandsStateChanged (HandStateBase src, HandStateBase dst)
void OnHandsExitedStableState (HandStateBase src, HandStateBase dst)
void OnHandsEnteredStableState (HandStateBase src, HandStateBase dst)
void OnEntityInHandsCreated (InventoryLocation src)
void OnEntityInHandsDestroyed (InventoryLocation src)
bool HandEvent (InventoryMode mode, HandEventBase e)
override bool DropEntity (InventoryMode mode, EntityAI owner, notnull EntityAI item)
bool ThrowEntity (EntityAI item, vector dir, float force)
bool RedirectToHandEvent (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
override bool TakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
override bool TakeEntityToInventory (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item)
override bool TakeEntityToCargoEx (InventoryMode mode, notnull EntityAI item, int idx, int row, int col)
Put item into into cargo on specific cargo location.
override bool TakeEntityAsAttachmentEx (InventoryMode mode, notnull EntityAI item, int slot)
override bool SwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2)
override bool ForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
override bool LocalDestroyEntity (notnull EntityAI item)
override bool ReplaceItemWithNew (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
bool ReplaceItemElsewhereWithNewInHands (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
Private Member Functions inherited from GameInventory
proto native bool GetCurrentInventoryLocation (out notnull InventoryLocation loc)
returns information about current item location
proto native bool FindFreeLocationFor (notnull EntityAI item, FindInventoryLocationType flags, out notnull InventoryLocation loc)
FindFreeLocationFor.
proto native bool FindFreeLocationForEx (notnull EntityAI item, FindInventoryLocationType flags, notnull InventoryLocation exclude, out notnull InventoryLocation loc)
FindFreeLocationForEx.
proto native bool FindFirstFreeLocationForNewEntity (string item_type, FindInventoryLocationType flags, out notnull InventoryLocation loc)
FindFirstFreeLocationForNewEntity.
proto native int FindFreeLocationsFor (notnull EntityAI item, FindInventoryLocationType flags, out notnull array< ref InventoryLocation > locs)
searches inventory for suitable location for @item
bool IsInCargo ()
Returns true if this Inventory owner is in cargo of something.
bool IsAttachment ()
Returns true if this Inventory owner is an attachment of something.
bool IsCargoInHiearchy ()
Returns true if inventory owner or his hiearchy parents are in cargo.
bool GetCurrentAttachmentSlotInfo (out int slot_id, out string slot_name)
Returns true if the item is currently attached and outputs attachment slot id and name.
proto native bool CanAddSwappedEntity (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2)
void OnInventoryFailure (InventoryCommandType type, InventoryValidationReason reason, InventoryLocation src, InventoryLocation dst)
bool TakeEntityToInventory (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item)
Put item anywhere into this entity (as attachment or into cargo, recursively)
bool TakeEntityToTargetInventory (InventoryMode mode, notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
helper that finds location first, then moves the entity into it
bool TakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
move src to dst
bool TakeEntityToCargo (InventoryMode mode, notnull EntityAI item)
moves item to cargo of this intentory
bool TakeEntityToTargetCargo (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
Put item into into cargo of another entity.
bool TakeEntityToCargoEx (InventoryMode mode, notnull EntityAI item, int idx, int row, int col)
moves item on specific cargo location
bool TakeEntityToTargetCargoEx (InventoryMode mode, notnull CargoBase cargo, notnull EntityAI item, int row, int col)
Put item into into cargo on specific cargo location of another entity.
bool TakeEntityAsAttachmentEx (InventoryMode mode, notnull EntityAI item, int slot)
bool TakeEntityAsTargetAttachmentEx (InventoryMode mode, notnull EntityAI target, notnull EntityAI item, int slot)
put item as attachment of target
bool TakeEntityAsAttachment (InventoryMode mode, notnull EntityAI item)
bool TakeEntityAsTargetAttachment (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
bool SwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2)
bool ForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
bool DropEntity (InventoryMode mode, EntityAI owner, notnull EntityAI item)
bool DropEntityWithTransform (InventoryMode mode, EntityAI owner, notnull EntityAI item, vector transform[4])
bool DropEntityInBounds (InventoryMode mode, EntityAI owner, notnull EntityAI item, vector halfExtents, float angle, float cosAngle, float sinAngle)
bool LocalDestroyEntity (notnull EntityAI item)
bool ReplaceItemWithNew (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
proto native bool GetFlipCargo ()
proto native void SetFlipCargo (bool flip)
proto native void FlipCargo ()
proto native void ResetFlipCargo ()
proto native EntityAI GetInventoryOwner ()
Engine native functions.
proto native bool HasEntityInInventory (notnull EntityAI item)
query inventory if item is somewhere
proto native bool EnumerateInventory (InventoryTraversalType tt, out array< EntityAI > items)
enumerate inventory using traversal type and filling items array
proto native int CountInventory ()
almost identical to EnumerateInventory except it does not return items
proto native CargoBase GetCargo ()
cargo
proto native CargoBase GetCargoFromIndex (int index)
proto native EntityAI CreateEntityInCargo (string typeName)
Create Entity of specified type in cargo of entity.
proto native EntityAI CreateEntityInCargoEx (string typeName, int idx, int row, int col, bool flip)
Create Entity of specified type in cargo of entity at coordinates (row, col)
proto native bool HasEntityInCargo (notnull EntityAI e)
proto native bool HasEntityInCargoEx (notnull EntityAI e, int idx, int row, int col)
proto native bool CanAddEntityInCargo (notnull EntityAI e, bool flip)
proto native bool CanAddEntityInCargoEx (notnull EntityAI e, int idx, int row, int col, bool flip)
proto native bool CanAddEntityInCargoExLoc (InventoryLocation loc)
proto native bool TestAddEntityInCargoEx (notnull EntityAI e, int idx, int row, int col, bool flip, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check, bool do_script_load_check)
proto native bool TestAddEntityInCargoExLoc (notnull InventoryLocation loc, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check, bool do_script_load_check)
proto native bool CanRemoveEntityInCargo (notnull EntityAI e)
proto native bool CanRemoveEntityInCargoEx (notnull EntityAI e, int idx, int row, int col)
proto native int GetSlotId (int index)
attachments
proto native int GetSlotIdCount ()
proto native int GetAttachmentSlotId (int index)
proto native int GetAttachmentSlotsCount ()
bool HasAttachmentSlot (int slotId)
proto native bool HasInventorySlot (int slotId)
proto native int AttachmentCount ()
Returns count of attachments attached to this item.
proto native EntityAI CreateAttachment (string typeName)
Create Entity of specified type as attachment of entity.
proto native EntityAI CreateAttachmentEx (string typeName, int slotId)
Create Entity of specified type as attachment of entity.
proto native EntityAI GetAttachmentFromIndex (int index)
proto native EntityAI FindAttachment (int slot)
Returns attached entity in slot (you can use InventorySlots.GetSlotIdFromString(name) to get slot id)
proto native EntityAI FindAttachmentByName (string slotName)
Returns attached entity in slot (you can use EntityAI.GetActionComponentName to get slot id)
proto native bool HasAttachment (notnull EntityAI e)
brief Returns True if entity is attached to this
proto native bool HasAttachmentEx (notnull EntityAI e, int slot)
brief Returns True if entity is attached to this in slot
proto native bool CanAddAttachment (notnull EntityAI e)
Check if attachment can be added to any slot.
proto native bool CanAddAttachmentEx (notnull EntityAI e, int slot)
Check if attachment can be added to slot @NOTE: Note that slot index IS NOT slot ID! Slot ID is defined in DZ/data/config.cpp.
proto native bool CanRemoveAttachment (EntityAI attachment)
proto native bool CanRemoveAttachmentEx (EntityAI attachment, int slot)
proto native EntityAI FindPlaceholderForSlot (int slot)
Returns placeholder entity for slot (naked arms, legs etc)
proto native bool IsPlaceholderEntity (notnull Object e)
proto native bool CanLockInventoryWithKey (notnull EntityAI key)
locks
proto native bool CanUnlockInventoryWithKey (notnull EntityAI key)
proto native void LockInventoryWithKey (notnull EntityAI key)
proto native void UnlockInventoryWithKey (notnull EntityAI key)
proto native bool HasKeys ()
proto native void LockInventory (int lockType)
proto native void UnlockInventory (int lockType)
proto native int GetScriptLockCount ()
proto native bool IsInventoryUnlocked ()
proto native bool IsInventoryLocked ()
proto native bool IsInventoryLockedForLockType (int lockType)
proto native bool SetSlotLock (int slot, bool locked)
proto native bool GetSlotLock (int slot)
void Init ()
script functions
bool OnStoreLoad (ParamsReadContext ctx, int version)
db load hooks
void OnAfterStoreLoad ()
void OnStoreSave (ParamsWriteContext ctx)
db store hook
void EEInit ()
void EEDelete (EntityAI parent)
EntityAI CreateInInventory (string type)
creates entity somewhere in inventory
bool CanAddEntityToInventory (notnull EntityAI item, int flag=FindInventoryLocationType.ANY)
ask inventory if item could be placed somewhere in inventory
bool AddEntityToInventory (notnull EntityAI item)
add entity somewhere in inventory
bool CanRemoveEntity ()
Returns if entity can be removed from its current location.
bool CanAddEntityInto (notnull EntityAI item, FindInventoryLocationType flags=FindInventoryLocationType.ANY)
Asks inventory if item could be placed in inventory, hands, etc.
bool CanAddEntityIntoInventory (notnull EntityAI item)
Test if entity can be put to the inventory (Cargo, ProxyCargo, Attachment)
bool CanAddEntityIntoHands (notnull EntityAI item)
Test if entity can be put into hands.
bool OnInputUserDataProcess (ParamsReadContext ctx)
synchronization
bool OnInventoryJunctureFromServer (ParamsReadContext ctx)
bool OnInventoryJunctureRepairFromServer (ParamsReadContext ctx)
void OnInventoryJunctureFailureFromServer (ParamsReadContext ctx)
void OnServerInventoryCommand (ParamsReadContext ctx)
bool AddInventoryReservationEx (EntityAI item, InventoryLocation dst, int timeout_ms)
bool ExtendInventoryReservationEx (EntityAI item, InventoryLocation dst, int timeout_ms)
bool ClearInventoryReservationEx (EntityAI item, InventoryLocation dst)
proto native int GetAnyInventoryReservationCount ()
Private Attributes
int m_syncClearUserReservationindex = -1
Private Attributes inherited from GameInventory
const int c_InventoryReservationTimeoutMS = 5000
reservations
const int c_InventoryReservationTimeoutShortMS = 3000
const float c_MaxItemDistanceRadius = 2.5
anti-cheats
Additional Inherited Members
Static Private Member Functions inherited from GameInventory
static proto native EntityAI LocationCreateEntity (notnull InventoryLocation inv_loc, string type, int iSetupFlags, int iRotation)
creates new item directly at location
static proto native EntityAI LocationCreateLocalEntity (notnull InventoryLocation inv_loc, string type, int iSetupFlags, int iRotation)
creates new local item directly at location @NOTE: the item is created localy, i.e. it's not registered to network
static proto native bool LocationCanAddEntity (notnull InventoryLocation inv_loc)
queries if the entity contained in inv_loc.m_item can be added to ground/attachment/cargo/hands/...
static bool LocationCanAddEntityEx (notnull InventoryLocation inv_loc)
static proto native bool LocationTestAddEntity (notnull InventoryLocation inv_loc, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check, bool do_script_load_check)
test if the entity contained in inv_loc.m_item can be added to ground/attachment/cargo/hands/...
static proto native bool LocationCanRemoveEntity (notnull InventoryLocation inv_loc)
queries if the entity contained in inv_loc.m_item can be removed from ground/attachment/cargo/hands/...
static proto native bool LocationCanMoveEntity (notnull InventoryLocation src, notnull InventoryLocation dst)
queries if the entity contained in inv_loc.m_item can be moved to another location This is a shorthand for CanRemove + CanAdd query
static int GetInventoryCheckContext ()
static bool LocationCanMoveEntitySyncCheck (notnull InventoryLocation src, notnull InventoryLocation dst)
static proto native EntityAI LocationGetEntity (notnull InventoryLocation inv_loc)
static void OnServerInventoryCommandStatic (ParamsReadContext ctx)
static proto native bool LocationAddEntity (notnull InventoryLocation inv_loc)
adds item to inventory location
static proto native bool LocationRemoveEntity (notnull InventoryLocation inv_loc)
removes item from inventory location
static proto native bool LocationMoveEntity (notnull InventoryLocation src_loc, notnull InventoryLocation dst_loc)
removes item from current inventory location and adds it to destination
static proto native bool LocationSyncMoveEntity (notnull InventoryLocation src_loc, notnull InventoryLocation dst_loc)
synchronously removes item from current inventory location and adds it to destination no anims involved
static proto native bool LocationSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2)
swaps two entities
static proto native bool ServerLocationMoveEntity (notnull EntityAI item, ParamsWriteContext ctx)
removes item from current inventory location and adds it to destination + sync via inventory command
static proto native bool ServerLocationSyncMoveEntity (Man player, notnull EntityAI item, ParamsWriteContext ctx)
synchronously removes item from current inventory location and adds it to destination + sync via inventory command no anims involved
static proto native bool ServerLocationSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, ParamsWriteContext ctx)
swaps two entities
static proto native bool ServerHandEvent (notnull Man player, notnull EntityAI item, ParamsWriteContext ctx)
hand event to clients
static proto native bool PrepareDropEntityPos (EntityAI owner, notnull EntityAI item, out vector mat[4], bool useValuesInMatrix=false, int conflictCheckDepth=-1)
Finds a transformation for the item to be dropped to If the initial transforation overlaps with another conflicting entity (i.e. car) then the transform will be snapped to the nearest outer edge. If no valid snapping transformation could be found, then the output from 'PlaceOnSurface' is used.
static proto native bool TestDropEntityPos (EntityAI owner, notnull EntityAI item, out vector mat[4], bool useValuesInMatrix=false, int conflictCheckDepth=-1)
static proto native bool CanSwapEntities (notnull EntityAI item1, notnull EntityAI item2)
test if ordinary swap can be performed.
static bool CanSwapEntitiesEx (notnull EntityAI item1, notnull EntityAI item2)
static proto native bool CanForceSwapEntities (notnull EntityAI item1, InventoryLocation item1_dst, notnull EntityAI item2, out InventoryLocation item2_dst)
test if forced swap can be performed.
static bool CanForceSwapEntitiesEx (notnull EntityAI item1, InventoryLocation item1_dst, notnull EntityAI item2, out InventoryLocation item2_dst)
static bool MakeDstForSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, out InventoryLocation dst1, out InventoryLocation dst2)
helper function for swap
static bool MakeSrcAndDstForSwap (notnull EntityAI item1, notnull EntityAI item2, out InventoryLocation src1, out InventoryLocation src2, out InventoryLocation dst1, out InventoryLocation dst2)
helper function for swap
static bool MakeSrcAndDstForForceSwap (notnull EntityAI item1, notnull EntityAI item2, out InventoryLocation src1, out InventoryLocation src2, out InventoryLocation dst1, notnull InventoryLocation dst2)
helper function for ForceSwap
static bool SetGroundPosByOwner (EntityAI owner, notnull EntityAI item, out InventoryLocation ground)
static bool SetGroundPosByTransform (EntityAI owner, notnull EntityAI item, out InventoryLocation ground, vector transform[4])
static void SetGroundPosByOwnerBounds (EntityAI owner, notnull EntityAI item, out InventoryLocation ground, vector halfExtents, float angle, float cosAngle, float sinAngle)
static proto native bool AddInventoryReservation (EntityAI item, InventoryLocation dst, int timeout_ms)
static proto native bool ExtendInventoryReservation (EntityAI item, InventoryLocation dst, int timeout_ms)
static proto native bool ClearInventoryReservation (EntityAI item, InventoryLocation dst)
static proto native bool HasInventoryReservation (EntityAI item, InventoryLocation dst)
Internally: HasInventoryReservationEx(item, dst, FindInventoryReservationMode.LEGACY, FindInventoryReservationMode.LEGACY)
static proto native bool HasInventoryReservationCanAdd (EntityAI item, InventoryLocation dst)
Internally: !HasInventoryReservationEx(item, dst, FindInventoryReservationMode.ITEM, FindInventoryReservationMode.DST)
static proto native bool HasInventoryReservationEx (EntityAI item, InventoryLocation dst, FindInventoryReservationMode itemMode, FindInventoryReservationMode parentMode)
itemMode will iterate over item reservations, parentMode will iterate over parent reservations
static proto native bool GetInventoryReservationCount (EntityAI item, InventoryLocation dst)
static proto native bool CheckRequestSrc (notnull Man requestingPlayer, notnull InventoryLocation src, float radius)
static proto native bool CheckDropRequest (notnull Man requestingPlayer, notnull InventoryLocation src, float radius)
static proto native bool CheckTakeItemRequest (notnull Man requestingPlayer, notnull InventoryLocation src, notnull InventoryLocation dst, float radius)
static proto native bool CheckMoveToDstRequest (notnull Man requestingPlayer, notnull InventoryLocation src, notnull InventoryLocation dst, float radius)
static proto native bool CheckSwapItemsRequest (notnull Man requestingPlayer, notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, float radius)
static proto native bool CheckManipulatedObjectsDistances (notnull EntityAI e0, notnull EntityAI e1, float radius)
Static Private Attributes inherited from GameInventory
static int m_inventory_check_context = InventoryCheckContext.DEFAULT
Detailed Description
inventory for plain man/human
HumanInventory has simple synchronous operations only, i.e. no animations are involved while adding/removing/swapping to/from hands.
Animations are added on higher level of hierarchy (DayZPlayerInventory for example)
Definition at line 9 of file HumanInventory.c.
Member Function Documentation
CanAddEntityInHands()
HumanInventory::CanAddEntityInHands (EntityAI e) private
alternative for TestAddEntityInHands(e, true, true, true);
CanOpenInventory()
proto native bool HumanInventory::CanOpenInventory () private
CanRemoveEntityInHands()
HumanInventory::CanRemoveEntityInHands () private
Returns
true if entity can be removed from hands
ClearUserReservedLocation()
proto native void HumanInventory::ClearUserReservedLocation (notnull EntityAI eai) private
Referenced by ClearUserReservedLocationSynced().
ClearUserReservedLocationAtIndex()
proto native bool HumanInventory::ClearUserReservedLocationAtIndex (int index) private
Referenced by ClearUserReservedLocationAtIndexSynced(), RedirectToHandEvent(), Update(), and ValidateUserReservationCancel().
ClearUserReservedLocationAtIndexSynced()
void HumanInventory::ClearUserReservedLocationAtIndexSynced (int index) inline private
Definition at line 85 of file HumanInventory.c.
  {
    if (GetGame().IsClient())
      m_syncClearUserReservationindex = index;
    else if (!GetGame().IsMultiplayer())
    {
      ClearUserReservedLocationAtIndex(index);
      InventoryLocation il = new InventoryLocation();
      GetUserReservedLocation(index, il);
      EntityAI item = il.GetItem();
      item.GetOnReleaseLock().Invoke(item);
    }
  }
References ClearUserReservedLocationAtIndex(), GetGame(), GetUserReservedLocation(), and m_syncClearUserReservationindex.
ClearUserReservedLocationForContainer()
proto native void HumanInventory::ClearUserReservedLocationForContainer (notnull EntityAI eai) private
ClearUserReservedLocationSynced()
void HumanInventory::ClearUserReservedLocationSynced (notnull EntityAI eai) inline private
Definition at line 73 of file HumanInventory.c.
  {
    if (GetGame().IsClient())
      m_syncClearUserReservationindex = FindUserReservedLocationIndex(eai);
    else if (!GetGame().IsMultiplayer())
    {
      ClearUserReservedLocation(eai);
      eai.GetOnReleaseLock().Invoke(eai);
    }
  }
References ClearUserReservedLocation(), FindUserReservedLocationIndex(), GetGame(), and m_syncClearUserReservationindex.
CreateInHands()
HumanInventory::CreateInHands (string typeName) private
creates new entity in hands
Parameters
[in] typeName type name of the entity to be created
Returns
new entity or null otherwise
Referenced by CreateInInventory(), CTObjectFollower::SetHandsItem(), and ActionUncoverHeadBase::UncoverHead().
CreateInInventory()
HumanInventory::CreateInInventory (string type) inline private
creates entity somewhere in inventory
Parameters
[in] type item type to be placed in inventory
Returns
created entity
Definition at line 65 of file HumanInventory.c.
  {
    EntityAI newEntity = super.CreateInInventory(type);
    if (newEntity == null)
      newEntity = CreateInHands(type);
    return newEntity;
  }
References CreateInHands().
DropEntity()
override bool HumanInventory::DropEntity (InventoryMode mode, EntityAI owner, notnull EntityAI item) inline private
Definition at line 139 of file HumanInventory.c.
  {
    InventoryLocation src = new InventoryLocation();
    if (item && item.GetInventory() && item.GetInventory().GetCurrentInventoryLocation(src))
    {
      switch (src.GetType())
      {
      case InventoryLocationType.HANDS:
        if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::DropEntity(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
        HandEvent(mode, new HandEventDrop(GetManOwner(), src));
        return true;
      default:
        return super.DropEntity(mode, owner, item);
      }
    }
    Error("No inventory location");
    return false;
  }
References Error(), GetManOwner(), HandEvent(), hndDebugPrint(), and LogManager::IsInventoryHFSMLogEnable().
Referenced by EntityAI::DropEntityImpl(), and ThrowEntity().
FindCollidingUserReservedLocationIndex()
proto native int HumanInventory::FindCollidingUserReservedLocationIndex (notnull EntityAI e, notnull InventoryLocation dst) private
FindFirstUserReservedLocationIndexForContainer()
proto native int HumanInventory::FindFirstUserReservedLocationIndexForContainer (notnull EntityAI e) private
FindUserReservedLocationIndex()
proto native int HumanInventory::FindUserReservedLocationIndex (notnull EntityAI e) private
Referenced by ClearUserReservedLocationSynced(), and RedirectToHandEvent().
ForceSwapEntities()
override bool HumanInventory::ForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) inline private
returns item to previous location, if available
Definition at line 368 of file HumanInventory.c.
  {
    InventoryLocation src1, src2, dst1;
    if (GameInventory.MakeSrcAndDstForForceSwap(item1, item2, src1, src2, dst1, item2_dst))
    {
      GameInventory manOwnerInventory = GetManOwner().GetInventory();
      if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::FSwap(" + typename.EnumToString(InventoryMode, mode) + ") dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " dst2=" + InventoryLocation.DumpToStringNullSafe(item2_dst));
      bool handled = false;
      switch (src1.GetType())
      {
      case InventoryLocationType.HANDS:
        if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::FSwap-HND@1(" + typename.EnumToString(InventoryMode, mode) + ") src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) + " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " item2_dst=" + InventoryLocation.DumpToStringNullSafe(item2_dst));
        HandEventBase e = new HandEventForceSwap(GetManOwner(), src1, src2, dst1, item2_dst);
        e.ReserveInventory();
        HandEvent(mode, e);
        handled = true;
        break;
      }
      switch (src2.GetType())
      {
      case InventoryLocationType.HANDS:
        InventoryLocation fswap_dst2 = new InventoryLocation;
        if (SwappingToPreviousLocation(item2, item1, fswap_dst2))
        {
          if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::FSwap-PREV(" + typename.EnumToString(InventoryMode, mode) + ") src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) + " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " fswap_dst2=" + InventoryLocation.DumpToStringNullSafe(fswap_dst2));
          HandEvent(mode, new HandEventForceSwap(GetManOwner(), src1, src2, dst1, fswap_dst2));
        }
        else
        {
          if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::FSwap-HND@2(" + typename.EnumToString(InventoryMode, mode) + ") src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) + " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " item2_dst=" + InventoryLocation.DumpToStringNullSafe(item2_dst));
          HandEvent(mode, new HandEventForceSwap(GetManOwner(), src1, src2, dst1, item2_dst));
        }
        handled = true;
        break;
      }
      bool returnValue = true;
      if (!handled)
        returnValue = super.ForceSwapEntities(mode, item1, item2, item2_dst);
      return returnValue;
    }
    Error("HumanInventory::ForceSwapEntities: No inventory location");
    return false;
  }
References InventoryLocation::DumpToStringNullSafe(), Error(), GetManOwner(), HandEvent(), hndDebugPrint(), LogManager::IsInventoryHFSMLogEnable(), GameInventory::MakeSrcAndDstForForceSwap(), and SwappingToPreviousLocation().
Referenced by EntityAI::ForceSwapEntitiesImpl().
GetDebugFlag()
proto native bool HumanInventory::GetDebugFlag () private
GetEntityInHands()
HumanInventory::GetEntityInHands () private
Returns
entity in hands
Referenced by HasEntityInHands(), EntityAI::PredictiveMoveItemFromHandsToInventory(), ReplaceItemInElsewhereWithNewinHandsImpl(), ReplaceItemInHandsWithNewImpl(), ReplaceItemWithNew(), and EntityAI::TakeEntityToHandsImpl().
GetManOwner()
Man HumanInventory::GetManOwner () inline private
Definition at line 102 of file HumanInventory.c.
  {
    return Man.Cast(GetInventoryOwner());
  }
References GameInventory::GetInventoryOwner().
Referenced by HumanInventoryWithFSM::CreateStableStates(), DropEntity(), ForceSwapEntities(), HumanInventoryWithFSM::Init(), LocalDestroyEntity(), OnEntityInHandsCreated(), OnEntityInHandsDestroyed(), HumanInventoryWithFSM::ProcessHandAbortEvent(), HumanInventoryWithFSM::ProcessHandEvent(), ReplaceItemElsewhereWithNewInHands(), ReplaceItemInHandsWithNew(), ReplaceItemInHandsWithNewElsewhere(), SwapEntities(), TakeEntityAsAttachmentEx(), TakeEntityToCargoEx(), TakeToDst(), and ThrowEntity().
GetUserReservedLocation()
proto native void HumanInventory::GetUserReservedLocation (int index, out notnull InventoryLocation dst) private
Referenced by ClearUserReservedLocationAtIndexSynced(), RedirectToHandEvent(), and Update().
GetUserReservedLocationCount()
proto native int HumanInventory::GetUserReservedLocationCount () private
HandEvent()
bool HumanInventory::HandEvent (InventoryMode mode, HandEventBase e) inline private
Definition at line 134 of file HumanInventory.c.
  {
    return true;
  }
Referenced by DropEntity(), ForceSwapEntities(), LocalDestroyEntity(), ReplaceItemInElsewhereWithNewinHandsImpl(), ReplaceItemInHandsWithNewImpl(), SwapEntities(), TakeEntityAsAttachmentEx(), TakeEntityToCargoEx(), and ThrowEntity().
HandleInventoryManipulation()
void HumanInventory::HandleInventoryManipulation () protected
Referenced by Update().
HasEntityInHands()
bool HumanInventory::HasEntityInHands (EntityAI e) inline private
Definition at line 107 of file HumanInventory.c.
  {
    return e == GetEntityInHands();
  }
References GetEntityInHands().
LocalDestroyEntity()
override bool HumanInventory::LocalDestroyEntity (notnull EntityAI item) inline private
Definition at line 421 of file HumanInventory.c.
  {
    InventoryLocation src = new InventoryLocation();
    if (item.GetInventory().GetCurrentInventoryLocation(src))
    {
      switch (src.GetType())
      {
      case InventoryLocationType.HANDS:
        if (GetInventoryOwner().IsAlive())
        {
          if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::LocalDestroy inv item=" + item);
          HandEvent(InventoryMode.LOCAL, new HandEventDestroy(GetManOwner(), src));
          return true;
        }
        return super.LocalDestroyEntity(item);
      default:
        return super.LocalDestroyEntity(item);
      }
    }
    Error("LocalDestroyEntity: No inventory location");
    return false;
  }
References Error(), GameInventory::GetInventoryOwner(), GetManOwner(), HandEvent(), hndDebugPrint(), and LogManager::IsInventoryHFSMLogEnable().
Referenced by EntityAI::LocalDestroyEntityInHands(), and CTObjectFollower::SetHandsItem().
OnEntityInHandsCreated()
void HumanInventory::OnEntityInHandsCreated (InventoryLocation src) inline private
Definition at line 118 of file HumanInventory.c.
  {
    InventoryLocation cpy = new InventoryLocation();
    cpy.Copy(src);
    if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] OnEntityInHandsCreated src=" + InventoryLocation.DumpToStringNullSafe(cpy));
    ProcessHandEvent(new HandEventCreated(GetManOwner(), src));
  }
References InventoryLocation::DumpToStringNullSafe(), GetManOwner(), hndDebugPrint(), LogManager::IsInventoryHFSMLogEnable(), and ProcessHandEvent().
OnEntityInHandsDestroyed()
void HumanInventory::OnEntityInHandsDestroyed (InventoryLocation src) inline private
Definition at line 126 of file HumanInventory.c.
  {
    InventoryLocation cpy = new InventoryLocation();
    cpy.Copy(src);
    if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] OnEntityInHandsDestroyed src=" + InventoryLocation.DumpToStringNullSafe(cpy));
    ProcessHandEvent(new HandEventDestroyed(GetManOwner(), cpy));
  }
References InventoryLocation::DumpToStringNullSafe(), GetManOwner(), hndDebugPrint(), LogManager::IsInventoryHFSMLogEnable(), and ProcessHandEvent().
OnHandsEnteredStableState()
void HumanInventory::OnHandsEnteredStableState (HandStateBase src, HandStateBase dst) private
OnHandsExitedStableState()
void HumanInventory::OnHandsExitedStableState (HandStateBase src, HandStateBase dst) private
OnHandsStateChanged()
void HumanInventory::OnHandsStateChanged (HandStateBase src, HandStateBase dst) private
ProcessHandEvent()
bool HumanInventory::ProcessHandEvent (HandEventBase e) private
Referenced by OnEntityInHandsCreated(), and OnEntityInHandsDestroyed().
RedirectToHandEvent()
bool HumanInventory::RedirectToHandEvent (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst) inline private
Definition at line 192 of file HumanInventory.c.
  {
    if (src.GetType() == InventoryLocationType.HANDS)
    {
      Man man_src = Man.Cast(src.GetParent());
      if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HI::RedirectToHandEvent - source location == HANDS, player has to handle this");
      EntityAI item = src.GetItem();
      int r_index = FindUserReservedLocationIndex(item);
      if (r_index >= 0)
      {
        InventoryLocation r_il = new InventoryLocation();
        GetUserReservedLocation(r_index, r_il);
        ClearUserReservedLocationAtIndex(r_index);
        int r_type = r_il.GetType();
        if (r_type == InventoryLocationType.CARGO || r_type == InventoryLocationType.PROXYCARGO)
          r_il.GetParent().GetOnReleaseLock().Invoke(item);
        else if (r_type == InventoryLocationType.ATTACHMENT)
          r_il.GetParent().GetOnAttachmentReleaseLock().Invoke(item, r_il.GetSlot());
      }
      man_src.GetHumanInventory().HandEvent(mode, new HandEventMoveTo(man_src, src, dst));
      return true;
    }
    if (dst.GetType() == InventoryLocationType.HANDS)
    {
      if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HI::RedirectToHandEvent - dst location == HANDS, player has to handle this");
      Man man_dst = Man.Cast(dst.GetParent());
      man_dst.GetHumanInventory().HandEvent(mode, new HandEventTake(man_dst, src));
      return true;
    }
    return false;
  }
References ClearUserReservedLocationAtIndex(), FindUserReservedLocationIndex(), GetUserReservedLocation(), hndDebugPrint(), and LogManager::IsInventoryHFSMLogEnable().
Referenced by TakeEntityToInventory(), and TakeToDst().
ReplaceItemElsewhereWithNewInHands()
bool HumanInventory::ReplaceItemElsewhereWithNewInHands (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline private
Definition at line 456 of file HumanInventory.c.
  {
    return ReplaceItemInElsewhereWithNewinHandsImpl(mode, new HandEventDestroyElsewhereAndReplaceWithNewInHands(GetManOwner(), null, lambda));
  }
References GetManOwner(), and ReplaceItemInElsewhereWithNewinHandsImpl().
Referenced by EntityAI::ReplaceItemElsewhereWithNewInHandsImpl().
ReplaceItemInElsewhereWithNewinHandsImpl()
bool HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl (InventoryMode mode, HandEventBase e) inline protected
Definition at line 461 of file HumanInventory.c.
  {
    if (GetEntityInHands())
    {
      Error("[inv] HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl Item in hands, event=" + e.DumpToString());
      return false;
    }
    InventoryLocation dst = e.GetDst();
    if (dst)
    {
      switch (dst.GetType())
      {
      case InventoryLocationType.HANDS:
        if (GetInventoryOwner().IsAlive())
        {
          if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl event=" + e);
          HandEvent(mode, e);
          return true;
        }
        if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl DEAD_owner=" + GetInventoryOwner().GetName() + "=" + GetInventoryOwner());
        Error("HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl TODO"); // replace-with-new in corpse's hands, not implemented
        return false;
      default:
        Error("[inv] HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl src has to be hands");
        return false;
      }
    }
    Error("[inv] HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl no dst in event, event=" + e.DumpToString());
    return false;
  }
References Error(), GetEntityInHands(), GameInventory::GetInventoryOwner(), GetName(), HandEvent(), hndDebugPrint(), and LogManager::IsInventoryHFSMLogEnable().
Referenced by ReplaceItemElsewhereWithNewInHands().
ReplaceItemInHandsWithNew()
bool HumanInventory::ReplaceItemInHandsWithNew (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline protected
Definition at line 526 of file HumanInventory.c.
  {
    return ReplaceItemInHandsWithNewImpl(mode, new HandEventDestroyAndReplaceWithNew(GetManOwner(), null, lambda));
  }
References GetManOwner(), and ReplaceItemInHandsWithNewImpl().
Referenced by EntityAI::ReplaceItemInHandsWithNewImpl(), and ReplaceItemWithNew().
ReplaceItemInHandsWithNewElsewhere()
bool HumanInventory::ReplaceItemInHandsWithNewElsewhere (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline protected
Definition at line 531 of file HumanInventory.c.
  {
    return ReplaceItemInHandsWithNewImpl(mode, new HandEventDestroyAndReplaceWithNewElsewhere(GetManOwner(), null, lambda));
  }
References GetManOwner(), and ReplaceItemInHandsWithNewImpl().
Referenced by EntityAI::ReplaceItemInHandsWithNewElsewhereImpl().
ReplaceItemInHandsWithNewImpl()
bool HumanInventory::ReplaceItemInHandsWithNewImpl (InventoryMode mode, HandEventBase e) inline protected
Definition at line 496 of file HumanInventory.c.
  {
    EntityAI itemInHands = GetEntityInHands();
    InventoryLocation src = new InventoryLocation();
    if (itemInHands && itemInHands.GetInventory().GetCurrentInventoryLocation(src))
    {
      switch (src.GetType())
      {
      case InventoryLocationType.HANDS:
        if ((mode != InventoryMode.SERVER) && GetInventoryOwner().IsAlive())
        {
          if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::ReplaceItemInHandsWithNewImpl event=" + e);
          HandEvent(mode, e);
          return true;
        }
        if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::ReplaceItemInHandsWithNewImpl DEAD_owner=" + GetInventoryOwner().GetName() + "=" + GetInventoryOwner());
        HandEvent(mode, e);
        return true;
      default:
        Error("[inv] HumanInventory::ReplaceItemInHandsWithNewImpl src has to be hands");
        return false;
      }
    }
    Error("[inv] HumanInventory::ReplaceItemInHandsWithNewImpl No item in hands, event=" + e.DumpToString());
    return false;
  }
References Error(), GetEntityInHands(), GameInventory::GetInventoryOwner(), GetName(), HandEvent(), hndDebugPrint(), and LogManager::IsInventoryHFSMLogEnable().
Referenced by ReplaceItemInHandsWithNew(), and ReplaceItemInHandsWithNewElsewhere().
ReplaceItemWithNew()
override bool HumanInventory::ReplaceItemWithNew (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline private
Definition at line 447 of file HumanInventory.c.
  {
    EntityAI itemInHands = GetEntityInHands();
    if (itemInHands == lambda.m_OldItem)
      return ReplaceItemInHandsWithNew(mode, lambda);
    return super.ReplaceItemWithNew(mode, lambda);
  }
References GetEntityInHands(), and ReplaceItemInHandsWithNew().
Referenced by EntityAI::ReplaceItemWithNewImpl().
SetUserReservedLocation()
proto native void HumanInventory::SetUserReservedLocation (notnull EntityAI eai, notnull InventoryLocation dst) private
SwapEntities()
override bool HumanInventory::SwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2) inline private
returns item to previous location, if available
Definition at line 324 of file HumanInventory.c.
  {
    InventoryLocation src1, src2, dst1, dst2;
    if (GameInventory.MakeSrcAndDstForSwap(item1, item2, src1, src2, dst1, dst2))
    {
      bool handled = false;
      switch (src1.GetType())
      {
      case InventoryLocationType.HANDS:
        InventoryLocation fswap_dst2 = new InventoryLocation;
        if (SwappingToPreviousLocation(item1, item2, fswap_dst2))
        {
          if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::Swap HandEventForceSwap(" + typename.EnumToString(InventoryMode, mode) + ") IH=src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2));
          HandEvent(mode, new HandEventForceSwap(GetManOwner(), src1, src2, dst1, fswap_dst2));
        }
        else
        {
          if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::Swap HandEventSwap(" + typename.EnumToString(InventoryMode, mode) + ") src1=" + InventoryLocation.DumpToStringNullSafe(src1) + "src2=" + InventoryLocation.DumpToStringNullSafe(src2));
          HandEvent(mode, new HandEventSwap(GetManOwner(), src1, src2, dst1, dst2));
        }
        handled = true;
        break;
      }
      switch (src2.GetType())
      {
      case InventoryLocationType.HANDS:
        if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::Swap HandEventSwap2(" + typename.EnumToString(InventoryMode, mode) + ") src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " IH=src2=" + InventoryLocation.DumpToStringNullSafe(src2));
        HandEvent(mode, new HandEventSwap(GetManOwner(), src2, src1, dst2, dst1));
        handled = true;
        break;
      }
      if (!handled)
        return super.SwapEntities(mode, item1, item2);
      return true;
    }
    Error("HumanInventory::SwapEntities: cannot create src1, src2, dst1, dst2");
    return false;
  }
References InventoryLocation::DumpToStringNullSafe(), Error(), GetManOwner(), HandEvent(), hndDebugPrint(), LogManager::IsInventoryHFSMLogEnable(), GameInventory::MakeSrcAndDstForSwap(), and SwappingToPreviousLocation().
Referenced by EntityAI::SwapEntitiesImpl().
SwappingToPreviousLocation()
bool HumanInventory::SwappingToPreviousLocation (EntityAI item1, EntityAI item2, out InventoryLocation dst) inline protected
Definition at line 536 of file HumanInventory.c.
  {
    bool SwapToPrevious = true;
    InventoryLocation src1 = new InventoryLocation();
    InventoryLocation src2 = new InventoryLocation();
    dst = new InventoryLocation();
    if (item1.GetInventory().GetCurrentInventoryLocation(src1) && item2.GetInventory().GetCurrentInventoryLocation(src2))
    {
      if (item1.m_OldLocation && item1.m_OldLocation.IsValid() && !item1.m_OldLocation.CollidesWith(src2) && item1.m_OldLocation.GetParent() && item1.m_OldLocation.GetParent().GetHierarchyRootPlayer())
      {
        dst.Copy(item1.m_OldLocation);
        int count = item1.GetInventory().GetSlotIdCount();
        if (count > 0 && src2.GetType() == InventoryLocationType.ATTACHMENT) //item2 is currently attached somewhere
        {
          for (int i = 0; i < count; i++)
          {
            int slotID = item1.GetInventory().GetSlotId(i);
            if (src2.GetSlot() == slotID) //can be attached into the same slot. And will be.
              return false;
          }
        }
        if (!item1.m_OldLocation.GetParent().GetInventory().LocationCanAddEntity(item1.m_OldLocation))
          SwapToPrevious = false;
        if (CanSwapEntitiesEx(item1, item2))
          SwapToPrevious = false;
        if (SwapToPrevious)
          return true;
      }
    }
    return false;
  }
References GameInventory::CanSwapEntitiesEx().
Referenced by ForceSwapEntities(), and SwapEntities().
TakeEntityAsAttachmentEx()
override bool HumanInventory::TakeEntityAsAttachmentEx (InventoryMode mode, notnull EntityAI item, int slot) inline private
Definition at line 294 of file HumanInventory.c.
  {
    InventoryLocation src = new InventoryLocation();
    if (item.GetInventory().GetCurrentInventoryLocation(src))
    {
      switch (src.GetType())
      {
      case InventoryLocationType.HANDS:
        if (GetInventoryOwner().IsAlive())
        {
          if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::Take2Att(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + " slot=" + slot);
          InventoryLocation dst = new InventoryLocation();
          EntityAI src_entity = GetInventoryOwner();
          dst.SetAttachment(src_entity, item, slot);
          HandEvent(mode, new HandEventMoveTo(GetManOwner(), src, dst));
          return true;
        }
        return super.TakeEntityAsAttachmentEx(mode, item, slot);
      default:
        return super.TakeEntityAsAttachmentEx(mode, item, slot);
      }
    }
    Error("HumanInventory::TakeEntityAsAttachmentEx: No inventory location");
    return false;
  }
References Error(), GameInventory::GetInventoryOwner(), GetManOwner(), HandEvent(), hndDebugPrint(), and LogManager::IsInventoryHFSMLogEnable().
Referenced by EntityAI::TakeEntityAsAttachmentExImpl().
TakeEntityToCargoEx()
override bool HumanInventory::TakeEntityToCargoEx (InventoryMode mode, notnull EntityAI item, int idx, int row, int col) inline private
Put item into into cargo on specific cargo location.
Definition at line 265 of file HumanInventory.c.
  {
    InventoryLocation src = new InventoryLocation();
    if (item.GetInventory().GetCurrentInventoryLocation(src))
    {
      switch (src.GetType())
      {
      case InventoryLocationType.HANDS:
        if (GetInventoryOwner().IsAlive())
        {
          if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::Take2Cgo(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + " row=" + row + " col=" + col);
          InventoryLocation dst = new InventoryLocation();
          dst.SetCargo(GetInventoryOwner(), item, idx, row, col, item.GetInventory().GetFlipCargo());
          HandEvent(mode, new HandEventMoveTo(GetManOwner(), src, dst));
          return true;
        }
        return super.TakeEntityToCargoEx(mode, item, idx, row, col);
      default:
        return super.TakeEntityToCargoEx(mode, item, idx, row, col);
      }
    }
    Error("HumanInventory::TakeEntityToCargoEx: No inventory location");
    return false;
  }
References Error(), GameInventory::GetInventoryOwner(), GetManOwner(), HandEvent(), hndDebugPrint(), and LogManager::IsInventoryHFSMLogEnable().
TakeEntityToInventory()
override bool HumanInventory::TakeEntityToInventory (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item) inline private
Definition at line 241 of file HumanInventory.c.
  {
    InventoryLocation src = new InventoryLocation();
    if (item.GetInventory().GetCurrentInventoryLocation(src))
    {
      InventoryLocation dst = new InventoryLocation();
      if (FindFreeLocationFor(item, flags, dst))
      {
        if (RedirectToHandEvent(mode, src, dst))
          return true;
        if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::Take2Inv(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
        return super.TakeEntityToInventory(mode, flags, item);
      }
      else
        return false; // no room
    }
    Error("HumanInventory::TakeEntityToInventory: No inventory location");
    return false;
  }
References Error(), GameInventory::FindFreeLocationFor(), hndDebugPrint(), LogManager::IsInventoryHFSMLogEnable(), and RedirectToHandEvent().
Referenced by EntityAI::PredictiveMoveItemFromHandsToInventory(), and EntityAI::TakeEntityToInventoryImpl().
TakeToDst()
override bool HumanInventory::TakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst) inline private
Definition at line 231 of file HumanInventory.c.
  {
    if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] Take2Dst(" + typename.EnumToString(InventoryMode, mode) + ") src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
    if (GetManOwner().IsAlive() && RedirectToHandEvent(mode, src, dst))
      return true;
    return super.TakeToDst(mode, src, dst);
  }
References InventoryLocation::DumpToStringNullSafe(), GetManOwner(), hndDebugPrint(), LogManager::IsInventoryHFSMLogEnable(), and RedirectToHandEvent().
Referenced by EntityAI::TakeEntityToHandsImpl(), and EntityAI::TakeToDstImpl().
TestAddEntityInHands()
HumanInventory::TestAddEntityInHands (EntityAI e, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check) private
Parameters
[in] e entity to test for taking in hands
[in] do_item_check deny if entity is not InventoryItem
[in] do_occupancy_test deny if there is item in hands already
[in] do_script_check deny if script conditions fail
Returns
true if item passed all tests
ThrowEntity()
bool HumanInventory::ThrowEntity (EntityAI item, vector dir, float force) inline private
Definition at line 160 of file HumanInventory.c.
  {
    if (GetGame().IsServer() && GetGame().IsMultiplayer())
      return false;
    DayZPlayer player = DayZPlayer.Cast(item.GetHierarchyRootPlayer());
    InventoryMode invMode = InventoryMode.PREDICTIVE;
    if (player.NeedInventoryJunctureFromServer(item, item.GetHierarchyParent(), null))
      invMode = InventoryMode.JUNCTURE;
    InventoryLocation src = new InventoryLocation();
    if (item && item.GetInventory() && item.GetInventory().GetCurrentInventoryLocation(src))
    {
      switch (src.GetType())
      {
      case InventoryLocationType.HANDS:
        if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[inv] HumanInventory::ThrowEntity item=" + item);
        HandEventThrow throwEvent = new HandEventThrow(GetManOwner(), src);
        throwEvent.SetForce(dir * force);
        HandEvent(invMode, throwEvent);
        return true;
      default:
        DropEntity(invMode, player, item);
        return true;
      }
    }
    Error("No inventory location");
    return false;
  }
References DropEntity(), Error(), GetGame(), GetManOwner(), HandEvent(), hndDebugPrint(), and LogManager::IsInventoryHFSMLogEnable().
Update()
void HumanInventory::Update (float delta_time) inline protected
Definition at line 575 of file HumanInventory.c.
  {
    HandleInventoryManipulation();
    if (m_syncClearUserReservationindex != -1 && ScriptInputUserData.CanStoreInputUserData())
    {
      ScriptInputUserData ctx = new ScriptInputUserData();
      ctx.Write(INPUT_UDT_INVENTORY);
      ctx.Write(InventoryCommandType.USER_RESERVATION_CANCEL);
      ctx.Write(m_syncClearUserReservationindex);
      ctx.Send();
      InventoryLocation il = new InventoryLocation();
      GetUserReservedLocation(m_syncClearUserReservationindex, il);
      ClearUserReservedLocationAtIndex(m_syncClearUserReservationindex);
      EntityAI item = il.GetItem();
      item.GetOnReleaseLock().Invoke(item);
      m_syncClearUserReservationindex = -1;
    }
  }
References ScriptInputUserData::CanStoreInputUserData(), ClearUserReservedLocationAtIndex(), GetUserReservedLocation(), HandleInventoryManipulation(), INPUT_UDT_INVENTORY, and m_syncClearUserReservationindex.
ValidateUserReservationCancel()
bool HumanInventory::ValidateUserReservationCancel (inout Serializer ctx, InventoryValidation validation) inline protected
TODO(kumarjac): It returned true and claimed success before, is this correct?
Definition at line 596 of file HumanInventory.c.
  {
    validation.m_Result = InventoryValidationResult.SUCCESS;
    int index = -1;
    if (!ctx.Read(index))
    {
      return true;
    }
    ClearUserReservedLocationAtIndex(index);
    //m_UserReservationToClear = index;
    return true;
  }
References ClearUserReservedLocationAtIndex().
Member Data Documentation
m_syncClearUserReservationindex
int HumanInventory::m_syncClearUserReservationindex = -1 private
Definition at line 11 of file HumanInventory.c.
Referenced by ClearUserReservedLocationAtIndexSynced(), ClearUserReservedLocationSynced(), and Update().
The documentation for this class was generated from the following file:
scripts/3_Game/Systems/Inventory/HumanInventory.c