DayZ: ArrowManagerPlayer Class Reference
ArrowManagerPlayer Class Reference
Private Member Functions
void ArrowManagerPlayer (PlayerBase player)
bool Save (ParamsWriteContext ctx)
bool Load (ParamsReadContext ctx)
Private Member Functions inherited from ArrowManagerBase
void ArrowManagerBase (EntityAI owner)
void AddArrow (EntityAI arrow)
void RemoveArrow (EntityAI arrow)
void ClearArrows ()
int GetArrowsCount ()
void DropArrow (int index)
void DropFirstArrow ()
void DropAllArrows ()
EntityAI GetArrow (int index)
EntityAI GetFirstArrow ()
EntityAI AcquireFirstArrow (bool keepTransform=false)
Static Private Member Functions
static void InitializeHash ()
static void AddArrowTypeToHash (string ArrowType)
static GetArrowTypeFromHash (int hash)
Static Private Attributes
static ref map< int, typename > m_TypeHashTable
Additional Inherited Members
Private Attributes inherited from ArrowManagerBase
const int VERSION = 2
ref array< EntityAI > m_Arrows
EntityAI m_Owner
Detailed Description
Definition at line 1 of file ArrowManagerPlayer.c.
Constructor & Destructor Documentation
ArrowManagerPlayer()
void ArrowManagerPlayer::ArrowManagerPlayer (PlayerBase player) inline private
Definition at line 5 of file ArrowManagerPlayer.c.
  {
    if (!m_TypeHashTable)
      InitializeHash();
  }
References InitializeHash(), and m_TypeHashTable.
Member Function Documentation
AddArrowTypeToHash()
static void ArrowManagerPlayer::AddArrowTypeToHash (string ArrowType) inline static private
Definition at line 21 of file ArrowManagerPlayer.c.
  {
    m_TypeHashTable.Insert(ArrowType.Hash(), ArrowType.ToType());
  }
References m_TypeHashTable.
Referenced by InitializeHash().
GetArrowTypeFromHash()
static ArrowManagerPlayer::GetArrowTypeFromHash (int hash) inline static private
Definition at line 26 of file ArrowManagerPlayer.c.
  {
    return m_TypeHashTable.Get(hash);
  }
References m_TypeHashTable.
Referenced by Load().
InitializeHash()
static void ArrowManagerPlayer::InitializeHash () inline static private
Definition at line 11 of file ArrowManagerPlayer.c.
  {
    m_TypeHashTable = new map<int, typename>();
    AddArrowTypeToHash("Ammo_HuntingBolt");
    AddArrowTypeToHash("Ammo_ImprovisedBolt_1");
    AddArrowTypeToHash("Ammo_ImprovisedBolt_2");
    AddArrowTypeToHash("Ammo_ImprovisedBolt_3");
  }
References AddArrowTypeToHash(), and m_TypeHashTable.
Referenced by ArrowManagerPlayer().
Load()
bool ArrowManagerPlayer::Load (ParamsReadContext ctx) inline private
Definition at line 71 of file ArrowManagerPlayer.c.
  {
    int version;
    if (!ctx.Read(version))
      return false;
    int count;
    if (!ctx.Read(count))
      return false;
    for (int i = 0; i < count; i++)
    {
      if (version >= 1)
      {
        int hash;
        if (!ctx.Read(hash))
          return false;
        float angleF[3];
        float posF[3];
        float value;
        if (!ctx.Read(value))
          return false;
        angleF[0] = value;
        if (!ctx.Read(value))
          return false;
        angleF[1] = value;
        if (!ctx.Read(value))
          return false;
        angleF[2] = value;
        if (!ctx.Read(value))
          return false;
        posF[0] = value;
        if (!ctx.Read(value))
          return false;
        posF[1] = value;
        if (!ctx.Read(value))
          return false;
        posF[2] = value;
        vector angle = "0 0 0";
        vector pos = "0 0 0";
        angle = vector.ArrayToVec(angleF);
        pos = vector.ArrayToVec(posF);
        int pivot;
        if (!ctx.Read(pivot))
          return false;
        if (version >= 2)
        {
#ifdef SERVER
          int spawnFlags = ECE_KEEPHEIGHT | ECE_DYNAMIC_PERSISTENCY;
#else
          int spawnFlags = ECE_LOCAL | ECE_KEEPHEIGHT | ECE_DYNAMIC_PERSISTENCY;
#endif
          typename arrowType = GetArrowTypeFromHash(hash);
          EntityAI arrow = EntityAI.Cast(GetGame().CreateObjectEx(arrowType.ToString(), pos, spawnFlags));
          if (arrow)
          {
            arrow.SetQuantityToMinimum();
            arrow.SetYawPitchRoll(angle);
            m_Owner.AddChild(arrow, pivot);
          }
        }
      }
    }
    return true;
  }
References vector::ArrayToVec(), ECE_DYNAMIC_PERSISTENCY, ECE_KEEPHEIGHT, ECE_LOCAL, GetArrowTypeFromHash(), GetGame(), and ArrowManagerBase::m_Owner.
Save()
bool ArrowManagerPlayer::Save (ParamsWriteContext ctx) inline private
Definition at line 31 of file ArrowManagerPlayer.c.
  {
    ctx.Write(VERSION);
    int count = m_Arrows.Count();
    int i;
    //TODO MW Delete after find why sometimes arrow missing - most likely Life span
    for (i = count - 1; i >= 0; i--)
    {
      if (!m_Arrows.Get(i))
        m_Arrows.Remove(i);
    }
    count = m_Arrows.Count();
    ctx.Write(count);
    for (i = 0; i < count; i++)
    {
      EntityAI arrow = m_Arrows.Get(i);
      string type = arrow.GetType();
      ctx.Write(type.Hash());
      vector angle = arrow.GetLocalYawPitchRoll();
      vector pos = arrow.GetLocalPosition();
      ctx.Write(angle[0]);
      ctx.Write(angle[1]);
      ctx.Write(angle[2]);
      ctx.Write(pos[0]);
      ctx.Write(pos[1]);
      ctx.Write(pos[2]);
      int pivot = arrow.GetHierarchyPivot();
      ctx.Write(pivot);
    }
    return true;
  }
References string::Hash(), ArrowManagerBase::m_Arrows, and ArrowManagerBase::VERSION.
Member Data Documentation
m_TypeHashTable
ref map<int, typename> ArrowManagerPlayer::m_TypeHashTable static private
Definition at line 3 of file ArrowManagerPlayer.c.
Referenced by AddArrowTypeToHash(), ArrowManagerPlayer(), GetArrowTypeFromHash(), and InitializeHash().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/ArrowManager/ArrowManagerPlayer.c