DayZ: CarLightBase Class Reference
CarLightBase Class Reference
Private Member Functions
void CarRearLight ()
void SetAsSegregatedBrakeLight ()
void SetAsSegregatedReverseLight ()
void CivilianSedanFrontLight ()
void Hatchback_02FrontLight ()
void Offroad_02FrontLight ()
void OffroadHatchbackFrontLight ()
void Sedan_02FrontLight ()
void Truck_01FrontLight ()
Private Attributes
float m_SegregatedBrakeBrightness = 2
float m_SegregatedBrakeRadius = 6
float m_SegregatedBrakeAngle = 180
vector m_SegregatedBrakeColorRGB = Vector(1, 0.05, 0.05)
Detailed Description
Definition at line 1 of file CarRearLightBase.c.
Member Function Documentation
CarRearLight()
void CarLightBase::CarRearLight () inline private
Definition at line 9 of file CarRearLightBase.c.
  {
    // These are just some default values which can be overwrittend down in the hierarchy.
    // Reverse light only
    m_SegregatedBrightness = 2;
    m_SegregatedRadius = 10;
    m_SegregatedAngle = 180;
    m_SegregatedColorRGB = Vector(1.0, 1.0, 1.0);
    // Brake & Revese lights combined
    m_AggregatedBrightness = 2.5;
    m_AggregatedRadius = 12;
    m_AggregatedAngle = 180;
    m_AggregatedColorRGB = Vector(1.0, 0.5, 0.5);
    FadeIn(0.1);
    SetFadeOutTime(0.1);
    SetVisibleDuringDaylight(false);
    SetCastShadow(false);
    SetFlareVisible(false);
    EnableSpecular(false); // Specular is disabled because it causes ugly shining on cars
    SegregateLight();
  }
References Vector().
CivilianSedanFrontLight()
void CarLightBase::CivilianSedanFrontLight () inline private
Definition at line 3 of file CivilianSedanFrontLight.c.
  {
    m_SegregatedBrightness = 5;
    m_SegregatedRadius = 65;
    m_SegregatedAngle = 90;
    m_SegregatedColorRGB = Vector(1.0, 0.8, 0.8);
    m_AggregatedBrightness = 10;
    m_AggregatedRadius = 80;
    m_AggregatedAngle = 100;
    m_AggregatedColorRGB = Vector(1.0, 0.8, 0.8);
    FadeIn(0.3);
    SetFadeOutTime(0.25);
    SegregateLight();
  }
References Vector().
Hatchback_02FrontLight()
void CarLightBase::Hatchback_02FrontLight () inline private
Definition at line 3 of file Hatchback_02FrontLight.c.
  {
    m_SegregatedBrightness = 6;
    m_SegregatedRadius = 65;
    m_SegregatedAngle = 80;
    m_SegregatedColorRGB = Vector(0.8, 0.8, 1);
    m_AggregatedBrightness = 12;
    m_AggregatedRadius = 90;
    m_AggregatedAngle = 90;
    m_AggregatedColorRGB = Vector(0.8, 0.8, 1);
    FadeIn(0.3);
    SetFadeOutTime(0.25);
    SegregateLight();
  }
References Vector().
Offroad_02FrontLight()
void CarLightBase::Offroad_02FrontLight () inline private
Definition at line 3 of file Offroad_02FrontLight.c.
  {
    m_SegregatedBrightness = 5;
    m_SegregatedRadius = 75;
    m_SegregatedAngle = 90;
    m_SegregatedColorRGB = Vector(0.85, 0.85, 0.58);
    m_AggregatedBrightness = 10;
    m_AggregatedRadius = 100;
    m_AggregatedAngle = 120;
    m_AggregatedColorRGB = Vector(0.85, 0.85, 0.58);
    FadeIn(0.1);
    SetFadeOutTime(0.05);
    SegregateLight();
  }
References Vector().
OffroadHatchbackFrontLight()
void CarLightBase::OffroadHatchbackFrontLight () inline private
Definition at line 3 of file OffroadHatchbackFrontLight.c.
  {
    m_SegregatedBrightness = 5;
    m_SegregatedRadius = 55;
    m_SegregatedAngle = 110;
    m_SegregatedColorRGB = Vector(1.0, 0.8, 0.6);
    m_AggregatedBrightness = 10;
    m_AggregatedRadius = 75;
    m_AggregatedAngle = 120;
    m_AggregatedColorRGB = Vector(1.0, 0.8, 0.6);
    FadeIn(0.3);
    SetFadeOutTime(0.25);
    SegregateLight();
  }
References Vector().
Sedan_02FrontLight()
void CarLightBase::Sedan_02FrontLight () inline private
Definition at line 3 of file Sedan_02FrontLight.c.
  {
    m_SegregatedBrightness = 4;
    m_SegregatedRadius = 75;
    m_SegregatedAngle = 90;
    m_SegregatedColorRGB = Vector(0.95, 0.95, 0.78);
    m_AggregatedBrightness = 8;
    m_AggregatedRadius = 100;
    m_AggregatedAngle = 120;
    m_AggregatedColorRGB = Vector(0.95, 0.95, 0.78);
    FadeIn(0.1);
    SetFadeOutTime(0.05);
    SegregateLight();
  }
References Vector().
SetAsSegregatedBrakeLight()
void CarLightBase::SetAsSegregatedBrakeLight () inline private
Definition at line 34 of file CarRearLightBase.c.
  {
    SetRadiusTo(m_SegregatedBrakeRadius);
    SetSpotLightAngle(m_SegregatedBrakeAngle);
    SetBrightnessTo(m_SegregatedBrakeBrightness);
    SetAmbientColor(m_SegregatedBrakeColorRGB[0], m_SegregatedBrakeColorRGB[1], m_SegregatedBrakeColorRGB[2]);
    SetDiffuseColor(m_SegregatedBrakeColorRGB[0], m_SegregatedBrakeColorRGB[1], m_SegregatedBrakeColorRGB[2]);
    SetFadeOutTime(0.1);
    SetFlareVisible(false);
  }
SetAsSegregatedReverseLight()
void CarLightBase::SetAsSegregatedReverseLight () inline private
Definition at line 45 of file CarRearLightBase.c.
  {
    SetRadiusTo(m_SegregatedRadius);
    SetSpotLightAngle(m_SegregatedAngle);
    SetBrightnessTo(m_SegregatedBrightness);
    SetAmbientColor(m_SegregatedColorRGB[0], m_SegregatedColorRGB[1], m_SegregatedColorRGB[2]);
    SetDiffuseColor(m_SegregatedColorRGB[0], m_SegregatedColorRGB[1], m_SegregatedColorRGB[2]);
    SetFadeOutTime(0.1);
    SetFlareVisible(false);
  }
Truck_01FrontLight()
void CarLightBase::Truck_01FrontLight () inline private
Definition at line 3 of file Truck_01FrontLight.c.
  {
    m_SegregatedBrightness = 4;
    m_SegregatedRadius = 75;
    m_SegregatedAngle = 90;
    m_SegregatedColorRGB = Vector(0.90, 0.90, 0.68);
    m_AggregatedBrightness = 8;
    m_AggregatedRadius = 100;
    m_AggregatedAngle = 120;
    m_AggregatedColorRGB = Vector(0.90, 0.90, 0.68);
    FadeIn(0.1);
    SetFadeOutTime(0.05);
    SegregateLight();
  }
References Vector().
Member Data Documentation
m_SegregatedBrakeAngle
float CarLightBase::m_SegregatedBrakeAngle = 180 private
Definition at line 6 of file CarRearLightBase.c.
m_SegregatedBrakeBrightness
float CarLightBase::m_SegregatedBrakeBrightness = 2 private
Definition at line 4 of file CarRearLightBase.c.
m_SegregatedBrakeColorRGB
vector CarLightBase::m_SegregatedBrakeColorRGB = Vector(1, 0.05, 0.05) private
Definition at line 7 of file CarRearLightBase.c.
m_SegregatedBrakeRadius
float CarLightBase::m_SegregatedBrakeRadius = 6 private
Definition at line 5 of file CarRearLightBase.c.
The documentation for this class was generated from the following files:
scripts/4_World/Entities/ScriptedLightBase/SpotLightBase/CarLightBase/CarRearLightBase.c
scripts/4_World/Entities/ScriptedLightBase/SpotLightBase/CarLightBase/CivilianSedanFrontLight.c
scripts/4_World/Entities/ScriptedLightBase/SpotLightBase/CarLightBase/Hatchback_02FrontLight.c
scripts/4_World/Entities/ScriptedLightBase/SpotLightBase/CarLightBase/Offroad_02FrontLight.c
scripts/4_World/Entities/ScriptedLightBase/SpotLightBase/CarLightBase/OffroadHatchbackFrontLight.c
scripts/4_World/Entities/ScriptedLightBase/SpotLightBase/CarLightBase/Sedan_02FrontLight.c
scripts/4_World/Entities/ScriptedLightBase/SpotLightBase/CarLightBase/Truck_01FrontLight.c