DayZ: ActionFillBrakes Class Reference
ActionFillBrakes Class Reference
Private Member Functions
void ActionFillBrakes ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnEndAnimationLoopServer (ActionData action_data)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 11 of file ActionFillBrakes.c.
Constructor & Destructor Documentation
ActionFillBrakes()
void ActionFillBrakes::ActionFillBrakes () inline private
Definition at line 13 of file ActionFillBrakes.c.
  {
    m_CallbackClass = ActionFillBrakesCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_EMPTY_VESSEL;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
    m_FullBody = true;
    m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
    m_LockTargetOnUse = false;
    m_Text = "#refill_car";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_LockTargetOnUse, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionFillBrakes::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 30 of file ActionFillBrakes.c.
  {
    if (!target || !IsTransport(target))
      return false;
    if (item.GetQuantity() <= 0)
      return false;
    Car car = Car.Cast(target.GetObject());
    if (!car)
      return false;
    if (car.GetFluidFraction(CarFluid.BRAKE) >= 0.98)
      return false;
    float distance = Math.AbsFloat(vector.Distance(car.GetPosition(), player.GetPosition()));
    CarScript carS = CarScript.Cast(car);
    if (distance <= carS.GetActionDistanceFuel())
    {
      array<string> selections = new array<string>;
      target.GetObject().GetActionComponentNameList(target.GetComponentIndex(), selections);
      for (int s = 0; s < selections.Count(); s++)
      {
        if (selections[s] == carS.GetActionCompNameBrakes())
          return true;
      }
    }
    return false;
  }
References Math::AbsFloat(), vector::Distance(), and IsTransport().
CreateConditionComponents()
override void ActionFillBrakes::CreateConditionComponents () inline private
Definition at line 24 of file ActionFillBrakes.c.
  {
    m_ConditionItem = new CCINonRuined;
    m_ConditionTarget = new CCTNone;
  }
References m_ConditionItem, and m_ConditionTarget.
OnEndAnimationLoopServer()
override void ActionFillBrakes::OnEndAnimationLoopServer (ActionData action_data) inline private
Definition at line 62 of file ActionFillBrakes.c.
  {
    if (action_data.m_MainItem && action_data.m_MainItem.GetQuantity() <= 0.01)
      action_data.m_MainItem.SetQuantity(0);
  }
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/Vehicles/ActionFillBrakes.c