DayZ: ActionUnrestrainTargetCB Class Reference
ActionUnrestrainTargetCB Class Reference
Private Member Functions
override void CreateActionComponent ()
float ObtainUnrestrainTime ()
Private Attributes
const float DEFAULT_UNRESTRAIN_TIME = 2
Detailed Description
Definition at line 1 of file ActionUnrestrainTarget.c.
Member Function Documentation
CreateActionComponent()
override void ActionUnrestrainTargetCB::CreateActionComponent () inline private
Definition at line 5 of file ActionUnrestrainTarget.c.
  {
    float time = ObtainUnrestrainTime();
    if (time <= 0)
      time = DEFAULT_UNRESTRAIN_TIME;
    if (m_ActionData.m_Player.IsQuickRestrain())
      time = DEBUG_QUICK_UNRESTRAIN_TIME;
    m_ActionData.m_ActionComponent = new CAContinuousTime(time);
  }
References DEBUG_QUICK_UNRESTRAIN_TIME, DEFAULT_UNRESTRAIN_TIME, ActionData::m_ActionComponent, ActionBaseCB::m_ActionData, ActionData::m_Player, and ObtainUnrestrainTime().
ObtainUnrestrainTime()
float ActionUnrestrainTargetCB::ObtainUnrestrainTime () inline private
Definition at line 18 of file ActionUnrestrainTarget.c.
  {
    PlayerBase target_player = PlayerBase.Cast(m_ActionData.m_Target.GetObject());
    PlayerBase source_player = m_ActionData.m_Player;
    if (target_player.IsRestrained())
    {
      EntityAI item_in_hands_source = source_player.GetItemInHands();
      ItemBase item_in_hands_target = target_player.GetItemInHands();
      CachedObjectsArrays.ARRAY_STRING.Clear();
      item_in_hands_target.ConfigGetTextArray("CanBeUnrestrainedBy", CachedObjectsArrays.ARRAY_STRING);
      string item_in_hands_name = item_in_hands_source.GetType();
      for (int i = 0; i < CachedObjectsArrays.ARRAY_STRING.Count(); i++)
      {
        if ((i % 2) == 0)
        {
          string class_name = CachedObjectsArrays.ARRAY_STRING.Get(i);
          if (GetGame().IsKindOf(item_in_hands_name, class_name))
          {
            float value = CachedObjectsArrays.ARRAY_STRING.Get(i + 1).ToFloat();
            return value;
          }
        }
      }
    }
    return -1;
  }
References CachedObjectsArrays::ARRAY_STRING, class_name, GetGame(), ActionBaseCB::m_ActionData, ActionData::m_Player, and ActionData::m_Target.
Referenced by CreateActionComponent().
Member Data Documentation
DEFAULT_UNRESTRAIN_TIME
const float ActionUnrestrainTargetCB::DEFAULT_UNRESTRAIN_TIME = 2 private
Definition at line 3 of file ActionUnrestrainTarget.c.
Referenced by CreateActionComponent().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionUnrestrainTarget.c