DayZ: ItemRadio Class Reference
ItemRadio Class Reference
Private Member Functions
override bool IsTransmitter ()
bool CanOperate ()
override void OnSwitchOn ()
override void OnSwitchOff ()
override void OnWorkStop ()
void TuneNextStation ()
void TunePreviousStation ()
override void SetActions ()
Detailed Description
Definition at line 1 of file Radio.c.
Member Function Documentation
CanOperate()
bool ItemRadio::CanOperate () inline private
Definition at line 9 of file Radio.c.
  {
    return GetCompEM().IsSwitchedOn();
  }
IsTransmitter()
override bool ItemRadio::IsTransmitter () inline private
Definition at line 3 of file Radio.c.
  {
    return true;
  }
OnSwitchOff()
override void ItemRadio::OnSwitchOff () inline private
Definition at line 21 of file Radio.c.
  {
    //switch device off
    SwitchOn(false);
  }
OnSwitchOn()
override void ItemRadio::OnSwitchOn () inline private
Definition at line 15 of file Radio.c.
  {
    //switch device on
    SwitchOn(true);
  }
OnWorkStop()
override void ItemRadio::OnWorkStop () inline private
Definition at line 27 of file Radio.c.
  {
    //turn off device
    GetCompEM().SwitchOff();
  }
SetActions()
override void ItemRadio::SetActions () inline private
Definition at line 46 of file Radio.c.
  {
    super.SetActions();
    AddAction(ActionTurnOnTransmitter);
    AddAction(ActionTurnOffTransmitter);
    AddAction(ActionTuneRadioStation);
  }
References ActionTuneRadioStation(), ActionTurnOffTransmitter(), ActionTurnOnTransmitter(), and AddAction().
TuneNextStation()
void ItemRadio::TuneNextStation () inline private
Definition at line 34 of file Radio.c.
  {
    //tune next station
    TuneNext();
  }
References TuneNext.
TunePreviousStation()
void ItemRadio::TunePreviousStation () inline private
Definition at line 40 of file Radio.c.
  {
    //tune previous station
    TunePrev();
  }
References TunePrev().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Radio.c