DayZ: EffBulletImpactBase Class Reference
EffBulletImpactBase Class Reference
Private Member Functions
void EffBulletImpactBase ()
override void OnCheckUpdate ()
void SetEnterParticle (int id)
void SetExitParticle (int id)
void SetRicochetParticle (int id)
void SetSingleParticle (int id)
void SetAngledEnterValue (float f)
void EvaluateEffect (Object directHit, int componentIndex, vector pos, int impact_type, vector surfNormal, vector exitPos, vector inSpeed, vector outSpeed, string ammoType)
float CalculateStoppingForce (float in_speedf, float out_speedf, string ammoType, float weight)
void OnEnterCalculations (Particle p)
void OnExitCalculations (Particle p, float outSpeedf)
void OnRicochetCalculations (Particle p, float outspeedf)
void OnEnterAngledCalculations (Particle p)
override void Event_OnStarted ()
Private Member Functions inherited from EffectParticle
override EffectType GetEffectType ()
Get what type of effect the Effect is.
override bool IsParticle ()
Check whether the Effect is EffectParticle without casting.
void SetParticle (Particle p)
Sets the main particle which this Effect will manage.
Particle GetParticle ()
Gets the main particle which this Effect is managing.
override void Start ()
Plays all elements this effect consists of.
override void Stop ()
Stops all elements this effect consists of.
void AttachTo (Object obj, vector local_pos="0 0 0", vector local_ori="0 0 0", bool force_rotation_to_world=false)
Read Particle.AddAsChild.
void ReAttach ()
Helper method to attach to parent using stored settings.
void AddAsChild (Object obj, vector local_pos, vector local_ori, bool force_rotation_to_world)
Helper method to attach to parent.
void Event_OnPlayStart ()
Event which just simply exists (DEPRECATED)
void Event_OnPlayStarted ()
Event which just simply exists (DEPRECATED)
void SetParticleID (int id)
Sets the id of the particle to be used.
int GetParticleID ()
Gets the id of the particle to be used.
void SetCurrentParticleID (int id)
Sets the id of the particle to be used.
int GetCurrentParticleID ()
Gets the current id of the managed Particle.
override void SetCurrentParent (Object parent_obj, bool updateCached=true)
Set current parent of the managed Particle.
override Object GetCurrentParent ()
Get the current parent of the managed Particle.
override void SetCurrentPosition (vector pos, bool updateCached=true)
Set the current world position of the managed Particle.
override vector GetCurrentPosition ()
Get the current world position of the managed Particle.
override void SetCurrentLocalPosition (vector pos, bool updateCached=true)
Set the current local position of the managed Particle.
override vector GetCurrentLocalPosition ()
Get the current local position of the managed Particle.
void SetOrientation (vector ori)
Set orientation of the EffectParticle.
vector GetOrientation ()
Get the orientation of the EffectParticle.
void SetCurrentOrientation (vector ori, bool updateCached=true)
Set the current orientation of the managed Particle.
vector GetCurrentOrientation ()
Get the current orientation of the managed Particle.
void ForceParticleRotationRelativeToWorld (bool state)
Set orientation setting to be used by the effect when the Effect starts.
bool IsParticleRotationRelativeToWorld ()
Get the orientation setting to be used by the effect when the Effect starts.
bool IsParticleCurrentRotationRelativeToWorld ()
Get the current orientation setting to be used by the managed Particle.
void EffectParticle ()
ctor
void ~EffectParticle ()
dtor
override void InitEffect ()
init
override string GetDebugName ()
Override when getting debug information.
override void ValidateStart ()
Validation whether an effect truly started playing or if the Effect should stop as none is present.
void CheckLifeSpan ()
Was never called and probably should never be called.
void SetDecalOwner (Object o)
Private Attributes
float MIN_SCALING_PARAM = 0.1
Object m_DirectHit
float m_StoppingForce
float m_Weight
int m_ImpactType
int m_ComponentIndex
vector m_Pos
vector m_SurfNormal
vector m_ExitPos
vector m_InSpeed
vector m_OutSpeed
string m_AmmoType
int m_ParticleEnter = -1
int m_ParticleExit = -1
int m_ParticleRicochet = -1
float m_EnterSplashCoef = 0.003
float m_ExitSplashCoef = 0.002
float m_RicochetSplashCoef = 0.002
float m_EnterAngledSplashCoef = 0.01
float m_AngledEnter = 0.40
Private Attributes inherited from EffectParticle
Particle m_ParticleObj
The main Particle effect that this Effect wrapper manages.
int m_ParticleID
The ID in the ParticleList to create Particle from.
vector m_Orientation
Orientation set by SetOrientation.
bool m_ForceRotationRelativeToWorld
Orientation setting to be used by the effect when the Effect starts.
vector m_ParticleOrientation
Object m_Object
Static Private Attributes
static const int SURVIVOR_HEAD = 0
static const int INFECTED_HEAD = 3
static float DEFAULT_PROJECTILE_WEIGHT = 0.015
static vector INVALID = "0 0 0"
Detailed Description
Definition at line 1 of file BulletImpactBase.c.
Constructor & Destructor Documentation
EffBulletImpactBase()
void EffBulletImpactBase::EffBulletImpactBase () inline private
Definition at line 35 of file BulletImpactBase.c.
  {
  }
Member Function Documentation
CalculateStoppingForce()
float EffBulletImpactBase::CalculateStoppingForce (float in_speedf, float out_speedf, string ammoType, float weight) inline private
Definition at line 88 of file BulletImpactBase.c.
  {
    if (m_ImpactType == ImpactTypes.MELEE)
      return Math.RandomFloat(50, 100);
    float projectile_weight_coef = weight / DEFAULT_PROJECTILE_WEIGHT;
    float stopping_force = (in_speedf - out_speedf) * projectile_weight_coef;
    return stopping_force;
  }
References DEFAULT_PROJECTILE_WEIGHT, m_ImpactType, and Math::RandomFloat().
Referenced by EvaluateEffect().
EvaluateEffect()
void EffBulletImpactBase::EvaluateEffect (Object directHit, int componentIndex, vector pos, int impact_type, vector surfNormal, vector exitPos, vector inSpeed, vector outSpeed, string ammoType) inline private
Definition at line 72 of file BulletImpactBase.c.
  {
    m_DirectHit = directHit;
    m_Pos = pos;
    m_ImpactType = impact_type;
    m_ComponentIndex = componentIndex;
    m_SurfNormal = surfNormal;
    m_ExitPos = exitPos;
    m_InSpeed = inSpeed;
    m_OutSpeed = outSpeed;
    m_AmmoType = ammoType;
    m_Weight = GetGame().ConfigGetFloat("CfgAmmo " + ammoType + " weight");
    m_StoppingForce = CalculateStoppingForce(m_InSpeed.Length(), m_OutSpeed.Length(), ammoType, m_Weight);
  }
References CalculateStoppingForce(), GetGame(), vector::Length(), m_AmmoType, m_ComponentIndex, m_DirectHit, m_ExitPos, m_ImpactType, m_InSpeed, m_OutSpeed, m_Pos, m_StoppingForce, m_SurfNormal, and m_Weight.
Event_OnStarted()
override void EffBulletImpactBase::Event_OnStarted () inline private
Definition at line 219 of file BulletImpactBase.c.
  {
    Particle p;
    vector particle_orientation;
    float outSpeedf = m_OutSpeed.Length();
    ParticleManager gPM = ParticleManager.GetInstance();
    if (m_ImpactType == ImpactTypes.RICOCHET)
    {
      p = gPM.PlayInWorld(m_ParticleRicochet, m_Pos);
      if (p)
      {
        particle_orientation = m_OutSpeed.VectorToAngles();
        particle_orientation = particle_orientation + "0 -90 0";
        p.SetOrientation(particle_orientation);
        OnRicochetCalculations(p, outSpeedf);
      }
    }
    else
    {
      p = gPM.PlayInWorld(m_ParticleEnter, m_Pos);
      if (p)
      {
        if (m_SurfNormal != INVALID)
        {
          particle_orientation = m_SurfNormal.VectorToAngles();
          particle_orientation = particle_orientation + "0 270 0";
        }
        else
        {
          particle_orientation = "0 0 0"; // This vector is in angles
        }
        p.SetOrientation(particle_orientation);
        OnEnterCalculations(p);
      }
      if (outSpeedf > 0 && m_SurfNormal != INVALID)
      {
        p = gPM.PlayInWorld(m_ParticleExit, m_ExitPos);
        if (p)
        {
          particle_orientation = m_OutSpeed.VectorToAngles();
          particle_orientation = particle_orientation + "0 -90 0";
          p.SetOrientation(particle_orientation);
          OnExitCalculations(p, outSpeedf);
        }
      }
      else
      {
        if (m_SurfNormal != INVALID)
        {
          vector surfNormalN = m_SurfNormal.Normalized();
          vector inSpeedN = m_InSpeed.Normalized();
          vector bounce_ori = surfNormalN + inSpeedN;
          float dot = vector.Dot(bounce_ori, surfNormalN);
          if (dot > m_AngledEnter)
          {
            p = gPM.PlayInWorld(m_ParticleRicochet, m_Pos);
            if (p)
            {
              particle_orientation = bounce_ori.VectorToAngles();
              particle_orientation = particle_orientation + "0 -90 0";
              p.SetOrientation(particle_orientation);
              OnEnterAngledCalculations(p);
            }
          }
        }
      }
    }
    if (p)
      SetParticle(p);
    // Additional impact particle over long ranges. It shows players where their bullets land
    if (Type() != Hit_MeatBones)
    {
      vector camera_pos = GetGame().GetCurrentCameraPosition();
      float distance = vector.Distance(camera_pos, m_Pos);
      // Additional size increase by distance from camera
      float scaling_by_distance = distance * 0.01;
      // Now scale down the above size increase by player's zoom-in value
      float current_FOV = Camera.GetCurrentFOV();
      float config_FOV = GetDayZGame().GetUserFOVFromConfig();
      float FOV_scale = current_FOV / config_FOV;
      scaling_by_distance = 1 + scaling_by_distance * FOV_scale;
      if (scaling_by_distance > 1.1)
      {
        Particle p_distant = gPM.PlayInWorld(ParticleList.IMPACT_DISTANT_DUST, m_Pos);
        particle_orientation = m_SurfNormal.VectorToAngles();
        particle_orientation[1] = particle_orientation[1] + 270;
        p_distant.SetOrientation(particle_orientation);
        p_distant.ScaleParticleParam(EmitorParam.SIZE, scaling_by_distance - 0.5);
        p_distant.ScaleParticleParam(EmitorParam.BIRTH_RATE, scaling_by_distance * 0.1);
        p_distant.ScaleParticleParam(EmitorParam.BIRTH_RATE_RND, scaling_by_distance * 0.1);
        p_distant.ScaleParticleParam(EmitorParam.LIFETIME, scaling_by_distance * 0.3);
        p_distant.ScaleParticleParam(EmitorParam.LIFETIME_RND, scaling_by_distance * 0.3);
      }
    }
  }
References vector::Distance(), vector::Dot(), GetDayZGame(), GetGame(), ParticleList::IMPACT_DISTANT_DUST, INVALID, vector::Length(), m_AngledEnter, m_ExitPos, m_ImpactType, m_InSpeed, m_OutSpeed, m_ParticleEnter, m_ParticleExit, m_ParticleRicochet, m_Pos, m_SurfNormal, vector::Normalized(), OnEnterAngledCalculations(), OnEnterCalculations(), OnExitCalculations(), OnRicochetCalculations(), ParticleManager(), EffectParticle::SetParticle(), Type, and vector::VectorToAngles().
OnCheckUpdate()
override void EffBulletImpactBase::OnCheckUpdate () inline private
Definition at line 40 of file BulletImpactBase.c.
  {
    //DbgUI.Text( m_ammoType );
  }
OnEnterAngledCalculations()
void EffBulletImpactBase::OnEnterAngledCalculations (Particle p) inline private
Definition at line 197 of file BulletImpactBase.c.
  {
    float velocity_min = MIN_SCALING_PARAM + (m_StoppingForce * m_EnterAngledSplashCoef);
    float velocity_max = MIN_SCALING_PARAM + (m_StoppingForce * m_EnterAngledSplashCoef);
    float size = MIN_SCALING_PARAM + (m_StoppingForce * m_EnterAngledSplashCoef);
    float birth_rate = MIN_SCALING_PARAM + (m_StoppingForce * m_EnterAngledSplashCoef);
    if (velocity_min < MIN_SCALING_PARAM)
      velocity_min = MIN_SCALING_PARAM;
    if (size < MIN_SCALING_PARAM)
      size = MIN_SCALING_PARAM;
    if (birth_rate < MIN_SCALING_PARAM)
      birth_rate = MIN_SCALING_PARAM;
    p.ScaleParticleParam(EmitorParam.VELOCITY, velocity_min);
    p.ScaleParticleParam(EmitorParam.VELOCITY_RND, velocity_max);
    p.ScaleParticleParam(EmitorParam.SIZE, size);
    p.ScaleParticleParam(EmitorParam.BIRTH_RATE, birth_rate);
  }
References m_EnterAngledSplashCoef, m_StoppingForce, and MIN_SCALING_PARAM.
Referenced by Event_OnStarted().
OnEnterCalculations()
void EffBulletImpactBase::OnEnterCalculations (Particle p) inline private
Definition at line 100 of file BulletImpactBase.c.
  {
    // All values represent scale
    float velocity_min = (m_StoppingForce * m_EnterSplashCoef);
    float velocity_max = (m_StoppingForce * m_EnterSplashCoef);
    float size = (m_StoppingForce * m_EnterSplashCoef);
    float birth_rate = (m_StoppingForce * m_EnterSplashCoef);
    float air_resistance = velocity_min;
    float lifetime = (m_StoppingForce * m_EnterSplashCoef);
    float lifetime_rnd = (m_StoppingForce * m_EnterSplashCoef);
    if (m_AmmoType == "Bullet_12GaugePellets")
    {
      birth_rate *= 0.5;
      velocity_min *= 2;
      velocity_max *= 2;
    }
    if (velocity_min < 0.75)
      velocity_min = 0.75;
    if (size < 0.75)
      size = 0.75;
    if (lifetime < 0.5)
      lifetime = 0.5;
    if (lifetime_rnd < 0.5)
      lifetime_rnd = 0.5;
    if (velocity_max < 1)
      velocity_max = 1;
    /*Print("===============");
      Print(velocity_min);
      Print(velocity_max);
      Print(size);
      Print(birth_rate);
      Print(air_resistance);
      Print(lifetime);
      Print(lifetime_rnd);*/
    p.ScaleParticleParam(EmitorParam.VELOCITY, velocity_min);
    p.ScaleParticleParam(EmitorParam.VELOCITY_RND, velocity_max);
    p.ScaleParticleParam(EmitorParam.SIZE, size);
    p.ScaleParticleParam(EmitorParam.BIRTH_RATE, birth_rate);
    p.ScaleParticleParam(EmitorParam.AIR_RESISTANCE, air_resistance);
    p.ScaleParticleParam(EmitorParam.AIR_RESISTANCE_RND, air_resistance);
    p.ScaleParticleParam(EmitorParam.LIFETIME, lifetime);
    p.ScaleParticleParam(EmitorParam.LIFETIME_RND, lifetime_rnd);
  }
References m_AmmoType, m_EnterSplashCoef, and m_StoppingForce.
Referenced by Event_OnStarted().
OnExitCalculations()
void EffBulletImpactBase::OnExitCalculations (Particle p, float outSpeedf) inline private
Definition at line 153 of file BulletImpactBase.c.
  {
    float velocity_min = 1 + (outSpeedf * m_ExitSplashCoef);
    float velocity_max = 1 + (outSpeedf * m_ExitSplashCoef);
    float size = 1 + (outSpeedf * m_ExitSplashCoef);
    float birth_rate = 1 + (outSpeedf * m_ExitSplashCoef);
    if (velocity_min < MIN_SCALING_PARAM)
      velocity_min = MIN_SCALING_PARAM;
    if (size < MIN_SCALING_PARAM)
      size = MIN_SCALING_PARAM;
    if (birth_rate < MIN_SCALING_PARAM)
      birth_rate = MIN_SCALING_PARAM;
    p.ScaleParticleParam(EmitorParam.VELOCITY, velocity_min);
    p.ScaleParticleParam(EmitorParam.VELOCITY_RND, velocity_max);
    p.ScaleParticleParam(EmitorParam.SIZE, size);
    p.ScaleParticleParam(EmitorParam.BIRTH_RATE, birth_rate);
  }
References m_ExitSplashCoef, and MIN_SCALING_PARAM.
Referenced by Event_OnStarted().
OnRicochetCalculations()
void EffBulletImpactBase::OnRicochetCalculations (Particle p, float outspeedf) inline private
Definition at line 175 of file BulletImpactBase.c.
  {
    float velocity_min = MIN_SCALING_PARAM + (m_StoppingForce * m_RicochetSplashCoef);
    float velocity_max = MIN_SCALING_PARAM + (m_StoppingForce * m_RicochetSplashCoef);
    float size = MIN_SCALING_PARAM + (m_StoppingForce * m_RicochetSplashCoef);
    float birth_rate = MIN_SCALING_PARAM + (m_StoppingForce * m_RicochetSplashCoef);
    if (velocity_min < MIN_SCALING_PARAM)
      velocity_min = MIN_SCALING_PARAM;
    if (size < MIN_SCALING_PARAM)
      size = MIN_SCALING_PARAM;
    if (birth_rate < MIN_SCALING_PARAM)
      birth_rate = MIN_SCALING_PARAM;
    p.ScaleParticleParam(EmitorParam.VELOCITY, velocity_min);
    p.ScaleParticleParam(EmitorParam.VELOCITY_RND, velocity_max);
    p.ScaleParticleParam(EmitorParam.SIZE, size);
    p.ScaleParticleParam(EmitorParam.BIRTH_RATE, birth_rate);
  }
References m_RicochetSplashCoef, m_StoppingForce, and MIN_SCALING_PARAM.
Referenced by Event_OnStarted().
SetAngledEnterValue()
void EffBulletImpactBase::SetAngledEnterValue (float f) inline private
Definition at line 67 of file BulletImpactBase.c.
  {
    m_AngledEnter = f;
  }
References m_AngledEnter.
SetEnterParticle()
void EffBulletImpactBase::SetEnterParticle (int id) inline private
Definition at line 45 of file BulletImpactBase.c.
  {
    m_ParticleEnter = id;
  }
References m_ParticleEnter.
Referenced by Hit_Water::CalculateStoppingForce(), Hit_Concrete::Hit_Concrete(), Hit_Dirt::Hit_Dirt(), Hit_Foliage::Hit_Foliage(), Hit_Glass::Hit_Glass(), Hit_Glass_Thin::Hit_Glass_Thin(), Hit_Grass::Hit_Grass(), Hit_Gravel::Hit_Gravel(), Hit_MeatBones::Hit_MeatBones(), Hit_Metal::Hit_Metal(), Hit_Plaster::Hit_Plaster(), Hit_Plastic::Hit_Plastic(), Hit_Rubber::Hit_Rubber(), Hit_Sand::Hit_Sand(), Hit_Textile::Hit_Textile(), Hit_Wood::Hit_Wood(), and SetSingleParticle().
SetExitParticle()
void EffBulletImpactBase::SetExitParticle (int id) inline private
Definition at line 50 of file BulletImpactBase.c.
  {
    m_ParticleExit = id;
  }
References m_ParticleExit.
Referenced by Hit_Concrete::Hit_Concrete(), Hit_Dirt::Hit_Dirt(), Hit_Foliage::Hit_Foliage(), Hit_Glass::Hit_Glass(), Hit_Glass_Thin::Hit_Glass_Thin(), Hit_Grass::Hit_Grass(), Hit_Gravel::Hit_Gravel(), Hit_MeatBones::Hit_MeatBones(), Hit_Metal::Hit_Metal(), Hit_Plaster::Hit_Plaster(), Hit_Plastic::Hit_Plastic(), Hit_Rubber::Hit_Rubber(), Hit_Sand::Hit_Sand(), Hit_Textile::Hit_Textile(), Hit_Wood::Hit_Wood(), and SetSingleParticle().
SetRicochetParticle()
void EffBulletImpactBase::SetRicochetParticle (int id) inline private
Definition at line 55 of file BulletImpactBase.c.
  {
    m_ParticleRicochet = id;
  }
References m_ParticleRicochet.
Referenced by Hit_Concrete::Hit_Concrete(), Hit_Dirt::Hit_Dirt(), Hit_Foliage::Hit_Foliage(), Hit_Glass::Hit_Glass(), Hit_Glass_Thin::Hit_Glass_Thin(), Hit_Grass::Hit_Grass(), Hit_Gravel::Hit_Gravel(), Hit_MeatBones::Hit_MeatBones(), Hit_Metal::Hit_Metal(), Hit_Plaster::Hit_Plaster(), Hit_Plastic::Hit_Plastic(), Hit_Rubber::Hit_Rubber(), Hit_Sand::Hit_Sand(), Hit_Textile::Hit_Textile(), Hit_Wood::Hit_Wood(), and SetSingleParticle().
SetSingleParticle()
void EffBulletImpactBase::SetSingleParticle (int id) inline private
Definition at line 60 of file BulletImpactBase.c.
  {
    SetEnterParticle(id);
    SetExitParticle(id);
    SetRicochetParticle(id);
  }
References SetEnterParticle(), SetExitParticle(), and SetRicochetParticle().
Referenced by Hit_ErrorNoMaterial::Hit_ErrorNoMaterial(), Hit_MeatBones_MeleeFist::Hit_MeatBones_MeleeFist(), Hit_Undefined::Hit_Undefined(), and Hit_Water::Hit_Water().
Member Data Documentation
DEFAULT_PROJECTILE_WEIGHT
float EffBulletImpactBase::DEFAULT_PROJECTILE_WEIGHT = 0.015 static private
Definition at line 5 of file BulletImpactBase.c.
Referenced by CalculateStoppingForce(), Hit_Foliage::CalculateStoppingForce(), Hit_MeatBones::CalculateStoppingForce(), and Hit_Water::CalculateStoppingForce().
INFECTED_HEAD
const int EffBulletImpactBase::INFECTED_HEAD = 3 static private
Definition at line 4 of file BulletImpactBase.c.
INVALID
vector EffBulletImpactBase::INVALID = "0 0 0" static private
Definition at line 21 of file BulletImpactBase.c.
Referenced by Event_OnStarted().
m_AmmoType
string EffBulletImpactBase::m_AmmoType private
Definition at line 19 of file BulletImpactBase.c.
Referenced by EvaluateEffect(), OnEnterCalculations(), and Hit_MeatBones::OnEnterCalculations().
m_AngledEnter
float EffBulletImpactBase::m_AngledEnter = 0.40 private
Definition at line 33 of file BulletImpactBase.c.
Referenced by Event_OnStarted(), Hit_Concrete::Hit_Concrete(), Hit_Grass::Hit_Grass(), Hit_MeatBones::Hit_MeatBones(), Hit_Water::Hit_Water(), and SetAngledEnterValue().
m_ComponentIndex
int EffBulletImpactBase::m_ComponentIndex private
Definition at line 13 of file BulletImpactBase.c.
Referenced by EvaluateEffect().
m_DirectHit
Object EffBulletImpactBase::m_DirectHit private
Definition at line 9 of file BulletImpactBase.c.
Referenced by Hit_MeatBones::CalculateStoppingForce(), and EvaluateEffect().
m_EnterAngledSplashCoef
float EffBulletImpactBase::m_EnterAngledSplashCoef = 0.01 private
Definition at line 32 of file BulletImpactBase.c.
Referenced by OnEnterAngledCalculations().
m_EnterSplashCoef
float EffBulletImpactBase::m_EnterSplashCoef = 0.003 private
Definition at line 29 of file BulletImpactBase.c.
Referenced by Hit_MeatBones::Hit_MeatBones(), OnEnterCalculations(), Hit_MeatBones::OnEnterCalculations(), and Hit_Wood::OnEnterCalculations().
m_ExitPos
vector EffBulletImpactBase::m_ExitPos private
Definition at line 16 of file BulletImpactBase.c.
Referenced by EvaluateEffect(), Event_OnStarted(), and Hit_MeatBones::Event_OnStarted().
m_ExitSplashCoef
float EffBulletImpactBase::m_ExitSplashCoef = 0.002 private
Definition at line 30 of file BulletImpactBase.c.
Referenced by Hit_MeatBones::Hit_MeatBones(), OnExitCalculations(), Hit_MeatBones::OnExitCalculations(), and Hit_Wood::OnExitCalculations().
m_ImpactType
int EffBulletImpactBase::m_ImpactType private
Definition at line 12 of file BulletImpactBase.c.
Referenced by CalculateStoppingForce(), Hit_Foliage::CalculateStoppingForce(), Hit_MeatBones::CalculateStoppingForce(), EvaluateEffect(), Event_OnStarted(), and Hit_MeatBones::Event_OnStarted().
m_InSpeed
vector EffBulletImpactBase::m_InSpeed private
Definition at line 17 of file BulletImpactBase.c.
Referenced by EvaluateEffect(), Event_OnStarted(), and Hit_MeatBones::Event_OnStarted().
m_OutSpeed
vector EffBulletImpactBase::m_OutSpeed private
Definition at line 18 of file BulletImpactBase.c.
Referenced by EvaluateEffect(), Event_OnStarted(), and Hit_MeatBones::Event_OnStarted().
m_ParticleEnter
int EffBulletImpactBase::m_ParticleEnter = -1 private
Definition at line 24 of file BulletImpactBase.c.
Referenced by Event_OnStarted(), and SetEnterParticle().
m_ParticleExit
int EffBulletImpactBase::m_ParticleExit = -1 private
Definition at line 25 of file BulletImpactBase.c.
Referenced by Event_OnStarted(), and SetExitParticle().
m_ParticleRicochet
int EffBulletImpactBase::m_ParticleRicochet = -1 private
Definition at line 26 of file BulletImpactBase.c.
Referenced by Event_OnStarted(), and SetRicochetParticle().
m_Pos
vector EffBulletImpactBase::m_Pos private
Definition at line 14 of file BulletImpactBase.c.
Referenced by EvaluateEffect(), Event_OnStarted(), and Hit_MeatBones::OnEnterCalculations().
m_RicochetSplashCoef
float EffBulletImpactBase::m_RicochetSplashCoef = 0.002 private
Definition at line 31 of file BulletImpactBase.c.
Referenced by OnRicochetCalculations().
m_StoppingForce
float EffBulletImpactBase::m_StoppingForce private
Definition at line 10 of file BulletImpactBase.c.
Referenced by Hit_MeatBones::BloodSplatGround(), EvaluateEffect(), OnEnterAngledCalculations(), OnEnterCalculations(), Hit_MeatBones::OnEnterCalculations(), Hit_Wood::OnEnterCalculations(), and OnRicochetCalculations().
m_SurfNormal
vector EffBulletImpactBase::m_SurfNormal private
Definition at line 15 of file BulletImpactBase.c.
Referenced by EvaluateEffect(), Hit_Water::EvaluateEffect(), and Event_OnStarted().
m_Weight
float EffBulletImpactBase::m_Weight private
Definition at line 11 of file BulletImpactBase.c.
Referenced by EvaluateEffect().
MIN_SCALING_PARAM
float EffBulletImpactBase::MIN_SCALING_PARAM = 0.1 private
Definition at line 7 of file BulletImpactBase.c.
Referenced by Hit_MeatBones::Hit_MeatBones(), OnEnterAngledCalculations(), Hit_MeatBones::OnEnterCalculations(), Hit_Wood::OnEnterCalculations(), OnExitCalculations(), Hit_MeatBones::OnExitCalculations(), Hit_Wood::OnExitCalculations(), and OnRicochetCalculations().
SURVIVOR_HEAD
const int EffBulletImpactBase::SURVIVOR_HEAD = 0 static private
Definition at line 3 of file BulletImpactBase.c.
The documentation for this class was generated from the following file:
scripts/3_Game/Effects/EffectParticle/BulletImpactBase.c