DayZ: CAContinuousFillPowerGenerator Class Reference
CAContinuousFillPowerGenerator Class Reference
Private Member Functions
void CAContinuousFillPowerGenerator (float quantity_filled_per_second, int liquid_type)
override void Setup (ActionData action_data)
override int Execute (ActionData action_data)
override void CalcAndSetQuantity (ActionData action_data)
Private Member Functions inherited from CAContinuousFill
void CAContinuousFill (float quantity_filled_per_second, int liquid_type)
override void Setup (ActionData action_data)
override int Execute (ActionData action_data)
override int Cancel (ActionData action_data)
override int Interrupt (ActionData action_data)
override float GetProgress ()
void CalcAndSetQuantity (ActionData action_data)
Additional Inherited Members
Private Attributes inherited from CAContinuousFill
float m_TargetUnits
float m_SpentQuantity
float m_SpentQuantity_total
float m_ItemQuantity
float m_AdjustedQuantityFilledPerSecond
float m_QuantityFilledPerSecond
ref Param1< float > m_SpentUnits
float m_TimeElpased
float m_DefaultTimeStep = 0.25
int m_liquid_type
Detailed Description
Definition at line 1 of file CAContinuousFillPowerGenerator.c.
Constructor & Destructor Documentation
CAContinuousFillPowerGenerator()
void CAContinuousFillPowerGenerator::CAContinuousFillPowerGenerator (float quantity_filled_per_second, int liquid_type) inline private
Definition at line 3 of file CAContinuousFillPowerGenerator.c.
  {
    m_QuantityFilledPerSecond = quantity_filled_per_second;
    m_liquid_type = liquid_type;
  }
References CAContinuousFill::m_liquid_type, and CAContinuousFill::m_QuantityFilledPerSecond.
Member Function Documentation
CalcAndSetQuantity()
override void CAContinuousFillPowerGenerator::CalcAndSetQuantity (ActionData action_data) inline private
Definition at line 59 of file CAContinuousFillPowerGenerator.c.
  {
    m_SpentQuantity_total += m_SpentQuantity;
    if (m_SpentUnits)
    {
      m_SpentUnits.param1 = m_SpentQuantity;
      SetACData(m_SpentUnits);
    }
    if (GetGame().IsServer())
    {
      PowerGeneratorBase pg = PowerGeneratorBase.Cast(action_data.m_Target.GetObject()); // get power generator
      int consumed_fuel = pg.AddFuel(m_SpentQuantity);
      action_data.m_MainItem.AddQuantity(-consumed_fuel);
    }
    m_SpentQuantity = 0;
  }
References GetGame(), CAContinuousFill::m_SpentQuantity, CAContinuousFill::m_SpentQuantity_total, CAContinuousFill::m_SpentUnits, and CABase::SetACData().
Execute()
override int CAContinuousFillPowerGenerator::Execute (ActionData action_data) inline private
Definition at line 26 of file CAContinuousFillPowerGenerator.c.
  {
    if (!action_data.m_Player)
      return UA_ERROR;
    PowerGeneratorBase pg = PowerGeneratorBase.Cast(action_data.m_Target.GetObject()); // get power generator
    if (pg.GetFuel() >= pg.GetMaxFuel())
      return UA_FINISHED;
    else
    {
      if (m_SpentQuantity_total < m_TargetUnits)
      {
        m_SpentQuantity += m_AdjustedQuantityFilledPerSecond * action_data.m_Player.GetDeltaT();
        m_TimeElpased += action_data.m_Player.GetDeltaT();
        if (m_TimeElpased >= m_DefaultTimeStep)
        {
          CalcAndSetQuantity(action_data);
          m_TimeElpased = 0;
          //Setup(action_data); //reset data after repeat
        }
        return UA_PROCESSING;
      }
      else
      {
        CalcAndSetQuantity(action_data);
        OnCompletePogress(action_data);
        return UA_FINISHED;
      }
    }
  }
References CalcAndSetQuantity(), CAContinuousFill::m_AdjustedQuantityFilledPerSecond, CAContinuousFill::m_DefaultTimeStep, CAContinuousFill::m_SpentQuantity, CAContinuousFill::m_SpentQuantity_total, CAContinuousFill::m_TargetUnits, CAContinuousFill::m_TimeElpased, CAContinuousBase::OnCompletePogress(), UA_ERROR, UA_FINISHED, and UA_PROCESSING.
Setup()
override void CAContinuousFillPowerGenerator::Setup (ActionData action_data) inline private
Definition at line 9 of file CAContinuousFillPowerGenerator.c.
  {
    m_TimeElpased = 0;
    if (!m_SpentUnits)
      m_SpentUnits = new Param1<float>(0);
    else
      m_SpentUnits.param1 = 0;
    EntityAI pg = EntityAI.Cast(action_data.m_Target.GetObject()); // get power generator
    m_QuantityFilledPerSecond *= Math.Min(action_data.m_MainItem.GetLiquidThroughputCoef(), pg.GetLiquidThroughputCoef());
    m_ItemQuantity = action_data.m_MainItem.GetQuantity();
    m_TargetUnits = pg.GetCompEM().GetEnergyMax() - pg.GetCompEM().GetEnergy();
    m_AdjustedQuantityFilledPerSecond = action_data.m_Player.GetSoftSkillsManager().AddSpecialtyBonus(m_QuantityFilledPerSecond, m_Action.GetSpecialtyWeight(), true);
  }
References CABase::m_Action, CAContinuousFill::m_AdjustedQuantityFilledPerSecond, CAContinuousFill::m_ItemQuantity, CAContinuousFill::m_QuantityFilledPerSecond, CAContinuousFill::m_SpentUnits, CAContinuousFill::m_TargetUnits, CAContinuousFill::m_TimeElpased, and Math::Min().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousFillPowerGenerator.c