DayZ: scripts/4_World/Entities/Firearms/FSM/States/WeaponStableState.c File Reference
WeaponStableState.c File Reference
Enumerations
enum MuzzleState { U = -1 , E = 0 , F = 1 , L = 2 }
Functions
void WeaponStableState (Weapon_Base w=NULL, WeaponStateBase parent=NULL, int anim_state=-1)
void SyncAnimState ()
override void OnEntry (WeaponEventBase e)
override void OnUpdate (float dt)
override void OnExit (WeaponEventBase e)
override bool IsIdle ()
int GetCurrentStateID ()
Weapon state properties
Properties defining the state in several properties for other systems Override these to set them up
Several systems depends on this: WeaponFSM.RandomizeFSMState, which picks out a suitable FSM state when attaching magazine through CE WeaponFSM.ValidateAndRepair, which will attempt to identify a desync and repair the FSM state if so
@WARNING So it is important to set these up correctly to prevent any desync of weapon FSM and actual wepon state
bool IsRepairEnabled ()
Whether WeaponFSM.ValidateAndRepair should be applied on this state @NOTE: This property was implemented at the same time as ValARep To have it disabled by default In case there are modders who created their own state But potentially did not set up their properties correctly As having ValARep run on an improper setup would result in horrible VME spam and desync @WARNING: When enabling repair, it is imperative that all properties are set up correctly.
bool HasBullet ()
Whether there is a bullet in the chamber @NOTE: This should only be false when it is empty So this is true when there is a bullet in the chamber Regardless of the bullet being loaded, firedout or jammed.
bool HasMagazine ()
Whether there is a magazine attached.
bool IsJammed ()
Whether the gun is jammed.
bool IsDischarged ()
Whether the gun is discharged.
bool IsWeaponOpen ()
Whether the gun is open.
void InitMuzzleArray ()
Override with the filling of m_muzzleHasBullet.
bool IsSingleState ()
Special one for when the weapon only has one singular state (like Magnum)
Weapon state properties helpers
Several helpers for better access of certain properties
MuzzleState GetMuzzleState (int idx)
Get chamber state of the muzzle at index.
int GetMuzzleStateCount ()
bool IsChamberValid (int idx)
bool IsChamberFiredOut (int idx)
bool IsChamberFull (int idx)
void ValidateMuzzleArray ()
Safety check and error message in case not set up correctly.
Variables
enum MuzzleState m_animState
ref array< MuzzleState > m_muzzleHasBullet = new array<MuzzleState>()
Enumeration Type Documentation
MuzzleState
enum MuzzleState
Enumerator
U
UNKNOWN.
E
EMPTY.
F
FIRED.
L
LOADED.
Definition at line 14 of file WeaponStableState.c.
{
  U = -1,
  E = 0,
  F = 1,
  L = 2
}
Function Documentation
GetCurrentStateID()
int GetCurrentStateID ()
Definition at line 91 of file WeaponStableState.c.
{ return 0; }
GetMuzzleState()
MuzzleState GetMuzzleState (int idx)
Get chamber state of the muzzle at index.
Definition at line 148 of file WeaponStableState.c.
{ return m_muzzleHasBullet[idx]; }
References m_muzzleHasBullet.
GetMuzzleStateCount()
int GetMuzzleStateCount ()
Definition at line 149 of file WeaponStableState.c.
{ return m_muzzleHasBullet.Count(); }
References m_muzzleHasBullet.
HasBullet()
bool HasBullet ()
Whether there is a bullet in the chamber @NOTE: This should only be false when it is empty So this is true when there is a bullet in the chamber Regardless of the bullet being loaded, firedout or jammed.
Definition at line 120 of file WeaponStableState.c.
{ return false; }
HasMagazine()
bool HasMagazine ()
Whether there is a magazine attached.
Definition at line 123 of file WeaponStableState.c.
{ return false; }
InitMuzzleArray()
void InitMuzzleArray ()
Override with the filling of m_muzzleHasBullet.
Definition at line 135 of file WeaponStableState.c.
{ m_muzzleHasBullet = { MuzzleState.U }; }
References m_muzzleHasBullet.
IsChamberFiredOut()
bool IsChamberFiredOut (int idx)
Definition at line 151 of file WeaponStableState.c.
{ return m_muzzleHasBullet[idx] == MuzzleState.F; }
References m_muzzleHasBullet.
Referenced by DoubleBarrel_Base::CanChamberBullet(), Weapon_Base::CanChamberBullet(), Weapon::CanChamberBullet(), Weapon::CanFire(), Weapon::GetMuzzleStates(), and Weapon_Base::ShowBullet().
IsChamberFull()
bool IsChamberFull (int idx)
Definition at line 152 of file WeaponStableState.c.
{ return m_muzzleHasBullet[idx] != MuzzleState.E; }
References m_muzzleHasBullet.
Referenced by Weapon::CanChamberBullet(), Weapon_Base::CanEjectBullet(), Weapon::ForceSyncSelectionState(), Weapon::GetMuzzleStates(), and InventoryItemSuper::IsChamberFullEx().
IsChamberValid()
bool IsChamberValid (int idx)
Definition at line 150 of file WeaponStableState.c.
{ return m_muzzleHasBullet[idx] != MuzzleState.U; }
References m_muzzleHasBullet.
IsDischarged()
bool IsDischarged ()
Whether the gun is discharged.
Definition at line 129 of file WeaponStableState.c.
{ return false; }
IsIdle()
override bool IsIdle ()
Definition at line 89 of file WeaponStableState.c.
{ return true; }
Referenced by Weapon::CanRemoveFromHands(), and ManBase::OnQuickBarSingleUse().
IsJammed()
bool IsJammed ()
Whether the gun is jammed.
Definition at line 126 of file WeaponStableState.c.
{ return false; }
IsRepairEnabled()
bool IsRepairEnabled ()
Whether WeaponFSM.ValidateAndRepair should be applied on this state @NOTE: This property was implemented at the same time as ValARep To have it disabled by default In case there are modders who created their own state But potentially did not set up their properties correctly As having ValARep run on an improper setup would result in horrible VME spam and desync @WARNING: When enabling repair, it is imperative that all properties are set up correctly.
Definition at line 113 of file WeaponStableState.c.
{ return false; }
IsSingleState()
bool IsSingleState ()
Special one for when the weapon only has one singular state (like Magnum)
Definition at line 138 of file WeaponStableState.c.
{ return false; }
Referenced by ValidateMuzzleArray().
IsWeaponOpen()
bool IsWeaponOpen ()
Whether the gun is open.
Definition at line 132 of file WeaponStableState.c.
{ return false; }
OnEntry()
override void OnEntry (WeaponEventBase e)
Definition at line 70 of file WeaponStableState.c.
  {
    super.OnEntry(e);
    m_weapon.SetJammed(false);
    if (e)
      SyncAnimState();
    m_weapon.ResetWeaponAnimState();
  }
References m_weapon, and SyncAnimState().
OnExit()
override void OnExit (WeaponEventBase e)
Definition at line 83 of file WeaponStableState.c.
  {
    m_weapon.ResetWeaponAnimState();
    super.OnExit(e);
  }
References m_weapon.
OnUpdate()
override void OnUpdate (float dt)
Definition at line 78 of file WeaponStableState.c.
  {
    super.OnUpdate(dt);
    SyncAnimState();
  }
References SyncAnimState().
SyncAnimState()
void SyncAnimState ()
Definition at line 39 of file WeaponStableState.c.
  {
    int curr = m_weapon.GetWeaponAnimState();
    if (curr != m_animState)
    {
      //if (LogManager.IsWeaponLogEnable()) fsmDebugSpam("[wpnfsm] " + Object.GetDebugName(m_weapon) + " synchronizing anim state: " + curr + " --> " + m_animState);
      PlayerBase p;
      if (Class.CastTo(p, m_weapon.GetHierarchyParent()))
      {
        if (p.GetItemInHands() == m_weapon)
        {
          HumanCommandWeapons hcw = p.GetCommandModifier_Weapons();
          if (hcw)
          {
            hcw.SetInitState(m_animState);
            if (LogManager.IsWeaponLogEnable()) fsmDebugSpam("[wpnfsm] " + Object.GetDebugName(m_weapon) + " state=" + m_weapon.GetCurrentState().Type() + " synchronized anim state: " + typename.EnumToString(PistolAnimState, curr) + " --> " + typename.EnumToString(PistolAnimState, m_animState));
          }
          else
          {
            Human wpnOwner = Human.Cast(m_weapon.GetHierarchyRootPlayer());
            HumanCommandWeapons.StaticSetInitState(wpnOwner, m_animState);
            if (LogManager.IsWeaponLogEnable()) fsmDebugSpam("[wpnfsm] " + Object.GetDebugName(m_weapon) + " state=" + m_weapon.GetCurrentState().Type() + " synchronized remote anim state: " + typename.EnumToString(PistolAnimState, curr) + " --> " + typename.EnumToString(PistolAnimState, m_animState));
          }
        }
        m_weapon.SetWeaponAnimState(m_animState);
      }
      else
        m_weapon.SetGroundAnimFrameIndex(m_animState);
    }
  }
References Class::CastTo(), fsmDebugSpam(), LogManager::IsWeaponLogEnable(), m_animState, m_weapon, and HumanCommandWeapons::StaticSetInitState().
Referenced by HandStateBase::OnEntry(), OnEntry(), HandStateBase::OnUpdate(), and OnUpdate().
ValidateMuzzleArray()
void ValidateMuzzleArray ()
Safety check and error message in case not set up correctly.
Definition at line 157 of file WeaponStableState.c.
  {
    // There is only one
    if (IsSingleState())
      return;
    bool failed = false;
    if (!failed)
    {
      foreach (MuzzleState state : m_muzzleHasBullet)
      {
        if (state == MuzzleState.U)
        {
          failed = true;
          break;
        }
      }
    }
    if (failed)
    {
      ErrorExSeverity severity = ErrorExSeverity.ERROR;
#ifdef DEVELOPER
      if (DayZGame.m_IsPreviewSpawn)
      {
        // we do not want VMEs when spawning the item in order to visualize it for preview in script console
        severity = ErrorExSeverity.INFO;
      }
#endif
      ErrorEx("Muzzle array validation has failed. Please set up the correct muzzle states by overriding InitMuzzleArray.", severity);
    }
  }
References ErrorEx, IsSingleState(), and m_muzzleHasBullet.
Referenced by WeaponStableState().
WeaponStableState()
void WeaponStableState (Weapon_Base w = NULL, WeaponStateBase parent = NULL, int anim_state = -1)
Definition at line 32 of file WeaponStableState.c.
  {
    m_animState = anim_state;
    InitMuzzleArray();
    ValidateMuzzleArray();
  }
References WeaponStableState::InitMuzzleArray(), m_animState, and ValidateMuzzleArray().
Referenced by Weapon_Base::InitStateMachine().
Variable Documentation
m_animState
enum MuzzleState m_animState
Referenced by SyncAnimState(), and WeaponStableState().
m_muzzleHasBullet
ref array<MuzzleState> m_muzzleHasBullet = new array<MuzzleState>()
Definition at line 30 of file WeaponStableState.c.
Referenced by GetMuzzleState(), GetMuzzleStateCount(), InitMuzzleArray(), WeaponStableState::InitMuzzleArray(), WeaponStateJammed::InitMuzzleArray(), IsChamberFiredOut(), IsChamberFull(), IsChamberValid(), and ValidateMuzzleArray().