DayZ: scripts/4_World/Entities/DayZPlayerUtils.c File Reference
DayZPlayerUtils.c File Reference
Classes
class ComponentCollisionBox
class ComponentCollisionCapsule
Enumerations
enum QueryFlags
Functions
enum QueryFlags EnableDebugDraw (bool pEnable)
enables debug draw in functions
static proto native void DrawDebugText (string text, vector pos, float size)
static proto native void DrawStartFrame ()
clear info - new draw starts
static proto native void DrawDebugBox (vector pos, float size, int color)
draws debug box (color=red)
static proto native bool DebugOverrideAnimationTranslation (string pAnimName, vector pTranslation)
overrides total animation translation
static proto native bool DebugOverrideAnimationRotation (string pAnimName, vector pRotation)
overrides total animation rotation
static proto native bool DebugOverrideAnimationSpeed (string pAnimName, float pSpeed)
overrides total animation speed
static proto float LinearRangeClamp (float pValueX, float pValueY, float pLimits[])
static proto native void PhysicsGetEntitiesInBox (vector min, vector max, notnull out array< EntityAI > entList)
returns entities overlapping/touching in AABB box -
static proto native void SceneGetEntitiesInBox (vector min, vector max, notnull out array< EntityAI > entList, int flags=QueryFlags.DYNAMIC)
returns entities overlapping/touching in AABB box -
static proto native void GetEntitiesInCone (vector pos, vector dir, float angle, float dist, float minHeigh, float maxHeight, out array< Object > entList)
static Object GetMeleeTarget (vector pos, vector dir, float angle, float dist, float minHeight, float maxHeight, EntityAI pToIgnore, array< typename > targetableObjects, out array< Object > allTargets=NULL)
returns fight target
static proto native bool PlayerCanChangeStance (DayZPlayer pPlayer, int pTargetStance, bool forceCheck=false)
static proto native bool FindMagazinesForAmmo (DayZPlayer player, string ammoTypeName, out array< Magazine > mags)
static Magazine SelectStoreCartridge (DayZPlayer player, Weapon_Base weapon, int muzzleIndex, Magazine exclude_mag, float damage, string magTypeName)
static bool HandleDropMagazine (DayZPlayer player, Magazine mag)
static bool HandleDropCartridge (DayZPlayer player, float damage, string cartTypeName, string magTypeName)
static bool HandleStoreCartridge (DayZPlayer player, Weapon_Base weapon, int muzzleIndex, float damage, string cartTypeName, string magTypeName, bool CanDrop=true)
static proto native bool InitComponentCollisions (Human player, array< ref ComponentCollisionBox > boxes, array< ref ComponentCollisionCapsule > capsules)
static proto native bool IsComponentCollisionInitialized ()
static proto native void ClearComponentCollisions ()
static proto native vector GetMemoryPointPositionBoneRelative (DayZPlayer pPlayer, int pBoneIndex, int pPointIndex)
static void InitPlayerComponentCollisions (Human player)
static int ConvertStanceMaskToStanceIdx (int stanceMask)
static EWaterLevels CheckWaterLevel (DayZPlayer pPlayer, out vector waterLevel)
void DayZPlayerUtils ()
cannot be instantiated
static void InitCachedEntList ()
Variables
NONE
STATIC
Static objects are included in the query.
DYNAMIC
Dynamic objects are included in the query.
ORIGIN_DISTANCE
Check only distance to object origins, not BB.
ONLY_ROADWAYS
Only roadways are included in the query.
static ref array< Object > m_CachedEntList
class ComponentCollisionBox EnableDebugDraw
Enumeration Type Documentation
QueryFlags
enum QueryFlags
Definition at line 1 of file DayZPlayerUtils.c.
{
  NONE,
  STATIC,
  DYNAMIC,
  ORIGIN_DISTANCE,
  ONLY_ROADWAYS,
}
Function Documentation
CheckWaterLevel()
static EWaterLevels CheckWaterLevel (DayZPlayer pPlayer, out vector waterLevel) static
if total water depth >= 1.5m && character is 1.5m in water
Definition at line 413 of file DayZPlayerUtils.c.
  {
    SHumanCommandSwimSettings swimData = pPlayer.GetDayZPlayerType().CommandSwimSettingsW();
    vector pp = pPlayer.GetPosition();
    waterLevel = HumanCommandSwim.WaterLevelCheck(pPlayer, pp);
    if (waterLevel[1] < swimData.m_fToCrouchLevel)
      return EWaterLevels.LEVEL_LOW;
    else if (waterLevel[1] >= swimData.m_fToCrouchLevel && waterLevel[1] < swimData.m_fToErectLevel)
      return EWaterLevels.LEVEL_CROUCH;
    else// if (waterLevel[1] >= swimData.m_fToErectLevel)
    {
      if (waterLevel[0] >= swimData.m_fWaterLevelIn && waterLevel[1] >= swimData.m_fWaterLevelIn)
        return EWaterLevels.LEVEL_SWIM_START;
      else
        return EWaterLevels.LEVEL_ERECT;
    }
  }
References HumanCommandSwim().
ClearComponentCollisions()
ClearComponentCollisions () static
ConvertStanceMaskToStanceIdx()
static int ConvertStanceMaskToStanceIdx (int stanceMask) static
Definition at line 387 of file DayZPlayerUtils.c.
  {
    switch (stanceMask)
    {
    case stanceMask &DayZPlayerConstants.STANCEMASK_PRONE:
      return DayZPlayerConstants.STANCEIDX_PRONE;
    case stanceMask &DayZPlayerConstants.STANCEMASK_CROUCH:
      return DayZPlayerConstants.STANCEIDX_CROUCH;
    case stanceMask &DayZPlayerConstants.STANCEMASK_ERECT:
      return DayZPlayerConstants.STANCEIDX_ERECT;
    case stanceMask &DayZPlayerConstants.STANCEMASK_RAISEDPRONE:
      return DayZPlayerConstants.STANCEIDX_RAISEDPRONE;
    case stanceMask &DayZPlayerConstants.STANCEMASK_RAISEDCROUCH:
      return DayZPlayerConstants.STANCEIDX_RAISEDCROUCH;
    case stanceMask &DayZPlayerConstants.STANCEMASK_RAISEDERECT:
      return DayZPlayerConstants.STANCEIDX_RAISEDERECT;
    }
    return -1;
  }
DayZPlayerUtils()
void DayZPlayerUtils () private
cannot be instantiated
Definition at line 441 of file DayZPlayerUtils.c.
{};
Referenced by ManBase::BrokenLegForceProne(), Can(), DayZPlayer::CanJump(), DayZPlayer::CanPickupHeavyItem(), DayZInfected::ChaseAttackLogic(), DayZPlayerImplementSwimming::CheckSwimmingStart(), ejectBulletAndStoreInMagazine(), EmoteBase::EmoteFBStanceCheck(), DayZInfected::FightAttackLogic(), HandleFightLogic(), HandleStoreCartridge(), DayZPlayerImplementSwimming::HandleSwimming(), InitPlayerComponentCollisions(), WeaponStateBase::OnAbort(), WeaponChambering_Base::OnAbort(), OnAbort(), WeaponStateBase::OnEntry(), ActionEmptyMagazine::OnExecuteServer(), WeaponStateBase::OnExit(), DayZPlayerImplementAiming::ProcessAimFilters(), VicinityItemManager::RefreshVicinityItems(), and SelectStoreCartridge().
DebugOverrideAnimationRotation()
static proto native bool DebugOverrideAnimationRotation (string pAnimName, vector pRotation) static
overrides total animation rotation
DebugOverrideAnimationSpeed()
static proto native bool DebugOverrideAnimationSpeed (string pAnimName, float pSpeed) static
overrides total animation speed
DebugOverrideAnimationTranslation()
static proto native bool DebugOverrideAnimationTranslation (string pAnimName, vector pTranslation) static
overrides total animation translation
DrawDebugBox()
static proto native void DrawDebugBox (vector pos, float size, int color) static
draws debug box (color=red)
DrawDebugText()
static proto native void DrawDebugText (string text, vector pos, float size) static
DrawStartFrame()
static proto native void DrawStartFrame () static
clear info - new draw starts
EnableDebugDraw()
enum QueryFlags EnableDebugDraw (bool pEnable)
enables debug draw in functions
FindMagazinesForAmmo()
static proto native bool FindMagazinesForAmmo (DayZPlayer player, string ammoTypeName, out array< Magazine > mags) static
GetEntitiesInCone()
static proto native void GetEntitiesInCone (vector pos, vector dir, float angle, float dist, float minHeigh, float maxHeight, out array< Object > entList) static
Referenced by GetMeleeTarget().
GetMeleeTarget()
static Object GetMeleeTarget (vector pos, vector dir, float angle, float dist, float minHeight, float maxHeight, EntityAI pToIgnore, array< typename > targetableObjects, out array< Object > allTargets = NULL) static
returns fight target
Definition at line 88 of file DayZPlayerUtils.c.
  {
    // Print("In: GetFightTarget");
    InitCachedEntList();
    GetEntitiesInCone(pos, dir, angle, dist, minHeight, maxHeight, m_CachedEntList);
    Object ret = NULL;
    Object obj = NULL;
    float retVal = dist * 2; // max value
    float tgAngle = Math.Tan(Math.DEG2RAD * angle);
    // DrawStartFrame();
    foreach (auto ent: m_CachedEntList)
    {
      if (ent == pToIgnore)
        continue;
      Class.CastTo(obj, ent);
      if (obj)
      {
        // check for targetable objects
        if (!obj.IsAnyInherited(targetableObjects))
          continue;
        if (!obj.IsAlive())
          continue;
      }
      vector entpos = ent.GetPosition();
      vector diff = entpos - pos;
      float cDistSq = diff.LengthSq();
      if (cDistSq > dist * dist) // out of distance
      {
        //Print("out of distance");
        continue;
      }
      float frontDist = diff[0] * dir[0] + diff[2] * dir[2];
      if (frontDist < 0.1) // behind the pos/dist half plane or further than dist
      {
        //Print("behind the pos/dist half plane or further than dist");
        continue;
      }
      vector project = pos + dir * frontDist;
      vector posdiff = Vector(project[0] - entpos[0], 0, project[2] - entpos[2]);
      float sideDist = posdiff.LengthSq();
      if (sideDist > tgAngle) // out of cone
      {
        //Print("out of cone");
        continue;
      }
      float sum = frontDist + sideDist;
      if (sum < retVal)
      {
        ret = ent;
        retVal = sum;
      }
      else
      {
        //Print("sum !< retVal");
      }
      // string txt     = project.ToString() + ": " + sum.ToString();
      // DrawDebugBox(project,0.01,0xffff0000);
      // DrawDebugBox(entpos,0.01,0xffff0000);
      // DrawDebugText(txt, project, 1.0);
      allTargets.Insert(ent);
    }
    return ret;
  }
References Class::CastTo(), Math::DEG2RAD, GetEntitiesInCone(), InitCachedEntList(), m_CachedEntList, Math::Tan(), and Vector().
GetMemoryPointPositionBoneRelative()
static proto native vector GetMemoryPointPositionBoneRelative (DayZPlayer pPlayer, int pBoneIndex, int pPointIndex) static
HandleDropCartridge()
static bool HandleDropCartridge (DayZPlayer player, float damage, string cartTypeName, string magTypeName) static
Definition at line 263 of file DayZPlayerUtils.c.
  {
    vector pos = player.GetPosition();
    EntityAI entityGround = player.SpawnEntityOnGroundPos(magTypeName, pos);
    if (entityGround && entityGround.IsInherited(Magazine))
    {
      Magazine magazineGround;
      if (Class.CastTo(magazineGround, entityGround))
      {
        magazineGround.ServerSetAmmoCount(0);
        magazineGround.SetHealth("", "", (1 - damage) * magazineGround.GetMaxHealth());
        if (magazineGround.ServerStoreCartridge(damage, cartTypeName))
          return true;
      }
    }
    return false;
  }
References Class::CastTo().
Referenced by HandleStoreCartridge().
HandleDropMagazine()
static bool HandleDropMagazine (DayZPlayer player, Magazine mag) static
We don't care if a valid transform couldn't be found, we just want to preferably use it instead of placing on the player
Definition at line 244 of file DayZPlayerUtils.c.
  {
    vector m4[4];
    Math3D.MatrixIdentity4(m4);
    GameInventory.PrepareDropEntityPos(player, mag, m4, false, -1);
    InventoryLocation il_mag_next = new InventoryLocation;
    il_mag_next.SetGround(mag, m4);
    InventoryLocation il_mag_curr = new InventoryLocation;
    if (mag.GetInventory().GetCurrentInventoryLocation(il_mag_curr))
      return GameInventory.LocationSyncMoveEntity(il_mag_curr, il_mag_next);
    else
    {
      Error("DayZPlayerUtils::HandleDropMagazine - cannot get current inv location of mag=" + mag);
      return false;
    }
  }
References Error(), GameInventory::LocationSyncMoveEntity(), Math3D::MatrixIdentity4(), and GameInventory::PrepareDropEntityPos().
HandleStoreCartridge()
static bool HandleStoreCartridge (DayZPlayer player, Weapon_Base weapon, int muzzleIndex, float damage, string cartTypeName, string magTypeName, bool CanDrop = true) static
find suitable heap / mag
create a new one in inventory
drop on ground
Definition at line 282 of file DayZPlayerUtils.c.
  {
    if (damage < 1.0)
    {
      array<Magazine> magazines = new array<Magazine>();
      if (DayZPlayerUtils.FindMagazinesForAmmo(player, magTypeName, magazines))
      {
        int healthLevel = -1;
        float testHeatlh = 1 - damage;
        foreach (Magazine magazine : magazines)
        {
          if (healthLevel == -1)
          {
            if (magazine.CanAddCartridges(1))
            {
              int numberOfHealthLevels = magazine.GetNumberOfHealthLevels();
              for (int i = 1; i < numberOfHealthLevels; i++)
              {
                if (magazine.GetHealthLevelValue(i) < testHeatlh)
                {
                  healthLevel = i - 1;
                  break;
                }
              }
            }
          }
          if (magazine.GetHealthLevel() == healthLevel)
          {
            if (magazine.ServerStoreCartridge(damage, cartTypeName))
              return true;
          }
        }
      }
      InventoryLocation inventoryLocation = new InventoryLocation();
      if (player.GetInventory().FindFirstFreeLocationForNewEntity(magTypeName, FindInventoryLocationType.ANY, inventoryLocation))
      {
        EntityAI entityInventory = SpawnEntity(magTypeName, inventoryLocation, ECE_IN_INVENTORY, RF_DEFAULT);
        if (entityInventory && entityInventory.IsInherited(Magazine))
        {
          Magazine magazineInventory;
          if (Class.CastTo(magazineInventory, entityInventory))
          {
            magazineInventory.ServerSetAmmoCount(0);
            magazineInventory.SetHealth("", "", (1 - damage) * magazineInventory.GetMaxHealth());
            if (magazineInventory.ServerStoreCartridge(damage, cartTypeName))
              return true;
          }
        }
      }
      if (CanDrop)
        return HandleDropCartridge(player, damage, cartTypeName, magTypeName);
    }
    return false;
  }
References Class::CastTo(), DayZPlayerUtils(), ECE_IN_INVENTORY, HandleDropCartridge(), RF_DEFAULT, and SpawnEntity().
InitCachedEntList()
static void InitCachedEntList () static private
Definition at line 444 of file DayZPlayerUtils.c.
  {
    if (m_CachedEntList == NULL)
      m_CachedEntList = new array<Object>;
    m_CachedEntList.Clear();
  }
References m_CachedEntList.
Referenced by GetMeleeTarget().
InitComponentCollisions()
static proto native bool InitComponentCollisions (Human player, array< ref ComponentCollisionBox > boxes, array< ref ComponentCollisionCapsule > capsules) static
InitPlayerComponentCollisions()
static void InitPlayerComponentCollisions (Human player) static
Definition at line 364 of file DayZPlayerUtils.c.
  {
    if (IsComponentCollisionInitialized())
      Error("DayZPlayerUtils.InitComponentCollisions: already initialized!");
    array<ref ComponentCollisionBox> b = new array<ref ComponentCollisionBox>;
    b.Insert(new ComponentCollisionBox(0.40, 0.31, 0.31, "Pelvis", "Spine2"));
    b.Insert(new ComponentCollisionBox(0.40, 0.31, 0.31, "Spine3", "Neck"));
    array<ref ComponentCollisionCapsule> c = new array<ref ComponentCollisionCapsule>;
    c.Insert(new ComponentCollisionCapsule(0.11, "Neck1", "Head"));
    c.Insert(new ComponentCollisionCapsule(0.09, "LeftArm", "LeftArmRoll"));
    c.Insert(new ComponentCollisionCapsule(0.08, "LeftForeArm", "LeftHand"));
    c.Insert(new ComponentCollisionCapsule(0.09, "RightArm", "RightArmRoll"));
    c.Insert(new ComponentCollisionCapsule(0.08, "RightForeArm", "RightHand"));
    c.Insert(new ComponentCollisionCapsule(0.11, "LeftUpLeg", "LeftUpLegRoll"));
    c.Insert(new ComponentCollisionCapsule(0.10, "LeftLeg", "LeftFoot"));
    c.Insert(new ComponentCollisionCapsule(0.11, "RightUpLeg", "RightUpLegRoll"));
    c.Insert(new ComponentCollisionCapsule(0.10, "RightLeg", "RightFoot"));
    DayZPlayerUtils.InitComponentCollisions(player, b, c);
  }
References DayZPlayerUtils(), Error(), and IsComponentCollisionInitialized().
IsComponentCollisionInitialized()
IsComponentCollisionInitialized () static
Returns
true if already initialized
Referenced by InitPlayerComponentCollisions().
LinearRangeClamp()
static proto float LinearRangeClamp (float pValueX, float pValueY, float pLimits[]) static
pLimits in form Xvalue, Ymin, Ymax, Xvalue1, Ymin1, Ymax1, .... sample 0, 0, 5, 1, 2, 3, 2, 0, 1 for X <= 0 it clamps Y to Rangle (0,5) for X == 0.5 it clamps Y to Rangle (1,4) for X == 1 it clamps Y to Rangle (2,3) for X == 1.5 it clamps Y to Rangle (1,2) for X >= 2 it clamps Y to Rangle (0,1)
PhysicsGetEntitiesInBox()
static proto native void PhysicsGetEntitiesInBox (vector min, vector max, notnull out array< EntityAI > entList) static
returns entities overlapping/touching in AABB box -
PlayerCanChangeStance()
static proto native bool PlayerCanChangeStance (DayZPlayer pPlayer, int pTargetStance, bool forceCheck = false) static
SceneGetEntitiesInBox()
static proto native void SceneGetEntitiesInBox (vector min, vector max, notnull out array< EntityAI > entList, int flags = QueryFlags.DYNAMIC) static
returns entities overlapping/touching in AABB box -
SelectStoreCartridge()
static Magazine SelectStoreCartridge (DayZPlayer player, Weapon_Base weapon, int muzzleIndex, Magazine exclude_mag, float damage, string magTypeName) static
Definition at line 195 of file DayZPlayerUtils.c.
  {
    if (damage < 1.0)
    {
      // find suitable heap / mag (but not the excluded one)
      ref array<Magazine> mags = new array<Magazine>;
      if (DayZPlayerUtils.FindMagazinesForAmmo(player, magTypeName, mags))
      {
        int sz = mags.Count();
        for (int i = 0; i < sz; ++i)
        {
          Magazine mag_i = mags.Get(i);
          if (mag_i != exclude_mag && mag_i.CanAddCartridges(1))
            return mag_i;
        }
      }
      // create a new one in inventory
      InventoryLocation inv_loc = new InventoryLocation;
      if (player.GetInventory().FindFirstFreeLocationForNewEntity(magTypeName, FindInventoryLocationType.ANY, inv_loc))
      {
        EntityAI eai_inv = SpawnEntity(magTypeName, inv_loc, ECE_IN_INVENTORY, RF_DEFAULT);
        if (eai_inv && eai_inv.IsInherited(Magazine))
        {
          Magazine mag_inv;
          if (Class.CastTo(mag_inv, eai_inv))
          {
            mag_inv.ServerSetAmmoCount(0);
            return mag_inv;
          }
        }
      }
    }
    vector pos = player.GetPosition();
    EntityAI eai_gnd = player.SpawnEntityOnGroundPos(magTypeName, pos);
    if (eai_gnd && eai_gnd.IsInherited(Magazine))
    {
      Magazine mag_gnd;
      if (Class.CastTo(mag_gnd, eai_gnd))
      {
        mag_gnd.ServerSetAmmoCount(0);
        return mag_gnd;
      }
    }
    return NULL;
  }
References Class::CastTo(), DayZPlayerUtils(), ECE_IN_INVENTORY, RF_DEFAULT, and SpawnEntity().
Variable Documentation
DYNAMIC
@ DYNAMIC
Dynamic objects are included in the query.
Definition at line 4 of file DayZPlayerUtils.c.
EnableDebugDraw
class ComponentCollisionBox EnableDebugDraw private
m_CachedEntList
ref array<Object> m_CachedEntList static private
Definition at line 437 of file DayZPlayerUtils.c.
Referenced by GetMeleeTarget(), and InitCachedEntList().
NONE
@ NONE
Definition at line 0 of file DayZPlayerUtils.c.
ONLY_ROADWAYS
ONLY_ROADWAYS
Only roadways are included in the query.
Definition at line 8 of file DayZPlayerUtils.c.
ORIGIN_DISTANCE
ORIGIN_DISTANCE
Check only distance to object origins, not BB.
Definition at line 6 of file DayZPlayerUtils.c.
STATIC
@ STATIC
Static objects are included in the query.
Definition at line 2 of file DayZPlayerUtils.c.