DayZ: ModifierBase Class Reference
ModifierBase Class Reference
Inherited by AntibioticsMdfr [private], AreaExposureMdfr [private], BleedingCheckMdfr [private], BlindedMdfr [private], BloodRegenMdfr [private], BoneRegenMdfr [private], BrainDiseaseMdfr [private], BrokenArmsMdfr [private], BrokenLegsMdfr [private], BurningMdfr [private], CharcoalMdfr [private], CholeraMdfr [private], CommonColdMdfr [private], ContaminationStage1Mdfr [private], ContaminationStage2Mdfr [private], ContaminationStage3Mdfr [private], DisinfectionMdfr [private], DrowningMdfr [private], EpinephrineMdfr [private], FatigueMdfr [private], FeverMdfr [private], FliesMdfr [private], HealthMdfr [private], HealthRegenMdfr [private], HeartAttackMdfr [private], HeatBufferMdfr [private], HeatComfortMdfr [private], HemolyticReactionMdfr [private], HungerMdfr [private], ImmuneSystemMdfr [private], ImmunityBoost [private], InfluenzaMdfr [private], MaskMdfr [private], MorphineMdfr [private], PainKillersMdfr [private], PoisoningMdfr [private], SalineMdfr [private], SalmonellaMdfr [private], ShockDamageMdfr [private], ShockMdfr [private], StomachMdfr [private], StuffedStomachMdfr [private], TestDiseaseMdfr [private], TestingMdfr [private], ThirstMdfr [private], ToxicityMdfr [private], TremorMdfr [private], UnconsciousnessMdfr [private], VomitStuffedMdfr [private], WetMdfr [private], WoundInfectStage1Mdfr [private], WoundInfectStage2Mdfr [private], and WoundInfectionMdfr [private].
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnReconnect (PlayerBase player)
override string GetDebugText ()
override string GetDebugTextSimple ()
override void OnTick (PlayerBase player, float deltaT)
Detailed Description
Definition at line 3 of file BreathVapourMdfr.c.
Member Function Documentation
ActivateCondition()
override bool ModifierBase::ActivateCondition (PlayerBase player) inline private
Definition at line 15 of file BreathVapourMdfr.c.
  {
    return true;
  }
Referenced by Tick().
DeactivateCondition()
override bool ModifierBase::DeactivateCondition (PlayerBase player) inline private
Definition at line 20 of file BreathVapourMdfr.c.
  {
    return false;
  }
Referenced by Tick().
GetDebugText()
override string ModifierBase::GetDebugText () inline private
Definition at line 30 of file BreathVapourMdfr.c.
  {
    //return m_Player.GetStatHeatComfort().Get().ToString();
  }
GetDebugTextSimple()
override string ModifierBase::GetDebugTextSimple () inline private
Definition at line 35 of file BreathVapourMdfr.c.
  {
    //return m_Player.GetStatHeatComfort().Get().ToString();
  }
Init()
override void ModifierBase::Init () inline private
Definition at line 5 of file BreathVapourMdfr.c.
  {
    m_TrackActivatedTime = false;
    m_ID = eModifiers.MDF_BREATH_VAPOUR;
    m_TickIntervalInactive = DEFAULT_TICK_TIME_INACTIVE;
    m_TickIntervalActive = 6;
    DisableDeactivateCheck();
  }
References DEFAULT_TICK_TIME_INACTIVE, DisableDeactivateCheck(), m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
Referenced by InitBase().
OnReconnect()
override void ModifierBase::OnReconnect (PlayerBase player) inline private
Definition at line 25 of file BreathVapourMdfr.c.
  {
  }
Referenced by Activate().
OnTick()
override void ModifierBase::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 41 of file BreathVapourMdfr.c.
  {
    if (!player.m_Environment.IsTemperatureSet())
      return;
    float air_temperature = player.m_Environment.GetTemperature();
    int level = 0;//default
    if (MiscGameplayFunctions.IsValueInRange(air_temperature, PlayerConstants.BREATH_VAPOUR_THRESHOLD_HIGH, PlayerConstants.BREATH_VAPOUR_THRESHOLD_LOW))
    {
      float value = Math.InverseLerp(PlayerConstants.BREATH_VAPOUR_THRESHOLD_LOW, PlayerConstants.BREATH_VAPOUR_THRESHOLD_HIGH, air_temperature);
      value = Math.Clamp(value, 0, 1);
      level = Math.Round(Math.Lerp(1, BREATH_VAPOUR_LEVEL_MAX, value));
    }
    else if (air_temperature < PlayerConstants.BREATH_VAPOUR_THRESHOLD_HIGH)
      level = BREATH_VAPOUR_LEVEL_MAX;
    if (level != player.m_BreathVapour)
    {
      player.m_BreathVapour = level;
      player.SetSynchDirty();
    }
  }
References BREATH_VAPOUR_LEVEL_MAX, PlayerConstants::BREATH_VAPOUR_THRESHOLD_HIGH, PlayerConstants::BREATH_VAPOUR_THRESHOLD_LOW, Math::Clamp(), Math::InverseLerp(), Math::Lerp(), and Math::Round().
Referenced by Tick().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/PlayerModifiers/Modifiers/BreathVapourMdfr.c