DayZ: ScriptConsoleGeneralTab Class Reference
ScriptConsoleGeneralTab Class Reference
Protected Member Functions
void ScriptConsoleGeneralTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void ~ScriptConsoleGeneralTab ()
void Init ()
void RefreshDateWidgets (int year, int month, int day, int hour, int minute)
bool IsLocationNameAvailable (string name)
void LateInit ()
void Teleport (PlayerBase player, vector position)
void RefreshLocations ()
string GetCurrentLocationName ()
vector GetCurrentLocationPos ()
void GetCurrentPositionData (out LocationParams data)
bool IsCurrentPositionCustom ()
int GetCurrentPositionIndex ()
bool IsCurrentPositionValid ()
void UpdateHudDebugSetting ()
void RefreshPlayerPosEditBoxes ()
void UpdateTime (bool slider_used)
void UpdateMousePos ()
void SetMapPos (vector pos)
vector GetMapPos ()
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnKeyDown (Widget w, int x, int y, int key)
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
override bool OnDoubleClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override void OnRPCEx (int rpc_type, ParamsReadContext ctx)
override void Update (float timeslice)
Protected Attributes
const string DEFAULT_POS_XYZ = "<1,2,3>"
vector m_MapPos
bool m_PlayerPosRefreshBlocked
ref array< ref RemotePlayerStatDebug > m_PlayerDebugStats = new array<ref RemotePlayerStatDebug>
MissionGameplay m_MissionGameplay
PluginDeveloper m_Developer
SliderWidget m_TimeSlider
ref Timer m_LateInit = new Timer()
bool m_UpdatePlayerPositions
EditBoxWidget m_TeleportX
EditBoxWidget m_TeleportY
EditBoxWidget m_TeleportXYZ
EditBoxWidget m_DateYear
EditBoxWidget m_DateMonth
EditBoxWidget m_DateDay
EditBoxWidget m_DateHour
EditBoxWidget m_DateMinute
ButtonWidget m_LocationAddButton
ButtonWidget m_LocationRemoveButton
ButtonWidget m_TeleportButton
ButtonWidget m_ButtonCopyPos
ButtonWidget m_DiagDrawButton
ButtonWidget m_DiagToggleButton
CheckBoxWidget m_LogsEnabled
CheckBoxWidget m_HudDCharStats
CheckBoxWidget m_HudDCharLevels
CheckBoxWidget m_HudDCharStomach
CheckBoxWidget m_HudDCharModifiers
CheckBoxWidget m_HudDCharAgents
CheckBoxWidget m_HudDCharDebug
CheckBoxWidget m_HudDFreeCamCross
CheckBoxWidget m_HudDVersion
CheckBoxWidget m_ShowOthers
CheckBoxWidget m_HudDTemperature
MapWidget m_DebugMapWidget
TextWidget m_PlayerCurPos
TextWidget m_MouseCurPos
TextWidget m_PlayerMouseDiff
TextListboxWidget m_DiagToggleTextListbox
TextListboxWidget m_PositionsListbox
TextListboxWidget m_DiagDrawmodeTextListbox
TextListboxWidget m_HelpTextListboxWidget
Static Protected Attributes
static float DEBUG_MAP_ZOOM = 1
static bool SHOW_OTHERS = 0
Static Private Attributes
static int m_ObjectsScope = 2
Additional Inherited Members
Private Member Functions inherited from ScriptConsoleTabBase
void ScriptConsoleTabBase (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void Init (int id)
int GetID ()
Widget GetRoot ()
bool IsSelected ()
void Select (bool select, ScriptConsoleTabBase selectedHandler)
void OnSelected ()
void Show (bool show, ScriptConsoleTabBase selectedHandler)
Widget GetButton ()
void Update (float timeslice)
bool OnChange (Widget w, int x, int y, bool finished)
bool OnClick (Widget w, int x, int y, int button)
bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
bool OnKeyDown (Widget w, int x, int y, int key)
bool OnDoubleClick (Widget w, int x, int y, int button)
void OnRPCEx (int rpc_type, ParamsReadContext ctx)
bool OnMouseButtonDown (Widget w, int x, int y, int button)
bool OnKeyPress (Widget w, int x, int y, int key)
void AddItemToClipboard (TextListboxWidget text_listbox_widget)
Private Attributes inherited from ScriptConsoleTabBase
int m_Id
bool m_IsSelected
Widget m_ParentRoot
Widget m_Root
Widget m_Button
ScriptConsole m_ScriptConsole
ScriptConsoleTabBase m_Parent
PluginConfigDebugProfile m_ConfigDebugProfile
PluginConfigDebugProfileFixed m_ConfigDebugProfileFixed
Detailed Description
Definition at line 1 of file ScriptConsoleGeneralTab.c.
Constructor & Destructor Documentation
ScriptConsoleGeneralTab()
void ScriptConsoleGeneralTab::ScriptConsoleGeneralTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent = null) inline protected
Definition at line 64 of file ScriptConsoleGeneralTab.c.
  {
    m_MissionGameplay = MissionGameplay.Cast(GetGame().GetMission());
    m_DiagToggleTextListbox = TextListboxWidget.Cast(root.FindAnyWidget("DiagToggle"));
    m_DiagToggleButton = ButtonWidget.Cast(root.FindAnyWidget("DiagToggleButton"));
    m_DiagDrawmodeTextListbox = TextListboxWidget.Cast(root.FindAnyWidget("DiagDrawmode"));
    m_DiagDrawButton = ButtonWidget.Cast(root.FindAnyWidget("DiagDrawButton"));
    m_DebugMapWidget = MapWidget.Cast(root.FindAnyWidget("MapWidget"));
    m_PositionsListbox = TextListboxWidget.Cast(root.FindAnyWidget("PositionsList"));
    m_TeleportButton = ButtonWidget.Cast(root.FindAnyWidget("ButtonTeleport"));
    m_ButtonCopyPos = ButtonWidget.Cast(root.FindAnyWidget("Button_CopyPos"));
    m_TeleportX = EditBoxWidget.Cast(root.FindAnyWidget("TeleportX"));
    m_TeleportY = EditBoxWidget.Cast(root.FindAnyWidget("TeleportY"));
    m_TeleportXYZ = EditBoxWidget.Cast(root.FindAnyWidget("TeleportXYZ"));
    m_PlayerCurPos = TextWidget.Cast(root.FindAnyWidget("PlayerPosLabel"));
    m_PlayerMouseDiff = TextWidget.Cast(root.FindAnyWidget("PlayerMouseDiff"));
    m_MouseCurPos = TextWidget.Cast(root.FindAnyWidget("MousePosLabel"));
    m_LogsEnabled = CheckBoxWidget.Cast(root.FindAnyWidget("cbx_LogsEnabled"));
    m_HudDCharStats = CheckBoxWidget.Cast(root.FindAnyWidget("cbx_CharacterStats"));
    m_HudDCharLevels = CheckBoxWidget.Cast(root.FindAnyWidget("cbx_CharacterLevels"));
    m_HudDCharStomach = CheckBoxWidget.Cast(root.FindAnyWidget("cbx_CharacterStomach"));
    m_HudDCharModifiers = CheckBoxWidget.Cast(root.FindAnyWidget("cbx_CharacterModifiers"));
    m_HudDCharAgents = CheckBoxWidget.Cast(root.FindAnyWidget("cbx_CharacterAgents"));
    m_HudDCharDebug = CheckBoxWidget.Cast(root.FindAnyWidget("cbx_CharacterDebug"));
    m_HudDFreeCamCross = CheckBoxWidget.Cast(root.FindAnyWidget("cbx_FreeCamCross"));
    m_HudDTemperature = CheckBoxWidget.Cast(root.FindAnyWidget("cbx_Temp"));
    m_HudDVersion = CheckBoxWidget.Cast(root.FindAnyWidget("cbx_Version"));
    m_LocationAddButton = ButtonWidget.Cast(root.FindAnyWidget("AddButton"));
    //m_LocationAddButton.SetHandler(ToolTipEventHandler.GetInstance());
    m_LocationRemoveButton = ButtonWidget.Cast(root.FindAnyWidget("RemoveButton"));
    m_TimeSlider = SliderWidget.Cast(root.FindAnyWidget("TimeSlider"));
    m_DateYear = EditBoxWidget.Cast(root.FindAnyWidget("DateYear"));
    m_DateMonth = EditBoxWidget.Cast(root.FindAnyWidget("DateMonth"));
    m_DateDay = EditBoxWidget.Cast(root.FindAnyWidget("DateDay"));
    m_DateHour = EditBoxWidget.Cast(root.FindAnyWidget("DateHour"));
    m_DateMinute = EditBoxWidget.Cast(root.FindAnyWidget("DateMinute"));
    m_ShowOthers = CheckBoxWidget.Cast(root.FindAnyWidget("ShowOthersCheckbox"));
    m_HelpTextListboxWidget = TextListboxWidget.Cast(root.FindAnyWidget("HelpTextListboxWidget"));
    m_Developer = PluginDeveloper.Cast(GetPlugin(PluginDeveloper));
    Init();
    LateInit();
  }
References GetGame(), GetPlugin(), Init(), LateInit(), m_ButtonCopyPos, m_DateDay, m_DateHour, m_DateMinute, m_DateMonth, m_DateYear, m_DebugMapWidget, m_Developer, m_DiagDrawButton, m_DiagDrawmodeTextListbox, m_DiagToggleButton, m_DiagToggleTextListbox, m_HelpTextListboxWidget, m_HudDCharAgents, m_HudDCharDebug, m_HudDCharLevels, m_HudDCharModifiers, m_HudDCharStats, m_HudDCharStomach, m_HudDFreeCamCross, m_HudDTemperature, m_HudDVersion, m_LocationAddButton, m_LocationRemoveButton, m_LogsEnabled, m_MissionGameplay, m_MouseCurPos, m_PlayerCurPos, m_PlayerMouseDiff, m_PositionsListbox, m_ShowOthers, m_TeleportButton, m_TeleportX, m_TeleportXYZ, m_TeleportY, and m_TimeSlider.
~ScriptConsoleGeneralTab()
void ScriptConsoleGeneralTab::~ScriptConsoleGeneralTab () inline protected
Definition at line 119 of file ScriptConsoleGeneralTab.c.
  {
    DEBUG_MAP_ZOOM = m_DebugMapWidget.GetScale();
    PluginRemotePlayerDebugClient plugin_remote_client = PluginRemotePlayerDebugClient.Cast(GetPlugin(PluginRemotePlayerDebugClient));
    if (SHOW_OTHERS && plugin_remote_client && GetGame().GetPlayer())
      plugin_remote_client.RequestPlayerInfo(PlayerBase.Cast(GetGame().GetPlayer()), 0);
  }
References DEBUG_MAP_ZOOM, GetGame(), GetPlayer(), GetPlugin(), MapWidget::GetScale(), m_DebugMapWidget, and SHOW_OTHERS.
Member Function Documentation
GetCurrentLocationName()
string ScriptConsoleGeneralTab::GetCurrentLocationName () inline protected
Definition at line 243 of file ScriptConsoleGeneralTab.c.
  {
    string name;
    LocationParams prms;
    GetCurrentPositionData(prms);
    if (prms)
      name = prms.param1;
    return name;
  }
References GetCurrentPositionData(), and name.
Referenced by OnClick().
GetCurrentLocationPos()
vector ScriptConsoleGeneralTab::GetCurrentLocationPos () inline protected
Definition at line 252 of file ScriptConsoleGeneralTab.c.
  {
    LocationParams prms;
    GetCurrentPositionData(prms);
    if (prms)
      return prms.param3;
    else
      return vector.Zero;
  }
References GetCurrentPositionData(), and vector::Zero.
Referenced by OnClick(), OnDoubleClick(), and OnItemSelected().
GetCurrentPositionData()
void ScriptConsoleGeneralTab::GetCurrentPositionData (out LocationParams data) inline protected
Definition at line 262 of file ScriptConsoleGeneralTab.c.
  {
    if (m_PositionsListbox.GetSelectedRow() != -1)
      m_PositionsListbox.GetItemData(m_PositionsListbox.GetSelectedRow(), 0, data);
  }
References m_PositionsListbox.
Referenced by GetCurrentLocationName(), GetCurrentLocationPos(), and IsCurrentPositionCustom().
GetCurrentPositionIndex()
int ScriptConsoleGeneralTab::GetCurrentPositionIndex () inline protected
Definition at line 278 of file ScriptConsoleGeneralTab.c.
  {
    return m_PositionsListbox.GetSelectedRow();
  }
References m_PositionsListbox.
Referenced by OnClick(), and OnItemSelected().
GetMapPos()
vector ScriptConsoleGeneralTab::GetMapPos () inline protected
Definition at line 363 of file ScriptConsoleGeneralTab.c.
  {
    return m_MapPos;
  }
References m_MapPos.
Referenced by OnClick(), and Update().
Init()
void ScriptConsoleGeneralTab::Init () inline protected
Definition at line 128 of file ScriptConsoleGeneralTab.c.
  {
    // Update checkbox Character Values
    m_HudDCharStats.SetChecked(m_ConfigDebugProfile.GetCharacterStatsVisible());
    m_HudDCharLevels.SetChecked(m_ConfigDebugProfile.GetCharacterLevelsVisible());
    m_HudDCharStomach.SetChecked(m_ConfigDebugProfile.GetCharacterStomachVisible());
    m_HudDCharModifiers.SetChecked(m_ConfigDebugProfile.GetCharacterModifiersVisible());
    m_HudDCharAgents.SetChecked(m_ConfigDebugProfile.GetCharacterAgentsVisible());
    m_HudDCharDebug.SetChecked(m_ConfigDebugProfile.GetCharacterDebugVisible());
    m_HudDFreeCamCross.SetChecked(m_ConfigDebugProfile.GetFreeCameraCrosshairVisible());
    m_HudDVersion.SetChecked(m_ConfigDebugProfile.GetVersionVisible());
    m_HudDTemperature.SetChecked(m_ConfigDebugProfile.GetTempVisible());
    m_LogsEnabled.SetChecked(m_ConfigDebugProfile.GetLogsEnabled());
    TStringArray diag_names = new TStringArray;
    GetGame().GetDiagModeNames(diag_names);
    int i;
    for (i = 0; i < diag_names.Count(); i++)
      m_DiagToggleTextListbox.AddItem(diag_names.Get(i), NULL, 0);
    GetGame().GetDiagDrawModeNames(diag_names);
    for (i = 0; i < diag_names.Count(); i++)
      m_DiagDrawmodeTextListbox.AddItem(diag_names.Get(i), NULL, 0);
    RefreshLocations();
    UpdateHudDebugSetting();
    if (GetGame().GetPlayer())
    {
      m_DebugMapWidget.SetScale(DEBUG_MAP_ZOOM);
      m_DebugMapWidget.SetMapPos(GetGame().GetPlayer().GetWorldPosition());
    }
    m_TeleportXYZ.SetText(DEFAULT_POS_XYZ);
    m_LateInit.Run(0.05, this, "LateInit", null, false);
    int year, month, day, hour, minute;
    GetGame().GetWorld().GetDate(year, month, day, hour, minute);
    RefreshDateWidgets(year, month, day, hour, minute);
  }
References DEBUG_MAP_ZOOM, DEFAULT_POS_XYZ, GetGame(), GetPlayer(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_DebugMapWidget, m_DiagDrawmodeTextListbox, m_DiagToggleTextListbox, m_HudDCharAgents, m_HudDCharDebug, m_HudDCharLevels, m_HudDCharModifiers, m_HudDCharStats, m_HudDCharStomach, m_HudDFreeCamCross, m_HudDTemperature, m_HudDVersion, m_LateInit, m_LogsEnabled, m_TeleportXYZ, RefreshDateWidgets(), RefreshLocations(), MapWidget::SetMapPos(), MapWidget::SetScale(), and UpdateHudDebugSetting().
Referenced by ScriptConsoleGeneralTab().
IsCurrentPositionCustom()
bool ScriptConsoleGeneralTab::IsCurrentPositionCustom () inline protected
Definition at line 268 of file ScriptConsoleGeneralTab.c.
  {
    LocationParams prms;
    GetCurrentPositionData(prms);
    if (prms)
      return prms.param2;
    else
      return false;
  }
References GetCurrentPositionData().
IsCurrentPositionValid()
bool ScriptConsoleGeneralTab::IsCurrentPositionValid () inline protected
Definition at line 283 of file ScriptConsoleGeneralTab.c.
  {
    return (m_PositionsListbox.GetSelectedRow() != -1);
  }
References m_PositionsListbox.
Referenced by OnClick(), and OnItemSelected().
IsLocationNameAvailable()
bool ScriptConsoleGeneralTab::IsLocationNameAvailable (string name) inline protected
Definition at line 185 of file ScriptConsoleGeneralTab.c.
  {
    int count = m_PositionsListbox.GetNumItems();
    for (int i = 0; i < count; i++)
    {
      LocationParams data;
      m_PositionsListbox.GetItemData(i, 0, data);
      if (data.param1 == name)
        return false;
    }
    return true;
  }
References m_PositionsListbox, and name.
LateInit()
void ScriptConsoleGeneralTab::LateInit () inline protected
Definition at line 199 of file ScriptConsoleGeneralTab.c.
  {
    m_ShowOthers.SetChecked(SHOW_OTHERS);
    if (m_ConfigDebugProfile)
    {
      int prevRow = m_ConfigDebugProfile.GetSpawnLocIndex();
      if (prevRow < m_PositionsListbox.GetNumItems())
        m_PositionsListbox.SelectRow(prevRow);
    }
    PluginRemotePlayerDebugClient plugin_remote_client = PluginRemotePlayerDebugClient.Cast(GetPlugin(PluginRemotePlayerDebugClient));
    if (SHOW_OTHERS && plugin_remote_client && GetGame().GetPlayer())
    {
      plugin_remote_client.RequestPlayerInfo(PlayerBase.Cast(GetGame().GetPlayer()), 1);
      m_UpdatePlayerPositions = 1;
    }
  }
References GetGame(), GetPlayer(), GetPlugin(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_PositionsListbox, m_ShowOthers, m_UpdatePlayerPositions, and SHOW_OTHERS.
Referenced by ScriptConsoleGeneralTab().
OnChange()
override bool ScriptConsoleGeneralTab::OnChange (Widget w, int x, int y, bool finished) inline protected
Definition at line 400 of file ScriptConsoleGeneralTab.c.
  {
    super.OnChange(w, x, y, finished);
    if (w == m_ShowOthers && GetGame().GetPlayer())
    {
      PluginRemotePlayerDebugClient plugin_remote_client = PluginRemotePlayerDebugClient.Cast(GetPlugin(PluginRemotePlayerDebugClient));
      if (m_ShowOthers.IsChecked())
      {
        plugin_remote_client.RequestPlayerInfo(PlayerBase.Cast(GetGame().GetPlayer()), 1);
        m_UpdatePlayerPositions = 1;
        SHOW_OTHERS = true;
      }
      else
      {
        plugin_remote_client.RequestPlayerInfo(PlayerBase.Cast(GetGame().GetPlayer()), 0);
        m_UpdatePlayerPositions = 0;
        SHOW_OTHERS = false;
      }
      return true;
    }
    else if (w == m_TimeSlider || w == m_DateDay || w == m_DateYear || w == m_DateMonth || w == m_DateHour || w == m_DateMinute)
    {
      UpdateTime(w == m_TimeSlider);
      return true;
    }
    return false;
  }
References GetGame(), GetPlayer(), GetPlugin(), m_DateDay, m_DateHour, m_DateMinute, m_DateMonth, m_DateYear, m_ShowOthers, m_TimeSlider, m_UpdatePlayerPositions, SHOW_OTHERS, UpdateTime(), x, and y.
OnClick()
override bool ScriptConsoleGeneralTab::OnClick (Widget w, int x, int y, int button) inline protected
Definition at line 477 of file ScriptConsoleGeneralTab.c.
  {
    super.OnClick(w, x, y, button);
    int i;
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    PluginDeveloper module_dev = PluginDeveloper.Cast(GetPlugin(PluginDeveloper));
    if (w == m_PositionsListbox)
    {
      vector position = GetCurrentLocationPos();
      m_TeleportX.SetText(position[0].ToString());
      m_TeleportY.SetText(position[2].ToString());
      if (IsCurrentPositionValid())
        m_ConfigDebugProfile.SetSpawnLocIndex(GetCurrentPositionIndex());
      return true;
    }
    else if (w == m_TeleportButton)
    {
      float pos_x = m_TeleportX.GetText().ToFloat();
      float pos_z = m_TeleportY.GetText().ToFloat();
      float pos_y = GetGame().SurfaceY(pos_x, pos_z);
      vector v = Vector(pos_x, pos_y, pos_z);
      if (m_TeleportXYZ.GetText() != "" && m_TeleportXYZ.GetText() != DEFAULT_POS_XYZ)
      {
        string pos = m_TeleportXYZ.GetText();
        v = pos.BeautifiedToVector();
      }
      Teleport(player, v);
      return true;
    }
    else if (w == m_ButtonCopyPos)
    {
      GetGame().CopyToClipboard(GetMapPos().ToString());
      return true;
    }
    else if (w == m_LogsEnabled)
    {
      //Log("m_LogsEnabled: "+ToString(m_LogsEnabled.IsChecked()));
      if (m_ConfigDebugProfile)
      {
        m_ConfigDebugProfile.SetLogsEnabled(m_LogsEnabled.IsChecked());
        LogManager.SetLogsEnabled(m_LogsEnabled.IsChecked());
      }
      return true;
    }
    else if (w == m_HudDCharStats)
    {
      if (m_ConfigDebugProfile)
        m_ConfigDebugProfile.SetCharacterStatsVisible(m_HudDCharStats.IsChecked());
      // Refresh UI by new settings
      m_MissionGameplay.GetHudDebug().RefreshByLocalProfile();
      return true;
    }
    else if (w == m_HudDCharLevels)
    {
      if (m_ConfigDebugProfile)
        m_ConfigDebugProfile.SetCharacterLevelsVisible(m_HudDCharLevels.IsChecked());
      // Refresh UI by new settings
      m_MissionGameplay.GetHudDebug().RefreshByLocalProfile();
      return true;
    }
    else if (w == m_HudDCharStomach)
    {
      if (m_ConfigDebugProfile)
        m_ConfigDebugProfile.SetCharacterStomachVisible(m_HudDCharStomach.IsChecked());
      // Refresh UI by new settings
      m_MissionGameplay.GetHudDebug().RefreshByLocalProfile();
      return true;
    }
    else if (w == m_HudDVersion)
    {
      if (m_ConfigDebugProfile)
        m_ConfigDebugProfile.SetVersionVisible(m_HudDVersion.IsChecked());
      // Refresh UI by new settings
      m_MissionGameplay.GetHudDebug().RefreshByLocalProfile();
      return true;
    }
    else if (w == m_HudDTemperature)
    {
      if (m_ConfigDebugProfile)
        m_ConfigDebugProfile.SetTempVisible(m_HudDTemperature.IsChecked());
      // Refresh UI by new settings
      m_MissionGameplay.GetHudDebug().RefreshByLocalProfile();
      return true;
    }
    else if (w == m_HudDCharModifiers)
    {
      if (m_ConfigDebugProfile)
        m_ConfigDebugProfile.SetCharacterModifiersVisible(m_HudDCharModifiers.IsChecked());
      // Refresh UI by new settings
      m_MissionGameplay.GetHudDebug().RefreshByLocalProfile();
      return true;
    }
    else if (w == m_HudDCharAgents)
    {
      if (m_ConfigDebugProfile)
        m_ConfigDebugProfile.SetCharacterAgentsVisible(m_HudDCharAgents.IsChecked());
      // Refresh UI by new settings
      m_MissionGameplay.GetHudDebug().RefreshByLocalProfile();
      return true;
    }
    else if (w == m_HudDCharDebug)
    {
      if (m_ConfigDebugProfile)
        m_ConfigDebugProfile.SetCharacterDebugVisible(m_HudDCharDebug.IsChecked());
      // Refresh UI by new settings
      m_MissionGameplay.GetHudDebug().RefreshByLocalProfile();
      return true;
    }
    else if (w == m_HudDFreeCamCross)
    {
      if (m_ConfigDebugProfile)
        m_ConfigDebugProfile.SetFreeCameraCrosshairVisible(m_HudDFreeCamCross.IsChecked());
      // Refresh UI by new settings
      m_MissionGameplay.GetHudDebug().RefreshByLocalProfile();
      GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(GetGame().GetMission().RefreshCrosshairVisibility);
      return true;
    }
    else if (w == m_DiagToggleButton)
    {
      int toggle_row_index = m_DiagToggleTextListbox.GetSelectedRow();
      bool toggle_state = GetGame().GetDiagModeEnable(toggle_row_index);
      GetGame().SetDiagModeEnable(toggle_row_index, !toggle_state);
      return true;
    }
    else if (w == m_DiagDrawButton)
    {
      int draw_row_index = m_DiagDrawmodeTextListbox.GetSelectedRow();
      GetGame().SetDiagDrawMode(draw_row_index);
      return true;
    }
    // TOUCHED THIS
    else if (w == m_LocationAddButton)
    {
      ScriptConsoleAddLocation menu = ScriptConsoleAddLocation.Cast(g_Game.GetUIManager().EnterScriptedMenu(MENU_LOC_ADD, m_ScriptConsole));
      menu.SetPosition(GetMapPos());
      return true;
    }
    else if (w == m_LocationRemoveButton)
    {
      m_ConfigDebugProfile.CustomLocationsRemove(GetCurrentLocationName());
      RefreshLocations();
      return true;
    }
    return false;
  }
References string::BeautifiedToVector(), CALL_CATEGORY_SYSTEM, DEFAULT_POS_XYZ, g_Game, GetCurrentLocationName(), GetCurrentLocationPos(), GetCurrentPositionIndex(), GetGame(), GetMapPos(), GetPlayer(), GetPlugin(), IsCurrentPositionValid(), m_ButtonCopyPos, ScriptConsoleTabBase::m_ConfigDebugProfile, m_DiagDrawButton, m_DiagDrawmodeTextListbox, m_DiagToggleButton, m_DiagToggleTextListbox, m_HudDCharAgents, m_HudDCharDebug, m_HudDCharLevels, m_HudDCharModifiers, m_HudDCharStats, m_HudDCharStomach, m_HudDFreeCamCross, m_HudDTemperature, m_HudDVersion, m_LocationAddButton, m_LocationRemoveButton, m_LogsEnabled, m_MissionGameplay, m_PositionsListbox, ScriptConsoleTabBase::m_ScriptConsole, m_TeleportButton, m_TeleportX, m_TeleportXYZ, m_TeleportY, MENU_LOC_ADD, RefreshCrosshairVisibility(), RefreshLocations(), LogManager::SetLogsEnabled(), Teleport(), ToString(), Vector(), x, and y.
OnDoubleClick()
override bool ScriptConsoleGeneralTab::OnDoubleClick (Widget w, int x, int y, int button) inline protected
Definition at line 446 of file ScriptConsoleGeneralTab.c.
  {
    super.OnDoubleClick(w, x, y, button);
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (w == m_DebugMapWidget)
    {
      vector screen_to_map = m_DebugMapWidget.ScreenToMap(Vector(x, y, 0));
      float pos_y_a = GetGame().SurfaceY(screen_to_map[0], screen_to_map[2]);
      float pos_y_b = GetGame().SurfaceRoadY(screen_to_map[0], screen_to_map[2]);
      float pos_y = Math.Max(pos_y_a, pos_y_b);
      screen_to_map[1] = pos_y;
      m_Developer.Teleport(player, screen_to_map);
      return true;
    }
    if (w == m_PositionsListbox)
    {
      vector position = GetCurrentLocationPos();
      Teleport(player, position);
      return true;
    }
    if (w == m_TeleportXYZ)
    {
      EditBoxWidget.Cast(w).SetText("");
      return true;
    }
    return false;
  }
References GetCurrentLocationPos(), GetGame(), GetPlayer(), m_DebugMapWidget, m_Developer, m_PositionsListbox, m_TeleportXYZ, Math::Max(), MapWidget::ScreenToMap(), Teleport(), Vector(), x, and y.
OnItemSelected()
override bool ScriptConsoleGeneralTab::OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline protected
Definition at line 429 of file ScriptConsoleGeneralTab.c.
  {
    super.OnItemSelected(w, x, y, row, column, oldRow, oldColumn);
    if (w == m_PositionsListbox)
    {
      vector position = GetCurrentLocationPos();
      m_TeleportX.SetText(position[0].ToString());
      m_TeleportY.SetText(position[2].ToString());
      m_TeleportXYZ.SetText(position.ToString());
      if (IsCurrentPositionValid())
        m_ConfigDebugProfile.SetSpawnLocIndex(GetCurrentPositionIndex());
      return true;
    }
    return false;
  }
References GetCurrentLocationPos(), GetCurrentPositionIndex(), IsCurrentPositionValid(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_PositionsListbox, m_TeleportX, m_TeleportXYZ, m_TeleportY, ToString(), x, and y.
OnKeyDown()
override bool ScriptConsoleGeneralTab::OnKeyDown (Widget w, int x, int y, int key) inline protected
Definition at line 394 of file ScriptConsoleGeneralTab.c.
  {
    super.OnKeyDown(w, x, y, key);
    return false;
  }
References x, and y.
OnMouseButtonDown()
override bool ScriptConsoleGeneralTab::OnMouseButtonDown (Widget w, int x, int y, int button) inline protected
Definition at line 368 of file ScriptConsoleGeneralTab.c.
  {
    super.OnMouseButtonDown(w, x, y, button);
    if (w == m_DebugMapWidget)
    {
      if (button == 0)
      {
        m_PlayerPosRefreshBlocked = true;
        int mouseX, mouseY;
        GetMousePos(mouseX, mouseY);
        vector mousePos, worldPos;
        mousePos[0] = mouseX;
        mousePos[1] = mouseY;
        worldPos = m_DebugMapWidget.ScreenToMap(mousePos);
        worldPos[1] = GetGame().SurfaceY(worldPos[0], worldPos[2]);
        SetMapPos(worldPos);
      }
      else if (button == 1 && GetGame().GetPlayer())
        SetMapPos(GetGame().GetPlayer().GetWorldPosition());
    }
    return true;
  }
References GetGame(), GetMousePos(), GetPlayer(), m_DebugMapWidget, m_PlayerPosRefreshBlocked, MapWidget::ScreenToMap(), SetMapPos(), x, and y.
OnRPCEx()
override void ScriptConsoleGeneralTab::OnRPCEx (int rpc_type, ParamsReadContext ctx) inline protected
Definition at line 652 of file ScriptConsoleGeneralTab.c.
  {
    super.OnRPCEx(rpc_type, ctx);
#ifdef DIAG_DEVELOPER
    switch (rpc_type)
    {
    case ERPCs.DEV_PLAYER_DEBUG_DATA:
    {
      ctx.Read(m_PlayerDebugStats);
      break;
    }
    }
#endif
  }
References m_PlayerDebugStats.
RefreshDateWidgets()
void ScriptConsoleGeneralTab::RefreshDateWidgets (int year, int month, int day, int hour, int minute) inline protected
Definition at line 174 of file ScriptConsoleGeneralTab.c.
  {
    float time01 = Math.InverseLerp(0, 60 * 24 - 1, (hour * 60) + minute);
    m_DateYear.SetText(year.ToString());
    m_DateMonth.SetText(month.ToString());
    m_DateDay.SetText(day.ToString());
    m_DateHour.SetText(hour.ToString());
    m_DateMinute.SetText(minute.ToString());
    m_TimeSlider.SetCurrent(time01 * 100);
  }
References Math::InverseLerp(), m_DateDay, m_DateHour, m_DateMinute, m_DateMonth, m_DateYear, and m_TimeSlider.
Referenced by Init(), and UpdateTime().
RefreshLocations()
void ScriptConsoleGeneralTab::RefreshLocations () inline protected
Definition at line 226 of file ScriptConsoleGeneralTab.c.
  {
    m_PositionsListbox.ClearItems();
    array<ref LocationParams> locData = new array<ref LocationParams>;
    m_ConfigDebugProfile.GetLocationsData(locData, true);
    m_ConfigDebugProfileFixed.GetLocationsData(locData, false);
    foreach (LocationParams dta: locData)
    {
      string name = dta.param1;
      if (!dta.param2)
        name = "[" + name + "]";
      m_PositionsListbox.AddItem(name, dta, 0);
    }
  }
References ScriptConsoleTabBase::m_ConfigDebugProfile, ScriptConsoleTabBase::m_ConfigDebugProfileFixed, m_PositionsListbox, and name.
Referenced by Init(), and OnClick().
RefreshPlayerPosEditBoxes()
void ScriptConsoleGeneralTab::RefreshPlayerPosEditBoxes () inline protected
Definition at line 290 of file ScriptConsoleGeneralTab.c.
  {
    if (!GetGame().GetPlayer())
      return;
    vector playerPos = GetGame().GetPlayer().GetPosition();
    SetMapPos(playerPos);
  }
References GetGame(), GetPlayer(), and SetMapPos().
Referenced by Update().
SetMapPos()
void ScriptConsoleGeneralTab::SetMapPos (vector pos) inline protected
Definition at line 357 of file ScriptConsoleGeneralTab.c.
  {
    m_MapPos = pos;
    m_PlayerCurPos.SetText("Pos: " + MiscGameplayFunctions.TruncateToS(pos[0]) + ", " + MiscGameplayFunctions.TruncateToS(pos[1]) + ", " + MiscGameplayFunctions.TruncateToS(pos[2]));
  }
References m_MapPos, and m_PlayerCurPos.
Referenced by OnMouseButtonDown(), and RefreshPlayerPosEditBoxes().
Teleport()
void ScriptConsoleGeneralTab::Teleport (PlayerBase player, vector position) inline protected
Definition at line 219 of file ScriptConsoleGeneralTab.c.
  {
    if (position[1] == 0)
      position[1] = GetGame().SurfaceY(position[0], position[2]);
    m_Developer.Teleport(player, position);
  }
References GetGame(), and m_Developer.
Referenced by OnClick(), and OnDoubleClick().
Update()
override void ScriptConsoleGeneralTab::Update (float timeslice) inline protected
Definition at line 667 of file ScriptConsoleGeneralTab.c.
  {
    super.Update(timeslice);
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    m_DebugMapWidget.ClearUserMarks();
    if (m_UpdatePlayerPositions)
    {
      foreach (RemotePlayerStatDebug rpd: m_PlayerDebugStats)
      {
        if (rpd.m_Player != player)
        {
          vector dir = rpd.m_Pos - player.GetWorldPosition();
          dir[1] = 0;
          string dist = ((int)dir.Length()).ToString();
          string text = rpd.m_Name + " " + dist + "m.";
          m_DebugMapWidget.AddUserMark(rpd.m_Pos, text, COLOR_BLUE, "\\dz\\gear\\navigation\\data\\map_tree_ca.paa");
        }
      }
    }
    if (player)
    {
      vector playerPos = player.GetWorldPosition();
      m_DebugMapWidget.AddUserMark(playerPos, "You", COLOR_RED, "\\dz\\gear\\navigation\\data\\map_tree_ca.paa");
      if (playerPos != GetMapPos())
        m_DebugMapWidget.AddUserMark(GetMapPos(), "Pos", COLOR_BLUE, "\\dz\\gear\\navigation\\data\\map_tree_ca.paa");
    }
    UpdateMousePos();
    if (!m_PlayerPosRefreshBlocked)
      RefreshPlayerPosEditBoxes();
    foreach (MapMarker marker: ScriptConsole.m_MarkedEntities)
      m_DebugMapWidget.AddUserMark(marker.GetMarkerPos(), marker.GetMarkerText(), marker.GetMarkerColor(), MapMarkerTypes.GetMarkerTypeFromID(marker.GetMarkerIcon()));
  }
References MapWidget::AddUserMark(), MapWidget::ClearUserMarks(), COLOR_BLUE, COLOR_RED, GetGame(), GetMapPos(), MapMarkerTypes::GetMarkerTypeFromID(), GetPlayer(), vector::Length(), m_DebugMapWidget, m_PlayerDebugStats, m_PlayerPosRefreshBlocked, m_UpdatePlayerPositions, RefreshPlayerPosEditBoxes(), RemotePlayerStatDebug(), ToString(), and UpdateMousePos().
UpdateHudDebugSetting()
void ScriptConsoleGeneralTab::UpdateHudDebugSetting () protected
Referenced by Init().
UpdateMousePos()
void ScriptConsoleGeneralTab::UpdateMousePos () inline protected
Definition at line 334 of file ScriptConsoleGeneralTab.c.
  {
    int x, y;
    GetMousePos(x, y);
    vector mousePos, worldPos;
    mousePos[0] = x;
    mousePos[1] = y;
    worldPos = m_DebugMapWidget.ScreenToMap(mousePos);
    worldPos[1] = GetGame().SurfaceY(worldPos[0], worldPos[2]);
    if (m_MouseCurPos)
      m_MouseCurPos.SetText("Mouse: " + MiscGameplayFunctions.TruncateToS(worldPos[0]) + ", " + MiscGameplayFunctions.TruncateToS(worldPos[1]) + ", " + MiscGameplayFunctions.TruncateToS(worldPos[2]));
    if (m_PlayerMouseDiff && GetGame().GetPlayer())
    {
      vector playerPos = GetGame().GetPlayer().GetWorldPosition();
      //playerPos[1] = 0;
      float dst = (worldPos - playerPos).Length();
      m_PlayerMouseDiff.SetText("Distance: " + MiscGameplayFunctions.TruncateToS(dst));
    }
  }
References GetGame(), GetMousePos(), GetPlayer(), m_DebugMapWidget, m_MouseCurPos, m_PlayerMouseDiff, MapWidget::ScreenToMap(), x, and y.
Referenced by Update().
UpdateTime()
void ScriptConsoleGeneralTab::UpdateTime (bool slider_used) inline protected
Definition at line 299 of file ScriptConsoleGeneralTab.c.
  {
    Param5<int, int, int, int, int> p5 = new Param5<int, int, int, int, int>(0, 0, 0, 0, 0);
    int year, month, day, hour, minute;
    year = m_DateYear.GetText().ToInt();
    month = m_DateMonth.GetText().ToInt();
    day = m_DateDay.GetText().ToInt();
    if (slider_used)
    {
      int time_minutes = Math.Lerp(0, (24 * 60) - 1, m_TimeSlider.GetCurrent() / 100);
      hour = time_minutes / 60;
      minute = time_minutes % 60;
    }
    else
    {
      hour = m_DateHour.GetText().ToInt();
      minute = m_DateMinute.GetText().ToInt();
    }
    p5.param1 = year;
    p5.param2 = month;
    p5.param3 = day;
    p5.param4 = hour;
    p5.param5 = minute;
    RefreshDateWidgets(year, month, day, hour, minute);
    GetGame().GetWorld().SetDate(year, month, day, hour, minute);
    if (GetGame().GetPlayer())
      GetGame().GetPlayer().RPCSingleParam(ERPCs.DEV_RPC_SET_TIME, p5, true);
  }
References GetGame(), GetPlayer(), Math::Lerp(), m_DateDay, m_DateHour, m_DateMinute, m_DateMonth, m_DateYear, m_TimeSlider, and RefreshDateWidgets().
Referenced by OnChange().
Member Data Documentation
DEBUG_MAP_ZOOM
float ScriptConsoleGeneralTab::DEBUG_MAP_ZOOM = 1 static protected
Definition at line 5 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), and ~ScriptConsoleGeneralTab().
DEFAULT_POS_XYZ
const string ScriptConsoleGeneralTab::DEFAULT_POS_XYZ = "<1,2,3>" protected
Definition at line 8 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), and OnClick().
m_ButtonCopyPos
ButtonWidget ScriptConsoleGeneralTab::m_ButtonCopyPos protected
Definition at line 35 of file ScriptConsoleGeneralTab.c.
Referenced by OnClick(), and ScriptConsoleGeneralTab().
m_DateDay
EditBoxWidget ScriptConsoleGeneralTab::m_DateDay protected
Definition at line 28 of file ScriptConsoleGeneralTab.c.
Referenced by OnChange(), RefreshDateWidgets(), ScriptConsoleGeneralTab(), and UpdateTime().
m_DateHour
EditBoxWidget ScriptConsoleGeneralTab::m_DateHour protected
Definition at line 29 of file ScriptConsoleGeneralTab.c.
Referenced by OnChange(), RefreshDateWidgets(), ScriptConsoleGeneralTab(), and UpdateTime().
m_DateMinute
EditBoxWidget ScriptConsoleGeneralTab::m_DateMinute protected
Definition at line 30 of file ScriptConsoleGeneralTab.c.
Referenced by OnChange(), RefreshDateWidgets(), ScriptConsoleGeneralTab(), and UpdateTime().
m_DateMonth
EditBoxWidget ScriptConsoleGeneralTab::m_DateMonth protected
Definition at line 27 of file ScriptConsoleGeneralTab.c.
Referenced by OnChange(), RefreshDateWidgets(), ScriptConsoleGeneralTab(), and UpdateTime().
m_DateYear
EditBoxWidget ScriptConsoleGeneralTab::m_DateYear protected
Definition at line 26 of file ScriptConsoleGeneralTab.c.
Referenced by OnChange(), RefreshDateWidgets(), ScriptConsoleGeneralTab(), and UpdateTime().
m_DebugMapWidget
MapWidget ScriptConsoleGeneralTab::m_DebugMapWidget protected
Definition at line 52 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), OnDoubleClick(), OnMouseButtonDown(), ScriptConsoleGeneralTab(), Update(), UpdateMousePos(), and ~ScriptConsoleGeneralTab().
m_Developer
PluginDeveloper ScriptConsoleGeneralTab::m_Developer protected
Definition at line 15 of file ScriptConsoleGeneralTab.c.
Referenced by OnDoubleClick(), ScriptConsoleGeneralTab(), and Teleport().
m_DiagDrawButton
ButtonWidget ScriptConsoleGeneralTab::m_DiagDrawButton protected
Definition at line 36 of file ScriptConsoleGeneralTab.c.
Referenced by OnClick(), and ScriptConsoleGeneralTab().
m_DiagDrawmodeTextListbox
TextListboxWidget ScriptConsoleGeneralTab::m_DiagDrawmodeTextListbox protected
Definition at line 60 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_DiagToggleButton
ButtonWidget ScriptConsoleGeneralTab::m_DiagToggleButton protected
Definition at line 37 of file ScriptConsoleGeneralTab.c.
Referenced by OnClick(), and ScriptConsoleGeneralTab().
m_DiagToggleTextListbox
TextListboxWidget ScriptConsoleGeneralTab::m_DiagToggleTextListbox protected
Definition at line 58 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HelpTextListboxWidget
TextListboxWidget ScriptConsoleGeneralTab::m_HelpTextListboxWidget protected
Definition at line 61 of file ScriptConsoleGeneralTab.c.
Referenced by ScriptConsoleGeneralTab().
m_HudDCharAgents
CheckBoxWidget ScriptConsoleGeneralTab::m_HudDCharAgents protected
Definition at line 44 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDCharDebug
CheckBoxWidget ScriptConsoleGeneralTab::m_HudDCharDebug protected
Definition at line 45 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDCharLevels
CheckBoxWidget ScriptConsoleGeneralTab::m_HudDCharLevels protected
Definition at line 41 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDCharModifiers
CheckBoxWidget ScriptConsoleGeneralTab::m_HudDCharModifiers protected
Definition at line 43 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDCharStats
CheckBoxWidget ScriptConsoleGeneralTab::m_HudDCharStats protected
Definition at line 40 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDCharStomach
CheckBoxWidget ScriptConsoleGeneralTab::m_HudDCharStomach protected
Definition at line 42 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDFreeCamCross
CheckBoxWidget ScriptConsoleGeneralTab::m_HudDFreeCamCross protected
Definition at line 46 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDTemperature
CheckBoxWidget ScriptConsoleGeneralTab::m_HudDTemperature protected
Definition at line 51 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDVersion
CheckBoxWidget ScriptConsoleGeneralTab::m_HudDVersion protected
Definition at line 47 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_LateInit
ref Timer ScriptConsoleGeneralTab::m_LateInit = new Timer() protected
Definition at line 18 of file ScriptConsoleGeneralTab.c.
Referenced by Init().
m_LocationAddButton
ButtonWidget ScriptConsoleGeneralTab::m_LocationAddButton protected
Definition at line 32 of file ScriptConsoleGeneralTab.c.
Referenced by OnClick(), and ScriptConsoleGeneralTab().
m_LocationRemoveButton
ButtonWidget ScriptConsoleGeneralTab::m_LocationRemoveButton protected
Definition at line 33 of file ScriptConsoleGeneralTab.c.
Referenced by OnClick(), and ScriptConsoleGeneralTab().
m_LogsEnabled
CheckBoxWidget ScriptConsoleGeneralTab::m_LogsEnabled protected
Definition at line 39 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_MapPos
vector ScriptConsoleGeneralTab::m_MapPos protected
Definition at line 9 of file ScriptConsoleGeneralTab.c.
Referenced by GetMapPos(), and SetMapPos().
m_MissionGameplay
MissionGameplay ScriptConsoleGeneralTab::m_MissionGameplay protected
Definition at line 14 of file ScriptConsoleGeneralTab.c.
Referenced by OnClick(), and ScriptConsoleGeneralTab().
m_MouseCurPos
TextWidget ScriptConsoleGeneralTab::m_MouseCurPos protected
Definition at line 55 of file ScriptConsoleGeneralTab.c.
Referenced by ScriptConsoleGeneralTab(), and UpdateMousePos().
m_ObjectsScope
int ScriptConsoleGeneralTab::m_ObjectsScope = 2 static private
Definition at line 3 of file ScriptConsoleGeneralTab.c.
m_PlayerCurPos
TextWidget ScriptConsoleGeneralTab::m_PlayerCurPos protected
Definition at line 54 of file ScriptConsoleGeneralTab.c.
Referenced by ScriptConsoleGeneralTab(), and SetMapPos().
m_PlayerDebugStats
ref array<ref RemotePlayerStatDebug> ScriptConsoleGeneralTab::m_PlayerDebugStats = new array<ref RemotePlayerStatDebug> protected
Definition at line 12 of file ScriptConsoleGeneralTab.c.
Referenced by OnRPCEx(), and Update().
m_PlayerMouseDiff
TextWidget ScriptConsoleGeneralTab::m_PlayerMouseDiff protected
Definition at line 56 of file ScriptConsoleGeneralTab.c.
Referenced by ScriptConsoleGeneralTab(), and UpdateMousePos().
m_PlayerPosRefreshBlocked
bool ScriptConsoleGeneralTab::m_PlayerPosRefreshBlocked protected
Definition at line 10 of file ScriptConsoleGeneralTab.c.
Referenced by OnMouseButtonDown(), and Update().
m_PositionsListbox
TextListboxWidget ScriptConsoleGeneralTab::m_PositionsListbox protected
Definition at line 59 of file ScriptConsoleGeneralTab.c.
Referenced by GetCurrentPositionData(), GetCurrentPositionIndex(), IsCurrentPositionValid(), IsLocationNameAvailable(), LateInit(), OnClick(), OnDoubleClick(), OnItemSelected(), RefreshLocations(), and ScriptConsoleGeneralTab().
m_ShowOthers
CheckBoxWidget ScriptConsoleGeneralTab::m_ShowOthers protected
Definition at line 49 of file ScriptConsoleGeneralTab.c.
Referenced by LateInit(), OnChange(), and ScriptConsoleGeneralTab().
m_TeleportButton
ButtonWidget ScriptConsoleGeneralTab::m_TeleportButton protected
Definition at line 34 of file ScriptConsoleGeneralTab.c.
Referenced by OnClick(), and ScriptConsoleGeneralTab().
m_TeleportX
EditBoxWidget ScriptConsoleGeneralTab::m_TeleportX protected
Definition at line 23 of file ScriptConsoleGeneralTab.c.
Referenced by OnClick(), OnItemSelected(), and ScriptConsoleGeneralTab().
m_TeleportXYZ
EditBoxWidget ScriptConsoleGeneralTab::m_TeleportXYZ protected
Definition at line 25 of file ScriptConsoleGeneralTab.c.
Referenced by Init(), OnClick(), OnDoubleClick(), OnItemSelected(), and ScriptConsoleGeneralTab().
m_TeleportY
EditBoxWidget ScriptConsoleGeneralTab::m_TeleportY protected
Definition at line 24 of file ScriptConsoleGeneralTab.c.
Referenced by OnClick(), OnItemSelected(), and ScriptConsoleGeneralTab().
m_TimeSlider
SliderWidget ScriptConsoleGeneralTab::m_TimeSlider protected
Definition at line 17 of file ScriptConsoleGeneralTab.c.
Referenced by OnChange(), RefreshDateWidgets(), ScriptConsoleGeneralTab(), and UpdateTime().
m_UpdatePlayerPositions
bool ScriptConsoleGeneralTab::m_UpdatePlayerPositions protected
Definition at line 20 of file ScriptConsoleGeneralTab.c.
Referenced by LateInit(), OnChange(), and Update().
SHOW_OTHERS
bool ScriptConsoleGeneralTab::SHOW_OTHERS = 0 static protected
Definition at line 6 of file ScriptConsoleGeneralTab.c.
Referenced by LateInit(), OnChange(), and ~ScriptConsoleGeneralTab().
The documentation for this class was generated from the following file:
scripts/5_Mission/GUI/ScriptConsoleGeneralTab.c