DayZ: WarmthNotfr Class Reference
WarmthNotfr Class Reference
Protected Member Functions
DSLevelsTemp DetermineLevel (float value, float m_warning_treshold, float m_critical_treshold, float m_empty_treshold, float p_warning_treshold, float p_critical_treshold, float p_empty_treshold)
override void DisplayTendency (float delta)
float GetObservedValue ()
Private Member Functions
void WarmthNotfr (NotifiersManager manager)
override int GetNotifierType ()
Private Member Functions inherited from NotifierBase
int CalculateTendency (float delta, float inctresholdlow, float inctresholdmed, float inctresholdhigh, float dectresholdlow, float dectresholdmed, float dectresholdhigh)
eBadgeLevel DetermineBadgeLevel (float value, float lvl_1, float lvl_2, float lvl_3)
void DisplayBadge ()
void HideBadge ()
float GetObservedValue ()
Private Attributes
const float DEC_TRESHOLD_LOW = 0
const float DEC_TRESHOLD_MED = -0.2
const float DEC_TRESHOLD_HIGH = -0.3
const float INC_TRESHOLD_LOW = 0
const float INC_TRESHOLD_MED = 0.2
const float INC_TRESHOLD_HIGH = 0.3
Detailed Description
Definition at line 1 of file WarmthNotfr.c.
Constructor & Destructor Documentation
WarmthNotfr()
void WarmthNotfr::WarmthNotfr (NotifiersManager manager) inline private
Definition at line 10 of file WarmthNotfr.c.
  {
    m_TendencyBufferSize = 6;
  }
References NotifierBase::m_TendencyBufferSize.
Member Function Documentation
DetermineLevel()
DSLevelsTemp WarmthNotfr::DetermineLevel (float value, float m_warning_treshold, float m_critical_treshold, float m_empty_treshold, float p_warning_treshold, float p_critical_treshold, float p_empty_treshold) inline protected
Definition at line 21 of file WarmthNotfr.c.
  {
    DSLevelsTemp level = DSLevelsTemp.NORMAL;
    if (value < 0)
    {
      if (value < m_warning_treshold) level = DSLevelsTemp.WARNING_MINUS;
      if (value < m_critical_treshold) level = DSLevelsTemp.CRITICAL_MINUS;
      if (value <= m_empty_treshold) level = DSLevelsTemp.BLINKING_MINUS;
    }
    else
    {
      if (value > p_warning_treshold) level = DSLevelsTemp.WARNING_PLUS;
      if (value > p_critical_treshold) level = DSLevelsTemp.CRITICAL_PLUS;
      if (value >= p_empty_treshold) level = DSLevelsTemp.BLINKING_PLUS;
    }
    return level;
  }
Referenced by DisplayTendency().
DisplayTendency()
override void WarmthNotfr::DisplayTendency (float delta) inline protected
Definition at line 41 of file WarmthNotfr.c.
  {
    int tendency = CalculateTendency(delta, INC_TRESHOLD_LOW, INC_TRESHOLD_MED, INC_TRESHOLD_HIGH, DEC_TRESHOLD_LOW, DEC_TRESHOLD_MED, DEC_TRESHOLD_HIGH);
    DSLevelsTemp level = DetermineLevel(GetObservedValue(), PlayerConstants.THRESHOLD_HEAT_COMFORT_MINUS_WARNING, PlayerConstants.THRESHOLD_HEAT_COMFORT_MINUS_CRITICAL, PlayerConstants.THRESHOLD_HEAT_COMFORT_MINUS_EMPTY, PlayerConstants.THRESHOLD_HEAT_COMFORT_PLUS_WARNING, PlayerConstants.THRESHOLD_HEAT_COMFORT_PLUS_CRITICAL, PlayerConstants.THRESHOLD_HEAT_COMFORT_PLUS_EMPTY);
    DisplayElementTendency dis_elm = DisplayElementTendency.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_TDCY_TEMPERATURE));
    if (dis_elm)
    {
      dis_elm.SetTendency(tendency);
      dis_elm.SetSeriousnessLevel(level);
    }
  }
References NotifierBase::CalculateTendency(), DEC_TRESHOLD_HIGH, DEC_TRESHOLD_LOW, DEC_TRESHOLD_MED, DetermineLevel(), GetElement(), GetObservedValue(), NotifierBase::GetVirtualHud(), INC_TRESHOLD_HIGH, INC_TRESHOLD_LOW, INC_TRESHOLD_MED, PlayerConstants::THRESHOLD_HEAT_COMFORT_MINUS_CRITICAL, PlayerConstants::THRESHOLD_HEAT_COMFORT_MINUS_EMPTY, PlayerConstants::THRESHOLD_HEAT_COMFORT_MINUS_WARNING, PlayerConstants::THRESHOLD_HEAT_COMFORT_PLUS_CRITICAL, PlayerConstants::THRESHOLD_HEAT_COMFORT_PLUS_EMPTY, and PlayerConstants::THRESHOLD_HEAT_COMFORT_PLUS_WARNING.
GetNotifierType()
override int WarmthNotfr::GetNotifierType () inline private
Definition at line 15 of file WarmthNotfr.c.
  {
    return eNotifiers.NTF_WARMTH;
  }
GetObservedValue()
float WarmthNotfr::GetObservedValue () inline protected
Definition at line 56 of file WarmthNotfr.c.
  {
    return m_Player.GetStatHeatComfort().Get();
  }
References NotifierBase::m_Player.
Referenced by DisplayTendency().
Member Data Documentation
DEC_TRESHOLD_HIGH
const float WarmthNotfr::DEC_TRESHOLD_HIGH = -0.3 private
Definition at line 5 of file WarmthNotfr.c.
Referenced by DisplayTendency().
DEC_TRESHOLD_LOW
const float WarmthNotfr::DEC_TRESHOLD_LOW = 0 private
Definition at line 3 of file WarmthNotfr.c.
Referenced by DisplayTendency().
DEC_TRESHOLD_MED
const float WarmthNotfr::DEC_TRESHOLD_MED = -0.2 private
Definition at line 4 of file WarmthNotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_HIGH
const float WarmthNotfr::INC_TRESHOLD_HIGH = 0.3 private
Definition at line 8 of file WarmthNotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_LOW
const float WarmthNotfr::INC_TRESHOLD_LOW = 0 private
Definition at line 6 of file WarmthNotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_MED
const float WarmthNotfr::INC_TRESHOLD_MED = 0.2 private
Definition at line 7 of file WarmthNotfr.c.
Referenced by DisplayTendency().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/PlayerNotifiers/Notifiers/WarmthNotfr.c