DayZ: Clothing Class Reference
Clothing Class Reference
Protected Member Functions
void InitGlobalExclusionValues ()
void CheckParent ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnWork (float consumed_energy)
void OnLightCreated ()
void CreateHeadtorchLight ()
void AttachLightOnHead (EntityAI person)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void SetActions ()
override bool IsLightSource ()
override ItemBase GetLightSourceItem ()
override void OnInvisibleSet (bool invisible)
Private Member Functions
override bool CanPutInCargo (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override void SetActions ()
override void SwitchItemSelectionTextureEx (EItemManipulationContext context, Param par=null)
void Headtorch_ColorBase ()
override void SetActions ()
Private Attributes
HeadtorchLight m_Light
ref Timer m_Timer
Static Private Attributes
static int REFLECTOR_ID = 4
static int GLASS_ID = 5
static string LIGHT_OFF_GLASS = "dz\\characters\\headgear\\data\\HeadTorchGlass.rvmat"
static string LIGHT_OFF_REFLECTOR = "dz\\characters\\headgear\\data\\HeadTorch.rvmat"
static string LIGHT_ON_GLASS = "dz\\characters\\headgear\\data\\HeadTorchGlass_on.rvmat"
static string LIGHT_ON_GLASS_RED = "dz\\characters\\headgear\\data\\HeadTorchGlass_on_red.rvmat"
static string LIGHT_ON_REFLECTOR = "dz\\characters\\headgear\\data\\HeadTorch_ON.rvmat"
static string LIGHT_ON_REFLECTOR_RED = "dz\\characters\\headgear\\data\\HeadTorch_ON_red.rvmat"
static vector m_OnHeadLocalPos = Vector(0.12, 0.15, 0)
static vector m_OnHeadLocalOri = Vector(0, 90, 0)
static string m_OffHeadLightPoint = "beamStart"
static string m_OffHeadLightTarget = "beamEnd"
Detailed Description
Definition at line 1 of file Armband_ColorBase.c.
Member Function Documentation
AttachLightOnHead()
void Clothing::AttachLightOnHead (EntityAI person) inline protected
Definition at line 153 of file Headtorch_ColorBase.c.
  {
    if (person.IsPlayer())
    {
      PlayerBase player = PlayerBase.Cast(person);
      int boneIdx = player.GetBoneIndexByName("Head");
      if (boneIdx != -1)
      {
        if (m_Light.GetParent())
          m_Light.DetachFromParent();
        m_Light.SetPosition(m_OnHeadLocalPos);
        m_Light.SetOrientation(m_OnHeadLocalOri);
        player.AddChild(m_Light, boneIdx);
      }
    }
    else if (person.IsZombie())
    {
      if (m_Light.GetParent())
        m_Light.DetachFromParent();
      m_Light.SetPosition(m_OnHeadLocalPos);
      m_Light.SetOrientation(m_OnHeadLocalOri);
      person.AddChild(m_Light, 17);
    }
  }
References m_Light.
CanPutAsAttachment()
override bool Clothing::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 11 of file Armband_ColorBase.c.
  {
    if (!super.CanPutAsAttachment(parent)) return false;
    if (GetQuantity() <= 1)
      return true;
    return false;
  }
References GetQuantity().
CanPutInCargo()
override bool Clothing::CanPutInCargo (EntityAI parent) inline private
Definition at line 3 of file Armband_ColorBase.c.
  {
    if (!super.CanPutInCargo(parent)) return false;
    if (GetNumberOfItems() == 0 || !parent || parent.IsMan())
      return true;
    return false;
  }
References GetNumberOfItems(), and EntityAI::IsMan().
CheckParent()
void Clothing::CheckParent () inline protected
Definition at line 39 of file Headtorch_ColorBase.c.
  {
    EntityAI owner = GetHierarchyParent();
    // Spawn a battery in the headtorch if it's attached on a zombie and switch it on
    if (owner && owner.IsZombie())
    {
      GetInventory().CreateAttachment("Battery9V");
      GetCompEM().SwitchOn();
    }
    if (m_Timer)
      m_Timer.Stop();
    m_Timer = null;
  }
References m_Timer.
CreateHeadtorchLight()
void Clothing::CreateHeadtorchLight () inline protected
Definition at line 116 of file Headtorch_ColorBase.c.
  {
    if (!m_Light)
      m_Light = HeadtorchLight.Cast(ScriptedLightBase.CreateLight(HeadtorchLight, "0 0 0"));
    OnLightCreated();
    m_Light.PerformVisibilityCheck(this);
    EntityAI owner = GetHierarchyParent();
    if (owner)
    {
      if (owner.IsPlayer())
      {
        PlayerBase owner_PB = PlayerBase.Cast(owner);
        ItemBase att_item = owner_PB.GetItemOnSlot("Eyewear");
        if (att_item == this)
          AttachLightOnHead(owner_PB);
        else
          m_Light.AttachOnMemoryPoint(this, m_OffHeadLightPoint, m_OffHeadLightTarget);
      }
      else if (owner.IsZombie())
      {
        int slot_id = InventorySlots.GetSlotIdFromString("Eyewear");
        EntityAI item_EAI = owner.GetInventory().FindAttachment(slot_id);
        ItemBase item_IB = ItemBase.Cast(item_EAI);
        if (item_IB == this)
          AttachLightOnHead(owner);
      }
    }
    else
      m_Light.AttachOnMemoryPoint(this, m_OffHeadLightPoint, m_OffHeadLightTarget);
  }
References InventorySlots::GetSlotIdFromString(), and m_Light.
GetLightSourceItem()
override ItemBase Clothing::GetLightSourceItem () inline protected
Definition at line 224 of file Headtorch_ColorBase.c.
  {
    return this;
  }
Headtorch_ColorBase()
void Clothing::Headtorch_ColorBase () inline private
Definition at line 22 of file Headtorch_ColorBase.c.
  {
    if (GetGame().IsServer())
    {
      if (!m_Timer)
        m_Timer = new Timer(CALL_CATEGORY_SYSTEM);
      m_Timer.Run(1, this, "CheckParent", NULL, false);
    }
  }
References CALL_CATEGORY_SYSTEM, GetGame(), and m_Timer.
InitGlobalExclusionValues()
void Clothing::InitGlobalExclusionValues () inline protected
Definition at line 33 of file Headtorch_ColorBase.c.
  {
    super.InitGlobalExclusionValues();
    AddSingleExclusionValueGlobal(EAttExclusions.EXCLUSION_HEADSTRAP_0);
  }
IsLightSource()
override bool Clothing::IsLightSource () inline protected
Definition at line 219 of file Headtorch_ColorBase.c.
  {
    return true;
  }
OnInvisibleSet()
override void Clothing::OnInvisibleSet (bool invisible) inline protected
Definition at line 229 of file Headtorch_ColorBase.c.
  {
    if (m_Light)
      m_Light.SetEnabled(!invisible);
  }
References m_Light.
OnLightCreated()
void Clothing::OnLightCreated () inline protected
Definition at line 111 of file Headtorch_ColorBase.c.
  {
    m_Light.SetColorToWhite();
  }
References m_Light, and PointLightBase::SetColorToWhite().
OnWasAttached()
override void Clothing::OnWasAttached (EntityAI parent, int slot_id) inline protected
Definition at line 183 of file Headtorch_ColorBase.c.
  {
    super.OnWasAttached(parent, slot_id);
    PlayerBase player = PlayerBase.Cast(parent);
    if (player)
    {
      if (m_Light)
        AttachLightOnHead(player);
    }
  }
References m_Light.
OnWasDetached()
override void Clothing::OnWasDetached (EntityAI parent, int slot_id) inline protected
Definition at line 196 of file Headtorch_ColorBase.c.
  {
    super.OnWasDetached(parent, slot_id);
    if (parent && (parent.IsPlayer() || parent.IsZombie()))
    {
      if (m_Light)
      {
        m_Light.DetachFromParent();
        m_Light.AttachOnMemoryPoint(this, m_OffHeadLightPoint, m_OffHeadLightTarget);
      }
    }
  }
References m_Light.
OnWork()
override void Clothing::OnWork (float consumed_energy) inline protected
Definition at line 91 of file Headtorch_ColorBase.c.
  {
    super.OnWork(consumed_energy);
    if (!GetGame().IsServer() || !GetGame().IsMultiplayer()) // Client side
    {
      Battery9V battery = Battery9V.Cast(GetCompEM().GetEnergySource());
      if (battery && m_Light)
      {
        float efficiency = battery.GetEfficiency0To1();
        if (efficiency < 1)
          m_Light.SetIntensity(efficiency, GetCompEM().GetUpdateInterval());
        else
          m_Light.SetIntensity(1, 0);
      }
    }
  }
References GetGame(), m_Light, and PointLightBase::SetIntensity().
OnWorkStart()
override void Clothing::OnWorkStart () inline protected
Definition at line 56 of file Headtorch_ColorBase.c.
  {
    super.OnWorkStart();
    if (!GetGame().IsServer() || !GetGame().IsMultiplayer()) // Client side
      CreateHeadtorchLight();
    if (IsInherited(Headtorch_Black))
    {
      SetObjectMaterial(GLASS_ID, LIGHT_ON_GLASS_RED);
      SetObjectMaterial(REFLECTOR_ID, LIGHT_ON_REFLECTOR_RED);
    }
    else
    {
      SetObjectMaterial(GLASS_ID, LIGHT_ON_GLASS);
      SetObjectMaterial(REFLECTOR_ID, LIGHT_ON_REFLECTOR);
    }
  }
References GetGame().
OnWorkStop()
override void Clothing::OnWorkStop () inline protected
Definition at line 75 of file Headtorch_ColorBase.c.
  {
    super.OnWorkStop();
    if (!GetGame().IsServer() || !GetGame().IsMultiplayer()) // Client side
    {
      if (m_Light)
        m_Light.FadeOut();
      m_Light = NULL;
    }
    SetObjectMaterial(GLASS_ID, LIGHT_OFF_GLASS);
    SetObjectMaterial(REFLECTOR_ID, LIGHT_OFF_REFLECTOR);
  }
References GetGame(), and m_Light.
SetActions() [1/3]
override void Clothing::SetActions () inline private
Definition at line 19 of file Armband_ColorBase.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SetActions() [2/3]
override void Clothing::SetActions () inline protected
Definition at line 210 of file Headtorch_ColorBase.c.
  {
    super.SetActions();
    AddAction(ActionTurnOnWhileInHands);
    AddAction(ActionTurnOffWhileInHands);
    AddAction(ActionTurnOnHeadtorch);
    AddAction(ActionTurnOffHeadtorch);
  }
References AddAction().
SetActions() [3/3]
override void Clothing::SetActions () inline private
Definition at line 3 of file WitchHood.c.
  {
    super.SetActions();
    AddAction(ActionWringClothes);
  }
References AddAction().
SwitchItemSelectionTextureEx()
override void Clothing::SwitchItemSelectionTextureEx (EItemManipulationContext context, Param par = null) inline private
Definition at line 25 of file Armband_ColorBase.c.
  {
    super.SwitchItemSelectionTextureEx(context, par);
    if (context == EItemManipulationContext.ATTACHING || context == EItemManipulationContext.UPDATE)
    {
      Param1<PlayerBase> data = Param1<PlayerBase>.Cast(par);
      if (!data)
        return;
      PlayerBase player = data.param1;
      int selection_idx = -1;
      string texture;
      array<string> show_selections = new array<string>;
      array<string> hide_selections = new array<string>;
      //has top
      if (player.FindAttachmentBySlotName("Body"))
      {
        show_selections.Insert("camoMale_big_a");
        show_selections.Insert("camoMale_big_b");
        show_selections.Insert("camoFemale_big_a");
        show_selections.Insert("camoFemale_big_b");
        hide_selections.Insert("camoMale_small_a");
        hide_selections.Insert("camoMale_small_b");
        hide_selections.Insert("camoFemale_small_a");
        hide_selections.Insert("camoFemale_small_b");
      }
      //has no top
      else
      {
        hide_selections.Insert("camoMale_big_a");
        hide_selections.Insert("camoMale_big_b");
        hide_selections.Insert("camoFemale_big_a");
        hide_selections.Insert("camoFemale_big_b");
        show_selections.Insert("camoMale_small_a");
        show_selections.Insert("camoMale_small_b");
        show_selections.Insert("camoFemale_small_a");
        show_selections.Insert("camoFemale_small_b");
      }
      int i;
      for (i = 0; i < show_selections.Count(); i++)
      {
        selection_idx = GetHiddenSelectionIndex(show_selections[i]);
        texture = GetHiddenSelectionsData().GetHiddenSelectionsTextures()[selection_idx];
        SetObjectTexture(selection_idx, texture);
      }
      for (i = 0; i < hide_selections.Count(); i++)
      {
        selection_idx = GetHiddenSelectionIndex(hide_selections[i]);
        SetObjectTexture(selection_idx, "");
      }
    }
  }
Member Data Documentation
GLASS_ID
int Clothing::GLASS_ID = 5 static private
Definition at line 6 of file Headtorch_ColorBase.c.
LIGHT_OFF_GLASS
string Clothing::LIGHT_OFF_GLASS = "dz\\characters\\headgear\\data\\HeadTorchGlass.rvmat" static private
Definition at line 8 of file Headtorch_ColorBase.c.
LIGHT_OFF_REFLECTOR
string Clothing::LIGHT_OFF_REFLECTOR = "dz\\characters\\headgear\\data\\HeadTorch.rvmat" static private
Definition at line 9 of file Headtorch_ColorBase.c.
LIGHT_ON_GLASS
string Clothing::LIGHT_ON_GLASS = "dz\\characters\\headgear\\data\\HeadTorchGlass_on.rvmat" static private
Definition at line 10 of file Headtorch_ColorBase.c.
LIGHT_ON_GLASS_RED
string Clothing::LIGHT_ON_GLASS_RED = "dz\\characters\\headgear\\data\\HeadTorchGlass_on_red.rvmat" static private
Definition at line 11 of file Headtorch_ColorBase.c.
LIGHT_ON_REFLECTOR
string Clothing::LIGHT_ON_REFLECTOR = "dz\\characters\\headgear\\data\\HeadTorch_ON.rvmat" static private
Definition at line 12 of file Headtorch_ColorBase.c.
LIGHT_ON_REFLECTOR_RED
string Clothing::LIGHT_ON_REFLECTOR_RED = "dz\\characters\\headgear\\data\\HeadTorch_ON_red.rvmat" static private
Definition at line 13 of file Headtorch_ColorBase.c.
m_Light
HeadtorchLight Clothing::m_Light private
Definition at line 3 of file Headtorch_ColorBase.c.
m_OffHeadLightPoint
string Clothing::m_OffHeadLightPoint = "beamStart" static private
Definition at line 17 of file Headtorch_ColorBase.c.
m_OffHeadLightTarget
string Clothing::m_OffHeadLightTarget = "beamEnd" static private
Definition at line 18 of file Headtorch_ColorBase.c.
m_OnHeadLocalOri
vector Clothing::m_OnHeadLocalOri = Vector(0, 90, 0) static private
Definition at line 16 of file Headtorch_ColorBase.c.
m_OnHeadLocalPos
vector Clothing::m_OnHeadLocalPos = Vector(0.12, 0.15, 0) static private
Definition at line 15 of file Headtorch_ColorBase.c.
m_Timer
ref Timer Clothing::m_Timer private
Definition at line 20 of file Headtorch_ColorBase.c.
REFLECTOR_ID
int Clothing::REFLECTOR_ID = 4 static private
Definition at line 5 of file Headtorch_ColorBase.c.
The documentation for this class was generated from the following files:
scripts/4_World/Entities/ItemBase/Clothing/Armband_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/Headtorch_ColorBase.c
scripts/4_World/Entities/ItemBase/Clothing/WitchHood.c