DayZ: DayZPlayer Class Reference
DayZPlayer Class Reference
Protected Member Functions
void DayZPlayerImplement ()
constructor
DayZPlayerImplementAiming GetAimingModel ()
DayZPlayerImplementMeleeCombat GetMeleeCombat ()
DayZPlayerMeleeFightLogic_LightHeavy GetMeleeFightLogic ()
DayZPlayerImplementThrowing GetThrowing ()
DayZPlayerImplementFallDamage GetFallDamage ()
void ~DayZPlayerImplement ()
override bool IsEyeZoom ()
Legacy.
override int GetEyeZoomLevel ()
override bool IsShootingFromCamera ()
void OverrideShootFromCamera (bool pState)
bool IsInIronsights ()
bool IsInOptics ()
override bool IsInThirdPerson ()
void SetIsInThirdPerson (bool state)
bool IsFireWeaponRaised ()
bool IsTryingHoldBreath ()
bool IsSprintFull ()
void ShowWeaponDebug (bool show)
bool IsWeaponDebugEnabled ()
void SetFallYDiff (float value)
override float GetCurrentWaterLevel ()
override void SetCurrentWaterLevel (float pWaterLevel)
void SetIronsights (bool value)
void SetOptics (bool value)
void ExitSights ()
void SwitchOptics (ItemOptics optic, bool state)
void SetClimbingLadderType (string value)
bool CanConsumeStamina (EStaminaConsumers consumer)
Implementations only! - used on PlayerBase.
bool CanStartConsumingStamina (EStaminaConsumers consumer)
void DepleteStamina (EStaminaModifiers modifier, float dT=-1)
bool IsInVehicle ()
bool IsSwimming ()
bool IsClimbingLadder ()
bool PlaySoundEvent (EPlayerSoundEventID id, bool from_anim_system=false, bool is_from_server=false)
bool PlaySoundEventEx (EPlayerSoundEventID id, bool from_anim_system=false, bool is_from_server=false, int param=0)
bool IsFBSymptomPlaying ()
float GetDeltaT ()
override string GetDebugText ()
void TriggerPullPlayerOutOfVehicle ()
void TriggerPullPlayerOutOfVehicleImpl ()
override void OnVariablesSynchronized ()
bool HandleDeath (int pCurrentCommandID)
void ResetDeathStartTime ()
int GetTypeOfDeath (int pCurrentCommandID)
void SendDeathJuncture (int pAnimTypeDeath, float pAnimHitDirDeath)
override void EEKilled (Object killer)
void ShowDeadScreen (bool show, float duration)
override void StopDeathDarkeningEffect ()
void SimulateDeath (bool state)
void LockControls (bool state)
void SetDeathDarknessLevel (float duration, float tick_time)
void SendCompleteWeaponRaiseJuncture ()
void CompleteWeaponRaise ()
void ResetWeaponRaiseProgress ()
bool IsWeaponRaiseCompleted ()
DayZPlayerInventory GetDayZPlayerInventory ()
override void OnInputForRemote (ParamsReadContext ctx)
override void OnInputFromServer (ParamsReadContext ctx)
void RequestSoundEvent (EPlayerSoundEventID id, bool from_server_and_client=false)
void RequestSoundEventEx (EPlayerSoundEventID id, bool from_server_and_client=false, int param=0)
void SendSoundEvent (EPlayerSoundEventID id)
void SendSoundEventEx (EPlayerSoundEventID id, int param=0)
override void OnItemInHandsChanged ()
WeaponManager GetWeaponManager ()
void HandleWeapons (float pDt, Entity pInHands, HumanInputController pInputs, out bool pExitIronSights)
void HandleOptic (notnull ItemOptics optic, bool inHands, HumanInputController pInputs, out bool pExitOptics)
bool IsInFullbodyDamageAnimation ()
void EvaluateDamageHit (int pCurrentCommandID)
Must be ran at the start of CommandHandler before Jump is triggered.
bool HandleDamageHit (int pCurrentCommandID)
void ResetDamageHitState (bool resetTimer)
bool EvaluateDeathAnimation (int pDamageType, EntityAI pSource, string pAmmoType, out int pAnimType, out float pAnimHitDir)
selects animation type and direction based on damage system data
bool EvaluateDamageHitAnimation (TotalDamageResult pDamageResult, int pDamageType, EntityAI pSource, string pComponent, string pAmmoType, vector pModelPos, out int pAnimType, out float pAnimHitDir, out bool pAnimHitFullbody)
selects animation type and direction based on damage system data
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
event from damage system
override bool HeadingModel (float pDt, SDayZPlayerHeadingModel pModel)
override bool AimingModel (float pDt, SDayZPlayerAimingModel pModel)
bool CanJump ()
bool CanClimb (int climbType, SHumanCommandClimbResult climbRes)
void OnJumpStart ()
void OnJumpEnd (int pLandType=0)
void StopHandEvent ()
void StopWeaponEvent ()
void AbortWeaponEvent ()
void HandleADS ()
void HandleView ()
bool ModCommandHandlerBefore (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
bool ModCommandHandlerInside (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
bool ModCommandHandlerAfter (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
override void CommandHandler (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
void HideClothing (ItemOptics optic, bool state)
void CommandHandlerDebug (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
override int CameraHandler (int pCameraMode)
void OnMovementChanged ()
Event, called when HumanMovementState.m_iMovement changes...walk, run, sprint, etc..
void OnSprintStart ()
void OnSprintEnd ()
void OnInputUserDataReceived (ParamsReadContext ctx)
bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx)
void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx)
AnimBootsType GetBootsType ()
AnimUpperBodyType GetBodyAttachmentType ()
AnimBackType GetBackAttachmentType ()
AnimRangedWeaponType GetShoulderAttachmentType ()
string GetSurfaceType (SurfaceAnimationBone limbType)
AbstractWave PlaySound (SoundObject so, SoundObjectBuilder sob)
void AddNoise (NoiseParams noisePar, float noiseMultiplier=1.0)
void OnStepEvent (string pEventType, string pUserString, int pUserInt)
void OnSoundEvent (string pEventType, string pUserString, int pUserInt)
void OnParticleEvent (string pEventType, string pUserString, int pUserInt)
void ProcessWeaponEvent (string pEventType, string pUserString, int pUserInt)
void ProcessAttachmentEvent (string pEventType, string pUserString, int pUserInt)
void SetVariablesLadderSoundObjectBuilder (SoundObjectBuilder soundObjectBuilder)
void ProcessSoundEvent (string pEventType, string pUserString, int pUserInt)
AbstractWave ProcessVoiceEvent (string pEventType, string pUserString, int pUserInt)
void ProcessFeetDamageServer (int pUserInt)
bool CheckForTakeItem (EntityAI item)
bool CheckForDropItem (EntityAI item)
bool CheckForRespawn (EntityAI item)
bool IsLanded (int pCurrentCommandID)
bool OnLand (int pCurrentCommandID, FallDamageData fallDamageData)
bool IsAlreadyInFallingCommand (int pCurrentCommandID)
void OverrideSlidePoseAngle (float value)
movement sliding override, originally for FB gestures
float GetSlidePoseAngle ()
void CheckAnimationOverrides ()
bool IsPlayerSelected ()
bool IsRestrained ()
bool IsInFBEmoteState ()
Checks if fullbody animation or specific locked state is active in emote manager.
void SetSuicide (bool state)
bool CommitedSuicide ()
void OnLadder (float delta_time, HumanMovementState pState)
called every command handler tick when player is on ladder
void EOnContact (IEntity other, Contact extra)
void AttenuateSoundIfNecessary (SoundObject soundObject)
void CheckLiftWeapon ()
void ProcessLiftWeapon ()
void SetHandheldOpticsInUse (bool state)
bool IsHandheldOpticsInUse ()
bool IsLiftWeapon ()
bool IsRaised ()
bool IsFighting ()
bool CanPickupHeavyItem (notnull EntityAI item)
-------------— Checks if player can pick up heavy item ----------------------—
bool CanPickupHeavyItemSwap (notnull EntityAI item1, notnull EntityAI item2)
void SetReturnToOptics (bool state)
void RunADSTimer ()
void StopADSTimer ()
Protected Attributes
ref DayZPlayerImplementAiming m_AimingModel
ref DayZPlayerImplementMeleeCombat m_MeleeCombat
ref DayZPlayerMeleeFightLogic_LightHeavy m_MeleeFightLogic
ref DayZPlayerImplementSwimming m_Swimming
ref DayZPlayerImplementThrowing m_Throwing
ref DayZPlayerImplementJumpClimb m_JumpClimb
ref DayZPlayerImplementFallDamage m_FallDamage
ref PlayerSoundEventHandler m_PlayerSoundEventHandler
SHumanCommandMoveSettings m_MoveSettings
float m_FallYDiff
float m_SprintedTime
float m_SprintedTimePerStanceMin
bool m_SprintFull
bool m_IsRaised
bool m_ShouldReload
bool m_Camera3rdPerson
bool m_CameraZoomToggle
bool m_bADS
bool m_WeaponRaiseCompleted
measures time from the weapon raise start to complete raise (once per)
ECameraZoomType m_CameraEyeZoomLevel
bool m_WasIronsight
bool m_CameraIronsight
bool m_CameraOptics
float m_DeathDarkeningCurrentTime
bool m_IsTryingHoldBreath
bool m_IsShootingFromCamera
bool m_PlayerSelected
bool m_Suicide
bool m_IsUnconscious
bool m_ShouldBeUnconscious
bool m_IsUnconsciousFalling
bool m_UnconsciousDebug
int m_LastCommandBeforeUnconscious
ref WeaponDebug m_WeaponDebug
ref DeathEffectTimer m_DeathEffectTimer
ref Timer m_FightEndBlendTimer
bool m_ProcessFirearmMeleeHit
bool m_ContinueFirearmMelee
bool m_LiftWeapon_player
bool m_ProcessLiftWeapon
bool m_ProcessLiftWeaponState
int m_LastSurfaceUnderHash
Transport m_TransportCache
string m_ClimbingLadderType
bool m_isFBsymptomPlaying
bool m_HandheldOpticsInUse
bool m_ResetADS
int m_StepCounter
int m_NextVoNNoiseTime
ref array< ref SyncHitInfo > m_SyncedHitDataArray
bool m_RaiseStarted = false
bool m_AimingFinisherStarted = false
bool m_IsWeapon
bool m_TriggerPullPlayerOutOfVehicleSynch
bool m_PullPlayerOutOfVehicleKeepsInLocalSpace = false
int m_PullPlayerOutOfVehicleState = -1
int m_ActionSoundCategoryHash
float m_dT
int m_DeathAnimType = -2
float m_DeathHitDir = 0
bool m_DeathJuctureSent = false
bool m_DamageHitFullbody = false
int m_DamageHitAnimType = -1.0
float m_DamageHitDir = 0.0
float m_DamageHealth = 0.0
const float HIT_INTERVAL_MIN = 0.3
float m_HitElapsedTime = HIT_INTERVAL_MIN
float m_fLastHeadingDiff = 0
float m_LastHeadingAngleBlock
float m_LastHeadingAngleBlock2
float m_LastHeadingAngle
int m_LastBackSoundTime
int m_LastBackSoundTime2
float m_SoundOffset
float m_TestDamageCounter = -1
float m_DebugDirectionVal = -180
VKOSTIK - tady dat 0 misto -1.
bool m_DebugTypeVal = false
int m_DebugWeaponChangeStage = 0
string m_DebugWeaponChangeItem
int m_DebugWeaponChangeShowSlot
bool m_CameraEyeZoom
ref Timer m_ADSAutomationTimer
bool m_ADSTimerLaunched
bool m_ProcessWeaponRaiseCompleted
bool m_IsFireWeaponRaised
Private Attributes
ref HumanMovementState m_MovementState = new HumanMovementState()
time step for gradual update of dead screen visibilibty up to full visbility [s]
float m_WeaponRaiseTime
float m_CurrentWaterLevel
bool m_WasInVehicle
Static Private Attributes
static const int DEAD_SCREEN_DELAY = 1000
static const float DEFAULT_DYING_TIME = 2.5
DEPRECATED.
static const float DYING_PROGRESSION_TIME = 0.05
how long does it take to full death screen [s]
Detailed Description
Definition at line 70 of file DayZPlayerImplement.c.
Constructor & Destructor Documentation
~DayZPlayerImplement()
void DayZPlayer::~DayZPlayerImplement () inline protected
Definition at line 204 of file DayZPlayerImplement.c.
  {
  }
Member Function Documentation
AbortWeaponEvent()
void DayZPlayer::AbortWeaponEvent () inline protected
Definition at line 1522 of file DayZPlayerImplement.c.
  {
    GetDayZPlayerInventory().AbortWeaponEvent();
  }
AddNoise()
void DayZPlayer::AddNoise (NoiseParams noisePar, float noiseMultiplier = 1.0) inline protected
Definition at line 2766 of file DayZPlayerImplement.c.
  {
    if (noisePar != null)
      GetGame().GetNoiseSystem().AddNoise(this, noisePar, noiseMultiplier);
  }
References GetGame().
AimingModel()
override bool DayZPlayer::AimingModel (float pDt, SDayZPlayerAimingModel pModel) inline protected
This Aiming Model
Definition at line 1402 of file DayZPlayerImplement.c.
  {
    GetMovementState(m_MovementState);
    if (m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_MELEE2)
    {
      HumanCommandMelee2 hcm = GetCommand_Melee2();
      if (hcm.IsFinisher())
      {
        if (!m_AimingFinisherStarted)
        {
          m_AimingModel.OnFinisherBegin(pModel.m_fCurrentAimY);
          m_AimingFinisherStarted = true;
        }
        m_AimingModel.ProcessStealthFilters(pDt, pModel);
      }
      return true;
    }
    if (m_MovementState.IsRaised())
    {
      if (!m_RaiseStarted)
      {
        m_AimingModel.OnRaiseBegin(this);
        m_RaiseStarted = true;
      }
      m_AimingModel.ProcessAimFilters(pDt, pModel, m_MovementState.m_iStanceIdx);
      return true;
    }
    m_RaiseStarted = false;
    m_AimingFinisherStarted = false;
    return true;
  }
References GetCommand_Melee2(), GetMovementState(), and m_MovementState.
AttenuateSoundIfNecessary()
void DayZPlayer::AttenuateSoundIfNecessary (SoundObject soundObject) inline protected
Definition at line 3309 of file DayZPlayerImplement.c.
  {
    if (GetGame().GetPlayer() != NULL && (IsSoundInsideBuilding() != GetGame().GetPlayer().IsSoundInsideBuilding() || IsCameraInsideVehicle() != GetGame().GetPlayer().IsCameraInsideVehicle()))
      soundObject.SetKind(WaveKind.WAVEATTALWAYS);
    else
      soundObject.SetKind(WaveKind.WAVEEFFECTEX);
  }
References GetGame(), and GetPlayer().
CameraHandler()
override int DayZPlayer::CameraHandler (int pCameraMode) inline protected
This is main camera selection logic
ironsights
get movement state
VKOSTIK: v ostatnich commandech mimo COMMANDID_MOVE je m_MovementState.m_iStanceIdx - DayZPlayerConstants.STANCEIDX_ERECT m_MovementState.m_iMovement = 0 (idle)
COMMANDID_ACTION returns stance right - ERECT/CROUCH
melee camera - not melee - stays in stance camera
special handling to allow the camera to fully blend before transitioning to the raised one
Definition at line 2362 of file DayZPlayerImplement.c.
  {
    if (!m_LiftWeapon_player)
    {
      ItemOptics optics = null;
      EntityAI entityInHands = GetHumanInventory().GetEntityInHands();
      Weapon weapon = Weapon.Cast(entityInHands);
      if (weapon)
        optics = weapon.GetAttachedOptics();
      else if (entityInHands)
        Class.CastTo(optics, entityInHands);
      if (m_CameraOptics && optics)
        return DayZPlayerCameras.DAYZCAMERA_OPTICS;
      else if (m_CameraIronsight && weapon)
        return DayZPlayerCameras.DAYZCAMERA_IRONSIGHTS;
    }
    // If the logic above doesn't reach optics nor ironsights camera,
    // yet weapon is still raised and ads is wanted, enforce 1pv camera
    // as this will reduce erratic behaviour of camera switching in 3pv
    HumanInputController hic = GetInputController();
    if (m_Camera3rdPerson && m_IsWeapon && m_IsRaised && hic && hic.WeaponADS())
      return DayZPlayerCameras.DAYZCAMERA_1ST;
    //uncon
    if (GetCurrentCommandID() == DayZPlayerConstants.COMMANDID_UNCONSCIOUS)
      return DayZPlayerCameras.DAYZCAMERA_1ST_UNCONSCIOUS;
    HumanCommandVehicle vehicleCommand = GetCommand_Vehicle();
    if (!m_Camera3rdPerson)
    {
      if (vehicleCommand)
        return DayZPlayerCameras.DAYZCAMERA_1ST_VEHICLE;
      return DayZPlayerCameras.DAYZCAMERA_1ST;
    }
    else
    {
      if (vehicleCommand)
      {
        Transport transport = vehicleCommand.GetTransport();
        if (transport && GetParent())
          return transport.Get3rdPersonCameraType();
      }
      GetMovementState(m_MovementState);
      if (m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_CLIMB)
        return DayZPlayerCameras.DAYZCAMERA_3RD_CLIMB;
      if (m_JumpClimb.m_bIsJumpInProgress)
        return DayZPlayerCameras.DAYZCAMERA_3RD_JUMP;
      int targetStanceIndex = m_MovementState.m_iStanceIdx;
      HumanCommandMove commandMove = GetCommand_Move();
      if (commandMove && commandMove.IsChangingStance() && m_MovementState.IsRaised())
        targetStanceIndex = m_MovementState.m_iStanceIdx - DayZPlayerConstants.STANCEIDX_RAISED;
      //
      // normal movement cameras
      if (targetStanceIndex == DayZPlayerConstants.STANCEIDX_CROUCH)
        return DayZPlayerCameras.DAYZCAMERA_3RD_CRO;
      else if (targetStanceIndex == DayZPlayerConstants.STANCEIDX_RAISEDCROUCH)
        return DayZPlayerCameras.DAYZCAMERA_3RD_CRO_RAISED;
      else if (targetStanceIndex == DayZPlayerConstants.STANCEIDX_PRONE)
        return DayZPlayerCameras.DAYZCAMERA_3RD_PRO;
      else if (targetStanceIndex == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
        return DayZPlayerCameras.DAYZCAMERA_3RD_PRO_RAISED;
      if (targetStanceIndex == DayZPlayerConstants.STANCEIDX_RAISEDERECT)
      {
        if (m_IsWeapon)
          return DayZPlayerCameras.DAYZCAMERA_3RD_ERC_RAISED;
        else
          return DayZPlayerCameras.DAYZCAMERA_3RD_ERC_RAISED_MELEE;
      }
      else if (targetStanceIndex == DayZPlayerConstants.MOVEMENTIDX_SPRINT)
        return DayZPlayerCameras.DAYZCAMERA_3RD_ERC_SPR;
      // DayZPlayerConstants.STANCEIDX_ERECT
      return DayZPlayerCameras.DAYZCAMERA_3RD_ERC;
    }
    return DayZPlayerCameras.DAYZCAMERA_1ST;
  }
References Class::CastTo(), DayZPlayerCameras::DAYZCAMERA_1ST, DayZPlayerCameras::DAYZCAMERA_1ST_UNCONSCIOUS, DayZPlayerCameras::DAYZCAMERA_1ST_VEHICLE, DayZPlayerCameras::DAYZCAMERA_3RD_CLIMB, DayZPlayerCameras::DAYZCAMERA_3RD_CRO, DayZPlayerCameras::DAYZCAMERA_3RD_CRO_RAISED, DayZPlayerCameras::DAYZCAMERA_3RD_ERC, DayZPlayerCameras::DAYZCAMERA_3RD_ERC_RAISED, DayZPlayerCameras::DAYZCAMERA_3RD_ERC_RAISED_MELEE, DayZPlayerCameras::DAYZCAMERA_3RD_ERC_SPR, DayZPlayerCameras::DAYZCAMERA_3RD_JUMP, DayZPlayerCameras::DAYZCAMERA_3RD_PRO, DayZPlayerCameras::DAYZCAMERA_3RD_PRO_RAISED, DayZPlayerCameras::DAYZCAMERA_IRONSIGHTS, DayZPlayerCameras::DAYZCAMERA_OPTICS, GetCommand_Move(), GetCommand_Vehicle(), GetCurrentCommandID(), GetInputController(), GetMovementState(), GetParent(), and m_MovementState.
CanClimb()
bool DayZPlayer::CanClimb (int climbType, SHumanCommandClimbResult climbRes) inline protected
Definition at line 1474 of file DayZPlayerImplement.c.
  {
    if (IsFBSymptomPlaying() || IsRestrained() || IsUnconscious() || IsInFBEmoteState())
      return false;
    if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_PRONE || m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
      return false;
    if (IsRaised() && GetInputInterface().SyncedPress("UAGetOverControllerHelper")) //no raised climb on cotroller
      return false;
    HumanItemBehaviorCfg hibcfg = GetItemAccessor().GetItemInHandsBehaviourCfg();
    if (!hibcfg.m_bJumpAllowed)
      return false;
    if (climbRes)
    {
      EntityAI entity;
      if (Class.CastTo(entity, climbRes.m_GrabPointParent) && entity.IsHologram())
        return false;
      if (Class.CastTo(entity, climbRes.m_ClimbStandPointParent) && entity.IsHologram())
        return false;
      if (Class.CastTo(entity, climbRes.m_ClimbOverStandPointParent) && entity.IsHologram())
        return false;
    }
    return true;
  }
References Class::CastTo(), GetItemAccessor(), IsRaised(), and m_MovementState.
CanConsumeStamina()
bool DayZPlayer::CanConsumeStamina (EStaminaConsumers consumer) inline protected
Implementations only! - used on PlayerBase.
Definition at line 375 of file DayZPlayerImplement.c.
{};
Referenced by GetAttackTypeByWeaponAttachments(), GetAttackTypeFromInputs(), and HandleFightLogic().
CanJump()
bool DayZPlayer::CanJump () inline protected
Jump
Definition at line 1446 of file DayZPlayerImplement.c.
  {
    if (IsFBSymptomPlaying() || IsRestrained() || IsUnconscious() || IsInFBEmoteState())
      return false;
    if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_PRONE || m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
      return false;
    if (IsRaised() && GetInputInterface().SyncedPress("UAGetOverControllerHelper")) //no raised jump on cotroller
      return false;
    HumanItemBehaviorCfg hibcfg = GetItemAccessor().GetItemInHandsBehaviourCfg();
    if (!hibcfg.m_bJumpAllowed)
      return false;
    if (!DayZPlayerUtils.PlayerCanChangeStance(this, DayZPlayerConstants.STANCEIDX_ERECT) || !DayZPlayerUtils.PlayerCanChangeStance(this, DayZPlayerConstants.STANCEIDX_RAISEDERECT))
      return false;
    HumanCommandMove hcm = GetCommand_Move();
    if (hcm)
    {
      if (hcm.IsChangingStance())
        return false;
    }
    return true;
  }
References DayZPlayerUtils(), GetCommand_Move(), GetItemAccessor(), IsRaised(), and m_MovementState.
CanPickupHeavyItem()
bool DayZPlayer::CanPickupHeavyItem (notnull EntityAI item) inline protected
-------------— Checks if player can pick up heavy item ----------------------—
Definition at line 3340 of file DayZPlayerImplement.c.
  {
    return !item.IsHeavyBehaviour() || (item.IsHeavyBehaviour() && DayZPlayerUtils.PlayerCanChangeStance(this, DayZPlayerConstants.STANCEIDX_ERECT));
  }
References DayZPlayerUtils().
CanPickupHeavyItemSwap()
bool DayZPlayer::CanPickupHeavyItemSwap (notnull EntityAI item1, notnull EntityAI item2) inline protected
Definition at line 3345 of file DayZPlayerImplement.c.
  {
    return CanPickupHeavyItem(item1) && CanPickupHeavyItem(item2);
  }
CanStartConsumingStamina()
bool DayZPlayer::CanStartConsumingStamina (EStaminaConsumers consumer) inline protected
Definition at line 376 of file DayZPlayerImplement.c.
{};
CheckAnimationOverrides()
void DayZPlayer::CheckAnimationOverrides () inline protected
Definition at line 3261 of file DayZPlayerImplement.c.
  {
  }
CheckForDropItem()
bool DayZPlayer::CheckForDropItem (EntityAI item) inline protected
Definition at line 3159 of file DayZPlayerImplement.c.
  {
    /*
      bool restrained = IsRestrained(); // IsRestrained()
      bool unconscious = IsUnconscious(); // IsRestrained()
      ItemBase ib = ItemBase.Cast(item);
      if (!IsAlive() || restrained || unconscious || ib.CanBeMovedOverride())
      return true;
      return false;
    */
    return CheckForTakeItem(item); //the two functions are currently identical
  }
CheckForRespawn()
bool DayZPlayer::CheckForRespawn (EntityAI item) inline protected
Player respawn
Definition at line 3177 of file DayZPlayerImplement.c.
  {
    PlayerBase player = PlayerBase.Cast(this);
    if (!player)
      return true;
    if (!IsAlive() || player.IsUnconscious())
      return true;
    return false;
  }
CheckForTakeItem()
bool DayZPlayer::CheckForTakeItem (EntityAI item) inline protected
anti-cheat condition
Definition at line 3148 of file DayZPlayerImplement.c.
  {
    bool restrained = IsRestrained(); // IsRestrained()
    bool unconscious = IsUnconscious(); // IsRestrained()
    ItemBase ib = ItemBase.Cast(item);
    if (ib && (PlayerBase.DEBUG_INVENTORY_ACCESS || !IsAlive() || restrained || unconscious || ib.CanBeMovedOverride()))
      return true;
    return false;
  }
CheckLiftWeapon()
void DayZPlayer::CheckLiftWeapon () protected
CommandHandler()
override void DayZPlayer::CommandHandler (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline protected
This is main command logic
handle all Camera changes, switch + zoom
handle death with high priority
handle finished commands
default behaviour after finish is to start move
debug test script command !PSOVIS
Sprint attack limiting - player has to be in full sprint for at least 0.5s
If we are not in fall command then something else is currently running and we can safely continue here, otherwise terminate here
throwing handling
melee
Definition at line 1871 of file DayZPlayerImplement.c.
  {
    m_dT = pDt;
    if (ModCommandHandlerBefore(pDt, pCurrentCommandID, pCurrentCommandFinished))
      return;
    HumanInputController hic = GetInputController();
    EntityAI entityInHands = GetHumanInventory().GetEntityInHands();
    GetMovementState(m_MovementState);
    bool isRaisedNow = m_MovementState.IsRaised();
    bool isWeapon = entityInHands && entityInHands.IsInherited(Weapon);
    bool updateAimingMdfr = false;
    if (isWeapon != m_IsWeapon)
    {
      m_IsWeapon = isWeapon;
      updateAimingMdfr = true;
    }
    if (isRaisedNow != m_IsRaised)
    {
      updateAimingMdfr = true;
      m_IsRaised = m_MovementState.IsRaised();
    }
    if (updateAimingMdfr)
    {
      if (isRaisedNow && isWeapon)
        GetUApi().ActivateModificator("aiming");
      else
        GetUApi().DeactivateModificator("aiming");
    }
    // handle ADS ironsights/optics transition logic
    HandleADS();
    // handle weapons
    if (hic)
    {
      ItemOptics opticInHands = ItemOptics.Cast(entityInHands);
      if (isWeapon && (!m_ProcessFirearmMeleeHit || !m_ContinueFirearmMelee))
      {
        m_ProcessFirearmMeleeHit = false;
        bool exitIronSights = false;
        HandleWeapons(pDt, entityInHands, hic, exitIronSights);
      }
      else if (IsHandheldOpticsInUse() && m_CameraOptics && opticInHands)
      {
        bool exitOptic = false;
        HandleOptic(opticInHands, true, hic, exitOptic);
      }
    }
    HandleView();
    if (m_MovementState.m_iMovement != m_MovementState.m_LocalMovement)
    {
      OnMovementChanged();
      m_MovementState.m_LocalMovement = m_MovementState.m_iMovement;
    }
    if (HandleDeath(pCurrentCommandID))
      return;
    if (pCurrentCommandFinished)
    {
      if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_UNCONSCIOUS)
      {
        if ((m_LastCommandBeforeUnconscious == DayZPlayerConstants.COMMANDID_VEHICLE) && (m_TransportCache != null))
        {
          int crew_index = m_TransportCache.CrewMemberIndex(this);
          int seat = m_TransportCache.GetSeatAnimationType(crew_index);
          StartCommand_Vehicle(m_TransportCache, crew_index, seat, true);
          m_TransportCache = null;
          return;
        }
      }
      // start moving
      // start falling ? (could happen after climbing)
      if (PhysicsIsFalling(true))
      {
        StartCommand_Fall(0);
        SetFallYDiff(GetPosition()[1]);
        return;
      }
      if (m_Swimming.m_bWasSwimming)
      {
        StartCommand_Swim();
        return;
      }
      StartCommand_Move();
      if (GetHumanInventory().GetEntityInHands())
        ForceStandUpForHeavyItems(GetHumanInventory().GetEntityInHands());
      return;
    }
    //--------------------------------------------
    if (ModCommandHandlerInside(pDt, pCurrentCommandID, pCurrentCommandFinished))
      return;
    //--------------------------------------------
    // vehicle handling
    if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_VEHICLE)
    {
      HumanCommandVehicle hcv = GetCommand_Vehicle();
      if (hcv.WasGearChange())
      {
        GearChangeActionCallback cb = GearChangeActionCallback.Cast(AddCommandModifier_Action(DayZPlayerConstants.CMD_ACTIONMOD_SHIFTGEAR, GearChangeActionCallback));
        cb.SetVehicleCommand(hcv);
      }
      return;
    }
    //--------------------------------------------
    HumanCommandMove hcm = GetCommand_Move();
    if (hcm && hcm.GetCurrentMovementSpeed() > 2.99 && m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_SPRINT)
    {
      m_SprintedTime += pDt;
      if (m_SprintedTime > m_SprintedTimePerStanceMin)
      {
        m_SprintFull = true;
        m_SprintedTimePerStanceMin = PlayerConstants.FULL_SPRINT_DELAY_DEFAULT;
      }
      else
        m_SprintFull = false;
    }
    else
    {
      m_SprintedTime = 0.0;
      m_SprintFull = false;
    }
    //--------------------------------------------
    // swimming handling
    if (m_Swimming.HandleSwimming(pCurrentCommandID, hcm, m_MovementState))
    {
      m_JumpClimb.CheckAndFinishJump();
      return;
    }
    //--------------------------------------------
    // ladder handling
    if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_LADDER)
    {
      OnLadder(pDt, m_MovementState);
      return;
    }
    //--------------------------------------------
    // climb handling
    if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_CLIMB)
      return;
    //--------------------------------------------
    // fall handling
    if (IsAlreadyInFallingCommand(pCurrentCommandID))
    {
      if (IsLanded(pCurrentCommandID))
      {
        DayZPlayerType type = GetDayZPlayerType();
        NoiseParams npar;
        FallDamageData fallDamageData = new FallDamageData();
        fallDamageData.m_Height = m_FallYDiff - GetPosition()[1];
        // land
        if (fallDamageData.m_Height < 0.5)
        {
          fallDamageData.m_LandType = HumanCommandFall.LANDTYPE_NONE;
          OnLand(pCurrentCommandID, fallDamageData);
          npar = type.GetNoiseParamsLandLight();
          AddNoise(npar);
        }
        else if (fallDamageData.m_Height < 3.0)
        {
          if (m_MovementState.IsInProne() || m_MovementState.IsInRaisedProne())
            fallDamageData.m_LandType = HumanCommandFall.LANDTYPE_NONE;
          else
            fallDamageData.m_LandType = HumanCommandFall.LANDTYPE_LIGHT;
          OnLand(pCurrentCommandID, fallDamageData);
          npar = type.GetNoiseParamsLandLight();
          AddNoise(npar);
        }
        else if (fallDamageData.m_Height < 5.0)
        {
          fallDamageData.m_LandType = HumanCommandFall.LANDTYPE_MEDIUM;
          OnLand(pCurrentCommandID, fallDamageData);
          npar = type.GetNoiseParamsLandHeavy();
          AddNoise(npar);
        }
        else
        {
          fallDamageData.m_LandType = HumanCommandFall.LANDTYPE_HEAVY;
          OnLand(pCurrentCommandID, fallDamageData);
          npar = type.GetNoiseParamsLandHeavy();
          AddNoise(npar);
        }
        if (fallDamageData.m_Height >= DayZPlayerImplementFallDamage.HEALTH_HEIGHT_LOW && GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
          OnPlayerRecievedHit();
        m_FallDamage.HandleFallDamage(fallDamageData);
        m_JumpClimb.CheckAndFinishJump(fallDamageData.m_LandType);
      }
      if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_FALL)
        return;
    }
    else if (PhysicsIsFalling(false))
    {
      // Not in a falling command but the controller is falling, start default fall
      StartCommand_Fall(0);
      SetFallYDiff(GetPosition()[1]);
      return;
    }
    //--------------------------------------------
    // handle jumping
#ifndef NO_GUI
#ifdef DEVELOPER
    if (DiagMenu.GetEngineValue(DayZPlayerConstants.DEBUG_ENABLEJUMP))
    {
      SHumanCommandClimbSettings hcls = GetDayZPlayerType().CommandClimbSettingsW();
      if (m_MovementState.m_iMovement != DayZPlayerConstants.MOVEMENTIDX_IDLE)
        hcls.m_fFwMaxDistance = 3;
      else
        hcls.m_fFwMaxDistance = 1.2;
      SHumanCommandClimbResult ret;
      HumanCommandClimb.DoClimbTest(this, ret, 0x3);
    }
#endif
#endif
    // start jump
    if (hic.IsJumpClimb())
    {
      m_JumpClimb.JumpOrClimb();
      if (m_JumpClimb.WasSuccessful())
        return;
    }
    HumanCommandAdditives ad = GetCommandModifier_Additives();
    bool force = false;
#ifndef NO_GUI
#ifdef DEVELOPER
    force = DiagMenu.GetEngineValue(DayZPlayerConstants.DEBUG_ENABLETALKING);
#endif
#endif
    float amplitude = IsPlayerSpeaking();
    if (amplitude > 0.1 || force)
    {
      if (ad)
        ad.SetTalking(true);
      // add noises on server
      if (GetGame().IsServer())
      {
        int now = GetGame().GetTime();
        if (now >= m_NextVoNNoiseTime)
        {
          m_NextVoNNoiseTime = now + 1000;
          int voiceLevel = GetGame().GetVoiceLevel(this);
          DayZPlayerType pt = GetDayZPlayerType();
          // add noise every second while talking
          NoiseParams vonpar;
          switch (voiceLevel)
          {
          case VoiceLevelWhisper:
            vonpar = pt.GetNoiseParamsWhisper();
            break;
          case VoiceLevelTalk:
            vonpar = pt.GetNoiseParamsTalk();
            break;
          case VoiceLevelShout:
            vonpar = pt.GetNoiseParamsShout();
            break;
          }
          AddNoise(vonpar);
        }
      }
    }
    else
    {
      if (ad)
        ad.SetTalking(false);
    }
    //--------------------------------------------
    // anything whats handled by InputController
    if (hic)
    {
      HumanCommandWeapons hcw = GetCommandModifier_Weapons();
      m_Throwing.HandleThrowing(hic, hcw, entityInHands, pDt);
      if (m_MeleeFightLogic.CanFight())
      {
        if (m_MeleeFightLogic.HandleFightLogic(pCurrentCommandID, hic, entityInHands, m_MovementState, m_ContinueFirearmMelee))
        {
          m_ProcessFirearmMeleeHit = isWeapon && (hic.IsMeleeWeaponAttack() || m_ProcessFirearmMeleeHit) || m_ContinueFirearmMelee;
          return;
        }
      }
    }
    if (ModCommandHandlerAfter(pDt, pCurrentCommandID, pCurrentCommandFinished))
      return;
  }
References AddCommandModifier_Action(), AddNoise(), DayZPlayerImplementFallDamage(), DayZPlayerType(), HumanCommandClimb::DoClimbTest(), ForceStandUpForHeavyItems(), PlayerConstants::FULL_SPRINT_DELAY_DEFAULT, GetCommand_Move(), GetCommand_Vehicle(), GetCommandModifier_Additives(), GetCommandModifier_Weapons(), GetDayZPlayerType(), DiagMenu::GetEngineValue(), GetGame(), GetInputController(), GetInstanceType(), GetMovementState(), GetPosition, GetUApi(), HumanCommandAdditives(), HumanCommandFall(), IsPlayerSpeaking(), m_MovementState, ModCommandHandlerAfter(), ModCommandHandlerBefore(), ModCommandHandlerInside(), NoiseParams(), PhysicsIsFalling(), SHumanCommandClimbSettings(), StartCommand_Fall(), StartCommand_Move(), StartCommand_Swim(), and StartCommand_Vehicle().
CommandHandlerDebug()
void DayZPlayer::CommandHandlerDebug (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline protected
debug handling of adding commands
set item in hands
fuj
start show
damage test
Definition at line 2236 of file DayZPlayerImplement.c.
  {
    if (GetPluginManager())
    {
      PluginDayzPlayerDebug playerDebug = PluginDayzPlayerDebug.Cast(GetPluginManager().GetPluginByType(PluginDayzPlayerDebug));
      if (playerDebug)
      {
        playerDebug.CommandHandler();
        if (m_DebugWeaponChangeStage == 0)
        {
          // debug weapon change
          int hideSlot;
          if (playerDebug.IsWeaponChange(m_DebugWeaponChangeItem, hideSlot, m_DebugWeaponChangeShowSlot))
          {
            //Print("Change Weapon started: " + m_DebugWeaponChangeItem + "," + hideSlot.ToString() + "," + m_DebugWeaponChangeShowSlot.ToString());
            HumanCommandWeapons w = GetCommandModifier_Weapons();
            w.StartAction(WeaponActions.HIDE, hideSlot);
            m_DebugWeaponChangeStage = 1;
          }
        }
        else if (m_DebugWeaponChangeStage == 1)
        {
          // wait for weapon hide to meet event
          HumanCommandWeapons w2 = GetCommandModifier_Weapons();
          if (w2 && w2.GetRunningAction() == WeaponActions.HIDE)
          {
            if (w2.IsEvent() == WeaponEvents.CHANGE_HIDE)
            {
              //Print("Change Weapon - hidden: ");
              PlayerBase player = PlayerBase.Cast(this);
              EntityAI item_in_hands = player.GetHumanInventory().GetEntityInHands();
              if (item_in_hands != NULL && player.CanDropEntity(item_in_hands) && GetGame().GetPlayer().GetHumanInventory().CanRemoveEntityInHands())
                player.PredictiveDropEntity(item_in_hands);
              if (m_DebugWeaponChangeItem != "")
              {
                InventoryLocation dst = new InventoryLocation;
                dst.SetHands(this, NULL);
                EntityAI item = SpawnEntity(m_DebugWeaponChangeItem, dst, ECE_IN_INVENTORY, RF_DEFAULT);
              }
              w2.StartAction(WeaponActions.SHOW, 3);
              m_DebugWeaponChangeStage = 2;
            }
          }
        }
        else if (m_DebugWeaponChangeStage == 2)
        {
          HumanCommandWeapons w3 = GetCommandModifier_Weapons();
          if (w3 && w3.IsActionFinished())
            m_DebugWeaponChangeStage = 0;
        }
      }
    }
    if (m_TestDamageCounter >= 0)
    {
      if (m_TestDamageCounter > 3)
      {
        m_DebugDirectionVal = m_DebugDirectionVal + 90;
        m_TestDamageCounter = 0;
        if (m_DebugDirectionVal > 90)
        {
          m_DebugDirectionVal = -180;
          m_DebugTypeVal = !m_DebugTypeVal;
        }
        if (m_DebugTypeVal)
        {
          AddCommandModifier_Damage(0, m_DebugDirectionVal); // starts light
        }
        else
        {
          StartCommand_Damage(0, m_DebugDirectionVal); // starts heavy (full body)
        }
        // 0.. types
        // from: -180 back, -90 left, 0 front, 90 right, 180 back
        //AddCommandModifier_Damage(0, directionVal); // starts light
        //StartCommand_Damage(0, 0); // starts heavy (full body)
      }
      m_TestDamageCounter += pDt;
    }
#ifndef NO_GUI
#ifdef DEVELOPER
    // injury / exhaustion
    {
      HumanCommandAdditives ad = GetCommandModifier_Additives();
      float v = DiagMenu.GetEngineRangeValue(DayZPlayerConstants.DEBUG_SHOWINJURY);
      if (v > 0)
        ad.SetInjured(v, true);
      v = DiagMenu.GetEngineRangeValue(DayZPlayerConstants.DEBUG_SHOWEXHAUSTION);
      if (v > 0)
        ad.SetExhaustion(v, true);
    }
#endif
#endif
  }
References AddCommandModifier_Damage(), ECE_IN_INVENTORY, GetCommandModifier_Additives(), GetCommandModifier_Weapons(), DiagMenu::GetEngineRangeValue(), GetGame(), GetPlayer(), GetPluginManager(), HumanCommandAdditives(), PluginDayzPlayerDebug(), RF_DEFAULT, SpawnEntity(), and StartCommand_Damage().
CommitedSuicide()
bool DayZPlayer::CommitedSuicide () inline protected
Definition at line 3280 of file DayZPlayerImplement.c.
  {
    return m_Suicide;
  }
CompleteWeaponRaise()
void DayZPlayer::CompleteWeaponRaise () inline protected
Definition at line 724 of file DayZPlayerImplement.c.
  {
    m_WeaponRaiseTime = 0;
    m_WeaponRaiseCompleted = true;
  }
DayZPlayerImplement()
void DayZPlayer::DayZPlayerImplement () inline protected
constructor
Definition at line 147 of file DayZPlayerImplement.c.
  {
    m_SprintFull = false;
    m_SprintedTime = 0;
    m_SprintedTimePerStanceMin = PlayerConstants.FULL_SPRINT_DELAY_DEFAULT;
    m_AimingModel = new DayZPlayerImplementAiming(this);
    m_MeleeCombat = new DayZPlayerImplementMeleeCombat(this);
    m_MeleeFightLogic = new DayZPlayerMeleeFightLogic_LightHeavy(this);
    m_Swimming = new DayZPlayerImplementSwimming(this);
    m_Throwing = new DayZPlayerImplementThrowing(this);
    m_JumpClimb = new DayZPlayerImplementJumpClimb(this);
    m_FallDamage = new DayZPlayerImplementFallDamage(this);
    m_ADSAutomationTimer = new Timer();
    m_bADS = false;
    m_WeaponRaiseCompleted = false;
    SetOptics(false);
    m_IsShootingFromCamera = true;
    m_ProcessFirearmMeleeHit = false;
    m_ContinueFirearmMelee = false;
    m_WasIronsight = true; //initially uses ironsights by default
#ifdef PLATFORM_CONSOLE
    m_Camera3rdPerson = !GetGame().GetWorld().Is3rdPersonDisabled();
#endif
    m_LastSurfaceUnderHash = ("cp_gravel").Hash();
    m_NextVoNNoiseTime = 0;
    m_SyncedHitDataArray = new array<ref SyncHitInfo>;
    m_CurrentWaterLevel = 0;
    m_WeaponRaiseTime = 0;
    RegisterNetSyncVariableBoolSignal("m_TriggerPullPlayerOutOfVehicleSynch");
  }
References DayZPlayerImplementFallDamage(), DayZPlayerImplementMeleeCombat(), DayZPlayerMeleeFightLogic_LightHeavy(), PlayerConstants::FULL_SPRINT_DELAY_DEFAULT, GetGame(), and m_MeleeCombat.
DepleteStamina()
void DayZPlayer::DepleteStamina (EStaminaModifiers modifier, float dT = -1) inline protected
Definition at line 377 of file DayZPlayerImplement.c.
{};
Referenced by HandleComboHit(), HandleFightLogic(), HandleInitialFirearmMelee(), HandleInitialMeleeErc(), HandleProneKick(), HandleSprintAttack(), and SymptomBase::OnAnimationFinish().
EEHitBy()
override void DayZPlayer::EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline protected
event from damage system
Definition at line 1252 of file DayZPlayerImplement.c.
  {
    super.EEHitBy(damageResult, damageType, source, component, dmgZone, ammo, modelPos, speedCoef);
    m_TransportHitRegistered = false;
    if (!IsAlive())
    {
      int animTypeDeath;
      float animHitDirDeath;
      if (EvaluateDeathAnimation(damageType, source, ammo, animTypeDeath, animHitDirDeath))
        SendDeathJuncture(animTypeDeath, animHitDirDeath);
      if (!m_DeathSyncSent) //checked until the death is evaluated by 'OnCommandHandlerTick' higher up the road
      {
        Man killer = source.GetHierarchyRootPlayer();
        if (!m_KillerData) //only one player is considered killer in the event of crossfire
        {
          m_KillerData = new KillerData();
          m_KillerData.m_Killer = killer;
          m_KillerData.m_MurderWeapon = source;
        }
        if (killer && killer.IsPlayer())
        {
          // was player killed by headshot?
          if (dmgZone == "Brain")
          {
            m_KilledByHeadshot = true;
            if (m_KillerData.m_Killer == killer)
              m_KillerData.m_KillerHiTheBrain = true;
          }
        }
      }
    }
    else
    {
      int animType;
      float animHitDir;
      bool animHitFullbody;
      if (EvaluateDamageHitAnimation(damageResult, damageType, source, dmgZone, ammo, modelPos, animType, animHitDir, animHitFullbody))
        DayZPlayerSyncJunctures.SendDamageHitEx(this, animType, animHitDir, animHitFullbody, damageResult, damageType, source, dmgZone, ammo, modelPos);
      else
      {
        bool skipSoundRequest = false;
        if (damageType == DamageType.CUSTOM && GetCommand_Fall())
          skipSoundRequest = GetFallDamage().GetLandType() < HumanCommandFall.LANDTYPE_MEDIUM;
        if (!skipSoundRequest)
          RequestSoundEvent(EPlayerSoundEventID.TAKING_DMG_LIGHT);
      }
    }
    // interupt melee for non-blocked hit or heavy hit
    if (animHitFullbody)
    {
      HumanCommandMelee2 hcm = GetCommand_Melee2();
      if (hcm)
        hcm.Cancel();
    }
  }
References component, GetCommand_Fall(), GetCommand_Melee2(), HumanCommandFall(), and DayZPlayerSyncJunctures::SendDamageHitEx().
EEKilled()
override void DayZPlayer::EEKilled (Object killer) inline protected
Definition at line 605 of file DayZPlayerImplement.c.
  {
    SendDeathJuncture(-1, 0);
    super.EEKilled(killer);
  }
EOnContact()
void DayZPlayer::EOnContact (IEntity other, Contact extra) inline protected
Phx contact event
Definition at line 3293 of file DayZPlayerImplement.c.
  {
    if (!IsAlive())
      return;
    if (GetParent() == other)
      return;
    Transport transport = Transport.Cast(other);
    if (transport)
    {
      if (GetGame().IsServer())
        RegisterTransportHit(transport);
    }
  }
References GetGame(), and GetParent().
EvaluateDamageHit()
void DayZPlayer::EvaluateDamageHit (int pCurrentCommandID) inline protected
Must be ran at the start of CommandHandler before Jump is triggered.
Reset damage hit to prevent animation from playing unnecessarily when it is already cancelled out
ignore hit impacts in prone (for now)
Definition at line 1051 of file DayZPlayerImplement.c.
  {
    m_DamageHitAnimType = -1;
    if (!m_SyncedHitDataArray || m_SyncedHitDataArray.Count() == 0)
      return;
    //evaluate all hit data
    SyncHitInfo data;
    SyncHitInfo greatest_hit;
    for (int i = 0; i < m_SyncedHitDataArray.Count(); i++)
    {
      data = m_SyncedHitDataArray[i];
      m_DamageHitDir = data.m_HitDir;
      //client-side effects
#ifndef SERVER
      if (IsAlive() && !IsUnconscious() && data.m_HasSource && GetGame().GetMission().GetHud() && GetGame().GetPlayer() == this) //only for controlled players
      {
        m_DamageHealth = data.m_HealthDamage;
        if (m_DamageHealth > 0.0)
        {
          float rel = m_DamageHealth / (GetMaxHealth("", "Health") * PlayerConstants.HEAVY_HIT_THRESHOLD);
          GetGame().GetMission().GetHud().SpawnHitDirEffect(this, m_DamageHitDir, rel);
        }
      }
#endif
      if (!greatest_hit)
        greatest_hit = data;
      //else if (data.m_HealthDamage > greatest_hit.m_HealthDamage || (data.m_Fullbody && !greatest_hit.m_Fullbody)) //TODO - revisit cumulative calculation for animation evaluation purposes (stagger on shotgun to the chest)
      else if (data.m_Fullbody) //temporary solution; last fullbody hit is used for animation purposes, some light hit otherwise
        greatest_hit = data;
    }
    m_SyncedHitDataArray.Clear();
    m_DamageHealth = 0.0;
    if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_PRONE || m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
      return;
    //general effects
    m_DamageHitFullbody = greatest_hit.m_Fullbody;
    m_DamageHitAnimType = greatest_hit.m_AnimType;
    m_DamageHitDir = greatest_hit.m_HitDir;
  }
References GetGame(), GetPlayer(), PlayerConstants::HEAVY_HIT_THRESHOLD, and m_MovementState.
EvaluateDamageHitAnimation()
bool DayZPlayer::EvaluateDamageHitAnimation (TotalDamageResult pDamageResult, int pDamageType, EntityAI pSource, string pComponent, string pAmmoType, vector pModelPos, out int pAnimType, out float pAnimHitDir, out bool pAnimHitFullbody) inline protected
selects animation type and direction based on damage system data
impact from infected attack will be light only
play full body when these coponents were hit
skip evaluation of dmg hit animation
direction
Definition at line 1174 of file DayZPlayerImplement.c.
  {
    int invertHitDir = 0; //Used to flip the heavy hit animation direction
    pAnimType = 0;
    pAnimHitFullbody = false; // additive anm
    GetMovementState(m_MovementState);
    switch (pDamageType)
    {
    case DT_CLOSE_COMBAT:
      if (pSource.IsInherited(DayZInfected))
        break;
      pAnimType = GetGame().ConfigGetInt("cfgAmmo " + pAmmoType + " hitAnimation");
      invertHitDir = GetGame().ConfigGetInt("cfgAmmo " + pAmmoType + " invertHitDir");
      if (!IsUnconscious() && pAnimType == 1 && !m_MeleeFightLogic.IsInBlock())
        pAnimHitFullbody = true;
      break;
    case DT_FIRE_ARM:
      int impactBehaviour = 0;
      if (!IsUnconscious() && GetHealth("", "Shock") > 25)
      {
        if (pComponent == "Torso" || pComponent == "Head")
        {
          impactBehaviour = GetGame().ConfigGetInt("cfgAmmo " + pAmmoType + " impactBehaviour");
          float fireDamage = pDamageResult.GetHighestDamage("Health");
          float shockDamage = pDamageResult.GetHighestDamage("Shock");
          if ((fireDamage > 80.0 || shockDamage > 40.0) && impactBehaviour == 1)
            pAnimHitFullbody = true;
        }
      }
      break;
    case DT_EXPLOSION:
      break;
    case DT_CUSTOM:
      pAnimType = GetGame().ConfigGetInt("cfgAmmo " + pAmmoType + " hitAnimation");
      if (pAnimType == 1)
        pAnimHitFullbody = true;
      else
        return false;
      break;
    }
    vector targetDirection = GetDirection();
    vector toSourceDirection = (pSource.GetPosition() - GetPosition());
    targetDirection[1] = 0;
    toSourceDirection[1] = 0;
    targetDirection.Normalize();
    toSourceDirection.Normalize();
    float cosFi = vector.Dot(targetDirection, toSourceDirection);
    vector cross = targetDirection * toSourceDirection;
    pAnimHitDir = Math.Acos(cosFi) * Math.RAD2DEG;
    // We will invert direction of the hit
    if (invertHitDir > 0)
      pAnimHitDir -= 180;
    if (cross[1] < 0)
      pAnimHitDir = -pAnimHitDir;
    return true;
  }
References Math::Acos(), vector::Dot(), GetGame(), GetMovementState(), GetPosition, m_MovementState, and Math::RAD2DEG.
EvaluateDeathAnimation()
bool DayZPlayer::EvaluateDeathAnimation (int pDamageType, EntityAI pSource, string pAmmoType, out int pAnimType, out float pAnimHitDir) inline protected
selects animation type and direction based on damage system data
direction
Definition at line 1145 of file DayZPlayerImplement.c.
  {
    bool doPhxImpulse = GetGame().ConfigGetInt("cfgAmmo " + pAmmoType + " doPhxImpulse") > 0;
    pAnimType = DayZPlayerConstants.DEATH_DEFAULT;
    if (doPhxImpulse)
      pAnimType = DayZPlayerConstants.DEATH_FAST;
    vector targetDirection = GetDirection();
    vector toSourceDirection = (pSource.GetPosition() - GetPosition());
    targetDirection[1] = 0;
    toSourceDirection[1] = 0;
    targetDirection.Normalize();
    toSourceDirection.Normalize();
    float cosFi = vector.Dot(targetDirection, toSourceDirection);
    vector cross = targetDirection * toSourceDirection;
    pAnimHitDir = Math.Acos(cosFi) * Math.RAD2DEG;
    if (cross[1] < 0)
      pAnimHitDir = -pAnimHitDir;
    return true;
  }
References Math::Acos(), vector::Dot(), GetGame(), GetPosition, and Math::RAD2DEG.
ExitSights()
void DayZPlayer::ExitSights () inline protected
Definition at line 324 of file DayZPlayerImplement.c.
  {
    ItemOptics optics = null;
    EntityAI entityInHands = GetHumanInventory().GetEntityInHands();
    Weapon weapon = Weapon.Cast(entityInHands);
    if (weapon)
      optics = weapon.GetAttachedOptics();
    else
      optics = ItemOptics.Cast(entityInHands);
    SetIronsights(false);
    SetOptics(false);
    if (optics)
      SwitchOptics(optics, false);
    HumanCommandWeapons hcw = GetCommandModifier_Weapons();
    if (hcw)
      hcw.SetADS(false);
  }
References GetCommandModifier_Weapons().
GetAimingModel()
DayZPlayerImplementAiming DayZPlayer::GetAimingModel () inline protected
Definition at line 179 of file DayZPlayerImplement.c.
  {
    return m_AimingModel;
  }
GetBackAttachmentType()
AnimBackType DayZPlayer::GetBackAttachmentType () inline protected
Definition at line 2669 of file DayZPlayerImplement.c.
  {
    EntityAI back = GetInventory().FindAttachment(InventorySlots.BACK);
    if (back)
    {
      switch (back.GetAttachmentSoundType())
      {
      case "Small":
        return AnimBackType.Small;
      case "Military":
        return AnimBackType.Military;
      case "Outdoor":
        return AnimBackType.Outdoor;
      case "Ghillie":
        return AnimBackType.Ghillie;
      }
    }
    return AnimBackType.None;
  }
GetBodyAttachmentType()
AnimUpperBodyType DayZPlayer::GetBodyAttachmentType () inline protected
Definition at line 2638 of file DayZPlayerImplement.c.
  {
    EntityAI attachment = GetInventory().FindAttachment(InventorySlots.BODY);
    if (attachment)
    {
      switch (attachment.GetAttachmentSoundType())
      {
      case "NylonJacket":
        return AnimUpperBodyType.NylonJacket;
      case "TShirt":
        return AnimUpperBodyType.TShirt;
      case "WoolShirt":
        return AnimUpperBodyType.WoolShirt;
      case "HeavyJacket":
        return AnimUpperBodyType.HeavyJacket;
      case "LeatherJacket":
        return AnimUpperBodyType.LeatherJacket;
      case "Coat":
        return AnimUpperBodyType.Coat;
      case "ChemlonDress":
        return AnimUpperBodyType.ChemlonDress;
      case "Ghillie":
        return AnimUpperBodyType.Ghillie;
      case "Chainmail":
        return AnimUpperBodyType.Chainmail;
      }
    }
    return AnimUpperBodyType.None;
  }
GetBootsType()
AnimBootsType DayZPlayer::GetBootsType () inline protected
Definition at line 2620 of file DayZPlayerImplement.c.
  {
    EntityAI boots = GetInventory().FindAttachment(InventorySlots.FEET);
    if (boots)
    {
      switch (boots.GetAttachmentSoundType())
      {
      case "Sneakers":
        return AnimBootsType.Sneakers;
      case "Boots":
        return AnimBootsType.Boots;
      }
    }
    return AnimBootsType.None;
  }
GetCurrentWaterLevel()
override float DayZPlayer::GetCurrentWaterLevel () inline protected
Definition at line 286 of file DayZPlayerImplement.c.
  {
    return m_CurrentWaterLevel;
  }
Referenced by InterruptWaterCheck().
GetDayZPlayerInventory()
DayZPlayerInventory DayZPlayer::GetDayZPlayerInventory () inline protected
Definition at line 741 of file DayZPlayerImplement.c.
  {
    DayZPlayerInventory inv = DayZPlayerInventory.Cast(GetInventory());
    return inv;
  }
Referenced by ActionPossibilityCheck(), and CanPlayEmote().
GetDebugText()
override string DayZPlayer::GetDebugText () inline protected
Definition at line 417 of file DayZPlayerImplement.c.
  {
    string text = super.GetDebugText();
    text += "Parent: " + Object.GetDebugName(Object.Cast(GetParent())) + "\n";//keep
    text += "IsSimulationDisabled: " + GetIsSimulationDisabled() + "\n";//keep
    /*
      text += "DamageDestroyed: " + IsDamageDestroyed() + "\n";
      text += "DeathProcessed: " + IsDeathProcessed() + "\n";
      text += "DeathConditionMet: " + IsDeathConditionMet() + "\n";
      text += "PullOutOfVehicleState: " + m_PullPlayerOutOfVehicleState + "\n";
      text += "PullOutOfVehicleSynch: " + m_TriggerPullPlayerOutOfVehicleSynch + "\n";
      text += "Position: " + GetPosition() + "\n";*/
    return text;
  }
References GetParent().
GetDeltaT()
float DayZPlayer::GetDeltaT () inline protected
Definition at line 403 of file DayZPlayerImplement.c.
  {
    return m_dT;
  }
GetEyeZoomLevel()
override int DayZPlayer::GetEyeZoomLevel () inline protected
Definition at line 214 of file DayZPlayerImplement.c.
  {
    return m_CameraEyeZoomLevel;
  }
Referenced by DayZPlayerCameraBase(), HoldBreathFOVEffect(), and StdFovUpdate().
GetFallDamage()
DayZPlayerImplementFallDamage DayZPlayer::GetFallDamage () inline protected
Definition at line 199 of file DayZPlayerImplement.c.
  {
    return m_FallDamage;
  }
GetMeleeCombat()
DayZPlayerImplementMeleeCombat DayZPlayer::GetMeleeCombat () inline protected
Definition at line 184 of file DayZPlayerImplement.c.
  {
    return m_MeleeCombat;
  }
References m_MeleeCombat.
Referenced by Init().
GetMeleeFightLogic()
DayZPlayerMeleeFightLogic_LightHeavy DayZPlayer::GetMeleeFightLogic () inline protected
Definition at line 189 of file DayZPlayerImplement.c.
  {
    return m_MeleeFightLogic;
  }
GetShoulderAttachmentType()
AnimRangedWeaponType DayZPlayer::GetShoulderAttachmentType () inline protected
Definition at line 2691 of file DayZPlayerImplement.c.
  {
    EntityAI shoulderAttachment = GetInventory().FindAttachment(InventorySlots.SHOULDER);
    EntityAI meleeAttachment = GetInventory().FindAttachment(InventorySlots.MELEE);
    AnimRangedWeaponType shoulderAttType = AnimRangedWeaponType.None;
    AnimRangedWeaponType meleeAttType = AnimRangedWeaponType.None;
    if (shoulderAttachment)
    {
      switch (shoulderAttachment.GetAttachmentSoundType())
      {
      case "Shotgun":
      {
        shoulderAttType = AnimRangedWeaponType.Shotgun;
        break;
      }
      case "Rifle":
      {
        shoulderAttType = AnimRangedWeaponType.Rifle;
        break;
      }
      }
    }
    if (meleeAttachment)
    {
      switch (meleeAttachment.GetAttachmentSoundType())
      {
      case "Shotgun":
      {
        meleeAttType = AnimRangedWeaponType.Shotgun;
        break;
      }
      case "Rifle":
      {
        meleeAttType = AnimRangedWeaponType.Rifle;
        break;
      }
      }
    }
    if (shoulderAttType == AnimRangedWeaponType.Shotgun || meleeAttType == AnimRangedWeaponType.Shotgun)
      return AnimRangedWeaponType.Shotgun;
    if (shoulderAttType == AnimRangedWeaponType.Rifle || meleeAttType == AnimRangedWeaponType.Rifle)
      return AnimRangedWeaponType.Rifle;
    return AnimRangedWeaponType.None;
  }
GetSlidePoseAngle()
float DayZPlayer::GetSlidePoseAngle () inline protected
Definition at line 3256 of file DayZPlayerImplement.c.
  {
    return GetDayZPlayerType().CommandMoveSettingsW().m_fSlidingPoseAngle;
  }
References GetDayZPlayerType().
GetSurfaceType()
string DayZPlayer::GetSurfaceType (SurfaceAnimationBone limbType) inline protected
Definition at line 2741 of file DayZPlayerImplement.c.
  {
    string surfaceType;
    int liquidType;
    g_Game.SurfaceUnderObjectByBone(this, limbType, surfaceType, liquidType);
    return surfaceType;
  }
References g_Game.
GetThrowing()
DayZPlayerImplementThrowing DayZPlayer::GetThrowing () inline protected
Definition at line 194 of file DayZPlayerImplement.c.
  {
    return m_Throwing;
  }
Referenced by ActionPossibilityCheck(), and CanPlayEmote().
GetTypeOfDeath()
int DayZPlayer::GetTypeOfDeath (int pCurrentCommandID) inline protected
Definition at line 572 of file DayZPlayerImplement.c.
  {
    switch (pCurrentCommandID)
    {
    case DayZPlayerConstants.COMMANDID_SWIM:
      return DayZPlayerConstants.DEATH_WATER;
    case DayZPlayerConstants.COMMANDID_FALL:
      return DayZPlayerConstants.DEATH_FALL;
    case DayZPlayerConstants.COMMANDID_UNCONSCIOUS:
      HumanCommandUnconscious hcu = GetCommand_Unconscious();
      if (hcu)
      {
        if (hcu.IsOnLand())
          return DayZPlayerConstants.DEATH_UNCON_ON_LAND;
        if (hcu.IsInWater())
          return DayZPlayerConstants.DEATH_UNCON_IN_WATER;
      }
      break;
    }
    return DayZPlayerConstants.DEATH_BODY;
  }
References GetCommand_Unconscious().
GetWeaponManager()
WeaponManager DayZPlayer::GetWeaponManager () inline protected
Definition at line 810 of file DayZPlayerImplement.c.
{ return null; }
Referenced by ActionPossibilityCheck(), CanPlayEmote(), HandsContainer::GetCombinationFlags(), HandsContainer::OnPerformCombination(), and ScriptedWidgetEventHandler::SetWeaponModeAndZeroing().
HandleADS()
void DayZPlayer::HandleADS () inline protected
This is main command logic
artificial Auto-ADS delay
if !raised if sprinting
Definition at line 1531 of file DayZPlayerImplement.c.
  {
    if (!IsAlive())
    {
      if (m_CameraIronsight || m_CameraOptics)
        ExitSights();
      return;
    }
    bool bADSToggle = false;
    bool exitSights = false;
    HumanInputController hic = GetInputController();
    HumanItemAccessor hia = GetItemAccessor();
    HumanCommandWeapons hcw = GetCommandModifier_Weapons();
    PlayerBase playerPB = PlayerBase.Cast(this);
    GetMovementState(m_MovementState);
    if (playerPB.IsRolling())
      exitSights = true;
    if (m_ResetADS || !hia.IsItemInHandsWeapon())
    {
      hic.ResetADS();
      m_ResetADS = false;
    }
    if (!m_MovementState.IsRaised() || m_LiftWeapon_player)
    {
      ResetWeaponRaiseProgress();
      exitSights = true;
    }
    else
    {
      if (m_bADS != hic.WeaponADS())
      {
        m_bADS = hic.WeaponADS();
        bADSToggle = true;
      }
      if (m_bADS && !m_CameraIronsight && !m_CameraOptics)
      {
        if (!IsWeaponRaiseCompleted())
        {
          bADSToggle = false;
          exitSights = true;
        }
        else
          bADSToggle = true;
      }
    }
    if (bADSToggle && !GetCommand_Melee2() && !GetThrowing().IsThrowingModeEnabled())
    {
      if (hia.IsItemInHandsWeapon() && playerPB.GetItemInHands() && playerPB.GetItemInHands().IsWeapon() && playerPB.GetWeaponManager() && !playerPB.GetWeaponManager().IsRunning())
      {
        Weapon_Base weapon = Weapon_Base.Cast(GetHumanInventory().GetEntityInHands());
        ItemOptics optic = weapon.GetAttachedOptics();
        bool switchToADS = false;
        bool canUseIronsights = weapon.CanEnterIronsights();
        bool canUseOptics = optic != NULL;
        if (canUseIronsights || canUseOptics)
          switchToADS = m_bADS;
        // go to ironsights - disable ironsights when
        if (!m_MovementState.IsRaised() || m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_SPRINT)
          switchToADS = false;
        // fixes camera switching during item transitions
        if (IsLiftWeapon() || !IsRaised() || GetDayZPlayerInventory().IsProcessing() || !IsWeaponRaiseCompleted() || IsFighting())
          exitSights = true;
        else if (switchToADS) // enter ironsights or optics
        {
          // filter by usability
          if (m_WasIronsight && !canUseIronsights)
            m_WasIronsight = false;
          else if (!m_WasIronsight && !canUseOptics)
            m_WasIronsight = true;
          if (m_WasIronsight)
          {
            hic.ResetFreeLookToggle();
            SwitchOptics(optic, false);
            SetIronsights(true);
          }
          else if (!m_WasIronsight || (!canUseIronsights && canUseOptics))
          {
            SetIronsights(false);
            SwitchOptics(optic, true);
          }
          else
            exitSights = true;
          if (hcw && (m_CameraOptics/* || m_CameraIronsight*/))
            hcw.SetADS(true);
        }
        else
          exitSights = true;
      }
    }
    // leave ironsight and/ or optics
    if (exitSights && !IsHandheldOpticsInUse() && (m_CameraIronsight || m_CameraOptics) || GetCommand_Melee2())
      ExitSights();
  }
References GetCommand_Melee2(), GetCommandModifier_Weapons(), GetInputController(), GetItemAccessor(), GetMovementState(), HumanItemAccessor(), IsProcessing(), IsRaised(), and m_MovementState.
HandleDamageHit()
bool DayZPlayer::HandleDamageHit (int pCurrentCommandID) inline protected
Definition at line 1100 of file DayZPlayerImplement.c.
  {
    // Update elapsed time since hit first
    if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_DAMAGE)
    {
      // Throttle heavy hit command up to a fixed rate
      if (m_HitElapsedTime < HIT_INTERVAL_MIN)
      {
        m_HitElapsedTime += m_dT;
        ResetDamageHitState(false);
        return false;
      }
    }
    // If transportcache is not null, player is unconscious inside of a car and should not head into a damage command
    if (m_DamageHitAnimType != -1 && m_TransportCache == null && !CommitedSuicide())
    {
      HumanCommandVehicle vehCommand = GetCommand_Vehicle();
      if (m_DamageHitFullbody && (!vehCommand || vehCommand.IsGettingIn() || vehCommand.IsGettingOut()))
      {
        StartCommand_Damage(m_DamageHitAnimType, m_DamageHitDir);
        ResetDamageHitState(true);
        return true;
      }
      else
      {
        AddCommandModifier_Damage(m_DamageHitAnimType, m_DamageHitDir);
        ResetDamageHitState(false);
        return false;
      }
    }
    return pCurrentCommandID == DayZPlayerConstants.COMMANDID_DAMAGE;
  }
References AddCommandModifier_Damage(), GetCommand_Vehicle(), and StartCommand_Damage().
HandleDeath()
bool DayZPlayer::HandleDeath (int pCurrentCommandID) inline protected
Can't pull a body out of a car that is in water, don't need to handle that
Definition at line 488 of file DayZPlayerImplement.c.
  {
    if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_DEATH)
    {
      switch (m_PullPlayerOutOfVehicleState)
      {
      case -1:
        break;
      case 0:
        m_PullPlayerOutOfVehicleState = -1;
        PhysicsSetSolid(true);
        DayZPlayerVehicleCommandDeathCallback callbackVeh;
        Class.CastTo(callbackVeh, StartCommand_Death(DayZPlayerConstants.DEATH_PULL_OUT_TRANSPORT, 0, DayZPlayerVehicleCommandDeathCallback, m_PullPlayerOutOfVehicleKeepsInLocalSpace));
        Class.CastTo(callbackVeh.m_pPlayer, this);
        break;
      }
      return true;
    }
    if (m_DeathAnimType != -2 && g_Game.GetMissionState() == g_Game.MISSION_STATE_GAME)
    {
      if (!CommitedSuicide())
      {
        int type = m_DeathAnimType;
        if (type == DayZPlayerConstants.DEATH_DEFAULT)
          type = GetTypeOfDeath(pCurrentCommandID);
        m_WasInVehicle = false;
        HumanCommandVehicle hcv = GetCommand_Vehicle();
        if (hcv)
        {
          m_TransportCache = hcv.GetTransport();
          m_WasInVehicle = !hcv.IsGettingIn() && !hcv.IsGettingOut();
        }
        bool keepInLocalSpace = false;
        if (IsUnconscious() || m_WasInVehicle)
        {
          if (m_TransportCache)
          {
            m_TransportCache.CrewDeath(m_TransportCache.CrewMemberIndex(this));
            m_TransportCache.MarkCrewMemberDead(m_TransportCache.CrewMemberIndex(this));
          }
        }
        else
        {
          if (m_TransportCache)
          {
            m_TransportCache.CrewGetOut(m_TransportCache.CrewMemberIndex(this));
            m_TransportCache.MarkCrewMemberDead(m_TransportCache.CrewMemberIndex(this));
          }
          keepInLocalSpace = m_PullPlayerOutOfVehicleKeepsInLocalSpace;
        }
        DisableSimulation(false);
        GetItemAccessor().HideItemInHands(false);
        m_TransportCache = null;
        DayZPlayerCommandDeathCallback callback;
        Class.CastTo(callback, StartCommand_Death(type, m_DeathHitDir, DayZPlayerCommandDeathCallback, keepInLocalSpace));
        Class.CastTo(callback.m_pPlayer, this);
      }
      else
        PhysicsSetRagdoll(true);
      // disable voice communication
      GetGame().GetWorld().SetVoiceOn(false, false);
      return true;
    }
    return false;
  }
References Class::CastTo(), g_Game, GetCommand_Vehicle(), GetGame(), GetItemAccessor(), PhysicsSetRagdoll(), PhysicsSetSolid(), and StartCommand_Death().
HandleOptic()
void DayZPlayer::HandleOptic (notnull ItemOptics optic, bool inHands, HumanInputController pInputs, out bool pExitOptics) inline protected
Definition at line 949 of file DayZPlayerImplement.c.
  {
    UAInterface input = GetInputInterface();
    if (!input)
      return;
    Weapon_Base weapon;
    int FOVcount;
    bool controllerPressIn;
    bool controllerPressOut;
    if (input.SyncedPress_ID(UAZoomInOptics))
    {
      weapon = Weapon_Base.Cast(optic.GetHierarchyParent());
      FOVcount = optic.GetStepFOVCount();
      controllerPressIn = input.SyncedPress_ID(UAZoomInOpticsControllerHelper);
      if (weapon && m_CameraIronsight && !m_CameraOptics)
      {
        SetIronsights(false);
        SwitchOptics(optic, true);
        optic.SetStepFOVIndex(0);
      }
      else if (m_CameraOptics)
      {
        if (controllerPressIn) //controller
        {
          if (!optic.StepFOVUp())
          {
            if (FOVcount > 0)
            {
              optic.SetStepFOVIndex(0); //loop to minimum magnification
            }
            if (weapon && weapon.CanEnterIronsights()) //loop into ironsights
            {
              SwitchOptics(optic, false);
              pInputs.ResetFreeLookToggle();
              SetIronsights(true);
            }
          }
        }
        else //m&k
          optic.StepFOVUp();
      }
    }
    if (input.SyncedPress_ID(UAZoomOutOptics))
    {
      weapon = Weapon_Base.Cast(optic.GetHierarchyParent());
      FOVcount = optic.GetStepFOVCount();
      controllerPressOut = input.SyncedPress_ID(UAZoomOutOpticsControllerHelper);
      if (m_CameraOptics)
      {
        if (!optic.StepFOVDown())
        {
          if (controllerPressOut)
          {
            if (FOVcount > 0 && (!weapon || !weapon.CanEnterIronsights()))
            {
              optic.SetStepFOVIndex(FOVcount - 1); //loop to maximum magnification
            }
          }
          if (weapon && weapon.CanEnterIronsights())
          {
            SwitchOptics(optic, false);
            pInputs.ResetFreeLookToggle();
            SetIronsights(true);
          }
        }
      }
      else if (controllerPressOut && weapon && m_CameraIronsight)
      {
        SwitchOptics(optic, true);
        if (FOVcount > 0)
        {
          optic.SetStepFOVIndex(FOVcount - 1); //loop to maximum magnification
        }
      }
    }
  }
HandleView()
void DayZPlayer::HandleView () inline protected
3rd person camera
Definition at line 1640 of file DayZPlayerImplement.c.
  {
    if (!IsAlive())
    {
      if (m_CameraIronsight || m_CameraOptics)
        ExitSights();
      return;
    }
    HumanInputController hic = GetInputController();
    bool camChange = hic.CameraViewChanged();
    if (IsRaised())
    {
      if (m_IsWeapon)
        camChange = false;
    }
    if (GetGame().GetWorld().Is3rdPersonDisabled())
      m_Camera3rdPerson = false;
    else if (camChange)
      m_Camera3rdPerson = !m_Camera3rdPerson;
    // exits optics completely, comment to return to ADS
    if (m_LiftWeapon_player && (m_CameraOptics || m_CameraIronsight))
      ExitSights();
    if (IsPlayerInStance(DayZPlayerConstants.STANCEMASK_RAISEDPRONE) && (m_CameraOptics || m_CameraIronsight))
      GetDayZPlayerType().SetVerticalMinimumAimLimit(DayZPlayerCameraIronsights.CONST_UD_MIN_BACK);
    else
      GetDayZPlayerType().SetVerticalMinimumAimLimit(DayZPlayerCameraIronsights.CONST_UD_MIN);
    if (hic.IsZoomToggle() && !m_MovementState.IsRaised())
    {
      m_CameraEyeZoomLevel = ECameraZoomType.NORMAL;
      if ((IsClimbingLadder() && Math.AbsInt(m_MovementState.m_iMovement) == 2) || (IsSwimming() && m_MovementState.m_iMovement == 3))
        m_CameraEyeZoomLevel = ECameraZoomType.SHALLOW;
      else if (!IsClimbingLadder() && !IsSwimming() && !IsInVehicle())
      {
        float pSpeed;
        vector pLocalDirection;
        hic.GetMovement(pSpeed, pLocalDirection);
        if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_ERECT && pSpeed == 3)
          m_CameraEyeZoomLevel = ECameraZoomType.SHALLOW;
      }
    }
    else
      m_CameraEyeZoomLevel = ECameraZoomType.NONE;
    if (m_MovementState.IsRaisedInProne())
    {
      float headingAngle = MiscGameplayFunctions.GetHeadingAngle(this);
      float headingAngleDiffBlock = Math.AbsFloat(m_LastHeadingAngleBlock - headingAngle);
      float headingAngleDiffBlock2 = Math.AbsFloat(m_LastHeadingAngleBlock2 - headingAngle);
      float headingAngleDiff = 0.0;
      if (m_LastHeadingAngle * headingAngle < 0.0)
        headingAngleDiff = Math.AbsFloat(m_LastHeadingAngle + headingAngle);
      else
        headingAngleDiff = Math.AbsFloat(m_LastHeadingAngle - headingAngle);
      if (headingAngleDiff > 0.2)
      {
        int time = GetGame().GetTime();
        float timefilterconstant = 400 - (headingAngleDiff * 100);
        if (headingAngleDiffBlock > 0.8 && time - m_LastBackSoundTime > timefilterconstant)
        {
          float volume = headingAngleDiff / 0.5;
          if (volume > 1)
            volume = 1;
          if (volume < 0.25)
            volume = 0.25;
          m_SoundOffset = headingAngleDiff / 2;
          if (m_SoundOffset > 0.25)
            m_SoundOffset = 0.25;
          string soundSetName = "Cloth_Body_longmove_TShirt_Soundset";
          string bodyClothName = "";
          EntityAI attachment = GetInventory().FindAttachment(InventorySlots.BODY);
          if (attachment)
            bodyClothName = attachment.GetAttachmentSoundType();
          if (bodyClothName != "")
          {
            string path = "CfgSoundTables CfgAttachmentSoundTables Cloth_Body_Longmove_LookupTable";
            int soundCount = GetGame().ConfigGetChildrenCount(path);
            for (int i = 0; i < soundCount; i++)
            {
              string name = "";
              GetGame().ConfigGetChildName(path, i, name);
              if (name == bodyClothName)
              {
                TStringArray stringArray = new TStringArray();
                GetGame().ConfigGetTextArray(path + " " + name + " soundSets", stringArray);
                soundSetName = stringArray.Get(0);
                delete stringArray;
              }
            }
          }
          SoundParams soundParams = new SoundParams(soundSetName);
          SoundObjectBuilder soundObjectBuilder = new SoundObjectBuilder(soundParams);
          if (soundObjectBuilder != NULL)
          {
            SoundObject soundObject = soundObjectBuilder.BuildSoundObject();
            if (soundObject != NULL)
            {
              soundObject.SetPosition(GetPosition());
              AbstractWave wave = GetGame().GetSoundScene().Play3D(soundObject, soundObjectBuilder);
              wave.SetStartOffset(m_SoundOffset);
              wave.SetVolumeRelative(volume);
              m_LastBackSoundTime = GetGame().GetTime();
              m_LastHeadingAngleBlock = headingAngle;
            }
          }
        }
        if (headingAngleDiffBlock2 > 1.5 && time - m_LastBackSoundTime2 > (timefilterconstant * 2))
        {
          float volume2 = headingAngleDiff * 2;
          if (volume2 > 1)
            volume2 = 1;
          m_SoundOffset = headingAngleDiff / 1.8;
          if (m_SoundOffset < 0.1)
            m_SoundOffset = 0.1;
          if (m_SoundOffset > 0.3)
            m_SoundOffset = 0.3;
          string soundSetName2 = "walkProne_noHS_asphalt_ext_Char_SoundSet";
          string surfaceType = GetSurfaceType();
          if (surfaceType != "")
          {
            string movementSurfaceType = "walkProne_" + surfaceType;
            string path2 = "CfgSoundTables CfgStepSoundTables walkProne_noHS_Char_LookupTable";
            int soundCount2 = GetGame().ConfigGetChildrenCount(path2);
            for (int i2 = 0; i2 < soundCount2; i2++)
            {
              string name2 = "";
              GetGame().ConfigGetChildName(path2, i2, name2);
              if (name2 == movementSurfaceType)
              {
                TStringArray stringArray2 = new TStringArray();
                GetGame().ConfigGetTextArray(path2 + " " + name2 + " soundSets", stringArray2);
                soundSetName2 = stringArray2.Get(0);
                delete stringArray2;
              }
            }
          }
          SoundParams soundParams2 = new SoundParams(soundSetName2);
          SoundObjectBuilder soundObjectBuilder2 = new SoundObjectBuilder(soundParams2);
          if (soundObjectBuilder2 != NULL)
          {
            SoundObject soundObject2 = soundObjectBuilder2.BuildSoundObject();
            if (soundObject2 != NULL)
            {
              soundObject2.SetPosition(GetPosition());
              AbstractWave wave2 = GetGame().GetSoundScene().Play3D(soundObject2, soundObjectBuilder2);
              wave2.SetStartOffset(m_SoundOffset);
              wave2.SetVolumeRelative(volume2);
              m_LastBackSoundTime2 = GetGame().GetTime();
              m_LastHeadingAngleBlock2 = headingAngle;
            }
          }
        }
        m_LastHeadingAngle = headingAngle;
      }
    }
  }
References Math::AbsFloat(), Math::AbsInt(), GetDayZPlayerType(), GetGame(), GetInputController(), GetPosition, IsPlayerInStance(), IsRaised(), m_MovementState, name, path, SoundObject(), and SoundObjectBuilder().
HandleWeapons()
void DayZPlayer::HandleWeapons (float pDt, Entity pInHands, HumanInputController pInputs, out bool pExitIronSights) inline protected
HandleWeapons
fire
Definition at line 816 of file DayZPlayerImplement.c.
  {
    HumanCommandWeapons hcw = GetCommandModifier_Weapons();
    GetDayZPlayerInventory().HandleWeaponEvents(pDt, pExitIronSights);
    Weapon_Base weapon;
    Class.CastTo(weapon, pInHands);
    ItemOptics optic = weapon.GetAttachedOptics();
    CheckLiftWeapon();
    ProcessLiftWeapon();
    GetMovementState(m_MovementState);
    // hold breath
    if (pInputs.IsHoldBreath() && m_MovementState.IsRaised() && (IsInIronsights() || IsInOptics()))
      m_IsTryingHoldBreath = true;
    else
      m_IsTryingHoldBreath = false;
    if (pInputs.IsFireModeChange())
      GetWeaponManager().SetNextMuzzleMode();
    if (pInputs.IsZeroingUp())
    {
      if (optic && (optic.IsInOptics() || optic.IsUsingWeaponIronsightsOverride()))
        optic.StepZeroingUp();
      else
        weapon.StepZeroingUpAllMuzzles();
    }
    if (pInputs.IsZeroingDown())
    {
      if (optic && (optic.IsInOptics() || optic.IsUsingWeaponIronsightsOverride()))
        optic.StepZeroingDown();
      else
        weapon.StepZeroingDownAllMuzzles();
    }
    if (!m_LiftWeapon_player && (m_CameraIronsight || !weapon.CanEnterIronsights() || m_CameraOptics/*m_ForceHandleOptics*/)) // HACK straight to optics, if ironsights not allowed
    {
      if (optic)
        HandleOptic(optic, false, pInputs, pExitIronSights);
    }
    if (!m_MovementState.IsRaised())
    {
      m_IsFireWeaponRaised = false; //legacy reasons
      if (weapon && weapon.IsInOptics())
        weapon.ExitOptics();
      ResetWeaponRaiseProgress();
      return; // if not raised => return
    }
    else
    {
      m_IsFireWeaponRaised = true; //legacy reasons
      if (!IsWeaponRaiseCompleted())
        m_WeaponRaiseTime += pDt;
      if (m_WeaponRaiseTime >= PlayerConstants.WEAPON_RAISE_BLEND_DELAY)
        CompleteWeaponRaise();
    }
    if (GetWeaponManager().CanFire(weapon))
    {
      bool autofire = weapon.GetCurrentModeAutoFire(weapon.GetCurrentMuzzle()) && weapon.IsChamberEjectable(weapon.GetCurrentMuzzle());
      int burst = weapon.GetCurrentModeBurstSize(weapon.GetCurrentMuzzle());
      int burst_count = weapon.GetBurstCount();
      if (!autofire && (burst < 2 || burst_count < 1))
      {
        if (pInputs.IsAttackButtonDown() && GetInputInterface().SyncedValue("UAWeaponMeleeAttack") == 0 && GetInputInterface().SyncedValue("UAHeavyMeleeAttack") == 0)
          GetWeaponManager().Fire(weapon);
      }
      else if (autofire || burst > 1)
      {
#ifdef DIAG_DEVELOPER
        int burst_option = GetWeaponManager().GetBurstOption();
        if (burst_option == 0)
        {
#endif
          if (pInputs.IsAttackButton() && GetInputInterface().SyncedValue("UAWeaponMeleeAttack") == 0 && GetInputInterface().SyncedValue("UAHeavyMeleeAttack") == 0)
          {
            if (autofire || burst_count < burst)
              GetWeaponManager().Fire(weapon);
          }
          else
            weapon.ResetBurstCount();
#ifdef DIAG_DEVELOPER
        }
        else if (burst_option == 1)
        {
          if (burst > 1 && burst_count == burst)
            weapon.ResetBurstCount();
          else if (burst > 1 && burst_count < burst)
            GetWeaponManager().Fire(weapon);
          else
          {
            //Autofire
            if (pInputs.IsAttackButton())
              GetWeaponManager().Fire(weapon);
          }
        }
#endif
      }
    }
#ifdef PLATFORM_CONSOLE
    if (GetGame().GetInput().LocalRelease("UAFire", false) || m_ShouldReload)
    {
      if (!weapon.IsWaitingForActionFinish() && !IsFighting())
      {
        int muzzle_index = weapon.GetCurrentMuzzle();
        if (weapon.IsChamberFiredOut(muzzle_index))
        {
          if (weapon.CanProcessWeaponEvents())
          {
            if (GetWeaponManager().CanEjectBullet(weapon))
            {
              GetWeaponManager().EjectBullet();
              pExitIronSights = true;
              m_ShouldReload = false;
            }
          }
        }
      }
      else
        m_ShouldReload = true;
    }
#endif
  }
References Class::CastTo(), GetCommandModifier_Weapons(), GetGame(), GetInput(), GetMovementState(), m_MovementState, and PlayerConstants::WEAPON_RAISE_BLEND_DELAY.
HeadingModel()
override bool DayZPlayer::HeadingModel (float pDt, SDayZPlayerHeadingModel pModel) inline protected
on ladder - do nothing
if it's standing from prone on back
Definition at line 1322 of file DayZPlayerImplement.c.
  {
    if (!IsAlive())
      return false;
    GetMovementState(m_MovementState);
    if (m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_LADDER)
    {
      m_fLastHeadingDiff = 0;
      return false;
    }
    if (m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_VEHICLE)
    {
      HumanCommandVehicle hmv = GetCommand_Vehicle();
      if (hmv.IsGettingOut() || hmv.IsGettingIn())
        return DayZPlayerImplementHeading.NoHeading(pDt, pModel, m_fLastHeadingDiff);
      m_fLastHeadingDiff = 0;
      return false;
    }
    if (m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_UNCONSCIOUS)
    {
      HumanCommandUnconscious hcu = GetCommand_Unconscious();
      if (!hcu.IsWakingUp())
      {
        m_fLastHeadingDiff = 0;
        //pModel.m_iCamMode = DayZPlayerConstants.CAMERAMODE_HEAD;
        return false;
      }
    }
    if (m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_CLIMB)
    {
      m_fLastHeadingDiff = 0;
      return false;
    }
#ifdef DEVELOPER
    int actMenuValue = DiagMenu.GetEngineValue(DayZPlayerConstants.DEBUG_TURNSLIDE);
    if (actMenuValue != 0)
    {
      return DayZPlayerImplementHeading.ClampHeading(pDt, pModel, m_fLastHeadingDiff);
    }
#endif
    if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
    {
      m_fLastHeadingDiff = 0;
      return false;
    }
    if (m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_MOVE)
    {
      HumanCommandMove hcm = GetCommand_Move();
      if (hcm.IsStandingFromBack())
      {
        m_fLastHeadingDiff = 0;
        return false;
      }
    }
    HumanItemAccessor hia = GetItemAccessor();
    HumanItemBehaviorCfg hibcfg = hia.GetItemInHandsBehaviourCfg();
    if (hibcfg && hibcfg.m_StanceRotation[m_MovementState.m_iStanceIdx] == DayZPlayerConstants.ROTATION_DISABLE)
      return DayZPlayerImplementHeading.NoHeading(pDt, pModel, m_fLastHeadingDiff);
    if (IsUnconscious() || (GetCommand_Move() && GetCommand_Move().IsLeavingUncon()))
      return DayZPlayerImplementHeading.NoHeading(pDt, pModel, m_fLastHeadingDiff);
    return DayZPlayerImplementHeading.RotateOrient(pDt, pModel, m_fLastHeadingDiff);
  }
References DayZPlayerImplementHeading::ClampHeading(), GetCommand_Move(), GetCommand_Unconscious(), GetCommand_Vehicle(), DiagMenu::GetEngineValue(), GetItemAccessor(), GetMovementState(), HumanItemAccessor(), IsLeavingUncon(), m_MovementState, DayZPlayerImplementHeading::NoHeading(), and DayZPlayerImplementHeading::RotateOrient().
HideClothing()
void DayZPlayer::HideClothing (ItemOptics optic, bool state) inline protected
Definition at line 2220 of file DayZPlayerImplement.c.
{}
IsAlreadyInFallingCommand()
bool DayZPlayer::IsAlreadyInFallingCommand (int pCurrentCommandID) inline protected
Definition at line 3239 of file DayZPlayerImplement.c.
  {
    return pCurrentCommandID == DayZPlayerConstants.COMMANDID_FALL;
  }
IsClimbingLadder()
bool DayZPlayer::IsClimbingLadder () inline protected
Definition at line 389 of file DayZPlayerImplement.c.
  {
    return m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_LADDER;
  }
References m_MovementState.
Referenced by CanPlayEmote().
IsEyeZoom()
override bool DayZPlayer::IsEyeZoom () inline protected
Legacy.
Definition at line 209 of file DayZPlayerImplement.c.
  {
    return GetEyeZoomLevel() > 0;
  }
References GetEyeZoomLevel().
IsFBSymptomPlaying()
bool DayZPlayer::IsFBSymptomPlaying () inline protected
Definition at line 398 of file DayZPlayerImplement.c.
  {
    return m_isFBsymptomPlaying;
  }
IsFighting()
bool DayZPlayer::IsFighting () protected
Referenced by CanPlayEmote(), and HandleInitialFirearmMelee().
IsFireWeaponRaised()
bool DayZPlayer::IsFireWeaponRaised () inline protected
Definition at line 249 of file DayZPlayerImplement.c.
  {
    GetMovementState(m_MovementState);
    if (m_MovementState)
      return m_MovementState.IsRaised();
    return false;
  }
References GetMovementState(), and m_MovementState.
IsHandheldOpticsInUse()
bool DayZPlayer::IsHandheldOpticsInUse () inline protected
Definition at line 3325 of file DayZPlayerImplement.c.
  {
    return m_HandheldOpticsInUse;
  }
IsInFBEmoteState()
bool DayZPlayer::IsInFBEmoteState () protected
Checks if fullbody animation or specific locked state is active in emote manager.
IsInFullbodyDamageAnimation()
bool DayZPlayer::IsInFullbodyDamageAnimation () inline protected
Definition at line 1045 of file DayZPlayerImplement.c.
  {
    return (m_DamageHitFullbody && m_DamageHitAnimType != -1) || GetCommand_Damage() != null;
  }
References GetCommand_Damage().
IsInIronsights()
bool DayZPlayer::IsInIronsights () inline protected
Definition at line 229 of file DayZPlayerImplement.c.
  {
    return m_CameraIronsight;
  }
Referenced by SelectCrossHair(), and ScriptedWidgetEventHandler::Update().
IsInOptics()
bool DayZPlayer::IsInOptics () inline protected
Definition at line 234 of file DayZPlayerImplement.c.
  {
    return m_CameraOptics;
  }
Referenced by SelectCrossHair().
IsInThirdPerson()
override bool DayZPlayer::IsInThirdPerson () inline protected
Definition at line 239 of file DayZPlayerImplement.c.
  {
    return m_Camera3rdPerson;
  }
IsInVehicle()
bool DayZPlayer::IsInVehicle () inline protected
Definition at line 379 of file DayZPlayerImplement.c.
  {
    return m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_VEHICLE || (GetParent() != null && GetParent().IsInherited(Transport));
  }
References GetParent(), and m_MovementState.
IsLanded()
bool DayZPlayer::IsLanded (int pCurrentCommandID) inline protected
Definition at line 3210 of file DayZPlayerImplement.c.
  {
    if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_FALL)
    {
      HumanCommandFall fall = GetCommand_Fall();
      if (fall)
        return fall.PhysicsLanded();
    }
    return false;
  }
References GetCommand_Fall(), and HumanCommandFall().
IsLiftWeapon()
bool DayZPlayer::IsLiftWeapon () protected
IsPlayerSelected()
bool DayZPlayer::IsPlayerSelected () inline protected
Definition at line 3265 of file DayZPlayerImplement.c.
  {
    return m_PlayerSelected;
  }
Referenced by ScriptedWidgetEventHandler::GetActionManager(), GetActionManager(), Update(), and ScriptedWidgetEventHandler::Update().
IsRaised()
bool DayZPlayer::IsRaised () inline protected
Definition at line 3331 of file DayZPlayerImplement.c.
  {
    return m_IsRaised;
  }
Referenced by FloatingCrossHair(), SelectCrossHair(), ScriptedWidgetEventHandler::Update(), and ActionManagerClient::Update().
IsRestrained()
bool DayZPlayer::IsRestrained () protected
Referenced by CanPlayEmote(), and Update().
IsShootingFromCamera()
override bool DayZPlayer::IsShootingFromCamera () inline protected
Definition at line 219 of file DayZPlayerImplement.c.
  {
    return m_IsShootingFromCamera;
  }
Referenced by OnEmoteEnd(), and StdFovUpdate().
IsSprintFull()
bool DayZPlayer::IsSprintFull () inline protected
Definition at line 263 of file DayZPlayerImplement.c.
  {
    return m_SprintFull;
  }
Referenced by HandleFightLogic().
IsSwimming()
bool DayZPlayer::IsSwimming () inline protected
Definition at line 384 of file DayZPlayerImplement.c.
  {
    return m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_SWIM;
  }
References m_MovementState.
Referenced by CanPlayEmote().
IsTryingHoldBreath()
bool DayZPlayer::IsTryingHoldBreath () inline protected
Definition at line 258 of file DayZPlayerImplement.c.
  {
    return m_IsTryingHoldBreath;
  }
IsWeaponDebugEnabled()
bool DayZPlayer::IsWeaponDebugEnabled () inline protected
Definition at line 276 of file DayZPlayerImplement.c.
  {
    return m_WeaponDebug != null;
  }
IsWeaponRaiseCompleted()
bool DayZPlayer::IsWeaponRaiseCompleted () inline protected
Definition at line 736 of file DayZPlayerImplement.c.
  {
    return m_WeaponRaiseCompleted;
  }
LockControls()
void DayZPlayer::LockControls (bool state) inline protected
Definition at line 689 of file DayZPlayerImplement.c.
  {
    if (state == true)
    {
      GetGame().GetInput().ChangeGameFocus(1, INPUT_DEVICE_MOUSE);
      GetGame().GetInput().ChangeGameFocus(1, INPUT_DEVICE_KEYBOARD);
      GetGame().GetInput().ChangeGameFocus(1, INPUT_DEVICE_GAMEPAD);
      if (GetGame().GetUIManager())
      {
        GetGame().GetUIManager().ShowUICursor(true);
        if (GetGame().GetUIManager().IsDialogVisible())
          GetGame().GetUIManager().CloseDialog();
      }
    }
    else
    {
      GetGame().GetInput().ChangeGameFocus(-1, INPUT_DEVICE_MOUSE);
      GetGame().GetInput().ChangeGameFocus(-1, INPUT_DEVICE_KEYBOARD);
      GetGame().GetInput().ChangeGameFocus(-1, INPUT_DEVICE_GAMEPAD);
      if (GetGame().GetUIManager())
      {
        if (GetGame().GetUIManager().GetMenu())
          GetGame().GetUIManager().ShowUICursor(true);
        else
          GetGame().GetUIManager().ShowUICursor(false);
      }
    }
  }
References GetGame(), INPUT_DEVICE_GAMEPAD, INPUT_DEVICE_KEYBOARD, and INPUT_DEVICE_MOUSE.
ModCommandHandlerAfter()
bool DayZPlayer::ModCommandHandlerAfter (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline protected
Definition at line 1859 of file DayZPlayerImplement.c.
  {
    return false;
  }
ModCommandHandlerBefore()
bool DayZPlayer::ModCommandHandlerBefore (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline protected
ModOverrides
Definition at line 1849 of file DayZPlayerImplement.c.
  {
    return false;
  }
ModCommandHandlerInside()
bool DayZPlayer::ModCommandHandlerInside (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline protected
Definition at line 1854 of file DayZPlayerImplement.c.
  {
    return false;
  }
OnInputForRemote()
override void DayZPlayer::OnInputForRemote (ParamsReadContext ctx) inline protected
Definition at line 747 of file DayZPlayerImplement.c.
  {
    int userDataType = 0;
    if (!ctx.Read(userDataType))
    {
      Error("DayZPlayer: OnInputForRemote - cannot read input type");
      return;
    }
    switch (userDataType)
    {
    case INPUT_UDT_WEAPON_REMOTE_EVENT:
      GetDayZPlayerInventory().OnEventForRemoteWeapon(ctx);
      break;
    case INPUT_UDT_HAND_REMOTE_EVENT:
      GetDayZPlayerInventory().OnHandEventForRemote(ctx);
      break;
    case INPUT_UDT_INVENTORY:
      GetDayZPlayerInventory().OnInputUserDataForRemote(ctx);
      break;
    default:
      Error("OnInputForRemote - unknown userDataType=" + userDataType);
      break;
    }
  }
References Error(), INPUT_UDT_HAND_REMOTE_EVENT, INPUT_UDT_INVENTORY, and INPUT_UDT_WEAPON_REMOTE_EVENT.
OnInputFromServer()
override void DayZPlayer::OnInputFromServer (ParamsReadContext ctx) inline protected
Definition at line 773 of file DayZPlayerImplement.c.
  {
    int userDataType = 0;
    if (!ctx.Read(userDataType))
    {
      Error("DayZPlayer: OnInputFromServer - cannot read input type");
      return;
    }
    switch (userDataType)
    {
    case INPUT_UDT_INVENTORY:
      GetDayZPlayerInventory().OnServerInventoryCommand(ctx);
      break;
    default:
      Error("OnInputFromServer - unknown userDataType=" + userDataType);
      break;
    }
  }
References Error(), and INPUT_UDT_INVENTORY.
OnInputUserDataProcess()
bool DayZPlayer::OnInputUserDataProcess (int userDataType, ParamsReadContext ctx) inline protected
Definition at line 2568 of file DayZPlayerImplement.c.
  {
    m_MeleeCombat.SetTargetObject(null);
    m_MeleeCombat.SetHitPos(vector.Zero);
    m_MeleeCombat.SetHitZoneIdx(-1);
    m_MeleeCombat.SetFinisherType(-1);
    if (userDataType == INPUT_UDT_MELEE_TARGET)
    {
      EntityAI target = null;
      if (ctx.Read(target))
        m_MeleeCombat.SetTargetObject(target);
      vector hitPos = vector.Zero;
      if (ctx.Read(hitPos))
        m_MeleeCombat.SetHitPos(hitPos);
      int hitZoneIdx = -1;
      if (ctx.Read(hitZoneIdx))
        m_MeleeCombat.SetHitZoneIdx(hitZoneIdx);
      int finisherType = -1;
      if (ctx.Read(finisherType))
        m_MeleeCombat.SetFinisherType(finisherType);
      return true;
    }
    return false;
  }
References INPUT_UDT_MELEE_TARGET, m_MeleeCombat, and vector::Zero.
OnInputUserDataReceived()
void DayZPlayer::OnInputUserDataReceived (ParamsReadContext ctx) inline protected
Input userdata
Definition at line 2556 of file DayZPlayerImplement.c.
  {
    int userDataTypeParam = 0;
    if (!ctx.Read(userDataTypeParam))
    {
      Error("DayZPlayerImplement: cannot read input type");
      return;
    }
    OnInputUserDataProcess(userDataTypeParam, ctx);
  }
References Error(), and OnInputUserDataProcess().
OnItemInHandsChanged()
override void DayZPlayer::OnItemInHandsChanged () inline protected
Definition at line 797 of file DayZPlayerImplement.c.
  {
    //Print("inv: DayZPlayerImplement::OnItemInHandsChanged: "/* + GetHumanInventory().GetEntityInHands()*/);
    StopWeaponEvent();
    GetItemAccessor().OnItemInHandsChanged();
    if (!IsAlive())
    {
      //Print("inv: DayZPlayerImplement::OnItemInHandsChanged - human not alive! calling ResetWeaponInHands");
      GetItemAccessor().ResetWeaponInHands();
    }
  }
References GetItemAccessor().
Referenced by Execute(), NetSyncCurrentStateID(), OnAfterStoreLoad(), and TurnItemIntoItemLambda::OnSuccess().
OnJumpEnd()
void DayZPlayer::OnJumpEnd (int pLandType = 0) inline protected
Definition at line 1508 of file DayZPlayerImplement.c.
  {
  }
OnJumpStart()
void DayZPlayer::OnJumpStart () inline protected
Definition at line 1504 of file DayZPlayerImplement.c.
  {
  }
OnLadder()
void DayZPlayer::OnLadder (float delta_time, HumanMovementState pState) protected
called every command handler tick when player is on ladder
OnLand()
bool DayZPlayer::OnLand (int pCurrentCommandID, FallDamageData fallDamageData) inline protected
Definition at line 3223 of file DayZPlayerImplement.c.
  {
    if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_FALL)
    {
      HumanCommandFall fall = GetCommand_Fall();
      if (fall)
      {
        fall.Land(fallDamageData.m_LandType);
        return true;
      }
    }
    return false;
  }
References GetCommand_Fall(), and HumanCommandFall().
OnMovementChanged()
void DayZPlayer::OnMovementChanged () inline protected
Event, called when HumanMovementState.m_iMovement changes...walk, run, sprint, etc..
Definition at line 2463 of file DayZPlayerImplement.c.
  {
    switch (m_MovementState.m_LocalMovement)
    {
    case DayZPlayerConstants.MOVEMENTIDX_CROUCH_RUN:
    {
      //OnCrouchRunEnd();
      break;
    }
    case DayZPlayerConstants.MOVEMENTIDX_SPRINT:
    {
      OnSprintEnd();
      break;
    }
    case DayZPlayerConstants.MOVEMENTIDX_RUN:
    {
      //OnRunEnd();
      break;
    }
    case DayZPlayerConstants.MOVEMENTIDX_WALK:
    {
      //OnWalkEnd();
      break;
    }
    case DayZPlayerConstants.MOVEMENTIDX_IDLE:
    {
      //OnIdleEnd();
      break;
    }
    case DayZPlayerConstants.MOVEMENTIDX_SLIDE:
    {
      //OnSlideEnd();
      break;
    }
    }
    switch (m_MovementState.m_iMovement)
    {
    case DayZPlayerConstants.MOVEMENTIDX_CROUCH_RUN:
    {
      //OnCrouchRunStart();
      break;
    }
    case DayZPlayerConstants.MOVEMENTIDX_SPRINT:
    {
      OnSprintStart();
      break;
    }
    case DayZPlayerConstants.MOVEMENTIDX_RUN:
    {
      //OnRunStart();
      break;
    }
    case DayZPlayerConstants.MOVEMENTIDX_WALK:
    {
      //OnWalkStart();
      break;
    }
    case DayZPlayerConstants.MOVEMENTIDX_IDLE:
    {
      //OnIdleStart();
      break;
    }
    case DayZPlayerConstants.MOVEMENTIDX_SLIDE:
    {
      //OnSlideStart();
      break;
    }
    }
  }
References m_MovementState.
OnParticleEvent()
void DayZPlayer::OnParticleEvent (string pEventType, string pUserString, int pUserInt) inline protected
Definition at line 2917 of file DayZPlayerImplement.c.
  {
  }
OnSoundEvent()
void DayZPlayer::OnSoundEvent (string pEventType, string pUserString, int pUserInt) inline protected
Definition at line 2892 of file DayZPlayerImplement.c.
  {
    if (pEventType == "Sound")
      ProcessSoundEvent(pEventType, pUserString, pUserInt);
    else if (pEventType == "SoundWeapon")
      ProcessWeaponEvent(pEventType, pUserString, pUserInt);
    else if (pEventType == "SoundAttachment")
      ProcessAttachmentEvent(pEventType, pUserString, pUserInt);
    else if (pEventType == "SoundVoice")
    {
      if (GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT || GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_REMOTE)
      {
        int event_id = m_PlayerSoundEventHandler.ConvertAnimIDtoEventID(pUserInt);
        if (event_id > 0)
        {
          PlaySoundEvent(event_id);
          return;
        }
      }
      ProcessVoiceEvent(pEventType, pUserString, pUserInt);
    }
    else
      Debug.Log("OnSoundEvent: Unknown sound event \"" + pEventType + "\"");
  }
References GetInstanceType(), and Debug::Log().
OnSprintEnd()
void DayZPlayer::OnSprintEnd () inline protected
Definition at line 2543 of file DayZPlayerImplement.c.
  {
    if (GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
    {
      GetUApi().GetInputByID(UALeanLeft).Unlock();
      GetUApi().GetInputByID(UALeanRight).Unlock();
    }
  }
References GetInstanceType(), and GetUApi().
OnSprintStart()
void DayZPlayer::OnSprintStart () inline protected
Definition at line 2534 of file DayZPlayerImplement.c.
  {
    if (GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
    {
      GetUApi().GetInputByID(UALeanLeft).Lock();
      GetUApi().GetInputByID(UALeanRight).Lock();
    }
  }
References GetInstanceType(), and GetUApi().
OnStepEvent()
void DayZPlayer::OnStepEvent (string pEventType, string pUserString, int pUserInt) inline protected
Event Processing
Definition at line 2777 of file DayZPlayerImplement.c.
  {
    DayZPlayerType type = GetDayZPlayerType();
    ref HumanMovementState state = new HumanMovementState();
    GetMovementState(state);
#ifndef SERVER
    DayZPlayerTypeStepSoundLookupTable table = type.GetStepSoundLookupTable();
    SoundObjectBuilder soundBuilder = NULL;
    if (pUserInt < 100)
    {
      string surface;
      if (pUserInt % 2 == 1)
      {
        surface = GetSurfaceType(SurfaceAnimationBone.LeftBackLimb);
        if (surface.Length() == 0)//if no surface found, try other leg
          surface = GetSurfaceType(SurfaceAnimationBone.RightBackLimb);
      }
      else
      {
        surface = GetSurfaceType(SurfaceAnimationBone.RightBackLimb);
        if (surface.Length() == 0)//if no surface found, try other leg
          surface = GetSurfaceType(SurfaceAnimationBone.LeftBackLimb);
      }
      if (surface.Length() != 0)
        m_LastSurfaceUnderHash = surface.Hash();
      soundBuilder = table.GetSoundBuilder(pUserInt, state.m_iMovement, m_LastSurfaceUnderHash, GetBootsType());
    }
    else
    {
      string surface2 = GetSurfaceType();
      if (surface2.Length() != 0)
        m_LastSurfaceUnderHash = surface2.Hash();
      soundBuilder = table.GetSoundBuilder(pUserInt, state.m_iMovement, m_LastSurfaceUnderHash, GetBootsType());
    }
    if (soundBuilder != NULL && GetGame().GetPlayer())
    {
      vector orientation = Vector(0, 0, 0);
      vector edgeLength = Vector(1.5, 3.0, 1.5);
      array<Object> excludedObjects = new array<Object>;
      array<Object> collidedObjects = new array<Object>;
      if (GetGame().IsBoxColliding(GetPosition(), orientation, edgeLength, excludedObjects, collidedObjects))
      {
        for (int i = 0; i < collidedObjects.Count(); ++i)
        {
          string objectClass = collidedObjects.Get(i).GetType();
          if (objectClass.Contains("BushSoft") || objectClass.Contains("BushHard"))
          {
            for (int j = 0; j < type.GetVegetationSounds().Count(); ++j)
            {
              VegetationSound vegetationSound = type.GetVegetationSounds().Get(j);
              if (vegetationSound.GetAnimEventIds().Find(pUserInt) >= 0)
              {
                SoundObjectBuilder vegSoundObjectBuilder = vegetationSound.GetSoundObjectBuilder();
                SoundObject vegSoundObject = vegetationSound.GetSoundObjectBuilder().BuildSoundObject();
                if (vegSoundObject != NULL)
                {
                  AttenuateSoundIfNecessary(vegSoundObject);
                  PlaySound(vegSoundObject, vegSoundObjectBuilder);
                }
                break;
              }
            }
            break;
          }
        }
      }
      SoundObject soundObject = soundBuilder.BuildSoundObject();
      if (soundObject != NULL)
      {
        AttenuateSoundIfNecessary(soundObject);
        PlaySound(soundObject, soundBuilder);
      }
    }
#endif
    if (GetGame().IsServer())
    {
      m_StepCounter++;//move outside of server condition if needed on client as well
      float noiseMultiplier = 0;
      NoiseParams noiseParams;
      if (state.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_ERECT || state.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDERECT)
        noiseParams = type.GetNoiseParamsStand();
      else if (state.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_CROUCH || state.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDCROUCH)
        noiseParams = type.GetNoiseParamsCrouch();
      else if (state.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_PRONE || state.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
        noiseParams = type.GetNoiseParamsProne();
      else
      {
        Debug.Log(string.Format("Wrong stance, id: %1 using backup with stand stance (id: 0)", state.m_iStanceIdx));
        noiseParams = type.GetNoiseParamsStand();
      }
      noiseMultiplier = NoiseAIEvaluate.GetNoiseMultiplier(this);
      AddNoise(noiseParams, noiseMultiplier);
      if ((m_StepCounter % PlayerConstants.CHECK_EVERY_N_STEP) == 0)
        ProcessFeetDamageServer(pUserInt);
    }
  }
References AddNoise(), PlayerConstants::CHECK_EVERY_N_STEP, Count, DayZPlayerType(), GetDayZPlayerType(), GetGame(), GetMovementState(), NoiseAIEvaluate::GetNoiseMultiplier(), GetPlayer(), GetPosition, string::Hash(), string::Length(), Debug::Log(), NoiseParams(), PlaySound(), SoundObject(), and Vector().
OnSyncJuncture()
void DayZPlayer::OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx) inline protected
SyncJunctures
Definition at line 2603 of file DayZPlayerImplement.c.
  {
    switch (pJunctureID)
    {
    case DayZPlayerSyncJunctures.SJ_DEATH:
      if (m_DeathAnimType == -2)
        DayZPlayerSyncJunctures.ReadDeathParams(pCtx, m_DeathAnimType, m_DeathHitDir);
      break;
    case DayZPlayerSyncJunctures.SJ_DAMAGE_HIT:
      SyncHitInfo data = new SyncHitInfo;
      if (DayZPlayerSyncJunctures.ReadDamageHitParamsEx(pCtx, data) && data != null)
        m_SyncedHitDataArray.Insert(data);
      break;
    }
  }
References DayZPlayerSyncJunctures::ReadDamageHitParamsEx(), DayZPlayerSyncJunctures::ReadDeathParams(), DayZPlayerSyncJunctures::SJ_DAMAGE_HIT, and DayZPlayerSyncJunctures::SJ_DEATH.
OnVariablesSynchronized()
override void DayZPlayer::OnVariablesSynchronized () inline protected
Definition at line 480 of file DayZPlayerImplement.c.
  {
    if (m_TriggerPullPlayerOutOfVehicleSynch && !GetGame().IsDedicatedServer())
      TriggerPullPlayerOutOfVehicleImpl();
    super.OnVariablesSynchronized();
  }
References GetGame().
OverrideShootFromCamera()
void DayZPlayer::OverrideShootFromCamera (bool pState) inline protected
Definition at line 224 of file DayZPlayerImplement.c.
  {
    m_IsShootingFromCamera = pState;
  }
Referenced by EmoteBase::OnBeforeStandardCallbackCreated(), and OnEmoteEnd().
OverrideSlidePoseAngle()
void DayZPlayer::OverrideSlidePoseAngle (float value) inline protected
movement sliding override, originally for FB gestures
Definition at line 3245 of file DayZPlayerImplement.c.
  {
    if (!m_MoveSettings)
      m_MoveSettings = GetDayZPlayerType().CommandMoveSettingsW();
    if (m_MoveSettings.m_fSlidingPoseAngle != value)
    {
      m_MoveSettings.m_fSlidingPoseAngle = value;
      StartCommand_Move(); //nescessary, re-initializes with adjusted values
    }
  }
References GetDayZPlayerType(), and StartCommand_Move().
PlaySound()
AbstractWave DayZPlayer::PlaySound (SoundObject so, SoundObjectBuilder sob) inline protected
Sounds
Definition at line 2756 of file DayZPlayerImplement.c.
  {
    if (so == null)
      return null;
    so.SetPosition(GetPosition());
    AbstractWave wave = GetGame().GetSoundScene().Play3D(so, sob);
    return wave;
  }
References GetGame(), and GetPosition.
PlaySoundEvent()
bool DayZPlayer::PlaySoundEvent (EPlayerSoundEventID id, bool from_anim_system = false, bool is_from_server = false) inline protected
Definition at line 395 of file DayZPlayerImplement.c.
{};
Referenced by InjurySoundHandlerBase::PlaySound(), and StaminaSoundHandlerBase::Update().
PlaySoundEventEx()
bool DayZPlayer::PlaySoundEventEx (EPlayerSoundEventID id, bool from_anim_system = false, bool is_from_server = false, int param = 0) inline protected
Definition at line 396 of file DayZPlayerImplement.c.
{};
Referenced by PlaySound().
ProcessAttachmentEvent()
void DayZPlayer::ProcessAttachmentEvent (string pEventType, string pUserString, int pUserInt) inline protected
Definition at line 2975 of file DayZPlayerImplement.c.
  {
    DayZPlayerType type = GetDayZPlayerType();
    DayZPlayerTypeAttachmentSoundLookupTable table = type.GetAttachmentSoundLookupTable();
    array<string> attachments = new array<string>();
    pUserString.Split(",", attachments);
    for (int i = 0; i < attachments.Count(); i++)
    {
      int attachmentHash = -1;
      if (attachments[i] == "shoulder")
        attachmentHash = GetShoulderAttachmentType();
      else if (attachments[i] == "body")
        attachmentHash = GetBodyAttachmentType();
      else if (attachments[i] == "back")
        attachmentHash = GetBackAttachmentType();
      SoundObjectBuilder soundBuilder = table.GetSoundBuilder(pUserInt, attachments[i], attachmentHash);
      if (soundBuilder != NULL)
      {
        SoundObject soundObject = soundBuilder.BuildSoundObject();
        if (soundObject != NULL)
        {
          AttenuateSoundIfNecessary(soundObject);
          PlaySound(soundObject, soundBuilder);
        }
      }
    }
  }
References DayZPlayerType(), GetDayZPlayerType(), PlaySound(), and SoundObject().
ProcessFeetDamageServer()
void DayZPlayer::ProcessFeetDamageServer (int pUserInt) protected
ProcessLiftWeapon()
void DayZPlayer::ProcessLiftWeapon () protected
ProcessSoundEvent()
void DayZPlayer::ProcessSoundEvent (string pEventType, string pUserString, int pUserInt) inline protected
Definition at line 3035 of file DayZPlayerImplement.c.
  {
    DayZPlayerType type = GetDayZPlayerType();
    DayZPlayerTypeAnimTable table = type.GetSoundTable();
    AnimSoundEvent soundEvent;
    if (table)
      soundEvent = table.GetSoundEvent(pUserInt);
    if (soundEvent != NULL)
    {
      if (!GetGame().IsDedicatedServer())
      {
        SoundObjectBuilder objectBuilder = soundEvent.GetSoundBuilder();
        if (GetCommand_Ladder())
          SetVariablesLadderSoundObjectBuilder(objectBuilder);
        objectBuilder.AddEnvSoundVariables(GetPosition());
        SoundObject soundObject = objectBuilder.BuildSoundObject();
        if (soundObject != NULL)
        {
          AttenuateSoundIfNecessary(soundObject);
          PlaySound(soundObject, objectBuilder);
        }
      }
      if (GetGame().IsServer())
      {
        if (soundEvent.m_NoiseParams != NULL)
          GetGame().GetNoiseSystem().AddNoise(this, soundEvent.m_NoiseParams);
      }
    }
  }
References DayZPlayerType(), GetCommand_Ladder(), GetDayZPlayerType(), GetGame(), GetPosition, PlaySound(), and SoundObject().
ProcessVoiceEvent()
AbstractWave DayZPlayer::ProcessVoiceEvent (string pEventType, string pUserString, int pUserInt) inline protected
Definition at line 3069 of file DayZPlayerImplement.c.
  {
#ifdef SERVER//none of this code needs to run on server, ifdef put here rather than before the method call to maintain mod compatibility
    return null;
#endif
    DayZPlayerType type = GetDayZPlayerType();
    DayZPlayerTypeVoiceSoundLookupTable table = type.GetVoiceSoundLookupTable();
    if (!table)
      return null;
    AbstractWave wave;
    EntityAI mask = GetInventory().FindAttachment(InventorySlots.MASK);
    EntityAI head_gear = GetInventory().FindAttachment(InventorySlots.HEADGEAR);
    string category;
    if (mask || head_gear)
    {
      string category_mask;
      string category_headgear;
      int priority_mask;
      int priority_headgear;
      if (mask)
      {
        category_mask = mask.ConfigGetString("soundVoiceType");
        priority_mask = mask.ConfigGetInt("soundVoicePriority");
      }
      if (head_gear)
      {
        category_headgear = head_gear.ConfigGetString("soundVoiceType");
        priority_headgear = head_gear.ConfigGetInt("soundVoicePriority");
      }
      if (priority_headgear >= priority_mask && category_headgear != "")
        category = category_headgear;
      else
        category = category_mask;
    }
    if (category == "")
      category = "none";
    SoundObjectBuilder soundBuilder = table.GetSoundBuilder(pUserInt, category.Hash());
    if (soundBuilder)
    {
      PlayerBase player = PlayerBase.Cast(this);
      //this code block looks super shady, but it's the only way the sounds play correctly, god knows what's going on on c++ side
      int maleVoiceType = 0;
      int femaleVoiceType = 0;
      if (player.IsMale())
        maleVoiceType = player.GetVoiceType();
      else
        femaleVoiceType = player.GetVoiceType();
      soundBuilder.AddVariable("male", maleVoiceType);
      soundBuilder.AddVariable("female", femaleVoiceType);
      // end of weirdness
      SoundObject soundObject = soundBuilder.BuildSoundObject();
      if (soundObject != NULL)
      {
        AttenuateSoundIfNecessary(soundObject);
        wave = PlaySound(soundObject, soundBuilder);
      }
    }
    return wave;
  }
References DayZPlayerType(), GetDayZPlayerType(), PlaySound(), and SoundObject().
Referenced by Play().
ProcessWeaponEvent()
void DayZPlayer::ProcessWeaponEvent (string pEventType, string pUserString, int pUserInt) inline protected
Definition at line 2923 of file DayZPlayerImplement.c.
  {
    DayZPlayerType type = GetDayZPlayerType();
    AnimSoundEvent soundEvent = null;
    float quantity = 0;
    EntityAI entityInHands = GetHumanInventory().GetEntityInHands();
    if (entityInHands && entityInHands.IsInherited(ItemBase))
    {
      ItemBase item;
      Class.CastTo(item, entityInHands);
      if (item.HasQuantity())
        quantity = (float)item.GetQuantity() / (item.GetQuantityMax() - item.GetQuantityMin());
      InventoryItemType invItemType = item.GetInventoryItemType();
      soundEvent = invItemType.GetSoundEvent(pUserInt);
    }
    if (soundEvent == null)
    {
      quantity = 0;
      soundEvent = type.GetSoundWeaponEvent(pUserInt);
    }
    if (soundEvent != null)
    {
      if (!GetGame().IsDedicatedServer())
      {
        SoundObjectBuilder builder = soundEvent.GetSoundBuilderEx(m_ActionSoundCategoryHash);
        if (builder)
        {
          builder.AddVariable("quantity", quantity);
          builder.AddVariable("interior", IsSoundInsideBuilding());
          SoundObject soundObject = builder.BuildSoundObject();
          if (soundObject != NULL)
          {
            AttenuateSoundIfNecessary(soundObject);
            PlaySound(soundObject, builder);
          }
        }
        else
        {
          //TODO:Userful error message
        }
      }
      if (GetGame().IsServer())
        AddNoise(soundEvent.m_NoiseParams);
    }
  }
References AddNoise(), Class::CastTo(), DayZPlayerType(), GetDayZPlayerType(), GetGame(), PlaySound(), and SoundObject().
RequestSoundEvent()
void DayZPlayer::RequestSoundEvent (EPlayerSoundEventID id, bool from_server_and_client = false) protected
RequestSoundEventEx()
void DayZPlayer::RequestSoundEventEx (EPlayerSoundEventID id, bool from_server_and_client = false, int param = 0) protected
Referenced by DrowningMdfr::PlayDrowningSound().
ResetDamageHitState()
void DayZPlayer::ResetDamageHitState (bool resetTimer) inline protected
Definition at line 1135 of file DayZPlayerImplement.c.
  {
    m_DamageHitAnimType = -1;
    m_DamageHitFullbody = false;
    if (resetTimer)
      m_HitElapsedTime = 0;
  }
ResetDeathStartTime()
void DayZPlayer::ResetDeathStartTime () inline protected
Definition at line 567 of file DayZPlayerImplement.c.
  {
    ResetDeathCooldown();
  }
References ResetDeathCooldown().
ResetWeaponRaiseProgress()
void DayZPlayer::ResetWeaponRaiseProgress () inline protected
Definition at line 730 of file DayZPlayerImplement.c.
  {
    m_WeaponRaiseTime = 0;
    m_WeaponRaiseCompleted = false;
  }
RunADSTimer()
void DayZPlayer::RunADSTimer () protected
SendCompleteWeaponRaiseJuncture()
void DayZPlayer::SendCompleteWeaponRaiseJuncture () protected
SendDeathJuncture()
void DayZPlayer::SendDeathJuncture (int pAnimTypeDeath, float pAnimHitDirDeath) inline protected
Definition at line 596 of file DayZPlayerImplement.c.
  {
    if (m_DeathJuctureSent)
      return;
    DayZPlayerSyncJunctures.SendDeath(this, pAnimTypeDeath, pAnimHitDirDeath);
    m_DeathJuctureSent = true;
  }
References DayZPlayerSyncJunctures::SendDeath().
SendSoundEvent()
void DayZPlayer::SendSoundEvent (EPlayerSoundEventID id) protected
SendSoundEventEx()
void DayZPlayer::SendSoundEventEx (EPlayerSoundEventID id, int param = 0) protected
SetClimbingLadderType()
void DayZPlayer::SetClimbingLadderType (string value) inline protected
Definition at line 369 of file DayZPlayerImplement.c.
  {
    m_ClimbingLadderType = value;
  }
SetCurrentWaterLevel()
override void DayZPlayer::SetCurrentWaterLevel (float pWaterLevel) inline protected
Definition at line 291 of file DayZPlayerImplement.c.
  {
    m_CurrentWaterLevel = pWaterLevel;
  }
Referenced by DayZPlayerImplementSwimming::HandleSwimming().
SetDeathDarknessLevel()
void DayZPlayer::SetDeathDarknessLevel (float duration, float tick_time) protected
SetFallYDiff()
void DayZPlayer::SetFallYDiff (float value) inline protected
Definition at line 281 of file DayZPlayerImplement.c.
  {
    m_FallYDiff = value;
  }
SetHandheldOpticsInUse()
void DayZPlayer::SetHandheldOpticsInUse (bool state) inline protected
Definition at line 3320 of file DayZPlayerImplement.c.
  {
    m_HandheldOpticsInUse = state;
  }
SetIronsights()
void DayZPlayer::SetIronsights (bool value) inline protected
Definition at line 296 of file DayZPlayerImplement.c.
  {
    Weapon_Base weapon = Weapon_Base.Cast(GetHumanInventory().GetEntityInHands());
    if (weapon)
      m_WasIronsight = m_CameraIronsight;
    m_CameraIronsight = value;
    if (value)
    {
      HumanCommandWeapons hcw = GetCommandModifier_Weapons();
      if (hcw)
        hcw.SetADS(true);
    }
  }
References GetCommandModifier_Weapons().
SetIsInThirdPerson()
void DayZPlayer::SetIsInThirdPerson (bool state) inline protected
Definition at line 244 of file DayZPlayerImplement.c.
  {
    m_Camera3rdPerson = state;
  }
SetOptics()
void DayZPlayer::SetOptics (bool value) inline protected
Definition at line 312 of file DayZPlayerImplement.c.
  {
    m_CameraOptics = value;
    if (value)
    {
      HumanCommandWeapons hcw = GetCommandModifier_Weapons();
      if (hcw)
        hcw.SetADS(!IsHandheldOpticsInUse());
    }
  }
References GetCommandModifier_Weapons().
SetReturnToOptics()
void DayZPlayer::SetReturnToOptics (bool state) protected
SetSuicide()
void DayZPlayer::SetSuicide (bool state) inline protected
Definition at line 3275 of file DayZPlayerImplement.c.
  {
    m_Suicide = state;
  }
Referenced by CommitSuicide(), and EmoteBase::OnCallbackEnd().
SetVariablesLadderSoundObjectBuilder()
void DayZPlayer::SetVariablesLadderSoundObjectBuilder (SoundObjectBuilder soundObjectBuilder) inline protected
Definition at line 3006 of file DayZPlayerImplement.c.
  {
    if (m_ClimbingLadderType == "wood")
      soundObjectBuilder.AddVariable("laddertype", 1);
    else
      soundObjectBuilder.AddVariable("laddertype", 0);
    AnimBootsType pBoots = GetBootsType();
    if (pBoots == AnimBootsType.None)
    {
      soundObjectBuilder.AddVariable("bare", 1);
      soundObjectBuilder.AddVariable("sneakers", 0);
      soundObjectBuilder.AddVariable("boots", 0);
    }
    else if (pBoots == AnimBootsType.Sneakers)
    {
      soundObjectBuilder.AddVariable("bare", 0);
      soundObjectBuilder.AddVariable("sneakers", 1);
      soundObjectBuilder.AddVariable("boots", 0);
    }
    else if (pBoots == AnimBootsType.Boots)
    {
      soundObjectBuilder.AddVariable("bare", 0);
      soundObjectBuilder.AddVariable("sneakers", 0);
      soundObjectBuilder.AddVariable("boots", 1);
    }
  }
ShowDeadScreen()
void DayZPlayer::ShowDeadScreen (bool show, float duration) inline protected
Definition at line 612 of file DayZPlayerImplement.c.
  {
#ifndef NO_GUI
    if (show && IsPlayerSelected())
    {
#ifdef PLATFORM_PS4
      OnlineServices.SetMultiplayState(false);
#endif
      string message = "";
      if (!GetGame().GetMission().IsPlayerRespawning())
        message = "#dayz_implement_dead";
#ifdef PLATFORM_CONSOLE
      GetGame().GetUIManager().ScreenFadeIn(duration, message, FadeColors.DARK_RED, FadeColors.WHITE);
#else
      GetGame().GetUIManager().ScreenFadeIn(duration, message, FadeColors.BLACK, FadeColors.WHITE);
#endif
    }
    else
    {
      GetGame().GetUIManager().ScreenFadeOut(duration);
      if (duration > 0)
        GetGame().GetCallQueue(CALL_CATEGORY_GUI).CallLater(StopDeathDarkeningEffect, duration * 1000, false);
      else
        GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(StopDeathDarkeningEffect);
    }
#endif
  }
References CALL_CATEGORY_GUI, GetGame(), and OnlineServices::SetMultiplayState().
ShowWeaponDebug()
void DayZPlayer::ShowWeaponDebug (bool show) inline protected
Definition at line 268 of file DayZPlayerImplement.c.
  {
    if (show)
      m_WeaponDebug = new WeaponDebug;
    else
      m_WeaponDebug = null;
  }
SimulateDeath()
void DayZPlayer::SimulateDeath (bool state) inline protected
Definition at line 652 of file DayZPlayerImplement.c.
  {
    if (g_Game.GetMissionState() != DayZGame.MISSION_STATE_GAME)
      return;
    LockControls(state);
    if (state)
    {
      float duration = DEFAULT_DYING_TIME;
      if (m_KilledByHeadshot)
        duration = 0;
      if (duration > DYING_PROGRESSION_TIME && !m_IsUnconscious)
      {
        if (!m_DeathEffectTimer)
          m_DeathEffectTimer = new DeathEffectTimer();
        Param2<float, float> par = new Param2<float, float>(duration, DYING_PROGRESSION_TIME);
        m_DeathEffectTimer.Run(DYING_PROGRESSION_TIME, this, "SetDeathDarknessLevel", par, true);
      }
      ShowDeadScreen(state, duration);
      GetGame().GetSoundScene().SetSoundVolume(0, 0);
      GetGame().GetSoundScene().SetSpeechExVolume(0, 0);
      GetGame().GetSoundScene().SetMusicVolume(0, 0);
      GetGame().GetSoundScene().SetVOIPVolume(0, 0);
      GetGame().GetSoundScene().SetRadioVolume(0, 0);
    }
    else
    {
      StopDeathDarkeningEffect();
      ShowDeadScreen(state, 0);
    }
  }
References g_Game, and GetGame().
StopADSTimer()
void DayZPlayer::StopADSTimer () protected
StopDeathDarkeningEffect()
override void DayZPlayer::StopDeathDarkeningEffect () inline protected
Definition at line 643 of file DayZPlayerImplement.c.
  {
    if (m_DeathEffectTimer && m_DeathEffectTimer.IsRunning())
    {
      m_DeathEffectTimer.Stop();
      m_DeathEffectTimer = null;
    }
  }
StopHandEvent()
void DayZPlayer::StopHandEvent () inline protected
Definition at line 1512 of file DayZPlayerImplement.c.
  {
    GetDayZPlayerInventory().CancelHandEvent();
  }
StopWeaponEvent()
void DayZPlayer::StopWeaponEvent () inline protected
Definition at line 1517 of file DayZPlayerImplement.c.
  {
    GetDayZPlayerInventory().CancelWeaponEvent();
  }
SwitchOptics()
void DayZPlayer::SwitchOptics (ItemOptics optic, bool state) inline protected
Definition at line 345 of file DayZPlayerImplement.c.
  {
    if (optic)
    {
      if (state)
      {
        if (optic.HasEnergyManager())
          optic.GetCompEM().SwitchOn();
        optic.EnterOptics();
        optic.OnOpticEnter();
      }
      else
      {
        optic.ExitOptics();
        optic.OnOpticExit();
        if (optic.HasEnergyManager())
          optic.GetCompEM().SwitchOff();
      }
    }
    if (m_CameraOptics != state)
      SetOptics(state);
  }
TriggerPullPlayerOutOfVehicle()
void DayZPlayer::TriggerPullPlayerOutOfVehicle () inline protected
Definition at line 432 of file DayZPlayerImplement.c.
  {
    if (!GetGame().IsServer())
      return;
    Transport transport;
    if (!Class.CastTo(transport, GetParent()))
      return;
    int crewIdx = -1;
    for (int i = 0; i < transport.CrewSize(); ++i)
    {
      if (transport.CrewMember(i) == this)
      {
        crewIdx = i;
        break;
      }
    }
    if (crewIdx == -1)
      return;
    transport.CrewGetOut(crewIdx);
    TriggerPullPlayerOutOfVehicleImpl();
    SetSynchDirty();
  }
References Class::CastTo(), GetGame(), and GetParent().
TriggerPullPlayerOutOfVehicleImpl()
void DayZPlayer::TriggerPullPlayerOutOfVehicleImpl () inline protected
Reset the cooldown so simulation doesn't automatically get re-disabled
Synced to re-enable simulation on client as the death processing sets disable simulation to local only
Handle own client animation freeze
Definition at line 460 of file DayZPlayerImplement.c.
  {
    ResetDeathCooldown();
    DisableSimulation(false);
    switch (GetInstanceType())
    {
    case DayZPlayerInstanceType.INSTANCETYPE_SERVER:
    case DayZPlayerInstanceType.INSTANCETYPE_CLIENT:
    case DayZPlayerInstanceType.INSTANCETYPE_AI_SERVER:
    case DayZPlayerInstanceType.INSTANCETYPE_AI_SINGLEPLAYER:
      m_PullPlayerOutOfVehicleState = 0;
      m_TriggerPullPlayerOutOfVehicleSynch = true;
      break;
    }
  }
References GetInstanceType(), and ResetDeathCooldown().
Member Data Documentation
DEAD_SCREEN_DELAY
const int DayZPlayer::DEAD_SCREEN_DELAY = 1000 static private
Definition at line 72 of file DayZPlayerImplement.c.
DEFAULT_DYING_TIME
const float DayZPlayer::DEFAULT_DYING_TIME = 2.5 static private
DEPRECATED.
Definition at line 73 of file DayZPlayerImplement.c.
DYING_PROGRESSION_TIME
const float DayZPlayer::DYING_PROGRESSION_TIME = 0.05 static private
how long does it take to full death screen [s]
Definition at line 74 of file DayZPlayerImplement.c.
HIT_INTERVAL_MIN
const float DayZPlayer::HIT_INTERVAL_MIN = 0.3 protected
Definition at line 1042 of file DayZPlayerImplement.c.
m_ActionSoundCategoryHash
int DayZPlayer::m_ActionSoundCategoryHash protected
Definition at line 142 of file DayZPlayerImplement.c.
m_ADSAutomationTimer
ref Timer DayZPlayer::m_ADSAutomationTimer protected
Definition at line 3362 of file DayZPlayerImplement.c.
m_ADSTimerLaunched
bool DayZPlayer::m_ADSTimerLaunched protected
Definition at line 3363 of file DayZPlayerImplement.c.
m_AimingFinisherStarted
bool DayZPlayer::m_AimingFinisherStarted = false protected
Definition at line 133 of file DayZPlayerImplement.c.
m_AimingModel
ref DayZPlayerImplementAiming DayZPlayer::m_AimingModel protected
Definition at line 78 of file DayZPlayerImplement.c.
m_bADS
bool DayZPlayer::m_bADS protected
Definition at line 95 of file DayZPlayerImplement.c.
m_Camera3rdPerson
bool DayZPlayer::m_Camera3rdPerson protected
Definition at line 93 of file DayZPlayerImplement.c.
m_CameraEyeZoom
bool DayZPlayer::m_CameraEyeZoom protected
Definition at line 3361 of file DayZPlayerImplement.c.
m_CameraEyeZoomLevel
ECameraZoomType DayZPlayer::m_CameraEyeZoomLevel protected
Definition at line 98 of file DayZPlayerImplement.c.
m_CameraIronsight
bool DayZPlayer::m_CameraIronsight protected
Definition at line 100 of file DayZPlayerImplement.c.
m_CameraOptics
bool DayZPlayer::m_CameraOptics protected
Definition at line 101 of file DayZPlayerImplement.c.
m_CameraZoomToggle
bool DayZPlayer::m_CameraZoomToggle protected
Definition at line 94 of file DayZPlayerImplement.c.
m_ClimbingLadderType
string DayZPlayer::m_ClimbingLadderType protected
Definition at line 123 of file DayZPlayerImplement.c.
m_ContinueFirearmMelee
bool DayZPlayer::m_ContinueFirearmMelee protected
Definition at line 117 of file DayZPlayerImplement.c.
m_CurrentWaterLevel
float DayZPlayer::m_CurrentWaterLevel private
Definition at line 136 of file DayZPlayerImplement.c.
m_DamageHealth
float DayZPlayer::m_DamageHealth = 0.0 protected
Definition at line 1040 of file DayZPlayerImplement.c.
m_DamageHitAnimType
int DayZPlayer::m_DamageHitAnimType = -1.0 protected
Definition at line 1038 of file DayZPlayerImplement.c.
m_DamageHitDir
float DayZPlayer::m_DamageHitDir = 0.0 protected
Definition at line 1039 of file DayZPlayerImplement.c.
m_DamageHitFullbody
bool DayZPlayer::m_DamageHitFullbody = false protected
HandleDamageHit
Definition at line 1037 of file DayZPlayerImplement.c.
m_DeathAnimType
int DayZPlayer::m_DeathAnimType = -2 protected
HandleDeath
Definition at line 413 of file DayZPlayerImplement.c.
m_DeathDarkeningCurrentTime
float DayZPlayer::m_DeathDarkeningCurrentTime protected
Definition at line 103 of file DayZPlayerImplement.c.
m_DeathEffectTimer
ref DeathEffectTimer DayZPlayer::m_DeathEffectTimer protected
Definition at line 114 of file DayZPlayerImplement.c.
m_DeathHitDir
float DayZPlayer::m_DeathHitDir = 0 protected
Definition at line 414 of file DayZPlayerImplement.c.
m_DeathJuctureSent
bool DayZPlayer::m_DeathJuctureSent = false protected
Definition at line 415 of file DayZPlayerImplement.c.
m_DebugDirectionVal
float DayZPlayer::m_DebugDirectionVal = -180 protected
VKOSTIK - tady dat 0 misto -1.
Definition at line 2228 of file DayZPlayerImplement.c.
m_DebugTypeVal
bool DayZPlayer::m_DebugTypeVal = false protected
Definition at line 2229 of file DayZPlayerImplement.c.
m_DebugWeaponChangeItem
string DayZPlayer::m_DebugWeaponChangeItem protected
Definition at line 2232 of file DayZPlayerImplement.c.
m_DebugWeaponChangeShowSlot
int DayZPlayer::m_DebugWeaponChangeShowSlot protected
Definition at line 2233 of file DayZPlayerImplement.c.
m_DebugWeaponChangeStage
int DayZPlayer::m_DebugWeaponChangeStage = 0 protected
Definition at line 2231 of file DayZPlayerImplement.c.
m_dT
float DayZPlayer::m_dT protected
Definition at line 144 of file DayZPlayerImplement.c.
m_FallDamage
ref DayZPlayerImplementFallDamage DayZPlayer::m_FallDamage protected
Definition at line 84 of file DayZPlayerImplement.c.
m_FallYDiff
float DayZPlayer::m_FallYDiff protected
Definition at line 87 of file DayZPlayerImplement.c.
m_FightEndBlendTimer
ref Timer DayZPlayer::m_FightEndBlendTimer protected
Definition at line 115 of file DayZPlayerImplement.c.
m_fLastHeadingDiff
float DayZPlayer::m_fLastHeadingDiff = 0 protected
This HeadingModel
Definition at line 1319 of file DayZPlayerImplement.c.
m_HandheldOpticsInUse
bool DayZPlayer::m_HandheldOpticsInUse protected
Definition at line 125 of file DayZPlayerImplement.c.
m_HitElapsedTime
float DayZPlayer::m_HitElapsedTime = HIT_INTERVAL_MIN protected
Definition at line 1043 of file DayZPlayerImplement.c.
m_isFBsymptomPlaying
bool DayZPlayer::m_isFBsymptomPlaying protected
Definition at line 124 of file DayZPlayerImplement.c.
Referenced by SmptAnimMetaBase::Play(), and SmptAnimMetaBase::~SmptAnimMetaFB().
m_IsFireWeaponRaised
bool DayZPlayer::m_IsFireWeaponRaised protected
Definition at line 3365 of file DayZPlayerImplement.c.
m_IsRaised
bool DayZPlayer::m_IsRaised protected
Definition at line 91 of file DayZPlayerImplement.c.
m_IsShootingFromCamera
bool DayZPlayer::m_IsShootingFromCamera protected
Definition at line 105 of file DayZPlayerImplement.c.
m_IsTryingHoldBreath
bool DayZPlayer::m_IsTryingHoldBreath protected
Definition at line 104 of file DayZPlayerImplement.c.
m_IsUnconscious
bool DayZPlayer::m_IsUnconscious protected
Definition at line 108 of file DayZPlayerImplement.c.
m_IsUnconsciousFalling
bool DayZPlayer::m_IsUnconsciousFalling protected
Definition at line 110 of file DayZPlayerImplement.c.
m_IsWeapon
bool DayZPlayer::m_IsWeapon protected
Definition at line 134 of file DayZPlayerImplement.c.
m_JumpClimb
ref DayZPlayerImplementJumpClimb DayZPlayer::m_JumpClimb protected
Definition at line 83 of file DayZPlayerImplement.c.
m_LastBackSoundTime
int DayZPlayer::m_LastBackSoundTime protected
Definition at line 1838 of file DayZPlayerImplement.c.
m_LastBackSoundTime2
int DayZPlayer::m_LastBackSoundTime2 protected
Definition at line 1839 of file DayZPlayerImplement.c.
m_LastCommandBeforeUnconscious
int DayZPlayer::m_LastCommandBeforeUnconscious protected
Definition at line 112 of file DayZPlayerImplement.c.
m_LastHeadingAngle
float DayZPlayer::m_LastHeadingAngle protected
Definition at line 1837 of file DayZPlayerImplement.c.
m_LastHeadingAngleBlock
float DayZPlayer::m_LastHeadingAngleBlock protected
Definition at line 1835 of file DayZPlayerImplement.c.
m_LastHeadingAngleBlock2
float DayZPlayer::m_LastHeadingAngleBlock2 protected
Definition at line 1836 of file DayZPlayerImplement.c.
m_LastSurfaceUnderHash
int DayZPlayer::m_LastSurfaceUnderHash protected
Definition at line 121 of file DayZPlayerImplement.c.
m_LiftWeapon_player
bool DayZPlayer::m_LiftWeapon_player protected
Definition at line 118 of file DayZPlayerImplement.c.
m_MeleeCombat
ref DayZPlayerImplementMeleeCombat DayZPlayer::m_MeleeCombat protected
Definition at line 79 of file DayZPlayerImplement.c.
m_MeleeFightLogic
ref DayZPlayerMeleeFightLogic_LightHeavy DayZPlayer::m_MeleeFightLogic protected
Definition at line 80 of file DayZPlayerImplement.c.
m_MovementState
ref HumanMovementState DayZPlayer::m_MovementState = new HumanMovementState() private
time step for gradual update of dead screen visibilibty up to full visbility [s]
cached ptr for movement state
Definition at line 77 of file DayZPlayerImplement.c.
m_MoveSettings
SHumanCommandMoveSettings DayZPlayer::m_MoveSettings protected
Definition at line 86 of file DayZPlayerImplement.c.
m_NextVoNNoiseTime
int DayZPlayer::m_NextVoNNoiseTime protected
Definition at line 128 of file DayZPlayerImplement.c.
m_PlayerSelected
bool DayZPlayer::m_PlayerSelected protected
Definition at line 106 of file DayZPlayerImplement.c.
m_PlayerSoundEventHandler
ref PlayerSoundEventHandler DayZPlayer::m_PlayerSoundEventHandler protected
Definition at line 85 of file DayZPlayerImplement.c.
m_ProcessFirearmMeleeHit
bool DayZPlayer::m_ProcessFirearmMeleeHit protected
Definition at line 116 of file DayZPlayerImplement.c.
m_ProcessLiftWeapon
bool DayZPlayer::m_ProcessLiftWeapon protected
Definition at line 119 of file DayZPlayerImplement.c.
m_ProcessLiftWeaponState
bool DayZPlayer::m_ProcessLiftWeaponState protected
Definition at line 120 of file DayZPlayerImplement.c.
m_ProcessWeaponRaiseCompleted
bool DayZPlayer::m_ProcessWeaponRaiseCompleted protected
Definition at line 3364 of file DayZPlayerImplement.c.
m_PullPlayerOutOfVehicleKeepsInLocalSpace
bool DayZPlayer::m_PullPlayerOutOfVehicleKeepsInLocalSpace = false protected
Definition at line 140 of file DayZPlayerImplement.c.
m_PullPlayerOutOfVehicleState
int DayZPlayer::m_PullPlayerOutOfVehicleState = -1 protected
Definition at line 141 of file DayZPlayerImplement.c.
m_RaiseStarted
bool DayZPlayer::m_RaiseStarted = false protected
Definition at line 132 of file DayZPlayerImplement.c.
m_ResetADS
bool DayZPlayer::m_ResetADS protected
Definition at line 126 of file DayZPlayerImplement.c.
m_ShouldBeUnconscious
bool DayZPlayer::m_ShouldBeUnconscious protected
Definition at line 109 of file DayZPlayerImplement.c.
m_ShouldReload
bool DayZPlayer::m_ShouldReload protected
Definition at line 92 of file DayZPlayerImplement.c.
m_SoundOffset
float DayZPlayer::m_SoundOffset protected
Definition at line 1840 of file DayZPlayerImplement.c.
m_SprintedTime
float DayZPlayer::m_SprintedTime protected
Definition at line 88 of file DayZPlayerImplement.c.
m_SprintedTimePerStanceMin
float DayZPlayer::m_SprintedTimePerStanceMin protected
Definition at line 89 of file DayZPlayerImplement.c.
m_SprintFull
bool DayZPlayer::m_SprintFull protected
Definition at line 90 of file DayZPlayerImplement.c.
m_StepCounter
int DayZPlayer::m_StepCounter protected
Definition at line 127 of file DayZPlayerImplement.c.
m_Suicide
bool DayZPlayer::m_Suicide protected
Definition at line 107 of file DayZPlayerImplement.c.
m_Swimming
ref DayZPlayerImplementSwimming DayZPlayer::m_Swimming protected
Definition at line 81 of file DayZPlayerImplement.c.
m_SyncedHitDataArray
ref array<ref SyncHitInfo> DayZPlayer::m_SyncedHitDataArray protected
Definition at line 129 of file DayZPlayerImplement.c.
m_TestDamageCounter
float DayZPlayer::m_TestDamageCounter = -1 protected
This is Debug functionality
Definition at line 2227 of file DayZPlayerImplement.c.
m_Throwing
ref DayZPlayerImplementThrowing DayZPlayer::m_Throwing protected
Definition at line 82 of file DayZPlayerImplement.c.
m_TransportCache
Transport DayZPlayer::m_TransportCache protected
Definition at line 122 of file DayZPlayerImplement.c.
m_TriggerPullPlayerOutOfVehicleSynch
bool DayZPlayer::m_TriggerPullPlayerOutOfVehicleSynch protected
Definition at line 139 of file DayZPlayerImplement.c.
m_UnconsciousDebug
bool DayZPlayer::m_UnconsciousDebug protected
Definition at line 111 of file DayZPlayerImplement.c.
m_WasInVehicle
bool DayZPlayer::m_WasInVehicle private
Definition at line 138 of file DayZPlayerImplement.c.
m_WasIronsight
bool DayZPlayer::m_WasIronsight protected
Definition at line 99 of file DayZPlayerImplement.c.
m_WeaponDebug
ref WeaponDebug DayZPlayer::m_WeaponDebug protected
Definition at line 113 of file DayZPlayerImplement.c.
m_WeaponRaiseCompleted
bool DayZPlayer::m_WeaponRaiseCompleted protected
measures time from the weapon raise start to complete raise (once per)
Definition at line 97 of file DayZPlayerImplement.c.
m_WeaponRaiseTime
float DayZPlayer::m_WeaponRaiseTime private
Definition at line 96 of file DayZPlayerImplement.c.
The documentation for this class was generated from the following file:
scripts/4_World/Entities/DayZPlayerImplement.c