DayZ: scripts/4_World/Classes/PlayerModifiers/ModifierBase.c File Reference
ModifierBase.c File Reference
Enumerations
enum eModifiersTickType { TICK = 1 , ACTIVATE_CHECK = 2 , DEACTIVATE_CHECK = 4 }
Functions
void ModifierBase ()
void InitBase (PlayerBase player, ModifiersManager manager)
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
PlayerBase GetPlayer ()
bool IsPersistent ()
void MakeParamObjectPersistent (Param object)
void ResetLastTickTime ()
string GetDebugText ()
string GetDebugTextSimple ()
void DisableActivateCheck ()
void DisableDeactivateCheck ()
void Tick (float delta_time)
bool IsActive ()
void SetLock (bool state)
bool IsLocked ()
bool IsTrackAttachedTime ()
float GetAttachedTime ()
void SetAttachedTime (float time)
int GetModifierID ()
string GetName ()
Gets the name which is set for the ParticleManager, default is "ParticleSourceManager".
bool ActivateCondition (PlayerBase player)
bool DeactivateCondition (PlayerBase player)
void OnActivate (PlayerBase player)
is called when an inactive modifier gets activated during gameplay, is NOT called on activation upon player server connection(see OnReconnect)
void OnReconnect (PlayerBase player)
is called when a modifier is being re-activated upon player server connection, use to activate systems which are not persistent and need to run alongside active modifiers
void OnDeactivate (PlayerBase player)
void Activate ()
void ActivateRequest (EActivationType trigger)
void Deactivate (bool trigger=true)
void OnStoreSave (ParamsWriteContext ctx)
void OnTick (PlayerBase player, float deltaT)
Variables
enum eModifiersTickType m_ID = 0
ModifiersManager m_Manager
string m_System = "Modifiers"
float m_ActivatedTime
bool m_TrackActivatedTime
bool m_IsPersistent
PlayerBase m_Player
float m_TickIntervalInactive = 5
float m_TickIntervalActive = 3
bool m_IsActive
bool m_ShouldBeActive
float m_AccumulatedTimeActive
float m_AccumulatedTimeInactive
float m_LastTickedActive
int m_TickType = (eModifiersTickType.TICK | eModifiersTickType.ACTIVATE_CHECK | eModifiersTickType.DEACTIVATE_CHECK)
float m_LastTickedInactive
bool m_IsLocked = false
EActivationType m_ActivationType
eModifierSyncIDs m_SyncID
PluginPlayerStatus m_ModulePlayerStatus
Enumeration Type Documentation
eModifiersTickType
enum eModifiersTickType
Enumerator
TICK
ACTIVATE_CHECK
DEACTIVATE_CHECK
Definition at line 1 of file ModifierBase.c.
{
  TICK = 1,
  ACTIVATE_CHECK = 2,
  DEACTIVATE_CHECK = 4,
}
Function Documentation
Activate()
void Activate ()
Definition at line 195 of file ModifierBase.c.
  {
    m_IsActive = true;
    m_Player.m_SyncedModifiers = (m_Player.m_SyncedModifiers | m_SyncID);
    if (m_ActivationType == EActivationType.TRIGGER_EVENT_ON_ACTIVATION) OnActivate(m_Player);
    else if (m_ActivationType == EActivationType.TRIGGER_EVENT_ON_CONNECT) OnReconnect(m_Player);
    m_Player.SetSynchDirty();
  }
References m_ActivationType, m_IsActive, m_Player, m_SyncID, OnActivate(), and ModifierBase::OnReconnect().
Referenced by Tick(), and Unpin().
ActivateCondition()
bool ActivateCondition (PlayerBase player)
Definition at line 168 of file ModifierBase.c.
  {
    return false;
  }
ActivateRequest()
void ActivateRequest (EActivationType trigger)
Definition at line 204 of file ModifierBase.c.
  {
    m_ShouldBeActive = true;
    m_ActivationType = trigger;
  }
References m_ActivationType, and m_ShouldBeActive.
Referenced by Tick().
Deactivate()
void Deactivate (bool trigger = true)
Definition at line 210 of file ModifierBase.c.
  {
    if (!m_IsActive)
      return;
    m_Player.m_SyncedModifiers = (m_Player.m_SyncedModifiers & ~m_SyncID);
    m_ShouldBeActive = false;
    m_IsActive = false;
    m_ActivatedTime = 0;
    if (trigger)
      OnDeactivate(m_Player);
  }
References m_ActivatedTime, m_IsActive, m_Player, m_ShouldBeActive, and OnDeactivate().
Referenced by Tick().
DeactivateCondition()
bool DeactivateCondition (PlayerBase player)
Definition at line 173 of file ModifierBase.c.
  {
    return false;
  }
DisableActivateCheck()
void DisableActivateCheck ()
Definition at line 78 of file ModifierBase.c.
  {
    m_TickType = (m_TickType & ~eModifiersTickType.ACTIVATE_CHECK);
  }
References m_TickType.
Referenced by AntibioticsMdfr::Init(), CharcoalMdfr::Init(), AreaExposureMdfr::Init(), BlindedMdfr::Init(), HeartAttackMdfr::Init(), HemolyticReactionMdfr::Init(), TestDiseaseMdfr::Init(), DisinfectionMdfr::Init(), EpinephrineMdfr::Init(), FliesMdfr::Init(), MorphineMdfr::Init(), PainKillersMdfr::Init(), and SalineMdfr::Init().
DisableDeactivateCheck()
void DisableDeactivateCheck ()
Definition at line 83 of file ModifierBase.c.
  {
    m_TickType = (m_TickType & ~eModifiersTickType.DEACTIVATE_CHECK);
  }
References m_TickType.
Referenced by ModifierBase::Init(), AreaExposureMdfr::Init(), BleedingCheckMdfr::Init(), HeartAttackMdfr::Init(), TestDiseaseMdfr::Init(), FliesMdfr::Init(), HealthMdfr::Init(), HealthRegenMdfr::Init(), HeatComfortMdfr::Init(), HungerMdfr::Init(), ImmuneSystemMdfr::Init(), ShockMdfr::Init(), StomachMdfr::Init(), ThirstMdfr::Init(), and ToxicityMdfr::Init().
GetAttachedTime()
float GetAttachedTime ()
Definition at line 144 of file ModifierBase.c.
  {
    return m_ActivatedTime;
  }
References m_ActivatedTime.
Referenced by AntibioticsMdfr::DeactivateCondition(), CharcoalMdfr::DeactivateCondition(), HemolyticReactionMdfr::DeactivateCondition(), DisinfectionMdfr::DeactivateCondition(), EpinephrineMdfr::DeactivateCondition(), ImmunityBoost::DeactivateCondition(), MorphineMdfr::DeactivateCondition(), PainKillersMdfr::DeactivateCondition(), SalineMdfr::DeactivateCondition(), TestingMdfr::DeactivateCondition(), AntibioticsMdfr::GetDebugText(), DisinfectionMdfr::GetDebugText(), EpinephrineMdfr::GetDebugText(), ImmunityBoost::GetDebugText(), MorphineMdfr::GetDebugText(), PainKillersMdfr::GetDebugText(), AntibioticsMdfr::GetDebugTextSimple(), CharcoalMdfr::GetDebugTextSimple(), DisinfectionMdfr::GetDebugTextSimple(), CharcoalMdfr::OnTick(), ContaminationStage3Mdfr::OnTick(), and PainKillersMdfr::OnTick().
GetDebugText()
string GetDebugText ()
Definition at line 68 of file ModifierBase.c.
  {
    return "";
  }
GetDebugTextSimple()
string GetDebugTextSimple ()
Definition at line 73 of file ModifierBase.c.
  {
    return "";
  }
GetModifierID()
int GetModifierID ()
Definition at line 154 of file ModifierBase.c.
  {
    return m_ID;
  }
References m_ID.
GetPlayer()
PlayerBase GetPlayer ()
Definition at line 47 of file ModifierBase.c.
  {
    return m_Player;
  }
References m_Player.
Referenced by Actions_DoCancel(), Actions_DoInternalCommand(), Actions_Start(), ActivateModifier(), PluginBase::ActivateModifier(), MissionBase::AddActiveInputRestriction(), LayoutHolder::AddItemToQuickbarRadial(), ClientData::AddPlayerBase(), AddQuickbarItem(), VicinityItemManager::AddVicinityItems(), EntityAI::AdvancedCommunication(), DayZCreature::AttenuateSoundIfNecessary(), DayZPlayer::AttenuateSoundIfNecessary(), CameraShake::CameraShake(), UIScriptedMenu::CameraToolsMenu(), InventoryGridController::CanAddItemInHandToInventory(), LayoutHolder::CanAddToQuickbarEx(), Attachments::CanCombine(), Attachments::CanCombineAmmo(), Container::CanCombineAmmo(), VicinitySlotsContainer::CanCombineAmmo(), LayoutHolder::CanCombineEx(), BaseBuildingBase::CanDisplayAttachmentCategory(), BaseBuildingBase::CanDisplayAttachmentSlot(), LayoutHolder::CanDropEx(), LayoutHolder::CanEquipEx(), BaseBuildingBase::CanReceiveAttachment(), LayoutHolder::CanSwapOrTakeToHandsEx(), LayoutHolder::CanTakeToInventoryEx(), CheckAllowUpdate(), UIScriptedMenu::CheckForLightsAndNVG(), Attachments::Combine(), PlayerContainer::Combine(), VicinitySlotsContainer::Combine(), PluginDayzPlayerDebug_Ctrl::CommandHandler(), PluginDayzPlayerDebug_Weapons::CommandHandler(), DayZPlayer::CommandHandlerDebug(), MissionBase::CreateLogoutMenu(), DeactivateModifier(), PluginBase::DeactivateModifier(), PluginDayzPlayerDebug_OtherCmds::Death_Start(), PluginBase::DeleteSceneObject(), WeaponDebug::DisplayGeneralInfo(), Hud::DisplayPresence(), Hud::DisplayStance(), PoweredOptic_Base::DoMeasurement(), Icon::DoubleClick(), HandsContainer::DoubleClick(), AttachmentCategoriesRow::DoubleClick(), ClosableContainer::DoubleClick(), PlayerContainer::DoubleClick(), VicinitySlotsContainer::DoubleClick(), ZombieContainer::DoubleClick(), Icon::DraggingOver(), ClosableContainer::DraggingOver(), DraggingOverCenterPanel(), ClosableContainer::DraggingOverGrid(), ClosableContainer::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), ZombieContainer::DraggingOverHeader(), Icon::DraggingOverSwap(), ScriptConsoleItemsTab::DrawItems(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), AttachmentCategoriesRow::DropReceived(), ClosableContainer::DropReceived(), Icon::DropReceivedFromMain(), EntityLightSource::EOnInit(), HandsContainer::EquipItem(), ItemManager::EvaluateContainerDragabilityDefault(), DayZPlayer::EvaluateDamageHit(), Event_OnClick(), AnalyticsManagerClient::Event_OnEntityKilled(), VicinityItemManager::ExcludeFromContainer_Phase1(), VicinityItemManager::ExcludeFromContainer_Phase2(), VicinityItemManager::ExcludeFromContainer_Phase3(), UIScriptedMenu::ExecuteSelectedItem(), UIScriptedMenu::GameRespawn(), UIScriptedMenu::GameRetry(), GestureMenuItem(), ItemManager::GetChosenCombinationFlag(), HandsContainer::GetCombinationFlags(), ItemManager::GetCombinationFlags(), ColorManager::GetItemColor(), UIScriptedMenu::GetItems(), InventoryGridController::GetQuickbarItemColor(), Attachments::GetRecipeCount(), HandsContainer::GetRecipeCount(), PlayerContainer::GetRecipeCount(), ItemManager::GetRecipeCount(), ActionDismantlePart::GetText(), ActionRepairPart::GetText(), ActionTransferLiquid::GetText(), ActionWorldCraft::GetText(), ActionBuildShelter::GetText(), WeaponDebug::GetWeaponInHands(), UIScriptedMenu::HandleLights(), UIScriptedMenu::HandleNVG(), HandsContainer::HandsContainer(), MissionBase::HideInventory(), PluginDayzPlayerDebug_OtherCmds::Hit_Start(), Init(), UIScriptedMenu::Init(), ScriptConsoleGeneralTab::Init(), ManBase::InitEditor(), PluginBase::InitLoad(), HandsContainer::InspectItem(), AttachmentsOutOfReach::IsAttachmentReachable(), DayZPlayerImplement::IsControlledPlayer(), HandsContainer::IsEmpty(), IsInventoryVisible(), HandsContainer::IsItemActive(), HandsContainer::IsItemWithQuantityActive(), UIScriptedMenu::IsLocalPlayer(), PluginBase::IsModifierLocked(), IsObjectObstructed(), IsObjectObstructedFilterEx(), ScriptConsoleGeneralTab::LateInit(), PluginConfigHandler::LoadScenePlayer(), PluginBase::LockModifier(), LockModifier(), Icon::MouseClick(), AttachmentCategoriesRow::MouseClick(), PlayerContainer::MouseClick(), ZombieContainer::MouseClick(), HandsContainer::MouseClick2(), ClosableContainer::MouseClick2(), MoveFocusByArea(), ActionMenu::NextAction(), ActionMenu::NextActionCategory(), OnActivate(), OnCenterPanelDropReceived(), ScriptConsoleGeneralTab::OnChange(), HudDebugWinBase::OnChange(), PluginDayzPlayerDebug_Weapons::OnClick(), UIScriptedMenu::OnClick(), ScriptConsoleGeneralTab::OnClick(), ScriptConsoleItemsTab::OnClick(), UIScriptedMenu::OnDoubleClick(), ScriptConsoleGeneralTab::OnDoubleClick(), ScriptConsoleItemsTab::OnDoubleClick(), Icon::OnDraggingOverBackground(), PlayerContainer::OnDropReceivedFromGhostArea(), ZombieContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), ClosableContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromHeader(), VicinitySlotsContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), Grenade_Base::OnExplosionEffects(), PluginBase::OnGUITimer(), HandsArea::OnHandsPanelDropReceived(), SlotsIcon::OnIconDrag(), InventoryGridController::OnItemDrag(), InventoryGridController::OnItemDrop(), InventoryGridController::OnItemDropReceived(), MissionBase::OnMissionFinish(), ScriptConsoleGeneralTab::OnMouseButtonDown(), ScriptConsoleSoundsTab::OnMouseButtonDown(), Icon::OnPerformCombination(), HandsContainer::OnPerformCombination(), Icon::OnPerformRecipe(), InventoryItem::OnRightClick(), OnRightPanelDropReceived(), OnScheduledTick(), OnSelectAction(), ScriptConsoleVicinityTab::OnSelectAction(), ScriptedWidgetEventHandler::OnSelectAction(), ScriptedWidgetEventHandler::OnSelectActionEx(), OnShow(), DayZPlayer::OnStepEvent(), PluginBase::OnUIEditorOpened(), DayZPlayerCameraBase::OnUpdate(), PoweredOptic_Base::OnWorkStart(), PoweredOptic_Base::OnWorkStop(), MissionBase::Pause(), Icon::PerformCombination(), UIScriptedMenu::Play(), MissionBase::PlayerControlDisable(), MissionBase::PlayerControlEnable(), PlayerPreview::PlayerPreview(), PlayerSyncDelete(), PluginDayzPlayerDebug_Weapons::PluginDayzPlayerDebug_Weapons(), ActionMenu::PrevAction(), ActionMenu::PrevActionCategory(), UIScriptedMenu::PrimaryAction(), UIScriptedMenu::ProcessEmoteConditionRequest(), ActionMenu::Refresh(), ScriptConsoleGeneralTab::RefreshPlayerPosEditBoxes(), Hud::RefreshPlayerTags(), VicinityItemManager::RefreshVicinityItems(), InventoryGridController::Remove(), EntityAI::RemoveAction(), RemoveAction(), InventoryItem::RemoveAction(), RequestDetailedInfo(), ResetModifiers(), HudDebugWinBase::ResetStats(), RightArea::RightArea(), HudDebugWinBase::RPCChangeStat(), ScriptConsoleEnfScriptTab::RunEnscript(), ScriptConsoleEnfScriptTab::RunEnscriptServer(), SceneObject::SceneObjectSynch(), ScriptConsoleSoundsTab::ScriptConsoleSoundsTab(), UIScriptedMenu::SecondaryAction(), HandsPreview::Select(), PlayerContainer::Select(), VicinitySlotsContainer::Select(), ZombieContainer::Select(), PluginBase::SelectAndFocusPlayerObject(), ScriptConsoleWeatherTab::SendRPC(), HandsContainer::SetActive(), PluginBase::SetDeveloperItemClient(), PluginBase::SetDeveloperItemClientEx(), HandsContainer::SetLastActive(), Container::SetLock(), UIScriptedMenu::SetPreset(), Hud::SetStamina(), SetUpdate(), HudDebugWinBase::SetUpdate(), ScriptedWidgetEventHandler::ShowActionMenu(), MissionBase::ShowInventory(), ItemManager::ShowSourceDropzone(), Hud::ShowVehicleInfo(), PluginBase::SpawnEntityInInventory(), PluginBase::SpawnFromClipboard(), PluginBase::SpawnNewInfectedEntity(), ScriptConsoleItemsTab::SpawnPreset(), InventoryItem::SplitIntoStackMaxClient(), HandsContainer::SplitItem(), Icon::Swap(), HandsContainer::TakeAsAttachment(), ClosableContainer::TakeAsAttachment(), DeveloperTeleport::TeleportAtCursor(), DeveloperTeleport::TeleportAtCursorEx(), TestOwnership(), Tick(), PluginDayzPlayerDebug_Weapons::Tick(), MissionBase::TickScheduler(), ToggleDebugWindowEvent(), PluginBase::ToggleFreeCamera(), PluginBase::ToggleFreeCameraBackPos(), HandsContainer::TransferItem(), AttachmentCategoriesRow::TransferItem(), VicinitySlotsContainer::TransferItem(), Attachments::TransferItemToVicinity(), HandsContainer::TransferItemToVicinity(), AttachmentCategoriesRow::TransferItemToVicinity(), PluginDayzPlayerDebug_OtherCmds::Uncon_End(), PluginDayzPlayerDebug_OtherCmds::Uncon_Start(), HudDebugWinBase::Update(), UIScriptedMenu::Update(), ScriptConsoleGeneralTab::Update(), ScriptConsoleSoundsTab::Update(), Hud::UpdateBloodName(), UpdateConsoleToolbar(), MissionBase::UpdateDebugMonitor(), UIScriptedMenu::UpdateInfo(), HandsHeader::UpdateInterval(), VicinityContainer::UpdateInterval(), UpdateInterval(), PlayerPreview::UpdateInterval(), InventoryGridController::UpdateItems(), ScriptConsoleGeneralTab::UpdateMousePos(), ScriptConsoleSoundsTab::UpdateMousePos(), UpdateSpecialtyMeter(), PluginBase::UpdateStatsLocal(), ScriptConsoleGeneralTab::UpdateTime(), ActionMenu::UpdateWidgets(), UIScriptedMenu::~CameraToolsMenu(), InventoryItem::~ItemBase(), SceneObject::~SceneObject(), and ScriptConsoleGeneralTab::~ScriptConsoleGeneralTab().
Init()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
Definition at line 44 of file ModifierBase.c.
{}
InitBase()
void InitBase (PlayerBase player, ModifiersManager manager)
Definition at line 37 of file ModifierBase.c.
  {
    m_Manager = manager;
    m_Player = player;
    Init();
  }
References ModifierBase::Init(), m_Manager, and m_Player.
IsActive()
bool IsActive ()
Definition at line 124 of file ModifierBase.c.
  {
    return m_IsActive;
  }
References m_IsActive.
Referenced by IsActivable(), IsInactive(), IsTakeable(), OnItemLocationChanged(), OnRPC(), LayoutHolder::RecomputeOpenedContainers(), RefreshState(), ItemBase::SetActive(), LayoutHolder::SetFirstActive(), LayoutHolder::SetLastActive(), and UniversalTemperatureSourceDebug::Update().
IsLocked()
bool IsLocked ()
Definition at line 134 of file ModifierBase.c.
  {
    return m_IsLocked;
  }
References m_IsLocked.
Referenced by IsLockedOnGate(), MissionBase::OnUpdate(), and Tick().
IsPersistent()
bool IsPersistent ()
Definition at line 52 of file ModifierBase.c.
  {
    return m_IsPersistent;
  }
References m_IsPersistent.
IsTrackAttachedTime()
bool IsTrackAttachedTime ()
Definition at line 139 of file ModifierBase.c.
  {
    return m_TrackActivatedTime;
  }
References m_TrackActivatedTime.
MakeParamObjectPersistent()
void MakeParamObjectPersistent (Param object)
Definition at line 57 of file ModifierBase.c.
  {
    m_Manager.m_ParamList.Insert(object);
  }
References m_Manager.
Referenced by TestDiseaseMdfr::Init(), and SymptomBase::OnInit().
ModifierBase()
void ModifierBase ()
Definition at line 32 of file ModifierBase.c.
  {
    Class.CastTo(m_ModulePlayerStatus, GetPlugin(PluginPlayerStatus));
  }
References Class::CastTo(), GetPlugin(), and m_ModulePlayerStatus.
OnActivate()
void OnActivate (PlayerBase player)
is called when an inactive modifier gets activated during gameplay, is NOT called on activation upon player server connection(see OnReconnect)
Definition at line 179 of file ModifierBase.c.
  {
  }
OnDeactivate()
void OnDeactivate (PlayerBase player)
Definition at line 190 of file ModifierBase.c.
  {
  }
OnReconnect()
void OnReconnect (PlayerBase player)
is called when a modifier is being re-activated upon player server connection, use to activate systems which are not persistent and need to run alongside active modifiers
Definition at line 185 of file ModifierBase.c.
  {
  }
OnStoreSave()
void OnStoreSave (ParamsWriteContext ctx)
Definition at line 223 of file ModifierBase.c.
  {
  }
OnTick()
void OnTick (PlayerBase player, float deltaT) private
Definition at line 228 of file ModifierBase.c.
  {
  }
ResetLastTickTime()
void ResetLastTickTime ()
Definition at line 63 of file ModifierBase.c.
  {
    m_LastTickedActive = 0;
  }
References m_LastTickedActive.
SetAttachedTime()
void SetAttachedTime (float time)
Definition at line 149 of file ModifierBase.c.
  {
    m_ActivatedTime = time;
  }
References m_ActivatedTime.
SetLock()
void SetLock (bool state)
Definition at line 129 of file ModifierBase.c.
  {
    m_IsLocked = state;
  }
References m_IsLocked.
Referenced by Container::SetEntity(), and Container::~CargoContainer().
Tick()
void Tick (float delta_time)
Definition at line 88 of file ModifierBase.c.
  {
    if (!m_IsActive && m_ShouldBeActive)
      Activate();
    if (m_IsActive)
    {
      m_AccumulatedTimeActive += delta_time;
      if (m_AccumulatedTimeActive > m_TickIntervalActive)
      {
        if (m_TickType & eModifiersTickType.DEACTIVATE_CHECK && DeactivateCondition(m_Player) && !IsLocked())
          Deactivate();
        else//if(m_TickType & eModifiersTickType.TICK)
        {
          m_ActivatedTime += m_AccumulatedTimeActive;
          OnTick(m_Player, m_AccumulatedTimeActive);
        }
        m_AccumulatedTimeActive = 0;
      }
    }
    else if (m_TickType & eModifiersTickType.ACTIVATE_CHECK)
    {
      m_AccumulatedTimeInactive += delta_time;
      if (m_AccumulatedTimeInactive > m_TickIntervalInactive)
      {
        if (ActivateCondition(m_Player))
        {
          if (!IsLocked())
            ActivateRequest(EActivationType.TRIGGER_EVENT_ON_ACTIVATION);
        }
        m_AccumulatedTimeInactive = 0;
      }
    }
  }
References Activate(), ModifierBase::ActivateCondition(), ActivateRequest(), Deactivate(), ModifierBase::DeactivateCondition(), IsLocked(), m_AccumulatedTimeActive, m_AccumulatedTimeInactive, m_ActivatedTime, m_IsActive, m_Player, m_ShouldBeActive, m_TickIntervalActive, m_TickIntervalInactive, m_TickType, and ModifierBase::OnTick().
Variable Documentation
m_AccumulatedTimeActive
float m_AccumulatedTimeActive
Definition at line 22 of file ModifierBase.c.
Referenced by Tick().
m_AccumulatedTimeInactive
float m_AccumulatedTimeInactive
Definition at line 23 of file ModifierBase.c.
Referenced by Tick().
m_ActivatedTime
float m_ActivatedTime
Definition at line 14 of file ModifierBase.c.
Referenced by Deactivate(), GetAttachedTime(), SetAttachedTime(), and Tick().
m_ActivationType
EActivationType m_ActivationType
Definition at line 28 of file ModifierBase.c.
Referenced by Activate(), ActivateRequest(), and BrokenLegsMdfr::Init().
m_ID
enum eModifiersTickType m_ID = 0
m_IsActive
bool m_IsActive
Definition at line 20 of file ModifierBase.c.
Referenced by Activate(), LayoutHolder::Container(), Deactivate(), Event_OnClick(), Hide(), PluginBase::Hide(), IsActive(), ItemBase::IsActive(), ScriptedWidgetEventHandler::IsActive(), RightArea::MoveUpDownIcons(), OnGUITimer(), OnStoreSave(), ItemBase::OnStoreSave(), PluginBase::OnUpdate(), OnUpdate(), OnVariablesSynchronized(), HandsContainer::Refresh(), SetActive(), ItemBase::SetActive(), LayoutHolder::SetActive(), ScriptedWidgetEventHandler::SetActive(), LayoutHolder::SetFirstActive(), ItemBase::SetInactive(), SetInactive(), LayoutHolder::SetLastActive(), ItemBase::SetUsed(), Show(), PluginBase::Show(), ShowWidgets(), Tick(), ToggleDebugWindowEvent(), ToggleDebugWindowEventOld(), ToggleDebugWindowEventP(), Container::UpdateSelection(), and LeftArea::UpdateSelectionIcons().
m_IsLocked
bool m_IsLocked = false
Definition at line 27 of file ModifierBase.c.
Referenced by CheckLockedStateServer(), IsLocked(), SetBaseLockValues(), CombinationLock::SetBaseLockValues(), and SetLock().
m_IsPersistent
bool m_IsPersistent
Definition at line 16 of file ModifierBase.c.
Referenced by AntibioticsMdfr::Init(), CharcoalMdfr::Init(), BrokenLegsMdfr::Init(), HeartAttackMdfr::Init(), HemolyticReactionMdfr::Init(), PoisoningMdfr::Init(), DisinfectionMdfr::Init(), EpinephrineMdfr::Init(), ImmunityBoost::Init(), MorphineMdfr::Init(), PainKillersMdfr::Init(), SalineMdfr::Init(), IsPersistent(), and SymptomBase::OnInit().
m_LastTickedActive
float m_LastTickedActive
Definition at line 24 of file ModifierBase.c.
Referenced by ResetLastTickTime().
m_LastTickedInactive
float m_LastTickedInactive
Definition at line 26 of file ModifierBase.c.
m_Manager
ModifiersManager m_Manager
Definition at line 12 of file ModifierBase.c.
Referenced by SymptomBase::CanActivate(), ContaminatedTrigger_Dynamic(), InitBase(), MakeParamObjectPersistent(), SymptomBase::OnGetActivatedServer(), and MaskMdfr::OnTick().
m_ModulePlayerStatus
PluginPlayerStatus m_ModulePlayerStatus
Definition at line 30 of file ModifierBase.c.
Referenced by Debug(), MessageReceiverBase::DisplayElementBase(), ManBase::Init(), ModifierBase(), ManBase::SetStamina(), and DisplayElementBase::UpdateHUD().
m_Player
PlayerBase m_Player
Definition at line 17 of file ModifierBase.c.
m_ShouldBeActive
bool m_ShouldBeActive
Definition at line 21 of file ModifierBase.c.
Referenced by ActivateRequest(), Deactivate(), and Tick().
m_SyncID
eModifierSyncIDs m_SyncID
Definition at line 29 of file ModifierBase.c.
Referenced by Activate(), AreaExposureMdfr::Init(), FeverMdfr::Init(), ContaminationStage1Mdfr::Init(), ContaminationStage2Mdfr::Init(), ContaminationStage3Mdfr::Init(), WoundInfectStage1Mdfr::Init(), WoundInfectStage2Mdfr::Init(), and DrowningMdfr::Init().
m_System
string m_System = "Modifiers"
Definition at line 13 of file ModifierBase.c.
Referenced by MessageReceiverBase::DisplayElementBase().
m_TickIntervalActive
float m_TickIntervalActive = 3
Definition at line 19 of file ModifierBase.c.
Referenced by AntibioticsMdfr::Init(), BloodRegenMdfr::Init(), BoneRegenMdfr::Init(), ModifierBase::Init(), CharcoalMdfr::Init(), AreaExposureMdfr::Init(), BleedingCheckMdfr::Init(), BlindedMdfr::Init(), BrokenArmsMdfr::Init(), BrokenLegsMdfr::Init(), BurningMdfr::Init(), FatigueMdfr::Init(), FeverMdfr::Init(), HeartAttackMdfr::Init(), HeatBufferMdfr::Init(), HemolyticReactionMdfr::Init(), PoisoningMdfr::Init(), StuffedStomachMdfr::Init(), TremorMdfr::Init(), VomitStuffedMdfr::Init(), WetMdfr::Init(), BrainDiseaseMdfr::Init(), CholeraMdfr::Init(), CommonColdMdfr::Init(), ContaminationStage1Mdfr::Init(), ContaminationStage2Mdfr::Init(), ContaminationStage3Mdfr::Init(), InfluenzaMdfr::Init(), SalmonellaMdfr::Init(), TestDiseaseMdfr::Init(), WoundInfectStage1Mdfr::Init(), WoundInfectStage2Mdfr::Init(), DisinfectionMdfr::Init(), DrowningMdfr::Init(), EpinephrineMdfr::Init(), FliesMdfr::Init(), HealthMdfr::Init(), HealthRegenMdfr::Init(), HeatComfortMdfr::Init(), HungerMdfr::Init(), ImmuneSystemMdfr::Init(), ImmunityBoost::Init(), MaskMdfr::Init(), MorphineMdfr::Init(), PainKillersMdfr::Init(), SalineMdfr::Init(), ShockMdfr::Init(), ShockDamageMdfr::Init(), StomachMdfr::Init(), TestingMdfr::Init(), ThirstMdfr::Init(), ToxicityMdfr::Init(), UnconsciousnessMdfr::Init(), and Tick().
m_TickIntervalInactive
float m_TickIntervalInactive = 5
Definition at line 18 of file ModifierBase.c.
Referenced by AntibioticsMdfr::Init(), BloodRegenMdfr::Init(), BoneRegenMdfr::Init(), ModifierBase::Init(), CharcoalMdfr::Init(), AreaExposureMdfr::Init(), BleedingCheckMdfr::Init(), BlindedMdfr::Init(), BrokenArmsMdfr::Init(), BrokenLegsMdfr::Init(), BurningMdfr::Init(), FatigueMdfr::Init(), FeverMdfr::Init(), HeartAttackMdfr::Init(), HeatBufferMdfr::Init(), HemolyticReactionMdfr::Init(), PoisoningMdfr::Init(), StuffedStomachMdfr::Init(), TremorMdfr::Init(), VomitStuffedMdfr::Init(), WetMdfr::Init(), BrainDiseaseMdfr::Init(), CholeraMdfr::Init(), CommonColdMdfr::Init(), ContaminationStage1Mdfr::Init(), ContaminationStage2Mdfr::Init(), ContaminationStage3Mdfr::Init(), InfluenzaMdfr::Init(), SalmonellaMdfr::Init(), TestDiseaseMdfr::Init(), WoundInfectStage1Mdfr::Init(), WoundInfectStage2Mdfr::Init(), DisinfectionMdfr::Init(), DrowningMdfr::Init(), EpinephrineMdfr::Init(), FliesMdfr::Init(), HealthMdfr::Init(), HealthRegenMdfr::Init(), HeatComfortMdfr::Init(), HungerMdfr::Init(), ImmuneSystemMdfr::Init(), ImmunityBoost::Init(), MaskMdfr::Init(), MorphineMdfr::Init(), PainKillersMdfr::Init(), SalineMdfr::Init(), ShockMdfr::Init(), ShockDamageMdfr::Init(), StomachMdfr::Init(), TestingMdfr::Init(), ThirstMdfr::Init(), ToxicityMdfr::Init(), UnconsciousnessMdfr::Init(), and Tick().
m_TickType
int m_TickType = (eModifiersTickType.TICK | eModifiersTickType.ACTIVATE_CHECK | eModifiersTickType.DEACTIVATE_CHECK)
Definition at line 25 of file ModifierBase.c.
Referenced by DisableActivateCheck(), DisableDeactivateCheck(), and Tick().
m_TrackActivatedTime
bool m_TrackActivatedTime
Definition at line 15 of file ModifierBase.c.
Referenced by AntibioticsMdfr::Init(), BloodRegenMdfr::Init(), BoneRegenMdfr::Init(), ModifierBase::Init(), CharcoalMdfr::Init(), AreaExposureMdfr::Init(), BleedingCheckMdfr::Init(), BlindedMdfr::Init(), BrokenArmsMdfr::Init(), BrokenLegsMdfr::Init(), BurningMdfr::Init(), FatigueMdfr::Init(), FeverMdfr::Init(), HeartAttackMdfr::Init(), HeatBufferMdfr::Init(), HemolyticReactionMdfr::Init(), PoisoningMdfr::Init(), StuffedStomachMdfr::Init(), TremorMdfr::Init(), VomitStuffedMdfr::Init(), WetMdfr::Init(), BrainDiseaseMdfr::Init(), CholeraMdfr::Init(), CommonColdMdfr::Init(), ContaminationStage3Mdfr::Init(), InfluenzaMdfr::Init(), SalmonellaMdfr::Init(), TestDiseaseMdfr::Init(), WoundInfectStage1Mdfr::Init(), WoundInfectStage2Mdfr::Init(), DisinfectionMdfr::Init(), DrowningMdfr::Init(), EpinephrineMdfr::Init(), FliesMdfr::Init(), HealthMdfr::Init(), HealthRegenMdfr::Init(), HeatComfortMdfr::Init(), HungerMdfr::Init(), ImmuneSystemMdfr::Init(), ImmunityBoost::Init(), MaskMdfr::Init(), MorphineMdfr::Init(), PainKillersMdfr::Init(), SalineMdfr::Init(), ShockDamageMdfr::Init(), StomachMdfr::Init(), TestingMdfr::Init(), ThirstMdfr::Init(), ToxicityMdfr::Init(), UnconsciousnessMdfr::Init(), and IsTrackAttachedTime().