DayZ: scripts/5_Mission/GUI/GesturesMenu.c File Reference
GesturesMenu.c File Reference
Classes
class UIScriptedMenu
Enumerations
enum GestureCategories {
CATEGORIES , CATEGORY_1 , CATEGORY_2 , CATEGORY_3 ,
CATEGORY_4 , CATEGORY_5 , CONSOLE_GESTURES
}
Functions
void GestureMenuItem (int id, string name, GestureCategories category)
string GetName ()
Gets the name which is set for the ParticleManager, default is "ParticleSourceManager".
string GetBoundButtonText ()
int GetID ()
GestureCategories GetCategory ()
Widget GetRadialItemCard ()
void SetRadialItemCard (Widget widget)
void SetCanPerformEmote (bool state)
bool GetCanPerformEmote ()
Variables
enum GestureCategories m_ID
string m_Name
GestureCategories m_Category
EmoteBase m_EmoteClass
bool m_CanPerformEmote
Widget m_RadialMenuSelector
Widget m_RadialMenuItemCard
Enumeration Type Documentation
GestureCategories
enum GestureCategories
Enumerator
CATEGORIES
CATEGORY_1
CATEGORY_2
CATEGORY_3
CATEGORY_4
CATEGORY_5
CONSOLE_GESTURES
Definition at line 1 of file GesturesMenu.c.
{
  CATEGORIES, //special category selection
  CATEGORY_1,
  CATEGORY_2,
  CATEGORY_3,
  CATEGORY_4,
  CATEGORY_5,
  CONSOLE_GESTURES
}
Function Documentation
GestureMenuItem()
void GestureMenuItem (int id, string name, GestureCategories category) protected
Definition at line 23 of file GesturesMenu.c.
  {
    m_ID = id;
    m_Name = name;
    m_Category = category;
    m_CanPerformEmote = true;
    PlayerBase player;
    if (Class.CastTo(player, GetGame().GetPlayer()) && category != GestureCategories.CATEGORIES)
      m_EmoteClass = player.GetEmoteManager().GetNameEmoteMap().Get(id);
  }
References Class::CastTo(), GetGame(), GetPlayer(), m_CanPerformEmote, m_Category, m_EmoteClass, m_ID, m_Name, and name.
Referenced by UIScriptedMenu::CreateGestureContent(), UIScriptedMenu::ExecuteSelectedCategory(), UIScriptedMenu::ExecuteSelectedItem(), UIScriptedMenu::GetGestureItems(), UIScriptedMenu::MarkSelected(), and UIScriptedMenu::UnmarkSelected().
GetBoundButtonText()
string GetBoundButtonText () protected
Definition at line 40 of file GesturesMenu.c.
  {
    string ret = "";
    if (GetGame().GetInput().IsEnabledMouseAndKeyboardEvenOnServer() && m_EmoteClass && m_EmoteClass.GetInputActionName() != "")
    {
      map<int, ref TStringArray> button_map = InputUtils.GetComboButtonNamesFromInput(m_EmoteClass.GetInputActionName(), EInputDeviceType.MOUSE_AND_KEYBOARD);
      if (button_map && button_map.Count() > 0)
      {
        TStringArray buttons;
        for (int j = 0; j < button_map.Count(); j++)
        {
          if (j > 0)
            ret += "; ";
          buttons = button_map.GetElement(j);
          for (int i = 0; i < buttons.Count(); i++)
          {
            if (i > 0)
              ret += " + ";
            ret += buttons[i];
          }
        }
      }
    }
    return ret;
  }
References InputUtils::GetComboButtonNamesFromInput(), GetGame(), GetInput(), EmoteBase::GetInputActionName(), and m_EmoteClass.
GetCanPerformEmote()
bool GetCanPerformEmote () protected
Definition at line 94 of file GesturesMenu.c.
  {
    return m_CanPerformEmote;
  }
References m_CanPerformEmote.
GetCategory()
GestureCategories GetCategory () protected
Definition at line 74 of file GesturesMenu.c.
  {
    return m_Category;
  }
References m_Category.
GetID()
int GetID () protected
Definition at line 69 of file GesturesMenu.c.
  {
    return m_ID;
  }
References m_ID.
GetRadialItemCard()
Widget GetRadialItemCard () protected
Definition at line 79 of file GesturesMenu.c.
  {
    return m_RadialMenuItemCard;
  }
References m_RadialMenuItemCard.
SetCanPerformEmote()
void SetCanPerformEmote (bool state) protected
Definition at line 89 of file GesturesMenu.c.
  {
    m_CanPerformEmote = state;
  }
References m_CanPerformEmote.
SetRadialItemCard()
void SetRadialItemCard (Widget widget) protected
Definition at line 84 of file GesturesMenu.c.
  {
    m_RadialMenuItemCard = widget;
  }
References m_RadialMenuItemCard.
Variable Documentation
m_CanPerformEmote
bool m_CanPerformEmote protected
Definition at line 18 of file GesturesMenu.c.
Referenced by GestureMenuItem(), GetCanPerformEmote(), and SetCanPerformEmote().
m_Category
GestureCategories m_Category protected
Definition at line 16 of file GesturesMenu.c.
m_EmoteClass
EmoteBase m_EmoteClass protected
Definition at line 17 of file GesturesMenu.c.
Referenced by GestureMenuItem(), and GetBoundButtonText().
m_ID
enum GestureCategories m_ID
m_Name
string m_Name protected
Definition at line 15 of file GesturesMenu.c.
m_RadialMenuItemCard
Widget m_RadialMenuItemCard protected
Definition at line 21 of file GesturesMenu.c.
Referenced by GetRadialItemCard(), and SetRadialItemCard().
m_RadialMenuSelector
Widget m_RadialMenuSelector protected
Definition at line 20 of file GesturesMenu.c.