DayZ: scripts/4_World/Entities/ItemBase/ClockBase.c File Reference
ClockBase.c File Reference
Enumerations
enum EAlarmClockState { UNSET , SET , RINGING , COUNT }
Functions
void ClockBase ()
void ~ClockBase ()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
override void SetActions ()
int GetAlarmInMin ()
static int ConvertAlarmHand01ToMins12h (float time01)
static int ConvertAlarmHand01ToMins (float time01, int mins_max)
static float ConvertMins12hToAlarmHand01 (int mins)
static int ConvertTimeToMins12h (int hour, int minute)
static int GetTimeDiffInMins12h (int from_mins, int to_mins)
string GetToggleSound ()
string GetRingingSound ()
string GetHitSound ()
string GetDestroyedSound ()
string GetWorkingSound ()
override void EEKilled (Object killer)
override void EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos)
override void OnDamageDestroyed (int oldLevel)
void OnRingingStartServer ()
void OnRingingStartClient ()
void OnRingingStopServer ()
void OnRingingStopClient ()
void SetAlarmInXMins (int in_mins)
float GetRingingDurationMax ()
void SetupTimerServer ()
void SetState (EAlarmClockState state)
void Disarm ()
void Arm ()
void ActivateParent ()
void MakeRingingStart ()
void MakeRingingStop ()
void TurnOnClient ()
void TurnOffClient ()
override void OnVariablesSynchronized ()
bool IsRinging ()
bool IsAlarmOn ()
void TurnOn ()
void TurnOff ()
void SetAlarmTimeServer (float time01)
Variables
enum EAlarmClockState m_AlarmTime01
int m_State = EAlarmClockState.UNSET
static const float UPDATE_TICK_RATE = 1
ref Timer m_TimerUpdate
float m_RingingDuration
int m_StatePrev = -1
EffectSound m_RingingSoundLoop
EffectSound m_TurnOnSound
EffectSound m_DestoryedSound
EffectSound m_HitSound
EffectSound m_WorkingSound
const float RINGING_DURATION_MAX = 60
Enumeration Type Documentation
EAlarmClockState
enum EAlarmClockState
Enumerator
UNSET
SET
RINGING
COUNT
Definition at line 1 of file ClockBase.c.
{
  UNSET,
  SET,
  RINGING,
  //-----------
  COUNT
}
Function Documentation
ActivateParent()
void ActivateParent () protected
Definition at line 203 of file ClockBase.c.
  {
    if (GetHierarchyParent())
    {
      ItemBase parent = ItemBase.Cast(GetHierarchyParent());
      if (parent)
        parent.OnActivatedByItem(this);
    }
  }
Referenced by OnRingingStartServer().
Arm()
void Arm () protected
Definition at line 196 of file ClockBase.c.
  {
    SetupTimerServer();
    SetState(EAlarmClockState.SET);
    m_RingingDuration = 0;
  }
References m_RingingDuration, SetState(), and SetupTimerServer().
ClockBase()
void ClockBase ()
Definition at line 27 of file ClockBase.c.
  {
    Init();
  }
References Init().
ConvertAlarmHand01ToMins()
static int ConvertAlarmHand01ToMins (float time01, int mins_max) static protected
Definition at line 70 of file ClockBase.c.
  {
    return Math.Lerp(0, mins_max, time01);
  }
References Math::Lerp().
ConvertAlarmHand01ToMins12h()
static int ConvertAlarmHand01ToMins12h (float time01) static protected
Definition at line 65 of file ClockBase.c.
  {
    return Math.Lerp(0, 12 * 60, time01);
  }
References Math::Lerp().
Referenced by GetAlarmInMin(), and AlarmClock_ColorBase::OnUpdate().
ConvertMins12hToAlarmHand01()
static float ConvertMins12hToAlarmHand01 (int mins) static protected
Definition at line 75 of file ClockBase.c.
  {
    return Math.InverseLerp(0, 12 * 60, mins);
  }
References Math::InverseLerp().
Referenced by SetAlarmInXMins().
ConvertTimeToMins12h()
static int ConvertTimeToMins12h (int hour, int minute) static protected
Definition at line 81 of file ClockBase.c.
  {
    if (hour >= 12)
      hour -= 12;
    return hour * 60 + minute;
  }
Referenced by GetAlarmInMin(), AlarmClock_ColorBase::OnUpdate(), and SetAlarmInXMins().
Disarm()
void Disarm () protected
Definition at line 191 of file ClockBase.c.
  {
    SetState(EAlarmClockState.UNSET);
  }
References SetState().
Referenced by TurnOff().
EEHitByRemote()
override void EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos) protected
Definition at line 124 of file ClockBase.c.
  {
    super.EEHitByRemote(damageType, source, component, dmgZone, ammo, modelPos);
    PlaySoundSet(m_HitSound, GetHitSound(), 0, 0);
  }
References component, GetHitSound(), and m_HitSound.
EEKilled()
override void EEKilled (Object killer) protected
Definition at line 118 of file ClockBase.c.
  {
    super.EEKilled(killer);
    TurnOff();
  }
References TurnOff().
GetAlarmInMin()
int GetAlarmInMin () protected
Definition at line 53 of file ClockBase.c.
  {
    int alarm_hand_in_mins = ConvertAlarmHand01ToMins12h(m_AlarmTime01);
    int pass, hour, minute;
    GetGame().GetWorld().GetDate(pass, pass, pass, hour, minute);
    int curr_time_in_minutes = ConvertTimeToMins12h(hour, minute);
    int ring_in_mins = GetTimeDiffInMins12h(curr_time_in_minutes, alarm_hand_in_mins);
    return ring_in_mins;
  }
References ConvertAlarmHand01ToMins12h(), ConvertTimeToMins12h(), GetGame(), GetTimeDiffInMins12h(), and m_AlarmTime01.
Referenced by AlarmClock_ColorBase::GetDebugText().
GetDestroyedSound()
string GetDestroyedSound () protected
Definition at line 109 of file ClockBase.c.
  {
    return "";
  }
Referenced by OnDamageDestroyed().
GetHitSound()
string GetHitSound () protected
Definition at line 105 of file ClockBase.c.
  {
    return "";
  }
Referenced by EEHitByRemote().
GetRingingDurationMax()
float GetRingingDurationMax () protected
Definition at line 173 of file ClockBase.c.
  {
    return RINGING_DURATION_MAX;
  }
References RINGING_DURATION_MAX.
Referenced by AlarmClock_ColorBase::GetDebugText(), and AlarmClock_ColorBase::OnUpdate().
GetRingingSound()
string GetRingingSound () protected
Definition at line 101 of file ClockBase.c.
  {
    return "";
  }
Referenced by OnRingingStartClient().
GetTimeDiffInMins12h()
static int GetTimeDiffInMins12h (int from_mins, int to_mins) static protected
Definition at line 88 of file ClockBase.c.
  {
    if (to_mins > from_mins)
      return to_mins - from_mins;
    else if (to_mins < from_mins)
      return ((12 * 60) - from_mins) + to_mins;
    else return 0;
  }
Referenced by GetAlarmInMin().
GetToggleSound()
string GetToggleSound () protected
Definition at line 97 of file ClockBase.c.
  {
    return "";
  }
Referenced by OnVariablesSynchronized().
GetWorkingSound()
string GetWorkingSound () protected
Definition at line 113 of file ClockBase.c.
  {
    return "";
  }
Referenced by OnVariablesSynchronized().
Init()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
pre-init arrays
Definition at line 41 of file ClockBase.c.
  {
    RegisterNetSyncVariableInt("m_State", 0, EAlarmClockState.COUNT - 1);
  }
IsAlarmOn()
bool IsAlarmOn () protected
Definition at line 274 of file ClockBase.c.
  {
    return (m_State == EAlarmClockState.SET);
  }
References m_State.
Referenced by AlarmClock_ColorBase::OnUpdate().
IsRinging()
bool IsRinging () protected
Definition at line 269 of file ClockBase.c.
  {
    return (m_State == EAlarmClockState.RINGING);
  }
References m_State.
Referenced by AlarmClock_ColorBase::OnUpdate(), KitchenTimer::OnUpdate(), and TurnOff().
MakeRingingStart()
void MakeRingingStart () protected
Definition at line 213 of file ClockBase.c.
  {
    if (!m_TimerUpdate)
      SetupTimerServer();
    SetState(EAlarmClockState.RINGING);
    OnRingingStartServer();
  }
References m_TimerUpdate, OnRingingStartServer(), SetState(), and SetupTimerServer().
Referenced by AlarmClock_ColorBase::OnDebugSpawn(), AlarmClock_ColorBase::OnStoreLoad(), KitchenTimer::OnStoreLoad(), AlarmClock_ColorBase::OnUpdate(), and KitchenTimer::OnUpdate().
MakeRingingStop()
void MakeRingingStop () protected
Definition at line 222 of file ClockBase.c.
  {
    SetState(EAlarmClockState.UNSET);
    OnRingingStopServer();
  }
References OnRingingStopServer(), and SetState().
Referenced by KitchenTimer::OnUpdate(), and TurnOff().
OnDamageDestroyed()
override void OnDamageDestroyed (int oldLevel) protected
Definition at line 130 of file ClockBase.c.
  {
    super.OnDamageDestroyed(oldLevel);
    if (GetGame().IsClient())
    {
      OnRingingStopClient();
      if (oldLevel != -1)
        PlaySoundSet(m_DestoryedSound, GetDestroyedSound(), 0, 0);
    }
  }
References GetDestroyedSound(), GetGame(), m_DestoryedSound, and OnRingingStopClient().
OnRingingStartClient()
void OnRingingStartClient () protected
Definition at line 148 of file ClockBase.c.
  {
    PlaySoundSetLoop(m_RingingSoundLoop, GetRingingSound(), 0, 0);
    if (m_WorkingSound)
      SEffectManager.DestroyEffect(m_WorkingSound);
  }
References SEffectManager::DestroyEffect(), GetRingingSound(), m_RingingSoundLoop, and m_WorkingSound.
Referenced by OnVariablesSynchronized().
OnRingingStartServer()
void OnRingingStartServer () protected
Definition at line 143 of file ClockBase.c.
  {
    ActivateParent();
  }
References ActivateParent().
Referenced by MakeRingingStart().
OnRingingStopClient()
void OnRingingStopClient () protected
Definition at line 158 of file ClockBase.c.
  {
    SEffectManager.DestroyEffect(m_RingingSoundLoop);
  }
References SEffectManager::DestroyEffect(), and m_RingingSoundLoop.
Referenced by OnDamageDestroyed(), OnVariablesSynchronized(), and AlarmClock_ColorBase::~AlarmClock_ColorBase().
OnRingingStopServer()
void OnRingingStopServer () protected
Referenced by MakeRingingStop().
OnVariablesSynchronized()
override void OnVariablesSynchronized () protected
Definition at line 233 of file ClockBase.c.
  {
    super.OnVariablesSynchronized();
    if (m_State != m_StatePrev)//state changed
    {
      if (m_StatePrev == EAlarmClockState.RINGING)
        OnRingingStopClient();
      else if (m_State == EAlarmClockState.RINGING)
        OnRingingStartClient();
      if (m_State == EAlarmClockState.SET)
      {
        if (m_StatePrev != -1 || IsInitialized())
          PlaySoundSet(m_TurnOnSound, GetToggleSound(), 0, 0);
        if (GetWorkingSound())
          PlaySoundSet(m_WorkingSound, GetWorkingSound(), 0, 0, true);
      }
      else if (m_State == EAlarmClockState.UNSET)
      {
        if (m_StatePrev == EAlarmClockState.SET)
        {
          if (m_WorkingSound)
            SEffectManager.DestroyEffect(m_WorkingSound);
          if (m_StatePrev != -1 || IsInitialized())
            PlaySoundSet(m_TurnOnSound, GetToggleSound(), 0, 0);
        }
      }
      m_StatePrev = m_State;
    }
  }
References SEffectManager::DestroyEffect(), GetToggleSound(), GetWorkingSound(), IsInitialized(), m_State, m_StatePrev, m_TurnOnSound, m_WorkingSound, OnRingingStartClient(), and OnRingingStopClient().
SetActions()
override void SetActions ()
Definition at line 46 of file ClockBase.c.
  {
    super.SetActions();
    AddAction(ActionAttachExplosivesTrigger);
  }
References ActionAttachExplosivesTrigger(), and AddAction().
SetAlarmInXMins()
void SetAlarmInXMins (int in_mins) protected
Definition at line 163 of file ClockBase.c.
  {
    int pass, hour, minute;
    GetGame().GetWorld().GetDate(pass, pass, pass, hour, minute);
    int mins12h = ConvertTimeToMins12h(hour, minute) + in_mins;
    float time01 = ConvertMins12hToAlarmHand01(mins12h);
    SetAlarmTimeServer(time01);
    Arm();
  }
References Arm(), ConvertMins12hToAlarmHand01(), ConvertTimeToMins12h(), GetGame(), and SetAlarmTimeServer().
Referenced by AlarmClock_ColorBase::OnAction().
SetAlarmTimeServer()
void SetAlarmTimeServer (float time01) protected
Definition at line 294 of file ClockBase.c.
  {
    SetAnimationPhaseNow("ClockAlarm", time01);
    m_AlarmTime01 = time01;
  }
References m_AlarmTime01.
Referenced by AlarmClock_ColorBase::OnStoreLoad(), and SetAlarmInXMins().
SetState()
void SetState (EAlarmClockState state) protected
Definition at line 185 of file ClockBase.c.
  {
    m_State = state;
    SetSynchDirty();
  }
References m_State.
SetupTimerServer()
void SetupTimerServer () protected
Definition at line 179 of file ClockBase.c.
  {
    m_TimerUpdate = new Timer();
    m_TimerUpdate.Run(UPDATE_TICK_RATE, this, "OnUpdate", null, true);
  }
References m_TimerUpdate, and UPDATE_TICK_RATE.
Referenced by Arm(), and MakeRingingStart().
TurnOff()
void TurnOff () protected
Definition at line 284 of file ClockBase.c.
  {
    if (IsRinging())
      MakeRingingStop();
    else
      Disarm();
    m_TimerUpdate = null;
  }
References Disarm(), IsRinging(), m_TimerUpdate, and MakeRingingStop().
Referenced by EEKilled(), and AlarmClock_ColorBase::OnUpdate().
TurnOffClient()
void TurnOffClient () protected
TurnOn()
void TurnOn () protected
Definition at line 279 of file ClockBase.c.
  {
    Arm();
  }
References Arm().
Referenced by AlarmClock_ColorBase::OnDebugSpawn(), AlarmClock_ColorBase::OnStoreLoad(), and KitchenTimer::SetAlarmTimeServer().
TurnOnClient()
void TurnOnClient () protected
~ClockBase()
void ~ClockBase ()
Definition at line 32 of file ClockBase.c.
  {
    SEffectManager.DestroyEffect(m_WorkingSound);
    SEffectManager.DestroyEffect(m_HitSound);
    SEffectManager.DestroyEffect(m_DestoryedSound);
    SEffectManager.DestroyEffect(m_TurnOnSound);
    SEffectManager.DestroyEffect(m_RingingSoundLoop);
  }
References SEffectManager::DestroyEffect(), m_DestoryedSound, m_HitSound, m_RingingSoundLoop, m_TurnOnSound, and m_WorkingSound.
Variable Documentation
m_AlarmTime01
enum EAlarmClockState m_AlarmTime01
Referenced by GetAlarmInMin(), AlarmClock_ColorBase::OnStoreSave(), AlarmClock_ColorBase::OnUpdate(), and SetAlarmTimeServer().
m_DestoryedSound
EffectSound m_DestoryedSound
Definition at line 21 of file ClockBase.c.
Referenced by OnDamageDestroyed(), and ~ClockBase().
m_HitSound
EffectSound m_HitSound
Definition at line 22 of file ClockBase.c.
Referenced by EEHitByRemote(), and ~ClockBase().
m_RingingDuration
float m_RingingDuration
Definition at line 16 of file ClockBase.c.
Referenced by Arm(), AlarmClock_ColorBase::GetDebugText(), KitchenTimer::GetDebugText(), AlarmClock_ColorBase::OnUpdate(), and KitchenTimer::OnUpdate().
m_RingingSoundLoop
EffectSound m_RingingSoundLoop
Definition at line 19 of file ClockBase.c.
Referenced by OnRingingStartClient(), OnRingingStopClient(), KitchenTimer::OnRingingStopClient(), and ~ClockBase().
m_State
int m_State = EAlarmClockState.UNSET
Definition at line 13 of file ClockBase.c.
m_StatePrev
int m_StatePrev = -1
Definition at line 17 of file ClockBase.c.
Referenced by OnVariablesSynchronized(), and SetState().
m_TimerUpdate
ref Timer m_TimerUpdate
Definition at line 15 of file ClockBase.c.
Referenced by Init(), MakeRingingStart(), SetupTimerServer(), TurnOff(), and ~HudDebug().
m_TurnOnSound
EffectSound m_TurnOnSound
Definition at line 20 of file ClockBase.c.
Referenced by OnVariablesSynchronized(), and ~ClockBase().
m_WorkingSound
EffectSound m_WorkingSound
Definition at line 23 of file ClockBase.c.
Referenced by OnRingingStartClient(), OnVariablesSynchronized(), KitchenTimer::TurnOff(), and ~ClockBase().
RINGING_DURATION_MAX
const float RINGING_DURATION_MAX = 60
Definition at line 25 of file ClockBase.c.
Referenced by GetRingingDurationMax().
UPDATE_TICK_RATE
const float UPDATE_TICK_RATE = 1 static
Definition at line 14 of file ClockBase.c.
Referenced by AlarmClock_ColorBase::OnUpdate(), KitchenTimer::OnUpdate(), and SetupTimerServer().