DayZ: scripts/4_World/Entities/Firearms/Archery/Crossbow.c File Reference
Crossbow.c File Reference
Classes
class WeaponStableState
represents weapon's stable state (i.e. the basic states that the weapon will spend the most time in)
class Crossbow_Base
base for Crossbow @NOTE name copies config base class
Enumerations
enum XBAnimState { uncocked = 0 , cocked = 1 }
enum XBStableStateID
Functions
enum XBStableStateID OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
Variables
UNKNOWN = 0
UncockedEmpty = 1
CockedEmpty = 2
Loaded = 3
class XBCockedEmpty extends WeaponStableState OnEntry
Enumeration Type Documentation
XBAnimState
enum XBAnimState
Enumerator
uncocked
default weapon state, closed and discharged
cocked
Definition at line 1 of file Crossbow.c.
{
  uncocked = 0,
  cocked = 1,
};
XBStableStateID
enum XBStableStateID
Definition at line 7 of file Crossbow.c.
{
  UNKNOWN = 0,
  UncockedEmpty = 1,
  CockedEmpty = 2,
  Loaded = 3,
}
Function Documentation
GetCurrentStateID()
override int GetCurrentStateID ()
Definition at line 19 of file Crossbow.c.
{ return XBStableStateID.UncockedEmpty; }
HasBullet()
override bool HasBullet ()
Definition at line 20 of file Crossbow.c.
{ return false; }
HasMagazine()
override bool HasMagazine ()
Definition at line 21 of file Crossbow.c.
{ return false; }
InitMuzzleArray()
override void InitMuzzleArray ()
Definition at line 24 of file Crossbow.c.
{ m_muzzleHasBullet = {MuzzleState.E}; }
References m_muzzleHasBullet.
IsJammed()
override bool IsJammed ()
Definition at line 22 of file Crossbow.c.
{ return false; }
Referenced by Weapon::CanFire(), and Weapon::RandomizeFSMState().
IsRepairEnabled()
override bool IsRepairEnabled ()
Definition at line 23 of file Crossbow.c.
{ return true; }
OnEntry()
enum XBStableStateID OnEntry (WeaponEventBase e)
Definition at line 1 of file Crossbow.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { Uncocked Empty UE"); m_weapon.SetCharged(false); super.OnEntry(e); }
OnExit()
override void OnExit (WeaponEventBase e)
Definition at line 18 of file Crossbow.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } Uncocked Empty UE"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
Variable Documentation
CockedEmpty
CockedEmpty = 2
Definition at line 20 of file Crossbow.c.
Loaded
Loaded = 3
Definition at line 21 of file Crossbow.c.
OnEntry
class XBCockedEmpty extends WeaponStableState OnEntry
UncockedEmpty
UncockedEmpty = 1
Definition at line 19 of file Crossbow.c.
UNKNOWN
@ UNKNOWN = 0
Definition at line 18 of file Crossbow.c.