DayZ: CCTWaterSurface Class Reference
CCTWaterSurface Class Reference
Protected Member Functions
void CCTWaterSurface (float maximal_target_distance=UAMaxDistances.DEFAULT, string surfaceType="")
override bool Can (PlayerBase player, ActionTarget target)
override bool CanContinue (PlayerBase player, ActionTarget target)
Protected Attributes
const int HEIGHT_DIFF_LIMIT_METERS = 1.0
float m_MaximalActionDistanceSq
string m_SurfaceType
ref array< string > m_AllowedSurfaceList
DEPRECATED.
Detailed Description
Definition at line 1 of file CCTWaterSurface.c.
Constructor & Destructor Documentation
CCTWaterSurface()
void CCTWaterSurface::CCTWaterSurface (float maximal_target_distance = UAMaxDistances.DEFAULT, string surfaceType = "") inline protected
Definition at line 9 of file CCTWaterSurface.c.
  {
    m_MaximalActionDistanceSq = maximal_target_distance * maximal_target_distance;
    m_SurfaceType = surfaceType;
    m_AllowedSurfaceList = new array<string>();
    surfaceType.Split("|", m_AllowedSurfaceList);
  }
References m_AllowedSurfaceList, m_MaximalActionDistanceSq, and m_SurfaceType.
Member Function Documentation
Can()
override bool CCTWaterSurface::Can (PlayerBase player, ActionTarget target) inline protected
use hit position from ActionTarget otherwise player's position
special handling for sea
Definition at line 18 of file CCTWaterSurface.c.
  {
    if (!target || (target && target.GetObject()))
      return false;
    vector hitPosition = target.GetCursorHitPos();
    if (hitPosition == vector.Zero)
      hitPosition = player.GetPosition();
    string surfaceType;
    float waterLevel = player.GetCurrentWaterLevel();
    g_Game.SurfaceGetType3D(hitPosition[0], hitPosition[1] + waterLevel, hitPosition[2], surfaceType);
    if (waterLevel > 0.0)
      return Surface.AllowedWaterSurface(hitPosition[1] + waterLevel, surfaceType, m_AllowedSurfaceList);
    float surfaceHeight = g_Game.SurfaceY(hitPosition[0], hitPosition[2]);
    if (!surfaceType)
      surfaceHeight = hitPosition[1];
    float heightDiff = Math.AbsFloat(hitPosition[1] - surfaceHeight);
    if (surfaceType != "" && heightDiff > HEIGHT_DIFF_LIMIT_METERS)
      return false;
    float distSq = vector.DistanceSq(player.GetPosition(), hitPosition);
    if (distSq > m_MaximalActionDistanceSq)
      return false;
    return Surface.AllowedWaterSurface(hitPosition[1], surfaceType, m_AllowedSurfaceList);
  }
References Math::AbsFloat(), Surface::AllowedWaterSurface(), vector::DistanceSq(), g_Game, HEIGHT_DIFF_LIMIT_METERS, m_AllowedSurfaceList, m_MaximalActionDistanceSq, and vector::Zero.
CanContinue()
override bool CCTWaterSurface::CanContinue (PlayerBase player, ActionTarget target) inline protected
Definition at line 51 of file CCTWaterSurface.c.
  {
    return true;
  }
Member Data Documentation
HEIGHT_DIFF_LIMIT_METERS
const int CCTWaterSurface::HEIGHT_DIFF_LIMIT_METERS = 1.0 protected
Definition at line 3 of file CCTWaterSurface.c.
Referenced by Can().
m_AllowedSurfaceList
ref array<string> CCTWaterSurface::m_AllowedSurfaceList protected
DEPRECATED.
Definition at line 7 of file CCTWaterSurface.c.
Referenced by Can(), and CCTWaterSurface().
m_MaximalActionDistanceSq
float CCTWaterSurface::m_MaximalActionDistanceSq protected
Definition at line 5 of file CCTWaterSurface.c.
Referenced by Can(), and CCTWaterSurface().
m_SurfaceType
string CCTWaterSurface::m_SurfaceType protected
Definition at line 6 of file CCTWaterSurface.c.
Referenced by CCTWaterSurface().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/TargetConditionsComponents/CCTWaterSurface.c