DayZ: RemotelyActivatedItemBehaviour Class Reference
RemotelyActivatedItemBehaviour Class Reference
Protected Member Functions
void RemotelyActivatedItemBehaviour (notnull EntityAI pParent)
void ~RemotelyActivatedItemBehaviour ()
void SetTrigger ()
void OnVariableSynchronized ()
void OnStoreSave (ParamsWriteContext ctx)
bool OnStoreLoad (ParamsReadContext ctx, int version)
void OnAfterLoad ()
void SetPersistentPairID (int id)
void Pair ()
void Pair (notnull EntityAI device)
void Unpair ()
EntityAI GetPairDevice ()
bool IsPaired ()
void SetPairDeviceNetIds (notnull EntityAI device)
int GetPairDeviceNetIdLow ()
int GetPairDeviceNetIdHigh ()
Static Protected Member Functions
static int GeneratePersistentID ()
Protected Attributes
EntityAI m_Parent
bool m_IsTrigger
EntityAI m_PairDevice
int m_PairDeviceNetIdLow
int m_PairDeviceNetIdHigh
int m_PersistentPairID = int.MIN
Static Protected Attributes
static ref map< int, EntityAI > m_RemoteReceivers = new map<int, EntityAI>()
Detailed Description
Definition at line 1 of file RemotelyActivatedItemBehaviour.c.
Constructor & Destructor Documentation
RemotelyActivatedItemBehaviour()
void RemotelyActivatedItemBehaviour::RemotelyActivatedItemBehaviour (notnull EntityAI pParent) inline protected
Definition at line 12 of file RemotelyActivatedItemBehaviour.c.
  {
    m_Parent = pParent;
    m_PairDeviceNetIdLow = -1;
    m_PairDeviceNetIdHigh = -1;
  }
References m_PairDeviceNetIdHigh, m_PairDeviceNetIdLow, and m_Parent.
~RemotelyActivatedItemBehaviour()
void RemotelyActivatedItemBehaviour::~RemotelyActivatedItemBehaviour () inline protected
Definition at line 20 of file RemotelyActivatedItemBehaviour.c.
  {
    if (m_Parent)
      Unpair();
  }
References m_Parent, and Unpair().
Member Function Documentation
GeneratePersistentID()
static int RemotelyActivatedItemBehaviour::GeneratePersistentID () inline static protected
Definition at line 81 of file RemotelyActivatedItemBehaviour.c.
  {
    int randomID = Math.RandomInt(0, int.MAX);
    if (m_RemoteReceivers.Contains(randomID))
    {
      //it's very unlikely to have a collision here, but lets handle it anyway
      return GeneratePersistentID();
    }
    else
      return randomID;
  }
References GeneratePersistentID(), m_RemoteReceivers, MAX, and Math::RandomInt().
Referenced by GeneratePersistentID(), and InventoryItem::PairWithDevice().
GetPairDevice()
EntityAI RemotelyActivatedItemBehaviour::GetPairDevice () inline protected
Definition at line 141 of file RemotelyActivatedItemBehaviour.c.
  {
    return m_PairDevice;
  }
References m_PairDevice.
GetPairDeviceNetIdHigh()
int RemotelyActivatedItemBehaviour::GetPairDeviceNetIdHigh () inline protected
Definition at line 161 of file RemotelyActivatedItemBehaviour.c.
  {
    return m_PairDeviceNetIdHigh;
  }
References m_PairDeviceNetIdHigh.
Referenced by Pair().
GetPairDeviceNetIdLow()
int RemotelyActivatedItemBehaviour::GetPairDeviceNetIdLow () inline protected
Definition at line 156 of file RemotelyActivatedItemBehaviour.c.
  {
    return m_PairDeviceNetIdLow;
  }
References m_PairDeviceNetIdLow.
Referenced by Pair().
IsPaired()
bool RemotelyActivatedItemBehaviour::IsPaired () inline protected
Definition at line 146 of file RemotelyActivatedItemBehaviour.c.
  {
    return m_PairDevice != null;
  }
References m_PairDevice.
OnAfterLoad()
void RemotelyActivatedItemBehaviour::OnAfterLoad () inline protected
Definition at line 63 of file RemotelyActivatedItemBehaviour.c.
  {
    if (m_IsTrigger && m_PersistentPairID != int.MIN && !m_PairDevice)
    {
      EntityAI receiver = m_RemoteReceivers.Get(m_PersistentPairID);
      if (receiver)
      {
        //if both the receiver and trigger are somewhere in the world outside of the player inventory, there is no guarantee
        //that the pairing is going to be succesful during the 'OnStoreLoad' event as that requires the receiver to already be loaded when the trigger is being loaded
        //therefore, it's necessary to also perform pairing in this event, which happens at the end of the storage loading process
        //do note that this event is not called when the entity is being loaded as part of the player inventory, therefore, we need to pair both in 'OnStoreLoad' and here to handle both situations
        //(when the trigger is in the player's inventory, it always loads correctly after the receiver, which is always in the world)
        Pair(receiver);
      }
    }
  }
References m_IsTrigger, m_PairDevice, m_PersistentPairID, m_RemoteReceivers, MIN, and Pair().
OnStoreLoad()
bool RemotelyActivatedItemBehaviour::OnStoreLoad (ParamsReadContext ctx, int version) inline protected
Definition at line 41 of file RemotelyActivatedItemBehaviour.c.
  {
    if (!ctx.Read(m_PersistentPairID))
      return false;
    if (m_PersistentPairID == int.MIN)//default value, no point in going further
      return true;
    if (m_IsTrigger)//trigger
    {
      EntityAI receiver = m_RemoteReceivers.Get(m_PersistentPairID);
      if (receiver)
        Pair(receiver);
    }
    else // remotely controlled device
    {
      m_RemoteReceivers.Insert(m_PersistentPairID, m_Parent);//receivers will register themselves upon being loaded from the storage
    }
    return true;
  }
References m_IsTrigger, m_Parent, m_PersistentPairID, m_RemoteReceivers, MIN, and Pair().
OnStoreSave()
void RemotelyActivatedItemBehaviour::OnStoreSave (ParamsWriteContext ctx) inline protected
Definition at line 36 of file RemotelyActivatedItemBehaviour.c.
  {
    ctx.Write(m_PersistentPairID);
  }
References m_PersistentPairID.
OnVariableSynchronized()
void RemotelyActivatedItemBehaviour::OnVariableSynchronized () inline protected
Definition at line 31 of file RemotelyActivatedItemBehaviour.c.
  {
    Pair();
  }
References Pair().
Pair() [1/2]
void RemotelyActivatedItemBehaviour::Pair () inline protected
Definition at line 101 of file RemotelyActivatedItemBehaviour.c.
  {
    EntityAI device = EntityAI.Cast(GetGame().GetObjectByNetworkId(GetPairDeviceNetIdLow(), GetPairDeviceNetIdHigh()));
    if (device)
      Pair(device);
  }
References GetGame(), GetPairDeviceNetIdHigh(), GetPairDeviceNetIdLow(), and Pair().
Referenced by OnAfterLoad(), OnStoreLoad(), OnVariableSynchronized(), and Pair().
Pair() [2/2]
void RemotelyActivatedItemBehaviour::Pair (notnull EntityAI device) inline protected
Definition at line 108 of file RemotelyActivatedItemBehaviour.c.
  {
    m_PairDevice = device;
    SetPairDeviceNetIds(device);
    if (device != m_Parent && (!m_Parent.GetPairDevice() || m_Parent.GetPairDevice() != m_PairDevice))
      m_PairDevice.PairRemote(m_Parent);
    m_PairDevice.SetSynchDirty();
    m_Parent.SetSynchDirty();
  }
References m_PairDevice, m_Parent, and SetPairDeviceNetIds().
SetPairDeviceNetIds()
void RemotelyActivatedItemBehaviour::SetPairDeviceNetIds (notnull EntityAI device) inline protected
Definition at line 151 of file RemotelyActivatedItemBehaviour.c.
  {
    device.GetNetworkID(m_PairDeviceNetIdLow, m_PairDeviceNetIdHigh);
  }
References m_PairDeviceNetIdHigh, and m_PairDeviceNetIdLow.
Referenced by Pair().
SetPersistentPairID()
void RemotelyActivatedItemBehaviour::SetPersistentPairID (int id) inline protected
Definition at line 93 of file RemotelyActivatedItemBehaviour.c.
  {
    m_PersistentPairID = id;
    if (!m_IsTrigger)
      m_RemoteReceivers.Insert(id, m_Parent);
  }
References m_IsTrigger, m_Parent, m_PersistentPairID, and m_RemoteReceivers.
SetTrigger()
void RemotelyActivatedItemBehaviour::SetTrigger () inline protected
Definition at line 26 of file RemotelyActivatedItemBehaviour.c.
  {
    m_IsTrigger = true;
  }
References m_IsTrigger.
Unpair()
void RemotelyActivatedItemBehaviour::Unpair () inline protected
Definition at line 120 of file RemotelyActivatedItemBehaviour.c.
  {
    m_PairDeviceNetIdLow = -1;
    m_PairDeviceNetIdHigh = -1;
    if (m_PairDevice)
    {
      m_PairDevice.SetSynchDirty();
      m_PairDevice = null;
    }
    if (m_PersistentPairID != int.MIN)
    {
      if (m_RemoteReceivers.Contains(m_PersistentPairID))
        m_RemoteReceivers.Remove(m_PersistentPairID);
    }
    m_PersistentPairID = int.MIN;
    m_Parent.SetSynchDirty();
  }
References m_PairDevice, m_PairDeviceNetIdHigh, m_PairDeviceNetIdLow, m_Parent, m_PersistentPairID, m_RemoteReceivers, and MIN.
Referenced by ~RemotelyActivatedItemBehaviour().
Member Data Documentation
m_IsTrigger
bool RemotelyActivatedItemBehaviour::m_IsTrigger protected
Definition at line 4 of file RemotelyActivatedItemBehaviour.c.
Referenced by OnAfterLoad(), OnStoreLoad(), SetPersistentPairID(), and SetTrigger().
m_PairDevice
EntityAI RemotelyActivatedItemBehaviour::m_PairDevice protected
Definition at line 5 of file RemotelyActivatedItemBehaviour.c.
Referenced by GetPairDevice(), IsPaired(), OnAfterLoad(), Pair(), and Unpair().
m_PairDeviceNetIdHigh
int RemotelyActivatedItemBehaviour::m_PairDeviceNetIdHigh protected
Definition at line 7 of file RemotelyActivatedItemBehaviour.c.
Referenced by GetPairDeviceNetIdHigh(), RemotelyActivatedItemBehaviour(), SetPairDeviceNetIds(), and Unpair().
m_PairDeviceNetIdLow
int RemotelyActivatedItemBehaviour::m_PairDeviceNetIdLow protected
Definition at line 6 of file RemotelyActivatedItemBehaviour.c.
Referenced by GetPairDeviceNetIdLow(), RemotelyActivatedItemBehaviour(), SetPairDeviceNetIds(), and Unpair().
m_Parent
EntityAI RemotelyActivatedItemBehaviour::m_Parent protected
Definition at line 3 of file RemotelyActivatedItemBehaviour.c.
Referenced by OnStoreLoad(), Pair(), RemotelyActivatedItemBehaviour(), SetPersistentPairID(), Unpair(), and ~RemotelyActivatedItemBehaviour().
m_PersistentPairID
int RemotelyActivatedItemBehaviour::m_PersistentPairID = int.MIN protected
Definition at line 8 of file RemotelyActivatedItemBehaviour.c.
Referenced by OnAfterLoad(), OnStoreLoad(), OnStoreSave(), SetPersistentPairID(), and Unpair().
m_RemoteReceivers
ref map<int, EntityAI> RemotelyActivatedItemBehaviour::m_RemoteReceivers = new map<int, EntityAI>() static protected
Definition at line 10 of file RemotelyActivatedItemBehaviour.c.
Referenced by GeneratePersistentID(), OnAfterLoad(), OnStoreLoad(), SetPersistentPairID(), and Unpair().
The documentation for this class was generated from the following file:
scripts/3_Game/RemotelyActivatedItemBehaviour.c