DayZ: scripts/3_Game/Noise.c File Reference
Noise.c File Reference
Classes
class NoiseSystem
Functions
class NoiseSystem NoiseParams ()
void NoiseSystem ()
void ~NoiseSystem ()
proto void AddNoise (EntityAI source_entity, NoiseParams noise_params, float external_strenght_multiplier=1.0)
proto void AddNoisePos (EntityAI source_entity, vector pos, NoiseParams noise_params, float external_strenght_multiplier=1.0)
proto void AddNoiseTarget (vector pos, float lifetime, NoiseParams noise_params, float external_strength_multiplier=1.0)
Will make a noise at that position which the AI will "see" for the duration of 'lifetime'.
proto native void Load (string noise_name)
proto native void LoadFromPath (string noise_path)
Function Documentation
AddNoise()
proto void NoiseParams::AddNoise (EntityAI source_entity, NoiseParams noise_params, float external_strenght_multiplier = 1.0) private
Referenced by DayZPlayer::CommandHandler(), DayZPlayer::OnStepEvent(), and DayZPlayer::ProcessWeaponEvent().
AddNoisePos()
proto void NoiseParams::AddNoisePos (EntityAI source_entity, vector pos, NoiseParams noise_params, float external_strenght_multiplier = 1.0) private
AddNoiseTarget()
proto void NoiseParams::AddNoiseTarget (vector pos, float lifetime, NoiseParams noise_params, float external_strength_multiplier = 1.0) private
Will make a noise at that position which the AI will "see" for the duration of 'lifetime'.
Load()
proto native void Load (string noise_name)
LoadFromPath()
proto native void LoadFromPath (string noise_path)
NoiseParams()
class NoiseSystem NoiseParams ()
Definition at line 1 of file Noise.c.
  {
  }
Referenced by DayZPlayer::CommandHandler(), DayZPlayerType(), EEInit(), AlarmClock_ColorBase::Init(), KitchenTimer::Init(), FlareSimulation::OnActivation(), ActionCloseDoors::OnEndServer(), ActionCloseFence::OnEndServer(), ActionOpenDoors::OnEndServer(), ActionOpenFence::OnEndServer(), DayZPlayer::OnStepEvent(), OnWorkStart(), and StartHeating().
NoiseSystem()
void NoiseParams::NoiseSystem () private
Definition at line 16 of file Noise.c.
{
~NoiseSystem()
void NoiseParams::~NoiseSystem () private
Definition at line 17 of file Noise.c.