DayZ: MenuData Class Reference
MenuData Class Reference
Private Member Functions
proto native int GetCharactersCount ()
proto native int GetLastPlayedCharacter ()
proto native Man CreateCharacterPerson (int index)
Return Character person or null if character initialization failed (inventory load, or corrupted data)
proto void GetLastServerAddress (int index, out string address)
proto native int GetLastServerPort (int index)
proto void GetLastServerName (int index, out string address)
proto void RequestSetDefaultCharacterData ()
proto bool RequestGetDefaultCharacterData ()
void OnSetDefaultCharacter (ParamsWriteContext ctx)
Actual DefaultCharacter saving.
bool OnGetDefaultCharacter (ParamsReadContext ctx)
Actual DefaultCharacter loading.
proto void GetCharacterName (int index, out string name)
proto native void SetCharacterName (int index, string newName)
proto native void SaveCharacter (bool localPlayer, bool verified)
proto native void SaveDefaultCharacter (Man character)
proto native void SaveCharactersLocal ()
Saves characters menu data to file.
proto native void LoadCharactersLocal ()
Loads characters menu data from file.
proto native void ClearCharacters ()
MenuDefaultCharacterData GetMenuDefaultCharacterDataInstance ()
Private Member Functions inherited from Managed
void IntroSceneCharacter ()
void ~IntroSceneCharacter ()
bool IsDefaultCharacter ()
void SetToDefaultCharacter ()
void SetCharacterID (int char_id)
int GetCharacterID ()
PlayerBase GetCharacterObj ()
TStringArray GetCharGenderList ()
TStringArray GetCharList (ECharGender gender)
TStringArray GetCharShirtsList ()
TStringArray GetCharPantsList ()
TStringArray GetCharShoesList ()
void SetCharacterGender (ECharGender gender)
bool IsCharacterFemale ()
ECharGender GetCharacterGender ()
vector GetPosition ()
int GetNextCharacterID ()
int GetPrevCharacterID ()
void CreateNewCharacterRandom ()
void CreateNewCharacterById (int character_id)
void CreateNewCharacterByName (string character_name, bool randomize_equip=true)
void CreateDefaultCharacter ()
void GetLastPlayedServer (int characterID, out string address, out string name, out int port)
void CreateNewCharacter ()
void LoadCharacterData (vector char_pos, vector char_rot, bool default_char=false)
Generates random equip for the new IntroSceneCharacter, whatever is defined in 'cfgCharacterCreation'.
void CharacterUnload ()
void CharacterLoad (int character_id, vector char_pos, vector char_rot)
void SetupPlayerName (bool new_name)
void SetAttachment (string type, int slot)
string GetCharacterNameById (int char_id)
string GetCharacterName ()
void SaveCharName (string name)
void SaveDefaultCharacter ()
void TransferValues (PlayerBase player)
void Init ()
void OnScheduledTick (float deltatime)
void CheckValues ()
float GetBlood ()
float GetHealth ()
void CheckHealth ()
void CheckBlood ()
void SendInitValues ()
Sends values on object creation.
void SendValue (int value_type, float value)
void ReceiveValue (int value_type, float value)
void OnRPC (ParamsReadContext ctx)
void ShowDebugValues (bool show)
void BleedingIndicator (int source_ID, int severity, GameplayEffectsDataBleeding parent)
void InitIndicator (vector position)
void StopIndicator (bool instant=false)
void StartRunningDrops ()
bool IsRunningDrops ()
Are any drops currently being animated?
void TrySpawnNextDrop ()
void ResetSequence ()
void ResetIndicator ()
void Update (float timeSlice)
bool GetEndNow ()
int GetSeverity ()
void GameplayEffectsData (array< ref Widget > input, int type, int user_override=-1)
void Init (array< ref Widget > input, int type, Widget layout_root, int user_override=-1)
array< ref Widget > GetWidgetSet ()
int GetWidgetSetType ()
int GetWidgetSetID ()
bool HasDefinedHandle ()
Returns 'true' if this class contains update info.
bool DataInitialized ()
void UpdateVisibility (bool state)
void RegisterData (Param p)
void Update (float timeSlice=0, Param p=null, int handle=-1)
void ForceStop ()
Additional Inherited Members
Private Attributes inherited from Managed
int m_CharacterId
string m_CharacterType
MenuData m_CharacterDta
PlayerBase m_CharacterObj
vector m_CharacterPos
vector m_CharacterRot
ref TStringArray m_CharGenderList = new TStringArray
ref TStringArray m_CharShirtList = new TStringArray
ref TStringArray m_CharPantsList = new TStringArray
ref TStringArray m_CharShoesList = new TStringArray
ref map< ECharGender, ref array< string > > m_Characters = new map<ECharGender, ref array<string>>
ECharGender m_CharGender
bool m_InitialSyncSent
bool m_Initialized
bool m_Terminating = false
bool m_EndNow = false
bool m_IsRunning = false
int m_DropSpawnsQueued
int m_ActiveDropsCount
int m_Severity
int m_SourceID
GameplayEffectsDataBleeding m_ParentMetaData
array< float > m_DropProbabilityArray
float m_AverageFrequency
float m_SequenceTick
float m_SequenceDuration
float m_TimeElapsedTotal
float m_TimeElapsedSequence
float m_LastDropSpawnTime
float m_DropSpawnMinDelay
float m_DropSpawnMaxDelay
int m_CurrentDropProbabilityStep
int m_DropProbabilityRollsCount
vector m_BasePosition
ref set< ref BleedingIndicatorDropData > m_ActiveDrops
ref set< int > m_CleanupQueue
ref array< ref Widget > m_WidgetArray
int m_Type
int m_WidgetSetIdentifier
Widget m_LayoutRoot
Detailed Description
Definition at line 882 of file gameplay.c.
Member Function Documentation
ClearCharacters()
proto native void MenuData::ClearCharacters () private
Referenced by DayZIntroSceneXbox::~DayZIntroSceneXbox().
CreateCharacterPerson()
proto native Man MenuData::CreateCharacterPerson (int index) private
Return Character person or null if character initialization failed (inventory load, or corrupted data)
Referenced by Managed::CharacterLoad().
GetCharacterName()
proto void MenuData::GetCharacterName (int index, out string name) private
Referenced by DayZIntroSceneXbox::DayZIntroSceneXbox(), Managed::GetCharacterName(), Managed::GetCharacterNameById(), Managed::LoadCharacterData(), and Managed::SetupPlayerName().
GetCharactersCount()
proto native int MenuData::GetCharactersCount () private
Referenced by DayZIntroSceneXbox::DayZIntroSceneXbox(), Managed::GetNextCharacterID(), Managed::GetPrevCharacterID(), and DayZIntroSceneXbox::SaveCharName().
GetLastPlayedCharacter()
proto native int MenuData::GetLastPlayedCharacter () private
Referenced by DayZIntroSceneXbox::DayZIntroSceneXbox(), and Managed::LoadCharacterData().
GetLastServerAddress()
proto void MenuData::GetLastServerAddress (int index, out string address) private
Referenced by Managed::GetLastPlayedServer().
GetLastServerName()
proto void MenuData::GetLastServerName (int index, out string address) private
Referenced by Managed::GetLastPlayedServer().
GetLastServerPort()
proto native int MenuData::GetLastServerPort (int index) private
Referenced by Managed::GetLastPlayedServer().
GetMenuDefaultCharacterDataInstance()
MenuDefaultCharacterData MenuData::GetMenuDefaultCharacterDataInstance () inline private
Definition at line 935 of file gameplay.c.
  {
    return GetGame().GetMenuDefaultCharacterData();
  }
References GetGame().
Referenced by OnGetDefaultCharacter(), and OnSetDefaultCharacter().
LoadCharactersLocal()
proto native void MenuData::LoadCharactersLocal () private
Loads characters menu data from file.
OnGetDefaultCharacter()
bool MenuData::OnGetDefaultCharacter (ParamsReadContext ctx) inline private
Actual DefaultCharacter loading.
Definition at line 910 of file gameplay.c.
  {
    if (!GetMenuDefaultCharacterDataInstance())
    {
      Error("MenuData | OnGetDefaultCharacter - failed to get data class!");
      return false;
    }
    if (GetMenuDefaultCharacterDataInstance().DeserializeCharacterData(ctx))
      return true;
    return false;
  }
References Error(), and GetMenuDefaultCharacterDataInstance().
OnSetDefaultCharacter()
void MenuData::OnSetDefaultCharacter (ParamsWriteContext ctx) inline private
Actual DefaultCharacter saving.
Definition at line 897 of file gameplay.c.
  {
    if (!GetMenuDefaultCharacterDataInstance()/* || GetGame().IsServer()*/)
    {
      Error("MenuData | OnSetDefaultCharacter - failed to get data class!");
      return;
    }
    GetMenuDefaultCharacterDataInstance().SerializeCharacterData(ctx);
    SaveCharactersLocal();
  }
References Error(), GetMenuDefaultCharacterDataInstance(), SaveCharactersLocal(), and MenuDefaultCharacterData::SerializeCharacterData().
RequestGetDefaultCharacterData()
proto bool MenuData::RequestGetDefaultCharacterData () private
RequestSetDefaultCharacterData()
proto void MenuData::RequestSetDefaultCharacterData () private
Referenced by Managed::SaveDefaultCharacter().
SaveCharacter()
proto native void MenuData::SaveCharacter (bool localPlayer, bool verified) private
SaveCharactersLocal()
proto native void MenuData::SaveCharactersLocal () private
Saves characters menu data to file.
Referenced by OnSetDefaultCharacter(), Managed::SaveCharName(), and DayZIntroSceneXbox::SaveCharName().
SaveDefaultCharacter()
proto native void MenuData::SaveDefaultCharacter (Man character) private
SetCharacterName()
proto native void MenuData::SetCharacterName (int index, string newName) private
Referenced by Managed::SaveCharName(), and DayZIntroSceneXbox::SaveCharName().
The documentation for this class was generated from the following file:
scripts/3_Game/gameplay.c