DayZ: LogManager Class Reference
LogManager Class Reference
Static Private Member Functions
static void Init ()
static bool IsLogsEnable ()
static void SetLogsEnabled (bool enable)
static bool IsActionLogEnable ()
static void ActionLogEnable (bool enable)
static bool IsInventoryMoveLogEnable ()
static void InventoryMoveLogEnable (bool enable)
static bool IsInventoryReservationLogEnable ()
static void InventoryReservationLogEnable (bool enable)
static bool IsInventoryHFSMLogEnable ()
static void InventoryHFSMLogEnable (bool enable)
static bool IsSyncLogEnable ()
static void SyncLogEnable (bool enable)
static bool IsQuickbarLogEnable ()
static void QuickbarLogEnable (bool enable)
static bool IsBaseBuildingLogEnable ()
static void BaseBuildingLogEnable (bool enable)
static bool IsSymptomLogEnable ()
static void SymptomLogEnable (bool enable)
static bool IsWeaponLogEnable ()
static void WeaponLogEnable (bool enable)
static bool IsWeatherLogEnabled ()
static bool IsBleedingChancesLogEnable ()
static void BleedingChancesLogEnable (bool enable)
Static Private Attributes
static bool m_DoLogs
static bool m_DoActionDebugLog
static bool m_DoSymptomDebugLog
static bool m_DoInventoryMoveLog
static bool m_DoInventoryReservationLog
static bool m_DoInventoryHFSMLog
static bool m_DoSyncLog
static bool m_DoQuickbarLog
static bool m_DoBaseBuildingLog
static bool m_DoWeaponLog
static bool m_DoWeatherLog
static bool m_DoBleedingChanceLog
Detailed Description
Definition at line 674 of file Debug.c.
Member Function Documentation
ActionLogEnable()
static void LogManager::ActionLogEnable (bool enable) inline static private
Definition at line 724 of file Debug.c.
  {
    m_DoActionDebugLog = enable;
  }
References m_DoActionDebugLog.
BaseBuildingLogEnable()
static void LogManager::BaseBuildingLogEnable (bool enable) inline static private
Definition at line 784 of file Debug.c.
  {
    m_DoBaseBuildingLog = enable;
  }
References m_DoBaseBuildingLog.
BleedingChancesLogEnable()
static void LogManager::BleedingChancesLogEnable (bool enable) inline static private
Definition at line 819 of file Debug.c.
  {
    m_DoBleedingChanceLog = enable;
  }
References m_DoBleedingChanceLog.
Init()
static void LogManager::Init () inline static private
Definition at line 689 of file Debug.c.
  {
#ifdef DIAG_DEVELOPER
    m_DoLogs = true;
#else
    m_DoLogs = IsCLIParam("doLogs");
#endif
    m_DoActionDebugLog = IsCLIParam("doActionLog");
    m_DoSymptomDebugLog = IsCLIParam("doSymptomLog");
    m_DoInventoryMoveLog = IsCLIParam("doInvMoveLog");
    m_DoInventoryReservationLog = IsCLIParam("doInvReservLog");
    m_DoInventoryHFSMLog = IsCLIParam("doInvHFSMLog");
    m_DoSyncLog = IsCLIParam("doSyncLog");
    m_DoQuickbarLog = IsCLIParam("doQuickbarLog");
    m_DoBaseBuildingLog = IsCLIParam("doBaseBuildingLog");
    m_DoWeaponLog = IsCLIParam("doWeaponLog");
    m_DoWeatherLog = IsCLIParam("doWeatherLog");
  }
References IsCLIParam(), m_DoActionDebugLog, m_DoBaseBuildingLog, m_DoInventoryHFSMLog, m_DoInventoryMoveLog, m_DoInventoryReservationLog, m_DoLogs, m_DoQuickbarLog, m_DoSymptomDebugLog, m_DoSyncLog, m_DoWeaponLog, and m_DoWeatherLog.
Referenced by CGame::CGame().
InventoryHFSMLogEnable()
static void LogManager::InventoryHFSMLogEnable (bool enable) inline static private
Definition at line 754 of file Debug.c.
  {
    m_DoInventoryHFSMLog = enable;
  }
References m_DoInventoryHFSMLog.
InventoryMoveLogEnable()
static void LogManager::InventoryMoveLogEnable (bool enable) inline static private
Definition at line 734 of file Debug.c.
  {
    m_DoInventoryMoveLog = enable;
  }
References m_DoInventoryMoveLog.
InventoryReservationLogEnable()
static void LogManager::InventoryReservationLogEnable (bool enable) inline static private
Definition at line 744 of file Debug.c.
  {
    m_DoInventoryReservationLog = enable;
  }
References m_DoInventoryReservationLog.
IsActionLogEnable()
static bool LogManager::IsActionLogEnable () inline static private
Definition at line 719 of file Debug.c.
  {
    return m_DoActionDebugLog;
  }
References m_DoActionDebugLog.
Referenced by ActionManagerClient::ActionStart(), EntityAI::AddAction(), AddAction(), InventoryItem::AddAction(), AnimatedActionBase::Do(), AnimatedActionBase::End(), ActionInput::Init(), ActionInteractBaseCB::InitActionComponent(), ActionBaseCB::Interrupt(), ActionManagerClient::LockInventory(), OnActionEnd(), AnimatedActionBase::OnAnimationEvent(), ActionContinuousBaseCB::OnAnimationEvent(), ActionInteractBaseCB::OnAnimationEvent(), ActionContinuousBase::OnEndAnimationLoop(), ActionBaseCB::OnFinish(), ActionContinuousBase::OnFinishProgress(), ActionContinuousBase::OnStartAnimationLoop(), ActionManagerClient::ProcessActionInputEnd(), ActionManagerClient::ProcessActionRequestEnd(), ActionInput::SetInput(), SetupAction(), Start(), ActionManagerServer::StartDeliveredAction(), ActionManagerClient::UnlockInventory(), and ActionManagerServer::Update().
IsBaseBuildingLogEnable()
static bool LogManager::IsBaseBuildingLogEnable () inline static private
Definition at line 779 of file Debug.c.
  {
    return m_DoBaseBuildingLog;
  }
References m_DoBaseBuildingLog.
Referenced by AddToConstructedParts(), BaseBuildingBase::AfterStoreLoad(), BuildPartServer(), DestroyConnectedParts(), ItemBase::DestroyConstruction(), DestroyMaterialsServer(), DestroyPartServer(), DismantlePartServer(), DropNonUsableMaterialsServer(), HideConstructionPart(), InitBaseState(), ItemBase::InitBaseState(), InitVisuals(), ItemBase::InitVisuals(), LockServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), ItemBase::OnSetSlotLock(), BaseBuildingBase::OnStoreLoad(), BaseBuildingBase::OnStoreSave(), ItemBase::OnVariablesSynchronized(), OnVariablesSynchronized(), RemoveFromConstructedParts(), ConstructionPart::SetBuiltState(), SetLockOnAttachedMaterials(), ItemBase::SetMountedState(), ItemBase::SetPartFromSyncData(), ConstructionPart::SetRequestBuiltState(), ShowConstructionPart(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), Synchronize(), UnlockServer(), ItemBase::UpdateAttachmentPhysics(), UpdateConstructionParts(), UpdatePhysics(), ItemBase::UpdatePhysics(), and UpdateVisuals().
IsBleedingChancesLogEnable()
static bool LogManager::IsBleedingChancesLogEnable () inline static private
Definition at line 814 of file Debug.c.
  {
    return m_DoBleedingChanceLog;
  }
References m_DoBleedingChanceLog.
Referenced by BleedChanceData::CalculateBleedChance(), and BleedingSourcesManagerBase::ProcessHit().
IsInventoryHFSMLogEnable()
static bool LogManager::IsInventoryHFSMLogEnable () inline static private
Definition at line 749 of file Debug.c.
  {
    return m_DoInventoryHFSMLog;
  }
References m_DoInventoryHFSMLog.
Referenced by HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Abort(), HandActionBase::Action(), HandEventBase::CanPerformEvent(), HandEventSwap::CanPerformEvent(), HandEventBase::CanPerformEventEx(), HandEventBase::CheckRequest(), HandEventSwap::CheckRequest(), HandEventBase::CheckRequestSrc(), ReplaceItemWithNewLambdaBase::CopyOldPropertiesToNew(), ReplaceItemWithNewLambdaBase::CreateNetworkObjectInfo(), ReplaceItemWithNewLambdaBase::CreateNewEntity(), ReplaceItemWithNewLambdaBase::DeleteOldEntity(), HumanInventory::DropEntity(), ReplaceItemWithNewLambdaBase::Execute(), Execute(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindAbortDestinationState(), HumanInventory::ForceSwapEntities(), HandGuardBase::GuardCondition(), HandGuardHasItemInEvent::GuardCondition(), HandleHandEvent(), HandleInventory(), HandleTakeToDst(), HumanInventoryWithFSM::Init(), Init(), HumanInventory::LocalDestroyEntity(), HandStateBase::OnAbort(), HumanInventory::OnEntityInHandsCreated(), HumanInventory::OnEntityInHandsDestroyed(), HandStateBase::OnEntry(), HandStartAction::OnEntry(), HandStateBase::OnExit(), OnHandEventForRemote(), OnHandsEnteredStableState(), OnHandsExitedStableState(), OnHandsStateChanged(), ReplaceItemWithNewLambdaBase::OnSuccess(), ReplaceItemWithNewLambdaBase::PrepareLocations(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortEvent(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessAbortEvent(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortTransition(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessAbortTransition(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessEvent(), HumanInventoryWithFSM::ProcessHandAbortEvent(), HumanInventoryWithFSM::ProcessHandEvent(), FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessLocalTransition(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessLocalTransition(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessLocalTransition(), OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessLocalTransition(), HumanInventory::RedirectToHandEvent(), HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl(), HumanInventory::ReplaceItemInHandsWithNewImpl(), SelectAnimationOfForceSwapInHands(), SelectAnimationOfMoveFromHands(), SelectAnimationOfTakeToHands(), OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), HumanInventory::SwapEntities(), SyncHandEventToRemote(), HumanInventory::TakeEntityAsAttachmentEx(), HumanInventory::TakeEntityToCargoEx(), HumanInventory::TakeEntityToInventory(), HumanInventory::TakeToDst(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Terminate(), and HumanInventory::ThrowEntity().
IsInventoryMoveLogEnable()
static bool LogManager::IsInventoryMoveLogEnable () inline static private
Definition at line 729 of file Debug.c.
  {
    return m_DoInventoryMoveLog;
  }
References m_DoInventoryMoveLog.
Referenced by GameInventory::DropEntity(), GameInventory::DropEntityInBounds(), GameInventory::DropEntityWithTransform(), GameInventory::EEInit(), ForceSwapEntities(), HandleForceSwapEntities(), HandleSwapEntities(), HandleTakeToDst(), GameInventory::LocalDestroyEntity(), GameInventory::ReplaceItemWithNew(), StoreInputForRemotes(), SwapEntities(), GameInventory::TakeEntityAsAttachment(), GameInventory::TakeEntityAsAttachmentEx(), GameInventory::TakeEntityAsTargetAttachment(), GameInventory::TakeEntityAsTargetAttachmentEx(), GameInventory::TakeEntityToCargo(), GameInventory::TakeEntityToCargoEx(), GameInventory::TakeEntityToInventory(), GameInventory::TakeEntityToTargetCargo(), GameInventory::TakeEntityToTargetCargoEx(), GameInventory::TakeEntityToTargetInventory(), TakeToDst(), ValidateDestroy(), ValidateHandEvent(), ValidateSwap(), and ValidateSyncMove().
IsInventoryReservationLogEnable()
static bool LogManager::IsInventoryReservationLogEnable () inline static private
Definition at line 739 of file Debug.c.
  {
    return m_DoInventoryReservationLog;
  }
References m_DoInventoryReservationLog.
Referenced by CGame::AddInventoryJunctureEx(), GameInventory::AddInventoryReservationEx(), GameInventory::ClearInventoryReservationEx(), CGame::ClearJunctureEx(), GameInventory::ExtendInventoryReservationEx(), and TryAcquireTwoInventoryJuncturesFromServer().
IsLogsEnable()
static bool LogManager::IsLogsEnable () inline static private
Definition at line 709 of file Debug.c.
  {
    return m_DoLogs;
  }
References m_DoLogs.
Referenced by Debug::LogMessage(), MissionBase::OnInit(), and Debug::ReceivedLogMessageFromServer().
IsQuickbarLogEnable()
static bool LogManager::IsQuickbarLogEnable () inline static private
Definition at line 769 of file Debug.c.
  {
    return m_DoQuickbarLog;
  }
References m_DoQuickbarLog.
IsSymptomLogEnable()
static bool LogManager::IsSymptomLogEnable () inline static private
Definition at line 789 of file Debug.c.
  {
    return m_DoSymptomDebugLog;
  }
References m_DoSymptomDebugLog.
Referenced by SymptomBase::OnGetActivatedClient(), SymptomBase::OnGetActivatedServer(), SymptomBase::OnGetDeactivatedClient(), and SymptomBase::OnGetDeactivatedServer().
IsSyncLogEnable()
static bool LogManager::IsSyncLogEnable () inline static private
Definition at line 759 of file Debug.c.
  {
    return m_DoSyncLog;
  }
References m_DoSyncLog.
Referenced by HandEventBase::CheckRequestSrc(), EntityAI::DropEntityImpl(), EntityAI::ForceSwapEntitiesImpl(), EntityAI::LocalDestroyEntityInHands(), ManBase::NeedInventoryJunctureFromServer(), OnHandleStoredInputUserData(), OnHandleStoredJunctureData(), OnInputUserDataForRemote(), OnInputUserDataProcess(), OnInventoryJunctureFromServer(), ManBase::OnQuickBarSingleUse(), OnServerInventoryCommand(), GameInventory::OnServerInventoryCommandStatic(), DayZPlayerCommandDeathCallback::OnSimulationEnd(), EntityAI::PredictiveMoveItemFromHandsToInventory(), EntityAI::ReplaceItemElsewhereWithNewInHandsImpl(), EntityAI::ReplaceItemInHandsWithNewElsewhereImpl(), EntityAI::ReplaceItemInHandsWithNewImpl(), EntityAI::ReplaceItemWithNewImpl(), InventoryInputUserData::SendInputUserDataDestroy(), InventoryInputUserData::SendInputUserDataHandEvent(), InventoryInputUserData::SendInputUserDataMove(), InventoryInputUserData::SendInputUserDataSwap(), InventoryInputUserData::SendServerHandEventViaInventoryCommand(), SendServerHandEventViaJuncture(), InventoryInputUserData::SendServerMove(), InventoryInputUserData::SendServerSwap(), EntityAI::SwapEntitiesImpl(), EntityAI::TakeEntityAsAttachmentExImpl(), EntityAI::TakeEntityAsAttachmentImpl(), ManBase::TakeEntityAsAttachmentImpl(), EntityAI::TakeEntityToCargoImpl(), ManBase::TakeEntityToCargoImpl(), EntityAI::TakeEntityToHandsImpl(), ManBase::TakeEntityToHandsImpl(), EntityAI::TakeEntityToInventoryImpl(), ManBase::TakeEntityToInventoryImpl(), EntityAI::TakeEntityToTargetAttachmentExImpl(), ManBase::TakeEntityToTargetAttachmentImpl(), EntityAI::TakeEntityToTargetCargoExImpl(), EntityAI::TakeEntityToTargetCargoImpl(), ManBase::TakeEntityToTargetCargoImpl(), EntityAI::TakeEntityToTargetInventoryImpl(), ManBase::TakeEntityToTargetInventoryImpl(), TakeToDst(), EntityAI::TakeToDstImpl(), ManBase::TakeToDstImpl(), TryAcquireInventoryJunctureFromServer(), TryAcquireTwoInventoryJuncturesFromServer(), ValidateHandEvent(), ValidateSwap(), and ValidateSyncMove().
IsWeaponLogEnable()
static bool LogManager::IsWeaponLogEnable () inline static private
Definition at line 799 of file Debug.c.
  {
    return m_DoWeaponLog;
  }
References m_DoWeaponLog.
Referenced by AbortWeaponEvent(), Weapon::CanRemoveFromHands(), ejectBulletAndStoreInMagazine(), WeaponGuardBase::GuardCondition(), GuardCondition(), HandleWeaponEvents(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::LoadAndSetCurrentFSMState(), WeaponStateBase::LoadCurrentFSMState(), Weapon::LoadCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::LoadCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::LoadCurrentUnstableFSMState(), magazinesHaveEqualSizes(), WeaponStateBase::OnAbort(), WeaponChambering_Base::OnAbort(), OnAbort(), WeaponStableState::OnEntry(), WeaponStateJammed::OnEntry(), WeaponStateBase::OnEntry(), WeaponChambering_Base::OnEntry(), WeaponStartAction::OnEntry(), WeaponFire::OnEntry(), OnEntry(), OnEventForRemoteWeapon(), OnExit(), WeaponStableState::OnExit(), WeaponStateJammed::OnExit(), WeaponChambering_Base::OnExit(), WeaponChambering_Cartridge::OnExit(), WeaponStateBase::OnExit(), Weapon::OnStoreLoad(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::OnStoreLoad(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::OnStoreSave(), WeaponStartAction::OnUpdate(), PostWeaponEvent(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessEvent(), pushToChamberFromAttachedMagazine(), pushToChamberFromInnerMagazine(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::RandomizeFSMStateEx(), Weapon::ResetWeaponAnimState(), WeaponStateBase::SaveCurrentFSMState(), Weapon::SaveCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentUnstableFSMState(), SyncAnimState(), Weapon::SyncEventToRemote(), and HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ValidateAndRepairHelper().
IsWeatherLogEnabled()
static bool LogManager::IsWeatherLogEnabled () inline static private
Definition at line 809 of file Debug.c.
  {
    return m_DoWeatherLog;
  }
References m_DoWeatherLog.
Referenced by Debug::WeatherLog().
QuickbarLogEnable()
static void LogManager::QuickbarLogEnable (bool enable) inline static private
Definition at line 774 of file Debug.c.
  {
    m_DoQuickbarLog = enable;
  }
References m_DoQuickbarLog.
SetLogsEnabled()
static void LogManager::SetLogsEnabled (bool enable) inline static private
Definition at line 714 of file Debug.c.
  {
    m_DoLogs = enable;
  }
References m_DoLogs.
Referenced by ScriptConsoleGeneralTab::OnClick().
SymptomLogEnable()
static void LogManager::SymptomLogEnable (bool enable) inline static private
Definition at line 794 of file Debug.c.
  {
    m_DoSymptomDebugLog = enable;
  }
References m_DoSymptomDebugLog.
SyncLogEnable()
static void LogManager::SyncLogEnable (bool enable) inline static private
Definition at line 764 of file Debug.c.
  {
    m_DoSyncLog = enable;
  }
References m_DoSyncLog.
WeaponLogEnable()
static void LogManager::WeaponLogEnable (bool enable) inline static private
Definition at line 804 of file Debug.c.
  {
    m_DoWeaponLog = enable;
  }
References m_DoWeaponLog.
Member Data Documentation
m_DoActionDebugLog
bool LogManager::m_DoActionDebugLog static private
Definition at line 677 of file Debug.c.
Referenced by ActionLogEnable(), Init(), and IsActionLogEnable().
m_DoBaseBuildingLog
bool LogManager::m_DoBaseBuildingLog static private
Definition at line 684 of file Debug.c.
Referenced by BaseBuildingLogEnable(), Init(), and IsBaseBuildingLogEnable().
m_DoBleedingChanceLog
bool LogManager::m_DoBleedingChanceLog static private
Definition at line 687 of file Debug.c.
Referenced by BleedingChancesLogEnable(), and IsBleedingChancesLogEnable().
m_DoInventoryHFSMLog
bool LogManager::m_DoInventoryHFSMLog static private
Definition at line 681 of file Debug.c.
Referenced by Init(), InventoryHFSMLogEnable(), and IsInventoryHFSMLogEnable().
m_DoInventoryMoveLog
bool LogManager::m_DoInventoryMoveLog static private
Definition at line 679 of file Debug.c.
Referenced by Init(), InventoryMoveLogEnable(), and IsInventoryMoveLogEnable().
m_DoInventoryReservationLog
bool LogManager::m_DoInventoryReservationLog static private
Definition at line 680 of file Debug.c.
Referenced by Init(), InventoryReservationLogEnable(), and IsInventoryReservationLogEnable().
m_DoLogs
bool LogManager::m_DoLogs static private
Definition at line 676 of file Debug.c.
Referenced by Init(), IsLogsEnable(), and SetLogsEnabled().
m_DoQuickbarLog
bool LogManager::m_DoQuickbarLog static private
Definition at line 683 of file Debug.c.
Referenced by Init(), IsQuickbarLogEnable(), and QuickbarLogEnable().
m_DoSymptomDebugLog
bool LogManager::m_DoSymptomDebugLog static private
Definition at line 678 of file Debug.c.
Referenced by Init(), IsSymptomLogEnable(), and SymptomLogEnable().
m_DoSyncLog
bool LogManager::m_DoSyncLog static private
Definition at line 682 of file Debug.c.
Referenced by Init(), IsSyncLogEnable(), and SyncLogEnable().
m_DoWeaponLog
bool LogManager::m_DoWeaponLog static private
Definition at line 685 of file Debug.c.
Referenced by Init(), IsWeaponLogEnable(), and WeaponLogEnable().
m_DoWeatherLog
bool LogManager::m_DoWeatherLog static private
Definition at line 686 of file Debug.c.
Referenced by Init(), and IsWeatherLogEnabled().
The documentation for this class was generated from the following file:
scripts/3_Game/tools/Debug.c