DayZ: PPERequester_MenuBase Class Reference
PPERequester_MenuBase Class Reference
Protected Member Functions
void OnStart (Param par=null)
void OnStart (Param par=null)
void OnStart (Param par=null)
void OnStart (Param par=null)
void OnStart (Param par=null)
Protected Attributes
float m_Gauss
Private Member Functions
void SetBlurIntensity (float gauss)
void SetVignetteIntensity (float vignette)
Detailed Description
Definition at line 1 of file PPERControllerDisconnectBlur.c.
Member Function Documentation
OnStart() [1/5]
void PPERequester_MenuBase::OnStart (Param par = null) inline protected
Definition at line 3 of file PPERControllerDisconnectBlur.c.
  {
    super.OnStart();
    SetTargetValueFloat(PostProcessEffectType.GaussFilter, PPEGaussFilter.PARAM_INTENSITY, false, 1.0, PPEGaussFilter.L_0_DISCONNECT, PPOperators.SET); //PPOperators.OVERRIDE?
  }
References PPEGaussFilter::L_0_DISCONNECT, PPEGaussFilter::PARAM_INTENSITY, and SetTargetValueFloat().
OnStart() [2/5]
void PPERequester_MenuBase::OnStart (Param par = null) inline protected
Definition at line 5 of file PPERControlsBlur.c.
  {
    super.OnStart();
    m_Gauss = Param1<float>.Cast(par).param1;
    SetTargetValueFloat(PostProcessEffectType.GaussFilter, PPEGaussFilter.PARAM_INTENSITY, true, m_Gauss, PPEGaussFilter.L_0_CONTROLS, PPOperators.SET);
  }
References PPEGaussFilter::L_0_CONTROLS, PPEGaussFilter::PARAM_INTENSITY, and SetTargetValueFloat().
OnStart() [3/5]
void PPERequester_MenuBase::OnStart (Param par = null) inline protected
Definition at line 3 of file PPERIntroChromAbb.c.
  {
    super.OnStart();
    SetTargetValueFloat(PostProcessEffectType.ChromAber, PPEChromAber.PARAM_POWERX, false, 0.002, PPEChromAber.L_0_INTRO, PPOperators.SET);
    SetTargetValueFloat(PostProcessEffectType.ChromAber, PPEChromAber.PARAM_POWERY, false, 0.002, PPEChromAber.L_1_INTRO, PPOperators.SET);
  }
References PPEChromAber::L_0_INTRO, PPEChromAber::L_1_INTRO, PPEChromAber::PARAM_POWERX, PPEChromAber::PARAM_POWERY, and SetTargetValueFloat().
OnStart() [4/5]
void PPERequester_MenuBase::OnStart (Param par = null) inline protected
Definition at line 5 of file PPERServerBrowser.c.
  {
    super.OnStart();
    m_Gauss = Param1<float>.Cast(par).param1;
    SetTargetValueFloat(PostProcessEffectType.GaussFilter, PPEGaussFilter.PARAM_INTENSITY, true, m_Gauss, PPEGaussFilter.L_0_SERVER_BROWSER, PPOperators.SET);
  }
References PPEGaussFilter::L_0_SERVER_BROWSER, PPEGaussFilter::PARAM_INTENSITY, and SetTargetValueFloat().
OnStart() [5/5]
void PPERequester_MenuBase::OnStart (Param par = null) inline protected
Definition at line 5 of file PPERTutorial.c.
  {
    super.OnStart();
    m_Gauss = Param1<float>.Cast(par).param1;
    SetTargetValueFloat(PostProcessEffectType.GaussFilter, PPEGaussFilter.PARAM_INTENSITY, true, m_Gauss, PPEGaussFilter.L_0_TUTORIALS, PPOperators.SET);
  }
References PPEGaussFilter::L_0_TUTORIALS, PPEGaussFilter::PARAM_INTENSITY, and SetTargetValueFloat().
SetBlurIntensity()
void PPERequester_MenuBase::SetBlurIntensity (float gauss) inline private
Definition at line 3 of file PPERMenuEffects.c.
  {
    SetTargetValueFloat(PostProcessEffectType.GaussFilter, PPEGaussFilter.PARAM_INTENSITY, true, gauss, PPEGaussFilter.L_0_MENU, PPOperators.SET);
  }
References PPEGaussFilter::L_0_MENU, PPEGaussFilter::PARAM_INTENSITY, and SetTargetValueFloat().
SetVignetteIntensity()
void PPERequester_MenuBase::SetVignetteIntensity (float vignette) inline private
Definition at line 8 of file PPERMenuEffects.c.
  {
    SetTargetValueFloat(PostProcessEffectType.Glow, PPEGlow.PARAM_VIGNETTE, false, vignette, PPEGlow.L_25_MENU, PPOperators.SET);
    SetTargetValueColor(PostProcessEffectType.Glow, PPEGlow.PARAM_VIGNETTECOLOR, {0.0, 0.0, 0.0, 0.0}, PPEGlow.L_26_MENU, PPOperators.OVERRIDE);
  }
References PPEGlow::L_25_MENU, PPEGlow::L_26_MENU, PPEGlow::PARAM_VIGNETTE, PPEGlow::PARAM_VIGNETTECOLOR, SetTargetValueColor(), and SetTargetValueFloat().
Member Data Documentation
m_Gauss
float PPERequester_MenuBase::m_Gauss protected
Definition at line 3 of file PPERControlsBlur.c.
The documentation for this class was generated from the following files:
scripts/3_Game/PPEManager/Requesters/PPERControllerDisconnectBlur.c
scripts/3_Game/PPEManager/Requesters/PPERControlsBlur.c
scripts/3_Game/PPEManager/Requesters/PPERServerBrowser.c
scripts/3_Game/PPEManager/Requesters/PPERTutorial.c
scripts/3_Game/PPEManager/Requesters/PPERIntroChromAbb.c
scripts/3_Game/PPEManager/Requesters/PPERMenuEffects.c