DayZ: scripts/4_World/Entities/Firearms/FlareSimulation.c File Reference
FlareSimulation.c File Reference
Classes
class FlareSimulation
class FlareSimulation_Green
Functions
FlareSimulation Managed FlareSimulation_Red ()
void FlareSimulation ()
void OnActivation (Entity flare)
void OnTermination (Entity flare)
void OnFire (Entity flare)
void Simulate (Entity flare)
void CastFlareAINoise (vector position)
void TurnOffDistantLight ()
void ~FlareSimulation ()
FlareSimulation_Green FlareSimulation FlareSimulation_Blue ()
void FlareSimulation_Green ()
Variables
Particle m_ParMainFire
EffectSound m_BurningSound
FlareLight m_FlareLight
static const float MAX_FARLIGHT_DIST = 40
static const float MIN_FARLIGHT_DIST = 5
static ref NoiseParams m_NoisePar
float m_LastNoiseTime = -1
float m_NoiseTimer = 0
const float NOISE_DELAY = 5
m_ScriptedLight
int m_ParticleId
Function Documentation
CastFlareAINoise()
void FlareSimulation_Red::CastFlareAINoise (vector position) protected
Definition at line 194 of file FlareSimulation.c.
FlareSimulation()
void FlareSimulation_Red::FlareSimulation () protected
Definition at line 135 of file FlareSimulation.c.
                           : FlareSimulation
{
  void FlareSimulation_Blue()
  {
References FlareSimulation_Blue().
FlareSimulation_Blue()
FlareSimulation_Green FlareSimulation FlareSimulation_Blue ()
Definition at line 1 of file FlareSimulation.c.
  {
    m_ScriptedLight = FlareLightBlue;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_BLUE;
  }
Referenced by FlareSimulation().
FlareSimulation_Green()
void FlareSimulation_Blue::FlareSimulation_Green ()
Definition at line 139 of file FlareSimulation.c.
  {
    m_ScriptedLight = FlareLightBlue;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_BLUE;
  }
}
References FlareLightBlue(), and m_ScriptedLight.
FlareSimulation_Red()
FlareSimulation Managed FlareSimulation_Red ()
Definition at line 1 of file FlareSimulation.c.
  {
    m_ScriptedLight = FlareLightRed;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_RED;
  }
OnActivation()
void FlareSimulation_Red::OnActivation (Entity flare) protected
Definition at line 141 of file FlareSimulation.c.
OnFire()
void FlareSimulation_Red::OnFire (Entity flare) protected
Definition at line 171 of file FlareSimulation.c.
                      : Managed
{
  protected Particle m_ParMainFire;
  protected EffectSound m_BurningSound;
  protected FlareLight m_FlareLight;
  const static float MAX_FARLIGHT_DIST = 40;
  const static float MIN_FARLIGHT_DIST = 5;
  static ref NoiseParams m_NoisePar; // Contains the noise data ( template and strength )
  float m_LastNoiseTime = -1;
  float m_NoiseTimer = 0;
  const float NOISE_DELAY = 5; // How much time between two consecutive noise pings
  static protected typename m_ScriptedLight;
  static protected int m_ParticleId;
  void FlareSimulation()
  {
    m_ScriptedLight = FlareLight;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE;
  }
  void OnActivation(Entity flare)
  {
    if (!GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      m_FlareLight = FlareLight.Cast(ScriptedLightBase.CreateLight(m_ScriptedLight, Vector(0, 0, 0)));
      if (m_FlareLight)
        m_FlareLight.AttachOnObject(flare);
      if (m_ParMainFire)
        m_ParMainFire.Stop();
      m_ParMainFire = ParticleManager.GetInstance().PlayOnObject(m_ParticleId, flare);
      m_ParMainFire.SetWiggle(7, 0.3);
      flare.PlaySoundSetLoop(m_BurningSound, "roadflareLoop_SoundSet", 0, 0);
    }
    if (GetGame().IsServer())
    {
      // Create and load noise parameters
      m_NoisePar = new NoiseParams();
      m_NoisePar.LoadFromPath("cfgWeapons Flaregun_Base NoiseFlare");
    }
  }
  void OnTermination(Entity flare)
  {
    //MiscGameplayFunctions.GenerateAINoiseAtPosition(flare.GetPosition(), NOISE_DELAY, m_NoisePar);
  }
  void OnFire(Entity flare)
  {
    //m_ParMainFire = ParticleManager.GetInstance().PlayOnObject( ParticleList.FLAREPROJ_FIRE, flare);
    //m_ParMainFire.SetWiggle( 7, 0.3);
  }
  void Simulate(Entity flare)
  {
    DayZPlayer player = GetGame().GetPlayer();
    if (player)
      vector playerPos = player.GetPosition();
    float dist = vector.DistanceSq(flare.GetPosition(), playerPos);
    if ((dist <= MAX_FARLIGHT_DIST * MAX_FARLIGHT_DIST) && (dist > MIN_FARLIGHT_DIST * MIN_FARLIGHT_DIST))
      m_ParMainFire.SetParameter(0, EmitorParam.SIZE, MiscGameplayFunctions.Normalize(dist, MAX_FARLIGHT_DIST * MAX_FARLIGHT_DIST));
    if (dist <= MIN_FARLIGHT_DIST * MIN_FARLIGHT_DIST)
      TurnOffDistantLight();
    //CastFlareAINoise( flare.GetPosition() );
  }
  void CastFlareAINoise(vector position)
  {
    if (m_LastNoiseTime < 0)
      m_LastNoiseTime = GetGame().GetTime() * 0.0033;
    float delta_time = GetGame().GetTime() * 0.0033 - m_LastNoiseTime;
    m_LastNoiseTime = GetGame().GetTime() * 0.0033;
    m_NoiseTimer += delta_time;
    if (m_NoiseTimer >= NOISE_DELAY)
    {
      MiscGameplayFunctions.GenerateAINoiseAtPosition(position, NOISE_DELAY, m_NoisePar);
      m_NoiseTimer = 0;
    }
  }
  void TurnOffDistantLight()
  {
    if (m_ParMainFire)
    {
      m_ParMainFire.SetParameter(0, EmitorParam.LIFETIME, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.LIFETIME_RND, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.REPEAT, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.SIZE, 0);
    }
  }
  void ~FlareSimulation()
  {
    if (m_ParMainFire)
      m_ParMainFire.Stop();
    if (m_BurningSound)
      m_BurningSound.SoundStop();
    if (m_FlareLight)
      m_FlareLight.FadeOut();
  }
}
class FlareSimulation_Red : FlareSimulation
{
  void FlareSimulation_Red()
  {
    m_ScriptedLight = FlareLightRed;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_RED;
  }
}
class FlareSimulation_Green : FlareSimulation
{
  void FlareSimulation_Green()
  {
    m_ScriptedLight = FlareLightGreen;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_GREEN;
  }
}
class FlareSimulation_Blue : FlareSimulation
{
  void FlareSimulation_Blue()
  {
    m_ScriptedLight = FlareLightBlue;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_BLUE;
  }
}
OnTermination()
void FlareSimulation_Red::OnTermination (Entity flare) protected
Definition at line 166 of file FlareSimulation.c.
                      : Managed
{
  protected Particle m_ParMainFire;
  protected EffectSound m_BurningSound;
  protected FlareLight m_FlareLight;
  const static float MAX_FARLIGHT_DIST = 40;
  const static float MIN_FARLIGHT_DIST = 5;
  static ref NoiseParams m_NoisePar; // Contains the noise data ( template and strength )
  float m_LastNoiseTime = -1;
  float m_NoiseTimer = 0;
  const float NOISE_DELAY = 5; // How much time between two consecutive noise pings
  static protected typename m_ScriptedLight;
  static protected int m_ParticleId;
  void FlareSimulation()
  {
    m_ScriptedLight = FlareLight;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE;
  }
  void OnActivation(Entity flare)
  {
    if (!GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      m_FlareLight = FlareLight.Cast(ScriptedLightBase.CreateLight(m_ScriptedLight, Vector(0, 0, 0)));
      if (m_FlareLight)
        m_FlareLight.AttachOnObject(flare);
      if (m_ParMainFire)
        m_ParMainFire.Stop();
      m_ParMainFire = ParticleManager.GetInstance().PlayOnObject(m_ParticleId, flare);
      m_ParMainFire.SetWiggle(7, 0.3);
      flare.PlaySoundSetLoop(m_BurningSound, "roadflareLoop_SoundSet", 0, 0);
    }
    if (GetGame().IsServer())
    {
      // Create and load noise parameters
      m_NoisePar = new NoiseParams();
      m_NoisePar.LoadFromPath("cfgWeapons Flaregun_Base NoiseFlare");
    }
  }
  void OnTermination(Entity flare)
  {
    //MiscGameplayFunctions.GenerateAINoiseAtPosition(flare.GetPosition(), NOISE_DELAY, m_NoisePar);
  }
  void OnFire(Entity flare)
  {
    //m_ParMainFire = ParticleManager.GetInstance().PlayOnObject( ParticleList.FLAREPROJ_FIRE, flare);
    //m_ParMainFire.SetWiggle( 7, 0.3);
  }
  void Simulate(Entity flare)
  {
    DayZPlayer player = GetGame().GetPlayer();
    if (player)
      vector playerPos = player.GetPosition();
    float dist = vector.DistanceSq(flare.GetPosition(), playerPos);
    if ((dist <= MAX_FARLIGHT_DIST * MAX_FARLIGHT_DIST) && (dist > MIN_FARLIGHT_DIST * MIN_FARLIGHT_DIST))
      m_ParMainFire.SetParameter(0, EmitorParam.SIZE, MiscGameplayFunctions.Normalize(dist, MAX_FARLIGHT_DIST * MAX_FARLIGHT_DIST));
    if (dist <= MIN_FARLIGHT_DIST * MIN_FARLIGHT_DIST)
      TurnOffDistantLight();
    //CastFlareAINoise( flare.GetPosition() );
  }
  void CastFlareAINoise(vector position)
  {
    if (m_LastNoiseTime < 0)
      m_LastNoiseTime = GetGame().GetTime() * 0.0033;
    float delta_time = GetGame().GetTime() * 0.0033 - m_LastNoiseTime;
    m_LastNoiseTime = GetGame().GetTime() * 0.0033;
    m_NoiseTimer += delta_time;
    if (m_NoiseTimer >= NOISE_DELAY)
    {
      MiscGameplayFunctions.GenerateAINoiseAtPosition(position, NOISE_DELAY, m_NoisePar);
      m_NoiseTimer = 0;
    }
  }
  void TurnOffDistantLight()
  {
    if (m_ParMainFire)
    {
      m_ParMainFire.SetParameter(0, EmitorParam.LIFETIME, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.LIFETIME_RND, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.REPEAT, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.SIZE, 0);
    }
  }
  void ~FlareSimulation()
  {
    if (m_ParMainFire)
      m_ParMainFire.Stop();
    if (m_BurningSound)
      m_BurningSound.SoundStop();
    if (m_FlareLight)
      m_FlareLight.FadeOut();
  }
}
class FlareSimulation_Red : FlareSimulation
{
  void FlareSimulation_Red()
  {
    m_ScriptedLight = FlareLightRed;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_RED;
  }
}
class FlareSimulation_Green : FlareSimulation
{
  void FlareSimulation_Green()
  {
    m_ScriptedLight = FlareLightGreen;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_GREEN;
  }
}
class FlareSimulation_Blue : FlareSimulation
{
  void FlareSimulation_Blue()
  {
    m_ScriptedLight = FlareLightBlue;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_BLUE;
  }
}
Simulate()
void FlareSimulation_Red::Simulate (Entity flare) protected
Definition at line 177 of file FlareSimulation.c.
                      : Managed
{
  protected Particle m_ParMainFire;
  protected EffectSound m_BurningSound;
  protected FlareLight m_FlareLight;
  const static float MAX_FARLIGHT_DIST = 40;
  const static float MIN_FARLIGHT_DIST = 5;
  static ref NoiseParams m_NoisePar; // Contains the noise data ( template and strength )
  float m_LastNoiseTime = -1;
  float m_NoiseTimer = 0;
  const float NOISE_DELAY = 5; // How much time between two consecutive noise pings
  static protected typename m_ScriptedLight;
  static protected int m_ParticleId;
  void FlareSimulation()
  {
    m_ScriptedLight = FlareLight;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE;
  }
  void OnActivation(Entity flare)
  {
    if (!GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      m_FlareLight = FlareLight.Cast(ScriptedLightBase.CreateLight(m_ScriptedLight, Vector(0, 0, 0)));
      if (m_FlareLight)
        m_FlareLight.AttachOnObject(flare);
      if (m_ParMainFire)
        m_ParMainFire.Stop();
      m_ParMainFire = ParticleManager.GetInstance().PlayOnObject(m_ParticleId, flare);
      m_ParMainFire.SetWiggle(7, 0.3);
      flare.PlaySoundSetLoop(m_BurningSound, "roadflareLoop_SoundSet", 0, 0);
    }
    if (GetGame().IsServer())
    {
      // Create and load noise parameters
      m_NoisePar = new NoiseParams();
      m_NoisePar.LoadFromPath("cfgWeapons Flaregun_Base NoiseFlare");
    }
  }
  void OnTermination(Entity flare)
  {
    //MiscGameplayFunctions.GenerateAINoiseAtPosition(flare.GetPosition(), NOISE_DELAY, m_NoisePar);
  }
  void OnFire(Entity flare)
  {
    //m_ParMainFire = ParticleManager.GetInstance().PlayOnObject( ParticleList.FLAREPROJ_FIRE, flare);
    //m_ParMainFire.SetWiggle( 7, 0.3);
  }
  void Simulate(Entity flare)
  {
    DayZPlayer player = GetGame().GetPlayer();
    if (player)
      vector playerPos = player.GetPosition();
    float dist = vector.DistanceSq(flare.GetPosition(), playerPos);
    if ((dist <= MAX_FARLIGHT_DIST * MAX_FARLIGHT_DIST) && (dist > MIN_FARLIGHT_DIST * MIN_FARLIGHT_DIST))
      m_ParMainFire.SetParameter(0, EmitorParam.SIZE, MiscGameplayFunctions.Normalize(dist, MAX_FARLIGHT_DIST * MAX_FARLIGHT_DIST));
    if (dist <= MIN_FARLIGHT_DIST * MIN_FARLIGHT_DIST)
      TurnOffDistantLight();
    //CastFlareAINoise( flare.GetPosition() );
  }
  void CastFlareAINoise(vector position)
  {
    if (m_LastNoiseTime < 0)
      m_LastNoiseTime = GetGame().GetTime() * 0.0033;
    float delta_time = GetGame().GetTime() * 0.0033 - m_LastNoiseTime;
    m_LastNoiseTime = GetGame().GetTime() * 0.0033;
    m_NoiseTimer += delta_time;
    if (m_NoiseTimer >= NOISE_DELAY)
    {
      MiscGameplayFunctions.GenerateAINoiseAtPosition(position, NOISE_DELAY, m_NoisePar);
      m_NoiseTimer = 0;
    }
  }
  void TurnOffDistantLight()
  {
    if (m_ParMainFire)
    {
      m_ParMainFire.SetParameter(0, EmitorParam.LIFETIME, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.LIFETIME_RND, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.REPEAT, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.SIZE, 0);
    }
  }
  void ~FlareSimulation()
  {
    if (m_ParMainFire)
      m_ParMainFire.Stop();
    if (m_BurningSound)
      m_BurningSound.SoundStop();
    if (m_FlareLight)
      m_FlareLight.FadeOut();
  }
}
class FlareSimulation_Red : FlareSimulation
{
  void FlareSimulation_Red()
  {
    m_ScriptedLight = FlareLightRed;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_RED;
  }
}
class FlareSimulation_Green : FlareSimulation
{
  void FlareSimulation_Green()
  {
    m_ScriptedLight = FlareLightGreen;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_GREEN;
  }
}
class FlareSimulation_Blue : FlareSimulation
{
  void FlareSimulation_Blue()
  {
    m_ScriptedLight = FlareLightBlue;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_BLUE;
  }
}
TurnOffDistantLight()
void FlareSimulation_Red::TurnOffDistantLight () protected
Definition at line 212 of file FlareSimulation.c.
                      : Managed
{
  protected Particle m_ParMainFire;
  protected EffectSound m_BurningSound;
  protected FlareLight m_FlareLight;
  const static float MAX_FARLIGHT_DIST = 40;
  const static float MIN_FARLIGHT_DIST = 5;
  static ref NoiseParams m_NoisePar; // Contains the noise data ( template and strength )
  float m_LastNoiseTime = -1;
  float m_NoiseTimer = 0;
  const float NOISE_DELAY = 5; // How much time between two consecutive noise pings
  static protected typename m_ScriptedLight;
  static protected int m_ParticleId;
  void FlareSimulation()
  {
    m_ScriptedLight = FlareLight;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE;
  }
  void OnActivation(Entity flare)
  {
    if (!GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      m_FlareLight = FlareLight.Cast(ScriptedLightBase.CreateLight(m_ScriptedLight, Vector(0, 0, 0)));
      if (m_FlareLight)
        m_FlareLight.AttachOnObject(flare);
      if (m_ParMainFire)
        m_ParMainFire.Stop();
      m_ParMainFire = ParticleManager.GetInstance().PlayOnObject(m_ParticleId, flare);
      m_ParMainFire.SetWiggle(7, 0.3);
      flare.PlaySoundSetLoop(m_BurningSound, "roadflareLoop_SoundSet", 0, 0);
    }
    if (GetGame().IsServer())
    {
      // Create and load noise parameters
      m_NoisePar = new NoiseParams();
      m_NoisePar.LoadFromPath("cfgWeapons Flaregun_Base NoiseFlare");
    }
  }
  void OnTermination(Entity flare)
  {
    //MiscGameplayFunctions.GenerateAINoiseAtPosition(flare.GetPosition(), NOISE_DELAY, m_NoisePar);
  }
  void OnFire(Entity flare)
  {
    //m_ParMainFire = ParticleManager.GetInstance().PlayOnObject( ParticleList.FLAREPROJ_FIRE, flare);
    //m_ParMainFire.SetWiggle( 7, 0.3);
  }
  void Simulate(Entity flare)
  {
    DayZPlayer player = GetGame().GetPlayer();
    if (player)
      vector playerPos = player.GetPosition();
    float dist = vector.DistanceSq(flare.GetPosition(), playerPos);
    if ((dist <= MAX_FARLIGHT_DIST * MAX_FARLIGHT_DIST) && (dist > MIN_FARLIGHT_DIST * MIN_FARLIGHT_DIST))
      m_ParMainFire.SetParameter(0, EmitorParam.SIZE, MiscGameplayFunctions.Normalize(dist, MAX_FARLIGHT_DIST * MAX_FARLIGHT_DIST));
    if (dist <= MIN_FARLIGHT_DIST * MIN_FARLIGHT_DIST)
      TurnOffDistantLight();
    //CastFlareAINoise( flare.GetPosition() );
  }
  void CastFlareAINoise(vector position)
  {
    if (m_LastNoiseTime < 0)
      m_LastNoiseTime = GetGame().GetTime() * 0.0033;
    float delta_time = GetGame().GetTime() * 0.0033 - m_LastNoiseTime;
    m_LastNoiseTime = GetGame().GetTime() * 0.0033;
    m_NoiseTimer += delta_time;
    if (m_NoiseTimer >= NOISE_DELAY)
    {
      MiscGameplayFunctions.GenerateAINoiseAtPosition(position, NOISE_DELAY, m_NoisePar);
      m_NoiseTimer = 0;
    }
  }
  void TurnOffDistantLight()
  {
    if (m_ParMainFire)
    {
      m_ParMainFire.SetParameter(0, EmitorParam.LIFETIME, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.LIFETIME_RND, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.REPEAT, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.SIZE, 0);
    }
  }
  void ~FlareSimulation()
  {
    if (m_ParMainFire)
      m_ParMainFire.Stop();
    if (m_BurningSound)
      m_BurningSound.SoundStop();
    if (m_FlareLight)
      m_FlareLight.FadeOut();
  }
}
class FlareSimulation_Red : FlareSimulation
{
  void FlareSimulation_Red()
  {
    m_ScriptedLight = FlareLightRed;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_RED;
  }
}
class FlareSimulation_Green : FlareSimulation
{
  void FlareSimulation_Green()
  {
    m_ScriptedLight = FlareLightGreen;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_GREEN;
  }
}
class FlareSimulation_Blue : FlareSimulation
{
  void FlareSimulation_Blue()
  {
    m_ScriptedLight = FlareLightBlue;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_BLUE;
  }
}
~FlareSimulation()
void FlareSimulation_Red::~FlareSimulation () protected
Definition at line 223 of file FlareSimulation.c.
                      : Managed
{
  protected Particle m_ParMainFire;
  protected EffectSound m_BurningSound;
  protected FlareLight m_FlareLight;
  const static float MAX_FARLIGHT_DIST = 40;
  const static float MIN_FARLIGHT_DIST = 5;
  static ref NoiseParams m_NoisePar; // Contains the noise data ( template and strength )
  float m_LastNoiseTime = -1;
  float m_NoiseTimer = 0;
  const float NOISE_DELAY = 5; // How much time between two consecutive noise pings
  static protected typename m_ScriptedLight;
  static protected int m_ParticleId;
  void FlareSimulation()
  {
    m_ScriptedLight = FlareLight;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE;
  }
  void OnActivation(Entity flare)
  {
    if (!GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      m_FlareLight = FlareLight.Cast(ScriptedLightBase.CreateLight(m_ScriptedLight, Vector(0, 0, 0)));
      if (m_FlareLight)
        m_FlareLight.AttachOnObject(flare);
      if (m_ParMainFire)
        m_ParMainFire.Stop();
      m_ParMainFire = ParticleManager.GetInstance().PlayOnObject(m_ParticleId, flare);
      m_ParMainFire.SetWiggle(7, 0.3);
      flare.PlaySoundSetLoop(m_BurningSound, "roadflareLoop_SoundSet", 0, 0);
    }
    if (GetGame().IsServer())
    {
      // Create and load noise parameters
      m_NoisePar = new NoiseParams();
      m_NoisePar.LoadFromPath("cfgWeapons Flaregun_Base NoiseFlare");
    }
  }
  void OnTermination(Entity flare)
  {
    //MiscGameplayFunctions.GenerateAINoiseAtPosition(flare.GetPosition(), NOISE_DELAY, m_NoisePar);
  }
  void OnFire(Entity flare)
  {
    //m_ParMainFire = ParticleManager.GetInstance().PlayOnObject( ParticleList.FLAREPROJ_FIRE, flare);
    //m_ParMainFire.SetWiggle( 7, 0.3);
  }
  void Simulate(Entity flare)
  {
    DayZPlayer player = GetGame().GetPlayer();
    if (player)
      vector playerPos = player.GetPosition();
    float dist = vector.DistanceSq(flare.GetPosition(), playerPos);
    if ((dist <= MAX_FARLIGHT_DIST * MAX_FARLIGHT_DIST) && (dist > MIN_FARLIGHT_DIST * MIN_FARLIGHT_DIST))
      m_ParMainFire.SetParameter(0, EmitorParam.SIZE, MiscGameplayFunctions.Normalize(dist, MAX_FARLIGHT_DIST * MAX_FARLIGHT_DIST));
    if (dist <= MIN_FARLIGHT_DIST * MIN_FARLIGHT_DIST)
      TurnOffDistantLight();
    //CastFlareAINoise( flare.GetPosition() );
  }
  void CastFlareAINoise(vector position)
  {
    if (m_LastNoiseTime < 0)
      m_LastNoiseTime = GetGame().GetTime() * 0.0033;
    float delta_time = GetGame().GetTime() * 0.0033 - m_LastNoiseTime;
    m_LastNoiseTime = GetGame().GetTime() * 0.0033;
    m_NoiseTimer += delta_time;
    if (m_NoiseTimer >= NOISE_DELAY)
    {
      MiscGameplayFunctions.GenerateAINoiseAtPosition(position, NOISE_DELAY, m_NoisePar);
      m_NoiseTimer = 0;
    }
  }
  void TurnOffDistantLight()
  {
    if (m_ParMainFire)
    {
      m_ParMainFire.SetParameter(0, EmitorParam.LIFETIME, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.LIFETIME_RND, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.REPEAT, 0);
      m_ParMainFire.SetParameter(0, EmitorParam.SIZE, 0);
    }
  }
  void ~FlareSimulation()
  {
    if (m_ParMainFire)
      m_ParMainFire.Stop();
    if (m_BurningSound)
      m_BurningSound.SoundStop();
    if (m_FlareLight)
      m_FlareLight.FadeOut();
  }
}
class FlareSimulation_Red : FlareSimulation
{
  void FlareSimulation_Red()
  {
    m_ScriptedLight = FlareLightRed;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_RED;
  }
}
class FlareSimulation_Green : FlareSimulation
{
  void FlareSimulation_Green()
  {
    m_ScriptedLight = FlareLightGreen;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_GREEN;
  }
}
class FlareSimulation_Blue : FlareSimulation
{
  void FlareSimulation_Blue()
  {
    m_ScriptedLight = FlareLightBlue;
    m_ParticleId = ParticleList.FLAREPROJ_ACTIVATE_BLUE;
  }
}
Variable Documentation
m_BurningSound
EffectSound m_BurningSound protected
Definition at line 122 of file FlareSimulation.c.
m_FlareLight
FlareLight m_FlareLight protected
Definition at line 123 of file FlareSimulation.c.
m_LastNoiseTime
float m_LastNoiseTime = -1 protected
Definition at line 128 of file FlareSimulation.c.
m_NoisePar
ref NoiseParams m_NoisePar static protected
Definition at line 127 of file FlareSimulation.c.
m_NoiseTimer
float m_NoiseTimer = 0 protected
Definition at line 129 of file FlareSimulation.c.
m_ParMainFire
Particle m_ParMainFire protected
Definition at line 121 of file FlareSimulation.c.
m_ParticleId
int m_ParticleId static protected
Definition at line 133 of file FlareSimulation.c.
m_ScriptedLight
m_ScriptedLight static protected
Definition at line 132 of file FlareSimulation.c.
Referenced by FlareSimulation_Green().
MAX_FARLIGHT_DIST
const float MAX_FARLIGHT_DIST = 40 static protected
Definition at line 124 of file FlareSimulation.c.
MIN_FARLIGHT_DIST
const float MIN_FARLIGHT_DIST = 5 static protected
Definition at line 125 of file FlareSimulation.c.
NOISE_DELAY
const float NOISE_DELAY = 5 protected
Definition at line 130 of file FlareSimulation.c.