DayZ: SymptomManager Class Reference
SymptomManager Class Reference
Private Member Functions
void Init ()
int GetStorageVersion ()
void AutoactivateSymptoms ()
void SymptomManager (PlayerBase player)
void OnPlayerKilled ()
SymptomBase GetSymptomByUID (int SYMPTOM_uid)
void ~SymptomManager ()
PlayerBase GetPlayer ()
void RegisterSymptom (SymptomBase Symptom)
void OnAnimationFinished (eAnimFinishType type=eAnimFinishType.SUCCESS)
void OnAnimationStarted ()
int CreateUniqueID ()
bool IsUIDUsed (int uid)
string GetSymptomName (int symptom_id)
SmptAnimMetaBase SpawnAnimMetaObject (int symptom_id)
void RequestSymptomExit (int SYMPTOM_uid)
Exits a specific Symptom with a given UID.
bool IsSymptomPrimary (int symptom_id)
void OnInputUserDataReceived (ParamsReadContext ctx)
int GetCurrentCommandID ()
void OnTick (float deltatime, int pCurrentCommandID, HumanMovementState movement_state)
void SetAnimation (ParamsReadContext ctx)
void UpdateActiveSymptoms (float deltatime)
void OnSymptomExit (SymptomBase Symptom, int uid)
int GetSymptomMaxCount (int symptom_id)
int GetSymptomCount (int symptom_id)
void IncreaseSymptomCount (int symptom_id)
void DecreaseSymptomCount (int symptom_id)
SymptomBase SpawnSymptom (int symptom_id, int uid=-1)
void CleanUpPrimaryQueue ()
SymptomBase QueueUpPrimarySymptom (int symptom_id, int uid=-1)
void QueueUpSecondarySymptom (int symptom_id, int uid=-1)
SymptomBase QueueUpSecondarySymptomEx (int symptom_id, int uid=-1)
void RemoveSecondarySymptom (int symptom_id)
Removes a single Symptom.
SymptomBase GetCurrentPrimaryActiveSymptom ()
int FindFirstAvailableSymptomIndex ()
int ComparePriority (int prio1, int prio2)
int GetSymptomPriority (int symptom_id)
void OnRPC (int rpc_type, ParamsReadContext ctx)
void OnStoreSave (ParamsWriteContext ctx)
bool OnStoreLoad (ParamsReadContext ctx, int version)
Private Attributes
PlayerBase m_Player
ref map< int, ref SymptomBase > m_AvailableSymptoms
ref map< int, int > m_ActiveSymptomTypes
ref array< ref SymptomBase > m_SymptomQueuePrimary
ref array< ref SymptomBase > m_SymptomQueueSecondary
ref map< int, SymptomBase > m_SymptomsUIDs
ref array< ref Param > m_SymptomQueueServerDbg
ref array< ref Param > m_SymptomQueueServerDbgPrimary
ref array< ref Param > m_SymptomQueueServerDbgSecondary
ref Timer m_Timer
int m_ActiveSymptomIndexPrimary = -1
int m_CurrentCommandID
const int STORAGE_VERSION = 121
bool m_ShowDebug = false
bool m_ShowDebug2 = false
ref SmptAnimMetaBase m_AnimMeta
Detailed Description
Definition at line 42 of file StateManager.c.
Constructor & Destructor Documentation
SymptomManager()
void SymptomManager::SymptomManager (PlayerBase player) inline private
Definition at line 101 of file StateManager.c.
  {
    m_ActiveSymptomTypes = new map<int, int>;
    m_SymptomsUIDs = new map<int, SymptomBase >;
    m_SymptomQueuePrimary = new array<ref SymptomBase>;
    m_SymptomQueueSecondary = new array<ref SymptomBase>;
    m_SymptomQueueServerDbg = new array<ref Param>;
    m_SymptomQueueServerDbgPrimary = new array<ref Param>;
    m_SymptomQueueServerDbgSecondary = new array<ref Param>;
    m_AvailableSymptoms = new map<int, ref SymptomBase>;
    m_Player = player;
    Init();
    AutoactivateSymptoms();
  }
References AutoactivateSymptoms(), Init(), m_ActiveSymptomTypes, m_AvailableSymptoms, m_Player, m_SymptomQueuePrimary, m_SymptomQueueSecondary, m_SymptomQueueServerDbg, m_SymptomQueueServerDbgPrimary, m_SymptomQueueServerDbgSecondary, and m_SymptomsUIDs.
~SymptomManager()
void SymptomManager::~SymptomManager () inline private
Definition at line 133 of file StateManager.c.
  {
  }
Member Function Documentation
AutoactivateSymptoms()
void SymptomManager::AutoactivateSymptoms () inline private
Definition at line 93 of file StateManager.c.
  {
    if (GetGame().IsClient())
      return;
    QueueUpSecondarySymptom(SymptomIDs.SYMPTOM_BLOODLOSS);
  }
References GetGame(), and QueueUpSecondarySymptom().
Referenced by SymptomManager().
CleanUpPrimaryQueue()
void SymptomManager::CleanUpPrimaryQueue () inline private
Definition at line 411 of file StateManager.c.
  {
    for (int i = 0; i < m_SymptomQueuePrimary.Count(); i++)
      m_SymptomQueuePrimary.Get(i).RequestDestroy();
  }
References m_SymptomQueuePrimary.
Referenced by OnRPC().
ComparePriority()
int SymptomManager::ComparePriority (int prio1, int prio2) inline private
Definition at line 507 of file StateManager.c.
  {
    if (prio1 > prio2)
      return 1;
    else if (prio2 > prio1)
      return 2;
    return 0;
  }
Referenced by QueueUpPrimarySymptom().
CreateUniqueID()
int SymptomManager::CreateUniqueID () inline private
Definition at line 169 of file StateManager.c.
  {
    int uid = Math.RandomInt(1, 2147483647);
    if (!IsUIDUsed(uid)) return uid;
    else return CreateUniqueID();
  }
References CreateUniqueID(), IsUIDUsed(), and Math::RandomInt().
Referenced by CreateUniqueID(), and SpawnSymptom().
DecreaseSymptomCount()
void SymptomManager::DecreaseSymptomCount (int symptom_id) inline private
Definition at line 379 of file StateManager.c.
  {
    if (m_ActiveSymptomTypes.Contains(symptom_id))
    {
      if (m_ActiveSymptomTypes.Get(symptom_id) == 1)
        m_ActiveSymptomTypes.Remove(symptom_id);
      else
        m_ActiveSymptomTypes.Set(symptom_id, m_ActiveSymptomTypes.Get(symptom_id) - 1);
    }
  }
References m_ActiveSymptomTypes.
Referenced by OnSymptomExit().
FindFirstAvailableSymptomIndex()
int SymptomManager::FindFirstAvailableSymptomIndex () inline private
Definition at line 497 of file StateManager.c.
  {
    for (int i = 0; i < m_SymptomQueuePrimary.Count(); i++)
    {
      if (m_SymptomQueuePrimary.Get(i).CanActivate())
        return i;
    }
    return -1;
  }
References m_SymptomQueuePrimary.
Referenced by OnTick().
GetCurrentCommandID()
int SymptomManager::GetCurrentCommandID () inline private
Definition at line 208 of file StateManager.c.
  {
    return m_CurrentCommandID;
  }
References m_CurrentCommandID.
GetCurrentPrimaryActiveSymptom()
SymptomBase SymptomManager::GetCurrentPrimaryActiveSymptom () inline private
Definition at line 480 of file StateManager.c.
  {
    if (GetGame().IsServer())
    {
      if (m_ActiveSymptomIndexPrimary >= 0 && m_ActiveSymptomIndexPrimary < m_SymptomQueuePrimary.Count())
      {
        if (m_SymptomQueuePrimary.Get(m_ActiveSymptomIndexPrimary)) return m_SymptomQueuePrimary.Get(m_ActiveSymptomIndexPrimary);
      }
    }
    if (!GetGame().IsDedicatedServer())
    {
      if (m_SymptomQueuePrimary.Count() > 0)
        return m_SymptomQueuePrimary.Get(0);
    }
    return NULL;
  }
References GetGame(), m_ActiveSymptomIndexPrimary, and m_SymptomQueuePrimary.
Referenced by AnimFinished(), OnAnimationStarted(), and UpdateActiveSymptoms().
GetPlayer()
PlayerBase SymptomManager::GetPlayer () inline private
Definition at line 137 of file StateManager.c.
  {
    return m_Player;
  }
References m_Player.
GetStorageVersion()
int SymptomManager::GetStorageVersion () inline private
Definition at line 87 of file StateManager.c.
  {
    return STORAGE_VERSION;
  }
References STORAGE_VERSION.
GetSymptomByUID()
SymptomBase SymptomManager::GetSymptomByUID (int SYMPTOM_uid) inline private
Definition at line 127 of file StateManager.c.
  {
    return m_SymptomsUIDs.Get(SYMPTOM_uid);
  }
References m_SymptomsUIDs.
GetSymptomCount()
int SymptomManager::GetSymptomCount (int symptom_id) inline private
Definition at line 363 of file StateManager.c.
  {
    if (m_ActiveSymptomTypes.Contains(symptom_id))
      return m_ActiveSymptomTypes.Get(symptom_id);
    else
      return -1;
  }
References m_ActiveSymptomTypes.
Referenced by QueueUpPrimarySymptom(), and QueueUpSecondarySymptomEx().
GetSymptomMaxCount()
int SymptomManager::GetSymptomMaxCount (int symptom_id) inline private
Definition at line 357 of file StateManager.c.
  {
    return m_AvailableSymptoms.Get(symptom_id).GetMaxCount();
  }
References m_AvailableSymptoms.
Referenced by QueueUpPrimarySymptom(), and QueueUpSecondarySymptomEx().
GetSymptomName()
string SymptomManager::GetSymptomName (int symptom_id) inline private
Definition at line 181 of file StateManager.c.
  {
    return m_AvailableSymptoms.Get(symptom_id).GetName();
  }
References m_AvailableSymptoms.
GetSymptomPriority()
int SymptomManager::GetSymptomPriority (int symptom_id) inline private
Definition at line 516 of file StateManager.c.
  {
    return m_AvailableSymptoms.Get(symptom_id).GetPriority();
  }
References m_AvailableSymptoms.
Referenced by QueueUpPrimarySymptom().
IncreaseSymptomCount()
void SymptomManager::IncreaseSymptomCount (int symptom_id) inline private
Definition at line 371 of file StateManager.c.
  {
    if (m_ActiveSymptomTypes.Contains(symptom_id))
      m_ActiveSymptomTypes.Set(symptom_id, m_ActiveSymptomTypes.Get(symptom_id) + 1);
    else
      m_ActiveSymptomTypes.Insert(symptom_id, 1);
  }
References m_ActiveSymptomTypes.
Referenced by SpawnSymptom().
Init()
void SymptomManager::Init () inline private
Definition at line 70 of file StateManager.c.
  {
    RegisterSymptom(new CoughSymptom);
    RegisterSymptom(new VomitSymptom);
    RegisterSymptom(new BlindnessSymptom);
    RegisterSymptom(new SneezeSymptom);
    RegisterSymptom(new FeverBlurSymptom);
    RegisterSymptom(new BloodLoss);
    RegisterSymptom(new LaughterSymptom);
    RegisterSymptom(new FreezeSymptom);
    RegisterSymptom(new HotSymptom);
    RegisterSymptom(new PainLightSymptom);
    RegisterSymptom(new PainHeavySymptom);
    RegisterSymptom(new HandShiversSymptom);
    //RegisterSymptom(new BulletHitSymptom);
  }
References RegisterSymptom().
Referenced by SymptomManager().
IsSymptomPrimary()
bool SymptomManager::IsSymptomPrimary (int symptom_id) inline private
Definition at line 199 of file StateManager.c.
  {
    return m_AvailableSymptoms.Get(symptom_id).IsPrimary();
  }
References m_AvailableSymptoms.
Referenced by OnStoreLoad().
IsUIDUsed()
bool SymptomManager::IsUIDUsed (int uid) inline private
Definition at line 176 of file StateManager.c.
  {
    return m_SymptomsUIDs.Contains(uid);
  }
References m_SymptomsUIDs.
Referenced by CreateUniqueID().
OnAnimationFinished()
void SymptomManager::OnAnimationFinished (eAnimFinishType type = eAnimFinishType.SUCCESS) inline private
Definition at line 157 of file StateManager.c.
  {
    if (m_AnimMeta)
      m_AnimMeta.AnimFinished(type);
  }
References m_AnimMeta.
Referenced by OnTick(), PlayRequest(), and Update().
OnAnimationStarted()
void SymptomManager::OnAnimationStarted () inline private
Definition at line 163 of file StateManager.c.
  {
    if (GetCurrentPrimaryActiveSymptom())
      GetCurrentPrimaryActiveSymptom().AnimationStart();
  }
References SymptomBase::AnimationStart(), and GetCurrentPrimaryActiveSymptom().
Referenced by Update().
OnInputUserDataReceived()
void SymptomManager::OnInputUserDataReceived (ParamsReadContext ctx) inline private
Definition at line 204 of file StateManager.c.
  {
  }
OnPlayerKilled()
void SymptomManager::OnPlayerKilled () inline private
Definition at line 116 of file StateManager.c.
  {
    for (int i = 0; i < m_SymptomQueuePrimary.Count(); i++)
      m_SymptomQueuePrimary.Get(i).OnOwnerKilled();
    for (i = 0; i < m_SymptomQueueSecondary.Count(); i++)
    {
      if (m_SymptomQueueSecondary.Get(i)) m_SymptomQueueSecondary.Get(i).OnOwnerKilled();
    }
  }
References m_SymptomQueuePrimary, and m_SymptomQueueSecondary.
OnRPC()
void SymptomManager::OnRPC (int rpc_type, ParamsReadContext ctx) inline private
Definition at line 521 of file StateManager.c.
  {
    ctx.Read(CachedObjectsParams.PARAM2_INT_INT);
    int symptom_id = CachedObjectsParams.PARAM2_INT_INT.param1;
    int uid = CachedObjectsParams.PARAM2_INT_INT.param2;
    bool is_primary = m_AvailableSymptoms.Get(symptom_id).IsPrimary();
    if (rpc_type == ERPCs.RPC_PLAYER_SYMPTOM_ON)
    {
      if (is_primary)
      {
        CleanUpPrimaryQueue();
        QueueUpPrimarySymptom(symptom_id, uid);
      }
      else
        QueueUpSecondarySymptom(symptom_id, uid);
    }
    else if (rpc_type == ERPCs.RPC_PLAYER_SYMPTOM_OFF)
    {
      if (is_primary)
        CleanUpPrimaryQueue();
      else
        RemoveSecondarySymptom(symptom_id);
    }
  }
References CleanUpPrimaryQueue(), m_AvailableSymptoms, CachedObjectsParams::PARAM2_INT_INT, QueueUpPrimarySymptom(), QueueUpSecondarySymptom(), and RemoveSecondarySymptom().
OnStoreLoad()
bool SymptomManager::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 567 of file StateManager.c.
  {
    array<int> m_SaveQueue;
    if (ctx.Read(m_SaveQueue))
    {
      for (int i = 0; i < m_SaveQueue.Count(); i++)
      {
        int id = m_SaveQueue.Get(i);
        if (IsSymptomPrimary(id))
          QueueUpPrimarySymptom(id);
        else
          QueueUpSecondarySymptom(id);
      }
      return true;
    }
    else
      return false;
  }
References IsSymptomPrimary(), QueueUpPrimarySymptom(), and QueueUpSecondarySymptom().
OnStoreSave()
void SymptomManager::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 548 of file StateManager.c.
  {
    array<int> m_SaveQueue = new array<int>;
    for (int i = 0; i < m_SymptomQueuePrimary.Count(); i++)
    {
      if (m_SymptomQueuePrimary.Get(i).IsPersistent())
        m_SaveQueue.Insert(m_SymptomQueuePrimary.Get(i).GetType());
    }
    for (i = 0; i < m_SymptomQueueSecondary.Count(); i++)
    {
      if (m_SymptomQueueSecondary.Get(i).IsPersistent())
        m_SaveQueue.Insert(m_SymptomQueueSecondary.Get(i).GetType());
    }
    ctx.Write(m_SaveQueue);
  }
References m_SymptomQueuePrimary, and m_SymptomQueueSecondary.
OnSymptomExit()
void SymptomManager::OnSymptomExit (SymptomBase Symptom, int uid) inline private
Definition at line 314 of file StateManager.c.
  {
    bool is_primary;
    if (Symptom)
    {
      is_primary = Symptom.IsPrimary();
      DecreaseSymptomCount(Symptom.GetType());
    }
    if (m_SymptomsUIDs.Contains(uid))
      m_SymptomsUIDs.Remove(uid);
    else
      Debug.LogError("Symptom with this UID does not exist", "PlayerSymptoms");
    if (is_primary)
    {
      for (int i = 0; i < m_SymptomQueuePrimary.Count(); i++)
      {
        if (m_SymptomQueuePrimary.Get(i) == Symptom)
        {
          m_SymptomQueuePrimary.RemoveOrdered(i);
          break;
        }
      }
    }
    else
    {
      for (i = 0; i < m_SymptomQueueSecondary.Count(); i++)
      {
        if (m_SymptomQueueSecondary.Get(i) == Symptom)
        {
          m_SymptomQueueSecondary.RemoveOrdered(i);
          break;
        }
      }
    }
    m_ActiveSymptomIndexPrimary = -1;
#ifdef DIAG_DEVELOPER
    if (GetGame()) SendServerDebugToClient();
#endif
  }
References DecreaseSymptomCount(), GetGame(), Debug::LogError(), m_ActiveSymptomIndexPrimary, m_SymptomQueuePrimary, m_SymptomQueueSecondary, and m_SymptomsUIDs.
Referenced by SymptomBase::OnDestructed().
OnTick()
void SymptomManager::OnTick (float deltatime, int pCurrentCommandID, HumanMovementState movement_state) inline private
Definition at line 213 of file StateManager.c.
  {
    // pCurrentCommandID might be the initial value, but the system itself requires
    // current value, so retrieve the current value from player instead
    m_CurrentCommandID = m_Player.GetCurrentCommandID();
    if (m_ActiveSymptomIndexPrimary == -1)
      m_ActiveSymptomIndexPrimary = FindFirstAvailableSymptomIndex();
    UpdateActiveSymptoms(deltatime);
    if (m_AnimMeta)
    {
      if (m_AnimMeta.IsDestroyReqested())
        m_AnimMeta = null;
    }
    if (m_AnimMeta)
    {
      //anim requested
      if (!m_AnimMeta.IsPlaying())
      {
        // not playing yet and not possible to play
        SymptomBase symptom = m_AvailableSymptoms.Get(m_AnimMeta.m_StateType);
        if (symptom && !symptom.CanActivate())
          m_AnimMeta = null;
        else if (m_AnimMeta.PlayRequest() == EAnimPlayState.FAILED)
          OnAnimationFinished(eAnimFinishType.FAILURE);
      }
      else
        m_AnimMeta.Update(movement_state);
    }
#ifdef DIAG_DEVELOPER
#ifndef SERVER //must be here !!!
    if (DiagMenu.GetBool(DiagMenuIDs.MISC_PLAYER_SYMPTOMS_SHOW))
    {
      //DisplayDebug(true);
      array<ref Param> primary_debug = PrepareClientDebug(m_SymptomQueuePrimary);
      array<ref Param> secondary_debug = PrepareClientDebug(m_SymptomQueueSecondary);
      DisplayDebug1("Symptoms Client", 50, primary_debug, secondary_debug);
      DisplayDebug2("Symptoms Server", 300, m_SymptomQueueServerDbgPrimary, m_SymptomQueueServerDbgSecondary);
      ShowAvailableSymptoms();
    }
    else
    {
      CleanDebug1("Symptoms Client", 50);
      CleanDebug2("Symptoms Server", 300);
      CleanAvailableSymptoms();
    }
#endif
#endif
  }
References FindFirstAvailableSymptomIndex(), DiagMenu::GetBool(), m_ActiveSymptomIndexPrimary, m_AnimMeta, m_AvailableSymptoms, m_CurrentCommandID, m_Player, m_SymptomQueuePrimary, m_SymptomQueueSecondary, m_SymptomQueueServerDbgPrimary, m_SymptomQueueServerDbgSecondary, OnAnimationFinished(), and UpdateActiveSymptoms().
QueueUpPrimarySymptom()
SymptomBase SymptomManager::QueueUpPrimarySymptom (int symptom_id, int uid = -1) inline private
Definition at line 418 of file StateManager.c.
  {
    SymptomBase Symptom;
    if ((GetSymptomCount(symptom_id) >= GetSymptomMaxCount(symptom_id)) && GetSymptomMaxCount(symptom_id) != -1)
      return null;
    for (int i = 0; i < m_SymptomQueuePrimary.Count(); i++)
    {
      if (m_SymptomQueuePrimary.Get(i).CanBeInterupted() && ComparePriority(GetSymptomPriority(symptom_id), m_SymptomQueuePrimary.Get(i).GetPriority()) == 1)
      {
        Symptom = SpawnSymptom(symptom_id, uid);
        m_SymptomQueuePrimary.InsertAt(Symptom, i);
        if (m_SymptomQueuePrimary.Count() > MAX_QUEUE_SIZE)
        {
          m_SymptomQueuePrimary.Get(MAX_QUEUE_SIZE).RequestDestroy();// no need to remove from the array, that's done via Symptom callback on destruct
        }
        break;
      }
    }
    if (!Symptom && m_SymptomQueuePrimary.Count() < MAX_QUEUE_SIZE)
    {
      Symptom = SpawnSymptom(symptom_id, uid);
      m_SymptomQueuePrimary.Insert(Symptom);
    }
#ifdef DIAG_DEVELOPER
    SendServerDebugToClient();
#endif
    return Symptom;
  }
References ComparePriority(), GetSymptomCount(), GetSymptomMaxCount(), GetSymptomPriority(), m_SymptomQueuePrimary, MAX_QUEUE_SIZE, and SpawnSymptom().
Referenced by OnRPC(), and OnStoreLoad().
QueueUpSecondarySymptom()
void SymptomManager::QueueUpSecondarySymptom (int symptom_id, int uid = -1) inline private
Definition at line 448 of file StateManager.c.
  {
    QueueUpSecondarySymptomEx(symptom_id, uid);
  }
References QueueUpSecondarySymptomEx().
Referenced by AutoactivateSymptoms(), OnRPC(), and OnStoreLoad().
QueueUpSecondarySymptomEx()
SymptomBase SymptomManager::QueueUpSecondarySymptomEx (int symptom_id, int uid = -1) inline private
Definition at line 453 of file StateManager.c.
  {
    if ((GetSymptomCount(symptom_id) >= GetSymptomMaxCount(symptom_id)) && GetSymptomMaxCount(symptom_id) != -1)
      return null;
    if (m_AvailableSymptoms.Get(symptom_id).IsPrimary())
      return null;
    SymptomBase Symptom = SpawnSymptom(symptom_id, uid);
    m_SymptomQueueSecondary.Insert(Symptom);
    return Symptom;
  }
References GetSymptomCount(), GetSymptomMaxCount(), m_AvailableSymptoms, m_SymptomQueueSecondary, and SpawnSymptom().
Referenced by QueueUpSecondarySymptom().
RegisterSymptom()
void SymptomManager::RegisterSymptom (SymptomBase Symptom) inline private
Definition at line 142 of file StateManager.c.
  {
    Symptom.Init(this, m_Player, 0);
    int id = Symptom.GetType();
    if (m_AvailableSymptoms.Contains(id))
    {
      Error("SymptomBase Symptom already registered !");
      return;
    }
    m_AvailableSymptoms.Insert(id, Symptom);
    //PrintString("inserting id: "+ToString(id));
  }
References Error(), m_AvailableSymptoms, and m_Player.
Referenced by Init().
RemoveSecondarySymptom()
void SymptomManager::RemoveSecondarySymptom (int symptom_id) inline private
Removes a single Symptom.
Definition at line 468 of file StateManager.c.
  {
    for (int i = 0; i < m_SymptomQueueSecondary.Count(); i++)
    {
      if (m_SymptomQueueSecondary.Get(i) && m_SymptomQueueSecondary.Get(i).GetType() == symptom_id)
      {
        m_SymptomQueueSecondary.Get(i).RequestDestroy();
        return;
      }
    }
  }
References m_SymptomQueueSecondary.
Referenced by OnRPC().
RequestSymptomExit()
void SymptomManager::RequestSymptomExit (int SYMPTOM_uid) inline private
Exits a specific Symptom with a given UID.
Definition at line 194 of file StateManager.c.
  {
    if (m_SymptomsUIDs.Get(SYMPTOM_uid)) m_SymptomsUIDs.Get(SYMPTOM_uid).RequestDestroy();
  }
References m_SymptomsUIDs.
SetAnimation()
void SymptomManager::SetAnimation (ParamsReadContext ctx) inline private
Definition at line 268 of file StateManager.c.
  {
    if (m_AnimMeta)
    {
      // animation meta already exists
      // pass
    }
    else
    {
      int state_type;
      if (ctx.Read(state_type))
      {
        m_AnimMeta = SpawnAnimMetaObject(state_type);
        if (m_AnimMeta)
          m_AnimMeta.Init(ctx, this, m_Player);
      }
    }
  }
References m_AnimMeta, m_Player, and SpawnAnimMetaObject().
SpawnAnimMetaObject()
SmptAnimMetaBase SymptomManager::SpawnAnimMetaObject (int symptom_id) inline private
Definition at line 186 of file StateManager.c.
  {
    SmptAnimMetaBase animMeta = m_AvailableSymptoms.Get(symptom_id).SpawnAnimMetaObject();
    animMeta.m_StateType = symptom_id;
    return animMeta;
  }
References m_AvailableSymptoms.
Referenced by SetAnimation().
SpawnSymptom()
SymptomBase SymptomManager::SpawnSymptom (int symptom_id, int uid = -1) inline private
Definition at line 390 of file StateManager.c.
  {
    if (m_AvailableSymptoms.Get(symptom_id))
    {
      SymptomBase Symptom = SymptomBase.Cast(m_AvailableSymptoms.Get(symptom_id).ClassName().ToType().Spawn());
      if (uid == -1)
        uid = CreateUniqueID();
      Symptom.Init(this, m_Player, uid);
      if (m_SymptomsUIDs.Contains(uid))
        Error("Symptoms: Unique ID already exists !");
      m_SymptomsUIDs.Insert(uid, Symptom);
      IncreaseSymptomCount(symptom_id);
      return Symptom;
    }
    if (!Symptom)
      Error("Symptom not registered");
    return NULL;
  }
References CreateUniqueID(), Error(), IncreaseSymptomCount(), m_AvailableSymptoms, m_Player, and m_SymptomsUIDs.
Referenced by QueueUpPrimarySymptom(), and QueueUpSecondarySymptomEx().
UpdateActiveSymptoms()
void SymptomManager::UpdateActiveSymptoms (float deltatime) inline private
Definition at line 287 of file StateManager.c.
  {
    //if( GetGame().IsClient() && !m_Player.IsPlayer() ) return;
    //primary
    if (GetCurrentPrimaryActiveSymptom())
    {
      if (!GetCurrentPrimaryActiveSymptom().IsActivated())
      {
        if (GetCurrentPrimaryActiveSymptom().CanActivate())
          GetCurrentPrimaryActiveSymptom().Activate();
      }
      if (GetCurrentPrimaryActiveSymptom().IsActivated())
        GetCurrentPrimaryActiveSymptom().Update(deltatime);
    }
    //secondary
    for (int i = 0; i < m_SymptomQueueSecondary.Count(); i++)
    {
      if (m_SymptomQueueSecondary.Get(i) && !m_SymptomQueueSecondary.Get(i).IsActivated())
        m_SymptomQueueSecondary.Get(i).Activate();
      else
      {
        if (m_SymptomQueueSecondary.Get(i)) m_SymptomQueueSecondary.Get(i).Update(deltatime);
      }
    }
  }
References SymptomBase::Activate(), GetCurrentPrimaryActiveSymptom(), m_SymptomQueueSecondary, and SymptomBase::Update().
Referenced by OnTick().
Member Data Documentation
m_ActiveSymptomIndexPrimary
int SymptomManager::m_ActiveSymptomIndexPrimary = -1 private
Definition at line 60 of file StateManager.c.
Referenced by GetCurrentPrimaryActiveSymptom(), OnSymptomExit(), and OnTick().
m_ActiveSymptomTypes
ref map<int, int> SymptomManager::m_ActiveSymptomTypes private
Definition at line 46 of file StateManager.c.
Referenced by DecreaseSymptomCount(), GetSymptomCount(), IncreaseSymptomCount(), and SymptomManager().
m_AnimMeta
ref SmptAnimMetaBase SymptomManager::m_AnimMeta private
Definition at line 68 of file StateManager.c.
Referenced by OnAnimationFinished(), OnTick(), and SetAnimation().
m_AvailableSymptoms
ref map<int, ref SymptomBase> SymptomManager::m_AvailableSymptoms private
Definition at line 45 of file StateManager.c.
Referenced by GetSymptomMaxCount(), GetSymptomName(), GetSymptomPriority(), IsSymptomPrimary(), OnRPC(), OnTick(), QueueUpSecondarySymptomEx(), RegisterSymptom(), SpawnAnimMetaObject(), SpawnSymptom(), and SymptomManager().
m_CurrentCommandID
int SymptomManager::m_CurrentCommandID private
Definition at line 61 of file StateManager.c.
Referenced by GetCurrentCommandID(), and OnTick().
m_Player
PlayerBase SymptomManager::m_Player private
Definition at line 44 of file StateManager.c.
Referenced by GetPlayer(), OnTick(), RegisterSymptom(), SetAnimation(), SpawnSymptom(), and SymptomManager().
m_ShowDebug
bool SymptomManager::m_ShowDebug = false private
Definition at line 65 of file StateManager.c.
m_ShowDebug2
bool SymptomManager::m_ShowDebug2 = false private
Definition at line 66 of file StateManager.c.
m_SymptomQueuePrimary
ref array<ref SymptomBase> SymptomManager::m_SymptomQueuePrimary private
Definition at line 48 of file StateManager.c.
Referenced by CleanUpPrimaryQueue(), FindFirstAvailableSymptomIndex(), GetCurrentPrimaryActiveSymptom(), OnPlayerKilled(), OnStoreSave(), OnSymptomExit(), OnTick(), QueueUpPrimarySymptom(), and SymptomManager().
m_SymptomQueueSecondary
ref array<ref SymptomBase> SymptomManager::m_SymptomQueueSecondary private
Definition at line 49 of file StateManager.c.
Referenced by OnPlayerKilled(), OnStoreSave(), OnSymptomExit(), OnTick(), QueueUpSecondarySymptomEx(), RemoveSecondarySymptom(), SymptomManager(), and UpdateActiveSymptoms().
m_SymptomQueueServerDbg
ref array<ref Param> SymptomManager::m_SymptomQueueServerDbg private
Definition at line 54 of file StateManager.c.
Referenced by SymptomManager().
m_SymptomQueueServerDbgPrimary
ref array<ref Param> SymptomManager::m_SymptomQueueServerDbgPrimary private
Definition at line 55 of file StateManager.c.
Referenced by OnTick(), and SymptomManager().
m_SymptomQueueServerDbgSecondary
ref array<ref Param> SymptomManager::m_SymptomQueueServerDbgSecondary private
Definition at line 56 of file StateManager.c.
Referenced by OnTick(), and SymptomManager().
m_SymptomsUIDs
ref map<int, SymptomBase > SymptomManager::m_SymptomsUIDs private
Definition at line 51 of file StateManager.c.
Referenced by GetSymptomByUID(), IsUIDUsed(), OnSymptomExit(), RequestSymptomExit(), SpawnSymptom(), and SymptomManager().
m_Timer
ref Timer SymptomManager::m_Timer private
Definition at line 58 of file StateManager.c.
STORAGE_VERSION
const int SymptomManager::STORAGE_VERSION = 121 private
Definition at line 63 of file StateManager.c.
Referenced by GetStorageVersion().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/PlayerSymptoms/StateManager.c