DayZ: scripts/3_Game/PPEManager/PPERequestData.c File Reference
PPERequestData.c File Reference
Classes
class PPERequestParamDataBase
Data for one material parameter, requester side.
Functions
void PPERequestParamDataBool (int requester_idx, int mat_id, int param_id, int data_type=0, int priority=0, int mask=PPOperators.SET, bool relative=false)
void PPERequestParamDataFloat (int requester_idx, int mat_id, int param_id, int data_type=0, int priority=0, int mask=PPOperators.SET, bool relative=false)
override void InitValues ()
Variables
class PPERequestParamDataBase m_BoolTarget
bool m_BoolCurrent
bool m_BoolLast
class PPERequestParamDataInt extends PPERequestParamDataBase m_FloatTarget
float m_FloatCurrent
float m_FloatLast
float m_FloatFormerTarget
float m_FloatStart
class PPERequestParamDataColor extends PPERequestParamDataBase m_VectorTarget
vector m_VectorCurrent
vector m_VectorLast
Function Documentation
InitValues()
override void InitValues ()
Definition at line 147 of file PPERequestData.c.
  {
    m_FloatTarget = float.LOWEST;
    m_FloatCurrent = float.LOWEST;
    m_FloatLast = float.LOWEST;
    m_FloatFormerTarget = float.LOWEST;
    m_FloatStart = float.LOWEST;
  }
References float::LOWEST, m_FloatCurrent, m_FloatFormerTarget, m_FloatLast, m_FloatStart, and m_FloatTarget.
Referenced by ScriptConsoleWeatherTab::OnClick(), and ScriptConsoleWeatherTab::ScriptConsoleWeatherTab().
PPERequestParamDataBool()
void PPERequestParamDataBool (int requester_idx, int mat_id, int param_id, int data_type = 0, int priority = 0, int mask = PPOperators.SET, bool relative = false)
Definition at line 111 of file PPERequestData.c.
  {
    m_BoolCurrent = 0;
    m_BoolLast = 0;
    m_VariableType = PPEConstants.VAR_TYPE_BOOL;
  }
References m_BoolCurrent, and m_BoolLast.
Referenced by PPERequesterBase::PrepareData(), PPERequesterBase::SetTargetValueBool(), PPERequesterBase::SetTargetValueBoolDefault(), and PPEMatClassParameterCommandData::Update().
PPERequestParamDataFloat()
void PPERequestParamDataFloat (int requester_idx, int mat_id, int param_id, int data_type = 0, int priority = 0, int mask = PPOperators.SET, bool relative = false)
Definition at line 142 of file PPERequestData.c.
  {
    m_VariableType = PPEConstants.VAR_TYPE_FLOAT;
  }
Referenced by PPERequesterBase::PrepareData(), PPERequesterBase::SetTargetValueFloat(), PPERequesterBase::SetTargetValueFloatDefault(), and PPEMatClassParameterCommandData::Update().
Variable Documentation
m_BoolCurrent
bool m_BoolCurrent
Definition at line 108 of file PPERequestData.c.
Referenced by PPERequestParamDataBool().
m_BoolLast
bool m_BoolLast
Definition at line 109 of file PPERequestData.c.
Referenced by PPERequestParamDataBool().
m_BoolTarget
class PPERequestParamDataBase m_BoolTarget
m_FloatCurrent
float m_FloatCurrent
Definition at line 136 of file PPERequestData.c.
Referenced by InitValues().
m_FloatFormerTarget
float m_FloatFormerTarget
Definition at line 139 of file PPERequestData.c.
Referenced by InitValues().
m_FloatLast
float m_FloatLast
Definition at line 137 of file PPERequestData.c.
Referenced by InitValues().
m_FloatStart
float m_FloatStart
Definition at line 140 of file PPERequestData.c.
Referenced by InitValues().
m_FloatTarget
class PPERequestParamDataInt extends PPERequestParamDataBase m_FloatTarget
Referenced by InitValues().
m_VectorCurrent
vector m_VectorCurrent
Definition at line 185 of file PPERequestData.c.
m_VectorLast
vector m_VectorLast
Definition at line 186 of file PPERequestData.c.
m_VectorTarget
class PPERequestParamDataColor extends PPERequestParamDataBase m_VectorTarget