DayZ: scripts/5_Mission/GUI/CrossHairSelector.c File Reference
CrossHairSelector.c File Reference
Classes
class CrossHair
Functions
void CrossHairSelector ()
void ~CrossHairSelector ()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
void OnWidgetScriptInit (Widget w)
void Update ()
void GetPlayer ()
void GetActionManager ()
CrossHair GetCrossHairByName (string widgetName)
CrossHair GetCurrentCrossHair ()
void SelectCrossHair ()
void ShowCrossHair (CrossHair crossHair)
void FloatingCrossHair (Widget widget)
Highly WIP, do not use.
Variables
class CrossHair m_Player
ActionManagerBase m_AM
Widget m_Root
ref set< ref CrossHair > m_CrossHairs
vector m_PreviousDirection
Floating crosshair.
bool m_PreviousDirectionSet
Function Documentation
CrossHairSelector()
void CrossHairSelector () protected
Definition at line 67 of file CrossHairSelector.c.
  {
    m_Player = null;
    m_AM = null;
    m_CrossHairs = new set<ref CrossHair>;
    GetGame().GetPostUpdateQueue(CALL_CATEGORY_GUI).Insert(Update);
  }
References CALL_CATEGORY_GUI, GetGame(), m_AM, m_CrossHairs, m_Player, and Update().
FloatingCrossHair()
void FloatingCrossHair (Widget widget) protected
Highly WIP, do not use.
Only intended to be used with track IR
Definition at line 217 of file CrossHairSelector.c.
  {
    HumanInputController hic = m_Player.GetInputController();
    if (!hic.CameraIsTracking())
    {
      widget.SetPos(0, 0);
      widget.Update();
      return;
    }
    ActionBase action = m_AM.GetRunningAction();
    float dt = GetDayZGame().GetDeltaT();
    HumanCommandWeapons hcw = m_Player.GetCommandModifier_Weapons();
    vector transform[4];
    m_Player.GetTransformWS(transform);
    vector aimAngles = Vector(hcw.GetBaseAimingAngleLR(), hcw.GetBaseAimingAngleUD(), 0.0);
    vector plrAngles = Math3D.MatrixToAngles(transform);
    aimAngles = Vector(0.0, hcw.GetBaseAimingAngleUD(), 0.0);
    plrAngles = Vector(hic.GetHeadingAngle() * -Math.RAD2DEG, 0, 0);
    vector resAngle = aimAngles + plrAngles;
    vector start;
    MiscGameplayFunctions.GetHeadBonePos(m_Player, start);
    vector direction = resAngle.AnglesToVector();
    int layer = ObjIntersectView;
    float range = 1.0;
    Weapon_Base weapon;
    if (Class.CastTo(weapon, m_Player.GetItemInHands()) && m_Player.IsRaised())
    {
      layer = ObjIntersectFire;
      range = 10.0;
      vector usti_hlavne_position = weapon.GetSelectionPositionMS("usti hlavne");
      vector konec_hlavne_position = weapon.GetSelectionPositionMS("konec hlavne");
      usti_hlavne_position = m_Player.ModelToWorld(usti_hlavne_position);
      konec_hlavne_position = m_Player.ModelToWorld(konec_hlavne_position);
      vector contact_dir;
      int contact_component;
      direction = konec_hlavne_position - usti_hlavne_position;
      direction.Normalize();
      start = konec_hlavne_position;
      m_PreviousDirectionSet = false;
    }
    else
    {
      if (!m_PreviousDirectionSet)
      {
        m_PreviousDirectionSet = true;
        m_PreviousDirection = direction;
      }
      float r0[4];
      float r1[4];
      vector t[4];
      Math3D.DirectionAndUpMatrix(m_PreviousDirection, vector.Up, t);
      Math3D.MatrixToQuat(t, r0);
      Math3D.DirectionAndUpMatrix(direction, vector.Up, t);
      Math3D.MatrixToQuat(t, r1);
      Math3D.QuatLerp(r0, r0, r1, 0.1);
      Math3D.QuatToMatrix(r0, t);
      direction = t[2];
      m_PreviousDirection = direction;
    }
    vector end = start + (direction * range);
    vector position = end;
    DayZPhysics.RaycastRV(start, end, position, contact_dir, contact_component, null, m_Player, m_Player, false, false, layer);
    /*
      vector lines[2];
      lines[0] = start;
      lines[1] = end;
      Shape.CreateSphere(0xFFFFFF00, ShapeFlags.ONCE, usti_hlavne_position, 0.1);
      Shape.CreateSphere(0xFFFFFF00, ShapeFlags.ONCE, konec_hlavne_position, 0.1);
      Shape.CreateLines(0xFF00FF00, ShapeFlags.ONCE, lines, 2);
    */
    vector screenSpace = GetGame().GetScreenPos(position);
    float sx, sy;
    widget.GetScreenSize(sx, sy);
    screenSpace[0] = screenSpace[0] - (sx * 0.5);
    screenSpace[1] = screenSpace[1] - (sy * 0.5);
    widget.SetScreenPos(screenSpace[0], screenSpace[1]);
    widget.Update();
  }
References Class::CastTo(), Math3D::DirectionAndUpMatrix(), GetDayZGame(), GetGame(), DayZPlayer::IsRaised(), m_AM, m_Player, m_PreviousDirection, m_PreviousDirectionSet, Math3D::MatrixToAngles(), Math3D::MatrixToQuat(), Math3D::QuatLerp(), Math3D::QuatToMatrix(), Math::RAD2DEG, DayZPhysics::RaycastRV(), vector::Up, and Vector().
Referenced by ShowCrossHair().
GetActionManager()
void GetActionManager () protected
Definition at line 130 of file CrossHairSelector.c.
  {
    if (m_Player && m_Player.IsPlayerSelected())
      Class.CastTo(m_AM, m_Player.GetActionManager());
    else
      m_AM = null;
  }
References Class::CastTo(), DayZPlayer::IsPlayerSelected(), m_AM, and m_Player.
Referenced by ManBase::AddAction(), ManBase::CanBeRestrained(), Container::CanCombineAmmo(), ManBase::CanDeleteItems(), ManBase::CloseMapEx(), ManBase::CommandHandler(), ManBase::HeadingModel(), ManBase::OnQuickBarContinuousUseEnd(), ManBase::OnQuickBarContinuousUseStart(), ManBase::OnQuickBarSingleUse(), ManBase::ReloadWeapon(), and ManBase::RemoveAction().
GetCrossHairByName()
CrossHair GetCrossHairByName (string widgetName) protected
Definition at line 138 of file CrossHairSelector.c.
  {
    for (int i = 0; i < m_CrossHairs.Count(); i++)
    {
      if (m_CrossHairs.Get(i).GetName() == widgetName)
        return m_CrossHairs.Get(i);
    }
    return null;
  }
References m_CrossHairs.
Referenced by SelectCrossHair().
GetCurrentCrossHair()
CrossHair GetCurrentCrossHair () protected
Definition at line 149 of file CrossHairSelector.c.
  {
    for (int i = 0; i < m_CrossHairs.Count(); i++)
    {
      if (m_CrossHairs.Get(i).IsCurrent())
        return m_CrossHairs.Get(i);
    }
    return null;
  }
References m_CrossHairs.
Referenced by ShowCrossHair(), and Update().
GetPlayer()
void GetPlayer () protected
Definition at line 125 of file CrossHairSelector.c.
  {
    Class.CastTo(m_Player, GetGame().GetPlayer());
  }
References Class::CastTo(), GetGame(), ScriptedWidgetEventHandler::GetPlayer(), and m_Player.
Init()
void Init () protected
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
pre-init arrays
Definition at line 81 of file CrossHairSelector.c.
  {
    m_CrossHairs.Clear();
    Widget child = m_Root.GetChildren();
    while (child)
    {
      m_CrossHairs.Insert(CrossHair(child));
      child = child.GetSibling();
    }
  }
References m_CrossHairs, and m_Root.
OnWidgetScriptInit()
void OnWidgetScriptInit (Widget w) protected
Definition at line 93 of file CrossHairSelector.c.
  {
    m_Root = w;
    m_Root.SetHandler(this);
    Init();
    m_Root.Update();
  }
References ScriptedWidgetEventHandler::Init(), and m_Root.
SelectCrossHair()
void SelectCrossHair () protected
firearms
On Continuous Actions
raised hands(bare + non-firearm) + melee cmd
handle unconscious state
default
Definition at line 160 of file CrossHairSelector.c.
  {
    if (!m_AM) return;
    HumanInputController hic = m_Player.GetInputController();
    ActionBase action = m_AM.GetRunningAction();
    bool firearmInHands = m_Player.GetItemInHands() && m_Player.GetItemInHands().IsWeapon();
    if (firearmInHands && m_Player.IsRaised() && !m_Player.IsInIronsights() && !m_Player.IsInOptics() && !hic.CameraIsFreeLook() && !m_Player.GetCommand_Melee2())
      ShowCrossHair(GetCrossHairByName("crossT_128x128"));
    else if (action && action.GetActionCategory() == AC_CONTINUOUS)
    {
      int actionState = m_AM.GetActionState(action);
      if (actionState != UA_NONE)
        ShowCrossHair(null);
    }
    else if (m_Player.IsRaised() || m_Player.GetCommand_Melee2() || GetGame().GetUIManager().GetMenu() != null)
      ShowCrossHair(null);
    else if (m_Player.GetCommand_Unconscious())
      ShowCrossHair(null);
    else
      ShowCrossHair(GetCrossHairByName("dot"));
  }
References AC_CONTINUOUS, GetCrossHairByName(), GetGame(), DayZPlayer::IsInIronsights(), DayZPlayer::IsInOptics(), DayZPlayer::IsRaised(), m_AM, m_Player, ShowCrossHair(), and UA_NONE.
Referenced by Update().
ShowCrossHair()
void ShowCrossHair (CrossHair crossHair) protected
no crosshair + clean + hide the previous
hide prev crosshair
show the new one
Definition at line 191 of file CrossHairSelector.c.
  {
    if (!crossHair)
    {
      if (GetCurrentCrossHair())
        GetCurrentCrossHair().Hide();
      return;
    }
    else
    {
      if (GetCurrentCrossHair() && GetCurrentCrossHair() != crossHair)
        GetCurrentCrossHair().Hide();
    }
    if (!crossHair.IsCurrent() && crossHair.IsShown())
      crossHair.Show();
#ifdef WIP_TRACKIR
    FloatingCrossHair(crossHair.GetWidget());
#endif
  }
References FloatingCrossHair(), GetCurrentCrossHair(), and CrossHair::Hide().
Referenced by SelectCrossHair(), and Update().
~CrossHairSelector()
void ~CrossHairSelector () protected
Definition at line 76 of file CrossHairSelector.c.
  {
    GetGame().GetPostUpdateQueue(CALL_CATEGORY_GUI).Remove(Update);
  }
References CALL_CATEGORY_GUI, GetGame(), and Update().
Variable Documentation
m_AM
ActionManagerBase m_AM protected
Definition at line 57 of file CrossHairSelector.c.
Referenced by ScriptedWidgetEventHandler::ContinuousActionProgress(), CrossHairSelector(), FloatingCrossHair(), ScriptedWidgetEventHandler::GetActionManager(), GetActionManager(), ScriptedWidgetEventHandler::GetActions(), ScriptedWidgetEventHandler::ItemActionsWidget(), SelectCrossHair(), ScriptedWidgetEventHandler::Update(), and Update().
m_CrossHairs
ref set<ref CrossHair> m_CrossHairs protected
Definition at line 61 of file CrossHairSelector.c.
Referenced by CrossHairSelector(), GetCrossHairByName(), GetCurrentCrossHair(), and Init().
m_Player
class CrossHair m_Player
m_PreviousDirection
vector m_PreviousDirection protected
Floating crosshair.
Definition at line 64 of file CrossHairSelector.c.
Referenced by FloatingCrossHair().
m_PreviousDirectionSet
bool m_PreviousDirectionSet protected
Definition at line 65 of file CrossHairSelector.c.
Referenced by FloatingCrossHair().
m_Root
Widget m_Root protected
Definition at line 59 of file CrossHairSelector.c.