DayZ: scripts/4_World/Entities/Grenade_Base/SmokeGrenadeBase.c File Reference
SmokeGrenadeBase.c File Reference
Enumerations
enum ESmokeGrenadeState { NO_SMOKE , LOOP = 2 , END = 3 , COUNT = 4 }
Functions
void SetParticleSmokeCurrent (int particle)
void SetParticleSmokeStart (int particle)
void SetParticleSmokeLoop (int particle)
void SetParticleSmokeEnd (int particle)
void SetSoundSmokeStart (string sound)
void SetSoundSmokeLoop (string sound)
void SetSoundSmokeEnd (string sound)
void PlaySmokeParticle ()
void SoundSmokeStart ()
void SoundSmokeLoop ()
void SoundSmokeEnd ()
void SoundSmokeStop ()
void DestroySmokeGrenade ()
void RefreshParticlesAndSounds ()
override void Unpin ()
override void OnActivateFinished ()
override void OnWorkStart ()
override void OnWork (float consumed_energy)
override void OnWorkStop ()
override bool CanPutInCargo (EntityAI parent)
override void OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
override void SetActions ()
override void OnVariablesSynchronized ()
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
ESmokeGrenadeState GetSmokeGrenadeState ()
override void EEDelete (EntityAI parent)
void SetSmokeGrenadeState (ESmokeGrenadeState state)
void SmokeGrenadeBase ()
void ~SmokeGrenadeBase ()
Variables
enum ESmokeGrenadeState m_TimerSmokeStart
ref Timer m_TimerSmokeLoop
ref Timer m_TimerSmokeEnd
ref Timer m_TimerDefer
ESmokeGrenadeState m_SmokeGrenadeState
ESmokeGrenadeState m_LastSmokeGrenadeState
Particle m_ParticleSmoke
particle
int m_ParticleSmokeCurrentId
int m_ParticleSmokeStartId
int m_ParticleSmokeLoopId
int m_ParticleSmokeEndId
vector m_ParticleSmokePosition
EffectSound m_SoundSmoke
sounds
string m_SoundSmokeStartId
string m_SoundSmokeLoopId
string m_SoundSmokeEndId
ref NoiseParams m_NoisePar
Noise.
Enumeration Type Documentation
ESmokeGrenadeState
enum ESmokeGrenadeState
Enumerator
NO_SMOKE
LOOP
END
COUNT
Definition at line 1 of file SmokeGrenadeBase.c.
{
  NO_SMOKE = 0
              START = 1,
              LOOP = 2,
              END = 3,
              COUNT = 4
}
Function Documentation
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) protected
Definition at line 208 of file SmokeGrenadeBase.c.
  {
    return !GetCompEM().IsWorking();
  }
DestroySmokeGrenade()
void DestroySmokeGrenade () protected
Definition at line 100 of file SmokeGrenadeBase.c.
  {
    SetSmokeGrenadeState(ESmokeGrenadeState.NO_SMOKE);
    if (GetGame().IsServer())
      SetHealth("", "", 0);
  }
References GetGame(), and SetSmokeGrenadeState().
EEDelete()
override void EEDelete (EntityAI parent) protected
Definition at line 239 of file SmokeGrenadeBase.c.
  {
    super.EEDelete(parent);
    SoundSmokeStop();
    DestroyParticle(m_ParticleSmoke);
  }
References DestroyParticle(), m_ParticleSmoke, and SoundSmokeStop().
GetSmokeGrenadeState()
ESmokeGrenadeState GetSmokeGrenadeState () protected
Definition at line 234 of file SmokeGrenadeBase.c.
  {
    return m_SmokeGrenadeState;
  }
References m_SmokeGrenadeState.
Referenced by RefreshParticlesAndSounds().
OnActivatedByItem()
override void OnActivatedByItem (notnull ItemBase item) protected
Called when this item is activated by other.
Definition at line 213 of file SmokeGrenadeBase.c.
  {
    GetCompEM().SwitchOn();
  }
OnActivateFinished()
override void OnActivateFinished () protected
Definition at line 164 of file SmokeGrenadeBase.c.
  {
    if (GetCompEM() && GetCompEM().CanWork())
      GetCompEM().SwitchOn();
  }
OnExplosionEffects()
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType) protected
Definition at line 232 of file SmokeGrenadeBase.c.
{}
OnVariablesSynchronized()
override void OnVariablesSynchronized () protected
Definition at line 225 of file SmokeGrenadeBase.c.
  {
    super.OnVariablesSynchronized();
    RefreshParticlesAndSounds();
  }
References RefreshParticlesAndSounds().
OnWork()
override void OnWork (float consumed_energy) protected
Definition at line 189 of file SmokeGrenadeBase.c.
  {
    if (GetGame().IsServer())
    {
      NoiseSystem noise = GetGame().GetNoiseSystem();
      if (noise)
        noise.AddNoisePos(this, GetPosition(), m_NoisePar);
    }
  }
References GetGame(), GetPosition, and m_NoisePar.
OnWorkStart()
override void OnWorkStart () protected
Definition at line 171 of file SmokeGrenadeBase.c.
  {
    SetSmokeGrenadeState(ESmokeGrenadeState.START);
    if (GetGame().IsServer())
    {
      m_NoisePar = new NoiseParams();
      m_NoisePar.LoadFromPath("cfgVehicles " + GetType() + " NoiseSmokeGrenade");
      NoiseSystem noise = GetGame().GetNoiseSystem();
      if (noise)
        noise.AddNoisePos(this, GetPosition(), m_NoisePar);
    }
    Param1<ESmokeGrenadeState> par = new Param1<ESmokeGrenadeState>(ESmokeGrenadeState.LOOP);
    m_TimerSmokeLoop.Run(5.0, this, "SetSmokeGrenadeState", par);
  }
References GetGame(), GetPosition, GetType(), m_NoisePar, m_TimerSmokeLoop, NoiseParams(), and SetSmokeGrenadeState().
OnWorkStop()
override void OnWorkStop () protected
defer timer
Definition at line 200 of file SmokeGrenadeBase.c.
  {
    SetSmokeGrenadeState(ESmokeGrenadeState.END);
    m_TimerDefer.Run(5.0, this, "DestroySmokeGrenade");
  }
References m_TimerDefer, and SetSmokeGrenadeState().
PlaySmokeParticle()
void PlaySmokeParticle () protected
Definition at line 74 of file SmokeGrenadeBase.c.
  {
    m_ParticleSmoke = ParticleManager.GetInstance().PlayOnObject(m_ParticleSmokeCurrentId, this, m_ParticlePosition, vector.Zero, true);
  }
References m_ParticlePosition, m_ParticleSmoke, m_ParticleSmokeCurrentId, ParticleManager(), and vector::Zero.
Referenced by RefreshParticlesAndSounds().
RefreshParticlesAndSounds()
void RefreshParticlesAndSounds () protected
Definition at line 108 of file SmokeGrenadeBase.c.
  {
    ESmokeGrenadeState state = GetSmokeGrenadeState();
    if (m_LastSmokeGrenadeState != state)
    {
      if (state == ESmokeGrenadeState.START)
      {
        //Print("RefreshAudioVisual:: START");
        SoundSmokeEnd();
        SoundSmokeStart();
        DestroyParticle(m_ParticleSmoke);
        SetParticleSmokeCurrent(m_ParticleSmokeStartId);
        PlaySmokeParticle();
      }
      else if (state == ESmokeGrenadeState.LOOP)
      {
        //Print("RefreshAudioVisual:: LOOP");
        SoundSmokeStop();
        SoundSmokeLoop();
        DestroyParticle(m_ParticleSmoke);
        SetParticleSmokeCurrent(m_ParticleSmokeLoopId);
        PlaySmokeParticle();
      }
      else if (state == ESmokeGrenadeState.END)
      {
        //Print("RefreshAudioVisual:: END");
        SoundSmokeStop();
        SoundSmokeEnd();
        DestroyParticle(m_ParticleSmoke);
        SetParticleSmokeCurrent(m_ParticleSmokeEndId);
        PlaySmokeParticle();
      }
      else if (state == ESmokeGrenadeState.NO_SMOKE)
      {
        //Print("RefreshAudioVisual:: NO_SMOKE");
        SoundSmokeStop();
        DestroyParticle(m_ParticleSmoke);
      }
      m_LastSmokeGrenadeState = state;
    }
  }
References DestroyParticle(), GetSmokeGrenadeState(), m_LastSmokeGrenadeState, m_ParticleSmoke, m_ParticleSmokeEndId, m_ParticleSmokeLoopId, m_ParticleSmokeStartId, PlaySmokeParticle(), SetParticleSmokeCurrent(), SoundSmokeEnd(), SoundSmokeLoop(), SoundSmokeStart(), and SoundSmokeStop().
Referenced by OnVariablesSynchronized().
SetActions()
override void SetActions () protected
Definition at line 218 of file SmokeGrenadeBase.c.
  {
    super.SetActions();
    RemoveAction(ActionPin);
  }
References RemoveAction().
SetParticleSmokeCurrent()
void SetParticleSmokeCurrent (int particle) protected
Definition at line 39 of file SmokeGrenadeBase.c.
  {
    m_ParticleSmokeCurrentId = particle;
  }
References m_ParticleSmokeCurrentId.
Referenced by RefreshParticlesAndSounds().
SetParticleSmokeEnd()
void SetParticleSmokeEnd (int particle) protected
Definition at line 54 of file SmokeGrenadeBase.c.
  {
    m_ParticleSmokeEndId = particle;
  }
References m_ParticleSmokeEndId.
Referenced by M18SmokeGrenade_ColorBase::M18SmokeGrenade_White(), M18SmokeGrenade_ColorBase::M18SmokeGrenade_Yellow(), M18SmokeGrenade_Yellow(), OnWorkStop(), RDG2SmokeGrenade_ColorBase::RDG2SmokeGrenade_Black(), RDG2SmokeGrenade_Black(), and SmokeGrenadeBase().
SetParticleSmokeLoop()
void SetParticleSmokeLoop (int particle) protected
Definition at line 49 of file SmokeGrenadeBase.c.
  {
    m_ParticleSmokeLoopId = particle;
  }
References m_ParticleSmokeLoopId.
Referenced by M18SmokeGrenade_ColorBase::M18SmokeGrenade_White(), M18SmokeGrenade_ColorBase::M18SmokeGrenade_Yellow(), M18SmokeGrenade_Yellow(), OnWorkStop(), RDG2SmokeGrenade_ColorBase::RDG2SmokeGrenade_Black(), RDG2SmokeGrenade_Black(), and SmokeGrenadeBase().
SetParticleSmokeStart()
void SetParticleSmokeStart (int particle) protected
Definition at line 44 of file SmokeGrenadeBase.c.
  {
    m_ParticleSmokeStartId = particle;
  }
References m_ParticleSmokeStartId.
Referenced by M18SmokeGrenade_ColorBase::M18SmokeGrenade_White(), M18SmokeGrenade_ColorBase::M18SmokeGrenade_Yellow(), M18SmokeGrenade_Yellow(), OnWorkStop(), RDG2SmokeGrenade_ColorBase::RDG2SmokeGrenade_Black(), RDG2SmokeGrenade_Black(), and SmokeGrenadeBase().
SetSmokeGrenadeState()
void SetSmokeGrenadeState (ESmokeGrenadeState state) protected
Definition at line 247 of file SmokeGrenadeBase.c.
  {
    //Print("Setting SGS to: " + typename.EnumToString(ESmokeGrenadeState, state));
    if (GetGame().IsServer())
    {
      if (m_SmokeGrenadeState != state)
      {
        m_SmokeGrenadeState = state;
        //synchronize
        SetSynchDirty();
      }
    }
  }
References GetGame(), and m_SmokeGrenadeState.
Referenced by DestroySmokeGrenade(), OnWorkStart(), and OnWorkStop().
SetSoundSmokeEnd()
void SetSoundSmokeEnd (string sound) protected
Definition at line 69 of file SmokeGrenadeBase.c.
  {
    m_SoundSmokeEndId = sound;
  }
References m_SoundSmokeEndId.
Referenced by SmokeGrenadeBase::M18SmokeGrenade_ColorBase(), and SmokeGrenadeBase::RDG2SmokeGrenade_ColorBase().
SetSoundSmokeLoop()
void SetSoundSmokeLoop (string sound) protected
Definition at line 64 of file SmokeGrenadeBase.c.
  {
    m_SoundSmokeLoopId = sound;
  }
References m_SoundSmokeLoopId.
Referenced by SmokeGrenadeBase::M18SmokeGrenade_ColorBase(), and SmokeGrenadeBase::RDG2SmokeGrenade_ColorBase().
SetSoundSmokeStart()
void SetSoundSmokeStart (string sound) protected
Definition at line 59 of file SmokeGrenadeBase.c.
  {
    m_SoundSmokeStartId = sound;
  }
References m_SoundSmokeStartId.
Referenced by SmokeGrenadeBase::M18SmokeGrenade_ColorBase(), and SmokeGrenadeBase::RDG2SmokeGrenade_ColorBase().
SmokeGrenadeBase()
void SmokeGrenadeBase () protected
no effect on base
no effect on base
no effect on base
Definition at line 263 of file SmokeGrenadeBase.c.
  {
    m_SmokeGrenadeState = ESmokeGrenadeState.NO_SMOKE;
    m_TimerSmokeLoop = new Timer;
    m_TimerDefer = new Timer;
    SetAmmoType("");
    SetPinnable(false);
    SetGrenadeType(EGrenadeType.CHEMICAL);
    SetParticleSmokeStart(ParticleList.INVALID);
    SetParticleSmokeLoop(ParticleList.INVALID);
    SetParticleSmokeEnd(ParticleList.INVALID);
    RegisterNetSyncVariableInt("m_SmokeGrenadeState", ESmokeGrenadeState.NO_SMOKE, ESmokeGrenadeState.COUNT);
  }
References ParticleList::INVALID, m_SmokeGrenadeState, m_TimerDefer, m_TimerSmokeLoop, SetAmmoType(), SetParticleSmokeEnd(), SetParticleSmokeLoop(), and SetParticleSmokeStart().
SoundSmokeEnd()
void SoundSmokeEnd () protected
Definition at line 89 of file SmokeGrenadeBase.c.
  {
    PlaySoundSetLoop(m_SoundSmoke, m_SoundSmokeEndId, 1.0, 1.0);
  }
References m_SoundSmoke, and m_SoundSmokeEndId.
Referenced by RefreshParticlesAndSounds().
SoundSmokeLoop()
void SoundSmokeLoop () protected
Definition at line 84 of file SmokeGrenadeBase.c.
  {
    PlaySoundSetLoop(m_SoundSmoke, m_SoundSmokeLoopId, 0.3, 1.0);
  }
References m_SoundSmoke, and m_SoundSmokeLoopId.
Referenced by RefreshParticlesAndSounds().
SoundSmokeStart()
void SoundSmokeStart () protected
Definition at line 79 of file SmokeGrenadeBase.c.
  {
    PlaySoundSetLoop(m_SoundSmoke, m_SoundSmokeStartId, 0.3, 1.0);
  }
References m_SoundSmoke, and m_SoundSmokeStartId.
Referenced by RefreshParticlesAndSounds().
SoundSmokeStop()
void SoundSmokeStop () protected
Definition at line 95 of file SmokeGrenadeBase.c.
  {
    StopSoundSet(m_SoundSmoke);
  }
References m_SoundSmoke.
Referenced by EEDelete(), and RefreshParticlesAndSounds().
Unpin()
override void Unpin () protected
Definition at line 156 of file SmokeGrenadeBase.c.
  {
    super.Unpin();
    Activate();
  }
References Activate().
~SmokeGrenadeBase()
void ~SmokeGrenadeBase () protected
Variable Documentation
m_LastSmokeGrenadeState
ESmokeGrenadeState m_LastSmokeGrenadeState protected
Definition at line 20 of file SmokeGrenadeBase.c.
Referenced by RefreshParticlesAndSounds().
m_NoisePar
ref NoiseParams m_NoisePar protected
Noise.
Definition at line 37 of file SmokeGrenadeBase.c.
m_ParticleSmoke
Particle m_ParticleSmoke protected
particle
Definition at line 23 of file SmokeGrenadeBase.c.
Referenced by BuildingSuper::EEDelete(), EEDelete(), BuildingSuper::EEInit(), PlaySmokeParticle(), and RefreshParticlesAndSounds().
m_ParticleSmokeCurrentId
int m_ParticleSmokeCurrentId protected
Definition at line 24 of file SmokeGrenadeBase.c.
Referenced by PlaySmokeParticle(), and SetParticleSmokeCurrent().
m_ParticleSmokeEndId
int m_ParticleSmokeEndId protected
Definition at line 27 of file SmokeGrenadeBase.c.
Referenced by RefreshParticlesAndSounds(), and SetParticleSmokeEnd().
m_ParticleSmokeLoopId
int m_ParticleSmokeLoopId protected
Definition at line 26 of file SmokeGrenadeBase.c.
Referenced by RefreshParticlesAndSounds(), and SetParticleSmokeLoop().
m_ParticleSmokePosition
vector m_ParticleSmokePosition protected
Definition at line 28 of file SmokeGrenadeBase.c.
m_ParticleSmokeStartId
int m_ParticleSmokeStartId protected
Definition at line 25 of file SmokeGrenadeBase.c.
Referenced by RefreshParticlesAndSounds(), and SetParticleSmokeStart().
m_SmokeGrenadeState
ESmokeGrenadeState m_SmokeGrenadeState protected
Definition at line 19 of file SmokeGrenadeBase.c.
Referenced by GetSmokeGrenadeState(), SetSmokeGrenadeState(), and SmokeGrenadeBase().
m_SoundSmoke
EffectSound m_SoundSmoke protected
sounds
Definition at line 31 of file SmokeGrenadeBase.c.
Referenced by SoundSmokeEnd(), SoundSmokeLoop(), SoundSmokeStart(), and SoundSmokeStop().
m_SoundSmokeEndId
string m_SoundSmokeEndId protected
Definition at line 34 of file SmokeGrenadeBase.c.
Referenced by SetSoundSmokeEnd(), and SoundSmokeEnd().
m_SoundSmokeLoopId
string m_SoundSmokeLoopId protected
Definition at line 33 of file SmokeGrenadeBase.c.
Referenced by SetSoundSmokeLoop(), and SoundSmokeLoop().
m_SoundSmokeStartId
string m_SoundSmokeStartId protected
Definition at line 32 of file SmokeGrenadeBase.c.
Referenced by SetSoundSmokeStart(), and SoundSmokeStart().
m_TimerDefer
ref Timer m_TimerDefer protected
Definition at line 17 of file SmokeGrenadeBase.c.
Referenced by OnWorkStop(), and SmokeGrenadeBase().
m_TimerSmokeEnd
ref Timer m_TimerSmokeEnd protected
Definition at line 15 of file SmokeGrenadeBase.c.
m_TimerSmokeLoop
ref Timer m_TimerSmokeLoop protected
Definition at line 14 of file SmokeGrenadeBase.c.
Referenced by OnWorkStart(), and SmokeGrenadeBase().
m_TimerSmokeStart
enum ESmokeGrenadeState m_TimerSmokeStart