DayZ: Container Class Reference
Container Class Reference
Protected Member Functions
void CargoContainer (LayoutHolder parent, bool is_attachment=false)
void ~CargoContainer ()
int GetCargoIndex ()
void AddedToCargoEx (EntityAI item, bool refresh=true)
void AddedToCargo (EntityAI item)
void RemovedFromCargo (EntityAI item)
void MovedInCargo (EntityAI item)
void SetLock (EntityAI item)
void ReleaseLock (EntityAI item)
override void SetLayoutName ()
void SetEntity (EntityAI item, int cargo_index=0, bool immedUpdate=true)
EntityAI GetEntity ()
void UpdateHeaderText ()
void InitGridHeight ()
void UpdateSize ()
float GetIconSize ()
float GetSpaceSize ()
int GetCargoCapacity ()
int GetMaxCargoCapacity ()
Icon GetIcon (EntityAI item)
Icon GetIcon (int index)
Icon GetFocusedIcon ()
override float GetFocusedContainerHeight (bool contents=false)
override float GetFocusedContainerYPos (bool contents=false)
override float GetFocusedContainerYScreenPos (bool contents=false)
void UpdateSelection ()
void UpdateRowVisibility (int count)
override void Refresh ()
void RefreshImpl ()
override void UpdateInterval ()
Icon InitIconEx (Icon icon, EntityAI item, int pos_x, int pos_y, bool refresh=true)
Icon InitIcon (Icon icon, EntityAI item, int pos_x, int pos_y)
bool HasItem (EntityAI item)
override bool TransferItemToVicinity ()
override void SetDefaultFocus (bool while_micromanagment_mode=false)
override void SetLastFocus ()
override void Unfocus ()
override void UnfocusAll ()
override void SetNextActive ()
override void SetPreviousActive (bool force=false)
override void SetNextRightActive ()
override void SetNextLeftActive ()
override EntityAI GetFocusedItem ()
override void SetLastActive ()
override void SetActive (bool active)
override bool IsItemActive ()
override bool IsItemWithQuantityActive ()
override bool IsEmpty ()
int GetRecipeCount (bool recipe_anywhere, ItemBase entity1, ItemBase entity2, PlayerBase player)
override bool CanCombineAmmo ()
override bool TransferItem ()
override bool SplitItem ()
override bool EquipItem ()
override bool SelectItem ()
override bool Select ()
override bool Combine ()
void ShowFalseCargoHeader (bool show)
void SetAlternateFalseTextHeaderWidget (TextWidget w)
void ClosableContainer (LayoutHolder parent, int sort=-1)
override bool IsDisplayable ()
override void UpdateRadialIcon ()
void SetOpenState (bool state)
override Header GetHeader ()
override void Open ()
override void Close ()
override void SetLayoutName ()
override void OnShow ()
override LayoutHolder Get (int x)
override void Refresh ()
void CloseButtonOnMouseButtonDown ()
override float GetFocusedContainerHeight (bool contents=false)
override float GetFocusedContainerYPos (bool contents=false)
override float GetFocusedContainerYScreenPos (bool contents=false)
void MoveContainerUp (Widget cont)
void MoveContainerDown (Widget cont)
override void CheckHeaderDragability ()
Protected Attributes
const int ROWS_NUMBER_XBOX = 5
CargoBase m_Cargo
int m_CargoIndex = -1
int m_FocusedItemPosition = -1
ref array< ref CargoContainerRow > m_Rows
ref array< ref Icon > m_Icons
ref map< EntityAI, ref Param3< ref Icon, int, int > > m_ShowedItemPositions
ref map< EntityAI, ref Param3< ref Icon, int, int > > m_ShowedLockPositions
float m_IconSize
float m_SpaceSize
bool m_IsAttachment
TextWidget m_FalseHeaderTextWidget
TextWidget m_AlternateFalseHeaderTextWidget
Widget m_CargoHeader
Widget m_CargoContainer
Widget m_ItemsContainer
ref SizeToChild m_Resizer1
ref SizeToChild m_Resizer2
ref Timer m_ResizeTimer
ref ClosableHeader m_ClosableHeader
bool m_LockCargo
Detailed Description
Definition at line 2 of file CargoContainer.c.
Constructor & Destructor Documentation
~CargoContainer()
void Container::~CargoContainer () inline protected
Definition at line 52 of file CargoContainer.c.
  {
    if (m_Entity)
    {
      m_Entity.GetOnItemAddedIntoCargo().Remove(AddedToCargo);
      m_Entity.GetOnItemRemovedFromCargo().Remove(RemovedFromCargo);
      m_Entity.GetOnItemMovedInCargo().Remove(MovedInCargo);
      m_Entity.GetOnSetLock().Remove(SetLock);
      m_Entity.GetOnReleaseLock().Remove(ReleaseLock);
    }
  }
References m_Entity, and SetLock().
Member Function Documentation
AddedToCargo()
void Container::AddedToCargo (EntityAI item) inline protected
Definition at line 110 of file CargoContainer.c.
  {
    AddedToCargoEx(item);
  }
References AddedToCargoEx().
AddedToCargoEx()
void Container::AddedToCargoEx (EntityAI item, bool refresh = true) inline protected
Definition at line 66 of file CargoContainer.c.
  {
    InventoryLocation il = new InventoryLocation;
    item.GetInventory().GetCurrentInventoryLocation(il);
    int x = il.GetCol();
    int y = il.GetRow();
    if (m_ShowedItemPositions.Contains(item))
    {
      Param3<ref Icon, int, int> item_pos = m_ShowedItemPositions.Get(item);
      InitIconEx(item_pos.param1, item, x, y, refresh);
      item_pos.param2 = x;
      item_pos.param3 = y;
    }
    else
    {
      ref Icon icon = new Icon(this, false);
      m_Icons.Insert(icon);
      InitIconEx(icon, item, x, y, refresh);
      m_ShowedItemPositions.Insert(item, new Param3<ref Icon, int, int>(icon, x, y));
    }
    if (refresh)
      UpdateHeaderText();
#ifdef PLATFORM_CONSOLE
    for (int i = 0; i < m_Cargo.GetItemCount(); i++)
    {
      EntityAI item2 = m_Cargo.GetItem(i);
      Param3<ref Icon, int, int> data = m_ShowedItemPositions.Get(item2);
      if (data)
      {
        data.param1.SetCargoPos(i);
        data.param1.SetPos();
      }
    }
    m_FocusedItemPosition = Math.Min(m_ShowedItemPositions.Count() - 1, m_FocusedItemPosition);
    if (refresh)
      Refresh();
#endif
  }
References CargoBase::GetItem(), CargoBase::GetItemCount(), InitIconEx(), Math::Min(), Refresh(), UpdateHeaderText(), x, and y.
Referenced by AddedToCargo(), and SetEntity().
CanCombineAmmo()
override bool Container::CanCombineAmmo () inline protected
Definition at line 747 of file CargoContainer.c.
  {
    if (GetFocusedIcon())
    {
      ActionManagerClient amc = ActionManagerClient.Cast(PlayerBase.Cast(GetGame().GetPlayer()).GetActionManager());
      ItemBase entity = ItemBase.Cast(GetFocusedIcon().GetObject());
      ItemBase item_in_hands = ItemBase.Cast(GetGame().GetPlayer().GetHumanInventory().GetEntityInHands());
      return (amc.CanPerformActionFromInventory(item_in_hands, entity) || amc.CanSetActionFromInventory(item_in_hands, entity));
    }
    return false;
  }
References GetActionManager(), GetFocusedIcon(), GetGame(), GetObject(), and GetPlayer().
CargoContainer()
void Container::CargoContainer (LayoutHolder parent, bool is_attachment = false) inline protected
Definition at line 30 of file CargoContainer.c.
  {
    m_IsAttachment = is_attachment;
    m_Rows = new array<ref CargoContainerRow>;
    m_Icons = new array<ref Icon>;
    m_ShowedItemPositions = new map<EntityAI, ref Param3<ref Icon, int, int>>;
    m_ShowedLockPositions = new map<EntityAI, ref Param3<ref Icon, int, int>>;
    m_CargoContainer = m_RootWidget.FindAnyWidget("grid_background");
    m_ItemsContainer = m_RootWidget.FindAnyWidget("grid_overlay");
    m_CargoHeader = m_RootWidget.FindAnyWidget("grid_container_header_spacer");
#ifndef PLATFORM_CONSOLE
    m_RootWidget.GetScript(m_Resizer1);
#endif
    m_RootWidget.FindAnyWidget("grid_container").GetScript(m_Resizer2);
    m_CargoHeader.Show(is_attachment);
    m_FalseHeaderTextWidget = TextWidget.Cast(m_CargoHeader.FindAnyWidget("TextWidget0"));
    m_MainWidget = m_CargoContainer;
    m_FocusedItemPosition = -1;
  }
References m_CargoContainer, and m_RootWidget.
Referenced by HandsContainer::AttachmentAdded(), HandsContainer::AttachmentRemoved(), HandsContainer::DestroyCargo(), HandsContainer::ShowAtt(), and HandsContainer::UnfocusGrid().
CheckHeaderDragability()
override void Container::CheckHeaderDragability () inline protected
Definition at line 171 of file ClosableContainer.c.
  {
    super.CheckHeaderDragability();
    if (m_ClosableHeader && m_Entity) //TODO: do the entity check here?
    {
      int flag = m_ClosableHeader.GetMainWidget().GetFlags();
      bool old = flag & WidgetFlags.DRAGGABLE;
      bool current = ItemBase.Cast(m_Entity) && m_Entity.IsTakeable();
      //bool changed = false;
      if (old && !current)
      {
        m_ClosableHeader.GetMainWidget().ClearFlags(WidgetFlags.DRAGGABLE);
        Widget drag = GetDragWidget();
        if (drag && drag == m_ClosableHeader.GetMainWidget())
        {
          CancelWidgetDragging();
          m_ClosableHeader.OnDropHeader(null);
        }
        //changed = true;
      }
      else if (!old && current)
      {
        m_ClosableHeader.GetMainWidget().SetFlags(WidgetFlags.DRAGGABLE);
        //changed = true;
      }
      /*if (old != current)
        {
        flag &= ~WidgetFlags.DRAGGABLE;
        m_ClosableHeader.GetMainWidget().SetFlags( flag );
        }*/
    }
  }
References CancelWidgetDragging(), GetDragWidget(), and m_Entity.
Referenced by LayoutHolder::UpdateInterval().
ClosableContainer()
void Container::ClosableContainer (LayoutHolder parent, int sort = -1) inline protected
Definition at line 6 of file ClosableContainer.c.
  {
    m_Body = new array<ref LayoutHolder>;
    m_ClosableHeader = new ClosableHeader(this, "CloseButtonOnMouseButtonDown");
    if (sort > -1)
      m_RootWidget.SetSort(sort + 2);
    m_MainWidget = m_MainWidget.FindWidget("body");
  }
References m_RootWidget.
Close()
override void Container::Close () inline protected
Definition at line 73 of file ClosableContainer.c.
  {
    ItemManager.GetInstance().SetDefaultOpenState(m_Entity.GetType(), false);
    super.Close();
    SetOpenForSlotIcon(false);
    OnHide();
    m_Parent.m_Parent.Refresh(); //TODO: ???
  }
References ItemManager::GetInstance(), m_Entity, m_Parent, and OnHide().
Referenced by LayoutHolder::Toggle().
CloseButtonOnMouseButtonDown()
void Container::CloseButtonOnMouseButtonDown () inline protected
Definition at line 106 of file ClosableContainer.c.
  {
    Close();
  }
References ClosableContainer::Close().
Combine()
override bool Container::Combine () inline protected
Definition at line 894 of file CargoContainer.c.
  {
    if (CanCombine())
    {
      if (GetFocusedIcon())
      {
        Icon icon = GetFocusedIcon();
        if (icon)
        {
          EntityAI item_in_hands = GetGame().GetPlayer().GetHumanInventory().GetEntityInHands();
          EntityAI prev_item = EntityAI.Cast(icon.GetObject());
          if (item_in_hands && prev_item)
            return icon.CombineItems(item_in_hands, prev_item);
        }
      }
    }
    return false;
  }
References GetFocusedIcon(), and GetGame().
EquipItem()
override bool Container::EquipItem () inline protected
Definition at line 801 of file CargoContainer.c.
  {
    if (CanEquip())
    {
      if (GetFocusedIcon())
      {
        ItemBase entity = ItemBase.Cast(GetFocusedIcon().GetObject());
        if (entity)
        {
          GetGame().GetPlayer().PredictiveTakeEntityToInventory(FindInventoryLocationType.ATTACHMENT, entity);
          return true;
        }
      }
    }
    return false;
  }
References GetFocusedIcon(), GetGame(), and GetObject().
Get()
override LayoutHolder Container::Get (int x) inline protected
Definition at line 93 of file ClosableContainer.c.
  {
    if (m_Body && x < m_Body.Count() && x >= 0)
      return m_Body.Get(x);
    return null;
  }
References LayoutHolder::Count(), and x.
GetCargoCapacity()
int Container::GetCargoCapacity () inline protected
Definition at line 376 of file CargoContainer.c.
  {
#ifdef PLATFORM_CONSOLE
#ifndef PLATFORM_WINDOWS
    return CargoList.Cast(m_Cargo).GetTotalWeight(null);
#endif
#endif
    int total_size = 0;
    for (int i = 0; i < m_Cargo.GetItemCount(); ++i)
    {
      int x, y;
      m_Cargo.GetItemSize(i, x, y);
      total_size += x * y;
    }
    return total_size;
  }
References CargoBase::GetItemCount(), CargoBase::GetItemSize(), x, and y.
Referenced by UpdateHeaderText().
GetCargoIndex()
int Container::GetCargoIndex () inline protected
Definition at line 64 of file CargoContainer.c.
{ return m_CargoIndex; }
References m_CargoIndex.
GetEntity()
EntityAI Container::GetEntity () inline protected
Definition at line 280 of file CargoContainer.c.
  {
    return m_Entity;
  }
References m_Entity.
GetFocusedContainerHeight() [1/2]
override float Container::GetFocusedContainerHeight (bool contents = false) inline protected
Definition at line 428 of file CargoContainer.c.
  {
    float x, y;
    if (contents && GetFocusedIcon())
      GetFocusedIcon().GetRootWidget().GetScreenSize(x, y);
    else
      GetRootWidget().GetScreenSize(x, y);
    return y;
  }
References GetFocusedIcon(), x, and y.
Referenced by LeftArea::GetCurrentContainerBottomY(), RightArea::GetCurrentContainerBottomY(), and LayoutHolder::ScrollToActiveContainer().
GetFocusedContainerHeight() [2/2]
override float Container::GetFocusedContainerHeight (bool contents = false) inline protected
Definition at line 111 of file ClosableContainer.c.
  {
    float x, y;
    if (contents && GetFocusedContainer())
      y = GetFocusedContainer().GetFocusedContainerHeight(contents);
    else if (GetRootWidget())
      GetRootWidget().GetScreenSize(x, y);
    return y;
  }
References LayoutHolder::GetFocusedContainerHeight(), x, and y.
GetFocusedContainerYPos() [1/2]
override float Container::GetFocusedContainerYPos (bool contents = false) inline protected
Definition at line 438 of file CargoContainer.c.
  {
    float x, y;
    if (contents && GetFocusedIcon())
      GetFocusedIcon().GetRootWidget().GetPos(x, y);
    else
      GetRootWidget().GetPos(x, y);
    return y;
  }
References GetFocusedIcon(), x, and y.
GetFocusedContainerYPos() [2/2]
override float Container::GetFocusedContainerYPos (bool contents = false) inline protected
Definition at line 121 of file ClosableContainer.c.
  {
    float x, y;
    if (contents && GetFocusedContainer())
      y = GetFocusedContainer().GetFocusedContainerYPos(contents);
    else if (GetRootWidget())
      GetRootWidget().GetPos(x, y);
    return y;
  }
References LayoutHolder::GetFocusedContainerYPos(), x, and y.
GetFocusedContainerYScreenPos() [1/2]
override float Container::GetFocusedContainerYScreenPos (bool contents = false) inline protected
Definition at line 448 of file CargoContainer.c.
  {
    float x, y;
    if (contents && GetFocusedIcon())
      GetFocusedIcon().GetRootWidget().GetScreenPos(x, y);
    else
      GetRootWidget().GetScreenPos(x, y);
    return y;
  }
References GetFocusedIcon(), x, and y.
Referenced by LeftArea::GetCurrentContainerBottomY(), RightArea::GetCurrentContainerBottomY(), LeftArea::GetCurrentContainerTopY(), RightArea::GetCurrentContainerTopY(), and LayoutHolder::ScrollToActiveContainer().
GetFocusedContainerYScreenPos() [2/2]
override float Container::GetFocusedContainerYScreenPos (bool contents = false) inline protected
Definition at line 131 of file ClosableContainer.c.
  {
    float x, y;
    if (contents && GetFocusedContainer())
      y = GetFocusedContainer().GetFocusedContainerYScreenPos(contents);
    else if (GetRootWidget())
      GetRootWidget().GetScreenPos(x, y);
    return y;
  }
References LayoutHolder::GetFocusedContainerYScreenPos(), x, and y.
GetFocusedIcon()
Icon Container::GetFocusedIcon () inline protected
Definition at line 423 of file CargoContainer.c.
  {
    return GetIcon(m_FocusedItemPosition);
  }
References GetIcon().
Referenced by CanCombineAmmo(), Combine(), EquipItem(), GetFocusedContainerHeight(), GetFocusedContainerYPos(), GetFocusedContainerYScreenPos(), GetFocusedItem(), IsItemActive(), IsItemWithQuantityActive(), SelectItem(), SetLastActive(), SplitItem(), TransferItem(), TransferItemToVicinity(), and Unfocus().
GetFocusedItem()
override EntityAI Container::GetFocusedItem () inline protected
Definition at line 692 of file CargoContainer.c.
  {
    Icon icon = GetFocusedIcon();
    if (icon)
      return EntityAI.Cast(icon.GetObject());
    return null;
  }
References GetFocusedIcon().
Referenced by LayoutHolder::CanCombine(), VicinitySlotsContainer::CanCombineAmmo(), LayoutHolder::CanDrop(), LayoutHolder::CanEquip(), LayoutHolder::CanOpenCloseContainer(), LayoutHolder::CanSplit(), LayoutHolder::CanSwapOrTakeToHands(), LayoutHolder::CanTakeToInventory(), VicinitySlotsContainer::Combine(), VicinitySlotsContainer::EquipItem(), ZombieContainer::EquipItem(), VicinityContainer::ExpandCollapseContainer(), VicinitySlotsContainer::InspectItem(), VicinitySlotsContainer::IsEmptyItemActive(), ZombieContainer::IsEmptyItemActive(), VicinitySlotsContainer::IsItemActive(), VicinitySlotsContainer::IsItemWithContainerActive(), ZombieContainer::IsItemWithContainerActive(), VicinitySlotsContainer::IsItemWithQuantityActive(), ZombieContainer::IsItemWithQuantityActive(), VicinitySlotsContainer::IsTakeable(), HandsContainer::OnSelectButton(), Select(), VicinitySlotsContainer::Select(), ZombieContainer::Select(), VicinityContainer::SplitItem(), VicinitySlotsContainer::TransferItem(), ZombieContainer::TransferItem(), ZombieContainer::TransferItemToVicinity(), and UpdateConsoleToolbar().
GetHeader()
override Header Container::GetHeader () inline protected
Definition at line 56 of file ClosableContainer.c.
  {
    return m_ClosableHeader;
  }
Referenced by LayoutHolder::GetFocusedContainerHeight(), LayoutHolder::GetFocusedContainerYScreenPos(), LayoutHolder::SetActive(), LayoutHolder::SetLastActive(), and UpdateHeaderText().
GetIcon() [1/2]
Icon Container::GetIcon (EntityAI item) inline protected
Definition at line 403 of file CargoContainer.c.
  {
    if (item && m_ShowedItemPositions.Contains(item))
    {
      Param3<ref Icon, int, int> data = m_ShowedItemPositions.Get(item);
      return data.param1;
    }
    return null;
  }
GetIcon() [2/2]
Icon Container::GetIcon (int index) inline protected
Definition at line 413 of file CargoContainer.c.
  {
    if (m_Cargo == null)
      return null;
    if (index >= 0 && m_Cargo.GetItemCount() > index)
      return GetIcon(m_Cargo.GetItem(index));
    return null;
  }
References GetIcon(), CargoBase::GetItem(), and CargoBase::GetItemCount().
GetIconSize()
float Container::GetIconSize () inline protected
Definition at line 366 of file CargoContainer.c.
  {
    return m_IconSize;
  }
References m_IconSize.
GetMaxCargoCapacity()
int Container::GetMaxCargoCapacity () inline protected
Definition at line 393 of file CargoContainer.c.
  {
#ifdef PLATFORM_CONSOLE
#ifndef PLATFORM_WINDOWS
    return CargoList.Cast(m_Cargo).GetMaxWeight();
#endif
#endif
    return m_Cargo.GetWidth() * m_Cargo.GetHeight();
  }
References CargoBase::GetHeight(), and CargoBase::GetWidth().
Referenced by UpdateHeaderText().
GetRecipeCount()
int Container::GetRecipeCount (bool recipe_anywhere, ItemBase entity1, ItemBase entity2, PlayerBase player) inline protected
Definition at line 741 of file CargoContainer.c.
  {
    PluginRecipesManager recipes_manager = PluginRecipesManager.Cast(GetPlugin(PluginRecipesManager));
    return recipes_manager.GetValidRecipes(entity1, entity2, null, player);
  }
References GetPlugin().
GetSpaceSize()
float Container::GetSpaceSize () inline protected
Definition at line 371 of file CargoContainer.c.
  {
    return m_SpaceSize;
  }
References m_SpaceSize.
HasItem()
bool Container::HasItem (EntityAI item) inline protected
Definition at line 563 of file CargoContainer.c.
  {
    return m_ShowedItemPositions.Contains(item);
  }
InitGridHeight()
void Container::InitGridHeight () inline protected
Definition at line 313 of file CargoContainer.c.
  {
    m_Rows.Clear();
    m_ShowedItemPositions.Clear();
    ref CargoContainerRow row;
#ifdef PLATFORM_CONSOLE
    int cargo_height = 1;
#else
    int cargo_height = m_Entity.GetInventory().GetCargoFromIndex(m_CargoIndex).GetHeight();
#endif
    for (int j = 0; j < cargo_height; j++)
    {
      row = new CargoContainerRow(this);
      row.SetNumber(j);
      row.SetEntity(m_Entity);
#ifdef PLATFORM_WINDOWS
#ifndef PLATFORM_CONSOLE
      row.SetWidth(m_Entity.GetInventory().GetCargoFromIndex(m_CargoIndex).GetWidth(), false);
#endif
#endif
      row.GetRootWidget().SetSort(j, false);
      m_Rows.Insert(row);
    }
    float y;
    row.GetRootWidget().FindAnyWidget("Icon0").GetScreenSize(y, m_IconSize);
#ifdef PLATFORM_WINDOWS
#ifndef PLATFORM_CONSOLE
    row.GetRootWidget().FindAnyWidget("Spacer0").GetScreenSize(m_SpaceSize, y);
#endif
#endif
    m_Resizer2.ResizeParentToChild();
#ifndef PLATFORM_CONSOLE
    m_Resizer1.ResizeParentToChild();
#endif
  }
References m_Entity, and y.
Referenced by SetEntity().
InitIcon()
Icon Container::InitIcon (Icon icon, EntityAI item, int pos_x, int pos_y) inline protected
Definition at line 558 of file CargoContainer.c.
  {
    return InitIconEx(icon, item, pos_x, pos_y);
  }
References InitIconEx().
InitIconEx()
Icon Container::InitIconEx (Icon icon, EntityAI item, int pos_x, int pos_y, bool refresh = true) inline protected
Definition at line 531 of file CargoContainer.c.
  {
#ifdef PLATFORM_CONSOLE
    icon.SetSize(1, 1);
#ifdef PLATFORM_WINDOWS
    pos_y = pos_y * 5 + pos_x;
#endif
    icon.SetCargoPos(pos_y);
    icon.SetPosY(pos_y);
    icon.SetPosEx(refresh);
#else
    int size_x, size_y;
    GetGame().GetInventoryItemSize(InventoryItem.Cast(item), size_x, size_y);
    if (item.GetInventory().GetFlipCargo())
      icon.SetSize(size_y, size_x);
    else
      icon.SetSize(size_x, size_y);
    icon.SetPosX(pos_x);
    icon.SetPosY(pos_y);
    icon.SetPosEx(refresh);
#endif
    icon.InitEx(item, refresh);
    return icon;
  }
References GetGame().
Referenced by AddedToCargoEx(), and InitIcon().
IsDisplayable()
override bool Container::IsDisplayable () inline protected
Definition at line 17 of file ClosableContainer.c.
  {
    for (int i = 0; i < m_Body.Count(); i++)
    {
      LayoutHolder c = m_Body[i];
      if (c && c.IsDisplayable())
        return true;
    }
    return false;
  }
IsEmpty()
override bool Container::IsEmpty () inline protected
Definition at line 736 of file CargoContainer.c.
  {
    return m_Icons.Count() == 0;
  }
Referenced by AttachmentsWrapper::IsDisplayable(), AttachmentCategoriesContainer::IsDisplayable(), and IsItemWithQuantityActive().
IsItemActive()
override bool Container::IsItemActive () inline protected
Definition at line 716 of file CargoContainer.c.
  {
    if (GetFocusedIcon())
    {
      ItemBase item = ItemBase.Cast(GetFocusedIcon().GetObject());
      return (item != null);
    }
    return false;
  }
References GetFocusedIcon(), and GetObject().
IsItemWithQuantityActive()
override bool Container::IsItemWithQuantityActive () inline protected
Definition at line 726 of file CargoContainer.c.
  {
    if (GetFocusedIcon())
    {
      ItemBase item = ItemBase.Cast(GetFocusedIcon().GetObject());
      return (!IsEmpty() && QuantityConversions.HasItemQuantity(item) && item.CanBeSplit());
    }
    return false;
  }
References GetFocusedIcon(), GetObject(), QuantityConversions::HasItemQuantity(), and IsEmpty().
MoveContainerDown()
void Container::MoveContainerDown (Widget cont) inline protected
Definition at line 156 of file ClosableContainer.c.
  {
    if (m_Entity)
    {
      InventoryLocation loc = new InventoryLocation;
      m_Entity.GetInventory().GetCurrentInventoryLocation(loc);
      if (loc.IsValid())
      {
        int slot = loc.GetSlot();
        Inventory.MoveAttachmentDown(slot);
        UpdateSelectionIcons();
      }
    }
  }
References Inventory(), and m_Entity.
MoveContainerUp()
void Container::MoveContainerUp (Widget cont) inline protected
Definition at line 141 of file ClosableContainer.c.
  {
    if (m_Entity)
    {
      InventoryLocation loc = new InventoryLocation;
      m_Entity.GetInventory().GetCurrentInventoryLocation(loc);
      if (loc.IsValid())
      {
        int slot = loc.GetSlot();
        Inventory.MoveAttachmentUp(slot);
        UpdateSelectionIcons();
      }
    }
  }
References Inventory(), and m_Entity.
MovedInCargo()
void Container::MovedInCargo (EntityAI item) inline protected
Definition at line 144 of file CargoContainer.c.
  {
    InventoryLocation il = new InventoryLocation;
    item.GetInventory().GetCurrentInventoryLocation(il);
    int x = il.GetCol();
#ifdef PLATFORM_CONSOLE
    int y = il.GetRow() - 1;
#else
    int y = il.GetRow();
#endif
    if (m_ShowedItemPositions.Contains(item))
    {
      ref Param3<ref Icon, int, int> data = m_ShowedItemPositions.Get(item);
      if (data.param1)
      {
        if (data.param2 != x || data.param3 != y)
        {
          data.param2 = x;
          data.param3 = y;
#ifdef PLATFORM_CONSOLE
          data.param1.SetCargoPos(data.param3);
#endif
#ifdef PLATFORM_WINDOWS
          data.param1.SetPosX(data.param2);
          data.param1.SetPosY(data.param3);
#endif
        }
        data.param1.UpdateInterval();
      }
    }
    UpdateSelection();
  }
References UpdateSelection(), x, and y.
OnShow()
override void Container::OnShow () inline protected
Definition at line 87 of file ClosableContainer.c.
  {
    if (IsOpened())
      super.OnShow();
  }
References ClosableContainer::IsOpened().
Open()
override void Container::Open () inline protected
Definition at line 61 of file ClosableContainer.c.
  {
    if (IsDisplayable())
    {
      super.Open();
      ItemManager.GetInstance().SetDefaultOpenState(m_Entity.GetType(), true);
      SetOpenForSlotIcon(true);
      OnShow();
      m_Parent.m_Parent.Refresh();
    }
  }
References ItemManager::GetInstance(), ClosableContainer::IsDisplayable(), m_Entity, m_Parent, and OnShow().
Referenced by LayoutHolder::Toggle().
Refresh() [1/2]
override void Container::Refresh () inline protected
Definition at line 505 of file CargoContainer.c.
  {
#ifdef PLATFORM_CONSOLE
    if (!m_ResizeTimer)
      m_ResizeTimer = new Timer();
    if (m_ResizeTimer.IsRunning())
      m_ResizeTimer.Stop();
    m_ResizeTimer.Run(0.05, this, "RefreshImpl");
#endif
  }
Referenced by AddedToCargoEx(), LayoutHolder::Insert(), LayoutHolder::Remove(), RemovedFromCargo(), and SetEntity().
Refresh() [2/2]
override void Container::Refresh () inline protected
Definition at line 100 of file ClosableContainer.c.
  {
    if (!m_Closed)
      super.Refresh();
  }
RefreshImpl()
void Container::RefreshImpl () inline protected
Definition at line 516 of file CargoContainer.c.
  {
    UpdateRowVisibility(m_ShowedItemPositions.Count());
    UpdateSelection();
  }
References UpdateRowVisibility(), and UpdateSelection().
ReleaseLock()
void Container::ReleaseLock (EntityAI item) inline protected
Definition at line 199 of file CargoContainer.c.
  {
#ifndef PLATFORM_CONSOLE
    if (m_ShowedLockPositions.Contains(item))
    {
      Icon ic = m_ShowedLockPositions.Get(item).param1;
      m_Icons.RemoveItem(ic);
      m_ShowedLockPositions.Remove(item);
      item.GetOnReleaseLock().Remove(ReleaseLock);
    }
#endif
  }
RemovedFromCargo()
void Container::RemovedFromCargo (EntityAI item) inline protected
Definition at line 115 of file CargoContainer.c.
  {
    Param3<ref Icon, int, int> data = m_ShowedItemPositions.Get(item);
    if (data)
    {
      m_Icons.RemoveItem(data.param1);
      m_ShowedItemPositions.Remove(item);
    }
    UpdateHeaderText();
#ifdef PLATFORM_CONSOLE
    for (int i = 0; i < m_Cargo.GetItemCount(); i++)
    {
      EntityAI item2 = m_Cargo.GetItem(i);
      data = m_ShowedItemPositions.Get(item2);
      if (data && data.param1)
      {
        data.param1.SetCargoPos(i);
        data.param1.SetPos();
      }
    }
    m_FocusedItemPosition = Math.Min(m_ShowedItemPositions.Count() - 1, m_FocusedItemPosition);
    Refresh();
#endif
  }
References CargoBase::GetItem(), CargoBase::GetItemCount(), Math::Min(), Refresh(), and UpdateHeaderText().
Select()
override bool Container::Select () inline protected
Definition at line 833 of file CargoContainer.c.
  {
    EntityAI focused_item = GetFocusedItem();
    EntityAI selected_item = ItemManager.GetInstance().GetSelectedItem();
    DayZPlayer player = GetGame().GetPlayer();
    if (focused_item != selected_item)
    {
      if (selected_item)
      {
        if (selected_item.GetInventory().CanRemoveEntity() && m_Entity)
        {
          bool can_add = m_Entity.GetInventory().CanAddEntityInCargo(selected_item, selected_item.GetInventory().GetFlipCargo());
          bool in_cargo = !player.GetInventory().HasEntityInInventory(selected_item) || !m_Entity.GetInventory().HasEntityInCargo(selected_item);
          if (can_add && in_cargo)
          {
            player.PredictiveTakeEntityToTargetCargo(m_Entity, selected_item);
            Container selected_cont2 = ItemManager.GetInstance().GetSelectedContainer();
            if (selected_cont2)
              selected_cont2.SetActive(false);
            SetActive(true);
            m_FocusedItemPosition = 0;
            return true;
          }
          else
          {
            Container selected_cont = ItemManager.GetInstance().GetSelectedContainer();
            if (selected_cont)
              selected_cont.SetActive(false);
            SetActive(true);
            SetDefaultFocus(true);
          }
        }
      }
      else if (focused_item && focused_item.GetInventory().CanRemoveEntity())
      {
        EntityAI item_in_hands = GetGame().GetPlayer().GetHumanInventory().GetEntityInHands();
        if (item_in_hands)
        {
          if (GameInventory.CanSwapEntitiesEx(item_in_hands, focused_item))
          {
            player.PredictiveSwapEntities(item_in_hands, focused_item);
            return true;
          }
        }
        else
        {
          if (player.GetHumanInventory().CanAddEntityInHands(focused_item))
          {
            player.PredictiveTakeEntityToHands(focused_item);
            return true;
          }
        }
      }
    }
    return false;
  }
References GameInventory::CanSwapEntitiesEx(), GetFocusedItem(), GetGame(), ItemManager::GetInstance(), m_Entity, SetActive(), and SetDefaultFocus().
Referenced by HandsContainer::OnSelectButton().
SelectItem()
override bool Container::SelectItem () inline protected
Definition at line 818 of file CargoContainer.c.
  {
    Icon focused_item = GetFocusedIcon();
    if (focused_item)
    {
      ItemBase item = ItemBase.Cast(focused_item.GetObject());
      if (item && item.IsTakeable() && item.CanPutIntoHands(null))
      {
        ItemManager.GetInstance().SetSelectedItemEx(item, this, focused_item);
        return true;
      }
    }
    return false;
  }
References GetFocusedIcon(), and ItemManager::GetInstance().
SetActive()
override void Container::SetActive (bool active) inline protected
Definition at line 710 of file CargoContainer.c.
  {
    super.SetActive(active);
    UpdateSelection();
  }
References UpdateSelection().
SetAlternateFalseTextHeaderWidget()
void Container::SetAlternateFalseTextHeaderWidget (TextWidget w) inline protected
Definition at line 918 of file CargoContainer.c.
  {
    bool update = !m_AlternateFalseHeaderTextWidget;
    m_AlternateFalseHeaderTextWidget = w;
    if (update)
      UpdateHeaderText();
  }
References m_AlternateFalseHeaderTextWidget, and UpdateHeaderText().
SetDefaultFocus()
override void Container::SetDefaultFocus (bool while_micromanagment_mode = false) inline protected
Definition at line 589 of file CargoContainer.c.
  {
    super.SetDefaultFocus(while_micromanagment_mode);
    Unfocus();
    m_FocusedItemPosition = 0;
    UpdateSelection();
  }
References Unfocus(), and UpdateSelection().
Referenced by Select(), LayoutHolder::SetActive(), LayoutHolder::SetFirstActive(), and SetLastFocus().
SetEntity()
void Container::SetEntity (EntityAI item, int cargo_index = 0, bool immedUpdate = true) inline protected
Definition at line 239 of file CargoContainer.c.
  {
    if (item)
    {
      m_Entity = item;
      m_Cargo = item.GetInventory().GetCargoFromIndex(cargo_index);
      m_CargoIndex = cargo_index;
      m_Entity.GetOnItemAddedIntoCargo().Insert(AddedToCargo);
      m_Entity.GetOnItemRemovedFromCargo().Insert(RemovedFromCargo);
      m_Entity.GetOnItemMovedInCargo().Insert(MovedInCargo);
      m_Entity.GetOnSetLock().Insert(SetLock);
      m_Entity.GetOnReleaseLock().Insert(ReleaseLock);
      if (immedUpdate)
        UpdateHeaderText();
      InitGridHeight();
      m_MainWidget = m_ItemsContainer;
      if (m_Cargo)
      {
        int i;
        int prev_count = m_ShowedItemPositions.Count();
        //START - Add new item Icons
        for (i = 0; i < m_Cargo.GetItemCount(); i++)
        {
          EntityAI cargo_item = m_Cargo.GetItem(i);
          if (cargo_item)
            AddedToCargoEx(cargo_item, immedUpdate);
        }
#ifdef PLATFORM_CONSOLE
        if (immedUpdate)
          Refresh();
#endif
      }
    }
  }
References AddedToCargoEx(), CargoBase::GetItem(), CargoBase::GetItemCount(), InitGridHeight(), m_Entity, m_ItemsContainer, Refresh(), SetLock(), and UpdateHeaderText().
SetLastActive()
override void Container::SetLastActive () inline protected
Definition at line 701 of file CargoContainer.c.
  {
    super.SetLastActive();
    if (GetFocusedIcon())
      GetFocusedIcon().SetActive(false);
    m_FocusedItemPosition = ((m_Rows.Count() - 1) * ROWS_NUMBER_XBOX);
    UpdateSelection();
  }
References GetFocusedIcon(), Icon::SetActive(), and UpdateSelection().
Referenced by AttachmentsGroupContainer::SetPreviousActive(), and LayoutHolder::SetPreviousActive().
SetLastFocus()
override void Container::SetLastFocus () inline protected
Definition at line 598 of file CargoContainer.c.
  {
    SetDefaultFocus();
  }
References SetDefaultFocus().
Referenced by LayoutHolder::SetLastActive().
SetLayoutName() [1/2]
override void Container::SetLayoutName () inline protected
Definition at line 212 of file CargoContainer.c.
  {
#ifdef PLATFORM_CONSOLE
    m_LayoutName = WidgetLayoutName.CargoContainerXbox;
#else
    switch (InventoryMenu.GetWidthType())
    {
    case ScreenWidthType.NARROW:
    {
      m_LayoutName = WidgetLayoutName.CargoContainerNarrow;
      break;
    }
    case ScreenWidthType.MEDIUM:
    {
      m_LayoutName = WidgetLayoutName.CargoContainerMedium;
      break;
    }
    case ScreenWidthType.WIDE:
    {
      m_LayoutName = WidgetLayoutName.CargoContainerWide;
      break;
    }
    }
#endif
  }
References WidgetLayoutName::CargoContainerMedium, WidgetLayoutName::CargoContainerNarrow, WidgetLayoutName::CargoContainerWide, WidgetLayoutName::CargoContainerXbox, and InventoryMenu().
SetLayoutName() [2/2]
override void Container::SetLayoutName () inline protected
Definition at line 82 of file ClosableContainer.c.
  {
    m_LayoutName = WidgetLayoutName.ClosableContainer;
  }
References WidgetLayoutName::ClosableContainer.
SetLock()
void Container::SetLock (EntityAI item) inline protected
Definition at line 178 of file CargoContainer.c.
  {
#ifndef PLATFORM_CONSOLE
    if (GetGame().GetPlayer())
    {
      InventoryLocation il = new InventoryLocation;
      int index = GetGame().GetPlayer().GetHumanInventory().FindUserReservedLocationIndex(item);
      if (index >= 0)
      {
        GetGame().GetPlayer().GetHumanInventory().GetUserReservedLocation(index, il);
        ref Icon icon = new Icon(this, false);
        m_Icons.Insert(icon);
        icon.InitLock(m_Entity, item, il.GetCol(), il.GetRow(), il.GetFlip());
        m_ShowedLockPositions.Insert(item, new Param3<ref Icon, int, int>(icon, 1, 1));
        item.GetOnReleaseLock().Insert(ReleaseLock);
      }
    }
#endif
  }
References GetGame(), GetPlayer(), and m_Entity.
SetNextActive()
override void Container::SetNextActive () inline protected
Definition at line 620 of file CargoContainer.c.
  {
    Unfocus();
    int focused_row = m_FocusedItemPosition / ROWS_NUMBER_XBOX;
    int max_row = (m_Icons.Count() - 1) / ROWS_NUMBER_XBOX;
    if (max_row > focused_row)
    {
      m_FocusedItemPosition += ROWS_NUMBER_XBOX;
      if (m_FocusedItemPosition >= m_Icons.Count())
        m_FocusedItemPosition = m_Icons.Count() - 1;
      UpdateSelection();
    }
    else
      SetActive(false);
  }
References ROWS_NUMBER_XBOX, SetActive(), Unfocus(), and UpdateSelection().
Referenced by LayoutHolder::MoveGridCursor().
SetNextLeftActive()
override void Container::SetNextLeftActive () inline protected
Definition at line 672 of file CargoContainer.c.
  {
    if (m_Icons.Count() > 0)
    {
      Unfocus();
      int focused_row = m_FocusedItemPosition / ROWS_NUMBER_XBOX;
      int row_min = focused_row * ROWS_NUMBER_XBOX;
      int row_max = row_min + ROWS_NUMBER_XBOX - 1;
      if (row_max >= m_Icons.Count())
        row_max = m_Icons.Count() - 1;
      m_FocusedItemPosition--;
      if (m_FocusedItemPosition < row_min)
        m_FocusedItemPosition = row_max;
      UpdateSelection();
    }
  }
References ROWS_NUMBER_XBOX, Unfocus(), and UpdateSelection().
Referenced by LayoutHolder::MoveGridCursor().
SetNextRightActive()
override void Container::SetNextRightActive () inline protected
Definition at line 652 of file CargoContainer.c.
  {
    if (m_Icons.Count() > 0)
    {
      Unfocus();
      int focused_row = m_FocusedItemPosition / ROWS_NUMBER_XBOX;
      int row_min = focused_row * ROWS_NUMBER_XBOX;
      int row_max = row_min + ROWS_NUMBER_XBOX - 1;
      if (row_max >= m_Icons.Count())
        row_max = m_Icons.Count() - 1;
      m_FocusedItemPosition++;
      if (m_FocusedItemPosition > row_max)
        m_FocusedItemPosition = row_min;
      UpdateSelection();
    }
  }
References ROWS_NUMBER_XBOX, Unfocus(), and UpdateSelection().
Referenced by LayoutHolder::MoveGridCursor().
SetOpenState()
void Container::SetOpenState (bool state) inline protected
Definition at line 46 of file ClosableContainer.c.
  {
    ItemManager.GetInstance().SetDefaultOpenState(m_Entity.GetType(), state);
    m_Closed = !state;
    if (!m_Closed)
      OnShow();
    else
      OnHide();
  }
References ItemManager::GetInstance(), m_Entity, OnHide(), and OnShow().
SetPreviousActive()
override void Container::SetPreviousActive (bool force = false) inline protected
Definition at line 637 of file CargoContainer.c.
  {
    Unfocus();
    int focused_row = m_FocusedItemPosition / ROWS_NUMBER_XBOX;
    if (focused_row > 0)
    {
      m_FocusedItemPosition = m_FocusedItemPosition - ROWS_NUMBER_XBOX;
      UpdateSelection();
    }
    else
      SetActive(false);
  }
References ROWS_NUMBER_XBOX, SetActive(), Unfocus(), and UpdateSelection().
Referenced by LayoutHolder::MoveGridCursor(), and LayoutHolder::Remove().
ShowFalseCargoHeader()
void Container::ShowFalseCargoHeader (bool show) inline protected
Definition at line 913 of file CargoContainer.c.
  {
    m_CargoHeader.Show(show);
  }
SplitItem()
override bool Container::SplitItem () inline protected
Definition at line 778 of file CargoContainer.c.
  {
    if (CanSplit())
    {
      if (GetFocusedIcon())
      {
        ItemBase entity = ItemBase.Cast(GetFocusedIcon().GetObject());
        if (entity)
        {
          if (entity.HasQuantity() && entity.CanBeSplit())
          {
            entity.OnRightClick();
            Icon icon = m_ShowedItemPositions.Get(entity).param1;
            if (icon)
              icon.SetQuantity();
          }
        }
      }
    }
    return false;
  }
References GetFocusedIcon(), and GetObject().
TransferItem()
override bool Container::TransferItem () inline protected
Definition at line 761 of file CargoContainer.c.
  {
    if (CanTakeToInventory())
    {
      if (GetFocusedIcon())
      {
        EntityAI entity = EntityAI.Cast(GetFocusedIcon().GetObject());
        if (entity)
        {
          GetGame().GetPlayer().PredictiveTakeEntityToInventory(FindInventoryLocationType.CARGO, entity);
          return true;
        }
      }
    }
    return false;
  }
References GetFocusedIcon(), GetGame(), and GetObject().
TransferItemToVicinity()
override bool Container::TransferItemToVicinity () inline protected
Definition at line 568 of file CargoContainer.c.
  {
    if (CanDrop())
    {
      Man player = GetGame().GetPlayer();
      if (GetFocusedIcon())
      {
        ItemBase item = ItemBase.Cast(GetFocusedIcon().GetObject());
        if (item && player.CanDropEntity(item))
        {
          if (item.GetTargetQuantityMax() < item.GetQuantity())
            item.SplitIntoStackMaxClient(null, -1);
          else
            player.PhysicalPredictiveDropItem(item);
          return true;
        }
      }
    }
    return false;
  }
References GetFocusedIcon(), GetGame(), and GetObject().
Unfocus()
override void Container::Unfocus () inline protected
Definition at line 603 of file CargoContainer.c.
  {
    Icon icon = GetFocusedIcon();
    if (icon)
      icon.SetActive(false);
  }
References GetFocusedIcon().
Referenced by LayoutHolder::SetActive(), SetDefaultFocus(), SetNextActive(), SetNextLeftActive(), SetNextRightActive(), and SetPreviousActive().
UnfocusAll()
override void Container::UnfocusAll () inline protected
Definition at line 610 of file CargoContainer.c.
  {
    if (m_Icons)
    {
      foreach (Icon icon : m_Icons)
        icon.SetActive(false);
    }
    m_FocusedItemPosition = 0;
  }
References m_Icons.
UpdateHeaderText()
void Container::UpdateHeaderText () inline protected
Definition at line 285 of file CargoContainer.c.
  {
    Widget header;
    string name = m_Entity.GetDisplayName();
    name.ToUpper();
    if (m_Entity.CanDisplayCargo() && m_Entity.GetInventory().GetCargoFromIndex(m_CargoIndex))
    {
      name = name + " (" + GetCargoCapacity().ToString() + "/" + GetMaxCargoCapacity() + ")";
      if (m_IsAttachment && m_CargoHeader)
      {
        m_FalseHeaderTextWidget.SetText(name);
        float x, y;
        m_FalseHeaderTextWidget.Update();
        m_FalseHeaderTextWidget.GetScreenSize(x, y);
        m_CargoHeader.FindAnyWidget("grid_container_header").SetSize(1, y + InventoryMenu.GetHeightMultiplied(10));
        m_CargoHeader.Update();
        if (m_AlternateFalseHeaderTextWidget)
          m_AlternateFalseHeaderTextWidget.SetText(name);
        return;
      }
    }
    if (Container.Cast(GetParent()) && Container.Cast(GetParent()).GetHeader())
      Container.Cast(GetParent()).GetHeader().SetName(name);
  }
References GetCargoCapacity(), GetHeader(), GetMaxCargoCapacity(), GetParent(), InventoryMenu(), m_Entity, name, x, and y.
Referenced by AddedToCargoEx(), RemovedFromCargo(), SetAlternateFalseTextHeaderWidget(), and SetEntity().
UpdateInterval()
override void Container::UpdateInterval () inline protected
Definition at line 522 of file CargoContainer.c.
  {
    foreach (Param3<ref Icon, int, int> data : m_ShowedItemPositions)
    {
      if (data.param1)
        data.param1.UpdateInterval();
    }
  }
References m_ShowedItemPositions.
UpdateRadialIcon()
override void Container::UpdateRadialIcon () inline protected
Definition at line 28 of file ClosableContainer.c.
  {
    if (m_SlotIcon)
    {
      bool show_radial_icon;
      show_radial_icon = IsOpened();
      show_radial_icon = show_radial_icon && ((m_Entity.GetInventory().GetCargo() && m_Entity.CanDisplayCargo()) || m_Entity.GetSlotsCountCorrect() > 0);
      show_radial_icon = show_radial_icon && !m_Entity.GetInventory().IsInventoryLockedForLockType(HIDE_INV_FROM_SCRIPT);
      if (IsDisplayable())
      {
        m_SlotIcon.GetRadialIconPanel().Show(true);
        SetOpenForSlotIcon(show_radial_icon);
      }
      else
        m_SlotIcon.GetRadialIconPanel().Show(false);
    }
  }
References ClosableContainer::IsDisplayable(), ClosableContainer::IsOpened(), and m_Entity.
Referenced by Attachments::UpdateInterval().
UpdateRowVisibility()
void Container::UpdateRowVisibility (int count) inline protected
Definition at line 473 of file CargoContainer.c.
  {
    int i;
    int rows = Math.Max(1, Math.Ceil((count + 1) / ROWS_NUMBER_XBOX));
    int diff = rows - m_Rows.Count();
    if (diff < 0)
    {
      for (i = m_Rows.Count() - 1; i >= rows; i--)
        m_Rows.Remove(i);
    }
    else if (diff > 0)
    {
      m_MainWidget = m_CargoContainer;
      for (i = m_Rows.Count(); i < rows; i++)
      {
        ref CargoContainerRow row = new CargoContainerRow(this);
        row.SetNumber(i);
        row.SetEntity(m_Entity);
        row.GetRootWidget().SetSort(i);
        m_Rows.Insert(row);
      }
      m_MainWidget = m_ItemsContainer;
    }
    m_Resizer2.ResizeParentToChild();
#ifndef PLATFORM_CONSOLE
    m_Resizer1.ResizeParentToChild();
#endif
  }
References Math::Ceil(), m_CargoContainer, m_Entity, m_ItemsContainer, and Math::Max().
Referenced by RefreshImpl().
UpdateSelection()
void Container::UpdateSelection () inline protected
Definition at line 458 of file CargoContainer.c.
  {
    if (m_IsActive)
    {
      if (m_FocusedItemPosition >= m_Icons.Count())
        m_FocusedItemPosition = m_Icons.Count() - 1;
      Icon icon = GetIcon(m_FocusedItemPosition);
      if (icon && !icon.IsActive())
      {
        icon.SetActive(true);
        Inventory.GetInstance().UpdateConsoleToolbar();
      }
    }
  }
References GetIcon(), Inventory(), and m_IsActive.
Referenced by MovedInCargo(), RefreshImpl(), SetActive(), SetDefaultFocus(), SetLastActive(), SetNextActive(), SetNextLeftActive(), SetNextRightActive(), and SetPreviousActive().
UpdateSize()
void Container::UpdateSize () inline protected
Definition at line 357 of file CargoContainer.c.
  {
#ifndef PLATFORM_CONSOLE
    m_Resizer1.ResizeParentToChild();
#else
    m_Resizer2.ResizeParentToChild();
#endif
  }
Member Data Documentation
m_AlternateFalseHeaderTextWidget
TextWidget Container::m_AlternateFalseHeaderTextWidget protected
Definition at line 20 of file CargoContainer.c.
Referenced by SetAlternateFalseTextHeaderWidget().
m_Cargo
CargoBase Container::m_Cargo protected
Definition at line 6 of file CargoContainer.c.
m_CargoContainer
Widget Container::m_CargoContainer protected
Definition at line 22 of file CargoContainer.c.
Referenced by CargoContainer(), and UpdateRowVisibility().
m_CargoHeader
Widget Container::m_CargoHeader protected
Definition at line 21 of file CargoContainer.c.
m_CargoIndex
int Container::m_CargoIndex = -1 protected
Definition at line 7 of file CargoContainer.c.
Referenced by GetCargoIndex().
m_ClosableHeader
ref ClosableHeader Container::m_ClosableHeader protected
Definition at line 3 of file ClosableContainer.c.
m_FalseHeaderTextWidget
TextWidget Container::m_FalseHeaderTextWidget protected
Definition at line 19 of file CargoContainer.c.
m_FocusedItemPosition
int Container::m_FocusedItemPosition = -1 protected
Definition at line 9 of file CargoContainer.c.
m_Icons
ref array<ref Icon> Container::m_Icons protected
Definition at line 11 of file CargoContainer.c.
Referenced by UnfocusAll().
m_IconSize
float Container::m_IconSize protected
Definition at line 15 of file CargoContainer.c.
Referenced by GetIconSize().
m_IsAttachment
bool Container::m_IsAttachment protected
Definition at line 18 of file CargoContainer.c.
m_ItemsContainer
Widget Container::m_ItemsContainer protected
Definition at line 23 of file CargoContainer.c.
Referenced by SetEntity(), and UpdateRowVisibility().
m_LockCargo
bool Container::m_LockCargo protected
Definition at line 4 of file ClosableContainer.c.
m_Resizer1
ref SizeToChild Container::m_Resizer1 protected
Definition at line 25 of file CargoContainer.c.
m_Resizer2
ref SizeToChild Container::m_Resizer2 protected
Definition at line 27 of file CargoContainer.c.
m_ResizeTimer
ref Timer Container::m_ResizeTimer protected
Definition at line 28 of file CargoContainer.c.
m_Rows
ref array<ref CargoContainerRow> Container::m_Rows protected
Definition at line 10 of file CargoContainer.c.
m_ShowedItemPositions
ref map<EntityAI, ref Param3<ref Icon, int, int> > Container::m_ShowedItemPositions protected
Definition at line 12 of file CargoContainer.c.
Referenced by UpdateInterval().
m_ShowedLockPositions
ref map<EntityAI, ref Param3<ref Icon, int, int> > Container::m_ShowedLockPositions protected
Definition at line 13 of file CargoContainer.c.
m_SpaceSize
float Container::m_SpaceSize protected
Definition at line 16 of file CargoContainer.c.
Referenced by GetSpaceSize().
ROWS_NUMBER_XBOX
const int Container::ROWS_NUMBER_XBOX = 5 protected
Definition at line 4 of file CargoContainer.c.
Referenced by SetNextActive(), SetNextLeftActive(), SetNextRightActive(), and SetPreviousActive().
The documentation for this class was generated from the following files:
scripts/5_Mission/GUI/InventoryNew/ContainedItems/CargoContainer.c
scripts/5_Mission/GUI/InventoryNew/Containers/ClosableContainer.c