DayZ: ActionLoadMagazine Class Reference
ActionLoadMagazine Class Reference
Private Member Functions
void ActionLoadMagazine ()
override bool HasProneException ()
override void CreateConditionComponents ()
bool CanLoadMagazine (ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanBePerformedFromQuickbar ()
override void OnExecuteServer (ActionData action_data)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 9 of file ActionLoadMagazine.c.
Constructor & Destructor Documentation
ActionLoadMagazine()
void ActionLoadMagazine::ActionLoadMagazine () inline private
Definition at line 11 of file ActionLoadMagazine.c.
  {
    m_CallbackClass = ActionLoadMagazineCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_FILLMAG;
    m_CommandUIDProne = DayZPlayerConstants.CMD_ACTIONFB_FILLMAG;
    m_Text = "#load_magazine";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionLoadMagazine::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 42 of file ActionLoadMagazine.c.
  {
    return CanLoadMagazine(target, item);
  }
References CanLoadMagazine().
ActionConditionContinue()
override bool ActionLoadMagazine::ActionConditionContinue (ActionData action_data) inline private
Definition at line 37 of file ActionLoadMagazine.c.
  {
    return CanLoadMagazine(action_data.m_Target, action_data.m_MainItem);
  }
References CanLoadMagazine().
CanBePerformedFromQuickbar()
override bool ActionLoadMagazine::CanBePerformedFromQuickbar () inline private
Definition at line 47 of file ActionLoadMagazine.c.
  {
    return true;
  }
CanLoadMagazine()
bool ActionLoadMagazine::CanLoadMagazine (ActionTarget target, ItemBase item) inline private
Definition at line 30 of file ActionLoadMagazine.c.
  {
    Magazine trg;
    Magazine itm;
    return (Class.CastTo(trg, target.GetObject()) && Class.CastTo(itm, item) && itm.GetAmmoCount() < itm.GetAmmoMax() && trg.GetAmmoCount() != 0 && itm.IsCompatiableAmmo(trg));
  }
References Class::CastTo().
Referenced by ActionCondition(), and ActionConditionContinue().
CreateConditionComponents()
override void ActionLoadMagazine::CreateConditionComponents () inline private
Definition at line 24 of file ActionLoadMagazine.c.
  {
    m_ConditionItem = new CCINonRuined();
    m_ConditionTarget = new CCTNonRuined(UAMaxDistances.DEFAULT);
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
HasProneException()
override bool ActionLoadMagazine::HasProneException () inline private
Definition at line 19 of file ActionLoadMagazine.c.
  {
    return true;
  }
OnExecuteServer()
override void ActionLoadMagazine::OnExecuteServer (ActionData action_data) inline private
Definition at line 52 of file ActionLoadMagazine.c.
  {
    //Param1<float> timeSpendParam;
    //if( !Class.CastTo(timeSpendParam, action_data.m_ActionComponent.GetACData()) ) return;
    Magazine trg;
    Magazine itm;
    if (Class.CastTo(trg, action_data.m_Target.GetObject()) && Class.CastTo(itm, action_data.m_MainItem))
    {
      float dmg;
      string ammoType;
      if (trg.ServerAcquireCartridge(dmg, ammoType))
      {
        if (!itm.ServerStoreCartridge(dmg, ammoType))
          trg.ServerStoreCartridge(dmg, ammoType);
        else
          itm.ApplyManipulationDamage(); //damages magazine
      }
      trg.SetSynchDirty();
      itm.SetSynchDirty();
      //manipulationDamage
      //if(trg.GetAmmoCount() > 0 )
      //trg.SetSynchDirty();
      //itm.SetSynchDirty();
    }
  }
References Class::CastTo().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionLoadMagazine.c