DayZ: PPEColors Class Reference
PPEColors Class Reference
Colors - PostProcessEffectType.Colors.
Private Member Functions
override int GetPostProcessEffectID ()
override string GetDefaultMaterialPath ()
override void RegisterMaterialParameters ()
Private Member Functions inherited from PPEClassBase
void PPEClassBase (string mat_path_override="")
void Init (string mat_path_override="")
void CreateMaterial ()
Material GetMaterial ()
void CreateDataStructure ()
void RegisterMaterialParameters ()
inserted into associative array by parameter int value, parameter registration order does not matter (still ordered, though)
void RegisterParameterScalarBool (int idx, string parameter_name, bool default_value)
void RegisterParameterScalarInt (int idx, string parameter_name, int default_value, int min, int max)
void RegisterParameterScalarFloat (int idx, string parameter_name, float default_value, float min, float max)
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
void RegisterParameterScalarFloatEx (int idx, string parameter_name, float default_value, float min, float max, typename type)
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
void RegisterParameterColor (int idx, string parameter_name, float r, float g, float b, float a)
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
void RegisterParameterColorEx (int idx, string parameter_name, float r, float g, float b, float a, typename type)
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
void RegisterParameterVector (int idx, string parameter_name, array< float > default_values)
void RegisterParameterTexture (int idx, string parameter_name, string default_path)
void RegisterParameterResource (int idx, string parameter_name, string default_path)
void InsertParamValueData (PPERequestParamDataBase request_data)
Distributes requester data to the material class structure and links them to appropriate parameter.
void RemoveRequest (int req_idx)
unused, see 'RemoveActiveRequestFromMaterials' for more info
void OnUpdate (float timeslice, int order)
generic update method, take care when overriding!
void SetFinalParameterValue (int parameter_idx)
Clamps the values being set to defaults, if there is no request setting non-zero values on the parameter.
void ApplyValueChanges ()
void InsertUpdatedParameter (int mat_id)
void ParamUpdateRemove (int parameter_idx)
Queue selected parameter for removal from the update queue.
void SetParameterUpdating (int order, int parameter_id)
Queue specific parameter of this material to update.
void ParamUpdateQueueCleanup (int order)
string GetDefaultMaterialPath ()
override this if you want to use different path by default; '.emat' is appended automatically
void ChangeMaterialPathUsed (string path)
string GetCurrentMaterialPath ()
int GetPostProcessEffectID ()
Overriden in all material classes!
PPEMatClassParameterCommandData GetParameterCommandData (int parameter_idx)
Some PP effects are handled as hard-coded exceptions, outside of material system. Default == PPEExceptions.NONE (systemic behaviour)
void DbgPrnt (string text)
Static Private Attributes
static const int PARAM_BRIGHTNESS = 0
static const int PARAM_CONTRAST = 1
static const int PARAM_OFFSET = 2
static const int PARAM_OVERLAYFACTOR = 3
static const int PARAM_OVERLAYCOLOR = 4
static const int PARAM_SATURATION = 5
static const int PARAM_COLORIZATIONCOLOR = 6
static const int PARAM_DESATURATIONWEIGHTS = 7
Additional Inherited Members
Private Attributes inherited from PPEClassBase
PPEManager m_Manager
string m_MaterialPath = ""
Material m_Material
ref map< int, ref array< int > > m_ParameterUpdateQueueMap
ref array< int > m_ParameterRemovalQueue
ref array< int > m_UpdatedParameters
ref map< int, ref PPEMatClassParameterCommandData > m_MaterialParamMapStructure
Detailed Description
Colors - PostProcessEffectType.Colors.
Definition at line 3 of file PPEColors.c.
Member Function Documentation
GetDefaultMaterialPath()
override string PPEColors::GetDefaultMaterialPath () inline private
Definition at line 19 of file PPEColors.c.
  {
    return "Graphics/Materials/postprocess/colors";
  }
GetPostProcessEffectID()
override int PPEColors::GetPostProcessEffectID () inline private
Definition at line 14 of file PPEColors.c.
  {
    return PostProcessEffectType.Colors;
  }
RegisterMaterialParameters()
override void PPEColors::RegisterMaterialParameters () inline private
Definition at line 24 of file PPEColors.c.
  {
    RegisterParameterScalarFloat(PARAM_BRIGHTNESS, "Brightness", 1, 0, 2);
    RegisterParameterScalarFloat(PARAM_CONTRAST, "Contrast", 1, 0, 2);
    RegisterParameterScalarFloat(PARAM_OFFSET, "Offset", 0, -1, 1);
    RegisterParameterScalarFloat(PARAM_OVERLAYFACTOR, "OverlayFactor", 0, 0, 1);
    RegisterParameterColor(PARAM_OVERLAYCOLOR, "OverlayColor", 1, 1, 1, 0);
    RegisterParameterScalarFloatEx(PARAM_SATURATION, "Saturation", 1, 0, 1, PPEMatClassParameterFloatSaturation);
    RegisterParameterColorEx(PARAM_COLORIZATIONCOLOR, "ColorizationColor", 1.0, 1.0, 1.0, 0.0, PPEMatClassParameterColorColorization);
    RegisterParameterVector(PARAM_DESATURATIONWEIGHTS, "DesaturationWeights", {0.299, 0.587, 0.114, 0});
  }
References PARAM_BRIGHTNESS, PARAM_COLORIZATIONCOLOR, PARAM_CONTRAST, PARAM_DESATURATIONWEIGHTS, PARAM_OFFSET, PARAM_OVERLAYCOLOR, PARAM_OVERLAYFACTOR, PARAM_SATURATION, PPEMatClassParameterFloatSaturation(), PPEClassBase::RegisterParameterColor(), PPEClassBase::RegisterParameterColorEx(), PPEClassBase::RegisterParameterScalarFloat(), PPEClassBase::RegisterParameterScalarFloatEx(), and PPEClassBase::RegisterParameterVector().
Member Data Documentation
PARAM_BRIGHTNESS
const int PPEColors::PARAM_BRIGHTNESS = 0 static private
Definition at line 5 of file PPEColors.c.
Referenced by RegisterMaterialParameters().
PARAM_COLORIZATIONCOLOR
const int PPEColors::PARAM_COLORIZATIONCOLOR = 6 static private
Definition at line 11 of file PPEColors.c.
Referenced by RegisterMaterialParameters().
PARAM_CONTRAST
const int PPEColors::PARAM_CONTRAST = 1 static private
Definition at line 6 of file PPEColors.c.
Referenced by RegisterMaterialParameters().
PARAM_DESATURATIONWEIGHTS
const int PPEColors::PARAM_DESATURATIONWEIGHTS = 7 static private
Definition at line 12 of file PPEColors.c.
Referenced by RegisterMaterialParameters().
PARAM_OFFSET
const int PPEColors::PARAM_OFFSET = 2 static private
Definition at line 7 of file PPEColors.c.
Referenced by RegisterMaterialParameters().
PARAM_OVERLAYCOLOR
const int PPEColors::PARAM_OVERLAYCOLOR = 4 static private
Definition at line 9 of file PPEColors.c.
Referenced by RegisterMaterialParameters().
PARAM_OVERLAYFACTOR
const int PPEColors::PARAM_OVERLAYFACTOR = 3 static private
Definition at line 8 of file PPEColors.c.
Referenced by RegisterMaterialParameters().
PARAM_SATURATION
const int PPEColors::PARAM_SATURATION = 5 static private
Definition at line 10 of file PPEColors.c.
Referenced by RegisterMaterialParameters().
The documentation for this class was generated from the following file:
scripts/3_Game/PPEManager/Materials/MatClasses/PPEColors.c