DayZ: PlayerSpawnHandler Class Reference
PlayerSpawnHandler Class Reference
Static Private Member Functions
static bool LoadData ()
static bool IsInitialized ()
static PlayerSpawnPreset GetRandomCharacterPreset ()
static bool ProcessEquipmentData (PlayerBase player, PlayerSpawnPreset data)
equips character with the chosen preset
static void ProcessSlotsEquipment (PlayerBase player, PlayerSpawnPreset data)
iterates over each object and spawns alternatives
static bool SelectAndSpawnSlotEquipment (PlayerBase player, PlayerSpawnPresetSlotData slotData)
selects weighted slot equipment variant
static void ProcessCargoEquipment (PlayerBase player, PlayerSpawnPreset data)
chooses one object from the array
static bool SelectAndSpawnCargoSet (PlayerBase player, PlayerSpawnPreset data)
static bool SpawnDiscreteCargoItemSet (PlayerBase player, PlayerSpawnPresetDiscreteCargoSetData csd)
static bool SpawnDiscreteSlotItemSet (PlayerBase player, PlayerSpawnPresetDiscreteItemSetSlotData dis, int slotID)
static bool SpawnComplexChildrenItems (EntityAI parent, notnull PlayerSpawnPresetItemSetBase data)
could spawn other items recursively. Parent item is guaranteed here.
static bool SpawnSimpleChildrenItems (EntityAI parent, PlayerSpawnPresetItemSetBase data)
static void HandleNewItem (notnull ItemBase item, PlayerSpawnPresetItemSetBase data)
static EntityAI CreateChildItem (EntityAI parent, string type)
static void ApplyAttributes (ItemBase item, PlayerSpawnAttributesData attributes)
Static Private Attributes
static bool m_Initialized
static ref PlayerSpawnJsonData m_Data = new PlayerSpawnJsonData()
Detailed Description
Definition at line 1 of file CfgPlayerSpawnHandler.c.
Member Function Documentation
ApplyAttributes()
static void PlayerSpawnHandler::ApplyAttributes (ItemBase item, PlayerSpawnAttributesData attributes) inline static private
Definition at line 273 of file CfgPlayerSpawnHandler.c.
  {
    if (!attributes)
      return;
    float health01 = Math.RandomFloatInclusive(attributes.healthMin, attributes.healthMax);
    item.SetHealth01("", "Health", health01);
    float quantity01 = Math.RandomFloatInclusive(attributes.quantityMin, attributes.quantityMax);
    if (item.IsMagazine())
    {
      Magazine mag = Magazine.Cast(item);
      //todo: magazine bullet customization?
      /*if (attributes.magazineAmmoOrdered && attributes.magazineAmmoOrdered.Count() > 0)
        {
        mag.ServerSetAmmoCount(0);
        foreach (string bulletType : attributes.magazineAmmoOrdered)
        {
          mag.ServerStoreCartridge(health01,bulletType);
        }
        mag.SetSynchDirty();
        }
        else*/
      {
        int ammoQuantity = (int)Math.Lerp(0, mag.GetAmmoMax(), quantity01);
        mag.ServerSetAmmoCount(ammoQuantity);
      }
    }
    else //'varQuantityDestroyOnMin' quantity safeguard
    {
      float quantityAbsolute = Math.Lerp(item.GetQuantityMin(), item.GetQuantityMax(), quantity01);
      quantityAbsolute = Math.Round(quantityAbsolute); //avoids weird floats
      if (quantityAbsolute <= item.GetQuantityMin() && item.ConfigGetBool("varQuantityDestroyOnMin"))
        quantityAbsolute++;
      item.SetQuantity(quantityAbsolute);
    }
  }
References Math::Lerp(), Math::RandomFloatInclusive(), and Math::Round().
Referenced by HandleNewItem(), and SpawnSimpleChildrenItems().
CreateChildItem()
static EntityAI PlayerSpawnHandler::CreateChildItem (EntityAI parent, string type) inline static private
Definition at line 248 of file CfgPlayerSpawnHandler.c.
  {
    PlayerBase player;
    ItemBase newItem;
    if (Class.CastTo(player, parent)) //special behavior
    {
      int count = player.GetInventory().AttachmentCount();
      if (Class.CastTo(newItem, player.GetInventory().CreateInInventory(type)))
        return newItem;
      Debug.Log("FAILED spawning item: " + type + ", it fits in no cargo or attachment on any worn item", "n/a", "n/a", "CreateChildItem");
      return null;
    }
    //weapon magazine exception
    if (GetGame().ConfigIsExisting(CFG_MAGAZINESPATH + " " + type) && parent.IsWeapon())
    {
      Weapon_Base wep
      if (Class.CastTo(wep, parent))
        return wep.SpawnAttachedMagazine(type);
    }
    return parent.GetInventory().CreateInInventory(type);
  }
References Class::CastTo(), CFG_MAGAZINESPATH, GetGame(), and Debug::Log().
Referenced by SpawnComplexChildrenItems(), and SpawnSimpleChildrenItems().
GetRandomCharacterPreset()
static PlayerSpawnPreset PlayerSpawnHandler::GetRandomCharacterPreset () inline static private
Definition at line 40 of file CfgPlayerSpawnHandler.c.
  {
    array<int> weightedPresetIndexes = new array<int>();
    int count = m_Data.presets.Count();
    PlayerSpawnPreset p;
    for (int i = 0; i < count; i++)
    {
      p = m_Data.presets[i];
      if (p.IsValid())
      {
        for (int j = 0; j < p.spawnWeight; j++)
          weightedPresetIndexes.Insert(i);
      }
    }
    return m_Data.presets.Get(weightedPresetIndexes.GetRandomElement());
  }
References m_Data.
Referenced by MissionBase::OnClientNewEvent().
HandleNewItem()
static void PlayerSpawnHandler::HandleNewItem (notnull ItemBase item, PlayerSpawnPresetItemSetBase data) inline static private
Definition at line 236 of file CfgPlayerSpawnHandler.c.
  {
    ApplyAttributes(item, data.attributes);
    PlayerBase player;
    if (Class.CastTo(player, item.GetHierarchyRootPlayer()) && data.GetQuickbarIdx() > -1)
      player.SetQuickBarEntityShortcut(item, data.GetQuickbarIdx());
    SpawnComplexChildrenItems(item, data);
    SpawnSimpleChildrenItems(item, data);
  }
References ApplyAttributes(), Class::CastTo(), SpawnComplexChildrenItems(), and SpawnSimpleChildrenItems().
Referenced by SpawnComplexChildrenItems(), and SpawnDiscreteSlotItemSet().
IsInitialized()
static bool PlayerSpawnHandler::IsInitialized () inline static private
Definition at line 35 of file CfgPlayerSpawnHandler.c.
  {
    return m_Initialized;
  }
References m_Initialized.
Referenced by MissionBase::OnClientNewEvent().
LoadData()
static bool PlayerSpawnHandler::LoadData () inline static private
Definition at line 6 of file CfgPlayerSpawnHandler.c.
  {
    array<string> spawnGearPresetFiles = CfgGameplayHandler.GetPlayerSpawnGearPresetFiles();
    if (!spawnGearPresetFiles || (spawnGearPresetFiles && spawnGearPresetFiles.Count() == 0))
      return false;
    m_Data.presets = {};
    foreach (string spawnPresetFile : spawnGearPresetFiles)
    {
      PlayerSpawnPreset preset;
      string path = "$mission:" + spawnPresetFile;
      string errorMessage;
      if (!JsonFileLoader<PlayerSpawnPreset>.LoadFile(path, preset, errorMessage))
      {
        ErrorEx(errorMessage);
        return false;
      }
      if (preset != null)
        m_Data.presets.Insert(preset);
    }
    m_Initialized = m_Data.presets.Count() > 0;
    return true;
  }
References ErrorEx, CfgGameplayHandler::GetPlayerSpawnGearPresetFiles(), m_Data, m_Initialized, and path.
Referenced by MissionBase::OnInit().
ProcessCargoEquipment()
static void PlayerSpawnHandler::ProcessCargoEquipment (PlayerBase player, PlayerSpawnPreset data) inline static private
chooses one object from the array
Definition at line 114 of file CfgPlayerSpawnHandler.c.
  {
    if (!data.HasDiscreteUnsortedItemSetsDefined())
    {
      Debug.Log("No non-empty 'discreteUnsortedItemSets' array found. Skipping cargo spawns", "n/a", "n/a", "ProcessCargoEquipment");
      return;
    }
    SelectAndSpawnCargoSet(player, data);
  }
References Debug::Log(), and SelectAndSpawnCargoSet().
Referenced by ProcessEquipmentData().
ProcessEquipmentData()
static bool PlayerSpawnHandler::ProcessEquipmentData (PlayerBase player, PlayerSpawnPreset data) inline static private
equips character with the chosen preset
Definition at line 59 of file CfgPlayerSpawnHandler.c.
  {
    if (data.IsValid())
    {
      ProcessSlotsEquipment(player, data);
      ProcessCargoEquipment(player, data);
    }
    return true;
  }
References ProcessCargoEquipment(), and ProcessSlotsEquipment().
Referenced by MissionBase::OnClientNewEvent().
ProcessSlotsEquipment()
static void PlayerSpawnHandler::ProcessSlotsEquipment (PlayerBase player, PlayerSpawnPreset data) inline static private
iterates over each object and spawns alternatives
Definition at line 71 of file CfgPlayerSpawnHandler.c.
  {
    if (!data.HasAttachmentSlotSetsDefined())
    {
      Debug.Log("No non-empty 'attachmentSlotItemSets' array found. Skipping slot spawns", "n/a", "n/a", "ProcessSlotsEquipment");
      return;
    }
    foreach (PlayerSpawnPresetSlotData slotData : data.attachmentSlotItemSets)
      SelectAndSpawnSlotEquipment(player, slotData);
  }
References Debug::Log(), and SelectAndSpawnSlotEquipment().
Referenced by ProcessEquipmentData().
SelectAndSpawnCargoSet()
static bool PlayerSpawnHandler::SelectAndSpawnCargoSet (PlayerBase player, PlayerSpawnPreset data) inline static private
Definition at line 125 of file CfgPlayerSpawnHandler.c.
  {
    array<int> weightedDiscreteSetIndexes = new array<int>();
    int count = data.discreteUnsortedItemSets.Count();
    PlayerSpawnPresetDiscreteCargoSetData csd;
    for (int i = 0; i < count; i++)
    {
      csd = data.discreteUnsortedItemSets[i];
      if (csd.IsValid()) //only when the spawnWeight is set
      {
        for (int j = 0; j < csd.spawnWeight; j++)
          weightedDiscreteSetIndexes.Insert(i);
      }
    }
    csd = null;
    if (weightedDiscreteSetIndexes.Count() > 0)
      csd = data.discreteUnsortedItemSets.Get(weightedDiscreteSetIndexes.GetRandomElement());
    return SpawnDiscreteCargoItemSet(player, csd);
  }
References SpawnDiscreteCargoItemSet().
Referenced by ProcessCargoEquipment().
SelectAndSpawnSlotEquipment()
static bool PlayerSpawnHandler::SelectAndSpawnSlotEquipment (PlayerBase player, PlayerSpawnPresetSlotData slotData) inline static private
selects weighted slot equipment variant
Definition at line 84 of file CfgPlayerSpawnHandler.c.
  {
    int slotID;
    if (!slotData.TranslateAndValidateSlot(player, slotID))
      return false;
    if (!slotData.IsValid())
      return false;
    array<int> weightedDiscreteSetIndexes = new array<int>();
    int count = slotData.discreteItemSets.Count();
    PlayerSpawnPresetDiscreteItemSetSlotData dis;
    for (int i = 0; i < count; i++)
    {
      dis = slotData.discreteItemSets[i];
      if (dis.IsValid()) //only when the type exists and spawnWeight is set
      {
        for (int j = 0; j < dis.spawnWeight; j++)
          weightedDiscreteSetIndexes.Insert(i);
      }
    }
    dis = null;
    if (weightedDiscreteSetIndexes.Count() > 0)
      dis = slotData.discreteItemSets.Get(weightedDiscreteSetIndexes.GetRandomElement());
    return SpawnDiscreteSlotItemSet(player, dis, slotID);
  }
References SpawnDiscreteSlotItemSet().
Referenced by ProcessSlotsEquipment().
SpawnComplexChildrenItems()
static bool PlayerSpawnHandler::SpawnComplexChildrenItems (EntityAI parent, notnull PlayerSpawnPresetItemSetBase data) inline static private
could spawn other items recursively. Parent item is guaranteed here.
Definition at line 180 of file CfgPlayerSpawnHandler.c.
  {
    if (!data.complexChildrenTypes || data.complexChildrenTypes.Count() < 1) //no children defined, still valid!
      return false;
    foreach (PlayerSpawnPresetComplexChildrenType cct : data.complexChildrenTypes)
    {
      //todo: slotID option over nyah?
      if (cct.itemType == string.Empty)
      {
        Debug.Log("Empty item type found in 'complexChildrenTypes' of parent : " + parent, "n/a", "n/a", "SpawnSimpleChildrenItems");
        continue;
      }
      ItemBase item;
      Class.CastTo(item, CreateChildItem(parent, cct.itemType));
      if (item)
        HandleNewItem(item, cct);
      else
        Debug.Log("FAILED spawning item: " + cct.itemType + " of parent: " + parent, "n/a", "n/a", "SpawnComplexChildrenItems");
    }
    return true;
  }
References Class::CastTo(), CreateChildItem(), HandleNewItem(), and Debug::Log().
Referenced by HandleNewItem(), and SpawnDiscreteCargoItemSet().
SpawnDiscreteCargoItemSet()
static bool PlayerSpawnHandler::SpawnDiscreteCargoItemSet (PlayerBase player, PlayerSpawnPresetDiscreteCargoSetData csd) inline static private
Definition at line 147 of file CfgPlayerSpawnHandler.c.
  {
    SpawnComplexChildrenItems(player, csd);
    SpawnSimpleChildrenItems(player, csd);
    return true;
  }
References SpawnComplexChildrenItems(), and SpawnSimpleChildrenItems().
Referenced by SelectAndSpawnCargoSet().
SpawnDiscreteSlotItemSet()
static bool PlayerSpawnHandler::SpawnDiscreteSlotItemSet (PlayerBase player, PlayerSpawnPresetDiscreteItemSetSlotData dis, int slotID) inline static private
Definition at line 154 of file CfgPlayerSpawnHandler.c.
  {
    if (!dis)
    {
      Debug.Log("No PlayerSpawnPresetDiscreteItemSet found. Skipping spawn for slot: " + InventorySlots.GetSlotName(slotID), "n/a", "n/a", "SpawnDiscreteSlotItemSet");
      return false;
    }
    ItemBase item;
    if (slotID == InventorySlots.HANDS) //hands exception
      item = ItemBase.Cast(player.GetHumanInventory().CreateInHands(dis.itemType));
    else
      item = ItemBase.Cast(player.GetInventory().CreateAttachmentEx(dis.itemType, slotID));
    if (item)
      HandleNewItem(item, dis);
    else if (dis.itemType != string.Empty)
    {
      Debug.Log("FAILED spawning item type: " + dis.itemType + " into slot: " + InventorySlots.GetSlotName(slotID) + " of parent: " + player, "n/a", "n/a", "SpawnDiscreteSlotItemSet");
      return false;
    }
    return item != null;
  }
References InventorySlots::GetSlotName(), HandleNewItem(), and Debug::Log().
Referenced by SelectAndSpawnSlotEquipment().
SpawnSimpleChildrenItems()
static bool PlayerSpawnHandler::SpawnSimpleChildrenItems (EntityAI parent, PlayerSpawnPresetItemSetBase data) inline static private
Definition at line 206 of file CfgPlayerSpawnHandler.c.
  {
    if (!data || !data.simpleChildrenTypes || data.simpleChildrenTypes.Count() < 1) //no children defined, still valid!
      return false;
    int count = data.simpleChildrenTypes.Count();
    string itemType;
    for (int i = 0; i < count; i++)
    {
      itemType = data.simpleChildrenTypes[i];
      if (itemType == string.Empty)
      {
        Debug.Log("Empty item type found at idx: " + i.ToString() + " of 'simpleChildrenTypes' array. Skipping", "n/a", "n/a", "SpawnSimpleChildrenItems");
        continue;
      }
      ItemBase item;
      Class.CastTo(item, CreateChildItem(parent, itemType));
      if (item)
      {
        if (!data.simpleChildrenUseDefaultAttributes)
          ApplyAttributes(item, data.attributes);
      }
      else
        Debug.Log("FAILED spawning item type: " + itemType + " to parent: " + parent, "n/a", "n/a", "SpawnSimpleChildrenItems");
    }
    return true;
  }
References ApplyAttributes(), Class::CastTo(), CreateChildItem(), Empty, and Debug::Log().
Referenced by HandleNewItem(), and SpawnDiscreteCargoItemSet().
Member Data Documentation
m_Data
ref PlayerSpawnJsonData PlayerSpawnHandler::m_Data = new PlayerSpawnJsonData() static private
Definition at line 4 of file CfgPlayerSpawnHandler.c.
Referenced by GetRandomCharacterPreset(), and LoadData().
m_Initialized
bool PlayerSpawnHandler::m_Initialized static private
Definition at line 3 of file CfgPlayerSpawnHandler.c.
Referenced by IsInitialized(), and LoadData().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/PlayerGearSpawn/CfgPlayerSpawnHandler.c