DayZ: scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/Medical/ActionSewTarget.c File Reference
ActionSewTarget.c File Reference
Classes
class ActionSewTargetCB
Functions
ActionSewTargetCB ActionContinuousBaseCB ActionSewTarget ()
override void CreateActionComponent ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override void ApplyBandage (ItemBase item, PlayerBase player)
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 27 of file ActionSewTarget.c.
  {
    if (!super.ActionCondition(player, target, item))
      return false;
    PlayerBase otherPlayer = PlayerBase.Cast(target.GetObject());
    return otherPlayer.IsBleeding();
  }
ActionSewTarget()
ActionSewTargetCB ActionContinuousBaseCB ActionSewTarget ()
Definition at line 1 of file ActionSewTarget.c.
  {
    m_CallbackClass = ActionSewTargetCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
    m_Text = "#sew_targets_cuts";
  }
Referenced by ActionConstructor::RegisterActions(), and SewingKit::SetActions().
ApplyBandage()
override void ApplyBandage (ItemBase item, PlayerBase player)
Definition at line 46 of file ActionSewTarget.c.
  {
    if (player.GetBleedingManagerServer())
      player.GetBleedingManagerServer().RemoveMostSignificantBleedingSourceEx(item);
    PluginTransmissionAgents transmissionAgents = PluginTransmissionAgents.Cast(GetPlugin(PluginTransmissionAgents));
    transmissionAgents.TransmitAgents(item, player, AGT_ITEM_TO_FLESH);
    if (item.HasQuantity())
      item.AddQuantity(-20, true);
    else
      item.Delete();
  }
References AGT_ITEM_TO_FLESH, and GetPlugin().
CreateActionComponent()
override void ActionSewTarget::CreateActionComponent ()
Definition at line 12 of file ActionSewTarget.c.
  {
    m_CallbackClass = ActionSewTargetCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
    m_FullBody = true;
References m_FullBody, m_StanceMask, and m_Text.
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 21 of file ActionSewTarget.c.
  {
    m_ConditionItem = new CCINonRuined();
    m_ConditionTarget = new CCTMan(UAMaxDistances.DEFAULT);
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 36 of file ActionSewTarget.c.
  {
    if (CanReceiveAction(action_data.m_Target))
    {
      PlayerBase player = PlayerBase.Cast(action_data.m_Target.GetObject());
      if (action_data.m_MainItem && player)
        ApplyBandage(action_data.m_MainItem, player);
    }
  }
References ActionBandageBase::ApplyBandage(), and CanReceiveAction().