DayZ: Bot Class Reference
Bot Class Reference
Protected Member Functions
void Bot (PlayerBase ow)
void SetInstanceType (DayZPlayerInstanceType t)
void Start (bool use_trigger, BotTrigger trigger=null)
void DelayedStart (float ms)
void OnDelayedStart ()
void Stop ()
void OnTrigger ()
void OnUpdate (float dt)
void OnTimer ()
bool ProcessEvent (BotEventBase e)
void InitFSM ()
Protected Attributes
ref Timer m_Timer = new Timer
const float c_TriggerTimeoutMS = 1000.0
const float c_UpdateMS = 16.0
ref BotFSM m_FSM = null
bool m_UseTrigger = false
bool m_Triggered = false
DayZPlayerInstanceType m_InstanceType = DayZPlayerInstanceType.INSTANCETYPE_CLIENT
ref BotTrigger m_BotTrigger = null
ref BotStateBase m_BotTest = null
Private Attributes
PlayerBase m_Owner = null
Detailed Description
Definition at line 18 of file Bot.c.
Constructor & Destructor Documentation
Bot()
void Bot::Bot (PlayerBase ow) inline protected
Definition at line 32 of file Bot.c.
  {
    m_Owner = ow;
  }
References m_Owner.
Member Function Documentation
DelayedStart()
void Bot::DelayedStart (float ms) inline protected
Definition at line 62 of file Bot.c.
  {
    m_Timer.Run(ms / 1000.0, this, "OnDelayedStart", null, false);
  }
References m_Timer.
InitFSM()
void Bot::InitFSM () inline protected
transition table
Definition at line 126 of file Bot.c.
References m_BotTest, and m_FSM.
Referenced by Start().
OnDelayedStart()
void Bot::OnDelayedStart () inline protected
Definition at line 67 of file Bot.c.
  {
    Start(false, null);
    ProcessEvent(new BotEventStart(m_Owner));
    m_UseTrigger = false;
  }
References m_Owner, m_UseTrigger, ProcessEvent(), and Start().
OnTimer()
void Bot::OnTimer () inline protected
Definition at line 119 of file Bot.c.
  {
    //m_FSM.GetCurrentState().OnUpdate(c_UpdateMS / 1000.0);
    //OnTrigger(); // to detect trigger stop
  }
OnTrigger()
void Bot::OnTrigger () inline protected
Definition at line 82 of file Bot.c.
  {
    bool triggered = m_BotTrigger.CheckTrigger();
    if (!m_Triggered)
    {
      if (triggered)
      {
        m_Timer.Stop(); // stop trigger timer
        m_Triggered = true;
        ProcessEvent(new BotEventStart(m_Owner));
        m_Timer.Run(c_UpdateMS / 1000.0, this, "OnUpdate", null, true);
        botDebugPrint("[bot] + " + m_Owner + " Started test!");
      }
    }
    else
    {
      if (!triggered)
      {
        m_Timer.Stop(); // stop update timer
        m_Triggered = false;
        ProcessEvent(new BotEventStop(m_Owner));
        m_Timer.Run(c_TriggerTimeoutMS / 1000.0, this, "OnTrigger", null, true);
        botDebugPrint("[bot] + " + m_Owner + " Stopped test!");
      }
    }
  }
References botDebugPrint(), c_TriggerTimeoutMS, c_UpdateMS, m_BotTrigger, m_Owner, m_Timer, m_Triggered, and ProcessEvent().
Referenced by OnUpdate().
OnUpdate()
void Bot::OnUpdate (float dt) inline protected
Definition at line 112 of file Bot.c.
  {
    m_FSM.GetCurrentState().OnUpdate(dt);
    OnTrigger(); // to detect trigger stop
  }
References m_FSM, and OnTrigger().
ProcessEvent()
bool Bot::ProcessEvent (BotEventBase e) inline protected
Definition at line 167 of file Bot.c.
  {
    if (m_FSM.ProcessEvent(e) == ProcessEventResult.FSM_OK)
    {
      botDebugSpam("[botfsm] Processed event e=" + e.ToString());
      return true;
    }
    else
    {
      botDebugSpam("[botfsm] FSM refused to process event (no transition): src=" + m_FSM.GetCurrentState().ToString() + " event=" + e.ToString());
      return false;
    }
  }
References botDebugSpam(), and m_FSM.
Referenced by OnDelayedStart(), and OnTrigger().
SetInstanceType()
void Bot::SetInstanceType (DayZPlayerInstanceType t) inline protected
Definition at line 37 of file Bot.c.
{ m_InstanceType = t; }
References m_InstanceType.
Start()
void Bot::Start (bool use_trigger, BotTrigger trigger = null) inline protected
Definition at line 39 of file Bot.c.
  {
    m_UseTrigger = use_trigger;
    InitFSM();
    if (m_UseTrigger)
    {
      if (m_UseTrigger && trigger == null)
        Error("use trigger, but trigger null");
      m_Triggered = false;
      m_BotTrigger = trigger;
      botDebugPrint("[bot] + " + m_Owner + " Bot waiting for trigger...");
      m_Timer.Run(c_TriggerTimeoutMS / 1000.0, this, "OnTrigger", null, true);
    }
    else
    {
      botDebugPrint("[bot] + " + m_Owner + " Bot Started.");
      m_Timer.Run(c_UpdateMS / 1000.0, this, "OnTimer", null, true);
    }
  }
References botDebugPrint(), c_TriggerTimeoutMS, c_UpdateMS, Error(), InitFSM(), m_BotTrigger, m_Owner, m_Timer, m_Triggered, and m_UseTrigger.
Stop()
void Bot::Stop () inline protected
Definition at line 75 of file Bot.c.
  {
    m_Triggered = false;
    m_Timer.Stop();
    m_FSM.Terminate();
  }
References m_FSM, m_Timer, and m_Triggered.
Member Data Documentation
c_TriggerTimeoutMS
const float Bot::c_TriggerTimeoutMS = 1000.0 protected
Definition at line 22 of file Bot.c.
Referenced by OnTrigger(), and Start().
c_UpdateMS
const float Bot::c_UpdateMS = 16.0 protected
Definition at line 24 of file Bot.c.
Referenced by OnTrigger(), and Start().
m_BotTest
ref BotStateBase Bot::m_BotTest = null protected
Definition at line 30 of file Bot.c.
Referenced by InitFSM().
m_BotTrigger
ref BotTrigger Bot::m_BotTrigger = null protected
Definition at line 29 of file Bot.c.
Referenced by OnTrigger(), and Start().
m_FSM
ref BotFSM Bot::m_FSM = null protected
Definition at line 25 of file Bot.c.
Referenced by InitFSM(), OnUpdate(), ProcessEvent(), and Stop().
m_InstanceType
DayZPlayerInstanceType Bot::m_InstanceType = DayZPlayerInstanceType.INSTANCETYPE_CLIENT protected
Definition at line 28 of file Bot.c.
Referenced by SetInstanceType().
m_Owner
PlayerBase Bot::m_Owner = null private
Definition at line 20 of file Bot.c.
Referenced by Bot(), BotStateIdle::BotStateIdle(), OnDelayedStart(), OnTrigger(), and Start().
m_Timer
ref Timer Bot::m_Timer = new Timer protected
Definition at line 21 of file Bot.c.
Referenced by DelayedStart(), OnTrigger(), Start(), and Stop().
m_Triggered
bool Bot::m_Triggered = false protected
Definition at line 27 of file Bot.c.
Referenced by OnTrigger(), Start(), and Stop().
m_UseTrigger
bool Bot::m_UseTrigger = false protected
Definition at line 26 of file Bot.c.
Referenced by OnDelayedStart(), and Start().
The documentation for this class was generated from the following file:
scripts/4_World/Systems/Bot/Bot.c