DayZ: ActionCraftBolts Class Reference
ActionCraftBolts Class Reference
Protected Member Functions
void InitCuttingTypes ()
void ActionCraftBolts ()
override void CreateConditionComponents ()
bool IsCuttingType (Object item)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStartServer (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Protected Attributes
bool m_IsKnifeInHands
Ammunition_Base m_ResultEntity
Private Attributes
const ref set< string > CUTTING_TYPES = new set<string>()
Additional Inherited Members
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 11 of file ActionCraftBolts.c.
Constructor & Destructor Documentation
ActionCraftBolts()
void ActionCraftBolts::ActionCraftBolts () inline protected
Definition at line 42 of file ActionCraftBolts.c.
  {
    m_CallbackClass = ActionCraftBoltsCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_CRAFTING;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH;
    m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_HIGH;
    m_Text = "#STR_CraftBolt0";
    InitCuttingTypes();
  }
References InitCuttingTypes(), AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
Member Function Documentation
ActionCondition()
override bool ActionCraftBolts::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline protected
Definition at line 66 of file ActionCraftBolts.c.
  {
    if (IsCuttingType(item))
    {
      //knife in hands
      if (target.GetObject())
        return (target.GetObject().ClassName() == "WoodenStick");
    }
    else if (target.GetObject())
    {
      // material in hands
      return IsCuttingType(target.GetObject());
    }
    return false;
  }
References IsCuttingType().
CreateConditionComponents()
override void ActionCraftBolts::CreateConditionComponents () inline protected
Definition at line 55 of file ActionCraftBolts.c.
  {
    m_ConditionItem = new CCINonRuined();
    m_ConditionTarget = new CCTNonRuined();
  }
References m_ConditionItem, and m_ConditionTarget.
InitCuttingTypes()
void ActionCraftBolts::InitCuttingTypes () inline protected
Definition at line 18 of file ActionCraftBolts.c.
  {
    CUTTING_TYPES.Clear();
    CUTTING_TYPES.Insert("Sickle");
    CUTTING_TYPES.Insert("KukriKnife");
    CUTTING_TYPES.Insert("FangeKnife");
    CUTTING_TYPES.Insert("KitchenKnife");
    CUTTING_TYPES.Insert("SteakKnife");
    CUTTING_TYPES.Insert("StoneKnife");
    CUTTING_TYPES.Insert("Cleaver");
    CUTTING_TYPES.Insert("CombatKnife");
    CUTTING_TYPES.Insert("HuntingKnife");
    CUTTING_TYPES.Insert("Machete");
    CUTTING_TYPES.Insert("CrudeMachete");
    CUTTING_TYPES.Insert("OrientalMachete");
    CUTTING_TYPES.Insert("WoodAxe");
    CUTTING_TYPES.Insert("Hatchet");
    CUTTING_TYPES.Insert("FirefighterAxe");
    CUTTING_TYPES.Insert("AK_Bayonet");
    CUTTING_TYPES.Insert("M9A1_Bayonet");
    CUTTING_TYPES.Insert("SKS_Bayonet");
    CUTTING_TYPES.Insert("BoneKnife");
  }
References CUTTING_TYPES.
Referenced by ActionCraftBolts().
IsCuttingType()
bool ActionCraftBolts::IsCuttingType (Object item) inline protected
Definition at line 61 of file ActionCraftBolts.c.
  {
    return CUTTING_TYPES.Find(item.ClassName()) >= 0;
  }
References CUTTING_TYPES.
Referenced by ActionCondition(), and OnStartServer().
OnFinishProgressServer()
override void ActionCraftBolts::OnFinishProgressServer (ActionData action_data) inline protected
Definition at line 89 of file ActionCraftBolts.c.
  {
    ItemBase knife;
    ItemBase material;
    bool added = false;
    if (m_IsKnifeInHands)
    {
      //knife in hands
      knife = action_data.m_MainItem;
      material = ItemBase.Cast(action_data.m_Target.GetObject());
    }
    else
    {
      // material in hands
      material = action_data.m_MainItem;
      knife = ItemBase.Cast(action_data.m_Target.GetObject());
    }
    if (!material || !knife)
      return;
    if (m_ResultEntity)
    {
      if (m_ResultEntity.GetAmmoCount() < m_ResultEntity.GetAmmoMax())
      {
        m_ResultEntity.ServerAddAmmoCount(1);
        added = true;
      }
    }
    if (!added)
    {
      m_ResultEntity = Ammunition_Base.Cast(action_data.m_Player.SpawnEntityOnGroundPos("Ammo_ImprovisedBolt_1", action_data.m_Player.GetPosition()));
      m_ResultEntity.SetHealth("", "", material.GetHealth("", ""));
      m_ResultEntity.ServerSetAmmoCount(1);
    }
    material.AddQuantity(-1);
    knife.AddHealth("", "", -3);
  }
References m_IsKnifeInHands, and m_ResultEntity.
OnStartServer()
override void ActionCraftBolts::OnStartServer (ActionData action_data) inline protected
Definition at line 83 of file ActionCraftBolts.c.
  {
    m_IsKnifeInHands = IsCuttingType(action_data.m_MainItem);
    m_ResultEntity = null;
  }
References IsCuttingType(), m_IsKnifeInHands, and m_ResultEntity.
Member Data Documentation
CUTTING_TYPES
const ref set<string> ActionCraftBolts::CUTTING_TYPES = new set<string>() private
Definition at line 13 of file ActionCraftBolts.c.
Referenced by InitCuttingTypes(), and IsCuttingType().
m_IsKnifeInHands
bool ActionCraftBolts::m_IsKnifeInHands protected
Definition at line 15 of file ActionCraftBolts.c.
Referenced by OnFinishProgressServer(), and OnStartServer().
m_ResultEntity
Ammunition_Base ActionCraftBolts::m_ResultEntity protected
Definition at line 16 of file ActionCraftBolts.c.
Referenced by OnFinishProgressServer(), and OnStartServer().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionCraftBolts.c