DayZ: ClientData Class Reference
ClientData Class Reference
Static Private Member Functions
static void ResetClientData ()
static void AddPlayerBase (Man player)
static void RemovePlayerBase (Man player)
static void SyncEvent_PreprocessPlayerList (SyncPlayerList player_list)
static void SyncEvent_OnRecievedPlayerList (SyncPlayerList player_list)
static array< string > GetSimplePlayerList ()
static array< string > GetSimplePlayerList (SyncPlayerList list)
static void SyncEvent_OnEntityKilled (SyncEntityKillInfo entity_killed_data)
static void SyncEvent_OnPlayerIgnitedFireplace (EFireIgniteType igante_type)
Static Private Attributes
static ref ScriptInvoker SyncEvent_OnPlayerListUpdate = new ScriptInvoker()
static ref ScriptInvoker SyncEvent_OnEntityKilled = new ScriptInvoker()
static ref ScriptInvoker SyncEvent_OnPlayerIgnitedFireplace = new ScriptInvoker()
static ref array< Man > m_PlayerBaseList = new array<Man>
static ref SyncPlayerList m_PlayerList
static ref SyncPlayerList m_LastNewPlayers
static ref OnlineServices m_OnlineServices
Detailed Description
Definition at line 1 of file ClientData.c.
Member Function Documentation
AddPlayerBase()
static void ClientData::AddPlayerBase (Man player) inline static private
Definition at line 23 of file ClientData.c.
  {
    if (m_PlayerBaseList && player != GetGame().GetPlayer())
      m_PlayerBaseList.Insert(player);
  }
References GetGame(), GetPlayer(), and m_PlayerBaseList.
Referenced by ManBase::Init().
GetSimplePlayerList() [1/2]
static array< string > ClientData::GetSimplePlayerList () inline static private
Definition at line 84 of file ClientData.c.
  {
    array<string> ids = new array<string>;
    if (m_PlayerList && m_PlayerList.m_PlayerList)
    {
      for (int i = 0; i < m_PlayerList.m_PlayerList.Count(); i++)
      {
        SyncPlayer player = m_PlayerList.m_PlayerList.Get(i);
        ids.Insert(player.m_UID);
      }
    }
    return ids;
  }
References m_PlayerList.
Referenced by OnlineServices::GetPendingInviteList(), BiosSessionService::GetSessionPlayerList(), OnlineServices::SetMultiplayState(), and SyncEvent_OnRecievedPlayerList().
GetSimplePlayerList() [2/2]
static array< string > ClientData::GetSimplePlayerList (SyncPlayerList list) inline static private
Definition at line 99 of file ClientData.c.
  {
    array<string> ids = new array<string>;
    if (list)
    {
      for (int i = 0; i < list.m_PlayerList.Count(); i++)
      {
        SyncPlayer player = list.m_PlayerList.Get(i);
        ids.Insert(player.m_UID);
      }
    }
    return ids;
  }
RemovePlayerBase()
static void ClientData::RemovePlayerBase (Man player) inline static private
Definition at line 29 of file ClientData.c.
  {
    if (m_PlayerBaseList)
      m_PlayerBaseList.RemoveItem(player);
  }
References m_PlayerBaseList.
Referenced by ManBase::EEKilled(), and ManBase::~PlayerBase().
ResetClientData()
static void ClientData::ResetClientData () inline static private
Definition at line 13 of file ClientData.c.
  {
    if (m_PlayerBaseList)
      m_PlayerBaseList.Clear();
    if (m_PlayerList && m_PlayerList.m_PlayerList)
      m_PlayerList.m_PlayerList.Clear();
    if (m_LastNewPlayers && m_LastNewPlayers.m_PlayerList)
      m_LastNewPlayers.m_PlayerList.Clear();
  }
References m_LastNewPlayers, m_PlayerBaseList, and m_PlayerList.
Referenced by CGame::OnEvent().
SyncEvent_OnEntityKilled()
static void ClientData::SyncEvent_OnEntityKilled (SyncEntityKillInfo entity_killed_data) inline static private
Definition at line 114 of file ClientData.c.
  {
    SyncEvent_OnEntityKilled.Invoke(entity_killed_data.m_EntityVictim, entity_killed_data.m_EntityKiller, entity_killed_data.m_EntitySource, entity_killed_data.m_IsHeadShot);
  }
References SyncEvent_OnEntityKilled.
SyncEvent_OnPlayerIgnitedFireplace()
static void ClientData::SyncEvent_OnPlayerIgnitedFireplace (EFireIgniteType igante_type) inline static private
Definition at line 119 of file ClientData.c.
  {
    SyncEvent_OnPlayerIgnitedFireplace.Invoke(igante_type);
  }
References SyncEvent_OnPlayerIgnitedFireplace.
SyncEvent_OnRecievedPlayerList()
static void ClientData::SyncEvent_OnRecievedPlayerList (SyncPlayerList player_list) inline static private
Definition at line 51 of file ClientData.c.
  {
    if (m_PlayerList && m_PlayerList.m_PlayerList)
    {
      //Print("SyncEvent_OnRecievedPlayerList | " + m_PlayerList.m_PlayerList.Count());
    }
    SyncPlayerList new_players = SyncPlayerList.Compare(m_PlayerList, player_list);
    if (!m_LastNewPlayers)
      m_LastNewPlayers = player_list;
    else
      m_LastNewPlayers = SyncPlayerList.Compare(m_LastNewPlayers, new_players);
    m_PlayerList = SyncPlayerList.Compare(player_list, null);
#ifdef PLATFORM_CONSOLE
#ifndef PLATFORM_WINDOWS // if app is not on Windows with -XBOX parameter
    array<string> newPlayersSimple = GetSimplePlayerList(new_players);
    OnlineServices.LoadPermissions(newPlayersSimple);
    OnlineServices.m_ClientServices.GetSessionService().OnSessionPlayerListUpdate(newPlayersSimple);
    if (new_players.m_PlayerList.Count() > 0)
      OnlineServices.LoadFriends();
    if (g_Game.GetGameState() == DayZGameState.IN_GAME)
      OnlineServices.SetMultiplayState(OnlineServices.GetMultiplayState());
#endif
#endif
    SyncEvent_OnPlayerListUpdate.Invoke(player_list);
  }
References SyncPlayerList::Compare(), g_Game, OnlineServices::GetMultiplayState(), GetSimplePlayerList(), OnlineServices::LoadFriends(), OnlineServices::LoadPermissions(), OnlineServices::m_ClientServices, m_LastNewPlayers, m_PlayerList, OnlineServices::SetMultiplayState(), and SyncEvent_OnPlayerListUpdate.
Referenced by SyncEvents::OnSyncEvent().
SyncEvent_PreprocessPlayerList()
static void ClientData::SyncEvent_PreprocessPlayerList (SyncPlayerList player_list) inline static private
Definition at line 35 of file ClientData.c.
  {
    foreach (auto sync_player : player_list.m_PlayerList)
    {
      PlayerIdentity identity = sync_player.m_Identity;
      if (!identity)
      {
        ErrorEx("PlayerIdentity not synchronized before SyncPlayer", ErrorExSeverity.WARNING);
        continue;
      }
      sync_player.m_UID = identity.GetPlainId();
      sync_player.m_PlayerName = identity.GetPlainName();
    }
  }
References ErrorEx.
Referenced by SyncEvents::OnSyncEvent().
Member Data Documentation
m_LastNewPlayers
ref SyncPlayerList ClientData::m_LastNewPlayers static private
Definition at line 9 of file ClientData.c.
Referenced by OnlineServices::OnFriendsAsync(), ResetClientData(), and SyncEvent_OnRecievedPlayerList().
m_OnlineServices
ref OnlineServices ClientData::m_OnlineServices static private
Definition at line 11 of file ClientData.c.
m_PlayerBaseList
ref array<Man> ClientData::m_PlayerBaseList = new array<Man> static private
Definition at line 7 of file ClientData.c.
Referenced by AddPlayerBase(), Hud::RefreshPlayerTags(), RemovePlayerBase(), and ResetClientData().
m_PlayerList
ref SyncPlayerList ClientData::m_PlayerList static private
Definition at line 8 of file ClientData.c.
Referenced by GetSimplePlayerList(), UIScriptedMenu::Init(), ResetClientData(), and SyncEvent_OnRecievedPlayerList().
SyncEvent_OnEntityKilled
ref ScriptInvoker ClientData::SyncEvent_OnEntityKilled = new ScriptInvoker() static private
Definition at line 4 of file ClientData.c.
Referenced by SyncEvents::OnSyncEvent(), AnalyticsManagerClient::RegisterEvents(), SyncEvent_OnEntityKilled(), and AnalyticsManagerClient::UnregisterEvents().
SyncEvent_OnPlayerIgnitedFireplace
ref ScriptInvoker ClientData::SyncEvent_OnPlayerIgnitedFireplace = new ScriptInvoker() static private
Definition at line 5 of file ClientData.c.
Referenced by SyncEvents::OnSyncEvent(), AnalyticsManagerClient::RegisterEvents(), SyncEvent_OnPlayerIgnitedFireplace(), and AnalyticsManagerClient::UnregisterEvents().
SyncEvent_OnPlayerListUpdate
ref ScriptInvoker ClientData::SyncEvent_OnPlayerListUpdate = new ScriptInvoker() static private
Definition at line 3 of file ClientData.c.
Referenced by UIScriptedMenu::Init(), SyncEvent_OnRecievedPlayerList(), and UIScriptedMenu::~InGameMenuXbox().
The documentation for this class was generated from the following file:
scripts/3_Game/Client/ClientData.c