DayZ: PlayerSoundEventBase Class Reference
PlayerSoundEventBase Class Reference
Private Member Functions
void DamageSoundEvents ()
override bool CanPlay (PlayerBase player)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
void DrowningEvents ()
override bool CanPlay (PlayerBase player)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
void HeatComfortEventsBase ()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
void HoldBreathSoundEventBase ()
override bool HasHoldBreathException ()
void InjurySoundEvents ()
override bool CanPlay (PlayerBase player)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override bool CanPlay (PlayerBase player)
override void OnPlay (PlayerBase player)
override void OnEnd ()
void MeleeAttackSoundEvents ()
override bool CanPlay (PlayerBase player)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override void OnEnd ()
void PickupHeavySoundEvent ()
void StaminaSoundEventBase ()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override void OnPlay (PlayerBase player)
void SymptomSoundEventBase ()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
Private Attributes
const int MAX_VOLUME = 4
Detailed Description
Definition at line 1 of file DamageEvents.c.
Member Function Documentation
CanPlay() [1/5]
override bool PlayerSoundEventBase::CanPlay (PlayerBase player) inline private
Definition at line 10 of file DamageEvents.c.
  {
    return true;
  }
CanPlay() [2/5]
override bool PlayerSoundEventBase::CanPlay (PlayerBase player) inline private
Definition at line 9 of file DrowningEvents.c.
  {
    return true;
  }
CanPlay() [3/5]
override bool PlayerSoundEventBase::CanPlay (PlayerBase player) inline private
Definition at line 10 of file InjuryEvents.c.
  {
    return true;
  }
CanPlay() [4/5]
override bool PlayerSoundEventBase::CanPlay (PlayerBase player) inline private
Definition at line 8 of file JumpEvents.c.
  {
    if (!super.CanPlay(player))
      return false;
    return true;
  }
CanPlay() [5/5]
override bool PlayerSoundEventBase::CanPlay (PlayerBase player) inline private
Definition at line 9 of file MeleeAttack.c.
  {
    return true;
  }
DamageSoundEvents()
void PlayerSoundEventBase::DamageSoundEvents () inline private
Definition at line 4 of file DamageEvents.c.
  {
    m_HasPriorityOverTypes = -1;//-1 for all
    m_Type = EPlayerSoundEventType.DAMAGE;
  }
References m_HasPriorityOverTypes, and m_Type.
DrowningEvents()
void PlayerSoundEventBase::DrowningEvents () inline private
Definition at line 3 of file DrowningEvents.c.
  {
    m_HasPriorityOverTypes = -1;//-1 for all
    m_Type = EPlayerSoundEventType.DROWNING;
  }
References m_HasPriorityOverTypes, and m_Type.
HasHoldBreathException()
override bool PlayerSoundEventBase::HasHoldBreathException () inline private
Definition at line 8 of file HoldBreathEvents.c.
  {
    return true;
  }
Referenced by CanPlay().
HasPriorityOverCurrent() [1/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 15 of file DamageEvents.c.
  {
    return true;
  }
HasPriorityOverCurrent() [2/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 14 of file DrowningEvents.c.
  {
    return true;
  }
HasPriorityOverCurrent() [3/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 10 of file HeatComfortEvents.c.
  {
    return true;
  }
HasPriorityOverCurrent() [4/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 15 of file InjuryEvents.c.
  {
    return true;
  }
HasPriorityOverCurrent() [5/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 3 of file JumpEvents.c.
  {
    return true;
  }
HasPriorityOverCurrent() [6/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 14 of file MeleeAttack.c.
  {
    if (type_other == EPlayerSoundEventType.DAMAGE)
      return false;
    return true;
  }
HasPriorityOverCurrent() [7/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 10 of file StaminaEvents.c.
  {
    return false;
  }
HasPriorityOverCurrent() [8/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 9 of file SymptomEvents.c.
  {
    return true;
  }
HeatComfortEventsBase()
void PlayerSoundEventBase::HeatComfortEventsBase () inline private
Definition at line 4 of file HeatComfortEvents.c.
  {
    m_HasPriorityOverTypes = EPlayerSoundEventType.DUMMY | EPlayerSoundEventType.INJURY | EPlayerSoundEventType.STAMINA | EPlayerSoundEventType.GENERAL;//-1 for all
    m_Type = EPlayerSoundEventType.GENERAL;
  }
References m_HasPriorityOverTypes, and m_Type.
HoldBreathSoundEventBase()
void PlayerSoundEventBase::HoldBreathSoundEventBase () inline private
Definition at line 3 of file HoldBreathEvents.c.
  {
    m_HasPriorityOverTypes = -1;
  }
References m_HasPriorityOverTypes.
InjurySoundEvents()
void PlayerSoundEventBase::InjurySoundEvents () inline private
Definition at line 4 of file InjuryEvents.c.
  {
    m_HasPriorityOverTypes = -1;//-1 for all
    m_Type = EPlayerSoundEventType.INJURY;
  }
References m_HasPriorityOverTypes, and m_Type.
MeleeAttackSoundEvents()
void PlayerSoundEventBase::MeleeAttackSoundEvents () inline private
Definition at line 3 of file MeleeAttack.c.
  {
    m_Type = EPlayerSoundEventType.MELEE;
    m_HasPriorityOverTypes = -1;
  }
References m_HasPriorityOverTypes, and m_Type.
OnEnd() [1/2]
override void PlayerSoundEventBase::OnEnd () inline private
Definition at line 22 of file JumpEvents.c.
  {
    super.OnEnd();
    //m_Player.GetStaminaSoundHandlerClient().PostponeStamina(1000);
    if (m_Player)
      StaminaSoundHandlerClient.Cast(m_Player.m_PlayerSoundManagerClient.GetHandler(eSoundHandlers.STAMINA)).PostponeStamina(1300);
  }
References m_Player.
Referenced by Play(), and ~PlayerSoundEventBase().
OnEnd() [2/2]
override void PlayerSoundEventBase::OnEnd () inline private
Definition at line 21 of file MeleeAttack.c.
  {
    super.OnEnd();
    if (m_Player)
      StaminaSoundHandlerClient.Cast(m_Player.m_PlayerSoundManagerClient.GetHandler(eSoundHandlers.STAMINA)).PostponeStamina(800);
  }
References m_Player.
OnPlay() [1/2]
override void PlayerSoundEventBase::OnPlay (PlayerBase player) inline private
Definition at line 15 of file JumpEvents.c.
  {
    super.OnPlay(player);
    if (player.CanSpawnBreathVaporEffect())
      player.SpawnBreathVaporEffect();
  }
OnPlay() [2/2]
override void PlayerSoundEventBase::OnPlay (PlayerBase player) inline private
!! beware of the ifdef above , most likely you want to put your code above it, otherwise it might not get executed !!!
Definition at line 15 of file StaminaEvents.c.
  {
    super.OnPlay(player);
    MaskBase mask = MaskBase.Cast(player.GetInventory().FindAttachment(InventorySlots.GetSlotIdFromString("Mask")));
    float rel_volume = 1;
    if (mask)
    {
      if (mask.IsExternalFilterAttached() || mask.HasIntegratedFilter())
        rel_volume = Math.Lerp(MAX_VOLUME, 1, mask.GetFilterQuantity01());
    }
    if (m_SoundSetCallback)
      m_SoundSetCallback.SetVolumeRelative(rel_volume);
#ifdef DIAG_DEVELOPER
    if (!DiagMenu.GetBool(DiagMenuIDs.MISC_BREATH_VAPOR_LVL))//disabled in debug, do not spawn particles
      return;
#endif
    if (player.CanSpawnBreathVaporEffect())
      player.SpawnBreathVaporEffect();
  }
References DiagMenu::GetBool(), InventorySlots::GetSlotIdFromString(), Math::Lerp(), m_SoundSetCallback, MAX_VOLUME, and AbstractWave::SetVolumeRelative().
PickupHeavySoundEvent()
void PlayerSoundEventBase::PickupHeavySoundEvent () inline private
Definition at line 3 of file MiscEvents.c.
  {
    m_HasPriorityOverTypes = -1;//-1 for all
    m_Type = EPlayerSoundEventType.STAMINA;
    m_ID = EPlayerSoundEventID.PICKUP_HEAVY;
    m_SoundVoiceAnimEventClassID = 19;
  }
References m_HasPriorityOverTypes, m_ID, m_SoundVoiceAnimEventClassID, and m_Type.
StaminaSoundEventBase()
void PlayerSoundEventBase::StaminaSoundEventBase () inline private
Definition at line 4 of file StaminaEvents.c.
  {
    m_Type = EPlayerSoundEventType.STAMINA;
    m_HasPriorityOverTypes = EPlayerSoundEventType.STAMINA;
  }
References m_HasPriorityOverTypes, and m_Type.
SymptomSoundEventBase()
void PlayerSoundEventBase::SymptomSoundEventBase () inline private
Definition at line 3 of file SymptomEvents.c.
  {
    m_Type = EPlayerSoundEventType.GENERAL;
    m_HasPriorityOverTypes = -1;
  }
References m_HasPriorityOverTypes, and m_Type.
Member Data Documentation
MAX_VOLUME
const int PlayerSoundEventBase::MAX_VOLUME = 4 private
Definition at line 3 of file StaminaEvents.c.
The documentation for this class was generated from the following files:
scripts/4_World/Classes/SoundEvents/PlayerSoundEvents/Events/DamageEvents.c
scripts/4_World/Classes/SoundEvents/PlayerSoundEvents/Events/StaminaEvents.c
scripts/4_World/Classes/SoundEvents/PlayerSoundEvents/Events/DrowningEvents.c
scripts/4_World/Classes/SoundEvents/PlayerSoundEvents/Events/HeatComfortEvents.c
scripts/4_World/Classes/SoundEvents/PlayerSoundEvents/Events/HoldBreathEvents.c
scripts/4_World/Classes/SoundEvents/PlayerSoundEvents/Events/InjuryEvents.c
scripts/4_World/Classes/SoundEvents/PlayerSoundEvents/Events/JumpEvents.c
scripts/4_World/Classes/SoundEvents/PlayerSoundEvents/Events/MeleeAttack.c
scripts/4_World/Classes/SoundEvents/PlayerSoundEvents/Events/MiscEvents.c
scripts/4_World/Classes/SoundEvents/PlayerSoundEvents/Events/SymptomEvents.c