DayZ: CfgGameplayHandler Class Reference
CfgGameplayHandler Class Reference
Static Private Member Functions
static void RegisterItem (ITEM_DataBase item)
static void ValidateItems ()
static void InitData ()
static bool LoadData ()
static void OnLoaded ()
static void SyncDataSend (notnull Man player)
static void SyncDataSendEx (notnull PlayerIdentity identity)
static void OnRPC (Man player, ParamsReadContext ctx)
static bool GetDisablePersonalLight ()
static int GetLightingConfig ()
static TStringArray GetObjectSpawnersArr ()
static array< float > GetEnvironmentMinTemps ()
static array< float > GetEnvironmentMaxTemps ()
static array< float > GetWetnessWeightModifiers ()
static bool GetDisableBaseDamage ()
static bool GetDisableContainerDamage ()
static bool GetDisableRespawnDialog ()
static bool GetDisableRespawnInUnconsciousness ()
static float GetSprintStaminaModifierErc ()
static float GetSprintStaminaModifierCro ()
static float GetSprintSwimmingStaminaModifier ()
static float GetSprintLadderStaminaModifier ()
static float GetStaminaWeightLimitThreshold ()
static float GetStaminaMax ()
static float GetStaminaKgToStaminaPercentPenalty ()
static float GetStaminaMinCap ()
static float GetMeleeStaminaModifier ()
static float GetObstacleTraversalStaminaModifier ()
static float GetHoldBreathStaminaModifier ()
static float GetMovementTimeToStrafeJog ()
static float GetMovementTimeToSprint ()
static float GetMovementTimeToStrafeSprint ()
static float GetMovementRotationSpeedJog ()
static float GetMovementRotationSpeedSprint ()
static bool GetDisable2dMap ()
static bool GetDisableIsCollidingBBoxCheck ()
static bool GetDisableIsCollidingPlayerCheck ()
static bool GetDisableIsClippingRoofCheck ()
static bool GetDisableIsBaseViableCheck ()
static bool GetDisableIsInTerrainCheck ()
static bool GetDisableIsUnderwaterCheck ()
static bool GetDisableHeightPlacementCheck ()
static bool GetDisableIsPlacementPermittedCheck ()
static bool GetDisableIsCollidingAngleCheck ()
static bool GetDisableIsCollidingGPlotCheck ()
static bool GetDisableIsCollidingCheck ()
static bool GetDisablePerformRoofCheck ()
static bool GetDisableDistanceCheck ()
static TStringSet GetDisallowedTypesInUnderground ()
static bool GetHitIndicationOverrideEnabled ()
static int GetHitIndicationMode ()
static int GetHitIndicationTypeID ()
static int GetHitIndicationIndicatorColor ()
static float GetHitIndicationMaxDuration ()
static float GetHitIndicationBreakPoint ()
static float GetHitIndicationScatter ()
static bool GetHitIndicationPPEEnabled ()
static bool GetUse3DMap ()
static float GetShockRefillSpeedConscious ()
static float GetShockRefillSpeedUnconscious ()
static bool GetAllowRefillSpeedModifier ()
static bool GetMapIgnoreMapOwnership ()
static bool GetMapIgnoreNavItemsOwnership ()
static bool GetMapDisplayPlayerPosition ()
static bool GetMapDisplayNavigationInfo ()
static float GetStaminaDepletionSpeed ()
static float GetHealthDepletionSpeed ()
static float GetShockDepletionSpeed ()
static bool GetAllowStaminaAffectInertia ()
static TStringArray GetPlayerSpawnGearPresetFiles ()
Static Private Attributes
static string m_Path = "$mission:cfggameplay.json"
static ref array< ref ITEM_DataBase > m_Items = new array<ref ITEM_DataBase>()
static ref CfgGameplayJson m_Data = new CfgGameplayJson()
Detailed Description
Definition at line 1 of file CfgGameplayHandler.c.
Member Function Documentation
GetAllowRefillSpeedModifier()
static bool CfgGameplayHandler::GetAllowRefillSpeedModifier () inline static private
Definition at line 384 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.ShockHandlingData.allowRefillSpeedModifier;
  }
References m_Data.
Referenced by ShockMdfr::OnTick().
GetAllowStaminaAffectInertia()
static bool CfgGameplayHandler::GetAllowStaminaAffectInertia () inline static private
Definition at line 425 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.MovementData.allowStaminaAffectInertia;
  }
References m_Data.
Referenced by ManBase::OnCommandHandlerTick().
GetDisable2dMap()
static bool CfgGameplayHandler::GetDisable2dMap () inline static private
Definition at line 254 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.disable2dMap;
  }
References m_Data.
GetDisableBaseDamage()
static bool CfgGameplayHandler::GetDisableBaseDamage () inline static private
Definition at line 154 of file CfgGameplayHandler.c.
  {
    return m_Data.GeneralData.disableBaseDamage;
  }
References m_Data.
Referenced by Entity::ProcessInvulnerabilityCheck().
GetDisableContainerDamage()
static bool CfgGameplayHandler::GetDisableContainerDamage () inline static private
Definition at line 160 of file CfgGameplayHandler.c.
  {
    return m_Data.GeneralData.disableContainerDamage;
  }
References m_Data.
Referenced by Entity::ProcessInvulnerabilityCheck().
GetDisableDistanceCheck()
static bool CfgGameplayHandler::GetDisableDistanceCheck () inline static private
Definition at line 319 of file CfgGameplayHandler.c.
  {
    return m_Data.BaseBuildingData.ConstructionData.disableDistanceCheck;
  }
References m_Data.
GetDisableHeightPlacementCheck()
static bool CfgGameplayHandler::GetDisableHeightPlacementCheck () inline static private
Definition at line 289 of file CfgGameplayHandler.c.
  {
    return m_Data.BaseBuildingData.HologramData.disableHeightPlacementCheck;
  }
References m_Data.
Referenced by Hologram::HeightPlacementCheck().
GetDisableIsBaseViableCheck()
static bool CfgGameplayHandler::GetDisableIsBaseViableCheck () inline static private
Definition at line 274 of file CfgGameplayHandler.c.
  {
    return m_Data.BaseBuildingData.HologramData.disableIsBaseViableCheck;
  }
References m_Data.
Referenced by Hologram::IsBaseViable().
GetDisableIsClippingRoofCheck()
static bool CfgGameplayHandler::GetDisableIsClippingRoofCheck () inline static private
Definition at line 269 of file CfgGameplayHandler.c.
  {
    return m_Data.BaseBuildingData.HologramData.disableIsClippingRoofCheck;
  }
References m_Data.
Referenced by Hologram::IsClippingRoof().
GetDisableIsCollidingAngleCheck()
static bool CfgGameplayHandler::GetDisableIsCollidingAngleCheck () inline static private
Definition at line 299 of file CfgGameplayHandler.c.
  {
    return m_Data.BaseBuildingData.HologramData.disableIsCollidingAngleCheck;
  }
References m_Data.
Referenced by Hologram::IsCollidingAngle().
GetDisableIsCollidingBBoxCheck()
static bool CfgGameplayHandler::GetDisableIsCollidingBBoxCheck () inline static private
Definition at line 259 of file CfgGameplayHandler.c.
  {
    return m_Data.BaseBuildingData.HologramData.disableIsCollidingBBoxCheck;
  }
References m_Data.
Referenced by Hologram::GetProjectionEntityPosition(), and Hologram::IsCollidingBBox().
GetDisableIsCollidingCheck()
static bool CfgGameplayHandler::GetDisableIsCollidingCheck () inline static private
Definition at line 309 of file CfgGameplayHandler.c.
  {
    return m_Data.BaseBuildingData.ConstructionData.disableIsCollidingCheck;
  }
References m_Data.
Referenced by IsColliding(), and IsCollidingEx().
GetDisableIsCollidingGPlotCheck()
static bool CfgGameplayHandler::GetDisableIsCollidingGPlotCheck () inline static private
Definition at line 304 of file CfgGameplayHandler.c.
  {
    return m_Data.BaseBuildingData.HologramData.disableIsCollidingGPlotCheck;
  }
References m_Data.
Referenced by Hologram::IsCollidingGPlot().
GetDisableIsCollidingPlayerCheck()
static bool CfgGameplayHandler::GetDisableIsCollidingPlayerCheck () inline static private
Definition at line 264 of file CfgGameplayHandler.c.
  {
    return m_Data.BaseBuildingData.HologramData.disableIsCollidingPlayerCheck;
  }
References m_Data.
Referenced by Hologram::IsCollidingPlayer().
GetDisableIsInTerrainCheck()
static bool CfgGameplayHandler::GetDisableIsInTerrainCheck () inline static private
Definition at line 279 of file CfgGameplayHandler.c.
  {
    return m_Data.BaseBuildingData.HologramData.disableIsInTerrainCheck;
  }
References m_Data.
Referenced by Hologram::IsInTerrain().
GetDisableIsPlacementPermittedCheck()
static bool CfgGameplayHandler::GetDisableIsPlacementPermittedCheck () inline static private
Definition at line 294 of file CfgGameplayHandler.c.
  {
    return m_Data.BaseBuildingData.HologramData.disableIsPlacementPermittedCheck;
  }
References m_Data.
Referenced by Hologram::IsPlacementPermitted().
GetDisableIsUnderwaterCheck()
static bool CfgGameplayHandler::GetDisableIsUnderwaterCheck () inline static private
Definition at line 284 of file CfgGameplayHandler.c.
  {
    return m_Data.BaseBuildingData.HologramData.disableIsUnderwaterCheck;
  }
References m_Data.
Referenced by Hologram::IsUnderwater().
GetDisablePerformRoofCheck()
static bool CfgGameplayHandler::GetDisablePerformRoofCheck () inline static private
Definition at line 314 of file CfgGameplayHandler.c.
  {
    return m_Data.BaseBuildingData.ConstructionData.disablePerformRoofCheck;
  }
References m_Data.
Referenced by BaseBuildingBase::PerformRoofCheckForBase().
GetDisablePersonalLight()
static bool CfgGameplayHandler::GetDisablePersonalLight () inline static private
! ===================================================================================== !! the naming convention for static functions in this file is Get+MemberVariableName !! ! =====================================================================================
Definition at line 121 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.disablePersonalLight;
  }
References m_Data.
Referenced by PlayerBase::OnGameplayDataHandlerSync().
GetDisableRespawnDialog()
static bool CfgGameplayHandler::GetDisableRespawnDialog () inline static private
Definition at line 165 of file CfgGameplayHandler.c.
  {
    return m_Data.GeneralData.disableRespawnDialog;
  }
References m_Data.
Referenced by MissionBase::OnGameplayDataHandlerLoad(), and ManBase::OnGameplayDataHandlerSync().
GetDisableRespawnInUnconsciousness()
static bool CfgGameplayHandler::GetDisableRespawnInUnconsciousness () inline static private
Definition at line 170 of file CfgGameplayHandler.c.
  {
    return m_Data.GeneralData.disableRespawnInUnconsciousness;
  }
References m_Data.
Referenced by UIScriptedMenu::ShouldRestartBeVisible(), and UIScriptedMenu::UpdateGUI().
GetDisallowedTypesInUnderground()
static TStringSet CfgGameplayHandler::GetDisallowedTypesInUnderground () inline static private
Definition at line 324 of file CfgGameplayHandler.c.
  {
    return m_Data.BaseBuildingData.HologramData.disallowedTypesInUnderground;
  }
References m_Data.
Referenced by ManBase::CanPlaceItem().
GetEnvironmentMaxTemps()
static array< float > CfgGameplayHandler::GetEnvironmentMaxTemps () inline static private
Definition at line 143 of file CfgGameplayHandler.c.
  {
    return m_Data.WorldsData.environmentMaxTemps;
  }
References m_Data.
Referenced by WorldData::Init().
GetEnvironmentMinTemps()
static array< float > CfgGameplayHandler::GetEnvironmentMinTemps () inline static private
Definition at line 138 of file CfgGameplayHandler.c.
  {
    return m_Data.WorldsData.environmentMinTemps;
  }
References m_Data.
Referenced by WorldData::Init().
GetHealthDepletionSpeed()
static float CfgGameplayHandler::GetHealthDepletionSpeed () inline static private
Definition at line 415 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.DrowningData.healthDepletionSpeed;
  }
References m_Data.
Referenced by DrowningMdfr::OnTick().
GetHitIndicationBreakPoint()
static float CfgGameplayHandler::GetHitIndicationBreakPoint () inline static private
Definition at line 354 of file CfgGameplayHandler.c.
  {
    return m_Data.UIData.HitIndicationData.hitDirectionBreakPointRelative;
  }
References m_Data.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationIndicatorColor()
static int CfgGameplayHandler::GetHitIndicationIndicatorColor () inline static private
Definition at line 344 of file CfgGameplayHandler.c.
  {
    return m_Data.UIData.HitIndicationData.hitDirectionIndicatorColorStr.HexToInt();
  }
References m_Data.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationMaxDuration()
static float CfgGameplayHandler::GetHitIndicationMaxDuration () inline static private
Definition at line 349 of file CfgGameplayHandler.c.
  {
    return m_Data.UIData.HitIndicationData.hitDirectionMaxDuration;
  }
References m_Data.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationMode()
static int CfgGameplayHandler::GetHitIndicationMode () inline static private
Definition at line 334 of file CfgGameplayHandler.c.
  {
    return m_Data.UIData.HitIndicationData.hitDirectionBehaviour;
  }
References m_Data.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationOverrideEnabled()
static bool CfgGameplayHandler::GetHitIndicationOverrideEnabled () inline static private
Definition at line 329 of file CfgGameplayHandler.c.
  {
    return m_Data.UIData.HitIndicationData.hitDirectionOverrideEnabled;
  }
References m_Data.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationPPEEnabled()
static bool CfgGameplayHandler::GetHitIndicationPPEEnabled () inline static private
Definition at line 364 of file CfgGameplayHandler.c.
  {
    return m_Data.UIData.HitIndicationData.hitIndicationPostProcessEnabled;
  }
References m_Data.
Referenced by ManBase::OnGameplayDataHandlerSync().
GetHitIndicationScatter()
static float CfgGameplayHandler::GetHitIndicationScatter () inline static private
Definition at line 359 of file CfgGameplayHandler.c.
  {
    return m_Data.UIData.HitIndicationData.hitDirectionScatter;
  }
References m_Data.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationTypeID()
static int CfgGameplayHandler::GetHitIndicationTypeID () inline static private
Definition at line 339 of file CfgGameplayHandler.c.
  {
    return m_Data.UIData.HitIndicationData.hitDirectionStyle;
  }
References m_Data.
Referenced by HitDirectionEffectBase::CheckValues().
GetHoldBreathStaminaModifier()
static float CfgGameplayHandler::GetHoldBreathStaminaModifier () inline static private
Definition at line 224 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.StaminaData.holdBreathStaminaModifier;
  }
References m_Data.
Referenced by Init().
GetLightingConfig()
static int CfgGameplayHandler::GetLightingConfig () inline static private
Definition at line 128 of file CfgGameplayHandler.c.
  {
    return m_Data.WorldsData.lightingConfig;
  }
References m_Data.
Referenced by ManBase::UpdateLighting().
GetMapDisplayNavigationInfo()
static bool CfgGameplayHandler::GetMapDisplayNavigationInfo () inline static private
Definition at line 405 of file CfgGameplayHandler.c.
  {
    return m_Data.MapData.displayNavInfo;
  }
References m_Data.
Referenced by UIScriptedMenu::Init().
GetMapDisplayPlayerPosition()
static bool CfgGameplayHandler::GetMapDisplayPlayerPosition () inline static private
Definition at line 400 of file CfgGameplayHandler.c.
  {
    return m_Data.MapData.displayPlayerPosition;
  }
References m_Data.
Referenced by UIScriptedMenu::Init().
GetMapIgnoreMapOwnership()
static bool CfgGameplayHandler::GetMapIgnoreMapOwnership () inline static private
Definition at line 390 of file CfgGameplayHandler.c.
  {
    return m_Data.MapData.ignoreMapOwnership;
  }
References m_Data.
Referenced by UIScriptedMenu::CloseMapMenu(), MissionBase::OnUpdate(), and UIScriptedMenu::Update().
GetMapIgnoreNavItemsOwnership()
static bool CfgGameplayHandler::GetMapIgnoreNavItemsOwnership () inline static private
Definition at line 395 of file CfgGameplayHandler.c.
  {
    return m_Data.MapData.ignoreNavItemsOwnership;
  }
References m_Data.
Referenced by UIScriptedMenu::Init(), and UIScriptedMenu::Update().
GetMeleeStaminaModifier()
static float CfgGameplayHandler::GetMeleeStaminaModifier () inline static private
Definition at line 214 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.StaminaData.meleeStaminaModifier;
  }
References m_Data.
Referenced by StaminaHandler::RegisterStaminaModifiers().
GetMovementRotationSpeedJog()
static float CfgGameplayHandler::GetMovementRotationSpeedJog () inline static private
Definition at line 244 of file CfgGameplayHandler.c.
  {
    return Math.Max(0.01, m_Data.PlayerData.MovementData.rotationSpeedJog);
  }
References m_Data, and Math::Max().
GetMovementRotationSpeedSprint()
static float CfgGameplayHandler::GetMovementRotationSpeedSprint () inline static private
Definition at line 249 of file CfgGameplayHandler.c.
  {
    return Math.Max(0.01, m_Data.PlayerData.MovementData.rotationSpeedSprint);
  }
References m_Data, and Math::Max().
GetMovementTimeToSprint()
static float CfgGameplayHandler::GetMovementTimeToSprint () inline static private
Definition at line 234 of file CfgGameplayHandler.c.
  {
    return Math.Max(0.01, m_Data.PlayerData.MovementData.timeToSprint);
  }
References m_Data, and Math::Max().
Referenced by DayZPlayerTypeUtils::DayZPlayerTypeInitMovement().
GetMovementTimeToStrafeJog()
static float CfgGameplayHandler::GetMovementTimeToStrafeJog () inline static private
Definition at line 229 of file CfgGameplayHandler.c.
  {
    return Math.Max(0.01, m_Data.PlayerData.MovementData.timeToStrafeJog);
  }
References m_Data, and Math::Max().
Referenced by DayZPlayerTypeUtils::DayZPlayerTypeInitMovement().
GetMovementTimeToStrafeSprint()
static float CfgGameplayHandler::GetMovementTimeToStrafeSprint () inline static private
Definition at line 239 of file CfgGameplayHandler.c.
  {
    return Math.Max(0.01, m_Data.PlayerData.MovementData.timeToStrafeSprint);
  }
References m_Data, and Math::Max().
Referenced by DayZPlayerTypeUtils::DayZPlayerTypeInitMovement().
GetObjectSpawnersArr()
static TStringArray CfgGameplayHandler::GetObjectSpawnersArr () inline static private
Definition at line 133 of file CfgGameplayHandler.c.
  {
    return m_Data.WorldsData.objectSpawnersArr;
  }
References m_Data.
Referenced by ObjectSpawnerHandler::SpawnObjects().
GetObstacleTraversalStaminaModifier()
static float CfgGameplayHandler::GetObstacleTraversalStaminaModifier () inline static private
Definition at line 219 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.StaminaData.obstacleTraversalStaminaModifier;
  }
References m_Data.
Referenced by StaminaHandler::RegisterStaminaModifiers().
GetPlayerSpawnGearPresetFiles()
static TStringArray CfgGameplayHandler::GetPlayerSpawnGearPresetFiles () inline static private
Definition at line 430 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.spawnGearPresetFiles;
  }
References m_Data.
Referenced by PlayerSpawnHandler::LoadData().
GetShockDepletionSpeed()
static float CfgGameplayHandler::GetShockDepletionSpeed () inline static private
Definition at line 420 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.DrowningData.shockDepletionSpeed;
  }
References m_Data.
Referenced by DrowningMdfr::OnTick().
GetShockRefillSpeedConscious()
static float CfgGameplayHandler::GetShockRefillSpeedConscious () inline static private
Definition at line 374 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.ShockHandlingData.shockRefillSpeedConscious;
  }
References m_Data.
Referenced by ShockMdfr::GetRefillSpeed().
GetShockRefillSpeedUnconscious()
static float CfgGameplayHandler::GetShockRefillSpeedUnconscious () inline static private
Definition at line 379 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.ShockHandlingData.shockRefillSpeedUnconscious;
  }
References m_Data.
Referenced by ShockMdfr::GetRefillSpeed().
GetSprintLadderStaminaModifier()
static float CfgGameplayHandler::GetSprintLadderStaminaModifier () inline static private
Definition at line 189 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.StaminaData.sprintLadderStaminaModifier;
  }
References m_Data.
Referenced by StaminaHandler::StaminaProcessor_Ladder().
GetSprintStaminaModifierCro()
static float CfgGameplayHandler::GetSprintStaminaModifierCro () inline static private
Definition at line 180 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.StaminaData.sprintStaminaModifierCro;
  }
References m_Data.
Referenced by StaminaHandler::StaminaProcessor_Move().
GetSprintStaminaModifierErc()
static float CfgGameplayHandler::GetSprintStaminaModifierErc () inline static private
Definition at line 175 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.StaminaData.sprintStaminaModifierErc;
  }
References m_Data.
Referenced by StaminaHandler::StaminaProcessor_Move().
GetSprintSwimmingStaminaModifier()
static float CfgGameplayHandler::GetSprintSwimmingStaminaModifier () inline static private
Definition at line 185 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.StaminaData.sprintSwimmingStaminaModifier;
  }//----------------------------------------------------------------------------------
References m_Data.
Referenced by StaminaHandler::StaminaProcessor_Swimming().
GetStaminaDepletionSpeed()
static float CfgGameplayHandler::GetStaminaDepletionSpeed () inline static private
Definition at line 410 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.DrowningData.staminaDepletionSpeed;
  }
References m_Data.
GetStaminaKgToStaminaPercentPenalty()
static float CfgGameplayHandler::GetStaminaKgToStaminaPercentPenalty () inline static private
Definition at line 204 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.StaminaData.staminaKgToStaminaPercentPenalty;
  }
References m_Data.
Referenced by StaminaHandler::Update().
GetStaminaMax()
static float CfgGameplayHandler::GetStaminaMax () inline static private
Definition at line 199 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.StaminaData.staminaMax;
  }
References m_Data.
Referenced by StaminaHandler::DepleteStamina(), StaminaHandler::GetStaminaMax(), PlayerStatsPCO_Base::Init(), StaminaHandler::RegisterStaminaModifiers(), StaminaHandler::SetStamina(), Hud::SetStamina(), StaminaHandler::StaminaHandler(), and StaminaHandler::Update().
GetStaminaMinCap()
static float CfgGameplayHandler::GetStaminaMinCap () inline static private
Definition at line 209 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.StaminaData.staminaMinCap;
  }
References m_Data.
Referenced by StaminaHandler::RegisterStaminaConsumers(), and StaminaHandler::Update().
GetStaminaWeightLimitThreshold()
static float CfgGameplayHandler::GetStaminaWeightLimitThreshold () inline static private
Definition at line 194 of file CfgGameplayHandler.c.
  {
    return m_Data.PlayerData.StaminaData.staminaWeightLimitThreshold;
  }
References m_Data.
Referenced by StaminaHandler::Update().
GetUse3DMap()
static bool CfgGameplayHandler::GetUse3DMap () inline static private
Definition at line 369 of file CfgGameplayHandler.c.
  {
    return m_Data.UIData.use3DMap;
  }
References m_Data.
Referenced by UIScriptedMenu::CloseMapMenu(), ManBase::CommandHandler(), MissionBase::HandleMapToggleByKeyboardShortcut(), MissionBase::OnUpdate(), ActionUnfoldMapCB::PerformMapChange(), and ActionUnfoldMapCB::~ActionUnfoldMapCB().
GetWetnessWeightModifiers()
static array< float > CfgGameplayHandler::GetWetnessWeightModifiers () inline static private
Definition at line 147 of file CfgGameplayHandler.c.
  {
    return m_Data.WorldsData.wetnessWeightModifiers;
  }
References m_Data.
Referenced by Entity::GetWetWeightModifier().
InitData()
static void CfgGameplayHandler::InitData () inline static private
Definition at line 29 of file CfgGameplayHandler.c.
  {
    foreach (ITEM_DataBase item: m_Items)
      item.InitServer();
  }
References m_Items.
Referenced by LoadData().
LoadData()
static bool CfgGameplayHandler::LoadData () inline static private
we are allowed to read the file, so we replace the default data with data from json
Definition at line 42 of file CfgGameplayHandler.c.
  {
    if (!FileExist(m_Path))
    {
      m_Path = "";
      GetGame().GetWorldName(m_Path);
      m_Path = string.Format("dz/worlds/%1/ce/cfggameplay.json", m_Path);
    }
    bool cfgGameplayFileEnabled = GetGame().ServerConfigGetInt("enableCfgGameplayFile");
#ifdef DIAG_DEVELOPER
    if (!GetGame().IsDedicatedServer())
      cfgGameplayFileEnabled = true;
#endif
    if (!cfgGameplayFileEnabled || !FileExist(m_Path))
    {
      m_Data.InitServer();//legacy call
      InitData();
      OnLoaded();
      return false;
    }
    string errorMessage;
    if (!JsonFileLoader<CfgGameplayJson>.LoadFile(m_Path, m_Data, errorMessage))
      ErrorEx(errorMessage);
    ValidateItems();
    OnLoaded();
    return true;
  }
References ErrorEx, FileExist(), GetGame(), InitData(), m_Data, m_Path, OnLoaded(), and ValidateItems().
Referenced by MissionBase::OnInit().
OnLoaded()
static void CfgGameplayHandler::OnLoaded () inline static private
Definition at line 77 of file CfgGameplayHandler.c.
  {
    GetGame().GetMission().OnGameplayDataHandlerLoad();
    DayZGame.Cast(GetGame()).OnGameplayDataHandlerLoad();
  }
References GetGame().
Referenced by LoadData().
OnRPC()
static void CfgGameplayHandler::OnRPC (Man player, ParamsReadContext ctx) inline static private
Definition at line 98 of file CfgGameplayHandler.c.
  {
    Param1<CfgGameplayJson> data = new Param1<CfgGameplayJson>(null);
    if (ctx.Read(data))
      m_Data = data.param1;
    else
      ErrorEx("CfgGameplayHandler - client failed to read incoming data");
  }
References ErrorEx, and m_Data.
Referenced by CGame::OnRPC().
RegisterItem()
static void CfgGameplayHandler::RegisterItem (ITEM_DataBase item) inline static private
Definition at line 9 of file CfgGameplayHandler.c.
  {
    m_Items.Insert(item);
  }
References m_Items.
Referenced by ITEM_DataBase::ITEM_DataBase().
SyncDataSend()
static void CfgGameplayHandler::SyncDataSend (notnull Man player) inline static private
Definition at line 84 of file CfgGameplayHandler.c.
  {
    GetGame().RPCSingleParam(player, ERPCs.RPC_CFG_GAMEPLAY_SYNC, new Param1<CfgGameplayJson>(m_Data), true, player.GetIdentity());
  }
References GetGame(), and m_Data.
SyncDataSendEx()
static void CfgGameplayHandler::SyncDataSendEx (notnull PlayerIdentity identity) inline static private
Definition at line 90 of file CfgGameplayHandler.c.
  {
    //Debug.Log("SyncDataSendEx");
    GetGame().RPCSingleParam(null, ERPCs.RPC_CFG_GAMEPLAY_SYNC, new Param1<CfgGameplayJson>(m_Data), true, identity);
  }
References GetGame(), and m_Data.
Referenced by MissionBase::OnEvent().
ValidateItems()
static void CfgGameplayHandler::ValidateItems () inline static private
Definition at line 14 of file CfgGameplayHandler.c.
  {
    foreach (ITEM_DataBase item : m_Items)
    {
      if (!item.ValidateServer())
      {
        string itemName = item.Type().ToString();
        itemName.Replace("ITEM_", "");
        PrintToRPT("Validation failed during loading of 'cfggameplay.json' for " + itemName);
        item.InitServer();
      }
    }
  }
References m_Items, and PrintToRPT().
Referenced by LoadData().
Member Data Documentation
m_Data
ref CfgGameplayJson CfgGameplayHandler::m_Data = new CfgGameplayJson() static private
Definition at line 6 of file CfgGameplayHandler.c.
Referenced by GetAllowRefillSpeedModifier(), GetAllowStaminaAffectInertia(), GetDisable2dMap(), GetDisableBaseDamage(), GetDisableContainerDamage(), GetDisableDistanceCheck(), GetDisableHeightPlacementCheck(), GetDisableIsBaseViableCheck(), GetDisableIsClippingRoofCheck(), GetDisableIsCollidingAngleCheck(), GetDisableIsCollidingBBoxCheck(), GetDisableIsCollidingCheck(), GetDisableIsCollidingGPlotCheck(), GetDisableIsCollidingPlayerCheck(), GetDisableIsInTerrainCheck(), GetDisableIsPlacementPermittedCheck(), GetDisableIsUnderwaterCheck(), GetDisablePerformRoofCheck(), GetDisablePersonalLight(), GetDisableRespawnDialog(), GetDisableRespawnInUnconsciousness(), GetDisallowedTypesInUnderground(), GetEnvironmentMaxTemps(), GetEnvironmentMinTemps(), GetHealthDepletionSpeed(), GetHitIndicationBreakPoint(), GetHitIndicationIndicatorColor(), GetHitIndicationMaxDuration(), GetHitIndicationMode(), GetHitIndicationOverrideEnabled(), GetHitIndicationPPEEnabled(), GetHitIndicationScatter(), GetHitIndicationTypeID(), GetHoldBreathStaminaModifier(), GetLightingConfig(), GetMapDisplayNavigationInfo(), GetMapDisplayPlayerPosition(), GetMapIgnoreMapOwnership(), GetMapIgnoreNavItemsOwnership(), GetMeleeStaminaModifier(), GetMovementRotationSpeedJog(), GetMovementRotationSpeedSprint(), GetMovementTimeToSprint(), GetMovementTimeToStrafeJog(), GetMovementTimeToStrafeSprint(), GetObjectSpawnersArr(), GetObstacleTraversalStaminaModifier(), GetPlayerSpawnGearPresetFiles(), GetShockDepletionSpeed(), GetShockRefillSpeedConscious(), GetShockRefillSpeedUnconscious(), GetSprintLadderStaminaModifier(), GetSprintStaminaModifierCro(), GetSprintStaminaModifierErc(), GetSprintSwimmingStaminaModifier(), GetStaminaDepletionSpeed(), GetStaminaKgToStaminaPercentPenalty(), GetStaminaMax(), GetStaminaMinCap(), GetStaminaWeightLimitThreshold(), GetUse3DMap(), GetWetnessWeightModifiers(), LoadData(), OnRPC(), SyncDataSend(), and SyncDataSendEx().
m_Items
ref array<ref ITEM_DataBase> CfgGameplayHandler::m_Items = new array<ref ITEM_DataBase>() static private
Definition at line 4 of file CfgGameplayHandler.c.
Referenced by InitData(), RegisterItem(), and ValidateItems().
m_Path
string CfgGameplayHandler::m_Path = "$mission:cfggameplay.json" static private
Definition at line 3 of file CfgGameplayHandler.c.
Referenced by LoadData().
The documentation for this class was generated from the following file:
scripts/3_Game/CfgGameplayHandler.c