DayZ: RopeBelt Class Reference
RopeBelt Class Reference
Private Member Functions
override void SetActions ()
override bool CanPutInCargo (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
Detailed Description
Definition at line 1 of file RopeBelt.c.
Member Function Documentation
CanPutInCargo()
override bool RopeBelt::CanPutInCargo (EntityAI parent) inline private
Definition at line 10 of file RopeBelt.c.
  {
    if (!super.CanPutInCargo(parent))
      return false;
    return IsEmpty();
  }
References IsEmpty().
CanReceiveAttachment()
override bool RopeBelt::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 18 of file RopeBelt.c.
  {
    if (!super.CanReceiveAttachment(attachment, slotId))
      return false;
    return !GetInventory().IsInCargo();
  }
SetActions()
override void RopeBelt::SetActions () inline private
Definition at line 3 of file RopeBelt.c.
  {
    super.SetActions();
    AddAction(ActionDeCraftRopeBelt);
  }
References ActionDeCraftRopeBelt(), and AddAction().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Clothing/RopeBelt.c