DayZ: HandEventSwap Class Reference
HandEventSwap Class Reference
Private Member Functions
void HandEventForceSwap (Man p=null, InventoryLocation src=null, InventoryLocation src2=null, InventoryLocation dst=null, InventoryLocation dst2=null)
override bool CheckRequest ()
override bool CanPerformEvent ()
Detailed Description
Definition at line 621 of file Hand_Events.c.
Member Function Documentation
CanPerformEvent()
override bool HandEventSwap::CanPerformEvent () inline private
Definition at line 643 of file Hand_Events.c.
  {
    bool test2 = GameInventory.CanForceSwapEntitiesEx(m_Src.GetItem(), m_Dst, m_Src2.GetItem(), m_Dst2); // null here means 'do not search for dst2' (already have valid one from constructor)
#ifdef DEVELOPER
    if (LogManager.IsInventoryHFSMLogEnable())
    {
      if (!test2)
        Debug.InventoryHFSMLog("CanForceSwapEntitiesEx failed", typename.EnumToString(HandEventID, GetEventID()), "n/a", "CanPerformEvent", m_Player.ToString());
    }
#endif
    return test2;
  }
References GameInventory::CanForceSwapEntitiesEx(), GetEventID(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), m_Player, and m_Src.
CheckRequest()
override bool HandEventSwap::CheckRequest () inline private
Definition at line 625 of file Hand_Events.c.
  {
    bool test1 = false;
    EntityAI inHands = m_Player.GetHumanInventory().GetEntityInHands();
    if (GetSrcEntity() && inHands && m_Dst && m_Dst.IsValid())
    {
      test1 = GameInventory.CheckSwapItemsRequest(m_Player, m_Src, m_Src2, m_Dst, m_Dst2, GameInventory.c_MaxItemDistanceRadius);
#ifdef DEVELOPER
      if (LogManager.IsInventoryHFSMLogEnable())
      {
        if (!test1)
          Debug.InventoryHFSMLog("CheckSwapItemsRequest failed", typename.EnumToString(HandEventID, GetEventID()), "n/a", "CheckRequest", m_Player.ToString());
      }
#endif
    }
    return test1;
  }
References GameInventory::c_MaxItemDistanceRadius, GameInventory::CheckSwapItemsRequest(), GetEventID(), GetSrcEntity(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), m_Player, and m_Src.
HandEventForceSwap()
void HandEventSwap::HandEventForceSwap (Man p = null, InventoryLocation src = null, InventoryLocation src2 = null, InventoryLocation dst = null, InventoryLocation dst2 = null) inline private
Definition at line 623 of file Hand_Events.c.
{ m_EventID = HandEventID.FORCESWAP; }
References m_EventID.
The documentation for this class was generated from the following file:
scripts/3_Game/Systems/Inventory/Hand_Events.c