DayZ: ActionCraftBoltsFeather Class Reference
ActionCraftBoltsFeather Class Reference
Protected Member Functions
void ActionCraftBoltsFeather ()
override void CreateConditionComponents ()
bool IsFeatherType (string itemInHandsType)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStartServer (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Protected Attributes
bool m_IsFeatherInHands
Ammunition_Base m_ResultEntity
Additional Inherited Members
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 11 of file ActionCraftBoltsFeather.c.
Constructor & Destructor Documentation
ActionCraftBoltsFeather()
void ActionCraftBoltsFeather::ActionCraftBoltsFeather () inline protected
Definition at line 16 of file ActionCraftBoltsFeather.c.
  {
    m_CallbackClass = ActionCraftBoltsFeatherCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_CRAFTING;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH;
    m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_HIGH;
    m_Text = "#STR_CraftBolt1";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
Member Function Documentation
ActionCondition()
override bool ActionCraftBoltsFeather::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline protected
Definition at line 39 of file ActionCraftBoltsFeather.c.
  {
    if (IsFeatherType(item.ClassName()))
    {
      //feather in hands
      if (target.GetObject())
        return (target.GetObject().ClassName() == "Ammo_ImprovisedBolt_1");
    }
    else if (target.GetObject())
    {
      // bolt in hands
      return IsFeatherType(target.GetObject().ClassName());
    }
    return false;
  }
References IsFeatherType().
CreateConditionComponents()
override void ActionCraftBoltsFeather::CreateConditionComponents () inline protected
Definition at line 28 of file ActionCraftBoltsFeather.c.
  {
    m_ConditionItem = new CCINonRuined();
    m_ConditionTarget = new CCTNonRuined();
  }
References m_ConditionItem, and m_ConditionTarget.
IsFeatherType()
bool ActionCraftBoltsFeather::IsFeatherType (string itemInHandsType) inline protected
Definition at line 34 of file ActionCraftBoltsFeather.c.
  {
    return itemInHandsType == "ChickenFeather";
  }
Referenced by ActionCondition(), and OnStartServer().
OnFinishProgressServer()
override void ActionCraftBoltsFeather::OnFinishProgressServer (ActionData action_data) inline protected
Definition at line 61 of file ActionCraftBoltsFeather.c.
  {
    ItemBase feather;
    Ammunition_Base bolt;
    bool added = false;
    if (m_IsFeatherInHands)
    {
      //feather in hands
      feather = action_data.m_MainItem;
      bolt = Ammunition_Base.Cast(action_data.m_Target.GetObject());
    }
    else
    {
      // bolt in hands
      bolt = Ammunition_Base.Cast(action_data.m_MainItem);
      feather = ItemBase.Cast(action_data.m_Target.GetObject());
    }
    if (!bolt || !feather)
      return;
    float dmg;
    string type;
    bolt.ServerAcquireCartridge(dmg, type);
    if (m_ResultEntity)
    {
      type = m_ResultEntity.ConfigGetString("Ammo");
      if (m_ResultEntity.GetAmmoCount() < m_ResultEntity.GetAmmoMax())
      {
        m_ResultEntity.ServerStoreCartridge(dmg, type);
        added = true;
      }
    }
    if (!added)
    {
      m_ResultEntity = Ammunition_Base.Cast(action_data.m_Player.SpawnEntityOnGroundPos("Ammo_ImprovisedBolt_2", action_data.m_Player.GetPosition()));
      type = m_ResultEntity.ConfigGetString("Ammo");
      m_ResultEntity.ServerSetAmmoCount(0);
      m_ResultEntity.ServerStoreCartridge(dmg, type);
      m_ResultEntity.SetHealth01("", "", bolt.GetHealth01("", ""));
    }
    feather.AddQuantity(-1);
  }
References m_IsFeatherInHands, and m_ResultEntity.
OnStartServer()
override void ActionCraftBoltsFeather::OnStartServer (ActionData action_data) inline protected
Definition at line 55 of file ActionCraftBoltsFeather.c.
  {
    m_IsFeatherInHands = IsFeatherType(action_data.m_MainItem.ClassName());
    m_ResultEntity = null;
  }
References IsFeatherType(), m_IsFeatherInHands, and m_ResultEntity.
Member Data Documentation
m_IsFeatherInHands
bool ActionCraftBoltsFeather::m_IsFeatherInHands protected
Definition at line 13 of file ActionCraftBoltsFeather.c.
Referenced by OnFinishProgressServer(), and OnStartServer().
m_ResultEntity
Ammunition_Base ActionCraftBoltsFeather::m_ResultEntity protected
Definition at line 14 of file ActionCraftBoltsFeather.c.
Referenced by OnFinishProgressServer(), and OnStartServer().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionCraftBoltsFeather.c