DayZ: CAContinuousTransferQuantity Class Reference
CAContinuousTransferQuantity Class Reference
Protected Member Functions
void CAContinuousTransferQuantity (float quantity_filled_per_second)
override void Setup (ActionData action_data)
override int Execute (ActionData action_data)
override override int Cancel (ActionData action_data)
override float GetProgress ()
void CalcAndSetQuantity (ActionData action_data)
Protected Attributes
float m_TargetUnits
float m_SpentQuantity
float m_ItemQuantity
float m_SourceQuantity
float m_QuantityFilledPerSecond
float m_TimeToComplete
ref Param1< float > m_SpentUnits
Detailed Description
Definition at line 1 of file CAContinuousTransferQuantity.c.
Constructor & Destructor Documentation
CAContinuousTransferQuantity()
void CAContinuousTransferQuantity::CAContinuousTransferQuantity (float quantity_filled_per_second) inline protected
Definition at line 11 of file CAContinuousTransferQuantity.c.
  {
    m_QuantityFilledPerSecond = quantity_filled_per_second;
  }
References m_QuantityFilledPerSecond.
Member Function Documentation
CalcAndSetQuantity()
void CAContinuousTransferQuantity::CalcAndSetQuantity (ActionData action_data) inline protected
Definition at line 73 of file CAContinuousTransferQuantity.c.
  {
    if (GetGame().IsServer())
    {
      if (m_SpentUnits)
      {
        m_SpentUnits.param1 = m_SpentQuantity;
        SetACData(m_SpentUnits);
      }
      action_data.m_MainItem.AddQuantity(m_SpentQuantity);
      ItemBase trg;
      if (Class.CastTo(trg, action_data.m_Target.GetObject()))
        trg.AddQuantity(-m_SpentQuantity, false, false);
    }
  }
References Class::CastTo(), GetGame(), m_SpentQuantity, m_SpentUnits, and CABase::SetACData().
Cancel()
override override int CAContinuousTransferQuantity::Cancel (ActionData action_data) inline protected
Definition at line 57 of file CAContinuousTransferQuantity.c.
  {
    if (!action_data.m_Player)
      return UA_ERROR;
    CalcAndSetQuantity(action_data);
    return UA_CANCEL;
  }
References CalcAndSetQuantity(), UA_CANCEL, and UA_ERROR.
Execute()
override int CAContinuousTransferQuantity::Execute (ActionData action_data) inline protected
Definition at line 31 of file CAContinuousTransferQuantity.c.
  {
    if (!action_data.m_Player)
      return UA_ERROR;
    ItemBase trg;
    Class.CastTo(trg, action_data.m_Target.GetObject());
    if (action_data.m_MainItem.GetQuantity() >= action_data.m_MainItem.GetQuantityMax() || trg.GetQuantity() == 0)
      return UA_FINISHED;
    else
    {
      if (m_SpentQuantity < m_TargetUnits && m_SpentQuantity < m_SourceQuantity)
      {
        m_SpentQuantity += m_QuantityFilledPerSecond * action_data.m_Player.GetDeltaT();
        float val = m_ItemQuantity - m_SpentQuantity;
        if (m_Action) m_Action.SendMessageToClient(action_data.m_Player, val.ToString());
        return UA_PROCESSING;
      }
      else
      {
        CalcAndSetQuantity(action_data);
        OnCompletePogress(action_data);
        return UA_FINISHED;
      }
    }
  }
References CalcAndSetQuantity(), Class::CastTo(), CABase::m_Action, m_ItemQuantity, m_QuantityFilledPerSecond, m_SourceQuantity, m_SpentQuantity, m_TargetUnits, CAContinuousBase::OnCompletePogress(), UA_ERROR, UA_FINISHED, and UA_PROCESSING.
GetProgress()
override float CAContinuousTransferQuantity::GetProgress () inline protected
Definition at line 66 of file CAContinuousTransferQuantity.c.
  {
    float progress = (m_SpentQuantity * m_QuantityFilledPerSecond) / m_TimeToComplete;
    return (m_SpentQuantity * m_QuantityFilledPerSecond) / m_TimeToComplete;
  }
References m_QuantityFilledPerSecond, m_SpentQuantity, and m_TimeToComplete.
Setup()
override void CAContinuousTransferQuantity::Setup (ActionData action_data) inline protected
Definition at line 16 of file CAContinuousTransferQuantity.c.
  {
    m_SpentQuantity = 0;
    if (!m_SpentUnits)
      m_SpentUnits = new Param1<float>(0);
    else
      m_SpentUnits.param1 = 0;
    m_ItemQuantity = action_data.m_MainItem.GetQuantity();
    ItemBase trg;
    if (Class.CastTo(trg, action_data.m_Target.GetObject()))
      m_SourceQuantity = trg.GetQuantity();
    m_TargetUnits = action_data.m_MainItem.GetQuantityMax();
    m_TimeToComplete = (Math.Min((m_TargetUnits - m_ItemQuantity), m_SourceQuantity)) / m_QuantityFilledPerSecond;
  }
References Class::CastTo(), m_ItemQuantity, m_QuantityFilledPerSecond, m_SourceQuantity, m_SpentQuantity, m_SpentUnits, m_TargetUnits, m_TimeToComplete, and Math::Min().
Member Data Documentation
m_ItemQuantity
float CAContinuousTransferQuantity::m_ItemQuantity protected
Definition at line 5 of file CAContinuousTransferQuantity.c.
Referenced by Execute(), and Setup().
m_QuantityFilledPerSecond
float CAContinuousTransferQuantity::m_QuantityFilledPerSecond protected
Definition at line 7 of file CAContinuousTransferQuantity.c.
Referenced by CAContinuousTransferQuantity(), Execute(), GetProgress(), and Setup().
m_SourceQuantity
float CAContinuousTransferQuantity::m_SourceQuantity protected
Definition at line 6 of file CAContinuousTransferQuantity.c.
Referenced by Execute(), and Setup().
m_SpentQuantity
float CAContinuousTransferQuantity::m_SpentQuantity protected
Definition at line 4 of file CAContinuousTransferQuantity.c.
Referenced by CalcAndSetQuantity(), Execute(), GetProgress(), and Setup().
m_SpentUnits
ref Param1<float> CAContinuousTransferQuantity::m_SpentUnits protected
Definition at line 9 of file CAContinuousTransferQuantity.c.
Referenced by CalcAndSetQuantity(), and Setup().
m_TargetUnits
float CAContinuousTransferQuantity::m_TargetUnits protected
Definition at line 3 of file CAContinuousTransferQuantity.c.
Referenced by Execute(), and Setup().
m_TimeToComplete
float CAContinuousTransferQuantity::m_TimeToComplete protected
Definition at line 8 of file CAContinuousTransferQuantity.c.
Referenced by GetProgress(), and Setup().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousTransferQuantity.c