DayZ: ActionInjectTarget Class Reference
ActionInjectTarget Class Reference
Private Member Functions
void ActionInjectTarget ()
override void CreateConditionComponents ()
override void OnExecuteServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void ApplyModifiers (ActionData action_data)
Detailed Description
Definition at line 1 of file ActionInjectTarget.c.
Constructor & Destructor Documentation
ActionInjectTarget()
void ActionInjectTarget::ActionInjectTarget () inline private
Definition at line 3 of file ActionInjectTarget.c.
  {
    m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_MEDIUM;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INJECTIONTARGET;
    m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
    m_Text = "#inject_target";
  }
References AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_MEDIUM.
Member Function Documentation
ApplyModifiers()
override void ActionInjectTarget::ApplyModifiers (ActionData action_data) inline private
Definition at line 37 of file ActionInjectTarget.c.
  {
    action_data.m_MainItem.OnApply(PlayerBase.Cast(action_data.m_Target.GetObject()));
    //PlayerBase ntarget = PlayerBase.Cast( action_data.m_Target.GetObject() );
    //ntarget.GiveShock(100);
  }
Referenced by OnExecuteServer().
CreateConditionComponents()
override void ActionInjectTarget::CreateConditionComponents () inline private
Definition at line 13 of file ActionInjectTarget.c.
  {
    m_ConditionItem = new CCINonRuined;
    m_ConditionTarget = new CCTMan(UAMaxDistances.DEFAULT);
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnEndServer()
override void ActionInjectTarget::OnEndServer (ActionData action_data) inline private
Definition at line 31 of file ActionInjectTarget.c.
  {
    if (action_data.m_WasExecuted && action_data.m_MainItem)
      action_data.m_MainItem.Delete();
  }
OnExecuteServer()
override void ActionInjectTarget::OnExecuteServer (ActionData action_data) inline private
Definition at line 19 of file ActionInjectTarget.c.
  {
    if (CanReceiveAction(action_data.m_Target))
    {
      if (action_data.m_MainItem)
      {
        ApplyModifiers(action_data);
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty(m_SpecialtyWeight);
      }
    }
  }
References ApplyModifiers(), CanReceiveAction(), and m_SpecialtyWeight.
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/Medical/ActionInjectTarget.c