DayZ: scripts/4_World/Entities/ScriptedEntities/Triggers/TrapTrigger.c File Reference
TrapTrigger.c File Reference
Classes
class TrapTrigger
Trigger used by traps.
Functions
TrapTrigger Trigger OnEnterServerEvent (TriggerInsider insider)
void TrapTrigger ()
void SetParentObject (TrapBase obj)
bool CanAddObjectAsInsider (Object object)
void OnLeaveServerEvent (TriggerInsider insider)
void SetEnabled ()
prevents insider adding in the wrong position, HOTFIX
Variables
bool m_Enabled = false
TrapBase m_ParentObj
Function Documentation
CanAddObjectAsInsider()
bool OnEnterServerEvent::CanAddObjectAsInsider (Object object) protected
Definition at line 85 of file TrapTrigger.c.
OnEnterServerEvent()
TrapTrigger Trigger OnEnterServerEvent (TriggerInsider insider)
Definition at line 1 of file TrapTrigger.c.
  {
    PlayerBase playerInsider = PlayerBase.Cast(insider.GetObject());
    if (playerInsider)
    {
      // If the player is jogging / sprinting while standing with or without hands raised, tripwire will trigger
      bool isErect = (playerInsider.m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_ERECT || playerInsider.m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDERECT || playerInsider.m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDCROUCH);
      bool isJogging = (playerInsider.m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_RUN || playerInsider.m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_SPRINT);
      if (isJogging && isErect)
      {
        super.OnEnterServerEvent(insider);
        return;
      }
      // Special handling of crouch sprint
      if (playerInsider.m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_CROUCH && playerInsider.m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_SPRINT)
      {
        super.OnEnterServerEvent(insider);
        return;
      }
    }
    else
      super.OnEnterServerEvent(insider);
  }
OnLeaveServerEvent()
void OnEnterServerEvent::OnLeaveServerEvent (TriggerInsider insider) protected
Definition at line 100 of file TrapTrigger.c.
                  : Trigger
{
  bool m_Enabled = false;
  TrapBase m_ParentObj;
#ifdef DEVELOPER
  bool m_CanSendDbg = true;
#endif
  void TrapTrigger()
  {
    int mask = GetEventMask();
    mask &= ~EntityEvent.INIT;
    SetEventMask(mask);
  }
  void SetParentObject(TrapBase obj)
  {
    if (GetGame().IsServer())
      m_ParentObj = obj;
  }
  override protected bool CanAddObjectAsInsider(Object object)
  {
    return m_Enabled && object.IsInherited(EntityAI) && m_ParentObj && m_ParentObj.IsActive() && m_ParentObj.GetTrapTrigger() == this;
  }
  override protected void OnEnterServerEvent(TriggerInsider insider)
  {
#ifdef DEVELOPER
    m_CanSendDbg = false;
#endif
    if (m_ParentObj && m_ParentObj.IsActive())
      m_ParentObj.SnapOnObject(EntityAI.Cast(insider.GetObject()));
  }
  override protected void OnLeaveServerEvent(TriggerInsider insider)
  {
    if (m_ParentObj && m_ParentObj.IsActive())
      m_ParentObj.RemoveFromObject(EntityAI.Cast(insider.GetObject()));
  }
  void SetEnabled()
  {
    m_Enabled = true;
  }
#ifdef DEVELOPER
  override void DebugSendDmgTrigger()
  {
    if (m_CanSendDbg)
      super.DebugSendDmgTrigger();
  }
#endif
}
// Used for tripwire type traps, where we want to allow players to go through
class TripWireTrigger : TrapTrigger
{
  override protected void OnEnterServerEvent(TriggerInsider insider)
  {
    PlayerBase playerInsider = PlayerBase.Cast(insider.GetObject());
    if (playerInsider)
    {
      // If the player is jogging / sprinting while standing with or without hands raised, tripwire will trigger
      bool isErect = (playerInsider.m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_ERECT || playerInsider.m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDERECT || playerInsider.m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDCROUCH);
      bool isJogging = (playerInsider.m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_RUN || playerInsider.m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_SPRINT);
      if (isJogging && isErect)
      {
        super.OnEnterServerEvent(insider);
        return;
      }
      // Special handling of crouch sprint
      if (playerInsider.m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_CROUCH && playerInsider.m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_SPRINT)
      {
        super.OnEnterServerEvent(insider);
        return;
      }
    }
    else
      super.OnEnterServerEvent(insider);
  }
}
SetEnabled()
void OnEnterServerEvent::SetEnabled () protected
prevents insider adding in the wrong position, HOTFIX
Definition at line 107 of file TrapTrigger.c.
                  : Trigger
{
  bool m_Enabled = false;
  TrapBase m_ParentObj;
#ifdef DEVELOPER
  bool m_CanSendDbg = true;
#endif
  void TrapTrigger()
  {
    int mask = GetEventMask();
    mask &= ~EntityEvent.INIT;
    SetEventMask(mask);
  }
  void SetParentObject(TrapBase obj)
  {
    if (GetGame().IsServer())
      m_ParentObj = obj;
  }
  override protected bool CanAddObjectAsInsider(Object object)
  {
    return m_Enabled && object.IsInherited(EntityAI) && m_ParentObj && m_ParentObj.IsActive() && m_ParentObj.GetTrapTrigger() == this;
  }
  override protected void OnEnterServerEvent(TriggerInsider insider)
  {
#ifdef DEVELOPER
    m_CanSendDbg = false;
#endif
    if (m_ParentObj && m_ParentObj.IsActive())
      m_ParentObj.SnapOnObject(EntityAI.Cast(insider.GetObject()));
  }
  override protected void OnLeaveServerEvent(TriggerInsider insider)
  {
    if (m_ParentObj && m_ParentObj.IsActive())
      m_ParentObj.RemoveFromObject(EntityAI.Cast(insider.GetObject()));
  }
  void SetEnabled()
  {
    m_Enabled = true;
  }
#ifdef DEVELOPER
  override void DebugSendDmgTrigger()
  {
    if (m_CanSendDbg)
      super.DebugSendDmgTrigger();
  }
#endif
}
// Used for tripwire type traps, where we want to allow players to go through
class TripWireTrigger : TrapTrigger
{
  override protected void OnEnterServerEvent(TriggerInsider insider)
  {
    PlayerBase playerInsider = PlayerBase.Cast(insider.GetObject());
    if (playerInsider)
    {
      // If the player is jogging / sprinting while standing with or without hands raised, tripwire will trigger
      bool isErect = (playerInsider.m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_ERECT || playerInsider.m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDERECT || playerInsider.m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDCROUCH);
      bool isJogging = (playerInsider.m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_RUN || playerInsider.m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_SPRINT);
      if (isJogging && isErect)
      {
        super.OnEnterServerEvent(insider);
        return;
      }
      // Special handling of crouch sprint
      if (playerInsider.m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_CROUCH && playerInsider.m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_SPRINT)
      {
        super.OnEnterServerEvent(insider);
        return;
      }
    }
    else
      super.OnEnterServerEvent(insider);
  }
}
Referenced by EntityLightSource::CheckIfParentIsInCargo(), EntityLightSource::Destroy(), SpotLightBase::PerformVisibilityCheck(), and EntityLightSource::ScriptedLightBase().
SetParentObject()
void OnEnterServerEvent::SetParentObject (TrapBase obj)
Definition at line 79 of file TrapTrigger.c.
      {
        super.OnEnterServerEvent(insider);
        return;
TrapTrigger()
void OnEnterServerEvent::TrapTrigger ()
Definition at line 72 of file TrapTrigger.c.
      {
        super.OnEnterServerEvent(insider);
        return;
      }
Variable Documentation
m_Enabled
bool m_Enabled = false
Definition at line 65 of file TrapTrigger.c.
Referenced by ScriptedWidgetEventHandler::Disable(), ScriptedWidgetEventHandler::Enable(), OptionSelectorBase::IsSelectorEnabled(), and OptionSelectorBase::OptionSelector().
m_ParentObj
TrapBase m_ParentObj
Definition at line 66 of file TrapTrigger.c.
Referenced by Trigger::OnEnter(), Trigger::OnLeave(), and Trigger::SetParentObject().