DayZ: ActionRepairCarChassis Class Reference
ActionRepairCarChassis Class Reference
Protected Member Functions
void ActionRepairCarChassis ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override ActionData CreateActionData ()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
Protected Attributes
m_LastValidType
string m_CurrentDamageZone
int m_LastValidComponentIndex
Additional Inherited Members
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 19 of file ActionRepairCarChassis.c.
Constructor & Destructor Documentation
ActionRepairCarChassis()
void ActionRepairCarChassis::ActionRepairCarChassis () inline protected
Definition at line 25 of file ActionRepairCarChassis.c.
  {
    m_CallbackClass = ActionRepairCarChassisCB;
    m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
    m_FullBody = true;
    m_LockTargetOnUse = false;
    m_Text = "#repair";
    m_LastValidComponentIndex = -1;
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_LastValidComponentIndex, m_LockTargetOnUse, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionRepairCarChassis::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline protected
Definition at line 44 of file ActionRepairCarChassis.c.
  {
    if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
      return false;
    CarScript car = CarScript.Cast(target.GetObject());
    if (!car || !player)
      return false;
    if (GetGame().IsMultiplayer() && GetGame().IsServer())
      return true;
    if (m_LastValidType != target.Type() || m_LastValidComponentIndex != target.GetComponentIndex() || m_CurrentDamageZone == "")
    {
      string damageZone = "";
      array<string> selections = new array<string>();
      car.GetActionComponentNameList(target.GetComponentIndex(), selections);
      foreach (string selection : selections)
      {
        //NOTE: relevant fire geometry and view geometry selection names MUST match in order to get a valid damage zone
        if (car && DamageSystem.GetDamageZoneFromComponentName(car, selection, damageZone))
        {
          if (damageZone == "Engine")
            continue;
          int zoneHP = car.GetHealthLevel(damageZone);
          if (zoneHP > GameConstants.STATE_WORN && zoneHP < GameConstants.STATE_RUINED)
          {
            m_CurrentDamageZone = damageZone;
            m_LastValidComponentIndex = target.GetComponentIndex();
            //Determine if using a "Special" item for repairing
            WoodenPlank plank = WoodenPlank.Cast(item);
            Fabric tarp = Fabric.Cast(item);
            //Prevent planks and tarp from repairing non related areas
            if ((tarp || plank) && (damageZone != "BackWood" && damageZone != "BackTarp"))
              return false;
            return true;
          }
        }
      }
    }
    return false;
  }
References GetGame(), m_CurrentDamageZone, m_LastValidComponentIndex, m_LastValidType, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
CreateActionData()
override ActionData ActionRepairCarChassis::CreateActionData () inline protected
Definition at line 144 of file ActionRepairCarChassis.c.
  {
    RepairCarPartActionData actionData = new RepairCarPartActionData();
    return actionData;
  }
CreateConditionComponents()
override void ActionRepairCarChassis::CreateConditionComponents () inline protected
Definition at line 38 of file ActionRepairCarChassis.c.
  {
    m_ConditionItem = new CCINonRuined();
    m_ConditionTarget = new CCTCursor(UAMaxDistances.REPAIR);
  }
References m_ConditionItem, m_ConditionTarget, and UAMaxDistances::REPAIR.
HandleReciveData()
override void ActionRepairCarChassis::HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline protected
Definition at line 182 of file ActionRepairCarChassis.c.
  {
    super.HandleReciveData(action_recive_data, action_data);
    RepairCarPartActionReciveData recieveDataRepair = RepairCarPartActionReciveData.Cast(action_recive_data);
    RepairCarPartActionData.Cast(action_data).m_DamageZone = recieveDataRepair.m_DamageZoneRecived;
  }
OnFinishProgressServer()
override void ActionRepairCarChassis::OnFinishProgressServer (ActionData action_data) inline protected
Definition at line 93 of file ActionRepairCarChassis.c.
  {
    Object tgObject = action_data.m_Target.GetObject();
    string damageZone = RepairCarPartActionData.Cast(action_data).m_DamageZone;
    if (!GetGame().IsMultiplayer())
      damageZone = m_CurrentDamageZone;
    if (tgObject && damageZone != "")
    {
      CarScript car = CarScript.Cast(tgObject);
      if (car)
      {
        int newDmgLevel = Math.Clamp(car.GetHealthLevel(damageZone) - 1, GameConstants.STATE_WORN, GameConstants.STATE_RUINED);
        float zoneMax = car.GetMaxHealth(damageZone, "");
        float randomValue = Math.RandomFloatInclusive(zoneMax * 0.05, zoneMax * 0.15);
        switch (newDmgLevel)
        {
        case GameConstants.STATE_BADLY_DAMAGED:
          car.SetHealth(damageZone, "", (zoneMax * GameConstants.DAMAGE_RUINED_VALUE) + randomValue);
          break;
        case GameConstants.STATE_DAMAGED:
          car.SetHealth(damageZone, "", (zoneMax * GameConstants.DAMAGE_BADLY_DAMAGED_VALUE) + randomValue);
          break;
        case GameConstants.STATE_WORN:
          car.SetHealth(damageZone, "", (zoneMax * GameConstants.DAMAGE_DAMAGED_VALUE) + randomValue);
          break;
        }
        if (action_data.m_MainItem.HasQuantity())
        {
          if (action_data.m_MainItem.GetQuantity() > 1)
          {
            int qnt = action_data.m_MainItem.GetQuantity();
            Fabric usedTarp = Fabric.Cast(action_data.m_MainItem);
            WoodenPlank usedPlank = WoodenPlank.Cast(action_data.m_MainItem);
            if (usedTarp || usedPlank)
              qnt -= 1;
            else
              qnt -= action_data.m_MainItem.GetQuantityMax() * 0.25;
            action_data.m_MainItem.SetQuantity(qnt);
          }
          else
            action_data.m_MainItem.Delete();
        }
      }
    }
  }
References Math::Clamp(), GameConstants::DAMAGE_BADLY_DAMAGED_VALUE, GameConstants::DAMAGE_DAMAGED_VALUE, GameConstants::DAMAGE_RUINED_VALUE, GetGame(), m_CurrentDamageZone, Math::RandomFloatInclusive(), GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
ReadFromContext()
override bool ActionRepairCarChassis::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline protected
Definition at line 162 of file ActionRepairCarChassis.c.
  {
    if (!action_recive_data)
      action_recive_data = new RepairCarPartActionReciveData();
    super.ReadFromContext(ctx, action_recive_data);
    RepairCarPartActionReciveData recieveDataRepair = RepairCarPartActionReciveData.Cast(action_recive_data);
    if (HasTarget())
    {
      string zone;
      if (!ctx.Read(zone))
        return false;
      recieveDataRepair.m_DamageZoneRecived = zone;
    }
    return true;
  }
References HasTarget().
WriteToContext()
override void ActionRepairCarChassis::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline protected
Definition at line 150 of file ActionRepairCarChassis.c.
  {
    super.WriteToContext(ctx, action_data);
    RepairCarPartActionData repairActionData;
    if (HasTarget() && Class.CastTo(repairActionData, action_data))
    {
      repairActionData.m_DamageZone = m_CurrentDamageZone;
      ctx.Write(repairActionData.m_DamageZone);
    }
  }
References Class::CastTo(), HasTarget(), and m_CurrentDamageZone.
Member Data Documentation
m_CurrentDamageZone
string ActionRepairCarChassis::m_CurrentDamageZone protected
Definition at line 22 of file ActionRepairCarChassis.c.
Referenced by ActionCondition(), OnFinishProgressServer(), and WriteToContext().
m_LastValidComponentIndex
int ActionRepairCarChassis::m_LastValidComponentIndex protected
Definition at line 23 of file ActionRepairCarChassis.c.
Referenced by ActionCondition(), and ActionRepairCarChassis().
m_LastValidType
ActionRepairCarChassis::m_LastValidType protected
Definition at line 21 of file ActionRepairCarChassis.c.
Referenced by ActionCondition().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionRepairCarChassis.c