DayZ: scripts/4_World/Entities/ScriptedEntities/Triggers/ContaminatedTrigger.c File Reference
ContaminatedTrigger.c File Reference
Classes
class EffectTrigger
class ContaminatedTrigger_Local
Functions
void ContaminatedTrigger_Dynamic ()
void SetAreaState (int state)
void OnStayClientEvent (TriggerInsider insider, float deltaTime)
override void OnVariablesSynchronized ()
Variables
class ContaminatedTrigger extends EffectTrigger m_AreaState
Function Documentation
ContaminatedTrigger_Dynamic()
void ContaminatedTrigger_Dynamic ()
Definition at line 91 of file ContaminatedTrigger.c.
  {
    RegisterNetSyncVariableInt("m_AreaState");
    // Register in the trigger effect manager
    m_Manager = TriggerEffectManager.GetInstance();
    m_Manager.RegisterTriggerType(this);
  }
References TriggerEffectManager::GetInstance(), and m_Manager.
Referenced by ContaminatedArea_Dynamic::CreateTrigger(), and ContaminatedArea_Dynamic::SetDecayState().
OnStayClientEvent()
void OnStayClientEvent (TriggerInsider insider, float deltaTime) protected
Definition at line 107 of file ContaminatedTrigger.c.
  {
    //no super, overriding parent behaviour
    if (insider.GetObject().IsMan())
    {
      PlayerBase playerInsider = PlayerBase.Cast(insider.GetObject());
      // We will only handle the controlled player, as effects are only relevant to this player instance
      if (playerInsider.IsControlledPlayer())
      {
        // We check if we are not in the standard LIVE state
        bool nonDefaultState = m_AreaState > eAreaDecayStage.LIVE;
        if (nonDefaultState)
        {
          // if not we check the specific state and update local effect values
          int localPartBirthRate;
          if (m_AreaState == eAreaDecayStage.DECAY_START)
            localPartBirthRate = 20;
          else
            localPartBirthRate = 10;
          playerInsider.RequestTriggerEffect(this, m_PPERequester, m_AroundPartId, m_TinyPartId, GetAmbientSoundsetName(), nonDefaultState, localPartBirthRate);
        }
        else
          playerInsider.RequestTriggerEffect(this, m_PPERequester, m_AroundPartId, m_TinyPartId, GetAmbientSoundsetName());
      }
    }
  }
References TriggerInsider::GetObject(), m_AreaState, and m_PPERequester.
OnVariablesSynchronized()
override void OnVariablesSynchronized () protected
Definition at line 137 of file ContaminatedTrigger.c.
  {
    super.OnVariablesSynchronized();
    // Is the controlled player inside when trigger is synchronized
    for (int i = 0; i < GetInsiders().Count(); i++)
    {
      PlayerBase playerInsider = PlayerBase.Cast(m_insiders.Get(i).GetObject());
      if (playerInsider)
      {
        if (playerInsider.IsControlledPlayer())
        {
          // Update Local particle effects
          bool nonDefaultState = m_AreaState > eAreaDecayStage.LIVE;
          if (nonDefaultState)
          {
            int localPartBirthRate;
            if (m_AreaState == eAreaDecayStage.DECAY_START)
              localPartBirthRate = 20;
            else
              localPartBirthRate = 10;
            //Update the local effects
            playerInsider.RequestTriggerEffect(this, m_PPERequester, m_AroundPartId, m_TinyPartId, GetAmbientSoundsetName(), nonDefaultState, localPartBirthRate, true);
          }
          return;
        }
      }
    }
  }
References m_AreaState, and m_PPERequester.
SetAreaState()
void SetAreaState (int state)
Definition at line 100 of file ContaminatedTrigger.c.
  {
    m_AreaState = state;
    SetSynchDirty();
  }
References m_AreaState.
Variable Documentation
m_AreaState
class ContaminatedTrigger extends EffectTrigger m_AreaState
Referenced by OnStayClientEvent(), OnVariablesSynchronized(), and SetAreaState().