DayZ: HitDirectionImagesBase Class Reference
HitDirectionImagesBase Class Reference
Protected Member Functions
void PerformRegisterImages ()
void RegisterImage (string layout_path, string image_name)
void RandomizeImageIdx ()
array< string > GetTypeLayoutPathArray ()
array< string > GetTypeImagePathArray ()
void GetCurrentImageData (out Widget layout, out Widget image)
Layout should be sufficient for generic manipulation of the hit image.
Private Member Functions
void HitDirectionImagesBase ()
Private Attributes
int m_ImageIndex
Detailed Description
Definition at line 2 of file HitDirectionImagesBase.c.
Constructor & Destructor Documentation
HitDirectionImagesBase()
void HitDirectionImagesBase::HitDirectionImagesBase () inline private
Definition at line 6 of file HitDirectionImagesBase.c.
  {
    if ((!GetTypeLayoutPathArray() && !GetTypeImagePathArray()))
      PerformRegisterImages();
    RandomizeImageIdx();
  }
References GetTypeImagePathArray(), GetTypeLayoutPathArray(), PerformRegisterImages(), and RandomizeImageIdx().
Member Function Documentation
GetCurrentImageData()
void HitDirectionImagesBase::GetCurrentImageData (out Widget layout, out Widget image) inline protected
Layout should be sufficient for generic manipulation of the hit image.
Definition at line 38 of file HitDirectionImagesBase.c.
  {
    layout = GetGame().GetWorkspace().CreateWidgets(GetTypeLayoutPathArray()[m_ImageIndex]);
    image = layout.FindAnyWidget(GetTypeImagePathArray()[m_ImageIndex]);
  }
References GetGame(), GetTypeImagePathArray(), GetTypeLayoutPathArray(), and m_ImageIndex.
GetTypeImagePathArray()
array< string > HitDirectionImagesBase::GetTypeImagePathArray () inline protected
Definition at line 35 of file HitDirectionImagesBase.c.
{}
Referenced by GetCurrentImageData(), HitDirectionImagesBase(), RandomizeImageIdx(), and RegisterImage().
GetTypeLayoutPathArray()
array< string > HitDirectionImagesBase::GetTypeLayoutPathArray () inline protected
Definition at line 34 of file HitDirectionImagesBase.c.
{}
Referenced by GetCurrentImageData(), HitDirectionImagesBase(), and RegisterImage().
PerformRegisterImages()
void HitDirectionImagesBase::PerformRegisterImages () inline protected
Definition at line 14 of file HitDirectionImagesBase.c.
  {
    /*
      RegisterImage("gui/layouts/gameplay/HitDirectionIndication.layout","Single_indicator_Splash_1");
      RegisterImage("gui/layouts/gameplay/HitDirectionIndication.layout","Single_indicator_Splash_2");
      ...
    */
  }
Referenced by HitDirectionImagesBase().
RandomizeImageIdx()
void HitDirectionImagesBase::RandomizeImageIdx () inline protected
Definition at line 29 of file HitDirectionImagesBase.c.
  {
    m_ImageIndex = Math.RandomIntInclusive(0, GetTypeImagePathArray().Count() - 1);
  }
References Count, GetTypeImagePathArray(), m_ImageIndex, and Math::RandomIntInclusive().
Referenced by HitDirectionImagesBase().
RegisterImage()
void HitDirectionImagesBase::RegisterImage (string layout_path, string image_name) inline protected
Definition at line 23 of file HitDirectionImagesBase.c.
  {
    GetTypeLayoutPathArray().Insert(layout_path);
    GetTypeImagePathArray().Insert(image_name);
  }
References GetTypeImagePathArray(), and GetTypeLayoutPathArray().
Member Data Documentation
m_ImageIndex
int HitDirectionImagesBase::m_ImageIndex private
Definition at line 4 of file HitDirectionImagesBase.c.
Referenced by GetCurrentImageData(), and RandomizeImageIdx().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/HitIndication/HitDirectionImages/HitDirectionImagesBase.c