DayZ: EntityPlacementCallback Class Reference
EntityPlacementCallback Class Reference
Private Member Functions
void EntityPlacementCallback ()
void ~EntityPlacementCallback ()
void ClearDebugShapes ()
override void OnSetup ()
override void OnDebug (vector p0, vector p1, bool hasHit, bool found)
override bool OnFirstContact (Object other)
override bool OnQuery (Object other)
override bool OnCollide (Object other)
Detailed Description
Definition at line 1 of file EntityPlacementCallback.c.
Constructor & Destructor Documentation
EntityPlacementCallback()
void EntityPlacementCallback::EntityPlacementCallback () inline private
Definition at line 9 of file EntityPlacementCallback.c.
  {
  }
~EntityPlacementCallback()
void EntityPlacementCallback::~EntityPlacementCallback () inline private
Definition at line 13 of file EntityPlacementCallback.c.
  {
    ClearDebugShapes();
  }
References ClearDebugShapes().
Member Function Documentation
ClearDebugShapes()
void EntityPlacementCallback::ClearDebugShapes () inline private
Definition at line 18 of file EntityPlacementCallback.c.
  {
#ifdef DIAG_DEVELOPER
#ifndef SERVER
    foreach (auto shape : m_Shapes)
    {
      shape.Destroy();
      shape = null;
    }
    m_Shapes.Clear();
#endif
#endif
  }
Referenced by OnSetup(), and ~EntityPlacementCallback().
OnCollide()
override bool EntityPlacementCallback::OnCollide (Object other) inline private
Definition at line 128 of file EntityPlacementCallback.c.
  {
    if (other.IsScenery())
      return false;
    if (other.IsMan())
      return false;
    if (!other.CanObstruct() && !other.IsTransport())
      return false;
    return true;
  }
OnDebug()
override void EntityPlacementCallback::OnDebug (vector p0, vector p1, bool hasHit, bool found) inline private
Definition at line 70 of file EntityPlacementCallback.c.
  {
#ifdef DIAG_DEVELOPER
#ifndef SERVER
    Shape shape;
    int alpha = 0x33000000;
    int colour = 0x00FF0000;
    if (!hasHit && found)
      colour = 0x000000FF;
    else if (!hasHit)
    {
      colour = 0x0000FF00;
      alpha = 0x11000000;
    }
    shape = Shape.Create(ShapeType.BBOX, colour | alpha, ShapeFlags.NOZBUFFER | ShapeFlags.TRANSP, -m_Extents, m_Extents);
    shape.SetMatrix(m_Transform);
    m_Shapes.Insert(shape);
    vector p[2];
    p[0] = p0;
    p[1] = p1;
    shape = Shape.CreateLines(colour | 0xFF000000, ShapeFlags.NOZBUFFER | ShapeFlags.TRANSP, p, 2);
    m_Shapes.Insert(shape);
#endif
#endif
  }
References m_Extents, m_Transform, and Shape.
OnFirstContact()
override bool EntityPlacementCallback::OnFirstContact (Object other) inline private
Definition at line 99 of file EntityPlacementCallback.c.
  {
    if (!other.IsTransport())
      return false;
    return true;
  }
OnQuery()
override bool EntityPlacementCallback::OnQuery (Object other) inline private
Definition at line 107 of file EntityPlacementCallback.c.
  {
    if (other.IsScenery())
      return false;
    if (other.IsMan())
      return false;
    EntityAI entity;
    if (Class.CastTo(entity, other))
    {
      if (entity.IsAnimal() || entity.IsZombie())
        return false;
    }
    if (other.GetCollisionRadius() < 0.05)
      return false;
    return true;
  }
References Class::CastTo().
OnSetup()
override void EntityPlacementCallback::OnSetup () inline private
Definition at line 32 of file EntityPlacementCallback.c.
  {
#ifdef DIAG_DEVELOPER
#ifndef SERVER
    m_DebugEnabled = DiagMenu.GetBool(DiagMenuIDs.INVENTORY_ENTITY_PLACEMENT_CALLBACK_DEBUG);
#endif
#endif
    ClearDebugShapes();
    m_DirectionFunc[0] = 1.2;
    m_DirectionFunc[1] = 0.3;
    Human human;
    if (Class.CastTo(human, m_Owner))
    {
      m_OwnerPosition = human.GetBonePositionWS(human.GetBoneIndexByName("Head"));
      HumanInputController hic = human.GetInputController();
      if (hic)
      {
        float headingAngle = hic.GetHeadingAngle() + Math.PI_HALF;
        m_OwnerDirection[0] = Math.Cos(headingAngle);
        m_OwnerDirection[1] = 0.0;
        m_OwnerDirection[2] = Math.Sin(headingAngle);
        m_OwnerDirection.Normalized();
      }
      else
        m_OwnerDirection = human.GetDirection();
    }
    else if (m_Owner)
    {
      m_OwnerPosition = m_Owner.GetPosition();
      m_OwnerDirection = m_Owner.GetDirection();
    }
  }
References Class::CastTo(), ClearDebugShapes(), Math::Cos(), DiagMenu::GetBool(), m_DebugEnabled, m_DirectionFunc, m_Owner, m_OwnerDirection, m_OwnerPosition, vector::Normalized(), Math::PI_HALF, and Math::Sin().
The documentation for this class was generated from the following file:
scripts/4_World/Systems/Inventory/EntityPlacementCallback.c