DayZ: DayZCreature Class Reference
DayZCreature Class Reference
Protected Member Functions
void DayZCreatureAI ()
void IncreaseEffectTriggerCount ()
void DecreaseEffectTriggerCount ()
void AddDamageSphere (AnimDamageParams damage_params)
override void EEKilled (Object killer)
AnimBootsType GetBootsType ()
AbstractWave PlaySound (SoundObject so, SoundObjectBuilder sob)
void OnSoundEvent (int event_id, string event_user_string)
void OnSoundVoiceEvent (int event_id, string event_user_string)
void OnStepEvent (int event_id, string event_user_string)
void OnDamageEvent (int event_id, string event_user_string)
void RegisterAnimEvents ()
void AttenuateSoundIfNecessary (SoundObject soundObject)
bool ResistContaminatedEffect ()
bool IsDanger ()
string CaptureSound ()
string ReleaseSound ()
void CinematicTakeControl (DayZPlayer player)
bool CinematicCanJump ()
override bool ModCommandHandlerBefore (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
Protected Attributes
DayZPlayer m_CinematicPlayer
Private Member Functions
proto native AIAgent GetAIAgent ()
proto native bool IsSoundInsideBuilding ()
proto native void AddDamageSphere (string bone_name, string ammo_name, float radius, float duration, bool invertTeams)
proto native DayZCreatureAIType GetCreatureAIType ()
proto native void InitAIAgent (AIGroup group)
proto native void DestroyAIAgent ()
void ProcessSoundEvent (AnimSoundEvent sound_event)
void ProcessSoundVoiceEvent (AnimSoundVoiceEvent sound_event)
void ProcessStepEvent (AnimStepEvent step_event)
void ProcessDamageEvent (AnimDamageEvent damage_event)
Private Attributes
int m_EffectTriggerCount
Detailed Description
Definition at line 138 of file DayZAnimal.c.
Member Function Documentation
AddDamageSphere() [1/2]
void DayZCreature::AddDamageSphere (AnimDamageParams damage_params) inline protected
Definition at line 179 of file DayZAnimal.c.
  {
    AddDamageSphere(damage_params.m_sBoneName, damage_params.m_sAmmoName, damage_params.m_fRadius, damage_params.m_fDuration, damage_params.m_bInvertTeams);
  }
AddDamageSphere() [2/2]
proto native void DayZCreature::AddDamageSphere (string bone_name, string ammo_name, float radius, float duration, bool invertTeams) private
AttenuateSoundIfNecessary()
void DayZCreature::AttenuateSoundIfNecessary (SoundObject soundObject) inline protected
Definition at line 311 of file DayZAnimal.c.
  {
    if (GetGame().GetPlayer() != NULL && (IsSoundInsideBuilding() != GetGame().GetPlayer().IsSoundInsideBuilding() || GetGame().GetPlayer().IsCameraInsideVehicle()))
      soundObject.SetKind(WaveKind.WAVEATTALWAYS);
    else
      soundObject.SetKind(WaveKind.WAVEEFFECTEX);
  }
References GetGame(), and GetPlayer().
CaptureSound()
string DayZCreature::CaptureSound () inline protected
Definition at line 334 of file DayZAnimal.c.
  {
    return "";
  }
CinematicCanJump()
bool DayZCreature::CinematicCanJump () inline protected
Definition at line 353 of file DayZAnimal.c.
  {
    return true;
  }
CinematicTakeControl()
void DayZCreature::CinematicTakeControl (DayZPlayer player) inline protected
Definition at line 348 of file DayZAnimal.c.
  {
    m_CinematicPlayer = player;
  }
DayZCreatureAI()
void DayZCreature::DayZCreatureAI () inline protected
Definition at line 162 of file DayZAnimal.c.
  {
    RegisterAnimEvents();
    SetFlags(EntityFlags.TOUCHTRIGGERS, false);
  }
References SetFlags().
DecreaseEffectTriggerCount()
void DayZCreature::DecreaseEffectTriggerCount () inline protected
Definition at line 174 of file DayZAnimal.c.
  {
    m_EffectTriggerCount--;
  }
DestroyAIAgent()
proto native void DayZCreature::DestroyAIAgent () private
EEKilled()
override void DayZCreature::EEKilled (Object killer) inline protected
Definition at line 184 of file DayZAnimal.c.
  {
    super.EEKilled(killer);
    CreateComponent(COMP_TYPE_BODY_STAGING); // TO DO: This is never called on clients in multiplayer! That's why skinning doesn't work properly in MP. DAYZ-28269
  }
References COMP_TYPE_BODY_STAGING.
GetAIAgent()
proto native AIAgent DayZCreature::GetAIAgent () private
GetBootsType()
AnimBootsType DayZCreature::GetBootsType () inline protected
Definition at line 190 of file DayZAnimal.c.
  {
    return AnimBootsType.None;
  }
GetCreatureAIType()
proto native DayZCreatureAIType DayZCreature::GetCreatureAIType () private
IncreaseEffectTriggerCount()
void DayZCreature::IncreaseEffectTriggerCount () inline protected
Definition at line 169 of file DayZAnimal.c.
  {
    m_EffectTriggerCount++;
  }
InitAIAgent()
proto native void DayZCreature::InitAIAgent (AIGroup group) private
AIAgent initialization. Manual ai initialization for creatures created with CreateObject(... init_ai = false...).
IsDanger()
bool DayZCreature::IsDanger () inline protected
Definition at line 329 of file DayZAnimal.c.
  {
    return false;
  }
IsSoundInsideBuilding()
proto native bool DayZCreature::IsSoundInsideBuilding () private
ModCommandHandlerBefore()
override bool DayZCreature::ModCommandHandlerBefore (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline protected
sprint
jog
walk
Definition at line 358 of file DayZAnimal.c.
  {
    if (!m_CinematicPlayer)
      return super.ModCommandHandlerBefore(pDt, pCurrentCommandID, pCurrentCommandFinished);
    UAInterface input = m_CinematicPlayer.GetInputInterface();
    DayZCreatureAIInputController controller;
    GetGame().GameScript.CallFunction(this, "GetInputController", controller, 0);
    if (!input || !controller)
      return super.ModCommandHandlerBefore(pDt, pCurrentCommandID, pCurrentCommandFinished);
    float movementX = input.SyncedValue_ID(UAAimRight) - input.SyncedValue_ID(UAAimLeft);
    float maxTurnSpeed = 100.0;
    movementX = Math.Clamp(movementX * maxTurnSpeed * pDt, -180, 180);
    if (input.SyncedValue_ID(UALookAround) > 0)
      movementX = 0;
    bool isJump = input.SyncedValue_ID(UAGetOver) > 0;
    bool isMove = input.SyncedValue_ID(UAMoveForward) > 0;
    bool isRest = input.SyncedValue_ID(UAMoveBack) > 0;
    bool isSleep = input.SyncedValue_ID(UAReloadMagazine) > 0;
    float heading = GetOrientation()[0] + movementX;
    int iAlert = 0;
    float fAlert = 0;
    int iSpeed = 0;
    float fSpeed = 0;
    if (isMove)
    {
      iAlert = 1;
      fAlert = 0.2;
      bool isSprint = input.SyncedValue_ID(UATurbo) > 0;
      bool isJog = input.SyncedValue_ID(UAWalkRunTemp) > 0;
      bool isWalk = !isSprint && !isJog;
      if (isSprint)
      {
        iSpeed = 3;
      }
      else if (isJog)
      {
        iSpeed = 2;
      }
      else if (isWalk)
      {
        iSpeed = 1;
      }
    }
    DayZAnimalInputController animalController;
    if (Class.CastTo(animalController, controller))
    {
      animalController.OverrideBehaviourSlot(true, DayZAnimalBehaviourSlot.NON_SPECIFIC_THREAT);
      animalController.OverrideBehaviourAction(true, DayZAnimalBehaviourAction.TRAVELING_INPUT);
      if (!isMove)
      {
        if (isRest)
        {
          iSpeed = 0;
          animalController.OverrideBehaviourAction(true, DayZAnimalBehaviourAction.IDLE1_INPUT);
        }
        if (isSleep)
        {
          iSpeed = 0;
          animalController.OverrideBehaviourAction(true, DayZAnimalBehaviourAction.WALKING_INPUT);
        }
      }
    }
    bool lowVel = GetVelocity(this).Length() < 0.5;
    if (iSpeed > 0 && lowVel)
    {
      iAlert = 4;
      fAlert = 1.0;
      iSpeed = 3;
    }
    if (animalController)
    {
      switch (iSpeed)
      {
      case 0:
        fSpeed = 0;
        break;
      case 1:
        fSpeed = 2;
        break;
      case 2:
        fSpeed = 3;
        break;
      case 3:
        fSpeed = 5;
        break;
      }
    }
    controller.OverrideTurnSpeed(true, Math.PI2 / pDt);
    controller.OverrideMovementSpeed(true, fSpeed);
    controller.OverrideHeading(true, heading * Math.DEG2RAD);
    controller.OverrideAlertLevel(true, true, iAlert, fAlert);
    if (CinematicCanJump() && isJump)
      controller.OverrideJump(true, 101, 2.0);
    return true;
  }
References Class::CastTo(), Math::Clamp(), Math::DEG2RAD, GetGame(), GetOrientation(), GetVelocity(), and Math::PI2.
OnDamageEvent()
void DayZCreature::OnDamageEvent (int event_id, string event_user_string) inline protected
Definition at line 226 of file DayZAnimal.c.
  {
    AnimDamageEvent damage_event = GetCreatureAIType().GetDamageEvent(event_id);
    if (damage_event != NULL)
      ProcessDamageEvent(damage_event);
  }
OnSoundEvent()
void DayZCreature::OnSoundEvent (int event_id, string event_user_string) inline protected
Definition at line 205 of file DayZAnimal.c.
  {
    AnimSoundEvent sound_event = GetCreatureAIType().GetSoundEvent(event_id);
    if (sound_event != NULL)
      ProcessSoundEvent(sound_event);
  }
OnSoundVoiceEvent()
void DayZCreature::OnSoundVoiceEvent (int event_id, string event_user_string) inline protected
Definition at line 212 of file DayZAnimal.c.
  {
    AnimSoundVoiceEvent voice_event = GetCreatureAIType().GetSoundVoiceEvent(event_id);
    if (voice_event != NULL)
      ProcessSoundVoiceEvent(voice_event);
  }
OnStepEvent()
void DayZCreature::OnStepEvent (int event_id, string event_user_string) inline protected
Definition at line 219 of file DayZAnimal.c.
  {
    AnimStepEvent step_event = GetCreatureAIType().GetStepEvent(event_id);
    if (step_event != NULL)
      ProcessStepEvent(step_event);
  }
PlaySound()
AbstractWave DayZCreature::PlaySound (SoundObject so, SoundObjectBuilder sob) inline protected
Definition at line 195 of file DayZAnimal.c.
  {
    if (so == NULL)
      return NULL;
    so.SetPosition(GetPosition());
    AbstractWave wave = GetGame().GetSoundScene().Play3D(so, sob);
    return wave;
  }
References GetGame(), and GetPosition.
ProcessDamageEvent()
void DayZCreature::ProcessDamageEvent (AnimDamageEvent damage_event) inline private
Definition at line 306 of file DayZAnimal.c.
  {
    AddDamageSphere(damage_event.m_DamageParams);
  }
ProcessSoundEvent()
void DayZCreature::ProcessSoundEvent (AnimSoundEvent sound_event) inline private
Definition at line 251 of file DayZAnimal.c.
  {
    if (!GetGame().IsDedicatedServer())
    {
      SoundObjectBuilder objectBuilder = sound_event.GetSoundBuilder();
      if (NULL != objectBuilder)
      {
        objectBuilder.AddEnvSoundVariables(GetPosition());
        SoundObject soundObject = objectBuilder.BuildSoundObject();
        PlaySound(soundObject, objectBuilder);
      }
    }
    if (GetGame().IsServer())
    {
      if (sound_event.m_NoiseParams != NULL)
        GetGame().GetNoiseSystem().AddNoise(this, sound_event.m_NoiseParams);
    }
  }
References GetGame(), GetPosition, PlaySound(), and SoundObject().
ProcessSoundVoiceEvent()
void DayZCreature::ProcessSoundVoiceEvent (AnimSoundVoiceEvent sound_event) inline private
Definition at line 271 of file DayZAnimal.c.
  {
    if (!GetGame().IsDedicatedServer())
    {
      SoundObjectBuilder objectBuilder = sound_event.GetSoundBuilder();
      if (NULL != objectBuilder)
      {
        objectBuilder.AddEnvSoundVariables(GetPosition());
        SoundObject soundObject = objectBuilder.BuildSoundObject();
        AttenuateSoundIfNecessary(soundObject);
        PlaySound(soundObject, objectBuilder);
      }
    }
    if (GetGame().IsServer())
    {
      if (sound_event.m_NoiseParams != NULL)
        GetGame().GetNoiseSystem().AddNoise(this, sound_event.m_NoiseParams);
    }
  }
References GetGame(), GetPosition, PlaySound(), and SoundObject().
ProcessStepEvent()
void DayZCreature::ProcessStepEvent (AnimStepEvent step_event) inline private
Definition at line 292 of file DayZAnimal.c.
  {
    SoundObjectBuilder soundBuilder = step_event.GetSoundBuilder(GetSurfaceType().Hash());
    if (soundBuilder == NULL)
      return;
    soundBuilder.AddEnvSoundVariables(GetPosition());
    SoundObject soundObject = soundBuilder.BuildSoundObject();
    AttenuateSoundIfNecessary(soundObject);
    PlaySound(soundObject, soundBuilder);
    //TODO effects
  }
References GetPosition, PlaySound(), and SoundObject().
RegisterAnimEvents()
void DayZCreature::RegisterAnimEvents () inline protected
Definition at line 233 of file DayZAnimal.c.
  {
    if (!RegisterAnimationEvent("Sound", "OnSoundEvent"))
      Print("Error registering anim. event (Sound)");
    if (!RegisterAnimationEvent("SoundVoice", "OnSoundVoiceEvent"))
      Print("Error registering anim. event (SoundVoice)");
    if (!GetGame().IsDedicatedServer())
    {
      if (!RegisterAnimationEvent("Step", "OnStepEvent"))
        Print("Error registering anim. event (Step)");
    }
    if (!RegisterAnimationEvent("Damage", "OnDamageEvent"))
      Print("Error registering anim. event (Damage)");
  }
References GetGame(), Print(), and RegisterAnimationEvent().
ReleaseSound()
string DayZCreature::ReleaseSound () inline protected
Definition at line 339 of file DayZAnimal.c.
  {
    return "";
  }
ResistContaminatedEffect()
bool DayZCreature::ResistContaminatedEffect () inline protected
Definition at line 319 of file DayZAnimal.c.
  {
    return false;
  }
Member Data Documentation
m_CinematicPlayer
DayZPlayer DayZCreature::m_CinematicPlayer protected
Definition at line 159 of file DayZAnimal.c.
m_EffectTriggerCount
int DayZCreature::m_EffectTriggerCount private
Definition at line 157 of file DayZAnimal.c.
The documentation for this class was generated from the following file:
scripts/3_Game/Entities/DayZAnimal.c