DayZ: Entity Class Reference
Entity Class Reference
Protected Member Functions
void EntityAI ()
void ~EntityAI ()
void DeferredInit ()
bool IsInitialized ()
int GetHideIconMask ()
should the item's icon be hidden in any part of the inventory?
float ConvertNonlethalDamage (float damage, DamageType damageType)
float ConvertNonlethalDamage (float damage)
DEPRECATED - for legacy purposes.
DamageZoneMap GetEntityDamageZoneMap ()
map< int, string > GetEntityDamageDisplayNameMap ()
bool CanDisplayWeight ()
'displayWeight' in item config
void Log (string msg, string fnc_name="n/a")
Log.
void LogWarning (string msg, string fnc_name="n/a")
LogWarning.
void LogError (string msg, string fnc_name="n/a")
LogError.
bool HasFlammableMaterial ()
Override this method to return TRUE when this item has or can provide fire. Evaluated on server and client.
bool CanBeIgnitedBy (EntityAI igniter=NULL)
Override this method so it checks whenever this item can be ignited right now or not. Evaluated on Server and Client.
bool CanIgniteItem (EntityAI ignite_target=NULL)
Override this method and check if the given item can be ignited right now by this one. Evaluated on Server and Client.
bool IsIgnited ()
Override this method and make it so it returns whenever this item is on fire right now or not. Evaluated on Server and Client.
bool DisassembleOnLastDetach ()
bool IsBasebuildingKit ()
bool PlacementCanBeRotated ()
Should return false if you want to disable hologram rotation.
void OnIgnitedTarget (EntityAI target_item)
Executed on Server when this item ignites some target item.
void OnIgnitedThis (EntityAI fire_source)
Executed on Server when some item ignited this one.
void OnIgnitedTargetFailed (EntityAI target_item)
Executed on Server when this item failed to ignite target item.
void OnIgnitedThisFailed (EntityAI fire_source)
Executed on Server when some item failed to ignite this one.
bool IsTargetIgnitionSuccessful (EntityAI item_target)
Final evaluation just before the target item is actually ignited. Evaluated on Server.
bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
Final evaluation just before this item is actually ignited from fire source. Evaluated on Server.
void OnPlacementStarted (Man player)
void OnHologramBeingPlaced (Man player)
void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
void OnPlacementCancelled (Man player)
bool CanBePlaced (Man player, vector position)
string CanBePlacedFailMessage (Man player, vector position)
Method which returns message why object can't be placed at given position.
bool DoPlacingHeightCheck ()
Do the roof check when placing this?
float HeightCheckOverride ()
used as script-side override of distance for specific height checks
float HeightStartCheckOverride ()
used as script-side override of start pos for specific height checks
bool IsEmpty ()
is this container empty or not, checks both cargo and attachments
bool CanBeSplit ()
bool HasAnyCargo ()
is this container empty or not, checks only cargo
array< EntityAI > GetAttachmentsWithCargo ()
array< EntityAI > GetAttachmentsWithAttachments ()
int GetAgents ()
void RemoveAgent (int agent_id)
void RemoveAllAgents ()
void RemoveAllAgentsExcept (int agent_to_keep)
void InsertAgent (int agent, float count=1)
override bool IsEntityAI ()
bool IsInventoryVisible ()
bool IsPlayer ()
bool IsAnimal ()
bool IsZombie ()
bool IsZombieMilitary ()
bool IsIgnoredByConstruction ()
bool CanBeTargetedByAI (EntityAI ai)
bool CanBeBackstabbed ()
override void Delete ()
Delete this object in next frame.
void DeleteOnClient ()
void DeleteSafe ()
void DeleteSave ()
bool IsSetForDeletion ()
override bool CanBeActionTarget ()
void SetPrepareToDelete ()
bool IsPreparedToDelete ()
void CheckForDestroy ()
bool IsPrepareToDelete ()
bool TryDelete ()
void OnBeforeTryDelete ()
proto native EntityAI GetHierarchyRoot ()
Returns root of current hierarchy (for example: if this entity is in Backpack on gnd, returns Backpack)
proto native Man GetHierarchyRootPlayer ()
Returns root of current hierarchy cast to Man.
proto native EntityAI GetHierarchyParent ()
Returns direct parent of current entity.
proto native CEItemProfile GetEconomyProfile ()
Get economy item profile (if assigned, otherwise null)
int GetHierarchyLevel (int lvl=0)
void OnInventoryInit ()
void EEInit ()
Called upon object creation.
void EEDelete (EntityAI parent)
Called right before object deleting.
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
void OnItemAttachmentSlotChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
void EEParentedTo (EntityAI parent)
Called from 'IEntity.AddChild'.
void EEParentedFrom (EntityAI parent)
Called from 'IEntity.RemoveChild' or 'IEntity.AddChild' when hierarchy changes.
void EEInventoryIn (Man newParentMan, EntityAI diz, EntityAI newParent)
void EEInventoryOut (Man oldParentMan, EntityAI diz, EntityAI newParent)
void EEAmmoChanged ()
void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
void OnDamageDestroyed (int oldLevel)
Called when the health gets to the min value, 'oldLevel' is previous health level, 'oldLevel' -1 means this entity was just spawned.
void AttemptDestructionBehaviour (int oldLevel, int newLevel, string zone)
void SetTakeable (bool pState)
void EEKilled (Object killer)
called on server when the entity is killed
bool ReplaceOnDeath ()
string GetDeadItemName ()
bool KeepHealthOnReplace ()
void DeathUpdate ()
void OnAttachmentRuined (EntityAI attachment)
Called when some attachment of this parent is ruined. Called on server and client side.
void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
void EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos)
void EEItemAttached (EntityAI item, string slot_name)
void SwitchItemSelectionTexture (EntityAI item, string slot_name)
void SwitchItemSelectionTextureEx (EItemManipulationContext context, Param par=null)
void EEItemDetached (EntityAI item, string slot_name)
void EECargoIn (EntityAI item)
void EECargoOut (EntityAI item)
void EECargoMove (EntityAI item)
ScriptInvoker GetOnItemAttached ()
ScriptInvoker GetOnItemDetached ()
ScriptInvoker GetOnItemAddedIntoCargo ()
ScriptInvoker GetOnItemRemovedFromCargo ()
ScriptInvoker GetOnItemMovedInCargo ()
ScriptInvoker GetOnItemFlipped ()
ScriptInvoker GetOnViewIndexChanged ()
ScriptInvoker GetOnSetLock ()
ScriptInvoker GetOnReleaseLock ()
ScriptInvoker GetOnAttachmentSetLock ()
ScriptInvoker GetOnAttachmentReleaseLock ()
ScriptInvoker GetOnHitByInvoker ()
ScriptInvoker GetOnKilledInvoker ()
void OnMovedInsideCargo (EntityAI container)
Called when this item enters cargo of some container.
void OnRemovedFromCargo (EntityAI container)
Called when this item exits cargo of some container.
void OnMovedWithinCargo (EntityAI container)
Called when this item moves within cargo of some container.
void EEOnAfterLoad ()
Called when entity is part of "connected system" and being restored after load.
void EEOnCECreate ()
Called when entity is being created as new by CE/ Debug.
void AfterStoreLoad ()
Called when entity is being loaded from DB or Storage (after all children loaded)
void OnBinLoadItemsDropped ()
Called when an item fails to get loaded into the inventory of an entity and gets dropped.
void HideAllSelections ()
Sets all animation values to 1, making them INVISIBLE if they are configured in models.cfg in such way. These selections must also be defined in the entity's config class in 'AnimationSources'.
void ShowAllSelections ()
Sets all animation values to 0, making them VISIBLE if they are configured in models.cfg in such way. These selections must also be defined in the entity's config class in 'AnimationSources'.
bool CanReceiveAttachment (EntityAI attachment, int slotId)
calls this->CanReceiveAttachment(attachment)
bool CanLoadAttachment (EntityAI attachment)
bool CanPutAsAttachment (EntityAI parent)
calls this->CanPutAsAttachment(parent)
bool CanSwitchDuringAttach (EntityAI parent)
bool CanReleaseAttachment (EntityAI attachment)
calls this->CanReleaseAttachment(attachment)
bool CanDetachAttachment (EntityAI parent)
calls this->CanDetachAttachment(parent)
bool CanBeFSwaped ()
bool CanCombineAttachment (notnull EntityAI e, int slot, bool stack_max_limit=false)
bool CanBeCombined (EntityAI other_item, bool reservation_check=true, bool stack_max_limit=false)
void CombineItemsClient (EntityAI entity2, bool use_stack_max=false)
bool CanReceiveItemIntoCargo (EntityAI item)
calls this->CanReceiveItemIntoCargo(item)
bool CanLoadItemIntoCargo (EntityAI item)
calls this->CanLoadItemIntoCargo(item), is called on server start when loading in the storage
bool CanPutInCargo (EntityAI parent)
calls this->CanPutInCargo(parent)
bool CanSwapItemInCargo (EntityAI child_entity, EntityAI new_entity)
calls this->CanSwapItemInCargo(child_entity, new_entity)
bool CanReleaseCargo (EntityAI cargo)
calls this->CanReleaseCargo(cargo)
bool CanRemoveFromCargo (EntityAI parent)
calls this->CanRemoveFromCargo(parent)
bool CanReceiveItemIntoHands (EntityAI item_to_hands)
calls this->CanReceiveItemIntoHands(item_to_hands)
bool IsBeingPlaced ()
override bool IsHologram ()
bool CanSaveItemInHands (EntityAI item_in_hands)
bool CanPutIntoHands (EntityAI parent)
calls this->CanPutIntoHands(parent)
bool CanReleaseFromHands (EntityAI handheld)
calls this->CanReleaseFromHands(handheld)
bool CanRemoveFromHands (EntityAI parent)
calls this->CanRemoveFromHands(parent)
bool CanDisplayAttachmentSlot (string slot_name)
bool CanDisplayAttachmentSlot (int slot_id)
bool CanDisplayAnyAttachmentSlot ()
bool CanDisplayAttachmentCategory (string category_name)
bool CanDisplayCargo ()
bool CanAssignToQuickbar ()
bool CanAssignAttachmentsToQuickbar ()
bool IgnoreOutOfReachCondition ()
void OnWasAttached (EntityAI parent, int slot_id)
void OnWasDetached (EntityAI parent, int slot_id)
void OnCargoChanged ()
bool IsTakeable ()
proto native GameInventory GetInventory ()
proto native void CreateAndInitInventory ()
proto native void DestroyInventory ()
int GetSlotsCountCorrect ()
EntityAI FindAttachmentBySlotName (string slot_name)
bool IsLockedInSlot ()
bool PredictiveTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
Put item anywhere into this entity (as attachment or into cargo, recursively)
bool LocalTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
bool ServerTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
bool PredictiveTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
bool LocalTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
bool ServerTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
bool PredictiveTakeEntityToCargo (notnull EntityAI item)
Put item into into cargo.
bool LocalTakeEntityToCargo (notnull EntityAI item)
bool ServerTakeEntityToCargo (notnull EntityAI item)
bool PredictiveTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
bool LocalTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
bool ServerTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
bool PredictiveTakeEntityToCargoEx (notnull EntityAI item, int idx, int row, int col)
Put item into into cargo on specific cargo location.
bool LocalTakeEntityToCargoEx (notnull EntityAI item, int idx, int row, int col)
bool PredictiveTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
bool LocalTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
bool ServerTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
bool PredictiveTakeEntityAsAttachmentEx (notnull EntityAI item, int slot)
Returns if item can be added as attachment on specific slot. Note that slot index IS NOT slot ID! Slot ID is defined in DZ/data/config.cpp.
bool LocalTakeEntityAsAttachmentEx (notnull EntityAI item, int slot)
bool ServerTakeEntityAsAttachmentEx (notnull EntityAI item, int slot)
bool PredictiveTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
bool LocalTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
bool ServerTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
bool PredictiveTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
bool LocalTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
bool ServerTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
bool PredictiveTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
bool LocalTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
bool ServerTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
bool PredictiveTakeEntityAsAttachment (notnull EntityAI item)
Put item into as attachment.
bool LocalTakeEntityAsAttachment (notnull EntityAI item)
bool ServerTakeEntityAsAttachment (notnull EntityAI item)
bool PredictiveDropEntity (notnull EntityAI item)
bool LocalDropEntity (notnull EntityAI item)
bool ServerDropEntity (notnull EntityAI item)
EntityAI GetAttachmentByType (typename type)
Get attached entity by type.
EntityAI GetAttachmentByConfigTypeName (string type)
Get attached entity by config type name.
bool CanDropEntity (notnull EntityAI item)
Returns if item can be dropped out from this entity.
EntityAI SpawnInInventoryOrGroundPos (string object_name, GameInventory inv, vector pos)
EntityAI SpawnEntityOnGroundPos (string object_name, vector pos)
EntityAI SpawnEntityOnGround (string object_name, vector mat[4])
bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination)
void SetWet (float value, bool allow_client=false)
void AddWet (float value)
void SetWetMax ()
float GetWet ()
float GetWetMax ()
float GetWetMin ()
float GetWetInit ()
bool HasWetness ()
void OnWetChanged (float newVal, float oldVal)
void OnWetLevelChanged (EWetnessLevel newLevel, EWetnessLevel oldLevel)
EWetnessLevel GetWetLevel ()
float GetQuantity ()
int GetQuantityMax ()
void SetQuantityToMinimum ()
int GetTargetQuantityMax (int attSlotID=-1)
int GetQuickBarBonus ()
void SetTemperature (float value, bool allow_client=false)
void AddTemperature (float value)
void SetTemperatureMax ()
float GetTemperature ()
float GetTemperatureInit ()
float GetTemperatureMin ()
float GetTemperatureMax ()
HiddenSelectionsData GetHiddenSelectionsData ()
int GetHiddenSelectionIndex (string selection)
Returns index of the string found in cfg array 'hiddenSelections'. If it's not found then it returns -1.
override TStringArray GetHiddenSelections ()
Returns the hiddenSelectionsTextures array from the object's config.
override TStringArray GetHiddenSelectionsTextures ()
Returns the hiddenSelectionsTextures array from the object's config.
override TStringArray GetHiddenSelectionsMaterials ()
Returns the hiddenSelectionsMaterials array from the object's config.
proto native void PlaceOnSurfaceRotated (out vector trans[4], vector pos, float dx=0, float dz=0, float fAngle=0, bool align=false)
proto native void RegisterNetSyncVariableBool (string variableName)
registers bool variable synchronized over network
proto native void RegisterNetSyncVariableBoolSignal (string variableName)
when bool variable is true, it's sent to clients and become false again
proto native void RegisterNetSyncVariableInt (string variableName, int minValue=0, int maxValue=0)
registers int variable synchronized over network
proto native void RegisterNetSyncVariableFloat (string variableName, float minValue=0, float maxValue=0, int precision=1)
registers float variable synchronized over network
proto native void RegisterNetSyncVariableObject (string variableName)
registers object variable synchronized over network, only synchronizes if network id is assigned. Doesn't handle object despawn on client
proto native void UpdateNetSyncVariableInt (string variableName, float minValue=0, float maxValue=0)
proto native void UpdateNetSyncVariableFloat (string variableName, float minValue=0, float maxValue=0, int precision=1)
proto native void SwitchLight (bool isOn)
proto native void SetSimpleHiddenSelectionState (int index, bool state)
Simple hidden selection state; 0 == hidden.
proto native bool IsSimpleHiddenSelectionVisible (int index)
proto native void SetObjectTexture (int index, string texture_name)
Change texture in hiddenSelections.
proto native owned string GetObjectTexture (int index)
proto native void SetObjectMaterial (int index, string mat_name)
Change material in hiddenSelections.
proto native owned string GetObjectMaterial (int index)
proto native bool IsPilotLight ()
proto native void SetPilotLight (bool isOn)
void OnStoreSave (ParamsWriteContext ctx)
Engine calls this function to collect data from entity to store for persistence (on server side).
bool OnStoreLoad (ParamsReadContext ctx, int version)
Called when data is loaded from persistence (on server side).
proto native void SetSynchDirty ()
Sets object synchronization dirty flag, which signalize that object wants to be synchronized (take effect only in MP on server side)
void OnVariablesSynchronized ()
Called on clients after receiving synchronization data from server.
proto native void SetAITargetCallbacks (AbstractAITargetCallbacks callbacks)
override void EOnFrame (IEntity other, float timeSlice)
string GetDebugText ()
void GetDebugButtonNames (out string button1, out string button2, out string button3, out string button4)
void OnDebugButtonPressClient (int button_index)
void OnDebugButtonPressServer (int button_index)
Shape DebugBBoxDraw ()
void DebugBBoxSetColor (int color)
void DebugBBoxDelete ()
Shape DebugDirectionDraw (float distance=1)
void DebugDirectionSetColor (int color)
void DebugDirectionDelete ()
void HideSelection (string selection_name)
Hides selection of the given name. Must be configed in config.cpp and models.cfg.
void ShowSelection (string selection_name)
Shows selection of the given name. Must be configed in config.hpp and models.cfg.
proto void GetPersistentID (out int b1, out int b2, out int b3, out int b4)
proto native void SetLifetime (float fLifeTime)
Set (override) remaining economy lifetime (seconds)
proto native float GetLifetime ()
Get remaining economy lifetime (seconds)
proto native void IncreaseLifetime ()
Reset economy lifetime to default (seconds)
proto native void SetLifetimeMax (float fLifeTime)
Set (override) max economy lifetime per entity instance (seconds)
proto native float GetLifetimeMax ()
Get max economy lifetime per instance - default is from DB (seconds)
void IncreaseLifetimeUp ()
Reset economy lifetime to default across entity hierarchy all the way to the topmost entity.
ComponentBodyStaging GetCompBS ()
Use this to access Body Staging component on dead character. Returns NULL if the given object lacks such component.
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
float GetWetWeightModifier ()
float GetConfigWeightModified ()
int GetWeight ()
void ClearWeightDirty ()
void SetWeightDirty ()
float GetInventoryAndCargoWeight (bool forceRecalc=false)
float GetWeightSpecialized (bool forceRecalc=false)
returns weight of the entity in a way that's specific to the entity type and is internal to the weight system calculation, to obtain entity's weight, use the 'GetWeightEx' method instead
float GetWeightEx (bool forceRecalc=false)
returns overall weight of the entity, 'forceRecalc = true' is meant to be used only when debugging, using it in gameplay code is higly inadvisable as it bypasses the weight caching and has adverse effect on performance
void UpdateWeight (WeightUpdateType updateType=WeightUpdateType.FULL, float weightAdjustment=0)
float GetSingleInventoryItemWeightEx ()
void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
bool OnAction (int action_id, Man player, ParamsReadContext ctx)
string GetHitComponentForAI ()
Returns hit component for the Entity (overriden for each Type - PlayerBase, DayZInfected, DayZAnimal, etc.)
string GetDefaultHitComponent ()
returns default hit component for the Entity (overriden for each Type - PlayerBase, DayZInfected, DayZAnimal, etc.)
string GetDefaultHitPositionComponent ()
returns default hit position component name for the Entity (overriden by type if needed - used mainly as support for impact particles)
array< string > GetSuitableFinisherHitComponents ()
vector GetDefaultHitPosition ()
int GetMeleeTargetType ()
value is related to EMeleeTargetType
string GetAttachmentSoundType ()
returns sound type of attachment (used for clothing and weapons on DayZPlayerImplement, paired with Anim*Type enum from DayZAnimEvents)
bool IsHeavyBehaviour ()
returns item behaviour of item (more in ItemBase)
bool IsOneHandedBehaviour ()
returns item behaviour of item (more in ItemBase)
bool IsTwoHandedBehaviour ()
returns item behaviour of item (more in ItemBase)
string ChangeIntoOnAttach (string slot)
string ChangeIntoOnDetach ()
void OnCEUpdate ()
Central economy calls this function whenever going over all the entities.
void OnDebugSpawnEx (DebugSpawnParams params)
void OnDebugSpawn ()
override EntityAI ProcessMeleeItemDamage (int mode=0)
float GetLiquidThroughputCoef ()
Returns liquid throughput coeficient.
string GetInvulnerabilityTypeString ()
void ProcessInvulnerabilityCheck (string servercfg_param)
void SetBayonetAttached (bool pState, int slot_idx=-1)
bool HasBayonetAttached ()
int GetBayonetAttachmentIdx ()
void SetButtstockAttached (bool pState, int slot_idx=-1)
bool HasButtstockAttached ()
int GetButtstockAttachmentIdx ()
void SetInvisibleRecursive (bool invisible, EntityAI parent=null, array< int > attachments=null)
void SoundHardTreeFallingPlay ()
void SoundSoftTreeFallingPlay ()
void SoundHardBushFallingPlay ()
void SoundSoftBushFallingPlay ()
void RegisterTransportHit (Transport transport)
bool GetInventoryHandAnimation (notnull InventoryLocation loc, out int value)
bool TranslateSlotFromSelection (string selection_name, out int slot_id)
bool IsUniversalTemperatureSource ()
Universal Temperature Sources Helpers.
UTemperatureSource GetUniversalTemperatureSource ()
void SetUniversalTemperatureSource (UTemperatureSource uts)
vector GetUniversalTemperatureSourcePosition ()
RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
Remotely controlled devices helpers.
void PairRemote (notnull EntityAI trigger)
void UnpairRemote ()
EntityAI GetPairDevice ()
void SetPersistentPairID (int id)
bool HasTurnableValveBehavior ()
Turnable Valve behaviour.
bool IsValveTurnable (int pValveIndex)
int GetTurnableValveIndex (int pComponentIndex)
void ExecuteActionsConnectedToValve (int pValveIndex)
set< int > GetAttachmentExclusionInitSlotValue (int slotId)
override this to modify slot behavior for specific items, or just set 'm_AttachmentExclusionMaskGlobal' value for simple items
void InitLegacyConfigExclusionValues ()
bool InitLegacyExclusionCheck ()
void InitLegacySlotExclusionValuesImplicit ()
adding base one-directional relations between headgear, masks, eyewear, and headstraps (exception)
void InitLegacySlotExclusionValuesDerived ()
void InitGlobalExclusionValues ()
override to init part of the mask, independent of slot-specific behavior
void AddSingleExclusionValueGlobal (EAttExclusions value)
to help with item staging exclusions
void ClearSingleExclusionValueGlobal (EAttExclusions value)
to help with item staging exclusions
void SetAttachmentExclusionMaskGlobal (set< int > values)
void SetAttachmentExclusionMaskSlot (int slotId, set< int > values)
sets values for specific slot
bool IsExclusionFlagPresent (set< int > values)
checks 'this' if the incoming flag is present for the current state (slot behavior and others)
bool IsExclusionFlagPresentRecursive (set< int > values, int targetSlot)
Gets flag from what is effectively an owner.
bool CheckExclusionAccessCondition (int occupiedSlot, int targetSlot, set< int > value, inout set< int > adjustedValue)
void AdjustExclusionAccessCondition (int occupiedSlot, int testedSlot, set< int > value, inout set< int > adjustedValue)
if we want to filter
bool CheckExclusionAccessPropagation (int occupiedSlot, int targetSlot, set< int > value, inout set< int > adjustedValue)
special propagation contition
void AdjustExclusionAccessPropagation (int occupiedSlot, int testedSlot, set< int > value, inout set< int > adjustedValue)
if we want to filter propagation specifically; DO NOT override unless you know what you are doing.
bool IsManagingArrows ()
ArrowManagerBase GetArrowManager ()
void SetFromProjectile (ProjectileStoppedInfo info)
void ClearInventory ()
bool IsSkinned ()
Skinning.
void SetAsSkinned ()
bool CanBeSkinnedWith (EntityAI tool)
ComponentEnergyManager GetCompEM ()
bool HasEnergyManager ()
If this item has class EnergyManager in its config then it returns true. Otherwise returns false.
void OnWorkStart ()
Energy manager event: Called only once when this device starts doing its work.
void OnWork (float consumed_energy)
Energy manager event: Called every device update if its supposed to do some work. The update can be every second or at random, depending on its manipulation.
void OnWorkStop ()
Energy manager event: Called when the device stops working (was switched OFF or ran out of energy)
void OnSwitchOn ()
Energy manager event: Called when the device is switched on.
void OnSwitchOff ()
Energy manager event: Called when the device is switched OFF.
void OnIsPlugged (EntityAI source_device)
Energy manager event: Called when this device is plugged into some energy source.
void OnIsUnplugged (EntityAI last_energy_source)
Energy manager event: Called when this device is UNPLUGGED from the energy source.
void OnOwnSocketTaken (EntityAI device)
Energy manager event: When something is plugged into this device.
void OnOwnSocketReleased (EntityAI device)
Energy manager event: When something is UNPLUGGED from this device.
void OnInitEnergy ()
Energy manager event: Object's initialization. Energy Manager is fully initialized by this point.
void OnEnergyConsumed ()
Energy manager event: Called when energy was consumed on this device. ALWAYS CALL super.OnEnergyConsumed() !!!
void OnEnergyAdded ()
Energy manager event: Called when energy was added on this device. ALWAYS CALL super.OnEnergyAdded() !!!
Static Protected Member Functions
static EWetnessLevel GetWetLevelInternal (float wetness)
Protected Attributes
ref DamageZoneMap m_DamageZoneMap
bool m_CanDisplayWeight
float m_ElapsedSinceLastUpdate
UTemperatureSource m_UniversalTemperatureSource
bool m_PendingDelete = false
bool m_Initialized = false
bool m_TransportHitRegistered = false
vector m_TransportHitVelocity
ref ScriptInvoker m_OnItemAttached
ref ScriptInvoker m_OnItemDetached
ref ScriptInvoker m_OnItemAddedIntoCargo
ref ScriptInvoker m_OnItemRemovedFromCargo
ref ScriptInvoker m_OnItemMovedInCargo
ref ScriptInvoker m_OnItemFlipped
ref ScriptInvoker m_OnViewIndexChanged
ref ScriptInvoker m_OnSetLock
ref ScriptInvoker m_OnReleaseLock
ref ScriptInvoker m_OnAttachmentSetLock
ref ScriptInvoker m_OnAttachmentReleaseLock
ref ScriptInvoker m_OnHitByInvoker
ref ScriptInvoker m_OnKilledInvoker
Private Member Functions
proto native void SetNearPlane (float nearPlane)
proto native float GetNearPlane ()
proto native void SetActive (bool active)
Sets this camera as active.
proto native bool IsActive ()
Is this camera active?
proto native void SetFOV (float fov)
Field of View settings.
proto native void SetFocus (float distance, float blur)
Depth of Field settings.
proto native void LookAt (vector targetPos)
Orientation change by lookAt point.
Component CreateComponent (int comp_type, string extended_class_name="")
CreateComponent.
Component GetComponent (int comp_type, string extended_class_name="")
GetComponent.
bool DeleteComponent (int comp_type)
DeleteComponent.
string GetDestructionBehaviour ()
bool IsDestructionBehaviour ()
bool HasComponent (int comp_type)
IsComponentExist.
void MaxLifetimeRefreshCalc ()
Calculates if the max lifetime is higher than refresher frequency (i.e. gets kept alive by refresher)
bool IsRefresherSignalingViable ()
void InitDamageZoneMapping ()
Initializes script-side map of damage zones and their components (named selections in models)
void InitDamageZoneDisplayNameMapping ()
Initialize map of damage zone display names for more optimized retrieval.
void InitAttachmentExclusionValues ()
void InitInherentSlotExclusionMap ()
map stored on instance to better respond to various state changes
void PropagateExclusionValueRecursive (set< int > values, int slotId)
void ClearExclusionValueRecursive (set< int > values, int slotId)
set< int > GetAttachmentExclusionMaskAll (int slotId)
Slot-specific, children (attachments), and additional (state etc.) masks combined.
set< int > GetAttachmentExclusionMaskSlot (int slotId)
Specific slot behavior.
set< int > GetAttachmentExclusionMaskGlobal ()
Global mask value, independent of slot-specific behavior!
set< int > GetAttachmentExclusionMaskChildren ()
Mask value coming from the item's attachments.
bool HasInternalExclusionConflicts (int targetSlot)
checks if any attachment or item state would interfere with this being attached into a different slot (Headgear -> Mask)
proto native void SetLightType (int pType)
proto native int GetLightType ()
proto native void SetEnabled (bool pState)
proto native bool IsEnabled ()
proto native void SetCastShadow (bool pState)
proto native bool GetCastShadow ()
proto native bool EnableSpecular (bool pState)
proto native bool EnableLinear (bool pState)
proto native void SetPulseCoef (float pState)
proto native void SetVisibleDuringDaylight (bool pState)
proto native bool IsVisibleDuringDaylight ()
proto native void SetRadius (float pValue)
proto native float GetRadius ()
proto native void EnableHeatHaze (bool pState)
proto native void SetHeatHazeRadius (float pValue)
proto native float GetHeatHazeRadius ()
proto native void SetHeatHazePower (float pValue)
proto native float GetHeatHazePower ()
proto native void SetDiffuseColor (float pRed, float pGreen, float pBlue)
proto native void SetDiffuseColorV (vector pColorVector)
proto native void SetDiffuseAlpha (float pAlpha)
proto native vector GetDiffuseColorV ()
proto native float GetDiffuseAlpha ()
proto native void SetAmbientColor (float pRed, float pGreen, float pBlue)
proto native void SetAmbientColorV (vector pColorVector)
proto native void SetAmbientAlpha (float pAlpha)
proto native vector GetAmbientColorV ()
proto native float GetAmbientAlpha ()
proto native void SetBrightness (float pValue)
proto native float GetBrightness ()
proto native void SetFlareVisible (bool pState)
proto native bool IsFlareVisible ()
proto native void SetFlareRelPosition (vector pPosition)
proto native vector GetFlareRelPosition ()
proto native void SetSpotLightAngle (float pValue)
proto native float GetSpotLightAngle ()
proto native float GetSoundLength ()
Static Private Member Functions
static proto native Camera GetCurrentCamera ()
Returns active Camera instance (note: player's camera is not Camera instance - thus it return null)
static proto native float GetCurrentFOV ()
Returns FOV of current camera object.
static proto native void InterpolateTo (Camera targetCamera, float time, int type)
Interpolation between camera instances (current camera becomes targetCamera at the end of interpolation)
Private Attributes
bool m_DeathSyncSent
bool m_KilledByHeadshot
bool m_PreparedToDelete = false
bool m_RefresherViable = false
bool m_WeightDirty = 1
ref map< int, ref set< int > > m_AttachmentExclusionSlotMap
ref set< int > m_AttachmentExclusionMaskGlobal
ref set< int > m_AttachmentExclusionMaskChildren
ref DestructionEffectBase m_DestructionBehaviourObj
ref KillerData m_KillerData
ref HiddenSelectionsData m_HiddenSelectionsData
const int DEAD_REPLACE_DELAY = 2000
const int DELETE_CHECK_DELAY = 100
ref array< EntityAI > m_AttachmentsWithCargo
ref array< EntityAI > m_AttachmentsWithAttachments
ref InventoryLocation m_OldLocation
ref map< int, string > m_DamageDisplayNameMap = new map<int, string>
float m_Weight
float m_WeightEx
float m_ConfigWeight = ConfigGetInt("weight")
float m_LastUpdatedTime
ref ComponentsBank m_ComponentsBank
ComponentEnergyManager m_EM
int m_ViewIndex = 0
void SetViewIndex (int index)
Sets item preview index.
int GetViewIndex ()
Returns item preview index !!!! IF OVERRIDING with more dynamic events call GetOnViewIndexChanged() in constructor on client !!!!
Detailed Description
Definition at line 1 of file Camera.c.
Constructor & Destructor Documentation
~EntityAI()
void Entity::~EntityAI () inline protected
Definition at line 204 of file EntityAI.c.
  {
  }
Member Function Documentation
AddSingleExclusionValueGlobal()
void Entity::AddSingleExclusionValueGlobal (EAttExclusions value) inline protected
to help with item staging exclusions
Definition at line 3347 of file EntityAI.c.
  {
    if (m_AttachmentExclusionMaskGlobal.Find(value) == -1)
      m_AttachmentExclusionMaskGlobal.Insert(value);
  }
AddTemperature()
void Entity::AddTemperature (float value) inline protected
Definition at line 1973 of file EntityAI.c.
{};
AddWet()
void Entity::AddWet (float value) protected
AdjustExclusionAccessCondition()
void Entity::AdjustExclusionAccessCondition (int occupiedSlot, int testedSlot, set< int > value, inout set< int > adjustedValue) inline protected
if we want to filter
Definition at line 3523 of file EntityAI.c.
  {
    adjustedValue = value;
  }
AdjustExclusionAccessPropagation()
void Entity::AdjustExclusionAccessPropagation (int occupiedSlot, int testedSlot, set< int > value, inout set< int > adjustedValue) inline protected
if we want to filter propagation specifically; DO NOT override unless you know what you are doing.
Definition at line 3545 of file EntityAI.c.
  {
    AdjustExclusionAccessCondition(occupiedSlot, testedSlot, value, adjustedValue);
  }
AfterStoreLoad()
void Entity::AfterStoreLoad () inline protected
Called when entity is being loaded from DB or Storage (after all children loaded)
Definition at line 1183 of file EntityAI.c.
  {
  }
AttemptDestructionBehaviour()
void Entity::AttemptDestructionBehaviour (int oldLevel, int newLevel, string zone) inline protected
Definition at line 863 of file EntityAI.c.
  {
    if (IsDestructionBehaviour() && GetDestructionBehaviour())
    {
      typename destType = GetDestructionBehaviour().ToType();
      if (destType)
      {
        if (!m_DestructionBehaviourObj)
          m_DestructionBehaviourObj = DestructionEffectBase.Cast(destType.Spawn());
        if (m_DestructionBehaviourObj)
          m_DestructionBehaviourObj.OnHealthLevelChanged(this, oldLevel, newLevel, zone);
      }
      else
        ErrorEx("Incorrect destruction behaviour type, make sure the class returned in 'GetDestructionBehaviour()' is a valid type inheriting from 'DestructionEffectBase'");
    }
  }
References ErrorEx, GetDestructionBehaviour(), and IsDestructionBehaviour().
CanAssignAttachmentsToQuickbar()
Entity::CanAssignAttachmentsToQuickbar () inline protected
Returns
true if attached item can be assigned to quickbar safely
Definition at line 1550 of file EntityAI.c.
  {
    return true;
  }
CanAssignToQuickbar()
Entity::CanAssignToQuickbar () inline protected
Returns
true if item can be assigned to quickbar safely
Definition at line 1542 of file EntityAI.c.
  {
    return true;
  }
CanBeActionTarget()
override bool Entity::CanBeActionTarget () inline protected
Definition at line 662 of file EntityAI.c.
  {
    if (super.CanBeActionTarget())
      return !IsSetForDeletion();
    else
      return false;
  }
CanBeBackstabbed()
bool Entity::CanBeBackstabbed () inline protected
Definition at line 613 of file EntityAI.c.
  {
    return false;
  }
CanBeCombined()
bool Entity::CanBeCombined (EntityAI other_item, bool reservation_check = true, bool stack_max_limit = false) inline protected
Definition at line 1325 of file EntityAI.c.
  {
    return false;
  }
CanBeFSwaped()
bool Entity::CanBeFSwaped () inline protected
Definition at line 1312 of file EntityAI.c.
  {
    return true;
  }
CanBeIgnitedBy()
bool Entity::CanBeIgnitedBy (EntityAI igniter = NULL) inline protected
Override this method so it checks whenever this item can be ignited right now or not. Evaluated on Server and Client.
Definition at line 423 of file EntityAI.c.
  {
    return false;
  }
CanBePlaced()
bool Entity::CanBePlaced (Man player, vector position) inline protected
Definition at line 502 of file EntityAI.c.
  {
    return true;
  }
CanBePlacedFailMessage()
string Entity::CanBePlacedFailMessage (Man player, vector position) inline protected
Method which returns message why object can't be placed at given position.
Definition at line 508 of file EntityAI.c.
  {
    return "";
  }
CanBeSkinnedWith()
bool Entity::CanBeSkinnedWith (EntityAI tool) inline protected
Definition at line 406 of file EntityAI.c.
  {
    if (!IsSkinned() && tool)
      if (!IsAlive())
        return true;
    return false;
  }
CanBeSplit()
bool Entity::CanBeSplit () inline protected
Definition at line 537 of file EntityAI.c.
  {
    return false;
  }
CanBeTargetedByAI()
bool Entity::CanBeTargetedByAI (EntityAI ai) inline protected
Definition at line 603 of file EntityAI.c.
  {
    if (ai && ai.IsBeingBackstabbed())
      return false;
    if (!dBodyIsActive(this) && !IsMan())
      return false;
    return !IsDamageDestroyed();
  }
References dBodyIsActive(), IsDamageDestroyed(), and EntityAI::IsMan().
CanCombineAttachment()
bool Entity::CanCombineAttachment (notnull EntityAI e, int slot, bool stack_max_limit = false) inline protected
Definition at line 1317 of file EntityAI.c.
  {
    EntityAI att = GetInventory().FindAttachment(slot);
    if (att)
      return att.CanBeCombined(e, true, stack_max_limit);
    return false;
  }
CanDetachAttachment()
Entity::CanDetachAttachment (EntityAI parent) inline protected
calls this->CanDetachAttachment(parent)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, parent, "CanDetachAttachment");
Definition at line 1307 of file EntityAI.c.
  {
    return true;
  }
CanDisplayAnyAttachmentSlot()
Entity::CanDisplayAnyAttachmentSlot () inline protected
Returns
true if any attachment slot can be shown
Definition at line 1508 of file EntityAI.c.
  {
    int count = GetInventory().GetAttachmentSlotsCount();
    int slotID;
    for (int i = 0; i < count; i++)
    {
      slotID = GetInventory().GetAttachmentSlotId(i);
      if (CanDisplayAttachmentSlot(slotID))
        return true;
    }
    return false;
  }
References CanDisplayAttachmentSlot().
CanDisplayAttachmentCategory()
Entity::CanDisplayAttachmentCategory (string category_name) inline protected
Parameters
category_name->name of the attachment category that will or won't be displayed
Returns
true if attachment icon can be displayed in UI (inventory)
Definition at line 1526 of file EntityAI.c.
  {
    return true;
  }
CanDisplayAttachmentSlot() [1/2]
bool Entity::CanDisplayAttachmentSlot (int slot_id) inline protected
Definition at line 1500 of file EntityAI.c.
  {
    return InventorySlots.GetShowForSlotId(slot_id);
  }
References InventorySlots::GetShowForSlotId().
CanDisplayAttachmentSlot() [2/2]
bool Entity::CanDisplayAttachmentSlot (string slot_name) inline protected
Definition at line 1490 of file EntityAI.c.
  {
    Debug.LogWarning("Obsolete function - use CanDisplayAttachmentSlot with slot id parameter");
    return InventorySlots.GetShowForSlotId(InventorySlots.GetSlotIdFromString(slot_name));
  }
References InventorySlots::GetShowForSlotId(), InventorySlots::GetSlotIdFromString(), and Debug::LogWarning().
CanDisplayCargo()
Entity::CanDisplayCargo () inline protected
Returns
true if cargo can be displayed in UI (inventory)
Definition at line 1534 of file EntityAI.c.
  {
    return GetInventory().GetCargo() != null;
  }
CanDisplayWeight()
bool Entity::CanDisplayWeight () inline protected
'displayWeight' in item config
Definition at line 371 of file EntityAI.c.
  {
    return m_CanDisplayWeight;
  }
CanDropEntity()
bool Entity::CanDropEntity (notnull EntityAI item) inline protected
Returns if item can be dropped out from this entity.
Definition at line 1852 of file EntityAI.c.
  {
    return true;
  }
CanIgniteItem()
bool Entity::CanIgniteItem (EntityAI ignite_target = NULL) inline protected
Override this method and check if the given item can be ignited right now by this one. Evaluated on Server and Client.
Definition at line 429 of file EntityAI.c.
  {
    return false;
  }
CanLoadAttachment()
bool Entity::CanLoadAttachment (EntityAI attachment) inline protected
Definition at line 1259 of file EntityAI.c.
  {
    return true;
  }
CanLoadItemIntoCargo()
Entity::CanLoadItemIntoCargo (EntityAI item) inline protected
calls this->CanLoadItemIntoCargo(item), is called on server start when loading in the storage
Returns
true if action allowed
Note
: return scriptConditionExecute(this, item, "CanLoadItemIntoCargo");
Definition at line 1353 of file EntityAI.c.
  {
    return true;
  }
CanPutAsAttachment()
Entity::CanPutAsAttachment (EntityAI parent) inline protected
calls this->CanPutAsAttachment(parent)
Parameters
[in] parent target entity this is trying to attach to
Returns
true if action allowed
Note
: engine code is scriptConditionExecute(this, parent, "CanPutAsAttachment")
Definition at line 1271 of file EntityAI.c.
  {
    return !IsHologram();
  }
References IsHologram().
CanPutInCargo()
Entity::CanPutInCargo (EntityAI parent) inline protected
calls this->CanPutInCargo(parent)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, parent, "CanPutInCargo");
Definition at line 1364 of file EntityAI.c.
  {
    return !IsHologram();
  }
References IsHologram().
CanPutIntoHands()
Entity::CanPutIntoHands (EntityAI parent) inline protected
calls this->CanPutIntoHands(parent)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, parent, "CanPutIntoHands");
Definition at line 1459 of file EntityAI.c.
  {
    return !IsHologram();
  }
References IsHologram().
CanReceiveAttachment()
Entity::CanReceiveAttachment (EntityAI attachment, int slotId) inline protected
calls this->CanReceiveAttachment(attachment)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, attachment, "CanReceiveAttachment");
Definition at line 1236 of file EntityAI.c.
  {
    //generic occupancy check
    EntityAI currentAtt = GetInventory().FindAttachment(slotId);
    bool hasInternalConflict = attachment.HasInternalExclusionConflicts(slotId);
    if (currentAtt) //probably a swap or same-type swap
    {
      set<int> diff = attachment.GetAttachmentExclusionMaskAll(slotId);
      diff.RemoveItems(currentAtt.GetAttachmentExclusionMaskAll(slotId));
      if (diff.Count() == 0)
        return !hasInternalConflict;
      else
        return !hasInternalConflict && !IsExclusionFlagPresentRecursive(diff, slotId);
    }
    return !hasInternalConflict && !IsExclusionFlagPresentRecursive(attachment.GetAttachmentExclusionMaskAll(slotId), slotId);
  }
CanReceiveItemIntoCargo()
Entity::CanReceiveItemIntoCargo (EntityAI item) inline protected
calls this->CanReceiveItemIntoCargo(item)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, item, "CanReceiveItemIntoCargo");
Definition at line 1339 of file EntityAI.c.
  {
    if (GetInventory() && GetInventory().GetCargo())
      return GetInventory().GetCargo().CanReceiveItemIntoCargo(item));
      return true;
    }
CanReceiveItemIntoHands()
Entity::CanReceiveItemIntoHands (EntityAI item_to_hands) inline protected
calls this->CanReceiveItemIntoHands(item_to_hands)
Returns
true if action allowed
Note
: scriptConditionExecute(this, item_to_hands, "CanReceiveItemIntoHands");
Definition at line 1433 of file EntityAI.c.
  {
    return true;
  }
CanReleaseAttachment()
Entity::CanReleaseAttachment (EntityAI attachment) inline protected
calls this->CanReleaseAttachment(attachment)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, attachment, "CanReleaseAttachment");
Definition at line 1287 of file EntityAI.c.
  {
    if (attachment && attachment.GetInventory() && GetInventory())
    {
      InventoryLocation il = new InventoryLocation();
      attachment.GetInventory().GetCurrentInventoryLocation(il);
      if (il.IsValid())
      {
        int slot = il.GetSlot();
        return !GetInventory().GetSlotLock(slot);
      }
    }
    return true;
  }
CanReleaseCargo()
Entity::CanReleaseCargo (EntityAI cargo) inline protected
calls this->CanReleaseCargo(cargo)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, cargo, "CanReleaseCargo");
Definition at line 1389 of file EntityAI.c.
  {
    return true;
  }
CanReleaseFromHands()
Entity::CanReleaseFromHands (EntityAI handheld) inline protected
calls this->CanReleaseFromHands(handheld)
Returns
true if action allowed
Note
: scriptConditionExecute(this, handheld, "CanReleaseFromHands");
Definition at line 1470 of file EntityAI.c.
  {
    return true;
  }
CanRemoveFromCargo()
Entity::CanRemoveFromCargo (EntityAI parent) inline protected
calls this->CanRemoveFromCargo(parent)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, parent, "CanRemoveFromCargo");
Definition at line 1400 of file EntityAI.c.
  {
    return true;
  }
CanRemoveFromHands()
Entity::CanRemoveFromHands (EntityAI parent) inline protected
calls this->CanRemoveFromHands(parent)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, parent, "CanRemoveFromHands");
Definition at line 1481 of file EntityAI.c.
  {
    return true;
  }
CanSaveItemInHands()
bool Entity::CanSaveItemInHands (EntityAI item_in_hands) inline protected
Definition at line 1448 of file EntityAI.c.
  {
    return true;
  }
CanSwapEntities()
bool Entity::CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination) inline protected
Definition at line 1891 of file EntityAI.c.
  {
    return true;
  }
CanSwapItemInCargo()
Entity::CanSwapItemInCargo (EntityAI child_entity, EntityAI new_entity) inline protected
calls this->CanSwapItemInCargo(child_entity, new_entity)
Returns
true if action allowed
Note
: return ScriptConditionExecute(GetOwner(), child_entity, "CanSwapItemInCargo", new_entity);
Definition at line 1375 of file EntityAI.c.
  {
    if (GetInventory() && GetInventory().GetCargo())
      return GetInventory().GetCargo().CanSwapItemInCargo(child_entity, new_entity));
      return true;
    }
CanSwitchDuringAttach()
bool Entity::CanSwitchDuringAttach (EntityAI parent) inline protected
Definition at line 1277 of file EntityAI.c.
  {
    return false;
  }
ChangeIntoOnAttach()
string Entity::ChangeIntoOnAttach (string slot) inline protected
Definition at line 2850 of file EntityAI.c.
{}
ChangeIntoOnDetach()
string Entity::ChangeIntoOnDetach () inline protected
Definition at line 2851 of file EntityAI.c.
{}
CheckExclusionAccessCondition()
bool Entity::CheckExclusionAccessCondition (int occupiedSlot, int targetSlot, set< int > value, inout set< int > adjustedValue) inline protected
Definition at line 3501 of file EntityAI.c.
  {
    bool occupiedException = occupiedSlot == InventorySlots.HANDS || occupiedSlot == InventorySlots.SHOULDER || occupiedSlot == InventorySlots.MELEE || occupiedSlot == InventorySlots.LEFTHAND;
    bool targetException = targetSlot == InventorySlots.HANDS || targetSlot == InventorySlots.SHOULDER || targetSlot == InventorySlots.MELEE || targetSlot == InventorySlots.LEFTHAND;
    if (occupiedException)
    {
      adjustedValue = value;
      return false;
    }
    if (targetException)
    {
      adjustedValue = null;
      return false;
    }
    AdjustExclusionAccessCondition(occupiedSlot, targetSlot, value, adjustedValue);
    return adjustedValue.Count() != 0;
  }
CheckExclusionAccessPropagation()
bool Entity::CheckExclusionAccessPropagation (int occupiedSlot, int targetSlot, set< int > value, inout set< int > adjustedValue) inline protected
special propagation contition
Definition at line 3529 of file EntityAI.c.
  {
    bool occupiedException = occupiedSlot == InventorySlots.HANDS || occupiedSlot == InventorySlots.SHOULDER || occupiedSlot == InventorySlots.MELEE || occupiedSlot == InventorySlots.LEFTHAND;
    bool targetException = targetSlot == InventorySlots.HANDS || targetSlot == InventorySlots.SHOULDER || targetSlot == InventorySlots.MELEE || targetSlot == InventorySlots.LEFTHAND || targetSlot == InventorySlots.INVALID;
    if (targetException)
    {
      adjustedValue = null;
      return false;
    }
    AdjustExclusionAccessPropagation(occupiedSlot, targetSlot, value, adjustedValue);
    return adjustedValue.Count() != 0;
  }
References InventorySlots::INVALID.
CheckForDestroy()
void Entity::CheckForDestroy () inline protected
Definition at line 681 of file EntityAI.c.
  {
    if (IsPrepareToDelete())
      GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(TryDelete, DELETE_CHECK_DELAY, false);
  }
References CALL_CATEGORY_SYSTEM, GetGame(), and IsPrepareToDelete().
ClearExclusionValueRecursive()
void Entity::ClearExclusionValueRecursive (set< int > values, int slotId) inline private
Definition at line 3393 of file EntityAI.c.
  {
    if (values && values.Count() != 0)
    {
      set<int> passThis;
      InventoryLocation lcn = new InventoryLocation();
      GetInventory().GetCurrentInventoryLocation(lcn);
      if (CheckExclusionAccessPropagation(lcn.GetSlot(), slotId, values, passThis))
      {
        int count = passThis.Count();
        for (int i = 0; i < count; i++)
          m_AttachmentExclusionMaskChildren.RemoveItem(passThis[i]);
        EntityAI parent = GetHierarchyParent();
        if (parent)
          parent.ClearExclusionValueRecursive(passThis, lcn.GetSlot());
      }
    }
  }
ClearInventory()
void Entity::ClearInventory () protected
ClearSingleExclusionValueGlobal()
void Entity::ClearSingleExclusionValueGlobal (EAttExclusions value) inline protected
to help with item staging exclusions
Definition at line 3354 of file EntityAI.c.
  {
    int idx = m_AttachmentExclusionMaskGlobal.Find(value);
    if (idx != -1)
      m_AttachmentExclusionMaskGlobal.Remove(idx);
  }
ClearWeightDirty()
void Entity::ClearWeightDirty () inline protected
Definition at line 2578 of file EntityAI.c.
  {
    //Print("ent:" + this + " - ClearWeightDirty");
    m_WeightDirty = 0;
  }
CombineItemsClient()
void Entity::CombineItemsClient (EntityAI entity2, bool use_stack_max = false) inline protected
Definition at line 1330 of file EntityAI.c.
  {}
ConvertNonlethalDamage() [1/2]
float Entity::ConvertNonlethalDamage (float damage) inline protected
DEPRECATED - for legacy purposes.
Definition at line 355 of file EntityAI.c.
  {
    return 0.0;
  }
ConvertNonlethalDamage() [2/2]
float Entity::ConvertNonlethalDamage (float damage, DamageType damageType) inline protected
Definition at line 349 of file EntityAI.c.
  {
    return 0.0;
  }
CreateAndInitInventory()
proto native void Entity::CreateAndInitInventory () protected
CreateComponent()
Component Entity::CreateComponent (int comp_type, string extended_class_name = "") inline private
CreateComponent.
Definition at line 229 of file EntityAI.c.
  {
    return GetComponent(comp_type, extended_class_name);
  }
DeathUpdate()
void Entity::DeathUpdate () inline protected
Definition at line 912 of file EntityAI.c.
  {
    EntityAI dead_entity = EntityAI.Cast(GetGame().CreateObjectEx(GetDeadItemName(), GetPosition(), ECE_OBJECT_SWAP, RF_ORIGINAL));
    dead_entity.SetOrientation(GetOrientation());
    if (KeepHealthOnReplace())
      dead_entity.SetHealth(GetHealth());
    this.Delete();
  }
References ECE_OBJECT_SWAP, GetDeadItemName(), GetGame(), GetOrientation(), GetPosition, KeepHealthOnReplace(), and RF_ORIGINAL.
DebugBBoxDelete()
void Entity::DebugBBoxDelete () inline protected
Definition at line 2364 of file EntityAI.c.
  {
    GetComponent(COMP_TYPE_ETITY_DEBUG).DebugBBoxDelete();
  }
References COMP_TYPE_ETITY_DEBUG.
DebugBBoxDraw()
Shape Entity::DebugBBoxDraw () inline protected
Definition at line 2354 of file EntityAI.c.
  {
    return GetComponent(COMP_TYPE_ETITY_DEBUG).DebugBBoxDraw();
  }
References COMP_TYPE_ETITY_DEBUG.
DebugBBoxSetColor()
void Entity::DebugBBoxSetColor (int color) inline protected
Definition at line 2359 of file EntityAI.c.
  {
    GetComponent(COMP_TYPE_ETITY_DEBUG).DebugBBoxSetColor(color);
  }
References COMP_TYPE_ETITY_DEBUG.
DebugDirectionDelete()
void Entity::DebugDirectionDelete () inline protected
Definition at line 2379 of file EntityAI.c.
  {
    GetComponent(COMP_TYPE_ETITY_DEBUG).DebugDirectionDelete();
  }
References COMP_TYPE_ETITY_DEBUG.
DebugDirectionDraw()
Shape Entity::DebugDirectionDraw (float distance = 1) inline protected
Definition at line 2369 of file EntityAI.c.
  {
    return GetComponent(COMP_TYPE_ETITY_DEBUG).DebugDirectionDraw(distance);
  }
References COMP_TYPE_ETITY_DEBUG.
DebugDirectionSetColor()
void Entity::DebugDirectionSetColor (int color) inline protected
Definition at line 2374 of file EntityAI.c.
  {
    GetComponent(COMP_TYPE_ETITY_DEBUG).DebugDirectionSetColor(color);
  }
References COMP_TYPE_ETITY_DEBUG.
DeferredInit()
void Entity::DeferredInit () inline protected
Definition at line 209 of file EntityAI.c.
  {
    m_Initialized = true;
  }
References m_Initialized.
Delete()
override void Entity::Delete () inline protected
Delete this object in next frame.
Returns
void
ItemBase item = GetGame().GetPlayer().CreateInInventory("GrenadeRGD5");
item.Delete();
Definition at line 626 of file EntityAI.c.
  {
    m_PendingDelete = true;
    super.Delete();
  }
DeleteComponent()
bool Entity::DeleteComponent (int comp_type) inline private
DeleteComponent.
Definition at line 244 of file EntityAI.c.
  {
    return m_ComponentsBank.DeleteComponent(comp_type);
  }
DeleteOnClient()
void Entity::DeleteOnClient () inline protected
Definition at line 632 of file EntityAI.c.
  {
    GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(GetGame().ObjectDeleteOnClient, this);
  }
References CALL_CATEGORY_SYSTEM, and GetGame().
DeleteSafe()
void Entity::DeleteSafe () inline protected
Definition at line 638 of file EntityAI.c.
  {
    if (GetHierarchyRootPlayer() == null)
      Delete();
    else
    {
      if (GetGame().IsServer() && GetGame().IsMultiplayer())
        GetHierarchyRootPlayer().JunctureDeleteItem(this);
      else
        GetHierarchyRootPlayer().AddItemToDelete(this);
    }
  }
References GetGame().
DeleteSave()
void Entity::DeleteSave () inline protected
Definition at line 652 of file EntityAI.c.
  {
    DeleteSafe();
  }
DestroyInventory()
proto native void Entity::DestroyInventory () protected
DisassembleOnLastDetach()
bool Entity::DisassembleOnLastDetach () inline protected
Definition at line 443 of file EntityAI.c.
  {
    return false;
  }
DoPlacingHeightCheck()
bool Entity::DoPlacingHeightCheck () inline protected
Do the roof check when placing this?
Definition at line 514 of file EntityAI.c.
  {
    return false;
  }
EEAmmoChanged()
void Entity::EEAmmoChanged () inline protected
Definition at line 840 of file EntityAI.c.
  {
    SetWeightDirty();
  }
EECargoIn()
void Entity::EECargoIn (EntityAI item) inline protected
Definition at line 1006 of file EntityAI.c.
  {
    SetWeightDirty();
    if (m_OnItemAddedIntoCargo)
      m_OnItemAddedIntoCargo.Invoke(item, this);
    item.OnMovedInsideCargo(this);
  }
EECargoMove()
void Entity::EECargoMove (EntityAI item) inline protected
Definition at line 1026 of file EntityAI.c.
  {
    if (m_OnItemMovedInCargo)
      m_OnItemMovedInCargo.Invoke(item, this);
    item.OnMovedWithinCargo(this);
  }
EECargoOut()
void Entity::EECargoOut (EntityAI item) inline protected
Definition at line 1016 of file EntityAI.c.
  {
    SetWeightDirty();
    if (m_OnItemRemovedFromCargo)
      m_OnItemRemovedFromCargo.Invoke(item, this);
    item.OnRemovedFromCargo(this);
  }
EEDelete()
void Entity::EEDelete (EntityAI parent) inline protected
Called right before object deleting.
Definition at line 769 of file EntityAI.c.
  {
    m_PendingDelete = true;
    GetInventory().EEDelete(parent);
    if (m_EM)
      m_EM.OnDeviceDestroyed();
  }
References ComponentEnergyManager::OnDeviceDestroyed().
EEHealthLevelChanged()
void Entity::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline protected
Definition at line 845 of file EntityAI.c.
  {
    // Notify potential parent that this item was ruined
    EntityAI parent = GetHierarchyParent();
    if (newLevel == GameConstants.STATE_RUINED)
    {
      if (parent)
        parent.OnAttachmentRuined(this);
      if (!zone)
        OnDamageDestroyed(oldLevel);
      AttemptDestructionBehaviour(oldLevel, newLevel, zone);
    }
  }
References OnDamageDestroyed(), and GameConstants::STATE_RUINED.
EEHitBy()
void Entity::EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline protected
Definition at line 927 of file EntityAI.c.
  {
    if (m_OnHitByInvoker)
      m_OnHitByInvoker.Invoke(this, damageResult, damageType, source, component, dmgZone, ammo, modelPos, speedCoef);
#ifdef DEVELOPER
    //Print("EEHitBy: " + this + "; damageResult:"+ damageResult.GetDamage("","") +"; damageType: "+ damageType +"; source: "+ source +"; component: "+ component +"; dmgZone: "+ dmgZone +"; ammo: "+ ammo +"; modelPos: "+ modelPos);
#endif
  }
References component.
EEHitByRemote()
void Entity::EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos) inline protected
Definition at line 937 of file EntityAI.c.
  {
  }
EEInit()
void Entity::EEInit () inline protected
Called upon object creation.
Definition at line 744 of file EntityAI.c.
  {
    if (GetInventory())
    {
      GetInventory().EEInit();
      m_AttachmentsWithCargo.Clear();
      m_AttachmentsWithAttachments.Clear();
      for (int i = 0; i < GetInventory().AttachmentCount(); i++)
      {
        EntityAI attachment = GetInventory().GetAttachmentFromIndex(i);
        if (attachment)
        {
          if (attachment.GetInventory().GetCargo())
            m_AttachmentsWithCargo.Insert(attachment);
          if (attachment.GetInventory().GetAttachmentSlotsCount() > 0)
            m_AttachmentsWithAttachments.Insert(attachment);
        }
      }
    }
    MaxLifetimeRefreshCalc();
  }
EEInventoryIn()
void Entity::EEInventoryIn (Man newParentMan, EntityAI diz, EntityAI newParent) inline protected
Definition at line 829 of file EntityAI.c.
  {
  }
EEInventoryOut()
void Entity::EEInventoryOut (Man oldParentMan, EntityAI diz, EntityAI newParent) inline protected
Definition at line 832 of file EntityAI.c.
  {
    m_LastUpdatedTime = 0.0;
    if (GetInventory() && newParent == null)
      GetInventory().ResetFlipCargo();
  }
EEItemAttached()
void Entity::EEItemAttached (EntityAI item, string slot_name) inline protected
Definition at line 943 of file EntityAI.c.
  {
    int slotId = InventorySlots.GetSlotIdFromString(slot_name);
    PropagateExclusionValueRecursive(item.GetAttachmentExclusionMaskAll(slotId), slotId); //Performed from parent to avoid event order issues on swap
    SetWeightDirty();
    if (m_ComponentsBank != NULL)
    {
      for (int comp_key = 0; comp_key < COMP_TYPE_COUNT; ++comp_key)
      {
        if (m_ComponentsBank.IsComponentAlreadyExist(comp_key))
          m_ComponentsBank.GetComponent(comp_key).Event_OnItemAttached(item, slot_name);
      }
    }
    // Energy Manager
    if (m_EM && item.GetCompEM())
      m_EM.OnAttachmentAdded(item);
    if (item.GetInventory().GetCargo())
      m_AttachmentsWithCargo.Insert(item);
    if (item.GetInventory().GetAttachmentSlotsCount() > 0)
      m_AttachmentsWithAttachments.Insert(item);
    if (m_OnItemAttached)
      m_OnItemAttached.Invoke(item, slot_name, this);
  }
References COMP_TYPE_COUNT, InventorySlots::GetSlotIdFromString(), and ComponentEnergyManager::OnAttachmentAdded().
EEItemDetached()
void Entity::EEItemDetached (EntityAI item, string slot_name) inline protected
Definition at line 976 of file EntityAI.c.
  {
    int slotId = InventorySlots.GetSlotIdFromString(slot_name);
    ClearExclusionValueRecursive(item.GetAttachmentExclusionMaskAll(slotId), slotId); //Performed from parent to avoid event order issues on swap
    SetWeightDirty();
    if (m_ComponentsBank != NULL)
    {
      for (int comp_key = 0; comp_key < COMP_TYPE_COUNT; ++comp_key)
      {
        if (m_ComponentsBank.IsComponentAlreadyExist(comp_key))
          m_ComponentsBank.GetComponent(comp_key).Event_OnItemDetached(item, slot_name);
      }
    }
    // Energy Manager
    if (m_EM && item.GetCompEM())
      m_EM.OnAttachmentRemoved(item);
    if (m_AttachmentsWithCargo.Find(item) > -1)
      m_AttachmentsWithCargo.RemoveItem(item);
    if (m_AttachmentsWithAttachments.Find(item) > -1)
      m_AttachmentsWithAttachments.RemoveItem(item);
    if (m_OnItemDetached)
      m_OnItemDetached.Invoke(item, slot_name, this);
  }
References COMP_TYPE_COUNT, InventorySlots::GetSlotIdFromString(), and ComponentEnergyManager::OnAttachmentRemoved().
EEItemLocationChanged()
void Entity::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline protected
Definition at line 793 of file EntityAI.c.
  {
    EntityAI old_owner = oldLoc.GetParent();
    EntityAI new_owner = newLoc.GetParent();
    OnItemLocationChanged(old_owner, new_owner);
    if (oldLoc.GetType() == InventoryLocationType.ATTACHMENT && newLoc.GetType() == InventoryLocationType.ATTACHMENT)
      OnItemAttachmentSlotChanged(oldLoc, newLoc);
    if (oldLoc.GetType() == InventoryLocationType.ATTACHMENT)
    {
      if (old_owner)
        OnWasDetached(old_owner, oldLoc.GetSlot());
      else
        Error("EntityAI::EEItemLocationChanged - detached, but old_owner is null");
    }
    if (newLoc.GetType() == InventoryLocationType.ATTACHMENT)
    {
      if (new_owner)
        OnWasAttached(newLoc.GetParent(), newLoc.GetSlot());
      else
        Error("EntityAI::EEItemLocationChanged - attached, but new_owner is null");
    }
  }
References Error(), OnItemAttachmentSlotChanged(), OnItemLocationChanged(), OnWasAttached(), and OnWasDetached().
EEKilled()
void Entity::EEKilled (Object killer) inline protected
called on server when the entity is killed
Definition at line 886 of file EntityAI.c.
  {
    if (m_OnKilledInvoker)
      m_OnKilledInvoker.Invoke(this, killer);
    //analytics
    GetGame().GetAnalyticsServer().OnEntityKilled(killer, this);
    if (ReplaceOnDeath())
      GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(DeathUpdate, DEAD_REPLACE_DELAY, false);
  }
References CALL_CATEGORY_SYSTEM, GetGame(), and ReplaceOnDeath().
EEOnAfterLoad()
void Entity::EEOnAfterLoad () inline protected
Called when entity is part of "connected system" and being restored after load.
Definition at line 1145 of file EntityAI.c.
  {
    // ENERGY MANAGER
    // Restore connections between devices which were connected before server restart
    if (m_EM && m_EM.GetRestorePlugState())
    {
      int b1 = m_EM.GetEnergySourceStorageIDb1();
      int b2 = m_EM.GetEnergySourceStorageIDb2();
      int b3 = m_EM.GetEnergySourceStorageIDb3();
      int b4 = m_EM.GetEnergySourceStorageIDb4();
      // get pointer to EntityAI based on this ID
      EntityAI potential_energy_source = GetGame().GetEntityByPersitentID(b1, b2, b3, b4); // This function is available only in this event!
      // IMPORTANT!
      // Object IDs acquired here become INVALID when electric devices are transfered to another server while in plugged state (like Flashlight plugged into its attachment 9V battery)
      // To avoid issues, these items must be excluded from this system of restoring plug state so they don't unintentionally plug to incorrect devices through these invalid IDs.
      // Therefore their plug state is being restored withing the EEItemAttached() event while being excluded by the following 'if' conditions...
      bool is_attachment = false;
      if (potential_energy_source)
        is_attachment = GetInventory().HasAttachment(potential_energy_source);
      if (!is_attachment && potential_energy_source)
        is_attachment = potential_energy_source.GetInventory().HasAttachment(this);
      if (potential_energy_source && potential_energy_source.GetCompEM() /*&& potential_energy_source.HasEnergyManager()*/ && !is_attachment)
        m_EM.PlugThisInto(potential_energy_source); // restore connection
    }
  }
References ComponentEnergyManager::GetEnergySourceStorageIDb1(), ComponentEnergyManager::GetEnergySourceStorageIDb2(), ComponentEnergyManager::GetEnergySourceStorageIDb3(), ComponentEnergyManager::GetEnergySourceStorageIDb4(), GetGame(), ComponentEnergyManager::GetRestorePlugState(), and ComponentEnergyManager::PlugThisInto().
EEOnCECreate()
void Entity::EEOnCECreate () inline protected
Called when entity is being created as new by CE/ Debug.
Definition at line 1178 of file EntityAI.c.
  {
  }
EEParentedFrom()
void Entity::EEParentedFrom (EntityAI parent) inline protected
Called from 'IEntity.RemoveChild' or 'IEntity.AddChild' when hierarchy changes.
Definition at line 825 of file EntityAI.c.
  {
  }
EEParentedTo()
void Entity::EEParentedTo (EntityAI parent) inline protected
Called from 'IEntity.AddChild'.
Definition at line 820 of file EntityAI.c.
  {
  }
EnableHeatHaze()
proto native void Entity::EnableHeatHaze (bool pState) private
EnableLinear()
proto native bool Entity::EnableLinear (bool pState) private
EnableSpecular()
proto native bool Entity::EnableSpecular (bool pState) private
EntityAI()
void Entity::EntityAI () inline protected
Definition at line 166 of file EntityAI.c.
  {
    // Set up the Energy Manager
    string type = GetType();
    string param_access_energy_sys = "CfgVehicles " + type + " EnergyManager ";
    bool is_electic_device = GetGame().ConfigIsExisting(param_access_energy_sys);
    if (is_electic_device) // TO DO: Check if this instance is a hologram (advanced placement). If Yes, then do not create Energy Manager component.
    {
      CreateComponent(COMP_TYPE_ENERGY_MANAGER);
      RegisterNetSyncVariableBool("m_EM.m_IsSwichedOn");
      RegisterNetSyncVariableBool("m_EM.m_CanWork");
      RegisterNetSyncVariableBool("m_EM.m_IsPlugged");
      RegisterNetSyncVariableInt("m_EM.m_EnergySourceNetworkIDLow");
      RegisterNetSyncVariableInt("m_EM.m_EnergySourceNetworkIDHigh");
      RegisterNetSyncVariableFloat("m_EM.m_Energy");
    }
    // Item preview index
    RegisterNetSyncVariableInt("m_ViewIndex", 0, 99);
    // Refresher signalization
    RegisterNetSyncVariableBool("m_RefresherViable");
    m_AttachmentsWithCargo = new array<EntityAI>();
    m_AttachmentsWithAttachments = new array<EntityAI>();
    m_LastUpdatedTime = 0.0;
    m_ElapsedSinceLastUpdate = 0.0;
    m_CanDisplayWeight = ConfigGetBool("displayWeight");
    InitDamageZoneMapping();
    InitDamageZoneDisplayNameMapping();
    m_HiddenSelectionsData = new HiddenSelectionsData(GetType());
    GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(DeferredInit, 34);
  }
References CALL_CATEGORY_SYSTEM, COMP_TYPE_ENERGY_MANAGER, GetGame(), and GetType().
EOnFrame()
override void Entity::EOnFrame (IEntity other, float timeSlice) inline protected
Definition at line 2313 of file EntityAI.c.
  {
    if (m_ComponentsBank != NULL)
    {
      for (int comp_key = 0; comp_key < COMP_TYPE_COUNT; ++comp_key)
      {
        if (m_ComponentsBank.IsComponentAlreadyExist(comp_key))
          m_ComponentsBank.GetComponent(comp_key).Event_OnFrame(other, timeSlice);
      }
    }
  }
References COMP_TYPE_COUNT.
ExecuteActionsConnectedToValve()
void Entity::ExecuteActionsConnectedToValve (int pValveIndex) protected
FindAttachmentBySlotName()
EntityAI Entity::FindAttachmentBySlotName (string slot_name) inline protected
Definition at line 1596 of file EntityAI.c.
  {
    if (GetGame())
    {
      int slot_id = InventorySlots.GetSlotIdFromString(slot_name);
      if (slot_id != InventorySlots.INVALID)
        return GetInventory().FindAttachment(slot_id);
    }
    return null;
  }
References GetGame(), InventorySlots::GetSlotIdFromString(), and InventorySlots::INVALID.
GetAgents()
int Entity::GetAgents () inline protected
Definition at line 565 of file EntityAI.c.
{ return 0; }
GetAmbientAlpha()
proto native float Entity::GetAmbientAlpha () private
GetAmbientColorV()
proto native vector Entity::GetAmbientColorV () private
GetArrowManager()
ArrowManagerBase Entity::GetArrowManager () inline protected
Definition at line 3555 of file EntityAI.c.
  {
    return null;
  }
GetAttachmentByConfigTypeName()
EntityAI Entity::GetAttachmentByConfigTypeName (string type) inline protected
Get attached entity by config type name.
Definition at line 1839 of file EntityAI.c.
  {
    for (int i = 0; i < GetInventory().AttachmentCount(); i++)
    {
      EntityAI attachment = GetInventory().GetAttachmentFromIndex(i);
      if (attachment.IsKindOf(type))
        return attachment;
    }
    return NULL;
  }
GetAttachmentByType()
EntityAI Entity::GetAttachmentByType (typename type) inline protected
Get attached entity by type.
Definition at line 1825 of file EntityAI.c.
  {
    for (int i = 0; i < GetInventory().AttachmentCount(); i++)
    {
      EntityAI attachment = GetInventory().GetAttachmentFromIndex(i);
      if (attachment && attachment.IsInherited(type))
        return attachment;
    }
    return NULL;
  }
GetAttachmentExclusionInitSlotValue()
set< int > Entity::GetAttachmentExclusionInitSlotValue (int slotId) inline protected
override this to modify slot behavior for specific items, or just set 'm_AttachmentExclusionMaskGlobal' value for simple items
Definition at line 3182 of file EntityAI.c.
  {
    set<int> dflt = new set<int>;
    return dflt;
  }
GetAttachmentExclusionMaskAll()
set< int > Entity::GetAttachmentExclusionMaskAll (int slotId) inline private
Slot-specific, children (attachments), and additional (state etc.) masks combined.
Definition at line 3413 of file EntityAI.c.
  {
    set<int> values = new set<int>();
    set<int> slotValues = GetAttachmentExclusionMaskSlot(slotId);
    if (slotValues)
      values.InsertSet(slotValues);
    values.InsertSet(m_AttachmentExclusionMaskGlobal);
    values.InsertSet(m_AttachmentExclusionMaskChildren);
    return values;
  }
GetAttachmentExclusionMaskChildren()
set< int > Entity::GetAttachmentExclusionMaskChildren () inline private
Mask value coming from the item's attachments.
Definition at line 3438 of file EntityAI.c.
  {
    return m_AttachmentExclusionMaskChildren;
  }
GetAttachmentExclusionMaskGlobal()
set< int > Entity::GetAttachmentExclusionMaskGlobal () inline private
Global mask value, independent of slot-specific behavior!
Definition at line 3432 of file EntityAI.c.
  {
    return m_AttachmentExclusionMaskGlobal;
  }
GetAttachmentExclusionMaskSlot()
set< int > Entity::GetAttachmentExclusionMaskSlot (int slotId) inline private
Specific slot behavior.
Definition at line 3426 of file EntityAI.c.
  {
    return m_AttachmentExclusionSlotMap.Get(slotId);
  }
GetAttachmentSoundType()
string Entity::GetAttachmentSoundType () inline protected
returns sound type of attachment (used for clothing and weapons on DayZPlayerImplement, paired with Anim*Type enum from DayZAnimEvents)
Definition at line 2827 of file EntityAI.c.
  {
    return "None";
  }
GetAttachmentsWithAttachments()
array< EntityAI > Entity::GetAttachmentsWithAttachments () inline protected
Definition at line 560 of file EntityAI.c.
  {
    return m_AttachmentsWithAttachments;
  }
GetAttachmentsWithCargo()
array< EntityAI > Entity::GetAttachmentsWithCargo () inline protected
Definition at line 555 of file EntityAI.c.
  {
    return m_AttachmentsWithCargo;
  }
GetBayonetAttachmentIdx()
int Entity::GetBayonetAttachmentIdx () inline protected
Definition at line 2975 of file EntityAI.c.
{};
GetBrightness()
proto native float Entity::GetBrightness () private
GetButtstockAttachmentIdx()
int Entity::GetButtstockAttachmentIdx () inline protected
Definition at line 2979 of file EntityAI.c.
{};
GetCastShadow()
proto native bool Entity::GetCastShadow () private
GetCompBS()
ComponentBodyStaging Entity::GetCompBS () inline protected
Use this to access Body Staging component on dead character. Returns NULL if the given object lacks such component.
Definition at line 2429 of file EntityAI.c.
  {
    if (HasComponent(COMP_TYPE_BODY_STAGING))
      return ComponentBodyStaging.Cast(GetComponent(COMP_TYPE_BODY_STAGING));
    return NULL;
  }
References COMP_TYPE_BODY_STAGING.
GetCompEM()
ComponentEnergyManager Entity::GetCompEM () inline protected
energy manager ENERGY MANAGER:Documentation: Confluence >> Camping & Squatting >> Electricity >> Energy Manager functionalities Use this to access Energy Manager component on your device. Returns NULL if the given object lacks such component.
Definition at line 2439 of file EntityAI.c.
  {
    if (m_EM)
      return m_EM;
    if (HasComponent(COMP_TYPE_ENERGY_MANAGER))
      return ComponentEnergyManager.Cast(GetComponent(COMP_TYPE_ENERGY_MANAGER));
    return NULL;
  }
References COMP_TYPE_ENERGY_MANAGER.
GetComponent()
Component Entity::GetComponent (int comp_type, string extended_class_name = "") inline private
GetComponent.
Definition at line 235 of file EntityAI.c.
  {
    if (m_ComponentsBank == NULL)
      m_ComponentsBank = new ComponentsBank(this);
    return m_ComponentsBank.GetComponent(comp_type, extended_class_name);
  }
GetConfigWeightModified()
float Entity::GetConfigWeightModified () inline protected
Definition at line 2557 of file EntityAI.c.
  {
    return m_ConfigWeight * GetWetWeightModifier();
  }
GetCurrentCamera()
static proto native Camera Entity::GetCurrentCamera () static private
Returns active Camera instance (note: player's camera is not Camera instance - thus it return null)
Returns
Camera active Camera instance
GetCurrentFOV()
static proto native float Entity::GetCurrentFOV () static private
Returns FOV of current camera object.
Returns
float FOV of current camera object
GetDeadItemName()
string Entity::GetDeadItemName () inline protected
Definition at line 902 of file EntityAI.c.
  {
    return "";
  }
GetDebugActions()
void Entity::GetDebugActions (out TSelectableActionInfoArrayEx outputList) inline protected
Definition at line 2658 of file EntityAI.c.
  {
    //fix entity
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.FIX_ENTITY, "Fix Entity", FadeColors.LIGHT_GREY));
    //weight
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.GET_TOTAL_WEIGHT, "Print Weight", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.GET_TOTAL_WEIGHT_RECALC, "Print Weight Verbose", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.GET_PLAYER_WEIGHT, "Print Player Weight", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.GET_PLAYER_WEIGHT_RECALC, "Print Player Weight Verbose", FadeColors.LIGHT_GREY));
  }
References SAT_DEBUG_ACTION.
GetDebugButtonNames()
void Entity::GetDebugButtonNames (out string button1, out string button2, out string button3, out string button4) inline protected
Definition at line 2349 of file EntityAI.c.
{} //DEPRICATED, USE GetDebugActions / OnAction
GetDebugText()
string Entity::GetDebugText () inline protected
Definition at line 2325 of file EntityAI.c.
  {
    string text = string.Empty;
    text += "Weight: " + GetWeightEx() + "\n";
    text += "Disabled: " + GetIsSimulationDisabled() + "\n";
#ifdef SERVER
    if (GetEconomyProfile())
      text += "CE Lifetime default: " + (int)GetEconomyProfile().GetLifetime() + "\n";
    text += "CE Lifetime remaining: " + (int)GetLifetime() + "\n";
#endif
    ComponentEnergyManager compEM = GetCompEM();
    if (compEM)
    {
      text += "Energy Source: " + Object.GetDebugName(compEM.GetEnergySource()) + "\n";
      text += "Switched On: " + compEM.IsSwitchedOn() + "\n";
      text += "Is Working: " + compEM.IsWorking() + "\n";
    }
    return text;
  }
GetDefaultHitComponent()
string Entity::GetDefaultHitComponent () inline protected
returns default hit component for the Entity (overriden for each Type - PlayerBase, DayZInfected, DayZAnimal, etc.)
returns Global so it is obvious you need to configure that properly on entity
Definition at line 2794 of file EntityAI.c.
  {
    Debug.LogError("EntityAI: DefaultHitComponent not set properly for that entity (" + GetType() + ")");
    return "";
  }
References GetType(), and Debug::LogError().
GetDefaultHitPosition()
vector Entity::GetDefaultHitPosition () inline protected
Definition at line 2814 of file EntityAI.c.
  {
    Debug.LogError("EntityAI: DefaultHitPosition not set for that entity (" + GetType() + ")");
    return vector.Zero;
  }
References GetType(), Debug::LogError(), and vector::Zero.
GetDefaultHitPositionComponent()
string Entity::GetDefaultHitPositionComponent () inline protected
returns default hit position component name for the Entity (overriden by type if needed - used mainly as support for impact particles)
Definition at line 2802 of file EntityAI.c.
  {
    Debug.LogError("EntityAI: DefaultHitPositionComponent not set for that entity (" + GetType() + ")");
    return "";
  }
References GetType(), and Debug::LogError().
GetDestructionBehaviour()
string Entity::GetDestructionBehaviour () inline private
Definition at line 249 of file EntityAI.c.
  {
    return "";
  }
GetDiffuseAlpha()
proto native float Entity::GetDiffuseAlpha () private
GetDiffuseColorV()
proto native vector Entity::GetDiffuseColorV () private
GetEconomyProfile()
proto native CEItemProfile Entity::GetEconomyProfile () protected
Get economy item profile (if assigned, otherwise null)
GetEntityDamageDisplayNameMap()
map< int, string > Entity::GetEntityDamageDisplayNameMap () inline protected
Definition at line 365 of file EntityAI.c.
  {
    return m_DamageDisplayNameMap;
  }
GetEntityDamageZoneMap()
DamageZoneMap Entity::GetEntityDamageZoneMap () inline protected
Definition at line 360 of file EntityAI.c.
  {
    return m_DamageZoneMap;
  }
GetFlareRelPosition()
proto native vector Entity::GetFlareRelPosition () private
GetHeatHazePower()
proto native float Entity::GetHeatHazePower () private
GetHeatHazeRadius()
proto native float Entity::GetHeatHazeRadius () private
GetHiddenSelectionIndex()
int Entity::GetHiddenSelectionIndex (string selection) inline protected
Returns index of the string found in cfg array 'hiddenSelections'. If it's not found then it returns -1.
Definition at line 2004 of file EntityAI.c.
  {
    if (m_HiddenSelectionsData)
      return m_HiddenSelectionsData.GetHiddenSelectionIndex(selection);
    return -1;
  }
GetHiddenSelections()
override TStringArray Entity::GetHiddenSelections () inline protected
Returns the hiddenSelectionsTextures array from the object's config.
Definition at line 2013 of file EntityAI.c.
  {
    if (m_HiddenSelectionsData)
      return m_HiddenSelectionsData.m_HiddenSelections;
    else
      return super.GetHiddenSelections();
  }
GetHiddenSelectionsData()
HiddenSelectionsData Entity::GetHiddenSelectionsData () inline protected
Definition at line 1998 of file EntityAI.c.
  {
    return m_HiddenSelectionsData;
  }
GetHiddenSelectionsMaterials()
override TStringArray Entity::GetHiddenSelectionsMaterials () inline protected
Returns the hiddenSelectionsMaterials array from the object's config.
Definition at line 2031 of file EntityAI.c.
  {
    if (m_HiddenSelectionsData)
      return m_HiddenSelectionsData.m_HiddenSelectionsMaterials;
    else
      return super.GetHiddenSelectionsMaterials();
  }
GetHiddenSelectionsTextures()
override TStringArray Entity::GetHiddenSelectionsTextures () inline protected
Returns the hiddenSelectionsTextures array from the object's config.
Definition at line 2022 of file EntityAI.c.
  {
    if (m_HiddenSelectionsData)
      return m_HiddenSelectionsData.m_HiddenSelectionsTextures;
    else
      return super.GetHiddenSelectionsTextures();
  }
GetHideIconMask()
int Entity::GetHideIconMask () inline protected
should the item's icon be hidden in any part of the inventory?
Definition at line 220 of file EntityAI.c.
  {
    return EInventoryIconVisibility.ALWAYS;
  }
GetHierarchyLevel()
int Entity::GetHierarchyLevel (int lvl = 0) inline protected
Definition at line 730 of file EntityAI.c.
  {
    if (!GetHierarchyParent())
      return lvl;
    return GetHierarchyParent().GetHierarchyLevel(lvl + 1);
  }
GetHierarchyParent()
proto native EntityAI Entity::GetHierarchyParent () protected
Returns direct parent of current entity.
GetHierarchyRoot()
proto native EntityAI Entity::GetHierarchyRoot () protected
Returns root of current hierarchy (for example: if this entity is in Backpack on gnd, returns Backpack)
GetHierarchyRootPlayer()
proto native Man Entity::GetHierarchyRootPlayer () protected
Returns root of current hierarchy cast to Man.
GetHitComponentForAI()
string Entity::GetHitComponentForAI () inline protected
Returns hit component for the Entity (overriden for each Type - PlayerBase, DayZInfected, DayZAnimal, etc.)
returns Global so it is obvious you need to configure that properly on entity
Definition at line 2786 of file EntityAI.c.
  {
    Debug.LogError("EntityAI: HitComponentForAI not set properly for that entity (" + GetType() + ")");
    return "";
  }
References GetType(), and Debug::LogError().
GetInventory()
proto native GameInventory Entity::GetInventory () protected
GetInventoryAndCargoWeight()
float Entity::GetInventoryAndCargoWeight (bool forceRecalc = false) inline protected
Definition at line 2601 of file EntityAI.c.
  {
    float totalWeight;
    if (GetInventory())
    {
      int i = 0;
      int AttachmentsCount = GetInventory().AttachmentCount();
      if (AttachmentsCount > 0)
      {
        for (i = 0; i < AttachmentsCount; i++)
          totalWeight += GetInventory().GetAttachmentFromIndex(i).GetWeightEx(forceRecalc);
      }
      CargoBase cargo = GetInventory().GetCargo();
      if (cargo)
      {
        int cargoCount = cargo.GetItemCount();
        for (i = 0; i < cargoCount; i++)
          totalWeight += cargo.GetItem(i).GetWeightEx(forceRecalc);
      }
    }
    return totalWeight;
  }
GetInventoryHandAnimation()
bool Entity::GetInventoryHandAnimation (notnull InventoryLocation loc, out int value) inline protected
Definition at line 3093 of file EntityAI.c.
  {
    value = -1;
    return false;
  }
GetInvulnerabilityTypeString()
string Entity::GetInvulnerabilityTypeString () inline protected
Definition at line 2947 of file EntityAI.c.
  {
    return "";
  }
GetLifetime()
proto native float Entity::GetLifetime () protected
Get remaining economy lifetime (seconds)
GetLifetimeMax()
proto native float Entity::GetLifetimeMax () protected
Get max economy lifetime per instance - default is from DB (seconds)
GetLightType()
proto native int Entity::GetLightType () private
GetLiquidThroughputCoef()
float Entity::GetLiquidThroughputCoef () inline protected
Returns liquid throughput coeficient.
Definition at line 2942 of file EntityAI.c.
  {
    return LIQUID_THROUGHPUT_DEFAULT;
  }
References LIQUID_THROUGHPUT_DEFAULT.
GetMeleeTargetType()
int Entity::GetMeleeTargetType () inline protected
value is related to EMeleeTargetType
Definition at line 2821 of file EntityAI.c.
  {
    return EMeleeTargetType.ALIGNABLE;
  }
GetNearPlane()
proto native float Entity::GetNearPlane () private
get near plane of camera
GetObjectMaterial()
proto native owned string Entity::GetObjectMaterial (int index) protected
GetObjectTexture()
proto native owned string Entity::GetObjectTexture (int index) protected
GetOnAttachmentReleaseLock()
ScriptInvoker Entity::GetOnAttachmentReleaseLock () inline protected
Definition at line 1103 of file EntityAI.c.
  {
    if (!m_OnAttachmentReleaseLock)
      m_OnAttachmentReleaseLock = new ScriptInvoker;
    return m_OnAttachmentReleaseLock;
  }
GetOnAttachmentSetLock()
ScriptInvoker Entity::GetOnAttachmentSetLock () inline protected
Definition at line 1096 of file EntityAI.c.
  {
    if (!m_OnAttachmentSetLock)
      m_OnAttachmentSetLock = new ScriptInvoker;
    return m_OnAttachmentSetLock;
  }
GetOnHitByInvoker()
ScriptInvoker Entity::GetOnHitByInvoker () inline protected
Definition at line 1110 of file EntityAI.c.
  {
    if (!m_OnHitByInvoker)
      m_OnHitByInvoker = new ScriptInvoker;
    return m_OnHitByInvoker;
  }
GetOnItemAddedIntoCargo()
ScriptInvoker Entity::GetOnItemAddedIntoCargo () inline protected
Definition at line 1047 of file EntityAI.c.
  {
    if (!m_OnItemAddedIntoCargo)
      m_OnItemAddedIntoCargo = new ScriptInvoker;
    return m_OnItemAddedIntoCargo;
  }
GetOnItemAttached()
ScriptInvoker Entity::GetOnItemAttached () inline protected
Definition at line 1033 of file EntityAI.c.
  {
    if (!m_OnItemAttached)
      m_OnItemAttached = new ScriptInvoker;
    return m_OnItemAttached;
  }
GetOnItemDetached()
ScriptInvoker Entity::GetOnItemDetached () inline protected
Definition at line 1040 of file EntityAI.c.
  {
    if (!m_OnItemDetached)
      m_OnItemDetached = new ScriptInvoker;
    return m_OnItemDetached;
  }
GetOnItemFlipped()
ScriptInvoker Entity::GetOnItemFlipped () inline protected
Definition at line 1068 of file EntityAI.c.
  {
    if (!m_OnItemFlipped)
      m_OnItemFlipped = new ScriptInvoker;
    return m_OnItemFlipped;
  }
GetOnItemMovedInCargo()
ScriptInvoker Entity::GetOnItemMovedInCargo () inline protected
Definition at line 1061 of file EntityAI.c.
  {
    if (!m_OnItemMovedInCargo)
      m_OnItemMovedInCargo = new ScriptInvoker;
    return m_OnItemMovedInCargo;
  }
GetOnItemRemovedFromCargo()
ScriptInvoker Entity::GetOnItemRemovedFromCargo () inline protected
Definition at line 1054 of file EntityAI.c.
  {
    if (!m_OnItemRemovedFromCargo)
      m_OnItemRemovedFromCargo = new ScriptInvoker;
    return m_OnItemRemovedFromCargo;
  }
GetOnKilledInvoker()
ScriptInvoker Entity::GetOnKilledInvoker () inline protected
Definition at line 1117 of file EntityAI.c.
  {
    if (!m_OnKilledInvoker)
      m_OnKilledInvoker = new ScriptInvoker;
    return m_OnKilledInvoker;
  }
GetOnReleaseLock()
ScriptInvoker Entity::GetOnReleaseLock () inline protected
Definition at line 1089 of file EntityAI.c.
  {
    if (!m_OnReleaseLock)
      m_OnReleaseLock = new ScriptInvoker;
    return m_OnReleaseLock;
  }
GetOnSetLock()
ScriptInvoker Entity::GetOnSetLock () inline protected
Definition at line 1082 of file EntityAI.c.
  {
    if (!m_OnSetLock)
      m_OnSetLock = new ScriptInvoker;
    return m_OnSetLock;
  }
GetOnViewIndexChanged()
ScriptInvoker Entity::GetOnViewIndexChanged () inline protected
Definition at line 1075 of file EntityAI.c.
  {
    if (!m_OnViewIndexChanged)
      m_OnViewIndexChanged = new ScriptInvoker;
    return m_OnViewIndexChanged;
  }
GetPairDevice()
EntityAI Entity::GetPairDevice () protected
GetPersistentID()
proto void Entity::GetPersistentID (out int b1, out int b2, out int b3, out int b4) protected
Returns blocks of bits of persistence id of this entity. This id stays the same even after server restart.
GetQuantity()
float Entity::GetQuantity () inline protected
Definition at line 1948 of file EntityAI.c.
  {
    return 0;
  }
GetQuantityMax()
int Entity::GetQuantityMax () inline protected
Definition at line 1953 of file EntityAI.c.
  {
    return 0;
  }
GetQuickBarBonus()
int Entity::GetQuickBarBonus () inline protected
Definition at line 1965 of file EntityAI.c.
  {
    return 0;
  }
GetRadius()
proto native float Entity::GetRadius () private
GetRemotelyActivatedItemBehaviour()
RemotelyActivatedItemBehaviour Entity::GetRemotelyActivatedItemBehaviour () protected
Remotely controlled devices helpers.
GetSingleInventoryItemWeightEx()
float Entity::GetSingleInventoryItemWeightEx () inline protected
Definition at line 2656 of file EntityAI.c.
{}
GetSlotsCountCorrect()
int Entity::GetSlotsCountCorrect () inline protected
Definition at line 1588 of file EntityAI.c.
  {
    if (GetInventory())
      return GetInventory().GetAttachmentSlotsCount();
    else
      return -1;
  }
GetSoundLength()
proto native float Entity::GetSoundLength () private
GetSpotLightAngle()
proto native float Entity::GetSpotLightAngle () private
GetSuitableFinisherHitComponents()
array< string > Entity::GetSuitableFinisherHitComponents () inline protected
Definition at line 2808 of file EntityAI.c.
  {
    Debug.LogError("EntityAI: SuitableFinisherHitComponents not set for that entity (" + GetType() + ")");
    return null;
  }
References GetType(), and Debug::LogError().
GetTargetQuantityMax()
int Entity::GetTargetQuantityMax (int attSlotID = -1) inline protected
Definition at line 1960 of file EntityAI.c.
  {
    return 0;
  }
GetTemperature()
float Entity::GetTemperature () inline protected
Definition at line 1976 of file EntityAI.c.
  {
    return 0;
  }
GetTemperatureInit()
float Entity::GetTemperatureInit () inline protected
Definition at line 1981 of file EntityAI.c.
  {
    return 0;
  }
GetTemperatureMax()
float Entity::GetTemperatureMax () inline protected
Definition at line 1991 of file EntityAI.c.
  {
    return 0;
  }
GetTemperatureMin()
float Entity::GetTemperatureMin () inline protected
Definition at line 1986 of file EntityAI.c.
  {
    return 0;
  }
GetTurnableValveIndex()
int Entity::GetTurnableValveIndex (int pComponentIndex) protected
GetUniversalTemperatureSource()
UTemperatureSource Entity::GetUniversalTemperatureSource () inline protected
Definition at line 3110 of file EntityAI.c.
  {
    return m_UniversalTemperatureSource;
  }
GetUniversalTemperatureSourcePosition()
vector Entity::GetUniversalTemperatureSourcePosition () inline protected
Definition at line 3120 of file EntityAI.c.
  {
    return GetPosition();
  }
References GetPosition.
GetViewIndex()
int Entity::GetViewIndex () inline protected
Returns item preview index !!!! IF OVERRIDING with more dynamic events call GetOnViewIndexChanged() in constructor on client !!!!
Definition at line 2740 of file EntityAI.c.
  {
    if (MemoryPointExists("invView2"))
    {
#ifdef PLATFORM_WINDOWS
      InventoryLocation il = new InventoryLocation();
      GetInventory().GetCurrentInventoryLocation(il);
      InventoryLocationType type = il.GetType();
      switch (type)
      {
      case InventoryLocationType.CARGO:
      {
        return 0;
      }
      case InventoryLocationType.ATTACHMENT:
      {
        return 1;
      }
      case InventoryLocationType.HANDS:
      {
        return 0;
      }
      case InventoryLocationType.GROUND:
      {
        return 1;
      }
      case InventoryLocationType.PROXYCARGO:
      {
        return 0;
      }
      default:
      {
        return 0;
      }
      }
#endif
#ifdef PLATFORM_CONSOLE
      return 1;
#endif
    }
    return 0;
  }
GetWeight()
int Entity::GetWeight () inline protected
Definition at line 2573 of file EntityAI.c.
  {
    return GetWeightEx();
  }
GetWeightEx()
float Entity::GetWeightEx (bool forceRecalc = false) inline protected
returns overall weight of the entity, 'forceRecalc = true' is meant to be used only when debugging, using it in gameplay code is higly inadvisable as it bypasses the weight caching and has adverse effect on performance
Definition at line 2632 of file EntityAI.c.
  {
    if (m_WeightDirty || forceRecalc)//recalculate
    {
      m_WeightEx = GetWeightSpecialized(forceRecalc);
      ClearWeightDirty();
#ifdef DEVELOPER
      if (WeightDebug.m_VerbosityFlags & WeightDebugType.RECALC_FORCED)
        WeightDebug.GetWeightDebug(this).SetWeight(m_WeightEx);
      if (WeightDebug.m_VerbosityFlags & WeightDebugType.RECALC_DIRTY)
      {
        Print("ent:" + this + " - Dirty Recalc");
        if (WeightDebug.m_VerbosityFlags & WeightDebugType.DUMP_STACK)
          DumpStack();
      }
#endif
    }
    return m_WeightEx;
  }
References DumpStack(), GetWeightSpecialized(), and Print().
GetWeightSpecialized()
float Entity::GetWeightSpecialized (bool forceRecalc = false) inline protected
returns weight of the entity in a way that's specific to the entity type and is internal to the weight system calculation, to obtain entity's weight, use the 'GetWeightEx' method instead
Definition at line 2625 of file EntityAI.c.
  {
    return GetInventoryAndCargoWeight(forceRecalc);
  }
GetWet()
float Entity::GetWet () inline protected
Definition at line 1902 of file EntityAI.c.
  {
    return 0;
  }
GetWetInit()
float Entity::GetWetInit () inline protected
Definition at line 1917 of file EntityAI.c.
  {
    return 0;
  }
GetWetLevel()
EWetnessLevel Entity::GetWetLevel () protected
GetWetLevelInternal()
static EWetnessLevel Entity::GetWetLevelInternal (float wetness) inline static protected
Definition at line 1934 of file EntityAI.c.
  {
    if (wetness < GameConstants.STATE_DAMP)
      return EWetnessLevel.DRY;
    else if (wetness < GameConstants.STATE_WET)
      return EWetnessLevel.DAMP;
    else if (wetness < GameConstants.STATE_SOAKING_WET)
      return EWetnessLevel.WET;
    else if (wetness < GameConstants.STATE_DRENCHED)
      return EWetnessLevel.SOAKING;
    return EWetnessLevel.DRENCHED;
  }
References GameConstants::STATE_DAMP, GameConstants::STATE_DRENCHED, GameConstants::STATE_SOAKING_WET, and GameConstants::STATE_WET.
GetWetMax()
float Entity::GetWetMax () inline protected
Definition at line 1907 of file EntityAI.c.
  {
    return 0;
  }
GetWetMin()
float Entity::GetWetMin () inline protected
Definition at line 1912 of file EntityAI.c.
  {
    return 0;
  }
GetWetWeightModifier()
float Entity::GetWetWeightModifier () inline protected
Definition at line 2552 of file EntityAI.c.
  {
    return CfgGameplayHandler.GetWetnessWeightModifiers()[GetWetLevel()];
  }
References GetWetLevel(), and CfgGameplayHandler::GetWetnessWeightModifiers().
HasAnyCargo()
bool Entity::HasAnyCargo () inline protected
is this container empty or not, checks only cargo
Definition at line 543 of file EntityAI.c.
  {
    CargoBase cargo = GetInventory().GetCargo();
    if (!cargo) return false; //this is not a cargo container
    if (cargo.GetItemCount() > 0)
      return true;
    else
      return false;
  }
HasBayonetAttached()
bool Entity::HasBayonetAttached () inline protected
Definition at line 2974 of file EntityAI.c.
{};
HasButtstockAttached()
bool Entity::HasButtstockAttached () inline protected
Definition at line 2978 of file EntityAI.c.
{};
HasComponent()
bool Entity::HasComponent (int comp_type) inline private
IsComponentExist.
Definition at line 260 of file EntityAI.c.
  {
    if (m_ComponentsBank)
      return m_ComponentsBank.IsComponentAlreadyExist(comp_type);
    return false;
  }
HasEnergyManager()
bool Entity::HasEnergyManager () inline protected
If this item has class EnergyManager in its config then it returns true. Otherwise returns false.
Definition at line 2450 of file EntityAI.c.
  {
    return HasComponent(COMP_TYPE_ENERGY_MANAGER);
  }
References COMP_TYPE_ENERGY_MANAGER.
HasFlammableMaterial()
bool Entity::HasFlammableMaterial () inline protected
Override this method to return TRUE when this item has or can provide fire. Evaluated on server and client.
Definition at line 417 of file EntityAI.c.
  {
    return false;
  }
HasInternalExclusionConflicts()
bool Entity::HasInternalExclusionConflicts (int targetSlot) inline private
checks if any attachment or item state would interfere with this being attached into a different slot (Headgear -> Mask)
Definition at line 3444 of file EntityAI.c.
  {
    set<int> targetSlotValues = GetAttachmentExclusionMaskSlot(targetSlot);
    if (targetSlotValues) //can be null, if so, no conflict
    {
      set<int> additionalValues = new set<int>(); //NOT slot values
      additionalValues.InsertSet(GetAttachmentExclusionMaskGlobal());
      additionalValues.InsertSet(GetAttachmentExclusionMaskChildren());
      int countTarget = targetSlotValues.Count();
      for (int i = 0; i < countTarget; i++)
      {
        if (additionalValues.Find(targetSlotValues[i]) != -1)
          return true;
      }
    }
    return false;
  }
HasTurnableValveBehavior()
bool Entity::HasTurnableValveBehavior () protected
Turnable Valve behaviour.
HasWetness()
bool Entity::HasWetness () inline protected
Definition at line 1922 of file EntityAI.c.
  {
    return GetWetMax() - GetWetMin() != 0;
  }
References GetWetMax(), and GetWetMin().
HeightCheckOverride()
float Entity::HeightCheckOverride () inline protected
used as script-side override of distance for specific height checks
Definition at line 520 of file EntityAI.c.
  {
    return 0.0;
  }
HeightStartCheckOverride()
float Entity::HeightStartCheckOverride () inline protected
used as script-side override of start pos for specific height checks
Definition at line 526 of file EntityAI.c.
  {
    return 0.0;
  }
HideAllSelections()
void Entity::HideAllSelections () inline protected
Sets all animation values to 1, making them INVISIBLE if they are configured in models.cfg in such way. These selections must also be defined in the entity's config class in 'AnimationSources'.
Definition at line 1195 of file EntityAI.c.
  {
    string cfg_path = "cfgVehicles " + GetType() + " AnimationSources";
    if (GetGame().ConfigIsExisting(cfg_path))
    {
      int selections = GetGame().ConfigGetChildrenCount(cfg_path);
      for (int i = 0; i < selections; i++)
      {
        string selection_name;
        GetGame().ConfigGetChildName(cfg_path, i, selection_name);
        HideSelection(selection_name);
      }
    }
  }
References GetGame(), and GetType().
HideSelection()
void Entity::HideSelection (string selection_name) inline protected
Hides selection of the given name. Must be configed in config.cpp and models.cfg.
Definition at line 2385 of file EntityAI.c.
  {
    if (!ToDelete())
    {
      SetAnimationPhase(selection_name, 1); // 1 = hide, 0 = unhide!
    }
  }
IgnoreOutOfReachCondition()
Entity::IgnoreOutOfReachCondition () inline protected
Returns
if true, attachment condition for out of reach (inventory) will be ignored
Definition at line 1558 of file EntityAI.c.
  {
    return GetHierarchyRootPlayer() == GetGame().GetPlayer();
  }
References GetGame().
IncreaseLifetime()
proto native void Entity::IncreaseLifetime () protected
Reset economy lifetime to default (seconds)
IncreaseLifetimeUp()
void Entity::IncreaseLifetimeUp () inline protected
Reset economy lifetime to default across entity hierarchy all the way to the topmost entity.
Definition at line 2419 of file EntityAI.c.
  {
    IncreaseLifetime();
    if (GetHierarchyParent())
      GetHierarchyParent().IncreaseLifetimeUp();
  }
InitAttachmentExclusionValues()
void Entity::InitAttachmentExclusionValues () inline private
Definition at line 3150 of file EntityAI.c.
  {
    m_AttachmentExclusionSlotMap = new map<int, ref set<int>>();
    m_AttachmentExclusionMaskGlobal = new set<int>;
    m_AttachmentExclusionMaskChildren = new set<int>();
    int count = GetInventory().GetSlotIdCount();
    //no sense in performing inits for something that cannot be attached anywhere (hand/lefthand and some other 'special' slots are the reason for creating 'new' sets above)
    if (count == 0)
      return;
    InitInherentSlotExclusionMap();
    InitGlobalExclusionValues();
    InitLegacyConfigExclusionValues();
  }
InitDamageZoneDisplayNameMapping()
void Entity::InitDamageZoneDisplayNameMapping () inline private
Initialize map of damage zone display names for more optimized retrieval.
Definition at line 310 of file EntityAI.c.
  {
    string path_base;
    string path;
    string component_name;
    if (IsWeapon())
      path_base = CFG_WEAPONSPATH;
    else if (IsMagazine())
      path_base = CFG_MAGAZINESPATH;
    else
      path_base = CFG_VEHICLESPATH;
    path_base = string.Format("%1 %2 DamageSystem DamageZones", path_base, GetType());
    if (!GetGame().ConfigIsExisting(path_base))
    {
      component_name = GetDisplayName();
      GetGame().FormatRawConfigStringKeys(component_name);
      m_DamageDisplayNameMap.Insert("".Hash(), component_name);
    }
    else
    {
      TStringArray zone_names = new TStringArray;
      GetDamageZones(zone_names);
      for (int i = 0; i < zone_names.Count(); i++)
      {
        path = string.Format("%1 %2 displayName", path_base, zone_names[i]);
        if (GetGame().ConfigIsExisting(path) && GetGame().ConfigGetTextRaw(path, component_name))
        {
          GetGame().FormatRawConfigStringKeys(component_name);
          m_DamageDisplayNameMap.Insert(zone_names[i].Hash(), component_name);
        }
      }
    }
  }
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, string::Format(), GetGame(), GetType(), and path.
InitDamageZoneMapping()
void Entity::InitDamageZoneMapping () inline private
Initializes script-side map of damage zones and their components (named selections in models)
Definition at line 303 of file EntityAI.c.
  {
    m_DamageZoneMap = new DamageZoneMap;
    DamageSystem.GetDamageZoneMap(this, m_DamageZoneMap);
  }
InitGlobalExclusionValues()
void Entity::InitGlobalExclusionValues () protected
override to init part of the mask, independent of slot-specific behavior
InitInherentSlotExclusionMap()
void Entity::InitInherentSlotExclusionMap () inline private
map stored on instance to better respond to various state changes
Definition at line 3167 of file EntityAI.c.
  {
    int count = GetInventory().GetSlotIdCount();
    //starting with the INVALID slot, so it is always in the map of attachable items
    SetAttachmentExclusionMaskSlot(InventorySlots.INVALID, GetAttachmentExclusionInitSlotValue(InventorySlots.INVALID));
    int slotId;
    for (int i = 0; i < count; i++)
    {
      slotId = GetInventory().GetSlotId(i);
      SetAttachmentExclusionMaskSlot(slotId, GetAttachmentExclusionInitSlotValue(slotId));
    }
  }
References InventorySlots::INVALID.
InitLegacyConfigExclusionValues()
void Entity::InitLegacyConfigExclusionValues () inline protected
Definition at line 3189 of file EntityAI.c.
  {
    bool performLegacyInit = InitLegacyExclusionCheck();
    //adding implicit slot info AFTER the check is performed
    InitLegacySlotExclusionValuesImplicit();
    if (performLegacyInit)
      InitLegacySlotExclusionValuesDerived();
  }
InitLegacyExclusionCheck()
bool Entity::InitLegacyExclusionCheck () inline protected
Definition at line 3201 of file EntityAI.c.
  {
    //first check the globals
    if (m_AttachmentExclusionMaskGlobal.Count() > 0)
      return false;
    //now the map
    int count = m_AttachmentExclusionSlotMap.Count();
    if (count > 1) //more than InventorySlots.INVALID
    {
      for (int i = 0; i < count; i++)
      {
        int countSet = m_AttachmentExclusionSlotMap.GetElement(i).Count();
        if (countSet > 0) //SOMETHING is defined
          return false;
      }
    }
    return true;
  }
InitLegacySlotExclusionValuesDerived()
void Entity::InitLegacySlotExclusionValuesDerived () inline protected
Definition at line 3280 of file EntityAI.c.
  {
    int slotId;
    int slotCount = GetInventory().GetSlotIdCount();
    for (int i = 0; i < slotCount; i++)
    {
      slotId = GetInventory().GetSlotId(i);
      set<int> tmp;
      switch (slotId)
      {
      case InventorySlots.HEADGEAR:
      {
        tmp = new set<int>;
        tmp.Copy(GetAttachmentExclusionMaskSlot(slotId));
        if (ConfigGetBool("noNVStrap"))
          tmp.Insert(EAttExclusions.LEGACY_HEADSTRAP_HEADGEAR);
        if (ConfigGetBool("noMask"))
          tmp.Insert(EAttExclusions.LEGACY_MASK_HEADGEAR);
        if (ConfigGetBool("noEyewear"))
          tmp.Insert(EAttExclusions.LEGACY_EYEWEAR_HEADGEAR);
        SetAttachmentExclusionMaskSlot(slotId, tmp);
        break;
      }
      case InventorySlots.MASK:
      {
        tmp = new set<int>;
        tmp.Copy(GetAttachmentExclusionMaskSlot(slotId));
        if (ConfigGetBool("noNVStrap"))
          tmp.Insert(EAttExclusions.LEGACY_HEADSTRAP_MASK);
        if (ConfigGetBool("noHelmet"))
          tmp.Insert(EAttExclusions.LEGACY_HEADGEAR_MASK);
        if (ConfigGetBool("noEyewear"))
          tmp.Insert(EAttExclusions.LEGACY_EYEWEAR_MASK);
        SetAttachmentExclusionMaskSlot(slotId, tmp);
        break;
      }
      case InventorySlots.EYEWEAR:
      {
        tmp = new set<int>;
        tmp.Copy(GetAttachmentExclusionMaskSlot(slotId));
        if (ConfigGetBool("isStrap"))
        {
          if (ConfigGetBool("noHelmet"))
            tmp.Insert(EAttExclusions.LEGACY_HEADGEAR_HEADSTRAP);
          if (ConfigGetBool("noMask"))
            tmp.Insert(EAttExclusions.LEGACY_MASK_HEADSTRAP);
        }
        else
        {
          if (ConfigGetBool("noHelmet"))
            tmp.Insert(EAttExclusions.LEGACY_HEADGEAR_EYEWEWEAR);
          if (ConfigGetBool("noMask"))
            tmp.Insert(EAttExclusions.LEGACY_MASK_EYEWEWEAR);
        }
        SetAttachmentExclusionMaskSlot(slotId, tmp);
        break;
      }
      }
    }
  }
InitLegacySlotExclusionValuesImplicit()
Entity::InitLegacySlotExclusionValuesImplicit () inline protected
adding base one-directional relations between headgear, masks, eyewear, and headstraps (exception)
Note
: 'InitLegacyConfigExclusionValues' adds them the other way if the item does not have any script-side exclusions AND has some legacy config parameter.
Definition at line 3227 of file EntityAI.c.
  {
    int slotId;
    int slotCount = GetInventory().GetSlotIdCount();
    for (int i = 0; i < slotCount; i++)
    {
      slotId = GetInventory().GetSlotId(i);
      set<int> tmp;
      switch (slotId)
      {
      case InventorySlots.HEADGEAR:
      {
        tmp = new set<int>;
        tmp.Copy(GetAttachmentExclusionInitSlotValue(slotId));
        tmp.Insert(EAttExclusions.LEGACY_HEADGEAR_MASK);
        tmp.Insert(EAttExclusions.LEGACY_HEADGEAR_HEADSTRAP);
        tmp.Insert(EAttExclusions.LEGACY_HEADGEAR_EYEWEWEAR);
        SetAttachmentExclusionMaskSlot(slotId, tmp);
        break;
      }
      case InventorySlots.MASK:
      {
        tmp = new set<int>;
        tmp.Copy(GetAttachmentExclusionInitSlotValue(slotId));
        tmp.Insert(EAttExclusions.LEGACY_MASK_HEADGEAR);
        tmp.Insert(EAttExclusions.LEGACY_MASK_HEADSTRAP);
        tmp.Insert(EAttExclusions.LEGACY_MASK_EYEWEWEAR);
        SetAttachmentExclusionMaskSlot(slotId, tmp);
        break;
      }
      case InventorySlots.EYEWEAR:
      {
        tmp = new set<int>;
        tmp.Copy(GetAttachmentExclusionInitSlotValue(slotId));
        if (ConfigGetBool("isStrap"))
        {
          tmp.Insert(EAttExclusions.LEGACY_HEADSTRAP_HEADGEAR);
          tmp.Insert(EAttExclusions.LEGACY_HEADSTRAP_MASK);
        }
        else
        {
          tmp.Insert(EAttExclusions.LEGACY_EYEWEAR_HEADGEAR);
          tmp.Insert(EAttExclusions.LEGACY_EYEWEAR_MASK);
        }
        SetAttachmentExclusionMaskSlot(slotId, tmp);
        break;
      }
      }
    }
  }
InsertAgent()
void Entity::InsertAgent (int agent, float count = 1) protected
InterpolateTo()
static proto native void Entity::InterpolateTo (Camera targetCamera, float time, int type) static private
Interpolation between camera instances (current camera becomes targetCamera at the end of interpolation)
Parameters
targetCamera to which camera we want to interpolate
time true interpolation time
type 0 = without dynamics 1 = first half - acceleration, second half deceleration 2 = first third - acceleration, second third - linear movement, last third - deceleration
IsActive()
proto native bool Entity::IsActive () private
Is this camera active?
Returns
bool true if this camera is active
IsAnimal()
bool Entity::IsAnimal () inline protected
Definition at line 583 of file EntityAI.c.
  {
    return false;
  }
IsBasebuildingKit()
bool Entity::IsBasebuildingKit () inline protected
Definition at line 448 of file EntityAI.c.
  {
    return false;
  }
IsBeingPlaced()
bool Entity::IsBeingPlaced () inline protected
Definition at line 1438 of file EntityAI.c.
  {
    return false;
  }
IsDestructionBehaviour()
bool Entity::IsDestructionBehaviour () inline private
Definition at line 254 of file EntityAI.c.
  {
    return false;
  }
IsEmpty()
bool Entity::IsEmpty () inline protected
is this container empty or not, checks both cargo and attachments
Definition at line 532 of file EntityAI.c.
  {
    return (!HasAnyCargo() && GetInventory().AttachmentCount() == 0);
  }
IsEnabled()
proto native bool Entity::IsEnabled () private
IsEntityAI()
override bool Entity::IsEntityAI () inline protected
Definition at line 571 of file EntityAI.c.
{ return true; }
IsExclusionFlagPresent()
bool Entity::IsExclusionFlagPresent (set< int > values) inline protected
checks 'this' if the incoming flag is present for the current state (slot behavior and others)
Definition at line 3464 of file EntityAI.c.
  {
    int slotId;
    string slotName;
    GetInventory().GetCurrentAttachmentSlotInfo(slotId, slotName); //if currently attached, treat it accordingly
    set<int> currentSlotValuesAll = GetAttachmentExclusionMaskAll(slotId);
    int count = values.Count();
    for (int i = 0; i < count; i++)
    {
      if (currentSlotValuesAll.Find(values[i]) != -1)
        return true;
    }
    return false;
  }
References slotName.
IsExclusionFlagPresentRecursive()
bool Entity::IsExclusionFlagPresentRecursive (set< int > values, int targetSlot) inline protected
Gets flag from what is effectively an owner.
Definition at line 3481 of file EntityAI.c.
  {
    if (values && values.Count() != 0)
    {
      InventoryLocation lcn = new InventoryLocation();
      GetInventory().GetCurrentInventoryLocation(lcn);
      EntityAI parent = GetHierarchyParent();
      set<int> passThis;
      if (CheckExclusionAccessCondition(lcn.GetSlot(), targetSlot, values, passThis))
      {
        if (parent && parent != this) //we reached root if false
          return parent.IsExclusionFlagPresentRecursive(passThis, lcn.GetSlot());
      }
      return IsExclusionFlagPresent(passThis);
    }
    return false;
  }
IsFlareVisible()
proto native bool Entity::IsFlareVisible () private
IsHeavyBehaviour()
bool Entity::IsHeavyBehaviour () inline protected
returns item behaviour of item (more in ItemBase)
Definition at line 2833 of file EntityAI.c.
  {
    return false;
  }
IsHologram()
override bool Entity::IsHologram () inline protected
Definition at line 1443 of file EntityAI.c.
  {
    return false;
  }
IsIgnited()
bool Entity::IsIgnited () inline protected
Override this method and make it so it returns whenever this item is on fire right now or not. Evaluated on Server and Client.
Definition at line 435 of file EntityAI.c.
  {
    if (m_EM)
      return m_EM.IsWorking();
    return false;
  }
References ComponentEnergyManager::IsWorking().
IsIgnoredByConstruction()
bool Entity::IsIgnoredByConstruction () inline protected
Definition at line 598 of file EntityAI.c.
  {
    return IsDamageDestroyed();
  }
References IsDamageDestroyed().
IsInitialized()
bool Entity::IsInitialized () inline protected
Definition at line 214 of file EntityAI.c.
  {
    return m_Initialized;
  }
References m_Initialized.
IsInventoryVisible()
bool Entity::IsInventoryVisible () inline protected
Definition at line 573 of file EntityAI.c.
  {
    return !(GetParent() || GetHierarchyParent());
  }
References GetParent().
IsLockedInSlot()
Entity::IsLockedInSlot () inline protected
Returns
true if entity is locked in attachment slot
Definition at line 1610 of file EntityAI.c.
  {
    EntityAI parent = GetHierarchyParent();
    if (parent)
    {
      InventoryLocation inventory_location = new InventoryLocation();
      GetInventory().GetCurrentInventoryLocation(inventory_location);
      return parent.GetInventory().GetSlotLock(inventory_location.GetSlot());
    }
    return false;
  }
IsManagingArrows()
bool Entity::IsManagingArrows () inline protected
Definition at line 3550 of file EntityAI.c.
  {
    return false;
  }
IsOneHandedBehaviour()
bool Entity::IsOneHandedBehaviour () inline protected
returns item behaviour of item (more in ItemBase)
Definition at line 2839 of file EntityAI.c.
  {
    return false;
  }
IsPilotLight()
proto native bool Entity::IsPilotLight () protected
IsPlayer()
bool Entity::IsPlayer () inline protected
Definition at line 578 of file EntityAI.c.
  {
    return false;
  }
IsPreparedToDelete()
bool Entity::IsPreparedToDelete () inline protected
Definition at line 675 of file EntityAI.c.
  {
    return m_PreparedToDelete;
  }
IsPrepareToDelete()
bool Entity::IsPrepareToDelete () inline protected
Definition at line 687 of file EntityAI.c.
  {
    return false;
  }
IsRefresherSignalingViable()
bool Entity::IsRefresherSignalingViable () inline private
Definition at line 286 of file EntityAI.c.
  {
    if (IsRuined())
      return false;
    return m_RefresherViable;
  }
IsSetForDeletion()
bool Entity::IsSetForDeletion () inline protected
Definition at line 657 of file EntityAI.c.
  {
    return IsPreparedToDelete() || m_PendingDelete || ToDelete() || IsPendingDeletion();
  }
References IsPendingDeletion().
IsSimpleHiddenSelectionVisible()
proto native bool Entity::IsSimpleHiddenSelectionVisible (int index) protected
IsSkinned()
bool Entity::IsSkinned () inline protected
Skinning.
Definition at line 395 of file EntityAI.c.
  {
    return GetCompBS() && GetCompBS().IsSkinned();
  }
IsTakeable()
bool Entity::IsTakeable () inline protected
Definition at line 1579 of file EntityAI.c.
  {
    return false;
  }
IsTargetIgnitionSuccessful()
bool Entity::IsTargetIgnitionSuccessful (EntityAI item_target) inline protected
Final evaluation just before the target item is actually ignited. Evaluated on Server.
Definition at line 484 of file EntityAI.c.
  {
    return true;
  }
IsThisIgnitionSuccessful()
bool Entity::IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline protected
Final evaluation just before this item is actually ignited from fire source. Evaluated on Server.
Definition at line 490 of file EntityAI.c.
  {
    return true;
  }
IsTwoHandedBehaviour()
bool Entity::IsTwoHandedBehaviour () inline protected
returns item behaviour of item (more in ItemBase)
Definition at line 2845 of file EntityAI.c.
  {
    return false;
  }
IsUniversalTemperatureSource()
bool Entity::IsUniversalTemperatureSource () inline protected
Universal Temperature Sources Helpers.
Definition at line 3105 of file EntityAI.c.
  {
    return GetUniversalTemperatureSource() != null && GetUniversalTemperatureSource().IsActive();
  }
IsValveTurnable()
bool Entity::IsValveTurnable (int pValveIndex) protected
IsVisibleDuringDaylight()
proto native bool Entity::IsVisibleDuringDaylight () private
IsZombie()
bool Entity::IsZombie () inline protected
Definition at line 588 of file EntityAI.c.
  {
    return false;
  }
IsZombieMilitary()
bool Entity::IsZombieMilitary () inline protected
Definition at line 593 of file EntityAI.c.
  {
    return false;
  }
KeepHealthOnReplace()
bool Entity::KeepHealthOnReplace () inline protected
Definition at line 907 of file EntityAI.c.
  {
    return false;
  }
LocalDropEntity()
bool Entity::LocalDropEntity (notnull EntityAI item) inline protected
Definition at line 1812 of file EntityAI.c.
  {
    return false;
  }
LocalTakeEntityAsAttachment()
bool Entity::LocalTakeEntityAsAttachment (notnull EntityAI item) inline protected
Definition at line 1798 of file EntityAI.c.
  {
    return GetInventory().TakeEntityAsAttachment(InventoryMode.LOCAL, item);
  }
LocalTakeEntityAsAttachmentEx()
bool Entity::LocalTakeEntityAsAttachmentEx (notnull EntityAI item, int slot) inline protected
Definition at line 1731 of file EntityAI.c.
  {
    return GetInventory().TakeEntityAsAttachmentEx(InventoryMode.LOCAL, item, slot);
  }
LocalTakeEntityToCargo()
bool Entity::LocalTakeEntityToCargo (notnull EntityAI item) inline protected
Definition at line 1667 of file EntityAI.c.
  {
    return GetInventory().TakeEntityToCargo(InventoryMode.LOCAL, item);
  }
LocalTakeEntityToCargoEx()
bool Entity::LocalTakeEntityToCargoEx (notnull EntityAI item, int idx, int row, int col) inline protected
Definition at line 1701 of file EntityAI.c.
  {
    return GetInventory().TakeEntityToCargoEx(InventoryMode.LOCAL, item, idx, row, col);
  }
LocalTakeEntityToInventory()
bool Entity::LocalTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline protected
Definition at line 1634 of file EntityAI.c.
  {
    return GetInventory().TakeEntityToInventory(InventoryMode.LOCAL, flags, item);
  }
LocalTakeEntityToTargetAttachment()
bool Entity::LocalTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline protected
Definition at line 1763 of file EntityAI.c.
  {
    return GetInventory().TakeEntityAsTargetAttachment(InventoryMode.LOCAL, target, item);
  }
LocalTakeEntityToTargetAttachmentEx()
bool Entity::LocalTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline protected
Definition at line 1747 of file EntityAI.c.
  {
    return GetInventory().TakeEntityAsTargetAttachmentEx(InventoryMode.LOCAL, target, item, slot);
  }
LocalTakeEntityToTargetCargo()
bool Entity::LocalTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline protected
Definition at line 1683 of file EntityAI.c.
  {
    return GetInventory().TakeEntityToTargetCargo(InventoryMode.LOCAL, target, item);
  }
LocalTakeEntityToTargetCargoEx()
bool Entity::LocalTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline protected
Definition at line 1713 of file EntityAI.c.
  {
    return GetInventory().TakeEntityToTargetCargoEx(InventoryMode.LOCAL, cargo, item, row, col);
  }
LocalTakeEntityToTargetInventory()
bool Entity::LocalTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline protected
Definition at line 1649 of file EntityAI.c.
  {
    return GetInventory().TakeEntityToTargetInventory(InventoryMode.LOCAL, target, flags, item);
  }
LocalTakeToDst()
bool Entity::LocalTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline protected
Definition at line 1779 of file EntityAI.c.
  {
    return GetInventory().TakeToDst(InventoryMode.LOCAL, src, dst);
  }
Log()
void Entity::Log (string msg, string fnc_name = "n/a") inline protected
Log.
Definition at line 377 of file EntityAI.c.
  {
    Debug.Log(msg, "Object", "n/a", fnc_name, this.GetType());
  }
References GetType(), and Debug::Log().
LogError()
void Entity::LogError (string msg, string fnc_name = "n/a") inline protected
LogError.
Definition at line 389 of file EntityAI.c.
  {
    Debug.LogError(msg, "Object", "n/a", fnc_name, this.GetType());
  }
References GetType(), and Debug::LogError().
LogWarning()
void Entity::LogWarning (string msg, string fnc_name = "n/a") inline protected
LogWarning.
Definition at line 383 of file EntityAI.c.
  {
    Debug.LogWarning(msg, "Object", "n/a", fnc_name, this.GetType());
  }
References GetType(), and Debug::LogWarning().
LookAt()
proto native void Entity::LookAt (vector targetPos) private
Orientation change by lookAt point.
Parameters
targetPos where to look at
MaxLifetimeRefreshCalc()
void Entity::MaxLifetimeRefreshCalc () inline private
Calculates if the max lifetime is higher than refresher frequency (i.e. gets kept alive by refresher)
Definition at line 269 of file EntityAI.c.
  {
    if ((!GetGame().IsMultiplayer() || GetGame().IsServer()) && GetEconomyProfile())
    {
      float lifetime = GetEconomyProfile().GetLifetime();
      int frequency = GetCEApi().GetCEGlobalInt("FlagRefreshFrequency");
      if (frequency <= 0)
        frequency = GameConstants.REFRESHER_FREQUENCY_DEFAULT;
      if (frequency <= lifetime)
      {
        m_RefresherViable = true;
        SetSynchDirty();
      }
    }
  }
References GetCEApi(), GetGame(), and GameConstants::REFRESHER_FREQUENCY_DEFAULT.
OnAction()
bool Entity::OnAction (int action_id, Man player, ParamsReadContext ctx) inline protected
Definition at line 2669 of file EntityAI.c.
  {
    if (action_id == EActions.FIX_ENTITY)
    {
#ifdef DIAG_DEVELOPER
      FixEntity();
#endif
    }
    else if (action_id == EActions.GET_TOTAL_WEIGHT) //Prints total weight of item + its contents
    {
      WeightDebug.ClearWeightDebug();
#ifndef SERVER
      Debug.Log("======================== " + GetType() + " =================================");
#endif
      Debug.Log("Weight:" + GetWeightEx().ToString());
      Debug.Log("Weight excluding cargo and attachments:" + GetSingleInventoryItemWeightEx());
      Debug.Log("----------------------------------------------------------------------------------------------");
    }
    else if (action_id == EActions.GET_TOTAL_WEIGHT_RECALC) //Prints total weight of item + its contents
    {
      WeightDebug.ClearWeightDebug();
      WeightDebug.SetVerbosityFlags(WeightDebugType.RECALC_FORCED);
#ifndef SERVER
      Debug.Log("======================== " + GetType() + " RECALC ===========================");
#endif
      Debug.Log("Weight:" + GetWeightEx(true).ToString());
      Debug.Log("Weight excluding cargo and attachments:" + GetSingleInventoryItemWeightEx());
      WeightDebug.PrintAll(this);
      Debug.Log("----------------------------------------------------------------------------------------------");
      WeightDebug.SetVerbosityFlags(0);
    }
    else if (action_id == EActions.GET_PLAYER_WEIGHT) //Prints total weight of item + its contents
    {
      WeightDebug.ClearWeightDebug();
#ifndef SERVER
      Debug.Log("======================== PLAYER: " + player + " ===========================");
#endif
      Debug.Log("New overall weight Player:" + player.GetWeightEx().ToString());
      Debug.Log("----------------------------------------------------------------------------------------------");
    }
    else if (action_id == EActions.GET_PLAYER_WEIGHT_RECALC) //Prints total weight of item + its contents
    {
      WeightDebug.ClearWeightDebug();
      WeightDebug.SetVerbosityFlags(WeightDebugType.RECALC_FORCED);
#ifndef SERVER
      Debug.Log("======================== PLAYER RECALC: " + player + " ===========================");
#endif
      Debug.Log("New overall weight Player:" + player.GetWeightEx(true).ToString());
      WeightDebug.PrintAll(player);
      Debug.Log("----------------------------------------------------------------------------------------------");
      WeightDebug.SetVerbosityFlags(0);
    }
    return false;
  }
References GetSingleInventoryItemWeightEx(), GetType(), Debug::Log(), and ToString().
OnAttachmentRuined()
void Entity::OnAttachmentRuined (EntityAI attachment) inline protected
Called when some attachment of this parent is ruined. Called on server and client side.
Definition at line 922 of file EntityAI.c.
  {
    // ...
  }
OnBeforeTryDelete()
void Entity::OnBeforeTryDelete () protected
OnBinLoadItemsDropped()
void Entity::OnBinLoadItemsDropped () inline protected
Called when an item fails to get loaded into the inventory of an entity and gets dropped.
Definition at line 1188 of file EntityAI.c.
  {
    if (GetHierarchyRootPlayer())
      GetHierarchyRootPlayer().SetProcessUIWarning(true);
  }
OnCargoChanged()
void Entity::OnCargoChanged () inline protected
Definition at line 1577 of file EntityAI.c.
{ }
OnCEUpdate()
void Entity::OnCEUpdate () inline protected
Central economy calls this function whenever going over all the entities.
void OnCEUpdate()
{
// dont forget to propagate this call trough class hierarchy! - always at the start of the function
super.OnCEUpdate();
// use m_ElapsedSinceLastUpdate for time-related purposes
}
Definition at line 2865 of file EntityAI.c.
  {
    float currentTime = GetGame().GetTickTime();
    if (m_LastUpdatedTime == 0)
      m_LastUpdatedTime = currentTime;
    m_ElapsedSinceLastUpdate = currentTime - m_LastUpdatedTime;
    m_LastUpdatedTime = currentTime;
  }
References GetGame().
OnDamageDestroyed()
void Entity::OnDamageDestroyed (int oldLevel) protected
Called when the health gets to the min value, 'oldLevel' is previous health level, 'oldLevel' -1 means this entity was just spawned.
OnDebugButtonPressClient()
void Entity::OnDebugButtonPressClient (int button_index) inline protected
Definition at line 2350 of file EntityAI.c.
{} //DEPRICATED, USE GetDebugActions / OnAction
OnDebugButtonPressServer()
void Entity::OnDebugButtonPressServer (int button_index) inline protected
Definition at line 2351 of file EntityAI.c.
{} //DEPRICATED, USE GetDebugActions / OnAction
OnDebugSpawn()
void Entity::OnDebugSpawn () inline protected
Definition at line 2880 of file EntityAI.c.
  {
    array<string> slots = new array<string>;
    ConfigGetTextArray("Attachments", slots);
    array<string> mags = new array<string>;
    ConfigGetTextArray("magazines", mags);
    //-------
    TStringArray all_paths = new TStringArray;
    all_paths.Insert(CFG_VEHICLESPATH);
    all_paths.Insert(CFG_MAGAZINESPATH);
    all_paths.Insert(CFG_WEAPONSPATH);
    string config_path;
    string child_name;
    int scope;
    string path;
    int consumable_count;
    for (int i = 0; i < all_paths.Count(); i++)
    {
      config_path = all_paths.Get(i);
      int children_count = GetGame().ConfigGetChildrenCount(config_path);
      for (int x = 0; x < children_count; x++)
      {
        GetGame().ConfigGetChildName(config_path, x, child_name);
        path = config_path + " " + child_name;
        scope = GetGame().ConfigGetInt(config_path + " " + child_name + " scope");
        bool should_check = 1;
        if (config_path == "CfgVehicles" && scope == 0)
          should_check = 0;
        if (should_check)
        {
          string inv_slot;
          GetGame().ConfigGetText(config_path + " " + child_name + " inventorySlot", inv_slot);
          for (int z = 0; z < slots.Count(); z++)
          {
            if (slots.Get(z) == inv_slot)
            {
              this.GetInventory().CreateInInventory(child_name);
              continue;
              //Print("matching attachment: " + child_name + " for inv. slot name:" +inv_slot);
            }
          }
        }
      }
    }
  };
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, GetGame(), path, and x.
OnDebugSpawnEx()
void Entity::OnDebugSpawnEx (DebugSpawnParams params) inline protected
Definition at line 2875 of file EntityAI.c.
  {
    OnDebugSpawn();
  }
References OnDebugSpawn.
OnEnergyAdded()
void Entity::OnEnergyAdded () inline protected
Energy manager event: Called when energy was added on this device. ALWAYS CALL super.OnEnergyAdded() !!!
Definition at line 2491 of file EntityAI.c.
{}
OnEnergyConsumed()
void Entity::OnEnergyConsumed () inline protected
Energy manager event: Called when energy was consumed on this device. ALWAYS CALL super.OnEnergyConsumed() !!!
Definition at line 2488 of file EntityAI.c.
{}
OnExplosionEffects()
override void Entity::OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType) inline protected
Definition at line 778 of file EntityAI.c.
  {
    super.OnExplosionEffects(source, directHit, componentIndex, surface, pos, surfNormal, energyFactor, explosionFactor, isWater, ammoType);
#ifndef SERVER
    g_Game.GetWorld().AddEnvShootingSource(pos, 1.0);
#endif
    if (m_DestructionBehaviourObj && m_DestructionBehaviourObj.HasExplosionDamage())
      m_DestructionBehaviourObj.OnExplosionEffects(source, directHit, componentIndex, surface, pos, surfNormal, energyFactor, explosionFactor, isWater, ammoType);
  }
References g_Game.
OnHologramBeingPlaced()
void Entity::OnHologramBeingPlaced (Man player) protected
OnIgnitedTarget()
void Entity::OnIgnitedTarget (EntityAI target_item) inline protected
Executed on Server when this item ignites some target item.
Definition at line 460 of file EntityAI.c.
  {
  }
OnIgnitedTargetFailed()
void Entity::OnIgnitedTargetFailed (EntityAI target_item) inline protected
Executed on Server when this item failed to ignite target item.
Definition at line 472 of file EntityAI.c.
  {
  }
OnIgnitedThis()
void Entity::OnIgnitedThis (EntityAI fire_source) inline protected
Executed on Server when some item ignited this one.
Definition at line 466 of file EntityAI.c.
  {
  }
OnIgnitedThisFailed()
void Entity::OnIgnitedThisFailed (EntityAI fire_source) inline protected
Executed on Server when some item failed to ignite this one.
Definition at line 478 of file EntityAI.c.
  {
  }
OnInitEnergy()
void Entity::OnInitEnergy () inline protected
Energy manager event: Object's initialization. Energy Manager is fully initialized by this point.
Definition at line 2485 of file EntityAI.c.
{}
OnInventoryInit()
void Entity::OnInventoryInit () inline protected
Definition at line 738 of file EntityAI.c.
  {
    InitAttachmentExclusionValues();
  }
OnIsPlugged()
void Entity::OnIsPlugged (EntityAI source_device) inline protected
Energy manager event: Called when this device is plugged into some energy source.
Definition at line 2473 of file EntityAI.c.
{}
OnIsUnplugged()
void Entity::OnIsUnplugged (EntityAI last_energy_source) inline protected
Energy manager event: Called when this device is UNPLUGGED from the energy source.
Definition at line 2476 of file EntityAI.c.
{}
OnItemAttachmentSlotChanged()
void Entity::OnItemAttachmentSlotChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline protected
Definition at line 791 of file EntityAI.c.
{}
OnItemLocationChanged()
void Entity::OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline protected
Definition at line 789 of file EntityAI.c.
{ }
OnMovedInsideCargo()
void Entity::OnMovedInsideCargo (EntityAI container) inline protected
Called when this item enters cargo of some container.
Definition at line 1126 of file EntityAI.c.
  {
    if (m_EM)
      m_EM.HandleMoveInsideCargo(container);
  }
References ComponentEnergyManager::HandleMoveInsideCargo().
OnMovedWithinCargo()
void Entity::OnMovedWithinCargo (EntityAI container) inline protected
Called when this item moves within cargo of some container.
Definition at line 1139 of file EntityAI.c.
  {
  }
OnOwnSocketReleased()
void Entity::OnOwnSocketReleased (EntityAI device) inline protected
Energy manager event: When something is UNPLUGGED from this device.
Definition at line 2482 of file EntityAI.c.
{}
OnOwnSocketTaken()
void Entity::OnOwnSocketTaken (EntityAI device) inline protected
Energy manager event: When something is plugged into this device.
Definition at line 2479 of file EntityAI.c.
{}
OnPlacementCancelled()
void Entity::OnPlacementCancelled (Man player) protected
OnPlacementComplete()
void Entity::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") protected
OnPlacementStarted()
void Entity::OnPlacementStarted (Man player) protected
OnRemovedFromCargo()
void Entity::OnRemovedFromCargo (EntityAI container) inline protected
Called when this item exits cargo of some container.
Definition at line 1133 of file EntityAI.c.
  {
  }
OnRPC()
override void Entity::OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) inline protected
Definition at line 2494 of file EntityAI.c.
  {
    super.OnRPC(sender, rpc_type, ctx);
    if (GetGame().IsClient())
    {
      switch (rpc_type)
      {
      // BODY STAGING - server => client synchronization of skinned state.
      case ERPCs.RPC_BS_SKINNED_STATE:
      {
        Param1<bool> p_skinned_state = new Param1<bool>(false);
        if (ctx.Read(p_skinned_state))
        {
          float state = p_skinned_state.param1;
          if (state && GetCompBS())
            GetCompBS().SetAsSkinnedClient();
        }
        break;
      }
      case ERPCs.RPC_EXPLODE_EVENT:
      {
        OnExplodeClient();
        break;
      }
      }
    }
  }
References GetGame().
OnStoreLoad()
bool Entity::OnStoreLoad (ParamsReadContext ctx, int version) inline protected
Called when data is loaded from persistence (on server side).
void OnStoreLoad(ParamsReadContext ctx, int version)
{
// dont forget to propagate this call trough class hierarchy!
if (!super.OnStoreLoad(ctx, version))
  return false;
// read data loaded from game database (format and order of reading must be the same as writing!)
int a;
if (!ctx.Read(a))
  return false;
float b;
if (!ctx.Read(b))
  return false;
return true;
}
Definition at line 2192 of file EntityAI.c.
  {
    // Restoring of energy related states
    if (m_EM)
    {
      // Load energy amount
      float f_energy = 0;
      if (!ctx.Read(f_energy))
        f_energy = 0;
      m_EM.SetEnergy(f_energy);
      // Load passive/active state
      bool b_is_passive = false;
      if (!ctx.Read(b_is_passive))
        return false;
      m_EM.SetPassiveState(b_is_passive);
      // Load ON/OFF state
      bool b_is_on = false;
      if (!ctx.Read(b_is_on))
      {
        m_EM.SwitchOn();
        return false;
      }
      // Load plugged/unplugged state
      bool b_is_plugged = false;
      if (!ctx.Read(b_is_plugged))
        return false;
      // ENERGY SOURCE
      if (version <= 103)
      {
        // Load energy source ID low
        int i_energy_source_ID_low = 0; // Even 0 can be valid ID!
        if (!ctx.Read(i_energy_source_ID_low))
          return false;
        // Load energy source ID high
        int i_energy_source_ID_high = 0; // Even 0 can be valid ID!
        if (!ctx.Read(i_energy_source_ID_high))
          return false;
      }
      else
      {
        int b1 = 0;
        int b2 = 0;
        int b3 = 0;
        int b4 = 0;
        if (!ctx.Read(b1)) return false;
        if (!ctx.Read(b2)) return false;
        if (!ctx.Read(b3)) return false;
        if (!ctx.Read(b4)) return false;
        if (b_is_plugged)
        {
          // Because function GetEntityByPersitentID() cannot be called here, ID values must be stored and used later.
          m_EM.StoreEnergySourceIDs(b1, b2, b3, b4);
          m_EM.RestorePlugState(true);
        }
      }
      if (b_is_on)
        m_EM.SwitchOn();
    }
    return true;
  }
References ComponentEnergyManager::RestorePlugState(), ComponentEnergyManager::SetEnergy(), ComponentEnergyManager::SetPassiveState(), ComponentEnergyManager::StoreEnergySourceIDs(), and ComponentEnergyManager::SwitchOn().
OnStoreSave()
void Entity::OnStoreSave (ParamsWriteContext ctx) inline protected
Engine calls this function to collect data from entity to store for persistence (on server side).
void OnStoreSave(ParamsWriteContext ctx)
{
// dont forget to propagate this call trough class hierarchy!
super.OnStoreSave(ctx);
// write any data (using params) you want to store
int   a = 5;
float b = 6.0;
ctx.Write(a);
ctx.Write(b);
}
Definition at line 2133 of file EntityAI.c.
  {
    // Saving of energy related states
    if (m_EM)
    {
      // Save energy amount
      ctx.Write(m_EM.GetEnergy());
      // Save passive/active state
      ctx.Write(m_EM.IsPassive());
      // Save ON/OFF state
      ctx.Write(m_EM.IsSwitchedOn());
      // Save plugged/unplugged state
      ctx.Write(m_EM.IsPlugged());
      // ENERGY SOURCE
      // Save energy source IDs
      EntityAI energy_source = m_EM.GetEnergySource();
      int b1 = 0;
      int b2 = 0;
      int b3 = 0;
      int b4 = 0;
      if (energy_source)
        energy_source.GetPersistentID(b1, b2, b3, b4);
      ctx.Write(b1); // Save energy source block 1
      ctx.Write(b2); // Save energy source block 2
      ctx.Write(b3); // Save energy source block 3
      ctx.Write(b4); // Save energy source block 4
    }
  }
References ComponentEnergyManager::GetEnergy(), ComponentEnergyManager::GetEnergySource(), ComponentEnergyManager::IsPassive(), ComponentEnergyManager::IsPlugged(), and ComponentEnergyManager::IsSwitchedOn().
OnSwitchOff()
void Entity::OnSwitchOff () inline protected
Energy manager event: Called when the device is switched OFF.
Definition at line 2470 of file EntityAI.c.
{}
OnSwitchOn()
void Entity::OnSwitchOn () inline protected
Energy manager event: Called when the device is switched on.
Definition at line 2467 of file EntityAI.c.
{}
OnVariablesSynchronized()
void Entity::OnVariablesSynchronized () inline protected
Called on clients after receiving synchronization data from server.
Definition at line 2268 of file EntityAI.c.
  {
    if (m_EM)
    {
      if (GetGame().IsMultiplayer())
      {
        bool is_on = m_EM.IsSwitchedOn();
        if (is_on != m_EM.GetPreviousSwitchState())
        {
          if (is_on)
            m_EM.SwitchOn();
          else
            m_EM.SwitchOff();
        }
        int id_low = m_EM.GetEnergySourceNetworkIDLow();
        int id_High = m_EM.GetEnergySourceNetworkIDHigh();
        EntityAI energy_source = EntityAI.Cast(GetGame().GetObjectByNetworkId(id_low, id_High));
        if (energy_source)
        {
          ComponentEnergyManager esem = energy_source.GetCompEM();
          if (!esem)
          {
            string object = energy_source.GetType();
            Error("Synchronization error! Object " + object + " has no instance of the Energy Manager component!");
          }
          m_EM.PlugThisInto(energy_source);
        }
        else
          m_EM.UnplugThis();
        m_EM.DeviceUpdate();
        m_EM.StartUpdates();
      }
    }
  }
References ComponentEnergyManager::DeviceUpdate(), Error(), ComponentEnergyManager::GetEnergySourceNetworkIDHigh(), ComponentEnergyManager::GetEnergySourceNetworkIDLow(), GetGame(), ComponentEnergyManager::GetPreviousSwitchState(), ComponentEnergyManager::IsSwitchedOn(), ComponentEnergyManager::PlugThisInto(), ComponentEnergyManager::StartUpdates(), ComponentEnergyManager::SwitchOff(), ComponentEnergyManager::SwitchOn(), and ComponentEnergyManager::UnplugThis().
OnWasAttached()
void Entity::OnWasAttached (EntityAI parent, int slot_id) protected
OnWasDetached()
void Entity::OnWasDetached (EntityAI parent, int slot_id) inline protected
Definition at line 1567 of file EntityAI.c.
  {
    if (!IsFlagSet(EntityFlags.VISIBLE))
    {
      SetInvisible(false);
      OnInvisibleSet(false);
      SetInvisibleRecursive(false, parent);
    }
  }
OnWetChanged()
void Entity::OnWetChanged (float newVal, float oldVal) protected
OnWetLevelChanged()
void Entity::OnWetLevelChanged (EWetnessLevel newLevel, EWetnessLevel oldLevel) protected
OnWork()
void Entity::OnWork (float consumed_energy) inline protected
Energy manager event: Called every device update if its supposed to do some work. The update can be every second or at random, depending on its manipulation.
Definition at line 2461 of file EntityAI.c.
{}
OnWorkStart()
void Entity::OnWorkStart () inline protected
Energy manager event: Called only once when this device starts doing its work.
Definition at line 2458 of file EntityAI.c.
{}
OnWorkStop()
void Entity::OnWorkStop () inline protected
Energy manager event: Called when the device stops working (was switched OFF or ran out of energy)
Definition at line 2464 of file EntityAI.c.
{}
PairRemote()
void Entity::PairRemote (notnull EntityAI trigger) protected
PlacementCanBeRotated()
bool Entity::PlacementCanBeRotated () inline protected
Should return false if you want to disable hologram rotation.
Definition at line 454 of file EntityAI.c.
  {
    return true;
  }
PlaceOnSurfaceRotated()
proto native void Entity::PlaceOnSurfaceRotated (out vector trans[4], vector pos, float dx = 0, float dz = 0, float fAngle = 0, bool align = false) protected
PredictiveDropEntity()
bool Entity::PredictiveDropEntity (notnull EntityAI item) inline protected
Definition at line 1807 of file EntityAI.c.
  {
    return false;
  }
PredictiveTakeEntityAsAttachment()
bool Entity::PredictiveTakeEntityAsAttachment (notnull EntityAI item) inline protected
Put item into as attachment.
Definition at line 1791 of file EntityAI.c.
  {
    if (GetGame().IsMultiplayer())
      return GetInventory().TakeEntityAsAttachment(InventoryMode.JUNCTURE, item);
    else
      return GetInventory().TakeEntityAsAttachment(InventoryMode.PREDICTIVE, item);
  }
References GetGame().
PredictiveTakeEntityAsAttachmentEx()
bool Entity::PredictiveTakeEntityAsAttachmentEx (notnull EntityAI item, int slot) inline protected
Returns if item can be added as attachment on specific slot. Note that slot index IS NOT slot ID! Slot ID is defined in DZ/data/config.cpp.
Definition at line 1724 of file EntityAI.c.
  {
    if (GetGame().IsMultiplayer())
      return GetInventory().TakeEntityAsAttachmentEx(InventoryMode.JUNCTURE, item, slot);
    else
      return GetInventory().TakeEntityAsAttachmentEx(InventoryMode.PREDICTIVE, item, slot);
  }
References GetGame().
PredictiveTakeEntityToCargo()
bool Entity::PredictiveTakeEntityToCargo (notnull EntityAI item) inline protected
Put item into into cargo.
Definition at line 1660 of file EntityAI.c.
  {
    if (GetGame().IsMultiplayer())
      return GetInventory().TakeEntityToCargo(InventoryMode.JUNCTURE, item);
    else
      return GetInventory().TakeEntityToCargo(InventoryMode.PREDICTIVE, item);
  }
References GetGame().
PredictiveTakeEntityToCargoEx()
bool Entity::PredictiveTakeEntityToCargoEx (notnull EntityAI item, int idx, int row, int col) inline protected
Put item into into cargo on specific cargo location.
Definition at line 1694 of file EntityAI.c.
  {
    if (GetGame().IsMultiplayer())
      return GetInventory().TakeEntityToCargoEx(InventoryMode.JUNCTURE, item, idx, row, col);
    else
      return GetInventory().TakeEntityToCargoEx(InventoryMode.PREDICTIVE, item, idx, row, col);
  }
References GetGame().
PredictiveTakeEntityToInventory()
bool Entity::PredictiveTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline protected
Put item anywhere into this entity (as attachment or into cargo, recursively)
Definition at line 1627 of file EntityAI.c.
  {
    if (GetGame().IsMultiplayer())
      return GetInventory().TakeEntityToInventory(InventoryMode.JUNCTURE, flags, item);
    else
      return GetInventory().TakeEntityToInventory(InventoryMode.PREDICTIVE, flags, item);
  }
References GetGame().
PredictiveTakeEntityToTargetAttachment()
bool Entity::PredictiveTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline protected
Definition at line 1756 of file EntityAI.c.
  {
    if (GetGame().IsMultiplayer())
      return GetInventory().TakeEntityAsTargetAttachment(InventoryMode.JUNCTURE, target, item);
    else
      return GetInventory().TakeEntityAsTargetAttachment(InventoryMode.PREDICTIVE, target, item);
  }
References GetGame().
PredictiveTakeEntityToTargetAttachmentEx()
bool Entity::PredictiveTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline protected
Definition at line 1740 of file EntityAI.c.
  {
    if (GetGame().IsMultiplayer())
      return GetInventory().TakeEntityAsTargetAttachmentEx(InventoryMode.JUNCTURE, target, item, slot);
    else
      return GetInventory().TakeEntityAsTargetAttachmentEx(InventoryMode.PREDICTIVE, target, item, slot);
  }
References GetGame().
PredictiveTakeEntityToTargetCargo()
bool Entity::PredictiveTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline protected
Definition at line 1676 of file EntityAI.c.
  {
    if (GetGame().IsMultiplayer())
      return GetInventory().TakeEntityToTargetCargo(InventoryMode.JUNCTURE, target, item);
    else
      return GetInventory().TakeEntityToTargetCargo(InventoryMode.PREDICTIVE, target, item);
  }
References GetGame().
PredictiveTakeEntityToTargetCargoEx()
bool Entity::PredictiveTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline protected
Definition at line 1706 of file EntityAI.c.
  {
    if (GetGame().IsMultiplayer())
      return GetInventory().TakeEntityToTargetCargoEx(InventoryMode.JUNCTURE, cargo, item, row, col);
    else
      return GetInventory().TakeEntityToTargetCargoEx(InventoryMode.PREDICTIVE, cargo, item, row, col);
  }
References GetGame().
PredictiveTakeEntityToTargetInventory()
bool Entity::PredictiveTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline protected
Definition at line 1642 of file EntityAI.c.
  {
    if (GetGame().IsMultiplayer())
      return GetInventory().TakeEntityToTargetInventory(InventoryMode.JUNCTURE, target, flags, item);
    else
      return GetInventory().TakeEntityToTargetInventory(InventoryMode.PREDICTIVE, target, flags, item);
  }
References GetGame().
PredictiveTakeToDst()
bool Entity::PredictiveTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline protected
Definition at line 1772 of file EntityAI.c.
  {
    if (GetGame().IsMultiplayer())
      return GetInventory().TakeToDst(InventoryMode.JUNCTURE, src, dst);
    else
      return GetInventory().TakeToDst(InventoryMode.PREDICTIVE, src, dst);
  }
References GetGame().
ProcessInvulnerabilityCheck()
void Entity::ProcessInvulnerabilityCheck (string servercfg_param) inline protected
Definition at line 2952 of file EntityAI.c.
  {
    if (GetGame() && GetGame().IsMultiplayer() && GetGame().IsServer())
    {
      int invulnerability;
      switch (servercfg_param)
      {
      case "disableContainerDamage":
        invulnerability = CfgGameplayHandler.GetDisableContainerDamage();
        break;
      case "disableBaseDamage":
        invulnerability = CfgGameplayHandler.GetDisableBaseDamage();
        break;
      }
      if (invulnerability > 0)
        SetAllowDamage(false);
    }
  }
References CfgGameplayHandler::GetDisableBaseDamage(), CfgGameplayHandler::GetDisableContainerDamage(), and GetGame().
ProcessMeleeItemDamage()
override EntityAI Entity::ProcessMeleeItemDamage (int mode = 0) inline protected
Definition at line 2934 of file EntityAI.c.
  {
    if (GetGame().IsServer())
      AddHealth("", "Health", -MELEE_ITEM_DAMAGE);
    return this;
  }
References GetGame(), and MELEE_ITEM_DAMAGE.
PropagateExclusionValueRecursive()
void Entity::PropagateExclusionValueRecursive (set< int > values, int slotId) inline private
Definition at line 3376 of file EntityAI.c.
  {
    if (values && values.Count() != 0)
    {
      set<int> passThis;
      InventoryLocation lcn = new InventoryLocation();
      GetInventory().GetCurrentInventoryLocation(lcn);
      if (CheckExclusionAccessPropagation(lcn.GetSlot(), slotId, values, passThis))
      {
        m_AttachmentExclusionMaskChildren.InsertSet(passThis);
        EntityAI parent = GetHierarchyParent();
        if (parent)
          parent.PropagateExclusionValueRecursive(passThis, lcn.GetSlot());
      }
    }
  }
RegisterNetSyncVariableBool()
Entity::RegisterNetSyncVariableBool (string variableName) protected
registers bool variable synchronized over network
Parameters
[in] variableName which variable should be synchronized
RegisterNetSyncVariableBoolSignal()
Entity::RegisterNetSyncVariableBoolSignal (string variableName) protected
when bool variable is true, it's sent to clients and become false again
Parameters
[in] variableName which variable should be synchronized
RegisterNetSyncVariableFloat()
Entity::RegisterNetSyncVariableFloat (string variableName, float minValue = 0, float maxValue = 0, int precision = 1) protected
registers float variable synchronized over network
Parameters
[in] variableName which variable should be synchronized
[in] minValue minimal value used for quantization (when minValue == maxValue, no quatization is done)
[in] maxValue maximal value used for quantization (when minValue == maxValue, no quatization is done)
[in] precision precision in number of digits after decimal point
RegisterNetSyncVariableInt()
Entity::RegisterNetSyncVariableInt (string variableName, int minValue = 0, int maxValue = 0) protected
registers int variable synchronized over network
Parameters
[in] variableName which variable should be synchronized
[in] minValue minimal value used for quantization (when minValue == maxValue, no quatization is done)
[in] maxValue maximal value used for quantization (when minValue == maxValue, no quatization is done)
RegisterNetSyncVariableObject()
Entity::RegisterNetSyncVariableObject (string variableName) protected
registers object variable synchronized over network, only synchronizes if network id is assigned. Doesn't handle object despawn on client
Parameters
[in] variableName which variable should be synchronized
RegisterTransportHit()
void Entity::RegisterTransportHit (Transport transport) inline protected
Definition at line 3042 of file EntityAI.c.
  {
    if (!m_TransportHitRegistered)
    {
      m_TransportHitRegistered = true;
      m_TransportHitVelocity = GetVelocity(transport);
      Car car;
      float damage;
      vector impulse;
      // a different attempt to solve hits from "standing" car to the players
      if (Car.CastTo(car, transport))
      {
        if (car.GetSpeedometerAbsolute() > 2)
        {
          damage = m_TransportHitVelocity.Length();
          ProcessDirectDamage(DT_CUSTOM, transport, "", "TransportHit", "0 0 0", damage);
        }
        else
          m_TransportHitRegistered = false;
        // compute impulse and apply only if the body dies
        if (IsDamageDestroyed() && car.GetSpeedometerAbsolute() > 3)
        {
          impulse = 40 * m_TransportHitVelocity;
          impulse[1] = 40 * 1.5;
          dBodyApplyImpulse(this, impulse);
        }
      }
      else //old solution just in case if somebody use it
      {
        // avoid damage because of small movements
        if (m_TransportHitVelocity.Length() > 0.1)
        {
          damage = m_TransportHitVelocity.Length();
          ProcessDirectDamage(DT_CUSTOM, transport, "", "TransportHit", "0 0 0", damage);
        }
        else
          m_TransportHitRegistered = false;
        // compute impulse and apply only if the body dies
        if (IsDamageDestroyed() && m_TransportHitVelocity.Length() > 0.3)
        {
          impulse = 40 * m_TransportHitVelocity;
          impulse[1] = 40 * 1.5;
          dBodyApplyImpulse(this, impulse);
        }
      }
    }
  }
References dBodyApplyImpulse(), GetVelocity(), IsDamageDestroyed(), and vector::Length().
RemoveAgent()
void Entity::RemoveAgent (int agent_id) protected
RemoveAllAgents()
void Entity::RemoveAllAgents () protected
RemoveAllAgentsExcept()
void Entity::RemoveAllAgentsExcept (int agent_to_keep) protected
ReplaceOnDeath()
bool Entity::ReplaceOnDeath () inline protected
Definition at line 897 of file EntityAI.c.
  {
    return false;
  }
ServerDropEntity()
bool Entity::ServerDropEntity (notnull EntityAI item) inline protected
Definition at line 1817 of file EntityAI.c.
  {
    return false;
  }
ServerTakeEntityAsAttachment()
bool Entity::ServerTakeEntityAsAttachment (notnull EntityAI item) inline protected
Definition at line 1802 of file EntityAI.c.
  {
    return GetInventory().TakeEntityAsAttachment(InventoryMode.SERVER, item);
  }
ServerTakeEntityAsAttachmentEx()
bool Entity::ServerTakeEntityAsAttachmentEx (notnull EntityAI item, int slot) inline protected
Definition at line 1735 of file EntityAI.c.
  {
    return GetInventory().TakeEntityAsAttachmentEx(InventoryMode.SERVER, item, slot);
  }
ServerTakeEntityToCargo()
bool Entity::ServerTakeEntityToCargo (notnull EntityAI item) inline protected
Definition at line 1671 of file EntityAI.c.
  {
    return GetInventory().TakeEntityToCargo(InventoryMode.SERVER, item);
  }
ServerTakeEntityToInventory()
bool Entity::ServerTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline protected
Definition at line 1638 of file EntityAI.c.
  {
    return GetInventory().TakeEntityToInventory(InventoryMode.SERVER, flags, item);
  }
ServerTakeEntityToTargetAttachment()
bool Entity::ServerTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline protected
Definition at line 1767 of file EntityAI.c.
  {
    return GetInventory().TakeEntityAsTargetAttachment(InventoryMode.SERVER, target, item);
  }
ServerTakeEntityToTargetAttachmentEx()
bool Entity::ServerTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline protected
Definition at line 1751 of file EntityAI.c.
  {
    return GetInventory().TakeEntityAsTargetAttachmentEx(InventoryMode.SERVER, target, item, slot);
  }
ServerTakeEntityToTargetCargo()
bool Entity::ServerTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline protected
Definition at line 1687 of file EntityAI.c.
  {
    return GetInventory().TakeEntityToTargetCargo(InventoryMode.SERVER, target, item);
  }
ServerTakeEntityToTargetCargoEx()
bool Entity::ServerTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline protected
Definition at line 1717 of file EntityAI.c.
  {
    return GetInventory().TakeEntityToTargetCargoEx(InventoryMode.SERVER, cargo, item, row, col);
  }
ServerTakeEntityToTargetInventory()
bool Entity::ServerTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline protected
Definition at line 1653 of file EntityAI.c.
  {
    return GetInventory().TakeEntityToTargetInventory(InventoryMode.SERVER, target, flags, item);
  }
ServerTakeToDst()
bool Entity::ServerTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline protected
Definition at line 1783 of file EntityAI.c.
  {
    return GetInventory().TakeToDst(InventoryMode.SERVER, src, dst);
  }
SetActive()
proto native void Entity::SetActive (bool active) private
Sets this camera as active.
SetAITargetCallbacks()
proto native void Entity::SetAITargetCallbacks (AbstractAITargetCallbacks callbacks) protected
SetAmbientAlpha()
proto native void Entity::SetAmbientAlpha (float pAlpha) private
SetAmbientColor()
proto native void Entity::SetAmbientColor (float pRed, float pGreen, float pBlue) private
SetAmbientColorV()
proto native void Entity::SetAmbientColorV (vector pColorVector) private
SetAsSkinned()
void Entity::SetAsSkinned () inline protected
Definition at line 400 of file EntityAI.c.
  {
    if (GetCompBS())
      GetCompBS().SetAsSkinned();
  }
SetAttachmentExclusionMaskGlobal()
void Entity::SetAttachmentExclusionMaskGlobal (set< int > values) inline protected
Definition at line 3361 of file EntityAI.c.
  {
    m_AttachmentExclusionMaskGlobal.Clear();
    m_AttachmentExclusionMaskGlobal.Copy(values);
  }
SetAttachmentExclusionMaskSlot()
void Entity::SetAttachmentExclusionMaskSlot (int slotId, set< int > values) inline protected
sets values for specific slot
Definition at line 3368 of file EntityAI.c.
  {
    if (m_AttachmentExclusionSlotMap)
      m_AttachmentExclusionSlotMap.Set(slotId, values);
    else
      ErrorEx("m_AttachmentExclusionSlotMap not available! Fill the 'inventorySlot[]' in the " + this + " config file.");
  }
References ErrorEx.
SetBayonetAttached()
void Entity::SetBayonetAttached (bool pState, int slot_idx = -1) inline protected
Definition at line 2973 of file EntityAI.c.
{};
SetBrightness()
proto native void Entity::SetBrightness (float pValue) private
SetButtstockAttached()
void Entity::SetButtstockAttached (bool pState, int slot_idx = -1) inline protected
Definition at line 2977 of file EntityAI.c.
{};
SetCastShadow()
proto native void Entity::SetCastShadow (bool pState) private
SetDiffuseAlpha()
proto native void Entity::SetDiffuseAlpha (float pAlpha) private
SetDiffuseColor()
proto native void Entity::SetDiffuseColor (float pRed, float pGreen, float pBlue) private
SetDiffuseColorV()
proto native void Entity::SetDiffuseColorV (vector pColorVector) private
SetEnabled()
proto native void Entity::SetEnabled (bool pState) private
SetFlareRelPosition()
proto native void Entity::SetFlareRelPosition (vector pPosition) private
SetFlareVisible()
proto native void Entity::SetFlareVisible (bool pState) private
SetFocus()
proto native void Entity::SetFocus (float distance, float blur) private
Depth of Field settings.
Parameters
distance DOF distance parameter
blur DOF blur parameter
SetFOV()
proto native void Entity::SetFOV (float fov) private
Field of View settings.
Parameters
fov FOV angle in radians
SetFromProjectile()
void Entity::SetFromProjectile (ProjectileStoppedInfo info) inline protected
Definition at line 3560 of file EntityAI.c.
  {
  }
SetHeatHazePower()
proto native void Entity::SetHeatHazePower (float pValue) private
SetHeatHazeRadius()
proto native void Entity::SetHeatHazeRadius (float pValue) private
SetInvisibleRecursive()
void Entity::SetInvisibleRecursive (bool invisible, EntityAI parent = null, array< int > attachments = null) inline protected
Definition at line 2981 of file EntityAI.c.
  {
    array<int> childrenAtt = new array<int>;
    array<int> attachmentsArray = new array<int>;
    if (attachments)
      attachmentsArray.Copy(attachments);
    else
    {
      for (int i = 0; i < GetInventory().GetAttachmentSlotsCount(); i++)
        attachmentsArray.Insert(GetInventory().GetAttachmentSlotId(i));
    }
    EntityAI item;
    foreach (int slot : attachmentsArray)
    {
      if (parent)
        item = parent.GetInventory().FindAttachment(slot);
      else
        item = this;//GetInventory().FindAttachment(slot);
      if (item)
      {
        if (item.GetInventory().AttachmentCount() > 0)
        {
          for (i = 0; i < item.GetInventory().GetAttachmentSlotsCount(); i++)
            childrenAtt.Insert(item.GetInventory().GetAttachmentSlotId(i));
          SetInvisibleRecursive(invisible, item, childrenAtt);
        }
        item.SetInvisible(invisible);
        item.OnInvisibleSet(invisible);
      }
    }
  }
SetLifetime()
proto native void Entity::SetLifetime (float fLifeTime) protected
Set (override) remaining economy lifetime (seconds)
SetLifetimeMax()
proto native void Entity::SetLifetimeMax (float fLifeTime) protected
Set (override) max economy lifetime per entity instance (seconds)
SetLightType()
proto native void Entity::SetLightType (int pType) private
SetNearPlane()
proto native void Entity::SetNearPlane (float nearPlane) private
set near plane of camera
Parameters
nearPlane clamped internally to 0.01m
SetObjectMaterial()
proto native void Entity::SetObjectMaterial (int index, string mat_name) protected
Change material in hiddenSelections.
SetObjectTexture()
proto native void Entity::SetObjectTexture (int index, string texture_name) protected
Change texture in hiddenSelections.
SetPersistentPairID()
void Entity::SetPersistentPairID (int id) inline protected
Definition at line 3134 of file EntityAI.c.
  {
    RemotelyActivatedItemBehaviour raib = GetRemotelyActivatedItemBehaviour();
    if (raib)
      raib.SetPersistentPairID(id);
  }
References GetRemotelyActivatedItemBehaviour().
SetPilotLight()
proto native void Entity::SetPilotLight (bool isOn) protected
SetPrepareToDelete()
void Entity::SetPrepareToDelete () inline protected
Definition at line 670 of file EntityAI.c.
  {
    m_PreparedToDelete = true;
  }
SetPulseCoef()
proto native void Entity::SetPulseCoef (float pState) private
SetQuantityToMinimum()
void Entity::SetQuantityToMinimum () protected
SetRadius()
proto native void Entity::SetRadius (float pValue) private
SetSimpleHiddenSelectionState()
proto native void Entity::SetSimpleHiddenSelectionState (int index, bool state) protected
Simple hidden selection state; 0 == hidden.
SetSpotLightAngle()
proto native void Entity::SetSpotLightAngle (float pValue) private
SetSynchDirty()
proto native void Entity::SetSynchDirty () protected
Sets object synchronization dirty flag, which signalize that object wants to be synchronized (take effect only in MP on server side)
SetTakeable()
void Entity::SetTakeable (bool pState) protected
SetTemperature()
void Entity::SetTemperature (float value, bool allow_client = false) inline protected
Definition at line 1972 of file EntityAI.c.
{};
SetTemperatureMax()
void Entity::SetTemperatureMax () inline protected
Definition at line 1974 of file EntityAI.c.
{};
SetUniversalTemperatureSource()
void Entity::SetUniversalTemperatureSource (UTemperatureSource uts) inline protected
Definition at line 3115 of file EntityAI.c.
  {
    m_UniversalTemperatureSource = uts;
  }
SetViewIndex()
void Entity::SetViewIndex (int index) inline protected
Sets item preview index.
Definition at line 2731 of file EntityAI.c.
  {
    m_ViewIndex = index;
    if (GetGame().IsServer())
      SetSynchDirty();
  }
References GetGame().
SetVisibleDuringDaylight()
proto native void Entity::SetVisibleDuringDaylight (bool pState) private
SetWeightDirty()
void Entity::SetWeightDirty () inline protected
Definition at line 2584 of file EntityAI.c.
  {
#ifdef DEVELOPER
    if (WeightDebug.m_VerbosityFlags & WeightDebugType.SET_DIRTY_FLAG)
    {
      Print("---------------------------------------");
      Print("ent:" + this + " - SetWeightDirty");
      if (WeightDebug.m_VerbosityFlags & WeightDebugType.DUMP_STACK)
        DumpStack();
      Print("---------------------------------------");
    }
#endif
    m_WeightDirty = 1;
    if (GetHierarchyParent())
      GetHierarchyParent().SetWeightDirty();
  }
References DumpStack(), and Print().
SetWet()
void Entity::SetWet (float value, bool allow_client = false) protected
SetWetMax()
void Entity::SetWetMax () protected
ShowAllSelections()
void Entity::ShowAllSelections () inline protected
Sets all animation values to 0, making them VISIBLE if they are configured in models.cfg in such way. These selections must also be defined in the entity's config class in 'AnimationSources'.
Definition at line 1213 of file EntityAI.c.
  {
    string cfg_path = "cfgVehicles " + GetType() + " AnimationSources";
    if (GetGame().ConfigIsExisting(cfg_path))
    {
      int selections = GetGame().ConfigGetChildrenCount(cfg_path);
      for (int i = 0; i < selections; i++)
      {
        string selection_name;
        GetGame().ConfigGetChildName(cfg_path, i, selection_name);
        ShowSelection(selection_name);
      }
    }
  }
References GetGame(), and GetType().
ShowSelection()
void Entity::ShowSelection (string selection_name) inline protected
Shows selection of the given name. Must be configed in config.hpp and models.cfg.
Definition at line 2394 of file EntityAI.c.
  {
    if (!ToDelete())
    {
      SetAnimationPhase(selection_name, 0); // 1 = hide, 0 = unhide!
    }
  }
SoundHardBushFallingPlay()
void Entity::SoundHardBushFallingPlay () inline protected
Definition at line 3030 of file EntityAI.c.
  {
    EffectSound sound = SEffectManager.PlaySound("hardBushFall_SoundSet", GetPosition());
    sound.SetAutodestroy(true);
  }
References GetPosition, and SEffectManager::PlaySound().
SoundHardTreeFallingPlay()
void Entity::SoundHardTreeFallingPlay () inline protected
Definition at line 3018 of file EntityAI.c.
  {
    EffectSound sound = SEffectManager.PlaySound("hardTreeFall_SoundSet", GetPosition());
    sound.SetAutodestroy(true);
  }
References GetPosition, and SEffectManager::PlaySound().
SoundSoftBushFallingPlay()
void Entity::SoundSoftBushFallingPlay () inline protected
Definition at line 3036 of file EntityAI.c.
  {
    EffectSound sound = SEffectManager.PlaySound("softBushFall_SoundSet", GetPosition());
    sound.SetAutodestroy(true);
  }
References GetPosition, and SEffectManager::PlaySound().
SoundSoftTreeFallingPlay()
void Entity::SoundSoftTreeFallingPlay () inline protected
Definition at line 3024 of file EntityAI.c.
  {
    EffectSound sound = SEffectManager.PlaySound("softTreeFall_SoundSet", GetPosition());
    sound.SetAutodestroy(true);
  }
References GetPosition, and SEffectManager::PlaySound().
SpawnEntityOnGround()
EntityAI Entity::SpawnEntityOnGround (string object_name, vector mat[4]) inline protected
Definition at line 1882 of file EntityAI.c.
  {
    InventoryLocation il = new InventoryLocation();
    il.SetGround(NULL, mat);
    return SpawnEntity(object_name, il, ECE_PLACE_ON_SURFACE, RF_DEFAULT);
  }
References ECE_PLACE_ON_SURFACE, RF_DEFAULT, and SpawnEntity().
SpawnEntityOnGroundPos()
EntityAI Entity::SpawnEntityOnGroundPos (string object_name, vector pos) inline protected
Definition at line 1871 of file EntityAI.c.
  {
    InventoryLocation il = new InventoryLocation();
    vector mat[4];
    Math3D.MatrixIdentity4(mat);
    mat[3] = pos;
    il.SetGround(NULL, mat);
    return SpawnEntity(object_name, il, ECE_PLACE_ON_SURFACE, RF_DEFAULT);
  }
References ECE_PLACE_ON_SURFACE, Math3D::MatrixIdentity4(), RF_DEFAULT, and SpawnEntity().
SpawnInInventoryOrGroundPos()
EntityAI Entity::SpawnInInventoryOrGroundPos (string object_name, GameInventory inv, vector pos) inline protected
Definition at line 1857 of file EntityAI.c.
  {
    if (inv)
    {
      EntityAI res = inv.CreateInInventory(object_name);
      if (res)
        return res;
    }
    return SpawnEntityOnGroundPos(object_name, pos);
  }
SwitchItemSelectionTexture()
void Entity::SwitchItemSelectionTexture (EntityAI item, string slot_name) protected
SwitchItemSelectionTextureEx()
void Entity::SwitchItemSelectionTextureEx (EItemManipulationContext context, Param par = null) protected
SwitchLight()
proto native void Entity::SwitchLight (bool isOn) protected
TranslateSlotFromSelection()
bool Entity::TranslateSlotFromSelection (string selection_name, out int slot_id) inline protected
Definition at line 3099 of file EntityAI.c.
  {
    return false;
  }
TryDelete()
bool Entity::TryDelete () inline protected
Definition at line 692 of file EntityAI.c.
  {
    if (!IsPrepareToDelete())
    {
      Debug.Log("TryDelete - not ready for deletion");
      return false;
    }
    if (GetGame().HasInventoryJunctureItem(this))
    {
      Debug.Log("TryDelete - deferred call");
      GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(TryDelete, DELETE_CHECK_DELAY, false);
      return false;
    }
    OnBeforeTryDelete();
    Debug.Log("TryDelete - OnBeforeTryDelete end");
    DeleteSafe();
    Debug.Log("TryDelete - DeleteSafe end");
    return true;
  }
References CALL_CATEGORY_SYSTEM, GetGame(), IsPrepareToDelete(), and Debug::Log().
UnpairRemote()
void Entity::UnpairRemote () protected
UpdateNetSyncVariableFloat()
proto native void Entity::UpdateNetSyncVariableFloat (string variableName, float minValue = 0, float maxValue = 0, int precision = 1) protected
UpdateNetSyncVariableInt()
proto native void Entity::UpdateNetSyncVariableInt (string variableName, float minValue = 0, float maxValue = 0) protected
UpdateWeight()
void Entity::UpdateWeight (WeightUpdateType updateType = WeightUpdateType.FULL, float weightAdjustment = 0) protected
Member Data Documentation
DEAD_REPLACE_DELAY
const int Entity::DEAD_REPLACE_DELAY = 2000 private
Definition at line 115 of file EntityAI.c.
DELETE_CHECK_DELAY
const int Entity::DELETE_CHECK_DELAY = 100 private
Definition at line 116 of file EntityAI.c.
m_AttachmentExclusionMaskChildren
ref set<int> Entity::m_AttachmentExclusionMaskChildren private
Definition at line 108 of file EntityAI.c.
m_AttachmentExclusionMaskGlobal
ref set<int> Entity::m_AttachmentExclusionMaskGlobal private
Definition at line 107 of file EntityAI.c.
m_AttachmentExclusionSlotMap
ref map<int, ref set<int> > Entity::m_AttachmentExclusionSlotMap private
Definition at line 106 of file EntityAI.c.
m_AttachmentsWithAttachments
ref array<EntityAI> Entity::m_AttachmentsWithAttachments private
Definition at line 119 of file EntityAI.c.
m_AttachmentsWithCargo
ref array<EntityAI> Entity::m_AttachmentsWithCargo private
Definition at line 118 of file EntityAI.c.
m_CanDisplayWeight
bool Entity::m_CanDisplayWeight protected
Definition at line 128 of file EntityAI.c.
m_ComponentsBank
ref ComponentsBank Entity::m_ComponentsBank private
Definition at line 225 of file EntityAI.c.
m_ConfigWeight
float Entity::m_ConfigWeight = ConfigGetInt("weight") private
Definition at line 127 of file EntityAI.c.
m_DamageDisplayNameMap
ref map<int, string> Entity::m_DamageDisplayNameMap = new map<int, string> private
Definition at line 123 of file EntityAI.c.
m_DamageZoneMap
ref DamageZoneMap Entity::m_DamageZoneMap protected
Definition at line 122 of file EntityAI.c.
m_DeathSyncSent
bool Entity::m_DeathSyncSent private
Definition at line 101 of file EntityAI.c.
m_DestructionBehaviourObj
ref DestructionEffectBase Entity::m_DestructionBehaviourObj private
Definition at line 110 of file EntityAI.c.
m_ElapsedSinceLastUpdate
float Entity::m_ElapsedSinceLastUpdate protected
Definition at line 130 of file EntityAI.c.
m_EM
ComponentEnergyManager Entity::m_EM private
Definition at line 226 of file EntityAI.c.
m_HiddenSelectionsData
ref HiddenSelectionsData Entity::m_HiddenSelectionsData private
Definition at line 113 of file EntityAI.c.
m_Initialized
bool Entity::m_Initialized = false protected
Definition at line 135 of file EntityAI.c.
m_KilledByHeadshot
bool Entity::m_KilledByHeadshot private
Definition at line 102 of file EntityAI.c.
m_KillerData
ref KillerData Entity::m_KillerData private
Definition at line 112 of file EntityAI.c.
m_LastUpdatedTime
float Entity::m_LastUpdatedTime private
Definition at line 129 of file EntityAI.c.
m_OldLocation
ref InventoryLocation Entity::m_OldLocation private
Definition at line 120 of file EntityAI.c.
m_OnAttachmentReleaseLock
ref ScriptInvoker Entity::m_OnAttachmentReleaseLock protected
Definition at line 160 of file EntityAI.c.
m_OnAttachmentSetLock
ref ScriptInvoker Entity::m_OnAttachmentSetLock protected
Definition at line 158 of file EntityAI.c.
m_OnHitByInvoker
ref ScriptInvoker Entity::m_OnHitByInvoker protected
Definition at line 162 of file EntityAI.c.
m_OnItemAddedIntoCargo
ref ScriptInvoker Entity::m_OnItemAddedIntoCargo protected
Definition at line 144 of file EntityAI.c.
m_OnItemAttached
ref ScriptInvoker Entity::m_OnItemAttached protected
Definition at line 140 of file EntityAI.c.
m_OnItemDetached
ref ScriptInvoker Entity::m_OnItemDetached protected
Definition at line 142 of file EntityAI.c.
m_OnItemFlipped
ref ScriptInvoker Entity::m_OnItemFlipped protected
Definition at line 150 of file EntityAI.c.
m_OnItemMovedInCargo
ref ScriptInvoker Entity::m_OnItemMovedInCargo protected
Definition at line 148 of file EntityAI.c.
m_OnItemRemovedFromCargo
ref ScriptInvoker Entity::m_OnItemRemovedFromCargo protected
Definition at line 146 of file EntityAI.c.
m_OnKilledInvoker
ref ScriptInvoker Entity::m_OnKilledInvoker protected
Definition at line 164 of file EntityAI.c.
m_OnReleaseLock
ref ScriptInvoker Entity::m_OnReleaseLock protected
Definition at line 156 of file EntityAI.c.
m_OnSetLock
ref ScriptInvoker Entity::m_OnSetLock protected
Definition at line 154 of file EntityAI.c.
m_OnViewIndexChanged
ref ScriptInvoker Entity::m_OnViewIndexChanged protected
Definition at line 152 of file EntityAI.c.
m_PendingDelete
bool Entity::m_PendingDelete = false protected
Definition at line 134 of file EntityAI.c.
m_PreparedToDelete
bool Entity::m_PreparedToDelete = false private
Definition at line 103 of file EntityAI.c.
m_RefresherViable
bool Entity::m_RefresherViable = false private
Definition at line 104 of file EntityAI.c.
m_TransportHitRegistered
bool Entity::m_TransportHitRegistered = false protected
Definition at line 136 of file EntityAI.c.
m_TransportHitVelocity
vector Entity::m_TransportHitVelocity protected
Definition at line 137 of file EntityAI.c.
m_UniversalTemperatureSource
UTemperatureSource Entity::m_UniversalTemperatureSource protected
Definition at line 132 of file EntityAI.c.
m_ViewIndex
int Entity::m_ViewIndex = 0 protected
view index Item view index is used to setup which camera will be used in item view widget in inventory. With this index you can setup various camera angles for different item states (e.g. fireplace, weapons).
Definition at line 2728 of file EntityAI.c.
m_Weight
float Entity::m_Weight private
Definition at line 125 of file EntityAI.c.
m_WeightDirty
bool Entity::m_WeightDirty = 1 private
Definition at line 105 of file EntityAI.c.
m_WeightEx
float Entity::m_WeightEx private
Definition at line 126 of file EntityAI.c.
The documentation for this class was generated from the following files:
scripts/3_Game/Entities/Camera.c
scripts/3_Game/Entities/EntityAI.c
scripts/3_Game/Entities/EntityLightSource.c
scripts/3_Game/Entities/SoundOnVehicle.c