DayZ: CGame Class Reference
CGame Class Reference
Protected Member Functions
void SetConnectivityStatState (EConnectivityStatType type, EConnectivityStatLevel level)
bool OnConnectivityStatChange (EConnectivityStatType type, EConnectivityStatLevel newLevel, EConnectivityStatLevel oldLevel)
void AddVoiceNotification (VONStopSpeakingEventParams vonStartParams)
void RemoveVoiceNotification (VONStopSpeakingEventParams vonStopParams)
void UpdateLoginQueue (float timeslice)
void OnLoginTimeEvent (int loginTime)
void LoginTimeCountdown ()
void OnRespawnEvent (int time)
void OnPreloadEvent (vector pos)
void StoreLoginDataPrepare ()
void EnterLoginQueue (UIMenuPanel parent)
void EnterLoginTime (UIMenuPanel parent)
void OnMPConnectionLostEvent (int duration)
void LoadProgressUpdate (int progressState, float progress, string title)
override void OnAfterCreate ()
override void OnActivateMessage ()
override void OnDeactivateMessage ()
override bool OnInitialize ()
void InitNotifications ()
string GetDatabaseID ()
void SetDatabaseID (string id)
void CreateTitleScreen ()
void DeleteTitleScreen ()
bool ShouldShowControllerDisconnect ()
void UpdateInputDeviceDisconnectWarning ()
void JoinLaunch ()
void ConnectLaunch ()
void PartyLaunch ()
void MainMenuLaunch ()
void MissionLaunch ()
void SelectUser (int gamepad=-1)
void SetPreviousGamepad (int gamepad)
int GetPreviousGamepad ()
void GamepadCheck ()
void SelectGamepad ()
void TryConnect ()
bool GetLastVisitedServer (out string ip, out int port)
void AddVisitedServer (string ip, int port)
bool IsVisited (string ip, int port)
void RefreshCurrentServerInfo ()
void Connect ()
void DisconnectSessionScript (bool displayJoinError=false)
void DisconnectSessionEx (DisconnectSessionFlags flags)
void ConnectFromServerBrowser (string ip, int port, string password="")
void ConnectFromJoin (string ip, int port)
void ConnectFromCLI ()
bool IsLeftCtrlDown ()
override void OnKeyPress (int key)
override void OnKeyRelease (int key)
override void OnMouseButtonPress (int button)
override void OnMouseButtonRelease (int button)
override void OnDeviceReset ()
float GetDeltaT ()
override void OnUpdate (bool doSim, float timeslice)
override void OnPostUpdate (bool doSim, float timeslice)
override void OnRPC (PlayerIdentity sender, Object target, int rpc_type, ParamsReadContext ctx)
void DelayedMidAirDetonation (float x, float y, float z)
void CheckDialogs ()
void SetConnecting (bool value)
Returns true when connecting to server.
bool IsConnecting ()
bool IsLoading ()
void SetKeyboardHandle (UIScriptedMenu handler)
void LoadingShow ()
void LoadingHide (bool force=false)
override string CreateDefaultPlayer ()
override string CreateRandomPlayer ()
override TStringArray ListAvailableCharacters ()
void ExplosionEffectsEx (Object source, Object directHit, int componentIndex, float energyFactor, float explosionFactor, HitInfo hitInfo)
void ExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
void OnProjectileStopped (ProjectileStoppedInfo info)
void OnProjectileStoppedInTerrain (TerrainCollisionInfo info)
void OnProjectileStoppedInObject (ObjectCollisionInfo info)
void FirearmEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, vector exitPos, vector inSpeed, vector outSpeed, bool isWater, bool deflected, string ammoType)
void CloseCombatEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, bool isWater, string ammoType)
void UpdateVoiceLevel (int level)
void InitCharacterMenuDataInfo (int menudata_count)
void SetPlayerGameName (string name)
string GetPlayerGameName ()
void SetNewCharacter (bool state)
bool IsNewCharacter ()
void SetUserFOV (float pFov)
float GetUserFOV ()
float GetFOVByZoomType (ECameraZoomType type)
void SetHudBrightness (float value)
float GetHUDBrightnessSetting ()
void SetEVValue (float value)
float GetCurrentEVValue ()
float GetPreviousEVValue ()
int GetCurrentDisplayLanguageIdx ()
bool IsWorldWetTempUpdateEnabled ()
bool IsFoodDecayEnabled ()
float GetFoodDecayModifier ()
array< int > GetConnectedInputDeviceList ()
void SetMouseCursorDesiredVisibility (bool visible)
bool GetMouseCursorDesiredVisibility ()
bool CanDisplayMouseCursor ()
extend as needed, only game focus and M&K setting (consoles only!) are checked natively
void RefreshMouseCursorVisibility ()
BillboardSetHandler GetBillboardHandler ()
void CreateGamepadDisconnectMenu ()
void DeleteGamepadDisconnectMenu ()
native void CreateMission (string path)
Create only enforce script mission, used for mission script reloading.
proto native void RestartMission ()
proto native void AbortMission ()
Returns to main menu, leave world empty for using last mission world.
proto native void RespawnPlayer ()
proto native bool CanRespawnPlayer ()
proto native void SetLoginTimerFinished ()
proto native void SetMainMenuWorld (string world)
proto native owned string GetMainMenuWorld ()
proto native void LogoutRequestTime ()
Logout methods.
proto native void LogoutRequestCancel ()
proto native bool IsMultiplayer ()
proto native bool IsClient ()
proto native bool IsServer ()
proto native bool IsDedicatedServer ()
Robust check which is preferred than the above, as it is valid much sooner.
proto native int ServerConfigGetInt (string name)
Server config parsing. Returns 0 if not found.
proto native bool IsDebug ()
void SetDebugMonitorEnabled (int value)
bool IsDebugMonitor ()
proto native void GetPlayerIndentities (out array< PlayerIdentity > identities)
proto native float SurfaceY (float x, float z)
proto native float SurfaceRoadY (float x, float z, RoadSurfaceDetection rsd=RoadSurfaceDetection.LEGACY)
proto native float SurfaceRoadY3D (float x, float y, float z, RoadSurfaceDetection rsd)
proto void SurfaceGetType (float x, float z, out string type)
proto void SurfaceGetType3D (float x, float y, float z, out string type)
proto void SurfaceUnderObject (notnull Object object, out string type, out int liquidType)
proto void SurfaceUnderObjectEx (notnull Object object, out string type, out string impact, out int liquidType)
proto void SurfaceUnderObjectByBone (notnull Object object, int boneType, out string type, out int liquidType)
proto native float SurfaceGetNoiseMultiplier (Object directHit, vector pos, int componentIndex)
proto native vector SurfaceGetNormal (float x, float z)
proto native float SurfaceGetSeaLevel ()
proto native bool SurfaceIsSea (float x, float z)
proto native bool SurfaceIsPond (float x, float z)
proto native float GetWaterDepth (vector posWS)
proto native void UpdatePathgraphRegion (vector regionMin, vector regionMax)
float GetHighestSurfaceYDifference (array< vector > positions)
Returns the largest height difference between the given positions.
vector GetSurfaceOrientation (float x, float z)
Returns tilt of the ground on the given position in degrees, so you can use this value to rotate any item according to terrain.
bool IsSurfaceDigable (string surface)
Checks if the surface is digable.
bool IsSurfaceFertile (string surface)
Checks if the surface is fertile.
void UpdatePathgraphRegionByObject (Object object)
proto native bool IsBoxColliding (vector center, vector orientation, vector edgeLength, array< Object > excludeObjects, array< Object > collidedObjects=NULL)
Finds all objects that are in choosen oriented bounding box (OBB)
proto native bool IsBoxCollidingGeometry (vector center, vector orientation, vector edgeLength, int iPrimaryType, int iSecondaryType, array< Object > excludeObjects, array< Object > collidedObjects=NULL)
Finds all objects with geometry iType that are in choosen oriented bounding box (OBB)
proto native bool IsBoxCollidingGeometryProxy (notnull BoxCollidingParams params, array< Object > excludeObjects, array< ref BoxCollidingResult > collidedObjects=NULL)
proto native Weather GetWeather ()
Returns weather controller object.
proto native void SetEVUser (float value)
Sets custom camera camera EV. range: -50.0..50.0? //TODO.
proto native void OverrideDOF (bool enable, float focusDistance, float focusLength, float focusLengthNear, float blur, float focusDepthOffset)
proto native void AddPPMask (float ndcX, float ndcY, float ndcRadius, float ndcBlur)
proto native void ResetPPMask ()
proto native void OverrideInventoryLights (vector diffuse, vector ambient, vector ground, vector dir)
proto native void NightVissionLightParams (float lightIntensityMul, float noiseIntensity)
proto native void OpenURL (string url)
proto native void InitDamageEffects (Object effect)
Initialization of damage effects.
proto native EntityAI GetEntityByPersitentID (int b1, int b2, int b3, int b4)
bool IsKindOf (string cfg_class_name, string cfg_parent_name)
Returns is class name inherited from parent class name.
bool ObjectIsKindOf (Object object, string cfg_parent_name)
Returns is object inherited from parent class name.
int ConfigFindClassIndex (string config_path, string searched_member)
proto int GetTime ()
returns mission time in milliseconds
ScriptCallQueue GetCallQueue (int call_category)
ScriptInvoker GetUpdateQueue (int call_category)
ScriptInvoker GetPostUpdateQueue (int call_category)
TimerQueue GetTimerQueue (int call_category)
DragQueue GetDragQueue ()
string CreateDefaultPlayer ()
returns class name of first valid survivor (TODO address confusing naming?)
string CreateRandomPlayer ()
returns class name of random survivor (TODO address confusing naming?)
TStringArray ListAvailableCharacters ()
outputs array of all valid survivor class names
bool IsInventoryOpen ()
proto native BiosUserManager GetUserManager ()
proto native ContentDLC GetContentDLCService ()
Return DLC service (service for entitlement keys for unlock content)
bool IsMissionMainMenu ()
Returns true when current mission is Main Menu.
MenuDefaultCharacterData GetMenuDefaultCharacterData (bool fill_data=true)
AnalyticsManagerServer GetAnalyticsServer ()
AnalyticsManagerClient GetAnalyticsClient ()
Static Protected Member Functions
static float GetUserFOVFromConfig ()
static bool CheckAmmoCompability (EntityAI weaponInHand, EntityAI ammo)
static bool IsDigitalCopy ()
Protected Attributes
ref BillboardSetHandler m_BillboardSetHandler
const int MISSION_STATE_MAINMENU = 0
const int MISSION_STATE_GAME = 1
const int MISSION_STATE_FINNISH = 2
DayZGameState m_GameState
DayZLoadState m_LoadState
ref NotificationUI m_Notifications
bool m_FirstConnect = true
ref LoadingScreen m_loading
ref Widget m_IntroMenu
ref Widget m_GamepadDisconnectMenu
int m_PrevBlur
string m_DatabaseID
string m_ConnectAddress
int m_ConnectPort
string m_ConnectPassword
const int MAX_VISITED = 50
ref TStringArray m_Visited
const float ARROW_PIERCE_DEPTH = 0.05
Private Member Functions
void DayZGame ()
void ~DayZGame ()
void DeferredInit ()
void GlobalsInit ()
void RegisterProfilesOptions ()
void ResetProfileOptions ()
void SetMissionPath (string path)
Called from C++.
string GetMissionPath ()
string GetMissionFolderPath ()
override ScriptCallQueue GetCallQueue (int call_category)
override ScriptInvoker GetUpdateQueue (int call_category)
override ScriptInvoker GetPostUpdateQueue (int call_category)
override TimerQueue GetTimerQueue (int call_category)
override DragQueue GetDragQueue ()
void OnGameplayDataHandlerLoad ()
int GetMissionState ()
void SetMissionState (int state)
bool GetProfileOption (EDayZProfilesOptions option)
bool GetProfileOptionBool (EDayZProfilesOptions option)
int GetProfileOptionInt (EDayZProfilesOptions option)
float GetProfileOptionFloat (EDayZProfilesOptions option)
bool GetProfileOptionDefault (EDayZProfilesOptions option)
bool GetProfileOptionDefaultBool (EDayZProfilesOptions option)
int GetProfileOptionDefaultInt (EDayZProfilesOptions option)
float GetProfileOptionDefaultFloat (EDayZProfilesOptions option)
void SetProfileOption (EDayZProfilesOptions option, bool value)
void SetProfileOptionBool (EDayZProfilesOptions option, bool value)
void SetProfileOptionInt (EDayZProfilesOptions option, int value)
void SetProfileOptionFloat (EDayZProfilesOptions option, float value)
map< EDayZProfilesOptions, ref DayZProfilesOption > GetProfileOptionMap ()
bool IsStressTest ()
bool IsAimLogEnabled ()
void SetGameState (DayZGameState state)
DayZGameState GetGameState ()
void SetLoadState (DayZLoadState state)
DayZLoadState GetLoadState ()
Backlit GetBacklit ()
override bool IsInventoryOpen ()
void EarlyAccessDialog (UIScriptedMenu parent)
override UIScriptedMenu CreateScriptedMenu (int id)
create custom main menu part (submenu)
void ReloadMission ()
void CancelLoginQueue ()
void CancelLoginTimeCountdown ()
void ClearConnectivityStates ()
override void OnEvent (EventType eventTypeId, Param params)
void CGame ()
void ~CGame ()
proto native WorkspaceWidget GetWorkspace ()
proto native WorkspaceWidget GetLoadingWorkspace ()
void OnEvent (EventType eventTypeId, Param params)
Called when some system event occur.
void OnProcessLifetimeChanged (int plmtype)
void OnLicenseChanged ()
void OnAfterCreate ()
Called after creating of CGame instance.
void OnActivateMessage ()
Called when recieving focus (windows)
void OnDeactivateMessage ()
Called when loosing focus (windows)
bool OnInitialize ()
Called once before game update loop starts, ret value indicates if init was done in scripts, otherwise it is done in the engine.
void OnDeviceReset ()
Called when inputs is not possible (Steam overlay active or something), all internal script variables should be reset here!
void OnUpdate (bool doSim, float timeslice)
Called on World update.
void OnPostUpdate (bool doSim, float timeslice)
Called on World update after simulation of entities.
void OnKeyPress (int key)
Called when key is pressed.
void OnKeyRelease (int key)
Called when key is released.
void OnMouseButtonPress (int button)
Called when mouse button is pressed.
void OnMouseButtonRelease (int button)
Called when mouse button is released.
UIScriptedMenu CreateScriptedMenu (int id)
create custom main menu part (submenu)
UIScriptedWindow CreateScriptedWindow (int id)
create custom window part
void OnRPC (PlayerIdentity sender, Object target, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
proto native void RequestExit (int code)
Sets exit code and quits in the right moment.
proto native void RequestRestart (int code)
Sets exit code and restart in the right moment.
proto native bool IsAppActive ()
Returns if the application is focused on PC, returns true always on console.
proto bool GetHostAddress (out string address, out int port)
Gets the server address. (from client)
proto owned string GetHostName ()
Gets the server name. (from client)
proto GetServersResultRow GetHostData ()
Gets the server data. (from client)
proto native int Connect (UIScriptedMenu parent, string IpAddress, int port, string password)
Connects to IsServer.
proto native int ConnectLastSession (UIScriptedMenu parent, int selectedCharacter=-1)
Connects to last success network session.
proto native void DisconnectSession ()
Disconnects from current multiplayer session.
proto native void DisconnectSessionForce ()
Forces disconnect from current multiplayer session even if not yet in the game.
proto native void GetProfileStringList (string name, out TStringArray values)
Gets array of strings from profile variable.
proto bool GetProfileString (string name, out string value)
Gets string from profile variable.
proto native void SetProfileStringList (string name, TStringArray values)
Sets array of strings to profile variable.
proto native void SetProfileString (string name, string value)
Sets string to profile variable.
proto native void SaveProfile ()
Saves profile on disk.
proto void GetPlayerName (out string name)
Gets current player name.
proto void GetPlayerNameShort (int maxLength, out string name)
Gets current player name. If length of player name is grater than maxLength, then it is omitted and append ellipsis.
proto native void SetPlayerName (string name)
Sets current player name.
proto native Entity CreatePlayer (PlayerIdentity identity, string name, vector pos, float radius, string spec)
Assign player entity to client (in multiplayer)
proto native void SelectPlayer (PlayerIdentity identity, Object player)
Selects player's controlled object.
proto void GetPlayerNetworkIDByIdentityID (int playerIdentityID, out int networkIdLowBits, out int networkIdHightBits)
returns player's network id from identity id in out parameters
proto native Object GetObjectByNetworkId (int networkIdLowBits, int networkIdHighBits)
Returns entity identified by network id.
proto native bool RegisterNetworkStaticObject (Object object)
Static objects cannot be replicated by default (there are too many objects on the map). Use this method when you want to replicate some scripted variables. Cannot be called in object's constructor, because networking is not initialized yet.
proto native void SelectSpectator (PlayerIdentity identity, string spectatorObjType, vector position)
Creates spectator object (mostly cameras)
proto native void UpdateSpectatorPosition (vector position)
Updates spectator position on server = position of network bubble.
proto native void SendLogoutTime (Object player, int time)
Inform client about logout time (creates logout screen on specified client)
proto native void DisconnectPlayer (PlayerIdentity identity, string uid="")
Destroy player info and disconnect.
proto native void AddToReconnectCache (PlayerIdentity identity)
Add player to reconnect cache to be able to rejoin character still existing in the world.
proto native void RemoveFromReconnectCache (string uid)
Remove player from reconnect cache.
proto native void ClearReconnectCache ()
Remove all player from reconnect cache.
proto native void StorageVersion (int iVersion)
Set actual storage version - for next save.
proto native int LoadVersion ()
Returns actual storage version - loading.
proto native int SaveVersion ()
Returns actual storage version - saving.
proto native float GetDayTime ()
Returns current daytime on server.
proto bool ConfigGetText (string path, out string value)
Get string value from config on path.
proto bool ConfigGetTextRaw (string path, out string value)
Get raw string value from config on path.
string ConfigGetTextOut (string path)
Get string value from config on path.
bool FormatRawConfigStringKeys (inout string value)
Changes localization key format to script-friendly format.
string GetModelName (string class_name)
Get name of the p3d file of the given class name.
proto native float ConfigGetFloat (string path)
Get float value from config on path.
proto native vector ConfigGetVector (string path)
Get vector value from config on path.
proto native int ConfigGetInt (string path)
Get int value from config on path.
proto native int ConfigGetType (string path)
Returns type of config value.
proto native void ConfigGetTextArray (string path, out TStringArray values)
Get array of strings from config on path.
proto native void ConfigGetTextArrayRaw (string path, out TStringArray values)
Get array of raw strings from config on path.
proto native void ConfigGetFloatArray (string path, out TFloatArray values)
Get array of floats from config on path.
proto native void ConfigGetIntArray (string path, out TIntArray values)
Get array of integers from config on path.
proto bool ConfigGetChildName (string path, int index, out string name)
Get name of subclass in config class on path.
proto bool ConfigGetBaseName (string path, out string base_name)
Get name of base class of config class on path.
proto native int ConfigGetChildrenCount (string path)
Get count of subclasses in config class on path.
proto native bool ConfigIsExisting (string path)
proto native void ConfigGetFullPath (string path, out TStringArray full_path)
proto native void ConfigGetObjectFullPath (Object obj, out TStringArray full_path)
proto native void GetModInfos (notnull out array< ref ModInfo > modArray)
proto native bool GetModToBeReported ()
string ConfigPathToString (TStringArray array_path)
Converts array of strings into single string.
proto bool CommandlineGetParam (string name, out string value)
Get command line parameter value.
proto native void CopyToClipboard (string text)
proto void CopyFromClipboard (out string text)
proto native void BeginOptionsVideo ()
proto native void EndOptionsVideo ()
proto native void AdminLog (string text)
proto native bool PreloadObject (string type, float distance)
Preload objects with certain type in certain distance from camera.
proto native Object CreateStaticObjectUsingP3D (string p3dFilename, vector position, vector orientation, float scale=1.0, bool createLocal=false)
proto native Object CreateObject (string type, vector pos, bool create_local=false, bool init_ai=false, bool create_physics=true)
Creates object of certain type.
proto native SoundOnVehicle CreateSoundOnObject (Object source, string sound_name, float distance, bool looped, bool create_local=false)
proto native SoundWaveOnVehicle CreateSoundWaveOnObject (Object source, SoundObject soundObject, AbstractWave soundWave)
proto native Object CreateObjectEx (string type, vector pos, int iFlags, int iRotation=RF_DEFAULT)
Creates object of certain type.
proto native void ObjectDelete (Object obj)
proto native void ObjectDeleteOnClient (Object obj)
proto native void RemoteObjectDelete (Object obj)
proto native void RemoteObjectTreeDelete (Object obj)
RemoteObjectDelete - deletes only remote object (unregisters from network). do not use if not sure what you do.
proto native void RemoteObjectCreate (Object obj)
RemoteObjectDelete - deletes only remote object tree (unregisters from network). do not use if not sure what you do.
proto native void RemoteObjectTreeCreate (Object obj)
RemoteObjectCreate - postponed registration of network object (and creation of remote object). do not use if not sure what you do.
proto native int ObjectRelease (Object obj)
RemoteObjectTreeCreate - postponed registration of network object tree (and creation of remote objects). do not use if not sure what you do.
proto void ObjectGetType (Object obj, out string type)
proto void ObjectGetDisplayName (Object obj, out string name)
proto native vector ObjectGetSelectionPosition (Object obj, string name)
proto native vector ObjectGetSelectionPositionLS (Object obj, string name)
proto native vector ObjectGetSelectionPositionMS (Object obj, string name)
proto native vector ObjectGetSelectionPositionWS (Object obj, string name)
proto native vector ObjectModelToWorld (Object obj, vector modelPos)
proto native vector ObjectWorldToModel (Object obj, vector worldPos)
proto native bool IsObjectAccesible (EntityAI item, Man player)
returns true if player can access item's cargo/attachments (check only distance)
proto native Input GetInput ()
proto native vector GetCurrentCameraPosition ()
proto native vector GetCurrentCameraDirection ()
proto native AbstractSoundScene GetSoundScene ()
proto native NoiseSystem GetNoiseSystem ()
proto native bool AddInventoryJuncture (Man player, notnull EntityAI item, InventoryLocation dst, bool test_dst_occupancy, int timeout_ms)
bool AddInventoryJunctureEx (Man player, notnull EntityAI item, InventoryLocation dst, bool test_dst_occupancy, int timeout_ms)
proto native bool HasInventoryJunctureItem (notnull EntityAI item)
proto native bool HasInventoryJunctureDestination (Man player, notnull InventoryLocation dst)
proto native bool AddActionJuncture (Man player, notnull EntityAI item, int timeout_ms)
proto native bool ExtendActionJuncture (Man player, notnull EntityAI item, int timeout_ms)
proto native bool ClearJuncture (Man player, notnull EntityAI item)
bool ClearJunctureEx (Man player, notnull EntityAI item)
proto native bool ExecuteEnforceScript (string expression, string mainFnName)
Delevoper only: Executes Enforce Script expression, if there is an error, is printed into the script console.
proto native void DumpInstances (bool csvFormatting)
Delevoper only: Dump all script allocations.
proto native bool ScriptTest ()
proto native void GetDiagModeNames (out TStringArray diag_names)
Get list of all debug modes.
proto native void SetDiagModeEnable (int diag_mode, bool enabled)
Set specific debug mode.
proto native bool GetDiagModeEnable (int diag_mode)
Gets state of specific debug mode.
proto native void GetDiagDrawModeNames (out TStringArray diag_names)
Get list of all debug draw modes.
proto native void SetDiagDrawMode (int diag_draw_mode)
Set debug draw mode.
proto native int GetDiagDrawMode ()
Gets current debug draw mode.
proto native bool IsPhysicsExtrapolationEnabled ()
If physics extrapolation is enabled, always true on retail release builds.
proto native float GetFps ()
Returns average FPS of last 16 frames.
proto native float GetTickTime ()
Returns current time from start of the game.
proto void GetInventoryItemSize (InventoryItem item, out int width, out int height)
proto native void GetObjectsAtPosition (vector pos, float radius, out array< Object > objects, out array< CargoBase > proxyCargos)
Returns list of all objects in circle "radius" around position "pos".
proto native void GetObjectsAtPosition3D (vector pos, float radius, out array< Object > objects, out array< CargoBase > proxyCargos)
Returns list of all objects in sphere "radius" around position "pos".
proto native World GetWorld ()
proto void GetWorldName (out string world_name)
string GetWorldName ()
proto native bool VerifyWorldOwnership (string sWorldName)
proto native bool GoBuyWorldDLC (string sWorldName)
proto void FormatString (string format, string params[], out string output)
proto void GetVersion (out string version)
proto native UIManager GetUIManager ()
proto native DayZPlayer GetPlayer ()
proto native void GetPlayers (out array< Man > players)
DayZPlayer GetPlayerByIndex (int index=0)
proto native void StoreLoginData (ParamsWriteContext ctx)
Stores login userdata as parameters which are sent to server.
proto native vector GetPointerDirection ()
Returns the direction where the mouse points, from the camera view.
proto native vector GetWorldDirectionFromScreen (vector world_pos)
Transforms position in world to position in screen in pixels as x, y component of vector, z parameter represents distance between camera and world_pos.
proto native vector GetScreenPos (vector world_pos)
Transforms position in world to position in screen in pixels as x, y component of vector, z parameter represents distance between camera and world_pos.
proto native vector GetScreenPosRelative (vector world_pos)
Transforms position in world to position in screen in percentage (0.0 - 1.0) as x, y component of vector, z parameter represents distance between camera and world_pos.
proto native MenuData GetMenuData ()
Return singleton of MenuData class - at main menu contains characters played with current profile.
proto native void RPC (Object target, int rpcType, notnull array< ref Param > params, bool guaranteed, PlayerIdentity recipient=null)
Initiate remote procedure call. When called on client, RPC is evaluated on server; When called on server, RPC is executed on all clients.
void RPCSingleParam (Object target, int rpc_type, Param param, bool guaranteed, PlayerIdentity recipient=null)
see CGame.RPC
proto native void RPCSelf (Object target, int rpcType, notnull array< ref Param > params)
Not actually an RPC, as it will send it only to yourself.
void RPCSelfSingleParam (Object target, int rpcType, Param param)
proto native void ProfilerStart (string name)
Use for profiling code from start to stop, they must match have same name, look wiki pages for more info: https://confluence.bistudio.com/display/EN/Profiler.
proto native void ProfilerStop (string name)
Use for profiling code from start to stop, they must match have same name, look wiki pages for more info: https://confluence.bistudio.com/display/EN/Profiler.
proto native void Chat (string text, string colorClass)
Prints text into game chat.
proto native void ChatMP (Man recipient, string text, string colorClass)
proto native void ChatPlayer (string text)
proto native void MutePlayer (string muteUID, string playerUID, bool mute)
Mutes voice of source player to target player.
proto native void MuteAllPlayers (string listenerId, bool mute)
Mute all players for listenerId.
proto native void EnableVoN (Object player, bool enable)
Enable/disable VoN for target player.
proto native void SetVoiceEffect (Object player, int effect, bool enable)
Enable/disable VoN effect (only on server)
proto native void SetVoiceLevel (int level)
Set voice level of VoN (only on client) (VoiceLevelWhisper = 0, VoiceLevelNormal = 1, VoiceLevelShout = 2)
proto native int GetVoiceLevel (Object player=null)
Get voice level of VoN (on both client and server) (VoiceLevelWhisper = 0, VoiceLevelNormal = 1, VoiceLevelShout = 2)
proto native void EnableMicCapture (bool enable)
Enable microphone to locally capture audio from user. Audio heard does NOT automatically get transmitted over network.
proto native bool IsMicCapturing ()
Returns whether mic is currently capturing audio from user.
proto native bool IsInPartyChat ()
Returns whether user is currently in a voice party (currently only supported on xbox)
proto native Mission GetMission ()
proto native void SetMission (Mission mission)
proto native void StartRandomCutscene (string world)
Starts intro.
proto native void PlayMission (string path)
Starts mission (equivalent for SQF playMission). You MUST use double slash \.
Static Private Member Functions
static bool ReportModded ()
Private Attributes
const int STATS_COUNT = EConnectivityStatType.COUNT
EConnectivityStatLevel m_ConnectivityStatsStates [STATS_COUNT]
int m_MissionState
ref LoginTimeBase m_LoginTimeScreen
ref LoginQueueBase m_LoginQueue
int m_LoginTime
ref ConnectionLost m_connectionLost
ref TimerQueue m_timerQueue [CALL_CATEGORY_COUNT]
ref ScriptCallQueue m_callQueue [CALL_CATEGORY_COUNT]
ref ScriptInvoker m_updateQueue [CALL_CATEGORY_COUNT]
ref ScriptInvoker m_postUpdateQueue [CALL_CATEGORY_COUNT]
ref DragQueue m_dragQueue
ref DayZProfilesOptions m_DayZProfileOptions
bool m_early_access_dialog_accepted
UIScriptedMenu m_keyboard_handler
ScriptModule m_mission_module
string m_MissionPath
string m_MissionFolderPath
bool m_IsCtrlHolding
bool m_IsWinHolding
bool m_IsLeftAltHolding
bool m_IsRightAltHolding
bool m_IsWorldWetTempUpdateEnabled = true
bool m_IsFoodDecayEnabled = true
float m_FoodDecayModifier
bool m_IsStressTest
bool m_AimLoggingEnabled
int m_OriginalCharactersCount
string m_PlayerName
bool m_IsNewCharacter
bool m_IsConnecting
bool m_ConnectFromJoin
bool m_ShouldShowControllerDisconnect
bool m_CursorDesiredVisibilityScript = true
int m_PreviousGamepad
float m_UserFOV
float m_DeltaTime
float m_volume_sound
float m_volume_speechEX
float m_volume_music
float m_volume_VOIP
float m_volume_radio
float m_PreviousEVValue
float m_EVValue = 0
ref Backlit m_Backlit
ref array< string > m_CharClassNames = new array<string>()
ref array< int > m_ConnectedInputDeviceList
ref EffectSound m_CrashSound
ref EffectSound m_ArtySound
const int MIN_ARTY_SOUND_RANGE = 300
int m_DebugMonitorEnabled
ScriptModule GameScript
ref array< ref Param > m_ParamCache
ref AnalyticsManagerServer m_AnalyticsManagerServer
ref AnalyticsManagerClient m_AnalyticsManagerClient
ref MenuDefaultCharacterData m_CharacterData
Static Private Attributes
static bool m_ReportModded
static ref AmmoCamParams m_AmmoShakeParams = new AmmoCamParams()
static ref ScriptInvoker Event_OnRPC = new ScriptInvoker()
static ref NoiseParams m_NoiseParams = new NoiseParams()
Detailed Description
Definition at line 849 of file DayZGame.c.
Constructor & Destructor Documentation
~DayZGame()
void CGame::~DayZGame () inline private
Definition at line 1027 of file DayZGame.c.
  {
    PPEManagerStatic.DestroyManagerStatic();
    BleedChanceData.Cleanup();
    NotificationSystem.CleanupInstance();
    g_Game = null;
    SetDispatcher(null);
    Print("~DayZGame()");
  }
References BleedChanceData::Cleanup(), NotificationSystem::CleanupInstance(), PPEManagerStatic::DestroyManagerStatic(), g_Game, Print(), and SetDispatcher().
CGame()
void CGame::CGame () inline private
Definition at line 33 of file Game.c.
  {
    Math.Randomize(-1);
    LogManager.Init();
    m_ParamCache = new array<ref Param>;
    m_ParamCache.Insert(null);
    //analytics
    m_AnalyticsManagerServer = new AnalyticsManagerServer;
    m_AnalyticsManagerClient = new AnalyticsManagerClient;
    //m_CharacterData = new MenuCharacrerData;
    // actual script version - increase by one when you make changes
    StorageVersion(GAME_STORAGE_VERSION);
#ifdef DIAG_DEVELOPER
    m_EnergyManagerArray = new array<ComponentEnergyManager>;
#endif
    if (!IsDedicatedServer())
    {
      SEffectManager.Init();
      AmmoEffects.Init();
      VONManager.Init();
    }
  }
References GAME_STORAGE_VERSION, AmmoEffects::Init(), SEffectManager::Init(), LogManager::Init(), VONManager::Init(), IsDedicatedServer(), m_AnalyticsManagerClient, m_AnalyticsManagerServer, m_ParamCache, Math::Randomize(), and StorageVersion().
~CGame()
void CGame::~CGame () inline private
Definition at line 62 of file Game.c.
  {
    // Clean these up even if it is dedicated server, just to be safe
    SEffectManager.Cleanup();
    AmmoEffects.Cleanup();
    VONManager.CleanupInstance();
    // Is initialized in StartupEvent
    ParticleManager.CleanupInstance();
  }
References AmmoEffects::Cleanup(), SEffectManager::Cleanup(), VONManager::CleanupInstance(), and ParticleManager().
Member Function Documentation
AbortMission()
proto native void CGame::AbortMission () protected
Returns to main menu, leave world empty for using last mission world.
Referenced by OnEvent().
AddActionJuncture()
proto native bool CGame::AddActionJuncture (Man player, notnull EntityAI item, int timeout_ms) private
AddInventoryJuncture()
proto native bool CGame::AddInventoryJuncture (Man player, notnull EntityAI item, InventoryLocation dst, bool test_dst_occupancy, int timeout_ms) private
Referenced by AddInventoryJunctureEx().
AddInventoryJunctureEx()
bool CGame::AddInventoryJunctureEx (Man player, notnull EntityAI item, InventoryLocation dst, bool test_dst_occupancy, int timeout_ms) inline private
Definition at line 717 of file Game.c.
  {
    bool result = AddInventoryJuncture(player, item, dst, test_dst_occupancy, timeout_ms/*10000000*/);
#ifdef DEVELOPER
    if (LogManager.IsInventoryReservationLogEnable())
      Debug.InventoryReservationLog("STS = " + player.GetSimulationTimeStamp() + " result: " + result + " item:" + item + " dst: " + InventoryLocation.DumpToStringNullSafe(dst), "n/a", "n/a", "AddInventoryJuncture", player.ToString());
#endif
    //Print("Juncture - STS = " + player.GetSimulationTimeStamp() + " item:" + item + " dst: " + InventoryLocation.DumpToStringNullSafe(dst));
    return result;
  }
References AddInventoryJuncture(), InventoryLocation::DumpToStringNullSafe(), Debug::InventoryReservationLog(), and LogManager::IsInventoryReservationLogEnable().
AddPPMask()
proto native void CGame::AddPPMask (float ndcX, float ndcY, float ndcRadius, float ndcBlur) protected
AddToReconnectCache()
proto native void CGame::AddToReconnectCache (PlayerIdentity identity) private
Add player to reconnect cache to be able to rejoin character still existing in the world.
Note
Works only on server and no database requests are sent
Parameters
identity of player
AddVisitedServer()
void CGame::AddVisitedServer (string ip, int port) inline protected
Definition at line 2410 of file DayZGame.c.
  {
    string uid = ip + ":" + port;
    if (m_Visited)
    {
      int pos = m_Visited.Find(uid);
      if (pos < 0)
      {
        if (m_Visited.Count() == MAX_VISITED)
          m_Visited.Remove(0);
        m_Visited.Insert(uid);
      }
      else
      {
        // if item is not saved as last server, move it
        if (pos != (m_Visited.Count() - 1))
        {
          m_Visited.Remove(pos);
          m_Visited.Insert(uid);
        }
      }
      SetProfileStringList("SB_Visited", m_Visited);
      SaveProfile();
    }
  }
References SaveProfile(), and SetProfileStringList().
Referenced by OnEvent().
AddVoiceNotification()
void CGame::AddVoiceNotification (VONStopSpeakingEventParams vonStartParams) inline protected
Definition at line 1684 of file DayZGame.c.
  {
    m_Notifications.AddVoiceNotification(vonStartParams.param2, vonStartParams.param1);
  }
AdminLog()
proto native void CGame::AdminLog (string text) private
BeginOptionsVideo()
proto native void CGame::BeginOptionsVideo () private
CancelLoginQueue()
void CGame::CancelLoginQueue () inline private
Definition at line 1321 of file DayZGame.c.
  {
    if (m_LoginQueue)
    {
      if (m_LoginQueue.IsStatic())
      {
        m_LoginQueue.Hide();
        delete m_LoginQueue;
      }
      else
        m_LoginQueue.Close();
    }
  }
References m_LoginQueue.
Referenced by OnEvent(), and OnLoginTimeEvent().
CancelLoginTimeCountdown()
void CGame::CancelLoginTimeCountdown () inline private
Definition at line 1335 of file DayZGame.c.
  {
    GetCallQueue(CALL_CATEGORY_SYSTEM).Remove(this.LoginTimeCountdown);
    if (m_LoginTimeScreen)
    {
      if (m_LoginTimeScreen.IsStatic())
      {
        m_LoginTimeScreen.Hide();
        delete m_LoginTimeScreen;
      }
      else
        m_LoginTimeScreen.Close();
    }
  }
References CALL_CATEGORY_SYSTEM, GetCallQueue(), and m_LoginTimeScreen.
Referenced by LoginTimeCountdown(), OnEvent(), and OnPreloadEvent().
CanDisplayMouseCursor()
bool CGame::CanDisplayMouseCursor () inline protected
extend as needed, only game focus and M&K setting (consoles only!) are checked natively
Only checking on console because while loading on PC, the mouse might not be detected
Platform defaults
Definition at line 3474 of file DayZGame.c.
  {
#ifdef PLATFORM_CONSOLE
    if (GetInput())
      return GetInput().IsMouseConnected();
#endif
#ifdef PLATFORM_CONSOLE
    return false;
#else
    return true;
#endif
  }
References GetInput().
Referenced by RefreshMouseCursorVisibility().
CanRespawnPlayer()
proto native bool CGame::CanRespawnPlayer () protected
Chat()
proto native void CGame::Chat (string text, string colorClass) private
Prints text into game chat.
Parameters
text to print
colorClass ??
usage :
GetGame().Chat("Item splitted", "colorAction");
ChatMP()
proto native void CGame::ChatMP (Man recipient, string text, string colorClass) private
ChatPlayer()
proto native void CGame::ChatPlayer (string text) private
CheckAmmoCompability()
static bool CGame::CheckAmmoCompability (EntityAI weaponInHand, EntityAI ammo) inline static protected
Definition at line 3388 of file DayZGame.c.
  {
    TStringArray ammo_names = new TStringArray; // Array of ammo types (their name) that can be used with weapon in hand
    string cfg_path = "CfgWeapons " + weaponInHand.GetType() + " chamberableFrom"; // Create config path
    GetGame().ConfigGetTextArray(cfg_path, ammo_names); // Get ammo types
    foreach (string ammo_name : ammo_names) // for every ammo in ammo string compare passed ammo
    {
      if (ammo.GetType() == ammo_name)
        return true;
    }
    // if no ammo from the array matches with ammo passed, return false
    return false;
  }
References GetGame().
CheckDialogs()
void CGame::CheckDialogs () inline protected
Definition at line 3013 of file DayZGame.c.
  {
#ifndef NO_GUI
    Mission mission = GetMission();
    if (mission && !m_loading.IsLoading() && GetUIManager().IsDialogQueued())
    {
      mission.Pause();
      GetUIManager().ShowQueuedDialog();
    }
#endif
  }
References GetMission(), GetUIManager(), mission, and Mission::Pause().
ClearConnectivityStates()
void CGame::ClearConnectivityStates () inline private
Definition at line 1351 of file DayZGame.c.
  {
    for (int i = 0; i < STATS_COUNT; i++)
      m_ConnectivityStatsStates[i] = 0;
  }
References STATS_COUNT.
Referenced by OnEvent().
ClearJuncture()
proto native bool CGame::ClearJuncture (Man player, notnull EntityAI item) private
Referenced by ClearJunctureEx().
ClearJunctureEx()
bool CGame::ClearJunctureEx (Man player, notnull EntityAI item) inline private
Definition at line 736 of file Game.c.
  {
#ifdef DEVELOPER
    if (LogManager.IsInventoryReservationLogEnable())
      Debug.InventoryReservationLog("STS = " + player.GetSimulationTimeStamp() + " item:" + item, "n/a", "n/a", "ClearJuncture", player.ToString());
#endif
    return ClearJuncture(player, item);
  }
References ClearJuncture(), Debug::InventoryReservationLog(), and LogManager::IsInventoryReservationLogEnable().
ClearReconnectCache()
proto native void CGame::ClearReconnectCache () private
Remove all player from reconnect cache.
Note
Works only on server
CloseCombatEffects()
void CGame::CloseCombatEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, bool isWater, string ammoType) inline protected
Definition at line 3271 of file DayZGame.c.
  {
#ifndef SERVER
    ImpactEffectsData impactEffectsData = new ImpactEffectsData();
    impactEffectsData.m_DirectHit = directHit;
    impactEffectsData.m_ComponentIndex = componentIndex;
    impactEffectsData.m_Surface = surface;
    impactEffectsData.m_Position = pos;
    impactEffectsData.m_ImpactType = ImpactTypes.MELEE;
    impactEffectsData.m_SurfaceNormal = Vector(Math.RandomFloat(-1, 1), Math.RandomFloat(-1, 1), Math.RandomFloat(-1, 1));
    impactEffectsData.m_ExitPosition = "0 0 0";
    impactEffectsData.m_InSpeed = "0 0 0";
    impactEffectsData.m_OutSpeed = "0 0 0";
    impactEffectsData.m_IsDeflected = false;
    impactEffectsData.m_AmmoType = ammoType;
    impactEffectsData.m_IsWater = isWater;
    if (directHit)
      directHit.OnReceivedHit(impactEffectsData);
    ImpactMaterials.EvaluateImpactEffectEx(impactEffectsData);
#endif
    // add hit noise
    if (IsServer())
    {
      m_NoiseParams.LoadFromPath("cfgAmmo " + ammoType + " NoiseHit");
      float surfaceCoef = SurfaceGetNoiseMultiplier(directHit, pos, componentIndex);
      GetNoiseSystem().AddNoisePos(EntityAI.Cast(source), pos, m_NoiseParams, surfaceCoef);
    }
  }
References ImpactMaterials::EvaluateImpactEffectEx(), GetNoiseSystem(), IsServer(), m_NoiseParams, Math::RandomFloat(), SurfaceGetNoiseMultiplier(), and Vector().
CommandlineGetParam()
proto bool CGame::CommandlineGetParam (string name, out string value) private
Get command line parameter value.
Parameters
name of parameter
value output
Returns
true when parameter exists, false otherwise
usage :
// you run e.g.: DayZInt.exe -scriptDebug=true
string value;
if (GetGame().CommandlineGetParam("scriptDebug", value) && value == "true")
{
Print("Script debugging on!");
}
Referenced by DayZGame().
ConfigFindClassIndex()
int CGame::ConfigFindClassIndex (string config_path, string searched_member) inline protected
Searches given config path (config_path) for the given member (searched_member) and returns its index. \nReturns -1 if not found.
usage:
int skinning_class_index = g_Game.ConfigFindClassIndex(cfgPath_animal, "Skinning");
Definition at line 1307 of file Game.c.
  {
    int class_count = ConfigGetChildrenCount(config_path);
    for (int index = 0; index < class_count; index++)
    {
      string found_class = "";
      ConfigGetChildName(config_path, index, found_class);
      if (found_class == searched_member)
        return index;
    }
    return -1;
  }
References ConfigGetChildName(), and ConfigGetChildrenCount().
ConfigGetBaseName()
proto bool CGame::ConfigGetBaseName (string path, out string base_name) private
Get name of base class of config class on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
name output
Returns
true on success, false if path or base is not exists
ConfigGetChildName()
proto bool CGame::ConfigGetChildName (string path, int index, out string name) private
Get name of subclass in config class on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
index of subclass in class
name output
Returns
true on success, false if path or child is not found
Referenced by ConfigFindClassIndex(), and DayZGame().
ConfigGetChildrenCount()
proto native int CGame::ConfigGetChildrenCount (string path) private
Get count of subclasses in config class on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
index of parameter in class
name output
Returns
true on success, false if path or child is not found
Referenced by ConfigFindClassIndex(), and DayZGame().
ConfigGetFloat()
proto native float CGame::ConfigGetFloat (string path) private
Get float value from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
Returns
value
Referenced by FirearmEffects().
ConfigGetFloatArray()
proto native void CGame::ConfigGetFloatArray (string path, out TFloatArray values) private
Get array of floats from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
value output
ConfigGetFullPath()
proto native void CGame::ConfigGetFullPath (string path, out TStringArray full_path) private
Referenced by IsKindOf().
ConfigGetInt()
proto native int CGame::ConfigGetInt (string path) private
Get int value from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
Returns
value
Referenced by DayZGame(), IsSurfaceDigable(), and IsSurfaceFertile().
ConfigGetIntArray()
proto native void CGame::ConfigGetIntArray (string path, out TIntArray values) private
Get array of integers from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
value output
ConfigGetObjectFullPath()
proto native void CGame::ConfigGetObjectFullPath (Object obj, out TStringArray full_path) private
Referenced by ObjectIsKindOf().
ConfigGetText()
proto bool CGame::ConfigGetText (string path, out string value) private
Get string value from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
value output
Returns
true on success
Referenced by ConfigGetTextOut(), and GetModelName().
ConfigGetTextArray()
proto native void CGame::ConfigGetTextArray (string path, out TStringArray values) private
Get array of strings from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
value output
usage :
TStringArray characterAnimations = new TStringArray;
GetGame().ConfigGetTextArray("CfgMovesMaleSdr2 States menu_idleUnarmed0 variantsPlayer", characterAnimations);
ConfigGetTextArrayRaw()
proto native void CGame::ConfigGetTextArrayRaw (string path, out TStringArray values) private
Get array of raw strings from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
value output in raw format (localization keys '$STR_' are not translated)
usage :
TStringArray characterAnimations = new TStringArray;
GetGame().ConfigGetTextArrayRaw("CfgMovesMaleSdr2 States menu_idleUnarmed0 variantsPlayer", characterAnimations);
Note
use 'FormatRawConfigStringKeys' method to change localization keys to script-friendly
ConfigGetTextOut()
string CGame::ConfigGetTextOut (string path) inline private
Get string value from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
Returns
value output string
Definition at line 445 of file Game.c.
  {
    string ret_s;
    ConfigGetText(path, ret_s);
    return ret_s;
  }
References ConfigGetText(), and path.
ConfigGetTextRaw()
proto bool CGame::ConfigGetTextRaw (string path, out string value) private
Get raw string value from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
value output in raw format (localization keys '$STR_' are not translated)
Returns
true on success
Note
use 'FormatRawConfigStringKeys' method to change localization keys to script-friendly
ConfigGetType()
proto native int CGame::ConfigGetType (string path) private
Returns type of config value.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
Returns
one of constants CT_INT, CT_FLOAT, CT_STRING, CT_ARRAY, CT_CLASS, CT_OTHER
ConfigGetVector()
proto native vector CGame::ConfigGetVector (string path) private
Get vector value from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
Returns
value
ConfigIsExisting()
proto native bool CGame::ConfigIsExisting (string path) private
ConfigPathToString()
string CGame::ConfigPathToString (TStringArray array_path) inline private
Converts array of strings into single string.
Parameters
Array of strings like {"All", "AllVehicles", "Land"}
Returns
Converts given array into something lile "All AllVehicles Land".
???
Definition at line 608 of file Game.c.
  {
    string return_path = "";
    int count = array_path.Count();
    for (int i = 0; i < count; i++)
    {
      return_path += array_path.Get(i);
      if (i < count - 1)
        return_path += " ";
    }
    return return_path;
  }
Connect() [1/2]
void CGame::Connect () inline protected
Definition at line 2456 of file DayZGame.c.
  {
    SetConnecting(true);
    DeleteTitleScreen();
    string addr;
    int port;
    if (GetHostAddress(addr, port))
    {
      if (m_ConnectAddress == addr && m_ConnectPort == port)
        return;
    }
    if (Connect(GetUIManager().GetMenu(), m_ConnectAddress, m_ConnectPort, m_ConnectPassword) != 0)
      DisconnectSessionScript(true);
  }
References Connect(), DeleteTitleScreen(), DisconnectSessionScript(), GetHostAddress(), GetUIManager(), and SetConnecting().
Referenced by Connect(), ConnectFromCLI(), ConnectFromJoin(), and TryConnect().
Connect() [2/2]
proto native int CGame::Connect (UIScriptedMenu parent, string IpAddress, int port, string password) private
Connects to IsServer.
Parameters
IpAddress of the server
port of the server set to 0 for default port
password of the server
Returns
0 on success, error code from ErrorModuleHandler on not success
ConnectFromCLI()
void CGame::ConnectFromCLI () inline protected
Definition at line 2547 of file DayZGame.c.
  {
    string port;
    if (GetCLIParam("connect", m_ConnectAddress))
    {
      GetCLIParam("port", port);
      m_ConnectPort = port.ToInt();
      GetCLIParam("password", m_ConnectPassword);
      m_ConnectFromJoin = false;
      Connect();
    }
  }
References Connect(), and GetCLIParam().
Referenced by ConnectLaunch(), and TryConnect().
ConnectFromJoin()
void CGame::ConnectFromJoin (string ip, int port) inline protected
Definition at line 2539 of file DayZGame.c.
  {
    m_ConnectAddress = ip;
    m_ConnectPort = port;
    m_ConnectFromJoin = true;
    Connect();
  }
References Connect().
ConnectFromServerBrowser()
void CGame::ConnectFromServerBrowser (string ip, int port, string password = "") inline protected
Definition at line 2530 of file DayZGame.c.
  {
    m_ConnectAddress = ip;
    m_ConnectPort = port;
    m_ConnectPassword = password;
    m_ConnectFromJoin = false;
    OnlineServices.LoadMPPrivilege();
  }
References OnlineServices::LoadMPPrivilege().
ConnectLastSession()
proto native int CGame::ConnectLastSession (UIScriptedMenu parent, int selectedCharacter = -1) private
Connects to last success network session.
Returns
0 on success, error code from ErrorModuleHandler on not success
ConnectLaunch()
void CGame::ConnectLaunch () inline protected
Definition at line 2063 of file DayZGame.c.
  {
    BiosUserManager user_manager = GetUserManager();
    if (user_manager.GetTitleInitiator())
      user_manager.SelectUserEx(user_manager.GetTitleInitiator());
    SetGameState(DayZGameState.CONNECT);
    SetLoadState(DayZLoadState.CONNECT_START);
#ifndef PLATFORM_WINDOWS
#ifdef PLATFORM_CONSOLE
    CreateTitleScreen();
    GamepadCheck();
#endif
#else
    ConnectFromCLI();
#endif
  }
References ConnectFromCLI(), CreateTitleScreen(), GamepadCheck(), GetUserManager(), SetGameState(), and SetLoadState().
Referenced by OnInitialize().
CopyFromClipboard()
proto void CGame::CopyFromClipboard (out string text) private
CopyToClipboard()
proto native void CGame::CopyToClipboard (string text) private
CreateDefaultPlayer() [1/2]
override string CGame::CreateDefaultPlayer () inline protected
Definition at line 3074 of file DayZGame.c.
  {
    if (m_CharClassNames.Count() > 0)
      return m_CharClassNames[0];
    return "";
  }
CreateDefaultPlayer() [2/2]
string CGame::CreateDefaultPlayer () inline protected
returns class name of first valid survivor (TODO address confusing naming?)
Definition at line 1356 of file Game.c.
{}
CreateGamepadDisconnectMenu()
void CGame::CreateGamepadDisconnectMenu () protected
CreateMission()
native void CGame::CreateMission (string path) protected
Create only enforce script mission, used for mission script reloading.
Referenced by ReloadMission().
CreateObject()
proto native Object CGame::CreateObject (string type, vector pos, bool create_local = false, bool init_ai = false, bool create_physics = true) private
Creates object of certain type.
Parameters
type of objects to create
pos position where to create object
create_local if True, object is not spawned on clients only on server
init_ai if creating object is LightAI class, by this param is initialised AI or not
Returns
new Object
CreateObjectEx()
proto native Object CGame::CreateObjectEx (string type, vector pos, int iFlags, int iRotation = RF_DEFAULT) private
Creates object of certain type.
Parameters
type of objects to create
pos position where to create object
iFlags are used to setup object and/ or spawn behavior
iRotation are used to setup object rotation on spawn (or default if not specified)
Returns
new Object
Referenced by OnProjectileStopped(), OnProjectileStoppedInObject(), and OnProjectileStoppedInTerrain().
CreatePlayer()
proto native Entity CGame::CreatePlayer (PlayerIdentity identity, string name, vector pos, float radius, string spec) private
Assign player entity to client (in multiplayer)
Note
Works only on server
Parameters
name
CreateRandomPlayer() [1/2]
override string CGame::CreateRandomPlayer () inline protected
Definition at line 3083 of file DayZGame.c.
  {
    return m_CharClassNames.GetRandomElement();
  }
CreateRandomPlayer() [2/2]
string CGame::CreateRandomPlayer () inline protected
returns class name of random survivor (TODO address confusing naming?)
Definition at line 1359 of file Game.c.
{}
CreateScriptedMenu() [1/2]
override UIScriptedMenu CGame::CreateScriptedMenu (int id) inline private
create custom main menu part (submenu)
Definition at line 1301 of file DayZGame.c.
  {
#ifndef NO_GUI
    Mission mission = GetMission();
    if (mission)
      return mission.CreateScriptedMenu(id);
#endif
    return NULL;
  }
References Mission::CreateScriptedMenu(), GetMission(), and mission.
CreateScriptedMenu() [2/2]
UIScriptedMenu CGame::CreateScriptedMenu (int id) inline private
create custom main menu part (submenu)
Definition at line 186 of file Game.c.
{ }
CreateScriptedWindow()
UIScriptedWindow CGame::CreateScriptedWindow (int id) inline private
create custom window part
Definition at line 191 of file Game.c.
{ }
CreateSoundOnObject()
proto native SoundOnVehicle CGame::CreateSoundOnObject (Object source, string sound_name, float distance, bool looped, bool create_local = false) private
CreateSoundWaveOnObject()
proto native SoundWaveOnVehicle CGame::CreateSoundWaveOnObject (Object source, SoundObject soundObject, AbstractWave soundWave) private
CreateStaticObjectUsingP3D()
proto native Object CGame::CreateStaticObjectUsingP3D (string p3dFilename, vector position, vector orientation, float scale = 1.0, bool createLocal = false) private
CreateTitleScreen()
void CGame::CreateTitleScreen () inline protected
Definition at line 1989 of file DayZGame.c.
  {
    DeleteTitleScreen();
    m_IntroMenu = GetWorkspace().CreateWidgets("gui/layouts/xbox/day_z_title_screen.layout");
    RichTextWidget text_widget = RichTextWidget.Cast(m_IntroMenu.FindAnyWidget("InputPromptText"));
    m_IntroMenu.FindAnyWidget("notification_root").Show(false);
    if (text_widget)
    {
      string text = Widget.TranslateString("#console_start_game");
#ifdef PLATFORM_XBOX
      BiosUserManager user_manager = GetGame().GetUserManager();
      if (user_manager && user_manager.GetSelectedUser())
        text_widget.SetText(string.Format(text, "<image set=\"xbox_buttons\" name=\"A\" />"));
      else
        text_widget.SetText(string.Format(text, "<image set=\"xbox_buttons\" name=\"A\" />"));
#endif
#ifdef PLATFORM_PS4
      string confirm = "cross";
      if (GetGame().GetInput().GetEnterButton() == GamepadButton.A)
        confirm = "cross";
      else
        confirm = "circle";
      text_widget.SetText(string.Format(text, "<image set=\"playstation_buttons\" name=\"" + confirm + "\" />"));
#endif
    }
#ifdef PLATFORM_CONSOLE
#ifdef PLATFORM_XBOX
#ifdef BUILD_EXPERIMENTAL
    m_IntroMenu.FindAnyWidget("notification_root").Show(true);
#endif
#endif
#endif
  }
References DeleteTitleScreen(), GetGame(), GetInput(), and GetWorkspace().
Referenced by ConnectLaunch(), GamepadCheck(), MissionLaunch(), and OnInitialize().
DayZGame()
void CGame::DayZGame () inline private
Definition at line 947 of file DayZGame.c.
  {
    PPEManagerStatic.CreateManagerStatic();
#ifdef PLATFORM_CONSOLE
    SetMainMenuWorld("MainMenuSceneXbox");
#endif
    m_MissionState = MISSION_STATE_GAME;
    m_keyboard_handler = null;
#ifdef DEVELOPER
    m_early_access_dialog_accepted = true;
#endif
    for (int i = 0; i < CALL_CATEGORY_COUNT; i++)
    {
      m_callQueue[i] = new ScriptCallQueue();
      m_updateQueue[i] = new ScriptInvoker();
      m_timerQueue[i] = new TimerQueue();
      m_postUpdateQueue[i] = new ScriptInvoker();
    }
    m_dragQueue = new DragQueue;
    m_LoginTime = 0;
    string tmp;
    if (CommandlineGetParam("stresstest", tmp))
      m_IsStressTest = true;
    if (CommandlineGetParam("doAimLogs", tmp))
      m_AimLoggingEnabled = true;
    // initialize backlit effects
    m_Backlit = new Backlit();
    m_Backlit.OnInit(this);
    m_ReportModded = GetModToBeReported();
#ifndef NO_GUI
    if (m_loading == null)
      m_loading = new LoadingScreen(this);
    if (m_loading)
      m_loading.ShowEx(this);
    RefreshMouseCursorVisibility();
#endif
    Debug.Init();
    Component.Init();
    CachedObjectsParams.Init();
    CachedObjectsArrays.Init();
    BleedChanceData.InitBleedChanceData();
    GetUApi().PresetSelect(GetUApi().PresetCurrent());
    m_DayZProfileOptions = new DayZProfilesOptions();
    GetCallQueue(CALL_CATEGORY_GUI).Call(DeferredInit);
    GetCallQueue(CALL_CATEGORY_GAMEPLAY).Call(GlobalsInit);
    string path = "cfgVehicles";
    string child_name = "";
    int count = ConfigGetChildrenCount(path);
    for (int p = 0; p < count; ++p)
    {
      ConfigGetChildName(path, p, child_name);
      if (ConfigGetInt(path + " " + child_name + " scope") == 2 && IsKindOf(child_name, "SurvivorBase"))
        m_CharClassNames.Insert(child_name);
    }
    m_IsConnecting = false;
    m_ConnectFromJoin = false;
  }
References CALL_CATEGORY_COUNT, CALL_CATEGORY_GAMEPLAY, CALL_CATEGORY_GUI, CommandlineGetParam(), ConfigGetChildName(), ConfigGetChildrenCount(), ConfigGetInt(), PPEManagerStatic::CreateManagerStatic(), GetCallQueue(), GetModToBeReported(), GetUApi(), Component::Init(), Debug::Init(), CachedObjectsParams::Init(), CachedObjectsArrays::Init(), BleedChanceData::InitBleedChanceData(), IsKindOf(), LoadingScreen(), m_timerQueue, MISSION_STATE_GAME, path, RefreshMouseCursorVisibility(), and SetMainMenuWorld().
Referenced by IsMissionMainMenu().
DeferredInit()
void CGame::DeferredInit () inline private
Definition at line 1039 of file DayZGame.c.
  {
    GameOptions opt = new GameOptions();
    opt.Initialize();
    GetInput().UpdateConnectedInputDeviceList();
    m_UserFOV = GetUserFOVFromConfig();
    m_volume_sound = GetSoundScene().GetSoundVolume();
    m_volume_speechEX = GetSoundScene().GetSpeechExVolume();
    m_volume_music = GetSoundScene().GetMusicVolume();
    m_volume_VOIP = GetSoundScene().GetVOIPVolume();
    m_volume_radio = GetSoundScene().GetRadioVolume();
    PPEManagerStatic.GetPPEManager().Init();
    GetMenuDefaultCharacterData();
  }
References GetInput(), GetMenuDefaultCharacterData(), PPEManagerStatic::GetPPEManager(), GetSoundScene(), and GetUserFOVFromConfig().
DelayedMidAirDetonation()
void CGame::DelayedMidAirDetonation (float x, float y, float z) inline protected
Definition at line 3006 of file DayZGame.c.
  {
    EffectSound artilleryFallSound = SEffectManager.PlaySound("Artillery_Fall_SoundSet", Vector(x, y, z));
    artilleryFallSound.SetAutodestroy(true);
  }
References SEffectManager::PlaySound(), Vector(), x, and y.
DeleteGamepadDisconnectMenu()
void CGame::DeleteGamepadDisconnectMenu () protected
DeleteTitleScreen()
void CGame::DeleteTitleScreen () inline protected
Definition at line 2025 of file DayZGame.c.
  {
    if (m_IntroMenu)
      delete m_IntroMenu;
  }
References m_IntroMenu.
Referenced by Connect(), CreateTitleScreen(), GamepadCheck(), MainMenuLaunch(), and SelectGamepad().
DisconnectPlayer()
proto native void CGame::DisconnectPlayer (PlayerIdentity identity, string uid = "") private
Destroy player info and disconnect.
Note
Works only on server
DisconnectSession()
proto native void CGame::DisconnectSession () private
Disconnects from current multiplayer session.
DisconnectSessionEx()
void CGame::DisconnectSessionEx (DisconnectSessionFlags flags) inline protected
Definition at line 2485 of file DayZGame.c.
  {
    if (flags & DisconnectSessionFlags.SELECT_USER && OnlineServices.GetBiosUser())
      GetGame().GetUserManager().SelectUserEx(OnlineServices.GetBiosUser());
    if (flags & DisconnectSessionFlags.JOIN_ERROR_ENABLED)
    {
      if (!(flags & DisconnectSessionFlags.JOIN_ERROR_CHECK) || GetGameState() == DayZGameState.JOIN)
        NotificationSystem.AddNotification(NotificationType.JOIN_FAIL_GET_SESSION, NotificationSystem.DEFAULT_TIME_DISPLAYED);
    }
    if (flags & DisconnectSessionFlags.IGNORE_WHEN_IN_GAME && GetGameState() == DayZGameState.IN_GAME)
      return;
    if (flags & DisconnectSessionFlags.CLOSE_MENUS && GetGame().GetUIManager())
    {
      GetGame().GetUIManager().CloseAllSubmenus();
      if (GetGame().GetUIManager().IsDialogVisible())
        GetGame().GetUIManager().CloseDialog();
    }
    if (flags & DisconnectSessionFlags.ALWAYS_FORCE)
      DisconnectSessionForce();
    if (GetGame().GetMission())
    {
      if (g_Game.GetGameState() != DayZGameState.MAIN_MENU)
      {
        if (flags & DisconnectSessionFlags.DISCONNECT_ERROR_ENABLED)
          NotificationSystem.AddNotification(NotificationType.DISCONNECTED, NotificationSystem.DEFAULT_TIME_DISPLAYED);
        GetGame().GetMission().AbortMission();
        SetGameState(DayZGameState.MAIN_MENU);
        SetLoadState(DayZLoadState.MAIN_MENU_CONTROLLER_SELECT);
        GamepadCheck();
      }
    }
    else
      MainMenuLaunch();
  }
References NotificationSystem::AddNotification(), NotificationSystem::DEFAULT_TIME_DISPLAYED, DisconnectSessionForce(), g_Game, GamepadCheck(), OnlineServices::GetBiosUser(), GetGame(), GetMission(), GetUIManager(), MainMenuLaunch(), SetGameState(), and SetLoadState().
Referenced by DisconnectSessionScript().
DisconnectSessionForce()
proto native void CGame::DisconnectSessionForce () private
Forces disconnect from current multiplayer session even if not yet in the game.
Referenced by DisconnectSessionEx(), and TryConnect().
DisconnectSessionScript()
void CGame::DisconnectSessionScript (bool displayJoinError = false) inline protected
Definition at line 2473 of file DayZGame.c.
  {
    DisconnectSessionFlags flags = DisconnectSessionFlags.SELECT_USER | DisconnectSessionFlags.IGNORE_WHEN_IN_GAME;
    if (displayJoinError)
    {
      flags |= DisconnectSessionFlags.JOIN_ERROR_ENABLED;
      flags |= DisconnectSessionFlags.JOIN_ERROR_CHECK;
    }
    DisconnectSessionEx(flags);
  }
References DisconnectSessionEx().
Referenced by Connect(), and TryConnect().
DumpInstances()
proto native void CGame::DumpInstances (bool csvFormatting) private
Delevoper only: Dump all script allocations.
EarlyAccessDialog()
void CGame::EarlyAccessDialog (UIScriptedMenu parent) inline private
Definition at line 1290 of file DayZGame.c.
  {
    if (!m_early_access_dialog_accepted)
    {
      g_Game.GetUIManager().EnterScriptedMenu(MENU_EARLYACCESS, parent);
      m_early_access_dialog_accepted = true;
    }
  }
References g_Game, and MENU_EARLYACCESS.
EnableMicCapture()
proto native void CGame::EnableMicCapture (bool enable) private
Enable microphone to locally capture audio from user. Audio heard does NOT automatically get transmitted over network.
Parameters
enable enables or disabled listening
EnableVoN()
proto native void CGame::EnableVoN (Object player, bool enable) private
Enable/disable VoN for target player.
Parameters
player in question
enable sets if player can use VoN
EndOptionsVideo()
proto native void CGame::EndOptionsVideo () private
EnterLoginQueue()
void CGame::EnterLoginQueue (UIMenuPanel parent) inline protected
Definition at line 1832 of file DayZGame.c.
  {
    m_LoginQueue = LoginQueueBase.Cast(GetUIManager().EnterScriptedMenu(MENU_LOGIN_QUEUE, parent));
  }
References GetUIManager(), and MENU_LOGIN_QUEUE.
Referenced by UpdateLoginQueue().
EnterLoginTime()
void CGame::EnterLoginTime (UIMenuPanel parent) inline protected
Definition at line 1838 of file DayZGame.c.
  {
    m_LoginTimeScreen = LoginTimeBase.Cast(GetUIManager().EnterScriptedMenu(MENU_LOGIN_TIME, parent));
  }
References GetUIManager(), and MENU_LOGIN_TIME.
Referenced by OnLoginTimeEvent(), and OnRespawnEvent().
ExecuteEnforceScript()
proto native bool CGame::ExecuteEnforceScript (string expression, string mainFnName) private
Delevoper only: Executes Enforce Script expression, if there is an error, is printed into the script console.
ExplosionEffects()
void CGame::ExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType) inline protected
Definition at line 3114 of file DayZGame.c.
  {
#ifndef SERVER
    if (source)
    {
      source.OnExplosionEffects(source, directHit, componentIndex, surface, pos, surfNormal, energyFactor, explosionFactor, isWater, ammoType);
      if (source.ShootsExplosiveAmmo() && ammoType == "Explosion_40mm_Ammo")
        ParticleManager.GetInstance().PlayInWorld(ParticleList.EXPLOSION_LANDMINE, pos);
      float distance_to_player = vector.Distance(pos, GetGame().GetPlayer().GetPosition());
      m_AmmoShakeParams.Load(ammoType);
      if (distance_to_player < m_AmmoShakeParams.m_Radius)
      {
        float dist01 = Math.InverseLerp(0, m_AmmoShakeParams.m_Radius, distance_to_player);
        float modifier = Math.Lerp(m_AmmoShakeParams.m_ModifierClose, m_AmmoShakeParams.m_ModifierFar, dist01);
        GetGame().GetPlayer().GetCurrentCamera().SpawnCameraShake(modifier * m_AmmoShakeParams.m_Strength);
      }
    }
#endif
  }
References vector::Distance(), ParticleList::EXPLOSION_LANDMINE, GetGame(), GetPlayer(), GetPosition, Math::InverseLerp(), Math::Lerp(), and ParticleManager().
Referenced by ExplosionEffectsEx().
ExplosionEffectsEx()
void CGame::ExplosionEffectsEx (Object source, Object directHit, int componentIndex, float energyFactor, float explosionFactor, HitInfo hitInfo) inline protected
Definition at line 3095 of file DayZGame.c.
  {
    vector pos = hitInfo.GetPosition();
    string ammoType = hitInfo.GetAmmoType();
    // Call legacy method
    ExplosionEffects(source, directHit, componentIndex, hitInfo.GetSurface(), pos, hitInfo.GetSurfaceNormal(), energyFactor, explosionFactor, hitInfo.IsWater(), ammoType);
    // add explosion noise
    if (IsServer())
    {
      //NoiseParams npar = new NoiseParams();
      m_NoiseParams.LoadFromPath(string.Format("cfgAmmo %1 NoiseExplosion", ammoType));
      GetNoiseSystem().AddNoiseTarget(pos, 21, m_NoiseParams, hitInfo.GetSurfaceNoiseMultiplier());
    }
  }
References ExplosionEffects(), GetNoiseSystem(), IsServer(), and m_NoiseParams.
ExtendActionJuncture()
proto native bool CGame::ExtendActionJuncture (Man player, notnull EntityAI item, int timeout_ms) private
FirearmEffects()
void CGame::FirearmEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, vector exitPos, vector inSpeed, vector outSpeed, bool isWater, bool deflected, string ammoType) inline protected
Definition at line 3226 of file DayZGame.c.
  {
#ifndef SERVER
    ImpactEffectsData impactEffectsData = new ImpactEffectsData();
    impactEffectsData.m_DirectHit = directHit;
    impactEffectsData.m_ComponentIndex = componentIndex;
    impactEffectsData.m_Surface = surface;
    impactEffectsData.m_Position = pos;
    impactEffectsData.m_ImpactType = ImpactTypes.UNKNOWN;
    impactEffectsData.m_SurfaceNormal = surfNormal;
    impactEffectsData.m_ExitPosition = exitPos;
    impactEffectsData.m_InSpeed = inSpeed;
    impactEffectsData.m_OutSpeed = outSpeed;
    impactEffectsData.m_IsDeflected = deflected;
    impactEffectsData.m_AmmoType = ammoType;
    impactEffectsData.m_IsWater = isWater;
    if (directHit)
      directHit.OnReceivedHit(impactEffectsData);
    ImpactMaterials.EvaluateImpactEffectEx(impactEffectsData);
#endif
    if (IsServer())
    {
      if (source && source.ShootsExplosiveAmmo() && !deflected && outSpeed == vector.Zero)
      {
        if (ammoType == "Bullet_40mm_ChemGas")
          GetGame().CreateObject("ContaminatedArea_Local", pos);
        else if (ammoType == "Bullet_40mm_Explosive")
          DamageSystem.ExplosionDamage(EntityAI.Cast(source), null, "Explosion_40mm_Ammo", pos, DamageType.EXPLOSION);
      }
      // add hit noise
      m_NoiseParams.LoadFromPath("cfgAmmo " + ammoType + " NoiseHit");
      float surfaceCoef = SurfaceGetNoiseMultiplier(directHit, pos, componentIndex);
      float coefAdjusted = surfaceCoef * inSpeed.Length() / ConfigGetFloat("cfgAmmo " + ammoType + " initSpeed");
      GetNoiseSystem().AddNoiseTarget(pos, 10, m_NoiseParams, coefAdjusted); // Leave a ping for 5 seconds
    }
  }
References ConfigGetFloat(), ImpactMaterials::EvaluateImpactEffectEx(), GetGame(), GetNoiseSystem(), IsServer(), m_NoiseParams, SurfaceGetNoiseMultiplier(), and vector::Zero.
FormatRawConfigStringKeys()
bool CGame::FormatRawConfigStringKeys (inout string value) inline private
Changes localization key format to script-friendly format.
Parameters
original config string.
Returns
value output string with '$' substituted to script-friendly '#'. If not found, does nothing.
Definition at line 457 of file Game.c.
  {
    int ret;
    ret = value.Replace("$STR_", "#STR_");
    return ret > 0;
  }
FormatString()
proto void CGame::FormatString (string format, string params[], out string output) private
GamepadCheck()
void CGame::GamepadCheck () inline protected
Definition at line 2236 of file DayZGame.c.
  {
#ifndef AUTOTEST
    if (GetInput().IsActiveGamepadSelected())
    {
#endif
      DeleteTitleScreen();
      SelectUser();
#ifndef AUTOTEST
    }
    else
    {
#ifdef PLATFORM_CONSOLE
#ifndef PLATFORM_WINDOWS
#ifdef PLATFORM_PS4
      if (GetUserManager().GetSelectedUser())
      {
        int gamepad = GetInput().GetUserGamepad(GetUserManager().GetSelectedUser());
        if (gamepad > -1)
          SelectUser(gamepad);
        else
        {
          if (!m_IntroMenu && !(GetGame().GetUIManager().GetMenu() && GetGame().GetUIManager().GetMenu().GetID() == MENU_TITLE_SCREEN))
            CreateTitleScreen();
          GetGame().GetInput().IdentifyGamepad(GetGame().GetInput().GetEnterButton());
        }
      }
      else
#endif
      {
        if (!m_IntroMenu && !(GetUIManager().GetMenu() && GetUIManager().GetMenu().GetID() == MENU_TITLE_SCREEN))
          CreateTitleScreen();
        GetInput().IdentifyGamepad(GetInput().GetEnterButton());
      }
#endif
#endif
    }
#endif
  }
References CreateTitleScreen(), DeleteTitleScreen(), GetGame(), GetID(), GetInput(), GetUIManager(), GetUserManager(), MENU_TITLE_SCREEN, and SelectUser().
Referenced by ConnectLaunch(), DisconnectSessionEx(), MissionLaunch(), and SelectUser().
GetAnalyticsClient()
AnalyticsManagerClient CGame::GetAnalyticsClient () inline protected
Definition at line 1399 of file Game.c.
  {
    return m_AnalyticsManagerClient;
  }
References m_AnalyticsManagerClient.
GetAnalyticsServer()
AnalyticsManagerServer CGame::GetAnalyticsServer () inline protected
Definition at line 1394 of file Game.c.
  {
    return m_AnalyticsManagerServer;
  }
References m_AnalyticsManagerServer.
GetBacklit()
Backlit CGame::GetBacklit () inline private
Definition at line 1274 of file DayZGame.c.
  {
    return m_Backlit;
  }
References m_Backlit.
GetBillboardHandler()
BillboardSetHandler CGame::GetBillboardHandler () inline protected
Definition at line 3516 of file DayZGame.c.
  {
    return m_BillboardSetHandler;
  }
References m_BillboardSetHandler.
GetCallQueue() [1/2]
override ScriptCallQueue CGame::GetCallQueue (int call_category) inline private
Definition at line 1129 of file DayZGame.c.
  {
    return m_callQueue[call_category];
  }
Referenced by CancelLoginTimeCountdown(), DayZGame(), OnEvent(), OnLoginTimeEvent(), OnRespawnEvent(), OnRPC(), OnUpdate(), and UpdateInputDeviceDisconnectWarning().
GetCallQueue() [2/2]
ScriptCallQueue CGame::GetCallQueue (int call_category) inline protected
Returns CallQueue for certain category
Parameters
call_category call category, valid values are:
CALL_CATEGORY_SYSTEM - calls & timers in this queue are processed every time without any restrictions
CALL_CATEGORY_GUI - calls & timers in this queue are processed when GUI is enabled (even during pase game)
CALL_CATEGORY_GAMEPLAY - calls & timers in this queue are processed only during mission, when game is not paused
usage:
GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(this, "Refresh"); // calls "Refresh" function on "this" with no arguments
GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(this, "Show", new Param1<bool>(true)); // calls "Show" function on "this" with one bool argument
GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(this, "SetPos", new Param2<float, float>(0.2, 0.5)); // calls "SetPos" function on "this" with two float arguments
Definition at line 1336 of file Game.c.
{}
GetConnectedInputDeviceList()
array< int > CGame::GetConnectedInputDeviceList () inline protected
Definition at line 3454 of file DayZGame.c.
  {
    if (!m_ConnectedInputDeviceList)
      m_ConnectedInputDeviceList = new array<int>;
    return m_ConnectedInputDeviceList;
  }
References m_ConnectedInputDeviceList.
GetContentDLCService()
proto native ContentDLC CGame::GetContentDLCService () protected
Return DLC service (service for entitlement keys for unlock content)
GetCurrentCameraDirection()
proto native vector CGame::GetCurrentCameraDirection () private
GetCurrentCameraPosition()
proto native vector CGame::GetCurrentCameraPosition () private
GetCurrentDisplayLanguageIdx()
int CGame::GetCurrentDisplayLanguageIdx () inline protected
Definition at line 3422 of file DayZGame.c.
  {
    ListOptionsAccess language_option;
    GameOptions options = new GameOptions();
    language_option = ListOptionsAccess.Cast(options.GetOptionByType(OptionAccessType.AT_OPTIONS_LANGUAGE));
    int idx = -1;
    if (language_option)
      idx = language_option.GetIndex();
    return idx;
  }
GetCurrentEVValue()
float CGame::GetCurrentEVValue () inline protected
Definition at line 3412 of file DayZGame.c.
  {
    return m_EVValue;
  }
References m_EVValue.
GetDatabaseID()
string CGame::GetDatabaseID () inline protected
Definition at line 1977 of file DayZGame.c.
  {
    return m_DatabaseID;
  }
References m_DatabaseID.
GetDayTime()
proto native float CGame::GetDayTime () private
Returns current daytime on server.
GetDeltaT()
float CGame::GetDeltaT () inline protected
Definition at line 2643 of file DayZGame.c.
  {
    return m_DeltaTime;
  }
References m_DeltaTime.
GetDiagDrawMode()
proto native int CGame::GetDiagDrawMode () private
Gets current debug draw mode.
GetDiagDrawModeNames()
proto native void CGame::GetDiagDrawModeNames (out TStringArray diag_names) private
Get list of all debug draw modes.
GetDiagModeEnable()
proto native bool CGame::GetDiagModeEnable (int diag_mode) private
Gets state of specific debug mode.
GetDiagModeNames()
proto native void CGame::GetDiagModeNames (out TStringArray diag_names) private
Get list of all debug modes.
GetDragQueue() [1/2]
override DragQueue CGame::GetDragQueue () inline private
Definition at line 1149 of file DayZGame.c.
  {
    return m_dragQueue;
  }
References m_dragQueue.
Referenced by OnUpdate().
GetDragQueue() [2/2]
DragQueue CGame::GetDragQueue () inline protected
Returns DragQueue. Callbacks are called on mouse move until mouse button is released, then the queue is cleaned.
Definition at line 1353 of file Game.c.
{}
GetEntityByPersitentID()
proto native EntityAI CGame::GetEntityByPersitentID (int b1, int b2, int b3, int b4) protected
Returns EntityAI by its persistent ID parts or null if entity with given persistent ID does not exists.
This function returns valid data only inside AfterLoad event. Do not use this in anywhere else.
Its main purpose is only for keep track on object connections after server restarts, all data related to this function are deleted when server initialization is done.
GetFoodDecayModifier()
float CGame::GetFoodDecayModifier () inline protected
Definition at line 3444 of file DayZGame.c.
  {
#ifdef DIAG_DEVELOPER
    if (FeatureTimeAccel.GetFeatureTimeAccelEnabled(ETimeAccelCategories.FOOD_DECAY))
      return m_FoodDecayModifier * FeatureTimeAccel.GetFeatureTimeAccelValue();
#endif
    return m_FoodDecayModifier;
  }
References m_FoodDecayModifier.
Referenced by IsFoodDecayEnabled().
GetFOVByZoomType()
float CGame::GetFOVByZoomType (ECameraZoomType type) inline protected
Definition at line 3360 of file DayZGame.c.
  {
    switch (type)
    {
    case ECameraZoomType.NONE:
      return GetUserFOV();
    case ECameraZoomType.NORMAL:
      return Math.Min(GetUserFOV(), GameConstants.DZPLAYER_CAMERA_FOV_EYEZOOM);
    case ECameraZoomType.SHALLOW:
      return Math.Min(GetUserFOV(), GameConstants.DZPLAYER_CAMERA_FOV_EYEZOOM_SHALLOW);
    default:
      return GetUserFOV();
    }
    return GetUserFOV();
  }
References GameConstants::DZPLAYER_CAMERA_FOV_EYEZOOM, GameConstants::DZPLAYER_CAMERA_FOV_EYEZOOM_SHALLOW, GetUserFOV(), and Math::Min().
GetFps()
proto native float CGame::GetFps () private
Returns average FPS of last 16 frames.
Returns
fps in milliseconds
GetGameState()
DayZGameState CGame::GetGameState () inline private
Definition at line 1254 of file DayZGame.c.
  {
    return m_GameState;
  }
References m_GameState.
Referenced by OnEvent(), OnMPConnectionLostEvent(), and TryConnect().
GetHighestSurfaceYDifference()
float CGame::GetHighestSurfaceYDifference (array< vector > positions) inline protected
Returns the largest height difference between the given positions.
Definition at line 1051 of file Game.c.
  {
    float high = -9999999;
    float low = 99999999;
    for (int i = 0; i < positions.Count(); i++)
    {
      vector pos = positions.Get(i);
      pos[1] = SurfaceRoadY(pos[0], pos[2]);
      float y = pos[1];
      if (y > high)
        high = y;
      if (y < low)
        low = y;
      ;
    }
    return high - low;
  }
References SurfaceRoadY(), and y.
GetHostAddress()
proto bool CGame::GetHostAddress (out string address, out int port) private
Gets the server address. (from client)
Referenced by Connect(), OnEvent(), RefreshCurrentServerInfo(), and TryConnect().
GetHostData()
proto GetServersResultRow CGame::GetHostData () private
Gets the server data. (from client)
GetHostName()
proto owned string CGame::GetHostName () private
Gets the server name. (from client)
GetHUDBrightnessSetting()
float CGame::GetHUDBrightnessSetting () inline protected
Definition at line 3382 of file DayZGame.c.
  {
    return g_Game.GetProfileOptionFloat(EDayZProfilesOptions.HUD_BRIGHTNESS);
  }
References g_Game.
Referenced by OnInitialize().
GetInput()
proto native Input CGame::GetInput () private
Referenced by CanDisplayMouseCursor(), CreateTitleScreen(), DeferredInit(), GamepadCheck(), SelectUser(), and UpdateInputDeviceDisconnectWarning().
GetInventoryItemSize()
proto void CGame::GetInventoryItemSize (InventoryItem item, out int width, out int height) private
GetLastVisitedServer()
bool CGame::GetLastVisitedServer (out string ip, out int port) inline protected
Definition at line 2393 of file DayZGame.c.
  {
    if (m_Visited)
    {
      if (m_Visited.Count() > 0)
      {
        string uid = m_Visited.Get(m_Visited.Count() - 1);
        TStringArray output = new TStringArray;
        uid.Split(":", output);
        ip = output[0];
        port = output[1].ToInt();
        return true;
      }
    }
    return false;
  }
GetLoadingWorkspace()
proto native WorkspaceWidget CGame::GetLoadingWorkspace () private
GetLoadState()
DayZLoadState CGame::GetLoadState () inline private
Definition at line 1264 of file DayZGame.c.
  {
    return m_LoadState;
  }
References m_LoadState.
Referenced by OnInitialize(), SelectGamepad(), SelectUser(), and TryConnect().
GetMainMenuWorld()
proto native owned string CGame::GetMainMenuWorld () protected
Referenced by MainMenuLaunch(), and PartyLaunch().
GetMenuData()
proto native MenuData CGame::GetMenuData () private
Return singleton of MenuData class - at main menu contains characters played with current profile.
GetMenuDefaultCharacterData()
MenuDefaultCharacterData CGame::GetMenuDefaultCharacterData (bool fill_data = true) inline protected
Definition at line 1379 of file Game.c.
  {
    //Print("GetMenuDefaultCharacterData");
    //DumpStack();
    //if used on server, creates an empty container to be filled by received data
    if (!m_CharacterData)
    {
      m_CharacterData = new MenuDefaultCharacterData;
      if (fill_data)
        GetGame().GetMenuData().RequestGetDefaultCharacterData(); //fills the structure
    }
    return m_CharacterData;
  }
References GetGame(), and m_CharacterData.
Referenced by DeferredInit(), and StoreLoginDataPrepare().
GetMission()
proto native Mission CGame::GetMission () private
Referenced by CheckDialogs(), CreateScriptedMenu(), DisconnectSessionEx(), OnConnectivityStatChange(), OnEvent(), OnKeyPress(), OnKeyRelease(), OnLoginTimeEvent(), OnMouseButtonPress(), OnMouseButtonRelease(), OnPostUpdate(), OnUpdate(), UpdateLoginQueue(), and UpdateVoiceLevel().
GetMissionFolderPath()
string CGame::GetMissionFolderPath () inline private
Definition at line 1124 of file DayZGame.c.
  {
    return m_MissionFolderPath;
  }
References m_MissionFolderPath.
GetMissionPath()
string CGame::GetMissionPath () inline private
Definition at line 1119 of file DayZGame.c.
  {
    return m_MissionPath;
  }
References m_MissionPath.
GetMissionState()
int CGame::GetMissionState () inline private
Definition at line 1162 of file DayZGame.c.
  {
    return m_MissionState;
  }
References m_MissionState.
GetModelName()
string CGame::GetModelName (string class_name) inline private
Get name of the p3d file of the given class name.
Parameters
class name of the desired object
Returns
Name of the object's p3d file (without the '.p3d' suffix)
Definition at line 469 of file Game.c.
  {
    if (class_name != "")
    {
      string cfg = "CfgVehicles " + class_name + " model";
      string model_path;
      if (GetGame().ConfigGetText(cfg, model_path))
      {
        int to_substring_end = model_path.Length() - 4; // -4 to leave out the '.p3d' suffix
        int to_substring_start = 0;
        // Currently we have model path. To get the name out of it we need to parse this string from the end and stop at the first found '\' sign
        for (int i = to_substring_end; i > 0; i--)
        {
          string sign = model_path.Get(i);
          if (sign == "\\")
          {
            to_substring_start = i + 1;
            break
          }
        }
        string model_name = model_path.Substring(to_substring_start, to_substring_end - to_substring_start);
        return model_name;
      }
    }
    return "UNKNOWN_P3D_FILE";
  }
References class_name, ConfigGetText(), and GetGame().
GetModInfos()
proto native void CGame::GetModInfos (notnull out array< ref ModInfo > modArray) private
GetModToBeReported()
proto native bool CGame::GetModToBeReported () private
Referenced by DayZGame().
GetMouseCursorDesiredVisibility()
bool CGame::GetMouseCursorDesiredVisibility () inline protected
Definition at line 3468 of file DayZGame.c.
  {
    return m_CursorDesiredVisibilityScript;
  }
References m_CursorDesiredVisibilityScript.
GetNoiseSystem()
proto native NoiseSystem CGame::GetNoiseSystem () private
Referenced by CloseCombatEffects(), ExplosionEffectsEx(), and FirearmEffects().
GetObjectByNetworkId()
proto native Object CGame::GetObjectByNetworkId (int networkIdLowBits, int networkIdHighBits) private
Returns entity identified by network id.
Parameters
networkIdLowBits identity used in MP (use NULL in singleplayer)
networkIdHighBits object which should be controlled by player
GetObjectsAtPosition()
proto native void CGame::GetObjectsAtPosition (vector pos, float radius, out array< Object > objects, out array< CargoBase > proxyCargos) private
Returns list of all objects in circle "radius" around position "pos".
Parameters
pos
radius
objects output array
GetObjectsAtPosition3D()
proto native void CGame::GetObjectsAtPosition3D (vector pos, float radius, out array< Object > objects, out array< CargoBase > proxyCargos) private
Returns list of all objects in sphere "radius" around position "pos".
Parameters
pos
radius
objects output array
GetPlayer()
proto native DayZPlayer CGame::GetPlayer () private
Referenced by ExplosionEffects(), OnEvent(), OnRespawnEvent(), OnRPC(), and OnUpdate().
GetPlayerByIndex()
DayZPlayer CGame::GetPlayerByIndex (int index = 0) inline private
Definition at line 814 of file Game.c.
  {
    array<Man> players();
    GetPlayers(players);
    if (index >= players.Count())
      return null;
    return DayZPlayer.Cast(players[index]);
  }
References GetPlayers().
GetPlayerGameName()
string CGame::GetPlayerGameName () inline protected
Definition at line 3320 of file DayZGame.c.
  {
    return m_PlayerName;
  }
References m_PlayerName.
GetPlayerIndentities()
proto native void CGame::GetPlayerIndentities (out array< PlayerIdentity > identities) protected
GetPlayerName()
proto void CGame::GetPlayerName (out string name) private
Gets current player name.
Parameters
name output value
GetPlayerNameShort()
proto void CGame::GetPlayerNameShort (int maxLength, out string name) private
Gets current player name. If length of player name is grater than maxLength, then it is omitted and append ellipsis.
Parameters
maxLength - max chars in name
name - output value of player name with 'maxLength' characters and then ellipsis "..."
GetPlayerNetworkIDByIdentityID()
proto void CGame::GetPlayerNetworkIDByIdentityID (int playerIdentityID, out int networkIdLowBits, out int networkIdHightBits) private
returns player's network id from identity id in out parameters
Parameters
identity PlayerIdentity.id used in MP (use NULL in singleplayer)
networkIdLowBits lower bits of 64bit network id
networkIdHighBits higher bits of 64bit network id
Note
Usable only on server
GetPlayers()
proto native void CGame::GetPlayers (out array< Man > players) private
Referenced by GetPlayerByIndex().
GetPointerDirection()
proto native vector CGame::GetPointerDirection () private
Returns the direction where the mouse points, from the camera view.
GetPostUpdateQueue() [1/2]
override ScriptInvoker CGame::GetPostUpdateQueue (int call_category) inline private
Definition at line 1139 of file DayZGame.c.
  {
    return m_postUpdateQueue[call_category];
  }
Referenced by OnPostUpdate().
GetPostUpdateQueue() [2/2]
ScriptInvoker CGame::GetPostUpdateQueue (int call_category) inline protected
Definition at line 1340 of file Game.c.
{}
GetPreviousEVValue()
float CGame::GetPreviousEVValue () inline protected
Definition at line 3417 of file DayZGame.c.
  {
    return m_PreviousEVValue;
  }
References m_PreviousEVValue.
GetPreviousGamepad()
int CGame::GetPreviousGamepad () inline protected
Definition at line 2231 of file DayZGame.c.
  {
    return m_PreviousGamepad;
  }
References m_PreviousGamepad.
GetProfileOption()
bool CGame::GetProfileOption (EDayZProfilesOptions option) inline private
Definition at line 1174 of file DayZGame.c.
  {
    return m_DayZProfileOptions.GetProfileOption(option);
  }
Referenced by GetProfileOptionBool().
GetProfileOptionBool()
bool CGame::GetProfileOptionBool (EDayZProfilesOptions option) inline private
Definition at line 1179 of file DayZGame.c.
  {
    return GetProfileOption(option);
  }
References GetProfileOption().
GetProfileOptionDefault()
bool CGame::GetProfileOptionDefault (EDayZProfilesOptions option) inline private
Definition at line 1194 of file DayZGame.c.
  {
    return m_DayZProfileOptions.GetProfileOptionDefaultBool(option);
  }
Referenced by GetProfileOptionDefaultBool().
GetProfileOptionDefaultBool()
bool CGame::GetProfileOptionDefaultBool (EDayZProfilesOptions option) inline private
Definition at line 1199 of file DayZGame.c.
  {
    return GetProfileOptionDefault(option);
  }
References GetProfileOptionDefault().
GetProfileOptionDefaultFloat()
float CGame::GetProfileOptionDefaultFloat (EDayZProfilesOptions option) inline private
Definition at line 1209 of file DayZGame.c.
  {
    return m_DayZProfileOptions.GetProfileOptionDefaultFloat(option);
  }
GetProfileOptionDefaultInt()
int CGame::GetProfileOptionDefaultInt (EDayZProfilesOptions option) inline private
Definition at line 1204 of file DayZGame.c.
  {
    return m_DayZProfileOptions.GetProfileOptionDefaultInt(option);
  }
GetProfileOptionFloat()
float CGame::GetProfileOptionFloat (EDayZProfilesOptions option) inline private
Definition at line 1189 of file DayZGame.c.
  {
    return m_DayZProfileOptions.GetProfileOptionFloat(option);
  }
GetProfileOptionInt()
int CGame::GetProfileOptionInt (EDayZProfilesOptions option) inline private
Definition at line 1184 of file DayZGame.c.
  {
    return m_DayZProfileOptions.GetProfileOptionInt(option);
  }
GetProfileOptionMap()
map< EDayZProfilesOptions, ref DayZProfilesOption > CGame::GetProfileOptionMap () inline private
Definition at line 1234 of file DayZGame.c.
  {
    return m_DayZProfileOptions.GetProfileOptionMap();
  }
GetProfileString()
proto bool CGame::GetProfileString (string name, out string value) private
Gets string from profile variable.
Parameters
name of the variable
value output value
Returns
true when successful
GetProfileStringList()
proto native void CGame::GetProfileStringList (string name, out TStringArray values) private
Gets array of strings from profile variable.
Parameters
name of the variable
values output values
usage:
TStringArray lastInventoryArray = new TStringArray;
GetGame().GetProfileStringList("lastInventory", lastInventoryArray);
Referenced by OnInitialize().
GetScreenPos()
proto native vector CGame::GetScreenPos (vector world_pos) private
Transforms position in world to position in screen in pixels as x, y component of vector, z parameter represents distance between camera and world_pos.
GetScreenPosRelative()
proto native vector CGame::GetScreenPosRelative (vector world_pos) private
Transforms position in world to position in screen in percentage (0.0 - 1.0) as x, y component of vector, z parameter represents distance between camera and world_pos.
GetSoundScene()
proto native AbstractSoundScene CGame::GetSoundScene () private
Referenced by DeferredInit().
GetSurfaceOrientation()
vector CGame::GetSurfaceOrientation (float x, float z) inline protected
Returns tilt of the ground on the given position in degrees, so you can use this value to rotate any item according to terrain.
Definition at line 1075 of file Game.c.
  {
    vector normal = GetGame().SurfaceGetNormal(x, z);
    vector angles = normal.VectorToAngles();
    angles[1] = angles[1] + 270; // This fixes rotation of item so it stands vertically. Feel free to change, but fix existing use cases.
    //Hack because setorientation and similar functions break and flip stuff upside down when using exactly this vector \_()_/ (note: happens when surface is flat)
    if (angles == "0 540 0")
      angles = "0 0 0";
    return angles;
  }
References GetGame(), and x.
GetTickTime()
proto native float CGame::GetTickTime () private
Returns current time from start of the game.
Returns
time in seconds
GetTime()
proto int CGame::GetTime () protected
returns mission time in milliseconds
GetTimerQueue() [1/2]
override TimerQueue CGame::GetTimerQueue (int call_category) inline private
Definition at line 1144 of file DayZGame.c.
  {
    return m_timerQueue[call_category];
  }
References m_timerQueue.
Referenced by OnUpdate().
GetTimerQueue() [2/2]
TimerQueue CGame::GetTimerQueue (int call_category) inline protected
Returns TimerQueue for certain category
Parameters
call_category call category, valid values are:
CALL_CATEGORY_SYSTEM - calls & timers in this queue are processed every time without any restrictions
CALL_CATEGORY_GUI - calls & timers in this queue are processed when GUI is enabled (even during pase game)
CALL_CATEGORY_GAMEPLAY - calls & timers in this queue are processed only during mission, when game is not paused
Definition at line 1348 of file Game.c.
{}
GetUIManager()
proto native UIManager CGame::GetUIManager () private
Referenced by CheckDialogs(), Connect(), DisconnectSessionEx(), EnterLoginQueue(), EnterLoginTime(), GamepadCheck(), IsInventoryOpen(), LoadProgressUpdate(), OnLoginTimeEvent(), OnRespawnEvent(), RefreshMouseCursorVisibility(), SelectGamepad(), SetDatabaseID(), UpdateInputDeviceDisconnectWarning(), and UpdateLoginQueue().
GetUpdateQueue() [1/2]
override ScriptInvoker CGame::GetUpdateQueue (int call_category) inline private
Definition at line 1134 of file DayZGame.c.
  {
    return m_updateQueue[call_category];
  }
Referenced by OnUpdate().
GetUpdateQueue() [2/2]
ScriptInvoker CGame::GetUpdateQueue (int call_category) inline protected
Definition at line 1338 of file Game.c.
{}
GetUserFOV()
float CGame::GetUserFOV () inline protected
Definition at line 3346 of file DayZGame.c.
  {
    return m_UserFOV;
  }
References m_UserFOV.
Referenced by GetFOVByZoomType().
GetUserFOVFromConfig()
static float CGame::GetUserFOVFromConfig () inline static protected
Definition at line 3351 of file DayZGame.c.
  {
    GameOptions gameOptions = new GameOptions;
    NumericOptionsAccess noa;
    if (gameOptions && Class.CastTo(noa, gameOptions.GetOptionByType(OptionAccessType.AT_OPTIONS_FIELD_OF_VIEW)))
      return noa.ReadValue();
    return 1.0;
  }
References Class::CastTo().
Referenced by DeferredInit(), and SelectGamepad().
GetUserManager()
proto native BiosUserManager CGame::GetUserManager () protected
Referenced by ConnectLaunch(), GamepadCheck(), JoinLaunch(), MainMenuLaunch(), MissionLaunch(), OnEvent(), OnLoginTimeEvent(), SelectGamepad(), and SelectUser().
GetVersion()
proto void CGame::GetVersion (out string version) private
GetVoiceLevel()
proto native int CGame::GetVoiceLevel (Object player = null) private
Get voice level of VoN (on both client and server) (VoiceLevelWhisper = 0, VoiceLevelNormal = 1, VoiceLevelShout = 2)
GetWaterDepth()
proto native float CGame::GetWaterDepth (vector posWS) protected
GetWeather()
proto native Weather CGame::GetWeather () protected
Returns weather controller object.
GetWorkspace()
proto native WorkspaceWidget CGame::GetWorkspace () private
Referenced by CreateTitleScreen().
GetWorld()
proto native World CGame::GetWorld () private
Referenced by OnEvent().
GetWorldDirectionFromScreen()
proto native vector CGame::GetWorldDirectionFromScreen (vector world_pos) private
Transforms position in world to position in screen in pixels as x, y component of vector, z parameter represents distance between camera and world_pos.
GetWorldName() [1/2]
string CGame::GetWorldName () inline private
Definition at line 799 of file Game.c.
  {
    string world_name;
    g_Game.GetWorldName(world_name);
    return world_name;
  }
References g_Game.
GetWorldName() [2/2]
proto void CGame::GetWorldName (out string world_name) private
GlobalsInit()
void CGame::GlobalsInit () inline private
Definition at line 1059 of file DayZGame.c.
  {
    if (GetCEApi())
    {
      m_IsWorldWetTempUpdateEnabled = (GetCEApi().GetCEGlobalInt("WorldWetTempUpdate") == 1);
      m_FoodDecayModifier = GetCEApi().GetCEGlobalFloat("FoodDecay");
      //check for legacy INT format, if value == float.MIN when read as FLOAT, it is of type INT, so we read it as such below
      if (m_FoodDecayModifier == float.MIN)
        m_FoodDecayModifier = GetCEApi().GetCEGlobalInt("FoodDecay");
    }
    //we need to perform the load here as some objects behaving correctly after spawn is dependent on CE being initialized before spawning them
    ObjectSpawnerHandler.OnGameplayDataHandlerLoad();
  }
References GetCEApi(), MIN, and ObjectSpawnerHandler::OnGameplayDataHandlerLoad().
GoBuyWorldDLC()
proto native bool CGame::GoBuyWorldDLC (string sWorldName) private
HasInventoryJunctureDestination()
proto native bool CGame::HasInventoryJunctureDestination (Man player, notnull InventoryLocation dst) private
HasInventoryJunctureItem()
proto native bool CGame::HasInventoryJunctureItem (notnull EntityAI item) private
InitCharacterMenuDataInfo()
void CGame::InitCharacterMenuDataInfo (int menudata_count) inline protected
Definition at line 3310 of file DayZGame.c.
  {
    m_OriginalCharactersCount = menudata_count;
  }
InitDamageEffects()
proto native void CGame::InitDamageEffects (Object effect) protected
Initialization of damage effects.
InitNotifications()
void CGame::InitNotifications () inline protected
Definition at line 1958 of file DayZGame.c.
  {
    NotificationSystem.InitInstance();
    m_Notifications = new NotificationUI();
  }
References NotificationSystem::InitInstance().
Referenced by OnInitialize().
IsAimLogEnabled()
bool CGame::IsAimLogEnabled () inline private
Definition at line 1244 of file DayZGame.c.
  {
    return m_AimLoggingEnabled;
  }
References m_AimLoggingEnabled.
IsAppActive()
proto native bool CGame::IsAppActive () private
Returns if the application is focused on PC, returns true always on console.
Referenced by RefreshMouseCursorVisibility().
IsBoxColliding()
proto native bool CGame::IsBoxColliding (vector center, vector orientation, vector edgeLength, array< Object > excludeObjects, array< Object > collidedObjects = NULL) protected
Finds all objects that are in choosen oriented bounding box (OBB)
Parameters
center vector, center of OBB
orientation vector, direction (front vector), used for calculation of OBB rotation
edgeLength vector, sizes of whole box
excludeObjects array<Object>, objects that should be excluded from collision check
collidedObjects array<Object>, out parameter, objects that collided with OBB
Returns
bool, true if at least one object collided with OBB, false otherwise
Note
Object that doesn't have collision geometry will be ignored, as this only uses geometry
vector pos = GetPosition();
vector orientation = GetOrientation();
vector size = "10 4 8";
array<Object> excluded_objects = new array<Object>;
excluded_objects.Insert(this);
array<Object> nearby_objects = new array<Object>;
if(GetGame().IsBoxColliding(pos, orientation, size, excluded_objects, nearby_objects))
{
  for (int i = 0, c = nearby_objects.Count(); i < c; ++i)
  {
    PrintString("object " + i.ToString());
  }
}
IsBoxCollidingGeometry()
proto native bool CGame::IsBoxCollidingGeometry (vector center, vector orientation, vector edgeLength, int iPrimaryType, int iSecondaryType, array< Object > excludeObjects, array< Object > collidedObjects = NULL) protected
Finds all objects with geometry iType that are in choosen oriented bounding box (OBB)
Parameters
center vector, center of OBB
orientation vector, direction (front vector), used for calculation of OBB rotation
edgeLength vector, sizes of whole box
iPrimaryType int, type of intersection, possible values ObjIntersectFire(0), ObjIntersectView(1), ObjIntersectGeom(2), ObjIntersectIFire(3), ObjIntersectNone(4)
iSecondaryType int, type of intersection, possible values ObjIntersectFire(0), ObjIntersectView(1), ObjIntersectGeom(2), ObjIntersectIFire(3), ObjIntersectNone(4)
excludeObjects array<Object>, objects that should be excluded from collision check
collidedObjects array<Object>, out parameter, objects that collided with OBB
Returns
bool, true if at least one object collided with OBB, false otherwise
vector pos = GetPosition();
vector orientation = GetOrientation();
vector size = "10 4 8";
array<Object> excluded_objects = new array<Object>;
excluded_objects.Insert(this);
array<Object> nearby_objects = new array<Object>;
if(GetGame().IsBoxCollidingGeometry(pos, orientation, size, ObjIntersectView, ObjIntersectGeom, excluded_objects, nearby_objects))
{
  for (int i = 0, c = nearby_objects.Count(); i < c; ++i)
  {
    PrintString("object " + i.ToString());
  }
}
IsBoxCollidingGeometryProxy()
proto native bool CGame::IsBoxCollidingGeometryProxy (notnull BoxCollidingParams params, array< Object > excludeObjects, array< ref BoxCollidingResult > collidedObjects = NULL) protected
IsClient()
proto native bool CGame::IsClient () protected
IsConnecting()
bool CGame::IsConnecting () inline protected
Definition at line 3031 of file DayZGame.c.
  {
    return m_IsConnecting;
  }
References m_IsConnecting.
IsDebug()
proto native bool CGame::IsDebug () protected
IsDebugMonitor()
bool CGame::IsDebugMonitor () inline protected
Definition at line 1026 of file Game.c.
  {
    return IsServer() && m_DebugMonitorEnabled;
  }
References IsServer(), and m_DebugMonitorEnabled.
IsDedicatedServer()
proto native bool CGame::IsDedicatedServer () protected
Robust check which is preferred than the above, as it is valid much sooner.
Note
You may want to use #ifdef SERVER instead for slight performance gain...
Referenced by CGame().
IsDigitalCopy()
static bool CGame::IsDigitalCopy () inline static protected
Definition at line 1010 of file Game.c.
  {
    return OnlineServices.IsGameActive(false);
  }
References OnlineServices::IsGameActive().
IsFoodDecayEnabled()
bool CGame::IsFoodDecayEnabled () inline protected
Definition at line 3439 of file DayZGame.c.
  {
    return (GetFoodDecayModifier() != 0);
  }
References GetFoodDecayModifier().
IsInPartyChat()
proto native bool CGame::IsInPartyChat () private
Returns whether user is currently in a voice party (currently only supported on xbox)
IsInventoryOpen() [1/2]
override bool CGame::IsInventoryOpen () inline private
Definition at line 1280 of file DayZGame.c.
  {
#ifndef NO_GUI
    if (GetUIManager().FindMenu(MENU_INVENTORY) != NULL)
      return true;
#endif
    return false;
  }
References GetUIManager(), and MENU_INVENTORY.
IsInventoryOpen() [2/2]
bool CGame::IsInventoryOpen () inline protected
Definition at line 1364 of file Game.c.
  {
  }
IsKindOf()
bool CGame::IsKindOf (string cfg_class_name, string cfg_parent_name) inline protected
Returns is class name inherited from parent class name.
Parameters
cfg_class_name Config Class name ("Animal_CervusElaphus")
cfg_parent_name Parent Config Class name ("DZ_LightAI")
Returns
bool is class name inherited from parent class name
bool is_kind = GetGame().IsKindOf("Animal_CervusElaphus", "DZ_LightAI");
PrintString(ToString(is_kind));
>> 1
Definition at line 1239 of file Game.c.
  {
    TStringArray full_path = new TStringArray;
    ConfigGetFullPath("CfgVehicles " + cfg_class_name, full_path);
    if (full_path.Count() == 0)
      ConfigGetFullPath("CfgAmmo " + cfg_class_name, full_path);
    if (full_path.Count() == 0)
      ConfigGetFullPath("CfgMagazines " + cfg_class_name, full_path);
    if (full_path.Count() == 0)
      ConfigGetFullPath("cfgWeapons " + cfg_class_name, full_path);
    if (full_path.Count() == 0)
      ConfigGetFullPath("CfgNonAIVehicles " + cfg_class_name, full_path);
    cfg_parent_name.ToLower();
    for (int i = 0; i < full_path.Count(); i++)
    {
      string tmp = full_path.Get(i);
      tmp.ToLower();
      if (tmp == cfg_parent_name)
        return true;
    }
    return false;
  }
References ConfigGetFullPath().
Referenced by DayZGame().
IsLeftCtrlDown()
bool CGame::IsLeftCtrlDown () inline protected
Definition at line 2562 of file DayZGame.c.
  {
    return m_IsCtrlHolding;
  }
References m_IsCtrlHolding.
IsLoading()
bool CGame::IsLoading () inline protected
Definition at line 3037 of file DayZGame.c.
  {
    return m_loading && m_loading.IsLoading();
  }
Referenced by LoadingHide().
IsMicCapturing()
proto native bool CGame::IsMicCapturing () private
Returns whether mic is currently capturing audio from user.
IsMissionMainMenu()
bool CGame::IsMissionMainMenu () inline protected
Returns true when current mission is Main Menu.
Definition at line 1374 of file Game.c.
  {
    return (g_Game.GetMissionState() == DayZGame.MISSION_STATE_MAINMENU);
  }
References DayZGame(), and g_Game.
IsMultiplayer()
proto native bool CGame::IsMultiplayer () protected
Referenced by OnUpdate().
IsNewCharacter()
bool CGame::IsNewCharacter () inline protected
Definition at line 3330 of file DayZGame.c.
  {
    return m_IsNewCharacter;
  }
References m_IsNewCharacter.
IsObjectAccesible()
proto native bool CGame::IsObjectAccesible (EntityAI item, Man player) private
returns true if player can access item's cargo/attachments (check only distance)
IsPhysicsExtrapolationEnabled()
proto native bool CGame::IsPhysicsExtrapolationEnabled () private
If physics extrapolation is enabled, always true on retail release builds.
IsServer()
proto native bool CGame::IsServer () protected
Referenced by CloseCombatEffects(), ExplosionEffectsEx(), FirearmEffects(), and IsDebugMonitor().
IsStressTest()
bool CGame::IsStressTest () inline private
Definition at line 1239 of file DayZGame.c.
  {
    return m_IsStressTest;
  }
References m_IsStressTest.
IsSurfaceDigable()
bool CGame::IsSurfaceDigable (string surface) inline protected
Checks if the surface is digable.
Definition at line 1088 of file Game.c.
  {
    return ConfigGetInt("CfgSurfaces " + surface + " isDigable");
  }
References ConfigGetInt().
IsSurfaceFertile()
bool CGame::IsSurfaceFertile (string surface) inline protected
Checks if the surface is fertile.
Definition at line 1094 of file Game.c.
  {
    return ConfigGetInt("CfgSurfaces " + surface + " isFertile");
  }
References ConfigGetInt().
IsVisited()
bool CGame::IsVisited (string ip, int port) inline protected
Definition at line 2437 of file DayZGame.c.
  {
    string uid = ip + ":" + port;
    int index = m_Visited.Find(uid);
    return (index >= 0);
  }
IsWorldWetTempUpdateEnabled()
bool CGame::IsWorldWetTempUpdateEnabled () inline protected
Definition at line 3434 of file DayZGame.c.
  {
    return m_IsWorldWetTempUpdateEnabled;
  }
References m_IsWorldWetTempUpdateEnabled.
JoinLaunch()
void CGame::JoinLaunch () inline protected
Definition at line 2048 of file DayZGame.c.
  {
    SetGameState(DayZGameState.JOIN);
    SetLoadState(DayZLoadState.JOIN_START);
#ifdef PLATFORM_CONSOLE
    string join_param;
    if (GetCLIParam("join", join_param))
    {
      BiosUserManager user_manager = GetUserManager();
      user_manager.ParseJoinAsync(join_param);
    }
#endif
  }
References GetCLIParam(), GetUserManager(), SetGameState(), and SetLoadState().
Referenced by OnInitialize().
ListAvailableCharacters() [1/2]
override TStringArray CGame::ListAvailableCharacters () inline protected
Definition at line 3089 of file DayZGame.c.
  {
    return m_CharClassNames;
  }
References m_CharClassNames.
ListAvailableCharacters() [2/2]
TStringArray CGame::ListAvailableCharacters () inline protected
outputs array of all valid survivor class names
Definition at line 1362 of file Game.c.
{}
LoadingHide()
void CGame::LoadingHide (bool force = false) inline protected
Definition at line 3057 of file DayZGame.c.
  {
#ifndef NO_GUI
    m_loading.Hide(force);
    // turn the lights back on
    PPEManagerStatic.GetPPEManager().StopAllEffects();
#ifdef PLATFORM_CONSOLE
    if (!IsLoading())
    {
      if (m_LoadState != DayZLoadState.MAIN_MENU_START && m_LoadState != DayZLoadState.MAIN_MENU_USER_SELECT)
        UpdateInputDeviceDisconnectWarning();
    }
#endif
#endif
  }
References PPEManagerStatic::GetPPEManager(), IsLoading(), and UpdateInputDeviceDisconnectWarning().
Referenced by OnEvent().
LoadingShow()
void CGame::LoadingShow () inline protected
Definition at line 3049 of file DayZGame.c.
  {
#ifndef NO_GUI
    m_loading.ShowEx(this);
#endif
  }
Referenced by OnEvent().
LoadProgressUpdate()
void CGame::LoadProgressUpdate (int progressState, float progress, string title) inline protected
Definition at line 1861 of file DayZGame.c.
  {
#ifndef NO_GUI
    switch (progressState)
    {
    case PROGRESS_START:
    {
#ifndef NO_GUI
      // get out of the black screen immediately
      GetUIManager().ScreenFadeOut(0);
#endif
      m_loading.Inc();
      m_loading.SetTitle(title);
      if (m_loading.m_HintPanel)
        m_loading.m_HintPanel.ShowRandomPage();
    }
    break;
    case PROGRESS_FINISH:
    {
      m_loading.Dec();
    }
    break;
    case PROGRESS_PROGRESS:
    {
      m_loading.SetProgress(progress);
    }
    break;
    case PROGRESS_UPDATE:
    {
      m_loading.SetProgress(0);
    }
    break;
    }
#endif
  }
References GetUIManager(), PROGRESS_FINISH, PROGRESS_PROGRESS, PROGRESS_START, and PROGRESS_UPDATE.
Referenced by OnEvent().
LoadVersion()
proto native int CGame::LoadVersion () private
Returns actual storage version - loading.
LoginTimeCountdown()
void CGame::LoginTimeCountdown () inline protected
Definition at line 1765 of file DayZGame.c.
  {
    if (m_LoginTime > 0)
    {
      if (m_LoginTimeScreen)
        m_LoginTimeScreen.SetTime(m_LoginTime);
      m_LoginTime--;
    }
    else
    {
      // stop the call loop
      CancelLoginTimeCountdown();
    }
  }
References CancelLoginTimeCountdown().
LogoutRequestCancel()
proto native void CGame::LogoutRequestCancel () protected
LogoutRequestTime()
proto native void CGame::LogoutRequestTime () protected
Logout methods.
MainMenuLaunch()
void CGame::MainMenuLaunch () inline protected
Definition at line 2096 of file DayZGame.c.
  {
#ifdef PLATFORM_WINDOWS
    BiosUserManager user_manager = GetUserManager();
    if (user_manager)
    {
      if (user_manager.GetTitleInitiator())
        user_manager.SelectUserEx(user_manager.GetTitleInitiator());
    }
#endif
    SetGameState(DayZGameState.MAIN_MENU);
    SetLoadState(DayZLoadState.MAIN_MENU_START);
    StartRandomCutscene(GetMainMenuWorld());
    DeleteTitleScreen();
  }
References DeleteTitleScreen(), GetMainMenuWorld(), GetUserManager(), SetGameState(), SetLoadState(), and StartRandomCutscene().
Referenced by DisconnectSessionEx(), and OnInitialize().
MissionLaunch()
void CGame::MissionLaunch () inline protected
Definition at line 2113 of file DayZGame.c.
  {
    BiosUserManager user_manager = GetUserManager();
    if (user_manager)
    {
      if (user_manager.GetTitleInitiator())
        user_manager.SelectUserEx(user_manager.GetTitleInitiator());
    }
    SetGameState(DayZGameState.IN_GAME);
    SetLoadState(DayZLoadState.MISSION_START);
#ifndef PLATFORM_WINDOWS
#ifdef PLATFORM_CONSOLE
#ifndef DEVELOPER
    CreateTitleScreen();
    GamepadCheck();
    return;
#endif
#endif
#endif
    string mission;
    GetCLIParam("mission", mission);
    PlayMission(mission);
  }
References CreateTitleScreen(), GamepadCheck(), GetCLIParam(), GetUserManager(), mission, PlayMission(), SetGameState(), and SetLoadState().
Referenced by OnInitialize().
MuteAllPlayers()
proto native void CGame::MuteAllPlayers (string listenerId, bool mute) private
Mute all players for listenerId.
Parameters
listenerId uid of player
mute true, if player can not listen anybody. Otherwise false.
MutePlayer()
proto native void CGame::MutePlayer (string muteUID, string playerUID, bool mute) private
Mutes voice of source player to target player.
Parameters
muteUID uid of player you want to mute
playerUID uid of player that (doesnt't) want to hear muteUID
Referenced by OnRPC().
NightVissionLightParams()
proto native void CGame::NightVissionLightParams (float lightIntensityMul, float noiseIntensity) protected
set night vission parameters (set to zero when to disable it)
Parameters
lightIntensityMul multiplicator of lights intensity
noiseIntensity intensity of noise PP
ObjectDelete()
proto native void CGame::ObjectDelete (Object obj) private
ObjectDeleteOnClient()
proto native void CGame::ObjectDeleteOnClient (Object obj) private
ObjectGetDisplayName()
proto void CGame::ObjectGetDisplayName (Object obj, out string name) private
ObjectGetSelectionPosition()
proto native vector CGame::ObjectGetSelectionPosition (Object obj, string name) private
ObjectGetSelectionPositionLS()
proto native vector CGame::ObjectGetSelectionPositionLS (Object obj, string name) private
ObjectGetSelectionPositionMS()
proto native vector CGame::ObjectGetSelectionPositionMS (Object obj, string name) private
ObjectGetSelectionPositionWS()
proto native vector CGame::ObjectGetSelectionPositionWS (Object obj, string name) private
ObjectGetType()
proto void CGame::ObjectGetType (Object obj, out string type) private
ObjectIsKindOf()
bool CGame::ObjectIsKindOf (Object object, string cfg_parent_name) inline protected
Returns is object inherited from parent class name.
Parameters
object Object
cfg_parent_name Parent Config Class name ("DZ_LightAI")
Returns
bool is object inherited from parent class name
bool is_kind = GetGame().IsKindOf(my_animal, "DZ_LightAI");
PrintString(ToString(is_kind));
>> 1
Definition at line 1281 of file Game.c.
  {
    TStringArray full_path = new TStringArray;
    ConfigGetObjectFullPath(object, full_path);
    cfg_parent_name.ToLower();
    for (int i = 0; i < full_path.Count(); i++)
    {
      string tmp = full_path.Get(i);
      tmp.ToLower();
      if (tmp == cfg_parent_name)
        return true;
    }
    return false;
  }
References ConfigGetObjectFullPath().
ObjectModelToWorld()
proto native vector CGame::ObjectModelToWorld (Object obj, vector modelPos) private
ObjectRelease()
proto native int CGame::ObjectRelease (Object obj) private
RemoteObjectTreeCreate - postponed registration of network object tree (and creation of remote objects). do not use if not sure what you do.
ObjectWorldToModel()
proto native vector CGame::ObjectWorldToModel (Object obj, vector worldPos) private
OnActivateMessage() [1/2]
override void CGame::OnActivateMessage () inline protected
Definition at line 1909 of file DayZGame.c.
  {
    RefreshMouseCursorVisibility();
  }
References RefreshMouseCursorVisibility().
OnActivateMessage() [2/2]
void CGame::OnActivateMessage () inline private
Called when recieving focus (windows)
Definition at line 107 of file Game.c.
  {
  }
OnAfterCreate() [1/2]
override void CGame::OnAfterCreate () inline protected
Definition at line 1903 of file DayZGame.c.
  {
    Math.Randomize(-1);
  }
References Math::Randomize().
OnAfterCreate() [2/2]
void CGame::OnAfterCreate () inline private
Called after creating of CGame instance.
Definition at line 100 of file Game.c.
  {
  }
OnConnectivityStatChange()
bool CGame::OnConnectivityStatChange (EConnectivityStatType type, EConnectivityStatLevel newLevel, EConnectivityStatLevel oldLevel) inline protected
Definition at line 1641 of file DayZGame.c.
  {
    if (!GetGame() || !GetGame().GetMission())
      return false;
    Hud hud = GetGame().GetMission().GetHud();
    if (!hud)
      return false;
    hud.SetConnectivityStatIcon(type, newLevel);
    return true;
  }
References GetGame(), and GetMission().
Referenced by SetConnectivityStatState().
OnDeactivateMessage() [1/2]
override void CGame::OnDeactivateMessage () inline protected
Definition at line 1915 of file DayZGame.c.
  {
    RefreshMouseCursorVisibility();
  }
References RefreshMouseCursorVisibility().
OnDeactivateMessage() [2/2]
void CGame::OnDeactivateMessage () inline private
Called when loosing focus (windows)
Definition at line 114 of file Game.c.
  {
  }
OnDeviceReset() [1/2]
override void CGame::OnDeviceReset () inline protected
Definition at line 2634 of file DayZGame.c.
  {
    m_IsCtrlHolding = false;
    m_IsWinHolding = false;
    m_IsLeftAltHolding = false;
    m_IsRightAltHolding = false;
  }
OnDeviceReset() [2/2]
void CGame::OnDeviceReset () inline private
Called when inputs is not possible (Steam overlay active or something), all internal script variables should be reset here!
Definition at line 129 of file Game.c.
  {
  }
OnEvent() [1/2]
override void CGame::OnEvent (EventType eventTypeId, Param params) inline private
Definition at line 1359 of file DayZGame.c.
  {
    string address;
    int port;
    int high, low;
    switch (eventTypeId)
    {
    case StartupEventTypeID:
    {
#ifndef SERVER
      // Just call it, to create the global instance if it doesn't exist yet
      ParticleManager.GetInstance();
#endif
      break;
    }
    case MPSessionStartEventTypeID:
    {
#ifndef SERVER
      ClearConnectivityStates();
#endif
      m_FirstConnect = true;
      ClientData.ResetClientData();
      break;
    }
    case MPSessionEndEventTypeID:
    {
      LoadingHide();
      CancelLoginTimeCountdown();
      SetConnecting(false);
      SetGameState(DayZGameState.MAIN_MENU);
      m_FirstConnect = true;
#ifdef PLATFORM_CONSOLE
      if (GetUserManager().GetSelectedUser())
      {
        OnlineServices.LeaveGameplaySession();
        OnlineServices.ClearCurrentServerInfo();
        if (GetGameState() == DayZGameState.IN_GAME)
          SetLoadState(DayZLoadState.MAIN_MENU_START);
      }
      m_Notifications.ClearVoiceNotifications();
#endif
      // analytics - disconnected player
      StatsEventDisconnectedData discData = new StatsEventDisconnectedData();
      discData.m_CharacterId = g_Game.GetDatabaseID();
      discData.m_Reason = "quit";
      Analytics.PlayerDisconnected(discData);
      break;
    }
    case MPSessionFailEventTypeID:
    {
      CancelLoginQueue();
      LoadingHide(true);
      SetConnecting(false);
      ProgressAsync.DestroyAllPendingProgresses();
      if (GetGameState() == DayZGameState.CONNECTING)
        SetGameState(DayZGameState.MAIN_MENU);
      break;
    }
    case MPSessionPlayerReadyEventTypeID:
    {
      LoadingHide(true);
      ProgressAsync.DestroyAllPendingProgresses();
      SetGameState(DayZGameState.IN_GAME);
      // analytics - spawned
      StatsEventSpawnedData spawnData = new StatsEventSpawnedData();
      spawnData.m_CharacterId = g_Game.GetDatabaseID();
      spawnData.m_Lifetime = 0;
      spawnData.m_Position = vector.Zero;
      if (GetPlayer())
        spawnData.m_Position = GetPlayer().GetPosition();
      spawnData.m_DaytimeHour = 0;
      spawnData.m_Population = 0;
      Analytics.PlayerSpawned(spawnData);
#ifdef PLATFORM_CONSOLE
      m_Notifications.ClearVoiceNotifications();
      OnlineServices.SetMultiplayState(true);
#endif
      if (m_FirstConnect)
      {
        m_FirstConnect = false;
        if (GetHostAddress(address, port))
          AddVisitedServer(address, port);
#ifdef PLATFORM_CONSOLE
#ifndef PLATFORM_WINDOWS // if app is not on Windows with -XBOX parameter
        if (null != GetUserManager().GetSelectedUser())
        {
          OnlineServices.EnterGameplaySession();
          OnlineServices.LoadVoicePrivilege();
        }
#endif
#endif
      }
      UpdateInputDeviceDisconnectWarning();
      break;
    }
    case MPConnectionLostEventTypeID:
    {
      MPConnectionLostEventParams conLost_params;
      if (Class.CastTo(conLost_params, params))
      {
        int duration = conLost_params.param1;
        OnMPConnectionLostEvent(duration);
      }
      break;
    }
    case WorldCleaupEventTypeID:
    {
      LoadingShow();
      break;
    }
    case DialogQueuedEventTypeID:
    {
      GetCallQueue(CALL_CATEGORY_SYSTEM).Call(g_Game.CheckDialogs);
      break;
    }
    case ChatMessageEventTypeID:
    {
      ChatMessageEventParams chat_params;
      if (Class.CastTo(chat_params, params))
      {
      }
      break;
    }
    case ProgressEventTypeID:
    {
      ProgressEventParams prog_params;
      if (Class.CastTo(prog_params, params))
        LoadProgressUpdate(prog_params.param1, prog_params.param2, prog_params.param3);
      break;
    }
    case LoginTimeEventTypeID:
    {
      LoginTimeEventParams loginTimeParams;
      if (Class.CastTo(loginTimeParams, params))
        OnLoginTimeEvent(loginTimeParams.param1);
      break;
    }
    case RespawnEventTypeID:
    {
      RespawnEventParams respawnParams;
      if (Class.CastTo(respawnParams, params))
        OnRespawnEvent(respawnParams.param1);
      break;
    }
    case PreloadEventTypeID:
    {
      PreloadEventParams preloadParams;
      if (Class.CastTo(preloadParams, params))
        OnPreloadEvent(preloadParams.param1);
      break;
    }
    case LogoutEventTypeID:
    {
      LogoutEventParams logoutParams;
      if (Class.CastTo(logoutParams, params))
        GetCallQueue(CALL_CATEGORY_GUI).Call(GetMission().StartLogoutMenu, logoutParams.param1);
      break;
    }
    case SelectedUserChangedEventTypeID:
    {
      OnlineServices.Init();
      break;
    }
    case LoginStatusEventTypeID:
    {
      LoginStatusEventParams loginStatusParams;
      Class.CastTo(loginStatusParams, params);
      string msg1 = loginStatusParams.param1;
      string msg2 = loginStatusParams.param2;
      string finalMsg;
      // write either to login time screen or loading screen
      if (m_LoginTimeScreen)
      {
        finalMsg = msg1;
        // login time screen supports two lines
        if (msg2.Length() > 0)
          finalMsg += "\n" + msg2;
        m_LoginTimeScreen.SetStatus(finalMsg);
      }
      else if (m_loading)
      {
        // loading only one line, but it's a long one
        finalMsg = msg1 + " " + msg2;
        m_loading.SetStatus(finalMsg);
      }
      break;
    }
    case ConnectingStartEventTypeID:
    {
      g_Game.SetGameState(DayZGameState.CONNECTING);
      SetConnecting(true);
      break;
    }
    case ConnectingAbortEventTypeID:
    {
      g_Game.SetGameState(DayZGameState.MAIN_MENU);
      SetConnecting(false);
      if (m_ConnectFromJoin)
      {
        m_ConnectFromJoin = false;
        AbortMission();
      }
      break;
    }
    case DLCOwnerShipFailedEventTypeID:
    {
      DLCOwnerShipFailedParams dlcParams;
      if (Class.CastTo(dlcParams, params))
        Print("### DLC Ownership failed !!! Map: " + dlcParams.param1);
      break;
    }
    case ConnectivityStatsUpdatedEventTypeID:
    {
      ConnectivityStatsUpdatedEventParams connectivityStatsParams;
      if (Class.CastTo(connectivityStatsParams, params))
      {
        PlayerIdentity playerIdentity = connectivityStatsParams.param1;
        int pingAvg = playerIdentity.GetPingAvg();
        if (pingAvg < GetWorld().GetPingWarningThreshold())
          SetConnectivityStatState(EConnectivityStatType.PING, EConnectivityStatLevel.OFF);
        else if (pingAvg < GetWorld().GetPingCriticalThreshold())
          SetConnectivityStatState(EConnectivityStatType.PING, EConnectivityStatLevel.LEVEL1);
        else
          SetConnectivityStatState(EConnectivityStatType.PING, EConnectivityStatLevel.LEVEL2);
      }
      break;
    }
    case ServerFpsStatsUpdatedEventTypeID:
    {
      ServerFpsStatsUpdatedEventParams serverFpsStatsParams;
      if (Class.CastTo(serverFpsStatsParams, params))
      {
#ifdef DIAG_DEVELOPER
        m_ServerFpsStatsParams = serverFpsStatsParams;
#endif
        float fps = serverFpsStatsParams.param1;
        if (fps > GetWorld().GetServerFpsWarningThreshold())
          SetConnectivityStatState(EConnectivityStatType.SERVER_PERF, EConnectivityStatLevel.OFF);
        else if (fps > GetWorld().GetServerFpsCriticalThreshold())
          SetConnectivityStatState(EConnectivityStatType.SERVER_PERF, EConnectivityStatLevel.LEVEL1);
        else
          SetConnectivityStatState(EConnectivityStatType.SERVER_PERF, EConnectivityStatLevel.LEVEL2);
      }
      break;
    }
    }
    VONManager.GetInstance().OnEvent(eventTypeId, params);
    Mission mission = GetMission();
    if (mission)
      mission.OnEvent(eventTypeId, params);
    ErrorModuleHandler emh = ErrorModuleHandler.GetInstance();
    if (emh)
      emh.OnEvent(eventTypeId, params);
  }
References AbortMission(), AddVisitedServer(), CALL_CATEGORY_GUI, CALL_CATEGORY_SYSTEM, CancelLoginQueue(), CancelLoginTimeCountdown(), Class::CastTo(), ChatMessageEventTypeID, ClearConnectivityStates(), OnlineServices::ClearCurrentServerInfo(), ConnectingAbortEventTypeID, ConnectingStartEventTypeID, ConnectivityStatsUpdatedEventTypeID, ProgressAsync::DestroyAllPendingProgresses(), DialogQueuedEventTypeID, DLCOwnerShipFailedEventTypeID, OnlineServices::EnterGameplaySession(), g_Game, GetCallQueue(), GetGameState(), GetHostAddress(), ErrorModuleHandler::GetInstance(), VONManager::GetInstance(), GetMission(), GetPlayer(), GetUserManager(), GetWorld(), OnlineServices::Init(), OnlineServices::LeaveGameplaySession(), LoadingHide(), LoadingShow(), LoadProgressUpdate(), OnlineServices::LoadVoicePrivilege(), LoginStatusEventTypeID, LoginTimeEventTypeID, LogoutEventTypeID, mission, MPConnectionLostEventTypeID, MPSessionEndEventTypeID, MPSessionFailEventTypeID, MPSessionPlayerReadyEventTypeID, MPSessionStartEventTypeID, Mission::OnEvent(), OnLoginTimeEvent(), OnMPConnectionLostEvent(), OnPreloadEvent(), OnRespawnEvent(), ParticleManager(), Analytics::PlayerDisconnected(), Analytics::PlayerSpawned(), PreloadEventTypeID, Print(), ProgressEventTypeID, ClientData::ResetClientData(), RespawnEventTypeID, SelectedUserChangedEventTypeID, ServerFpsStatsUpdatedEventTypeID, SetConnecting(), SetConnectivityStatState(), SetGameState(), SetLoadState(), OnlineServices::SetMultiplayState(), StartupEventTypeID, UpdateInputDeviceDisconnectWarning(), WorldCleaupEventTypeID, and vector::Zero.
OnEvent() [2/2]
void CGame::OnEvent (EventType eventTypeId, Param params) inline private
Called when some system event occur.
Parameters
eventTypeId event type.
params Param object, cast to specific param class to get parameters for particular event.
Definition at line 82 of file Game.c.
  {
  }
OnGameplayDataHandlerLoad()
void CGame::OnGameplayDataHandlerLoad () inline private
Definition at line 1155 of file DayZGame.c.
  {
  }
OnInitialize() [1/2]
override bool CGame::OnInitialize () inline protected
Definition at line 1921 of file DayZGame.c.
  {
    ParticleList.PreloadParticles();
    RegisterProfilesOptions();
    SetHudBrightness(GetHUDBrightnessSetting());
    InitNotifications();
    m_Visited = new TStringArray;
    GetProfileStringList("SB_Visited", m_Visited);
    if (GetLoadState() == DayZLoadState.UNDEFINED)
    {
      string param;
      if (GetCLIParam("join", param))
      {
        JoinLaunch();
#ifndef PLATFORM_PS4
        CreateTitleScreen();
#endif
      }
      else if (GetCLIParam("connect", param))
        ConnectLaunch();
      else if (GetCLIParam("mission", param))
        MissionLaunch();
      else if (GetCLIParam("party", param))
        PartyLaunch();
      else
        MainMenuLaunch();
      return true;
    }
    return false;
  }
References ConnectLaunch(), CreateTitleScreen(), GetCLIParam(), GetHUDBrightnessSetting(), GetLoadState(), GetProfileStringList(), InitNotifications(), JoinLaunch(), MainMenuLaunch(), MissionLaunch(), PartyLaunch(), ParticleList::PreloadParticles(), RegisterProfilesOptions(), and SetHudBrightness().
OnInitialize() [2/2]
bool CGame::OnInitialize () inline private
Called once before game update loop starts, ret value indicates if init was done in scripts, otherwise it is done in the engine.
Definition at line 121 of file Game.c.
  {
    return false;
  }
OnKeyPress() [1/2]
override void CGame::OnKeyPress (int key) inline protected
Definition at line 2568 of file DayZGame.c.
  {
    if (key == KeyCode.KC_LCONTROL)
      m_IsCtrlHolding = true;
    if (key == KeyCode.KC_LMENU)
      m_IsLeftAltHolding = true;
    if (key == KeyCode.KC_RMENU)
      m_IsRightAltHolding = true;
    if (m_keyboard_handler)
      m_keyboard_handler.OnKeyDown(NULL, 0, 0, key);
    Mission mission = GetMission();
    if (mission)
      mission.OnKeyPress(key);
#ifdef DEVELOPER
    if ((m_IsLeftAltHolding || m_IsLeftAltHolding) && key == KeyCode.KC_F4)
      RequestExit(0);
#endif
  }
References GetMission(), mission, UIScriptedMenu::OnKeyDown(), Mission::OnKeyPress(), and RequestExit().
OnKeyPress() [2/2]
void CGame::OnKeyPress (int key) inline private
Called when key is pressed.
Parameters
key direct input key code (DIK)
Definition at line 155 of file Game.c.
  {
  }
OnKeyRelease() [1/2]
override void CGame::OnKeyRelease (int key) inline protected
Definition at line 2595 of file DayZGame.c.
  {
    if (key == KeyCode.KC_LCONTROL)
      m_IsCtrlHolding = false;
    if (key == KeyCode.KC_LWIN)
      m_IsWinHolding = false;
    if (key == KeyCode.KC_LMENU || key == KeyCode.KC_RMENU)
      m_IsLeftAltHolding = false;
    if (key == KeyCode.KC_RMENU)
      m_IsRightAltHolding = false;
    if (m_keyboard_handler)
      m_keyboard_handler.OnKeyUp(NULL, 0, 0, key);
    Mission mission = GetMission();
    if (mission)
      mission.OnKeyRelease(key);
  }
References GetMission(), mission, Mission::OnKeyRelease(), and UIScriptedMenu::OnKeyUp().
OnKeyRelease() [2/2]
void CGame::OnKeyRelease (int key) inline private
Called when key is released.
Parameters
key direct input key code (DIK)
Definition at line 163 of file Game.c.
  {
  }
OnLicenseChanged()
void CGame::OnLicenseChanged () inline private
Definition at line 92 of file Game.c.
  {
  }
OnLoginTimeEvent()
void CGame::OnLoginTimeEvent (int loginTime) inline protected
Definition at line 1727 of file DayZGame.c.
  {
#ifndef NO_GUI
    // remove login queue if exits
    CancelLoginQueue();
    GetUserManager().GetUserDatabaseIdAsync();
    m_LoginTime = loginTime;
    // timer for login
    if (m_LoginTime > 0)
    {
      if (!m_LoginTimeScreen)
      {
        GetUIManager().CloseAll();
        if (GetMission())
        {
          UIScriptedMenu parent = GetUIManager().GetMenu();
          EnterLoginTime(parent);
        }
        else
        {
          m_LoginTimeScreen = new LoginTimeStatic();
          GetUIManager().ShowScriptedMenu(m_LoginTimeScreen, null);
        }
      }
      m_LoginTimeScreen.SetTime(m_LoginTime);
      m_LoginTimeScreen.Show();
      GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(this.LoginTimeCountdown, 1000, true);
    }
#endif
  }
References CALL_CATEGORY_SYSTEM, CancelLoginQueue(), EnterLoginTime(), GetCallQueue(), GetMission(), GetUIManager(), and GetUserManager().
Referenced by OnEvent().
OnMouseButtonPress() [1/2]
override void CGame::OnMouseButtonPress (int button) inline protected
Definition at line 2618 of file DayZGame.c.
  {
    Mission mission = GetMission();
    if (mission)
      mission.OnMouseButtonPress(button);
  }
References GetMission(), mission, and Mission::OnMouseButtonPress().
OnMouseButtonPress() [2/2]
void CGame::OnMouseButtonPress (int button) inline private
Called when mouse button is pressed.
Parameters
button - number of button Mouse API
Definition at line 171 of file Game.c.
  {
  }
OnMouseButtonRelease() [1/2]
override void CGame::OnMouseButtonRelease (int button) inline protected
Definition at line 2626 of file DayZGame.c.
  {
    Mission mission = GetMission();
    if (mission)
      mission.OnMouseButtonRelease(button);
  }
References GetMission(), mission, and Mission::OnMouseButtonRelease().
OnMouseButtonRelease() [2/2]
void CGame::OnMouseButtonRelease (int button) inline private
Called when mouse button is released.
Parameters
button - number of button Mouse API
Definition at line 179 of file Game.c.
  {
  }
OnMPConnectionLostEvent()
void CGame::OnMPConnectionLostEvent (int duration) inline protected
Definition at line 1844 of file DayZGame.c.
  {
    if (duration >= 0)//(-1 means conn. reestablished)
      SetConnectivityStatState(EConnectivityStatType.CONN_LOST, EConnectivityStatLevel.LEVEL1);
    else
      SetConnectivityStatState(EConnectivityStatType.CONN_LOST, EConnectivityStatLevel.OFF);
#ifdef PLATFORM_PS4
    //PSN Set multiplay state
    if (duration < 0 && GetGameState() == DayZGameState.IN_GAME)
      OnlineServices.SetMultiplayState(true);
    else
      OnlineServices.SetMultiplayState(false);
#endif
  }
References GetGameState(), SetConnectivityStatState(), and OnlineServices::SetMultiplayState().
Referenced by OnEvent().
OnPostUpdate() [1/2]
override void CGame::OnPostUpdate (bool doSim, float timeslice) inline protected
Definition at line 2715 of file DayZGame.c.
  {
    Mission mission = GetMission();
    bool gameIsRunning = false;
    if (doSim && mission && !mission.IsPaused())
      gameIsRunning = true;
    GetPostUpdateQueue(CALL_CATEGORY_SYSTEM).Invoke(timeslice);
#ifndef NO_GUI
    if (m_loading && m_loading.IsLoading())
    {
    }
    else if (m_LoginTimeScreen && m_LoginTimeScreen.IsStatic())
    {
    }
    else
      GetPostUpdateQueue(CALL_CATEGORY_GUI).Invoke(timeslice);
#endif
    if (gameIsRunning)
      GetPostUpdateQueue(CALL_CATEGORY_GAMEPLAY).Invoke(timeslice);
  }
References CALL_CATEGORY_GAMEPLAY, CALL_CATEGORY_GUI, CALL_CATEGORY_SYSTEM, GetMission(), GetPostUpdateQueue(), Mission::IsPaused(), and mission.
OnPostUpdate() [2/2]
void CGame::OnPostUpdate (bool doSim, float timeslice) inline private
Called on World update after simulation of entities.
Parameters
doSim False when simulation is paused, True otherwise
timeslice time elapsed from last call
Definition at line 147 of file Game.c.
  {
  }
OnPreloadEvent()
void CGame::OnPreloadEvent (vector pos) inline protected
Definition at line 1810 of file DayZGame.c.
  {
    // cancel only login time (respawn time is parallel with preload, but login time is not)
    if (m_LoginTimeScreen && !m_LoginTimeScreen.IsRespawn())
      CancelLoginTimeCountdown();
    // tell game to continue
    StoreLoginDataPrepare();
  }
References CancelLoginTimeCountdown(), and StoreLoginDataPrepare().
Referenced by OnEvent().
OnProcessLifetimeChanged()
void CGame::OnProcessLifetimeChanged (int plmtype) inline private
Definition at line 87 of file Game.c.
  {
  }
OnProjectileStopped()
void CGame::OnProjectileStopped (ProjectileStoppedInfo info) inline protected
Definition at line 3140 of file DayZGame.c.
  {
    string simulation;
    GetGame().ConfigGetText("cfgAmmo " + info.GetAmmoType() + " simulation", simulation);
    if (simulation == "shotArrow")
    {
      string pile;
      GetGame().ConfigGetText("cfgAmmo " + info.GetAmmoType() + " spawnPileType", pile);
      EntityAI arrow = EntityAI.Cast(GetGame().CreateObjectEx(pile, info.GetPos(), ECE_DYNAMIC_PERSISTENCY));
      arrow.PlaceOnSurface();
      arrow.SetFromProjectile(info);
    }
  }
References CreateObjectEx(), ECE_DYNAMIC_PERSISTENCY, and GetGame().
OnProjectileStoppedInObject()
void CGame::OnProjectileStoppedInObject (ObjectCollisionInfo info) inline protected
Definition at line 3186 of file DayZGame.c.
  {
    string simulation;
    GetGame().ConfigGetText("cfgAmmo " + info.GetAmmoType() + " simulation", simulation);
    if (simulation == "shotArrow")
    {
      string pile;
      GetGame().ConfigGetText("cfgAmmo " + info.GetAmmoType() + " spawnPileType", pile);
      EntityAI arrow = null;
      EntityAI ent = EntityAI.Cast(info.GetHitObj());
      if (ent)
      {
        EntityAI parent = ent.GetHierarchyParent();
        if (parent && parent.IsPlayer())
        {
          arrow = EntityAI.Cast(GetGame().CreateObjectEx(pile, parent.GetPosition(), ECE_DYNAMIC_PERSISTENCY));
          arrow.PlaceOnSurface();
          arrow.SetFromProjectile(info);
          return;
        }
      }
      vector pos = info.GetPos();
      vector dir = -info.GetInVelocity();
      dir.Normalize();
      pos -= dir * ARROW_PIERCE_DEPTH;
      arrow = EntityAI.Cast(GetGame().CreateObjectEx(pile, pos, ECE_KEEPHEIGHT | ECE_DYNAMIC_PERSISTENCY));
      arrow.SetDirection(dir);
      arrow.SetFromProjectile(info);
      info.GetHitObj().AddArrow(arrow, info.GetComponentIndex(), info.GetHitObjPos(), info.GetHitObjRot());
    }
  }
References ARROW_PIERCE_DEPTH, CreateObjectEx(), ECE_DYNAMIC_PERSISTENCY, ECE_KEEPHEIGHT, GetGame(), and vector::Normalize().
OnProjectileStoppedInTerrain()
void CGame::OnProjectileStoppedInTerrain (TerrainCollisionInfo info) inline protected
Definition at line 3161 of file DayZGame.c.
  {
    string simulation;
    if (info.GetIsWater())
      return;
    GetGame().ConfigGetText("cfgAmmo " + info.GetAmmoType() + " simulation", simulation);
    if (simulation == "shotArrow")
    {
      string pile;
      GetGame().ConfigGetText("cfgAmmo " + info.GetAmmoType() + " spawnPileType", pile);
      vector pos = info.GetPos();
      vector dir = -info.GetInVelocity();
      dir.Normalize();
      pos -= dir * ARROW_PIERCE_DEPTH;
      EntityAI arrow = EntityAI.Cast(GetGame().CreateObjectEx(pile, pos, ECE_KEEPHEIGHT | ECE_DYNAMIC_PERSISTENCY));
      arrow.SetDirection(dir);
      arrow.SetFromProjectile(info);
    }
  }
References ARROW_PIERCE_DEPTH, CreateObjectEx(), ECE_DYNAMIC_PERSISTENCY, ECE_KEEPHEIGHT, GetGame(), and vector::Normalize().
OnRespawnEvent()
void CGame::OnRespawnEvent (int time) inline protected
Definition at line 1782 of file DayZGame.c.
  {
    // use login time screen for respawn timer
    if (time >= 0)
    {
      m_LoginTime = time;
      if (!m_LoginTimeScreen)
      {
        GetUIManager().CloseAll();
        UIScriptedMenu parent = GetUIManager().GetMenu();
        EnterLoginTime(parent);
      }
      m_LoginTimeScreen.SetRespawn(true);
      m_LoginTimeScreen.SetTime(m_LoginTime);
      m_LoginTimeScreen.Show();
      GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(this.LoginTimeCountdown, 1000, true);
    }
    if (GetPlayer())
      GetPlayer().StopDeathDarkeningEffect();
    PPERequesterBank.GetRequester(PPERequester_DeathDarkening).Start(new Param1<float>(1.0));
  }
References CALL_CATEGORY_SYSTEM, EnterLoginTime(), GetCallQueue(), GetPlayer(), and GetUIManager().
Referenced by OnEvent().
OnRPC() [1/2]
override void CGame::OnRPC (PlayerIdentity sender, Object target, int rpc_type, ParamsReadContext ctx) inline protected
Definition at line 2741 of file DayZGame.c.
  {
    super.OnRPC(sender, target, rpc_type, ctx);
    Event_OnRPC.Invoke(sender, target, rpc_type, ctx);
    //Print("["+ GetGame().GetTime().ToString() +"] => DayZGame::OnRPC = "+ EnumTools.EnumToString(ERPCs,rpc_type));
    if (target)
    {
      // call rpc on target
      target.OnRPC(sender, rpc_type, ctx);
    }
    else
    {
      switch (rpc_type)
      {
#ifndef SERVER
#ifndef NO_GUI
      case ERPCs.RPC_CFG_GAMEPLAY_SYNC:
      {
        CfgGameplayHandler.OnRPC(null, ctx);
        break;
      }
      case ERPCs.RPC_UNDERGROUND_SYNC:
      {
        UndergroundAreaLoader.OnRPC(ctx);
        break;
      }
      case ERPCs.RPC_SEND_NOTIFICATION:
      {
        NotificationType type;
        float show_time;
        string detail_text;
        ctx.Read(type);
        ctx.Read(show_time);
        ctx.Read(detail_text);
        NotificationSystem.AddNotification(type, show_time, detail_text);
        break;
      }
      case ERPCs.RPC_SEND_NOTIFICATION_EXTENDED:
      {
        float show_time_ext;
        string title_text_ext;
        string detail_text_ext;
        string icon_ext;
        ctx.Read(show_time_ext);
        ctx.Read(title_text_ext);
        ctx.Read(detail_text_ext);
        ctx.Read(icon_ext);
        NotificationSystem.AddNotificationExtended(show_time_ext, title_text_ext, detail_text_ext, icon_ext);
        break;
      }
      case ERPCs.RPC_SOUND_HELICRASH:
      {
        bool playSound;
        vector pos;
        string sound_set;
        //Helicrash is a world event, we want anyone to be able to hear it
        Param3<bool, vector, int> playCrashSound = new Param3<bool, vector, int>(false, "0 0 0", 0);
        if (ctx.Read(playCrashSound))
        {
          playSound = playCrashSound.param1;
          pos = playCrashSound.param2;
          sound_set = CrashSoundSets.GetSoundSetByHash(playCrashSound.param3);
        }
        if (playSound)
        {
          m_CrashSound = SEffectManager.PlaySound(sound_set, pos, 0.1, 0.1);
          m_CrashSound.SetAutodestroy(true);
        }
        break;
      }
      //Random off map artillery barrage
      case ERPCs.RPC_SOUND_ARTILLERY:
      {
        vector position;
        Param1<vector> playArtySound = new Param1<vector>(vector.Zero);
        if (ctx.Read(playArtySound))
        {
          position = playArtySound.param1;
          if (position == vector.Zero)
            break;
        }
        else
          break;
        if (!GetGame().GetPlayer())
          break;
        if (vector.DistanceSq(GetGame().GetPlayer().GetPosition(), position) <= (MIN_ARTY_SOUND_RANGE * MIN_ARTY_SOUND_RANGE))
          break;
        m_ArtySound = SEffectManager.PlaySound("Artillery_Distant_Barrage_SoundSet", position, 0.1, 0.1);
        m_ArtySound.SetAutodestroy(true);
        break;
      }
      case ERPCs.RPC_SOUND_CONTAMINATION:
      {
        vector soundPos;
        Param1<vector> playContaminatedSound = new Param1<vector>(vector.Zero);
        if (ctx.Read(playContaminatedSound))
        {
          soundPos = playContaminatedSound.param1;
          if (soundPos == vector.Zero)
            break;
        }
        else
          break;
        if (!GetGame().GetPlayer())
          break;
        EffectSound closeArtySound = SEffectManager.PlaySound("Artillery_Close_SoundSet", soundPos);
        closeArtySound.SetAutodestroy(true);
        // We add camera shake upon shell detonation
        float distance_to_player = vector.DistanceSq(soundPos, GetGame().GetPlayer().GetPosition());
        if (distance_to_player <= GameConstants.CAMERA_SHAKE_ARTILLERY_DISTANCE2)
        {
          float strength_factor = Math.InverseLerp(GameConstants.CAMERA_SHAKE_ARTILLERY_DISTANCE, 0, Math.Sqrt(distance_to_player));
          DayZPlayerCamera camera = GetGame().GetPlayer().GetCurrentCamera();
          if (camera)
            camera.SpawnCameraShake(strength_factor * 4);
        }
        ParticleManager.GetInstance().PlayInWorld(ParticleList.CONTAMINATED_AREA_GAS_SHELL, soundPos);
        break;
      }
      // Single artillery shot to announce dynamic contaminated area
      case ERPCs.RPC_SOUND_ARTILLERY_SINGLE:
      {
        vector soundPosition;
        vector delayedSoundPos;
        float soundDelay;
        Param3<vector, vector, float> playArtyShotSound = new Param3<vector, vector, float>(vector.Zero, vector.Zero, 0);
        if (ctx.Read(playArtyShotSound))
        {
          soundPosition = playArtyShotSound.param1;
          delayedSoundPos = playArtyShotSound.param2;
          soundDelay = playArtyShotSound.param3;
          if (soundPosition == vector.Zero)
            break;
        }
        else
          break;
        if (!GetGame().GetPlayer())
          break;
        m_ArtySound = SEffectManager.PlaySound("Artillery_Distant_SoundSet", soundPosition, 0.1, 0.1);
        m_ArtySound.SetAutodestroy(true);
        // We remove the amount of time the incoming sound lasts
        soundDelay -= 5;
        // We convert to milliseconds
        soundDelay *= 1000;
        GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLater(DelayedMidAirDetonation, soundDelay, false, delayedSoundPos[0], delayedSoundPos[1], delayedSoundPos[2]);
        break;
      }
      case ERPCs.RPC_SET_BILLBOARDS:
      {
        if (!m_BillboardSetHandler)
          m_BillboardSetHandler = new BillboardSetHandler();
        Param1<int> indexP = new Param1<int>(-1);
        if (ctx.Read(indexP))
        {
          int index = indexP.param1;
          m_BillboardSetHandler.OnRPCIndex(index);
        }
        break;
      }
#endif
#endif
      case ERPCs.RPC_USER_SYNC_PERMISSIONS:
      {
        map<string, bool> mute_list;
        if (ctx.Read(mute_list))
        {
          for (int i = 0; i < mute_list.Count(); i++)
          {
            string uid = mute_list.GetKey(i);
            bool mute = mute_list.GetElement(i);
            MutePlayer(uid, sender.GetPlainId(), mute);
          }
        }
        break;
      }
        /*
          case ERPCs.RPC_SERVER_RESPAWN_MODE:
          {
          int mode;
          if (ctx.Read(mode) && !IsServer())
          {
            GetMission().SetRespawnModeClient(mode);
          }
          }
        */
#ifdef DEVELOPER
      case ERPCs.DEV_SET_WEATHER:
      {
        Param1<DebugWeatherRPCData> p1data = new Param1<DebugWeatherRPCData>(null);
        if (ctx.Read(p1data))
        {
          DebugWeatherRPCData data = p1data.param1;
          if (data.m_FogValue >= 0)
            GetGame().GetWeather().GetFog().Set(data.m_FogValue, data.m_FogInterpolation, data.m_FogDuration);
          if (data.m_OvercastValue >= 0)
            GetGame().GetWeather().GetOvercast().Set(data.m_OvercastValue, data.m_OvercastInterpolation, data.m_OvercastDuration);
          if (data.m_RainValue >= 0)
            GetGame().GetWeather().GetRain().Set(data.m_RainValue, data.m_RainInterpolation, data.m_RainDuration);
        }
        else
          ErrorEx("Failed to read weather debug data");
        break;
      }
#endif
#ifdef DIAG_DEVELOPER
#ifdef SERVER
      case ERPCs.DIAG_CAMERATOOLS_CAM_DATA:
      {
        if (!m_CameraToolsMenuServer)
          m_CameraToolsMenuServer = new CameraToolsMenuServer;
        m_CameraToolsMenuServer.OnRPC(rpc_type, ctx);
        break;
      }
      case ERPCs.DIAG_CAMERATOOLS_CAM_SUBSCRIBE:
      {
        if (!m_CameraToolsMenuServer)
          m_CameraToolsMenuServer = new CameraToolsMenuServer;
        m_CameraToolsMenuServer.OnRPC(rpc_type, ctx);
        break;
      }
#endif
#endif
      }
      // global rpc's handling
    }
  }
References NotificationSystem::AddNotification(), NotificationSystem::AddNotificationExtended(), CALL_CATEGORY_GAMEPLAY, GameConstants::CAMERA_SHAKE_ARTILLERY_DISTANCE, GameConstants::CAMERA_SHAKE_ARTILLERY_DISTANCE2, ParticleList::CONTAMINATED_AREA_GAS_SHELL, DayZPlayerCamera(), vector::DistanceSq(), ErrorEx, GetCallQueue(), GetGame(), GetPlayer(), GetPosition, CrashSoundSets::GetSoundSetByHash(), Math::InverseLerp(), MutePlayer(), CfgGameplayHandler::OnRPC(), UndergroundAreaLoader::OnRPC(), ParticleManager(), SEffectManager::PlaySound(), Math::Sqrt(), and vector::Zero.
OnRPC() [2/2]
void CGame::OnRPC (PlayerIdentity sender, Object target, int rpc_type, ParamsReadContext ctx) inline private
Called after remote procedure call is recieved for this object.
Parameters
target object on which remote procedure is called, when NULL, RPC is evaluated by CGame as global
rpc_type user defined identification of RPC
ctx read context for params
Definition at line 199 of file Game.c.
  {
  }
OnUpdate() [1/2]
override void CGame::OnUpdate (bool doSim, float timeslice) inline protected
Definition at line 2649 of file DayZGame.c.
  {
    m_DeltaTime = timeslice;
    Mission mission = GetMission();
    bool gameIsRunning = false;
    if (doSim && mission && !mission.IsPaused())
      gameIsRunning = true;
    if (doSim && mission)
      mission.OnUpdate(timeslice);
    // queues and timers update
    GetCallQueue(CALL_CATEGORY_SYSTEM).Tick(timeslice);
    GetUpdateQueue(CALL_CATEGORY_SYSTEM).Invoke(timeslice);
    GetTimerQueue(CALL_CATEGORY_SYSTEM).Tick(timeslice);
#ifndef NO_GUI
    if (m_IsConnecting)
      UpdateLoginQueue(timeslice);
    if (m_loading && m_loading.IsLoading())
      m_loading.OnUpdate(timeslice);
    else if (m_LoginTimeScreen && m_LoginTimeScreen.IsStatic())
      m_LoginTimeScreen.Update(timeslice);
    else
    {
      GetCallQueue(CALL_CATEGORY_GUI).Tick(timeslice);
      GetUpdateQueue(CALL_CATEGORY_GUI).Invoke(timeslice);
      GetTimerQueue(CALL_CATEGORY_GUI).Tick(timeslice);
      GetDragQueue().Tick();
    }
    NotificationSystem.Update(timeslice);
    if (m_Notifications)
      m_Notifications.Update(timeslice);
#ifndef SERVER
#ifdef DIAG_DEVELOPER
    if (GetGame().IsMultiplayer() && GetPlayer() && DiagMenu.GetBool(DiagMenuIDs.MISC_CONNECTION_STATS))
    {
      PlayerIdentity playerIdentity = GetPlayer().GetIdentity();
      if (playerIdentity)
      {
        int pingAct = playerIdentity.GetPingAct();
        int pingAvg = playerIdentity.GetPingAvg();
      }
      DrawPerformaceStats(pingAct, pingAvg);
    }
#endif
#endif
#endif
    if (gameIsRunning)
    {
      GetCallQueue(CALL_CATEGORY_GAMEPLAY).Tick(timeslice);
      GetUpdateQueue(CALL_CATEGORY_GAMEPLAY).Invoke(timeslice);
      GetTimerQueue(CALL_CATEGORY_GAMEPLAY).Tick(timeslice);
    }
  }
References CALL_CATEGORY_GAMEPLAY, CALL_CATEGORY_GUI, CALL_CATEGORY_SYSTEM, DiagMenu::GetBool(), GetCallQueue(), GetDragQueue(), GetGame(), GetMission(), GetPlayer(), GetTimerQueue(), GetUpdateQueue(), IsMultiplayer(), Mission::IsPaused(), mission, Mission::OnUpdate(), NotificationSystem::Update(), and UpdateLoginQueue().
OnUpdate() [2/2]
void CGame::OnUpdate (bool doSim, float timeslice) inline private
Called on World update.
Parameters
doSim False when simulation is paused, True otherwise
timeslice time elapsed from last call
Definition at line 138 of file Game.c.
  {
  }
OpenURL()
proto native void CGame::OpenURL (string url) protected
OverrideDOF()
proto native void CGame::OverrideDOF (bool enable, float focusDistance, float focusLength, float focusLengthNear, float blur, float focusDepthOffset) protected
OverrideInventoryLights()
proto native void CGame::OverrideInventoryLights (vector diffuse, vector ambient, vector ground, vector dir) protected
override inventory light
Parameters
diffuse directional light
ambient ambient light
ground ground light
dir direction of light, Vector(0,0,1) is from camera
PartyLaunch()
void CGame::PartyLaunch () inline protected
Definition at line 2082 of file DayZGame.c.
  {
    SetGameState(DayZGameState.PARTY);
    SetLoadState(DayZLoadState.PARTY_START);
    BiosUserManager user_manager = GetGame().GetUserManager();
    string param;
    if (GetCLIParam("party", param))
    {
      user_manager.ParsePartyAsync(param);
      StartRandomCutscene(GetMainMenuWorld());
    }
  }
References GetCLIParam(), GetGame(), GetMainMenuWorld(), SetGameState(), SetLoadState(), and StartRandomCutscene().
Referenced by OnInitialize().
PlayMission()
proto native void CGame::PlayMission (string path) private
Starts mission (equivalent for SQF playMission). You MUST use double slash \.
Referenced by MissionLaunch(), and SelectGamepad().
PreloadObject()
proto native bool CGame::PreloadObject (string type, float distance) private
Preload objects with certain type in certain distance from camera.
Parameters
type of objects which should be preloaded
distance from camera in which objects should be preloaded
Returns
true on success
ProfilerStart()
proto native void CGame::ProfilerStart (string name) private
Use for profiling code from start to stop, they must match have same name, look wiki pages for more info: https://confluence.bistudio.com/display/EN/Profiler.
ProfilerStop()
proto native void CGame::ProfilerStop (string name) private
Use for profiling code from start to stop, they must match have same name, look wiki pages for more info: https://confluence.bistudio.com/display/EN/Profiler.
RefreshCurrentServerInfo()
void CGame::RefreshCurrentServerInfo () inline protected
Definition at line 2444 of file DayZGame.c.
  {
    string addr;
    int port;
    if (GetHostAddress(addr, port))
    {
      m_ConnectAddress = addr;
      m_ConnectPort = port;
    }
    OnlineServices.GetCurrentServerInfo(m_ConnectAddress, m_ConnectPort);
  }
References OnlineServices::GetCurrentServerInfo(), and GetHostAddress().
RefreshMouseCursorVisibility()
void CGame::RefreshMouseCursorVisibility () inline protected
Handles app active-ness
Fallback, just in-case
Definition at line 3490 of file DayZGame.c.
  {
#ifndef NO_GUI
#ifdef FEATURE_CURSOR
    if (!IsAppActive())
      ShowCursorWidget(true);
    else
#endif
    {
      bool showCursor = m_CursorDesiredVisibilityScript && CanDisplayMouseCursor();
      UIManager ui = GetUIManager();
      if (ui)
      {
        ui.ShowCursor(showCursor);
      }
      else
      {
        ShowCursorWidget(showCursor);
      }
    }
#endif
  }
References CanDisplayMouseCursor(), GetUIManager(), IsAppActive(), and ShowCursorWidget().
Referenced by DayZGame(), OnActivateMessage(), OnDeactivateMessage(), and SetMouseCursorDesiredVisibility().
RegisterNetworkStaticObject()
proto native bool CGame::RegisterNetworkStaticObject (Object object) private
Static objects cannot be replicated by default (there are too many objects on the map). Use this method when you want to replicate some scripted variables. Cannot be called in object's constructor, because networking is not initialized yet.
Parameters
object static object to replicate
Returns
false, if registration wasn't successful or when object is already registered
RegisterProfilesOptions()
void CGame::RegisterProfilesOptions () inline private
Definition at line 1077 of file DayZGame.c.
  {
    m_DayZProfileOptions.RegisterProfileOptionBool(EDayZProfilesOptions.CROSSHAIR, SHOW_CROSSHAIR);
    m_DayZProfileOptions.RegisterProfileOptionBool(EDayZProfilesOptions.HUD, SHOW_HUD);
    m_DayZProfileOptions.RegisterProfileOptionBool(EDayZProfilesOptions.QUICKBAR, SHOW_QUICKBAR);
    m_DayZProfileOptions.RegisterProfileOptionBool(EDayZProfilesOptions.SERVER_MESSAGES, SYSTEM_CHAT_MSG);
    m_DayZProfileOptions.RegisterProfileOptionBool(EDayZProfilesOptions.USERS_CHAT, DIRECT_CHAT_MSG);
    m_DayZProfileOptions.RegisterProfileOptionBool(EDayZProfilesOptions.RADIO_CHAT, RADIO_CHAT_MSG);
    m_DayZProfileOptions.RegisterProfileOptionBool(EDayZProfilesOptions.GAME_MESSAGES, GAME_CHAT_MSG, false);
    m_DayZProfileOptions.RegisterProfileOptionBool(EDayZProfilesOptions.ADMIN_MESSAGES, ADMIN_CHAT_MSG, false);
    m_DayZProfileOptions.RegisterProfileOptionBool(EDayZProfilesOptions.PLAYER_MESSAGES, PLAYER_CHAT_MSG, false);
    m_DayZProfileOptions.RegisterProfileOptionBool(EDayZProfilesOptions.SERVERINFO_DISPLAY, SHOW_SERVERINFO, true);
    m_DayZProfileOptions.RegisterProfileOptionBool(EDayZProfilesOptions.BLEEDINGINDICATION, ENABLE_BLEEDINGINDICATION, true);
    m_DayZProfileOptions.RegisterProfileOptionBool(EDayZProfilesOptions.CONNECTIVITY_INFO, SHOW_CONNECTIVITYINFO, true);
    m_DayZProfileOptions.RegisterProfileOptionFloat(EDayZProfilesOptions.HUD_BRIGHTNESS, HUD_BRIGHTNESS, 0.0);
  }
References ADMIN_CHAT_MSG, DIRECT_CHAT_MSG, ENABLE_BLEEDINGINDICATION, GAME_CHAT_MSG, HUD_BRIGHTNESS, PLAYER_CHAT_MSG, RADIO_CHAT_MSG, SHOW_CONNECTIVITYINFO, SHOW_CROSSHAIR, SHOW_HUD, SHOW_QUICKBAR, SHOW_SERVERINFO, and SYSTEM_CHAT_MSG.
Referenced by OnInitialize().
ReloadMission()
void CGame::ReloadMission () inline private
Definition at line 1312 of file DayZGame.c.
  {
#ifdef DEVELOPER
    Print("Reloading mission module!");
    CreateMission(m_MissionPath);
#endif
  }
References CreateMission(), and Print().
RemoteObjectCreate()
proto native void CGame::RemoteObjectCreate (Object obj) private
RemoteObjectDelete - deletes only remote object tree (unregisters from network). do not use if not sure what you do.
RemoteObjectDelete()
proto native void CGame::RemoteObjectDelete (Object obj) private
RemoteObjectTreeCreate()
proto native void CGame::RemoteObjectTreeCreate (Object obj) private
RemoteObjectCreate - postponed registration of network object (and creation of remote object). do not use if not sure what you do.
RemoteObjectTreeDelete()
proto native void CGame::RemoteObjectTreeDelete (Object obj) private
RemoteObjectDelete - deletes only remote object (unregisters from network). do not use if not sure what you do.
RemoveFromReconnectCache()
proto native void CGame::RemoveFromReconnectCache (string uid) private
Remove player from reconnect cache.
Note
Works only on server
Parameters
uid of the player
RemoveVoiceNotification()
void CGame::RemoveVoiceNotification (VONStopSpeakingEventParams vonStopParams) inline protected
Definition at line 1689 of file DayZGame.c.
  {
    m_Notifications.RemoveVoiceNotification(vonStopParams.param2);
  }
ReportModded()
static bool CGame::ReportModded () inline static private
Definition at line 1269 of file DayZGame.c.
  {
    return m_ReportModded;
  }
References m_ReportModded.
RequestExit()
proto native void CGame::RequestExit (int code) private
Sets exit code and quits in the right moment.
Referenced by OnKeyPress().
RequestRestart()
proto native void CGame::RequestRestart (int code) private
Sets exit code and restart in the right moment.
ResetPPMask()
proto native void CGame::ResetPPMask () protected
ResetProfileOptions()
void CGame::ResetProfileOptions () inline private
Definition at line 1095 of file DayZGame.c.
  {
    m_DayZProfileOptions.ResetOptionsBool();
    m_DayZProfileOptions.ResetOptionsInt();
    m_DayZProfileOptions.ResetOptionsFloat();
  }
Referenced by SelectGamepad().
RespawnPlayer()
proto native void CGame::RespawnPlayer () protected
RestartMission()
proto native void CGame::RestartMission () protected
RPC()
proto native void CGame::RPC (Object target, int rpcType, notnull array< ref Param > params, bool guaranteed, PlayerIdentity recipient = null) private
Initiate remote procedure call. When called on client, RPC is evaluated on server; When called on server, RPC is executed on all clients.
Parameters
target object on which remote procedure is called, when NULL, RPC is evaluated by CGame as global
rpc_type user defined identification of RPC
params custom params array
recipient specified client to send RPC to. If NULL, RPC will be send to all clients (specifying recipient increase security and decrease network traffic)
const int RPC_LOW_BLOOD_PRESSURE_EFFECT = 0;
...
// on server side, after blood pressure of player is low...
Param1<float> p = new Param1<float>(m_blood_pressure);
array<param> params = new array<param>;
params.Insert(p);
GetGame().RPC(player, RPC_LOW_BLOOD_PRESSURE_EFFECT, params);
// or shortcut
GetGame().RPCSingleParam(player, RPC_LOW_BLOOD_PRESSURE_EFFECT, p);
...
// on client
class PlayerBase
{
// override OnRPC function
void OnRPC(PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
{
  // dont forget to propagate this call trough class hierarchy!
  super.OnRPC(rpc_type, ctx);
  switch(rpc_type)
  {
    case RPC_LOW_BLOOD_PRESSURE_EFFECT:
      Param1<float> p = Param1<float>(0);
      if (ctx.Read(p))
      {
        float blood_pressure = p.param1;
        float effect_intensity = 1.0 - blood_pressure;
        ShowFancyScreenEffect(effect_intensity);
      }
    break;
  }
}
}
Referenced by RPCSingleParam().
RPCSelf()
proto native void CGame::RPCSelf (Object target, int rpcType, notnull array< ref Param > params) private
Not actually an RPC, as it will send it only to yourself.
Referenced by RPCSelfSingleParam().
RPCSelfSingleParam()
void CGame::RPCSelfSingleParam (Object target, int rpcType, Param param) inline private
Definition at line 888 of file Game.c.
  {
    m_ParamCache.Set(0, param);
    RPCSelf(target, rpcType, m_ParamCache);
  }
References m_ParamCache, and RPCSelf().
RPCSingleParam()
void CGame::RPCSingleParam (Object target, int rpc_type, Param param, bool guaranteed, PlayerIdentity recipient = null) inline private
see CGame.RPC
Definition at line 881 of file Game.c.
  {
    m_ParamCache.Set(0, param);
    RPC(target, rpc_type, m_ParamCache, guaranteed, recipient);
  }
References m_ParamCache, and RPC().
SaveProfile()
proto native void CGame::SaveProfile () private
Saves profile on disk.
Referenced by AddVisitedServer().
SaveVersion()
proto native int CGame::SaveVersion () private
Returns actual storage version - saving.
ScriptTest()
proto native bool CGame::ScriptTest () private
SelectGamepad()
void CGame::SelectGamepad () inline protected
Definition at line 2276 of file DayZGame.c.
  {
    ResetProfileOptions();
    BiosUserManager user_manager = GetUserManager();
    if (user_manager)
    {
      BiosUser selected_user = user_manager.GetSelectedUser();
      if (selected_user)
      {
        OnlineServices.SetBiosUser(selected_user);
        SetPlayerName(selected_user.GetName());
        SetUserFOV(GetUserFOVFromConfig());
#ifdef PLATFORM_CONSOLE
        SetPlayerGameName(selected_user.GetName());
        user_manager.GetUserDatabaseIdAsync();
#endif
      }
      if (GetUIManager().GetMenu())
        GetUIManager().GetMenu().Refresh();
    }
    switch (GetLoadState())
    {
    case DayZLoadState.JOIN_USER_SELECT:
    {
      SetLoadState(DayZLoadState.JOIN_CONTROLLER_SELECT);
      OnlineServices.LoadMPPrivilege();
      break;
    }
    case DayZLoadState.PARTY_USER_SELECT:
    {
      SetLoadState(DayZLoadState.PARTY_CONTROLLER_SELECT);
      DeleteTitleScreen();
      GetUIManager().EnterScriptedMenu(MENU_SERVER_BROWSER, GetUIManager().GetMenu());
      break;
    }
    case DayZLoadState.CONNECT_USER_SELECT:
    {
      SetLoadState(DayZLoadState.CONNECT_CONTROLLER_SELECT);
      OnlineServices.LoadMPPrivilege();
      break;
    }
    case DayZLoadState.MAIN_MENU_USER_SELECT:
    {
      SetLoadState(DayZLoadState.MAIN_MENU_CONTROLLER_SELECT);
      DeleteTitleScreen();
      GetUIManager().EnterScriptedMenu(MENU_MAIN, GetUIManager().GetMenu());
      break;
    }
    case DayZLoadState.MISSION_USER_SELECT:
    {
      SetLoadState(DayZLoadState.MISSION_CONTROLLER_SELECT);
      DeleteTitleScreen();
      string mission;
      GetCLIParam("mission", mission);
      PlayMission(mission);
      break;
    }
    }
  }
References DeleteTitleScreen(), GetCLIParam(), GetLoadState(), GetUIManager(), GetUserFOVFromConfig(), GetUserManager(), OnlineServices::LoadMPPrivilege(), MENU_MAIN, MENU_SERVER_BROWSER, mission, PlayMission(), ResetProfileOptions(), OnlineServices::SetBiosUser(), SetLoadState(), SetPlayerGameName(), SetPlayerName(), and SetUserFOV().
Referenced by SelectUser().
SelectPlayer()
proto native void CGame::SelectPlayer (PlayerIdentity identity, Object player) private
Selects player's controlled object.
Parameters
identity identity used in MP (use NULL in singleplayer)
player object which should be controlled by player
Note
We can use only instances of DayZPlayer now
SelectSpectator()
proto native void CGame::SelectSpectator (PlayerIdentity identity, string spectatorObjType, vector position) private
Creates spectator object (mostly cameras)
Parameters
identity identity used in MP (use NULL in singleplayer)
spectatorObjType classname for spectator object (like cameras)
position where to create spectator instance
SelectUser()
void CGame::SelectUser (int gamepad = -1) inline protected
Definition at line 2141 of file DayZGame.c.
  {
    BiosUserManager user_manager = GetUserManager();
    if (user_manager)
    {
      BiosUser selected_user;
      if (gamepad > -1)
      {
        GetInput().GetGamepadUser(gamepad, selected_user);
#ifdef PLATFORM_PS4
        if (selected_user)
#endif
        {
          if (user_manager.SelectUserEx(selected_user))
          {
            GetGame().GetInput().IdentifyGamepad(GamepadButton.BUTTON_NONE);
            GetInput().SelectActiveGamepad(gamepad);
          }
          else
            selected_user = user_manager.GetSelectedUser();
#ifdef PLATFORM_PS4
          if (!selected_user.IsOnline())
          {
            user_manager.LogOnUserAsync(selected_user);
            return;
          }
#endif
        }
#ifdef PLATFORM_PS4
        else
        {
          GetInput().ResetActiveGamepad();
          GamepadCheck();
        }
#endif
      }
      if (!selected_user)
        selected_user = user_manager.GetSelectedUser();
      if (!selected_user)
      {
        user_manager.PickUserAsync();
        return;
      }
      user_manager.SelectUserEx(selected_user);
      switch (GetLoadState())
      {
      case DayZLoadState.JOIN_START:
      {
        SetLoadState(DayZLoadState.JOIN_USER_SELECT);
        break;
      }
      case DayZLoadState.PARTY_START:
      {
        SetLoadState(DayZLoadState.PARTY_USER_SELECT);
        break;
      }
      case DayZLoadState.MAIN_MENU_START:
      {
        SetLoadState(DayZLoadState.MAIN_MENU_USER_SELECT);
        break;
      }
      case DayZLoadState.CONNECT_START:
      {
        SetLoadState(DayZLoadState.CONNECT_USER_SELECT);
        break;
      }
      case DayZLoadState.MISSION_START:
      {
        SetLoadState(DayZLoadState.MISSION_USER_SELECT);
        break;
      }
      default:
        break;
      }
      SelectGamepad();
      g_Game.SetHudBrightness(g_Game.GetHUDBrightnessSetting());
    }
  }
References g_Game, GamepadCheck(), GetGame(), GetInput(), GetLoadState(), GetUserManager(), SelectGamepad(), and SetLoadState().
Referenced by GamepadCheck().
SendLogoutTime()
proto native void CGame::SendLogoutTime (Object player, int time) private
Inform client about logout time (creates logout screen on specified client)
Note
Works only on server
Parameters
player object which is logging out
time length of logout
ServerConfigGetInt()
proto native int CGame::ServerConfigGetInt (string name) protected
Server config parsing. Returns 0 if not found.
SetConnecting()
void CGame::SetConnecting (bool value) inline protected
Returns true when connecting to server.
Definition at line 3026 of file DayZGame.c.
  {
    m_IsConnecting = value;
  }
Referenced by Connect(), and OnEvent().
SetConnectivityStatState()
void CGame::SetConnectivityStatState (EConnectivityStatType type, EConnectivityStatLevel level) inline protected
Definition at line 1632 of file DayZGame.c.
  {
    if (level != m_ConnectivityStatsStates[type])
    {
      if (OnConnectivityStatChange(type, level, m_ConnectivityStatsStates[type]))//before setting the prev. level to be the current level, we need to make sure we successfully set the icon
        m_ConnectivityStatsStates[type] = level;
    }
  }
References OnConnectivityStatChange().
Referenced by OnEvent(), and OnMPConnectionLostEvent().
SetDatabaseID()
void CGame::SetDatabaseID (string id) inline protected
Definition at line 1982 of file DayZGame.c.
  {
    m_DatabaseID = id;
    if (GetUIManager().GetMenu())
      GetUIManager().GetMenu().Refresh();
  }
References GetUIManager().
SetDebugMonitorEnabled()
void CGame::SetDebugMonitorEnabled (int value) inline protected
Definition at line 1021 of file Game.c.
  {
    m_DebugMonitorEnabled = value;
  }
References m_DebugMonitorEnabled.
SetDiagDrawMode()
proto native void CGame::SetDiagDrawMode (int diag_draw_mode) private
Set debug draw mode.
SetDiagModeEnable()
proto native void CGame::SetDiagModeEnable (int diag_mode, bool enabled) private
Set specific debug mode.
SetEVUser()
proto native void CGame::SetEVUser (float value) protected
Sets custom camera camera EV. range: -50.0..50.0? //TODO.
Referenced by SetEVValue().
SetEVValue()
void CGame::SetEVValue (float value) inline protected
Definition at line 3405 of file DayZGame.c.
  {
    m_PreviousEVValue = m_EVValue;
    SetEVUser(value);
    m_EVValue = value;
  }
References m_EVValue, and SetEVUser().
SetGameState()
void CGame::SetGameState (DayZGameState state) inline private
Definition at line 1249 of file DayZGame.c.
  {
    m_GameState = state;
  }
Referenced by ConnectLaunch(), DisconnectSessionEx(), JoinLaunch(), MainMenuLaunch(), MissionLaunch(), OnEvent(), PartyLaunch(), and TryConnect().
SetHudBrightness()
void CGame::SetHudBrightness (float value) inline protected
Definition at line 3376 of file DayZGame.c.
  {
    Widget.SetLV(value);
    Widget.SetTextLV(value);
  }
Referenced by OnInitialize().
SetKeyboardHandle()
void CGame::SetKeyboardHandle (UIScriptedMenu handler) inline protected
Definition at line 3043 of file DayZGame.c.
  {
    m_keyboard_handler = handler;
  }
SetLoadState()
void CGame::SetLoadState (DayZLoadState state) inline private
Definition at line 1259 of file DayZGame.c.
  {
    m_LoadState = state;
  }
Referenced by ConnectLaunch(), DisconnectSessionEx(), JoinLaunch(), MainMenuLaunch(), MissionLaunch(), OnEvent(), PartyLaunch(), SelectGamepad(), and SelectUser().
SetLoginTimerFinished()
proto native void CGame::SetLoginTimerFinished () protected
SetMainMenuWorld()
proto native void CGame::SetMainMenuWorld (string world) protected
Referenced by DayZGame().
SetMission()
proto native void CGame::SetMission (Mission mission) private
SetMissionPath()
void CGame::SetMissionPath (string path) inline private
Called from C++.
Definition at line 1103 of file DayZGame.c.
  {
    m_MissionPath = path;
    int pos_end = 0;
    int pos_cur = 0;
    while (pos_cur != -1)
    {
      pos_end = pos_cur;
      pos_cur = path.IndexOfFrom(pos_cur + 1, "\\");
    }
    m_MissionFolderPath = path.Substring(0, pos_end);
  }
References string::IndexOfFrom(), path, and string::Substring().
SetMissionState()
void CGame::SetMissionState (int state) inline private
Definition at line 1168 of file DayZGame.c.
  {
    m_MissionState = state;
  }
SetMouseCursorDesiredVisibility()
void CGame::SetMouseCursorDesiredVisibility (bool visible) inline protected
Definition at line 3461 of file DayZGame.c.
  {
    m_CursorDesiredVisibilityScript = visible;
    RefreshMouseCursorVisibility();
  }
References RefreshMouseCursorVisibility().
SetNewCharacter()
void CGame::SetNewCharacter (bool state) inline protected
Definition at line 3325 of file DayZGame.c.
  {
    m_IsNewCharacter = state;
  }
SetPlayerGameName()
void CGame::SetPlayerGameName (string name) inline protected
Definition at line 3315 of file DayZGame.c.
  {
    m_PlayerName = name;
  }
References name.
Referenced by SelectGamepad().
SetPlayerName()
proto native void CGame::SetPlayerName (string name) private
Sets current player name.
Parameters
name
Referenced by SelectGamepad().
SetPreviousGamepad()
void CGame::SetPreviousGamepad (int gamepad) inline protected
Definition at line 2226 of file DayZGame.c.
  {
    m_PreviousGamepad = gamepad;
  }
SetProfileOption()
void CGame::SetProfileOption (EDayZProfilesOptions option, bool value) inline private
Definition at line 1214 of file DayZGame.c.
  {
    m_DayZProfileOptions.SetProfileOptionBool(option, value);
  }
Referenced by SetProfileOptionBool().
SetProfileOptionBool()
void CGame::SetProfileOptionBool (EDayZProfilesOptions option, bool value) inline private
Definition at line 1219 of file DayZGame.c.
  {
    SetProfileOption(option, value);
  }
References SetProfileOption().
SetProfileOptionFloat()
void CGame::SetProfileOptionFloat (EDayZProfilesOptions option, float value) inline private
Definition at line 1229 of file DayZGame.c.
  {
    m_DayZProfileOptions.SetProfileOptionFloat(option, value);
  }
SetProfileOptionInt()
void CGame::SetProfileOptionInt (EDayZProfilesOptions option, int value) inline private
Definition at line 1224 of file DayZGame.c.
  {
    m_DayZProfileOptions.SetProfileOptionInt(option, value);
  }
SetProfileString()
proto native void CGame::SetProfileString (string name, string value) private
Sets string to profile variable.
Parameters
name of the variable
value to set
SetProfileStringList()
proto native void CGame::SetProfileStringList (string name, TStringArray values) private
Sets array of strings to profile variable.
Parameters
name of the variable
values to set
Referenced by AddVisitedServer().
SetUserFOV()
void CGame::SetUserFOV (float pFov) inline protected
Definition at line 3335 of file DayZGame.c.
  {
    if (pFov < OPTIONS_FIELD_OF_VIEW_MIN)
      pFov = OPTIONS_FIELD_OF_VIEW_MIN;
    if (pFov > OPTIONS_FIELD_OF_VIEW_MAX)
      pFov = OPTIONS_FIELD_OF_VIEW_MAX;
    m_UserFOV = pFov;
  }
Referenced by SelectGamepad().
SetVoiceEffect()
proto native void CGame::SetVoiceEffect (Object player, int effect, bool enable) private
Enable/disable VoN effect (only on server)
Parameters
player in question
voice effect (VoiceEffectMumbling = 1, VoiceEffectExtortion = 2, VoiceEffectObstruction = 4)
enable or disable effect
SetVoiceLevel()
proto native void CGame::SetVoiceLevel (int level) private
Set voice level of VoN (only on client) (VoiceLevelWhisper = 0, VoiceLevelNormal = 1, VoiceLevelShout = 2)
Parameters
level of voice
ShouldShowControllerDisconnect()
bool CGame::ShouldShowControllerDisconnect () inline protected
Definition at line 2031 of file DayZGame.c.
  {
    return m_ShouldShowControllerDisconnect;
  }
References m_ShouldShowControllerDisconnect.
StartRandomCutscene()
proto native void CGame::StartRandomCutscene (string world) private
Starts intro.
Referenced by MainMenuLaunch(), and PartyLaunch().
StorageVersion()
proto native void CGame::StorageVersion (int iVersion) private
Set actual storage version - for next save.
Referenced by CGame().
StoreLoginData()
proto native void CGame::StoreLoginData (ParamsWriteContext ctx) private
Stores login userdata as parameters which are sent to server.
Referenced by StoreLoginDataPrepare().
StoreLoginDataPrepare()
void CGame::StoreLoginDataPrepare () inline protected
Definition at line 1822 of file DayZGame.c.
  {
    ScriptReadWriteContext ctx = new ScriptReadWriteContext;
    //GetMenuData().RequestGetDefaultCharacterData();
    GetMenuDefaultCharacterData().SerializeCharacterData(ctx.GetWriteContext());
    StoreLoginData(ctx.GetWriteContext());
  }
References GetMenuDefaultCharacterData(), MenuDefaultCharacterData::SerializeCharacterData(), and StoreLoginData().
Referenced by OnPreloadEvent().
SurfaceGetNoiseMultiplier()
proto native float CGame::SurfaceGetNoiseMultiplier (Object directHit, vector pos, int componentIndex) protected
Referenced by CloseCombatEffects(), and FirearmEffects().
SurfaceGetNormal()
proto native vector CGame::SurfaceGetNormal (float x, float z) protected
SurfaceGetSeaLevel()
proto native float CGame::SurfaceGetSeaLevel () protected
SurfaceGetType()
proto void CGame::SurfaceGetType (float x, float z, out string type) protected
SurfaceGetType3D()
proto void CGame::SurfaceGetType3D (float x, float y, float z, out string type) protected
SurfaceIsPond()
proto native bool CGame::SurfaceIsPond (float x, float z) protected
SurfaceIsSea()
proto native bool CGame::SurfaceIsSea (float x, float z) protected
SurfaceRoadY()
proto native float CGame::SurfaceRoadY (float x, float z, RoadSurfaceDetection rsd = RoadSurfaceDetection.LEGACY) protected
Referenced by GetHighestSurfaceYDifference().
SurfaceRoadY3D()
proto native float CGame::SurfaceRoadY3D (float x, float y, float z, RoadSurfaceDetection rsd) protected
SurfaceUnderObject()
proto void CGame::SurfaceUnderObject (notnull Object object, out string type, out int liquidType) protected
SurfaceUnderObjectByBone()
proto void CGame::SurfaceUnderObjectByBone (notnull Object object, int boneType, out string type, out int liquidType) protected
SurfaceUnderObjectEx()
proto void CGame::SurfaceUnderObjectEx (notnull Object object, out string type, out string impact, out int liquidType) protected
SurfaceY()
proto native float CGame::SurfaceY (float x, float z) protected
TryConnect()
void CGame::TryConnect () inline protected
Definition at line 2339 of file DayZGame.c.
  {
    if (GetLoadState() == DayZLoadState.JOIN_CONTROLLER_SELECT)
    {
      SetGameState(DayZGameState.CONNECTING);
      OnlineServices.GetSession();
    }
    else
    {
      if (GetGameState() != DayZGameState.CONNECTING)
      {
        switch (GetLoadState())
        {
        case DayZLoadState.CONNECT_CONTROLLER_SELECT:
        {
          SetGameState(DayZGameState.CONNECTING);
          ConnectFromCLI();
          break;
        }
        case DayZLoadState.PARTY_CONTROLLER_SELECT:
        {
          SetGameState(DayZGameState.CONNECTING);
          Connect();
          break;
        }
        case DayZLoadState.MAIN_MENU_CONTROLLER_SELECT:
        {
          SetGameState(DayZGameState.CONNECTING);
          Connect();
          break;
        }
        }
      }
      else
      {
        string address;
        int port;
        if (GetHostAddress(address, port))
        {
          if (m_ConnectAddress == address && m_ConnectPort == port)
            ErrorModuleHandler.ThrowError(ErrorCategory.ConnectErrorScript, EConnectErrorScript.ALREADY_CONNECTING_THIS);
          else
            ErrorModuleHandler.ThrowError(ErrorCategory.ConnectErrorScript, EConnectErrorScript.ALREADY_CONNECTING, string.Format("%1:%2", address, port));
        }
        else
        {
          DisconnectSessionForce();
          DisconnectSessionScript();
          TryConnect();
        }
      }
    }
  }
References Connect(), ConnectFromCLI(), DisconnectSessionForce(), DisconnectSessionScript(), GetGameState(), GetHostAddress(), GetLoadState(), OnlineServices::GetSession(), SetGameState(), ErrorModuleHandler::ThrowError(), and TryConnect().
Referenced by TryConnect().
UpdateInputDeviceDisconnectWarning()
void CGame::UpdateInputDeviceDisconnectWarning () inline protected
Definition at line 2036 of file DayZGame.c.
  {
#ifdef PLATFORM_CONSOLE
    if (!GetUIManager().IsMenuOpen(MENU_WARNING_INPUTDEVICE_DISCONNECT))
    {
      m_ShouldShowControllerDisconnect = !GetInput().AreAllAllowedInputDevicesActive();
      if (m_ShouldShowControllerDisconnect)
        GetCallQueue(CALL_CATEGORY_GUI).Call(GetUIManager().EnterScriptedMenu, MENU_WARNING_INPUTDEVICE_DISCONNECT, GetUIManager().GetMenu());
    }
#endif
  }
References CALL_CATEGORY_GUI, GetCallQueue(), GetInput(), GetUIManager(), and MENU_WARNING_INPUTDEVICE_DISCONNECT.
Referenced by LoadingHide(), and OnEvent().
UpdateLoginQueue()
void CGame::UpdateLoginQueue (float timeslice) inline protected
Display login queue position dialog
manually update static login queue dialog
Definition at line 1695 of file DayZGame.c.
  {
    int pos = GetUIManager().GetLoginQueuePosition();
    if (!m_LoginQueue && pos > 0)
    {
      GetUIManager().CloseAll();
      if (GetMission())
      {
        UIScriptedMenu parent = GetUIManager().GetMenu();
        EnterLoginQueue(parent);
      }
      else
      {
        m_LoginQueue = new LoginQueueStatic();
        GetUIManager().ShowScriptedMenu(m_LoginQueue, null);
      }
    }
    if (m_LoginQueue)
    {
      m_LoginQueue.SetPosition(pos);
      LoginQueueStatic loginQueue;
      if (LoginQueueBase.CastTo(loginQueue, m_LoginQueue))
        loginQueue.Update(timeslice);
    }
  }
References EnterLoginQueue(), GetMission(), and GetUIManager().
Referenced by OnUpdate().
UpdatePathgraphRegion()
proto native void CGame::UpdatePathgraphRegion (vector regionMin, vector regionMax) protected
Referenced by UpdatePathgraphRegionByObject().
UpdatePathgraphRegionByObject()
void CGame::UpdatePathgraphRegionByObject (Object object) inline protected
Definition at line 1099 of file Game.c.
  {
    if (object)
    {
      vector pos = object.GetPosition();
      vector min_max[2];
      float radius = object.ClippingInfo(min_max);
      vector min = Vector(pos[0] - radius, pos[1], pos[2] - radius);
      vector max = Vector(pos[0] + radius, pos[1], pos[2] + radius);
      UpdatePathgraphRegion(min, max);
    }
  }
References UpdatePathgraphRegion(), and Vector().
UpdateSpectatorPosition()
proto native void CGame::UpdateSpectatorPosition (vector position) private
Updates spectator position on server = position of network bubble.
Parameters
position
UpdateVoiceLevel()
void CGame::UpdateVoiceLevel (int level) inline protected
Definition at line 3305 of file DayZGame.c.
  {
    GetMission().UpdateVoiceLevelWidgets(level);
  }
References GetMission().
VerifyWorldOwnership()
proto native bool CGame::VerifyWorldOwnership (string sWorldName) private
Member Data Documentation
ARROW_PIERCE_DEPTH
const float CGame::ARROW_PIERCE_DEPTH = 0.05 protected
Definition at line 3158 of file DayZGame.c.
Referenced by OnProjectileStoppedInObject(), and OnProjectileStoppedInTerrain().
Event_OnRPC
ref ScriptInvoker CGame::Event_OnRPC = new ScriptInvoker() static private
Definition at line 925 of file DayZGame.c.
GameScript
ScriptModule CGame::GameScript private
Definition at line 12 of file Game.c.
Referenced by CallQueueContext::CallParams().
m_AimLoggingEnabled
bool CGame::m_AimLoggingEnabled private
Definition at line 897 of file DayZGame.c.
Referenced by IsAimLogEnabled().
m_AmmoShakeParams
ref AmmoCamParams CGame::m_AmmoShakeParams = new AmmoCamParams() static private
Definition at line 923 of file DayZGame.c.
m_AnalyticsManagerClient
ref AnalyticsManagerClient CGame::m_AnalyticsManagerClient private
Definition at line 18 of file Game.c.
Referenced by CGame(), and GetAnalyticsClient().
m_AnalyticsManagerServer
ref AnalyticsManagerServer CGame::m_AnalyticsManagerServer private
Definition at line 17 of file Game.c.
Referenced by CGame(), and GetAnalyticsServer().
m_ArtySound
ref EffectSound CGame::m_ArtySound private
Definition at line 936 of file DayZGame.c.
m_Backlit
ref Backlit CGame::m_Backlit private
Definition at line 927 of file DayZGame.c.
Referenced by GetBacklit().
m_BillboardSetHandler
ref BillboardSetHandler CGame::m_BillboardSetHandler protected
Definition at line 851 of file DayZGame.c.
Referenced by GetBillboardHandler().
m_callQueue
ref ScriptCallQueue CGame::m_callQueue[CALL_CATEGORY_COUNT] private
Definition at line 876 of file DayZGame.c.
m_CharacterData
ref MenuDefaultCharacterData CGame::m_CharacterData private
Definition at line 19 of file Game.c.
Referenced by GetMenuDefaultCharacterData().
m_CharClassNames
ref array<string> CGame::m_CharClassNames = new array<string>() private
Definition at line 929 of file DayZGame.c.
Referenced by ListAvailableCharacters().
m_ConnectAddress
string CGame::m_ConnectAddress protected
Definition at line 1970 of file DayZGame.c.
m_ConnectedInputDeviceList
ref array<int> CGame::m_ConnectedInputDeviceList private
Definition at line 930 of file DayZGame.c.
Referenced by GetConnectedInputDeviceList().
m_ConnectFromJoin
bool CGame::m_ConnectFromJoin private
Definition at line 902 of file DayZGame.c.
m_connectionLost
ref ConnectionLost CGame::m_connectionLost private
Definition at line 874 of file DayZGame.c.
m_ConnectivityStatsStates
EConnectivityStatLevel CGame::m_ConnectivityStatsStates[STATS_COUNT] private
Definition at line 858 of file DayZGame.c.
m_ConnectPassword
string CGame::m_ConnectPassword protected
Definition at line 1972 of file DayZGame.c.
m_ConnectPort
int CGame::m_ConnectPort protected
Definition at line 1971 of file DayZGame.c.
m_CrashSound
ref EffectSound CGame::m_CrashSound private
Definition at line 933 of file DayZGame.c.
m_CursorDesiredVisibilityScript
bool CGame::m_CursorDesiredVisibilityScript = true private
Definition at line 904 of file DayZGame.c.
Referenced by GetMouseCursorDesiredVisibility().
m_DatabaseID
string CGame::m_DatabaseID protected
Definition at line 1968 of file DayZGame.c.
Referenced by GetDatabaseID().
m_DayZProfileOptions
ref DayZProfilesOptions CGame::m_DayZProfileOptions private
Definition at line 880 of file DayZGame.c.
m_DebugMonitorEnabled
int CGame::m_DebugMonitorEnabled private
Definition at line 10 of file Game.c.
Referenced by IsDebugMonitor(), and SetDebugMonitorEnabled().
m_DeltaTime
float CGame::m_DeltaTime private
Definition at line 908 of file DayZGame.c.
Referenced by GetDeltaT().
m_dragQueue
ref DragQueue CGame::m_dragQueue private
Definition at line 879 of file DayZGame.c.
Referenced by GetDragQueue().
m_early_access_dialog_accepted
bool CGame::m_early_access_dialog_accepted private
Definition at line 881 of file DayZGame.c.
m_EVValue
float CGame::m_EVValue = 0 private
Definition at line 917 of file DayZGame.c.
Referenced by GetCurrentEVValue(), and SetEVValue().
m_FirstConnect
bool CGame::m_FirstConnect = true protected
Definition at line 866 of file DayZGame.c.
m_FoodDecayModifier
float CGame::m_FoodDecayModifier private
Definition at line 893 of file DayZGame.c.
Referenced by GetFoodDecayModifier().
m_GamepadDisconnectMenu
ref Widget CGame::m_GamepadDisconnectMenu protected
Definition at line 1965 of file DayZGame.c.
m_GameState
DayZGameState CGame::m_GameState protected
Definition at line 863 of file DayZGame.c.
Referenced by GetGameState().
m_IntroMenu
ref Widget CGame::m_IntroMenu protected
Definition at line 1964 of file DayZGame.c.
Referenced by DeleteTitleScreen().
m_IsConnecting
bool CGame::m_IsConnecting private
Definition at line 901 of file DayZGame.c.
Referenced by IsConnecting().
m_IsCtrlHolding
bool CGame::m_IsCtrlHolding private
Definition at line 886 of file DayZGame.c.
Referenced by IsLeftCtrlDown().
m_IsFoodDecayEnabled
bool CGame::m_IsFoodDecayEnabled = true private
Definition at line 892 of file DayZGame.c.
m_IsLeftAltHolding
bool CGame::m_IsLeftAltHolding private
Definition at line 888 of file DayZGame.c.
m_IsNewCharacter
bool CGame::m_IsNewCharacter private
Definition at line 900 of file DayZGame.c.
Referenced by IsNewCharacter().
m_IsRightAltHolding
bool CGame::m_IsRightAltHolding private
Definition at line 889 of file DayZGame.c.
m_IsStressTest
bool CGame::m_IsStressTest private
Definition at line 896 of file DayZGame.c.
Referenced by IsStressTest().
m_IsWinHolding
bool CGame::m_IsWinHolding private
Definition at line 887 of file DayZGame.c.
m_IsWorldWetTempUpdateEnabled
bool CGame::m_IsWorldWetTempUpdateEnabled = true private
Definition at line 891 of file DayZGame.c.
Referenced by IsWorldWetTempUpdateEnabled().
m_keyboard_handler
UIScriptedMenu CGame::m_keyboard_handler private
Definition at line 882 of file DayZGame.c.
m_loading
ref LoadingScreen CGame::m_loading protected
Definition at line 869 of file DayZGame.c.
m_LoadState
DayZLoadState CGame::m_LoadState protected
Definition at line 864 of file DayZGame.c.
Referenced by GetLoadState().
m_LoginQueue
ref LoginQueueBase CGame::m_LoginQueue private
Definition at line 871 of file DayZGame.c.
Referenced by CancelLoginQueue().
m_LoginTime
int CGame::m_LoginTime private
Definition at line 872 of file DayZGame.c.
m_LoginTimeScreen
ref LoginTimeBase CGame::m_LoginTimeScreen private
Definition at line 870 of file DayZGame.c.
Referenced by CancelLoginTimeCountdown().
m_mission_module
ScriptModule CGame::m_mission_module private
Definition at line 883 of file DayZGame.c.
m_MissionFolderPath
string CGame::m_MissionFolderPath private
Definition at line 885 of file DayZGame.c.
Referenced by GetMissionFolderPath().
m_MissionPath
string CGame::m_MissionPath private
Definition at line 884 of file DayZGame.c.
Referenced by GetMissionPath().
m_MissionState
int CGame::m_MissionState private
Definition at line 860 of file DayZGame.c.
Referenced by GetMissionState().
m_NoiseParams
ref NoiseParams CGame::m_NoiseParams = new NoiseParams() static private
Definition at line 939 of file DayZGame.c.
m_Notifications
ref NotificationUI CGame::m_Notifications protected
Definition at line 865 of file DayZGame.c.
m_OriginalCharactersCount
int CGame::m_OriginalCharactersCount private
Definition at line 898 of file DayZGame.c.
m_ParamCache
ref array<ref Param> CGame::m_ParamCache private
Definition at line 14 of file Game.c.
Referenced by CGame(), RPCSelfSingleParam(), and RPCSingleParam().
m_PlayerName
string CGame::m_PlayerName private
Definition at line 899 of file DayZGame.c.
Referenced by GetPlayerGameName().
m_postUpdateQueue
ref ScriptInvoker CGame::m_postUpdateQueue[CALL_CATEGORY_COUNT] private
Definition at line 878 of file DayZGame.c.
m_PrevBlur
int CGame::m_PrevBlur protected
Definition at line 1966 of file DayZGame.c.
m_PreviousEVValue
float CGame::m_PreviousEVValue private
Definition at line 916 of file DayZGame.c.
Referenced by GetPreviousEVValue().
m_PreviousGamepad
int CGame::m_PreviousGamepad private
Definition at line 905 of file DayZGame.c.
Referenced by GetPreviousGamepad().
m_ReportModded
bool CGame::m_ReportModded static private
Definition at line 895 of file DayZGame.c.
Referenced by ReportModded().
m_ShouldShowControllerDisconnect
bool CGame::m_ShouldShowControllerDisconnect private
Definition at line 903 of file DayZGame.c.
Referenced by ShouldShowControllerDisconnect().
m_timerQueue
ref TimerQueue CGame::m_timerQueue[CALL_CATEGORY_COUNT] private
Definition at line 875 of file DayZGame.c.
m_updateQueue
ref ScriptInvoker CGame::m_updateQueue[CALL_CATEGORY_COUNT] private
Definition at line 877 of file DayZGame.c.
m_UserFOV
float CGame::m_UserFOV private
Definition at line 906 of file DayZGame.c.
Referenced by GetUserFOV().
m_Visited
ref TStringArray CGame::m_Visited protected
Definition at line 1975 of file DayZGame.c.
m_volume_music
float CGame::m_volume_music private
Definition at line 912 of file DayZGame.c.
m_volume_radio
float CGame::m_volume_radio private
Definition at line 914 of file DayZGame.c.
m_volume_sound
float CGame::m_volume_sound private
Definition at line 910 of file DayZGame.c.
m_volume_speechEX
float CGame::m_volume_speechEX private
Definition at line 911 of file DayZGame.c.
m_volume_VOIP
float CGame::m_volume_VOIP private
Definition at line 913 of file DayZGame.c.
MAX_VISITED
const int CGame::MAX_VISITED = 50 protected
Definition at line 1974 of file DayZGame.c.
MIN_ARTY_SOUND_RANGE
const int CGame::MIN_ARTY_SOUND_RANGE = 300 private
Definition at line 937 of file DayZGame.c.
MISSION_STATE_FINNISH
const int CGame::MISSION_STATE_FINNISH = 2 protected
Definition at line 855 of file DayZGame.c.
MISSION_STATE_GAME
const int CGame::MISSION_STATE_GAME = 1 protected
Definition at line 854 of file DayZGame.c.
Referenced by DayZGame().
MISSION_STATE_MAINMENU
const int CGame::MISSION_STATE_MAINMENU = 0 protected
Definition at line 853 of file DayZGame.c.
STATS_COUNT
const int CGame::STATS_COUNT = EConnectivityStatType.COUNT private
Definition at line 857 of file DayZGame.c.
Referenced by ClearConnectivityStates().
The documentation for this class was generated from the following files:
scripts/3_Game/DayZGame.c
scripts/3_Game/Global/Game.c