DayZ: scripts/4_World/Entities/ManBase/DayZPlayer/DayZPlayerCamera3rdPerson.c File Reference
DayZPlayerCamera3rdPerson.c File Reference
Classes
class DayZPlayerCameraBase
this is main camera class
class DayZPlayerCamera3rdPersonErc
class DayZPlayerCamera3rdPersonErcRaised
class DayZPlayerCamera3rdPersonCrouch
class DayZPlayerCamera3rdPersonProneBase
Functions
class DayZPlayerCamera3rdPerson extends DayZPlayerCameraBase DayZPlayerCamera3rdPersonErc (DayZPlayer pPlayer, HumanInputController pInput)
void DayZPlayerCamera3rdPerson (DayZPlayer pPlayer, HumanInputController pInput)
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
override vector GetBaseAngles ()
override vector GetAdditiveAngles ()
override string GetCameraName ()
class DayZPlayerCamera3rdPersonJump extends DayZPlayerCamera3rdPersonErc DayZPlayerCamera3rdPersonClimb (DayZPlayer pPlayer, HumanInputController pInput)
void DayZPlayerCamera3rdPersonJump (DayZPlayer pPlayer, HumanInputController pInput)
class DayZPlayerCamera3rdPersonErcSpr extends DayZPlayerCamera3rdPersonErc DayZPlayerCamera3rdPersonErcRaised (DayZPlayer pPlayer, HumanInputController pInput)
void DayZPlayerCamera3rdPersonErcSpr (DayZPlayer pPlayer, HumanInputController pInput)
override bool IsCamera3rdRaised ()
void DayZPlayerCamera3rdPersonCrouch (DayZPlayer pPlayer, HumanInputController pInput)
float UpdateLRAngleLookAt (float pMin, float pMax, float pDt)
class DayZPlayerCamera3rdPersonProne extends DayZPlayerCamera3rdPersonProneBase DayZPlayerCamera3rdPersonProneRaised (DayZPlayer pPlayer, HumanInputController pInput)
void DayZPlayerCamera3rdPersonProne (DayZPlayer pPlayer, HumanInputController pInput)
Variables
static const float CONST_UD_MIN = -85.0
down limit
static const float CONST_UD_MAX = 85.0
up limit
static const float CONST_LR_MIN = -160.0
down limit
static const float CONST_LR_MAX = 160.0
up limit
int m_iBoneIndex = -1
runtime config
vector m_CameraOffsetMS
model space offset
vector m_CameraOffsetLS
local space offset
float m_fDistance
distance from start
float m_fShoulderWidth
shoulder camera widths
bool m_bShoulderInLS
true - shoulder is in local space
float m_fRoll
camera roll (deprecated)
float m_fLeanDistance
shift on leaning
float m_fUpDownAngle
runtime values
float m_fUpDownAngleAdd
up down angle in rad
float m_fLeftRightAngle
left right angle in rad (in freelook only)
float m_fLeftRightAngleAdd
left right angle in rad (in freelook only)
float m_fCameraLRShoulder
shoulder offsets
float m_fCameraLRShoulderVel [1]
float m_fPredictCollisionRadius
collision prediction
ref HumanMovementState m_MovementState = new HumanMovementState()
movement state
float m_fDelay
runtime config
float m_fDamping
float m_fDelayTimer
runtime values
float m_fJumpStartY
float m_fJumpOffset
float m_jumpOffsetVelocity [1]
int m_iPelvisBone
float m_fTime
class DayZPlayerCamera3rdPersonErcRaisedMelee extends DayZPlayerCamera3rdPersonErcRaised CONST_CAMERAMOVEMENTHEIGH = 0.4
float m_fCameraHeight
float m_fCameraHeightVel [1]
class DayZPlayerCamera3rdPersonCrouchRaised extends DayZPlayerCamera3rdPersonCrouch m_BaseOffsetVelX [1]
class DayZPlayerCamera3rdPersonCrouchRaised extends DayZPlayerCamera3rdPersonCrouch m_BaseOffsetVelY [1]
class DayZPlayerCamera3rdPersonCrouchRaised extends DayZPlayerCamera3rdPersonCrouch m_BaseOffsetVelZ [1]
float m_LookAtLRAngle
Function Documentation
DayZPlayerCamera3rdPerson()
void DayZPlayerCamera3rdPersonErc::DayZPlayerCamera3rdPerson (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 159 of file DayZPlayerCamera3rdPerson.c.
{
  void DayZPlayerCamera3rdPersonJump(DayZPlayer pPlayer, HumanInputController pInput)
  {
Referenced by Hologram::GetProjectionEntityPosition().
DayZPlayerCamera3rdPersonClimb()
class DayZPlayerCamera3rdPersonJump extends DayZPlayerCamera3rdPersonErc DayZPlayerCamera3rdPersonClimb (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 168 of file DayZPlayerCamera3rdPerson.c.
  {
    //Print("new camera: DayZPlayerCamera3rdPersonClimb");
    m_fDistance = 1.0;
    m_CameraOffsetMS = "0.0 0.3 -0.6";
    m_iBoneIndex = pPlayer.GetBoneIndexByName("Spine");
    m_fPredictCollisionRadius = 0.5;
  }
Referenced by DayZPlayerCameras::RegisterCameras().
DayZPlayerCamera3rdPersonCrouch()
void DayZPlayerCamera3rdPersonCrouch (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 352 of file DayZPlayerCamera3rdPerson.c.
  {
    //Print("new camera: DayZPlayerCamera3rdPersonCrouch");
    m_fDistance = 1.4;
    m_CameraOffsetMS = "0.0 0.7 0.1";
    m_CameraOffsetLS = "0.0 0.3 0.0";
    m_fShoulderWidth = 0.3;
  }
References m_CameraOffsetLS, m_CameraOffsetMS, m_fDistance, and m_fShoulderWidth.
DayZPlayerCamera3rdPersonErc()
class DayZPlayerCamera3rdPerson extends DayZPlayerCameraBase DayZPlayerCamera3rdPersonErc (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 4 of file DayZPlayerCamera3rdPerson.c.
  {
    //Print("new camera: DayZPlayerCamera3rdPersonErc");
    m_fDistance = 1.6;
    m_CameraOffsetMS = "0.0 1.4 0.0";
    m_CameraOffsetLS = "0.0 0.3 0.0";
    m_fShoulderWidth = 0.3;
    m_fPredictCollisionRadius = 1.2;
  }
References CONST_LR_MAX, CONST_LR_MIN, CONST_UD_MAX, and CONST_UD_MIN.
DayZPlayerCamera3rdPersonErcRaised()
class DayZPlayerCamera3rdPersonErcSpr extends DayZPlayerCamera3rdPersonErc DayZPlayerCamera3rdPersonErcRaised (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 234 of file DayZPlayerCamera3rdPerson.c.
  {
    //Print("new camera: DayZPlayerCamera3rdPersonErcRaised");
    m_fPredictCollisionRadius = 0.2;
    if (pPlayer.GetCurrentPerItemCameraUD() == DayZPlayerCameras.PERITEMUD_EMPTYHANDED)
    {
      // no item in hands
      m_fDistance = 1.2;
      m_fShoulderWidth = 0.4;
      m_CameraOffsetMS = "0.0 1.3 0.2";
      m_CameraOffsetLS = "0.0 0.3 0.0";
    }
    else if (pPlayer.GetCurrentPerItemCameraUD() == DayZPlayerCameras.PERITEMUD_TWOHANDED)
    {
      // two handed
      m_fDistance = 1.2;
      m_fShoulderWidth = 0.4;
      m_CameraOffsetMS = "0.0 1.3 0.2";
      m_CameraOffsetLS = "0.0 0.3 0.0";
    }
    else if (pPlayer.GetCurrentPerItemCameraUD() == DayZPlayerCameras.PERITEMUD_ONEHANDED)
    {
      // one handed
      m_fDistance = 1.2;
      m_fShoulderWidth = 0.4;
      m_CameraOffsetMS = "0.0 1.3 0.2";
      m_CameraOffsetLS = "0.0 0.3 0.0";
    }
    else
    {
      // weapons in hands
      m_fDistance = 0.8;
      m_CameraOffsetMS = "0.0 1.3 0.2";
      m_CameraOffsetLS = "0.0 0.3 0.0";
      m_fShoulderWidth = 0.5;
    }
  }
DayZPlayerCamera3rdPersonErcSpr()
void DayZPlayerCamera3rdPersonErcRaised::DayZPlayerCamera3rdPersonErcSpr (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 286 of file DayZPlayerCamera3rdPerson.c.
  {
    //Print("new camera: DayZPlayerCamera3rdPersonErcRaised");
    m_fPredictCollisionRadius = 0.2;
    if (pPlayer.GetCurrentPerItemCameraUD() == DayZPlayerCameras.PERITEMUD_EMPTYHANDED)
    {
      // no item in hands
      m_fDistance = 1.2;
      m_fShoulderWidth = 0.4;
      m_CameraOffsetMS = "0.0 1.3 0.2";
      m_CameraOffsetLS = "0.0 0.3 0.0";
    }
    else if (pPlayer.GetCurrentPerItemCameraUD() == DayZPlayerCameras.PERITEMUD_TWOHANDED)
    {
Referenced by DayZPlayerCameras::RegisterCameras().
DayZPlayerCamera3rdPersonJump()
void DayZPlayerCamera3rdPersonClimb::DayZPlayerCamera3rdPersonJump (DayZPlayer pPlayer, HumanInputController pInput)
runtime config
runtime values
Definition at line 222 of file DayZPlayerCamera3rdPerson.c.
  {
    //Print("new camera: DayZPlayerCamera3rdPersonClimb");
    m_fDistance = 1.0;
    m_CameraOffsetMS = "0.0 0.3 -0.6";
    m_iBoneIndex = pPlayer.GetBoneIndexByName("Spine");
    m_fPredictCollisionRadius = 0.5;
  }
}
// *************************************************************************************
// ! DayZPlayerCamera3rdPersonErc - 3rd person erected sprint
// *************************************************************************************
class DayZPlayerCamera3rdPersonErcSpr extends DayZPlayerCamera3rdPersonErc
References m_CameraOffsetMS, m_fDistance, m_fPredictCollisionRadius, and m_iBoneIndex.
Referenced by DayZPlayerCameras::RegisterCameras().
DayZPlayerCamera3rdPersonProne()
void DayZPlayerCamera3rdPersonProneRaised::DayZPlayerCamera3rdPersonProne (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 527 of file DayZPlayerCamera3rdPerson.c.
  {
    //Print("new camera: DayZPlayerCamera3rdPersonProneRaised");
    m_iBoneIndex = pPlayer.GetBoneIndexByName("Camera3rd_Helper");
    m_fDistance = 1.0;
    m_CameraOffsetMS = "0.0 0.4 0.0";
    m_CameraOffsetLS = "0.0 0.2 0.0";
    m_fShoulderWidth = 0.5;
  }
References m_CameraOffsetLS, m_CameraOffsetMS, m_fDistance, m_fShoulderWidth, and m_iBoneIndex.
Referenced by DayZPlayerCameras::RegisterCameras().
DayZPlayerCamera3rdPersonProneRaised()
class DayZPlayerCamera3rdPersonProne extends DayZPlayerCamera3rdPersonProneBase DayZPlayerCamera3rdPersonProneRaised (DayZPlayer pPlayer, HumanInputController pInput) protected
Definition at line 507 of file DayZPlayerCamera3rdPerson.c.
  {
    //Print("new camera: DayZPlayerCamera3rdPersonProneRaised");
    m_iBoneIndex = pPlayer.GetBoneIndexByName("Camera3rd_Helper");
    m_fDistance = 1.0;
    m_CameraOffsetMS = "0.0 0.4 0.0";
    m_CameraOffsetLS = "0.0 0.2 0.0";
    m_fShoulderWidth = 0.5;
  }
Referenced by DayZPlayerCameras::RegisterCameras().
GetAdditiveAngles()
override vector DayZPlayerCamera3rdPersonErc::GetAdditiveAngles ()
Definition at line 251 of file DayZPlayerCamera3rdPerson.c.
  {
    m_fTime += pDt * 5;
    vector tm[4];
GetBaseAngles()
override vector DayZPlayerCamera3rdPersonErc::GetBaseAngles ()
Definition at line 242 of file DayZPlayerCamera3rdPerson.c.
                                            : hips bone not found");
    m_fTime = 0.0;
GetCameraName()
override string DayZPlayerCamera3rdPersonErc::GetCameraName ()
Definition at line 260 of file DayZPlayerCamera3rdPerson.c.
IsCamera3rdRaised()
override bool IsCamera3rdRaised ()
Definition at line 325 of file DayZPlayerCamera3rdPerson.c.
  {
    return true;
  }
OnActivate()
override void DayZPlayerCamera3rdPersonErc::OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
Definition at line 175 of file DayZPlayerCamera3rdPerson.c.
  {
    super.OnUpdate(pDt, pOutResult);
    float yPos = m_pPlayer.GetOrigin()[1];
OnUpdate()
override void DayZPlayerCamera3rdPersonErc::OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
update angles from input
base bone pos
apply shoulder dist
store distance
basically -> transform up vector (0,1,0) and read x coord -> and set is as roll
prev update
movement height
prev update
update angles from input
this is actually negative to yaw
base bone pos
apply shoulder dist
store distance
Definition at line 192 of file DayZPlayerCamera3rdPerson.c.
    {
      m_fDelayTimer += pDt;
      m_fJumpOffset = yDiff;
    }
    else
      m_fJumpOffset = Math.SmoothCD(m_fJumpOffset, -(m_fDamping * yDiff), m_jumpOffsetVelocity, 0.3, 1000, pDt);
    float newY = pOutResult.m_CameraTM[3][1] - m_fJumpOffset;
    pOutResult.m_CameraTM[3][1] = newY;
  }
  float m_fDelay;
  float m_fDamping;
  float m_fDelayTimer;
  float m_fJumpStartY;
  float m_fJumpOffset;
  float m_jumpOffsetVelocity[1];
}
// *************************************************************************************
// ! DayZPlayerCamera3rdPersonJump - 3rd person jump
// *************************************************************************************
class DayZPlayerCamera3rdPersonClimb extends DayZPlayerCamera3rdPersonErc
{
  void DayZPlayerCamera3rdPersonClimb(DayZPlayer pPlayer, HumanInputController pInput)
  {
    //Print("new camera: DayZPlayerCamera3rdPersonClimb");
    m_fDistance = 1.0;
    m_CameraOffsetMS = "0.0 0.3 -0.6";
    m_iBoneIndex = pPlayer.GetBoneIndexByName("Spine");
    m_fPredictCollisionRadius = 0.5;
  }
}
// *************************************************************************************
// ! DayZPlayerCamera3rdPersonErc - 3rd person erected sprint
// *************************************************************************************
class DayZPlayerCamera3rdPersonErcSpr extends DayZPlayerCamera3rdPersonErc
{
  void DayZPlayerCamera3rdPersonErcSpr(DayZPlayer pPlayer, HumanInputController pInput)
  {
    //Print("new camera: DayZPlayerCamera3rdPersonErcSpr");
    m_fDistance = 2.0;
References m_fDelayTimer, and m_fJumpOffset.
UpdateLRAngleLookAt()
float UpdateLRAngleLookAt (float pMin, float pMax, float pDt) protected
lr angle
Definition at line 413 of file DayZPlayerCamera3rdPerson.c.
  {
    if (m_pInput.CameraIsFreeLook() || m_bForceFreeLook)
    {
      m_LookAtLRAngle += m_pInput.GetAimChange()[0] * Math.RAD2DEG;
      m_LookAtLRAngle = Limit(m_LookAtLRAngle, pMin, pMax);
      m_fLRAngleVel[0] = 0; // reset filter
    }
    else
    {
      // smooth value back to 0
      m_LookAtLRAngle = Math.SmoothCD(m_LookAtLRAngle, 0, m_fLRAngleVel, 0.14, 1000, pDt);
      // m_fLeftRightAngle  = 0.9 * (1.0 - pDt);
    }
    return m_LookAtLRAngle;
  }
References HumanInputController::CameraIsFreeLook(), HumanInputController::GetAimChange(), Limit(), m_bForceFreeLook, m_fLRAngleVel, m_LookAtLRAngle, m_pInput, Math::RAD2DEG, and Math::SmoothCD().
Variable Documentation
CONST_CAMERAMOVEMENTHEIGH
class DayZPlayerCamera3rdPersonErcRaisedMelee extends DayZPlayerCamera3rdPersonErcRaised CONST_CAMERAMOVEMENTHEIGH = 0.4
CONST_LR_MAX
const float CONST_LR_MAX = 160.0 static
up limit
Definition at line 157 of file DayZPlayerCamera3rdPerson.c.
CONST_LR_MIN
const float CONST_LR_MIN = -160.0 static
down limit
Definition at line 156 of file DayZPlayerCamera3rdPerson.c.
CONST_UD_MAX
const float CONST_UD_MAX = 85.0 static
up limit
Definition at line 154 of file DayZPlayerCamera3rdPerson.c.
CONST_UD_MIN
const float CONST_UD_MIN = -85.0 static
down limit
Definition at line 153 of file DayZPlayerCamera3rdPerson.c.
m_BaseOffsetVelX
class DayZPlayerCamera3rdPersonCrouchRaised extends DayZPlayerCamera3rdPersonCrouch m_BaseOffsetVelX[1] protected
m_BaseOffsetVelY
class DayZPlayerCamera3rdPersonCrouchRaised extends DayZPlayerCamera3rdPersonCrouch m_BaseOffsetVelY[1] protected
m_BaseOffsetVelZ
class DayZPlayerCamera3rdPersonCrouchRaised extends DayZPlayerCamera3rdPersonCrouch m_BaseOffsetVelZ[1] protected
m_bShoulderInLS
bool m_bShoulderInLS protected
true - shoulder is in local space
Definition at line 271 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCameraBase::OnUpdate().
m_CameraOffsetLS
vector m_CameraOffsetLS protected
local space offset
Definition at line 268 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCamera3rdPersonCrouch(), DayZPlayerCamera3rdPersonCrouch::DayZPlayerCamera3rdPersonCrouchRaised(), DayZPlayerCamera3rdPersonProneBase::DayZPlayerCamera3rdPersonProne(), and DayZPlayerCamera3rdPersonProne().
m_CameraOffsetMS
vector m_CameraOffsetMS protected
model space offset
Definition at line 267 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCamera3rdPersonCrouch(), DayZPlayerCamera3rdPersonCrouch::DayZPlayerCamera3rdPersonCrouchRaised(), DayZPlayerCamera3rdPersonErc::DayZPlayerCamera3rdPersonErcSpr(), DayZPlayerCamera3rdPersonJump(), DayZPlayerCamera3rdPersonProneBase::DayZPlayerCamera3rdPersonProne(), DayZPlayerCamera3rdPersonProne(), and DayZPlayerCamera3rdPersonVehicle().
m_fCameraHeight
float m_fCameraHeight protected
Definition at line 377 of file DayZPlayerCamera3rdPerson.c.
m_fCameraHeightVel
float m_fCameraHeightVel[1] protected
Definition at line 378 of file DayZPlayerCamera3rdPerson.c.
m_fCameraLRShoulder
float m_fCameraLRShoulder protected
shoulder offsets
Definition at line 283 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCameraBase::DayZPlayerCamera3rdPerson(), and DayZPlayerCameraBase::OnUpdate().
m_fCameraLRShoulderVel
float m_fCameraLRShoulderVel[1] protected
Definition at line 284 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCameraBase::DayZPlayerCamera3rdPerson(), and DayZPlayerCameraBase::OnUpdate().
m_fDamping
float m_fDamping
Definition at line 259 of file DayZPlayerCamera3rdPerson.c.
m_fDelay
float m_fDelay
runtime config
Definition at line 258 of file DayZPlayerCamera3rdPerson.c.
m_fDelayTimer
float m_fDelayTimer
runtime values
Definition at line 262 of file DayZPlayerCamera3rdPerson.c.
Referenced by OnUpdate().
m_fDistance
float m_fDistance protected
distance from start
Definition at line 269 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCamera3rdPersonCrouch().
m_fJumpOffset
float m_fJumpOffset
Definition at line 264 of file DayZPlayerCamera3rdPerson.c.
Referenced by OnUpdate().
m_fJumpStartY
float m_fJumpStartY
Definition at line 263 of file DayZPlayerCamera3rdPerson.c.
m_fLeanDistance
float m_fLeanDistance protected
shift on leaning
Definition at line 273 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCameraBase::DayZPlayerCamera3rdPerson().
m_fLeftRightAngle
float m_fLeftRightAngle protected
left right angle in rad (in freelook only)
Definition at line 279 of file DayZPlayerCamera3rdPerson.c.
m_fLeftRightAngleAdd
float m_fLeftRightAngleAdd protected
left right angle in rad (in freelook only)
Definition at line 280 of file DayZPlayerCamera3rdPerson.c.
m_fPredictCollisionRadius
float m_fPredictCollisionRadius protected
collision prediction
Definition at line 287 of file DayZPlayerCamera3rdPerson.c.
m_fRoll
float m_fRoll protected
camera roll (deprecated)
Definition at line 272 of file DayZPlayerCamera3rdPerson.c.
m_fShoulderWidth
float m_fShoulderWidth protected
shoulder camera widths
Definition at line 270 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCamera3rdPersonCrouch(), DayZPlayerCamera3rdPersonCrouch::DayZPlayerCamera3rdPersonCrouchRaised(), DayZPlayerCamera3rdPersonProneBase::DayZPlayerCamera3rdPersonProne(), DayZPlayerCamera3rdPersonProne(), and DayZPlayerCameraBase::OnUpdate().
m_fTime
float m_fTime protected
Definition at line 325 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCamera3rdPersonErc::OnUpdate().
m_fUpDownAngle
float m_fUpDownAngle protected
runtime values
up down angle in rad
Definition at line 277 of file DayZPlayerCamera3rdPerson.c.
m_fUpDownAngleAdd
float m_fUpDownAngleAdd protected
up down angle in rad
Definition at line 278 of file DayZPlayerCamera3rdPerson.c.
m_iBoneIndex
int m_iBoneIndex = -1 protected
runtime config
main bone
Definition at line 266 of file DayZPlayerCamera3rdPerson.c.
m_iPelvisBone
int m_iPelvisBone protected
Definition at line 324 of file DayZPlayerCamera3rdPerson.c.
m_jumpOffsetVelocity
float m_jumpOffsetVelocity[1]
Definition at line 265 of file DayZPlayerCamera3rdPerson.c.
m_LookAtLRAngle
float m_LookAtLRAngle protected
Definition at line 411 of file DayZPlayerCamera3rdPerson.c.
Referenced by UpdateLRAngleLookAt().
m_MovementState
ref HumanMovementState m_MovementState = new HumanMovementState() protected
movement state
Definition at line 290 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayer::AimingModel(), ManBase::BrokenLegForceProne(), ManBase::BrokenLegWalkShock(), DayZPlayer::CameraHandler(), DayZPlayer::CanClimb(), DayZPlayer::CanJump(), DayZPlayer::CommandHandler(), ManBase::CommandHandler(), InjurySoundHandlerBase::DetermineInjuryZone(), DayZPlayer::EvaluateDamageHit(), DayZPlayer::EvaluateDamageHitAnimation(), ManBase::GetFeetDamageMoveModifier(), DayZPlayer::HandleADS(), DayZPlayer::HandleView(), DayZPlayer::HandleWeapons(), DayZPlayer::HeadingModel(), ManBase::HeadingModel(), ManBase::IsClimbing(), DayZPlayer::IsClimbingLadder(), ManBase::IsFalling(), DayZPlayer::IsFireWeaponRaised(), ManBase::IsInProne(), ManBase::IsInRasedProne(), DayZPlayer::IsInVehicle(), ManBase::IsLeaning(), ManBase::IsSprinting(), DayZPlayer::IsSwimming(), ManBase::IsUnconscious(), ManBase::OnCommandHandlerTick(), DayZPlayer::OnMovementChanged(), DayZPlayerCameraBase::OnUpdate(), and ManBase::UpdateBrokenLegs().