DayZ: array< TimerBase > Class Reference
array< TimerBase > Class Reference
Tools
TimerQueue Class using for system purpose only.
Private Member Functions
void TimerQueue ()
void ~TimerQueue ()
void Tick (float timeslice)
Private Attributes
bool m_processing
Detailed Description
TimerQueue Class using for system purpose only.
Definition at line 362 of file tools.c.
Constructor & Destructor Documentation
~TimerQueue()
void array< TimerBase >::~TimerQueue () inline private
Definition at line 373 of file tools.c.
  {
    if (Count())
    {
      for (int i = Count() - 1; i >= 0; i--)
        Get(i).OnTimerQueueDestoryed();
      Clear();
    }
  }
References Clear(), Count, and Get().
Member Function Documentation
Tick()
void array< TimerBase >::Tick (float timeslice) inline private
Definition at line 385 of file tools.c.
  {
    if (m_processing) return;
    m_processing = true;
    if (Count())
    {
      for (int i = Count() - 1; i >= 0; i--)
        Get(i).Tick(timeslice);
    }
    m_processing = false;
  }
References Count, and Get().
TimerQueue()
void array< TimerBase >::TimerQueue () inline private
Definition at line 367 of file tools.c.
  {
    m_processing = false;
  }
Member Data Documentation
m_processing
bool array< TimerBase >::m_processing private
Definition at line 364 of file tools.c.
The documentation for this class was generated from the following file:
scripts/3_Game/tools/tools.c