DayZ: scripts/3_Game/gameplay.c File Reference
gameplay.c File Reference
Classes
class JsonSerializer
Class for sending RPC over network.
class ScriptRPC
class ScriptInputUserData
class ScriptReadWriteContext
class ScriptRemoteInputUserData
class ScriptJunctureData
class MeleeCombatData
class Selection
Selection class.
class LOD
LOD class.
class ObjectTyped
class Entity
class ItemPreviewWidget
class PlayerPreviewWidget
class RichTextWidget
class MapWidget
class PlayerIdentityBase
Player description (base engine class)
class PlayerIdentity
The class that will be instanced (moddable)
class CursorIcons
class Hud
class Mission
Mission class.
class MenuData
class MenuDefaultCharacterData
class OptionsAccess
class OptionsAccessEvents
Invokers for ParticleManager events.
class GameOptions
class Static
class PrtTest
Typedefs
typedef Serializer ParamsReadContext
typedef Serializer ParamsWriteContext
typedef int ChatChannel
typedef Param3< int, float, string > ProgressEventParams
state, progress, title
typedef Param1< string > ScriptLogEventParams
typedef Param4< int, string, string, string > ChatMessageEventParams
channel, from, text, color config class
typedef Param1< int > ChatChannelEventParams
typedef Param1< int > SQFConsoleEventParams
typedef Param2< string, string > ClientConnectedEventParams
Name, uid.
typedef Param5< PlayerIdentity, bool, vector, float, int > ClientPrepareEventParams
PlayerIdentity, useDB, pos, yaw, preloadTimeout (= additional time in seconds to how long server waits for loginData)
typedef Param3< PlayerIdentity, vector, Serializer > ClientNewEventParams
PlayerIdentity, PlayerPos, Top, Bottom, Shoe, Skin.
typedef Param2< PlayerIdentity, Man > ClientNewReadyEventParams
PlayerIdentity, Man.
typedef Param2< PlayerIdentity, Man > ClientRespawnEventParams
PlayerIdentity, Man.
typedef Param2< PlayerIdentity, Man > ClientReadyEventParams
PlayerIdentity, Man.
typedef Param2< PlayerIdentity, Man > ClientReconnectEventParams
PlayerIdentity, Man.
typedef Param4< PlayerIdentity, Man, int, bool > ClientDisconnectedEventParams
PlayerIdentity, Man, LogoutTime, AuthFailed.
typedef Param1< int > LoginTimeEventParams
LoginTime.
typedef Param1< int > RespawnEventParams
RespawnTime.
typedef Param1< vector > PreloadEventParams
Position.
typedef Param1< Man > LogoutCancelEventParams
Player.
typedef Param1< PlayerIdentity > ConnectivityStatsUpdatedEventParams
PlayerIdentity.
typedef Param1< float > ServerFpsStatsUpdatedEventParams
float
typedef Param2< string, string > LoginStatusEventParams
text message for line 1, text message for line 2
typedef Param1< int > LogoutEventParams
logoutTime
typedef Param3< int, int, bool > WindowsResizeEventParams
Width, Height, Windowed.
typedef Param2< bool, bool > VONStateEventParams
listening, toggled
typedef Param2< string, string > VONStartSpeakingEventParams
player name, player id
typedef Param2< string, string > VONStopSpeakingEventParams
player name, player id
typedef Param1< string > DLCOwnerShipFailedParams
world name
typedef Param1< FreeDebugCamera > SetFreeCameraEventParams
Camera.
typedef Param1< int > MPConnectionLostEventParams
Duration.
typedef Param2< int, string > MPConnectionCloseEventParams
EClientKicked, AdditionalInfo.
typedef Param2< DayZPlayer, Object > PlayerDeathEventParams
Player, "Killer" (Beware: Not necessarily actually the killer, Client doesn't have this info)
typedef Link< Object > OLinkT
Enumerations
enum InventoryTraversalType { PREORDER , INORDER , POSTORDER , LEVELORDER }
tree traversal type, for more see http://en.wikipedia.org/wiki/Tree_traversal
enum OptionAccessType {
AT_UNKNOWN , AT_OBJECTS_DETAIL , AT_TEXTURE_DETAIL , AT_HDR_DETAIL ,
AT_FSAA_DETAIL , AT_VSYNC_VALUE , AT_ANISO_DETAIL , AT_OPTIONS_FXAA_VALUE ,
AT_OPTIONS_SW_VALUE , AT_POSTPROCESS_EFFECTS , AT_QUALITY_PREFERENCE , AT_ATOC_DETAIL ,
AT_AMBIENT_OCCLUSION , AT_BLOOM , AT_ROTATION_BLUR , AT_SHADOW_DETAIL ,
AT_OPTIONS_TERRAIN , AT_OPTIONS_RESOLUTION , AT_OPTIONS_GAMMA_SLIDER , AT_OPTIONS_BRIGHT_SLIDER ,
AT_OPTIONS_VISIBILITY_SLIDER , AT_OPTIONS_OBJECT_VISIBILITY_SLIDER , AT_OPTIONS_SHADOW_VISIBILITY_SLIDER , AT_OPTIONS_DRAWDISTANCE_SLIDER ,
AT_ASPECT_RATIO , AT_OPTIONS_FIELD_OF_VIEW , AT_OPTIONS_MUSIC_SLIDER , AT_OPTIONS_EFFECTS_SLIDER ,
AT_OPTIONS_VON_SLIDER , AT_OPTIONS_MASTER_VOLUME , AT_OPTIONS_HWACC , AT_OPTIONS_EAX ,
AT_OPTIONS_LANGUAGE , AT_OPTIONS_RADIO , AT_CONFIG_MOUSE_FILTERING , AT_CONFIG_HEAD_BOB ,
AT_OPTIONS_DISPLAY_MODE , AT_OPTIONS_TERRAIN_SHADER , AT_OPTIONS_AIM_HELPER , AT_OPTIONS_MOUSE_AND_KEYBOARD ,
AT_OPTIONS_PAUSE , AT_OPTIONS_FLIPMODE , AT_OPTIONS_VON_THRESHOLD_SLIDER , AT_OPTIONS_MOUSE_YAXIS_INVERTED ,
AT_OPTIONS_MOUSE_XAXIS , AT_OPTIONS_MOUSE_YAXIS , AT_OPTIONS_MOUSE_XAXIS_AIM_MOD , AT_OPTIONS_MOUSE_YAXIS_AIM_MOD ,
AT_OPTIONS_CONTROLLER_LS_XAXIS , AT_OPTIONS_CONTROLLER_LS_YAXIS , AT_OPTIONS_CONTROLLER_LS_XAXIS_VEHICLE_MOD , AT_OPTIONS_CONTROLLER_RS_YAXIS_INVERTED ,
AT_OPTIONS_CONTROLLER_RS_XAXIS , AT_OPTIONS_CONTROLLER_RS_YAXIS , AT_OPTIONS_CONTROLLER_RS_XAXIS_AIM_MOD , AT_OPTIONS_CONTROLLER_RS_YAXIS_AIM_MOD ,
AT_OPTIONS_VON_INPUT_MODE
}
C++ OptionAccessType.
enum OptionIDsScript {
OPTION_HUD = 100 , OPTION_CROSSHAIR , OPTION_GAME_MESSAGES , OPTION_ADMIN_MESSAGES ,
OPTION_PLAYER_MESSAGES , OPTION_QUICKBAR , OPTION_SERVER_INFO , OPTION_BLEEDINGINDICATION ,
OPTION_CONNECTIVITY_INFO , OPTION_HUD_BRIGHTNESS
}
Used for script-based game options. For anything C++ based, you would most likely use "Option Access Type" above.
Functions
proto native CGame GetGame ()
static string GetPathFromSlotID (int slot_ID)
Returns config path of att. slot category, empty if undefined.
static int GetConfigArrayCountFromSlotID (int slot_ID)
How many 'default equip' types are listed in the corresponding array.
static array< string > GetConfigAttachmentTypes (int slot_ID)
Lists all configured types (if any) for the appropriate attachment.
static array< int > GetAttachmentSlotsArray ()
Lists all customizable InventorySlots.
static array< string > GetConfigArrayNames ()
for conversion of slot ID to config array's string
proto native void WriteValue (float value)
proto native float GetMin ()
proto native float GetMax ()
proto native float GetDefault ()
EntityAI SpawnEntity (string object_name, notnull InventoryLocation inv_loc, int iSetupFlags, int iRotation)
Variables
const int INDEX_NOT_FOUND = -1
class MeleeCombatData NullStringArray [1] = { "" }
class LOD Object
PlayerIdentity PROGRESS_START = 0
const int PROGRESS_FINISH = 1
const int PROGRESS_PROGRESS = 2
const int PROGRESS_UPDATE = 3
const EventType StartupEventTypeID
no params
const EventType WorldCleaupEventTypeID
no params
const EventType MPSessionStartEventTypeID
no params
const EventType MPSessionEndEventTypeID
no params
const EventType MPSessionFailEventTypeID
no params
const EventType MPSessionPlayerReadyEventTypeID
no params
const EventType MPConnectionLostEventTypeID
params: MPConnectionLostEventParams
const EventType MPConnectionCloseEventTypeID
params: MPConnectionCloseEventParams
const EventType ProgressEventTypeID
params: ProgressEventParams
const EventType NetworkManagerClientEventTypeID
no params
const EventType NetworkManagerServerEventTypeID
no params
const EventType DialogQueuedEventTypeID
no params
const EventType ChatMessageEventTypeID
params: ChatMessageEventParams
const EventType ChatChannelEventTypeID
params: ChatChannelEventParams
const EventType ClientConnectedEventTypeID
params: ClientConnectedEventParams
const EventType ClientPrepareEventTypeID
params: ClientPrepareEventParams
const EventType ClientNewEventTypeID
params: ClientNewEventParams
const EventType ClientNewReadyEventTypeID
params: ClientNewReadyEventParams
const EventType ClientRespawnEventTypeID
params: ClientRespawnEventParams
const EventType ClientReconnectEventTypeID
params: ClientReconnectEventParams
const EventType ClientReadyEventTypeID
params: ClientReadyEventParams
const EventType ClientDisconnectedEventTypeID
params: ClientDisconnectedEventParams
const EventType ClientRemovedEventTypeID
no params
const EventType ConnectivityStatsUpdatedEventTypeID
params: ConnectivityStatsUpdatedEventParams
const EventType ServerFpsStatsUpdatedEventTypeID
params: ServerFpsStatsUpdatedEventParams
const EventType LogoutCancelEventTypeID
params: LogoutCancelEventParams
const EventType LoginTimeEventTypeID
params: LoginTimeEventParams
const EventType RespawnEventTypeID
params: RespawnEventParams
const EventType PreloadEventTypeID
params: PreloadEventParams
const EventType LogoutEventTypeID
params: LogoutEventParams
const EventType LoginStatusEventTypeID
params: LoginStatusEventParams
const EventType SelectedUserChangedEventTypeID
no params
const EventType ScriptLogEventTypeID
params: ScriptLogEventParams
const EventType VONStateEventTypeID
params: VONStateEventParams
const EventType VONStartSpeakingEventTypeID
params: VONStartSpeakingEventParams
const EventType VONStopSpeakingEventTypeID
params: VONStopSpeakingEventParams
const EventType VONUserStartedTransmittingAudioEventTypeID
no params
const EventType VONUserStoppedTransmittingAudioEventTypeID
no params
const EventType PartyChatStatusChangedEventTypeID
no params
const EventType DLCOwnerShipFailedEventTypeID
params: DLCOwnerShipFailedParams
const EventType SetFreeCameraEventTypeID
params: SetFreeCameraEventParams
const EventType ConnectingStartEventTypeID
no params
const EventType ConnectingAbortEventTypeID
no params
const EventType PlayerDeathEventTypeID
params: PlayerDeathEventParams
class MenuDefaultCharacterData m_AttachmentSlots
static ref array< string > m_ConfigArrayNames
static const string m_Path = "cfgCharacterCreation"
ref ScriptInvoker Event_OnRevert = new ScriptInvoker()
class ListOptionsAccess extends OptionsAccess ReadValue
Typedef Documentation
ChatChannel
typedef int ChatChannel
Definition at line 387 of file gameplay.c.
ChatChannelEventParams
typedef Param1<int> ChatChannelEventParams
Definition at line 395 of file gameplay.c.
ChatMessageEventParams
typedef Param4<int, string, string, string> ChatMessageEventParams
channel, from, text, color config class
Definition at line 394 of file gameplay.c.
ClientConnectedEventParams
typedef Param2<string, string> ClientConnectedEventParams
Name, uid.
Definition at line 399 of file gameplay.c.
ClientDisconnectedEventParams
typedef Param4<PlayerIdentity, Man, int, bool> ClientDisconnectedEventParams
PlayerIdentity, Man, LogoutTime, AuthFailed.
Definition at line 413 of file gameplay.c.
ClientNewEventParams
typedef Param3<PlayerIdentity, vector, Serializer> ClientNewEventParams
PlayerIdentity, PlayerPos, Top, Bottom, Shoe, Skin.
Definition at line 403 of file gameplay.c.
ClientNewReadyEventParams
typedef Param2<PlayerIdentity, Man> ClientNewReadyEventParams
PlayerIdentity, Man.
Definition at line 405 of file gameplay.c.
ClientPrepareEventParams
typedef Param5<PlayerIdentity, bool, vector, float, int> ClientPrepareEventParams
PlayerIdentity, useDB, pos, yaw, preloadTimeout (= additional time in seconds to how long server waits for loginData)
Definition at line 401 of file gameplay.c.
ClientReadyEventParams
typedef Param2<PlayerIdentity, Man> ClientReadyEventParams
PlayerIdentity, Man.
Definition at line 409 of file gameplay.c.
ClientReconnectEventParams
typedef Param2<PlayerIdentity, Man> ClientReconnectEventParams
PlayerIdentity, Man.
Definition at line 411 of file gameplay.c.
ClientRespawnEventParams
typedef Param2<PlayerIdentity, Man> ClientRespawnEventParams
PlayerIdentity, Man.
Definition at line 407 of file gameplay.c.
ConnectivityStatsUpdatedEventParams
typedef Param1<PlayerIdentity> ConnectivityStatsUpdatedEventParams
PlayerIdentity.
Definition at line 424 of file gameplay.c.
DLCOwnerShipFailedParams
typedef Param1<string> DLCOwnerShipFailedParams
world name
Definition at line 440 of file gameplay.c.
LoginStatusEventParams
typedef Param2<string, string> LoginStatusEventParams
text message for line 1, text message for line 2
Definition at line 428 of file gameplay.c.
LoginTimeEventParams
typedef Param1<int> LoginTimeEventParams
LoginTime.
Definition at line 416 of file gameplay.c.
LogoutCancelEventParams
typedef Param1<Man> LogoutCancelEventParams
Player.
Definition at line 422 of file gameplay.c.
LogoutEventParams
typedef Param1<int> LogoutEventParams
logoutTime
Definition at line 430 of file gameplay.c.
MPConnectionCloseEventParams
typedef Param2<int, string> MPConnectionCloseEventParams
EClientKicked, AdditionalInfo.
Definition at line 446 of file gameplay.c.
MPConnectionLostEventParams
typedef Param1<int> MPConnectionLostEventParams
Duration.
Definition at line 444 of file gameplay.c.
OLinkT
typedef Link<Object> OLinkT
Definition at line 1456 of file gameplay.c.
ParamsReadContext
typedef Serializer ParamsReadContext
Definition at line 15 of file gameplay.c.
ParamsWriteContext
typedef Serializer ParamsWriteContext
Definition at line 16 of file gameplay.c.
PlayerDeathEventParams
typedef Param2<DayZPlayer, Object> PlayerDeathEventParams
Player, "Killer" (Beware: Not necessarily actually the killer, Client doesn't have this info)
Definition at line 448 of file gameplay.c.
PreloadEventParams
typedef Param1<vector> PreloadEventParams
Position.
Definition at line 420 of file gameplay.c.
ProgressEventParams
typedef Param3<int, float, string> ProgressEventParams
state, progress, title
Definition at line 391 of file gameplay.c.
RespawnEventParams
typedef Param1<int> RespawnEventParams
RespawnTime.
Definition at line 418 of file gameplay.c.
ScriptLogEventParams
typedef Param1<string> ScriptLogEventParams
Definition at line 392 of file gameplay.c.
ServerFpsStatsUpdatedEventParams
typedef Param1<float> ServerFpsStatsUpdatedEventParams
float
Definition at line 426 of file gameplay.c.
SetFreeCameraEventParams
typedef Param1<FreeDebugCamera> SetFreeCameraEventParams
Camera.
Definition at line 442 of file gameplay.c.
SQFConsoleEventParams
typedef Param1<int> SQFConsoleEventParams
Definition at line 396 of file gameplay.c.
VONStartSpeakingEventParams
typedef Param2<string, string> VONStartSpeakingEventParams
player name, player id
Definition at line 436 of file gameplay.c.
VONStateEventParams
typedef Param2<bool, bool> VONStateEventParams
listening, toggled
Definition at line 434 of file gameplay.c.
VONStopSpeakingEventParams
typedef Param2<string, string> VONStopSpeakingEventParams
player name, player id
Definition at line 438 of file gameplay.c.
WindowsResizeEventParams
typedef Param3<int, int, bool> WindowsResizeEventParams
Width, Height, Windowed.
Definition at line 432 of file gameplay.c.
Enumeration Type Documentation
InventoryTraversalType
enum InventoryTraversalType
tree traversal type, for more see http://en.wikipedia.org/wiki/Tree_traversal
Enumerator
PREORDER
INORDER
POSTORDER
LEVELORDER
Definition at line 5 of file gameplay.c.
{
  PREORDER,
  INORDER,
  POSTORDER,
  LEVELORDER
};
OptionAccessType
enum OptionAccessType
C++ OptionAccessType.
Enumerator
AT_UNKNOWN
AT_OBJECTS_DETAIL
AT_TEXTURE_DETAIL
AT_HDR_DETAIL
AT_FSAA_DETAIL
AT_VSYNC_VALUE
AT_ANISO_DETAIL
AT_OPTIONS_FXAA_VALUE
AT_OPTIONS_SW_VALUE
AT_POSTPROCESS_EFFECTS
AT_QUALITY_PREFERENCE
AT_ATOC_DETAIL
AT_AMBIENT_OCCLUSION
AT_BLOOM
AT_ROTATION_BLUR
AT_SHADOW_DETAIL
AT_OPTIONS_TERRAIN
AT_OPTIONS_RESOLUTION
AT_OPTIONS_GAMMA_SLIDER
AT_OPTIONS_BRIGHT_SLIDER
AT_OPTIONS_VISIBILITY_SLIDER
AT_OPTIONS_OBJECT_VISIBILITY_SLIDER
AT_OPTIONS_SHADOW_VISIBILITY_SLIDER
AT_OPTIONS_DRAWDISTANCE_SLIDER
AT_ASPECT_RATIO
AT_OPTIONS_FIELD_OF_VIEW
AT_OPTIONS_MUSIC_SLIDER
AT_OPTIONS_EFFECTS_SLIDER
AT_OPTIONS_VON_SLIDER
AT_OPTIONS_MASTER_VOLUME
AT_OPTIONS_HWACC
AT_OPTIONS_EAX
AT_OPTIONS_LANGUAGE
AT_OPTIONS_RADIO
AT_CONFIG_MOUSE_FILTERING
AT_CONFIG_HEAD_BOB
AT_OPTIONS_DISPLAY_MODE
AT_OPTIONS_TERRAIN_SHADER
AT_OPTIONS_AIM_HELPER
AT_OPTIONS_MOUSE_AND_KEYBOARD
AT_OPTIONS_PAUSE
AT_OPTIONS_FLIPMODE
AT_OPTIONS_VON_THRESHOLD_SLIDER
AT_OPTIONS_MOUSE_YAXIS_INVERTED
AT_OPTIONS_MOUSE_XAXIS
AT_OPTIONS_MOUSE_YAXIS
AT_OPTIONS_MOUSE_XAXIS_AIM_MOD
AT_OPTIONS_MOUSE_YAXIS_AIM_MOD
AT_OPTIONS_CONTROLLER_LS_XAXIS
AT_OPTIONS_CONTROLLER_LS_YAXIS
AT_OPTIONS_CONTROLLER_LS_XAXIS_VEHICLE_MOD
AT_OPTIONS_CONTROLLER_RS_YAXIS_INVERTED
AT_OPTIONS_CONTROLLER_RS_XAXIS
AT_OPTIONS_CONTROLLER_RS_YAXIS
AT_OPTIONS_CONTROLLER_RS_XAXIS_AIM_MOD
AT_OPTIONS_CONTROLLER_RS_YAXIS_AIM_MOD
AT_OPTIONS_VON_INPUT_MODE
Definition at line 1181 of file gameplay.c.
{
  AT_UNKNOWN,
  AT_OBJECTS_DETAIL,
  AT_TEXTURE_DETAIL,
  AT_HDR_DETAIL,
  AT_FSAA_DETAIL,
  AT_VSYNC_VALUE,
  AT_ANISO_DETAIL,
  AT_OPTIONS_FXAA_VALUE,
  AT_OPTIONS_SW_VALUE,
  AT_POSTPROCESS_EFFECTS,
  AT_QUALITY_PREFERENCE,
  AT_ATOC_DETAIL,
  AT_AMBIENT_OCCLUSION,
  AT_BLOOM,
  AT_ROTATION_BLUR,
  AT_SHADOW_DETAIL,
  AT_OPTIONS_TERRAIN,
  AT_OPTIONS_RESOLUTION,
  AT_OPTIONS_GAMMA_SLIDER,
  AT_OPTIONS_BRIGHT_SLIDER,
  AT_OPTIONS_VISIBILITY_SLIDER,
  AT_OPTIONS_OBJECT_VISIBILITY_SLIDER,
  AT_OPTIONS_SHADOW_VISIBILITY_SLIDER,
  AT_OPTIONS_DRAWDISTANCE_SLIDER,
  AT_ASPECT_RATIO,
  AT_OPTIONS_FIELD_OF_VIEW,
  AT_OPTIONS_MUSIC_SLIDER,
  AT_OPTIONS_EFFECTS_SLIDER,
  AT_OPTIONS_VON_SLIDER,
  AT_OPTIONS_MASTER_VOLUME,
  AT_OPTIONS_HWACC,
  AT_OPTIONS_EAX,
  AT_OPTIONS_LANGUAGE,
  AT_OPTIONS_RADIO,
  AT_CONFIG_MOUSE_FILTERING,
  AT_CONFIG_HEAD_BOB,
  AT_OPTIONS_DISPLAY_MODE,
  AT_OPTIONS_TERRAIN_SHADER,
  AT_OPTIONS_AIM_HELPER,
  AT_OPTIONS_MOUSE_AND_KEYBOARD,
  AT_OPTIONS_PAUSE,
  AT_OPTIONS_FLIPMODE,
  AT_OPTIONS_VON_THRESHOLD_SLIDER,
  AT_OPTIONS_MOUSE_YAXIS_INVERTED,
  AT_OPTIONS_MOUSE_XAXIS,
  AT_OPTIONS_MOUSE_YAXIS,
  AT_OPTIONS_MOUSE_XAXIS_AIM_MOD,
  AT_OPTIONS_MOUSE_YAXIS_AIM_MOD,
  AT_OPTIONS_CONTROLLER_LS_XAXIS,
  AT_OPTIONS_CONTROLLER_LS_YAXIS,
  AT_OPTIONS_CONTROLLER_LS_XAXIS_VEHICLE_MOD,
  AT_OPTIONS_CONTROLLER_RS_YAXIS_INVERTED,
  AT_OPTIONS_CONTROLLER_RS_XAXIS,
  AT_OPTIONS_CONTROLLER_RS_YAXIS,
  AT_OPTIONS_CONTROLLER_RS_XAXIS_AIM_MOD,
  AT_OPTIONS_CONTROLLER_RS_YAXIS_AIM_MOD,
  AT_OPTIONS_VON_INPUT_MODE
};
OptionIDsScript
enum OptionIDsScript
Used for script-based game options. For anything C++ based, you would most likely use "Option Access Type" above.
Enumerator
OPTION_HUD
OPTION_CROSSHAIR
OPTION_GAME_MESSAGES
OPTION_ADMIN_MESSAGES
OPTION_PLAYER_MESSAGES
OPTION_QUICKBAR
OPTION_SERVER_INFO
OPTION_BLEEDINGINDICATION
OPTION_CONNECTIVITY_INFO
OPTION_HUD_BRIGHTNESS
Definition at line 1245 of file gameplay.c.
{
  OPTION_HUD = 100, //starts at 100 to avoid ID conflict with AT_
  OPTION_CROSSHAIR,
  OPTION_GAME_MESSAGES,
  OPTION_ADMIN_MESSAGES,
  OPTION_PLAYER_MESSAGES,
  OPTION_QUICKBAR,
  OPTION_SERVER_INFO,
  OPTION_BLEEDINGINDICATION,
  OPTION_CONNECTIVITY_INFO,
  OPTION_HUD_BRIGHTNESS
};
Function Documentation
GetAttachmentSlotsArray()
static array< int > GetAttachmentSlotsArray () static
Lists all customizable InventorySlots.
Definition at line 1168 of file gameplay.c.
  {
    return m_AttachmentSlots;
  }
References m_AttachmentSlots.
GetConfigArrayCountFromSlotID()
static int GetConfigArrayCountFromSlotID (int slot_ID) static
How many 'default equip' types are listed in the corresponding array.
Definition at line 1152 of file gameplay.c.
  {
    TStringArray types = new TStringArray;
    GetGame().ConfigGetTextArray(GetPathFromSlotID(slot_ID), types);
    return types.Count();
  }
References GetGame(), and GetPathFromSlotID().
GetConfigArrayNames()
static array< string > GetConfigArrayNames () static
for conversion of slot ID to config array's string
Definition at line 1174 of file gameplay.c.
  {
    return m_ConfigArrayNames;
  }
References m_ConfigArrayNames.
GetConfigAttachmentTypes()
static array< string > GetConfigAttachmentTypes (int slot_ID) static
Lists all configured types (if any) for the appropriate attachment.
Definition at line 1160 of file gameplay.c.
  {
    TStringArray types = new TStringArray;
    GetGame().ConfigGetTextArray(GetPathFromSlotID(slot_ID), types);
    return types;
  }
References GetGame(), and GetPathFromSlotID().
GetDefault()
proto native float GetDefault ()
GetGame()
proto native CGame GetGame ()
Referenced by MissionBase::AbortMission(), HandActionBase::Action(), ActionBuildPart::ActionCondition(), ActionCondition(), ActionBuryBody::ActionCondition(), ActionCreateGreenhouseGardenPlot::ActionCondition(), ActionDigGardenPlot::ActionCondition(), ActionDigInStash::ActionCondition(), ActionEmptyBottleBase::ActionCondition(), ActionMineBush::ActionCondition(), ActionMineBushByHand::ActionCondition(), ActionPackGift::ActionCondition(), ActionRepairCarChassis::ActionCondition(), ActionTransferLiquid::ActionCondition(), ActionUnrestrainTarget::ActionCondition(), ActionWorldCraft::ActionCondition(), ActionDeployHuntingTrap::ActionCondition(), ActionBuildShelter::ActionCondition(), ActionDetachFromTarget::ActionCondition(), ActionPullOutPlug::ActionCondition(), ActionTakeMaterialToHands::ActionCondition(), ActionInteractLoopBase::ActionCondition(), ActionAttachOnSelection::ActionCondition(), ActionWorldLiquidActionSwitch::ActionCondition(), FirearmActionMechanicManipulate::ActionCondition(), ActionBuildPart::ActionConditionContinue(), ActionRestrainTarget::ActionConditionContinue(), ActionDeployHuntingTrap::ActionConditionContinue(), ActionConditionContinue(), ActionContinuousBase::ActionContinuousBase(), Actions_DoCancel(), Actions_DoInternalCommand(), Actions_Start(), ActionManagerClient::ActionStart(), ActionTargetsCursor::ActionTargetsCursor(), SymptomBase::Activate(), Ammo_40mm_Smoke_ColorBase::Activate(), BillboardSetHandler::ActivateBillboardSet(), ShockDamageMdfr::ActivateCondition(), ActivateModifier(), Grenade_Base::ActivateRandomTime(), MissionBase::AddActiveInputRestriction(), ManBase::AddActiveNV(), AddAgent(), BleedingSourcesManagerBase::AddBleedingSource(), AddDefect(), ItemBase::AddDefect(), ScriptedWidgetEventHandler::AddElement(), AddInsider(), GameInventory::AddInventoryReservationEx(), ScriptedWidgetEventHandler::AddItem(), UIPopupScript::AddItemToClipboard(), ScriptConsoleTabBase::AddItemToClipboard(), LayoutHolder::AddItemToQuickbarRadial(), PluginBase::AddKeyframe(), AddModifier(), DayZPlayer::AddNoise(), NotificationUI::AddNotification(), ClientData::AddPlayerBase(), PPEffects::AddPPMask(), AddQuickbarItem(), SceneObject::AddRotation(), array::AddSubgroup(), ScriptedWidgetEventHandler::AddSubgroup(), ScriptedWidgetEventHandler::AddTab(), AddTemperatureToItem(), HudDebugWinBase::AddValue(), VicinityItemManager::AddVicinityItems(), NotificationUI::AddVoiceNotification(), EntityAI::AdvancedCommunication(), AfterStoreLoad(), FireplaceBase::AfterStoreLoad(), Hologram::AlignProjectionOnTerrain(), AnimFinished(), UIScriptedMenu::Apply(), ScriptedWidgetEventHandler::Apply(), AttachBleedingToZonesByHeight(), DayZCreature::AttenuateSoundIfNecessary(), DayZPlayer::AttenuateSoundIfNecessary(), SymptomManager::AutoactivateSymptoms(), Back(), UIScriptedMenu::Back(), ScriptedWidgetEventHandler::BannerHandlerBase(), ItemBase::BatteryCharger(), Barrel_ColorBase::BleachClothes(), BleedingSource(), Hit_MeatBones::BloodSplatGround(), BotSelectNearestTarget(), UIScriptedMenu::BottomChanged(), BuildCondition(), SoundObjectBuilder::BuildSoundObject(), CalcAndSetQuantity(), CAContinuousEmpty::CalcAndSetQuantity(), CAContinuousEmptyMagazine::CalcAndSetQuantity(), CAContinuousFill::CalcAndSetQuantity(), CAContinuousFillBrakes::CalcAndSetQuantity(), CAContinuousFillCoolant::CalcAndSetQuantity(), CAContinuousFillFuel::CalcAndSetQuantity(), CAContinuousFillOil::CalcAndSetQuantity(), CAContinuousFillPowerGenerator::CalcAndSetQuantity(), CAContinuousQuantity::CalcAndSetQuantity(), CAContinuousQuantityBloodTransfer::CalcAndSetQuantity(), CAContinuousQuantityEdible::CalcAndSetQuantity(), CAContinuousQuantityExtinguish::CalcAndSetQuantity(), CAContinuousQuantityLiquidTransfer::CalcAndSetQuantity(), CAContinuousQuantityRepeat::CalcAndSetQuantity(), CAContinuousTransferQuantity::CalcAndSetQuantity(), CASingleUseQuantity::CalcAndSetQuantity(), CASingleUseQuantityEdible::CalcAndSetQuantity(), CalcAndSetTotalEnergy(), HitDirectionEffectBase::CalculateArrowPosition(), CalculateEyeAccoTarget(), PluginBase::CalculatePos(), BroomBase::CalculateQuantity(), FlammableBase::CalculateQuantity(), CallQueueContext::CallParams(), CameraShake::CameraShake(), UIScriptedMenu::CameraToolsMenu(), CCTCursorNoObject::Can(), CCTSurface::Can(), CCTTree::Can(), InventoryGridController::CanAddItemInHandToInventory(), LayoutHolder::CanAddToQuickbarEx(), Inventory_Base::CanBeFilledAtPosition(), GardenBase::CanBePlaced(), UIScriptedMenu::Cancel(), HumanCommandActionCallback::CancelCondition(), Attachments::CanCombine(), AttachmentCategoriesRow::CanCombine(), Attachments::CanCombineAmmo(), Container::CanCombineAmmo(), VicinitySlotsContainer::CanCombineAmmo(), LayoutHolder::CanCombineEx(), BaseBuildingBase::CanDisplayAttachmentCategory(), BaseBuildingBase::CanDisplayAttachmentSlot(), LayoutHolder::CanDropEx(), WeaponManager::CanEjectBulletVerified(), Attachments::CanEquip(), LayoutHolder::CanEquipEx(), HandEventRemove::CanPerformEventEx(), FireplaceBase::CanPlaceFireplaceInSelectedSpot(), CanPlayEmoteClientCheck(), BaseBuildingBase::CanReceiveAttachment(), Container_Base::CanReceiveItemIntoCargo(), LayoutHolder::CanSwapOrTakeToHandsEx(), LayoutHolder::CanTakeToInventoryEx(), BroomBase::CanTransformIntoStick(), FlammableBase::CanTransformIntoStick(), CanUseToolToBuildPart(), CanUseToolToDismantlePart(), ComponentEnergyManager::CanWork(), PluginBase::CaptureFocus(), CaptureFocus(), CarPartsHealthCheck(), FlareSimulation::CastFlareAINoise(), UIScriptedMenu::ChangeAccount(), ChangeFakePlaytime(), ScriptConsoleSoundsTab::ChangeFilter(), ScriptConsoleItemsTab::ChangeFilter(), UIScriptedMenu::CharacterCreationMenu(), ChatLine::ChatLine(), CheckAllowUpdate(), CGame::CheckAmmoCompability(), CheckContactCache(), BaseBuildingBase::CheckFenceClosed(), BaseBuildingBase::CheckFenceOpened(), Entity::CheckForDestroy(), ManBase::CheckForGag(), ItemBase::CheckForHybridAttachments(), UIScriptedMenu::CheckForLightsAndNVG(), SlotsIcon::CheckHasItemSize(), RecipeBase::CheckIngredientMatch(), Icon::CheckIsWeapon(), PMTPlayback::CheckOnePlayingSA(), WeaponParticlesBase::CheckParticleOverride(), Hologram::CheckPowerSource(), ItemBase::CheckRainTick(), SymptomBase::CheckSoundFinished(), PMTPlayback::CheckStop(), ShockHandler::CheckValue(), ItemBase::CheckWater(), House::ChristmasTree(), SEffectManager::Cleanup(), CleanUpOnClosedClient(), InventoryItem::ClearInventory(), ManBase::ClearInventory(), PluginBase::ClearInventory(), GameInventory::ClearInventoryReservationEx(), HumanInventory::ClearUserReservedLocationAtIndexSynced(), HumanInventory::ClearUserReservedLocationSynced(), ScriptedWidgetEventHandler::Close(), BaseBuildingBase::CloseFence(), ManBase::CloseInventoryMenu(), ManBase::CloseMapEx(), UIScriptedMenu::CloseMapMenu(), UIScriptedMenu::CloseMenu(), UIScriptedWindow::CloseWindow(), UIManager::CloseWindow(), ScriptConsoleEnfScriptTab::ColorRunButton(), Barrel_ColorBase::ColourClothes(), Barrel_ColorBase::ColourLeatherClothes(), Attachments::Combine(), Container::Combine(), AttachmentCategoriesRow::Combine(), PlayerContainer::Combine(), VicinitySlotsContainer::Combine(), Icon::Combine(), InventoryItem::CombineItemsClient(), PluginDayzPlayerDebug_Ctrl::CommandHandler(), PluginDayzPlayerDebug_Weapons::CommandHandler(), DayZPlayer::CommandHandler(), ManBase::CommandHandler(), DayZPlayer::CommandHandlerDebug(), CommitSuicide(), ServerBrowserTab::Construct(), ConstructionActionData::ConstructionActionData(), ContactEvent(), FireplaceBase::ContactEvent(), PluginBase::ContainsFirstClass(), MissionBase::Continue(), ScriptedWidgetEventHandler::ContinuousActionProgress(), MissionBase::ControlPersonalLight(), InventoryItem::ConvertEnergyToQuantity(), Cooling(), UnboxLambda::CopyOldPropertiesToNew(), DropEquipAndDestroyRootLambda::CopyOldPropertiesToNew(), ItemBase::CreateAreaDamage(), AttachmentsOutOfReach::CreateAttachmentPosition(), CreateBleedingEffect(), CreateCarDestroyedEffect(), MissionBase::CreateCharacter(), PlayerSpawnHandler::CreateChildItem(), CreateCollisionTrigger(), ItemBase::CreateConstructionKit(), UIScriptedMenu::CreateContent(), ManBase::CreateCopyOfItemInInventory(), CreateDamageTriggerEx(), Managed::CreateDefaultCharacter(), ScriptedWidgetEventHandler::CreateFollowedObject(), UIScriptedMenu::CreateGestureContent(), UIScriptedMenu::CreateGroupContainer(), Particle::CreateInWorld(), CreateItemBasePiles(), Chemlight_ColorBase::CreateLight(), EntityLightSource::CreateLight(), MissionBase::CreateLogoutMenu(), CreateMagazinePiles(), CreateMagazinePilesFromBullet(), PPEClassBase::CreateMaterial(), PluginBase::CreateModuleWidgets(), CreateModuleWidgets(), ReplaceItemWithNewLambdaBase::CreateNetworkObjectInfo(), CreateNetworkObjectInfo(), Managed::CreateNewCharacter(), Managed::CreateNewCharacterByName(), ReplaceItemWithNewLambdaBase::CreateNewEntity(), ReplaceAndDestroyLambdaEx::CreateNewEntity(), CreateOrgan(), Particle::CreateParticleEffect(), ParticleSource::CreateParticleEx(), PlayerBase::CreatePersonalLight(), ItemBase::CreatePlant(), SyncPlayerList::CreatePlayerList(), CAContinuousMineWood::CreatePrimaryItems(), DayZIntroSceneXbox::CreateRandomCharacter(), PlayerStatBase::CreateRecord(), ScriptedWidgetEventHandler::CreateRootWidget(), ItemBase::CreateRope(), CAContinuousMineWood::CreateSecondaryItems(), CGame::CreateTitleScreen(), CreateTrigger(), EffectArea::CreateTrigger(), ScriptedWidgetEventHandler::CreateVideoLoadingEntry(), Weapon::CreateWeaponWithAmmo(), Icon::CreateWhiteBackground(), PluginBase::CreateWidgetOverlay(), EffectAreaLoader::CreateZones(), CreditsElement::CreditsDepartmentElement(), CreditsDepartmentSection(), CrossHairSelector(), CTObjectFollower::CTActor(), ScriptedWidgetEventHandler::CTEvent(), ScriptedWidgetEventHandler::CTKeyframe(), PluginBase::CursorHide(), PluginBase::CursorShow(), DamageHands(), DayZIntroScene::DayZIntroScene(), DayZIntroSceneXbox::DayZIntroSceneXbox(), DayZPlayer::DayZPlayerImplement(), DayZPlayerTypeRegisterItems(), DayZPlayerTypeRegisterSounds(), DayZPlayerTypeStepSoundLookupTable::DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTable::DayZPlayerTypeVoiceSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTableImpl(), SymptomBase::Deactivate(), DeactivateModifier(), ShockHandler::DealShock(), ManBase::DealShock(), PluginDayzPlayerDebug_OtherCmds::Death_Start(), Entity::DeathUpdate(), Component::DebugBBoxDelete(), Component::DebugBBoxDraw(), Component::DebugDirectionDelete(), Component::DebugDirectionDraw(), DebugGrowAgentsRequest(), DebugMonitor::DebugMonitor(), DebugRemoveAgentsRequest(), ComponentEnergyManager::DebugUpdate(), DecreaseCookedItemQuantity(), IEntity::DecreaseHealth(), IEntity::Delete(), PluginBase::DeleteKeyframe(), EntityLightSource::DeleteLightNow(), EntityLightSource::DeleteLightWithDelay(), Entity::DeleteOnClient(), Entity::DeleteSafe(), PluginBase::DeleteSceneObject(), ItemManager::DeserializeDefaultHeaderOpenStates(), ItemManager::DeserializeDefaultOpenStates(), Destroy(), ItemBase::DestroyAreaDamage(), ItemBase::DestroyClutterCutter(), FireplaceBase::DestroyClutterCutter(), DestroyCollisionTrigger(), ActionDestroyPart::DestroyCondition(), ItemBase::DestroyConstruction(), ItemBase::DestroyConstructionKit(), DestroyDamageTriggerEx(), ItemBase::DestroyFireplace(), ScriptedWidgetEventHandler::DestroyFollowedObject(), DestroyLock(), DestroyMaterialsServer(), Particle::DestroyParticleEffect(), ItemBase::DestroyPlant(), DestroySmokeGrenade(), Icon::DestroyWhiteBackground(), RainProcurementHandler::DetermineAmountCoef(), ComponentEnergyManager::DeviceUpdate(), DeveloperFreeCamera::DisableFreeCamera(), Disarm(), KitBase::DisassembleKit(), CGame::DisconnectSessionEx(), ActionDismantlePart::DismantleCondition(), WeaponDebug::DisplayGeneralInfo(), UIScriptedMenu::DisplayHint(), DisplayHint(), Hud::DisplayPresence(), Hud::DisplayStance(), PluginBase::DisplayTendency(), RecipeBase::Do(), InventoryItem::DoAmmoExplosion(), DoEverything(), PoweredOptic_Base::DoMeasurement(), Icon::DoubleClick(), HandsContainer::DoubleClick(), AttachmentCategoriesRow::DoubleClick(), ClosableContainer::DoubleClick(), PlayerContainer::DoubleClick(), VicinitySlotsContainer::DoubleClick(), ZombieContainer::DoubleClick(), Icon::DraggingOver(), ClosableContainer::DraggingOver(), DraggingOverCenterPanel(), Icon::DraggingOverCombine(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverGrid(), ClosableContainer::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), ZombieContainer::DraggingOverHeader(), Icon::DraggingOverSwap(), ScriptConsoleItemsTab::DrawItems(), WeaponDebug::DrawLineOfFireCameraHybrid(), WeaponDebug::DrawLineOfFireMuzzleToHit(), DropAllItemsInInventoryInBounds(), ScriptedWidgetEventHandler::DropdownPrefab(), ActionRepackTentCB::DropDuringRepacking(), DropNonUsableMaterialsServer(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), AttachmentCategoriesRow::DropReceived(), ClosableContainer::DropReceived(), Icon::DropReceivedFromMain(), UniversalTemperatureSourceLambdaBaseImpl::DryItemsInVicinity(), MissionBaseWorld::DumpCurrentUILayout(), ScriptConsoleConfigTab::DumpParam(), DynamicArea_Flare::DynamicArea_Flare(), PluginBase::EditorToggle(), PluginBase::EditorUpdate(), EffectArea::EEDelete(), House::EEDelete(), BuildingSuper::EEDelete(), StaticObj_Roadblock_Wood_Small::EEDelete(), CrashBase::EEDelete(), GardenBase::EEDelete(), ItemBase::EEDelete(), Roadflare::EEDelete(), FlammableBase::EEDelete(), EEDelete(), Weapon::EEFired(), ImprovisedExplosive::EEHealthLevelChanged(), Plastic_Explosive::EEHealthLevelChanged(), Weapon_Base::EEHealthLevelChanged(), InventoryItem::EEHealthLevelChanged(), ItemBase::EEHealthLevelChanged(), MaskBase::EEHealthLevelChanged(), GasMask_Filter::EEHealthLevelChanged(), Clothing_Base::EEHealthLevelChanged(), Container_Base::EEHealthLevelChanged(), TrapBase::EEHealthLevelChanged(), EEHealthLevelChanged(), ManBase::EEHealthLevelChanged(), ManBase::EEHitBy(), EEHitBy(), ContaminatedArea_Dynamic::EEInit(), ContaminatedArea_Local::EEInit(), SpookyArea::EEInit(), SpookyPlayerStalker::EEInit(), House::EEInit(), BuildingSuper::EEInit(), StaticObj_Roadblock_Wood_Small::EEInit(), Weapon::EEInit(), ItemBase::EEInit(), EEInit(), FlammableBase::EEInit(), CarScript::EEInit(), ItemBase::EEItemAttached(), FireplaceBase::EEItemAttached(), EEItemAttached(), ManBase::EEItemAttached(), ItemBase::EEItemDetached(), FireplaceBase::EEItemDetached(), FlammableBase::EEItemDetached(), EEItemDetached(), ManBase::EEItemDetached(), InventoryItem::EEItemLocationChanged(), HeadGear_Base::EEItemLocationChanged(), Mask_Base::EEItemLocationChanged(), ItemBase::EEItemLocationChanged(), ManBase::EEItemOutOfHands(), Entity::EEKilled(), InventoryItemSuper::EEKilled(), Plastic_Explosive::EEKilled(), Ammo_40mm_Explosive::EEKilled(), Ammo_40mm_Smoke_ColorBase::EEKilled(), ManBase::EEKilled(), Entity::EEOnAfterLoad(), ItemBase::EEOnAfterLoad(), ContaminatedArea_Dynamic::EEOnCECreate(), Effect(), ejectBulletAndStoreInMagazine(), WeaponManager::EjectBulletVerified(), HandsContainer::ElectricityIcon(), EmoteManager(), Inventory_Base::EmptySeedPack(), Container_Base::EmtpyInventory(), DeveloperFreeCamera::EnableFreeCamera(), End(), AnimatedActionBase::End(), EndLoading(), TriggerEvents::Enter(), OnlineServices::EnterGameplaySession(), ActionViewBinoculars::EnterOptics(), Entity::EntityAI(), DayZCreatureAI::EOnContact(), DayZInfected::EOnContact(), DayZPlayer::EOnContact(), Grenade_ChemGas::EOnContact(), EOnFrame(), DayZSpectator::EOnFrame(), EntityLightSource::EOnFrame(), DayZInfected::EOnInit(), ItemBase::EOnInit(), EntityLightSource::EOnInit(), ManBase::EOnPostFrame(), EOnPostSimulate(), CarScript::EOnPostSimulate(), Attachments::EquipItem(), Container::EquipItem(), HandsContainer::EquipItem(), PlayerContainer::EquipItem(), VicinitySlotsContainer::EquipItem(), ZombieContainer::EquipItem(), ItemManager::EvaluateContainerDragabilityDefault(), DayZPlayer::EvaluateDamageHit(), DayZInfected::EvaluateDamageHitAnimation(), DayZPlayer::EvaluateDamageHitAnimation(), DayZInfected::EvaluateDeathAnimation(), DayZPlayer::EvaluateDeathAnimation(), EffBulletImpactBase::EvaluateEffect(), EvaluateFinisherAttack(), ActionFishingNew::EvaluateFishingResult(), EvaluateHit_Common(), ComponentEnergyManager::Event_OnAwake(), Event_OnClick(), PluginBase::Event_OnClick(), PluginBase::Event_OnClickMiddle(), PluginBase::Event_OnDoubleClick(), PluginBase::Event_OnDrag(), AnalyticsManagerClient::Event_OnEntityKilled(), ComponentEnergyManager::Event_OnInit(), SyncEvents::Event_OnRPC(), EffBulletImpactBase::Event_OnStarted(), VicinityItemManager::ExcludeFromContainer_Phase1(), VicinityItemManager::ExcludeFromContainer_Phase2(), VicinityItemManager::ExcludeFromContainer_Phase3(), CAContinuousFertilizeGardenSlot::Execute(), CAContinuousFish::Execute(), CAContinuousMineWood::Execute(), CAContinuousTimeCooking::Execute(), CAContinuousWringClothes::Execute(), ReplaceItemWithNewLambdaBase::Execute(), PluginBase::ExecuteEnforceScript(), UIScriptedMenu::ExecuteSelectedItem(), UIScriptedMenu::Exit(), ActionViewBinoculars::ExitOptics(), IEntity::Explode(), Explode(), CGame::ExplosionEffects(), GameInventory::ExtendInventoryReservationEx(), ItemBase::Fertilize(), Inventory_Base::Fill(), Container_Base::FillInventory(), Entity::FindAttachmentBySlotName(), ManBase::FindCargoByBaseType(), ActionManagerClient::FindContextualUserActions(), CGame::FirearmEffects(), Icon::FlagAction(), FloatingCrossHair(), Inventory_Base::Fold(), ItemBase::Fold(), PluginBase::FreeCameraControlDisable(), PluginBase::FreeCameraControlEnable(), ItemBase::FullyBuild(), CGame::GamepadCheck(), GameplayEffectWidgets_base::GameplayEffectWidgets(), UIScriptedMenu::GameRespawn(), UIScriptedMenu::GameRetry(), ItemBase::GardenBase(), PluginBase::GatherPlayerInfo(), GatherSurfaces(), Environment::GatherTemperatureSources(), PluginBase::GatherTemperatureSources(), GenerateAINoiseAtPosition(), ScriptedWidgetEventHandler::GenerateQuickBarBackgroundTiles(), PluginRecipesManagerBase::GenerateRecipeCache(), GestureMenuItem(), UIScriptedMenu::GesturesMenu(), ManBase::GetAimPosition(), GetAlarmInMin(), AmmoEffects::GetAmmoEffectTypename(), AmmoEffects::GetAmmoParticleID(), Ammunition_Base::GetAmmoWeightByBulletType(), AttachmentCategoriesContainer::GetAttachmentCategoriesCount(), AttachmentCategoriesContainer::GetAttachmentCategory(), AttachmentCategoriesSlotsContainer::GetAttachmentCategory(), ConstructionActionData::GetAttachmentsFromSelection(), ConstructionActionData::GetAttachmentSlotFromSelection(), ItemBase::GetAttachmentSlots(), PluginBase::GetBaseClasses(), PluginBase::GetBaseClassPath(), PluginBase::GetBaseClassPathRecursive(), GetBoundButtonText(), Managed::GetCharacterName(), Managed::GetCharacterNameById(), ItemManager::GetChosenCombinationFlag(), OnlineServices::GetClientServices(), GetCollisionBoxData(), HandsContainer::GetCombinationFlags(), ItemManager::GetCombinationFlags(), GetComponentNamesFromDamageZone(), PluginBase::GetConfig(), GetConfigArrayCountFromSlotID(), SceneObject::GetConfigAttachments(), GetConfigAttachmentTypes(), PluginBase::GetConfigRecursive(), UIScriptedMenu::GetControlMappingInfo(), HitDirectionImagesBase::GetCurrentImageData(), SymptomManager::GetCurrentPrimaryActiveSymptom(), ComponentEnergyManager::GetCurrentUpdateTime(), GetDamageZoneMap(), UndergroundAreaLoader::GetData(), AlarmClock_ColorBase::GetDebugText(), KitchenTimer::GetDebugText(), ItemManager::GetDefaultOpenStateHands(), Hologram::GetDefaultOrientation(), IEntity::GetDisplayName(), InventoryItem::GetDryingIncrement(), GetEmptyingEndSoundset(), GetEmptyingLoopSoundset(), ComponentEnergyManager::GetEnergyMax(), ItemBase::GetEnergyNeededToCharge(), Debug::GetFiltredConfigClasses(), Edible_Base::GetFoodAgents(), Edible_Base::GetFoodDigestibility(), Edible_Base::GetFoodEnergy(), Edible_Base::GetFoodNutritionalIndex(), Edible_Base::GetFoodTotalVolume(), Edible_Base::GetFoodToxicity(), Edible_Base::GetFoodWater(), GetHealthLevelForAmmo(), HiddenSelectionsData::GetHiddenSelectionsConfig(), HiddenSelectionsData::GetHiddenSelectionsMaterialsConfig(), HiddenSelectionsData::GetHiddenSelectionsTexturesConfig(), ActionTargetsCursor::GetHud(), ScriptedWidgetEventHandler::GetHud(), AttachmentCategoriesContainer::GetIconName(), AttachmentCategoriesSlotsContainer::GetIconName(), InputUtils::GetImagesetAndIconFromInputAction(), EntityAI::GetImpactSurfaceTypeEx(), GetInstance(), ColorManager::GetItemColor(), GetItemDisplayName(), UIScriptedMenu::GetItems(), Attachments::GetItemSlots(), Liquid::GetLiquidConfigProperty(), GetMaterialType(), GetMeleeTargetEx(), CGame::GetMenuDefaultCharacterData(), MenuData::GetMenuDefaultCharacterDataInstance(), IEntity::GetModelName(), CGame::GetModelName(), UIScriptedMenu::GetMouseLookDir(), PluginBase::GetMousePositionInScene(), ScriptedWidgetEventHandler::GetOnScreenPosition(), Surface::GetParamFloat(), PluginBase::GetPlantType(), ActionTargetsCursor::GetPlayer(), ScriptedWidgetEventHandler::GetPlayer(), GetPlayer(), ManBase::GetPlayerClass(), GetProfileValueBool(), Hologram::GetProjectionEntityPosition(), InventoryItem::GetProtectionLevel(), InventoryGridController::GetQuickbarItemColor(), Attachments::GetRecipeCount(), HandsContainer::GetRecipeCount(), PlayerContainer::GetRecipeCount(), ItemManager::GetRecipeCount(), GetRequiredParts(), DayZIntroScene::GetSelectedUserName(), IEntity::GetSelectionPositionLS(), IEntity::GetSelectionPositionMS(), IEntity::GetSelectionPositionOld(), IEntity::GetSelectionPositionWS(), InventoryItem::GetSoakingIncrement(), RecipeBase::GetSoundCategory(), GetStanceMask(), IEntity::GetSurfaceNoise(), CGame::GetSurfaceOrientation(), IEntity::GetSurfaceType(), ActionDismantlePart::GetText(), ActionRepairPart::GetText(), ActionTransferLiquid::GetText(), ActionWorldCraft::GetText(), ActionBuildShelter::GetText(), ItemBase::GetTimeNeededToCharge(), IEntity::GetType(), GetTypeMaxGlobalHealth(), AttachmentCategoriesContainer::GetViewIndex(), WeaponDebug::GetWeaponInHands(), ItemBase::GrowthTimerTick(), HandGuardBase::GuardCondition(), GUIAction_ActivateCommand(), GUIAction_EnableAI(), GUIAction_InitDebugObject(), GUIAction_ReleaseDebugObject(), GUIAction_SetValue(), HandEvent(), DayZPlayer::HandleDeath(), HandleEngineSound(), HandleError(), HandleFallDamage(), HandleFishingResultFailure(), HandleFishingResultSuccess(), HandleForceSwapEntities(), HandleInput(), UIScriptedMenu::HandleLights(), MissionBase::HandleMapToggleByKeyboardShortcut(), UIScriptedMenu::HandleNVG(), BaseBuildingBase::HandleRefreshers(), PluginBase::HandleSetTime(), HandleSoundEffectsPipeCreaking(), HandleSwapEntities(), HandleTakeToDst(), DayZPlayer::HandleView(), DayZPlayer::HandleWeapons(), HandsContainer::HandsContainer(), HandsPreview::HandsPreview(), ItemBase::Harvest(), IEntity::HasAnimation(), HasConflictPart(), InventoryItem::HasFoodStage(), HasMaterials(), HasRequiredPart(), Clothing::Headtorch_ColorBase(), Heating(), HiddenSelectionsData::HiddenSelectionsData(), ItemBase::HideAllAnimationsAndProxyPhysics(), Entity::HideAllSelections(), MissionBase::HideInventory(), Weapon::HideWeaponBarrel(), Hologram::HideWhenClose(), PluginDayzPlayerDebug_OtherCmds::Hit_Start(), HitZoneSelection(), HitZoneSelectionRaycast(), Hologram::Hologram(), UIScriptedMenu::HudShow(), FireplaceBase::IgniteEntityAsFireplace(), Entity::IgnoreOutOfReachCondition(), UIScriptedMenu::InGameMenuXbox(), InheritsFrom(), Init(), LoginScreenBase::Init(), MenuDefaultCharacterData::Init(), PPEffects::Init(), BleedingSourcesManagerBase::Init(), BleedingCheckMdfr::Init(), DayZInfected::Init(), AlarmClock_ColorBase::Init(), KitchenTimer::Init(), FlammableBase::Init(), ManBase::Init(), PluginBase::Init(), PluginManager::Init(), SoundSetMap::Init(), UIScriptedMenu::Init(), WarningMenuBase::Init(), ScriptedWidgetEventHandler::Init(), ScriptConsoleConfigTab::Init(), ScriptConsoleGeneralTab::Init(), ScriptConsoleItemsTab::Init(), CABase::Init(), Init(), HumanCommandActionCallback::Init(), ItemBase::Init(), AttachmentCategoriesRow::Init(), SceneObject::Init(), Hud::Init(), ScriptedWidgetEventHandler::Init(), ItemOptics::Init2DPreloadType(), Liquid::InitAllLiquids(), Attachments::InitAttachmentGrid(), ItemOptics::InitCameraOverrideProperties(), Debug::InitCanvas(), Entity::InitDamageZoneDisplayNameMapping(), InitData(), ItemOptics::InitDOFAvailability(), Weapon::InitDOFProperties(), ManBase::InitEditor(), AttachmentCategoriesContainer::InitGhostSlots(), ZombieContainer::InitGhostSlots(), MissionBaseWorld::InitialiseWorldData(), InitializeWidgets(), Container::InitIconEx(), PluginBase::InitLoad(), InventoryItemSuper::InitMapState(), ItemOptics::InitOpticsDOFProperties(), ItemOptics::InitOpticsPP(), ItemOptics::InitReddotData(), Weapon::InitReliability(), ITEM_PlayerData::InitServer(), ScriptConsoleWeatherTab::InitValues(), InitWidgets(), PluginBase::InitWidgets(), EffectArea::InitZone(), MissionBase::InsertCorpse(), BaseBuildingBase::InsertRefresherPosition(), HandsContainer::InspectItem(), PlayerContainer::InspectItem(), ScriptedWidgetEventHandler::InspectItem(), Interact(), Land_Underground_Panel_Lever::Interact(), ActionBaseCB::Interrupt(), CAContinuousFill::Interrupt(), CAContinuousQuantityExtinguish::Interrupt(), Inventory(), UIScriptedMenu::InviteMenu(), EntityAI::IsAreaAtDoorFree(), AttachmentsOutOfReach::IsAttachmentReachable(), Hologram::IsBaseViable(), Hologram::IsClippingRoof(), IsColliding(), Hologram::IsCollidingBBox(), IsCollidingEx(), DayZPlayerImplement::IsControlledPlayer(), PluginBase::IsCurrentUIPageValid(), IsDummyFinished(), HandsContainer::IsEmpty(), IsEntityOnInteriorSurface(), BaseBuildingBase::IsFacingCamera(), Input::IsInactiveGamepadOrUserSelected(), PluginBase::IsInConsole(), PluginBase::IsIngame(), IsInventoryVisible(), HandsContainer::IsItemActive(), HandsContainer::IsItemWithQuantityActive(), IEntity::IsKindOf(), ScriptedWidgetEventHandler::IsLocalPlayer(), UIScriptedMenu::IsLocalPlayer(), IsObjectObstructed(), IsObjectObstructedFilterEx(), IsOutOfMap(), MissionBase::IsPaused(), ItemBase::IsPlaceable(), IsPlaceableAtPosition(), ItemBase::IsPlaceableAtPosition(), ActionDigWorms::IsPlayerOnGround(), IsRainingAboveEntity(), InventoryItem::IsServerCheck(), IsServerOrLocalPlayer(), IsSpaceFor(), Hologram::IsSurfaceSea(), Hologram::IsSurfaceWater(), ItemBase::IsSurfaceWater(), ActionDigWorms::IsTargetFertile(), ManBase::IsTargetInActiveRefresherRange(), FireplaceBase::IsThisIgnitionSuccessful(), VONManager::IsVoiceThresholdMinimum(), IsVonToggled(), IsWindy(), ITEM_DataBase(), ScriptedWidgetEventHandler::ItemActionsWidget(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), InventoryItem::ItemBase(), ItemManager::ItemManager(), ScriptedWidgetEventHandler::KeybindingElement(), ScriptedWidgetEventHandler::KeybindingElementNew(), array::KeybindingsContainer(), ScriptedWidgetEventHandler::KeybindingsGroup(), KillPlayer(), InventoryItem::KindOf(), Land_Underground_EntranceBase::Land_Underground_EntranceBase(), LateInit(), ScriptConsoleGeneralTab::LateInit(), ScriptedWidgetEventHandler::LayoutHolder(), UIScriptedMenu::Leave(), TriggerEvents::Leave(), ServerBrowserTab::LeftHold(), Weapon::LiftWeaponCheck(), ArrowManagerPlayer::Load(), AmmoCamParams::Load(), DayZCreatureAIType::LoadAnimDamageEvents(), DayZCreatureAIType::LoadAnimSoundEvents(), DayZCreatureAIType::LoadAnimSoundVoiceEvents(), DayZCreatureAIType::LoadAnimStepEvents(), BillboardSetHandler::LoadBillboardConfigs(), Managed::LoadCharacterData(), LoadConfig(), CfgGameplayHandler::LoadData(), ModStructure::LoadData(), LoadDataAsync(), UIScriptedMenu::LoadFavoriteServers(), ScriptedWidgetEventHandler::LoadFilters(), PluginBase::LoadFromCfg(), LoadFromCfg(), LoadingScreen(), ModLoader::LoadMods(), UIScriptedMenu::LoadMods(), InventoryItem::LoadParticleConfigOnFire(), InventoryItem::LoadParticleConfigOnOverheating(), LoadPlayerAttachmentIndexes(), PluginConfigHandler::LoadScenePlayer(), PluginConfigHandler::LoadSceneSettings(), InventoryItemType::LoadSoundEvents(), LoadSoundWeaponEvent(), SoundLookupTable::LoadTable(), LoadVegetationSounds(), ScriptedWidgetEventHandler::LoadVideo(), GameInventory::LocalDestroyEntity(), UIMenuPanel::LockControls(), DayZPlayer::LockControls(), LockModifier(), LockOvenAttachments(), Debug::LogMessage(), PluginBase::LogPrint(), LogSuicide(), magazinesHaveEqualSizes(), MainMenuButtonEffect::MainMenuButtonEffect(), ScriptedWidgetEventHandler::MainMenuDlcHandlerBase(), SymptomBase::MakeParamObjectPersistent(), MaterialIsRuined(), Entity::MaxLifetimeRefreshCalc(), ManBase::Message(), MissionBaseWorld::MissionBase(), Dispatcher::MissionGameplayHideInventory(), MissionBase::MissionServer(), DayZCreature::ModCommandHandlerBefore(), IEntity::ModelToWorld(), ScriptedWidgetEventHandler::ModsMenuDetailed(), ScriptedWidgetEventHandler::ModsMenuDetailedEntry(), ScriptedWidgetEventHandler::ModsMenuSimple(), ScriptedWidgetEventHandler::ModsMenuSimpleEntry(), ScriptedWidgetEventHandler::ModsMenuTooltip(), Icon::MouseClick(), AttachmentCategoriesRow::MouseClick(), PlayerContainer::MouseClick(), ZombieContainer::MouseClick(), HandsContainer::MouseClick2(), ClosableContainer::MouseClick2(), ClosableHeader::MouseEnter(), MoveAttachmentDown(), MoveAttachmentUp(), ActionDeployBase::MoveEntityToFinalPosition(), MoveFocusByArea(), ItemBase::MutePlayer(), ManBase::NeedInventoryJunctureFromServer(), ActionMenu::NextAction(), ActionMenu::NextActionCategory(), UIScriptedMenu::NoteMenu(), NotificationUI::NotificationUI(), ActionUnrestrainTargetCB::ObtainUnrestrainTime(), HandStateBase::OnAbort(), WeaponChambering_Base::OnAbort(), EntityAI::OnAction(), Magnum_Base::OnAction(), InventoryItem::OnAction(), Edible_Base::OnAction(), OnAction(), AlarmClock_ColorBase::OnAction(), BroomBase::OnAction(), KitchenTimer::OnAction(), ActionManagerServer::OnActionEnd(), OnActivate(), OnActivate(), WeaponParticlesBase::OnActivate(), DrowningMdfr::OnActivate(), ClaymoreMine::OnActivatedByItem(), ImprovisedExplosive::OnActivatedByItem(), Plastic_Explosive::OnActivatedByItem(), RemoteDetonatorTrigger::OnActivatedByItem(), Ammo_40mm_Explosive::OnActivatedByItem(), Grenade_Base::OnActivateFinished(), Grenade_Base::OnActivateImmediate(), FlareSimulation::OnActivation(), OnAnimationEvent(), AnimatedActionBase::OnAnimationEvent(), EmoteCB::OnAnimationEvent(), ClaymoreMine::OnArmed(), OnlineServices::OnAutoConnectToEmptyServer(), ScriptedWidgetEventHandler::OnBleedingIndicationChanged(), ManBase::OnBleedingSourceAdded(), ManBase::OnBleedingSourceRemoved(), OnCenterPanelDropReceived(), Entity::OnCEUpdate(), UIScriptedMenu::OnChange(), UIPopupScript::OnChange(), ScriptConsoleGeneralTab::OnChange(), HudDebugWinBase::OnChange(), UIScriptedMenu::OnChanged(), WidgetEventHandler::OnChildAdd(), WidgetEventHandler::OnChildRemove(), PluginDayzPlayerDebug_Weapons::OnClick(), UIScriptedMenu::OnClick(), ScriptedWidgetEventHandler::OnClick(), UIPopupScript::OnClick(), UIPropertyAttachment::OnClick(), ScriptConsoleGeneralTab::OnClick(), ScriptConsoleItemsTab::OnClick(), ScriptConsoleWeatherTab::OnClick(), OnClick(), WidgetEventHandler::OnClick(), UIScriptedMenu::OnClick_Continue(), UIScriptedMenu::OnClick_Exit(), UIScriptedMenu::OnClick_Respawn(), UIScriptedMenu::OnClick_Restart(), MissionBase::OnClientDisconnectedEvent(), MissionBase::OnClientNewEvent(), MissionBase::OnClientReadyEvent(), MissionBase::OnClientRespawnEvent(), UIPopupScript::OnClose(), ManBase::OnCommandLadderFinish(), ManBase::OnCommandLadderStart(), ManBase::OnCommandMoveStart(), ManBase::OnCommandSwimFinish(), ManBase::OnCommandSwimStart(), ManBase::OnCommandVehicleFinish(), ManBase::OnCommandVehicleStart(), ManBase::OnConnect(), CGame::OnConnectivityStatChange(), OnContact(), ZombieMaleBase::OnDamageDestroyed(), Grenade_ChemGas::OnDamageDestroyed(), OnDamageDestroyed(), UnconsciousnessMdfr::OnDeactivate(), Entity::OnDebugSpawn(), FishingRod_Base_New::OnDebugSpawn(), PluginBase::OnDestroy(), ManBase::OnDisconnect(), Land_Underground_Stairs_Exit::OnDoorStateChangedServer(), ScriptedWidgetEventHandler::OnDoubleClick(), UIScriptedMenu::OnDoubleClick(), ScriptConsoleGeneralTab::OnDoubleClick(), ScriptConsoleItemsTab::OnDoubleClick(), OnDoubleClick(), WidgetEventHandler::OnDoubleClick(), WidgetEventHandler::OnDrag(), WidgetEventHandler::OnDraggingOver(), Icon::OnDraggingOverBackground(), ClosableHeader::OnDragHeader(), WidgetEventHandler::OnDrop(), WidgetEventHandler::OnDropReceived(), PlayerContainer::OnDropReceivedFromGhostArea(), ZombieContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesContainer::OnDropReceivedFromHeader(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), ClosableContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromHeader(), VicinitySlotsContainer::OnDropReceivedFromHeader(), ZombieContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), ManBase::OnDrowningEnd(), OnEnd(), ActionDrainLiquid::OnEnd(), ActionLockAttachment::OnEnd(), ActionPourLiquid::OnEnd(), ActionContinuousBase::OnEndAnimationLoop(), OnEndAnimationLoop(), ActionDrainLiquid::OnEndAnimationLoop(), ActionLockAttachment::OnEndAnimationLoop(), ActionPourLiquid::OnEndAnimationLoop(), ActionTransferLiquid::OnEndAnimationLoop(), ActionRepackTent::OnEndAnimationLoop(), ActionViewOptics::OnEndClient(), ActionViewOptics::OnEndServer(), OnEndServer(), ActionCloseDoors::OnEndServer(), ActionCloseFence::OnEndServer(), ActionOpenDoors::OnEndServer(), ActionOpenFence::OnEndServer(), ActionRepackTent::OnEndServer(), FirearmActionDetachMagazine::OnEndServer(), Battery9V::OnEnergyAdded(), Battery9V::OnEnergyConsumed(), Chemlight_ColorBase::OnEnergyConsumed(), OnEngineStart(), CarScript::OnEngineStart(), CarScript::OnEngineStop(), AreaDamageTriggerBase::OnEnter(), BarbedWireTrigger::OnEnter(), AreaDamageBase::OnEnter(), Hit_MeatBones::OnEnterCalculations(), OnEntry(), BotTestSpamUserActions::OnEntry(), HandStateBase::OnEntry(), WeaponStateBase::OnEntry(), OnEvent(), MissionBase::OnEvent(), ActionRemoveSeed::OnExecute(), ActionTakeArrowToHands::OnExecute(), ActionTakeItemToHands::OnExecute(), ActionHandcuffTarget::OnExecuteClient(), ActionDigInStash::OnExecuteServer(), OnExecuteServer(), ActionEmptyMagazine::OnExecuteServer(), ActionCheckPulse::OnExecuteServer(), ActionDetachFromTarget::OnExecuteServer(), ActionPickupChicken::OnExecuteServer(), ActionRepositionPluggedItem::OnExecuteServer(), ActionTakeArrow::OnExecuteServer(), ActionTakeHybridAttachment::OnExecuteServer(), ActionTakeHybridAttachmentToHands::OnExecuteServer(), ActionTakeItem::OnExecuteServer(), ActionTakeMaterialToHands::OnExecuteServer(), ActionAttachOnSelection::OnExecuteServer(), ActionAttachPowerSourceToPanel::OnExecuteServer(), ActionAttachToConstruction::OnExecuteServer(), ActionAttachWithSwitch::OnExecuteServer(), ActionCreateIndoorFireplace::OnExecuteServer(), ActionCreateIndoorOven::OnExecuteServer(), ActionFoldEntityToSlot::OnExecuteServer(), ActionOpen::OnExecuteServer(), ActionUnfoldEntity::OnExecuteServer(), HandStateBase::OnExit(), OnExplode(), Grenade_ChemGas::OnExplode(), FireworksLauncherClientEvent::OnExplode(), FuelStation::OnExplosionEffects(), Grenade_Base::OnExplosionEffects(), ActionUnfoldMapCB::OnFinish(), ActionBaseCB::OnFinish(), ActionContinuousBase::OnFinishProgress(), ActionRestrainTarget::OnFinishProgressClient(), ActionShave::OnFinishProgressClient(), OnFinishProgressClient(), OnFinishProgressServer(), ActionCreateGreenhouseGardenPlot::OnFinishProgressServer(), ActionDestroyCombinationLock::OnFinishProgressServer(), ActionDigGardenPlot::OnFinishProgressServer(), ActionDigInStash::OnFinishProgressServer(), ActionDigWorms::OnFinishProgressServer(), ActionDismantleGardenPlot::OnFinishProgressServer(), ActionPackGift::OnFinishProgressServer(), ActionRepairCarChassis::OnFinishProgressServer(), ActionRepairTent::OnFinishProgressServer(), ActionRepairTentPart::OnFinishProgressServer(), ActionSawPlanks::OnFinishProgressServer(), ActionStripCarrierVest::OnFinishProgressServer(), ActionUnpackBox::OnFinishProgressServer(), ActionUnpackGift::OnFinishProgressServer(), ActionUnrestrainTarget::OnFinishProgressServer(), ActionDeployBase::OnFinishProgressServer(), ActionCheckPulseTarget::OnFinishProgressServer(), ActionRepackTent::OnFinishProgressServer(), Weapon::OnFireModeChange(), ScriptedWidgetEventHandler::OnFocus(), WidgetEventHandler::OnFocus(), WidgetEventHandler::OnFocusLost(), PluginBase::OnFrame(), PointLightBase::OnFrameLightSource(), FireworksLauncher::OnFuseIgnitedServer(), BiosUserManager::OnGameNameChanged(), Input::OnGamepadConnected(), Input::OnGamepadDisconnected(), Input::OnGamepadIdentification(), ObjectSpawnerHandler::OnGameplayDataHandlerLoad(), MissionBase::OnGameplayDataHandlerLoad(), ManBase::OnGameplayDataHandlerSync(), BiosSessionService::OnGetGameplaySession(), BiosSessionService::OnGetSessionError(), OnGUI(), OnGUITimer(), PluginBase::OnGUITimer(), HandsArea::OnHandsPanelDropReceived(), DestructionEffectBase::OnHealthLevelChanged(), UIScriptedMenu::OnHide(), OnHide(), SlotsIcon::OnIconDrag(), ItemBase::OnIgnitedTarget(), ItemBase::OnIgnitedTargetFailed(), FireplaceBase::OnIgnitedThis(), SymptomBase::OnInit(), PluginBase::OnInit(), MissionBase::OnInit(), OnInit(), ItemBase::OnInitEnergy(), OnInputDeviceChanged(), UIScriptedMenu::OnInputDeviceChanged(), ServerBrowserTab::OnInputDeviceChanged(), ScriptedWidgetEventHandler::OnInputDeviceChanged(), WeaponManager::OnInputUserDataProcess(), ManBase::OnInputUserDataProcess(), OnInventoryEnter(), OnInventoryJunctureFailureFromServer(), ItemBase::OnIsCharged(), AnalyticsManagerClient::OnItemAttachedAtPlayer(), InventoryGridController::OnItemDrag(), InventoryGridController::OnItemDrop(), InventoryGridController::OnItemDropReceived(), OnItemLocationChanged(), ItemBase::OnItemLocationChanged(), BiosUserManager::OnJoin(), ManBase::OnJumpOutVehicleFinish(), Input::OnKeyboardConnected(), Input::OnKeyboardDisconnected(), PluginBase::OnKeyPress(), MissionBaseWorld::OnKeyRelease(), Input::OnLastInputDeviceChanged(), AreaDamageTriggerBase::OnLeave(), AreaDamageBase::OnLeave(), Backlit::OnLeaveCar(), CfgGameplayHandler::OnLoaded(), OnlineServices::OnLoadVoicePrivilege(), MissionBaseWorld::OnLog(), BiosUserManager::OnLoggedOn(), MissionBase::OnMenuEnter(), MissionBase::OnMissionFinish(), UIScriptedMenu::OnModalResult(), PluginBase::OnMouse(), ScrollBarContainer::OnMouseButtonDown(), ScriptedWidgetEventHandler::OnMouseButtonDown(), UIScriptedMenu::OnMouseButtonDown(), ScriptConsoleGeneralTab::OnMouseButtonDown(), ScriptConsoleSoundsTab::OnMouseButtonDown(), WidgetEventHandler::OnMouseButtonDown(), MissionBaseWorld::OnMouseButtonPress(), PluginBase::OnMouseButtonRelease(), MissionBaseWorld::OnMouseButtonRelease(), OnMouseButtonUp(), ScriptedWidgetEventHandler::OnMouseButtonUp(), WidgetEventHandler::OnMouseButtonUp(), Input::OnMouseConnected(), Input::OnMouseDisconnected(), ScriptedWidgetEventHandler::OnMouseEnter(), OptionSelectorBase::OnMouseEnter(), WidgetEventHandler::OnMouseEnter(), ScriptedWidgetEventHandler::OnMouseLeave(), OptionSelectorBase::OnMouseLeave(), WidgetEventHandler::OnMouseLeave(), WidgetEventHandler::OnMouseWheel(), UIPopupScript::OnOpen(), ItemOptics::OnOpticEnter(), ItemOptics::OnOpticExit(), Land_Underground_Panel_Lever::OnPanelUsedSynchronized(), ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), ManBase::OnParticleEvent(), ScriptedWidgetEventHandler::OnPartyChatChangedEvent(), BiosUserManager::OnPartyHost(), Icon::OnPerformCombination(), HandsContainer::OnPerformCombination(), Icon::OnPerformRecipe(), Grenade_Base::OnPin(), OnPlacementComplete(), ClaymoreMine::OnPlacementComplete(), ImprovisedExplosive::OnPlacementComplete(), GardenBase::OnPlacementComplete(), InventoryItem::OnPlacementComplete(), ItemBase::OnPlacementComplete(), KitBase::OnPlacementComplete(), FireworksLauncher::OnPlacementComplete(), Inventory_Base::OnPlacementComplete(), TentBase::OnPlacementComplete(), TrapBase::OnPlacementComplete(), ItemBase::OnPlacementStarted(), ScriptedWidgetEventHandler::OnPlaybackStart(), ScriptedWidgetEventHandler::OnPlaybackStop(), ManBase::OnPlayerLoaded(), MissionBase::OnPlayerRespawned(), WeaponDebug::OnPostFrameUpdate(), CGame::OnProjectileStopped(), CGame::OnProjectileStoppedInObject(), CGame::OnProjectileStoppedInTerrain(), ManBase::OnRestrainStart(), InventoryItem::OnRightClick(), OnRightPanelDropReceived(), OnRPC(), PluginBase::OnRPC(), Entity::OnRPC(), WrittenNoteData::OnRPC(), OnRPC(), ManBase::OnRPC(), CGame::OnRPC(), PluginBase::OnRPCSyncSceneObject(), PluginBase::OnRPCTemp(), OnScheduledTick(), DebugMonitorValues::OnScheduledTick(), Managed::OnScheduledTick(), OnSelectAction(), ScriptConsoleVicinityTab::OnSelectAction(), ScriptedWidgetEventHandler::OnSelectAction(), ScriptedWidgetEventHandler::OnSelectActionEx(), ScriptedWidgetEventHandler::OnSelectConsolePreset(), ScriptedWidgetEventHandler::OnSelectKBPreset(), UIScriptedMenu::OnSelectKBPreset(), ManBase::OnSelectPlayer(), GameInventory::OnServerInventoryCommandStatic(), DeveloperFreeCamera::OnSetFreeCameraEvent(), UIScriptedMenu::OnShow(), OnShow(), BiosUserManager::OnSignedOut(), DayZPlayerCommandDeathCallback::OnSimulationEnd(), ManBase::OnSpawnedFromConsole(), FirearmActionDetachMagazine::OnStageStart(), PPERequester_GameplayBase::OnStart(), ActionContinuousBase::OnStartAnimationLoop(), OnStartAnimationLoop(), ActionDrainLiquid::OnStartAnimationLoop(), ActionLockAttachment::OnStartAnimationLoop(), ActionPourLiquid::OnStartAnimationLoop(), ActionTransferLiquid::OnStartAnimationLoop(), ActionRepackTent::OnStartAnimationLoopServer(), ActionViewOptics::OnStartClient(), OnStartClient(), ActionTransferLiquid::OnStartServer(), ActionViewOptics::OnStartServer(), OnStartServer(), ActionHandsPartSwitch::OnStartServer(), ActionBuildPartSwitch::OnStartServer(), FirearmActionDetachMagazine::OnStartServer(), ActionReadPaperCB::OnStateChange(), ActionWritePaperCB::OnStateChange(), DayZPlayer::OnStepEvent(), TrapBase::OnSteppedOn(), OnSteppedOn(), PPERequester_GameplayBase::OnStop(), GardenBase::OnStoreLoad(), ItemBase::OnStoreLoad(), ItemBase::OnStoreLoadCustom(), ItemBase::OnStoreSave(), FireplaceBase::OnStoreSave(), Grenade_Base::OnStoreSave(), ManBase::OnStoreSave(), ReplaceWithNewReciveCargoLambda::OnSuccess(), UnboxLambda::OnSuccess(), OnSuccess(), Backlit::OnSwimmingStop(), ItemBase::OnSwitchOff(), FlammableBase::OnSwitchOff(), ItemBase::OnSwitchOn(), FlammableBase::OnSwitchOn(), SymptomManager::OnSymptomExit(), WeaponManager::OnSyncJuncture(), ManBase::OnTick(), ShockMdfr::OnTick(), UniversalTemperatureSource::OnTimer(), TimerBase::OnTimer(), TreeHard::OnTreeCutDown(), TreeSoft::OnTreeCutDown(), BushHard::OnTreeCutDown(), BushSoft::OnTreeCutDown(), PluginBase::OnUIEditorOpened(), ManBase::OnUnconsciousStart(), ManBase::OnUnconsciousStop(), ManBase::OnUnconsciousUpdate(), OnUndergroundPresenceUpdate(), Grenade_Base::OnUnpin(), InventoryActionHandler::OnUpdate(), AlarmClock_ColorBase::OnUpdate(), UIPopupScript::OnUpdate(), ActionReadPaper::OnUpdate(), ActionWritePaper::OnUpdate(), CGame::OnUpdate(), PPERequester_GameplayBase::OnUpdate(), OnUpdate(), OnUpdate(), DayZPlayerCameraBase::OnUpdate(), DayZPlayerCamera1stPerson::OnUpdate(), OnUpdate(), MissionBase::OnUpdate(), OnUpdateClient(), Land_Underground_EntranceBase::OnUpdateServer(), BiosUserManager::OnUserLoggedOn(), BiosUserManager::OnUserPicked(), OnValveManipulationCanceled(), OnValveManipulationEnd(), OnValveManipulationStart(), Entity::OnVariablesSynchronized(), DayZPlayer::OnVariablesSynchronized(), InventoryItem::OnVariablesSynchronized(), ItemBase::OnVariablesSynchronized(), Ammo_40mm_Smoke_ColorBase::OnVariablesSynchronized(), OnVariablesSynchronized(), ScriptedWidgetEventHandler::OnVonStateEvent(), HeadGear_Base::OnWasAttached(), PlateCarrierVest::OnWasAttached(), OnWasAttached(), OnWasDetached(), WeaponManager::OnWeaponActionEnd(), ConsoleToolbarWidgetHandlerBase::OnWidgetScriptInit(), OnWork(), ItemBase::OnWork(), Clothing::OnWork(), Heatpack::OnWork(), PoweredOptic_Base::OnWork(), Roadflare::OnWork(), Switchable_Base::OnWork(), FlammableBase::OnWork(), ItemOptics::OnWorkStart(), OnWorkStart(), ItemBase::OnWorkStart(), Clothing::OnWorkStart(), Heatpack::OnWorkStart(), PoweredOptic_Base::OnWorkStart(), Roadflare::OnWorkStart(), Switchable_Base::OnWorkStart(), ItemOptics::OnWorkStop(), ItemBase::OnWorkStop(), Chemlight_ColorBase::OnWorkStop(), Clothing::OnWorkStop(), Heatpack::OnWorkStop(), PoweredOptic_Base::OnWorkStop(), Roadflare::OnWorkStop(), Switchable_Base::OnWorkStop(), FlammableBase::OnWorkStop(), ScriptedWidgetEventHandler::Open(), ScriptedWidgetEventHandler::OpenDiscord(), ScriptedWidgetEventHandler::OpenDLC(), ScriptedWidgetEventHandler::OpenFeedback(), BaseBuildingBase::OpenFence(), ScriptedWidgetEventHandler::OpenForums(), UIScriptedMenu::OpenMenu(), UIScriptedMenu::OpenMenu(), Land_Underground_EntranceBase::OpenServer(), ScriptedWidgetEventHandler::OpenTwitter(), UIManager::OpenWindow(), ScriptedWidgetEventHandler::OpenYoutube(), OptionSelectorBase::OptionSelector(), OptionSelectorBase::OptionSelectorEditbox(), OptionSelectorSliderSetup::OptionSelectorLevelMarker(), OptionSelectorSliderSetup::OptionSelectorSlider(), ScriptedWidgetEventHandler::OptionsMenuControls(), ScriptedWidgetEventHandler::OptionsMenuGame(), ScriptedWidgetEventHandler::OptionsMenuSounds(), ScriptedWidgetEventHandler::OptionsMenuVideo(), OrderedPositionNumbersFromGridCoords(), PPEffects::OverrideDOF(), ItemBase::Pack(), RemotelyActivatedItemBehaviour::Pair(), InventoryItem::PairWithDevice(), Inventory_Base::ParticleCookingStart(), ParticleCookingStop(), Inventory_Base::ParticleCookingStop(), ItemBase::ParticleTest(), CGame::PartyLaunch(), MissionBase::Pause(), ActionManagerClient::PerformActionStart(), Icon::PerformCombination(), ActionUnfoldMapCB::PerformMapChange(), BaseBuildingBase::PerformRoofCheckForBase(), UIScriptedMenu::PerformSetToDefaults(), UIScriptedMenu::PerformSetToDefaultsExt(), UIScriptedMenu::PerformSwitchPreset(), ItemBase::PileOfWoodenPlanks(), ItemBase::Pitch(), Hologram::PlaceEntity(), ItemBase::PlaceOnGround(), SceneObject::PlaceOnSurface(), EffectArea::PlaceParticles(), ManBase::PlacingStartLocal(), ItemBase::PlantBase(), Play(), UIScriptedMenu::Play(), PlayActionSound(), InventoryItem::PlayAttachSound(), InventoryItem::PlayDeployFinishSound(), ItemBase::PlayDeployLoopSound(), Inventory_Base::PlayDeployLoopSound(), InventoryItem::PlayDeployLoopSoundEx(), InventoryItem::PlayDeploySound(), PlayerContainer::PlayerContainer(), MissionBase::PlayerControlDisable(), MissionBase::PlayerControlEnable(), MissionBase::PlayerDisconnected(), PluginBase::PlayerList(), ScriptedWidgetEventHandler::PlayerListEntryScriptedWidget(), ScriptedWidgetEventHandler::PlayerListScriptedWidget(), PlayerPreview::PlayerPreview(), PlayerSoundManagerClient(), PlayerSyncCreate(), PlayerSyncDelete(), ContaminatedArea_Dynamic::PlayFlareVFX(), ContaminatedArea_Dynamic::PlayFX(), MissionBase::PlayMusic(), PlayParticle(), PluginBase::PlayPause(), InventoryItem::PlayPlaceSound(), PlaySFX(), DayZCreature::PlaySound(), EntityAI::PlaySound(), DayZPlayer::PlaySound(), IEntity::PlaySound(), PlaySoundActivate(), IEntity::PlaySoundLoop(), IEntity::PlaySoundSet(), PlaySurrenderInOut(), PlayVFX(), PluginBase::PluginAdminLog(), PluginDayzPlayerDebug_Weapons::PluginDayzPlayerDebug_Weapons(), ComponentEnergyManager::PlugInDevice(), UIPopupScript::PopupBack(), UIPopupScript::PopupOpen(), FirearmActionAttachMagazine::Post_SetupAction(), FirearmActionAttachMagazineQuick::Post_SetupAction(), RecoilBase::PostInit(), StaminaSoundHandlerBase::PostponeStamina(), Entity::PredictiveTakeEntityAsAttachment(), Entity::PredictiveTakeEntityAsAttachmentEx(), Entity::PredictiveTakeEntityToCargo(), Entity::PredictiveTakeEntityToCargoEx(), Entity::PredictiveTakeEntityToInventory(), Entity::PredictiveTakeEntityToTargetAttachment(), Entity::PredictiveTakeEntityToTargetAttachmentEx(), Entity::PredictiveTakeEntityToTargetCargo(), Entity::PredictiveTakeEntityToTargetCargoEx(), Entity::PredictiveTakeEntityToTargetInventory(), Entity::PredictiveTakeToDst(), ParticleList::PreloadParticles(), ReplaceItemWithNewLambdaBase::PrepareLocations(), ItemManager::PrepareTooltip(), MouseButtonInfo::Press(), ServerBrowserTabConsolePages::PressX(), ServerBrowserTab::PressX(), ActionMenu::PrevAction(), ActionMenu::PrevActionCategory(), UIScriptedMenu::PrimaryAction(), HeatComfortAnimHandler::Process(), ActionManagerClient::ProcessActionInputEnd(), ActionManagerClient::ProcessActionRequestEnd(), Edible_Base::ProcessDecay(), UIScriptedMenu::ProcessEmoteConditionRequest(), ManBase::ProcessFeetDamageServer(), ManBase::ProcessHandDamage(), BleedingSourcesManagerBase::ProcessHit(), EntityAI::ProcessImpactSoundEx(), Entity::ProcessInvulnerabilityCheck(), ProcessLighting(), MissionBase::ProcessLoginData(), Entity::ProcessMeleeItemDamage(), ProcessSound(), InjurySoundHandlerBase::ProcessSound(), ProcessSound(), DayZCreature::ProcessSoundEvent(), DayZPlayer::ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), DayZInfected::ProcessSoundVoiceEvent(), DayZInfected::ProcessVoiceFX(), DayZPlayer::ProcessWeaponEvent(), ScriptedWidgetEventHandler::ProjectedCrosshair(), RadialMenu(), RadialProgressBar::RadialProgressBar(), UIScriptedMenu::RadialQuickbarMenu(), RainProcurementManager::RainProcurementCheck(), RainProcurementComponentBase::RainProcurementComponentBase(), MissionBase::RandomArtillery(), Randomize(), UIScriptedMenu::RandomizeCharacter(), ReceiveMaterialsServer(), DebugMonitorValues::ReceiveValue(), ItemBase::Refresh(), ActionMenu::Refresh(), UIScriptedMenu::Refresh(), Refresh(), ScriptedWidgetEventHandler::RefreshDLCIcon(), RefreshFireplaceVisuals(), ManBase::RefreshHandAnimationState(), ScriptConsoleGeneralTab::RefreshPlayerPosEditBoxes(), Hud::RefreshPlayerTags(), Icon::RefreshQuickbar(), RefreshQuickbar(), Hud::RefreshQuickbar(), AttachmentCategoriesRow::RefreshSlot(), RefreshState(), Hud::RefreshVehicleHud(), VicinityItemManager::RefreshVicinityItems(), Hologram::RefreshVisual(), ItemBase::RegenerateNavmesh(), DayZCreature::RegisterAnimEvents(), RegisterAttacks(), BleedingSourcesManagerBase::RegisterBleedingZoneEx(), SyncEvents::RegisterEvents(), GameplayEffectWidgets_base::RegisterLayouts(), PluginManager::RegisterPlugin(), DayZProfilesOptions::RegisterProfileOptionFloat(), DayZProfilesOptions::RegisterProfileOptionInt(), IEntity::Release(), MouseButtonInfo::Release(), Release(), PluginBase::ReleaseFocus(), ReleaseFocus(), ScriptedWidgetEventHandler::Reload(), InventoryGridController::Remove(), EntityAI::RemoveAction(), RemoveAction(), InventoryItem::RemoveAction(), ManBase::RemoveActiveNV(), SceneObject::RemoveAttachment(), BleedingSourcesManagerBase::RemoveBleedingSource(), RemoveInsider(), ReplaceItemWithNewLambdaBase::RemoveNetworkObjectInfo(), RemoveNetworkObjectInfo(), ItemBase::RemovePlant(), ItemBase::RemovePlantEx(), BaseBuildingBase::RemoveRefresherPosition(), ItemBase::RemoveSlot(), RemoveSplint(), ScriptConsoleVicinityTab::RenderList(), ActionRepairPart::RepairCondition(), ActionRepairTent::RepairDamageTransfer(), DestructionEffectBase::ReplaceEntityServer(), UndergroundTriggerCarrierBase::RequestDelayedTriggerSpawn(), RequestDetailedInfo(), ManBase::RequestHandAnimationStateRefresh(), Land_Underground_EntranceBase::RequestLatentTransition(), ManBase::RequestResetADSSync(), UIScriptedMenu::RequestRespawn(), FireworksLauncherClientEvent::RequestSecondaryExplosion(), House::RequestSoundEvent(), UIScriptedMenu::Reset(), UIScriptedMenu::ResetCurrentTab(), ComponentEnergyManager::ResetEnergyUsage(), PluginBase::ResetGUI(), ResetModifiers(), DayZProfilesOptions::ResetOptionsFloat(), DayZProfilesOptions::ResetOptionsInt(), ManBase::ResetPlayer(), PPEffects::ResetPPMask(), UIPopupScript::ResetSliders(), HudDebugWinBase::ResetStats(), Icon::RevertToOriginalFlip(), RightArea::RightArea(), ServerBrowserTab::RightHold(), IEntity::RPC(), HudDebugWinBase::RPCChangeStat(), IEntity::RPCSingleParam(), array::Run(), ScriptConsoleEnfScriptTab::RunEnscript(), ScriptConsoleEnfScriptTab::RunEnscriptServer(), PluginBase::Save(), Managed::SaveCharName(), DayZIntroSceneXbox::SaveCharName(), UIScriptedMenu::SaveFavoriteServersConsoles(), ScriptedWidgetEventHandler::SaveFilters(), PlayerStats::SaveStats(), BetaSound::SaySound(), ManBase::SaySoundSet(), Dispatcher::SceneEditorCommand(), PluginBase::SceneLoad(), SceneObject::SceneObjectSynch(), UIScriptedMenu::ScriptConsole(), Dispatcher::ScriptConsoleAddPrint(), ScriptConsoleGeneralTab::ScriptConsoleGeneralTab(), Dispatcher::ScriptConsoleHistoryBack(), Dispatcher::ScriptConsoleHistoryForward(), ScriptConsoleSoundsTab::ScriptConsoleSoundsTab(), EntityLightSource::ScriptedLightBase(), UIScriptedMenu::SecondaryAction(), Attachments::Select(), Container::Select(), HandsPreview::Select(), AttachmentCategoriesRow::Select(), PlayerContainer::Select(), VicinitySlotsContainer::Select(), ZombieContainer::Select(), PluginBase::SelectAndFocusPlayerObject(), SelectCrossHair(), SelectEvent(), ScriptedWidgetEventHandler::SelectPlayer(), CGame::SelectUser(), SendEmoteRequestSync(), InventoryInputUserData::SendInputUserDataDestroy(), InventoryInputUserData::SendInputUserDataHandEvent(), InventoryInputUserData::SendInputUserDataMove(), InventoryInputUserData::SendInputUserDataSwap(), ManBase::SendLiftWeaponSync(), SendMessageToClient(), ActionEmptyBottleBase::SendRPC(), ScriptConsoleWeatherTab::SendRPC(), SendRPC(), PluginBase::SendRPCAgents(), InventoryInputUserData::SendServerHandEventViaInventoryCommand(), SendServerHandEventViaJuncture(), PluginBase::SendServerLogToClient(), InventoryInputUserData::SendServerMove(), InventoryInputUserData::SendServerSwap(), ManBase::SendSoundEventEx(), SyncEvents::SendSyncEvent(), SendSyncMessages(), Managed::SendValue(), DebugMonitorValues::SendValue(), ItemManager::SerializeDefaultHeaderOpenStates(), ItemManager::SerializeDefaultOpenStates(), ScriptedWidgetEventHandler::ServerBrowserEntry(), ScriptedWidgetEventHandler::ServerBrowserFilterContainer(), ServerBrowserTab(), InventoryActionHandler::SetAction(), SetActive(), ItemBase::SetActive(), HandsContainer::SetActive(), SetAlarmInXMins(), PluginBase::SetBadge(), PPEffects::SetBlur(), Roadflare::SetBurningStateSynchronized(), SetBurntFirewood(), SetCarHornState(), UIScriptedMenu::SetCharacter(), PPEffects::SetChromAbb(), SetControlType(), ItemManager::SetDefaultOpenStateHands(), UniversalTemperatureSourceDebug::SetDefferedActive(), PluginBase::SetDeveloperItemClient(), PluginBase::SetDeveloperItemClientEx(), BleedingSourcesManagerBase::SetDiag(), SetDisplayNameText(), WeaponManager::SetEjectBulletTryTimestamp(), ComponentEnergyManager::SetEnergy(), SetEntityShortcut(), Ammunition_Base::SetFromProjectile(), OnlineServices::SetGameplayActivity(), UIScriptedMenu::SetGameVersion(), WorldLighting::SetGlobalLighting(), CTObjectFollower::SetHandsItem(), SceneObject::SetHealth(), ItemBase::SetInactive(), SceneData::SetInitDay(), SceneData::SetInitFog(), SceneData::SetInitHour(), SceneData::SetInitMinute(), SceneData::SetInitMonth(), SceneData::SetInitOvercast(), SceneData::SetInitRain(), SceneData::SetInitWindForce(), SceneData::SetInitYear(), SlotsIcon::SetItemSize(), Icon::SetItemSizeEx(), HandsContainer::SetLastActive(), EntityLightSource::SetLifetime(), Container::SetLock(), SetLockOnAttachedMaterials(), PPEffects::SetNVParams(), SetNVPostprocess(), TrapTrigger::SetParentObject(), OnlineServices::SetPendingInviteList(), PlayerContainer::SetPlayer(), DeveloperTeleport::SetPlayerDirection(), DeveloperTeleport::SetPlayerPosition(), SceneObject::SetPosition(), UIScriptedMenu::SetPreset(), ScriptConsoleItemsTab::SetPreviewObject(), DayZProfilesOptions::SetProfileOption(), DayZProfilesOptions::SetProfileOptionFloat(), DayZProfilesOptions::SetProfileOptionInt(), SetProfileValueBool(), PPEffects::SetRadialBlur(), ConstructionPart::SetRequestBuiltState(), UIScriptedMenu::SetServerInfo(), ItemBase::SetSlotTextureFertilized(), SetSmokeGrenadeState(), ItemBase::SetSpoiled(), PluginBase::SetStamina(), Hud::SetStamina(), PluginBase::SetStance(), SetState(), LoginScreenBase::SetTime(), CAContinuousFertilizeGardenSlot::Setup(), SetupAction(), ActionBuildPart::SetupAction(), ActionFishingNew::SetupAction(), ActionWorldCraft::SetupAction(), ActionBuildShelter::SetupAction(), ActionDetachFromTarget::SetupAction(), SetupAction(), ActionAttachOnSelection::SetupAction(), ActionAttachWithSwitch::SetupAction(), SetUpdate(), HudDebugWinBase::SetUpdate(), Managed::SetupPlayerName(), PluginBase::SetupSpawnedEntity(), SetupTrap(), ItemBase::SetupTrap(), TrapSpawnBase::SetupTrap(), SetupTrapPlayer(), ItemBase::SetupTrapPlayer(), ItemBase::SetUsed(), PPERequester_GameplayBase::SetValuesIronsights(), PPERequester_GameplayBase::SetValuesOptics(), InventoryItem::SetVariableMask(), Entity::SetViewIndex(), SetWaterLevelHeight(), UIScriptedMenu::ShoesChanged(), ShootsExplosiveAmmo(), ScriptedWidgetEventHandler::ShowActionMenu(), HandsContainer::ShowActionMenuCombine(), Icon::ShowActionMenuCombine(), Entity::ShowAllSelections(), MissionBase::ShowChat(), DayZPlayer::ShowDeadScreen(), ServerBrowserTab::ShowHideConsoleWidgets(), MissionBase::ShowInventory(), OnlineServices::ShowInviteScreen(), Hud::ShowPlayerTag(), ItemOptics::ShowReddot(), ItemManager::ShowSourceDropzone(), ManBase::ShowUnconsciousScreen(), Hud::ShowVehicleInfo(), ShowVoiceNotification(), FlareSimulation::Simulate(), DayZPlayer::SimulateDeath(), EnProfilerTests::Sleep(), SleepAgain(), SlotsIcon::SlotsIcon(), SnapOnObject(), DayZIntroScene::SnapToGround(), DayZIntroSceneXbox::SnapToGround(), SoftSkillManagerDebug(), ActionSortAmmoPile::SortAmmo(), ItemBase::SoundBuzzLoopStart(), ItemBase::SoundBuzzLoopStop(), ItemBase::SoundCollision(), ItemBase::SoundCut(), ItemBase::SoundElectricShock(), BaseBuildingBase::SoundGateCloseEnd(), BaseBuildingBase::SoundGateCloseStart(), BaseBuildingBase::SoundGateOpenStart(), EffectSound::SoundPlayEx(), ItemBase::SoundSpark(), ManBase::SpawnAI(), ItemBase::SpawnCatch(), TrapSpawnBase::SpawnCatch(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), ManBase::SpawnDrowningBubbles(), PluginBase::SpawnEntityAsAttachment(), PluginBase::SpawnEntityInInventory(), PluginBase::SpawnEntityInPlayerInventory(), PluginBase::SpawnEntityOnCursorDir(), PluginBase::SpawnEntityOnGroundPatternGrid(), PluginBase::SpawnEntityOnGroundPos(), ManBase::SpawnEntityOnGroundPos(), PluginBase::SpawnFromClipboard(), PluginBase::SpawnItemOnCrosshair(), ContaminatedArea_Dynamic::SpawnItems(), SpawnItems(), TentBase::SpawnKit(), PluginBase::SpawnNewInfectedEntity(), ObjectSpawnerHandler::SpawnObject(), ScriptConsoleItemsTab::SpawnPreset(), CrashBase::SpawnRandomDeerLater(), CrashBase::SpawnRandomDeers(), UndergroundTriggerCarrierBase::SpawnTrigger(), UndergroundAreaLoader::SpawnTriggerCarrier(), InventoryItem::SplitIntoStackMax(), InventoryItem::SplitIntoStackMaxCargoClient(), InventoryItem::SplitIntoStackMaxClient(), InventoryItem::SplitIntoStackMaxHandsClient(), InventoryItem::SplitIntoStackMaxToInventoryLocationClient(), HandsContainer::SplitItem(), ManBase::SpreadAgentsEx(), StaminaHandler::StaminaHandler(), Chemlight_ColorBase::StandUp(), FlammableBase::StandUp(), Start(), ActionRepositionPluggedItem::Start(), ActionSwitchSeats::Start(), WeaponManager::StartAction(), StartActivate(), ActionManagerServer::StartDeliveredAction(), StartFire(), MissionBase::StartLogoutMenu(), ItemBase::StartLoopSound(), PoweredOptic_Base::StartPeriodicMeasurement(), StartSourceBleedingIndication(), TriggerEvents::Stay(), TriggerEvents::StayFinish(), TriggerEvents::StayStart(), Stop(), UIScriptedMenu::Stop(), ItemBase::StopDeployLoopSound(), Inventory_Base::StopDeployLoopSound(), InventoryItem::StopDeployLoopSoundEx(), StopFire(), StopParticle(), ScrollBarContainer::StopScrolling(), IEntity::StopSoundSet(), StopSourceBleedingIndication(), UIScriptedMenu::StopVideo(), EnProfilerTests::StringConcat(), EnProfilerTests::StringFormat(), Icon::Swap(), ManBase::SwitchItemTypeAttach(), ComponentEnergyManager::SwitchOff(), ComponentEnergyManager::SwitchOn(), PluginBase::SwitchPermanentCrossHair(), PlayerBase::SwitchPersonalLight(), SwitchPreset(), CfgGameplayHandler::SyncDataSend(), UndergroundAreaLoader::SyncDataSend(), CfgGameplayHandler::SyncDataSendEx(), MissionBase::SyncGlobalLighting(), Synch(), SoftSkillsManager::SynchDebugStats(), IEntity::SynchExplosion(), WeaponManager::Synchronize(), ItemBase::Synchronize(), Synchronize(), Edible_Base::Synchronize(), Inventory_Base::Synchronize(), ItemBase::SynchronizeBaseState(), ComponentBodyStaging::SynchSkinnedState(), SoftSkillsManager::SynchSpecialtyLevel(), InventoryItemSuper::SyncMapMarkers(), ItemBase::SyncSlots(), SymptomBase::SyncToClientActivated(), SymptomBase::SyncToClientDeactivated(), SyncValveVariables(), HandsContainer::TakeAsAttachment(), ClosableContainer::TakeAsAttachment(), EntityAI::TakeEntityToHandsImpl(), TakeMaterialsServer(), TakeToDst(), ScriptConsoleGeneralTab::Teleport(), DeveloperTeleport::TeleportAtCursor(), DeveloperTeleport::TeleportAtCursorEx(), TeleportCheck(), TestCleanup(), EnProfilerTests::TestFuncCountData(), PMTPlayback::TestOnePlaying(), PMTPlayback::TestOnePlayingStandAlone(), PMTPlayback::TestOnePlayingStandAloneAutoDestroy(), TestOwnership(), ManBase::TestSend(), PMTPlayback::TestStopping(), PMTPlayback::TestWiggleStress(), HumanInventory::ThrowEntity(), ThrowEntityFromInventory(), Tick(), PluginDayzPlayerDebug_Weapons::Tick(), AnimationTimer::Tick(), Tick(), TickNotifiers(), MissionBase::TickScheduler(), PluginBase::ToggleCameraTools(), ToggleDebugWindowEvent(), PluginBase::ToggleFocus(), PluginBase::ToggleFreeCamera(), PluginBase::ToggleFreeCameraBackPos(), PluginBase::ToggleMissionLoader(), ScriptedWidgetEventHandler::ToggleMute(), ManBase::TogglePlacingLocal(), PluginBase::ToggleScriptConsole(), UIScriptedMenu::TopChanged(), TransferInventory(), Attachments::TransferItem(), Container::TransferItem(), HandsContainer::TransferItem(), AttachmentCategoriesRow::TransferItem(), PlayerContainer::TransferItem(), VicinitySlotsContainer::TransferItem(), ZombieContainer::TransferItem(), TransferItemProperties(), Attachments::TransferItemToVicinity(), Container::TransferItemToVicinity(), HandsContainer::TransferItemToVicinity(), AttachmentCategoriesRow::TransferItemToVicinity(), PlayerContainer::TransferItemToVicinity(), ZombieContainer::TransferItemToVicinity(), DayZPlayer::TriggerPullPlayerOutOfVehicle(), TryAcquireInventoryJunctureFromServer(), TryAcquireTwoInventoryJuncturesFromServer(), Entity::TryDelete(), ItemBase::TryPitch(), EntityLightSource::TryShadowOptimization(), FlammableBase::TryTransformIntoStick(), ScriptedWidgetEventHandler::TutorialKeybinds(), ScriptedWidgetEventHandler::UiHintPanel(), UIPropertyAttachment::UIPropertyAttachment(), PluginDayzPlayerDebug_OtherCmds::Uncon_End(), PluginDayzPlayerDebug_OtherCmds::Uncon_Start(), UndergroundHandlerClient(), ReplaceItemWithNewLambdaBase::UndoRemoveNetworkObjectInfo(), UndoRemoveNetworkObjectInfo(), Inventory_Base::Unfold(), UnlimitedAmmoDebugCheck(), UIMenuPanel::UnlockControls(), ComponentEnergyManager::UnplugDevice(), ComponentEnergyManager::UnplugThis(), UpdataControllerInput(), Update(), StaminaSoundHandlerBase::Update(), ActionTargetsCursor::Update(), ScriptedWidgetEventHandler::Update(), HudDebugWinBase::Update(), Update(), ShockHandler::Update(), WeaponManager::Update(), StaminaHandler::Update(), SymptomBase::Update(), UIScriptedMenu::Update(), ScriptConsoleGeneralTab::Update(), ScriptConsoleSoundsTab::Update(), ScriptConsoleWeatherTab::Update(), GameplayEffectsData::Update(), ActionManagerClient::Update(), ActionManagerServer::Update(), Update(), Roadflare::UpdateActiveParticles(), ScriptedWidgetEventHandler::UpdateAudioLevel(), WorldData::UpdateBaseEnvTemperature(), Hud::UpdateBloodName(), ComponentEnergyManager::UpdateCanWork(), FlammableBase::UpdateCheckForReceivingUpgrade(), PPEffects::UpdateColor(), InputUtils::UpdateConsolePresetID(), UpdateConsoleToolbar(), UpdateConstructionParts(), UIScriptedMenu::UpdateControlsElements(), UIScriptedMenu::UpdateControlsElementVisibility(), WarningMenuBase::UpdateControlsElementVisibility(), MissionBase::UpdateCorpseStatesServer(), MissionBase::UpdateDebugMonitor(), ManBase::UpdateDelete(), UpdateDistanceWidget(), ClosableHeader::UpdateFlip(), Icon::UpdateFlip(), ItemBase::UpdateFuelMeter(), UIScriptedMenu::UpdateGUI(), ScriptedWidgetEventHandler::UpdateIconVisibility(), UIScriptedMenu::UpdateInfo(), UIScriptedMenu::UpdateInfoPanelText(), UpdateInsiders(), AreaDamageTriggerBase::UpdateInsiders(), Attachments::UpdateInterval(), HandsPreview::UpdateInterval(), HandsHeader::UpdateInterval(), VicinityContainer::UpdateInterval(), UpdateInterval(), PlayerPreview::UpdateInterval(), InventoryGridController::UpdateItems(), UpdateLifespan(), ManBase::UpdateLighting(), MissionBase::UpdateLogoutPlayers(), FlammableBase::UpdateMaterial(), UIScriptedMenu::UpdateMenuFocus(), ScriptConsoleGeneralTab::UpdateMousePos(), ScriptConsoleSoundsTab::UpdateMousePos(), ItemBase::UpdateNavmesh(), PumpkinHelmet::UpdateNVGStatus(), NotificationUI::UpdateOffset(), ActionTargetsCursor::UpdatePCIconsVisibility(), ScriptedWidgetEventHandler::UpdatePCIconsVisibility(), ItemBase::UpdatePhysics(), MissionBase::UpdatePlayersStats(), ScriptedWidgetEventHandler::UpdatePos(), Hud::UpdateQuickbarGlobalVisibility(), DayZIntroSceneXbox::UpdateSelectedUserName(), Hologram::UpdateSelections(), KazuarOptic::UpdateSelectionVisibility(), StarlightOptic::UpdateSelectionVisibility(), UpdateSpecialtyMeter(), ScriptedWidgetEventHandler::UpdateStats(), ItemBase::UpdateStatusLights(), PluginBase::UpdateStatWidgets(), ScriptConsoleGeneralTab::UpdateTime(), ScriptedWidgetEventHandler::UpdateTotalTime(), UpdateVisuals(), UpdateVoiceIcon(), ScriptedWidgetEventHandler::UpdateWasMicCapturing(), ActionMenu::UpdateWidgets(), UpdateWidgetsStats(), UIMenuPanel::UseKeyboard(), UIMenuPanel::UseMouse(), ValidateDestroy(), ValidateSyncMove(), ScriptedWidgetEventHandler::VideoPlayer(), VirtualHud(), WarningMenuBase::WarningMenuBase(), Weapon::Weapon_Base(), WeaponParticlesBase::WeaponParticlesBase(), WorldData::WeatherOnBeforeChange(), IEntity::WorldToModel(), CrashBase::Wreck_Mi8_Crashed(), CrashBase::Wreck_SantasSleigh(), CrashBase::Wreck_UH1Y(), ActionUnfoldMapCB::~ActionUnfoldMapCB(), UIScriptedMenu::~CameraToolsMenu(), ScriptedWidgetEventHandler::~ContinuousActionProgress(), ~CrossHairSelector(), DayZIntroSceneXbox::~DayZIntroSceneXbox(), EmoteCB::~EmoteCB(), UIScriptedMenu::~GesturesMenu(), HandsPreview::~HandsPreview(), Hologram::~Hologram(), UIScriptedMenu::~InGameMenuXbox(), UIScriptedMenu::~InspectMenuNew(), UIScriptedMenu::~InviteMenu(), ScriptedWidgetEventHandler::~ItemActionsWidget(), InventoryItem::~ItemBase(), UIScriptedMenu::~LogoutMenu(), UIScriptedMenu::~MainMenu(), MainMenuButtonEffect::~MainMenuButtonEffect(), UIScriptedMenu::~MainMenuConsole(), ScriptedWidgetEventHandler::~MainMenuDlcHandlerBase(), UIScriptedMenu::~MapMenu(), MissionBaseWorld::~MissionBase(), MissionBase::~MissionServer(), UIScriptedMenu::~NoteMenu(), ScriptedWidgetEventHandler::~OptionsMenuSounds(), ScriptedWidgetEventHandler::~OptionsMenuVideo(), ManBase::~PlayerBase(), PluginManager::~PluginManager(), ScriptedWidgetEventHandler::~ProjectedCrosshair(), RadialProgressBar::~RadialProgressBar(), UIScriptedMenu::~RadialQuickbarMenu(), SceneObject::~SceneObject(), UIScriptedMenu::~ScriptConsole(), ScriptConsoleGeneralTab::~ScriptConsoleGeneralTab(), ~ServerBrowserTab(), ShockDealtEffect::~ShockDealtEffect(), ~SoftSkillManagerDebug(), ItemBase::~TentBase(), UIPopupScript::~UIPopupScriptSceneManager(), UIPopupScript::~UIPopupScriptSceneSettings(), ~UndergroundHandlerClient(), UndergroundTriggerCarrierBase::~UndergroundTriggerCarrier(), and WarningMenuBase::~WarningMenuBase().
GetMax()
proto native float GetMax ()
Referenced by ManBase::ResetPlayer().
GetMin()
proto native float GetMin ()
GetPathFromSlotID()
static string GetPathFromSlotID (int slot_ID) static
Returns config path of att. slot category, empty if undefined.
Definition at line 1144 of file gameplay.c.
  {
    int idx = m_AttachmentSlots.Find(slot_ID);
    string path = "" + m_Path + " " + m_ConfigArrayNames.Get(idx);
    return path;
  }
References m_AttachmentSlots, m_ConfigArrayNames, m_Path, and path.
Referenced by GetConfigArrayCountFromSlotID(), and GetConfigAttachmentTypes().
SpawnEntity()
EntityAI SpawnEntity (string object_name, notnull InventoryLocation inv_loc, int iSetupFlags, int iRotation)
Definition at line 1466 of file gameplay.c.
{
  return GameInventory.LocationCreateEntity(inv_loc, object_name, iSetupFlags, iRotation);
}
References GameInventory::LocationCreateEntity().
WriteValue()
proto native void WriteValue (float value)
Variable Documentation
ChatChannelEventTypeID
const EventType ChatChannelEventTypeID
params: ChatChannelEventParams
Definition at line 486 of file gameplay.c.
Referenced by MissionBase::OnEvent().
ChatMessageEventTypeID
const EventType ChatMessageEventTypeID
params: ChatMessageEventParams
Definition at line 484 of file gameplay.c.
Referenced by CGame::OnEvent(), and MissionBase::OnEvent().
ClientConnectedEventTypeID
const EventType ClientConnectedEventTypeID
params: ClientConnectedEventParams
Definition at line 490 of file gameplay.c.
ClientDisconnectedEventTypeID
const EventType ClientDisconnectedEventTypeID
params: ClientDisconnectedEventParams
Definition at line 504 of file gameplay.c.
Referenced by MissionBase::OnEvent().
ClientNewEventTypeID
const EventType ClientNewEventTypeID
params: ClientNewEventParams
Definition at line 494 of file gameplay.c.
Referenced by MissionBase::OnEvent().
ClientNewReadyEventTypeID
const EventType ClientNewReadyEventTypeID
params: ClientNewReadyEventParams
Definition at line 496 of file gameplay.c.
ClientPrepareEventTypeID
const EventType ClientPrepareEventTypeID
params: ClientPrepareEventParams
Definition at line 492 of file gameplay.c.
Referenced by MissionBase::OnEvent().
ClientReadyEventTypeID
const EventType ClientReadyEventTypeID
params: ClientReadyEventParams
Definition at line 502 of file gameplay.c.
Referenced by MissionBase::OnEvent().
ClientReconnectEventTypeID
const EventType ClientReconnectEventTypeID
params: ClientReconnectEventParams
Definition at line 500 of file gameplay.c.
Referenced by MissionBase::OnEvent().
ClientRemovedEventTypeID
const EventType ClientRemovedEventTypeID
no params
Definition at line 506 of file gameplay.c.
ClientRespawnEventTypeID
const EventType ClientRespawnEventTypeID
params: ClientRespawnEventParams
Definition at line 498 of file gameplay.c.
Referenced by MissionBase::OnEvent().
ConnectingAbortEventTypeID
const EventType ConnectingAbortEventTypeID
no params
Definition at line 554 of file gameplay.c.
Referenced by CGame::OnEvent().
ConnectingStartEventTypeID
const EventType ConnectingStartEventTypeID
no params
Definition at line 552 of file gameplay.c.
Referenced by CGame::OnEvent().
ConnectivityStatsUpdatedEventTypeID
const EventType ConnectivityStatsUpdatedEventTypeID
params: ConnectivityStatsUpdatedEventParams
Definition at line 510 of file gameplay.c.
Referenced by CGame::OnEvent().
DialogQueuedEventTypeID
const EventType DialogQueuedEventTypeID
no params
Definition at line 480 of file gameplay.c.
Referenced by CGame::OnEvent().
DLCOwnerShipFailedEventTypeID
const EventType DLCOwnerShipFailedEventTypeID
params: DLCOwnerShipFailedParams
Definition at line 548 of file gameplay.c.
Referenced by CGame::OnEvent().
Event_OnRevert
ref ScriptInvoker Event_OnRevert = new ScriptInvoker()
Definition at line 0 of file gameplay.c.
INDEX_NOT_FOUND
const int INDEX_NOT_FOUND = -1
Definition at line 13 of file gameplay.c.
Referenced by VicinityItemManager::AddVicinityCargos(), VicinityItemManager::AddVicinityItems(), EOnPostSimulate(), SpacerBase::GetChildIndex(), GetComponentIndex(), GPSReceiver::GetHiddenSelection(), GetTurnableValveIndex(), Init(), InventoryGridController::InventoryQuickbar(), InventoryGridController::OnItemDrop(), InventoryGridController::OnItemDropReceived(), OnItemInPlayerPossession(), VicinityItemManager::RefreshVicinityItems(), GPSReceiver::UpdateDisplayElevation(), and GPSReceiver::UpdateDisplayPosition().
LoginStatusEventTypeID
const EventType LoginStatusEventTypeID
params: LoginStatusEventParams
Definition at line 524 of file gameplay.c.
Referenced by CGame::OnEvent().
LoginTimeEventTypeID
const EventType LoginTimeEventTypeID
params: LoginTimeEventParams
Definition at line 516 of file gameplay.c.
Referenced by CGame::OnEvent().
LogoutCancelEventTypeID
const EventType LogoutCancelEventTypeID
params: LogoutCancelEventParams
Definition at line 514 of file gameplay.c.
Referenced by MissionBase::OnEvent().
LogoutEventTypeID
const EventType LogoutEventTypeID
params: LogoutEventParams
Definition at line 522 of file gameplay.c.
Referenced by CGame::OnEvent().
m_AttachmentSlots
class MenuDefaultCharacterData m_AttachmentSlots
Initial value:
= {
    InventorySlots.SHOULDER,
    InventorySlots.MELEE,
    InventorySlots.HEADGEAR,
    InventorySlots.MASK,
    InventorySlots.EYEWEAR,
    InventorySlots.GLOVES,
    InventorySlots.ARMBAND,
    InventorySlots.BODY,
    InventorySlots.VEST,
    InventorySlots.BACK,
    InventorySlots.HIPS,
    InventorySlots.LEGS,
    InventorySlots.FEET
  }
Referenced by GetAttachmentSlotsArray(), and GetPathFromSlotID().
m_ConfigArrayNames
ref array<string> m_ConfigArrayNames static
Initial value:
= {
    "shoulder",
    "melee",
    "headgear",
    "mask",
    "eyewear",
    "gloves",
    "armband",
    "top",
    "vests",
    "backpacks",
    "hips",
    "bottom",
    "shoe"
  }
Definition at line 1125 of file gameplay.c.
{
    "shoulder",
    "melee",
    "headgear",
    "mask",
    "eyewear",
    "gloves",
    "armband",
    "top",
    "vests",
    "backpacks",
    "hips",
    "bottom",
    "shoe"
  };
Referenced by GetConfigArrayNames(), and GetPathFromSlotID().
m_Path
const string m_Path = "cfgCharacterCreation" static
Definition at line 1141 of file gameplay.c.
Referenced by GetPathFromSlotID().
MPConnectionCloseEventTypeID
const EventType MPConnectionCloseEventTypeID
params: MPConnectionCloseEventParams
Definition at line 470 of file gameplay.c.
MPConnectionLostEventTypeID
const EventType MPConnectionLostEventTypeID
params: MPConnectionLostEventParams
Definition at line 468 of file gameplay.c.
Referenced by CGame::OnEvent().
MPSessionEndEventTypeID
const EventType MPSessionEndEventTypeID
no params
Definition at line 462 of file gameplay.c.
Referenced by CGame::OnEvent().
MPSessionFailEventTypeID
const EventType MPSessionFailEventTypeID
no params
Definition at line 464 of file gameplay.c.
Referenced by CGame::OnEvent().
MPSessionPlayerReadyEventTypeID
const EventType MPSessionPlayerReadyEventTypeID
no params
Definition at line 466 of file gameplay.c.
Referenced by CGame::OnEvent(), ConnectErrorClientModule::OnEvent(), OnEvent(), and ConnectErrorServerModule::OnEvent().
MPSessionStartEventTypeID
const EventType MPSessionStartEventTypeID
no params
Definition at line 460 of file gameplay.c.
Referenced by CGame::OnEvent().
NetworkManagerClientEventTypeID
const EventType NetworkManagerClientEventTypeID
no params
Definition at line 476 of file gameplay.c.
NetworkManagerServerEventTypeID
const EventType NetworkManagerServerEventTypeID
no params
Definition at line 478 of file gameplay.c.
NullStringArray
class MeleeCombatData NullStringArray[1] = { "" }
Object
class LOD Object
Referenced by ScriptConsoleVicinityTab::RenderList().
PartyChatStatusChangedEventTypeID
const EventType PartyChatStatusChangedEventTypeID
no params
Definition at line 546 of file gameplay.c.
Referenced by OnEvent().
PlayerDeathEventTypeID
const EventType PlayerDeathEventTypeID
params: PlayerDeathEventParams
Definition at line 556 of file gameplay.c.
PreloadEventTypeID
const EventType PreloadEventTypeID
params: PreloadEventParams
Definition at line 520 of file gameplay.c.
Referenced by CGame::OnEvent().
PROGRESS_FINISH
const int PROGRESS_FINISH = 1
Definition at line 382 of file gameplay.c.
Referenced by CGame::LoadProgressUpdate().
PROGRESS_PROGRESS
const int PROGRESS_PROGRESS = 2
Definition at line 383 of file gameplay.c.
Referenced by CGame::LoadProgressUpdate().
PROGRESS_START
PlayerIdentity PROGRESS_START = 0
Referenced by CGame::LoadProgressUpdate().
PROGRESS_UPDATE
const int PROGRESS_UPDATE = 3
Definition at line 384 of file gameplay.c.
Referenced by CGame::LoadProgressUpdate().
ProgressEventTypeID
const EventType ProgressEventTypeID
params: ProgressEventParams
Definition at line 474 of file gameplay.c.
Referenced by CGame::OnEvent().
ReadValue
class OptionsAccessEvents ReadValue
RespawnEventTypeID
const EventType RespawnEventTypeID
params: RespawnEventParams
Definition at line 518 of file gameplay.c.
Referenced by CGame::OnEvent().
ScriptLogEventTypeID
const EventType ScriptLogEventTypeID
params: ScriptLogEventParams
Definition at line 530 of file gameplay.c.
SelectedUserChangedEventTypeID
const EventType SelectedUserChangedEventTypeID
no params
Definition at line 528 of file gameplay.c.
Referenced by CGame::OnEvent().
ServerFpsStatsUpdatedEventTypeID
const EventType ServerFpsStatsUpdatedEventTypeID
params: ServerFpsStatsUpdatedEventParams
Definition at line 512 of file gameplay.c.
Referenced by CGame::OnEvent().
SetFreeCameraEventTypeID
const EventType SetFreeCameraEventTypeID
params: SetFreeCameraEventParams
Definition at line 550 of file gameplay.c.
Referenced by MissionBase::OnEvent().
StartupEventTypeID
const EventType StartupEventTypeID
no params
Definition at line 454 of file gameplay.c.
Referenced by CGame::OnEvent().
VONStartSpeakingEventTypeID
const EventType VONStartSpeakingEventTypeID
params: VONStartSpeakingEventParams
Definition at line 536 of file gameplay.c.
Referenced by OnEvent().
VONStateEventTypeID
const EventType VONStateEventTypeID
params: VONStateEventParams
Definition at line 534 of file gameplay.c.
Referenced by OnEvent().
VONStopSpeakingEventTypeID
const EventType VONStopSpeakingEventTypeID
params: VONStopSpeakingEventParams
Definition at line 538 of file gameplay.c.
Referenced by OnEvent().
VONUserStartedTransmittingAudioEventTypeID
const EventType VONUserStartedTransmittingAudioEventTypeID
no params
Definition at line 540 of file gameplay.c.
Referenced by OnEvent().
VONUserStoppedTransmittingAudioEventTypeID
const EventType VONUserStoppedTransmittingAudioEventTypeID
no params
Definition at line 542 of file gameplay.c.
Referenced by OnEvent().
WorldCleaupEventTypeID
const EventType WorldCleaupEventTypeID
no params
Definition at line 456 of file gameplay.c.
Referenced by CGame::OnEvent().