DayZ: scripts/4_World/Entities/ItemBase/FireplaceBase.c File Reference
FireplaceBase.c File Reference
Enumerations
enum FireplaceFireState {
NO_FIRE = 1 , START_FIRE = 2 , SMALL_FIRE = 3 , NORMAL_FIRE = 4 ,
END_FIRE = 5 , EXTINGUISHING_FIRE = 6 , EXTINGUISHED_FIRE = 7 , REIGNITED_FIRE = 8 ,
COUNT = 9
}
Functions
void FireplaceBase ()
void ~FireplaceBase ()
override void EEInit ()
override void EEItemAttached (EntityAI item, string slot_name)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnAttachmentRuined (EntityAI attachment)
override void EEDelete (EntityAI parent)
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
void Synchronize ()
override void OnVariablesSynchronized ()
override bool IsFireplace ()
bool IsBaseFireplace ()
bool IsBarrelWithHoles ()
bool IsFireplaceIndoor ()
bool IsIndoorOven ()
override bool CanHaveWetness ()
override bool CanHaveTemperature ()
ItemBase GetCookingEquipment ()
void SetCookingEquipment (ItemBase equipment)
void ClearCookingEquipment (ItemBase pItem)
void ClearCookingEquipment ()
DEPRECATED.
bool DirectCookingSlotsInUse ()
bool SmokingSlotsInUse ()
void DestroyFireplace ()
[DEPRECATED]
override bool IsPrepareToDelete ()
override void EECargoOut (EntityAI item)
void RefreshFireplaceVisuals ()
void SetBurntFirewood ()
void RefreshFireplacePhysics ()
void RefreshFireParticlesAndSounds (bool force_refresh)
void StopAllParticlesAndSounds ()
bool CanShowSmoke ()
void RefreshFireState ()
bool PlayParticle (out Particle particle, int particle_type, vector pos, bool worldpos=false)
bool StopParticle (out Particle particle)
void ParticleFireStartStart ()
void ParticleFireStartStop ()
void ParticleSmallFireStart ()
void ParticleSmallFireStop ()
void ParticleNormalFireStart ()
void ParticleNormalFireStop ()
void ParticleSmallSmokeStart ()
void ParticleSmallSmokeStop ()
void ParticleNormalSmokeStart ()
void ParticleNormalSmokeStop ()
void ParticleFireEndStart ()
void ParticleFireEndStop ()
void ParticleFireWindyNoIgniteStart ()
void ParticleSteamExtinguishingStart ()
void ParticleSteamExtinguishingStop ()
void ParticleSteamEndStart ()
void ParticleSteamEndStop ()
void ParticleWetNoIgniteStart ()
void ParticleWetNoIgniteStop ()
bool GetCeilingHeight (out float actual_height)
float GetAirResistanceForSmokeParticles (float actual_height)
vector GetFireEffectPosition ()
vector GetSmokeEffectPosition ()
void SoundFireLightStart ()
void SoundFireHeavyStart ()
void SoundFireNoFireStart ()
void SoundFireExtinguishedStart ()
void SoundFireWetNoIgniteStart ()
void SoundFireExtinguishingStart ()
void SoundFireWindyNoIgniteStart ()
void SoundFireStop ()
void AddToFireConsumables (ItemBase item)
float GetFireConsumableTypeEnergy (ItemBase item)
void RemoveFromFireConsumables (FireConsumable fire_consumable)
FireConsumable GetFireConsumableByItem (ItemBase item)
FireConsumable SetItemToConsume ()
FireConsumable GetItemToConsume ()
void SpendFireConsumable (float amount)
int GetKindlingCount ()
Returns count of all kindling type items (define in 'm_KindlingTypes') attached to fireplace.
int GetFuelCount ()
Returns count of all fuel type items (define in 'm_FuelTypes') attached to fireplace.
bool IsKindling (ItemBase item)
Returns if item attached to fireplace is kindling.
bool IsFuel (ItemBase item)
Returns if item attached to fireplace is fuel.
bool IsItemTypeAttached (typename item_type)
bool IsItemAttachedQuantity (typename item_type, float quantity)
bool HasLastAttachment ()
bool HasLastFuelKindlingAttached ()
bool IsBurning ()
void SetBurningState (bool is_burning)
bool HasAshes ()
void SetAshesState (bool has_ashes)
bool IsOven ()
bool HasStoneCircle ()
bool HasStones ()
int GetAttachedStonesCount ()
void SetOvenState (bool is_oven)
void SetStoneCircleState (bool has_stonecircle)
float GetTemperatureLossMP ()
void SetTemperatureLossMP (float value)
float GetFuelBurnRateMP ()
void SetFuelBurnRateMP (float value)
int GetFireState ()
void SetFireState (FireplaceFireState state)
void SetExtinguishingState ()
void StartFire (bool force_start=false)
void StartHeating ()
void Heating ()
void StopFire (FireplaceFireState fire_state=FireplaceFireState.END_FIRE)
void StopHeating ()
void StartCooling ()
void Cooling ()
void StopCooling ()
void CookWithEquipment ()
Cooking GetCookingProcess ()
void CookOnDirectSlot (ItemBase slot_item, float temp_equip, float temp_ext)
void SmokeOnSmokingSlot (ItemBase slot_item, float temp_equip, float temp_ext)
void BurnItemsInFireplace ()
void AddTemperatureToItemByFire (ItemBase item)
void AddTemperatureToFireplace (float amount)
DEPRECATED.
void AddDamageToItemByFireEx (ItemBase item, bool can_be_ruined, bool pAttachment)
void AddDamageToItemByFire (ItemBase item, bool can_be_ruined)
void AddWetnessToItem (ItemBase item, float amount)
void AddWetnessToFireplace (float amount)
void TransferHeatToNearPlayers ()
DEPRECATED.
void CreateAreaDamage ()
void DestroyAreaDamage ()
bool IsFacingFireplace (PlayerBase player)
DEPRECATED.
bool HasAnyKindling ()
static bool IsWindy ()
bool GetIgniteFailure ()
void SetIgniteFailure (bool failure)
static bool IsEntityWet (notnull EntityAI entity_ai)
bool IsWet ()
bool IsRoofAbove ()
override bool IsOpen ()
bool IsCeilingHighEnoughForSmoke ()
static bool IsRainingAboveEntity (notnull EntityAI entity_ai)
bool IsRainingAbove ()
static bool IsEntityOnWaterSurface (notnull EntityAI entity_ai)
bool IsOnWaterSurface ()
static bool IsEntityOnInteriorSurface (notnull EntityAI entity_ai)
bool IsOnInteriorSurface ()
override bool IsEmpty ()
bool IsCargoEmpty ()
bool HasCookingStand ()
bool IsInAnimPhase (string anim_phase)
bool IsSpaceFor (vector size)
override bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination)
bool CanBuildOven ()
bool IsSpaceForOven ()
bool CanBuildStoneCircle ()
bool IsSpaceForCircle ()
bool CanDismantleOven ()
bool CanDismantleStoneCircle ()
bool CanCookOnStick ()
bool CanExtinguishFire ()
FireplaceLight GetLightEntity ()
void SetLightEntity (FireplaceLight light)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override string GetPlaceSoundset ()
void CalcAndSetTotalEnergy ()
void CalcAndSetQuantity ()
override void OnAttachmentQuantityChanged (ItemBase item)
override bool CanReleaseAttachment (EntityAI attachment)
void LockOvenAttachments (bool lock)
override bool DisassembleOnLastDetach ()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
override void OnDebugSpawn ()
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
override bool OnAction (int action_id, Man player, ParamsReadContext ctx)
Variables
enum FireplaceFireState WIND = 0
enum FireplaceFireState WET = 1
enum FireplaceFireState m_IsBurning = false
bool m_HasAshes = false
bool m_IsOven = false
bool m_HasStoneCircle = false
bool m_RoofAbove = false
bool m_NoIgnite = false
int m_OvenAttachmentsLockState = -1
FireplaceFireState m_FireState = FireplaceFireState.NO_FIRE
FireplaceFireState m_LastFireState = FireplaceFireState.NO_FIRE
vector m_HalfExtents
float m_TemperatureLossMP = 1.0
float m_FuelBurnRateMP = 1.0
determines how fast will the fireplace loose its temperature when cooling (lower is better)
ref Cooking m_CookingProcess
determines how fast will the fuel item burn before spending (lower is better)
const float PARAM_SMALL_FIRE_TEMPERATURE = 150
const float PARAM_NORMAL_FIRE_TEMPERATURE = 1000
maximum fireplace temperature of a small fire (degree Celsius)
const float PARAM_MIN_FIRE_TEMPERATURE = 30
maximum fireplace temperature of a normal fire (degree Celsius)
const float PARAM_TEMPERATURE_INCREASE = 3
minimum fireplace temperature under which the fireplace is inactive (degree Celsius)
const float PARAM_TEMPERATURE_DECREASE = 3
how much will temperature increase when fireplace is burning (degree Celsius per second)
const float PARAM_MAX_WET_TO_IGNITE = 0.2
how much will temperature decrease when fireplace is cooling (degree Celsius per second)
const float PARAM_MIN_TEMP_TO_REIGNITE = 30
maximum wetness value when the fireplace can be ignited
const float PARAM_IGNITE_RAIN_THRESHOLD = 0.1
minimum fireplace temperature under which the fireplace can be reignited using air only (degree Celsius)
const float PARAM_BURN_WET_THRESHOLD = 0.40
maximum rain value when the fireplace can be ignited
const float PARAM_WET_INCREASE_COEF = 0.02
maximum wetness value when the fireplace is able to burn
const float PARAM_WET_HEATING_DECREASE_COEF = 0.01
value for calculating of wetness that fireplace gain when raining
const float PARAM_WET_COOLING_DECREASE_COEF = 0.002
value for calculating wetness loss during heating process
const float PARAM_FIRE_CONSUM_RATE_AMOUNT = 0.5
value for calculating wetness loss during cooling process
const float PARAM_BURN_DAMAGE_COEF = 5.0
base value of fire consumption rate (how many base energy will be spent on each update)
const float PARAM_ITEM_HEAT_TEMP_INCREASE_COEF = 10
value for calculating damage on items located in fireplace cargo
const float PARAM_ITEM_HEAT_MIN_TEMP = 40
value for calculating temperature increase on each heat update interval (degree Celsius)
const float PARAM_MAX_ITEM_HEAT_TEMP_INCREASE = 200
minimum temperature for items that can be heated in fireplace cargo or as attachments (degree Celsius)
const float PARAM_FULL_HEAT_RADIUS = 2.0
maximum value of temperature of items in fireplace when heating (degree Celsius)
const float PARAM_HEAT_RADIUS = 4.0
radius in which objects are fully heated by fire
const float PARAM_HEAT_THROUGH_AIR_COEF = 0.1
radius in which objects are heated by fire
const float PARAM_MAX_TRANSFERED_TEMPERATURE = 25
DEPRECATED value for calculation of heat transfered from fireplace through air to player (environment)
const int MIN_STONES_TO_BUILD_CIRCLE = 8
const int MIN_STONES_TO_BUILD_OVEN = 16
minimum amount of stones for circle
const int MAX_TEMPERATURE_TO_DISMANTLE_OVEN = 40
minimum amount of stones for oven
const float MIN_CEILING_HEIGHT = 5
maximum temperature for dismantling oven
const float TEMPERATURE_LOSS_MP_DEFAULT = 1.0
min height of ceiling for fire to be ignited
const float TEMPERATURE_LOSS_MP_STONES = 0.90
const float TEMPERATURE_LOSS_MP_OVEN = 0.75
const float FUEL_BURN_RATE_DEFAULT = 1.0
const float FUEL_BURN_RATE_STONES = 0.92
const float FUEL_BURN_RATE_OVEN = 0.85
const float PARAM_COOKING_TEMP_THRESHOLD = 100
cooking
const float PARAM_COOKING_EQUIP_MAX_TEMP = 250
temperature threshold for starting coooking process (degree Celsius)
const float PARAM_COOKING_EQUIP_TEMP_INCREASE = 10
maximum temperature of attached cooking equipment (degree Celsius)
const int TIMER_HEATING_UPDATE_INTERVAL = 3
const int TIMER_COOLING_UPDATE_INTERVAL = 2
update interval duration of heating process (seconds)
const int DIRECT_COOKING_SLOT_COUNT = 3
direct cooking slots
const float DIRECT_COOKING_SPEED = 1.5
const int SMOKING_SLOT_COUNT = 4
const float SMOKING_SPEED = 1
const int LIFETIME_FIREPLACE_STONE_CIRCLE = 172800
const int LIFETIME_FIREPLACE_STONE_OVEN = 604800
const float IGNITE_WIND_THRESHOLD = 0.8
ref Timer m_HeatingTimer
ref Timer m_CoolingTimer
FireplaceLight m_Light
float m_LightDistance = 2000
ItemBase m_CookingEquipment
ItemBase m_DirectCookingSlots [DIRECT_COOKING_SLOT_COUNT]
ItemBase m_SmokingSlots [SMOKING_SLOT_COUNT]
ref FireConsumable m_ItemToConsume
int PARTICLE_FIRE_START = ParticleList.CAMP_FIRE_START
int PARTICLE_OVEN_FIRE_START = ParticleList.CAMP_STOVE_FIRE_START
int PARTICLE_SMALL_FIRE = ParticleList.CAMP_SMALL_FIRE
int PARTICLE_NORMAL_FIRE = ParticleList.CAMP_NORMAL_FIRE
int PARTICLE_OVEN_FIRE = ParticleList.CAMP_STOVE_FIRE
int PARTICLE_SMALL_SMOKE = ParticleList.CAMP_SMALL_SMOKE
int PARTICLE_NORMAL_SMOKE = ParticleList.CAMP_NORMAL_SMOKE
int PARTICLE_FIRE_END = ParticleList.CAMP_FIRE_END
int PARTICLE_OVEN_FIRE_END = ParticleList.CAMP_STOVE_FIRE_END
int PARTICLE_STEAM_END = ParticleList.CAMP_STEAM_2END
int PARTICLE_STEAM_EXTINGUISHING = ParticleList.CAMP_STEAM_EXTINGUISH_START
int PARTICLE_NO_IGNITE_WIND = ParticleList.CAMP_NO_IGNITE_WIND
Particle m_ParticleFireStart
Particle m_ParticleSmallFire
Particle m_ParticleNormalFire
Particle m_ParticleSmallSmoke
Particle m_ParticleNormalSmoke
Particle m_ParticleFireEnd
Particle m_ParticleSteamEnd
Particle m_ParticleSteamExtinguishing
const string SOUND_FIRE_HEAVY = "HeavyFire_SoundSet"
const string SOUND_FIRE_LIGHT = "LightFire_SoundSet"
const string SOUND_FIRE_NO_FIRE = "NoFuelFire_SoundSet"
const string SOUND_FIRE_EXTINGUISHING = "ExtinguishByWater_SoundSet"
const string SOUND_FIRE_EXTINGUISHED = "ExtinguishByWaterEnd_SoundSet"
EffectSound m_SoundFireLoop
EffectSound m_SoundFire
static ref map< typename, ref FireConsumableType > m_FireConsumableTypes
ref map< ItemBase, ref FireConsumable > m_FireConsumables
const string MESSAGE_IGNITE_IGNIT_ITEM_DAMAGED = "You cannot start fire. Fireplace is ruined."
const string MESSAGE_IGNITE_NO_KINDLING = "There needs to be some kindling to start a fire."
const string MESSAGE_IGNITE_TOO_WET = "The fireplace is too wet to be ignited."
const string MESSAGE_IGNITE_RAIN = "The fire went out because of the rain."
const string MESSAGE_IGNITE_WIND = "The fire went out because of the wind."
const string MESSAGE_IGNITE_IN_WATER = "I cannot ignite the fireplace in the water."
const string MESSAGE_IGNITE_UNDER_LOW_ROOF = "I cannot ignite the fireplace here, the is not enough room."
const string MESSAGE_REIGNITE_NO_KINDLING = "There needs to be some kindling to start a fire."
const string MESSAGE_REIGNITE_RAIN = "Cannot reignite fireplace in rain."
const string MESSAGE_REIGNITE_TOO_WET = "The fireplace is too wet to be reignited."
const string MESSAGE_BURY_ASHES_FAILED_NOT_EMPTY = "Cannot bury ashes. There are sill items in it."
const string MESSAGE_BURY_ASHES_FAILED_SURFACE = "Cannot bury ashes on hard surface."
const string MESSAGE_BURY_ASHES_FAILED_BURNING = "Cannot bury ashes, the fireplace is still burning."
const string MESSAGE_BURY_ASHES_FAILED_TOO_HOT = "Cannot bury ashes, the fireplace is too hot."
const string MESSAGE_CANNOT_BUILD_OVEN = "Cannot build oven."
const string MESSAGE_CANNOT_DISMANTLE_OVEN = "Cannot dismantle oven."
const string ANIMATION_ASHES = "Ashes"
const string ANIMATION_KINDLING = "Kindling"
const string ANIMATION_STICKS = "Sticks"
const string ANIMATION_WOOD = "Wood"
const string ANIMATION_BURNT_WOOD = "BurntWood"
const string ANIMATION_STONE = "Stone"
const string ANIMATION_STONES = "StonesCircle"
const string ANIMATION_TRIPOD = "Tripod"
const string ANIMATION_OVEN = "Oven"
const string ANIMATION_INVENTORY = "Inventory"
const string ANIMATION_COOKWARE_HANDLE = "handleRotate"
const string ANIMATION_CAULDRON_HANDLE = "handle1Rotate"
const string MATERIAL_FIREPLACE_GLOW = "dz\\gear\\cooking\\data\\stoneground.rvmat"
const string MATERIAL_FIREPLACE_NOGLOW = "dz\\gear\\cooking\\data\\stonegroundnoemit.rvmat"
ATTACHMENT_STICKS = WoodenStick
ATTACHMENT_FIREWOOD = Firewood
ATTACHMENT_RAGS = Rag
ATTACHMENT_BANDAGE = BandageDressing
ATTACHMENT_BOOK = ItemBook
ATTACHMENT_BARK_OAK = Bark_Oak
ATTACHMENT_BARK_BIRCH = Bark_Birch
ATTACHMENT_PAPER = Paper
ATTACHMENT_GIFTWRAP = GiftWrapPaper
ATTACHMENT_PUNCHEDCARD = PunchedCard
ATTACHMENT_EYEMASK_COLORBASE = EyeMask_ColorBase
ATTACHMENT_TRIPOD = Tripod
ATTACHMENT_COOKINGSTAND = CookingStand
ATTACHMENT_STONES = Stone
ATTACHMENT_COOKING_POT = Pot
ATTACHMENT_FRYING_PAN = FryingPan
ATTACHMENT_CAULDRON = Cauldron
const string OBJECT_CLUTTER_CUTTER = "ClutterCutterFireplace"
Object m_ClutterCutter
ref AreaDamageManager m_AreaDamage
float m_TotalEnergy
ref NoiseParams m_NoisePar
bool m_CanNoise = true
ref UniversalTemperatureSource m_UTSource
ref UniversalTemperatureSourceSettings m_UTSSettings
ref UniversalTemperatureSourceLambdaFireplace m_UTSLFireplace
Enumeration Type Documentation
FireplaceFireState
enum FireplaceFireState
Enumerator
NO_FIRE
START_FIRE
SMALL_FIRE
NORMAL_FIRE
END_FIRE
EXTINGUISHING_FIRE
EXTINGUISHED_FIRE
REIGNITED_FIRE
COUNT
Definition at line 1 of file FireplaceBase.c.
{
  NO_FIRE = 1,
  START_FIRE = 2,
  SMALL_FIRE = 3,
  NORMAL_FIRE = 4,
  END_FIRE = 5,
  EXTINGUISHING_FIRE = 6,
  EXTINGUISHED_FIRE = 7,
  REIGNITED_FIRE = 8,
  COUNT = 9 //for net sync purposes
}
Function Documentation
AddDamageToItemByFire()
void AddDamageToItemByFire (ItemBase item, bool can_be_ruined) protected
Definition at line 2140 of file FireplaceBase.c.
  {
    item.DecreaseHealth(PARAM_BURN_DAMAGE_COEF, false);
    if (item.CanBeCooked() & item.GetHealthLevel() >= GameConstants.STATE_BADLY_DAMAGED)
    {
      Edible_Base edible_item = Edible_Base.Cast(item);
      edible_item.ChangeFoodStage(FoodStageType.BURNED);
    }
  }
References PARAM_BURN_DAMAGE_COEF, and GameConstants::STATE_BADLY_DAMAGED.
AddDamageToItemByFireEx()
void AddDamageToItemByFireEx (ItemBase item, bool can_be_ruined, bool pAttachment) protected
fireplace cargo only
cargo item attachments
fuel & kindling
cookable
Definition at line 2083 of file FireplaceBase.c.
  {
    if (!item)
      return;
    if (GetTemperature() <= PARAM_ITEM_HEAT_MIN_TEMP)
      return;
    if (!pAttachment)
    {
      GameInventory itemInventory = item.GetInventory();
      if (itemInventory)
      {
        for (int i = 0; i < itemInventory.AttachmentCount(); ++i)
          itemInventory.GetAttachmentFromIndex(i).AddHealth("", "", -PARAM_BURN_DAMAGE_COEF);
      }
      item.AddHealth("", "", -PARAM_BURN_DAMAGE_COEF);
    }
    else
    {
      float timerCoef = 1.0;
      if (m_HeatingTimer && m_HeatingTimer.IsRunning())
        timerCoef = TIMER_HEATING_UPDATE_INTERVAL;
      else if (m_CoolingTimer && m_CoolingTimer.IsRunning())
        timerCoef = TIMER_COOLING_UPDATE_INTERVAL;
      switch (item.Type())
      {
      case ATTACHMENT_TRIPOD:
      case ATTACHMENT_COOKINGSTAND:
      case ATTACHMENT_COOKING_POT:
      case ATTACHMENT_CAULDRON:
      case ATTACHMENT_FRYING_PAN:
        item.DecreaseHealth(GameConstants.FIRE_ATTACHMENT_DAMAGE_PER_SECOND * timerCoef, false);
        break;
      }
      if (IsFuel(item) || IsKindling(item))
      {
        if (item.GetHealthLevel() < GameConstants.STATE_BADLY_DAMAGED)
          item.DecreaseHealth(PARAM_BURN_DAMAGE_COEF, false);
      }
      if (item.CanBeCooked() && item.GetHealthLevel() >= GameConstants.STATE_BADLY_DAMAGED)
      {
        Edible_Base edible_item = Edible_Base.Cast(item);
        edible_item.ChangeFoodStage(FoodStageType.BURNED);
      }
    }
  }
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_COOKINGSTAND, ATTACHMENT_FRYING_PAN, ATTACHMENT_TRIPOD, GameConstants::FIRE_ATTACHMENT_DAMAGE_PER_SECOND, GetTemperature(), IsFuel(), IsKindling(), m_CoolingTimer, m_HeatingTimer, PARAM_BURN_DAMAGE_COEF, PARAM_ITEM_HEAT_MIN_TEMP, GameConstants::STATE_BADLY_DAMAGED, TIMER_COOLING_UPDATE_INTERVAL, and TIMER_HEATING_UPDATE_INTERVAL.
Referenced by BurnItemsInFireplace().
AddTemperatureToFireplace()
void AddTemperatureToFireplace (float amount) protected
DEPRECATED.
Definition at line 2080 of file FireplaceBase.c.
{};
AddTemperatureToItemByFire()
void AddTemperatureToItemByFire (ItemBase item) protected
Definition at line 2069 of file FireplaceBase.c.
  {
    if (item.GetTemperatureMax() >= PARAM_ITEM_HEAT_MIN_TEMP)
    {
      float temperature = item.GetTemperature() + PARAM_ITEM_HEAT_TEMP_INCREASE_COEF;
      temperature = Math.Clamp(temperature, PARAM_ITEM_HEAT_MIN_TEMP, PARAM_MAX_ITEM_HEAT_TEMP_INCREASE);
      item.SetTemperature(temperature);
    }
  }
References Math::Clamp(), PARAM_ITEM_HEAT_MIN_TEMP, PARAM_ITEM_HEAT_TEMP_INCREASE_COEF, and PARAM_MAX_ITEM_HEAT_TEMP_INCREASE.
Referenced by BurnItemsInFireplace().
AddToFireConsumables()
void AddToFireConsumables (ItemBase item) protected
Definition at line 1259 of file FireplaceBase.c.
  {
    m_FireConsumables.Insert(item, new FireConsumable(item, GetFireConsumableTypeEnergy(item)));
    CalcAndSetQuantity();
  }
References CalcAndSetQuantity(), GetFireConsumableTypeEnergy(), and m_FireConsumables.
Referenced by FireplaceBase::EEItemAttached().
AddWetnessToFireplace()
void AddWetnessToFireplace (float amount) protected
Definition at line 2161 of file FireplaceBase.c.
  {
    //add wetness
    float wetness = GetWet();
    wetness = wetness + amount;
    wetness = Math.Clamp(wetness, 0, 1); //wetness <0-1>
    SetWet(wetness);
    //decrease temperature
    if (amount > 0)
    {
      float temperature = GetTemperature();
      temperature = temperature * (1 - (wetness * 0.5));
      temperature = Math.Clamp(temperature, PARAM_MIN_FIRE_TEMPERATURE, PARAM_NORMAL_FIRE_TEMPERATURE);
      // temperature via UniversalTemperatureSource
      m_UTSLFireplace.SetFuelCount(GetFuelCount());
      m_UTSLFireplace.SetCurrentTemperature(temperature);
    }
  }
References Math::Clamp(), GetFuelCount(), GetTemperature(), GetWet(), m_UTSLFireplace, PARAM_MIN_FIRE_TEMPERATURE, PARAM_NORMAL_FIRE_TEMPERATURE, and SetWet().
Referenced by Cooling(), and Heating().
AddWetnessToItem()
void AddWetnessToItem (ItemBase item, float amount) protected
Definition at line 2152 of file FireplaceBase.c.
  {
    float wetness = item.GetWet();
    wetness = wetness + amount;
    wetness = Math.Clamp(wetness, 0, 1); //wetness <0-1>
    item.SetWet(wetness);
  }
References Math::Clamp().
Referenced by BurnItemsInFireplace().
AfterStoreLoad()
override void AfterStoreLoad () protected
Definition at line 436 of file FireplaceBase.c.
  {
    super.AfterStoreLoad();
    Synchronize();
    //start fire
    if (IsBurning())
    {
      if (GetGame() && GetGame().IsServer())
      {
        StartFire(true); //will be auto-synchronized when starting fire
      }
    }
  }
References GetGame(), IsBurning(), StartFire(), and Synchronize().
BurnItemsInFireplace()
void BurnItemsInFireplace () protected
cargo
attachments
Definition at line 2031 of file FireplaceBase.c.
  {
    CargoBase cargo = GetInventory().GetCargo();
    for (int i = 0; i < cargo.GetItemCount(); i++)
    {
      ItemBase item = ItemBase.Cast(cargo.GetItem(i));
      //set damage
      AddDamageToItemByFireEx(item, false, false);
      if (item.GetHealth("", "Health") <= 0 && !item.IsKindOf("Grenade_Base"))
        item.Delete();
      //add temperature
      AddTemperatureToItemByFire(item);
      //remove wetness
      AddWetnessToItem(item, -PARAM_WET_HEATING_DECREASE_COEF);
    }
    for (int j = 0; j < GetInventory().AttachmentCount(); ++j)
    {
      ItemBase attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(j));
      //set damage
      AddDamageToItemByFireEx(attachment, false, true);
      //add temperature
      AddTemperatureToItemByFire(attachment);
      //remove wetness
      AddWetnessToItem(attachment, -PARAM_WET_HEATING_DECREASE_COEF);
    }
  }
References AddDamageToItemByFireEx(), AddTemperatureToItemByFire(), AddWetnessToItem(), and PARAM_WET_HEATING_DECREASE_COEF.
Referenced by Cooling(), and Heating().
CalcAndSetQuantity()
void CalcAndSetQuantity () protected
Definition at line 2478 of file FireplaceBase.c.
  {
    if (GetGame() && GetGame().IsServer())
    {
      float remainingEnergy;
      foreach (FireConsumable fireConsumable : m_FireConsumables)
      {
        float quantity = fireConsumable.GetItem().GetQuantity();
        if (quantity > 0)
        {
          remainingEnergy += ((quantity - 1) * fireConsumable.GetEnergy()) + fireConsumable.GetRemainingEnergy();
          //Print( fireConsumable.GetItem().GetType() + " remaining energy = " + ( ( ( quantity - 1 ) * fire_consumable.GetEnergy() ) + fire_consumable.GetRemainingEnergy() ).ToString() );
        }
        else
        {
          remainingEnergy += fireConsumable.GetRemainingEnergy();
          //Print( fireConsumable.GetItem().GetType() + " remaining energy = " + ( fireConsumable.GetRemainingEnergy().ToString() ) );
        }
      }
      SetQuantity(remainingEnergy / m_TotalEnergy * GetQuantityMax());
    }
  }
References GetGame(), GetQuantityMax(), m_FireConsumables, m_TotalEnergy, and SetQuantity().
Referenced by AddToFireConsumables(), CAContinuousEmpty::Cancel(), CAContinuousEmptyMagazine::Cancel(), CAContinuousFill::Cancel(), CAContinuousFillBrakes::Cancel(), CAContinuousFillCoolant::Cancel(), CAContinuousFillFuel::Cancel(), CAContinuousFillOil::Cancel(), CAContinuousQuantity::Cancel(), CAContinuousQuantityLiquidTransfer::Cancel(), CAContinuousQuantityRepeat::Cancel(), CAContinuousTransferQuantity::Cancel(), CAContinuousDisinfectPlant::Execute(), CAContinuousEmpty::Execute(), CAContinuousEmptyMagazine::Execute(), CAContinuousFertilizeGardenSlot::Execute(), CAContinuousFill::Execute(), CAContinuousFillBrakes::Execute(), CAContinuousFillCoolant::Execute(), CAContinuousFillFuel::Execute(), CAContinuousFillOil::Execute(), CAContinuousFillPowerGenerator::Execute(), CAContinuousQuantity::Execute(), CAContinuousQuantityLiquidTransfer::Execute(), CAContinuousQuantityRepeat::Execute(), CAContinuousTransferQuantity::Execute(), CAContinuousWaterPlant::Execute(), CAContinuousWaterSlot::Execute(), CASingleUseQuantity::Execute(), OnAttachmentQuantityChanged(), RemoveFromFireConsumables(), and SpendFireConsumable().
CalcAndSetTotalEnergy()
void CalcAndSetTotalEnergy () protected
Definition at line 2447 of file FireplaceBase.c.
  {
    if (GetGame() && GetGame().IsServer())
    {
      m_TotalEnergy = 0;
      foreach (FireConsumableType fireConsumableType : m_FireConsumableTypes)
      {
        string quantityConfigPath = string.Format("CfgVehicles %1 varQuantityMax", fireConsumableType.GetItemType().ToString());
        string stackMaxConfigPath = string.Format("CfgSlots Slot_%1 stackMax", fireConsumableType.GetAttSlot());
        if (GetGame().ConfigIsExisting(quantityConfigPath))
          float quantityMax = GetGame().ConfigGetFloat(quantityConfigPath);
        if (GetGame().ConfigIsExisting(stackMaxConfigPath))
          float stackMax = GetGame().ConfigGetFloat(stackMaxConfigPath);
        //debug
        //Print( fireConsumableType.GetItemType().ToString() + " quantityMax = " + quantityMax.ToString() + " [" + (quantity_max*fire_consumable_type.GetEnergy()).ToString()  + "] | stack_max = " + stack_max.ToString() + " [" + (stack_max*fire_consumable_type.GetEnergy()).ToString() + "]" );
        if (stackMax > 0)
          m_TotalEnergy += stackMax * fireConsumableType.GetEnergy();
        else
          m_TotalEnergy += quantityMax * fireConsumableType.GetEnergy();
      }
      //debug
      //Print( "Total energy = " + m_TotalEnergy.ToString() );
    }
  }
References GetGame(), m_FireConsumableTypes, m_TotalEnergy, and quantityMax.
Referenced by FireplaceBase().
CanBuildOven()
bool CanBuildOven () protected
Definition at line 2365 of file FireplaceBase.c.
  {
    return !IsOven() && !IsBurning() && (GetAttachedStonesCount() >= MIN_STONES_TO_BUILD_OVEN) && !FindAttachmentBySlotName("CookingTripod") && !HasStoneCircle() && IsSpaceForOven();
  }
References GetAttachedStonesCount(), HasStoneCircle(), IsBurning(), IsOven(), IsSpaceForOven(), and MIN_STONES_TO_BUILD_OVEN.
CanBuildStoneCircle()
bool CanBuildStoneCircle () protected
Definition at line 2377 of file FireplaceBase.c.
  {
    return !HasStoneCircle() && !IsOven() && !IsBurning() && (GetAttachedStonesCount() >= MIN_STONES_TO_BUILD_CIRCLE) && IsSpaceForCircle();
  }
References GetAttachedStonesCount(), HasStoneCircle(), IsBurning(), IsOven(), IsSpaceForCircle(), and MIN_STONES_TO_BUILD_CIRCLE.
CanCookOnStick()
bool CanCookOnStick () protected
Definition at line 2398 of file FireplaceBase.c.
  {
    return (GetTemperature() >= PARAM_COOKING_TEMP_THRESHOLD);
  }
References GetTemperature(), and PARAM_COOKING_TEMP_THRESHOLD.
CanDismantleOven()
bool CanDismantleOven () protected
Definition at line 2388 of file FireplaceBase.c.
  {
    return (IsOven() && !IsBurning() && !DirectCookingSlotsInUse() && !SmokingSlotsInUse() && GetTemperature() <= MAX_TEMPERATURE_TO_DISMANTLE_OVEN);
  }
References DirectCookingSlotsInUse(), GetTemperature(), IsBurning(), IsOven(), MAX_TEMPERATURE_TO_DISMANTLE_OVEN, and SmokingSlotsInUse().
CanDismantleStoneCircle()
bool CanDismantleStoneCircle () protected
Definition at line 2393 of file FireplaceBase.c.
  {
    return (HasStoneCircle() && !IsOven() && !IsBurning());
  }
References HasStoneCircle(), IsBurning(), and IsOven().
CanExtinguishFire()
bool CanExtinguishFire () protected
Definition at line 2404 of file FireplaceBase.c.
  {
    return IsBurning();
  }
References IsBurning().
CanHaveTemperature()
override bool CanHaveTemperature () protected
Definition at line 524 of file FireplaceBase.c.
  {
    return true;
  }
CanHaveWetness()
override bool CanHaveWetness () protected
Definition at line 519 of file FireplaceBase.c.
  {
    return true;
  }
CanReleaseAttachment()
override bool CanReleaseAttachment (EntityAI attachment) protected
Definition at line 2510 of file FireplaceBase.c.
  {
    if (!super.CanReleaseAttachment(attachment))
      return false;
    ItemBase item = ItemBase.Cast(attachment);
    if (IsKindling(item) || IsFuel(item))
      return !IsBurning();
    return true;
  }
References IsBurning(), IsFuel(), and IsKindling().
CanShowSmoke()
bool CanShowSmoke () protected
Definition at line 959 of file FireplaceBase.c.
  {
    return true;
  }
CanSwapEntities()
override bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination) protected
Definition at line 2357 of file FireplaceBase.c.
  {
    if (!otherDestination || otherDestination.GetParent() == this)
      return false;
    return true;
  }
ClearCookingEquipment() [1/2]
void ClearCookingEquipment () protected
DEPRECATED.
Definition at line 549 of file FireplaceBase.c.
  {
    SetCookingEquipment(null);
  }
References FireplaceBase::SetCookingEquipment().
Referenced by FireplaceBase::EEItemDetached(), and ItemBase::EEItemDetached().
ClearCookingEquipment() [2/2]
void ClearCookingEquipment (ItemBase pItem) protected
Definition at line 540 of file FireplaceBase.c.
  {
    if (m_CookingProcess)
      m_CookingProcess.TerminateCookingSounds(pItem);
    SetCookingEquipment(null);
  }
References m_CookingProcess, and FireplaceBase::SetCookingEquipment().
CookOnDirectSlot()
void CookOnDirectSlot (ItemBase slot_item, float temp_equip, float temp_ext) protected
Definition at line 1994 of file FireplaceBase.c.
  {
    if (m_CookingProcess == null)
      m_CookingProcess = new Cooking();
    m_CookingProcess.CookWithEquipment(slot_item);
    switch (slot_item.Type())
    {
    case ATTACHMENT_CAULDRON:
    case ATTACHMENT_COOKING_POT:
    case ATTACHMENT_FRYING_PAN:
      float cookEquipTemp = temp_equip + PARAM_COOKING_EQUIP_TEMP_INCREASE;
      if (temp_ext <= PARAM_SMALL_FIRE_TEMPERATURE)
        cookEquipTemp = Math.Clamp(cookEquipTemp, PARAM_ITEM_HEAT_MIN_TEMP, PARAM_SMALL_FIRE_TEMPERATURE);
      else
        cookEquipTemp = Math.Clamp(cookEquipTemp, PARAM_ITEM_HEAT_MIN_TEMP, PARAM_COOKING_EQUIP_MAX_TEMP);
      slot_item.SetTemperature(cookEquipTemp);
      break;
    }
  }
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, Math::Clamp(), m_CookingProcess, PARAM_COOKING_EQUIP_MAX_TEMP, PARAM_COOKING_EQUIP_TEMP_INCREASE, PARAM_ITEM_HEAT_MIN_TEMP, and PARAM_SMALL_FIRE_TEMPERATURE.
Referenced by Cooling(), and Heating().
CookWithEquipment()
void CookWithEquipment () protected
Definition at line 1978 of file FireplaceBase.c.
  {
    if (m_CookingProcess == null)
      m_CookingProcess = new Cooking();
    m_CookingProcess.CookWithEquipment(m_CookingEquipment);
  }
References m_CookingEquipment, and m_CookingProcess.
Referenced by Cooling(), Heating(), and ItemBase::OnWork().
Cooling()
void Cooling () protected
Definition at line 1844 of file FireplaceBase.c.
  {
    float wetness = GetWet();
    float temperature = GetTemperature();
    float temperature_modifier = 0;
    if (!IsBurning() && temperature >= 10)
    {
      //check wetness
      //set wetness if raining and alter temperature modifier (which will lower temperature increase because of rain)
      float rain = GetGame().GetWeather().GetRain().GetActual();
      if (IsRainingAbove() && !IsRoofAbove())
      {
        //set wet to fireplace
        AddWetnessToFireplace(PARAM_WET_INCREASE_COEF * rain);
        //set temperature modifier
        temperature_modifier = temperature_modifier + (PARAM_TEMPERATURE_DECREASE * rain);
      }
      else //subtract wetness
        AddWetnessToFireplace(-PARAM_WET_COOLING_DECREASE_COEF);
      //calculate already obtained wetness (e.g. extinguished by water)
      temperature_modifier = temperature_modifier + (PARAM_TEMPERATURE_DECREASE * wetness);
      // temperature via UniversalTemperatureSource
      m_UTSLFireplace.SetFuelCount(GetFuelCount());
      temperature = GetTemperature() - (PARAM_TEMPERATURE_DECREASE * TIMER_COOLING_UPDATE_INTERVAL) - temperature_modifier;
      m_UTSLFireplace.SetCurrentTemperature(temperature);
      m_UTSource.Update(m_UTSSettings, m_UTSLFireplace);
      //damage cargo items
      BurnItemsInFireplace();
      //cook with equipment if temperature of equipment is still high
      if (m_CookingEquipment)
      {
        float cook_equip_temp = m_CookingEquipment.GetTemperature();
        if (cook_equip_temp >= PARAM_COOKING_TEMP_THRESHOLD)
        {
          //cook
          CookWithEquipment();
        }
      }
      float cook_item_temp;
      int i;
      // manage cooking on direct cooking slots
      if (DirectCookingSlotsInUse())
      {
        for (i = 0; i < DIRECT_COOKING_SLOT_COUNT; i++)
        {
          if (m_DirectCookingSlots[i])
          {
            cook_item_temp = m_DirectCookingSlots[i].GetTemperature();
            if (cook_item_temp >= PARAM_COOKING_TEMP_THRESHOLD)
              CookOnDirectSlot(m_DirectCookingSlots[i], cook_item_temp, temperature);
          }
        }
      }
      // manage smoking slots
      if (SmokingSlotsInUse())
      {
        for (i = 0; i < SMOKING_SLOT_COUNT; i++)
        {
          if (m_SmokingSlots[i])
            SmokeOnSmokingSlot(m_SmokingSlots[i], cook_item_temp, temperature);
        }
      }
      //Debug
      //PlayerBase player = ( PlayerBase ) GetGame().GetPlayer();
      //if (player != NULL) {player.MessageAction ( temperature.ToString() );}
    }
    else
    {
      //stop cooling
      if (Math.AbsFloat(temperature) < 10)
      {
        StopCooling();
        m_UTSource.SetActive(false);
      }
    }
  }
References Math::AbsFloat(), AddWetnessToFireplace(), BurnItemsInFireplace(), CookOnDirectSlot(), CookWithEquipment(), DIRECT_COOKING_SLOT_COUNT, DirectCookingSlotsInUse(), GetFuelCount(), GetGame(), GetTemperature(), GetWet(), IsBurning(), IsRainingAbove(), IsRoofAbove(), m_CookingEquipment, m_DirectCookingSlots, m_SmokingSlots, m_UTSLFireplace, m_UTSource, m_UTSSettings, PARAM_COOKING_TEMP_THRESHOLD, PARAM_TEMPERATURE_DECREASE, PARAM_WET_COOLING_DECREASE_COEF, PARAM_WET_INCREASE_COEF, SmokeOnSmokingSlot(), SMOKING_SLOT_COUNT, SmokingSlotsInUse(), StopCooling(), and TIMER_COOLING_UPDATE_INTERVAL.
CreateAreaDamage()
void CreateAreaDamage () protected
Definition at line 2185 of file FireplaceBase.c.
  {
    //destroy area damage if some already exists
    DestroyAreaDamage();
    //create new area damage
    m_AreaDamage = new AreaDamageLoopedDeferred(this);
    m_AreaDamage.SetDamageComponentType(AreaDamageComponentTypes.HITZONE);
    m_AreaDamage.SetExtents("-0.30 0 -0.30", "0.30 0.75 0.30");
    m_AreaDamage.SetLoopInterval(0.5);
    m_AreaDamage.SetDeferDuration(0.5);
    m_AreaDamage.SetHitZones({ "Head", "Torso", "LeftHand", "LeftLeg", "LeftFoot", "RightHand", "RightLeg", "RightFoot" });
    m_AreaDamage.SetAmmoName("FireDamage");
    m_AreaDamage.Spawn();
  }
References DestroyAreaDamage(), AreaDamageComponentTypes::HITZONE, and m_AreaDamage.
Referenced by ItemBase::UpdateAttachmentVisuals().
DestroyAreaDamage()
void DestroyAreaDamage () protected
Definition at line 2201 of file FireplaceBase.c.
  {
    if (m_AreaDamage)
      m_AreaDamage.Destroy();
  }
References m_AreaDamage.
Referenced by CreateAreaDamage(), FireplaceBase::CreateAreaDamage(), ItemBase::CreateAreaDamage(), OnVariablesSynchronized(), StopCooling(), ItemBase::UpdateAttachmentVisuals(), BaseBuildingBase::UpdateBarbedWireAreaDamagePos(), and ~FireplaceBase().
DestroyFireplace()
void DestroyFireplace () protected
[DEPRECATED]
Definition at line 575 of file FireplaceBase.c.
  {
    DeleteSafe();
  }
DirectCookingSlotsInUse()
bool DirectCookingSlotsInUse () protected
Definition at line 554 of file FireplaceBase.c.
  {
    for (int i = 0; i < DIRECT_COOKING_SLOT_COUNT; i++)
    {
      if (m_DirectCookingSlots[i])
        return true;
    }
    return false;
  }
References DIRECT_COOKING_SLOT_COUNT, and m_DirectCookingSlots.
Referenced by CanDismantleOven(), FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), Cooling(), Heating(), and StopCooling().
DisassembleOnLastDetach()
override bool DisassembleOnLastDetach () protected
Definition at line 2555 of file FireplaceBase.c.
  {
    return true;
  }
EECargoOut()
override void EECargoOut (EntityAI item) protected
Definition at line 585 of file FireplaceBase.c.
  {
    super.EECargoOut(item);
    CheckForDestroy();
  }
EEDelete()
override void EEDelete (EntityAI parent) protected
Definition at line 368 of file FireplaceBase.c.
  {
    super.EEDelete(parent);
    SetFireState(FireplaceFireState.NO_FIRE);
    // cleanup particles (for cases of leaving burning fplace and going back outside of network bubble)
#ifndef SERVER
    StopAllParticlesAndSounds();
#endif
  }
References SetFireState(), and StopAllParticlesAndSounds().
EEInit()
override void EEInit () protected
Definition at line 285 of file FireplaceBase.c.
  {
    super.EEInit();
    //refresh visual on init
    RefreshFireplaceVisuals();
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      m_UTSSettings = new UniversalTemperatureSourceSettings();
      m_UTSSettings.m_AffectStat = true;
      m_UTSSettings.m_ManualUpdate = true;
      m_UTSSettings.m_TemperatureMin = 0;
      m_UTSSettings.m_TemperatureMax = PARAM_NORMAL_FIRE_TEMPERATURE;
      m_UTSSettings.m_TemperatureCap = PARAM_MAX_TRANSFERED_TEMPERATURE;
      m_UTSSettings.m_RangeFull = PARAM_FULL_HEAT_RADIUS;
      m_UTSSettings.m_RangeMax = PARAM_HEAT_RADIUS;
      m_UTSLFireplace = new UniversalTemperatureSourceLambdaFireplace();
      m_UTSLFireplace.SetSmallFireplaceTemperatureMax(PARAM_SMALL_FIRE_TEMPERATURE);
      m_UTSLFireplace.SetNormalFireplaceTemperatureMax(PARAM_NORMAL_FIRE_TEMPERATURE);
      m_UTSource = new UniversalTemperatureSource(this, m_UTSSettings, m_UTSLFireplace);
    }
  }
References GetGame(), m_UTSLFireplace, m_UTSource, m_UTSSettings, PARAM_FULL_HEAT_RADIUS, PARAM_HEAT_RADIUS, PARAM_MAX_TRANSFERED_TEMPERATURE, PARAM_NORMAL_FIRE_TEMPERATURE, PARAM_SMALL_FIRE_TEMPERATURE, and RefreshFireplaceVisuals().
EEItemAttached()
override void EEItemAttached (EntityAI item, string slot_name) protected
Definition at line 311 of file FireplaceBase.c.
  {
    super.EEItemAttached(item, slot_name);
    //cookware
    switch (item.Type())
    {
    case ATTACHMENT_CAULDRON:
    case ATTACHMENT_COOKING_POT:
    case ATTACHMENT_FRYING_PAN:
      SetCookingEquipment(ItemBase.Cast(item));
      break;
    }
  }
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, and FireplaceBase::SetCookingEquipment().
FireplaceBase()
void FireplaceBase () protected
Definition at line 232 of file FireplaceBase.c.
  {
    //STATIC: define kindling types
    if (!m_FireConsumableTypes)
    {
      m_FireConsumableTypes = new ref map<typename, ref FireConsumableType>();
      m_FireConsumableTypes.Insert(ATTACHMENT_RAGS, new FireConsumableType(ATTACHMENT_RAGS, 14, true, "Rags"));
      m_FireConsumableTypes.Insert(ATTACHMENT_BANDAGE, new FireConsumableType(ATTACHMENT_BANDAGE, 14, true, "MedicalBandage"));
      m_FireConsumableTypes.Insert(ATTACHMENT_BOOK, new FireConsumableType(ATTACHMENT_BOOK, 36, true, "Book"));
      m_FireConsumableTypes.Insert(ATTACHMENT_BARK_OAK, new FireConsumableType(ATTACHMENT_BARK_OAK, 20, true, "OakBark"));
      m_FireConsumableTypes.Insert(ATTACHMENT_BARK_BIRCH, new FireConsumableType(ATTACHMENT_BARK_BIRCH, 14, true, "BirchBark"));
      m_FireConsumableTypes.Insert(ATTACHMENT_PAPER, new FireConsumableType(ATTACHMENT_PAPER, 10, true, "Paper"));
      m_FireConsumableTypes.Insert(ATTACHMENT_GIFTWRAP, new FireConsumableType(ATTACHMENT_GIFTWRAP, 10, true, "GiftWrapPaper"));
      m_FireConsumableTypes.Insert(ATTACHMENT_PUNCHEDCARD, new FireConsumableType(ATTACHMENT_PUNCHEDCARD, 10, true, "PunchedCard"));
      m_FireConsumableTypes.Insert(ATTACHMENT_EYEMASK_COLORBASE, new FireConsumableType(ATTACHMENT_EYEMASK_COLORBASE, 10, true, "EyeMask_ColorBase"));
      //define fuel types
      m_FireConsumableTypes.Insert(ATTACHMENT_STICKS, new FireConsumableType(ATTACHMENT_STICKS, 40, false, "WoodenStick"));
      m_FireConsumableTypes.Insert(ATTACHMENT_FIREWOOD, new FireConsumableType(ATTACHMENT_FIREWOOD, 100, false, "Firewood"));
    }
    //calculate total energy
    CalcAndSetTotalEnergy();
    //define fuel / kindling items (fire consumables)
    m_FireConsumables = new ref map<ItemBase, ref FireConsumable>;
    //default burning parameters
    SetTemperatureLossMP(TEMPERATURE_LOSS_MP_DEFAULT);
    SetFuelBurnRateMP(FUEL_BURN_RATE_DEFAULT);
    //synchronized variables
    RegisterNetSyncVariableBool("m_IsBurning");
    RegisterNetSyncVariableBool("m_HasAshes");
    RegisterNetSyncVariableBool("m_IsOven");
    RegisterNetSyncVariableBool("m_HasStoneCircle");
    RegisterNetSyncVariableBool("m_RoofAbove");
    RegisterNetSyncVariableInt("m_FireState", FireplaceFireState.NO_FIRE, FireplaceFireState.COUNT);
    RegisterNetSyncVariableBool("m_IsSoundSynchRemote");
    RegisterNetSyncVariableBool("m_IsPlaceSound");
    RegisterNetSyncVariableBool("m_NoIgnite");
    m_HalfExtents = vector.Zero;
  }
References ATTACHMENT_BANDAGE, ATTACHMENT_BARK_BIRCH, ATTACHMENT_BARK_OAK, ATTACHMENT_BOOK, ATTACHMENT_EYEMASK_COLORBASE, ATTACHMENT_FIREWOOD, ATTACHMENT_GIFTWRAP, ATTACHMENT_PAPER, ATTACHMENT_PUNCHEDCARD, ATTACHMENT_RAGS, ATTACHMENT_STICKS, CalcAndSetTotalEnergy(), FUEL_BURN_RATE_DEFAULT, m_FireConsumables, m_FireConsumableTypes, m_HalfExtents, SetFuelBurnRateMP(), SetTemperatureLossMP(), TEMPERATURE_LOSS_MP_DEFAULT, and vector::Zero.
GetAirResistanceForSmokeParticles()
float GetAirResistanceForSmokeParticles (float actual_height) protected
Definition at line 1186 of file FireplaceBase.c.
  {
    float air_res;
    actual_height = Math.Clamp(actual_height, 0, 36);
    air_res = (6 - actual_height) * 0.33;
    air_res = Math.Clamp(air_res, 0, 2);
    return air_res;
  }
References Math::Clamp().
Referenced by ParticleNormalSmokeStart(), and ParticleSmallSmokeStart().
GetAttachedStonesCount()
int GetAttachedStonesCount () protected
Definition at line 1531 of file FireplaceBase.c.
  {
    if (HasStones())
      return GetAttachmentByType(ATTACHMENT_STONES).GetQuantity();
    return 0;
  }
References ATTACHMENT_STONES, and HasStones().
Referenced by CanBuildOven(), and CanBuildStoneCircle().
GetCeilingHeight()
bool GetCeilingHeight (out float actual_height) protected
Definition at line 1170 of file FireplaceBase.c.
  {
    vector from = this.GetPosition();
    vector to = this.GetPosition();
    from[1] = from[1] + 1.0;
    to[1] = to[1] + MIN_CEILING_HEIGHT;
    vector contactPos;
    vector contactDir;
    int contactComponent;
    bool hit = DayZPhysics.RaycastRV(from, to, contactPos, contactDir, contactComponent, NULL, NULL, this);
    actual_height = vector.Distance(from, contactPos) + 1.0;
    return hit;
  }
References vector::Distance(), GetPosition, MIN_CEILING_HEIGHT, and DayZPhysics::RaycastRV().
Referenced by ParticleNormalSmokeStart(), and ParticleSmallSmokeStart().
GetCookingEquipment()
ItemBase GetCookingEquipment () protected
Definition at line 530 of file FireplaceBase.c.
  {
    return m_CookingEquipment;
  }
References m_CookingEquipment.
Referenced by ItemBase::CookWithEquipment(), ItemBase::OnSwitchOff(), ItemBase::OnWork(), ItemBase::OnWorkStart(), ItemBase::RemoveCookingAudioVisuals(), and StopCooling().
GetCookingProcess()
Cooking GetCookingProcess () protected
Definition at line 1986 of file FireplaceBase.c.
  {
    if (m_CookingProcess == null)
      m_CookingProcess = new Cooking();
    return m_CookingProcess;
  }
References m_CookingProcess.
GetDebugActions()
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList) protected
Definition at line 2617 of file FireplaceBase.c.
  {
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.ACTIVATE_ENTITY, "Ignite", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.DEACTIVATE_ENTITY, "Extinguish", FadeColors.LIGHT_GREY));
    outputList.Insert(new TSelectableActionInfoWithColor(SAT_DEBUG_ACTION, EActions.SEPARATOR, "___________________________", FadeColors.LIGHT_GREY));
    super.GetDebugActions(outputList);
  }
References SAT_DEBUG_ACTION.
GetFireConsumableByItem()
FireConsumable GetFireConsumableByItem (ItemBase item) protected
Definition at line 1297 of file FireplaceBase.c.
  {
    return m_FireConsumables.Get(item);
  }
References m_FireConsumables.
Referenced by FireplaceBase::EEItemDetached().
GetFireConsumableTypeEnergy()
float GetFireConsumableTypeEnergy (ItemBase item) protected
support for inherited classes; second pass of lookup inside FireConsumableType
Definition at line 1265 of file FireplaceBase.c.
  {
    FireConsumableType fireConsumableType = m_FireConsumableTypes.Get(item.Type());
    if (!fireConsumableType)
    {
      int count = m_FireConsumableTypes.Count();
      for (int i = 0; i < count; ++i)
      {
        if (item.IsInherited(m_FireConsumableTypes.GetKey(i)))
          fireConsumableType = m_FireConsumableTypes.GetElement(i);
      }
    }
    if (fireConsumableType)
      return fireConsumableType.GetEnergy();
    return 0;
  }
References m_FireConsumableTypes.
Referenced by AddToFireConsumables().
GetFireEffectPosition()
vector GetFireEffectPosition () protected
Definition at line 1199 of file FireplaceBase.c.
  {
    return Vector(0, 0.05, 0);
  }
References Vector().
Referenced by ParticleFireEndStart(), ParticleFireStartStart(), ParticleFireWindyNoIgniteStart(), ParticleNormalFireStart(), ParticleSmallFireStart(), ParticleSteamEndStart(), ParticleSteamExtinguishingStart(), and ParticleWetNoIgniteStart().
GetFireState()
int GetFireState () protected
Definition at line 1586 of file FireplaceBase.c.
  {
    return m_FireState;
  }
References m_FireState.
Referenced by Heating(), RefreshFireParticlesAndSounds(), and RefreshFireState().
GetFuelBurnRateMP()
float GetFuelBurnRateMP () protected
Definition at line 1575 of file FireplaceBase.c.
  {
    return m_FuelBurnRateMP;
  }
References m_FuelBurnRateMP.
Referenced by Heating().
GetFuelCount()
int GetFuelCount () protected
Returns count of all fuel type items (define in 'm_FuelTypes') attached to fireplace.
Definition at line 1406 of file FireplaceBase.c.
  {
    int attachmentsCount = GetInventory().AttachmentCount();
    int fuelCount = 0;
    for (int i = 0; i < attachmentsCount; ++i)
    {
      ItemBase item = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(i));
      if (IsFuel(item))
        fuelCount++;
    }
    return fuelCount;
  }
References IsFuel().
Referenced by AddWetnessToFireplace(), Cooling(), HasLastFuelKindlingAttached(), and Heating().
GetIgniteFailure()
bool GetIgniteFailure () protected
Definition at line 2235 of file FireplaceBase.c.
  {
    return m_NoIgnite;
  }
References m_NoIgnite.
Referenced by FireplaceBase::IsThisIgnitionSuccessful().
GetItemToConsume()
FireConsumable GetItemToConsume () protected
Definition at line 1332 of file FireplaceBase.c.
  {
    return m_ItemToConsume;
  }
References m_ItemToConsume.
Referenced by SpendFireConsumable().
GetKindlingCount()
int GetKindlingCount () protected
Returns count of all kindling type items (define in 'm_KindlingTypes') attached to fireplace.
Definition at line 1389 of file FireplaceBase.c.
  {
    int attachmentsCount = GetInventory().AttachmentCount();
    int kindlingCount = 0;
    for (int i = 0; i < attachmentsCount; ++i)
    {
      ItemBase item = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(i));
      if (IsKindling(item))
        kindlingCount++;
    }
    return kindlingCount;
  }
References IsKindling().
Referenced by HasAnyKindling(), HasLastFuelKindlingAttached(), and RefreshFireplaceVisuals().
GetLightEntity()
FireplaceLight GetLightEntity () protected
Definition at line 2409 of file FireplaceBase.c.
  {
    return m_Light;
  }
References m_Light.
Referenced by RefreshFireplaceVisuals(), and ~FireplaceBase().
GetPlaceSoundset()
override string GetPlaceSoundset () protected
Definition at line 2438 of file FireplaceBase.c.
  {
    return "placeFireplace_SoundSet";
  }
GetSmokeEffectPosition()
vector GetSmokeEffectPosition () protected
Definition at line 1204 of file FireplaceBase.c.
  {
    return Vector(0, 0.05, 0);
  }
References Vector().
GetTemperatureLossMP()
float GetTemperatureLossMP () protected
Definition at line 1564 of file FireplaceBase.c.
  {
    return m_TemperatureLossMP;
  }
References m_TemperatureLossMP.
HasAnyKindling()
bool HasAnyKindling () protected
Definition at line 2220 of file FireplaceBase.c.
  {
    return GetKindlingCount() > 0;
  }
References GetKindlingCount().
Referenced by FireplaceBase::CanBeIgnitedBy(), and FireplaceBase::IsThisIgnitionSuccessful().
HasAshes()
bool HasAshes () protected
Definition at line 1500 of file FireplaceBase.c.
  {
    return m_HasAshes;
  }
References m_HasAshes.
Referenced by FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), IsPrepareToDelete(), FireplaceBase::IsPrepareToDelete(), RefreshFireplaceVisuals(), and SpendFireConsumable().
HasCookingStand()
bool HasCookingStand () protected
Definition at line 2331 of file FireplaceBase.c.
  {
    return GetInventory().FindAttachment(InventorySlots.GetSlotIdFromString("CookingTripod")) != null;
  }
References InventorySlots::GetSlotIdFromString().
Referenced by FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), and Heating().
HasLastAttachment()
bool HasLastAttachment () protected
Definition at line 1472 of file FireplaceBase.c.
  {
    return GetInventory().AttachmentCount() == 1;
  }
HasLastFuelKindlingAttached()
bool HasLastFuelKindlingAttached () protected
Definition at line 1478 of file FireplaceBase.c.
  {
    return (GetFuelCount() + GetKindlingCount()) == 1;
  }
References GetFuelCount(), and GetKindlingCount().
HasStoneCircle()
bool HasStoneCircle () protected
Definition at line 1519 of file FireplaceBase.c.
  {
    return m_HasStoneCircle;
  }
References m_HasStoneCircle.
Referenced by CanBuildOven(), CanBuildStoneCircle(), CanDismantleStoneCircle(), FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), FireplaceBase::CanReleaseAttachment(), and RefreshFireplaceVisuals().
HasStones()
bool HasStones () protected
Definition at line 1524 of file FireplaceBase.c.
  {
    EntityAI attached_item = GetAttachmentByType(ATTACHMENT_STONES);
    return attached_item && attached_item.GetQuantity() > 0;
  }
References ATTACHMENT_STONES.
Referenced by FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), GetAttachedStonesCount(), and RefreshFireplaceVisuals().
Heating()
void Heating () protected
Definition at line 1681 of file FireplaceBase.c.
  {
    float temperature = GetTemperature();
    float temperature_modifier = 0;
    //check burning conditions
    if (GetWet() > PARAM_BURN_WET_THRESHOLD)
    {
      StopFire(FireplaceFireState.EXTINGUISHED_FIRE);
      return;
    }
    else
    {
      if (m_FireConsumables.Count() == 0)
      {
        StopFire();
        return;
      }
    }
    //spend actual fire consumable
    float amount = PARAM_FIRE_CONSUM_RATE_AMOUNT * GetFuelBurnRateMP() * TIMER_HEATING_UPDATE_INTERVAL;
    SpendFireConsumable(amount);
    //set wetness if raining and alter temperature modifier (which will lower temperature increase because of rain)
    float rain = GetGame().GetWeather().GetRain().GetActual();
    if (rain >= PARAM_BURN_WET_THRESHOLD && !IsRoofAbove())
    {
      //set wet to fireplace
      AddWetnessToFireplace(PARAM_WET_INCREASE_COEF * rain);
      //set temperature modifier
      temperature_modifier = PARAM_TEMPERATURE_INCREASE * rain;
    }
    //subtract wetness when heating and not raining above
    else
      AddWetnessToFireplace(-PARAM_WET_HEATING_DECREASE_COEF);
    // temperature via UniversalTemperatureSource
    m_UTSLFireplace.SetFuelCount(GetFuelCount());
    temperature = GetTemperature() + (PARAM_TEMPERATURE_INCREASE * TIMER_HEATING_UPDATE_INTERVAL) - temperature_modifier;
    m_UTSLFireplace.SetCurrentTemperature(temperature);
    m_UTSource.Update(m_UTSSettings, m_UTSLFireplace);
    //check fire state
    if (GetFireState() != FireplaceFireState.EXTINGUISHING_FIRE)
      RefreshFireState();
    //damage cargo items
    BurnItemsInFireplace();
    //manage cooking equipment (this applies only for case of cooking pot on a tripod)
    if (HasCookingStand() && m_CookingEquipment)
    {
      float cook_equip_temp = m_CookingEquipment.GetTemperature();
      if (cook_equip_temp >= PARAM_COOKING_TEMP_THRESHOLD)
      {
        //start cooking
        CookWithEquipment();
      }
      //DEBUG
      /*
        PlayerBase player = ( PlayerBase ) GetGame().GetPlayer();
        string s_message = "cooking equipment temp = " + ftoa(cook_equip_temp) + " | PARAM_COOKING_TEMP_THRESHOLD = " + ftoa(PARAM_COOKING_TEMP_THRESHOLD);
        if (player != NULL) {player.MessageAction (s_message);}
        Print ( s_message );
      */
      //set temperature to cooking equipment
      cook_equip_temp = cook_equip_temp + PARAM_COOKING_EQUIP_TEMP_INCREASE;
      if (temperature <= PARAM_SMALL_FIRE_TEMPERATURE)
        cook_equip_temp = Math.Clamp(cook_equip_temp, PARAM_ITEM_HEAT_MIN_TEMP, PARAM_SMALL_FIRE_TEMPERATURE);
      else
        cook_equip_temp = Math.Clamp(cook_equip_temp, PARAM_ITEM_HEAT_MIN_TEMP, PARAM_COOKING_EQUIP_MAX_TEMP);
      m_CookingEquipment.SetTemperature(cook_equip_temp);
    }
    float cook_item_temp;
    int i;
    // manage cooking on direct cooking slots
    if (DirectCookingSlotsInUse())
    {
      for (i = 0; i < DIRECT_COOKING_SLOT_COUNT; i++)
      {
        if (m_DirectCookingSlots[i])
        {
          cook_item_temp = m_DirectCookingSlots[i].GetTemperature();
          if (cook_item_temp >= PARAM_COOKING_TEMP_THRESHOLD)
            CookOnDirectSlot(m_DirectCookingSlots[i], cook_item_temp, temperature);
        }
      }
    }
    // manage smoking slots
    if (SmokingSlotsInUse())
    {
      for (i = 0; i < SMOKING_SLOT_COUNT; i++)
      {
        if (m_SmokingSlots[i])
          SmokeOnSmokingSlot(m_SmokingSlots[i], cook_item_temp, temperature);
      }
    }
    //Make noise for AI, only at night
    if (GetGame().GetWorld().IsNight() && m_CanNoise)
    {
      NoiseSystem noise = GetGame().GetNoiseSystem();
      if (noise && m_NoisePar)
        noise.AddNoisePos(this, GetPosition(), m_NoisePar);
      m_CanNoise = false;
    }
    else
      m_CanNoise = true;
    Synchronize();
  }
References AddWetnessToFireplace(), BurnItemsInFireplace(), Math::Clamp(), CookOnDirectSlot(), CookWithEquipment(), DIRECT_COOKING_SLOT_COUNT, DirectCookingSlotsInUse(), GetFireState(), GetFuelBurnRateMP(), GetFuelCount(), GetGame(), GetPosition, GetTemperature(), GetWet(), HasCookingStand(), IsRoofAbove(), m_CanNoise, m_CookingEquipment, m_DirectCookingSlots, m_FireConsumables, m_NoisePar, m_SmokingSlots, m_UTSLFireplace, m_UTSource, m_UTSSettings, PARAM_BURN_WET_THRESHOLD, PARAM_COOKING_EQUIP_MAX_TEMP, PARAM_COOKING_EQUIP_TEMP_INCREASE, PARAM_COOKING_TEMP_THRESHOLD, PARAM_FIRE_CONSUM_RATE_AMOUNT, PARAM_ITEM_HEAT_MIN_TEMP, PARAM_SMALL_FIRE_TEMPERATURE, PARAM_TEMPERATURE_INCREASE, PARAM_WET_HEATING_DECREASE_COEF, PARAM_WET_INCREASE_COEF, RefreshFireState(), SmokeOnSmokingSlot(), SMOKING_SLOT_COUNT, SmokingSlotsInUse(), SpendFireConsumable(), StopFire(), Synchronize(), and TIMER_HEATING_UPDATE_INTERVAL.
IsBarrelWithHoles()
bool IsBarrelWithHoles () protected
Definition at line 504 of file FireplaceBase.c.
  {
    return false;
  }
IsBaseFireplace()
bool IsBaseFireplace () protected
Definition at line 499 of file FireplaceBase.c.
  {
    return false;
  }
IsBurning()
bool IsBurning () protected
Definition at line 1488 of file FireplaceBase.c.
  {
    return m_IsBurning;
  }
References m_IsBurning.
Referenced by AfterStoreLoad(), FireplaceBase::AfterStoreLoad(), FireplaceBase::CanBeIgnitedBy(), CanBuildOven(), CanBuildStoneCircle(), CanDismantleOven(), CanDismantleStoneCircle(), CanExtinguishFire(), FireplaceBase::CanExtinguishFire(), FireplaceBase::CanIgniteItem(), FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), FireplaceBase::CanReceiveAttachment(), CanReleaseAttachment(), FireplaceBase::CanReleaseAttachment(), Cooling(), FireplaceBase::IsIgnited(), IsPrepareToDelete(), FireplaceBase::IsPrepareToDelete(), RefreshFireplaceVisuals(), RefreshFireState(), and StartFire().
IsCargoEmpty()
bool IsCargoEmpty () protected
Definition at line 2326 of file FireplaceBase.c.
  {
    return (GetInventory().GetCargo().GetItemCount() == 0);
  }
Referenced by FireplaceBase::CanPutInCargo(), and FireplaceBase::CanPutIntoHands().
IsCeilingHighEnoughForSmoke()
bool IsCeilingHighEnoughForSmoke () protected
Definition at line 2269 of file FireplaceBase.c.
  {
    return !MiscGameplayFunctions.IsUnderRoof(this, FireplaceBase.MIN_CEILING_HEIGHT);
  }
Referenced by FireplaceBase::IsThisIgnitionSuccessful().
IsEmpty()
override bool IsEmpty () protected
Definition at line 2320 of file FireplaceBase.c.
  {
    return (GetInventory().GetCargo().GetItemCount() == 0 && GetInventory().AttachmentCount() == 0);
  }
Referenced by RecipeBase::CanDo(), CivilianBelt::CanPutInCargo(), HipPack_ColorBase::CanPutInCargo(), Belt_Base::CanPutInCargo(), MilitaryBelt::CanPutInCargo(), RopeBelt::CanPutInCargo(), and IsPrepareToDelete().
IsEntityOnInteriorSurface()
static bool IsEntityOnInteriorSurface (notnull EntityAI entity_ai) static protected
Definition at line 2307 of file FireplaceBase.c.
  {
    string surfaceType;
    vector fireplacePosition = entity_ai.GetPosition();
    GetGame().SurfaceGetType3D(fireplacePosition[0], fireplacePosition[1] + 1.0, fireplacePosition[2], surfaceType);
    return (GetGame().ConfigGetInt("CfgSurfaces " + surfaceType + " interior") == 1);
  }
References GetGame().
Referenced by FireplaceBase::CanIgniteEntityAsFireplace().
IsEntityOnWaterSurface()
static bool IsEntityOnWaterSurface (notnull EntityAI entity_ai) static protected
Definition at line 2286 of file FireplaceBase.c.
  {
    vector fireplacePosition = entity_ai.GetPosition();
    string surfaceType;
    g_Game.SurfaceGetType3D(fireplacePosition[0], fireplacePosition[1] + g_Game.SurfaceGetSeaLevel(), fireplacePosition[2], surfaceType);
    if (!surfaceType)
    {
      float waterLevelDiff = fireplacePosition[1] - g_Game.SurfaceGetSeaLevel();
      return waterLevelDiff < 0.5;
    }
    else if (surfaceType.Contains("water"))
      return true;
    return false;
  }
References g_Game.
IsEntityWet()
static bool IsEntityWet (notnull EntityAI entity_ai) static protected
Definition at line 2246 of file FireplaceBase.c.
  {
    return (entity_ai.GetWet() >= FireplaceBase.PARAM_MAX_WET_TO_IGNITE);
  }
IsFacingFireplace()
bool IsFacingFireplace (PlayerBase player) protected
DEPRECATED.
Definition at line 2208 of file FireplaceBase.c.
  {
    ErrorEx("Deprecated method", ErrorExSeverity.INFO);
    return false;
  }
References ErrorEx.
IsFireplace()
override bool IsFireplace () protected
Definition at line 494 of file FireplaceBase.c.
  {
    return true;
  }
Referenced by TripodBase::CanSwapEntities(), and InventoryItem::ProcessItemTemperature().
IsFireplaceIndoor()
bool IsFireplaceIndoor () protected
Definition at line 509 of file FireplaceBase.c.
  {
    return false;
  }
IsFuel()
bool IsFuel (ItemBase item) protected
Returns if item attached to fireplace is fuel.
support for inherited classes; second pass of lookup inside FireConsumableType
Definition at line 1440 of file FireplaceBase.c.
  {
    FireConsumableType fireConsumableType = m_FireConsumableTypes.Get(item.Type());
    if (!fireConsumableType)
    {
      int count = m_FireConsumableTypes.Count();
      for (int i = 0; i < count; ++i)
      {
        if (item.IsInherited(m_FireConsumableTypes.GetKey(i)))
          fireConsumableType = m_FireConsumableTypes.GetElement(i);
      }
    }
    return fireConsumableType && !fireConsumableType.IsKindling();
  }
References m_FireConsumableTypes.
Referenced by AddDamageToItemByFireEx(), FireplaceBase::CanReceiveAttachment(), CanReleaseAttachment(), FireplaceBase::CanReleaseAttachment(), FireplaceBase::EEItemAttached(), FireplaceBase::EEItemDetached(), and GetFuelCount().
IsInAnimPhase()
bool IsInAnimPhase (string anim_phase) protected
Definition at line 2337 of file FireplaceBase.c.
  {
    return GetAnimationPhase(anim_phase) == 0;
  }
Referenced by SetBurntFirewood().
IsIndoorOven()
bool IsIndoorOven () protected
Definition at line 514 of file FireplaceBase.c.
  {
    return false;
  }
IsItemAttachedQuantity()
bool IsItemAttachedQuantity (typename item_type , float quantity) protected
Definition at line 1464 of file FireplaceBase.c.
  {
    ItemBase item = ItemBase.Cast(GetAttachmentByType(item_type));
    return item.GetQuantity() >= quantity;
  }
IsItemTypeAttached()
bool IsItemTypeAttached (typename item_type) protected
Definition at line 1458 of file FireplaceBase.c.
  {
    return GetAttachmentByType(item_type) != null;
  }
Referenced by RefreshFireplaceVisuals(), and FireplaceBase::RefreshPhysics().
IsKindling()
bool IsKindling (ItemBase item) protected
Returns if item attached to fireplace is kindling.
support for inherited classes; second pass of lookup inside FireConsumableType
Definition at line 1422 of file FireplaceBase.c.
  {
    FireConsumableType fireConsumableType = m_FireConsumableTypes.Get(item.Type());
    if (!fireConsumableType)
    {
      int count = m_FireConsumableTypes.Count();
      for (int i = 0; i < count; ++i)
      {
        if (item.IsInherited(m_FireConsumableTypes.GetKey(i)))
          fireConsumableType = m_FireConsumableTypes.GetElement(i);
      }
    }
    return fireConsumableType && fireConsumableType.IsKindling();
  }
References m_FireConsumableTypes.
Referenced by AddDamageToItemByFireEx(), FireplaceBase::CanReceiveAttachment(), CanReleaseAttachment(), FireplaceBase::CanReleaseAttachment(), FireplaceBase::EEItemAttached(), FireplaceBase::EEItemDetached(), and GetKindlingCount().
IsOnInteriorSurface()
bool IsOnInteriorSurface () protected
Definition at line 2314 of file FireplaceBase.c.
  {
    return FireplaceBase.IsEntityOnInteriorSurface(this);
  }
Referenced by FireplaceBase::IsThisIgnitionSuccessful().
IsOnWaterSurface()
bool IsOnWaterSurface () protected
Definition at line 2301 of file FireplaceBase.c.
  {
    return FireplaceBase.IsEntityOnWaterSurface(this);
  }
Referenced by FireplaceBase::IsThisIgnitionSuccessful().
IsOpen()
override bool IsOpen () protected
Definition at line 2263 of file FireplaceBase.c.
  {
    return true;
  }
IsOven()
bool IsOven () protected
Definition at line 1515 of file FireplaceBase.c.
  {
    return m_IsOven;
  }
References m_IsOven.
Referenced by CanBuildOven(), CanBuildStoneCircle(), CanDismantleOven(), CanDismantleStoneCircle(), FireplaceBase::CanDisplayAttachmentCategory(), FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), FireplaceBase::CanReceiveAttachment(), FireplaceBase::CanReleaseAttachment(), FireplaceBase::CanShowSmoke(), FireplaceBase::EEItemAttached(), FireplaceBase::IsThisIgnitionSuccessful(), OnVariablesSynchronized(), ParticleFireEndStart(), ParticleFireStartStart(), ParticleFireWindyNoIgniteStart(), ParticleNormalFireStart(), ParticleSmallFireStart(), RefreshFireplaceVisuals(), FireplaceBase::RefreshPhysics(), and StartHeating().
IsPrepareToDelete()
override bool IsPrepareToDelete () protected
Definition at line 580 of file FireplaceBase.c.
  {
    return IsEmpty() && !IsBurning() && !HasAshes();
  }
References HasAshes(), IsBurning(), and IsEmpty().
Referenced by Entity::CheckForDestroy(), and Entity::TryDelete().
IsRainingAbove()
bool IsRainingAbove () protected
Definition at line 2280 of file FireplaceBase.c.
  {
    return FireplaceBase.IsRainingAboveEntity(this);
  }
Referenced by Cooling(), and FireplaceBase::IsThisIgnitionSuccessful().
IsRainingAboveEntity()
static bool IsRainingAboveEntity (notnull EntityAI entity_ai) static protected
Definition at line 2275 of file FireplaceBase.c.
  {
    return (GetGame() && (GetGame().GetWeather().GetRain().GetActual() >= FireplaceBase.PARAM_IGNITE_RAIN_THRESHOLD));
  }
References GetGame().
IsRoofAbove()
bool IsRoofAbove () protected
Definition at line 2257 of file FireplaceBase.c.
  {
    return m_RoofAbove;
  }
References m_RoofAbove.
Referenced by Cooling(), Heating(), ParticleNormalSmokeStart(), ParticleSmallSmokeStart(), and StartHeating().
IsSpaceFor()
bool IsSpaceFor (vector size) protected
Definition at line 2342 of file FireplaceBase.c.
  {
    array<Object> objs = {};
    if (GetGame().IsBoxCollidingGeometry(GetWorldPosition() + Vector(0, size[1] * 0.5 + 0.1, 0), GetDirection().VectorToAngles(), size, ObjIntersect.View, ObjIntersect.Geom, {this}, objs))
    {
      foreach (Object obj : objs)
      {
        if (dBodyGetInteractionLayer(obj) == PhxInteractionLayers.ITEM_LARGE)
          return false;
      }
    }
    return true;
  }
References dBodyGetInteractionLayer(), GetGame(), and Vector().
Referenced by IsSpaceForCircle(), and IsSpaceForOven().
IsSpaceForCircle()
bool IsSpaceForCircle () protected
Definition at line 2382 of file FireplaceBase.c.
  {
    return IsSpaceFor(Vector(0.9, 0.1, 0.9));
  }
References IsSpaceFor(), and Vector().
Referenced by CanBuildStoneCircle().
IsSpaceForOven()
bool IsSpaceForOven () protected
Definition at line 2370 of file FireplaceBase.c.
  {
    const float size = 0.6;
    return IsSpaceFor(Vector(size, size, size));
  }
References IsSpaceFor(), and Vector().
Referenced by CanBuildOven().
IsWet()
bool IsWet () protected
Definition at line 2251 of file FireplaceBase.c.
  {
    return FireplaceBase.IsEntityWet(this);
  }
Referenced by FireplaceBase::IsThisIgnitionSuccessful(), and RefreshFireplaceVisuals().
IsWindy()
static bool IsWindy () static protected
Definition at line 2226 of file FireplaceBase.c.
  {
    //check wind
    float wind_speed = GetGame().GetWeather().GetWindSpeed();
    float wind_speed_threshold = GetGame().GetWeather().GetWindMaximumSpeed() * FireplaceBase.IGNITE_WIND_THRESHOLD;
    return (wind_speed >= wind_speed_threshold);
  }
References GetGame().
Referenced by FireplaceBase::IsThisIgnitionSuccessful(), and StartHeating().
LockOvenAttachments()
void LockOvenAttachments (bool lock) protected
Definition at line 2522 of file FireplaceBase.c.
  {
    //Print("LockOvenAttachments");
    //string path_cooking_equipment = "" + CFG_VEHICLESPATH + " " + GetType() + " GUIInventoryAttachmentsProps CookingEquipment attachmentSlots";
    string path_cooking_equipment = string.Format("%1 %2 GUIInventoryAttachmentsProps CookingEquipment attachmentSlots", CFG_VEHICLESPATH, GetType());
    //string path_direct_cooking = "" + CFG_VEHICLESPATH + " " + GetType() + " GUIInventoryAttachmentsProps DirectCooking attachmentSlots";
    string path_direct_cooking = string.Format("%1 %2 GUIInventoryAttachmentsProps DirectCooking attachmentSlots", CFG_VEHICLESPATH, GetType());
    if (GetGame().ConfigIsExisting(path_cooking_equipment) && GetGame().ConfigIsExisting(path_direct_cooking))
    {
      array<string> arr_cooking_equipment = new array<string>;
      array<string> arr_direct_cooking = new array<string>;
      GetGame().ConfigGetTextArray(path_cooking_equipment, arr_cooking_equipment);
      GetGame().ConfigGetTextArray(path_direct_cooking, arr_direct_cooking);
      for (int i = 0; i < arr_cooking_equipment.Count(); i++)
      {
        if (lock != GetInventory().GetSlotLock(InventorySlots.GetSlotIdFromString(arr_cooking_equipment[i])))
        {
          GetInventory().SetSlotLock(InventorySlots.GetSlotIdFromString(arr_cooking_equipment[i]), lock);
          //Print("attachment lock: " + arr_cooking_equipment[i] + " " + lock);
        }
      }
      for (i = 0; i < arr_direct_cooking.Count(); i++)
      {
        if (lock == GetInventory().GetSlotLock(InventorySlots.GetSlotIdFromString(arr_direct_cooking[i])))
        {
          GetInventory().SetSlotLock(InventorySlots.GetSlotIdFromString(arr_direct_cooking[i]), !lock);
          //Print("attachment lock: " + arr_direct_cooking[i] + " " + !lock);
        }
      }
    }
    m_OvenAttachmentsLockState = lock;
  }
References CFG_VEHICLESPATH, GetGame(), InventorySlots::GetSlotIdFromString(), GetType(), and m_OvenAttachmentsLockState.
Referenced by RefreshFireplaceVisuals().
OnAction()
override bool OnAction (int action_id, Man player, ParamsReadContext ctx) protected
Definition at line 2626 of file FireplaceBase.c.
  {
    if (super.OnAction(action_id, player, ctx))
      return true;
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      if (action_id == EActions.ACTIVATE_ENTITY)
        OnIgnitedThis(null);
      else if (action_id == EActions.DEACTIVATE_ENTITY)
        StopFire();
    }
    return false;
  }
References GetGame(), FireplaceBase::OnIgnitedThis(), and StopFire().
OnAttachmentQuantityChanged()
override void OnAttachmentQuantityChanged (ItemBase item) protected
Definition at line 2503 of file FireplaceBase.c.
  {
    super.OnAttachmentQuantityChanged(item);
    CalcAndSetQuantity();
  }
References CalcAndSetQuantity().
OnAttachmentRuined()
override void OnAttachmentRuined (EntityAI attachment) protected
Definition at line 334 of file FireplaceBase.c.
  {
    switch (attachment.Type())
    {
    case ATTACHMENT_TRIPOD:
    case ATTACHMENT_COOKINGSTAND:
      int slot = InventorySlots.GetSlotIdFromString("CookingEquipment");
      EntityAI ent = GetInventory().FindAttachment(slot);
      if (ent)
      {
        switch (ent.Type())
        {
        case ATTACHMENT_COOKING_POT:
        case ATTACHMENT_CAULDRON:
        case ATTACHMENT_FRYING_PAN:
          vector direction = ent.GetDirection();
          float dot = vector.Dot(direction, vector.Forward);
          float angle = Math.Acos(dot);
          if (direction[0] < 0)
            angle = -angle;
          float cos = Math.Cos(angle);
          float sin = Math.Sin(angle);
          GetInventory().DropEntityInBounds(InventoryMode.SERVER, this, ent, "2 0 2", angle, cos, sin);
          break;
        }
      }
      attachment.Delete();
      break;
    }
  }
References Math::Acos(), ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_COOKINGSTAND, ATTACHMENT_FRYING_PAN, ATTACHMENT_TRIPOD, Math::Cos(), vector::Dot(), vector::Forward, InventorySlots::GetSlotIdFromString(), and Math::Sin().
OnDebugSpawn()
override void OnDebugSpawn () protected
Definition at line 2601 of file FireplaceBase.c.
  {
    ItemBase firewood = ItemBase.Cast(GetInventory().CreateInInventory("Firewood"));
    firewood.SetQuantity(firewood.GetQuantityMax());
    ItemBase sticks = ItemBase.Cast(GetInventory().CreateInInventory("WoodenStick"));
    sticks.SetQuantity(sticks.GetQuantityMax());
    ItemBase stone = ItemBase.Cast(GetInventory().CreateInInventory("Stone"));
    stone.SetQuantity(stone.GetQuantityMax());
    GetInventory().CreateInInventory("Rag");
    SpawnEntityOnGroundPos("PetrolLighter", GetPosition());
  }
References GetPosition.
OnItemLocationChanged()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) protected
Definition at line 326 of file FireplaceBase.c.
  {
    super.OnItemLocationChanged(old_owner, new_owner);
    //refresh physics after location change (with delay)
    GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).Call(RefreshFireplacePhysics);
  }
References CALL_CATEGORY_GAMEPLAY, GetGame(), and FireplaceBase::RefreshFireplacePhysics().
OnPlacementComplete()
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") protected
Definition at line 2423 of file FireplaceBase.c.
  {
    super.OnPlacementComplete(player, position, orientation);
    if (GetGame().IsServer())
    {
      //remove grass
      Object cc_object = GetGame().CreateObjectEx(OBJECT_CLUTTER_CUTTER, position, ECE_PLACE_ON_SURFACE);
      cc_object.SetOrientation(orientation);
      GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLater(GetGame().ObjectDelete, 1000, false, cc_object);
      SetIsPlaceSound(true);
    }
  }
References CALL_CATEGORY_GAMEPLAY, ECE_PLACE_ON_SURFACE, GetGame(), OBJECT_CLUTTER_CUTTER, and SetIsPlaceSound().
OnRPC()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) protected
Definition at line 2560 of file FireplaceBase.c.
  {
    super.OnRPC(sender, rpc_type, ctx);
    ref Param1<bool> p = new Param1<bool>(false);
    if (ctx.Read(p))
      bool failure = p.param1;
    switch (rpc_type)
    {
    case FirePlaceFailure.WIND:
      if (failure)
      {
        ParticleFireWindyNoIgniteStart();
        SoundFireStop();
        SoundFireWindyNoIgniteStart();
      }
      break;
    case FirePlaceFailure.WET:
      if (failure)
      {
        ParticleWetNoIgniteStart();
        SoundFireStop();
        SoundFireWetNoIgniteStart();
      }
      break;
    }
  }
References ParticleFireWindyNoIgniteStart(), ParticleWetNoIgniteStart(), SoundFireStop(), SoundFireWetNoIgniteStart(), and SoundFireWindyNoIgniteStart().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) protected
Definition at line 398 of file FireplaceBase.c.
  {
    if (!super.OnStoreLoad(ctx, version))
      return false;
    //--- Fireplace data ---
    //Load ashes state
    if (!ctx.Read(m_HasAshes))
    {
      m_HasAshes = false; //set default
      return false;
    }
    //Load temperature loss MP
    if (!ctx.Read(m_TemperatureLossMP))
    {
      m_TemperatureLossMP = 1.0; //set default
      return false;
    }
    //Load fuel burn rate MP
    if (!ctx.Read(m_FuelBurnRateMP))
    {
      m_FuelBurnRateMP = 1.0; //set default
      return false;
    }
    //Load burning state, if true start fire
    if (!ctx.Read(m_IsBurning))
    {
      m_IsBurning = false; //set default
      return false;
    }
    //---
    return true;
  }
References m_FuelBurnRateMP, m_HasAshes, m_IsBurning, and m_TemperatureLossMP.
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) protected
Definition at line 381 of file FireplaceBase.c.
  {
    super.OnStoreSave(ctx);
    //Save ashes state
    ctx.Write(m_HasAshes);
    //Save temperature loss MP
    ctx.Write(m_TemperatureLossMP);
    //Save fuel burn rate MP
    ctx.Write(m_FuelBurnRateMP);
    //Save burning state
    ctx.Write(m_IsBurning);
  }
References m_FuelBurnRateMP, m_HasAshes, m_IsBurning, and m_TemperatureLossMP.
OnVariablesSynchronized()
override void OnVariablesSynchronized () protected
Definition at line 469 of file FireplaceBase.c.
  {
    super.OnVariablesSynchronized();
    RefreshFireplaceVisuals();
    RefreshFireParticlesAndSounds(false);
    if (IsPlaceSound())
      PlayPlaceSound();
    if (IsBaseFireplace() && !IsOven())
    {
      if (m_IsBurning && !m_AreaDamage)
        CreateAreaDamage();
      else if (!m_IsBurning && m_AreaDamage)
        DestroyAreaDamage();
    }
  }
References FireplaceBase::CreateAreaDamage(), DestroyAreaDamage(), FireplaceBase::IsBaseFireplace(), IsOven(), IsPlaceSound(), m_AreaDamage, m_IsBurning, PlayPlaceSound(), RefreshFireParticlesAndSounds(), and RefreshFireplaceVisuals().
ParticleFireEndStart()
void ParticleFireEndStart () protected
Definition at line 1117 of file FireplaceBase.c.
  {
    if (IsOven())
      PlayParticle(m_ParticleFireEnd, PARTICLE_OVEN_FIRE_END, GetFireEffectPosition());
    else
      PlayParticle(m_ParticleFireEnd, PARTICLE_FIRE_END, GetFireEffectPosition());
  }
References GetFireEffectPosition(), IsOven(), m_ParticleFireEnd, PARTICLE_FIRE_END, PARTICLE_OVEN_FIRE_END, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleFireEndStop()
void ParticleFireEndStop () protected
Definition at line 1125 of file FireplaceBase.c.
  {
    StopParticle(m_ParticleFireEnd);
  }
References m_ParticleFireEnd, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleFireStartStart()
void ParticleFireStartStart () protected
Definition at line 1027 of file FireplaceBase.c.
  {
    if (IsOven())
      PlayParticle(m_ParticleFireStart, PARTICLE_OVEN_FIRE_START, GetFireEffectPosition());
    else
      PlayParticle(m_ParticleFireStart, PARTICLE_FIRE_START, GetFireEffectPosition());
  }
References GetFireEffectPosition(), IsOven(), m_ParticleFireStart, PARTICLE_FIRE_START, PARTICLE_OVEN_FIRE_START, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleFireStartStop()
void ParticleFireStartStop () protected
Definition at line 1035 of file FireplaceBase.c.
  {
    StopParticle(m_ParticleFireStart);
  }
References m_ParticleFireStart, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleFireWindyNoIgniteStart()
void ParticleFireWindyNoIgniteStart () protected
Definition at line 1130 of file FireplaceBase.c.
  {
    if (IsOven())
      PlayParticle(m_ParticleFireEnd, PARTICLE_OVEN_FIRE_END, GetFireEffectPosition());
    else
      PlayParticle(m_ParticleFireEnd, PARTICLE_NO_IGNITE_WIND, GetFireEffectPosition());
  }
References GetFireEffectPosition(), IsOven(), m_ParticleFireEnd, PARTICLE_NO_IGNITE_WIND, PARTICLE_OVEN_FIRE_END, and PlayParticle().
Referenced by OnRPC().
ParticleNormalFireStart()
void ParticleNormalFireStart () protected
Definition at line 1055 of file FireplaceBase.c.
  {
    if (IsOven())
      PlayParticle(m_ParticleNormalFire, PARTICLE_OVEN_FIRE, GetFireEffectPosition());
    else
      PlayParticle(m_ParticleNormalFire, PARTICLE_NORMAL_FIRE, GetFireEffectPosition());
  }
References GetFireEffectPosition(), IsOven(), m_ParticleNormalFire, PARTICLE_NORMAL_FIRE, PARTICLE_OVEN_FIRE, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleNormalFireStop()
void ParticleNormalFireStop () protected
Definition at line 1063 of file FireplaceBase.c.
  {
    StopParticle(m_ParticleNormalFire);
  }
References m_ParticleNormalFire, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleNormalSmokeStart()
void ParticleNormalSmokeStart () protected
Definition at line 1093 of file FireplaceBase.c.
  {
    PlayParticle(m_ParticleNormalSmoke, PARTICLE_NORMAL_SMOKE, GetSmokeEffectPosition());
    //calculate air resistance
    float actual_height;
    if (GetCeilingHeight(actual_height))
    {
      float air_resistance = GetAirResistanceForSmokeParticles(actual_height);
      //alter smoke height
      m_ParticleNormalSmoke.SetParameter(-1, EmitorParam.AIR_RESISTANCE, air_resistance);
    }
    if (IsRoofAbove())
      m_ParticleNormalSmoke.SetParameter(-1, EmitorParam.WIND, false);
  }
References GetAirResistanceForSmokeParticles(), GetCeilingHeight(), FireplaceBase::GetSmokeEffectPosition(), IsRoofAbove(), m_ParticleNormalSmoke, PARTICLE_NORMAL_SMOKE, PlayParticle(), and Particle::SetParameter().
ParticleNormalSmokeStop()
void ParticleNormalSmokeStop () protected
Definition at line 1111 of file FireplaceBase.c.
  {
    StopParticle(m_ParticleNormalSmoke);
  }
References m_ParticleNormalSmoke, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSmallFireStart()
void ParticleSmallFireStart () protected
Definition at line 1041 of file FireplaceBase.c.
  {
    if (IsOven())
      PlayParticle(m_ParticleSmallFire, PARTICLE_OVEN_FIRE, GetFireEffectPosition());
    else
      PlayParticle(m_ParticleSmallFire, PARTICLE_SMALL_FIRE, GetFireEffectPosition());
  }
References GetFireEffectPosition(), IsOven(), m_ParticleSmallFire, PARTICLE_OVEN_FIRE, PARTICLE_SMALL_FIRE, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSmallFireStop()
void ParticleSmallFireStop () protected
Definition at line 1049 of file FireplaceBase.c.
  {
    StopParticle(m_ParticleSmallFire);
  }
References m_ParticleSmallFire, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSmallSmokeStart()
void ParticleSmallSmokeStart () protected
Definition at line 1069 of file FireplaceBase.c.
  {
    PlayParticle(m_ParticleSmallSmoke, PARTICLE_SMALL_SMOKE, GetSmokeEffectPosition());
    //calculate air resistance
    float actual_height;
    if (GetCeilingHeight(actual_height))
    {
      float air_resistance = GetAirResistanceForSmokeParticles(actual_height);
      //alter smoke height
      m_ParticleSmallSmoke.SetParameter(-1, EmitorParam.AIR_RESISTANCE, air_resistance);
    }
    if (IsRoofAbove())
      m_ParticleSmallSmoke.SetParameter(-1, EmitorParam.WIND, false);
  }
References GetAirResistanceForSmokeParticles(), GetCeilingHeight(), FireplaceBase::GetSmokeEffectPosition(), IsRoofAbove(), m_ParticleSmallSmoke, PARTICLE_SMALL_SMOKE, PlayParticle(), and Particle::SetParameter().
ParticleSmallSmokeStop()
void ParticleSmallSmokeStop () protected
Definition at line 1087 of file FireplaceBase.c.
  {
    StopParticle(m_ParticleSmallSmoke);
  }
References m_ParticleSmallSmoke, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSteamEndStart()
void ParticleSteamEndStart () protected
Definition at line 1150 of file FireplaceBase.c.
  {
    PlayParticle(m_ParticleSteamEnd, PARTICLE_STEAM_END, GetFireEffectPosition());
  }
References GetFireEffectPosition(), m_ParticleSteamEnd, PARTICLE_STEAM_END, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSteamEndStop()
void ParticleSteamEndStop () protected
Definition at line 1155 of file FireplaceBase.c.
  {
    StopParticle(m_ParticleSteamEnd);
  }
References m_ParticleSteamEnd, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSteamExtinguishingStart()
void ParticleSteamExtinguishingStart () protected
Definition at line 1139 of file FireplaceBase.c.
  {
    PlayParticle(m_ParticleSteamExtinguishing, PARTICLE_STEAM_EXTINGUISHING, GetFireEffectPosition());
  }
References GetFireEffectPosition(), m_ParticleSteamExtinguishing, PARTICLE_STEAM_EXTINGUISHING, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSteamExtinguishingStop()
void ParticleSteamExtinguishingStop () protected
Definition at line 1144 of file FireplaceBase.c.
  {
    StopParticle(m_ParticleSteamExtinguishing);
  }
References m_ParticleSteamExtinguishing, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleWetNoIgniteStart()
void ParticleWetNoIgniteStart () protected
Definition at line 1160 of file FireplaceBase.c.
  {
    PlayParticle(m_ParticleSteamEnd, PARTICLE_STEAM_END, GetFireEffectPosition());
  }
References GetFireEffectPosition(), m_ParticleSteamEnd, PARTICLE_STEAM_END, and PlayParticle().
Referenced by OnRPC().
ParticleWetNoIgniteStop()
void ParticleWetNoIgniteStop () protected
Definition at line 1165 of file FireplaceBase.c.
  {
    StopParticle(m_ParticleSteamEnd);
  }
References m_ParticleSteamEnd, and StopParticle().
PlayParticle()
bool PlayParticle (out Particle particle, int particle_type, vector pos, bool worldpos = false) protected
Definition at line 997 of file FireplaceBase.c.
  {
    if (!particle && GetGame() && (!GetGame().IsDedicatedServer()))
    {
      if (!worldpos)
        particle = ParticleManager.GetInstance().PlayOnObject(particle_type, this, pos);
      else
        particle = ParticleManager.GetInstance().PlayInWorld(particle_type, pos);
      return true;
    }
    return false;
  }
References GetGame(), and ParticleManager().
RefreshFireParticlesAndSounds()
void RefreshFireParticlesAndSounds (bool force_refresh) protected
Definition at line 761 of file FireplaceBase.c.
  {
    FireplaceFireState fire_state = GetFireState();
    if (m_LastFireState != fire_state || force_refresh)
    {
      switch (fire_state)
      {
      case FireplaceFireState.START_FIRE:
      {
        //particles
        ParticleFireStartStart();
        //sounds
        SoundFireStop();
        SoundFireLightStart();
        break;
      }
      case FireplaceFireState.SMALL_FIRE:
      {
        //particles
        ParticleFireStartStop();
        ParticleSmallFireStart();
        if (CanShowSmoke())
          ParticleSmallSmokeStart();
        else
          ParticleSmallSmokeStop();
        ParticleNormalFireStop();
        ParticleNormalSmokeStop();
        ParticleSteamExtinguishingStop();
        //sounds
        SoundFireStop();
        SoundFireLightStart();
        break;
      }
      case FireplaceFireState.NORMAL_FIRE:
      {
        //particles
        ParticleFireStartStop();
        ParticleSmallFireStop();
        ParticleSmallSmokeStop();
        ParticleNormalFireStart();
        if (CanShowSmoke())
          ParticleNormalSmokeStart();
        else
          ParticleNormalSmokeStop();
        ParticleSteamExtinguishingStop();
        //sounds
        SoundFireStop();
        SoundFireHeavyStart();
        break;
      }
      case FireplaceFireState.END_FIRE:
      {
        //particles
        ParticleFireStartStop();
        ParticleSmallFireStop();
        ParticleSmallSmokeStop();
        ParticleNormalFireStop();
        ParticleNormalSmokeStop();
        ParticleFireEndStart();
        //sounds
        SoundFireStop();
        SoundFireNoFireStart();
        break;
      }
      case FireplaceFireState.EXTINGUISHING_FIRE: //TODO add steam particles when extinguishing
      {
        //particles
        ParticleFireStartStop();
        ParticleSmallFireStop();
        ParticleSmallSmokeStop();
        ParticleNormalFireStop();
        ParticleNormalSmokeStop();
        ParticleFireEndStop();
        ParticleSteamExtinguishingStart();
        //sounds
        SoundFireStop();
        SoundFireExtinguishingStart();
        break;
      }
      case FireplaceFireState.EXTINGUISHED_FIRE: //TODO add steam particles when fireplace is extinguished
      {
        //particles
        ParticleFireStartStop();
        ParticleSmallFireStop();
        ParticleSmallSmokeStop();
        ParticleNormalFireStop();
        ParticleNormalSmokeStop();
        ParticleFireEndStop();
        ParticleSteamExtinguishingStop();
        if (CanShowSmoke())
          ParticleSteamEndStart();
        else
          ParticleSteamEndStop();
        //sounds
        SoundFireStop();
        SoundFireExtinguishedStart();
        SoundFireNoFireStart();
        break;
      }
      case FireplaceFireState.REIGNITED_FIRE:
      {
        //particles
        ParticleFireStartStart();
        ParticleSmallFireStop();
        ParticleSmallSmokeStop();
        ParticleNormalFireStop();
        ParticleNormalSmokeStop();
        ParticleFireEndStop();
        ParticleSteamEndStop();
        //sounds
        SoundFireStop();
        break;
      }
      case FireplaceFireState.NO_FIRE:
      {
        //particles
        ParticleFireStartStop();
        ParticleSmallFireStop();
        ParticleSmallSmokeStop();
        ParticleNormalFireStop();
        ParticleNormalSmokeStop();
        ParticleFireEndStop();
        ParticleSteamEndStop();
        ParticleSteamExtinguishingStop();
        //sounds
        SoundFireStop();
        break;
      }
      }
      m_LastFireState = fire_state;
    }
  }
References FireplaceBase::CanShowSmoke(), GetFireState(), m_LastFireState, ParticleFireEndStart(), ParticleFireEndStop(), ParticleFireStartStart(), ParticleFireStartStop(), ParticleNormalFireStart(), ParticleNormalFireStop(), FireplaceBase::ParticleNormalSmokeStart(), ParticleNormalSmokeStop(), ParticleSmallFireStart(), ParticleSmallFireStop(), FireplaceBase::ParticleSmallSmokeStart(), ParticleSmallSmokeStop(), ParticleSteamEndStart(), ParticleSteamEndStop(), ParticleSteamExtinguishingStart(), ParticleSteamExtinguishingStop(), SoundFireExtinguishedStart(), SoundFireExtinguishingStart(), SoundFireHeavyStart(), SoundFireLightStart(), SoundFireNoFireStart(), and SoundFireStop().
Referenced by OnVariablesSynchronized(), and FireplaceBase::OnVariablesSynchronized().
RefreshFireplacePhysics()
void RefreshFireplacePhysics () protected
RefreshFireplaceVisuals()
void RefreshFireplaceVisuals () protected
single stone; everything else hidden
hide stones stack completely
Definition at line 596 of file FireplaceBase.c.
  {
    if (IsHologram())
      return;
    // Light
#ifndef SERVER
    if (IsBurning())
    {
      //turn light on
      if (!GetLightEntity())
      {
        SetLightEntity(FireplaceLight.Cast(ScriptedLightBase.CreateLight(FireplaceLight, GetPosition(), 20)));
        GetLightEntity().AttachOnMemoryPoint(this, "light");
      }
      if (GetLightEntity() && GetLightEntity().GetBrightness() > 0)
      {
        // change brightness based on the distance of player to the fireplace
        Object player = GetGame().GetPlayer();
        float lightDist = m_LightDistance;
        if (IsOven())
          lightDist = 50;
        if (player)
        {
          if (vector.DistanceSq(player.GetPosition(), this.GetPosition()) > lightDist * lightDist)
            GetLightEntity().FadeBrightnessTo(0, 5);
          else
            GetLightEntity().FadeBrightnessTo(FireplaceLight.m_FireplaceBrightness, 5);
        }
        // The following solves an issue with the light point clipping through narrow geometry
        if (IsItemTypeAttached(ATTACHMENT_STONES) || IsBarrelWithHoles() || IsFireplaceIndoor())
          GetLightEntity().SetInteriorMode();
        else
          GetLightEntity().SetExteriorMode();
      }
    }
    else
    {
      //turn light off
      if (GetLightEntity())
        GetLightEntity().FadeOut();
    }
#endif
    //set default burn parameters based on fireplace type
    if (IsBarrelWithHoles() || IsFireplaceIndoor() || IsIndoorOven() || IsOven())
    {
      SetFuelBurnRateMP(FUEL_BURN_RATE_OVEN);
      SetTemperatureLossMP(TEMPERATURE_LOSS_MP_OVEN);
    }
    else if (HasStoneCircle())
    {
      SetFuelBurnRateMP(FUEL_BURN_RATE_STONES);
      SetTemperatureLossMP(TEMPERATURE_LOSS_MP_STONES);
    }
    else
    {
      SetFuelBurnRateMP(FUEL_BURN_RATE_DEFAULT);
      SetTemperatureLossMP(TEMPERATURE_LOSS_MP_DEFAULT);
    }
    // Oven attachments
    if (IsOven())
    {
      //lock attachment slots
      if (!m_OvenAttachmentsLockState)
        LockOvenAttachments(true);
    }
    else
    {
      //unlock attachment slots
      if (m_OvenAttachmentsLockState)
        LockOvenAttachments(false);
    }
    //VISUAL STATES
    //Fuel state
    if (GetGame().IsServer()) // SetAnimationPhase should ideally be called on server only..
    {
      // Sticks state
      if (IsItemTypeAttached(ATTACHMENT_STICKS))
        SetAnimationPhase(ANIMATION_STICKS, 0);
      else
        SetAnimationPhase(ANIMATION_STICKS, 1);
      // Firewood state
      if (IsItemTypeAttached(ATTACHMENT_FIREWOOD))
      {
        if (IsBurning() && HasAshes())
        {
          SetAnimationPhase(ANIMATION_BURNT_WOOD, 0); // Because this might not be set under certain circumstances
          SetAnimationPhase(ANIMATION_WOOD, 1);
        }
        if (IsWet() || !IsBurning())
        {
          SetAnimationPhase(ANIMATION_BURNT_WOOD, 1);
          SetAnimationPhase(ANIMATION_WOOD, 0);
        }
      }
      else
      {
        SetAnimationPhase(ANIMATION_WOOD, 1);
        SetAnimationPhase(ANIMATION_BURNT_WOOD, 1);
      }
      // Kindling state
      if (GetKindlingCount() != 0)
        SetAnimationPhase(ANIMATION_KINDLING, 0);
      else
        SetAnimationPhase(ANIMATION_KINDLING, 1);
      // Ashes state
      if (HasAshes())
        SetAnimationPhase(ANIMATION_ASHES, 0);
      else
        SetAnimationPhase(ANIMATION_ASHES, 1);
      // Stone variations
      if (HasStones())
      {
        if (HasStoneCircle())
        {
          SetAnimationPhase(ANIMATION_STONES, 0);
          SetAnimationPhase(ANIMATION_STONE, 1);
        }
        else if (IsOven())
        {
          SetAnimationPhase(ANIMATION_OVEN, 0);
          SetAnimationPhase(ANIMATION_STONE, 1);
        }
        else
        {
          SetAnimationPhase(ANIMATION_STONES, 1);
          SetAnimationPhase(ANIMATION_OVEN, 1);
          SetAnimationPhase(ANIMATION_STONE, 0);
        }
      }
      else
      {
        SetAnimationPhase(ANIMATION_STONE, 1);
      }
    }
    //refresh physics (with delay)
    GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).Call(RefreshFireplacePhysics);
  }
References ANIMATION_ASHES, ANIMATION_BURNT_WOOD, ANIMATION_KINDLING, ANIMATION_OVEN, ANIMATION_STICKS, ANIMATION_STONE, ANIMATION_STONES, ANIMATION_WOOD, ATTACHMENT_FIREWOOD, ATTACHMENT_STICKS, ATTACHMENT_STONES, CALL_CATEGORY_GAMEPLAY, vector::DistanceSq(), FUEL_BURN_RATE_DEFAULT, FUEL_BURN_RATE_OVEN, FUEL_BURN_RATE_STONES, GetGame(), GetKindlingCount(), GetLightEntity(), GetPosition, HasAshes(), HasStoneCircle(), HasStones(), FireplaceBase::IsBarrelWithHoles(), IsBurning(), FireplaceBase::IsFireplaceIndoor(), IsHologram(), FireplaceBase::IsIndoorOven(), IsItemTypeAttached(), IsOven(), IsWet(), LockOvenAttachments(), m_LightDistance, m_OvenAttachmentsLockState, FireplaceBase::RefreshFireplacePhysics(), SetFuelBurnRateMP(), SetLightEntity(), SetTemperatureLossMP(), TEMPERATURE_LOSS_MP_DEFAULT, TEMPERATURE_LOSS_MP_OVEN, and TEMPERATURE_LOSS_MP_STONES.
Referenced by EEInit(), FireplaceBase::EEItemAttached(), FireplaceBase::EEItemDetached(), OnVariablesSynchronized(), SetItemToConsume(), and Synchronize().
RefreshFireState()
void RefreshFireState () protected
Definition at line 965 of file FireplaceBase.c.
  {
    float temperature = GetTemperature();
    //if it's burning
    if (IsBurning())
    {
      //Start fire
      if (temperature <= PARAM_MIN_FIRE_TEMPERATURE)
      {
        if (GetFireState() != FireplaceFireState.START_FIRE)
          SetFireState(FireplaceFireState.START_FIRE);
      }
      //Small fire
      else if (temperature <= PARAM_SMALL_FIRE_TEMPERATURE)
      {
        if (GetFireState() != FireplaceFireState.SMALL_FIRE)
          SetFireState(FireplaceFireState.SMALL_FIRE);
      }
      //Normal fire
      else if (temperature > PARAM_SMALL_FIRE_TEMPERATURE)
      {
        if (GetFireState() != FireplaceFireState.NORMAL_FIRE)
          SetFireState(FireplaceFireState.NORMAL_FIRE);
      }
    }
  }
References GetFireState(), GetTemperature(), IsBurning(), PARAM_MIN_FIRE_TEMPERATURE, PARAM_SMALL_FIRE_TEMPERATURE, and SetFireState().
Referenced by Heating().
RemoveFromFireConsumables()
void RemoveFromFireConsumables (FireConsumable fire_consumable) protected
Definition at line 1286 of file FireplaceBase.c.
  {
    if (fire_consumable)
    {
      m_FireConsumables.Remove(fire_consumable.GetItem());
      delete fire_consumable;
    }
    CalcAndSetQuantity();
  }
References CalcAndSetQuantity(), and m_FireConsumables.
Referenced by FireplaceBase::EEItemDetached(), and SpendFireConsumable().
SetAshesState()
void SetAshesState (bool has_ashes) protected
Definition at line 1506 of file FireplaceBase.c.
  {
    m_HasAshes = has_ashes;
    if (m_HasAshes)
      SetBurntFirewood();
  }
References m_HasAshes, and SetBurntFirewood().
Referenced by SpendFireConsumable().
SetBurningState()
void SetBurningState (bool is_burning) protected
Definition at line 1494 of file FireplaceBase.c.
  {
    m_IsBurning = is_burning;
  }
References m_IsBurning.
Referenced by StartFire(), and StopFire().
SetBurntFirewood()
void SetBurntFirewood () protected
Definition at line 749 of file FireplaceBase.c.
  {
    if (GetGame().IsServer() && IsInAnimPhase(ANIMATION_WOOD))
    {
      SetAnimationPhase(ANIMATION_WOOD, 1);
      SetAnimationPhase(ANIMATION_BURNT_WOOD, 0);
    }
  }
References ANIMATION_BURNT_WOOD, ANIMATION_WOOD, GetGame(), and IsInAnimPhase().
Referenced by SetAshesState().
SetCookingEquipment()
void SetCookingEquipment (ItemBase equipment) protected
Definition at line 535 of file FireplaceBase.c.
  {
    m_CookingEquipment = equipment;
  }
References m_CookingEquipment.
Referenced by ItemBase::ClearCookingEquipment(), and ItemBase::EEItemAttached().
SetExtinguishingState()
void SetExtinguishingState () protected
Definition at line 1602 of file FireplaceBase.c.
  {
    SetFireState(FireplaceFireState.EXTINGUISHING_FIRE);
  }
References SetFireState().
SetFireState()
void SetFireState (FireplaceFireState state) protected
Definition at line 1592 of file FireplaceBase.c.
  {
    if (m_FireState != state)
    {
      m_FireState = state;
      Synchronize();
    }
  }
References m_FireState, and Synchronize().
Referenced by EEDelete(), RefreshFireState(), SetExtinguishingState(), StopCooling(), and StopFire().
SetFuelBurnRateMP()
void SetFuelBurnRateMP (float value) protected
Definition at line 1580 of file FireplaceBase.c.
  {
    m_FuelBurnRateMP = value;
  }
References m_FuelBurnRateMP.
Referenced by FireplaceBase(), and RefreshFireplaceVisuals().
SetIgniteFailure()
void SetIgniteFailure (bool failure) protected
Definition at line 2240 of file FireplaceBase.c.
  {
    m_NoIgnite = failure;
  }
References m_NoIgnite.
Referenced by FireplaceBase::IsThisIgnitionSuccessful().
SetItemToConsume()
FireConsumable SetItemToConsume () protected
Definition at line 1305 of file FireplaceBase.c.
  {
    if (m_FireConsumables.Count() == 0)
      m_ItemToConsume = null;
    else
    {
      for (int i = 0; i < m_FireConsumables.Count(); ++i)
      {
        ItemBase key = m_FireConsumables.GetKey(i);
        FireConsumable fireConsumable = m_FireConsumables.Get(key);
        if (i == 0)
          m_ItemToConsume = fireConsumable;
        else
        {
          if (fireConsumable.GetEnergy() < m_ItemToConsume.GetEnergy())
            m_ItemToConsume = fireConsumable;
        }
      }
    }
    //refresh visual
    RefreshFireplaceVisuals();
    return m_ItemToConsume;
  }
References m_FireConsumables, m_ItemToConsume, and RefreshFireplaceVisuals().
Referenced by SpendFireConsumable(), and StartFire().
SetLightEntity()
void SetLightEntity (FireplaceLight light) protected
Definition at line 2414 of file FireplaceBase.c.
  {
    m_Light = light;
  }
References m_Light.
Referenced by RefreshFireplaceVisuals().
SetOvenState()
void SetOvenState (bool is_oven) protected
Definition at line 1539 of file FireplaceBase.c.
  {
    if (m_IsOven != is_oven)
    {
      m_IsOven = is_oven;
      m_RoofAbove = is_oven;
      GetInventory().SetSlotLock(InventorySlots.GetSlotIdFromString("Stones"), is_oven);
      Synchronize();
    }
  }
References InventorySlots::GetSlotIdFromString(), m_IsOven, m_RoofAbove, and Synchronize().
SetStoneCircleState()
void SetStoneCircleState (bool has_stonecircle) protected
Definition at line 1551 of file FireplaceBase.c.
  {
    if (m_HasStoneCircle != has_stonecircle)
    {
      m_HasStoneCircle = has_stonecircle;
      GetInventory().SetSlotLock(InventorySlots.GetSlotIdFromString("Stones"), has_stonecircle);
      Synchronize();
    }
  }
References InventorySlots::GetSlotIdFromString(), m_HasStoneCircle, and Synchronize().
SetTemperatureLossMP()
void SetTemperatureLossMP (float value) protected
Definition at line 1569 of file FireplaceBase.c.
  {
    m_TemperatureLossMP = value;
  }
References m_TemperatureLossMP.
Referenced by FireplaceBase(), and RefreshFireplaceVisuals().
SmokeOnSmokingSlot()
void SmokeOnSmokingSlot (ItemBase slot_item, float temp_equip, float temp_ext) protected
Definition at line 2016 of file FireplaceBase.c.
  {
    if (m_CookingProcess == NULL)
      m_CookingProcess = new Cooking();
    // smoking slots accept only individual meat/fruit/veg items
    Edible_Base ingr = Edible_Base.Cast(slot_item);
    if (ingr)
      m_CookingProcess.SmokeItem(ingr, FireplaceBase.TIMER_HEATING_UPDATE_INTERVAL * FireplaceBase.SMOKING_SPEED);
  }
References m_CookingProcess.
Referenced by Cooling(), and Heating().
SmokingSlotsInUse()
bool SmokingSlotsInUse () protected
Definition at line 564 of file FireplaceBase.c.
  {
    for (int i = 0; i < SMOKING_SLOT_COUNT; i++)
    {
      if (m_SmokingSlots[i])
        return true;
    }
    return false;
  }
References m_SmokingSlots, and SMOKING_SLOT_COUNT.
Referenced by CanDismantleOven(), FireplaceBase::CanPutIntoHands(), Cooling(), and Heating().
SoundFireExtinguishedStart()
void SoundFireExtinguishedStart () protected
Definition at line 1229 of file FireplaceBase.c.
  {
    PlaySoundSet(m_SoundFire, SOUND_FIRE_EXTINGUISHED, 0.1, 0.1);
  }
References m_SoundFire, and SOUND_FIRE_EXTINGUISHED.
Referenced by RefreshFireParticlesAndSounds().
SoundFireExtinguishingStart()
void SoundFireExtinguishingStart () protected
Definition at line 1239 of file FireplaceBase.c.
  {
    PlaySoundSetLoop(m_SoundFireLoop, SOUND_FIRE_EXTINGUISHING, 1.0, 0.5);
  }
References m_SoundFireLoop, and SOUND_FIRE_EXTINGUISHING.
Referenced by RefreshFireParticlesAndSounds().
SoundFireHeavyStart()
void SoundFireHeavyStart () protected
Definition at line 1219 of file FireplaceBase.c.
  {
    PlaySoundSetLoop(m_SoundFireLoop, SOUND_FIRE_HEAVY, 1.0, 2.0);
  }
References m_SoundFireLoop, and SOUND_FIRE_HEAVY.
Referenced by RefreshFireParticlesAndSounds().
SoundFireLightStart()
void SoundFireLightStart () protected
Definition at line 1214 of file FireplaceBase.c.
  {
    PlaySoundSetLoop(m_SoundFireLoop, SOUND_FIRE_LIGHT, 1.0, 1.0);
  }
References m_SoundFireLoop, and SOUND_FIRE_LIGHT.
Referenced by RefreshFireParticlesAndSounds().
SoundFireNoFireStart()
void SoundFireNoFireStart () protected
Definition at line 1224 of file FireplaceBase.c.
  {
    PlaySoundSetLoop(m_SoundFireLoop, SOUND_FIRE_NO_FIRE, 2.0, 2.0);
  }
References m_SoundFireLoop, and SOUND_FIRE_NO_FIRE.
Referenced by RefreshFireParticlesAndSounds().
SoundFireStop()
void SoundFireStop () protected
Definition at line 1250 of file FireplaceBase.c.
  {
    StopSoundSet(m_SoundFireLoop);
  }
References m_SoundFireLoop.
Referenced by OnRPC(), and RefreshFireParticlesAndSounds().
SoundFireWetNoIgniteStart()
void SoundFireWetNoIgniteStart () protected
Definition at line 1234 of file FireplaceBase.c.
  {
    PlaySoundSet(m_SoundFire, SOUND_FIRE_EXTINGUISHED, 0.1, 0.1);
  }
References m_SoundFire, and SOUND_FIRE_EXTINGUISHED.
Referenced by OnRPC().
SoundFireWindyNoIgniteStart()
void SoundFireWindyNoIgniteStart () protected
Definition at line 1244 of file FireplaceBase.c.
  {
    PlaySoundSet(m_SoundFire, "ExtinguishByWind_SoundSet", 0, 0);
  }
References m_SoundFire.
Referenced by OnRPC().
SpendFireConsumable()
void SpendFireConsumable (float amount) protected
Definition at line 1341 of file FireplaceBase.c.
  {
    //spend item
    FireConsumable fireConsumable = GetItemToConsume();
    if (!fireConsumable)
    {
      //Set new item to consume
      fireConsumable = SetItemToConsume();
    }
    if (fireConsumable)
    {
      ItemBase item = fireConsumable.GetItem();
      fireConsumable.SetRemainingEnergy(fireConsumable.GetRemainingEnergy() - amount);
      if (fireConsumable.GetRemainingEnergy() <= 0 || amount == 0)
      {
        //set ashes
        if (!HasAshes())
          SetAshesState(true);
        if (item.IsAnyInherited({ItemBook, Paper, GiftWrapPaper, EyeMask_ColorBase}))
        {
          RemoveFromFireConsumables(fireConsumable);
          item.Delete();
        }
        else
        {
          //if there is nothing left, delete and remove old consumable, set new fire consumable
          if (item.GetQuantity() <= 1)
          {
            //remove item from fuel items
            RemoveFromFireConsumables(fireConsumable);
          }
          else
            fireConsumable.SetRemainingEnergy(fireConsumable.GetEnergy());
          item.AddQuantity(-1);
          SetItemToConsume();
        }
      }
    }
    CalcAndSetQuantity();
  }
References CalcAndSetQuantity(), GetItemToConsume(), HasAshes(), RemoveFromFireConsumables(), SetAshesState(), and SetItemToConsume().
Referenced by Heating(), and StopFire().
StartCooling()
void StartCooling () protected
Definition at line 1831 of file FireplaceBase.c.
  {
    if (m_HeatingTimer)
    {
      m_HeatingTimer.Stop();
      m_HeatingTimer = null;
    }
    //Start cooling
    m_CoolingTimer = new Timer(CALL_CATEGORY_GAMEPLAY);
    m_CoolingTimer.Run(TIMER_COOLING_UPDATE_INTERVAL, this, "Cooling", null, true);
  }
References CALL_CATEGORY_GAMEPLAY, m_CoolingTimer, m_HeatingTimer, and TIMER_COOLING_UPDATE_INTERVAL.
Referenced by StopFire().
StartFire()
void StartFire (bool force_start = false) protected
Definition at line 1615 of file FireplaceBase.c.
  {
    //stop cooling process if active
    if (m_CoolingTimer)
    {
      m_CoolingTimer.Stop();
      m_CoolingTimer = null;
    }
    //set under roof flag (was fire ignited under roof?)
    if (MiscGameplayFunctions.IsUnderRoof(this))
      m_RoofAbove = true;
    //start fire
    if (!IsBurning() || force_start)
    {
      SetItemToConsume();
      SetBurningState(true);
      m_UTSource.SetActive(true);
      StartHeating();
      //Update navmesh
      if (!IsFireplaceIndoor())
      {
        SetAffectPathgraph(false, true);
        GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(GetGame().UpdatePathgraphRegionByObject, 100, false, this);
      }
    }
    Synchronize();
  }
References CALL_CATEGORY_SYSTEM, GetGame(), IsBurning(), FireplaceBase::IsFireplaceIndoor(), m_CoolingTimer, m_RoofAbove, m_UTSource, SetBurningState(), SetItemToConsume(), StartHeating(), and Synchronize().
Referenced by AfterStoreLoad(), and FireplaceBase::OnIgnitedThis().
StartHeating()
void StartHeating () protected
Definition at line 1648 of file FireplaceBase.c.
  {
    //visual
    SetObjectMaterial(0, MATERIAL_FIREPLACE_GLOW);
    if (IsWindy() && !IsRoofAbove() && !IsOven() && !IsBarrelWithHoles())
    {
      StopFire();
      return;
    }
    if (GetWet() > PARAM_BURN_WET_THRESHOLD)
    {
      StopFire(FireplaceFireState.EXTINGUISHED_FIRE);
      return;
    }
    //create area damage
    if (IsBaseFireplace() && !IsOven())
      CreateAreaDamage();
    m_HeatingTimer = new Timer(CALL_CATEGORY_GAMEPLAY);
    m_HeatingTimer.Run(TIMER_HEATING_UPDATE_INTERVAL, this, "Heating", null, true);
    //Setup the noise parameters on fire start
    m_NoisePar = new NoiseParams();
    if (IsRoofAbove() || IsOven() || IsFireplaceIndoor()) //If we have a roof, we are probably inside
      m_NoisePar.LoadFromPath("CfgVehicles FireplaceBase NoiseFireplaceSpecial");
    else
      m_NoisePar.LoadFromPath("CfgVehicles FireplaceBase NoiseFireplaceBase");
  }
References CALL_CATEGORY_GAMEPLAY, FireplaceBase::CreateAreaDamage(), GetWet(), FireplaceBase::IsBarrelWithHoles(), FireplaceBase::IsBaseFireplace(), FireplaceBase::IsFireplaceIndoor(), IsOven(), IsRoofAbove(), IsWindy(), m_HeatingTimer, m_NoisePar, MATERIAL_FIREPLACE_GLOW, NoiseParams(), PARAM_BURN_WET_THRESHOLD, StopFire(), and TIMER_HEATING_UPDATE_INTERVAL.
Referenced by StartFire().
StopAllParticlesAndSounds()
void StopAllParticlesAndSounds () protected
Definition at line 932 of file FireplaceBase.c.
  {
    // go through all fireplace particles
    if (m_ParticleFireStart)
      StopParticle(m_ParticleFireStart);
    if (m_ParticleSmallFire)
      StopParticle(m_ParticleSmallFire);
    if (m_ParticleNormalFire)
      StopParticle(m_ParticleNormalFire);
    if (m_ParticleSmallSmoke)
      StopParticle(m_ParticleSmallSmoke);
    if (m_ParticleNormalSmoke)
      StopParticle(m_ParticleNormalSmoke);
    if (m_ParticleFireEnd)
      StopParticle(m_ParticleFireEnd);
    if (m_ParticleSteamEnd)
      StopParticle(m_ParticleSteamEnd);
    if (m_ParticleSteamExtinguishing)
      StopParticle(m_ParticleSteamExtinguishing);
    // go through all fireplace sounds
    if (m_SoundFireLoop)
      StopSoundSet(m_SoundFireLoop);
    if (m_SoundFire)
      StopSoundSet(m_SoundFire);
  }
References m_ParticleFireEnd, m_ParticleFireStart, m_ParticleNormalFire, m_ParticleNormalSmoke, m_ParticleSmallFire, m_ParticleSmallSmoke, m_ParticleSteamEnd, m_ParticleSteamExtinguishing, m_SoundFire, m_SoundFireLoop, and StopParticle().
Referenced by EEDelete().
StopCooling()
void StopCooling () protected
Definition at line 1932 of file FireplaceBase.c.
  {
    //stop all fire visuals
    SetFireState(FireplaceFireState.NO_FIRE);
    SetObjectMaterial(0, MATERIAL_FIREPLACE_NOGLOW);
    //Stop cooling
    m_CoolingTimer.Stop();
    m_CoolingTimer = NULL;
    //destroy area damage
    DestroyAreaDamage();
    //remove cookware audio visuals
    if (GetCookingEquipment())
    {
      Bottle_Base cooking_pot = Bottle_Base.Cast(GetCookingEquipment());
      if (cooking_pot)
        cooking_pot.RemoveAudioVisualsOnClient();
    }
    if (DirectCookingSlotsInUse())
    {
      for (int i = 0; i < DIRECT_COOKING_SLOT_COUNT; i++)
      {
        if (m_DirectCookingSlots[i])
        {
          Bottle_Base cookingpot = Bottle_Base.Cast(m_DirectCookingSlots[i]);
          if (cookingpot)
            cookingpot.RemoveAudioVisualsOnClient();
          FryingPan fryingpan = FryingPan.Cast(m_DirectCookingSlots[i]);
          if (fryingpan)
            fryingpan.RemoveAudioVisualsOnClient();
          Edible_Base itsfood = Edible_Base.Cast(m_DirectCookingSlots[i]);
          if (itsfood)
            itsfood.MakeSoundsOnClient(false);
        }
      }
    }
  }
References DestroyAreaDamage(), DIRECT_COOKING_SLOT_COUNT, DirectCookingSlotsInUse(), GetCookingEquipment(), m_CoolingTimer, m_DirectCookingSlots, MATERIAL_FIREPLACE_NOGLOW, and SetFireState().
Referenced by Cooling().
StopFire()
void StopFire (FireplaceFireState fire_state = FireplaceFireState.END_FIRE) protected
Definition at line 1804 of file FireplaceBase.c.
  {
    StopHeating();
    SpendFireConsumable(0);
    SetBurningState(false);
    StartCooling();
    SetFireState(fire_state);
    //Update navmesh
    if (!IsFireplaceIndoor())
    {
      SetAffectPathgraph(false, false);
      GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(GetGame().UpdatePathgraphRegionByObject, 100, false, this);
    }
    Synchronize();
  }
References CALL_CATEGORY_SYSTEM, GetGame(), FireplaceBase::IsFireplaceIndoor(), SetBurningState(), SetFireState(), SpendFireConsumable(), StartCooling(), StopHeating(), and Synchronize().
Referenced by Heating(), OnAction(), and StartHeating().
StopHeating()
void StopHeating () protected
Definition at line 1822 of file FireplaceBase.c.
  {
    if (!m_HeatingTimer)
      return;
    m_HeatingTimer.Stop();
    m_HeatingTimer = null;
  }
References m_HeatingTimer.
Referenced by StopFire().
StopParticle()
bool StopParticle (out Particle particle) protected
Definition at line 1013 of file FireplaceBase.c.
  {
    if (particle && GetGame() && (!GetGame().IsDedicatedServer()))
    {
      particle.Stop();
      particle = NULL;
      return true;
    }
    return false;
  }
References GetGame().
Synchronize()
void Synchronize () protected
Definition at line 455 of file FireplaceBase.c.
  {
    if (GetGame() && GetGame().IsServer())
    {
      SetSynchDirty();
      if (GetGame().IsMultiplayer() && GetGame().IsServer())
      {
        //Refresh visuals (on server)
        GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).Call(RefreshFireplaceVisuals);
      }
    }
  }
References CALL_CATEGORY_GAMEPLAY, GetGame(), and RefreshFireplaceVisuals().
TransferHeatToNearPlayers()
void TransferHeatToNearPlayers () protected
DEPRECATED.
Definition at line 2182 of file FireplaceBase.c.
{}
~FireplaceBase()
void ~FireplaceBase () protected
Definition at line 277 of file FireplaceBase.c.
  {
    DestroyAreaDamage();
    if (GetLightEntity())
      GetLightEntity().FadeOut();
  }
References DestroyAreaDamage(), and GetLightEntity().
Variable Documentation
ANIMATION_ASHES
const string ANIMATION_ASHES = "Ashes" protected
Definition at line 170 of file FireplaceBase.c.
Referenced by RefreshFireplaceVisuals().
ANIMATION_BURNT_WOOD
const string ANIMATION_BURNT_WOOD = "BurntWood" protected
Definition at line 174 of file FireplaceBase.c.
Referenced by RefreshFireplaceVisuals(), and SetBurntFirewood().
ANIMATION_CAULDRON_HANDLE
const string ANIMATION_CAULDRON_HANDLE = "handle1Rotate" protected
Definition at line 181 of file FireplaceBase.c.
Referenced by FireplaceBase::EEItemAttached(), and FireplaceBase::EEItemDetached().
ANIMATION_COOKWARE_HANDLE
const string ANIMATION_COOKWARE_HANDLE = "handleRotate" protected
Definition at line 180 of file FireplaceBase.c.
Referenced by FireplaceBase::EEItemAttached(), and FireplaceBase::EEItemDetached().
ANIMATION_INVENTORY
const string ANIMATION_INVENTORY = "Inventory" protected
Definition at line 179 of file FireplaceBase.c.
ANIMATION_KINDLING
const string ANIMATION_KINDLING = "Kindling" protected
Definition at line 171 of file FireplaceBase.c.
Referenced by RefreshFireplaceVisuals().
ANIMATION_OVEN
const string ANIMATION_OVEN = "Oven" protected
Definition at line 178 of file FireplaceBase.c.
Referenced by RefreshFireplaceVisuals(), and FireplaceBase::RefreshPhysics().
ANIMATION_STICKS
const string ANIMATION_STICKS = "Sticks" protected
Definition at line 172 of file FireplaceBase.c.
Referenced by RefreshFireplaceVisuals().
ANIMATION_STONE
const string ANIMATION_STONE = "Stone" protected
Definition at line 175 of file FireplaceBase.c.
Referenced by RefreshFireplaceVisuals().
ANIMATION_STONES
const string ANIMATION_STONES = "StonesCircle" protected
Definition at line 176 of file FireplaceBase.c.
Referenced by RefreshFireplaceVisuals().
ANIMATION_TRIPOD
const string ANIMATION_TRIPOD = "Tripod" protected
Definition at line 177 of file FireplaceBase.c.
Referenced by FireplaceBase::RefreshPhysics().
ANIMATION_WOOD
const string ANIMATION_WOOD = "Wood" protected
Definition at line 173 of file FireplaceBase.c.
Referenced by RefreshFireplaceVisuals(), and SetBurntFirewood().
ATTACHMENT_BANDAGE
ATTACHMENT_BANDAGE = BandageDressing protected
Definition at line 194 of file FireplaceBase.c.
Referenced by FireplaceBase().
ATTACHMENT_BARK_BIRCH
ATTACHMENT_BARK_BIRCH = Bark_Birch protected
Definition at line 197 of file FireplaceBase.c.
Referenced by FireplaceBase().
ATTACHMENT_BARK_OAK
ATTACHMENT_BARK_OAK = Bark_Oak protected
Definition at line 196 of file FireplaceBase.c.
Referenced by FireplaceBase().
ATTACHMENT_BOOK
ATTACHMENT_BOOK = ItemBook protected
Definition at line 195 of file FireplaceBase.c.
Referenced by FireplaceBase().
ATTACHMENT_CAULDRON
ATTACHMENT_CAULDRON = Cauldron protected
Definition at line 208 of file FireplaceBase.c.
Referenced by AddDamageToItemByFireEx(), FireplaceBase::CanLoadAttachment(), FireplaceBase::CanReceiveAttachment(), CookOnDirectSlot(), EEItemAttached(), FireplaceBase::EEItemAttached(), ItemBase::EEItemAttached(), FireplaceBase::EEItemDetached(), ItemBase::EEItemDetached(), OnAttachmentRuined(), and ItemBase::RemoveCookingAudioVisuals().
ATTACHMENT_COOKING_POT
ATTACHMENT_COOKING_POT = Pot protected
Definition at line 206 of file FireplaceBase.c.
Referenced by AddDamageToItemByFireEx(), FireplaceBase::CanLoadAttachment(), FireplaceBase::CanReceiveAttachment(), CookOnDirectSlot(), EEItemAttached(), FireplaceBase::EEItemAttached(), ItemBase::EEItemAttached(), FireplaceBase::EEItemDetached(), ItemBase::EEItemDetached(), OnAttachmentRuined(), and ItemBase::RemoveCookingAudioVisuals().
ATTACHMENT_COOKINGSTAND
ATTACHMENT_COOKINGSTAND = CookingStand protected
Definition at line 204 of file FireplaceBase.c.
Referenced by AddDamageToItemByFireEx(), and OnAttachmentRuined().
ATTACHMENT_EYEMASK_COLORBASE
ATTACHMENT_EYEMASK_COLORBASE = EyeMask_ColorBase protected
Definition at line 201 of file FireplaceBase.c.
Referenced by FireplaceBase().
ATTACHMENT_FIREWOOD
ATTACHMENT_FIREWOOD = Firewood protected
Definition at line 191 of file FireplaceBase.c.
Referenced by FireplaceBase(), and RefreshFireplaceVisuals().
ATTACHMENT_FRYING_PAN
ATTACHMENT_FRYING_PAN = FryingPan protected
Definition at line 207 of file FireplaceBase.c.
Referenced by AddDamageToItemByFireEx(), FireplaceBase::CanLoadAttachment(), FireplaceBase::CanReceiveAttachment(), CookOnDirectSlot(), EEItemAttached(), ItemBase::EEItemAttached(), FireplaceBase::EEItemDetached(), ItemBase::EEItemDetached(), OnAttachmentRuined(), and ItemBase::RemoveCookingAudioVisuals().
ATTACHMENT_GIFTWRAP
ATTACHMENT_GIFTWRAP = GiftWrapPaper protected
Definition at line 199 of file FireplaceBase.c.
Referenced by FireplaceBase().
ATTACHMENT_PAPER
ATTACHMENT_PAPER = Paper protected
Definition at line 198 of file FireplaceBase.c.
Referenced by FireplaceBase().
ATTACHMENT_PUNCHEDCARD
ATTACHMENT_PUNCHEDCARD = PunchedCard protected
Definition at line 200 of file FireplaceBase.c.
Referenced by FireplaceBase().
ATTACHMENT_RAGS
ATTACHMENT_RAGS = Rag protected
Definition at line 193 of file FireplaceBase.c.
Referenced by FireplaceBase().
ATTACHMENT_STICKS
ATTACHMENT_STICKS = WoodenStick protected
Definition at line 190 of file FireplaceBase.c.
Referenced by FireplaceBase(), and RefreshFireplaceVisuals().
ATTACHMENT_STONES
ATTACHMENT_STONES = Stone protected
Definition at line 205 of file FireplaceBase.c.
Referenced by FireplaceBase::CanLoadAttachment(), FireplaceBase::CanReceiveAttachment(), FireplaceBase::CanReleaseAttachment(), GetAttachedStonesCount(), HasStones(), and RefreshFireplaceVisuals().
ATTACHMENT_TRIPOD
ATTACHMENT_TRIPOD = Tripod protected
Definition at line 203 of file FireplaceBase.c.
Referenced by AddDamageToItemByFireEx(), FireplaceBase::CanLoadAttachment(), OnAttachmentRuined(), and FireplaceBase::RefreshPhysics().
DIRECT_COOKING_SLOT_COUNT
const int DIRECT_COOKING_SLOT_COUNT = 3 protected
direct cooking slots
update interval duration of cooling process (seconds)
Definition at line 86 of file FireplaceBase.c.
Referenced by Cooling(), DirectCookingSlotsInUse(), Heating(), and StopCooling().
DIRECT_COOKING_SPEED
const float DIRECT_COOKING_SPEED = 1.5 protected
Definition at line 87 of file FireplaceBase.c.
FUEL_BURN_RATE_DEFAULT
const float FUEL_BURN_RATE_DEFAULT = 1.0 protected
Definition at line 74 of file FireplaceBase.c.
Referenced by FireplaceBase(), and RefreshFireplaceVisuals().
FUEL_BURN_RATE_OVEN
const float FUEL_BURN_RATE_OVEN = 0.85 protected
Definition at line 76 of file FireplaceBase.c.
Referenced by RefreshFireplaceVisuals().
FUEL_BURN_RATE_STONES
const float FUEL_BURN_RATE_STONES = 0.92 protected
Definition at line 75 of file FireplaceBase.c.
Referenced by RefreshFireplaceVisuals().
IGNITE_WIND_THRESHOLD
const float IGNITE_WIND_THRESHOLD = 0.8 protected
Definition at line 95 of file FireplaceBase.c.
LIFETIME_FIREPLACE_STONE_CIRCLE
const int LIFETIME_FIREPLACE_STONE_CIRCLE = 172800 protected
Definition at line 92 of file FireplaceBase.c.
LIFETIME_FIREPLACE_STONE_OVEN
const int LIFETIME_FIREPLACE_STONE_OVEN = 604800 protected
Definition at line 93 of file FireplaceBase.c.
m_AreaDamage
ref AreaDamageManager m_AreaDamage protected
Definition at line 214 of file FireplaceBase.c.
Referenced by CreateAreaDamage(), FireplaceBase::CreateAreaDamage(), ItemBase::CreateDamageTrigger(), ItemBase::CreateElectrifiedDamageTrigger(), DestroyAreaDamage(), ItemBase::DestroyDamageTrigger(), and OnVariablesSynchronized().
m_CanNoise
bool m_CanNoise = true private
Definition at line 221 of file FireplaceBase.c.
Referenced by Heating().
m_ClutterCutter
Object m_ClutterCutter protected
Definition at line 211 of file FireplaceBase.c.
Referenced by FireplaceBase::AfterStoreLoad(), ItemBase::DestroyClutterCutter(), GardenBase::EEDelete(), GardenBase::OnPlacementComplete(), OnPlacementComplete(), TentBase::OnPlacementComplete(), GardenBase::OnStoreLoad(), and ItemBase::OnStoreLoad().
m_CookingEquipment
ItemBase m_CookingEquipment protected
Definition at line 106 of file FireplaceBase.c.
Referenced by CookWithEquipment(), Cooling(), GetCookingEquipment(), ItemBase::GetCookingEquipment(), Heating(), SetCookingEquipment(), and ItemBase::SetCookingEquipment().
m_CookingProcess
ref Cooking m_CookingProcess protected
determines how fast will the fuel item burn before spending (lower is better)
Definition at line 40 of file FireplaceBase.c.
Referenced by ClearCookingEquipment(), ItemBase::ClearCookingEquipment(), CookOnDirectSlot(), CookWithEquipment(), ItemBase::CookWithEquipment(), GetCookingProcess(), ItemBase::OnSwitchOff(), and SmokeOnSmokingSlot().
m_CoolingTimer
ref Timer m_CoolingTimer protected
Definition at line 99 of file FireplaceBase.c.
Referenced by AddDamageToItemByFireEx(), StartCooling(), StartFire(), and StopCooling().
m_DirectCookingSlots
ItemBase m_DirectCookingSlots[DIRECT_COOKING_SLOT_COUNT] protected
Definition at line 107 of file FireplaceBase.c.
Referenced by Cooling(), DirectCookingSlotsInUse(), FireplaceBase::EEItemAttached(), FireplaceBase::EEItemDetached(), Heating(), and StopCooling().
m_FireConsumables
ref map<ItemBase, ref FireConsumable> m_FireConsumables protected
Definition at line 149 of file FireplaceBase.c.
Referenced by AddToFireConsumables(), CalcAndSetQuantity(), FireplaceBase(), GetFireConsumableByItem(), Heating(), RemoveFromFireConsumables(), and SetItemToConsume().
m_FireConsumableTypes
ref map<typename, ref FireConsumableType> m_FireConsumableTypes static protected
Definition at line 148 of file FireplaceBase.c.
Referenced by CalcAndSetTotalEnergy(), FireplaceBase(), GetFireConsumableTypeEnergy(), IsFuel(), and IsKindling().
m_FireState
FireplaceFireState m_FireState = FireplaceFireState.NO_FIRE protected
Definition at line 31 of file FireplaceBase.c.
Referenced by GetFireState(), and SetFireState().
m_FuelBurnRateMP
float m_FuelBurnRateMP = 1.0 protected
determines how fast will the fireplace loose its temperature when cooling (lower is better)
Definition at line 37 of file FireplaceBase.c.
Referenced by GetFuelBurnRateMP(), OnStoreLoad(), OnStoreSave(), and SetFuelBurnRateMP().
m_HalfExtents
vector m_HalfExtents protected
Definition at line 33 of file FireplaceBase.c.
m_HasAshes
bool m_HasAshes = false protected
Definition at line 25 of file FireplaceBase.c.
Referenced by HasAshes(), OnStoreLoad(), OnStoreSave(), and SetAshesState().
m_HasStoneCircle
bool m_HasStoneCircle = false protected
Definition at line 27 of file FireplaceBase.c.
Referenced by HasStoneCircle(), FireplaceBase::OnStoreLoad(), FireplaceBase::OnStoreSave(), and SetStoneCircleState().
m_HeatingTimer
ref Timer m_HeatingTimer protected
Definition at line 98 of file FireplaceBase.c.
Referenced by AddDamageToItemByFireEx(), StartCooling(), StartHeating(), and StopHeating().
m_IsBurning
enum FireplaceFireState m_IsBurning = false
Referenced by IsBurning(), OnStoreLoad(), OnStoreSave(), OnVariablesSynchronized(), and SetBurningState().
m_IsOven
bool m_IsOven = false protected
Definition at line 26 of file FireplaceBase.c.
Referenced by IsOven(), FireplaceBase::OnStoreLoad(), FireplaceBase::OnStoreSave(), and SetOvenState().
m_ItemToConsume
ref FireConsumable m_ItemToConsume protected
Definition at line 109 of file FireplaceBase.c.
Referenced by GetItemToConsume(), and SetItemToConsume().
m_LastFireState
FireplaceFireState m_LastFireState = FireplaceFireState.NO_FIRE protected
Definition at line 32 of file FireplaceBase.c.
Referenced by RefreshFireParticlesAndSounds().
m_Light
FireplaceLight m_Light protected
Definition at line 102 of file FireplaceBase.c.
m_LightDistance
float m_LightDistance = 2000 protected
Definition at line 103 of file FireplaceBase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), and RefreshFireplaceVisuals().
m_NoIgnite
bool m_NoIgnite = false protected
Definition at line 29 of file FireplaceBase.c.
Referenced by GetIgniteFailure(), and SetIgniteFailure().
m_NoisePar
ref NoiseParams m_NoisePar protected
Definition at line 220 of file FireplaceBase.c.
m_OvenAttachmentsLockState
int m_OvenAttachmentsLockState = -1 protected
Definition at line 30 of file FireplaceBase.c.
Referenced by LockOvenAttachments(), and RefreshFireplaceVisuals().
m_ParticleFireEnd
Particle m_ParticleFireEnd protected
Definition at line 130 of file FireplaceBase.c.
Referenced by ParticleFireEndStart(), ParticleFireEndStop(), ParticleFireWindyNoIgniteStart(), and StopAllParticlesAndSounds().
m_ParticleFireStart
Particle m_ParticleFireStart protected
Definition at line 125 of file FireplaceBase.c.
Referenced by ParticleFireStartStart(), ParticleFireStartStop(), and StopAllParticlesAndSounds().
m_ParticleNormalFire
Particle m_ParticleNormalFire protected
Definition at line 127 of file FireplaceBase.c.
Referenced by ParticleNormalFireStart(), ParticleNormalFireStop(), and StopAllParticlesAndSounds().
m_ParticleNormalSmoke
Particle m_ParticleNormalSmoke protected
Definition at line 129 of file FireplaceBase.c.
Referenced by ParticleNormalSmokeStart(), FireplaceBase::ParticleNormalSmokeStart(), ParticleNormalSmokeStop(), and StopAllParticlesAndSounds().
m_ParticleSmallFire
Particle m_ParticleSmallFire protected
Definition at line 126 of file FireplaceBase.c.
Referenced by ParticleSmallFireStart(), ParticleSmallFireStop(), and StopAllParticlesAndSounds().
m_ParticleSmallSmoke
Particle m_ParticleSmallSmoke protected
Definition at line 128 of file FireplaceBase.c.
Referenced by ParticleSmallSmokeStart(), FireplaceBase::ParticleSmallSmokeStart(), ParticleSmallSmokeStop(), and StopAllParticlesAndSounds().
m_ParticleSteamEnd
Particle m_ParticleSteamEnd protected
Definition at line 131 of file FireplaceBase.c.
Referenced by ParticleSteamEndStart(), ParticleSteamEndStop(), ParticleWetNoIgniteStart(), ParticleWetNoIgniteStop(), and StopAllParticlesAndSounds().
m_ParticleSteamExtinguishing
Particle m_ParticleSteamExtinguishing protected
Definition at line 132 of file FireplaceBase.c.
Referenced by ParticleSteamExtinguishingStart(), ParticleSteamExtinguishingStop(), and StopAllParticlesAndSounds().
m_RoofAbove
bool m_RoofAbove = false protected
Definition at line 28 of file FireplaceBase.c.
Referenced by FireplaceBase::Close(), FireplaceBase::CloseLoad(), FireplaceBase::FireplaceIndoor(), IsRoofAbove(), FireplaceBase::Open(), FireplaceBase::OpenLoad(), FireplaceBase::OvenIndoor(), SetOvenState(), and StartFire().
m_SmokingSlots
ItemBase m_SmokingSlots[SMOKING_SLOT_COUNT] protected
Definition at line 108 of file FireplaceBase.c.
Referenced by Cooling(), FireplaceBase::EEItemAttached(), FireplaceBase::EEItemDetached(), Heating(), and SmokingSlotsInUse().
m_SoundFire
EffectSound m_SoundFire protected
Definition at line 143 of file FireplaceBase.c.
Referenced by SoundFireExtinguishedStart(), SoundFireWetNoIgniteStart(), SoundFireWindyNoIgniteStart(), and StopAllParticlesAndSounds().
m_SoundFireLoop
EffectSound m_SoundFireLoop protected
Definition at line 142 of file FireplaceBase.c.
Referenced by BuildingSuper::EEDelete(), BuildingSuper::EEInit(), SoundFireExtinguishingStart(), SoundFireHeavyStart(), SoundFireLightStart(), SoundFireNoFireStart(), SoundFireStop(), and StopAllParticlesAndSounds().
m_TemperatureLossMP
float m_TemperatureLossMP = 1.0 protected
Definition at line 36 of file FireplaceBase.c.
Referenced by GetTemperatureLossMP(), OnStoreLoad(), OnStoreSave(), and SetTemperatureLossMP().
m_TotalEnergy
float m_TotalEnergy protected
Definition at line 217 of file FireplaceBase.c.
Referenced by CalcAndSetQuantity(), and CalcAndSetTotalEnergy().
m_UTSLFireplace
ref UniversalTemperatureSourceLambdaFireplace m_UTSLFireplace protected
Definition at line 226 of file FireplaceBase.c.
Referenced by AddWetnessToFireplace(), Cooling(), EEInit(), and Heating().
m_UTSource
ref UniversalTemperatureSource m_UTSource protected
Definition at line 224 of file FireplaceBase.c.
Referenced by Cooling(), BuildingSuper::EEDelete(), BuildingSuper::EEInit(), EEInit(), ItemBase::EEInit(), CarScript::EEInit(), CarScript::EOnPostSimulate(), Heating(), CarScript::OnEngineStart(), CarScript::OnEngineStop(), ItemBase::OnSwitchOff(), ItemBase::OnSwitchOn(), ItemBase::OnWork(), ItemBase::OnWorkStart(), ItemBase::OnWorkStop(), and StartFire().
m_UTSSettings
ref UniversalTemperatureSourceSettings m_UTSSettings protected
Definition at line 225 of file FireplaceBase.c.
Referenced by Cooling(), BuildingSuper::EEInit(), EEInit(), ItemBase::EEInit(), CarScript::EEInit(), CarScript::EOnPostSimulate(), Heating(), and ItemBase::OnWork().
MATERIAL_FIREPLACE_GLOW
const string MATERIAL_FIREPLACE_GLOW = "dz\\gear\\cooking\\data\\stoneground.rvmat" protected
Definition at line 185 of file FireplaceBase.c.
Referenced by StartHeating().
MATERIAL_FIREPLACE_NOGLOW
const string MATERIAL_FIREPLACE_NOGLOW = "dz\\gear\\cooking\\data\\stonegroundnoemit.rvmat" protected
Definition at line 186 of file FireplaceBase.c.
Referenced by StopCooling().
MAX_TEMPERATURE_TO_DISMANTLE_OVEN
const int MAX_TEMPERATURE_TO_DISMANTLE_OVEN = 40 protected
minimum amount of stones for oven
Definition at line 67 of file FireplaceBase.c.
Referenced by CanDismantleOven().
MESSAGE_BURY_ASHES_FAILED_BURNING
const string MESSAGE_BURY_ASHES_FAILED_BURNING = "Cannot bury ashes, the fireplace is still burning." protected
Definition at line 164 of file FireplaceBase.c.
MESSAGE_BURY_ASHES_FAILED_NOT_EMPTY
const string MESSAGE_BURY_ASHES_FAILED_NOT_EMPTY = "Cannot bury ashes. There are sill items in it." protected
Definition at line 162 of file FireplaceBase.c.
MESSAGE_BURY_ASHES_FAILED_SURFACE
const string MESSAGE_BURY_ASHES_FAILED_SURFACE = "Cannot bury ashes on hard surface." protected
Definition at line 163 of file FireplaceBase.c.
MESSAGE_BURY_ASHES_FAILED_TOO_HOT
const string MESSAGE_BURY_ASHES_FAILED_TOO_HOT = "Cannot bury ashes, the fireplace is too hot." protected
Definition at line 165 of file FireplaceBase.c.
MESSAGE_CANNOT_BUILD_OVEN
const string MESSAGE_CANNOT_BUILD_OVEN = "Cannot build oven." protected
Definition at line 166 of file FireplaceBase.c.
MESSAGE_CANNOT_DISMANTLE_OVEN
const string MESSAGE_CANNOT_DISMANTLE_OVEN = "Cannot dismantle oven." protected
Definition at line 167 of file FireplaceBase.c.
MESSAGE_IGNITE_IGNIT_ITEM_DAMAGED
const string MESSAGE_IGNITE_IGNIT_ITEM_DAMAGED = "You cannot start fire. Fireplace is ruined." protected
Definition at line 152 of file FireplaceBase.c.
MESSAGE_IGNITE_IN_WATER
const string MESSAGE_IGNITE_IN_WATER = "I cannot ignite the fireplace in the water." protected
Definition at line 157 of file FireplaceBase.c.
MESSAGE_IGNITE_NO_KINDLING
const string MESSAGE_IGNITE_NO_KINDLING = "There needs to be some kindling to start a fire." protected
Definition at line 153 of file FireplaceBase.c.
MESSAGE_IGNITE_RAIN
const string MESSAGE_IGNITE_RAIN = "The fire went out because of the rain." protected
Definition at line 155 of file FireplaceBase.c.
MESSAGE_IGNITE_TOO_WET
const string MESSAGE_IGNITE_TOO_WET = "The fireplace is too wet to be ignited." protected
Definition at line 154 of file FireplaceBase.c.
MESSAGE_IGNITE_UNDER_LOW_ROOF
const string MESSAGE_IGNITE_UNDER_LOW_ROOF = "I cannot ignite the fireplace here, the is not enough room." protected
Definition at line 158 of file FireplaceBase.c.
MESSAGE_IGNITE_WIND
const string MESSAGE_IGNITE_WIND = "The fire went out because of the wind." protected
Definition at line 156 of file FireplaceBase.c.
MESSAGE_REIGNITE_NO_KINDLING
const string MESSAGE_REIGNITE_NO_KINDLING = "There needs to be some kindling to start a fire." protected
Definition at line 159 of file FireplaceBase.c.
MESSAGE_REIGNITE_RAIN
const string MESSAGE_REIGNITE_RAIN = "Cannot reignite fireplace in rain." protected
Definition at line 160 of file FireplaceBase.c.
MESSAGE_REIGNITE_TOO_WET
const string MESSAGE_REIGNITE_TOO_WET = "The fireplace is too wet to be reignited." protected
Definition at line 161 of file FireplaceBase.c.
MIN_CEILING_HEIGHT
const float MIN_CEILING_HEIGHT = 5 protected
maximum temperature for dismantling oven
Definition at line 68 of file FireplaceBase.c.
Referenced by GetCeilingHeight().
MIN_STONES_TO_BUILD_CIRCLE
const int MIN_STONES_TO_BUILD_CIRCLE = 8 protected
maximum value for temperature that will be transfered to player (environment)
Definition at line 65 of file FireplaceBase.c.
Referenced by CanBuildStoneCircle().
MIN_STONES_TO_BUILD_OVEN
const int MIN_STONES_TO_BUILD_OVEN = 16 protected
minimum amount of stones for circle
Definition at line 66 of file FireplaceBase.c.
Referenced by CanBuildOven().
OBJECT_CLUTTER_CUTTER
const string OBJECT_CLUTTER_CUTTER = "ClutterCutterFireplace" protected
Definition at line 210 of file FireplaceBase.c.
Referenced by FireplaceBase::AfterStoreLoad(), FireplaceBase::OnIgnitedThis(), and OnPlacementComplete().
PARAM_BURN_DAMAGE_COEF
const float PARAM_BURN_DAMAGE_COEF = 5.0 protected
base value of fire consumption rate (how many base energy will be spent on each update)
Definition at line 56 of file FireplaceBase.c.
PARAM_BURN_WET_THRESHOLD
const float PARAM_BURN_WET_THRESHOLD = 0.40 protected
maximum rain value when the fireplace can be ignited
Definition at line 51 of file FireplaceBase.c.
Referenced by Heating(), and StartHeating().
PARAM_COOKING_EQUIP_MAX_TEMP
const float PARAM_COOKING_EQUIP_MAX_TEMP = 250 protected
temperature threshold for starting coooking process (degree Celsius)
Definition at line 80 of file FireplaceBase.c.
Referenced by CookOnDirectSlot(), Heating(), and ItemBase::OnWork().
PARAM_COOKING_EQUIP_TEMP_INCREASE
const float PARAM_COOKING_EQUIP_TEMP_INCREASE = 10 protected
maximum temperature of attached cooking equipment (degree Celsius)
Definition at line 81 of file FireplaceBase.c.
Referenced by CookOnDirectSlot(), Heating(), and ItemBase::OnWork().
PARAM_COOKING_TEMP_THRESHOLD
const float PARAM_COOKING_TEMP_THRESHOLD = 100 protected
cooking
Definition at line 79 of file FireplaceBase.c.
Referenced by CanCookOnStick(), Cooling(), Heating(), and ItemBase::OnWork().
PARAM_FIRE_CONSUM_RATE_AMOUNT
const float PARAM_FIRE_CONSUM_RATE_AMOUNT = 0.5 protected
value for calculating wetness loss during cooling process
Definition at line 55 of file FireplaceBase.c.
Referenced by Heating().
PARAM_FULL_HEAT_RADIUS
const float PARAM_FULL_HEAT_RADIUS = 2.0 protected
maximum value of temperature of items in fireplace when heating (degree Celsius)
Definition at line 60 of file FireplaceBase.c.
Referenced by BuildingSuper::EEInit(), and EEInit().
PARAM_HEAT_RADIUS
const float PARAM_HEAT_RADIUS = 4.0 protected
radius in which objects are fully heated by fire
Definition at line 61 of file FireplaceBase.c.
Referenced by BuildingSuper::EEInit(), and EEInit().
PARAM_HEAT_THROUGH_AIR_COEF
const float PARAM_HEAT_THROUGH_AIR_COEF = 0.1 protected
radius in which objects are heated by fire
Definition at line 62 of file FireplaceBase.c.
PARAM_IGNITE_RAIN_THRESHOLD
const float PARAM_IGNITE_RAIN_THRESHOLD = 0.1 protected
minimum fireplace temperature under which the fireplace can be reignited using air only (degree Celsius)
Definition at line 50 of file FireplaceBase.c.
PARAM_ITEM_HEAT_MIN_TEMP
const float PARAM_ITEM_HEAT_MIN_TEMP = 40 protected
value for calculating temperature increase on each heat update interval (degree Celsius)
Definition at line 58 of file FireplaceBase.c.
Referenced by AddDamageToItemByFireEx(), AddTemperatureToItemByFire(), CookOnDirectSlot(), and Heating().
PARAM_ITEM_HEAT_TEMP_INCREASE_COEF
const float PARAM_ITEM_HEAT_TEMP_INCREASE_COEF = 10 protected
value for calculating damage on items located in fireplace cargo
Definition at line 57 of file FireplaceBase.c.
Referenced by AddTemperatureToItemByFire().
PARAM_MAX_ITEM_HEAT_TEMP_INCREASE
const float PARAM_MAX_ITEM_HEAT_TEMP_INCREASE = 200 protected
minimum temperature for items that can be heated in fireplace cargo or as attachments (degree Celsius)
Definition at line 59 of file FireplaceBase.c.
Referenced by AddTemperatureToItemByFire().
PARAM_MAX_TRANSFERED_TEMPERATURE
const float PARAM_MAX_TRANSFERED_TEMPERATURE = 25 protected
DEPRECATED value for calculation of heat transfered from fireplace through air to player (environment)
Definition at line 63 of file FireplaceBase.c.
Referenced by BuildingSuper::EEInit(), and EEInit().
PARAM_MAX_WET_TO_IGNITE
const float PARAM_MAX_WET_TO_IGNITE = 0.2 protected
how much will temperature decrease when fireplace is cooling (degree Celsius per second)
Definition at line 48 of file FireplaceBase.c.
PARAM_MIN_FIRE_TEMPERATURE
const float PARAM_MIN_FIRE_TEMPERATURE = 30 protected
maximum fireplace temperature of a normal fire (degree Celsius)
Definition at line 45 of file FireplaceBase.c.
Referenced by AddWetnessToFireplace(), and RefreshFireState().
PARAM_MIN_TEMP_TO_REIGNITE
const float PARAM_MIN_TEMP_TO_REIGNITE = 30 protected
maximum wetness value when the fireplace can be ignited
Definition at line 49 of file FireplaceBase.c.
PARAM_NORMAL_FIRE_TEMPERATURE
const float PARAM_NORMAL_FIRE_TEMPERATURE = 1000 protected
maximum fireplace temperature of a small fire (degree Celsius)
Definition at line 44 of file FireplaceBase.c.
Referenced by AddWetnessToFireplace(), and EEInit().
PARAM_SMALL_FIRE_TEMPERATURE
const float PARAM_SMALL_FIRE_TEMPERATURE = 150 protected
Definition at line 43 of file FireplaceBase.c.
Referenced by CookOnDirectSlot(), EEInit(), Heating(), and RefreshFireState().
PARAM_TEMPERATURE_DECREASE
const float PARAM_TEMPERATURE_DECREASE = 3 protected
how much will temperature increase when fireplace is burning (degree Celsius per second)
Definition at line 47 of file FireplaceBase.c.
Referenced by Cooling().
PARAM_TEMPERATURE_INCREASE
const float PARAM_TEMPERATURE_INCREASE = 3 protected
minimum fireplace temperature under which the fireplace is inactive (degree Celsius)
Definition at line 46 of file FireplaceBase.c.
Referenced by Heating().
PARAM_WET_COOLING_DECREASE_COEF
const float PARAM_WET_COOLING_DECREASE_COEF = 0.002 protected
value for calculating wetness loss during heating process
Definition at line 54 of file FireplaceBase.c.
Referenced by Cooling().
PARAM_WET_HEATING_DECREASE_COEF
const float PARAM_WET_HEATING_DECREASE_COEF = 0.01 protected
value for calculating of wetness that fireplace gain when raining
Definition at line 53 of file FireplaceBase.c.
Referenced by BurnItemsInFireplace(), and Heating().
PARAM_WET_INCREASE_COEF
const float PARAM_WET_INCREASE_COEF = 0.02 protected
maximum wetness value when the fireplace is able to burn
Definition at line 52 of file FireplaceBase.c.
Referenced by Cooling(), and Heating().
PARTICLE_FIRE_END
int PARTICLE_FIRE_END = ParticleList.CAMP_FIRE_END protected
Definition at line 119 of file FireplaceBase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::Fireplace(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), and ParticleFireEndStart().
PARTICLE_FIRE_START
int PARTICLE_FIRE_START = ParticleList.CAMP_FIRE_START protected
Definition at line 112 of file FireplaceBase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::Fireplace(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), and ParticleFireStartStart().
PARTICLE_NO_IGNITE_WIND
int PARTICLE_NO_IGNITE_WIND = ParticleList.CAMP_NO_IGNITE_WIND protected
Definition at line 123 of file FireplaceBase.c.
Referenced by ParticleFireWindyNoIgniteStart().
PARTICLE_NORMAL_FIRE
int PARTICLE_NORMAL_FIRE = ParticleList.CAMP_NORMAL_FIRE protected
Definition at line 115 of file FireplaceBase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::Fireplace(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), and ParticleNormalFireStart().
PARTICLE_NORMAL_SMOKE
int PARTICLE_NORMAL_SMOKE = ParticleList.CAMP_NORMAL_SMOKE protected
Definition at line 118 of file FireplaceBase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::Fireplace(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), ParticleNormalSmokeStart(), and FireplaceBase::ParticleNormalSmokeStart().
PARTICLE_OVEN_FIRE
int PARTICLE_OVEN_FIRE = ParticleList.CAMP_STOVE_FIRE protected
Definition at line 116 of file FireplaceBase.c.
Referenced by ParticleNormalFireStart(), and ParticleSmallFireStart().
PARTICLE_OVEN_FIRE_END
int PARTICLE_OVEN_FIRE_END = ParticleList.CAMP_STOVE_FIRE_END protected
Definition at line 120 of file FireplaceBase.c.
Referenced by ParticleFireEndStart(), and ParticleFireWindyNoIgniteStart().
PARTICLE_OVEN_FIRE_START
int PARTICLE_OVEN_FIRE_START = ParticleList.CAMP_STOVE_FIRE_START protected
Definition at line 113 of file FireplaceBase.c.
Referenced by ParticleFireStartStart().
PARTICLE_SMALL_FIRE
int PARTICLE_SMALL_FIRE = ParticleList.CAMP_SMALL_FIRE protected
Definition at line 114 of file FireplaceBase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::Fireplace(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), and ParticleSmallFireStart().
PARTICLE_SMALL_SMOKE
int PARTICLE_SMALL_SMOKE = ParticleList.CAMP_SMALL_SMOKE protected
Definition at line 117 of file FireplaceBase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::Fireplace(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), ParticleSmallSmokeStart(), and FireplaceBase::ParticleSmallSmokeStart().
PARTICLE_STEAM_END
int PARTICLE_STEAM_END = ParticleList.CAMP_STEAM_2END protected
Definition at line 121 of file FireplaceBase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::Fireplace(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), ParticleSteamEndStart(), and ParticleWetNoIgniteStart().
PARTICLE_STEAM_EXTINGUISHING
int PARTICLE_STEAM_EXTINGUISHING = ParticleList.CAMP_STEAM_EXTINGUISH_START protected
Definition at line 122 of file FireplaceBase.c.
Referenced by ParticleSteamExtinguishingStart().
SMOKING_SLOT_COUNT
const int SMOKING_SLOT_COUNT = 4 protected
Definition at line 88 of file FireplaceBase.c.
Referenced by Cooling(), Heating(), and SmokingSlotsInUse().
SMOKING_SPEED
const float SMOKING_SPEED = 1 protected
Definition at line 89 of file FireplaceBase.c.
SOUND_FIRE_EXTINGUISHED
const string SOUND_FIRE_EXTINGUISHED = "ExtinguishByWaterEnd_SoundSet" protected
Definition at line 139 of file FireplaceBase.c.
Referenced by SoundFireExtinguishedStart(), and SoundFireWetNoIgniteStart().
SOUND_FIRE_EXTINGUISHING
const string SOUND_FIRE_EXTINGUISHING = "ExtinguishByWater_SoundSet" protected
Definition at line 138 of file FireplaceBase.c.
Referenced by SoundFireExtinguishingStart().
SOUND_FIRE_HEAVY
const string SOUND_FIRE_HEAVY = "HeavyFire_SoundSet" protected
Definition at line 135 of file FireplaceBase.c.
Referenced by SoundFireHeavyStart().
SOUND_FIRE_LIGHT
const string SOUND_FIRE_LIGHT = "LightFire_SoundSet" protected
Definition at line 136 of file FireplaceBase.c.
Referenced by SoundFireLightStart().
SOUND_FIRE_NO_FIRE
const string SOUND_FIRE_NO_FIRE = "NoFuelFire_SoundSet" protected
Definition at line 137 of file FireplaceBase.c.
Referenced by SoundFireNoFireStart().
TEMPERATURE_LOSS_MP_DEFAULT
const float TEMPERATURE_LOSS_MP_DEFAULT = 1.0 protected
min height of ceiling for fire to be ignited
Definition at line 70 of file FireplaceBase.c.
Referenced by FireplaceBase(), and RefreshFireplaceVisuals().
TEMPERATURE_LOSS_MP_OVEN
const float TEMPERATURE_LOSS_MP_OVEN = 0.75 protected
Definition at line 72 of file FireplaceBase.c.
Referenced by RefreshFireplaceVisuals().
TEMPERATURE_LOSS_MP_STONES
const float TEMPERATURE_LOSS_MP_STONES = 0.90 protected
Definition at line 71 of file FireplaceBase.c.
Referenced by RefreshFireplaceVisuals().
TIMER_COOLING_UPDATE_INTERVAL
const int TIMER_COOLING_UPDATE_INTERVAL = 2 protected
update interval duration of heating process (seconds)
Definition at line 84 of file FireplaceBase.c.
Referenced by AddDamageToItemByFireEx(), Cooling(), and StartCooling().
TIMER_HEATING_UPDATE_INTERVAL
const int TIMER_HEATING_UPDATE_INTERVAL = 3 protected
how much will temperature increase when attached on burning fireplace (degree Celsius)
Definition at line 83 of file FireplaceBase.c.
Referenced by AddDamageToItemByFireEx(), BuildingSuper::EEInit(), Heating(), and StartHeating().
WET
enum FireplaceFireState WET = 1
WIND
enum FireplaceFireState WIND = 0