DayZ: ActionEmptyBottleBase Class Reference
ActionEmptyBottleBase Class Reference
Protected Member Functions
void SendRPC (ActionData actionData, bool enable)
Private Member Functions
void ActionEmptyBottleBase ()
override void CreateConditionComponents ()
override bool HasTarget ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override void OnStartAnimationLoop (ActionData action_data)
override void OnEndAnimationLoop (ActionData action_data)
override void OnEndServer (ActionData action_data)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 14 of file ActionEmptyBottleBase.c.
Constructor & Destructor Documentation
ActionEmptyBottleBase()
void ActionEmptyBottleBase::ActionEmptyBottleBase () inline private
Definition at line 16 of file ActionEmptyBottleBase.c.
  {
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_EMPTY_VESSEL;
    m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
    m_CallbackClass = ActionEmptyBottleBaseCB;
    m_FullBody = false;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
    m_Text = "#empty";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionEmptyBottleBase::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 38 of file ActionEmptyBottleBase.c.
  {
    if (GetGame().IsServer() && GetGame().IsMultiplayer())
      return true;
    if (item.IsLiquidPresent())
      return true;
    return false;
  }
References GetGame().
ActionConditionContinue()
override bool ActionEmptyBottleBase::ActionConditionContinue (ActionData action_data) inline private
Definition at line 48 of file ActionEmptyBottleBase.c.
  {
    if (action_data.m_MainItem.GetQuantity() > action_data.m_MainItem.GetQuantityMin())
      return true;
    return false;
  }
CreateConditionComponents()
override void ActionEmptyBottleBase::CreateConditionComponents () inline private
Definition at line 27 of file ActionEmptyBottleBase.c.
  {
    m_ConditionItem = new CCINotRuinedAndEmpty;
    m_ConditionTarget = new CCTNone;
  }
References m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool ActionEmptyBottleBase::HasTarget () inline private
Definition at line 33 of file ActionEmptyBottleBase.c.
  {
    return false;
  }
OnEndAnimationLoop()
override void ActionEmptyBottleBase::OnEndAnimationLoop (ActionData action_data) inline private
Definition at line 60 of file ActionEmptyBottleBase.c.
  {
    SendRPC(action_data, false);
  }
References SendRPC().
OnEndServer()
override void ActionEmptyBottleBase::OnEndServer (ActionData action_data) inline private
Definition at line 65 of file ActionEmptyBottleBase.c.
  {
    SendRPC(action_data, false);
  }
References SendRPC().
OnStartAnimationLoop()
override void ActionEmptyBottleBase::OnStartAnimationLoop (ActionData action_data) inline private
Definition at line 55 of file ActionEmptyBottleBase.c.
  {
    SendRPC(action_data, true);
  }
References SendRPC().
SendRPC()
void ActionEmptyBottleBase::SendRPC (ActionData actionData, bool enable) inline protected
Definition at line 70 of file ActionEmptyBottleBase.c.
  {
    if (!GetGame().IsMultiplayer() || GetGame().IsServer())
    {
      ActionEmptyBottleBaseCB comp = ActionEmptyBottleBaseCB.Cast(actionData.m_Callback);
      if (comp.m_RPCStopAlreadySent)
        return;
      Bottle_Base target_vessel = Bottle_Base.Cast(actionData.m_MainItem);
      Param1<bool> play = new Param1<bool>(enable);
      GetGame().RPCSingleParam(target_vessel, SoundTypeBottle.EMPTYING, play, true);
      if (!enable)
        comp.m_RPCStopAlreadySent = true;
    }
  }
References GetGame().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionEmptyBottleBase.c