DayZ: PointLightBase Class Reference
PointLightBase Class Reference
Protected Member Functions
void Roadblock_Light ()
void EntranceLight ()
Protected Attributes
float m_DefaultBrightness = 5.5
float m_DefaultRadius = 20
Private Member Functions
void AnniversaryBoxLight ()
void BonfireLight ()
override void OnFrameLightSource (IEntity other, float timeSlice)
void BrightnessTestLight ()
override void OnFrameLightSource (IEntity other, float timeSlice)
void ChemlightLight ()
void SetIntensity (float coef, float time)
void SetColorToWhite ()
void SetColorToRed ()
void SetColorToGreen ()
void SetColorToBlue ()
void SetColorToYellow ()
void FireplaceLight ()
void SetInteriorMode ()
void SetExteriorMode ()
void FlareLight ()
void GoatLight ()
void MuzzleFlashLight ()
void MuzzleFlashLight_2 ()
void PartyLight ()
override void OnFrameLightSource (IEntity other, float timeSlice)
void PersonalLight ()
override void OnFrameLightSource (IEntity other, float timeSlice)
void PortableGasLampLight ()
void RoadflareLight ()
void StoveLight ()
void TorchLight ()
override void OnFrameLightSource (IEntity other, float timeSlice)
void XmasSleighLight ()
void XmasTreeLight ()
void ZombieMummyLight ()
Private Attributes
float m_Timer = 0
Static Private Attributes
static float m_FireRadius = 40
static float m_FireBrightness = 15.0
static string m_MemoryPoint = "bonfire_fire"
static float m_DefaultBrightness = 1.5
static float m_DefaultRadius = 7.5
static float m_FireplaceRadius = 25
static float m_FireplaceBrightness = 4.75
static float m_FlareRadius = 100
static float m_FlareBrightness = 10.0
static float m_Lifetime = 0.04
static float m_TorchRadius = 15
static float m_TorchBrightness = 5.0
static float m_RoadflareRadius = 30
static float m_RoadflareBrightness = 8.5
Detailed Description
Definition at line 25 of file StaticObj_Roadblock_Wood_Small.c.
Member Function Documentation
AnniversaryBoxLight()
void PointLightBase::AnniversaryBoxLight () inline private
Definition at line 3 of file AnniversaryBoxLight.c.
  {
    SetVisibleDuringDaylight(true);
    SetRadiusTo(1);
    SetBrightnessTo(3);
    SetCastShadow(false);
    SetAmbientColor(0.9, 0.85, 0.4);
    SetDiffuseColor(0.9, 0.85, 0.4);
  }
BonfireLight()
void PointLightBase::BonfireLight () inline private
Definition at line 7 of file BonfireLight.c.
  {
    SetVisibleDuringDaylight(true);
    SetRadiusTo(m_FireRadius);
    SetBrightnessTo(m_FireBrightness);
    SetCastShadow(false);
    SetFadeOutTime(1);
    SetDiffuseColor(1.0, 0.45, 0.25);
    SetAmbientColor(1.0, 0.45, 0.25);
    SetFlareVisible(false);
    SetFlickerAmplitude(0.55);
    SetFlickerSpeed(0.75);
    SetDancingShadowsMovementSpeed(0.1);
    SetDancingShadowsAmplitude(0.03);
  }
BrightnessTestLight()
void PointLightBase::BrightnessTestLight () inline private
Definition at line 7 of file BrightnessTestLight.c.
  {
    SetVisibleDuringDaylight(true);
    SetRadiusTo(30);
    SetCastShadow(true);
    SetDiffuseColor(1, 1, 1);
    SetAmbientColor(1, 1, 1);
    SetBrightnessTo(10);
  }
ChemlightLight()
void PointLightBase::ChemlightLight () inline private
Definition at line 6 of file ChemlightLight.c.
  {
    SetVisibleDuringDaylight(false);
    SetRadiusTo(m_DefaultRadius);
    SetBrightnessTo(m_DefaultBrightness);
    FadeIn(1);
    SetFadeOutTime(2);
    SetFlareVisible(false);
  }
References m_DefaultBrightness, and m_DefaultRadius.
EntranceLight()
void PointLightBase::EntranceLight () inline protected
Definition at line 6 of file EntranceLight.c.
  {
    SetVisibleDuringDaylight(true);
    SetRadiusTo(m_DefaultRadius);
    SetBrightnessTo(m_DefaultBrightness);
    FadeIn(1);
    SetFadeOutTime(2);
    SetFlareVisible(false);
    SetCastShadow(false);
    SetAmbientColor(0.9, 0.9, 0.7);
    SetDiffuseColor(0.9, 0.9, 0.7);
  }
References m_DefaultBrightness, and m_DefaultRadius.
FireplaceLight()
void PointLightBase::FireplaceLight () inline private
Definition at line 6 of file FireplaceLight.c.
  {
    SetVisibleDuringDaylight(false);
    SetRadiusTo(m_FireplaceRadius);
    SetBrightnessTo(m_FireplaceBrightness);
    SetCastShadow(true);
    SetFadeOutTime(5);
    SetDiffuseColor(1.3, 0.35, 0.15);
    SetAmbientColor(1.3, 0.35, 0.15);
    SetFlareVisible(false);
    SetFlickerAmplitude(0.3);
    SetFlickerSpeed(0.9);
    SetExteriorMode();
    EnableHeatHaze(true);
    SetHeatHazeRadius(0.23);
    SetHeatHazePower(0.010);
  }
References SetExteriorMode().
FlareLight()
void PointLightBase::FlareLight () inline private
Definition at line 7 of file FlareLight.c.
  {
    SetVisibleDuringDaylight(true);
    SetRadiusTo(m_FlareRadius);
    SetBrightnessTo(m_FlareBrightness);
    FadeIn(1);
    SetFadeOutTime(0.2);
    SetDiffuseColor(0.7, 0.7, 0.3);
    SetAmbientColor(0.7, 0.7, 0.3);
    SetFlareVisible(false);
    SetFlickerAmplitude(0.9);
    SetFlickerSpeed(0.3);
    SetDancingShadowsMovementSpeed(0.5);
    SetDancingShadowsAmplitude(0.15);
    //SetLifetime( 50 );
    EnableLinear(true);
    EnableHeatHaze(true);
    SetHeatHazeRadius(0.1);
    SetHeatHazePower(0.02);
#ifdef PLATFORM_WINDOWS
    SetCastShadow(true);
#else
    SetCastShadow(false);
#endif
  }
References m_FlareBrightness, and m_FlareRadius.
GoatLight()
void PointLightBase::GoatLight () inline private
Definition at line 3 of file GoatLight.c.
  {
    SetVisibleDuringDaylight(true);
    SetRadiusTo(1.6);
    SetBrightnessTo(3.1);
    SetCastShadow(false);
    SetFadeOutTime(15);
    SetDiffuseColor(0.85, 0.1, 0.1);
    SetAmbientColor(0.85, 0.1, 0.1);
    SetFlareVisible(false);
    SetFlickerAmplitude(0.35);
    SetFlickerSpeed(0.25);
    SetDancingShadowsMovementSpeed(0.05);
    SetDancingShadowsAmplitude(0.03);
  }
MuzzleFlashLight()
void PointLightBase::MuzzleFlashLight () inline private
Definition at line 5 of file MuzzleFlashLight.c.
  {
    SetLifetime(m_Lifetime);
    FadeIn(m_Lifetime * 0.5);
    SetFadeOutTime(m_Lifetime * 0.5);
    SetVisibleDuringDaylight(true);
    SetRadiusTo(15);
    SetBrightnessTo(1);
    SetCastShadow(false);
    SetAmbientColor(0.76, 0.68, 0.31);
    SetDiffuseColor(0.76, 0.68, 0.31);
    SetFlareVisible(false);
  }
References m_Lifetime.
MuzzleFlashLight_2()
void PointLightBase::MuzzleFlashLight_2 () inline private
Definition at line 43 of file MuzzleFlashLight.c.
  {
    SetLifetime(m_Lifetime);
    FadeIn(m_Lifetime * 0.1);
    SetFadeOutTime(m_Lifetime * 0.1);
    SetVisibleDuringDaylight(true);
    SetRadiusTo(12);
    SetBrightnessTo(0.2);
    SetCastShadow(false);
    SetAmbientColor(0.36, 0.32, 0.13);
    SetDiffuseColor(0.36, 0.32, 0.13);
    SetFlareVisible(false);
  }
References m_Lifetime.
OnFrameLightSource() [1/5]
override void PointLightBase::OnFrameLightSource (IEntity other, float timeSlice) inline private
Definition at line 23 of file BonfireLight.c.
  {
  }
OnFrameLightSource() [2/5]
override void PointLightBase::OnFrameLightSource (IEntity other, float timeSlice) inline private
Definition at line 18 of file BrightnessTestLight.c.
  {
    m_Timer += timeSlice;
    float pulse = Math.AbsFloat(Math.Cos(m_Timer));
    if (pulse > 0)
    {
      Print(pulse);
      SetBrightnessTo(pulse);
    }
  }
References Math::AbsFloat(), Math::Cos(), m_Timer, and Print().
OnFrameLightSource() [3/5]
override void PointLightBase::OnFrameLightSource (IEntity other, float timeSlice) inline private
Definition at line 15 of file PartyLight.c.
  {
    float valS = Math.AbsFloat(Math.Sin(m_Timer * Math.PI2));
    float valC = Math.AbsFloat(Math.Cos(m_Timer * Math.PI2));
    float valT = Math.AbsFloat(Math.Tan(m_Timer * Math.PI2));
    SetDiffuseColor(valS, valC, valT);
    SetAmbientColor(valS, valC, valT);
    m_Timer += timeSlice;
  }
References Math::AbsFloat(), Math::Cos(), m_Timer, Math::PI2, Math::Sin(), and Math::Tan().
OnFrameLightSource() [4/5]
override void PointLightBase::OnFrameLightSource (IEntity other, float timeSlice) inline private
Definition at line 15 of file PersonalLight.c.
  {
    if (GetGame() && IsEnabled())
    {
      vector pos = GetGame().GetCurrentCameraPosition();
      pos += Vector(0, -0.4, 0);
      SetPosition(pos);
    }
  }
References GetGame(), SetPosition(), and Vector().
OnFrameLightSource() [5/5]
override void PointLightBase::OnFrameLightSource (IEntity other, float timeSlice) inline private
Definition at line 25 of file TorchLight.c.
  {
  }
PartyLight()
void PointLightBase::PartyLight () inline private
Definition at line 5 of file PartyLight.c.
  {
    SetVisibleDuringDaylight(true);
    SetRadiusTo(30);
    SetBrightnessTo(1.0);
    SetCastShadow(true);
    //SetLifetime(600);
    SetFadeOutTime(1);
  }
PersonalLight()
void PointLightBase::PersonalLight () inline private
Definition at line 3 of file PersonalLight.c.
  {
    SetVisibleDuringDaylight(false);
    SetRadiusTo(3);
    SetBrightnessTo(0.38);
    SetDiffuseColor(0.2, 0.23, 0.25);
    SetCastShadow(false);
    EnableSpecular(false);
    EnableLinear(true);
    SetFlareVisible(false);
  }
PortableGasLampLight()
void PointLightBase::PortableGasLampLight () inline private
Definition at line 6 of file PortableGasLampLight.c.
  {
    SetVisibleDuringDaylight(false);
    SetRadiusTo(m_TorchRadius);
    SetBrightnessTo(m_TorchBrightness);
    SetCastShadow(true);
    FadeIn(0.5);
    SetFadeOutTime(0.1);
    SetDiffuseColor(1.0, 0.7, 0.5);
    SetAmbientColor(1.0, 0.7, 0.5);
    SetFlickerAmplitude(0.3);
    SetFlickerSpeed(0.75);
    SetDancingShadowsMovementSpeed(0.005);
    SetDancingShadowsAmplitude(0.003);
  }
Roadblock_Light()
void PointLightBase::Roadblock_Light () inline protected
Definition at line 30 of file StaticObj_Roadblock_Wood_Small.c.
  {
    SetVisibleDuringDaylight(true);
    SetRadiusTo(m_DefaultRadius);
    SetBrightnessTo(m_DefaultBrightness);
    FadeIn(1);
    SetFadeOutTime(2);
    SetFlareVisible(false);
    SetCastShadow(false);
    SetAmbientColor(0.9, 0.9, 0.7);
    SetDiffuseColor(0.9, 0.9, 0.7);
    SetBlinkingSpeed(1);
  }
References m_DefaultBrightness, and m_DefaultRadius.
RoadflareLight()
void PointLightBase::RoadflareLight () inline private
Definition at line 7 of file RoadflareLight.c.
  {
    SetVisibleDuringDaylight(true);
    SetRadiusTo(m_RoadflareRadius);
    SetBrightnessTo(m_RoadflareBrightness);
    SetCastShadow(true);
    FadeIn(1);
    SetFadeOutTime(1);
    SetDiffuseColor(1.0, 0.3, 0.3);
    SetAmbientColor(1.0, 0.3, 0.3);
    SetFlareVisible(true);
    SetFlickerAmplitude(0.2);
    SetFlickerSpeed(1.5);
    SetDancingShadowsMovementSpeed(0.1);
    SetDancingShadowsAmplitude(0.015);
    EnableHeatHaze(true);
    SetHeatHazeRadius(0.1);
    SetHeatHazePower(0.02);
  }
SetColorToBlue()
void PointLightBase::SetColorToBlue () inline private
Definition at line 40 of file ChemlightLight.c.
  {
    SetAmbientColor(0.3, 0.3, 1.0);
    SetDiffuseColor(0.3, 0.3, 1.0);
  }
SetColorToGreen()
void PointLightBase::SetColorToGreen () inline private
Definition at line 34 of file ChemlightLight.c.
  {
    SetAmbientColor(0.3, 1.0, 0.2);
    SetDiffuseColor(0.3, 1.0, 0.2);
  }
SetColorToRed()
void PointLightBase::SetColorToRed () inline private
Definition at line 28 of file ChemlightLight.c.
  {
    SetAmbientColor(1.0, 0.3, 0.2);
    SetDiffuseColor(1.0, 0.3, 0.2);
  }
Referenced by Headtorch_Black::OnLightCreated().
SetColorToWhite()
void PointLightBase::SetColorToWhite () inline private
Definition at line 22 of file ChemlightLight.c.
  {
    SetAmbientColor(0.9, 0.9, 1.0);
    SetDiffuseColor(0.9, 0.9, 1.0);
  }
Referenced by Clothing::OnLightCreated().
SetColorToYellow()
void PointLightBase::SetColorToYellow () inline private
Definition at line 46 of file ChemlightLight.c.
  {
    SetAmbientColor(1.0, 1.0, 0.3);
    SetDiffuseColor(1.0, 1.0, 0.3);
  }
SetExteriorMode()
void PointLightBase::SetExteriorMode () inline private
Definition at line 32 of file FireplaceLight.c.
  {
    SetDancingShadowsMovementSpeed(0.25);
    SetDancingShadowsAmplitude(0.10);
  }
Referenced by FireplaceLight().
SetIntensity()
void PointLightBase::SetIntensity (float coef, float time) inline private
Definition at line 16 of file ChemlightLight.c.
  {
    FadeBrightnessTo(m_DefaultBrightness * coef, time);
    FadeRadiusTo(m_DefaultRadius * coef, time);
  }
References m_DefaultBrightness, and m_DefaultRadius.
Referenced by Clothing::OnWork(), ItemBase::OnWork(), and Switchable_Base::OnWork().
SetInteriorMode()
void PointLightBase::SetInteriorMode () inline private
Definition at line 25 of file FireplaceLight.c.
  {
    SetDancingShadowsMovementSpeed(0.05);
    SetDancingShadowsAmplitude(0.05);
  }
StoveLight()
void PointLightBase::StoveLight () inline private
Definition at line 3 of file StoveLight.c.
  {
    SetVisibleDuringDaylight(false);
    SetRadiusTo(1);
    SetBrightnessTo(3.0);
    SetCastShadow(true);
    SetFadeOutTime(0.2);
    SetDiffuseColor(0.2, 0.45, 0.7);
    SetAmbientColor(0.2, 0.45, 0.7);
    SetFlareVisible(false);
    SetFlickerAmplitude(0.35);
    SetFlickerSpeed(0.55);
    SetDancingShadowsMovementSpeed(0.05);
    SetDancingShadowsAmplitude(0.03);
    EnableHeatHaze(true);
    SetHeatHazeRadius(0.08);
    SetHeatHazePower(0.015);
  }
TorchLight()
void PointLightBase::TorchLight () inline private
Definition at line 6 of file TorchLight.c.
  {
    SetVisibleDuringDaylight(false);
    SetRadiusTo(m_TorchRadius);
    SetBrightnessTo(m_TorchBrightness);
    SetCastShadow(true);
    SetFadeOutTime(1);
    SetDiffuseColor(1.3, 0.35, 0.15);
    SetAmbientColor(1.3, 0.35, 0.15);
    SetFlareVisible(false);
    SetFlickerAmplitude(0.55);
    SetFlickerSpeed(0.75);
    SetDancingShadowsMovementSpeed(0.1);
    SetDancingShadowsAmplitude(0.03);
    EnableHeatHaze(true);
    SetHeatHazeRadius(0.08);
    SetHeatHazePower(0.015);
  }
XmasSleighLight()
void PointLightBase::XmasSleighLight () inline private
Definition at line 3 of file XmasSleighLight.c.
  {
    SetVisibleDuringDaylight(false);
    SetRadiusTo(24);
    SetBrightnessTo(3);
    SetCastShadow(false);
    SetDiffuseColor(0.7, 0.7, 1.0);
    SetFlareVisible(false);
    SetFlickerAmplitude(0.5);
    SetFlickerSpeed(1);
  }
XmasTreeLight()
void PointLightBase::XmasTreeLight () inline private
Definition at line 3 of file XmasTreeLight.c.
  {
    SetVisibleDuringDaylight(false);
    SetRadiusTo(12);
    SetBrightnessTo(0.50);
    SetCastShadow(false);
    SetDiffuseColor(1.2, 1.0, 0.7);
    SetDancingShadowsMovementSpeed(0.005);
    SetDancingShadowsAmplitude(0.003);
  }
ZombieMummyLight()
void PointLightBase::ZombieMummyLight () inline private
Definition at line 3 of file ZombieMummyLight.c.
  {
    SetVisibleDuringDaylight(false);
    SetRadiusTo(2.1);
    SetBrightnessTo(3.1);
    SetCastShadow(false);
    SetFadeOutTime(15);
    SetDiffuseColor(0.6, 0.5, 0.1);
    SetAmbientColor(0.6, 0.5, 0.1);
    SetFlareVisible(false);
    SetFlickerAmplitude(0.35);
    SetFlickerSpeed(0.25);
    SetDancingShadowsMovementSpeed(0.05);
    SetDancingShadowsAmplitude(0.03);
  }
Member Data Documentation
m_DefaultBrightness [1/2]
float PointLightBase::m_DefaultBrightness = 5.5 protected
Definition at line 27 of file StaticObj_Roadblock_Wood_Small.c.
m_DefaultBrightness [2/2]
float PointLightBase::m_DefaultBrightness = 1.5 static private
Definition at line 3 of file ChemlightLight.c.
m_DefaultRadius [1/2]
float PointLightBase::m_DefaultRadius = 20 protected
Definition at line 28 of file StaticObj_Roadblock_Wood_Small.c.
m_DefaultRadius [2/2]
float PointLightBase::m_DefaultRadius = 7.5 static private
Definition at line 4 of file ChemlightLight.c.
m_FireBrightness
float PointLightBase::m_FireBrightness = 15.0 static private
Definition at line 4 of file BonfireLight.c.
Referenced by BuildingSuper::EEInit().
m_FireplaceBrightness
float PointLightBase::m_FireplaceBrightness = 4.75 static private
Definition at line 4 of file FireplaceLight.c.
m_FireplaceRadius
float PointLightBase::m_FireplaceRadius = 25 static private
Definition at line 3 of file FireplaceLight.c.
m_FireRadius
float PointLightBase::m_FireRadius = 40 static private
Definition at line 3 of file BonfireLight.c.
Referenced by BuildingSuper::EEInit().
m_FlareBrightness
float PointLightBase::m_FlareBrightness = 10.0 static private
Definition at line 4 of file FlareLight.c.
m_FlareRadius
float PointLightBase::m_FlareRadius = 100 static private
Definition at line 3 of file FlareLight.c.
m_Lifetime
static float PointLightBase::m_Lifetime = 0.04 static private
Definition at line 3 of file MuzzleFlashLight.c.
m_MemoryPoint
static string PointLightBase::m_MemoryPoint = "bonfire_fire" static private
Definition at line 5 of file BonfireLight.c.
Referenced by BuildingSuper::EEInit().
m_RoadflareBrightness
float PointLightBase::m_RoadflareBrightness = 8.5 static private
Definition at line 4 of file RoadflareLight.c.
m_RoadflareRadius
float PointLightBase::m_RoadflareRadius = 30 static private
Definition at line 3 of file RoadflareLight.c.
m_Timer
float PointLightBase::m_Timer = 0 private
Definition at line 5 of file BrightnessTestLight.c.
m_TorchBrightness
static float PointLightBase::m_TorchBrightness = 5.0 static private
Definition at line 4 of file PortableGasLampLight.c.
m_TorchRadius
static float PointLightBase::m_TorchRadius = 15 static private
Definition at line 3 of file PortableGasLampLight.c.
The documentation for this class was generated from the following files:
scripts/4_World/Entities/Building/Wrecks/StaticObj_Roadblock_Wood_Small.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/BonfireLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/BrightnessTestLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/ChemlightLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/EntranceLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/FireplaceLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/FlareLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/MuzzleFlashLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/PartyLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/PortableGasLampLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/RoadflareLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/TorchLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/AnniversaryBoxLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/GoatLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/PersonalLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/StoveLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/XmasSleighLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/XmasTreeLight.c
scripts/4_World/Entities/ScriptedLightBase/PointLightBase/ZombieMummyLight.c