DayZ: Environment Class Reference
Environment Class Reference
Protected Member Functions
void Environment (PlayerBase pPlayer)
void Init (PlayerBase pPlayer)
void Update (float pDelta)
bool IsTemperatureSet ()
void AddToEnvironmentTemperature (float pTemperature)
float GetPlayerHeat ()
Returns heat player generated based on player's movement speed (for now)
bool IsUnderRoof ()
bool IsWaterContact ()
bool IsInsideBuilding ()
bool IsInsideVehicle ()
bool IsRaining ()
void CheckUnderRoof ()
Checks whether Player is sheltered.
void CheckWaterContact (out float pWaterLevel)
float GetTemperatureHeightCorrection ()
float GetWindModifierPerSurface ()
float GetTemperature ()
float GetEnvironmentTemperature ()
float GetWetDelta ()
void CollectAndSetPlayerData ()
void CollectAndSetEnvironmentData ()
void SetEnvironmentTemperature ()
void ProcessWetnessByRain ()
void ProcessWetnessByWaterLevel (float pWaterLevel)
void ProcessItemsWetness (array< int > pSlotIds)
void ProcessItemsDryness ()
void ApplyWetnessToItem (ItemBase pItem)
void ApplyDrynessToItem (ItemBase pItem)
void ApplyDrynessToItemEx (ItemBase pItem, EnvironmentDrynessData pDrynessData)
void ProcessItemsHeat ()
Calculates and process temperature of items.
bool OverridenHeatComfort (out float value)
DEPRECATED.
float EnvTempToCoef (float pTemp)
void BodyPartHeatProperties (array< int > pBodyPartIds, float pCoef, out float pHeatComfort, out float pHeat)
returns weighted avg heat comfort for bodypart
void GatherTemperatureSources ()
void ProcessTemperatureSources ()
float GetUniversalSourcesTemperageAverage ()
float CalcTemperatureFromTemperatureSource (notnull UTemperatureSource uts)
string GetDebugMessage ()
debug
int GetNextRoofCheck ()
float GetWaterLevel ()
float GetDayOrNight ()
Protected Attributes
float m_WetDryTick
float m_ItemsWetnessMax
float m_RoofCheckTimer
keeps wetness of most wet item in player's possesion
PlayerBase m_Player
float m_PlayerHeightPos
float m_PlayerSpeed
float m_PlayerTemperature
float m_PlayerHeat
float m_HeatComfort
float m_Rain = 0
float m_Wind = 0
float m_Fog = 0
float m_DayOrNight = 0
float m_Clouds = 0
float m_EnvironmentTemperature = 0
float m_Time = 0
string m_SurfaceType
float m_WaterLevel
bool m_IsUnderRoof
bool m_IsInWater
bool m_IsTempSet
float m_HeatSourceTemp
float m_HeatBufferTimer
DEPRECATED.
ref array< int > m_SlotIdsComplete
ref array< int > m_SlotIdsUpper
ref array< int > m_SlotIdsBottom
ref array< int > m_SlotIdsLower
ref array< int > m_HeadParts
ref array< int > m_BodyParts
ref array< int > m_FeetParts
ref SimpleMovingAverage< float > m_WindAverageBuffer
bool m_HasTemperatureSources
float m_UTSAverageTemperature
ref array< UTemperatureSource > m_UTemperatureSources
ref SimpleMovingAverage< float > m_UTSAverageTemperatureBuffer
Private Member Functions
bool IsUnderRoofBuilding ()
void LogDryWetProcess (string message, bool indented=false)
Private Attributes
const float RAIN_LIMIT_LOW = 0.05
const float WATER_LEVEL_HIGH = 1.5
const float WATER_LEVEL_MID = 1.2
const float WATER_LEVEL_LOW = 0.5
const float WATER_LEVEL_NONE = 0.15
bool m_IsUnderRoofBuilding
Detailed Description
Definition at line 1 of file Environment.c.
Constructor & Destructor Documentation
Environment()
void Environment::Environment (PlayerBase pPlayer) inline protected
Definition at line 64 of file Environment.c.
  {
    Init(pPlayer);
  }
References Init().
Member Function Documentation
AddToEnvironmentTemperature()
void Environment::AddToEnvironmentTemperature (float pTemperature) protected
ApplyDrynessToItem()
void Environment::ApplyDrynessToItem (ItemBase pItem) inline protected
Definition at line 631 of file Environment.c.
  {
    EnvironmentDrynessData drynessData = new EnvironmentDrynessData();
    ApplyDrynessToItemEx(pItem, drynessData);
  }
References ApplyDrynessToItemEx().
ApplyDrynessToItemEx()
void Environment::ApplyDrynessToItemEx (ItemBase pItem, EnvironmentDrynessData pDrynessData) inline protected
adds wetness to item inside parent item containing liquid
adds wetness to item inside wet parent item
Definition at line 637 of file Environment.c.
  {
    if (pItem)
    {
      float dryingIncrement = pItem.GetDryingIncrement("player");
      if (pDrynessData.m_UseTemperatureSources)
        dryingIncrement = pItem.GetDryingIncrement("playerHeatSource");
      ItemBase parentItem;
      bool isParentWet = false;
      bool parentContainsLiquid = false;
      InventoryLocation iLoc = new InventoryLocation();
      if (pItem.GetInventory().GetCurrentInventoryLocation(iLoc))
      {
        EntityAI parent = iLoc.GetParent();
        if (parent)
        {
          parentItem = ItemBase.Cast(parent);
          if (parentItem)
          {
            if (parentItem.GetWet() >= GameConstants.STATE_SOAKING_WET)
              isParentWet = true;
            if ((parentItem.GetLiquidType() != 0) && (parentItem.GetQuantity() > 0))
              parentContainsLiquid = true;
          }
          if ((pItem.GetWet() > m_ItemsWetnessMax) && (parent == m_Player))
            m_ItemsWetnessMax = pItem.GetWet();
        }
      }
      float dryingCoef = 0;
      if (!isParentWet && !parentContainsLiquid)
      {
        dryingCoef = (-1 * GameConstants.ENVIRO_TICK_RATE * dryingIncrement) / pDrynessData.m_TemperatureSourceDistance;
        if (pItem.GetWet() >= GameConstants.STATE_DAMP)
        {
          LogDryWetProcess(string.Format("%1 (dry coef=%2/s, current wetness=%3) [normal]", pItem.GetDisplayName(), dryingCoef / GameConstants.ENVIRO_TICK_RATE, pItem.GetWet()), parentItem != null);
          pItem.AddWet(dryingCoef);
        }
        if (pItem.GetInventory().GetCargo())
        {
          int inItemCount = pItem.GetInventory().GetCargo().GetItemCount();
          for (int i = 0; i < inItemCount; i++)
          {
            ItemBase inItem;
            if (Class.CastTo(inItem, pItem.GetInventory().GetCargo().GetItem(i)))
              ApplyDrynessToItemEx(inItem, pDrynessData);
          }
        }
        int attCount = pItem.GetInventory().AttachmentCount();
        if (attCount > 0)
        {
          for (int attIdx = 0; attIdx < attCount; attIdx++)
          {
            EntityAI attachment = pItem.GetInventory().GetAttachmentFromIndex(attIdx);
            ItemBase itemAtt;
            if (ItemBase.CastTo(itemAtt, attachment))
              ApplyDrynessToItemEx(itemAtt, pDrynessData);
          }
        }
        pItem.AddTemperature(GameConstants.ENVIRO_TICK_RATE * GameConstants.TEMPERATURE_RATE_COOLING_PLAYER);
      }
      if (parentContainsLiquid)
      {
        dryingCoef = (GameConstants.ENVIRO_TICK_RATE * pItem.GetSoakingIncrement("parentWithLiquid")) / pDrynessData.m_TemperatureSourceDistance;
        LogDryWetProcess(string.Format("%1 (dry coef=%2/s, current wetness=%3) [parent contains liquid]", pItem.GetDisplayName(), dryingCoef / GameConstants.ENVIRO_TICK_RATE, pItem.GetWet()), parentItem != null);
        pItem.AddWet(dryingCoef);
        pItem.AddTemperature(GameConstants.ENVIRO_TICK_RATE * GameConstants.TEMPERATURE_RATE_COOLING_PLAYER);
      }
      if (isParentWet)
      {
        if (pItem.GetWet() < parentItem.GetWet())
        {
          dryingCoef = (GameConstants.ENVIRO_TICK_RATE * pItem.GetSoakingIncrement("wetParent")) / pDrynessData.m_TemperatureSourceDistance;
          LogDryWetProcess(string.Format("%1 (dry coef=%2/s, current wetness=%3) [parent wet]", pItem.GetDisplayName(), dryingCoef / GameConstants.ENVIRO_TICK_RATE, pItem.GetWet()), parentItem != null);
          pItem.AddWet(dryingCoef);
        }
        pItem.AddTemperature(GameConstants.ENVIRO_TICK_RATE * GameConstants.TEMPERATURE_RATE_COOLING_PLAYER * 3.5);
      }
    }
  }
References ApplyDrynessToItemEx(), Class::CastTo(), GameConstants::ENVIRO_TICK_RATE, LogDryWetProcess(), m_ItemsWetnessMax, m_Player, GameConstants::STATE_DAMP, GameConstants::STATE_SOAKING_WET, and GameConstants::TEMPERATURE_RATE_COOLING_PLAYER.
Referenced by ApplyDrynessToItem(), ApplyDrynessToItemEx(), and ProcessItemsDryness().
ApplyWetnessToItem()
void Environment::ApplyWetnessToItem (ItemBase pItem) inline protected
Definition at line 549 of file Environment.c.
  {
    if (pItem)
    {
      ItemBase parentItem;
      bool isParentWet = false;
      bool parentContainsLiquid = false;
      InventoryLocation iLoc = new InventoryLocation();
      if (pItem.GetInventory().GetCurrentInventoryLocation(iLoc))
      {
        EntityAI parent = iLoc.GetParent();
        if (parent)
        {
          parentItem = ItemBase.Cast(parent);
          if (parentItem)
          {
            if (parentItem.GetWet() >= GameConstants.STATE_SOAKING_WET)
              isParentWet = true;
            if ((parentItem.GetLiquidType() != 0) && (parentItem.GetQuantity() > 0))
              parentContainsLiquid = true;
          }
          else
            isParentWet = true;
          if ((pItem.GetWet() > m_ItemsWetnessMax) && (parent == m_Player))
            m_ItemsWetnessMax = pItem.GetWet();
        }
      }
      if (isParentWet || parentContainsLiquid)
      {
        float soakingCoef = 0;
        if (parentContainsLiquid)
        {
          soakingCoef = pItem.GetSoakingIncrement("parentWithLiquid");
          LogDryWetProcess(string.Format("%1 (soak coef=%2/s, current wetness=%3) [parent contains liquid]", pItem.GetDisplayName(), soakingCoef / GameConstants.ENVIRO_TICK_RATE, pItem.GetWet()), parentItem != null);
        }
        else if (isParentWet && parentItem)
        {
          if (pItem.GetWet() < parentItem.GetWet())
          {
            soakingCoef = pItem.GetSoakingIncrement("wetParent");
            LogDryWetProcess(string.Format("%1 (soak coef=%2/s, current wetness=%3) [parent wet]", pItem.GetDisplayName(), soakingCoef / GameConstants.ENVIRO_TICK_RATE, pItem.GetWet()), parentItem != null);
          }
        }
        else
        {
          soakingCoef = GetWetDelta();
          LogDryWetProcess(string.Format("%1 (soak coef=%2/s, current wetness=%3) [normal]", pItem.GetDisplayName(), soakingCoef / GameConstants.ENVIRO_TICK_RATE, pItem.GetWet()), parentItem != null);
        }
        pItem.AddWet(soakingCoef);
        pItem.AddTemperature(GameConstants.ENVIRO_TICK_RATE * GameConstants.TEMPERATURE_RATE_COOLING_PLAYER * pItem.GetSoakingIncrement("wetParent"));
        if (pItem.GetInventory().GetCargo())
        {
          int inItemCount = pItem.GetInventory().GetCargo().GetItemCount();
          for (int i = 0; i < inItemCount; i++)
          {
            ItemBase inItem;
            if (Class.CastTo(inItem, pItem.GetInventory().GetCargo().GetItem(i)))
              ApplyWetnessToItem(inItem);
          }
        }
        int attCount = pItem.GetInventory().AttachmentCount();
        if (attCount > 0)
        {
          for (int attIdx = 0; attIdx < attCount; attIdx++)
          {
            EntityAI attachment = pItem.GetInventory().GetAttachmentFromIndex(attIdx);
            ItemBase itemAtt = ItemBase.Cast(attachment);
            if (itemAtt)
              ApplyWetnessToItem(itemAtt);
          }
        }
      }
    }
  }
References ApplyWetnessToItem(), Class::CastTo(), GameConstants::ENVIRO_TICK_RATE, GetWetDelta(), LogDryWetProcess(), m_ItemsWetnessMax, m_Player, GameConstants::STATE_SOAKING_WET, and GameConstants::TEMPERATURE_RATE_COOLING_PLAYER.
Referenced by ApplyWetnessToItem(), and ProcessItemsWetness().
BodyPartHeatProperties()
void Environment::BodyPartHeatProperties (array< int > pBodyPartIds, float pCoef, out float pHeatComfort, out float pHeat) inline protected
returns weighted avg heat comfort for bodypart
go through all body parts we've defined for that zone (ex.: head, body, feet)
Definition at line 806 of file Environment.c.
  {
    int attCount;
    EntityAI attachment;
    ItemBase item;
    pHeatComfort = -1;
    attCount = m_Player.GetInventory().AttachmentCount();
    for (int attIdx = 0; attIdx < attCount; attIdx++)
    {
      attachment = m_Player.GetInventory().GetAttachmentFromIndex(attIdx);
      if (attachment.IsClothing())
      {
        item = ItemBase.Cast(attachment);
        int attachmentSlot = attachment.GetInventory().GetSlotId(0);
        for (int i = 0; i < pBodyPartIds.Count(); i++)
        {
          if (attachmentSlot == pBodyPartIds.Get(i))
          {
            float heatIsoMult = 1.0;
            if (attachmentSlot == InventorySlots.VEST)
              heatIsoMult = GameConstants.ENVIRO_HEATISOLATION_VEST_WEIGHT;
            if (attachmentSlot == InventorySlots.BACK)
              heatIsoMult = GameConstants.ENVIRO_HEATISOLATION_BACK_WEIGHT;
            pHeatComfort += heatIsoMult * MiscGameplayFunctions.GetCurrentItemHeatIsolation(item);
            // go through any attachments and cargo (only current level, ignore nested containers - they isolate)
            int inAttCount = item.GetInventory().AttachmentCount();
            if (inAttCount > 0)
            {
              for (int inAttIdx = 0; inAttIdx < inAttCount; inAttIdx++)
              {
                EntityAI inAttachment = item.GetInventory().GetAttachmentFromIndex(inAttIdx);
                ItemBase itemAtt = ItemBase.Cast(inAttachment);
                if (itemAtt)
                  pHeat += itemAtt.GetTemperature();
              }
            }
            if (item.GetInventory().GetCargo())
            {
              int inItemCount = item.GetInventory().GetCargo().GetItemCount();
              for (int j = 0; j < inItemCount; j++)
              {
                ItemBase inItem;
                if (Class.CastTo(inItem, item.GetInventory().GetCargo().GetItem(j)))
                  pHeat += inItem.GetTemperature();
              }
            }
          }
        }
      }
    }
    pHeatComfort = (pHeatComfort / pBodyPartIds.Count()) * pCoef;
    pHeat = (pHeat / pBodyPartIds.Count()) * pCoef;
  }
References Class::CastTo(), GameConstants::ENVIRO_HEATISOLATION_BACK_WEIGHT, GameConstants::ENVIRO_HEATISOLATION_VEST_WEIGHT, and m_Player.
Referenced by ProcessItemsHeat().
CalcTemperatureFromTemperatureSource()
float Environment::CalcTemperatureFromTemperatureSource (notnull UTemperatureSource uts) inline protected
heat transfer through air to player (env temperature)
dist factor minimum should be at 0
Definition at line 928 of file Environment.c.
  {
    float distance = vector.Distance(m_Player.GetPosition(), uts.GetPosition());
    distance = Math.Max(distance, 0.1); //min distance cannot be 0 (division by zero)
    float temperature = 0;
    //Debug.Log(string.Format("CalcTemperatureFromTemperatureSource::distance: %1", distance), "Environment");
    if (distance > uts.GetFullRange())
    {
      float distFactor = 1 - (distance / uts.GetMaxRange());
      distFactor = Math.Max(distFactor, 0.0);
      temperature = uts.GetTemperature() * distFactor;
      //temperature = Math.Clamp(temperature, uts.GetTemperatureMin(), uts.GetTemperatureMax());
      //Debug.Log(string.Format("CalcTemperatureFromTemperatureSource::distFactor: %1", distFactor), "Environment");
      //Debug.Log(string.Format("CalcTemperatureFromTemperatureSource::temperatureXX: %1", temperature), "Environment");
    }
    else
      temperature = uts.GetTemperature();
    //Debug.Log(string.Format("CalcTemperatureFromTemperatureSource::temperature: %1", temperature), "Environment");
    return temperature;
  }
References vector::Distance(), m_Player, and Math::Max().
Referenced by ProcessTemperatureSources().
CheckUnderRoof()
void Environment::CheckUnderRoof () inline protected
Checks whether Player is sheltered.
Definition at line 256 of file Environment.c.
  {
    // if inside vehicle return immediatelly
    if (IsInsideVehicle())
    {
      m_IsUnderRoof = false;
      m_IsUnderRoofBuilding = false;
      return;
    }
    float hitFraction;
    vector hitPosition, hitNormal;
    vector from = m_Player.GetPosition();
    vector to = from + "0 25 0";
    Object hitObject;
    PhxInteractionLayers collisionLayerMask = PhxInteractionLayers.ITEM_LARGE | PhxInteractionLayers.BUILDING | PhxInteractionLayers.VEHICLE;
    m_IsUnderRoof = DayZPhysics.RayCastBullet(from, to, collisionLayerMask, null, hitObject, hitPosition, hitNormal, hitFraction);
    m_IsUnderRoofBuilding = hitObject && hitObject.IsInherited(House);
  }
References IsInsideVehicle(), m_IsUnderRoof, m_IsUnderRoofBuilding, m_Player, and DayZPhysics::RayCastBullet().
Referenced by Update().
CheckWaterContact()
void Environment::CheckWaterContact (out float pWaterLevel) inline protected
no valid surface under character
sync info about water contact to player
update active surface
Definition at line 278 of file Environment.c.
  {
    m_IsInWater = false;
    if (m_Player.IsSwimming())
    {
      m_IsInWater = true;
      HumanMovementState hms = new HumanMovementState();
      m_Player.GetMovementState(hms);
      pWaterLevel = WATER_LEVEL_MID;
      if (hms.m_iMovement >= DayZPlayerConstants.MOVEMENTIDX_WALK)
        pWaterLevel = WATER_LEVEL_HIGH;
      return;
    }
    if (IsUnderRoofBuilding())
    {
      m_IsInWater = false;
      return;
    }
    string surfType;
    int liquidType;
    g_Game.SurfaceUnderObject(m_Player, surfType, liquidType);
    switch (liquidType)
    {
    case 0: // sea
    case LIQUID_WATER:
    case LIQUID_RIVERWATER:
      pWaterLevel = m_Player.GetCurrentWaterLevel();
      m_IsInWater = true;
      break;
    }
    m_Player.SetInWater(m_IsInWater);
    m_SurfaceType = surfType;
  }
References g_Game, IsUnderRoofBuilding(), LIQUID_RIVERWATER, LIQUID_WATER, m_IsInWater, m_Player, m_SurfaceType, WATER_LEVEL_HIGH, and WATER_LEVEL_MID.
Referenced by Update().
CollectAndSetEnvironmentData()
void Environment::CollectAndSetEnvironmentData () inline protected
Definition at line 429 of file Environment.c.
  {
    Weather weather = g_Game.GetWeather();
    m_Rain = weather.GetRain().GetActual();
    m_DayOrNight = g_Game.GetWorld().GetSunOrMoon();
    m_Fog = weather.GetFog().GetActual();
    m_Clouds = weather.GetOvercast().GetActual();
    m_Wind = m_WindAverageBuffer.Add(weather.GetWindSpeed() / weather.GetWindMaximumSpeed());
    SetEnvironmentTemperature();
  }
References g_Game, m_Clouds, m_DayOrNight, m_Fog, m_Rain, m_Wind, m_WindAverageBuffer, and SetEnvironmentTemperature().
Referenced by Update().
CollectAndSetPlayerData()
void Environment::CollectAndSetPlayerData () inline protected
Definition at line 416 of file Environment.c.
  {
    vector playerPos = m_Player.GetPosition();
    m_PlayerHeightPos = playerPos[1];
    HumanCommandMove hcm = m_Player.GetCommand_Move();
    if (hcm)
      m_PlayerSpeed = hcm.GetCurrentMovementSpeed();
    m_PlayerHeat = GetPlayerHeat();
  }
References GetPlayerHeat(), m_Player, m_PlayerHeat, m_PlayerHeightPos, and m_PlayerSpeed.
Referenced by Update().
EnvTempToCoef()
float Environment::EnvTempToCoef (float pTemp) inline protected
Definition at line 794 of file Environment.c.
  {
    if (pTemp >= GameConstants.ENVIRO_HIGH_TEMP_LIMIT)
      return 1;
    if (pTemp <= GameConstants.ENVIRO_LOW_TEMP_LIMIT)
      return -1;
    return (pTemp - GameConstants.ENVIRO_PLAYER_COMFORT_TEMP) / GameConstants.ENVIRO_TEMP_EFFECT_ON_PLAYER;
  }
References GameConstants::ENVIRO_HIGH_TEMP_LIMIT, GameConstants::ENVIRO_LOW_TEMP_LIMIT, GameConstants::ENVIRO_PLAYER_COMFORT_TEMP, and GameConstants::ENVIRO_TEMP_EFFECT_ON_PLAYER.
Referenced by ProcessItemsHeat().
GatherTemperatureSources()
void Environment::GatherTemperatureSources () inline protected
next temp source is too far
Definition at line 870 of file Environment.c.
  {
    m_UTemperatureSources.Clear();
    array<Object> nearestObjects = new array<Object>;
    GetGame().GetObjectsAtPosition(m_Player.GetPosition(), GameConstants.ENVIRO_TEMP_SOURCES_LOOKUP_RADIUS, nearestObjects, null);
    foreach (Object nearestObject : nearestObjects)
    {
      EntityAI ent = EntityAI.Cast(nearestObject);
      if (ent && ent.IsUniversalTemperatureSource() && ent != m_Player)
      {
        if (vector.DistanceSq(m_Player.GetPosition(), ent.GetPosition()) > Math.SqrFloat(ent.GetUniversalTemperatureSource().GetMaxRange()))
          continue;
        m_UTemperatureSources.Insert(ent.GetUniversalTemperatureSource());
      }
    }
    if (m_Player.GetItemInHands() && m_Player.GetItemInHands().IsUniversalTemperatureSource())
      m_UTemperatureSources.Insert(m_Player.GetItemInHands().GetUniversalTemperatureSource());
  }
References vector::DistanceSq(), GameConstants::ENVIRO_TEMP_SOURCES_LOOKUP_RADIUS, GetGame(), m_Player, m_UTemperatureSources, and Math::SqrFloat().
Referenced by Update().
GetDayOrNight()
float Environment::GetDayOrNight () inline protected
Definition at line 1051 of file Environment.c.
  {
    return m_DayOrNight;
  }
References m_DayOrNight.
GetDebugMessage()
string Environment::GetDebugMessage () inline protected
debug
Definition at line 1014 of file Environment.c.
  {
    string message;
    message += "Player stats";
    message += "\nHeat comfort: " + m_HeatComfort.ToString();
    message += "\nInside: " + IsInsideBuilding().ToString() + " (" + m_Player.GetSurfaceType() + ")";
    message += "\nUnder roof: " + m_IsUnderRoof.ToString() + " (" + GetNextRoofCheck() + ")";
    if (IsWaterContact() && m_WaterLevel > WATER_LEVEL_NONE)
      message += "\nWater Level: " + m_WaterLevel;
    message += "\n\nWeather stats";
    message += "\nEnv temperature (base): " + g_Game.GetMission().GetWorldData().GetBaseEnvTemperature().ToString();
    message += "\nEnv temperature (modified): " + m_EnvironmentTemperature.ToString();
    message += "\nWind: " + m_Wind.ToString() + " (x" + GetWindModifierPerSurface() + ")";
    message += "\nRain: " + m_Rain.ToString();
    message += "\nDay/Night (1/0): " + m_DayOrNight.ToString();
    message += "\nFog: " + m_Fog.ToString();
    message += "\nClouds: " + m_Clouds.ToString();
    message += "\nHeight: " + GetTemperatureHeightCorrection().ToString();
    message += "\nWet delta: " + GetWetDelta().ToString();
    return message;
  }
References g_Game, GetNextRoofCheck(), GetTemperatureHeightCorrection(), GetWetDelta(), GetWindModifierPerSurface(), IsInsideBuilding(), IsWaterContact(), m_Clouds, m_DayOrNight, m_EnvironmentTemperature, m_Fog, m_HeatComfort, m_IsUnderRoof, m_Player, m_Rain, m_WaterLevel, m_Wind, bool::ToString(), float::ToString(), and WATER_LEVEL_NONE.
GetEnvironmentTemperature()
float Environment::GetEnvironmentTemperature () inline protected
Definition at line 344 of file Environment.c.
  {
    float temperature;
    temperature = g_Game.GetMission().GetWorldData().GetBaseEnvTemperature();
    temperature += Math.AbsFloat(temperature * m_Clouds * GameConstants.ENVIRO_CLOUDS_TEMP_EFFECT);
    if (IsWaterContact())
      temperature -= Math.AbsFloat(temperature * GameConstants.ENVIRO_WATER_TEMPERATURE_COEF);
    if (IsInsideBuilding() || m_IsUnderRoofBuilding)
      temperature += Math.AbsFloat(temperature * GameConstants.ENVIRO_TEMPERATURE_INSIDE_COEF);
    else if (IsInsideVehicle())
      temperature += Math.AbsFloat(temperature * GameConstants.ENVIRO_TEMPERATURE_INSIDE_VEHICLE_COEF);
    else if (IsUnderRoof() && !m_IsUnderRoofBuilding)
    {
      temperature += Math.AbsFloat(temperature * GameConstants.ENVIRO_TEMPERATURE_UNDERROOF_COEF);
      temperature -= GameConstants.ENVIRO_TEMPERATURE_WIND_COEF * GetWindModifierPerSurface() * m_Wind;
    }
    else
    {
      temperature -= GameConstants.ENVIRO_TEMPERATURE_WIND_COEF * GetWindModifierPerSurface() * m_Wind;
      temperature -= Math.AbsFloat(temperature * m_Fog * GameConstants.ENVIRO_FOG_TEMP_EFFECT);
      temperature -= GetTemperatureHeightCorrection();
    }
    // incorporate temperature from temperature sources (buffer)
    if (Math.AbsFloat(m_UTSAverageTemperature) > 0.001)
      temperature += m_UTSAverageTemperature;
    return temperature;
  }
References Math::AbsFloat(), GameConstants::ENVIRO_CLOUDS_TEMP_EFFECT, GameConstants::ENVIRO_FOG_TEMP_EFFECT, GameConstants::ENVIRO_TEMPERATURE_INSIDE_COEF, GameConstants::ENVIRO_TEMPERATURE_INSIDE_VEHICLE_COEF, GameConstants::ENVIRO_TEMPERATURE_UNDERROOF_COEF, GameConstants::ENVIRO_TEMPERATURE_WIND_COEF, GameConstants::ENVIRO_WATER_TEMPERATURE_COEF, g_Game, GetTemperatureHeightCorrection(), GetWindModifierPerSurface(), IsInsideBuilding(), IsInsideVehicle(), IsUnderRoof(), IsWaterContact(), m_Clouds, m_Fog, m_IsUnderRoofBuilding, m_UTSAverageTemperature, and m_Wind.
Referenced by GetWetDelta(), and SetEnvironmentTemperature().
GetNextRoofCheck()
int Environment::GetNextRoofCheck () inline protected
Definition at line 1038 of file Environment.c.
  {
    return (GameConstants.ENVIRO_TICK_ROOF_RC_CHECK - m_RoofCheckTimer) + 1;
  }
References GameConstants::ENVIRO_TICK_ROOF_RC_CHECK, and m_RoofCheckTimer.
Referenced by GetDebugMessage().
GetPlayerHeat()
float Environment::GetPlayerHeat () inline protected
Returns heat player generated based on player's movement speed (for now)
Definition at line 219 of file Environment.c.
  {
    float heat = Math.Max(m_PlayerSpeed * GameConstants.ENVIRO_DEFAULT_ENTITY_HEAT, GameConstants.ENVIRO_DEFAULT_ENTITY_HEAT);
    return heat;
  }
References GameConstants::ENVIRO_DEFAULT_ENTITY_HEAT, m_PlayerSpeed, and Math::Max().
Referenced by CollectAndSetPlayerData(), and ProcessItemsHeat().
GetTemperature()
float Environment::GetTemperature () inline protected
Definition at line 338 of file Environment.c.
  {
    return m_EnvironmentTemperature;
  }
References m_EnvironmentTemperature.
GetTemperatureHeightCorrection()
float Environment::GetTemperatureHeightCorrection () inline protected
Definition at line 324 of file Environment.c.
  {
    float temperature_reduction = Math.Max(0, (m_PlayerHeightPos * GameConstants.ENVIRO_TEMPERATURE_HEIGHT_REDUCTION));
    return temperature_reduction;
  }
References GameConstants::ENVIRO_TEMPERATURE_HEIGHT_REDUCTION, m_PlayerHeightPos, and Math::Max().
Referenced by GetDebugMessage(), and GetEnvironmentTemperature().
GetUniversalSourcesTemperageAverage()
float Environment::GetUniversalSourcesTemperageAverage () inline protected
Definition at line 923 of file Environment.c.
  {
    return m_UTSAverageTemperature;
  }
References m_UTSAverageTemperature.
GetWaterLevel()
float Environment::GetWaterLevel () inline protected
Definition at line 1043 of file Environment.c.
  {
    if (IsWaterContact() && m_WaterLevel > WATER_LEVEL_NONE)
      return m_WaterLevel;
    else
      return 0;
  }
References IsWaterContact(), m_WaterLevel, and WATER_LEVEL_NONE.
GetWetDelta()
float Environment::GetWetDelta () inline protected
player is getting wet by movement/swimming in water (+differentiate wetDelta by water level)
player is getting wet from rain
player is drying
Definition at line 377 of file Environment.c.
  {
    float wetDelta = 0;
    if (IsWaterContact())
    {
      if (m_WaterLevel >= WATER_LEVEL_HIGH)
        wetDelta = 1;
      else if (m_WaterLevel >= WATER_LEVEL_MID && m_WaterLevel < WATER_LEVEL_HIGH)
        wetDelta = 0.66;
      else if (m_WaterLevel >= WATER_LEVEL_LOW && m_WaterLevel < WATER_LEVEL_MID)
        wetDelta = 0.66;
      else if (m_WaterLevel >= WATER_LEVEL_NONE && m_WaterLevel < WATER_LEVEL_LOW)
        wetDelta = 0.33;
    }
    else if (IsRaining() && !IsInsideBuilding() && !IsUnderRoof() && !IsInsideVehicle())
    {
      wetDelta = GameConstants.ENVIRO_WET_INCREMENT * GameConstants.ENVIRO_TICKS_TO_WETNESS_CALCULATION * (m_Rain) * (1 + (GameConstants.ENVIRO_WIND_EFFECT * m_Wind));
    }
    else
    {
      float tempEffect = Math.Max(m_PlayerHeat + GetEnvironmentTemperature(), 1.0);
      float weatherEffect = ((1 - (m_Fog * GameConstants.ENVIRO_FOG_DRY_EFFECT))) * (1 - (m_Clouds * GameConstants.ENVIRO_CLOUD_DRY_EFFECT));
      if (weatherEffect <= 0)
        weatherEffect = 1.0;
      wetDelta = -(GameConstants.ENVIRO_DRY_INCREMENT * weatherEffect * tempEffect);
      if (!IsInsideBuilding())
        wetDelta *= 1 + (GameConstants.ENVIRO_WIND_EFFECT * m_Wind);
    }
    return wetDelta;
  }
References GameConstants::ENVIRO_CLOUD_DRY_EFFECT, GameConstants::ENVIRO_DRY_INCREMENT, GameConstants::ENVIRO_FOG_DRY_EFFECT, GameConstants::ENVIRO_TICKS_TO_WETNESS_CALCULATION, GameConstants::ENVIRO_WET_INCREMENT, GameConstants::ENVIRO_WIND_EFFECT, GetEnvironmentTemperature(), IsInsideBuilding(), IsInsideVehicle(), IsRaining(), IsUnderRoof(), IsWaterContact(), m_Clouds, m_Fog, m_PlayerHeat, m_Rain, m_WaterLevel, m_Wind, Math::Max(), WATER_LEVEL_HIGH, WATER_LEVEL_LOW, WATER_LEVEL_MID, and WATER_LEVEL_NONE.
Referenced by ApplyWetnessToItem(), and GetDebugMessage().
GetWindModifierPerSurface()
float Environment::GetWindModifierPerSurface () inline protected
Definition at line 330 of file Environment.c.
  {
    if (IsUnderRoofBuilding())
      return 0.0;
    return g_Game.ConfigGetFloat("CfgSurfaces " + m_SurfaceType + " windModifier");
  }
References g_Game, IsUnderRoofBuilding(), and m_SurfaceType.
Referenced by GetDebugMessage(), and GetEnvironmentTemperature().
Init()
void Environment::Init (PlayerBase pPlayer) inline protected
whole body slots
upper body part slots
bottom body part slots
lower body part slots
heat comfort related slots
Definition at line 69 of file Environment.c.
  {
    m_Player = pPlayer;
    m_PlayerSpeed = 0.0;
    m_WetDryTick = 0.0;
    m_RoofCheckTimer = 0.0;
    m_WaterLevel = 0.0;
    m_HeatComfort = 0.0;
    m_IsUnderRoof = false;
    m_IsInWater = false;
    m_SurfaceType = "cp_dirt";
    m_HeatBufferTimer = 0.0;
    m_WindAverageBuffer = new SimpleMovingAverage<float>(30, 0.5);
    m_UTSAverageTemperature = 0.0;
    m_UTemperatureSources = new array<UTemperatureSource>();
    m_UTSAverageTemperatureBuffer = new SimpleMovingAverage<float>(10, 0);
    m_SlotIdsComplete = new array<int>;
    m_SlotIdsComplete = {
      InventorySlots.HEADGEAR,
      InventorySlots.MASK,
      InventorySlots.EYEWEAR,
      InventorySlots.GLOVES,
      InventorySlots.ARMBAND,
      InventorySlots.BODY,
      InventorySlots.HIPS,
      InventorySlots.VEST,
      InventorySlots.BACK,
      InventorySlots.LEGS,
      InventorySlots.FEET
    };
    m_SlotIdsUpper = new array<int>;
    m_SlotIdsUpper = {
      InventorySlots.GLOVES,
      InventorySlots.ARMBAND,
      InventorySlots.BODY,
      InventorySlots.HIPS,
      InventorySlots.VEST,
      InventorySlots.BACK,
      InventorySlots.LEGS,
      InventorySlots.FEET
    };
    m_SlotIdsBottom = new array<int>;
    m_SlotIdsBottom = {
      InventorySlots.HIPS,
      InventorySlots.LEGS,
      InventorySlots.FEET
    };
    m_SlotIdsLower = new array<int>;
    m_SlotIdsLower = {
      InventorySlots.FEET,
    };
    m_HeadParts = new array<int>;
    m_HeadParts = {
      InventorySlots.HEADGEAR,
      InventorySlots.MASK,
    };
    m_BodyParts = new array<int>;
    m_BodyParts = {
      InventorySlots.GLOVES,
      InventorySlots.BODY,
      InventorySlots.BACK,
      InventorySlots.VEST,
    };
    m_FeetParts = new array<int>;
    m_FeetParts = {
      InventorySlots.LEGS,
      InventorySlots.FEET,
    };
  }
References m_BodyParts, m_FeetParts, m_HeadParts, m_HeatBufferTimer, m_HeatComfort, m_IsInWater, m_IsUnderRoof, m_Player, m_PlayerSpeed, m_RoofCheckTimer, m_SlotIdsBottom, m_SlotIdsComplete, m_SlotIdsLower, m_SlotIdsUpper, m_SurfaceType, m_UTemperatureSources, m_UTSAverageTemperature, m_UTSAverageTemperatureBuffer, m_WaterLevel, m_WetDryTick, and m_WindAverageBuffer.
IsInsideBuilding()
bool Environment::IsInsideBuilding () inline protected
Definition at line 235 of file Environment.c.
  {
    return m_Player && m_Player.IsSoundInsideBuilding();
  }
References m_Player.
Referenced by GetDebugMessage(), GetEnvironmentTemperature(), GetWetDelta(), and Update().
IsInsideVehicle()
bool Environment::IsInsideVehicle () inline protected
Definition at line 240 of file Environment.c.
  {
    return m_Player && m_Player.IsInVehicle();
  }
References m_Player.
Referenced by CheckUnderRoof(), GetEnvironmentTemperature(), GetWetDelta(), and Update().
IsRaining()
bool Environment::IsRaining () inline protected
Definition at line 250 of file Environment.c.
  {
    return m_Rain > RAIN_LIMIT_LOW;
  }
References m_Rain, and RAIN_LIMIT_LOW.
Referenced by GetWetDelta(), and Update().
IsTemperatureSet()
bool Environment::IsTemperatureSet () inline protected
Definition at line 210 of file Environment.c.
  {
    return m_IsTempSet;
  }
References m_IsTempSet.
IsUnderRoof()
bool Environment::IsUnderRoof () inline protected
Definition at line 225 of file Environment.c.
  {
    return m_IsUnderRoof;
  }
References m_IsUnderRoof.
Referenced by GetEnvironmentTemperature(), GetWetDelta(), and Update().
IsUnderRoofBuilding()
bool Environment::IsUnderRoofBuilding () inline private
Definition at line 245 of file Environment.c.
  {
    return m_IsUnderRoofBuilding;
  }
References m_IsUnderRoofBuilding.
Referenced by CheckWaterContact(), and GetWindModifierPerSurface().
IsWaterContact()
bool Environment::IsWaterContact () inline protected
Definition at line 230 of file Environment.c.
  {
    return m_IsInWater;
  }
References m_IsInWater.
Referenced by GetDebugMessage(), GetEnvironmentTemperature(), GetWaterLevel(), GetWetDelta(), and Update().
LogDryWetProcess()
void Environment::LogDryWetProcess (string message, bool indented = false) inline private
Definition at line 1056 of file Environment.c.
  {
#ifdef DIAG_DEVELOPER
    if (m_DebugLogDryWet)
    {
      string indentation = "";
      if (indented)
        indentation = "|--";
      Debug.Log(string.Format("%1 %2", indentation, message));
    }
#endif
  }
References Debug::Log().
Referenced by ApplyDrynessToItemEx(), ApplyWetnessToItem(), ProcessItemsDryness(), and ProcessItemsWetness().
OverridenHeatComfort()
bool Environment::OverridenHeatComfort (out float value) protected
DEPRECATED.
ProcessItemsDryness()
void Environment::ProcessItemsDryness () inline protected
Definition at line 513 of file Environment.c.
  {
    EntityAI attachment;
    ItemBase item;
    int attCount = m_Player.GetInventory().AttachmentCount();
    LogDryWetProcess(string.Format("Environment :: ProcessItemsDryness (update interval=%1s)", GameConstants.ENVIRO_TICK_RATE));
    EnvironmentDrynessData drynessData = new EnvironmentDrynessData();
    drynessData.m_UseTemperatureSources = m_HasTemperatureSources;
    if (m_HasTemperatureSources)
    {
      float distance = vector.Distance(m_UTemperatureSources[0].GetPosition(), m_Player.GetPosition());
      distance = Math.Max(distance, 0.1);
      drynessData.m_TemperatureSourceDistance = distance;
      LogDryWetProcess(string.Format("distance to heatsource: %1 m", distance));
    }
    for (int attIdx = 0; attIdx < attCount; attIdx++)
    {
      attachment = m_Player.GetInventory().GetAttachmentFromIndex(attIdx);
      if (attachment && attachment.IsItemBase())
      {
        item = ItemBase.Cast(attachment);
        if (item)
          ApplyDrynessToItemEx(item, drynessData);
      }
    }
    if (m_Player.GetItemInHands())
      ApplyDrynessToItemEx(m_Player.GetItemInHands(), drynessData);
    LogDryWetProcess("==========");
  }
References ApplyDrynessToItemEx(), vector::Distance(), GameConstants::ENVIRO_TICK_RATE, GetPosition, LogDryWetProcess(), m_HasTemperatureSources, m_Player, m_UTemperatureSources, and Math::Max().
Referenced by Update().
ProcessItemsHeat()
void Environment::ProcessItemsHeat () inline protected
Calculates and process temperature of items.
Heat Comfort
Heat (from items);
Definition at line 734 of file Environment.c.
  {
    float hcHead, hcBody, hcFeet;
    float hHead, hBody, hFeet;
    float heatComfortAvg;
    float heatAvg;
    BodyPartHeatProperties(m_HeadParts, GameConstants.ENVIRO_HEATCOMFORT_HEADPARTS_WEIGHT, hcHead, hHead);
    BodyPartHeatProperties(m_BodyParts, GameConstants.ENVIRO_HEATCOMFORT_BODYPARTS_WEIGHT, hcBody, hBody);
    BodyPartHeatProperties(m_FeetParts, GameConstants.ENVIRO_HEATCOMFORT_FEETPARTS_WEIGHT, hcFeet, hFeet);
    heatComfortAvg = (hcHead + hcBody + hcFeet) / 3;
    heatAvg = (hHead + hBody + hFeet) / 3;
    heatAvg = heatAvg * GameConstants.ENVIRO_ITEM_HEAT_TRANSFER_COEF;
    // heat buffer
    float applicableHB = 0.0;
    if (m_UTSAverageTemperature < 0.001)
    {
      applicableHB = m_Player.GetStatHeatBuffer().Get() / 30.0;
      if (applicableHB > 0.0)
      {
        if (m_HeatBufferTimer > 1.0)
          m_Player.GetStatHeatBuffer().Add(Math.Min(EnvTempToCoef(m_EnvironmentTemperature), -0.1) * GameConstants.ENVIRO_PLAYER_HEATBUFFER_DECREASE);
        else
          m_HeatBufferTimer += GameConstants.ENVIRO_PLAYER_HEATBUFFER_TICK;
      }
      else
        m_HeatBufferTimer = 0.0;
    }
    else
    {
      applicableHB = m_Player.GetStatHeatBuffer().Get() / 30.0;
      if (m_HeatComfort > PlayerConstants.THRESHOLD_HEAT_COMFORT_MINUS_WARNING)
      {
        m_Player.GetStatHeatBuffer().Add(GameConstants.ENVIRO_PLAYER_HEATBUFFER_INCREASE);
        m_HeatBufferTimer = 0.0;
      }
      else
        m_HeatBufferTimer = 0.0;
    }
    m_HeatComfort = (heatComfortAvg + heatAvg + (GetPlayerHeat() / 100)) + EnvTempToCoef(m_EnvironmentTemperature);
    if ((m_HeatComfort + applicableHB) < (PlayerConstants.THRESHOLD_HEAT_COMFORT_PLUS_WARNING - 0.01))
      m_HeatComfort += applicableHB;
    else
    {
      if (m_HeatComfort <= (PlayerConstants.THRESHOLD_HEAT_COMFORT_PLUS_WARNING - 0.01))
        m_HeatComfort = PlayerConstants.THRESHOLD_HEAT_COMFORT_PLUS_WARNING - 0.01;
    }
    m_HeatComfort = Math.Clamp(m_HeatComfort, m_Player.GetStatHeatComfort().GetMin(), m_Player.GetStatHeatComfort().GetMax());
    m_Player.GetStatHeatComfort().Set(m_HeatComfort);
  }
References BodyPartHeatProperties(), Math::Clamp(), GameConstants::ENVIRO_HEATCOMFORT_BODYPARTS_WEIGHT, GameConstants::ENVIRO_HEATCOMFORT_FEETPARTS_WEIGHT, GameConstants::ENVIRO_HEATCOMFORT_HEADPARTS_WEIGHT, GameConstants::ENVIRO_ITEM_HEAT_TRANSFER_COEF, GameConstants::ENVIRO_PLAYER_HEATBUFFER_DECREASE, GameConstants::ENVIRO_PLAYER_HEATBUFFER_INCREASE, GameConstants::ENVIRO_PLAYER_HEATBUFFER_TICK, EnvTempToCoef(), GetPlayerHeat(), m_BodyParts, m_EnvironmentTemperature, m_FeetParts, m_HeadParts, m_HeatBufferTimer, m_HeatComfort, m_Player, m_UTSAverageTemperature, Math::Min(), PlayerConstants::THRESHOLD_HEAT_COMFORT_MINUS_WARNING, and PlayerConstants::THRESHOLD_HEAT_COMFORT_PLUS_WARNING.
Referenced by Update().
ProcessItemsWetness()
void Environment::ProcessItemsWetness (array< int > pSlotIds) inline protected
Definition at line 478 of file Environment.c.
  {
    EntityAI attachment;
    int playerAttachmentCount = m_Player.GetInventory().AttachmentCount();
    LogDryWetProcess(string.Format("Environment :: ProcessItemsWetness (update interval=%1s)", GameConstants.ENVIRO_TICK_RATE));
    for (int attIdx = 0; attIdx < playerAttachmentCount; ++attIdx)
    {
      attachment = m_Player.GetInventory().GetAttachmentFromIndex(attIdx);
      if (attachment.IsItemBase())
      {
        int attachmentSlotsCount = attachment.GetInventory().GetSlotIdCount();
        for (int attachmentSlotId = 0; attachmentSlotId < attachmentSlotsCount; ++attachmentSlotId)
        {
          int attachmentSlot = attachment.GetInventory().GetSlotId(attachmentSlotId);
          for (int i = 0; i < pSlotIds.Count(); ++i)
          {
            if (attachmentSlot == pSlotIds.Get(i))
            {
              ApplyWetnessToItem(ItemBase.Cast(attachment));
              break;
            }
          }
        }
      }
    }
    if (m_Player.GetItemInHands())
      ApplyWetnessToItem(m_Player.GetItemInHands());
    LogDryWetProcess("==========");
  }
References ApplyWetnessToItem(), GameConstants::ENVIRO_TICK_RATE, LogDryWetProcess(), and m_Player.
Referenced by ProcessWetnessByRain(), and ProcessWetnessByWaterLevel().
ProcessTemperatureSources()
void Environment::ProcessTemperatureSources () inline protected
adds average of 2 most significat sources to buffer
Definition at line 894 of file Environment.c.
  {
    if (m_UTemperatureSources.Count() == 0)
    {
      m_HasTemperatureSources = false;
      m_UTSAverageTemperature = m_UTSAverageTemperatureBuffer.Add(0);
      return;
    }
    array<float> utsTemperatures = new array<float>();
    // get temperature from the source (based on distance), save it for min/max filtering
    foreach (UTemperatureSource tempSource : m_UTemperatureSources)
      utsTemperatures.Insert(CalcTemperatureFromTemperatureSource(tempSource));
    float min = MiscGameplayFunctions.GetMinValue(utsTemperatures);
    float max = MiscGameplayFunctions.GetMaxValue(utsTemperatures);
    if (max > 0 && min < 0)
    {
      m_UTSAverageTemperature = m_UTSAverageTemperatureBuffer.Add((max + min) * 0.5);
    }
    else
      m_UTSAverageTemperature = m_UTSAverageTemperatureBuffer.Add(max);
    m_HasTemperatureSources = true;
  }
References CalcTemperatureFromTemperatureSource(), m_HasTemperatureSources, m_UTemperatureSources, m_UTSAverageTemperature, and m_UTSAverageTemperatureBuffer.
Referenced by Update().
ProcessWetnessByRain()
void Environment::ProcessWetnessByRain () inline protected
Definition at line 447 of file Environment.c.
  {
    ProcessItemsWetness(m_SlotIdsComplete);
  }
References m_SlotIdsComplete, and ProcessItemsWetness().
Referenced by Update().
ProcessWetnessByWaterLevel()
void Environment::ProcessWetnessByWaterLevel (float pWaterLevel) inline protected
complete
upper part
bottom part
feet
Definition at line 452 of file Environment.c.
  {
    // process attachments by water depth
    if (pWaterLevel >= WATER_LEVEL_HIGH)
    {
      ProcessItemsWetness(m_SlotIdsComplete);
    }
    else if (pWaterLevel >= WATER_LEVEL_MID && pWaterLevel < WATER_LEVEL_HIGH)
    {
      ProcessItemsWetness(m_SlotIdsUpper);
    }
    else if (pWaterLevel >= WATER_LEVEL_LOW && pWaterLevel < WATER_LEVEL_MID)
    {
      ProcessItemsWetness(m_SlotIdsBottom);
    }
    else if (pWaterLevel >= WATER_LEVEL_NONE && pWaterLevel < WATER_LEVEL_LOW)
    {
      ProcessItemsWetness(m_SlotIdsLower);
    }
  }
References m_SlotIdsBottom, m_SlotIdsComplete, m_SlotIdsLower, m_SlotIdsUpper, ProcessItemsWetness(), WATER_LEVEL_HIGH, WATER_LEVEL_LOW, WATER_LEVEL_MID, and WATER_LEVEL_NONE.
Referenced by Update().
SetEnvironmentTemperature()
void Environment::SetEnvironmentTemperature () inline protected
Definition at line 441 of file Environment.c.
  {
    m_IsTempSet = true;
    m_EnvironmentTemperature = GetEnvironmentTemperature();
  }
References GetEnvironmentTemperature(), m_EnvironmentTemperature, and m_IsTempSet.
Referenced by CollectAndSetEnvironmentData().
Update()
void Environment::Update (float pDelta) inline protected
check if player is under roof (only if the Building check is false)
Updates data
Process temperature
Process item wetness/dryness
setting of wetness/dryiness of player
reset item wetness counter;
Definition at line 156 of file Environment.c.
  {
    if (m_Player)
    {
      m_RoofCheckTimer += pDelta;
      if (m_RoofCheckTimer >= GameConstants.ENVIRO_TICK_ROOF_RC_CHECK)
      {
        if (!IsInsideBuilding())
          CheckUnderRoof();
        m_RoofCheckTimer = 0;
      }
      m_Time += pDelta;
      if (m_Time >= GameConstants.ENVIRO_TICK_RATE)
      {
        m_Time = 0;
        m_WetDryTick++; // Sets whether it is time to add wetness to items and clothing
        CheckWaterContact(m_WaterLevel);
        CollectAndSetPlayerData();
        CollectAndSetEnvironmentData();
        GatherTemperatureSources();
        ProcessTemperatureSources();
        ProcessItemsHeat();
        if (m_WetDryTick >= GameConstants.ENVIRO_TICKS_TO_WETNESS_CALCULATION)
        {
          if (IsWaterContact())
            ProcessWetnessByWaterLevel(m_WaterLevel);
          else if (IsRaining() && !IsInsideBuilding() && !IsUnderRoof() && !IsInsideVehicle())
            ProcessWetnessByRain();
          else
            ProcessItemsDryness();
          if ((m_ItemsWetnessMax < GameConstants.STATE_WET) && (m_Player.GetStatWet().Get() == 1))
            m_Player.GetStatWet().Set(0);
          else if ((m_ItemsWetnessMax >= GameConstants.STATE_WET) && (m_Player.GetStatWet().Get() == 0))
            m_Player.GetStatWet().Set(1);
          m_WetDryTick = 0;
          m_ItemsWetnessMax = 0;
        }
      }
    }
  }
References CheckUnderRoof(), CheckWaterContact(), CollectAndSetEnvironmentData(), CollectAndSetPlayerData(), GameConstants::ENVIRO_TICK_RATE, GameConstants::ENVIRO_TICK_ROOF_RC_CHECK, GameConstants::ENVIRO_TICKS_TO_WETNESS_CALCULATION, GatherTemperatureSources(), IsInsideBuilding(), IsInsideVehicle(), IsRaining(), IsUnderRoof(), IsWaterContact(), m_ItemsWetnessMax, m_Player, m_RoofCheckTimer, m_Time, m_WaterLevel, m_WetDryTick, ProcessItemsDryness(), ProcessItemsHeat(), ProcessTemperatureSources(), ProcessWetnessByRain(), ProcessWetnessByWaterLevel(), and GameConstants::STATE_WET.
Member Data Documentation
m_BodyParts
ref array<int> Environment::m_BodyParts protected
Definition at line 48 of file Environment.c.
Referenced by Init(), and ProcessItemsHeat().
m_Clouds
float Environment::m_Clouds = 0 protected
Definition at line 27 of file Environment.c.
Referenced by CollectAndSetEnvironmentData(), GetDebugMessage(), GetEnvironmentTemperature(), and GetWetDelta().
m_DayOrNight
float Environment::m_DayOrNight = 0 protected
Definition at line 26 of file Environment.c.
Referenced by CollectAndSetEnvironmentData(), GetDayOrNight(), and GetDebugMessage().
m_EnvironmentTemperature
float Environment::m_EnvironmentTemperature = 0 protected
Definition at line 28 of file Environment.c.
Referenced by GetDebugMessage(), GetTemperature(), ProcessItemsHeat(), and SetEnvironmentTemperature().
m_FeetParts
ref array<int> Environment::m_FeetParts protected
Definition at line 49 of file Environment.c.
Referenced by Init(), and ProcessItemsHeat().
m_Fog
float Environment::m_Fog = 0 protected
Definition at line 25 of file Environment.c.
Referenced by CollectAndSetEnvironmentData(), GetDebugMessage(), GetEnvironmentTemperature(), and GetWetDelta().
m_HasTemperatureSources
bool Environment::m_HasTemperatureSources protected
Definition at line 53 of file Environment.c.
Referenced by ProcessItemsDryness(), and ProcessTemperatureSources().
m_HeadParts
ref array<int> Environment::m_HeadParts protected
Definition at line 47 of file Environment.c.
Referenced by Init(), and ProcessItemsHeat().
m_HeatBufferTimer
float Environment::m_HeatBufferTimer protected
DEPRECATED.
Definition at line 40 of file Environment.c.
Referenced by Init(), and ProcessItemsHeat().
m_HeatComfort
float Environment::m_HeatComfort protected
Definition at line 20 of file Environment.c.
Referenced by GetDebugMessage(), Init(), and ProcessItemsHeat().
m_HeatSourceTemp
float Environment::m_HeatSourceTemp protected
Definition at line 39 of file Environment.c.
m_IsInWater
bool Environment::m_IsInWater protected
Definition at line 36 of file Environment.c.
Referenced by CheckWaterContact(), Init(), and IsWaterContact().
m_IsTempSet
bool Environment::m_IsTempSet protected
Definition at line 37 of file Environment.c.
Referenced by IsTemperatureSet(), and SetEnvironmentTemperature().
m_IsUnderRoof
bool Environment::m_IsUnderRoof protected
Definition at line 34 of file Environment.c.
Referenced by CheckUnderRoof(), GetDebugMessage(), Init(), and IsUnderRoof().
m_IsUnderRoofBuilding
bool Environment::m_IsUnderRoofBuilding private
Definition at line 35 of file Environment.c.
Referenced by CheckUnderRoof(), GetEnvironmentTemperature(), and IsUnderRoofBuilding().
m_ItemsWetnessMax
float Environment::m_ItemsWetnessMax protected
Definition at line 11 of file Environment.c.
Referenced by ApplyDrynessToItemEx(), ApplyWetnessToItem(), and Update().
m_Player
PlayerBase Environment::m_Player protected
Definition at line 15 of file Environment.c.
Referenced by ApplyDrynessToItemEx(), ApplyWetnessToItem(), BodyPartHeatProperties(), CalcTemperatureFromTemperatureSource(), CheckUnderRoof(), CheckWaterContact(), CollectAndSetPlayerData(), GatherTemperatureSources(), GetDebugMessage(), Init(), IsInsideBuilding(), IsInsideVehicle(), ProcessItemsDryness(), ProcessItemsHeat(), ProcessItemsWetness(), and Update().
m_PlayerHeat
float Environment::m_PlayerHeat protected
Definition at line 19 of file Environment.c.
Referenced by CollectAndSetPlayerData(), and GetWetDelta().
m_PlayerHeightPos
float Environment::m_PlayerHeightPos protected
Definition at line 16 of file Environment.c.
Referenced by CollectAndSetPlayerData(), and GetTemperatureHeightCorrection().
m_PlayerSpeed
float Environment::m_PlayerSpeed protected
Definition at line 17 of file Environment.c.
Referenced by CollectAndSetPlayerData(), GetPlayerHeat(), and Init().
m_PlayerTemperature
float Environment::m_PlayerTemperature protected
Definition at line 18 of file Environment.c.
m_Rain
float Environment::m_Rain = 0 protected
Definition at line 23 of file Environment.c.
Referenced by CollectAndSetEnvironmentData(), GetDebugMessage(), GetWetDelta(), and IsRaining().
m_RoofCheckTimer
float Environment::m_RoofCheckTimer protected
keeps wetness of most wet item in player's possesion
Definition at line 12 of file Environment.c.
Referenced by GetNextRoofCheck(), Init(), and Update().
m_SlotIdsBottom
ref array<int> Environment::m_SlotIdsBottom protected
Definition at line 44 of file Environment.c.
Referenced by Init(), and ProcessWetnessByWaterLevel().
m_SlotIdsComplete
ref array<int> Environment::m_SlotIdsComplete protected
Definition at line 42 of file Environment.c.
Referenced by Init(), ProcessWetnessByRain(), and ProcessWetnessByWaterLevel().
m_SlotIdsLower
ref array<int> Environment::m_SlotIdsLower protected
Definition at line 45 of file Environment.c.
Referenced by Init(), and ProcessWetnessByWaterLevel().
m_SlotIdsUpper
ref array<int> Environment::m_SlotIdsUpper protected
Definition at line 43 of file Environment.c.
Referenced by Init(), and ProcessWetnessByWaterLevel().
m_SurfaceType
string Environment::m_SurfaceType protected
Definition at line 30 of file Environment.c.
Referenced by CheckWaterContact(), GetWindModifierPerSurface(), and Init().
m_Time
float Environment::m_Time = 0 protected
Definition at line 29 of file Environment.c.
Referenced by Update().
m_UTemperatureSources
ref array<UTemperatureSource> Environment::m_UTemperatureSources protected
Definition at line 55 of file Environment.c.
Referenced by GatherTemperatureSources(), Init(), ProcessItemsDryness(), and ProcessTemperatureSources().
m_UTSAverageTemperature
float Environment::m_UTSAverageTemperature protected
Definition at line 54 of file Environment.c.
Referenced by GetEnvironmentTemperature(), GetUniversalSourcesTemperageAverage(), Init(), ProcessItemsHeat(), and ProcessTemperatureSources().
m_UTSAverageTemperatureBuffer
ref SimpleMovingAverage<float> Environment::m_UTSAverageTemperatureBuffer protected
Definition at line 56 of file Environment.c.
Referenced by Init(), and ProcessTemperatureSources().
m_WaterLevel
float Environment::m_WaterLevel protected
Definition at line 33 of file Environment.c.
Referenced by GetDebugMessage(), GetWaterLevel(), GetWetDelta(), Init(), and Update().
m_WetDryTick
float Environment::m_WetDryTick protected
Definition at line 10 of file Environment.c.
Referenced by Init(), and Update().
m_Wind
float Environment::m_Wind = 0 protected
Definition at line 24 of file Environment.c.
Referenced by CollectAndSetEnvironmentData(), GetDebugMessage(), GetEnvironmentTemperature(), and GetWetDelta().
m_WindAverageBuffer
ref SimpleMovingAverage<float> Environment::m_WindAverageBuffer protected
Definition at line 51 of file Environment.c.
Referenced by CollectAndSetEnvironmentData(), and Init().
RAIN_LIMIT_LOW
const float Environment::RAIN_LIMIT_LOW = 0.05 private
Definition at line 3 of file Environment.c.
Referenced by IsRaining().
WATER_LEVEL_HIGH
const float Environment::WATER_LEVEL_HIGH = 1.5 private
Definition at line 5 of file Environment.c.
Referenced by CheckWaterContact(), GetWetDelta(), and ProcessWetnessByWaterLevel().
WATER_LEVEL_LOW
const float Environment::WATER_LEVEL_LOW = 0.5 private
Definition at line 7 of file Environment.c.
Referenced by GetWetDelta(), and ProcessWetnessByWaterLevel().
WATER_LEVEL_MID
const float Environment::WATER_LEVEL_MID = 1.2 private
Definition at line 6 of file Environment.c.
Referenced by CheckWaterContact(), GetWetDelta(), and ProcessWetnessByWaterLevel().
WATER_LEVEL_NONE
const float Environment::WATER_LEVEL_NONE = 0.15 private
Definition at line 8 of file Environment.c.
Referenced by GetDebugMessage(), GetWaterLevel(), GetWetDelta(), and ProcessWetnessByWaterLevel().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/Environment/Environment.c