DayZ: SceneObject Class Reference
SceneObject Class Reference
Protected Member Functions
SceneObject Init (string obj_name, vector pos)
EntityAI GetObject ()
string GetName ()
bool IsPlayer ()
string GetInitScript ()
void SetInitScript (string init_script)
void EditorShapeUpdatePos ()
void EditorShapeSetColor (int color)
void EditorShapeSelect ()
void EditorShapeDeselect ()
vector GetSize ()
void EditorShapeAdd ()
void EditorShapeRemove ()
void EditorLineRemove (SceneObject obj)
void EditorLineAdd (SceneObject obj)
void LinkEntityAI (EntityAI e)
bool IsLinkedWithSceneObject (SceneObject scene_object)
void LinkSceneObject (SceneObject scene_object, bool draw_line=true)
void UnlinkSceneObject (SceneObject scene_object)
void UnlinkAll ()
array< SceneObject > GetLinkedSceneObjects ()
int GetLinkedSceneObjectsCount ()
SceneObject GetLinkedSceneObject (int i)
EntityAI GetLinkedObject (int i)
void ~SceneObject ()
string GetTypeName ()
void PlaceOnSurface ()
void SetPosition (vector pos)
vector GetPosition ()
float GetHealth ()
float GetMaxHealth ()
void SetHealth (float value)
string GetPositionAsString ()
void SetPositionAsString (string string_pos)
float GetRotation ()
void SetRotation (float rot)
void SceneObjectSynch (Param p)
void AddRotation (float add_rot)
void AddAttachment (string att_name)
bool CanAttachment (EntityAI e)
void RemoveAttachment (EntityAI e)
array< EntityAI > GetAttachments ()
TStringArray GetConfigAttachments ()
Protected Attributes
EntityAI m_ObjectPtr
Shape m_DebugShapeBBox
string m_InitScript
string m_ObjectName
string m_ObjectNameOrigin
ref array< SceneObject > m_LinkedSceneObjects
ref map< SceneObject, Shape > m_LinkedSceneObjectsShapes
ref array< int > m_LinkedSceneObjectsIndices
Private Member Functions
override bool IsPlayer ()
Static Private Attributes
static const int COLOR_OBJ_BBOX_NORMAL = 0x00000000
static const int COLOR_OBJ_BBOX_SELECT = 0x1f007C00
Detailed Description
Definition at line 1 of file SceneObject.c.
Constructor & Destructor Documentation
~SceneObject()
void SceneObject::~SceneObject () inline protected
Definition at line 338 of file SceneObject.c.
  {
    if (m_ObjectPtr && m_ObjectPtr != GetGame().GetPlayer())
    {
      GetGame().ObjectDelete(m_ObjectPtr);
      m_ObjectPtr = NULL;
    }
    for (int i = 0; i < m_LinkedSceneObjects.Count(); i++)
      EditorLineRemove(m_LinkedSceneObjects.Get(i));
    EditorShapeRemove();
  }
References EditorLineRemove(), EditorShapeRemove(), GetGame(), GetPlayer(), m_LinkedSceneObjects, and m_ObjectPtr.
Member Function Documentation
AddAttachment()
void SceneObject::AddAttachment (string att_name) inline protected
Definition at line 520 of file SceneObject.c.
  {
    GetObject().GetInventory().CreateAttachment(att_name);
  }
References GetObject().
Referenced by PluginBase::SelectedObjectDuplicate().
AddRotation()
void SceneObject::AddRotation (float add_rot) inline protected
Definition at line 497 of file SceneObject.c.
  {
    if (m_ObjectPtr)
    {
      if (GetGame().IsClient() && GetGame().IsMultiplayer())
      {
        Param par = new Param3<string, EntityAI, Param>("AddRotation", m_ObjectPtr, new Param1<float>(add_rot));
        SceneObjectSynch(par);
      }
      else
      {
        vector v = m_ObjectPtr.GetOrientation();
        v[0] = v[0] + add_rot;
        m_ObjectPtr.SetOrientation(v);
        EditorShapeUpdatePos();
      }
    }
  }
References EditorShapeUpdatePos(), GetGame(), m_ObjectPtr, and SceneObjectSynch().
CanAttachment()
bool SceneObject::CanAttachment (EntityAI e) inline protected
Definition at line 528 of file SceneObject.c.
  {
    return GetObject().GetInventory().CanAddAttachment(e);
  }
References GetObject().
EditorLineAdd()
void SceneObject::EditorLineAdd (SceneObject obj) inline protected
Definition at line 224 of file SceneObject.c.
  {
    if (obj.GetObject() != NULL && GetObject() != NULL)
    {
      if (m_LinkedSceneObjectsShapes.Contains(obj))
        EditorLineRemove(obj);
      vector pos1 = obj.GetSize();
      pos1[0] = 0; pos1[1] = pos1[1] / 2; pos1[2] = 0;
      pos1 = pos1 + obj.GetObject().GetPosition();
      vector pos2 = GetSize();
      pos2[0] = 0; pos2[1] = pos2[1] / 2; pos2[2] = 0;
      pos2 = pos2 + GetObject().GetPosition();
      m_LinkedSceneObjectsShapes.Insert(obj, Debug.DrawArrow(pos1, pos2));
    }
  }
References Debug::DrawArrow(), EditorLineRemove(), GetObject(), GetSize(), and m_LinkedSceneObjectsShapes.
Referenced by PluginBase::EditorUpdate(), and LinkSceneObject().
EditorLineRemove()
void SceneObject::EditorLineRemove (SceneObject obj) inline protected
Definition at line 208 of file SceneObject.c.
  {
    for (int i = 0; i < m_LinkedSceneObjectsShapes.Count(); i++)
    {
      if (m_LinkedSceneObjectsShapes.GetKey(i) == obj)
      {
        m_LinkedSceneObjectsShapes.GetElement(i).Destroy();
        m_LinkedSceneObjectsShapes.Remove(obj);
        break;
      }
    }
  }
References m_LinkedSceneObjectsShapes.
Referenced by EditorLineAdd(), PluginBase::EditorUpdate(), UnlinkSceneObject(), and ~SceneObject().
EditorShapeAdd()
void SceneObject::EditorShapeAdd () inline protected
Definition at line 161 of file SceneObject.c.
  {
    if (m_DebugShapeBBox != NULL)
      return;
    vector min = "0 0 0";
    vector max = "0 0 0";
    vector size = GetSize();
    float width = size[0];
    float height = size[1];
    float length = size[2];
    float width_h = width * 0.5;
    float lenght_h = length * 0.5;
    min[0] = -width_h;
    min[1] = 0;
    min[2] = -lenght_h;
    max[0] = width_h;
    max[1] = height;
    max[2] = lenght_h;
    //Log("EditorShapeAdd -> "+m_ObjectPtr.Ptr().GetType());
    m_DebugShapeBBox = Debug.DrawBox(min, max);
    EditorShapeUpdatePos();
    EditorShapeDeselect();
  }
References Debug::DrawBox(), EditorShapeDeselect(), EditorShapeUpdatePos(), GetSize(), and m_DebugShapeBBox.
Referenced by PluginBase::EditorUpdate().
EditorShapeDeselect()
void SceneObject::EditorShapeDeselect () inline protected
Definition at line 129 of file SceneObject.c.
  {
    EditorShapeSetColor(COLOR_OBJ_BBOX_NORMAL);
  }
References COLOR_OBJ_BBOX_NORMAL, and EditorShapeSetColor().
Referenced by EditorShapeAdd(), and PluginBase::EditorUpdate().
EditorShapeRemove()
void SceneObject::EditorShapeRemove () inline protected
Definition at line 196 of file SceneObject.c.
  {
    if (m_DebugShapeBBox != NULL)
    {
      m_DebugShapeBBox.Destroy();
      m_DebugShapeBBox = NULL;
    }
  }
References m_DebugShapeBBox.
Referenced by PluginBase::EditorUpdate(), and ~SceneObject().
EditorShapeSelect()
void SceneObject::EditorShapeSelect () inline protected
Definition at line 121 of file SceneObject.c.
  {
    EditorShapeSetColor(COLOR_OBJ_BBOX_SELECT);
  }
References COLOR_OBJ_BBOX_SELECT, and EditorShapeSetColor().
Referenced by PluginBase::EditorUpdate().
EditorShapeSetColor()
void SceneObject::EditorShapeSetColor (int color) inline protected
Definition at line 112 of file SceneObject.c.
  {
    if (m_DebugShapeBBox)
      m_DebugShapeBBox.SetColor(color);
  }
References m_DebugShapeBBox.
Referenced by EditorShapeDeselect(), and EditorShapeSelect().
EditorShapeUpdatePos()
void SceneObject::EditorShapeUpdatePos () inline protected
Definition at line 97 of file SceneObject.c.
  {
    if (m_DebugShapeBBox != NULL)
    {
      vector mat[4];
      GetObject().GetTransform(mat);
      if (m_DebugShapeBBox != NULL)
        m_DebugShapeBBox.SetMatrix(mat);
    }
  }
References GetObject(), and m_DebugShapeBBox.
Referenced by AddRotation(), EditorShapeAdd(), SetPosition(), and SetRotation().
GetAttachments()
array< EntityAI > SceneObject::GetAttachments () inline protected
Definition at line 544 of file SceneObject.c.
  {
    array<EntityAI> ret = new array<EntityAI>;
    for (int i = 0; i < GetObject().GetInventory().AttachmentCount(); ++i)
      ret.Insert(GetObject().GetInventory().GetAttachmentFromIndex(i));
    return ret;
  }
References GetObject().
GetConfigAttachments()
TStringArray SceneObject::GetConfigAttachments () inline protected
Definition at line 557 of file SceneObject.c.
  {
    string type_name = GetTypeName();
    TStringArray cfg_attachments = new TStringArray;
    string cfg_path;
    if (GetGame().ConfigIsExisting(CFG_VEHICLESPATH + " " + type_name))
      cfg_path = CFG_VEHICLESPATH + " " + type_name + " attachments";
    else if (GetGame().ConfigIsExisting(CFG_WEAPONSPATH + " " + type_name))
      cfg_path = CFG_WEAPONSPATH + " " + type_name + " attachments";
    else if (GetGame().ConfigIsExisting(CFG_MAGAZINESPATH + " " + type_name))
      cfg_path = CFG_MAGAZINESPATH + " " + type_name + " attachments";
    GetGame().ConfigGetTextArray(cfg_path, cfg_attachments);
    return cfg_attachments;
  }
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, GetGame(), and GetTypeName().
Referenced by UIScriptedMenu::Refresh().
GetHealth()
float SceneObject::GetHealth () inline protected
Definition at line 409 of file SceneObject.c.
  {
    if (m_ObjectPtr)
      return m_ObjectPtr.GetHealth("", "");
    return 0;
  }
References m_ObjectPtr.
Referenced by UIScriptedMenu::Refresh(), and PluginConfigHandler::SaveSceneObjects().
GetInitScript()
string SceneObject::GetInitScript () inline protected
Definition at line 81 of file SceneObject.c.
  {
    return m_InitScript;
  }
References m_InitScript.
Referenced by UIPopupScript::OnOpen(), and PluginConfigHandler::SaveSceneObjects().
GetLinkedObject()
EntityAI SceneObject::GetLinkedObject (int i) inline protected
Definition at line 330 of file SceneObject.c.
  {
    return GetLinkedSceneObject(i).GetObject();
  }
References GetLinkedSceneObject(), and GetObject().
GetLinkedSceneObject()
SceneObject SceneObject::GetLinkedSceneObject (int i) inline protected
Definition at line 322 of file SceneObject.c.
  {
    return m_LinkedSceneObjects.Get(i);
  }
References m_LinkedSceneObjects.
Referenced by GetLinkedObject(), and UnlinkAll().
GetLinkedSceneObjects()
array< SceneObject > SceneObject::GetLinkedSceneObjects () inline protected
Definition at line 306 of file SceneObject.c.
  {
    return m_LinkedSceneObjects;
  }
References m_LinkedSceneObjects.
Referenced by PluginBase::EditorUpdate(), and PluginConfigHandler::SaveSceneObjects().
GetLinkedSceneObjectsCount()
int SceneObject::GetLinkedSceneObjectsCount () inline protected
Definition at line 314 of file SceneObject.c.
  {
    return m_LinkedSceneObjects.Count();
  }
References m_LinkedSceneObjects.
Referenced by UnlinkAll().
GetMaxHealth()
float SceneObject::GetMaxHealth () inline protected
Definition at line 419 of file SceneObject.c.
  {
    if (m_ObjectPtr)
      return m_ObjectPtr.GetMaxHealth("", "");
    return 0;
  }
References m_ObjectPtr.
GetName()
string SceneObject::GetName () inline protected
Definition at line 65 of file SceneObject.c.
  {
    return m_ObjectName;
  }
References m_ObjectName.
GetObject()
EntityAI SceneObject::GetObject () inline protected
Definition at line 57 of file SceneObject.c.
  {
    return m_ObjectPtr;
  }
References m_ObjectPtr.
Referenced by AddAttachment(), CanAttachment(), PluginBase::DeleteSceneObject(), EditorLineAdd(), EditorShapeUpdatePos(), GetAttachments(), GetLinkedObject(), PluginBase::GetSceneObjectByEntity(), GetSize(), and PluginConfigHandler::SaveSceneObjects().
GetPosition()
vector SceneObject::GetPosition () inline protected
Definition at line 399 of file SceneObject.c.
  {
    if (m_ObjectPtr)
      return m_ObjectPtr.GetPosition();
    return Vector(0, 0, 0);
  }
References m_ObjectPtr, and Vector().
Referenced by UIScriptedMenu::Refresh().
GetPositionAsString()
string SceneObject::GetPositionAsString () inline protected
Definition at line 446 of file SceneObject.c.
  {
    if (m_ObjectPtr)
      return m_ObjectPtr.GetPosition().ToString(false);
    return Vector(0, 0, 0).ToString(false);
  }
References m_ObjectPtr, and Vector().
Referenced by PluginConfigHandler::SaveSceneObjects().
GetRotation()
float SceneObject::GetRotation () inline protected
Definition at line 464 of file SceneObject.c.
  {
    if (m_ObjectPtr)
    {
      vector v = m_ObjectPtr.GetOrientation();
      return v[0];
    }
    return 0;
  }
References m_ObjectPtr.
Referenced by UIScriptedMenu::Refresh(), and PluginConfigHandler::SaveSceneObjects().
GetSize()
vector SceneObject::GetSize () inline protected
Definition at line 137 of file SceneObject.c.
  {
    vector size = Vector(1, 1, 1);
    vector min_max[2];
    if (GetObject())
    {
      GetObject().GetCollisionBox(min_max);
      size[0] = min_max[1][0] - min_max[0][0];
      size[2] = min_max[1][2] - min_max[0][2];
      size[1] = min_max[1][1] - min_max[0][1];
      return size;
    }
    else
      Print("Error: SceneObject " + m_ObjectNameOrigin + " dont has game object.");
    return size;
  }
References GetObject(), m_ObjectNameOrigin, Print(), and Vector().
Referenced by EditorLineAdd(), and EditorShapeAdd().
GetTypeName()
string SceneObject::GetTypeName () inline protected
Definition at line 355 of file SceneObject.c.
  {
    return m_ObjectPtr.GetType();
  }
References m_ObjectPtr.
Referenced by GetConfigAttachments(), UIScriptedMenu::Refresh(), PluginConfigHandler::SaveSceneObjects(), and PluginLocalProfile::SceneSave().
Init()
SceneObject SceneObject::Init (string obj_name, vector pos) inline protected
Definition at line 20 of file SceneObject.c.
  {
    if (obj_name != STRING_EMPTY)
    {
      m_ObjectNameOrigin = obj_name;
      bool is_ai = GetGame().IsKindOf(obj_name, "DZ_LightAI");
      PluginDeveloper module_dev = PluginDeveloper.Cast(GetPlugin(PluginDeveloper));
      EntityAI e = module_dev.SpawnEntityOnGroundPos(PluginSceneManager.PLAYER, obj_name, 100, 0.0, pos);
      if (e != NULL)
      {
        if (e.IsInherited(ItemBase))
        {
          ItemBase item = ItemBase.Cast(e);
          if (item.HasQuantity())
            item.SetQuantity(item.GetQuantityMax());
        }
        m_ObjectName = e.GetType();
        LinkEntityAI(e);
      }
      else if (obj_name != "player")
        return NULL;
    }
    m_LinkedSceneObjects = new array<SceneObject>;
    m_LinkedSceneObjectsShapes = new map<SceneObject, Shape>;
    m_LinkedSceneObjectsIndices = new array<int>;
    return this;
  }
References GetGame(), GetPlugin(), LinkEntityAI(), m_LinkedSceneObjects, m_LinkedSceneObjectsIndices, m_LinkedSceneObjectsShapes, m_ObjectName, m_ObjectNameOrigin, and STRING_EMPTY.
IsLinkedWithSceneObject()
bool SceneObject::IsLinkedWithSceneObject (SceneObject scene_object) inline protected
Definition at line 254 of file SceneObject.c.
  {
    int index = m_LinkedSceneObjects.Find(scene_object);
    if (index >= 0)
      return true;
    else
      return false;
  }
References m_LinkedSceneObjects.
Referenced by LinkSceneObject().
IsPlayer() [1/2]
bool SceneObject::IsPlayer () inline protected
Definition at line 73 of file SceneObject.c.
  {
    return false;
  }
IsPlayer() [2/2]
override bool SceneObject::IsPlayer () inline private
Definition at line 6 of file ScenePlayer.c.
  {
    return true;
  }
LinkEntityAI()
void SceneObject::LinkEntityAI (EntityAI e) inline protected
Definition at line 246 of file SceneObject.c.
  {
    m_ObjectPtr = e;
  }
References m_ObjectPtr.
Referenced by Init().
LinkSceneObject()
void SceneObject::LinkSceneObject (SceneObject scene_object, bool draw_line = true) inline protected
Definition at line 266 of file SceneObject.c.
  {
    if (!IsLinkedWithSceneObject(scene_object))
    {
      if (draw_line)
        EditorLineAdd(scene_object);
      m_LinkedSceneObjects.Insert(scene_object);
    }
  }
References EditorLineAdd(), IsLinkedWithSceneObject(), and m_LinkedSceneObjects.
PlaceOnSurface()
void SceneObject::PlaceOnSurface () inline protected
Definition at line 363 of file SceneObject.c.
  {
    if (m_ObjectPtr)
    {
      if (GetGame().IsClient() && GetGame().IsMultiplayer())
      {
        Param par = new Param3<string, EntityAI, Param>("PlaceOnSurface", m_ObjectPtr, NULL);
        SceneObjectSynch(par);
      }
      else
        m_ObjectPtr.PlaceOnSurface();
    }
  }
References GetGame(), m_ObjectPtr, and SceneObjectSynch().
Referenced by SetPosition().
RemoveAttachment()
void SceneObject::RemoveAttachment (EntityAI e) inline protected
Definition at line 536 of file SceneObject.c.
  {
    GetGame().ObjectDelete(e);
  }
References GetGame().
SceneObjectSynch()
void SceneObject::SceneObjectSynch (Param p) inline protected
Definition at line 489 of file SceneObject.c.
  {
    GetGame().RPCSingleParam(GetGame().GetPlayer(), ERPCs.RPC_SYNC_SCENE_OBJECT, p, true, NULL);
  }
References GetGame(), and GetPlayer().
Referenced by AddRotation(), PlaceOnSurface(), SetHealth(), and SetPosition().
SetHealth()
void SceneObject::SetHealth (float value) inline protected
Definition at line 429 of file SceneObject.c.
  {
    if (m_ObjectPtr)
    {
      if (GetGame().IsClient() && GetGame().IsMultiplayer())
      {
        Param par = new Param3<string, EntityAI, Param>("SetHealth", m_ObjectPtr, new Param1<float>(value));
        SceneObjectSynch(par);
      }
      else
        m_ObjectPtr.SetHealth("", "", value);
    }
  }
References GetGame(), m_ObjectPtr, and SceneObjectSynch().
SetInitScript()
void SceneObject::SetInitScript (string init_script) inline protected
Definition at line 89 of file SceneObject.c.
  {
    m_InitScript = init_script;
  }
References m_InitScript.
Referenced by UIPopupScript::OnClick().
SetPosition()
void SceneObject::SetPosition (vector pos) inline protected
Definition at line 380 of file SceneObject.c.
  {
    if (m_ObjectPtr)
    {
      if (GetGame().IsClient() && GetGame().IsMultiplayer())
      {
        Param par = new Param3<string, EntityAI, Param>("SetPosition", m_ObjectPtr, new Param1<vector>(pos));
        SceneObjectSynch(par);
      }
      else
        m_ObjectPtr.SetPosition(pos);
    }
    PlaceOnSurface();
    EditorShapeUpdatePos();
  }
References EditorShapeUpdatePos(), GetGame(), m_ObjectPtr, PlaceOnSurface(), and SceneObjectSynch().
Referenced by SetPositionAsString().
SetPositionAsString()
void SceneObject::SetPositionAsString (string string_pos) inline protected
Definition at line 456 of file SceneObject.c.
  {
    SetPosition(string_pos.ToVector());
  }
References SetPosition().
SetRotation()
void SceneObject::SetRotation (float rot) inline protected
Definition at line 478 of file SceneObject.c.
  {
    if (m_ObjectPtr)
    {
      vector v = m_ObjectPtr.GetOrientation();
      v[0] = rot;
      m_ObjectPtr.SetOrientation(v);
      EditorShapeUpdatePos();
    }
  }
References EditorShapeUpdatePos(), and m_ObjectPtr.
Referenced by PluginBase::SelectedObjectDuplicate().
UnlinkAll()
void SceneObject::UnlinkAll () inline protected
Definition at line 292 of file SceneObject.c.
  {
    int link_count = GetLinkedSceneObjectsCount();
    if (link_count > 0)
    {
      for (int i = 0; i < link_count; ++i)
        PluginSceneManager.GetInstance().UnlinkSceneObjects(this, GetLinkedSceneObject(0));
    }
  }
References GetLinkedSceneObject(), and GetLinkedSceneObjectsCount().
Referenced by PluginBase::DeleteSceneObject().
UnlinkSceneObject()
void SceneObject::UnlinkSceneObject (SceneObject scene_object) inline protected
Definition at line 279 of file SceneObject.c.
  {
    int index = m_LinkedSceneObjects.Find(scene_object);
    if (index >= 0 && index < m_LinkedSceneObjects.Count())
    {
      EditorLineRemove(scene_object);
      m_LinkedSceneObjects.Remove(index);
    }
  }
References EditorLineRemove(), and m_LinkedSceneObjects.
Member Data Documentation
COLOR_OBJ_BBOX_NORMAL
const int SceneObject::COLOR_OBJ_BBOX_NORMAL = 0x00000000 static private
Definition at line 3 of file SceneObject.c.
Referenced by EditorShapeDeselect().
COLOR_OBJ_BBOX_SELECT
const int SceneObject::COLOR_OBJ_BBOX_SELECT = 0x1f007C00 static private
Definition at line 4 of file SceneObject.c.
Referenced by EditorShapeSelect().
m_DebugShapeBBox
Shape SceneObject::m_DebugShapeBBox protected
Definition at line 7 of file SceneObject.c.
Referenced by EditorShapeAdd(), EditorShapeRemove(), EditorShapeSetColor(), and EditorShapeUpdatePos().
m_InitScript
string SceneObject::m_InitScript protected
Definition at line 8 of file SceneObject.c.
Referenced by GetInitScript(), and SetInitScript().
m_LinkedSceneObjects
ref array<SceneObject> SceneObject::m_LinkedSceneObjects protected
Definition at line 12 of file SceneObject.c.
Referenced by GetLinkedSceneObject(), GetLinkedSceneObjects(), GetLinkedSceneObjectsCount(), Init(), IsLinkedWithSceneObject(), LinkSceneObject(), UnlinkSceneObject(), and ~SceneObject().
m_LinkedSceneObjectsIndices
ref array<int> SceneObject::m_LinkedSceneObjectsIndices protected
Definition at line 15 of file SceneObject.c.
Referenced by Init().
m_LinkedSceneObjectsShapes
ref map<SceneObject, Shape> SceneObject::m_LinkedSceneObjectsShapes protected
Definition at line 13 of file SceneObject.c.
Referenced by EditorLineAdd(), EditorLineRemove(), and Init().
m_ObjectName
string SceneObject::m_ObjectName protected
Definition at line 9 of file SceneObject.c.
Referenced by GetName(), and Init().
m_ObjectNameOrigin
string SceneObject::m_ObjectNameOrigin protected
Definition at line 10 of file SceneObject.c.
Referenced by GetSize(), and Init().
m_ObjectPtr
EntityAI SceneObject::m_ObjectPtr protected
Definition at line 6 of file SceneObject.c.
Referenced by AddRotation(), GetHealth(), GetMaxHealth(), GetObject(), GetPosition(), GetPositionAsString(), GetRotation(), GetTypeName(), LinkEntityAI(), PlaceOnSurface(), SetHealth(), SetPosition(), SetRotation(), and ~SceneObject().
The documentation for this class was generated from the following files:
scripts/4_World/Classes/SceneEditor/SceneObject.c
scripts/4_World/Classes/SceneEditor/ScenePlayer.c