DayZ: FlashbangEffect Class Reference
FlashbangEffect Class Reference
Protected Member Functions
void FlashbangEffect (PlayerBase player, bool visual=true)
void ~FlashbangEffect ()
void SetupFlashbangValues (float progress_mult=1.0, float visual_value_max=1.0, float sound_value_max=1.0)
void PlaySound ()
void SetAttenuationFilter ()
void ResetAttenuationFilter ()
void StopSound ()
void ClearVisual ()
void SetVisual (float val)
void Stop ()
void Update (float deltatime)
Protected Attributes
const float ALPHA_MIN = 0.0
const float ALPHA_MAX = 1.0
const float SOUND_DEFER_TIME = 0.4
float m_HitDuration
SFX will be played ~0.5s AFTER VFX.
float m_BreakPoint
float m_TimeActive
float m_DayTimeToggle
float m_AlphaMaxActual
float m_SoundMaxActual
float m_ProgressMultiplier
bool m_Visual
bool m_Initialized
PlayerBase m_Player
EffectSound m_FlashbangEffectSound
float m_SoundStopTime
ref Timer m_DeferAttenuation
PPERequester_FlashbangEffects m_Requester
Detailed Description
Definition at line 1 of file FlashbangEffect.c.
Constructor & Destructor Documentation
FlashbangEffect()
void FlashbangEffect::FlashbangEffect (PlayerBase player, bool visual = true) inline protected
naive time of the day selector
-1: night; 1: day
Definition at line 28 of file FlashbangEffect.c.
  {
    m_Player = player;
    m_Visual = visual;
    m_Initialized = false;
    m_HitDuration = 8.0;
    m_BreakPoint = 2.5;
    m_AlphaMaxActual = ALPHA_MAX;
    m_SoundMaxActual = 1.0;
    m_ProgressMultiplier = 1.0;
    m_FlashbangEffectSound = null;
    if (m_Visual)
    {
      Class.CastTo(m_Requester, PPERequesterBank.GetRequester(PPERequester_FlashbangEffects));
      m_Requester.Start();
    }
    m_DeferAttenuation = new ref Timer();
    m_DeferAttenuation.Run(SOUND_DEFER_TIME, this, "PlaySound", null, false);
    m_DayTimeToggle = 5;
    if (g_Game.GetDayTime() >= 22.0 || g_Game.GetDayTime() < 7.0)
      m_DayTimeToggle = 10;
  }
References ALPHA_MAX, Class::CastTo(), g_Game, m_AlphaMaxActual, m_BreakPoint, m_DayTimeToggle, m_DeferAttenuation, m_FlashbangEffectSound, m_HitDuration, m_Initialized, m_Player, m_ProgressMultiplier, m_Requester, m_SoundMaxActual, m_Visual, and SOUND_DEFER_TIME.
~FlashbangEffect()
void FlashbangEffect::~FlashbangEffect () inline protected
Definition at line 57 of file FlashbangEffect.c.
  {
    if (m_Visual)
      ClearVisual();
    if (m_Player)
      m_Player.OnPlayerReceiveFlashbangHitEnd();
    if (m_DeferAttenuation.IsRunning())
      m_DeferAttenuation.Stop();
    m_DeferAttenuation = null;
    SEffectManager.DestroyEffect(m_FlashbangEffectSound);
  }
References ClearVisual(), SEffectManager::DestroyEffect(), m_DeferAttenuation, m_FlashbangEffectSound, m_Player, and m_Visual.
Member Function Documentation
ClearVisual()
void FlashbangEffect::ClearVisual () inline protected
Definition at line 137 of file FlashbangEffect.c.
  {
    if (m_Requester)
      m_Requester.Stop();
  }
References m_Requester.
Referenced by ~FlashbangEffect().
PlaySound()
void FlashbangEffect::PlaySound () inline protected
Definition at line 86 of file FlashbangEffect.c.
  {
    if (!m_Initialized)
    {
      Error("" + this + " not initialized");
      return;
    }
    vector pos;
    MiscGameplayFunctions.GetHeadBonePos(m_Player, pos);
    if (!m_FlashbangEffectSound)
      m_FlashbangEffectSound = SEffectManager.CreateSound("Tinnitus_SoundSet", pos);
    if (!m_FlashbangEffectSound.IsPlaying())
    {
      m_FlashbangEffectSound.SetParent(m_Player);
      m_FlashbangEffectSound.SetAttachedLocalPos(m_Player.WorldToModel(pos));
      m_FlashbangEffectSound.SetSoundWaveKind(WaveKind.WAVEEFFECTEX);
      m_FlashbangEffectSound.SetSoundFadeIn(4 * Math.Clamp(m_ProgressMultiplier, 0.5, 1.0)); //TODO
      m_SoundStopTime = 2 * Math.Clamp(m_ProgressMultiplier, 0.5, 1.0);
      m_FlashbangEffectSound.SetSoundFadeOut(m_SoundStopTime); //TODO
      m_FlashbangEffectSound.SetSoundMaxVolume(Math.Clamp(m_SoundMaxActual, 0.1, 1.0)); //TODO
      m_FlashbangEffectSound.SetSoundLoop(true);
      m_FlashbangEffectSound.SoundPlay();
      m_FlashbangEffectSound.SetAutodestroy(true);
      SetAttenuationFilter();
    }
  }
References Math::Clamp(), SEffectManager::CreateSound(), Error(), EffectSound::IsPlaying(), m_FlashbangEffectSound, m_Initialized, m_Player, m_ProgressMultiplier, m_SoundMaxActual, m_SoundStopTime, SetAttenuationFilter(), EffectSound::SetAutodestroy(), EffectSound::SetParent(), EffectSound::SetSoundFadeIn(), EffectSound::SetSoundFadeOut(), EffectSound::SetSoundLoop(), EffectSound::SetSoundMaxVolume(), EffectSound::SetSoundWaveKind(), and EffectSound::SoundPlay().
ResetAttenuationFilter()
void FlashbangEffect::ResetAttenuationFilter () inline protected
Definition at line 123 of file FlashbangEffect.c.
  {
    m_Player.SetMasterAttenuation("");
  }
References m_Player.
Referenced by Update().
SetAttenuationFilter()
void FlashbangEffect::SetAttenuationFilter () inline protected
Definition at line 117 of file FlashbangEffect.c.
  {
    if (!m_DeferAttenuation.IsRunning() || m_Player.GetMasterAttenuation() != "FlashbangAttenuation")
      m_Player.SetMasterAttenuation("FlashbangAttenuation");
  }
References m_DeferAttenuation, and m_Player.
Referenced by PlaySound().
SetupFlashbangValues()
void FlashbangEffect::SetupFlashbangValues (float progress_mult = 1.0, float visual_value_max = 1.0, float sound_value_max = 1.0) inline protected
Definition at line 72 of file FlashbangEffect.c.
  {
    if (!m_Initialized)
    {
      m_Initialized = true;
      m_ProgressMultiplier = progress_mult;
      m_AlphaMaxActual = visual_value_max;
      m_SoundMaxActual = sound_value_max;
      m_HitDuration *= m_ProgressMultiplier;
      m_BreakPoint *= m_ProgressMultiplier;
    }
  }
References m_AlphaMaxActual, m_BreakPoint, m_HitDuration, m_Initialized, m_ProgressMultiplier, and m_SoundMaxActual.
SetVisual()
void FlashbangEffect::SetVisual (float val) inline protected
Definition at line 143 of file FlashbangEffect.c.
  {
    if (m_Requester && m_Requester.IsRequesterRunning())
      m_Requester.SetFlashbangIntensity(val, m_DayTimeToggle);
  }
References m_DayTimeToggle, and m_Requester.
Referenced by Update().
Stop()
void FlashbangEffect::Stop () inline protected
Definition at line 149 of file FlashbangEffect.c.
  {
    StopSound();
  }
References StopSound().
StopSound()
void FlashbangEffect::StopSound () inline protected
Definition at line 128 of file FlashbangEffect.c.
  {
    if (m_FlashbangEffectSound)
    {
      m_FlashbangEffectSound.SoundStop();
      SEffectManager.DestroyEffect(m_FlashbangEffectSound);
    }
  }
References SEffectManager::DestroyEffect(), m_FlashbangEffectSound, and EffectSound::SoundStop().
Referenced by Stop(), and Update().
Update()
void FlashbangEffect::Update (float deltatime) inline protected
Definition at line 154 of file FlashbangEffect.c.
  {
    if (!m_Initialized)
      Error("" + this + " not initialized");
    else if (m_Visual)
    {
      float value;
      if (m_TimeActive <= m_BreakPoint)
      {
        value = m_AlphaMaxActual;
        //Print("Flashbango | m_AlphaMaxActual: " + value);
      }
      else
      {
        value = Math.InverseLerp(m_HitDuration - m_BreakPoint, m_HitDuration, m_TimeActive);
        value = Math.Clamp(value, 0.0, 1.0);
        value = m_AlphaMaxActual - value * m_AlphaMaxActual;
        //Print("Flashbango | tmp_value: " + value);
      }
      SetVisual(value);
    }
    m_TimeActive += deltatime;
    if (m_TimeActive >= m_HitDuration - m_SoundStopTime)
      StopSound();
    if (m_TimeActive >= m_HitDuration)
    {
      ResetAttenuationFilter();
      delete this;
    }
  }
References Math::Clamp(), Error(), Math::InverseLerp(), m_AlphaMaxActual, m_BreakPoint, m_HitDuration, m_Initialized, m_SoundStopTime, m_TimeActive, m_Visual, ResetAttenuationFilter(), SetVisual(), and StopSound().
Member Data Documentation
ALPHA_MAX
const float FlashbangEffect::ALPHA_MAX = 1.0 protected
Definition at line 4 of file FlashbangEffect.c.
Referenced by FlashbangEffect().
ALPHA_MIN
const float FlashbangEffect::ALPHA_MIN = 0.0 protected
Definition at line 3 of file FlashbangEffect.c.
m_AlphaMaxActual
float FlashbangEffect::m_AlphaMaxActual protected
Definition at line 13 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), SetupFlashbangValues(), and Update().
m_BreakPoint
float FlashbangEffect::m_BreakPoint protected
Definition at line 9 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), SetupFlashbangValues(), and Update().
m_DayTimeToggle
float FlashbangEffect::m_DayTimeToggle protected
Definition at line 11 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), and SetVisual().
m_DeferAttenuation
ref Timer FlashbangEffect::m_DeferAttenuation protected
Definition at line 24 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), SetAttenuationFilter(), and ~FlashbangEffect().
m_FlashbangEffectSound
EffectSound FlashbangEffect::m_FlashbangEffectSound protected
Definition at line 21 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), PlaySound(), StopSound(), and ~FlashbangEffect().
m_HitDuration
float FlashbangEffect::m_HitDuration protected
SFX will be played ~0.5s AFTER VFX.
Definition at line 8 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), SetupFlashbangValues(), and Update().
m_Initialized
bool FlashbangEffect::m_Initialized protected
Definition at line 18 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), PlaySound(), SetupFlashbangValues(), and Update().
m_Player
PlayerBase FlashbangEffect::m_Player protected
Definition at line 20 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), PlaySound(), ResetAttenuationFilter(), SetAttenuationFilter(), and ~FlashbangEffect().
m_ProgressMultiplier
float FlashbangEffect::m_ProgressMultiplier protected
Definition at line 15 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), PlaySound(), and SetupFlashbangValues().
m_Requester
PPERequester_FlashbangEffects FlashbangEffect::m_Requester protected
Definition at line 26 of file FlashbangEffect.c.
Referenced by ClearVisual(), FlashbangEffect(), and SetVisual().
m_SoundMaxActual
float FlashbangEffect::m_SoundMaxActual protected
Definition at line 14 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), PlaySound(), and SetupFlashbangValues().
m_SoundStopTime
float FlashbangEffect::m_SoundStopTime protected
Definition at line 22 of file FlashbangEffect.c.
Referenced by PlaySound(), and Update().
m_TimeActive
float FlashbangEffect::m_TimeActive protected
Definition at line 10 of file FlashbangEffect.c.
Referenced by Update().
m_Visual
bool FlashbangEffect::m_Visual protected
Definition at line 17 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), Update(), and ~FlashbangEffect().
SOUND_DEFER_TIME
const float FlashbangEffect::SOUND_DEFER_TIME = 0.4 protected
Definition at line 6 of file FlashbangEffect.c.
Referenced by FlashbangEffect().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/Explosions/FlashbangEffect.c