DayZ: BloodContainerBase Class Reference
BloodContainerBase Class Reference
Private Member Functions
override void SetActions ()
void BloodBagFull ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
Detailed Description
Definition at line 1 of file BloodBagEmpty.c.
Member Function Documentation
BloodBagFull()
void BloodContainerBase::BloodBagFull () inline private
Definition at line 3 of file BloodBagFull.c.
  {
  }
SetActions() [1/4]
override void BloodContainerBase::SetActions () inline private
Definition at line 3 of file BloodBagEmpty.c.
  {
    super.SetActions();
    AddAction(ActionCollectBloodTarget);
    AddAction(ActionCollectBloodSelf);
  }
References AddAction().
SetActions() [2/4]
override void BloodContainerBase::SetActions () inline private
Definition at line 3 of file BloodBagIV.c.
  {
    super.SetActions();
    AddAction(ActionGiveBloodTarget);
    AddAction(ActionGiveBloodSelf);
  }
References AddAction().
SetActions() [3/4]
override void BloodContainerBase::SetActions () inline private
Definition at line 3 of file BloodSyringe.c.
  {
    super.SetActions();
    AddAction(ActionGiveBloodTarget);
    AddAction(ActionGiveBloodSelf);
  }
References AddAction().
SetActions() [4/4]
override void BloodContainerBase::SetActions () inline private
Definition at line 3 of file Syringe.c.
  {
    super.SetActions();
    AddAction(ActionCollectSampleTarget);
    AddAction(ActionCollectSampleSelf);
  }
References AddAction().
The documentation for this class was generated from the following files:
scripts/4_World/Entities/ItemBase/BloodContainerBase/BloodBagEmpty.c
scripts/4_World/Entities/ItemBase/BloodContainerBase/BloodBagFull.c
scripts/4_World/Entities/ItemBase/BloodContainerBase/BloodBagIV.c
scripts/4_World/Entities/ItemBase/BloodContainerBase/BloodSyringe.c
scripts/4_World/Entities/ItemBase/BloodContainerBase/Syringe.c