DayZ: scripts/1_Core/proto/EnConvert.c File Reference
EnConvert.c File Reference
Classes
class bool
class func
class float
class vector
class typename
class EnumTools
Enumerations
enum EBool { NO = 0 , YES = 1 }
Functions
proto string ToString ()
proto string AsciiToString ()
Converts ASCII code to string.
string ToStringLen (int len)
Integer to string with fixed length, padded with zeroes.
bool InRange (int min, int max, bool inclusive_min=true, bool inclusive_max=true)
Check whether integer falls into an inclusive range.
Variables
enum EBool ZERO_PAD_SIZE = 8
static string m_ZeroPad [ZERO_PAD_SIZE] = {"", "0", "00", "000", "0000", "00000", "000000", "0000000"}
const int MAX = 2147483647
const int MIN = -2147483648
Enumeration Type Documentation
EBool
enum EBool
Enumerator
NO
YES
Definition at line 16 of file EnConvert.c.
{
  NO = 0,
  YES = 1
}
Function Documentation
AsciiToString()
proto string AsciiToString () protected
Converts ASCII code to string.
Parameters
ascii ASCII code for convert to string.
Returns
string - Converted int.
int ascii_code = 77;
string str = ascii_code.AsciiToString();
Print(str);
>> str = 'M'
InRange()
bool InRange (int min, int max, bool inclusive_min = true, bool inclusive_max = true) protected
Check whether integer falls into an inclusive range.
Parameters
min int low end of range
max int high end of range
Returns
bool True if this value is withing the set range
int num = 123;
bool test = num.InRange(100, 150);
Print(test);
>> s = true
Definition at line 84 of file EnConvert.c.
  {
    if ((!inclusive_min && value <= min) || value < min)
      return false;
    if ((!inclusive_max && value >= max) || value > max)
      return false;
    return true;
  }
ToString()
proto string ToString () protected
Referenced by HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Abort(), RecipeBase::ApplyModificationsResults(), EmoteConstructor::ConstructEmotes(), AnimatedActionBase::Do(), AnimatedActionBase::End(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindAbortDestinationState(), ForceSwapEntities(), ScriptedWidgetEventHandler::GenerateQuickBarBackgroundTiles(), UnconsciousnessMdfr::GetDebugText(), CharcoalMdfr::GetDebugTextSimple(), KeysToUIElements::GetKeyToUIElement(), LogTemplates::GetTemplate(), HandleForceSwapEntities(), HandleHandEvent(), HandleSwapEntities(), HandleTakeToDst(), ActionInput::Init(), ActionBaseCB::Interrupt(), MissionBase::InvokeOnConnect(), MissionBase::InvokeOnDisconnect(), Component::LogErrorBadCompType(), BotStateBase::OnAbort(), HandStateBase::OnAbort(), Entity::OnAction(), OnActionEnd(), ScriptConsoleGeneralTab::OnClick(), ManBase::OnConnect(), ManBase::OnDisconnect(), BotStateBase::OnEntry(), HandStateBase::OnEntry(), OnErrorThrown(), BotStateBase::OnExit(), ActionBaseCB::OnFinish(), SymptomBase::OnGetActivatedClient(), SymptomBase::OnGetActivatedServer(), SymptomBase::OnGetDeactivatedClient(), SymptomBase::OnGetDeactivatedServer(), ScriptConsoleGeneralTab::OnItemSelected(), UIPopupScript::OnOpen(), Icon::OnPerformRecipe(), ManBase::OnReconnect(), UIPopupScript::OnUpdate(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortEvent(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessAbortEvent(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessEvent(), KeysToUIElements::RegisterKeyToUIElement(), LogTemplates::RegisterLogTamplate(), ScriptedWidgetEventHandler::Remove(), SVNBlamePlugin::Run(), ManBase::Save(), ActionInput::SetInput(), ScriptedWidgetEventHandler::SetInterpTime(), SlotsIcon::SetItemSize(), DebugMonitor::SetPosition(), SetTextSmart(), ScriptedWidgetEventHandler::SetTimeBefore(), ScriptedWidgetEventHandler::Show(), RecipeBase::SpawnItems(), OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), StoreInputForRemotes(), SwapEntities(), TakeToDst(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Terminate(), ComponentEnergyManager::UnplugCordFromSocket(), ScriptConsoleGeneralTab::Update(), ServerBrowserTab::UpdatePageButtons(), ComponentEnergyManager::UpdateSelections(), ComponentEnergyManager::UpdateSocketSelections(), ValidateDestroy(), ValidateSwap(), and ValidateSyncMove().
ToStringLen()
string ToStringLen (int len) protected
Integer to string with fixed length, padded with zeroes.
Parameters
num int integer to convert
len int fixed length
Returns
vector Converted s as vector
int num = 123;
string s = num.ToStringLen(5);
Print(s);
>> s = '00123'
Definition at line 59 of file EnConvert.c.
  {
    string str = value.ToString();
    int l = len - str.Length();
    if (l > 0 && l < ZERO_PAD_SIZE)
      return m_ZeroPad[l] + str;
    return str;
  }
References string::Length(), m_ZeroPad, string::ToString(), and ZERO_PAD_SIZE.
Referenced by ItemBase::GetSlotPosition(), ItemBase::RemoveSlot(), ItemBase::SetSlotTextureDigged(), ItemBase::SetSlotTextureFertilized(), ItemBase::UpdatePlant(), and ItemBase::UpdateSlotTexture().
Variable Documentation
m_ZeroPad
string m_ZeroPad[ZERO_PAD_SIZE] = {"", "0", "00", "000", "0000", "00000", "000000", "0000000"} static protected
Definition at line 25 of file EnConvert.c.
{"", "0", "00", "000", "0000", "00000", "000000", "0000000"};
Referenced by ToStringLen().
MAX
const int MAX = 2147483647 protected
Definition at line 27 of file EnConvert.c.
Referenced by RemotelyActivatedItemBehaviour::GeneratePersistentID(), GetMeleeTargetEx(), Grenade_Base::OnExplosionEffects(), InventoryItem::OnStoreLoad(), and SnapOnObject().
MIN
const int MIN = -2147483648 protected
Definition at line 28 of file EnConvert.c.
Referenced by CGame::GlobalsInit(), RemotelyActivatedItemBehaviour::OnAfterLoad(), RemotelyActivatedItemBehaviour::OnStoreLoad(), and RemotelyActivatedItemBehaviour::Unpair().
ZERO_PAD_SIZE
enum EBool ZERO_PAD_SIZE = 8
Referenced by ToStringLen().