DayZ: ToolBase Class Reference
ToolBase Class Reference
Private Member Functions
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void Cleaver ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void CombatKnife ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void Machete ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void FirefighterAxe ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override bool CanPutAsAttachment (EntityAI parent)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override bool CanPutAsAttachment (EntityAI parent)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void Machete ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void Machete ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void Pliers ()
override void SetActions ()
void Screwdriver ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void Sickle ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void Sword ()
override bool IsMeleeFinisher ()
override void SetActions ()
override void SetActions ()
Detailed Description
Definition at line 1 of file BoneKnife.c.
Member Function Documentation
CanPutAsAttachment() [1/2]
override bool ToolBase::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 13 of file AK_Bayonet.c.
  {
    if (!super.CanPutAsAttachment(parent)) return false;
    if (parent.FindAttachmentBySlotName("suppressorImpro") == null && parent.FindAttachmentBySlotName("weaponMuzzleAK") == null)
      return true;
    return false;
  }
CanPutAsAttachment() [2/2]
override bool ToolBase::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 13 of file M9A1_Bayonet.c.
  {
    if (!super.CanPutAsAttachment(parent)) return false;
    if (parent.FindAttachmentBySlotName("suppressorImpro") == null && parent.FindAttachmentBySlotName("weaponMuzzleM4") == null)
      return true;
    return false;
  }
Cleaver()
void ToolBase::Cleaver () inline private
Definition at line 3 of file Cleaver.c.
  {
  }
CombatKnife()
void ToolBase::CombatKnife () inline private
Definition at line 3 of file CombatKnife.c.
  {
  }
FirefighterAxe()
void ToolBase::FirefighterAxe () inline private
Definition at line 3 of file FirefighterAxe.c.
  {
  }
GetValidFinishers() [1/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 8 of file BoneKnife.c.
  {
    return {EMeleeHitType.FINISHER_LIVERSTAB, EMeleeHitType.FINISHER_NECKSTAB};
  }
GetValidFinishers() [2/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 12 of file Cleaver.c.
  {
    return {EMeleeHitType.FINISHER_NECKSTAB};
  }
GetValidFinishers() [3/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 12 of file CombatKnife.c.
  {
    return {EMeleeHitType.FINISHER_LIVERSTAB, EMeleeHitType.FINISHER_NECKSTAB};
  }
GetValidFinishers() [4/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 12 of file CrudeMachete.c.
  {
    return {EMeleeHitType.FINISHER_LIVERSTAB, EMeleeHitType.FINISHER_NECKSTAB};
  }
GetValidFinishers() [5/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 8 of file FangeKnife.c.
  {
    return {EMeleeHitType.FINISHER_LIVERSTAB, EMeleeHitType.FINISHER_NECKSTAB};
  }
GetValidFinishers() [6/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 8 of file HuntingKnife.c.
  {
    return {EMeleeHitType.FINISHER_LIVERSTAB, EMeleeHitType.FINISHER_NECKSTAB};
  }
GetValidFinishers() [7/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 8 of file AK_Bayonet.c.
  {
    return {EMeleeHitType.FINISHER_LIVERSTAB, EMeleeHitType.FINISHER_NECKSTAB};
  }
GetValidFinishers() [8/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 8 of file M9A1_Bayonet.c.
  {
    return {EMeleeHitType.FINISHER_LIVERSTAB, EMeleeHitType.FINISHER_NECKSTAB};
  }
GetValidFinishers() [9/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 8 of file KitchenKnife.c.
  {
    return {EMeleeHitType.FINISHER_LIVERSTAB, EMeleeHitType.FINISHER_NECKSTAB};
  }
GetValidFinishers() [10/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 8 of file KukriKnife.c.
  {
    return {EMeleeHitType.FINISHER_LIVERSTAB, EMeleeHitType.FINISHER_NECKSTAB};
  }
GetValidFinishers() [11/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 12 of file Machete.c.
  {
    return {EMeleeHitType.FINISHER_LIVERSTAB, EMeleeHitType.FINISHER_NECKSTAB};
  }
GetValidFinishers() [12/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 12 of file OrientalMachete.c.
  {
    return {EMeleeHitType.FINISHER_LIVERSTAB, EMeleeHitType.FINISHER_NECKSTAB};
  }
GetValidFinishers() [13/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 13 of file Screwdriver.c.
  {
    return {EMeleeHitType.FINISHER_LIVERSTAB, EMeleeHitType.FINISHER_NECKSTAB};
  }
GetValidFinishers() [14/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 12 of file Sickle.c.
  {
    return {EMeleeHitType.FINISHER_LIVERSTAB, EMeleeHitType.FINISHER_NECKSTAB};
  }
GetValidFinishers() [15/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 8 of file SteakKnife.c.
  {
    return {EMeleeHitType.FINISHER_LIVERSTAB, EMeleeHitType.FINISHER_NECKSTAB};
  }
GetValidFinishers() [16/16]
override array< int > ToolBase::GetValidFinishers () inline private
Definition at line 8 of file StoneKnife.c.
  {
    return {EMeleeHitType.FINISHER_LIVERSTAB, EMeleeHitType.FINISHER_NECKSTAB};
  }
IsMeleeFinisher() [1/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 3 of file BoneKnife.c.
  {
    return true;
  }
IsMeleeFinisher() [2/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 7 of file Cleaver.c.
  {
    return true;
  }
IsMeleeFinisher() [3/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 7 of file CombatKnife.c.
  {
    return true;
  }
IsMeleeFinisher() [4/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 7 of file CrudeMachete.c.
  {
    return true;
  }
IsMeleeFinisher() [5/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 3 of file FangeKnife.c.
  {
    return true;
  }
IsMeleeFinisher() [6/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 3 of file HuntingKnife.c.
  {
    return true;
  }
IsMeleeFinisher() [7/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 3 of file AK_Bayonet.c.
  {
    return true;
  }
IsMeleeFinisher() [8/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 3 of file M9A1_Bayonet.c.
  {
    return true;
  }
IsMeleeFinisher() [9/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 3 of file KitchenKnife.c.
  {
    return true;
  }
IsMeleeFinisher() [10/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 3 of file KukriKnife.c.
  {
    return true;
  }
IsMeleeFinisher() [11/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 7 of file Machete.c.
  {
    return true;
  }
IsMeleeFinisher() [12/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 7 of file OrientalMachete.c.
  {
    return true;
  }
IsMeleeFinisher() [13/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 8 of file Screwdriver.c.
  {
    return true;
  }
IsMeleeFinisher() [14/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 7 of file Sickle.c.
  {
    return true;
  }
IsMeleeFinisher() [15/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 3 of file SteakKnife.c.
  {
    return true;
  }
IsMeleeFinisher() [16/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 3 of file StoneKnife.c.
  {
    return true;
  }
IsMeleeFinisher() [17/17]
override bool ToolBase::IsMeleeFinisher () inline private
Definition at line 7 of file Sword.c.
  {
    return false;
  }
Machete() [1/3]
void ToolBase::Machete () inline private
Definition at line 3 of file CrudeMachete.c.
  {
  }
Machete() [2/3]
void ToolBase::Machete () inline private
Definition at line 3 of file Machete.c.
  {
  }
Machete() [3/3]
void ToolBase::Machete () inline private
Definition at line 3 of file OrientalMachete.c.
  {
  }
OnWasAttached() [1/2]
override void ToolBase::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 21 of file AK_Bayonet.c.
  {
    super.OnWasAttached(parent, slot_id);
    if (parent.IsWeapon())
      parent.SetBayonetAttached(true, slot_id);
  }
OnWasAttached() [2/2]
override void ToolBase::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 21 of file M9A1_Bayonet.c.
  {
    super.OnWasAttached(parent, slot_id);
    if (parent.IsWeapon())
      parent.SetBayonetAttached(true, slot_id);
  }
OnWasDetached() [1/2]
override void ToolBase::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 29 of file AK_Bayonet.c.
  {
    super.OnWasDetached(parent, slot_id);
    if (parent.IsWeapon())
      parent.SetBayonetAttached(false);
  }
OnWasDetached() [2/2]
override void ToolBase::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 29 of file M9A1_Bayonet.c.
  {
    super.OnWasDetached(parent, slot_id);
    if (parent.IsWeapon())
      parent.SetBayonetAttached(false);
  }
Pliers()
void ToolBase::Pliers () inline private
Definition at line 3 of file Pliers.c.
  {
    m_MineDisarmRate = 100;
  }
Screwdriver()
void ToolBase::Screwdriver () inline private
Definition at line 3 of file Screwdriver.c.
  {
    m_MineDisarmRate = 80;
  }
SetActions() [1/22]
override void ToolBase::SetActions () inline private
Definition at line 13 of file BoneKnife.c.
  {
    super.SetActions();
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionSkinning);
    AddAction(ActionMineBush);
    AddAction(ActionMineTreeBark);
    AddAction(ActionDigWorms);
    AddAction(ActionCraftBolts);
  }
References ActionSkinning(), and AddAction().
SetActions() [2/22]
override void ToolBase::SetActions () inline private
Definition at line 17 of file Cleaver.c.
  {
    super.SetActions();
    AddAction(ActionBurnSewTarget);
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionSkinning);
    AddAction(ActionMineBush);
    AddAction(ActionMineTreeBark);
    AddAction(ActionBurnSewSelf);
    AddAction(ActionDigWorms);
    AddAction(ActionShaveTarget);
    AddAction(ActionShave);
    AddAction(ActionCraftBolts);
  }
References ActionSkinning(), and AddAction().
SetActions() [3/22]
override void ToolBase::SetActions () inline private
Definition at line 17 of file CombatKnife.c.
  {
    super.SetActions();
    AddAction(ActionBurnSewTarget);
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionSkinning);
    AddAction(ActionMineBush);
    AddAction(ActionMineTreeBark);
    AddAction(ActionBurnSewSelf);
    AddAction(ActionDigWorms);
    AddAction(ActionShaveTarget);
    AddAction(ActionDisarmMine);
    AddAction(ActionDisarmExplosive);
    AddAction(ActionShave);
    AddAction(ActionCraftBolts);
  }
References ActionDisarmExplosive(), ActionDisarmMine(), ActionSkinning(), and AddAction().
SetActions() [4/22]
override void ToolBase::SetActions () inline private
Definition at line 17 of file CrudeMachete.c.
  {
    super.SetActions();
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionBurnSewTarget);
    AddAction(ActionSkinning);
    AddAction(ActionMineBush);
    AddAction(ActionMineTreeBark);
    AddAction(ActionBurnSewSelf);
    AddAction(ActionDigWorms);
    AddAction(ActionCraftBolts);
  }
References ActionSkinning(), and AddAction().
SetActions() [5/22]
override void ToolBase::SetActions () inline private
Definition at line 13 of file FangeKnife.c.
  {
    super.SetActions();
    AddAction(ActionBurnSewTarget);
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionSkinning);
    AddAction(ActionMineBush);
    AddAction(ActionMineTreeBark);
    AddAction(ActionBurnSewSelf);
    AddAction(ActionDigWorms);
    AddAction(ActionShaveTarget);
    AddAction(ActionShave);
    AddAction(ActionCraftBolts);
  }
References ActionSkinning(), and AddAction().
SetActions() [6/22]
override void ToolBase::SetActions () inline private
Definition at line 7 of file FirefighterAxe.c.
  {
    super.SetActions();
    AddAction(ActionMineTree);
    AddAction(ActionMineTreeBark);
    AddAction(ActionMineBush);
    //AddAction(ActionRepairPart);
    AddAction(ActionDismantlePart);
    //AddAction(ActionBuildPart);
    //AddAction(ActionDestroyPart);
    //AddAction(ActionSawPlanks);
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionSkinning);
    AddAction(ActionCraftBolts);
  }
References ActionSkinning(), and AddAction().
SetActions() [7/22]
override void ToolBase::SetActions () inline private
Definition at line 3 of file Hacksaw.c.
  {
    super.SetActions();
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionMineBush);
    AddAction(ActionSawPlanks);
    AddAction(ActionDismantlePart);
    //AddAction(ActionDestroyCombinationLock);
    //AddAction(ActionDestroyPart);
    AddAction(ActionSkinning);
    AddAction(ActionMineTreeBark);
  }
References ActionSkinning(), and AddAction().
SetActions() [8/22]
override void ToolBase::SetActions () inline private
Definition at line 3 of file Hatchet.c.
  {
    super.SetActions();
    AddAction(ActionMineTree);
    AddAction(ActionMineTreeBark);
    AddAction(ActionMineBush);
    AddAction(ActionRepairPart);
    AddAction(ActionDismantlePart);
    AddAction(ActionBuildPart);
    //AddAction(ActionDestroyPart);
    //AddAction(ActionSawPlanks);
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionSkinning);
    AddAction(ActionCraftBolts);
  }
References ActionSkinning(), and AddAction().
SetActions() [9/22]
override void ToolBase::SetActions () inline private
Definition at line 13 of file HuntingKnife.c.
  {
    super.SetActions();
    AddAction(ActionBurnSewTarget);
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionSkinning);
    AddAction(ActionMineBush);
    AddAction(ActionMineTreeBark);
    AddAction(ActionBurnSewSelf);
    AddAction(ActionDigWorms);
    AddAction(ActionShaveTarget);
    AddAction(ActionDisarmMine);
    AddAction(ActionDisarmExplosive);
    AddAction(ActionShave);
    AddAction(ActionCraftBolts);
  }
References ActionDisarmExplosive(), ActionDisarmMine(), ActionSkinning(), and AddAction().
SetActions() [10/22]
override void ToolBase::SetActions () inline private
Definition at line 37 of file AK_Bayonet.c.
  {
    super.SetActions();
    AddAction(ActionBurnSewTarget);
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionSkinning);
    AddAction(ActionMineBush);
    AddAction(ActionMineTreeBark);
    AddAction(ActionBurnSewSelf);
    AddAction(ActionDigWorms);
    AddAction(ActionShaveTarget);
    AddAction(ActionDisarmMine);
    AddAction(ActionDisarmExplosive);
    AddAction(ActionShave);
    AddAction(ActionCraftBolts);
  }
References ActionDisarmExplosive(), ActionDisarmMine(), ActionSkinning(), and AddAction().
SetActions() [11/22]
override void ToolBase::SetActions () inline private
Definition at line 37 of file M9A1_Bayonet.c.
  {
    super.SetActions();
    AddAction(ActionBurnSewTarget);
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionSkinning);
    AddAction(ActionMineBush);
    AddAction(ActionMineTreeBark);
    AddAction(ActionBurnSewSelf);
    AddAction(ActionDigWorms);
    AddAction(ActionShaveTarget);
    AddAction(ActionDisarmMine);
    AddAction(ActionDisarmExplosive);
    AddAction(ActionShave);
    AddAction(ActionCraftBolts);
  }
References ActionDisarmExplosive(), ActionDisarmMine(), ActionSkinning(), and AddAction().
SetActions() [12/22]
override void ToolBase::SetActions () inline private
Definition at line 13 of file KitchenKnife.c.
  {
    super.SetActions();
    AddAction(ActionBurnSewTarget);
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionSkinning);
    AddAction(ActionMineBush);
    AddAction(ActionMineTreeBark);
    AddAction(ActionBurnSewSelf);
    AddAction(ActionDigWorms);
    AddAction(ActionShaveTarget);
    AddAction(ActionDisarmMine);
    AddAction(ActionDisarmExplosive);
    AddAction(ActionShave);
    AddAction(ActionCraftBolts);
  }
References ActionDisarmExplosive(), ActionDisarmMine(), ActionSkinning(), and AddAction().
SetActions() [13/22]
override void ToolBase::SetActions () inline private
Definition at line 13 of file KukriKnife.c.
  {
    super.SetActions();
    AddAction(ActionBurnSewTarget);
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionSkinning);
    AddAction(ActionMineBush);
    AddAction(ActionMineTreeBark);
    AddAction(ActionBurnSewSelf);
    AddAction(ActionDigWorms);
    AddAction(ActionShaveTarget);
    AddAction(ActionShave);
    AddAction(ActionCraftBolts);
  }
References ActionSkinning(), and AddAction().
SetActions() [14/22]
override void ToolBase::SetActions () inline private
Definition at line 17 of file Machete.c.
  {
    super.SetActions();
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionBurnSewTarget);
    AddAction(ActionSkinning);
    AddAction(ActionMineBush);
    AddAction(ActionMineTreeBark);
    AddAction(ActionBurnSewSelf);
    AddAction(ActionDigWorms);
    AddAction(ActionCraftBolts);
  }
References ActionSkinning(), and AddAction().
SetActions() [15/22]
override void ToolBase::SetActions () inline private
Definition at line 17 of file OrientalMachete.c.
  {
    super.SetActions();
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionBurnSewTarget);
    AddAction(ActionSkinning);
    AddAction(ActionMineBush);
    AddAction(ActionMineTreeBark);
    AddAction(ActionBurnSewSelf);
    AddAction(ActionDigWorms);
    AddAction(ActionCraftBolts);
  }
References ActionSkinning(), and AddAction().
SetActions() [16/22]
override void ToolBase::SetActions () inline private
Definition at line 8 of file Pliers.c.
  {
    super.SetActions();
    AddAction(ActionDismantlePart);
    AddAction(ActionBuildPart);
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionMountBarbedWire);
    AddAction(ActionUnmountBarbedWire);
    AddAction(ActionLockAttachment);
    AddAction(ActionDisarmExplosive);
  }
References ActionDisarmExplosive(), and AddAction().
SetActions() [17/22]
override void ToolBase::SetActions () inline private
Definition at line 18 of file Screwdriver.c.
  {
    super.SetActions();
    AddAction(ActionBurnSewTarget);
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionBurnSewSelf);
    AddAction(ActionMineTreeBark);
    AddAction(ActionSkinning);
    AddAction(ActionLockAttachment);
    AddAction(ActionDisarmMine);
    AddAction(ActionDisarmExplosive);
    AddAction(ActionMineRock1H);
  }
References ActionDisarmExplosive(), ActionDisarmMine(), ActionSkinning(), and AddAction().
SetActions() [18/22]
override void ToolBase::SetActions () inline private
Definition at line 17 of file Sickle.c.
  {
    super.SetActions();
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionMineBush);
    AddAction(ActionSkinning);
    AddAction(ActionMineTreeBark);
    AddAction(ActionDigWorms);
    AddAction(ActionShaveTarget);
    AddAction(ActionShave);
    AddAction(ActionCraftBolts);
  }
References ActionSkinning(), and AddAction().
SetActions() [19/22]
override void ToolBase::SetActions () inline private
Definition at line 13 of file SteakKnife.c.
  {
    super.SetActions();
    AddAction(ActionBurnSewTarget);
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionSkinning);
    AddAction(ActionMineBush);
    AddAction(ActionMineTreeBark);
    AddAction(ActionBurnSewSelf);
    AddAction(ActionDigWorms);
    AddAction(ActionShaveTarget);
    AddAction(ActionDisarmMine);
    AddAction(ActionDisarmExplosive);
    AddAction(ActionShave);
    AddAction(ActionCraftBolts);
  }
References ActionDisarmExplosive(), ActionDisarmMine(), ActionSkinning(), and AddAction().
SetActions() [20/22]
override void ToolBase::SetActions () inline private
Definition at line 13 of file StoneKnife.c.
  {
    super.SetActions();
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionSkinning);
    AddAction(ActionMineBush);
    AddAction(ActionMineTreeBark);
    AddAction(ActionDigWorms);
    AddAction(ActionCraftBolts);
  }
References ActionSkinning(), and AddAction().
SetActions() [21/22]
override void ToolBase::SetActions () inline private
Definition at line 12 of file Sword.c.
  {
    super.SetActions();
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionSkinning);
    AddAction(ActionMineBush);
    AddAction(ActionMineTreeBark);
  }
References ActionSkinning(), and AddAction().
SetActions() [22/22]
override void ToolBase::SetActions () inline private
Definition at line 3 of file WoodAxe.c.
  {
    super.SetActions();
    //AddAction(ActionBuildPartSwitch);
    AddAction(ActionMineTree);
    AddAction(ActionMineTreeBark);
    AddAction(ActionMineBush);
    //AddAction(ActionRepairPart);
    AddAction(ActionDismantlePart);
    //AddAction(ActionBuildPart);
    AddAction(ActionUnrestrainTarget);
    AddAction(ActionSkinning);
    AddAction(ActionCraftBolts);
  }
References ActionSkinning(), and AddAction().
Sickle()
void ToolBase::Sickle () inline private
Definition at line 3 of file Sickle.c.
  {
  }
Sword()
void ToolBase::Sword () inline private
Definition at line 3 of file Sword.c.
  {
  }
The documentation for this class was generated from the following files:
scripts/4_World/Entities/ItemBase/BoneKnife.c
scripts/4_World/Entities/ItemBase/Cleaver.c
scripts/4_World/Entities/ItemBase/CombatKnife.c
scripts/4_World/Entities/ItemBase/CrudeMachete.c
scripts/4_World/Entities/ItemBase/FangeKnife.c
scripts/4_World/Entities/ItemBase/FirefighterAxe.c
scripts/4_World/Entities/ItemBase/Hacksaw.c
scripts/4_World/Entities/ItemBase/Hatchet.c
scripts/4_World/Entities/ItemBase/HuntingKnife.c
scripts/4_World/Entities/ItemBase/Inventory_Base/AK_Bayonet.c
scripts/4_World/Entities/ItemBase/Inventory_Base/M9A1_Bayonet.c
scripts/4_World/Entities/ItemBase/KitchenKnife.c
scripts/4_World/Entities/ItemBase/KukriKnife.c
scripts/4_World/Entities/ItemBase/Machete.c
scripts/4_World/Entities/ItemBase/OrientalMachete.c
scripts/4_World/Entities/ItemBase/Pliers.c
scripts/4_World/Entities/ItemBase/Screwdriver.c
scripts/4_World/Entities/ItemBase/Sickle.c
scripts/4_World/Entities/ItemBase/SteakKnife.c
scripts/4_World/Entities/ItemBase/StoneKnife.c
scripts/4_World/Entities/ItemBase/Sword.c
scripts/4_World/Entities/ItemBase/WoodAxe.c