DayZ: HealthNotfr Class Reference
HealthNotfr Class Reference
Protected Member Functions
float GetObservedValue ()
Private Member Functions
void HealthNotfr (NotifiersManager manager)
override int GetNotifierType ()
override void DisplayBadge ()
override void DisplayTendency (float delta)
override void HideBadge ()
Private Member Functions inherited from NotifierBase
int CalculateTendency (float delta, float inctresholdlow, float inctresholdmed, float inctresholdhigh, float dectresholdlow, float dectresholdmed, float dectresholdhigh)
eBadgeLevel DetermineBadgeLevel (float value, float lvl_1, float lvl_2, float lvl_3)
void DisplayBadge ()
void HideBadge ()
float GetObservedValue ()
Private Attributes
const float DEC_TRESHOLD_LOW = 0
const float DEC_TRESHOLD_MED = -0.7
const float DEC_TRESHOLD_HIGH = -1.3
const float INC_TRESHOLD_LOW = 0
const float INC_TRESHOLD_MED = 0.7
const float INC_TRESHOLD_HIGH = 1.3
Detailed Description
Definition at line 1 of file HealthNotfr.c.
Constructor & Destructor Documentation
HealthNotfr()
void HealthNotfr::HealthNotfr (NotifiersManager manager) inline private
Definition at line 18 of file HealthNotfr.c.
  {
    m_TickInterval = 3000;
    m_TendencyBufferSize = 6;
  }
References NotifierBase::m_TendencyBufferSize, and NotifierBase::m_TickInterval.
Member Function Documentation
DisplayBadge()
override void HealthNotfr::DisplayBadge () inline private
Definition at line 29 of file HealthNotfr.c.
  {
  }
DisplayTendency()
override void HealthNotfr::DisplayTendency (float delta) inline private
Definition at line 33 of file HealthNotfr.c.
  {
    int tendency = CalculateTendency(delta, INC_TRESHOLD_LOW, INC_TRESHOLD_MED, INC_TRESHOLD_HIGH, DEC_TRESHOLD_LOW, DEC_TRESHOLD_MED, DEC_TRESHOLD_HIGH);
    //PrintString("tendency:" + tendency);
    //GetVirtualHud().SetStatus(eDisplayElements.DELM_TDCY_HEALTH,tendency);
    //DSLevels level = DetermineLevel( GetObservedValue(), PlayerConstants.THRESHOLD_HEALTH_WARNING, PlayerConstants.THRESHOLD_HEALTH_CRITICAL, PlayerConstants.THRESHOLD_HEALTH_BLINKING, PlayerConstants.THRESHOLD_HEALTH_EXTRA);
    EStatLevels health_level = m_Player.GetStatLevelHealth();
    DisplayElementTendency dis_elm = DisplayElementTendency.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_TDCY_HEALTH));
    if (dis_elm)
    {
      dis_elm.SetSeriousnessLevel(health_level);
      dis_elm.SetTendency(tendency);
    }
  }
References NotifierBase::CalculateTendency(), DEC_TRESHOLD_HIGH, DEC_TRESHOLD_LOW, DEC_TRESHOLD_MED, GetElement(), NotifierBase::GetVirtualHud(), INC_TRESHOLD_HIGH, INC_TRESHOLD_LOW, INC_TRESHOLD_MED, and NotifierBase::m_Player.
GetNotifierType()
override int HealthNotfr::GetNotifierType () inline private
Definition at line 24 of file HealthNotfr.c.
  {
    return eNotifiers.NTF_HEALTHY;
  }
GetObservedValue()
float HealthNotfr::GetObservedValue () inline protected
Definition at line 57 of file HealthNotfr.c.
  {
    float health = m_Player.GetHealth("", "Health");
    //PrintString("health:" + health);
    return health;
  }
References NotifierBase::m_Player.
HideBadge()
override void HealthNotfr::HideBadge () inline private
Definition at line 51 of file HealthNotfr.c.
  {
  }
Member Data Documentation
DEC_TRESHOLD_HIGH
const float HealthNotfr::DEC_TRESHOLD_HIGH = -1.3 private
Definition at line 12 of file HealthNotfr.c.
Referenced by DisplayTendency().
DEC_TRESHOLD_LOW
const float HealthNotfr::DEC_TRESHOLD_LOW = 0 private
Definition at line 10 of file HealthNotfr.c.
Referenced by DisplayTendency().
DEC_TRESHOLD_MED
const float HealthNotfr::DEC_TRESHOLD_MED = -0.7 private
Definition at line 11 of file HealthNotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_HIGH
const float HealthNotfr::INC_TRESHOLD_HIGH = 1.3 private
Definition at line 15 of file HealthNotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_LOW
const float HealthNotfr::INC_TRESHOLD_LOW = 0 private
Definition at line 13 of file HealthNotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_MED
const float HealthNotfr::INC_TRESHOLD_MED = 0.7 private
Definition at line 14 of file HealthNotfr.c.
Referenced by DisplayTendency().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/PlayerNotifiers/Notifiers/HealthNotfr.c