DayZ: FuelStation Class Reference
FuelStation Class Reference
Private Member Functions
override void EEKilled (Object killer)
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
bool HasFuelToGive ()
Returns true if this stand is functional.
Detailed Description
Definition at line 1 of file Land_FuelStation_Feed.c.
Member Function Documentation
EEKilled()
override void FuelStation::EEKilled (Object killer) inline private
Definition at line 3 of file Land_FuelStation_Feed.c.
  {
    super.EEKilled(killer);
    Explode(DT_EXPLOSION, "LandFuelFeed_Ammo");
  }
References Explode().
HasFuelToGive()
bool FuelStation::HasFuelToGive () inline private
Returns true if this stand is functional.
Definition at line 31 of file Land_FuelStation_Feed.c.
  {
    return !IsRuined();
  }
OnExplosionEffects()
override void FuelStation::OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType) inline private
Definition at line 10 of file Land_FuelStation_Feed.c.
  {
    super.OnExplosionEffects(source, directHit, componentIndex, surface, pos, surfNormal, energyFactor, explosionFactor, isWater, ammoType);
    if (!GetGame().IsDedicatedServer())
    {
      vector n = surfNormal.VectorToAngles() + "0 90 0";
      Particle p1 = ParticleManager.GetInstance().PlayInWorld(ParticleList.SMOKE_GENERIC_WRECK, pos);
      p1.SetOrientation(n);
      Particle p2 = ParticleManager.GetInstance().PlayInWorld(ParticleList.EXPLOSION_LANDMINE, pos);
      p2.SetOrientation(n);
      Particle p3 = ParticleManager.GetInstance().PlayInWorld(ParticleList.IMPACT_METAL_RICOCHET, pos);
      p3.SetOrientation(n);
      Particle p4 = ParticleManager.GetInstance().PlayInWorld(ParticleList.IMPACT_GRAVEL_RICOCHET, pos);
      p4.SetOrientation(n);
    }
  }
References ParticleList::EXPLOSION_LANDMINE, GetGame(), ParticleList::IMPACT_GRAVEL_RICOCHET, ParticleList::IMPACT_METAL_RICOCHET, ParticleManager(), and ParticleList::SMOKE_GENERIC_WRECK.
The documentation for this class was generated from the following file:
scripts/4_World/Entities/Building/Specific/Land_FuelStation_Feed.c