DayZ: scripts/4_World/Plugins/PluginBase/PluginDayzPlayerDebug.c File Reference
PluginDayzPlayerDebug.c File Reference
Classes
class PluginDayzPlayerDebugUserData
class HumanCommandActionCallback
Functions
class PluginDayzPlayerDebugUserData OnClick (Widget w, int x, int y, int button)
buttons clicks
void PluginDayzPlayerDebugUserData (string name, int category, int pUserData, bool pFullBody, int pStanceMask=-1)
int GetInt ()
bool IsFullBody ()
int GetStanceMask ()
int GetCategory ()
string GetName ()
Gets the name which is set for the ParticleManager, default is "ParticleSourceManager".
string GetNameUnique ()
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
void PluginDayzPlayerDebug ()
void CreateTypeNameMapping ()
void ~PluginDayzPlayerDebug ()
void RegisterDebugItem (ItemBase item, PlayerBase player)
bool IsActive ()
void ShowWidgets (bool show)
void Show ()
void Hide ()
void CaptureFocus ()
void ReleaseFocus ()
void ToggleDebugWindowEvent ()
void ToggleDebugWindowEventOld ()
void ToggleDebugWindowEventP ()
void ToggleDebugWindowSetMode (int pMode)
void CreateModuleWidgets ()
void DestroyModuleWidgets ()
void ShowCard (int pCard)
void Tick ()
void UpdatePlayerStatus (DayZPlayer pPlayer)
void DbgShowBoneName (DayZPlayer pPlayer)
void UpdateCommandModifiers (DayZPlayer pPlayer)
void DisplayActions (int pType)
void Actions_Start ()
void Actions_DoInternalCommand (int pCommandId)
void Actions_DoCancel ()
void Actions_UpdateGlobals (DayZPlayer pPlayer)
void PlayerSyncCreate ()
void PlayerSyncDelete ()
void UpdateItemAccessor (DayZPlayer pPlayer)
bool IsWeaponChange (out string pNewWeapon, out int pHideSlot, out int pShowSlot)
void CommandHandler ()
void RegisterAnimation (string name, int category, int pUserData, bool pFullBody, int pStanceMask=-1)
void RegisterAnimations ()
Variables
int m_iUserData
bool m_bIsFullBody
int m_iStanceMask
int m_Category
string m_Name
PluginDayzPlayerDebug m_pPluginPlayerDebug
class PluginDayzPlayerActionCallback extends HumanCommandActionCallback TYPE_MOD_LOOPING = 0
const int TYPE_MOD_ONETIME = 1
const int TYPE_FB_LOOPING = 2
const int TYPE_FB_ONETIME = 3
const int TYPE_MOD_GESTURE_LOOPING = 4
const int TYPE_MOD_GESTURE_ONETIME = 5
const int TYPE_FB_GESTURE_LOOPING = 6
const int TYPE_FB_GESTURE_ONETIME = 7
const int TYPE_FB_SUICIDE_LOOPING = TYPE_FB_GESTURE_LOOPING
const int TYPE_ALL = -1
ref Timer m_TickTimer
ref array< ref PluginDayzPlayerDebugUserData > m_AnimationList = new array<ref PluginDayzPlayerDebugUserData>()
ref map< string, ref PluginDayzPlayerDebugUserData > m_AnimationListMappings = new map<string, ref PluginDayzPlayerDebugUserData>()
ref map< int, string > m_TypeNameMappings = new map<int, string>()
bool m_IsActive = false
bool m_HasFocus = false
bool m_HasServerWalk = false
Widget m_MainWnd
Widget m_Card0
Widget m_Card1
Widget m_Card2
Widget m_Card3
Widget m_Card4
ButtonWidget m_Card0Button
ButtonWidget m_Card1Button
ButtonWidget m_Card2Button
ButtonWidget m_Card3Button
ButtonWidget m_Card4Button
EditBoxWidget m_PlayerStatusV
TextListboxWidget m_ActionsSelector
ButtonWidget m_ActionsStart
ButtonWidget m_ActionsEnd
ButtonWidget m_ActionsFinish
ButtonWidget m_ActionsCancel
ButtonWidget m_ActionsOTA
ButtonWidget m_ActionsOTL
TextWidget m_ActionStateV
TextWidget m_ActionEventV
TextWidget m_ActionsGlobalStatus
EditBoxWidget m_ActionsFilter
ButtonWidget m_PlayerSyncCreateShadow
ButtonWidget m_PlayerSyncDelete
ButtonWidget m_PlayerServerWalk
TextWidget m_ItemAccClass
TextWidget m_ItemAccSClass
TextWidget m_ItemAccInst
ButtonWidget m_ActionTypeAll
ButtonWidget m_ActionTypeLA
ButtonWidget m_ActionTypeOA
ButtonWidget m_ActionTypeFLA
ButtonWidget m_ActionTypeFOA
ButtonWidget m_ActionTypeLG
ButtonWidget m_ActionTypeOG
ButtonWidget m_ActionTypeFLG
ButtonWidget m_ActionTypeFOG
ButtonWidget m_ClearEventsButton
TextListboxWidget m_EventsHistory
ref PluginDayzPlayerDebugUIHandler m_pUIHandler
Entity m_pPlayerShadow
int m_CurrentType
bool m_CH_ActionStart = false
int m_CH_ActionCommand = -1000
bool m_CH_ActionCancel = false
ref PluginDayzPlayerDebug_Weapons m_Weapons
ref PluginDayzPlayerDebug_Ctrl m_Controls
ref PluginDayzPlayerDebug_OtherCmds m_OtherCmds
int m_CurrentMode = 0
Function Documentation
Actions_DoCancel()
void Actions_DoCancel () protected
Definition at line 770 of file PluginDayzPlayerDebug.c.
  {
    DayZPlayer player = DayZPlayer.Cast(GetGame().GetPlayer());
    if (!player)
      return;
    HumanCommandActionCallback clbk = player.GetCommand_Action();
    if (!clbk)
    {
      clbk = player.GetCommandModifier_Action();
      if (!clbk)
        return;
    }
    clbk.Cancel();
  }
References GetGame(), and GetPlayer().
Referenced by CommandHandler().
Actions_DoInternalCommand()
void Actions_DoInternalCommand (int pCommandId) protected
Definition at line 751 of file PluginDayzPlayerDebug.c.
  {
    DayZPlayer player = DayZPlayer.Cast(GetGame().GetPlayer());
    if (!player)
      return;
    HumanCommandActionCallback clbk = player.GetCommand_Action();
    if (!clbk)
    {
      clbk = player.GetCommandModifier_Action();
      if (!clbk)
        return;
    }
    clbk.InternalCommand(pCommandId);
  }
References GetGame(), and GetPlayer().
Referenced by CommandHandler().
Actions_Start()
void Actions_Start () protected
start action
Definition at line 720 of file PluginDayzPlayerDebug.c.
  {
    int row = m_ActionsSelector.GetSelectedRow();
    if (row == -1)
      return;
    DayZPlayer player = DayZPlayer.Cast(GetGame().GetPlayer());
    if (!player)
      return;
    PluginDayzPlayerDebugUserData userData;
    m_ActionsSelector.GetItemData(row, 0, userData);
    PluginDayzPlayerActionCallback a;
    if (userData.IsFullBody())
      a = PluginDayzPlayerActionCallback.Cast(player.StartCommand_Action(userData.GetInt(), PluginDayzPlayerActionCallback, userData.GetStanceMask()));
    else
      a = PluginDayzPlayerActionCallback.Cast(player.AddCommandModifier_Action(userData.GetInt(), PluginDayzPlayerActionCallback));
    m_ActionEventV.SetText("");
    a.m_pStateWidget = m_ActionStateV;
    a.m_pAnimEventWidget = m_ActionEventV;
    a.m_EventsHistory = m_EventsHistory;
    Print(m_ActionStateV);
    m_ActionStateV.SetText("Crash Test");
  }
References GetGame(), GetPlayer(), m_ActionEventV, m_ActionsSelector, m_ActionStateV, m_EventsHistory, and Print().
Referenced by CommandHandler().
Actions_UpdateGlobals()
void Actions_UpdateGlobals (DayZPlayer pPlayer) protected
Definition at line 789 of file PluginDayzPlayerDebug.c.
  {
    HumanCommandActionCallback clbk = pPlayer.GetCommandModifier_Action();
    if (!clbk)
      m_ActionsGlobalStatus.SetText("No Action");
    m_ActionsGlobalStatus.SetText(clbk.ToString());
  }
References m_ActionsGlobalStatus.
Referenced by UpdateCommandModifiers().
CaptureFocus()
void CaptureFocus () protected
Definition at line 354 of file PluginDayzPlayerDebug.c.
  {
    if (!m_HasFocus)
    {
      GetGame().GetInput().ChangeGameFocus(1);
      GetGame().GetUIManager().ShowUICursor(true);
      m_HasFocus = true;
    }
  }
References GetGame(), and m_HasFocus.
CommandHandler()
void CommandHandler () protected
Definition at line 968 of file PluginDayzPlayerDebug.c.
  {
    if (m_CH_ActionStart)
    {
      Actions_Start();
      m_CH_ActionStart = false;
    }
    if (m_CH_ActionCommand != -1000)
    {
      Actions_DoInternalCommand(m_CH_ActionCommand);
      m_CH_ActionCommand = -1000;
    }
    if (m_CH_ActionCancel)
    {
      Actions_DoCancel();
      m_CH_ActionCancel = false;
    }
    if (m_Weapons)
      m_Weapons.CommandHandler();
    if (m_Controls)
      m_Controls.CommandHandler();
    if (m_OtherCmds)
      m_OtherCmds.CommandHandler();
  }
References Actions_DoCancel(), Actions_DoInternalCommand(), Actions_Start(), m_CH_ActionCancel, m_CH_ActionCommand, m_CH_ActionStart, m_Controls, m_OtherCmds, and m_Weapons.
CreateModuleWidgets()
void CreateModuleWidgets () protected
Definition at line 434 of file PluginDayzPlayerDebug.c.
  {
    if (!m_pUIHandler)
    {
      m_pUIHandler = new PluginDayzPlayerDebugUIHandler();
      m_pUIHandler.m_pPluginPlayerDebug = this;
    }
    if (!m_MainWnd)
    {
      m_MainWnd = GetGame().GetWorkspace().CreateWidgets("gui/layouts/debug/day_z_playerdebug.layout");
      m_MainWnd.SetHandler(m_pUIHandler);
      m_MainWnd.Show(false);
    }
    m_Card0 = m_MainWnd.FindAnyWidget("Card0");
    m_Card1 = m_MainWnd.FindAnyWidget("Card1");
    m_Card2 = m_MainWnd.FindAnyWidget("Card2");
    m_Card3 = m_MainWnd.FindAnyWidget("Card3");
    m_Card4 = m_MainWnd.FindAnyWidget("Card4");
    m_Card0Button = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("Card0Button"));
    m_Card1Button = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("Card1Button"));
    m_Card2Button = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("Card2Button"));
    m_Card3Button = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("Card3Button"));
    m_Card4Button = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("Card4Button"));
    m_PlayerStatusV = EditBoxWidget.Cast(m_MainWnd.FindAnyWidget("PlayerStatusV"));
    m_ActionsSelector = TextListboxWidget.Cast(m_MainWnd.FindAnyWidget("ActionsSelector"));
    m_ActionsStart = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ActionsStart"));
    m_ActionsEnd = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ActionsEnd"));
    m_ActionsFinish = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ActionsFinish"));
    m_ActionsCancel = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ActionsCancel"));
    m_ActionsOTA = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ActionsOTA"));
    m_ActionsOTL = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ActionsOTL"));
    m_ActionStateV = TextWidget.Cast(m_MainWnd.FindAnyWidget("ActionStateV"));
    m_ActionEventV = TextWidget.Cast(m_MainWnd.FindAnyWidget("ActionEventV"));
    m_ActionsGlobalStatus = TextWidget.Cast(m_MainWnd.FindAnyWidget("ActionGlobalStatus"));
    m_ActionsFilter = EditBoxWidget.Cast(m_MainWnd.FindAnyWidget("FilterField"));
    m_PlayerSyncCreateShadow = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("PlayerSyncCreate"));
    m_PlayerSyncDelete = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("PlayerSyncDelete"));
    m_PlayerServerWalk = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("PlayerServerWalk"));
    m_ItemAccClass = TextWidget.Cast(m_MainWnd.FindAnyWidget("ItemAccessClass"));
    m_ItemAccSClass = TextWidget.Cast(m_MainWnd.FindAnyWidget("ItemAccessSClass"));
    m_ItemAccInst = TextWidget.Cast(m_MainWnd.FindAnyWidget("ItemAccessInst"));
    m_ActionTypeAll = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ActionsGroupALL"));
    m_ActionTypeLA = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ActionsGroupLA"));
    m_ActionTypeOA = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ActionsGroupOA"));
    m_ActionTypeFLA = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ActionsGroupFLA"));
    m_ActionTypeFOA = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ActionsGroupFOA"));
    m_ActionTypeLG = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ActionsGroupLG"));
    m_ActionTypeOG = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ActionsGroupOG"));
    m_ActionTypeFLG = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ActionsGroupFLG"));
    m_ActionTypeFOG = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ActionsGroupFOG"));
    m_EventsHistory = TextListboxWidget.Cast(m_MainWnd.FindAnyWidget("EventHistory"));
    m_ClearEventsButton = ButtonWidget.Cast(m_MainWnd.FindAnyWidget("ClearButton"));
    DisplayActions(-1);
    ShowCard(0);
    // m_DebugAgentListWidget = m_DebugRootWidget.FindAnyWidget("w_Agents");
    // m_DebugFloatsListWidget = m_DebugRootWidget.FindAnyWidget("w_Floats");
    // m_DebugStringsListWidget = m_DebugRootWidget.FindAnyWidget("w_Strings");
    // m_DebugFloatsProperListWidget = m_DebugRootWidget.FindAnyWidget("w_FloatsProper");
    // m_ItemPreviewWidget = m_DebugRootWidget.FindAnyWidget("w_ItemPreview");
    // m_ClassNameWidget = m_DebugRootWidget.FindAnyWidget("w_ClassName");
  }
References DisplayActions(), GetGame(), m_ActionEventV, m_ActionsCancel, m_ActionsEnd, m_ActionsFilter, m_ActionsFinish, m_ActionsGlobalStatus, m_ActionsOTA, m_ActionsOTL, m_ActionsSelector, m_ActionsStart, m_ActionStateV, m_ActionTypeAll, m_ActionTypeFLA, m_ActionTypeFLG, m_ActionTypeFOA, m_ActionTypeFOG, m_ActionTypeLA, m_ActionTypeLG, m_ActionTypeOA, m_ActionTypeOG, m_Card0, m_Card0Button, m_Card1, m_Card1Button, m_Card2, m_Card2Button, m_Card3, m_Card3Button, m_Card4, m_Card4Button, m_ClearEventsButton, m_EventsHistory, m_ItemAccClass, m_ItemAccInst, m_ItemAccSClass, m_MainWnd, m_PlayerServerWalk, m_PlayerStatusV, m_PlayerSyncCreateShadow, m_PlayerSyncDelete, m_pUIHandler, and PluginBase::ShowCard().
CreateTypeNameMapping()
void CreateTypeNameMapping () protected
Definition at line 287 of file PluginDayzPlayerDebug.c.
  {
    m_TypeNameMappings.Insert(TYPE_MOD_LOOPING, "MOD_LOOPING");
    m_TypeNameMappings.Insert(TYPE_MOD_ONETIME, "MOD_ONETIME");
    m_TypeNameMappings.Insert(TYPE_FB_LOOPING, "FB_LOOPING");
    m_TypeNameMappings.Insert(TYPE_FB_ONETIME, "FB_ONETIME");
    m_TypeNameMappings.Insert(TYPE_MOD_GESTURE_LOOPING, "MOD_GESTURE_LOOPING");
    m_TypeNameMappings.Insert(TYPE_MOD_GESTURE_ONETIME, "MOD_GESTURE_ONETIME");
    m_TypeNameMappings.Insert(TYPE_FB_GESTURE_LOOPING, "FB_GESTURE_LOOPING");
    m_TypeNameMappings.Insert(TYPE_FB_GESTURE_ONETIME, "FB_GESTURE_ONETIME");
  }
References m_TypeNameMappings, TYPE_FB_GESTURE_LOOPING, TYPE_FB_GESTURE_ONETIME, TYPE_FB_LOOPING, TYPE_FB_ONETIME, TYPE_MOD_GESTURE_LOOPING, TYPE_MOD_GESTURE_ONETIME, TYPE_MOD_LOOPING, and TYPE_MOD_ONETIME.
Referenced by PluginDayzPlayerDebug().
DbgShowBoneName()
void DbgShowBoneName (DayZPlayer pPlayer) protected
Definition at line 620 of file PluginDayzPlayerDebug.c.
  {
    int boneIndex = pPlayer.GetBoneIndexByName("Head");
    // vector   pos     = pPlayer.GetBonePositionMS(boneIndex);
    vector tm[4];
    pPlayer.GetBoneTransformMS(boneIndex, tm);
    string a = "Bone index:";
    a += boneIndex.ToString();
    a += ",";
    a += tm.ToString();
    Print(a);
  }
References Print().
DestroyModuleWidgets()
void DestroyModuleWidgets () protected
Definition at line 510 of file PluginDayzPlayerDebug.c.
  {
    delete m_MainWnd;
  }
References PluginBase::m_MainWnd.
DisplayActions()
void DisplayActions (int pType) protected
Definition at line 670 of file PluginDayzPlayerDebug.c.
  {
    m_CurrentType = pType;
    TStringArray sortedNames = new TStringArray();
    m_ActionsSelector.ClearItems();
    string filterTextLower = m_ActionsFilter.GetText();
    filterTextLower.ToLower();
    TStringArray filterTokens = new TStringArray;
    filterTextLower.Split(" ", filterTokens);
    foreach (PluginDayzPlayerDebugUserData dta: m_AnimationList)
    {
      string nameLower = dta.GetName();
      nameLower.ToLower();
      bool add = false;
      if (pType == -1 || pType == dta.GetCategory())
      {
        if (filterTextLower)
        {
          foreach (string token: filterTokens)
          {
            if (nameLower.Contains(token))
              add = true;
          }
        }
        else
          add = true;
      }
      if (add)
        sortedNames.Insert(dta.GetNameUnique());
    }
    sortedNames.Sort();
    foreach (int i, string sortedNameUnique: sortedNames)
    {
      PluginDayzPlayerDebugUserData data = m_AnimationListMappings.Get(sortedNameUnique);
      string sortedName = data.GetName();
      string typeName;
      if (m_TypeNameMappings.Contains(data.GetCategory()))
        typeName = m_TypeNameMappings.Get(data.GetCategory());
      m_ActionsSelector.AddItem(sortedName, data, 0, i);
      if (typeName)
        m_ActionsSelector.SetItem(i, typeName, null, 1);
    }
  }
References m_ActionsFilter, m_ActionsSelector, m_AnimationList, m_AnimationListMappings, m_CurrentType, and m_TypeNameMappings.
Referenced by CreateModuleWidgets().
GetCategory()
int OnClick::GetCategory ()
Definition at line 81 of file PluginDayzPlayerDebug.c.
Referenced by OnErrorThrown().
GetInt()
int OnClick::GetInt ()
Definition at line 66 of file PluginDayzPlayerDebug.c.
  {
Referenced by PluginConfigHandler::GetBatchSpawnQuantity(), PluginConfigHandler::GetConfigClassesFlag(), PluginConfigHandler::GetEmoteFromSlot(), PluginConfigHandler::GetEmoteSlot1(), PluginConfigHandler::GetEmoteSlot10(), PluginConfigHandler::GetEmoteSlot11(), PluginConfigHandler::GetEmoteSlot2(), PluginConfigHandler::GetEmoteSlot3(), PluginConfigHandler::GetEmoteSlot4(), PluginConfigHandler::GetEmoteSlot5(), PluginConfigHandler::GetEmoteSlot6(), PluginConfigHandler::GetEmoteSlot7(), PluginConfigHandler::GetEmoteSlot8(), PluginConfigHandler::GetEmoteSlot9(), PluginConfigHandler::GetItemCategoryFlag(), PluginConfigHandler::GetSceneEditorRotationAngle(), PluginConfigHandler::GetSpawnLocIndex(), and PluginConfigHandler::GetTabSelected().
GetNameUnique()
string OnClick::GetNameUnique ()
Definition at line 90 of file PluginDayzPlayerDebug.c.
{
  protected static ref set<string> m_AnimEventMapping;
  void PluginDayzPlayerActionCallback()
GetStanceMask()
int OnClick::GetStanceMask ()
Definition at line 76 of file PluginDayzPlayerDebug.c.
  {
    super.OnMouseLeave(w, enterW, x, y);
    GetGame().GetMission().RemoveActiveInputExcludes({"menu"}, true);
References GetGame(), x, and y.
Referenced by Can(), AnimatedActionBase::CreateAndSetupActionCallback(), and SetupAction().
Hide()
void Hide () protected
Definition at line 345 of file PluginDayzPlayerDebug.c.
  {
    ShowWidgets(false);
    m_IsActive = false;
    m_TickTimer = NULL;
  }
References m_IsActive, m_TickTimer, and PluginBase::ShowWidgets().
IsActive()
bool IsActive () protected
Definition at line 320 of file PluginDayzPlayerDebug.c.
  {
    return m_IsActive;
  }
References PluginBase::m_IsActive.
IsFullBody()
bool OnClick::IsFullBody ()
Definition at line 71 of file PluginDayzPlayerDebug.c.
                                                  {"menu"});
    return true;
  }
Referenced by Can(), AnimatedActionBase::CreateAndSetupActionCallback(), and ManBase::HeadingModel().
IsWeaponChange()
bool IsWeaponChange (out string pNewWeapon, out int pHideSlot, out int pShowSlot) protected
Definition at line 956 of file PluginDayzPlayerDebug.c.
  {
    if (m_Weapons)
      m_Weapons.IsWeaponChange(pNewWeapon, pHideSlot, pShowSlot);
    return false;
  }
References m_Weapons.
OnChange()
override bool OnChange (Widget w, int x, int y, bool finished)
Definition at line 62 of file PluginDayzPlayerDebug.c.
  {
    super.OnChange(w, x, y, finished);
    return m_pPluginPlayerDebug.OnChange(w, x, y, finished);
  }
References m_pPluginPlayerDebug, x, and y.
OnClick()
class PluginDayzPlayerDebugUserData OnClick (Widget w, int x, int y, int button)
buttons clicks
send rcp
Definition at line 1 of file PluginDayzPlayerDebug.c.
  {
    super.OnClick(w, x, y, button);
    return m_pPluginPlayerDebug.OnClick(w, x, y, button);
  }
OnMouseEnter()
override bool OnMouseEnter (Widget w, int x, int y)
Definition at line 68 of file PluginDayzPlayerDebug.c.
  {
    super.OnMouseEnter(w, x, y);
    GetGame().GetMission().AddActiveInputExcludes({"menu"});
    return true;
  }
References x, and y.
OnMouseLeave()
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
Definition at line 76 of file PluginDayzPlayerDebug.c.
  {
    super.OnMouseLeave(w, enterW, x, y);
    GetGame().GetMission().RemoveActiveInputExcludes({"menu"}, true);
    return true;
  }
PlayerSyncCreate()
void PlayerSyncCreate () protected
Definition at line 802 of file PluginDayzPlayerDebug.c.
  {
    PlayerSyncDelete();
    vector item_position = GetGame().GetPlayer().GetPosition() + (GetGame().GetPlayer().GetDirection() * 2.0);
    m_pPlayerShadow = Entity.Cast(GetGame().CreateObject("SurvivorM_Mirek", item_position, false, false));
    DayZPlayer pl = DayZPlayer.Cast(GetGame().GetPlayer());
    pl.DebugSyncShadowSetup(DayZPlayer.Cast(m_pPlayerShadow));
  }
References GetGame(), m_pPlayerShadow, and PlayerSyncDelete().
PlayerSyncDelete()
void PlayerSyncDelete () protected
Definition at line 814 of file PluginDayzPlayerDebug.c.
  {
    if (m_pPlayerShadow)
    {
      GetGame().ObjectDelete(m_pPlayerShadow);
      m_pPlayerShadow = NULL;
    }
    DayZPlayer pl = DayZPlayer.Cast(GetGame().GetPlayer());
    if (pl)
      pl.DebugSyncShadowSetup(NULL);
  }
References GetGame(), GetPlayer(), and m_pPlayerShadow.
Referenced by PlayerSyncCreate(), and ~PluginDayzPlayerDebug().
PluginDayzPlayerDebug()
void PluginDayzPlayerDebug () protected
Definition at line 269 of file PluginDayzPlayerDebug.c.
  {
    RegisterAnimations();
    CreateTypeNameMapping();
#ifndef NO_GUI
    CreateModuleWidgets();
    m_Weapons = new PluginDayzPlayerDebug_Weapons(m_Card1);
    m_Controls = new PluginDayzPlayerDebug_Ctrl(m_Card2);
    m_OtherCmds = new PluginDayzPlayerDebug_OtherCmds(m_Card3);
#endif
    //m_TypeNameMappings.Insert(TYPE_FB_SUICIDE_LOOPING, "TYPE_FB_SUICIDE_LOOPING");
  }
References PluginBase::CreateModuleWidgets(), CreateTypeNameMapping(), m_Card1, m_Card2, m_Card3, m_Controls, m_OtherCmds, m_Weapons, and RegisterAnimations().
Referenced by DayZPlayer::CommandHandlerDebug().
PluginDayzPlayerDebugUserData()
void OnClick::PluginDayzPlayerDebugUserData (string name, int category, int pUserData, bool pFullBody, int pStanceMask = -1)
Definition at line 57 of file PluginDayzPlayerDebug.c.
  {
    super.OnClick(w, x, y, button);
    return m_pPluginPlayerDebug.OnClick(w, x, y, button);
  }
  override bool OnChange(Widget w, int x, int y, bool finished)
  {
    super.OnChange(w, x, y, finished);
References m_pPluginPlayerDebug, x, and y.
Referenced by RegisterAnimation().
RegisterAnimation()
void RegisterAnimation (string name, int category, int pUserData, bool pFullBody, int pStanceMask = -1) protected
Definition at line 998 of file PluginDayzPlayerDebug.c.
  {
    PluginDayzPlayerDebugUserData data = new PluginDayzPlayerDebugUserData(name, category, pUserData, pFullBody, pStanceMask);
    m_AnimationList.Insert(data);
    m_AnimationListMappings.Insert(data.GetNameUnique(), data);
  }
References m_AnimationList, m_AnimationListMappings, name, and PluginDayzPlayerDebugUserData().
Referenced by RegisterAnimations().
RegisterAnimations()
void RegisterAnimations () protected
one time
fullbody looping
one time
-------------------— GESTURES ----------------------—
looping
one time
fullbody looping
fullbody one time
-------------------— SUICIDE -----------------------—
fullbody looping
Definition at line 1005 of file PluginDayzPlayerDebug.c.
  {
    RegisterAnimation("CLEAN HANDS BOTTLE", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_CLEANHANDSBOTTLE, false);
    RegisterAnimation("DRINK", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_DRINK, false);
    RegisterAnimation("EAT", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_EAT, false);
    RegisterAnimation("EMPTY VESSEL", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_EMPTY_VESSEL, false);
    RegisterAnimation("CATCH RAIN", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_CATCHRAIN, false);
    RegisterAnimation("VIEW COMPASS", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_VIEWCOMPASS, false);
    RegisterAnimation("ITEM TUNE", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_ITEM_TUNE, false);
    RegisterAnimation("GIVE L ITEM", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_GIVEL, false);
    RegisterAnimation("GIVE R ITEM", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_GIVER, false);
    RegisterAnimation("SHAVE", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_SHAVE, false);
    RegisterAnimation("FILL MAG", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_FILLMAG, false);
    RegisterAnimation("EMPTY MAG", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_EMPTYMAG, false);
    RegisterAnimation("OPEN ITEM", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_OPENITEM, false);
    RegisterAnimation("TAKE TEMP SELF", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_TAKETEMPSELF, false);
    RegisterAnimation("VIEW MAP", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_VIEWMAP, false);
    RegisterAnimation("RAISE ITEM", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_RAISEITEM, false);
    RegisterAnimation("SEARCH INVENTORY", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_SEARCHINVENTORY, false);
    RegisterAnimation("CRAFTING UPPDERBODY", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_CRAFTING, false);
    RegisterAnimation("RESTRAINED STRUGGLE", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_RESTRAINEDSTRUGGLE, false);
    RegisterAnimation("COVER HEAD SELF", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_COVERHEAD_SELF, false);
    RegisterAnimation("COVER HEAD TARGET", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_COVERHEAD_TARGET, false);
    RegisterAnimation("SET ALARM CLOCK", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_SET_ALARM, false);
    RegisterAnimation("ENGINE START", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_STARTENGINE, false);
    RegisterAnimation("TOOT HORN", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_TOOTHORN, false);
    RegisterAnimation("ENGINE STOP", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_STOPENGINE, false);
    RegisterAnimation("SHIFT GEAR", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_SHIFTGEAR, false);
    RegisterAnimation("TURN ON/OFF LIGHTS", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_HEADLIGHT, false);
    RegisterAnimation("DRIVER OPEN DOOR", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_DRIVER_DOOR_OPEN, false);
    RegisterAnimation("DRIVER CLOSE DOOR", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_DRIVER_DOOR_CLOSE, false);
    RegisterAnimation("CODRIVER OPEN DOOR", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_CODRIVER_DOOROPEN, false);
    RegisterAnimation("CODRIVER CLOSE DOOR", TYPE_MOD_LOOPING, DayZPlayerConstants.CMD_ACTIONMOD_CODRIVER_DOORCLOSE, false);
    RegisterAnimation("PICK UP HANDS", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_HANDS, false);
    RegisterAnimation("PICK UP INVENTORY", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_INVENTORY, false);
    RegisterAnimation("LICK BATTERY", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_LICKBATTERY, false);
    RegisterAnimation("LIGHT FLARE", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_LIGHTFLARE, false);
    RegisterAnimation("LITCHEM LIGHT", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_LITCHEMLIGHT, false);
    RegisterAnimation("UNPIN GRENAGE", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_UNPINGRENAGE, false);
    RegisterAnimation("OPEN DOOR FW", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_OPENDOORFW, false);
    RegisterAnimation("OPEN LID", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_OPENLID, false);
    RegisterAnimation("CLOSE LID", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_CLOSELID, false);
    RegisterAnimation("RADIO ON", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_ITEM_ON, false);
    RegisterAnimation("RADIO OFF", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_ITEM_OFF, false);
    RegisterAnimation("BATON EXTEND", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_BATONEXTEND, false);
    RegisterAnimation("BATON RETRACT", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_BATONRETRACT, false);
    RegisterAnimation("UNLOCK HANDCUFF TARGET", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_UNLOCKHANDCUFFTARGET, false);
    RegisterAnimation("FISHINGROD EXTEND", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_FISHINGRODEXTEND, false);
    RegisterAnimation("FISHINGROD RETRACT", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_FISHINGRODRETRACT, false);
    RegisterAnimation("OPEN ITEM ONCE", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_OPENITEM_ONCE, false);
    RegisterAnimation("CLOSE ITEM ONCE", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_CLOSEITEM_ONCE, false);
    RegisterAnimation("ATTACH SCOPE", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_ATTACHSCOPE, false);
    RegisterAnimation("ATTACH BARREL", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_ATTACHBARREL, false);
    RegisterAnimation("EMPTY SEEDS PACK", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_EMPTYSEEDSPACK, false);
    RegisterAnimation("INTERACT", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_INTERACTONCE, false);
    RegisterAnimation("ATTACH ITEM", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_ATTACHITEM, false);
    RegisterAnimation("STOP ALARM CLOCK", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_STOP_ALARM, false);
    RegisterAnimation("PRESS TRIGGER", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_PRESS_TRIGGER, false);
    RegisterAnimation("DROP ITEM HANDS", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_DROPITEM_HANDS, false);
    RegisterAnimation("DROP ITEM INVENTORY", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_DROPITEM_INVENTORY, false);
    RegisterAnimation("EAT PILL", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_EAT_PILL, false);
    RegisterAnimation("EAT TABLET", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_EAT_TABLET, false);
    RegisterAnimation("HEATPACK", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_HEATPACK, false);
    RegisterAnimation("BLOODTEST", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_BLOODTEST, false);
    RegisterAnimation("BLOODTESTOTHER", TYPE_MOD_ONETIME, DayZPlayerConstants.CMD_ACTIONMOD_BLOODTESTOTHER, false);
    RegisterAnimation("DRINK", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_DRINK, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("EAT", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_EAT, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("CATCH RAIN", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_CATCHRAIN, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("WALKIETALKIE TUNE", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_ITEM_TUNE, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("GIVE L ITEM", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_GIVEL, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("GIVE R ITEM", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_GIVER, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("FILL MAG", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_FILLMAG, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("EMPTY MAG", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_EMPTYMAG, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("DRINK POND", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_DRINKPOND, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("DRINK WELL", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_DRINKWELL, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("FILL BOTTLE WELL", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_FILLBOTTLEWELL, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("FIRE ESTINGUISHER", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_FIREESTINGUISHER, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("FLAME REPAIR", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_FLAME_REPAIR, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("WRING CLOTH", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_WRING, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("FISHING", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_FISHING, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("CPR", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_CPR, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("BANDAGE", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_BANDAGE, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("CRAFTING", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_CRAFTING, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("INTERACT", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_INTERACT, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("FORCE FEED TARGET", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_FORCEFEED, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("BANDAGE TARGET", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_BANDAGETARGET, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("SPRAY PLANT", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_SPRAYPLANT, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("START FIRE", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_STARTFIRE, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("ANIMAL SKINNING", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_ANIMALSKINNING, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("WASH HANDS WELL", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_WASHHANDSWELL, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("WASH HANDS POND", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_WASHHANDSPOND, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("SALINE BLOODBAG TARGET", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_SALINEBLOODBAGTARGET, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("SALINE BLOOD BAG", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_SALINEBLOODBAG, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("STITCH UP SELF", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_STITCHUPSELF, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("VOMIT", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_VOMIT, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("UNRESTRAINT TARGET", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_UNRESTRAINTARGET, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("RESTRAIN TARGET", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_RESTRAINTARGET, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("CHECK PULSE", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_CHECKPULSE, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("CLEAN WOUNDS TARGET", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_CLEANWOUNDSTARGET, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("COLLECT BLOOD SELF", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_COLLECTBLOODSELF, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("EMPTY VESSEL", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_EMPTY_VESSEL, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("OPEN ITEM", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_OPENITEM, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("HACK BUSH", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_HACKBUSH, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("HACK TREE", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_HACKTREE, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("TAKE TEMP SELF", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_TAKETEMPSELF, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("DIG HOLE", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_DIG, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("DIG UP CACHE", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_DIGUPCACHE, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("DIG MANIPULATE", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_DIGMANIPULATE, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("DEPLOY HEAVY", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_HEAVY, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("DEPLOY 1HD", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_1HD, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("DEPLOY 2HD", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_2HD, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("BLOW FIREPLACE", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_BLOWFIREPLACE, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("VIEW MAP", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_VIEWMAP, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("VIEW COMPASS", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_VIEWCOMPASS, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("FILL BOTTLE POND", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_FILLBOTTLEPOND, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("PLACING HEAVY", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_PLACING_HEAVY, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("PLACING 1HD", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_PLACING_1HD, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("PLACING 2HD", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_PLACING_2HD, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("CUT BARK", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_CUTBARK, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("VIEW NOTE", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_VIEWNOTE, true, DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("SEARCH INVENTORY", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_SEARCHINVENTORY, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("LOOK OPTICS", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_LOOKOPTICS, true, DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("MINE ROCK", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_MINEROCK, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("RAISE ITEM", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_RAISEITEM, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("RESTRAINED STRUGGLE", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_RESTRAINEDSTRUGGLE, true, DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("RESTRAIN SELF", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_RESTRAINSELF, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("ASSEMBLE", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_ASSEMBLE, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("DISASSEMBLE", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_DISASSEMBLE, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("RAISE FLAG", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_RAISE_FLAG, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("LOWER FLAG", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_LOWER_FLAG, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("SET ALARM CLOCK", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_SET_ALARM, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("SHOVEL DIG", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_SHOVEL_DIG, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("VEHICLE_PUSH", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_VEHICLE_PUSH, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("PATCHING_TIRE", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_PATCHING_TIRE, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("PATCHING_DUCTTAPE", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_PATCHING_DUCTTAPE, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("PATCHING_SEWING", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_PATCHING_SEWING, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("PATCHING_LEATHER_SEWING_KIT", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_PATCHING_LEATHER_SEWING_KIT, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("SPLITTING FIREWOOD", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_SPLITTING_FIREWOOD, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("BREAKING STICK", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_BREAKING_STICK, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("CLEANING_WEAPON", TYPE_FB_LOOPING, DayZPlayerConstants.CMD_ACTIONFB_CLEANING_WEAPON, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("PICK UP HANDS", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HANDS, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("PICK UP INVENTORY", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_PICKUP_INVENTORY, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("LICK BATTERY", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_LICKBATTERY, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("LIGHT FLARE", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_LIGHTFLARE, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("LITCHEM LIGHT", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_LITCHEMLIGHT, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("UNPIN GRENAGE", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_UNPINGRENAGE, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("RADIO ON", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_ITEM_ON, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("RADIO OFF", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_ITEM_OFF, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("HANDCUFF TARGET", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_HANDCUFFTARGET, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("MORPHINE", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_MORPHINE, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("INJECTION", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_INJECTION, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("INJECTION TARGET", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_INJECTIONTARGET, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("DRINK SIP", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_DRINKSIP, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("CLEAN HANDS BOTTLE", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_CLEANHANDSBOTTLE, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("OPEN ITEM ONCE", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_OPENITEM_ONCE, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("POKE", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_POKE, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("ATTACH SCOPE", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_ATTACHSCOPE, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("ATTACH BARREL", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_ATTACHBARREL, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("RESTRAIN", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_RESTRAIN, true, DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("PICK UP HEAVY", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HEAVY, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("STOP ALARM CLOCK", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_STOP_ALARM, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("PRESS TRIGGER", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_PRESS_TRIGGER, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("EAT PILL", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_EAT_PILL, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("EAT TABLET", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_EAT_TABLET, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("HEATPACK", TYPE_FB_ONETIME, DayZPlayerConstants.CMD_ACTIONFB_HEATPACK, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("GREETING", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_GREETING, false);
    RegisterAnimation("POINT", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_POINT, false);
    RegisterAnimation("THUMB UP", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_THUMB, false);
    RegisterAnimation("THUMB DOWN", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_THUMB, false);
    RegisterAnimation("SILENCE", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_SILENCE, false);
    RegisterAnimation("TAUNT", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_TAUNT, false);
    RegisterAnimation("TIME OUT", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_TIMEOUT, false);
    RegisterAnimation("HEART", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_HEART, false);
    RegisterAnimation("FACEPALM", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_FACEPALM, false);
    RegisterAnimation("WATCHING", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_WATCHING, false);
    RegisterAnimation("HOLD", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_HOLD, false);
    RegisterAnimation("LISTENING", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_LISTENING, false);
    RegisterAnimation("POINT AT SELF", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_POINTSELF, false);
    RegisterAnimation("LOOK AT ME", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_LOOKATME, false);
    RegisterAnimation("OKAY", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_OKAY, false);
    RegisterAnimation("RPS", TYPE_MOD_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREMOD_RPS, false);
    RegisterAnimation("THROAT", TYPE_MOD_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREMOD_THROAT, false);
    RegisterAnimation("CLAP", TYPE_MOD_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREMOD_CLAP, false);
    RegisterAnimation("DABBING", TYPE_MOD_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREMOD_DABBING, false);
    RegisterAnimation("MOVE", TYPE_MOD_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREMOD_MOVE, false);
    RegisterAnimation("DOWN", TYPE_MOD_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREMOD_DOWN, false);
    RegisterAnimation("COME", TYPE_MOD_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREMOD_COME, false);
    RegisterAnimation("TAUNT KISS", TYPE_MOD_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREMOD_TAUNTKISS, false);
    RegisterAnimation("TAUNT ELBOW", TYPE_MOD_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREMOD_TAUNTELBOW, false);
    RegisterAnimation("TAUNT THINK", TYPE_MOD_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREMOD_TAUNTTHINK, false);
    RegisterAnimation("NOD HEAD", TYPE_MOD_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREMOD_NODHEAD, false);
    RegisterAnimation("SHAKE HEAD", TYPE_MOD_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREMOD_SHAKEHEAD, false);
    RegisterAnimation("SHRUG", TYPE_MOD_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREMOD_SHRUG, false);
    RegisterAnimation("SURRENDER", TYPE_MOD_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREMOD_SURRENDER, false);
    RegisterAnimation("GREETING", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_GREETING, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("POINT", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_POINT, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("THUMBUP", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_THUMB, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("THUMBDOWN", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_THUMB, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("SILENCE", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_SILENCE, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("TAUNT", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_TAUNT, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("TIMEOUT", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_TIMEOUT, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("HEART", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_HEART, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("WATCHING", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_WATCHING, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("HOLD", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_HOLD, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("LISTENING", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_LISTENING, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("POINTSELF", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_POINTSELF, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("LOOKATME", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_LOOKATME, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("OKAY", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_OKAY, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("SALUTE", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_SALUTE, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("CAMPFIRE", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_CAMPFIRE, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("LYINGDOWN", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_LYINGDOWN, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("SOS", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_SOS, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("SITA", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_SITA, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("SITB", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_SITB, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("DABBING", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_DABBING, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("SURRENDER", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_SURRENDER, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("KNEEL", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_GESTUREFB_KNEEL, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("TRAILER WAKE UP", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_TRAILER_WAKE_UP, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("TRAILER DEAD BODY", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_TRAILER_DEAD_BODY, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("TRAILER WALKIE TALKIE", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_TRAILER_WALKIE_TALKIE, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("TRAILER WOUNDED", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_TRAILER_WOUNDED, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("TRAILER WALK AWAY", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_TRAILER_WALK_AWAY, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("TRAILER DEAD DEAD", TYPE_FB_GESTURE_LOOPING, DayZPlayerConstants.CMD_TRAILER_DEAD, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("THROAT", TYPE_FB_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREFB_THROAT, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("MOVE", TYPE_FB_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREFB_MOVE, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("DOWN", TYPE_FB_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREFB_DOWN, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("COME", TYPE_FB_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREFB_COME, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("TAUNT KISS", TYPE_FB_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREFB_TAUNTKISS, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("TAUNT THINK", TYPE_FB_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREFB_TAUNTTHINK, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("DANCE", TYPE_FB_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREFB_DANCE, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("NOD HEAD", TYPE_FB_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREFB_NODHEAD, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("SHAKE HEAD", TYPE_FB_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREFB_SHAKEHEAD, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("SHRUG", TYPE_FB_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREFB_SHRUG, true, DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("SURRENDER", TYPE_FB_GESTURE_ONETIME, DayZPlayerConstants.CMD_GESTUREFB_SURRENDER, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_PRONE);
    RegisterAnimation("TRAILER MASK", TYPE_FB_GESTURE_ONETIME, DayZPlayerConstants.CMD_TRAILER_MASK, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("TRAILER MASK_02", TYPE_FB_GESTURE_ONETIME, DayZPlayerConstants.CMD_TRAILER_MASK_02, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("1HD", TYPE_FB_SUICIDE_LOOPING, DayZPlayerConstants.CMD_SUICIDEFB_1HD, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("FIREAXE", TYPE_FB_SUICIDE_LOOPING, DayZPlayerConstants.CMD_SUICIDEFB_FIREAXE, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("PITCHFORK", TYPE_FB_SUICIDE_LOOPING, DayZPlayerConstants.CMD_SUICIDEFB_PITCHFORK, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("PISTOL", TYPE_FB_SUICIDE_LOOPING, DayZPlayerConstants.CMD_SUICIDEFB_PISTOL, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("RIFLE", TYPE_FB_SUICIDE_LOOPING, DayZPlayerConstants.CMD_SUICIDEFB_RIFLE, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("SWORD", TYPE_FB_SUICIDE_LOOPING, DayZPlayerConstants.CMD_SUICIDEFB_SWORD, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("UNARMED", TYPE_FB_SUICIDE_LOOPING, DayZPlayerConstants.CMD_SUICIDEFB_UNARMED, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("WOODAXE", TYPE_FB_SUICIDE_LOOPING, DayZPlayerConstants.CMD_SUICIDEFB_WOODAXE, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("SPEAR", TYPE_FB_SUICIDE_LOOPING, DayZPlayerConstants.CMD_SUICIDEFB_SPEAR, true, DayZPlayerConstants.STANCEMASK_ERECT);
    RegisterAnimation("SICKLE", TYPE_FB_SUICIDE_LOOPING, DayZPlayerConstants.CMD_SUICIDEFB_SICKLE, true, DayZPlayerConstants.STANCEMASK_CROUCH);
    RegisterAnimation("HOE", TYPE_FB_SUICIDE_LOOPING, DayZPlayerConstants.CMD_SUICIDEFB_HOE, true, DayZPlayerConstants.STANCEMASK_ERECT);
  }
References RegisterAnimation(), TYPE_FB_GESTURE_LOOPING, TYPE_FB_GESTURE_ONETIME, TYPE_FB_LOOPING, TYPE_FB_ONETIME, TYPE_FB_SUICIDE_LOOPING, TYPE_MOD_GESTURE_LOOPING, TYPE_MOD_GESTURE_ONETIME, TYPE_MOD_LOOPING, and TYPE_MOD_ONETIME.
Referenced by PluginDayzPlayerDebug().
RegisterDebugItem()
void RegisterDebugItem (ItemBase item, PlayerBase player) protected
Definition at line 315 of file PluginDayzPlayerDebug.c.
  {
  }
ReleaseFocus()
void ReleaseFocus () protected
Definition at line 365 of file PluginDayzPlayerDebug.c.
  {
    if (m_HasFocus)
    {
      GetGame().GetInput().ChangeGameFocus(-1);
      GetGame().GetUIManager().ShowUICursor(false);
      m_HasFocus = false;
    }
  }
References GetGame(), and m_HasFocus.
Referenced by ToggleDebugWindowEvent().
Show()
void Show () protected
Definition at line 332 of file PluginDayzPlayerDebug.c.
  {
    ShowWidgets(true);
    m_IsActive = true;
    if (!m_TickTimer)
    {
      m_TickTimer = new Timer();
      m_TickTimer.Run(0.1, this, "Tick", NULL, true);
    }
  }
References m_IsActive, m_TickTimer, and PluginBase::ShowWidgets().
ShowCard()
void ShowCard (int pCard) protected
Definition at line 516 of file PluginDayzPlayerDebug.c.
  {
    m_Card0.Show(pCard == 0);
    m_Card1.Show(pCard == 1);
    m_Card2.Show(pCard == 2);
    m_Card3.Show(pCard == 3);
    m_Card4.Show(pCard == 4);
  }
References m_Card0, m_Card1, m_Card2, m_Card3, and m_Card4.
ShowWidgets()
void ShowWidgets (bool show) protected
Definition at line 325 of file PluginDayzPlayerDebug.c.
  {
    if (m_MainWnd)
      m_MainWnd.Show(show);
  }
References m_MainWnd.
Referenced by OnRPC(), PluginItemDiagnostic(), and ToggleDebugWindowEvent().
Tick()
void Tick () protected
Definition at line 530 of file PluginDayzPlayerDebug.c.
  {
    DayZPlayer player = DayZPlayer.Cast(GetGame().GetPlayer());
    if (!player)
      return;
    // Print("PluginDayzPlayerDebug tick");
    UpdatePlayerStatus(player);
    // DbgShowBoneName(player);
    UpdateCommandModifiers(player);
    UpdateItemAccessor(player);
    m_Weapons.Tick();
  }
References GetGame(), GetPlayer(), m_Weapons, UpdateCommandModifiers(), UpdateItemAccessor(), and UpdatePlayerStatus().
ToggleDebugWindowEvent()
void ToggleDebugWindowEvent () protected
Definition at line 378 of file PluginDayzPlayerDebug.c.
  {
    m_CurrentMode++;
    if (m_CurrentMode > 2)
      m_CurrentMode = 0;
    ToggleDebugWindowSetMode(m_CurrentMode);
  }
References m_CurrentMode, and PluginBase::ToggleDebugWindowSetMode().
Referenced by OnClick().
ToggleDebugWindowEventOld()
void ToggleDebugWindowEventOld () protected
act:0 foc:0 -> act:1 foc:0 act:1 foc:0 -> act:0 foc:0 act:1 foc:1 -> act:1 foc:0
Definition at line 389 of file PluginDayzPlayerDebug.c.
  {
    if (m_IsActive && !m_HasFocus)
      Hide();
    else
    {
      Show();
      ReleaseFocus();
    }
  }
References PluginBase::Hide(), m_HasFocus, m_IsActive, PluginBase::ReleaseFocus(), and PluginBase::Show().
ToggleDebugWindowEventP()
void ToggleDebugWindowEventP () protected
act:0 foc:0 -> act:1 foc:1 act:1 foc:0 -> act:1 foc:1 act:1 foc:1 -> act:0 foc:0
Definition at line 405 of file PluginDayzPlayerDebug.c.
  {
    if (m_IsActive && m_HasFocus)
    {
      Hide();
      ReleaseFocus();
    }
    else
    {
      Show();
      CaptureFocus();
    }
  }
References PluginBase::CaptureFocus(), PluginBase::Hide(), m_HasFocus, m_IsActive, PluginBase::ReleaseFocus(), and PluginBase::Show().
ToggleDebugWindowSetMode()
void ToggleDebugWindowSetMode (int pMode) protected
Definition at line 424 of file PluginDayzPlayerDebug.c.
  {
    switch (pMode)
    {
    case 0: Hide(); ReleaseFocus(); break;
    case 1: Show(); ReleaseFocus(); break;
    case 2: Show(); CaptureFocus(); break;
    }
  }
References PluginBase::CaptureFocus(), PluginBase::Hide(), PluginBase::ReleaseFocus(), and PluginBase::Show().
UpdateCommandModifiers()
void UpdateCommandModifiers (DayZPlayer pPlayer) protected
Definition at line 638 of file PluginDayzPlayerDebug.c.
  {
    Actions_UpdateGlobals(pPlayer);
    // int nMods = pPlayer.GetCommandModifierCount();
    // Print("Number of modifiers");
    // Print(nMods);
    /*
      for (int i = 0; i < nMods; i ++)
      {
      // int a = pPlayer.GetCommandModifierId(i);
      if (pPlayer.GetCommandModifierId(i) == DayZPlayerConstants.COMMANDID_MOD_ACTION)
      {
      }
      // Print(a);
      }
    */
    HumanCommandActionCallback clbk = pPlayer.GetCommandModifier_Action();
    if (clbk)
      Print(clbk);
    ;
  }
References Actions_UpdateGlobals(), and Print().
Referenced by Tick().
UpdateItemAccessor()
void UpdateItemAccessor (DayZPlayer pPlayer) protected
Definition at line 832 of file PluginDayzPlayerDebug.c.
  {
    m_ItemAccClass.SetText(pPlayer.DebugGetItemClass());
    m_ItemAccSClass.SetText(pPlayer.DebugGetItemSuperClass());
    m_ItemAccInst.SetText(pPlayer.DebugGetItemAnimInstance());
  }
References m_ItemAccClass, m_ItemAccInst, and m_ItemAccSClass.
Referenced by Tick().
UpdatePlayerStatus()
void UpdatePlayerStatus (DayZPlayer pPlayer) protected
Definition at line 553 of file PluginDayzPlayerDebug.c.
  {
    ref HumanMovementState state = new HumanMovementState();
    pPlayer.GetMovementState(state);
    string a = "Cmd:";
    if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_MOVE)
    {
      a += "MOVE:";
      a += " st:" + state.m_iStanceIdx.ToString() + ", mv:" + state.m_iMovement.ToString();
    }
    else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_ACTION)
    {
      a += "FB ACTION:";
      a += " st:" + state.m_iStanceIdx.ToString();
    }
    else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_MELEE)
    {
      a += "MELEE:";
      a += " st:" + state.m_iStanceIdx.ToString();
    }
    else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_MELEE2)
    {
      a += "MELEE2:";
      a += " st:" + state.m_iStanceIdx.ToString();
    }
    else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_FALL)
    {
      a += "FALL:";
      a += " st:" + state.m_iStanceIdx.ToString();
    }
    else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_DEATH)
    {
      a += "now DEAD:";
      a += " st:" + state.m_iStanceIdx.ToString();
    }
    else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_LADDER)
    {
      a += "LADDER:";
      a += " st:" + state.m_iStanceIdx.ToString();
    }
    else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_UNCONSCIOUS)
    {
      a += "Unconscious:";
      a += " st:" + state.m_iStanceIdx.ToString();
    }
    else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_SWIM)
    {
      a += "Swimming:";
      a += " st:" + state.m_iStanceIdx.ToString();
    }
    else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_CLIMB)
    {
      a += "Climbing:";
      a += " st:" + state.m_iStanceIdx.ToString();
    }
    else
      a += "UNKNOWN";
    m_PlayerStatusV.SetText(a);
  }
References m_PlayerStatusV.
Referenced by Tick().
~PluginDayzPlayerDebug()
void ~PluginDayzPlayerDebug () protected
Definition at line 300 of file PluginDayzPlayerDebug.c.
  {
    ReleaseFocus();
    PlayerSyncDelete();
#ifndef NO_GUI
    m_Weapons = NULL;
    m_Controls = NULL;
    m_OtherCmds = NULL;
    DestroyModuleWidgets();
#endif
  }
References PluginBase::DestroyModuleWidgets(), m_Controls, m_OtherCmds, m_Weapons, PlayerSyncDelete(), and PluginBase::ReleaseFocus().
Variable Documentation
m_ActionEventV
TextWidget m_ActionEventV protected
Definition at line 222 of file PluginDayzPlayerDebug.c.
Referenced by Actions_Start(), and CreateModuleWidgets().
m_ActionsCancel
ButtonWidget m_ActionsCancel protected
Definition at line 218 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_ActionsEnd
ButtonWidget m_ActionsEnd protected
Definition at line 216 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_ActionsFilter
EditBoxWidget m_ActionsFilter protected
Definition at line 225 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets(), DisplayActions(), PluginBase::OnContinouousAction(), PluginBase::PluginAdminLog(), and PluginBase::TotemFlagChange().
m_ActionsFinish
ButtonWidget m_ActionsFinish protected
Definition at line 217 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_ActionsGlobalStatus
TextWidget m_ActionsGlobalStatus protected
Definition at line 223 of file PluginDayzPlayerDebug.c.
Referenced by Actions_UpdateGlobals(), and CreateModuleWidgets().
m_ActionsOTA
ButtonWidget m_ActionsOTA protected
Definition at line 219 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_ActionsOTL
ButtonWidget m_ActionsOTL protected
Definition at line 220 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_ActionsSelector
TextListboxWidget m_ActionsSelector protected
Definition at line 214 of file PluginDayzPlayerDebug.c.
Referenced by Actions_Start(), CreateModuleWidgets(), and DisplayActions().
m_ActionsStart
ButtonWidget m_ActionsStart protected
Definition at line 215 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_ActionStateV
TextWidget m_ActionStateV protected
Definition at line 221 of file PluginDayzPlayerDebug.c.
Referenced by Actions_Start(), and CreateModuleWidgets().
m_ActionTypeAll
ButtonWidget m_ActionTypeAll protected
Definition at line 235 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_ActionTypeFLA
ButtonWidget m_ActionTypeFLA protected
Definition at line 238 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_ActionTypeFLG
ButtonWidget m_ActionTypeFLG protected
Definition at line 242 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_ActionTypeFOA
ButtonWidget m_ActionTypeFOA protected
Definition at line 239 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_ActionTypeFOG
ButtonWidget m_ActionTypeFOG protected
Definition at line 243 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_ActionTypeLA
ButtonWidget m_ActionTypeLA protected
Definition at line 236 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_ActionTypeLG
ButtonWidget m_ActionTypeLG protected
Definition at line 240 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_ActionTypeOA
ButtonWidget m_ActionTypeOA protected
Definition at line 237 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_ActionTypeOG
ButtonWidget m_ActionTypeOG protected
Definition at line 241 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_AnimationList
ref array<ref PluginDayzPlayerDebugUserData> m_AnimationList = new array<ref PluginDayzPlayerDebugUserData>() protected
Definition at line 192 of file PluginDayzPlayerDebug.c.
Referenced by DisplayActions(), and RegisterAnimation().
m_AnimationListMappings
ref map<string, ref PluginDayzPlayerDebugUserData> m_AnimationListMappings = new map<string, ref PluginDayzPlayerDebugUserData>() protected
Definition at line 193 of file PluginDayzPlayerDebug.c.
Referenced by DisplayActions(), and RegisterAnimation().
m_bIsFullBody
bool m_bIsFullBody protected
Definition at line 96 of file PluginDayzPlayerDebug.c.
m_Card0
Widget m_Card0 protected
Definition at line 201 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets(), and ShowCard().
m_Card0Button
ButtonWidget m_Card0Button protected
Definition at line 206 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_Card1
Widget m_Card1 protected
Definition at line 202 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets(), PluginDayzPlayerDebug(), and ShowCard().
m_Card1Button
ButtonWidget m_Card1Button protected
Definition at line 207 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_Card2
Widget m_Card2 protected
Definition at line 203 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets(), PluginDayzPlayerDebug(), and ShowCard().
m_Card2Button
ButtonWidget m_Card2Button protected
Definition at line 208 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_Card3
Widget m_Card3 protected
Definition at line 204 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets(), PluginDayzPlayerDebug(), and ShowCard().
m_Card3Button
ButtonWidget m_Card3Button protected
Definition at line 209 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_Card4
Widget m_Card4 protected
Definition at line 205 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets(), and ShowCard().
m_Card4Button
ButtonWidget m_Card4Button protected
Definition at line 210 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_Category
int m_Category protected
Definition at line 98 of file PluginDayzPlayerDebug.c.
m_CH_ActionCancel
bool m_CH_ActionCancel = false protected
Definition at line 259 of file PluginDayzPlayerDebug.c.
Referenced by CommandHandler().
m_CH_ActionCommand
int m_CH_ActionCommand = -1000 protected
Definition at line 258 of file PluginDayzPlayerDebug.c.
Referenced by CommandHandler().
m_CH_ActionStart
bool m_CH_ActionStart = false protected
Definition at line 257 of file PluginDayzPlayerDebug.c.
Referenced by CommandHandler().
m_ClearEventsButton
ButtonWidget m_ClearEventsButton protected
Definition at line 246 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_Controls
ref PluginDayzPlayerDebug_Ctrl m_Controls protected
Definition at line 263 of file PluginDayzPlayerDebug.c.
Referenced by CommandHandler(), UIScriptedMenu::Init(), UIScriptedMenu::OnClick(), PluginDayzPlayerDebug(), and ~PluginDayzPlayerDebug().
m_CurrentMode
int m_CurrentMode = 0 protected
Definition at line 375 of file PluginDayzPlayerDebug.c.
Referenced by PPERequester_GameplayBase::SetNVMode(), PPERequester_GameplayBase::SetUndergroundExposureCoef(), PluginBase::ToggleDebugWindowEvent(), and ToggleDebugWindowEvent().
m_CurrentType
int m_CurrentType protected
Definition at line 254 of file PluginDayzPlayerDebug.c.
Referenced by DisplayActions().
m_EventsHistory
TextListboxWidget m_EventsHistory protected
Definition at line 248 of file PluginDayzPlayerDebug.c.
Referenced by Actions_Start(), CreateModuleWidgets(), and HumanCommandActionCallback::OnAnimationEvent().
m_HasFocus
bool m_HasFocus = false protected
Definition at line 197 of file PluginDayzPlayerDebug.c.
Referenced by PluginBase::CaptureFocus(), CaptureFocus(), PluginBase::ReleaseFocus(), ReleaseFocus(), ToggleDebugWindowEventOld(), and ToggleDebugWindowEventP().
m_HasServerWalk
bool m_HasServerWalk = false protected
Definition at line 198 of file PluginDayzPlayerDebug.c.
m_IsActive
bool m_IsActive = false protected
Definition at line 196 of file PluginDayzPlayerDebug.c.
m_iStanceMask
int m_iStanceMask protected
Definition at line 97 of file PluginDayzPlayerDebug.c.
m_ItemAccClass
TextWidget m_ItemAccClass protected
Definition at line 231 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets(), and UpdateItemAccessor().
m_ItemAccInst
TextWidget m_ItemAccInst protected
Definition at line 233 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets(), and UpdateItemAccessor().
m_ItemAccSClass
TextWidget m_ItemAccSClass protected
Definition at line 232 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets(), and UpdateItemAccessor().
m_iUserData
int m_iUserData protected
Definition at line 95 of file PluginDayzPlayerDebug.c.
m_MainWnd
Widget m_MainWnd protected
Definition at line 200 of file PluginDayzPlayerDebug.c.
Referenced by PluginBase::CreateModuleWidgets(), CreateModuleWidgets(), PluginBase::ResetValues(), PluginBase::ShowWidgets(), and ShowWidgets().
m_Name
string m_Name protected
Definition at line 99 of file PluginDayzPlayerDebug.c.
m_OtherCmds
ref PluginDayzPlayerDebug_OtherCmds m_OtherCmds protected
Definition at line 264 of file PluginDayzPlayerDebug.c.
Referenced by CommandHandler(), PluginDayzPlayerDebug(), and ~PluginDayzPlayerDebug().
m_PlayerServerWalk
ButtonWidget m_PlayerServerWalk protected
Definition at line 229 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_PlayerStatusV
EditBoxWidget m_PlayerStatusV protected
Definition at line 213 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets(), and UpdatePlayerStatus().
m_PlayerSyncCreateShadow
ButtonWidget m_PlayerSyncCreateShadow protected
Definition at line 227 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_PlayerSyncDelete
ButtonWidget m_PlayerSyncDelete protected
Definition at line 228 of file PluginDayzPlayerDebug.c.
Referenced by CreateModuleWidgets().
m_pPlayerShadow
Entity m_pPlayerShadow protected
Definition at line 252 of file PluginDayzPlayerDebug.c.
Referenced by PlayerSyncCreate(), and PlayerSyncDelete().
m_pPluginPlayerDebug
PluginDayzPlayerDebug m_pPluginPlayerDebug
Definition at line 83 of file PluginDayzPlayerDebug.c.
Referenced by OnChange(), and PluginDayzPlayerDebugUserData().
m_pUIHandler
ref PluginDayzPlayerDebugUIHandler m_pUIHandler protected
Definition at line 250 of file PluginDayzPlayerDebug.c.
Referenced by PluginBase::CreateModuleWidgets(), and CreateModuleWidgets().
m_TickTimer
ref Timer m_TickTimer private
Definition at line 190 of file PluginDayzPlayerDebug.c.
m_TypeNameMappings
ref map<int, string> m_TypeNameMappings = new map<int, string>() protected
Definition at line 194 of file PluginDayzPlayerDebug.c.
Referenced by CreateTypeNameMapping(), and DisplayActions().
m_Weapons
ref PluginDayzPlayerDebug_Weapons m_Weapons protected
Definition at line 262 of file PluginDayzPlayerDebug.c.
Referenced by CommandHandler(), IsWeaponChange(), PluginDayzPlayerDebug(), Tick(), and ~PluginDayzPlayerDebug().
TYPE_ALL
const int TYPE_ALL = -1 private
Definition at line 187 of file PluginDayzPlayerDebug.c.
TYPE_FB_GESTURE_LOOPING
const int TYPE_FB_GESTURE_LOOPING = 6 private
Definition at line 183 of file PluginDayzPlayerDebug.c.
Referenced by CreateTypeNameMapping(), and RegisterAnimations().
TYPE_FB_GESTURE_ONETIME
const int TYPE_FB_GESTURE_ONETIME = 7 private
Definition at line 184 of file PluginDayzPlayerDebug.c.
Referenced by CreateTypeNameMapping(), and RegisterAnimations().
TYPE_FB_LOOPING
const int TYPE_FB_LOOPING = 2 private
Definition at line 178 of file PluginDayzPlayerDebug.c.
Referenced by CreateTypeNameMapping(), and RegisterAnimations().
TYPE_FB_ONETIME
const int TYPE_FB_ONETIME = 3 private
Definition at line 179 of file PluginDayzPlayerDebug.c.
Referenced by CreateTypeNameMapping(), and RegisterAnimations().
TYPE_FB_SUICIDE_LOOPING
const int TYPE_FB_SUICIDE_LOOPING = TYPE_FB_GESTURE_LOOPING private
Definition at line 185 of file PluginDayzPlayerDebug.c.
Referenced by RegisterAnimations().
TYPE_MOD_GESTURE_LOOPING
const int TYPE_MOD_GESTURE_LOOPING = 4 private
Definition at line 181 of file PluginDayzPlayerDebug.c.
Referenced by CreateTypeNameMapping(), and RegisterAnimations().
TYPE_MOD_GESTURE_ONETIME
const int TYPE_MOD_GESTURE_ONETIME = 5 private
Definition at line 182 of file PluginDayzPlayerDebug.c.
Referenced by CreateTypeNameMapping(), and RegisterAnimations().
TYPE_MOD_LOOPING
class PluginDayzPlayerActionCallback extends HumanCommandActionCallback TYPE_MOD_LOOPING = 0
Referenced by CreateTypeNameMapping(), and RegisterAnimations().
TYPE_MOD_ONETIME
const int TYPE_MOD_ONETIME = 1 private
Definition at line 177 of file PluginDayzPlayerDebug.c.
Referenced by CreateTypeNameMapping(), and RegisterAnimations().