DayZ: TimerBase Class Reference
TimerBase Class Reference
Tools
Simple class for fading Widgets.
Protected Member Functions
void Timer (int category=CALL_CATEGORY_SYSTEM)
void Run (float duration, Managed obj, string fn_name, Param params=NULL, bool loop=false)
Starts timer.
void OnTimer ()
override void Stop ()
Protected Attributes
Managed m_target
string m_function
ref Param m_params
Private Member Functions
void WidgetFadeTimer ()
void FadeIn (Widget w, float time, bool continue_=false)
Make "fade in" effect on Widget (transparency goes from 0.0 to 1.0)
void FadeOut (Widget w, float time, bool continue_=false)
Make "fade out" effect on Widget (transparency goes from 1.0 to 0.0)
void OnTimer ()
void OnUpdate ()
Private Attributes
Widget m_widget
bool m_fadeIn
float m_alpha
Detailed Description
Simple class for fading Widgets.
Timer class. Use when you want call function after some time, or repeatedly in time intervals. Call is not executed after the Timer object is deleted.
usage:
class MyObject
{
ref Timer myTimer1;
ref Timer myTimer2;
ref Timer myTimer3;
void MyObject()
{
  myTimer1 = new Timer();
  myTimer1.Run(10, this, "Refresh"); // calls "Refresh" on "this" after 10 seconds
  myTimer2 = new Timer();
  myTimer2.Run(10, this, "Refresh", NULL, true); // calls "Refresh" on "this" every 10 seconds, until Pause or Stop is called
  myTimer3 = new Timer();
  myTimer3.Run(15, this, "Show", new Param1<bool>(false)); // calls "Show" on "this" with one bool argument after 15 seconds
}
void Refresh();
void Show(bool visible);
}
Definition at line 405 of file tools.c.
Member Function Documentation
FadeIn()
void TimerBase::FadeIn (Widget w, float time, bool continue_ = false) inline private
Make "fade in" effect on Widget (transparency goes from 0.0 to 1.0)
Parameters
w widget which will be faded
time duration of effect
continue - if True continue from current alpha value, otherwise always begin from 0.0 alpha
Definition at line 423 of file tools.c.
  {
    m_alpha = w.GetAlpha();
    if (continue_ && m_alpha > 0.95)
    {
      w.SetAlpha(1.0);
      w.Show(true);
      return;
    }
    m_widget = w;
    m_fadeIn = true;
    OnStart(time, false);
    if (m_widget)
    {
      m_alpha = m_widget.GetAlpha();
      m_widget.SetAlpha(0);
      m_widget.Show(true);
    }
    if (continue_)
      m_time = m_alpha * time;
  }
References m_time, and OnStart().
FadeOut()
void TimerBase::FadeOut (Widget w, float time, bool continue_ = false) inline private
Make "fade out" effect on Widget (transparency goes from 1.0 to 0.0)
Parameters
w widget which will be faded
time duration of effect
continue - if True continue from current alpha value, otherwise always begin from 1.0 alpha
Definition at line 456 of file tools.c.
  {
    m_alpha = w.GetAlpha();
    if (continue_ && m_alpha < 0.05)
    {
      w.SetAlpha(0);
      w.Show(false);
      return;
    }
    m_widget = w;
    m_fadeIn = false;
    OnStart(time, false);
    if (m_widget && !continue_)
    {
      m_alpha = 1.0;
      m_widget.SetAlpha(m_alpha);
      m_widget.Show(true);
    }
    if (continue_)
      m_time = (1.0 - m_alpha) * time;
  }
References m_alpha, m_time, and OnStart().
OnTimer() [1/2]
void TimerBase::OnTimer () inline private
Definition at line 483 of file tools.c.
  {
    if (m_widget)
    {
      if (m_fadeIn)
        m_widget.SetAlpha(1);
      else
      {
        m_widget.SetAlpha(0);
        m_widget.Show(false);
      }
    }
  }
Referenced by Tick().
OnTimer() [2/2]
void TimerBase::OnTimer () inline protected
Definition at line 574 of file tools.c.
  {
    if (m_params)
    {
      GetGame().GameScript.CallFunctionParams(m_target, m_function, NULL, m_params);
      m_params = NULL;
    }
    else
      GetGame().GameScript.CallFunction(m_target, m_function, NULL, 0);
  }
References GetGame().
OnUpdate()
void TimerBase::OnUpdate () inline private
Definition at line 497 of file tools.c.
  {
    float timeDiff = m_time / m_duration;
    float progress;
    if (m_widget)
    {
      if (m_fadeIn)
        progress = timeDiff;
      else
      {
        progress = Math.Lerp(m_alpha, 0, timeDiff);
        progress = Math.Clamp(progress, 0, 1);
      }
      m_widget.SetAlpha(progress);
    }
  }
References Math::Clamp(), Math::Lerp(), m_duration, and m_time.
Referenced by Tick().
Run()
void TimerBase::Run (float duration, Managed obj, string fn_name, Param params = NULL, bool loop = false) inline protected
Starts timer.
Parameters
duration function is executed after this time (in seconds).
obj target object on which function will be executed
fn_name name of function (on object "obj") which will be executed
params function arguments see Param for usage, default NULL (no arguments)
loop when true, timer is looped endlessly and function is executed after every loop.
Definition at line 565 of file tools.c.
  {
    m_target = obj;
    m_function = fn_name;
    m_params = params;
    OnStart(duration, loop);
  }
References OnStart().
Stop()
override void TimerBase::Stop () inline protected
Definition at line 585 of file tools.c.
  {
    super.Stop();
    m_params = NULL;
  }
Timer()
void TimerBase::Timer (int category = CALL_CATEGORY_SYSTEM) inline protected
Definition at line 552 of file tools.c.
  {
    OnInit(category);
  }
References OnInit().
WidgetFadeTimer()
void TimerBase::WidgetFadeTimer () inline private
Definition at line 411 of file tools.c.
  {
    OnInit(CALL_CATEGORY_GUI);
    m_fadeIn = true;
  }
References CALL_CATEGORY_GUI, and OnInit().
Member Data Documentation
m_alpha
float TimerBase::m_alpha private
Definition at line 409 of file tools.c.
Referenced by FadeOut().
m_fadeIn
bool TimerBase::m_fadeIn private
Definition at line 408 of file tools.c.
m_function
string TimerBase::m_function protected
Definition at line 549 of file tools.c.
m_params
ref Param TimerBase::m_params protected
Definition at line 550 of file tools.c.
m_target
Managed TimerBase::m_target protected
Definition at line 548 of file tools.c.
m_widget
Widget TimerBase::m_widget private
Definition at line 407 of file tools.c.
The documentation for this class was generated from the following file:
scripts/3_Game/tools/tools.c