DayZ: PlayerSoundManagerBase Class Reference
PlayerSoundManagerBase Class Reference
Private Member Functions
override void Init ()
override void Update ()
Detailed Description
Definition at line 56 of file PlayerSoundManager.c.
Member Function Documentation
Init()
override void PlayerSoundManagerBase::Init () inline private
Definition at line 61 of file PlayerSoundManager.c.
  {
    RegisterHandler(new StaminaSoundHandlerServer(m_Player));
    RegisterHandler(new HungerSoundHandlerServer(m_Player));
    RegisterHandler(new ThirstSoundHandlerServer(m_Player));
    RegisterHandler(new InjurySoundHandlerServer(m_Player));
  }
References m_Player, and RegisterHandler().
Referenced by PlayerSoundManagerBase().
Update()
override void PlayerSoundManagerBase::Update () inline private
Definition at line 69 of file PlayerSoundManager.c.
  {
    if (m_Player.IsUnconscious())
      return;
    for (int i = 0; i < (MAX_HANDLERS_COUNT - 1); i++)
      m_Handlers[i].Update();
  }
References m_Handlers, m_Player, MAX_HANDLERS_COUNT, and Update().
Referenced by Update().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/SoundHandlers/PlayerSoundManager.c