DayZ: scripts/4_World/Plugins/PluginManager.c File Reference
PluginManager.c File Reference
Classes
class PluginManager
Functions
PluginManager GetPluginManager ()
Returns registred plugin by class type, better is to use global funtion GetPlugin(typename plugin_type)
void PluginManagerInit ()
void PluginManagerDelete ()
bool IsPluginManagerExists ()
PluginBase GetPlugin (typename plugin_type)
bool IsModuleExist (typename plugin_type)
Variables
class PluginManager g_Plugins
Function Documentation
GetPlugin()
PluginBase GetPlugin (typename plugin_type)
Definition at line 300 of file PluginManager.c.
{
  PluginBase plugin = null;
  if (IsPluginManagerExists())
  {
    plugin = GetPluginManager().GetPluginByType(plugin_type);
    if (plugin == null)
    {
#ifdef DIAG_DEVELOPER
      if (IsPluginManagerExists())
      {
        PrintString("Module " + plugin_type.ToString() + " is not Registred in PluginManager.c!");
        DumpStack();
      }
#endif
    }
  }
  return plugin;
}
References DumpStack(), PluginManager::GetPluginByType(), GetPluginManager(), IsPluginManagerExists(), and PrintString().
Referenced by ActionCondition(), ActionRepairShelter::ActionCondition(), ActionRepairTent::ActionCondition(), ActionRepairTentPart::ActionCondition(), ActionContinuousBase::ActionContinuousBase(), ActionBandageBase::ApplyBandage(), ApplyBandage(), ActionEatMeat::ApplyModifiers(), RecipeBase::CanDo(), InventoryItem::CanRepair(), ManBase::Consume(), ActionCollectBloodTargetLambda::CopyOldPropertiesToNew(), Debug(), MessageReceiverBase::DisplayElementBase(), RecipeBase::Do(), ManBase::EEHitBy(), EmoteManager(), Liquid::FillContainerEnviro(), PluginBase::GetConfig(), ManBase::GetDebugActions(), PluginBase::GetInstance(), PluginConfigHandler::GetInstance(), GetInstance(), Attachments::GetRecipeCount(), HandsContainer::GetRecipeCount(), PlayerContainer::GetRecipeCount(), ItemManager::GetRecipeCount(), Container::GetRecipeCount(), InventoryItem::GetRecipesActions(), UIPopupScript::GetSceneEditor(), ActionWorldCraft::GetSoundCategory(), ActionWorldCraft::GetText(), HideCrosshairVisibility(), HudDebugWinCharModifiers(), HudDebugWinBase::HudDebugWinTemperature(), InventoryItem::IDToName(), BleedingCheckMdfr::Init(), ManBase::Init(), UIScriptedMenu::Init(), ScriptConsoleConfigTab::Init(), SceneObject::Init(), ManBase::InitEditor(), Inventory(), IsModuleExist(), InventoryItem::ItemBase(), ScriptConsoleGeneralTab::LateInit(), ScriptConsoleItemsTab::ListItemRelatedActions(), BaseBuildingBase::LogAnimateFlag(), MessageReceiverBase::MessageReceiverBase(), MissionBaseWorld::MissionBase(), ModifierBase(), InventoryItem::NameToID(), NotifierBase::NotifierBase(), InventoryItem::OnAction(), ActionWorldCraft::OnActionInfoUpdate(), SymptomBase::OnAnimationFinish(), SymptomBase::OnAnimationStart(), ScriptConsoleGeneralTab::OnChange(), UIPopupScript::OnClick(), UIPropertyAttachment::OnClick(), ScriptConsoleGeneralTab::OnClick(), ActionConsume::OnEndServer(), ActionGiveBloodSelf::OnEndServer(), ActionGiveBloodTarget::OnEndServer(), ActionInteractLoopBase::OnEndServer(), OnEndServer(), ActionWashHandsItem::OnEndServer(), MissionBase::OnEvent(), OnFinishProgressServer(), ActionRepairPart::OnFinishProgressServer(), ActionRepairShelter::OnFinishProgressServer(), ActionRepairTent::OnFinishProgressServer(), ActionWashHandsItemContinuous::OnFinishProgressServer(), ActionWorldCraft::OnFinishProgressServer(), ActionTestBloodSelf::OnFinishProgressServer(), ActionTestBloodTarget::OnFinishProgressServer(), OnInit(), PluginBase::OnInit(), PluginBase::OnKeyPress(), PluginBase::OnMouse(), UIPopupScript::OnOpen(), BaseBuildingBase::OnPartBuiltServer(), ManBase::OnRPC(), PluginBase::OnRPCPluginDayzCreatureDebug(), PluginBase::OnRPCSyncSceneObject(), ManBase::OnSelectPlayer(), DeveloperFreeCamera::OnSetFreeCameraEvent(), ActionTestBloodTarget::OnStartServer(), ItemBase::PlantBase(), ItemBase::PlantSeed(), RefreshByLocalProfile(), RefreshCrosshairVisibility(), InventoryItem::Repair(), ActionRepairTent::RepairDamageTransfer(), ManBase::ResetPlayer(), PluginConfigHandler::SceneDataSave(), UIScriptedMenu::SceneEditorMenu(), UIScriptedMenu::ScriptConsole(), ScriptConsoleEnfScriptTab::ScriptConsoleEnfScriptTab(), ScriptConsoleGeneralTab::ScriptConsoleGeneralTab(), ScriptConsoleItemsTab::ScriptConsoleItemsTab(), ScriptConsoleTabBase::ScriptConsoleTabBase(), Dispatcher::SendLogAtClient(), SetAgents(), HudDebugWinBase::SetContentValues(), PluginBase::SetDeveloperItemClientEx(), ManBase::SetHairLevelToHide(), CAContinuousCraft::Setup(), SetUpdate(), HudDebugWinBase::SetUpdate(), HudDebugWinBase::SetupValues(), HudDebugWinBase::SetValues(), MissionBase::ShowHairDebugValues(), ScriptConsoleItemsTab::SpawnPreset(), ManBase::SpreadAgentsEx(), Liquid::Transfer(), AreaExposureMdfr::TransmitAgents(), UIPopupScript::UIPopupScriptEditorSettings(), UIPopupScript::UIPopupScriptInitScript(), UIPopupScript::UIPopupScriptPositionManager(), HudDebugWinBase::Update(), MissionBase::UpdatePlayersStats(), UIPopupScript::UpdateSceneList(), HudDebugWinBase::UpdateValues(), UIScriptedMenu::~ScriptConsole(), and ScriptConsoleGeneralTab::~ScriptConsoleGeneralTab().
GetPluginManager()
PluginManager GetPluginManager ()
Returns registred plugin by class type, better is to use global funtion GetPlugin(typename plugin_type)
Parameters
module_tpye typename class type of plugin
Returns
PluginBase
PluginRepairing plugin = GetPluginManager().GetPluginByType(PluginRepairing);
Definition at line 260 of file PluginManager.c.
{
  /*
    if ( g_Plugins == NULL )
    {
    PluginManagerInit();
    }
  */
  return g_Plugins;
}
References g_Plugins.
Referenced by DayZInfected::CommandHandlerDebug(), DayZPlayer::CommandHandlerDebug(), and GetPlugin().
IsModuleExist()
bool IsModuleExist (typename plugin_type)
Definition at line 323 of file PluginManager.c.
{
  if (IsPluginManagerExists())
    return (GetPlugin(plugin_type) != NULL);
  return false;
}
References GetPlugin(), and IsPluginManagerExists().
Referenced by UIScriptedMenu::~SceneEditorMenu().
IsPluginManagerExists()
bool IsPluginManagerExists ()
Definition at line 292 of file PluginManager.c.
{
  if (g_Plugins != null)
    return true;
  return false;
}
References g_Plugins.
Referenced by GetPlugin(), PlayerAgentPool::GrowAgents(), IsModuleExist(), MessageReceiverBase::Unsubscribe(), and MessageReceiverBase::UnsubscribeAll().
PluginManagerDelete()
void PluginManagerDelete ()
Definition at line 283 of file PluginManager.c.
{
  if (g_Plugins)
  {
    delete g_Plugins;
    g_Plugins = NULL;
  }
}
References g_Plugins.
Referenced by MissionBaseWorld::~MissionBase().
PluginManagerInit()
void PluginManagerInit ()
Definition at line 273 of file PluginManager.c.
{
  if (g_Plugins == NULL)
  {
    g_Plugins = new PluginManager;
    g_Plugins.Init();
    g_Plugins.PluginsInit();
  }
}
References g_Plugins.
Referenced by MissionBaseWorld::MissionBase().
Variable Documentation
g_Plugins
class PluginManager g_Plugins
Referenced by GetPluginManager(), IsPluginManagerExists(), PluginManagerDelete(), and PluginManagerInit().