DayZ: ErrorProperties Class Reference
ErrorProperties Class Reference
Class which holds the properties and handling of an error.
Protected Member Functions
void ErrorProperties (string message, string serverMessage)
void HandleError (int errorCode, string additionalInfo="")
string GetClientMessage (string additionalInfo="")
string GetServerMessage (string additionalInfo="")
Protected Attributes
string m_Message
Message which will appear on Client.
string m_ServerMessage
Message which will appear on Server.
Private Attributes
const string EP_HEADER_FORMAT_STRING = "%1 (%2)"
Formating for header (%1 = Header; %2 = ErrorCode)
const string EP_MESSAGE_FORMAT_STRING = "%1\n(%2)"
Formating for message (%1 = Message; %2 = AdditionalInfo)
Detailed Description
Class which holds the properties and handling of an error.
Definition at line 2 of file ErrorProperties.c.
Constructor & Destructor Documentation
ErrorProperties()
void ErrorProperties::ErrorProperties (string message, string serverMessage) inline protected
Definition at line 10 of file ErrorProperties.c.
  {
    m_Message = message;
    m_ServerMessage = serverMessage;
  }
References m_Message, and m_ServerMessage.
Member Function Documentation
GetClientMessage()
string ErrorProperties::GetClientMessage (string additionalInfo = "") inline protected
Definition at line 18 of file ErrorProperties.c.
  {
    if (additionalInfo != "")
      return string.Format(EP_MESSAGE_FORMAT_STRING, m_Message, additionalInfo);
    else
      return m_Message;
  }
References EP_MESSAGE_FORMAT_STRING, string::Format(), and m_Message.
GetServerMessage()
string ErrorProperties::GetServerMessage (string additionalInfo = "") inline protected
Definition at line 26 of file ErrorProperties.c.
  {
    if (additionalInfo != "")
      return string.Format(EP_MESSAGE_FORMAT_STRING, m_ServerMessage, additionalInfo);
    else
      return m_ServerMessage;
  }
References EP_MESSAGE_FORMAT_STRING, string::Format(), and m_ServerMessage.
HandleError()
void ErrorProperties::HandleError (int errorCode, string additionalInfo = "") inline protected
Definition at line 16 of file ErrorProperties.c.
{}
Member Data Documentation
EP_HEADER_FORMAT_STRING
const string ErrorProperties::EP_HEADER_FORMAT_STRING = "%1 (%2)" private
Formating for header (%1 = Header; %2 = ErrorCode)
Definition at line 4 of file ErrorProperties.c.
EP_MESSAGE_FORMAT_STRING
const string ErrorProperties::EP_MESSAGE_FORMAT_STRING = "%1\n(%2)" private
Formating for message (%1 = Message; %2 = AdditionalInfo)
Definition at line 5 of file ErrorProperties.c.
Referenced by GetClientMessage(), and GetServerMessage().
m_Message
string ErrorProperties::m_Message protected
Message which will appear on Client.
Definition at line 7 of file ErrorProperties.c.
Referenced by ErrorProperties(), GetClientMessage(), GetHeader(), and HandleError().
m_ServerMessage
string ErrorProperties::m_ServerMessage protected
Message which will appear on Server.
Definition at line 8 of file ErrorProperties.c.
Referenced by ErrorProperties(), and GetServerMessage().
The documentation for this class was generated from the following file:
scripts/3_Game/Global/ErrorModuleHandler/ErrorProperties.c