DayZ: scripts/3_Game/Client/Notifications/NotificationSystem.c File Reference
NotificationSystem.c File Reference
Classes
class NotificationSystem
Enumerations
enum NotificationType {
FRIEND_CONNECTED , INVITE_FAIL_SAME_SERVER , JOIN_FAIL_GET_SESSION , CONNECT_FAIL_GENERIC ,
DISCONNECTED , GENERIC_ERROR , NOTIFICATIONS_END
}
DEPRECATED (moved into NotificationSystem)
Functions
void NotificationRuntimeData (float time, NotificationData data, string detail_text)
float GetTime ()
float GetRemainingTime ()
string GetIcon ()
string GetTitleText ()
string GetDetailText ()
void UpdateRemainingTime (float updateInterval)
void SetTime (float time)
DEPRECATED.
Variables
static const float NOTIFICATION_FADE_TIME = 3.0
enum NotificationType m_StaticData
float m_NotificationTime
float m_TimeRemaining
string m_DetailText
Enumeration Type Documentation
NotificationType
enum NotificationType
DEPRECATED (moved into NotificationSystem)
Enumerator
FRIEND_CONNECTED
INVITE_FAIL_SAME_SERVER
JOIN_FAIL_GET_SESSION
CONNECT_FAIL_GENERIC
DISCONNECTED
GENERIC_ERROR
NOTIFICATIONS_END
Definition at line 3 of file NotificationSystem.c.
{
  FRIEND_CONNECTED,
  INVITE_FAIL_SAME_SERVER,
  JOIN_FAIL_GET_SESSION,
  CONNECT_FAIL_GENERIC,
  DISCONNECTED,
  GENERIC_ERROR,
  //Please add types before this item
  NOTIFICATIONS_END
}
Function Documentation
GetDetailText()
string GetDetailText ()
Definition at line 55 of file NotificationSystem.c.
  {
    return m_DetailText;
  }
References m_DetailText.
GetIcon()
string GetIcon ()
Definition at line 45 of file NotificationSystem.c.
  {
    return m_StaticData.m_Icon;
  }
References m_StaticData.
Referenced by Container::GetFocusedIcon(), Container::GetIcon(), and Container::UpdateSelection().
GetRemainingTime()
float GetRemainingTime ()
Definition at line 40 of file NotificationSystem.c.
  {
    return m_TimeRemaining;
  }
References m_TimeRemaining.
GetTime()
float GetTime ()
Definition at line 35 of file NotificationSystem.c.
  {
    return m_NotificationTime;
  }
References m_NotificationTime.
Referenced by ShockDamageMdfr::ActivateCondition(), AttachBleedingToZonesByHeight(), HumanCommandActionCallback::CancelCondition(), CheckContactCache(), PlayerStatBase::CreateRecord(), MissionBase::InsertCorpse(), ServerBrowserTab::LeftHold(), MissionBase::OnClientDisconnectedEvent(), OnScheduledTick(), GameInventory::OnServerInventoryCommandStatic(), ShockMdfr::OnTick(), UIPopupScript::OnUpdate(), ServerBrowserTabConsolePages::PressX(), ServerBrowserTab::PressX(), ProcessSound(), InjurySoundHandlerBase::ProcessSound(), Randomize(), ServerBrowserTab::RightHold(), InventoryInputUserData::SendInputUserDataHandEvent(), InventoryInputUserData::SendInputUserDataMove(), InventoryInputUserData::SendInputUserDataSwap(), StaminaSoundHandlerBase::Update(), MissionBase::UpdateLogoutPlayers(), and ValidateSyncMove().
GetTitleText()
string GetTitleText ()
Definition at line 50 of file NotificationSystem.c.
  {
    return m_StaticData.m_TitleText;
  }
References m_StaticData.
NotificationRuntimeData()
void NotificationRuntimeData (float time, NotificationData data, string detail_text)
Definition at line 23 of file NotificationSystem.c.
  {
    m_NotificationTime = time;
    m_TimeRemaining = time;
    m_StaticData = data;
    if (detail_text != "")
      m_DetailText = detail_text;
    else
      m_DetailText = m_StaticData.m_DescriptionText;
  }
References m_DetailText, m_NotificationTime, m_StaticData, and m_TimeRemaining.
Referenced by NotificationSystem::AddNotification(), NotificationSystem::AddNotificationExtended(), and NotificationSystem::Update().
SetTime()
void SetTime (float time)
DEPRECATED.
UpdateRemainingTime()
void UpdateRemainingTime (float updateInterval)
Definition at line 60 of file NotificationSystem.c.
  {
    m_TimeRemaining -= updateInterval;
  }
References m_TimeRemaining.
Variable Documentation
m_DetailText
string m_DetailText
Definition at line 21 of file NotificationSystem.c.
Referenced by GetDetailText(), and NotificationRuntimeData().
m_NotificationTime
float m_NotificationTime
Definition at line 19 of file NotificationSystem.c.
Referenced by GetTime(), and NotificationRuntimeData().
m_StaticData
enum NotificationType m_StaticData
Referenced by GetIcon(), GetTitleText(), and NotificationRuntimeData().
m_TimeRemaining
float m_TimeRemaining
Definition at line 20 of file NotificationSystem.c.
Referenced by GetRemainingTime(), NotificationRuntimeData(), and UpdateRemainingTime().
NOTIFICATION_FADE_TIME
const float NOTIFICATION_FADE_TIME = 3.0 static
Definition at line 1 of file NotificationSystem.c.