DayZ: WeaponStableState Class Reference
WeaponStableState Class Reference
represents weapon's stable state (i.e. the basic states that the weapon will spend the most time in)
Private Member Functions
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsDischarged ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
Detailed Description
represents weapon's stable state (i.e. the basic states that the weapon will spend the most time in)
Stable states have associated animation states that they supposed to be in. If they are not, the SetWeaponAnimState is called on the weapon in order to set to required (configured) state
@NOTE: OnExit from stable state, the weapon's animation state (
See also
Weapon_Base::m_weaponAnimState) is set to -1 (unknown) In case of action abort the final stable state is forced to set proper animation state according to configuration (
m_animState)
Definition at line 26 of file Crossbow.c.
Member Function Documentation
GetCurrentStateID() [1/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 30 of file Crossbow.c.
{ return XBStableStateID.CockedEmpty; }
GetCurrentStateID() [2/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 41 of file Crossbow.c.
{ return XBStableStateID.Loaded; }
GetCurrentStateID() [3/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 33 of file SKS.c.
{ return SKSStableStateID.SKS_CLO_BU1; }
GetCurrentStateID() [4/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 44 of file SKS.c.
{ return SKSStableStateID.SKS_OPN_BU0; }
GetCurrentStateID() [5/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 35 of file BoltActionRifleExternalMagazine_Base.c.
{ return BAREMStableStateID.BAREM_CLO_BU1_MA0; }
GetCurrentStateID() [6/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 46 of file BoltActionRifleExternalMagazine_Base.c.
{ return BAREMStableStateID.BAREM_CLO_BU1_MA1; }
GetCurrentStateID() [7/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 57 of file BoltActionRifleExternalMagazine_Base.c.
{ return BAREMStableStateID.BAREM_CLO_BU0_MA1; }
GetCurrentStateID() [8/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 68 of file BoltActionRifleExternalMagazine_Base.c.
{ return BAREMStableStateID.BAREM_CLO_BUF_MA0; }
GetCurrentStateID() [9/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 79 of file BoltActionRifleExternalMagazine_Base.c.
{ return BAREMStableStateID.BAREM_CLO_BUF_MA1; }
GetCurrentStateID() [10/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 33 of file BoltActionRifleInnerMagazine_Base.c.
{ return BARIMStableStateID.LoadedCharged; }
GetCurrentStateID() [11/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 44 of file BoltActionRifleInnerMagazine_Base.c.
{ return BARIMStableStateID.LoadedDischarged; }
GetCurrentStateID() [12/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 40 of file DoubleBarrel_Base.c.
{ return DoubleBarrelStableStateID.LoadedEmpty; }
GetCurrentStateID() [13/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 51 of file DoubleBarrel_Base.c.
{ return DoubleBarrelStableStateID.EmptyLoaded; }
GetCurrentStateID() [14/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 62 of file DoubleBarrel_Base.c.
{ return DoubleBarrelStableStateID.FireoutLoaded; }
GetCurrentStateID() [15/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 73 of file DoubleBarrel_Base.c.
{ return DoubleBarrelStableStateID.FireoutFireout; }
GetCurrentStateID() [16/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 85 of file DoubleBarrel_Base.c.
{ return DoubleBarrelStableStateID.FireoutEmpty; }
GetCurrentStateID() [17/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 97 of file DoubleBarrel_Base.c.
{ return DoubleBarrelStableStateID.EmptyFireout; }
GetCurrentStateID() [18/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 109 of file DoubleBarrel_Base.c.
{ return DoubleBarrelStableStateID.EmptyEmpty; }
GetCurrentStateID() [19/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 31 of file Flaregun.c.
{ return FLAREStableStateID.Fireout; }
GetCurrentStateID() [20/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 43 of file Flaregun.c.
{ return FLAREStableStateID.Loaded; }
GetCurrentStateID() [21/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 43 of file Pistol_Base.c.
{ return PistolStableStateID.CLO_CHG_BU0_MA0; }
GetCurrentStateID() [22/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 54 of file Pistol_Base.c.
{ return PistolStableStateID.CLO_CHG_BU1_MA0; }
GetCurrentStateID() [23/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 77 of file Pistol_Base.c.
{ return PistolStableStateID.OPE_DIS_BU0_MA0; }
GetCurrentStateID() [24/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 90 of file Pistol_Base.c.
{ return PistolStableStateID.CLO_CHG_BU0_MA1; }
GetCurrentStateID() [25/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 101 of file Pistol_Base.c.
{ return PistolStableStateID.CLO_DIS_BU0_MA1; }
GetCurrentStateID() [26/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 124 of file Pistol_Base.c.
{ return PistolStableStateID.CLO_CHG_BU1_MA1; }
GetCurrentStateID() [27/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 135 of file Pistol_Base.c.
{ return PistolStableStateID.OPE_DIS_BU0_MA1; }
GetCurrentStateID() [28/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 33 of file Repeater.c.
{ return RPTStableStateID.LoadedCharged; }
GetCurrentStateID() [29/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 44 of file Repeater.c.
{ return RPTStableStateID.LoadedDischarged; }
GetCurrentStateID() [30/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 33 of file RifleBoltFree_Base.c.
{ return RBFStableStateID.RBF_CLO_BU1_MA0; }
GetCurrentStateID() [31/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 44 of file RifleBoltFree_Base.c.
{ return RBFStableStateID.RBF_CLO_BU1_MA1; }
GetCurrentStateID() [32/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 55 of file RifleBoltFree_Base.c.
{ return RBFStableStateID.RBF_CLO_BU0_MA1; }
GetCurrentStateID() [33/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 36 of file RifleBoltLock_Base.c.
{ return RBLStableStateID.RBL_CLO_BU1_MA0; }
GetCurrentStateID() [34/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 47 of file RifleBoltLock_Base.c.
{ return RBLStableStateID.RBL_CLO_BU1_MA1; }
GetCurrentStateID() [35/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 58 of file RifleBoltLock_Base.c.
{ return RBLStableStateID.RBL_CLO_BU0_MA1; }
GetCurrentStateID() [36/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 69 of file RifleBoltLock_Base.c.
{ return RBLStableStateID.RBL_OPN_BU0_MA1; }
GetCurrentStateID() [37/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 81 of file RifleBoltLock_Base.c.
{ return RBLStableStateID.RBL_OPN_BU0_MA0; }
GetCurrentStateID() [38/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 30 of file RifleSingleShot_Base.c.
{ return RSSStableStateID.Fireout; }
GetCurrentStateID() [39/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 41 of file RifleSingleShot_Base.c.
{ return RSSStableStateID.Loaded; }
GetCurrentStateID() [40/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 30 of file MP133.c.
{ return PumpShotgunStableStateID.Fireout; }
GetCurrentStateID() [41/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 41 of file MP133.c.
{ return PumpShotgunStableStateID.Loaded; }
GetCurrentStateID() [42/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 31 of file SingleShotPistol_Base.c.
{ return SSPStableStateID.Fireout; }
GetCurrentStateID() [43/43]
override int WeaponStableState::GetCurrentStateID () inline private
Definition at line 43 of file SingleShotPistol_Base.c.
{ return SSPStableStateID.Loaded; }
HasBullet() [1/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 31 of file Crossbow.c.
{ return false; }
HasBullet() [2/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 42 of file Crossbow.c.
{ return true; }
HasBullet() [3/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 34 of file SKS.c.
{ return true; }
HasBullet() [4/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 45 of file SKS.c.
{ return false; }
HasBullet() [5/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 36 of file BoltActionRifleExternalMagazine_Base.c.
{ return true; }
HasBullet() [6/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 47 of file BoltActionRifleExternalMagazine_Base.c.
{ return true; }
HasBullet() [7/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 58 of file BoltActionRifleExternalMagazine_Base.c.
{ return false; }
HasBullet() [8/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 69 of file BoltActionRifleExternalMagazine_Base.c.
{ return true; }
HasBullet() [9/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 80 of file BoltActionRifleExternalMagazine_Base.c.
{ return true; }
HasBullet() [10/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 34 of file BoltActionRifleInnerMagazine_Base.c.
{ return true; }
HasBullet() [11/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 45 of file BoltActionRifleInnerMagazine_Base.c.
{ return true; }
HasBullet() [12/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 41 of file DoubleBarrel_Base.c.
{ return true; }
HasBullet() [13/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 52 of file DoubleBarrel_Base.c.
{ return true; }
HasBullet() [14/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 63 of file DoubleBarrel_Base.c.
{ return true; }
HasBullet() [15/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 74 of file DoubleBarrel_Base.c.
{ return true; }
HasBullet() [16/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 86 of file DoubleBarrel_Base.c.
{ return true; }
HasBullet() [17/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 98 of file DoubleBarrel_Base.c.
{ return true; }
HasBullet() [18/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 110 of file DoubleBarrel_Base.c.
{ return false; }
HasBullet() [19/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 32 of file Flaregun.c.
{ return true; }
HasBullet() [20/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 44 of file Flaregun.c.
{ return true; }
HasBullet() [21/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 44 of file Pistol_Base.c.
{ return false; }
HasBullet() [22/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 55 of file Pistol_Base.c.
{ return true; }
HasBullet() [23/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 78 of file Pistol_Base.c.
{ return false; }
HasBullet() [24/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 91 of file Pistol_Base.c.
{ return false; }
HasBullet() [25/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 102 of file Pistol_Base.c.
{ return false; }
HasBullet() [26/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 125 of file Pistol_Base.c.
{ return true; }
HasBullet() [27/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 136 of file Pistol_Base.c.
{ return false; }
HasBullet() [28/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 34 of file Repeater.c.
{ return true; }
HasBullet() [29/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 45 of file Repeater.c.
{ return true; }
HasBullet() [30/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 34 of file RifleBoltFree_Base.c.
{ return true; }
HasBullet() [31/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 45 of file RifleBoltFree_Base.c.
{ return true; }
HasBullet() [32/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 56 of file RifleBoltFree_Base.c.
{ return false; }
HasBullet() [33/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 37 of file RifleBoltLock_Base.c.
{ return true; }
HasBullet() [34/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 48 of file RifleBoltLock_Base.c.
{ return true; }
HasBullet() [35/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 59 of file RifleBoltLock_Base.c.
{ return false; }
HasBullet() [36/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 70 of file RifleBoltLock_Base.c.
{ return false; }
HasBullet() [37/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 82 of file RifleBoltLock_Base.c.
{ return false; }
HasBullet() [38/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 31 of file RifleSingleShot_Base.c.
{ return true; }
HasBullet() [39/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 42 of file RifleSingleShot_Base.c.
{ return true; }
HasBullet() [40/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 31 of file MP133.c.
{ return true; }
HasBullet() [41/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 42 of file MP133.c.
{ return true; }
HasBullet() [42/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 32 of file SingleShotPistol_Base.c.
{ return true; }
HasBullet() [43/43]
override bool WeaponStableState::HasBullet () inline private
Definition at line 44 of file SingleShotPistol_Base.c.
{ return true; }
HasMagazine() [1/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 32 of file Crossbow.c.
{ return false; }
HasMagazine() [2/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 43 of file Crossbow.c.
{ return false; }
HasMagazine() [3/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 35 of file SKS.c.
{ return false; }
HasMagazine() [4/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 46 of file SKS.c.
{ return false; }
HasMagazine() [5/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 37 of file BoltActionRifleExternalMagazine_Base.c.
{ return false; }
HasMagazine() [6/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 48 of file BoltActionRifleExternalMagazine_Base.c.
{ return true; }
HasMagazine() [7/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 59 of file BoltActionRifleExternalMagazine_Base.c.
{ return true; }
HasMagazine() [8/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 70 of file BoltActionRifleExternalMagazine_Base.c.
{ return false; }
HasMagazine() [9/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 81 of file BoltActionRifleExternalMagazine_Base.c.
{ return true; }
HasMagazine() [10/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 35 of file BoltActionRifleInnerMagazine_Base.c.
{ return false; }
HasMagazine() [11/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 46 of file BoltActionRifleInnerMagazine_Base.c.
{ return false; }
HasMagazine() [12/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 42 of file DoubleBarrel_Base.c.
{ return false; }
HasMagazine() [13/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 53 of file DoubleBarrel_Base.c.
{ return false; }
HasMagazine() [14/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 64 of file DoubleBarrel_Base.c.
{ return false; }
HasMagazine() [15/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 75 of file DoubleBarrel_Base.c.
{ return false; }
HasMagazine() [16/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 87 of file DoubleBarrel_Base.c.
{ return false; }
HasMagazine() [17/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 99 of file DoubleBarrel_Base.c.
{ return false; }
HasMagazine() [18/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 111 of file DoubleBarrel_Base.c.
{ return false; }
HasMagazine() [19/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 33 of file Flaregun.c.
{ return false; }
HasMagazine() [20/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 45 of file Flaregun.c.
{ return false; }
HasMagazine() [21/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 45 of file Pistol_Base.c.
{ return false; }
HasMagazine() [22/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 56 of file Pistol_Base.c.
{ return false; }
HasMagazine() [23/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 79 of file Pistol_Base.c.
{ return false; }
HasMagazine() [24/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 92 of file Pistol_Base.c.
{ return true; }
HasMagazine() [25/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 103 of file Pistol_Base.c.
{ return true; }
HasMagazine() [26/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 126 of file Pistol_Base.c.
{ return true; }
HasMagazine() [27/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 137 of file Pistol_Base.c.
{ return true; }
HasMagazine() [28/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 35 of file Repeater.c.
{ return false; }
HasMagazine() [29/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 46 of file Repeater.c.
{ return false; }
HasMagazine() [30/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 35 of file RifleBoltFree_Base.c.
{ return false; }
HasMagazine() [31/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 46 of file RifleBoltFree_Base.c.
{ return true; }
HasMagazine() [32/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 57 of file RifleBoltFree_Base.c.
{ return true; }
HasMagazine() [33/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 38 of file RifleBoltLock_Base.c.
{ return false; }
HasMagazine() [34/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 49 of file RifleBoltLock_Base.c.
{ return true; }
HasMagazine() [35/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 60 of file RifleBoltLock_Base.c.
{ return true; }
HasMagazine() [36/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 71 of file RifleBoltLock_Base.c.
{ return true; }
HasMagazine() [37/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 83 of file RifleBoltLock_Base.c.
{ return false; }
HasMagazine() [38/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 32 of file RifleSingleShot_Base.c.
{ return false; }
HasMagazine() [39/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 43 of file RifleSingleShot_Base.c.
{ return false; }
HasMagazine() [40/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 32 of file MP133.c.
{ return false; }
HasMagazine() [41/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 43 of file MP133.c.
{ return false; }
HasMagazine() [42/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 33 of file SingleShotPistol_Base.c.
{ return false; }
HasMagazine() [43/43]
override bool WeaponStableState::HasMagazine () inline private
Definition at line 45 of file SingleShotPistol_Base.c.
{ return false; }
InitMuzzleArray() [1/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 35 of file Crossbow.c.
{ m_muzzleHasBullet = {MuzzleState.E}; }
References m_muzzleHasBullet.
Referenced by WeaponStableState().
InitMuzzleArray() [2/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 46 of file Crossbow.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [3/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 38 of file SKS.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [4/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 50 of file SKS.c.
{ m_muzzleHasBullet = {MuzzleState.E}; }
References m_muzzleHasBullet.
InitMuzzleArray() [5/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 40 of file BoltActionRifleExternalMagazine_Base.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [6/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 51 of file BoltActionRifleExternalMagazine_Base.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [7/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 62 of file BoltActionRifleExternalMagazine_Base.c.
{ m_muzzleHasBullet = {MuzzleState.E}; }
References m_muzzleHasBullet.
InitMuzzleArray() [8/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 73 of file BoltActionRifleExternalMagazine_Base.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [9/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 84 of file BoltActionRifleExternalMagazine_Base.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [10/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 38 of file BoltActionRifleInnerMagazine_Base.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [11/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 49 of file BoltActionRifleInnerMagazine_Base.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [12/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 45 of file DoubleBarrel_Base.c.
{ m_muzzleHasBullet = {MuzzleState.L, MuzzleState.E}; }
References m_muzzleHasBullet.
InitMuzzleArray() [13/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 56 of file DoubleBarrel_Base.c.
{ m_muzzleHasBullet = {MuzzleState.E, MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [14/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 67 of file DoubleBarrel_Base.c.
{ m_muzzleHasBullet = {MuzzleState.F, MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [15/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 78 of file DoubleBarrel_Base.c.
{ m_muzzleHasBullet = {MuzzleState.F, MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [16/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 90 of file DoubleBarrel_Base.c.
{ m_muzzleHasBullet = {MuzzleState.F, MuzzleState.E}; }
References m_muzzleHasBullet.
InitMuzzleArray() [17/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 102 of file DoubleBarrel_Base.c.
{ m_muzzleHasBullet = {MuzzleState.E, MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [18/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 114 of file DoubleBarrel_Base.c.
{ m_muzzleHasBullet = {MuzzleState.E, MuzzleState.E}; }
References m_muzzleHasBullet.
InitMuzzleArray() [19/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 37 of file Flaregun.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [20/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 49 of file Flaregun.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [21/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 48 of file Pistol_Base.c.
{ m_muzzleHasBullet = {MuzzleState.E}; }
References m_muzzleHasBullet.
InitMuzzleArray() [22/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 59 of file Pistol_Base.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [23/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 84 of file Pistol_Base.c.
{ m_muzzleHasBullet = {MuzzleState.E}; }
References m_muzzleHasBullet.
InitMuzzleArray() [24/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 95 of file Pistol_Base.c.
{ m_muzzleHasBullet = {MuzzleState.E}; }
References m_muzzleHasBullet.
InitMuzzleArray() [25/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 106 of file Pistol_Base.c.
{ m_muzzleHasBullet = {MuzzleState.E}; }
References m_muzzleHasBullet.
InitMuzzleArray() [26/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 129 of file Pistol_Base.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [27/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 141 of file Pistol_Base.c.
{ m_muzzleHasBullet = {MuzzleState.E}; }
References m_muzzleHasBullet.
InitMuzzleArray() [28/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 38 of file Repeater.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [29/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 49 of file Repeater.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [30/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 38 of file RifleBoltFree_Base.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [31/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 49 of file RifleBoltFree_Base.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [32/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 60 of file RifleBoltFree_Base.c.
{ m_muzzleHasBullet = {MuzzleState.E}; }
References m_muzzleHasBullet.
InitMuzzleArray() [33/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 41 of file RifleBoltLock_Base.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [34/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 52 of file RifleBoltLock_Base.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [35/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 63 of file RifleBoltLock_Base.c.
{ m_muzzleHasBullet = {MuzzleState.E}; }
References m_muzzleHasBullet.
InitMuzzleArray() [36/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 75 of file RifleBoltLock_Base.c.
{ m_muzzleHasBullet = {MuzzleState.E}; }
References m_muzzleHasBullet.
InitMuzzleArray() [37/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 87 of file RifleBoltLock_Base.c.
{ m_muzzleHasBullet = {MuzzleState.E}; }
References m_muzzleHasBullet.
InitMuzzleArray() [38/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 35 of file RifleSingleShot_Base.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [39/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 46 of file RifleSingleShot_Base.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [40/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 35 of file MP133.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [41/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 46 of file MP133.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [42/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 37 of file SingleShotPistol_Base.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [43/43]
override void WeaponStableState::InitMuzzleArray () inline private
Definition at line 49 of file SingleShotPistol_Base.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
IsBoltOpen() [1/9]
override bool WeaponStableState::IsBoltOpen () inline private
Definition at line 48 of file SKS.c.
{ return true; }
IsBoltOpen() [2/9]
override bool WeaponStableState::IsBoltOpen () inline private
Definition at line 35 of file Flaregun.c.
{ return false; }
IsBoltOpen() [3/9]
override bool WeaponStableState::IsBoltOpen () inline private
Definition at line 47 of file Flaregun.c.
{ return false; }
IsBoltOpen() [4/9]
override bool WeaponStableState::IsBoltOpen () inline private
Definition at line 81 of file Pistol_Base.c.
{ return true; }
IsBoltOpen() [5/9]
override bool WeaponStableState::IsBoltOpen () inline private
Definition at line 139 of file Pistol_Base.c.
{ return true; }
IsBoltOpen() [6/9]
override bool WeaponStableState::IsBoltOpen () inline private
Definition at line 73 of file RifleBoltLock_Base.c.
{ return true; }
IsBoltOpen() [7/9]
override bool WeaponStableState::IsBoltOpen () inline private
Definition at line 85 of file RifleBoltLock_Base.c.
{ return true; }
IsBoltOpen() [8/9]
override bool WeaponStableState::IsBoltOpen () inline private
Definition at line 35 of file SingleShotPistol_Base.c.
{ return false; }
IsBoltOpen() [9/9]
override bool WeaponStableState::IsBoltOpen () inline private
Definition at line 47 of file SingleShotPistol_Base.c.
{ return false; }
IsDischarged()
override bool WeaponStableState::IsDischarged () inline private
Definition at line 82 of file Pistol_Base.c.
{ return true; }
IsJammed() [1/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 33 of file Crossbow.c.
{ return false; }
IsJammed() [2/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 44 of file Crossbow.c.
{ return false; }
IsJammed() [3/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 36 of file SKS.c.
{ return false; }
IsJammed() [4/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 47 of file SKS.c.
{ return false; }
IsJammed() [5/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 38 of file BoltActionRifleExternalMagazine_Base.c.
{ return false; }
IsJammed() [6/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 49 of file BoltActionRifleExternalMagazine_Base.c.
{ return false; }
IsJammed() [7/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 60 of file BoltActionRifleExternalMagazine_Base.c.
{ return false; }
IsJammed() [8/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 71 of file BoltActionRifleExternalMagazine_Base.c.
{ return false; }
IsJammed() [9/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 82 of file BoltActionRifleExternalMagazine_Base.c.
{ return false; }
IsJammed() [10/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 36 of file BoltActionRifleInnerMagazine_Base.c.
{ return false; }
IsJammed() [11/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 47 of file BoltActionRifleInnerMagazine_Base.c.
{ return false; }
IsJammed() [12/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 43 of file DoubleBarrel_Base.c.
{ return false; }
IsJammed() [13/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 54 of file DoubleBarrel_Base.c.
{ return false; }
IsJammed() [14/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 65 of file DoubleBarrel_Base.c.
{ return false; }
IsJammed() [15/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 76 of file DoubleBarrel_Base.c.
{ return false; }
IsJammed() [16/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 88 of file DoubleBarrel_Base.c.
{ return false; }
IsJammed() [17/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 100 of file DoubleBarrel_Base.c.
{ return false; }
IsJammed() [18/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 112 of file DoubleBarrel_Base.c.
{ return false; }
IsJammed() [19/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 34 of file Flaregun.c.
{ return false; }
IsJammed() [20/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 46 of file Flaregun.c.
{ return false; }
IsJammed() [21/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 46 of file Pistol_Base.c.
{ return false; }
IsJammed() [22/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 57 of file Pistol_Base.c.
{ return false; }
IsJammed() [23/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 80 of file Pistol_Base.c.
{ return false; }
IsJammed() [24/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 93 of file Pistol_Base.c.
{ return false; }
IsJammed() [25/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 104 of file Pistol_Base.c.
{ return false; }
IsJammed() [26/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 127 of file Pistol_Base.c.
{ return false; }
IsJammed() [27/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 138 of file Pistol_Base.c.
{ return false; }
IsJammed() [28/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 36 of file Repeater.c.
{ return false; }
IsJammed() [29/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 47 of file Repeater.c.
{ return false; }
IsJammed() [30/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 36 of file RifleBoltFree_Base.c.
{ return false; }
IsJammed() [31/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 47 of file RifleBoltFree_Base.c.
{ return false; }
IsJammed() [32/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 58 of file RifleBoltFree_Base.c.
{ return false; }
IsJammed() [33/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 39 of file RifleBoltLock_Base.c.
{ return false; }
IsJammed() [34/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 50 of file RifleBoltLock_Base.c.
{ return false; }
IsJammed() [35/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 61 of file RifleBoltLock_Base.c.
{ return false; }
IsJammed() [36/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 72 of file RifleBoltLock_Base.c.
{ return false; }
IsJammed() [37/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 84 of file RifleBoltLock_Base.c.
{ return false; }
IsJammed() [38/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 33 of file RifleSingleShot_Base.c.
{ return false; }
IsJammed() [39/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 44 of file RifleSingleShot_Base.c.
{ return false; }
IsJammed() [40/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 33 of file MP133.c.
{ return false; }
IsJammed() [41/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 44 of file MP133.c.
{ return false; }
IsJammed() [42/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 34 of file SingleShotPistol_Base.c.
{ return false; }
IsJammed() [43/43]
override bool WeaponStableState::IsJammed () inline private
Definition at line 46 of file SingleShotPistol_Base.c.
{ return false; }
IsRepairEnabled() [1/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 34 of file Crossbow.c.
{ return true; }
IsRepairEnabled() [2/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 45 of file Crossbow.c.
{ return true; }
IsRepairEnabled() [3/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 37 of file SKS.c.
{ return true; }
IsRepairEnabled() [4/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 49 of file SKS.c.
{ return true; }
IsRepairEnabled() [5/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 39 of file BoltActionRifleExternalMagazine_Base.c.
{ return true; }
IsRepairEnabled() [6/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 50 of file BoltActionRifleExternalMagazine_Base.c.
{ return true; }
IsRepairEnabled() [7/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 61 of file BoltActionRifleExternalMagazine_Base.c.
{ return true; }
IsRepairEnabled() [8/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 72 of file BoltActionRifleExternalMagazine_Base.c.
{ return true; }
IsRepairEnabled() [9/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 83 of file BoltActionRifleExternalMagazine_Base.c.
{ return true; }
IsRepairEnabled() [10/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 37 of file BoltActionRifleInnerMagazine_Base.c.
{ return true; }
IsRepairEnabled() [11/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 48 of file BoltActionRifleInnerMagazine_Base.c.
{ return true; }
IsRepairEnabled() [12/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 44 of file DoubleBarrel_Base.c.
{ return true; }
IsRepairEnabled() [13/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 55 of file DoubleBarrel_Base.c.
{ return true; }
IsRepairEnabled() [14/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 66 of file DoubleBarrel_Base.c.
{ return true; }
IsRepairEnabled() [15/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 77 of file DoubleBarrel_Base.c.
{ return true; }
IsRepairEnabled() [16/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 89 of file DoubleBarrel_Base.c.
{ return true; }
IsRepairEnabled() [17/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 101 of file DoubleBarrel_Base.c.
{ return true; }
IsRepairEnabled() [18/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 113 of file DoubleBarrel_Base.c.
{ return true; }
IsRepairEnabled() [19/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 36 of file Flaregun.c.
{ return true; }
IsRepairEnabled() [20/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 48 of file Flaregun.c.
{ return true; }
IsRepairEnabled() [21/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 47 of file Pistol_Base.c.
{ return true; }
IsRepairEnabled() [22/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 58 of file Pistol_Base.c.
{ return true; }
IsRepairEnabled() [23/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 83 of file Pistol_Base.c.
{ return true; }
IsRepairEnabled() [24/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 94 of file Pistol_Base.c.
{ return true; }
IsRepairEnabled() [25/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 105 of file Pistol_Base.c.
{ return true; }
IsRepairEnabled() [26/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 128 of file Pistol_Base.c.
{ return true; }
IsRepairEnabled() [27/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 140 of file Pistol_Base.c.
{ return true; }
IsRepairEnabled() [28/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 37 of file Repeater.c.
{ return true; }
IsRepairEnabled() [29/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 48 of file Repeater.c.
{ return true; }
IsRepairEnabled() [30/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 37 of file RifleBoltFree_Base.c.
{ return true; }
IsRepairEnabled() [31/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 48 of file RifleBoltFree_Base.c.
{ return true; }
IsRepairEnabled() [32/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 59 of file RifleBoltFree_Base.c.
{ return true; }
IsRepairEnabled() [33/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 40 of file RifleBoltLock_Base.c.
{ return true; }
IsRepairEnabled() [34/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 51 of file RifleBoltLock_Base.c.
{ return true; }
IsRepairEnabled() [35/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 62 of file RifleBoltLock_Base.c.
{ return true; }
IsRepairEnabled() [36/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 74 of file RifleBoltLock_Base.c.
{ return true; }
IsRepairEnabled() [37/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 86 of file RifleBoltLock_Base.c.
{ return true; }
IsRepairEnabled() [38/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 34 of file RifleSingleShot_Base.c.
{ return true; }
IsRepairEnabled() [39/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 45 of file RifleSingleShot_Base.c.
{ return true; }
IsRepairEnabled() [40/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 34 of file MP133.c.
{ return true; }
IsRepairEnabled() [41/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 45 of file MP133.c.
{ return true; }
IsRepairEnabled() [42/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 36 of file SingleShotPistol_Base.c.
{ return true; }
IsRepairEnabled() [43/43]
override bool WeaponStableState::IsRepairEnabled () inline private
Definition at line 48 of file SingleShotPistol_Base.c.
{ return true; }
OnEntry() [1/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 28 of file Crossbow.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { Cocked Empty CE"); m_weapon.SetCharged(true); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [2/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 39 of file Crossbow.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { Loaded L"); m_weapon.SetCharged(true); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [3/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 31 of file SKS.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { close bullet"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [4/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 42 of file SKS.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { open nobull"); m_weapon.SetWeaponOpen(true); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [5/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 33 of file BoltActionRifleExternalMagazine_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { close bullet nomag"); super.OnEntry(e);}
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [6/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 44 of file BoltActionRifleExternalMagazine_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { close bullet mag"); super.OnEntry(e);}
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [7/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 55 of file BoltActionRifleExternalMagazine_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { close nobull mag"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [8/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 66 of file BoltActionRifleExternalMagazine_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { close fireout bullet nomag"); super.OnEntry(e);}
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [9/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 77 of file BoltActionRifleExternalMagazine_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { close fireout bull mag"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [10/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 31 of file BoltActionRifleInnerMagazine_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { LoadedCharged C1"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [11/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 42 of file BoltActionRifleInnerMagazine_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { LoadedDischarged D1"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [12/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 38 of file DoubleBarrel_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { LoadedEmpty L_E"); super.OnEntry(e); m_weapon.SetCurrentMuzzle(MuzzleIndex.First);}
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [13/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 49 of file DoubleBarrel_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { EmptyLoaded E_L"); super.OnEntry(e); m_weapon.SetCurrentMuzzle(MuzzleIndex.Second);}
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [14/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 60 of file DoubleBarrel_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { FireoutLoaded F_L"); super.OnEntry(e); m_weapon.SetCurrentMuzzle(MuzzleIndex.Second);}
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [15/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 71 of file DoubleBarrel_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { FireoutFireout F_F"); super.OnEntry(e); m_weapon.SetCurrentMuzzle(MuzzleIndex.First);}
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [16/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 83 of file DoubleBarrel_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { FireoutEmpty F_E"); super.OnEntry(e); m_weapon.SetCurrentMuzzle(MuzzleIndex.First);}
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [17/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 95 of file DoubleBarrel_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { EmptyFireout E_F"); super.OnEntry(e); m_weapon.SetCurrentMuzzle(MuzzleIndex.First);}
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [18/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 107 of file DoubleBarrel_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { EmptyEmpty E_E"); super.OnEntry(e); m_weapon.SetCurrentMuzzle(MuzzleIndex.First);}
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [19/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 11 of file WeaponStateJammed.c.
  {
    super.OnEntry(e);
    m_weapon.SetJammed(true);
  }
References m_weapon.
OnEntry() [20/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 29 of file Flaregun.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { Fireout F"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [21/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 41 of file Flaregun.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { Loaded C"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [22/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 41 of file Pistol_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnstate] { CC00 closed charged nobull nomag"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnEntry() [23/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 52 of file Pistol_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnstate] { CC10 closed charged bullet nomag"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnEntry() [24/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 75 of file Pistol_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnstate] { OD00 opened dischgd nobullet nomag"); m_weapon.SetCharged(false); m_weapon.SetWeaponOpen(true); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [25/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 88 of file Pistol_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnstate] { CC01 closed charged nobullet mag"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnEntry() [26/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 99 of file Pistol_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnstate] { CD01 closed dischgd nobullet mag"); m_weapon.SetCharged(false); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [27/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 122 of file Pistol_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnstate] { CC11 closed charged bullet mag"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnEntry() [28/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 133 of file Pistol_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnstate] { OD01 opened dischgd nobullet mag"); m_weapon.SetWeaponOpen(true); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [29/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 31 of file Repeater.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { LoadedCharged C1"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [30/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 42 of file Repeater.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { LoadedDischarged D1"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [31/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 31 of file RifleBoltFree_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { close bullet nomag"); super.OnEntry(e);}
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [32/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 42 of file RifleBoltFree_Base.c.
{ /*Print("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { close bullet mag");*/ super.OnEntry(e);}
OnEntry() [33/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 53 of file RifleBoltFree_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { close nobull mag"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [34/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 34 of file RifleBoltLock_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { close bullet nomag"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [35/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 45 of file RifleBoltLock_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { close bullet mag"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [36/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 56 of file RifleBoltLock_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { close nobull mag"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [37/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 67 of file RifleBoltLock_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { lock nobull mag"); m_weapon.SetWeaponOpen(true); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [38/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 79 of file RifleBoltLock_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { lock nobull nomag"); m_weapon.SetWeaponOpen(true); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [39/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 28 of file RifleSingleShot_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { Fireout F"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [40/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 39 of file RifleSingleShot_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { Loaded C"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [41/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 28 of file MP133.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { Fireout F"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [42/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 39 of file MP133.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { Loaded C"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [43/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 29 of file SingleShotPistol_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { Fireout F"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [44/44]
override void WeaponStableState::OnEntry (WeaponEventBase e) inline private
Definition at line 41 of file SingleShotPistol_Base.c.
{ if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { Loaded C"); super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [1/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 29 of file Crossbow.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } Cocked Empty CE"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [2/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 40 of file Crossbow.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } Loaded L"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [3/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 32 of file SKS.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } close bullet"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [4/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 43 of file SKS.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } open nobull"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [5/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 34 of file BoltActionRifleExternalMagazine_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } close bullet nomag"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [6/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 45 of file BoltActionRifleExternalMagazine_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } close bullet mag"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [7/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 56 of file BoltActionRifleExternalMagazine_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } close nobull mag"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [8/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 67 of file BoltActionRifleExternalMagazine_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } close fireout bullet nomag"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [9/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 78 of file BoltActionRifleExternalMagazine_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } close fireout bull mag"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [10/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 32 of file BoltActionRifleInnerMagazine_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } LoadedCharged C1"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [11/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 43 of file BoltActionRifleInnerMagazine_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } LoadedDischarged D1"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [12/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 39 of file DoubleBarrel_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } LoadedEmpty L_E"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [13/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 50 of file DoubleBarrel_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } EmptyLoaded E_L"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [14/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 61 of file DoubleBarrel_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } FireoutLoaded F_L"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [15/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 72 of file DoubleBarrel_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } FireoutFireout F_F"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [16/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 84 of file DoubleBarrel_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } FireoutEmpty F_E"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [17/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 96 of file DoubleBarrel_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } EmptyFireout E_F"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [18/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 108 of file DoubleBarrel_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } EmptyEmpty E_E"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [19/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 22 of file WeaponStateJammed.c.
  {
    super.OnExit(e);
    //m_weapon.SetJammed(false);
  }
OnExit() [20/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 30 of file Flaregun.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } Fireout F"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [21/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 42 of file Flaregun.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } Loaded C"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [22/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 42 of file Pistol_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnstate] } CC00 closed charged nobull nomag"); }
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnExit() [23/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 53 of file Pistol_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnstate] } CC10 closed charged bullet nomag"); }
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnExit() [24/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 76 of file Pistol_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnstate] } 0D00 opened dischgd nobullet nomag"); }
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnExit() [25/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 89 of file Pistol_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnstate] } CC01 closed charged nobullet mag"); }
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnExit() [26/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 100 of file Pistol_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnstate] } CD01 closed dischgd nobullet mag"); }
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnExit() [27/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 123 of file Pistol_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnstate] } CC11 closed charged bullet mag"); }
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnExit() [28/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 134 of file Pistol_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnstate] } 0D01 opened dischgd nobullet mag"); }
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnExit() [29/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 32 of file Repeater.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } LoadedCharged C1"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [30/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 43 of file Repeater.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } LoadedDischarged D1"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [31/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 32 of file RifleBoltFree_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } close bullet nomag"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [32/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 43 of file RifleBoltFree_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } close bullet mag"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [33/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 54 of file RifleBoltFree_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } close nobull mag"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [34/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 35 of file RifleBoltLock_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } close bullet nomag"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [35/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 46 of file RifleBoltLock_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } close bullet mag"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [36/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 57 of file RifleBoltLock_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } close nobull mag"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [37/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 68 of file RifleBoltLock_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } open nobull mag"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [38/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 80 of file RifleBoltLock_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } open nobull nomag"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [39/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 29 of file RifleSingleShot_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } Fireout F"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [40/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 40 of file RifleSingleShot_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } Loaded C"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [41/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 29 of file MP133.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } Fireout F"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [42/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 40 of file MP133.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } Loaded C"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [43/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 30 of file SingleShotPistol_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } Fireout F"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [44/44]
override void WeaponStableState::OnExit (WeaponEventBase e) inline private
Definition at line 42 of file SingleShotPistol_Base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } Loaded C"); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
The documentation for this class was generated from the following files:
scripts/4_World/Entities/Firearms/Archery/Crossbow.c
scripts/4_World/Entities/Firearms/AutomaticRifle/SKS.c
scripts/4_World/Entities/Firearms/BoltActionRifleExternalMagazine_Base.c
scripts/4_World/Entities/Firearms/BoltActionRifleInnerMagazine_Base.c
scripts/4_World/Entities/Firearms/DoubleBarrel_Base.c
scripts/4_World/Entities/Firearms/FSM/States/WeaponStateJammed.c
scripts/4_World/Entities/Firearms/Pistol/Flaregun.c
scripts/4_World/Entities/Firearms/Pistol_Base.c
scripts/4_World/Entities/Firearms/Rifle/Repeater.c
scripts/4_World/Entities/Firearms/RifleBoltFree_Base.c
scripts/4_World/Entities/Firearms/RifleBoltLock_Base.c
scripts/4_World/Entities/Firearms/RifleSingleShot_Base.c
scripts/4_World/Entities/Firearms/Shotgun/MP133.c
scripts/4_World/Entities/Firearms/SingleShotPistol_Base.c