DayZ: CAContinuousBase Class Reference
CAContinuousBase Class Reference
Private Member Functions
override bool IsContinuousAction ()
void OnCompletePogress (ActionData action_data)
Private Member Functions inherited from CABase
void Init (ActionData action_data)
void Setup (ActionData action_data)
int Execute (ActionData action_data)
int Cancel (ActionData action_data)
int Interrupt (ActionData action_data)
void SetACData (Param units)
Param GetACData ()
bool IsContinuousAction ()
float GetProgress ()
Additional Inherited Members
Private Attributes inherited from CABase
ActionBase m_Action
float m_LastTick
ref Param m_ACData
ref Param2< float, float > m_ProgressParam
Detailed Description
Definition at line 1 of file CAContinuousBase.c.
Member Function Documentation
IsContinuousAction()
override bool CAContinuousBase::IsContinuousAction () inline private
Definition at line 3 of file CAContinuousBase.c.
  {
    return true;
  }
OnCompletePogress()
void CAContinuousBase::OnCompletePogress (ActionData action_data) inline private
Definition at line 8 of file CAContinuousBase.c.
  {
    ActionContinuousBase action = ActionContinuousBase.Cast(action_data.m_Action);
    if (action)
      action.OnFinishProgress(action_data);
  }
Referenced by CAContinuousCraft::Execute(), CAContinuousDisinfectPlant::Execute(), CAContinuousEmpty::Execute(), CAContinuousEmptyMagazine::Execute(), CAContinuousFertilizeGardenSlot::Execute(), CAContinuousFill::Execute(), CAContinuousFillBrakes::Execute(), CAContinuousFillCoolant::Execute(), CAContinuousFillFuel::Execute(), CAContinuousFillOil::Execute(), CAContinuousFillPowerGenerator::Execute(), CAContinuousMineWood::Execute(), CAContinuousQuantity::Execute(), CAContinuousQuantityLiquidTransfer::Execute(), CAContinuousQuantityRepeat::Execute(), CAContinuousRepeat::Execute(), CAContinuousRepeatFishing::Execute(), CAContinuousRepeatStartEngine::Execute(), CAContinuousTime::Execute(), CAContinuousTimeCooking::Execute(), CAContinuousTransferQuantity::Execute(), CAContinuousWaterPlant::Execute(), CAContinuousWaterSlot::Execute(), CAContinuousWringClothes::Execute(), and CAContinuousRepeatPushCar::Execute().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousBase.c