DayZ: ItemMegaphone Class Reference
ItemMegaphone Class Reference
Private Member Functions
override bool IsTransmitter ()
override void OnSwitchOn ()
override void OnWorkStart ()
override void OnWorkStop ()
override void SetActions ()
Detailed Description
Definition at line 1 of file Megaphone.c.
Member Function Documentation
IsTransmitter()
override bool ItemMegaphone::IsTransmitter () inline private
Definition at line 3 of file Megaphone.c.
  {
    return true;
  }
OnSwitchOn()
override void ItemMegaphone::OnSwitchOn () inline private
Definition at line 9 of file Megaphone.c.
  {
    if (!GetCompEM().CanWork())
      GetCompEM().SwitchOff();
  }
OnWorkStart()
override void ItemMegaphone::OnWorkStart () inline private
Definition at line 15 of file Megaphone.c.
  {
    //turn device on
    SwitchOn(true); // Note: This is not Energy Manager function. This is engine function.
  }
OnWorkStop()
override void ItemMegaphone::OnWorkStop () inline private
Definition at line 21 of file Megaphone.c.
  {
    //auto switch off (EM)
    GetCompEM().SwitchOff();
    //turn off device
    SwitchOn(false); // Note: This is not Energy Manager function. This is engine function.
  }
SetActions()
override void ItemMegaphone::SetActions () inline private
Definition at line 34 of file Megaphone.c.
  {
    super.SetActions();
    AddAction(ActionTurnOnTransmitter);
    AddAction(ActionTurnOffTransmitter);
    AddAction(ActionRaiseMegaphone);
  }
References ActionRaiseMegaphone(), ActionTurnOffTransmitter(), ActionTurnOnTransmitter(), and AddAction().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Megaphone.c