DayZ: DayZPlayerImplementJumpClimb Class Reference
DayZPlayerImplementJumpClimb Class Reference
Private Member Functions
void DayZPlayerImplementJumpClimb (DayZPlayerImplement pPlayer)
bool WasSuccessful ()
Only valid immediately after 'JumpOrClimb' is called.
void JumpOrClimb ()
Can't change to bool return.
void CheckAndFinishJump (int pLandType=0)
bool Climb (SHumanCommandClimbResult pClimbRes)
void Jump ()
int GetClimbType (float pHeight)
Private Attributes
bool m_bIsJumpInProgress = false
DayZPlayerImplement m_Player
bool m_bWasClimb
Detailed Description
Definition at line 1 of file DayZPlayerImplementJumpClimb.c.
Constructor & Destructor Documentation
DayZPlayerImplementJumpClimb()
void DayZPlayerImplementJumpClimb::DayZPlayerImplementJumpClimb (DayZPlayerImplement pPlayer) inline private
Definition at line 3 of file DayZPlayerImplementJumpClimb.c.
  {
    m_Player = pPlayer;
  }
References m_Player.
Member Function Documentation
CheckAndFinishJump()
void DayZPlayerImplementJumpClimb::CheckAndFinishJump (int pLandType = 0) inline private
Definition at line 59 of file DayZPlayerImplementJumpClimb.c.
  {
    if (m_bIsJumpInProgress)
    {
      m_bIsJumpInProgress = false;
      m_Player.OnJumpEnd(pLandType);
    }
  }
References m_bIsJumpInProgress, and m_Player.
Climb()
bool DayZPlayerImplementJumpClimb::Climb (SHumanCommandClimbResult pClimbRes) inline private
Definition at line 68 of file DayZPlayerImplementJumpClimb.c.
  {
    int climbType = GetClimbType(pClimbRes.m_fClimbHeight);
    if (climbType != -1)
    {
      m_Player.StartCommand_Climb(pClimbRes, climbType);
      m_Player.StopHandEvent();
      m_bWasClimb = true;
    }
    return climbType != -1;
  }
References GetClimbType(), m_bWasClimb, and m_Player.
Referenced by JumpOrClimb().
GetClimbType()
int DayZPlayerImplementJumpClimb::GetClimbType (float pHeight) inline private
Definition at line 92 of file DayZPlayerImplementJumpClimb.c.
  {
    int climbType = -1;
    if (pHeight < 1.1)
      climbType = 0;
    else if (pHeight >= 1.1 && pHeight < 1.7)
      climbType = 1;
    else if (pHeight >= 1.7 && pHeight < 2.75)
      climbType = 2;
    return climbType;
  }
Referenced by Climb(), and JumpOrClimb().
Jump()
void DayZPlayerImplementJumpClimb::Jump () inline private
Definition at line 82 of file DayZPlayerImplementJumpClimb.c.
  {
    m_bIsJumpInProgress = true;
    m_Player.SetFallYDiff(m_Player.GetPosition()[1]);
    m_Player.OnJumpStart();
    m_Player.StartCommand_Fall(2.6);
    m_Player.StopHandEvent();
  }
References m_bIsJumpInProgress, and m_Player.
Referenced by JumpOrClimb().
JumpOrClimb()
void DayZPlayerImplementJumpClimb::JumpOrClimb () inline private
Can't change to bool return.
Reset states
Early exit if the player is being heavy damaged so the stagger animation can't be skipped
Definition at line 15 of file DayZPlayerImplementJumpClimb.c.
  {
    m_bWasClimb = false;
    if (m_Player.IsInFullbodyDamageAnimation())
      return;
    SHumanCommandClimbSettings hcls = m_Player.GetDayZPlayerType().CommandClimbSettingsW();
    if (m_Player.m_MovementState.m_iMovement != DayZPlayerConstants.MOVEMENTIDX_IDLE)
      hcls.m_fFwMaxDistance = 2.5;
    else
      hcls.m_fFwMaxDistance = 1.2;
    SHumanCommandClimbResult climbRes = new SHumanCommandClimbResult();
    HumanCommandClimb.DoClimbTest(m_Player, climbRes, 0);
    if (climbRes.m_bIsClimb || climbRes.m_bIsClimbOver)
    {
      int climbType = GetClimbType(climbRes.m_fClimbHeight);
      if (!m_Player.CanClimb(climbType, climbRes))
        return;
      if (Climb(climbRes))
      {
        if (climbType == 1)
          m_Player.DepleteStamina(EStaminaModifiers.VAULT);
        else if (climbType == 2)
          m_Player.DepleteStamina(EStaminaModifiers.CLIMB);
        return;
      }
    }
    if (m_Player.CanJump())
    {
      Jump();
      m_Player.DepleteStamina(EStaminaModifiers.JUMP);
    }
  }
References Climb(), HumanCommandClimb::DoClimbTest(), GetClimbType(), Jump(), m_bWasClimb, m_Player, and SHumanCommandClimbSettings().
WasSuccessful()
bool DayZPlayerImplementJumpClimb::WasSuccessful () inline private
Only valid immediately after 'JumpOrClimb' is called.
Definition at line 9 of file DayZPlayerImplementJumpClimb.c.
  {
    return m_bIsJumpInProgress || m_bWasClimb;
  }
References m_bIsJumpInProgress, and m_bWasClimb.
Member Data Documentation
m_bIsJumpInProgress
bool DayZPlayerImplementJumpClimb::m_bIsJumpInProgress = false private
Definition at line 106 of file DayZPlayerImplementJumpClimb.c.
Referenced by CheckAndFinishJump(), Jump(), and WasSuccessful().
m_bWasClimb
bool DayZPlayerImplementJumpClimb::m_bWasClimb private
Definition at line 110 of file DayZPlayerImplementJumpClimb.c.
Referenced by Climb(), JumpOrClimb(), and WasSuccessful().
m_Player
DayZPlayerImplement DayZPlayerImplementJumpClimb::m_Player private
Definition at line 109 of file DayZPlayerImplementJumpClimb.c.
Referenced by CheckAndFinishJump(), Climb(), DayZPlayerImplementJumpClimb(), Jump(), and JumpOrClimb().
The documentation for this class was generated from the following file:
scripts/4_World/Entities/DayZPlayerImplementJumpClimb.c