DayZ: scripts/3_Game/Systems/FSMBase.c File Reference
FSMBase.c File Reference
Classes
class FSMTransition< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >
class FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >
Enumerations
enum ProcessEventResult { FSM_OK , FSM_TERMINATED , FSM_ABORTED , FSM_NO_TRANSITION }
Functions
void fsmbDebugPrint (string s)
void fsmbDebugSpam (string s)
Enumeration Type Documentation
ProcessEventResult
enum ProcessEventResult
Enumerator
FSM_OK
FSM_TERMINATED
FSM_ABORTED
FSM_NO_TRANSITION
Definition at line 40 of file FSMBase.c.
{
  FSM_OK,
  FSM_TERMINATED,
  FSM_ABORTED,
  FSM_NO_TRANSITION,
};
Function Documentation
fsmbDebugPrint()
void fsmbDebugPrint (string s)
Definition at line 1 of file FSMBase.c.
{
#ifdef FSM_DEBUG
  PrintToRPT("" + s); // comment/uncomment to hide/see debug logs
#else
  //Print("" + s); // comment/uncomment to hide/see debug logs
#endif
}
References PrintToRPT().
Referenced by FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessLocalTransition(), OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessLocalTransition(), OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), and FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start().
fsmbDebugSpam()
void fsmbDebugSpam (string s)
Definition at line 9 of file FSMBase.c.
{
#ifdef FSM_DEBUG_SPAM
  PrintToRPT("" + s); // comment/uncomment to hide/see debug logs
#else
  //Print("" + s); // comment/uncomment to hide/see debug logs
#endif
}
References PrintToRPT().