DayZ: ActionUngagTarget Class Reference
ActionUngagTarget Class Reference
Private Member Functions
void ActionUngagTarget ()
override void CreateConditionComponents ()
override GetInputType ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
bool IsWearingGag (PlayerBase player)
Private Member Functions inherited from ActionContinuousBase
void OnStartAnimationLoopServer (ActionData action_data)
void OnStartAnimationLoopClient (ActionData action_data)
void OnEndAnimationLoopServer (ActionData action_data)
void OnEndAnimationLoopClient (ActionData action_data)
void OnFinishProgressServer (ActionData action_data)
void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 1 of file ActionUngagTarget.c.
Constructor & Destructor Documentation
ActionUngagTarget()
void ActionUngagTarget::ActionUngagTarget () inline private
Definition at line 3 of file ActionUngagTarget.c.
  {
    m_CallbackClass = ActionUncoverHeadTargetCB;
    m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_COVERHEAD_TARGET;
    //m_FullBody = true;
    m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
    m_Text = "#ungag_person";
  }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionUngagTarget::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 24 of file ActionUngagTarget.c.
  {
    PlayerBase targetPlayer;
    if (Class.CastTo(targetPlayer, target.GetObject()))
    {
      if (IsWearingGag(targetPlayer) && null == player.GetHumanInventory().GetEntityInHands())
        return true;
    }
    return false;
  }
References Class::CastTo(), and IsWearingGag().
CreateConditionComponents()
override void ActionUngagTarget::CreateConditionComponents () inline private
Definition at line 12 of file ActionUngagTarget.c.
  {
    m_ConditionItem = new CCINone;
    m_ConditionTarget = new CCTMan(UAMaxDistances.DEFAULT, false);
  }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetInputType()
override ActionUngagTarget::GetInputType () inline private
Definition at line 19 of file ActionUngagTarget.c.
  {
    return ContinuousInteractActionInput;
  }
IsWearingGag()
bool ActionUngagTarget::IsWearingGag (PlayerBase player) inline private
Definition at line 52 of file ActionUngagTarget.c.
  {
    EntityAI attachment;
    Class.CastTo(attachment, player.GetInventory().FindAttachment(InventorySlots.MASK));
    if (attachment && attachment.GetType() == "MouthRag")
      return true;
    return false;
  }
References Class::CastTo().
Referenced by ActionCondition().
OnFinishProgressServer()
override void ActionUngagTarget::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 35 of file ActionUngagTarget.c.
  {
    PlayerBase ntarget = PlayerBase.Cast(action_data.m_Target.GetObject());
    if (CanReceiveAction(action_data.m_Target))
    {
      EntityAI attachment;
      Class.CastTo(attachment, ntarget.GetInventory().FindAttachment(InventorySlots.MASK));
      if (attachment && attachment.GetType() == "MouthRag")
      {
        UngagSelfLambda lamb = new UngagSelfLambda(attachment, "Rag", action_data.m_Player);
        lamb.SetTransferParams(true, true, true, false, 1);
        action_data.m_Player.ServerReplaceItemElsewhereWithNewInHands(lamb);
      }
    }
  }
References CanReceiveAction(), and Class::CastTo().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionUngagTarget.c