DayZ: OptionSelector Class Reference
OptionSelector Class Reference
Protected Member Functions
void OptionSelectorMultistate (Widget parent, int current_index, ScriptedWidgetEventHandler parent_c, bool disabled, notnull array< string > options)
void LoadNewValues (notnull array< string > options, int current_index)
override void SetNextOption ()
override void SetPrevOption ()
void PerformSetOption (int index)
void SetCanSwitch (bool value)
bool CanSwitch ()
void SetValue (int value, bool fire_event=true)
void SetValue (string value, bool fire_event=true)
void SetRandomValue ()
int GetValue ()
override void SetStringOption (string option, bool fire_event=true)
Protected Attributes
bool m_CanSwitch
Detailed Description
Definition at line 1 of file OptionSelectorMultistate.c.
Member Function Documentation
CanSwitch()
bool OptionSelector::CanSwitch () inline protected
Definition at line 64 of file OptionSelectorMultistate.c.
  {
    return m_CanSwitch;
  }
References m_CanSwitch.
GetValue()
int OptionSelector::GetValue () inline protected
Definition at line 99 of file OptionSelectorMultistate.c.
  {
    return m_SelectedOptionIndex;
  }
LoadNewValues()
void OptionSelector::LoadNewValues (notnull array< string > options, int current_index) inline protected
Definition at line 22 of file OptionSelectorMultistate.c.
  {
    m_Options = options;
    SetValue(current_index);
  }
References SetValue().
OptionSelectorMultistate()
void OptionSelector::OptionSelectorMultistate (Widget parent, int current_index, ScriptedWidgetEventHandler parent_c, bool disabled, notnull array< string > options) inline protected
Definition at line 5 of file OptionSelectorMultistate.c.
  {
    m_CanSwitch = true;
    m_SelectorType = 2;
    m_Options = options;
    if (options.Count() == 0)
      Error("Invalid OptionSelectorMultistate options");
    if (current_index < 0 || current_index >= m_Options.Count())
      m_SelectedOptionIndex = 0;
    else
      m_SelectedOptionIndex = current_index;
    m_SelectedOption.SetText(m_Options.Get(m_SelectedOptionIndex));
  }
References Error().
PerformSetOption()
void OptionSelector::PerformSetOption (int index) inline protected
Definition at line 52 of file OptionSelectorMultistate.c.
  {
    m_SelectedOptionIndex = index;
    m_SelectedOption.SetText(m_Options.Get(index));
    m_OptionChanged.Invoke(index);
  }
Referenced by SetNextOption(), and SetPrevOption().
SetCanSwitch()
void OptionSelector::SetCanSwitch (bool value) inline protected
Definition at line 59 of file OptionSelectorMultistate.c.
  {
    m_CanSwitch = value;
  }
SetNextOption()
override void OptionSelector::SetNextOption () inline protected
Definition at line 28 of file OptionSelectorMultistate.c.
  {
    int idx = m_SelectedOptionIndex;
    idx++;
    if (idx >= m_Options.Count())
      idx = 0;
    m_AttemptOptionChange.Invoke(idx);
    if (m_CanSwitch)
      PerformSetOption(idx);
  }
References PerformSetOption().
Referenced by OptionSelectorBase::OnClick(), and OptionSelectorBase::OnMouseButtonUp().
SetPrevOption()
override void OptionSelector::SetPrevOption () inline protected
Definition at line 40 of file OptionSelectorMultistate.c.
  {
    int idx = m_SelectedOptionIndex;
    idx--;
    if (idx < 0)
      idx = m_Options.Count() - 1;
    m_AttemptOptionChange.Invoke(idx);
    if (m_CanSwitch)
      PerformSetOption(idx);
  }
References PerformSetOption().
Referenced by OptionSelectorBase::OnMouseButtonUp().
SetRandomValue()
void OptionSelector::SetRandomValue () inline protected
Definition at line 92 of file OptionSelectorMultistate.c.
  {
    m_SelectedOptionIndex = Math.RandomInt(0, m_Options.Count());
    m_SelectedOption.SetText(m_Options.Get(m_SelectedOptionIndex));
    m_OptionChanged.Invoke(m_SelectedOptionIndex);
  }
References Math::RandomInt().
SetStringOption()
override void OptionSelector::SetStringOption (string option, bool fire_event = true) inline protected
Definition at line 104 of file OptionSelectorMultistate.c.
  {
    int index = m_Options.Find(option);
    if (index > -1)
    {
      m_SelectedOptionIndex = index;
      m_SelectedOption.SetText(m_Options.Get(m_SelectedOptionIndex));
      if (fire_event)
        m_OptionChanged.Invoke(m_SelectedOptionIndex);
    }
  }
SetValue() [1/2]
void OptionSelector::SetValue (int value, bool fire_event = true) inline protected
Definition at line 69 of file OptionSelectorMultistate.c.
  {
    if (value < m_Options.Count() && value >= 0)
    {
      m_SelectedOptionIndex = value;
      m_SelectedOption.SetText(m_Options.Get(m_SelectedOptionIndex));
      if (fire_event)
        m_OptionChanged.Invoke(m_SelectedOptionIndex);
    }
  }
Referenced by LoadNewValues().
SetValue() [2/2]
void OptionSelector::SetValue (string value, bool fire_event = true) inline protected
Definition at line 80 of file OptionSelectorMultistate.c.
  {
    int index = m_Options.Find(value);
    if (index >= 0)
    {
      m_SelectedOptionIndex = index;
      m_SelectedOption.SetText(m_Options.Get(m_SelectedOptionIndex));
      if (fire_event)
        m_OptionChanged.Invoke(m_SelectedOptionIndex);
    }
  }
Member Data Documentation
m_CanSwitch
bool OptionSelector::m_CanSwitch protected
Definition at line 3 of file OptionSelectorMultistate.c.
Referenced by CanSwitch().
The documentation for this class was generated from the following file:
scripts/5_Mission/GUI/NewUI/OptionSelectorMultistate.c