DayZ: BuildingSuper Class Reference
BuildingSuper Class Reference
Protected Member Functions
override void EEInit ()
override void EEDelete (EntityAI parent)
void BonfireHeating ()
DEPRECATED.
Protected Attributes
BonfireLight m_Light
Particle m_ParticleFire
Particle m_ParticleSmoke
EffectSound m_SoundFireLoop
ref Timer m_BonfireHeatingTimer
ref UniversalTemperatureSource m_UTSource
DEPRECATED.
ref UniversalTemperatureSourceSettings m_UTSSettings
ref UniversalTemperatureSourceLambdaConstant m_UTSLBonfire
Private Member Functions
void BuildingWithFireplace ()
override bool IsBuilding ()
override bool IsFuelStation ()
override float GetLiquidThroughputCoef ()
void Land_Misc_Greenhouse ()
override bool IsBuilding ()
override bool IsWell ()
override EWaterSourceObjectType GetWaterSourceObjectType ()
override float GetLiquidThroughputCoef ()
override void SetActions ()
Private Attributes
const float TIMER_HEATING_UPDATE_INTERVAL = 2
const float PARAM_HEAT_RADIUS = 15
const float PARAM_FULL_HEAT_RADIUS = 5
const float PARAM_MAX_TRANSFERED_TEMPERATURE = 25
const float CONST_FIRE_TEMP = 1000
maximum value for temperature that will be transfered to player (environment)
Detailed Description
Definition at line 1 of file BuildingWithFireplace.c.
Member Function Documentation
BonfireHeating()
void BuildingSuper::BonfireHeating () inline protected
DEPRECATED.
Definition at line 95 of file Bonfire.c.
{};
BuildingWithFireplace()
void BuildingSuper::BuildingWithFireplace () inline private
Definition at line 3 of file BuildingWithFireplace.c.
  {
  }
EEDelete()
override void BuildingSuper::EEDelete (EntityAI parent) inline protected
Definition at line 67 of file Bonfire.c.
  {
    super.EEDelete(parent);
#ifndef SERVER
    // outside of bubble - do effects cleanup (light, particles, sound)
    // light
    if (m_Light)
      m_Light.FadeOut();
    // particles
    if (m_ParticleSmoke)
      m_ParticleSmoke.Stop();
    if (m_ParticleFire)
      m_ParticleFire.Stop();
    // sounds
    if (m_SoundFireLoop)
      m_SoundFireLoop.SoundStop();
#endif
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
      m_UTSource.SetActive(false);
  }
References GetGame(), m_Light, m_ParticleSmoke, m_SoundFireLoop, m_UTSource, EffectSound::SoundStop(), and Particle::Stop().
EEInit()
override void BuildingSuper::EEInit () inline protected
Definition at line 22 of file Bonfire.c.
  {
    super.EEInit();
#ifndef SERVER
    // object creation - create effects (light, particles, sound)
    // light
    if (!m_Light)
    {
      m_Light = BonfireLight.Cast(ScriptedLightBase.CreateLight(BonfireLight, Vector(0, 0, 0), 1));
      m_Light.AttachOnMemoryPoint(this, m_Light.m_MemoryPoint);
      m_Light.FadeBrightnessTo(m_Light.m_FireBrightness, 0);
      m_Light.FadeRadiusTo(m_Light.m_FireRadius, 0);
    }
    // particles
    if (!m_ParticleSmoke)
      m_ParticleSmoke = ParticleManager.GetInstance().PlayOnObject(ParticleList.BONFIRE_SMOKE, this, GetMemoryPointPos("bonfire_smoke"), Vector(0, 0, 0), true);
    if (!m_ParticleFire)
      m_ParticleFire = ParticleManager.GetInstance().PlayOnObject(ParticleList.BONFIRE_FIRE, this, GetMemoryPointPos("bonfire_fire"), Vector(0, 0, 0), true);
    // sounds
    if (!m_SoundFireLoop)
      PlaySoundSetLoop(m_SoundFireLoop, "HeavyFire_SoundSet", 1.0, 2.0);
#endif
    if (GetGame().IsServer() || !GetGame().IsMultiplayer())
    {
      m_UTSSettings = new UniversalTemperatureSourceSettings();
      m_UTSSettings.m_UpdateInterval = TIMER_HEATING_UPDATE_INTERVAL;
      m_UTSSettings.m_Updateable = true;
      m_UTSSettings.m_TemperatureMin = 0;
      m_UTSSettings.m_TemperatureMax = CONST_FIRE_TEMP;
      m_UTSSettings.m_TemperatureCap = PARAM_MAX_TRANSFERED_TEMPERATURE;
      m_UTSSettings.m_RangeFull = PARAM_FULL_HEAT_RADIUS;
      m_UTSSettings.m_RangeMax = PARAM_HEAT_RADIUS;
      m_UTSLBonfire = new UniversalTemperatureSourceLambdaConstant();
      m_UTSource = new UniversalTemperatureSource(this, m_UTSSettings, m_UTSLBonfire);
      m_UTSource.SetActive(true);
    }
  }
References ParticleList::BONFIRE_FIRE, ParticleList::BONFIRE_SMOKE, GetGame(), PointLightBase::m_FireBrightness, PointLightBase::m_FireRadius, m_Light, PointLightBase::m_MemoryPoint, m_ParticleSmoke, m_SoundFireLoop, m_UTSource, m_UTSSettings, PARAM_FULL_HEAT_RADIUS, PARAM_HEAT_RADIUS, PARAM_MAX_TRANSFERED_TEMPERATURE, ParticleManager(), TIMER_HEATING_UPDATE_INTERVAL, and Vector().
GetLiquidThroughputCoef() [1/2]
override float BuildingSuper::GetLiquidThroughputCoef () inline private
Definition at line 13 of file FuelStation.c.
  {
    return LIQUID_THROUGHPUT_FUELSTATION;
  }
References LIQUID_THROUGHPUT_FUELSTATION.
GetLiquidThroughputCoef() [2/2]
override float BuildingSuper::GetLiquidThroughputCoef () inline private
Definition at line 18 of file Well.c.
  {
    return LIQUID_THROUGHPUT_WELL;
  }
References LIQUID_THROUGHPUT_WELL.
GetWaterSourceObjectType()
override EWaterSourceObjectType BuildingSuper::GetWaterSourceObjectType () inline private
Definition at line 13 of file Well.c.
  {
    return EWaterSourceObjectType.WELL;
  }
IsBuilding() [1/2]
override bool BuildingSuper::IsBuilding () inline private
Definition at line 3 of file FuelStation.c.
  {
    return false;
  }
IsBuilding() [2/2]
override bool BuildingSuper::IsBuilding () inline private
Definition at line 3 of file Well.c.
  {
    return false;
  }
IsFuelStation()
override bool BuildingSuper::IsFuelStation () inline private
Definition at line 8 of file FuelStation.c.
  {
    return true;
  }
IsWell()
override bool BuildingSuper::IsWell () inline private
Definition at line 8 of file Well.c.
  {
    return GetWaterSourceObjectType() == EWaterSourceObjectType.WELL;
  }
Land_Misc_Greenhouse()
void BuildingSuper::Land_Misc_Greenhouse () inline private
Definition at line 3 of file Land_Misc_Greenhouse.c.
  {
  }
SetActions()
override void BuildingSuper::SetActions () inline private
Definition at line 23 of file Well.c.
  {
    super.SetActions();
    AddAction(ActionWashHandsWell);
    AddAction(ActionDrinkWellContinuous);
  }
References ActionDrinkWellContinuous(), ActionWashHandsWell(), and AddAction().
Member Data Documentation
CONST_FIRE_TEMP
const float BuildingSuper::CONST_FIRE_TEMP = 1000 private
maximum value for temperature that will be transfered to player (environment)
Definition at line 7 of file Bonfire.c.
m_BonfireHeatingTimer
ref Timer BuildingSuper::m_BonfireHeatingTimer protected
Definition at line 15 of file Bonfire.c.
m_Light
BonfireLight BuildingSuper::m_Light protected
Definition at line 9 of file Bonfire.c.
m_ParticleFire
Particle BuildingSuper::m_ParticleFire protected
Definition at line 10 of file Bonfire.c.
m_ParticleSmoke
Particle BuildingSuper::m_ParticleSmoke protected
Definition at line 11 of file Bonfire.c.
m_SoundFireLoop
EffectSound BuildingSuper::m_SoundFireLoop protected
Definition at line 12 of file Bonfire.c.
m_UTSLBonfire
ref UniversalTemperatureSourceLambdaConstant BuildingSuper::m_UTSLBonfire protected
Definition at line 20 of file Bonfire.c.
m_UTSource
ref UniversalTemperatureSource BuildingSuper::m_UTSource protected
DEPRECATED.
Definition at line 18 of file Bonfire.c.
m_UTSSettings
ref UniversalTemperatureSourceSettings BuildingSuper::m_UTSSettings protected
Definition at line 19 of file Bonfire.c.
PARAM_FULL_HEAT_RADIUS
const float BuildingSuper::PARAM_FULL_HEAT_RADIUS = 5 private
Definition at line 5 of file Bonfire.c.
PARAM_HEAT_RADIUS
const float BuildingSuper::PARAM_HEAT_RADIUS = 15 private
Definition at line 4 of file Bonfire.c.
PARAM_MAX_TRANSFERED_TEMPERATURE
const float BuildingSuper::PARAM_MAX_TRANSFERED_TEMPERATURE = 25 private
Definition at line 6 of file Bonfire.c.
TIMER_HEATING_UPDATE_INTERVAL
const float BuildingSuper::TIMER_HEATING_UPDATE_INTERVAL = 2 private
Definition at line 3 of file Bonfire.c.
The documentation for this class was generated from the following files:
scripts/4_World/Entities/Building/BuildingWithFireplace.c
scripts/4_World/Entities/Building/Specific/Bonfire.c
scripts/4_World/Entities/Building/FuelStation.c
scripts/4_World/Entities/Building/Residential/Misc/Land_Misc_Greenhouse.c
scripts/4_World/Entities/Building/Well.c