DayZ: Clothing_Base Class Reference
Clothing_Base Class Reference
Private Member Functions
override bool IsClothing ()
override bool CanHaveWetness ()
int GetGlassesEffectID ()
Used for 'glasses' (and other colored layers triggered by attach/detach in the InventorySlots.EYEWEAR)
array< int > GetEffectWidgetTypes ()
override bool CanPutInCargo (EntityAI parent)
bool CanPutInCargoClothingConditions (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
bool CanReceiveItemIntoCargoClothingConditions (EntityAI item)
bool SmershException (EntityAI hierarchyParent)
override bool CanLoadItemIntoCargo (EntityAI item)
bool CanLoadItemIntoCargoClothingConditions (EntityAI item)
bool CanWearUnderMask (EntityAI parent)
deprecated
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void SwitchItemSelectionTextureEx (EItemManipulationContext context, Param par=null)
Detailed Description
Definition at line 4 of file Clothing_Base.c.
Member Function Documentation
CanHaveWetness()
override bool Clothing_Base::CanHaveWetness () inline private
Definition at line 11 of file Clothing_Base.c.
  {
    return true;
  }
CanLoadItemIntoCargo()
override bool Clothing_Base::CanLoadItemIntoCargo (EntityAI item) inline private
Definition at line 85 of file Clothing_Base.c.
  {
    if (!super.CanLoadItemIntoCargo(item))
      return false;
    return CanLoadItemIntoCargoClothingConditions(item);
  }
CanLoadItemIntoCargoClothingConditions()
bool Clothing_Base::CanLoadItemIntoCargoClothingConditions (EntityAI item) inline private
Definition at line 93 of file Clothing_Base.c.
  {
    EntityAI parent = GetHierarchyParent();
    if (parent && parent.IsInherited(UndergroundStash))
      return true;
    return !parent || parent.IsMan() || SmershException(parent);
  }
References EntityAI::IsMan().
CanPutInCargo()
override bool Clothing_Base::CanPutInCargo (EntityAI parent) inline private
Definition at line 30 of file Clothing_Base.c.
  {
    if (!super.CanPutInCargo(parent))
      return false;
    return !parent || CanPutInCargoClothingConditions(parent);
  }
CanPutInCargoClothingConditions()
bool Clothing_Base::CanPutInCargoClothingConditions (EntityAI parent) inline private
Definition at line 38 of file Clothing_Base.c.
  {
    bool is_hidden_stash_exception = false;
    if (parent.IsInherited(UndergroundStash))
      is_hidden_stash_exception = true;
    if (GetNumberOfItems() == 0 || !parent || parent.IsMan() || is_hidden_stash_exception)
    {
      EntityAI cargoParent = parent.GetHierarchyParent();
      ClothingBase parentClothing = ClothingBase.Cast(parent);
      if (cargoParent)
        return !(parent.IsClothing() && cargoParent.IsClothing()) || (parentClothing && parentClothing.SmershException(cargoParent));
      return true;
    }
    return false;
  }
References GetNumberOfItems(), and EntityAI::IsMan().
CanReceiveItemIntoCargo()
override bool Clothing_Base::CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 58 of file Clothing_Base.c.
  {
    if (!super.CanReceiveItemIntoCargo(item))
      return false;
    return CanReceiveItemIntoCargoClothingConditions(item);
  }
CanReceiveItemIntoCargoClothingConditions()
bool Clothing_Base::CanReceiveItemIntoCargoClothingConditions (EntityAI item) inline private
Definition at line 66 of file Clothing_Base.c.
  {
    EntityAI hierarchyParent = GetHierarchyParent();
    return !hierarchyParent || hierarchyParent.IsMan() || SmershException(hierarchyParent);
  }
CanWearUnderMask()
bool Clothing_Base::CanWearUnderMask (EntityAI parent) inline private
deprecated
Definition at line 105 of file Clothing_Base.c.
  {
    return true;
  }
EEHealthLevelChanged()
override void Clothing_Base::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 111 of file Clothing_Base.c.
  {
    super.EEHealthLevelChanged(oldLevel, newLevel, zone);
    if (!GetGame().IsDedicatedServer())
    {
      PlayerBase player_owner = PlayerBase.Cast(GetHierarchyParent());
      if (player_owner)
      {
        if (player_owner.m_CorpseState != 0)
          GetGame().GetCallQueue(CALL_CATEGORY_GUI).CallLater(player_owner.UpdateCorpseState, 0, false);
      }
    }
  }
References CALL_CATEGORY_GUI, and GetGame().
GetEffectWidgetTypes()
array< int > Clothing_Base::GetEffectWidgetTypes () inline private
Definition at line 24 of file Clothing_Base.c.
  {
    return null;
  }
GetGlassesEffectID()
int Clothing_Base::GetGlassesEffectID () inline private
Used for 'glasses' (and other colored layers triggered by attach/detach in the InventorySlots.EYEWEAR)
Definition at line 17 of file Clothing_Base.c.
  {
    return -1;
  }
IsClothing()
override bool Clothing_Base::IsClothing () inline private
Definition at line 6 of file Clothing_Base.c.
  {
    return true;
  }
SmershException()
bool Clothing_Base::SmershException (EntityAI hierarchyParent) inline private
Definition at line 73 of file Clothing_Base.c.
  {
    EntityAI hp = hierarchyParent.GetHierarchyParent();
    if (hp)
    {
      if (!hp.IsMan())
        return false;
    }
    return IsInherited(SmershBag) && hierarchyParent.IsInherited(SmershVest);
  }
SwitchItemSelectionTextureEx()
override void Clothing_Base::SwitchItemSelectionTextureEx (EItemManipulationContext context, Param par = null) inline private
Definition at line 126 of file Clothing_Base.c.
  {
    super.SwitchItemSelectionTextureEx(context, par);
    Param1<PlayerBase> data = Param1<PlayerBase>.Cast(par);
    if (!data)
      return;
    PlayerBase player = data.param1;
    int personality = GetHiddenSelectionIndex("personality");
    if (personality >= 0)
    {
      string tone_mat = player.m_EmptyGloves.GetHiddenSelectionsMaterials().Get(0);
      string tone_texture;
      if (player.m_CorpseState > PlayerConstants.CORPSE_STATE_FRESH)
        tone_texture = player.m_DecayedTexture;
      else
        tone_texture = player.m_EmptyGloves.GetHiddenSelectionsTextures().Get(0);
      SetObjectMaterial(personality, tone_mat);
      SetObjectTexture(personality, tone_texture);
    }
  }
References PlayerConstants::CORPSE_STATE_FRESH.
The documentation for this class was generated from the following file:
scripts/4_World/Entities/ItemBase/Clothing_Base.c