DayZ: AIBehaviourHLDataZombie2 Class Reference
AIBehaviourHLDataZombie2 Class Reference
Private Member Functions
void AIBehaviourHLDataZombie2 ()
void ~AIBehaviourHLDataZombie2 ()
override void OnParseConfig ()
Private Attributes
float m_fDamageToCrawl
float m_fCrawlProbability
Detailed Description
Definition at line 116 of file AIBehaviour.c.
Constructor & Destructor Documentation
AIBehaviourHLDataZombie2()
void AIBehaviourHLDataZombie2::AIBehaviourHLDataZombie2 () inline private
Definition at line 121 of file AIBehaviour.c.
{}
~AIBehaviourHLDataZombie2()
void AIBehaviourHLDataZombie2::~AIBehaviourHLDataZombie2 () inline private
Definition at line 122 of file AIBehaviour.c.
{}
Member Function Documentation
OnParseConfig()
override void AIBehaviourHLDataZombie2::OnParseConfig () inline private
Definition at line 124 of file AIBehaviour.c.
  {
    Print("zombie data parse config start");
    ParseBehaviourSlot("Calm");
    ParseBehaviourSlot("Attracted");
    ParseBehaviourSlot("Disturbed");
    ParseBehaviourSlot("Alerted");
    ParseAlertLevel("Calm");
    ParseAlertLevel("Disturbed");
    ParseAlertLevel("Attracted");
    ParseAlertLevel("Alerted");
    m_fDamageToCrawl = ReadParamValue("damageToCrawl", 0.01);
    m_fCrawlProbability = ReadParamValue("crawlProbability", 0.01);
    Print("zombie data parse config end");
  }
References m_fCrawlProbability, m_fDamageToCrawl, AIBehaviourHLData::ParseAlertLevel(), AIBehaviourHLData::ParseBehaviourSlot(), Print(), and AIBehaviourHLData::ReadParamValue().
Member Data Documentation
m_fCrawlProbability
float AIBehaviourHLDataZombie2::m_fCrawlProbability private
Definition at line 119 of file AIBehaviour.c.
Referenced by OnParseConfig().
m_fDamageToCrawl
float AIBehaviourHLDataZombie2::m_fDamageToCrawl private
Definition at line 118 of file AIBehaviour.c.
Referenced by OnParseConfig().
The documentation for this class was generated from the following file:
scripts/3_Game/AIBehaviour.c