DayZ: HandGuardBase Class Reference
HandGuardBase Class Reference
TODO(kumarjac): This guard is unused but it has a fault and doesn't conform with maximimal/minimal checks on "Juncture"/"Remote".
Protected Member Functions
void HandGuardHasItemInEvent (Man p=null)
override bool GuardCondition (HandEventBase e)
void HandGuardIsSameItemInHands (Man p=null)
override bool GuardCondition (HandEventBase e)
void HandGuardHasDestroyedItemInHands (Man p=null)
override bool GuardCondition (HandEventBase e)
void HandGuardHasItemInHands (Man p=null)
override bool GuardCondition (HandEventBase e)
void HandGuardHasRoomForItem (Man p=null)
override bool GuardCondition (HandEventBase e)
void HandGuardCanMove (Man p=null)
override bool GuardCondition (HandEventBase e)
void HandGuardCanSwap (Man p=NULL)
override bool GuardCondition (HandEventBase e)
void HandGuardCanForceSwap (Man p=NULL)
override bool GuardCondition (HandEventBase e)
void HandGuardInstantForceSwap (Man p=NULL)
override bool GuardCondition (HandEventBase e)
void HandSelectAnimationOfMoveFromHandsEvent (Man p=null)
override bool GuardCondition (HandEventBase e)
void HandSelectAnimationOfForceSwapInHandsEvent (Man p=NULL)
bool ProcessSwapEvent (notnull HandEventBase e, out int animType1, out int animType2)
override bool GuardCondition (HandEventBase e)
void BotGuardHasItemInHands (Man p=NULL)
override bool GuardCondition (HandEventBase e)
Protected Attributes
Man m_Player
Private Member Functions
bool GuardCondition (HandEventBase e)
void HandGuardAnd (HandGuardBase arg0=null, HandGuardBase arg1=null)
override bool GuardCondition (HandEventBase e)
void HandGuardNot (HandGuardBase arg0=null)
override bool GuardCondition (HandEventBase e)
void HandGuardOr (HandGuardBase arg0=null, HandGuardBase arg1=null)
override bool GuardCondition (HandEventBase e)
void HandSelectAnimationOfTakeToHandsEvent (Man p=null)
override bool GuardCondition (HandEventBase e)
Private Attributes
ref HandGuardBase m_arg0
ref HandGuardBase m_arg1
Detailed Description
TODO(kumarjac): This guard is unused but it has a fault and doesn't conform with maximimal/minimal checks on "Juncture"/"Remote".
guards
represents guard on a transition from state to state
Definition at line 6 of file Hand_Guards.c.
Member Function Documentation
BotGuardHasItemInHands()
void HandGuardBase::BotGuardHasItemInHands (Man p = NULL) inline protected
Definition at line 61 of file BotGuards.c.
{ m_Player = p; }
References m_Player.
GuardCondition() [1/17]
bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 14 of file Hand_Guards.c.
{ return true; }
GuardCondition() [2/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 25 of file Hand_Guards.c.
  {
    bool result = m_arg0.GuardCondition(e) && m_arg1.GuardCondition(e);
#ifdef DEVELOPER
    if (LogManager.IsInventoryHFSMLogEnable())
      Debug.InventoryHFSMLog("GuardCondition result: " + result + " - " + m_arg0.Type() + " && " + m_arg1.Type(), "HandGuardAnd", "n/a", "GuardCondition", e.m_Player.ToString());
#endif
    return result;
  }
References Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
GuardCondition() [3/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 44 of file Hand_Guards.c.
  {
    bool result = !m_arg0.GuardCondition(e);
#ifdef DEVELOPER
    if (LogManager.IsInventoryHFSMLogEnable())
      Debug.InventoryHFSMLog("GuardCondition result: " + result + " - " + m_arg0.Type(), "HandGuardNot", "n/a", "GuardCondition", e.m_Player.ToString());
#endif
    return result;
  }
References Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
GuardCondition() [4/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 63 of file Hand_Guards.c.
  {
    bool result = m_arg0.GuardCondition(e) || m_arg1.GuardCondition(e);
#ifdef DEVELOPER
    if (LogManager.IsInventoryHFSMLogEnable())
      Debug.InventoryHFSMLog("GuardCondition result: " + result + " - " + m_arg0.Type() + " || " + m_arg1.Type(), "HandGuardOr", "n/a", "GuardCondition", e.m_Player.ToString());
#endif
    return result;
  }
References Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
GuardCondition() [5/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline protected
Definition at line 80 of file Hand_Guards.c.
  {
    EntityAI eai = e.GetSrcEntity();
    if (eai != NULL /* && CanTakeInHands*/)
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryHFSMLogEnable())
        Debug.InventoryHFSMLog("GuardCondition result: true - " + eai, "HandGuardHasItemInEvent", "n/a", "GuardCondition", m_Player.ToString());
#endif
      return true;
    }
#ifdef DEVELOPER
    if (LogManager.IsInventoryHFSMLogEnable())
      Debug.InventoryHFSMLog("GuardCondition result: false - " + eai, "HandGuardHasItemInEvent", "n/a", "GuardCondition", m_Player.ToString());
#endif
    return false;
  }
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [6/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline protected
Definition at line 127 of file Hand_Guards.c.
  {
    bool result = false;
    if (e.GetSrcEntity() == m_Player.GetHumanInventory().GetEntityInHands())
      result = true;
#ifdef DEVELOPER
    if (LogManager.IsInventoryHFSMLogEnable())
      Debug.InventoryHFSMLog("GuardCondition result: " + result + " - srcItem = " + e.GetSrcEntity() + " hnd= " + m_Player.GetHumanInventory().GetEntityInHands(), "HandGuardIsSameItemInHands", "n/a", "GuardCondition", e.m_Player.ToString());
#endif
    return result;
  }
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [7/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline protected
Definition at line 146 of file Hand_Guards.c.
  {
    EntityAI hnd = m_Player.GetHumanInventory().GetEntityInHands();
    if (e.GetSrcEntity())
    {
      if (e.GetSrcEntity() == hnd)
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryHFSMLogEnable())
          Debug.InventoryHFSMLog("GuardCondition result: true - has same entity in hands " + hnd, "HandGuardHasDestroyedItemInHands", "n/a", "GuardCondition", m_Player.ToString());
#endif
        return true;
      }
      if (hnd == null)
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryHFSMLogEnable())
          Debug.InventoryHFSMLog("GuardCondition result: true - hands already empty", "HandGuardHasDestroyedItemInHands", "n/a", "GuardCondition", m_Player.ToString());
#endif
        return true;
      }
    }
    else
    {
#ifdef DEVELOPER
      if (LogManager.IsInventoryHFSMLogEnable())
        Debug.InventoryHFSMLog("GuardCondition result: true - hands already empty and item destroyed", "HandGuardHasDestroyedItemInHands", "n/a", "GuardCondition", m_Player.ToString());
#endif
      return true;
    }
#ifdef DEVELOPER
    if (LogManager.IsInventoryHFSMLogEnable())
      Debug.InventoryHFSMLog("GuardCondition result: false -  destroyed entity not in hands", "HandGuardHasDestroyedItemInHands", "n/a", "GuardCondition", m_Player.ToString());
#endif
    return false;
  }
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [8/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline protected
Definition at line 190 of file Hand_Guards.c.
  {
    bool result = false;
    if (m_Player.GetHumanInventory().GetEntityInHands())
      result = true;
#ifdef DEVELOPER
    if (LogManager.IsInventoryHFSMLogEnable())
      Debug.InventoryHFSMLog("GuardCondition result: " + result + " - " + m_Player.GetHumanInventory().GetEntityInHands(), "HandGuardHasItemInHands", "n/a", "GuardCondition", m_Player.ToString());
#endif
    return result;
  }
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [9/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline protected
Definition at line 210 of file Hand_Guards.c.
  {
    if (e.GetDst() && e.GetDst().IsValid())
    {
      if (!GetGame().IsDedicatedServer())
      {
        if (m_Player)
          m_Player.GetHumanInventory().ClearInventoryReservationEx(e.GetDst().GetItem(), e.GetDst());
      }
      if (!GameInventory.LocationTestAddEntity(e.GetDst(), false, true, true, true, true, false))
      {
#ifdef DEVELOPER
        if (LogManager.IsInventoryHFSMLogEnable())
          Debug.InventoryHFSMLog("GuardCondition result: false - no room at dst=" + InventoryLocation.DumpToStringNullSafe(e.GetDst()), "HandGuardHasRoomForItem", "n/a", "GuardCondition", m_Player.ToString());
#endif
        //if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[hndfsm] HandGuardHasRoomForItem - no room at dst=" + InventoryLocation.DumpToStringNullSafe(e.GetDst()));
        //Error("[hndfsm] HandGuardHasRoomForItem - no room at dst=" + InventoryLocation.DumpToStringNullSafe(e.GetDst()));
        return false;
      }
      if (!GetGame().IsDedicatedServer())
      {
        if (m_Player)
          m_Player.GetHumanInventory().AddInventoryReservationEx(e.GetDst().GetItem(), e.GetDst(), GameInventory.c_InventoryReservationTimeoutShortMS);
      }
#ifdef DEVELOPER
      if (LogManager.IsInventoryHFSMLogEnable())
        Debug.InventoryHFSMLog("GuardCondition result: true", "HandGuardHasRoomForItem", "n/a", "GuardCondition", m_Player.ToString());
#endif
      return true;
    }
#ifdef DEVELOPER
    if (LogManager.IsInventoryHFSMLogEnable())
      Debug.InventoryHFSMLog("GuardCondition result: false - e.m_Dst is null", "HandGuardHasRoomForItem", "n/a", "GuardCondition", m_Player.ToString());
#endif
    return false;
  }
References GameInventory::c_InventoryReservationTimeoutShortMS, InventoryLocation::DumpToStringNullSafe(), GetGame(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), GameInventory::LocationTestAddEntity(), and m_Player.
GuardCondition() [10/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline protected
Definition at line 259 of file Hand_Guards.c.
  {
    HandEventMoveTo es = HandEventMoveTo.Cast(e);
    bool result = e.m_IsJuncture || e.m_IsRemote;
    if (result == false)
      result = GameInventory.LocationCanMoveEntity(es.GetSrc(), es.GetDst());
#ifdef DEVELOPER
    if (LogManager.IsInventoryHFSMLogEnable())
      Debug.InventoryHFSMLog("GuardCondition result: " + result, "HandGuardCanMove", "n/a", "GuardCondition", m_Player.ToString());
#endif
    return result;
  }
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), GameInventory::LocationCanMoveEntity(), and m_Player.
GuardCondition() [11/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline protected
Definition at line 281 of file Hand_Guards.c.
  {
    HandEventSwap es = HandEventSwap.Cast(e);
    bool result = e.m_IsJuncture || e.m_IsRemote;
    if (result == false)
      result = GameInventory.CanSwapEntitiesEx(es.GetSrc().GetItem(), es.m_Src2.GetItem());
#ifdef DEVELOPER
    if (LogManager.IsInventoryHFSMLogEnable())
      Debug.InventoryHFSMLog("GuardCondition result: " + result, "HandGuardCanSwap", "n/a", "GuardCondition", m_Player.ToString());
#endif
    //if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[hndfsm] HandGuardCanSwap guard - cannot swap");
    return result;
  }
References GameInventory::CanSwapEntitiesEx(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [12/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline protected
Definition at line 303 of file Hand_Guards.c.
  {
    HandEventForceSwap es = HandEventForceSwap.Cast(e);
    bool result = e.m_IsJuncture || e.m_IsRemote;
    if (result == false)
    {
      result = GameInventory.CanSwapEntitiesEx(es.GetSrc().GetItem(), es.m_Src2.GetItem());
      if (result == false && es.m_Dst2)
        result = GameInventory.CanForceSwapEntitiesEx(es.GetSrc().GetItem(), es.m_Dst, es.m_Src2.GetItem(), es.m_Dst2);
    }
#ifdef DEVELOPER
    if (LogManager.IsInventoryHFSMLogEnable())
      Debug.InventoryHFSMLog("GuardCondition result: " + result, "HandGuardCanForceSwap", "n/a", "GuardCondition", m_Player.ToString());
#endif
    return result;
  }
References GameInventory::CanForceSwapEntitiesEx(), GameInventory::CanSwapEntitiesEx(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [13/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline protected
Definition at line 330 of file Hand_Guards.c.
  {
    HandEventForceSwap es = HandEventForceSwap.Cast(e);
    InventoryLocation src1 = es.m_Src;
    InventoryLocation dst2 = es.m_Dst2;
    bool result = false;
    if (src1.GetType() == InventoryLocationType.CARGO && dst2.GetType() == InventoryLocationType.CARGO)
    {
      if (src1.GetParent() == dst2.GetParent())
        result = true;
    }
#ifdef DEVELOPER
    if (LogManager.IsInventoryHFSMLogEnable())
      Debug.InventoryHFSMLog("GuardCondition result: " + result, "HandGuardInstantForceSwap", "n/a", "GuardCondition", m_Player.ToString());
#endif
    return result;
  }
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [14/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 171 of file HandAnimated_Guards.c.
  {
    int animType = -1;
    if (SelectAnimationOfTakeToHands(e.m_Player, e.GetSrc(), e.GetDst(), animType))
    {
      e.m_AnimationID = animType;
      return true;
    }
    return false;
  }
References SelectAnimationOfTakeToHands().
GuardCondition() [15/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline protected
Definition at line 192 of file HandAnimated_Guards.c.
  {
    EntityAI eai = m_Player.GetHumanInventory().GetEntityInHands();
    if (eai)
    {
      InventoryLocation src = new InventoryLocation;
      if (eai.GetInventory().GetCurrentInventoryLocation(src))
      {
        if (e.m_IsJuncture == false && e.m_IsRemote == false)
        {
          if (!GameInventory.LocationCanMoveEntity(src, e.GetDst()))
          {
            if (LogManager.IsInventoryHFSMLogEnable())
              hndDebugPrint("[hndfsm] HandSelectAnimationOfMoveFromHandsEvent - rejected");
            return false;
          }
        }
        int animType = -1;
        if (SelectAnimationOfMoveFromHands(e.m_Player, src, e.GetDst(), animType))
        {
          e.m_AnimationID = animType;
          return true;
        }
        return false;
      }
    }
    return false;
  }
References hndDebugPrint(), LogManager::IsInventoryHFSMLogEnable(), GameInventory::LocationCanMoveEntity(), m_Player, and SelectAnimationOfMoveFromHands().
GuardCondition() [16/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline protected
Definition at line 239 of file HandAnimated_Guards.c.
  {
    HandEventForceSwap es = HandEventForceSwap.Cast(e);
    if (es)
    {
      if (LogManager.IsInventoryHFSMLogEnable())
        hndDebugPrint("[hndfsm] HandSelectAnimationOfForceSwapInHandsEvent FSwap e=" + e.DumpToString());
      if (!es.m_Src2.IsValid() || !es.m_Src.IsValid())
      {
        Error("[hndfsm] HandSelectAnimationOfForceSwapInHandsEvent - invalid item source");
        return false;
      }
      bool allow = e.m_IsJuncture || e.m_IsRemote;
      if (allow == false)
      {
        if (GameInventory.CanSwapEntitiesEx(es.GetSrc().GetItem(), es.m_Src2.GetItem()))
        {
          allow = true; // allow if ordinary swap
        }
        else if (es.m_Dst2)
        {
          if (GameInventory.CanForceSwapEntitiesEx(es.GetSrc().GetItem(), es.m_Dst, es.m_Src2.GetItem(), es.m_Dst2) == false)
            Error("[hndfsm] HandSelectAnimationOfForceSwapInHandsEvent - no room at dst=" + InventoryLocation.DumpToStringNullSafe(es.m_Dst2));
          else
            allow = true;
        }
      }
      if (allow)
      {
        int animType1 = -1;
        int animType2 = -1;
        if (ProcessSwapEvent(e, animType1, animType2))
        {
          e.m_AnimationID = animType1;
          es.m_Animation2ID = animType2;
          return true;
        }
      }
      else
        Error("[hndfsm] HandSelectAnimationOfForceSwapInHandsEvent - m_HasRoomGuard.GuardCondition failed");
    }
    else
      Error("[hndfsm] HandSelectAnimationOfForceSwapInHandsEvent - not a swap event");
    return false;
  }
References GameInventory::CanForceSwapEntitiesEx(), GameInventory::CanSwapEntitiesEx(), InventoryLocation::DumpToStringNullSafe(), Error(), hndDebugPrint(), and LogManager::IsInventoryHFSMLogEnable().
GuardCondition() [17/17]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline protected
Definition at line 63 of file BotGuards.c.
  {
    if (m_Player.GetHumanInventory().GetEntityInHands())
    {
      if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[botfsm] guard - has valid entity in hands");
      return true;
    }
    if (LogManager.IsInventoryHFSMLogEnable()) hndDebugPrint("[botfsm] guard - no entity in hands");
    return false;
  }
References hndDebugPrint(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
HandGuardAnd()
void HandGuardBase::HandGuardAnd (HandGuardBase arg0 = null, HandGuardBase arg1 = null) inline private
Definition at line 23 of file Hand_Guards.c.
{ m_arg0 = arg0; m_arg1 = arg1; }
HandGuardCanForceSwap()
void HandGuardBase::HandGuardCanForceSwap (Man p = NULL) inline protected
Definition at line 301 of file Hand_Guards.c.
{ m_Player = p; }
References m_Player.
HandGuardCanMove()
void HandGuardBase::HandGuardCanMove (Man p = null) inline protected
Definition at line 257 of file Hand_Guards.c.
{ m_Player = p; }
References m_Player.
HandGuardCanSwap()
void HandGuardBase::HandGuardCanSwap (Man p = NULL) inline protected
Definition at line 279 of file Hand_Guards.c.
{ m_Player = p; }
References m_Player.
HandGuardHasDestroyedItemInHands()
void HandGuardBase::HandGuardHasDestroyedItemInHands (Man p = null) inline protected
Definition at line 144 of file Hand_Guards.c.
{ m_Player = p; }
References m_Player.
HandGuardHasItemInEvent()
void HandGuardBase::HandGuardHasItemInEvent (Man p = null) inline protected
Definition at line 78 of file Hand_Guards.c.
{ m_Player = p; }
References m_Player.
HandGuardHasItemInHands()
void HandGuardBase::HandGuardHasItemInHands (Man p = null) inline protected
Definition at line 188 of file Hand_Guards.c.
{ m_Player = p; }
References m_Player.
HandGuardHasRoomForItem()
void HandGuardBase::HandGuardHasRoomForItem (Man p = null) inline protected
Definition at line 208 of file Hand_Guards.c.
{ m_Player = p; }
References m_Player.
HandGuardInstantForceSwap()
void HandGuardBase::HandGuardInstantForceSwap (Man p = NULL) inline protected
Definition at line 328 of file Hand_Guards.c.
{ m_Player = p; }
References m_Player.
HandGuardIsSameItemInHands()
void HandGuardBase::HandGuardIsSameItemInHands (Man p = null) inline protected
Definition at line 125 of file Hand_Guards.c.
{ m_Player = p; }
References m_Player.
HandGuardNot()
void HandGuardBase::HandGuardNot (HandGuardBase arg0 = null) inline private
Definition at line 42 of file Hand_Guards.c.
{ m_arg0 = arg0; }
HandGuardOr()
void HandGuardBase::HandGuardOr (HandGuardBase arg0 = null, HandGuardBase arg1 = null) inline private
Definition at line 61 of file Hand_Guards.c.
{ m_arg0 = arg0; m_arg1 = arg1; }
HandSelectAnimationOfForceSwapInHandsEvent()
void HandGuardBase::HandSelectAnimationOfForceSwapInHandsEvent (Man p = NULL) inline protected
Definition at line 228 of file HandAnimated_Guards.c.
{ m_Player = p; }
References m_Player.
HandSelectAnimationOfMoveFromHandsEvent()
void HandGuardBase::HandSelectAnimationOfMoveFromHandsEvent (Man p = null) inline protected
Definition at line 187 of file HandAnimated_Guards.c.
  {
    m_Player = p;
  }
References m_Player.
HandSelectAnimationOfTakeToHandsEvent()
void HandGuardBase::HandSelectAnimationOfTakeToHandsEvent (Man p = null) inline private
Definition at line 169 of file HandAnimated_Guards.c.
{ }
ProcessSwapEvent()
bool HandGuardBase::ProcessSwapEvent (notnull HandEventBase e, out int animType1, out int animType2) inline protected
Definition at line 230 of file HandAnimated_Guards.c.
  {
    HandEventSwap es = HandEventSwap.Cast(e);
    if (es)
      return SelectAnimationOfForceSwapInHands(e.m_Player, es.m_Src, es.m_Src2, es.m_Dst, es.m_Dst2, animType1, animType2);
    Error("HandSelectAnimationOfForceSwapInHandsEvent - not an swap event");
    return false;
  }
References Error(), and SelectAnimationOfForceSwapInHands().
Member Data Documentation
m_arg0
ref HandGuardBase HandGuardBase::m_arg0 private
Definition at line 20 of file Hand_Guards.c.
m_arg1
ref HandGuardBase HandGuardBase::m_arg1 private
Definition at line 21 of file Hand_Guards.c.
m_Player
Man HandGuardBase::m_Player protected
Definition at line 77 of file Hand_Guards.c.
The documentation for this class was generated from the following files:
scripts/3_Game/Systems/Inventory/Hand_Guards.c
scripts/3_Game/Systems/Inventory/HandAnimated_Guards.c
scripts/4_World/Systems/Bot/BotGuards.c