DayZ: CAContinuousWaterPlant Class Reference
CAContinuousWaterPlant Class Reference
Protected Member Functions
void CAContinuousWaterPlant (float quantity_used_per_second)
override void Setup (ActionData action_data)
override int Execute (ActionData action_data)
override float GetProgress ()
Protected Attributes
float m_PlantThirstyness
float m_TimeToComplete
Additional Inherited Members
Private Member Functions inherited from CAContinuousQuantity
void CAContinuousQuantity (float quantity_used_per_second)
override void Setup (ActionData action_data)
override int Execute (ActionData action_data)
override int Cancel (ActionData action_data)
override float GetProgress ()
void CalcAndSetQuantity (ActionData action_data)
Private Attributes inherited from CAContinuousQuantity
float m_ItemQuantity
float m_SpentQuantity
float m_ItemMaxQuantity
float m_QuantityUsedPerSecond
float m_AdjustedQuantityUsedPerSecond
ref Param1< float > m_SpentUnits
Detailed Description
Definition at line 1 of file CAContinuousWaterPlant.c.
Constructor & Destructor Documentation
CAContinuousWaterPlant()
void CAContinuousWaterPlant::CAContinuousWaterPlant (float quantity_used_per_second) inline protected
Definition at line 6 of file CAContinuousWaterPlant.c.
  {
    m_QuantityUsedPerSecond = quantity_used_per_second;
  }
References CAContinuousQuantity::m_QuantityUsedPerSecond.
Member Function Documentation
Execute()
override int CAContinuousWaterPlant::Execute (ActionData action_data) inline protected
Definition at line 30 of file CAContinuousWaterPlant.c.
  {
    if (!action_data.m_Player)
      return UA_ERROR;
    if (m_ItemQuantity <= 0)
      return UA_FINISHED;
    else
    {
      if (m_SpentQuantity < m_ItemQuantity && m_SpentQuantity < m_PlantThirstyness)
      {
        m_AdjustedQuantityUsedPerSecond = action_data.m_Player.GetSoftSkillsManager().AddSpecialtyBonus(m_QuantityUsedPerSecond, m_Action.GetSpecialtyWeight(), true);
        m_SpentQuantity += m_QuantityUsedPerSecond * action_data.m_Player.GetDeltaT();
        if (m_Action)
        {
          PlantBase plant;
          Class.CastTo(plant, action_data.m_Target.GetObject());
          Slot slot = plant.GetSlot();
          slot.GiveWater(m_SpentQuantity);
        }
        return UA_PROCESSING;
      }
      else
      {
        CalcAndSetQuantity(action_data);
        OnCompletePogress(action_data);
        return UA_FINISHED;
      }
    }
  }
References CalcAndSetQuantity(), Class::CastTo(), CABase::m_Action, CAContinuousQuantity::m_AdjustedQuantityUsedPerSecond, CAContinuousQuantity::m_ItemQuantity, m_PlantThirstyness, CAContinuousQuantity::m_QuantityUsedPerSecond, CAContinuousQuantity::m_SpentQuantity, CAContinuousBase::OnCompletePogress(), UA_ERROR, UA_FINISHED, and UA_PROCESSING.
GetProgress()
override float CAContinuousWaterPlant::GetProgress () inline protected
Definition at line 62 of file CAContinuousWaterPlant.c.
  {
    //float progress = (m_SpentQuantity*m_QuantityUsedPerSecond)/m_TimeToComplete;
    return (m_SpentQuantity * m_QuantityUsedPerSecond) / m_TimeToComplete;
  }
References CAContinuousQuantity::m_QuantityUsedPerSecond, CAContinuousQuantity::m_SpentQuantity, and m_TimeToComplete.
Setup()
override void CAContinuousWaterPlant::Setup (ActionData action_data) inline protected
Definition at line 11 of file CAContinuousWaterPlant.c.
  {
    PlantBase target_PB;
    if (Class.CastTo(target_PB, action_data.m_Target.GetObject()))
    {
      m_SpentQuantity = 0;
      if (!m_SpentUnits)
        m_SpentUnits = new Param1<float>(0);
      else
        m_SpentUnits.param1 = 0;
      if (action_data.m_MainItem)
        m_ItemQuantity = action_data.m_MainItem.GetQuantity();
      if (target_PB)
        m_PlantThirstyness = target_PB.GetWaterMax() - target_PB.GetWater();
      m_TimeToComplete = (Math.Min(m_PlantThirstyness, m_ItemQuantity)) / m_QuantityUsedPerSecond;
    }
  }
References Class::CastTo(), CAContinuousQuantity::m_ItemQuantity, m_PlantThirstyness, CAContinuousQuantity::m_QuantityUsedPerSecond, CAContinuousQuantity::m_SpentQuantity, CAContinuousQuantity::m_SpentUnits, m_TimeToComplete, and Math::Min().
Member Data Documentation
m_PlantThirstyness
float CAContinuousWaterPlant::m_PlantThirstyness protected
Definition at line 3 of file CAContinuousWaterPlant.c.
Referenced by Execute(), and Setup().
m_TimeToComplete
float CAContinuousWaterPlant::m_TimeToComplete protected
Definition at line 4 of file CAContinuousWaterPlant.c.
Referenced by GetProgress(), and Setup().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousWaterPlant.c