DayZ: PPEMatClassParameterColor Class Reference
PPEMatClassParameterColor Class Reference
Private Member Functions
override void ModifyResultValues (inout Param result_values)
Detailed Description
Definition at line 307 of file PPEMatClassParameterColor.c.
Member Function Documentation
ModifyResultValues()
override void PPEMatClassParameterColor::ModifyResultValues (inout Param result_values) inline private
Definition at line 309 of file PPEMatClassParameterColor.c.
  {
    super.ModifyResultValues(result_values);
    //saturation-dependency handling
    Param par = PPEManagerStatic.GetPPEManager().GetPostProcessCurrentValues(PostProcessEffectType.Glow, PPEGlow.PARAM_SATURATION);
    float saturation_coef = Param1<float>.Cast(par).param1;
    float r = Param4<float, float, float, float>.Cast(result_values).param1;
    float g = Param4<float, float, float, float>.Cast(result_values).param2;
    float b = Param4<float, float, float, float>.Cast(result_values).param3;
    float a = Param4<float, float, float, float>.Cast(result_values).param4;
    float highest_channel = Math.Max(Math.Max(r, g), b);
    saturation_coef = Easing.EaseOutSine(saturation_coef);
    r = Math.Lerp(highest_channel, r, saturation_coef);
    g = Math.Lerp(highest_channel, g, saturation_coef);
    b = Math.Lerp(highest_channel, b, saturation_coef);
    a = Math.Lerp(m_ColorDefaults[3], a, saturation_coef);
    //
    Param4<float, float, float, float>.Cast(result_values).param1 = r;
    Param4<float, float, float, float>.Cast(result_values).param2 = g;
    Param4<float, float, float, float>.Cast(result_values).param3 = b;
    Param4<float, float, float, float>.Cast(result_values).param4 = a;
  }
References Easing::EaseOutSine(), PPEManagerStatic::GetPPEManager(), Math::Lerp(), m_ColorDefaults, Math::Max(), and PPEGlow::PARAM_SATURATION.
Referenced by Update().
The documentation for this class was generated from the following file:
scripts/3_Game/PPEManager/Materials/MatParameters/PPEMatClassParameterColor.c