DayZ: RightArea Class Reference
RightArea Class Reference
Protected Member Functions
void RightArea (LayoutHolder parent)
PlayerContainer GetPlayerContainer ()
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
override bool Select ()
override bool SelectItem ()
override bool Combine ()
override bool SplitItem ()
override bool EquipItem ()
override bool TransferItem ()
override bool InspectItem ()
override bool TransferItemToVicinity ()
override void UnfocusGrid ()
override bool CanTakeToInventory ()
override bool CanTakeToInventoryEx (EntityAI focusedEntity)
bool HasEntityContainerVisible (EntityAI entity)
void SwapItemsInOrder (int slot1, int slot2)
bool IsPlayerEquipmentActive ()
override void SetSameLevelNextActive ()
override void SetSameLevelPreviousActive ()
override void ExpandCollapseContainer ()
override void Refresh ()
override void SetLayoutName ()
override void SetParentWidget ()
override void OnShow ()
override void UpdateInterval ()
void MoveUpDownIcons ()
override ScrollWidget GetScrollWidget ()
override void UpdateSelectionIcons ()
float GetCurrentContainerTopY ()
float GetCurrentContainerBottomY ()
Protected Attributes
Widget m_ContentParent
ScrollWidget m_ScrollWidget
Widget m_UpIcon
Widget m_DownIcon
ref SizeToChild m_ContentResize
bool m_ShouldChangeSize = true
bool m_ProcessGridMovement
Private Attributes
ref PlayerContainer m_PlayerContainer
Private Attributes inherited from Container
const int ROWS_NUMBER_XBOX = 5
CargoBase m_Cargo
int m_CargoIndex = -1
int m_FocusedItemPosition = -1
ref array< ref CargoContainerRow > m_Rows
ref array< ref Icon > m_Icons
ref map< EntityAI, ref Param3< ref Icon, int, int > > m_ShowedItemPositions
ref map< EntityAI, ref Param3< ref Icon, int, int > > m_ShowedLockPositions
float m_IconSize
float m_SpaceSize
bool m_IsAttachment
TextWidget m_FalseHeaderTextWidget
TextWidget m_AlternateFalseHeaderTextWidget
Widget m_CargoHeader
Widget m_CargoContainer
Widget m_ItemsContainer
ref SizeToChild m_Resizer1
ref SizeToChild m_Resizer2
ref Timer m_ResizeTimer
ref ClosableHeader m_ClosableHeader
bool m_LockCargo
Additional Inherited Members
Private Member Functions inherited from Container
void CargoContainer (LayoutHolder parent, bool is_attachment=false)
void ~CargoContainer ()
int GetCargoIndex ()
void AddedToCargoEx (EntityAI item, bool refresh=true)
void AddedToCargo (EntityAI item)
void RemovedFromCargo (EntityAI item)
void MovedInCargo (EntityAI item)
void SetLock (EntityAI item)
void ReleaseLock (EntityAI item)
override void SetLayoutName ()
void SetEntity (EntityAI item, int cargo_index=0, bool immedUpdate=true)
EntityAI GetEntity ()
void UpdateHeaderText ()
void InitGridHeight ()
void UpdateSize ()
float GetIconSize ()
float GetSpaceSize ()
int GetCargoCapacity ()
int GetMaxCargoCapacity ()
Icon GetIcon (EntityAI item)
Icon GetIcon (int index)
Icon GetFocusedIcon ()
override float GetFocusedContainerHeight (bool contents=false)
override float GetFocusedContainerYPos (bool contents=false)
override float GetFocusedContainerYScreenPos (bool contents=false)
void UpdateSelection ()
void UpdateRowVisibility (int count)
override void Refresh ()
void RefreshImpl ()
override void UpdateInterval ()
Icon InitIconEx (Icon icon, EntityAI item, int pos_x, int pos_y, bool refresh=true)
Icon InitIcon (Icon icon, EntityAI item, int pos_x, int pos_y)
bool HasItem (EntityAI item)
override bool TransferItemToVicinity ()
override void SetDefaultFocus (bool while_micromanagment_mode=false)
override void SetLastFocus ()
override void Unfocus ()
override void UnfocusAll ()
override void SetNextActive ()
override void SetPreviousActive (bool force=false)
override void SetNextRightActive ()
override void SetNextLeftActive ()
override EntityAI GetFocusedItem ()
override void SetLastActive ()
override void SetActive (bool active)
override bool IsItemActive ()
override bool IsItemWithQuantityActive ()
override bool IsEmpty ()
int GetRecipeCount (bool recipe_anywhere, ItemBase entity1, ItemBase entity2, PlayerBase player)
override bool CanCombineAmmo ()
override bool TransferItem ()
override bool SplitItem ()
override bool EquipItem ()
override bool SelectItem ()
override bool Select ()
override bool Combine ()
void ShowFalseCargoHeader (bool show)
void SetAlternateFalseTextHeaderWidget (TextWidget w)
void ClosableContainer (LayoutHolder parent, int sort=-1)
override bool IsDisplayable ()
override void UpdateRadialIcon ()
void SetOpenState (bool state)
override Header GetHeader ()
override void Open ()
override void Close ()
override void SetLayoutName ()
override void OnShow ()
override LayoutHolder Get (int x)
override void Refresh ()
void CloseButtonOnMouseButtonDown ()
override float GetFocusedContainerHeight (bool contents=false)
override float GetFocusedContainerYPos (bool contents=false)
override float GetFocusedContainerYScreenPos (bool contents=false)
void MoveContainerUp (Widget cont)
void MoveContainerDown (Widget cont)
override void CheckHeaderDragability ()
Detailed Description
Definition at line 1 of file RightArea.c.
Constructor & Destructor Documentation
RightArea()
void RightArea::RightArea (LayoutHolder parent) inline protected
Definition at line 14 of file RightArea.c.
  {
    m_MainWidget.Show(true);
    m_ScrollWidget = ScrollWidget.Cast(m_MainWidget.FindAnyWidget("Scroller"));
    m_MainWidget = m_MainWidget.FindAnyWidget("Content");
    //m_ContentParent   = m_RootWidget.FindAnyWidget("ContentParent");
    m_PlayerContainer = new PlayerContainer(this, false);
    m_PlayerContainer.SetPlayer(PlayerBase.Cast(GetGame().GetPlayer()));
    m_Body.Insert(m_PlayerContainer);
    m_ActiveIndex = 0;
    m_ProcessGridMovement = false;
    m_UpIcon = m_RootWidget.FindAnyWidget("Up");
    m_DownIcon = m_RootWidget.FindAnyWidget("Down");
    //m_ContentParent.GetScript( m_ContentResize );
    RecomputeOpenedContainers();
  }
References GetGame(), GetPlayer(), m_DownIcon, m_PlayerContainer, m_ProcessGridMovement, m_RootWidget, m_ScrollWidget, and m_UpIcon.
Member Function Documentation
CanTakeToInventory()
override bool RightArea::CanTakeToInventory () inline protected
Definition at line 89 of file RightArea.c.
  {
    return false;
  }
CanTakeToInventoryEx()
override bool RightArea::CanTakeToInventoryEx (EntityAI focusedEntity) inline protected
Definition at line 94 of file RightArea.c.
  {
    return false;
  }
Combine()
override bool RightArea::Combine () inline protected
Definition at line 54 of file RightArea.c.
  {
    return m_PlayerContainer.Combine();
  }
References m_PlayerContainer.
DraggingOverHeader()
override void RightArea::DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline protected
Definition at line 39 of file RightArea.c.
  {
    m_PlayerContainer.DraggingOverHeader(w, x, y, receiver);
  }
References m_PlayerContainer, x, and y.
EquipItem()
override bool RightArea::EquipItem () inline protected
Definition at line 64 of file RightArea.c.
  {
    return m_PlayerContainer.EquipItem();
  }
References m_PlayerContainer.
ExpandCollapseContainer()
override void RightArea::ExpandCollapseContainer () inline protected
Definition at line 125 of file RightArea.c.
  {
    m_PlayerContainer.ExpandCollapseContainer();
  }
References m_PlayerContainer.
GetCurrentContainerBottomY()
float RightArea::GetCurrentContainerBottomY () inline protected
Definition at line 239 of file RightArea.c.
  {
    float x, y;
    GetMainWidget().Update();
    GetMainWidget().GetScreenPos(x, y);
    float cont_screen_pos = GetFocusedContainerYScreenPos();
    float cont_screen_height = GetFocusedContainerHeight();
    return cont_screen_pos - y + cont_screen_height;
  }
References Container::GetFocusedContainerHeight(), Container::GetFocusedContainerYScreenPos(), x, and y.
Referenced by MoveUpDownIcons().
GetCurrentContainerTopY()
float RightArea::GetCurrentContainerTopY () inline protected
Definition at line 229 of file RightArea.c.
  {
    float x, y;
    GetMainWidget().Update();
    GetMainWidget().GetScreenPos(x, y);
    float cont_screen_pos = GetFocusedContainerYScreenPos();
    return cont_screen_pos - y;
  }
References Container::GetFocusedContainerYScreenPos(), x, and y.
Referenced by MoveUpDownIcons().
GetPlayerContainer()
PlayerContainer RightArea::GetPlayerContainer () inline protected
Definition at line 34 of file RightArea.c.
  {
    return m_PlayerContainer;
  }
References m_PlayerContainer.
GetScrollWidget()
override ScrollWidget RightArea::GetScrollWidget () inline protected
Definition at line 216 of file RightArea.c.
  {
    return m_ScrollWidget;
  }
References m_ScrollWidget.
HasEntityContainerVisible()
bool RightArea::HasEntityContainerVisible (EntityAI entity) inline protected
Definition at line 99 of file RightArea.c.
  {
    return m_PlayerContainer.HasEntityContainerVisible(entity);
  }
References m_PlayerContainer.
InspectItem()
override bool RightArea::InspectItem () inline protected
Definition at line 74 of file RightArea.c.
  {
    return m_PlayerContainer.InspectItem();
  }
References m_PlayerContainer.
IsPlayerEquipmentActive()
bool RightArea::IsPlayerEquipmentActive () inline protected
Definition at line 109 of file RightArea.c.
  {
    return m_PlayerContainer.IsPlayerEquipmentActive();
  }
References m_PlayerContainer.
MoveUpDownIcons()
void RightArea::MoveUpDownIcons () inline protected
Definition at line 177 of file RightArea.c.
  {
    if (m_UpIcon && m_DownIcon)
    {
      m_UpIcon.Show(m_IsActive);
      m_DownIcon.Show(m_IsActive);
      if (m_IsActive)
      {
        float x, y;
        m_UpIcon.GetScreenSize(x, y);
        float top_y = GetCurrentContainerTopY();
        m_UpIcon.SetPos(0, Math.Clamp(top_y, 0, 99999));
#ifndef PLATFORM_CONSOLE
        float x2, y2;
        m_DownIcon.GetScreenSize(x2, y2);
        float bottom_y = GetCurrentContainerBottomY() - y2;
        float diff = bottom_y - (top_y + y);
        if (diff < 0)
        {
          top_y += diff / 2;
          bottom_y -= diff / 2;
        }
        m_DownIcon.SetPos(0, bottom_y);
#endif
      }
    }
    /*else
      {
      ErrorEx("up/down icons not present!");
      }
      #else
      m_ScrollWidget.Update();
      #endif*/
  }
References Math::Clamp(), GetCurrentContainerBottomY(), GetCurrentContainerTopY(), m_DownIcon, m_IsActive, m_UpIcon, x, and y.
Referenced by UpdateSelectionIcons().
OnShow()
override void RightArea::OnShow () inline protected
Definition at line 163 of file RightArea.c.
  {
    super.OnShow();
    Refresh();
  }
References Refresh().
Refresh()
override void RightArea::Refresh () inline protected
Definition at line 130 of file RightArea.c.
  {
    m_ScrollWidget.Update();
    m_PlayerContainer.Refresh();
    m_ShouldChangeSize = true;
  }
References m_PlayerContainer, m_ScrollWidget, and m_ShouldChangeSize.
Referenced by OnShow(), SetSameLevelNextActive(), and SetSameLevelPreviousActive().
Select()
override bool RightArea::Select () inline protected
Definition at line 44 of file RightArea.c.
  {
    return m_PlayerContainer.Select();
  }
References m_PlayerContainer.
SelectItem()
override bool RightArea::SelectItem () inline protected
Definition at line 49 of file RightArea.c.
  {
    return m_PlayerContainer.SelectItem();
  }
References m_PlayerContainer.
SetLayoutName()
override void RightArea::SetLayoutName () inline protected
Definition at line 137 of file RightArea.c.
  {
#ifdef PLATFORM_CONSOLE
    m_LayoutName = WidgetLayoutName.RightAreaXbox;
#else
    switch (InventoryMenu.GetWidthType())
    {
    case ScreenWidthType.NARROW:
      m_LayoutName = WidgetLayoutName.RightAreaNarrow;
      break;
    case ScreenWidthType.MEDIUM:
      m_LayoutName = WidgetLayoutName.RightAreaMedium;
      break;
    case ScreenWidthType.WIDE:
      m_LayoutName = WidgetLayoutName.RightAreaWide;
      break;
    }
#endif
  }
References InventoryMenu(), WidgetLayoutName::RightAreaMedium, WidgetLayoutName::RightAreaNarrow, WidgetLayoutName::RightAreaWide, and WidgetLayoutName::RightAreaXbox.
SetParentWidget()
override void RightArea::SetParentWidget () inline protected
Definition at line 158 of file RightArea.c.
  {
    m_ParentWidget = m_Parent.GetMainWidget().FindAnyWidget("RightPanel");
  }
References m_Parent, and m_ParentWidget.
SetSameLevelNextActive()
override void RightArea::SetSameLevelNextActive () inline protected
Definition at line 114 of file RightArea.c.
  {
    m_PlayerContainer.SetSameLevelNextActive();
    Refresh();
  }
References m_PlayerContainer, and Refresh().
SetSameLevelPreviousActive()
override void RightArea::SetSameLevelPreviousActive () inline protected
Definition at line 119 of file RightArea.c.
  {
    m_PlayerContainer.SetSameLevelPreviousActive();
    Refresh();
  }
References m_PlayerContainer, and Refresh().
SplitItem()
override bool RightArea::SplitItem () inline protected
Definition at line 59 of file RightArea.c.
  {
    return m_PlayerContainer.SplitItem();
  }
References m_PlayerContainer.
SwapItemsInOrder()
void RightArea::SwapItemsInOrder (int slot1, int slot2) inline protected
Definition at line 104 of file RightArea.c.
  {
    m_PlayerContainer.SwapItemsInOrder(slot1, slot2);
  }
References m_PlayerContainer.
TransferItem()
override bool RightArea::TransferItem () inline protected
Definition at line 69 of file RightArea.c.
  {
    return m_PlayerContainer.TransferItem();
  }
References m_PlayerContainer.
TransferItemToVicinity()
override bool RightArea::TransferItemToVicinity () inline protected
Definition at line 79 of file RightArea.c.
  {
    return m_PlayerContainer.TransferItemToVicinity();
  }
References m_PlayerContainer.
UnfocusGrid()
override void RightArea::UnfocusGrid () inline protected
Definition at line 84 of file RightArea.c.
  {
    m_PlayerContainer.UnfocusGrid();
  }
References m_PlayerContainer.
UpdateInterval()
override void RightArea::UpdateInterval () inline protected
Definition at line 169 of file RightArea.c.
  {
    super.UpdateInterval();
    m_PlayerContainer.UpdateInterval();
    CheckScrollbarVisibility();
  }
References m_PlayerContainer.
UpdateSelectionIcons()
override void RightArea::UpdateSelectionIcons () inline protected
Definition at line 221 of file RightArea.c.
  {
#ifdef PLATFORM_CONSOLE
    ScrollToActiveContainer();
#endif
    MoveUpDownIcons();
  }
References MoveUpDownIcons().
Member Data Documentation
m_ContentParent
Widget RightArea::m_ContentParent protected
Definition at line 4 of file RightArea.c.
m_ContentResize
ref SizeToChild RightArea::m_ContentResize protected
Definition at line 10 of file RightArea.c.
m_DownIcon
Widget RightArea::m_DownIcon protected
Definition at line 8 of file RightArea.c.
Referenced by MoveUpDownIcons(), and RightArea().
m_PlayerContainer
ref PlayerContainer RightArea::m_PlayerContainer private
Definition at line 3 of file RightArea.c.
Referenced by Combine(), DraggingOverHeader(), EquipItem(), ExpandCollapseContainer(), GetPlayerContainer(), HasEntityContainerVisible(), InspectItem(), IsPlayerEquipmentActive(), Refresh(), RightArea(), Select(), SelectItem(), SetSameLevelNextActive(), SetSameLevelPreviousActive(), SplitItem(), SwapItemsInOrder(), TransferItem(), TransferItemToVicinity(), UnfocusGrid(), and UpdateInterval().
m_ProcessGridMovement
bool RightArea::m_ProcessGridMovement protected
Definition at line 12 of file RightArea.c.
Referenced by RightArea().
m_ScrollWidget
ScrollWidget RightArea::m_ScrollWidget protected
Definition at line 6 of file RightArea.c.
Referenced by GetScrollWidget(), Refresh(), and RightArea().
m_ShouldChangeSize
bool RightArea::m_ShouldChangeSize = true protected
Definition at line 11 of file RightArea.c.
Referenced by Refresh().
m_UpIcon
Widget RightArea::m_UpIcon protected
Definition at line 7 of file RightArea.c.
Referenced by MoveUpDownIcons(), and RightArea().
The documentation for this class was generated from the following file:
scripts/5_Mission/GUI/InventoryNew/Areas/RightArea.c