DayZ: scripts/4_World/Entities/ItemBase/Edible_Base/Bottle_Base.c File Reference
Bottle_Base.c File Reference
Enumerations
enum SoundTypeBottle { POURING = 1 , EMPTYING = 0 }
Functions
void Bottle_Base ()
void ~Bottle_Base ()
override void EEDelete (EntityAI parent)
override void EECargoIn (EntityAI item)
override void Synchronize ()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
override void OnVariablesSynchronized ()
void RemoveAudioVisualsOnClient ()
void RefreshAudioVisualsOnClient (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned)
void RefreshAudioVisuals (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned)
void RemoveAudioVisuals ()
void ParticleCookingStart (int particle_id)
void ParticleCookingStop ()
void PlayPouringLoopSound ()
void StopPouringLoopSound ()
void PlayEmptyingLoopSound ()
void StopEmptyingLoopSound ()
string GetEmptyingLoopSoundset ()
string GetEmptyingEndSoundset ()
string GetPouringSoundset ()
string GetEmptyingLoopSoundsetHard ()
string GetEmptyingLoopSoundsetSoft ()
string GetEmptyingLoopSoundsetWater ()
string GetEmptyingEndSoundsetHard ()
string GetEmptyingEndSoundsetSoft ()
string GetEmptyingEndSoundsetWater ()
float GetLiquidEmptyRate ()
Returns base liquid empty rate (absolute)..preferrably use the 'GetLiquidThroughputCoef' instead.
override void SetActions ()
override void OnDebugSpawn ()
Variables
enum SoundTypeBottle m_ParticleCooking
int m_ParticlePlaying = ParticleList.INVALID
int PARTICLE_BOILING_EMPTY = ParticleList.COOKING_BOILING_EMPTY
int PARTICLE_BOILING_START = ParticleList.COOKING_BOILING_START
int PARTICLE_BOILING_DONE = ParticleList.COOKING_BOILING_DONE
int PARTICLE_BAKING_START = ParticleList.COOKING_BAKING_START
int PARTICLE_BAKING_DONE = ParticleList.COOKING_BAKING_DONE
int PARTICLE_DRYING_START = ParticleList.COOKING_DRYING_START
int PARTICLE_DRYING_DONE = ParticleList.COOKING_DRYING_DONE
int PARTICLE_BURNING_DONE = ParticleList.COOKING_BURNING_DONE
EffectSound m_PouringLoopSound
EffectSound m_EmptyingLoopSound
CookingMethodType m_CookingMethod
bool m_CookingIsDone
bool m_CookingIsEmpty
bool m_CookingIsBurned
const string SOUND_BOILING_EMPTY = "Boiling_SoundSet"
const string SOUND_BOILING_START = "Boiling_SoundSet"
const string SOUND_BOILING_DONE = "Boiling_Done_SoundSet"
const string SOUND_DRYING_START = "Drying_SoundSet"
const string SOUND_DRYING_DONE = "Drying_Done_SoundSet"
float m_LiquidEmptyRate
const float QUANTITY_EMPTIED_PER_SEC_DEFAULT = 200
Enumeration Type Documentation
SoundTypeBottle
enum SoundTypeBottle
Enumerator
POURING
EMPTYING
Definition at line 1 of file Bottle_Base.c.
{
  POURING = 1,
  EMPTYING = 0,
}
Function Documentation
Bottle_Base()
void Bottle_Base () private
Definition at line 46 of file Bottle_Base.c.
  {
    RegisterNetSyncVariableInt("m_CookingMethod", CookingMethodType.NONE, CookingMethodType.COUNT);
    RegisterNetSyncVariableBool("m_CookingIsDone");
    RegisterNetSyncVariableBool("m_CookingIsEmpty");
    RegisterNetSyncVariableBool("m_CookingIsBurned");
    m_LiquidEmptyRate = QUANTITY_EMPTIED_PER_SEC_DEFAULT;
  }
References m_LiquidEmptyRate, and QUANTITY_EMPTIED_PER_SEC_DEFAULT.
EECargoIn()
override void EECargoIn (EntityAI item) private
Definition at line 70 of file Bottle_Base.c.
  {
    super.EECargoIn(item);
    MiscGameplayFunctions.SoakItemInsideParentContainingLiquidAboveThreshold(ItemBase.Cast(item), this);
  }
EEDelete()
override void EEDelete (EntityAI parent) private
Definition at line 62 of file Bottle_Base.c.
  {
    super.EEDelete(parent);
    //remove audio visuals
    RemoveAudioVisuals();
  }
References RemoveAudioVisuals().
GetEmptyingEndSoundset()
string GetEmptyingEndSoundset () private
Definition at line 304 of file Bottle_Base.c.
  {
    vector pos = GetPosition();
    string surfaceType = GetGame().GetPlayer().GetSurfaceType();
    string soundSet = "";
    bool diggable = GetGame().IsSurfaceDigable(surfaceType);
    if (!diggable)
      soundSet = GetEmptyingEndSoundsetHard();
    else if (diggable)
      soundSet = GetEmptyingEndSoundsetSoft();
    else if (GetGame().SurfaceIsPond(pos[0], pos[2]) || GetGame().SurfaceIsSea(pos[0], pos[2]))
      soundSet = GetEmptyingEndSoundsetWater();
    return soundSet;
  }
References Bottle_Base::GetEmptyingEndSoundsetHard(), Bottle_Base::GetEmptyingEndSoundsetSoft(), Bottle_Base::GetEmptyingEndSoundsetWater(), GetGame(), and GetPosition.
Referenced by StopEmptyingLoopSound().
GetEmptyingEndSoundsetHard()
string GetEmptyingEndSoundsetHard () private
GetEmptyingEndSoundsetSoft()
string GetEmptyingEndSoundsetSoft () private
GetEmptyingEndSoundsetWater()
string GetEmptyingEndSoundsetWater () private
GetEmptyingLoopSoundset()
string GetEmptyingLoopSoundset () private
Definition at line 286 of file Bottle_Base.c.
  {
    vector pos = GetPosition();
    string surfaceType = GetGame().GetPlayer().GetSurfaceType();
    string soundSet = "";
    bool diggable = GetGame().IsSurfaceDigable(surfaceType);
    if (!diggable)
      soundSet = GetEmptyingLoopSoundsetHard();
    else if (diggable)
      soundSet = GetEmptyingLoopSoundsetSoft();
    else if (GetGame().SurfaceIsPond(pos[0], pos[2]) || GetGame().SurfaceIsSea(pos[0], pos[2]))
      soundSet = GetEmptyingLoopSoundsetWater();
    return soundSet;
  }
References Bottle_Base::GetEmptyingLoopSoundsetHard(), Bottle_Base::GetEmptyingLoopSoundsetSoft(), Bottle_Base::GetEmptyingLoopSoundsetWater(), GetGame(), and GetPosition.
Referenced by PlayEmptyingLoopSound().
GetEmptyingLoopSoundsetHard()
string GetEmptyingLoopSoundsetHard () private
GetEmptyingLoopSoundsetSoft()
string GetEmptyingLoopSoundsetSoft () private
GetEmptyingLoopSoundsetWater()
string GetEmptyingLoopSoundsetWater () private
GetLiquidEmptyRate()
float GetLiquidEmptyRate () private
Returns base liquid empty rate (absolute)..preferrably use the 'GetLiquidThroughputCoef' instead.
Definition at line 331 of file Bottle_Base.c.
  {
    return m_LiquidEmptyRate;
  }
References m_LiquidEmptyRate.
GetPouringSoundset()
string GetPouringSoundset () private
OnDebugSpawn()
override void OnDebugSpawn () private
Definition at line 355 of file Bottle_Base.c.
  {
    SetQuantityMax();
  }
References SetQuantityMax().
OnRPC()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) private
Definition at line 89 of file Bottle_Base.c.
  {
    super.OnRPC(sender, rpc_type, ctx);
    Param1<bool> p = new Param1<bool>(false);
    if (!ctx.Read(p))
      return;
    bool play = p.param1;
    switch (rpc_type)
    {
    case SoundTypeBottle.POURING:
      if (play)
        PlayPouringLoopSound();
      else
        StopPouringLoopSound();
      break;
    case SoundTypeBottle.EMPTYING:
      if (play)
        PlayEmptyingLoopSound();
      else
        StopEmptyingLoopSound();
      break;
    }
  }
References PlayEmptyingLoopSound(), PlayPouringLoopSound(), StopEmptyingLoopSound(), and StopPouringLoopSound().
OnVariablesSynchronized()
override void OnVariablesSynchronized () private
Definition at line 119 of file Bottle_Base.c.
  {
    super.OnVariablesSynchronized();
    if (m_CookingMethod != CookingMethodType.NONE)
      RefreshAudioVisuals(m_CookingMethod, m_CookingIsDone, m_CookingIsEmpty, m_CookingIsBurned);
    else
      RemoveAudioVisuals();
  }
References m_CookingIsBurned, m_CookingIsDone, m_CookingIsEmpty, m_CookingMethod, RefreshAudioVisuals(), and RemoveAudioVisuals().
ParticleCookingStart()
void ParticleCookingStart (int particle_id) private
Definition at line 232 of file Bottle_Base.c.
  {
#ifndef SERVER
    if (m_ParticlePlaying != particle_id)
    {
      //stop previous particles
      ParticleCookingStop();
      //create new
      vector localPos = MiscGameplayFunctions.GetSteamPosition(GetHierarchyParent());
      m_ParticleCooking = ParticleManager.GetInstance().PlayInWorld(particle_id, localPos);
      m_ParticlePlaying = particle_id;
    }
#endif
  }
References m_ParticleCooking, m_ParticlePlaying, particle_id, ParticleCookingStop(), and ParticleManager().
Referenced by RefreshAudioVisuals().
ParticleCookingStop()
void ParticleCookingStop () private
Definition at line 249 of file Bottle_Base.c.
  {
    if (m_ParticleCooking && GetGame() && !GetGame().IsDedicatedServer())
    {
      m_ParticleCooking.Stop();
      m_ParticleCooking = null;
      m_ParticlePlaying = ParticleList.INVALID;
    }
  }
References GetGame(), ParticleList::INVALID, m_ParticleCooking, and m_ParticlePlaying.
Referenced by ParticleCookingStart(), and RemoveAudioVisuals().
PlayEmptyingLoopSound()
void PlayEmptyingLoopSound () private
Definition at line 271 of file Bottle_Base.c.
  {
    if (!m_EmptyingLoopSound || !m_EmptyingLoopSound.IsSoundPlaying())
      m_EmptyingLoopSound = SEffectManager.PlaySoundOnObject(GetEmptyingLoopSoundset(), this, 0, 0, true);
  }
References GetEmptyingLoopSoundset(), EffectSound::IsSoundPlaying(), m_EmptyingLoopSound, and SEffectManager::PlaySoundOnObject().
Referenced by OnRPC().
PlayPouringLoopSound()
void PlayPouringLoopSound () private
Definition at line 259 of file Bottle_Base.c.
  {
    if (!m_PouringLoopSound || !m_PouringLoopSound.IsSoundPlaying())
      m_PouringLoopSound = SEffectManager.PlaySoundOnObject(GetPouringSoundset(), this, 0, 0, true);
  }
References Bottle_Base::GetPouringSoundset(), EffectSound::IsSoundPlaying(), m_PouringLoopSound, and SEffectManager::PlaySoundOnObject().
Referenced by OnRPC().
RefreshAudioVisuals()
void RefreshAudioVisuals (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned) private
Definition at line 146 of file Bottle_Base.c.
  {
    string soundName;
    int particleId;
    //if at least one of the food items is burned
    if (is_burned)
    {
      soundName = SOUND_BURNING_DONE;
      particleId = PARTICLE_BURNING_DONE;
    }
    //proper cooking methods
    else
    {
      switch (cooking_method)
      {
      case CookingMethodType.BOILING:
        if (is_empty)
        {
          soundName = SOUND_BOILING_EMPTY;
          particleId = PARTICLE_BOILING_EMPTY;
        }
        else
        {
          if (is_done)
          {
            soundName = SOUND_BOILING_DONE;
            particleId = PARTICLE_BOILING_DONE;
          }
          else
          {
            soundName = SOUND_BOILING_START;
            particleId = PARTICLE_BOILING_START;
          }
        }
        break;
      case CookingMethodType.BAKING:
        if (is_done)
        {
          soundName = SOUND_BAKING_DONE;
          particleId = PARTICLE_BAKING_DONE;
        }
        else
        {
          soundName = SOUND_BAKING_START;
          particleId = PARTICLE_BAKING_START ;
        }
        break;
      case CookingMethodType.DRYING:
        if (is_done)
        {
          soundName = SOUND_DRYING_DONE;
          particleId = PARTICLE_DRYING_DONE;
        }
        else
        {
          soundName = SOUND_DRYING_START;
          particleId = PARTICLE_DRYING_START;
        }
        break;
      default:
        soundName = "";
        particleId = ParticleList.NONE;
        break;
      }
    }
    //play effects
    ParticleCookingStart(particleId);
    SoundCookingStart(soundName);
  }
References ParticleList::NONE, PARTICLE_BAKING_DONE, PARTICLE_BAKING_START, PARTICLE_BOILING_DONE, PARTICLE_BOILING_EMPTY, PARTICLE_BOILING_START, PARTICLE_BURNING_DONE, PARTICLE_DRYING_DONE, PARTICLE_DRYING_START, ParticleCookingStart(), SOUND_BAKING_DONE, SOUND_BAKING_START, SOUND_BOILING_DONE, SOUND_BOILING_EMPTY, SOUND_BOILING_START, SOUND_BURNING_DONE, SOUND_DRYING_DONE, SOUND_DRYING_START, and SoundCookingStart().
Referenced by OnVariablesSynchronized().
RefreshAudioVisualsOnClient()
void RefreshAudioVisualsOnClient (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned) private
Definition at line 136 of file Bottle_Base.c.
  {
    m_CookingMethod = cooking_method;
    m_CookingIsDone = is_done;
    m_CookingIsEmpty = is_empty;
    m_CookingIsBurned = is_burned;
    Synchronize();
  }
References m_CookingIsBurned, m_CookingIsDone, m_CookingIsEmpty, m_CookingMethod, and Synchronize().
RemoveAudioVisuals()
void RemoveAudioVisuals () private
Definition at line 225 of file Bottle_Base.c.
  {
    ParticleCookingStop();
    SoundCookingStop();
  }
References ParticleCookingStop(), and SoundCookingStop().
Referenced by EEDelete(), and OnVariablesSynchronized().
RemoveAudioVisualsOnClient()
void RemoveAudioVisualsOnClient () private
Definition at line 129 of file Bottle_Base.c.
  {
    m_CookingMethod = CookingMethodType.NONE;
    Synchronize();
  }
References m_CookingMethod, and Synchronize().
SetActions()
override void SetActions () private
Definition at line 336 of file Bottle_Base.c.
  {
    super.SetActions();
    AddAction(ActionFillFuel);
    AddAction(ActionFillCoolant);
    AddAction(ActionFillGeneratorTank);
    AddAction(ActionExtinguishFireplaceByLiquid);
    AddAction(ActionFillBottleBase);
    AddAction(ActionWaterGardenSlot);
    AddAction(ActionWaterPlant);
    AddAction(ActionForceDrink);
    AddAction(ActionDrainLiquid);
    AddAction(ActionPourLiquid);
    AddAction(ActionWashHandsItemContinuous);
    AddAction(ActionDrink);
    AddAction(ActionEmptyBottleBase);
  }
References ActionExtinguishFireplaceByLiquid(), and AddAction().
StopEmptyingLoopSound()
void StopEmptyingLoopSound () private
Definition at line 277 of file Bottle_Base.c.
  {
    if (m_EmptyingLoopSound)
      m_EmptyingLoopSound.SoundStop();
    EffectSound sound = SEffectManager.PlaySoundOnObject(GetEmptyingEndSoundset(), this);
    sound.SetAutodestroy(true);
  }
References GetEmptyingEndSoundset(), m_EmptyingLoopSound, SEffectManager::PlaySoundOnObject(), and EffectSound::SoundStop().
Referenced by OnRPC().
StopPouringLoopSound()
void StopPouringLoopSound () private
Definition at line 265 of file Bottle_Base.c.
  {
    if (m_PouringLoopSound)
      m_PouringLoopSound.SoundStop();
  }
References m_PouringLoopSound, and EffectSound::SoundStop().
Referenced by OnRPC().
Synchronize()
override void Synchronize () private
Definition at line 84 of file Bottle_Base.c.
  {
    SetSynchDirty();
  }
~Bottle_Base()
void ~Bottle_Base () private
Definition at line 56 of file Bottle_Base.c.
  {
    SEffectManager.DestroyEffect(m_PouringLoopSound);
    SEffectManager.DestroyEffect(m_EmptyingLoopSound);
  }
References SEffectManager::DestroyEffect(), m_EmptyingLoopSound, and m_PouringLoopSound.
Variable Documentation
m_CookingIsBurned
bool m_CookingIsBurned protected
Definition at line 34 of file Bottle_Base.c.
Referenced by OnVariablesSynchronized(), Inventory_Base::OnVariablesSynchronized(), RefreshAudioVisualsOnClient(), and Inventory_Base::RefreshAudioVisualsOnClient().
m_CookingIsDone
bool m_CookingIsDone protected
Definition at line 32 of file Bottle_Base.c.
Referenced by OnVariablesSynchronized(), Inventory_Base::OnVariablesSynchronized(), RefreshAudioVisualsOnClient(), and Inventory_Base::RefreshAudioVisualsOnClient().
m_CookingIsEmpty
bool m_CookingIsEmpty protected
Definition at line 33 of file Bottle_Base.c.
Referenced by OnVariablesSynchronized(), Inventory_Base::OnVariablesSynchronized(), RefreshAudioVisualsOnClient(), and Inventory_Base::RefreshAudioVisualsOnClient().
m_CookingMethod
CookingMethodType m_CookingMethod protected
Definition at line 31 of file Bottle_Base.c.
Referenced by OnVariablesSynchronized(), Inventory_Base::OnVariablesSynchronized(), RefreshAudioVisualsOnClient(), Inventory_Base::RefreshAudioVisualsOnClient(), RemoveAudioVisualsOnClient(), and Inventory_Base::RemoveAudioVisualsOnClient().
m_EmptyingLoopSound
EffectSound m_EmptyingLoopSound protected
Definition at line 28 of file Bottle_Base.c.
Referenced by PlayEmptyingLoopSound(), StopEmptyingLoopSound(), and ~Bottle_Base().
m_LiquidEmptyRate
float m_LiquidEmptyRate protected
Definition at line 43 of file Bottle_Base.c.
Referenced by Bottle_Base(), and GetLiquidEmptyRate().
m_ParticleCooking
enum SoundTypeBottle m_ParticleCooking
Referenced by ParticleCookingStart(), Inventory_Base::ParticleCookingStart(), ParticleCookingStop(), and Inventory_Base::ParticleCookingStop().
m_ParticlePlaying
int m_ParticlePlaying = ParticleList.INVALID protected
Definition at line 11 of file Bottle_Base.c.
Referenced by ParticleCookingStart(), Inventory_Base::ParticleCookingStart(), ParticleCookingStop(), and Inventory_Base::ParticleCookingStop().
m_PouringLoopSound
EffectSound m_PouringLoopSound protected
Definition at line 27 of file Bottle_Base.c.
Referenced by PlayPouringLoopSound(), StopPouringLoopSound(), and ~Bottle_Base().
PARTICLE_BAKING_DONE
int PARTICLE_BAKING_DONE = ParticleList.COOKING_BAKING_DONE protected
Definition at line 19 of file Bottle_Base.c.
Referenced by RefreshAudioVisuals().
PARTICLE_BAKING_START
int PARTICLE_BAKING_START = ParticleList.COOKING_BAKING_START protected
Definition at line 18 of file Bottle_Base.c.
Referenced by RefreshAudioVisuals().
PARTICLE_BOILING_DONE
int PARTICLE_BOILING_DONE = ParticleList.COOKING_BOILING_DONE protected
Definition at line 16 of file Bottle_Base.c.
Referenced by RefreshAudioVisuals().
PARTICLE_BOILING_EMPTY
int PARTICLE_BOILING_EMPTY = ParticleList.COOKING_BOILING_EMPTY protected
Definition at line 14 of file Bottle_Base.c.
Referenced by RefreshAudioVisuals().
PARTICLE_BOILING_START
int PARTICLE_BOILING_START = ParticleList.COOKING_BOILING_START protected
Definition at line 15 of file Bottle_Base.c.
Referenced by RefreshAudioVisuals().
PARTICLE_BURNING_DONE
int PARTICLE_BURNING_DONE = ParticleList.COOKING_BURNING_DONE protected
Definition at line 24 of file Bottle_Base.c.
Referenced by RefreshAudioVisuals().
PARTICLE_DRYING_DONE
int PARTICLE_DRYING_DONE = ParticleList.COOKING_DRYING_DONE protected
Definition at line 22 of file Bottle_Base.c.
Referenced by RefreshAudioVisuals().
PARTICLE_DRYING_START
int PARTICLE_DRYING_START = ParticleList.COOKING_DRYING_START protected
Definition at line 21 of file Bottle_Base.c.
Referenced by RefreshAudioVisuals().
QUANTITY_EMPTIED_PER_SEC_DEFAULT
const float QUANTITY_EMPTIED_PER_SEC_DEFAULT = 200 private
Definition at line 44 of file Bottle_Base.c.
Referenced by Bottle_Base().
SOUND_BOILING_DONE
const string SOUND_BOILING_DONE = "Boiling_Done_SoundSet" protected
Definition at line 39 of file Bottle_Base.c.
Referenced by RefreshAudioVisuals().
SOUND_BOILING_EMPTY
const string SOUND_BOILING_EMPTY = "Boiling_SoundSet" protected
Definition at line 37 of file Bottle_Base.c.
Referenced by RefreshAudioVisuals().
SOUND_BOILING_START
const string SOUND_BOILING_START = "Boiling_SoundSet" protected
Definition at line 38 of file Bottle_Base.c.
Referenced by RefreshAudioVisuals().
SOUND_DRYING_DONE
const string SOUND_DRYING_DONE = "Drying_Done_SoundSet" protected
Definition at line 41 of file Bottle_Base.c.
Referenced by RefreshAudioVisuals().
SOUND_DRYING_START
const string SOUND_DRYING_START = "Drying_SoundSet" protected
Definition at line 40 of file Bottle_Base.c.
Referenced by RefreshAudioVisuals().