DayZ: scripts/4_World/Classes/SoundHandlers/ThirstSoundHandler.c File Reference
ThirstSoundHandler.c File Reference
Classes
class SoundHandlerBase
class ThirstSoundHandlerBase
Functions
override void Update ()
void ProcessSound ()
void PlaySound ()
Variables
class ThirstSoundHandlerBase extends SoundHandlerBase SOUND_INTERVALS_LIGHT_MIN = 10
const float SOUND_INTERVALS_LIGHT_MAX = 30
float m_SoundTime
EffectSound m_Sound
Function Documentation
PlaySound()
void PlaySound ()
Definition at line 36 of file ThirstSoundHandler.c.
  {
    m_Player.PlaySoundEventEx(EPlayerSoundEventID.THIRST);
  }
References m_Player, and DayZPlayer::PlaySoundEventEx().
ProcessSound()
void ProcessSound ()
Definition at line 26 of file ThirstSoundHandler.c.
  {
    if (GetGame().GetTime() > m_SoundTime)
    {
      float offset_time = Math.RandomFloatInclusive(SOUND_INTERVALS_LIGHT_MIN, SOUND_INTERVALS_LIGHT_MAX) * 1000;
      m_SoundTime = GetGame().GetTime() + offset_time;
      PlaySound();
    }
  }
References GetGame(), GetTime(), m_SoundTime, PlaySound(), Math::RandomFloatInclusive(), SOUND_INTERVALS_LIGHT_MAX, and SOUND_INTERVALS_LIGHT_MIN.
Variable Documentation
m_Sound
EffectSound m_Sound
Definition at line 18 of file ThirstSoundHandler.c.
m_SoundTime
float m_SoundTime
Definition at line 17 of file ThirstSoundHandler.c.
SOUND_INTERVALS_LIGHT_MAX
const float SOUND_INTERVALS_LIGHT_MAX = 30
Definition at line 16 of file ThirstSoundHandler.c.
SOUND_INTERVALS_LIGHT_MIN
class ThirstSoundHandlerBase extends SoundHandlerBase SOUND_INTERVALS_LIGHT_MIN = 10