DayZ: scripts/3_Game/Global/ErrorModuleHandler/ConnectErrorScriptModule.c File Reference
ConnectErrorScriptModule.c File Reference
Classes
class ConnectErrorScriptModuleUI
Enumerations
enum EConnectErrorScript
Functions
enum EConnectErrorScript ConnectErrorScriptModule ()
override void InitOptionalVariables ()
override void FillErrorDataMap ()
override void OnEvent (EventType eventTypeId, Param params)
Handles VON-related events.
Variables
UNKNOWN = -1
OK = 0
ALREADY_CONNECTING
ALREADY_CONNECTING_THIS
Enumeration Type Documentation
EConnectErrorScript
enum EConnectErrorScript
Definition at line 1 of file ConnectErrorScriptModule.c.
{
  UNKNOWN = -1, // -1 must always be UNKNOWN
  OK = 0, // 0 must always be OK
  ALREADY_CONNECTING, // Already joining a server
  ALREADY_CONNECTING_THIS, // Already joining this exact server
}
Function Documentation
ConnectErrorScriptModule()
enum EConnectErrorScript ConnectErrorScriptModule ()
Definition at line 1 of file ConnectErrorScriptModule.c.
  {
    SetCategory(ErrorCategory.ConnectErrorScript);
  }
References ALREADY_CONNECTING, ALREADY_CONNECTING_THIS, OK, and UNKNOWN.
Referenced by ErrorModuleHandler::Init().
FillErrorDataMap()
override void FillErrorDataMap ()
Definition at line 27 of file ConnectErrorScriptModule.c.
  {
    super.FillErrorDataMap();
    InsertDialogueErrorProperties(EConnectErrorScript.ALREADY_CONNECTING, "#STR_script_already_connecting", DBT_YESNOCANCEL, DBB_NO);
    InsertDialogueErrorProperties(EConnectErrorScript.ALREADY_CONNECTING_THIS, "#STR_script_already_connecting_this");
  }
References InsertDialogueErrorProperties().
Referenced by ErrorHandlerModuleScript().
InitOptionalVariables()
override void InitOptionalVariables ()
Definition at line 17 of file ConnectErrorScriptModule.c.
  {
    super.InitOptionalVariables();
    m_Header = "#server_browser_connecting_failed";
#ifndef NO_GUI
    m_UIHandler = new ConnectErrorScriptModuleUI();
#endif
  }
Referenced by ErrorHandlerModuleScript().
OnEvent()
override void OnEvent (EventType eventTypeId, Param params)
Handles VON-related events.
Parameters
eventTypeId event that fired
params event-specific parameters
Definition at line 35 of file ConnectErrorScriptModule.c.
  {
    switch (eventTypeId)
    {
    case MPSessionPlayerReadyEventTypeID:
#ifndef NO_GUI
      g_Game.GetUIManager().CloseSpecificDialog(m_LastErrorThrown);
#endif
      break;
    default:
      break;
    }
  }
References g_Game, m_LastErrorThrown, and MPSessionPlayerReadyEventTypeID.
Variable Documentation
ALREADY_CONNECTING
@ ALREADY_CONNECTING
Definition at line 16 of file ConnectErrorScriptModule.c.
Referenced by ConnectErrorScriptModule().
ALREADY_CONNECTING_THIS
ALREADY_CONNECTING_THIS
Definition at line 17 of file ConnectErrorScriptModule.c.
Referenced by ConnectErrorScriptModule().
OK
@ OK = 0
Definition at line 14 of file ConnectErrorScriptModule.c.
Referenced by ConnectErrorScriptModule().
UNKNOWN
@ UNKNOWN = -1
Definition at line 13 of file ConnectErrorScriptModule.c.
Referenced by ConnectErrorScriptModule().