DayZ: scripts/4_World/Classes/BleedingSources/BleedingSource.c File Reference
BleedingSource.c File Reference
Enumerations
enum eBleedingSourceType { NORMAL , CONTAMINATED }
Functions
void BleedingSource (PlayerBase player, int bit, string bone, vector orientation, vector offset, int max_time, float flow_modifier, string particle_name)
void ~BleedingSource ()
void SetType (eBleedingSourceType type)
eBleedingSourceType GetType ()
int GetActiveTime ()
void SetActiveTime (int time)
int GetBit ()
void CreateParticle ()
void RemoveParticle ()
void OnUpdateServer (float deltatime, float blood_scale, bool no_blood_loss)
void StartSourceBleedingIndication ()
void StopSourceBleedingIndication (bool instant=false)
void DrawDebugShape ()
void RemoveDebugShape ()
Variables
enum eBleedingSourceType m_Position
Particle m_BloodParticle
PlayerBase m_Player
int m_Bit
string m_Bone
ref EffectParticle m_BleedingEffect
vector m_Orientation
Shape m_DebugShape
Shape m_DebugShape1
ref Timer m_DebugTick
vector m_Offset
float m_FlowModifier
float m_ActiveTime
float m_MaxTime
string m_ParticleName
bool m_DeleteRequested
eBleedingSourceType m_Type = eBleedingSourceType.NORMAL
Enumeration Type Documentation
eBleedingSourceType
enum eBleedingSourceType
Enumerator
NORMAL
CONTAMINATED
Definition at line 1 of file BleedingSource.c.
{
  NORMAL,
  CONTAMINATED,
}
Function Documentation
BleedingSource()
void BleedingSource (PlayerBase player, int bit, string bone, vector orientation, vector offset, int max_time, float flow_modifier, string particle_name)
Definition at line 27 of file BleedingSource.c.
  {
    //m_Position = position;
    m_Player = player;
    m_Bit = bit;
    m_Bone = bone;
    m_Orientation = orientation;
    m_Offset = offset;
    m_FlowModifier = flow_modifier;
    m_MaxTime = max_time;
    m_ParticleName = particle_name;
    //CreateBleedSymptom();
    if (!GetGame().IsDedicatedServer())
    {
      CreateParticle();
      StartSourceBleedingIndication();
    }
  }
References CreateParticle(), GetGame(), m_Bit, m_Bone, m_FlowModifier, m_MaxTime, m_Offset, m_Orientation, m_ParticleName, m_Player, and StartSourceBleedingIndication().
Referenced by BleedingSourcesManagerBase::AddBleedingSource().
CreateParticle()
void CreateParticle ()
Definition at line 83 of file BleedingSource.c.
  {
    int boneIdx = m_Player.GetBoneIndexByName(m_Bone);
    m_BleedingEffect = EffectParticle.Cast(m_ParticleName.ToType().Spawn());
    if (m_BleedingEffect)
    {
      SEffectManager.PlayInWorld(m_BleedingEffect, "0 0 0");
      m_BloodParticle = m_BleedingEffect.GetParticle();
      m_BloodParticle.SetOrientation(m_Orientation);
      vector pos;
      pos += m_Offset;
      m_BloodParticle.SetPosition(pos);
      float time = Math.RandomFloat01() * 2;
      //time = time;
      m_BloodParticle.SetParameter(-1, EmitorParam.CURRENT_TIME, time);
      //m_BloodParticle.SetParameter(1, EmitorParam.CURRENT_TIME, time);
      m_Player.AddChild(m_BloodParticle, boneIdx);
      return;
    }
    else
      Error("bleeding source: failed to spawn the particle: " + m_ParticleName);
  }
References Error(), m_BleedingEffect, m_BloodParticle, m_Bone, m_Offset, m_Orientation, m_ParticleName, m_Player, SEffectManager::PlayInWorld(), Math::RandomFloat01(), Particle::SetParameter(), and string::ToType().
Referenced by BleedingSource(), CreateInWorld(), ParticleSource::CreateInWorld(), CreateOnObject(), ParticleSource::CreateOnObject(), ParticleSource::PlayInWorld(), PlayInWorldEx(), PlayOnObject(), and ParticleSource::PlayOnObject().
DrawDebugShape()
void DrawDebugShape ()
Definition at line 169 of file BleedingSource.c.
  {
    RemoveDebugShape();
    Particle p = m_BleedingEffect.GetParticle();
    vector pos = p.GetPosition();
    m_DebugShape = Debug.DrawSphere(pos, 0.009, COLOR_BLUE, ShapeFlags.TRANSP | ShapeFlags.NOOUTLINE | ShapeFlags.NOZBUFFER);
    vector arrow_to = m_BloodParticle.GetOrientation();
    arrow_to = arrow_to.AnglesToVector();
    arrow_to = -arrow_to * 0.3;
    arrow_to = pos + arrow_to;
    m_DebugShape1 = Debug.DrawArrow(pos, arrow_to, 0.1, COLOR_GREEN);
  }
References COLOR_BLUE, COLOR_GREEN, Debug::DrawArrow(), Debug::DrawSphere(), m_BleedingEffect, m_BloodParticle, m_DebugShape, m_DebugShape1, and RemoveDebugShape().
GetActiveTime()
int GetActiveTime ()
Definition at line 68 of file BleedingSource.c.
  {
    return m_ActiveTime;
  }
References m_ActiveTime.
GetBit()
int GetBit ()
Definition at line 78 of file BleedingSource.c.
  {
    return m_Bit;
  }
References m_Bit.
Referenced by OnUpdateServer().
GetType()
eBleedingSourceType GetType ()
Definition at line 63 of file BleedingSource.c.
  {
    return m_Type;
  }
References m_Type.
Referenced by Ammo_40mm_Smoke_ColorBase::Activate(), ItemBase::BatteryCharger(), EntityAI::Building(), InventoryItem::CanBeCombined(), Container_Base::CanPutInCargo(), BaseBuildingBase::CanReceiveAttachment(), ItemBase::ChangeInfestation(), Chemlight_ColorBase::Chemlight_ColorBase(), Chemlight_ColorBase::CreateLight(), RecipeBase::Do(), InventoryItemSuper::EEHealthLevelChanged(), CarWheel_Ruined::EEHealthLevelChanged(), EEInit(), Inventory_Base::EmptySeedPack(), Entity::EntityAI(), Entity::GetDefaultHitComponent(), Entity::GetDefaultHitPosition(), Entity::GetDefaultHitPositionComponent(), InventoryItem::GetDryingIncrement(), ItemBase::GetEnergyNeededToCharge(), IEntity::GetHiddenSelections(), IEntity::GetHiddenSelectionsMaterials(), IEntity::GetHiddenSelectionsTextures(), Entity::GetHitComponentForAI(), ManBase::GetItemOnSlot(), IEntity::GetModelName(), InventoryItem::GetMuzzleID(), ActionTargetsCursor::GetOnScreenPosition(), InventoryItem::GetProtectionLevel(), PluginRecipesManagerBase::GetRecipeIntersection(), InventoryItem::GetSoakingIncrement(), Entity::GetSuitableFinisherHitComponents(), ItemBase::GetTimeNeededToCharge(), IEntity::HasAnimation(), InventoryItem::HasFoodStage(), ItemBase::HideAllAnimationsAndProxyPhysics(), Entity::HideAllSelections(), ManBase::HideHairSelections(), Hologram::Hologram(), AlarmClock_ColorBase::Init(), KitchenTimer::Init(), FlammableBase::Init(), ItemOptics::Init2DPreloadType(), ItemOptics::InitCameraOverrideProperties(), Entity::InitDamageZoneDisplayNameMapping(), ItemOptics::InitDOFAvailability(), Weapon::InitDOFProperties(), ItemOptics::InitOpticsDOFProperties(), ItemOptics::InitOpticsPP(), ItemOptics::InitReddotData(), Weapon::InitReliability(), IEntity::KindOf(), InventoryItem::KindOf(), Land_Bilboard_Base::Land_Bilboard_Base(), Weapon::LoadCurrentFSMState(), InventoryItem::LoadParticleConfigOnFire(), InventoryItem::LoadParticleConfigOnOverheating(), LockOvenAttachments(), Entity::Log(), Entity::LogError(), Entity::LogWarning(), Entity::OnAction(), ItemBase::OnInitEnergy(), InventoryItem::OnRightClick(), Ammo_40mm_Smoke_ColorBase::OnVariablesSynchronized(), OnWorkStart(), ItemBase::PlantBase(), InventoryItem::PlayAttachSound(), Weapon::SaveCurrentFSMState(), ItemBase::SetFuel(), Entity::ShowAllSelections(), PluginRecipesManagerBase::SortIngredientsInRecipe(), InventoryItem::SplitIntoStackMax(), InventoryItem::SplitIntoStackMaxHands(), InventoryItem::SplitItem(), InventoryItem::SplitItemToInventoryLocation(), VicinityObjects::TransformToVicinityObjects(), and FlammableBase::TryTransformIntoStick().
OnUpdateServer()
void OnUpdateServer (float deltatime, float blood_scale, bool no_blood_loss)
Definition at line 112 of file BleedingSource.c.
  {
    m_ActiveTime += deltatime;
    if (m_ActiveTime >= m_MaxTime)
    {
      if (m_Player.GetBleedingManagerServer() && !m_DeleteRequested)
      {
        m_Player.GetBleedingManagerServer().RequestDeletion(GetBit());//add yourself to a list of sources to be deleted
        m_DeleteRequested = true;
      }
    }
    if (!no_blood_loss)
    {
      float flow = m_FlowModifier;
      switch (m_Type)
      {
      case eBleedingSourceType.NORMAL:
      {
        //do nothing
        break;
      }
      case eBleedingSourceType.CONTAMINATED:
      {
        flow *= PlayerConstants.BLEEDING_SOURCE_BURN_MODIFIER;
      }
      }
      m_Player.AddHealth("GlobalHealth", "Blood", (PlayerConstants.BLEEDING_SOURCE_BLOODLOSS_PER_SEC * blood_scale * deltatime * flow));
    }
  }
References PlayerConstants::BLEEDING_SOURCE_BLOODLOSS_PER_SEC, PlayerConstants::BLEEDING_SOURCE_BURN_MODIFIER, GetBit(), m_ActiveTime, m_DeleteRequested, m_FlowModifier, m_MaxTime, m_Player, and m_Type.
RemoveDebugShape()
void RemoveDebugShape ()
Definition at line 184 of file BleedingSource.c.
  {
    if (m_DebugShape)
      Debug.RemoveShape(m_DebugShape);
    if (m_DebugShape1)
      Debug.RemoveShape(m_DebugShape1);
  }
References m_DebugShape, m_DebugShape1, and Debug::RemoveShape().
Referenced by DrawDebugShape(), and ~BleedingSource().
RemoveParticle()
void RemoveParticle ()
Definition at line 107 of file BleedingSource.c.
  {
    SEffectManager.DestroyEffect(m_BleedingEffect);
  }
References SEffectManager::DestroyEffect(), and m_BleedingEffect.
Referenced by ~BleedingSource().
SetActiveTime()
void SetActiveTime (int time)
Definition at line 73 of file BleedingSource.c.
  {
    m_ActiveTime = time;
  }
References m_ActiveTime.
SetType()
void SetType (eBleedingSourceType type)
Definition at line 58 of file BleedingSource.c.
  {
    m_Type = type;
  }
References m_Type.
StartSourceBleedingIndication()
void StartSourceBleedingIndication ()
Definition at line 143 of file BleedingSource.c.
  {
    if (m_Player.IsControlledPlayer())
    {
#ifdef DIAG_DEVELOPER
      if (DbgBleedingIndicationStaticInfo.m_DbgEnableBleedingIndication)
      {
#endif
        Param4<bool, int, vector, bool> par = new Param4<bool, int, vector, bool>(true, m_Bit, "0 0 0", false);
        GetGame().GetMission().GetEffectWidgets().AddActiveEffects({EffectWidgetsTypes.BLEEDING_LAYER});
        GetGame().GetMission().GetEffectWidgets().UpdateWidgets(EffectWidgetsTypes.BLEEDING_LAYER, 0, par);
#ifdef DIAG_DEVELOPER
      }
#endif
    }
  }
References GetGame(), m_Bit, DbgBleedingIndicationStaticInfo::m_DbgEnableBleedingIndication, and m_Player.
Referenced by BleedingSource().
StopSourceBleedingIndication()
void StopSourceBleedingIndication (bool instant = false)
Definition at line 160 of file BleedingSource.c.
  {
    if (m_Player && m_Player.IsControlledPlayer() && GetGame() && (!GetGame().IsDedicatedServer()))
    {
      Param4<bool, int, vector, bool> par = new Param4<bool, int, vector, bool>(false, m_Bit, "0 0 0", instant);
      GetGame().GetMission().GetEffectWidgets().UpdateWidgets(EffectWidgetsTypes.BLEEDING_LAYER, 0, par);
    }
  }
References GetGame(), m_Bit, and m_Player.
Referenced by ~BleedingSource().
~BleedingSource()
void ~BleedingSource ()
Definition at line 48 of file BleedingSource.c.
  {
    if (m_BloodParticle)
      RemoveParticle();
    RemoveDebugShape();
    StopSourceBleedingIndication(!m_Player || !m_Player.IsAlive());
  }
References m_BloodParticle, m_Player, RemoveDebugShape(), RemoveParticle(), and StopSourceBleedingIndication().
Variable Documentation
m_ActiveTime
float m_ActiveTime
Definition at line 21 of file BleedingSource.c.
Referenced by GetActiveTime(), OnUpdateServer(), and SetActiveTime().
m_Bit
int m_Bit
Definition at line 12 of file BleedingSource.c.
Referenced by BleedingSource(), GetBit(), BleedingSourcesManagerBase::RegisterBleedingZoneEx(), StartSourceBleedingIndication(), and StopSourceBleedingIndication().
m_BleedingEffect
ref EffectParticle m_BleedingEffect
Definition at line 14 of file BleedingSource.c.
Referenced by CreateParticle(), DrawDebugShape(), and RemoveParticle().
m_BloodParticle
Particle m_BloodParticle
Definition at line 10 of file BleedingSource.c.
Referenced by CreateParticle(), DrawDebugShape(), and ~BleedingSource().
m_Bone
string m_Bone
Definition at line 13 of file BleedingSource.c.
Referenced by BleedingSource(), and CreateParticle().
m_DebugShape
Shape m_DebugShape
Definition at line 16 of file BleedingSource.c.
Referenced by DrawDebugShape(), and RemoveDebugShape().
m_DebugShape1
Shape m_DebugShape1
Definition at line 17 of file BleedingSource.c.
Referenced by DrawDebugShape(), and RemoveDebugShape().
m_DebugTick
ref Timer m_DebugTick
Definition at line 18 of file BleedingSource.c.
m_DeleteRequested
bool m_DeleteRequested
Definition at line 24 of file BleedingSource.c.
Referenced by OnUpdateServer().
m_FlowModifier
float m_FlowModifier
Definition at line 20 of file BleedingSource.c.
Referenced by BleedingSource(), and OnUpdateServer().
m_MaxTime
float m_MaxTime
Definition at line 22 of file BleedingSource.c.
Referenced by BleedingSource(), and OnUpdateServer().
m_Offset
vector m_Offset
Definition at line 19 of file BleedingSource.c.
m_Orientation
vector m_Orientation
Definition at line 15 of file BleedingSource.c.
Referenced by BleedingSource(), ScriptedWidgetEventHandler::CreateFollowedObject(), CreateParticle(), CTObjectFollower::CTActor(), ScriptedWidgetEventHandler::CTKeyframe(), ScriptedWidgetEventHandler::SetOrientation(), and ScriptedWidgetEventHandler::SetRotation().
m_ParticleName
string m_ParticleName
Definition at line 23 of file BleedingSource.c.
Referenced by BleedingSource(), and CreateParticle().
m_Player
PlayerBase m_Player
Definition at line 11 of file BleedingSource.c.
m_Position
enum eBleedingSourceType m_Position
m_Type
eBleedingSourceType m_Type = eBleedingSourceType.NORMAL
Definition at line 25 of file BleedingSource.c.
Referenced by MindStateSoundEventBase::AlertedMoveSoundEvent(), DisplayElementBadge::BadgeBleeding(), DisplayElementBadge::BadgeFracture(), DisplayElementBadge::BadgeHeartbeat(), DisplayElementBadge::BadgeLegs(), DisplayElementBadge::BadgePills(), DisplayElementBadge::BadgePoisoned(), DisplayElementBadge::BadgeSick(), DisplayElementBadge::BadgeStuffed(), DisplayElementBadge::BadgeWet(), BotStateBase::Bot_TestSpawnOpen(), BotStateBase::BotSpawnEntityInHands(), MindStateSoundEventBase::CalmMoveSoundEvent(), CalmMoveSoundEvent(), CanPlay(), MindStateSoundEventBase::ChaseMoveSoundEvent(), ChaseMoveSoundEvent(), PlayerSoundEventBase::DamageSoundEvents(), PlayerSoundEventBase::DrowningEvents(), DisplayElementBase::ElementStance(), HoldBreathSoundEventBase::ExhaustedBreathSoundEvent(), ExhaustedBreathSoundEvent(), Managed::GameplayEffectsData(), MessageReceiverBase::GetAgentType(), GetType(), MessageReceiverBase::GetType(), Managed::GetWidgetSetType(), HasPriorityOverCurrent(), PlayerSoundEventBase::HeatComfortEventsBase(), HoldBreathSoundEventBase(), InfectedSoundEventBase(), AgentBase::Init(), Managed::Init(), PlayerStatBase::Init(), Init(), PlayerSoundEventBase::InjurySoundEvents(), PlayerSoundEventBase::MeleeAttackSoundEvents(), BotStateBase::OnEntry(), OnUpdateServer(), PlayerSoundEventBase::PickupHeavySoundEvent(), PickupHeavySoundEvent(), PlayerSoundEventBase(), HandEventBase::ReadFromContext(), SetType(), StaminaModifier(), StaminaSoundEventBase::StaminaNormalDummy(), PlayerSoundEventBase::StaminaSoundEventBase(), PlayerSoundEventBase::SymptomSoundEventBase(), DisplayElementTendency::TendencyBacteria(), DisplayElementTendency::TendencyBlood(), DisplayElementTendency::TendencyHealth(), DisplayElementTendency::TendencyHunger(), DisplayElementTendency::TendencyTemperature(), DisplayElementTendency::TendencyThirst(), and HandEventBase::WriteToContext().