DayZ: scripts/4_World/Entities/ItemBase.c File Reference
ItemBase.c File Reference
Classes
class ItemBase
class InventoryItem
Typedefs
typedef ItemBase Inventory_Base
Functions
class ItemBase extends InventoryItem SpawnItemOnLocation (string object_name, notnull InventoryLocation loc, bool full_quantity)
void TransferModifiers (PlayerBase reciever)
appears to be deprecated, legacy code
void ItemBase ()
void InitItemVariables ()
bool UsesGlobalDeploy ()
override int GetQuickBarBonus ()
void InitializeActions ()
override void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
void SetActions ()
void AddAction (typename actionName)
void RemoveAction (typename actionName)
void OnItemInHandsPlayerSwimStart (PlayerBase player)
ScriptedLightBase GetLight ()
void LoadParticleConfigOnFire (int id)
void LoadParticleConfigOnOverheating (int id)
float GetOverheatingValue ()
void IncreaseOverheating (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
void CheckOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
bool IsOverheatingEffectActive ()
void OnOverheatingDecay ()
void StartOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
void UpdateOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
void StopOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
void RegisterOverheatingParticle (Particle p, float min_heat_coef, float max_heat_coef, int particle_id, Object parent, vector local_pos, vector local_ori)
float GetOverheatingCoef ()
void UpdateAllOverheatingParticles ()
void KillAllOverheatingParticles ()
float GetInfectionChance (int system=0, Param param=null)
Infection chance while/after using this item, originally used for wound infection after bandaging, params 'system' and 'param' can allow usage by other systems as well.
float GetDisinfectQuantity (int system=0, Param param1=null)
float GetFilterDamageRatio ()
bool HasMuzzle ()
Returns true if this item has a muzzle (weapons, suppressors)
int GetMuzzleID ()
Returns global muzzle ID. If not found, then it gets automatically registered.
int GetDamageSystemVersionChange ()
Re-sets DamageSystem changes.
void ~ItemBase ()
static int GetDebugActionsMask ()
static bool HasDebugActionsMask (int mask)
static void SetDebugActionsMask (int mask)
static void AddDebugActionsMask (int mask)
static void RemoveDebugActionsMask (int mask)
static void ToggleDebugActionsMask (int mask)
void SetCEBasedQuantity ()
void LockToParent ()
Locks this item in it's current attachment slot of its parent. This makes the "locked" icon visible in inventory over this item.
void UnlockFromParent ()
Unlocks this item from its attachment slot of its parent.
override void CombineItemsClient (EntityAI entity2, bool use_stack_max=true)
bool IsLiquidPresent ()
bool IsLiquidContainer ()
bool IsBloodContainer ()
bool IsNVG ()
bool IsExplosive ()
string GetExplosiveTriggerSlotName ()
bool IsLightSource ()
bool CanBeRepairedByCrafting ()
bool IsFacingPlayer (PlayerBase player, string selection)
bool IsPlayerInside (PlayerBase player, string selection)
override bool CanObstruct ()
override bool IsBeingPlaced ()
void SetIsBeingPlaced (bool is_being_placed)
void OnEndPlacement ()
override bool IsHologram ()
bool CanBeDigged ()
bool CanMakeGardenplot ()
void SetIsHologram (bool is_hologram)
override void OnMovedInsideCargo (EntityAI container)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void EOnContact (IEntity other, Contact extra)
void RefreshPhysics ()
override void OnCreatePhysics ()
override void OnItemAttachmentSlotChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void EEDelete (EntityAI parent)
override void EEKilled (Object killer)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override string ChangeIntoOnAttach (string slot)
override string ChangeIntoOnDetach ()
void ExplodeAmmo ()
void DoAmmoExplosion ()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
bool DamageItemInCargo (float damage)
bool DamageItemAttachments (float damage)
override bool CanBeSplit ()
void SplitIntoStackMaxClient (EntityAI destination_entity, int slot_id)
void SplitIntoStackMax (EntityAI destination_entity, int slot_id, PlayerBase player)
void SplitIntoStackMaxToInventoryLocationClient (notnull InventoryLocation dst)
void SplitIntoStackMaxCargoClient (EntityAI destination_entity, int idx, int row, int col)
void SplitIntoStackMaxToInventoryLocation (notnull InventoryLocation dst)
ItemBase SplitIntoStackMaxToInventoryLocationEx (notnull InventoryLocation dst)
void SplitIntoStackMaxCargo (EntityAI destination_entity, int idx, int row, int col)
void SplitIntoStackMaxHandsClient (PlayerBase player)
void SplitIntoStackMaxHands (PlayerBase player)
void SplitItemToInventoryLocation (notnull InventoryLocation dst)
void SplitItem (PlayerBase player)
void OnQuantityChanged (float delta)
Called on server side when this item's quantity is changed. Call super.OnQuantityChanged(); first when overriding this event.
void OnAttachmentQuantityChanged (ItemBase item)
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
void OnAttachmentQuantityChangedEx (ItemBase item, float delta)
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void OnRightClick ()
override bool CanBeCombined (EntityAI other_item, bool reservation_check=true, bool stack_max_limit=false)
bool IsCombineAll (ItemBase other_item, bool use_stack_max=false)
bool IsResultOfSplit ()
void SetResultOfSplit (bool value)
int ComputeQuantityUsed (ItemBase other_item, bool use_stack_max=true)
float ComputeQuantityUsedEx (ItemBase other_item, bool use_stack_max=true)
void CombineItems (ItemBase other_item, bool use_stack_max=true)
void OnCombine (ItemBase other_item)
void GetRecipesActions (Man player, out TSelectableActionInfoArray outputList)
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
override bool OnAction (int action_id, Man player, ParamsReadContext ctx)
void OnActivatedByTripWire ()
void OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
bool CanExplodeInFire ()
bool CanEat ()
override bool IsIgnoredByConstruction ()
bool HasFoodStage ()
bool CanBeCooked ()
bool CanBeCookedOnStick ()
bool CanRepair (ItemBase item_repair_kit)
bool Repair (PlayerBase player, ItemBase item_repair_kit, float specialty_weight)
int GetItemSize ()
bool CanBeMovedOverride ()
void SetCanBeMovedOverride (bool setting)
void MessageToOwnerStatus (string text)
Send message to owner player in grey color.
void MessageToOwnerAction (string text)
Send message to owner player in yellow color.
void MessageToOwnerFriendly (string text)
Send message to owner player in green color.
void MessageToOwnerImportant (string text)
Send message to owner player in red color.
override bool IsItemBase ()
override bool KindOf (string tag)
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
void TransferVariablesFloat (array< float > float_vars)
array< float > GetVariablesFloat ()
int NameToID (string name)
string IDToName (int id)
void OnSyncVariables (ParamsReadContext ctx)
void SerializeNumericalVars (array< float > floats_out)
void DeSerializeNumericalVars (array< float > floats)
void WriteVarsToCTX (ParamsWriteContext ctx)
bool ReadVarsFromCTX (ParamsReadContext ctx, int version=-1)
void SaveVariables (ParamsWriteContext ctx)
bool LoadVariables (ParamsReadContext ctx, int version=-1)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void AfterStoreLoad ()
override void EEOnAfterLoad ()
bool CanBeDisinfected ()
override void OnVariablesSynchronized ()
bool SetQuantity (float value, bool destroy_config=true, bool destroy_forced=false, bool allow_client=false, bool clamp_to_stack_max=true)
Set item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted.
bool AddQuantity (float value, bool destroy_config=true, bool destroy_forced=false)
add item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted
void SetQuantityMax ()
override void SetQuantityToMinimum ()
void SetQuantityNormalized (float value, bool destroy_config=true, bool destroy_forced=false)
Sets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, setting 0.5 will result in value 2500)
float GetQuantityNormalized ()
Gets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, value 2500 will result in 0.5)
override int GetQuantityMax ()
override int GetTargetQuantityMax (int attSlotID=-1)
int GetQuantityMin ()
int GetQuantityInit ()
bool HasQuantity ()
override float GetQuantity ()
bool IsFullQuantity ()
override float GetSingleInventoryItemWeightEx ()
float GetSingleInventoryItemWeight ()
float GetWeightSpecialized (bool forceRecalc=false)
int GetNumberOfItems ()
Returns the number of items in cargo, otherwise returns 0(non-cargo objects). Recursive.
float GetUnitWeight (bool include_wetness=true)
Obsolete, use GetWeightEx instead.
void SetVariableMask (int variable)
void RemoveItemVariable (int variable)
Removes variable from variable mask, making it appear as though the variable has never been changed from default.
bool IsVariableSet (int variable)
'true' if this variable has ever been changed from default
override void ClearInventory ()
float GetEnergy ()
override void OnEnergyConsumed ()
override void OnEnergyAdded ()
void ConvertEnergyToQuantity ()
override void SetTemperature (float value, bool allow_client=false)
override void AddTemperature (float value)
override void SetTemperatureMax ()
override float GetTemperature ()
override float GetTemperatureInit ()
override float GetTemperatureMin ()
override float GetTemperatureMax ()
float GetHeatIsolationInit ()
float GetHeatIsolation ()
float GetDryingIncrement (string pIncrementName)
float GetSoakingIncrement (string pIncrementName)
override void SetWet (float value, bool allow_client=false)
override void AddWet (float value)
override void SetWetMax ()
override float GetWet ()
override float GetWetMax ()
override float GetWetMin ()
override float GetWetInit ()
override void OnWetChanged (float newVal, float oldVal)
override void OnWetLevelChanged (EWetnessLevel newLevel, EWetnessLevel oldLevel)
override EWetnessLevel GetWetLevel ()
bool IsServerCheck (bool allow_client)
float GetItemModelLength ()
float GetItemAttachOffset ()
void SetCleanness (int value, bool allow_client=false)
bool AllowFoodConsumption ()
int GetLockType ()
string GetLockSoundSet ()
void SetColor (int r, int g, int b, int a)
void GetColor (out int r, out int g, out int b, out int a)
gets item's color variable as components
bool IsColorSet ()
string GetColorString ()
Returns item's PROCEDURAL color as formated string, i.e. "#(argb,8,8,3)color(0.15,0.15,0.15,1.0,CO)".
void SetLiquidType (int value, bool allow_client=false)
int GetLiquidTypeInit ()
int GetLiquidType ()
void OnInventoryEnter (Man player)
Event called on item when it is placed in the player(Man) inventory, passes the owner as a parameter.
void OnInventoryExit (Man player)
Event called on item when it is removed from the player(Man) inventory, passes the old owner as a parameter.
override void OnPlacementStarted (Man player)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
bool ContainsAgent (int agent_id)
override void RemoveAgent (int agent_id)
override void RemoveAllAgents ()
override void RemoveAllAgentsExcept (int agents_to_keep_mask)
override void InsertAgent (int agent, float count=1)
void TransferAgents (int agents)
transfer agents from another item
override int GetAgents ()
bool LoadAgents (ParamsReadContext ctx, int version)
void SaveAgents (ParamsWriteContext ctx)
float GetProtectionLevel (int type, bool consider_filter=false, int system=0)
override void EEOnCECreate ()
Called when entity is being created as new by CE/ Debug.
void Open ()
Implementations only.
void Close ()
bool IsOpen ()
override bool CanDisplayCargo ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
static void PlayFireParticles (ItemBase weapon, int muzzle_index, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void PlayBulletCasingEjectParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void PlayOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void UpdateOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void StopOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
override bool IsHeavyBehaviour ()
override bool IsOneHandedBehaviour ()
override bool IsTwoHandedBehaviour ()
bool IsDeployable ()
float GetDeployTime ()
how long it takes to deploy this item in seconds
override void SetTakeable (bool pState)
override bool IsTakeable ()
void PreLoadSoundAttachmentType ()
Attachment Sound Type getting from config file.
override string GetAttachmentSoundType ()
void SoundSynchRemoteReset ()
void SoundSynchRemote ()
bool IsSoundSynchRemote ()
string GetDeploySoundset ()
string GetPlaceSoundset ()
string GetLoopDeploySoundset ()
string GetDeployFinishSoundset ()
void SetIsPlaceSound (bool is_place_sound)
bool IsPlaceSound ()
void SetIsDeploySound (bool is_deploy_sound)
bool IsDeploySound ()
void PlayDeployLoopSoundEx ()
void StopDeployLoopSoundEx ()
void PlayDeploySound ()
void PlayDeployFinishSound ()
void PlayPlaceSound ()
bool CanPlayDeployLoopSound ()
void PlayAttachSound (string slot_type)
Plays sound on item attach. Be advised, the config structure may slightly change in 1.11 update to allow for more complex use.
void PlayDetachSound (string slot_type)
void OnApply (PlayerBase player)
float GetBandagingEffectivity ()
array< string > GetHeadHidingSelection ()
bool HidesSelectionBySlot ()
WrittenNoteData GetWrittenNoteData ()
void StopItemDynamicPhysics ()
void PerformDamageSystemReinit ()
void SetZoneDamageCEInit ()
Sets zone damages to match randomized global health set by CE (CE spawn only)
bool IsCoverFaceForShave (string slot_name)
DEPRECATED in use, but returns correct values nontheless. Check performed elsewhere.
void ProcessItemWetness (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB)
void ProcessItemTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB)
void ProcessItemWetnessAndTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB)
void HierarchyCheck (out bool hasParent, out bool hasRootAsPlayer, out ItemBase refParentIB)
void ProcessDecay (float delta, bool hasRootAsPlayer)
bool CanDecay ()
bool CanProcessDecay ()
bool CanHaveWetness ()
bool CanHaveTemperature ()
override void OnCEUpdate ()
bool IsCargoException4x3 (EntityAI item)
void CopyScriptPropertiesFrom (EntityAI oldItem)
void AddLightSourceItem (ItemBase lightsource)
Adds a light source child.
void RemoveLightSourceItem ()
ItemBase GetLightSourceItem ()
array< int > GetValidFinishers ()
returns an array of possible finishers
bool GetActionWidgetOverride (out typename name)
If we need a different (handheld)item action widget displayed, the logic goes in here.
bool PairWithDevice (notnull ItemBase otherDevice)
bool CanBeUsedForSuicide ()
void SetupSpawnedItem (ItemBase item, float health, float quantity)
Variables
static ref map< typename, ref TInputActionMap > m_ItemTypeActionsMap = new map<typename, ref TInputActionMap>
TInputActionMap m_InputActionMap
bool m_ActionsInitialize
static int m_DebugActionsMask
bool m_RecipesInitialized
int m_VariablesMask
float m_VarQuantity
float m_VarQuantityPrev
int m_VarQuantityInit
int m_VarQuantityMin
int m_VarQuantityMax
int m_Count
float m_VarStackMax
float m_StoreLoadedQuantity = float.LOWEST
float m_VarTemperature
float m_VarTemperatureInit
float m_VarTemperatureMin
float m_VarTemperatureMax
float m_VarWet
float m_VarWetPrev
float m_VarWetInit
float m_VarWetMin
float m_VarWetMax
int m_Cleanness
int m_CleannessInit
int m_CleannessMin
int m_CleannessMax
bool m_WantPlayImpactSound
bool m_CanPlayImpactSound = true
float m_ImpactSpeed
int m_ImpactSoundSurfaceHash
float m_HeatIsolation
float m_ItemModelLength
float m_ItemAttachOffset
int m_VarLiquidType
int m_ItemBehaviour = -1
int m_QuickBarBonus = 0
bool m_IsBeingPlaced
bool m_IsHologram
bool m_IsPlaceSound
bool m_IsDeploySound
bool m_IsTakeable
bool m_IsSoundSynchRemote
bool m_ThrowItemOnDrop
bool m_ItemBeingDroppedPhys
bool m_CanBeMovedOverride
bool m_FixDamageSystemInit = false
bool can_this_be_combined = false
bool m_CanThisBeSplit = false
bool m_IsStoreLoad = false
bool m_CanShowQuantity
bool m_HasQuantityBar
bool m_CanBeDigged
EffectSound m_DeployLoopSoundEx
distinguish if item has been created as new or it came from splitting (server only flag)
string m_SoundAttType
int m_ColorComponentR
int m_ColorComponentG
int m_ColorComponentB
int m_ColorComponentA
ItemBase m_LightSourceItem
ref TIntArray m_SingleUseActions
ref TIntArray m_ContinuousActions
ref TIntArray m_InteractActions
int m_AttachedAgents
static ref map< int, ref array< ref WeaponParticlesOnFire > > m_OnFireEffect
static ref map< int, ref array< ref WeaponParticlesOnBulletCasingEject > > m_OnBulletCasingEjectEffect
ref map< int, ref array< ref WeaponParticlesOnOverheating > > m_OnOverheatingEffect
static ref map< string, int > m_WeaponTypeToID
static int m_LastRegisteredWeaponID = 0
bool m_IsOverheatingEffectActive
float m_OverheatingShots
ref Timer m_CheckOverheating
int m_ShotsToStartOverheating = 0
int m_MaxOverheatingValue = 0
float m_OverheatingDecayInterval = 1
ref array< ref OverheatingParticle > m_OverheatingParticles
ref TStringArray m_HeadHidingSelections
bool m_HideSelectionsBySlot
PluginAdminLog m_AdminLog
ref Timer m_PhysDropTimer
ref array< int > m_CompatibleLocks = new array<int>
int m_LockType
ref EffectSound m_LockingSound
string m_LockSoundSet = ""
EffectSound m_SoundPlace
EffectSound m_SoundDeploy
EffectSound m_SoundDeployFinish
Typedef Documentation
Inventory_Base
typedef ItemBase Inventory_Base
Definition at line 1 of file ItemBase.c.
Function Documentation
AddAction()
void SpawnItemOnLocation::AddAction (typename actionName) protected
Definition at line 4990 of file ItemBase.c.
AddDebugActionsMask()
static void SpawnItemOnLocation::AddDebugActionsMask (int mask) static protected
Definition at line 5446 of file ItemBase.c.
Referenced by InventoryItem::ToggleDebugActionsMask().
AddLightSourceItem()
void SpawnItemOnLocation::AddLightSourceItem (ItemBase lightsource) protected
Adds a light source child.
Definition at line 9281 of file ItemBase.c.
AddQuantity()
bool SpawnItemOnLocation::AddQuantity (float value, bool destroy_config = true, bool destroy_forced = false) protected
add item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted
Definition at line 7900 of file ItemBase.c.
Referenced by InventoryItem::CombineItems(), Edible_Base::Consume(), InventoryItem::OnAction(), ItemBase::OnIgnitedTarget(), ItemBase::OnIgnitedTargetFailed(), ItemBase::RemovePlanks(), InventoryItem::SplitIntoStackMax(), InventoryItem::SplitIntoStackMaxCargo(), InventoryItem::SplitIntoStackMaxHands(), InventoryItem::SplitIntoStackMaxToInventoryLocationEx(), InventoryItem::SplitItem(), and InventoryItem::SplitItemToInventoryLocation().
AddTemperature()
override void SpawnItemOnLocation::AddTemperature (float value) protected
Definition at line 8194 of file ItemBase.c.
Referenced by InventoryItem::OnAction(), and InventoryItem::ProcessItemTemperature().
AddWet()
override void SpawnItemOnLocation::AddWet (float value) protected
Definition at line 8271 of file ItemBase.c.
Referenced by InventoryItem::OnAction(), FlammableBase::OnWork(), and InventoryItem::ProcessItemWetness().
AfterStoreLoad()
override void SpawnItemOnLocation::AfterStoreLoad () protected
Definition at line 7747 of file ItemBase.c.
AllowFoodConsumption()
bool SpawnItemOnLocation::AllowFoodConsumption () protected
Definition at line 8371 of file ItemBase.c.
CanBeCombined()
override bool SpawnItemOnLocation::CanBeCombined (EntityAI other_item, bool reservation_check = true, bool stack_max_limit = false) protected
Definition at line 6635 of file ItemBase.c.
CanBeCooked()
bool SpawnItemOnLocation::CanBeCooked () protected
Definition at line 7044 of file ItemBase.c.
CanBeCookedOnStick()
bool SpawnItemOnLocation::CanBeCookedOnStick () protected
Definition at line 7049 of file ItemBase.c.
CanBeDigged()
bool SpawnItemOnLocation::CanBeDigged () protected
Definition at line 5646 of file ItemBase.c.
CanBeDisinfected()
bool SpawnItemOnLocation::CanBeDisinfected () protected
Definition at line 7776 of file ItemBase.c.
CanBeMovedOverride()
bool SpawnItemOnLocation::CanBeMovedOverride () protected
Definition at line 7084 of file ItemBase.c.
CanBeRepairedByCrafting()
bool SpawnItemOnLocation::CanBeRepairedByCrafting () protected
Definition at line 5602 of file ItemBase.c.
CanBeSplit()
override bool SpawnItemOnLocation::CanBeSplit () protected
Definition at line 6180 of file ItemBase.c.
Referenced by InventoryItem::OnRightClick(), InventoryItem::SplitItem(), and InventoryItem::SplitItemToInventoryLocation().
CanBeUsedForSuicide()
bool SpawnItemOnLocation::CanBeUsedForSuicide () protected
Definition at line 9340 of file ItemBase.c.
CanDecay()
BrisketSpread Edible_Base CanDecay () protected
Definition at line 9213 of file ItemBase.c.
Referenced by InventoryItem::OnCEUpdate().
CanDisplayCargo()
override bool SpawnItemOnLocation::CanDisplayCargo () protected
Definition at line 8677 of file ItemBase.c.
CanEat()
bool SpawnItemOnLocation::CanEat () protected
Definition at line 7025 of file ItemBase.c.
CanExplodeInFire()
bool SpawnItemOnLocation::CanExplodeInFire () protected
Definition at line 7019 of file ItemBase.c.
CanHaveTemperature()
bool SpawnItemOnLocation::CanHaveTemperature () protected
Definition at line 9232 of file ItemBase.c.
Referenced by InventoryItem::OnCEUpdate().
CanHaveWetness()
bool SpawnItemOnLocation::CanHaveWetness () protected
Definition at line 9226 of file ItemBase.c.
Referenced by InventoryItem::OnCEUpdate().
CanMakeGardenplot()
bool SpawnItemOnLocation::CanMakeGardenplot () protected
Definition at line 5651 of file ItemBase.c.
CanObstruct()
override bool SpawnItemOnLocation::CanObstruct () protected
Definition at line 5619 of file ItemBase.c.
CanPlayDeployLoopSound()
bool SpawnItemOnLocation::CanPlayDeployLoopSound () protected
Definition at line 9039 of file ItemBase.c.
Referenced by InventoryItem::OnVariablesSynchronized(), ItemBase::OnVariablesSynchronized(), Inventory_Base::OnVariablesSynchronized(), and OnVariablesSynchronized().
CanProcessDecay()
override bool CanProcessDecay () protected
Definition at line 9219 of file ItemBase.c.
Referenced by InventoryItem::OnCEUpdate().
CanPutAsAttachment()
override bool SpawnItemOnLocation::CanPutAsAttachment (EntityAI parent) protected
Definition at line 8700 of file ItemBase.c.
CanPutInCargo()
override bool SpawnItemOnLocation::CanPutInCargo (EntityAI parent) protected
Definition at line 8686 of file ItemBase.c.
CanReceiveAttachment()
override bool SpawnItemOnLocation::CanReceiveAttachment (EntityAI attachment, int slotId) protected
Definition at line 8724 of file ItemBase.c.
CanReceiveItemIntoCargo()
override bool SpawnItemOnLocation::CanReceiveItemIntoCargo (EntityAI item) protected
Definition at line 8715 of file ItemBase.c.
CanRepair()
bool SpawnItemOnLocation::CanRepair (ItemBase item_repair_kit) protected
Definition at line 7055 of file ItemBase.c.
ChangeIntoOnAttach()
override string SpawnItemOnLocation::ChangeIntoOnAttach (string slot) protected
Definition at line 6003 of file ItemBase.c.
ChangeIntoOnDetach()
override string SpawnItemOnLocation::ChangeIntoOnDetach () protected
Definition at line 6027 of file ItemBase.c.
CheckOverheating()
void SpawnItemOnLocation::CheckOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "") protected
Definition at line 5192 of file ItemBase.c.
Referenced by InventoryItem::IncreaseOverheating(), and InventoryItem::OnOverheatingDecay().
ClearInventory()
override void SpawnItemOnLocation::ClearInventory () protected
Definition at line 8119 of file ItemBase.c.
Referenced by PluginBase::OnRPCClearInventory().
Close()
void SpawnItemOnLocation::Close () protected
Referenced by UIScriptedMenu::Cancel(), UIScriptedMenu::CloseMapMenu(), UIScriptedMenu::GameRespawn(), UIScriptedMenu::GameRetry(), UIScriptedMenu::Leave(), UIScriptedMenu::OnClick(), WarningMenuBase::OnClick(), OnClick(), OnKeyDown(), UIScriptedMenu::OnKeyUp(), UIScriptedMenu::OnMouseButtonUp(), FireplaceBase::OnWasDetached(), UIScriptedMenu::Update(), WarningMenuBase::Update(), and UIScriptedMenu::UpdateWarningMenu().
CombineItems()
void SpawnItemOnLocation::CombineItems (ItemBase other_item, bool use_stack_max = true) protected
Definition at line 6737 of file ItemBase.c.
Referenced by InventoryItem::CombineItemsClient().
CombineItemsClient()
override void SpawnItemOnLocation::CombineItemsClient (EntityAI entity2, bool use_stack_max = true) protected
Definition at line 5528 of file ItemBase.c.
Referenced by PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), HandsContainer::TakeAsAttachment(), and ClosableContainer::TakeAsAttachment().
ComputeQuantityUsed()
int SpawnItemOnLocation::ComputeQuantityUsed (ItemBase other_item, bool use_stack_max = true) protected
Definition at line 6713 of file ItemBase.c.
Referenced by InventoryItem::IsCombineAll().
ComputeQuantityUsedEx()
float SpawnItemOnLocation::ComputeQuantityUsedEx (ItemBase other_item, bool use_stack_max = true) protected
Definition at line 6718 of file ItemBase.c.
Referenced by InventoryItem::CombineItems(), and InventoryItem::ComputeQuantityUsed().
ContainsAgent()
bool SpawnItemOnLocation::ContainsAgent (int agent_id) protected
Definition at line 8507 of file ItemBase.c.
Referenced by InventoryItem::RemoveAgent().
ConvertEnergyToQuantity()
void SpawnItemOnLocation::ConvertEnergyToQuantity () protected
Definition at line 8166 of file ItemBase.c.
Referenced by InventoryItem::OnEnergyAdded(), and InventoryItem::OnEnergyConsumed().
CopyScriptPropertiesFrom()
void SpawnItemOnLocation::CopyScriptPropertiesFrom (EntityAI oldItem) protected
Definition at line 9275 of file ItemBase.c.
DamageItemAttachments()
bool SpawnItemOnLocation::DamageItemAttachments (float damage) protected
Definition at line 6163 of file ItemBase.c.
Referenced by InventoryItem::EEHitBy().
DamageItemInCargo()
bool SpawnItemOnLocation::DamageItemInCargo (float damage) protected
Definition at line 6144 of file ItemBase.c.
Referenced by InventoryItem::EEHitBy().
DeSerializeNumericalVars()
void SpawnItemOnLocation::DeSerializeNumericalVars (array< float > floats) protected
Definition at line 7337 of file ItemBase.c.
Referenced by InventoryItem::ReadVarsFromCTX(), and InventoryItem::TransferVariablesFloat().
DoAmmoExplosion()
void SpawnItemOnLocation::DoAmmoExplosion () protected
Definition at line 6079 of file ItemBase.c.
EEDelete()
override void SpawnItemOnLocation::EEDelete (EntityAI parent) protected
Definition at line 5925 of file ItemBase.c.
EEHealthLevelChanged()
override void SpawnItemOnLocation::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) protected
drops content of container when ruined in fireplace
Definition at line 6535 of file ItemBase.c.
EEHitBy()
override void SpawnItemOnLocation::EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) protected
Definition at line 6103 of file ItemBase.c.
EEItemLocationChanged()
override void SpawnItemOnLocation::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) protected
Definition at line 5703 of file ItemBase.c.
EEKilled()
override void SpawnItemOnLocation::EEKilled (Object killer) protected
item is able to explode in fire
Definition at line 5959 of file ItemBase.c.
EEOnAfterLoad()
override void SpawnItemOnLocation::EEOnAfterLoad () protected
Definition at line 7763 of file ItemBase.c.
EEOnCECreate()
override void SpawnItemOnLocation::EEOnCECreate () protected
Called when entity is being created as new by CE/ Debug.
Definition at line 8656 of file ItemBase.c.
EOnContact()
override void SpawnItemOnLocation::EOnContact (IEntity other, Contact extra) protected
Definition at line 5827 of file ItemBase.c.
ExplodeAmmo()
void SpawnItemOnLocation::ExplodeAmmo () protected
Definition at line 6066 of file ItemBase.c.
Referenced by InventoryItem::DoAmmoExplosion(), and InventoryItem::EEKilled().
GetActions()
override void SpawnItemOnLocation::GetActions (typename action_input_type , out array< ActionBase_Basic > actions) protected
Definition at line 4970 of file ItemBase.c.
GetActionWidgetOverride()
bool SpawnItemOnLocation::GetActionWidgetOverride (out typename name) protected
If we need a different (handheld)item action widget displayed, the logic goes in here.
Definition at line 9303 of file ItemBase.c.
GetAgents()
override int SpawnItemOnLocation::GetAgents () protected
Definition at line 8554 of file ItemBase.c.
Referenced by BakedBeansCan_Opened::CanProcessDecay(), PeachesCan_Opened::CanProcessDecay(), SardinesCan_Opened::CanProcessDecay(), SpaghettiCan_Opened::CanProcessDecay(), TunaCan_Opened::CanProcessDecay(), and Liquid::SetUpNutritionalProfile().
GetAttachmentSoundType()
override string SpawnItemOnLocation::GetAttachmentSoundType () protected
Definition at line 8929 of file ItemBase.c.
GetBandagingEffectivity()
float SpawnItemOnLocation::GetBandagingEffectivity () protected
Definition at line 9088 of file ItemBase.c.
GetColor()
void SpawnItemOnLocation::GetColor (out int r, out int g, out int b, out int a) protected
gets item's color variable as components
Definition at line 8401 of file ItemBase.c.
GetColorString()
string SpawnItemOnLocation::GetColorString () protected
Returns item's PROCEDURAL color as formated string, i.e. "#(argb,8,8,3)color(0.15,0.15,0.15,1.0,CO)".
Definition at line 8415 of file ItemBase.c.
GetDamageSystemVersionChange()
override int GetDamageSystemVersionChange () protected
Re-sets DamageSystem changes.
Returns
storage version on which the config changes occured (default -1, to be overriden!)
Note
Significant changes to DamageSystem in item configs have to be re-set by increasing the storage version and overriding this method. Default return is -1 (does nothing).
Definition at line 5384 of file ItemBase.c.
GetDebugActions()
override void SpawnItemOnLocation::GetDebugActions (out TSelectableActionInfoArrayEx outputList) protected
Definition at line 6792 of file ItemBase.c.
GetDebugActionsMask()
static int SpawnItemOnLocation::GetDebugActionsMask () static protected
Definition at line 5431 of file ItemBase.c.
GetDeployFinishSoundset()
string SpawnItemOnLocation::GetDeployFinishSoundset () protected
GetDeploySoundset()
string SpawnItemOnLocation::GetDeploySoundset () protected
Definition at line 138 of file LargeTent.c.
GetDeployTime()
float SpawnItemOnLocation::GetDeployTime () protected
how long it takes to deploy this item in seconds
Definition at line 8897 of file ItemBase.c.
GetDisinfectQuantity()
float SpawnItemOnLocation::GetDisinfectQuantity (int system = 0, Param param1 = null) protected
Definition at line 5341 of file ItemBase.c.
GetDryingIncrement()
float SpawnItemOnLocation::GetDryingIncrement (string pIncrementName) protected
Definition at line 8234 of file ItemBase.c.
Referenced by InventoryItem::ProcessItemWetness().
GetEnergy()
float SpawnItemOnLocation::GetEnergy () protected
Definition at line 8140 of file ItemBase.c.
Referenced by ItemBase::CanAddFuel(), FlammableBase::CanBeIgnitedBy(), BroomBase::CanTransformIntoStick(), InventoryItem::GetWeightSpecialized(), FlammableBase::OnWork(), Chemlight_ColorBase::OnWorkStop(), Roadflare::OnWorkStop(), FlammableBase::OnWorkStop(), and Liquid::SetUpNutritionalProfile().
GetExplosiveTriggerSlotName()
string SpawnItemOnLocation::GetExplosiveTriggerSlotName () protected
Definition at line 5590 of file ItemBase.c.
GetFilterDamageRatio()
override float GetFilterDamageRatio () protected
Definition at line 5346 of file ItemBase.c.
GetHeadHidingSelection()
array< string > SpawnItemOnLocation::GetHeadHidingSelection () protected
Definition at line 9093 of file ItemBase.c.
GetHeatIsolation()
float SpawnItemOnLocation::GetHeatIsolation () protected
Definition at line 8229 of file ItemBase.c.
GetHeatIsolationInit()
float SpawnItemOnLocation::GetHeatIsolationInit () protected
Definition at line 8224 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
GetInfectionChance()
float SpawnItemOnLocation::GetInfectionChance (int system = 0, Param param = null) protected
Infection chance while/after using this item, originally used for wound infection after bandaging, params 'system' and 'param' can allow usage by other systems as well.
Definition at line 5335 of file ItemBase.c.
GetItemAttachOffset()
float SpawnItemOnLocation::GetItemAttachOffset () protected
Definition at line 8348 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
GetItemModelLength()
float SpawnItemOnLocation::GetItemModelLength () protected
Definition at line 8339 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
GetItemSize()
int SpawnItemOnLocation::GetItemSize () protected
Definition at line 7069 of file ItemBase.c.
GetLight()
ScriptedLightBase SpawnItemOnLocation::GetLight () protected
GetLightSourceItem()
ItemBase SpawnItemOnLocation::GetLightSourceItem () protected
Definition at line 9291 of file ItemBase.c.
GetLiquidType()
int SpawnItemOnLocation::GetLiquidType () protected
Definition at line 8442 of file ItemBase.c.
Referenced by ActionFillBottleBase::ActionCondition(), InventoryItem::IsLiquidPresent(), InventoryItem::OnAction(), and InventoryItem::SetQuantity().
GetLiquidTypeInit()
int SpawnItemOnLocation::GetLiquidTypeInit () protected
Definition at line 8437 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
GetLockSoundSet()
string SpawnItemOnLocation::GetLockSoundSet () protected
Definition at line 8384 of file ItemBase.c.
GetLockType()
int SpawnItemOnLocation::GetLockType () protected
Definition at line 8379 of file ItemBase.c.
GetLoopDeploySoundset()
string SpawnItemOnLocation::GetLoopDeploySoundset () protected
Definition at line 143 of file LargeTent.c.
GetMuzzleID()
int SpawnItemOnLocation::GetMuzzleID () protected
Returns global muzzle ID. If not found, then it gets automatically registered.
Definition at line 5361 of file ItemBase.c.
Referenced by InventoryItem::ItemBase().
GetNumberOfItems()
int SpawnItemOnLocation::GetNumberOfItems () protected
Returns the number of items in cargo, otherwise returns 0(non-cargo objects). Recursive.
Definition at line 8059 of file ItemBase.c.
Referenced by Barrel_ColorBase::CanDetachAttachment(), FireplaceBase::CanDetachAttachment(), ClothingBase::CanPutAsAttachment(), Barrel_ColorBase::CanPutInCargo(), Clothing::CanPutInCargo(), Clothing_Base::CanPutInCargoClothingConditions(), and Barrel_ColorBase::CanPutIntoHands().
GetOverheatingCoef()
float SpawnItemOnLocation::GetOverheatingCoef () protected
Definition at line 5271 of file ItemBase.c.
Referenced by InventoryItem::UpdateAllOverheatingParticles().
GetOverheatingValue()
float SpawnItemOnLocation::GetOverheatingValue () protected
Definition at line 5171 of file ItemBase.c.
GetPlaceSoundset()
string SpawnItemOnLocation::GetPlaceSoundset () protected
Definition at line 2438 of file FireplaceBase.c.
GetProtectionLevel()
float SpawnItemOnLocation::GetProtectionLevel (int type, bool consider_filter = false, int system = 0) protected
Definition at line 8617 of file ItemBase.c.
GetQuantity()
override float SpawnItemOnLocation::GetQuantity () protected
Definition at line 7995 of file ItemBase.c.
Referenced by InventoryItem::AddQuantity(), InventoryItem::CanBeCombined(), InventoryItem::CanBeSplit(), ItemBase::CanIgniteItem(), Clothing::CanPutAsAttachment(), ItemBase::CanPutAsAttachment(), InventoryItem::CombineItems(), InventoryItem::ComputeQuantityUsedEx(), Mask_Base::ConsumeQuantity(), Barrel_ColorBase::DetermineAction(), Mask_Base::GetFilterQuantity(), Mask_Base::GetFilterQuantity01(), InventoryItem::GetProtectionLevel(), FlammableBase::GetRagQuantity(), InventoryItem::GetWeightSpecialized(), Mask_Base::HasValidFilter(), LargeGasCanister::IsDestructionBehaviour(), MediumGasCanister::IsDestructionBehaviour(), SmallGasCanister::IsDestructionBehaviour(), InventoryItem::IsFullQuantity(), ItemBase::RemovePlanks(), InventoryItem::SplitIntoStackMax(), InventoryItem::SplitIntoStackMaxCargo(), InventoryItem::SplitIntoStackMaxHands(), InventoryItem::SplitIntoStackMaxToInventoryLocationEx(), InventoryItem::SplitItem(), InventoryItem::SplitItemToInventoryLocation(), FlammableBase::UpdateLight(), BroomBase::UpdateParticle(), FlammableBase::UpdateParticle(), and ItemBase::UpdateSelections().
GetQuantityInit()
int SpawnItemOnLocation::GetQuantityInit () protected
Definition at line 7984 of file ItemBase.c.
GetQuantityMax()
override int SpawnItemOnLocation::GetQuantityMax () protected
Definition at line 7941 of file ItemBase.c.
Referenced by CalcAndSetQuantity(), InventoryItem::CanBeCombined(), Capture(), InventoryItem::ComputeQuantityUsedEx(), Edible_Base::GetDisinfectQuantity(), DisinfectantAlcohol::GetDisinfectQuantity(), IodineTincture::GetDisinfectQuantity(), Mask_Base::GetFilterQuantity01(), Mask_Base::GetFilterQuantityMax(), InventoryItem::GetQuantityNormalized(), InventoryItem::HasQuantity(), InventoryItem::IsFullQuantity(), InventoryItem::OnAction(), InventoryItem::SetQuantity(), InventoryItem::SetQuantityMax(), InventoryItem::SetQuantityNormalized(), BroomBase::UpdateParticle(), and ItemBase::UpdateSelections().
GetQuantityMin()
int SpawnItemOnLocation::GetQuantityMin () protected
Definition at line 7979 of file ItemBase.c.
Referenced by InventoryItem::GetQuantityNormalized(), InventoryItem::HasQuantity(), InventoryItem::InitItemVariables(), InventoryItem::OnWasAttached(), InventoryItem::OnWasDetached(), Release(), InventoryItem::SetQuantity(), InventoryItem::SetQuantityNormalized(), and InventoryItem::SetQuantityToMinimum().
GetQuantityNormalized()
float SpawnItemOnLocation::GetQuantityNormalized () protected
Gets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, value 2500 will result in 0.5)
Definition at line 7927 of file ItemBase.c.
GetQuickBarBonus()
override int SpawnItemOnLocation::GetQuickBarBonus () protected
Definition at line 4953 of file ItemBase.c.
GetRecipesActions()
void SpawnItemOnLocation::GetRecipesActions (Man player, out TSelectableActionInfoArray outputList) protected
Definition at line 6771 of file ItemBase.c.
GetSingleInventoryItemWeight()
float SpawnItemOnLocation::GetSingleInventoryItemWeight () protected
Definition at line 8015 of file ItemBase.c.
GetSingleInventoryItemWeightEx()
override float SpawnItemOnLocation::GetSingleInventoryItemWeightEx () protected
Definition at line 8006 of file ItemBase.c.
Referenced by InventoryItem::GetSingleInventoryItemWeight(), and Entity::OnAction().
GetSoakingIncrement()
float SpawnItemOnLocation::GetSoakingIncrement (string pIncrementName) protected
Definition at line 8243 of file ItemBase.c.
GetTargetQuantityMax()
override int SpawnItemOnLocation::GetTargetQuantityMax (int attSlotID = -1) protected
Definition at line 7963 of file ItemBase.c.
Referenced by InventoryItem::SplitIntoStackMax(), InventoryItem::SplitIntoStackMaxCargo(), InventoryItem::SplitIntoStackMaxHands(), and InventoryItem::SplitIntoStackMaxToInventoryLocationEx().
GetTemperature()
override float SpawnItemOnLocation::GetTemperature () protected
Definition at line 8204 of file ItemBase.c.
Referenced by AddDamageToItemByFireEx(), InventoryItem::AddTemperature(), AddWetnessToFireplace(), CanCookOnStick(), CanDismantleOven(), Cooling(), InventoryItem::DoAmmoExplosion(), InventoryItem::EEKilled(), Heating(), InventoryItem::ProcessItemTemperature(), and RefreshFireState().
GetTemperatureInit()
override float SpawnItemOnLocation::GetTemperatureInit () protected
Definition at line 8209 of file ItemBase.c.
GetTemperatureMax()
override float SpawnItemOnLocation::GetTemperatureMax () protected
Definition at line 8219 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), and InventoryItem::SetTemperature().
GetTemperatureMin()
override float SpawnItemOnLocation::GetTemperatureMin () protected
Definition at line 8214 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), InventoryItem::ProcessItemTemperature(), and InventoryItem::SetTemperature().
GetUnitWeight()
float SpawnItemOnLocation::GetUnitWeight (bool include_wetness = true) protected
Obsolete, use GetWeightEx instead.
Definition at line 8079 of file ItemBase.c.
GetValidFinishers()
array< int > SpawnItemOnLocation::GetValidFinishers () protected
returns an array of possible finishers
Definition at line 9297 of file ItemBase.c.
GetVariablesFloat()
array< float > SpawnItemOnLocation::GetVariablesFloat () protected
Definition at line 7251 of file ItemBase.c.
GetWeightSpecialized()
float SpawnItemOnLocation::GetWeightSpecialized (bool forceRecalc = false) protected
Definition at line 8020 of file ItemBase.c.
Referenced by Entity::GetWeightEx().
GetWet()
override float SpawnItemOnLocation::GetWet () protected
Definition at line 8281 of file ItemBase.c.
Referenced by InventoryItem::AddWet(), AddWetnessToFireplace(), CanBeIgnitedBy(), ItemBase::CanIgniteItem(), Cooling(), InventoryItem::GetUnitWeight(), Heating(), and StartHeating().
GetWetInit()
override float SpawnItemOnLocation::GetWetInit () protected
Definition at line 8296 of file ItemBase.c.
GetWetLevel()
override EWetnessLevel SpawnItemOnLocation::GetWetLevel () protected
Definition at line 8316 of file ItemBase.c.
Referenced by Entity::GetWetWeightModifier().
GetWetMax()
override float SpawnItemOnLocation::GetWetMax () protected
Definition at line 8286 of file ItemBase.c.
Referenced by Entity::HasWetness(), InventoryItem::InitItemVariables(), InventoryItem::OnAction(), and InventoryItem::SetWet().
GetWetMin()
override float SpawnItemOnLocation::GetWetMin () protected
Definition at line 8291 of file ItemBase.c.
Referenced by Entity::HasWetness(), InventoryItem::InitItemVariables(), and InventoryItem::SetWet().
GetWrittenNoteData()
WrittenNoteData SpawnItemOnLocation::GetWrittenNoteData () protected
Definition at line 9103 of file ItemBase.c.
HasDebugActionsMask()
static bool SpawnItemOnLocation::HasDebugActionsMask (int mask) static protected
Definition at line 5436 of file ItemBase.c.
Referenced by InventoryItem::ToggleDebugActionsMask().
HasFoodStage()
bool SpawnItemOnLocation::HasFoodStage () protected
Definition at line 7038 of file ItemBase.c.
Referenced by Edible_Base::Edible_Base(), and Edible_Base::GetDebugActions().
HasMuzzle()
bool SpawnItemOnLocation::HasMuzzle () protected
Returns true if this item has a muzzle (weapons, suppressors)
Definition at line 5352 of file ItemBase.c.
Referenced by InventoryItem::ItemBase().
HasQuantity()
bool SpawnItemOnLocation::HasQuantity () protected
Definition at line 7990 of file ItemBase.c.
Referenced by ItemBase::CatchSetQuant(), Mask_Base::ConsumeQuantity(), InventoryItem::ConvertEnergyToQuantity(), CAContinuousMineWood::CreatePrimaryItems(), Mask_Base::GetFilterQuantityMax(), InventoryItem::GetProtectionLevel(), Mask_Base::HasIntegratedFilter(), InventoryItem::InitItemVariables(), InventoryItem::IsLiquidPresent(), InventoryItem::OnWasAttached(), InventoryItem::OnWasDetached(), InventoryItem::SetCEBasedQuantity(), and InventoryItem::SetQuantity().
HidesSelectionBySlot()
bool SpawnItemOnLocation::HidesSelectionBySlot () protected
Definition at line 9098 of file ItemBase.c.
HierarchyCheck()
void SpawnItemOnLocation::HierarchyCheck (out bool hasParent, out bool hasRootAsPlayer, out ItemBase refParentIB) protected
Definition at line 9191 of file ItemBase.c.
Referenced by InventoryItem::OnCEUpdate().
IDToName()
string SpawnItemOnLocation::IDToName (int id) protected
Definition at line 7264 of file ItemBase.c.
IncreaseOverheating()
void SpawnItemOnLocation::IncreaseOverheating (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) protected
Definition at line 5176 of file ItemBase.c.
Referenced by Weapon::EEFired().
InitializeActions()
void SpawnItemOnLocation::InitializeActions () protected
Definition at line 4958 of file ItemBase.c.
InitItemVariables()
void SpawnItemOnLocation::InitItemVariables () protected
Definition at line 4861 of file ItemBase.c.
InsertAgent()
override void SpawnItemOnLocation::InsertAgent (int agent, float count = 1) protected
Definition at line 8539 of file ItemBase.c.
Referenced by Bottle_Base::EEOnCECreate(), Edible_Base::HumanSteakMeat(), InventoryItem::OnAction(), Edible_Base::ProcessDecay(), and ManBase::SetBloodyHandsPenalty().
IsBeingPlaced()
override bool SpawnItemOnLocation::IsBeingPlaced () protected
Definition at line 5625 of file ItemBase.c.
Referenced by InventoryItem::CanPlayDeployLoopSound(), OnInventoryExit(), ItemBase::OnItemLocationChanged(), Barrel_ColorBase::OnVariablesSynchronized(), and FireplaceBase::OnVariablesSynchronized().
IsBloodContainer()
bool SpawnItemOnLocation::IsBloodContainer () protected
Definition at line 5573 of file ItemBase.c.
IsCargoException4x3()
bool SpawnItemOnLocation::IsCargoException4x3 (EntityAI item) protected
Definition at line 9270 of file ItemBase.c.
Referenced by Bottle_Base::CanLoadItemIntoCargo(), Inventory_Base::CanLoadItemIntoCargo(), Bottle_Base::CanPutInCargo(), Inventory_Base::CanPutInCargo(), Bottle_Base::CanReceiveItemIntoCargo(), and Inventory_Base::CanReceiveItemIntoCargo().
IsColorSet()
bool SpawnItemOnLocation::IsColorSet () protected
Definition at line 8409 of file ItemBase.c.
IsCombineAll()
bool SpawnItemOnLocation::IsCombineAll (ItemBase other_item, bool use_stack_max = false) protected
Definition at line 6698 of file ItemBase.c.
Referenced by InventoryItem::CombineItemsClient().
IsCoverFaceForShave()
bool SpawnItemOnLocation::IsCoverFaceForShave (string slot_name) protected
DEPRECATED in use, but returns correct values nontheless. Check performed elsewhere.
Definition at line 9136 of file ItemBase.c.
IsDeployable()
bool SpawnItemOnLocation::IsDeployable () protected
Definition at line 8891 of file ItemBase.c.
IsDeploySound()
bool SpawnItemOnLocation::IsDeploySound () protected
Definition at line 8977 of file ItemBase.c.
Referenced by InventoryItem::OnVariablesSynchronized(), ItemBase::OnVariablesSynchronized(), Inventory_Base::OnVariablesSynchronized(), and OnVariablesSynchronized().
IsExplosive()
bool SpawnItemOnLocation::IsExplosive () protected
explosive
Definition at line 5585 of file ItemBase.c.
IsFacingPlayer()
bool SpawnItemOnLocation::IsFacingPlayer (PlayerBase player, string selection) protected
Definition at line 5609 of file ItemBase.c.
IsFullQuantity()
bool SpawnItemOnLocation::IsFullQuantity () protected
Definition at line 8000 of file ItemBase.c.
Referenced by InventoryItem::CanBeCombined(), and CAContinuousMineWood::CreatePrimaryItems().
IsHeavyBehaviour()
override bool SpawnItemOnLocation::IsHeavyBehaviour () protected
Definition at line 8861 of file ItemBase.c.
Referenced by Start().
IsHologram()
override bool SpawnItemOnLocation::IsHologram () protected
Definition at line 5641 of file ItemBase.c.
Referenced by ItemBase::AssembleKit(), IEntity::CanBeActionTarget(), Entity::CanPutAsAttachment(), Entity::CanPutInCargo(), Entity::CanPutIntoHands(), KitBase::DisassembleKit(), ItemBase::EOnInit(), ItemBase::Pack(), RefreshFireplaceVisuals(), and ItemBase::UpdateAllSelections().
IsIgnoredByConstruction()
override bool SpawnItemOnLocation::IsIgnoredByConstruction () protected
Definition at line 7031 of file ItemBase.c.
IsItemBase()
override bool SpawnItemOnLocation::IsItemBase () protected
Definition at line 7168 of file ItemBase.c.
Referenced by IEntity::CanBeIgnoredByDroppedItem().
IsLightSource()
bool SpawnItemOnLocation::IsLightSource () protected
Definition at line 5597 of file ItemBase.c.
IsLiquidContainer()
bool SpawnItemOnLocation::IsLiquidContainer () protected
Definition at line 5568 of file ItemBase.c.
Referenced by InventoryItem::GetDebugActions(), and InventoryItem::SetQuantity().
IsLiquidPresent()
bool SpawnItemOnLocation::IsLiquidPresent () protected
Definition at line 5562 of file ItemBase.c.
IsNVG()
bool SpawnItemOnLocation::IsNVG () protected
Definition at line 5578 of file ItemBase.c.
IsOneHandedBehaviour()
override bool SpawnItemOnLocation::IsOneHandedBehaviour () protected
Definition at line 8871 of file ItemBase.c.
IsOpen()
override bool IsOpen () protected
Definition at line 8672 of file ItemBase.c.
Referenced by FireplaceBase::CanBeIgnitedBy(), FireplaceBase::CanDisplayAttachmentCategory(), InventoryItem::CanDisplayCargo(), FireplaceBase::CanDisplayCargo(), FireplaceBase::CanExtinguishFire(), FireplaceBase::CanIgniteItem(), FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), FireplaceBase::CanReceiveAttachment(), FireplaceBase::CanReceiveItemIntoCargo(), FireplaceBase::CanReleaseCargo(), FireplaceBase::CanShowSmoke(), FireplaceBase::IsThisIgnitionSuccessful(), FireplaceBase::OnVariablesSynchronized(), and FireplaceBase::UpdateVisualState().
IsOverheatingEffectActive()
bool SpawnItemOnLocation::IsOverheatingEffectActive () protected
Definition at line 5209 of file ItemBase.c.
Referenced by InventoryItem::CheckOverheating().
IsPlaceSound()
bool SpawnItemOnLocation::IsPlaceSound () protected
Definition at line 8967 of file ItemBase.c.
Referenced by Barrel_ColorBase::OnVariablesSynchronized(), ItemBase::OnVariablesSynchronized(), OnVariablesSynchronized(), and TrapSpawnBase::OnVariablesSynchronized().
IsPlayerInside()
bool SpawnItemOnLocation::IsPlayerInside (PlayerBase player, string selection) protected
Definition at line 5614 of file ItemBase.c.
IsResultOfSplit()
bool SpawnItemOnLocation::IsResultOfSplit () protected
Definition at line 6703 of file ItemBase.c.
Referenced by InventoryItem::EEHealthLevelChanged().
IsServerCheck()
bool SpawnItemOnLocation::IsServerCheck (bool allow_client) protected
Definition at line 8322 of file ItemBase.c.
Referenced by InventoryItem::SetCleanness(), InventoryItem::SetLiquidType(), InventoryItem::SetQuantity(), InventoryItem::SetTemperature(), and InventoryItem::SetWet().
IsSoundSynchRemote()
bool SpawnItemOnLocation::IsSoundSynchRemote () protected
Definition at line 8952 of file ItemBase.c.
Referenced by InventoryItem::CanPlayDeployLoopSound(), Barrel_ColorBase::OnVariablesSynchronized(), FireplaceBase::OnVariablesSynchronized(), and ItemBase::OnVariablesSynchronized().
IsTakeable()
override bool SpawnItemOnLocation::IsTakeable () protected
Definition at line 8911 of file ItemBase.c.
IsTwoHandedBehaviour()
override bool SpawnItemOnLocation::IsTwoHandedBehaviour () protected
Definition at line 8881 of file ItemBase.c.
IsVariableSet()
bool SpawnItemOnLocation::IsVariableSet (int variable) protected
'true' if this variable has ever been changed from default
Definition at line 8112 of file ItemBase.c.
Referenced by InventoryItem::IsColorSet(), InventoryItem::SerializeNumericalVars(), and InventoryItem::WriteVarsToCTX().
ItemBase()
void SpawnItemOnLocation::ItemBase () protected
Definition at line 4810 of file ItemBase.c.
KillAllOverheatingParticles()
void SpawnItemOnLocation::KillAllOverheatingParticles () protected
Definition at line 5307 of file ItemBase.c.
Referenced by InventoryItem::UpdateOverheating().
KindOf()
override bool SpawnItemOnLocation::KindOf (string tag) protected
Definition at line 7174 of file ItemBase.c.
LoadAgents()
bool SpawnItemOnLocation::LoadAgents (ParamsReadContext ctx, int version) protected
Definition at line 8601 of file ItemBase.c.
Referenced by InventoryItem::OnStoreLoad().
LoadParticleConfigOnFire()
void SpawnItemOnLocation::LoadParticleConfigOnFire (int id) protected
Definition at line 5046 of file ItemBase.c.
Referenced by InventoryItem::ItemBase().
LoadParticleConfigOnOverheating()
void SpawnItemOnLocation::LoadParticleConfigOnOverheating (int id) protected
Definition at line 5115 of file ItemBase.c.
Referenced by InventoryItem::ItemBase().
LoadVariables()
bool SpawnItemOnLocation::LoadVariables (ParamsReadContext ctx, int version = -1) protected
Definition at line 7577 of file ItemBase.c.
Referenced by InventoryItem::OnStoreLoad().
LockToParent()
void SpawnItemOnLocation::LockToParent () protected
Locks this item in it's current attachment slot of its parent. This makes the "locked" icon visible in inventory over this item.
Definition at line 5503 of file ItemBase.c.
MessageToOwnerAction()
void SpawnItemOnLocation::MessageToOwnerAction (string text) protected
Send message to owner player in yellow color.
Returns
void
item_stone.MessageToOwnerAction("Some Action Message");
Definition at line 7122 of file ItemBase.c.
MessageToOwnerFriendly()
void SpawnItemOnLocation::MessageToOwnerFriendly (string text) protected
Send message to owner player in green color.
Returns
void
item_stone.MessageToOwnerFriendly("Some Friendly Message");
Definition at line 7140 of file ItemBase.c.
MessageToOwnerImportant()
void SpawnItemOnLocation::MessageToOwnerImportant (string text) protected
Send message to owner player in red color.
Returns
void
item_stone.MessageToOwnerImportant("Some Important Message");
Definition at line 7158 of file ItemBase.c.
MessageToOwnerStatus()
void SpawnItemOnLocation::MessageToOwnerStatus (string text) protected
Send message to owner player in grey color.
Returns
void
item_stone.MessageToOwnerStatus("Some Status Message");
Definition at line 7104 of file ItemBase.c.
NameToID()
int SpawnItemOnLocation::NameToID (string name) protected
Definition at line 7258 of file ItemBase.c.
OnAction()
override bool SpawnItemOnLocation::OnAction (int action_id, Man player, ParamsReadContext ctx) protected
Definition at line 6834 of file ItemBase.c.
OnActivatedByItem()
void SpawnItemOnLocation::OnActivatedByItem (notnull ItemBase item) protected
Called when this item is activated by other.
Definition at line 293 of file RemoteDetonator.c.
References ParticleList::BOLT_CUPID_HIT, DeleteThis(), and ParticleManager().
OnActivatedByTripWire()
void SpawnItemOnLocation::OnActivatedByTripWire () protected
DEPRECATED use OnActivatedByItem below Called when this item is activated from a trip wire that was stepped on.
OnApply()
void SpawnItemOnLocation::OnApply (PlayerBase player) protected
OnAttachmentQuantityChanged()
void SpawnItemOnLocation::OnAttachmentQuantityChanged (ItemBase item) protected
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
Definition at line 6524 of file ItemBase.c.
Referenced by InventoryItem::OnAttachmentQuantityChangedEx().
OnAttachmentQuantityChangedEx()
void SpawnItemOnLocation::OnAttachmentQuantityChangedEx (ItemBase item, float delta) protected
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
Definition at line 6530 of file ItemBase.c.
OnCEUpdate()
override void SpawnItemOnLocation::OnCEUpdate () protected
Definition at line 9238 of file ItemBase.c.
OnCombine()
void SpawnItemOnLocation::OnCombine (ItemBase other_item) protected
Definition at line 6763 of file ItemBase.c.
OnCreatePhysics()
override void SpawnItemOnLocation::OnCreatePhysics () protected
Definition at line 5857 of file ItemBase.c.
OnEndPlacement()
void SpawnItemOnLocation::OnEndPlacement () protected
Definition at line 5639 of file ItemBase.c.
OnEnergyAdded()
override void SpawnItemOnLocation::OnEnergyAdded () protected
Definition at line 8158 of file ItemBase.c.
OnEnergyConsumed()
override void SpawnItemOnLocation::OnEnergyConsumed () protected
Definition at line 8151 of file ItemBase.c.
OnInventoryEnter()
void SpawnItemOnLocation::OnInventoryEnter (Man player) protected
Event called on item when it is placed in the player(Man) inventory, passes the owner as a parameter.
Definition at line 8449 of file ItemBase.c.
OnInventoryExit()
void SpawnItemOnLocation::OnInventoryExit (Man player) protected
Event called on item when it is removed from the player(Man) inventory, passes the old owner as a parameter.
Definition at line 8462 of file ItemBase.c.
OnItemAttachmentSlotChanged()
override void SpawnItemOnLocation::OnItemAttachmentSlotChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) protected
Definition at line 5862 of file ItemBase.c.
Referenced by Entity::EEItemLocationChanged().
OnItemInHandsPlayerSwimStart()
void SpawnItemOnLocation::OnItemInHandsPlayerSwimStart (PlayerBase player) protected
OnItemLocationChanged()
override void SpawnItemOnLocation::OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) protected
Definition at line 5867 of file ItemBase.c.
Referenced by Entity::EEItemLocationChanged().
OnMovedInsideCargo()
override void SpawnItemOnLocation::OnMovedInsideCargo (EntityAI container) protected
Definition at line 5696 of file ItemBase.c.
OnOverheatingDecay()
void SpawnItemOnLocation::OnOverheatingDecay () protected
Definition at line 5214 of file ItemBase.c.
OnPlacementComplete()
override void SpawnItemOnLocation::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") protected
Definition at line 8490 of file ItemBase.c.
OnPlacementStarted()
override void SpawnItemOnLocation::OnPlacementStarted (Man player) protected
Definition at line 8483 of file ItemBase.c.
OnQuantityChanged()
void SpawnItemOnLocation::OnQuantityChanged (float delta) protected
Called on server side when this item's quantity is changed. Call super.OnQuantityChanged(); first when overriding this event.
Definition at line 6512 of file ItemBase.c.
Referenced by InventoryItem::SetQuantity().
OnRightClick()
override void SpawnItemOnLocation::OnRightClick () protected
Definition at line 6573 of file ItemBase.c.
OnRPC()
override void SpawnItemOnLocation::OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) protected
Definition at line 7194 of file ItemBase.c.
OnStoreLoad()
override bool SpawnItemOnLocation::OnStoreLoad (ParamsReadContext ctx, int version) protected
Definition at line 7620 of file ItemBase.c.
OnStoreSave()
override void SpawnItemOnLocation::OnStoreSave (ParamsWriteContext ctx) protected
Definition at line 7719 of file ItemBase.c.
OnSyncVariables()
void SpawnItemOnLocation::OnSyncVariables (ParamsReadContext ctx) protected
Definition at line 7270 of file ItemBase.c.
OnVariablesSynchronized()
override void SpawnItemOnLocation::OnVariablesSynchronized () protected
Definition at line 7783 of file ItemBase.c.
OnWasAttached()
override void SpawnItemOnLocation::OnWasAttached (EntityAI parent, int slot_id) protected
Definition at line 5983 of file ItemBase.c.
Referenced by Entity::EEItemLocationChanged().
OnWasDetached()
override void SpawnItemOnLocation::OnWasDetached (EntityAI parent, int slot_id) protected
Definition at line 5995 of file ItemBase.c.
OnWetChanged()
override void SpawnItemOnLocation::OnWetChanged (float newVal, float oldVal) protected
Definition at line 8301 of file ItemBase.c.
Referenced by InventoryItem::OnVariablesSynchronized(), and InventoryItem::SetWet().
OnWetLevelChanged()
override void SpawnItemOnLocation::OnWetLevelChanged (EWetnessLevel newLevel, EWetnessLevel oldLevel) protected
Definition at line 8311 of file ItemBase.c.
Referenced by InventoryItem::OnWetChanged().
Open()
override void Open () protected
Implementations only.
Definition at line 88 of file CannedFood.c.
Referenced by FireplaceBase::OnWasAttached().
PairWithDevice()
bool SpawnItemOnLocation::PairWithDevice (notnull ItemBase otherDevice) protected
Definition at line 9308 of file ItemBase.c.
Referenced by ClaymoreMine::OnDebugSpawn(), and ClaymoreMine::OnPlacementComplete().
PerformDamageSystemReinit()
void SpawnItemOnLocation::PerformDamageSystemReinit () protected
Definition at line 9111 of file ItemBase.c.
Referenced by InventoryItem::AfterStoreLoad().
PlayAttachSound()
void SpawnItemOnLocation::PlayAttachSound (string slot_type) protected
Plays sound on item attach. Be advised, the config structure may slightly change in 1.11 update to allow for more complex use.
Definition at line 9045 of file ItemBase.c.
Referenced by InventoryItem::OnWasAttached().
PlayBulletCasingEjectParticles()
static void SpawnItemOnLocation::PlayBulletCasingEjectParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) static protected
Definition at line 8780 of file ItemBase.c.
PlayDeployFinishSound()
void SpawnItemOnLocation::PlayDeployFinishSound () protected
Definition at line 9015 of file ItemBase.c.
Referenced by ItemBase::OnVariablesSynchronized().
PlayDeployLoopSoundEx()
void SpawnItemOnLocation::PlayDeployLoopSoundEx () protected
Definition at line 8982 of file ItemBase.c.
Referenced by InventoryItem::OnVariablesSynchronized().
PlayDeploySound()
void SpawnItemOnLocation::PlayDeploySound () protected
Definition at line 9003 of file ItemBase.c.
Referenced by InventoryItem::OnVariablesSynchronized(), ItemBase::OnVariablesSynchronized(), Inventory_Base::OnVariablesSynchronized(), and OnVariablesSynchronized().
PlayDetachSound()
void SpawnItemOnLocation::PlayDetachSound (string slot_type) protected
Definition at line 9081 of file ItemBase.c.
PlayFireParticles()
static void SpawnItemOnLocation::PlayFireParticles (ItemBase weapon, int muzzle_index, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) static protected
Definition at line 8760 of file ItemBase.c.
PlayOverheatingParticles()
static void SpawnItemOnLocation::PlayOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) static protected
Definition at line 8800 of file ItemBase.c.
PlayPlaceSound()
void SpawnItemOnLocation::PlayPlaceSound () protected
Definition at line 9027 of file ItemBase.c.
Referenced by Barrel_ColorBase::OnVariablesSynchronized(), ItemBase::OnVariablesSynchronized(), OnVariablesSynchronized(), and TrapSpawnBase::OnVariablesSynchronized().
PreLoadSoundAttachmentType()
void SpawnItemOnLocation::PreLoadSoundAttachmentType () protected
Attachment Sound Type getting from config file.
Definition at line 8917 of file ItemBase.c.
Referenced by InventoryItem::ItemBase().
ProcessDecay()
void SpawnItemOnLocation::ProcessDecay (float delta, bool hasRootAsPlayer) protected
Definition at line 9208 of file ItemBase.c.
Referenced by InventoryItem::OnCEUpdate().
ProcessItemTemperature()
void SpawnItemOnLocation::ProcessItemTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB) protected
Definition at line 9166 of file ItemBase.c.
Referenced by InventoryItem::OnCEUpdate(), and InventoryItem::ProcessItemWetnessAndTemperature().
ProcessItemWetness()
void SpawnItemOnLocation::ProcessItemWetness (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB) protected
Definition at line 9141 of file ItemBase.c.
Referenced by InventoryItem::OnCEUpdate(), and InventoryItem::ProcessItemWetnessAndTemperature().
ProcessItemWetnessAndTemperature()
void SpawnItemOnLocation::ProcessItemWetnessAndTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB) protected
Definition at line 9185 of file ItemBase.c.
ReadVarsFromCTX()
bool SpawnItemOnLocation::ReadVarsFromCTX (ParamsReadContext ctx, int version = -1) protected
Definition at line 7440 of file ItemBase.c.
Referenced by InventoryItem::LoadVariables(), and InventoryItem::OnSyncVariables().
RefreshPhysics()
void SpawnItemOnLocation::RefreshPhysics () protected
RegisterOverheatingParticle()
void SpawnItemOnLocation::RegisterOverheatingParticle (Particle p, float min_heat_coef, float max_heat_coef, int particle_id, Object parent, vector local_pos, vector local_ori) protected
Definition at line 5257 of file ItemBase.c.
RemoveAction()
void SpawnItemOnLocation::RemoveAction (typename actionName) protected
Definition at line 5028 of file ItemBase.c.
RemoveAgent()
override void SpawnItemOnLocation::RemoveAgent (int agent_id) protected
Definition at line 8520 of file ItemBase.c.
Referenced by InventoryItem::OnAction().
RemoveAllAgents()
override void SpawnItemOnLocation::RemoveAllAgents () protected
Definition at line 8529 of file ItemBase.c.
Referenced by InventoryItem::SetQuantity().
RemoveAllAgentsExcept()
override void SpawnItemOnLocation::RemoveAllAgentsExcept (int agents_to_keep_mask) protected
Definition at line 8534 of file ItemBase.c.
RemoveDebugActionsMask()
static void SpawnItemOnLocation::RemoveDebugActionsMask (int mask) static protected
Definition at line 5451 of file ItemBase.c.
Referenced by InventoryItem::ToggleDebugActionsMask().
RemoveItemVariable()
void SpawnItemOnLocation::RemoveItemVariable (int variable) protected
Removes variable from variable mask, making it appear as though the variable has never been changed from default.
Definition at line 8106 of file ItemBase.c.
RemoveLightSourceItem()
void SpawnItemOnLocation::RemoveLightSourceItem () protected
Definition at line 9286 of file ItemBase.c.
Repair()
bool SpawnItemOnLocation::Repair (PlayerBase player, ItemBase item_repair_kit, float specialty_weight) protected
Definition at line 7062 of file ItemBase.c.
SaveAgents()
void SpawnItemOnLocation::SaveAgents (ParamsWriteContext ctx) protected
Definition at line 8608 of file ItemBase.c.
Referenced by InventoryItem::OnStoreSave().
SaveVariables()
void SpawnItemOnLocation::SaveVariables (ParamsWriteContext ctx) protected
Definition at line 7554 of file ItemBase.c.
Referenced by InventoryItem::OnStoreSave().
SerializeNumericalVars()
void SpawnItemOnLocation::SerializeNumericalVars (array< float > floats_out) protected
Definition at line 7297 of file ItemBase.c.
Referenced by InventoryItem::GetVariablesFloat().
SetActions()
void SpawnItemOnLocation::SetActions () protected
Definition at line 4981 of file ItemBase.c.
SetCanBeMovedOverride()
void SpawnItemOnLocation::SetCanBeMovedOverride (bool setting) protected
Definition at line 7091 of file ItemBase.c.
SetCEBasedQuantity()
void SpawnItemOnLocation::SetCEBasedQuantity () protected
Definition at line 5469 of file ItemBase.c.
Referenced by InventoryItem::EEOnCECreate().
SetCleanness()
void SpawnItemOnLocation::SetCleanness (int value, bool allow_client = false) protected
Definition at line 8357 of file ItemBase.c.
Referenced by InventoryItem::DeSerializeNumericalVars(), InventoryItem::EEHealthLevelChanged(), ItemBase::OnCombine(), SewingKit::OnCombine(), and InventoryItem::ReadVarsFromCTX().
SetColor()
void SpawnItemOnLocation::SetColor (int r, int g, int b, int a) protected
Definition at line 8392 of file ItemBase.c.
SetDebugActionsMask()
static void SpawnItemOnLocation::SetDebugActionsMask (int mask) static protected
Definition at line 5441 of file ItemBase.c.
SetIsBeingPlaced()
void SpawnItemOnLocation::SetIsBeingPlaced (bool is_being_placed) protected
Definition at line 5630 of file ItemBase.c.
SetIsDeploySound()
void SpawnItemOnLocation::SetIsDeploySound (bool is_deploy_sound) protected
Definition at line 8972 of file ItemBase.c.
Referenced by InventoryItem::OnPlacementComplete(), ItemBase::OnPlacementComplete(), KitBase::OnPlacementComplete(), Inventory_Base::OnPlacementComplete(), and ItemBase::SpawnCatch().
SetIsHologram()
void SpawnItemOnLocation::SetIsHologram (bool is_hologram) protected
Definition at line 5656 of file ItemBase.c.
SetIsPlaceSound()
void SpawnItemOnLocation::SetIsPlaceSound (bool is_place_sound) protected
Definition at line 8962 of file ItemBase.c.
Referenced by Barrel_ColorBase::OnPlacementComplete(), ItemBase::OnPlacementComplete(), OnPlacementComplete(), and TrapSpawnBase::OnPlacementComplete().
SetLiquidType()
void SpawnItemOnLocation::SetLiquidType (int value, bool allow_client = false) protected
Definition at line 8428 of file ItemBase.c.
Referenced by InventoryItem::DeSerializeNumericalVars(), InventoryItem::OnAction(), and InventoryItem::ReadVarsFromCTX().
SetQuantity()
bool SpawnItemOnLocation::SetQuantity (float value, bool destroy_config = true, bool destroy_forced = false, bool allow_client = false, bool clamp_to_stack_max = true) protected
Set item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted.
Definition at line 7838 of file ItemBase.c.
Referenced by InventoryItem::AddQuantity(), InventoryItem::AfterStoreLoad(), CalcAndSetQuantity(), Capture(), InventoryItem::DeSerializeNumericalVars(), MaskBase::EEHealthLevelChanged(), GasMask_Filter::EEHealthLevelChanged(), InventoryItem::OnAction(), InventoryItem::ReadVarsFromCTX(), Release(), InventoryItem::SetQuantityMax(), InventoryItem::SetQuantityNormalized(), InventoryItem::SetQuantityToMinimum(), and InventoryItem::SplitIntoStackMax().
SetQuantityMax()
void SpawnItemOnLocation::SetQuantityMax () protected
Definition at line 7905 of file ItemBase.c.
Referenced by InventoryItem::OnAction(), Barrel_ColorBase::OnDebugSpawn(), and OnDebugSpawn().
SetQuantityNormalized()
void SpawnItemOnLocation::SetQuantityNormalized (float value, bool destroy_config = true, bool destroy_forced = false) protected
Sets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, setting 0.5 will result in value 2500)
Definition at line 7918 of file ItemBase.c.
Referenced by FlammableBase::CalculateQuantity(), InventoryItem::ConvertEnergyToQuantity(), and InventoryItem::SetCEBasedQuantity().
SetQuantityToMinimum()
override void SpawnItemOnLocation::SetQuantityToMinimum () protected
Definition at line 7911 of file ItemBase.c.
SetResultOfSplit()
void SpawnItemOnLocation::SetResultOfSplit (bool value) protected
Definition at line 6708 of file ItemBase.c.
Referenced by InventoryItem::EEHealthLevelChanged().
SetTakeable()
override void SpawnItemOnLocation::SetTakeable (bool pState) protected
Definition at line 8905 of file ItemBase.c.
Referenced by Barrel_ColorBase::Close(), FireplaceBase::Close(), Barrel_ColorBase::CloseLoad(), FireplaceBase::CloseLoad(), ImprovisedExplosive::EEHealthLevelChanged(), Plastic_Explosive::EEHealthLevelChanged(), EEItemAttached(), EEItemDetached(), LockServer(), Grenade_Base::OnActivateFinished(), Grenade_Base::OnActivateImmediate(), ImprovisedExplosive::OnDisarmed(), Plastic_Explosive::OnDisarmed(), ItemOptics::OnInventoryExit(), InventoryItem::OnPlacementStarted(), ItemOptics::OnWasAttached(), ItemOptics::OnWasDetached(), Barrel_ColorBase::Open(), FireplaceBase::Open(), Barrel_ColorBase::OpenLoad(), FireplaceBase::OpenLoad(), ItemBase::PlantBase(), ItemBase::SetMountedState(), and UnlockServer().
SetTemperature()
override void SpawnItemOnLocation::SetTemperature (float value, bool allow_client = false) protected
Definition at line 8178 of file ItemBase.c.
Referenced by InventoryItem::AddTemperature(), InventoryItem::DeSerializeNumericalVars(), ItemBase::OnWork(), Heatpack::OnWork(), Heatpack::OnWorkStart(), InventoryItem::ReadVarsFromCTX(), and InventoryItem::SetTemperatureMax().
SetTemperatureMax()
override void SpawnItemOnLocation::SetTemperatureMax () protected
Definition at line 8199 of file ItemBase.c.
SetupSpawnedItem()
void SetupSpawnedItem (ItemBase item, float health, float quantity)
Definition at line 4700 of file ItemBase.c.
Referenced by PluginBase::SetupSpawnedEntity(), PluginBase::SpawnEntityAsAttachment(), PluginBase::SpawnEntityInInventory(), and PluginBase::SpawnEntityInPlayerInventory().
SetVariableMask()
void SpawnItemOnLocation::SetVariableMask (int variable) protected
Definition at line 8096 of file ItemBase.c.
Referenced by InventoryItem::SetCleanness(), InventoryItem::SetColor(), InventoryItem::SetLiquidType(), InventoryItem::SetQuantity(), InventoryItem::SetTemperature(), and InventoryItem::SetWet().
SetWet()
override void SpawnItemOnLocation::SetWet (float value, bool allow_client = false) protected
Definition at line 8252 of file ItemBase.c.
Referenced by InventoryItem::AddWet(), AddWetnessToFireplace(), InventoryItem::DeSerializeNumericalVars(), InventoryItem::ReadVarsFromCTX(), and InventoryItem::SetWetMax().
SetWetMax()
override void SpawnItemOnLocation::SetWetMax () protected
Definition at line 8276 of file ItemBase.c.
SetZoneDamageCEInit()
void SpawnItemOnLocation::SetZoneDamageCEInit () protected
Sets zone damages to match randomized global health set by CE (CE spawn only)
Definition at line 9123 of file ItemBase.c.
Referenced by InventoryItem::EEOnCECreate().
SoundSynchRemote()
void SpawnItemOnLocation::SoundSynchRemote () protected
Definition at line 8945 of file ItemBase.c.
Referenced by Barrel_ColorBase::Close(), FireplaceBase::Close(), ItemBase::OnEndPlacement(), Barrel_ColorBase::Open(), FireplaceBase::Open(), and ItemBase::ToggleAnimation().
SoundSynchRemoteReset()
void SpawnItemOnLocation::SoundSynchRemoteReset () protected
Definition at line 8938 of file ItemBase.c.
SpawnItemOnLocation()
class ItemBase extends InventoryItem SpawnItemOnLocation (string object_name, notnull InventoryLocation loc, bool full_quantity)
Definition at line 13 of file ItemBase.c.
Referenced by ManBase::CreateInInventory().
SplitIntoStackMax()
void SpawnItemOnLocation::SplitIntoStackMax (EntityAI destination_entity, int slot_id, PlayerBase player) protected
Definition at line 6211 of file ItemBase.c.
Referenced by InventoryItem::SplitIntoStackMaxClient().
SplitIntoStackMaxCargo()
void SpawnItemOnLocation::SplitIntoStackMaxCargo (EntityAI destination_entity, int idx, int row, int col) protected
Definition at line 6370 of file ItemBase.c.
Referenced by InventoryItem::SplitIntoStackMaxCargoClient().
SplitIntoStackMaxCargoClient()
void SpawnItemOnLocation::SplitIntoStackMaxCargoClient (EntityAI destination_entity, int idx, int row, int col) protected
Definition at line 6309 of file ItemBase.c.
SplitIntoStackMaxClient()
void SpawnItemOnLocation::SplitIntoStackMaxClient (EntityAI destination_entity, int slot_id) protected
Definition at line 6188 of file ItemBase.c.
SplitIntoStackMaxHands()
void SpawnItemOnLocation::SplitIntoStackMaxHands (PlayerBase player) protected
Definition at line 6418 of file ItemBase.c.
Referenced by InventoryItem::SplitIntoStackMaxHandsClient().
SplitIntoStackMaxHandsClient()
void SpawnItemOnLocation::SplitIntoStackMaxHandsClient (PlayerBase player) protected
Definition at line 6394 of file ItemBase.c.
SplitIntoStackMaxToInventoryLocation()
void SpawnItemOnLocation::SplitIntoStackMaxToInventoryLocation (notnull InventoryLocation dst) protected
Definition at line 6334 of file ItemBase.c.
Referenced by InventoryItem::SplitIntoStackMaxToInventoryLocationClient().
SplitIntoStackMaxToInventoryLocationClient()
void SpawnItemOnLocation::SplitIntoStackMaxToInventoryLocationClient (notnull InventoryLocation dst) protected
Definition at line 6288 of file ItemBase.c.
SplitIntoStackMaxToInventoryLocationEx()
ItemBase SpawnItemOnLocation::SplitIntoStackMaxToInventoryLocationEx (notnull InventoryLocation dst) protected
Definition at line 6339 of file ItemBase.c.
Referenced by InventoryItem::SplitIntoStackMaxToInventoryLocation().
SplitItem()
void SpawnItemOnLocation::SplitItem (PlayerBase player) protected
Definition at line 6476 of file ItemBase.c.
Referenced by InventoryItem::OnRightClick().
SplitItemToInventoryLocation()
void SpawnItemOnLocation::SplitItemToInventoryLocation (notnull InventoryLocation dst) protected
Definition at line 6443 of file ItemBase.c.
StartOverheating()
void SpawnItemOnLocation::StartOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "") protected
Definition at line 5238 of file ItemBase.c.
Referenced by InventoryItem::CheckOverheating().
StopDeployLoopSoundEx()
void SpawnItemOnLocation::StopDeployLoopSoundEx () protected
Definition at line 8994 of file ItemBase.c.
Referenced by InventoryItem::OnVariablesSynchronized().
StopItemDynamicPhysics()
void SpawnItemOnLocation::StopItemDynamicPhysics () protected
Definition at line 9105 of file ItemBase.c.
StopOverheating()
void SpawnItemOnLocation::StopOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "") protected
Definition at line 5251 of file ItemBase.c.
Referenced by InventoryItem::CheckOverheating().
StopOverheatingParticles()
static void SpawnItemOnLocation::StopOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) static protected
Definition at line 8840 of file ItemBase.c.
ToggleDebugActionsMask()
static void SpawnItemOnLocation::ToggleDebugActionsMask (int mask) static protected
Definition at line 5456 of file ItemBase.c.
TransferAgents()
void SpawnItemOnLocation::TransferAgents (int agents) protected
transfer agents from another item
Definition at line 8548 of file ItemBase.c.
TransferModifiers()
void SpawnItemOnLocation::TransferModifiers (PlayerBase reciever) private
appears to be deprecated, legacy code
TransferVariablesFloat()
void SpawnItemOnLocation::TransferVariablesFloat (array< float > float_vars) protected
Definition at line 7246 of file ItemBase.c.
UnlockFromParent()
void SpawnItemOnLocation::UnlockFromParent () protected
Unlocks this item from its attachment slot of its parent.
Definition at line 5516 of file ItemBase.c.
Referenced by ItemBase::DestroyPlant(), InventoryItemSuper::EEHealthLevelChanged(), CarWheel_Ruined::EEHealthLevelChanged(), ItemBase::RemovePlant(), and ItemBase::RemovePlantEx().
UpdateAllOverheatingParticles()
void SpawnItemOnLocation::UpdateAllOverheatingParticles () protected
Definition at line 5279 of file ItemBase.c.
Referenced by InventoryItem::UpdateOverheating().
UpdateOverheating()
void SpawnItemOnLocation::UpdateOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "") protected
Definition at line 5244 of file ItemBase.c.
Referenced by InventoryItem::CheckOverheating().
UpdateOverheatingParticles()
static void SpawnItemOnLocation::UpdateOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) static protected
Definition at line 8820 of file ItemBase.c.
UsesGlobalDeploy()
bool SpawnItemOnLocation::UsesGlobalDeploy () protected
Definition at line 4948 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
WriteVarsToCTX()
void SpawnItemOnLocation::WriteVarsToCTX (ParamsWriteContext ctx) protected
Definition at line 7401 of file ItemBase.c.
Referenced by InventoryItem::SaveVariables().
~ItemBase()
void SpawnItemOnLocation::~ItemBase () protected
Definition at line 5392 of file ItemBase.c.
Variable Documentation
can_this_be_combined
bool can_this_be_combined = false
Definition at line 4741 of file ItemBase.c.
Referenced by InventoryItem::CanBeCombined(), InventoryItem::InitItemVariables(), Edible_Base::InitItemVariables(), VitaminBottle::InitItemVariables(), DisinfectantAlcohol::InitItemVariables(), IodineTincture::InitItemVariables(), Inventory_Base::InitItemVariables(), and ItemBase::InitItemVariables().
m_ActionsInitialize
bool m_ActionsInitialize
Definition at line 4683 of file ItemBase.c.
m_AdminLog
PluginAdminLog m_AdminLog protected
Definition at line 4794 of file ItemBase.c.
m_AttachedAgents
int m_AttachedAgents private
Definition at line 4768 of file ItemBase.c.
Referenced by InventoryItem::ContainsAgent(), InventoryItem::GetAgents(), InventoryItem::InsertAgent(), InventoryItem::LoadAgents(), InventoryItem::RemoveAgent(), InventoryItem::RemoveAllAgents(), InventoryItem::RemoveAllAgentsExcept(), InventoryItem::SaveAgents(), and InventoryItem::TransferAgents().
m_CanBeDigged
bool m_CanBeDigged protected
Definition at line 4746 of file ItemBase.c.
Referenced by InventoryItem::CanBeDigged(), and InventoryItem::InitItemVariables().
m_CanBeMovedOverride
bool m_CanBeMovedOverride
Definition at line 4739 of file ItemBase.c.
Referenced by InventoryItem::CanBeMovedOverride(), InventoryItem::InitItemVariables(), and InventoryItem::SetCanBeMovedOverride().
m_CanPlayImpactSound
bool m_CanPlayImpactSound = true
Definition at line 4721 of file ItemBase.c.
Referenced by InventoryItem::EOnContact(), and InventoryItem::OnInventoryEnter().
m_CanShowQuantity
bool m_CanShowQuantity
Definition at line 4744 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
m_CanThisBeSplit
bool m_CanThisBeSplit = false
Definition at line 4742 of file ItemBase.c.
Referenced by InventoryItem::CanBeSplit(), InventoryItem::GetUnitWeight(), InventoryItem::GetWeightSpecialized(), InventoryItem::InitItemVariables(), and InventoryItem::OnVariablesSynchronized().
m_CheckOverheating
ref Timer m_CheckOverheating private
Definition at line 4784 of file ItemBase.c.
Referenced by InventoryItem::IncreaseOverheating(), and InventoryItem::OnOverheatingDecay().
m_Cleanness
int m_Cleanness
Definition at line 4715 of file ItemBase.c.
Referenced by InventoryItem::EEHealthLevelChanged(), ItemBase::GetInfectionChance(), Bandana_ColorBase::GetInfectionChance(), SewingKit::GetInfectionChance(), InventoryItem::InitItemVariables(), ItemBase::OnCombine(), SewingKit::OnCombine(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetCleanness(), and InventoryItem::WriteVarsToCTX().
m_CleannessInit
int m_CleannessInit
Definition at line 4716 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
m_CleannessMax
int m_CleannessMax
Definition at line 4718 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), and InventoryItem::SetCleanness().
m_CleannessMin
int m_CleannessMin
Definition at line 4717 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), and InventoryItem::SetCleanness().
m_ColorComponentA
int m_ColorComponentA protected
Definition at line 4756 of file ItemBase.c.
Referenced by InventoryItem::DeSerializeNumericalVars(), InventoryItem::GetColor(), InventoryItem::ReadVarsFromCTX(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetColor(), and InventoryItem::WriteVarsToCTX().
m_ColorComponentB
int m_ColorComponentB protected
Definition at line 4755 of file ItemBase.c.
Referenced by InventoryItem::DeSerializeNumericalVars(), InventoryItem::GetColor(), InventoryItem::ReadVarsFromCTX(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetColor(), and InventoryItem::WriteVarsToCTX().
m_ColorComponentG
int m_ColorComponentG protected
Definition at line 4754 of file ItemBase.c.
Referenced by InventoryItem::DeSerializeNumericalVars(), InventoryItem::GetColor(), InventoryItem::ReadVarsFromCTX(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetColor(), and InventoryItem::WriteVarsToCTX().
m_ColorComponentR
int m_ColorComponentR protected
Definition at line 4753 of file ItemBase.c.
Referenced by InventoryItem::DeSerializeNumericalVars(), InventoryItem::GetColor(), InventoryItem::ReadVarsFromCTX(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetColor(), and InventoryItem::WriteVarsToCTX().
m_CompatibleLocks
ref array<int> m_CompatibleLocks = new array<int> protected
Definition at line 4800 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
m_ContinuousActions
ref TIntArray m_ContinuousActions protected
Definition at line 4763 of file ItemBase.c.
Referenced by InventoryItem::ItemBase().
m_Count
int m_Count
Definition at line 4700 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
m_DebugActionsMask
int m_DebugActionsMask static
Definition at line 4685 of file ItemBase.c.
m_DeployLoopSoundEx
EffectSound m_DeployLoopSoundEx protected
distinguish if item has been created as new or it came from splitting (server only flag)
Definition at line 4749 of file ItemBase.c.
Referenced by InventoryItem::OnVariablesSynchronized(), InventoryItem::PlayDeployLoopSoundEx(), InventoryItem::StopDeployLoopSoundEx(), and InventoryItem::~ItemBase().
m_FixDamageSystemInit
bool m_FixDamageSystemInit = false
Definition at line 4740 of file ItemBase.c.
Referenced by InventoryItem::AfterStoreLoad(), ItemBase::AfterStoreLoad(), ItemBase::EEHealthLevelChanged(), InventoryItem::EEOnAfterLoad(), ItemBase::EEOnAfterLoad(), and InventoryItem::OnStoreLoad().
m_HasQuantityBar
bool m_HasQuantityBar
Definition at line 4745 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
m_HeadHidingSelections
ref TStringArray m_HeadHidingSelections protected
Definition at line 4790 of file ItemBase.c.
Referenced by InventoryItem::GetHeadHidingSelection(), and InventoryItem::ItemBase().
m_HeatIsolation
float m_HeatIsolation
Definition at line 4725 of file ItemBase.c.
Referenced by InventoryItem::GetHeatIsolation(), and InventoryItem::InitItemVariables().
m_HideSelectionsBySlot
bool m_HideSelectionsBySlot protected
Definition at line 4791 of file ItemBase.c.
Referenced by InventoryItem::HidesSelectionBySlot(), and InventoryItem::ItemBase().
m_ImpactSoundSurfaceHash
int m_ImpactSoundSurfaceHash
Definition at line 4723 of file ItemBase.c.
Referenced by InventoryItem::EOnContact(), and InventoryItem::OnVariablesSynchronized().
m_ImpactSpeed
float m_ImpactSpeed
Definition at line 4722 of file ItemBase.c.
Referenced by InventoryItem::EOnContact(), InventoryItem::InitItemVariables(), and InventoryItem::OnVariablesSynchronized().
m_InputActionMap
TInputActionMap m_InputActionMap
Definition at line 4682 of file ItemBase.c.
m_InteractActions
ref TIntArray m_InteractActions protected
Definition at line 4764 of file ItemBase.c.
Referenced by EntityAI::Building(), and InventoryItem::ItemBase().
m_IsBeingPlaced
bool m_IsBeingPlaced
Definition at line 4731 of file ItemBase.c.
Referenced by TrapSpawnBase::CanBePlaced(), InventoryItem::InitItemVariables(), InventoryItem::IsBeingPlaced(), and InventoryItem::SetIsBeingPlaced().
m_IsDeploySound
bool m_IsDeploySound
Definition at line 4734 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), InventoryItem::IsDeploySound(), and InventoryItem::SetIsDeploySound().
m_IsHologram
bool m_IsHologram
Definition at line 4732 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), InventoryItem::IsHologram(), and InventoryItem::SetIsHologram().
m_IsOverheatingEffectActive
bool m_IsOverheatingEffectActive private
Definition at line 4782 of file ItemBase.c.
Referenced by InventoryItem::IsOverheatingEffectActive(), InventoryItem::StartOverheating(), and InventoryItem::StopOverheating().
m_IsPlaceSound
bool m_IsPlaceSound
Definition at line 4733 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), InventoryItem::IsPlaceSound(), and InventoryItem::SetIsPlaceSound().
m_IsSoundSynchRemote
bool m_IsSoundSynchRemote
Definition at line 4736 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), InventoryItem::IsSoundSynchRemote(), InventoryItem::SoundSynchRemote(), and InventoryItem::SoundSynchRemoteReset().
m_IsStoreLoad
bool m_IsStoreLoad = false
Definition at line 4743 of file ItemBase.c.
Referenced by InventoryItem::DeSerializeNumericalVars(), ItemOptics::OnStoreLoad(), InventoryItem::OnStoreLoad(), and InventoryItem::ReadVarsFromCTX().
m_IsTakeable
bool m_IsTakeable
Definition at line 4735 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), InventoryItem::IsTakeable(), and InventoryItem::SetTakeable().
m_ItemAttachOffset
float m_ItemAttachOffset
Definition at line 4727 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
m_ItemBehaviour
int m_ItemBehaviour = -1
Definition at line 4729 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), InventoryItem::IsHeavyBehaviour(), InventoryItem::IsOneHandedBehaviour(), and InventoryItem::IsTwoHandedBehaviour().
m_ItemBeingDroppedPhys
bool m_ItemBeingDroppedPhys
Definition at line 4738 of file ItemBase.c.
Referenced by InventoryItem::StopItemDynamicPhysics().
m_ItemModelLength
float m_ItemModelLength
Definition at line 4726 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
m_ItemTypeActionsMap
ref map<typename, ref TInputActionMap> m_ItemTypeActionsMap = new map<typename, ref TInputActionMap> static
Definition at line 4681 of file ItemBase.c.
Referenced by InventoryItem::InitializeActions().
m_LastRegisteredWeaponID
int m_LastRegisteredWeaponID = 0 static private
Definition at line 4779 of file ItemBase.c.
Referenced by InventoryItem::GetMuzzleID().
m_LightSourceItem
ItemBase m_LightSourceItem protected
Definition at line 4760 of file ItemBase.c.
Referenced by InventoryItem::AddLightSourceItem(), InventoryItem::GetLightSourceItem(), and InventoryItem::RemoveLightSourceItem().
m_LockingSound
ref EffectSound m_LockingSound protected
Definition at line 4802 of file ItemBase.c.
m_LockSoundSet
string m_LockSoundSet = "" protected
Definition at line 4803 of file ItemBase.c.
Referenced by InventoryItem::GetLockSoundSet(), and InventoryItem::InitItemVariables().
m_LockType
int m_LockType protected
Definition at line 4801 of file ItemBase.c.
Referenced by InventoryItem::GetLockType(), and InventoryItem::InitItemVariables().
m_MaxOverheatingValue
int m_MaxOverheatingValue = 0 private
Definition at line 4786 of file ItemBase.c.
Referenced by InventoryItem::CheckOverheating(), InventoryItem::GetOverheatingCoef(), InventoryItem::IncreaseOverheating(), InventoryItem::LoadParticleConfigOnOverheating(), and InventoryItem::OnOverheatingDecay().
m_OnBulletCasingEjectEffect
ref map<int, ref array<ref WeaponParticlesOnBulletCasingEject> > m_OnBulletCasingEjectEffect static private
Definition at line 4776 of file ItemBase.c.
Referenced by InventoryItem::LoadParticleConfigOnFire(), and InventoryItem::PlayBulletCasingEjectParticles().
m_OnFireEffect
ref map<int, ref array<ref WeaponParticlesOnFire> > m_OnFireEffect static private
Definition at line 4775 of file ItemBase.c.
Referenced by InventoryItem::LoadParticleConfigOnFire(), and InventoryItem::PlayFireParticles().
m_OnOverheatingEffect
ref map<int, ref array<ref WeaponParticlesOnOverheating> > m_OnOverheatingEffect private
Definition at line 4777 of file ItemBase.c.
Referenced by InventoryItem::LoadParticleConfigOnOverheating().
m_OverheatingDecayInterval
float m_OverheatingDecayInterval = 1 private
Definition at line 4787 of file ItemBase.c.
Referenced by InventoryItem::IncreaseOverheating(), InventoryItem::LoadParticleConfigOnOverheating(), and InventoryItem::OnOverheatingDecay().
m_OverheatingParticles
ref array<ref OverheatingParticle> m_OverheatingParticles private
Definition at line 4788 of file ItemBase.c.
Referenced by InventoryItem::KillAllOverheatingParticles(), InventoryItem::RegisterOverheatingParticle(), and InventoryItem::UpdateAllOverheatingParticles().
m_OverheatingShots
float m_OverheatingShots private
Definition at line 4783 of file ItemBase.c.
Referenced by InventoryItem::CheckOverheating(), InventoryItem::GetOverheatingCoef(), InventoryItem::GetOverheatingValue(), InventoryItem::IncreaseOverheating(), and InventoryItem::OnOverheatingDecay().
m_PhysDropTimer
ref Timer m_PhysDropTimer protected
Definition at line 4797 of file ItemBase.c.
m_QuickBarBonus
int m_QuickBarBonus = 0
Definition at line 4730 of file ItemBase.c.
Referenced by InventoryItem::GetQuickBarBonus(), ManBase::GetQuickBarBonus(), ManBase::Init(), and InventoryItem::ItemBase().
m_RecipesInitialized
bool m_RecipesInitialized
Definition at line 4686 of file ItemBase.c.
m_ShotsToStartOverheating
int m_ShotsToStartOverheating = 0 private
Definition at line 4785 of file ItemBase.c.
Referenced by InventoryItem::CheckOverheating(), InventoryItem::GetOverheatingCoef(), InventoryItem::ItemBase(), and InventoryItem::LoadParticleConfigOnOverheating().
m_SingleUseActions
ref TIntArray m_SingleUseActions protected
Definition at line 4762 of file ItemBase.c.
Referenced by InventoryItem::ItemBase().
m_SoundAttType
string m_SoundAttType protected
Definition at line 4751 of file ItemBase.c.
Referenced by InventoryItem::GetAttachmentSoundType(), and InventoryItem::PreLoadSoundAttachmentType().
m_SoundDeploy
EffectSound m_SoundDeploy protected
Definition at line 4806 of file ItemBase.c.
Referenced by InventoryItem::PlayDeploySound().
m_SoundDeployFinish
EffectSound m_SoundDeployFinish protected
Definition at line 4807 of file ItemBase.c.
Referenced by InventoryItem::PlayDeployFinishSound().
m_SoundPlace
EffectSound m_SoundPlace protected
Definition at line 4805 of file ItemBase.c.
Referenced by InventoryItem::PlayPlaceSound().
m_StoreLoadedQuantity
float m_StoreLoadedQuantity = float.LOWEST
Definition at line 4702 of file ItemBase.c.
Referenced by InventoryItem::AfterStoreLoad(), InventoryItem::DeSerializeNumericalVars(), InventoryItem::ReadVarsFromCTX(), and InventoryItem::SetQuantity().
m_ThrowItemOnDrop
bool m_ThrowItemOnDrop
Definition at line 4737 of file ItemBase.c.
Referenced by InventoryItem::EEItemLocationChanged().
m_VariablesMask
int m_VariablesMask
Definition at line 4692 of file ItemBase.c.
Referenced by InventoryItem::IsVariableSet(), InventoryItem::RemoveItemVariable(), InventoryItem::SaveVariables(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetVariableMask(), and InventoryItem::WriteVarsToCTX().
m_VarLiquidType
int m_VarLiquidType
Definition at line 4728 of file ItemBase.c.
Referenced by InventoryItem::GetLiquidType(), InventoryItem::InitItemVariables(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetLiquidType(), and InventoryItem::WriteVarsToCTX().
m_VarQuantity
float m_VarQuantity
Definition at line 4695 of file ItemBase.c.
Referenced by InventoryItem::GetQuantity(), InventoryItem::GetQuantityNormalized(), InventoryItem::InitItemVariables(), InventoryItem::OnVariablesSynchronized(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetQuantity(), and InventoryItem::WriteVarsToCTX().
m_VarQuantityInit
int m_VarQuantityInit
Definition at line 4697 of file ItemBase.c.
Referenced by InventoryItem::GetQuantityInit(), and InventoryItem::InitItemVariables().
m_VarQuantityMax
int m_VarQuantityMax
Definition at line 4699 of file ItemBase.c.
Referenced by InventoryItem::GetQuantityMax(), InventoryItem::GetTargetQuantityMax(), InventoryItem::InitItemVariables(), InventoryItem::OnWasAttached(), and InventoryItem::OnWasDetached().
m_VarQuantityMin
int m_VarQuantityMin
Definition at line 4698 of file ItemBase.c.
Referenced by InventoryItem::GetQuantityMin(), and InventoryItem::InitItemVariables().
m_VarQuantityPrev
float m_VarQuantityPrev
Definition at line 4696 of file ItemBase.c.
Referenced by InventoryItem::OnVariablesSynchronized().
m_VarStackMax
float m_VarStackMax
Definition at line 4701 of file ItemBase.c.
Referenced by InventoryItem::GetQuantityMax(), InventoryItem::GetTargetQuantityMax(), and InventoryItem::InitItemVariables().
m_VarTemperature
float m_VarTemperature
Definition at line 4704 of file ItemBase.c.
Referenced by InventoryItem::GetTemperature(), InventoryItem::InitItemVariables(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetTemperature(), and InventoryItem::WriteVarsToCTX().
m_VarTemperatureInit
float m_VarTemperatureInit
Definition at line 4705 of file ItemBase.c.
Referenced by InventoryItem::GetTemperatureInit(), and InventoryItem::InitItemVariables().
m_VarTemperatureMax
float m_VarTemperatureMax
Definition at line 4707 of file ItemBase.c.
Referenced by InventoryItem::GetTemperatureMax(), InventoryItem::InitItemVariables(), and InventoryItem::SetTemperatureMax().
m_VarTemperatureMin
float m_VarTemperatureMin
Definition at line 4706 of file ItemBase.c.
Referenced by InventoryItem::GetTemperatureMin(), and InventoryItem::InitItemVariables().
m_VarWet
float m_VarWet
Definition at line 4709 of file ItemBase.c.
Referenced by InventoryItem::GetWet(), InventoryItem::GetWetLevel(), InventoryItem::InitItemVariables(), InventoryItem::OnVariablesSynchronized(), InventoryItem::ProcessItemWetness(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetWet(), and InventoryItem::WriteVarsToCTX().
m_VarWetInit
float m_VarWetInit
Definition at line 4711 of file ItemBase.c.
Referenced by InventoryItem::GetWetInit(), and InventoryItem::InitItemVariables().
m_VarWetMax
float m_VarWetMax
Definition at line 4713 of file ItemBase.c.
Referenced by InventoryItem::GetWetMax(), InventoryItem::InitItemVariables(), InventoryItem::ProcessItemWetness(), and InventoryItem::SetWetMax().
m_VarWetMin
float m_VarWetMin
Definition at line 4712 of file ItemBase.c.
Referenced by InventoryItem::GetWetMin(), InventoryItem::InitItemVariables(), and InventoryItem::ProcessItemWetness().
m_VarWetPrev
float m_VarWetPrev
Definition at line 4710 of file ItemBase.c.
Referenced by InventoryItem::OnVariablesSynchronized().
m_WantPlayImpactSound
bool m_WantPlayImpactSound
Definition at line 4720 of file ItemBase.c.
Referenced by InventoryItem::EOnContact(), InventoryItem::InitItemVariables(), and InventoryItem::OnVariablesSynchronized().
m_WeaponTypeToID
ref map<string, int> m_WeaponTypeToID static private
Definition at line 4778 of file ItemBase.c.
Referenced by InventoryItem::GetMuzzleID().