DayZ: scripts/5_Mission/GUI/NewUI/Credits/Elements/CreditsDepartmentElement.c File Reference
CreditsDepartmentElement.c File Reference
Classes
class CreditsElement
Functions
void CreditsDepartmentSection (int index, Widget parent, JsonDataCreditsSection section_data)
void LoadDataAsync (array< string > section_data)
Variables
class CreditsDepartmentElement extends CreditsElement m_SectionTitle
WrapSpacerWidget m_SectionSections
ref array< Widget > m_SectionEntries = new array<Widget>
Function Documentation
CreditsDepartmentSection()
void CreditsDepartmentSection (int index, Widget parent, JsonDataCreditsSection section_data) protected
Definition at line 43 of file CreditsDepartmentElement.c.
  {
    m_Root = GetGame().GetWorkspace().CreateWidgets("gui/layouts/new_ui/credits/department_element/department_section.layout", parent);
    m_SectionTitle = TextWidget.Cast(m_Root.FindAnyWidget("section_title"));
    m_SectionSections = WrapSpacerWidget.Cast(m_Root.FindAnyWidget("section_elements"));
    if (section_data.SectionName != "")
      m_SectionTitle.SetText(section_data.SectionName);
    else
    {
      m_SectionTitle.Show(false);
      m_Root.FindAnyWidget("SeparatorPanel").Show(false);
    }
    LoadDataAsync(section_data.SectionLines);
    m_Root.SetSort(index);
  }
References GetGame(), CreditsElement::LoadDataAsync(), m_Root, m_SectionSections, and m_SectionTitle.
Referenced by CreditsElement::LoadDataAsync().
LoadDataAsync()
void LoadDataAsync (array< string > section_data) protected
Definition at line 61 of file CreditsDepartmentElement.c.
  {
    for (int i = 1; i <= section_data.Count(); i++)
    {
      TextWidget w = TextWidget.Cast(GetGame().GetWorkspace().CreateWidgets("gui/layouts/new_ui/credits/department_element/department_section_element.layout", m_SectionSections));
      w.SetText(section_data.Get(i - 1) + " \n");
      w.Update();
      m_Root.SetSort(i);
      m_SectionEntries.Insert(w);
    }
    m_SectionSections.Update();
  }
References GetGame(), m_Root, m_SectionEntries, and m_SectionSections.
Variable Documentation
m_SectionEntries
ref array<Widget> m_SectionEntries = new array<Widget> protected
Definition at line 41 of file CreditsDepartmentElement.c.
Referenced by LoadDataAsync().
m_SectionSections
WrapSpacerWidget m_SectionSections protected
Definition at line 40 of file CreditsDepartmentElement.c.
Referenced by CreditsDepartmentSection(), and LoadDataAsync().
m_SectionTitle
class CreditsDepartmentElement extends CreditsElement m_SectionTitle
Referenced by CreditsDepartmentSection().