DayZ: scripts/3_Game/Systems/TestFramework.c File Reference
TestFramework.c File Reference
Classes
class array
Result for an object found in CGame.IsBoxCollidingGeometryProxy.
class TFModule
Typedefs
typedef array< ref TFResult > TFResultArr
Enumerations
enum TFR { FAIL = -1 , SUCCESS , PENDING }
Functions
void TFResult (TFR result)
TFResult And (TFResult other)
TFResult Or (TFResult other)
void TestFramework ()
void ~TestFramework ()
override void EOnInit (IEntity other, int extra)
override void EOnFrame (IEntity other, float timeSlice)
void AddInitTest (string test)
void AddFrameTest (string test)
bool Assert (bool condition)
TFResult NTFR (TFR result)
TFResult BTFR (bool result)
TFResult CTFR ()
Variables
enum TFR Result
class TFModule m_OnInitModule
Test Framework.
ref TFModule m_OnFrameModule
Typedef Documentation
TFResultArr
typedef array<ref TFResult> TFResultArr
Definition at line 43 of file TestFramework.c.
Enumeration Type Documentation
TFR
enum TFR
Enumerator
FAIL
SUCCESS
PENDING
Definition at line 1 of file TestFramework.c.
{
  FAIL = -1,
  SUCCESS,
  PENDING,
}
Function Documentation
AddFrameTest()
void AddFrameTest (string test) protected
Definition at line 250 of file TestFramework.c.
  {
    m_OnFrameModule.AddTest(this, test, true);
  }
References m_OnFrameModule.
Referenced by TestEvents(), PMTPlayback::TestOnePlaying(), PMTPlayback::TestOnePlayingStandAlone(), PMTPlayback::TestOnePlayingStandAloneAutoDestroy(), and PMTPlayback::TestStopping().
AddInitTest()
void AddInitTest (string test) protected
Definition at line 245 of file TestFramework.c.
  {
    m_OnInitModule.AddTest(this, test, false);
  }
References m_OnInitModule.
Referenced by EnProfilerTests::EnProfilerTests(), PMTCreationAndCleanup(), PMTPlayback::PMTPlayback(), and ScriptInvokerTests::ScriptInvokerTests().
And()
TFResult And (TFResult other)
Definition at line 17 of file TestFramework.c.
  {
    if (Result == TFR.PENDING || other.Result == TFR.PENDING)
      ErrorEx("Trying to And while one of the results are PENDING.");
    if (Result == TFR.SUCCESS && other.Result == TFR.SUCCESS)
      Result = TFR.SUCCESS;
    else
      Result = TFR.FAIL;
    return this;
  }
References ErrorEx, and Result.
Assert()
bool Assert (bool condition) protected
Definition at line 258 of file TestFramework.c.
  {
    if (!condition)
      ErrorEx("ASSERTION FAILED.");
    return condition;
  }
References ErrorEx.
Referenced by PMTPlayback::CheckOnePlaying(), PMTPlayback::CheckOnePlayingSA(), PMTPlayback::CheckOnePlayingSAAD(), PMTPlayback::CheckStop(), CheckTestEvents(), PMTF::InsertManager(), PassCheckEvents(), EnProfilerTests::TestAddFlags(), EnProfilerTests::TestClassCountData(), EnProfilerTests::TestClassTimeData(), TestCleanup(), EnProfilerTests::TestClearFlags(), ScriptInvokerTests::TestClearRunning(), TestCreationSmallBlocking(), TestEvents(), ScriptInvokerTests::TestFirstUnique(), EnProfilerTests::TestFuncCountData(), EnProfilerTests::TestFuncTimeData(), ScriptInvokerTests::TestInsertRemoveUnique(), ScriptInvokerTests::TestInsertRunning(), ScriptInvokerTests::TestInsertUniqueImmediate(), EnProfilerTests::TestModule(), TestOwnership(), ScriptInvokerTests::TestSecondUnique(), EnProfilerTests::TestSetFlags(), EnProfilerTests::TestToggling(), and EnProfilerTests::TestTogglingImmediate().
BTFR()
TFResult BTFR (bool result) protected
Definition at line 274 of file TestFramework.c.
  {
    if (result)
      return new TFResult(TFR.SUCCESS);
    else
      return new TFResult(TFR.FAIL);
  }
References TFResult().
Referenced by PMTPlayback::CheckOnePlaying(), PMTPlayback::CheckOnePlayingSA(), PMTPlayback::CheckOnePlayingSAAD(), PMTPlayback::CheckStop(), CheckTestEvents(), TestCleanup(), ScriptInvokerTests::TestClearRunning(), TestCreationSmallBlocking(), ScriptInvokerTests::TestFirstUnique(), ScriptInvokerTests::TestInsertRemoveUnique(), ScriptInvokerTests::TestInsertRunning(), ScriptInvokerTests::TestInsertUniqueImmediate(), ScriptInvokerTests::TestInvokeRunning(), EnProfilerTests::TestModule(), PMTPlayback::TestOnePlaying(), PMTPlayback::TestOnePlayingStandAlone(), PMTPlayback::TestOnePlayingStandAloneAutoDestroy(), TestOwnership(), ScriptInvokerTests::TestSecondUnique(), PMTPlayback::TestStopping(), EnProfilerTests::TestToggling(), EnProfilerTests::TestTogglingImmediate(), and PMTPlayback::TestWiggleStress().
CTFR()
TFResult CTFR () protected
Definition at line 282 of file TestFramework.c.
  {
    return new TFResult(TFR.SUCCESS);
  }
References TFResult().
Referenced by TestCleanup(), and TestMultiCreation().
EOnFrame()
override void EOnFrame (IEntity other, float timeSlice) protected
Definition at line 236 of file TestFramework.c.
  {
    if (m_OnFrameModule.Run(false, timeSlice))
      GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(Delete);
  }
References CALL_CATEGORY_SYSTEM, GetGame(), and m_OnFrameModule.
EOnInit()
override void EOnInit (IEntity other, int extra) protected
Definition at line 231 of file TestFramework.c.
  {
    m_OnInitModule.Run(true, 0);
  }
References m_OnInitModule.
NTFR()
TFResult NTFR (TFR result) protected
Definition at line 269 of file TestFramework.c.
  {
    return new TFResult(result);
  }
References TFResult().
Referenced by PMTPlayback::CheckOnePlaying(), PMTPlayback::CheckOnePlayingSA(), PMTPlayback::CheckOnePlayingSAAD(), PMTPlayback::CheckStop(), CheckTestEvents(), EnProfilerTests::TestAddFlags(), EnProfilerTests::TestClassCountData(), EnProfilerTests::TestClassTimeData(), EnProfilerTests::TestClearFlags(), TestEvents(), EnProfilerTests::TestFuncCountData(), EnProfilerTests::TestFuncTimeData(), TestInvalidSize(), EnProfilerTests::TestModule(), TestOwnership(), EnProfilerTests::TestSetFlags(), EnProfilerTests::TestToggling(), and EnProfilerTests::TestTogglingImmediate().
Or()
TFResult Or (TFResult other)
Definition at line 30 of file TestFramework.c.
  {
    if (Result == TFR.PENDING || other.Result == TFR.PENDING)
      ErrorEx("Trying to Or while one of the results are PENDING.");
    if (Result == TFR.SUCCESS || other.Result == TFR.SUCCESS)
      Result = TFR.SUCCESS;
    else
      Result = TFR.FAIL;
    return this;
  }
References ErrorEx, and Result.
TestFramework()
void TestFramework () private
Definition at line 213 of file TestFramework.c.
  {
    SetEventMask(EntityEvent.INIT);
    SetEventMask(EntityEvent.FRAME);
    m_OnInitModule = new TFModule();
    m_OnFrameModule = new TFModule();
  }
References m_OnFrameModule, and m_OnInitModule.
TFResult()
void TFResult (TFR result)
Definition at line 12 of file TestFramework.c.
  {
    Result = result;
  }
References Result.
Referenced by TFModule::AddTest(), BTFR(), CTFR(), NTFR(), TestCleanup(), and TestMultiCreation().
~TestFramework()
void ~TestFramework () private
Definition at line 222 of file TestFramework.c.
  {
    m_OnInitModule.PrintResult("IM: ", this, "~TestFrameWork");
    m_OnFrameModule.PrintResult("FM: ", this, "~TestFrameWork");
  }
References m_OnFrameModule, and m_OnInitModule.
Variable Documentation
m_OnFrameModule
ref TFModule m_OnFrameModule private
Definition at line 211 of file TestFramework.c.
Referenced by AddFrameTest(), EOnFrame(), TestFramework(), and ~TestFramework().
m_OnInitModule
class TFModule m_OnInitModule
Test Framework.
Referenced by AddInitTest(), EOnInit(), TestFramework(), and ~TestFramework().
Result
enum TFR Result
Referenced by And(), Or(), and TFResult().