DayZ: PillsNotfr Class Reference
PillsNotfr Class Reference
Private Member Functions
void PillsNotfr (NotifiersManager manager)
override int GetNotifierType ()
override void DisplayBadge ()
override void HideBadge ()
Private Member Functions inherited from NotifierBase
int CalculateTendency (float delta, float inctresholdlow, float inctresholdmed, float inctresholdhigh, float dectresholdlow, float dectresholdmed, float dectresholdhigh)
eBadgeLevel DetermineBadgeLevel (float value, float lvl_1, float lvl_2, float lvl_3)
void DisplayBadge ()
void HideBadge ()
float GetObservedValue ()
Detailed Description
Definition at line 1 of file PillsNotfr.c.
Constructor & Destructor Documentation
PillsNotfr()
void PillsNotfr::PillsNotfr (NotifiersManager manager) inline private
Definition at line 3 of file PillsNotfr.c.
  {
    m_Active = false;
  }
References NotifierBase::m_Active.
Member Function Documentation
DisplayBadge()
override void PillsNotfr::DisplayBadge () inline private
Definition at line 13 of file PillsNotfr.c.
  {
    DisplayElementBadge dis_elm = DisplayElementBadge.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_BADGE_PILLS));
    if (dis_elm)
      dis_elm.SetLevel(eBadgeLevel.FIRST);
  }
References GetElement(), and NotifierBase::GetVirtualHud().
GetNotifierType()
override int PillsNotfr::GetNotifierType () inline private
Definition at line 8 of file PillsNotfr.c.
  {
    return eNotifiers.NTF_PILLS;
  }
HideBadge()
override void PillsNotfr::HideBadge () inline private
Definition at line 22 of file PillsNotfr.c.
  {
    DisplayElementBadge dis_elm = DisplayElementBadge.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_BADGE_PILLS));
    if (dis_elm)
      dis_elm.SetLevel(eBadgeLevel.NONE);
  }
References GetElement(), and NotifierBase::GetVirtualHud().
The documentation for this class was generated from the following file:
scripts/4_World/Classes/PlayerNotifiers/Notifiers/PillsNotfr.c