DayZ: BillboardSetHandler Class Reference
BillboardSetHandler Class Reference
Protected Member Functions
string GetTextureByType (string type)
void OnRPCIndex (int index)
bool LoadBillboardConfigs ()
Static Protected Member Functions
static bool ActivateBillboardSet (string setClassName, PlayerIdentity identity)
Protected Attributes
bool m_BillboardSetIndex = -1
ref array< ref BillboardSet > m_BillboardSets
Static Protected Attributes
static const string ROOT_CLASS = "BillboardPresets"
static int m_SetIndexCached = -1
Detailed Description
Definition at line 1 of file BillboardSet.c.
Member Function Documentation
ActivateBillboardSet()
static bool BillboardSetHandler::ActivateBillboardSet (string setClassName, PlayerIdentity identity) inline static protected
Definition at line 42 of file BillboardSet.c.
  {
    if (!g_Game)
      return false;
    if (m_SetIndexCached == -1)
    {
      int setCount = g_Game.ConfigGetChildrenCount(ROOT_CLASS);
      for (int setIndex = 0; setIndex < setCount; setIndex++)
      {
        string setName;
        GetGame().ConfigGetChildName(ROOT_CLASS, setIndex, setName);
        if (setName == setClassName)
        {
          m_SetIndexCached = setIndex;
          break
        }
      }
    }
    if (m_SetIndexCached != -1)
    {
      auto param = new Param1<int>(m_SetIndexCached);
      GetGame().RPCSingleParam(identity.GetPlayer(), ERPCs.RPC_SET_BILLBOARDS, param, true, identity);
      return true;
    }
    return false;
  }
References g_Game, GetGame(), m_SetIndexCached, and ROOT_CLASS.
GetTextureByType()
string BillboardSetHandler::GetTextureByType (string type) inline protected
Definition at line 8 of file BillboardSet.c.
  {
    if (m_BillboardSetIndex == -1)
      return "";
    BillboardSet bbset = m_BillboardSets.Get(m_BillboardSetIndex);
    return bbset.GetTextureByType(type);
  }
References BillboardSet(), m_BillboardSetIndex, and m_BillboardSets.
LoadBillboardConfigs()
bool BillboardSetHandler::LoadBillboardConfigs () inline protected
Definition at line 25 of file BillboardSet.c.
  {
    m_BillboardSets = new array<ref BillboardSet>();
    int setCount = g_Game.ConfigGetChildrenCount(ROOT_CLASS);
    for (int setIndex = 0; setIndex < setCount; setIndex++)
    {
      string setName;
      GetGame().ConfigGetChildName(ROOT_CLASS, setIndex, setName);
      string path = ROOT_CLASS + " " + setName;
      m_BillboardSets.Insert(new BillboardSet(path));
    }
    return true;
  }
References BillboardSet(), g_Game, GetGame(), m_BillboardSets, path, and ROOT_CLASS.
Referenced by OnRPCIndex().
OnRPCIndex()
void BillboardSetHandler::OnRPCIndex (int index) inline protected
Definition at line 16 of file BillboardSet.c.
  {
    if (!m_BillboardSets)
      LoadBillboardConfigs();
    if (m_BillboardSets && m_BillboardSets.IsValidIndex(index))
      m_BillboardSetIndex = index;
  }
References LoadBillboardConfigs(), m_BillboardSetIndex, and m_BillboardSets.
Member Data Documentation
m_BillboardSetIndex
bool BillboardSetHandler::m_BillboardSetIndex = -1 protected
Definition at line 3 of file BillboardSet.c.
Referenced by GetTextureByType(), and OnRPCIndex().
m_BillboardSets
ref array<ref BillboardSet> BillboardSetHandler::m_BillboardSets protected
Definition at line 4 of file BillboardSet.c.
Referenced by GetTextureByType(), LoadBillboardConfigs(), and OnRPCIndex().
m_SetIndexCached
int BillboardSetHandler::m_SetIndexCached = -1 static protected
Definition at line 6 of file BillboardSet.c.
Referenced by ActivateBillboardSet().
ROOT_CLASS
const string BillboardSetHandler::ROOT_CLASS = "BillboardPresets" static protected
Definition at line 5 of file BillboardSet.c.
Referenced by ActivateBillboardSet(), and LoadBillboardConfigs().
The documentation for this class was generated from the following file:
scripts/3_Game/BillboardSet.c