DayZ: ScriptConsoleItemsTab Class Reference
ScriptConsoleItemsTab Class Reference
Protected Member Functions
void ScriptConsoleItemsTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void ~ScriptConsoleItemsTab ()
void Init ()
override bool OnKeyDown (Widget w, int x, int y, int key)
void SelectObject (bool hide_presets=true)
void SelectPreset ()
int GetCurrentPresetIndex ()
int GetCurrentItemIndex ()
bool IsCurrentPresetFixed ()
bool IsPresetFixed (string preset_name)
int GetPresetIndexByName (string preset_name)
void ShowItemButtons ()
void HideItemButtons ()
void ShowItemTransferButtons ()
void ItemMoveUp ()
void ItemMoveDown ()
void SaveProfileSpawnDistance ()
void RenamePreset (string new_preset_name)
void SpawnPreset (EntityAI target, bool clear_inventory, string preset_name, InventoryLocationType location=InventoryLocationType.ATTACHMENT, float distance=0)
void SetDefaultPreset (int preset_index)
void SetObject (string object)
void SetPreviewObject (string object)
void AddItemToPreset ()
void ShowPresetButtons ()
void RemoveItemFromPreset ()
string GetCurrentPresetName ()
string GetCurrentItemName ()
string GetCurrentObjectName ()
void RefreshLists ()
void RenderPresets ()
void RenderPresetItems ()
void NewPreset (string preset_name)
void DeletePreset ()
int GetFilterColor (string color)
void PrepareFilters (string filter, out TStringArray filters, out TIntArray colors)
void ChangeFilter (TStringArray classes, TextListboxWidget widget, MultilineEditBoxWidget filterWidget, int categoryMask=-1, bool ignoreScope=false)
void SetFilterOrder (bool reversed)
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnDoubleClick (Widget w, int x, int y, int button)
override void Update (float timeslice)
void SetTextSpawnButton (ButtonWidget w, bool special, string suffix=" Special")
void UpdateButtonNames ()
TStringArray GetItemsClasses ()
string PreprocessFilterText (MultilineEditBoxWidget w)
void ChangeFilterItems (bool forced=false)
Static Protected Member Functions
static void DrawItems (string type, float distance=0)
static void DrawItemsClear ()
static string GetLastSelectedObject ()
Protected Attributes
const string CONST_DEFAULT_PRESET_PREFIX = "[Default]"
ref array< Widget > m_CategoryButtonsWidgets = new array<Widget>
ref array< string > m_CategoryButtonsNames = {"FIREARMS", "MELEE", "ATTACHMENTS", "MAGAZINES", "AMMO", "FOOD", "MEDICAL", "CARS", "BACKPACKS", "B-BUILDING"}
ref map< Widget, string > m_SpawnButtonsOriginalText = new map<Widget, string>()
int m_CategoryMask
MissionGameplay m_MissionGameplay
ref Timer m_RefreshFilterTimer = new Timer()
PluginDeveloper m_Developer
bool m_FilterOrderReversed
string m_SelectedObject
bool m_IsShiftDown
string m_FilterTextPrev
CheckBoxWidget m_CategoryMergeType
CheckBoxWidget m_ItemPreviewCheckbox
CheckBoxWidget m_ShowProtected
CheckBoxWidget m_ClearInventory
TextListboxWidget m_ObjectsTextListbox
TextListboxWidget m_PresetsTextListbox
TextListboxWidget m_PresetItemsTextListbox
ButtonWidget m_DrawInWorld
ButtonWidget m_DrawInWorldClear
ButtonWidget m_PresetNewButton
ButtonWidget m_PresetDeleteButton
ButtonWidget m_PresetRenameButton
ButtonWidget m_PresetSetDefaultButton
ButtonWidget m_PresetAddItemtButton
ButtonWidget m_ItemNameCopy
ButtonWidget m_PresetRemoveItemButton
ButtonWidget m_ItemMoveUpButton
ButtonWidget m_ItemMoveDownButton
ButtonWidget m_FilterOrderButton
ButtonWidget m_SpawnInInvButton
ButtonWidget m_SpawnGroundButton
ButtonWidget m_SpawnGroundPatternGrid
ButtonWidget m_SpawnOnTarget
ButtonWidget m_SpawnOnCursor
ButtonWidget m_SpawnInHands
ButtonWidget m_SpawnBatchButton
ButtonWidget m_ListActions
MultilineEditBoxWidget m_ObjectFilter
EditBoxWidget m_SpawnDistanceEditBox
EditBoxWidget m_RectSpawnRow
EditBoxWidget m_RectSpawnColumn
EditBoxWidget m_RectSpawnRowStep
EditBoxWidget m_RectSpawnColumnStep
EditBoxWidget m_DrawDistanceWidget
EditBoxWidget m_QuantityEditBox
EditBoxWidget m_DamageEditBox
EditBoxWidget m_BatchSpawnQuantity
CheckBoxWidget m_WithPhysicsCheckbox
TextWidget m_ItemDamageLabel
TextWidget m_ItemQuantityLabel
TextWidget m_SelectedObjectText
ItemPreviewWidget m_ItemPreviewWidget
ImageWidget m_FilterOrderImage
Static Protected Attributes
static int ITEMS_SELECTED_ROW = -1
static int PRESETS_SELECTED_ROW = 0
static int ITEMS_IN_PRESET_SELECTED_ROW
static float DRAW_DISTANCE = 1000
static bool CLEAR_IVN
static int m_ObjectsScope = 2
static string m_LastSelectedObject
static int m_SelectedObjectIsPreset = -1
static ref array< Shape > m_DebugShapes = new array<Shape>
static EntityAI m_PreviewEntity
static float m_ItemQuantity = 1
static bool m_WithPhysics = false
Private Member Functions
bool ListItemRelatedActions ()
Private Member Functions inherited from ScriptConsoleTabBase
void ScriptConsoleTabBase (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void Init (int id)
int GetID ()
Widget GetRoot ()
bool IsSelected ()
void Select (bool select, ScriptConsoleTabBase selectedHandler)
void OnSelected ()
void Show (bool show, ScriptConsoleTabBase selectedHandler)
Widget GetButton ()
void Update (float timeslice)
bool OnChange (Widget w, int x, int y, bool finished)
bool OnClick (Widget w, int x, int y, int button)
bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
bool OnKeyDown (Widget w, int x, int y, int key)
bool OnDoubleClick (Widget w, int x, int y, int button)
void OnRPCEx (int rpc_type, ParamsReadContext ctx)
bool OnMouseButtonDown (Widget w, int x, int y, int button)
bool OnKeyPress (Widget w, int x, int y, int key)
void AddItemToClipboard (TextListboxWidget text_listbox_widget)
Additional Inherited Members
Private Attributes inherited from ScriptConsoleTabBase
int m_Id
bool m_IsSelected
Widget m_ParentRoot
Widget m_Root
Widget m_Button
ScriptConsole m_ScriptConsole
ScriptConsoleTabBase m_Parent
PluginConfigDebugProfile m_ConfigDebugProfile
PluginConfigDebugProfileFixed m_ConfigDebugProfileFixed
Detailed Description
Definition at line 3 of file ScriptConsoleItemsTab.c.
Constructor & Destructor Documentation
ScriptConsoleItemsTab()
void ScriptConsoleItemsTab::ScriptConsoleItemsTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent = null) inline protected
Definition at line 77 of file ScriptConsoleItemsTab.c.
  {
    m_Developer = PluginDeveloper.Cast(GetPlugin(PluginDeveloper));
    m_DrawInWorld = ButtonWidget.Cast(root.FindAnyWidget("ButtonDrawItem"));
    m_DrawInWorldClear = ButtonWidget.Cast(root.FindAnyWidget("ButtonDrawItemClear"));
    m_CategoryMergeType = CheckBoxWidget.Cast(root.FindAnyWidget("CategoryMergeType"));
    m_ItemPreviewCheckbox = CheckBoxWidget.Cast(root.FindAnyWidget("ItemPreviewCheckbox"));
    m_ShowProtected = CheckBoxWidget.Cast(root.FindAnyWidget("ShowProtectedCheckbox"));
    m_FilterOrderImage = ImageWidget.Cast(root.FindAnyWidget("ObjectFilterSortPic"));
    m_ClearInventory = CheckBoxWidget.Cast(root.FindAnyWidget("ForceClearCheckbox"));
    m_DrawDistanceWidget = EditBoxWidget.Cast(root.FindAnyWidget("DrawItemDistance"));
    m_ObjectFilter = MultilineEditBoxWidget.Cast(root.FindAnyWidget("ObjectFilter"));
    m_SpawnDistanceEditBox = EditBoxWidget.Cast(root.FindAnyWidget("SpawnDistance"));
    m_SelectedObjectText = TextWidget.Cast(root.FindAnyWidget("SelectedObject"));
    m_ObjectsTextListbox = TextListboxWidget.Cast(root.FindAnyWidget("ObjectsList"));
    m_PresetsTextListbox = TextListboxWidget.Cast(root.FindAnyWidget("PresetList"));
    m_PresetItemsTextListbox = TextListboxWidget.Cast(root.FindAnyWidget("PresetItemsList"));
    m_PresetNewButton = ButtonWidget.Cast(root.FindAnyWidget("NewPresetButton"));
    m_PresetDeleteButton = ButtonWidget.Cast(root.FindAnyWidget("DeletePresetButton"));
    m_PresetRenameButton = ButtonWidget.Cast(root.FindAnyWidget("RenamePresetButton"));
    m_PresetSetDefaultButton = ButtonWidget.Cast(root.FindAnyWidget("SetDefaultPresetButton"));
    m_PresetAddItemtButton = ButtonWidget.Cast(root.FindAnyWidget("AddToPresetButton"));
    m_ItemNameCopy = ButtonWidget.Cast(root.FindAnyWidget("ItemNameCopy"));
    m_PresetRemoveItemButton = ButtonWidget.Cast(root.FindAnyWidget("RemoveFromPresetButton"));
    m_ItemMoveUpButton = ButtonWidget.Cast(root.FindAnyWidget("ItemMoveUpButton"));
    m_ItemMoveDownButton = ButtonWidget.Cast(root.FindAnyWidget("ItemMoveDownButton"));
    m_ItemPreviewWidget = ItemPreviewWidget.Cast(root.FindAnyWidget("ItemPreviewWidget"));
    m_QuantityEditBox = EditBoxWidget.Cast(root.FindAnyWidget("QuantityValue"));
    m_DamageEditBox = EditBoxWidget.Cast(root.FindAnyWidget("DamageValue"));
    m_ItemDamageLabel = TextWidget.Cast(root.FindAnyWidget("DamageLabel"));
    m_ItemQuantityLabel = TextWidget.Cast(root.FindAnyWidget("QuantityLabel"));
    m_WithPhysicsCheckbox = CheckBoxWidget.Cast(root.FindAnyWidget("WithPhysicsCheckbox"));
    m_SpawnInInvButton = ButtonWidget.Cast(root.FindAnyWidget("ButtonSpawnInInv"));
    m_SpawnGroundButton = ButtonWidget.Cast(root.FindAnyWidget("ButtonSpawnInGround"));
    m_SpawnOnTarget = ButtonWidget.Cast(root.FindAnyWidget("ButtonSpawnInTarget"));
    m_SpawnOnCursor = ButtonWidget.Cast(root.FindAnyWidget("ButtonSpawnCursor"));
    m_SpawnInHands = ButtonWidget.Cast(root.FindAnyWidget("ButtonSpawnHands"));
    m_SpawnBatchButton = ButtonWidget.Cast(root.FindAnyWidget("ButtonSpawnBatch"));
    string text;
    m_SpawnInInvButton.GetText(text);
    m_SpawnButtonsOriginalText.Insert(m_SpawnInInvButton, text);
    m_SpawnGroundButton.GetText(text);
    m_SpawnButtonsOriginalText.Insert(m_SpawnGroundButton, text);
    m_SpawnOnTarget.GetText(text);
    m_SpawnButtonsOriginalText.Insert(m_SpawnOnTarget, text);
    m_SpawnOnCursor.GetText(text);
    m_SpawnButtonsOriginalText.Insert(m_SpawnOnCursor, text);
    m_SpawnInHands.GetText(text);
    m_SpawnButtonsOriginalText.Insert(m_SpawnInHands, text);
    m_SpawnBatchButton.GetText(text);
    m_SpawnButtonsOriginalText.Insert(m_SpawnBatchButton, text);
    m_ListActions = ButtonWidget.Cast(root.FindAnyWidget("ListActions"));
    m_RectSpawnColumn = EditBoxWidget.Cast(root.FindAnyWidget("RectangleColumnValue"));
    m_RectSpawnRow = EditBoxWidget.Cast(root.FindAnyWidget("RectangleRowValue"));
    m_BatchSpawnQuantity = EditBoxWidget.Cast(root.FindAnyWidget("BatchCount"));
    m_RectSpawnColumnStep = EditBoxWidget.Cast(root.FindAnyWidget("RectangleStepXValue"));
    m_RectSpawnRowStep = EditBoxWidget.Cast(root.FindAnyWidget("RectangleStepYValue"));
    m_FilterOrderButton = ButtonWidget.Cast(root.FindAnyWidget("ObjectFilterSortButton"));
    Init();
  }
References GetPlugin(), Init(), m_BatchSpawnQuantity, m_CategoryMergeType, m_ClearInventory, m_DamageEditBox, m_Developer, m_DrawDistanceWidget, m_DrawInWorld, m_DrawInWorldClear, m_FilterOrderButton, m_FilterOrderImage, m_ItemDamageLabel, m_ItemMoveDownButton, m_ItemMoveUpButton, m_ItemNameCopy, m_ItemPreviewCheckbox, m_ItemPreviewWidget, m_ItemQuantityLabel, m_ListActions, m_ObjectFilter, m_ObjectsTextListbox, m_PresetAddItemtButton, m_PresetDeleteButton, m_PresetItemsTextListbox, m_PresetNewButton, m_PresetRemoveItemButton, m_PresetRenameButton, m_PresetSetDefaultButton, m_PresetsTextListbox, m_QuantityEditBox, m_RectSpawnColumn, m_RectSpawnColumnStep, m_RectSpawnRow, m_RectSpawnRowStep, m_SelectedObjectText, m_ShowProtected, m_SpawnBatchButton, m_SpawnButtonsOriginalText, m_SpawnDistanceEditBox, m_SpawnGroundButton, m_SpawnInHands, m_SpawnInInvButton, m_SpawnOnCursor, m_SpawnOnTarget, and m_WithPhysicsCheckbox.
~ScriptConsoleItemsTab()
void ScriptConsoleItemsTab::~ScriptConsoleItemsTab () inline protected
Definition at line 148 of file ScriptConsoleItemsTab.c.
  {
    ITEMS_SELECTED_ROW = m_ObjectsTextListbox.GetSelectedRow();
    PRESETS_SELECTED_ROW = m_PresetsTextListbox.GetSelectedRow();
    ITEMS_IN_PRESET_SELECTED_ROW = m_PresetItemsTextListbox.GetSelectedRow();
    m_PresetsTextListbox.ClearItems();
    if (m_PreviewEntity)
      m_PreviewEntity.Delete();
    m_RefreshFilterTimer.Stop();
    if (m_ConfigDebugProfile)
      m_ConfigDebugProfile.SetItemCategoryFlag(m_CategoryMask);
    m_ItemQuantity = m_QuantityEditBox.GetText().ToFloat();
    m_WithPhysics = m_WithPhysicsCheckbox.IsChecked();
  }
References ITEMS_IN_PRESET_SELECTED_ROW, ITEMS_SELECTED_ROW, m_CategoryMask, ScriptConsoleTabBase::m_ConfigDebugProfile, m_ItemQuantity, m_ObjectsTextListbox, m_PresetItemsTextListbox, m_PresetsTextListbox, m_PreviewEntity, m_QuantityEditBox, m_RefreshFilterTimer, m_WithPhysics, m_WithPhysicsCheckbox, and PRESETS_SELECTED_ROW.
Member Function Documentation
AddItemToPreset()
void ScriptConsoleItemsTab::AddItemToPreset () inline protected
Definition at line 660 of file ScriptConsoleItemsTab.c.
  {
    int selected_row_index = m_ObjectsTextListbox.GetSelectedRow();
    if (selected_row_index != -1 && GetCurrentPresetIndex() != -1)
    {
      string item_name;
      m_ObjectsTextListbox.GetItemText(selected_row_index, 0, item_name);
      m_ConfigDebugProfile.ItemAddToPreset(GetCurrentPresetName(), item_name);
      RenderPresetItems();
    }
  }
References GetCurrentPresetIndex(), GetCurrentPresetName(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_ObjectsTextListbox, and RenderPresetItems().
Referenced by OnClick().
ChangeFilter()
void ScriptConsoleItemsTab::ChangeFilter (TStringArray classes, TextListboxWidget widget, MultilineEditBoxWidget filterWidget, int categoryMask = -1, bool ignoreScope = false) inline protected
Definition at line 868 of file ScriptConsoleItemsTab.c.
  {
    widget.ClearItems();
    TStringArray filters;
    TIntArray filterColors;
    string widgetText;
    filterWidget.GetText(widgetText);
    PrepareFilters(widgetText, filters, filterColors);
    map<string, int> itemsAndColors = new map<string, int>();
    map<string, ref TStringArray> itemsByFilters = new map<string, ref TStringArray>();
    TStringArray itemsArray = TStringArray();
    for (int i = 0; i < classes.Count(); i++)
    {
      string config_path = classes.Get(i);
      int objects_count = GetGame().ConfigGetChildrenCount(config_path);
      for (int j = 0; j < objects_count; j++)
      {
        string child_name;
        GetGame().ConfigGetChildName(config_path, j, child_name);
        int scope = GetGame().ConfigGetInt(config_path + " " + child_name + " scope");
        if (scope >= m_ObjectsScope || ignoreScope)
        {
          int category_bit = GetGame().ConfigGetInt(config_path + " " + child_name + " debug_ItemCategory") - 1;
          category_bit = (1 << category_bit);
          bool display = false;
          int color = 0;
          if (category_bit & categoryMask)
            display = true;
          else if ((!m_ConfigDebugProfile.GetMergeType() || categoryMask == 0) && filters.Count() > 0)
          {
            string child_name_lower = child_name;
            child_name_lower.ToLower();
            foreach (int indx, string filter: filters)
            {
              if (child_name_lower.Contains(filter))
              {
                display = false;
                color = filterColors.Get(indx);
                TStringArray arr = itemsByFilters.Get(filter);
                if (!arr)
                {
                  arr = new TStringArray();
                  itemsByFilters.Set(filter, arr);
                }
                arr.Insert(child_name);
                itemsAndColors.Insert(child_name, color);
                break;
              }
            }
          }
          else if (categoryMask == 0)
            display = true;
          if (display)
            itemsArray.Insert(child_name);
        }
      }
    }
    if (itemsArray)
    {
      itemsArray.Sort();
      foreach (string it: itemsArray)
        widget.AddItem(it, NULL, 0);
    }
    if (filters)
    {
      if (m_FilterOrderReversed)
        filters.Invert();
      foreach (string f: filters)
      {
        TStringArray arr2 = itemsByFilters.Get(f);
        if (arr2)
        {
          arr2.Sort();
          foreach (string itm: arr2)
          {
            int row = widget.AddItem(itm, NULL, 0);
            int clr = itemsAndColors.Get(itm);
            if (clr)
              widget.SetItemColor(row, 0, clr);
          }
        }
      }
    }
  }
References GetGame(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_FilterOrderReversed, m_ObjectsScope, and PrepareFilters().
Referenced by ChangeFilterItems().
ChangeFilterItems()
void ScriptConsoleItemsTab::ChangeFilterItems (bool forced = false) inline protected
Definition at line 1457 of file ScriptConsoleItemsTab.c.
  {
    string widgetText = PreprocessFilterText(m_ObjectFilter);
    if (widgetText == m_FilterTextPrev && !forced)
      return;
    m_FilterTextPrev = widgetText;
    string txt = m_ConfigDebugProfile.GetItemSearch();
    m_ConfigDebugProfile.SetItemSearch(widgetText);
    ChangeFilter(GetItemsClasses(), m_ObjectsTextListbox, m_ObjectFilter, m_CategoryMask);
  }
References ChangeFilter(), GetItemsClasses(), m_CategoryMask, ScriptConsoleTabBase::m_ConfigDebugProfile, m_FilterTextPrev, m_ObjectFilter, m_ObjectsTextListbox, and PreprocessFilterText().
Referenced by Init(), OnChange(), OnClick(), and SetFilterOrder().
DeletePreset()
void ScriptConsoleItemsTab::DeletePreset () inline protected
Definition at line 809 of file ScriptConsoleItemsTab.c.
  {
    if (GetCurrentPresetIndex() != -1)
    {
      bool result = m_ConfigDebugProfile.PresetRemove(GetCurrentPresetName());
      RefreshLists();
    }
  }
References GetCurrentPresetIndex(), GetCurrentPresetName(), ScriptConsoleTabBase::m_ConfigDebugProfile, and RefreshLists().
Referenced by OnClick().
DrawItems()
static void ScriptConsoleItemsTab::DrawItems (string type, float distance = 0) inline static protected
need better logic for cleaning
Definition at line 283 of file ScriptConsoleItemsTab.c.
  {
    if (!distance)
      distance = DRAW_DISTANCE;
    array<Object> objects = new array<Object>;
    array<CargoBase> proxies = new array<CargoBase>;
    GetGame().GetObjectsAtPosition(GetGame().GetPlayer().GetPosition(), distance, objects, proxies);
    int i = 0;
    foreach (Object o: objects)
    {
      if (o.IsKindOf(type))
      {
        i++;
        ScriptConsole.m_MarkedEntities.Insert(new MapMarker(o.GetPosition(), "", COLOR_RED, eMapMarkerTypes.MARKERTYPE_MAP_BORDER_CROSS));
        Shape shape = Shape.CreateSphere(COLOR_RED, ShapeFlags.TRANSP | ShapeFlags.NOOUTLINE | ShapeFlags.NOZBUFFER, o.GetPosition() + "0 30 0", 1);
        vector lines[2];
        lines[0] = o.GetPosition();
        lines[1] = o.GetPosition() + "0 30 0";
        Shape line = Shape.CreateLines(COLOR_RED, ShapeFlags.TRANSP | ShapeFlags.NOOUTLINE | ShapeFlags.NOZBUFFER, lines, 2);
        m_DebugShapes.Insert(shape);
        m_DebugShapes.Insert(line);
      }
    }
    //GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLaterByName(this, "DrawItemsClear", 5000);
    Debug.Log(string.Format("found %1 instances of type %1", i, type));
  }
References COLOR_RED, DRAW_DISTANCE, GetGame(), GetPlayer(), GetPosition, Debug::Log(), m_DebugShapes, and Shape.
Referenced by OnClick(), and OnKeyDown().
DrawItemsClear()
static void ScriptConsoleItemsTab::DrawItemsClear () inline static protected
Definition at line 314 of file ScriptConsoleItemsTab.c.
  {
    ScriptConsole.m_MarkedEntities.Clear();
    foreach (Shape s: m_DebugShapes)
      s.Destroy();
    m_DebugShapes.Clear();
  }
References m_DebugShapes, and Shape.
Referenced by OnClick().
GetCurrentItemIndex()
int ScriptConsoleItemsTab::GetCurrentItemIndex () inline protected
Definition at line 383 of file ScriptConsoleItemsTab.c.
  {
    return m_PresetItemsTextListbox.GetSelectedRow();
  }
References m_PresetItemsTextListbox.
Referenced by GetCurrentItemName(), ItemMoveDown(), ItemMoveUp(), OnChange(), RemoveItemFromPreset(), ShowItemButtons(), and ShowItemTransferButtons().
GetCurrentItemName()
string ScriptConsoleItemsTab::GetCurrentItemName () inline protected
Definition at line 717 of file ScriptConsoleItemsTab.c.
  {
    if (GetCurrentItemIndex() != -1)
    {
      string item_name;
      m_PresetItemsTextListbox.GetItemText(GetCurrentItemIndex(), 0, item_name);
      return item_name;
    }
    return "";
  }
References GetCurrentItemIndex(), and m_PresetItemsTextListbox.
Referenced by Init(), OnClick(), and OnItemSelected().
GetCurrentObjectName()
string ScriptConsoleItemsTab::GetCurrentObjectName () inline protected
Definition at line 728 of file ScriptConsoleItemsTab.c.
  {
    int selected_row_index = m_ObjectsTextListbox.GetSelectedRow();
    if (selected_row_index != -1)
    {
      string item_name;
      m_ObjectsTextListbox.GetItemText(selected_row_index, 0, item_name);
      return item_name;
    }
    return "";
  }
References m_ObjectsTextListbox.
Referenced by Init(), OnDoubleClick(), and SelectObject().
GetCurrentPresetIndex()
int ScriptConsoleItemsTab::GetCurrentPresetIndex () inline protected
Definition at line 378 of file ScriptConsoleItemsTab.c.
  {
    return m_PresetsTextListbox.GetSelectedRow();
  }
References m_PresetsTextListbox.
Referenced by AddItemToPreset(), DeletePreset(), GetCurrentPresetName(), IsCurrentPresetFixed(), ItemMoveDown(), ItemMoveUp(), OnClick(), RemoveItemFromPreset(), RenamePreset(), RenderPresetItems(), SetDefaultPreset(), ShowItemTransferButtons(), and SpawnPreset().
GetCurrentPresetName()
string ScriptConsoleItemsTab::GetCurrentPresetName () inline protected
Definition at line 704 of file ScriptConsoleItemsTab.c.
  {
    int index = GetCurrentPresetIndex();
    // load preset items list
    if (index > -1 && index < m_PresetsTextListbox.GetNumItems())
    {
      PresetParams item_params_array;
      m_PresetsTextListbox.GetItemData(index, 0, item_params_array);
      return item_params_array.param1;
    }
    return "";
  }
References GetCurrentPresetIndex(), and m_PresetsTextListbox.
Referenced by AddItemToPreset(), DeletePreset(), ItemMoveDown(), ItemMoveUp(), OnChange(), OnClick(), RemoveItemFromPreset(), RenamePreset(), RenderPresetItems(), SelectPreset(), SetDefaultPreset(), and ShowItemButtons().
GetFilterColor()
int ScriptConsoleItemsTab::GetFilterColor (string color) inline protected
Definition at line 818 of file ScriptConsoleItemsTab.c.
  {
    switch (color)
    {
    case "r":
      return ARGB(255, 255, 0, 0);
    case "g":
      return ARGB(255, 0, 255, 0);
    case "b":
      return ARGB(255, 130, 130, 255);
    case "y":
      return ARGB(255, 255, 255, 0);
    case "o":
      return ARGB(255, 255, 169, 0);
    }
    return -1;//white
  }
References ARGB().
Referenced by PrepareFilters().
GetItemsClasses()
TStringArray ScriptConsoleItemsTab::GetItemsClasses () inline protected
Definition at line 1439 of file ScriptConsoleItemsTab.c.
  {
    return {CFG_VEHICLESPATH, CFG_WEAPONSPATH, CFG_MAGAZINESPATH, CFG_AMMO};
  }
References CFG_AMMO, CFG_MAGAZINESPATH, CFG_VEHICLESPATH, and CFG_WEAPONSPATH.
Referenced by ChangeFilterItems().
GetLastSelectedObject()
static string ScriptConsoleItemsTab::GetLastSelectedObject () inline static protected
Definition at line 323 of file ScriptConsoleItemsTab.c.
  {
    return m_LastSelectedObject;
  }
References m_LastSelectedObject.
Referenced by Dispatcher::CallMethod().
GetPresetIndexByName()
int ScriptConsoleItemsTab::GetPresetIndexByName (string preset_name) inline protected
Definition at line 412 of file ScriptConsoleItemsTab.c.
  {
    int i;
    for (i = 0; i < m_PresetsTextListbox.GetNumItems(); i++)
    {
      PresetParams item_params_array;
      m_PresetsTextListbox.GetItemData(i, 0, item_params_array);
      if (item_params_array.param1 == preset_name)
        return i;
    }
    return -1;
  }
References m_PresetsTextListbox.
Referenced by IsPresetFixed(), RenderPresets(), and SetDefaultPreset().
HideItemButtons()
void ScriptConsoleItemsTab::HideItemButtons () inline protected
Definition at line 470 of file ScriptConsoleItemsTab.c.
  {
    m_ItemMoveUpButton.Show(false);
    m_ItemMoveDownButton.Show(false);
  }
References m_ItemMoveDownButton, and m_ItemMoveUpButton.
Referenced by Init(), OnDoubleClick(), SelectObject(), and ShowPresetButtons().
Init()
void ScriptConsoleItemsTab::Init () inline protected
Definition at line 169 of file ScriptConsoleItemsTab.c.
  {
    m_RefreshFilterTimer.Run(0.85, this, "ChangeFilterItems", null, true);
    m_PresetDeleteButton.Show(false);
    m_PresetRenameButton.Show(false);
    m_DrawDistanceWidget.SetText(DRAW_DISTANCE.ToString());
    m_QuantityEditBox.SetText(m_ItemQuantity.ToString());
    m_WithPhysicsCheckbox.SetChecked(m_WithPhysics);
    if (m_ConfigDebugProfile)
    {
      string txt = (m_ConfigDebugProfile.GetItemSearch());
      m_ObjectFilter.SetText(m_ConfigDebugProfile.GetItemSearch());
      m_SpawnDistanceEditBox.SetText(m_ConfigDebugProfile.GetSpawnDistance().ToString());
      SetFilterOrder(m_ConfigDebugProfile.GetFilterOrderReversed());
      //m_ConfigDebugProfile.SetItemCategoryFlag(m_CategoryMask);
      m_BatchSpawnQuantity.SetText(m_ConfigDebugProfile.GetBatchSpawnQuantity().ToString());
      m_CategoryMask = m_ConfigDebugProfile.GetItemCategoryFlag();
      if (m_ItemPreviewCheckbox)
        m_ItemPreviewCheckbox.SetChecked(m_ConfigDebugProfile.GetShowItemPreview());
      array<ref CfgParam> params = m_ConfigDebugProfile.GetBatchSpawnRectangle();
      m_RectSpawnRow.SetText(CfgParamInt.Cast(params.Get(0)).GetValue().ToString());
      m_RectSpawnColumn.SetText(CfgParamInt.Cast(params.Get(1)).GetValue().ToString());
      m_RectSpawnRowStep.SetText(CfgParamFloat.Cast(params.Get(2)).GetValue().ToString());
      m_RectSpawnColumnStep.SetText(CfgParamFloat.Cast(params.Get(3)).GetValue().ToString());
    }
    if (m_ObjectsScope == 1)
      m_ShowProtected.SetChecked(true);
    else
      m_ShowProtected.SetChecked(false);
    int counter = 0;
    foreach (string name: m_CategoryButtonsNames)
    {
      string widget_name = "ItemCategory" + counter;
      CheckBoxWidget btw = CheckBoxWidget.Cast(m_ParentRoot.FindAnyWidget(widget_name));
      if (btw)
      {
        btw.SetText(name);
        m_CategoryButtonsWidgets.Insert(btw);
        int bit = 1 << counter;
        if (bit & m_CategoryMask)
        {
          btw.SetChecked(true);
          btw.SetTextColor(ARGB(255, 255, 0, 0));
        }
      }
      counter++;
    }
    if (ITEMS_IN_PRESET_SELECTED_ROW <= m_PresetItemsTextListbox.GetNumItems() && m_PresetItemsTextListbox.GetNumItems() > 0 && ITEMS_IN_PRESET_SELECTED_ROW > -1)
    {
      m_PresetItemsTextListbox.SelectRow(ITEMS_IN_PRESET_SELECTED_ROW);
      m_PresetItemsTextListbox.EnsureVisible(ITEMS_IN_PRESET_SELECTED_ROW);
      m_SelectedObjectText.SetText("Object : " + GetCurrentItemName());
      SetObject(GetCurrentItemName());
      m_SelectedObjectIsPreset = 0;
    }
    ChangeFilterItems(true);
    RenderPresets();
    //RenderPresetItems();
    m_MissionGameplay = MissionGameplay.Cast(GetGame().GetMission());
    if (!m_SelectedObjectIsPreset == 1 && ITEMS_SELECTED_ROW < m_ObjectsTextListbox.GetNumItems() && m_ObjectsTextListbox.GetNumItems() > 0 && ITEMS_SELECTED_ROW > -1)
    {
      m_ObjectsTextListbox.SelectRow(ITEMS_SELECTED_ROW);
      m_ObjectsTextListbox.EnsureVisible(ITEMS_SELECTED_ROW);
      m_SelectedObjectText.SetText(GetCurrentObjectName());
      SetObject(GetCurrentObjectName());
      m_LastSelectedObject = m_SelectedObject;
      m_PresetItemsTextListbox.SelectRow(-1);
      m_SelectedObjectIsPreset = 0;
    }
    if (m_PresetsTextListbox.GetNumItems() >= 0)
    {
      m_PresetsTextListbox.SelectRow(PRESETS_SELECTED_ROW);
      m_PresetsTextListbox.EnsureVisible(PRESETS_SELECTED_ROW);
      if (m_SelectedObjectIsPreset == 1)
        SelectPreset();
      else
        RenderPresetItems();
    }
    if (m_ObjectsScope == 1)
      m_ShowProtected.SetChecked(true);
    else
      m_ShowProtected.SetChecked(false);
    m_CategoryMergeType.SetChecked(m_ConfigDebugProfile.GetMergeType());
    HideItemButtons();
    ShowItemTransferButtons();
  }
References ARGB(), ChangeFilterItems(), DRAW_DISTANCE, GetCurrentItemName(), GetCurrentObjectName(), GetGame(), HideItemButtons(), ITEMS_IN_PRESET_SELECTED_ROW, ITEMS_SELECTED_ROW, m_BatchSpawnQuantity, m_CategoryButtonsNames, m_CategoryButtonsWidgets, m_CategoryMask, m_CategoryMergeType, ScriptConsoleTabBase::m_ConfigDebugProfile, m_DrawDistanceWidget, m_ItemPreviewCheckbox, m_ItemQuantity, m_LastSelectedObject, m_MissionGameplay, m_ObjectFilter, m_ObjectsScope, m_ObjectsTextListbox, ScriptConsoleTabBase::m_ParentRoot, m_PresetDeleteButton, m_PresetItemsTextListbox, m_PresetRenameButton, m_PresetsTextListbox, m_QuantityEditBox, m_RectSpawnColumn, m_RectSpawnColumnStep, m_RectSpawnRow, m_RectSpawnRowStep, m_RefreshFilterTimer, m_SelectedObject, m_SelectedObjectIsPreset, m_SelectedObjectText, m_ShowProtected, m_SpawnDistanceEditBox, m_WithPhysics, m_WithPhysicsCheckbox, name, PRESETS_SELECTED_ROW, RenderPresetItems(), RenderPresets(), SelectPreset(), SetFilterOrder(), SetObject(), and ShowItemTransferButtons().
Referenced by ScriptConsoleItemsTab().
IsCurrentPresetFixed()
bool ScriptConsoleItemsTab::IsCurrentPresetFixed () inline protected
Definition at line 388 of file ScriptConsoleItemsTab.c.
  {
    int index = GetCurrentPresetIndex();
    if (index > -1 && index < m_PresetsTextListbox.GetNumItems())
    {
      PresetParams item_params_array;
      m_PresetsTextListbox.GetItemData(index, 0, item_params_array);
      return item_params_array.param2;
    }
    return false;
  }
References GetCurrentPresetIndex(), and m_PresetsTextListbox.
Referenced by RenderPresetItems(), ShowItemButtons(), ShowItemTransferButtons(), ShowPresetButtons(), and SpawnPreset().
IsPresetFixed()
bool ScriptConsoleItemsTab::IsPresetFixed (string preset_name) inline protected
Definition at line 400 of file ScriptConsoleItemsTab.c.
  {
    int preset_index = GetPresetIndexByName(preset_name);
    PresetParams item_params_array;
    if (preset_index > -1 && preset_index < m_PresetsTextListbox.GetNumItems())
    {
      m_PresetsTextListbox.GetItemData(preset_index, 0, item_params_array);
      return item_params_array.param2;
    }
    return false;
  }
References GetPresetIndexByName(), and m_PresetsTextListbox.
Referenced by RenderPresets(), SelectPreset(), and SetDefaultPreset().
ItemMoveDown()
void ScriptConsoleItemsTab::ItemMoveDown () inline protected
Definition at line 507 of file ScriptConsoleItemsTab.c.
  {
    int new_index = GetCurrentItemIndex() + 1;
    if (GetCurrentItemIndex() != -1 && GetCurrentPresetIndex() != -1 && new_index < m_PresetItemsTextListbox.GetNumItems())
    {
      m_ConfigDebugProfile.SwapItem(GetCurrentPresetName(), GetCurrentItemIndex(), new_index);
      RenderPresetItems();
      m_PresetItemsTextListbox.SelectRow(new_index);
    }
  }
References GetCurrentItemIndex(), GetCurrentPresetIndex(), GetCurrentPresetName(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_PresetItemsTextListbox, and RenderPresetItems().
Referenced by OnClick().
ItemMoveUp()
void ScriptConsoleItemsTab::ItemMoveUp () inline protected
Definition at line 496 of file ScriptConsoleItemsTab.c.
  {
    int new_index = GetCurrentItemIndex() - 1;
    if (GetCurrentItemIndex() != -1 && GetCurrentPresetIndex() != -1 && new_index > -1)
    {
      m_ConfigDebugProfile.SwapItem(GetCurrentPresetName(), GetCurrentItemIndex(), new_index);
      RenderPresetItems();
      m_PresetItemsTextListbox.SelectRow(new_index);
    }
  }
References GetCurrentItemIndex(), GetCurrentPresetIndex(), GetCurrentPresetName(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_PresetItemsTextListbox, and RenderPresetItems().
Referenced by OnClick().
ListItemRelatedActions()
bool ScriptConsoleItemsTab::ListItemRelatedActions () inline private
Definition at line 1470 of file ScriptConsoleItemsTab.c.
  {
    string message = "";
    array<ActionBase_Basic> interactActions = new array<ActionBase_Basic>();
    m_PreviewEntity.GetActions(InteractActionInput, interactActions);
    if (interactActions)
    {
      message += "\n== Interact (F)\n\n";
      foreach (ActionBase_Basic iaction : interactActions)
      {
        if (iaction.Type() == ActionWorldCraft)
          continue;
        ActionBase ia = ActionBase.Cast(iaction);
        message += string.Format("%1 <%2>\n", Widget.TranslateString(ia.GetText()), ia.ClassName());
      }
    }
    array<ActionBase_Basic> continuousInteractActions = new array<ActionBase_Basic>();
    m_PreviewEntity.GetActions(ContinuousInteractActionInput, continuousInteractActions);
    if (continuousInteractActions)
    {
      message += "\n== Continuous Interact (F hold)\n\n";
      foreach (ActionBase_Basic ciaction : continuousInteractActions)
      {
        if (ciaction.Type() == ActionWorldCraft)
          continue;
        ActionBase cia = ActionBase.Cast(ciaction);
        message += string.Format("%1 <%2>\n", Widget.TranslateString(cia.GetText()), cia.ClassName());
      }
    }
    array<ActionBase_Basic> singleActions = new array<ActionBase_Basic>();
    m_PreviewEntity.GetActions(DefaultActionInput, singleActions);
    if (singleActions)
    {
      message += "\n== Single (LMB)\n\n";
      foreach (ActionBase_Basic saction : singleActions)
      {
        if (saction.Type() == ActionWorldCraft)
          continue;
        ActionBase sa = ActionBase.Cast(saction);
        message += string.Format("%1 <%2>\n", Widget.TranslateString(sa.GetText()), sa.ClassName());
      }
    }
    array<ActionBase_Basic> continuousActions = new array<ActionBase_Basic>();
    m_PreviewEntity.GetActions(ContinuousDefaultActionInput, continuousActions);
    if (continuousActions)
    {
      ActionBase_Basic craftingAction;
      message += "\n== Continuous (LMB hold)\n\n";
      foreach (ActionBase_Basic caction : continuousActions)
      {
        if (caction.Type() != ActionWorldCraft)
        {
          ActionBase ca = ActionBase.Cast(caction);
          message += string.Format("%1 <%2>\n", Widget.TranslateString(ca.GetText()), ca.ClassName());
        }
        else
          craftingAction = caction;
      }
      message += "\n== Crafting recipes \n\n";
      if (craftingAction)
      {
        PluginRecipesManager pluginRecipesManager = PluginRecipesManager.Cast(GetPlugin(PluginRecipesManager));
        array<RecipeBase> recipes = pluginRecipesManager.GetRecipesForItem(m_PreviewEntity.GetType());
        foreach (RecipeBase recipe : recipes)
        {
          if (recipe.IsItemInRecipe("Inventory_Base"))
            continue;
          message += string.Format("%1 <%2>\n", Widget.TranslateString(recipe.GetName()), recipe.Type());
        }
      }
    }
    ScriptConsoleUniversalInfoDialog infoDialog = ScriptConsoleUniversalInfoDialog.Cast(g_Game.GetUIManager().EnterScriptedMenu(MENU_SCRIPTCONSOLE_UNIVERSAL_INFO_DIALOG, m_ScriptConsole));
    infoDialog.SetLabel(string.Format("%1 related actions", m_PreviewEntity.GetType()));
    infoDialog.SetContent(message);
    return true;
  }
References g_Game, GetPlugin(), m_PreviewEntity, ScriptConsoleTabBase::m_ScriptConsole, and MENU_SCRIPTCONSOLE_UNIVERSAL_INFO_DIALOG.
Referenced by OnClick().
NewPreset()
void ScriptConsoleItemsTab::NewPreset (string preset_name) inline protected
Definition at line 803 of file ScriptConsoleItemsTab.c.
  {
    m_ConfigDebugProfile.PresetAdd(preset_name);
    RefreshLists();
  }
References ScriptConsoleTabBase::m_ConfigDebugProfile, and RefreshLists().
OnChange()
override bool ScriptConsoleItemsTab::OnChange (Widget w, int x, int y, bool finished) inline protected
Definition at line 984 of file ScriptConsoleItemsTab.c.
  {
    super.OnChange(w, x, y, finished);
    if (w == m_ShowProtected)
    {
      if (m_ShowProtected.IsChecked())
        m_ObjectsScope = 1;
      else
        m_ObjectsScope = 2;
      ChangeFilterItems(true);
      return true;
    }
    else if (w == m_ClearInventory)
    {
      CLEAR_IVN = m_ClearInventory.IsChecked();
      return true;
    }
    else if (m_CategoryButtonsWidgets.Find(w) >= 0)
    {
      int pos = m_CategoryButtonsWidgets.Find(w);
      int bit = Math.Pow(2, pos);
      CheckBoxWidget cbw = CheckBoxWidget.Cast(w);
      if (cbw.IsChecked())
      {
        m_CategoryMask = m_CategoryMask | bit;
        cbw.SetTextColor(ARGB(255, 255, 0, 0));
      }
      else
      {
        m_CategoryMask = (m_CategoryMask & ~bit);
        cbw.SetTextColor(ARGB(255, 255, 255, 255));
      }
      ChangeFilterItems(true);
      return true;
    }
    /*
      if (w == m_ObjectFilter)
      {
      m_RefreshFilterTimer.Run(0.85, this, "ChangeFilterItems", null, false);
      return true;
      }*/
    if (w == m_QuantityEditBox && (GetCurrentItemIndex() >= 0 || GetCurrentPresetName() != ""))
    {
      m_ConfigDebugProfile.SetItemQuantity(GetCurrentPresetName(), GetCurrentItemIndex(), m_QuantityEditBox.GetText().ToFloat());
      return true;
    }
    else if (w == m_DrawDistanceWidget)
    {
      DRAW_DISTANCE = m_DrawDistanceWidget.GetText().ToFloat();
      return true;
    }
    else if (w == m_DamageEditBox && (GetCurrentItemIndex() >= 0 || GetCurrentPresetName() != ""))
    {
      m_ConfigDebugProfile.SetItemHealth(GetCurrentPresetName(), GetCurrentItemIndex(), m_DamageEditBox.GetText().ToFloat());
      return true;
    }
    else if (w == m_WithPhysicsCheckbox && (GetCurrentItemIndex() >= 0 || GetCurrentPresetName() != ""))
    {
      m_ConfigDebugProfile.SetItemWithPhysics(GetCurrentPresetName(), GetCurrentItemIndex(), m_WithPhysicsCheckbox.IsChecked());
      return true;
    }
    else if (w == m_BatchSpawnQuantity)
    {
      m_ConfigDebugProfile.SetBatchSpawnQuantity(m_BatchSpawnQuantity.GetText().ToInt());
      return true;
    }
    else if ((w == m_RectSpawnRow || w == m_RectSpawnColumn || w == m_RectSpawnRowStep || w == m_RectSpawnColumnStep))
    {
      if (w == m_RectSpawnRow || w == m_RectSpawnColumn)
      {
        int rowQ = m_RectSpawnRow.GetText().ToInt();
        int columnQ = m_RectSpawnColumn.GetText().ToInt();
        int result = columnQ * rowQ;
        m_BatchSpawnQuantity.SetText(result.ToString());
        m_ConfigDebugProfile.SetBatchSpawnQuantity(m_BatchSpawnQuantity.GetText().ToInt());
      }
      if (m_ConfigDebugProfile)
        m_ConfigDebugProfile.SetBatchSpawnRectangle(m_RectSpawnRow.GetText().ToInt(), m_RectSpawnColumn.GetText().ToInt(), m_RectSpawnRowStep.GetText().ToFloat(), m_RectSpawnColumnStep.GetText().ToFloat());
      return true;
    }
    return false;
  }
References ARGB(), ChangeFilterItems(), CLEAR_IVN, DRAW_DISTANCE, GetCurrentItemIndex(), GetCurrentPresetName(), m_BatchSpawnQuantity, m_CategoryButtonsWidgets, m_CategoryMask, m_ClearInventory, ScriptConsoleTabBase::m_ConfigDebugProfile, m_DamageEditBox, m_DrawDistanceWidget, m_ObjectsScope, m_QuantityEditBox, m_RectSpawnColumn, m_RectSpawnColumnStep, m_RectSpawnRow, m_RectSpawnRowStep, m_ShowProtected, m_WithPhysicsCheckbox, Math::Pow(), x, and y.
OnClick()
override bool ScriptConsoleItemsTab::OnClick (Widget w, int x, int y, int button) inline protected
Definition at line 1103 of file ScriptConsoleItemsTab.c.
  {
    super.OnClick(w, x, y, button);
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    int objects_row_index;
    if (w == m_CategoryMergeType)
    {
      if (m_ConfigDebugProfile)
        m_ConfigDebugProfile.SetMergeType(m_CategoryMergeType.IsChecked());
      ChangeFilterItems(true);
      // Refresh UI by new settings
      m_MissionGameplay.GetHudDebug().RefreshByLocalProfile();
      return true;
    }
    else if (w == m_ObjectFilter)
    {
      ChangeFilterItems(true);
      return true;
    }
    else if (w == m_ItemPreviewCheckbox)
    {
      if (m_ConfigDebugProfile)
      {
        m_ConfigDebugProfile.SetShowItemPreview(m_ItemPreviewCheckbox.IsChecked());
        if (!m_ItemPreviewCheckbox.IsChecked())
          m_ItemPreviewWidget.SetItem(null);
      }
    }
    else if (w == m_SpawnInInvButton || w == m_SpawnGroundButton || w == m_SpawnOnTarget || w == m_SpawnOnCursor || w == m_SpawnInHands)
    {
      SaveProfileSpawnDistance();
      objects_row_index = m_ObjectsTextListbox.GetSelectedRow();
      vector rayStart = GetGame().GetCurrentCameraPosition();
      vector rayEnd = rayStart + GetGame().GetCurrentCameraDirection() * 50;
      vector hitPos;
      vector hitNormal;
      int hitComponentIndex;
      set<Object> hitObjects = new set<Object>;
      //DayZPhysics.RaycastRV(rayStart, rayEnd, hitPos, hitNormal, hitComponentIndex, hitObjects, NULL, player,);
      DayZPhysics.RaycastRV(rayStart, rayEnd, hitPos, hitNormal, hitComponentIndex, hitObjects, NULL, player, false, false, ObjIntersectView, 0.3);
      EntityAI target;
      if (hitObjects.Count())
        target = EntityAI.Cast(hitObjects.Get(0));
      if (m_SelectedObject != "")
      {
        // @NOTE: duplicate code in PluginDeveloper.c
        float distance = m_SpawnDistanceEditBox.GetText().ToFloat();
        if (m_SelectedObjectIsPreset == 1)
        {
          //------------ PRESETS -------------
          switch (w)
          {
          case m_SpawnOnTarget:
          {
            if (target && target.IsInherited(EntityAI))
            {
              EntityAI att_parent = EntityAI.Cast(target) ;
              SpawnPreset(att_parent, CLEAR_IVN, m_SelectedObject);
            }
            break;
          }
          case m_SpawnGroundButton:
          {
            SpawnPreset(player, false, m_SelectedObject, InventoryLocationType.GROUND, distance);
            break;
          }
          default:
          {
            SpawnPreset(player, CLEAR_IVN, m_SelectedObject);
            break;
          }
          }
        }
        else
        {
          //------------SINGLE ITEMS ------------
          float health = m_DamageEditBox.GetText().ToFloat() * MiscGameplayFunctions.GetTypeMaxGlobalHealth(m_SelectedObject);
          float quantity = m_QuantityEditBox.GetText().ToFloat();
          bool withPhysics = m_WithPhysicsCheckbox.IsChecked();
          bool spawnOnCrossHair = DeveloperFreeCamera.IsFreeCameraEnabled() || w == m_SpawnOnCursor;
          switch (w)
          {
          case m_SpawnGroundPatternGrid:
          {
            m_Developer.SpawnEntityOnCursorDir(player, m_SelectedObject, quantity, distance, health, m_IsShiftDown, "", withPhysics);
            break;
          }
          case m_SpawnOnTarget:
          {
            if (target && target.IsInherited(EntityAI))
              m_Developer.SpawnEntityInInventory(target, m_SelectedObject, health, quantity, m_IsShiftDown);
            break;
          }
          case m_SpawnInInvButton:
          {
            m_Developer.SpawnEntityInPlayerInventory(player, m_SelectedObject, -1, quantity, m_IsShiftDown);
            break;
          }
          case m_SpawnInHands:
          {
            m_Developer.SpawnEntityInPlayerInventory(player, m_SelectedObject, -1, quantity, m_IsShiftDown, "", FindInventoryLocationType.HANDS);
            break;
          }
          case m_SpawnOnCursor:
          case m_SpawnGroundButton:
          {
            if (spawnOnCrossHair)
              m_Developer.SpawnItemOnCrosshair(player, m_SelectedObject, health, quantity, 40, true, m_IsShiftDown, withPhysics);
            else
              m_Developer.SpawnEntityOnCursorDir(player, m_SelectedObject, quantity, distance, health, m_IsShiftDown, "", withPhysics);
            break;
          }
          }
        }
      }
      return true;
    }
    else if (w == m_FilterOrderButton)
    {
      SetFilterOrder(!m_FilterOrderReversed);
      return true;
    }
    else if (w == m_PresetsTextListbox)
    {
      SelectPreset();
      return true;
    }
    else if (w == m_PresetItemsTextListbox)
    {
      m_ObjectsTextListbox.SelectRow(-1);
      ShowItemButtons();
      ShowItemTransferButtons();
      m_SelectedObjectText.SetText("Object : " + GetCurrentItemName());
      SetObject(GetCurrentItemName());
      m_SelectedObjectIsPreset = 0;
      return true;
    }
    else if (w == m_PresetSetDefaultButton)
    {
      if (GetCurrentPresetName() != "")
        SetDefaultPreset(GetCurrentPresetIndex());
      return true;
    }
    else if (w == m_PresetNewButton)
    {
      g_Game.GetUIManager().EnterScriptedMenu(MENU_SCRIPTCONSOLE_DIALOG_PRESET_NAME, m_ScriptConsole);
      return true;
    }
    else if (w == m_PresetDeleteButton)
    {
      if (GetCurrentPresetName() != "")
        DeletePreset();
      return true;
    }
    else if (w == m_PresetRenameButton)
    {
      if (GetCurrentPresetName() != "")
        g_Game.GetUIManager().EnterScriptedMenu(MENU_SCRIPTCONSOLE_DIALOG_PRESET_RENAME, m_ScriptConsole);
      return true;
    }
    else if (w == m_PresetAddItemtButton)
    {
      AddItemToPreset();
      return true;
    }
    else if (w == m_ItemNameCopy)
    {
      AddItemToClipboard(m_ObjectsTextListbox);
      return true;
    }
    else if (w == m_PresetRemoveItemButton)
    {
      RemoveItemFromPreset();
      return true;
    }
    else if (w == m_ItemMoveUpButton)
    {
      ItemMoveUp();
      return true;
    }
    else if (w == m_ItemMoveDownButton)
    {
      ItemMoveDown();
      return true;
    }
    else if (w == m_SpawnBatchButton)
    {
      int count = m_BatchSpawnQuantity.GetText().ToInt();
      int rows = m_RectSpawnRow.GetText().ToInt();
      int columns = m_RectSpawnColumn.GetText().ToInt();
      float rowStep = m_RectSpawnRowStep.GetText().ToFloat();
      float columnStep = m_RectSpawnColumnStep.GetText().ToFloat();
      m_Developer.SpawnEntityOnGroundPatternGrid(player, m_SelectedObject, count, m_DamageEditBox.GetText().ToFloat(), 1, rows, columns, rowStep, columnStep, m_IsShiftDown, m_WithPhysicsCheckbox.IsChecked());
      return true;
    }
    else if (w == m_ListActions)
    {
      if (!m_PreviewEntity)
        return false;
      return ListItemRelatedActions();
    }
    else if (w == m_ObjectsTextListbox)
    {
      SelectObject();
      return true;
    }
    else if (w == m_DrawInWorld)
    {
      DrawItems(m_SelectedObject);
      return true;
    }
    else if (w == m_DrawInWorldClear)
    {
      DrawItemsClear();
      return true;
    }
    return false;
  }
References ScriptConsoleTabBase::AddItemToClipboard(), AddItemToPreset(), ChangeFilterItems(), CLEAR_IVN, DeletePreset(), DrawItems(), DrawItemsClear(), g_Game, GetCurrentItemName(), GetCurrentPresetIndex(), GetCurrentPresetName(), GetGame(), GetPlayer(), DeveloperFreeCamera::IsFreeCameraEnabled(), ItemMoveDown(), ItemMoveUp(), ListItemRelatedActions(), m_BatchSpawnQuantity, m_CategoryMergeType, ScriptConsoleTabBase::m_ConfigDebugProfile, m_DamageEditBox, m_Developer, m_DrawInWorld, m_DrawInWorldClear, m_FilterOrderButton, m_FilterOrderReversed, m_IsShiftDown, m_ItemMoveDownButton, m_ItemMoveUpButton, m_ItemNameCopy, m_ItemPreviewCheckbox, m_ItemPreviewWidget, m_ListActions, m_MissionGameplay, m_ObjectFilter, m_ObjectsTextListbox, m_PresetAddItemtButton, m_PresetDeleteButton, m_PresetItemsTextListbox, m_PresetNewButton, m_PresetRemoveItemButton, m_PresetRenameButton, m_PresetSetDefaultButton, m_PresetsTextListbox, m_PreviewEntity, m_QuantityEditBox, m_RectSpawnColumn, m_RectSpawnColumnStep, m_RectSpawnRow, m_RectSpawnRowStep, ScriptConsoleTabBase::m_ScriptConsole, m_SelectedObject, m_SelectedObjectIsPreset, m_SelectedObjectText, m_SpawnBatchButton, m_SpawnDistanceEditBox, m_SpawnGroundButton, m_SpawnGroundPatternGrid, m_SpawnInHands, m_SpawnInInvButton, m_SpawnOnCursor, m_SpawnOnTarget, m_WithPhysicsCheckbox, MENU_SCRIPTCONSOLE_DIALOG_PRESET_NAME, MENU_SCRIPTCONSOLE_DIALOG_PRESET_RENAME, DayZPhysics::RaycastRV(), RemoveItemFromPreset(), SaveProfileSpawnDistance(), SelectObject(), SelectPreset(), SetDefaultPreset(), SetFilterOrder(), ItemPreviewWidget::SetItem(), SetObject(), ShowItemButtons(), ShowItemTransferButtons(), SpawnPreset(), x, and y.
OnDoubleClick()
override bool ScriptConsoleItemsTab::OnDoubleClick (Widget w, int x, int y, int button) inline protected
Definition at line 1339 of file ScriptConsoleItemsTab.c.
  {
    super.OnDoubleClick(w, x, y, button);
    int i;
    int objects_row_index;
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (w == m_ObjectsTextListbox)
    {
      //select item
      m_PresetItemsTextListbox.SelectRow(-1);
      HideItemButtons();
      ShowItemTransferButtons();
      m_SelectedObjectText.SetText("Object : " + GetCurrentObjectName());
      m_SelectedObject = GetCurrentObjectName();
      m_LastSelectedObject = m_SelectedObject;
      m_SelectedObjectIsPreset = 0;
      //spawn item
      SaveProfileSpawnDistance();
      objects_row_index = m_ObjectsTextListbox.GetSelectedRow();
      vector rayStart = GetGame().GetCurrentCameraPosition();
      vector rayEnd = rayStart + GetGame().GetCurrentCameraDirection() * 1.5;
      vector hitPos;
      vector hitNormal;
      int hitComponentIndex;
      set<Object> hitObjects = new set<Object>;
      DayZPhysics.RaycastRV(rayStart, rayEnd, hitPos, hitNormal, hitComponentIndex, hitObjects, NULL, player);
      Object target = NULL;
      if (hitObjects.Count())
        target = hitObjects.Get(0);
      if (m_SelectedObject != "")
      {
        float distance = m_SpawnDistanceEditBox.GetText().ToFloat();
        if (button == 0) //LMB
        {
          m_Developer.SpawnEntityOnCursorDir(player, m_SelectedObject, 1, distance);
          return true;
        }
        else if (button == 1) //RMB
        {
          if (GetGame().IsMultiplayer())
            m_Developer.SpawnEntityInPlayerInventory(player, m_SelectedObject, -1, -1);
          else
          {
            EntityAI spawned_entity = m_Developer.SpawnEntityOnCursorDir(player, m_SelectedObject, -1, distance);
            player.LocalTakeEntityToHands(spawned_entity);
          }
          return true;
        }
        else if (button == 2) //MMB
        {
          m_Developer.SpawnEntityOnCursorDir(player, m_SelectedObject, 1, distance, -1, true);
          return true;
        }
      }
    }
    else if (w == m_QuantityEditBox)
    {
      m_QuantityEditBox.SetText("1.0");
      return true;
    }
    return false;
  }
References GetCurrentObjectName(), GetGame(), GetPlayer(), HideItemButtons(), m_Developer, m_LastSelectedObject, m_ObjectsTextListbox, m_PresetItemsTextListbox, m_QuantityEditBox, m_SelectedObject, m_SelectedObjectIsPreset, m_SelectedObjectText, m_SpawnDistanceEditBox, DayZPhysics::RaycastRV(), SaveProfileSpawnDistance(), ShowItemTransferButtons(), x, and y.
OnItemSelected()
override bool ScriptConsoleItemsTab::OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline protected
Definition at line 1071 of file ScriptConsoleItemsTab.c.
  {
    super.OnItemSelected(w, x, y, row, column, oldRow, oldColumn);
    if (w == m_PresetsTextListbox && (m_SelectedObjectIsPreset == 1 || m_SelectedObjectIsPreset == -1))
    {
      if (m_PresetsTextListbox.GetSelectedRow() != -1)
      {
        SelectPreset();
        return true;
      }
    }
    else if (w == m_PresetItemsTextListbox)
    {
      if (m_PresetItemsTextListbox.GetSelectedRow() != -1)
      {
        ShowItemButtons();
        ShowItemTransferButtons();
        m_SelectedObjectText.SetText(GetCurrentItemName());
        SetObject(GetCurrentItemName());
        m_SelectedObjectIsPreset = 0;
      }
      return true;
    }
    else if (w == m_ObjectsTextListbox)
    {
      SelectObject(false);
      return true;
    }
    return false;
  }
References GetCurrentItemName(), m_ObjectsTextListbox, m_PresetItemsTextListbox, m_PresetsTextListbox, m_SelectedObjectIsPreset, m_SelectedObjectText, SelectObject(), SelectPreset(), SetObject(), ShowItemButtons(), ShowItemTransferButtons(), x, and y.
OnKeyDown()
override bool ScriptConsoleItemsTab::OnKeyDown (Widget w, int x, int y, int key) inline protected
Definition at line 328 of file ScriptConsoleItemsTab.c.
  {
    if (key == KeyCode.KC_D && m_SelectedObject != "")
    {
      DrawItems(m_SelectedObject);
      return true;
    }
    else
      return super.OnKeyDown(w, x, y, key);
  }
References DrawItems(), m_SelectedObject, x, and y.
PrepareFilters()
void ScriptConsoleItemsTab::PrepareFilters (string filter, out TStringArray filters, out TIntArray colors) inline protected
Definition at line 836 of file ScriptConsoleItemsTab.c.
  {
    filter.Trim();
    filter.ToLower();
    filters = new TStringArray;
    TStringArray rawFilters = new TStringArray;
    filter.Split(" ", rawFilters);
    colors = new TIntArray;
    foreach (int i, string f: rawFilters)
    {
      int color = -1;
      if (f.IndexOf(":") == 1)//detect color prefix
      {
        string clr = f.Substring(0, 1);
        f = f.Substring(2, f.Length() - 2);//crop off color prefix
        color = GetFilterColor(clr);
      }
      else//autocolor
      {
        if (i % 2 == 1)
          color = ARGB(200, 255, 255, 255);
      }
      filters.Insert(f);
      colors.Insert(color);
    }
  }
References ARGB(), and GetFilterColor().
Referenced by ChangeFilter().
PreprocessFilterText()
string ScriptConsoleItemsTab::PreprocessFilterText (MultilineEditBoxWidget w) inline protected
Definition at line 1444 of file ScriptConsoleItemsTab.c.
  {
    string widgetText;
    w.GetText(widgetText);
    if (widgetText.Contains(","))
    {
      widgetText.Replace(",", " ");
      w.SetLine(0, widgetText);
    }
    return widgetText;
  }
Referenced by ChangeFilterItems().
RefreshLists()
void ScriptConsoleItemsTab::RefreshLists () inline protected
Definition at line 740 of file ScriptConsoleItemsTab.c.
  {
    RenderPresets();
    RenderPresetItems();
  }
References RenderPresetItems(), and RenderPresets().
Referenced by DeletePreset(), NewPreset(), and RenamePreset().
RemoveItemFromPreset()
void ScriptConsoleItemsTab::RemoveItemFromPreset () inline protected
Definition at line 695 of file ScriptConsoleItemsTab.c.
  {
    if (GetCurrentItemIndex() != -1 && GetCurrentPresetIndex() != -1)
    {
      m_ConfigDebugProfile.ItemRemoveFromPreset(GetCurrentPresetName(), GetCurrentItemIndex());
      RenderPresetItems();
    }
  }
References GetCurrentItemIndex(), GetCurrentPresetIndex(), GetCurrentPresetName(), ScriptConsoleTabBase::m_ConfigDebugProfile, and RenderPresetItems().
Referenced by OnClick().
RenamePreset()
void ScriptConsoleItemsTab::RenamePreset (string new_preset_name) inline protected
Definition at line 525 of file ScriptConsoleItemsTab.c.
  {
    if (new_preset_name && GetCurrentPresetIndex() != -1)
    {
      bool result = m_ConfigDebugProfile.PresetRename(GetCurrentPresetName(), new_preset_name);
      RefreshLists();
    }
  }
References GetCurrentPresetIndex(), GetCurrentPresetName(), ScriptConsoleTabBase::m_ConfigDebugProfile, and RefreshLists().
RenderPresetItems()
void ScriptConsoleItemsTab::RenderPresetItems () inline protected
Definition at line 780 of file ScriptConsoleItemsTab.c.
  {
    // load preset items list
    int i;
    m_PresetItemsTextListbox.ClearItems();
    if (GetCurrentPresetIndex() != -1)
    {
      bool isFixed = IsCurrentPresetFixed();
      TStringArray preset_array = new TStringArray;
      if (isFixed)
        m_ConfigDebugProfileFixed.GetPresetItems(GetCurrentPresetName(), preset_array);
      else
        m_ConfigDebugProfile.GetPresetItems(GetCurrentPresetName(), preset_array);
      if (preset_array)
      {
        for (i = 0; i < preset_array.Count(); i++)
          m_PresetItemsTextListbox.AddItem(preset_array.Get(i), NULL, 0);
      }
    }
  }
References GetCurrentPresetIndex(), GetCurrentPresetName(), IsCurrentPresetFixed(), ScriptConsoleTabBase::m_ConfigDebugProfile, ScriptConsoleTabBase::m_ConfigDebugProfileFixed, and m_PresetItemsTextListbox.
Referenced by AddItemToPreset(), Init(), ItemMoveDown(), ItemMoveUp(), RefreshLists(), RemoveItemFromPreset(), and SelectPreset().
RenderPresets()
void ScriptConsoleItemsTab::RenderPresets () inline protected
Definition at line 747 of file ScriptConsoleItemsTab.c.
  {
    m_PresetsTextListbox.ClearItems();
    int i;
    TBoolArray preset_params;
    // load custom presets list
    TStringArray custom_presets_array = m_ConfigDebugProfile.GetPresets();
    for (i = custom_presets_array.Count() - 1; i >= 0; i--)
      m_PresetsTextListbox.AddItem(custom_presets_array.Get(i), new PresetParams(custom_presets_array.Get(i), false, false), 0);
    // load fixed presets list
    TStringArray presets_array = m_ConfigDebugProfileFixed.GetPresets();
    for (i = 0; i < presets_array.Count(); i++)
      m_PresetsTextListbox.AddItem("[" + presets_array.Get(i) + "]", new PresetParams(presets_array.Get(i), true, false), 0);
    string default_preset = m_ConfigDebugProfile.GetDefaultPreset();
    if (default_preset != "")
    {
      // if is fixed
      int index = GetPresetIndexByName(default_preset);
      if (IsPresetFixed(default_preset))
        default_preset = "[" + default_preset + "]";
      PresetParams preset_params_array;
      if (index > -1 && index < m_PresetsTextListbox.GetNumItems())
      {
        m_PresetsTextListbox.GetItemData(index, 0, preset_params_array);
        m_PresetsTextListbox.SetItem(index, default_preset + CONST_DEFAULT_PRESET_PREFIX, preset_params_array, 0);
      }
    }
  }
References CONST_DEFAULT_PRESET_PREFIX, GetPresetIndexByName(), IsPresetFixed(), ScriptConsoleTabBase::m_ConfigDebugProfile, ScriptConsoleTabBase::m_ConfigDebugProfileFixed, and m_PresetsTextListbox.
Referenced by Init(), and RefreshLists().
SaveProfileSpawnDistance()
void ScriptConsoleItemsTab::SaveProfileSpawnDistance () inline protected
Definition at line 519 of file ScriptConsoleItemsTab.c.
  {
    if (m_ConfigDebugProfile && m_SpawnDistanceEditBox)
      m_ConfigDebugProfile.SetSpawnDistance(m_SpawnDistanceEditBox.GetText().ToFloat());
  }
References ScriptConsoleTabBase::m_ConfigDebugProfile, and m_SpawnDistanceEditBox.
Referenced by OnClick(), and OnDoubleClick().
SelectObject()
void ScriptConsoleItemsTab::SelectObject (bool hide_presets = true) inline protected
Definition at line 339 of file ScriptConsoleItemsTab.c.
  {
    if (hide_presets)
      m_PresetItemsTextListbox.SelectRow(-1);
    HideItemButtons();
    ShowItemTransferButtons();
    m_SelectedObjectText.SetText(GetCurrentObjectName());
    SetObject(GetCurrentObjectName());
    m_LastSelectedObject = m_SelectedObject;
    m_SelectedObjectIsPreset = 0;
  }
References GetCurrentObjectName(), HideItemButtons(), m_LastSelectedObject, m_PresetItemsTextListbox, m_SelectedObject, m_SelectedObjectIsPreset, m_SelectedObjectText, SetObject(), and ShowItemTransferButtons().
Referenced by OnClick(), and OnItemSelected().
SelectPreset()
void ScriptConsoleItemsTab::SelectPreset () inline protected
Definition at line 353 of file ScriptConsoleItemsTab.c.
  {
    m_ObjectsTextListbox.SelectRow(-1);
    RenderPresetItems();
    ShowPresetButtons();
    ShowItemTransferButtons();
    m_SelectedObject = GetCurrentPresetName();
    m_SelectedObjectText.SetText("Preset : " + m_SelectedObject);
    m_SelectedObjectIsPreset = 1;
    TStringArray command_array = new TStringArray;
    m_ConfigDebugProfileFixed.GetPresetItems(m_SelectedObject, command_array, "cmd");
    bool clear = !IsPresetFixed(m_SelectedObject);
    if (command_array.IsValidIndex(0))
    {
      string first_line = command_array.Get(0);
      first_line.ToLower();
      clear = (first_line == "clear_inv");
    }
    m_ClearInventory.SetChecked(clear);
  }
References GetCurrentPresetName(), IsPresetFixed(), m_ClearInventory, ScriptConsoleTabBase::m_ConfigDebugProfileFixed, m_ObjectsTextListbox, m_SelectedObject, m_SelectedObjectIsPreset, m_SelectedObjectText, RenderPresetItems(), ShowItemTransferButtons(), and ShowPresetButtons().
Referenced by Init(), OnClick(), and OnItemSelected().
SetDefaultPreset()
void ScriptConsoleItemsTab::SetDefaultPreset (int preset_index) inline protected
Definition at line 591 of file ScriptConsoleItemsTab.c.
  {
    // remove previous default parameter
    string default_preset = m_ConfigDebugProfile.GetDefaultPreset();
    if (default_preset != "")
    {
      int index = GetPresetIndexByName(default_preset);
      // if is fixed
      if (IsPresetFixed(default_preset))
        default_preset = "[" + default_preset + "]";
      PresetParams prev_preset_params_array;
      if (index > -1 && index < m_PresetsTextListbox.GetNumItems())
      {
        m_PresetsTextListbox.GetItemData(index, 0, prev_preset_params_array);
        prev_preset_params_array.param3 = false; // remove DEFAULT
        m_PresetsTextListbox.SetItem(index, default_preset, prev_preset_params_array, 0);
      }
    }
    // set preset on preset_index to default
    // if is fixed
    string preset_name = GetCurrentPresetName();
    if (IsPresetFixed(preset_name))
      preset_name = "[" + preset_name + "]";
    // set new default preset
    PresetParams preset_params_array;
    index = GetCurrentPresetIndex();
    if (index > -1 && index < m_PresetsTextListbox.GetNumItems())
    {
      m_PresetsTextListbox.GetItemData(index, 0, preset_params_array);
      preset_params_array.param3 = true; // DEFAULT
      m_PresetsTextListbox.SetItem(index, preset_name + CONST_DEFAULT_PRESET_PREFIX, preset_params_array, 0);
    }
    // store preset
    m_ConfigDebugProfile.SetDefaultPreset(GetCurrentPresetName());
  }
References CONST_DEFAULT_PRESET_PREFIX, GetCurrentPresetIndex(), GetCurrentPresetName(), GetPresetIndexByName(), IsPresetFixed(), ScriptConsoleTabBase::m_ConfigDebugProfile, and m_PresetsTextListbox.
Referenced by OnClick().
SetFilterOrder()
void ScriptConsoleItemsTab::SetFilterOrder (bool reversed) inline protected
Definition at line 972 of file ScriptConsoleItemsTab.c.
  {
    m_FilterOrderReversed = reversed;
    if (reversed)
      m_FilterOrderImage.SetRotation(0, 0, 180, true);
    else
      m_FilterOrderImage.SetRotation(0, 0, 0, true);
    ChangeFilterItems(true);
    if (m_ConfigDebugProfile)
      m_ConfigDebugProfile.SetFilterOrderReversed(reversed);
  }
References ChangeFilterItems(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_FilterOrderImage, and m_FilterOrderReversed.
Referenced by Init(), and OnClick().
SetObject()
void ScriptConsoleItemsTab::SetObject (string object) inline protected
Definition at line 628 of file ScriptConsoleItemsTab.c.
  {
    m_SelectedObject = object;
    if (m_ConfigDebugProfile && m_ConfigDebugProfile.GetShowItemPreview())
      SetPreviewObject(object);
  }
References ScriptConsoleTabBase::m_ConfigDebugProfile, m_SelectedObject, and SetPreviewObject().
Referenced by Init(), OnClick(), OnItemSelected(), and SelectObject().
SetPreviewObject()
void ScriptConsoleItemsTab::SetPreviewObject (string object) inline protected
Definition at line 637 of file ScriptConsoleItemsTab.c.
  {
#ifdef DEVELOPER
    if (m_PreviewEntity)
      m_PreviewEntity.Delete();
    if (!GetGame().IsKindOf(object, "DZ_LightAI") && !GetGame().IsKindOf(object, "Man"))
    {
      DayZGame.m_IsPreviewSpawn = true;
      m_PreviewEntity = EntityAI.Cast(GetGame().CreateObjectEx(object, "0 0 0", ECE_LOCAL | ECE_CREATEPHYSICS | ECE_TRACE));
      DayZGame.m_IsPreviewSpawn = false;
      if (m_PreviewEntity)
      {
        dBodyDestroy(m_PreviewEntity);//prevents cars from acting up when spawned this way(we only want the preview pic, no physics required)
        m_PreviewEntity.DisableSimulation(true);
        m_ItemPreviewWidget.SetItem(m_PreviewEntity);
        m_PreviewEntity.SetAllowDamage(false);
      }
    }
#endif
  }
References dBodyDestroy(), ECE_CREATEPHYSICS, ECE_LOCAL, ECE_TRACE, GetGame(), m_ItemPreviewWidget, m_PreviewEntity, and ItemPreviewWidget::SetItem().
Referenced by SetObject().
SetTextSpawnButton()
void ScriptConsoleItemsTab::SetTextSpawnButton (ButtonWidget w, bool special, string suffix = " Special") inline protected
Definition at line 1421 of file ScriptConsoleItemsTab.c.
  {
    string text = m_SpawnButtonsOriginalText.Get(w);
    if (special)
      text += suffix;
    w.SetText(text);
  }
References m_SpawnButtonsOriginalText.
Referenced by UpdateButtonNames().
ShowItemButtons()
void ScriptConsoleItemsTab::ShowItemButtons () inline protected
Definition at line 426 of file ScriptConsoleItemsTab.c.
  {
    if (!IsCurrentPresetFixed())
    {
      ShowItemTransferButtons();
      string preset_name = GetCurrentPresetName();
      int item_index = GetCurrentItemIndex();
      m_ItemMoveUpButton.Show(true);
      m_ItemMoveDownButton.Show(true);
      m_ItemDamageLabel.Show(true);
      m_ItemQuantityLabel.Show(true);
      if (preset_name != "" && item_index > -1)
      {
        m_DamageEditBox.Show(true);
        m_QuantityEditBox.Show(true);
        m_WithPhysicsCheckbox.Show(true);
        float item_health = m_ConfigDebugProfile.GetItemHealth(GetCurrentPresetName(), GetCurrentItemIndex());
        int item_quantity = m_ConfigDebugProfile.GetItemQuantity(GetCurrentPresetName(), GetCurrentItemIndex());
        bool item_with_physics = m_ConfigDebugProfile.GetItemWithPhysics(GetCurrentPresetName(), GetCurrentItemIndex());
        // damage
        m_DamageEditBox.SetText(item_health.ToString());
        // quantity
        m_QuantityEditBox.SetText(item_quantity.ToString());
        // with physics
        m_WithPhysicsCheckbox.SetChecked(item_with_physics);
      }
      else
      {
        m_DamageEditBox.Show(false);
        m_QuantityEditBox.Show(false);
        m_WithPhysicsCheckbox.Show(false);
      }
    }
  }
References GetCurrentItemIndex(), GetCurrentPresetName(), IsCurrentPresetFixed(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_DamageEditBox, m_ItemDamageLabel, m_ItemMoveDownButton, m_ItemMoveUpButton, m_ItemQuantityLabel, m_QuantityEditBox, m_WithPhysicsCheckbox, and ShowItemTransferButtons().
Referenced by OnClick(), and OnItemSelected().
ShowItemTransferButtons()
void ScriptConsoleItemsTab::ShowItemTransferButtons () inline protected
Definition at line 476 of file ScriptConsoleItemsTab.c.
  {
    int object_row = m_ObjectsTextListbox.GetSelectedRow();
    if (object_row > -1 && GetCurrentPresetIndex() > -1 && !IsCurrentPresetFixed())
      m_PresetAddItemtButton.Show(true);
    else
      m_PresetAddItemtButton.Show(false);
    if (GetCurrentItemIndex() > -1 && GetCurrentPresetIndex() > -1 && !IsCurrentPresetFixed())
      m_PresetRemoveItemButton.Show(true);
    else
      m_PresetRemoveItemButton.Show(false);
    if (object_row > -1)
      m_ItemNameCopy.Show(true);
    else
      m_ItemNameCopy.Show(false);
  }
References GetCurrentItemIndex(), GetCurrentPresetIndex(), IsCurrentPresetFixed(), m_ItemNameCopy, m_ObjectsTextListbox, m_PresetAddItemtButton, and m_PresetRemoveItemButton.
Referenced by Init(), OnClick(), OnDoubleClick(), OnItemSelected(), SelectObject(), SelectPreset(), and ShowItemButtons().
ShowPresetButtons()
void ScriptConsoleItemsTab::ShowPresetButtons () inline protected
Definition at line 672 of file ScriptConsoleItemsTab.c.
  {
    bool show = true;
    if (IsCurrentPresetFixed())
      show = false;
    m_PresetDeleteButton.Show(show);
    m_PresetRenameButton.Show(show);
    HideItemButtons();
  }
References HideItemButtons(), IsCurrentPresetFixed(), m_PresetDeleteButton, and m_PresetRenameButton.
Referenced by SelectPreset().
SpawnPreset()
void ScriptConsoleItemsTab::SpawnPreset (EntityAI target, bool clear_inventory, string preset_name, InventoryLocationType location = InventoryLocationType.ATTACHMENT, float distance = 0) inline protected
Definition at line 535 of file ScriptConsoleItemsTab.c.
  {
    // spawn preset items into inventory
    PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
    if (GetCurrentPresetIndex() != -1)
    {
      bool is_preset_fixed = IsCurrentPresetFixed();
      TStringArray preset_array = new TStringArray;
      if (is_preset_fixed)
        m_ConfigDebugProfileFixed.GetPresetItems(preset_name, preset_array);
      else
        m_ConfigDebugProfile.GetPresetItems(preset_name, preset_array);
      if (clear_inventory)
        m_Developer.ClearInventory(target);
      for (int i = 0; i < preset_array.Count(); i++)
      {
        float health = -1;
        int quantity = 1;
        bool with_physics = false;
        if (is_preset_fixed)
        {
          health = m_ConfigDebugProfileFixed.GetItemHealth(preset_name, i);
          quantity = m_ConfigDebugProfileFixed.GetItemQuantity(preset_name, i);
          with_physics = m_ConfigDebugProfileFixed.GetItemWithPhysics(preset_name, i);
        }
        else
        {
          health = m_ConfigDebugProfile.GetItemHealth(preset_name, i);
          quantity = m_ConfigDebugProfile.GetItemQuantity(preset_name, i);
          with_physics = m_ConfigDebugProfile.GetItemWithPhysics(preset_name, i);
        }
        if (location == InventoryLocationType.ATTACHMENT)
          EntityAI ent = m_Developer.SpawnEntityInInventory(target, preset_array.Get(i), -1, quantity, false, preset_name);
        //m_Developer.SpawnEntityAsAttachment(player, target, preset_array.Get(i), -1, quantity, false, preset_name);
        else if (location == InventoryLocationType.GROUND)
          m_Developer.SpawnEntityOnCursorDir(player, preset_array.Get(i), quantity, distance, health, false, preset_name, with_physics);
      }
      if (GetGame().IsMultiplayer())
      {
        ScriptRPC rpc = new ScriptRPC();
        rpc.Write(preset_name);
        rpc.Write(target);
        rpc.Send(player, ERPCs.DEV_RPC_SPAWN_PRESET, true, player.GetIdentity());
      }
      else
      {
        PluginDeveloper plugin = PluginDeveloper.Cast(GetPlugin(PluginDeveloper));
        plugin.HandlePresetSpawn(player, preset_name, target);
      }
    }
  }
References GetCurrentPresetIndex(), GetGame(), GetPlayer(), GetPlugin(), IsCurrentPresetFixed(), ScriptConsoleTabBase::m_ConfigDebugProfile, ScriptConsoleTabBase::m_ConfigDebugProfileFixed, and m_Developer.
Referenced by OnClick().
Update()
override void ScriptConsoleItemsTab::Update (float timeslice) inline protected
Definition at line 1412 of file ScriptConsoleItemsTab.c.
  {
    m_IsShiftDown = KeyState(KeyCode.KC_LSHIFT) || KeyState(KeyCode.KC_RSHIFT);
    UpdateButtonNames();
    super.Update(timeslice);
  }
References KeyState(), m_IsShiftDown, and UpdateButtonNames().
UpdateButtonNames()
void ScriptConsoleItemsTab::UpdateButtonNames () inline protected
Definition at line 1429 of file ScriptConsoleItemsTab.c.
  {
    SetTextSpawnButton(m_SpawnGroundButton, m_IsShiftDown);
    SetTextSpawnButton(m_SpawnInInvButton, m_IsShiftDown);
    SetTextSpawnButton(m_SpawnOnTarget, m_IsShiftDown);
    SetTextSpawnButton(m_SpawnOnCursor, m_IsShiftDown);
    SetTextSpawnButton(m_SpawnBatchButton, m_IsShiftDown);
    SetTextSpawnButton(m_SpawnInHands, m_IsShiftDown);
  }
References m_IsShiftDown, m_SpawnBatchButton, m_SpawnGroundButton, m_SpawnInHands, m_SpawnInInvButton, m_SpawnOnCursor, m_SpawnOnTarget, and SetTextSpawnButton().
Referenced by Update().
Member Data Documentation
CLEAR_IVN
bool ScriptConsoleItemsTab::CLEAR_IVN static protected
Definition at line 10 of file ScriptConsoleItemsTab.c.
Referenced by OnChange(), and OnClick().
CONST_DEFAULT_PRESET_PREFIX
const string ScriptConsoleItemsTab::CONST_DEFAULT_PRESET_PREFIX = "[Default]" protected
Definition at line 5 of file ScriptConsoleItemsTab.c.
Referenced by RenderPresets(), and SetDefaultPreset().
DRAW_DISTANCE
float ScriptConsoleItemsTab::DRAW_DISTANCE = 1000 static protected
Definition at line 9 of file ScriptConsoleItemsTab.c.
Referenced by DrawItems(), Init(), and OnChange().
ITEMS_IN_PRESET_SELECTED_ROW
int ScriptConsoleItemsTab::ITEMS_IN_PRESET_SELECTED_ROW static protected
Definition at line 8 of file ScriptConsoleItemsTab.c.
Referenced by Init(), and ~ScriptConsoleItemsTab().
ITEMS_SELECTED_ROW
int ScriptConsoleItemsTab::ITEMS_SELECTED_ROW = -1 static protected
Definition at line 6 of file ScriptConsoleItemsTab.c.
Referenced by Init(), and ~ScriptConsoleItemsTab().
m_BatchSpawnQuantity
EditBoxWidget ScriptConsoleItemsTab::m_BatchSpawnQuantity protected
Definition at line 68 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnChange(), OnClick(), and ScriptConsoleItemsTab().
m_CategoryButtonsNames
ref array<string> ScriptConsoleItemsTab::m_CategoryButtonsNames = {"FIREARMS", "MELEE", "ATTACHMENTS", "MAGAZINES", "AMMO", "FOOD", "MEDICAL", "CARS", "BACKPACKS", "B-BUILDING"} protected
Definition at line 21 of file ScriptConsoleItemsTab.c.
{"FIREARMS", "MELEE", "ATTACHMENTS", "MAGAZINES", "AMMO", "FOOD", "MEDICAL", "CARS", "BACKPACKS", "B-BUILDING"};
Referenced by Init().
m_CategoryButtonsWidgets
ref array<Widget> ScriptConsoleItemsTab::m_CategoryButtonsWidgets = new array<Widget> protected
Definition at line 20 of file ScriptConsoleItemsTab.c.
Referenced by Init(), and OnChange().
m_CategoryMask
int ScriptConsoleItemsTab::m_CategoryMask protected
Definition at line 23 of file ScriptConsoleItemsTab.c.
Referenced by ChangeFilterItems(), Init(), OnChange(), and ~ScriptConsoleItemsTab().
m_CategoryMergeType
CheckBoxWidget ScriptConsoleItemsTab::m_CategoryMergeType protected
Definition at line 32 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnClick(), and ScriptConsoleItemsTab().
m_ClearInventory
CheckBoxWidget ScriptConsoleItemsTab::m_ClearInventory protected
Definition at line 35 of file ScriptConsoleItemsTab.c.
Referenced by OnChange(), ScriptConsoleItemsTab(), and SelectPreset().
m_DamageEditBox
EditBoxWidget ScriptConsoleItemsTab::m_DamageEditBox protected
Definition at line 67 of file ScriptConsoleItemsTab.c.
Referenced by OnChange(), OnClick(), ScriptConsoleItemsTab(), and ShowItemButtons().
m_DebugShapes
ref array<Shape> ScriptConsoleItemsTab::m_DebugShapes = new array<Shape> static protected
Definition at line 14 of file ScriptConsoleItemsTab.c.
Referenced by DrawItems(), and DrawItemsClear().
m_Developer
PluginDeveloper ScriptConsoleItemsTab::m_Developer protected
Definition at line 26 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), OnDoubleClick(), ScriptConsoleItemsTab(), and SpawnPreset().
m_DrawDistanceWidget
EditBoxWidget ScriptConsoleItemsTab::m_DrawDistanceWidget protected
Definition at line 65 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnChange(), and ScriptConsoleItemsTab().
m_DrawInWorld
ButtonWidget ScriptConsoleItemsTab::m_DrawInWorld protected
Definition at line 39 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), and ScriptConsoleItemsTab().
m_DrawInWorldClear
ButtonWidget ScriptConsoleItemsTab::m_DrawInWorldClear protected
Definition at line 40 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), and ScriptConsoleItemsTab().
m_FilterOrderButton
ButtonWidget ScriptConsoleItemsTab::m_FilterOrderButton protected
Definition at line 50 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), and ScriptConsoleItemsTab().
m_FilterOrderImage
ImageWidget ScriptConsoleItemsTab::m_FilterOrderImage protected
Definition at line 74 of file ScriptConsoleItemsTab.c.
Referenced by ScriptConsoleItemsTab(), and SetFilterOrder().
m_FilterOrderReversed
bool ScriptConsoleItemsTab::m_FilterOrderReversed protected
Definition at line 27 of file ScriptConsoleItemsTab.c.
Referenced by ChangeFilter(), OnClick(), and SetFilterOrder().
m_FilterTextPrev
string ScriptConsoleItemsTab::m_FilterTextPrev protected
Definition at line 30 of file ScriptConsoleItemsTab.c.
Referenced by ChangeFilterItems().
m_IsShiftDown
bool ScriptConsoleItemsTab::m_IsShiftDown protected
Definition at line 29 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), Update(), and UpdateButtonNames().
m_ItemDamageLabel
TextWidget ScriptConsoleItemsTab::m_ItemDamageLabel protected
Definition at line 70 of file ScriptConsoleItemsTab.c.
Referenced by ScriptConsoleItemsTab(), and ShowItemButtons().
m_ItemMoveDownButton
ButtonWidget ScriptConsoleItemsTab::m_ItemMoveDownButton protected
Definition at line 49 of file ScriptConsoleItemsTab.c.
Referenced by HideItemButtons(), OnClick(), ScriptConsoleItemsTab(), and ShowItemButtons().
m_ItemMoveUpButton
ButtonWidget ScriptConsoleItemsTab::m_ItemMoveUpButton protected
Definition at line 48 of file ScriptConsoleItemsTab.c.
Referenced by HideItemButtons(), OnClick(), ScriptConsoleItemsTab(), and ShowItemButtons().
m_ItemNameCopy
ButtonWidget ScriptConsoleItemsTab::m_ItemNameCopy protected
Definition at line 46 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), ScriptConsoleItemsTab(), and ShowItemTransferButtons().
m_ItemPreviewCheckbox
CheckBoxWidget ScriptConsoleItemsTab::m_ItemPreviewCheckbox protected
Definition at line 33 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnClick(), and ScriptConsoleItemsTab().
m_ItemPreviewWidget
ItemPreviewWidget ScriptConsoleItemsTab::m_ItemPreviewWidget protected
Definition at line 73 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), ScriptConsoleItemsTab(), and SetPreviewObject().
m_ItemQuantity
float ScriptConsoleItemsTab::m_ItemQuantity = 1 static protected
Definition at line 16 of file ScriptConsoleItemsTab.c.
Referenced by Init(), and ~ScriptConsoleItemsTab().
m_ItemQuantityLabel
TextWidget ScriptConsoleItemsTab::m_ItemQuantityLabel protected
Definition at line 71 of file ScriptConsoleItemsTab.c.
Referenced by ScriptConsoleItemsTab(), and ShowItemButtons().
m_LastSelectedObject
string ScriptConsoleItemsTab::m_LastSelectedObject static protected
Definition at line 12 of file ScriptConsoleItemsTab.c.
Referenced by GetLastSelectedObject(), Init(), OnDoubleClick(), and SelectObject().
m_ListActions
ButtonWidget ScriptConsoleItemsTab::m_ListActions protected
Definition at line 58 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), and ScriptConsoleItemsTab().
m_MissionGameplay
MissionGameplay ScriptConsoleItemsTab::m_MissionGameplay protected
Definition at line 24 of file ScriptConsoleItemsTab.c.
Referenced by Init(), and OnClick().
m_ObjectFilter
MultilineEditBoxWidget ScriptConsoleItemsTab::m_ObjectFilter protected
Definition at line 59 of file ScriptConsoleItemsTab.c.
Referenced by ChangeFilterItems(), Init(), OnClick(), and ScriptConsoleItemsTab().
m_ObjectsScope
int ScriptConsoleItemsTab::m_ObjectsScope = 2 static protected
Definition at line 11 of file ScriptConsoleItemsTab.c.
Referenced by ChangeFilter(), Init(), and OnChange().
m_ObjectsTextListbox
TextListboxWidget ScriptConsoleItemsTab::m_ObjectsTextListbox protected
Definition at line 36 of file ScriptConsoleItemsTab.c.
Referenced by AddItemToPreset(), ChangeFilterItems(), GetCurrentObjectName(), Init(), OnClick(), OnDoubleClick(), OnItemSelected(), ScriptConsoleItemsTab(), SelectPreset(), ShowItemTransferButtons(), and ~ScriptConsoleItemsTab().
m_PresetAddItemtButton
ButtonWidget ScriptConsoleItemsTab::m_PresetAddItemtButton protected
Definition at line 45 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), ScriptConsoleItemsTab(), and ShowItemTransferButtons().
m_PresetDeleteButton
ButtonWidget ScriptConsoleItemsTab::m_PresetDeleteButton protected
Definition at line 42 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnClick(), ScriptConsoleItemsTab(), and ShowPresetButtons().
m_PresetItemsTextListbox
TextListboxWidget ScriptConsoleItemsTab::m_PresetItemsTextListbox protected
Definition at line 38 of file ScriptConsoleItemsTab.c.
Referenced by GetCurrentItemIndex(), GetCurrentItemName(), Init(), ItemMoveDown(), ItemMoveUp(), OnClick(), OnDoubleClick(), OnItemSelected(), RenderPresetItems(), ScriptConsoleItemsTab(), SelectObject(), and ~ScriptConsoleItemsTab().
m_PresetNewButton
ButtonWidget ScriptConsoleItemsTab::m_PresetNewButton protected
Definition at line 41 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), and ScriptConsoleItemsTab().
m_PresetRemoveItemButton
ButtonWidget ScriptConsoleItemsTab::m_PresetRemoveItemButton protected
Definition at line 47 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), ScriptConsoleItemsTab(), and ShowItemTransferButtons().
m_PresetRenameButton
ButtonWidget ScriptConsoleItemsTab::m_PresetRenameButton protected
Definition at line 43 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnClick(), ScriptConsoleItemsTab(), and ShowPresetButtons().
m_PresetSetDefaultButton
ButtonWidget ScriptConsoleItemsTab::m_PresetSetDefaultButton protected
Definition at line 44 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), and ScriptConsoleItemsTab().
m_PresetsTextListbox
TextListboxWidget ScriptConsoleItemsTab::m_PresetsTextListbox protected
Definition at line 37 of file ScriptConsoleItemsTab.c.
Referenced by GetCurrentPresetIndex(), GetCurrentPresetName(), GetPresetIndexByName(), Init(), IsCurrentPresetFixed(), IsPresetFixed(), OnClick(), OnItemSelected(), RenderPresets(), ScriptConsoleItemsTab(), SetDefaultPreset(), and ~ScriptConsoleItemsTab().
m_PreviewEntity
EntityAI ScriptConsoleItemsTab::m_PreviewEntity static protected
Definition at line 15 of file ScriptConsoleItemsTab.c.
Referenced by ListItemRelatedActions(), OnClick(), SetPreviewObject(), and ~ScriptConsoleItemsTab().
m_QuantityEditBox
EditBoxWidget ScriptConsoleItemsTab::m_QuantityEditBox protected
Definition at line 66 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnChange(), OnClick(), OnDoubleClick(), ScriptConsoleItemsTab(), ShowItemButtons(), and ~ScriptConsoleItemsTab().
m_RectSpawnColumn
EditBoxWidget ScriptConsoleItemsTab::m_RectSpawnColumn protected
Definition at line 62 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnChange(), OnClick(), and ScriptConsoleItemsTab().
m_RectSpawnColumnStep
EditBoxWidget ScriptConsoleItemsTab::m_RectSpawnColumnStep protected
Definition at line 64 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnChange(), OnClick(), and ScriptConsoleItemsTab().
m_RectSpawnRow
EditBoxWidget ScriptConsoleItemsTab::m_RectSpawnRow protected
Definition at line 61 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnChange(), OnClick(), and ScriptConsoleItemsTab().
m_RectSpawnRowStep
EditBoxWidget ScriptConsoleItemsTab::m_RectSpawnRowStep protected
Definition at line 63 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnChange(), OnClick(), and ScriptConsoleItemsTab().
m_RefreshFilterTimer
ref Timer ScriptConsoleItemsTab::m_RefreshFilterTimer = new Timer() protected
Definition at line 25 of file ScriptConsoleItemsTab.c.
Referenced by Init(), and ~ScriptConsoleItemsTab().
m_SelectedObject
string ScriptConsoleItemsTab::m_SelectedObject protected
Definition at line 28 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnClick(), OnDoubleClick(), OnKeyDown(), SelectObject(), SelectPreset(), and SetObject().
m_SelectedObjectIsPreset
int ScriptConsoleItemsTab::m_SelectedObjectIsPreset = -1 static protected
Definition at line 13 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnClick(), OnDoubleClick(), OnItemSelected(), SelectObject(), and SelectPreset().
m_SelectedObjectText
TextWidget ScriptConsoleItemsTab::m_SelectedObjectText protected
Definition at line 72 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnClick(), OnDoubleClick(), OnItemSelected(), ScriptConsoleItemsTab(), SelectObject(), and SelectPreset().
m_ShowProtected
CheckBoxWidget ScriptConsoleItemsTab::m_ShowProtected protected
Definition at line 34 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnChange(), and ScriptConsoleItemsTab().
m_SpawnBatchButton
ButtonWidget ScriptConsoleItemsTab::m_SpawnBatchButton protected
Definition at line 57 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), ScriptConsoleItemsTab(), and UpdateButtonNames().
m_SpawnButtonsOriginalText
ref map<Widget, string> ScriptConsoleItemsTab::m_SpawnButtonsOriginalText = new map<Widget, string>() protected
Definition at line 22 of file ScriptConsoleItemsTab.c.
Referenced by ScriptConsoleItemsTab(), and SetTextSpawnButton().
m_SpawnDistanceEditBox
EditBoxWidget ScriptConsoleItemsTab::m_SpawnDistanceEditBox protected
Definition at line 60 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnClick(), OnDoubleClick(), SaveProfileSpawnDistance(), and ScriptConsoleItemsTab().
m_SpawnGroundButton
ButtonWidget ScriptConsoleItemsTab::m_SpawnGroundButton protected
Definition at line 52 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), ScriptConsoleItemsTab(), and UpdateButtonNames().
m_SpawnGroundPatternGrid
ButtonWidget ScriptConsoleItemsTab::m_SpawnGroundPatternGrid protected
Definition at line 53 of file ScriptConsoleItemsTab.c.
Referenced by OnClick().
m_SpawnInHands
ButtonWidget ScriptConsoleItemsTab::m_SpawnInHands protected
Definition at line 56 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), ScriptConsoleItemsTab(), and UpdateButtonNames().
m_SpawnInInvButton
ButtonWidget ScriptConsoleItemsTab::m_SpawnInInvButton protected
Definition at line 51 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), ScriptConsoleItemsTab(), and UpdateButtonNames().
m_SpawnOnCursor
ButtonWidget ScriptConsoleItemsTab::m_SpawnOnCursor protected
Definition at line 55 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), ScriptConsoleItemsTab(), and UpdateButtonNames().
m_SpawnOnTarget
ButtonWidget ScriptConsoleItemsTab::m_SpawnOnTarget protected
Definition at line 54 of file ScriptConsoleItemsTab.c.
Referenced by OnClick(), ScriptConsoleItemsTab(), and UpdateButtonNames().
m_WithPhysics
bool ScriptConsoleItemsTab::m_WithPhysics = false static protected
Definition at line 17 of file ScriptConsoleItemsTab.c.
Referenced by Init(), and ~ScriptConsoleItemsTab().
m_WithPhysicsCheckbox
CheckBoxWidget ScriptConsoleItemsTab::m_WithPhysicsCheckbox protected
Definition at line 69 of file ScriptConsoleItemsTab.c.
Referenced by Init(), OnChange(), OnClick(), ScriptConsoleItemsTab(), ShowItemButtons(), and ~ScriptConsoleItemsTab().
PRESETS_SELECTED_ROW
int ScriptConsoleItemsTab::PRESETS_SELECTED_ROW = 0 static protected
Definition at line 7 of file ScriptConsoleItemsTab.c.
Referenced by Init(), and ~ScriptConsoleItemsTab().
The documentation for this class was generated from the following file:
scripts/5_Mission/GUI/ScriptConsoleItemsTab.c